### ISSUE TITLE
Interfaces de Desarrollo

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#1]
¿Se puede usar Anaconda en vez de las otras interfaces recomendadas? Es el que tengo que usar en otro curso y además ya trae instalados pip, matplotlib, numpy y muchos otros paquetes

**Comment by jtagle2** [comment]
Puedes usar lo que tu quieras, siempre y cuando tengas lo mínimo para poder desarrollar las actividades y tareas del curso (Python, PyQt5) y entregarlas (git). El resto es a preferencia del consumidor.
Saludos

**Comment by mjgutierrez1** [comment]
Ok, Gracias
