### ISSUE TITLE
Problema Visual Studio Code

### ISSUE THREAD

**Issue by IsidoraCarmona** [IIC2233/Syllabus#1]
No se como correr un codigo en Visual Studio Code, he visto que en otros computadores les aparece un boton para poder correrlo en la parte superior derecha, pero en el mio no sale, solo me aparece una opcion que dice run and debug, pero no me corre el codigo al apretarlo. Ahi añadi una foto de como se ve en mi computador.
![image](https://github.com/IIC2233/Syllabus/assets/162645031/41d7a1e7-c443-4c61-845e-7c09c97189c4)

**Comment by Hernan4444** [comment]
Hola @IsidoraCarmona 

Esperando que estés bien, una posuble causa de todo esto es que al archivo que tienes se llama "prueba" y no "prueba.py". Por lo tanto VScode no reconoce que es un archivo del tipo Python. 

De todas formas, VSCode (Visual Studio Code) es una herramienta para crear y modificar el código, pero en este curso, la forma de ejecutar los archivos no será desde VSCode, así que no te preocupes por esta situación. **Para ejecutar cualquier archivo Python, se utilizará la terminal/consola/CMD.** Por lo tanto, haremos todo lo posible para ayudarlos a lograr ese objetivo, pero si alguien quiere de todas formas hacerlo desde VSCode (que no la forma de este curso), no vamos a poder guiarlos. Más adelante en el curso se explicará por qué ejecutamos todo desde la terminal/consola/CMD.

Ahora bien, digamos que tienes una carpeta (o directorio, como es usualmente conocido) con un archivo llamado `main.py`.    En la siguiente imagen tengo justamente un directorio llamado `prueba` que contiene un archivo llamado `main.py`:

![image](https://github.com/IIC2233/Syllabus/assets/15641721/4d8dca65-d038-47b2-a92b-55c828eaa01a)


Para ejecutar **desde terminal**:

1. Primero hay abrir tu terminal (CMD) en la carpeta que contenga tu archivo .py que deseas ejecutar. Para esto, recomiendo ver [este enlace si usas Windows](https://es.wikihow.com/abrir-una-carpeta-en-la-ventana-de-comandos) o [este enlace si usas Mac](https://www.solvetic.com/tutoriales/article/6463-como-abrir-terminal-con-una-carpeta-especifica-en-mac-os/) donde se explica cómo hacerlo. Otra opción es utilizar el comando `cd` que lo enseñaremos en los contenidos semana 01 apenas se publiquen. Aunque por mientras puedes ver [la wiki](https://github.com/IIC2233/Syllabus/wiki/7.-Comandos-de-Terminal-relevantes) donde ahí tambien explica cómo se utiliza el comando `cd`.

2. Una vez que tu terminal está en la carpeta deseada, hacer `py main.py` para ejecutar el archivo. A veces `py main.py` no funciona, y hay que probar con `python3 main.py`, `py3 main.py` o `python main.py`. Con una de esos 4 comandos harás que Python se ejecute desde tu terminal. Te recomiendo recordar con cuál de los 4 comandos te funcionó para seguir utilizándolo por el resto del semestre.

Esta será la forma de ejecutar cada archivo durante el semestre, y desde la clase 1 (la otra semana) lo pondremos en practica para que todos estemos alineados con esta forma.

Si es que tienes problemas con ejecutar desde terminal, te recomiendo abrir otra issue para apoyarte en ese proceso 👍 

Saludosヾ(＾-＾)ノ

**Comment by Hernan4444** [comment]
Hola @IsidoraCarmona 

Recuerda que en las [reglas del foro, punto 8](https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)) que les pedimos leer al momento de contestar el formulario dice que no cierres la issue. Solo que comentes que fue resuelta.

Así que volveré a abrir esta issue para que los demás compañeros puedan verla. Más adelante el cuerpo docente cerrará está issue.
