### ISSUE TITLE
Error 404 en link de "Introducción al curso"

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#1]
Hola!

En la página [Introducción al curso](https://github.com/IIC2233/Syllabus/wiki/Introducción-al-curso), el link [guía del foro](https://github.com/IIC2233/Syllabus/Gu%C3%ADa-del-Foro) lanza un error 404. El link es "https://github.com/IIC2233/Syllabus/Gu%C3%ADa-del-Foro", mientras que el correcto es "https://github.com/IIC2233/Syllabus/wiki/Gu%C3%ADa-del-Foro".

Saludos, Alejandro.

**Comment by bamavrakis** [comment]
Hola! muchas gracias por avisar! lo arreglaremos a la brevedad ;).
Saludos!

Enviado desde mi iPhone

El 01-03-2017, a las 08:51, Alejandro Kaminetzky <notifications@github.com<mailto:notifications@github.com>> escribió:


Hola!

En la página Introducción al curso<https://github.com/IIC2233/Syllabus/wiki/Introducci%C3%B3n-al-curso>, el link guía del foro<https://github.com/IIC2233/Syllabus/Gu%C3%ADa-del-Foro> lanza un error 404.

Saludos, Alejandro.

**Comment by akaminetzkyp** [comment]
No hay problema. Feliz de ayudar! :)

**Comment by aaossa** [comment]
Arregla345
