### ISSUE TITLE
os.path.join me retorna dos backslashes y no uno para un path

### ISSUE THREAD

**Issue by crow-rojas** [IIC2233/syllabus#10]
¡Hola! Estoy programando la parte de los savegames de la T00 y al querer portabilizar el programa con os.path, el método open de archivos al ingresarle el path obtenido con os.path.join me tira un error diciendo que no se encuentra la ruta específicamente mostrando \\, pero si imprimo os.path.join antes del open la ruta se encuentra bien con un \.

Busqué en google pero hay información muy vaga respecto a esto. Espero alguien sepa que pueda ser, ¡gracias!

**Comment by StroveLight** [comment]
Hola! Eso se debe a como el computador interpreta los strings

El string '\\' corresponde a un string especial (llamada escape secuence), que significa que despues de este caracter viene una instruccion especial (Probablemente recuerdes el '\n' de Intro a Progra)
 
El hecho de que el computador los muestre como '\\\\' se debe a que así lee el primer "\\", y sabe que se viene una instruccion especial, pero luego lee el segundo "\\", y así sabe lo que realmente representa el "\\\\": un string "\\"

Para decirle al computador si es que quieres que lea el string tal y como "se ve", puedes usar el raw string, que se escribe agregando una "r" antes del inicio del string, por ejemplo, r"string\"

Dato freak: github tiene esta misma situacion, así que creo que desaparecieron algunos de tus "\\" de la pregunta (o así se ve desde mi computador)

He aquí un ejemplo de la situación:
![image](https://user-images.githubusercontent.com/48263952/62837985-1ce3cd00-bc44-11e9-9dea-9c933ac62485.png)

PD: si quieres saber cuales son las "escape secuences", puedes ver la [documentación](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals)

**Comment by crow-rojas** [comment]
Hola @StroveLight, gracias por responder. Tenía un poco conocimiento sobre lo que me dices pero era muy poco, con tu explicación me lo dejaste más claro. Sin embargo, seguí investigando más y Python debería intrepretar el path correctamente con os.path.join, pero sigue sin hacerlo. Mira, aquí hice un ejemplo:

![1](https://user-images.githubusercontent.com/53796435/62838510-47855400-bc4b-11e9-874f-1d5805310b8c.png)
![2](https://user-images.githubusercontent.com/53796435/62838512-49e7ae00-bc4b-11e9-83cb-8af8ba0e02dc.png)

Donde ejecuto el script de python, tengo la carpeta llamada 'carpeta', pido un input y luego abro un archivo inexistente (por eso lo abrí con 'w'), además que tengo el print del path, que está con un \, y luego en el argumento de open ocurre el error, porque lo reconoce como dos \, y eso no sé por qué ocurre. En teoría el código está bien escrito :/ Por cierto, estoy editando código con Visual Studio Code.

Alguna idea? Gracias!

**Comment by lily416** [comment]
Hola @crow-rojas 😄 

Prueba utilizando [`os.path.normpath`](https://docs.python.org/3/library/os.path.html#os.path.normpath), teóricamente dicha función debería cambiar los `\\` por `/`.

Ojalá te funcione 🙏

**Comment by crow-rojas** [comment]
Hola @lily416,

Lo intenté y aquí está el resultado, ocurre lo mismo :/

![3](https://user-images.githubusercontent.com/53796435/62839060-0f820f00-bc53-11e9-81f3-79af452a2c93.png)
![4](https://user-images.githubusercontent.com/53796435/62839066-190b7700-bc53-11e9-8447-1f24fc1786d7.png)

Igualmente ya ejecuté el script con el IDLE nativo de Python y no me da ningún error, se crea el archivo sin problemas, es raro. VS Code en su extensión de Python debe tener algun problema con los archivos y open. Tendré que usar otro editor por mientras.

**Comment by crow-rojas** [comment]
Y sí, es problema de VS Code, probé con Pycharm ahora y se me genera el archivo sin problemas.

¡Gracias por la ayuda! Igual si alguno ocupa VS Code, tiene el mismo problema y sabe como solucionarlo sería genial.

¡Saludos!

**Comment by jmwielandt** [comment]
Hola!
Eso es porque el error imprime el path como "raw", por eso aparecen los dos `\`.

![imagen](https://user-images.githubusercontent.com/37153467/62839124-b8306e80-bc53-11e9-8624-fdc050c7114e.png)

Haz un print del directorio en el que estás, con `print(os.getcwd())`. Además, un `print(os.listdir, sep='\n')` para ver qué archivos tienes en el directorio donde estás corriendo python.

Dime qué te retorna, probablemente estés ejecutando tu archivo en un lugar distinto al que crees.

Saludos!~

**Comment by crow-rojas** [comment]
Hola! @jmwielandt

Al parecer ese es el problema, al printear los métodos que me dijiste con VS Code, me di cuenta que al ejecutar con 'Run Code in Terminal', el script se está corriendo en otro lado, no en el mismo directorio del script.  Ahora a ver como soluciono eso.

**Comment by jmwielandt** [comment]
Hola!

Estaba escribiendo una segunda respuesta, pero me ganaste 🙈 La solución está más abajo.
>Aquí te pongo un ejemplo de cómo lo repliqué.
Abro VSCode en el escritorio, e intento ejecutar un archivo que está en `desktop/cosa_ej`, que abre un archivo que está en el mismo path que el `a.py`.
Ahora, lo que pasa es que python intenta buscar el archivo `'desktop/otro.txt'`, cuando debería estar buscando el archivo `'desktop/cosa_ej/otro.txt'`.
![imagen](https://user-images.githubusercontent.com/37153467/62839246-9df79000-bc55-11e9-8003-9f438bb0ab78.png)


La solución más fácil es:

![imagen](https://user-images.githubusercontent.com/37153467/62839293-40177800-bc56-11e9-964e-f7acdbe4011f.png)

Otra es que con la consola de vscode navegues hasta el directorio correcto y ejecutes a mano el archivo (`python nombre_archivo.py`). 'Run Code in Terminal' te mueve al sitio en el que abriste vscode antes de ejecutarlo.

Saludos!

**Comment by crow-rojas** [comment]
@jmwielandt abrir vscode del directorio solucionó todo, gracias por la solución!
