### ISSUE TITLE
Duda con ejemplo Properties

### ISSUE THREAD

**Issue by Panckx** [IIC2233/Syllabus#10]
Hola! Estaba viendo los contenidos de Properties y en la celda en que se define la clase Puente con decoradores algo no está funcionando bien, porque luego de que se setea la cantidad de personas en el puente a 10, se le restan 15 personas y quedan 5 personas, lo que no hace mucho sentido. De hecho está ocurriendo algo totalmente distinto, como se puede apreciar en el mismo código algo modificado:

```python
"""
Implementación de un puente.
"""


class Puente:  # pylint: disable=too-few-public-methods

    """Esta clase modela el funcionamiento de un puente."""

    def __init__(self, maximo):
        self.maximo = maximo
        self.__personas = 0

    @property
    def personas(self):
        """Retorna la cantidad de personas en el puente."""
        return self.__personas

    @personas.setter
    def personas(self, suma):
        print('Sumando {}'.format(suma))
        if self.__personas + suma > self.maximo:
            print('Se le suma {}, pero se pasa del máximo'.format(suma))
            self.__personas = self.maximo
        elif self.__personas + suma < 0:
            print('Se le suma {}, pero se pasa del mínimo'.format(suma))
            self.__personas = 0
        else:
            print('Se le suma {}, está dentro del rango'.format(suma))
            self.__personas += suma
        print()


PUENTE = Puente(10)
print('Sumar 7:')
PUENTE.personas += 7
print('Sumar 5:')
PUENTE.personas += 5
print('Sumar -15:')
PUENTE.personas -= 15
```

Mi pregunta entonces es, cómo se pueden usar los decoradores en el mismo ejemplo para poder usar la suma como parte de la propiedad?

**Comment by jecastro1** [comment]
Buen comentario!

Tal y como tú dices, el comportamiento mostrado en el código no es lo que se buscaba. Eso se produce porque al hacer:

```python
PUENTE.personas += 7
```

Eso equivale a:

```python
PUENTE.personas = PUENTE.personas + 7
```

Por lo tanto, lo primero que hace es **obtener** el valor `PUENTE.personas` desde el _getter_, le sumamos 7 y ese valor se lo pasamos al _setter_. En esa línea el _getter_ de `PUENTE.personas` retorna 0, pues no habíamos hecho nada antes. Entonces, el valor que entra al _setter_ es 7. Ahí funciona como se espera.

Sin embargo, en la siguiente línea al hacer:

```python
PUENTE.personas += 5
```
el valor que entra al _setter_ es 12, pues la expresión equivale a ```PUENTE.personas = PUENTE.personas + 5``` y el _getter_ esta vez devuelve 7. 

Como en el código se interpreta que el valor que entra al _setter_ es lo que queremos sumar, entonces significa que estuvimos intentando poner ¡19 personas en el puente! (12 + 7 que ya estaban)

En este caso, ponemos el límite de 10 personas en el puente y seteamos ese valor.

Luego, al tratar de sacar 15 personas del puente, uno espera que el puente quede vacío. Tal y como está el código esto no ocurre, pues ```PUENTE.personas -= 15``` equivale a ```PUENTE.personas = PUENTE.personas - 15``` que queda en ```10 - 5 = -5```.  Tal y como habíamos dicho antes, en el código se está interpretando el valor que llega al _setter_ como algo a sumar, por lo que estamos quitando 5 personas. 

Vamos a modificar el ejemplo para que no los confunda. Espero que haya quedado clara la situación, de no ser así te invito a seguir preguntando.

Muchas gracias, saludos

**Comment by Panckx** [comment]
Muchas gracias, me quedó muy claro!

**Comment by julioag** [comment]
Hola , estuve leyendo la explicación pero no me quedó claro la forma en que debiese alterar los atributos y que las properties se respeten??
gracias
