### ISSUE TITLE
Window 11, Python

### ISSUE THREAD

**Issue by IgnacioParraguez** [IIC2233/Syllabus#10]
- **Sistema Operativo:**
- **Programa a instalar:**

- Foto del error:
![image](https://github.com/IIC2233/Syllabus/assets/110941492/ce5d7e2d-65b6-4369-b09c-6fbd53e224e2)

- Descripción del problema:
- no encuentro la aplicacion de python en el computador para poder realizar el paso que me dicen en la foto enviada

**Comment by Dvckhv** [comment]
Hola @IgnacioParraguez ! , sigue estos pasos:
- Abre una consola, para ello escribe cmd en tu buscador y hacele click
- en consola escribe ` wsl `, te deberia abrir una terminal de Linux
- escribe `python3`, te abrirá un entorno de python en consola
-  en el entorno escribe la linea en cuestión y presiona Enter
- Para salir de el entorno escribe `exit()`
Cuentame si te sirvió :)
