### ISSUE TITLE
Cómo instalar y ejecutar Jupyter Notebook

### ISSUE THREAD

**Issue by LucaSpiniello** [IIC2233/syllabus#10]
- **Sistema Operativo:** windows 10
- **Programa a instalar:** jupyter

- Foto del error:

- Descripción del problema: abro pip y este se cierra automatica e inmediatamente.

**Comment by benjavicente** [comment]
Probablemente estés abriendo pip en el buscador de Windows, pero pip se ejecuta en el [Símbolo del sistema](https://es.wikipedia.org/wiki/S%C3%ADmbolo_del_sistema). Abre `cmd` y ahí ejecutas el comando `pip install jupyter`.  [[Documentación pip]](https://pip.pypa.io/en/stable/user_guide/#running-pip)

**Comment by LucaSpiniello** [comment]
si, eso es lo que me estaba, pero ejecute " pip install jupyter", en el
simbolo del sistema, luego me arrojo como output un codigo muy grande con
descargas y otras cosas, lo cual probablemente esta bien pero jupyter no me
aparece en el buscardor, es normal?

**Comment by LucaSpiniello** [comment]
debo hacer algo mas luego de ejecutar lo que te dije para que se descarge
realmente jupyter?

**Comment by benjavicente** [comment]
> debo hacer algo mas luego de ejecutar lo que te dije para que se descarge
realmente jupyter?

Jupyter ya debe estar instalado. Puedes verificarlo ejecutando `jupyter --v`, donde se imprimirán las versiones de los diferentes *componentes* de Jupyter. Cuando ejecuto ese comando, yo obtengo:
```
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.1
ipython          : 7.13.0
ipykernel        : 5.1.4
jupyter client   : 6.0.0
jupyter lab      : 2.0.1
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3
```
Para abrir un editor, puedes ejecutar `jupyter notebook` o `jupyter lab` (El último es el editor más nuevo), pero este se abre en una carpeta predeterminada. 
**Para ejecutarlo en la carpeta *Contenidos*, esto es lo que encontré:**

## Usando Jupyter Notebook
- En `cmd` ejecuta `jupyter notebook --notebook-dir="{path}"`, donde `{path}` es la dirección al directorio de contenidos (Ej: `D:\IIC2233\contenidos`).
- Luego copias uno de los links que aparecen y lo abres en el navegador.
- Se abrirá una ventana como esta:
![image](https://user-images.githubusercontent.com/62021328/76694749-a1bd1c00-6655-11ea-91b8-6cdbd270d4ec.png)

## Usando Jupyter Lab
- Similar a con Jupyter notebook, en `cmd` ejecuta `jupyter lab --notebook-dir="{path}"`.
- Abres uno de los links, y se abrirá una ventana como esta:
![image](https://user-images.githubusercontent.com/62021328/76694862-cc5ba480-6656-11ea-9624-f573ce4b44d7.png)

* Para cambiar la ubicación por defecto y no tener que usar `--notebook-dir="{path}"` cada vez puedes seguir [estas instrucciones](https://stackoverflow.com/a/40514875).  

## Usando Visual Studio Code
- Abre el directorio o el archivo en vsCode (Se puede ejecutar `code "{path}"` o usar "Abrir con Code" en el [menú contextual](https://es.wikipedia.org/wiki/Men%C3%BA_contextual).
- Al abrir por primera vez un *jupyter notebook* (`.ipynb`) se iniciará un "Jupyter Server". Puede que no se abra inmediatamente y tengas que re-abrir el archivo.
- vsCode se vería así:
![image](https://user-images.githubusercontent.com/62021328/76695050-eb5b3600-6658-11ea-9399-b9f39b8775a8.png)
*pd: no soy ayudante : |*

**Comment by LucaSpiniello** [comment]
muchas gracias te pasaste
