### ISSUE TITLE
En Mac: problemas con el setup_test.py de la instalación de python y git

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#10]
Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Problema
Seguí el video de la instalación de Python y Qt Designer, iba bien hasta ver si estaban instalado correctamente con el comando python3.8 setup_test.py
Esto es un copy/paste del terminal

''''
Last login: Sat Aug 21 20:01:42 on ttys002

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Fernandas-MacBook-Air:~ fernandadelpinozegers$ cd
Fernandas-MacBook-Air:~ fernandadelpinozegers$ python3.8 setup_test.py
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8: can't open file 'setup_test.py': [Errno 2] No such file or directory
Fernandas-MacBook-Air:~ fernandadelpinozegers$ progra avanzada
-bash: progra: command not found
Fernandas-MacBook-Air:~ fernandadelpinozegers$ cd progra avanzada
-bash: cd: progra: No such file or directory
Fernandas-MacBook-Air:~ fernandadelpinozegers$ 
''''

El archivo setup_test.py lo tengo en documentos, en una carpeta que se llama 'progra avanzada'

**Comment by pedroriosg** [comment]
@Fernanda1232123 pudiste resolver el problema?

Saludos

**Comment by Fernanda1232123** [comment]
Sí, ya está resuelto! Gracias
