### ISSUE TITLE
Instalación PyQt5 Mac OS

### ISSUE THREAD

**Issue by mmsaavedra1** [IIC2233/Syllabus#10]
¿Existe alguna diferencia al instalar PyQt5, en Mac OS, con alguno de los siguientes comandos?

`pip3 install PyQt5`

`brew install pyqt5 --with-python3` (Es la que aparece en la wiki)

**Comment by akaminetzkyp** [comment]
No debería haber diferencia alguna.

Saludos!

**Comment by jerosalazar** [comment]
hola, yo instale PyQt5 pero al poner import PyQt5 no me funciona. Llego a esto pero no se que mas hacer
https://github.com/IIC2233/Syllabus/issues/2

**Comment by Arcoirisky** [comment]
si lo hiciste por pip, a veces pasa y es horrible. entra en la página de
Python y baja el .html correspondiente, eso lo instalas directo de la
consola con "install <nombre archivo>" y debería funcionar bien

**Comment by Arcoirisky** [comment]
Si no me entendiste voy a mirar bien y te mando la página, a ver si te sirve

**Comment by Arcoirisky** [comment]
Pregunta (Perdón pero soy Windows, me di cuenta tarde que era para Mac 😅) Estaba viendo y necesitas Python 2 aún cuando instalas Python 3 porque sino tu Mac deja de funcionar bien ¿No habrás instalado el paquete en el 2? 
Sabía que en la consola, con Python 3 -m pip y todo lo que sigue debería dejarlo en el 3.6

Intenta ver si funciona en el Python 2 

¡Suerte!

**Comment by ifcarrera** [comment]
Hola!
¿Lo instalaste usando `pip3` en lugar de solamente `pip`?
Saludos
