### ISSUE TITLE
Solución ayudantia 1, ejercicio final

### ISSUE THREAD

**Issue by RositaMunoz** [IIC2233/syllabus#10]
Hola!
En el enunciado del ejercicio final de la ayudantia 1, dice que si la acción es "liberar" se elimina el primer pokemon capturado, pero en la pauta hacen .pop() a la lista que contiene los pokemons, entonces, según yo, se estaría eliminando el último pokemon capturado. Estaría bien?

Saludos!

**Comment by Mahund** [comment]
Hola @RositaMunoz !

Efectivamente, es un error en la versión de la ayudantía, la forma correcta es utilizando:

```python
ayudantes[ayudante].popleft()
```

Saludos!
