### ISSUE TITLE
macOS: Problemas con Jupyter y Qt Designer

### ISSUE THREAD

**Issue by diegobustosk** [IIC2233/syllabus#10]
Hola cuando intento ejecutar jupyter note book, me arroja "zsh: command not found: jupyter". Busque como arreglarlo y no pude.
Ademas no me deja poder usar Qt Designer me aparece un alert que dice "·Qt Designer” no se puede abrir porque no se puede verificar el desarrollador."

**Comment by tocococa** [comment]
Hola @diegobustosk! Puedes darme un par de datos más? Tienes instalada Anaconda y que SO estás usando? Y que pasa si corres el comando `jupyter --version`?

**Comment by diegobustosk** [comment]
Estoy usando macOS y como terminal zsh. Cuando corro el comando jupyter --version me sigue apareciendo  "zsh: command not found: jupyter" . No tengo instalado anaconda solo tengo python con la versión 3.7

**Comment by tocococa** [comment]
Okap, puedes cambiar a bash con `exec bash` y una vez en bash, escribir `jupyter lab`? 

Respecto a tu problema con Qt Designer, te recomiendo leer las instrucciones de [esta página](https://support.apple.com/en-us/HT202491) para que puedas abrir un programa no verificado".

**Comment by diegobustosk** [comment]
Lo acabo de hacer y me dice bash: jupyter: command not found

**Comment by tocococa** [comment]
Yap, me da la impresión que puede ser que no hayas instalado Jupyter o te hayas saltado algún paso. Por favor revisa la guía de instalación (https://iic2233.github.io/wiki/software) y me avisas cómo te va.

**Comment by diegobustosk** [comment]
Hola lo intente de nuevo y tampoco resulto, por lo que vi en internet es un problema del path pero no se como solucionarlo. Encontre este comando que me abre el notebook "python -m notebook" no tengo idea porque pero funciona

**Comment by diegobustosk** [comment]
Este es el link que me ayudo https://www.thetopsites.net/article/53362303.shtml

**Comment by tomasgv** [comment]
¡Hola @diegobustosk!

Dado que funciona `python -m notebook` para abrir Jupyter Notebook, entonces probablemente hubo un problema durante la instalación, y Jupyter terminó en un directorio perteneciente a la versión de Python 2.7 😱  (la que viene por defecto en macOS). ¡No te preocupes! Cosas así son muy frecuentes, especialmente porque queramos o no, contamos con más de una versión de Python (**no** intentes desinstalar la 2.7, cosas malas pueden pasar).

Primero, intenta desinstalar Jupyter, lo cual depende del comando que hayas usado al principio: puede ser `python -m pip install jupyter` o `python3 -m pip install jupyter`.

Una vez hecho esto, prueba hacer `pip3 install --upgrade pip` y luego `pip3 install jupyter`. Usando `pip3` nos aseguraremos de no usar Python 2.7.

Cuéntame cómo te va después de hacer esto, y en caso de que aún no funcione, recuerda que el próximo martes habrá una ayudantía dedicada a instalación, donde podrás tener una ayuda más rápida y efectiva 🚀 .

¡Saludos! 😄

**Comment by igbasly** [comment]
@diegobustosk, complementando lo que mis compañeros indican y dado que estás usando la terminal con zsh, es possible que también hayan habido problemas con el path de Python. Te invito a que leas lo que dejé en la issue #5 para solucionar este problema.

Mucho éxito 🚀
