### ISSUE TITLE
Actividad 9 de Marzo

### ISSUE THREAD

**Issue by pggodoy** [IIC2233/Syllabus#10]
Hola, en un curso me dijeron que el jueves no va a haber luz en gran parte del campus ¿Esto afectará de alguna forma la actividad de ese día?

**Comment by cruz** [comment]
El grupo de ayudantes estará durante esa hora pedaleando en unas bicicletas 🚴‍♀️ 🚴 🚴‍♀️ 🚴  para generar energía para ustedes, así que no habrá problema.









Recientemente se informó que el corte de luz será el día viernes, por lo tanto la actividad del jueves se desarrollará de manera normal. 🎉 🎉 🎉 🎉 

Saludos,

**Comment by bamavrakis** [comment]
Yo me estaba enchulando para el pedaleo :(

**Comment by akaminetzkyp** [comment]
Hola!

Si todavía necesitan personas para pedalear, yo podría sacrificarme a cambio de un simple 7 en la actividad.

Saludos,
Alejandro Kaminetzky
