### ISSUE TITLE
Solo se imprime el nombre de la variable no lo que contiene

### ISSUE THREAD

**Issue by rominaarancibia** [IIC2233/Syllabus#100]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

**hola! recientemente me ha ocurrido que al correr el código para probar funciones, por ejemplo que me de la solución de un tablero que estoy probando debería imprimir en la consola el tablero solucionado, pero en su lugar solo imprime "tablero solucionado" en esta. Ya probé reiniciando mi computador y buscando en internet pero no encuentro nada. Además, hace esto mismo para cualquier variable que le pido. Gracias **

**Comment by rominaarancibia** [comment]
Hola! Ya lo subí el problema ocurre al probar el archivo functions.py en el rango de lineas 100 y 147 (funcion solucionar tableros). Luego de probar esta, además que no imprime el tablero de prueba que esta ahí ocurre que al probar las otras funciones les empieza a pasar lo mismo en conjunto con las variables relacionadas a esta. muchas gracias quedo atenta :)

**Comment by cegalleta** [comment]
Hola!! Estuve revisando tu código y no veo problemas con como usas la función para imprimir, sin embargo, al solucionar el tablero, tu código entra en un loop infinito. Uno de los problemas que veo a simple vista es que cuando en tu función ```solucionar_tablero```, tu variable ```probar_vecinos``` nunca deja de ser ```True``` en el último "while". Quizás podrías partir por ahí. Para ver si es que tu código ejecuta alguna parte del código en la que tengas dudas, trata de poner muchos 'print' para identificar qué está pasando.

Me avisas como te va y perdón por la demora.

**Comment by cegalleta** [comment]
Una cosa! 

Tienes varios 'while' anidados en un 'for' gigante, no está necesariamente mal, pero se presta para errores hacerlo así! En caso de que aún tengas tiempo y ganas, podrías intentar adaptar un poco esa función para que utilice recursión! Así cuando hagas un cambio en el tablero, le pasas a la misma función el tablero modificado y te ahorras verificar más condiciones.

No es obligación que lo hagas así, es sólo una sugerencia.

**Comment by rominaarancibia** [comment]
Hola! Apliqué la sugerencia y me sigue pasando lo mismo:C ahora lo voy a subir esta entre las lineas 124 y 153. Se nota cuando en el archivo main.py y correr las lineas 57, 65 y 66 diciendo luego del print zsh: killed     /usr/local/bin/python y luego zsh: command not found: tablero_solucionado. Muchas gracias!

**Comment by rominaarancibia** [comment]
Actualizado mi repositorio para que puedas ver:( muchas gracias

**Comment by Hernan4444** [comment]
Hola @rominaarancibia 

Justo estaba sapeando tu código (🐸) y lo que ocurre es que dentro de tu función para solucionar todo, llamas a `celdas_vecinas_validas`. Dentro de esa función tienes un `while probar_siguiente:` y dentro de dicho `while`, nunca cambia el valor de `probar_siguiente` por lo tanto siempre es True, es decir, el `while` nunca acaba. Esto hace que tu programa nunca termine. Si en la línea 233 pones un `print("uwu")`, en tu consola aparecerán muchos `uwu` porque ese loop seguirá funcionando hasta el final,

Cómo menciona cegalleta, al tener tantos loops (for y while) metidos dentro de otro, puedes haber errores del tipo que un loop nunca acabe. Tal vez sería bueno evaluar paso a paso lo que hace cada línea para verificar que haga justamente lo que tu quieres y no otra cosa.

Saludos c:
