### ISSUE TITLE
Duda descuento readme

### ISSUE THREAD

**Issue by prochotito-rises** [IIC2233/syllabus#100]
Hola, acabo de caer en la cuenta que olvidé por completo subir el README .-.
Qué es lo que pasa en este caso? Porque según los descuentos, me bajan una décima por un README incompleto, pero yo no hice nada .-.
Disculpa ayudantes correctores por darles más pega ;(, juro que lo olvidé por completo

**Comment by tavalenzuelag** [comment]
Me pasó exactamente lo mismo! El problema es que es absolutamente necesario que suba el README para que el ayudante sepa el formato de los archivos.txt sino tendrá problema para revisar la tarea.
Subo el README no más?

**Comment by entamburini** [comment]
¡Hola! :)

Súbanlo igual, porque así los ayudantes tendrán menos problemas corrigiéndoles ;). Es preferible el descuento que pongamos a que no podamos entender su tarea :sweat: (a parte por el readme es super chico :eyes:
