### ISSUE TITLE
Buenas Prácticas: docstring

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#100]
Hola! Revisando las buenas prácticas y la Guía de Estilo, no encontré nada relacionado con la descripción de funciones con comentarios """comentario""". Es evaluado esto en las tareas?

**Comment by gatochico** [comment]
Hola! Las triple comas a las que te refieres se llaman **docstring**. Estos corresponden a _strings_ que usualmente se ponen al inicio de un módulo, una función, una clase, o un método, y tienen como fin servir como **la documentación oficial de dicho módulo/clase/etc.**, ya que son lo que retorna el atributo `__ doc __` de un objeto, o al llamar a `help(nombre_funcion_documentada)`.

El usar docstrings no es evaluado en las tareas ni pedido de forma obligatoria, pero al igual que cualquier tipo de comentario en el código, ayudan al corrector a entender tu tarea! 🤓

**Comment by dlmed** [comment]
Gracias!

**Comment by dlmed** [comment]
Y el espacio entre imports y def o entre def y esas cosas?

**Comment by gatochico** [comment]
Tampoco se descuenta  si no se utiliza, pero nuevamente, ayuda a mantener todo mas ordenado. 

En el link de [descuentos](https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md) se indica todas las reglas de PEP8 que sí se evaluan (idealmente revisar en cada tarea, ya que pueden estar sujetas a cambios)
