### ISSUE TITLE
Duda con opción solucionar tablero en el menú.

### ISSUE THREAD

**Issue by gaspar-mr05** [IIC2233/Syllabus#100]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. Tengo una duda con la opción (3) de solucionar tablero en el menú. Esta opción debe printear el tablero solucionado? o solo lo actualiza para que luego con la opción (1) se pueda ver visualizado?

**Comment by mtaguero** [comment]
¡Hola @gaspar-mr05!

Te recomiendo revisar bien el método `solucionar` que está en la página N°7 del enunciado.
Nota que en la parte final dice:

 "La solución se debe generar a partir del tablero entregado. **Importante:** este método genera un nuevo tablero solucionado, no modifica el tablero original."

En este caso, cuando seleccionas la opción "mostrar tablero" (1), entonces debería verse el tablero cargado previamente y no el solucionado. De este modo, al seleccionar la opción "solucionar tablero" (3) podrías printear el tablero solucionado o llevar a cabo otra acción según estimes conveniente.

Recuerda que si algo del enunciado no es claro, pero a ti te hace sentido, puedes dejar en tu README una sección de supuestos y consideraciones mencionando qué decisiones tomaste y por qué.

Avísame si quedó claro.

¡Éxito! 🎈
