### ISSUE TITLE
Duda orden de las columnas de los .csv

### ISSUE THREAD

**Issue by AndresGarciadelaHuerta** [IIC2233/Syllabus#100]
Hola! Tengo una duda con respecto al orden de las columnas de los archivos .csv que nos dieron. ¿Este orden será el mismo para las columnas de los .csv que usarán para revisar? Es decir, para el caso del users.csv por ejemplo, la primera columna son las orders, después fecha nacimiento, nombre usuario, nombre y apellido. ¿O nuestro programa debe ser capaz de identificar cada cosa en el archivo, independiente de las columnas en las que se encuentre en el .csv? (Me refiero a que cuando revisen quizás puede que el orden cambie y vaya primero apellido por ejemplo). Muchas gracias!

**Comment by fnquinteros** [comment]
No asumas que el orden será el mismo. Podríamos corregir con un csv con columnas en desorden... o no... quién sabe 😜
