### ISSUE TITLE
[Corto] Sobre la blank line al final de unos .csv

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#100]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### 3: Eliminar directamente la newline de los archivos contactos.csv y grupos.csv 

Hago la pregunta ya que al ser mi primera tarea no sé si descuentan por detalles como este, y me vi tentado a hacer la \# 3, sin embargo asumo que no podemos modificar los archivos base sin previo aviso, ¿no?

Saludos!

**Comment by IgnaciaJ** [comment]
Hola @fernandosmither ! Te recomiendo que hagas la segunda opción, sin embargo no es necesario volver a ponerla, ya que los ayudantes correctores van a tener el mismo archivo csv que tienes de base para correr tu tarea y luego este se  editará según lo que establezca tu programa, por lo que cambiarlo directamente del csv no es efectivo en el caso de corrección de tu tarea.

**Comment by fernandosmither** [comment]
> Hola @fernandosmither ! Te recomiendo que hagas la segunda opción, sin embargo no es necesario volver a ponerla, ya que los ayudantes correctores van a tener el mismo archivo csv que tienes de base para correr tu tarea y luego este se editará según lo que establezca tu programa, por lo que cambiarlo directamente del csv no es efectivo en el caso de corrección de tu tarea.

Vale, igual me preocupó el tema debido a que el linter me avisó sobre siempre dejar una newline al final de los archivos, [como aquí](https://www.flake8rules.com/rules/W292.html), entonces no sabía si eso también podría evaluarse. Asumo que no, entonces.

Muchas gracias!

**Comment by IgnaciaJ** [comment]
@fernandosmither en verdad da igual como lo quieras trabajar(puedes agregarle el espacio al final si quieres), ya que no es algo que nosotros evaluaremos para esta tarea, por lo que trabajalo como tu estimes conveniente :) Éxito en tu tarea!
