### ISSUE TITLE
Ataque

### ISSUE THREAD

**Issue by Nitsuga69** [IIC2233/syllabus#100]
Hola!

Si civ. A ataca a civ. B en el turno 1 y A tiene mayor poder total de ataque que el poder total de defensa de B, es decir, A debería ganar. Como el enunciado dice que los resultados deben mostrarse en el turno siguiente (turno 2 de A), mi pregunta es si B debe ser eliminado en el turno 1 de A (significaría que B no jugaría ese turno ya que fue eliminado) o se debe eliminar la civ. B en el turno 2 de A, es decir en el minuto que se muestran los resultados.

**Comment by jeschuwirth** [comment]
Saludos
Si no me equivoco no debería afectar en cualquier caso, si encuentras alguna razón por la que sea importante el orden, entonces especifica en el readme cual de ellas utilizaste y porque.

Suerte!
