### ISSUE TITLE
Tarea 1: Duda sobre la variable tiempo

### ISSUE THREAD

**Issue by estebanmb** [IIC2233/Syllabus#100]
Hola me ayudan con esto ?
Se que la base de datos incluye minutos  no obstante:
El usuario ingresa solo fecha y hora, o ¿también ingresa minutos?
Lo pregunto para saber, por ejemplo, la tasa de propagación del incendio, es decir, el enunciado indica 500 metros por hora. Si se produjo un incendio a las 17:00 y  en un mismo día un usuario ingresa a las 17:30 entonces el ¿incendio se propago 250 metros o cero metros? lo mismo con los pronósticos y las tasas de extinción de los recursos?  
En resumen, ¿debo simular por hora o por minuto?
Gracias.

**Comment by DiegoAndai** [comment]
Creo que lo que preguntas se preguntó en #27. Corrígeme si no es así.

Saludos.
