### ISSUE TITLE
yield from

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#1000]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! En el *notebook 2 de la semana 11* aparece el concepto de ```yield from``` y no logro entender bien de que se trata. Aún me quedan dudas con el ```yield``` por si mismo pero ahora cuando agregamos el ```from``` me quedan más dudas. Leí este artículo: https://stackoverflow.com/questions/9708902/in-practice-what-are-the-main-uses-for-the-new-yield-from-syntax-in-python-3 pero me dejó mas confundido que antes :s.

**Comment by Pablok98** [comment]
Hola! 
En términos más básicos, `yield from` permite que un iterador/generador pueda devolver un valor a partir de otro iterador/generador (que desde ahora llamaré _sub-iterador_). Básicamente, cuando un iterador devuelve `yield from` de un sub-iterador, entonces el programa va a llamar a este sub-iterador, va a partir "leyendo" sus líneas de código y una vez que encuentre el `yield` de este, el iterador principal devolverá ese valor y así sucesivamente (es parecido a tener una función que devuelve el `return` de otra función).

El artículo que indicas explica algunas de funciones más complejas, no tan necesarias en el curso (excepto una, que detallaré al final). Creo que un ejemplo que te podría ayudar mejor es [este](https://lerner.co.il/2020/05/08/making-sense-of-generators-coroutines-and-yield-from-in-python/). 

La explicación conceptual del ejemplo de `yield from` que tiene la página, es que presenta dos definiciones de generadores para iterar a través de una lista. El primero realiza un loop a través de la lista y devuelve con `yield` cada elemento. Como la lista ya es iterable, esto es equivalente a que tu función generadora simplemente llame a `yield from mi_lista`, por la razón que te expliqué en el primer párrafo. El programa al llamar `yield from` va a entrar en la lista hasta encontrar el primer elemento, el cual la lista va a devolver y luego tu función devolverá ese valor y así sucesivamente para cada iteración.

Lo que te quería comentar sobre el artículo de Stackoverflow es sobre esa "conexión bidireccional" que habla. Básicamente, cuando utilizas `yield from`, en tu código principal podrás enviar elementos devuelta al sub-iterador (utilizando `send()`) y viceversa, ya que con el `yield from` el que devuelve el valor al código principal es el `yield` de "más adentro" (en el ejemplo de la función, la lista misma estaría devolviendo sus valores a través del `yield from`, en cambio en la versión con el _loop_ lo valores los devuelve la función misma, pues los extrae de la lista y luego los devuelve).

Es posible que esto aún suene complejo, pero espero que te ayude para aclarar algunas dudas. Si sigues con dudas, solo escribeme 😄

**Comment by tomasgv** [comment]
¡Hola @YehudaGurovich!

Esta es una ocasión especial... **¿qué *issue* era?** 🤔 

Sí, esta es la ***issue* 1000!!!** 😱  😱 

🎊   🎊   🎊    **¡ F E L I C I D A D E S !**   🎊   🎊   🎊

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26393515/98255348-1681f500-1f5c-11eb-8a19-ab82845d8c7b.gif)

**Comment by YehudaGurovich** [comment]
> Hola!
> En términos más básicos, `yield from` permite que un iterador/generador pueda devolver un valor a partir de otro iterador/generador (que desde ahora llamaré _sub-iterador_). Básicamente, cuando un iterador devuelve `yield from` de un sub-iterador, entonces el programa va a llamar a este sub-iterador, va a partir "leyendo" sus líneas de código y una vez que encuentre el `yield` de este, el iterador principal devolverá ese valor y así sucesivamente (es parecido a tener una función que devuelve el `return` de otra función).
> 
> El artículo que indicas explica algunas de funciones más complejas, no tan necesarias en el curso (excepto una, que detallaré al final). Creo que un ejemplo que te podría ayudar mejor es [este](https://lerner.co.il/2020/05/08/making-sense-of-generators-coroutines-and-yield-from-in-python/).
> 
> La explicación conceptual del ejemplo de `yield from` que tiene la página, es que presenta dos definiciones de generadores para iterar a través de una lista. El primero realiza un loop a través de la lista y devuelve con `yield` cada elemento. Como la lista ya es iterable, esto es equivalente a que tu función generadora simplemente llame a `yield from mi_lista`, por la razón que te expliqué en el primer párrafo. El programa al llamar `yield from` va a entrar en la lista hasta encontrar el primer elemento, el cual la lista va a devolver y luego tu función devolverá ese valor y así sucesivamente para cada iteración.
> 
> Lo que te quería comentar sobre el artículo de Stackoverflow es sobre esa "conexión bidireccional" que habla. Básicamente, cuando utilizas `yield from`, en tu código principal podrás enviar elementos devuelta al sub-iterador (utilizando `send()`) y viceversa, ya que con el `yield from` el que devuelve el valor al código principal es el `yield` de "más adentro" (en el ejemplo de la función, la lista misma estaría devolviendo sus valores a través del `yield from`, en cambio en la versión con el _loop_ lo valores los devuelve la función misma, pues los extrae de la lista y luego los devuelve).
> 
> Es posible que esto aún suene complejo, pero espero que te ayude para aclarar algunas dudas. Si sigues con dudas, solo escribeme 😄

Tendre que darle varias vueltas hasta entenderlo jaja.

**Comment by Pablok98** [comment]
Te recomiendo revisar la materia de iteradores. Si tienes más dudas no dudes en preguntar :smile:
