### ISSUE TITLE
Problema al hacer Git Pull (Issue Miiiiiiiil 🎉)

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1000]
Hola, cuando intento hacer git pull a "contenidos" me aparece este mensaje, como lo soluciono??? 

![Captura de pantalla 2020-06-07 07 38 58](https://user-images.githubusercontent.com/62029138/84068561-225e9080-a997-11ea-9c88-96cd0b5797de.png)

**Comment by entamburini** [comment]
Hola @RonaldoSosa, 

El error te aparece porque tienes cambios registrados en esos archivos. Para hacer `git pull` tienes que eliminar los cambios hechos, así que te recomiendo que los respaldes en algún lado si es que te interesa guardarlos y luego realizar `git stash`. 

Después de eso si deberías ser capaz de hacer `git pull` sin problema.

PS: Felicitaciones! :tada: eres la issue número mil :partying_face: y por lo mismo, te queremos premiar con un cupón:

![photo_2020-06-08_15-00-35](https://user-images.githubusercontent.com/20786198/84069752-09ef7580-a999-11ea-883c-1de75b765d05.jpg)

:partying_face::balloon::balloon::partying_face:

**Comment by RonaldoSosa** [comment]
Yaaaa muchas gracias XD!!!!
