### ISSUE TITLE
Eliminar un nodo

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#1001]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Una pregunta simple, pero importante de cómo funcionan los nodos. Si por ejemplo elimino el nodo 4, el nodo 5 pasa a ser el nodo 4 o deja de existir el nodo 4?

**Comment by Pablok98** [comment]
¡Hola! 
La pregunta depende a que estructura de datos te refieres :open_mouth: 
Podría ser lista ligada, arbol, grafo, etc. ¿Con cuál tienes la duda?

**Comment by YehudaGurovich** [comment]
En lista ligada se *reemplaza*.
La pregunta en arbol es si se eliminan los hijos o pasan a ser parte del *padre mas grande*?
Y en grafo no me queda claro.

**Comment by Pablok98** [comment]
En el caso del árbol, depende de tu implementación o de lo que te pidan (si es una evaluación del curso). Tanto eliminar los hijos como pasar los hijos al padre son una respuesta válida, pero lo más común es eliminar los hijos (piensa en una carpeta de tu computador, si eliminas una carpeta ¿Quieres eliminar también sus contenidos o que ellos aparescan en todos lados y tengas que eliminarlos uno por uno?).

En el caso del grafo, cuando eliminas un nodo no se debería eliminar otros, pero si sus relaciones (las "flechas" que están conectadas con el nodo que eliminaste).

Espero que eso responda tu duda. Suerte!

**Comment by YehudaGurovich** [comment]
Gracias!
