### ISSUE TITLE
Output terminal de Visual Studio Code

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#1002]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Una consulta poco relacionada al curso pero no logro solucionarlo :/
¿Hay alguna forma de hacer que VSC muestre TODO el output en la consola sin cortar cuando los outputs son muy largos?
Me pasa que me los corta y muestra la última parte.

**Comment by tocococa** [comment]
Hola @YehudaGurovich ! A que te refieres con que los corta? Quieres decir que en la terminal de VSC las últimas columnas no aparecen?

**Comment by YehudaGurovich** [comment]
@tocococa Cuando se imprimen muchas líneas las primeras no aparecen :/

**Comment by tocococa** [comment]
Okaoka. En la configuración de VSC, busca `scrollback` y ahí te debería mostrar una opción que se llama `Terminal>Integrated: Scrollback` y ahí puedes aumentar el número de lineas que la terminal mantiene en su _buffer_. No se cuál es el máximo y no recomendaría dejarlo demasiado alto, porque si tienes un _loop_ que nunca deja de imprimir podrías terminar con un _buffer_ demasiado grande.

**Comment by YehudaGurovich** [comment]
Ok! Gracias.
