### ISSUE TITLE
Duda con ".vscode"

### ISSUE THREAD

**Issue by CatalinaGoldsack** [IIC2233/syllabus#1002]
Hola! Al subir mi Readme me di cuenta de que tengo un archivo ```.vscode``` subido que por alguna razón no salía en mi carpeta local de T02. ¿Qué debo hacer con este tipos de archivos? ¿Se ponen en el ```.gitignore```?

**Comment by Alonsinho1** [comment]
Hola!

El archivo .vscode es parecido al archivo pycache. Este se genera cuando utilizas vscode. Era invisible por que partía con un "." entonces mac lo escondía. Al ser un archivo innecesario para la corrección debe ser incluido en el gitignore.

**Comment by CatalinaGoldsack** [comment]
Gracias!! :) 
Agregué .vscode al .gitignore pero aun me sigue apareciendo en mi repositorio de github, ¿existe manera de borrarlo? Aun no entiendo muy bien cómo funciona...

**Comment by Alonsinho1** [comment]
Lo que pasa es que el archivo se subió antes de hacer el gitignore, entonces este se alcanzo a subir. Ahora que haces push, el archivo no se sube pero este ya se subió. Hay buscar una forma de sacarlo de ahí.... 

una como estas dos quizás  #904 :D  !! Dime si te sirven !

El gitignore, es una herramienta donde escribes los archivos y/o carpetas que tu no quieres subir al repositorio remoto. Si haces _git add ._ se preparan para hacer cambios a todos los archivos, exceptuando, a los que escribiste en el gitignore.

**Comment by CatalinaGoldsack** [comment]
Perfeeeecto!!!! Ahí lo logré eliminar, muchas gracias Alonso! :)
Si el commit que se revisará en la tarea incluía .vscode, ¿debiese rellenar el formulario de entrega atrasada por la eliminación del .vscode? ¿Esta actualización se considera como entrega atrasada?

**Comment by Alonsinho1** [comment]
Te recomiendo rellenarlo por si acaso, pero explica bien tu situación para que no crean que es una tarea atrasada. En el peor peor de los casos, solo deberías recibir un descuento por incluir el archivo.

**Comment by CatalinaGoldsack** [comment]
Buenísimo, gracias!!!

**Comment by CatalinaGoldsack** [comment]
Oh, se acabó el tiempo para entregar un commit atrasado... Creo que recibiré el descuento nomás :(

**Comment by Alonsinho1** [comment]
:c  

Igual no te preocupes, si es que llegas a recibirlo no creo que sea muy grande!  


Animo  (:D)->-<   !

**Comment by CatalinaGoldsack** [comment]
:blush: :blush: :blush:
