### ISSUE TITLE
Duda sobre README

### ISSUE THREAD

**Issue by aipostigo** [IIC2233/syllabus#1003]
Hola! no logre subir el README a tiempo, existe una posibilidad de entregarlo mas tarde y no descontar tanto o simplemente ya no lo entregue?

**Comment by entamburini** [comment]
Hola @aipostigo! 

Entrégalo igual!, tendrás un descuento pequeño (es como una o dos décimas) y no correrás el riesgo de que quien te corrija no haga su mejor trabajo por culpa de no entender las cosas que hiciste y que pudiste explicar en el README.

Saludos! :v:
