### ISSUE TITLE
Error de tipeo (nombres de archivos) en s13 ej5

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#1004]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, tengo un problema con mi solución del ejercicio 5, semana 13. En las instrucciones de `recomendar_peliculas`, decía "serializar, mediante Pickle, cada película en un archivo llamado **`recomendaciones.pkl`**". Sin embargo, bajé de esa parte de la pantalla, olvidé exactamente qué decía ahí, y llegué a las instrucciones repetidas como ayuda visual en el docstring de `recomendar_peliculas`, que dicen "serializar las películas en el archivo **`caracteristicas.pkl`**." Además, luego, el _main_ dice "Al correr este código, deberías obtener un archivo llamado **`recomendacion.pkl`** con la información de cada película y la opinion para cada una de estas." Corrí el _main_ y busqué el archivo, para luego acordarme que yo en realidad no creaba ningún archivo con ninguno de esos nombres, sino que sobreescribía `caracteristicas`. Por lo tanto, **ahora asumo que tengo `características` sobreescrito con mis recomendaciones (si funcionó... esperemos que sí 😅), y no sé si debería guardarme todas mis otras soluciones de los ejercicios, eliminar mi version local de `contenidos` y volver a clonarla** para tener los archivos originales. Ayura porfis 🥺

**Comment by aaossa** [comment]
Hola @sbcorrea , disculpa la demora en la respuesta 😅 Creo que, tal como en la *issue* https://github.com/IIC2233/syllabus/issues/1008, te recomendaría bajar el archivo a mano para tener el original. Luego, cambia tu código para crear el archivo nuevo y no sobrescribir el original. Ahora si corres todo debería funcionar bien (si es que hiciste bien el ejercicio claro 👀). Ojalá te sirva, pero si algo no te funciona o tienes otra duda pregunta por acá no más ✨ ¡Éxito en la actividad 🙌!

**Comment by aaossa** [comment]
Hola, ahora entendí el error de tipeo que decías 😱 Ya lo anoté en nuestro repositorio para que no se nos pase el próximo semestre 😓 ¡Gracias 💯! (Cuando publicamos algo intentamos no cambiarlo para que no tengan problemas con sus cambios locales)

**Comment by sbcorrea** [comment]
Buenísimo, ¡muchas gracias!
