### ISSUE TITLE
Outputs de los contenidos

### ISSUE THREAD

**Issue by amparostevens** [IIC2233/syllabus#1004]
Hola! 😄  Estaba leyendo los contenidos de la semana y me surgió una duda sobre los outputs en los ejemplos, que no se si será un error de jupyter o se debe imprimir así. Por ejemplo en el siguiente código: 
```
tupla = ("a", 1, 3, "hola")
tupla_serializada = pickle.dumps(tupla)

print(f"Resultado serialización: {tupla_serializada}")
print(f"Tipo de versión serializada: {type(tupla_serializada)}")
```

Me sale como output:
`Resultado serialización: b'\x80\x03(X\x01\x00\x00\x00aq\x00K\x01K\x03X\x04\x00\x00\x00holaq\x01tq\x02.'`

Está bien que aparezcan paréntesis y la palabra hola? Vale decir que no he modificado ni corrido los cuadernos.

**Comment by entamburini** [comment]
Hola @amparostevens! :D,

Buena pregunta. La respuesta corta es que si, está bien que aparezcan las comillas y la palabra "hola". La razón detrás del por qué python muestra las cosas de esa forma es porque es la manera que tiene de representar cosas codificadas en `bytes`.

Me explico, si te fijas al comienzo del resultado del print aparece una `b`. Eso indica que python identificó la variable como una instancia de clase `bytes` y por ende tratará de mostrar todo lo que entienda y lo que no lo representará en el formato `\xNN`. En ese sentido, la razón por la que te aparecen tantos de esos `\xNN` es porque `pickle` empaqueta las cosas y las serializa (convirtiendo lo empaquetado en bytes), por lo que el "hola" que era algo que podría mostrar si solo fuese ese string, queda encapsulado en cosas de pickle que no se pueden mostrar porque no son parte del encoding ascii. 

Vamos por un ejemplo para que quede más claro, si codificamos un simple string sin pickle:
```python
un_hola_entendible = b'hola'
print(un_hola_entendible)
# Imprime b'hola'
```
El output será: `b'hola'` porque porque solo codificaste la palabra a bytes y eran caracteres que pertenecen al encoding ascii. Por otra parte:
```python
otro_hola = pickle.dumps('hola')
print(otro_hola)
# Imprime b'\x80\x04\x95\x08\x00\x00\x00\x00\x00\x00\x00\x8c\x04hola\x94.'
```
Esto tiene ese output porque como dije antes, `pickle` empaqueta y serializa las cosas. Si te fijas, en ambos aparecerá el `b` al comienzo porque es cómo representa python las instancias de `bytes` en los prints, pero son cosas diferentes aunque en ambos casos quiera simplemente convertir en bytes un string "hola". 

Ojalá te haya quedado claro, cualquier cosa estaré atento! :)
