### ISSUE TITLE
Recorreccion de tarea. Reporte.

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2233/syllabus#1005]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)

### Contenido

Hola, tuve un problema de `.gitignore`, con lo cual no subí el archivo `parametros.py` en la tarea 1. Pedí una recorreccion y ahora me enviaron un correo diciendo que no lo subi denuevo. Bueno, no se si esto se decia en algun lado y no lo vi, pero no sabia que debia subirla a github(para recorregirla), creí que me enviarian algo que dijera algo como "subelo aqui, porque sera una revision mas individual", "sube los archivos que te faltaron a github antes de tal fecha".  Si esto se especificaba en algun lado asumo mi falta, pero si no, para esto no le pase a nadie mas podria especificarse, yo con los nervios (por la nota que obtuve) queria dejar la carpeta intacta para que vieran que no la habia modificado desde el dia que la entregue y por eso no subi nada.

**Comment by aaossa** [comment]
Hola @Lord-Kelsier , respondiendo un poco a tu *issue*, el único medio de entrega que usamos son los repositorios de GitHub, por lo que si no subiste tu archivo les ayudantes no pueden revisarlo 😅. Para corregir hacemos una "copia" de los contenidos de los repositorios al momento de la entrega, por lo que cambios posteriores no afectan la entrega, así que si no lo has hecho aún, sube tu archivo no más. Para poder ver tu caso de una manera más particular, dado que ya sale del proceso regular que es la recorrección, te recomiendo enviar un correo al correo del curso (iic2233@ing.puc.cl). Si ya enviaste el correo, tienes que esperar a que lo podamos revisar y te responderemos lo antes posible 👌 ¡Que tengas una buena semana ✨!

**Comment by Lord-Kelsier** [comment]
Ya subi mis archivos, pero en el feedback me dijeron que estos casos se ven a final de semestre

**Comment by Lord-Kelsier** [comment]
Coloque esta issue mas que nada como una recomendacion, si es que no esta especificado esto de que se debe subir los archivos ya que se que los temas administrativos no se resuelven por aqui.
