### ISSUE TITLE
Etiquetado al programar

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#1005]
¡Hola! Viendo la ayudantía de back-end, me quedó dando vuelta la recomendación a la pasada que hacía @lucasvsj de **programar en inglés**. Como no era un tema central no se explicaba, y me gustaría saber más al respecto... Me imagino que acostrumbrarse a etiquetar variables, funciones y clases en inglés haría más fácil colaborar en proyectos internacionales, o algo parecido. Por otra parte, asumo que no es buena idea adoptar esa práctica para mis entregas de este ramo, para no dificultar la corrección. ¿Cuáles son los pros y contras de programar en inglés vs español?
Gracias de antemano :)

**Comment by Alonsinho1** [comment]
Ademas de cosas obvias como el tema de que alguien no te entienda el nombre de las variables y que en el ambito internacional te entiendan mejor. Algunos programas trabajan con tus variables y las modifician al ingles.

Ejemplo concreto:
- Rails para algunos funciones toma el nombre de tus funciones y la pasa al plural. por ejemplo si escribiste "car" luego creara una nueva "variable" que se llamara "cars". Tranfomara tu palabra a su plural. Sin embargo, esto solo funcionara correctamente en ingles. En español si creas la variable "solicituds" su plural en Rails sera "Solicitudss¨, lo cual no tiene mucho sentido.

**Comment by Drpinto1** [comment]
¡Hola @sbcorrea!

Complementando un poco la respuesta de Alonso, un gran plus de escribir código en inglés, es que la gran mayoría de los lenguajes de programación tienen sus _built-ins_ hechos en este idioma, por lo que un código será más legible si se estando "en un solo idioma"; por ejemplo la lectura de:

`for condition in list(conditions)`
Será mucho más fluida que la lectura de:
`for condicion in list(condiciones)`

Además de esto están los temas que ambos mencionan (un código escrito en inglés será mucho mas asequible para un gran número de personas y existen herramientas que utilizan los nombres de variables asumiendo que estos está en inglés) e incluso la guía de estilos que todos amamos, [PEP8](https://www.python.org/dev/peps/pep-0008/#comments), contiene información al respecto :open_mouth: 

> Python coders from non-English speaking countries: please write your comments in English, unless you are 120% sure that the code will never be read by people who don't speak your language.

Si queremos definir pros y contras de escribir en cada idioma, al menos a nivel del curso, se me ocurren los siguientes (escribiré solo pros, pero al final los pros de uno son los contras del otro):

#### Español:
- Te asegurás que si un ayudante te está asistiendo, el idioma no le dificultará leer tu código (y sus comentarios).
- La escritura de código probablemente será más fluida, al no tener que buscar sinónimos o traducción de ciertas palabras que pueden ser un tanto específicas, lo que puede resultar en ahorro de tiempo.
- Podrás se consistente con los nombres de variables (métodos, clases, etc) que te entregamos en los enunciados, pues estos siempre estarán en español.
- En caso de querer explicar o mostrar tu código a una persona externa al curso o (solamente si el plazo de la evaluación en cuestión terminó :eyes:) a alguno de tus compañeros, te aseguras de que entenderán el idioma en que está escrito.

#### Inglés:
- Tu código será más legible y "futureproof"
- Podrás usar cualquier palabra del idioma (no tendrás problemas con tildes ni ñ)
- Te será más fácil acostumbrarte a escribir en inglés a futuro.
- Te ayudará a expandir tu vocabulario.
- Si en el futuro (un poco más lejano) quisieras reutilizar o compartir tu código, podrás hacerlo si necesidad de preocuparte del idioma.


Por último, sobre tu pregunta de si sería buena idea o no adoptar esta práctica durante el curso, esto es más una decisión personal que puedes tomar basándote en la lista de pros de cada idioma (y en las razones personales que tengas), sin embargo independiente de la decisión que tomes, esto no afectará de manera positiva o negativa tus calificaciones y correcciones. 

En general los ayudantes tienen un cierto manejo del inglés y en caso de que alguno tenga dificultades con esto, recibirá apoyo del resto del equipo docente, por lo que en ningún caso será problemático para ti :D

Si no estás segura de qué decisión tomar, siento que personalmente un buen punto intermedio es utilizar nombres de variables, clases, métodos, etc, en inglés, pero mantener los comentarios en español, así te empiezas a acostumbrar a escribir el código en inglés, pero te ahorras posibles problemas de interpretación de los comentarios.

¡Saludos!

**Comment by sbcorrea** [comment]
Bacan, me ayuda mucho!! Muchas graciassss se pasaron
