### ISSUE TITLE
Output ejercicio 1 semana 13

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#1006]
Hola! Empecé a hacer los ejercicios propuestos de I/O y serialización, pero cuando llegué al final del ejercicio 1 y no encontré output esperado, entré un poco (muchísimo) en pánico.

Monitoreé en cada paso de mi desarrollo (con prints) que las operaciones estuvieran correctas, pero mi archivo simpatico.bmp no se ve simpático cuando agrego esto al final para revisarlo:
```
with open('simpatico.bmp', 'rb') as simpatico:
    print(simpatico.read())
```

sino que imprime esto:
```
b'BM\xba\xdd\x01\x00\x00\x00\x00\x006\x00\x00\x00(\x00\x00\x00\xf4\x00\x00\x00\xa7\x00\x00\x00\x01\x00\x18\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc4\x0e\x00\x00\xc4\x0e\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```
con cientos de X más y algunos pocos caracteres distintos entre medio. Vi que en la issue #1004 hablaban de que a veces se ve raro, pero como no hay nada en el enunciado que describa el producto, sino solo el proceso, se me hace muy patente que si me equivoqué en alguna parte del proceso, no tengo cómo darme cuenta :( Ninguno de los pasos pide encoding o decoding pero tirando al achunte diría que me falta esto... ¿alguien me podría orientar respecto a cómo sé si me funcionó?

Si de casualidad estuviera el material de los outputs esperados del resto de los ejercicios pero yo no lo encuentro o faltó subirlos, sería también de GRAN GRAN ayuda, por último aunque fuera por temas de ánimo. Leer una mezcla de hexadecimal, letras y signos de puntuación que es justo lo suficientemente sistemática para parecer un mensaje de error, tratando de encontrarle lógica, en un semestre online donde no me puedo conseguir ninguna referencia de cómo se debería ver, se siente un poco como gritar al vacío 😢 muchas gracias de antemano si fuera posible

**Comment by jitorralba** [comment]
Hola! No soy ayudante, pero si abres el archivo desde jupyter, es decir, no desde "ejercicios_propuestos", te darás cuenta que es una imagen, por lo que entendí yo, si puedes visualizar la imagen, el ejercicio está bueno

**Comment by NelsonIMA** [comment]
Hola @jitorralba ! ¿Cuál alfabeto usaste para decodificar el archivo? Probé con los cuatro `.decode("")` que salen en la primera parte de los contenidos y no me funcionó :(

**Comment by rodrigobj99** [comment]
Hola! no soy ayudante, pero puedes obtener el entero correspondiente a cada byte de un bytearray con el uso de [ ], a mí al menos me resulto con eso!

**Comment by NelsonIMA** [comment]
Gracias!! @rodrigobj99

**Comment by fdoflorenzano** [comment]
Hola a todes,

@sbcorrea como dice @jitorralba el archivo resultado `simpatico.bmp` se trata de una imagen, si luego de guardarla eres capaz de abrirla, como una imagen cualquiera en tu computador, entonces significa que el resultado es correcto. Si te sale algún mensaje que dice está dañado o no se puede leer, entonces es probable que algún paso esté incorrecto en tu implementación.

En ese ejercicio no es necesario usar *encodings*, ya que no estamos trabajando con texto. Se trabaja solo directamente con *bytes*, por lo que resulta ese texto raro al imprimir porque Python te da una representación de texto de objetos *bytes*. De todas formas, imprimí también el resultado que me dio a mi y también tiene un montón de X y demases :)

Saludos.

**Comment by fdoflorenzano** [comment]
Hola @sbcorrea,

¿Cómo te fue con esta duda?

Esperaré un tiempo para ver si respondes, si no para resolver está _issue_ ya que sigue como "pendiente".

¡Saludos!
