### ISSUE TITLE
Problemas al hacer pull en el syllabus y al tratar de eliminar el syllabus de mi pc

### ISSUE THREAD

**Issue by burizar** [IIC2233/syllabus#1006]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola!
La semana pasada en la actividad tuve problemas para hacer pull en el syllabus. Pedí ayuda en discord y, según lo que me dijo la ayudante que me trato de solucionar el problema, no podía hacer pull porque modifiqué sin querer cosas en el syllabus.

![MINGW64__c_Users_buriz_OneDrive_Documents_6to Semestre_IIC2233-Programación Avanzada_syllabus_Actividades 05-11-2020 14_19_51](https://user-images.githubusercontent.com/69607342/98693932-a86c7200-234f-11eb-9a52-9fb43f038dd8.png)

La ayudante me recomendó borrar la carpeta del syllabus de mi pc y clonarla de nuevo, pero al tratar de borrarla me tira el siguiente error:

![1 acción interrumpida 05-11-2020 14_32_35](https://user-images.githubusercontent.com/69607342/98694119-d6ea4d00-234f-11eb-97ce-86f326af915c.png)

Si pongo reintentar se me abre esta otra ventana

![Acceso denegado a la carpeta 10-11-2020 12_07_23](https://user-images.githubusercontent.com/69607342/98694168-e79ac300-234f-11eb-8731-084ba3b78fe8.png)

He intentado habilitando la casilla que sale Hacer esto para todos los elementos actuales y apretando continuar pero se me vuelve a abrir la ventana anterior a esta.
Finalmente, para poder hacer la actividad clone de nuevo el syllabus y lo guardé en otro directorio. Me gustaría borrar la carpeta del syllabus que no funciona y quedarme con la nueva, pero como pueden ver, no he podido hacerlo. Ya intenté buscando el código de error que aparece en la segunda imagen en google y haciendo lo que sale en [este link](https://answers.microsoft.com/es-es/windows/forum/windows_7-files/error-0x80070091-el-directorio-no-esta-vacio/fe35db59-9fb5-4ea5-86e9-76841bc475f1) pero no funcionó. Si alguien pudiera ayudarme estaría muy agradecido :pray:.

**Comment by gatochico** [comment]
Hola @burizar ! Vengo con algunas ideas que podrían ayudarte. Trata de ejecutarlas en este orden:

**Opción 1:**
- Abre la carpeta del syllabus en git bash.
- Estando en la raíz del syllabus ejecuta los siguientes comandos:
- `git add .`
- `git stash`
- `git pull`
Con eso deberías poder hacer pull del syllabus y posiblemente poder borrar la carpeta.

**Opción 2:**
Buscando el error que te sale, en [https://es.joecomp.com/error-0x80070091-directory-is-not-empty](esta página) me dice que a veces la carpeta se puede eliminar cambiando su nombre primero. Podrías probar eso 🤔 

Si no funciona ninguna de esas opciones, puedes comentar esta issue, ya que las siguientes opciones parecen ser un poco más complicadas.

Cuéntanos cómo te va!

**Comment by burizar** [comment]
Funcionó cambiándole el nombre! 
Gracias!
