### ISSUE TITLE
Desarrollo AY09

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#1007]
Hola, el desarrollo de la AY09 cuándo lo subirán¿?
Gracias :nerd_face:

**Comment by Drpinto1** [comment]
¡Hola!

Se está subiendo la ayudantía en este momento, así que no debería tardar mucho en estar disponible.

¡Saludos!

**Comment by Camila-sty** [comment]
@Drpinto1 aún no la veo...
Dónde la subieron?

**Comment by Drpinto1** [comment]
Acaba de publicarse en Canvas 🌚

**Comment by Camila-sty** [comment]
@Drpinto1 en el módulo "semana 13" de canvas, está "Ayudantía: I/O y Serialización", pero al abrirla, no me aparece nada...

**Comment by Drpinto1** [comment]
Aparentemente esto lo causo un bug de Canvas 😵

Pero ya debería estar arreglado 🌝
Gracias por avisar :D

**Comment by Camila-sty** [comment]
Pero yo me refería al documento.... siempre han publicado el desarrollo como documento al igual que el enunciado... 
Será posible que lo suban ahora?

**Comment by Drpinto1** [comment]
Normalmente subimos dos documentos, enunciado y solución, pero si revisas el archivo `Enunciado.ipynb`, notarás que este no tiene partes por completar, todo el desarrollo está ahí 👀
