### ISSUE TITLE
Serializar objetos propios en ejercicio 3: Serialización con JSON y pickle

### ISSUE THREAD

**Issue by tcouso** [IIC2233/syllabus#1007]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ]X Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ]X Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola!
Estoy algo confundido con que se nos pide para almacenar las instancias de `Obra` en el ejercicio propuesto 3. Se detalla un formato para los nombres de archivo de cada obra, que me imagino que contendría los bytes de las instancias, pero no estoy muy seguro de cómo almacenar los bytes serializados dentro de un archivo que a su vez estaría en otro directorio (la carpeta Obras, hasta donde entendí). Mi pregunta, en concreto es: **¿Qué se nos pide que hagamos al serializar las instancias de `Obra` en el ejercicio propuesto 3?**

Saludos y gracias por la ayuda!

**Comment by aaossa** [comment]
Hola @tcouso ,

Lo que se pide en esa parte del ejercicio es serializar las obras usando `pickle` (con la consideración de crear el "messaggio" en el método `__getstate__`), lo que te entregará bytes si es que usas `pickle.dumps`. Estos bytes son los que debes guardar en un archivo con el nombre indicado. Ten ojo con crear la carpeta primero, y recuerda que la mejor forma de indicar una ruta es con `os.path.join` (Algo así te quedaría: `os.path.join("Obras", nombre_nuevo)`). Avísame si esto te resuelve la duda, pero si no es así vuelve a preguntar no más 👌

**Comment by tcouso** [comment]
Hola @aaossa,

Gracias por la explicación! Logré crear los directorios y los archivos, pero al abrir cualquiera de las obras en vez de aparecerme los bytes del objeto, sale un error con respecto a que el archivo no está codificado en utf-8. Revisé la solución del ejercicio y, a grandes rasgos, hice lo mismo. Cual podría ser el error en este caso?

Saludos!

**Comment by aaossa** [comment]
Hola @tcouso , si tienes un problema con el *encoding* entonces estás trabajando con los archivos en modo texto y no en modo binario. En tal caso, prueba leyendo los archivos con modo `"rb"` (o escribiendo con `"wb"`). Revisa si es eso 🤔
