### ISSUE TITLE
Problema en ejercicio 5

### ISSUE THREAD

**Issue by BFry712** [IIC2233/syllabus#1008]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
*  [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! tengo un problema del **ejercicio 5** de esta semana ya que cuando trato de deserializar y leer lo que contiene caracteristica.pkl me sale None y antes si me salian las caracteristicas. El error me ocurrió cuando apagué el computador y lo volvi a prender para seguir el ejercicio. Como lo podria arreglar?

**Comment by aaossa** [comment]
Hola @BFry712 , dado que es algo de un solo archivo, creo que basta con que lo bajes manualmente. Puedes encontrarlo [aquí](https://github.com/IIC2233/contenidos/blob/master/semana-13/ejercicios_propuestos/caracteristicas.pkl) (en el repositorio de contenidos en GitHub), descargarlo y guardarlo con el nombre `caracteristicas.pkl` 👌 Avísame si te funciona 🙌

**Comment by BFry712** [comment]
Hola @aaossa ! me funcionó super ahora!
Muchas gracias!
