### ISSUE TITLE
recorreccion de AS02

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#1008]
Hola. En un anuncio de canvas sale que íbamos a tener plazo hasta el 16 de junio hasta las 20:00 hrs para hacer una recorreción de AF04 y/o AS02, pero al abrir el formulario de AS02 (que es lo que quiero recorregir) sale una única opción disponible para recorregir que es la AS03.
https://docs.google.com/forms/d/e/1FAIpQLSepaeOedQBLOj21oS_vD7PU2YtfwdAsT35B4pNVZFcCY6obEw/viewform
Está mal? o cambiaron el plazo?

**Comment by entamburini** [comment]
Hola @Camila-sty!,

Interestante, es cierto! jajajaj ya se arregló :) 

Gracias por avisar! :v:

**Comment by Camila-sty** [comment]
@entamburini  ayer rellené el formulario para la recorrección de AS02, pero me equivoqué. Ya no quiero recorreguir nada jajaja, cómo lo hago? porque no pude eliminar el formulario...

**Comment by entamburini** [comment]
Chan! :scream: 

No se puede :c jasjasj nah broma, ahi te borre :)
