### ISSUE TITLE
Ejercicio propuesto 4/ Semana 13

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#1009]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, en la parte del enunciado donde indica agregar ceros hasta llegar a los 20 bytes, estos deben ser al comienzo o al final del chunk?

**Comment by aaossa** [comment]
Hola @Margarita-Paz , tienen que ser al final por lo que recuerdo 👌 (Al menos así lo hice yo también 😅). ¡Éxito con tu estudio para la actividad ✨!
