### ISSUE TITLE
Como hacer pdf's bonitos estilo Enunciado?

### ISSUE THREAD

**Issue by Christian-Klempau** [IIC2233/syllabus#1009]
Hola! 
Me surgió la duda, como hacen los pdf de los enunciados de las tareas y actividades?
Para poder poner *snippets* de código y formatos de color. Será exportando los .md como pdf o algo por el estilo? Gracias!

**Comment by benjavicente** [comment]
Hola!
Creo que las realizan con [LaTeX ](https://es.wikipedia.org/wiki/LaTeX) con un paquete llamado `listings`.

**Comment by Alonsinho1** [comment]
Tal como dice @benjavicente, se hacen con [LaTeX](https://es.wikipedia.org/wiki/LaTeX) (Se usa en practicamente todos los ramos de ing) y la ayuda de varios paquetes (Funciones adicionales que permiten agregar cosas a LaTex. `listings` es una de ellas). Es como importar modulos en un codigo de python.


Saludos! (:D)->-<

**Comment by lily416** [comment]
Complementando las respuestas de @benjavicente y @Alonsinho1,

Normalmente para darle al texto una fuente monoespaciada y ponerle color utilizamos el paquete [`minted`](www.overleaf.com/learn/latex/Code_Highlighting_with_minted). Pero también existen otros paquetes: [`lstlisting`](https://www.overleaf.com/learn/latex/code_listing) y [`verbatim`](https://www.overleaf.com/learn/latex/Code_listing#The_verbatim_environment). 
Cada uno tienes sus propias características, así que creo que depende de cada uno cuál usar. 🤔 

Me alegra que preguntes sobre cómo hacemos los enunciados, si tienes más dudas sobre cómo los hacemos o qué usamos, estaré encantada de responderte 😄 

Saludos y que tengas una buena semana. 👋❤️

**Comment by cruz** [comment]
Y además hay un editor online, si no quieres embarcarte a instalar LaTeX en tu computador: https://www.overleaf.com/.

**Comment by Christian-Klempau** [comment]
Hola a todos! Muchas gracias por responderme <3
Voy a revisar lo de los módulos de LaTex para aprender, gracias. Cuando tenga más tiempo voy a aprender con mayor profundidad y les preguntaré más :)
