### ISSUE TITLE
Test case 04 crear predios tira error

### ISSUE THREAD

**Issue by Valind4** [IIC2233/Syllabus#101]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holi, el test case de crear tira error porque en el nombre de archivo sale "predios.txt" en vez de "data/predios.txt", modifiqué el test case a "data/predios.txt" y ahí funciona, no sé si es error de mi compu, o si le pasa a todos, porque en enunciado decía que nombre_archivo incluía la ruta y "predios.txt" no la incluye.

**Comment by FernandoTFH** [comment]
Se comento lo que tu dices en la issue #40. Pero en resumen la funcion crear_predio se asume que el parametro nombre_archivo se va a abrir desde data/.
