### ISSUE TITLE
Posible contradicción distribución de puntaje y bonus islas

### ISSUE THREAD

**Issue by jorgee02** [IIC2233/Syllabus#101]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola buenas tardes. 

En la **distribución de puntaje, apartado funciones, solucionar tablero** se dice que se verifiquen todas las reglas obligatorias. Mi problema es que yo implementé el bonus, entonces para mi la regla 5 es igual de obligatoria que las otras 4. 

Bajo ese criterio, puedo asumir que si se me entrega un tablero que puede ser resuelto con las 4 reglas pero no con la 5ta, puedo retornar None?

En el enunciado sección 8.2 entiendo que estoy en lo correcto, pero me surgió la duda viendo la distribución de puntajes.

Estoy atento a sus comentarios.

Muchas gracias.

**Comment by matiasmasjuan** [comment]
Hola @jorgee02 !

Es efectivamente lo que dices. Si realizas ese bonus, entonces debes realizar la función ```solucionar_tablero``` cumpliendo la regla 5. En caso de no cumplirse esta regla, se debe retornar ```None```.

Saludos! 😄
