### ISSUE TITLE
Duda posibilidad de restricción a los ingresos de fechas de usuarios en el tiempo

### ISSUE THREAD

**Issue by pizquierdo2** [IIC2233/Syllabus#101]
¿Es posible poner la restricción de que cualquier fecha y hora que se ingrese sea mayor (posterior) a la última fecha y hora de ingreso? Eso no sólo es una excelente forma de solucionar los problemas de integridad del modelamiento, sino que también hace que el problema planteado se aproxime más al de un programa funcional que está siendo usado por personas reales.

Consideremos t0<t1 puntos del tiempo real. En la realidad nunca ocurrirá que si en t0 un usuario escribe como hora y fecha de ingreso t1’, después en t1 otro usuario escribiera como hora y fecha de ingreso t0' (con t0'<t1'). Pues de hecho t0=t0' y t1=t1' a menos que los usuarios estén mintiendo. Luego, no considerar la restricción propuesta implica no cerrar una posibilidad en la que es necesario que alguno de los usuarios mienta. Entonces, ¿Por qué no la consideraríamos, si lo que queremos son casos en los que nuestros usuarios no mientan?

**Comment by DiegoAndai** [comment]
Noté que copiaste y pegaste eso desde la issue #72. Trata de no hacer eso ya que contribuye al desorden del foro. Si escribiste tu pregunta y nadie la responde, sigue la discusión en el mismo issue. Ahí te respondí.
