### ISSUE TITLE
Modelamiento de las clases

### ISSUE THREAD

**Issue by isidoraabumohors** [IIC2233/Syllabus#101]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Tengo una duda respecto al enunciado. Cuando describe las entidades, comenta sobre las acciones que deben poder realizar. Por ejemplo, en el caso de jugador, dice que debe poder apostar. En ese contexto, se refiere a que si modelamos la apuesta como una función, esta debe encontrarse dentro de la clase Jugador? O podemos usar distintas funciones que no necesariamente se inicien desde la clase Jugador, con tal de que se le permita al jugador ingresar una apuesta?
Muchas gracias!

**Comment by catalina-arcila** [comment]
Hola @isidoraabumohors , está muy recomendado realizarlo de la primera manera que comentas, ya que en el _excel de puntaje _ se evaluará por la formulación de las entidades de manera correcta. Me avisas si sigues con alguna duda!

**Comment by isidoraabumohors** [comment]
Ya perfecto! Gracias. 
Dónde puedo encontrar ese excel?

**Comment by isidoraabumohors** [comment]
Ya perfecto! Entiendo que es lo recomendado, pero si se hace de la otra manera se descontará o no se asignará parte del puntaje?
