### ISSUE TITLE
Lista de orders /orders activas

### ISSUE THREAD

**Issue by behrmann97** [IIC2233/Syllabus#101]
Mi duda es simplemente si al imprimir la lista de orders y la de orders activas hay que imprimir las del usuario o todas las orders de todos los usuarios.

**Comment by sebacruzd** [comment]
Hola, 
La idea es que se vean las de todos, para que el usuario sepa qué está ocurriendo en el mercado.
Ojo que los distintos tipos de users pueden ver distintas cantidades de orders.

Saludos!

**Comment by behrmann97** [comment]
Ok, pero ¿pueden los underaged ver esto también o ellos pueden ver información de los mercados solamente? Si es que sí puede, ven la misma cantidad que los traders?

Saludos y gracias!

**Comment by sebacruzd** [comment]
Está especificado en el enunciado, primer párrafo de la página 3.
Si ahí no dice que puedan hacer algo, no deberían poder, ya que es la gracia de que hayan distintos tipos de usuarios.

**Comment by rihanuch** [comment]
el hecho de que un usuario tenga que acceder a un mercado para ver la información de este se extiende a todos los tipos de usuarios o solo a los underaged???

**Comment by Arcoirisky** [comment]
@rihanuch, sí se extiende a todos los usuarios. Tal como se dice en el enunciado, los Traders gozan de todo lo que pueden hacer los underaged y lo mismo pasa con los Investor, ya que son como Traders pero con más beneficios (El Premium si quieres llamarlo así sadjks) :D

**Comment by ptflores1** [comment]
Las lista de ordenes y ordenes activas tienen que ser de los mercados en que esta registrado el usuario?

**Comment by Jiparavich** [comment]
x2

**Comment by Arcoirisky** [comment]
Hola! Exactamente es así. Se deben ver todas las orders de los mercados en que está registrado el usuario que las pide :D
