### ISSUE TITLE
Este codigo me deja en blanco el archivo seguidores.csv, porque?

### ISSUE THREAD

**Issue by nlewin99** [IIC2233/syllabus#101]
[redacted]

**Comment by KnowYourselves** [comment]
Hola @nlewin99!

Recuerda que está estrictamente prohibido publicar código en el foro.
Puedes hacer otra _issue_ pidiendole a un ayudante que revise tu repo, pero no puedes subir código.

Saludos!

**Comment by nlewin99** [comment]
ok gracias y disculpa
