### ISSUE TITLE
Error en test de reemplazar tablero

### ISSUE THREAD

**Issue by ChupeteBecker** [IIC2233/Syllabus#101]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En los tests de tes_tablero_reemplazar me tira error porque no encuentra el archivo tableros.txt, siendo que ese archivo esta dentro de la carpeta T1 y dentro de la carpeta de los tests. Ademas estoy seguro que abri el archivo bien porque sino me tiraria algun error de sintaxis. No se que puede estar fallando.

**Comment by ChupeteBecker** [comment]
Me pasa ahora que si abro una terminal en vscode y corro ahi el codigo, si funciona, lo mismo en la termial de ubuntu, solo falla cuando hago el run en vscode

**Comment by dvillas28** [comment]
trata de ver desde que path se esta haciendo ese run en el vsc

**Comment by ChupeteBecker** [comment]
se hace en el mismo path donde se corre el codigo en las distintas terminales

**Comment by ManuelV03** [comment]
Hola, VScode es una herramienta para escribir código, no una para ejecutarlo por lo que es posible que falle. Por este motivo los incentivamos a que corran su código en la terminal, lo cual, dijiste que si te funcionaba bien así que sigue corriendo el código en la terminal. Avísame que tal.
