### ISSUE TITLE
Duda sobre herencia y multiherencia

### ISSUE THREAD

**Issue by MatiSick** [IIC2233/Syllabus#101]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola!, tengo una pregunta,  es sobre el orden de la multiherencia al momento de heredar desde una clase hija 2 o mas clases. En este caso, en el init de la clase hija y en el super de la clase padre se deben poner todos los atributos y en el orden de las clases padre?. Y cual sería ese orden?, es desde la clase de la izquierda a la derecha?. Y si ambas clases tienen un mismo atributo pero con distintos valores como sé cual es el que será heredado por la hija?.

Gracias :)

**Comment by tqmbanados** [comment]
Hola @MatiSick!
Creo que no entiendo del todo tu duda. Si es que entiendo bien, surge del problema con los argumentos del `__init__` al usar multi-herencia. Una cosa que te puede servir para entender mejor como funciona es pensar el `__init__` y el `super().__init__` como métodos normales de Python. Es decir, cuando instancias una clase nueva, lo que ocurre es que el programa ejecuta varias líneas de código tal cual como si llamaras una función. 

Algunas de estas líneas de código ocurren por detrás, pero no debemos preocuparnos de ellas. Lo importante es lo que ocurre en el método `__init__`, que se comporta tal cual como un método cualquiera. 
Es decir, ejecutará cada línea en el orden que está escrita. Si una de estas líneas es otra función o método, ejecutará esa función o método en el orden de sus líneas. Esto incluye el llamado a `super().__init__()`. Es decir, cuando se encuentre con esa línea, ejecutará todas las líneas en el `__init__` de la super-clase. 
Para explicarlo mejor, te propongo el siguiente ejemplo. 
Lo ideal es que copies el código y lo corras para entender bien el orden en que ocurren las cosas.

```python
class SuperA:
    def __init__(self, nombre, apellido, *args, **kwargs):
        self.valor_prueba = "A"
        print(nombre)
        super().__init__(*args)
        print(apellido)


class SuperB:
    def __init__(self, profecion, efectividad, *args, **kwargs):
        print(profecion)
        super().__init__(*args)
        self.valor_prueba = "B"
        print(efectividad)


class HijaMayor(SuperA, SuperB):
    def __init__(self, nombre, apellido, profecion, efectividad):
        super().__init__(nombre, apellido, profecion, efectividad)
        print(self.valor_prueba)


class HijaMenor(SuperB, SuperA):
    def __init__(self, nombre, apellido, profecion, efectividad):
        super().__init__(profecion, efectividad, nombre, apellido)
        print(self.valor_prueba)


test1 = HijaMayor("ESTER", "ES", "UN", "EJEMPLO")
test2 = HijaMenor("ester", "es", "otro", "ejemplo")
``` 

Al correr el código anterior, podemos ver el orden en que se ejecutan las cosas por los print:
```
ESTER
UN
EJEMPLO
ES
B
otro
ester
es
ejemplo
B
```

Si te fijas, la clase HijaMayor, parte llamando el `__init__()` de `SuperA`, pues esta está más a la izquierda. Esta comienza seteando un valor prueba al valor `"A"`. Luego imprime el primer argumento (`nombre`, cuyo valor es `"ESTER"`). Depués, llama al `__init__` de `SuperB`. Esta también imprime el primero argumento que recibe (que corresponde al tercer argumento que recibió `SuperA`). Luego hace un llamado a `super().__init__()` que no tiene efecto (pues `SuperB` está al final del orden de resolución de métodos, o `mro`). Finalmente imprime el segundo argumento que recibe, (es decir el cuarto argumento que recibió `SuperA`), y setea el mismo atributo `valor_prueba` a `"B"`, cambiando su valor. Luego, `SuperA` continúa el `__init__`, imprimiendo el segundo valor que recibió. **Finalmente**, `HijaMayor` imprime el atributo `self.valor_prueba`, que tiene el valor `B`, dado que este fue el último que se le asignó.

Este párrafo se ve largo y complicado, pero si lo lees viendo el código lo entenderás mejor.

Para la clase `HijaMenor` ocurren cosas bien parecidas, pero hay una diferencia importante: El valor final de `self.valor_prueba` sigue siendo `B`.  Esto es por que, si bien el `__init__` de `SuperA` se llama en teoría después del `__init__` de `SuperB`, este se llama **ANTES** de que `SuperB` setee su valor a `"B"`. Es decir, si ambas clases padres tienen un atributo del mismo nombre, el valor final que este tendrá no depende del orden en que se encuentren en la definición de la sub-clase, si no en cómo se estructuran sus `__init__`. 

La pregunta de los `args` y `kwargs` me gustaría que la reredactaras un poco para entender mejor tu confusión! Igual, si te fijas, en este ejemplo también hacemos uso de `args`, por lo que quizás encuentres ahí tu respuesta.

**Comment by MatiSick** [comment]
Muchas gracias por la respuesta, realmente me quedo muy claro con la explicación. Tenía una confusión con los ordenes pero ya lo entendí. Te pasaste de verdad!

**Comment by tqmbanados** [comment]
Me alegro muchísimo! Recuerda no cerrar las issues, pues pueden servirle a alguien más :)
