### ISSUE TITLE
Duda Idioma PEP8

### ISSUE THREAD

**Issue by Cschavez** [IIC2233/Syllabus#101]
Hola! leyendo las reglas PEP8 dice que ojalá se escriba el código en ingles al menos que este seguro que este no será leído por personas que no hablen mi idioma. Para efectos del curso, ¿es estrictamente necesario escribirlo en ingles? 
Muchas gracias !

**Comment by fgbruna** [comment]
[#12](https://github.com/IIC2233/Syllabus/issues/12)
