### ISSUE TITLE
Error al ejecutar interfaz gráfica AS04 

### ISSUE THREAD

**Issue by ssoliva** [IIC2233/syllabus#1010]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Al ejecutar el archivo main.py correspondiente a la interfaz gráfica de la AS04 me tira el siguiente error:

***This Windows version (6.3.9600) does not support de required Bluetooth API. Consider***
***updating to a more recent Windows (10.0.10586 or above).***

Qué significa? Y es posible que me afecte para la tarea 3? (Es necesario actualizarlo? :disappointed:  )

**Comment by aaossa** [comment]
Hola @ssoliva , ¿te ocurre este error con otros archivos de interfaces? Con les ayudantes tuvimos un caso similar durante la actividad y al final era que estaba usando `dumps` en lugar de `dump` (o `loads` en lugar de `load`, no recuerdo), por lo que quizás haya sido coincidencia y en verdad no sea algo grave. ¿Podrías avisarme si te siguió ocurriendo? ¿Te ocurre lo mismo con otros archivos? Démosle un par de vueltas para descartar qué cosas podrían ser 👌

**Comment by Agustinuv** [comment]
Hola, me pasó lo mismo en la actividad y estuve buscando por qué pudo haber sido el error y encontré en algunas partes que había personas que les pasaba algo parecido cuando importaban Qt (en este [link](https://issues.qgis.org/issues/20867) dicen que su error se fue cuando borraban la línea: `from PyQt5.Qt import *` .
Probé comentando la línea 6 de ventanas.py se se me solucionó (`#from PyQt5 import  Qt`). 
¿Cuál es la función de importar este módulo? Ya que no encontré en el código su uso
