### ISSUE TITLE
Duda sobre lenguaje de programación de un código

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#1010]
Hola, esto no tiene que ver con el curso en sí, pero estoy segura que algunos ayudantes saben más que solo python :D 
Tengo la duda del lenguaje de programación que tiene el siguiente código:
![image](https://user-images.githubusercontent.com/59337116/84451266-995a8a00-ac20-11ea-91cf-f1a0968b64f2.png)
Ahora, si no es mucho, quería saber si era posible pasar esto a python? utilizando las siguientes librerias: 
![image](https://user-images.githubusercontent.com/59337116/84451340-cf980980-ac20-11ea-8a7c-356b0cc7cf1b.png)
Gracias y ojalá puedan ayudarme jiji :smile:

**Comment by benjavicente** [comment]
Hola! Yo conozco `matplotlib` y `numpy` :D

`t` parece ser un vector espaciado uniformemente entre 0 y 2. En python se puede usar [`np.linspace`](https://numpy.org/doc/1.18/reference/generated/numpy.linspace.html).

`cos`, `pi`, `floor`, `e` están también en numpy.

Los puntos parece que representan [_operaciones entre elementos_](https://math.boisestate.edu/~calhoun/teaching/matlab-tutorials/lab_31/html/lab_31.html#:~:text=To%20use%20Matlab%20terminology%2C%20we,'%2C%20.%2F%20or%20'.). Creo que en python no son necesarios.

El plot es casi de la misma manera, `plt.plot` y `plt.title`.

**Comment by Alonsinho1** [comment]
Hola! Te recomiendo que señales cual es el lenguaje de origen, asi es más facil ayudarte, Sin embargo parece ser MatLab.

Con los dos links que te entrego @benjavicente se te hará super simple traducirlo, ya que las operaciones que estas haciendo no son complejas. Sin embargo, si estas traduciendo por que python te manejes mejor, te recomendaría hacerlo solo si es muy necesario. Siempre es mejor manejarse en varios lenguajes (Por algo existen varios y no solamente uno)

Saludos!

**Comment by Camila-sty** [comment]
Graciaaas!!
