### ISSUE TITLE
Duda actividad S04, pickle

### ISSUE THREAD

**Issue by bpardobravo** [IIC2233/syllabus#1011]
Hola, estaba tratando de hacer la parte de pickle de la actividad (no la entregué), y me sale el siguiente error:
![image](https://user-images.githubusercontent.com/48322933/84463619-53152300-ac40-11ea-9537-66b977d4c4ed.png)
![image](https://user-images.githubusercontent.com/48322933/84463622-59a39a80-ac40-11ea-88e0-3863d128b7e2.png)
Alguien entiende que pasa?

**Comment by Alonsinho1** [comment]
Hola recuerda que `__setstate__` es la función que te permite desearlizar los archivos pickle. Esta recibir un diccionario con los atributos del objeto. En la función desearlizar debes usar los valores de este diccionario para poder setear estos atributos como los que tendra tu instancia de la clase respectiva.

__¿Cómo relacionamos los atributos de este diccionario con el de la instancia definida en python?__

Recuerda que todas las instancias tienen un diccionario asociado con sus atributos el cual llamamos utilizando `__dict__`. Si cambiamos los values de este diccionario, tambien cambiaremos los valores de los atributos de la clase. Por ende, en `__setstate__` debemos, alterar el diccionario que recibe la función (Si es que deseamos cambiar el metodo default de desearlizacion) y luego hacer lo siguiente `self.__dict__ = diccionario_recibido`.

Si cambias la linea return por `self.__dict__ = diccionario_recibido`. ese error en particular se arreglara. Espero te haya servido!

Saludos ! ( :D )->-<
