### ISSUE TITLE
Me aparece un error que no entiendo (OSError: [WinError 10013])

### ISSUE THREAD

**Issue by yuwet15** [IIC2233/syllabus#1012]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

En el segundo cuaderno de esta semana, al tratar de crear servidor me da problema sock.bind((host, port)), y me tira error OSError: [WinError 10013], he buscado en internet pero no he podido solucionarlo

**Comment by jarvasquez** [comment]
Según yo es por los permisos que tiene python en tu computador. El firewall debería haber saltado y te preguntó si le podías conceder acceso a python para que pudiera acceder tanto a redes públicas como a privadas, y en una de esas le negaste el permiso. Puede ser?

**Comment by jarvasquez** [comment]
Si es así, debes buscar las configuraciones del FireWall para poder darle acceso a python con redes públicas y privadas, ahora estoy probando si me sirve. Te cuento como me va.

**Comment by jarvasquez** [comment]
Lo logréeeee!!! Le cambié el número del puerto jajajajajajj intenta con eso (y revisa lo del FireWall de todas formas)

**Comment by yuwet15** [comment]
okok muchas gracias :D

**Comment by aaossa** [comment]
@yuwet15 @jarvasquez ¿pudieron arreglarlo cambiando el número dep uerto? Me suena que puede ser que hayan estado especificando mal el *host* o usando un *port* protegido (con un número bajo). No debería ser necesario meterse con configuraciones de *firewall* 😅 Tengan cuidado con eso 👀

**Comment by yuwet15** [comment]
@aaossa sisi, se logró cambiando el puerto, pero profe, se puede saber porque causa ese problema el puerto?😅

**Comment by aaossa** [comment]
Lo único que se me ocurre, @yuwet15, es que quizás hay otra aplicación utilizando ese puerto 🤔. Una manera de revisar esto (al menos en Windows, no pude probar en otros OS) es utilizando el comando `netstat -aon | findstr 9000` (en lugar del 9000 usar el puerto que quieras ver). Eso te mostrará de dónde vienen las conexiones a ese puerto. El último numerito es el número de proceso asociado a la aplicación, en mi caso ese numerito era 18692. Para ver en específico cuál aplicación es, tienes que usar el comando `tasklist | findstr 18692` (cambiar con el número de proceso que corresponda) y como *output* me apareció justo el nombre de la aplicación que correspondía 👌 

Si haces eso, avisa por acá cuál era la aplicación, en una de esas el ejemplo ahora topa con una aplicación popular (digamos Spotify 😱) por lo que habría que cambiar el ejemplo de los contenidos 🤔

**Comment by yuwet15** [comment]
Lo acabo de probar, y la aplicacion que me usa ese puerto es "CloudHelper.exe"

**Comment by aaossa** [comment]
🤔 La verdad no me suena conocida esa aplicación, así que no creo que sea algo masivo. De todas maneras, ahora ten ojo con no usar ese puerto para no tener problemas no más 👌 Muchas gracias 🙌

**Comment by YehudaGurovich** [comment]
@aaossa Tengo el mismo problema pero el puerto 9000 me sale disponible. No se a que se debe :/.

**Comment by tocococa** [comment]
El problema que tenía @YehudaGurovich era (muy probablemente) debido a un VPN instalado, desinstalar el VPN y asegurarse de que los drivers del adaptador virtual instalado por el mismo estuvieran desinstalados solucionó el problema. Aparte de eso, correr los siguientes comandos desde CMD como administrador: `netsh winsock reset` y  `netsh int ip reset` pudo haber ayudado.
