### ISSUE TITLE
Recorreción T01

### ISSUE THREAD

**Issue by vobrador** [IIC2233/syllabus#1012]
Holaa! Estaba revisando el excel de notas y quería saber si la de la T01 incluye la recorrección o no? De ser así, donde puedo revisar esta recorrección?

**Comment by bvasquezm** [comment]
Hola @vobrador!

Las re-correcciones son subidas en el Excel. Si aún no están subidas, deberás esperar un poco. Te darás cuenta si hubieron cambios en los comentarios del los ítems que mandaste a re-corregir, la nota puedo haber cambiado como no. Saludos!

**Comment by vobrador** [comment]
Gracias! pero te queria preguntar donde puedo encontrar esos comentarios? en canvas no los encontre en la seccion de tareas ni de calificaciones, si los pude ver hace semanas antes de mandar a recoregir pero no recuerdo donde

**Comment by benjavicente** [comment]
Hola! Los comentarios están en las issues de tu repositorio personal.

Puede que este link te lleve directamente
https://github.com/IIC2233/vobrador-iic2233-2020-1/issues/8

**Comment by bvasquezm** [comment]
Les debería haber llegado un correo con la información. Saludos 😄!
