### ISSUE TITLE
Error al ejecutar archivos de la carpeta "codigo_base" semana 14

### ISSUE THREAD

**Issue by fran-gl** [IIC2233/syllabus#1013]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, al tratar de ejecutar los archivos de la carpeta "codigo_base" de los contenidos de la semana 14 me aparecía el siguiente error:

gaierror: [Errno 8] nodename nor servname provided, or not known

En internet encontré que al reemplazar ```socket.gethostname()``` por ```socket.gethostbyname("")``` el problema se solucionaba. Sin embargo, no funcionó cuando hice lo mismo en los ejercicios propuestos. Existe otra forma de solucionar el error? Muchas gracias de antemano.

**Comment by MatiasDuhalde** [comment]
Hola @fran-gl !

El error puede deberse a un error de configuración con las redes de tu computador! Sin embargo, la manera más fácil sería cambiar la dirección del host tanto del servidor como del cliente. Es probable que una de las siguientes strings te funcione: `"localhost", "127.0.0.1", "0.0.0.0"`.
Por lo tanto, sólo bastaría cambiar la línea `host = socket.gethostname()` a `host = "localhost"` de cada archivo (o alguna de las otras strings en vez de `localhost`).

Con respecto al error que te da, fíjate bien en qué retorna la función `socket.gethostname()` (intenta usar un print). Debería ser el nombre de tu dispositivo. Normalmente el sistema operativo debería reconocerlo como un host válido, pero falla porque puede que falten ciertas configuraciones. En una [issue del semestre pasado](https://github.com/IIC2233/syllabus-2020-1/issues/1020), la solución fue editar el archivo `hosts`. Su ubicación y las líneas que necesita dependerían de cada sistema operativo.

Sin embargo, te recomiendo intentar lo de cambiar la string del host, ya que debería ser suficiente para solucionar el problema.

**Comment by fran-gl** [comment]
Oka, muchísimas gracias.
