### ISSUE TITLE
Herencia

### ISSUE THREAD

**Issue by rieg-ec** [IIC2233/syllabus#1014]
Hola! haciendo una tarea para optimizacion queria usar la clase Model de gurobi como base para mi propia clase

ejemplo:
```python3
from gurobipy import Model as GurobiModel
class Model(GurobiModel):
    def __init__(self, name):
        super().__init__(name)
        self.Y = 6

model = Model('nombre')
```

pero me lanza error 

```AttributeError: 'gurobipy.Model' object has no attribute 'Y'```

no se si es posible ver el codigo fuente porque es una api comercial, pero me queda la duda de si hay casos en donde no se puede agregar atribibutos a la clase parent :thinking:

**Comment by rieg-ec** [comment]
y me pasa con cada atributo que quiera agregar en el constructor de la clase child :(

**Comment by benjavicente** [comment]
Pude replicar el error con el siguiente código:
```py
class GurobiModel:
    def __init__(self, name):
        self.name = name

    def __setattr__(self, attribute, value):
        if attribute not in {'name'}:
            raise AttributeError(f"'gurobipy.Model' object has no attribute {attribute}")

class Model(GurobiModel):
    def __init__(self, name):
        super().__init__(name)
        self.Y = 6

model = Model('nombre')
```
Puede que la clase padre tenga el método `__setattr__` que impida agregar nuevos atributos, entonces lo que podría funcionar es sobreescribir este método para aceptarlos.

```py
class Model(GurobiModel):
    def __init__(self, name):
        super().__init__(name)
        self.Y = 6

    def __setattr__(self, attribute, value):
        object.__setattr__(self, attribute, value)
```

**Comment by rieg-ec** [comment]
Efectivamente ese era el problema! gracias!
