### ISSUE TITLE
Problema de ejecución - Networking

### ISSUE THREAD

**Issue by frosatis** [IIC2233/syllabus#1015]
Hola!
Intentando ejecutar el código proporcionado en los contenidos me sale este error:
OSError: [WinError 10048] Solo se permite un uso de cada direcci▒n de socket (protocolo/direcci▒n de red/puerto)
Se arregla cuando cambio el id del puerto en el código, pero funciona una sola vez y luego vuelve a arrojar el error. Es normal? cada vez que pruebo algo debo cambiar el número de puerto?

**Comment by MatiasDuhalde** [comment]
Hola @frosatis !

Efectivamente, esto se debe a un problema con los puertos de tu sistema operativo. Cuando conectas un socket a un puerto para que pueda escuchar en él (i.e. cuando haces `socket.bind((host, port))`), este se adueña temporalmente del puerto. Si posteriormente otro socket distinto intenta escuchar en el mismo puerto, el sistema operativo lo evitará y se levantará la excepción que comentas.

Un ejemplo:

```python
import socket

sock_a = socket.socket(socket.AF_INET, socket.STREAM)
sock_a.bind(("localhost", 12345)) # El socket sock_a se adueña del puerto 12345

sock_b = socket.socket(socket.AF_INET, socket.STREAM)
sock_b.bind(("localhost", 12345)) # El socket sock_b intenta tomar el puerto 12345, pero falla :(
```

¿Cómo se puede evitar que falle? Primero debes cerrar el primer socket usando `socket.close()` (`sock_a.close()` en este caso), antes de asignar otro socket al mismo puerto.

Probablemente en tu caso, el programa "termina", pero el socket continúa ocupando el puerto, por lo tanto, al ejecutarlo de nuevo, este fallara dado que el puerto está ocupado.

Ojalá esto te ayude a entender el error 😃

**Comment by EmeraldMP** [comment]
Hola, tengo el mismo problema. Apesar de hacer socket.close()  ( que en el caso del codigo en los contenidos es sock.() ) sigue apareciendo el mensaje [WinError 10048] Solo se permite un uso de cada dirección de socket (protocolo/dirección de red/puerto). A qué se podría deber?

**Comment by MatiasDuhalde** [comment]
Hola @EmeraldMP !

Qué código estás ejecutando exactamente? Se me ocurre que esto puede deberse a que corres nuevamente el código, pero todavía hay una instancia anterior que aún lo está ejecutando. En otras palabras, la ejecución anterior nunca termino por completo. Se puede dar también que algún thread no-daemon siga ejecutandose luego del término del programa, y que siga manteniendo al socket en memoria (y el puerto ocupado). Te recomiendo intentar revisar si hay instancias del programa aún ejecutandose, usando el administrador de tareas o similar.

También, en algunos casos, el sistema operativo tarda en soltar el puerto ocupado por el socket (espera a un *timeout*), esto debido a la manera cómo funciona TCP. Sin embargo, en general este timeout es bastante corto, por lo que en la mayoría de los casos no debería ser un problema.

Avísanos si pudiste solucionar el problema! 😄

**Comment by EmeraldMP** [comment]
Siii, alli me funcionó 😊
