### ISSUE TITLE
Recomendación en caso de modificar archivos de repositorio de contenidos

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#1015]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, quisiera saber que se recomienda hacer en caso de que modifiquemos los archivos de contenidos como por ejemplo los ejercicios propuestos, para que no aparezca todo el rato que tenemos cambios pendientes para hacer push. Una opción es pasar todo a otra carpeta en mi computador, alguna otra opción a nivel de git. Yo siempre he obviado esto y sigo haciendo git pull pero ahora no se terminó el proceso de descarga de los contenidos de la semana 14 y ahora no me vuelve a dejar hacer git pull. Me aparece el siguiente error: *error: Your local changes to the following files would be overwritten by merge: ....*. Que solución existe? gracias.

**Comment by aaossa** [comment]
Hola @Gustav2000 , lo que te recomendaría es utilizar un comando de git que funciona como un "bolsillo". Un flujo que recomendaría es el siguiente:

1. Trabajar en los *notebooks* de contenidos y de ejercicios
2. Antes de bajar los nuevos cambios, usar el comando `git stash` para "guardar los cambios en el bolsillo"
3. Bajar los cambios en el repositorio de contenidos con `git pull`, lo que actualizará tus archivos locales
4. Ahora que tienes los cambios en tu repositorio local, usa `git stash pop` para "sacar los cambios del bolsillo"
5. Repetir desde 1...

Ahora, si en algún momento tienes un error como el que mencionas, probablemente se deba a que uno de los *commits* que estás "bajando" cambió un archivo que tú también modificaste. Para poder responderte mejor, ¿podrías mostrarme una captura del error y del *output* del comando `git status`? ¡Gracias ✨!

**Comment by Gustav2000** [comment]
Muchas gracias, ahí me funcionó!!
