### ISSUE TITLE
Errores al ejecutar codigo propuesto Networking

### ISSUE THREAD

**Issue by anamarn** [IIC2233/syllabus#1016]
Hola ! Estaba ejecutando el código de los Ejemplos de receptores y emisores mejorados y me sale este error: 
sock.connect((host_receptor, puerto_receptor))
ConnectionRefusedError: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión

También al intentar ejecutar el codigo 3. receptor json me aparece el
sock.connect((server_host, server_port))

OSError: [WinError 10049] La dirección solicitada no es válida en este contexto
 
Como lo soluciono? Es alguna cosa de firewall? Si es así como la cambio?
Gracias

**Comment by MatiasDuhalde** [comment]
Hola @anamarn !

Con respecto al error `ConnectionRefusedError: [WinError 10061]`, la causa más común es que intentas conectarte a un servidor que no está abierto. Para solucionar esto, bastaría con ejecutar primero el código del receptor, y luego el del emisor.

Con respecto al error `OSError: [WinError 10049]`, al parecer usar un string vacío como dirección del host tiene comportamientos distintos en diferentes plataformas. Una solución sería reemplazar `server_host  = ''` por `server_host = socket.gethostname()` (similar a como sale en el servidor).

Avísanos si eso resuelve tu error! 😄
