### ISSUE TITLE
Duda EJ3, Serializacion Semana 13

### ISSUE THREAD

**Issue by MagyarSplit** [IIC2233/syllabus#1016]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Estoy tratando de serializar las obras a "lista_obras.bin", y escribir el mensaje en el formato pedido nome-autore.opera, pero al tratar de hacerlo me entrega algo de la siguiente forma, en cada linea, notesen los caracteres no reconocidos:
 ```q)�qX4���Il Giovane del Christinno - Fernandino Alfaro.opera ```

Aqui pongo las funciones que me causan conflicto, son bien cortitas...
(lista_obras es una lista con cada instancia Obra, ya filtrado los atributos importantes), el mensaje actualizado no es el pedido, pero para simplificar puse ese.

 ```
def generar_mensaje(lista_obras): 
    with open("lista_obras.bin", "wb") as file:
        pickle.dump(lista_obras, file)

def __getstate__(self):
     nueva = self.__dict__.copy()
     nueva.update({"mensaje" : "¡Me están serializando!"})
     return f'{self.nome} - {self.autore}.opera\n'  ```

Muchas Gracias

**Comment by aaossa** [comment]
Hola @MagyarSplit , lo que ocurre es que estás haciendo mal la serialización 😅 Recuerda que `__getstate__` debe retornar un diccionario con los atributos que se quieren serializar, no un *string*. En resumen, tienes que retornar `nueva` en tu método `__getstate__` 👌 Cuéntame si es o te funciona, y si tienes más dudas pregunta por acá mismo 🙌

**Comment by MagyarSplit** [comment]
Hola, tengo claro eso, pero en el enunciado dice que debo escribir en el archivo de serializacion para cada obra el formato  ```nome-autore.opera ``` , y si hago lo que me dice, se debería escribir en el archivo de serializacion un diccionario copia de cada obra, pero este es un formato distinto al pedido, entonces, que hago para lograr lo pedido?
Saludos

**Comment by aaossa** [comment]
A lo que se refiere el formato es al nombre del archivo, no al contenido. El contenido debe ser la obra serializada, mientras que el nombre del archivo depende de los atributos 👌
