### ISSUE TITLE
[Semana 14, ejemplo 1] WinError 10016, conexión denegada por el equipo de destino 

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2233/syllabus#1017]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Hola! Traté de hacer la prueba del ejemplo 1 "Envío de JSON", pero cuando ejecuto el script desde el computador del cliente (una vez que ya está corriendo el script en el computador servidor) me lanza el siguiente error:

![image](https://user-images.githubusercontent.com/64439029/99279345-e6194100-280e-11eb-95cf-36abdd081458.png)

Mi código es exactamente el mismo que aparece en el _jupyter_, a excepción de que en la implementación del cliente a la variable `server_host` le di la dirección IP del computador servidor. 

Gracias y saludos :)

*Edit*: traté de hacer el mismo ejercicio corriendo los dos scripts en un solo computador e igualmente me lanzó el mismo error.

**Comment by aaossa** [comment]
Hola @ignaciomansuy , quizás no te acepte porque no está identificando la conexión como local, ¿podrías probar usando como *host* el *output* de `socket.gethostname()`? Cuéntame cómo te va con eso 👌

**Comment by ignaciomansuy** [comment]
Hola @aaossa, me funcionó! ¡Muchas gracias!
Tengo un par de dudas:
*  ¿Qué quiere decir que una conexión sea local? 
*  ¿Cuándo debo ocupar `socket.gethostname()` como el host y cuando debo ocupar la dirección IP de mi computador? 
*  `socket.gethostname()` retorna un string (DESKTOP-5IC...), asumo que ese string no equivale a la IP de mi computador, ¿es el método `bin` el que realiza la transformación del string a la IP?

¡Saludos! :)

**Comment by ignaciomansuy** [comment]
Hola de nuevo @aaossa, pese a que me funcionó corriendo los dos scripts en mi computador,  acabo de intentar hacer el ejemplo con dos computadores y me lanza el siguiente error:

![image](https://user-images.githubusercontent.com/64439029/99463851-75a91780-2915-11eb-9358-8dcabeeedc33.png)

Ambos computadores están conectados a la misma red wifi. 

¡Gracias por tu ayuda!

**Comment by aaossa** [comment]
Hola @ignaciomansuy ,

Para responder tus preguntas voy a simplificar algunas cosas y voy a apoyarme en la metáfora de que un edificio corresponde a una dirección IP y cada ventana/departamento a un puerto de esa dirección (imagen de los contenidos):

![imagen](https://user-images.githubusercontent.com/10425834/99471595-9ed1a400-2925-11eb-903d-7ec47c8aae40.png)

Simplificando un poco las cosas, piensa que lo que le das a tu programa es una dirección solamente, una referencia de dónde está el otro *socket* al que te quieres conectar. Si le das una dirección local, digamos "este mismo edificio pero en el departamento 8080" el programa sabe que no tiene que "salir a la calle" a buscar otro "edificio". Si le das una dirección remota, algo como "en el edificio 146.155.95.60 en el departamento 443", tu programa sabe que sí debe "salir a la calle" a buscarlo. 

En Python, la manera de obtener la dirección que especifica la actual (la local, la del *host*) es el método `socket.gethostname()`. Si usas esa dirección para un "edificio", tu programa sabe que no debe "salir a la calle". Para todo lo que hacemos en este curso, debería ser suficiente usar `socket.gethostname()` y no debería ser necesario utilizar otros valores.

Para poder conectar más de un computador en una misma red a veces sí es necesario configurar adecuadamente otros temas que van más allá de Python. En este curso eso no está cubierto porque no es algo que les pidamos ya que esperamos que puedan comunicar dos programas independientes dentro de un mismo equipo, y la verdad no estoy 100% seguro de cómo hacerlo 😅 Si es algo que quieres probar de todas maneras, avísame por acá mismo y puedo pedirle a les ayudantes que le den una mirada a esta *issue* para responderte 🤓 

¡Ojalá te sirva esta respuesta ✨!

PS: El *built-in* `bin` convierte un número a binario, no debería ser necesario en este conexto.

**Comment by ignaciomansuy** [comment]
Hola @aaossa, entiendo tu explicación, muchas gracias!
Sin embargo, sigo teniendo el siguiente error cuando trato de conectar dos computadores que están conectados a la misma red wifi:

![image](https://user-images.githubusercontent.com/64439029/99526396-f7cb2780-2979-11eb-81ac-8d70eacb1573.png)

Adjunto el código que estoy corriendo:

-**Servidor**
```import socket

host = socket.gethostname()
print(socket.gethostname())   # Esto obtiene el nombre en la red de este host
port = 12222

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.bind((host, port))
print("Listo para recibir. Ahora voy a esperar que me hablen...")
sock.listen()
print('escuchando')
sock_cliente, (host_cliente, puerto_cliente) = sock.accept()
print("Conexión desde", host_cliente, puerto_cliente)

while True:
    data = sock_cliente.recv(4096)
    print(f"Recibí estos bytes: {data}")
    if not data:
        break
    print("Los enviaré de vuelta")
    sock_cliente.sendall(data)

sock_cliente.close()
sock.close()
```

**Cliente**
```import json
import socket

server_host = 'DESKTOP-5ICVDP5'  # Debemos poner aquí la dirección IP del servidor.
                  # Si no ponemos nada, supone que estamos hablando con un programa en el mismo host.
server_port = 12222

# Generamos la información que enviaremos; en este caso, es un simple diccionario.
data = {1: "Hola", 2: "Chao"}
mensaje = json.dumps(data)

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((server_host, server_port))

# Debemos enviar bytes.
sock.sendall(mensaje.encode('utf-8'))

# Decodificamos los bytes y luego los deserializamos con JSON.
data = json.loads(sock.recv(4096).decode('utf-8'))
print(data)
input("ENTER para terminar.")
sock.close()
```

**Comment by aaossa** [comment]
Antes de darle una vuelta a eso, ¿te funciona el correr los ejemplos dentro de un mismo equipo?

**Comment by ignaciomansuy** [comment]
Si, me funciona en un mismo equipo.

**Comment by OrregoSilva** [comment]
Hola @ignaciomansuy y @aaossa 

Yo tenia la misma duda y logre solucionarlo, lo que hice fue:

**SERVER:**
`host = socket.gethostbyname(socket.gethostname())`
`port = 12345`

**CLIENT:**
`server_host = #El resultado de host en el server`
`port = 12345`

Espero que sea de ayuda!.

**Comment by ignaciomansuy** [comment]
Hola @OrregoSilva ! Probé las indicaciones pero sigue tirandome el mismo error :( 
Gracias igual por la ayuda!

**Comment by ignaciomansuy** [comment]
Hola @aaossa! Quería saber si me podrías seguir ayudando (o algún otro ayudante) a resolver el error (tratar de conectar localmente dos computadores) que mencioné más arriba, por favor.
Saludos :)

**Comment by MatiasDuhalde** [comment]
Hola @ignaciomansuy ! Estuve probando los códigos en mi red local, y me pude encontrar con un error parecido, pero no igual. El error tiene que ver con la configuración de redes, es algo aparte a python y dependería de cada computador o cada red local.

Lo que hace `socket.gethostname()` es obtener el nombre del dispositivo. Por ejemplo, en el código de arriba daba como output `'DESKTOP-5ICVDP5'`, y a mi me da algo similar: `'DESKTOP-ESFARS4'`. Un problema que puede surgir con esto es que estos nombres no se "registran" o no se "reconocen" correctamente por los otros miembros de la red, por lo que no es posible acceder a los hosts mediante este método.

Lo que te podría recomendar sería conseguir directamente las direcciones IP locales de cada dispositivo. Por ejemplo, en Windows bastaría con usar el comando `ipconfig`:

![image](https://user-images.githubusercontent.com/46191755/100140089-3cb9f700-2e6f-11eb-91b9-f48fbfae638d.png)

Y en Linux o Mac, se puede hacer con el comando `ifconfig`

![Screenshot from 2020-11-24 19-09-49](https://user-images.githubusercontent.com/46191755/100140641-00d36180-2e70-11eb-8e1d-0a6522cd4479.png)

De esta manera, los códigos quedarían así:


**Servidor**
```python
import socket

host = '192.168.1.143' # Acá lo tendrías que cambiar.
port = 12345

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.bind((host, port))
print("Listo para recibir. Ahora voy a esperar que me hablen...")
sock.listen()
print('escuchando')
sock_cliente, (host_cliente, puerto_cliente) = sock.accept()
print("Conexión desde", host_cliente, puerto_cliente)

while True:
    data = sock_cliente.recv(4096)
    print(f"Recibí estos bytes: {data}")
    if not data:
        break
    print("Los enviaré de vuelta")
    sock_cliente.sendall(data)

sock_cliente.close()
sock.close()
```


**Cliente**
```python
import socket
import json

server_host = '192.168.1.143' # Acá lo tendrías que modificar
server_port = 12222

# Generamos la información que enviaremos; en este caso, es un simple diccionario.
data = {1: "Hola", 2: "Chao"}
mensaje = json.dumps(data)

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((server_host, server_port))

# Debemos enviar bytes.
sock.sendall(mensaje.encode('utf-8'))

# Decodificamos los bytes y luego los deserializamos con JSON.
data = json.loads(sock.recv(4096).decode('utf-8'))
print(data)
input("ENTER para terminar.")
sock.close()
```

Un par de notas extras:
- Intenta que los computadores estén conectados al mismo punto de acceso, para descartar otros errores de networking que puedan suceder.
- Asegurate de que tus dispositivos tengan el permiso para ser descubiertos por otros miembros de la red (network discovery), puede que eso cause problemas.
- Asegurate que Python tenga los permisos para comunicarse con otros miembros de la red (en Windows aparece un popup que pide los permisos).

**Comment by ignaciomansuy** [comment]
Muchas gracias @MatiasDuhalde !!! Mi problema era que mi dispositivo estaba oculto para los otros miembros de la red. Se aprecia mucho tu ayuda!
Saludos :)
