### ISSUE TITLE
Problema conexión con computadores fuera de mi red

### ISSUE THREAD

**Issue by mpenalozag** [IIC2233/syllabus#1017]
No puedo tener el servidor y que un pc fuera de mi red se conecte, creo que es un problema de cuál ip usar. Probé con la que sale acá https://whatismyipaddress.com/es/mi-ip y nada :(

**Comment by tocococa** [comment]
creo que tienes que hacer port forwarding en tu router para que un equipo fuera de tu red se pueda conectar a tu servidor python.

**Comment by MatiasDuhalde** [comment]
Hola @mpenalozag !
Para entender bien lo pasa, ayuda imaginarse el camino que recorre un mensaje/paquete desde el cliente (fuera de tu red) hasta el servidor (en tu misma red). Cuando el cliente envía un mensaje, este viaja desde su computador y llega al router que posee la dirección pública (por ejemplo, la que te aparece aquí: https://whatismyipaddress.com/es/mi-ip ). El problema, es que puede haber varios dispositivos conectados a tu router, por lo que este no sabe a cual específicamente redireccionarle el paquete que recibió. Una manera de hacer esto, como mencionó @tocococa, es haciendo *Port Forwarding* dentro de las configuraciones de tu router, de manera que los mensajes recibidos en cierto puerto del router se redireccionen hacia el dispositivo deseado dentro de la red local (que en este ejemplo, sería el computador que está ejecutando el servidor). 

La forma de hacer este *Port Forwarding* varían dependiendo del modelo del router, pero generalmente se pueden encontrar tutoriales en internet para cada modelo específico.

Espero que mi respuesta te ayude un poco, y si sigues con dudas solo pregunta 😃

**Comment by mpenalozag** [comment]
Creo que me quedo claro, gracias !
