### ISSUE TITLE
Como personalizar la terminal. 

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#1018]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
Hola, quería saber como se le llama a cuando uno modifica la terminal para que se vea mas bonita como se ve en el modulo de ejemplos de la semana 14. Busco en internet pero no he podido encontrar.

**Comment by aaossa** [comment]
Hola @diego-ayala-2000 ,

Asumo que te refieres a esta captura:

![imagen](https://user-images.githubusercontent.com/10425834/99325858-e983eb00-2855-11eb-9df8-1fbd6c3c4ab2.png)

Tal como se ve en la parte de arriba de la ventana, lo que estás viendo se llama `zsh`, que es como una versión "extendida" de tu consola normal. Dependiendo de tu sistema operativo puedes utilizar [esta guía](https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH#how-to-install-zsh-on-many-platforms) para instalar `zsh`. Yo en particular ocupo [`ohmyzsh`](https://github.com/ohmyzsh/ohmyzsh) (que ocupa `zsh`) porque también quería personalizar mi consola, y como tengo Windows 10 tuve que hacer un par de cositas más (ahora es más fácil creo, pero sí que se puede)

![imagen](https://user-images.githubusercontent.com/10425834/99326392-040a9400-2857-11eb-9889-65635e3c2074.png)

Así se ve mi consola ahora. Y sip, tiene emojis 🐍 

Creo que es un buen ejercicio intentar configurar estas cosas, pero si necesitas ayuda puedes preguntar acá (aunque no hay garantía de respuesta al no ser algo 100% del curso 😅) o por `#miscelaneo` en Discord ✨

**Comment by diego-ayala-2000** [comment]
Muchas gracias!!!! Muy buena la ayuda.
