### ISSUE TITLE
error desconocido

### ISSUE THREAD

**Issue by feliperojas123** [IIC2233/syllabus#1019]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

resulta que hay una issue muy parecida que es la del error del firewall... le di perimiso a python para que pudiera tomar las distintas conexiones... y ahora me arroja este error
PermissionError: [Errno 13] Permission denied
y la verdad no entiendo el porque de este error

**Comment by feliperojas123** [comment]
es cuando ocupo el sock.bind para ser mas especifico

**Comment by aaossa** [comment]
Hola @feliperojas123 , ¿cuál ejemplo estás ocupando? ¿Qué puerto estás usando? Démosle una vuelta a eso 🤔

**Comment by feliperojas123** [comment]
hola buenas.. estoy en el segundo jupyter, el de networking y en la parte final para ver lo que se hace con el servido tcp el mas completo. me tira ese error el sock.bind... estoy usando el puerto que me dan y resulta que para el primer ejemplo del tercer jupyter me tira este error en cliente ConnectionRefusedError: [Errno 61] Connection refused.. la verdad nose que sucede

**Comment by aaossa** [comment]
Mmm veamos los errores por separado:

* ` PermissionError: [Errno 13] Permission denied`: Este error se da en el lado del servidor. Se produce porque no tienes permisos para tomar el puerto que quieres (asegúrate de tomar un puerto mayor que 1024) o porque no tienes permisos para tomar puertos (puede ocurrir si no estás en una sesión/usuario con privilegios suficientes en el sistema, en ese caso asegúrate de intentar ejecutar el código desde una sesión con privilegios de administrador para probar). Tiene sentido que este error aparezca al momento de hacer `sock.bind((host, port))` porque es el momento en que intentas "tomarte" el puerto para que el servidor quede escuchando conexiones ahí.
* `ConnectionRefusedError: [Errno 61] Connection refused`: Este error se da en el lado del cliente. Se produce cuando la conexión no es aceptada o es rechazada (asegúrate de tener un servidor "escuchando" en el puerto al que tu cliente se quiere conectar).

Es posible que ambos errores estén relacionados en tu caso. Si no puedes ejecutar el servidor, entonces el cliente no podrá conectarse. Así que vamos por el primer error... Dejaré dos cosas para que pruebes y me dices cuál funciona 🤔 

1. Probar otro puerto (relacionado con #1012)
2. Probar otro nombre para el *host* (relacionado con #1013)

Si ninguna te funciona o te funcionan ambas, porfa avisa por acá mismo para que le sirva a otras personas ✨ Ojalá funcione alguna 🙌 ¡Ánimo con tu estudio!
