### ISSUE TITLE
Ejercicios Networking

### ISSUE THREAD

**Issue by catalinamusalem** [IIC2233/syllabus#1019]
Hola! Como se crean dos consolas separadas en un mismo computador?

**Comment by tcouso** [comment]
Hola! Lo que yo hago es abrir dos ventanas del editor, y tener cada archivo python en su propia ventana. Para VS puedes abrir otra ventana apretando "Ctrl+Shift+N".
Ojalá te sirva!

**Comment by lily416** [comment]
Generalmente la terminal de las interfaces de desarrollo te permiten agregar o dividir una terminal, puedes usar eso para ver y correr varios archivos al mismo tiempo.

En el caso de VSCode, estos botones te permitirán hacerlo:
![image](https://user-images.githubusercontent.com/26393515/85204217-f4efdc00-b2e0-11ea-9e81-6212fde01f0a.png)

Saludos y que tengas una buena semana 👋😸
