### ISSUE TITLE
Debo subir ejemplo.py o añadirlo al .gitignore?

### ISSUE THREAD

**Issue by viceandres** [IIC2233/Syllabus#102]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido

[Agrega aquí lo que quieras aportar o preguntar]

**Mi duda es bien simple. Se debe subir a GitHub el archivo ejemplo.py siendo que yo no lo utilicé? O debo agregarlo al .gitignore? En las instrucciones del enunciado no se menciona que hacer con este archivo y en la sección dedicada a .gitignore se habla de los demás archivos que hay que ignorar. Debo agregarlo a mi repositorio o ignorarlo? De antemano muchas gracias.**

**Comment by MaxAl100** [comment]
Hola! Ya que no está explícito dentro del enunciado que debes ignorarlo, queda a criterio personal. Recuerda mencionar lo que decidiste hacer en tu README y si quieres referencia a este issue como prueba de lo que hiciste es correcto. Saludos y buena suerte con lo que queda de la tarea! ❤️
