### ISSUE TITLE
Uso de self.__variable = None en Ejercicio 2

### ISSUE THREAD

**Issue by moquezada** [IIC2233/syllabus#102]
¡Hola! Estaba haciendo el ejercicio 2 propuesto y no entiendo muy bien para qué utilizamos tanto ```self.__variable = None ``` como ```self.variable = variable``` en la siguiente parte del código:

```python     
class Usuario:
    
    def __init__(self, username, mail, edad, rut):
        # Así validamos de inmediato los atributos
        self.__username = None
        self.__mail = None
        self.__edad = None
        self.__rut = None
        self.username = username
        self.mail = mail
        self.edad = edad
        self.rut = rut
    
```

Si bien dice que es para validar de inmediato los atributos, no logro entender el cómo implementarlo.

**Comment by jjaguillon** [comment]
Esto es gracias a la definición del `setter` de esas properties.

#### Me explico

Gracias a los atributos llamados `__atributo` que creamos para tener un atributo donde contener el valor de la property, tendemos a definirlos inmediatamente en el `__init__` con los valores del parámetro, es decir.

`self.__username = username`

Dado que tenemos un `setter` definido, al ser instancias una clase de usuario, permite validar mediante las condiciones definidas en el `setter`.

`self.username = username`

Esto llamaría al `setter` de la property.

```@property
def username(self):
    pass

@username.setter
def username(self, value):
    #esto es llamado
    pass
```
