### ISSUE TITLE
 edad usuario

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#102]
En el pdf sale que birthday es el año de nacimiento, pero en el archivo viene la fecha exacta de nacimiento. ¿Para calcular la edad actual de un usuario se debe considerar la diferencia entre el día actual y la fecha exacta de nacimiento o la diferencia entre año actual y año de nacimiento?

**Comment by fdominguezclaro** [comment]
Debes calcular la fecha exacta para ver que edad tiene.

Suerte!!
