### ISSUE TITLE
Retractarse

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#102]
Cuando me hablan de que me tengo retractar, se refiere a que si selecciono "Crear una persona" por ejemplo y se desplega el menú de posibles personas a crear aparezca además la opción de volver atrás al menú de acciones? O se refiere a que si elijo una acción como "crear 30 soldados" pueda retractarme en la medida que siga en mi turno y deshacer esta acción?

**Comment by Arcoirisky** [comment]
Hola! Tu issue ya a sido respondida antes :D #70

**Comment by VicenteMerino** [comment]
Hola, hice esta issue porque no me quedó muy clara esa respuesta si por opción se refiere a la acción definitiva la cual puedo cancelar o por opción de ir de un menú a otro, puedo volver al menú anterior

**Comment by Arcoirisky** [comment]
Que puedes volver al menú anterior c:
