### ISSUE TITLE
ImportError: bad magic number in 'utils'

### ISSUE THREAD

**Issue by Donnatella** [IIC2233/Syllabus#102]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo corró mi codigo en el terminal me sale un error que es el siguiente:
** ImportError: bad magic number in 'utils'**
![issue 1](https://github.com/user-attachments/assets/f9e390dd-4ed2-4cbc-9865-e5a74d609448)

He buscado en internet y me dice que probablemente sea porque tengo una versión de python distinta al del .pyc pero mi versión de python es 3.12.4. Asi que no se como resolver este problema.

**Comment by Agusrush21** [comment]
Tienes que cambiar la version de python, si ves en youtube hay varias soluciones, una puede ser , desinstalar la version que tienes y luego instalar la correspondiente o otra seria instalar la que corresponde y al abrir el main abrelo con con el comando py -3.11 main.py 

Aunque esta ultima nose como sera en terminos evaluativos

**Comment by Dvckhv** [comment]
Hola!

Tal como menciona el compañero, es necesario ejecutar el archivo con python 3.11.x con x>7 tal como se menciona en la [wiki](https://github.com/IIC2233/Syllabus/wiki/4.-Software-Obligatorio).
Debes reinstalar python considerando esto.
