### ISSUE TITLE
Duda al crear grupos

### ISSUE THREAD

**Issue by ignaciaurrutia** [IIC2233/syllabus#102]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Cuando se crea un grupo, en el enunciado sale que los usuarios que se añadan deben existir en el programa, pero no específica si deben ser además parte de los contactos de la persona que está creando el grupo. ¿Se puede usar solo a los usuarios para crear el grupo o deben ser parte de contactos necesariamente?

**Comment by IgnaciaJ** [comment]
Hola @ignaciaurrutia ! Se requiere verificar si el nuevo integrante se encuentre en el archivo usuarios.csv, no es necesario que sean parte de los contactos del usuario. Para otra ocasión te recomiendo leer las issues antes de escribir una ya que, tu pregunta ya puede estar planteada  e incluso resuelta :)
Éxito en tu tarea!

**Comment by ivannia-puc** [comment]
Cuando uno crea un grupo, en el input, al momento de añadir los usuarios que estarán en dicho grupo ¿se incluye el usuario que está creando el grupo o este se añade automaticamente?

**Comment by IgnaciaJ** [comment]
Hola @ivannia-puc !! Como no sale especificado en el enunciado queda a tu criterio como recibe el input. Recuerda especificarlo en el README :) Éxito en tu tarea!
