### ISSUE TITLE
Cálculo de probabilidades durante el juego

### ISSUE THREAD

**Issue by nicolasgarciaes** [IIC2233/Syllabus#102]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola buenas, tengo una duda con respecto al cálculo de las probabilidades para poder ganar un juego y la probabilidad asociada a un jugador. Las fórmulas del enunciado, siempre nos darán resultados positivos? o existe la posibilidad que para cierta apuesta y ciertas características de un jugador, la probabilidad obtenida sea negativa?

**Comment by antoniablanco** [comment]
Podría darse el caso en que este negativo, por lo cual te recomiendo para no tener problemas utilizar el valor absoluto de la ecuación.

**Comment by juacob** [comment]
> Podría darse el caso en que este negativo, por lo cual te recomiendo para no tener problemas utilizar el valor absoluto de la ecuación.

No hay problema en hacer eso? siento que se deberia reemplazar por 0 el valor en caso de que la formula fuera negativa o no?
