### ISSUE TITLE
Distribución daño a edificios y ejército

### ISSUE THREAD

**Issue by Regenschrim** [IIC2233/Syllabus#102]
Si bien cuando uno inicia una batalla se deben sumar todas las vidas de los soldados y edificios, al igual que sus ataques. No me queda claro como se distribuye el daño a las entidades. Con esto último me refiero a cuanto daño recibe cada soldado como entidad única y cuanto daño va destinado a los edificios, ya que es posible invadir y no ganar, por lo que los edificios deberían quedar con menos vida al igual que todos los soldados (algunos con más que otros) o puede que se destruyan solo los edificios o mueran solo los soldados 😕
Traté de explicarme lo mejor que pude, no sé si se me habrá pasado en el enunciado, pero no vi como ocurría esto o ¿quizás me estoy complicando mucho?

**Comment by IchottMano** [comment]
@Regenschrim Hola!
Lo de la vida de las torres no esta en el enunciado, por lo que esta pensado como que no reciben daño, pero esta a tu criterio si lo implementas o no.
Por razones similares, la distribución del daño a tus soldados también esta a tu criterio.
Saludos!

**Comment by jminostroza** [comment]
O sea que basta con acabar con la vida de los soldados para conquistar un planeta?

**Comment by IchottMano** [comment]
@jminostroza Efectivamente.

Saludos!
