### ISSUE TITLE
Error test case AC1

### ISSUE THREAD

**Issue by Psacevedo** [IIC2233/Syllabus#102]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda
Hola equipo de IIC2233
tengo dudas si los test case de la AC1, creo que el enunciado difiere del archivo test.py dándome errores por que no están exactamente igual, quisiera saber si debo modificarlo para que quede igual a test.py o a la pauta para que al momento de ser revisado no tenga este tipo de errores y pueda optar al mejor puntaje.
De antemano muchísimas gracias 

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]
![image](https://github.com/IIC2233/Syllabus/assets/131568707/2784f635-5c02-42d7-b366-4c40b628c5d1)
![image](https://github.com/IIC2233/Syllabus/assets/131568707/05c7bc7e-de1a-4b20-9f06-9fa40236a5ea)

**Comment by Benjaminsolerp** [comment]
Hola una duda, si tengo 3 failures de los 38 tests. ¿Cómo se calcula la nota?
