### ISSUE TITLE
Unidades de Medida Recursos y puntos de poder

### ISSUE THREAD

**Issue by GustavPrudencio** [IIC2233/Syllabus#102]
Tengo mas que nada una consulta, sucede que cada recurso al movilizarse puede a lo más restarle al incendio recurso.autonomía*recurso.tasa_extincion puntos de poder lo cual generalmente esta en los órdenes de (100-1000). sin embargo si calculamos los puntos de poder del incendio como área*potencia los órdenes de magnitud son mucho mayores (10000-100000). Queria saber si el problema es las unidades de medida de la variable puntos de poder o si realmente deberia ser asi.

**Comment by gbordoni** [comment]
+1

**Comment by GustavPrudencio** [comment]
![image](https://cloud.githubusercontent.com/assets/26264167/24122751/d0bf56f0-0d9b-11e7-8427-1578c21b54bb.png)

En rojo esta la linea de puntos que puede quitar un recurso cualquiera vs el crecimiento minuto a minuto de los puntos de poder del incendio considerado en kilometros, todavia no estoy seguro pero creo que lo correcto es considerar el área en metros cuadrados.

**Comment by gbordoni** [comment]
@rpalmaotero  Ayuda pls

**Comment by negutierrez** [comment]
me sumo a @gbordoni, el crecimiento de los puntos de poder de un incendio es enorme considerando la relación cuadrática del radio en metros  y la multiplicación por la potencia. Si además de esto, el radio del incendio nunca es decreciente, es prácticamente imposible apagar un incendio.
Probablemente haya un problema con las unidades del enunciado

**Comment by FernandoPieressa** [comment]
@GustavPrudencio @gbordoni @negutierrez

Subimos un nuevo csv de recursos con datos mas razonables para atacar el incendio.

Saludos!

**Comment by GustavPrudencio** [comment]
Muchas gracias! probare de inmediato.

**Comment by chuma9615** [comment]
Aun con las muevas actualizaciones los recursos siguen siendo muy debiles si es que se quiere apagar un incendio digamos 1 dia despues de iniciado, esto deberia ser asi o mi programa es el que esta fallando?

@GustavPrudencio @gbordoni  les resulto con las nuevas bases de datos?

**Comment by gbordoni** [comment]
@chuma9615 Jajajaj buena yo estaba pensando lo mismo, en mi caso logro apagar un incendio mas o menos hasta 12 horas desde que se inicio...con mas horas  que esas no logro.

**Comment by berrazuriz1** [comment]
Yo tengo una duda de como se calcula los puntos de poder cuando hay un recurso actuando sobre el incendio. Mi problema es que la forma de calcula los puntos de poder, puntos poder = superficie afectada * potencia, hace que la los puntos no tengan "memoria" por decirlo, ya que el área se calcula con el radio y el radio se actualiza por cada minuto que pasa. Por lo anterior sí yo aplico un recurso el minuto dos, y vuelvo a calcular los puntos de poder al minuto tres, como los calculo con la formula me sale el mismo numero que me hubiera salido sin utilizar el recurso. No se si me explico, pero quizás por eso es tan difícil apagar los incendios, ya que si no lo apagas en el minuto, los puntos de poder se "reinician"  y no valió de nada los recursos anteriores.

**Comment by AmbrosioV** [comment]
Por lo que entiendo tienes que bombardear con todo para generar una tasa de puntos de poder apagados tal que alcance los puntos de poder del incendio (que seguira creciendo), y hay veces en que ya no los apagaste y se quemará todo

**Comment by FJavierOss** [comment]
Apoyo a @berrazuriz1, no será más razonable que la tasa de extinción se aplique directamente al radio del incendio? Porque por lo menos de esa manera se puede hacer una extinción continua del fuego a lo largo del tiempo hasta que se apague, además igual me parece extraño que el fuego se "apague" por falta de puntos de poder teniendo un área de incendio que estaba intocable, no se, me hace más sentido que se vaya reduciendo el radio hasta que se haga 0 y a causa de eso los puntos de poder se vayan reduciendo. Tengo el mismo problema :C

**Comment by arturodelreal** [comment]
@berrazuriz1 @FJavierOss Los puntos de poder de un incendia en todo momento están dados por la diferencia de puntos ganados por el incendio y puntos que han sido combatidos (área * potencia - puntos_eliminados_por_los_recursos).
