### ISSUE TITLE
Archivo en blanco después de editarlo

### ISSUE THREAD

**Issue by nlewin99** [IIC2233/syllabus#102]
mi código en seguidores.py deja el archivo en blanco, cuando debería solo dejar de seguir al argumento en cuestión, gracias.

**Comment by KnowYourselves** [comment]
Hola @nlewin99!

Esto se debe a que los cambios en los archivos solo ocurren una vez que haces `close`. En esa función debes cerrar los archivos.

Cuéntame cómo te va!

**Comment by nlewin99** [comment]
muchas gracias @KnowYourselves! pero lamentablemente la función sigue dejando en transformando el archivo seguidores.csv  en un archivo vacio

**Comment by nlewin99** [comment]
debe haber algun problema en el codigo pero no lo logro identificar

**Comment by KnowYourselves** [comment]
Lo que pasa es que tienes abierto el archivo tanto en modo lectura como en modo escritura a la vez, lo cual causa que seas incapaz de leer (intentas leer y no lees nada). Para solucionar esto, primero lee el archivo, cierralo y después escribe en el.

**Comment by nlewin99** [comment]
Muchas gracias,  saludos
