### ISSUE TITLE
Error al ejecutar ejemplos de Networking

### ISSUE THREAD

**Issue by rodrigobj99** [IIC2233/syllabus#1020]
Hola! Cuando ejecuto el codigo base (cliente tcp) me sale el siguiente error:

sock.connect((host, port))
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

Como puedo solucionarlo? que puede estar causando este problema?
Gracias!

**Comment by rodrigobj99** [comment]
Logre solucionarlo, era un error de configuración de mi computador, habia que activar la opcion compartir archivos en los ajustes.

**Comment by JaviGuzman** [comment]
En que ajustes te refieres @rodrigobj99 ? Tengo el mismo problema, no se donde arreglarlo.
Gracias!

**Comment by cncosta** [comment]
yo lo arregle poniendo
```python 
HOST = 'localhost'

**Comment by rodrigobj99** [comment]
@JaviGuzman tuve que hacer dos cosas para que me funcione, una fue en preferencias del sistema -> compartir: ahi active compartir archivos, y la otra fue modificar un archivo llamado hosts (puedes buscar como modificarlo en google) y le agregue esta linea, que es lo que me salia al poner  `print(gethostname)`:
![Captura de Pantalla 2020-06-18 a la(s) 5 11 08 p  m](https://user-images.githubusercontent.com/49729086/85072632-674ca900-b187-11ea-9f4b-4e19c2d89374.png)
