### ISSUE TITLE
Ejercicio 2.2 semana 14

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#1020]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Estoy pegada en este ejercicio 😔. Ya realicé toda la parte de TCP y funciona bien, pero al querer implementar el UDP, el mensaje no se manda desde el socket. Estoy basándome en el código del final del notebook 2 y no sé qué estoy haciendo mal. Analizando el código del notebook me di cuenta que si el cliente no manda un mensaje en UDP (comenté ese mensaje de cliente_udp.py) entonces el mensaje desde el servidor no llega, que es lo mismo que pasa en mi ejercicio. Entonces mi pregunta es si quizás el cliente también tiene que mandar un mensaje a través del socket UDP. Del enunciado entendí que sólo mandaba TCP pero quizás eso es lo que me falta 🤔

Gracias!

**Comment by aaossa** [comment]
Hola @denisseleiva , estuve haciendo el ejercicio y en un momento pasé por algo similar a lo que describes, así que veamos qué puede ser 🤔. Primero, se espera que los comandos siempre viajen por TCP y que solo la hora se envíe por UDP. El cliente envía los comandos por TCP al servidor, el servidor recibe los comandos por TCP desde el cliente, el servidor envía por UDP la hora al cliente, el cliente recibe la hora por UDP desde el servidor.

Ahora, tu problema podría ser alguna de las siguientes cosas:

1. Fíjate que en cliente, justo abajo de definir el `socket_udp`, se pide enviar el primer comando `"hora"` al servidor. Si no lo envías, el servidor no empezará a enviar la hora
2. Si ya hiciste eso, recuerda que desde el servidor tienes que enviar la hora al puerto específico en el que está el *socket* UDP del cliente
3. Si ya hiciste eso, quizás te faltó dejar al *socket* UDP del cliente escuchando en dicho puerto

Espero que alguna de estas opciones te sirva. Intenté no ser taaaan específico para no hacer tanto *spoiler* 😅 De todas maneras, si sigues con dudas o algo no te funciona, pregunta por acá mismo no más 👌 ¡Éxito con tu estudio ✨!

**Comment by denisseleiva** [comment]
A qué te refieres con "dejar al socket escuchando en ese puerto"? Basta con hacer socket.recvfrom()? Porque entiendo que no se hace listen() 🤔

**Comment by MatiasDuhalde** [comment]
Hola @denisseleiva ! 

Tienes razón, no se hace `listen`! Al final, `listen` lo que hace en TCP es permitirle al socket poder "aceptar" conexiones. Dado que UDP es *connectionless*, no hay que realizarlo en este caso.

Sin embargo, hay un método extra que es necesario invocar en este caso. Con "dejar al socket escuchando en ese puerto", además de `recvfrom`, habría que hacer algo extra para """ligar""" el socket al puerto :eyes: Si no ocupas ese método, el socket nunca sabrá en qué dirección y puerto debe escuchar mensajes, por lo que debes especificarlo de alguna manera.

También evité ser específico, así que si continúas con dudas, puedes seguir preguntando en este hilo 👇

**Comment by denisseleiva** [comment]
jajjajjajja creo que sé cuál es el método secreto al que se refieren pero no sé cómo implementarlo. 
1- ¿Tiene que estar en el servidor? (Como en el ejemplo del notebook)
2- ¿Tengo que conectar con el propio puerto del socket o con el puerto al que quiero llegar?

**Comment by aaossa** [comment]
@denisseleiva quizás sea mucho *spoiler* pero piensa bien dónde te conviene que esté el servidor UDP (puedes probar ambos), y recuerda que lo que estás haciendo es enviarle datos a otro *socket* así que tienes que usar el puerto en el que se encuentra ese (fíjate que es el que se pasa al momento de enviar el primer comando 👀)

**Comment by denisseleiva** [comment]
Dalee, gracias a ambos!!!
