### ISSUE TITLE
Ejemplos semana 14

### ISSUE THREAD

**Issue by ignaciovilla** [IIC2233/syllabus#1021]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola, al leer los ejemplos que se enviaron en el archivo "3-ejemplos" de los contenidos de la semana 14, en el ejemplo de la sección "Envío de muchos datos" que se muestra que se reciben menos bytes de los que se envían, me surge la siguiente duda:
Si es que nosotros enviamos todos los bytes del archivo, por qué estos no se reciben de la misma forma, es decir, porque al guardarlos solo se guarda una parte de ellos? A qué se debe esto, y por qué el cambio que se hace de enviar previamente el largo del archivo arregla esta situación?
Muchas gracias de antemano

**Comment by tocococa** [comment]
Hola @ignaciovilla! En el ejemplo que mencionas, se guardan solo ~4 kilobytes (kB) de los ~100 kB enviados porque en el código que está recibiendo el archivo, se declara
```
datos = sock_cliente.recv(4096)
with open('files/recibido.bin', 'wb') as binfile:
     binfile.write(datos)
```
donde `recv(buffer_size)` indica la [cantidad de bytes a recibir](https://docs.python.org/3/library/socket.html?highlight=recv#socket.socket.recv). Como se está utilizando un protocolo [TCP ](https://tools.ietf.org/html/rfc675)(indicado por `SOCK_STREAM`) al definir el socket de la clase que recibe, a diferencia de un socket [UDP](https://tools.ietf.org/html/rfc768), este NO está continuamente escuchando, y por lo tanto, al declarar un _buffer size_  igual a 4096, y recibir solo una vez, no vemos el resto del mensaje. 

Cuando declaramos en una primera comunicación el largo del mensaje a recibir, podemos hacer que el socket lea, en varios paquetes de tamaño reducido, todo el mensaje enviado. Esto se hace porque, a nivel de redes (dentro de tu PC no debería ocurrir), durante la transmisión, es probable que se pierda una cierta cantidad de estos paquetes, y al tratarse del protocolo TCP, si un paquete no llega, se volverá a intentar enviarlo. Esto no es un problema para un paquete pequeño (un par de kilobytes), pero si, por ejemplo, envías un paquete de 100 MB de una y el envió se interrumpe, podría ser problemático tener que reenviar todo el mensaje desde 0 (por congestión, tiempo de envío, etc.) o incluso imposible (por inestabilidad de la red, etc.).

Quedo atento a cualquier duda que puedas tener ( ͡~ ͜ʖ ͡°).

**Comment by Mamunoz42** [comment]
Hola,  tengo una duda similar, lo que pasa es que no entiendo el porque se usa la siguiente linea de codigo para definir el largo del archivo:
```Python
largo_archivo = int.from_bytes(sock_cliente.recv(4), byteorder='big')
```
no se si me la podrias explicar por favor, ya que no entiendo porque en el ```recv()``` utilizan solo 4 bytes, tampoco logro comprender que hace el ```from_bytes```. 
De antemano muchas gracias :smile:

**Comment by tocococa** [comment]
Hola @Mamunoz42 !

Esa línea se usa porque como **convención** (podrían ser 2, 3, 5, etc. bytes, dependiendo de cosas como el largo esperado del mensaje). Para ese programa en particular , se define que siempre los primeros 4 bytes de un mensaje van a indicar el largo del resto del mensaje (independiente de si el mensaje después tiene 1 B, 20 kB o 4 GB), de esta forma siempre que se reciba un mensaje, vamos a saber cuántos bytes tenemos que recibir a continuación. En la práctica, para headers de 4 bytes y chunks de 8, se vería algo así:


![image](https://user-images.githubusercontent.com/22779371/100274926-fbdce380-2f3d-11eb-9443-779ae39bc63b.png)


La función `int.from_bytes()` toma una serie de bytes y los decodifica como `int`, en este caso, esto funciona y entrega el número esperado, porque en el método que envía el mensaje, se utilizó `int.to_bytes()`, si no, podrías tomar bytes que representan algo distinto a un entero y obtener cualquier número. Si quieres ver en más detalle que hace y como se puede usar, puedes [leer acá](https://docs.python.org/3/library/stdtypes.html#int.to_bytes).

**Comment by Mamunoz42** [comment]
@tocococa Muchas gracias, te pasaste 😄

**Comment by ignaciovilla** [comment]
Muchas gracias!
