### ISSUE TITLE
Connect() takes 2 positional arguments but 3 were given (ejercicio 2.1, semana 14)

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#1022]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

¡Hola!

El método connect de socket debe recibir dos argumentos: el host y el port. El primero es un string y el segundo un int.
¿Qué puede estar pasando? Imprimí los argumentos que le entrego a connect() y efectivamente son 2.

Muchos saludos.

**Comment by MatiasDuhalde** [comment]
Hola @amahns1 !

El método connect de los sockets, en realidad, recibe un sólo argumento 😱

La dirección (host y port) debe ser entregado como una tupla que contenga a los dos en ese orden, de la siguiente manera: `sock.connect((host, port))`. Entonces, el único argumento que recibe sería la tupla (pero a su vez esta contiene 2 elementos).

El error dice `takes 2 positional arguments but 3 were given`, porque cuando llamas un método (cualquiera, no solo `connect`), el objeto también cuenta como argumento (en el ejemplo anterior, la variable `sock` pasaría a ser el `self`, y es por eso que el error dice que recibe 2).

Ojalá haya quedado un poco más claro 😃

**Comment by amahns1** [comment]
¿Pero entonces cómo puedo llamar a connect?  ¿Porque no puedo llamar a connect sin el socket o si?

**Comment by amahns1** [comment]
Entiendo, me acabo de dar cuenta que recibe una tupla.

Muchas gracias!
