### ISSUE TITLE
[WinError 10049] La dirección solicitada no es válida en este contexto

### ISSUE THREAD

**Issue by domja** [IIC2233/syllabus#1022]
Hola! tengo este error y he intentado hacer todas las soluciones de los otros issues pero aun no me resulta, puse server_host = socket.gethostname(), abri consolas separadas, etc sera alguna configuracion de mi computador o algo asi?

**Comment by igbasly** [comment]
Hola @domja, lo sentimos por la demora con tu issue 😓
Cuéntame, ¿aún tienes problemas con este error? y de ser así, ¿podrías darme un poco más de contexto respecto a cómo ocurre?
