### ISSUE TITLE
Dudas varias semana 13 y 14

### ISSUE THREAD

**Issue by daniela-carreno** [IIC2233/syllabus#1023]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, la materia de la semana 13 y 14 las he encontrado particularmente enredadas y me han salido varias dudas. Aquí van: 

1.  Cuándo y para qué ocupamos los bits? Todos los ejemplos son de bytes.
2. Los hosts necesitan de un lugar físico para existir ? me refiero a que si en algún lugar del mundo tienen una caja/disco/algo tangible?
3. Lo mismo con los servidores, son algo virtual o tienen arquitectura física?
4. Entendí que las IP son como un RUT de los hosts. Es posible cambiar la IP ? Se puede hacer eso? Para qué querría hacer esto?
4.1. Recuerdo que cuando salió pokemon go, un amigo le hizo algo a su teléfono para engañarlo de que su ubicación era en otro país. Eso tiene que ver con la IP o es otra cosa?
5. También sobre las IP (y un poco *off topic* a la materia en sí), en google me aparecen muchas entradas sobre cómo ocultarla. Algunos de los ejemplos que dan es para evitar anuncios personalizados. Si la oculto podría lograr que dejen de aparecer anuncios?  
6. Por qué las IP versión IPv6 agrupa de 2 hexadecimales en vez de separarlo por byte como es el caso del IPv4? por ejemplo, (FF)(00):*blablabla*:(FF)(00) 
7. De los puertos, 2^16 suena bajo para toda la cantidad de aplicaciones que existen. Puede ser que dos apps quieran usar el mismo puerto? En ese caso, como el servidor decide a quién admite? 
8. De la clase 14-1 qué hacen cada capa de encapsulamiento?
9. en la clase 14-2, por qué a veces usan "/" y otras "\" ? Cuándo se ocupa cada una?
10. En la sección de sockets dicen que 2^12 es pequeño. Qué tamaño tiene un byte grande? y cuál sería un tamaño de chunk razonable para leerlo?
11. También de la clase 14-2. Para enviar un mensaje hay algún encode preferido (ascii, utf-8, etc) o con declararlo es suficiente para que cualquier máquina lo decodifique?
12. Los servidores tienen capacidad finita o infinita de "atención" ? Funcionan con una cola de espera o si soy el cliente n+1 me bota de la página?
13. Tengo mac y uso sublime text 3. Para correr mis códigos lo hago desde la terminal. Hasta ahora siempre es de a un programa. Cómo hago correr dos consolas? (sugerencia de la clase 14-2). También podría conseguirme un windows con vs code con mi familia. En ese caso, cómo hago que mis computadores hablen entre ellos?

Muchas gracias! perdón lo largo.

PS: este es mi primer curso del major de computación. En los cursos que siguen, es tan intensa la programación como este? Qué materia de los contenidos es la que mejor debería manejar ?

**Comment by cruz** [comment]
Hola @daniela-carreno 

> 1. Cuándo y para qué ocupamos los bits? Todos los ejemplos son de bytes.

No estoy seguro si entiendo bien la pregunta. Si estoy yendo por otro lado, indícame. Los Byte están compuestos, cada uno de 8 bit. Cuando decimos el Byte `\x63 `, estamos mostrandos dos dígitos hexadecimales. El `\x` indica que lo que viene son dígitos hexadecimales. Los dígitos hexadecimales son `0`, `1`, ... `9`, `A`, `B`, `C`, `D`, `E`, `F`. Son 16 dígitos que representan los valores desde 0 hasta 15. Cada uno se puede escribir como un número binario usando 4 bit. Esto es así porque usando 4 bit (0's o 1's) podemos armar 2^4 = 16 combinaciones. La siguiente tabla muestra la equivalencia:

| Decimal       | Hexadecimal           | Binario (4 bit)  |
| ------------- |:-------------:| -----:|
| 0  | 0| 0000 |
| 1  | 1      |   0001 |
| 2  | 2     |   0010 |
| 3  | 3     |   0011 |
| 4  | 4     |   0100 |
| 5  | 5     |   0101 |
| 6  | 6     |   0110 |
| 7  | 7     |   0111 |
| 8  | 8     |   1000 |
| 9  | 9     |   1001 |
| 10  | A     |   1010 |
|11  | B     |   1011 |
| 12  | C     |   1100|
| 13  | D     |   1101 |
| 14  | E     |   1110 |
| 15  | F     |   1111 |

Entonces, intentando responder a la pregunta, los computadores **siempre** usan bit para representar todo: caracteres, imagenes, audio, video, etc. Pero procesarlos uno a uno puede ser poco eficiente, así que los procesan en grupos de 8 bit (1 Byte), o de 16 bit (2 Byte), o de 32 bit (4 Byte), etc., en general por potencias de dos. Por esto es más común que veas que hablamos de Byte en lugar de bit, pero "por debajo" siempre hay bits.

La razón de por qué se hace a través de potencias de 2 tiene que ver con la manera de construir los circuitos y porque los valores que puede tomar un bit son dos. En el curso Arquitectura de Computadores abordamos estos temas en detalle.


> 2. Los hosts necesitan de un lugar físico para existir ? me refiero a que si en algún lugar del mundo tienen una caja/disco/algo tangible?

Los _hosts_ son computadores que albergan (o "hostean") y ejecutan programas. Estos programas pueden funcionar por su propia cuenta, o bien comunicarse con otros programas, en cuyo caso esos programas van a tomar un rol de "programa cliente" o de "programa servidor". Un celular, por el hecho de ejecutar programas, también es un _host_, usualmente para programas cliente. El término _host_ es más general que decir un computador de escritorio, o un laptop, o un celular. Les llamamos _hosts_ porque **albergan** código, o más bien corresponde al "lugar donde se encuentra el programa cliente o el programa servidor". Por lo tanto los _host_ **son** elementos físicos (casi siempre, porque también existen las máquinas virtuales, pero eso es otro tema) donde se ejecutan los programas.


> 3. Lo mismo con los servidores, son algo virtual o tienen arquitectura física?

Esto es muy buena pregunta porque se puede prestar mucho a confusión. Un **servidor** es un **programa que escucha y atiende solicitudes** (o sea que "sirve" a los demás). Por lo tanto un **servidor es _software_**. Los servidores puede hablar distintos lenguajes (protocolos) para comunicarse con los clientes. Esta misma _issue_ se encuentra ahora dentro un servidor de github, el cual hace poco escuchó un mensaje desde tu navegador (cliente) para recibirlo, almacenarlo, y luego le avisó a los ayudantes y profesores que había un mensaje nuevo.

Dicho eso, es muy común también llamarle **servidor** a un computador físico muy poderoso (con muchos núcleos, RAM, disco y harto ancho de banda) que se encuentra en un _datacenter_ junto con muchos computadores más. Eso no es del todo correcto, pues **cualquier** computador puede ejecutar un programa servidor (el tuyo, el mío, un celular, etc), por lo tanto llamarle servidor a un computador particular genera confusión. Lo que ocurre es que los servidores que existen en la red (internet) pueden potencialmente recibir muchos clientes (por ejemplo, el servidor de github, de youtube, de instagram, de la escuela de ingeniería, del CAI, etc), y en ese caso es mejor que estén en un computador que esté siempre prendido y conectado y que pueda recibir y atender muchos clientes, por lo cual necesita harta memoria RAM, disco, y poder de cómputo. Por eso a esos computadores se les suele llamar servidores, sin embargo no es la terminología correcta.


> 4. Entendí que las IP son como un RUT de los hosts. Es posible cambiar la IP ? Se puede hacer eso? Para qué querría hacer esto?

Correcto. Las IP permiten identificar de manera única a cada _host_ (casi, pero también es otro tema). La IP tiene el objetivo, además de identificarte en la red, permite que cualquier _host_ del mundo pueda encontrarte. Para esto, están repartidas de manera ordenada. Por ejemplo, todas las IP de la universidad empiezan con 146.155.x.x. Cada proveedor de internet (movistar, entel, vtr, etc) y cada país tienen rangos de IP asignadas internacionalmente, de manera que sabiendo la IP se puede tener una idea aproximada de donde se encuentra un _host_ físico. Por esta razón si quieres conectarte a la Internet no puedes asignarte un IP cualquiera. Tienes que ser una IP que "siga las reglas" del lugar donde te encuentras. 

Puede ser distinto el caso cuando estás dentro de una organización (por ejemplo, dentro de la universidad con eduroam, o dentro de tu casa), en que antes de conectarte a la Internet, te conectas a una red "privada" de la organización, a través de la cual se te permite conectarte a la Internet. En ese caso se te asigna una IP "interna" dentro de la organización, y luego para conectarte a Internet se te asigna una IP que te representa. 

La manera de cambiar tu IP depende de tu sistema operativo. En Windows puede usar el comando `ipconfig`, y en Linux/macos puede usar el comando `ifconfig`. Para ver la diferencia busca la IP de tu computador, que puede ser algo como 10.1.x.x, o 192.168.x.x (tu IP real, interna), y luego anda a Google y escribe "what is my IP", y te dirá la IP con la que "sales al mundo" que es la que te asigna tu proveedor de Internet.


> 4.1. Recuerdo que cuando salió pokemon go, un amigo le hizo algo a su teléfono para engañarlo de que su ubicación era en otro país. Eso tiene que ver con la IP o es otra cosa?

Sí, tiene que ver. Con la IP puedes tener una idea del rango geográfico donde se encuentra un _host_. Gracias a eso, Netflix sabe que estás en Chile y no te ofrece las mismas películas que si estuvieras en USA. Sin embargo, hay servicios internacionales que te ofrecen ser "intermediarios" para conectarte a la Internet. Se conocen como VPN (Virtual Private Network) y te permiten conectarte a la Internet como si estuvieras geográficamente en otro lugar. De esta manera no sales a Internet a través de tu proveedor (el cual Netflix sabe que está en Chile), sino a que a través tu proveedor te conectas a un servidor, en Atlanta, y a través de él te conectas a Netflix, por lo tanto Netflix "cree" que estás en USA. Lo mismo pasa con Pokemon Go. Se ofrecen servicios distintos dependiendo del lugar de origen (¡discriminación!).


> 5. También sobre las IP (y un poco off topic a la materia en sí), en google me aparecen muchas entradas sobre cómo ocultarla. Algunos de los ejemplos que dan es para evitar anuncios personalizados. Si la oculto podría lograr que dejen de aparecer anuncios?

Justamente, son servicios que se llaman VPN. Algunos son pagados, otros son "gratuitos" (pero con publicidad), pueden exponerte a vulnerabilidades, pues te hacen parte de una red "intermediaria" donde no sabes lo que hay.

Otra alternativa es que se refiera a servicios de "anonimato", lo cual es un poco más complicado. Parte del protocolo IP es poder encontrar un servidor destinatario e identificarte para que el servidor te responda, pero si el servidor no conoce tu IP es difícil que el mensaje llegue de vuelta a tí. Dicho eso, hay técnicas para lograr este anonimato pero no son triviales. 

Finalmente una tercera alternativa es conectarse a buscadores que no almacenan tus datos (cuando te conectaste por última vez, qué búsquedas has hecho, por qué sitios has navegado), como "Duck Duck Go" (alternativa a Google). Es un tema que cada vez cobra más relevancia porque casi toda la comunicación que hacemos en Internet es utilizado por diversos servicios para identificarnos, "estudiarnos" y ofrecernos información personalizada.



> 6. Por qué las IP versión IPv6 agrupa de 2 hexadecimales en vez de separarlo por byte como es el caso del IPv4? por ejemplo, (FF)(00):blablabla:(FF)(00)

Es solo por comodidad de notación. IPv4 son 32 bit, o sea 4 Byte. Cada Byte, por ser un valor desde 0 a 255, era cómo representarlo como 4 números de 0 a 255 separados por puntos. Hacer lo mismo en IPv6 (128 bit), significaría 16 números de 0 a 255. Para ahorrarse notación, se usan hexadecimales porque permiten "abreviar" más la notación.


> 7. De los puertos, 2^16 suena bajo para toda la cantidad de aplicaciones que existen. Puede ser que dos apps quieran usar el mismo puerto? En ese caso, como el servidor decide a quién admite?

Suena bajo, 65536, pero tampoco tenemos tantas aplicaciones en un mismo _host_ que quieran conectarse a la red. Hay que pensar que un servidor escucha en un puerto específico, pero un _host_ no suele tener mucho servidores. En un mismo _hosts_, dos apps **no pueden escuchar en el mismo puerto**, pero entre distintos _hosts_ no hay problema. Ese número es por _host_, y no está asociado a la cantidad de aplicaciones existentes.


> 8. De la clase 14-1 qué hacen cada capa de encapsulamiento?

En resumen:
* Capa física: decide como codificar **1 bit** a través un cable o aire
* Capa de enlace: ve como transmitir **un grupo de bits** a través un cable de red, o conexión inalámbrica (WiFi, 4G, etc)
* Capa de red: como se usan las direcciones IP para **encontrar** un destinatario y hacer que un **paquete de Bytes** llegue a él pasando por muchos dispostivos intermedios (_routers_ o _enrutadores_).
* Capa de transporte: TCP y UDP, cómo se hacer que un **trozo de mensaje** llegue desde un _host_ origen a un _host_ destino, considerando que algunos trozos pueden perderse o no.
* Capa de aplicación (suele incluir presentación y sesión): protocolos como el de la actividad de hoy, como HTTP, como el de Whatsapp, etc, que permite que dos programas se entiendan y colaboren.

Puedes ver más en un [gran curso](http://iic2333.ing.puc.cl/), con un [gran profesor](https://twitter.com/cristianruz).


> 9. en la clase 14-2, por qué a veces usan "/" y otras "" ? Cuándo se ocupa cada una?

Aquí no estoy seguro a qué ejemplo te refieres. Si es en un mensaje HTTP (el `GET / HTTP\1.1...`), ese `/` indica que queremos la "raíz" de lo que tiene el servidor, su página principal, y eso en todo caso es parte de las regla del protocolo HTTP. Si es cuando hacemos `bind(("", port))`, al indicar un _host_ vacío estamos diciendo que queremos recibir conexiones de cualquier dirección (eso se usa en UDP). Sin embargo, no podemos hacer `bind(("/",port))`.




> 10. En la sección de sockets dicen que 2^12 es pequeño. Qué tamaño tiene un byte grande? y cuál sería un tamaño de chunk razonable para leerlo?

2^12 = 4096 Bytes corresponde a 4KB. Es un cantidad relativamente pequeña para confiabilidad de las conexiones modernas. Se sugiere una cantidad pequeña para minimizar la probabilidad de que el mensaje llegue incorrecto. Si un mensaje llega incorrecto hay que mandar todo de nuevo desde el inicio de ese trozo. Si vamos a repetir un trozo de mensaje, es mejor repetir un trozo de 2^12 = 4KB, que uno de 2^30 = 1 GB.

El tamaño 2^12 = 4KB es un tamaño razonable. De hecho el material dice que es sugerido.



> 11. También de la clase 14-2. Para enviar un mensaje hay algún encode preferido (ascii, utf-8, etc) o con declararlo es suficiente para que cualquier máquina lo decodifique?

En las máquinas modernas es más recomendable `utf-8`. Si bien no es estándar aún en todos los sistemas, cada vez es más adoptado. En cualquier caso siempre es recomendable explicitar el _encoding_ de manera de evitar ambigüedades y que terminemos llegando a una máquina que por defecto decodifica en otro mapa.

> 12. Los servidores tienen capacidad finita o infinita de "atención" ? Funcionan con una cola de espera o si soy el cliente n+1 me bota de la página?

Finita de todas maneras. Puede ser muy grande, pero es finita. La cantidad de depende de la configuración. Los sockets TCP tienen un espacio de "backlog" (se establece con `listen`) para conexiones que llegan, donde las conexiones que llegan se van acumulando hasta que el `socket` las puede atender. Además de eso, el sistema operativo tiene _buffers_ (espacios de memoria) para las conexiones que llegan, y las tarjeta de red también los tienen. Por lo tanto tu conexión puede quedarse en uno de esos _buffers_ o, si ellos están llenos, el _host_ simplemente bota (_drop_) la conexión. Puedes ver este efecto en sitios congestionados (HTTP y HTTPS usan TCP). 

Más allá de eso, las aplicaciones pueden tener otro espacio intermedio de espera. Cuando una aplicación te dice que "estás en una cola" es porque alguien, además de las colas ya existentes, programó una cola explícita de atención. 



> 13. Tengo mac y uso sublime text 3. Para correr mis códigos lo hago desde la terminal. Hasta ahora siempre es de a un programa. Cómo hago correr dos consolas? (sugerencia de la clase 14-2). También podría conseguirme un windows con vs code con mi familia. En ese caso, cómo hago que mis computadores hablen entre ellos?

Desde la aplicación `Terminal` Le das `Shell`->`New Window`, o `New Tab`.

Dentro de tu misma red domiciliaria puedes correr un programa servidor en el Mac, y el cliente en el Windows (o al revés). Necesitas conocer la IP de cada uno y asegurarte que no haya programas (como Firewalls) bloqueando los acceso a los puertos. Si eso está OK, debería poder usar la IP correspondiente al momento de crear los _sockets_ TCP. Da lo mismo si tienes sublime o vscode. Lo importante es que los corras desde una consola (terminal) en lugar del editor, y que conozcas las IP. En el programa cliente tienes que especificar que el destino es la IP donde corre tu servidor (para que lo pueda encontrar). En tu servidor usualmente no tienes que especificar la IP del cliente, porque el servidor parte primero y, cuando llega una conexión nueva, descubre la IP del cliente. También es importante que uses puertos mayores al 1024 porque los otros suelen estar reservados por los sistemas operativos.

A través de distintas casas también podría resultar, pero ahí tenemos que pasar por las redes de los proveedores de Internet y ellos a veces bloquean los puertos. 


> Muchas gracias! perdón lo largo.

Está bien, disfruté responder.


> PS: este es mi primer curso del major de computación. En los cursos que siguen, es tan intensa la programación como este? Qué materia de los contenidos es la que mejor debería manejar ?

Programar siempre lo tendrás. Talvez menos intenso, pero no será poco. Este curso, en todo caso, te dejará bien preparada para los lenguajes (se usan otros además de Python) y desafíos que vienen. ¿Qué hay que manejar? ... la verdad todo, pero es vital el modelamiento orientado a objetos y las estructuras de datos, sobre todo árboles y grafos.

**Comment by daniela-carreno** [comment]
Muchas gracias !
