### ISSUE TITLE
Networkig - static method

### ISSUE THREAD

**Issue by NikiHV** [IIC2233/syllabus#1023]
Hola!
En el ejemplo del cuaderno 3 de la semana 14, y también en los ejercicios propuestos de esta semana, se usa el decorador `@staticmethod`. He estado tratando de entender cómo funciona este y para qué sirve, y aunque entendí a grandes rasgos su función y por qué se implementa (leyendo en internet) aún no entiendo cómo funciona cuando se llama `sock.send()` desde el _static method_ del servidor. 

Se supone que `sock` sería el _sock_ del cliente, cuya clase tiene el método `send()`, pero esta es implementada para enviar un mensaje desde el cliente al servidor, ¿por qué se llama este método cuando el servidor quiere enviarle un mensaje al cliente? Obvio que el código funciona, pero no sé por qué 😅 no sé si es algo del _static method_ tampoco.

Un poco de luces sobre me sería de gran ayuda. Gracias!

**Comment by gatochico** [comment]
Hola! (lamentamos la demora, ojala siga sirviendo esta info u.u)

`@staticmethod` se usa como decorador para métodos de una clase que no necesiten usar algún atributo u otro método de la clase en su funcionamiento. Si te fijas, los métodos que tienen dicho decorador no incluyen el `self` dentro de sus parámetros por esta misma razón. 

En este caso en específico, el método send es estático ya que recibe primero un "mensaje" a enviar (el cual es variable y altamente personalizable, definido en la función `self.handle_command)` y luego el socket del cliente al que se debe enviar (este valor se genera recién cuando aceptamos la conexión de un cliente) y procede unicamente a trabajar con esos dos valores, por lo que no necesita acceder a algun otro atributo de clase para funcionar.

Con respecto a tu segunda pregunta, tenemos un **método send en cliente y servidor**, ya que así podemos usar ese método para pasar cualquier mensaje a enviar por algún protocolo que se quiera implementar (en este caso, añadir primero el largo y transformar a bytes) y luego usar el `send` de la librería `socket` que se encarga de hacer el envío en sí entre el servidor y cliente. La variable `sock` que mencionas es unicamente el **sock** del cliente que es lo que necesitamos para realizar la conexión, no es que estemos pasando la clase cliente completa. Server no tiene acceso a las funciones ni atributos de la clase cliente, y viceversa. Ese `send` que mencionas que va al final de cada método `send` de las clases corresponde a un **método de la librería socket** que hace toda la magia por nosotros (en resumen, el send de las clases y el send de socket son dos funciones distintas, que solo tienen un alcanze de nombre).

Espero haberme explicado bien, y cualquier duda pregunta!
