### ISSUE TITLE
Git pide credenciales con demasiada frecuencia

### ISSUE THREAD

**Issue by tocococa** [IIC2233/syllabus#1024]
En abril abrí un issue donde preguntaba porqué GitHub me estaba pidiendo las credenciales de usuario demasiado seguido (un par de veces al día).

Ahora creo que se porque pasa, ocurre cada vez que cambia mi IP, hoy se reinició el módem (es un módem 4G) y me asignó una IP nueva, y git me pidió que reingresara mis credenciales, y en Abril estaba constantemente cambiando entre otro módem 4G y una conexión ADSL y creo que por eso me pedía que volviera a iniciar sesión.

Pueden cerrar la issue altiro, pero solo quería comentarlo porque me carga llegar a un foro que dice "How do A?" ---> "nvm fixed it" sin postear la solución.

**Comment by lily416** [comment]
Para los que quieran leer un poco más sobre el problema que se presento, pueden revisar la issue #372.
