### ISSUE TITLE
Detalle en contenidos

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#1024]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Hola, en los contenidos de la semana 14 --> 2-networking-con-python.ipynb, en la parte de **Servidor TCP** cuando explica el método `accept()`  dice que nos retornará un socket con el que podremos comunicarnos con ese cliente en específico, y una dirección IP de ese cliente. Falta agregar que este método también retorna el puerto de ese cliente.

**Comment by aaossa** [comment]
Hola @Gustav2000 , creo que más que un *bug* es algo que podría quedar mejor especificado, así que coincido contigo 👌 Ya lo cambié en la versión privada de los contenidos, por lo que ahora quedó mejor ✨ ¡Muchas gracias por el comentario 😁! Cerraré la *issue* porque ya fueron modificados los contenidos.
