### ISSUE TITLE
OSError al realizar ejercicios propuestos

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#1025]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, he estado trabajando en los ejercicios propuestos, pero siempre me aparece este error y termino cerrando el programa y volviéndolo a abrir para que me funcione otra vez
<img width="901" alt="imagen" src="https://user-images.githubusercontent.com/53887845/99685071-ef99e780-2a60-11eb-8e52-19e434f8a513.png">

**Comment by aaossa** [comment]
Hola @Margarita-Paz , al parecer el error indica que ya hay un *socket* en ese *host* y puerto. ¿Podrías probar si te funciona cambiando el número de puerto? Es posible que en alguna ejecución anterior el puerto queda "tomado" u ocupado 🤔 Cuéntame si te funciona. ¡Éxito con el estudio! ✨
