### ISSUE TITLE
Errores antes de comenzar juego y ConnectionAbortedError: [WinError 10053] en AF05

### ISSUE THREAD

**Issue by juanpaxd** [IIC2233/syllabus#1026]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Tengo un problema respecto a la actividad formativa 05. Mi problema es que apenas corro el main.py de la carpeta Clientes, me comienza a salir el error "No se pudo decodificar el mensaje" muchas veces en consola. Tras ingresar mi nombre de usuario, me salta el siguiente error: "ConnectionAbortedError: [WinError 10053] Se ha anulado una conexión establecida por el software en su equipo host". Intenté solucionar el primero de muchas formas, pero tal vez lo esté causando lo mismo que causa el segundo.
El ayudante con el que contacté me dijo que creara esta issue, y que hiciera la actividad sin correrla.

PD: Ya tengo la actividad terminada al momento de crear esta issue.

**Comment by aaossa** [comment]
Hola @juanpaxd , ¿pudiste solucionar tu problema? Si es así, ¿cómo lo hiciste? En una de esas le sirve a otras personas ✨
