### ISSUE TITLE
Cantidad de cartas iniciales de cada jugador.

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#1027]
Hola tengo dos dudas:
1) ¿Cuando elijo una carta desaparece del mazo?
2) ¿Nostros escojemos con cuantas cartas partimos?
Gracias!

**Comment by gatochico** [comment]
Hola!

1. Sí, debería desaparecer del mazo ya que se 'transfirió' a la mano de los jugadores.
2. Queda a tu elección con cuantas cartas comienza cada jugador. (sería **_genial_** que lo incluyas como parámetro, para poder cambiarlo de forma más fácil al revisar :see_no_evil: )

Éxito y saludos!

**Comment by CataSudo** [comment]
Hola! No me queda claro la primera parte, entonces el juego acaba cuando ya no quedan cartas? Porque igual son pocas. O debemos hacer que las cartas iniciales sean más que los sprites entregados?

**Comment by gatochico** [comment]
Puedes asumir que nunca se te acabarán las cartas y el mazo es 'infinito'. Para esto, algunas ideas para trabajar el mazo son:

- Llamas a la función generadora de mazos pidiendo X cartas que usarás como mazo. Si se te acaban, llamas a la función de nuevo pidiendo más.
- Llamas la función cada vez que necesites sacar cartas, pidiendo las que necesites en ese momento.

**Comment by felipefuentesporras** [comment]
¿Esto significa que no es necesario tener un mazo definido en el juego? Es decir que puedo generar una carta al azar cada vez que se me pida?

**Comment by gatochico** [comment]
Sí, es totalmente válido si generas una carta al azar cada vez que se pida.

**Comment by Camila-sty** [comment]
Pero el mazo siempre entrega el mismo orden de cartas? porque si yo llamo a la función cada vez que necesite una carta ésta debiese ser distinta a la anterior?. Si sigo esta dinámica me debo encargar que en el mazo se elimine esa carta?, me confundí jajaj. Mi idea era llamar a la función cada vez que se necesite un número determinado de cartas, pero en ese caso no podría encargarme de "eliminar" las cartas que ya fueron entregadas, ya que no puedo modificar el archivo...

**Comment by gatochico** [comment]
La función generadora de mazos entrega una selección aleatoria de cartas cada vez que la llamas! Entonces habría dos opciones:

- Llamas a la función para que te devuelva un número grande de cartas (digamos, 100) , y con esta lista grande, vas distribuyendo las cartas del juego hasta que se te agote esta lista. Una vez se agote, llamas a la función de nuevo para tener mas cartas.  (de ahí lo que decía de 'eliminar la carta' para que no llames solo una vez a la función para generar cartas y luego reutilizes el primer "patrón" dado todo el juego).

- Llamas a la función cada vez que quieras sacar cartas, y le pides siempre el número exacto de cartas que necesites en ese momento. (necesitas sacar dos cartas, le pides 2).

Por lo tanto tu idea sería correcta.

**Comment by francisca0308** [comment]
Hola! En el enunciado sale que 

> El juego nunca robará una carta del mazo automáticamente por un jugador. Esto solo ocurre cuando el jugador decide robar del mazo.

Sin embargo, puedo asumir que esto no considera la repartida inicial de cartas? Que estas aparecen en la ventana de juego sin que los jugadores la pidan?

**Comment by Camila-sty** [comment]
@francisca0308 hola, no soy ayudante, pero con respecto a tu pregunta, yo creo que así debes  asumirlo, no hay ninguna nota en el enunciado que diga lo contrario, así que, yo creo que puedes, y puedes agregarlo en tu readme

**Comment by gatochico** [comment]
Confirmo! Puedes asumir lo que dices. Sin embargo, sí tienen que ir las cartas enviadas cuando comienza la partida en los logs, mas que nada por un tema de ayudar el _debugging_ para tí y los correctores
