### ISSUE TITLE
Robar carta a causa del +2

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#1029]
Hola, en el enunciado, en la página 5, punto 3, dice que no se puede robar automáticamente. Esto también aplica para cuando a uno le tiran un +2 y no tiene para responder?

**Comment by szabala** [comment]
Si! La idea es que el juego nunca robe por el jugador. Entonces en ese caso, aunque el jugador no pueda responder con otro +2, solo robara cuando aprete el boton para robar cartas (perdon por la redundancia c:).
