### ISSUE TITLE
Recolección de recursos

### ISSUE THREAD

**Issue by angelaparriana** [IIC2233/syllabus#103]
Cuando creo una nueva partida y tengo 3 trabajadores y elijo que recolecten recursos, puedo poner a los 3 a recolectar oro, piedra y madera, respectivamente?

**Comment by lily416** [comment]
Hola :)

Si, en un mismo turno puedes recolectar materiales distintos materiales y elegir cuántos trabajadores mandar a recolectarlos.

Saludos y éxito con la tarea 👋🏰
