### ISSUE TITLE
información relevante de mercados

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#103]
Hola! Tengo dos consultas respecto a lo que hay que desplegar para "Desplegar información de un mercado:" (final 3era página del enunciado):

1. El spread puede ser un valor **negativo** o debe ser **_siempre_** positivo (valor absoluto)?
2. El ask best y bid best son _**necesariamente**_ del mismo día en el que se está consultando?
🤔 

Muchas gracias y que tengan buen fin de semana! 😄 💻 🐍

**Comment by nebil** [comment]
1. ¿Qué tendría que ocurrir para el que el _spread_ fuese negativo? ¿Qué implicancias tendría esto?
2. No, no es necesario que el mejor _ask_ o el mejor _bid_ hayan sido colocados durante el mismo día de la consulta para que se muestren. Si imaginamos que hace dos días, un usuario realizó un _ask_ que, hasta ahora, sigue siendo la orden activa de venta con el menor precio, entonces **deberá** aparecer como el mejor _ask_ de hoy. Luego, esta información **no depende** del día de creación de las órdenes.

**Comment by rihanuch** [comment]
@nebil 
1. Ni idea, asumo que debería ser valor absoluto por tincada 🤓 
2. ok! gracias!

**Comment by iqacevedo** [comment]
@rihanuch me parece que la pregunta se refiere a ¿que sucede en el mercado si hay una _order_ de venta con un precio menor al de una _order_ de compra?.

Saludos !

**Comment by nebil** [comment]
@rihanuch, si haces un razonamiento en base a las preguntas que escribí en mi comentario anterior, estoy casi seguro de que tu inquietud sobre el signo del _spread_ se resolverá. :relieved:

**Comment by rihanuch** [comment]
el bid y ask best son orders activas?

**Comment by nebil** [comment]
Sí, al igual que el _spread_, esto se calcula en base a las órdenes activas del mercado.
