### ISSUE TITLE
Uso escritura en archivos con metodo .write( ) con parametros "a" o "w"

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#103]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Es conveniente usar el parametro "a" para escribir archivos con write o es mejor usar "w"? Que al usar "a" depende mucho de como hayan terminado de guardar el archivo, si por ejemplo dejaron un "\n" o no  al final del archivo puede arruinarlo para despues leerlo. Y aunque el parametro "w" puede solucionar este problema, escribir todo el archivo denuevo igual implica usar mas recursos del computador, ademas de que si, por cualquier motivo, se cierra el programa se podria perder parte de la informacion.

¿Cual es considerada la mejor practica en este caso?

**Comment by aljara97** [comment]
Hola @Ignacioislae, en esta tarea no usaremos bases de datos de un tamaño extenso, así que puede quedar a tu criterio cuál de los dos métodos implementar, mientras no se afecte la consistencia de los archivos. En el caso de trabajar con una base de datos mucho más extensa sería mejor trabajar con `"a"`.

Mucho éxito con tu tarea
