### ISSUE TITLE
Organización Menús

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#103]
Hola, en el enunciado (pag 5) dice que en el menú de prograposts, debe haber una opción de volver al menú de inicio (el cual es aquel donde se inicia sesión), sin embargo, más arriba en el enunciado, se pide que después de iniciar sesión, se de la opción de ir al menú de prograposts o de seguidores.
No será mejor que en vez de tener la opción de ir al menú de inicio, se vaya al menú anterior (al igual que en el menú de seguidores). Por lo menos yo lo hice así y no se si pasa por encima de las restricciones del enunciado.

**Comment by jeschuwirth** [comment]
Hola dlmed,

Tu forma de manejar los menus también es correcta, no hay problema con hacerlo de ese modo.

Para evitarte problemas te recomiendo citar esta issue en tu READMe ;)

Suerte!
