### ISSUE TITLE
Duda ubicacion incendios 

### ISSUE THREAD

**Issue by aSPCA** [IIC2233/Syllabus#103]
Hola!

En el enunciado en el punto 5.1 dice que:
Es necesario destacar que el radio de propagación esta indicado en metros por hora, mientras que la
ubicación de los incendios esta en grados, latitud y longitud, es por esto que pueden considerar 1o = 110 km

se refiere a que si por ejemplo tengo las coordenadas (lon: 2, lat: 3) y tomo la latitud como eje y y la longitud como eje x, puedo crear un plano cartesiano en que las coordenadas de la ubicación del foco del incendio son (220 km, 330 km)?

Gracias de antemano

**Comment by rpalmaotero** [comment]
Claro.
