### ISSUE TITLE
Duda nombre acciones jugador 

### ISSUE THREAD

**Issue by mvvaldes** [IIC2233/Syllabus#103]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, mi duda es que si las acciones de cada tipo de jugador se deben llamar como sale en el enunciado, ya que esto me causa problemas si la quiero definir la accion como metodo abstracto en la clase padre (Jugador) la que se hereda a cada tipo de clase de jugador

**Comment by catalina-arcila** [comment]
Hola @mvvaldes , la verdad que queda a tu criterio como vas a nombrar y formular tus entidades. Lo importante es que se noten bien diferencias las entidades, para que tengas el _puntaje del excel_. Además, recuerda que debes especificar tus entidades en el README. Suerte!
