### ISSUE TITLE
Duda sobre "rulos" en red y métodos

### ISSUE THREAD

**Issue by ssepul21** [IIC2233/Syllabus#103]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!
 Tenía la duda de si es necesario ponernos en el caso donde la estación de inicio sea igual a la estación de destino, lo cual es un rulo. En caso de que si, ¿cómo interpreto este suceso en métodos como `nivel_conexiones`, donde los output del método son específicos? o lo mismo con el método `invertir_tunel` (aunque en ese caso creo que cae en el caso 1)

Saludos!

**Comment by IanZmen** [comment]
Hola, en invertir_tunel por enunciado las 2 estaciones siempre serán distintas, mientras tanto para nivel_conexiones, considera siempre la menor distancia posible, interpretándolo como "tunel directo". EXITO

**Comment by ssepul21** [comment]
Me quedó clarito. Gracias!
