### ISSUE TITLE
Recolectar recursos (6.4.1)

### ISSUE THREAD

**Issue by Benjadef** [IIC2233/Syllabus#103]
En el punto 6.4.1, según lo que entiendo, al momento de visitar un planeta conquistado por primera vez, la ultima fecha de recolección no debería actualizarse, dado que "aun no elijo la opción de recolectar recursos", por lo tanto podría llevar horas en un planeta conquistado y no estaría generando recursos, a menos que la momento de visitarlo elija la opción de "recolectar recursos" (recolectando 0, dado que es la primera vez que recolecto).
Por otra parte si recolecto recursos en un planeta luego cierro el juego por una día, luego juego, al momento de recolectar recursos ¿la ultima fecha de recolección es del día anterior?

Saludos y muchas gracias!

**Comment by Pipelao** [comment]
Hola 

Según lo que entendí del enunciado en la sección 5.2 en última recolección, en caso de no haber fecha se utiliza la de cuando fue instanciada la clase. La otra pregunta no sé.

PD: No soy ayudante, xD.

Saludos.

**Comment by ptflores1** [comment]
Hola !
Como ya te dijo @Pipelao al crear un nuevo planeta debes asignarle la ultima fecha de recoleccion como la fecha de creacion.
Al recolectar los recursos tu programa debe ser capaz de "recordar" la fecha en que se recolectaron para cualquier otra "sesion".
Saludos !
