### ISSUE TITLE
Entrega de archivos en el flujo

### ISSUE THREAD

**Issue by palacioscb** [IIC2233/Syllabus#103]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola.
Tengo una duda con el tema de el archivo entregado en el flujo, en la parte de menú de inicio.
Se que este es un input, y además se deben usar paths relativos, pero no entiendo **de qué manera será entregado el input**.
Por ejemplo, si será "2x2", o "2x2.txt", o "Tareas\T0\Archivos\2x2.txt" (por dar algún ejemplo de path relativo).
Si no me equivoco, es necesario para poder saber de qué manera implementar las funciones mínimas abrir_archivo y cargar_archivo.
Me quedo atento a la respuesta. Muchas gracias por su tiempo!

**Comment by SALBUTAMOL12** [comment]
hola @palacioscb 
Con respecto a tu duda hay issues que responden a tu pregunta como #55 y #66.
Por otro lado con respecto al tercer ejemplo que entregas ("Tareas\T0\Archivos\2x2.txt") no debería estar agregado el "Tareas\T0\" debido a que se esta trabajando desde la carpeta T0, para que lo tengas en cuenta :thumbsup:.
