### ISSUE TITLE
Duda sobre input tarea

### ISSUE THREAD

**Issue by yuwet15** [IIC2233/syllabus#103]
Es posible asumir que al momento de pedir el numero de filas y columnas este solo ingrese numeros enteros? o puede ingresar cualquier cosa?

**Comment by Benja-c** [comment]
y se puede asumir que al momento de pedir filas y columnas no se va a ingresar un str?

**Comment by DCCollao** [comment]
Hola @Benja-c!

No puedes asumir eso. Ingresaremos cualquier tipo de dato, en cualquier formato y tu programa no debe caerse ante estos input.

**Comment by Benja-c** [comment]
Otra cosa cuando ya le pedi los inputs de filas y columnas tengo que dar la opcion de volver atras para elegir otro numero ?

**Comment by DCCollao** [comment]
Como no se pide en enunciado, no es necesario que des esa opción.
