### ISSUE TITLE
Commit a una actividad después de haberla entregado

### ISSUE THREAD

**Issue by nolate26** [IIC2233/Syllabus#103]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
Hola, quería saber si es que existe algún problema con hacer un commit a una actividad que ya fue entregada. Por ejemplo, quiero arreglar mi código de la **AS1**, para ver en que me equivoqué y dejarla guardada en mi repositorio,. Puedo hacer el commit sin que sea ese el que revisen y me la consideren como atrasada.
Gracias!!!

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by fernandosmither** [comment]
Hola!

No hay problema, ya que si quieres que te revisemos un commit posterior, el que conllevará un descuento, debes llenar un forms.
