### ISSUE TITLE
A quién gritar ¡DCCuatro!

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#1030]
Hola, con respecto a la acción de gritar, cómo se diferencia a quién va dirigida? por ejemplo, si hay 2 jugadores que poseen 1 carta, cómo diferencio a quién le grito? porque si uno ya gritó y el otro no, si aplico para los 2, voy a tener que robar cartas.

**Comment by gatochico** [comment]
Hola!

Para simplificar las cosas, puedes asumir que al momento de gritar DCCuatro, el grito será válido con tal que **por lo menos uno de tus contrincantes** tenga una carta y no haya gritado DCCuatro. De esta forma, no hay necesidad de implementar algo que dirija el grito a jugadores en específico.

En el caso que dices, donde hay 1 persona que gritó y una que no, si gritas DCCuatro la persona que no gritó a tiempo tendrá que tomar cartas y tú como jugador no caeras en ninguna penalización debido a la otra persona que sí había gritado. 

Espero me haya explicado bien! :)

**Comment by dlmed** [comment]
Gracias!!

**Comment by RonaldoSosa** [comment]
Hola! No me quedo del todo claro si por ejemplo j1 grita y estan tanto j2 como j3 con una carta sin gritar por algun motivo ambos son afectados ? Es decir debo hacer que el grito afecte a todos los que tengan una sola carta sin haber gritado?
