### ISSUE TITLE
duda indice bloques de envío de información

### ISSUE THREAD

**Issue by alterdieg0** [IIC2233/syllabus#1031]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

![image](https://user-images.githubusercontent.com/28828655/99890407-989d3980-2c3d-11eb-8ad4-059f69e819c8.png)

Hola en el punto 5.1.3 del enunciado al codificar los mensajes a enviar piden anteponer 4 bytes que indiquen **el número** del bloque en little endian, este numero parte del 0 o del 1?

Saludos

**Comment by alterdieg0** [comment]
según el dibujo del enunciado (que me acabo de fijar mejor) parten del 1 :eyes:
![image](https://user-images.githubusercontent.com/28828655/99890714-ea938e80-2c40-11eb-9a34-48646bc27137.png)

**Comment by lucasprato** [comment]
Hola alterdieg0,
Efectivamente hace más sentido que el primer bloque se numere con un 1 en vez de un 0 (a pesar de que sí es posible generar el número 0 a partir de los 4 bytes).
En caso de que quieras partir la numeración con un 0, es clave que lo documentes en el readme.
Éxito en la tarea
