### ISSUE TITLE
Qué mazo corresponde con qué jugador?

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#1031]
Hola, en el front-end de la Sala de Juego, cómo se diferencia de quién es cada mazo? como para saber cuántas cartas posee la persona que esté en el turno actual.

**Comment by DCCollao** [comment]
Hola @dlmed! 

Hay varias formas de diferenciar a quién pertenece cada mano dentro del juego. En el enunciado, a modo de ejemplo, pusimos la siguiente:
![image](https://user-images.githubusercontent.com/37167447/85211841-0d7ce800-b31b-11ea-9be0-78353540ac3c.png)

Entonces en el momento en que Blanca o Murry jueguen una carta, se debería mostrar en interfaz que la mano correspondiente a ese jugador pierde una carta. Con eso basta para tener claro que esa mano corresponde a Blanca o a Murry.

Ahora, si quieres ser más explícito respecto a quién es quién, puedes agregarle los elementos visuales que estimes correspondientes para hacerlo.

Espero haber respondido tu duda, éxito!

**Comment by dchahuan** [comment]
Pero envez de mostrar las cartas como todas en fila, se podria poner una sola carta y el numero de cartas que tiene arriba??

**Comment by DCCollao** [comment]
En la issue #1032 se habla de formas de mostrar las cartas cuando son más de 4. De todas formas, sería válido si decides hacerlo con el número de cartas que tiene arriba.
