### ISSUE TITLE
Output generador_de_cartas.py

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#1032]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

¡Hola!

No entiendo el output de `generador_de_cartas.py`. ¿Qué representa el segundo elemento de cada tupla?

Muchos saludos.

**Comment by rodrigobj99** [comment]
Hola @amahns1 
Tal como indica el enunciado:

![Captura de Pantalla 2020-11-22 a la(s) 1 12 32 p  m](https://user-images.githubusercontent.com/49729086/99908993-916d3e80-2cc4-11eb-9d5d-df1b6209b781.png)

Los elementos de cada tupla te sirven para llamar a los _sprites_ de las cartas de desarrollo, en este caso monopolio siempre estará acompañado de un 1 ya que solo hay un tipo de carta de monopolio en los _sprites_, mientras que para victoria hay dos tipos (y dos _sprites_) por lo cual puede estar acompañada por un 1 o un 2.
