### ISSUE TITLE
Display de cartas cuando son mayores a 4

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#1032]
Hola, en vista de que la cantidad de cartas que puede tener un jugador va desde 4 a 10, siendo estos parámetros que luego pueden ser modificados; cómo se debería hacer el display de cartas en la Sala de Juego?

**Comment by szabala** [comment]
Hola! La idea es que siempre sea visible la cantidad de cartas que los otros jugadores tienen en su mano. **Queda a tu criterio** como diseñar la interfaz gráfica para cumplir esto. Las interfaces mostradas en el enunciado solo son para ejemplificar.

Como recomendación, puedes usar BoxLayouts si quieres mostrar una cantidad indefinida de elementos en un espacio fijo. Por otro lado, puedes dejar 10 espacios definidos por jugador en tu layout e ir llenandolos acorde a la mano de cada jugador.

Espero haberte ayudado, saludos!

**Comment by BelenSilva1204** [comment]
Holaa, creé un QHBoxLayout con 10 Qlabels respectivos vacíos, pero al momento de añadir sólo dos cartas como si fueran mi mazo inicial las cartas se adecuan al tamaño del QHBoxLayout y quedan muy grandes/anchas, hay alguna manera de solucionar esto?;;

**Comment by etgutierrez** [comment]
Holaa, no soy ayudante, pero puedes usar .scaled(), al setear el pixmap

**Comment by beatrizacuna** [comment]
Hola! intenté lo de scaled, pero aún me siguen saliendo de un tamaño para adecuarse al BoxLayout :( qué puede estar mal?

**Comment by szabala** [comment]
Hola @BelenSilva1204 @beatrizacuna, pueden enviar una foto de como queda en la interfaz?
Perdon por la demora.

**Comment by beatrizacuna** [comment]
![Captura de pantalla 2020-06-30 a la(s) 20 59 01](https://user-images.githubusercontent.com/48481963/86191283-a9c19e80-bb14-11ea-816a-a689e99967e7.png)

**Comment by szabala** [comment]
Hola! Si no pudiste solucionar esto con el método .scaled(), puedes tratar de fijar el tamaño de la label. Otra forma es agregar [spacers ](https://stackoverflow.com/questions/33793315/how-to-use-spacers-in-qt)dentro de tu layout. 
Espero con esto puedas solucionarlo 😄

**Comment by beatrizacuna** [comment]
Me sirvió poner spacers, muchas gracias! Pero aún me gustaría saber por qué no funcionó el scaled 🤕  porque así se me haría mucho más fácil la implementación de nuevas cartas a la mano de cada jugador

**Comment by beatrizacuna** [comment]
ya lo resolví!

**Comment by BelenSilva1204** [comment]
> ya lo resolví!

Holaaa, te resultó scaled() o lo solucionaste de otra manera:( ?

**Comment by beatrizacuna** [comment]
sii, es que estaba poniendo scaled, y después setScaledContents(True), sacando el setScaledContents(True) se solucionó :)
