### ISSUE TITLE
Duda avance

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#1033]
En el avance no sale especificado si los mensajes que recibirá el cliente los recibirá en su terminal o en otra interfaz gráfica, ¿nosotros decidimos de que manera se va a recibir lo que el servidor enviará a cada cliente?, me refiero a si lo debemos mostrar  en alguna ventana o en la terminal del cliente

**Comment by lucasprato** [comment]
Hola!
> En el avance no sale especificado si los mensajes que recibirá el cliente los recibirá en su terminal o en otra interfaz gráfica, ¿nosotros decidimos de que manera se va a recibir lo que el servidor enviará a cada cliente?

Sobre esto, tal como dice el enunciado, el protocolo de comunicación siempre será entre el servidor y el backend de cada cliente, por lo que la comunicación nunca podría ser con un elemento del frontend. 

> me refiero a si lo debemos mostrar en alguna ventana o en la terminal del cliente

Ten en consideración que el objetivo del avance es lograr la conexión de los clientes, los logs de los clientes y el protocolo de comunicación. Queda a tu criterio si quieres que los clientes muestren la información que reciben desde el servidor y cómo hacerlo. En este sentido, si quieres hacerlo te recomiendo algo parecido a los logs del servidor por consola.

Éxito en la tarea!!
