### ISSUE TITLE
Número de port 

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#1033]
Hola! Nunca me quedó muy claro qué port número de port usar, estoy viendo en los cuadernos de contenidos y son todos distintos, puedo poner cualquiera para la tarea? Gracias y perdón si la duda es tonta que nunca entendí bien estoo

**Comment by entamburini** [comment]
Hola @jirarrazaval!, 

En resumidas cuentas, puede ser cualquiera mientras seas consistente tanto en el cliente como en el servidor. 

La razón de por qué hay que especificar el puerto es porque el computador tiene muchos (de verdad que demasiados!) para poder ocupar hartas cosas a la vez (por ejemplo chrome, descargar alguna cosa, spotify, etc), entonces es necesario que tu programa sea explícito cual puerto está usando para comunicarse dentro de tu computador (o en caso de que lo expongas al internet, para que otro computador entre y se comunique con el tuyo en el puerto correspondiente). 

Por eso no importa el número que pongas, siempre que seas consistente entre cliente y servidor ^^

**Comment by jirarrazaval** [comment]
Ya muchas gracias!
Otra pregunta, me sale este error cuando hago el bind con el servidor:}

self.socket_server.bind((self.host, self.port))
TypeError: str, bytes or bytearray expected, not int

Y la verdad es que no sé qué puede ser porque así lo han hecho en todos los ejemplos y todos funcionan pero el mío sale este error.. por que pasa???

**Comment by entamburini** [comment]
El error dice que le estás entregando algo de un tipo que no entiende. Estás segura de que ocurre en el momento del bind? estás segura de que el host es un string y no un entero? :o es difícil sin más información :c. 

Te propongo que le pongas prints y así rastrear el error :) (imprime lo que le llega al bind por si acaso)

**Comment by jirarrazaval** [comment]
Sí es un entero!! Pero imprimí el de los ejemplos y también son enteros! Ninguno transforma su port en strings, por eso no sé por qué yo debería hacerlo! No sé si me entiendes

**Comment by entamburini** [comment]
ajajaj buenisima! :raised_hands:
