### ISSUE TITLE
Path en archivo json

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1034]
Hola! Como se podrían guardar las rutas a los archivos en un archivo json , cuando intente importar os a mi archivo parametros.json me tiro un error , o no es necesario guardar la dirección en el sino solo un indicador, me refiero a algo como {"ruta":"imagen que deseo"} y crear la ruta a la imagen que yo deseo en un archivo.py .?

**Comment by DCCollao** [comment]
Hola @RonaldoSosa!

El error que obtuviste se debe a que los `import` funcionan solamente en archivos de formato `.py`.
**Una** forma de guardar paths en archivos `.json` es guardar el path en una lista, y esa lista entregarla como *value* de tu diccionario en *json*.

Por ejemplo:
`{'path_imagen': ["carpeta1", "carpeta2", "archivo"]}`

Al hacerlo de esta forma, puedes utilizar la librería `os` para trabajar con el diccionario en un archivo `.py`, de forma que no obtengas el error que mencionaste.

Éxito!

**Comment by RonaldoSosa** [comment]
Entendido, me quedo claro !! Gracias!!
