### ISSUE TITLE
Qué ignorar con gitignore

### ISSUE THREAD

**Issue by Zenos-Paradox** [IIC2233/syllabus#1035]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

En el enunciado dice que hay que ignorar sprites pero ¿Hay que hacerlo aún teniendo en cuanta que hay que reorganizar los archivos en dos directorios (de cliente y servidor)?

**Comment by EduardoIllanes** [comment]
Hola @Zenos-Paradox , si debes ignorar los sprites. Ahora, para ignorar un archivo o un sub-directorio dentro de un directorio basta con hacerlo de la forma `mi_carpeta/lo_que_quiero_ignorar`.Espero que te sirva y mucho éxito con tu tarea 😄
