### ISSUE TITLE
Numero de Jugadores por Partida

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#1036]
En el enunciado se dice que el numero de jugadores por partida es un parámetro, pero ¿este lo decidimos nosotros y no se cambia después?. O se espera después la interfaz gráfica se adapte a cualquier numero jugadores que existan.

**Comment by DCCollao** [comment]
Hola @felipefuentesporras!

En el enunciado se menciona que es un parámetro de forma que debe estar incluido en sus archivos de parámetros. El valor de dicho parámetro estará siempre entre 2 y 4, de forma que tu programa se debe adaptar a partidas de entre 2 y 4 personas, según el valor que tenga al momento de la ejecución.

**Comment by felipefuentesporras** [comment]
ya gracias!!
