### ISSUE TITLE
Dudas sobre acciones del jugador: construcciones e intercambios, si son inválidos se puede hacer otra acción?

### ISSUE THREAD

**Issue by mt-garcia** [IIC2233/syllabus#1036]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado dice que un jugador puede realizar *una acción durante su turno*, como comprar carta de desarrollo, intercambiar con jugadores, construir carretera o choza. No me quedó claro eso sí si al construir carretera o choza, si es inválida la acción, ¿el jugador *debe intentar construir en otro lado o elegir otra acción?*
Y también con el intercambio con otros jugadores, si el intercambio es "inválido" como sale en el enunciado, *¿puede elegir otra acción o perdió su oportunidad?*

**Comment by matiasmasjuan** [comment]
Hola @mt-garcia !

Tal como señala en enunciado:

![construir_reglas](https://user-images.githubusercontent.com/48495638/99956357-a7cad700-2d64-11eb-89c2-7bc293b9c6d9.png)

Ahora bien, la acción a realizar depende de **por qué** fue **inválido** la compra. Evidentemente, si la compra no se puede efectuar por **falta de recursos**, basta con **notificar al usuario** que la acción no fue posible realizarla debido a esto. Ahora bien, si el jugador **sí** tiene los recursos, pero la **posición de la construcción** es **inválida** (en el caso de una carretera el espacio ya está ocupado o no es continuo a una contrucción del jugador, y en el caso de la choza cuando no es construida a diferencia de 2 carreteras de otra choza) la idea es poder **notificar** al usuario pero permitiendo la acción de comprar nuevamente, por lo que habría que reubicar la construcción.

Para el caso del intercambio ocurre algo similar. En caso de que el **intercambio sea inválido** (ya sea por falta de recursos del jugador o de la otra persona con la que quieras intercambiar) se deberá notificar que el intercambio **no se pudo realizar**. Luego de esto, el turno del jugador debe funcionar de manera normal, por lo que debe ser posible intentar intercambiar nuevamente o realizar cualquier otra acción.

Espero haber respondido a tu pregunta, y mucho éxito con la tarea! :smile:

**Comment by mt-garcia** [comment]
> Hola @mt-garcia !
> 
> Tal como señala en enunciado:
> 
> ![construir_reglas](https://user-images.githubusercontent.com/48495638/99956357-a7cad700-2d64-11eb-89c2-7bc293b9c6d9.png)
> 
> Ahora bien, la acción a realizar depende de **por qué** fue **inválido** la compra. Evidentemente, si la compra no se puede efectuar por **falta de recursos**, basta con **notificar al usuario** que la acción no fue posible realizarla debido a esto. Ahora bien, si el jugador **sí** tiene los recursos, pero la **posición de la construcción** es **inválida** (en el caso de una carretera el espacio ya está ocupado o no es continuo a una contrucción del jugador, y en el caso de la choza cuando no es construida a diferencia de 2 carreteras de otra choza) la idea es poder **notificar** al usuario pero permitiendo la acción de comprar nuevamente, por lo que habría que reubicar la construcción.
> 
> Para el caso del intercambio ocurre algo similar. En caso de que el **intercambio sea inválido** (ya sea por falta de recursos del jugador o de la otra persona con la que quieras intercambiar) se deberá notificar que el intercambio **no se pudo realizar**. Luego de esto, el turno del jugador debe funcionar de manera normal, por lo que debe ser posible intentar intercambiar nuevamente o realizar cualquier otra acción.
> 
> Espero haber respondido a tu pregunta, y mucho éxito con la tarea! 😄

Sii, respondió mi duda, muchas gracias!
