### ISSUE TITLE
Chunk size 

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#1037]
Hola, en la parte de envió de cartas no me queda claro el chuck size? Lo tomamos como 4?

**Comment by szabala** [comment]
Hola! si ves el diagrama del _bytearray_, los _chunks_ que indican el identificador del objeto y el largo del siguiente bloque tienen **tamaño fijo 4**. Sin embargo, el _chunk_ que corresponde al objeto serializado no tiene que tener un tamaño especifico. El tamaño de este ultimo chunk se indica en el bloque anterior.
