### ISSUE TITLE
Tratando de usar localhost me dice que no tengo permiso

### ISSUE THREAD

**Issue by Cjparra97** [IIC2233/syllabus#1037]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Tratando de correr el servidor de la tarea me tira el siguiente error 'PermissionError: [Errno 13] Permission denied', trate de modificar el archivo con chmod 777 pero me sigue diciendo que no tengo autorizacion. Necesito autorizacion para usar como host localhost incluso cuando soy admin en el computador??

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by DCCollao** [comment]
Hola @Cjparra97! 
¿Tuviste este problema al ejecutar los archivos correspondientes a los contenidos de _networking_?

Estaré atento.
