### ISSUE TITLE
Duda parametros.json

### ISSUE THREAD

**Issue by margavicunas** [IIC2233/syllabus#1038]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holis, me surgió la duda de cómo poner los paths de los archivos de designer en el archivo de parámetros json u.u especialmente porque no permite importar os para hacer path.join ¿Dónde irían entonces? 
Gracias y suerte con el fin de semestre a la personita que lea esto 🌻

**Comment by matiasmasjuan** [comment]
Hola @margavicunas !

No hay problema con que los *paths* los guardes en el archivo ```parametros.json```. Recuerda que estos pueden ser importados en un archivo **.py** con el uso de ```json.load(nombre_archivo.json)```. Luego de esto, es posible obtener la ruta que deseas y utilizar la función de **os**, ```path.join```, para poder crear el *path* correctamente.

Saludos y mucho éxito con la tarea! :smile:

**Comment by margavicunas** [comment]
Ahhhh! Entonces el path.join tendría que hacerlo una vez cargado el archivo de parámetros?? Y en el json poner como una lista de las "partes" de la ruta?? (tipo --> ruta: ["cliente", "carpeta 1", "archivo que quiero"])

**Comment by matiasmasjuan** [comment]
Exacto! La forma en que quieras guardar el *path* en el archivo ```parametros.json``` queda a tu criterio según lo que te resulte más cómodo para hacer el ```os.path.join``` después.

Saludos!

**Comment by margavicunas** [comment]
Súper! Muchísimas gracias por la aclaración y la ayuda❤️
