### ISSUE TITLE
No entiendo como el servidor provee las cartas

### ISSUE THREAD

**Issue by Francisco5674** [IIC2233/syllabus#1039]
Hola gente, tengo un problema con lo del servidor cuando este tiene que pasar las cartas a sus clientes, se que puedo pasar archivos y todo ese tema con los sockets, pero si paso una carta, para poder mostrarla en pantalla necesito escribir un archivo de manera local de todas formas en el almacenamiento que este usando el usuario de cualquier cliente, entonces si es que el server provee las cartas, como que es un poco extraño que mande la carta, el cliente debe escribir un archivo nuevo y luego mostrar la carta con cada jugada correspondiente, porque el almacenamiento del cliente se va empezar a llenar con cartas incluso puede que repetidas, ¿No es más fácil que el cliente mande todo el mazo completo a cada cliente para que dichos clientes puedan usarlas con libertad?, de paso. de la misma manera que puedo crear archivos en el almacenamiento del cliente, ¿también puedo borrarlos? si es así, entonces puedo hacer lo que ustedes piden borrando las cartas que el cliente ya no este usando, aunque sería más difícil, algo similar a un almacenamiento de uso de memoria de acceso aleatorio, guardando archivos por un tiempo determinado y luego eliminarlos cuando dejen de ser útiles.

Saludos!

**Comment by szabala** [comment]
Hola! Es **requisito** de esta tarea que el servidor sea el único que tenga acceso directo a las imágenes. No necesitas guardar la imagen de manera local en el cliente para mostrarla en el juego. La idea (como se explica en la sección de "Envió de Cartas") es que el servidor serialice la imagen en forma de _bytes_ para luego mandarla dentro del _bytearray_ al cliente. Luego, este de-serializa la imagen y la carga en la interfaz.

Espero haberte ayudo, saludos!

**Comment by RenatoVWS** [comment]
Holaa una pregunta relacionada con lo mismo, si es que el servidor se encarga de proveer las imágenes, ¿También tiene que proveer la imagen del logo para construir la interfaz gráfica? ¿O puedo poner esa imagen en la carpeta de Cliente para construir la interfaz?
Saludos :)

**Comment by szabala** [comment]
Hola! En el enunciado se pide que el servidor provea las imagenes de las **cartas**. Puedes incluir el resto de sprites que utilices para la interfaz en la carpeta del cliente. Solo recuerda especificar en tu README donde hay que ubicar cada archivo.
Saludos!

**Comment by jonanortizvega** [comment]
Hola. La parte de atrás de las cartas también debe ser enviada desde el servidor? De ser así, se puede almacenar en el cliente para no tener que enviarla todo el tiempo?

**Comment by szabala** [comment]
Hola! El reverso de la carta también debe ser enviado desde el servidor. No es necesario que lo envíes todos los turnos, puedes almacenarlo como una variable en el cliente.
Saludos y disculpa la demora!
