### ISSUE TITLE
No funciona socket.accept()

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#1039]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, estoy intentando hacer que mi servidor acepte conexiones pero no me esta resultando :c. Estoy utilizando casi el mismo código que el utilizado en los ejemplos: 
![image](https://user-images.githubusercontent.com/69520590/99917548-b75c0880-2cef-11eb-9135-89020d78445d.png)
El programa solo hace print de "hola" pero no llega al print de "chao". Además, después de hacer el print de "hola", el programa se termina sin arrojar ningún error. Espero puedan ayudarme.

PD: estoy ocupando como host = "localhost" y puerto = 11111

He intentado arreglar el problema y me di cuenta que si ejecuto el programa, a veces me sale el siguiente error: 
![image](https://user-images.githubusercontent.com/69520590/99918423-7ebf2d80-2cf5-11eb-8d8a-46addc429008.png)

**Comment by DCCollao** [comment]
Hola @En-clases! 

Ya que mencionas una comparación con el código de los ejemplos, ¿éstos te funcionarion correctamente?

En este caso donde el _debug_ es especialmente complicado debido a la falta de información acerca del error en la cmd, te recomiendo que dejes tu código lo más similar que se pueda al que sabes que funciona (ejemplos), y le comiences a agregar cosas de a poco hasta que llegues a tu código actual (o a uno que funciona y es muy parecido al actual!).

Quedo atento por si aun así no logras encontrar el error.

**Comment by DCCollao** [comment]
Tengo unas preguntas más para tratar de ver el problema:

1. ¿El programa no imprime `chao` luego de conectar un cliente?
2. ¿El error sale por sí solo o solamente luego de que detienes el programa con `ctrl+c`?

**Comment by En-clases** [comment]
He ejecutado mi código de nuevo y ahora el servidor si me acepta conexiones. No sé qué cual habrá sido el error ya que no cambié nada del código. Gracias de todas maneras!
