### ISSUE TITLE
Estrategia de Extincion

### ISSUE THREAD

**Issue by NicolasCabello** [IIC2233/Syllabus#104]
tengo una duda cuando se ataca un incendio: por ejemplo si es cierto instante to tengo que los ptos de poder de un incendio son 1000 y para atacar el incendio tengo 600, tendre una diferencia de 400.. luego de ello como se supone que se sigue expandiendo el incendio?, debo recalcular el radio para cada instante?, no me queda muy claro como es el mecanismo de apagar el incendio :/

**Comment by rpalmaotero** [comment]
Revisa #59.
