### ISSUE TITLE
Archivo se escribe muy lento y no siempre se actualiza

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#104]
Mi codigo estaba corriendo perfecto y cuando agregue una funcion de eliminar posts, todo dejo de funcionar en relacion a escribir y leer los archivos csv.
Ahora no puedo escribir y cuando lo hago se demora como 4 minutos en actualizarse el archivo con la nueva linea (y solo funciona a veces en posts.csv pero no en usuarios). Tampoco lee bien porque antes por ejemplo podia ver todos los posts en el muro y propios perfecto y ahora sale error.
Se que es muy amplia mi pregunta pero quizas alguien sabe algo! Porque no e cambiado nada esa parte del codigo y todo dejo de funcionar
Gracias!

**Comment by jeschuwirth** [comment]
Hola @jirarrazabal,

Primero que nada asegúrate de estar cerrando los archivos una vez que los abres. Si ese no es el problema sube tu programa al github y lo puedo revisar desde acá.

Espero una respuesta :)

**Comment by jirarrazaval** [comment]
Me funciono tu consejo y ya me corre como antes! muchas gracias!!!

**Comment by jeschuwirth** [comment]
Evita cerrar las issues por si le sirven a algún otro alumno
