### ISSUE TITLE
Duda sobre utf8 en tablero.py - T00

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2233/syllabus#104]
Hola, que tal? Tengo un problema: cuando corrí el código de main.py para visualizar el tablero me imprimió un mensaje de error, pensé que podía arreglarlo cambiando el valor predeterminado del uft8 de "True" a "False" en el archivo tablero.py. Efectivamente me imprimió el tablero pero en el formato que el enunciado decía que no debía imprimir. ¿Cómo lo soluciono?

**Comment by DCCollao** [comment]
@ignacioarteaga99, si ejecutas tu programa por consola utilizando
`python main.py`
obtienes el mismo error?

Por otro lado, sí es válido que entregues tu tarea sin el utf-8 del tablero. También podrías tratar entregándolo con utf-8 y explicando en tu `readme.md` que tuviste problemas con eso.
