### ISSUE TITLE
Error 'Session cannot generate requests'

### ISSUE THREAD

**Issue by aplaza2** [IIC2233/Syllabus#104]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Hola, me ha pasado en algunas ocasiones que cuando trato de correr algún código me sale el error **'Session cannot generate requests'**, pero no logro entenderlo. No comprendo qué lo dispara e incluso hay veces que se me arregla solo. ¿Me podrían explicar el por qué salta y cómo arreglar este error?

PD: Utilizo vs code. No sé si tenga algo que ver, pero prefiero mencionarlo.

**Comment by Crisax234** [comment]
Me pasa exactamente lo mismo y se me arregla cuando quiere como se puede solucionar?

**Comment by pepinofdz** [comment]
+1
estaba haciendo los ejercicios propuestos de la semana 4, llegué al 2.3 y ahora no me funciona ni siquiera un print('a')

**Comment by fernandosmither** [comment]
¿Cómo estás corriendo el código? de casualidad te funciona si manualmente en la terminal escribes `python {modulo}.py`?

**Comment by aplaza2** [comment]
Pero al hacer eso se van a correr todas las celdas de código? Porque por ejemplo en las actividades propuestas en un mismo archivo hay varias celdas de código

**Comment by fernandosmither** [comment]
> Pero al hacer eso se van a correr todas las celdas de código? Porque por ejemplo en las actividades propuestas en un mismo archivo hay varias celdas de código

Ah ya veo, te refieres a que tienes problemas ejecutando líneas de código de un Jupyter Notebook usando VSC?

En ese caso, te recomendaría correr directamente los jupyter notebooks utilizando el laucher oficial de jupyter-lab https://jupyter.org/install

Sin embargo, si por alguna razón sigues prefiriendo utilizarlo en VSC, necesitaría tener alguna captura de pantalla completa de tu VSC con el error, o preferiblemente los pasos para replicar el error. De todas formas lo comentaré a los demás ayudantes a ver si a alguien le ha pasado esto.

**Comment by aplaza2** [comment]
Agradezco el consejo de los jupyter notebooks, pero igual me gustaría tratar de averiguar sobre el error y de cómo solucionarlo. Un ejercicio donde siempre me salta es en el ejercicio propuesto 2.3 defaultdicts, donde al momento de presionar el triángulo superior izquierdo de la celda para correr el código (el equivalente a hacer Ctrl+Alt+Enter) me sale este error y luego cualquier otra celda que trate de correr le salta este mismo error. Pero si no activo este ejercicio, todos los otros ejercicios corren sin problema

![image](https://user-images.githubusercontent.com/76175241/133939819-79d5d81c-27be-4eef-8150-880bbea46065.png)

**Comment by fernandosmither** [comment]
> Agradezco el consejo de los jupyter notebooks, pero igual me gustaría tratar de averiguar sobre el error y de cómo solucionarlo. Un ejercicio donde siempre me salta es en el ejercicio propuesto 2.3 defaultdicts de la semana 4, donde al momento de presionar el triángulo superior izquierdo de la celda para correr el código (el equivalente a hacer Ctrl+Alt+Enter) me sale este error y luego cualquier otra celda que trate de correr le salta este mismo error. Pero si no activo este ejercicio, todos los otros ejercicios corren sin problema
> 

Curioso, a mí al correrlo me tira simplemente el KeyError que Tomate no está en las frutas creadas: 

![image](https://user-images.githubusercontent.com/66154723/133942048-741679ac-4a7c-444a-94f9-7f5a67141787.png)


El cual se puede arreglar dejando solo frutas que existen:

![image](https://user-images.githubusercontent.com/66154723/133942068-85496eda-2469-4a9d-ab70-40e579bb306f.png)

<details>
<summary> Código: </summary>

```python
from random import randint


class MiDefaultDict(dict):
    
    def __init__(self, funcion_default=None, *args):
        super().__init__()
        self.funcion_default = funcion_default
        self.args = args
        
    def __getitem__(self, llave):
        # Este método se llama implicitamente al usar objeto[llave].
        # Pista: Para guardar un par llave-valor dentro del diccionario,
        # utiliza: self[llave] = valor
        
        # Utiliza aquí un bloque try/except, y maneja la excepción correspondiente
        # Recuerda usar funcion_default y args para determinar el nuevo valor!
        return super().__getitem__(llave)


# Crea la instancia del diccionario
rating_frutas = MiDefaultDict(randint, 0, 10)

# Agrega valores al diccionario
rating_frutas.update({
    "Manzana": 3,
    "Plátano": 7,
    "Arándanos": 6,
    "Pera": 3,
    "Sandía": 4,
    "Durazno": 5,
})

lista_de_frutas = ["Arándanos", "Sandía", "Pera"]

for fruta in lista_de_frutas:
    print(f"{fruta} tiene un rating de {rating_frutas[fruta]}/10!")
```
</details>

Lo que me hace pensar
* Será que cualquier excepción lanzada en tu jupyter provoca ese error?

Un checklist un poco obvio pero que quizás sirva
* ¿Seleccionaste una versión de python que te esté funcionando, cuando vscode te pide "select interpreter"?
  * Puedes cambiar el interpreter con ctrl + shift + p > Python: Select Interpreter
* Tienes la extensión de Jupyter correctamente instalada? (Ve si reinstalándola se arregla)
* Te aparece Jupyter Server: Local?
![image](https://user-images.githubusercontent.com/66154723/133942214-b6760c2a-6521-4867-8279-27a00ccd3c32.png)
* Te ocurre el mismo error cuando intentas correr esa celda desde el launcher de jupyter-lab?


Espero tus respuestas así podemos buscar una solución en conjunto, mientras no aparezca alguien que sepa exactamente qué es. Saludos! 😄

**Comment by carmebe** [comment]
Hola, a mi también me había aparecido este error mientras intentaba hacer el ejercicio, seguido por un "Kernel is dead". Si pones ese código en un entorno solamente de Python, verás que te entrega un **error de recursión** (el jupyter notebook se cuelga con un error de este tipo)

Espero que te haya servido, saludos!

**Comment by aplaza2** [comment]
Hola, me puse a revisar lo que me dijeron y llegué a lo siguiente:
- La versión de Python es funcional y está activada
- La extensión de Jupyter está correctamente instalada
- Sí aparece Jupyter Server: local

Eso sí, revisando particularmente el ejemplo (2.3 semana 4) descubrí que lo que dispara el error es una línea donde hago:

valor = self.[llave] 
(recordando que estamos definiendo el método getitem(llave) de una librería que estamos definiendo) 

Traté de pensar este error con lo del error de recursión, pero no llego a una conclusión. Además, si fuera solo un error en la celda tampoco entendería por qué cuando aparece luego me sale este mismo error en cualquier otra celda. Ojalá con la info nueva sea más claro para alguien qué está sucediendo y por qué se dispara el error.

**Comment by carmebe** [comment]
Si intentas usar ``self[llave]`` dentro del método ``__getitem__`` de la clase heredada de ``dict``, estas haciendo recursión, ya que son lo mismo, en ese caso no deberías trabajar con la clase tal cual, sino con la superclase. Y reitero, jupyter se cuelga a nivel global si se encuentra un error de recursión, es decir, deberás reiniciar el kernel cada vez que suceda.

**Comment by fernandosmither** [comment]
> Hola, me puse a revisar lo que me dijeron y llegué a lo siguiente:
> 
> * La versión de Python es funcional y está activada
> * La extensión de Jupyter está correctamente instalada
> * Sí aparece Jupyter Server: local
> 
> Eso sí, revisando particularmente el ejemplo (2.3 semana 4) descubrí que lo que dispara el error es una línea donde hago:
> 
> valor = self.[llave]
> (recordando que estamos definiendo el método getitem(llave) de una librería que estamos definiendo)
> 
> Traté de pensar este error con lo del error de recursión, pero no llego a una conclusión. Además, si fuera solo un error en la celda tampoco entendería por qué cuando aparece luego me sale este mismo error en cualquier otra celda. Ojalá con la info nueva sea más claro para alguien qué está sucediendo y por qué se dispara el error.

Avísame si la respuesta de @carmebe te hizo sentido. En particular podrías revisar si es la recursión lo que causa este error en particular corriendo por ejemplo:
```python
def dormammu(func):
    return func(func)
dormammu(dormammu)
```

El kernel también se muere cuando abrimos y cerramos interfaces gráficas.
```python

import sys
from PyQt5.QtWidgets import QWidget, QApplication

class MiVentana(QWidget):
    def __init__(self):
        super().__init__()
        self.setGeometry(200, 100, 300, 300)
        self.setWindowTitle('Mi Primera Ventana')


if __name__ == '__main__':
    app = QApplication([])
    ventana = MiVentana()
    ventana.show()
    sys.exit(app.exec_())
```

De hecho, logré replicar tu error al matar el kernel con el código de arriba. Namely,
![image](https://user-images.githubusercontent.com/66154723/134052683-226ac891-f41a-412b-8bb3-8f9e0c932afb.png)

Ya que esto te sucederá tanto en vscode como en el laucher oficial, te recomendaría practicar en archivos .py y no en jupyter notebooks, para este tipo de cosas. Avísame si te quedó alguna duda!

**Comment by aplaza2** [comment]
Revisé los ejercicios donde ocurría ese error y con lo que dijo @carmebe quede claro y pude arreglarlo. Realmente muchas gracias por la ayuda y tendré en cuenta este error para las recursiones y las interfaces gráficas (además de trabajar en archivos.py).
