### ISSUE TITLE
Duda método cliente_recurrente en Bebedor

### ISSUE THREAD

**Issue by diegorakos** [IIC2233/Syllabus#104]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! No comprendo qué debe hacer el método ```cliente_recurrente``` de un ```Bebedor```. Según el enunciado la actualización de los atributos de un jugador depende del método ```consumir``` del ```Bebestible```, y no veo en qué podría aportar el método ```cliente_recurrente``` a hacer lo que se pide.

![image](https://user-images.githubusercontent.com/80644651/162543595-5866fe10-f0aa-449a-ac78-23818b8ec9b9.png)
![image](https://user-images.githubusercontent.com/80644651/162543655-ee18526d-f483-4b39-a994-7570d077087a.png)

**Comment by Gsalinas1506** [comment]
Hola a ambos!

Lo que pide el enunciado es que cada vez que el bebedor consuma un bebestible se debe multiplicar todos los efectos producidos por el parámetro en cuestión. El hecho de que los jugadores tengan acciones especiales no indica que estas **necesariamente** deban ser modeladas como un método, si no que basta con que se cumpla con lo pedido en el enunciado.

Para este caso particular, la implementación de @Chumi-sun es un ejemplo de como se podría lograr el efecto de `cliente recurrente`

Espero se haya entendido, y cualquier cosa no duden en preguntar. Mucho éxito con la tarea! 🎲🃏

**Comment by Sebah01a** [comment]
Hola, como mencionas, " El hecho de que los jugadores tengan acciones especiales no indica que estas necesariamente deban ser modeladas como un método, si no que basta con que se cumpla con lo pedido en el enunciado." Sin embargo, en la corrección de mi avance, me dijeron que "Eso sí te faltó modelar algunas clases (Ojo 👀 los tipos de personalidades son clases, no métodos )". Entonces estoy confundido, no se si puedo tomar las personalidades como métodos dentro de Jugador o crear cuatro clases mas?.

**Comment by Gsalinas1506** [comment]
@Sebah01a Atención con que en esta issue hablábamos de las acciones especiales de cada jugador, no de su modelado debido a su personalidad. la personalidad y las acciones especiales de esta son cosas distintas: Es la personalidad (modelada como clase, como decía tu feedback) la que implica un comportamiento de acción especial, que puede ser modelada de distintas maneras. La diferencia es muy sútil, pero quedate con que una cosa engloba o implica a la otra

Espero poder haberte ayudado. Cualquier cosa no dudes en preguntar :D
