### ISSUE TITLE
Error en la rubrica - Parte Menú

### ISSUE THREAD

**Issue by bea-or** [IIC2233/Syllabus#104]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Error en la rúbrica en la parte 2 - menú

Hola, estaba leyendo el documento donde salen la asignación de puntaje y me di cuenta que en la parte 2, esta repetido dos veces "Se verifica correctamente el nombre de usuario. Se avisa en consola si es que es inválido.", mientras que no asigna puntaje por revisar si el nombre del tablero es valido. Asumo que uno de ellos es que revise el nombre del tablero sea valido, correcto?

**Comment by Hernan4444** [comment]
Hola @bea-or 

Tal como dices, uno de ellos valida el nombre de usuario y otro el nombre del tablero. Ya se corregió ese typo.

Muchas gracias por notarlo. 
Saludosヾ(＾-＾)ノ
