### ISSUE TITLE
Discrepancia en orders dadas a users y orders creadas en csvgenerator.py

### ISSUE THREAD

**Issue by MrEarle** [IIC2233/Syllabus#104]
Noté que al crear los csv con el archivo csvgenerator.py, no siempre calzan la cantidad de orders que tienen los usuarios (en conjunto) con la cantidad de orders en el archivo orders.csv
Es intencional? Porque de esta manera quedan orders puestas en el mercado por nadie (sin un usuario que lo haya hecho) Esto es un problema al intentar hacer match con estar orders, porque no existe un usuario al que pagar.

**Comment by rihanuch** [comment]
te refieres al issue #55 o no?

**Comment by MrEarle** [comment]
Si, no lo habia visto...
Van a subir un csvgenerator.py actualizado? Se hace difícil probar el programa con este error...

**Comment by rihanuch** [comment]
@hanavarrete dijo:
> Eso fue un error de nuestro script 🎉 . Omítanlas por el momento, el archivo que usemos para la corrección estará correcto.

**Comment by MrEarle** [comment]
Dice que el de la corrección estará correcto, pero no dice que vayan a actualizarlo. Asumo que si, pero igual prefiero preguntar.
Gracias
