### ISSUE TITLE
Duda AC001

### ISSUE THREAD

**Issue by oscars810** [IIC2233/syllabus#104]
Hola,

En la actividad de ayer me quedaron varias dudas:
1) Que era lo que había que escribir en el archivo, en las funciones `deposito_seguro` y `retiro_seguro.`

2) En la función `cargar_cliente` de BancoSeguroDCC ¿hay que implementar desde 0 la función o usar la de la función padre?

3) En la clase DrPintoDesencriptador, cuál sería la diferencia entre hacer property de `texto_desencriptado` que retorna `desencriptar()` en vez de usar directamente `desencriptar()`

**Comment by jaromero6** [comment]
Hola!
Respecto a tús dudas:
1. El código de la función debería haber sido de la siguiente manera:
**_ATENCION_** : El código mostrado necesariamente debería ser idéntico, solo se muestra un ejemplo de como debería haber sido
```
def retiro_seguro(self, dinero):
   if not self.tiene_fraude:
      super().retirar(dinero)  # También servía self.retirar(dinero)
     # Luego había que marcar al cliente,  lo mejor era invocar al getter de saldo actual
     self.saldo_actual = self.saldo  # Saldo fue modificado por retirar()
     # Entonces si saldo era menor a 0, el cliente quedaría marcado como fraudulento
     if self.tiene_fraude:
          # Guardabamos la transacción en banco_seguro/clientes.py
```

El método deposito_seguro seguía la misma idea. Ojo que podrían haber variaciones en el método, pero lo que debían tener en mente era que: El método debía realizar la transacción usando el método del padre, hacer que self.tiene_fraude en algún momento fuera `True` **_cuando correspondiera _** y en caso de ser una transacción válida guardarla en un archivo. Pueden haber variaciones (que no usen al setter de `saldo_actual` y modifiquen el atributo de forma manual por ejemplo).


2. Se podía hacer de las dos formas, pero era más fácil escribir el método de a 0. ¿Por qué? Porque el método del padre agregaba a  `self.clientes` elementos de la clase `Cliente`, nosotros queriamos agregar en nuestra nueva clase a `ClienteSeguro`, por lo que una manera era implementar el mismo método, pero cambiando la línea donde se creaba una instancia de `Cliente`para que creara la de `ClienteSeguro`. Si se usaba el método del padre, entonces se debía iterar por clientes, obtener los atributos de cada instancia de `Clientes` y crear una nueva instancia de `ClienteSeguro`. Finalmente el elemento de la lista debía de ser reeemplazado por la nueva instancia que se había creado. 

3. Respecto a como funcionaría la actividad no existen diferencias, es decir, se podía completar la actividad directamente usando `desencriptar` en vez de la property. Ahora si existe una diferencia a nivel de modelación, ya que el uso de properties permiten encapsular elementos de manera más sencilla en una clase. A veces, se quiere usar los efectos que usa un método, pero no se quiere exponer al método para que sea usado en código, en este caso el efecto del método se podría obtener mediante una property, de este modo nos aseguramos que cierto métodos sean solo ejecutados dentro de la clase y nunca sean llamados desde afuera.

Respecto a eso último, puede existir la duda ¿Por qué no usar un atributo para lo mismo? La respuesta es por un concepto de la interfaz que expone la clase, en la actividad si hubiesemos usado una atributo como `self.texto` por ejemplo, este podría haber sido modificado perfectamente desde afuera de la clase y es algo que no siempre es deseable. De este modo, si usamos properties y solo creamos el `getter` del texto desencriptado, entonces no se podrá modificar desde afuera el atributo de la clase.

Espero haberte ayudado.

**Comment by oscars810** [comment]
Muchisimas gracias por responder todas mis dudas con tanto detalle. ❤️
