### ISSUE TITLE
Test 09 detectar plagas

### ISSUE THREAD

**Issue by MonitoXDD** [IIC2233/Syllabus#104]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

al realizar los test, en particular el retiro de cultivos dependiendo de las plagas. 
tengo 3 test distintos del mismo archivo que me envían un fallo, sin embargo, el fallo solo se debe a que no están en el mismo orden la lista que sale del método detectar_plagas con respecto a la respuesta esperada. 

En este tipo de casos si se hace una revisión similar automatizada por parte de quien corrige se consideran estos casos como falla? o se ve si la falla tiene sentido?

**Comment by Agusrush21** [comment]
Pero como? Entonces ordenaste o no la lista que te pide retornar el metodo?

**Comment by MonitoXDD** [comment]
si, pero en el caso de que dos plagas tengan el mismo valor de cultivos retirados, a veces intercambia los valores del esperado.

- [['A', 1], ['V', 3], ['K', 3]]
+ [['A', 1], ['K', 3], ['V', 3]]

**Comment by Agusrush21** [comment]
Porque primero lo ordenas por cantidad de menor a mayor y luego si son iguales los ordenas alfabéticamente
