### ISSUE TITLE
Actualización de chat

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#104]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### A efectos de esta tarea se considerará un "chat mail", el cual será one-sided solamente?

Es decir, se evaluará la funcionalidad chat solamente mediante 1 consola a la vez, escribiendo un mensaje y que este quede correctamente registrado en el archivo pertinente, o se debe hacer un programa tal que si A está chateando con B, la consola de A espere que el archivo de chats sea editado externamente por B (otra instancia del mismo programa en la consola utilizada por B).

Espero que se haya entendido mi pregunta! 😅

**Comment by IgnaciaJ** [comment]
Hola @fernandosmither! el chat efectivamente es one-sided, debido a que todavía no se ha visto la materia para realizar lo segundo que describes. Sin embargo, considera que luego de correr tu programa y hablar en un grupo, ese mensaje debe quedar guardado en el csv correspondiente. Éxito en tu tarea!

**Comment by fernandosmither** [comment]
Resuelto, gracias.
