### ISSUE TITLE
Actividades

### ISSUE THREAD

**Issue by 7lpozas** [IIC2233/Syllabus#104]
Como funciona la entrega de actividades después del plazo. Hay que enviar a corregir después de la nota, con el commit o se ve al final del curso.

**Comment by mblejeune** [comment]
Hola! segun yo entendí de lo que lei, subes el commit al issue que esta en tu repositorio para eso y te sirve para las recorrecciones al final del curso, no para recorregir una vez te dan la nota! (soy alumna del curso tb porsiaca asi q no estoy segura), pero eso fue al menos lo que yo cache! :)
