### ISSUE TITLE
Recursos en vía de ser producidos al guardar

### ISSUE THREAD

**Issue by Liks96** [IIC2233/syllabus#104]
Respecto al archivo acciones_pendientes.csv y el inciso 5 sobre interacción por consola.
En el caso de mandar a 3 trabajadores a recolectar oro, dado que 'los recursos aparecerán al turno siguiente', cómo se hace posible que se guarde este valor recolectado por estos 3 trabajadores si se decide en el mismo turno "guardar la partida"? 
Como aparece en el enunciado, las únicas acciones pendientes que se pueden guardar según el formato las únicas que quedan 'pendientes', es la creación de edificios y trabajadores, no mencionándose nada sobre el valor que recolectó el trabajador en el turno que se guardó.

**Comment by lily416** [comment]
Hola :)

Se habla de tu duda en está issue #55.

Saludos y éxito en la tarea 👋 🏰
