### ISSUE TITLE
función del número de bloque

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2233/syllabus#1040]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, 

tengo una duda respecto a los números de bloque en la codificación. **¿Estos deben ser utilizados al momento de recibir el mensaje?**, ya que el mensaje si o si se recibirá en orden, entonces no veo cual es su uso :/

Gracias

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by matiasmasjuan** [comment]
Hola @antoniaalcayaga !

**Sí**, estos números de bloques **deben** ser **enviados y recibidos en el mensaje**. Tal como indicas, dado que se utiliza un protocolo TCP , los mensajes siempre llegarán de forma **ordenada**, por lo que sería un poco redundate tener que recibir los bloques y luego reordenarlos según su número. Sin embargo, llevar a cabo este procedimiento es una buena práctica, ya que permitiría saber cómo interpretar dicho número o identificador (aunque es cierto que para este caso no serviría de mucho).

De todas formas, lo que se busca con esto es poder darles una estructura de mensajes y evaluar si es posible que ustedes puedan seguir esta misma especificación, por lo que es necesario que cumplan con la **misma** estructura del enunciado y enviar el **número del bloque** que corresponda,

Saludos y mucho éxito con la tarea! :smile:

**Comment by antoniaalcayaga** [comment]
me quedo clarísimo, muchas gracias!

**Comment by alejita97** [comment]
una cosilla referente a esta issue que no entiendo, es que si enviamos por "separado" el numero de bloque con respecto al pedacito de mensaje o si es un bloque de 64 bytes, cuyos primeros 4 bytes sería el numero de bloque, esta opción me hace más sentido ya que de esta forma se donde va el bloque.
Saludos y ojalá me lean :)

**Comment by matiasmasjuan** [comment]
Hola @alejita97 !

Para efectos de esta tarea, da igual si es que el número de bloque se envía exactamente en el mismo bloque con el de 60 *bytes* (formando un gran bloque de 64 *bytes*) o no. Lo **importante**, es que antes de enviar los 60 *bytes* se deban **anteponer** o enviar los 4 *bytes* del número del bloque. Por lo tanto, la opción que dices es correcta.

Saludos y mucho éxito con la tarea! :smile:

**Comment by cperez20** [comment]
Hola, respecto a esto mismo tengo una duda cuando se deben anteponer los primeros 4 bytes que corresponden al largo del mensaje, me explico: si tengo un mensaje de 180 bytes, luego de anteponer a cada bloque de 60 bytes, los 4 bytes necesarios que indiquen su numero, luego me quedaría un mensaje de 192 bytes, entonces cual seria el largo real del mensaje a enviar?

**Comment by matiasmasjuan** [comment]
Hola @cperez20 !

El largo **real** del mensaje a enviar **solo** considera el **mensaje mismo**, **sin incluir** los 4 *bytes* extras por cada bloque que se genera. Por ejemplo, si quieres enviar un *string* que diga *"Hola"* y supongamos que eso equivale a 60 *bytes*, entonces el **largo** del mensaje que enviarás en el **primer envío en formato *big endian*** serán **solo** 60 *bytes*, ya que ese es el mensaje. **No se incluye**  los 4 *bytes* extras de cada bloque.

En el ejemplo que mencionas, si el mensaje son 180 *bytes*, entonces el primer **envío** del largo, deben ser el número 180, pero codificado en 4 *bytes* y se envía. No incluye los 4 *bytes* extras de cada bloque, por lo que el largo a enviar **no son 192, sino 180**.

Espero haber respondido a tu pregunta, y mucho éxito con la tarea! :smile:

**Comment by Benja-c** [comment]
Hola no me queda claro si es que hay que mandar varios mensajes de 64 bytes o si hay que mandar un mensaje que este separado de la forma que explica el protocolo.
saludos

**Comment by matiasmasjuan** [comment]
Hola @Benja-c !

Tú pregunta se explica con la respuesta anterior:

> Hola @alejita97 !
> 
> Para efectos de esta tarea, da igual si es que el número de bloque se envía exactamente en el mismo bloque con el de 60 _bytes_ (formando un gran bloque de 64 _bytes_) o no. Lo **importante**, es que antes de enviar los 60 _bytes_ se deban **anteponer** o enviar los 4 _bytes_ del número del bloque. Por lo tanto, la opción que dices es correcta.
> 
> Saludos y mucho éxito con la tarea! smile

Por lo tanto, se debe **respetar el protocolo**:

1. Se envía el valor del **largo** del mensaje de *bytes*, en un tamaño de 4 *bytes* en *big endian*.
2. Por cada 60 *bytes* del mensaje (del mismo largo que el anterior), se deben **anteponer** o **enviar** (ambas son válidas) 4 *bytes* del número del bloque en formato *little endian*.
3. En caso de que el último bloque de 60 *bytes* del mensaje  no alcance los 60 *bytes*, se deberán anteponer ceros (b'\x00')

En respuesta a tu pregunta, y si entendí bien, no es llegar y mandar mensajes de 64 *bytes*. Se **debe seguir el protocolo**.

Espero haber respondido a tu pregunta, y mucho éxito con la tarea! :smile:

**Comment by MrShadowPotato** [comment]
Hola. Si tengo por ejemplo 180 bytes, despues de enviar los 4 bytes con la cantidad de bytes a enviar, ¿es necesario enviar 3 paquetes de 60 bytes (o 64, por lo mencionado arriba), ocaso puedo enviar un puro paquete de 180 bytes (considerando los 4 bytes cada 60 bytes del mensaje original)?.

**Comment by matiasmasjuan** [comment]
Hola @MrShadowPotato !

Da igual si quieres enviar todo en un **mismo** *bytearray* o si quieres hacer un **send** por cada 60 *bytes* del mensaje (64 si consideras el número de bloque). Lo **importante** es que se **respete** el **protocolo**. Por lo tanto, deberás siempre anteponer 4 *bytes* del número de bloque antes de enviar el *chink* de 60 *bytes* de cada mensaje.

Saludos!
