### ISSUE TITLE
Ubicación de sprites

### ISSUE THREAD

**Issue by vWing7** [IIC2233/syllabus#1040]
Ya que solo el servidor debe tener acceso a los sprites, ¿puedo ubicar la carpeta sprites sentro de la carpeta servidor?

**Comment by KnowYourselves** [comment]
Hola @vWing7!

Si, si puedes. De hecho eso es lo que haría más sentido desde un punto de vista de modelación.

Éxito!

**Comment by jirarrazaval** [comment]
@KnowYourselves  Hola! Pero por ejemplo para el logo, también necesito enviarlo desde el servidor hacia el cliente??

**Comment by KnowYourselves** [comment]
Hola @jirarrazabal!

(Disculpas por la demora!) Estrictamente hablando, por requerimiento del enunciado, los únicos sprites que si o si deben ser enviados desde el servidor al cliente son las cartas.
