### ISSUE TITLE
host y port en T03

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#1041]
Hola, no he practicado mucho con la materia de "Networking" y estoy un poco perdida con el tema del "host" y "port", leí los tipos que existen de cada uno, pero no sé si para esta tarea tengo que ocupar alguno de los que indicaron en los contenidos¿? o depende de mi computador¿?

**Comment by gatochico** [comment]
Hola!

Para el _host_, tienes que usar la dirección IP/hostname de la máquina en donde ejecutarás el código de la tarea (tu computadora y en el caso de la corrección, la computadora del ayudante). En el notebook 2 de la semana 14 hay algunos ejemplos de cómo obtener el hostname mediante la librería socket (En el apartado **Servidor TCP**).

Para el _port_, tenemos que elegir que puerto usará nuestro programa. Aquí puedes elegir un **número cualquiera (9000, 4000, 4030, 4031, etc...)**, siempre y cuando no esté siendo ocupado ya. En general como regla, se usa un **valor alto** para los ports como en los ejemplos que dí antes, ya que los valores bajos (80, 21, 22, etc..) usualmente están ya ocupados para funciones estándar de tu computador.

Espero se haya entendido!

**Comment by Camila-sty** [comment]
Sí, muchas gracias!

**Comment by drosselot** [comment]
Y como se le debe entregar el host al cliente? Como no se cual va ser el host del que corrige, no puedo entregarselo como parametro

**Comment by gatochico** [comment]
Puedes definir como parámetro de host 'localhost' tanto en el json del cliente como del servidor:

```
host: 'localhost'
```

Al usar localhost, automáticamente usa como host la máquina en que se ejecuta el código y funcionará en cualquier computador. Un poco más de info en localhost se puede leer [aquí](https://www.hostinger.com/tutorials/what-is-localhost)

**Comment by drosselot** [comment]
Entonces tengo que asumir que tanto el host como el cliente van a ejecutarse en el mismo computador? Porque osino como se conectaría el cliente al servidor?

**Comment by gatochico** [comment]
Si, puedes asumir que correremos ambos archivos en el mismo computador al mismo tiempo.
