### ISSUE TITLE
Dudas varias semana 14

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#1041]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Leí la issue #1023 y me quedan varias dudas de las semana 14 que no entiendo de los contenidos ni ayudantías. Tampoco me funcionan bien los códigos de la semana 14 ni de la ayudantía 11 y no sé porqué.

Sobre la materia, la verdad me he leído los contenidos de networking 3 veces y he visto la ayudantía 2 veces y entiendo en esencia lo que se hace y cómo funciona, pero no logro entender cómo se arma el código. Estoy muy muy perdida.

1. Semana 13: No entiendo bien la diferencia entre codificar, encriptar y serializar.
2. No entiendo cómo se conecta el servidor con el cliente.
3. ¿Dónde puedo encontrar los métodos de socket y sus explicaciones? Vi que usan recv, bind, listen y varios otros que no entiendo qué hacen, qué argumentos reciben y, si retornan algo, qué retornan.
4. En la ayudantía 11 en ```server.py``` en el método ```listen_client_thread``` no entiendo qué es ```largo_archvo``` ni qué hace. El ayudante explica que tiene que ver con los chunks, pero no usan el for que separa los chunks y no seeee no entiendo esa parte. 
5. Para conectar el cliente y el servidor al mismo port y host, ¿se puede inventar cualquier número para el port y cualquier nombre para el host? O sea, ¿en la ayudantía 11 ```3254``` es un valor aleatorio? ¿El host puede ser cualquier otra palabra o solo sirve ```localhost```? ¿Tienen que ser ```int``` y ```str```, respectivamente? 

Sobre los códigos que no me funcionan:
1. En la semana 14 donde dice "Hagamos el ejercicio completo en una sola celda. Supondremos que queremos que el servidor se cierre después de aceptar cinco clientes." copio y pego el código del cliente y del servidor en archivos distintos en la misma carpeta, corro el servidor en una terminal y me sale: 
![Windows PowerShell 22-11-2020 0_36_28](https://user-images.githubusercontent.com/68581172/99919995-8edc0a80-2cff-11eb-9c1a-d1efd0c88e65.png)

¿Por qué será? Incluso le cambié el nombre al host y al port y pasa lo mismo.

2. De la ayudantía 11 me funciona correr el servidor y agregar clientes, sin embargo, cuando escribo un mensaje y aprieto el botón de enviar, el mensaje no aparece en la pantalla de ningún cliente, pero sí se imprime en la terminal. ¿Por qué será?

**Comment by cruz** [comment]
Hola @kalarconvl 

> 1. Semana 13: No entiendo bien la diferencia entre codificar, encriptar y serializar.

Son conceptos similares aunque con diferencias. **Codificar** es el concepto más general porque corresponde a "convertir una valor de una representación a otra". Por ejemplo, de un objeto a Bytes, de un objeto a JSON, de JSON a un objeto, un numero a string, o un numero a un caracter particular (a una `A`, a una `é`, etc). 

Cuando estás encriptando algo, lo estás **codificando** de tal manera que parezca ilegible a un tercero que lo lea, o más bien haciendo el proceso inverso de **decodificación** (desencriptación) suficientemente difícil, aunque no imposible (de lo contrario nadie lo podría leer, ni siquiera el destinatario). Los algoritmos de encriptación se basan en valores secretos (o mezcla entre valores secretos y públicos) de manera que codificas algo para que solo la persona que conozca ese valor secreto lo pueda decodificar.

Serializar, por último, también es una manera de codificar algo. No le llamamos encriptación solo porque cualquier receptor de ese mensaje codificado, lo puedo decodificar fácilmente sin necesitar ninguna información adicional al mensaje mismo. A la codificación le llamamos serialización cuando el objetivo de codificarla es pasarla a una representación que sea independiente del computador/sistema operativo donde la vaya a decodificar (deserializar). Por ejemplo, si tiene una letra `A` que quieres enviar desde tu computador con Windows de 32-bit y lo quieres enviar a otro proceso por la red, talvez tu computador representa la `A` como la secuencia `0x00 0x41`, y el computador que la recibe, que es un Linux de 64-bit siempre lee los bytes al revés, como `0x41 0x00`. En ese caso si no se ponen de acuerdo en un "formato de serialización", por mucho que estén codificados, no se van a poder entender.


> 2. No entiendo cómo se conecta el servidor con el cliente.
> 3. ¿Dónde puedo encontrar los métodos de socket y sus explicaciones? Vi que usan recv, bind, listen y varios otros que no entiendo qué hacen, qué argumentos reciben y, si retornan algo, qué retornan.

La descripción precisa de la interfaz de sockets, sus métodos y atributos, puedes encontrarla en detalle: [aquí](https://docs.python.org/3.7/library/socket.html). Esto contiene más detalle de los que vemos en el curso, pero seguramente encontrarás ahí lo que necesites.

Por otro lado, [este video](https://youtu.be/CR7tgk1DUhU?t=669) que hicimos para el semestre 2-2019 también explica un ejemplo de conexión con sockets donde va mostrando los pasos a partir de un código.

> 4. En la ayudantía 11 en server.py en el método listen_client_thread no entiendo qué es largo_archvo ni qué hace. El ayudante explica que tiene que ver con los chunks, pero no usan el for que separa los chunks y no seeee no entiendo esa parte.

Aunque no he visto el ejemplo, `largo_archivo` corresponde a la cantidad de datos (bytes) que quieres enviar. Para que el receptor sepa cuántos bytes debe esperar, lo que hacemos (podría ser de otra manera), es enviar primero una cantidad fija de bytes (4 o 5) donde enviamos un número que diga cuantos bytes (largo del archivo) vienen a continuación. El receptor sabe que primero debe leer 4 o 5 bytes, extraer de ahí un número, y con ese número saber cuantos bytes vienen a continuación. Lo de leer por grupos (_chunks_) de bytes es parte del protocolo. Lo hacemos así porque en general al enviar mensaje por la red, hay una probabilidad de que algunos bytes no lleguen correctamente o se pierdan, y en ese caso hay que enviar los bytes de nuevo. Esta probabilidad aumenta mientras más largo es el mensaje. Si mandamos el mensajes en trozos (_chunks_) pequeños, es menos probable que hayan fallas, y de ocurrir, habrá que reenviar menos bytes.

> 5. Para conectar el cliente y el servidor al mismo port y host, ¿se puede inventar cualquier número para el port y cualquier nombre para el host? O sea, ¿en la ayudantía 11 3254 es un valor aleatorio? ¿El host puede ser cualquier otra palabra o solo sirve localhost? ¿Tienen que ser int y str, respectivamente?

El port de recepción en el servidor puede ser cualquier número. De preferencia mayor a 1024 (por un tema de permisos). El port que le indicamos al cliente es el número puerto del servidor, para que el cliente sepa a cuál de todos los programas que están corriendo en el destinatario, debemos hablarle. Ese `3254` es un valor elegido al azar. Puedes cambiarlo, pero debe ser consistente con el cambio en cliente y en servidor.

El host debe ser la IP o el nombre del computador al que te quieres conectar. Cuando le ponemos 0.0.0.0, o 127.0.0.1, o localhost, estamos usando nombres por defecto, disponibles en todos los computadores que se usan para "referirse al mismo computador". Es una manera de decir "quiero enviar un mensaje a un proceso que está en mi mismo computador". En un caso general, queremos enviar a un computador distinto, y en ese caso necesitamos conocer su nombre, o su dirección IP, pero si no tenemos computadores externos disponibles, entonces nos vamos "a la segura" y probamos ambos programas en el mismo computador.

> 1. En la semana 14 donde dice "Hagamos el ejercicio completo en una sola celda. Supondremos que queremos que el servidor se cierre después de aceptar cinco clientes." copio y pego el código del cliente y del servidor en archivos distintos en la misma carpeta, corro el servidor en una terminal y me sale: [IMAGE]

Sobre los códigos voy a contestarte en otro post. Los probé y deberían andar bien. Es raro que no te funcione el servidor (se está cayendo en la instrucción `bind`), no te deje usar el puerto a menos que tengas otro proceso corriendo ahí. ¿Qué puerto usaste? Si lo cambiaste a otro puerto también debió haber funcionado. ¿Es exactamente la misma celda? ¿No le cambiaste nada?
