### ISSUE TITLE
Duda cartas a robar+2 acumulados

### ISSUE THREAD

**Issue by anamarn** [IIC2233/syllabus#1042]
Hola tenia una duda al acumular +2 seguidos:
No me quedo claro si en el DCCuatro se replica la mecánica  del Uno al acumular varios +2 seguidos.
Por ejemplo si hay 3 +2 seguidos en el descarte, entonces la siguiente persona que no pueda responder deberá robar 6 cartas? o solo 2? 
Gracias

**Comment by rieg-ec** [comment]
Hola, tenia la misma duda y en el enunciado sale *El nu ́mero de cartas acumuladas es dos veces la cantidad de cartas +2 jugadas sucesivamente sin que ningu ́n jugador robe.*

**Comment by gatochico** [comment]
Efectivamente como dice @rieg-ec, los +2 se acumulan tal como en el juego Uno original!
