### ISSUE TITLE
Mi thread se termina aunque tenga un while True:

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#1042]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, tengo un ```thread``` que al iniciarse ejecuta una función. Dicha función contiene un 
while True: 
       pass
Sin embargo, el thread termina de todas maneras. Espero puedan ayudarme, gracias.

**Comment by Christian-Klempau** [comment]
Hola @En-clases!

En general, si un thread está utilizando un `while True: pass`, no debería terminar nunca, a menos que por una condición externa el programa se termine. Pueden estar ocurriendo distintas cosas:

1. El thread es _daemon_ y por otra condición de programa u error de tu código, el programa termina o se cae.
2. El thread efectivamente está corriendo, pero como no realiza ninguna función, aparenta estar detenido. Podrías colocarle algunos prints.
3. Por una condición externa estás deteniendo el código
4. No estás pasando el argumento de la función correctamente, o no estás iniciando el _thread_.

Como tip, puedes usar el método `is_alive()`, que retorna `True` si el thread está efectivamente corriendo o `False` si ya terminó. Acá imprimo en consola cada un segundo el método, y puedes notar que imprime `True` "infinitamente".
A continuación te muestro un ejemplo de un _Thread_ con tu misma lógica y puedes notar que efectivamente, nunca termina:
![thread](https://user-images.githubusercontent.com/62039719/100024512-b5fd0f80-2dc5-11eb-82dc-79aff2d415c5.png)

**Comment by En-clases** [comment]
Muchas gracias por la aclaración! En mi caso el problema fue el primer punto, tenía un daemon thread y mi programa se terminaba antes de tiempo.

**Comment by Christian-Klempau** [comment]
Genial, de nada! Suerte :D
