### ISSUE TITLE
Jugar Carta Cliente

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1043]
Se espera algún tipo de formato en el front - end del cliente para jugar una carta por ejemplo, si quiere jugar una carta debe dar cliclk en ella , o algo así, a lo que voy es que la forma en que se hace esto  queda a nuestro criterio?

**Comment by DCCollao** [comment]
Hola!

Mientras lo dejes en el `readme.md` y/o lo expliques en tu interfaz, está bien!

**Comment by RonaldoSosa** [comment]
Entendido!Gracias :)
