### ISSUE TITLE
Ports y estructura de mensajes

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2233/syllabus#1043]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Mi pregunta es si podría usar para el servidor más de un port para diferenciar la naturaleza de los mensajes. La otra opción que se me ocurre es en los mensaje anteponer un código que identifique el tipo de mensaje y la acción que se debe hacer, pero eso modificaría la estructura de mensajes especificada en el enunciado.

**Comment by DCCollao** [comment]
Hola @jorge-ovalle!

De las dos opciones que mencionas, no te recomiendo el crear más de un _socket_ para la tarea, pues fue pensada para ser resuelta utilizando solamente uno tal como fue enseñado en los contenidos.

Respecto a la segunda forma, anteponer un código identificador dependiendo del tipo del mensaje y la acción **no necesariamente** rompe la estructura de mensajes solicitada por enunciado. Por ejemplo, podrías enviar un diccionario con distintos datos contenidos en él, y programar diferentes respuestas de tu programa dependiendo de su contenido :eyes:

Mucho éxito con la tarea!
