### ISSUE TITLE
Problemas al correr código Mac

### ISSUE THREAD

**Issue by isidorabecker** [IIC2233/syllabus#1044]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema
Hola, tengo problemas al correr el codigo en mi computador, ya que cuando creo una nueva ventana con pyqt5 no se abre nada, no se que puede estar originando este problema.
Agradecería me pudieran contestar lo más rapido posible, ya que estoy avanzando en la T03.
[Describe tu problema de manera detallada, explicando qué estás intentando hacer y explicando los errores o problemas que has encontrado. Se recomienda agregar fotos cuando sea posible]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by franciscojpcc** [comment]
Hola, probablemente ya instalaste Big Sur en tu mac, al parecer trae muchas fallas el software y todos están teniendo este error. En la issue #1014 un compañero explica cómo resolverlo. Básicamente tienes que desinstalar la versión más actualizada de PyQt5 e instalar la versión 5.13. Espero que no traiga problemas para lo que tenemos que implementar. D:

**Comment by aaossa** [comment]
Hola @isidorabecker , justo lo que dice @franciscojpcc 👌 . ¿Te funcionó lo de la *issue* citada? Si lo solucionas así o de otra manera, avisa por acá plis para considerarlo si es que alguien más tiene problemas. ¡Gracias ✨!

**Comment by isidorabecker** [comment]
Hola @aaossa , no pude arreglar el problema con lo que ustedes me dijiero así que tuve que llevar a formatear mi computador para volver al sistema operativo anterior.
