### ISSUE TITLE
Generador_de_Mazos

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#1044]
Es necesario hacer uso de este? Implemente una función que lo haga por mi.

**Comment by DCCollao** [comment]
Hola @CataSudo!
Sí, es necesario que uses la función que les entregamos. De esta manera logramos estandarizar la forma en que todos generan sus mazos, permitiendo modificaciones rápidas para agilizar la corrección! 

Éxito :smile:

**Comment by CataSudo** [comment]
Se puede modificar la funcion?

**Comment by DCCollao** [comment]
No es la idea. La modificación de la función sería de parte nuestra al corregir las tareas. Si tuviésemos muchas funciones generadoras de mazos, ese sería el caso si empezaran a modificar las funciones.
Lo ideal es que todo comportamiento que desees agregar a la función, lo hagas mediante otras funciones.
