### ISSUE TITLE
modelamiento back y front y parámetros

### ISSUE THREAD

**Issue by camolina2** [IIC2233/syllabus#1045]
Hola! 
Tengo tres dudas
1. Estaba viendo del código de la actividad, me di cuenta que instancian la ventana principal en la clase clientes y conectan las señales de comunicación aquí. Supongo que en el caso de la tarea, todas las instancias deben hacerse en main.py dentro de la carpeta clientes, para tener separado el back con el front. Es esto correcto? o lo hicieron así por alguna otra razón?

2. Si hago la ventana de inicio con qtdesigner e inserto alguna imagen desde ahí, dado que la ventana de inicio está en la carpeta clientes, cumplo aún con el requisito de que los clientes no deben manejar imágenes?

3. Se especifica que se debe tener 2 archivos json con host y port, debo incorporar ambos parámetros de forma exacta, es decir, mi id del computador como host de forma numérica? o basta con utilizar el método .gethostname(). Además, el puerto es arbitrario ? 

Muchas gracias de antemano :)

**Comment by gatochico** [comment]
Hola! En orden:

1. Puedes conectar las señales tanto en el cliente como aparte en un main.py, no hay una única forma correcta! Puedes seguir a la AF06 que conecta en el cliente directo, o a la AY08 (de interfaces gráficas) que lo hace aparte en el main. Eso sí, esto último de conectarlas en main.py es útil para términos de orden, ya que si tú o el ayudante necesita saber a qué va conectada cada señal, solo necesita abrir este archivo y podrá ubicarlas todas, en vez de tener que buscarlas a lo largo de todo el código. Reitero, puedes usar ambas opciones de todas formas.

2. El protocolo de que el servidor debe enviar imágenes aplica solo para las cartas. Cualquier otra imagen extra (logo, algun sprite extra que quieras poner), puede ir de forma directa almacenado en la carpeta clientes y ser llamada desde ahí. 

3. Una forma más facil es simplemente usar  'localhost' como parámetro de host, y conectarse con ese hostname. Este automáticamente refiere a tu máquina local! (veáse la AY10 como ejemplo :see_no_evil: )

Saludos!
