### ISSUE TITLE
codificación de la información a enviar 

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2233/syllabus#1046]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, 

Tengo una duda respecto a los mensajes que enviare entre servidor y clientes. Entiendo que en caso de que quiera mandar mensajes en str tengo que codificar con utf-8, sin embargo no me queda claro si yo podría por ejemplo mandar mensajes en formato de diccionario y codificar con ,  como lo hicieron el la AF05 . Mi duda es si esto ultimo se puede o no,  y si no se puede cual es la otra opción para mandar mensajes en otro formato que no sea str?.

Graciaaas! :)

**Comment by matiasmasjuan** [comment]
Hola @antoniaalcayaga !

Si, puedes mandar cualquier tipo de información siempre y cuando se encuentre **correctamente serializada**, lo cual incluye diccionarios u otras estructuras. Esto se puede lograr mediante las dos formas de **serialización** vistas en el curso: **pickle** y **json**, de las cuales puedes encontrar mayor información el los [Contenidos del curso: semana 13](https://github.com/IIC2233/contenidos/tree/master/semana-13). Si quieres ver ejemplos **explícitos** de **envío de información** que **no** necesariamente son solo *strings*, puedes ver los ejemplos de [Contenidos del curso: semana 14-ejemplos](https://github.com/IIC2233/contenidos/blob/master/semana-14/3-ejemplos.ipynb).

Saludos y mucho éxito con la tarea! :smile:
