### ISSUE TITLE
responsabilidad de servidor y backend

### ISSUE THREAD

**Issue by rieg-ec** [IIC2233/syllabus#1046]
Hola, leyendo el enunciado me dio la sensación de que es un poco innecesario que el servidor revise si la jugada es valida.. o sea, si juego una carta de color distinto a la que hay en el pozo, no hay para que pedirle al servidor que le diga al cliente que la acción es invalida, puedo implementar eso en el backend y solo enviar la acción al servidor una vez que sea valida. Y ademas así el servidor no se encarga de procesar tantas cosas (que en este caso no hay problema, pero en la vida real se debe considerar buena practica hacer que el servidor no se encargue de cosas que no son estrictamente necesarias?) pero como esta explícito en el enunciado prefiero ante la duda preguntar si es valido implementarlo de la forma que propuse y así no llevarme alguna sorpresa XD

**Comment by KnowYourselves** [comment]
Hola @rieg-ec!

Lo que propones es lo que uno usualmente concluye naturalmente, pero es una decisión de diseño. Dependiendo de las arquitecturas y los sistemas hay programas que son muy "client side", es decir que el cliente hace gran parte del trabajo, más allá de solo mostrar cosas, y otros que son muy "server side", donde el cliente es "tonto" y todo se lo pregunta al servidor.

Dependiendo del proyecto a realizar, a veces es preferible una estructura más client side que server side o viceversa, pero para efecto de este proyecto, como el enfoque es la comunicación entre el cliente y el servidor, preferimos que realicen todo eso a nivel del servidor, así realizan la parte interesante, que es establecer un estandard de comunicación entre ambos programas.

En resumen, sigue el enunciado. 👀 

Espero mi aclaración haya sido suficiente, éxito en la tarea!
