### ISSUE TITLE
Forma de recibir mensajes entre cliente-servidor

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#1047]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, no entiendo muy bien cómo manejar los envíos entre servidor y cliente. En la semana 14 de contenidos, utilizan la siguiente función para recibir mensajes del servidor:
```def listen_thread(self):
        while True:
            response_bytes_length = self.socket_client.recv(4)
            response_length = int.from_bytes(
                response_bytes_length, byteorder='big')
            response = bytearray()
```
Para la tarea, he implementado algo parecido pero no me funciona bien. **Qué hago cuando el servidor no esta enviando mensajes?** Tanto en el ejemplo de la semana y en la actividad AF05 utilizan un ```while True``` para recibir mensajes. Es decir, estan recibiendo constantemente mensajes por parte del servidor. En mi caso, cuando el servidor no esta enviando mensajes, el método ```self.socket_client.recv(4)``` me entrega bytes vacíos y mi programa se rompe. Desde ya muchas gracias!

**Comment by EduardoIllanes** [comment]
Hola @En-clases , el código que pones es una especie de "protocolo" que nos indica el tamaño del mensaje enviado.  Respecto al `while True`, la función se encarga de escuchar los mensajes que envíe un cliente en particular (el cliente podría mandar un mensaje en cualquier momento!). Si el cliente no esta enviando mensajes por el momento, bastaría con poner una condición que revise que el `self.socket_client.recv` no sea vacío, es mas, si revisas un poco mas abajo en el ejemplo que mencionas es lo que hacen.  Espero que se entienda y mucho éxito con tu tarea 😄

**Comment by En-clases** [comment]
Muchas gracias por la aclaración! Se me pasó que para la clase de ```Servidor``` sí revisaron si el mensaje recibido era vacío o no. Sin embargo, para la clase ```Cliente``` no veo que lo hayan incorporado :c. Cómo manejaron ese caso para dicha clase?

**Comment by EduardoIllanes** [comment]
@En-clases Para el caso del `Cliente` puedes realizar algo similar, puede ejecutar un thread que se dedique a escuchar al servidor una vez conectado a este y dependiendo del mensaje que reciba del servidor poner ciertas condiciones para realizar la acción que necesites. Específicamente en el ejemplo que mencionas se encuentra en la función `listen` y `listen_thread` de la clase `Client,` podrás notar que en este ejemplo en especifico no se realiza nada especial con el mensaje que envía el servidor(dado que es solo un ejemplo de muestra). Siéntete libre de agregarle condiciones al `listen_thread` de tu cliente de acuerdo del tipo de mensaje recibido y a lo que necesites. Éxito en tu tarea 🚀

**Comment by En-clases** [comment]
Muchísimas gracias, te pasaste! 😄
