### ISSUE TITLE
Duda conectar/elegir nombre

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#1047]
Al leer el enunciado no me a quedado claro algo:

¿El cliente se conecta primero, y luego elige su nombre? o ¿elige su nombre después de conectarse?

**Comment by KnowYourselves** [comment]
Hola @felipehen!

Estrictamente hablando, para elegir el nombre (interfaz gráfica) el cliente no tendría por qué estar conectado al servidor de forma inmediata, pero como en el peor de los casos va a tener que enviar su nombre muchas veces al servidor, es razonable que lo primero que haga el cliente sea establecer una conexión.

Éxito!
