### ISSUE TITLE
Problemas mostrando la ventana de espera

### ISSUE THREAD

**Issue by sebaew98** [IIC2233/syllabus#1048]
hola, estoy tratando de abrir mostrar ventana de espera pero no me funciona bien. Estoy trabajando en un mac, abro el servidor en terminal y ejecuto los usuarios en visual code.
Al momento de tener un usuario valido me tira la siguiente advertencia 

QObject::killTimer: Timers cannot be stopped from another thread
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread

y solo se me abre la sala de espera en casos excepcionales si vuelvo a abrir terminal, con esto ultimo me refiero a que.
1- tengo el terminal funcionando con el servidor
2- ejecuto el main del usuario/cliente
3- se me abre la ventana de inicio 
y aca tengo 2 opciones
  4.1- Vuelvo a mostrar la ventana de terminal (solo mostrarla, por que estaba en otro plano)
     5.2- escribo un nombre de usuario valido y apreto entrar para mandar los datos al servidor  
       5.1- Funciona todo ok y me abre la ventana de espera
  4.2- No muestro la ventana de terminal
     5.2- escribo un nombre de usuario valido y apreto entrar para mandar los datos al servidor   
         6.2- no se me abre la ventana de espera y se queda en un blucle donde tengo que forzar cerrado de python.
No tiene ninguna logica para mi esto y se como solucionarlo.

**Comment by gatochico** [comment]
Hola! Todavía persiste el problema?

Cloné tu repositorio actual, y la verdad es que no pude replicar el error. Te recomiendo que corras **todo** (servidor y clientes) con la terminal (puedes abrir muchas terminales al mismo tiempo, no solo una!) en vez de usar el **run** de la interfaz de VSC. Así lo corrí yo y no hubo problemas (solo uno de los path relativos al llamar a los archivos .ui, pero lo arregle y corrió bien). 

Avísame como te va!

**Comment by sebaew98** [comment]
no me funciona, habro todo desde terminal y persiste, se queda en un bucle

**Comment by fdoflorenzano** [comment]
Hola @sebaew98,

Me apareció el error que indicas, y por lo vi en tu código, es en la sección que esconde y muestra ventanas. Esas instrucciones de interfaz gráfica se intentan llamar desde un *thread* que se ejecuta en el *back-end* paralelamente, y me parece ese es el error. Como recomendado en el material del curso, todo manejo de actualizaciones a nivel de interfaz gráfica es mejor hacerlo a través de señales y no llamando directamente a los métodos de interfaz desde el *back-end*.

Reemplacé los `hide` y `show` directos que hiciste por emisiones de señales conectadas a esos métodos, y el error deja de aparece y me ven los cambios de ventana. Inténtalo y nos cuentas como te va.

Saludos.

**Comment by fdoflorenzano** [comment]
Hola @sebaew98,

¿Cómo te fue con este problema?

Saludos.

**Comment by sebaew98** [comment]
solucionado!
