### ISSUE TITLE
Separación front-back

### ISSUE THREAD

**Issue by Zenos-Paradox** [IIC2233/syllabus#1048]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, 

Servidor y cliente deben tener frontend y backend? El servidor no interactúa directamente con el usuario, o es considerado fronend el recibir los mensages de los clientes?

**Comment by matiasmasjuan** [comment]
Hola @Zenos-Paradox !

Tal como dice el enunciado, en el caso del **servidor**:

![logs_servidor](https://user-images.githubusercontent.com/48495638/100095797-d36bc100-2e39-11eb-8869-7885e8860736.png)

Y para el caso de la **interfaz**:

![interfaz_cliente](https://user-images.githubusercontent.com/48495638/100095913-00b86f00-2e3a-11eb-88d4-9d1d9cc27054.png)

En base a esto, puedes concluir que el servidor **no** cuenta con **interfaz gráfica**, por lo que tiene **back-end** y **no tiene front-end**. En el caso del **cliente**, este **si posee interfaz** y se debe comunicar con el servidor, por lo que posee tanto **front-end** como **back-end**.

En relación directa a tu pregunta, el servidor sólo posee **back-end**, por lo que toda la interacción de recibir y procesar mensajes es considerada back-end.

Saludos y mucho éxito con la tarea! :smile:
