### ISSUE TITLE
Problema al enviar 60 bytes (con zfill haciendo nada), el servidor espera un numero gigante.

### ISSUE THREAD

**Issue by DasVaca** [IIC2233/syllabus#1049]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Cómo dice el título, si envio mensajes que no son multiplos de 60 (se llena con zfill) se envian perfectamente, sin embargo para mensajes de tamaño multiplos de 60 (donde el zfill no llena nada) el cliente envia la información correcta, pero el servidor interpreta los bytes como int gigante (> 2000).
EL código es el estándar (to_bytes, from_bytes, bajo los mismos parametros) y similar a lo que hemos hecho, como no tienen signo no creo que sea problema de sobreflujo, creo el zfill es lo único que podría hacer cosas raras pero no se me ocurré
¿qué puede ser?.

**Comment by DasVaca** [comment]
Pantalla del cliente
![imagen](https://user-images.githubusercontent.com/41296566/100114696-74fe0d00-2e50-11eb-8841-ad16f9091b4b.png)

Log del servidor
![imagen](https://user-images.githubusercontent.com/41296566/100114635-631c6a00-2e50-11eb-9de7-9230dcb0d88a.png)

**Comment by lucasprato** [comment]
Hola @DasVaca!

Sin ver el código, es complicado poder determinar la fuente del error. Ocupas json o pickle para serializar/deserializar lo que se envía entre el servidor y los clientes?

Mientras avances con la tarea, puede ser que prefieras enviar información que no necesariamente es un string, por ejemplo, un diccionario, una lista o una tupla. En este sentido, quizás utilizar zfill no es muy conveniente, porque zfill lo que hace es rellenar un string con una cierta cantidad de ceros. En cambio, te recomiendo rellenar con una bytearray de zeros (de la forma b'\x00\x00\x00...') al **mensaje una vez serializado** (no al mensaje mismo). En internet puedes encontrar cómo implementarlo. 

Espero que te sea de ayuda!

**Comment by DasVaca** [comment]
Ya buenisima, por ahora no estaba serializando, usaba el encode nomás para enviar el string y ver si todo funcionaba. 
Seguiré tu sugerencia, me parece una muy buena idea.
