### ISSUE TITLE
Pixmap

### ISSUE THREAD

**Issue by sebaew98** [IIC2233/syllabus#1049]
Hola, por alguna razon no se muestran los pixmap de ningun archivo.ui que ejecuto en mi codigo. Esta configurado en qt designer al igual que en la tarea pasada sin diferencias y no se muestran los pixmap.

**Comment by KnowYourselves** [comment]
Hola @sebaew98!

Estas seguro que los path de los QPixmap están bien?, Y que tienes la capreta con las imagenes presente en el directrio?

Cuentame que tal!

**Comment by sebaew98** [comment]
esta todo como viene descargado del syllabus en mi carpeta de tarea, abro directamente el pixmap desde qt designer y se ve todo bien, pero cuando se despliega la ventana del cliente se ven todos los labels creados en el widget pero no el label con el pixmap asignado

**Comment by KnowYourselves** [comment]
Es probable que QtDesigner de forma interna te este interpretando de forma distinta los paths a los archivos que como realmente se encuentran en tu sistema de archivos.

Si abres el archivo .ui puedes ver lo siguiente:

![image](https://user-images.githubusercontent.com/26102039/85312754-433de000-b485-11ea-8249-5a6a5eb39c3b.png)

Sin embargo por lo que veo en lo que tienes en tu repo, la carpeta se llama "mis_sprites". Tal vez eso sea el problema?

**Comment by sebaew98** [comment]
esa es otra carpeta para posibles sprites, pero no la estoy utilizando. Estoy cargando los pixmap directamente en qt designer al igual que en la tarea pasada pero no se muestran :c. Y en la tarea pasada tambien estaban en una carpeta en el path del codigo.

**Comment by KnowYourselves** [comment]
Y en el resto de los pixmaps sale exactamente el path que esperas que salga?

**Comment by sebaew98** [comment]
no se ve ningun pixmap

**Comment by sebaew98** [comment]
abri todo desde el terminal y me funciono.

**Comment by DCCollao** [comment]
No cierres la issue! A alguien más le podría servir la solución al problema. Nosotros la cerraremos cuando sea pertinente :smile:
