### ISSUE TITLE
Duda al import utils

### ISSUE THREAD

**Issue by mrebolledo03** [IIC2233/Syllabus#105]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

No me esta resultando importar utils, tengo python 3.11.7, por lo que se que el error no es eso. Pero al agregar "import utils" o "from utils.py import utils" me arroja este error "Import "utils" could not be resolved" creo que es como si no estudiera encontrando el archivo

**Comment by vgalfaro** [comment]
Hola! esta issue ya fue discutida en #71, como bien se dijo ahí, ese no es un error sino una advertencia de vscode, funciona una vez lo ejecutas en la terminal, saludos!
