### ISSUE TITLE
Interacción con la consola 

### ISSUE THREAD

**Issue by jitorcas** [IIC2233/syllabus#105]
Hola! tengo un par de preguntas:
1. En en el enunciado aparecen los archivos que deben ir en Data y Save, pero no especifican dónde debo guardar los archivos de la tarea (main, etc). ¿Debo crear una carpeta nueva con los archivos de mi tarea, o puedo incluirlos en Data? o ¿cada usuario que inicia una partida juega en su propia carpeta?
2. Pueden jugar más de tres civilizaciones en el juego, ¿ o exclusivamente son tres las que interactúan?
3. En el archivo "acciones.cvs" aparecen una lista de acciones que debe hacer una civilización en especifico ("x" ,"Y" y "Z") , si el usuario elige crear una partida jugando con la civilización "x" , automáticamente compite contra la civilización "Y" y "Z" ? o las civilizaciones "X" ,"Y" y "Z" van a jugar independiente de la civilización que elija el usuario? 
4. Es necesario crear una partida especifica donde solo jueguen las maquinas que realizan acciones dentro de "acciones.csv" ? o siempre habrá un usuario que juega? 

pd: Revisé todas las issues donde el titulo tenia relación con mis preguntas, pero no me quedo claro :c 
gracias! 💯

**Comment by gatochico** [comment]
Hola 🐱 

Antes que todo, si tienes dudas respecto a más de una parte de la tarea, trata de postearlas en issues distintas para hacerle más fácil a tus compañeros encontrarlas si tienen dudas similares! Con respecto a tus preguntas:

1.  Tus archivos .py de la tarea se suben a tu repositorio privado, en la parte __Tareas/T01__ . Con eso basta, no es necesario que vayan dentro de otra carpeta adicional.
2.  Juegan solo 3 civilizaciones en una partida.
3. Una vez el usuario elige su civilización, las 2 restantes son las que ocupa la computadora. 
4. Puedes asumir que siempre habrá un usuario jugando, no es necesario que hagas una partida donde solo participe la computadora.

Espero haberte ayudado!
