### ISSUE TITLE
< 100 caracteres por linea

### ISSUE THREAD

**Issue by GuilleStanke** [IIC2233/Syllabus#105]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Si escribo en una linea menos de 100 caracteres, pero el código de esa linea empieza después de varios espacios/tabs, y sumando la cantidad de espacios y de caracteres hay más de 100: Se está cumpliendo la regla de los 100 caracteres?

**Comment by Hernan4444** [comment]
Hola @GuilleStanke 

Los espacios antes de empezar el código tambien se consideran dentro de ese límite. Así que no se está cumpliendo la regla si la suma de todo es > a 100.

Saludos c:
