### ISSUE TITLE
Error 2da opcion menu tarea 1

### ISSUE THREAD

**Issue by tomasvasquezp** [IIC2233/Syllabus#105]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, probando el main.py, al seleccionar la 2da opcion me sale este error: AttributeError: 'list' object has no attribute 'ciclo_mas_corto', no sé como arreglarlo, si pueden ayudarme, estaria buenisimo.

Gracias!

**Comment by tomasvasquezp** [comment]
Ahora me sale lo siguiente: module 'red' has no attribute 'ciclo_mas_corto'

**Comment by tomasvasquezp** [comment]
Al final logre arreglar el problema, pero cada vez que se hace el llamado, me da el siguiente error: TypeError: unsupported operand type(s) for +=: 'int' and 'str'

**Comment by pedrozavalat** [comment]
Hola @tomasvasquezp !

Respecto a tu ultima pregunta, probablemente no estas transformando las conexiones de string a int. 
Te recomiendo ver la issue #78. 

Si todavia tienes el error, responde esta misma issue, ¡Exito en tu tarea! :)
