### ISSUE TITLE
Duda Ejercicio Propuesto 2.1

### ISSUE THREAD

**Issue by anais-mv** [IIC2233/Syllabus#105]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, estaba realizando el ejercicio 2.1 de esta semana en VSCode y los emojis me causan algunos problemas. A veces el mismo emoji se agrega 2 veces juntas en una lista, es decir, aparece de esta forma.

`lista = ["🍰🍰", "🍕🍕"]`

También me pasaba que a veces no se imprimía el nombre del cliente completo, por ejemplo para "Enzo" a veces imprimía "En" o "E".

Al principio pensé que era porque no estaba usando bien el lock así que traté de arreglarlo pero no pude, entonces cambié todos los emojis por strings con sus nombres, ahora en vez de "🍕" decía "pizza", por ejemplo. Después de hacer esto el código me corrió bien y no hubieron repeticiones porque hubieran 2 trabajadores haciendo el pedido a la vez (lo que significa que implementé bien el lock). Pero igual no entiendo porque cuando eran emojis se producían estos errores.

**Comment by tqmbanados** [comment]
Hola! Puede ser un poco tarde ya para contestar, pero intentémos resolver el problema igual 😸. 
Me resulta difícil cachar cual es el problema sin ver el código, si quieres puedes subir un pantallazo acá en los comentarios. Dado que es un ejercicio propuesto, no hay problema. Si con texto normal te funciona bien, lo más seguro es que sea por alguna propiedad extraña de los emoji... busque por ahí pero no encontré mucho. En todo caso, sube el código y veré si es algo fácil de descubrir ahí, o si requiere indagar más en cómo funciona el threading y los emoji.

**Comment by anais-mv** [comment]
Hola! perdón por contestar tan tarde. Este es mi código:
![image](https://user-images.githubusercontent.com/89219471/135006578-2b128300-884b-4096-befb-25a31b856146.png)
![image](https://user-images.githubusercontent.com/89219471/135006592-4c818f09-86de-48df-a597-9b16bc741ba6.png)

**Comment by fernandosmither** [comment]
Podrías pegar el código aquí con formato código? (Triple backtick antes y después `)
