### ISSUE TITLE
Problemas con borrar linea específica de un archivo

### ISSUE THREAD

**Issue by ivannia-puc** [IIC2233/syllabus#105]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Para borrar una línea específica del archivo grupos.csv hice un código donde el archivo se reescribe omitiendo las líneas que no cumplan 2 condiciones. El problema es que al usar el "if bla1 != bla2 and bla3 != bla4:" me considera que se cumpla una condición o la otra, es como si tomara el "and" como "or". Probe separándolo en 2 if tipo:
if bla1 != bla2:
   if bla3 != bla4:
Y continua sucediendo lo mismo.

Gracias por su atención.

**Comment by hsazos** [comment]
Hola @ivannia-puc !

Podrías subir un pantallazo de tu código y describir específicamente donde te da problema?
