### ISSUE TITLE
Sobre calculo de probabilidades

### ISSUE THREAD

**Issue by juacob** [IIC2233/Syllabus#105]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, cuando en el enunciado se nos dice por ejemplo, esta accion debera calcular la probabilidad de algo segun esta formula... Podemos hacer el calculo de la probabilidad afuera de este metodo y que este metodo retorne por ejemplo una parte de la ecuacion que se necesita y con un metodo de una clase completamente diferente terminar de hacer el calculo? 

Un ejemplo seria que quiero hacer que el metodo probabilidad de ganar de la clase juegos retorne solo la parte que no involucra probabilidad__ganar_jugador y sacar la probabilidad completa de ganar el juego en el metodo apostar de la clase Juego. Adjunto imagenes
<img width="342" alt="apuesta" src="https://user-images.githubusercontent.com/89426673/162545699-2d993aff-ae21-4c15-92e6-b0eefb824bc9.PNG">
<img width="317" alt="prob" src="https://user-images.githubusercontent.com/89426673/162545700-e7bf0b71-d970-4ca6-a5a6-22ae762ae678.PNG">

**Comment by catalina-arcila** [comment]
Hola, no sé si entendí bien tu pregunta. Tu quieres separar una formula en partes? si es así tienes que tener en cuenta dos cosas. La primera, es que debes considerar en no caer en las variables globales y meter una variable a un método en su argumento. El segundo punto importante es mantener los nombres de las variables descriptivas para que se entienda que parte de la fórmula es que. Como último, recuerda mencionar el formato de tu fórmula en el README para que no haya equivocaciones en tu correción.
Si se mantienen esas consideraciones no veo porque no se podría hacer lo que mencionas. 
Si entendí mal tu preguntas me avisas jeje.
