### ISSUE TITLE
Fechas de nacimiento exóticas y registro de usuario

### ISSUE THREAD

**Issue by mebruna** [IIC2233/Syllabus#105]
1. Si un usuario intenta registrarse con fecha de nacimiento 30/2/1990 se debería retornar un mensaje de error o registrarlo normalmente? Lo mismo para fechas más exóticas como 40/13/1997.

2. Un usuario puede registrarse directamente como Investor? O es necesario registrarse normalmente (como Trader por defecto(?)) y luego hacer el pago para cambiar a Investor?

**Comment by Arcoirisky** [comment]
Para la primera pregunta. Sí debería lanzar un mensaje de error para esas fechas más exóticas como tú dices xD Si la fecha no existe entoces que no se registre.

Para la segunda, es más normal registrarse como un usuario normal y luego pagar por el plus que entrar y ser directamente plus. Así que está bien que primero sea Trader (mientras se cumplan las restricciones) y luego investor :)

**Comment by mebruna** [comment]
Y para fechas no tan exóticas como 29/2/2012 hay que verificar que el año haya sido bisiesto y todo eso? D:

**Comment by Arcoirisky** [comment]
No es tan terrible como te lo imaginas. Vos dale 💪

**Comment by BibarelUsedFly** [comment]
@mebruna usar datetime resuelve todos esos problemas :D
