### ISSUE TITLE
T1 : Distribución puntajes en PEP8 y Modularización

### ISSUE THREAD

**Issue by Osiries1111** [IIC2233/Syllabus#105]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

No me quedó claro si es que por esta tarea1 el puntaje que sale en la tabla de "Distribución puntajes" no se considerará el puntaje del PEP8 y Modularización o si es que se dará como puntaje extra, por favor, si me pueden explicar mejor con respecto a esto, porque en las bases no sale bien detallado

![image](https://github.com/IIC2233/Syllabus/assets/130408574/4023d173-5cc8-4410-9087-a5549360e3dc)

**Comment by Dominique236** [comment]
Hola! 
Como se menciona en la imagen que mandaste, "a manera de excepción, para la primera tarea (T1) **serán parte del puntaje de evaluación**" por lo tanto es parte de lo que se evalúa y ayudara a tu nota que esto esté implementado (en semestres anteriores y en las siguientes tareas funcionaran como descuentos). Además, si revisas la distribución de puntaje, Modularización y PEP8 aparecen en la Parte 2 con puntaje asignado para cada uno.
Cuéntame si esto resuelve tu duda 😊
