### ISSUE TITLE
Duda sobre planetas en una batalla

### ISSUE THREAD

**Issue by nhbravo** [IIC2233/Syllabus#105]
Hola! Mi duda es si ambos planetas que entrarán a una batalla (invasor e invadido) deben ser parte de la misma galaxia.

**Comment by IchottMano** [comment]
@nhbravo Hola!
Tal como dice el enunciado en la sección 5.1:
>Cada galaxia es independiente a las otras; es decir, las acciones realizadas en una galaxia no tienen ninguna implicancia en las otras. Cada galaxia tiene sus propios planetas y reservas de recursos. En otras palabras, cada galaxia es una simulación distinta.

Espero esto resuelva tu duda.
Saludos!
