### ISSUE TITLE
Eficiencia de usar simulación

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#105]
Mi duda es que para poder calcular la expansión del radio tomando en cuenta los pronosticos y los recursos decidi usar un sistema de simulación con ticks de un segundo, el problema con este sistema es que el procesamiento se vuelve absurdamente largo. 

Es recomendable buscar otra forma de solucionar este problema o no importa la ineficiencia del procesamiento?

**Comment by chuma9615** [comment]
Al parecer se puede simular por minutos, eso lei yo en otra issue y asi corre mucho mas facil

**Comment by rpalmaotero** [comment]
@KnowYourselves Revisa #59.
