### ISSUE TITLE
Cerrar el servidor sin cerrar la terminal

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#1050]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! ¿Cómo puedo cerrar el servidor (hacer que deje de correr) sin tener que cerrar la terminal en la que lo corrí? Tengo windows y uso vsc, windows terminal o powershell

**Comment by aaossa** [comment]
Hola @kalarconvl , creo que la manera más fácil en estos casos es utilizar `Ctrl+C`, lo que debería terminar la ejecución del programa y dejar la consola lista para ejecutar el siguiente comando 🤓 No sé si ese es exactamente el efecto que buscas, ¿podrías probar y me dices si resuelve tu duda? ¡Éxito ✨!

**Comment by kalarconvl** [comment]
Holaa creo que no me funciona, ¿es algo que debo agregar al código para que funcione?

**Comment by aaossa** [comment]
Hola @kalarconvl para que te funcione deberías seleccionar la consola desde la que ejecutaste el comando (por ejemplo, `python3 servidor.py`) y luego presionar la combinación de teclas, no es algo que tenga que ver con Python 😅

**Comment by kalarconvl** [comment]
Pucha no me funciona entonces. Lo quiero usar cuando me sale un error para no tener que abrir una terminal nueva y tener que hacer todo el ```cd  \Documents\...``` de nuevo cada vez

**Comment by aaossa** [comment]
@kalarconvl mmm eso no debería ser necesario, ¿cómo estás ejecutando los archivos? La terminal no debería cerrarse (a no ser que tengas un *loop* infinito en alguna parte que "mate" la consola quizás 💀) 🤔

**Comment by kalarconvl** [comment]
Esque como recién estoy empezando el código y estoy probando los envíos de mensajes, cuando termina lo que llevo y como copié harto código de la actividad entonces tengo excepciones que aún no reviso, me pasa esto:

![Windows PowerShell 24-11-2020 22_38_43](https://user-images.githubusercontent.com/68581172/100171882-e3b98580-2ea5-11eb-9f7d-831db7cd41b5.png)

Y es por la pura lata de no querer cerrar todo y volver a abrirlo que quiero poder usar ctrl+c

**Comment by DCCollao** [comment]
Hola @kalarconvl! A mí a veces me pasa que tengo que apretar **muchas** veces `ctrl + c` para poder detener un servidor en python. Podrías probar así a ver si funciona 🙀

**Comment by kalarconvl** [comment]
A ver si funciona 🤔

**Comment by kalarconvl** [comment]
Nada ajajajaja

**Comment by aaossa** [comment]
@kalarconvl ¿podrías mostrarnos cómo queda la consola después de presionar `Ctrl+C`? Debería aparecerte un mensaje al menos 😕

**Comment by kalarconvl** [comment]
No sale nada! Queda exactamente igual

**Comment by aaossa** [comment]
Mmm y probaste usando cmd en lugar de Powershell?

**Comment by kalarconvl** [comment]
Nop, cómo se hace? Puedo hacer push, quizás es por cómo instancio el servidor

**Comment by aaossa** [comment]
@kalarconvl dale con el *push* mientras, por si es algo de eso. Para abrir cmd puedes buscarlo en el menú de inicio de Windows o también usar `Windows+R` y escribir `cmd` en la ventanita que se abre:

![imagen](https://user-images.githubusercontent.com/10425834/100172761-c4235c80-2ea7-11eb-986a-4e47e8dcf3ce.png)

**Comment by kalarconvl** [comment]
Tampoco me funciona en cmd

**Comment by DCCollao** [comment]
Buscando posibles causas para esto, encontré que puede ser por un problema con los _threads_ no _daemon_. Te dejo el [link](https://stackoverflow.com/questions/11815947/cannot-kill-python-script-with-ctrl-c/11816038) de donde lo leí!

Otro link interesante donde se trata este tema es [este](https://stackoverflow.com/questions/1364173/stopping-python-using-ctrlc#:~:text=On%20Windows%2C%20the%20only%20sure,labeled%20as%20%22Pause%22.\)&text=Pressing%20Ctrl%20%2B%20c%20while%20a,to%20raise%20a%20KeyboardInterrupt%20exception.) donde además se mencionan varias opciones dependiendo del sistema operativo.

**Comment by aaossa** [comment]
Algo más simple, @kalarconvl podrías probar ejecutando `aceptar_clientes()` desde el *thread* principal (cambiando la última línea de tu `__init__` de `accept_connections()` a `aceptar_clientes()`)? En este caso, una vez que apretas `Ctrl+C` tienes que agregar una nueva conexión (ejecutar de nuevo el cliente) y ahí se detiene la ejecución. ¿Podrías confirmarme si te funciona?

**Comment by kalarconvl** [comment]
@DCCollao cambié a daemon el thread que acepta conexiones y como que comenzó, imprimió "servidor escuchando en localhost..." y después murió solo jajaja además no recomendaban hacer que ese thread sea daemon ni idea por qué.
@aaossa Camibé la línea y sigue igual! Misma terminal y no funciona ctrl+c 😢 Quizás mi computador es mañoso nomas

**Comment by aaossa** [comment]
@kalarconvl pero hiciste:

0. Cambiar la línea
1. Ejecutar el servidor
2. Conectar un cliente
3. Ctrl+C en la consola del servidor
4. Conectar otro cliente

?

**Comment by kalarconvl** [comment]
Sip

**Comment by kalarconvl** [comment]
O sea, ahora se me cae cuando hago ctr+c y agrego otro cliente, pero después de tratar de conectar a este segundo cliente. 
1. Cambié la línea
2. Ejecuto el servidor
3. Conecto a un cliente
4. crt + c en servidor
5. Ejecuto otra terminal para conectar a otro cliente --> el servidor se cae

¿Así debe ser?

**Comment by aaossa** [comment]
Sip, a eso me refería. Estaba probando con el cliente que tienes en la carpeta cliente que se conectaba y desconectaba al tiro 🤔 Si bien no arregla tu problema del todo, al menos ahora puedes detenerlo 😅 Ojalá no sea tanto cacho. Por lo que vi, si no es lo que dejó @DCCollao , puede ser algo en Windows... de hecho pude reproducir tu problema y cuando lo ejecuté en otro SO se cancelaba inmediatamente 🤔 Creo que pillaste un *bug* 🐛 

Sobre tu captura: justo ese *output* es el esperado si cancelas directamente 👌 Parece que está funcionando el parche 🩹

**Comment by kalarconvl** [comment]
Buenisimo!! Muchas graciaas y sii mejor activar otro cliente que abrir otra terminal y escribir toda la ruta de nuevo, al menos por ahora 😄 Debe ser de Windows entonces. Y no me dará problema que sea el thread principal el que acepta los clientes?

**Comment by aaossa** [comment]
Si necesitas que tu servidor haga algo adicional desde el *thread* principal en lugar de solo escuchar clientes, tendrías complicaciones porque el *thread* principal estará ocupado. Pero en principio cualquier *thread* debería poder encargarse de aceptar conexiones, así que no debería haber problemas ✨ Quizás si necesitas algo así te sirva enviar a otro *thread* eso adicional y dejar al principal ejecutando este método. De todas formas, te recomendaría dejar citada esta *issue* en tu README para que les ayudantes estén al tanto de este problema cuando corrijan tu tarea 🤓 ¡Éxito con la tarea 💪!

**Comment by kalarconvl** [comment]
Dalee perfecto muchas gracias!
