### ISSUE TITLE
Ventana de inicio se cierra inmediatamente tras abrirse

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#1050]
hice mi código basándome en el entregado por ustedes en la AF06, haciendo que el cliente tenga como atributo la ventana a abrirle  y que esta se muestre después de conectarse con un show.

el problema existe, en que se abre, pero se cierra inmediatamente.

**Comment by benjavicente** [comment]
A mi me pasó algo similar!
Me faltó ejecutar la aplicación con `sys.exit(app.exec_())`.

**Comment by felipehen** [comment]
> 
> 
> A mi me pasó algo similar!
> Me faltó ejecutar la aplicación con `sys.exit(app.exec_())`.

Gracias!!! era eso
