### ISSUE TITLE
FileNotFound: No such file or directory

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#1051]
Hola. Cree dos carpetas dentro de la T03, que es **clientes** y **servidor**, en la **clientes** cree un módulo ```.py```para mostrar la ventana de inicio que fue creada en QtDesigner, y al correr la ventana en el terminal me sale el siguiente error;
 
![image](https://user-images.githubusercontent.com/59337116/85239451-e3522580-b401-11ea-9358-42d1ce9fc47c.png)

¿a qué se debe?, no lo he podido solucionar.
Gracias :D

**Comment by benjavicente** [comment]
Puede ser que el programa no se esté corriendo en el directorio que crees.
Prueba imprimir `os.getcwd()` para ver en cual directorio se está ejecutando. Tal vez necesites añadir un directorio al _path_ del `.ui`.
Espero que sirva :)

**Comment by Camila-sty** [comment]
@benjavicente pero si perteneciese a otro directorio, como debería escribir el path del “.ui”?

**Comment by benjavicente** [comment]
Tienes que unir el directorio al que pertenece con el nombre del archivo, quedando **algo como**  `cliente\directorio\ventanainicio.ui`.
Si es que el archivo `ventanainicio.ui` está un directorio más arriba puedes añadir `..` antes para _subir_ a un directorio.

**Comment by Camila-sty** [comment]
@benjavicente hola, intenté imprimir ```os.getcwd()``` pero no se imprime nunca, sale solo el error...

**Comment by benjavicente** [comment]
Ojo que `"\v" == '\x0b'` es una [_tab vertical_](https://docs.python.org/3/reference/lexical_analysis.html#literals) (tal como `"\n"` es una nueva linea). Como un _path_ no puede tener tener ese carácter, se muestra un error de que este _path_ es inválido.

Para imprimir `os.getcwd()` tienes que hacerlo antes del error.
Si estás cargando la clase como aparece en syllabus, es antes de `loadUiType`
```py
...
print(os.getcwd())  # <--

window_name, base_class = uic.loadUiType("ventanainicio.ui")  # Aquí debe estar el error

class MainWindow(window_name, base_class):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
```

**Comment by Camila-sty** [comment]
Ok.
Me tira este directorio:
![image](https://user-images.githubusercontent.com/59337116/85291830-019f3c00-b469-11ea-8b32-279bb37a8e2d.png)
Debería agregar el directorio "cliente" porque está dentro de T03. Pero aun no entiendo lo del "\n", cómo debería agregar el directorio "cliente" ?

**Comment by benjavicente** [comment]
El directorio de ejecución es incorrecto, ya que los programas se deben ejecutar en los directorios `cliente` o `servidor` y no en `T03`. Para cambiar el directorio donde se ejecuta puedes usar `cd cliente` o `cd servidor` respectivamente.

El problema del `"\n"` es que `"\"` no es un `\

**Comment by Camila-sty** [comment]
dónde debo poner ```cd cliente``` ?

**Comment by benjavicente** [comment]
En la consola, antes de ejecutar el archivo.

**Comment by Camila-sty** [comment]
Es que por ejemplo, abro un terminal del directorio **cliente** , pero también me tira error; 
![image](https://user-images.githubusercontent.com/59337116/85293161-f5b47980-b46a-11ea-8501-0ef22e5516ab.png)

**Comment by Camila-sty** [comment]
@benjavicente  no entiendo D:
sería ```cd cliente ventana_inicio.py``` ?

**Comment by benjavicente** [comment]
`cd cliente`, y luego `ventana_inicio.py`

**Comment by Camila-sty** [comment]
@benjavicente no entiendo. Dónde en la cmd? en el terminal de VSC? es que no suelo ejecutar código en la consola, entonces no te entiendo mucho, podrías ser mas específico porfa?

**Comment by Camila-sty** [comment]
Creo que ya se a lo que te refieres, y lo hice anteriormente;
> Es que por ejemplo, abro un terminal del directorio **cliente** , pero también me tira error;
> ![image](https://user-images.githubusercontent.com/59337116/85293161-f5b47980-b46a-11ea-8501-0ef22e5516ab.png)

qué estaría pasando ahora?

**Comment by benjavicente** [comment]
El directorio de ejecución no tiene el directorio `'ventana'`.
Asegurate que en el terminal esté el path antes de ejecutar `ventana_inicio.py`
`C:\Users\MGS\Documents\cami\Programacion avanzada\camila-sty-iic2233-2020-1\Tareas\T03\cliente>`
¿Cómo está organizado tu directorio del cliente?

**Comment by Camila-sty** [comment]
es que no debería tener ningún directorio ```ventana``` , tengo la carpeta T03, dentro de ésta cree una carpeta de **cliente** y otra de **servidor** , dentro de **cliente** cree el módulo ```ventana_inicio.py``` .

**Comment by Camila-sty** [comment]
esto es lo que tengo en **cliente** :
![image](https://user-images.githubusercontent.com/59337116/85298775-7e82e380-b472-11ea-831f-6382f9f5e13e.png)

**Comment by benjavicente** [comment]
Ya perfecto, entonces el path relativo a la carpeta cliente del archivo debería ser solo `ventanadeinicio.ui`, ya que no pertenece a un directorio dentro de la carpeta.

**Comment by Camila-sty** [comment]
cómo? no te entendí..? qué debo hacer?

**Comment by Camila-sty** [comment]
> Ya perfecto, entonces el path relativo respecto a la carpeta `cliente` debería ser solo `ventanadeinicio.ui`, ya que este **no pertenece a un directorio dentro de `cliente`.**
Se supone que `ventanadeinicio.ui` sí pertenece al directorio **cliente** :thinking:  lo veo dentro..

**Comment by benjavicente** [comment]
Me refiero a que no hay otro directorio dentro de `cliente` que contenga a `ventanadeinicio.ui`.
`os.getcwd()` debería retornar `C:\Users\MGS\Documents\cami\Programacion avanzada\camila-sty-iic2233-2020-1\Tareas\T03\cliente`, el path completo de `cliente`.
y el path relativo del archivo de designer respecto al directorio de `cliente` (lo anterior) es `ventanadeinicio.ui`.

**Comment by Camila-sty** [comment]
Si si, pero aún no entiendo qué hacer jajajaj, en verdad no entiendo. Qué tengo que hacer para solucionar el problema? qué hago con el path ```ventanadeinicio.ui``` ?, lo dejo tal cual?.
Ya mencioné que ```os.getcwd()``` no retorna lo que mencionas, pero filo, me metí al terminal del directorio cliente y me arroja el último error que te mandé. No entiendo por qué me explicas lo anterior si ya me lo mencionaste, o acaso de ahí tengo que evaluar el error? Porfa podrías ser mas específico ? Gracias por la paciencia en todo caso :D

**Comment by benjavicente** [comment]
Al final el problema es que se está ejecutando `ventana_inicio.py` en un directorio incorrecto, el path estaba correcto desde un principio, **tienes que dejarlo tal cual**.
Para ejecutarlo en la consola (estoy asumiendo que tienes Windows) debes primero cambiar donde se ejecuta el archivo.
Es decir, tienes que abrir la consola (en vscode es `ctrl`+`shift`+`c`) y en la consola debes hacer lo siguiente:
```txt
C:\Users\MGS\Documents\cami\Programacion avanzada\camila-sty-iic2233-2020-1\Tareas\T03>cd cliente

C:\Users\MGS\Documents\cami\Programacion avanzada\camila-sty-iic2233-2020-1\Tareas\T03\cliente>ventana_inicio.py
```

**Comment by Camila-sty** [comment]
> Al final el problema es que se está ejecutando `ventana_inicio.py` en un directorio incorrecto, el path estaba correcto desde un principio, **tienes que dejarlo tal cual**.
> Para ejecutarlo en la consola (estoy asumiendo que tienes Windows) debes primero cambiar donde se ejecuta el archivo.
> Es decir, tienes que abrir la consola (en vscode es `ctrl`+`shift`+`c`) y en la consola debes hacer lo siguiente:
> 
> ```
> C:\Users\MGS\Documents\cami\Programacion avanzada\camila-sty-iic2233-2020-1\Tareas\T03>cd cliente
> 
> C:\Users\MGS\Documents\cami\Programacion avanzada\camila-sty-iic2233-2020-1\Tareas\T03\cliente>ventana_inicio.py
> ```

Sí, ya lo hice. Y me sale el error que te mencioné arriba, es distinto al de un principio, y al que te referías que no encuentra el directorio ```ventana```, pero no tengo ese directorio, entonces no sé que más hacer.... ¿? 
Mira:
![image](https://user-images.githubusercontent.com/59337116/85303461-847bc300-b478-11ea-8ebc-583f3fb63e0e.png)

**Comment by benjavicente** [comment]
Hmm está raro ese error, debe estár en la linea 5.
¿Te funciona con otro archivo `.ui`?

**Comment by Camila-sty** [comment]
@benjavicente con ninguno, cree dos ventanas y las dos me lanza el mismo error, solo que en la otra en vez de salir ```ventana``` sale ```sala```.
Podría hacer un push de esto, si quieres verlo, no sabría como arreglarlo xd

**Comment by benjavicente** [comment]
No soy ayudante xd
Prueba buscando en todo el directorio `ventana` y `sala` (con la lupa a la izquierda o `ctrl`+`shift`+`f`). En alguna parte deben estar causando el error.

**Comment by Camila-sty** [comment]
@benjavicente  debiste haberlo mencionado de un principio jajajajaja 
Gracias por la ayuda y la paciencia!.
Si algún ayudante mira esta issue ojalá pueda ayudarme D:, estoy hace rato con esto, y necesito que funcione para avanzar y probar el funcionamiento...
