### ISSUE TITLE
Codificación para la tarea

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2233/syllabus#1051]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!
Para la tarea entiendo que debemos usar una codificación UTF-8, mi duda es si podemos utilizar json para esto (ya que creo que este codifica en UTF-8) o si debemos codificar utilizando .encode("UTF-8")
Muchas gracias ☺️

**Comment by EduardoIllanes** [comment]
Hola @Sofia-Arratia esta pregunta ya fue respondida en la issue #1046 . De todas formas te contesto aquí, si puedes serializar tanto en **pickle** como en **json**. Saludos y éxito con tu tarea 🙌

**Comment by Sofia-Arratia** [comment]
Muchas gracias!
