### ISSUE TITLE
Restricciones al nombre de usuario

### ISSUE THREAD

**Issue by CatalinaFloresP** [IIC2233/syllabus#1052]
Tengo que asegurarme que el nombre de usuario ingresado no corresponda con ninguno de los otros nombres de usuarios en la partida pero, ¿Es necesario tener un registro de todos los nombres que se hayan ingresado en algún momento y que el nombre ingresado no coincida con ninguno de ellos incluso si no está en la partida?

**Comment by KnowYourselves** [comment]
Hola @CatalinaFloresP!

Tienes que tener en el servidor, de una u otra forma, un registro de todos los **clientes actualmente conectados**. En el momento que cierren el cliente, su nombre pasará a estar disponible.

Éxito!
