### ISSUE TITLE
Problema con mostrar ventanas 

### ISSUE THREAD

**Issue by bastian-perez** [IIC2233/syllabus#1052]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ]X Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### 
Ya tengo programado el envío de mensajes y el modo en que se muestra la ventana de sala de espera y su actualización, pero por cosas que no entiendo, pues no se muestra ningún error. La ventana no se muestra, se abre una ventana pero vacía y sin nada adentro, solo un fondo negro. Y el programa continua con normalidad y no se muestra ningún error ni estancamiento en algún lado no planeado. Esta ventana la tengo hecha con designer y el modo de importación y creación de la clase ventana también está correcto. Ayuda porfavor :(

**Comment by Mjtala** [comment]
@bastian-perez podrías subir a tu repo lo que llevas del código ya que así es más fácil probarlo?

**Comment by bastian-perez** [comment]
@Mjtala Recién subido! muchas gracias!
