### ISSUE TITLE
Llegada de mensajes vacíos al cliente que no son enviados por el servidor

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2233/syllabus#1053]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, 
me esta pasando, al implementar el protocolo, que llegan mensajes al cliente vacíos , que no son enviados por el servidor y no se si es normal (si es asi son faciles de ignorar), pero siento que debe ser un error en mi código. ¿quería saber si es un error común o si me podrían dar una orientación de lo que podría llegar a ser? por que tengo casi lo mismo que en la AF05, entonces no entiendo que pasa.

Gracias!

**Comment by lucasprato** [comment]
Hola @antoniaalcayaga,
Efectivamente es raro lo que está ocurriendo. Lo esperable es que el cliente solamente procese mensajes enviados a propósito desde el servidor. Asimismo, el cliente siempre debe estar "escuchando" al servidor, pero si éste no envía nada, entonces el cliente no escucha nada.

Te aconsejo que mires más ejemplos de implementaciones de Networking y detectar posibles falencias de tu tarea. Puedes ver los contenidos e incluso los repos de semestres pasados.

Éxito en tu tarea!
