### ISSUE TITLE
Log de que persona se conectó

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#1054]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Es necesario imprimir un log de que una persona se conectó además del mensaje de que ingresó a la sala de espera? Porque si alguien entra y la sala de espera está incompleta, va a conectarse e ingresar directo a la sala de espera, sin embargo, si ya empezó el juego y una persona trata de conectarse, no podrá hacerlo. Al final, conectarse es lo mismo que entrar a la sala de espera o es necesario hacer 2 logs distintos? En la misma línea, si es que conectarse no es lo mismo que entrar a la sala de espera, hay que imprimir el log cuando alguien trata de conectarse y el juego ya comenzó?

**Comment by matiasmasjuan** [comment]
Hola @kalarconvl !

De acuerdo a lo que indica el **enunciado**, en la el **servido** debe imprimir los logs cuando:

![log_conectarse](https://user-images.githubusercontent.com/48495638/100159680-f5dafa00-2e8c-11eb-88d0-838780dec59f.png)
En base a lo anterior, puedes concluir que **conectarse** no es lo mismo que **entrar a la sala de espera** y se deben imprimir **dos logs distintos**. Por lo tanto, apenas un cliente se ejecute (en su respectivo main) debe conectarse con el servidor. Sin embargo, esto **no implica** que haya ingresado a la **sala de espera**. Si se logra conectar un cliente, se debe imprimir el log de **conexión**. Si además la sala no está llena y el cliente puede entrar, entonces se debe **imprimir otro log** indicando que el cliente **logró** ingresar a la sala de espera. Por el contrario, si el servidor encuentra que la sala ya está llena, entonces se debería **imprimir un log** indicando que el cliente intentó ingresar a la sala, pero que el ingreso fue fallido debido a que la sala ya estaba llena o en juego.

Espero haber respondido a tu pregunta, y mucho éxito con la tarea! :smile:

**Comment by kalarconvl** [comment]
@matiasmasjuan Graciaas perfectoo! Eso sí, me queda una pregunta: cuando pongo listen le digo al servidor la máxima cantidad de personas que puede aceptar. ¿Cómo puedo ver que una persona se conectó sin aceptarla para poder verificar ahí si puede ingresar a la sala de espera? O mejor o le pongo un número al listen nomas?

**Comment by matiasmasjuan** [comment]
Quizas te estás complicando de más :thinking: . ```socket.listen(n)``` genera un *backlog* de conexiones esperando a ser aceptadas. Para efectos prácticos no pedimos esto, ya que la idea es que el cliente se conecte de forma **inmediata**. Recuerda que **muchos** clientes se pueden **conectar** con el **servidor**, pero sólo un **número máximo** (que debe estar en los parámetros) es capaz de **ingresar** correctamente a la sala de espera. Quizás te convendría almacenar de alguna forma los clientes que ya están en la **sala de espera**, y en caso de que un cliente se conecte, el servidor vea si se superó ese límite o no :eyes: 

Saludos! :smile:

**Comment by kalarconvl** [comment]
Entonces a ```socket.listen(n)``` no le pongo un ```n```? Cosa de que todos se puedan conectar, imprimiendo el log correspondiente, y si pueden entrar a la sala de espera (una lista o algo que me permita guardar los jugadores en lista de espera) según el parámetro del número máximo, se imprime el log correspondiente?

**Comment by matiasmasjuan** [comment]
Esa es la idea. :eyes: 

Saludos y mucho éxito con la tarea!

**Comment by kalarconvl** [comment]
Muchaas gracias!

**Comment by kalarconvl** [comment]
Me surgió otra duda de lo mismo! Cuando una persona no se puede conectar porque el juego ya está en curso, no hay que crear un thread para escucharla cierto?

**Comment by matiasmasjuan** [comment]
Según lo indicado en el enunciado:

**Para la Sala de Espera**

![sala_llena](https://user-images.githubusercontent.com/48495638/100173027-680d0800-2ea8-11eb-9099-1cbc0425efef.png)

Por lo tanto, si un cliente se intenta conectar pero la sala ya está llena o el juego está en curso, simplemente se le debe avisar y se debe desconectar.

Saludos!

**Comment by kalarconvl** [comment]
gracias!
