### ISSUE TITLE
Ventana inicial

### ISSUE THREAD

**Issue by dchahuan** [IIC2233/syllabus#1054]
Cuando uno se el cliente no se puede conectar al juego hay que avisarle la razon o podemos poner que hubo un error?

**Comment by KnowYourselves** [comment]
Hola @dchahuan!

Ambas opciones son válidas, pero en general es buena modelación avisar siempre la razón.

Éxito!

**Comment by dchahuan** [comment]
yaya gracias

**Comment by KnowYourselves** [comment]
Recuerda no cerrar las issues!
