### ISSUE TITLE
Materiales infinitos

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#1055]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

¿Cómo funciona exactamente el banco? ¿Hay infinitas cartas de cada tipo o tenemos que crear el *mazo* con el que se maneja el banco? Esto puede afectar si se acaba algun tipo de recurso o al sacar cartas de desarrollo.

**Comment by matiasmasjuan** [comment]
Hola @YehudaGurovich !

El banco posee **infinitas cartas**. Por lo tanto, **no habrá problemas** en caso de que se acabe un recurso, ya que **nunca** se **acabará**. (lo que tristemente si ocurre en el juego original :cry:

Saludos y mucho éxito con la tarea! :smile:

**Comment by YehudaGurovich** [comment]
@matiasmasjuan Ok! Gracias!

**Comment by YehudaGurovich** [comment]
@matiasmasjuan Me imagino entonces que podemos asumir que las carreteras y chozas también son infinitos.

**Comment by matiasmasjuan** [comment]
**Efectivamente**, dado que en el enunciado no se habla de recursos o construcciones **máximas**, puedes asumir que son **infinitos**.

Saludos! :smile:

**Comment by dedmu5** [comment]
> **Efectivamente**, dado que en el enunciado no se habla de recursos o construcciones **máximas**, puedes asumir que son **infinitos**.
> 
> Saludos! 😄

¿Puedo asumir que todos los recursos tangibles (carreteras, chozas, ciudades, recursos), tienen un máximo de 99 unidades? Por limitaciones de la interfaz gráfica me sería difícil colocar un número muy grande (además, no se vería y es poco probable que un jugador llegue a esa cantidad de recursos)

**Comment by matiasmasjuan** [comment]
Hola @dedmu5 !

Si se te hace más fácil en términos de interfaz, si, puedes tener un valor **máximo de 99**. Además, este número no está especificado en el enunciado y como bien dices, es muy poco probable que se llegue a esa cantidad de recursos (sobretodo si sale el número 7)

Saludos! :smile:

**Comment by riadeane** [comment]
> El banco posee **infinitas cartas**. Por lo tanto, **no habrá problemas** en caso de que se acabe un recurso, ya que **nunca** se **acabará**. (lo que tristemente si ocurre en el juego original 😢

Hola @matiasmasjuan!

Esto incluye las cartas de desarrollo? En tal caso uso la función `sacar_cartas` para cuando los jugadores compran una carta de desarrollo?

**Comment by matiasmasjuan** [comment]
Hola @riadeane !

**Si**, **también** incluye para las cartas de **desarrollo**. En ese caso, tal como mencionas, tendrías que llamar a la función ```sacar_cartas```.

Saludos! :smile:

**Comment by riadeane** [comment]
Gracias :D
