### ISSUE TITLE
Error al conectar 4 clientes al servidor: BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#1055]
Al conectcar 4 clientes mi servidor debe correr la siguiente funcion:

    self.socket_server.sendall(b'Empieza la ronda').encode('utf8')

pero me da el error en el titulo. Por que me da este error?

**Comment by gatochico** [comment]
Hola! 
`
BrokenPipeError ` ocurre en el sendall ya que tu servidor quiere enviar un mensaje, pero la conexión por el lado del cliente ya se cerró y por ende, le está enviando datos a algo que ya no existe o está 'roto' (que sería esa conexión que se ha cerrado).

Revisé tu código por encima, y veo un detalle por el lado del servidor: fijate que no estás haciendo un thread para escuchar a **cada** cliente que se conecta. Te recomiendo vayas viendo la ayudantía 10 de networking donde están muy bien separados los pasos de la conexión. Si te fijas, allí cada vez que el servidor recibe un cliente hace un proceso donde le construye un thread y lo corre para escucharlo. Podrías ver si por ahí está el error. Trata de ver al mismo tiempo tu código del server y el de la ayudantía: ¿Qué cosas tienen igual? ¿Qué difieren? En las cosas que difieren, alguna era necesaria (como los threads que dije)? 

Avísanos cualquier cosa!

**Comment by sofiuni** [comment]
Pero si se crea un Thread? mire el codigo pero no se donde *no* se crea un hilo, esta 

 thread = t.Thread(target=self.listen_thread, daemon=True)

**Comment by gatochico** [comment]
En `servidor.py`, fijate en el flujo que sigue tu programa al aceptar un cliente (en funcion_target) vs. el de la ayudantía (accept_connections_thread). En el segundo se crea un thread único para cada cliente recibido! Podrías ver si al implementar eso se soluciona el BrokenPipe

**Comment by sofiuni** [comment]
Hice todo eso pero me da error igual? el mismo error, ademas. Que pasa?

**Comment by gatochico** [comment]
Hola! (disculpa la demora) Encontré el error:

En tu server, cuando llamas a la función `sendall`, se está haciendo de forma incorrecta. Actualmente está así:
`self.socket_server.sendall(b'Empieza la ronda').encode('utf8')`

Por lo que se está aplicando sendall al socket del server. Sin embargo, se debería aplicar sendall a **el socket en específico de cada cliente al que quieres mandar info**, y no al del server. Viendo tu código, ahora almacenas los sockets de cada cliente en un diccionario cada vez que recibes una nueva conexión, donde el socket de cada cliente es la llave de cada par llave-valor. Por lo tanto, si quieres mandar a todos los clientes un mensaje, deberías hacer una iteración del tipo:
```
for cliente in self.diccionario_clientes.keys():
    cliente.sendall(mensaje_a_mandar) # ojo que no añadí el encode('utf8') aquí, ya que no es necesario
```

De esa forma tomas cada socket de clientes uno por uno y le envias la info!

Ahora arreglado esto, del lado del cliente puede que veas que no se recibió nada. Esto ya es otro tema, y tiene que ver con como estás manejando el decode del lado del cliente 🙈 Te recomiendo en el método de tu cliente donde se decodifican los bytes para rearmar el mensaje, hagas print después de cada linea de código para que veas qué va retornando cada parte de tu código en esa sección y puedas ver que está pasando en esa función.

Avísanos como te va!
