### ISSUE TITLE
problema ejecucion networking

### ISSUE THREAD

**Issue by mmunoz12** [IIC2233/syllabus#1056]
Hola! me pasa que al ejecutar codigos que usen networking, los outputs (print) generados en cada codigo no me aparecen en la consola a medida que yo conecto clientes o realizo alguna otra acción, sino que solo se imprimen (todos juntos) una vez que cierro el programa completo. Por lo tanto toda la información que entrega mi codigo sobre el servidor o los clientes no se ve de forma actualizada. A qué se puede deber esto? ojala se entienda.

**Comment by gatochico** [comment]
Hola! Podrías subir tu avance a tu repositorio para ver el problema?

**Comment by mmunoz12** [comment]
Mm es que aun no tengo el avance😅 pero me pasa con la AF06 y los ejemplos dados en la ayudantia, entonces creo que debe ser un problema de mi computador. Todo funciona correctamente pero para la tarea me va a complicar ya que no podre ir revisando en el momento si es que se conectan bien los clientes, por ejemplo. Igual te avisare cuando tenga el avance más hecho porsiacaso.

**Comment by gatochico** [comment]
Al final lograste solucionar tu problema? 😢Sino para leer tu código y ayudarte.

**Comment by mmunoz12** [comment]
hola! mmm al final empecé a ejecutar mi codigo en el vs code y ahí los prints van apareciendo a medida que el programa se ejecuta asi que ya no hay problema para revisarlo al menos. No supe solucionar el problema de la consola del computador pero supongo que es así nomas jaja. Pero muchas gracias igual!!<3

**Comment by gatochico** [comment]
Que bueno que pudiste ver los prints en vscode! En general igual deberían salir en la consola del computador si es que corres los programas por ahí (con `python main.py` o `python3 main.py` dependiendo de tu OS), que raro 🤔, pero si puedes de momento trabajar bien con tu código eso se puede ver después de terminada la tarea.
