### ISSUE TITLE
Problema con Daemon en listen de cliente

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2233/syllabus#1056]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)

### Duda

Hola! Al correr el codigo , logro que se me conecte el cliente al servidor, pero cuando el servidor luego le trata de mandar el nombre devuelta al cliente, se me cae el programa y me muetra un 'error fatal' el cual supuestamente se relaciona con el Daemon (esa parte del codigo fue inspirada en el de la AF05)
![Screen Shot 2020-11-24 at 8 32 15 PM](https://user-images.githubusercontent.com/69609564/100163302-25413500-2e94-11eb-951b-aa6c1c290ea5.png)

**Comment by tomasgv** [comment]
¡Hola @conyfernandezt!

Parece ser un error muy particular 🧐 . Por lo que [investigué](https://prodevsblog.com/questions/141797/fatal-python-error-and-bufferedwriter/), puede ocurrir cuando un *thread* intenta acceder a recursos luego de que el *thread* principal ya haya terminado.

En un caso que puede ser más cercano al tuyo, logré reproducir ese error para un servidor. Ocurrió cuando terminó el *thread*  principal mientras que existían *threads* de escucha de clientes esperando un mensaje con `recv`. 

Ambos casos tienen en común que termina el *thread* principal en un momento no deseado, por lo que revisaría eso en tu código. Para el servidor de la AF05, el *thread* principal se mantuvo corriendo con un `while True` en `main.py`, y el cliente con las ventanas mismas ya mantiene corriendo su *thread* principal.

Espero que esta respuesta haya sido de ayuda! Si después de esto no logras encontrar el error que está ocurriendo, haz `push` de tus cambios y avísame para echarles una mirada :eyes:

**Comment by conyfernandezt** [comment]
Hola Tomas! Tengo implementado el while True en el main y actualmente tengo el Daemon del cliente comentado porque osino me pasa lo que comente arriba. Pero ahora aparte de eso cuando corro el programa, me tira '[Errno 9] Bad file descriptor' en el cliente cuando trato de obtener el largo del mensaje cuando es recibido. Si me pudieras ayudar lo agredeceria mucho, ya que no entiendo lo que esta pasando

**Comment by tomasgv** [comment]
¡Hola @conyfernandezt!

Parece que tu problema ya fue respondido en la issue #1063! Si aún hay problemas, comenta por allá lo sucedido :eyes:

Respecto al problema que tuviste con hacer al *thread* *daemon*, si pones un `while True` en el `main` del cliente, de modo que el *thread* principal no termine, se solucionará el problema. Esto puede solo ser temporal, ya que cuando exista una interfaz gráfica el *thread* principal no terminará hasta que cierres la ventana 🎉

¡Saludos y mucho éxito con la tarea! 🧱
