### ISSUE TITLE
parametros.json

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#1057]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

¿Las *Keys* del parametros.json tienen que estar en mayúscula? Dado que está reemplazando el parametros.py y en el enunciado aparecen así uno pensaría eso pero en el ejemplo del enunciado muestran las *Keys* en minúsculas por lo que no me queda claro.

**Comment by lucasprato** [comment]
Hola @YehudaGurovich!

Cualquiera de las opciones es válida mientras seas consistente a lo largo de todo el programa. Ahora bien, como equipo de ayudantes te recomendamos que mantengas los keys con mayúsculas, tal como se ha pedido para los parámetros en las tareas anteriores. 

Éxito en la tarea!

**Comment by YehudaGurovich** [comment]
@lucasprato Ok. Gracias!
