### ISSUE TITLE
 int.from bytes e int.to bytes

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#1057]
Hola, me podrían explicar que hace  ```int.from bytes``` e ```int.to bytes```, sé que el ```int``` lo transforma a número entero, pero qué significa el ```from``` y el ```to```?

**Comment by szabala** [comment]
Hola! 
int.from_bytes(**bytes**): retorna un numero int representado por los **bytes** que le pases.
https://docs.python.org/3.7/library/stdtypes.html#int.from_bytes

(**int**).to_bytes : retorna un array de bytes que representan el **int** que le pases.
https://docs.python.org/3.7/library/stdtypes.html#int.to_bytes

Te invito a leer la documentación para que puedas ver ejemplos mas claros. 
Recuerda tratar de buscar primero por tu cuenta esta información! (en especifico, estos links
estaban en el enunciado) 
Espero haberte ayudado!

**Comment by Camila-sty** [comment]
si la ví, pero no entendía la diferencia de ```from``` y ```to```, y aún no la entiendo...

**Comment by szabala** [comment]
No te fijes tanto en `from` y `to`. 
` int.from_bytes()` es una **función**, mientras que `.to_bytes` es un **metodo** que puedes llamar de cualquier objeto del tipo `int`
Viendo los ejemplos de la documentación:

- Si quiero transformar el _byte_ `b'\x00\x10'` en un numero usando _big endian_ puedo hacer:
  `int.from_bytes(b'\x00\x10', byteorder='big')`
  y esto me retorna `16`
- Por otro lado, si quiero obtener la representación en _bytes_ del numero `16` utilizando _big endian_ :
   `(16).to_bytes(2, byteorder='big')`
  y esto me retorna `b'\x00\x10'`

La idea de esto es poder transformar numeros _int_ en _bytes_ y viceversa.
Saludos!

**Comment by KnowYourselves** [comment]
Hola @Camila-sty!

Para complementar la respuesta de @szabala, la diferencia entre `from_bytes` y `to_bytes` es que en la primera, estas creando un entero **desde** (`from`) una serie de bytes, mientras que en el segundo estas pasando un entero **a** (`to`) bytes, por ende la diferencia de nombre.

**Comment by Camila-sty** [comment]
ahora sí, gracias!
