### ISSUE TITLE
Correr ayudantia 10 desde cmd

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#1058]
Hola cuando corro la ayudantia 10 me tira este error al instanciar el main 
![image](https://user-images.githubusercontent.com/62180259/85306593-b5f68d80-b47c-11ea-959e-3b9a8c076be5.png)
También me queda la duda de si es que cada vez que quiera correr el codigo tengo que cerrar pycharm

**Comment by gatochico** [comment]
Hola! 

Primero, no, no es necesario que cierres tu IDE antes de correr el código mediante la terminal. Solo basta con que el código esté guardado antes de correrlo (pycharm tiene autoguardado, si mal no recuerdo? Si no lo tiene, basta un Ctrl+S en los archivos modificados antes de correr en terminal :ok_hand: )

Ahora, tu error: ¿Cómo estás corriendo el código desde la terminal? Probablemente el error sea un tema de paths relativos. Debes primero mediante `cd` llegar a la carpeta donde está tu código y luego ejecutarlo, o los paths relativos no funcionarán, ya que se calculan a partir tu ubicación en la terminal al momento de correr el código.

Espero tu respuesta!

**Comment by dsepulveda3** [comment]
Buena gracias! Si estaba corriendolo en la terminal (cmd). Efectivamente era eso, habia que llegar a la carpeta donde estaba el archivo con cd y luego poner "pyhton NOMBRE_ARCHIVO". Muchas gracias !
