### ISSUE TITLE
Problema con encode

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2233/syllabus#1058]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)

### Duda

Hola! estaba tratando de ocupar encode para pasar los mensajes a bytes, pero me lo deja en un string. He probado de mil formas y nada me funciona :(

**Comment by Lord-Kelsier** [comment]
Segun yo el proceso es:
```python 
string_de_json = json.dumps(mensaje)
mensaje_bytes = string_de_json.encode("utf-8")

```

**Comment by DCCollao** [comment]
Hola @conyfernandezt!

Efectivamente después de serializar un mensaje con json obtienes como resultado un dato de tipo _string_. Luego, para enviarlo, debes hacer justamente lo que indica @Lord-Kelsier, aplicando el encoding que desees al mensaje serializado. Una vez aplicado este paso tendrás tu objeto de clase `bytes`!

Te dejo adjunto un ejemplo para que quede más claro:
```Python3
import json

serializar = {"hola": "mundo"}
serializado = json.dumps(serializar)
encoded = serializado.encode("utf-8")
print(type(serializado), serializado)
print(type(encoded), encoded)
```

Cuyo _output_ es
```Python3
<class 'str'> {"hola": "mundo"}
<class 'bytes'> b'{"hola": "mundo"}'
```

**Comment by conyfernandezt** [comment]
Entonces, en el envio de informacion, los bytes que se tenga que enviar (los chunks de 60) deberian estar en ese formato? porque pense que tenian que tener el formato '\x63\x6c\x69\x63\x68\xe9'

**Comment by Lord-Kelsier** [comment]
Si, todo va en formato bytes, el segundo output y b'\x63\x6c\x69\x63\x68\xe9' son bytes. Tanto el servidor como  el cliente solo pueden enviar y recibir bytes

**Comment by DCCollao** [comment]
Mientras el mensaje que desees enviar sea de clase `bytes` no tendrás ningún problema. La diferencia de formato puede deberse a _encodings_ diferentes, o distintos tipos de datos codificados.
