### ISSUE TITLE
Aleatoriamente el envio de datos entre cliente y servidor falla

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2233/syllabus#1059]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, busco ayuda para resolver un problema, la busco aqui pues es un problema que no ocurre siempre, es aleatorio, si ocurriera cada vez que hiciera algo podria encontrar el origen, pero no puedo forzar que ocurra de ninguna forma. El **problema es** que cuando se envian datos desde el servidor hasta el cliente a veces llegan mal, pero no es que llegue mal ordenado el indice del paquete, sino que llegan corridos, es decir, mi programa lee los primeros 4 luego los siguientes 64, mirando que el primero sea el indice del paquete y aveces los 4 bytes del indice corresponden a parte del mensaje (**en resumen llegan corrido**). 

Esto me llevaria a pensar que hice algo mal, pero la mayoria de veces el programa funciona, se envian bien los datos, entonces el codigo deberia estar bien no? pues sino no funcionaria nunca.
Aun asi tengo un sospechoso:

- en mi codigo envie 3 cosas segidas a cada cliente, ¿python al tener 3 lineas seguidas que enviar datos a un socket puede mezclarlas?

Como duda extra: 
En los apuntes mencionaron que era recomendable que en el `rcv()` se pusiera una potencia pequña de 2, ¿esto aplica tambien para el `sendall()`? (es decir que se envien bytes cuyo largo es una potencia de 2)

**Comment by DCCollao** [comment]
Hola @Lord-Kelsier! 

Según la información que proporcionaste, creo que debe ser que no estás leyendo correctamente el mensaje según su largo.
Cuando un _socket_ recibe información, crea internamente una "cola" de lo que le falta por leer, y desde esa cola va sacando la información por trocitos del tamaño que le hayas indicado. Esto genera un problema que buscaré aclarar con el siguiente flujo:

1. Cliente envía un primer mensaje de 60 _bytes_
2. Cliente envía segundo mensaje de 60 _bytes_
3. Servidor comienza a leer su cola de mensajes, tomando _chunks_ de 64 _bytes_ cada uno
4. El primer mensaje que lee el servidor consta de los 60 _bytes_ del primer mensaje, y además los 4 primeros _bytes_ del segundo mensaje
5. Luego de leer el primer mensaje, quedan 56 _bytes_ en la cola del servidor, por lo que simplemente lee ese mensaje incompleto.

Es por esto que es importante que se rellene con _bytes_ 0 cuando el bloque no llega al largo especificado, como se indica en el diagrama del enunciado:
![image](https://user-images.githubusercontent.com/37167447/100174024-6ba18e80-2eaa-11eb-9cba-68a6244fe413.png)
