### ISSUE TITLE
Como comunicarme con otros computadores

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#1059]
Hola. Se que esta duda no es indispensable para poder pasar el ramo sin embargo la encuentro de mucha ultilidad...
Poniendo como ejemplo la AY10 como podría hacer para yo correr el server en mi computador, correr el main una vez en este mismo, y que otra persona desde otro computador pueda correr el main en el suyo y conectarse a mi servidor ? Así poder "chatear en linea"

**Comment by jeschuwirth** [comment]
Holaa,

Todo esto es la materia de Networking que se está viendo en el curso, si no te está funcionando correr el main en computadores distintos puede ser por que no están en la misma red local.

La conexión vista en el curso requiere que ambos computadores estén conectados en el mismo router. 

Si esa no era tu duda o no resuelve tu problema sigue comentando :)

**Comment by dsepulveda3** [comment]
Ya dale gracias ! Y en el caso de que quiera conectarme con personas que están conectados a otra red wifi? Me imagino que es un poco más complicado jajaja.

**Comment by jeschuwirth** [comment]
Para eso necesitarás hacer port-forwarding en tu router y jamás lo he intentado, por lo que no se si se puede o no con la librería.

Sin embargo puedes ocupar aplicaciones de terceros (como Hamachi) para "simular" una red local y poder correr el programa a distancia.

Como la pregunta se escapa de mi conocimiento te recomiendo mandarle un mensaje a algún profesor para que te expliquen de mejor manera, encuentro genial que quieras aprender más :D
