### ISSUE TITLE
Problema con cambiar_planos

### ISSUE THREAD

**Issue by joaquincarvajal** [IIC2233/Syllabus#106]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Al momento de ejecutar los test, siempre me retorna False, aunque en mi codigo tengo que se retorne false solo en el caso especifico de que no exista el archivo. ¿Será posible que los archivos para este test esten mal?

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by lfcpardo** [comment]
tengo la misma duda

**Comment by MaxAl100** [comment]
Hola! Podrías describir, por favor, cómo corres los tests?

**Comment by joaquincarvajal** [comment]
Hola!
Acabe por resolverlo durante el fin de semana!

Gracias igualmente!!

**Comment by joaquincarvajal** [comment]
Problema resuelto
