### ISSUE TITLE
Sobre los puntajes de simulación en la distribución de puntajes

### ISSUE THREAD

**Issue by Daniel-Guajardo** [IIC2233/Syllabus#106]
Respecto a este apartado

![image](https://user-images.githubusercontent.com/101299560/162545784-642e372c-0f8f-4208-9343-aea98011ec5e.png)

no me queda claro eso de "crear una o más partidas" al menos con respecto a eso de crear muchas partidas. ¿Se refiere a que mientras ejecuto el programa puedo jugar muchas partidas consecutivas? ¿O se refiere a que, de algún modo, se tienen varias partidas al mismo tiempo, o sea, varias instancias Casino creadas?

**Comment by catalina-arcila** [comment]
Hola!, se refiere principalmente que al correr una vez el código se puede jugar más de una vez tu programa, es decir, tu programa es capaz de salir de una similación y empezar otrar con solo correr **una** vez tu archivo en la terminal. Me avisas si sigues con la duda, suerte!
