### ISSUE TITLE
Duda acerca del uso de operador *args y **kwargs

### ISSUE THREAD

**Issue by MathiasPrett** [IIC2233/Syllabus#106]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola. Leyendo los contenidos, en el notebook de multiherencia se nos introduce el uso de los operadores *arg y  **kwargs, mediante el siguiente ejemplo:

![image](https://github.com/IIC2233/Syllabus/assets/142269948/a64c75dd-4223-4130-9883-87255e96a025)

A partir de lo que se explica ahí, me surgieron dos dudas:

1. Si por ejemplo para un test de nuestro código se entregan los los argumentos para evaluar nuestras clases en forma de **kwargs, especificando cada atributo con su propio key-word asociado, **para qué nos sirve el operador arg, si ya con el kwarg debería bastar para posicionar cada argumento en su lugar y arrancar correctamente la clase??**
2. Como se ve en la imagen adjunta, demuestran el uso del kwarg utilizando como ejemplo la creacion de la clase multiheredada académico. Se ve que cuando utilizan como ejemplo la persona "p1", le especifican sus atributos mediante el kwarg, mencionando su departamento, area y oficina utilizando su respectiva key-word. Sin embargo, noto que el nombre de la persona no tiene su key-word especificada, y aún asi la clase la reconoce y la crea correctamente. **A que se debe esto?**

gracias :)

**Comment by catalinamirandah** [comment]
Hola Mathias 😄,

Respondiendo a la primera pregunta, en este caso se utiliza únicamente **kwargs porque, como tú mencionas, se instancia la clase teniendo los atributo con sus propios key-word asociados. Distinto sería si la instanciáramos de la siguiente forma:

p1 = Academico(
    "Emilia Donoso",
    "O5",
    "Inteligencia de Máquina",
    "Ciencia De La Computación"
)

En este caso, deberás utilizar *args para definir tus clases, de todas formas, te sugiero que para evitar errores los pongas a ambos. Y en respuesta a la segunda pregunta, en python si un parámetro no tiene una key o nombre asignado, se asume que es un argumento posicional y se asigna al parámetro correspondiente según la posición, en este caso, la primera posición de los atributos de la clase Academico corresponde justamente al nombre.

Espero se haya entendido la explicación, sino coméntame aquí abajito.

Saludos!

**Comment by MathiasPrett** [comment]
@catalinamirandah entendido, muchas gracias!
