### ISSUE TITLE
ACTIVIDAD 1, duda libreria

### ISSUE THREAD

**Issue by jtvvtj** [IIC2233/Syllabus#106]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Puedo usar la librería defaultdict en la actividad 1?

**Comment by jtvvtj** [comment]
Pregunto ya que forma parte de la libreria collections, que sí nos dan
, y es contenido que se supone que ya se paso esta semana

**Comment by jtvvtj** [comment]
no dije nada sdjjsd

**Comment by Hernan4444** [comment]
Hola,

Solo por si acaso, si se puede usar. Cómo se indica en el enunciado, no pueden hacer import de nada más que las entregadas en el archivo, y justamente les damos `collections` por si la consideran necesario (no es obligación su uso, pero se las damos por si acaso).

Saludos! 🦖
