### ISSUE TITLE
líneas de definiciones en README.md

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#106]
Hola, es necesario que en el README.md especifique en qué línea y archivo se definió cada función y clase?

**Comment by jeschuwirth** [comment]
Hola @dlmed,

No es necesario que entregues la línea de cada función que hiciste. Basta con explicar que cosas pusiste en cada archivo.

Por ejemplo puedes decir que en tu archivo: usuario.py creaste la clase Usuario y x función asociada.

Recuerda que el readme debe ser corto y fácil de leer para el ayudante.

Si tienes dudas o no te queda claro puede seguir comentando en esta issue :)

Suerte!
