### ISSUE TITLE
modificar users.csv

### ISSUE THREAD

**Issue by odbravo** [IIC2233/Syllabus#106]
Como existen diferencias entre Traders e Investors, y esto no depende de su fecha de nacimiento ni otra variable en el archivo users.csv, ¿Podemos modificar ese archivo para que contenga una columna que identifique el tipo de usuario?

Además, si se utiliza el archivo csvgenerator.py se restablecerá el archivo users.csv a los valores iniciales, sin guardar las modificaciones que hayamos hecho, por ejemplo, registrando nuevos usuarios. ¿Podemos realizar modificaciones a ese archivo para que las funciones realicen un _update_ a los archivos csv en vez de restablecerlos a sus valores originales?

**Comment by Hernan4444** [comment]
@odbravo No puedes modificar ningún archivo en primera instancia (osea manual), tu programa debe ser capaz de leer el archivo que nosotros les damos al inicio y luego queda a tu criterio si modificas, creas o eliminas algo del archivo o incluso si cambias el formato y sigues con ese para las siguientes ejecuciones pero si llegamos a volver a poner el archivo en el formato inicial, tu programa debe saber como enfrentar eso.

Saludos!!

**Comment by odbravo** [comment]
Si obvio, la manipulación sería mediante el programa, pero insisto en que el csv que generan para los usuarios está incompleto, no se condice con los requerimientos propios de la tarea, ya que se debe poder diferenciar entre tipos de usuarios a pesar de que se cierre y se vuelva a abrir el programa.

**Comment by Hernan4444** [comment]
Uno de los desafios es implementar un sistema capaz de diferenciar los tipos de usuarios sin que nosotros se los demos altilo en el csv. Lo que si **queda a tu criterio** como tomar a los usuarios del csv en la primera instancia. Puedes suponer que todo aquel que por fecha tenga menos de 18 será underage, según la cantidad de ordes simultaneas que no hacen macht dirán cuales son Investor, etc (lo dejo a tu imaginación), pero luego por como se vá desarollando el mercado, tu programa deberá ver como guardar la información para que cuando se vuelva a ejecutar se dé cuenta de que es una continuacion de una ejecucion previa.

Saludos!!

**Comment by CPazrc** [comment]
Hola, tengo la misma inquietud que mi compañero... en base a tu respuesta, aunque yo seleccionara a mi criterio que tipo de usuario serán las personas (entre Trader e investor, porque la otra categoría resulta por defecto), aun así necesito que esa información quede registrada en el documento, porue de ella depende que funciones deben abrirse cuando se es de un tipo u otro (como el menú), lo que implicaría sí o sí añadir un indicador... no puedo sólo basarme en sus movimientos, ya que podría resultar que un usuario es Trader, por ejemplo, tratar de hacer más de 15 orders en un sólo día, y si no conozco el indicador necesario ¿que información uso para frenarlo?

Saludos...

**Comment by odbravo** [comment]
@CPazrc por si te sirve, yo lo que hice fue que mi programa detectara si en el .csv de los users hay una columna cuyo título sea la categoría del usuario. Si no existe la crea, asumiendo que sólo pueden ser underaged o traders, y si existe la lee. Si ya puedes leer y traspasar bien la información del csv, esto no debería ser difícil de implementar y cumple con lo que piden.

Ahora bien, si quieren que, sin tener una referencia de la categoría de usuario, identifiquemos entre traders e investors, esto es imposible, ya que el investor tiene facultades "ampliadas" a las del trader, por lo que podríamos tener un investor que, a pesar de sus privilegios, no los utilice, por lo que los datos guardados nos indicarían que es un trader.

**Comment by iqacevedo** [comment]
Hola !

Si leen el comentario de @Hernan4444 podrán ver que el les indico que queda a su criterio como tomar a los usuarios en la primera instancia que leen las bases de datos. Después de esto es labor de ustedes mantener consistencia entre los usuarios que son de un tipo y de otro cada vez que el programa se vuelva a ejecutar.

Saludos !
