### ISSUE TITLE
Formato de chat a mostrar

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#106]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

**Comment by Juampisaez** [comment]
Hola @fernandosmither 
En el enunciado se muestra un ejemplo de como se podria mostrar. Sin embargo, eres libre de buscar otra forma, solo debes fijarte en los elementos que el enunciado pide como **minimos** que deberia tener el chat (regular o grupo). Eso ultimo aparecen en los puntos **3.1** y **3.2** del enunciado (aparecen en negrita).

Espero se aclare un poco mas tu duda :)

**Comment by fernandosmither** [comment]
> Hola @fernandosmither
> En el enunciado se muestra un ejemplo de como se podria mostrar. Sin embargo, eres libre de buscar otra forma, solo debes fijarte en los elementos que el enunciado pide como **minimos** que deberia tener el chat (regular o grupo). Eso ultimo aparecen en los puntos **3.1** y **3.2** del enunciado (aparecen en negrita).
> 
> Espero se aclare un poco mas tu duda :)

Uff! Y yo buscando un ejemplo de chats desde el 5.1 ->
Si fuera llama me escupe. Gracias!
