### ISSUE TITLE
Recursos: posición geográfica en ruta

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#106]
"Al momento de consultar recursos, se debe indicar adicionalmente a lo almacenado en la base de datos, la ubicaci´on geogr´aﬁca del recurso, su estado actual (standby, en ruta a incendio, trabajando en incendio o en ruta a base). Si es que se encuentra fuera de la base, se debe indicar tiempo trabajado (desde que sali´o de la base) y tiempo de trabajo restante (la diferencia entre la autonom´ıa y el tiempo trabajado). Si se encuentra en ruta a alguna parte, se debe indicar la distancia hacia el objetivo."

Cuando los recursos se encuentran en ruta hacia alguna parte, hay que ir recalculando la posición (lon, lat)? O basta con saber punto origen / llegada y el tiempo recorrido/ restante?
Gracias!

**Comment by acrojas2** [comment]
Mi pregunta relacionada con esto mismo:
La posición se calcula respecto a la fecha en que el recurso fue asignado a apagar el incendio? Se puede considerar que apenas toca un punto de la circunferencia del incendio, el recurso comienza a apagar el incendio?o debe llegar al origen de la circunferencia para empezar a apagarlo?

**Comment by rpalmaotero** [comment]
@B-Dominguez se debe determinar la ubicación geográfica, es decir, latitud y longitud, además de los otros datos que se indican en el enunciado.

@acrojas2 Sobre la primera pregunta, sí. Sobre la segunda, no está definido, queda a tu criterio.
