### ISSUE TITLE
Nivel de economía

### ISSUE THREAD

**Issue by Pipelao** [IIC2233/Syllabus#106]
Hola :) , espero que se encuentren bien. Quiero preguntar acerca del nivel de economía, ¿qué pasa si al subir de nivel y multiplicar la tasa de deuterio o minerales me excedo de 10 o 15? , ¿es posible hacer eso?, si es así, ¿en qué otra ocasión me puedo exceder del límite? en caso que no, ¿hay alguna ocasión en la que me pueda exceder?

Gracias de ante mano, Saludos.

**Comment by ptflores1** [comment]
Hola eso se responde en #33 
Saludos !

**Comment by Pipelao** [comment]
@ptflores1 Gracias :)
