### ISSUE TITLE
enviar informcion de cliente a servidor

### ISSUE THREAD

**Issue by mleon17** [IIC2233/syllabus#1060]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mleon17** [comment]
Como puedo hacer para enviar al servidor el nombre se usuario del cliente?

**Comment by DCCollao** [comment]
Hola @mleon17!

En primer lugar, recuerda que para esta tarea no es necesario que cada cliente escoja un nombre de usuario, sino que **debes** hacer que el mismo servidor le asigne un nombre a cada cliente que se conecte correctamente.
Este tema se toca en la sección 5.2.1 del enunciado.

Mucho éxito!

**Comment by mleon17** [comment]
si eso ya lo hice, pero me complica mandar la información del cliente al servidor para que lo imprima en el servidor mismo.

**Comment by DCCollao** [comment]
En la issue #1068 expliqué un poco un ejemplo de contenidos, quizás eso te pueda ayudar.
Respecto a la forma en específico de identificar a un cliente desde el servidor, temo que no puedo darte esa respuesta, pues es una de las cosas que se espera solucionen para la tarea.
