### ISSUE TITLE
Error al intentar ejecutar ventana creada en Qt Designer

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#1060]
Hola, tengo un error al ejecutar un módulo ```.py``` donde intento mostrar la ventana creada en Qt Designer. Tengo dos carpetas creada en T03, que es **cliente** y **servidor** , dentro de **cliente** está éste módulo ```.py```. Para ejecutar esto, puse en la consola el directorio y luego el módulo, pero me lanza un error:
![image](https://user-images.githubusercontent.com/59337116/85311770-ec83d680-b483-11ea-8f05-e989ab60972e.png)
Supongo que no reconoce el directorio ```ventana```, pero éste no existe, entonces no sé cuál podría ser el error...?
Esto mismo lo puse al final de la issue #1051 , me estaba ayudando un compañero y no logramos resolverlo, quise hacer otra issue porque pienso que puede pasar de largo.

**Comment by KnowYourselves** [comment]
Hola @Camila-sty!

Podrías hacer push de tu código? Es más fácil que lo vea manualmente.

Avisame cuando lo hagas!

**Comment by Camila-sty** [comment]
@KnowYourselves  listo! gracias!

**Comment by KnowYourselves** [comment]
Pero que error más extraño. 

Abre el archivo `ventanainicio.ui` y verás las siguientes lineas:

![image](https://user-images.githubusercontent.com/26102039/85313701-674df100-b486-11ea-8124-846389123741.png)

Modifica el string `"ventana.inicio.qr"` por `"ventana_inicio.qr"` y voilà.

**Comment by Camila-sty** [comment]
GRACIAS!!!
