### ISSUE TITLE
Conexión con parametros.json

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#1061]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! en la parte 5.1.2 del enunciado habla sobre el uso de parametros.json, pero no entiendo si es que al instanciar mi clase servidor en mi main.py debo usarlo desde ahí o puedo asumir el localhost y el port escribiéndolos sin usar parametros.json

de antemano muchas gracias 😸

**Comment by matiasmasjuan** [comment]
Hola @Margarita-Paz !

Los parámetros de *localhost* y *port* **deben** ir en ```parametros.json```, por lo que **no** puedes asumir que los conoces de antemano al momento de instanciar el servidor. En base a eso, puedes intuir que deberás *deserializar* el archivo ```parametros.json``` **antes** de instanciar el servidor.

Saludos y mucho éxito con la tarea! :smile:

**Comment by Margarita-Paz** [comment]
Muchas gracias!
