### ISSUE TITLE
cerrar sockets

### ISSUE THREAD

**Issue by camolina2** [IIC2233/syllabus#1061]
Hola!

Me queda la duda de cuando realmente se debe cerrar un socket. 

En la última ayudantía, por lo que entiendo, solo cierran el socket del cliente cuando este no se ha podido conectar con el servidor y el socket del servidor no lo cierran nunca.

Sin embargo, en la última actividad, tienen como excepción que se mande a cerrar el socket del cliente cuando la conexión falla. Es decir, si es que no lo logra escuchar se envía la señal de que se que se cierre el socket del cliente correspondiente y se elimina el socket de ese cliente en el diccionario del servidor. 

Mi pregunta es porque me salen algunos errores de perdida de conexión y luego no encuentra al cliente, no sé si será por esto.

Muchas gracias

**Comment by gatochico** [comment]
Hola!

Idealmente deberías tratar de atrapar todos esos casos donde puede que la conexión se caiga/falle y cerrar el socket antes en el caso del cliente y el servidor. En la actividad hay buenos ejemplos de esto: el que indicas tú, que saca el socket del cliente del diccionario del servidor y lo cierra en el cliente, lo que evita posibles errores cuando necesites hacer envios masivos desde el servidor. Otro ejemplo, es que en el main del servidor, hacen un close del socket del servidor cuando hacer Ctrl-C para parar el programa. Esto evita que cierres el programa y el puerto quede ocupado, haciendo que tengas que ir al task manager a matar el proceso o elegir otro port para probar de nuevo tu tarea.

Aunque no sé qué codigo en específico te lanza esos errores, es buena intuición el tratar de implementar estas medidas anteriores para minimizarlos (:

Espero se haya entendido!
