### ISSUE TITLE
Enviar señal desde el servidor al backend

### ISSUE THREAD

**Issue by mpvalen** [IIC2233/syllabus#1062]
Hola, estuve intentando enviar la información que recibe el servidor desde el cliente, en forma de señales, al backend (del servidor). Probé hacer esto usando el código de los ejemplos de la clase 14, donde añadí un par de líneas: la señal, una instancia de clase `Backend`, la conexión de la señal y la emisión de esta.
![Screenshot_2](https://user-images.githubusercontent.com/50853911/85312429-d296c380-b484-11ea-9a51-ca5fbd62d94b.png)
![Screenshot_1](https://user-images.githubusercontent.com/50853911/85312480-e3dfd000-b484-11ea-8a72-a8f715453995.png)
En la clase Backend tengo el método `recibir` que debería printear el evento, pero nunca llega a printearse. La conexión servidor-cliente funciona bien.
Intenté emitir la señal antes de crear los threads y conectar al cliente, y funciona bien (asumo que el problema viene luego de crear threads)

![Screenshot_3](https://user-images.githubusercontent.com/50853911/85313050-a7f93a80-b485-11ea-88f5-00b2da5bd1c4.png)
Llevo pegada en esto harto rato :c ¿Cómo puedo arreglarlo?
Saludos

**Comment by KnowYourselves** [comment]
Hola @mpvalen!

Estás algo confundida. El servidor no tiene porque ser realizado con nada de PyQt, ya que no tiene asociada ningún tipo de interfaz gráfica. Debido a esto, no es necesario que te partas la cabeza con uso de señales, el servidor simplemente recibe mensajes de los clientes y los maneja, puedes pensar que de por si el servidor es un backend.

Éxito!

**Comment by lewebe** [comment]
@KnowYourselves Hola! Tengo una duda relacionada. Cuando dices
>puedes pensar que de por si el servidor es un backend.
Esto significa que la lógica de juego debería estar en el servidor, considerando que ese revisa si las jugadas son válidas o no? Si la respuesta es no, puedo hacerlo de esta manera en mi programa? Con esto, en el backend de Cliente solo quedaría lo que se refiere a las conexiones y actualización del frontend.

**Comment by KnowYourselves** [comment]
Hola @lewebe!

Exactamente, es parte del rol del servidor manejar toda la lógica del juego.
