### ISSUE TITLE
Duda avance envío de mensajes

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#1062]
Me quedan dudas sobre lo que debemos implementar para el avance, ya que por lo que entiendo, nos pide implementar que nuestro codigo al ejecutar el servidor y luego el cliente lo que deberia pasar es que primero le enviemos una solicitud de acceso al servidor y este la acepte para que luego el servidor le envíe de vuelta al cliente el nombre asignado (aleatoriamente) al cliente.
Sin embargo no me queda claro que tiene que pasar después, yo tengo eso implementado y también implemente el protocolo del envio entre cliente<->serividor, pero por ejemplo enviar algun mensaje desde el cliente hacia el servidor no nos piden ***¿debemos implementar algun tipo de mensaje desde el cliente hacia el servidor?, o con lo expuesto anteriormente basta??***

**Comment by matiasmasjuan** [comment]
Hola @totoiii !

Para este avance se pide exactamente lo que indicas, es decir, tener implementado el **protocolo de envío** tanto desde el cliente hacia el servidor, como del servidor al cliente. Dado que el cliente aún no envía un mensaje explícito hacia el servidor (al menos para el avance), no es necesario que lo hagan. Lo importante es que implementen el **protocolo** correctamente, por lo que se evaluará mas bien a nivel de código. Recuerda que el servidor debe imprimir los **logs** para saber si múltiples clientes se conectan correctamente con él.

Saludos y mucho éxito con la tarea! :smile:

**Comment by totoiii** [comment]
Gracias

**Comment by matiasmasjuan** [comment]
De nada!

Recuerda no cerrar las *issues* ya que les puede servir de utilidad para tus demás compañeras y compañeros.

Saludos! :smile:
