### ISSUE TITLE
[Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2233/syllabus#1063]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)

### Duda

Hola! al tratar de enviar el nombre al usuaria me sale el error '[Errno 9] Bad file descriptor' en la terminal y creo ques eso genera que no se pueda decodificar el mensaje. Busque en internet porque podia ser y la verdad esque no entendi mucho de que se trataba :(

**Comment by Juampisaez** [comment]
Hola, si puedes mostrar el error completo y una foto de la parte de tu código donde aparece el error, sería más fácil ayudarte en tu caso particular. Por otro lado, el error bad dile descriptor quiere decir que estás intentando usar un archivo que no ha sido abierto. [Acá puedes encontrar un ejemplo](https://es.stackoverflow.com/questions/42685/qu%C3%A9-significa-el-error-bad-file-descriptor-en-python3)

**Comment by conyfernandezt** [comment]
![Screen Shot 2020-11-25 at 12 24 01 AM](https://user-images.githubusercontent.com/69609564/100241884-f3bb7e80-2f12-11eb-8f0e-ac42501d073b.png)
![Screen Shot 2020-11-25 at 11 40 32 AM](https://user-images.githubusercontent.com/69609564/100241978-0b930280-2f13-11eb-8c04-d5971bb8d235.png)
La primera imagen corresponde al error que sale en la terminal y el segundo, donde deberia estar el error

**Comment by Juampisaez** [comment]
Ya, estuve viendo harto rato jugando con tu codigo, y me da la impresión de que el error esta en el finally de la linea 56, ya que tu while de la 49 siempre sera verdadero y al final del try lo que estas haciendo es cerrar tu socket, por lo que deja de escuchar al servidor, y por eso tira error. Aunque tambien tengo dudas con el threading.Lock() que colocas en la linea 50. Por otro lado una opcion a esta forma, es la vista en contenidos [en este link](https://github.com/IIC2233/contenidos/blob/master/semana-14/3-ejemplos.ipynb). 

Espero haberme explicado bien. Cualquier cosa, sigo atento.
