### ISSUE TITLE
Github Push

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#1064]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
Tengo este problema con github. Ingreso mi usuario y contraseña y no se conecta. Cambia la contraseña y sigue sin funcionar 
![git hub](https://user-images.githubusercontent.com/69764237/100209943-b7842000-2f0a-11eb-9338-ce9d30206a82.PNG)

[Agrega aquí lo que quieras aportar o preguntar]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Mjtala** [comment]
Hola @enriquemolinare, trata haciendo git pull origin master y avísame como te va!

**Comment by enriquemolinare** [comment]
Te refieres hacer el pull desde la pagina web? intenté subir las carpetas de server y client pero cuando se subían no se subían todos los archivos :/

**Comment by Mjtala** [comment]
No, ahí mismo en la consola en vez de escribir git push escribe **git pull origin master** . Lo más probable es que tu master en github esté más actualizado que tu repo local por lo que no te dejará subir cambios hasta que tu repo local tenga como mínimo las cosas que están en tu master.
**_Pasos_**
1. git pull origin master (en tu git bash, la misma de la foto)
2. git add
3. git commit -m "<loquequieras>"
4. git push
