### ISSUE TITLE
Cómo usar el archivo parametros.json

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#1064]
Hola! No me queda la utilidad de este archivo, cómo se debe utilizar y en qué cambia (ademas del formato en que se escribe) respecto a los archivo anteriores, de extensión `.py`

**Comment by Camila-sty** [comment]
Yo tengo la misma duda. Además quiero agregar otra cosa que tiene que ver con lo mismo.
El diccionario que se crea en ```parametos.json``` debemos asociarla a una variable para poder utilizarla en algún módulo ```.py``` ?
O se utiliza éste dict directamente? y cómo?

**Comment by gatochico** [comment]
Hola! 

`parametros.json` tiene la misma utilidad que `parametros.py` en las tareas anteriores: almacenar valores que pueden ser cambiados de forma rápida según cómo queramos que este configurado el programa. Lamentablemente, para esta tarea no hay muchos parametros explícitos a añadir, por lo que su utilidad no es tan obvia a simple vista u.u

Nos cambiamos a la extensión `.json` en esta tarea ya que antes no se había pasado la materia de serialización en tareas pasadas, pero es bastante más común que en diferentes proyectos de programación se usen json para definir parámetros u otras configuraciones (la misma configuración de VSC está en un `settings.json`! ). 

Ahora, respecto a su uso: Deben abrir el archivo con el método open() y luego usando los contenidos de la semana de serialización, cargar el json y usarlo cuando lo necesiten.

Saludos y éxito!

**Comment by tocococa** [comment]
En la misma línea, tiene sentido tener un .py que se corra antes de cargar el servidor y escriba los paths de los sprites a parametros.json? Porque ingresar todos los paths a mano lo encuentro tedioso (y poco escalable).

**Comment by gatochico** [comment]
La verdad no tendría mucho sentido, ya que usar un script para generar un parametro que luego será usado en otro script haría el .json innecesario. 

Como recomendación, como los nombres de la mayoría de los sprites son bastante genéricos y siguen un formato bien claro, podrías generar el path de forma dinámica según qué sprite necesites, y usar el .json para almacenar las partes únicas (que no siguen el molde)? Otra cosa es aprovechar el truco de concatenar paths usando una lista y `os.path.join` para no guardar todos los paths a todos los archivos en el json.

**Comment by lewebe** [comment]
Gracias gatochico, soy tu fans!
