### ISSUE TITLE
error al intentar recibir el mensaje de vuelta del servidor

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#1066]
Hola, tengo un error cuando el servidor manda de vuelta el mensaje al cliente. Tengo un método en cliente que se encarga de ejecutar un thread para ese cliente y recibir el mensaje del servidor, pero en esta función me tira el siguiente error:
![image](https://user-images.githubusercontent.com/59337116/85320662-679fb980-b491-11ea-86b1-319887ebd897.png)
Creo que tiene que ver con el tema del thread. Estoy ocupando la misma idea para el servidor y cliente creado en la AY10, pero adaptándola a mi programa. Ocupo el mismo método ```listen()``` y ```listen_thread()``` de la clase Cliente, para recibir el mensaje del servidor. Por qué no me funciona¿?

**Comment by gatochico** [comment]
Hola! (Espero todavía te sea util esta info)

Lo que ocurre es que llamas a la función `json.loads(decoded_data)`. Sin embargo, si haces `print(decoded_data)` justo antes de esa línea, puedes ver que decode_data **ya es un string que fue decodificado** (puedes comprobarlo ya que al hacer print de decoded_data, nos retorna el valor del string sin las comillas dobles, mientras que si el string no estuviera decodificado ya, las incluiria en el print. Por lo tanto, al hacer json.loads() harás loads de algo ya decodificado y te lanzará ese error.

Soluciones:
- De momento saca el json.loads mientras solo manejes envios de strings como el que tienes, y lo agregas de nuevo cuando avances mas en la tarea y lo necesites para parsear cosas más complejas.
- Comienza a implementar un protocolo más complejo de envío de mensajes de inmediato! Toma como inspiración la ayudantía 10, donde la info entre cliente y server se envía mediante diccionarios que luego son parseados por el json.loads()

Espero se haya entendido uwu. Éxito!

**Comment by Camila-sty** [comment]
Sí, muchas gracias, ahora lo pude solucionar :smile:

**Comment by Camila-sty** [comment]
No entendí mucho esto "la info entre cliente y server se envía mediante diccionarios que luego son parseados por el json.loads()". Se refiere a que el cliente puede recibir un dict donde puede venir string y bytes ?. A qué te refieres con son "parseados" por el json.loads() ?

**Comment by gatochico** [comment]
Con el envío mediante diccionarios, me refiero por ejemplo en la ayudantía, en [las lineas 120 a 125 de este archivo](https://github.com/IIC2233/syllabus/blob/master/Ayudant%C3%ADas/AY10/server.py), si te fijas guarda todo lo que se va a mandar en un **diccionario** que sigue un formato estándar (type, username, data). Luego, antes de enviarlo se transforma a un **string** y se codifica. Luego cuando llega al cliente y se decodifica, tendrás un **string con forma de diccionario** por lo que falta que se serialize con json.loads(). Una vez serializado recién se puede trabajar con esa información como si fuera un diccionario de python normal.

_Parsear_ refiere a ese proceso de tomar un _string_ que tiene una estructura similar a una estructura de datos (una lista, un diccionario, etc...) y transformarlo a esa estructura! (debería haberlo explicado en ese comentario, ups)

Espero haya quedado más claro ahora

**Comment by Camila-sty** [comment]
Sí, perfecto, gracias!!
