### ISSUE TITLE
[WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto

### ISSUE THREAD

**Issue by pabloist** [IIC2233/syllabus#1066]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola buenas, hice esta issue porque recibo este error al tratar de conectar un cliente al servidor de mi tarea e incluso cuando intento ejecutar los codigos de ayudantía que están bien formulados y no pude encontrar información al respecto :(

**Comment by Mjtala** [comment]
Hola @pabloist podrías subir tu código a tu repo para así poder verlo :)
