### ISSUE TITLE
Duda cantidad de jugadores

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#1067]
En el enunciado aparece que debemos iniciar el juego cuando se cumpla una cantidad de jugadores dada por CANTIDAD_JUGADORES_PARTIDA, sin embargo me hace sentido que los valores que pueda tomar ese valor está acotado (por ejemplo que juegue 1 jugadore no tiene mucho sentido) mi pregunta es (sobre todo debido a mi implementacion de la interfaz gráfica) es que  **este valor de CANTIDAD_JUGADORES_PARTIDA ¿siempre será 4?** o tambien debemos implementar nuestro programa para otros numeros, y si es asi, cuales son todos los valores posibles que podrá tomar CANTIDAD_JUGADORES_PARTIDA?

**Comment by amahns1** [comment]
Me sumo a la duda, sobre todo por la interfaz gráfica. En los sprites hay material para 4 jugadores, entonces ¿podemos asumir que el máximo son 4 jugadores? Además en la sala de espera habría que cambiar en algún momento el tamaño de la ventana o el tamaño de las letras.

**Comment by Mjtala** [comment]
Hola @totoiii y @amahns1, el juego debe estar implementado para 2, 3 o 4 jugadores y por ende las interfaces gráficas deben adaptarse a las diferentes cantidades de jugadores.

**Comment by Mjtala** [comment]
@amahns1 en relación a lo que mencionas sobre cambiar el tamaño de la ventana o tamaño de letras eso queda a tu criterio y lo que tu estimes conveniente.
