### ISSUE TITLE
Paths relativos en json

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#1068]
Hola. Si necesito agregar los paths de los sprites a parámetros.json como se hace? También no se como agregar el path si es que esta fuera de la carpeta. Por ejemplo, mi main.py esta en carpeta clientes pero los sprites están en otra carpeta.

**Comment by vicentevegaulloa** [comment]
Hola @tedroppelmann!

Respecto a lo primero, para agregar un path a `parametros.json`  puedes seguir el ejemplo que se entrega en el enunciado (p. 13):
![image](https://user-images.githubusercontent.com/48890894/85334747-c2dda600-b4a9-11ea-8eb4-864e4717d3ee.png)
Para hacerlo de manera más ordenada puedes anidar diccionarios (recuerda que debes manejar de forma especial los objetos anidados en JSON como se explica al final de este [notebook](https://github.com/IIC2233/contenidos/blob/master/semana-13/2-serializaci%C3%B3n.ipynb)).

Respecto a lo segundo, supongamos que tienes estos archivos:
![image](https://user-images.githubusercontent.com/48890894/85335996-eefa2680-b4ab-11ea-97ad-5212664e1f13.png)
Para abrir `hola.txt` desde `exp.py` debes escribir el path como: `"../folder2/hola.txt"`. Observa que antepuse dos puntos (`../`), esto indica que se debe buscar desde un nodo superior.

Espero haberte ayudado :smiley:
