### ISSUE TITLE
socket.sendall() ¿Qué socket hay que poner?

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#1068]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Viendo la AF05 me surgió una duda con el método sendall(). Una vez que tengo el mensaje que quiero enviar en bytes y pongo sendall, desde el servidor se pone el socket del cliente al cual se quiere enviar el mensaje: ```socket_cliente.sendall(mensaje)```

Por lo mismo pensé que cuando el cliente manda un mensaje al servidor había que poner ```socket_servidor.sendall(mensaje)```, pero ponen ```self.socket_cliente.sendall(mensaje)```, entonces no entiendo ¿qué socket se pone en el método ```socket.sendall(mensaje)```? ¿Al que se le quiere enviar el mensaje, solo el del cliente, el de quien envía el mensaje, o cómo funciona?

**Comment by DCCollao** [comment]
Hola @kalarconvl! 

Para tener más clara la forma de enviar y recibir datos mediante _sockets_ te recomiendo revisar los contenidos, pues hay varios ejemplos con los que probablemente te quede más claro cómo realizarlo de forma correcta.

Uno de los ejemplos de _networking_ que se incluye dentro de contenidos es el siguiente:

1. **Servidor**
```Python3
import socket

host = socket.gethostname()   # Esto obtiene el nombre en la red de este host
port = 12345

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.bind((host, port))
print("Listo para recibir. Ahora voy a esperar que me hablen...")
sock.listen()

sock_cliente, (host_cliente, puerto_cliente) = sock.accept()
print("Conexión desde", host_cliente, puerto_cliente)

while True:
    data = sock_cliente.recv(4096)
    print(f"Recibí estos bytes: {data}")
    if not data:
        break
    print("Los enviaré de vuelta")
    sock_cliente.sendall(data)

sock_cliente.close()
sock.close()
```

2. **Cliente**
```Python3
import json
import socket

server_host = ''  # Debemos poner aquí la dirección IP del servidor.
                  # Si no ponemos nada, supone que estamos hablando con un programa en el mismo host.
server_port = 12345

# Generamos la información que enviaremos; en este caso, es un simple diccionario.
data = {1: "Hola", 2: "Chao"}
mensaje = json.dumps(data)

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((server_host, server_port))

# Debemos enviar bytes.
sock.sendall(mensaje.encode('utf-8'))

# Decodificamos los bytes y luego los deserializamos con JSON.
data = json.loads(sock.recv(4096).decode('utf-8'))
print(data)
input("ENTER para terminar.")
sock.close()
```


En este ejemplo se envían y reciben datos desde **ambos lados de la conexión**, por lo que creo que es especialmente útil para comprender cómo se hace esta interacción.

Respecto a la pregunta sobre la AF05, creo que tu confusión se debe a un alcance de nombres. En el lado del cliente se crea un socket llamado socket_server, mientras que en el lado del cliente la variable que contiene al socket se llama socket_cliente. Esto significa que la línea de código que indicas (`self.socket_cliente.sendall(mensaje)`) está enviando datos a través de ese socket al `host` y `port` que se indicaron en su conexión (que corresponde al servidor), y **no** que se está enviando datos a un cliente.

Quedo atento a cualquier duda!
