### ISSUE TITLE
Atributo log no encontrado 

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#1069]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

hola! tengo un error del tipo AttributeError: 'Servidor' object has no attribute 'log_activado' pero en el init del servidor tengo definido como self.log_activado = True no entiendo en que puede estar fallando :(

**Comment by DCCollao** [comment]
Hola @Natydlb!
Generalmente este tipo de errores se dan cuando dentro del `__init__` llamas a un método que utiliza el atributo **antes de definir el atributo**. Te recomiendo que revises que estás definiendo al atributo antes de llamar a cualquier método que lo vaya a utilizar.

Quedo atento!
