### ISSUE TITLE
Leer mensajes por chunks

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#1069]
Hola, para la comunicación entre servidor y cliente, ¿se deben leer los mensajes por chunks?
Si es así, de a cuántos bytes se recomienda hacerlo?

**Comment by szabala** [comment]
Hola! Para el **Envio de Cartas** es necesario leer los mensajes por _chunks_ (ya que el _bytearray_ se confecciona para facilitar esto). Como queda a tu criterio como estrucutrar el resto de comunicaciones entre servidor y cliente, puedes leer los mensajes como te acomode. Te recomiendo igual hacerlo por _chunks_, asi no tienes que preocuparte del largo de las cosas que envies de antemano.

En cuanto al _chunk size_, lo que importa es que seas consistente (16 es un chunk size bastante comun). Puedes usar el que te acomode mientras que no sea demasiado grande, ya que entonces seria lo mismo que no leer el mensaje por _chunks_.

Suerte con la tarea!

**Comment by lewebe** [comment]
Gracias! Ahora me surge otra duda; cuando dices 
> queda a tu criterio como estrucutrar el resto de comunicaciones entre servidor y cliente
Cómo puedo estructurar más de una comunicación? Es decir, cómo hago para que mi fomar de leer datos cambie dependiendo de lo que recibo? Por ejemplo, si yo quiero como cliente enviar el nombre de usuario que me gustaría usar; cómo hago para que el server no lea datos buscando un id, un largo de bytes, etc. (cosas que tengo implementadas para cuando el cliente envía información de una carta)?

**Comment by szabala** [comment]
Existen varias maneras de solucionar esto: 

Una es enviar toda la información de la msima forma en que se envian las cartas. Entonces, armas un _bytearray_ como el de el enunciado donde los primeros cuatro _bytes_ te indican que es lo que se esta enviando. Por ejemplo, estableces que el `id` 4 signifique que lo que se esta mandando es un diccionario, el cual contiene un intento de ingreso de usuario (esto es más ordenado ya que mantienes un formato durante toda la comunicación).

Otra forma es mandar toda la información con diccionarios, y cuando tengas que enviar una carta, mandas un diccionario antes indicando que lo que viene es una carta. Entonces ahi cambias como el receptor lee el mensaje (ya que tienes que leer el _bytearray_ de la carta de manera especial).

Espero haber aclarado tu duda!
