### ISSUE TITLE
Duda sobre el readme y su extensión

### ISSUE THREAD

**Issue by Yeps3nM** [IIC2233/Syllabus#107]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola :) 
Tengo la duda si es una mala práctica ser detallada en el readme respecto a cómo funciona el código, y si soy detalla allí es necesario comentar el código? ¿Puedo hacer ambas cosas y está bien igual? Muchas gracias!!

**Comment by MaxAl100** [comment]
Hola! El README lo puedes hacer tan extenso como quieras, pero también te recomiendo tener respeto por el tiempo del ayudante :d.
Sobre si puedes hacer ambas cosas, no hay nada que te limite, como práctica general los comentarios del código son lo típico al trabajar con gente, el README en **general** son aspectos del comportamiento general o detalles específicos que no calzan muy bien dentro del código.
Espero haberte ayudado, si tienes más dudas escribe no más! :)

**Comment by Yeps3nM** [comment]
Entiendo! Entonces cuando mencione los métodos no debo describir todo lo que hacen, solo si está completo. Y sí especificar en caso de que no funcione completo, lo que le falta. Por otro lado, está bien si cambio el diseño del readme base pero aún así incluyo todo lo que piden?

**Comment by MaxAl100** [comment]
Claro, el readme base es para que los alumnos sepan que insertar, eso sí te recomiendo no cambiar demasiado el orden de las cosas para no enredar a los ayudantes! (y perdón por la tardanza en la respuesta 😅 )
