### ISSUE TITLE
Imprimir atributo tipo lista

### ISSUE THREAD

**Issue by fabarros** [IIC2233/Syllabus#107]
Hola, tengo una clase que uno de sus atributos es una lista. Al hacer print(lista) me arroja algo de la forma `__main__.Clase object at 0x039B5C50.`
Mi situación es la siguiente:
```
class Clase0:
   def __init__(self)
      #ASDASSD
class Clase1:
   def __init__(self)
      self.lista_clase1 = []
class Clase2:
   def __init__(self)
      ##asdasdas
   def agregar_cosa(self, cosa0 = Clase0, cosa1 = Clase1)
      cosa1.lista_clase1.append(cosa0)

a = Clase0()
b = Clase1()
c = Clase2()
c.agregar_cosa(a, b)
print(b.lista_clase1)
```
¿Cómo puedo hacer para imprimir la lista? Gracias :)

**Comment by tcgarrido** [comment]
Hola! sí te está imprimiendo la lista, de hecho creo que tu output es [__main__.Clase object at 0x039B5C50], si quieres que te imprima algo en específico agrégale el método __repr__ a la clase que estas agregando a la lista.
