### ISSUE TITLE
Problemas de uso git commit

### ISSUE THREAD

**Issue by matiaschen** [IIC2233/syllabus#107]
Hola, nuevamente no me funciona el commit, traté de borral la carpeta de repo personal para clonarla nuevamente, pero no me deja ni borrarla diciendo que hay un procesi activo. y no he podido hacer un commit o rm de un archivo que ya esta 'added' y falta su commit. Trate con rm -f ./.git/index.lock en la carpeta misma y rm -f C:/Users/matic/OneDrive/Escritorio/Universidad Real/2021-1/Programacion Avanzada/matiaschen-iic2233-2021-1/.git/index.lock. Reinicié el computador. Por Favor ayuda

**Comment by ajuanchuto** [comment]
¡Hola!

¿Porqué no te funciona el commit? Podrías subir pantallazo de lo que te aparece en la terminal para poder ayudarte mejor, Gracias 😃

**Comment by matiaschen** [comment]
![Capture](https://user-images.githubusercontent.com/70550149/112867758-a9e5cf00-9091-11eb-8481-e41124927606.PNG)
si obvio!

**Comment by matiaschen** [comment]
me había ocurrido antes y lo solucione borrando y clonando de nuevo, ya no me deja

**Comment by ajuanchuto** [comment]
Prueba con este comando para borrar el archivo: `rm --force ./.git/index.lock`.

Dime si te sirve, estaré buscando por mientras otras posibles soluciones. 💯

**Comment by matiaschen** [comment]
Buenísimo, no me funcionó, gracias

**Comment by matiaschen** [comment]
lo hice en la carpeta misma

**Comment by ajuanchuto** [comment]
¿Te funcionó o no? jajaja Me perdí. 😆

**Comment by matiaschen** [comment]
no me funciono

**Comment by matiaschen** [comment]
gracias por ayudar digo

**Comment by ajuanchuto** [comment]
Ya jajaj perfecto!

Entonces prueba haciendo esto: (Parado en la carpeta `C:/Users/matic/OneDrive/Escritorio/Universidad Real/2021-1/Programacion Avanzada/matiaschen-iic2233-2021-1/`)

```
cd .git
touch index.lock
rm -f index.lock
```
Y si no te funciona. nuevamente intenta con `rm --force index.lock`.

Dime si eso te funciona 😄

**Comment by matiaschen** [comment]
hice todo eso y tampoco :( llevo varias horas en esto jajaja

**Comment by matiaschen** [comment]
Si funco! te pasaste
