### ISSUE TITLE
Crear galaxia

### ISSUE THREAD

**Issue by Pipelao** [IIC2233/Syllabus#107]
Hola

Al momento de crear una galaxia (sección 6.1) el usuario elige un planeta que quede conquistado, ¿éste también parte con el 75% de la población máxima o parte con cero y el resto de los planetas no conquistados parte con el 75% de la población?

Gracias.

**Comment by IchottMano** [comment]
@Pipelao Hola!
Como dice el enunciado, al elegir un planeta todos **los demás** deben partir con el 75% de la población.
Saludos!

**Comment by Pipelao** [comment]
@IchottMano Gracias :)

**Comment by kenzoak** [comment]
Y cuando se crea una galaxia, se puede elegir no crear ningun planeta dentro de esta?

**Comment by IchottMano** [comment]
@kenzoak Hola!
Eso se responde en la issue #35 .
Saludos!

**Comment by kenzoak** [comment]
Perdón, no lo había visto. Gracias!
