### ISSUE TITLE
named tuples

### ISSUE THREAD

**Issue by santiago3c** [IIC2233/Syllabus#107]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

No entiendo qué hace Register_type en el siguiente ejemplo, si alguien me podría explicar por favor
![image](https://github.com/IIC2233/Syllabus/assets/142272696/c30f5167-9d4c-440a-ad5b-f0fd198003b2)

[Describe tu duda de manera detallada, explicando los contenidos en cuestión y ojalá colocando código o un caso de uso de ejemplo]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by catalinamirandah** [comment]
Hola 😄,

En este código, Register_type es el nombre que le estás dando a la namedtuple llamada Register, en la práctica puedes modificar este parámetro como a ti más te acomode. Es necesario asignar esto dado el tipo de estructura que estás creando, además de que favorece la legibilidad, mantenibilidad y facilidad de uso en el código.

Saludos!

**Comment by santiago3c** [comment]
Clarísimo, muchas gracias
