### ISSUE TITLE
Duda con funcion resolver_tablero()

### ISSUE THREAD

**Issue by RaiSepulveda** [IIC2233/Syllabus#107]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, buenas tardes tengo una duda con respecto a como debería pensar la función encontrar solución por que por mas que lo pienso no logro entender como encontrarla.
Logré resolver el tablero para una bomba pero para el momento que trato de resolver la 2da bomba se me cambia todo y la primera bomba deja de estar resuelta, es mejor hacer una funcion que resuelva todo de 1 o existe manera para ir resolviendo 1 a 1?
Muchas gracias de antemano

**Comment by elisahonorato** [comment]
Hola @RaiSepulveda, te recomiendo pensar alguna forma en la que no la tengas que rellenar manualmente, es decir, que haya un algoritmo que intente resolver todo de una. La otra opción es ir seleccionando pedazos de celda pero creo que puede ser más tedioso. Avísame si es que te sirve.
