### ISSUE TITLE
Duda autonomia

### ISSUE THREAD

**Issue by Okhan97** [IIC2233/Syllabus#107]
Se que dice en la tarea, pero quiero confirmar. Si un recurso tiene 3 horas de autonomia y se demora 1 hora en ir y 1 hora en volver ¿ entonces trabaja 1 o 3 horas ?

**Comment by rpalmaotero** [comment]
Sólo una hora.

**Comment by juvaldes** [comment]
Pero cuando definen la autonomia de un recurso el enunciado se dice que no cuenta el tiempo de traslado ( cuadro2: recursos.csv) . Entonces me salió la duda. No deberían ser 3 horas de trabajo?

**Comment by asdegoyeneche** [comment]
Me sumo a lo mencionado a @juvaldes. En el cuadro 2 se dice que no incluye traslado, pero en el punto 4.2.3 se menciona que el tiempo de trabajo restante es la diferencia entre la autonomía y tiempo trabajado (tiempo desde salida de base). ¿ Qué consideramos ?
Saludos

**Comment by arturodelreal** [comment]
@asdegoyeneche @juvaldes Tienen razón, queda a criterio de ustedes. No olviden poner lo que asumieron en el Readme
