### ISSUE TITLE
Sobre efectos causados por la personalidad del Jugador

### ISSUE THREAD

**Issue by JTUnger** [IIC2233/Syllabus#107]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Estaba veindo el excel de distribucion de puntaje y no me queda claro si es obligacion para obtener el puntaje completo implementar las aciones especiales de cada personalidad como un metodo distinto o si estas se pueden poner dentro de otros metodos. A lo que voy es que para obtener el puntaje completo de la imagen es nesesario que solo funcione el efecto o hay que tener metodos ludopatia(), tacano_extremo(), cliente_recurente(), suerte_principiante() 

![image](https://user-images.githubusercontent.com/68141520/162553851-14ccbd2d-d47c-4646-ab5d-54e70dcf8d90.png)

**Comment by Gsalinas1506** [comment]
Hola!
Para obtener el puntaje en el recuadro amarillo es necesario que las acciones especiales de cada jugador se implementen a nivel de código. Por ejemplo, para el caso del ludópata debería implementarse que cada vez que este realice una apuesta su ego y suerte aumenten, y que en caso de perder un juego su frustración aumente. Ahora, el cómo lo implementes es decisión tuya, pero lo importante es que esto se encuentre en tu código.

Ahora bien, para el puntaje del recuadro blanco este se asignará si las acciones especiales de cada jugador pueden verse reflejadas en la ejecución. Siguiendo con el ejemplo anterior, si después de realizar una apuesta y perder como ludópata puedo visualizar estos cambios en el programa, el puntaje se asignará completo.

Espero haber respondido tu duda!
Exito con la tarea! 🎲️🃏️
