### ISSUE TITLE
Problema al leer archivos: open(file, "a")

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#107]
cuando intento editar el archivo de "Seguidores.csv", me encuentro con un problema que me indica que el archivo "no es leible"

import os
ArchivoSeguidores = os.path.join("seguidores.csv")

with open(ArchivoSeguidores, "a") as archivo:
    for linea in archivo:
        print(linea)

me sale el siguiente error: Exception has occurred: UnsupportedOperation
not readable

**Comment by KnowYourselves** [comment]
Hola @felipehen!

Esto se debe a que el modo de lectura `"a"` es **estrictamente para escritura**, por lo cual no permite lectura. Si tu objetivo es leer y escribir sobre un archivo a la vez, te recomiendo investigar respecto al modo de lectura `"a+"`.

Éxito!
