### ISSUE TITLE
Duda property en atributos "privados"

### ISSUE THREAD

**Issue by diegocostares** [IIC2233/Syllabus#107]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola después del feedback de la AF1 me quedo una duda con respecto al uso de guion bajo a la hora de hacer un setter. En los contenidos se utiliza el __ para el setter y el setter (ej: self.__personas), pero en los comentarios que me hicieron me dijeron que no tenía que ser así... por lo que me queda la duda, ¿Cuál es la forma correcta?

**Comment by carmebe** [comment]
Hola, no sé si es este tu problema, pero en los **atributos de la clase** se utiliza el doble underscore ``__`` para **privatizarlos**, y al momento de crear la *property*, **lo defines sin esto**, pero este debe retornar valores que modifiquen ``self.__personas`` internamente. Para el setter, debes establecer ``@nombre_property.setter`` de esta forma:
```python
...
def __init__(self, *args, *kwargs):
    self.__personas = 0

@property
def personas(self):
    return self.__personas

@personas.setter
def personas(self, valor):
    if valor > 0 and valor <= 100
        self.__personas = valor
...
```
Ojo que en esa actividad, algunos atributos estaban **protegidos** y no privatizados (solamente tenían un underscore ``_``), por lo que igual se podían "llamar" afuera de la clase (eso ocurría en la clase Mascota si no me equivoco).

Espero que te haya ayudado, saludos!

**Comment by tqmbanados** [comment]
Hola @diegocostares ! Pudiste solucionar tu duda con el comentario de arriba? Es una respuesta bastante buena jejeje. Si no, feliz te ayudo más!

**Comment by diegocostares** [comment]
@tqmbanados super claro! Muchas gracias
