### ISSUE TITLE
No me funciona la excepción ConectionResetError

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#1070]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Tengo una duda desde con respecto a esta excepción. Tengo implementado en escuchar_cliente del servidor un 
```
try:
     while True:
          socket, _ = socket.recv(4)

except ConnectionResetError:
       print()
```
que es como el mismo código de los contenidos y de la AF05. Sin embargo, cuando cierro el programa del cliente me queda en un loop (por el while True) imprimiendo que no puede hacer recv(). 
Se supone que debería tirarme la excepción y no cacho por qué no me funciona. En la AF05 la ayudante a la que le pregunté me dijo que estaba bien que el while estuviese adentro de la excepción entonces no sé qué puede ser

graciasss

**Comment by cristozille** [comment]
Hola! ¿Qué mensaje aparece impreso en la terminal cuando no puede hacer recv()?

**Comment by tomytable** [comment]
Hola, me pasa lo mismo, estai ocupando Mac?

**Comment by denisseleiva** [comment]
@cristozille me estaba apareciendo un mensaje de error en la decodificación, al quitar ese print() no me imprime el loop, pero no entiendo por qué si no hay comunicación el while sigue corriendo 🤔
@tomytable siiiiiii tengo mac, no tengo windows para probar si ese es el problema uwu
Quizás si tienes windows @cristozille y hago push y lo corres y podríamos cachar si es algo con los mac 🤷‍♀️

**Comment by cristozille** [comment]
Eso! Has push :). Yo tengo mac pero no me había aparecido un error similar. Voy a probar unas cosas y te aviso.

**Comment by denisseleiva** [comment]
okaaa, ahí hice push 😁

**Comment by tomytable** [comment]
@cristozille yo igual pushee por si lo puedes mirar porfa

**Comment by cristozille** [comment]
Hola @denisseleiva! Por alguna razón en algunas versiones de Mac en vez de levantar el error al desconectar el socket se queda recibiendo strings vacíos, por lo que se queda pegado en el while True. Una forma de manejar esto es levantando la excepción de la forma:

if mensaje_bytes = b"":
    raise ConnectionResetError

Lo probé y me funcionó bien :)

**Comment by denisseleiva** [comment]
Bacaaaan, gracias!!!!!!!!! 😁😁
