### ISSUE TITLE
Uso de except/try T03

### ISSUE THREAD

**Issue by jaimecoloma** [IIC2233/syllabus#1070]
Hola, si bien siempre se ha dicho que el uso de expections es mala práctica, en el material de networking se utilizan mucho estas para abordar errores tipo "ConnectionError" y  que no se caiga el programa.
Dado que se pide en la tarea que ante un cierre repentino del server o el cliente debemos plantear distintos escenarios. ¿Como se espera que hagamos eso si se considera una mala práctica?
Quizás entendi mal y confundo librerías pero prefiero preguntarlo, Gracias!

**Comment by Drpinto1** [comment]
¡Hola!

El uso y manejo de excepciones **no es una mala práctica**, es una herramienta útil que es parte de los contenidos del curso, por lo que tienen permitido utilizarla.

Lo que se considera mala práctica es el **mal manejo de excepciones**, en particular el uso de `except` sin especificar la excepción que se quiere capturar o su equivalente `except Exception`. Lo anterior es una mala práctica puesto que estas sentencias capturarán cualquier excepción que se levante, por lo que podrían eventualmente capturar excepciones inesperadas y aplicar un comportamiento erróneo ante esto.

Un ejemplo simple de lo anterior sería el siguiente código:

```
def division(dividendo, divisor):
   '''Recibe los strings de dos números y los divide
   Si el divisor es 0, retorna None
   '''
   try:
      resultado = int(dividendo) / int(divisor)
   except:
      resultado = None
   return resultado
```

En este programa, esperamos que al intentar dividir por cero se levante un `ZeroDivisionError`, para luego atraparlo en el `except` y así obtener el `None` que queremos retornar, sin embargo si, por ejemplo, se ingresan valores inesperados, el `except` atrapará estos casos y generará un resultado `None` cuando no corresponde. Concretamente, al hacer algo como `division('1.2', '0.2')` obtendremos `None` cuando esto es una división deberíamos poder calcular.

Espero que esto te aclare un poco más el uso de excepciones, pero estaré atento a la issue por si te quedan dudas (o a cualquiera que lea la issue :D)
¡Saludos! :full_moon_with_face:

**Comment by jaimecoloma** [comment]
Yaa perfecto gracias!
