### ISSUE TITLE
Duda en clase logica en AF5

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#1071]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

En la AF5 en *servidor/logica.py* en la clase *logica*, abajo del __init__ dice: 'Comparte lista con Servidor (tienen la misma lista_jugadores)', no entiendo bien a que se refiere esto. Al editar la lista en lógica también se edita en el servidor (son el mismo objeto) o se refiere a que son 2 objetos equivalentes pero distintos.

**Comment by cristozille** [comment]
Hola! Son dos objetos distintos pero que contienen los mismos jugadores, por lo tanto son equivalentes. :)
