### ISSUE TITLE
Clientes por sobre el máximo

### ISSUE THREAD

**Issue by vWing7** [IIC2233/syllabus#1071]
En mi programa busco conectar el servidor con el cliente apenas se abra este último,para mandar las imágenes, mi pregunta es, ¿dejo que solo los primeros n clientes, con n siendo el número de jugadores que se requiere, se conecten con el servidor?, independiente de si han ingresado o no al lobby aún.

Gracias

**Comment by gatochico** [comment]
Hola! 

Deberías dejar que todos quienes corran el cliente se conecten al servidor, sin importar que sean más que el número máximo de jugadores. Algunas razones para esto son: 

- La restricción de jugadores máximos aplica sólo para entrar a la sala de espera y posteriormente al juego, y no para correr el programa en general
- El servidor es el que les debe avisar si pueden entrar o no, por lo que necesitan conectarse para recibir la respuesta
- Piensa en los casos bordes: supongamos máximo 2 jugadores. Se conectan dos clientes y uno ingresa a la sala de espera, pero el otro se queda en la ventana de inicio por x razon. Si llega un tercero, este debería poder entrar a la sala de espera, pues todavía quedan cupos.

Saludos!
