### ISSUE TITLE
gitignore archivo python

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2233/syllabus#1072]
Hola! Cómo se pone el archivo generados_de_mazos.py en el gitignore? busqué y no entendí bien como se hace para no ignorar todos los archivos .py 😅

**Comment by jeschuwirth** [comment]
Hola @beatrizacuna,

En la base, el archivos .gitignore ignoran los archivos escritos exactamente igual, un ejemplo de archivo .gitignore contiene:

> Enunciado.pdf
> archivo_a_ignorar.py

Además git te da la facilidad de utilizar *.(extensión), por ejemplo *.csv para ignorar todos los archivos con la misma extensión.

Espero que con esto quede clara la respuesta, sino puedes seguir comentando :)

**Comment by beatrizacuna** [comment]
Muchas gracias!!
