### ISSUE TITLE
Protocolo envío de mensjaes

### ISSUE THREAD

**Issue by isidorabecker** [IIC2233/syllabus#1072]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, para enviar mensajes es necesario hacerlo con json o pickle, o basta con codificar y transformar lo que se desee enviar en bytes ???
[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by lucasprato** [comment]
Hola @isidorabecker!

No es requisito, pero es recomendable. A medida que avances en la tarea, verás que te podría ser útil enviar estructuras de datos como diccionarios, tuplas o listas. En este sentido, serializar/deserializar con json o pickle te podría ser de muchísima ayuda. Ten en consideración que independientemente qué envíes, siempre debe seguir el protocolo que se muestra en el usuario.

Éxito en la tarea!

**Comment by isidorabecker** [comment]
Oki, si uso pickle no hay problema cierto ? aunque no sea el método más seguro.

**Comment by lucasprato** [comment]
Tanto json como pickle son válidos!
Saludos
