### ISSUE TITLE
Personalizar ventanas

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2233/syllabus#1073]
Perdon la pregunta tonta pero que metodo se usa para cambiarle el color a las cosas como el fondo de la ventana, los botones o el texto? me leí la documentacion pero no la logro entender :(

**Comment by lily416** [comment]
Primero que todo, no es una pregunta tonta c: 
Está super bien que preguntes después de haber investigado y no haber encontrado la respuesta :D

---

Para personalizar los elementos de una ventana se usan [_Qt Style Sheets_](https://doc.qt.io/Qt-5/stylesheet.html). A fin de cuentas, es una forma de agregar estilo a los componente basado en CSS (un mecanismo para darle estilo a las páginas web).

Entonces, para usar las _Qt Style sheets_, hay dos formas:
1. ### **Hacerlo directamente en tu código de python:**
   Para esto, debes utilizar el método `setStyleSheet()` y pasarle como _input_ un string con los cambios en el estilo que quieras realizar.
   
   ![image](https://user-images.githubusercontent.com/26393515/85334291-fcfa7800-b4a8-11ea-8f81-cd7db66d63c0.png)

1. ### **Hacerlo usando QtDesigner:**
   Para esto, debes hacer click derecho en el elemento que quieres editar, seleccionar “Change styleSheet” y te aparecerá una ventana donde puedes ingresar el estilo del elemento.
   
   ![image](https://user-images.githubusercontent.com/26393515/85333963-81003000-b4a8-11ea-9f2e-044b75b158ec.png)
   ![image](https://user-images.githubusercontent.com/26393515/85333941-747bd780-b4a8-11ea-8288-418054bda01c.png)


Espero que te sirva y cualquier duda que tengas no dudes en preguntar c:
Saludos y éxito en la tarea 👋🌈

**Comment by maggiemunoz** [comment]
muchisimas gracias!! necesitaba verlo escrito jajajaja :)

**Comment by maggiemunoz** [comment]
otra pregunta chica, como se hace para que te queden en lineas separadas pero que sea la misma linea? porque si apreto enter se me separa

**Comment by lily416** [comment]
¿Cuándo lo haces directamente en tu código?
Para crear strings de múltiples líneas, basta con usar comillas triples (‘‘‘ ’’’).

**Comment by maggiemunoz** [comment]
sii, gracias!
