### ISSUE TITLE
No llega información al cliente

### ISSUE THREAD

**Issue by BFry712** [IIC2233/syllabus#1073]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! tengo problemas con el envio de información desde el servidor y cliente. No me tira ningun error pero el nombre de usuario no llega al cliente.(Subí el codigo a mi repo)

**Comment by rodrigobj99** [comment]
Hola @BFry712 
Revisando tu código me di cuenta que el nombre de usuario no llega al cliente porque nunca es enviado desde el servidor. Esto ocurre porque tu método codificar en ningún parte codifica el mensaje, solo utiliza el largo de este, por lo tanto lo único que envía son números y no el mensaje mismo (en este caso el nombre de usuario).

Espero te sirva, cualquier cosa me avisas.

**Comment by BFry712** [comment]
Hola @rodrigobj99 !
No entiendo muy bien si despues del protocolo de envio de información es necesario codificarlo en json o no :c Lo que estaba tratando de hacer era enviar la info en bytes como: largo mensaje+ bloque 1+ 60 bytes y asi.

**Comment by rodrigobj99** [comment]
Hola @BFry712 !
Lo que el protocolo establece es que ademas de codificar el largo del mensaje y el número de bloque, también debes codificar el mensaje (usando **UTF-8** para el caso de _strings_), el método que uses para esto queda a elección tuya. 
Por otra parte si alguno de estos chunks es menor a 60 bytes lo deberas rellenar con _bytes_ 0 (b'\x 00') hasta alcanzar ese largo.

Espero te sirva, cualquier cosa me avisas.
