### ISSUE TITLE
Error utilizando json.loads()

### ISSUE THREAD

**Issue by MagyarSplit** [IIC2233/syllabus#1074]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! al utilizar json.loads me tira el siguiente error:

![error_json](https://user-images.githubusercontent.com/69654313/100285866-6860de00-2f50-11eb-9768-a9d6c1d1f626.png)

Como se puede apreciar, el cliente está recibiendo un diccionario el cual tiene como key "nombre_usuario" y como valor, su nombre.  Luego verifico el tipo de dato (str) y finalmente hago json.loads(mensaje_recibido).

Saludos!

**Comment by matiasmasjuan** [comment]
Hola @MagyarSplit !

Puedes hacer un **push** a tu repo porafavor? A simple vista no es fácil saber cómo estas serializando y des-serializando el mensaje :sweat_smile: .

Saludos!

**Comment by MagyarSplit** [comment]
De inmediato! muchas gracias @matiasmasjuan

**Comment by MagyarSplit** [comment]
@matiasmasjuan  ahí lo subí, perdón la demora

**Comment by matiasmasjuan** [comment]
Hola @MagyarSplit !

Lamento la demora :disappointed:. Me demoré más de lo que pensaba en encontrar el error.

En general el protocolo que realizas está bien. Sin embargo, al momento de agregar los *bytes* **ceros** (**b'\x00'**) y luego de **enviar** el mensaje, hacer un **decode** y luego un **json.loads(mensaje)**, existe un error debido a que *json* no se maneja muy bien con estos *bytes* ceros (b'\x00').  Por lo tanto, te sugiero hacer un ```mensaje.strip(b'\x00')``` **antes** de hacer un *decode()* para que luego el *json* no tenga problemas con *deserializar* el mensaje.

Avísame en caso de cualquier duda!

**Comment by MagyarSplit** [comment]
Lo voy a intentar, muchas gracias! @matiasmasjuan

**Comment by MagyarSplit** [comment]
@matiasmasjuan Lo intenté pero me sigue arrojando el mismo error :(
