### ISSUE TITLE
Interfaces gráficas: sólo se muestran los labels si las agrego a un layout

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#1074]
Hago las ventanas sin Indesign, y cuando no agrego un layout uso move() nomás, y siempre me ha funcionado.
Pero ahora no me aparecen las cosas si uso move(), sólo aparecen si las agrego a algún layout horizontal o vertical! Es muy raro porque nunca me había pasado antes, pero no sé por qué pasa ahora! En internet no me sale nada útil. Sé que parece tonta mi duda pero es demasiado importante para organizar la ventana ! Gracias!

**Comment by matiasmasjuan** [comment]
Hola @jirarrazaval !

¿Cómo estas definiendo tus ***QLabels***? ¿Estás segura de agregar el parámetro ```self``` dentro de **QLabel()**?

Recuerda que no es lo mismo definir:

```python
self.mi_label = QLabel()
```

que

```python
self.mi_label = QLabel(self)
```

Saludos y avisame si esto soluciona el problema!

**Comment by jirarrazaval** [comment]
Siii era esoo que pava jajaja gracias!
