### ISSUE TITLE
Error en Actividad F06

### ISSUE THREAD

**Issue by rldelafuente** [IIC2233/syllabus#1075]
Hola! Tengo un error que no puedo arreglar de la actividad formativa 06, me sale:

`ERROR: No se pudo conectar a localhost`

Intenté cambiar en "main.py" de "cliente" el HOST y PORT, pero aun persiste el mismo error.

Pd: Subí mi código actualizado a git.

Gracias de antemano!

**Comment by KnowYourselves** [comment]
Hola @rldelafuente!

Por lo que veo el PORT de tu servidor es distinto al de tu cliente, debiesen ser iguales. Prueba con eso y cuéntame que tal!

**Comment by rldelafuente** [comment]
Hola! 
Modifiqué el tema del PORT, pero continua el mismo error :(

**Comment by KnowYourselves** [comment]
Probaste con valor de puerto mayor a 8000?
