### ISSUE TITLE
El cliente no conecta en VS, solo en el terminal de mi pc

### ISSUE THREAD

**Issue by Constanzape** [IIC2233/syllabus#1075]
Hola, 
Cuando corro mi programa en Visual Studio no conecta el cliente, el servidor funciona bien, pero luego cuando corro el main del cliente no arroja nada. Cuando hago lo mismo desde el terminal de mi pc muestra la tabla perfectamente. Alguien que me pueda ayudar con las configuraciones de mi VS?

**Comment by EduardoIllanes** [comment]
Hola @Constanzape !
Estuve probando tu código  y si me conecta el cliente desde vscode 🤔 . ¿Estas segura de que estas corriendo ambos main con vscode desde sus directorios respectivos?. Puede ser que estés utilizando una misma consola para ambos y que no te hayas dado cuenta. Quedo atento a tu respuesta 🙌

**Comment by Constanzape** [comment]
Siii, estoy segura. Lo hago con terminal del Mac y con Idle y no tengo problema, pero cuando lo hago con vscode no me arroja nada. Agradecería si me pueden ayudar a revisar los ajustes de mi vs :(

**Comment by EduardoIllanes** [comment]
Mmmm me parecería muy raro que fuera por los ajustes de vscode. Si me puedes adjuntar una foto de lo que te aparece en ambas terminales (cliente y servidor) al correrlos de vscode. Quiero comprobar algo antes de pasar a revisar los ajustes

**Comment by Constanzape** [comment]
Ahora me funciono!!!! pero tuve que escribir en el terminal de vscode:
python client/main.py

porque si simplemente lo corría con el botón que parece un play (run) se volvía automáticamente a la terminal donde corrí el servidor. No se porque me pasará eso
Gracias!

**Comment by EduardoIllanes** [comment]
Genial ! 😄 que tengas que escribir `client/main.py` se debe a que vscode no esta corriendo en el directorio cliente. Éxito con tu tarea 🚀
