### ISSUE TITLE
Problema al mostrar Ventana de Espera

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#1076]
Acabo de lograr hacer que me acepte o no el nombre de usuario, por lo cual pongo que se cierre la ventana de Inicio. posteriormente, creo la Ventana de espera, del mismo método, que cree la Ventana de Inicio (guardándola como atributo en el cliente), pero inclusive cuando esta en el __init__, tiene el show(), no se muestra al instaurarla.

**Comment by KnowYourselves** [comment]
Hola @felipehen!

Sube tu código, avísame y veo que está pasando.

**Comment by felipehen** [comment]
hola! el código ya esta subido.

**Comment by KnowYourselves** [comment]
El error se debe a que estas intentando hacer `show` desde un thread. Esto solo no es valido. Si quieres hacer `show` de la ventana, en el init debes asignar una señal que haga exactamente eso.

**Comment by felipehen** [comment]
ahhh ya perfecto, voy a hacer eso, muchas gracias!!

**Comment by felipehen** [comment]
> 
> 
> El error se debe a que estas intentando hacer `show` desde un thread. Esto solo no es valido. Si quieres hacer `show` de la ventana, en el init debes asignar una señal que haga exactamente eso.

sigue sin poder funcionarne. e intentado crear una funcion que muestre las ventanas, y agregarla (mediante señales) a ambas ventanas, pero sigue sin funcionar en la ventana de espera

**Comment by KnowYourselves** [comment]
Podrías subir tu código nuevamente para ver?

**Comment by felipehen** [comment]
e subido todos mis cambios como cada 1 hora, pero cambie seriamente la forma en la que intentaba mostrar la ventana, de hecho, abri otro issue con un problema que me surgio despues.

pd: ya subi los archivos
