### ISSUE TITLE
main cliente

### ISSUE THREAD

**Issue by Mario-uc** [IIC2233/syllabus#1077]
Me abre el main (y funciona) si lo abro desde el visual studio, pero no si lo abro con python (me aparece una ventana en negro durante menos de 1 segundo y se cierra) me gustaría saber porq ocurre esto. Es que lo necesito para probar con más clientes

**Comment by DCCollao** [comment]
Hola @Mario-uc!

¿A qué te refieres con abrir desde visual studio? ¿Utilizas el botón para ejecutar código?
¿A qué te refieres con abrir con python?

Quedo atento!

**Comment by Mario-uc** [comment]
osea ejecutarlo desde visual studio, y el que no me funciona es abrirlo con python (cuando uno selecciona el archivo y coloca "abrir con python")

**Comment by DCCollao** [comment]
Para poder abrir varias instancias de cliente debes ejecutar tu código **por consola**.
Si quieres probar tu programa con 3 clientes, deberás abrir 4 consolas y ejecutar una vez el código correspondiente al servidor, y 3 veces el correspondiente a cliente.

Avísame qué tal.

**Comment by Mario-uc** [comment]
Abriéndolo directamente no me deja, tengo que abrir el idle de python primero o abrirlo de visual studio. Así que por ahora lo haré así. Es que para la act formativa 6 podía ejecutar directamente los cliente haciendo click en los archivos

**Comment by CataSudo** [comment]
Donde tienes tu carpeta del repositorio? Esta en el workspace??

**Comment by DCCollao** [comment]
Hola @Mario-uc!

Disculpa lo tarde de la respuesta.

Para ejecutar tal como ejecutaremos los ayudantes tu tarea, debes hacerlo a través de la consola de comandos. En windows tienes la opción de usar CMD o PowerShell, mientras que en linux o en mac utilizarás la bash. Dentro de esta consola, debes navegar utilizando el comando `cd` hasta la carpeta _root_ de tu tarea, en este caso, `T03`, de esta forma:

![image](https://user-images.githubusercontent.com/37167447/85915521-4551c700-b816-11ea-8bde-67118172b237.png)
Al abrir mi consola, inicia en el directorio `Diego`. En mi caso, mi carpeta de la tarea 3 está en mi escritorio(`C:\Users\Diego\Desktop\T03`) Por lo tanto, utilizando `cd`, navego hasta ella:
![image](https://user-images.githubusercontent.com/37167447/85915561-821dbe00-b816-11ea-9149-3929c0a63aee.png)
![image](https://user-images.githubusercontent.com/37167447/85915572-9497f780-b816-11ea-8966-bdcb2eb418ad.png)

Una vez acá, depende de lo que quieras hacer. Si quieres ejecutar el `main.py` del servidor, debes correr el comando `python servidor/main.py` o `python3 servidor/main.py` en caso de mac.

En el caso de que quisieras correr el archivo `main.py` correspondiente al cliente, deberías correr el comando `python cliente/main.py` o `python3 cliente/main.py` en caso de mac.

De esta forma, si quieres correr varias instancias de tu programa, basta con que abras varias terminales de comandos 😄.

P.D:
Lifehack:
Para abrir una consola directamente dentro de una carpeta puedes utilizar el explorador de archivos de Windows, y en la barra de dirección escribir `cmd`. Esto hará que la cmd se abra directamente en la carpeta que tienes abierta en el explorador.
![image](https://user-images.githubusercontent.com/37167447/85915622-27389680-b817-11ea-8cc3-1b613f81de8e.png)
<br />
![image](https://user-images.githubusercontent.com/37167447/85915626-3586b280-b817-11ea-8efd-b1eb2091f23e.png)
<br />
![image](https://user-images.githubusercontent.com/37167447/85915635-40414780-b817-11ea-9fe4-9c5406490a27.png)

Quedo atento a cualquier duda!
