### ISSUE TITLE
Problema al correr servidor

### ISSUE THREAD

**Issue by sofiaolmedos** [IIC2233/syllabus#1077]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Mi problema es que al correr el servidor como que se cierra sin lanzar ningún error y no espera a que se conecten los clientes. Me dí cuenta que corre hasta llegar a ```self.socket_servidor.accept()```.
En una issue (#1039) alguien tuvo el mismo error pero al final creo que se le arregló solo o algo, pero yo he corrido mi código muchas veces y todavia no se arregla :c

**Comment by Juampisaez** [comment]
Hola @sofiaolmedos,
Viendo tu codigo me percate que estas haciendo un `daemon = True`, lo cual seria la razon de que el Thread termine de ejecutarse (a mi parecer no es necesario), acuerdate que el Thread debe seguir escuchando hasta que termine el programa o se caiga de forma abrupta.

Espero haberte ayudado, cualquier cosa quedo atento.

**Comment by sofiaolmedos** [comment]
@Juampisaez es que lo puse asi porque en la AF05 lo hicieron asi, pero la verdad es que si no lo hago daemon corre sin problemas 😄

**Comment by Juampisaez** [comment]
Mmm.. Desconozco en verdad porque puede tirar error al colocar el daemon, dejame averiguar y te respondo.
