### ISSUE TITLE
Editar Generador de Mazos

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#1078]
Hola, la función generador de mazos puede ser editada?

**Comment by DCCollao** [comment]
Hola @CataSudo 
Esta pregunta debería ir en donde la hiciste en primer lugar, para no tener varias issues del mismo tema. Aunque la dejes como comentario, nosotros nos fijaremos en que está, pues tenemos un bot que nos avisa de esta situación. 
Respondí tu pregunta en la otra issue, si tienes más dudas por favor comenta allá!

Éxito
