### ISSUE TITLE
Cambio sala de espera a sala de juego y cantidad de jugadores

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2233/syllabus#1078]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! Tengo una duda puntual, ocurre que se señala que la partida empieza cuando se unen los jugadores necesarios, pero ocurre que cuando se añade el último se iniciaría automaticamente la sala de juego y no se mostraría en pantalla, ¿estaría bien esto? ¿Esta transición daría lo mismo? Lo otro no tengo claro del enunciado si puedo asumir que la cantidad de jugadores está predefinida por el parámetro, a lo que voy es que tengo predefinido cuantos jugadores pueden ingresar a la sala de espera para iniciar la partida y no depende de cuantos se unen. Con esto, puedo suponer además que un jugador no se ingresará al servidor solo porque la partida esté iniciada y no porque ya estén los jugadores máximos, ya que al unirse el último necesario, se inicia de inmediato la partida ¿o me equivoco? 
Eso es todo 😄, gracias de antemano!

**Comment by matiasmasjuan** [comment]
Hola @Jamesmoreno21 !

Responderé tus dudas en orden:

1. **Sí, está bien**. La transición como dices daría lo mismo. Como te habrás dado cuenta, apenas se **conectan** los **jugadores necesarios** **empieza** la partida, por lo que el **tiempo** en que el último jugador está a la sala de espera es casi **instantáneo**, ya que inmediatamente se abre la sala de juego. De todas formas, este último jugador igual tiene que **entrar** a la sala de espera, a pesar de que su tiempo ahí sea mínimo.
2. Efectivamente, ambas formas de verlo son correctas. Lo importante es que si ya **empezó** la partida, si otros clientes se **conectan** con el servidor e **intentan** entrar a la **sala de espera**, la **solicitud** deberá ser **rechazada**, advirtiendo al usuario.

Espero haber respondido a tu pregunta, y mucho éxito con la tarea! :smile:

**Comment by Jamesmoreno21** [comment]
Ya, entiendo, muchas gracias! Ocurre que si pongo breakpoints en VS Code paso a paso se ve que se abre la sala de espera pero se cierra de inmediato, así que gracias por la aclaración 😄
