### ISSUE TITLE
Cambio de lineas recorreción.

### ISSUE THREAD

**Issue by pabloist** [IIC2233/syllabus#1079]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, si en el README de la tarea habia incluido cambios de línea, en la recorrección tengo que incluirlos también o se dan por hechos? el máximo de cambio de lineas entre ambos es 20 o solo las de la recorreccion?

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by gatochico** [comment]
Hola @pabloist !

Las 20 líneas cuentan entre las del README y las que pongas en la recorrección (si cambiaste 5 líneas en el README, podrías cambiar hasta 15 en la recorrección).

Saludos ✨

**Comment by conyfernandezt** [comment]
Hola! Para la tarea anterior despues de la correcion, fue posible hacer cambio de lineas. Para la T02, se va a poder hacer eso tambien?

**Comment by gatochico** [comment]
@conyfernandezt  Puedes pedir cambio de líneas mediante el form de recorrección (recuerda explicar qué cosas de tu tarea se arreglan/mejoran con este cambio, y que esto tiene descuento asociado).
