### ISSUE TITLE
Modulo de juego

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#1079]
No me queda claro la forma de jugar, tipo yo tengo un usuario y este tiene sus cartas; tambien debo poder jugar por los otros clientes? O su comportamiento es aleatorio.

**Comment by DCCollao** [comment]
Hola @CataSudo 

Al abrir varias instancias de cliente, lo que estás haciendo es simular tener una partida donde jueguen más personas, pero dentro de tu mismo computador. Por lo tanto, también debes poder jugar por los otros clientes en su respectiva ventana.

El comportamiento aleatorio al que te refieres se incluye en el bonus Forever Alone, para el que necesitas tener solamente una instancia de cliente corriendo en tu computador.

Espero haber aclarado tu duda!
