### ISSUE TITLE
Interacciones de los métodos de la clase Tablero con las piezas explosivas.

### ISSUE THREAD

**Issue by maromero-21** [IIC2233/Syllabus#108]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

¿Los métodos de la clase Tablero que interactúan con las piezas dentro de este, están interactuando con una _**instancia de la clase Pieza**_ o su formato **_str_**?
Por ejemplo el método  **_piezas_explosivas_invalidas_** al interactuar con una pieza necesitamos acceder a sus atributos como el alcance o el tipo o podemos usar la propia cadena str y obtener esa información desde ahí?

**Comment by Dominique236** [comment]
Hola! 
Como se menciona en el enunciado de _piezas_explosivas_invalidas_, y la mayoría de los métodos/_properties_ de la clase Tablero, se "**utiliza el tablero guardado como atributo**" y, nuevamente por enunciado, este atributo es una **lista de listas de _strings_**, por tanto eso es lo que estás utilizando. Por lo mismo, en el ejemplo del enunciado, solo con su forma de lista de listas de _strings_ es posible contar la cantidad de piezas explosivas que no son válidas. 
Cuéntame si esto resuelve tu duda 😊

**Comment by maromero-21** [comment]
Muchas gracias! Me quedó clarísimo
