### ISSUE TITLE
Recursion en import

### ISSUE THREAD

**Issue by tocococa** [IIC2233/syllabus#108]
Puedo importar recursivamente modulos? Digamos que en a.py hay un metodo A, que necesita un método B de b.py para funcionar, pero a su vez B necesita de A para funcionar.

Tiene sentido o estoy enredandome demasiado?

**Comment by jeschuwirth** [comment]
Hola @tocococa,

Se suele recomendar la separación funcionar de tus archivos para este ramo, es decir, colocar todas las funciones o clases que interactuan fuertemente entre ellas en el mismo archivo.

Si tienes dos funciones que se necesitan entre ellas, entonces probablemente deban estar en el mismo archivo. Tener dos módulos que se importan entre ellos no siempre va a levantar un error en python pero es una mala práctica y trae problemas en varios otros lenguajes.

Te recomiendo colocar las funciones que se necesitan entre ellas en el mismo.

Suerte!

**Comment by tocococa** [comment]
Oka, gracias!
