### ISSUE TITLE
\volver y \salir

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#108]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### \salir debe solamente funcionar para chats grupales, o puedo hacer que si un usuario escribe \salir haga lo mismo que \volver en un chat personal?

**Comment by RafaelEdwards** [comment]
Holaa!

Tal como dice en el enunciado, ABANDONAR_FRASE solo debiera funcionar en los chats grupales, en cambio VOLVER_FRASE funciona tanto para los grupales como personales. Por lo que si dentro del chat personal ingresas ABANDONAR_FRASE, este input se debiera manejar como cualquier otro mensaje que pueda enviar el usuario y no como una palabra clave

Espero haberte ayudado y suerte con la tarea!

**Comment by fernandosmither** [comment]
Solved
