### ISSUE TITLE
Duda acción consumir de Bebestible

### ISSUE THREAD

**Issue by jlizamajara** [IIC2233/Syllabus#108]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo una duda con respecto a lo que hace la acción consumir de la entidad bebestibles 🧃, cuando se refiere a que debe informar por consola cada uno de los beneficios que se le apliquen al jugador indicando su característica afectada y magnitud ¿con beneficio se refiere solo a aquellos que generan cambios positivos en el jugador, como disminuir frustración? ¿o también debería considerar los efectos negativos, como aumentar frustración?
Muchas gracias de antemano!

**Comment by Gsalinas1506** [comment]
Hola! 
En consola deben mostrarse todos los atributos afectados por el consumo del bebestible, ya sean positivos o negativos, ya que se debe informar al jugador de qué es lo que está ocurriendo con las stats de su personaje.

Éxito con la Tarea! 🎲🃏
