### ISSUE TITLE
Atom no lee archivos

### ISSUE THREAD

**Issue by jgespinosa10** [IIC2233/Syllabus#108]
Atom no lee los archivos csv pero idle si. ¿Qué puedo hacer para que atom los lea?

**Comment by vijuarez** [comment]
Puedes especificar más el problema? El código de Python se cae al intentar abrir archivos CSV o cuando intentas abrir archivos CSV con Atom algo falla?

Saludos!

**Comment by jgespinosa10** [comment]
Al correr el programa en que abro los archivos, desde atom me indica que no existe tal archivo. mientras que desde idle si funciona

**Comment by vijuarez** [comment]
Como es la estructura del proyecto en Atom? Tengo entendido que si el script de python y el archivo CSV no estan en la parte más alta puede pasar que Atom intente ejecutar el script desde la parte más alta y por eso no encuentre el archivo.

Saludos!

**Comment by jgespinosa10** [comment]
perdón, pero no entiendo. A que te refieres con estructura del proyecto?

**Comment by vijuarez** [comment]
Ahora mismo no tengo Atom a mano (o sacaría fotos para hacerlo más claro :/), pero a la izquierda de la pantalla debería estar la estructura de proyecto. Es el 'mapa' donde estan las carpetas y archivos que conforman el proyecto que tienes abierto en Atom. 

http://static.filehorse.com/screenshots/developer-tools/atom-screenshot-02.png
(foto que me robe)

A la izquierda puedes ver todos los archivos que conforman el proyecto (la carpeta FileHorse.com, todas las carpetas que contiene y así sucesivamente), lo cual es la estructura del proyecto. Los archivos (el .py y el .csv) deberian funcionar bien cuando estan en la carpeta de más arriba (en la foto sería FileHorse.com), no en una de más abajo (digamos, si estuvieran en la carpeta system del ejemplo debería fallar)

Ojala eso solucione el problema, saludos!

**Comment by GustavPrudencio** [comment]
No estoy seguro si responde tu pregunta pero atom es solamente un editor, te recomiendo que pongan en una carpeta tus archivos .py y los cav, luego a esa misma carpeta dale boton derecho y abrir con atom, eso deberia bastar para poder ver los csv
