### ISSUE TITLE
usuario elige civilizacion

### ISSUE THREAD

**Issue by mjgarrido1** [IIC2233/syllabus#108]
Hola!
el usuario puede elegir cualquier civilizacion?
tengo la duda porque al principio dice que debemos ayudar al "gran polea"
es para sumarlo como interaccion a la consola

**Comment by gatochico** [comment]
Hola!

Si, el usuario debe poder elegir a cualquiera de la tres civilizaciones para jugar. La parte del **Gran Polea** es sólo para hacer más entretenido el enunciado :cat:

Saludos!
