### ISSUE TITLE
Dudas recurso_id e incendios

### ISSUE THREAD

**Issue by pcsalvo** [IIC2233/Syllabus#108]
Al momento de agregar usuarios a la base de datos, si este no es de la anaf se le debe asignar un 'recurso_id', este puede estar repetido? O debo comprobar si este recurso ya le pertenece a otra persona?
Y otra cosa que no me ha quedado bien clara de las otras issues, tengo que guardar la fecha y hora en que se apago el incendio en el archivo 'incendios.csv'? O se va calculando constantemente en base a las estrategias creadas?

**Comment by hanavarrete** [comment]
@pcsalvo debes verificar que el id no esté repetido sino tendríamos  dos pilotos con el mismo avión. Sobre tu segunda pregunta, no debes guardar los datos en incendios.csv sino que tu programa simula y reconoce si el incendio está apagado o no.

**Comment by ranieto** [comment]
@hanavarrete ¿eso no contradice lo que se dijo en #49 de que un recurso puede estar asignado a más de un usuario?

**Comment by hanavarrete** [comment]
@ranieto @pcsalvo Error mío, consideraremos correcto lo discutido en #49. Saludos!
