### ISSUE TITLE
backend y servidor

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#1080]
Tengo una dudad con la ubicación de las "reglas" del juego. Por ejemplo, si escribo un nombre de usuario inválido este tiene que enviarse al servidor y volver con al respuesta si es válido o no? o puede en el backed del cliente analizar los nombres de usuario y enviar al servidor solo los que ya sirven? No se si se entiende. Es más si debe existir un backed en los clientes o toda regla va en el servidor. saludos

**Comment by KnowYourselves** [comment]
Hola @tedroppelmann!

En este caso el cliente es un cliente "tonto", prácticamente la totalidad de la lógica la hace el servidor. El caso que propones el cliente debiese enviar el usuario al server y esperar una respuesta.

A pesar de esto, de todas formas el cliente debiése estar separado entre frontend y backend, solo que esta vez el backend no haría más que comunicarse con el servidor.

Éxito!
