### ISSUE TITLE
Descuento por libreria prohibida no utilizada

### ISSUE THREAD

**Issue by pabloist** [IIC2233/syllabus#1080]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola buenas! Disculpa tenia la duda porque me realizaron el descuento por una libreria prohibida que no utilice en el desarrollo del programa pero que olvidé quitarla del import; es posible que si en la recorrección la elimino me quiten ese descuento?

De antemano muchas gracias!

**Comment by Mjtala** [comment]
Hola @pabloist! Efectivamente puedes pedir que eliminen esa línea de tu código en la recorrección y así el descuento no aplicaría.
Ánimo con lo que queda del semestre!!

**Comment by pabloist** [comment]
Muchas gracias !!
