### ISSUE TITLE
Error al abrir archivo json desde el terminal

### ISSUE THREAD

**Issue by catalinamusalem** [IIC2233/syllabus#1081]
Hola! Tengo un problema cuando trato de abrir mi código desde el terminal ya que me aparece un error diciendo que esta malo el path del archivo json, pero cuando abro el codigo desde vs si me funciona. Cual puede ser el error?

**Comment by KnowYourselves** [comment]
Hola @catalinamusalem!

Sube to código para que le pueda echar una mirada. 

Éxito!

**Comment by catalinamusalem** [comment]
Lo acabo de subir
Muchas gracias!

**Comment by KnowYourselves** [comment]
Probablemente el error se debe a esto:

![image](https://user-images.githubusercontent.com/26102039/85470923-b32f9180-b57d-11ea-8758-6d208e1ccfa6.png)

Estás accediendo al json con el path "cliente/parametros.json", cuando debiese ser sin el "cliente", ya que el código sería ejecutado deesde la misma carpeta cliente.

Cuéntame si eso te ayuda!

**Comment by catalinamusalem** [comment]
Sí, eso era! Muchas gracias
