### ISSUE TITLE
Bloque antes de cada chunk

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#1081]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!

Llevo un tiempo tratando de entender un error al enviar el mensaje codificado desde el cliente al servidor.
Cada chunk tiene un int al principio. El problema es que al recibirlo se pierde parte de la imformación. Esto deja de ocurrir si no recibo la parte que viene antes del chunk.

Esta es la forma de recibir el mensaje en el servidor (se recibe el largo del mensaje antes)::
`while len(bytes_mensaje) < largo_mensaje:
                numero_chunk_bytes = socket_cliente.recv(4)
                chunk_bytes = socket_cliente.recv(60)
                bytes_mensaje += chunk_bytes`

Esta es la forma de enviar del cliente(se agrega el chunk final + los bytes 0):
`division_entera = len(mensaje_bytes) // 60
        for i in range(0, division_entera):
           numero_chunk = i + 1
            numero_chunk_bytes = numero_chunk.to_bytes(4, byteorder='little')
            chunk = mensaje_bytes[i*60:(i+1)*60]
            mensaje_codificado += (numero_chunk_bytes + chunk)
`

Si elimino la parte de recibir los 4 bytes que van antes de cada chunk, el servidor recibe sin problemas.

**Comment by EduardoIllanes** [comment]
Hola @amahns1 !
Viendo el código que pones me causa un poco de ruido la forma en que recibes el mensaje, sobre todo `numero_chunk_bytes = socket_cliente.recv(4)`  al estar dentro de ese `while` 👀.Te recomiendo fuertemente ver el [ejemplo de los contenidos](https://github.com/IIC2233/contenidos/blob/master/semana-14/3-ejemplos.ipynb)  ahí también se realiza un caso similar en donde se maneja los primero 4 bytes de un chunk. Quedo atento a tus comentarios por si te siguen quedando dudas y éxito en tu tarea 🙌

**Comment by amahns1** [comment]
Hola @EduardoIllanes! 
La razón por la que está adentro del `while` es porque se supone que el `bytearray` tiene `4 bytes` antes de cada bloque (solo puse una parte del código en la issue). Antes de este `while` se reciben los `4 bytes` que representan el largo del mensaje. Mi duda es cómo recibir esos `4 bytes` antes de cada bloque, lo cual no está funcionando

**Comment by amahns1** [comment]
Lo acabo de solucionar. Había que separa el caso en que el chunk era menor a `60 bytes`.

Muchas gracias!!
