### ISSUE TITLE
Envio de información 

### ISSUE THREAD

**Issue by jaimecoloma** [IIC2233/syllabus#1082]
Hola, tengo una duda un poco conceptual pero respecto a la tarea. Me confunde aún comprender bien cómo la información se recibe. Es decir entiendo bien que con .recv() puedo recibir en bytes el mensaje pero me enreda pensar que por ejemplo cuando el servidor envia una imagen, primero manda el tipo, luego el tamaño y luego el mensaje serializado, entonces son 3.recv (?). Esto me surgió porque pensaba en cómo enviar de vuelta la confirmación del nombre válido para el usuario y no sé si debe seguir una estructura parecida, ya que, para evitar errores en el cliente, si uso 3 .recv quizás me genera un error?
La duda la tengo ya que en interfaces era mas facil enviar y saber a donde mandabas algo y que tipo era pero como aquí todo se trabaja en una funcion ```escuchar_servidor```me enreda como trabajarlo bien.
Espero se entienda la pregunta jaja

**Comment by vicentevegaulloa** [comment]
Hola @jaimecoloma!

La idea es separar los bytes, por lo que tu idea de hacer varios `recv()` es correcta y no debería arrojarte errores. La gracia de la arquitectura cliente-servidor es que tu sabes como se enviarán y recibirán los mensajes por parte del servidor como del cliente. Esto te permite pensar en formas  óptimas de enviar y recibir los mensajes (como la forma de recibir y separar los bytes que tienes pensada). 
En interfaces las señales enviaban mensajes donde tu definías el tipo y no importaba la cantidad. Esto es dar unos pasos extra (definir tipo y tamaño, codificar y decodificar) para conseguir el mismo objetivo pero alcanzando otro puerto y/o computador.

**Comment by jaimecoloma** [comment]
@vicentevegaulloa es que lo que me genera duda es el hecho de que para enviar la carta hay un patron definido, pero debo seguir ese patron para enviar otras cosas? es decir si quiero enviar algo tipo (largo, mensaje codificado) en vez de (tipo, largo, mensaje codificado) como son las cartas no me va a generar error? ahi es donde me enredo un poco. O debo manejar en distintos if/elif los tipos de mensajes que me podrian llegar y eventualmente separarlos para recibir correctamente el archivo?
Gracias por la ayuda!

**Comment by vicentevegaulloa** [comment]
En el enunciado se dice que 

> **Queda a tu criterio cómo estructurar la comunicación entre el cliente y el servidor**, siempre
y cuando respete todo lo indicado en Networking. Sin embargo, **la única excepción a lo anterior es al implementar el envío de cartas** entre el cliente y el servidor.

Por lo que no es necesario que sigas el patrón definido en la parte de las cartas. Usar otro patrón de comunicación en otras partes no te debería causar problemas y es lo que más hace sentido si consideras que las cartas no son lo unico que se envía entre cliente y servidor.

**Comment by vicentevegaulloa** [comment]
Creo que esta  [issue](https://github.com/IIC2233/syllabus/issues/1069)  te puede servir!

**Comment by jaimecoloma** [comment]
Gracias! Eso era lo que necesitaba entender!

**Comment by vicentevegaulloa** [comment]
De nada!
