### ISSUE TITLE
INSTANCIAR GRILLA

### ISSUE THREAD

**Issue by betolguin** [IIC2233/syllabus#1082]
hola!! no entiendo bien como usar los métodos que nos entregan de la clase GrillaHexagonal,
si alguien me pudiera explicar bien como instanciarla y esas cosas para poder usarlas correctamente lo agradeceria muchisimo!!

quedo atento, 
saludos :)

**Comment by gatochico** [comment]
Hola @betolguin ! 

Lo que hace la clase `GrillaHexagonal `es tomar **un tamaño para las aristas del hexágono**. Luego, esta tiene un método llamado `generar_hexagono`, el cual recibe **una lista [filas, columnas]** con la cantidad de filas y columnas del grafo (que correspondería al valor de `dimensiones_mapa` en el archivo .JSON del grafo) y dos **enteros** que representan que tan trasladada a la derecha o abajo quieres que esté la grilla generada. Luego, esto te retorna un diccionario con llaves que representarán los **id** de los nodos y valores que serán **la posición en la interfaz donde ubicar el nodo**. Como ejemplo:

```
# Instancio la clase y digo que las aristas serán de tamaño 90
grilla = GeneradorGrillaHexagonal(90) 

# dimensiones_mapa debo extraerlo del JSON del grafo y para el que les dimos, corresponde a [5, 2]
# quiero que mi grilla quede trasladada 100 px a la derecha y 100 abajo.
posicion_nodos = grilla.generar_grilla(dimensiones_mapa, 100, 100) 

```

En ese punto, `posición_nodos` ya contiene un diccionario con los ids de los nodos y sus ubicaciones, por lo que se te debería facilitar el saber donde ubicar labels en las interfaces. No puedo indicarte como ubicarlas, pero con el tener ya este diccionario se te debería facilitar el hacerlo 🙈 . 

Como último disclaimer, recuerda que **el uso de esta clase es completamente opcional**, y solo la entregamos como ayuda para que no se demoraran tanto en posicionar la grilla. Si así lo deseas o se te complica mucho su uso, puedes no usarla y ver otra forma de hacerlo.

Saludos!

**Comment by dedmu5** [comment]
> Hola @betolguin !
> 
> Lo que hace la clase `GrillaHexagonal `es tomar **un tamaño para las aristas del hexágono**. Luego, esta tiene un método llamado `generar_hexagono`, el cual recibe **una lista [filas, columnas]** con la cantidad de filas y columnas del grafo (que correspondería al valor de `dimensiones_mapa` en el archivo .JSON del grafo) y dos **enteros** que representan que tan trasladada a la derecha o abajo quieres que esté la grilla generada. Luego, esto te retorna un diccionario con llaves que representarán los **id** de los nodos y valores que serán **la posición en la interfaz donde ubicar el nodo**. Como ejemplo:
> 
> ```
> # Instancio la clase y digo que las aristas serán de tamaño 90
> grilla = GeneradorGrillaHexagonal(90) 
> 
> # dimensiones_mapa debo extraerlo del JSON del grafo y para el que les dimos, corresponde a [5, 2]
> # quiero que mi grilla quede trasladada 100 px a la derecha y 100 abajo.
> posicion_nodos = grilla.generar_grilla(dimensiones_mapa, 100, 100) 
> ```
> 
> En ese punto, `posición_nodos` ya contiene un diccionario con los ids de los nodos y sus ubicaciones, por lo que se te debería facilitar el saber donde ubicar labels en las interfaces. No puedo indicarte como ubicarlas, pero con el tener ya este diccionario se te debería facilitar el hacerlo 🙈 .
> 
> Como último disclaimer, recuerda que **el uso de esta clase es completamente opcional**, y solo la entregamos como ayuda para que no se demoraran tanto en posicionar la grilla. Si así lo deseas o se te complica mucho su uso, puedes no usarla y ver otra forma de hacerlo.
> 
> Saludos!

Tengo una duda con respecto a eso.
En la foto del mapa que está en el enunciado, contando los nodos hay 33, pero cuando hago
`generador.generar_grilla([5,2], 30, 30)` por ejemplo, me entrega:
`{'0': (92, 30),  ...  , '38': (592, 680)}`
Esos son 39 nodos. ¿Qué es lo que no estoy viendo?

**Comment by gatochico** [comment]
Hola @dedmu5 ! ¿Estás seguro que no modificaste el archivo original `generador_grilla.py` sin querer?
Acabo de descargar la copia del syllabus y ejecutar la línea `generador.generar_grilla([5,2], 30, 30)` y me entrega 33 nodos, no 39 🤔 . Además probando ubicarlos en una interfaz me da la grilla correcta que pedimos.

Te recomiendo descargar de nuevo el archivo .py y probar con el nuevo.
Quedo atenta a qué ocurre!

**Comment by fran-gl** [comment]
Me ocurre lo mismo que @dedmu5, pero solo para algunos valores de arista. Por ejemplo si pongo ```GeneradorGrillaHexagonal(60)```, ```generar_grilla``` me entrega 33 nodos, pero si pongo ```GeneradorGrillaHexagonal(65)```,  ```generar_grilla``` me entrega 39 nodos.

**Comment by dedmu5** [comment]
> Me ocurre lo mismo que a @dedmu5, pero solo para algunos valores de arista. Por ejemplo si pongo `GeneradorGrillaHexagonal(60)`, `generar_grilla` me entrega 33 nodos, pero si pongo `GeneradorGrillaHexagonal(65)`, `generar_grilla` me entrega 39 nodos.

Efectivamente, yo tengo una arista de 125. Debe ser eso. Parece que es un bug con números impares

**Comment by gatochico** [comment]
Hola!

Efectivamente el generador de grilla tenía un pequeño bug :bug: con algunos tamaños de arista (donde no aproximaba correctamente las posiciones y terminaba entregando nodos duplicados, por ende les salían 39 nodos en vez de 33). Acabo de subir al syllabus una versión de ese archivo con ese problema solucionado (lo probe con 65 y 135, entre otros, y ahora sí entrega 33 nodos correctamente ubicados) 🤓 . 

Gracias a ambxs por hacerlo notar!
