### ISSUE TITLE
Sacar información de grafo.json

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2233/syllabus#1083]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! Quería saber si puedo sacar la información de grafo.json y poner la que necesite en el archivo de parametros.json ya sea del cliente o del servidor.
De antemano gracias!

**Comment by Mjtala** [comment]
Hola @Jamesmoreno21! La verdad es que **no es posible** hacer lo que dices, debes leerlo directamente de grafo.json. Recuerda que puedes leer la información de grafo.json y guardarla en un diccionario, lista o como estimes conveniente.

**Comment by Jamesmoreno21** [comment]
Ok! Comprendo, lo que pasa es que para formar el mapa o la estructura al menos, usaba las dimensiones en el cliente para generar la grilla, pero el resto de información la pensaba usar en la lógica del servidor, sobre todo la matriz de adyacencia, para el análisis de jugadas y varios, en tal caso me surgen dos preguntas, ¿puedo tener un grafo.json en el cliente y servidor? Siendo el mismo archivo duplicado para cada carpeta y en caso de que no, ¿puedo directamente obtener las coordenadas de los nodos con la grilla y hacerlos a mano en QtDesigner, así dejo grafo.json sólo para la parte del servidor?
Gracias de antemano 😄

**Comment by Jamesmoreno21** [comment]
Ya, muchas gracias, lo haré de esa forma entonces 😄
