### ISSUE TITLE
Formato parametros.json

### ISSUE THREAD

**Issue by sofiaemd** [IIC2233/syllabus#1083]
Hola! En el enunciado dice que el archivo de parámetros debe estar en formato:
{
    "host": <dirección_ip>,
    "port": <puerto>,
    ...
}
¿Hay que respetar los enter e indentaciones o puede estar todo en la misma linea?

**Comment by vicentevegaulloa** [comment]
El formato JSON permite cualquier indentación o espaciado, funcionará independiente de esto. Sin embargo, se recomienda presentarlo como en el enunciado para facilitar la lectura.

**Comment by NikiHV** [comment]
Dentro de la misma pregunta, ¿el formato de JSON incluye el uso de minúsculas para las "llaves"? ¿Estaría permitido que los nombres de las llaves estén en mayúsculas?
Por ejemplo:
```
{
"PARAMETRO_1": 1,
"PARAMETRO_2": "gracias"
}
```

**Comment by vicentevegaulloa** [comment]
Hola @NikiHV !

Da lo mismo si están o no en mayúscula. Está permitido.

**Comment by sofiaemd** [comment]
Muchas gracias!! 😁
