### ISSUE TITLE
Prueba de código, en mi pc crashea pero en otro no.

### ISSUE THREAD

**Issue by Gabucado** [IIC2233/syllabus#1084]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Probando mi codigo hasta cuando el programa tiene que abrir la sala de espera, he notado que, cuando instancio una vez más mi cliente, la instancia anterior se congela. Estuve todo el día viendo el porqué esto ocurría hasta que decidí probarlo en **otro computador**, uno más potente pero que no puedo usar para realizar mis tareas, en el que corrió _sin_ problemas **¿Por qué puede ocurrir esto?**. 
:<

**Comment by Mjtala** [comment]
@Gabucado podrías subir tu código a tu repo para poder verlo! Avísame cuando lo hagas

**Comment by Gabucado** [comment]
> @Gabucado podrías subir tu código a tu repo para poder verlo! Avísame cuando lo hagas

Ya esta arriba :0

**Comment by Mjtala** [comment]
Si abres las 4 pestañas de la sala de espera (una por cada jugador), y después de eso ingresas a los jugadores también se te queda pegado?

**Comment by Gabucado** [comment]
Nope, me pasa inmediatamente despues de abrir una segunda ventana para el cliente. 
Perdon por la demora de la respuesta, y muchas gracias por la atencion :o

**Comment by Mjtala** [comment]
Pero si abres una ventana para el cliente, primero ingresas el nombre de este y después abres otra ventana para otro cliente o primero abres otra ventana para otro cliente sin ingresar el nombre de ninguno?

**Comment by Gabucado** [comment]
Primero abro dos ventanas del cliente, pongo el nombre en uno y despues en la del otro, luego de eso la primera se congela :o

**Comment by Mjtala** [comment]
Hola! Perdón la demora pero podrías tratar borrando las líneas 65 y 66 del archivo client/frontend/principal donde sale 
if 'id' in message:
self.hide()
Me avisas si te funciona!

**Comment by Gabucado** [comment]
Hola @Mjtala !
Probé el fix que recomendaste y funciona perfectamente! Muchas gracias por la ayuda. 🎷🐛
