### ISSUE TITLE
Qt disagner y Anaconda 

### ISSUE THREAD

**Issue by cncosta** [IIC2233/syllabus#1084]
Hola Estoy usando qt disagner para mac, y pero me aparece el siguiente error al tratar de usar una styelsheet:
![Captura de pantalla 2020-06-22 a la(s) 22 01 25](https://user-images.githubusercontent.com/42576884/85352681-807d8e80-b4d4-11ea-8e3d-77a370fb6bbc.png)
He buscado como instalar anaconda, pero no entendí como hacerlo

**Comment by gatochico** [comment]
Hola! 

Mi primera recomendación sería que **mejor no bajes anaconda 😅**. Anaconda es una suite de herramientas para Data Science, que claro, viene con Python, la librería pyqt5... y mil cosas más que no son necesarias para lo que quieres hacer. Además 

¿Cómo descargaste Designer? Quizá podrias intentar desinstalándolo de tu computador y [descargándolo](https://build-system.fman.io/qt-designer-download) de nuevo. 

Avísanos cómo te va!

**Comment by cncosta** [comment]
@gatochico Logre encontrar el problema, estaba aplicando mal la stylesheet
