### ISSUE TITLE
Enviar Mapa a Cliente

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#1085]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia
Tengo una duda a como cargar una clase para los clientes que fue enviada desde el servidor.  Me explico, para crear el mapa Catan  en el servidor hice una clase que se llama Mapa y ahi guardo toda la informacion relacionada con el mapa. En el modulo donde se encuentra la clase  Mapa probé el dumps y loads del mapa instanciado para ver si funcionaba correctamente.
 El tema es que cuando quiero enviar el mapa instanciado desde el servidor y lo quiero cargar desde el cliente. Me tira un error de    _pickle.UnpicklingError: unpickling stack underflow. Entonces no se me ocurre como cargar algo de ese estilo. ¿Cuál consejos ustedes me podrían dar? 

Saludos
 
### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by matiasmasjuan** [comment]
Hola @enriquemolinare !

Recuerda que si quieres enviar **instancias** de **clases**, debes definir la **clase** en **ambos** **módulos**, tanto para el **cliente** como para el **servidor**. 

Avísame como te va! :smile:

**Comment by enriquemolinare** [comment]
hola, eso hice pero no funciona. No entiendo cual es error :(

**Comment by matiasmasjuan** [comment]
¿Podrías subir tu código al repo porfavor? Tal ves pueda revisarlo con mayor detalle.

**Comment by matiasmasjuan** [comment]
Hola @enriquemolinare !

Estuve viendo tu código, y la verdad es que existen varios errores donde la mayoría **no tienen relación** con el protocolo. La mayoría de ellos se encuentra en el método ```listen_thread``` de ```client.py```. Existen muchas variables que no están definidas y las llamas igual (```mensaje_compuesto, mensaje_compuesto_largo```) etc. Estas variables se crean en la sentencia ```if```, pero no en el ```else```, por lo que no están siendo definidas al momento de usarlas. Además, recuerda que al utilizar *pickle*, **no es necesario** realizar un *encode* y *decode* del string. Simplemente con utilizar ```pickle.dumps``` y ```pickle.loads``` basta para serializar y deserializar el mensaje y poder enviarlo. El error que existe es que en la línea 104 de ```server.py``` haces un ```dumps(mensaje)``` y luego llamas al método ```self.send``` en donde  haces un ```encode()``` al mensaje **ya serializado** (por lo cual no es necesario volver a hacer un **encode**) y despues obtienes el largo de ese mensaje. Recuerda que si ya realizaste un ```mensaje_bytes = pickle.dumps(mensaje)```, puedes calcular su largo con ```len(mensaje_bytes)``` y a **eso** transformarlo a *bytes* a través de un *encoding* (ya sea *big endian* o *little endian*. En caso de seguir teniendo dudas con el protocolo, te recomiendo ver los [Ejemplos: contenidos semana-14](https://github.com/IIC2233/contenidos/blob/master/semana-14/3-ejemplos.ipynb) ya que ahí hay ejemplos de envío de mensajes a través de ```pickle```.

A fin de cuentas, el error no es provocado por el **envío** de **objetos**, sino por el manejo de los *bytes* que estás serializando y enviando. Te recomiendo hacer *prints* constantes en tu código para ir *debbugeando* los errores. Podrías también intentar hacer el protocolo sin el envío de chunks (sino todo el mensaje de forma inmediata), y apenas estes seguro de que eso funcione, intentes modificar las sentencias para poder enviar el mensaje por chunks de 60 *bytes* como dice el enunciado.

Saludos, y mucho éxito con la tarea! :smile:

**Comment by enriquemolinare** [comment]
Hola, fui revisando lo que me dijiste. El tema es que la única diferencia que encuentro del mensaje originnal en bytes y el mensaje protocolado es que el mensaje original solo usa un '/' y el mensaje protcolado usa dos "//". 
No entiendo porque se produce ese error. He estado intento hallar el error , he leído nuevamente los contenidos pero no entiendo porque se agregan los "/"

**Comment by matiasmasjuan** [comment]
Hola @enriquemolinare !

Revisando nuevamente tu código, me di cuenta que este error se produce por lo **mismo** que te comenté antes. Dejandolo de forma mas explícita, en la línea 103 de server.py haces un dumps al mensaje, lo cual está bien. Luego en la línea 107 llamas a self.send(mensaje). Luego, si nos vamos a ese método, en la linea 52 y 53 le haces un ```encode()``` a ese mensaje. Esto es un error, y por la misma razón que antes, **no debes hacer un encode a un mensaje que ya está serializado con pickle.dumps()**. ¿Cómo solucionarlo? Simplemente borrando o comentando las líneas 52 y 53. Luego, en la línea 54, cambiar el len(msg_bytes) por len(value), (ya que value es el mensaje ya serializado con dumps). Y finalmente en la línea 56, llamar a dividir_mensaje(value). Esto soluciona el problema de los "//", pero deberás comprobar ahora que el protocolo de envío con los bloques y la separación de chunks sea correcta.

Saludos!

**Comment by enriquemolinare** [comment]
vale , muchas gracias. Te pasaste!!
