### ISSUE TITLE
impresion de algo extraño

### ISSUE THREAD

**Issue by camolina2** [IIC2233/syllabus#1085]
hola! 
aunque no me sale error se me imprime de forma inesperada esto en la parte del cliente, no he podido encontrar en qué momento exactamente pasa :(
y lo que he encontrado en internet no me ha servido.

**Failed to compute left/right minimum bearings for "GB18030 Bitmap"**

Muchas gracias de antemano!

**Comment by vicentevegaulloa** [comment]
Hola @camolina2!

Puedes hacer un push para revisarlo? Además, quisiera saber cual es tu sistema operativo y como estás corriendo tus archivos.

**Comment by camolina2** [comment]
Muchísimas gracias!!! 
el último push que hice está bien. Sistema operativo es macOS Catalina y estoy corriendo desde la terminal. 

Adjunto foto de lo que sale! 

![Captura de Pantalla 2020-06-23 a la(s) 19 49 53](https://user-images.githubusercontent.com/54114370/85479245-ccd7d580-b58b-11ea-9568-b7ae00482874.png)

**Comment by vicentevegaulloa** [comment]
Esto ha afectado de alguna forma tu código? o solo aparece sin querer pero nada más?

**Comment by camolina2** [comment]
Hasta el momento no ha pasado nada que afecte, el peor escenario es que a veces se imprime muuuuchas veces seguidas y eso es molesto. 
La verdad es que no sé si es algo malo y debería preocuparme o ignorarlo simplemente. 
Muchas graciaas por la ayudaaa :D

**Comment by vicentevegaulloa** [comment]
Por lo que he podido leer hasta el momento, es un tema de sistema operativo y es solo un mensaje de advertencia (aún no se de qué). En mi computador el error no ocurre y el programa muestra todo sin problemas. Te recomiendo seguir trabajando y olvidarte de esto, ya que al parecer es inofensivo. Seguiré investigando de que se trata y si encuentro algo relevante lo escribiré en esta issue por si alguien más tiene el mismo problema.

**Comment by camolina2** [comment]
Muchas graciaaas! :D
