### ISSUE TITLE
Dónde poner parámetro número de jugadores por partida

### ISSUE THREAD

**Issue by CatalinaGoldsack** [IIC2233/syllabus#1086]
Hola! el parámetro de CANTIDAD_JUGADORES_PARTIDA lo debo poner en un nuevo  parametros.py? O incluirlo en parametros.json? 😊

**Comment by vicentevegaulloa** [comment]
Hola @CatalinaGoldsack! 

Debes incluirlo en `parametros.json` al igual que todos los parámetros. En esta tarea no habrá `parametros.py`, sólo `parametros.json`.

**Comment by CatalinaGoldsack** [comment]
perfecto! muchas gracias :)

**Comment by vicentevegaulloa** [comment]
De nada!
