### ISSUE TITLE
Duda sobre roles / Sprites

### ISSUE THREAD

**Issue by pedroriosg** [IIC2233/syllabus#1086]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!, tengo una duda respecto a los roles, en concreto, no me queda claro si es el servidor quién envía los sprites a cada cliente, o, envía información y cada cliente "elige sus sprites".

Saludos y muchas gracias

**Comment by DCCollao** [comment]
Hola @pedroriosg!

Según enunciado, los roles del servidor **no incluyen** repartir las _sprites_ entre los distintos clientes. Solamente debe dedicarse a ser un intermediario en cuanto a los datos que respectan a la partida e imprimir sus logs.

![image](https://user-images.githubusercontent.com/37167447/100372229-b674f080-2fe7-11eb-94db-985d935b67e3.png)
Así que si quieres simplemente poner la carpeta de _sprites_ dentro de cliente, estará bien!
