### ISSUE TITLE
Citar Actividades del curso

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC2233/syllabus#1087]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! mi pregunta es sobre citar código, si revisamos y utilizamos código de las actividades formativas o sumativas, **este debe ser citado como si fuese código encontrado en internet?** O podemos utilizarlo y basarnos en él, solamente comentando en el README que utilizamos parte del código de X actividad?

**Comment by rodrigobj99** [comment]
Hola @SebaHagedorn ! En esos casos, puedes poner en la sección de "Referencias de código externo" del README algo como: "El modulo 'modulo.py' está basado en/tiene ideas sacadas de la actividad XX del curso" y se entenderá la idea.

Espero te sirva!

**Comment by SebaHagedorn** [comment]
Perfecto, muchas gracias!
