### ISSUE TITLE
Correr main.py en terminal

### ISSUE THREAD

**Issue by sebadelorenzo** [IIC2233/syllabus#1087]
Hola!! Tengo un problema de directorio al correr mi archivo main.py del cliente en la terminal. Cuando corro el archivo en vs code me abre bien la ventana de inicio creada en Qt designer. Sin embargo, cuando corro el archivo desde la terminal me levanta un error tipo ```FileNotFoundError: [Errno 2] No such file or directory: 'VentanaInicial.ui'```.

Me pregunto por qué pasa esto. Gracias de antemano!!

**Comment by Francisco5674** [comment]
Tengo el mismo problema, lo solucione cambiando el directorio en la terminal de tal manera que tomara la carpeta "T03" como directorio principal y para ejecutar los main.py del servidor y el cliente escribo los siguiente "python servidor/main.py" o en el caso del cliente "python cliente/main.py" y listo, pero ya que estamos en esta pregunta, ¿Esto esta bien? es decir funciona, pero no se si el cliente al ejecutarlo en otra carpeta de otro computador funcionará igual.

**Comment by Francisco5674** [comment]
Es decir, no he logrado que cliente o servidor sean independientes, todos los path de mi sistema son relativos a la carpeta que los contiene que es T03, y no a sus propias carpetas ya que si las uso como directorio principal, estas no reconocen ningún path que ellas mismas contienen, tal como dice sebadolorenzo, dice que no existen archivos que claramente están en la carpeta.
Por ejemplo:

- Si utilizo como directorio principal a cliente para ejecutar a cliente de esta manera
cd C:\Users\franc\source\repos\Francisco5674-iic2233-2020-1\Tareas\T03\cliente
y luego ejecuto:
python main.py
me dice que los archivos paremetros.json, o los archivos de las sprites no existen con el error 
"""FileNotFoundError: [Errno 2] No such file or directory: etc"""

-En cambio si utilizo
cd C:\Users\franc\source\repos\Francisco5674-iic2233-2020-1\Tareas\T03
y luego ejecuto:
python cliente/main.py
claramente despues de haber cambiado todos loas path en mi codigo de la manera que usen T03 como relativo
funciona perfecto...

**Comment by Francisco5674** [comment]
Hola regreso para decir que ya solucione el problema y ahora mis carpetas son completamente independientes una de la otra, lo logre cambiando el directorio principal de VS code a cliente o servidor en vez de T03 como entorno de trabajo, una vez modificados todos los path correspondientes a sus propios directorios, cuando los ejecutas en la terminal, no importe donde este la carpeta cliente o servidor, estas funcionaran de manera autónoma, ES GLORIOSO, espero haber sido de ayuda. XD

**Comment by sebadelorenzo** [comment]
Gracias por la ayuda!
