### ISSUE TITLE
Error inesperado con bind : OSError: [WinError 10048]

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#1088]
Hola! Estaba funcionando **perfecto** la conexión con los clientes, y de la nada cuando lo corrí denuevo el main de un cliente en el terminal (despúes de correr el servidor), aparece este error que no me deja conectarlo:
```
self.socket_server.bind((self.host, self.port)) OSError: [WinError 10048]
Solo se permite un uso de cada dirección de socket (protocolo/dirección de red/puerto)
```
Es raro porque sí me funciona en VSCode pero no en el terminal, y todo el rato me había funcionado perfecto en ambos!! Busqué en internet, intenté cambiar de port, reinicié el computador pero sigue el mismo error si lo corro por la consola el cliente

**Comment by jirarrazaval** [comment]
He buscado por internet y siempre sale que funciona hacer esto:
![image](https://user-images.githubusercontent.com/62080216/85424004-6760f600-b545-11ea-8cd1-ea819ed4c92e.png)
Pero aún no me funcionaa :(

**Comment by lily416** [comment]
Hola, no es necesario que cierres la issue, puede que alguien tenga el mismo problema que tuviste y está issue le sirva :)

Si puedes, comenta cómo lo solucionaste, para que podamos saberlo.

Saludos y éxito en la tarea 👋😄

**Comment by rldelafuente** [comment]
Hola! Tengo el mismo error :(

`Solo se permite un uso de cada dirección de socket`

Por si pueden comentar como solucionarlo.

**Comment by lily416** [comment]
@rldelafuente el error se produce cuando intentas acceder a un puerto que se encuentra ocupado.

La principal forma de arreglarlo, es terminar el proceso que se está ejecutando, para esto puedes:
* Interrumpir el proceso a través de la terminal. Normalmente se logra apretando `CTRL + C` en la terminal o consola.
* Interrumpir el proceso a través de administrador de tareas. Que es lo que hizo @jirarrazaval.

La otra opción es cambiar el puerto, ya que puede que otro programa lo esté utilizando.

Saludos y éxito en la tarea.
