### ISSUE TITLE
Comunicación para Cliente (Frontend - Backend - Main)

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2233/syllabus#1088]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!
Entiendo que la comunicación entre frontend y backend del cliente debe ser mediante señales, pero resulta que mi main (donde conecto las señales entre frontend y backend) contiene a mi clase cliente, la cual necesito que se comunique con el backend (en realidad, el backend es un archivo aparte que maneja la lógica de todo el cliente excepto comunicacion con el server). Siendo así, puedo llamar directamente los métodos de la lógica del programa desde el cliente [self.logica.metodo()]?  De no ser así, cómo debería comunicar mi parte del cliente con el frontend y el backend de este?

Muchas gracias!

**Comment by jturquiza** [comment]
Hola @Sofia-Arratia!

Por lo que entiendo, tu clase Cliente() maneja la conexión con el servidor? De ser así, esta clase forma parte del backend de tu programa, por lo que no debería estar en el main. En este caso, si la lógica que mencionas es un archivo que maneja las funciones del cliente, puedes llamarla como tu dices (self.logica.metodo()), siempre y cuando la clase Cliente() sea parte del backend.
Por otra parte, en el main, debes instanciar a tu clase Cliente(), y a las clases que corresponden al frontend (ventanas de inicio, espera, juego, etc), y luego conectar sus respectivas señales con el backend.

Espero que te sirva, y quedo atento si no respondí tu duda!

**Comment by Sofia-Arratia** [comment]
Aaaah perfecto, es decir, es incorrecto que el Cliente() (o de manera similar, el Servidor()) se encuentre dentro del archivo main, por lo que debo hacer un main aparte, no? Muchas gracias ☺️ que tengas un buen dia

**Comment by jturquiza** [comment]
Claro, la idea es tener un main que instancie las clases y conecte las señales. De nada! Mucha suerte!
