### ISSUE TITLE
Duda sobre carga de sprites en Qt Designer

### ISSUE THREAD

**Issue by JoMarchant** [IIC2233/syllabus#1089]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
El ayudante que corrigió mi tarea 2 tuvo problemas revisandola por un tema con los sprites en los .ui:
![image](https://user-images.githubusercontent.com/69648244/100371153-1cf90f00-2fe6-11eb-964d-8089331ed72d.png)

Lo primero que pensé fue que pudo haber sido un problema con cómo estaban escritas las rutas de los sprites en los archivos .ui, pero revisando encontré que están escritos en forma relativa al directorio donde se encuentran:
![image](https://user-images.githubusercontent.com/69648244/100371221-37cb8380-2fe6-11eb-8d24-b32b3170cb19.png)

No quiero tener este mismo problema con mi Tarea 03, ya que pudo haber resultado en que el ayudante no pueda revisar mi trabajo, por esto:
**¿Habrá sido un problema con la forma en que están escritas las rutas? (usando directamente ```/``` en vez del usado por el OS correspondiente) ¿Existe una forma de que queden guardados con el separador del OS?**

PD: Probé mi Tarea 02 en distintos computadores y funcionaba correctamente (eran todos Windows).

**Comment by Mjtala** [comment]
Hola @JoMarchant, cuando utilizas "/" directamente no es tan beneficioso ya que puede pasar que según el sistema operativo el path no funcione de manera correcta.
Para que esto no te vuelva a pasar te recomiendo utilizar os.path.join(os.getcwd(), "sprites", "flechas","down_4.png") ya que de esta manera te funcionará para ambos sistemas operativos.
Ánimo con lo que queda de semestre!! 😃😃😃

**Comment by JoMarchant** [comment]
Si entiendo eso bien!! Mi problema es que no se como hacer eso en los archivos .ui que se crean en Qt Designer. Es ahí donde automáticamente se le asigna el separador "/". Y tampoco estoy seguro si esa es la fuente del problema que tuvo quien corrigió mi Tarea 02.

**Comment by Mjtala** [comment]
y cómo guardaste tus rutas en parametros.py?

**Comment by Mjtala** [comment]
Al parecer en qtdesigner da lo mismo que el slash no calce con el de os y en realidad el problema son los path relativos . De hecho cloné tu repo y me funcionó perfecto tu programa así que te recomiendo que mandes a recorregir **explicitando** dónde poner la carpeta sprites ya que lo más probable fue que el ayudante puso las carpetas en otra parte y por ende, el path relativo no era el mismo que utilizaste tu.

**Comment by JoMarchant** [comment]
Yaa perfecto, muchas gracias!!
