### ISSUE TITLE
imagen de Pyqt no se ve

### ISSUE THREAD

**Issue by sebaelsaca** [IIC2233/syllabus#1089]
Hola! Me pasa que cuando corro el código de mi ventana inicial en VScode se ve el logo de DCCuatro. No obstante, cuando corro el código desde el terminal no se ve. Creo que el error va por el lado de que el path cambia en el terminal. Pero no se me ocurre como arreglarlo. Ya trate poniendole al path os.getcwd() pero no sirvió.

**Comment by gatochico** [comment]
Hola! 

Cuando corres el archivo desde la terminal, te mueves con `cd` hasta la ubicación de la carpeta Server (o Cliente) antes de ejecutar el código?

**Comment by sebaelsaca** [comment]
Sip

**Comment by gatochico** [comment]
Y estás trabajando las interfaces con QtDesigner? ¿U otro método?

Además, podrías subir tu progreso a tu repositorio para ver cómo están los paths a las imagenes? Así puedo ayudar más

**Comment by sebaelsaca** [comment]
Sin QtDesigner, solo Pyqt5. Ya lo subí! Gracias @gatochico

**Comment by gatochico** [comment]
Ejecuté tu código y sí se me muestra la ventana :o , mira:
![image](https://user-images.githubusercontent.com/37161120/85600905-e0cb1800-b61b-11ea-8c44-43494a7d56f3.png)

Sin embargo, lo tuve que correr con la consola puesta en la carpeta `T03` de tu repositorio:
![image](https://user-images.githubusercontent.com/37161120/85601231-2d165800-b61c-11ea-8952-4f8f22a339ce.png)
y luego ejecutando `python servidor\servidor.py` y `python cliente\main.py`

Esto se debe a que la carpeta de `sprites` está en el directorio T03, en vez de estar dentro de servidor y cliente en específico. Recuerda que esto no sigue la modelación pedida en la tarea, donde cliente y servidor están completamente aislados el uno del otro, y no pueden compartir archivos (en este caso, compartirían la carpeta sprites). Recuerda que quien debe tener los sprites es el servidor por lo que la carpeta debería ir ahí. Si quieres que el cliente use algún sprite  no-carta (por ejemplo, el logo), deberías copiar el archivo del logo y ubicarlo en la carpeta del cliente, en su propia carpeta sprites.

Intenta corriendo el programa como lo hice yo y me dices cómo te va! Si te funciona, recuerda hacer los arreglos del párrafo anterior para tener una modelación correcta.

Saludos!

**Comment by sebaelsaca** [comment]
Oka muchas gracias!
