### ISSUE TITLE
Asignar valor a parámetros

### ISSUE THREAD

**Issue by despipe** [IIC2233/Syllabus#109]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda con respecto al enunciado, cuando nos dicen que nosotros tenemos que crear el parametros.py no me queda claro si debemos asignarle un valor según nos parezca o si debe ser entre los números máximos en cada caso, por ejemplo en experiencia si uno elige le parámetro o si es 0 a 100 ya que es lo mínimo y máximo que puede valer la experiencia, graciaas

**Comment by MrNachoX** [comment]
Hola @despipe!
Si no se especifica un valor para un parámetro en el enunciado entonces debes asignarle uno que te parezca apropiado.
Recuerda que los parámetros son valores constantes en el programa y aparecen en el enunciado en ESTE_FORMATO y en color azul. Por ejemplo, ENERGIA_ENTRENAMIENTO, MIN_AUMENTO_EXPERIENCIA, MAX_AUMENTO_EXPERIENCIA, etc. son parámetros que debes que incluir en el archivo parametros.py, pero la experiencia no es un parámetro, sino que una característica de un programón que debes modelar según los contenidos que han aprendido en el curso. Espero que haya quedado claro, cualquier cosa no dudes en volver a preguntar :)
