### ISSUE TITLE
Duda utilización de recursos

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#109]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
¿Qué sucede cuando el jugador necesita utilizar, por ejemplo, 15 de energía para poder jugar, pero solo tiene 14? ¿Debemos permitirle utilizar estos y dejar su energía en catorce y sólo si tiene 0 no poder jugar o sólo si tiene la energía necesaria le permitimos jugar?

**Comment by MaxAl100** [comment]
Lo mismo con las otras característica...
Por ejemplo, yo supongo que con dinero y energía no debiéramos permitirle avanzar al jugador, pero si la suerte, confianza, ego, etcétera bajara bajo 0 sólo tendríamos que ponerle ese valor.

**Comment by antoniablanco** [comment]
Siguiendo tu ejemplo, solo podría jugar si es que tiene mínimo 15 de energía.  Y para las otras caracteristicas habria que dejar en cero.
