### ISSUE TITLE
Problema al abrir archivos

### ISSUE THREAD

**Issue by villalobosacu** [IIC2233/syllabus#109]
Hola, al intentar abrir los archivos me aparece el siguiente error
```python
File "[redacted]/Tareas/T00/Posts.py", line 22

            ^
SyntaxError: unexpected EOF while parsing
```

**Comment by DCCollao** [comment]
Hola!

Este error suele deberse a falta de alguna `,` o algún paréntesis. En mi experiencia, python te arroja el error en la línea siguiente a donde está realmente, así que quizás tengas algún error de sintáxis en la línea 21.

Avísame cómo te va!

**Comment by villalobosacu** [comment]
No tengo nada escrito en la linea 21. Además tengo activada (supuestamente) la opción de que el código se detenga en la línea 9, precisamente para probar el abrir el archivo. Respecto a paréntesis y comas, pareciera estar todo bien.

**Comment by DCCollao** [comment]
Actualiza tus archivos para poder echar un ojo 👀

**Comment by villalobosacu** [comment]
Como? No entendí eso.
Puede que el error se deba a que el archivo aparece "Untracked" o nada que ver?

**Comment by DCCollao** [comment]
Debes actualizar tus archivos en github para yo poder revisarlos y ver qué onda el error. 

Si sigues la secuencia git add, git commit y git push, no debería haber ningún problema

**Comment by villalobosacu** [comment]
Ahi lo actualice

No se que hice, pero lo volvi a correr y funciono

**Comment by villalobosacu** [comment]
Una ultima cosa, archivo en que tipo de dato queda?? Porque no me deja indexarlo

**Comment by DCCollao** [comment]
Eso depende de la forma en que trabajas el archivo. 
Si me das más detalles sobre lo que estás haciendo, te podré ayudar.

**Comment by villalobosacu** [comment]
Volvio el problema, intente correrlo de nuevo, pero no me deja abrirlo

**Comment by villalobosacu** [comment]
En este momento, solo estoy abriendo el archivo, para poder empezar a trabajarlo. 
Según yo debería quedar como lista de las filas, pero me marca el error que te comente

**Comment by DCCollao** [comment]
Es con el archivo que tienes subido en github?

**Comment by villalobosacu** [comment]
'_io.TextIOWrapper' me ponía que este tipo no se podía indexar, pero no sé lo que es

**Comment by villalobosacu** [comment]
Acabo de subir los archivos al repositorio.

**Comment by DCCollao** [comment]
Corrí tu archivo `.py`, y lo único que tuve que agregar para poder leer correctamente los archivos fue el encoding en la línea 17.

Por favor sube los errores completos que te da el programa cuando lo ejecutas

**Comment by villalobosacu** [comment]
Igualmente, ese codigo son tres formas distintas de abrir los archivos, no deberia bastar solo con una??

**Comment by villalobosacu** [comment]
Ahora la tercera forma me marca:
File "c:/Users/E5-422/Desktop/villalobosacu-iic2233-2020-1/Tareas/T00/test.py", line 11, in <module>
    with open(path_posts, "rt", encoding = "utf-8") as archivo:
FileNotFoundError: [Errno 2] No such file or directory: 'Tareas\\T00\\posts.csv'

pero debería estar en esa ruta. 
Igual me di cuenta que  el metodo ocupa \\ siendo que mi sistema operativo utiliza /

**Comment by DCCollao** [comment]
Eso depende de en qué directorio estás ejecutando tu archivo `.py`.
Si lo estás ejecutando en la carpeta `T00`, no es necesario que pongas la ruta completa, pues basta poniendo solamente `posts.csv`.

Y sí, basta con solamente una opción para leer los archivos.
