### ISSUE TITLE
test_tablero_solucionar no reconoce las respuestas correctas

### ISSUE THREAD

**Issue by Lucas-Purcell** [IIC2233/Syllabus#109]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

###  AssertIn y failed test case
A pesar de estar obteniendo tableros correctos con la función **solucionar()**, me encuentro con un error que se muestra en la imagen adjunta. Vi otra issue que tenía un problema similar pero era porque modificaba el tablero original. Estoy usando la función copy.deepcopy() en mi código para generar los tableros de solución por lo que no debiese ser ese mi problema. He investigado el funcionamiento de la función **'assertIn'** en línea y he descubierto que compara si las variables proporcionadas ocupan el mismo espacio de memoria en el computador. Esto me ha llevado a concluir que, dado que mi resultado, construido dentro de la función, no ocupará el mismo lugar en la memoria de mi computador que una variable que se crea independientemente, siempre obtendré un resultado de "failed" al utilizar **'assertIn'**.

Mi pregunta es si el uso de la función **'assertIn'** en este contexto es intencional o si podría tratarse de un error. He notado que otros tests utilizan **'assertListEqual'** en su lugar y justamente son esos test los que no me entregan "failed".
<img width="505" alt="Captura de pantalla 2023-08-28 a la(s) 19 56 43" src="https://github.com/IIC2233/Syllabus/assets/129962986/f4b9e7e9-7acb-4284-9743-a5ea4ada1efa">

**Comment by ManuelV03** [comment]
Hola, para lo que se usa assertIn es para saber si tu solución está dentro de la lista de soluciones posibles. Viendo la imagen que adjuntaste creo que el error está en que tu estas retornando todas las soluciones posibles al tablero cuando solo tienes que retornar una, por lo que tu retorno no forma parte de la lista de soluciones. Si no me equivoco esto se debería arreglar si haces que tu función retorne solo una solución. Avísame que tal.
