### ISSUE TITLE
Nombre carpeta

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#109]
Hola!

Tengo una pregunta corta y simple. En el enunciado dice que debemos crear la carpeta "Reportes Estrategias de Extinción". Importa si la carpeta que creamos no tiene el tilde (para que Python no explote)?

Saludos!

**Comment by stephichau** [comment]
hola @akaminetzkyp !
De hecho es mejor que no le pongas tildes a las carpetas porque podrías tener problemas con **git** :).

**Comment by benjamimo1** [comment]
Yo cree Reportes_Estrategias_de_Extincion, pues los espacios me son conflictivos en macOS

**Comment by akaminetzkyp** [comment]
Gracias @stephichau!
