### ISSUE TITLE
Sobre eliminar información de un CSV

### ISSUE THREAD

**Issue by fernandolalanne** [IIC2233/syllabus#109]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Quería preguntar cómo se puede borrar elementos de un CSV. Lo intenté remplazando la fila que quiero borrar por un string vacío pero me arroja error.

Desde ya muchas gracias!

**Comment by RafaelEdwards** [comment]
Holaa! 

La verdad no entiendo para que quieres borrar una fila del archivo csv, pero para modificarlo te podría ser útil abrirlo en modo Write and Read (w+). No puedo darte mucho más información sobre esto pero en internet hay muchas referencias sobre lo que quieres hacer. Recuerda que en las tareas puedes y debes investigar por tu cuenta,  siempre va a haber alguien que haya tenido el mismo problema que tú. No olvides citar las referencias que utilices en el README.

Aquí te dejo un link donde hablan de lo más básico: https://www.geeksforgeeks.org/writing-to-file-in-python/
También podrías ver los contenidos del curso sobre manejo de archivos.

Espero haberte ayudado y suerte con tu tarea :)
