### ISSUE TITLE
UnboundLocalError: local variable 'solucion' referenced before assignment

### ISSUE THREAD

**Issue by rominaarancibia** [IIC2233/Syllabus#109]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

**Hola! en la función solucionar tablero en mi código no deja de lanzarme UnboundLocalError: local variable 'solucion' referenced before assignment, ya probé aplicando global tal como lo señala google pero no logra solucionarlo.
La función está definida en el archivo functions.py entre las lineas 120 y 158 y se observa el error mencionado al ejecutar la linea 65 del archivo main.py donde ocupa como tablero lo descrito en la linea 57.

**Comment by rominaarancibia** [comment]
Hola!
1. A que se refiere con no tocar mucho el archivo funciones?
2. Sii es que el global lo puse porque no deja de lanzarme el error mencionado segun lo que leí en internet pero no funcionó porque sin importar donde lo ponga el error no cesa.
Muchas gracias:)

**Comment by elisahonorato** [comment]
1.  Solo debes completar estas funciones, es decir, no se puede cambiar su nombre, alterar los argumentos recibidos o cambiar lo que retorne la función. A continuación se detallan las funciones a implementar.
2. Lo reviso enseguida

**Comment by rominaarancibia** [comment]
1. Sii no las he cambiado le cambie momentáneamente el nombre a solucionar tablero para comprender mejor lo que hacía en otras partes del código pero ya lo devolví. Además hay algunas funciones que cree que puse entremedio de las que hay que rellenar en vista a que quería ver más fácil como afectaban a solucionar tablero pero luego las pondré debajo.
2. Okey quedo atenta muchas gracias

**Comment by elisahonorato** [comment]
1. Tienes que fijarte bien en lo que estás retornando, ya que en algunos casos no es lo que se te está pidiendo. 
2. Te recomiendo no asignar tantas variables al tablero, y sólo ir modificando el tablero que le entregaste a la función como argumento en un principio.

**Comment by elisahonorato** [comment]
Además, me olvidó comentarte que el uso de variables globales no está permitido para esta tarea. https://github.com/IIC2233/syllabus/blob/main/Tareas/Descuentos.md
