### ISSUE TITLE
No aparece el QDialog

### ISSUE THREAD

**Issue by Zenos-Paradox** [IIC2233/syllabus#1090]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola. 
Por alguna razón, cuando trato de hacer que mi cliente envíe una señal a su frontend para mostrar la pantalla de espera, el cliente actúa como si se estuviera mostrando, pero nada se ve. Si solo lo muestro en el main, funciona.  Intenté originando la señal desde el cliente mismo y desde un atributo del cliente (algo como Logica() en la AF05) pero ninguno funciona correctamente. Alguien sabe que puede ser? quizá un problema con parents?

**Comment by rodrigobj99** [comment]
Hola @Zenos-Paradox !
Estuve viendo tu código y no logre encontrar el error. Al parecer la señal no se conecta correctamente con la pantalla de espera. Pese a logre que funcionara instanciando la ventana dentro de cliente y conectando las señales dentro de cliente también. De todos modos seguiré probando a ver que puede estar causando el problema.

**Comment by Zenos-Paradox** [comment]
Hola, gracias por la ayuda. No entiendo bien por qué no funciona, por alguna razón la señal no es bien recibida. Terminé solo haciendo algo más parecido a lo de la AF05 e instancie dentro de cliente una clase controlador que maneje las señales y esas cosas, así funciona.
Oh ahora me acordé de que no estoy seguro de si llamé al super __init __en Logica() en ese código, creo que es eso. Ahora no puedo revisar porque cambié muchas cosas.

**Comment by rodrigobj99** [comment]
Hola @Zenos-Paradox !
Recuerda que siempre puedes revisar los commits anteriores de tu repo en el caso de que desees probar si eso era lo que falllaba. Por otro lado me alegro que ahora este funcionando.
