### ISSUE TITLE
pyqt5signals y networking

### ISSUE THREAD

**Issue by Zenos-Paradox** [IIC2233/syllabus#1091]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

He estado teniendo problemas haciendo que un cliente emita señales. En la AF05 lo hacen de una forma que creo que es demasiado acoplada pero, si trato de conectar las señales en el main, no parece funcionar. Hay algo que me estoy perdiendo o solo estoy haciendo algo mal y tengo que seguir intentando?

**Comment by matiasmasjuan** [comment]
Hola @Zenos-Paradox !

La **AF05** es una **buena** modelación de lo que vendría siendo una **correcta** separación de ***front-end*** y ***back-end***, además de presentar **alta cohesión** y **bajo acomplamiento**.  Quizás tu confusión se deba a que en otros ejemplos del curso se suelen instanciar todas las **ventanas** y el **back-end** en el **main** e inmediatamente conectar todas las señales, lo cual es bastante ordenado. Sin embargo, no es la única forma de hacerlo. En la actividad, se instancia un objeto **Controlador** el cual se encarga de **procesar** la información que llega del servidor y sirve de conexión a través de señales del **back-end** y **front-end**, lo cual es correcto. Esto no es acoplado, ya que el **acomplamiento** hace referencia a utilizar métodos desde el **front-end** directamente hacia el **back-end** (o viceversa) sin el uso de señales. En la AF05 si se utilizan, por lo que presenta un bajo acoplamiento. También quiero mencionar que no es necesario instanciar todas las ventanas juntas y conectar todas las señales de forma inmediata. En general se recomienda esto ya que es ordenado, pero no tiene por qué ser así. A lo que voy es que intenta no perder mucho tiempo intentando hacer todo en el **main**, ya que no es la única forma de poder modelar correctamente la separación **front-end**-**back-end** del **cliente**.

PD: Si sigues teniendo dudas sobre la cohesión y acomplamiento puedes revisar los [Contenidos: Semana-9](https://github.com/IIC2233/contenidos/blob/master/semana-09/4-dise%C3%B1o-front-back.ipynb)

Espero haber respondido a tu pregunta, y mucho éxito con la tarea! :smile:

**Comment by Zenos-Paradox** [comment]
Gracias, creo que lo entiendo mejor ahora. Voy a tratar de hacer algo así.
