### ISSUE TITLE
Diferencia entre encode() y json.dumps()

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#1091]
Como dice el título, aún no me queda clara la diferencia entre estas dos funciones. En teoría ambas convierten un objeto a bytes, no? Se ocupan en conjunto, se pueden usar por separado? La misma pregunta para sus funciones opuestas,`decode()` y `json.loads()` 

Esto lo pregunto ya que me acabo de dar cuenta que en mi código uso tanto `encode()` como `json.dumps()` para enviar datos al servidor, y este los lee solamente con `decode()` y funciona bien, a menos que me este equivocando y me pueda traer errores más adelante

**Comment by rieg-ec** [comment]
json.dumps() lo que hace es transformar el diccionario que le pases a un str, mientras que encode() es un método de la clase str() que transforma un str a bytes. Lo mismo con decode() y loads() pero viceversa. Por eso se ocupan los 2 para transformar un diccionario a bytes, ya que los diccionarios no poseen ese método.

**Comment by igbasly** [comment]
Hola @lewebe :smile:
Tal como mencionas, este tema puede causar cierta confusión debido a la similitud de los métodos involucrados. Primero quiero establecer dos principales diferencias:
1. El método `encode` es un método de *strings*, por lo tanto se aplican directamente a los *strings* para obtener su codificación en *bytes*. Esto es gracias a que los *strings* en Python son *unicode*, es decir, que cada carácter tiene  su código único en *bytes* definido por el mismo estándar.
2. El método `json.dumps` es un método de la librería `json` y permite serializar casi cualquier estructura de Python (listas, *strings*, enteros, diccionarios, etc)  en un *string* con formato JSON. Esto quiere decir, que el *string* resultante puede ser convertido a su estructura en cualquier lenguaje que soporte JSON.
Con estas dos diferencias establecemos que `encoge` se aplica a *strings* para obtener *bytes*  y `json.dumps` se aplica a estructuras de Python (Ojo, que no son todas, ni tampoco clases preparadas para eso) para obtener un *string* con esta información.

La ventaja de esto es precisamente lo que mencionas, JSON es un formato legible por humanos y altamente utilizado por su versatilidad, lo cual implica que puede manejarse en diferentes entornos (cada uno con sus estructuras propias). Por esto, JSON te permite transformar contenido en algo fácilmente transportable (*string*) el cual con `encode` se puede pasar a *bytes* para su envío a través de redes.

Sus funciones opuestas hacen exactamente eso, lo opuesto, `decode` aplicado a *bytes*  retorna un *string* y `json.loads` recibe un *string* y retorna una estructura.
OJO, que no debes confundir con `json.load` o `json.dump` (sin s) los cuales sirven únicamente al tratar con archivos. Así como tener claro que Pickle con `pickle.dumps` pueden recibir casi cualquier cosa en Python y transformarlo a un *byte-string` y revertirlo con `pickle.loads`, pero esto servirá únicamente en Python.

Espero que haya quedado claro y sorry por lo largo, pero no dudes en preguntarnos cualquier cosa, saludos ✌️.

**Comment by lewebe** [comment]
@igbasly Gracias por la respuesta! Me queda claro, pero ahora tengo otra duda relacionada. Estoy intentando enviar strings desde el cliente hasta el servidor. Mi manera de hacerlo (ademas de seguir los protocolos que dice el enunciado) es hacerle `encode`, despues `json.dumps` para enviarlo, y al recibirlo el servidor le hace `decode` y despues `json.loads`. Me tira error en la última parte al usar `json.loads`. Si se lo borro me funciona bien, pero esto es considerando que por ahora solo estoy mandando _strings_ y cuando mande una imagen por ejemplo, sí voy a necesitar usar el `json.loads`. Qué debería hacer?

**Comment by igbasly** [comment]
Ok, según lo que entendí haces algo como:
* Cliente
`string` -> `encode` -> `.dumps` -> enviar
* Servidor
`decode` -> `string` -> `.loads`

Corrígeme si me equivoco, pero de todas formas explicaré un poco la lógica 😅 .

El punto está en que debes generar *bytes* para poder enviarlos, por lo tanto, todo se centra en lo que tienes y cómo obtener *bytes* desde eso.
Entonces, por lo que te comentaba antes para un *string*, con `encode` ya consigues lo *bytes*, si tienes una estructura más compleja como un diccionario o una lista, con `json.dumps` puedes conseguir un *string*  y con eso *bytes*. 
Ahora, si quieres quieres mandar una imagen, esta no entra en la categoría de "estructura de Python" ya que estaría en un archivo, por lo tanto, como sabes que debes conseguir los *bytes* para enviarlos, tienes ver como llegar dese ese archivo hasta una serie de *bytes*, lo hemos visto :wink:.
¿Se va entendiendo la lógica?

Una vez que tengas los *bytes* y los envíes al servidor según la estructura que te piden en el enunciado, cuando los recibas solo debes asegurarte de ser consistente y hacer los pasos contrarios. 
Ej: Si envías un diccionario, entonces los pasaste a *string* con JSON y a *bytes* con `encode`, por lo tanto, cuando esos *bytes* llegan al servidor, con `decode` los devuelves a un *string* y este lo pasas a un diccionario con JSON.

Creo que eso explica un poco la lógica de como tratar en general el envío de información sin ser tan explícito, de todas formas hazme saber cualquier inquietud que aún quede pendiente 👍
