### ISSUE TITLE
¿Cómo importar correctamente parámetros del archivo  .json?

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2233/syllabus#1092]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! He leído varios Issues sobre parametros.json y no me queda claro como usarlo correctamente, por ejemplo, si estoy en un archivo x.py, ¿debería al inicio hacer el json.load(parametros.json)? este me daría un diccionario que puedo llamar PARAMETROS, luego para acceder a uno específico ¿debería hacer PARAMETROS["NOMBRES_DCC"]? Tengo la duda porque siento que ingresar el *key* en el diccionario sería como harcodear ¿o no? 😟 
Espero puedan ayudarme, gracias de antemano!

**Comment by matiasmasjuan** [comment]
Hola @Jamesmoreno21 !

Efectivamente, la forma en que dices para cargar los **parámetros** es **correcta**. Entiendo tu pregunta en el sentido de que podría verse que las *keys* fueran *hardcodeadas*, pero en realidad, **no es así**. A fin de cuentas, el nombre de la **KEY** sería el nombre del **parametro**, por lo que técnicamente **nunca** debería cambiar. Lo que **sí** puede cambiar son los **valores** de esa **key**, lo cual es justamente lo que pedimos que dejen como **parámetros**.  Por lo tanto, obtener el parámetro a través de ```PARAMETROS['NOMBRE_DCC']``` sí sería correcto, ya que es un símil a lo que hacían antes con **parametros.py**, lo cual era directamente decir ```NOMBRE_DCC = valor```. En ambos casos siempre se usa el mismo NOMBRE_DCC para llamar al valor de ese parámetro, por lo cual termina siendo lo mismo y es **correcto**.

Saludos y mucho éxito con la tarea! :smile:

**Comment by Jamesmoreno21** [comment]
Genial, lo haré así entonces. Muchas gracias! 😄
