### ISSUE TITLE
Error "QCoreApplication::exec: The event loop is already running" al intentar instanciar clase cliente desde ventana inicial

### ISSUE THREAD

**Issue by tcouso** [IIC2233/syllabus#1092]
Hola!
Quiero que mi clase cliente sea instanciada por la ventana inicial, para que la conexión al servidor se lleve a cabo una vez que el usuario ingrese su nombre y presione el botón de ingreso. Intenté hacer esto haciendo que la clase cliente se instanciara una vez que se emite una señal de la ventana inicial. Sin embargo, por motivos que desconozco, cuando hago esto mi programa empieza a imprimir eternamente "QCoreApplication::exec: The event loop is already running" y luego termina cayéndose. He tratado con aproximaciones similares y me termina pasando lo mismo. Muchas gracias de antemano por cualquier ayuda! :)

**Comment by josefeliuf** [comment]
hola! no soy ayudante pero tengo el mismo error y lo solucione haciendo que la clase cliente herede de QObject, pero al hacer eso me pasa que las señales dejaron de funcionar :(

**Comment by tcouso** [comment]
Oh que fome lo de las señales :( Gracias igual por tu ayuda!
