### ISSUE TITLE
WinError 10054

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2233/syllabus#1093]
Hola! Tengo un error al usar el método recv

![E3BD7637-4737-488B-BACD-AD8DBBF6BEAA](https://user-images.githubusercontent.com/62063962/85437020-f2e38280-b557-11ea-92d2-2babb4aeaaf9.jpeg)

**Comment by mariovaldesa** [comment]
He investigado en internet pero no se que puede ser.

**Comment by jitorralba** [comment]
Hola! No soy ayudante, pero a mi me pasó lo mismo y era porque tenía un error en el cliente (en mi caso en la interfaz gráfica que tengo como atributo del cliente), lo que hice yo, fue ejecutar los métodos que se deberían ejecutar cuando ocurre el erros sin ocupar networking, para poder encontrarlo más rápido.

**Comment by gatochico** [comment]
Confirmo a @jitorralba ! 

Eso ocurre porque hay un error en el cliente, este se cae y por ende en el lado del server se cae la conexión entre el server y ese cliente y hace que el server también se caiga. Por lo tanto, tienes que encontrar el bug en el cliente 🙈

**Comment by BelenSilva1204** [comment]
Holaa, tengo el mismo error y llevo mucho tiempo intentando buscar donde esta el bug y no lo encuentro :( no sé si alguien pueda ayudarme

**Comment by mariovaldesa** [comment]
Yo antes tenia un thread en el cliente que lo mantenía “online” y lo tenía como daemon... cuando le saqué el daemon se me arregló.
No se si a alguien le sirva jajaja

**Comment by gatochico** [comment]
@BelenSilva1204, actualiza tu código en tu repositorio para ayudarte a encontrar el bug!

**Comment by BelenSilva1204** [comment]
> @BelenSilva1204, actualiza tu código en tu repositorio para ayudarte a encontrar el bug!

Como dijo mariovaldesa también tenia código que mantenía online al cliente, pero al eliminar esto la información que envía el cliente no es escuchada por el servidor(estoy probando enviar el nombre de usuario para que sea revisado), ya subí mi código

**Comment by gatochico** [comment]
Hola! 

Revisé tu código y el server sí está recibiendo los datos! El problema cae en el segundo `while `de tu función `escuchar_cliente` en el servidor: si haces print de todo lo que está pasando en esa función, puedes ver que si recibe el mensaje y entra a ese segundo while, pero nunca cumple la condición para salir y por ende, se queda pegado en ese while todo el rato y es por ello que parece que no recibió el mensaje. Si arreglas ese segundo while (El que no es `while` True, el otro), debería poder funcionar.

Saludos!
