### ISSUE TITLE
No se abre una ventana y no arroja ningún error

### ISSUE THREAD

**Issue by MagyarSplit** [IIC2233/syllabus#1093]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Como dice el título, la ventana pop_up_cerrar no se abre (se instancea y todo) a pesar de usar .show() y conectar las señales.
Quizas se me está pasando algo, por lo mismo, subí mis avances al repositorio. 
Esta ventana se abre solamente cuando un cliente solicita conectarse y hay más clientes conectados que el parametro CANTIDAD_JUGADORES_PARTIDA.

Saludos

**Comment by Juampisaez** [comment]
Hola @MagyarSplit 
Estuve viendo el avance para poder ayudarte mejor, desconozco porque no esta funcionando en primera instancia. Por ahora te recomendaria que avanzaras con lo demas y que dentro de la sala de espera hagas lo mismo que intentas hacer en pop_up_cerrar. Averiguare porque no te resulta.

Quedo atento si tienes otras dudas.

**Comment by MagyarSplit** [comment]
@Juampisaez La sala de espera y ventana de juego se abren perfectamente, lo que me parece muy raro, pues no hago nada distinto con el pop_up_cerrar.

**Comment by Juampisaez** [comment]
Ahora si, estuvimos probando con otra ayudante el problema y lo solucionamos. En primer lugar, trata de mover lo siguiente al final del __init__ del cliente:
```
self.pop_up_cerrar = Pop_up_llena(self.socket_client)
self.senal_abrir_pop_up_llena.connect(self.pop_up_cerrar.abrir)
```
luego, si eso sigue sin funcionar, coloca prints antes y despues del .show() en el Pop_up_llena.

Avisame si funciona, quedo atento

**Comment by MagyarSplit** [comment]
@Juampisaez Perdón por no responder antes, si funcionó, muchas gracias!
Igualmente me queda la duda de por qué antes no funcionaba

Saludos!

**Comment by Juampisaez** [comment]
Que bueno!! Contestando a tu duda, hay veces en que qt no responde por x motivo (puede ser cualquiera) y los prints ayudan a resolver estos problemas. También pudo haber sido porque las ventanas cuando son instanciadas fuera del __init__ generan problemas (errores propios de qt en realidad).

**Comment by Zenos-Paradox** [comment]
Hola! tengo un problema parecido. Se abre bien mi sala de espera pero, al tratar de comenzar la partida cerrando esa y abriendo la principal el cliente crashea! lo raro es que si abro la ventana principal antes (haciendo que el método que abría la sala de espera abra la principal) se abre bien, asi que no se cual puede ser el problema :(

**Comment by Juampisaez** [comment]
Hola @Zenos-Paradox, pregunta: Instanciaste tu ventana principal dentro del init y la forma que utilizas para comunicarse es a través de señales?

**Comment by Zenos-Paradox** [comment]
1 - Si
2- No, uso directamente self.ventana.show() / close(). Debería usar señales para eso?

**Comment by Zenos-Paradox** [comment]
Ya, ahora lo hice con señales y funcionó. Pensé que en la AF05 lo habían hecho sin señales, quizá me confundí. Gracias :)

**Comment by Juampisaez** [comment]
Perfecto, eso te iba a decir, la interfaces funcionan mejor con señales
