### ISSUE TITLE
Problemas con la comunicación Servidor-Cliente

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC2233/syllabus#1094]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!, estoy teniendo un problema con mi código que no he podido resolver, es sobre la comunicación entre el servidor y el cliente. Intento actualizar una ventana de PyQt5, y me tira este error en el cliente:

**QObject::setParent: Cannot set parent, new parent is in a different thread**

Si me podrían guiar sobre qué puede estar pasando se los agradecería. :smile:.

**Comment by Juampisaez** [comment]
Hola @SebaHagedorn 
Antes que nada, queria pedirte que hicieras git push de tu repo para verlo mejor. Ahora, queria saber si tu servidor y cliente se pueden ejecutar desde la consola misma?

Quedo atento :)

**Comment by SebaHagedorn** [comment]
Hola!, ya se encuentra actualizado el repo y tanto el servidor como el cliente se pueden ejecutar desde la consola. Saludos y espero tu respuesta :thinking:. Gracias!

**Comment by Juampisaez** [comment]
Hola! perdon la demora, estuve viendo tu codigo y a priori decirte dos cosas. La primera es que cuando instancies el servidor y el cliente, al momento de corregir las tarea es mejor que en el puerto coloque "localhost" en vez de el nombre de tu host. En segundo lugar, creo que lo que podría estar afectando el mostrar tu interfaz es que no lo estas manejando con señales (es una mejor practica), y por otro lado, te recomiendo sacar el la exception del metodo escuchar (cliente). Ahi se me abrio la ventana pero no muestra nada por el hecho de que no ocupas señales.

Prueba esas cosas, y si sigue sin funcionar, comenta esta issue

**Comment by SebaHagedorn** [comment]
Hola! Muchisimas gracias! Se solucionó perfectamente. Buen fin de semana!

**Comment by nicolaszanni** [comment]
Hola, me pasa el mismo problema pero no se me muestra nada en la interfaz, además de aparecerme el error subrayado en la foto. He intentado, con :
self.imagen = QLabel(), imagen = QLabel(self) y aún así no pasa anda. Traté de utilizar una senal para llamar a la función pintar_hexagono como se mencionó anteriormente, pero sigue sin funcionar.
![Captura de pantalla 2020-12-01 a las 12 59 29](https://user-images.githubusercontent.com/69498312/100764333-fca9c580-33d4-11eb-9a6c-3eb4c960a7ba.png)

**Comment by Juampisaez** [comment]
Hola @nicolaszanni 
El error puede ser que estas ocupando Qbasictimer sin Threads. Mm, puede ser que estas tratando de hacer el show en otra instancia y no en la ventana misma ?
* No subas codigo, has git push a la proxima y lo vemos

Quedo atento :)

**Comment by nicolaszanni** [comment]
Lo corregí y no hubo cambio. Acabo de hacer git push a mi repositorio

**Comment by Juampisaez** [comment]
Mm y viste si las señales llegaban? con prints por ejemplo
