### ISSUE TITLE
 Address already in use

### ISSUE THREAD

**Issue by TdelrioC** [IIC2233/syllabus#1094]
Hola, me base en el ultimo ejemplo de la clase de networking para hacer el servidor y tengo un pequeño problema.
Puedo hacer andar el servidor y conectar multiples clientes, pero cuando cierro la terminal y vuelvo a abrir el servidor me tira este error "OSError: [Errno 48] Address already in use". Si cambio el puerto vuelve a funcionar, alguien sabe como hacer que se deje de usar el puerto una vez cerrada la terminal?

**Comment by vicentevegaulloa** [comment]
Hola @TdelrioC ! 

Intenta no cerrar el servidor cerrando la ventana de la terminal. Utiliza el comando `Ctrl+C` y no deberías tener el error. 

Espero te funcione 😄
