### ISSUE TITLE
Designer: método children entrega lista vacía apesar de tener hijos

### ISSUE THREAD

**Issue by DasVaca** [IIC2233/syllabus#1095]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [-] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [-] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! tengo la siguiente estructura:
![imagen](https://user-images.githubusercontent.com/41296566/100389248-ab33bc00-300b-11eb-8fae-cf26c19e9d00.png)
Se puede ver que los labels son hijos del grid_layout, sin embargo en el código si hago self.grid_jugadores.children() me entrega
una lista vacía (le hice print).
El objeto existe, pues si le hago print se imprime su lugar en la memoria, por lo que no sé qué puede estar pasando.
¿qué podría ser?
Ojalá no cambiar la estructura, porque no quiero tener un contador o cosas así, quiero iterar sobre los hijos y ver la condiciones (si no tienen texto).

**Comment by matiasmasjuan** [comment]
Hola @DasVaca !

Investigando un poco respecto al tema, me he encontrado con el mismo problema. Sin embargo, existen **otras** formas de poder iterar sobre los **widgets** dentro de una grilla. En particular, te pueden servir de utilidad los siguientes métodos:

* ```grilla.columnCount()```: retorna la cantidad de columnas de una grilla.

* ```grilla.rowCount()```: retorna la cantidad de filas de una grilla.

* ```grilla.count()```: retorna la cantidad de elementos dentro de una grilla.

* ```grilla.itemAtPosition(x, y)```: retorna el widget dentro de la grilla en la posicion x, y. Por ejemplo, el elemento en el (0, 0) de la grilla

* ```grilla.itemAtPosition(x, y).widget()```: retorna qué widget que está en la posición x, y. Puede ser útil  para obtener el Label que está en esa posición

* ```grilla.itemAt(x)```: retorna el widget x de la grilla.

Recuerda que puedes revisar más de estos métodos según la [Documentación oficial](https://doc.qt.io/qt-5/qgridlayout.html)

Saludos! :smile:

**Comment by DasVaca** [comment]
Oki! gracias 💯
