### ISSUE TITLE
Envio de cartas

### ISSUE THREAD

**Issue by aipostigo** [IIC2233/syllabus#1095]
Hola! Tenia una duda con respecto al envio de cartas, en el enunciado aparece que las tenemos que enviar de cierta forma, pero es posible que yo envie todas las cartas 1 vez respetando esa serializacion y despues trabajar desde el back end desde el cliente? o cada vez que necesite una carta tengo que serializarla y enviarla de esa forma.

**Comment by vicentevegaulloa** [comment]
Hola @aipostigo !

En el enunciado se pide que se envíen las cartas cada vez que se roba o se juega, por lo que no es válido enviarlas todas de una vez. 

Espero haberte ayudado 😄
