### ISSUE TITLE
Loop infinito al escuchar el servidor y viceversa 

### ISSUE THREAD

**Issue by magdalenarojas** [IIC2233/syllabus#1096]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holaa, cuando el cliente intenta escuchar el servidor se genera un loop infinito (el programa recibe bien el mensaje, pero después como que sigue intentando recibir mensajes) y no se como solucionarlo, ya que para esta parte me guíe de las actividades y ayudantía y siento que no debería tener problema 
pd: mi código ya está arriba

**Comment by EduardoIllanes** [comment]
Hola @magdalenarojas !
El loop es necesario por que el cliente necesita estar "atento" ya que puede recibir en cualquier momento un mensaje del servidor. Respecto al problema que se te genera, estuve probando tu código y este se produce en la linea 57, ya que estas mandando a decodificar bytes vacíos, cosa que no es posible. Debes mandar a decodificar **solamente si existe un mensaje**. En los [ejemplos de los contenidos](https://github.com/IIC2233/contenidos/blob/master/semana-14/3-ejemplos.ipynb) se muestra como manejar esto. Mucho éxito con tu tarea 😄 y quedo atento por si te siguen quedando dudas.

**Comment by magdalenarojas** [comment]
gracias!
