### ISSUE TITLE
Directorio para archivos UI y sprites

### ISSUE THREAD

**Issue by milosoria** [IIC2233/syllabus#1096]
Hola! tengo la duda sobre en qué directorio deben ir los archivos ui y los sprites, si en cliente o en el content root?
De antemano, muchas gracias!

**Comment by jirarrazabal** [comment]
Como las interfaces solo se utilizan en el lado del cliente, lo mas adecuado es que se encuentren en la carpeta client. Aun así, recuerda especificar todo en tu README. Suerte!

**Comment by tedroppelmann** [comment]
En la ayudantía dijeron que los sprites tenían que estar del lado del servidor :( mi duda es si los puedo dejar afuera..

**Comment by jirarrazabal** [comment]
Perdón tenía una confusión. Para aclarar:
-Los archivos .ui en la carpeta client.
-Los sprites de las cartas deben estar si o si en el servidor.
-Cosas como el logo u otro tipo de sprites pueden ir en el cliente.
-Dentro de lo posible no poner cosas fuera del cliente o del servidor, porque sino no se estaría cumpliendo del todo la separación mediante carpetas.
Esta es la respuesta definitiva con respecto a los sprites. Mucha Suerte!

**Comment by kipasten** [comment]
Perdona la duda pero eso significa que podemos mover la carpeta de sprites adentro de la carpeta del servidor??

**Comment by jirarrazabal** [comment]
Hola @kipasten ! Si, puedes mover los sprites a la carpeta del servidor. Pero te recomiendo que dejes algunos en la carpeta del cliente, para utilizarlos en su interfaz. Los sprites que deben estar si o si en la carpeta del servidor son las cartas.
