### ISSUE TITLE
duda con git y gitignore

### ISSUE THREAD

**Issue by eliasbruchfeld** [IIC2233/syllabus#1097]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Tengo una duda relacionada con gitignore y la otra con git en general.

1. Para esta tarea tengo muchas carpetas dentro de otras carpetas, entre server, client, backend, frontend, etc. Todas estas me generaron una carpeta __pycache__ distinta. ¿Hay alguna forma para decirle a gitignore que las quiero ignorar todas? O tengo que hacer el proceso largo de ignorarlas una por una.

2.  En la issue #561 explican como borrar un archivo de mi repositorio de github sin borrarlo del repositorio local. ¿Hay alguna forma de hacerlo con una carpeta completa? Cuando lo intento de esa misma manera me tira error.

**Comment by DCCollao** [comment]
Hola @eliasbruchfeld!
Respondiendo tu pregunta según la separaste:

1. Si en tu `.gitignore` escribes `__pycache__`, esta carpeta debería ser ignorada en todas sus apariciones dentro del repositorio, según [esto](https://github.com/martinohanlon/flightlight/issues/1), así que no debes preocuparte de ignorarlas una a una!

1. El proceso para borrar archivos y carpetas es distinto, pues una carpeta contiene más archivos o carpetas dentro de ella, mientras que un archivo no puede contener archivos dentro de él mismo. Es por esto que para eliminar una carpeta debes agregar el argumento `-r` (recursive) a la carpeta a eliminar.
Un ejemplo de cómo quedaría el comando es el siguiente:
`git rm -r --cached carpeta`
