### ISSUE TITLE
¿send o sendall?

### ISSUE THREAD

**Issue by NikiHV** [IIC2233/syllabus#1097]
Hola!
Tengo una duda. En los cuadernos y ejemplos a veces se usa el método `socket.send` y otras veces `socket.sendall`. ¿Cuál es la diferencia y cuál nos recomiendan usar? Encontré en internet que se sugería usar `sendall`, pero entonces no sé por qué se usó `send` en los ejemplos de los cuadernos, ¿da lo mismo para efectos de lo que haremos nosotros?

Saludos!!

**Comment by igbasly** [comment]
Hola @NikiHV :smile:
Como tú dices, realmente no hay gran diferencia para efectos de lo que se ve en el curso, pero de todas formas lo aclaramos.
* `send` es lo que se denomina una función de **bajo nivel**, esto quiere decir que está implementada de forma que su interacción es más cercana al nivel del *hardware* que la de python. Por ello, está función puede ser más propensa a generar errores, ya que su implementación le permite enviar menos *bytes* de los solicitados, pero indicando cuántos pudo enviar. 
Ej:
Si a se intenta enviar un arreglo de *bytes* de largo x con `send`, este retornará el número de bytes envíados que en este caso se guardó en `restantes`, este puede ser menor o igual a x.
```python
data = # Bytearray de largo x
restantes = send(data)
```
* `sendall` por otro lado, es una función de **alto nivel** definida en Python y única del lenguaje. Esta función utiliza dentro a `send`, pero a diferencia de la anterior siempre continuará enviando todos los *bytes* solicitados hasta terminar o que un error ocurra.

Nuevamente, para efectos del curso no hay gran diferencia con usar una u otra, por lo que eres libre de utilizar la que estimes conveniente. 
Avísame algo no quedó claro, saludos 🙌 .
