### ISSUE TITLE
duda aceptar clientes

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2233/syllabus#1098]
En la ayudantía y en la actividad vi que se usa esta linea "client_socket, address = self.socket_server.accept()" y estoy confundida a que se refiere con "address" (tengo otras preguntas al respecto pero primero necesito entender eso jaja"

**Comment by igbasly** [comment]
Hola @maggiemunoz :v:
Cuando uno tiene un `socket_servidor` como *socket* en modo servidor, y se acepta una conexión a este mediante `socker_servidor.accept()`, el método retornará dos cosas:
* La instancia de *socket* que permite la comunicación entre el servidor y el del cliente respectivo, *client_socket*.
* Y una tupla, que se llamó `address`, la cual contiene la dirección y el puerto con los cuales se estableció la conexión en el lado del cliente.

Como usualmente `address` contiene valores que ya conocemos, no es relevante para el programa, pero si es muy necesario contar con el *socket*  para poder escuchar y enviar datos al cliente.

Espero que esto aclare la duda y quedo atento por más consultas, saludos 🙌 .
