### ISSUE TITLE
Manejo excepciones de conexión

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#1098]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!

A la hora de manejar excepciones me surgieron un par de dudas con respecto al cierre de conexión forzada que no he podido solucionar. 
```
try:
        while True:
            input("Presione Ctrl + C para cerrar el servidor\n")
    except ConnectionResetError:
        print("Se ha desconectado un cliente")
    except KeyboardInterrupt:
        print("Cerrando el servidor...\n")
        sys.exit()
```
Este código está en el `main` del servidor. Lo único que captura es la interrupción forzada de parte del servidor. 
La interrupción forzada de parte del cliente y del servidor funcionan sin problema. Sin embargo, no logro capturar los errores del cliente cuando la interrupción es de parte del servidor, y viceversa. 
Cuando interrumpo desde el cliente, en el servidor sale `ConectionResetError (10054)`.
Cuando interrumpo desde el servidor, en el cliente captura el error, pero aunque haga `sys.exit()`, el programa sigue activo y no entiendo por qué si todos los threads son deamon.
```
except ConnectionResetError:
            print("Error de conexión con el servidor")
```
Tengo el código anterior en la clase Cliente, me imagino que el programa sigue porque el `exit()` no está en el `main`.

Mis dudas son: ¿Cómo puedo capturar estos errores de manera eficiente?, ¿Cómo puedo terminar la ejecución del cliente, cuando deja de correr el servidor, y lo mismo viceversa?

¡¡Muchas gracias!!

**Comment by EduardoIllanes** [comment]
Hola @amahns1! Perdón por la demora en responder, no se si ya lo habrás solucionado pero aquí va mi respuesta de todas formas. Para solucionar tu problema debería bastar con cerrar el `socket` del cliente y hacer `exit` dentro de la excepción del cliente. Saludos!

**Comment by amahns1** [comment]
Hola!
No te preocupes.
```
try:
            self.connect_to_server()
            self.listen()
        except ConnectionError:
            print("Conexión terminada.")
            self.socket_client.close()
            self.isConnected = False
            exit()
```
Tengo esto en el `cliente`, pero en caso de forzar la salida o un error accidental el programa no termina correctamente.

**Comment by EduardoIllanes** [comment]
Me puse a revisar tu código y efectivamente ser cierra la conexión con el servidor pero tu ventana sigue funcionando. Por lo que una manera mas efectiva seria agregarle una señal que "cierre" la ventana una vez que se termine la conexión con el servidor. Espero que te sirva 😄

**Comment by amahns1** [comment]
Entiendoo.
Muchas gracias!!
