### ISSUE TITLE
señales en QThread

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#1099]
intentando solucionar un problema de que las ventanas no se me abren cuando las intento abrir en un thread, me dijieron que usase señales para que se abrieran, pero después de mucho intentarlo, mis señales no son enviadas! O quisas son enviadas, pero no entran a la funcion asociada (mediante connect)

pd: subi todos mis codigos por si eso ayuda

**Comment by KnowYourselves** [comment]
Hola @felipehen!

Ahora el problema es que estas conectando la señal en el thread. Debes conectar la señal antes de entrar al thread (al igual que todas las demás señales) y utilizarla dentro de este.

Éxito!

**Comment by felipehen** [comment]
Gracias!! ahi lo solucione
