### ISSUE TITLE
Señal (pyqtSignal) no se emite desde Cliente (o se emite y no se recibe).

### ISSUE THREAD

**Issue by clementethompson** [IIC2233/syllabus#1099]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ]X Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo el siguiente problema:

Estoy modelando el problema de forma similar a la AF05. Es decir, tengo una clase Cliente que se comunica con el servidor (threads clásicos). Dentro de esa clase, creo una instancia de la clase Controlador (que hereda de QObject) de la forma self.controlador = Controlador() (**controlador es contenido en cliente**). La clase Controlador se encarga de manejar los eventos relaciondos con las interfaces. 
Las señales que estoy usando corresponden a atributos de clase de Controlador y son conectadas a métodos en el constructor de esta misma clase.  Cuando **emito la señal específica desde el cliente** (que recibe los datos del servidor) de la forma **self.controlador.nombre_señal.emit(datos)** no pasa absolutamente nada (el programa se congela) como si la señal estuviese desconectada. La verdad es que no tengo idea cual puede ser el problema.

**Comment by lucasprato** [comment]
Hola @clementethompson,

Antes de hablar específicamente de tu problema, quiero hacer énfasis en algo. Esta tarea se parece a la anterior en el sentido de que un cliente se separa entre un frontend (interfaz gráfica) y un backend (lógica), y ambas partes se comunican a través de señales. Esta tarea incluye además que cada cliente (con su propio frontend y backend) se conecta con un servidor. El servidor se conecta con el cliente a través de su backend usando señales. 

Teniendo en vista lo anterior, el problema que tienes puede originarse de distintas fuentes. Verificaste que el mensaje del servidor llega a ese cliente específico? Si llega al backend del cliente, verificaste si llega a la parte del código en donde se emite la señal al frontend? Verificaste dicha señal efectivamente esté bien conectada? Mi punto con esto es que trates de localizar efectivamente dónde ocurre de que el mensaje del servidor no llega al frontend.

> (el programa se congela)
Con esto te refieres a que solamente no llega la señal, o hay otras partes del programa que se ven comprometidas con su funcionamiento normal (antes de enviar la información)?

Ojalá esto de ayude!

**Comment by clementethompson** [comment]
Hola, en relación al primer párrafo entiendo lo que dices y creo tener modelado el programa de esa forma. Mi problema es que cuando envío una instrucción desde el servidor el cliente o clientes es info se recibe ok, pero al momento de establecer comunicación del cliente con su front end (debido a la instrucción recibida del servidor) la señal "no se emite" cuando explicitamente la estoy emitiendo. En todo caso hice un push por si quieres echarle una mirada al código. Gracias y saludos.

**Comment by lucasprato** [comment]
@clementethompson, vi el código y ocurre lo siguiente: las señales mostrar_sala_espera_signal y actualizar_jugadores_signal son atributos internos de la clase Controlador, por lo que no son accesibles a través de una instancia (ej. controlador.mostrar_sala_espera_signal). 

Te recomiendo que en vez de llamar las señales desde la instancia, llames a un nuevo método en Controlador que reciba la lista de usuarios y que este método sea el que accione las señales. Lo probé y funciona perfecto así.

Éxito en la tarea!!

**Comment by clementethompson** [comment]
Ok. Gracias te pasaste!
