### ISSUE TITLE
Editores de texto recomendados?

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233/Syllabus#11]
Hola, paso por aquí para consultar sobre editores de texto recomendados (que no sea PyCharm porque hace mi computador más lento)

Ojalá sean básicos y que no ocupen mucha memoria RAM, gracias

**Comment by flobarrios** [comment]
Hola!! personalmente te recomiendo Atom. Te dejo este [link](http://www.marinamele.com/install-and-configure-atom-editor-for-python) en donde se indican paquetes y configuraciones para Python.

Saludos!

**Comment by cilopez** [comment]
Sublime Text también apaña y es super simple

**Comment by hanavarrete** [comment]
Los tutoriales de como instalarlos están en la wiki, en [https://github.com/IIC2233/Syllabus/wiki/Interfaces-de-Desarrollo](este) link

**Comment by ifcarrera** [comment]
También recomiendo Atom!
Es muy amigable y personalizable.
Saludos :)

**Comment by gabrielpinkman** [comment]
Gracias a todos!

**Comment by nebil** [comment]
[:atom:](https://atom.io/) → haga clic para aumentar los niveles de dopamina.

Eso sí, quiero señalar que Atom —que, por cierto, es el editor que actualmente uso— no cumplirá con ninguno de tus dos requisitos, ya que es bastante completo y te pedirá mucho más RAM que un editor promedio del mercado. No obstante, pienso que para el desarrollo del curso, no te conviene utilizar un editor “básico”, ya que existen funcionalidades que querrás tener mientras escribes código.

Por último, como alternativa, podrías echarle un vistazo a [Visual Studio Code](https://code.visualstudio.com/), que es un editor que he querido probar hace algunos meses.
