### ISSUE TITLE
Duda sobre el Ranking de la tarea

### ISSUE THREAD

**Issue by rgmorales1** [IIC2233/syllabus#11]
Con respecto al ranking de la tarea y donde guarde todos los puntajes, ¿debo mostrar el puntaje junto al nombre del jugador o solo el puntaje?. En el caso de que sea junto al nombre del jugador, ¿Al mostrar el Ranking, que sucede si hay 2 jugadores con el mismo puntaje?, ¿tengo que mostrarlo a los 2 en el ranking verdad?. Por ejemplo si los 10 primeros puntajes son iguales, ¿cómo ordeno quien va primero y ultimo en el Ranking?

**Comment by DCCollao** [comment]
Hola!


- En el ranking deben aparecer tanto nombre de usuario como el puntaje obtenido por ese usuario.

- La forma en que decidas cómo ordenar los puntajes repetidos para mostrar el top 10 queda a tu criterio.

Éxito con la tarea!
