### ISSUE TITLE
Link Instalación Atom (Windows 10)

### ISSUE THREAD

**Issue by LucaSpiniello** [IIC2233/syllabus#11]
- **Sistema Operativo:** windows 10
- **Programa a instalar:** atom

- Foto del error:

- Descripción del problema: me descargue python, git, jupyter y pyQt5, todos los programas que pedían,para luego descargarme atom. Al seleccionar el link  de descargar el instalador mas reciente, me envio a github donde aparece una lista de 18 "Assents", descargue el primero que se llamaba "atom-1.45.0-delta.nupkg", sin embargo cuando intento abrirlo me arroja error.

**Comment by tocococa** [comment]
probaste descargando atom desde [este link?](https://atom.io/)

**Comment by LucaSpiniello** [comment]
ya me funciono gracias
