### ISSUE TITLE
En Mac: Problemas con el setup de git (siguiendo en video de canvas)

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#11]
Prerrequisitos
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Problema

Siguiendo las instrucciones del video de instalación de git en mac, no puedo pasar de este paso porque me dice que el comando no existe.

''''
Last login: Sat Aug 21 20:04:28 on ttys001

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Fernandas-MacBook-Air:~ fernandadelpinozegers$ git --version
git version 2.30.1 (Apple Git-130)
Fernandas-MacBook-Air:~ fernandadelpinozegers$ brew install git
-bash: brew: command not found
Fernandas-MacBook-Air:~ fernandadelpinozegers$ 
'''''

**Comment by agucova** [comment]
Parece ser un duplicado de #9, aunque este macOS usa una versión mas nueva que viene con `zsh` y no `bash`, por lo que el comando de `PATH` es distinto.

**Comment by pedroriosg** [comment]
@Fernanda1232123 pudiste resolver el problema?

Saludos

**Comment by Fernanda1232123** [comment]
Sí, ya está resuelto!
