### ISSUE TITLE
Repaso miércoles 8 marzo

### ISSUE THREAD

**Issue by AmbrosioV** [IIC2233/Syllabus#11]
Mandaron un mail diciendo que habrían dos sesiones de repaso sobre los temas de introducción a la programación, y dos horarios distintos (11.30 y 14.00 hrs) mi duda es si se vera materia distinta o sera el mismo repaso en dos horarios distintos.
Saludos

**Comment by andresfdezc** [comment]
Hola! Es el mismo repaso

**Comment by AmbrosioV** [comment]
Gracias!
