### ISSUE TITLE
Se pueden traer apuntes a la actividades con nota? Se puede ocupar google?

### ISSUE THREAD

**Issue by perezpefaur** [IIC2233/syllabus#11]
Gracias!

**Comment by KnowYourselves** [comment]
Hola!

En las actividades sumativas lo único que esta prohibido es copiar código de compañeros, puedes traer apuntes y usar Google

Saludos!

**Comment by Mahund** [comment]
Hola @perezpefaur!

Para complementar la respuesta de @KnowYourselves hay que recordar que *todo código* que utilices que **no** haya sido de tu autoría (google, ayudantias, etc) debe ser **citado**, para evitar cualquier tipo de malentendido al momento de corregir.

Mucho éxito en la actividad!

**Comment by Juaco97** [comment]
> Hola @perezpefaur!
> 
> Para complementar la respuesta de @KnowYourselves hay que recordar que _todo código_ que utilices que **no** haya sido de tu autoría (google, ayudantias, etc) debe ser **citado**, para evitar cualquier tipo de malentendido al momento de corregir.
> 
> Mucho éxito en la actividad!

La cita debería ir comentada en el código? Lo pregunto ya que en las tareas se dijo que cualquier extracto de código obtenido de internet debía ir explicado en el README.

**Comment by Arcoirisky** [comment]
Lo mejor es hacerlo en ambos, para que al revisarlos nos topemos con las citas y se ganen nuestro amor (?)

Igual dejarlo solo en el README es legal pero deben señalar bien la parte del código que utilizaron, el porqué y donde lo ubicaron. Incluso si lo sacaron de material presente o pasado del curso. 

Descansen!! Mañana les irá bien :D Confiamos en ustedes <3
