### ISSUE TITLE
Problema Linux Pop Os! al querer instalar pycodestyle para Python 3.7

### ISSUE THREAD

**Issue by Dyotson** [IIC2233/syllabus#11]
Hola, estoy trabajando en Pop Os! y intente instalar pycodestyle mediante pip, pero al intentar usar pip en python 3.7, tira el siguiente error:

```
dyotson@dyotsonpop:~/UNIVERSIDAD/PROGRAMACION AVANZADA/codigos$ /bin/python3.7 /home/dyotson/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py pip install -U pycodestyle --user
Traceback (most recent call last):
  File "/home/dyotson/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py", line 26, in <module>
    runpy.run_module(module, run_name="__main__", alter_sys=True)
  File "/usr/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 19, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils.util' 
```

Intente reinstalar pip3 pero sigue sin funcionar.

**Comment by Drpinto1** [comment]
¡Hola!

Pareciera que tienes un error con las dependencias de pip, intenta con estos comandos para instalarlas:

`sudo apt-get install python3-distutils`
`sudo apt-get install python3-apt`

Y luego intenta nuevamente la instalación. En caso de que esto no te funcione, te recomiendo leer (y probar) las alternativas del [post de AskUbuntu](https://askubuntu.com/questions/1239829/modulenotfounderror-no-module-named-distutils-util) dónde encontré esta solución.

Avísame si te funciona y si no, qué errores te aparecen.
¡Saludos!

**Comment by Dyotson** [comment]
No funciono ninguna de las opciones, no tengo un problema con pip3, de hecho funciona perfecto para Python 3.8, el problema es que pareciera que no existiera pip para python3.7, por lo cual no puedo instalar ningun modulo para esta version de Python... ¿Alguna recomendacion?

**Comment by Drpinto1** [comment]
Algo que se me ocurre es usar `python -m pip install` en lugar de `pip install`, intenta usar:

`python3 -m pip install` 
o en su defecto
`python3.7 -m pip install`

Dependiendo de cuál de ellos está asociado a 3.7

Avísame si te funciona :smile:

**Comment by Dyotson** [comment]
Ya lo resolvi! Por si alguien tiene Linux y tiene el mismo problema, sigan los pasos en este link:

https://linuxize.com/post/how-to-install-python-3-7-on-ubuntu-18-04/
