### ISSUE TITLE
Horario de consulta para las tareas

### ISSUE THREAD

**Issue by beayancan** [IIC2233/Syllabus#11]
Durante la primera clase se entregó la información de que durante el semestre iba a existir un horario para responder dudas sobra las tareas, por lo visto este sería un horario único justo después de las ayudantías.  Es por esto que quería saber si cabe la posibilidad de que exista otra instancia, ya que puede existir tope de horario con otra cátedra o ayudantía.

**Comment by FernandoPieressa** [comment]
Hola!

Lamentablemente no podremos tener otro horario para sala de ayuda por ahora, sin embargo elegimos ese modulo para asegurarnos que la gran mayoría de los cursos no tenga tope, puesto que por el modulo de cátedra del ramo J:45 y ayudantía M:4, prohíbe que se pueda tomar cualquier ramo que sea MJ:5 o M:45, por lo que los casos donde existe el tope es mínimo, mientras que en otros horarios habría mas riesgo de que algún alumno tenga tope

Si eres uno de estos pocos casos, lamentablemente no podremos hacer mucho al respecto, pero siempre tendremos la disposición de responder tus dudas en issues.

Saludos!
