### ISSUE TITLE
Conocer valor de variables durante la ejecucion de un Script [Python general]

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#110]
Hola! Como puedo conocer **en todo momento** el valor de las distintas variables en mi programa de forma mas profesional que `print()` ?
Me imagino se requiere de software especial.

**Comment by akaminetzkyp** [comment]
En PyCharm hay un debugger que te muestra todas las variables en cada momento. Puedes ir avanzando línea por línea. Es muy útil!
