### ISSUE TITLE
magos inicial?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#110]
En la seccion 7 (batalla), a qué se refiere numeros de magos inicial? (Se me ocurre que puede ser el 75% de la poblacion maxima de magos, la cantidad de magos antes de la batalla, o la cantidad de magos antes de aplicar la funcion `minimo`).

**Comment by ptflores1** [comment]
Hola !
Se refiere a la cantidad de magos antes de la batalla.
Saludos !
