### ISSUE TITLE
Archivos en .gitignore

### ISSUE THREAD

**Issue by isidoragutierrez** [IIC2233/Syllabus#110]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! En el enunciado de la tarea, si bien se específican los archivos que debe estar en .gitignore, no se especifica nada sobre el archivo **"test_todos.py"**. Este último **¿debe ir en .gitignore o se debe subir al repositorio personal?** Pregunto porque es uno de los archivos que no se debe modificar, por lo que por definición debería ir en .gitignore pero en la sección que especifica eso en la tarea no se menciona.

Muchas gracias de antemano.

**Comment by Juampisaez** [comment]
Holaa @isidoragutierrez 👋🏼
Efectivamente, el archivo que mencionas no debe ser modificado y bajo la finalidad del `.gitignore`, no debiese subirse. Sin embargo, en el enunciado no se especifica que ese archivo en particular se debe agregar al `.gitignore`. 
Por lo tanto, si lo agregas o no, no debiese afectar la corrección de tu tarea. De igual manera, te recomiendo agregarlo al `.gitignore`, para ser consistente con el objetivo de este archivo.

Quedo atento a cualquier duda,
Saludos,

**Comment by isidoragutierrez** [comment]
Muchas gracias!!!
