### ISSUE TITLE
Cambio moneda a DCC

### ISSUE THREAD

**Issue by nachocontreras** [IIC2233/Syllabus#110]
Hola! Tengo las siguientes dudas con relación al cambio de una moneda AAA a DCC:

Si el saldo actual es:
50.000 RUP
60.000 BAN
250.000 DCC

Al momento de mostrar el saldo, debo mostrar que tiene 360.000 DCC? o la relacion AAA y DCC no necesariamente es 1-1?
Al hacer upgrade de Trader a Investor, debo quedar con 60.000 DCC o no se puede realizar el upgrade debido a que tiene 250.000? Si es que queda con 60.000 DCC, como cambia la cantidad de las otras divisas ?

Gracias!

**Comment by fgbruna** [comment]
@nachocontreras Segun tu el balance se debe guardar solo en DCC ? o estás preguntando  si **solo al momento de mostrar el balance** lo debes hacer en términos de DCC?

**Comment by nachocontreras** [comment]
Si solo al momento de mostrar el balance, ya que cuando se quiera realizar el upgrade se deberia tener los 300.000 DCC reales, no como un conjunto de las otras monedas.
cierto?

**Comment by fgbruna** [comment]
Yo entiendo como que hay que tenerlos independiente de las otras monedas y al mostrar el balance hay que mostrar la cantidad de cada moneda,a menos que no existan mercados de la forma DCCXXX...

**Comment by nachocontreras** [comment]
En #54 sale: 
"_a la hora de consultar el saldo debes retornar la cantidad de monedas que tiene de cada divisa, además deberás transformar cada moneda a DCC y retornar el total del usuario en esta moneda_". 
De ahi mi duda en cuanto a como se transforma de DCC a otra divisa.

**Comment by fgbruna** [comment]
Aaah Ok, no había leído esa issue, ojalá algún ayudante pueda aclararlo, aunque yo por mientras haría el cambio 1:1 nomás jaja

**Comment by iqacevedo** [comment]
Hola !

@nachocontreras acabo de contestar como hacerlo en #54 . Debes mostrar lo que dices el saldo de cada moneda y el saldo total pasandolo a DCC. Respecto a tu segunda duda, no podrías realizar el upgrade en ese caso porque debes tener en tu poder 300.000 DCC reales.

Saludos !

**Comment by nachocontreras** [comment]
Gracias !!!
