### ISSUE TITLE
Duda respecto al aumento de parametros al subir de nivel

### ISSUE THREAD

**Issue by rir001** [IIC2233/Syllabus#110]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
En el enunciado se indica que al subir de nivel "se deberá sumar a los atributos de Vida, Ataque, Defensa y Velocidad un valor entre MIN_AUMENTO_ENTRENAMIENTO y MAX_AUMENTO_ENTRENAMIENTO aleatoriamente", este valor aleatorio es el mismo para cada atributo o es un valor independiente para c/u?

**Comment by MrNachoX** [comment]
Hola @rir001
El valor no es necesariamente el mismo para cada atributo, son 4 valores independientes.
