### ISSUE TITLE
Duda corrección tarea

### ISSUE THREAD

**Issue by kowal-sky** [IIC2233/Syllabus#110]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!
En el apartado 11 del enunciado se recalca que "sólo se corrigen tareas que se puedan ejecutar", por lo que tengo una duda acerca de si una tarea sigue siendo válida al no poder ejecutarse únicamente desde un git bash (imagen adjunta).

![image](https://user-images.githubusercontent.com/127861995/228145733-60d7b808-e7c4-49f1-9817-1a23ce8700c7.png)

Mi situación es que mi tarea es perfectamente funcional al ejecutarla desde VS code o desde la terminal de mi notebook, pero al intentarlo en un git bash el programa se detiene luego de recibir el primer input.

De antemano agradezco su ayuda!

**Comment by elisahonorato** [comment]
Hola @kowal-sky. Intenté correr tu tarea desde mi pc, y efectivamente no funciona. Te recomiendo investigar más sobre la librería os, ya que no estás indicando de manera correcta la ubicación de la carpeta "/Archivos".  Avísame si te queda claro

**Comment by kowal-sky** [comment]
No me queda claro.
Tendrá que ver mi sistema operativo?
Tengo windows y al usar las herramientas que trabajan con windows todo funciona bien, mientras que en un git bash(lo que tengo entendido que trabaja con linux, no estoy completamente seguro) el programa no funciona.

**Comment by elisahonorato** [comment]
Si, estaba corriendo desde tu repositorio la tarea, pero en realidad se evaluará desde la carpeta de tu tarea. Revisé esa parte del código y funciona correctamente desde un MacOs, asi es que no te preocupes.

**Comment by kowal-sky** [comment]
ok, muchas gracias
