### ISSUE TITLE
Problema con Anaconda

### ISSUE THREAD

**Issue by felipecs13** [IIC2233/syllabus#110]
Estaba en Computación: ciencia y mundo digital, me dicen que es un problema tener instalando Anaconda para la tarea. Que deberia hacer?

**Comment by entamburini** [comment]
Hola!,

Reafirmo lo que te dijeron, desinstala todo (Anaconda, Python, Pycharm en caso de que lo tengas) y reinstala Python y (si es que lo tienes) Pycharm, en ese orden :) 

Que estés bien! ^^

**Comment by fjhuanca** [comment]
Y al tener instalado Spyder pero sin Anaconda? Causaría algún problema?
