### ISSUE TITLE
T0. Consecuencias de abandonar grupo con dos integrantes

### ISSUE THREAD

**Issue by Incruen** [IIC2233/syllabus#110]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Según el enunciado, para crear un grupo válido en el sistema este debe tener al menos dos integrantes considerando al usuario que crea al grupo. **Al momento de abandar un grupo formado por el usuario (yo) y otro contacto, ¿debo borrar el grupo que ha quedado con un solo integrante?**

**Comment by RafaelEdwards** [comment]
Holaa!

En el caso en que el grupo quede con sólo un integrante, NO debes borrarlo, las condiciones que mencionas son sólo para crear los grupos. En el caso en que el grupo quede vacío, queda tu criterio si lo borras del csv o lo mantienes sin integrantes. De todas formas recuerda especificarlo en tu README.

Espero haberte ayudado y suerte en tu tarea :).
