### ISSUE TITLE
Importar variables de otro módulo

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2233/syllabus#110]
Hola! Quiero importar el nombre de usuario (variable dentro de una función) pedido al inicio del código a otro módulo, pero no sé cómo hacerlo y tampoco lo encuentro en internet. Cómo lo podría hacer?

**Comment by Tito0906** [comment]
Holaa @beatrizacuna! En esta issue [https://github.com/IIC2233/syllabus/issues/88](url) se trata cómo importar la función y eventualmente la variable. Quedaré atento por si esa issue no soluciona lo que quieres.

**Comment by beatrizacuna** [comment]
Es que no quiero pedir input nuevamente, sino que la variable usuario se "guarde" y la pueda importar a mi otro módulo. :)

**Comment by Tito0906** [comment]
Holaa @beatrizacuna, ¿tu variable se encuentra definida dentro de una función o está libre dentro del archivo?

**Comment by beatrizacuna** [comment]
holi, dentro de una función :)

**Comment by Tito0906** [comment]
Holaa @beatrizacuna, si tu variable se encuentra dentro de una función, entonces no es posible exportarla hacia afuera a menos que sea parte del return de la función. Esto se debe a que la variable existe sólo dentro de la función y no afuera de ella. 
Por otro lado, si es posible exportar variables que se encuentran solas, es decir, fuera de funciones y objetos mediante _from modulo import variable_. Estas últimas variables se denominan variables globales, pero su uso no está recomendado para importar y se podría penalizar en futuras tareas (en esta no). Lo ideal es importar funciones y objetos. 

Quedo atento por si tienes más dudas.

**Comment by Tito0906** [comment]
Hola @beatrizacuna, complemento y corrijo el comentario anterior. El uso de variables globales **si** es una mala práctica que podría conllevar descuentos para esta tarea.

Saludos!
