### ISSUE TITLE
El Cliente crashea cuando cierro la terminal de vscode

### ISSUE THREAD

**Issue by sustancia** [IIC2233/syllabus#1100]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, cuando ejecuto mi código del cliente y **cierro la terminal** el vscode crashea:c, me di cuenta de que el crasheo ocurre cuando intento trabajar con la interfaz grafica(es decir, cuando instancio la clase de mi interfaz), pero no entiendo porqué, puedo suponer que el thread que escucha al servidor puede quedar corriendo, pero es daemon = True, así que ni idea.
pd: ya subí a mi repositorio lo que llevo

**Comment by EduardoIllanes** [comment]
Hola @sustancia! Perdón por la demora en responder, no se si ya lo habrás resuelto pero aquí va mi respuesta. Generalmente vscode se crashea cuando existe un loop infinito por lo que puedes partir revisando tus loops. Si no es eso revisa si no estas sobrecargando la interfaz con muchos threads o algo por el estilo, eso también puede causar que se crashee. Si no es ninguno de lo anteriores puede ser que el `daemon = True` te este causando problemas, en la issue #1101 se trata sobre porque escuchar con daemon puede causar problemas al escuchar el servidor. Saludos!
