### ISSUE TITLE
modulo logging

### ISSUE THREAD

**Issue by Mjtala** [IIC2233/syllabus#1100]
Hola, quería saber si se puede importar el módulo logging.

**Comment by jirarrazabal** [comment]
Las dudas con respecto a que módulo se puede importar o no deben ser preguntadas en la Issue #1026. Suerte!

**Comment by Mjtala** [comment]
es que no aparece nada de logging

**Comment by jirarrazabal** [comment]
Si te fijas, al final de la Issue #1026 hay una sección donde puedes preguntar por librerías en particular que no fueron mencionadas.
