### ISSUE TITLE
problema al enviar mensaje desde el servidor

### ISSUE THREAD

**Issue by camirojasguajardo** [IIC2233/syllabus#1101]
* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! al tratar de enviar el nombre al cliente desde el servidor, me aparece el siguiente error (en la terminal del servidor): "ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto". Busqué en internet pero no me queda claro qué podría estar mal:( sos

Saludos!

**Comment by Juampisaez** [comment]
Hola @camirojasguajardo 
Antes que nada me gustaría saber si el servidor y el cliente se pueden ejecutar desde la consola, es decir, se logra la conexión, o esto es al momento de ejecutar el cliente y al tratar de enviar los primeros mensajes.
Si puedes git push para actualizar tu repo en github mejor aun, asi lo veo directamente.

Quedo atento :)

**Comment by camirojasguajardo** [comment]
@Juampisaez hola! sii, el cliente se logra conectar al servidor y se le otorga un nombre, el error se produce al momento de enviarle el nombre al cliente:(
- ya hice git push -

**Comment by Juampisaez** [comment]
Perfecto, ya lo pude observar.
Me da la impresión de que tu error esta en el metodo codificar_mensaje más que nada ya que el error lo arroja hacia el metodo enviar que a su vez llama al metodo que ya te mencione. Lo que te recomendaría también es usar prints, para ver de forma mas especifica en que parte se corta el codigo.
Avisame si el problema es efectivamente ese, sino, comenta esta issue de nuevo.

Quedo atento.

**Comment by camirojasguajardo** [comment]
@Juampisaez También creía que el problema era ese, revisé la función codificar muchas veces, le arreglé detalles y me di cuenta que el programa se cae en el momento en que manda los bytes (en la linea del .sendall()) y no en la codificación del mensaje :(

**Comment by Juampisaez** [comment]
Hola perdon lo tarde, estuve revisando de nuevo tu codigo y revisando otras dudas me percate de que al eliminar los exception los codigos funcionaban bien. Puedes probar esta posible solución, y en caso que no resulte, te recomiendo ojala basarte en el ejemplo de los contenidos para hacer la conexion y el envio de mensaje.
Por mientras preguntare si algun ayudante logra encontrar el problema.
Avisame si funciona y quedo atento.

**Comment by camirojasguajardo** [comment]
@Juampisaez logré solucionar ese error, sinceramente, no sé cómo jaja ya que traté modificando varias cosas. Ahora me sale un error nuevo, pero abriré otra issue para eso :) Gracias!

**Comment by Juampisaez** [comment]
Oka, igualmente te adjunto lo que me dijeron que "en el lado del cliente, el thread escuchar servidor es Daemon, y además de eso, no hay nada en el código que mantenga al cliente andando. Entonces el cliente ya conecta el socket, echa a andar el thread, sigue su ejecución normal y como no hay nada (como un while True o una interfaz gráfica todavía) que lo mantenga arriba, termina su ejecución y se cierra, cerrando el daemon thread también. Entonces el server recibió la conexión, escoge el nombre y cuando lo va a mandar se encuentra con el socket del cliente cerrado ya que el script del cliente se acabó. Y ahí aparece ese error. Lo que tiene que debes hacer, es tener algo que mantenga el script del cliente andando de forma indefinida. "

Esto es lo que me contestaron y creo que se explica muy bien.

**Comment by camirojasguajardo** [comment]
ohh, comprendo, me aclaró mucho! muchas gracias por la respuesta!
