### ISSUE TITLE
Duda con direcciones IP de cliente y servidor

### ISSUE THREAD

**Issue by jturquiza** [IIC2233/syllabus#1101]
Hola! He estado revisando los ejemplos de la semana 14, y entiendo que cuando el código del cliente y del servidor se corren en el mismo computador, sirve usar gethostname() para ambos. Pero cuando recomendaban usar dos computadores distintos, en el host del servidor había que poner el IP del otro computador. Mi duda es si hay alguna manera de obtener el IP de otro computador en la misma red con algún método, o para la tarea asumimos que todo se correrá en el mismo computador (así solo uso gethostname()).
Muchas gracias de antemano!

**Comment by cruz** [comment]
Hola @jturquiza 

En general para conocer de manera automática la dirección IP de otro computador, tienes que tener una manera de referirse a él. Usualmente lo que uno hace es darle un nombre fácil de recordar, por ejemplo `youtube.com`, `www.ing.puc.cl`, `instagram.com`, etc, y se utiliza un servicio que te permita hacer la traducción de ese nombre "textual" a una dirección IP. Ese servicio se llama DNS y es parte de las configuraciones de red que otorga tu proveedor de Internet. No es común asignarle un nombre a computadores dentro de una misma subred domiciliaria, pero sí se puede simular un servicio DNS dentro de tu computador usando un archivo de texto de nombre `hosts` que se encuentra en alguna parte del computador (seguramente ese archivo ya existe). En ese archivo tu puedes asignar la relación entre una dirección IP y un nombre arbitrario que tú elijas. Por ejemplo, este es el archivo en mi computador (con algunas cosas cambiadas para ejemplificar):

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost 
192.168.1.86      peliculas
192.168.1.87      escritorio
129.168.1.88      laptop
```

Eso me permite, por ejemplo, usar el string `escritorio` en mi programa y lo asocia automáticamente a la IP 192.168.1.87.

Ahora bien, para efectos de la tarea, puedes suponer que el servidor estará en el mismo computador. Solamente si quieren hacerlo más flexible, una buena práctica es tener un parámetro que es sea `IP_SERVIDOR` en un archivo y así poder cambiarlo en cada ejecución, o bien recibirlo como argumento en la línea de comandos.

Espero haberte aclarado un poco. Puedes probar buscar en tu computador ese archivo `hosts`, inventar un nombre para el otro computador, y después usar ese nombre en tu programa.

**Comment by jturquiza** [comment]
Perfecto! Muchas gracias por la aclaración! Me quedó claro
