### ISSUE TITLE
Capturar errores de conexión en la estructura de servidor

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#1102]
Hola, según entendí del enunciado, si hay 3 jugadores en la sala de espera y a uno se le cae la conexión, debieran quedar dos cupos libres. Estoy basando mi estructura de _Networking_ según la ayudantía y mis preguntas son las siguientes:

* Si tengo un dict en mi servidor donde guardo los sockets de los clientes y se cae la conexión de un cliente, ¿el socket de ese cliente seguirá en el dict?
* ¿Dónde podría poner un try/except para capturar los errores dentro de mi clase servidor? (En la ayudantía y en los ejemplos de clases no ponen try/except en el servidor, solo en el cliente)

**Comment by vicentevegaulloa** [comment]
Hola @lewebe!

Respecto a tu primera pregunta, te recomiendo no dejar el socket en el diccionario, ya que nunca más lo usarás, por lo que esto sólo podría complicar tu código más adelante.

Respecto a tu segunda pregunta, podrías usar `try/except` en el método que tengas para escuchar el thread de un cliente, ya que si se pierde la conexión el error se originará ahí.

**Comment by lewebe** [comment]
Gracias por tu respuesta @vicentevegaulloa ! Pero no me está funcionando... tengo la función que es un _thread_ que escucha al cliente de esta manera:
```python
while True:
    try:
        #código para escuchar a un cliente
    except ConnectionError:
        print('Ha habido un problema de conexión')
```
Cuando conecto al servidor con un cliente y manualmente cierro la consola que representa al cliente, no se imprime este mensaje en la consola del servidor. Todo lo anterior está dentro del `listen_client_thread`

**Comment by vicentevegaulloa** [comment]
Creo haber encontrado la solución a tu problema. Con un código muy similar, puse el `while` completo dentro del `try` y en el `except` puse un `return`. Como es un thread que tiene como target el método `listen_client_thread`, este acabará sin arrojar errores ya que el `return` termina formalmente con el método en ejecución y por ende el thread asociado. 

Ojala te funcione 🤞. Si no funciona por favor haz `push` para verlo en detalle.

**Comment by Mendez69** [comment]
> Creo haber encontrado la solución a tu problema. Con un código muy similar, puse el `while` completo dentro del `try` y en el `except` puse un `return`. Como es un thread que tiene como target el método `listen_client_thread`, este acabará sin arrojar errores ya que el `return` termina formalmente con el método en ejecución y por ende el thread asociado.
> 
> Ojala te funcione 🤞. Si no funciona por favor haz `push` para verlo en detalle.

a mi me funcionó eso!

**Comment by vicentevegaulloa** [comment]
Hola @lewebe! Lograste solucionarlo?
