### ISSUE TITLE
duda como conectar con la interfaz grafica

### ISSUE THREAD

**Issue by feliperojas123** [IIC2233/syllabus#1102]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

holaaa buenas.. resulta que tengo una duda en como usar las interfaces graficas.
la pregunta en si... es que no se donde inicializar el tipico
app = QApplication([])
ventana = Sala_espera()
backend_nombre = Nombre()
backend_nombre.senal_nombre = ventana.senal_nombre
sys.exit(app.exec_())

ya que al ponerlo antes que el cliente no continua el avance de este
si lo pongo despues no me deja emitir
hasta el momento nose como resolver esto

**Comment by matiasmasjuan** [comment]
Hola @feliperojas123 !

Antes que todo, te recomiendo ver la ***issue*** #1091 ya que se habla de un tema similar y que puede responder a tu duda. Tal como dices, si creas la ventana antes, el cliente no se podrá ejecutar correctamente, y si lo pones después, podrías tener problemas con las señales. Existen varias formas de poder modelar esto. Una de ellas es que implementes la instancias de ventanas y las señales dentro del Cliente. De esta forma podrás ir controlando de mejor forma las señales que envías desde el front-end al back-end, y saber cuando es necesario abrir otras ventanas, etc. Recuerda que tienes disponible todo el material del curso, incluyendo los contenidos, ayudantías y actividades que pueden servirte de utilidad. :eyes: 

Saludos y mucho éxito con la tarea! :smile:

**Comment by feliperojas123** [comment]
holaaaaa buenaas. me sirvio muchooo pero ya me conectan las señales y todo pero no logro hacer que se muestre la sala de espera

**Comment by matiasmasjuan** [comment]
¿Podrías subirlo a tu repo? Tal ves pueda ver con mayor detalle lo que sucede.

Saludos!

**Comment by feliperojas123** [comment]
ooooh yaaaaa muchas graciaaas altiro lo subo

**Comment by feliperojas123** [comment]
ya lo subi por si las moscas en si todo lo que viene es del cliente en la funcion traducir_respuesta y en backend emite la señal y fronted es toda la interfaz grafica

**Comment by matiasmasjuan** [comment]
Viendo el archivo ```cliente.py```, me dí cuenta que **no** defines las ventanas y señales como atributos **propios** del cliente. Por lo tanto, de la línea ```114-120```, intenta definir las ventanas y señales como ```self.ventana = Sala_espera()```. Y lo mismo para las señales (añadir el ```self```). De esta forma las ventanas estarán asociadas directamente a un atributo del cliente y se te hará más facil hacer los ```emit()``` que deseas mandar entre el *back-end* y *front-end* desde cualquier método del cliente.

Avísame cómo te va! :smile:

**Comment by feliperojas123** [comment]
noooo aun me sigue tirando lo mismo... pero me sale como un cohete depython que deberia ser la pestaña que intento abrir pero no me sale nada

**Comment by matiasmasjuan** [comment]
Que extraño :thinking: . Yo le puse self a **todas** las líneas entre la 114 y 120 y me funciona perfectamente la ventana. Podrías hacer denuevo un push y decirme qué sistema operativo utilizas?

**Comment by feliperojas123** [comment]
pucha le cambie eso y me entra en la señal y todo me imprime en el fronted la lista cliente. pero no me tira la ventana... lo que sucedesi es que se abre un cohete de pyton pero no me deja ver lo que es... y estoy usando macos... tu crei que sea por eso

**Comment by matiasmasjuan** [comment]
¿Podrías volver a hacer push porfavor? A mi me funcióno sin problemas la ventana. Tal ves sea por tu sistema operativo... :thinking:

**Comment by feliperojas123** [comment]
holaaaaa nooo aun no me funciana.. lo acabo de pushear para que lo veas... mmm puede ser igual que sea eso.. es que nose porque me sale ese cohete de python que deberia ser una ventana pero no me abre. que puedo hacer :(
