### ISSUE TITLE
Locks en arquitectura cliente-servidor

### ISSUE THREAD

**Issue by sofiaemd** [IIC2233/syllabus#1103]
Hola! Estaba revisando la distribución de puntaje y noté que en arquitectura cliente-servidor bajo consistencia sale 'Se utilizan locks cuando es necesario'. No entiendo dónde se deben usar locks, como parte del código de networking?

**Comment by KnowYourselves** [comment]
Hola @sofiaemd!

No es que tengas que utilizar locks en la parte de networking de tu código, sino que ten en cuenta que en tu servidor tienes un thread escuchando a cada cliente, por lo cual es posible que esos threads empiecen a utilizar recursos compartidos y ese caso lo debes tratar correctamente.

Éxito!

**Comment by sofiaemd** [comment]
yap! Muchas gracias!! :)
