### ISSUE TITLE
Problemas con error de Qapp

### ISSUE THREAD

**Issue by mariofloresm** [IIC2233/syllabus#1104]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Me pasa que estoy intentando abrir una ventana desde un main y cuando corro el codigo en vez de abrirme una ventana con lo que yo quiero que se me abra, se me abre una ventana buggeada que no puede cargarse y se genera un pycache con archivos (que supongo que son las ventanas que intento abrir), esto es raro porque si corro directamente el codigo de la ventana que quiero abrir, esta si se abre de manera correcta, entonces no entiendo que puede estar pasando y mucho menos como arreglarlo ¿me pondrían orientar?]

Saludos

**Comment by Juampisaez** [comment]
Hola @mariofloresm 
No me queda claro la forma en que estas tratando de abrir tu ventana, lo estas haciendo con un .show()? la quieres abrir en una clase Cliente? Si puedes hacer git push a github para verlo mejor, seria mas facil verlo.

Quedo atento :)

**Comment by mariofloresm** [comment]
Lo que estoy intentando hacer es recibir un mensaje desde el server diciendo que la partida debe empezar y luego mandar una señal desde el cliente a otro codigo dentro del mismo archivo (la ventana del juego) pero intento que cuando se reciba la señal desde el cliente la señal haga un self.show() o llame a una metodo para verificar que la señal llegó y después hacer self.show() con lo que me di cuenta que la señal llega bien pero me sigue abriendo una ventana que no carga nada, y obviamente verifique que si corro el codigo de esa ventana por si solo si muestra lo que quiero.

hare el git push, muchas gracias

**Comment by Juampisaez** [comment]
Hola, de verdad perdon lo tarde (esta duro el fin de semestre), me tinca que tu problema viendo tu codigo, es que tratas de hacer el show(), dentro del cliente lo cual no es muy buena practica. Te recomiendo crear una señal que llegue a la ventana y te muestre su contenido. La interfaz es mejor manejarla con señales (como la T02).

Espero solucione el problema, quedo atento igual
