### ISSUE TITLE
Enviar cartas Formato

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1104]
Hola! Para esta parte nos piden formar un bytearray con todas indicaciones dadas, estaría permitido agregarle datos extras a este bytearray que nos piden formar , señalo que el formato sería el mismo solo que al principio irían más bytes

**Comment by szabala** [comment]
Hola! Para que quieres agregar mas _bytes_ al inicio del _array_ ?

**Comment by RonaldoSosa** [comment]
Lo que pasa es que normalmente para mis mensaje envio diccionarios con el formato json, y dependiendo del contenido del diccionario mi cliente realiza diversas acciones, quiero hacer esto mismo para las cartas de modo que al principio solo me lea este diccionario con el cual voy a "indicar" de que lo que viene son los bytes de una carta y leerlos de forma adecuada

**Comment by szabala** [comment]
Para hacer esto si esta permitido agregar _bytes_ extra al inicio del _bytearray_, buena idea!
Saludos!

**Comment by RonaldoSosa** [comment]
Entendido! Gracias!
