### ISSUE TITLE
Carta Inicial del Pozo

### ISSUE THREAD

**Issue by furcelay** [IIC2233/syllabus#1105]
Puedo filtrar la carta inicial del pozo de modo que sea una carta regular?
Sería muy injusto que parta con un +2 por ejemplo...

**Comment by vicentevegaulloa** [comment]
Hola @furcelay!

En el enunciado no se especifica, por lo que **puedes** decidir con que tipo de carta partir siempre y cuando utilices adecuadamente el `generador_de_mazos.py` y menciones esto en tu **README** .

**Comment by furcelay** [comment]
Ok, gracias!

**Comment by vicentevegaulloa** [comment]
De nada!

**Comment by mrperrox** [comment]
Siguiendo el hilo de esta duda, si decido la primera carta del pozo con un `random.choice()`, tanto el número como el color , sería válido?? o tengo que usar la función `sacar_cartas` hasta encontrar una carta que no sea especial?

**Comment by vicentevegaulloa** [comment]
Hola @mrperrox!

En este caso no es correcto hacerlo con el `random.choice()` ya que no estarías sacando la carta con el generador de mazos. Lo crrecto sería lo segundo, usar `sacar_cartas` hasta obtener una que no sea especial.
