### ISSUE TITLE
nombres de usuario repetidos

### ISSUE THREAD

**Issue by eliasbruchfeld** [IIC2233/syllabus#1105]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo un archivo.txt con un par de nombres de usuario, y un código que saca un nombre al azar para usarse durante el juego. Hay algún problema si a dos usuarios distintos les toca el mismo nombre? O debería hacer un código que detecte si el nombre ya está usado para elegir otro.

**Comment by matiasmasjuan** [comment]
Hola @eliasbruchfeld !

De acuerdo con el enunciado, deberás asignar un **nombre único** a cada cliente ingresado:

![asignar_nombre](https://user-images.githubusercontent.com/48495638/100411996-17391300-3052-11eb-8167-9f42d8bc7553.png)

Por lo tanto, **no es correcto** que a dos usuarios distintos les toque el mismo nombre. **Deben** tener **distintos** nombres. De todas formas, quiero hacer énfasis en que da exactamente igual cómo quieras agregar los nombres. Tal como dice el enunciado, puedes tener una lista ya predeterminada. Incluso puedes hacer que sus nombres sean '1', '2', '3'... etc.

Saludos! :smile:

**Comment by eliasbruchfeld** [comment]
Si, la cosa es que incluso leyendo el enunciado no me queda claro. Dice que hay que asignar de forma automática un nombre de usuario a cada cliente, no un nombre de usuario **distinto**. Yo podría asignarle de forma automática el mismo nombre a cada cliente, y si estaría cumpliendo con el mínimo que dice el enunciado. A eso básicamente apunta mi pregunta. 

O sea si me dices que no se puede yo te creo y lo hago jaja pero al menos con el enunciado no se da a entender explícitamente eso.

**Comment by matiasmasjuan** [comment]
Vuelvo a mencionar el enunciado, en la seccíon **Flujo del programa**:

![nombre_unico](https://user-images.githubusercontent.com/48495638/100473293-c3afdf00-30bc-11eb-9376-40d450cc399a.png)

Puede no ser tan **explícito** como dices, pero un nombre **único** hace referencia a que cada usuario debe tener un nombre **distinto**.

Espero que con esto haya quedado un poco mas claro :sweat_smile: 

Saludos! :smile:
