### ISSUE TITLE
Ventana no responde al tratar de aplicar señales para el envió de mensajes

### ISSUE THREAD

**Issue by josefapv** [IIC2233/syllabus#1106]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, estoy modelando la tarea basándome en la AF05 y me surgió un problema. Cuando corro el programa, tal como esta en mi repo, funciona y se abre correctamente la ventana de sala de espera, sin embargo, cuando trato de probar el envió de mensajes, lo cual lo hago usando señales tal cual se hizo en la actividad, al correr el cliente se abre una ventana en blanco y me sale que el programa no responde. Lo que hago para implementar las señales esta comentado en el código, en interfaz.py y sala_de_espera.py. Si me pudieran ayudar a identificar que es lo que esta causando esto seria de gran ayuda, ya que llevo desde ayer tratando de solucionarlo y no puedo.

**Comment by lucasprato** [comment]
Hola @josefapv,

Analicé tu código y vi que estás un poco enredada con el uso de señales. No estabas ocupando señales para comunicar al backend con el frontend, los estabas comunicando de forma directa en la clase `Controlador`. Te describo cómo tendría que ser para que se uses señales:

1. En la clase `Controlador` debes instanciar las señales que quieras usar (arriba del `init`)
2. En el init debes conectar a la señal con el método `mostrar_sala_espera`
3. En la clase `Controlador` debes crear un nuevo método que se encargue de emitir la señal
4. Este nuevo método va a ser el que se comunicará con el backend.

Así, el flujo sería que en `cliente.py` se llama a este nuevo método del controlador. Este nuevo método emitirá la señal, la cual está conectada al método que hace el show de la ventana. Lo probé y funciona.

Éxito en la tarea!!

PS: Cambia el `HOST = "192.168.1.96" `por `HOST = "localhost"`, esto permitirá que tu programa pueda iniciarse en cualquier computador (hazlo tanto para el servidor como para el cliente).

**Comment by josefapv** [comment]
Ok, gracias te pasaste!

**Comment by guillejponce** [comment]
Hola! Yo estoy teniendo el mismo problema, seguí la estructura que mencionan arriba en la issue pero las ventanas siguen quedando en blanco y sin responder. Subí a mi repositorio mi avance por si podían ayudarme (debo estar conectando mal alguna señal o trabajando mal en algun archivo).
