### ISSUE TITLE
Server sigue aceptando clientes

### ISSUE THREAD

**Issue by srodriguezp** [IIC2233/syllabus#1107]
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola,
Tengo una duda con respecto al método listen() de socket ya que le entrego como argumento la cantidad máxima de clientes que quiero que acepte pero el server sigue aceptando clientes aunque se supere este numero. ¿Cómo lo puedo solucionar?

**Comment by lucasprato** [comment]
Hola @srodriguezp, puede porfa pushear tu código para poder verlo?

**Comment by lucasprato** [comment]
@srodriguezp, la  [documentación del método listen de sockets](https://docs.python.org/3/library/socket.html) habla sobre dicho argumento como `backlog`. Se dice de él lo siguiente:
> Enable a server to accept connections. If backlog is specified, it must be at least 0 (if it is lower, it is set to 0); it specifies the number of unaccepted connections that the system will allow before refusing new connections. If not specified, a default reasonable value is chosen.

Como puedes apreciar, este parámetro no es que limite la cantidad máxima de conexiones, sino que establece otro tipo de lógica relacionada con el rechazo de conexiones. 

Para limitar la cantidad de conexiones, te recomiendo implementar un contador externo que dependiendo de su valor no permita conectar a nuevos clientes.

Éxito en la tarea!!!

(gracias a @gatochico por su advise 😉)
