### ISSUE TITLE
Duda Inicio del Juego

### ISSUE THREAD

**Issue by DmBeta101** [IIC2233/syllabus#1107]
Hola tengo una duda,

Al momento de iniciar el juego con un usuario, puedo hacer que la ventana de inicio no se conecte al servidor, sino que al momento de apretar "Entrar" intente conectarse al servidor?

**Comment by DCCollao** [comment]
Hola!

Mientras no vaya en contra de lo que se dice en el enunciado (máximo de jugadores en la sala, nombre no repetido, nombre válido), no hay problema en hacerlo como planteas.
