### ISSUE TITLE
Rechazar conexiones desde servidor

### ISSUE THREAD

**Issue by Zenos-Paradox** [IIC2233/syllabus#1108]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Cómo e pueden rechazar conexiones desde un servidor? pensé que si no llamabas socket_cliente.accept() automáticamente se rechazaba la coexión causando un ConnectionRefusedError en el cliente, pero parece que este no es el caso.

**Comment by aaossa** [comment]
Hola @Zenos-Paradox, si no haces `accept`, el cliente debería quedar "en cola" por lo que está ocupando espacio en el valor que le das a `listen`. Creo que debería bastar con aceptarlo y luego ocupar su método `close`. Prueba eso y me dices si  te funciona 👌 ¡Éxito con la tarea ✨!

**Comment by Zenos-Paradox** [comment]
Con eso me funcionó. Gracias :)
