### ISSUE TITLE
Cliente no recive mensajes enviados

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#1108]
Al llegar a los 4 clientes mi programa deberia enviar, y por lo que entiendo, envia, un mensaje el cual debe recibir cada cliente. (en esta etapa de prueba, debe imprimir el mensaje que recibe) pero no recibe, o por lo menos, no imprime, nada. A que se debe?

**Comment by gatochico** [comment]
Hola! (lamento la demora, espero todavía sea util)

Revisé tu código y lo que ocurre es un problema en el ciclo `while` que utilizas para recibir el mensaje completo (donde entras al ciclo mientras que `while len(response) < response_length` ). Si imprimes justo antes de ese ciclo el valor de `response_length`, verás que es un valor muuy alto y por ende, tu código llega hasta ese ciclo y luego no sale más de ahí porque nunca se rompe la condición del while (compruebalo haciendo prints del bytearray dentro del while, si se imprimen).

Para solucionarlo, debes ir al método `send` del server y revisar que estés mandando el tamaño correcto. (Veo que estás haciendo send del mensaje de inmediato sin mandar el largo de este primero, por lo que nunca le adjuntas primero el largo del mensaje y el cliente nunca recibirá el largo del mensaje necesario para manejar el ciclo).

Como recomendación, imprime todo lo que estés creando en el método send del server y el receive del cliente, para que veas paso a paso como va funcionando tus métodos y puedas encontrar el punto donde está el error más facil.

Saludos!
