### ISSUE TITLE
Contenido Mapa al comenzar partida

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2233/syllabus#1109]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda sobre con que cosas tiene que abrirse el mapa de juego al comenzar la partida, entiendo que la parte 4.2.1 del enunciado de preparar el mapa tiene que hacerse antes de comenzar la partida. Sin embargo no me queda claro si el punto 4..2.2 de comenzar partida se debe hacer antes o después de mostrar el mapa ( es decir repartir los turnos , ubicar la chozas iniciales y las carreteras. Para mi lo mas natural es hacerlo antes de mostrar el mapa, pero como esta en el item de comenzar partida me confunde. 

Gracias:)

**Comment by EduardoIllanes** [comment]
>  es decir repartir los turnos , ubicar la chozas iniciales y las carreteras. Para mi lo mas natural es hacerlo antes de mostrar el mapa

Hola @antoniaalcayaga ! Lo que mencionas es correcto, éxito en tu tarea 😄
