### ISSUE TITLE
Usar dict como property

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#1109]
Hola! Resulta que en mi clase `Servidor` tengo un atributo `self.jugadores` que guarda a los clientes que eligieron un username correcto y lograron entrar a la sala de espera en un `dict()`. Ahora bien, me gustaría definirlo como _property_ para en el _setter_ poder poner que si el dict alcanza cierto número, la sala se considere como llena mediante un _boolean_, o si se cae la conexión de algún jugador, ese _boolean_ vuelva a ser _False_ y queden cupos para poder seguir llegando a la sala de espera. Mi problema es que no se cómo funciona el _setter_ de una _property_ que es un dict. Quiero hacer algo como
```python
class Servidor:
    def __init__(self):
        self._jugadores = dict()
        self.sala_espera_llena = False
    @property
    def jugadores(self):
        return self._jugadores
    @jugadores.setter
    def jugadores(self, value):
        #Aquí lo que quiero hacer es que funcione como un dict normal, de manera que si yo ingreso una nueva key
        #con un value, o bien desaparezca una key con su value (porque se cayó la conexión y por tanto, se cerró el socket)
        #el diccionario se actualice correctamente y luego chequee el estado de la sala de una forma como
        self.jugadores = value
        if self.jugadores.keys() == 4:
            self.sala_espera_llena = True
        else:
            self.sala_espera_llena = False
```
Lo que no entiendo es el `value` del setter, cómo se comporta y cómo hacer a través de _properties_ que simplemente actúe de manera normal y me chequee la cantidad de elementos que tiene cada vez que se extiende (de la forma`self.jugadores[nueva_key] = nuevo_value`) o se acorta este dict. (Obviamente en el código la clase `Servidor` está simplificada a mi problema). Muchas gracias!

**Comment by KnowYourselves** [comment]
Hola @lewebe!

Excelente idea!, Pero lamentablemente, no es algo que puedas hacer facilmente con properties. Esto se debe a que cuando haces `self.jugadores[llave] = valor` no estás modificando el atributo `jugadores`, sino un atributo interno de este, por lo cual el **setter no se va a activar**.

Debido a que no hay ninguna forma directa de conseguir este comportamiento, te recomendaría buscar otra forma de realizar lo que quieres hacer. En caso de que quieras intentarlo de todas formas. Deberías hacer tu propia clase diccionario, que herede de `dict` y redefinir su `__setitem__`. En [este link](https://stackoverflow.com/questions/3137685/using-property-decorator-on-dicts) puedes ver un ejemplo.

Éxito!

**Comment by lewebe** [comment]
Perfecto, muchas gracias king! 👑
