### ISSUE TITLE
Duda velocidad recursos

### ISSUE THREAD

**Issue by cilopez** [IIC2233/Syllabus#111]
En la tarea se especifica claramente que la velocidad de los recursos esta entregada en metros por segundos, lo que pasa es que estos datos me extrañan ya que según esto un bombero iría a 226 km/h y un avión  a 1270 km/h (según datos de la base). Entonces tomo la velocidad según lo que me hace sentido o según lo enunciado.

**Comment by Hernan4444** [comment]
@cilopez toma la velocidad según enunciado.

Saludos!
