### ISSUE TITLE
Relación Entrenador - Programon

### ISSUE THREAD

**Issue by isajofre** [IIC2233/Syllabus#111]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Quería consultar sobre la relación de entrenador con programon. No me queda claro si esta sería de agregación o de composición ya que considerando que todo toma lugar dentro de la Liga, los entrenadores son quienes poseen programones, sin embargo al revisar el diagrama de clases de la AS1 buscando una referencia me di cuenta que en un caso similar usan solo agregación (Atracción con Animal). Gracias!

**Comment by Emiliax16** [comment]
Hola @isajofre ! no puedo decirte directamente el tipo de relación entre esas entidades, pues debes reconocerlo para hacer tu diagrama y tu modelación. Tienes que pensar dentro del contexto de la tarea lo siguiente:
- ¿tiene sentido la existencia de los programones sin la entidad Entrenador?

Si  ves el ejemplo de mario bros de los contenidos de la semana 3 ([https://github.com/IIC2233/contenidos/blob/master/semana-03/1-diagrama-de-clases.ipynb](url) te debería quedar mucho más claro. Recuerda que debes pensar **en el contexto de la tarea**. De todas maneras recuerda justificar el diagrama! saludos c:
