### ISSUE TITLE
Errores bases de datos

### ISSUE THREAD

**Issue by MINGOD24** [IIC2233/syllabus#111]
Hola, estaba revisando mi tarea y me di cuenta que habian cosas que no me funcionaban. Al buscar el porque me di cuenta que habian usuarios que estaban distintos en los post y en los seguidores, un ejemplo es lily416 donde, en usuarios y posts aparece de tal manera, pero en seguidores aparece como lilyuwu416. Esto no me permite modificar los archivos correctamente, y creo que no es el unico caso. ¿Que hago?

**Comment by DCCollao** [comment]
Hola @MINGOD24 !

Acabo de revisar los archivos que mencionas y me aparece, tanto en [usuarios](https://github.com/IIC2233/syllabus/blob/master/Tareas/T00/usuarios.csv) como en [posts](https://github.com/IIC2233/syllabus/blob/master/Tareas/T00/posts.csv), "lilyuwu416". 

Asegúrate de que tengas los archivos actualizados a la última versión!
De todas formas, cualquier error que encuentres por favor avísanos por este medio,

Éxito
