### ISSUE TITLE
Duda Menú de inicio - Crear Predios ["Fallo en la carga"]

### ISSUE THREAD

**Issue by el-Jay-C** [IIC2233/Syllabus#111]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Tengo una duda cuando marcamos la opción 1 del menú de inicio y el método crear_predios nos retorna "Fallo en la carga de DCCultivo". Esto implica que no tenemos predios guardados, por lo que no podemos realizar ninguna acción de las disponibles en el menú de acciones (sin que nos dé error). En este caso ¿Debemos directamente salir del programa o está a nuestra disposición lo que hagamos y debemos mencionarlo en el README?

Gracias de antemano

**Comment by FernandoTFH** [comment]
Si efectivamente, está a tu disposición el ver que pasa en ese caso, pero por supuesto no debe "caerse", es decir tu debe programar la lógica de lo que pasa después. Y Si menciónalo en el README, para que el ayudante que te vaya a corregir, sepa que  lo que ocurre en esos casos, fue lo que tu decidiste que pasara.
