### ISSUE TITLE
Calculo de ataque y vida

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#111]
Para que el programa sea mas eficiente al calcular ataque y vida es necesario por ejemplo si son 50 soldados, que cada uno de ellos tenga un ataque y vida diferentes y luego sumarlos o puedo simplemente generar un soldado y multiplicarlo por el numero de estos

**Comment by ptflores1** [comment]
Hola !
Si es necesario que sean soldados diferentes, con su propia vida y ataque. Recuerda que **NO** es necesario guardar la vida y ataque de cada soldado, solo la cantidad existente.
Saludos !
