### ISSUE TITLE
error: bad signature 0x00000000 fatal: index file corrupt

### ISSUE THREAD

**Issue by miguelsaavedra27** [IIC2233/syllabus#111]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Intenté hacer un git push pero me aparece este error. ¿Qué puedo hacer?

**Comment by tqmbanados** [comment]
Hola! Como dice el error, es producto de que hay una falla en el archivo ```index``` de git. Esto también puede suceder si en las "subcarpetas" de tu carpeta git remota (la de tu computador) también hay carpetas ```.git```. Esto puede suceder si clonaste un repositorio dentro de otro repositorio por ejemplo. Te recomiendo poner en tu computador que las carpetas escondidas sean visibles, y luego revisar si en alguna subcarpeta tienes otra carpeta ```.git```. Si es el caso, avisa antes de hacer nada para solucionarlo de la mejor manera.
Si no, tendrás que borrar el archivo ```index```  dentro de la carpeta ```.git``` y luego resetear git. Puedes borrar ```index``` manualmente, o usar el comando ```del .git/index``` (en windows) y luego escribir el comando ```git reset```.

**Comment by tqmbanados** [comment]
Hola! no cierres las issues, pueden servirle a otra persona. Si se te arregló el problema, deja un comentario y nos haremos cargo :)
