### ISSUE TITLE
Sugerencia para proximos enunciados de tareas

### ISSUE THREAD

**Issue by xDanman** [IIC2233/syllabus#111]
Hola! solo hago esta issue para saber si es posible que las próximas fotos de código que coloquen en enunciados sean con un tema blanco(fondo blanco) en vez de negro, para así no gastar tinta demás para las personas que imprimen los enunciados.

Eso gracias!

**Comment by difischer** [comment]
Creo que esto debería tener más likes.

**Comment by gatochico** [comment]
Hola @xDanman !

Muy buena sugerencia 🌟 Será algo que tendremos en cuenta para los siguientes enunciados de tareas.

Saludos!
