### ISSUE TITLE
Menú de elecciones

### ISSUE THREAD

**Issue by Witomi** [IIC2233/syllabus#111]
Cuando hago el menú con las opciones de crear persona, atacar, construir, etc; puedo no mostrar las elecciones si no se pueden realizar(por falta de personas,recursos,etc) en vez de mostrarlas y printear que no se puede??

Gracias!

**Comment by DCCollao** [comment]
Hola!  Cualquiera de las dos formas debería servir, pero si no las mostrarás en caso de que no sean posibles sería bueno que lo explicaras en tu readme.
Saludos!
