### ISSUE TITLE
Edición adecuada de README.md

### ISSUE THREAD

**Issue by isidoragutierrez** [IIC2233/Syllabus#111]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!
Para editar el archivo README.md utilizando Markdown ¿se debe hacer directamente en GitHub y luego hacer git pull o se debe editar en algún editor desde mi computador y luego hacer git push?

Muchas gracias de antemano!

**Comment by mtaguero** [comment]
¡Hola @isidoragutierrez!

Puedes editarlo como a ti se te haga más comodo, ya sea local y luego subiéndolo con los demás archivos de tu tarea o directamente desde el repositorio. Sin embargo, para no confundirte con tus propios avances, te recomiendo editarlo de forma local, así cuando subas tus archivos, también actualizarás el README sin problemas.

Avísame si quedó claro o tienes otra duda.

¡Éxito! 🎈

**Comment by isidoragutierrez** [comment]
@mtaguero muchas gracias!! Me quedó clarísimo!
