### ISSUE TITLE
Creación .gitignore

### ISSUE THREAD

**Issue by vicenterodas** [IIC2233/Syllabus#111]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, tengo una duda sobre el gitignore. Luego de leer el enunciado y los links respectivos entiendo la función que tiene el gitignore. Pero en ninguna de las lecturas me queda claro qué debo hacer yo para que este funcione de manera correcta. No entiendo si debo crear un archivo llamado gitignore.py o que debo hacer. Gracias.

**Comment by Maratripa** [comment]
Hola! Para utilizar el gitignore debes crear un archivo llamado `.gitignore` (tiene un punto al principio y no tiene extensión). Te recomiendo crearlo por visual studio code agregando un archivo o con el siguiente comando
```sh
$ touch
```
 Debes crearlo dentro del directorio `T0` de tu repositorio personal.

Cuando esté creado y adentro tenga los archivos a ser ignorados, git los ignorará automáticamente, es decir, al correr el comando 
```sh
$ git status
```
No deberían aparecer los archivos o directorios listados en `.gitignore`.

Cuéntame si te queda alguna duda :)
