### ISSUE TITLE
Problema con los test de cambiar_plano

### ISSUE THREAD

**Issue by JSalas277** [IIC2233/Syllabus#111]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Estoy teniendo problemas con cambiar_plano, pues en los casos que me da False me funciona pero cuando lo intento para los otros casos tengo que me dan los resultados cuando reemplazo self.estaciones y self.red pero aun asi me da FAIL:

test_0 (tests_publicos.test_09_cambiar_planos.TestCambiarPlanos.test_0)

        Verificar lectura y modificación del nuevo plano.
         ... ['Moneda', 'Camino Agricola', 'Cerrillos', 'Mirador', 'Quinta Normal', 'San Joaquin']
[['0', '1', '1', '0', '0', '0'], ['0', '0', '1', '0', '1', '0'], ['0', '1', '0', '1', '0', '0'], ['0', '1', '1', '0', '1', '0'], ['0', '1', '1', '0', '0', '1'], ['0', '0', '1', '0', '1', '0']]
FAIL
test_1 (tests_publicos.test_09_cambiar_planos.TestCambiarPlanos.test_1)

        Verifica que no actualice cuando no existe archivo.
         ... ok
test_2 (tests_publicos.test_09_cambiar_planos.TestCambiarPlanos.test_2)

        Verificar lectura y modificación del nuevo plano.
         ... ['Camino Agricola', 'Lo Contador', 'Baquedano']
[['0', '1', '1'], ['0', '1', '0'], ['0', '0', '1']]
FAIL

**Comment by FelipeEscobarA** [comment]
["0", "1", "1"] != [0, 1, 1]
