### ISSUE TITLE
Problema con la función randint()

### ISSUE THREAD

**Issue by SVenegasA** [IIC2233/Syllabus#111]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Saludos,
Dentro de mi código, para decidir si un jugador ganó en un determinado juego o no, estoy usando la función randint y viendo si el valor que retorna es menor que prob_juego. Pero el problema es que randint solo me está retornando los valores 1 y 0 ¿Qué puedo hacer para solucionarlo? Ya me fijé que no fuera un error mío y efectivamente debiera retornarme un número del tipo float entre 0 y 1

**Comment by antoniablanco** [comment]
Hola, para ayudarte más, podrías subir como definiste el randint. En tu codigo.

**Comment by SVenegasA** [comment]
suceso = randint(0, 1)

**Comment by SVenegasA** [comment]
(Estoy importando la función desde el módulo random)
