### ISSUE TITLE
duda con método listen()

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#1110]
Hola, en mi clase servidor se supone que debiera existir el método listen() para definir cuántos clientes permite conectarse al servidor. Para esta tarea estoy probando algo como ```sock_servidor.listen(2)``` , pero al conectarme con distintas consolas acepta a más de dos clientes y no entiendo por qué...
Debería aceptar a dos clientes? o, el método no funciona así?

**Comment by igbasly** [comment]
Hola @Camila-sty :v:
Primero que todo, hay que diferenciar entre la clase `Servidor` que estés utilizando para modelar como el servidor maneja las distintas conexiones y el manejo de los datos. Y el `socket_servidor` que correspondería a una instancia de la clase `socket` la cual es finalmente como la “conexión en sí”, es decir, la representación del servidor en la red.
Con esto, podemos diferenciar los métodos `listen`, donde tendrás dos principales enfoques:
* En la clase `Servidor`, usualmente se modela un método `listen` o `escuchar_cliente` para que maneje los datos que se reciben por parte de **un cliente** en específico y se llame a las acciones necesarios por parte del servidor.
* Y en el `socket_servidor`, como instancia de `socket` posee un método `listen` que recibe un entero como mencionas, el cual indica algo así como el largo de la cola de espera de conexiones. Para entenderlo bien, el servidor está disponible para aceptar conexiones, cuando un cliente intenta hacer `.connect` con un servidor, se pasa a una especie de cola para ser aceptado. Una vez que el servidor haga `.accept` este cliente es autorizado para establecer la conexión, por lo tanto, `socket_servidor.listen` establece el largo de esta cola, y si tu hicieras `socket_servidor.listen(2)` significa que pueden haber máximo dos clientes esperando sin ser aceptados, si llegase un tercero será rechazando con un error de conexión hasta que el servidor haga `.accept` y libere un espacio.

Entonces, este último método no va a evitar que más de dos clientes se conecten simultáneamente al servidor, eso debes manejarlo internamente y verificarlo al momento de aceptar conexiones nuevas.

Espero haberte ayudado y lo siento por la demora en responder. Por favor hazme saber cualquier commentator al respecto, saludos 🙌.

**Comment by Camila-sty** [comment]
Se entendió perfecto, gracias!
