### ISSUE TITLE
Guardar información de grafo.json

### ISSUE THREAD

**Issue by fran-gl** [IIC2233/syllabus#1110]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda acerca de la forma de guardar la información del archivo ```grafo.json``` en el servidor. Está permitido hacer clases como por ejemplo ```Nodo``` o ```Grafo``` para guardar la información del grafo en el servidor? O solo puede estar guardada en algo como lista o un diccionario? Muchas gracias de antemano.

**Comment by DCCollao** [comment]
Hola @fran-gl!

Para guardar la información contenida en `grafo.json` puedes usar la estructura de datos que te resulte más cómoda, por lo que sería correcto crear clases `Nodo` y `Grafo` para almacenar la información. Lo único que no está permitido es programarlo de alguna forma que contradiga en algún punto al enunciado o distribución de puntajes.

**Comment by fran-gl** [comment]
> Hola @fran-gl!
> 
> Para guardar la información contenida en `grafo.json` puedes usar la estructura de datos que te resulte más cómoda, por lo que sería correcto crear clases `Nodo` y `Grafo` para almacenar la información. Lo único que no está permitido es programarlo de alguna forma que contradiga en algún punto al enunciado o distribución de puntajes.

Ok perfecto, muchas gracias!
