### ISSUE TITLE
Forma de mostrar los logs en la terminal

### ISSUE THREAD

**Issue by IgnaciaJ** [IIC2233/syllabus#1111]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
He estado buscando por hartas librerias como puedo agregar líneas a tablas ya creadas, de tal manera que se agregue una fila cada vez que un cliente interactúe con el programa, sin embargo, no he encontrado ninguna manera que se agregue sin desconfigurar el formato, alguna recomendación para agregar filas a las tablas? o librería más recomendada?(estoy usando tabulate)

**Comment by lucasprato** [comment]
Hola @IgnaciaJ,

Te recomiendo usar la librería [beautifultable](https://beautifultable.readthedocs.io/en/latest/source/beautifultable.html). Lo que hace es crear una tabla y uno le puede ir agregando filas. Su comando `columns.width` permite asignar un máximo de caracteres por columna, por lo que si una celda supera los caracteres establecidos para su columna, se hacen quiebres de línea. Además con `rows[i]` puedes obtener una fila con índice i para poder imprimir el log. En la documentación puedes encontrar otras cosas útiles que te podrían servir.

**Comment by IgnaciaJ** [comment]
gracias!!

**Comment by denisseleiva** [comment]
Holaaaa @lucasprato me vengo a colgar de esta issue 😅
Sabes de qué forma se puede imprimir sólo la última fila de la tabla? Intenté con print(self.table[-1]) y me sale cualquier cosa, creo que subieron una nueva versión de la librería y no he encontrado la forma de imprimir sólo la última fila uwu

**Comment by alterdieg0** [comment]
hola @denisseleiva yo ocupe el metodo **table.stream** de BeautifulTable en un thread para imprimir todos los logs que vayan llegando desde otro thread de una función generadora que recibe y pasa esos logs (con un yield), es un poco complicado pero queda de pana banana

**Comment by denisseleiva** [comment]
@alterdieg0 gracias por el tip jajajaja igual me terminé cambiando a prettytable, funcionó perfect
