### ISSUE TITLE
Deserializacion cartas y creacion de archivos .png en carpeta clientes

### ISSUE THREAD

**Issue by anamarn** [IIC2233/syllabus#1111]
Hola !
Tenia una duda con el tema de deserializar cartas. Tengo entendido que los clientes no tienen acceso a la carpeta sprites y por lo tanto se envian los bytes serializados de la imagen. Al deserializar en mi cliente, puedo escribir un nuevo archivo .png donde guardar la imagen  para después cargarlo en la interfaz? O existe una manera en donde no es necesario escribir archivos para cargar las imagenes en la interfaz (bytes a png sin pasar por write)?
Gracias c:

**Comment by szabala** [comment]
Hola!
En la issue #1039 se responde parcialmente tu duda.  Complementando esto, no hay necesidad de escribir la imagen en un archivo cuando el cliente la reciba, esto ya que QPixmap no solo carga imagenes desde .PNG sino que tambien [puede cargar _bytes_](https://doc.qt.io/qtforpython/PySide2/QtGui/QPixmap.html#id6). Alternativamente, puedes serializar un QPixmap desde el servidor y enviar eso al cliente.

Espero haberte ayudado 😄
