### ISSUE TITLE
Ganar sin gritar ¡DCCuatro!

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#1112]
Cuando un jugador se queda sin cartas, y nadie gritó ¡DCCuatro! en el momento que tenía solo una carta, igual gana?

**Comment by szabala** [comment]
Hola! En efecto en ese caso el jugador que se queda sin cartas **gana**.  Gritar ¡DCCuatro! **no** es una condición para ganar.
Espero haber aclarado tu duda, suerte con la tarea 😄
