### ISSUE TITLE
Interfaz sala de espera y sala de juego

### ISSUE THREAD

**Issue by sebaelsaca** [IIC2233/syllabus#1113]
Hola! No me queda claro si esta sala de espera y sala de juego va en el servidor o va en el front end del cliente?

**Comment by gatochico** [comment]
Hola! 

El servidor, al ser un ente que solo se encarga de manejar lógica y distribuirla entre clientes, no debería tener interfaz gráfica asociada. Al contrario, los clientes son quienes juegan DCCuatro y por ende ellos son los que necesitan la interfaz para interactuar. Por lo tanto, las ventanas son responsabilidad del **cliente**.

Éxito! 🎴
