### ISSUE TITLE
Regla construccion chozas y carreteras

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2233/syllabus#1113]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo una duda muy puntual porque he jugado catán antes (no sé si con las reglas correctas 😃 ), entonces ocurre que al menos tengo entendido que si construyo dos carreteras seguidas unidas por un nodo vacío, o sea, no hay choza del jugador pero continua la carretera, no puede otro jugador construir en ese vértice, que en teoría quedaría bloqueado, porque sino sería muy fácil cortar las carreteras más largas ¿puedo asumir o se tiene que hacer respetar esto?

Gracias de antemano!

**Comment by rodrigobj99** [comment]
Hola @Jamesmoreno21 !
El enunciado de **DCColonos** establece que el único requisito para construir una choza es que en no hayan chozas en los nodos adyacentes al nodo donde se quiere construir la nueva choza, es decir que hayan al menos dos caminos de distancia entre cada choza. 
Por lo tanto es posible construir una choza y cortar una carretera rival (siempre y cuando se cumplan las restricciones de construcción), quitándole 2 puntos en caso de que fuese la carretera mas larga.

Espero te sirva!
