### ISSUE TITLE
Versión de PyQt5

### ISSUE THREAD

**Issue by benjavicente** [IIC2233/syllabus#1114]
Hola!
Para mi programa se necesita tener la versión 5.14 de PyQt5, que salió a inicios de este año.
Si se usa una versión anterior ocurre un pequeño error, que podría solucionar al eliminar una función del programa.

¿Puedo usar esta versión?
¿Cómo indico al corrector que necesita sobre o esta versión?

He leído que se usa un archivo `requirements.txt`, y pienso mencionar esto en el README.

**Comment by gatochico** [comment]
Hola! No hay problema con que uses esta versión para tu programa (además, genial que te hayas dado cuenta que la funcionalidad que deseas aplica a partir de cierta versión 🙈). Lo que recomendaría es que menciones **bien claro y explícito** en tu README (idealmente sea lo primero que salga) que tu programa necesita esta versión y qué funcionalidades la requieren. De esta forma, el corrector sabrá que debe hacer _upgrade_ de pyqt5 antes de correr tu tarea. 

Éxito!
