### ISSUE TITLE
Error con recv

### ISSUE THREAD

**Issue by nlewin99** [IIC2233/syllabus#1115]
Cuando un cliente se conecta, se me cae el programa porque supuesta mente mi socket_cliente es una tupla que no tiene el atributo recv por lo que no me deja recibir info del server.
msg = socket_cliente.recv(2**16)
AttributeError: 'tuple' object has no attribute 'recv'

**Comment by igbasly** [comment]
Hola @nlewin99 :v:
Puede ocurrir que hayas asignado mal los objetos recibidos con `.accept`. Recuerda que este método del *socket* del servidor entrega una tupla con la instancia del *socket* que permite la comunicación con el cliente y otra tupla con la dirección a la cual se conectó el cliente. Esto se vería como ` socket_servidor.accept() => (socket_cliente, direccion)`.

Avísame si esto te ayuda con el error, de lo contrario, te pido un poco más de contexto respecto a lo que estás implementando 🙌

**Comment by nlewin99** [comment]
perfecto, muchas gracias!, otra cosa relacionada con lo que me explicaste recién, esa dirección es distinta para cada cliente que se conecta?

**Comment by igbasly** [comment]
En parte si, esta dirección es una tupla en el formato `(host, client_port)`, donde `host` corresponde a la dirección ip a la cual se conectó el cliente, es decir, lo que se configuró en su lado como *host*. Y `client_port` es un entero único para cada cliente que indica el puerto que está ocupando el servidor para comunicarse con ese usuario en específico.

**Comment by nlewin99** [comment]
Bacán, muchas gracias!
