### ISSUE TITLE
Mis clientes no reciben los mensajes del servidor

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#1115]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, he implementado las funciones para recibir y enviar mensajes entre cliente-servidor y normalmente todo funciona bien. Sin embargo, **cuando el servidor manda 2 mensajes seguidos, mis clientes solo reciben el primero y no el segundo :c**. Si entre estos dos mensajes hago un ```time.sleep(0.1)```, los 2 mensajes se reciben correctamente. No sé si esto es un error en mi código o es otra cosa relacionada a cómo funciona el envío de mensajes.

**Comment by Juampisaez** [comment]
Hola @En-clases 
Me da la impresión de que te falta hacer un sendall, ya que quieres enviar dos mensajes distintos, también puede ser que recibe ambos mensajes en uno. Si puedes hacer git push, seria mas facil ayudarte!

Quedo atento :)

**Comment by En-clases** [comment]
Gracias por la ayuda! Sin embargo para ambos mensajes hago sendall y tambien hice print sobre los mensajes que envío y recibo y no parece ser que se hayan enviado en un solo mensaje :c. Acabo de hacer git push en mi repositorio.

**Comment by Juampisaez** [comment]
Hola de nuevo, perdon lo tarde, talvez lo que te pueda ayudar son dos cosas, la primera es hacer solo un metodo que se encargue de enviar la informacion a los clientes (juntar los metodos enviar y enviar_a_todos, conservando el for que haces en este ultimo), y además que ocupes el decorador @staticmethod antes de definir este metodo:
![image](https://user-images.githubusercontent.com/48323752/100528818-9ef06000-31bf-11eb-917e-0490371ac451.png)
Tal vez enviando toda la información dentro de un solo metodo, no sea necesario hacer el time.sleep().

Espero que esto solucione el problema, nuevamente perdon lo tarde.

**Comment by En-clases** [comment]
Acabo de juntar las dos funciones y también implementé el decorador @staticmethod pero el problema sigue ahí :c. Si elimino el ```time.sleep``` los mensajes no llegan. Sin embargo, para solucionarlo solo debo poner el ```time.sleep(0.1)``` al principio de la función ```enviar``` lo que no es muy molesto. Para la tarea puedo dejar eso así?

**Comment by Juampisaez** [comment]
Yaa, logramos solucionarlo. Lo que debes hacer en primer lugar es borrar el time.sleep(). 
Luego intentar lo siguiente en el cliente:
```
if chunk + 1 < cantidad_chunks:
    bytes_leer = 60
    datos_recibidos = self.socket_cliente.recv(bytes_leer)
else:
    bytes_leer = largo_mensaje - len(mensaje)
    padding = 60 - bytes_leer
    datos_recibidos = self.socket_cliente.recv(bytes_leer)
    padding = self.socket_cliente.recv(padding)
mensaje.extend(datos_recibidos)
```

Quedo atento cualquier cosa.
