### ISSUE TITLE
problema con json.loads al recibir mensaje en el cliente

### ISSUE THREAD

**Issue by camirojasguajardo** [IIC2233/syllabus#1116]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! al aplicarle json.loads al mensaje en formato bytearray, se genera una excepción. Leí en otra issue que servía hacer mensaje.rstrip(b'\x00') y luego mensaje.decode() antes del .loads() pero no me funcionó :( 
-acabo de hacer gitpush en mi repositorio: el problema está en el método decodificar del cliente-
De antemano, agradezco su ayuda! Saludos :)

**Comment by matiasmasjuan** [comment]
Hola @camirojasguajardo !

Estuve revisando tu código y pude encontrar dos problemas:
1. Uno de ellos no se debe al problema del **cliente** como tu señalas, sino que es problema del **servidor** al momento de **codificar** el mensaje. En el archivo ```cliente.py```, si imprimes *bytes_mensajes* luego del *try* (casi al principio del método), te darás cuenta que el mensaje viene cortado. En particular, se ve algo asi:

```python
bytearray(b'\x00\x00\x00\x00{"nombre": "Susan Whitaker"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
```
Como se puede observar, el diccionario está cortado (el diccionario no está completo, le falta la ' } '). Esto se debe a que los **límites** de ```chunk[inicio : final]```, están corridos. En particular, recuerda que en strings, listas, etc, el ``string[ inicio: final]`` **no incluye** el valor de **final**, por lo que si quieres incluir ese límite, deberas definir ```chunk[inicio : final + 1]```.

2. El otro problema se encuentra en **cómo** está implementado el ```mensaje.rstrip(b\x00')``` en el **cliente**. Recuerda que esto sería llamar al método, pero no lo alteraría, por lo que su correcto uso sería: ```mensaje = mensaje.rstrip(b'\x00')```.

Solucionado esas dos cosas no deberías tener problemas y la decodificación debería funcionar bien.

Saludos! :smile:

**Comment by camirojasguajardo** [comment]
@matiasmasjuan hola! agregué esas modificaciones y me sigue dando error :( ahora, con esos arreglos, lo que le paso al .loads() es esto: bytearray(b'\x00{"nombre": "Jessica Perkins"}'). Está bien?

**Comment by matiasmasjuan** [comment]
Lo importante es considerar que ```json.loads``` no se maneja correctamente con los *bytes* ceros (```b'x\00'```) por lo que deberás **quitarlos** para no tener errores. De todas formas, recuerda siempre **cumplir** con el **protocolo de envío** señalado en el enunciado.

Saludos! :smile:

**Comment by camirojasguajardo** [comment]
eso era! jaja muchas gracias, me ayudaste mucho!
