### ISSUE TITLE
Serialización y endianess

### ISSUE THREAD

**Issue by tocococa** [IIC2233/syllabus#1116]
Hola! Para el protocolo de comunicación servidor-cliente, se especifica que la ID y el largo deben tener un _endianess_ particular, pero para el objeto/información que se envía serielizada a continuación no se especifica nada, ¿eso significa que queda a criterio nuestro que _endian_ usar o me falta leer algo?

**Comment by vicentevegaulloa** [comment]
Hola @tocococa!

El _endianness_ es importante a la hora de tranformar `int` a `bytes` y viceversa. Es por eso que se te indica el _endianness_ sólo para los largos e IDs. Los métodos `int.from_bytes` e `int.to_bytes` reciben entre otros argumentos el _endiannes_ para poder serializar o deserializar. Como esto sólo es necesario para `ints`, no debes preocuparte del resto de la información enviada y recibida.

**Comment by tocococa** [comment]
Solo por curiosidad, ¿porqué es importante para convertir `int` y nada más?

**Comment by vicentevegaulloa** [comment]
El endiannes define el orden de los bytes. Los metodos from_bytes y to_bytes te piden el endiannes para saber como quieres ordenar los bytes (de izquierda a derecha o derecha a izquierda). En python, solo los ints poseen estos metodos, por lo que si quisieras cambiar el endianness de un string o un float basta con que des vuelta el bytearray (como se explica en este [link](https://stackoverflow.com/questions/46109815/convert-string-from-big-endian-to-little-endian-or-vice-versa-in-python)).

Si quieres saber más sobre el endianness este [video](https://www.youtube.com/watch?v=NcaiHcBvDR4) lo explica de forma sublime (como gran parte de los videos del [canal](https://www.youtube.com/channel/UC9-y-6csu5WGm29I7JiwpnA).

Espero haberte ayudado!

**Comment by tocococa** [comment]
Gracias! Amo Computerphile ❤️ .

**Comment by NikiHV** [comment]
Hola!! Me queda una duda que tengo que se pregunta en esta issue, pero que no me quedó clara la respuesta.

Para la información que se envía (fuera del id y el largo), es decir, el color, la imagen de la carta, etc., el enunciado dice que debe enviarse serializada, pero no dice (hasta donde leí) con qué tipo de serialización. ¿Nosotros debemos decidir el protocolo de serialización del contenido mismo? ¿Qué serialización me recomendarían usar?

¿Si lo envío como bytes nomás estaría mal? Porque en ese caso solo estaría codificando y no serializando como pide el enunciado 😥 (Pero encuentro medio extra estar serializando si con codificar en bytes ya es suficiente)
