### ISSUE TITLE
Cliente recibe datos solo una vez

### ISSUE THREAD

**Issue by fedezang** [IIC2233/syllabus#1117]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo una duda respecto a los clientes, ya que cuando intento enviar información, solo reciben una vez un mensaje serializado. Si intento enviar información nuevamente, se envía, pero no la recibe el cliente. Por qué podría estar pasando eso? Estoy ocupando la misma estructura que en la AF05, pero no logro encontrar un error.

**Comment by EduardoIllanes** [comment]
Hola @fedezang !
Perdón por la demora en responder, estuve harto rato probando tu código y el error se encuentra en tu función  `recibir` que esta haciendo que se quede pegado y que no reciba mas mensajes. Te recomiendo revisar [esto](https://github.com/IIC2233/contenidos/blob/master/semana-14/3-ejemplos.ipynb) que te puede servir para realizar un correcto recibimiento de los mensajes y su manejo, podrás notar que no es muy diferente a tu código  por lo que no deberían ser muchas modificaciones para que te quede funcionando. Éxito con tu tarea 🙌

**Comment by fedezang** [comment]
Muchas gracias @EduardoIllanes. 
Estuve viendo harto mi código y el notebook que dijiste, pero aún así no veo donde se puede caer el código. Lo que si vi, es que se envía un mensaje vacío después de mi primer mensaje (bytearray(b'000000000000000000000000000000')), pero por lo que veo del código, no tendría por qué quedarse pegado en la función recibir, sino simplemente retornar un diccionario vacío.
Hay que manejar de forma excepcional ese caso? o no es ahí donde está el error?
Muchas gracias de antemano.

**Comment by fedezang** [comment]
Creo que logre encontrar el error y ahora me funciona. Muchas gracias por la ayuda
