### ISSUE TITLE
Actualizar imagen cartas

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1117]
Hola! Tengo un problema , cuando seteo bytes en una ventana con el setpixmap , lo que pasa es que yo intento hacer un setpixmap(qpixmap.ladfromdata(bytes)) pero me tira un error del tipo :
![Captura de pantalla 2020-06-24 13 53 53](https://user-images.githubusercontent.com/62029138/85614522-f5fa7380-b628-11ea-91d1-0f91659969db.png)
Que significa ese tipo de error ???

**Comment by vicentevegaulloa** [comment]
Hola @RonaldoSosa!

Por lo que he podido leer, ese error ocurre porque el `QPixmap` que utilizas en `setPixmap` debe ser una **instancia** de la clase `QPixmap`, no la clase `QPixmap`. Intenta guardar en una variable el `QPixmap` y luego usar la variable en `setPixmap`.

Espero que esto te funcione. Si no te funciona avisame y haz `push` para poder ver tu código.

**Comment by RonaldoSosa** [comment]
Sii era eso ! Ahora funciona !! Graciasss!!

**Comment by vicentevegaulloa** [comment]
De nada!
