### ISSUE TITLE
Al mandar mensaje de cliente a servidor se me desconecta el cliente

### ISSUE THREAD

**Issue by ChupetitoSuazo** [IIC2233/syllabus#1118]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, al intentar mandar un mensaje desde el cliente al servidor, logro hacer que se mande, pero al manejar la excepción me muestra un log que puse para saber si la conexión con el servidor fue reseteada (tal como lo hacen en la AF05 en el método de escuchar_cliente en servidor.py), siempre. A que se puede deber? El código esta actualizado en mi repositorio en servidor/servidor.py por si lo pueden revisar.

**Comment by Juampisaez** [comment]
Hola @ChupetitoSuazo 
Revise tu codigo y me da la impresion de que estas eliminando el cliente (en la linea 82). Eso podría generar el error.

Quedo atento :)
