### ISSUE TITLE
Imagenes en sala de inicio y espera

### ISSUE THREAD

**Issue by dchahuan** [IIC2233/syllabus#1118]
El cliente puede tener guardado la foto del logo? O la tiene que guardar el servidor y enviarsela al las salas?

**Comment by vicentevegaulloa** [comment]
Hola @dchahuan!

Si puedes. El enunciado dice que las cartas deben ser entregadas por el servidor, pero no hay problema con que pongas otros sprites en la carpeta del cliente.

**Comment by dchahuan** [comment]
yaya muchas gracias

**Comment by dchahuan** [comment]
Esto aplica a cartas dadas vuelta?

**Comment by vicentevegaulloa** [comment]
Todo lo relacionado con cartas es enviado por el servidor, incluyendo las cartas dadas vuelta.

**Comment by amparostevens** [comment]
> Todo lo relacionado con cartas es enviado por el servidor, incluyendo las cartas dadas vuelta.

Pero por ejemplo no se podría guardar la carta dada vuelta en el cliente para usarla sólo en el mazo ya que esa carta no va a cambiar nunca?

**Comment by vicentevegaulloa** [comment]
@amparostevens podrías enviarla al comienzo del juego desde el servidor y guardarla en el cliente para usarla por el resto del juego.
