### ISSUE TITLE
Chozas pueden estar sin caminos adyacentes ?

### ISSUE THREAD

**Issue by bastian-perez** [IIC2233/syllabus#1119]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ]X Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!
En el enunciado dice que cada choza debe estar al menos a dos caminos de distancia entre otra choza, pero no sale en ningún lado que para construir una choza, esta debe tener como requisito mínimo de construccion, dos caminos y otra choza después de estos. Para especificar mi duda mejor, supongamos que ya se dan las condiciones iniciales y cada jugador tiene sus dos chozas y dos caminos, si el primer jugador desea construir una choza, esta puede ser en un nodo vació que no tenga nodos adyacentes con chozas o caminos ? que no esté conectada por caminos hacia alguna de las chozas que ya posee.
Espero que se entienda bien mi duda. 

Muchas gracias!!

**Comment by rodrigobj99** [comment]
Hola @bastian-perez !
Lo que dices es correcto, como establece el enuciado la única restricción para construir chozas es que estas esten a dos caminos de distancia de otra, por lo tanto no es necesario que esten conectadas por carreteras con otras chozas.

Espero haber aclarado tu duda. Saludos!
