### ISSUE TITLE
Orden de acciones en cada turno

### ISSUE THREAD

**Issue by GustavoLuzzi** [IIC2233/syllabus#112]
Por lo que entiendo de acuerdo a la respuesta a otras issues, la ejecución de las acciones de las distintas civilizaciones debiera realizarse luego de que todas hayan declarado lo que harán, por ejemplo:

**Turno 1**
    - Jugador declara acción.
    - I.A. 1 declara acción.
    - I.A. 2 declara acción.
    - Consecuencias de las acciones.

Sin embargo el orden en que se ejecuten las acciones podría afectar las consecuencias. Por ejemplo, si el jugador decide atacar a IA 1, e IA 1 decide atacar a IA 2, si ejecutamos primero el ataque de IA 1 sus soldados no podrían defender el ataque del jugador, y el resultado sería distinto al obtenido al ejecutar los ataques en orden inverso. Cómo ejecutamos el orden de las acciones entonces? Siempre primero la civilización de id 0 y luego la de id 1 y 2??

**Comment by DCCollao** [comment]
Hola!
A la hora de hacer los cálculos de qué sucede después de seleccionar las acciones, se considera todo como un simultáneo. 

- civ1: Ataca a civ2
- civ2: Ataca a civ3
- civ3: Ataca a civ1

En este caso, si consideráramos el orden en que se ejecutó cada acción, civ1 recuperaría sus soldados luego de ejecutarse su ataque a la civ2, y por lo tanto estarían disponibles para defensa.

La manera correcta de hacerlo, es considerando que las acciones son simultáneas, es decir que civ1 al haber atacado a civ2, no cuenta con soldados para defenderse del ataque de civ3. Solo recuperará su defensa al terminar todas las acciones (Una forma de verlo es que los soldados no alcanzan a volver a su civilización respectiva para defender).

Espero haber aclarado tu duda, ánimo!

**Comment by GustavoLuzzi** [comment]
Muchas gracias!! Me quedan eso sí algunas dudas respecto a la simultaneidad de las acciones, por ejemplo:

- Si la civilización 1 ataca a la 2, y la civ. 2 ataca a la 1: en caso de que ambas tuvieran PA mayor a los PD del oponente, ambas pierden y gana la civilización 3?

- Si la civ. 1 y la civ. 2 atacan a la civ. 3: en caso que ambas tuvieran PA suficientes para derrotar a la civ. 3, quién se queda con la fracción aleatoria de sus recursos y ayudantes? Así mismo, si ninguna por separado tiene los PA suficientes para derrotar a la civ. 3, pero el poder de ataque de ambas juntas logra vencerla, quién se adjudica la derrota y por ende los recursos y ayudantes?

- Si la civ. 1 ataca a la civ. 2, la civ. 2 a la civ. 3, y la civ. 3 a la civ. 1: si todas tuvieran PA suficientes para derrotar a la civ. defensora, entonces pierden los 3 y hay un empate?

**Comment by DCCollao** [comment]
Hola!

Creo que ahora entiendo mejor tu duda, y creo que se responde bastante bien con el siguiente fragmento del enunciado:
![image](https://user-images.githubusercontent.com/37167447/55673956-19e76300-5885-11e9-9566-e6ec189e9168.png)
Esto quiere decir que debes seguir el orden indicado en acciones.csv para el cálculo de estas situaciones

1. Si sucede lo que explicas en este caso, el primer ataque que se haya efectuado según el archivo, será el ganador.

2. En este caso, también el primer ataque realizado según archivo será el ganador. En el segundo caso que planteas en este punto, el primer ataque debilitaría a la civilización objetivo, y el segundo sería el remate, por lo que la segunda civilización en atacar es la que se llevará los recursos y ayudantes.

3. Como la civ. 1 fue la primera en atacar a la civ. 2, y además cuenta con ataque suficiente para derrotarla, la civ. 2 no alcanza  a atacar a la civ.3. Esto tiene la consecuencia de que la civ. 3 sí logre atacar a civ. 1, y por lo tanto civ. 3 sería la ganadora en esta secuencia.

Para responder a tu pregunta tomé en cuenta que las 3 civilizaciones que me mencionaste fueran IA, pero es importante que recuerdes que la civilización del jugador es la que ejecuta primero su acción en cualquier caso.

Cualquier duda que te quede, deja un comentario!
Saludos y ánimo!

**Comment by GustavoLuzzi** [comment]
Perfecto, me quedó clarísimo. Muchas gracias!!
