### ISSUE TITLE
Problemas para aceptar strings como input()

### ISSUE THREAD

**Issue by mmunoz12** [IIC2233/syllabus#112]
Cuando creo un input() y utilizo opciones a elegir que sean numeros, no tengo ningun problema. Pero cuando quiero crear inputs que son palabras nuevas, por ejemplo al momento de crear usuario nuevo, python me tira el error de que la palabra nueva del input no esta definida.

**Comment by Tito0906** [comment]
Holaa @mmunoz12, ¿A que te refieres con utilizar opciones que sean números?  ¿Estas teniendo problemas para ingresar sólo letras al input() pero no números?

**Comment by mmunoz12** [comment]
Ya entendi mi problema! no estaba escribiendo el input como un string (con ""). Pero en la tarea, cuando un usuario quiera iniciar sesión, escribira su nombre como string ("") ? o nosotros debemos codificarlo para que el código acepte el nombre sin las comillas? no se si se entiende jaja

**Comment by Tito0906** [comment]
Cuando un usuario ingresa su nombre no debería incluir las comillas. La función input() cuando recibe lo ingresado, lo transforma automaticamente a _string_. Esto ocurre independiente de lo que se reciba en el input, por lo que no deberias necesitar transformar nada. 
Para probar el formato en el que estas recibiendo los elementos recuerda que existe la función type().

**Comment by mmunoz12** [comment]
si! eso pensé. Pero aun así me aparece el error NameError: name 'Juanuwu379' is not defined, por ejemplo, cuando no utilizo las comillas. Solo usando comillas me resulta :(
pd: ya revise que los usuarios no estuvieran guardados con comillas desde antes jaja

**Comment by Tito0906** [comment]
@mmunoz12  ¿Donde estás corriendo tu código? ¿Por favor prueba usando raw_input() en vez de input()? 
Si te funciona el raw_input() entonces están usando python 2.x y no python 3.x.

Quedo atento.

**Comment by aaossa** [comment]
@mmunoz12 creo que lo que pasa es que tienes algo como 
```python
input = input()
```
Entonces Python reemplaza el significado de input (la función que recibe lo que ingresa el usuario) por el resultado de dicha operación (un *string*). Prueba cambiandole el nombre a la variable.

**Comment by Tito0906** [comment]
Hola @mmunoz12! 

La razón por la cual te pedí probar raw_input() es porque esta es una función sólo de python 2.x y no de python 3.x . A lo largo de este curso se usará y revisaran las tareas con python 3.7 no con 2.x. Por esto, si te funciona raw_input(), es necesario que **cambies la versión de python** con la cual estás corriendo tu programa.

Saludos y éxito en tu tarea!

**Comment by mmunoz12** [comment]
Al final era ese el problema, no me di cuenta que tenia otra version. Mil gracias! @Tito0906
