### ISSUE TITLE
Duda respecto a parámetros

### ISSUE THREAD

**Issue by Daniel-Guajardo** [IIC2233/Syllabus#112]
Buenas:

Si por ejemplo tengo esta condición

![image](https://user-images.githubusercontent.com/101299560/162589960-f6dc56e6-77d3-4f65-8a2f-f1c0dff04bb7.png)

¿Ese incremento en 2 de ego, 3 de suerte y condicionalmente 5 de frustración los puedo escribir de forma fija en el código? ¿O debo también crear un parámetro para esos valores en el módulo de parámetros y darles esos valores?

**Comment by antoniablanco** [comment]
Dado qu estan en color azul, es necesario crean parametros dentro del modulo parametros.

**Comment by Daniel-Guajardo** [comment]
Asumo entonces que los números en azul de estas fórmulas también deben ser pasados como parámetros. ¿Estoy en lo cierto?

![image](https://user-images.githubusercontent.com/101299560/162591617-ebbda2e5-0e6f-4a17-b973-7e200d0bd577.png)

**Comment by mvvaldes** [comment]
Pero como el archivo parametros.py no se sube, como van a saber que nombre les puse?

**Comment by antoniablanco** [comment]
Si, todos los valores en azul.
