### ISSUE TITLE
csv orders

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#112]
Cuando no ha existido match no debería de todas formas haber un ";"";" como si fuese un string vacio?

**Comment by Hernan4444** [comment]
@movaldivia en ninguno de los archivos se coloca comillas para los string, del mismo modo si no hay nada en una casilla (no hay match) tampoco deberíamos poner comillas... no sería consecuente con el formato del archivo, si no hay nada entonces encontrarás dos puntos y coma seguidos `;;`

**Comment by movaldivia** [comment]
@Hernan4444 okey gracias por la info !
