### ISSUE TITLE
vida de torre y ejercito en guerra

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#112]
En el enunciado se habla de que el ataque de la torre de defensa se suma a al ataque del ejercito pero nose aclara si ocurre lo mismo con la vida de la torre . Tambien no me queda claro si cada vez que disminuye la vida del ejercito tengo que aplicarle la disminucion a  un numero de soldados especificos o esta se calcula desde el principio sumando las vidas de todos y solo cuando esta llega a 0 calculo el numero de soldados sobrevivientes sin considerar disminuciones para cada soldado.

**Comment by IchottMano** [comment]
@sjkinast Hola!
Ya que la vida de la torre no aparece en el enunciado, queda a tu criterio como decidas implementarlo 😄 
En segundo lugar, tal como dices tu, los soldados sobrevivientes se calculan una vez que el otro ejército ha sido derrotado.
Saludos y mucho éxito con la tarea!
