### ISSUE TITLE
Display de consultas usuario ANAF

### ISSUE THREAD

**Issue by Genaron** [IIC2233/Syllabus#112]
Tengo varias dudas con respecto al display de las consultas que un usuario ANAF puede realizar.

1. Al leer las filas del archivo de los incendios, deben mostrarse solo las filas de los incendios que han existido al momento de realizar la consulta (considerando la fecha y hora ingresadas al iniciar sesión), o deben mostrarse todas las filas del archivo 'incendios.csv'?

2. Al leer las filas de los usuarios, deben mostrarse las contraseñas?

3. Al hacer cualquier consulta avanzada (Incendios activos o apagados, recursos más utilizados o más efectivos), nuevamente.. Se considera solo lo que ha pasado hasta el momento de la simulación, o se consideran absolutamente todos los datos de los '.csv'? Por ejemplo, si entro al sistema el día 2017-03-10 y hay un incendio que empieza el 2017-03-11.. debo considerarlo 'apagado', 'activo' o no debo considerarlo? Lo mismo va para la cantidad de veces que los recursos han sido utilizados o en su ordenamiento del más efectivo al menos efectivo.

Además, al planificar la estrategia de extinción de un incendio, éste debe estar activo? Pensé que podría ocurrir que se envíen los recursos antes de que el incendio empiece, para que lleguen al mismo tiempo que la fecha de inicio y así su extinción sea más efectiva.

Gracias de antemano.

**Comment by rpalmaotero** [comment]
Punto a punto:

1. Parece consecuente al segundo párrafo de esa parte del enunciado mostrar sólo los activos.
2. Sí.
3. Igual que el punto 1), para ser consecuente sólo muestra los activos.
4. No está definido por lo que queda a tu criterio, sin embargo creo que te puede complicar más de lo que aporta. Te recomiendo considerar que sólo puedes apagar incendios que ya comenzaron.

**Comment by Genaron** [comment]
Muchas gracias
