### ISSUE TITLE
Duda sobre volver atrás y salir en los menú

### ISSUE THREAD

**Issue by KainaBGR** [IIC2233/Syllabus#112]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Quisiera saber qué acción ocurre cuando se seleccionan las opciones volver atrás y salir en cada menú. 
En primer lugar, al presionar volver atrás en algún menú ¿se debe deshacer la acción elegida previamente? por ejemplo: en el menú crear objeto, si se escoge una baya ¿se debe volver atrás y que se le quite al entrenador esa baya?; o ¿lo que debe ocurrir al escoger volver atrás es que se muestre en consola el menú anterior? por ejemplo: en el menú crear objeto si se escoge volver atrás que se muestre el menú entrenador.
En segundo lugar, al presionar salir en cada menú ¿se debe salir del juego por completo, sin importar el menú en que se está?
Gracias :)

**Comment by Emiliax16** [comment]
Hola @KainaBGR ! SI realizas una acción en cualquiera de los menús, esta acción debe aplicarse en todo los que implica por el resto del juego/turno según especifique el enunciado. El volver atrás es únicamente para poder tener un flujo adecuado del juego, no para deshacer nada de lo seleccionado. Un ejemplo es: el entrenador decide entrenar a un programón (lo cual tendrá sus efectos correspondientes en ambos). Luego, vuelves atrás al menú y participas en la Liga, los cambios que tuvieron el entrenador y el programón en el entrenamiento debes conservarse para esta liga. En resumen:
**Volver atrás** sólo te lleva al menú anterior, no cambia nada más. 
Saludos!

**Comment by bernirosas** [comment]
> Hola @KainaBGR ! SI realizas una acción en cualquiera de los menús, esta acción debe aplicarse en todo los que implica por el resto del juego/turno según especifique el enunciado. El volver atrás es únicamente para poder tener un flujo adecuado del juego, no para deshacer nada de lo seleccionado. Un ejemplo es: el entrenador decide entrenar a un programón (lo cual tendrá sus efectos correspondientes en ambos). Luego, vuelves atrás al menú y participas en la Liga, los cambios que tuvieron el entrenador y el programón en el entrenamiento debes conservarse para esta liga. En resumen: **Volver atrás** sólo te lleva al menú anterior, no cambia nada más. Saludos!

Hola! ¿Y que pasa en el menú del entrenador al volver al menú de inicio? No tiene mucho sentido que siga teniendo el entrenador asignado cuando lo único que se puede hacer es elegir un entrenador.
Saludos y gracias de antemano.
