### ISSUE TITLE
quitar y agregar tuneles asegurar_ruta

### ISSUE THREAD

**Issue by emivenezian** [IIC2233/Syllabus#112]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

En el enunciado dice que no se pueden agregar tuneles, pero puedo quitar un tunel y luego volver a agregarlo? Al final mantengo o disminuyo la cantidad de tuneles, no se agregan nuevos.

**Comment by MaxAl100** [comment]
Hola! La idea del enunciado de "no agregar túneles" significa que, al llegar a la solución, no tengas túneles que no hayan existido antes. Es decir que, al testear, sí puedes ir probando sacar distintos túneles y ver si funciona o no y agregarlos de vuelta en caso de ser necesario, pero no puedes terminar con un túnel donde en un comienzo no había ninguno.
Si sigues teniendo dudas, preguntame de nuevo! 😄
