### ISSUE TITLE
Clase reemplazar y formato del nuevo tablero

### ISSUE THREAD

**Issue by Yeps3nM** [IIC2233/Syllabus#112]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, he tenido problemas para implementar el código del método reemplazar porque no entiendo cómo se podría realizar la separación de la parte de la lista que corresponde al nuevo tablero teniendo en consideración las nuevas dimensiones. Debo entregar el nuevo tablero en formato de listas de listas? Para esto puedo buscar información/códigos de internet referenciándolos?

**Comment by Arielmanriquez** [comment]
Hola, no entiendo muy bien tu pregunta pero te dejo un mini resumen de lo que tiene que hacer este método. Este método retorna True si se logro reemplazar el tablero, y False si no se encuentra el tablero en el archivo.  En el método debes recorrer el archivo, encontrar la linea correspondiente, encontrar los datos(dimensiones, casillas) y cambiar los atributos de la clase correspondientes. El tablero que se guarda en el atributo tablero debe estar en el mismo formato que el original, lista de listas.
Si algo no te quedo claro me preguntas de nuevo, no hay problema.

**Comment by Yeps3nM** [comment]
Ya entiendo mejor, lo otro que iba relacionado a eso en mi duda es que si puedo encontrar ayuda en código externo y luego citarlo. Muchas gracias !!

**Comment by Arielmanriquez** [comment]
Lo siento, se me olvido esa parte. Por supuesto, puedes ocupar codigo externo siempre y cuando lo cites en el README y/o como comentario en la función.
