### ISSUE TITLE
duda de codigo entre archivos

### ISSUE THREAD

**Issue by nnovoag** [IIC2233/syllabus#112]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
hola! no se que hacer porque no me aparece ningún error pero quiero cambiar un atributo de una clase y en base a ese cambio va avanzando mi codigo y no se  esta cambiandooo AIUDAA

**Comment by IgnaciaJ** [comment]
Hola @nnovoag! puedes subir tus avances a tu repositorio y señalarme que atributo el que estas intentando cambiar?
