### ISSUE TITLE
Duda AC1 estudios con generos

### ISSUE THREAD

**Issue by ikahene** [IIC2233/Syllabus#112]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema
Al probar los test me dice que al menos un 50% de ellos tiene error porque se esperaba que la respuesta fuera un string en minúsculas aún cuando en la tupla que describía el anime, el estudio era con mayúsculas, por ejemplo si mi función retorna Ghibli porque así está escrito en la namedtuple los test esperan que la respuesta sea ghibli... En este caso debo tratar de solucionar este problema de alguna manera o da lo mismo?

**Comment by RGutierrez21** [comment]
Tengo la misma duda. Corriendo los test retornando sólo minúsculas, arrojan todos correctos, pero si dejo que retorne el nombre del estudio con el que trae en la namedtuple arroja todos los tests incorrectos.

**Comment by Hernan4444** [comment]
Hola,

Recomiendo revisar esta issue:
* https://github.com/IIC2233/Syllabus/issues/26

Pero en resumen, pasarlo a minúscula no es la solución, es que esa función pide una cosa en particular que falta tener en cuenta.

Saludos! 🦖
