### ISSUE TITLE
Recibir Instancias de Clase del servidor en Cliente

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#1121]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Quiero enviar una instancia del servidor al cliente pero cuando lo cargo en el cliente no me resulta.
Tengo las clases definidas en ambos módulos,  los módulos y las clases tanto del servidor como del cliente tienen el mismo nombre.  Envió una foto de mi código. 
Paa saber si el dumps y loads funciona correctamente en la clase probé el loads en el serviddor y se carga la instancia. Pero cuando lo hago en el cliente no funciona.
El error que me tira es  _pickle.UnpicklingError: unpickling stack underflow.

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

![Enviar mapa](https://user-images.githubusercontent.com/69764237/100514617-97f12f80-3176-11eb-82f6-1bffd4e051fe.PNG)
![recibir_mensaje](https://user-images.githubusercontent.com/69764237/100514620-9d4e7a00-3176-11eb-9330-3365710d66fd.PNG)

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by DCCollao** [comment]
Hola @enriquemolinare!

Logré replicar el error de pickle enviando datos entre cliente-servidor. Este me aparece solamente cuando intento leer un dato de pickle que no está completo, lo que me hace sospechar de un protocolo de envío de mensajes incorrecto. Te recomiendo que revises tu protocolo!

Cuando me aseguro de tener el largo del mensaje correcto, no me aparece ningún error y puedo cargar los datos sin problemas. Quizás [este link](https://stackoverflow.com/questions/23964048/python-unpickling-stack-underflow) pueda ser de ayuda.

**Comment by enriquemolinare** [comment]
revise la diferencia. Encontre solo una. Cuando hago el protocolo en servidor se agregan unos slash "/". La verdad es no tengo idea porque. 
Si te fijas  el mensaje antes de ser enviado a protocolado desde el servidor  es igual al mensaje protocolado en el servidor y al mensaje recibido del cliente solo que el mensaje original solo tiene un "/" entre cada bytes y el mensaje protocolado por el servidor y el mensje recibido por el cliente tienen dos "//".
El mensaje protocolado por el servidor te lo envió en los chunks cuyos primero 4 bytes es el numero del bloque y los otros 60 bytes es el mensaje. 
El mensaje protocolado en el servidor y el recibido en el cliente es el mismo
![Mensaje original](https://user-images.githubusercontent.com/69764237/100539241-6723ff80-3235-11eb-8570-42e710fdb8a4.PNG)
![Mensaje protocolado](https://user-images.githubusercontent.com/69764237/100539243-6c814a00-3235-11eb-8e2e-05db8327556c.PNG)
![Mensaje client](https://user-images.githubusercontent.com/69764237/100539244-70ad6780-3235-11eb-9e57-ad631c208bfb.PNG)


a de cuando se envía el mensaje y cuando
