### ISSUE TITLE
Problemas al iniciar clase cliente desde la ventana inicial

### ISSUE THREAD

**Issue by tcouso** [IIC2233/syllabus#1121]
Hola!
Adujunto nuevamente el issue, pues el anterior se perdió entre los demás.
Quiero que mi clase cliente sea instanciada por la ventana inicial, para que la conexión al servidor se lleve a cabo una vez que el usuario ingrese su nombre y presione el botón de ingreso. Intenté hacer esto haciendo que la clase cliente se instanciara una vez que se emite una señal de la ventana inicial. Sin embargo, por motivos que desconozco, cuando hago esto mi programa empieza a imprimir eternamente "QCoreApplication::exec: The event loop is already running" y luego termina cayéndose. He tratado con aproximaciones similares y me termina pasando lo mismo. 
Muchas gracias de antemano por cualquier ayuda! :)

**Comment by KnowYourselves** [comment]
Hola @tcouso!

Probe el código de tu repo y no me da ese error. Es ese el código del cual hablas, o todavía no haces push?

Quedo atento!

**Comment by CatalinaGoldsack** [comment]
Hola! Tengo el mismo problema y tampoco sé por qué es...
Según lo que he investigado tiene algo que ver con instanciar QApplication... pero no la pillo :(

**Comment by CatalinaGoldsack** [comment]
<img width="618" alt="Captura de Pantalla 2020-06-25 a la(s) 03 16 00" src="https://user-images.githubusercontent.com/62029175/85673865-51ad1700-b692-11ea-8bba-9d82c4919e37.png">
esto encontré en https://books.google.cl/books?id=d6t-DwAAQBAJ&pg=PT321&lpg=PT321&dq=%3E%3E%3E+QCoreApplication::exec:+The+event+loop+is+already+running&source=bl&ots=oPDpEU2Wxo&sig=ACfU3U1aaGMLVn-MEpYAdom5r2is01QbpQ&hl=es&sa=X&ved=2ahUKEwj3__uOs5zqAhXfILkGHdfyDt8Q6AEwB3oECAoQAQ#v=onepage&q&f=false

**Comment by tcouso** [comment]
> Hola @tcouso!
> 
> Probe el código de tu repo y no me da ese error. Es ese el código del cual hablas, o todavía no haces push?
> 
> Quedo atento!

Hola!
Había adaptado el código para entregar un adelanto de la tarea que funcionara. Sin embargo, ahora intenté nuevamente de la misma manera que antes y funcionó. Sinceramente no se por qué fue así. Aún así, muchas gracias por la ayuda.

**Comment by tcouso** [comment]
> Hola! Tengo el mismo problema y tampoco sé por qué es...
> Según lo que he investigado tiene algo que ver con instanciar QApplication... pero no la pillo :(

Ahora me funcionó, pero no estoy muy seguro de qué hice para que cambiara. Trataré de entenderlo y te comento cual era el problema. Muchas gracias por los recursos que compartiste!

**Comment by CatalinaGoldsack** [comment]
@tcouso bacán!!! Quedo atenta! Gracias!

**Comment by CatalinaGoldsack** [comment]
@KnowYourselves se te ocurre qué podrá ser?

**Comment by KnowYourselves** [comment]
Estimados,

Mis disculpas por la demora. Ya se cual es el error que le pasó a ambos. Como verás @CatalinaGoldsack tu al momento de iniciar sesión ocupas una señal que ejecuta una función donde instancias el cliente "al aire", es decir, sin asociarlo a tu mainwidget. El problema con esto, es que el cliente inicia un thread, que, por no estar asociado al mainwidget como atributo, provoca que choque con el thread de PyQt, ergo el error ""QCoreApplication::exec: The event loop is already running", intentaste iniciar un thread no relacionado a PyQt cuando el thread principal de este ya estaba corriendo.

La solución? Instancia el cliente como atributo de tu mainwidget. Con esto PyQt puede hacer que ambos threads funcionen en armonía.

Éxito!

**Comment by CatalinaGoldsack** [comment]
Perfeeecto!!! Creo que ahí lo pude solucionar, muchas gracias :)  😊
