### ISSUE TITLE
Señales del cliente no funcionan

### ISSUE THREAD

**Issue by stephenwpugh** [IIC2233/syllabus#1122]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Estoy creando señales backend-frontend en mi cliente y parecen no funcionar, intenté hacer una señal de prueba muy simple para ver dónde está el error, y es como si no estuvieran conectadas las señales en el main (probé conectando señal con método y también igualando señales). ¿Qué podría ser? Quizás influya que mi conexión con el servidor tampoco está al 100%
Muchas gracias desde ya! :)

**Comment by Juampisaez** [comment]
Hola @stephenwpugh 
Revisaste que el flujo llegara a la señal? es decir, lo pudiste visualizar con prints. De esta forma tal vez verias el problema de mejor manera. Me refiero a que cada vez que el cliente y el servidor se comuniquen, muestres su mensaje y luego veas si los mensajes llegan a tu interfaz.

Quedo atento :)

**Comment by stephenwpugh** [comment]
Puse **1.** Un `print('test backend)` en la funcion que emite la señal, **2.** un ´print('test frontend')` en la funcion del frontend que recibe la señal y **3.** un `print('test main)` justo despues de conectar la señal con la funcion en el main. De los 3 prints solo funciono el **backend y main** pero no el del frontend.

**Comment by jo00** [comment]
Hola yo tengo exactamente el mismo problema :( no entiendo que estoy haciendo mal, pero no se ejecuta la función que debería ejecutarse del frotend y la señal sí es emitida y sí está conectada (o eso según yo)

**Comment by Juampisaez** [comment]
@stephenwpugh intenta hacerla conexion y todo sin la ventana por mientras (ve si funcionan bien los mensajes), tal vez como dijiste, la implementacion del servidor es lo que esta fallando (como dices que no esta al 100%).

@jo00 Utiliza prints en el frotend antes y despues de lo que estas ejecutando, hay veces que pyqt se pone mañoso y no reconoce ciertas acciones.

**Comment by jo00** [comment]
hola lo hago y alfinal lo unico que no se ejecuta es el modulo dentro de la mainwindow. Es decir, se realiza la coneccion y se emite la señal pero sigue sin ejecutarse la funcion dentro del frontend

**Comment by Juampisaez** [comment]
@jo00 Me meti a ver tu codigo y cache que instancias la ventana en el main, te recomiendo instanciarla dentro de tu clase Cliente y de ahi mismo mandar las señales. (he visto harto ese problema con otros alumnos, prueba eso y me avisas).
