### ISSUE TITLE
OSError: [WinError 10049] La dirección solicitada no es válida en este contexto

### ISSUE THREAD

**Issue by PedroFuenzalida** [IIC2233/syllabus#1123]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, al correr el ejemplo del notebook me tira el error "OSError: [WinError 10049] La dirección solicitada no es válida en este contexto" la línea de código **sock.connect((server_host, server_port))**

**Comment by aaossa** [comment]
Hola @PedroFuenzalida , sospecho que es porque le estás dando una dirección externa a tu cliente, ¿qué valor le estás dando en `server_host`? ¿Podrías probar usando `server_host = socket.gethostname()` en lugar de otro valor? 🤔 Cuéntame si te funciona

**Comment by PedroFuenzalida** [comment]
Es el ejemplo de envío a JSON. Para el server usa socket.gethostname() y para el client usa "".

**Comment by aaossa** [comment]
Mmm no estoy seguro de qué podría ser, ¿podrías probar imprimiendo el valor de `server_host` en el servidor y usar ese mismo valor en el cliente?

**Comment by PedroFuenzalida** [comment]
Lo cambie por socket.gethostname() y funcionó.
