### ISSUE TITLE
Servidor no reconoce sockets

### ISSUE THREAD

**Issue by sofiaolmedos** [IIC2233/syllabus#1124]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! LLevo hartos días con el problema de que el servidor y el cliente se logran conectar pero al momento de mandar o recibir mensajes el sevidor no reconoce el socket, me tira el error
```OSError: [WinError 10038] Se intentó realizar una operación en un elemento que no es un socket```
A veces ocurre cuando el servidor intenta mandar el mensaje y a veces cuando intenta escuchar al cliente (sendall() y recv()). 
Estoy usando una estructura muy parecida a la AF05, entonces no entiendo porque no está funcionando.

**Comment by DCCollao** [comment]
Hola @sofiaolmedos!

Ese error suele aparecer cuando cierras un socket y luego intentas realizar una operación sobre este socket ahora cerrado. Te recomiendo que te fijes especialmente en las partes en que cierras sockets para verificar que no esté sucediendo esto.

Otra cosa que podría ser útil es agregar un `print` cada vez que vayas a intentar realizar alguna operación sobre un socket, así sabrás si estás tratando de trabajar con algún socket que cerraste anteriormente.
