### ISSUE TITLE
Desconexión de cliente

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#1124]
Cuando un cliente se sale en la sala de espera por ejemplo, hay forma de enviar el status al servidor antes de que se desconecte? No se como se puede hacer :(

**Comment by igbasly** [comment]
Hola @tedroppelmann 😄 
Es una práctica utilizada avisar al servidor cuando un cliente se está desconectando o bien avisar a los clientes cuando el servidor se está cerrando para que ambas partes terminen sus procesos de forma correcta y evitar cualquier inconveniente.
Ahora, como implementarlo depende de cómo hayas modelado todo tu programa, en la AF06 se tocó una forma de avisar al servidor mediante un mensaje. Lo importante es ver **cuando** avisar al servidor, para no hacerlo antes de cerrar el *socket* y que el servidor tome las acciones necesarias para terminar la conexión con el cliente evitando los errores (como dejar de escuchar y enviar).

Avísame si esto aclara un poco como manejar esta situación y cualquier otra duda que surja 🙌 .

**Comment by Aloncarrasco** [comment]
que pasa si el cliente se desconecta repentinamente y no alcanzo a enviar el mensaje de status? debo asumir que esto no pasará?

**Comment by igbasly** [comment]
Hola @Aloncarrasco 😄 
En caso de que el cliente se desconecte repentinamente y no alcance a enviar un mensaje, no hay mucho que hacer de su parte, pero es muy probable que surja un error en el servidor donde puedes capturarlo y proceder en base a eso. Debes tener mucho cuidado de capturar este error de la forma correcta, es decir, validando el tipo de error ocurrido y no uno genérico.

De todas formas no puedes asumir que esto no ocurrirá, es parte de los esperado manejar estos errores.
Espero que se entiendo, quedo atento :v:.

**Comment by Aloncarrasco** [comment]
Ahhh entonces puedo usar try y except?

**Comment by igbasly** [comment]
Si, en esta tarea se permite `try`/`except` siempre y cuando se utilice correctamente atrapando los errores requeridos. Puedes asegurarte por la Issue #1026.
