### ISSUE TITLE
Protocolo Envío de mensaje para distintas serializaciones 

### ISSUE THREAD

**Issue by diegobustosk** [IIC2233/syllabus#1125]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola tengo una duda con el protocolo de envío de información. Lo que pasa es que de alguna manera en el programa dependiendo de lo que quiera enviar, podría necesitar serializar en pickle, json o un string. Mi pregunta es si puedo enviar antes de el largo del mensaje una cadena de bytes que indique de que forma en que el mensaje tiene que ser leido ? por ejemplo hacerle un un enconde a la palabra json para que el receptor sepa que tiene que leer esos bytes en determinado formato.
[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by EduardoIllanes** [comment]
Hola @diegobustosk! La respuesta es si, puedes. Recuerda eso si que cuando luego mandes el **mensaje, este debe seguir el formato estipulado en el enunciado**. Saludos!
