### ISSUE TITLE
Número de cartas que muestro en pantalla

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#1125]
Hola! El máximo de cartas son 10, entonces si llego a tener eso tengo que mostrar las 10 en pantalla??? 
Y cuantas son para el mazo inicial, por la pantalla que muestran en el enunicado, supongo que son 4.

**Comment by gatochico** [comment]
Hola! 

Las cartas con las que comienzan los jugadores queda a tu criterio (sería ideal si lo agregas como parámetro).

Tu otra pregunta depende si refieres al jugador o a sus contrincantes: Si te refieres al jugador, **sí es necesario** que se muestren todas sus cartas en la pantalla, ya que este necesita poder intentar jugarlas todas en su turno. Con respecto a los adversarios, en la issue #1031 se habla un poco al respecto (spoiler: no es necesario mostrar las 10, con tal de que se pueda saber de alguna forma cuántas cartas tengan los adversarios en todo momento).

Saludos y éxito! 🎴

**Comment by RonaldoSosa** [comment]
Hola! Una consultado sobre este mismo tema, entonces por hacer un ejemplo solamente , podríamos mostrar la imagen de 4 cartas siempre, y con un label con un mensaje como el que esta en el enunciado que me indica el turno,señalar cuantas cartas le quedan a cada jugador en el transcurso del juego?

**Comment by gatochico** [comment]
Si, no habría problema con eso siempre y cuando aplique para la vista de las cartas de los contrincantes y se puedan ver cuantas cartas tienen todos en todo momento, no solo cuantas tiene quien está jugando. Recuerda también que las cartas propias deben mostrarse todas siempre.

Y claro, dependiendo si quieres implementar por ejemplo, el bonus de _Anonymous_ (que revela las cartas del resto), tendrías que pensar como mostrar esto en tu interfaz. Si no lo piensas implementar, no habría problema con lo que dices.

**Comment by RonaldoSosa** [comment]
Yaaa entendido gracias!!!
