### ISSUE TITLE
Problema QObject y threading

### ISSUE THREAD

**Issue by fedezang** [IIC2233/syllabus#1126]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! En mi código cuando se unen la cantidad de clientes necesarios para comenzar el juego, se debería abrir la sala de juego para ellos, sin embargo a todos los clientes les llega el siguiente error:
QObject::setParent: Cannot set parent, new parent is in a different thread
No se me ocurre que lo puede provocar ni en que parte, ya que mi único QObject es el controlador que es único para cada instancia de cliente y un thread que escucha al servidor.

**Comment by fedezang** [comment]
Creo que lo pude solucionar :)

**Comment by nicolaszanni** [comment]
Hola, como lo solucionaste?

**Comment by fedezang** [comment]
Me base en la issue #1094  , que dice que la interfaz y su backend hay que manejarlo con señales y no aplicar funciones directamente.
