### ISSUE TITLE
Separación sprites servidor y cliente 

### ISSUE THREAD

**Issue by benjavicente** [IIC2233/syllabus#1126]
Me confundió la separación de sprites mencionada en el enunciado:

Se pide que el servidor tiene que contener y distribuir **todas las sprites a los distintos usuarios** (parte 4.2.1)

Pero en el issue #1118 se menciona que solo las cartas.
En el enunciado se muestra el logo, pero no señala quien lo almacena.

Entonces, ¿sí se pueden utilizar sprites adicionales para decorar la interfaz?
Gracias de antemano

**Comment by KnowYourselves** [comment]
Hola @benjavicente!

Como mínimo, el servidor debe hacerse cargo de todos los sprites relacionados a las cartas. El resto es decisión tuya.

Éxito!
