### ISSUE TITLE
Ventana de inicio no responde al abrir Sala de Espera

### ISSUE THREAD

**Issue by totaurt** [IIC2233/syllabus#1127]
Hola! Tengo un problema abriendo la sala de espera que no he podido solucionar:( La sala de espera nunca se muestra ya que al momento de hacerlo se queda pegada la ventana de inicio. He estado revisando el código hace horas y todo está bien hasta el momento en que el nombre ingresado vuelve a cliente del servidor e intento abrir la sala de espera. Cualquier cosa puedo intentar explicarlo mejor o enviarles mi código. Saludos!!

**Comment by KnowYourselves** [comment]
Hola @totaurt!

Tu error se debe a que estás intentando hacer show de la ventana de esperada desde un thread, lo cual no es válido para PyQt. Debes utilizar una señal, que haya sido conectada fuera del thread, y emitirla desde dentro de éste, para mostrar cualquier ventana.

Éxito!

**Comment by totaurt** [comment]
Muchas gracias! lo pude solucionar :)
