### ISSUE TITLE
Título descriptivo (reemplazar con el título apropiado)

### ISSUE THREAD

**Issue by ignaciovilla** [IIC2233/syllabus#1127]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado de la tarea se da el parámetro CANTIDAD_JUGADORES_PARTIDA y me surge la siguiente duda: 
¿Podemos asumir un número mínimo y máximo de jugadores? ¿Pueden haber más jugadores que colores de construcciones?
Muchas gracias

**Comment by matiasmasjuan** [comment]
Hola @ignaciovilla !

Esta pregunta fue respondida en la *issue* #1067 .

Saludos!
