### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by jaimecoloma** [IIC2233/syllabus#1128]
Hola! Tengo un error que no he podido encontrar (ni en mi codigo ni en la web) la solución. Es cuando cierro la ventana (cualquiera) de un cliente. Arroja una Exception en el thread escuchar del cliente pero no se que es! subi mi codigo con el avance. Indica también la linea 57 del archivo ```servidor.py```. La verdad es que no se si se puede pedir esta ayuda pero me rendi con el problema :( 
(Cabe mencionar que utilicé de base el archivo de la AF06, pero ya había arreglado todo aquel detalle para aterrizarlo a mi archivo de la tarea)

**Comment by igbasly** [comment]
Hola @jaimecoloma :v:
Este error es un error que usualmente genera UNIX (macOS o Ubuntu) al manejar el recibimiento de 0 *bytes*.
*Contexto:*
Al cerrar una ventana imagino que estás manejando el término de la conexión y cerrando el *socket* del cliente (corrígeme si no es así). Cuando esto sucede *socket* por detrás "envía" un *byte* 0, el cual recibe el servidor e intenta procesarlo. Puedes comprobar imprimiendo el *byte*.
Usualmente Windows maneja esta situación y genera el error `ConnectionResetError`, pero UNIX no.

Una forma y común de solucionarlo es verificando que cuando se reciben datos, estos *bytes* sean distintos de 0, de lo contrario levantar la excepción o romper el ciclo para continuar con el programa.
Otra forma, que fue la utilizada en la AF06, es avisar al servidor cuando el cliente se está desconectando para que este tome las medidas necesarias de terminar el ciclo y continuar con el programa sin nunca recibir este *byte* 0.

Espero que esto te ayude a solucionar el error y por favor avísame cualquier cosa 😊 .

**Comment by igbasly** [comment]
Agregar que cuando me refiero a 

> "verificar que estos *bytes* sean distintos de 0"

quiero decir algo como:

```python
bytes_recibidos != 0
```
Independiente de si estos vienen de un `.recv(1)` o un `.recv(1000)`, pero son los primeros bytes que se reciben y no parte de un chunk, ya que eso involucra que pudiste recibir un "largo".

**Comment by jaimecoloma** [comment]
@igbasly ahhh curioso! No lo sabia! Finalmente implementé el closeEvent que mande un mensaje al servidor particular para que no se genere el error y me funcionó! Muchisimas gracias!!
