### ISSUE TITLE
Restricciones para usar grafo.json

### ISSUE THREAD

**Issue by dedmu5** [IIC2233/syllabus#1128]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, ¿puedo usar el archivo grafo.json como yo quiera? Es decir, ¿puedo ocuparlo parcialmente o totalmente de cualquier forma que me sea conveniente, sin necesariamente usar lo que vimos para recorrer grafos? Ej: crear clases, Nodo, Hexágono, etc. Se que está la issue #1110 pero me gustaría saber si es obligatorio usar lo que aprendimos en grafos.

**Comment by DCCollao** [comment]
Hola @dedmu5! 

En la [distribución de puntajes](https://docs.google.com/spreadsheets/d/1V-lZqUru4iXlYBNE-0THUUB3MOYyUBj45i1OOslGGII/edit#gid=592899891) se muestra qué se espera que hagan con el archivo `grafo.json`. En esta se detallan los puntajes asignados a distintos trabajos con el archivo, como su cargado, instanciar el grafo o calcular el camino más largo. Es importante notar también que estos ítems están pintados de *amarillo*, por lo que serán evaluados mirando el código que hayan escrito.

**Comment by dedmu5** [comment]
> Hola @dedmu5!
> 
> En la [distribución de puntajes](https://docs.google.com/spreadsheets/d/1V-lZqUru4iXlYBNE-0THUUB3MOYyUBj45i1OOslGGII/edit#gid=592899891) se muestra qué se espera que hagan con el archivo `grafo.json`. En esta se detallan los puntajes asignados a distintos trabajos con el archivo, como su cargado, instanciar el grafo o calcular el camino más largo. Es importante notar también que estos ítems están pintados de _amarillo_, por lo que serán evaluados mirando el código que hayan escrito.

Gracias shrek
