### ISSUE TITLE
Duda al obtener 7 en el lanzamiento de dados

### ISSUE THREAD

**Issue by MagyarSplit** [IIC2233/syllabus#1129]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Cito: 

> Si el número obtenido corresponde a 7, el o los jugadores con 8 o más cartas deberán devolver la mitad de ellas de manera aleatoria al banco. Es decir, no podrán elegir qué cartas devolver.

Para lo anterior se debe usar floor? lo digo porque puede que tenga 9 cartas y en ese caso la mitad no es un número entero. 

Saludos,
Felipe

**Comment by matiasmasjuan** [comment]
Hola @MagyarSplit !

Dado que **no está explícito** en el enunciado, queda a **tu criterio** cómo evaluar este caso. De todas formas, recomiendo redondearlo hacia abajo (utilizando *floor*) ya que sigue la misma regla que el juego original. Por lo tanto, si un jugador posee 9 cartas y sale 7, deberá **devolver aleatoriamente** 4 cartas al banco, y **debe** quedarse con 5.

Saludos! :smile:

**Comment by fran-gl** [comment]
Las cartas que se devuelven aleatoriamente son solamente cartas de materias primas?

**Comment by matiasmasjuan** [comment]
Hola @fran-gl !

**Sí**, las cartas que se devuelven al salir un **7** **solo** son las **materias primas**. Las cartas de **desarrollo siempre se conservan**. Por lo tanto, sólo se **contabilizan** las cartas de **materias primas** en caso de que salga **7**, y se devolverá la mitad si es que el número de cartas de materias primas del jugador es **8 o más**.

Saludos! :smile:

**Comment by fran-gl** [comment]
Perfecto, muchas gracias!
