### ISSUE TITLE
Carta Reverso

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1129]
Hola!Cuando deseo enviar una carta de la extensión  reverso.png debería seguir el mismo formato que con las otras , si esto último es así que en la parte que se supone que deba ir el color de la carta debería dejarlo en blanco y en tipo deberia  colocar "reverso" ??

**Comment by gatochico** [comment]
Hola! 

La carta reverso debería seguir el **mismo formato** que pedimos para el envío de cartas, sin embargo, el qué poner en 'color' y 'tipo' quedará a tu criterio. (si puedes indicalo en el readme 🙈 )

Saludos y mucho éxito!

**Comment by RonaldoSosa** [comment]
Entendido !Gracias :)
