### ISSUE TITLE
Problema con escrito "Nombre Apellido" en repositorio privado

### ISSUE THREAD

**Issue by connandiaz** [IIC2233/Syllabus#113]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

Tras leer los documentos del curso no logré encontrar mi duda respecto a cómo cambiar el título de "Nombre Apellido" a la izquierda de donde aparece mi comentario de mi repositorio privado.

**Comment by Juampisaez** [comment]
Holaa @connandiaz 👋🏼
Probablemente cuando configuraste Git con las instrucciones de la [Wiki](https://github.com/IIC2233/Syllabus/wiki/3.-Software-Obligatorio), colocaste literalmente `git config --global user.name "NOMBRE APELLIDO"`. Para solucionar esto, basta solamente con configurar nuevamente este paso en tu terminal, colocando tu usuario de github, en vez de "NOMBRE APELLIDO".

Quedo atento a cualquier cosa,
Saludos,
