### ISSUE TITLE
Duda respecto a que debe retornar en Encontrar ciclo mas corto en main.py

### ISSUE THREAD

**Issue by BenjaminIbanez** [IIC2233/Syllabus#113]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Buenas tardes, Mi duda es que en la funcion encontrar_ciclo_mas_corto, lo que debe retornar la funcion es la cantidad de estaciones mas cortas para llegar a la estacion, es decir un numero. Por lo que me pregunto si en el main.py nosotros tenemos que darle un sentido al dato que retorna, por ejemplo si retorna -1 que significa que no existe ruta, en le main.py debe retornar un -1 o un mensaje que diga "No existe una ruta para llegar a esa estacion".

**Comment by jprabyb** [comment]
Hola, recomiendo revisar la issue #98 donde explican lo que hay que hacer en ese caso
Saludos
