### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'usuarios.csv' al escribir en el, no para leerlo (archivo cerrado)

### ISSUE THREAD

**Issue by nicogrecod18** [IIC2233/syllabus#113]
Hola, tengo el mismo problema que el issue #73 , solo que a diferencia de él **si** tengo el archivo cerrado. Lo raro es que hace un rato si me funcionaba y ahora no puedo correr el código porque me aparece el mismo error que al que posteó originalmente.
lo estoy intentando abrir con: excel_usuarios = open(ruta, "r+", encoding = "utf-8")
si le borro el "+", me deja abrir el csv, pero no puedo abrirlo si quiero escribir en el.
mi sistema operativo es windows 10

**Comment by gatochico** [comment]
Pregunta: Puedes escribir en el si abres el archivo manualmente con tu editor de texto , lo editas y lo guardas?

**Comment by nicogrecod18** [comment]
![image](https://user-images.githubusercontent.com/62031857/77127867-d6055380-6a2c-11ea-912f-3e153ba65685.png)

me sale esto

**Comment by gatochico** [comment]
Entonces el problema ya no es de tu programa, sino que el archivo en sí en algún momento se bloqueo para escritura. Intenta haciendo overwrite en la imagen de arriba a ver si se arregla y si no funciona, trata bajando el csv de nuevo desde el Syllabus.

Avísanos como te va! 🤓

**Comment by nicogrecod18** [comment]
lo arregle !!! por alguna razón en propiedades del archivo estaba marcado el atributo read only. Muchas gracias !!
