### ISSUE TITLE
Duda sobre energía del entrenador

### ISSUE THREAD

**Issue by armas01** [IIC2233/Syllabus#113]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Respecto a la energía del entrenador, la cual viene dada en el archivo "entrenadores.csv", si gana una ronda y se reestablece la energía, debe volver a su valor en el archivo, o a 100? Ya que considero que muchos entrenadores comienzan con demasiada poca energía. Saludos.

**Comment by MrNachoX** [comment]
Hola @armas01, la energía de los entrenadores vuelve al máximo, es decir 100 y no el valor del archivo.
