### ISSUE TITLE
Evolución galaxia

### ISSUE THREAD

**Issue by castrillini** [IIC2233/Syllabus#113]
El nivel de evolución de una galaxia es el promedio del nivel de evolución de todos sus planetas, eliminando al planeta con mayor y menor nivel.
¿Qué pasa si tengo más de un planeta que comparte el máximo nivel de evolución?¿sólo se elimina un planeta?

**Comment by santilaguna** [comment]
no soy ayudante, pero es lo lógico no? Piensalo como eliminar tu peor nota de las actividades, no se eliminan 2 solo una =(

**Comment by IchottMano** [comment]
@castrillini Hola!
Efectivamente como dice @santilaguna , sólo se elimina uno de los dos (o varios) planetas que compartan el valor mas alto o bajo de evolución.
Saludos!
