### ISSUE TITLE
duda de reportes de incendios

### ISSUE THREAD

**Issue by rjdelrio** [IIC2233/Syllabus#113]
en el enunciado sale que la carpeta a crear se llamara Reportes Estrategias de Extinción pero dice en el enunciado también que se debe crear un archivo por incendio, entonces tengo la duda si el archivo se hace por CADA incendio o por cada planificación tomada?

**Comment by rpalmaotero** [comment]
> El nombre de cada reporte debe ser de la forma `id_incendio_nombre_criterio.txt`.

Debe ir con ese nombre (reemplazando los valores) dentro de la carpeta que mencionas.
