### ISSUE TITLE
Probabilidades dan siempre super malas

### ISSUE THREAD

**Issue by mvvaldes** [IIC2233/Syllabus#113]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, como se ha conversado en otro par de issues, las probabilidades de ganar pueden dar negativas. 

En lo personal encuentro que la respuesta que han dado de tomar el valor absoluto no tiene mucho sentido, porque hace que parámetros que deberían dar una mala probabilidad de ganar den una buena.

El tema de esta issue es que no solo puede dar negativo, sino que con las estadísticas iniciales para varios jugadores da siempre negativo, lo que hace que nunca puedan ganar, con esto en mente mi pregunta es:

Están seguros que la formula tiene esos paréntesis antes de favorito y esperanza?
![image](https://user-images.githubusercontent.com/50001680/162595078-b511bbff-ea64-430e-910d-8b0f0102aba0.png)

A mi no me hace sentido, porque los paréntesis le dan una contribución negativa de la "esperanza" a cada probabilidad.

**Comment by Ilancf** [comment]
No entiendo que tenemos que hacer, porque de hecho la probabilidad de ganar en un juego me da siempre negativo de lo bajo que es, entonces jamas ganaría alguien, entonces se va a cambiar algo del enunciado o algo, porque siempre se perdería

**Comment by antoniablanco** [comment]
Si hay personajes que tienen posibilidad positiva, centrate en los parametros que más afecten positivamente la formula. Y de esa forma puedes elegir un personaje que tenga tales parametros altos. En cualquier caso, no se evalua si es que se puede ganar, sino el programa en si.
