### ISSUE TITLE
T1, menú de acciones, error al importar utils

### ISSUE THREAD

**Issue by danogajardo** [IIC2233/Syllabus#113]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Al intentar importar el archivo utils.pyc, estando este en la misma carpeta que el main, me lanza el siguiente error: **Import "utils" could not be resolvedPylance[reportMissingImports]**. Intente importarlo con las versiones 3.11.9 y 3.12.5 resultando en ambas el mismo error.

**Comment by FernandoTFH** [comment]
Este error te lo da la terminal o el editor que estas usando?

**Comment by danogajardo** [comment]
el editor, uso visual code

**Comment by FernandoTFH** [comment]
El tema es que como el utils está compilado, visual code no puede ver su contenido, en general esto es para que extensiones que te ayudan a encontrar errores(como  pasarle mas o menos variable a una función que importaste) y recomendarte (autocompletado) y dar información de las funciones y/o variables que tenga el archivo importado  .No debería afectar a la hora de ejecutar tu programa.

**Comment by Cristobal-Hevia** [comment]
Me pasa lo mismo a mí a la hora de hacer Import utils, no entiendo cómo resolver el problema, y es necesario importar sus funciones para avanzar con la tarea.

**Comment by Cristobal-Hevia** [comment]
ya resolví el problema, el archivo se llamaba "utils.pyc" y le cambie el nombre a "utils.py" y me dejó importarlo

**Comment by Cristobal-Hevia** [comment]
Ahora cuando ejecuto el menú me da este error: SyntaxError: source code string cannot contain null bytes

**Comment by FernandoTFH** [comment]
@Cristobal-Hevia a mi entender es el editor el que "le molesta" cuando importas utils, porque el editor no puede leer el contenido de manera transparente, pero este no es un problema para el intérprete de python (quién es el que va ejecutar realmente tu programa, no el editor). 
Segundo, las extensiones le dicen a los programas como el cómo deben interpretar la información dentro del archivo, si tu le cambias la extensión, entonces el programa va a interpretar de mala manera el contenido. Un archivo compilado contiene todo en un lenguaje distinto (a mi entender el contenido está en binario) al normal. Por lo que cambiar la extensión no soluciona tu problema si no que solo engañas al editor, y como viste ahora confundiste al intérprete de python.
Te pido que vuelvas a ponerle la extensión .pyc o que lo borres y lo vuelvas a descargas, y hagas una prueba simple de un programa como este: 
import utils
import dccultivo

print("hola")
a = dccultivo.DCCultivo()
utils.plagas(a)
print("Hola")

Y lo ejecutes por consola (terminal) "python3.11 cosa.py"   (cosa es el nombre que le di a mi archivo de prueba, tu le puedes poner otro nombre), y hay si te sale un error en la consola, lo conversamos para ver como solucionarlo. Si no sale ningún error, entonces está confirmado que es el editor el que tiene problema con el utils y no el programa.

**Comment by Cristobal-Hevia** [comment]
Ahí me funcionó muchas gracias, perdón por la molestia
