### ISSUE TITLE
Ocupar funciones

### ISSUE THREAD

**Issue by Brocoleta** [IIC2233/syllabus#113]
Esta bien si tengo un archivo.py el cual es una funcion la cual recibe a un jugador y hace todo lo que quedo en espera de su turno anterior y lo retorna o esto tendria un descuento ya que no es una clase y no esta modelado de manera OOP?

**Comment by Arcoirisky** [comment]
Hola! 

Puedes tener funciones, clases, parámetros, lo que estimes conveniente en tantos archivos a parte estimes necesario.  No hay ningún problema con eso, sobretodo si te ayuda a modularizar tu programa. Pero también debes tener en cuenta el sentido de modularizar xD 

Tener muchas cosas (clases, objetos, funciones, etc), aunque sean todas de un tipo en particular (clases por ejemplo) pero sin mucha relación entre si (cómo funcionan, lo que manejan, etc), te debería dar para pensar en que si existe una mejor forma de ir agrupándolas entre tus módulos .py  

Espero que al menos te hubiera guiado un poco en decidir 😅

Ánimo!
