### ISSUE TITLE
Duda Orders sin dueño 

### ISSUE THREAD

**Issue by augustoas** [IIC2233/Syllabus#113]
Hola ! En un comienzo cada usuario tiene distintas orders y se pueden ver en el archivo users.csv en sus orders:list. Mi duda es que hay orders en el archivo orders.csv que no coinciden con ser de ningún user. Por ejemplo la order con id número 4 no hay nadie que en el archivo users la tenga en sus orders:list. Qué pasa con estas orders? no me queda claro a quien pertenecen o qué se hace con ellas. Saludos.

**Comment by Hernan4444** [comment]
#55
