### ISSUE TITLE
Problemas con `.gitignore`

### ISSUE THREAD

**Issue by nicolaspoli** [IIC2233/syllabus#113]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! llevo una buena cantidad de intentos y búsquedas y no logro entender porque mi .gitignore no funciona. Mi archivo tiene el siguiente texto:

# --------------------------------------------
# Python
# --------------------------------------------

# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

*.idea
*.DS_STORE
 
#TAREA 0
/Tareas/T0/*.pdf
/Tareas/T0/*.csv
/Tareas/T0/.vscode
/Tareas/T0/*.pdf

pero nada de lo que yo he agregado deja de aparecer. Por que puede ser?

Gracias de antemano

**Comment by nicolaspoli** [comment]
Olvidé ver el preview y se ve raro jajaja las primeras lineas no se ve pero es * .csv y * .pdf

**Comment by cristobalnic** [comment]
Hola @nicolaspoli!

Lo que estás intentando hacer es que se ignoren todos los archivos del tipo que señalas?
En ese caso debes poner un asterisco (*) previo a la extensión del archivo, así `*.pdf` para indicar que quieres ignorar todos los .pdf

Por lo que veo se me ocurre que: 
1. Las rutas de los archivos que estás señalando podrían estar con el caracter erróneo como separador (/, \).
2. La ubicación en que creaste el archivo puede no ser la correcta, el .gitignore debe estar en el mismo directorio que las carpetas que estás tratando de ignorar.
3. Si está en la ubicación correcta, intenta escribir las rutas sin el primer slash aunque creo que esto no debe afectar en realidad (Ej: Tareas/T0/*.pdf)
4. El archivo puede no estar guardado como el tipo .gitignore y podría estar como un .txt por ejemplo.

Como acotación, lo ideal sería que creases un .gitignore nuevo para cada tarea, y que lo ubicases en su carpeta respectiva. Esto te facilitaría también el tema de las rutas a escribir.
(Por supuesto para esta no se evalúa su uso pero es bueno que te acostumbres, porque después se pedirá).

Avísame si te funciona!

**Comment by nicolaspoli** [comment]
revisé todo lo que me dices y lo cambie a la carpeta de la tarea, sigue sin funcionar :c tiene algo que ver que ya estaban los archivos en el repo cuando hice por primera vez el gitignore?

**Comment by cristobalnic** [comment]
Por lo que puedo ver en tu repo, efectivamente ya tienes todos los archivos subidos, por lo que tendrás que eliminarlos primero! Para ello puedes usar el comando: `git rm -rf --cached .`

Este comando eliminará todos los archivos que estén en el repositorio remoto (El punto al final indica que quieres remover todos los archivos, pero también puedes hacerlo uno por uno así: `git rm -rf --cached archivo1`  `git rm -rf --cached archivo2` ... etc).

Luego tienes que corregir el `gitignore` que tienes subido, porque debe llamarse `.gitignore` (el punto es importante porque es la extensión del archivo).

Para verificar que todo esté bien, te recomiendo hacer un `git status`, para que puedas revisar que te aparezcan en rojo todos los archivos que piensas subir (y que no te aparezcan los que estás ignorando).

Ahora con el archivo ya corregido, que me parece que está ubicado correctamente, lo que lo único que quedaría es hacer `git add .` para añadir todos los archivos (al igual que anteriormente el punto es para añadir todos los disponibles, o también puedes ir uno por uno), luego `git commit` y finalmente `git push`. 

Dime si ahora te funciona! :)

**Comment by nicolaspoli** [comment]
Buenisima! Funcionó! Tuve que recrear la carpeta en el repositorio porque se borró al hacer el rm, pero lo importante es que ahora funciona :)

Muchas gracias :D

**Comment by namadatzis** [comment]
Hola @cristobalnic,

Tengo un problema similar, qué es lo correcto escribir acá o hacer una nueva issue referenciando tu respuesta?

Subí todos los .csv y estaba probando .gitignore pero ya había subido los archivos. Probé los códigos que indicas  borré todo, pero al volver a subir igual se suben los .csv, en mi pc el archivo es .gitignore pero en git aparece como .gitignore.txt y no entiendo bien cómo arreglarlo, gracias!

**Comment by cristobalnic** [comment]
Hola @namadatzis! En este caso está bien que preguntes por acá!

Lo que pasa es que tu archivo está guardado con la extensión .txt y no con .gitignore como debiese ser, es decir, el tuyo es un archivo de texto cuyo nombre es `.gitignore` y cuya extensión es `.txt`.

Me imagino que al no saber que en git aparece como .gitignore.txt antes de subirlo es porque no estás viendo las extensiones de los archivos en tu computador! Para eso te dejo aquí la forma de dejar visibles las extensiones para todos los archivos:

1) Busca **"Opciones del Explorador de archivos"** en la barra de búsqueda:
![image](https://user-images.githubusercontent.com/48327806/113073909-6c239c00-91a0-11eb-8bd6-6a3f47f4dbb7.png)

2) Al clickear se te abrirá una pestaña, en cuyo menú superior debes ir a la opción **"Ver"**. Ahí debes buscar la casilla con la opción **"Ocultar las extensiones de archivo para tipos de archivo conocidos"** y desmarcarla, para que se muestren las extensiones de todos los archivos:
![image](https://user-images.githubusercontent.com/48327806/113074075-befd5380-91a0-11eb-9424-e509f203cbb5.png)

3) Finalmente, en el mismo cuadro clickeas en **"Aplicar"** para que se guarde la configuración.

Ahora podrás ver que tu `.gitignore` ahora se llamará `.gitignore.txt` y podrás **borrarle la extensión `.txt`**. Ahí es probable que te aparezca una advertencia como esta:
![image](https://user-images.githubusercontent.com/48327806/113074379-58c50080-91a1-11eb-8daf-25aceb492463.png)
Pero le debes dar que sí, no te preocupes que funcionará perfectamente!

Luego de todo esto, el `.gitignore` está listo para ser usado! Tras borrar nuevamente los archivos de la nube (como ya lo hiciste), git debería ignorar los archivos que escribas en él!

Ojalá que esto te ayude a solucionar tu problema!
