### ISSUE TITLE
Cambiar color de fondo o texto en label sin afectar a contenedores

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2233/syllabus#1130]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! Tengo el problema de que al querer designar un color a un jugador y mostrarlo como tal, me ocurre que el diseño del contenedor y la vetana cambian también, esto lo hice en Designer. Leí y se trata de como un efecto "cascada" al usar *setStyleSheet* pero no sé cómo hacer que sólo cambie la label que quiero, si me pueden ayudar con un ejemplo se los agradecería muchísimo.

Saludos!

**Comment by EduardoIllanes** [comment]
Hola @Jamesmoreno21 para evitar ese efecto en "cascada" puede utilizar **QPalette** de Designer para el color de tu ventana (o para cualquier cosa en realidad). Te dejo la [documentación](https://doc.qt.io/qtforpython/PySide2/QtGui/QPalette.html) por si quieres ver mas en profundidad como funciona. Saludos!

**Comment by Jamesmoreno21** [comment]
Hola! Muchas gracias por la respuesta.También encontré otra forma de hacerlo que es haciendo un stylesheet sólo a label, poniendo un marcador, ¿puedo compartirlo por si alguien lo necesita?

**Comment by EduardoIllanes** [comment]
Sii puedes, poniendo el link donde encontraste tu respuesta 🙌

**Comment by Jamesmoreno21** [comment]
Ok! El link es https://forum.qt.io/topic/91500/change-qlabel-background-without-affecting-the-current-style/2, entregan las dos soluciones, con QPalette y SetStyleSheet, yo use la última y dice que si tengo una label llamada Dibujo y quiero cambiar color, letra, o lo que sea, se haría Dibujo.setStylesheet("QLabel#Dibujo{color: ..., font:...};) y con eso se hace un cambio local solo en Dibujo y no en el resto de elementos.
