### ISSUE TITLE
Consulta imagen Mazo

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#1131]
dentro de mi ventana de juego, en el centro de la pantalla se encuentran 2 labels, los cuales corresponden al mazo de donde se sacan cartas, y al pozo, donde se juegan cartas.

Originalmente, ambos parten con la imagen de la carta dada vuelta, aunque el poso es actualizado apenas parte el juego con una carta al azar (o al menos, ese es mi plan, tengo que hacerlo hoy), pero me surge una duda con el otro label, el mazo. 

¿Es necesario que mande su imagen como byte desde el servidor?¿ O este puede partir desde un principio con la imagen puesta?

Ademas, también tengo una imagen de carta, sobre el botón para robar (muy similar a la imagen del enunciado), ¿esta imagen también tiene que obtener su imagen desde el servidor?

**Comment by gatochico** [comment]
Hola!

Como se menciona en la issue #1039 , el servidor es el único con acceso a los sprites de las cartas. Por lo tanto, si quieres usar el sprite con el reverso de una carta en la interfaz, deberás enviar desde el servidor el sprite (o qlabel directamente) de esta y luego ubicarla en los lugares donde desees ponerla.

Éxito!
