### ISSUE TITLE
Error de mac en consola

### ISSUE THREAD

**Issue by RafaelEdwards** [IIC2233/syllabus#1131]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, estoy teniendo este error al intentar ejecutar el script del cliente, no sé si es algo de mi computador en específico o un error de código. (Acabo de empezar a implementar las interfaces gráficas, no sé si será por algo relacionado a esto).

```
2020-11-28 17:32:15.032 Python[32556:643569] unable to obtain configuration from
file:///Library/Preferences/com.apple.ViewBridge.plist due to Error Domain=NSCocoaErrorDomain Code=260 "The file
“com.apple.ViewBridge.plist” couldn’t be opened because there is no such file." UserInfo=
NSFilePath=/Library/Preferences/com.apple.ViewBridge.plist, NSUnderlyingError=0x7f8d52e3f260 {Error
Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```
Busqué en internet y no logré encontrar de que se trata específicamente pero creo que es algo con mi sistema operativo (OS Mojave 10.14.6)

Muchas gracias de antemano.

**Comment by igbasly** [comment]
Hola @RafaelEdwards :smile:

Podrías subir todo lo que tengas a tu repositorio para intentar ejecutarlo, ya que estuve leyendo y el error puede deberse a una falla del mismo sistema que se pudo haber solucionado en una actualización.

Mientras quedó atento a tu respuesta para intentar solucionarlo.:+1:

**Comment by RafaelEdwards** [comment]
Hola @igbasly 

Ya hice el push, avísame cómo te va cuando lo corras.

**Comment by RafaelEdwards** [comment]
Hola @igbasly

Ya hice el push, avísame cómo te va cuando lo corras.

Muchas gracias

**Comment by igbasly** [comment]
@RafaelEdwards, logré ejecutar tu tarea tanto el cliente como el servidor sin problemas :+1:.
Te comento el entorno que utilicé:
- MacOS Catalina 10.15.4
- PyQt5 5.12.3
- Python 3.7.

Mi recomendación frente a esto es primero que intentes re-instalar PyQt o Python si es necesario, con esto mismo te pido que me comentes si para la tarea anterior ya te había sucedido esto o bajo que contexto comenzó a aparecer.
En el último caso te recomendaría actualizar tu sistema operativo, pero esperamos a ver que tal va lo otro 🙌 .

**Comment by RafaelEdwards** [comment]
@igbasly mis versiones de Python y de PyQt5 son las mismas que las que utilizaste, por lo tanto, debería ser el sistema operativo. Sin embargo, seguí avanzando con la tarea y la verdad el código se ejecuta perfectamente, el error sólo aparece cuando se termina la ejecución, por lo que lo dejaré así mientras tanto.

Ahora que lo recuerdo creo que en la T02 recibía el mismo error en consola al terminar la ejecución.

**Comment by igbasly** [comment]
@RafaelEdwards tampoco te recomiendo actualizar el sistema operativo ahora, pero si te invito a reinstalar las librerías, tal vez eso ayude a reparar algunos paquetes perdidos.

Se todas formas, si puedes seguir avanzando así, también es válido, pero ten cuidado con posibles errores que puedan surgir de eso.

Cualquier cosa quedamos atentos a cualquiera otro inconveniente o duda que pueda surgir. Mucho éxito con el estudio!! :muscle:
