### ISSUE TITLE
Instanciar el mapa con PyQt5

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC2233/syllabus#1132]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!, estoy intentando crear la interfaz para el mapa, pero me complica crear los caminos. Hay alguna forma de crear una estructura en PyQt5 que simule un camino con el **angulo** que se nos pide, por favor si podrían guiarme sobre qué estructura podría ocupar se los agradecería mucho. Saludos!

**Comment by matiasmasjuan** [comment]
Hola @SebaHagedorn !

En lo personal, **no conozco** alguna estructura en PyQt5 que pueda simular un camino. Sin embargo, existen formas de poder rotar **Qlabels** a través de **QTransform**, para generar los ángulos que mencionas. Puedes encontrar algunos ejemplos de uso en [este link](https://programtalk.com/python-examples/PyQt5.QtGui.QTransform/).

Recuerda que en la carpeta sprites dadas en el syllabus hay imagenes de caminos rotados que te pueden servir de utilidad, pero no estoy seguro si eso es lo que estás buscando :thinking: .

Saludos! :smile:

**Comment by SebaHagedorn** [comment]
Muchas gracias!
