### ISSUE TITLE
Botones no se apretan

### ISSUE THREAD

**Issue by fedezang** [IIC2233/syllabus#1133]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! tengo un problema a la hora de probar mi interfaz, ya que algunos botones se pueden apretar y otros no me deja, probe poniendo setEnable(True) en los que tenia problema, pero no me funciona.
Quería saber si alguien podría probar abrir en su computador para saber si es un problema del código o del computador.
Y si fuera problema del código, ¿Cómo podría solucionarlo?
Gracias de antemano

**Comment by rodrigobj99** [comment]
Hola @fedezang !
Estuve probando tu código y pude apretar todos los botones. No se si será algo del sistema operativo (lo probe en mac) o si lograste arreglarlo y por eso funciona.

Saludos!

**Comment by denisseleiva** [comment]
Holaa @rodrigobj99 
Estoy teniendo el mismo problema que mi compañero:( El botón para lanzar dados lo cree en QTDesigner y si printeo isEnabled() me dice True, sin embargo es como si fuera estático. Estoy usando Mac.
No sé si podrías ver si es problema de código o qué cosa puede ser uwu

Gracias :3

**Comment by rodrigobj99** [comment]
Hola @denisseleiva 
Probé tu código y el botón lanzar funciona correctamente (se imprime botón funciona y dados en la terminal), quizás es un problema con la versión de PyQt5, ya que una de las versiones mas nuevas justamente producía que los botones no se pudieran apretar en Mac. La issue que trata de eso es la [892](https://github.com/IIC2233/syllabus/issues/892).

Espero te sirva. Saludos!

**Comment by fedezang** [comment]
Hola! Lo logré solucionar.
Después de probar mucho tiempo me di cuenta que por alguna razón en QT Designer (ocupandolo en mac) los botones no funcionan si la altura es menor a 35 px (supongo que pasara lo mismo para el ancho). Cambié el tamaño y ahi empezó a funcionar.

**Comment by denisseleiva** [comment]
jajajjajjaj no puede seeeer @fedezang eso funciona perfecto graciasssss!!!!!!

gracias tb @rodrigobj99 😁
