### ISSUE TITLE
Implementación general de la tarea

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#1134]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!

Tengo un par de dudas con las formas correctas de implementar la tarea y las buenas prácticas para lograrlo.

Lo primero, es que la clase `Cliente` se instancia infinitamente. Esto no lo entiendo. En el `main`, el código se queda pegado cuando se instancia el cliente, si hago un `print(algo)` abajo no se imprime.

Lo segundo, estoy instanciando las ventanas dentro de la clase `Cliente` (en parte debido a lo anterior, ya que el `main` no se puede usar después de que se instancia el cliente). Luego, el manejo de las ventanas lo hago a través de métodos pertenecientes a las ventanas que llamo dentro de `Cliente`. ¿Es muy mala práctica? Porque el uso de señales se ve disminuido. 

En el fondo, mi idea era instanciar el cliente y las ventana en el `main`, y luego ir conectando las señales. Pero me tuve que adaptar debido a que no logro solucionar el problema del `main`.

Muchos saludos.

**Comment by lucasprato** [comment]
Hola @amahns1,

> Lo primero, es que la clase Cliente se instancia infinitamente.

Ojo que no es correcto que un cliente se instancie infinitamente. Un cliente se instancia solo una vez por jugador. Quizás te confundiste con un `while` que sí debe haber en la clase `Cliente` y que siempre debe ser `True` mientras esté conectado. Específicamente, este boolean es necesario para que el cliente pueda estar siempre disponible para recibir información desde el servidor. La ayudantía 11 te puede servir de referente para entender la locación de ese `while`.

> Luego, el manejo de las ventanas lo hago a través de métodos pertenecientes a las ventanas que llamo dentro de Cliente. ¿Es muy mala práctica?

Efectivamente es mala práctica y a pesar de que pueda ser funcional, se te podría descontar puntaje. Esto debido a que no habría una clara modularización entre el frontend y el backend, y no habría uso de señales para conectarlos. Te recomiendo ver a Actividad 5, en donde se usó una interfaz para conectar a través de señales la lógica del backend con las vistas del frontend. Usar el `main` para conectar las señales también es válido.

Éxito en la tarea!

**Comment by amahns1** [comment]
Vale!
Eso sí, no entiendo qué está provocando que el `Cliente` se instancie constantemente. No es que tenga un while antes de instanciarlo, pero el código no pasa de la línea dónde la instancio. No he podido solucionarlo y eso impide conectar las señales apropiadamente.

**Comment by lucasprato** [comment]
Puedes porfa pushear tu repo?

**Comment by amahns1** [comment]
Ya está pusheado. Creo que hace dos días hice push de una versión con el mismo problema.

**Comment by lucasprato** [comment]
@amahns1 vi tu código y te recomiendo que implementes una Interfaz, tal como se hizo en la actividad de Networking. La gracia de hacer una interfaz, es que es el centro de comunicación entre el backend y el frontend, y es en esta clase donde se crean las señales y se conectan entre sí. La gran ventaja es que **puedes instanciar a la interfaz dentro del cliente**, por lo que no tienes el problema de que no el programa "no siga bajando" tras instanciar a un cliente. En la interfaz también se instancian las clases del frontend.

El flujo para trabajar con la interfaz es bastante sencillo. Pongamos de ejemplo imprimir en la ventana el nombre que le asigna el servidor a un jugador.
1. El backend del cliente recibe el nombre del jugador desde el servidor
2. En el backend, se llama a un método de la interfaz, por ejemplo, `mostrar_nombre_jugador`
3. En la interfaz (antes del init), se instancia una señal, por ejemplo, `mostrar_nombre_jugador_signal`. El método `mostrar_nombre_jugador` se encarga de emitir la señal `mostrar_nombre_jugador_signal`.
4. En el init, se conecta la señal `mostrar_nombre_jugador_signal` con el método correspondiente de la ventana.

De esta forma, cuando se llama a `mostrar_nombre_jugador`, este método emitirá una señal llamada `mostrar_nombre_jugador_signal`, la cual se ha conectado en el init con un método específico del frontend, el cual se encarga de visualizar el nombre del jugador en la ventana.

Espero que esto se sea de guía para tu tarea!

**Comment by amahns1** [comment]
Vale muchas gracias!
Definitivamente servirá mucho ya que el código estaba un poco desordenado.
