### ISSUE TITLE
Usar archivos de parametros.py para archivos que no se conecten por internet

### ISSUE THREAD

**Issue by dedmu5** [IIC2233/syllabus#1135]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, ¿Puedo usar archivos del tipo parametros.py para archivos .py que no sean del cliente ni del servidor? Según entendí, el enunciado solo exige que sean archivos .json en el caso que los parametros sean leídos por el servidor o el cliente.

**Comment by matiasmasjuan** [comment]
Hola @dedmu5 !

**No es posible** usar archivos del tipo **parametros.py**, **deben** ser  **parametros.json**. De todas formas, no entiendo a que te refieres con parámetros que no son del cliente ni del servidor. Recuerda que debes modelar tu tarea de tal forma en que el **cliente** se encuentre **completamente separado** del servidor. En base a eso, no es posible crear parámetros que no sean del cliente ni del servidor. Los parámetros **deben** estar **si o si** en alguno de los dos, pero no pueden estar ni en ambos o en ninguno. Por lo tanto, no es posible crear parámetros que sean accesibles tanto por el cliente y el servidor a la vez, ya que **no** se estaría **respetando** la **separación  cliente-servidor**.

Espero haber respondido a tu pregunta, y mucho éxito con la tarea! :smile:

**Comment by dedmu5** [comment]
> Hola @dedmu5 !
> 
> **No es posible** usar archivos del tipo **parametros.py**, **deben** ser **parametros.json**. De todas formas, no entiendo a que te refieres con parámetros que no son del cliente ni del servidor. Recuerda que debes modelar tu tarea de tal forma en que el **cliente** se encuentre **completamente separado** del servidor. En base a eso, no es posible crear parámetros que no sean del cliente ni del servidor. Los parámetros **deben** estar **si o si** en alguno de los dos, pero no pueden estar ni en ambos o en ninguno. Por lo tanto, no es posible crear parámetros que sean accesibles tanto por el cliente y el servidor a la vez, ya que **no** se estaría **respetando** la **separación cliente-servidor**.
> 
> Espero haber respondido a tu pregunta, y mucho éxito con la tarea! 😄

Hola, me refiero a esto:
![image](https://user-images.githubusercontent.com/65060602/100527276-d5be7a00-31af-11eb-9206-7d9520ac2bcd.png)
¿Esto que dice aquí implica que no puedo crear más archivos de parámetros? Porque había entendido que esos dos archivos .json son para los dos archivos que se conectan a internet (que tienen importado `socket`), por lo que, por ejemplo si tengo un archivo en mi frontend `sala_de_juego.py` puedo crear un archivo `parametros_sala_de_juego.py`. ¿Estoy entendiéndolo mal entonces?

**Comment by matiasmasjuan** [comment]
Tal como dice la misma sección del enunciado: "*a lo largo del enunciado se han ido presentando distintos números y palabras en **ESTE_FORMATO***". Todos estos párametros **deben** ir en **parametros.json**. Por lo tanto, los archivos ```json``` **no son solo** para parametros de conectividad, sino que también debe almacenar parámetros del programa. En tu ejemplo, si necesitas crear un parámetro para la ```sala_de_juego```, debe ir en alguno de los ```parametros.json```.

Espero que ahí se haya entendido un poco mejor :sweat_smile: .

Saludos!

**Comment by dedmu5** [comment]
> Tal como dice la misma sección del enunciado: "_a lo largo del enunciado se han ido presentando distintos números y palabras en **ESTE_FORMATO**_". Todos estos párametros **deben** ir en **parametros.json**. Por lo tanto, los archivos `json` **no son solo** para parametros de conectividad, sino que también debe almacenar parámetros del programa. En tu ejemplo, si necesitas crear un parámetro para la `sala_de_juego`, debe ir en alguno de los `parametros.json`.
> 
> Espero que ahí se haya entendido un poco mejor 😅 .
> 
> Saludos!

Clarito como el agua, pero me falto que me confirmaras si se pueden crear más de dos archivos de parámetros con extensión `.json` a lo largo de la tarea. 😀

**Comment by matiasmasjuan** [comment]
Perdon :sweat_smile: . No, todos los parámetros deben ir juntos, por lo que **no es posible** crear dos archivos ```json``` que almacenen parametros. Si te acomoda, puedes agrupar los parametros por sección, de esta forma estarán mas ordenados en el archivo ```parametros.json```.

Saludos!

**Comment by denisseleiva** [comment]
Hola! @matiasmasjuan con respecto a lo de los archivos json, en la parte 7.1.1 yo entiendo que hay dos archivos parametros.py, uno en la carpeta del cliente y otra en la carpeta del servidor, ¿Esto no es así?

**Comment by matiasmasjuan** [comment]
Hola @denisseleiva !

Casi, **deben** ser dos archivos **parametros.json**, uno en la carpeta cliente y otra en la carpeta del servidor como tu bien dices. **No parametros.py**.

Saludos! :smile:
