### ISSUE TITLE
Parametro Cantidad de Cartas Iniciales

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1135]
Hola!En una issue vi que podemos definir cuantas cartas iniciales serian y de ser preferible colocarlas como parámetro , sin embargo este parametro iria en solo en la carpeta servidor o también podría ir en la carpeta de clientes?Más específicamente en parametro.json

**Comment by KnowYourselves** [comment]
Hola @RonaldoSosa!

Respondo tu pregunta con otra pregunta: ¿Quien es el encargado de decidir cuantas cartas se van a entregar inicialmente?, considerando lo anterior, de tener el parámetro en el cliente, ¿Lo utilizarías?

Éxito!

**Comment by RonaldoSosa** [comment]
Respondiendo a la pregunta , sería el servidor !!!Vale ya entendí lo estaba planteando de manera incorrecta jsjssj , graciass! :)
