### ISSUE TITLE
Sprite ladrón

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#1136]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!

¿El sprite del ladrón lo tenemos que escoger nosotros?

Muchos saludos.

**Comment by matiasmasjuan** [comment]
Hola @amahns1 !

Según en el enunciado, en la parte del **BONUS: 8.1**:

![ladron](https://user-images.githubusercontent.com/48495638/100527666-11a70e80-31b3-11eb-8ff0-a688b0944827.png)

Por lo tanto, si deseas implementar una **sprite** para esto, lo puedes hacer, pero tendrias que escogerlo tu e incluirlo como un sprite adicional. Ahora bien, **no** es **obligatorio** hacer una sprite para el ladrón. Puedes hacerlo de la forma que estimes conveniente, siempre y cuando sea reconocible y no oculte el número del hexágono.

Saludos! :smile:
