### ISSUE TITLE
metodo generar_hexagono

### ISSUE THREAD

**Issue by PedroFuenzalida** [IIC2233/syllabus#1137]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Que es lo que retorna el método generar_hexagono que nos dan? sale que retorna un generador, pero le doy como atributo las dimensiones del grafo ([5,2]) y al recorrer el generador y printear, primero printea un diccionario de todos los nodos y después 6 posiciones, siendo que debería darme 7.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by gatochico** [comment]
Hola @PedroFuenzalida !

Para hacer la grilla, no deberías tener que usar el método `generar_hexagono`, sino que unicamente el método `generar_grilla(dimensiones, padding_x, padding_y)` . A este último, Dándole como parámetro [5,2] y los dos _padding_ horizontal y vertical que quieras usar para trasladar la grilla, debería únicamente retornarte un **diccionario de todos los nodos** con el formato `"ID": (X, Y)`, lo que te indicará que el nodo con el id ID, debería ir ubicado en la posición (X,Y) de la interfaz para poder formar la grilla. Algo así:

```
import generador_grilla

grilla = generador_grilla.GeneradorGrillaHexagonal(135)
nodos = grilla.generar_grilla([5,2], 30, 30)
```
Y luego solo trabajar con el diccionario de nodos para ubicar tus labels.

Este método usa internamente el método `generar_hexagono `para ir formando la grilla, por lo que en teoría no deberías interactuar de forma directa con este último, cuya función es obtener una posición y generar un único hexagono en esta.

Como último, si quieres trabajar con el archivo  `generador_grilla.py` te recomiendo que hagas pull del Syllabus y uses la última versión de este, que fue modificada tras encontrar un error en la issue #1082 .

Saludos y quedo atenta a cualquier duda!

**Comment by PedroFuenzalida** [comment]
Ahh ya perfecto. Muchas gracias!
