### ISSUE TITLE
Cliente se cae

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#1137]
Hola, se que no puedo compartir codigo así que no se muy bien como me podrían ayudar con esta duda. El tema es que al tener un cliente instanciado y apretar "ingresar" el usuario logra ingresar, pero cuando tengo 2 o mas clientes de estos en adelante al apretar "ingresar" ya no funciona y se cae el cliente, me deja de aparecer su ventana de inicio y no se me abre su sala de espera.

![image](https://user-images.githubusercontent.com/62180259/85796159-768fa180-b707-11ea-9a4c-4e38a0171811.png)

**Comment by gatochico** [comment]
Hola! Lograste solucionarlo?

Si no es así, podrías subir tu código actual a tu repositorio y así puedo mirarlo y ayudarte a ver el error.

**Comment by dsepulveda3** [comment]
Hola! Noo no he logrado solucionarlo :(. Acabo de hacer push. Probando cache que adicionalmente a lo que te digo me pase que si desconecto a un cliente y vuelvo a conectar a otro se me cae también.  Quedo atento a tu respuesta. Muchas gracias

**Comment by gatochico** [comment]
(lamento la demora :c )

Corrí tu código, y solo pude replicar el error cuando desconecto a un cliente (sale el error de tu pantallazo en el server). Sin embargo, si luego corro otra instancia del cliente si me deja entrar a la sala y el server sigue andando: ¿Eso es lo que ocure cuando lo pruebas en tu computador? Si no es así, dame los pasos exactos a seguir para replicar el error!

Con respecto al **connectionResetError**: este error ocurre cuando se pierde la conexion por el lado del cliente de forma inesperada (sea, el cliente o se cae o lo cortas a proposito, de forma que el programa deja de ejecutarse), y el server tenía el socket del cliente guardado, por lo que sigue escuchando y potencialmente enviandole información a un socket de algo que ya no está. Por lo tanto, deberías desde el servidor cerrar la conexion con este cliente caido en específico y eliminarlo de los clientes para que el server siga funcionando correctamente. Algunas ideas para manejarlo:
- Que el servidor maneje este error, ya que sabes exactamente en qué casos ocurre (y ya viste durante el curso cómo manejar errores, en la semana 5)
- Por el lado del cliente, hacer que el programa al caerse, o antes de que se cierre si lo cerramos a propósito, le indique esto al servidor por mensajes, para que el servidor pueda manejar apropiadamente el caso (también es util la semana 5 para esto).

Trata de solucionar tu problema con las ideas de arriba, de forma que el servidor elimine cualquier socket caido. Si aún así no te deja avanzar, o tienes alguna otra duda, comenta abajo!

**Comment by mmunoz12** [comment]
Hola! tengo una duda con respecto a este tema. Me pasa que mi cliente se cae cada vez que apreto el boton ingresar, por el error connectionResetError.  He revisado bien y no entiendo el porqué de esto. ¿Hay alguna forma de evitar que el cliente se caiga por esta razón?. No sé si queda claro o avisame si es mejor que abra una nueva issue. Cualquier ayuda me sirve :(

**Comment by gatochico** [comment]
Hola @mmunoz12! Lograste arreglarlo? Bajé tu código actual y tu programa si me dejó conectar 4 clientes sin problemas

**Comment by dsepulveda3** [comment]
Perfecto. @gatochico me queda claro conceptualmente como solucionar el error por desconexion del cliente. 
Lo que te nombro al prinipio (razón por la que abri el issue), es lo siguiente:
Si pruebas corriendo el servidor y después abriendo 2 clientes (main) funciona. El problema es al ingresar el nombre de usuario (en ambos clientes) y luego ingresando (apretando boton "entrar"). El primer cliente con el que intentes "entrar" funcionará, el segundo cliente con el que intentes "entar" se caera. Puedes probar esto, aun no logro entender que estoy haciendo mal. Realmente intente durante la mañana antes de escribirte ahora.

**Comment by gatochico** [comment]
@dsepulveda3 En tu repo actual tienes en el archivo `sala_espera.py`, las comparaciones de largo de esta forma:
`elif len(clientes == 2):`
mientras que deberían ser así:
`elif len(clientes) == 2:`

Será eso? Por lo menos haciendo ese cambio en todos los ifs mal escritos las dos ventanas del cliente se me quedan abiertas funcionando.

**Comment by dsepulveda3** [comment]
@gatochico  Ohh que pastel, efectivamente era eso. Como me tiraba un error de servidor solo me fije en este archivo inumerables veces jajaja. De la experiencia se aprende, error de novato. Muchas gracias !!

**Comment by mmunoz12** [comment]
@gatochico si! Habia logrado arreglarlo😅 me tiraba a error por algo que estab mandando mal pero el cliente no me avisaba que era eso. Muchas gracias igual!
