### ISSUE TITLE
Almacenar en memoria el reverso de la carta

### ISSUE THREAD

**Issue by benjavicente** [IIC2233/syllabus#1138]
Vi las issues #1039, #1129, #1131 y #1134 y no me quedó muy claro cómo se puede manejar la imagen de la carta de reverso.

Estaba pensando **mandar la carta una vez y almacenarla (sin guardar el archivo)**, de modo que no tenga que mandar los bytes de esta cada turno para ir mostrando las cartas que poseen los demás jugadores. ¿Se puede hacer esto?

Y si es que se puede, ¿puedo mandar esta carta con otro _id_ al de las cartas donde se muestra el color y el número?
Se especifica que se debe **mandar con un formato específico al robar cartas y al actualizar el pozo**; y por lo que entiendo, en ambos casos se muestra el **tipo y color** de la carta, por lo que me gustaría separar el _id_ de una carta normal y el reverso, ya que se utilizan en distintos casos.

Gracias de antemano!

**Comment by szabala** [comment]
Hola! No tienes que enviar el reverso de la carta en cada turno, puedes enviarlo una vez al inicio de la partida. Esto ya que es necesario cargar los reversos de las cartas en cada turno, y son siempre los mismos (:eye: con el bonus). Esto **NO** aplica para las imágenes de las cartas.

No hay problema con que asignes un nuevo _id_ para enviar el reverso, recuerda explicarlo en tu README!

**Comment by benjavicente** [comment]
Ya perfecto! Si había visto la parte del bonus, prefiero dejarlo de lado por ahora :sweat_smile:
Gracias!
