### ISSUE TITLE
Puedo mover los archivos entregados a la carpeta Cliente?

### ISSUE THREAD

**Issue by TMagini** [IIC2233/syllabus#1138]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Puedo mover los archivos por ejemplo, generador_grilla.py o generador_de_cartas.py a mi carpeta `client`, si es que no se puede, como puedo llamar a un archivo fuera de mi carpeta cliente?

```
T03
├── client
│   ├── sala_de_juego.py
│
├──generador_grilla.py
```

Me refiero a como importo a sala_de_juego.py el archivo generador_grilla.py en el caso de no poder mover el archivo.

**Comment by Mjtala** [comment]
Hola @TMagini, el generador_de_cartas pertenece a la lógica del juego por lo que debería ir dentro del servidor. Por otro lado, el generador de grilla podría ir en cliente pero recuerda que las dimensiones las obtienes de grafo.json que debería estar en el servidor, por lo que si dejas el generador de grilla en cliente tienes que mandarle las dimensiones desde el servidor. 
Ojalá te sirva!
