### ISSUE TITLE
Importar desde un directorio padre

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#1139]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!

Buscando en internet no encontré una manera de hacer un import relativo desde un directorio padre. Encontré que si desde`/T03/cliente/main.py` quiero importar la `clase A` de `T03/grilla.py`, en teoría `from ..grilla.py import A` debería funcionar, pero resulta en el error: `attempted relative import with no known parent package.`

¿Cuál es la manera correcta de importar un módulo desde un directorio padre?

Muchos saludos.

**Comment by lucasprato** [comment]
Hola @amahns1 (de nuevo), jajaja

En la issue [#1138](https://github.com/IIC2233/syllabus/issues/1138) se habla algo parecido. Se puede posicionar a `grilla.py` dentro de la carpeta `cliente`, pero debes tener en cuenta de que tendrán que realizar algunas comunicaciones extra con el servidor para obtener información de relevancia en `parametros.json` del servidor.

Saludos!
