### ISSUE TITLE
Cargando imagenes en Front-End

### ISSUE THREAD

**Issue by milosoria** [IIC2233/syllabus#1139]
Hola! Estoy teniendo problemas al cargar las imagenes en el front end una vez enviadas desde el servidor. Estoy ocupando el método loadFromData pero solo me está retornando True, lo cual significa que fue cargado exitosamente el pixmap, pero no me esta retornando el pixmap cargado :(
No encontré nada sobre este problema en internet.
De antemano, gracias!

**Comment by furcelay** [comment]
Hola!
Debes crear primero el pixmap y luego usar el método `loadFromData`, que retorna `True` si se cargó correctamente, por ejemplo:
```python
pixmap = QPixmap()
pixmap.loadFromData(imagen, 'png')
```

**Comment by matiasmasjuan** [comment]
Hola @milosoria !

Tal como dice @furcelay, el **método** ```loadFromData``` es un **método** de ***QPixmap*** que "*carga*" la imagen al ***QPixmap*** y además de retorna ```True``` o ```False``` si es que fue posible "*cargarlo*".

En el ejemplo anterior, se debe definir el ```pixmap``` como una instancia de ***QPixmap***, aplicándole el ***método*** ```loadFromData```. Cabe destacar que ```imagen``` es un ```bytearray()``` con los ```bytes``` de la imagen que se quiere mostrar. Posterior a eso, es posible aplicar el **método** ```setPixmap(pixmap)``` a algún ***QLabel***.

Saludos y mucho éxito con la tarea! 😄

**Comment by BelenSilva1204** [comment]
Holaa, mi imagen no se esta cargando ya que me retorna False, la imagen es un _bytearray_ con los _bytes_ y estoy cargándola en el servidor con base64 no sé si eso influye en algo?:(

**Comment by matiasmasjuan** [comment]
Hola @BelenSilva1204 !

El mismo ejemplo se puede hacer si estas utilizando ***Base64*** para pasar la imagen a *string*. Sin embargo, creo que el problema que puede estar ocurriendo es que quizás no estes aplicando los métodos ```base64.encodestring(archivo)``` y ```base64.decodestring()``` correctamente al momento de abrir la imagen en el servidor y luego cargar la imagen en el cliente respectivamente.

Avisame como te va! y mucho éxito con la tarea!

**Comment by BelenSilva1204** [comment]
Ahora me retorna True, pero me aparece este error 'NoneType' object has no attribute 'scaled' lo que indicaría que igual no está llegando bien la imagen;;

**Comment by matiasmasjuan** [comment]
Si retorna ```True``` quiere decir que se está cargando correctamente el ```bytearray()``` (imagen) en el ***QPixmap***. Sin embargo, el error que me señalas se debe a algo externo. Recuerda que los métodos ```scaled, setScaledContents(True), setGeometry```, etc, son **métodos** de **QLabel** que debes aplicarlos en el Front-end. Intenta revisar tu código añadiendo ```prints()``` para intentar encontrar el momento en que se produce un error.
En caso de seguir con el problema, me avisas!

Saludos 😄

**Comment by BelenSilva1204** [comment]
¡Muchísimas gracias! Pude solucionarlo :D
