### ISSUE TITLE
Errores encontrados en código base de ejerc. prop. 4.2 (Progragotchis)

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#114]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola, me parece haber encontrado 2 errores en el código base de este ejercicio:

1) Al código le faltó en la definición de los atributos de la super clase "Progragotchi" pedir el parámetro "hambre", para poder definir el atributo "hambre" de los objetos de las subclases respectivas. 

    Ocurre lo mismo con los parámetros que pide el método \__init__ de las subclases "Tamaprogra" y "DCGotchi", no así al usar el \__init__ de la super clase para setear sus atributos. 

2) Al correr el código para poner a prueba la modelación, arroja los 10 primeros elementos de la lista "progragotchis", que son los de menor valor (en mi caso por lo menos) y no los 10 últimos de mayor valor. No estoy seguro si me pasó esto por definir mal el método \__gt__ , resultando en un ordenamiento invertido de los elementos de la lista al ejecutarse "progragotchis.sort()"

**Comment by tqmbanados** [comment]
Hola! Sobre lo primero, tienes toda la razón, hay un pequeño error en el código base. Gracias por hacerlo notar! 
Sobre lo segundo, el método ```sort()``` normalmente ordena de menor a mayor. Entonces, para realizar de manera correcta el ejercicio tendrías que agregar un argumento al llamado del método ```sort()```, o bien, completar ```__gt__()``` de manera inversa, lo que no es muy recomendable. De todas formas, lo consideraría un error del ejercicio, pues el código dado no incluye el argumento ```reverse``` de sort. 

[Aquí](https://www.w3schools.com/python/ref_list_sort.asp) puedes leer sobre ```sort()``` y sus funcionalidades, es super útil para montones de cosas :)
