### ISSUE TITLE
Tipo de archivo de los reportes

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#114]
Hola!

En el enunciado dice que el nombre de cada incendio debe ser "id_incendio_nombre_criterio.txt".

1. Pregunta solo para estar seguro. Es "id_incendio" más "nombre_criterio", verdad? 

2. Podemos usar csv en vez de txt? De esta manera nuestros archivos se ven mas ordenados y bonitos. 😄 

Saludos!

**Comment by Hernan4444** [comment]
@akaminetzkyp Si y si :)
Saludos!!

**Comment by akaminetzkyp** [comment]
Gracias Hernán!
