### ISSUE TITLE
Formato fecha posts

### ISSUE THREAD

**Issue by jonanortizvega** [IIC2233/syllabus#114]
Hola, en el enunciado sale que es yy/mm/dd, eso significa que debo usar 20/03/18 y no 2020/03/18?
Pregunté en el issue del mismo título... pero nadie me respondió :'(

**Comment by gatochico** [comment]
Hola! Utiliza `2020/03/18` , ya que es el que aparece en los csv y así se mantiene el formato consistente en todas partes. Lamentamos la tardanza :(
