### ISSUE TITLE
pregunta herencia y init

### ISSUE THREAD

**Issue by totichi** [IIC2233/syllabus#114]
¿es recomendable/buena practica en vez de heredar una superclase, recibir en un init esa misma clase y ocuparla como atributo?
la duda surge de que tengo clase A,B y C. Todas estas últimas heredan de una superclase Z.
Además, tengo una clase W que hereda de Z, pero necesito heredar de una de las clases a,b o c y no se cual de las 3 será, de ahí que quiero crear la clase W sin que herede nada, pero que tenga como uno de los parametros inicializadores una de estas clases A,B O C.
gracias de antemano

**Comment by Arcoirisky** [comment]
Ten cuidado en la forma en que quieres modelar tu problema. Al agregarla en el init para convertirla en un atributo de tu clase W no estas haciendo una relación equivalente a la herencia. 

Quizás debas darle un par de vueltas a tus clases a,b y c para saber cuál de ellas es la que necesitas para heredar. En el peor de los casos puedes revisar de nuevo tus relaciones de la entrega de avance o los comentarios que se subieron de la misma. 

Así podrás darte una idea de lo que puedes hacer :D Porque, repito, más que recomendable o buena práctica, puede que no estés haciendo las relaciones que necesitas ó el cómo funciona la herencia a comparación de la agregación y composición.
