### ISSUE TITLE
Duda Menú de Inicio funcionalidad regar plantas

### ISSUE THREAD

**Issue by Igufu** [IIC2233/Syllabus#114]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Saludos!, tengo una duda respecto al Menú de Inicio, específicamente la opción de regar. ya que se recibe un input() y con este se llama a la función `buscar_y_regar` la cual recibe las coordenadas con formato de lista. Mi pregunta es cuál es el formato de ese input, ya que según el enunciado siempre será escrito de forma correcta. Pero no dice si será `[X, Y]`, `X, Y`, `XY`, etc.

el input será con un formato específico o lo decidiremos nosotros?, también quiero preguntar si se puede usar variantes de input como `int(input())` o `list(input())`. 

Otra duda muy corta es si deberíamos preocuparnos del comando `if __name__ == '__main__' ` para la ejecución.

Gracias!

**Comment by FernandoTFH** [comment]
1.- No está especificado, queda a tu criterio, el cómo lo recibes el input, pero has un print indicando como debe ser el input (recuerda que tus input deben ser a prueba de error a la hora de recibirlo).
2.- Es materia de introducción a la programación el usar el int(input()), str(input(),..., etc, por lo que sí puedes usarlo.
3.- Es una buena práctica, es mas bonito y te puede ser útil a futuro, pero no es necesario, ni obligatorio, por lo menos en esta tarea.
