### ISSUE TITLE
Aumento de soldados de planetas no conquistados

### ISSUE THREAD

**Issue by felipe8797** [IIC2233/Syllabus#114]
Tengo entendido que cuando a un planeta no conquistado se le puede cambiar el numero de soldados vía "Modificar una galaxia". No obstante, esto no me hace sentido, ya que supongo que cuando uno crea un planeta (de la forma que sea) este no tendrá creado su cuartel. Como funciona esto ? Por otra parte, en la guía se menciona que al crear una galaxia, sus planetas parten con un 75% de su población. Esto ocurre (en especial con magos y soldados) independientemente de que no tengan creado su cuartel?

**Comment by naquiroz** [comment]
Tengo la misma duda de la creacion de soldados!

**Comment by ptflores1** [comment]
Hola ! 
@felipe8797  lee #25 
Lo que dice @Pipelao es cierto solo que hay que tener ojo con algo. Antes de comenzar el modo "jugar en la galaxia" puedes modificar las galaxias pero luego de haber entrado a  "jugar en la galaxia" puedes salir para volver a modificarlas, lo que no puede pasar es que jugando con la galaxia se den opciones de modificarla. Espero que haya quedado claro.
Saludos !
