### ISSUE TITLE
Aplicación de comisión en usuarios del mercado

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233/Syllabus#114]
Hola, tengo una duda, dada la comisión del mercado cuando ocurre un match el "descuento" por comisión solo se le realiza a la moneda que cada usuario recibe cierto? No es que esté aplicado el descuento en las monedas que los usuarios entregan (que haría que pagaran menos de lo que les salió)

**Comment by nebil** [comment]
Sí, al producirse un _match_, la comisión asociada al mercado se aplica **únicamente** en el pago recibido por cada usuario, sin importar si es que este monto proviene desde un _ask_ o desde un _bid_.

**Comment by gabrielpinkman** [comment]
Gracias !

**Comment by cfernandez9** [comment]
y al enviar dinero de un usuario a otro, la comisión solo se cobra una vez o no?? Si u1 envía 100.000 DCC a u2, u2 solo recibe 95.000 DCC???

**Comment by AngelMatias** [comment]
O sea si hago un match de entregar 20.000 pesos Chilenos a 40 BItcoin, la tasa (por ejemplo 40%), se le aplica el descuento al comprador por 40*0.4 Bitcoin y al vendedor por 20.000*0.4 ?

**Comment by iqacevedo** [comment]
@cfernandez9 asi es.
@AngelMatias es tal como dices.

Saludos !

**Comment by cfernandez9** [comment]
@iqacevedo muchas gracias!!!
