### ISSUE TITLE
Duda uso libreria sys.path

### ISSUE THREAD

**Issue by armas01** [IIC2233/Syllabus#114]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! entiendo que se puede utilizar sys.exit para salir, pero puedo utilizar sys.path para acceder de una carpeta a otra?

Me explico, si tengo esto
T1/Menu/Archivo.py
T1/Funcion/Archivo2.py

si quiero que Archivo.py importe Archivo2.py, necesito utilizar sys.path según yo, si no, cual es la mejor forma de hacerlo???

Muchas gracias de antemano y dejo el link de stackoverflow que me guió a esto. https://stackoverflow.com/questions/4383571/importing-files-from-different-folder

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Sancauid** [comment]
Hola @armas01! Para importar el archivo2.py puedes poner:
import Funcion.archivo2 en el archivo T1/Menu/archivo.py
Esto porque Funcion/archivo2 es el path relativo desde el directorio raiz que sería T1.
