### ISSUE TITLE
Problema al importar PiezaExplosiva no reconoce el método

### ISSUE THREAD

**Issue by Matias449** [IIC2233/Syllabus#114]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Al momento de estar haciendo la property de piezas explosivas invalidas, estoy instanciando las piezas en la clase PiezaExplosiva, para esto la importo del archivo correspondiente, pero al momento de intentar usar el método verificar alcance, la terminal arroja este error:

'PiezaExplosiva' object has no attribute 'verifcar_alcance'

Ya verifique que no sea problema de identacion ni typo, y al correr el test exclusivo para la clase, pasa todos los tests

**Comment by Segismundios** [comment]
Le estás poniendo el () al final? en verificar_alcance()

**Comment by Matias449** [comment]
jsadhjhds si era eso, gracias!!
