### ISSUE TITLE
Duda Consumir de entidad bebestibles

### ISSUE THREAD

**Issue by nkantorn** [IIC2233/Syllabus#114]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo dos dudas sobre esta sección:

(1) No entiendo a que se refiere con que "todos los bebestibles recuperarán un valor de energía aleatorio". ¿Significa que cada jugador que consuma un bebestible recuperará energía dentro de un rango aleatorio?

(2) ¿Además de manipular el nivel de energía aleatorio debo informarlo en consola junto con cualquier otro cambio que se genere?

¡Muchas gracias!

**Comment by Gsalinas1506** [comment]
Hola!
Te respondo por orden:

(1) Al consumir un bebestible se recupera un valor de energía aleatorio dentro del rango [MIN_ENERGIA_DISPONIBLE, `MAX_ENERGIA_DISPONIBLE` ], por lo que el rango no es del todo aleatorio. Esos parámetros debes definirlos tú en `parámetros.py`. Por ejemplo, si ambos parámetros se definen como 5 y 9 respectivamente, tras cada consumo de bebestibles debería recuperarse, de forma aleatoria, 5, 6, 7 8 o 9 puntos de energía.

(2) **SI**. Tras consumir un bebestible se debe informar en consola todos los cambios a stats del jugador que se hagan.

Espero haberte ayudado :D
Éxito con la Tarea! 🃏 🎲

**Comment by nkantorn** [comment]
Yaaa perfecto muchas gracias!! Todo muy claro
