### ISSUE TITLE
Nodo faltante en grafo.json

### ISSUE THREAD

**Issue by sperezmasri** [IIC2233/syllabus#1140]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el archivo ```grafo.json``` en la lista de nodos vecinos al nodo 18 creo que falta el nodo 23 (en la lista de nodos vecinos del 23 está el 18 así que supongo que debería estar viceversa). No se si esto es un error o lo hicieron a propósito? Gracias de antemano

**Comment by gatochico** [comment]
Hola @sperezmasri !

Efectivamente faltaba esa conexión en el JSON 😓 . Se ha actualizado el archivo `grafo.json` del syllabus para incluir el nodo 23 en la lista de vecinos del nodo 18.

Gracias por hacernos notar este 🐛 y disculpa las molestias!
