### ISSUE TITLE
Consulta envio imagenes

### ISSUE THREAD

**Issue by aipostigo** [IIC2233/syllabus#1140]
Hola! tengo una consulta sobre la distribucion de puntaje y el envio de imagenes, si no se implementa esto y se utilizan imagenes de forma local solamente descontaria de la seccion de "manejo de bytes" de la asignacion de puntaje? o tendria efecto en otras areas tambien?

**Comment by gatochico** [comment]
Hola! (disculpa la demora u.u)

Además del puntaje perdido en _manejo de bytes_, el almacenar imágenes de forma local en el cliente conllevaría un descuento en la sección de roles, en la celda de _**Las responsabilidades del servidor son consistentes con el enunciado**_:
![image](https://user-images.githubusercontent.com/37161120/85912222-df0a7b80-b7f8-11ea-89df-829d5f476f59.png)
Ya que una de las tareas que debería estar haciendo el servidor no está siendo realizada por este.

Además de esta celda y la sección manejo de bytes, no habría otra celda afectada por no mandar las imagenes según el protocolo pedido.

Saludos!
