### ISSUE TITLE
Duda sobre el uso de bytearray

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#1141]
hola! Leyendo el enunciado, logre leer que nos piden usar bytearray, para enviar informacion. Pero queria preguntar si en vez de usar estos, podia usar QByteArray, ya que esta es la forma que e encontrado en internet para realizar lo que quiero hacer.

**Comment by gatochico** [comment]
Hola! Como está permitida la librería `pyqt5` completa, no debería haber problema con que uses cualquiera de sus elementos.
