### ISSUE TITLE
Duda Requisitos para una choza

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#1142]
Para construir una choza **¿deben haber 2 caminos o carreteras de diferencia** ya que en el juego de mesa en el que se baso se necesitan dos carrreteras, pero en este enunciado es solo 2 caminos, sin importar si hay carreteras o no, lo que implicaria que pudieses construir una choza donde tu quieras con tal de que en sus nodos adyacentes no hayan chozas, sin importar las carreteras construidas en los caminos adyacentes

**Comment by Mjtala** [comment]
Hola @totoiii! Tu duda la puedes encontrar en la issue #1119 
Si no te queda claro me avisas!
Éxito con la tarea!!! 🥳
