### ISSUE TITLE
Decirle a cliente si envié una carta para su mano o para el pozo

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#1142]
Hola, quería saber qué tanto puedo modificar el protocolo de envío de cartas. Me explico, se nos pide que las enviemos del tipo _bytearray_ con identificadores 1,2 y 3 para color, tipo e imagen respectivamente. Mi pregunta es si puedo enviar los mismos datos pero con _id_ 5,6 y 7 para indicar que la carta enviada corresponde a una que va en el pozo, y reservar los _id_ 1, 2 y 3 para cartas que van en la mano del jugador. Se hizo una pregunta similar respecto a los _id_ al momento de enviar cartas en la _issue_ #1138, pero no me quedó claro. Gracias!

**Comment by szabala** [comment]
Hola! Si puedes hacerlo 👍 
Esto ya que solo estas creando más _id_ (explicado en la _issue_ #1069) y esto se permite. Solo recuerda explicar los _ids_ que crees en tu README.
Suerte con la tarea 😄

**Comment by BelenSilva1204** [comment]
Holaa, eso quiere decir que es posible enviar un _bytearray_ que contenga el _id_, largo e imagen solamente? sin los datos del color y tipo?

**Comment by szabala** [comment]
Si, notar que esto **solo aplica** para las cartas del pozo.
Suerte con tu tarea!
