### ISSUE TITLE
Problema al comunicar servidor con cliente

### ISSUE THREAD

**Issue by rtrubio** [IIC2233/syllabus#1143]
Hola! estoy teniendo problemas con la comunicación entre el servidor y los clientes cuando llego al total de jugadores por partida. Cuando llego a esto, el servidor me tira el error "ConnectionResetError: [Errno 54] Connection reset by peer" mientras que en cada cliente me tira el error "OSError: [Errno 9] Bad file descriptor". Investigué un poco para saber que significaba cada error pero la verdad es que no entendí que podría ser, así que no se si alguno los conoce y/o sabe por qué podría estar pasando. 
Cualquier tipo de ayuda me sirve, muchas gracias!!

**Comment by igbasly** [comment]
Hola @rtrubio :v:
Es un poco amplio lo que mencionas acerca de tu error, te pediría por favor que subas tus cambios a tu repositorio para poder revisar con detalle que puede estar ocurriendo.
Para contextualizar, el error ocurre cuando el servidor a alcanzado el máximo de clientes conectados, donde intentas conectar uno extra y este no puede con `ConnectionResetError`, pero también los clientes conectados presentan el error `OSError: [Errno 9] Bad file descriptor`.

Quedo atento 😄

**Comment by rtrubio** [comment]
Hola @igbasly ! 
mis últimos cambios los subí ayer al repositorio, después de eso no he podido cambiar nada más. El/Los errores deberían estar en los archivos cliente.py y/o servidor.py.
Muchas gracias por la ayuda!

**Comment by igbasly** [comment]
Ya @rtrubio 🙌 

Después de un gran análisis del código, he podido detectar los principales generadores de problemas. Por temas de plagio y que este es solo un medio de ayuda, intentaré ser lo más claro posible para guiarte en cuanto a cómo debes manejar algunas cosas, pero no puedo responderte a "esto es lo que tienes que hacer".

Comenzando por el servidor, vi que utilizaste el método`listen` de *socket*, por lo cual te recomiendo que leas esta Issue #1110 donde explico en que consiste, además al manejar la aceptación de los clientes recuerda que estás en un ciclo que mantiene "vivo" al *thread* del servidor, por lo cual recomiendo que revises lo que sucede cuando cumples tu máximo de clientes aceptados, ya que una vez que un cliente se desconecte es posible que llegue uno nuevo y el servidor debe aceptarlo por la vacante abierta.
Solo para complementar, considera que estás modelando el servidor dentro de una aplicación de PyQt, por lo tanto, al ser esta un *thread* y al ser el servidor un *thread daemon*, también tienes que considerar cuando se cierra el servidor (el *socket*), ya que si bien el *thread* del servidor puede acabar su funcionamiento, si el *socket* no se cierra apropiadamente seguirá funcionando junto a los *threads* de los clientes, permitiendo el envío y recepción de información.

Por otro lado en el cliente, el problema está en que se genera el error `OSError: [Errno 9] Bad file descriptor`, el cual es un indicio de que el *socket* no está conectado a el servidor (problema del cliente, no que el servidor se haya cerrado), para resolverlo te recomiendo que revises el método `escuchar_servidor` y como sería una secuencia del ciclo ya que utilizaste `try/except` en su interior.

Espero que esto te ayude a resolver los problemas que se están generando, de todas formas quedo atento a cualquier duda al respecto que pueda haber quedado, éxito :v:.

**Comment by rtrubio** [comment]
perfecto! voy a revisar todo lo mencionado y cualquier duda vuelvo a preguntar, muchas gracias!!
