### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 35: invalid start byte

### ISSUE THREAD

**Issue by based-on-what** [IIC2233/syllabus#1144]
Hola a todos, estoy (tratando) de implementar correctamente el envío desde el servidor del bytearray de la carta, al momento de cargarla (json.loads()) desde el cliente (después de decodificarla), me arroja el error que escribí en el título de este tema.

El bytearray que tiene ese error es este:
`b'\x00\x00\x00\x01\n\x00\x00\x00amarillo\x00\x00\x00\x02\n\x00\x00\x00sentido\x00\x00\x00\x03\x80\x00\x00\x00pokemon\\sentido_amarillo.png'`

No logro descifrar muy bien cuál es el problema, para pasar los strings a bytes, lo hice mediante `bytearray(str, 'utf-8')`, con `.encode()` tengo el mismo error.

Saludos y gracias de antemano.

**Comment by igbasly** [comment]
Hola @based-on-what :v:

Dime, ¿aún estás teniendo problemas con tu programa? De ser así, podrías darme un poco más de detalle acerca del contexto en que está ocurriendo esto.

Saludos 🙌

**Comment by based-on-what** [comment]
> Hola @based-on-what ✌️
> 
> Dime, ¿aún estás teniendo problemas con tu programa? De ser así, podrías darme un poco más de detalle acerca del contexto en que está ocurriendo esto.
> 
> Saludos 🙌

Hola, sucede durante el proceso en el que estoy creando el bytearray que se envía desde el servidor para mostrar el sprite de la carta serializada, lo que me percaté es que combiné bytes de strings (tipo y color) y de integers (los ID y los largos X/Y/Z), causando ese error al decodificar todo el byterray de una sola vez, ahora tengo "la película más clara" sobre cómo solucionarlo y enviar correctamente el bytearray. Gracias!

**Comment by vobrador** [comment]
Holaa, tuve el mismo problema (el primero) y no he encontrado otra issue donde la expliquen y acá queda a medias jajaj. Alguien me podría ayudar con eso porfavor?

**Comment by igbasly** [comment]
Hola @vobrador ✌️ 
Lamento la demora, pero tal como le dije a tu compañero, me es difícil decir que podría causar el error sin mayor contexto.
 Considerando lo último que escribió y pensado que esto se podría  aplicar a tu caso, pienso que es probable que el error ocurra porque tienes un gran arreglo de *bytes* con una mezcla entre *bytes* de  *strings*, entero e imágenes, que al momento intentar des-serializarlo todo con json, genera este error porque hay datos que no puede transformar.
Como consejo, debes tener mucho cuidado cuando estás des-serializando los datos, en hacerlo tal como lo enviaste, respetando los mismos protocolos. Por ejemplo, si tenías un diccionario y lo pasaste a un *string* con JSON, y después a *bytes* con `encode`, pero luego intentas revertirlo con pickle, es probable que ocurra un error, lo mismo aplica acá.

De todas formas, te pido que me indiques un poco más de contexto respecto a tu problema y si lo que te he mencionado va al caso o no.
Quedó atento, saludos 🙌
