### ISSUE TITLE
Abrir parametros.json en servidor

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2233/syllabus#1145]
Hola! Quiero importar el archivo parametros.json al módulo servidor, en el cual tengo la clase Servidor. Mi pregunta es si se considera mala práctica hacerlo fuera de la clase, y si fuera así, debería crear una función que lo abra, o ponerlo en el inicio de la clase? 🤔

**Comment by furcelay** [comment]
Me uno al hilo :eyes:
En particular para el cliente he creado varios parámetros que controlan las dimensiones de los labels y los paths de los archivos .ui, por lo que resulta reiterativo abrir y cerrar `parametros.json` cada vez que quiera acceder a una variable, y en particular estos últimos debo leerlos fuera de la clase. Todo sería más simple si al comienzo de cada módulo leo el archivo y lo deserializo como una variable global `PARAMETROS`.

**Comment by gatochico** [comment]
Hola! 

En el hilo de la issue de líbrerías/malas prácticas #1026 se habla un poco de este tema. Citando lo que dijo @lily416 :

> Si bien, cargar los parámetros de esa forma (en una variable al inicio del archivo) es en si una variable global, no les descontaremos por ello (pero por otras variables globales sí lo haremos).
Lo más correcto sería crear una clase y asignarle los parámetros como uno o más atributos.

Saludos!

**Comment by furcelay** [comment]
Muchas gracias!
