### ISSUE TITLE
Cambio en archivo grafo.json

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#1145]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tuve que realizar un pequeño cambio en el archivo grafo.json para que funcione mi programa. Mi duda es: ¿Es válido hacerlo?, Pensaba subir el archivo al repo e indicar en el README el por qué no lo ignoré 🤔

Graciasss

**Comment by DCCollao** [comment]
Hola @denisseleiva! 

El cambio que necesitaste hacer a `grafo.json` no es válido. El archivo `grafo.json` debe ser ignorado mediante `.gitignore`, por lo que no tendremos tu archivo al momento de la corrección, así que usaremos el mismo que les entregamos de base para realizar la tarea.

Como recomendación, podrías leer el archivo `grafo.json` y una vez que lo tengas cargado en tu _script_, hacer las modificaciones necesarias para que funcione.
Mucho éxito!

**Comment by denisseleiva** [comment]
Okaa, gracias!
