### ISSUE TITLE
crear objeto cliente en servidor

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2233/syllabus#1146]
Hola, para modelar la funcionalidad del servidor, ¿debo crear una clase cliente que funciones dentro del servidor?

**Comment by gatochico** [comment]
Hola! 

Como el foco de esta tarea es Networking y no OOP, no es una obligación explícita que tu servidor funcione mediante clases. Sin embargo, es bastante util ya que puedes aprovechar los métodos y atributos de las clases para tener un programa mucho más ordenado y que se te haga más manejable al momento de trabajar en él. Nuevamente, no es obligación y no hay puntaje por trabajarlo como clase o sin clase.

Ahora si estás preguntando cómo se modelaría si se trabaja como clase... te recomendaría revisar las ayudantías de networking para ver ejemplos.

Éxito y saludos!!
