### ISSUE TITLE
Problema con enviar archivos por pickle desde el servidor: Cuando leo el archivo desde cliente no se lee todo el código

### ISSUE THREAD

**Issue by dedmu5** [IIC2233/syllabus#1146]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola. Implementé un sistema cliente - servidor basado en el jupyter de ejemplos de networking. Hice que cada vez que se quisiera mandar un archivo serializado por pickle, que antes se avisara enviando un string que diga "pickle", que lo que hace es cambiar un atributo (self.receiving_pickle) de True a False para que el cliente sepa que el contenido que venga a continuación hay que hacerle un pickle.load(). Resulta que puse varios prints y cada vez que mando un mensaje que no está serializado con pickle el código lee toda la función. Sin embargo, cuando envío un objeto serializado con pickle, misteriosamente el código se lee hasta una cierta parte, como si todo lo demás lo obviara.

Cuando envío un mensaje no serializado con pickle (se imprime el "AAAA..."):
![image](https://user-images.githubusercontent.com/65060602/100534200-01128a80-31eb-11eb-8f2a-4b0745c40c47.png)

Cuando envío un mensaje serializado con pickle (no se imprime el "AAAA..."):
![image](https://user-images.githubusercontent.com/65060602/100534214-24d5d080-31eb-11eb-809c-a62fce065128.png)

Lo cual no tiene sentido porque el código es:
[redacted]

Por otro lado, no tengo ningun except: pass ni nada de eso. Esto es super raro...
Tengo mi código actualizado en el repositorio, por si me pueden ayudar a verlo. Pienso que quizás es un problema de threading, pero hasta ahora he hecho de todo y no puedo solucionarlo. 
Saludos

**Comment by rodrigobj99** [comment]
Hola @dedmu5 !
Estuve revisando tu código y al parecer lograste solucionarlo, cambiando la serialización por otra que no sea pickle.
En caso de no ser así avisame para revisarlo nuevamente. 

Saludos!

**Comment by dedmu5** [comment]
> Hola @dedmu5 !
> Estuve revisando tu código y al parecer lograste solucionarlo, cambiando la serialización por otra que no sea pickle.
> En caso de no ser así avisame para revisarlo nuevamente.
> 
> Saludos!

Así es, disculpa por no avisar para no hacerte perder el tiempo. No sé que onda con pickle, pero muchas gracias por la disposición!
