### ISSUE TITLE
uso de os.path para buscar archivos en otras carpetas

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#1147]
segun pude investigar, el metodo os.path.join(), solo acepta argumentos de la forma "path-like object", osea str y bytes. Entonces, ¿como puedo usarlo para que me lea por ejemplo: ["..", "sprites", "simple", "reverso.png"]? (Este ejemplo, es la versión del path, donde practicante,  se hizo path.split("/"), del path "../sprites/simple/reverso.png").

**Comment by cristozille** [comment]
Hola! Se ingresa a la función de la forma os.path.join('..', 'sprites', 'simple', 'reverso.png').

**Comment by felipehen** [comment]
Hola, Ya habia pensado eso, pero yo buscaba un caso mas general, donde no se cuales seran los elementos de la lista, pero resulta que lo encontre un recien en internet, y es usando el metodo os.path.join(*lista)

**Comment by cristozille** [comment]
Buenisimo!
