### ISSUE TITLE
Duda número de bloque en envío de información

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2233/syllabus#1147]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! En la sección 5.1.3 del enunciado dice lo siguiente:
![image](https://user-images.githubusercontent.com/64439029/100544479-abfb6680-3234-11eb-87a1-d791a7a11b76.png)

Mi duda es ¿cual es el objetivo de enviar el número del bloque antes de la información? ¿La idea es que revisemos (a partir de los números de los bloques recibidos) si la información fue recibida completamente?

Saludos y gracias!

**Comment by lucasprato** [comment]
Hola @ignaciomansuy,
En la issue [#1040](https://github.com/IIC2233/syllabus/issues/1040) se respondió una duda similar. Recuerda siempre revisar issues pasadas para encontrar si alguna puede solucionar tu duda.

Éxito en la tarea!
