### ISSUE TITLE
Cambiar los nombres a los archivos de la carpeta sprites

### ISSUE THREAD

**Issue by dedmu5** [IIC2233/syllabus#1148]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, estoy haciendo mi programa de tal forma que cada jugador tiene de nombre el color que les tocó. De esta forma, los nombres de jugadores disponibles son ["rojo", "verde", "azul", "violeta"]. Dado esto, encuentro muy conveniente cambiar el nombre de los archivos de la carpeta sprites para instanciarlos más sencillamente usando el self.username de cada uno. Sin embargo, hay que ignorar la carpeta, por lo que ustedes tendrán nombres de sprites distintos a los mios. ¿Qué puedo hacer?

**Comment by lucasprato** [comment]
Hola @dedmu5!


> Dado esto, encuentro muy conveniente cambiar el nombre de los archivos de la carpeta sprites para instanciarlos más sencillamente usando el self.username de cada uno. 

Mantén la misma estructura que se da actualmente en la carpeta sprites del syllabus. Para corregir nosotros también la usaremos. 

El uso de `parametros.json` puede facilitar la llamada de los paths. Por ejemplo, se podría tener el siguiente key-value:

`"CHOZA_VERDE"  :  "choza_verde.png"`

Por lo que cuando quieras obtener  este path en el cliente podrías hacer algo parecido a lo siguiente:

`parametros[f"CHOZA_{upper(nombre_jugador)}"]`

Lo anterior asumiendo que nombre_jugador es `verde`.

Espero que esto te sea de ayuda!
