### ISSUE TITLE
Qtdesigner para mac

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2233/syllabus#1148]
hola! me descargué qtdesigner de esta pagina https://build-system.fman.io/qt-designer-download que es la que me han mandado, y me sale esto al intentar abrirlo, saben que puedo hacer?

![Captura de pantalla 2020-06-26 a las 15 06 13](https://user-images.githubusercontent.com/62019819/85892258-9635d100-b7be-11ea-9311-675ec90e7eaf.png)

**Comment by DaHunterTime** [comment]
Hola, no puedes abrirlo directamente debido a la configuración de seguridad de tu mac.

Para poder usarla igualmente después de que te salga el mensaje puedes ir a preferencias del sistema > "Seguridad y privacidad" > General > "Abrir de todos modos" y te debería de funcionar.

Si quieres más información revisa el [soporte de Apple](https://support.apple.com/es-cl/guide/mac-help/mh40616/mac).

**Comment by maggiemunoz** [comment]
gracias! me funcionó :)
