### ISSUE TITLE
Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#1149]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!
Estaba intentando probar la conexión entre el server y el cliente. Inicie primero el server y luego el cliente, pero al parecer el cliente se desconectaba de inmediato del servidor:
![image](https://user-images.githubusercontent.com/68198662/100554102-4aa5b880-3271-11eb-94dd-cc1c9c7a213a.png)

Para corroborar donde podría ser que la conexión se estaba cortando, puse un `print()` en el `while True` del cliente que se encarga de escuchar al servidor (`cliente `> `backend_cliente `> a continuación de la linea 35), así pensé que vería en la consola el mismo print hartas veces, pero en vez, ocurrio esto:

![image](https://user-images.githubusercontent.com/68198662/100554195-d0296880-3271-11eb-8231-8dc9344fb734.png)

El error es el siguiente: `Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads`

Estuve viendo si algún issue me podia ayudar, el más parecido fue el #1056, pero intenté buscar cual podría ser el thread que se estaba terminando antes de tiempo y 1) no logré encontrarlo ó 2) mi error puede ser diferente. Está hecho el push en mi repositorio, **¿Cual puede ser mi error?**

**Comment by gatochico** [comment]
Hola @Gsalinas1506 !

Lo que ocurre en tu caso es que en el código del cliente, **no hay nada que actualmente mantenga el código corriendo indefinidamente**. En específico, tienes que tu thread que escucha al cliente es Daemon (lo que significa que terminará en conjunto con la ejecución del programa principal), y si te fijas bien, no hay nada en tu código que deje al cliente corriendo (como un ciclo, por ejemplo), sino que ejecuta todo el código existente, llega al final y se acaba la ejecución del programa principal. Cuando uno trabaja con interfaces gráficas, la interfaz abierta suele ser lo que mantiene el código corriendo de forma indefinida, pero como todavía no lo implementas en tu cliente, no existe ese mecanismo todavía.

Algunas opciones serían:

1. Implementar la interfaz gráfica del cliente, para que esta sea lo que mantiene al cliente andando sin terminar el código.
2. Implementar temporalmente un ciclo infinito después de inicializar todos los atributos de la clase cliente, para que este ciclo mantenga el programa corriendo.
3. Cambiar tu thread de escuchar cliente a no daemon hasta que empieces a hacer la interfaz. (recuerda cambiarlo después!)

Saludos y quedo atenta!
