### ISSUE TITLE
Error al recibir información entre Servidor y Cliente

### ISSUE THREAD

**Issue by jtmeyer98** [IIC2233/syllabus#1149]
Para la tarea estoy utilizando un código basado en la ayudantía 10. 
Por medio de prints en el código puedo ver que la información se envía y se recibe bien entre servidor y cliente. 
Sin embargo ocurre un error "al mismo tiempo" que se recibe la información (en ambos programas).
Este "error" no permite que siga con el funcionamiento (como ver la sala de espera)

Lo que hice para ver donde era el error fue un built-in try/except"
```python
try:
    while True:
        "se recibe la info y se pasa al sgte método"

except:
    print("error")
```
Al parecer tanto el try como el except se ejecutan, porque puedo ver los prints de ambos.

Cuando saco el except del código el error en la terminal es el siguiente:
```bash
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\joset\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\joset\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\joset\Desktop\T03\servidor\servidor.py", line 51, in listen_client_thread
    bytes_recividos = client_socket.recv(4)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto
```
¿Que puedo hacer? 
Lo he intentado todo,  por favor un alma buena ayúdeme.

**Comment by jtmeyer98** [comment]
Acabo de hacer un commit por si algún ayudante lo quiere ver

**Comment by gatochico** [comment]
Hola! Corrí tu código y (además de un type error primero, ya que en el cliente emites una señal que debería enviar un `str`, y le pasas un `dict`) aparentemente lo que ocurre no es que el cliente caiga por algún error, sino que el problema se produce porque cuando haces `self.cerrar_ventana_inicial.emit()`, por alguna razón el programa principal (el que está en main.py) termina su curso y se acaba su ejecución.

Para probar, moví la linea de tu codigo `self.abrir_sala_de_espera.emit(str(usuarios))`  justo arriba de `self.cerrar_ventana_inicial.emit()`, con el fin de que se abriera primero la ventana de la sala de espera y luego se cierre la original, y por lo menos esta vez el programa quedó corriendo, con la ventana de la sala de espera abierta, sin que ni el server ni el cliente me lanzen error. Intenta haciendo eso y me dices cómo te va! 🐸

**Comment by jtmeyer98** [comment]
Perfecto!! Me funciona para todos los casos, muchas gracias!!!!
