### ISSUE TITLE
Librerías permitidas/no permitidas en la T01

### ISSUE THREAD

**Issue by lily416** [IIC2233/syllabus#115]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:
 
> **Puedo usar la librería nombre_librería para hacer explicación_de_lo_que_quiero_hacer**
 
¡Recuerden especificar en su README qué librerías utilizan!
 
---
 
## ✔ **Librerías Permitidas** 
- ABC
- random
- collections
- itertools
- functools
- math
- operator
- dataclasses
- string
- copy
- os
- sys.exit
- atexit
- pprint
- textwrap
- beautifultable
- typing
 
## ❌ **Librerías Prohibidas**
- csv
- json
- pickle
- shutil
- pathlib
- glob
- pandas
- numpy
- ast
- curses
- io
- re
 
## ☠️ **_Built-ins_ Prohibidos** 
- exception (try/except)
 
El uso de alguna de las siguiente funciones es automáticamente un 1,0 sin discusión: 😭
- exec
- eval
 
 
¡Ánimo y éxito en sus tareas! 🏁🚗🚲🏍

**Comment by dgzmr** [comment]
Puedo usar `colorama` para agregarle color a los prints?

**Comment by lily416** [comment]
@dgzmr Sí, puedes usar `colorama` 🌈

PD: Lo siento por la demora 😓

**Comment by benjastraub** [comment]
Respecto a 'exception', ¿es sólo try/except?

¿Puedo usar `raise Exception` en mis funciones para identificar problemas al llamar la función?

**Comment by lily416** [comment]
@benjastraub La prohibición de `exception` incluye usar `raise Exception`.
Para identificar los problemas que puedas tener al llamar funciones te recomiendo usar prints específicos que te permitan “ver” lo que está sucediendo en la función.

**Comment by cristozille** [comment]
Hola, se puede utilizar kwargs?

**Comment by lily416** [comment]
@cristozille Sí, pueden usar `kwargs`.

**Comment by dgzmr** [comment]
Se puede usar unidecode para quitar los acentos de los strings?

**Comment by lily416** [comment]
@dgzmr ¿Por qué le quieres quitar las tildes a las palabras?

**Comment by dgzmr** [comment]
@lily416 estoy como pasando directamente como kwargs desde el archivo los argumentos al instanciar los objetos, entonces como en el texto algunas columnas tienen acentos y usualmente no se usan acentos para definir variables se genera un error. Está permitido definir variables usando acentos?

**Comment by lily416** [comment]
@dgzmr El _encoding_ por defecto de la versión 3.7 de python es UTF-8, por lo que se pueden definir nombres de variables, clases y funciones con tildes, así que no necesitas utilizar `unidecode`.

En caso de que quieras asegurarte, para verificar el _encoding_ de python debes ejecutar lo siguiente en un archivo .py: 
```python
import sys
print(sys.getdefaultencoding())
```

**Comment by tcperez** [comment]
Hola, puedo usar sys.stdout? :)

**Comment by lily416** [comment]
@tcperez ¿Para qué quieres utilizarlo?

**Comment by tcperez** [comment]
para alterar los prints, así utilizar el programa es más grato

**Comment by Juampisaez** [comment]
Se pueden ocupar la estructuras por compresion para hacer mas pequeño el codigo?

**Comment by lily416** [comment]
@tcperez No puedes ocupar `sys.stdout`, centrate en utilizar `print` y `format`.

@Juampisaez Sí, pueden utilizar estructuras por comprensión.

**Comment by sebaav12** [comment]
Podemos usar la librería abc para clases abstractas??

**Comment by lily416** [comment]
@sebaav12 Sí, pueden usar `ABC`.

**Comment by Juan379** [comment]
Hola!
Puedo usar sys.path[0] para poder lleer los archivos de forma relativa utilizando os.path.join(sys.path[0], "pistas.csv") por ejemplo?

**Comment by MartinAracena** [comment]
Se puede usar global para llamar a los parametros por el nombre, asi solo hago un diccionario con los nombres y no tengo que poner cada una.

**Comment by lily416** [comment]
@Juan379 No puedes usar `sys.path`, ya que indirectamente estarías usando un path absoluto. Para profundizar más sobre el uso de paths relativos mejor revisa bien el [material](https://github.com/IIC2233/contenidos/blob/master/semana-01/3-paths.ipynb) o abre una issue. :)

@MartinAracena No puedes usar `global`, debido a que en esta tarea se descontará por el uso de variables globales, ya que es considerado una mala práctica.

**Comment by jpmarin1** [comment]
Hola! Puedo usar importlib.reload() para reiniciar un módulo?

**Comment by fbesoainp** [comment]
Hola! Puedo usar la libreria time para usar sleep y hacer una espera para comenzar la carrera?

**Comment by lily416** [comment]
@jpmarin1 No puedes utilizar `importlib.reload()`, mejor centrate en que el programa funcione sin tener que recargar los módulos.

@fbesoainp Tampoco puedes usar `time.sleep()`, ya que puede complicar la corrección de la tarea.

**Comment by jfuentesg26** [comment]
hola! puedo usar la funcion deepcopy()?

**Comment by Juan379** [comment]
Puedo usar el modulo tabulate para poder generar las tablas de tiempos y otras que quiero agregar? (pondría en el readme que este modulo lo tiene que descargar el ayudante)

**Comment by lily416** [comment]
@jfuentesg26 `deepcopy()` es parte de la librería `copy`, la cual está permitida, por lo que puedes usarlo 👍

Aunque debes tener cuidado, ya que `deepcopy` hace una copia recursiva de los elementos que estas copiando, por lo que si llegas a **modelar las clases circularmente** tu programa fallará al realizar la copia de la estructura 😱 Para más información revisa el siguiente [link](https://docs.python.org/3.7/library/copy.html#module-copy).

Si no te sientes seguro con respecto a la modelación de tu programa, lo mejor sería que uses la función `copy()` para duplicar los elementos 😉

**Comment by lily416** [comment]
@Juan379 Sí, puedes utilizar `tabulate`.

**Comment by SamWeinstein** [comment]
Hola! Se puede usar fileinput para guardar partidas?

**Comment by jpperez5** [comment]
Puedo utilizar la librería time (con fines "estéticos" para guardar las partidas?)?

**Comment by lily416** [comment]
@jpperez5 No puedes ocupar `time`.

**Comment by Jprampad** [comment]
@lily416 Se puede ocupar prettytable? ya que es muy parecida a beautifultable

**Comment by lily416** [comment]
@Jprampad Sí, puedes ocupar `prettytable`. Para futuro recuerda preguntar antes de que termine la entrega de la tarea 👀
