### ISSUE TITLE
Menú de Seguidores: loop para pedir input

### ISSUE THREAD

**Issue by iastruque** [IIC2233/syllabus#115]
En la parte menú de seguidores del enunciado que dice:
"Para seguir a otro usuario basta con ingresar el nombre de quien se quiere seguir, en caso de que el nombre
**ingresado no exista o se ingrese el nombre propio (no te puedes seguir a ti mismo) se le debe avisar al
usuario y regresar al men´u."**
 ¿Puedo hacer un loop hasta que escriba un usuario que cumpla con los requisitos?
En caso contrario cunado dice, regresar al menú, ¿se refiere al menú de seguidores ?

**Comment by Tito0906** [comment]
Holaa @iastruque! No es correcto que el programa entre en un loop, recuerda que el programa debe ser amigable con el usuario y como dice el enunciado, debe dar la opción de volver cuando corresponda. Además, en el caso del error en el nombre dice explícitamente que debe volver al menú. Esta bien si el menú al que retorna es el menú de seguidores.

**Comment by lily416** [comment]
Por favor no cierres las _issues_, puede que otro alumno tenga la misma duda y si se encuentra abierta le será más fácil encontrarla c:
