### ISSUE TITLE
Duda con método __gt__ en ejerc. prop. 4.2 (Progragotchis)

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#115]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, me pareció más práctico para este ejercicio definir el método \__gt__ solo una vez en la superclase "progragotchis" en vez de hacerlo en cada subclase, pues si bien cada subclase tiene una forma distinta de calcular su vida, todas ellas se ordenan de la misma manera: un objeto progragotchi es mayor que otro si tiene mayor vida que ese otro.

Por lo que encuentro que se puede definir directamente en la superclase el método \__gt__ , estableciendo el criterio mencionado anteriormente y haciendo uso del método "obtener_vida".

Aún asi, tengo la duda de si efectivamente lo que describí arriba esta bien, o si a lo mejor había que sobrescribir el método \__gt__ en cada subclase de forma distinta y no entendí bien el ejercicio.

Desde ya gracias.

**Comment by tqmbanados** [comment]
Hola! Gracias por tu aporte. Efectivamente, podría rellenarse el método en la superclase, sin embargo, para completarlo correctamente es necesario llamar el método ```obtener_vida()```, el cual no es parte de la superclase, y lanzaría error en la definición. Para solucionar esto, puedes definir ```obtener_vida()``` como abstract method en la superclase.
Son dos maneras distintas de enfrentar el problema, y cada cual puede ser útil en distintos contextos. Aunque por "economía de código", creo que tu sugerencia en este caso es óptima :)

**Comment by JuanpaBC** [comment]
bkn gracias
