### ISSUE TITLE
Objeto creado => objeto no creable

### ISSUE THREAD

**Issue by 3rdPix** [IIC2233/Syllabus#115]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Si tengo el conjunto de objetos _creables_, obtenidos a partir del archivo. Y el entrenador decide crear un objeto, y su resultado es **exitoso**. ¿Qué debemos hacer con el objeto de base? Se debe eliminar de la lista de objetos _creables_? De modo que ya no puede volver a ser creado ó, en contraste, permanece ahí, y el entrenador podría volver a tener una segunda copia de tal objeto si vuelve a crearlo exitosamente.

Por ejemplo, si yo realizara lo siguiente:
```
objetos = [obj1, obj2, obj3]
objetos_entrenador = []
entrenador.crear_objeto()
```

El resultado debería ser

**Opción 1**

```
objetos = [obj1, obj3]                  # el item se borra de los "creables"
objetos_entrenador = [obj2]
```

**Opción 2**

```
objetos = [obj1, obj2, obj3]            # es posible volver a crear al item
objetos_entrenador = [obj2]
```

**Comment by MrNachoX** [comment]
Hola @3rdPix! Los objetos se pueden volver a crear, por lo que el entrenador podría llegar a tener una segunda copia del objeto.
