### ISSUE TITLE
Glosario tarea

### ISSUE THREAD

**Issue by odbravo** [IIC2233/Syllabus#115]
En el enunciado el ítem 4 es Glosario y se le asocia un porcentaje, supongo que del valor que tiene en la evaluación. Mi pregunta es a qué se refieren con ese ítem ¿Tenemos que ocupar esos nombres como "comandos" que ingresa el usuario para operar en el sistema? ¿Basta con implementar las funciones asociadas a las acciones del glosario y que el sistema opere con opciones (ej: 1: realizar bid, 2: realizar ask, 3: salir)? ¿Hay algo más que hacer respecto a ese glosario?

**Comment by Arcoirisky** [comment]
Se refiere a la creación de esas entidades con/como clases o atributos :D 
Osea, con que existan las entidades definidas en el glosario y cumplan las funciones especificadas estarías bien  :+1:
