### ISSUE TITLE
Puedo hacer el readme usando jupyter para escribir en markdown? 

### ISSUE THREAD

**Issue by matix3000** [IIC2233/Syllabus#115]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola! se que jupyter tiene una suerte de interfaz, user friendly para utilizar markdown, quería preguntar si podia hacer el archivo readme en un jupyter?
O tiene que ser en el formato que entregaron?

Muchas gracias!

**Comment by roahoki** [comment]
Hola matix3000, puedes escribir el readme donde prefieras siempre y cuando respetes el formato que te pasamos, es decir, rellena correctamente el template que se entrega para que los ayudantes podamos entender tu trabajo de la mejor manera posible. Además, asegúrate que la extensión sea la pedida README.md
