### ISSUE TITLE
Puntaje por uso de contenidos

### ISSUE THREAD

**Issue by jahernandez2** [IIC2233/Syllabus#115]
Hola, estuve viendo la distribución de puntaje de la T1 y no existe una evaluación explícita de los contenidos (por ejemplo herencia o polimorfismo). ¿No existe una penalización si no se usan por lo tanto? Es decir que si en vez de hacer algo que estaba para hacerse con herencia y lo hago de una forma más "manual", ¿debería estar bien?
Saludos y gracias de antemano.

**Comment by pabloist** [comment]
Hola!

Te comento que en la sección de programación orientada a objetos, tienes los puntajes asociados a lo que indicas en: "Clase está bien definida". En caso de que no se utilice correctamente herencia cuando haya que hacerlo, el descuento irá asociado a dicho ítem.

Saludos!
