### ISSUE TITLE
Recolectar a planeta recientemente conquistado

### ISSUE THREAD

**Issue by alexaptib** [IIC2233/Syllabus#115]
Si quiero recolectar recursos de un planeta conquistado, este planeta tiene recursos desde su creacion o desde que es conquistado?
En otras palabras, un planeta empieza a generar recursos solamente si es conquistado o solo por el hecho de ser un planeta genera recursos?

**Comment by santilaguna** [comment]
desde su creación, no soy ayudante pero aparece en el enunciado

**Comment by IchottMano** [comment]
@alexaptib Hola!
Cuando desees recolectar recursos de un planeta conquistado, debes calcularlo usando la *ultima recolección* del planeta, si el planeta es creado manualmente, esto significa que el tiempo es el de creación.
Saludos!
