### ISSUE TITLE
Lectura de bytes

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1150]
Hola! En el enunciado mencionan que la única forma de enviar las imágenes es a través del formato dado , sin embargo una vez que llega al cliente (en el back end) es posible enviárselo al front end en el formato que más nos acomode ? Por ejemplo enviar sus datos de la imagen ya decodificados  en un diccionario

**Comment by DCCollao** [comment]
Hola @RonaldoSosa!

El protocolo de envío de datos mediante un bytearray que definimos en el enunciado es solamente para envío de las cartas entre servidor y cliente, cada vez que algún cliente lo solicite. La forma en que tú definas la comunicación frontend/backend queda a criterio tuyo. En todo caso, es importante fijarse en que el no uso de señales está considerado como una mala práctica para esta tarea y por lo tanto, si no las utilizas tendrás un descuento.

**Comment by RonaldoSosa** [comment]
Yaaaa entendido !!! Graciasss! PD el diccionario era para ""meterlo"" en una señal y pasarselo al front end
