### ISSUE TITLE
Error al correr el codigo de la ayudantia de networking

### ISSUE THREAD

**Issue by PedroFuenzalida** [IIC2233/syllabus#1150]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Al correr el codigo de la ayudantia me tira error en la linea de código 

**largo_archivo = int.from_bytes(client_socket.recv(4), byteorder='big')**

y me tira el error "[WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto". Copie y pegué el código sin cambiarle nada, entonces no se por qué falla.

**Comment by aaossa** [comment]
Hola @PedroFuenzalida, ¿qué valores estás usando para el *port* y *host* en el cliente y el servidor? ¿Probaste usando valores distintos? ¿La excepción ocurre al enviar el primer mensaje? Intenta con lo de las preguntas y si no funcione vamos viendo más en detalle qué podría ser 🤔 ¡Ánimo con la tarea ✨!

**Comment by PedroFuenzalida** [comment]
En ambos use como host **socket.gethostname()** y el puerto lo cambie para probar distintos valores. Ejecuto el servidor, printea "Servidor escuchando en..." después ejecuto el cliente que printea "Creando cliente" y "Cliente conectado a servidor" y después un segundo se cae el servidor con la excepción 

"Exception has occurred: ConnectionResetError
[WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto"

**Comment by aaossa** [comment]
Una posibilidad es que el cliente esté cerrando su conexión inmediatamente, por lo que el servidor no alcanza a enviarle nada. Lo que te recomendaría es ejecutar la función para escuchar del cliente en el *thread* principal (es decir, no usando `Thread`) e imprimir cada vez que hagas `recv` en el mismo cliente, por si te está llegando parte del mensaje. Además, mientras ejecutas el cliente en el *thread* principal, te recomendaría quitar (si es que tienes) los `try` y `except` que tengas, para ver las excepciones reales que se levanten.
