### ISSUE TITLE
Hexagonos png se sobreponen

### ISSUE THREAD

**Issue by fedezang** [IIC2233/syllabus#1151]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! tengo una duda respecto a los hexagonos en la interfaz, al colocar la grilla aparecen los hexagonos, pero debido a que la foto de cada hexagono es cuadrada, los extremos de esta foto (que debieran ser transparentes) se sobreponen sobre los hexagonos adyacentes.
Existe una forma de arreglar esto? Porque me podría complicar para mostrar las chozas y carreteras
![Captura de Pantalla 2020-11-29 a la(s) 23 08 22](https://user-images.githubusercontent.com/62078222/100561469-ca467e00-3297-11eb-83b2-0757789dcef0.png)

Gracias de antemano!

**Comment by DasVaca** [comment]
Hola, no soy ayudante, pero me ocurrió lo mismo y lo solucioné poniendole a cada hexagono en el stylesheet 
``'background-color: rgba(255, 255, 255, 0)'``
No sé si el rgb sea importante, pero el alpha tiene que ser 0 para que se vea transparente.

**Comment by fedezang** [comment]
Muchas Gracias! Lo logré solucionar
