### ISSUE TITLE
Agregar un numero al comienzo del bytearray al enviar cartas

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#1151]
mi cliente lee los mensajes basandose en sus primeros 4 bytes. Esto se debe a que cuando envio cartas, siempre partire con un 1, por lo cual se me ocurrio mandar toda la informacion de esta forma. Esto hace que el cliente tome estos primeros 4 bytes como la orden que va a seguir a continuacion. Por ejemplo, en el caso de que estos 4 bytes, sean un 6, debe cerrar la sala de espera, pues el juego esta por comenzar.

Pero, cuando idee esto, se me olvido pensar que pasara cuando las cartas no sean del jugador principal, sino que de uno de sus compañeros.  Como solucion a esto, se me ocurrio agregar un numero al inicio del bytearray, que identifique el jugador dueño de la carta, pero nose si eso este permitido. Un ejemplo podria ser, que antes del byteaaray haya un 8, indicando que la carta es para el jugador 3, o algo por el estilo.

Se que podria mandar un numero por separado, y luego hacer que los siguietes mensajes se lean de forma distinta, pero me da miedo que como mando los mensajes por thread, un mensaje diferente se pueda colar entre medio del numero y el bytearray, y practicamente destruir la forma que leo los mensajes

**Comment by gatochico** [comment]
Hola! (lamentamos la tardanza u.u)

¿Para qué quieres que el cliente reciba las cartas de otros jugadores? De forma general, en la mayoría de los casos basta con que solo el server contenga las cartas de todos los jugadores para efectuar la lógica, y que cada cliente reciba sus propias cartas solamente, por lo que no necesitarias ese diferenciador.

Espero tu respuesta!

**Comment by felipehen** [comment]
principalmente, para que cada jugador pueda ver cuantas cartas tiene cada uno de sus contrincantes. Creo que se me olvido especificar, por ejemplo, al jugador 1, solamente le mandare sus cartas, para el mismo, y un monton de reversos de carta, representando la cantidad de cartas que tiene cada uno de sus oponentes.

Por ejemplo, en una partida de 2 personas "felipe" y "sergio", donde caada uno tiene 4 cartas, felipe, veria sus 4 cartas, pero ademas veria 4 cartas reversas en el espacio de las cartas de sergio, y viceversa.

**Comment by gatochico** [comment]
Claro, comprendo.

La verdad es que la mejor opción es lo que dices de primero mandar por separado el contexto de la carta y luego enviar el bytearray que se define el enunciado y que este se lea de forma distinta según el primer mensaje. Respecto a la preocupación que tienes de que se 'cuelen' mensajes de otro thread entremedio de ambos send, puedes solucionarlo trabajando con el uso de _**locks**_  que se vió en la materia de threads (hacer que un thread ponga un lock sobre la función de enviar mensajes hasta que haya mandado el mensaje que quiere completo, y luego lo suelte para evitar que alguien más lo use mientras se está usando).
