### ISSUE TITLE
Error .loadFromData(my_bytes)

### ISSUE THREAD

**Issue by pablo-soto** [IIC2233/syllabus#1152]
Hola , llevo 2 dias intentando arreglar el error de loadfromdata, me he leido mil post y aun no puedo arreglarlo, si saben porque o algo de ayuda estaría muy agradecido
![error](https://user-images.githubusercontent.com/62078568/85907729-829b6200-b7e0-11ea-89b9-2304fe9345c7.png)

**Comment by lily416** [comment]
Hola @pablo-soto, ¿puedes subir tu código? Es para probarlo y ver si encuentro el error :)

**Comment by pablo-soto** [comment]
Graciass por contestarme, como prefieres que los suba? que haga un push a mi repo ? o lo mando por acá nomas?

**Comment by lily416** [comment]
Un push a tu repo, por favor.

**Comment by pablo-soto** [comment]
Subido! muchas gracias

**Comment by lily416** [comment]
Probando tu código me encontré con estas dos cosas:;
1. Con ciertas cartas se levanta este error: 
   ```python
   UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 27: invalid start byte
   ```
   Te recomiendo usar UTF-8 para hacer encode y decode.

1. Al tratar de cargar la imagen se produce este error:
   ```
   libpng error: Read Error
   ```
   No sé que lo puede causar, voy a investigar durante el fin de semana. Debido al domingo de descanso no te podré responder hasta el lunes, así que te invito a investigar por tu cuenta.

Si sigues teniendo problemas con el envió de imágenes, te recomiendo saltar esta parte (mandar las imágenes en un diccionario o leerlas desde el cliente) y continuar con otras funcionalidades.

Saludos 👋

**Comment by pablo-soto** [comment]
Graciasss eres un sol! `libpng error: Read Error` es el que no he podido arreglar, pero muchas gracias

**Comment by pablo-soto** [comment]
Lo pude arreglar, muchas gracias de todas formas por tu disposición. escribí todo el "listen server"  denuevo.
