### ISSUE TITLE
Uso de emojis para íconos de la interfaz gráfica

### ISSUE THREAD

**Issue by dfloreaa** [IIC2233/syllabus#1153]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tenia dudas respecto al **uso de emojis para dar cuenta de íconos en la interfaz gráfica** ¿está permitido? En particular me gustaría usar el 👍 para simbolizar el querer terminar un turno (sería el texto que contiene).
Gracias!

**Comment by DCCollao** [comment]
Hola @dfloreaa!

No hay problema con que utilices emojis para simbolizar cosas en tu interfaz gráfica. Eso sí, recuerda que debe ser fácilmente entendible por quien corrija, por lo que si no te queda tan intuitiva, una aclaración en tu `readme.md` de qué significa cada cosa podría ser útil.

Mucho éxito!
