### ISSUE TITLE
Error con archivo.ui

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#1154]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!! Me sale este error [Errno 2] No such file or directory: 'ventana_principal.ui', pero no entiendo la razón, si el archivo lo tengo en la misma carpeta que el archivo que estoy corriendo, gracias!

**Comment by rodrigobj99** [comment]
Hola @Natydlb !
Estuve revisando tu tarea y creo haber encontrado el error. Al momento de ejecutar el cliente debes hacerlo desde dentro de su carpeta (`client`), ya que si lo ejecutas dentro de `T03` y le das una ruta relativa como `client/main.py` no encontrara el archivo porque lo buscara dentro de `T03` y no dentro de `client`. Por otro lado si lo ejecutas dentro de la carpeta `client` si lo encontrara, pues esta dentro de esta.

Espero te sirva. Saludos!

**Comment by Natydlb** [comment]
ile
"/Users/user/Desktop/Repositorio/Natydlb-iic2233-2020-2/Tareas/T03/client/ventana_principal.py"
así lo manejaba de Studio code, pero de la terminal lo manejaba desde  (base)
user@MacBook-Pro-de-User client y ahi me funcionaba, pero no así el archivo
.ui porque no se ve en la interfaz

**Comment by rodrigobj99** [comment]
@Natydlb pero ahora te esta funcionando? Te sugiero que lo corras desde la terminal misma del computador, dentro de la carpeta que te especifique, para evitar porblemas.

Saludos!

**Comment by Natydlb** [comment]
Desde la terminal me corre el codigo, pero respecto al archivo .ui no me
muestra nada, como que no me lo lee :(

**Comment by rodrigobj99** [comment]
@Natydlb que raro. A mí me funciona perfectamente, aunque se demora unos segundos en pasar de la sala de espera a la sala de juego y además esta es distinta al archivo .ui, ya que esta tapada por otros widgets, pero al sacarlos se ve perfectamente la sala de juego exactamente como en el archivo .ui.

**Comment by Natydlb** [comment]
hola! perdon ayer estaba haciendo una prueba, me puse a jugar y no pude
lograr conectar el  contenido del archivo .ui con el chat que estaba
creando en visual studio pero no pude lograr meter el chat sin que ocupara
toda la pantalla porque no se ve

**Comment by rodrigobj99** [comment]
@Natydlb en ese caso te recomiendo que intentes hacer el chat de otra forma y mientras avances lo mas posible con el resto de la tarea.

Saludos!
