### ISSUE TITLE
QDialog, ¿Es ventajoso usarlo o puede ser un QWidget?

### ISSUE THREAD

**Issue by sjlarrain** [IIC2233/syllabus#1155]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! 
He estado buscando información sobre el `QDialog` y no he logrado implementarlo para el tema de intercambio de recursos. No entiendo cual es la ventaja de ocuparlo sobre crear una ventana `QWidget` que permita hacer lo mismo. Principalmente entiendo como puedo comunicar el backend con el frontend y como le enviaría la información del intercambio con  `QWidget`, pero con el `QDialog` no estoy encontrando la información necesaria y además no he logrado entender la utilidad de los módulos `accept()` y `reject()` ¿Pueden enviar información al `MainWindow` para después traspasarla al backend? ¿Como funcionan los metodos anteriormente mencionados y para que sirven?

Muchas gracias de antemano

Saludos

Santiago

**Comment by Mjtala** [comment]
Hola @sjlarrain ! La ventaja de usar QDialog es tener una ventana extra o un pop up que bloquea las otras ventanas hasta que aprietes aceptar o rechazar el mensaje (dependiendo de los botones que implementas). En otras palabras, solo debes instanciar QDialog, modificarlo según lo que necesitas y conectar las señales que ya vienen.
Recuerda que el uso de QDialog es solo un tip y no es obligatorio utilizarlo. Sin embargo, si quieres aprender a utilizar QDialog te recomiendo visitar este link 
https://www.learnpyqt.com/tutorials/dialogs/
Ojalá te sirva y ánimo con lo que queda del semestre!! 🥳🥳🥳

**Comment by sjlarrain** [comment]
Gracias @Mjtala! Me queda la duda si entonces el `QDialog` funciona de forma parecida a las ventanas? Las señales y botones se podrian aplicar de la misma forma al igual que contruirlo con designer?

Muchas gracias por el link!!

 Saludos

Santiago

**Comment by Mjtala** [comment]
Funcionan igual! Saludos.
