### ISSUE TITLE
Registro de Cartas en el Cliente

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#1155]
¿Esta permitido guardar un registro en el cliente del tipo de carta que se tiene sin incluir la imagen, solo el color y tipo, o se debe hacer obligatoria mente el registro de cada carta que tiene cada usuario en el servidor?

**Comment by DCCollao** [comment]
Hola @felipefuentesporras!

El cliente sí puede tener almacenado qué cartas tiene en su mano. Además, en el enunciado no se menciona que el servidor tiene un registro de qué cartas tiene cada jugador. Solamente debe encargarse de , cuando un jugador decida jugar una carta, verificar que la carta a jugar es válida.

**Comment by Aloncarrasco** [comment]
> Hola @felipefuentesporras!
> 
> El cliente sí puede tener almacenado qué cartas tiene en su mano. Además, en el enunciado no se menciona que el servidor tiene un registro de qué cartas tiene cada jugador. Solamente debe encargarse de , cuando un jugador decida jugar una carta, verificar que la carta a jugar es válida.

Entonces, puedo guardar la imagen de la carta cuando llegue? (por ejemplo guardo el 3_rojo.png, Aunque lo sobreescribo si esque me vuelve llegar)

**Comment by DCCollao** [comment]
Hola @Aloncarrasco! No. No es posible. La issue se refería a la información de la carta, como su color y número, no a su imagen. La imagen de la carta no se debe guardar en el cliente.
