### ISSUE TITLE
Envio de clases 

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#1156]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, estoy tratando de enviar un grafo no dirigido en formato json, por lo que estoy pasando  la clase del grafo  a __dict__ pero no logro poder enviarlo por que dentro de la clase hay otras clases instnciadas json no las puede serilisar. ME podrian dar alguna ayudita o consejo para poder hacer esto plis, llevo demasiado tiempo tratando de hacerlo.

**Comment by matiasmasjuan** [comment]
Hola @diego-ayala-2000 !

Antes que todo, te recomiendo ver la **issue** #1163 ya que trata de un tema similar. Tal como se menciona en esa **issue**, no puedes serializar instancias de **python** mediante **json**, por lo que tendrías dos opciones. La primera es serializar con **pickle** en lugar de **json**. La segunda, en caso de que lo anterior implique modificar en gran medida tu **protocolo de envío** y no quieras hacerlo, es procesar un poco mas la información. Entiendo que envías un grafo, y dentro instancias, pero ¿qué tienen esas instancias?, toda esa información la puedes representar de cualquier otra forma, como una lista con los atributos, o un diccionario. No es estrictamente necesario enviar instancias si sólo vas a necesitar un par de atributos de ella.

Espero que esto te sirva de ayuda, y mucho éxito con la tarea! :smile:
