### ISSUE TITLE
Ver cartas de otros jugadores

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#1157]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! En la sala de juego propuesta en el enunciado, a la derecha hay un rectángulo donde se ven unas cartas. ¿La idea es que todos los jugadores puedan ver cuántas cartas tienen los demás?

**Comment by EduardoIllanes** [comment]
Hola @kalarconvl! La respuesta es si, si te fijas en el enunciado sale que se debe mostrar

> La cantidad de recursos y puntos de victoria de los demás jugadores

Éxito con tu tarea 😄

**Comment by kalarconvl** [comment]
Perfeect gracias!
