### ISSUE TITLE
DCCuatro! requiere algún tipo de aviso?

### ISSUE THREAD

**Issue by benjavicente** [IIC2233/syllabus#1157]
Hola!

En el enunciado y la distribución de puntajes no se menciona la creación de un aviso en el interfaz para indicar cuando un jugador grita DCCuatro.
¿Para la tarea deberíamos implementar algo?

Es raro que los demás clientes no tengan como saber 🤔

**Comment by DCCollao** [comment]
Hola!

Si no se pide ni en enunciado ni en distribución, entonces no es necesario. Aún así, si te motivas a hacerlo para hacer más agradable la interacción del usuario con la aplicación, no hay ningún problema con que lo hagas.

Para que los demás clientes sepan, simplemente se deberían mostrar los cambios en las cantidades de cartas del resto de jugadores, dependiendo del caso.
