### ISSUE TITLE
Cambio de Nombre de archivos // Sprites

### ISSUE THREAD

**Issue by pedroriosg** [IIC2233/syllabus#1158]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!! Quería saber si se puede cambiar el nombre de un archivo de la carpeta de Sprites, en particular, los nombres `choza_roja` y `ciudad_roja` por `choza_rojo` y `ciudad_rojo`, esto para trabajar de manera más fácil la creación de QLabels.

Muchas gracias

**Comment by DCCollao** [comment]
Hola @pedroriosg!

Esta duda fue respondida en la issue #1148. Si te queda alguna duda adicional, hazla en los comentarios de esa issue.
