### ISSUE TITLE
cambio en generador_de_mazos.py

### ISSUE THREAD

**Issue by rieg-ec** [IIC2233/syllabus#1158]
Hola, podría cambiar el nombre de las variables en generador_de_mazos.py sin cambiar la funcionalidad?

**Comment by DCCollao** [comment]
Hola @rieg-ec!

¿Para qué quieres cambiar los nombres de las variables?

**Comment by rieg-ec** [comment]
es que mi programa esta en ingles y siento que pierde armonia si tiene palabras en español metidas xD

**Comment by DCCollao** [comment]
No es la idea que modifiquen ese archivo 😢, solamente debes importarlo y trabajar con él. Si su nombre en español perturba la armonía de tu programa, puedes utilizar el siguiente trucazo:

![image](https://user-images.githubusercontent.com/37167447/85916117-7a144d00-b81b-11ea-8807-0356d3b828f9.png)

Éxito!
