### ISSUE TITLE
Problema cargar todas las ventanas de juego

### ISSUE THREAD

**Issue by jaimecoloma** [IIC2233/syllabus#1159]
Hola! Tengo un problema con el cual he estado lidiando muchisimo tiempo. Es que ya diseñé como cargar las ventanas e iniciar la partida para cada cliente. Se mandan las imagenes serializadas y todo, sin embargo, al momento de cargar las cartas iniciales (de parametro dejé 7 cartas), me pasa que a algunos clientes les carga todas correctamente, a otros casi todas o a veces ninguna, pero el programa no imprime algún error entonces me ha complicado poder resolver el motivo de porqué esto pasa. Ya imprimí que se estén mandando todas y lo que no entiendo es porqué falla a uno o dos clientes y no ha todos. Dejaré mi codigo subido por si acaso :) (linea 172 envia la carta en ```servidor.py```)

**Comment by jitorralba** [comment]
Hola! Lo pudiste resolver? Que tengo exactamente el mismo problema

**Comment by jaimecoloma** [comment]
Creo que si, hice unos cambios y me ha vuelto a funcionar. No estoy 100% seguro de que todavia está bien pero lo que hice fue revisar de nuevo cada envio de parte del servidor y cada recepcion del cliente, creo que habían unos bytes que no se estaban recibiendo y eso desordenaba el flujo del código, o al menos esa es mi teoría. Revisa que cada cosa se lee como estableciste o en el caso de las cartas, como indica el enunciado y que efectivamente estas recibiendo todos los bytes con su uso correspondiende. Ojalá te ayude!

**Comment by jitorralba** [comment]
Buenisima, gracias!

**Comment by mmunoz12** [comment]
Tengo el mismo problema pero he revisado todo y no he podido solucionarlo :( . No sé que podría ser.

**Comment by fdoflorenzano** [comment]
Hola,

Gracias @jaimecoloma por dejar la _issue_ y tu consejo para solucionarlo 👍 

@mmunoz12 ¿Podrías describir un poco tu situación? ¿O es lo mismo que para @jaimecoloma? Si es lo mismo, ¿está en tu repositorio tu código para analizarlo?

Saludos.

**Comment by FelipeLara00** [comment]
Hola, no es exactamente el mismo problema pero tiene que ver con mostrar la ventana de juego. Lo que me pasa es que solo abre una ventana de juego y sin embargo puse un print en la funcion que se encarga de mandar la informacion desde el cliente hacia el front end de la ventana de juego y en todos los jugadores imprime bien.

**Comment by fdoflorenzano** [comment]
@FelipeLara00 si no está relacionada a la _issue_, entonces abre una nueva por favor. También, si lo haces, intenta dar un poco más de información sobre como llamas para abrir las ventanas (a grandes rasgos), y siempre recuerda subir tus avances en caso de que un ayudante pueda mirar tu código directamente.
