### ISSUE TITLE
No funciona mi código en mi computador, pero en otros si

### ISSUE THREAD

**Issue by SantinoDaloy** [IIC2233/syllabus#1159]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, tengo un problema y es que mi código no funciona en mi computador, pero si funciona en otros computadores. Probé desinstalar y reinstalar pyqt5-tools, pero no se me ocurre que otra cosa hacer. Gracias de antemano.

**Comment by Juampisaez** [comment]
Hola @SantinoDaloy 
Te tira algun error? o simplemente no se ejecuta nada (al ejecutarlo en vscode por ejemplo)

Quedo atento :)

**Comment by SantinoDaloy** [comment]
@Juampisaez ya intenté reinstalar pyqt5, python 3.7.8 y pyqt5-tools y ninguna funciona. Y la notebook en la que probé el código y funcionó tiene python 3.8

**Comment by SantinoDaloy** [comment]
@Juampisaez  haciendo más pruebas me dí cuenta que mi código funciona en python 3.8, pero no en python 3.7.8.

**Comment by Juampisaez** [comment]
Hola perdon por no responder antes. La verdad es que dudo mucho que ese sea el problema, tengo python 3.7 y me corre perfecto  tu codigo. Que bueno igual que te este funcionando ahora, investigare un poco mas de la razon por la cual no te funciona.

**Comment by SantinoDaloy** [comment]
Muchas gracias. Haciendo muchas más pruebas, me dí cuenta que si elimino la carpeta de sprites ahí el código accede a todas las funciones. Aun no entiendo bien que hice mal y me gustaría entenderlo, pero igual estoy cambiando la forma de acceder a los sprites para ver si ahora funciona el código.
