### ISSUE TITLE
Variables globales.

### ISSUE THREAD

**Issue by EstebanReyes1998** [IIC2233/syllabus#116]
Buenas tardes, en el enunciado de la Tarea 01 dice que se descontarán decimas por el uso de variables globales. ¿A que se refieren específicamente con eso? Saludos

**Comment by jmwielandt** [comment]
Hola!

Una variable global es una variable que puede ser accedida desde diferentes scopes, tanto para leerla como para escribirla. El uso de este tipo de variables es considerado _en general_ una muy mala práctica por varias razones:

- Hace difícil el _refactoring_. Al ser usada en muchos sitios, es difícil realizar cambios en torno a ella si eventualmente se hace necesario.
- Puede ocultar dependencias. A veces puede pasar que pienses que no la estás usando y la eliminas, pero sí la necesitabas y no sabes dónde.
- Dificulta la lectura del código. Te obliga a entender partes bastante amplias del código para entender el uso de la variable.
- Dificulta la modularización del código.
- Secciones de código pueden tener efectos secundarios difíciles de analizar.
- Entre otras.

En particular dentro del curso, esto es porque va contra toda idea del paradigma de programación orientada a objetos, que es encapsular las variables y métodos dentro de una misma clase especializada que pueda interactuar con otras.

A modo de resumen, lo que se encuentra **prohibido** es:

- uso de la palabra reservada `global`. Keyword para decirle al intérprete que se está haciendo referencia a la variable global.
- uso de `globals()`. Permite acceder a las variables globales del módulo donde es invocado en forma de diccionario.
- uso de `locals()`. Permite acceder a las variables locales del scope donde es invocado en forma de diccionario.
- uso de variables definidas en el scope global dentro de scopes locales y que no sean las de `parametros.py`.
- uso de cualquier estructura de datos o clase mutable con el objetivo de ser referenciada múltiples veces para pasar información entre scopes, en lugar de pasarla mediante argumentos o lectura directa de atributos.
- cualquier otra forma de realizar lo expuesto.

<details>
<summary>Ejemplo de uso de estructuras mutables referenciada varias veces para enviar información ❌  </summary>
<br>

```python

class A:
    def __init__(self, glob):
        self.glob = glob

    def send(self, a):
        self.glob[0] = a

    def recv(self):
        return self.glob[0]


lista_global = [None]

a1 = A(lista_global)
a2 = A(lista_global)

a1.send(3)
print(a2.recv())  # imprime un 3

```

</details>


Saludos!

**Comment by EstebanReyes1998** [comment]
Muchas gracias

**Comment by JuaniAndres** [comment]
hola un pregunta con esto:

> uso de variables definidas en el scope global dentro de scopes locales y que no sean las de parametros.py.

Esto significa que yo puedo llamar a algún parámetro del archivo parametros.py dentro de una función (por ejemplo de alguna formula) de manera global sin sufrir descuentos?

**Comment by jmwielandt** [comment]
Hola @JuaniAndres !

Exacto! Eso se puede.

Saludos~
