### ISSUE TITLE
Error al probar 'ciclo mas corto' en main.py

### ISSUE THREAD

**Issue by agustinvaldesz** [IIC2233/Syllabus#116]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Me paso que al probar los test cases de la funcion ciclo_mas_corto me salieron todos con ok, sin embargo, al llamar la función en el archivo main.py me aparece un error relacionado a la funcion y especificamente al archivo dcciudad.py al que como no tenemos acceso no puedo ver en que se contradicen.

**mi duda principal es, si los test cases me salieron todos ok es posible que todavía hayan errores en como se definió la función en un principio**

pd: hice git push de mi código por si requieren verlo.

**Comment by agustinvaldesz** [comment]
Agrego que el mismo error ocurre cuando ocupo asegurar_rutas en el menu, dandome el siguiente error: File "C:\Users\Agustín Valdés Z\OneDrive - uc.cl\Escritorio\Practica\agustinvaldesz-iic2233-2024-1\Tareas\T1\red.py", line 187, in asegurar_ruta
    matriz_elevada1 = dcciudad.elevar_matriz(matriz_copia, 2)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "dcciudad.py", line 51, in elevar_matriz
  File "dcciudad.py", line 42, in multiplicar_matriz
TypeError: unsupported operand type(s) for +=: 'int' and 'str'

**Comment by IanZmen** [comment]
Hola, creo que tu duda la responde la issue #78 ... Si hay algo que no quede claro no dudes en comentármelo. Éxito
