### ISSUE TITLE
Porcentaje de extincion

### ISSUE THREAD

**Issue by mguerreromir** [IIC2233/Syllabus#116]
En el enunciado se dice que cuando se consulta un incendio se debe mostrar el porcentaje de extincion de este. El porcentaje de extincion se define como la razon entre los puntos de poder que han sido extintos por los recursos y los puntos de poder del incendio desde que se inicio.
Mi pregunta es como calculo los puntos de poder del incendio cuando este se inicia si al momento de iniciarse el radio de este es cero (en el csv solo dan el foco del incendio) y los puntos de poder se calculan en funcion del radio.

**Comment by akaminetzkyp** [comment]
Quizás se refiere desde que se comenzó a apagar el incendio.

Saludos!

**Comment by chuma9615** [comment]
Yo para resolver ese problema asumi que el radio al inicio del incendio era 1, ya que en ninguna parte se especifica el radio al comenzar el incendio

**Comment by iqacevedo** [comment]
Hola 
Como dice tu compañero @chuma9615 , puedes asumir tu el radio inicial de tal manera de que el problema tenga sentido (no olvides anotar en el README el radio que asumiste).
Además, para el cálculo de los puntos de poder se consideran los puntos de poder acumulados desde que el incendió empezó (no los inciales).

Saludos !
