### ISSUE TITLE
Dudas de enunciado

### ISSUE THREAD

**Issue by iastruque** [IIC2233/syllabus#116]
Tengo varias dudas técnicas respecto al enunciado de la T00:
1.- Si estoy en el menú de seguidores y decido volver al menú anterior ¿Tengo que ir al menú inicio con la sesión iniciada o tengo que partir como en le comienzo del programa (sin ninguno usuario iniciado)?
2.- Tengo la misma duda con el menú de prograposts, es decir, que debe para cuando marco la opción [5]?
3.- la opción salir significa que deje de correr el programa?

**Comment by MatiasDuhalde** [comment]
Hola! 

Como se especificó en la issue #90, _todo lo que no esté especificado explícitamente en el enunciado queda a tu libre diseño_, pero siempre es importante (y nos ayuda a corregir) que indiques qué hiciste y porqué tomaste esa decisión en tu archivo `README.md`. Te recomiendo revisar la issue que indiqué, debería cubrir los tres puntos que pusiste en tu pregunta.

✌️

**Comment by KnowYourselves** [comment]
Hola @iastruque!

Para complementar la respuesta de @MatiasDuhalde, si es que tienes múltiples preguntas es preferible que hagas una _issue_ por pregunta con un título descriptivo para cada una.

Gracias!
