### ISSUE TITLE
Creación de properties por el mismo comportamiento

### ISSUE THREAD

**Issue by ribik20** [IIC2233/Syllabus#116]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

¿Cómo puedo definir muchas ```properties``` con valor entero, valor máximo y mínimo para una clase sin tener que utilizar tres ```if``` por cada propiedad? Si lo hago como se muestra en los contenidos, se repite el mismo código para cada propiedad.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by MrNachoX** [comment]
Hola @ribik20! no hay problema en utilizar varios ifs en las properties tal como sale en en los contenidos.
Si quieres hacerlo de otra forma podrías definir algún tipo de función para reutilizar el código varias veces, pero repito que esto no es necesario y está bien hacerlo como sale en los contenidos.
