### ISSUE TITLE
Implementación diferente de una parte de la tarea

### ISSUE THREAD

**Issue by juanesjeep** [IIC2233/syllabus#116]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Puedo hacer que cirto input se entrege de manera diferente 

me a por ejemplo la parte de Crear grupo te piden que se ingresen los usuarios de esta manera (usuario1;usuario2;usuario3...)
¿puedo crear algun tipo de "menu de seleccion" para que sea mas "intuitivo" el seleccionar los usuarios aunque se salga del input que estipularon en el enunciado si lo dejo definido y explicado en el README.md ?

**Comment by Tsbalart** [comment]
Hola @juanesjeep! Puedes hacerlo siempre y cuando lo especifiques claramente en el readme y  los grupos se guarden de la manera solicitada en los archivos csv, recuerda que los ayudantes usaremos nuestros propios archivos para corregir, por lo que debes respetar el formato indicado. Espero que haya quedado claro! Éxito con la tarea!

**Comment by Tsbalart** [comment]
Hola @juanesjeep! Para evitar complicaciones del ayudante que corrija tu tarea y posibles descuentos, es mejor que las cosas especificadas en el enunciado las sigas como estan. Por lo que te aconsejo que los inputs solicitados de cierta forma los realices de la forma solicitada, pero muy bien la iniciativa! Éxito con la tarea!
