### ISSUE TITLE
soldados

### ISSUE THREAD

**Issue by isihirmas** [IIC2233/syllabus#116]
Hola! Los soldados al igual que los trabajadores cuando atacan también cambian de disponibles a ocupados? Y si ataco a otra civilización, asumo que todos mis soldados pasan a estar ocupados?

**Comment by gatochico** [comment]
Hola! Los soldados se consideran ocupados durante el turno que atacan y cuando atacas a una civilización, envias a todos los soldados, por lo que __todos__ pasan a estar ocupados. Saludos! :cat:
