### ISSUE TITLE
Instanciar clase

### ISSUE THREAD

**Issue by julioag** [IIC2233/Syllabus#116]
Estuve tratando de instanciar una clase con un string pero no pude, existe algna forma de cambiar el string a un nonetype??
Gracias.

**Comment by nmaturana97** [comment]
Podrias dar mas detalle de lo que estas intentando hacer?
Te recomiendo siempre dar un ejemplo para que podamos entender bien lo que estas intentando hacer

**Comment by julioag** [comment]
ok, acá esta el ejemplo:
![image](https://user-images.githubusercontent.com/26441194/38117418-334e301e-338b-11e8-86ef-c563f7880ad1.png)

Lo que quiero hacer es instanciar la clase Galaxia pero no puedo porque nombre_galaxia es un string pero necesito instanciar la clase con el nombre del string (nombre_galaxia ="andromeda" y quiero instanciar la clase de la forma andromeda= Galaxia(...)). Se entiende mejor??

**Comment by jmwielandt** [comment]
No soy ayudante pero... no puedes (no solo tú, no se puede en general, nunca, bajo ningún concepto) crear una variable a través de un string. Para eso están las estructuras de datos, busca alguna que te sirva para ese propósito.
Eso~

**Comment by Pipelao** [comment]
Hola!
Te recomiendo que coloques como atributo de la clase Galaxia el nombre de esta y se lo entregues como argumento de manera que lo puedas llamar.
PD: No soy ayudante.
Saludos
