### ISSUE TITLE
readlines() no lee tildes?

### ISSUE THREAD

**Issue by jpsiegel** [IIC2233/Syllabus#116]
tengo el siguiente error al leer user.csv
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 625: character maps to <undefined>
asumo que es porque en el csv de users hay nombres con tildes, al parecer la posicion 625 calza con un "í" que quizas no puede ser leido por la funcion .readlines()
que se puede hacer?

**Comment by GustavPrudencio** [comment]
la función open recibe un argumento dedicado a la codificación del archivo, basta hacer open(virus.exe,'r',encoding='utf-8') use utf-8 pero puede que necesites otro
