### ISSUE TITLE
Pregunta sobre parametros celestes en las formulas

### ISSUE THREAD

**Issue by juacob** [IIC2233/Syllabus#116]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola en el issue #112 se dijo que se deben escribir los parametros celestes que aparecen en las formulas en el archivo parametros.py, es esto completamente necesario? siento que lo unico que hara es complejizar el codigo, teniendo que inventar un nombre distinto para cada uno al mismo tiempo que se intenta que sean nombres descriptivos. Me parece mucho mas facil ver que en la formula hay un 0.15 por ejemplo en vez de un MULTIPLICA_SUERTE_EN_PROBABILIDAD_GANAR_JUGADOR.

**Comment by antoniablanco** [comment]
Si, es necesario. Aunque en este caso ustedes ya conocen los valores por que son entregados en el enunciado. El trasfondo de que creen el archivo parametro, es que en otros proyectos ustedes tendran que crear sus parametro. Y tenerlos en un archivo separado es más facil para poder buscarlos y cambiarlos. Por que se puede dar que el mismo parametro este en distintas partes del codigo, cambiarlo en un archivo es más facil que  en todos los lugares donde se uso.

**Comment by juacob** [comment]
> Si, es necesario. Aunque en este caso ustedes ya conocen los valores por que son entregados en el enunciado. El trasfondo de que creen el archivo parametro, es que en otros proyectos ustedes tendran que crear sus parametro. Y tenerlos en un archivo separado es más facil para poder buscarlos y cambiarlos. Por que se puede dar que el mismo parametro este en distintas partes del codigo, cambiarlo en un archivo es más facil que en todos los lugares donde se uso.

Hola perdona de nuevo pero acabo de revisar el enunciado y no dice que todos los numeros que esten en celeste se deben definir en parametros, si no que los que sean celestes y esten escritos en el enunciado con el formato PARAMETRO_ALGO. Creo que no me di a entender, por lo que te queria preguntar de nuevo. Adjunto fotos para hacerlo mas claro, segun las fotos habria que poner en parametros el parametro PROBABILIDAD_EVENTO pero no el 15 que esta en la formula cierto?

<img width="481" alt="evento" src="https://user-images.githubusercontent.com/89426673/162838414-191c9646-5b83-4feb-8c74-cf3b561c52e1.PNG">
<img width="474" alt="formula" src="https://user-images.githubusercontent.com/89426673/162838416-e3375533-0c32-45bc-9f01-03a51880b9ba.PNG">
<img width="471" alt="parametro" src="https://user-images.githubusercontent.com/89426673/162838417-611df354-64a2-49df-a58c-ec65e9bfef0c.PNG">

**Comment by antoniablanco** [comment]
También deben estar en el archivo parametros

**Comment by M4rtinL4gies** [comment]
Perdón por insistir, pero la verdad es que no me queda claro que realmente sea necesario hacer lo anterior. Según el enunciado, las variables representadas con palabras con el formato ESTE_FORMATO, deben ser agregadas como parámetros. De tener que poner los números como parámetros, ¿no estarían también escritos en el enunciado con ese formato? Lo que digo es que en las fórmulas, en vez de números, tendrían que estar los nombres de los parámetros. Lo que el enunciado da a entender es que los pesos en las fórmulas se expresan simplemente como números.

**Comment by antoniablanco** [comment]
Pregunte tu duda con los ayudantes coordinadores y me dijieron que todo lo que este en azul es un parametro que debe estar en el archivo, te recomiendo cumplirlo para que no pierdas puntaje.
