### ISSUE TITLE
test solucionar no funciona bien

### ISSUE THREAD

**Issue by CrisHD935** [IIC2233/Syllabus#116]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Me pasa que los tests solucionar no funcionan si corro el archivo original con los tests pero si corro individualmente solo uno de los tests en un archivo aparte me funciona bien, y de hecho si hago los casos de manera aparte en otro archivo me da lo que me piden, pero dentro de los tests no funciona. Que podria causar esto??

<img width="609" alt="Captura de pantalla 2023-08-29 162714" src="https://github.com/IIC2233/Syllabus/assets/133688044/d74bd574-9e63-4511-8959-6914f921788d">
<img width="595" alt="Captura de pantalla 2023-08-29 162749" src="https://github.com/IIC2233/Syllabus/assets/133688044/a9a29bc7-4a4c-46a7-a6b1-5f6bc9c18b74">

**Comment by Hernan4444** [comment]
Hola @CrisHD935 

Lo más probable es que la ejecución de tu "solución" hace que algúna variable global sea editada y no has dado cuenta. Un caso típico de esto es cuando usamos listas como argumentos por defecto en una lista. Por ejemplo

```python3
def f(x=[]):
    x.append(1)
    return x

print(f())
print(f([2,2]))
print(f())
```

Tal vez lo que uno esperaría es que los print fueran:
```python
[1]
[2, 2, 1]
[1]
```
Pero la verdad, es que los print serán 
```python
[1]
[2, 2, 1]
[1, 1]
```
Esto es porque una lista no debe ser un valor por defecto, dado que cada vez que se ejecute la función y no se le entrege un argumento, se llamará a la misma lista, no a una nueva. Por lo tanto, la segunda vez que hacemos `f()` en vez de hacerle `append(1)` a la lista vacía, será un `append(1)` a la lista que ya tiene un `[1]`.

Si no estás haciendo nada como lo mencionado anteriormente, te recomiendo subir tu código a tu repositorio para que el cuerpo docente pueda echarle un ojo,

Saludosヾ(＾-＾)ノ

**Comment by CrisHD935** [comment]
Hola. Tenia algo asi en mi codigo asi que efectivamente era eso lo que causaba error. Gracias!
