### ISSUE TITLE
se me cambio de .py a .pyc en los tests publicos

### ISSUE THREAD

**Issue by JoseManuel396** [IIC2233/Syllabus#116]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, al meterme hoy dia a programar intente correr los tests publicos los que anteriormente si habia podido correr varias veces durante esta semana y me funcionaban sin ningun problema, pero al correrlos hoy dia la terminal no me reconocia los tests publicos y se debia a que todos mis tests publicos pasaron de ser .py a ser .pyc. ¿¿Saben como puede haber pasado esto y como lo podria arreglar??, porque mientras no se me arregle no puedo avanzar ya que no puedo correr los tests.

**Comment by FernandoTFH** [comment]
Creo que mejor no te compliques con arreglar los test, solo borrarlos y descargalos de nuevo. Y sobre como paso dejame buscar un poco mas del tema, porque lo único que se me ocurre es que el comando para ejecutar los test sea parecido al de compilarlo.
