### ISSUE TITLE
Duda enviar mensaje

### ISSUE THREAD

**Issue by jorgetf-desing** [IIC2233/syllabus#1160]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo un problema con el envío y recibo de datos a través de los sockets. Lo que pasa según el protocolo establecido, a mi me piden enviar el largo del mensaje en formato Big Endian, el número de bloque en Little Endian, y supongo que el contenido del mensaje en UTF-8. El problema es que según entiendo se envían cada uno de estos mensajes por separado, es decir, realizar un "send" para el largo, un "send" para el n° de bloque y un "send" para el mensaje, correcto? El problema es que los mensajes al ser enviados así, se mezclan al llegar, supongo que porque el buffer máximo es de 60, y al no llegar a 60 bytes seguirá recibiendo mensajes como uno solo, a menos que haya un pequeño delay de 1 segundo entre cada mensaje, y eso me está complicando en gran medida. Una solución que se me ocurre es enviar todo en un mismo mensaje, algo así como enviar el largo del mensaje total, el numero de bloque y el mensaje en sí como un mismo mensaje unido, y así evitar los problemas de recibo antes mencionados, pero ¿es válido hacer esto? 

Gracias de antemano y saludos!

**Comment by matiasmasjuan** [comment]
Hola @jorgetf-desing !

La primera forma que señalas es una manera **correcta** de realizar el envío. Sin embargo, me parece sumanente extraño que los mensajes se **mezclen** al llegar, ya que al ser un protocolo **TCP**, no debería ocurrir. Si crees que eso es el problema, podrías utilizar el número de bloque para ordenar los mensajes (por lo que tendrías que enviar el mensaje con su bloque juntos) aunque dudo que ese sea el problema.

Con respecto a lo segundo que mencionas, **no es posible en la práctica enviar todo junto**. Esto se debe a una razón sencilla: la idea del protocolo es que la información que se **envía** debe ser **igual** a la que se **recibe**. De lo contrario, ocurrirán errores. Por ejemplo, si el servidor envía el **largo** del mensaje, el cliente debe estar preparado para que en ese mismo instante reciba ese largo, y lo mismo sucede con los bloques de 4 *bytes* y los mensajes de 60 *bytes*. El problema de enviar todo junto, es que **no sabes** **cuántos** *bytes* vas a enviar, y por consecuencia, el receptor **no va a saber** cuántos **recibir**. Esto generaría una inconsistencia en el **protocolo** y por ende no estarías cumpliendo lo solicitado para esta tarea.

En base a lo anterior, lo mas probable es que tu error se deba a que no estás realizando el mismo protocolo de envío que el que recibe. La idea es que ambos procesos calzen para que se envían y reciban la misma cantidad de *bytes*.

Espero haber respondido a tu pregunta, y mucho éxito con la tarea! :smile:

**Comment by jorgetf-desing** [comment]
Gracias por la respuesta!!!!!!
