### ISSUE TITLE
mecanicas DCCuatro robar cartas

### ISSUE THREAD

**Issue by rieg-ec** [IIC2233/syllabus#1160]
Hola!, no me quedan claras las mecanicas del DCCuatro, porque en el enunciado en **3.3 Robar Cartas del mazo**  se especifica *un jugador puede decidir robar cartas siempre y cuando no haya jugado una carta en el mismo turno, porque luego de jugar una carta el turno termina automáticamente*, pero un poco mas abajo también sale *Como regla general, cuando un jugador roba una o multiples cartas del mazo, independiente del motivo, su turno termina automáticamente*. 

Mi idea es hacerlo como el UNO de toda la vida y que el turno acabe cuando uno tira una carta (o si no hay ninguna disponible, cuando robas) y antes de eso uno puede o no robar 1 carta, salvo que te hayan tirado un +2, que en ese caso solo se puede robar y pasar o tirar otro encima. Esta bien? (lo especificare en el README igual)

**Comment by DCCollao** [comment]
Hola @rieg-ec!

Lamentablemente no puedes hacerlo de esa forma :( pues en la distribución de puntajes se detalla lo siguiente:
![image](https://user-images.githubusercontent.com/37167447/85917636-d2eae200-b829-11ea-9bb4-e097e1759b43.png)

Lo que choca con la idea de poder robar y además jugar una carta en el mismo turno. En todo caso, si deseas agregar esa funcionalidad para hacerlo más jugable para ti, podrías agregar una [QCheckBox](https://doc.qt.io/qt-5/qcheckbox.html) que permita activar y desactivar esas reglas _custom_, además de mencionar en tu readme que añadiste esa funcionalidad, y así no te perjudique en la nota!

**Comment by rieg-ec** [comment]
ah ya, o sea las opciones son jugar una carta o robar una, pero nunca las dos en un turno. Esa era mi duda en realidad, gracias!
