### ISSUE TITLE
Asignar choza de forma aleatoria

### ISSUE THREAD

**Issue by n4chin** [IIC2233/syllabus#1161]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado de la tarea, sección 4.2.2 dice ". Luego, por cada jugador el servidor deberá ubicar de forma aleatoria en el mapa 2 chozas y 2 carreteras". ¿Es realmente necesario que sea así? ¿No puedo decirle al servidor que envíe un mensaje al cliente tal que de esta forma se haga todo aleatorio? Así para no cargar el grafo en server.

**Comment by EduardoIllanes** [comment]
Hola @n4chin! La respuesta es **si, tiene que ser así** ya que se evaluara una correcta arquitectura cliente-servidor y que el servidor cumpla con sus responsabilidades correspondientes, entre ellas la que mencionas. Saludos y éxito en tu tarea 😄
