### ISSUE TITLE
Limite de jugadores

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2233/syllabus#1162]
Existe un limite de jugadores por partida?
De la forma en que diseñe mi interfaz se ven bien hasta 8 jugadores, ¿debo extenderlo para más jugadores?
y si es que debo extenderlo, ¿para cuantos entonces?
y pasa algo similar con las cartas, ¿hay un limite?

**Comment by gatochico** [comment]
Hola! En el enunciado indica que la cantidad de jugadores variará siempre entre **2 y 4** jugadores, variables manejada por un parámetro.

Respecto a las cartas, se indica también que un jugador pierde cuando las cartas en su mano sobrepasan las 10, por lo que deberías poder soportar las 10 cartas que pueda tener el jugador en la mano como mínimo.

Saludos!
