### ISSUE TITLE
ConnectionAbortedError: [WinError 10053] Se ha anulado una conexi?n establecida por el software en su equipo host

### ISSUE THREAD

**Issue by ignaciovilla** [IIC2233/syllabus#1162]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
Hola, cuando intento conectar una ventana cliente con el servidor me aparece este error: 
ConnectionAbortedError: [WinError 10053] Se ha anulado una conexi?n establecida por el software en su equipo host
y no logro encontrar el problema ni la solución en internet. ¿Qué puede ser?
Muchas gracias

**Comment by Juampisaez** [comment]
Hola @ignaciovilla 
Puede que tal vez te entienda mal, quieres conectar el servidor con una ventana cliente, sin una clase cliente? Si puedes hacer git push a github mejor aun.

Quedo atento :)

**Comment by ignaciovilla** [comment]
Hola, nono, lo que estoy haciendo es lo siguiente, abro el servidor en un terminal, y en otro terminal diferente abro el cliente, pero este no alcanza a conectarse con el servidor porque me levanta ese error. El servidor y cliente tienen sus clases diferentes en diferentes carpetas tal cual como pide el enunciado. 
Hago ahora el push, muchas gracias!

**Comment by Juampisaez** [comment]
Ya, estuve viendolo mas detenidamente y me di cuenta que al hacer sacar el `daemon = True` del thread escuchar_al_servidor, funciona bien al parecer. No me salio de nuevo el error que comentas, prueba haciendo lo que te dije, maneja un poco los nombre y las instancias y dime si sigue habiendo problemas.

Quedo atento

**Comment by ignaciovilla** [comment]
Borre lo que me dijiste y ahora funciona, muchas gracias!
