### ISSUE TITLE
Como JSON serializar una clase propia

### ISSUE THREAD

**Issue by TMagini** [IIC2233/syllabus#1163]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Me pasa que cree la clase `Node` y `Hexagon` he instancio ambas en el archivo lógica, en donde después le mando esta información a todos los clientes para que armen la misma grilla con los mismos nodos y hexágonos, el problema es que el servidor me manda un error diciendo `TypeError: Object of type Hexagon is not JSON serializable`, ya que el mensaje contiene una lista de instancias `Hexagon`.

**Comment by matiasmasjuan** [comment]
Hola @TMagini !

**JSON NO permite** serializar un objeto **python**. Lo que puedes hacer es **personalizar** la serialización. Para eso, te recomiendo revisar los [Contenidos semana 13-serializacion](https://github.com/IIC2233/contenidos/blob/master/semana-13/2-serializaci%C3%B3n.ipynb). Por otro lado, si necesitas enviar instancias, deberás hacerlo con **pickle**, y no con json. En la siguiente sección [Contenidos semana 14-ejemplos](https://github.com/IIC2233/contenidos/blob/master/semana-14/3-ejemplos.ipynb) se muestran ejemplos concretos de cómo realizarlo. De todas formas, si crees que esto podría alterar en **gran medida** el **protocolo de envío** de mensajes que hayas realizado, siempre puedes procesar un poco mas la información antes de enviarla. Por ejemplo, en lugar de enviar las instancias, puedes enviar **solo** la informacion que necesitas de cada una de las instancias de forma separada. (diccionarios o listas te podrían servir en ese caso).

Saludos y mucho éxito con la tarea! :smile:
