### ISSUE TITLE
Número máximo de cartas

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#1163]
Hola, leyendo issues sobre el tema, se da a entender que el número máximo de cartas es 10 y que esto no cambia, pero mi pregunta es, como este valor se debe incluir como parámetro, el/la ayudante va a modificar este valor? Mi pregunta es porque mi interfaz gráfica está hecha como se indica en la #1043, es decir, son 10 espacios de QLabels vacíos por jugador y estos se muestra o esconden, dependiendo de las cartas que tenga cada uno, por lo que mi interfaz soporta hasta 10 cartas por jugador, entonces si se cambia este parámetro, digamos a 12, no se podrán mostrar estas 12 cartas en la interfaz.

**Comment by lily416** [comment]
Lo ideal es que el parámetro se pueda modificar por un número menor a 10, para que así pueda facilitar la corrección de los ítems relacionados.

Además, puede asumir que si se cambia el valor, nunca será mayor a 10, porque podría tener efectos en las interfaces, y por lo mismo, en la corrección de sus tareas.

Pese a esto, puede poner como un supuesto que ese parámetro se mantendrá constante durante toda la corrección de tu tarea y citar esta issue.

Saludos y éxito en la tarea 👋🃏
