### ISSUE TITLE
[Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by alanpiket** [IIC2233/syllabus#1164]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Me aparece este error en el termina y no se por que sucede. Trate de buscar y no encontré.

**Comment by aaossa** [comment]
Hola @alanpiket , ¿pudiste solucionar tu problema? Hay otras *issues* con la misma duda (tendrías que buscar `10054`, que es el número de error en Windows), por lo que si no lo has resuelto podrías ver si alguna respuesta de ahí te sirve. De todas maneras, cuéntame si pudiste solucionarlo o no 🙌 ¡Éxito con la tarea ✨!
