### ISSUE TITLE
Referencia a código obtenido de Contenidos

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#1164]
Hola, quería saber si es que ocupo código de los notebooks de  Contenidos del curso debo referenciarlos en el README? Lo digo porque si se ocupa un programa de detección de copia, puede que de positivo, ya que supongo que varios/as han hecho lo mismo con códigos del curso.

**Comment by jirarrazabal** [comment]
Hola! Si, debes señalarlo en tu README en la sección correspondiente a las referencias, junto a las líneas y el módulo donde utilizaste este código. Suerte!
