### ISSUE TITLE
Problema con setIcon para PushButton

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2233/syllabus#1165]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)

### Duda

Hola! estaba tratando de set un icono para los botones de la interfaz gráfica con setIcon, pero ve buscado en todas partes y de ninguna forma me funciona :(

**Comment by matiasmasjuan** [comment]
Hola @conyfernandezt !

El proceso es **muy parecido** que el de realizar un **setPixmap** para un **Qlabel**, con la única diferencia en que ahora se utiliza **QIcon**. A continuación se muestra un ejemplo:

```python
from PyQt5.QtWidgets import QPushButton
from PyQt5.QtCore import QSize
from PyQt5.QtGui import QIcon

self.boton_imagen = QPushButton(self) # Se crea el boton que tendrá el ícono.
self.boton_imagen.setGeometry(700, 100, 195, 273) # Se defines las coordenadas que quieras
self.boton_imagen.setIcon(QIcon('mi_imagen.png')) # Le defines un ícono con QIcon, seleccionando el path de la imagen
self.boton_imagen.setIconSize(QSize(197, 275)) # Opcional, puedes agrandar o disminuir el tamaño del ícono
```

Espero que esto te sirva de ayuda, cualquier duda me avisas! :smile:

**Comment by conyfernandezt** [comment]
Hola! Habia probado con eso, pero directamente con el boton creado de Qtdesigner. Deberia funcionar igual o no?

**Comment by matiasmasjuan** [comment]
Entonces el proceso es mucho mas sencillo! 

**Pasos**
1. **Crear el botón**
![paso1](https://user-images.githubusercontent.com/48495638/100670255-5fe81900-333d-11eb-83c0-38f83310172c.png)

2. **Ir a Stylesheets**

![paso2](https://user-images.githubusercontent.com/48495638/100670353-7f7f4180-333d-11eb-8efc-da2aeb9d5383.png)

3. **Hacer click en la flecha hacia abajo de Icon: Choose file**

![paso3](https://user-images.githubusercontent.com/48495638/100670433-99208900-333d-11eb-8f0b-b260aa9b8f31.png)

4. **Opcional: cambiar el tamaño**

![paso4](https://user-images.githubusercontent.com/48495638/100670455-a5a4e180-333d-11eb-918c-c1da0a8f71e0.png)

5. **Ver resultados**

![paso5](https://user-images.githubusercontent.com/48495638/100670480-afc6e000-333d-11eb-86ef-21e279cb6ac6.png)

Saludos! :smile:

**Comment by conyfernandezt** [comment]
Hola! Sii, lo hice asi, pero lo queria cambiar en un caso especial y ahi es cuando no me funcionaba. Se pueden cambiar? O una vez que lo creas asi, no hay como modificarlo?
Quedo atenta a tu respuestas,
Muchas gracias

**Comment by matiasmasjuan** [comment]
Tal como mencioné antes, **sí**, lo puedes cambiar. Basta con cambiar el **QIcon** y listo.

```python
self.boton_imagen.setIcon(QIcon('nueva_imagen.png'))
```
Con eso ya cambiarías la imagen del QPushButton.

Saludos! :smile:

**Comment by conyfernandezt** [comment]
Ahi me funciono! Muchas gracias :)
