### ISSUE TITLE
modelamiento de parametros.json

### ISSUE THREAD

**Issue by sebaelsaca** [IIC2233/syllabus#1165]
En el archivo parametros del servidor hay que guardar todos los id_imagen, nombre de colores, id_color y ese tipo de cosas o no es necesario? Que he construido todo sin parametros todavía y quiero saber que incluir dentro de tal archivo.

**Comment by gatochico** [comment]
Hola!

Como mínimo, tienen que estar los parametros que pide el enunciado (recuerda que están marcados con azul en el enunciado), tales como `Host`,`Port`,etc... Estos mínimos son los que se evaluarán en el ítem de parámetros.

Ahora, teniendo ya eso, puedes agregar cosas que tu creas sean importantes parametrizar (y así puedas tener un fácil acceso a ellas o modificarlas si es necesario): por ejemplo, las rutas a sprites o archivos. 

Saludos!

**Comment by sebaelsaca** [comment]
Gracias!
