### ISSUE TITLE
robar cartas

### ISSUE THREAD

**Issue by rieg-ec** [IIC2233/syllabus#1166]
Hola, en una issue anterior dijeron que solo se puede robar o jugar una carta en un turno, pero que sucede si me tiran un +2 al cual yo le puedo tirar otro +2 encima, pero supongamos que no tengo ninguno y al robar la primera carta me sale un +2, puedo tirarlo o si ya robe una tengo que seguir robando y pasar?

**Comment by szabala** [comment]
Hola! Como se explica en la sección de **cartas especiales**, si a un jugador le tiran un más dos y no tiene otro en su mano, este roba la cantidad acumulada de cartas y su turno termina automáticamente (sin importa que cartas robe).
Espero haber aclarado tu duda :smile:
