### ISSUE TITLE
Hint de cómo hacer el tablero por favorrrrr

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#1166]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Estoy en la parte de armar el tablero y entiendo que el servidor tiene que crear la grilla (con ```generador_grilla.py```) y esta nos entrega posiciones donde se ponen los nodos y que los parámetros de ```grafo.json``` indican 
cuáles nodos pertenecen a qué hexágono y cuáles son vecinos. Mi tema está en llevar todo esto a la interfaz gráfica. Primero, **¿el servidor sólo genera la grilla, los nodos y los hexágonos y le entrega esa información a la interfaz para que la interfaz se encargue de crear el tablero?** Y lo otro **¿cómo se representan los nodos en la interfaz?** Las imagenes son hexagonales, por lo que no puedo tomar las esquinas de "manera ordenada" como en un cuadrado o rectángulo. Ni siquiera se cómo preguntar. como que no se por dónde partir 😭

**Comment by kalarconvl** [comment]
Adicional a esto, ¿para poner las chozas hay que usar drag and drop? Porque no lo logré bien en la T02. ¿Podría hacerlo poniendo botones en cada nodo?

**Comment by pvcortes** [comment]
Pta estoy igual y me parece que la forma de resolverlo es la siguiente:

1) Notar que el hexágono i queda definido de la forma: [a, b, c, d, e, f] donde las letras son los índices de los nodos y estos vienen ordenados (espacialmente hablando) de izquierda a derecha y de arriba hacia abajo
2) Obtener entonces con el módulo generar_grilla.py las ubicaciones pertinentes de los nodos según la configuración de la interfaz
3) Tomar las ubicaciones de los nodos a y c del hexágono i-ésimo. Y sean estas (a_x, a_y) y (c_x, c_y) respectivamente, se tiene que la esquina superior derecha de la imagen cuadrada que contiene al hexágono en cuestión (según el tipo de materia prima asociada) viene dada por (c_x, a_y).
4) De forma análoga la esquina inferior derecha del cuadrado vendría dada por la tupla (d_x, f_y), con esto se puede definir el setGeometry de cada label para cada hexágono

Ahora bien, si alguien pudiera jugársela y decir si hay una forma de definir todos los hexágonos en un for loop, o apendear las imágenes (QLabels) a un diccionario y luego tirarle algún tipo de show() a todas sería fantástico. Dado que es un poco rústico, espacioso e ineficiente repetir este procedimiento 9 veces, no parece tener ningún sentido, otra idea sería tal vez ver la posibilidad de utilizar layouts, pero un gridlayout trata de forma disjunta el dominio de las imágenes hasta donde entiendo, y tampoco sé si utilizar layouts horizontales permite solaparlos luego en un layout vertical, depronto haciendo uso de addStretch negativo o algo asi, pero no estoy seguro, ojalá alguien cache y lo comparta, es muy frustrante perder el tiempo en esto con la carga actual del semestre.

saludos!

**Comment by kalarconvl** [comment]
Buenisima ideaaa y si! Muy fome repetirlo tantas veces con todos los hexágonos. Muchaas gracias! @pvcortes
