### ISSUE TITLE
Bug Pyqt5, Designer

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#1167]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, tengo un bug en mi código, que también tuve en la tarea 2, que me tira en consola el siguiente mensaje.
QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 255, 255, 255, 0%'
antes no le tome mucha atención ya que no molestaba tanto, pero ahora para debbugear no es comodo,ademas de que ns si interfiere con mi codigo., si me pueden ayudar plox.
en esta pagina encontré info pero no logre sacarlo
https://bugs.launchpad.net/calibre/+bug/1834989
se que es un bug con el designer, pero no se exactamente que parámetro del stylesheet.
hice un push por si me pueden ayudar je.

**Comment by DasVaca** [comment]
Hola! rgb es para darle los 3 colores (red, green, blue), rgba es para los 3 colores + alpha (red, green, blue, alpha), por lo tanto debes usar rgba. 
Comenta si funca ahora :eyes:.

**Comment by sa-Appel** [comment]
Hola!, le probé manual en el designer con 1 label, y me funco! Gracias ( si a alguien mas le pasa hay que poner un alpha, no dejarlo como 0.
pq ocurre este error? si cuando le seteo el stylesheet lo pongo con las herramientas del qt, en add backgroundcolor, tengo que cambiar como 60 labels manuales asique lo dejare para la hora poto
