### ISSUE TITLE
error en la ruta de la imagen

### ISSUE THREAD

**Issue by Mario-uc** [IIC2233/syllabus#1167]
cuando intento leer un archivo como "rb" la ruta sale que no existe  (No such file or directory: 'sprites\\pokemon\\4_verde.png') (sale con doble slash eso si, no sé por que se coloca, porque cuando uno hace print se muestra solo uno). ¿Que puede ser?

editado: He hecho otro programa que esta ubicado en el mismo lugar que el programa del servidor y en este si me abre el archivo :/ pero no veo la diferencia

**Comment by gatochico** [comment]
Hola! Cómo estás escribiendo la ruta? Con os.path.join() o escribiendo la ruta completa con un string? Otra duda, estás corriendo tu tarea desde el directorio correcto para que funcionen los paths relativos? 

Quedo atenta!

**Comment by Mario-uc** [comment]
Os.path join y la parte del archivo lo hice con format, es decir , la parte de ''4_verde.png''. Y con respecto al directorio, el main, el servidor y la carpeta de sprites estan en la misma carpeta.

**Comment by gatochico** [comment]
Puedes subir tu avance a tu repositorio para revisar los paths?

**Comment by Mario-uc** [comment]
Listo

**Comment by gatochico** [comment]
Hola! Acabo de leer tu código, ¿El error ocurre desde el lado del servidor o del cliente? Porque por lo que veo el servidor no lanza el error mientras que el cliente sí. Esto puede deberse a que cuando estas escribiendo la carta en el cliente, estas al mismo tiempo definiendo en el path un directorio que no está. Al contrario de con los archivos, los directorios no se crean solos si es que no existen, por lo que primero deberías crearlo (`os` tiene funciones para ello) y luego crear el archivo.

De todos modos, como tip, recuerda que el cliente no debe almacenar las cartas como archivo en ningún momento, sino que trabajar con los bytes de forma directa.

Por último, el doble backslash que te aparece es debido a que `\` es un caracter especial, y para que este se printee bien en el mensaje de error se le antepone otro `\`. Esto no afecta tu código y es la misma razón por la que cuando haces `print` directo sale con un solo `\` (En resumen: no te preocupes, está bien que en el mensaje de error se vea con dos backslashes)
