### ISSUE TITLE
Rotación de labels en el designer

### ISSUE THREAD

**Issue by josefeliuf** [IIC2233/syllabus#1168]
Hola! me surgió una duda al mirar el enunciado en la parte de "Interfaz". Como dice el título, quería saber como poder rotar los labels (en específico las cartas) como aparecen en la sala de juego (jugadores de la izquierda y derecha). Se me ocurre editar la imagen en una aplicación externa, pero quizás se puede hacer de manera más simple?

**Comment by gatochico** [comment]
Hola! 

`pyqt5` tiene métodos para rotar pixmaps. [Acá ](https://programtalk.com/python-examples/PyQt5.QtGui.QTransform/)hay algunos ejemplos. De todas formas, no es un requerimiento de la tarea el que rotes las cartas para que sigas el ejemplo del enunciado al pie de la letra. Hazlo solo si quieres que quede más estética ✨ 

Saludos!

**Comment by josefeliuf** [comment]
Oka! muchas gracias

**Comment by gatochico** [comment]
Recuerda no cerrar las issues, por si algún compañero tiene la misma duda :o

**Comment by j4vito** [comment]
Hola! también quiero rotar un label y entiendo que se puede hacer dentro del código, pero hay alguna forma de hacerlo dentro del Qt designer para ver inmediatamente como va quedando?

**Comment by gatochico** [comment]
A simple vista, creo que no. Podrías intentar revisando la pestaña de _property editor_ de los widgets, que es donde probablemente estaría si es que se puede.
