### ISSUE TITLE
Cambiar texto sin afectar los demás atributos del label

### ISSUE THREAD

**Issue by juanpaxd** [IIC2233/syllabus#1168]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

¿Existe alguna manera de cambiar SOLO el texto de un label sin afectar su fuente, posicion (si está centrado, o a la derecha), si está en negrita, su color de fondo (esto es lo que mas me afecta), etc etc? Al crear un label en qt designer y dejarlo bonito, y luego aplicarle setText, se cambia todo lo que habia editado (se mueve hacia la derecha, se cambia la fuente a 8 y se quita negrita si es que la hay). Mi duda es si hay una forma de ahorrarme todas las lineas de codigo que conllevaría volver a dejarlo bonito despues de cambiarle el texto.

**Comment by juanpaxd** [comment]
Logré arreglar todos los atributos (los cuales tenian que ser editados en la seccion derecha de Qt Designer) pero me falla el fondo. Tengo un label con un fondo gris, y cuando cambio su texto obtiene el fondo de la ventana (celeste). No sé cómo arreglar esto desde Qt Designer porque tendria que escribir el codigo que arregla el fondo para cada label (entre estos estan los recursos de cada jugador, sus puntajes, los nombres, etc)

**Comment by EduardoIllanes** [comment]
Hola @juanpaxd! Que bueno que hayas podido arreglar lo de los atributos 😄 . Respecto a lo del color de fondo creo que la issue #1130 te puede ser de ayuda. Ahí se dan dos formas de cambiar el color de fondo evitando el efecto cascada. Espero que te sirva 🙌
