### ISSUE TITLE
Envío de cartas

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#1169]
Tengo una duda respecto al envío de cartas. Es posible que al comienzo del juego se envíen todos los tipos de cartas según el formato que se pide en la tarea y guardarlos en el cliente y después cuando este robe una carta se envíen al servidor solo la acción y este ya no envíe la carta nuevamente? No se si entiende.

**Comment by gatochico** [comment]
Hola!

Esta issue ya se respondió en la #1095 (tienen hasta el mismo nombre, jaja). En resumen, no se puedey debes enviar la carta completa cada vez que la necesites. 

Saludos y éxito!
