### ISSUE TITLE
Error Permission denied/ No such file or directory AY11

### ISSUE THREAD

**Issue by emiliaup** [IIC2233/syllabus#1169]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola!! 
Cuando trato de ejecutar la ayudantía 11 me aparece “permission denied.” Trate de cambiar el port como fue indicado una de las issues, pero me sigue apareciendo un error.  Busque online y me apareció en StackOverflow que uno debería “type manage app execution aliases into the Windows search prompt and disable the store versions of Python altogether” (https://stackoverflow.com/questions/56974927/permission-denied-trying-to-run-python-on-windows-10) pero al hacer eso en mi Código me aparece “No such file or directory.” No se que hacer :(

**Comment by tocococa** [comment]
Hola @emiliaup ! Un par de cositas extra, ¿Desde dónde estás intentando ejecutar la ayudantía? ¿Estás usando una cuenta de administrador? ¿Y te corren otros programas de Python?

**Comment by emiliaup** [comment]
Hola! Lo hice como lo mostraron en la ayudantía en Git Bash here o en VSC arriba en Terminal. Me corre todo en Python, cuando ejecuto solo la parte de cliente.py me sale todo bien (Creando cliente Conexion terminada) pero cuando lo hago como lo muestran en la ayudantia para que se conecte el servidor y el cliente no me funciona :(

**Comment by tocococa** [comment]
Oka, ¿puedes intentar ejecutar el código de la ayudantía desde una terminal como CMD o PowerShell (no Git Bash ni VSC), asegurarte de que estás en el directorio correcto y que no hay directorios mal escritos dentro del código del servidor? Y para confirmar, ¿el error que te aparece es `Error: [Errno 13] Permission denied`, o es otro número?

**Comment by tocococa** [comment]
Ahhhh, ¿puedes copiar los archivos de tu ayudantía a un directorio local (algo así como `C:\Users\emili\Documents`)? Estás intentando ejecutar los archivos desde OneDrive y eso puede estar causando problemas 👀

**Comment by emiliaup** [comment]
C:\Users\emili\AY011>cd python3 server.py
The system cannot find the path specified.

Tampoco me funciona :/ 
Todo en la carpeta de AY011 lo saque de la ayudantia tengo todo el server.py el main.py client.py ...

**Comment by emiliaup** [comment]
En GitBash me sigue saliendo 
emili@DESKTOP ~/AY011
$ python3 server.py
bash: /c/Users/emili/AppData/Local/Microsoft/WindowsApps/python3: Permission denied

**Comment by tocococa** [comment]
Ya, un última cosa a ver si funciona antes de ponernos a ver otra soluciones, ¿puede probar si el comportamiento se repite si haces `python server.py`, `python3 server.py` y `PY server.py`?

**Comment by emiliaup** [comment]
ohhhh me funciono el PY server.py :) perfecto gracias
