### ISSUE TITLE
Importación de Usuarios y Orders

### ISSUE THREAD

**Issue by mmsaavedra1** [IIC2233/Syllabus#117]
Al momento de importar ambas categorías, se está asumiendo que todas los id de orders que están en cada usuario, están asociados a los almacenados en orders.csv. 

No tendría sentido que exista una order de un usuario que ya no existe, porque al revisar los archivos existían id de orders que no pertenecían a ningún usuario almacenado, no se si es una error de los archivos .csv ):

**Comment by stephichau** [comment]
Queda a tu criterio manejar esa información. 
Saludos!

**Comment by Hernan4444** [comment]
Por si acaso (respondiendo a tu ultima duda del error) #55

Saludos!
