### ISSUE TITLE
Funciones orden superior

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#117]
Hola, puedo usar funciones de orden superior para agrupar métodos dentro de mis clases y que así quede todo más ordenado?
Gracias!

**Comment by rihanuch** [comment]
Hola @jmwielandt !

Cuando dices
>  funciones de orden superior

¿A qué te refieres 🤔?¿Podrías dar un ejemplo de un código generalizado 👨‍💻 (recuerda que no se permite publicar código de la tarea ❌)?

**Comment by jmwielandt** [comment]
def saludar(idioma):
  def inglés():
    return 'Hello world'

  def español():
    return 'Hola mundo'

  aux = {'esp': español, 'ing': inglés}
  
  return aux[idioma]


print(saludar('ing'))
print(saludar('esp'))

**Comment by rihanuch** [comment]
¡No debería haber problemas! 👌

¡Éxito! 🍀 

----
PD: Si quieres escribir pedazos de código como este:

```Python
def saludar(idioma)
      def ingles():
            return "Hello world!"

      def espanol():
             return "Hola mundo!"

    aux: {"esp": espanol, "ing": ingles}
    return aux[idioma]
```

En formato [Markdown](https://es.wikipedia.org/wiki/Markdown) se puede hacer mediante el uso de 3 comillas del tipo "`" al comienzo y 3 "`" al final. ¡También puedes indicar el idioma 💻 (en este caso pones Python) justo después de las primeras 3 comillas y así se detecta el idioma del código que estás escribiendo! ✅

Te dejo un [cheat sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) de Markdown que es sumamente útil 🤓
