### ISSUE TITLE
Malas prácticas

### ISSUE THREAD

**Issue by Valind4** [IIC2233/Syllabus#117]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holi, no me quedó claro que es considerado una mala práctica y que cosas no, hay como una lista para ver qué cosas no hacer?. Por ejemplo, se puede usar el break?

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by FernandoTFH** [comment]
Todo lo que es mala práctica que será penalizado está Tareas/Bases Generales de Tareas - IIC2233.pdf. Esto es lo mas cercano que hay a una lista. Y sobre le break #52

**Comment by Valind4** [comment]
Gracias <3
