### ISSUE TITLE
Duda sobre inputs y manejo de errores

### ISSUE THREAD

**Issue by cseverino99** [IIC2233/syllabus#117]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [.X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Holaa, mi duda con los inputs es que tengo que asumir que siempre se ingresarán las opciones dadas( por ej: si las opciones son 1, 2 y 3... el input no será 4) o debo estar al tanto de todos los casos?

**Comment by Juampisaez** [comment]
Hola @cseverino99 
No puedes asumir eso, la idea es que manejes todos los casos posibles o los errores. Es decir, si las opciones son 1, 2 y 3, y colocas como input el 4, deberia aparecer un mensaje que diga que la opcion no es valida (**para cualquier input que no sea valido**).

Espero quede claro :)
Cualquier cosa comenta esta issue
