### ISSUE TITLE
Completitud de archivos (existencia de datos NaN)

### ISSUE THREAD

**Issue by 3rdPix** [IIC2233/Syllabus#117]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Es tal lo que dice el título: ¿Podemos asumir que los archivos siempre estarán completos? Sin que existan datos faltantes en alguna fila o columna.
Por ejemplo, un programon al que le falte el ataque:
```
nombre,tipo,nivel,vida,ataque,defensa,velocidad
pikachu,trueno,10,30,,30,30         # NaN en ataque
```

**Comment by MrNachoX** [comment]
Hola @3rdPix! Puedes asumir que todos los archivos siempre van a estar completos.
