### ISSUE TITLE
Temario actividad 1

### ISSUE THREAD

**Issue by topc01** [IIC2233/Syllabus#117]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola, podrían hacer un temario detallado para la Actividad 1 de mañana? Muchas gracias

**Comment by Hernan4444** [comment]
Hola @topc01 

La actividad abarca principalmente contenidos de esta semana, es decir OOP 2 (clase abstracta, polimorfismo y multiherencia), pero puede contener contenidos de semanas pasadas, como herencia, properties, diagrama de clase, listas, set, etc.

Saludosc:
