### ISSUE TITLE
Cantidad de comentarios que es permitido a la hora de definir métodos.

### ISSUE THREAD

**Issue by matix3000** [IIC2233/Syllabus#117]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola!!
Disculpen, que estoy comentando harto de los métodos empleados, donde describo la funcionalidad del algoritmo que estoy implementando, de la forma
"""
Descripción: Queremos sumar dos números, para realizarlo...(algún algoritmo de suma)

Input: a in R
Output: b in R
"""
1 + 1 = 2

Toma lineas, y me parece que se descuenta si uno de los archivos de python tiene mas de 400 líneas de código, quizá estoy haciendo las descripciónes muy detalladas, pero quería saber si se descontaba, no se si puedo subir una de mis descripciones para que evaluen si debería acortarlo.

De antemano muchas gracias!

**Comment by matix3000** [comment]
La duda era si en ese proceso de descontar cuentan los cometnarios

**Comment by Arielmanriquez** [comment]
Hola, si, el proceso de comentar tus funciones afecta el descuento, esto es porque el limite de 400 líneas no es técnico sino que es un limite para ayudar a la legibilidad del código.
No hay ningún problema en que hagas comentarios detallados sobre tus funciones pero si vas a superar las 400 líneas considera separar tus funciones y/o métodos en más de un archivo.
Otra opción que tienes es dejar algunos comentarios directamente en el README.
