### ISSUE TITLE
Ataque y Defensa

### ISSUE THREAD

**Issue by Vicerc** [IIC2233/syllabus#117]
Al momento de atacar, ¿En qué momento se restan los "boost" de defensa de las civilizaciones? Un ejemplo: civilización A tipo Comarca ataca a civilización B tipo DCC, ¿En qué momento se resta al poder de ataque de A los 100 x Cayud que tiene el poder de defensa de la civilización B? Además, ¿Cuándo el DCC pierde estos puntos de defensa extras mueren los ayudantes?, lo mismo para la comarca en el caso de ser atacada, ¿Ellos pierden recursos de madera una vez pierden la Cmadera/2 que tienen de bonus en su defensa?.
Tampoco entiendo si una civilización tipo Cobreloa modifica el hp de trabajadores, soldados y edificios, o si es más bien una suma Pd = Bd + Bd x 0.1, y al momento de atacar una civilización tipo Cobreloa se resta al poder de ataque ese Bd x 0.1 sin haber modificado ningún hp.

**Comment by BFFV** [comment]
Hola!
En la Issue #68 se habla de esto.

**Comment by Vicerc** [comment]
Graciaas!
Otra consulta, una vez la civilización pierde esta defensa extra, ¿La recupera? ¿O se pierde para siempre?

**Comment by BFFV** [comment]
La recupera, por lo que se debe considerar cada vez que la ataquen.
