### ISSUE TITLE
Flujo de menus

### ISSUE THREAD

**Issue by amparostevens** [IIC2233/syllabus#117]
Hola! 
Ya se que han preguntado por los menús varias veces pero aun no me queda claro qué pasa cuando logro ejecutar una acción en un menú (ya sea prograposts o seguidores). 

Por ejemplo, estando en menu prograposts elijo la opción ver mis posts. Luego de ejecutar la acción debo seguir en ese mismo menú y desplegar las opciones? Lo mismo para el menú seguidores?

Y también con respecto a la opción ir a menú principal del menú prograposts, se quiere con ello que uno tenga que volver a "iniciar sesión" o simplemente que de la opción de ir a otro menú? Porque la opción de que cierre sesión y comience de nuevo el programa encuentro que no es muy amigable con el usuario

**Comment by MatiasDuhalde** [comment]
Hola!

Cuando ejecutas una acción dentro de un menú (que no sea volver), luego de ejecutarla y de que se le muestre el resultado al usuario, **deberías permanecer en el mismo menú**. Tomando tu ejemplo del menú _prograposts_, luego de ejecutar la opción de ver tus posts deberías permanecer en el menú _prograposts_, y si el usuario desea volver, que tenga la opción de hacerlo aparte (la misma lógica aplica para el menú de seguidores).

Y con respecto a tu último punto, acabo de responder una issue donde se habla de aquello, por lo que te recomiendo revisarla #116 junto con la issue #90 que también toca el tema.
