### ISSUE TITLE
Plazo Entrega de Diagrama de Clases

### ISSUE THREAD

**Issue by djcontador** [IIC2233/Syllabus#117]
Hola! cuando se entrega el diagrama de clases? La fecha de entrega es la misma que la tarea 1 o se puede entregar junto con el README?

**Comment by sebacruzd** [comment]
Se puede entregar hasta un día después.

**Comment by malopez16** [comment]
Alguna sugerencia en cuanto al programa a usar (o página, no sé) para generarlo?
para no aplicarle al paint jajaj

**Comment by rrhurtado** [comment]
Dejo enlace a una buena página para hacer diagramas, bastante útil para diagramas de todo tipo, no solo de clases

https://www.draw.io/
