### ISSUE TITLE
Serializar imagen.

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#1170]
En el enunciado se menciona que tanto el tipo y el color deben estar serializados ( supongo que da lo mismo si es con json o con pickle) . ¿Es necesario hacer esto mismo con la imagen?, es decir, ¿Tengo que usar json o pickle, serializar la imagen, y despues pasarlo a bytes y enviarla?.¿ O estoy entendiendo mal el concepto de serializar?

**Comment by rieg-ec** [comment]
por si te ayuda, puedes pasar la imagen (el archivo .png) a binary ocupando el parámetro 'rb' de open(), así como

```python3
with open('imagen.png', 'rb') as file:
      datos = file.read()
```
con eso ya tienes la imagen serialized en bytes (otra cosa, pickle que es solo para serializar/deserializar objetos de python y json solo para serializar/deserializar json, por lo que no las puedes ocupar para imágenes)

**Comment by felipefuentesporras** [comment]
yo el string de  color y el tipo de carta lo pase a json y despues lo hago bytes, porque el resto de los mensajes en mi servidor los mando así. ¿Debería cambiar esto?

**Comment by rieg-ec** [comment]
yo creo que deberías cambiarlo porque no estas siguiendo el formato del enunciado (igual confirma con un ayudante no vaya a ser que si se pueda), yo hago lo mismo que tu pero para mandar información, pero para imágenes lo hago en el formato del enunciado, y si quiero agregar información (por ej. si es una carta del pozo o de mi mano) creo mas ID's (se menciona en #1142 que se puede)

**Comment by gatochico** [comment]
Hola! Respecto a tu pregunta inicial, sí, lo que tienes que hacer en ese protocolo es pasar a bytes tanto el tipo, el color y la imagen en sí. Como te habían dicho, no hay necesidad estricta de usar json o pickle ya que ni los strings ni las imagenes son o diccionarios o objetos de python. Simplemente debes codificarlas a binario.

Respecto a tu segunda pregunta, tu compañero/a @rieg-ec también está en lo correcto, no puedes pasar el color y tipo de carta a json, ya que el protocolo está definido de esa forma (sin usar json, sino que con los datos directos) y se debe seguir al pie de la letra. Eres libre de decidir tu el formato para cualquier otra cosa que no sean las cartas, pero las cartas sí o sí deben seguir el enunciado.

Espero haya quedado claro y saludos!
