### ISSUE TITLE
Jugador tiene cantidad impar de cartas y sale un 7 en los dados

### ISSUE THREAD

**Issue by camilapavesi** [IIC2233/syllabus#1170]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Cuando un jugador lanza los dados y sale un 7, los jugadores con 8 o más cartas deben devolver la mitad aleatoriamente. Si un jugador tiene una cantidad impar de cartas, debe devolver la mitad redondeada para arriba o para abajo? Por ejemplo, si tengo 9 cartas, debo devolver 4 o 5?
Gracias!! :)

**Comment by DasVaca** [comment]
Me parece que se responde <a href="https://github.com/IIC2233/syllabus/issues/1129">aquí</a>.

**Comment by camilapavesi** [comment]
Muchas gracias @DasVaca! Prometo que busqué en las issues y no la vi

**Comment by rodrigobj99** [comment]
Hola @camilapavesi tal como dice @DasVaca esta pregunta ya fue respondida en la issue [#1129 ](https://github.com/IIC2233/syllabus/issues/1129).

Exito en la tarea!
