### ISSUE TITLE
Carta cambio de color Avisar a los jugadores

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1171]
Una duda en ele enunciado dice:
![Captura de pantalla 2020-06-27 21 10 50](https://user-images.githubusercontent.com/62029138/85935127-f7db6580-b8ba-11ea-824b-33c1f4f48397.png)
Entonces para avisar a los demás jugadores se podría simplemente hacer un print del color elegido y quien lo hizo en los logs del servidor?

**Comment by jirarrazabal** [comment]
Hola! No basta con imprimirlo en consola. La idea es que se muestre en la interfaz de los clientes, ya sea en un pop-up como muestra la imagen del enunciado o en la interfaz del juego que se está utilizando. Suerte!

**Comment by RonaldoSosa** [comment]
Entendido!Gracias por la aclareación!

**Comment by DCCollao** [comment]
Hola @RonaldoSosa! Complementando la excelente respuesta que te dio mi compañera, te recuerdo que los clientes **no** tienen acceso al servidor si no es mediante sockets, por lo que, como dijo ella, no basta con imprimir en la consola del servidor, pues ningún cliente podrá ver dicha consola.
