### ISSUE TITLE
ConnectionResetError: WinError 10054

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#1172]
Hola, tengo un error al mandar información del servidor al cliente;
![image](https://user-images.githubusercontent.com/59337116/85935331-8f41b800-b8bd-11ea-9f87-4e0da363f9ac.png)
Cuál es el error "general" que está ocurriendo¿?
El problema puede ser que esté recibiendo más de una información a la vez¿?
No sé realmente lo que pasa porque me encargé de que cuando terminara una acción, se entregará otra información al cliente... 
Ojala me puedan ayudar mencionando el error que podría haber, gracias :D

**Comment by fdoflorenzano** [comment]
Hola @Camila-sty,

¿Pudiste solucionar el error? Es difícil entender la razón de ese error directamente ya que puede ser por muchas cosas. Por lo que he visto, aparece ese error cuando se intenta usar un _socket_ en alguno de los lados (cliente o servidor) pero que fue cerrado previamente (`close`). Tal vez algo ocurre en el flujo de alguno de tus programas que cierra anticipadamente un _socket_ y el otro programa aún intenta interactuar con el _socket_. Tal vez puedes buscar eso en tu código.

Saludos.
