### ISSUE TITLE
Cartas en blanco y negro en Sala de Juego 

### ISSUE THREAD

**Issue by totaurt** [IIC2233/syllabus#1173]
Buenas noches! Tengo un problema con la interfaz gráfica que no he podido resolver. Todas las cartas que se muestran en la Sala de Juego se ven sin color. Creo no haber hecho nada especial en la configuración en QtDesigner y en envío de cartas como lo recomiendan en la mayoría de las issues, con base64 y después en la ventana creo el pixmap con pixmap.loadFromData(imagen, "png"). Si me pudieran ayudar sería genial, gracias!

**Comment by totaurt** [comment]
ayuda:(
![image](https://user-images.githubusercontent.com/62078076/86146524-56286400-bac6-11ea-8df6-a4a7d8766c78.png)

**Comment by lily416** [comment]
Hola :) ¿Podrías subir tu código? Es para probarlo y ver si encuentro el error o algo que me llame la atención.

**Comment by totaurt** [comment]
Hola!! Sí, lo acabo de subir. Muchas graciass.

**Comment by lily416** [comment]
Después de mucho buscar encontramos lo que causaba que todo se viera blanco y negro :tada:

Se debe a que el QDialog tiene la property `enabled` como false, lo que hace que hace que no se pueda acceder a los elementos de la ventana.

Para arreglarlo puedes:
1. Cambiar directamente el archivo UI. Debes cambiar `false` que aparece en la línea 6 por un `true`
1. O cambiarlo en QtDesigner. Debes ver las property del QDialog y si buscas `enabled`, te aparecerá una checkbox.


Espero que te sirva,
Saludos y éxito en la tarea :wave::heart:

PS: Créditos a @gatochico por encontrar el error.

**Comment by totaurt** [comment]
AAAA muchísimas gracias, especialmente a @gatochico jajaja 😭 Ahora todo funciona y se ve perfecto. Justo había publicado la issue #1211, que se debía a esto mismo.  Me salvaron!!
