### ISSUE TITLE
Problema al enviar información

### ISSUE THREAD

**Issue by mariajoseguerrero** [IIC2233/syllabus#1174]
Hola! Tengo una duda en la parte de enviar información de las cartas. Al recibir el largo y el id de las cartas, se me detiene el programa (no indica error) al entrar al 'while' en el cual voy recibiendo en chunks la información. Para ver que podía ser, imprimi el id y el largo, y me salen números muy grandes y distintos a los que envío en el servidor. Por ejemplo, en el servidor imprimo uno de los largos y se me imprime 6, y en cliente imprimo lo mismo y se me imprime 1277174131. He revisado varias veces y no encuentro mi error, y tampoco se si efectivamente se me debería imprimir ese numero, pero de ser así, no se me debería detener el programa en el while. 
en servidor tengo: 
largo_color = (len(color_enviar)).to_bytes(4 , byteorder= 'little')
print(len(color_enviar))
-> 6 
en cliente tengo:
largo_color = int.from_bytes(self.socket_cliente.recv(4), byteorder= 'little')
print(largo_color)
->  1277174131

Gracias!

**Comment by mariajoseguerrero** [comment]
Ya lo solucioné, gracias :D

**Comment by DCCollao** [comment]
Hola! Me alegra que lo hayas podido resolver! 

Si posteas cuál era tu error, le podría servir a alguien más :smile:

**Comment by mariajoseguerrero** [comment]
Lo que pasaba era que tenia un error al enviar el mensaje, entonces era otro el que se me estaba leyendo, no el que necesitaba.
