### ISSUE TITLE
No llega todo el mensaje al cliente

### ISSUE THREAD

**Issue by BFry712** [IIC2233/syllabus#1174]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holaaa! necesito ayudaa,  el mensaje que mando del servidor al cliente llega incompleto :c he intentado hacer otras cosas pero no he podido resolver esto

**Comment by matiasmasjuan** [comment]
Hola @BFry712 !

Estuve revisando tu código y el problema se encuentra en el **protocolo de envío de mensajes**.

El primer error se encuentra en ```server.py```, línea 145. Intentas hacer un bloque de bytes que va desde [i : i + 60], lo cual llama mi antención. ¿Que pasa si i + 60 **supera** la cantidad de *bytes* del mensaje? Inmediatamente va a ocurrir un error, ya que se estan agregando *bytes* inexistentes a tu *bytearray()*.

El segundo error se debe a la **inconsistencia** entre los bytes que envías desde el servidor, con los que recibes en el cliente.  En el servidor, por cada 60 *bytes* del mensaje, agregas 4 *bytes* de la posición y luego 60 *bytes* del mensaje, lo cual da un total de 64 *bytes* por bloque. Sin embargo, en la línea 97 de ```client.py```, recibes un tamaño de chunk variable entre 60 y lo que queda de recibir del mensaje. Luego, a partir de ahí le sacas los 4 *bytes* de la posición. Esto no tiene ningún sentido. Si sabes que el tamaño que envía es de 64 *bytes* por bloque, entonces el cliente también debe recibir un chunk de 64 *bytes*. Luego de esto puedes quitarle los 4 *bytes* iniciales de la posición. Recuerda que una forma de quitarle los *bytes* ceros (b'x\00') es utilizando el método de *strings* ```strip``` y recién ahí decodificar el mensaje.

Por favor revisar con mayor detalle el código antes de hacer una ***issue*** al respecto :sweat_smile: 

Saludos!

**Comment by BFry712** [comment]
Muchas gracias @matiasmasjuan !
