### ISSUE TITLE
Envió de cartas

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#1175]
Hola tengo una duda con la estructura del envío de cartas. Para que sirve el ID de cada parte? Es decir, cual es el sentido por ejemplo de agregarle el 1 antes del largo del color?

**Comment by szabala** [comment]
Hola! La idea de agregar un ID es poder identificar el tipo de objeto que viene serializado en el siguiente bloque. De esta manera, cuando leas el _bytearray_ en el lado del cliente puedes distinguir que estas de-serializando. Si no usáramos un ID, tendríamos que tener una "regla" no escrita sobre el orden en que vienen los objetos en el _bytearray_. Esto ultimo no es una buena practica, ya que alguien que lea tu código no podrá entender como sabes que se esta enviando.

Espero haber aclarado tu duda :smile:

**Comment by tedroppelmann** [comment]
Igual en la tarea viene una regla implícita con el orden o no? Primero color, después número y después imagen. Mi duda va que al deserealizar del lado del cliente yo se que viene en ese orden y lo descodifico de esa forma.

**Comment by szabala** [comment]
Cuidado que en el enunciado se explicita que **es obligación** incluir el identificador. La idea es que si ademas necesitas enviar más información en el _bytearray_, puedes crear nuevos `IDs` y asignarles significados. Una ventaja de esto es tener un formato de comunicación unificado entre cliente y servidor.
Suerte con la tarea 👍

**Comment by tedroppelmann** [comment]
Si, para el envío de cartas utilizo el mismo formato que se pide incluyendo los ID y para cualquier otro envío uso json. Mi problema es que no se si es penalizado no utilizar los identificadores al deserealizar. Yo se el orden que viene y decodificarlo según eso.

**Comment by szabala** [comment]
Como indique antes, **es obligatorio estructurar el _bytearray_** como se muestra en el enunciado. Se considera una mala practica utilizar un orden implícito y sera penalizado en la corrección.

**Comment by tedroppelmann** [comment]
En el enunciado la figura 4 muestra la ilustración del bytearray. En ella existe un orden jajaja por eso pregunto. El bytearray que envió es idéntico al de la figura 4 y hay un orden por lo que entiendo :( (Color, número y después imagen) sorry si no cacho

**Comment by szabala** [comment]
No te preocupes! La idea de las _issues_ es poder aclarar tus dudas.

Si bien hay un orden en el _bytearray_ de la figura 4, fíjate que este no importa dado a que cada bloque (id, largo y objeto) tiene asociado un _ID_ en especifico. Entonces, si utilizas los _IDs_ al leer el bytearray, no importa el orden en que vengan los bloques dentro de este. Por ejemplo, podrías enviar los bloques en el orden Imagen-Color-Numero y el cliente podría obtener toda la información de igual manera.

Como resumen, en el enunciado no se indica ningún orden en especifico para enviar los bloques dentro del bytearray (la imagen es solo un ejemplo). Lo único que se pide es que se envíen bloques que contengan el ID, largo y objeto serializado. Si en tu código envías el ID de cada bloque pero no lo utilizas en la deserialización, en teoría sigues lo pedido en el enunciado pero podría considarse una mala practica.
