### ISSUE TITLE
Argumento 'arista grilla' en generador_grilla.py

### ISSUE THREAD

**Issue by camirojasguajardo** [IIC2233/syllabus#1176]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! estoy ocupando la clase contenida en el archivo generador_grilla.py, pero no me da las posiciones esperadas:( me imagino que puede ser porque el argumento 'arista grilla' no es en realidad lo que entendí que era jaja mi duda es: tal arista es el ancho del label que contiene al hexágono o solo del hexágono? o de la grilla en total? A la vez, me pregunto si ¿es necesario que los hexágonos sean regulares o basta con respetar las proporciones de las imagenes originales de los hexágonos (igual ancho y largo)?
Desde ya, agradezco sus respuestas :)
Saludos!

**Comment by Juampisaez** [comment]
Hola @camirojasguajardo 
1. El tema del tamaño de las aristas no te deben enfocar, acuerdate que el metodo que te importa es el de generar_grilla que recibe una lista de la forma [fila, columna] (lo explican de forma mas grafica en la ayudantia del martes pasado de la seccion 1 y 2), padding_x y padding_y, eso esta explicado en el archivo, si aun no lo entiendes comenta de nuevo.
2. Los hexagonos, siguiendo lo que ya te mencione, serán regulares (no es necesario que te preocupes de esto).

Quedo atento si tienes mas dudas o si algo no se explico bien :)

**Comment by camirojasguajardo** [comment]
hola @Juampisaez, gracias por tu respuesta! Comprendo que al ocupar el método generar_grilla, los argumentos necesarios son [fila, columna], padding_x y padding_y, pero para instanciar la clase que contiene tal método (GeneradorGrillaHexagonal), el argumento que debo entregar es la arista y ahí es donde me confundo jaja, no entiendo si esa arista es el tamaño de las aristas de los hexágonos que forman la grilla, la arista del label cuadrado que contiene a cada hexágono u otra cosa jaja:( he tratado con ambas opciones y, al ubicar algo en las posiciones de los nodos q devuelve el diccionario, no me calza:( me quedan corridas uwu

**Comment by Juampisaez** [comment]
Es el tamaño de cada arista, en el hexagono, en pixeles. Al final puedes verlo como el largo que tendrá cada camino en tu grafo. Puede que lo que esta provocando el descuadre es el padding. Ahora, ayer si no me equivoco actualizaron el archivo de generador_grilla.

Espero haberte ayudado mejor.

**Comment by camirojasguajardo** [comment]
@Juampisaez gracias! aunque sigue sin funcionarme, debo estar cometiendo otro error uwu
