### ISSUE TITLE
pyqtSignal y diferentes clases como eventos

### ISSUE THREAD

**Issue by cncosta** [IIC2233/syllabus#1176]
Hola tengo la siguiente duda, puedo hacer que una pyqtsignal pueda emitir más de una clase de eventos?
```python
several_class_signal = pyqtSignal(ObjetoA,ObjetoB,ObjetoC) 
#donde los objetos son de la forma
class ObjetoK:
    def __init__():
        self.atributo =atributo
        self.atributo2 = atributo2
# etc
```
con este código lo que quiero es que la señal al ser emitida pueda ser con cualquiera de los objetos A,B o C

**Comment by jirarrazabal** [comment]
Hola! 
Con el código mostrado no estas logrando lo que quieres, sino que estas haciendo que tu señal deba emitir un set con  todos los objetos indicados. 
Para que se puedan enviar cualquiera de los objetos se debe usar:
```several_class_signal = pyqtSignal([ObjetoA], [ObjetoB] , [ObjetoC]) ```
Pero luego, a la hora de conectar la señal se debe especificar a que slot de la señal quieres referirte de la siguiente manera:
```several_class_signal[Objeto].connect(self.handle_string)```
Para más información mira los siguientes links: 
https://www.riverbankcomputing.com/static/Docs/PyQt5/signals_slots.html
https://stackoverflow.com/questions/12050397/pyqt-signal-emit-with-object-instance-or-none

Aun así, este método puede traer errores y llegar a ser más complicado, por lo que te recomiendo usar mejor un diccionario donde, al emitir tu señal, el argumento del objeto que no desees enviar simplemente sea None, o separar tu señal en varias señales específicas para cada objeto.
Mucha Suerte!
