### ISSUE TITLE
JSONDecodeError: Expecting value...

### ISSUE THREAD

**Issue by janwandter** [IIC2233/syllabus#1177]
Hola, tengo 2 errores que me aparecen en distintos puntos de la ejecución, y algunas veces ni siquiera aparecen. No he podido encontrar un origen para ambos y ninguna solución en internet ha funcionado hasta ahora. Que puede ser?
 

![image](https://user-images.githubusercontent.com/61998417/85939882-e314c700-b8e6-11ea-9c7f-0f28ad1aecdf.png)

[actualizacion] un error ya lo solucione. El de la foto sigue y pasa cuando mando json iterando, entonces creo que se juntan en el listen del cliente. Alguna forma de evitar que se unan?

**Comment by fdoflorenzano** [comment]
Hola @janwandter,

¿Sigues con este problema?

Si no, si te fijas en el seguimiento del error, sale que efectivamente el error es en `listen_thread`, en el archivo `client.py`. Ese error se arroja cuando se intenta usar `json` para deserializar un *string* que no está en el formato JSON que espera el módulo. Se puede tratar de dos cosas: o el *string* que intentas deserializar no está en formato JSON, por lo que `json` no debería usarse ahí, o el *string* se dañó al ser enviado entre servidor y cliente, por lo que empieza a leerlo pero algo está extraño y no sabe como interpretarlo.

Te recomiendo agregar un `print` del *string* a deserializar para ver como te está llegando, y que es lo que le estás pasando a la función `loads`.

Saludos.

**Comment by janwandter** [comment]
Hola, sigo con errores cada ciertas ejecuciones. Lo que pasa es que yo le aviso al cliente cuando le voy a mandar bytearray. Pero cuando mando un bytearray seguido de un string en json, el recv del cliente algunas veces los une. Mi solucion momentanea es ponerle un sleep muy corto entre los 2 envios en el servidor, pero quiero solucionar el problema general.

**Comment by fdoflorenzano** [comment]
@janwandter 

Entiendo, pero no te recomiendo esa solución. Esos dos segundos es un número bastante arbitrario y no garantiza que se arregle la situación para siempre, sobretodo considerando que si lo manejas con *threads*, el orden y tiempos de ejecución no son predecibles.

Lo que me dices me da a entender que estas leyendo datos mediante `recv` de un largo fijo en vez de largo variable. Y por eso al enviar dos mensajes muy seguidos, no sabes como diferenciarlo. Te recomiendo seguir alguna estrategia para transmitir entre cliente y servidor ***cuanto*** tiene que leer. Así para cada mensaje lee lo justo y necesario, y luego para el siguiente mensaje lee lo justo y necesario, y así sucesivamente. En [este cuaderno](https://github.com/IIC2233/contenidos/blob/master/semana-14/3-ejemplos.ipynb) hay un ejemplo del tema, y en el video de cierre de la semana 14 se habla de este tema.

Saludos.

**Comment by janwandter** [comment]
Si! lo estaba haciendo con largo fijo. Ahora funciona mucho mejor! Gracias!
