### ISSUE TITLE
Metodos de un grafo no funcionan , las instancias se pierden.

### ISSUE THREAD

**Issue by nicolecll** [IIC2233/syllabus#1177]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola, estoy intentando instanciar un grafo y utilizar los métodos expuestos en los contenidos del curso, específicamente los contenidos de la semana 12, sin embargo los métodos propios del grafo no funcionan, cuando intento acceder a algún vecino de cierto grafo por ejemplo, me lanza keyError. Trate de entender el porque de este error pero no he llegado a mucho, la única diferencia con el ejemplo de los contenidos es que ahí las instancias de los nodos se hacen de manera global y luego se crea la lista, en cambio yo creo en un ciclo los nodos y formo la lista (son 32 por lo que creo que es muy engorroso instanciar uno por uno) **¿Puede ser que las instancias se pierdan de manera local y por eso los métodos no funcionan?**. Me ayudaría mucho una orientación :(

Hice push a mi repo específicamente en el archivo grafo.py del server.

**Comment by DCCollao** [comment]
Hola @nicolecll!

Creo que encontré el error en tu código. 
Cuando estás creando la lista de adyacencia, las llaves que le entregas el diccionario son **objetos de clase Nodo**, mientras que cuando intentas acceder a los valores del diccionario en tu método `vecinos`, el argumento `x` que entregas corresponde a un número entero, dando como resultado el `KeyError` que mencionas.

Para verificarlo, agregué las siguientes líneas en tu método `vecinos`:
```Python3
for key in self.lista_adyacencia.keys():
        print(type(key))
``` 

Espero que sea de ayuda!
