### ISSUE TITLE
Qdialog Built-ins Prohibidos

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1178]
Hola!Cuando intento usar QDialog para la parte de la carta de cambio de color , tengo la siguiente duda , lo que pasa es para hacer que me qdialog aparezca yo cree el siguiente método:
def crea_qdialog(self):
       ventana = Dialog_personalizado()
       ventana.exec_()
Quiero saber al hacerlo de esa forma se refiere  a los Built-ins Prohibidos , lo hago con eso ya que cuando no aplico esa parte el qdialog se abre y se cierra al instante además cuando intente hacer el método dentro de mi qdialog , el self.setParent(parent) , y luego crear el metodo
def crea_qdialog(self):
       ventana = Dialog_personalizado(self)
Esto desde mi ventana de juego mi qdialog aprecio dentro de mi ventana de juego , en fin el problema es que no se como hacer que la ventana de qdialog permanezca abierta sin el uso del exec_()

**Comment by aaossa** [comment]
Hola @RonaldoSosa , el método `exec_()` no es lo mismo que el _built-in_ `exec()`, así que no debes preocuparte ya que tue estás usando el método, que no está prohibido. En la issue https://github.com/IIC2233/syllabus/issues/686 se indica más información.

**Comment by RonaldoSosa** [comment]
Yaaa entendido!Graciass !!!
