### ISSUE TITLE
problema al hacer git full 

### ISSUE THREAD

**Issue by sbmirandap** [IIC2233/syllabus#1178]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
al hacer git pull del syllabus se me descargan ciertas cantidad de cosas y luego me sale "Aborting" y para de descargar, no puedo ver los archivos de la tarea y no he encontrado soluciones a esto :(

**Comment by Mjtala** [comment]
Puedes tratar haciendo git pull desde syllabus/Tareas?
Avísame si te funciona :)

**Comment by sbmirandap** [comment]
me pasa exactamente lo mismo :(

**Comment by Mjtala** [comment]
Trataste borrando y clonándola de nuevo?

**Comment by sbmirandap** [comment]
Jiji no lo había hecho! Ahí me funciono gracias

**Comment by Mjtala** [comment]
bacan, éxito con la tarea!
