### ISSUE TITLE
Termino del mazo

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2233/syllabus#1179]
Hola, vi en los issues que si se acaba el mazo uno genera más cartas, sin embargo, esto no me hace mucho sentido, pues podría eventualmente existir puros 2_rojos en la partida (como ejemplo) no tendría más sentido que cuando se acabe el mazo el nuevo mazo sean las cartas que ya se han botado? (como en el uno real) y así no se produce una multiplicación de cartas. tendría como condición eso si, que el minimo de cartas en un mazo es 41 o algo asi.

**Comment by Aloncarrasco** [comment]
Por otro lado, si prefieren que cada vez que me quede sin cartas simplemente genere uno mazo al azar, creo que esto facilitaría las cosas.

**Comment by DCCollao** [comment]
Hola @Aloncarrasco!

En #1027 se preguntó por el término del mazo. Por favor revisa esa issue y si te queda alguna duda, estaremos atentos a esa issue!
