### ISSUE TITLE
¿Comp puedo hacer para detectar cuando un cliente se ha desconectado del servidor?

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#1179]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo la duda de como hacer que el server sea capaz de detectar cuando es que un cliente de desconecta de manera forzada, y más importante aún, como identificar **cual fue el cliente que se desconectó**

Lo que tengo es que cuando un cliente de desconecta del servidor, se levanta la excepción `ConnectionResetError`, de una forma más o menos así:
(Esta es la función target del thread encargado de escuchar a un socket especifico)
```python
try:
        # Escuchamos a un socket
except ConnectionResetError as e:
        print("Se ha interrumpido la conexión de un jugador")
```

Lo que ocurre es que el levantar esta excepción me dice que un socket se desconectó, pero no me dice **cual fue**. Necesito saber esta información porque tengo un diccionario que se va rellenando con los sockets de los clientes que se conectan como llaves. **Entonces, mi intención es que cuando un cliente de desconecte, quitar ese socket del diccionario, pero como lo puedo hacer?** si cuando el usuario se desconecta no "puede avisar que se desconecto"?

**Comment by furcelay** [comment]
Hola @Gsalinas1506 !

En la función target del *thread* que escucha al cliente debes manejar la información que necesitas para identificar al cliente, una forma de hacerlo es que los argumentos de la función sean por ejemplo el *socket* y el *id* del cliente. De todos modos lo más probable es que sí tengas esa información porque el *socket* es el que levanta ese error, tal como comentas tu función escucha a un *socket* específico así que deberías saber cual es.

Si ya reconoces el *socket* y este es el *key* en un diccionario puedes eliminarlo con:
```python
del diccionario[socket]
```
Solo recuerda usar *locks* al realizar este tipo de operaciones para mantener coherencia entre *threads*.

Saludos!
