### ISSUE TITLE
Tablero_transformado, error de testcase que no entiendo

### ISSUE THREAD

**Issue by Jpdelaf** [IIC2233/Syllabus#118]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
*[X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, estoy teniendo un problema con la función Tablero transformado, en donde al parecer la consola me arroja un mensaje sobre un código dentro de los testcase el cual lo apunta como que no es una instancia de listas.
![Captura de pantalla 2023-08-29 173726](https://github.com/IIC2233/Syllabus/assets/141885410/ac0eb67d-caf8-403f-9ad8-2a9ab638e6b2)
![Captura de pantalla 2023-08-29 173803](https://github.com/IIC2233/Syllabus/assets/141885410/fd91c5f2-493e-4f37-8e43-6bd017ba016a)
quizá es porque yo no este retornando una lista según la consola, pero estoy muy seguro de que si es una lista lo que retorno, entonces no se bien.

**Comment by ManuelV03** [comment]
Hola, según lo que puedo ver en la foto tiene pinta de que definiste tablero_transformado como un método y mientras que hay que definirlo como una property (como pide el enunciado) y es por esto que el test case no funciona. Define tablero_transformado como una property y ve si funciona. Avísame que tal.

**Comment by Jpdelaf** [comment]
era eso, muchas gracias por la ayuda
