### ISSUE TITLE
Archivo gitignore T01

### ISSUE THREAD

**Issue by fnberrios** [IIC2233/syllabus#118]
Hola! ¿Debe ser subido el archivo .gitignore al repositorio personal o tienen otra forma de revisarlo?
Gracias de antemano.

**Comment by DCCollao** [comment]
Para las tareas, tu archivo ``.gitignore`` debería estar en la carpeta ``Txx`` (en este caso, T01) dentro de tu repositorio. De todas maneras, esa no es la única forma de utilizarlo. Te dejo esta [información](https://git-scm.com/docs/gitignore) por si quieres aprender más!

**Comment by fnberrios** [comment]
Gracias!
