### ISSUE TITLE
Actividad 1, tests estan mal escritos?

### ISSUE THREAD

**Issue by jtvvtj** [IIC2233/Syllabus#118]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Hola buenas, sucede que el test_consultas_estudios_genero, en 5 tests el resultado esperado, esta escrito todo en minuscula, lo cual tira "FAIL" debido a que los estudios estan escritos del siguiente modo "Sunrise", mientras que en el test en el resultado esperado esta como "sunrise", por lo que al correr el codigo tira "FAIL".

Y de casualidad, el test_consultas_resumen_anime, no tiene errores?, que la verdad ya no se que tengo malo con dicho test?

**Comment by Hernan4444** [comment]
Hola,

Recomiendo revisar esta issue:
* https://github.com/IIC2233/Syllabus/issues/26

Pero en resumen, no están mal los tests, es que esa función pide una cosa en particular que falta tener en cuenta.

Saludos! 🦖
