### ISSUE TITLE
Usuarios ya creados, pero sin clave

### ISSUE THREAD

**Issue by rldelafuente** [IIC2233/syllabus#118]
Hola!
Tengo una duda con las funciones de crear usuario e ingresar con un usuario. En el archivo usuarios, solo se indica el nombre de usuario, sin su clave. Es decir, solo los usuarios nuevos tendrán clave.
¿Mi duda es, los usuarios antiguos pueden ingresar sin clave? ¿O solo permitir que los usuarios que se crean puedan ingresar (con su clave correspondiente)?

Esto es por si se desea eliminar un post de un usuario que esta en la lista del excel.

**Comment by Tito0906** [comment]
Holaa @rldelafuente,  en el enunciado no se específica que se necesite una clave para entrar, tan sólo se necesita el nombre del usuario. Esto sucede para los usuarios nuevos y antiguos.  Creo que esta duda se explica por lo que se menciona en esta issue github.com/IIC2233/syllabus/issues/52.

Quedo atento por si tienes otras dudas!
