### ISSUE TITLE
Duda sobre diagrama de clases

### ISSUE THREAD

**Issue by Daniel-Guajardo** [IIC2233/Syllabus#118]
En el enunciado dice que debo identificar las clases que son abstractas. Entonces, ¿hay alguna regla estándar para identificar aquello dentro del diagrama de clases?

**Comment by catalina-arcila** [comment]
Hola @Daniel-Guajardo, para dejar claro que es una clase abstractra padre puedes agregarle (ABC) o (abstractmethod) en la definición de la clase

**Comment by Daniel-Guajardo** [comment]
Aún no estoy muy claro. ¿Podrías darme un ejemplo gráfico?
