### ISSUE TITLE
¿Se puede atacar a sí mismo?

### ISSUE THREAD

**Issue by fllullk** [IIC2233/syllabus#118]
En "acciones.csv" en el turno 58 la civilización cero se ataca a si misma, ¿eso está bien? ¿Una civilización se puede atacar a si misma o tiene que fallar esa acción?

Adjunto imagen

![image](https://user-images.githubusercontent.com/48299237/55581652-c5f94480-56f3-11e9-95fa-26955908ed73.png)

**Comment by iqacevedo** [comment]
Hola @fllullk,

Es un error en el archivo, gracias por notarlo.  Al revisar el archivo no tendrá este tipo de errores. Así que puedes omitir esa línea. Próximamente actualizaremos el archivo corrigiendo el error.

Saludos y éxito en la tarea!

**Comment by fllullk** [comment]
¡Gracias @iqacevedo!
