### ISSUE TITLE
Problems que muestra vscode

### ISSUE THREAD

**Issue by cimoya2** [IIC2233/syllabus#118]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola! Resulta que programando en la tarea 0 a través de vscode, la sección "problems" me indica dos cosas que no tienen que ver con mi código, si lo apreto se abre un nuevo archivo builtins.pyi de una extensión muy larga que nada que ver con la tarea, mi duda es **qué significa y si me afecta en la tarea, o simplemente lo ignoro?**
Gracias :)

![image](https://user-images.githubusercontent.com/80859583/112910532-e8977b80-90c9-11eb-90bd-844c50cc6c8e.png)

**Comment by nicoguz** [comment]
Hola!!
Este mismo error le ocurrió a un compañero tuyo y en la issue #61 hablan sobre su significado y por qué ocurre.

Con respecto a tu otra duda, mientras puedas ejecutar el código en tu tarea y no te genere problemas entonces puedes ignorarlo. Sin embargo, si comienzas a tener problemas puedes publicar una issue con el error específico que te impide trabajar para que así te podamos ayudar a solucionarlo.
De todas formas el error parece estar en una extensión de vscode y es probable que sea un error de instalación de las extensiones, pero no te recomiendo reinstalarlas a menos que te genere problemas.

Espero haberte ayudado : ) !
