### ISSUE TITLE
Inicio de sesión

### ISSUE THREAD

**Issue by bawas** [IIC2233/Syllabus#118]
no me queda claro los beneficios que presenta cada usuario respecto a las orders. Para un trader, se señala que este, aparte de poseer los beneficios que tienen los underage, tambien pueden ver las order realizadas en los ultimos 7 dias. ¿se refiere a todas las orders de todos los mercados?. y ¿que atributos de una order deben ser desplegados?

Por otra parte, en los requerimientos señalados al momento de iniciar sesión se encuentra la opción de enseñar la lista de orders (sea del dia, una fecha especifica, entre dos fechas, o un mercado en particular) y la lista de orders activas. ¿este despliegue de información debe estar restringido a los permisos de cada usuario? es decir, si un trader ingresa una fecha que queda fuera de su capacidad de visualizar información mas allá de una semana ¿debería reportarse en consola?. supongo que si todo lo anterior es correcto, el menú de información deberia ser distinto c/u usario.

saludos!

**Comment by nmaturana97** [comment]
me sumo a la pregunta, por favor que alguien explique bien esa parte del enunciado,
gracias.

**Comment by naazocar** [comment]
Por lo que entiendo el programa tiene que permitir que el usuario acceda a todas las orders que quiera (dentro de su poder según tipo de usuario), de un mercado, de una fecha, entre dos fechas, como el usuario quiera. Los atributos no sé, imagino que los necesarios para identificar la orden.

Y en el apartado 10 del enunciado dice que el menú debe ser distinto según tipo de usuario, así que creo que sí.

**Comment by nmaturana97** [comment]
Ya pero, a que se refiere con que "Ademas, pueden acceder a un
registro de las orders realizadas en los ultimos 7 dias.", ya que esto se contradice con:
"Lista de orders: Se deberia dar la opcion de desplegar en consola, de forma ordenada, una lista
de todos los orders del dia, una fecha especifica, entre dos fechas o de un mercado en particular."
Si algun ayudante puede explicar especificamente que puede hacer cada tipo de usuario seria bueno para todos creo yo. Gracias de antemano.

**Comment by iqacevedo** [comment]
Hola a todos !

Los usuarios debido a sus restricciones si tendrán menus diferentes, siempre deben cumplir las restricciones que tiene cada usuario. Por lo anterior si un Trader pide una order de una fecha más antigua a 7 días, no deberían mostrársela.

Saludos !
