### ISSUE TITLE
Puntos de Poder / Porcentaje Extincion

### ISSUE THREAD

**Issue by ofvera** [IIC2233/Syllabus#118]
Me surgió una duda con respecto al punto de poder al inicio que se usa para el porcentaje de extinción.
Los puntos de poder incluyen el área del incendio, este incluye el radio, pero no dice de que tamaño es al principio.
Si bien podemos asumir un tamaño r=1 (metros), por que empezó pequeño, el punto de poder inicial sería bajisimo. El porcentaje de extinción, si el incendio aumenta de tamaño con el tiempo antes de recurrir a el, el recurso podría 1) extinguir mucho más que el inicial, o 2) ser hasta negativo si crece más de lo que se apaga.
Caso 1: 4000%
Caso 2: -300%
En esos casos, no es ilustrativo un porcentaje, por que el estado inicial no tiene nada que ver con el tamaño del incendio.

**Comment by iqacevedo** [comment]
Hola!
En primer lugar tu debes asumir el tamaño inicial del radio de tal manera de que te haga sentido con el problema.
Además recuerda que para el cálculo de porcentaje de extinción, debes considerar los puntos de poder acumulados DESDE  el inicio (no los iniciales).

Saludos !
