### ISSUE TITLE
crear galaxia

### ISSUE THREAD

**Issue by bidelreal** [IIC2233/Syllabus#118]
Hola, no entiendo si en crear galaxia, de entre todos los planetas que crea el usuario, este debe elegir uno para que quede en estado conquistado, o si por cada galaxia que crea el usuario este debe elegir un planeta para que quede en estado conquistado. 
También tengo otra duda, el usuario cuando crea planetas puede escoger una galaxia que no haya sido de las recientemente creadas(una que este en el galaxias.csv por ejemplo)? 

6.1. El usuario debe ser capaz de crear la cantidad de planetas que el quiera, donde elige el nombre del planeta y la raza de su población. Todos estos planetas deben ser guardados bajo el nombre de una galaxia que también es decidida por el usuario. Todos los planetas y galaxias creadas deben ser registradas en el archivo planetas.csv y galaxias.csv respectivamente.
Finalmente, antes de guardar, el usuario tiene que elegir 1 planeta para que quede conquistado desde el
inicio. Todos los demás deberán ser poblados con el 75% de su población máxima.

**Comment by leolivares** [comment]
Hola! Respondiendo tus dudas

- La idea es que el usuario seleccione un planeta inicial para conquistar, por cada galaxia que sea creada. De esta manera podrá comenzar a jugar teniendo un planeta bajo su control.

- Sí, el usuario puede crear un planeta en las galaxias ya existentes. Esto seria bajo la modalidad de *Modificar una Galaxia*.

> En esta opción, el usuario puede elegir cualquier galaxia que exista en los archivos galaxias.csv y dentro de ella, modificar cualquier planeta. Las capacidades de modificación incluyen: 
> - Agregar un nuevo planeta sin conquistar.

Espero haber resuelto tus dudas!

**Comment by Pipelao** [comment]
Hola!
¿Entonces en un principio al usuario debo mostrarle las galaxias y planetas que ya existen (archivos .csv) y preguntarle si quiere crear una galaxia nueva, en caso contrario puede elegir una galaxia y un planeta de los que ya están creado? No logro entender del todo la función de los archivos .csv
Gracias de ante mano

**Comment by leolivares** [comment]
@Pipelao 
La idea de los archivos .csv es mantener los datos de las galaxias y los planetas, cada vez que se guarde el juego.

Inicialmente, al usuario se le debe permitir ciertas funcionalidades (Sección 6). Se supone que el archivo inicial, se generó a partir de ejecuciones anteriores del código, en donde se crearon algunas galaxias.

En caso de que el usuario desee *modificar una galaxia*, esto se hace en base de las galaxias creadas anteriormente, que se encuentran en los archivos.
Por otro lado, si el usuario desea *jugar en una galaxia*, se le debe permitir seleccionar alguna de las galaxias existente. De esta manera, puede continuar jugando una partida anterior.

Espero que te haya quedado mas claro! Lee la sección 6 nuevamente y con calma.

**Comment by Pipelao** [comment]
Entonces si entendí bien, ¿el usuario tiene 4 alternativas en un comienzo: Crear galaxia, modificar galaxia, consulta sobre galaxias y jugar en la galaxia?

**Comment by leolivares** [comment]
@Pipelao Exacto!

**Comment by Pipelao** [comment]
@leolivares Muchas gracias :)
