### ISSUE TITLE
Duda NUM_BARCOS - T00

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#118]
El usuario elige la cantidad de barcos con los que se va a jugar? O se determinan de manera random?

**Comment by emiliaup** [comment]
Tengo la misma pregunta en el archivo parametros sale que NUM_BARCOS = 3, RADIO_EXP = 3. Eso es en todos los casos con los barcos y r? o tiene que ser random?

**Comment by Tsbalart** [comment]
Hola @YehudaGurovich  y @emiliaup!
La gracia de los parámetros que están en parametros.py es que puedan modificarse sin generar problemas en el código. Estos datos los ingresaras tu mismo antes de que se inicie una partida, no el jugador. y eventualmente podrían cambiarlos los ayudantes para probar que tu juego sea aprueba de error.
Espero que se haya entendido, 
Exito con la tarea!

**Comment by rodrigopg908** [comment]
entonces se puede asumir que el numero de barcos nunca superara la cantidad de espacios disponibles en el tablero?
por ejemplo, num_barcos nunca sera mayor a 9 si el tablero es de 3x3 o hay que implementar en el codigo una condicion para que esto no suceda?

**Comment by Tsbalart** [comment]
Hola @rodrigobj99!
Si, puedes asumir que eso no sucedera.
Exito con la tarea!
