### ISSUE TITLE
Interfaz no carga al ejecutar desde main.py

### ISSUE THREAD

**Issue by giacop002** [IIC2233/syllabus#1180]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola,
Antes de empezar a construir la ventana principal del juego, decidí hacer una ventana de chat para asegurarme que me funcionara bien el envío de información entre servidor-clientes (el protocolo ya lo tengo listo). Mientras la hacía, la iba probando usando `if __name__ == "__main__:"` desde el mismo archivo, y así logré hacer una ventana de chat con la que quedé satisfecho. Sin embargo, al ejecutar el archivo main.py del cliente (con el servidor ya corriendo), se abre una ventana pero se queda cargando, sin mostrar nada. No me tira error ni nada, simplemente no carga, y al clickear la ventana se queda pegada, pero nada más.
**Hay algún error de modelación "común" o algo que haga que una ventana no cargue?** (En vez de simplemente no aparecer o aparecer vacía, en cuyo caso probablemente tendría que ver con `.show()`)

Gracias de antemano

![image](https://user-images.githubusercontent.com/62019269/100701520-9a25da80-337e-11eb-8506-66daa8d1d816.png) 
![image](https://user-images.githubusercontent.com/62019269/100701823-2801c580-337f-11eb-8fba-4ce4329200f1.png)

**Comment by lucasprato** [comment]
Hola @giacop002!

Por lo que vi en tu repo, estás un poco enredado con el uso de la interfaz. El objetivo de la interfaz es ser quien maneje las conexiones entre la lógica del backend y las vistas del frontend. Dado que en la interfaz es donde se manejan las conexiones, es allí donde se deben instanciar las señales. Es también en la interfaz donde instancias objetos del frontend. (La interfaz se instancia dentro en el backend.)

A continuación relato el flujo. Pongamos de ejemplo que quieres visualizar un mensaje en el frontend.
1. En la `Interfaz` instancias una señal (antes del init), ej. `enviar_mensaje_signal`
2. En el `init` de la `Interfaz`conectas la señal con el método correspondiente del frontend.
3. En la `Interfaz` creas un nuevo método, ej. `enviar_mensaje`. Este método **emite** la señal `enviar_mensaje_signal`
4. En el `Cliente` cuando quieras enviar un mensaje, simplemente deberás hacer del estilo `instancia_interfaz.enviar_mensaje(mensaje)`

De esta manera, cuando se llame al método de la instancia `Interfaz` en el cliente, esta emitirá la señal `enviar_mensaje_signal`, la cual está conectada con el método correspondiente del frontend que se encargará de visualizar el mensaje en la ventana.

Es clave entender que la interfaz es una zona intermedia entre el backend y el frontend, por lo que no debe haber lógica ni visualización. Solamente hay señales y conexiones entre métodos e instancias de ambos lados. Es por ello que tu método `manejar_mensaje ` corresponde a una tarea que se debería realizar en el backend y no en la interfaz.

Espero te sea de ayuda y éxito en la tarea!

**Comment by giacop002** [comment]
Hola, gracias por la respuesta :)
Me ayudó a tener esa parte harto más ordenada, pero sigo teniendo el mismo problema que la ventana no me carga cuando ejecuto el main.py del cliente uwu

**Comment by lucasprato** [comment]
Hola @giacop002, si sigues con el problema porfa pushea tu repo para revisarlo.
Saludos!

**Comment by giacop002** [comment]
@lucasprato gracias, ya hice push :)
avancé un poco con la sala de espera pero sigo con el mismo problema, ahora se me abren las dos ventanas y no carga ninguna uwu

**Comment by lucasprato** [comment]
@giacop002, probé tu código y se me caía al tiro. Elimina todo ese `while True` después del `ConnectionRefusedError`. También la idea de conexión es que **a través de señales** aparezca la ventana, por lo que justo después de instanciar la variable `thread` deberías llamar a **un nuevo método de la interfaz** que emita una **nueva señal**. La idea de esta señal es que se conecte al `show` de la `SalaEspera`. Probé eso y se habría correctamente. Ahora bien, habían otros errores en tu programa ajenos a las conexiones que hacían que se cayera el programa. Tienes que encargarte de reparar eso.

No es adecuado que el método `manejar_mensaje` esté en la `Interfaz`. En cambio, debería estar en el `backend`. **La interfaz se limita a la conexión a través de las señales entre en front y el back**. El trabajo previo que a veces se hace en este método pertenece al `backend`.

Éxito en la tarea!

**Comment by giacop002** [comment]
ok, muchas gracias por tu ayuda :))
