### ISSUE TITLE
Decidir turnos jugadores

### ISSUE THREAD

**Issue by josefeliuf** [IIC2233/syllabus#1180]
Hola!
Hay alguna forma en específico de decidir los turnos de los jugadores? y de ser así, cual sería?

**Comment by DCCollao** [comment]
Hola @josefeliuf! No especificamos una forma de definir el los turnos de los jugadores, por lo que queda a tu criterio cómo lo definirás, pero recuerda mencionarlo en tu `readme.md`

**Comment by josefeliuf** [comment]
Dale muchas gracias! @DCCollao
