### ISSUE TITLE
Excepts para cerrar conexiones

### ISSUE THREAD

**Issue by vobrador** [IIC2233/syllabus#1181]
Holaa, a partir de las actividades (AF06) y la ayudantia (AY10), tengo entendido que estaria bien manejar errores para cerrar conexiones entre clientes-servidor o/y servidor-clientes, cosa que ya hice. De todas maneras lo queria preguntar porque en su minuto me sono poco intuitivo y agradeceria mucho una breve explicacion de esto :) muchas gracias.

**Comment by gatochico** [comment]
Hola!

Sí puedes usar manejo de errores para lo que indicas (y en general, puedes usar manejo de errores en cualquier parte que creas sea pertinente). Lo único que se pide es que se manejen de forma correcta, atrapando el error en específico que se espera aparezca y no simplemente usando `except:` o `except Exception:` a ciegas, ya que esto ultimo es lo que es considerado mala práctica.

Saludos!
