### ISSUE TITLE
Construir carreteras ante choza de rival

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2233/syllabus#1181]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! Tengo una duda sobre donde se pueden poner carreteras pues tengo la duda si por ejemplo me cortan el camino por una choza. A lo que voy es por ejemplo tengo Choza-Carretera-Carretera, pero luego el rival poner una choza y queda Choza-Carretera-Carretera-Choza Rival, ¿puede el jugador poner un camino después de que el rival haya puesto la choza? Considerando que hay caminos libres para construir. Es decir, si puedo hacer:
Choza-Carretera-Carretera-Choza Rival-Carretera, con la carretera siendo del jugador y no del rival 
Gracias de antemano! 😄

**Comment by EduardoIllanes** [comment]
Hola @Jamesmoreno21! Lo que pones no es correcto ya que para construir una carretera 

> esta debe ubicarse junto a una choza o a otra carretera **ya existente del mismo jugador**

Saludos 😄

**Comment by Jamesmoreno21** [comment]
Ok! Es que me enreda un poco esta regla, ya que pregunté el caso opuesto en la  issue #1113, donde un rival si puede cortar un carretera, que en otras palabras sería que si por ejemplo tengo Choza-Carretera-Carretera-Carretera y el construye una choza entremedio se puede, y quedaría Choza-Carretera-Carretera-Choza Rival-Carretera, que es el resultado que te comenté antes pero en otro camino. Así que asumo que si se puede cortar una carretera pero no se puede construir una carretera cortada sólo por una choza rival, o me equivoco?
Gracias nuevamente! 😄

**Comment by EduardoIllanes** [comment]
> Así que asumo que si se puede cortar una carretera pero no se puede construir una carretera cortada sólo por una choza rival

Así es! Mucho éxito en tu tarea 🚀
