### ISSUE TITLE
Cartas monopolio y victoria en interfaz

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#1182]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! En la interfaz de ejemplo que se da en el enunciado abajo a la derecha hay una imagen de carta de victoria y la cantidad que hay de esta (supongo, no está explicado). Me surge la duda de por qué está esto si la carta de desarrollo que se le de al jugador, se pide que desaparezca de su mazo, por lo que este número de cantidad de cartas de victoria siempre será 0 🤔
Entonces, ¿Entendí mal la función de esa parte de la interfaz o, si está bien lo que estoy pensando, podría omitir poner eso en la interfaz ya que siempre será 0?

Espero que se entienda jajaaj 😥

**Comment by matiasmasjuan** [comment]
Hola @denisseleiva !

En el ejemplo de la interfaz del enunciado:

![sala_juego_4](https://user-images.githubusercontent.com/48495638/100762354-a2a80080-33d2-11eb-8a43-216abf6f3439.png)

Los puntos de victoria en la esquina inferior derecha, **no hacen referencia** a las cartas de desarrollo, ya que como tu bien dices, estas se eliminan de la mano al ser utilizadas. Estos puntos de victoria hacer referencia a los **puntos acumulados** por **todas** las **cartas de puntos de victoria** compradas por el jugador. En particular, en el ejemplo se muestra que ha comprado **0** cartas de puntos de victoria. Por eso es que sólo tiene 4 puntos. En caso de que haya comprado en algún momento **2 cartas** de **puntos de victoria**, entonces aparecería un **2** en lugar de un **0**, y el **total de puntos** sería **6** en lugar de 4. 

De todas formas, según el enunciado **no es obligación** mostrar cuántas cartas de puntos de victoria ha comprado el usuario. Sin embargo, esto podría ayudarte a corroborar si efectivamente se están contando bien los puntos de victoria del jugador.

Saludos! y mucho éxito con la tarea! :smile:

**Comment by denisseleiva** [comment]
Okaaa, gracias por la aclaración! 😁
