### ISSUE TITLE
Estética gráfica.

### ISSUE THREAD

**Issue by JoseTomasSoto** [IIC2233/syllabus#1183]
Al abrir una ventana (diseñada en Designer) en la pantalla de mi computador está superpuesto y se ve mal, pero al moverlo a mi monitor, está todo perfecto, esto es un problema? o da lo mismo?

**Comment by DCCollao** [comment]
Hola @JoseTomasSoto!

Es bastante común que hayan diferencias en cómo se ve una interfaz de PyQt5 en diferentes pantallas cuando estas tienen resoluciones distintas. 
¿Tus pantallas tienen resoluciones diferentes?

Si no es el caso, y te llegaran a descontar nota por esto en la evaluación, es posible una recorrección en donde muestres que en tu pantalla el programa se veía bien.
