### ISSUE TITLE
Dudas funcionamiento gritar DCCuatro

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#1183]
Cuando un jugador grita DCCuatro y recibe una penalización y deber robar cartas, pero no es su turno, entonces ¿debe esperar a su turno para robar?, ¿debe robar inmediatamente?. Y si es que fuese el caso de que debe robar inmediatamente, ¿el resto de los jugadores deben esperar que robe para poder seguir con los turnos? o juegan en paralelo mientras el roba cartas.

**Comment by rieg-ec** [comment]
tengo claro que debe robar automáticamente, pero dejo mi ward por si acaso para saber también :D

**Comment by szabala** [comment]
Hola! Si un jugador grita DCCuatro erróneamente, debe robar automáticamente aunque no sea su turno. Queda a tu criterio si los demás jugadores deben esperar a que robe o juegan paralelamente (aunque no debiera afectar el flujo del juego).

**Comment by lewebe** [comment]
Hola @szabala ! Y qué pasa si alguien grita DCCuatro y hay más de un jugador con una carta (asumiendo que ninguno había gritado DCCuatro para salvarse)?

**Comment by szabala** [comment]
Hola! Esto se responde en esta _issue_ #1030
Saludos 👋

**Comment by felipefuentesporras** [comment]
Si entendí bien, cuando te refieres a robar automáticamente, ¿igual el jugador tiene que robar el manualmente o no?

**Comment by szabala** [comment]
Si! disculpa la confusión, aun cuando un jugador diga DCCuatro erróneamente este debe apretar el mazo (o el botón correspondiente) para efectuar el robo. Por simplicidad, puedes hacer que el turno del jugador actual prosiga una vez los demas hayan robado las cartas necesarias.
Éxito con la tarea!

**Comment by felipefuentesporras** [comment]
yaaa, perfect. La ultima duda. ¿Si es que yo tengo 1 carta y digo DDCuatro, se le debe avisar a todos los jugadores que grite? y si yo tengo 1 carta y grito DCCuatro y otro jugador que tenia 1 carta no lo habia gritado, este ultimo ¿debe ser penalizado?.

**Comment by szabala** [comment]
Queda a tu criterio si avisarle o no a los demás jugadores (me parece muy útil hacerlo para probar la funcionalidad). En cuanto a la segunda pregunta, se responde con claridad en esta _issue_ #1030
Espero haber aclarado tu duda :smile:
