### ISSUE TITLE
Turno jugadores interfaz

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#1184]
Hay un orden en especifico en que se deban ver los otros jugadores en cada interfaz. Por ejemplo, debe estar a mi derecha el que venga despues de mi? o de lo mismo el orden de los jugadores

**Comment by jirarrazabal** [comment]
Hola! La idea es que en la interfaz esté a la derecha o a la izquierda el jugador que le toque el siguiente turno, para que el juego fluya en forma de círculo. Así hace más evidente a quien le toca a medida que progresa el juego y cuando se cambia de sentido. Suerte!
