### ISSUE TITLE
Metodo show() no funciona

### ISSUE THREAD

**Issue by OrregoSilva** [IIC2233/syllabus#1184]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Por alguna razón, cuando quiero que la ventana del juego aparezca (le hago ventana_juego.show()), esta no aparece y el programa como que se detiene y no tira ningún error, y eso que con la ventana de la sala de espera estoy haciendo algo prácticamente igual. Alguno me podría ayudar? En mi carpeta de Client hay un archivo backend.py, en las lineas 51 y 53 coloque unos print para que se vea en donde se muere el programa (linea 52).

EDIT: Trate se hacerlo mediante las señales que conecto en conectar_señales_2() y tampoco abre la ventana

**Comment by Benja-c** [comment]
Hola me pasa lo mismo no me funciona el metodo show, niquiera me abre la tarea 2 que antes funcionaba bien 🙃

**Comment by Juampisaez** [comment]
Hola @OrregoSilva 
Estuve probando tu codigo y me funciona super, no me muestra ningun error y de hecho se muestra la interfaz y el log super bien. Me parece que el problema puede ir con python mas que nada (aveces pasan estos errores). Puedes probar desinstalando todo lo que tengas de Python e instalar un version distinta (fijate que la version sea acorde a los bits de tu pc). Avisame si se logra solucionar :)

**Comment by OrregoSilva** [comment]
Hola!
Al final lo que ocurría era algo bien extraño, pasaba que si el widget lo instanciaba al momento de necesitarlo (osea cuando ya tenia todos los clientes), se pegaba, pero si lo instanciaba al momento de ejecutar un cliente y le iba actualizando los datos a medida que los demas se conectaban (lo que me genero muchas mas lineas) iba bien. No se exactamente lo que ocurria al final, aun asi muchas gracias @Juampisaez !
