### ISSUE TITLE
Uso de Base64 en T03

### ISSUE THREAD

**Issue by DmBeta101** [IIC2233/syllabus#1185]
Hola tengo una duda,

Se puede usar la librería Base64 en la Tarea 3?
Gracias de antemano por la respuesta

**Comment by benjavicente** [comment]
No han actualizado la lista, pero [mencionaron que se puede](https://github.com/IIC2233/syllabus/issues/1026#issuecomment-647743737).

**Comment by DCCollao** [comment]
Hola @DmBeta101! Como te bien te citó @benjavicente, este tipo de preguntas va en la issue específica de librerías de la tarea.
