### ISSUE TITLE
no se muestra la ventana de sala de espera

### ISSUE THREAD

**Issue by feliperojas123** [IIC2233/syllabus#1185]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

holaaa buenaas. resulta que mi codigo lee la señal entra al fronted lo modifica y al momento de hacer show no me abre nada.. lo que pasa es que se habre un cohete de python pero no muestra ninguna venta. mi sistema operativo es macos. nose que hacer la vda.. si alguien me puede ayudar plis

**Comment by sofiaolmedos** [comment]
Hola!! Perdon por colarme a la issue pero tengo el mismo problema. Al principio se me abría la ventana pero no se cargaba y ahora simplemente no pasa nada. Revisé y no falta ningún ```super().__init__()``` :c

**Comment by feliperojas123** [comment]
oooh muchaaas gracias hare los cambios y te digo si me resulta o no... te pasateeeeeee

**Comment by feliperojas123** [comment]
una pregunta. acabo al parecer de hacer todos los arreglos que has dicho pero la verdad no me resulta. me sigue apareciendo el mismo cohete sin mostrar la ventana. lo subire para que se pueda observar

**Comment by rodrigobj99** [comment]
Hola @feliperojas123 que raro, acabo de correr lo que tienes en tu repo y si me aparece la ventana, mi sistema operativo también es macos. Lo único que se me ocurre es definir y conectar las señales en `cliente.py`.

Saludos!

**Comment by rodrigobj99** [comment]
@sofiaolmedos te agradecería que abrieras una nueva [issue](https://github.com/IIC2233/syllabus/issues/new/choose) sobre tu problema, ya que este tipo de problemas suelen ser muy específicos y muchas veces tienen soluciones muy distintas. Además así es probable que revise tu código alguien con tu mismo sistema operativo y con eso descartar esos errores.

Saludos!

**Comment by feliperojas123** [comment]
holaa cambie las señales al cliente. ahora el cliente tiene las señales y hace todo el trabajo y me sigue sin funcionar. no me entra a la señal en fronted la de mostrar_label no me printea lo que tengo hay para ver y si hay señal y nuevamente me habre ese cohete que deberia ser la señal

**Comment by rodrigobj99** [comment]
Hola @feliperojas123 , que version de macos tienes instalada? Puede ser el problema de Big Sur.

Saludos!

**Comment by feliperojas123** [comment]
holaaa tengo la version macos high sierra 10.13.6, la actualizo???

**Comment by rodrigobj99** [comment]
No, no es necesario, con la que tienes esta bien, la versión Big Sur es la que tienes problemas, asi que no actualices a esa. Prueba eliminando el `self.repl()` de `cliente.py` ya que eso puede causar el error, y dado que no es necesario recibir inputs por consola. Por ultimo la otra opción es que sea la versión de PyQt5 instalada, cual tienes?

**Comment by feliperojas123** [comment]
ooooh graciaaaaas al fin pude ver la ventana te pasaste @rodrigobj99... enserio muchas gracias
