### ISSUE TITLE
Sobre envio de cartas T03

### ISSUE THREAD

**Issue by jmg-git** [IIC2233/syllabus#1186]
Hola! Tengo dudas respecto al formato de envio de cartas, no entiendo la parte que dice que hay que asignar un identificador numérico a cada tipo de objeto enviado, y porque después piden enviar todo el objeto serializado. No sería información redundante? Ademas no me queda claro porque se exigen que los tamaños de los dos primero bloques sea de 4 bytes, si para el primero tenemos (color, numero, imagen) y el segundo bloque es un numero que indica el largo de la serializacion. Si es que pueden darme un ejemplo para ejemplificar seria genial :). 
Gracias de antemanooo

**Comment by fdoflorenzano** [comment]
Hola @jmg-git,

Esa sección de la tarea en general tiene como intención simplemente describirles una especificación de estructura de mensajes y evaluar si son capaces de seguir e implementar dicha especificación. Efectivamente pueden haber datos redundantes para efectos de la tarea, pero estos siguen una lógica común de estructuración de representaciones de *bytes* de objetos.

La lógica general es la siguiente: primero identificar lo que está mandando, luego identificar el largo del contenido a mandar, y luego el contenido mismo. El identificador ayuda a saber como interpretar el siguiente contenido que se enviará. Como el orden entre componentes es siempre es el mismo, es verdad que probablemente es redundante el identificador, pero aún así ayuda. Tanto el identificador como el largo se especifican usando 4 *bytes* para dejar como estándar cuantos *bytes* se leerán en esas opciones. Si enviáramos la información sin saber el largo que tiene, puede traer complicaciones. Mientras más *bytes* se usan para representar un entero, más alto es el número que es capaz de representar (tiene un límite superior), pero para efectos de la tarea, es más que suficiente para el contenido que podrán intercambiar.

Espero se entienda, cualquier duda puedes escribirla.

Saludos.
