### ISSUE TITLE
Manejo Compra chozas y caminos por el Usuario

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC2233/syllabus#1186]
### Prerrequisitos:

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Mi duda es si para que el jugador compre una nueva choza o camino, debe colocar la choza o camino obligatoriamente mediante drag and drop o podría crear otra forma de realizar esto que sea igual de intuitiva?

**Comment by rodrigobj99** [comment]
Hola @SebaHagedorn 
El manejo para realizar compras de chozas o caminos lo puedes realizar de la forma en que prefieras, ya sea con drag and drop o haciendo click o de alguna otra manera que te resulte conveniente.

Saludos y exito en la tarea!

**Comment by SebaHagedorn** [comment]
Buenísima, Gracias!
