### ISSUE TITLE
serializar cartas

### ISSUE THREAD

**Issue by mleon17** [IIC2233/syllabus#1187]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mleon17** [comment]
Hola! Queria saber si es necesario serializar las cartas (desarrollo, materiales, etc)

**Comment by rodrigobj99** [comment]
Hola @mleon17 !
Tal como indica el enunciado, lo único obligatorio es cumplir con el protocolo de envío de mensajes, el cual no exige serialización, por lo tanto no es necesario serializar las cartas. Sin embargo es recomendable usar serialización ya sea en pickle o json para enviar la información y las cartas, ya que puede ser útil para enviar diversas estructuras de datos como listas, diccionarios o tuplas.

Saludos y éxito en la tarea!
