### ISSUE TITLE
Error imprime infinitamente

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#1187]
estoy trabajando en las situaciones donde alguien se desconecta, y quiero que por ahora me imprima un mensaje, pero al suceder, imprime el mensaje de manera indefinida, sin darme una manera de parar esta situación (con la excepcion de cerrar el servidor)

**Comment by gatochico** [comment]
Hola! Lograste solucionar este error? ¿Si no es así, puedes subir la versión más actualizada de tu código a tu repositorio para ayudarte a solucionarlo?

**Comment by felipehen** [comment]
Hola!

Siendo muy honesto, nisiquiera intente solucionarlo, decidi Comentar el print que se imprimia infinitamente, y trabajar en otras partes de mi programa para no quedarme estancado. Ya tengo todo subido!

**Comment by gatochico** [comment]
(Lamento la demora, jeje)

Por lo que veo en tu servidor atrapas bien la excepción cuando se te desconecta un cliente, sin embargo lo único que haces para manejarla es imprimir que se desconectó, por lo que el socket de  cliente desconectado sigue existiendo almacenado en el servidor. Entonces,el thread que escucha clientes seguirá escuchando ese socket del cliente desconectado y lanzará error todo el rato (por eso se te imprime de forma infinita, ya que ocurrira mientras el thread de escucha esté andando). 

Entonces, lo que debes hacer es manejar correctamente la excepción. Esto es que, cuando caigas en la excepción, tienes que identificar qué socket es el que se desconectó y proceder a sacarlo de la lista/diccionario/estructura de datos donde los guardas, ya que no te sirve más y es la fuente del error. No te puedo dar más detalles, pero esa es la idea principal a seguir 🙊 

Saludos!

**Comment by felipehen** [comment]
Gracias!!!
