### ISSUE TITLE
Recibir información dependiendo de si es pickle o json

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#1188]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Quiero enviar una clase ```Grafo``` desde el servidor al cliente, pero json no lo permite. Mi idea es serializarlo con pickle, pero el resto de la información enviarla con json (esto ya lo tengo implementado). Al momento de enviar, es cosa de poner cómo quiero que lo serialice, pero al momento de recibir, ¿cómo le puedo avisar al código que tiene que de-codificar con pickle y no con json?

Se me ocurre hacer un try / except dentro del try / except:
```
try:
    try:
        serializar con pickle
    except:
        serializar con json
except:
    error de que no puede decodificarse
```
Pero no se si se puede y el error que levantaría sería como genérico o no? ¿ Habrá una forma de decirle cómo quiero que lo decodifique?

**Comment by matiasmasjuan** [comment]
Hola @kalarconvl !

Hay dos formas en que puedes realizar esto **sin** necesariamente **alterar** el **protocolo de envío** de mensajes. El primero es, serializar y deserializar todo con **pickle** en lugar de json. De este modo te ahorras los posibles ```try /except``` que podrían surgir y tener una serialización mas fluida ya que serializas y des-serializas de la misma forma. Y lo segundo, es como tu bien dices, es hacer un ```try /except```. Evidentemente debes asignar el tipo de error, ya que de no hacerlo tendrás descuento por malas prácticas. En particular, podrías usar el ```except json.JSONDecodeError``` o ```except UnicodeDecodeError```.

Saludos! :smile:

**Comment by kalarconvl** [comment]
Ahh pero puedo hacer todo con pickle? Aunque en verdad es solo eso lo que quiero mandar con pickle, el resto está bien con json. ¿Como lo puse antes está bien si uso ```except UnicodeDecodeError```?

**Comment by matiasmasjuan** [comment]
**Sí**, puedes hacer todo con **pickle**. Sobre el uso de ```except UnicodeDecodeError```, siempre es mejor preguntar por la **issue** #1028 sobre librerías permitidas, no permitidas y malas prácticas.

Saludos!

**Comment by kalarconvl** [comment]
Y entre las dos opciones, ¿cuál será mejor? Usar solo pickle o ver lo del except?

**Comment by matiasmasjuan** [comment]
**Mi recomendación** (pero es algo completamente subjetivo y depende **mucho** de tu código) es cambiar de json a pickle. La razón de esto es porque apenas hay que cambiar 3 líneas del código.
Si antes tenias:
```python
mensaje_serializado = json.dumps(mensaje)
mensaje_bytes = mensaje_serializado.encode()
```
Ahora pasa a ser:
```python
mensaje_bytes = pickle.dumps(mensaje)
```
Ahora bien, todo esto depende de cómo esté implementado tu **protocolo**.

Saludos! :smile:

**Comment by kalarconvl** [comment]
Graciaaas! Estuve tratando de enviarlo así y cuando se conectan suficientes clientes y trata de abrirse la sala de juego, me sale:
```EOFError: Ran out of input``` ¿sabes por qué puede ser? Cuando empieza el juego, el servidor instancia el grafo y lo manda al cliente, según yo va por ahí pero no se que tengo mal

**Comment by kalarconvl** [comment]
El módulo con la función que instancia el grafo  se llama ```crear_grafo```. Este lo usa el servidor y después manda lo que crear grafo retorna. Pero en el cliente me sale: ```ModuleNotFoundError: No module named 'crear_grafo'```. No entiendo

**Comment by matiasmasjuan** [comment]
Con respecto al primer error, esto se debe a que intentas **serializar** y **deserializar** algún **bytearry** vacío o erróneo. De todas formas, siempre intenta buscar este tipo de errores en internet, **antes** de hacer algún comentario o *issue*.

El segundo error es porque el **modulo** ```crear_grafo``` no está en la carpeta del **client**, sino en la de **server**.

Saludos!

**Comment by kalarconvl** [comment]
Sobre lo segundo, claro, está en la de server porque ahí lo uso. ¿Tengo que poner crear_grafo en ambas carpetas?

**Comment by matiasmasjuan** [comment]
Si es que haces un ```import crear_grafo```, se espera que en ese directorio exista algún **módulo de python** que se llame ```crear_grafo```.

**Comment by kalarconvl** [comment]
Sipo, pero ese import lo tengo en el server donde se usa, no en el cliente, por eso no entiendo el error

**Comment by matiasmasjuan** [comment]
Lo que sucede es que al hacer un **print** del **objeto** **antes** de enviarla, te daras cuenta que dice algo como ```<crear_grafo.Grafo object at 0x7f42e027dac0>```. Por lo tanto, despues, al momento de hacer un **pickle.loads**, se espera que se encuentre ese módulo (```crear_grafo```) con la clase ```Grafo``` definida. De lo contraro, ocurrirá ese error.

Saludos!

**Comment by kalarconvl** [comment]
siii me pasa eso!! Entonces tengo que poner el mismo módulo en los 2 lados?

**Comment by matiasmasjuan** [comment]
**Sí**, a menos que quieras que la clase ```Grafo``` no esté definida ```crear_grafo``` sino que lo haces en el **mismo** módulo del servidor. En ese caso, no habría que definir el módulo ```crear_grafo``` ni en el servidor ni en el cliente, y hacer la clase ```Grafo``` en el módulo actual.
