### ISSUE TITLE
Problema con seguir el juego

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#1188]
Actualmente mi codigo, esta listo hasta determinado punto. Todos los jugadores son capaces de entrar en la sala de juego, reciben sus cartas iniciales, e incluso se actualizan el pozo y las "Cartas de sus oponentes" (este ultimo caso, muestra sprites de los "reversos de las cartas" para representar cuantas cartas tiene cada jugador.

incluso, si el jugador de turno hace click en una de sus cartas, esta es enviada y el servidor revisa si es jugable segun las reglas y responde con la respuesta correspondiente. 

Pero tengo un problema con esto mismo. Justo despues de que el primer jugador envia su carta, y el servidor la acepta (osea pasa de turno), el servidor se bloque y no recibe mas informacion. 

Descubri esto gracias a los distintos print que tengo en el programa, mostrandome como el mensaje es enviado, e incluso, es recibido por el servidor. Pero cuando este recibe, imprime el mensaje diciendo que esta recibiendo algo, pero deja de avanzar.

aca muestro dicha funcion para explicar de mejor manera: 

def escuchar_cliente(self, socket, IP):
        try:
            with th.Lock():
                print("Recibiendo info")
                orden = socket.recv(4)
                print(orden)

El primer print, si es imprimido, pero el segundo, no. Lo cual me llega a pensar que hay un problema con el recv, pero dado que e avanzado tanto sin ningun problema me hace dudarlo. Ademas, no se me levanta ninguna excepcion.

Muchas gracias de antemano

Pd: Tengo subido todo este codigo en mi repositorio, por si es necesario para verificar informacion.

**Comment by fdoflorenzano** [comment]
Hola @felipehen,

Revisé tu código y efectivamente pasa lo que indicas. Me perece el problema es algo relacionado a como manejas los turnos y escuchas a los clientes desde el servidor. 

Primero, tus clientes solo mandan acciones si es tu turno, y sospecho se queda bloqueado el servido porque se queda esperando a un cliente específico a que envié algo. Pero este cliente cree que no es tu turno, entonces no envía nada. Lo que hice para verificar esto fue modificar tu `print` a: `print(f"Recibiendo info de: {socket}, {IP}")` en servidor, y pude comprobar que se queda esperando a recibir algo del cliente que no enviaba nada por crees que no era su turno.

Eso me lleva mi segunda observación, tu servidor escucha a los clientes, pero es un solo *thread* el que escucha a todos los clientes en el orden en que se conectan. Eso hace imposible que un cliente le envíe un mensaje mientras es el turno de otro jugador. Aún peor, es que si envía un mensaje un cliente que no está siendo escuchado porque está después en la cola, por la naturaleza de los sockets, el mensaje queda guardado hasta que se lea, entonces potencialmente se procesan mucho después esos mensajes. Este detalle es importante para entender como funciona tu servidor, y te aconsejo considerar cambiarlo.

Espero se entienda y te ayude, nos comentas cualquier cosa.
Saludos.

**Comment by felipehen** [comment]
Claro, por la forma que tiene mi codigo, tiene logica. Pero, ¿como podria hacer que escuche a todos mis clientes al mismo tiempo, sin utilizar dicho metodo de "cola de clientes"?

**Comment by fdoflorenzano** [comment]
Por ejemplo, dedicando un *thread* a cada cliente. Como mostrado en el [cuaderno de los contenidos](https://github.com/IIC2233/contenidos/blob/master/semana-14/3-ejemplos.ipynb), y como sugerido en la [AF06](https://github.com/IIC2233/syllabus/tree/master/Actividades/AF06/).

Saludos.

**Comment by felipehen** [comment]
Si justo me habia acordado de ese cuaderno, voy a intentarlo, gracias
