### ISSUE TITLE
error al importar parametros

### ISSUE THREAD

**Issue by domja** [IIC2233/syllabus#1189]
Intente importar los parametros ocupando:
parametros = json.load(open('servidor/parametros.json', 'r'))
pero me da el siguiente error:
JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 21)

Alguien sabe porque puede ser??

**Comment by jirarrazabal** [comment]
Hola! Este error puede estar sucediendo debido a que en tu archivo parametros.json tienes múltiples diccionarios, en lugar de un gran arreglo. Si este es es el caso, intenta juntarlos en una lista de diccionarios o en un diccionario más grande. Suerte!
