### ISSUE TITLE
Simulacion

### ISSUE THREAD

**Issue by gbordoni** [IIC2233/Syllabus#119]
Buena cabros
Tengo una duda con la sensibilidad de la simulacion. En un issue pasado dijeron que podiamos asumir que el tiempo transcurria en minutos. Pero en la simulacion minuto a minuto para actualizar el radio, puntos de poder, recursos, etc, el tiempo de ejecucion me sube demasiado. Mi pregunta es, podría hacerlo por horas y especificarlo en el readme? 
Habría un poco de pérdida de sensibilidad (por ejemplo si ocurre algun evento en un incendio a las 12:40, en la simulación esto se comenzaría a considerar a las 13:00), pero sería mínimo, y hace que el programa corra mucho mas veloz.

saludos

**Comment by DiegoAndai** [comment]
#68 Es eso lo que buscas?

Saludos

**Comment by gbordoni** [comment]
Si había leído lo de minuto a minuto...a lo que voy es si es que existe alguna posibilidad de hacerlo hora por hora (o si es que lo hago y no se puede cuando me descontarían). 
Porque en verdad el codigo es exactamente el mismo, para hacerlo por minutos solo hay que multiplicar las horas * 60 y ajustar la tasa en que crece el radio, pero la cantidad de ciclos sube tanto que el programa deja de correr fluidamente.

**Comment by DiegoAndai** [comment]
Si tu problema es la fluidez, trata de darle un par de vueltas a la manera en que estás calculando lo que ocurre. Quizás no necesites tantos ciclos como estás pensando. Lo que si debe cumplir tu programa es que DEBE ser continuo con respecto al tiempo. En el issue que mencioné preguntaron también por fluidez y se recomendó leer:

https://en.wikipedia.org/wiki/Lazy_evaluation

Te recomiendo pensar una manera en que tu programa sea fluido y puedas tener también exactitud en las consultas.

PS: Si ves un issue muy relacionado con lo que vas a preguntar, intenta preguntar ahí para que el foro esté más ordenado y así todo funciona mejor 😄 

Saludos

**Comment by gbordoni** [comment]
@DiegoAndai Dale muchas gracias, y sorry por abrir un nuevo issue.

Una ultima con respecto a esto: que van a privilegiar mas al corregir? Que el programa tenga continuidad minuto a minuto, pero que se demore? O que sea fluido pero que simule hora a hora y pierda algo de continuidad y exactitud??

**Comment by negutierrez** [comment]
@gbordoni yo tenía el problema que se me demoraba muchisimo en simular, después noté que dentro de los ciclos creaba muchas clases, lo que gastaba mucha memoria. quizás sea eso

**Comment by DiegoAndai** [comment]
@gbordoni Esa información no se puede compartir, la idea es que ustedes comprendan desde el enunciado lo fundamental y lo que les estamos pidiendo. Recuerda que esta tarea tiene énfasis en OOP y modelación, por lo tanto un mal uso de la primera o una mala modelación puede perjudicarte. Con respecto a este último punto, parte de una solución correcta implica eficiencia. Tu tarea no solo debe ser funcional, debe presentar una ejecución razonable. No dejo de recomendarte que pienses bien lo que estás haciendo y veas donde se puede mejorar, sobre todo si es demasiado tu tiempo de ejecución.

Eso si, cuando reciban sus notas recibirán también el feedback con el desglose del puntaje, para que sepan en qué se asignaron los puntos.
