### ISSUE TITLE
Cuando el grupo no tiene participantes

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#119]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Si queda solo 1 o 0 participantes en un grupo se eliminan los mensajes? hay algún comportamiento en especial que deseen que programemos en este caso?

**Comment by Juampisaez** [comment]
Hola @fernandosmither 
Esto ya se respondio en la issue **Duda sobre integrantes mínimos en el grupo #96**

Cualquier otra duda quedo atento :)
