### ISSUE TITLE
Duda sobre volver al menú de inicio

### ISSUE THREAD

**Issue by clementesanchez** [IIC2233/Syllabus#119]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Mi duda es si al volver al menú de inicio, la partida se tiene que reiniciar, es decir la deuda total tiene que volver a su monto original. O si al volver al menú de inicio la deuda total tiene que permanecer como estaba, por lo que podría seguir siendo saldada por otro personaje. Gracias!

**Comment by tamyhan** [comment]
Hola Clemente! Sí, al volver al inicio se debe reiniciar la partida y por lo tanto, la deuda debe volver al monto original.
