### ISSUE TITLE
Entidad v/s Objeto T01

### ISSUE THREAD

**Issue by fnberrios** [IIC2233/syllabus#119]
Hola! Para la tarea T01, ¿cuál es la diferencia entre una entidad y un objeto?
Gracias de antemano.

**Comment by gatochico** [comment]
Hola @fnberrios!

Para efectos de esta tarea tanto entidad como objeto hace referencia a una **instancia** de una **clase definida por ti**. Por ejemplo, si hicieras una clase `Auto` y definieras `auto = Auto()` entonces `auto` sería tanto una entidad como un objeto.

En términos generales de programación entidad es más abstracto que objeto. Entidad hace referencia a la representación de algo dentro de un programa, mientras que objeto se refiere especificamente a una representación orientada a objetos.

Sin embargo en Python todo es un objeto, asi que en términos prácticos es lo mismo.

Espero haberte ayudado!

**Comment by fnberrios** [comment]
Bkn, gracias! @gatochico
