### ISSUE TITLE
Archivos que incorporar al .gitignore

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2233/syllabus#119]
Hola! En el enunciado de la tarea dice que se deben incluir "los archivos indicados en Archivos Entregados" al .gitignore. Sin embargo, nuestro código debe importar estos archivos y ocupar sus funciones y definiciones. ¿No debemos incluir estos archivos en nuestros git add puesto que los ayudantes incorporarán los archivos al momento de correr nuestros códigos?

**Comment by Tsbalart** [comment]
Hola @ignaciomansuy!
Efectivamente estos archivos serán incorporados a las respectivas carpetas de sus tareas por lo ayudantes. El objetivo de esto, es aligerar lo mas posible el tamaño de los repositorios de los alumnos para disminuir el tiempo de subida por parte de ustedes y el de bajada por parte de los ayudantes.
Exito en la tarea!

**Comment by DCCollao** [comment]
Esta issue ya fue resuelta en #93. Antes de publicar una issue es ideal que busquen en el compilado de issues #88 si alguien ya preguntó lo mismo, así evitamos issues repetidas. En caso de que algo no quede claro, comentar en la original.
Éxito!
