### ISSUE TITLE
Jugar en la galaxia 

### ISSUE THREAD

**Issue by Cschavez** [IIC2233/Syllabus#119]
Hola! La tarea dice que al momento de jugar con una galaxia parte con 1000 de minerales y 1000 de deuterio, entonces, esto es independiente de la cantidad de minerales y deuterio que el jugador haya ingresado al momento de crear una galaxia?
Otra pregunta, al modificar una galaxia aumentando la cantidad de soldados en un planeta no conquistado, también se tiene que tener en consideración si es que la galaxia tiene la cantidad de minerales y deuterio suficiente? o esta consideración solo se hace en "Generar unidades" (6.4.1 Visitar Planeta).
Muchas gracias !

**Comment by Cschavez** [comment]
Otra pregunta, al modificar una galaxia aumentando la cantidad de soldados en un planeta no conquistado, también se tiene que tener en consideración si es que la galaxia tiene la cantidad de minerales y deuterio suficiente? o esta consideración solo se hace en "Generar unidades" (6.4.1 Visitar Planeta).
Muchas gracias !

**Comment by IchottMano** [comment]
@Cschavez Hola!
En primer lugar como dice el enunciado, al empezar a jugar con una galaxia partes con 1000 de cada recurso.
En segundo lugar, cuando modificas la galaxia a modo de aumentar la cantidad de soldados de un planeta no conquistado sólo debes preocuparte de no sobrepasar los límites de población, por lo que no debes preocuparte de los minerales, lo cual sólo debes hacer cuando eres tú la que crea unidades dentro del juego.
Saludos y mucho éxito con tu tarea!
