### ISSUE TITLE
detalles de las acciones de los usuarios de la base de datos

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#119]
del enunciado: "Para esto es necesario que se guarde la hora y los detalles de las acciones (los valores de
los conceptos en italicas) en los siguientes casos
- ...
- **Sistema realiza un match entre dos orders** "
Que pasa con los matches que ya fueron realizados en la base de datos entregada?

**Comment by cilopez** [comment]
@nmaturana97  podrías dejar algo así como una fecha predeterminada para estos casos, que tenga cierto sentido, de ser así especificalo en tu *readme*.  ¡Saludos!
