### ISSUE TITLE
Imposibilidad de leer archivos en VSCode pero si en IDLE

### ISSUE THREAD

**Issue by TeresitaS** [IIC2233/syllabus#119]
Hola,
Estoy teniendo problemas al interactuar con archivos en VS Code. Al principio pensé que era un problema del código pero lo corrí en IDLE y si me funciona. He trabajado todo el tiempo en IDLE pero llega al punto que ya no esta tan amigable. Hoy día en la actividad me trato de ayudar un ayudante pero no logre solucionar el problema. (PD: tengo un Mac)

**Comment by DCCollao** [comment]
Hola @TeresitaS !

¿Cómo estás ejecutando los archivos en vscode?
¿Qué error te muestra?

**Comment by TeresitaS** [comment]
a=name_existe(name, "usuarios.csv")
  File "/Users/Teresita/Desktop/repolocal/TeresitaS-iic2233-2020-1/Tareas/T00/Funciones.py", line 4, in name_existe
    with open ("usuarios.csv", "rt", encoding = "utf-8") as archivo:
FileNotFoundError: [Errno 2] No such file or directory: 'usuarios.csv'

**Comment by DCCollao** [comment]
¿Cómo estás ejecutando el archivo en vscode?

**Comment by based-on-what** [comment]
Tengo exactamente el mismo problema, al momento de correrlo en el cmd, no imprime nada al entrar al ciclo del archivo "usuarios.csv", pero en IDLE imprime sin ninguna complicación
