### ISSUE TITLE
Duda con probabilidad y costo de crear un objeto

### ISSUE THREAD

**Issue by bernirosas** [IIC2233/Syllabus#119]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! En la parte de entrenador sale "Crear objetos: Con esta acción el entrenador buscar crear los objetos, para esto gasta ENERGIA_CREAR_OBJETO dependiendo del objeto. La creación o no de los objetos depende de PROB_EXITO_OBJETO". 
Mi pregunta va con que no entiendo como definimos ENERGIA_CREAR_OBJETO en parametros.py ya que depende de cada objeto y no es constante. En la parte de objeto dice "Por último, los atributos de esta entidad se encuentran en objetos.csv y son: (...)
Costo: Corresponde a un número que representa la energía que ocupa el entrenador para intentar
crear el objeto.
Probabilidad de éxito: Corresponde a un número que representa la probabilidad que tiene el
entrenador de crear exitosamente el objeto."
Pero en objetos.csv solo están tipo y nombre, no esta ni costo ni probabilidad de éxito, entonces realmente no entiendo qué hacer respecto a estos parametros.
Saludos y gracias de antemano.

**Comment by 3rdPix** [comment]
ENERGIA_CREAR_OBJETO es un nombre genérico para referirse al costo que cada tipo de objeto tendrá, lo mismo con la probabilidad. Y en un issue anterior habían dicho que uno tenía que definir los valores de `parametros.py`.
Así, tu decides qué costo y probabilidad otorgarle a cada tipo de objeto y lo estableces en ese módulo.

**Comment by bernirosas** [comment]
ok perfecto gracias! No había entendido.
