### ISSUE TITLE
Enunciado extraño: descripción tableros NxM.

### ISSUE THREAD

**Issue by fbehncke** [IIC2233/Syllabus#119]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, me pareció raro que en el enunciado de la tarea, en el ítem 4.Archivos y sección 4.2 tableros.txt, dice en el punto 3: "Luego vendrán NxM elementos separados por una coma (","), **donde por cada N elementos se inter- pretará como una fila del tablero**. " Si esto fuera así, el ejemplo justo después no tendría sentido ya que tendríamos lo siguiente: 

ejemplo_chico_sin_solución,2,5,V2,--,PP,--,H2,H3,--,--,PP,R11

donde N=2 (número de filas) y M=5 (número de columnas). Luego, a partir del enunciado entenderíamos que los primeros N elementos serían la primera fila, estos son: "V2" y "--", sin embargo, esto es evidentemente incorrecto, pues en ese caso tendríamos 5 filas y dos columnas. Por lo que sospecho que el enunciado debiese ser: "Luego vendrán NxM elementos separados por una coma (","), **donde por cada M elementos se inter- pretará como una fila del tablero**. " Agradecería la aclaración ya que estoy bien enredada. Muchas gracias!

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Mcroquevielle** [comment]
Hola!! Si, efectivamente es un error de enunciado. Debería decir que cada M elementos se considera una fila

**Comment by fbehncke** [comment]
gracias!
