### ISSUE TITLE
Testeo tarea, Iniciar múltiples clientes

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#1190]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!, cuando quiero manejar múltiples clientes desde diferentes consolas mi programa se "cae", se me cae al 3 cliente el front de los primeros 2, y con el 4 de mismo modo(en la sala de espera). Nose si esto es un problema de Ram u otro motivo de mi pc, o tengo un problema de código ( e revisado harto y no encuentro que puede ser).
Acabo de hacer un push por si algún ayudante puede probar y me confirma la duda. Slds
(se ejecuta server.py en la carpeta servidor y se ejecuta main.py en la carpeta cliente para que funcione)

**Comment by DCCollao** [comment]
Hola @sa-Appel!

Ejecuté tu código y efectivamente se cae cuando conecto al tercer cliente al servidor. Tengo más que suficiente ram, así que es posible descartar esta causa. Es seguro que el problema se encuentra en algún lugar del código.

PD: Por otro lado, te recomiendo que tengas cuidado con el lenguaje que utilizas en los archivos que subes a tu repositorio, especialmente habiendo pedido que te lo revisen.

**Comment by sa-Appel** [comment]
Oka voy a revisar,  gracias por verlo.

PD, si se me olvida que me dejo comentarios personales que tengo que sacar perdón je
