### ISSUE TITLE
Error en importar archivo

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#1191]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola tengo un error al intentar importar un parámetro desde el archivo que esta en otra carpeta (servidor) hacia  un archivo que esta en la carpeta (cliente)

from server import servidor as s
ModuleNotFoundError: No module named 'server'

pero cuando estoy en el archivo y me paro sobre "from server import servidor as s" y si me lo reconoce, como que se importara bien, no se a que se puede deber el error, podría ser por la ruta relativa??

**Comment by DCCollao** [comment]
El error en sí se debe a la forma en que funcionan los `import` dentro de Python. Este tema da para bastante explicación, así que te recomiendo que leas al respecto en documentación o [stackoverflow](https://stackoverflow.com/questions/11393492/python-package-import-from-parent-directory).

No pude evitar fijarme en que estás intentando importar un archivo desde `cliente` hasta `servidor`. Esto **no se debe hacer por ningún motivo**, pues cliente y servidor se deben tratar **como si estuviesen en distintos computadores**. No pueden acceder directamente a los archivos contenidos en el otro, pues dicha conexión debe ser posible solamente a través de sockets.
Si necesitas tener un parámetro tanto en cliente como en servidor, puedes incluirlo en el archivo `parametros.json` de ambos, y así no tendrías que hacer el import que mencionaste.

Espero que haya quedado claro!
