### ISSUE TITLE
No puedo abrir ventanas desde main.py

### ISSUE THREAD

**Issue by camisiilva** [IIC2233/syllabus#1192]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! estaba intentado abrir la sala de espera y solo me aparece el cohete de python pero no abre la ventana. Lo hice con señales como sale en otras issues pero tampoco me funciona. ¿que puede ser?

**Comment by Juampisaez** [comment]
Hola @camisiilva 
Probaste viendo hasta donde llega el flujo de tu codigo? o talvez si tu ventana se puede instanciar y se muestra por si sola (ejecutar solo la ventana)?. Si puedes hacer git push de tu codigo para verlo mejor seria bacan!

Quedo atento :)

**Comment by camisiilva** [comment]
Si, la ventana se logra instanciar (hice prints para ver que llegara al init de la ventana) e hice un print posterior a la señal. Pero no me imprime que la señal llegue. Ya hice push con lo que tengo actualmente. 
Muchas gracias, espero tu respuesta :)

**Comment by Juampisaez** [comment]
Yap, de todo lo que he visto en esta tarea, te recomendaría instanciar las ventanas dentro del Cliente y ahi hacer la conexion de señales. Me da la impresion de que ese es el problema, prueba eso y me avisas si funciona.

**Comment by camisiilva** [comment]
ahora si funciona! muchas gracias :)
