### ISSUE TITLE
[Bonus Anonymous] Notificación a todos los jugadores

### ISSUE THREAD

**Issue by cnsfeir** [IIC2233/syllabus#1192]
Hola,
Para el Bonus de Anonymous, ¿Es necesario notificar a todos los jugadores cuando alguno lo activa?
En el enunciado no se especifica, ¿Asumo que queda a criterio? Porque sería más simple si no requiriera el aviso general  :sweat_smile:

¡Muchas gracias!

**Comment by DCCollao** [comment]
Hola @cnsfeir!

Como por enunciado no se pide que se avise al resto de jugadores cuándo se activa, no es necesario que lo hagas. Además, esto agrega más tensión a la partida :eyes: pues nadie sabe si ya vieron sus cartas o no!

**Comment by cnsfeir** [comment]
JAJAJA me parece
¡Muchas gracias! @DCCollao
