### ISSUE TITLE
Información perdida  servidor-cliente

### ISSUE THREAD

**Issue by sebadelorenzo** [IIC2233/syllabus#1193]
Hola!! Tengo un problema sobre la información que recibe el cliente. Pareciera que no está recibiendo toda la información que le envía el servidor. Estuve haciendo varios prints a lo largo de mi código y me dí cuenta que el servidor si esta mandando toda la información o eso pareciera, sin embargo el cliente no la esta recibiendo completa, como si el mensaje enviado nunca llegará a destino. No es que llega la información incompleta, si no, simplemente no llega. Ejemplo: el servidor manda la información de 2 cartas (una primero y después la otra) pero solo llega una carta. Lo más extraño es que esto varía. A veces llegan las 2 cartas, a veces una y a veces ninguna. 

Por qué puede estar pasando esto? Gracias de antemano!

**Comment by fdoflorenzano** [comment]
Estimado @sebadelorenzo,

Al ver tu código superficialmente, noto que en tus clientes lees una cantidad absurda de *bytes* desde el *socket*. Digo absurda, porque es suficiente como para leer múltiples mensajes en un solo intento. Esa probablemente es la razón de porque a veces se leen las cartas bien, y a veces solo una o ninguna. Porque como no puedes predecir cuanto se habrá enviado hacia el cliente al momento de ejecutar `recv`, si lees demás, puede que leas múltiples mensajes que se enviaron desde el servidor. En este caso, estás leyendo más de una carta en un mismo mensaje, e intentar decodificar eso no tendrá sentido. Este tema se habla en los contenidos, y también se cuenta el problema en el video de dudas anónimas de la semana 14. Te recomiendo mirarlo.

Si tienes otra duda, nos avisas.
Saludos.

**Comment by sebadelorenzo** [comment]
Comprendo, gracias! Voy a revisar bien los contenidos y el video. Por un momento pensé que podría ser que estaba enviando toda la información de una desde el servido y tal vez las imágenes de las cartas eran muy grandes y se perdía información, por lo que pensé que podría solucionarlo con chunks. Pero por lo que me dices el problema no es la cantidad de información enviada, sino la cantidad de información recibida. Dicho eso, no debería tener problemas al no usar chunks para enviar la información? 

gracias nuevamente

**Comment by fdoflorenzano** [comment]
Hola @sebadelorenzo,

No necesariamente pasa con el envío. Envíes por *chunks* o no la información desde un lado, de todas formas tendrás que recibir de forma exacta al otro.

Saludos.

**Comment by sebadelorenzo** [comment]
Perfecto, ahi lo pude solucionar!! Muchas gracias por la aclaración, me quedó mucho más claro!
