### ISSUE TITLE
Error al correr el servidor desde cmd

### ISSUE THREAD

**Issue by magdalenarojas** [IIC2233/syllabus#1194]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holaa, al correr el servidor desde vscode y los clientes desde cmd el envio de mensajes anda super bien, se actualizan los jugadores en la sala de espera y todo, pero cuando el servidor lo corro desde cmd me empieza a fallar, solo recibe o envía algunos mensajes y los otros no :(
mi segunda duda es que al cerrar la interfaz gráfica el cliente no se desconecta y eso si que no tengo idea pq es :(

desde ya doy gracias jssjs

**Comment by Juampisaez** [comment]
Hola @magdalenarojas 
Una duda, estas ejecutando en vscode a traves del runner o la cmd. Si lo ejecutas desde la cmd de vscode (terminal), puedes ver que error te esta retornando.

Quedo atento :)

**Comment by magdalenarojas** [comment]
pucha no sabría decirte, pongo run -> start debbuging -> python file

**Comment by Juampisaez** [comment]
Yap, trata de hacerlo con la terminal de vscode:
![image](https://user-images.githubusercontent.com/48323752/100807815-c0488a80-3411-11eb-9ae3-7237c2e8b128.png)

y abres tu archivo.

**Comment by magdalenarojas** [comment]
sii ahi mismo lo hago:(
![2020-12-01 (2)](https://user-images.githubusercontent.com/69605162/100808059-3947e200-3412-11eb-897f-a263cbb38c01.png)

**Comment by Juampisaez** [comment]
Ya, me meti a revisar tu codigo, y estas borrando el cliente en el servidor (linea 73). Puede ser ese el problema, avisame si es efectivamente eso.

**Comment by magdalenarojas** [comment]
noo:( no es eso,  elimine esa linea para ver si funcionaba y sigue fallando. como que funciona solo con algunos clientes, o a veces con ninguno

**Comment by magdalenarojas** [comment]
otra cosa que me di cuenta es que si le pongo breakpoints al servidor como que funciona bien

**Comment by Juampisaez** [comment]
Mm, dejame verlo mejor, has push de tu codigo (en server importas logica y no esta en tu repo). Avisame

**Comment by magdalenarojas** [comment]
listo!
