### ISSUE TITLE
Duda implementación grafo no dirigido T03

### ISSUE THREAD

**Issue by ffelbol** [IIC2233/syllabus#1195]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! quiero saber si es necesario crear una clase grafo que contenga todas las instancias de la clase nodo o si puedo simplemente guardarlos en una lista.

**Comment by Juampisaez** [comment]
Hola @ffelbol 
Mientras no este estipulado en el enunciado, puedes utilizar cualquier herramienta que estimes conveniente, en lo personal yo lo habia pensado como un diccionario. Si lo explicas en tu readme mucho mejor, asi el ayudante corrector no pasara tiempo decifrando tu codigo. Espero haberte ayudado :)

**Comment by ffelbol** [comment]
Muchas gracias!
