### ISSUE TITLE
Duda sobre utilización de generador_de_cartas.py

### ISSUE THREAD

**Issue by dedmu5** [IIC2233/syllabus#1196]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, no entiendo bien para qué nos entregan el archivo generador_de_cartas.py. En el catán si no mal recuerdo las cartas de desarrollo se sacan de una en una. Me haría sentido que sacar_cartas(cantidad_cartas) me entregue una carta  de desarrollo al azar. Sin embargo, me entrega una lista de tuplas (lista que, de hecho, no sé si es al azar). ¿Por qué esto es así?, ¿Qué se espera que hagamos?.
Saludines

**Comment by Juampisaez** [comment]
Hola @dedmu5 
Les entregamos este archivo para que puedan sacar cartas de forma al azar y con las mismas proporciones del juego original (si no me equivoco es 5:3). La idea es que lo ocupen para evitarles pensar en como sacar las cartas. Se espera que cada vez que compren una carta de desarrollo ocupen esta funcion para simular el sacar una carta de este mazo, como tu dices probablemente compren solo una, por lo que el input sera 1 (la lista es al azar).

Espero haber respondido tu duda :)

**Comment by Jamesmoreno21** [comment]
A mi no me queda claro que se espera que hagamos aun 😢 , por ejemplo si un jugador quiere comprar una carta de desarrollo habría que ejecutar simplemente *sacar_cartas(1)*, o ¿tenemos que preguntarle cuantas cartas de desarrollo quiere para usar *sacar_cartas(n)* ? Estoy un poco confundido con eso, gracias de antemano!

**Comment by Juampisaez** [comment]
Imagina que quieres comprar una carta, lo que deberias hacer es dar tu `input = 1`  para que te quede la funcion tal como dices tu `sacar_cartas(1)`, esto te retornara una lista con solo una tupla que indica cual carta es y además esta en el mismo formato de los sprites (se penso para que fuera mas facil mostrar la carta, pero la implementacion no necesariamente debes mostrar la carta, puedes simplemente actualizar el contador de cartas que tienes). Yo te recomendaria hacer un boton que al ejecutar, saques solo una carta. (no es necesario preguntarle cuantas cartas quieres sacar, aunque tambien se podria hacer).

**Comment by Jamesmoreno21** [comment]
Ok! Me quedo claro, muchas gracias!
