### ISSUE TITLE
Rotar imagen en PyQt5

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2233/syllabus#1196]
Hola! No logro encontrar como rotar una imagen en PyQt5. Es para que me quede el GUI como el del enunciado, con ciertas cartas rotadas. No se si me podrían dirigir a algún link o darme algún tip al respecto. Se los agradecería mucho.

**Comment by jirarrazabal** [comment]
Hola! tu pregunta fue resuelta en la Issue #1168. Suerte!!
