### ISSUE TITLE
tipos de cartas a quitar cuando lanzamiento es 7

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2233/syllabus#1197]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, 

tengo una duda con respecto a los tipos de cartas que se deben contar y quitar cuando el dado cae en 7. Estas serán solo las cartas de materias primas? o hay que contar también las de desarrollo? En caso de ser esto ultimo, que pasa con las cartas de monopolio, hay que guardarlas a pesar de que no tengan ningún valor (ya que su efecto es inmediato)?

Muchas gracias c:

**Comment by Juampisaez** [comment]
Hola @antoniaalcayaga 
No esta escrito especificamente en el enunciado, pero puedes asumir que seran cartas de materia prima ya que en la parte anterior en el enunciado solo se hace enfasis a las materias primas (no consideres las de desarrollo para este caso), tal como se hace en el juego Catan.

Espero responder tu duda :)
