### ISSUE TITLE
Probar el código

### ISSUE THREAD

**Issue by faaceituno** [IIC2233/syllabus#1197]
Hola, queria saber como se puede probar el código desde el mismo pc, porque probando el ejemplo de la ayudantía puedo correr el servidor y despues conectar unicamente un cliente. Se pueden conectar varios clientes desde el mismo pc?

**Comment by kipasten** [comment]
no soy ayudante, pero para hacer eso solo debes correr el programa en distintas terminales, una para el server y otra por cada cliente que quieras conectar

**Comment by SamWeinstein** [comment]
Exactamente, tal como indica @kipasten debes puedes correr el programa para muchos clientes del mismo modo que lo haces para un solo cliente. Puedes abrir varias ventanas de tu editor de texto y conectar así varios clientes.
