### ISSUE TITLE
Se me crean ventanas de juego para clientes distintas para cada uno de ellos

### ISSUE THREAD

**Issue by elchocman** [IIC2233/syllabus#1198]
holaa, es que tengo un metodo donde abro 5 terminales, una para el servidor y otras 4 para los clientes, la cosa es que mi a la hora de haber 4 clientes conectados se abre mi ventana de juego(una para cada cliente) la cosa es que como esta ventana esta siendo instanciada en la carpeta de mis clientes cada terminal crea una ventana distinta para cada uno de los clientes, osea, que las 4 tienen posicionadas en distintos lugares las chozas y los hexagonos. Nose como arreglar esto, pense que se podria instanciar esta ventana de juego en el servidor pero no creo que eso sea posible aparte de que no es uno de los roles del servidor. Me gustaria saber alguna forma de hacer esto. Estoy abierto a consejos. Saludoss

**Comment by Mjtala** [comment]
Hola @elchocman! Te recomiendo que trates de instanciar a los Clientes en el servidor pero si prefieres no hacerlo entonces recuerda que debes enviar la información de todos los clientes a cada cliente (ojalá no sea confuso), para así poder acceder a la información de estos y mandar toda la data a la interfaz de cada cliente. De esta manera estarías mostrando a todos los jugadores el mismo tablero de juego.
Cuéntame como te va!
