### ISSUE TITLE
Programa se cae al desplegar ventana de juego

### ISSUE THREAD

**Issue by tcouso** [IIC2233/syllabus#1198]
Hola!
He tenido bastantes problemas a la hora de desplegar la ventana de juego para varios jugadores. El funcionamiento de mi programa es el siguiente: se detecta que el servidor está lleno (en relación a un parámetro de máximos jugadores) y se envía un mensaje mediante sockets a todos los jugadores conectados. El mensaje activa un método de transición desde la sala de espera a la ventana de juego.
En un inicio no funcionaba. Luego, sin realizar cambios, según entiendo, funcionó desplegar la ventana principal hasta para tres jugadores simultáneamente, pero posteriormente (luego de modificaciones en el programa no asociadas a networking) solo funcionó para un jugador. El programa ha sido muy inconsistente, en el sentido de que hay veces que, sin alterar el código, deja de funcionar incluso para un jugador, pero luego nuevamente funciona.
Sospecho que puede tener que ver con la exigencia sobre el computador, pues a la hora de ejecutar el programa se activa bastante la ventilación de mi notebook, y el uso de memoria aumenta sustancialmente.
Tengo bien poca idea de cual puede ser la falla, y está siendo una barrera para desarrollar el juego (por lo menos con dos jugadores conectados podría hacer algo) así que agradezco cualquier ayuda. La versión más reciente de mi programa ya esta en mi repo.
Gracias de antemano! :)

**Comment by fdoflorenzano** [comment]
Hola @tcouso,

Revisé tu avance en repositorio, y al conectar tres clientes efectivamente no se me desplegaba la ventana princiapal que parecía gatillarse en el código, además de congelarse el programa.

Revisando tu código, noté que si bien llamas mediante señales a la aparición de la ventana principal, el escondido de la ventana de espera la llamas directamente mediante `hide`. Cambié ese detalle a que se accionara mediante una señal y empezó a funcionar.

Recuerda que todo lo gráfico y de *front-end* es recomendable accionarlo mediante señales y no llamando directamente a las funciones desde el *back-end*. Intenta hacer esos arreglos y nos cuentas como te va.

Saludos.

**Comment by tcouso** [comment]
Hola @fdoflorenzano,
Hoy me dediqué a accionar todo lo gráfico mediante señales y ahora está funcionando el despliegue de varias ventanas, aparentemente sin problemas. Muchas gracias por la ayuda!
Me queda un detalle por resolver con respecto al servidor, que es que no estoy logrando que el programa concluya por su cuenta: logro desconectar todos los sockets y que el programa del cliente termine, pero el del servidor no he logrado plantearlo de manera que termine por su cuenta (siempre termino cerrándolo a mano en el administrador de tareas). Algún consejo sobre cómo organizar mejor el flujo del programa para el servidor? Quedo atento, saludos!

**Comment by fdoflorenzano** [comment]
Hola @tcouso,

Que bueno se te solucionó el problema original. Sobre lo segundo, para respetar el orden y reglas de las *issues*, te pido abras una nueva con tu nueva duda. Así esta *issue* solo condensa un problema y no varios.

Saludos.

**Comment by tcouso** [comment]
Toda la razón profe, perdón. Abriré un nuevo issue con la duda sobre el cierre del servidor.
Saludos!
