### ISSUE TITLE
Servidor no toma el ultimo jugador

### ISSUE THREAD

**Issue by mariaignaciag** [IIC2233/syllabus#1199]
Hola! mi programa como dice en el título no escucha al ultimo thread, por ejemplo si pongo 3 jugadores, solo me toma la señal de la interfaz de los primeros dos y se pongo 4, solo toma 3, sin embargo, el servidor si manda todo al total de jugadores, he hecho varios prints literal toda la tarde y no logro encontrar el error, seria genial si me pudieran orientar, muchas gracias! 😄

**Comment by gatochico** [comment]
Hola! Lograste solucionar el error? Bajé la ultima actualización de tu repo pero no pude replicar el error u.u

Si no has solucionado todavía el problema, dime los pasos exactos a seguir para replicar el error y así ayudarte.

Quedo atenta!!

**Comment by mariaignaciag** [comment]
hola!! aun no :( , subi una actualización ya que arreglé otros errores que tenia, te explico lo que pasa, si corres tal cual mi tarea como esta, tiene 3 jugadores, al iniciar los tres jugadores el servidor me envia todo a los jugadores, pero si apretas robar carta por ej, solo funciona en el jugador 1 y 2, pero en el 3 no corre nada, lo mismo con otras señales 😢

**Comment by gatochico** [comment]
Hola! Por fin logramos encontrar el error:

En tu archivo de servidor, tu función `self.start_game()` está de la siguiente forma:
```
def start_game(self):
    with self.lock:
        #codigo vario
        self.start_game()
```

Entonces si te fijas, la función se está llamando de forma recursiva. El problema cae es que como usas `self.lock` (una instancia en específico de Lock()) para obtener un lock sobre la función, la primera vez que llamas a la función este lock se usa y queda opcupado. Sin embargo, en la posterior llamada recursiva (cuando haces self.start_game() dentro de la misma función), va a llegar a la línea del lock y no lo podrá adquirir ya que la primera llamada a esta todavía no lo ha soltado! Y no lo hará hasta que todas las funciones de adentro terminen, cosa que nunca ocurrirá ya que no pueden acceder al lock hasta que la función padre lo suelte. En fin, se genera un caso de deadlock :skull: .

Para arreglarlo de forma temporal, cambia el `with self.lock:` por un `with Lock()` genérico y verás como todos los clientes podrán llamar a la carta. Sin embargo, te darás cuenta que ese cambio practicamente hace que el Lock() no tenga utilidad alguna, ya que cada vez que se use la función se generará una instancia de lock distinto en esta línea, y por ende ningún thread quedará esperando ya que nunca necesitarán el mismo lock. Por ende, te recomendaría repasar esa función nuevamente: ¿Es necesaria la llamada recursiva? ¿Necesita realmente un lock esa función?¿Si es así, donde? Dependiendo de tu respuesta, modifica esa función acordemente para que quede bien modelada.

Cualquier duda pregunta, y éxito con tu tarea! (perdón por decir la palabra lock tantas veces seguidas, jaja)

**Comment by mariaignaciag** [comment]
muchísimas gracias! modele de otra manera la función y me funcionó 🥳  , en verdad se pasaron ❤️
