### ISSUE TITLE
Falla al conectar un botón

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#1199]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, estoy conectando mi botón para comenzar una partida y no me funciona:(
Puse
self.boton_comenzar.clicked.connect(self.funcion)

**Comment by denisseleiva** [comment]
Holiss si estás usando QtDesigner en Mac hay un bug si el ancho/alto es menor a 35 los botones no son apretables(ni idea por qué). Prueba con esoo a mí me funcionó jajaj 👌

**Comment by rodrigobj99** [comment]
Hola @Margarita-Paz 
Lo que comenta @denisseleiva es correcto para algunas versiones de PyQt5 en mac. 
Por otro lado existe también un problema con las versiones nuevas de PyQt5, ya que algunas de estas justamente producían que los botones no se pudieran apretar en Mac. La issue que trata de eso es la #892 .

Espero te sirva. Saludos!
