### ISSUE TITLE
Problema con la versión default de python 3.8 en Linux Ubuntu 16.04

### ISSUE THREAD

**Issue by vattlestar** [IIC2233/Syllabus#12]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema
He intentado de muchas formas de cambiar la versión default de python 3.8 en mi pc con linux ubuntu 16.04 y no lo he logrado. Mi pc utiliza python 3.8.5 para otras funciones por lo que esta versión es utilizada por "default". Intenté utilizar este código:
![Captura de pantalla de 2021-08-21 21-35-26](https://user-images.githubusercontent.com/81594176/130339073-f1bb38d1-3924-4a65-a78d-8dd79bf2cf74.png)
Hay alguna otra forma de poder cambiar la versión default, o tendré que seleccionar con qué versión de python trabajar en vscode o jupyter notebook?
slds.

**Comment by agucova** [comment]
Ubuntu 16.04 es una versión bastante antigua de Ubuntu que solo recibe actualizaciones extendidas de seguridad y por ello no incluye versiones nuevas de Python en sus repositorios, sin embargo te dejo una opción:

### Utilizar una herramienta para manejar versiones de Python

Esto es probablemente lo más fácil para evitar conflictos con la versión del sistema de Python (ya que reemplazarla podría romper cosas). 

Una herramienta popular de manejo de versiones de python es [pyenv](https://github.com/pyenv/pyenv), la que se puede instalar fácilmente corriendo:

```shell
curl https://pyenv.run | bash
```
Y siguiendo las instrucciones. Luego, tendrás que reiniciar tu terminal y correr los siguientes comandos para instalar Python 3.8.11 y hacerla la versión por defecto del sistema:
```shell
pyenv install 3.8.11 
pyenv global 3.8.11
```

Nota que esto va a requerir que elijas explícitamente la versión 3.8.11 instalada por pyenv en tu editor. Por ejemplo en VSCode:

![image](https://user-images.githubusercontent.com/4694408/130481050-0664a931-bd28-4175-8fe0-ddaf0282b03e.png)


### Utilizar un [PPA](https://help.ubuntu.com/stable/ubuntu-help/addremove-ppa.html.en)

Esto permite instalar una versión mas reciente de Python utilizando `apt`, y dejar que las herramientas de Ubuntu decidan entre versiones.

Sin embargo, no pude encontrar un PPA mantenido que incluya la 3.8.10 o 3.8.11 para 16.04, ya que la mayoría viene con 3.10, 3.9 o 3.7 (como [deadsnakes](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa)), o bien solo actualizaron hasta 3.8.9.

### Instalar Python manualmente
No recomiendo esto, porque suele ser díficil de mantener, pero es un último recurso.

Primero, querrás instalar los requisitos para compilar Python:
```shell
sudo apt update
sudo apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget
```

Luego, querrás descargar Python 3.8.11 en un directorio temporal:
```
cd /tmp
wget https://www.python.org/ftp/python/3.8.11/Python-3.8.11.tgz
```

Y luego desempacar el `.tgz`, entrar al directorio, configurar el proceso de compilación e iniciar el proceso de compilación reemplazando el número en `-j 1` por el número de núcleos en tu computador:
```shell
tar -xf Python-3.8.11.tgz
cd Python-3.8.11
./configure --enable-optimizations
make -j 1
sudo make altinstall
```

Verás un montón de cosas pasando en tu pantalla, no te asustes. En mi computador (relativamente rápido) todo el proceso tomó 4 minutos, pero prepárate para esperar hasta 15 minutos.

Una vez terminado, tu editor debería mostrar la opción para utilizar Python 3.8.11 automáticamente.

**Comment by fernandosmither** [comment]
@vattlestar ¿Fue suficiente la respuesta del compañero?

Quedo atento.

**Comment by vattlestar** [comment]
Ya tengo instalado python 3.8.11, y hallé la forma de seleccionar esta version en vscode. Pero no en la terminal de ubuntu el default es la version 3.8.5, no sé si esto es problema para el curso en si.

**Comment by agucova** [comment]
> Ya tengo instalado python 3.8.11, y hallé la forma de seleccionar esta version en vscode. Pero no en la terminal de ubuntu el default es la version 3.8.5, no sé si esto es problema para el curso en si.

Si ejecutas Python utilizando VSCode no es un problema, pero puede serlo al ejecutar cosas a mano. ¿Qué método usaste para instalar Python?

**Comment by vattlestar** [comment]
lo instalé directamente de la source

**Comment by try-except** [comment]
si corres `python3.8.11` en la terminal funciona? El alias "python" probablemente apunta al intérprete por default

**Comment by vattlestar** [comment]
no me lo corre :(

**Comment by try-except** [comment]
Puedes postear un screenshot del lugar donde elegiste python3.8.11 en VSCode? Para agregar una imágen puedes copiarla y pegarla o arrastrarla cuando escribas tu respuesta

**Comment by vattlestar** [comment]
![image](https://user-images.githubusercontent.com/81594176/130526436-b3b0b2a9-7519-4911-9d4e-8b635ec9d646.png)

**Comment by try-except** [comment]
> ![image](https://user-images.githubusercontent.com/81594176/130526436-b3b0b2a9-7519-4911-9d4e-8b635ec9d646.png)

Gracias por la foto! Pero me refería al menú que usaste, como esta:

> ![image](https://user-images.githubusercontent.com/4694408/130481050-0664a931-bd28-4175-8fe0-ddaf0282b03e.png)

**Comment by vattlestar** [comment]
![image](https://user-images.githubusercontent.com/81594176/130531538-4ec226ef-65c6-4f45-9f0c-c6d42ffa5f2d.png)

**Comment by try-except** [comment]
Perfecto, si usas el comando `python3.8` en la terminal, funciona?

**Comment by agucova** [comment]
Si Python está en `/usr/local/bin/`, debe estar en `PATH`. 

Si efectivamente funciona al correr `python3.8`, puedes hacer lo siguiente para asociar los otros comandos:

```shell
echo "alias python3='python3.8' >> ~/.bash_aliases
echo "alias python='python3.8' >> ~/.bash_aliases
```

**Comment by vattlestar** [comment]
![image](https://user-images.githubusercontent.com/81594176/130675819-d6a480d4-1c51-413d-9ff0-6eea081f67a1.png)

**Comment by agucova** [comment]
Anaconda probablemente está tomando preferencia por sobre 3.8.11. Anaconda complica las cosas porque además está activando su entorno de Python con tu terminal.

Una opción es desinstalar Anaconda:
```shell
conda install anaconda-clean
anaconda-clean
```

La otra es desactivar el auto-inicio de Anaconda en `~/.bash_profile` (es un archivo oculto, puedes abrirlo escribiendo `xdg-open ~/.bash_profile`. Ahí deberías ver una línea parecida a esto:
```shell
export PATH="/home/valentina/anaconda3/bin:$PATH"
``` 
La que puedes desactivar comentándola, agregando un `#` al principio.

**Comment by vattlestar** [comment]
No tengo instalado anaconda, lo tenía y lo desinstalé antes de instalar python 3.8  nuevamente

**Comment by agucova** [comment]
El output de la screenshot que enviaste recién sugiere lo contrario, tienes una versión de Python de Anaconda y el `(base)` en tu terminal indica que tienes un entorno activado.

Probablemente desinstalaste Navigator y no la instalación completa, o falló la desinstalación por alguna razón.

**Comment by vattlestar** [comment]
Probé con la línea para desactivar el entorno y luego puse la version 3.8.11 como default desde el root y funcionó!
Muchas gracias c:
