### ISSUE TITLE
[Properties] Duda material de clases

### ISSUE THREAD

**Issue by dfvasquez** [IIC2233/Syllabus#12]
Holaaa!

En este ejemplo aparece que "las properties con decoradores tambien pueden involucrar acciones que dependen de variables de la clase", pero en el ejemplo solo pareciera ocupar atributos de la instancia. ¿Se refiere a esto último o a atributos de la clase? Me parece un poco confuso que diga "variables de la clase" Graciaaas :heart:

![image](https://cloud.githubusercontent.com/assets/20784077/23709434/3889487a-03f8-11e7-81af-b38e6b375f63.png)

**Comment by fvr1** [comment]
Si! efectivamente es una variable de instancia, ya que ésta es creada en el init y varía según la instancia.

**Comment by dfvasquez** [comment]
Gracias 😄
