### ISSUE TITLE
Instalación de pyqt5

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#12]
Hola! Estoy instalando pyqt5 como lo hacen en el video y me sale lo de la foto de que se instaló bien pero mi versión de pip no está actualizada, ¿tengo que pescarlo o da lo mismo? ¿qué es pip?

![Símbolo del sistema 13-08-2020 16_20_43](https://user-images.githubusercontent.com/68581172/90183273-3650b500-dd81-11ea-8500-350d93295d17.png)

**Comment by Baelfire18** [comment]
PyQt5 está correctamente instalado.
Ahora bien para actualizar pip, escribe en consola:
python -m pip install --upgrade pip

**Comment by kalarconvl** [comment]
Gracias!

**Comment by Baelfire18** [comment]
Pip un paquete que instala otros paquete. Es como el instalador de python 😉

**Comment by martin-iturralde** [comment]
Hola! Es que yo tengo un problema parecido, cuando trata de hacer el: python -m pip install --upgrade pip
No se me descarga nada (y antes tengo el mismo comentario en amarillo que el de la pregunta). 
![image](https://user-images.githubusercontent.com/69633813/90252328-444c1780-de0d-11ea-9f91-73837a490d94.png)

**Comment by Baelfire18** [comment]
Que raro, y te sigue saliendo eso? Seguro que ya no lo actualizaste? 
Hablame por discord y hagamoslo por llamada. 
Mi nombre es Baelfire18 en Discord

**Comment by emiliaup** [comment]
Hola!! yo tambien tengo un problema que el programa no me identifica la m ( -m) 
![image](https://user-images.githubusercontent.com/69696514/90297711-68cfe000-de5d-11ea-85a5-2542a9eae697.png)
[](url)

me sale:

"'-m' is not recognized as an internal or external command,
operable program or batch file."

**Comment by Baelfire18** [comment]
@emiliaup es pq tanto para actualizar pip o instalar jupyter debes poner python antes:
`*python -m pip install jupyter*` y 
*`python -m pip install --upgrade pip`*
respectivamente

**Comment by Baelfire18** [comment]
@martin-iturralde sigue sin funcionar?

**Comment by emiliaup** [comment]
@Baelfire18 
![image](https://user-images.githubusercontent.com/69696514/90428577-322edb00-e092-11ea-9786-f1e6ee9fcd5d.png)
Ahora si me funciono el m pero no se me carga nada. Trate con las dos formas (python y python3) y tampoco se me carga.
![image](https://user-images.githubusercontent.com/69696514/90428887-a9fd0580-e092-11ea-9919-8fd88ed52042.png)
![image](https://user-images.githubusercontent.com/69696514/90429034-f47e8200-e092-11ea-8ee7-e15b2f07cf54.png)

**Comment by Baelfire18** [comment]
@emiliaup prueba lo mismo sin python
**`pip install jupyter`** y 
**`pip install --upgrade pip`**
Ya que pip tambien debería funcionar solo
Cuentame si te sirve!

**Comment by emiliaup** [comment]
@Baelfire18 
:( tampoco 
![image](https://user-images.githubusercontent.com/69696514/90440262-ec2f4280-e0a4-11ea-8852-946d2fc69856.png)

**Comment by Baelfire18** [comment]
En una de esas no tienes instaldo pip aún jajajaj
Prueba con la siguiente linea antes de **`pip install pip`**
Si te funciona corre las anteriores, sino dime

**Comment by emiliaup** [comment]
jajaja me sale que "'pip' is not recognized as an internal or external command,
operable program or batch file."

**Comment by Baelfire18** [comment]
Yap entonces hay que instalar `pip `por primera vez en tu PC, para eso hay una documentación con instruciones, pero es más facil si alguien te guía. Es esa -> [(https://phoenixnap.com/kb/install-pip-windows)](url)

Te tinca hacerlo por discord, ya sea hoy conmigo ahora o mañana en la ayudatia con algun ayudante.
Mi user name de discord es @Baelfire18

**Comment by emiliaup** [comment]
Felizzz mañana que ahora tengo una clase 

gracias por todo :) te cuento como me va

**Comment by Baelfire18** [comment]
😉
