### ISSUE TITLE
Duda archivos

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#12]
Que pasa si quiero abrir un archivo que está contenida en mi repositorio persona?l, qué dirección habría que poner para que lo abra?, o por defecto el programa entenderá que el archivo está en el repositorio después de hacer commit-pull?

**Comment by VicenteMerino** [comment]
Otra duda, como se pueden descargar los archivos de la actividad del semestre pasado? Dado que no encuentro un botón que me lo permita.

Saludos

**Comment by Mahund** [comment]
Hola @VicenteMerino!

Asumiendo que tu primera pregunta hace referencia al uso de **Jupyter Notebook** te recomiendo veas la issue anterior #9 .

Sobre la segunda pregunta, los repositorios anteriores del curso están disponibles en [www.github.com/IIC2233](url), y en específico el semestre anterior esta en [https://github.com/IIC2233/syllabus-2018-2](url), donde debes realizar el mismo proceso de `git clone <url del syllabus correspondiente>`

Espero haberte ayudado!
