### ISSUE TITLE
Dinámica del juego

### ISSUE THREAD

**Issue by emneely** [IIC2233/syllabus#12]
Hola!! 
No me queda clara la dinámica del juego. El usuario debe ingresar las dimensiones del tablero, y el enunciado dice que antes de empezar a descubrir baldosas hay que mostrarle el tablero, este tiene que tener los legos puestos ya? O debe contener espacios vacíos?
No entiendo bien cuando mostrar los legos, siempre o solo cuando termine o pierda?
Gracias!!

**Comment by KnowYourselves** [comment]
Hola @emneely!

Piénsalo igual que el buscaminas. Cuando el jugador decida el tamaño se le va a mostrar el tablero con todas las baldosas ocultas, los Legos ya tiene una posición, solo que el jugador no los puede ver. Finalmente, los legos solo se deberían mostrar cuando el juego termine, sea porque el jugador descubrió un lego (y perdió) o descubrió todas las baldosas (y ganó).

Espero haberte ayudado!
