### ISSUE TITLE
Problema de acceso denegado

### ISSUE THREAD

**Issue by joshelml** [IIC2233/syllabus#12]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X]
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

[Agrega aquí lo que quieras aportar o preguntar]
Al correr mi código me aparece que el permiso esta denegado zsh: permission denied:, utilizo Mac.
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by igbasly** [comment]
Hola @joshelml :v:

¿Podrías darme mayor información acerca de lo que ocurre con este problema?
Por favor indica los pasos que estás siguiendo y el contexto en que estás realizando esto.

Quedo atento :smile:
