### ISSUE TITLE
Python 3.6.2 Mac

### ISSUE THREAD

**Issue by fjaraneda** [IIC2233/Syllabus#12]
Hola, descargue Python 3.6.2 en mac con el sistema El Capitan, me funciona bien al programar, pero no me deja abrir archivos .py. Probe instalándolo de nuevo, pero sigue sin abrir ese tipo de archivos.
Gracias.

**Comment by ifcarrera** [comment]
Hola! 
Puedes subir un pantallazo de lo que te sale exactamente ? O de cómo los estás ejecutando.
Saludos

**Comment by fjaraneda** [comment]
Ese es el problema no me aparece nada, sino que no me abre los archivos descargados

**Comment by iqacevedo** [comment]
Hola,

Crea un archivo simple llamado prueba.py que solo diga:
`print("Hola me estoy ejecutando")`

Después abre una ventana de comandos en la ubicación del archivo y escribe `py prueba.py`, si no te resulta intenta reemplazar `py` por `py3`, `python`o`python3`. Si se te imprime el mensaje puedes abrir archivos, en caso contrario muéstranos el mensaje de error que te sale.

Saludos !

**Comment by fjaraneda** [comment]
@iqacevedo Gracias sí me funcionó, además verifique descargando archivos.py en internet y si me abren, sin embargo el único que no me abre es el de SetUp del Syllabus

**Comment by akaminetzkyp** [comment]
Es posible que el programa se esté cayendo. Si lo corres directamente del archivo no podrás ver el error. Sin embargo, si primero abres IDLE (o cualquier interfaz) y abres el programa desde ahí deberías poder ver si algo raro esta pasando. Saludos!

**Comment by fjaraneda** [comment]
![captura de pantalla python](https://user-images.githubusercontent.com/30665384/29005799-7c14eef2-7ab1-11e7-9682-8fab41de83fd.png)
@akaminetzkyp  Hola, hice lo que me sugeriste, y me abre un archivo vacio "Untitled", que hace que se caiga mi pc, ya que despues debo forzar la salida para cerrarlo, lo que no ocurre con los otros archivos. Yo creo que voy a tratar de actualizar el sistema operativo del pc. Gracias.

**Comment by andresfdezc** [comment]
@fjaraneda El script `setup_test.py` contiene un emoji, lo que no está soportado por IDLE al ser un editor muy básico. Acabo de eliminar dicho emoji, por lo que te pido que hagas pull del Syllabus para tener esta última versión.

También te pido que pruebes el script desde el terminal, dirigiéndote en él hasta la carpeta donde esté el archivo y ejecutándolo con `python3 setup_test.py`. Este método funciona bien con el emoji y debería verse más o menos así:

![screen shot 2017-08-06 at 3 47 17 pm](https://user-images.githubusercontent.com/11430184/29006529-d5d44a6a-7abf-11e7-993e-e8f7a86404be.png)

Finalmente, **no te recomendamos que uses IDLE para este curso.**

**Comment by fjaraneda** [comment]
@andresfdezc Perfecto, ahi me funciono bien. Gracias.
