### ISSUE TITLE
Fecha prograposts 

### ISSUE THREAD

**Issue by rmaguilera** [IIC2233/syllabus#12]
Para la T00, al momento de crear un nuevo prograpost, le puedo pedir al usuario la fecha de hoy o debo usar la librería datetime para ponerle la fecha del día en que se esta creando?

**Comment by furcelay** [comment]
Yo creo que lo lógico es obtener la fecha del momento en que se escribió...

**Comment by gatochico** [comment]
Hola!

Tal como indica @furcelay, se le debe asignar automáticamente la fecha del día en que se escribió. 

Éxito!
