### ISSUE TITLE
Cálculo de la evolución de un planeta

### ISSUE THREAD

**Issue by bmorrisc** [IIC2233/Syllabus#120]
Hola! con respecto a la fórmula de la evolución de un planeta, no me queda clara la fracción que en ella aparece porque pensaba que la población total era la cantidad de magos y soldados actuales en el planeta, pero según lo que entiendo ese es el numerador... de ser así la fracción siempre sería igual a uno y eso no tiene mucho sentido (?)

**Comment by leolivares** [comment]
Hola! Revisa la issue #24.

**Comment by bmorrisc** [comment]
no la había visto, muchas gracias! :)
