### ISSUE TITLE
Equipo de los Pilotos T01

### ISSUE THREAD

**Issue by fnberrios** [IIC2233/syllabus#120]
Hola! ¿Cada piloto puede o NO pertenecer a un equipo? O ¿debe ser obligatorio que pertenezca a uno? De ser así, ¿puede elegir a que equipo pertenece?
Gracias de antemano.

**Comment by RositaMunoz** [comment]
Hola! 
Los que participan en la carrera siempre tienen un equipo, la diferencia es que los contrincantes vienen con un equipo definido en el archivo ``contrincantes.csv`` y el usuario debe elegir a qué equipo quiere pertenecer cuando crea la partida. ^^

**Comment by fnberrios** [comment]
Genial, gracias!
