### ISSUE TITLE
Puedo hacer el README en un word?

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#120]
sgregf

**Comment by hanavarrete** [comment]
No puedes usar word!. Saludos

**Comment by jorgeriesco** [comment]
pq no?

**Comment by hanavarrete** [comment]
@jorgeriesco  Porque en primer lugar para abrirlo se requiere software que no necesariamente tenemos instalado. Además markdown/tx/rst son formatos ideales para hacer el readme porque son soportados nativamente por github. 
Como recomendación, puedes usar de ejemplo el readme.md del syllabus, como ves, no necesitas abrir nada para poder leerlo. Espero que esto responda tu pregunta, saludos!
