### ISSUE TITLE
Duda con la materia

### ISSUE THREAD

**Issue by Toridonco** [IIC2233/Syllabus#120]
Hola, quede con bastantes preguntas sobre la herencia y la multiherencia, trate de leer de nuevo la materia pasada y la ayudantía pero igual sigo con bastantes preguntas. Estas son sobre todo de la estructura general que deben tener y como se comporta la herencia multiherencia en diferentes casos (por ejemplo que una clase que hereda de otras dos, las cuales tienen cada una variable con el mismo nombre, pero con un valor diferencte en cada una,), también  otra cosa que nome quedo muy clara fue sobre como funcionan y se ocupan los *args y **kwargs en estos casos.
Agradecería si me pueden aclarar estas dudas o me indicaran algún texto que pueda leer para entender mejor.

**Comment by CarlangaUC** [comment]
Hola!

Intentare explicarte todo con ejemplos y ahi me comentas si quedas con alguna duda, en todo caso en ayudantia hay mas ejemplos junto a los que puedes ver en la actividad ! :)

Para Herencia!

```python
class Juego:
    
    def __init__(self, nombre, genero):
        
        self.nombre = nombre
        self.genero = genero

class Minecraft(Juego):
    
    def __init__(self, nombre,genero,edicion):
        
        super().__init__(nombre,genero)
        self.edicion = edicion
        
juegazo = Minecraft("Minecraft","Aventura","1.5.2")
print(f"Nombre! : {juegazo.nombre} | Genero! : {juegazo.genero} | Edicion! : {juegazo.edicion}")

# Nombre! : Minecraft | Genero! : Aventura | Edicion! : 1.5.2
```

¿Que paso aca? , En este caso la clase Minecraft hereda de juego los atributos que yo quiero que herede, osea, nombre y genero, por ende los recibo desde el super y se acaba el problema.

Uso de args y kwargs!

```python
class Juego:
    
    def __init__(self, nombre, genero,*args,**kwargs):
        
        self.nombre = nombre
        self.genero = genero

class Minecraft(Juego):
    
    def __init__(self,edicion,*args,**kwargs):
        
        super().__init__(*args,**kwargs)
        self.edicion = edicion
        
juegazo = Minecraft(nombre="Minecraft",genero="Aventura",
                    edicion="1.5.2")
print(f"Nombre! : {juegazo.nombre} | Genero! : {juegazo.genero} | Edicion! : {juegazo.edicion}")
# Nombre! : Minecraft | Genero! : Aventura | Edicion! : 1.5.2
```
Como puedes ver nos arrojara el mismo resultado si empleamos *args y **kwargs! esto ocurre porque args y kwargs permite guardar argumentos a medida que los vas solicitando, esto permite heredar de una manera mas ordenada y completa (muy recomendado emplear, te evitas el problema del diamante que ocurre en multi-herencia).

Para Multi-Herencia!
```python
class Comida:
    
    def __init__(self,felicidad):
        
        self.felicidad = felicidad

class Pan(Comida):
    
    def __init__(self, harina,*args,**kwargs):
        
        super().__init__(*args,**kwargs)
        self.harina = harina
    
    
class Jamon(Comida):
    
    def __init__(self, tipo,*args,**kwargs):
        
        super().__init__(*args,**kwargs)
        self.tipo = tipo
    
    
class Sandiwch(Pan,Jamon):
    
    def __init__(self,aderezo,*args,**kwargs):
        
        super().__init__(*args,**kwargs)
        self.aderezo = aderezo
        
snack = Sandiwch(harina="integral", tipo = "pavo",
                 aderezo = "ketchup",felicidad = 10)
print(f"harina : {snack.harina} | tipo : {snack.tipo} |"+
      f" aderezo : {snack.aderezo} | felicidad : {snack.felicidad}")
# harina : integral | tipo : pavo | aderezo : ketchup | felicidad : 10
```

Observa que ahora tenemos dos clases ```Jamon``` y ```Pan```, y no ocurre ningun problema porque empleamos tanto super como args y kwargs, esto soluciona el famoso problema del diamante (puedes ver en clase algunos ejemplos de ese error).

En definitiva no olvides que al heredar estas heredando los atributos que tu desees y los metodos que viene con esa clase, es por esto que necesitas una manera ordenada para heredar ademas del uso de super para asi evitar posibles errores, si te queda alguna duda mas especifica me comentas :) .
