### ISSUE TITLE
Citar código: cuándo es necesario

### ISSUE THREAD

**Issue by Valind4** [IIC2233/Syllabus#120]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

holi, quería preguntar cuándo es necesario citar código, por ejemplo para ordenar busqué cómo usar la función sort() o para verificar existencia de archivo encontré otra función para tal cosa, tengo que citar código si es que busqué el uso de una función o es más para código específico (like más de 2 o 3 lineas).

y si es que busco como hacer tal cosa también tengo que citar aunque cambien todas las funciones que uso, (para hacer un menú por ejemplo)

gracias

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by 3rdPix** [comment]
El código que debes citar es **el código que no sea de tu autoría**. Es decir, si copias código de StackOverflow, GeekForGeeks o fuentes semejantes, es necesario que indiques el origen de lo que usaste, y en qué sección lo usaste. Usar la documentación oficial de Python como referencia para entender cómo funciona algún método o librería, no requiere cita, de hecho parte de los objetivos del curso es que se familiaricen con la lectura de la documentación.
