### ISSUE TITLE
prioridad de match de orders

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#120]
En el enunciado dice: "En este caso, cuando el precio del ask y el bid no son iguales, es fundamental entender que se respetan los precios que fueron puestos en primer lugar. **En otras palabras, el primer match se hace a 98 mil pesos, mientras que el segundo se hace a 100 mil pesos**, y no ambos a 105 mil pesos."

Según la frase en negrita se deduce que con la frase anterior  "que se respetan los precios que fueron puestos en primer lugar" cuando dicen "primer lugar" se refieren a las orders con el mejor precio de venta y de compra y no a la order que fue ingresada antes al sistema, porque en el ejemplo la order de 100 mil pesos fue ingresada antes al sistema que la order de 98 mil pesos, pero el primer match se hace con la order de 98 mil pesos y el segundo con la de 100 mil pesos.

Sin embargo, en otra issue que ya no encuentro leí una explicación en que decían que se debía respetar el primer lugar según cuál fue la última order creada, viendo la fecha y hora de creación.

¿Cuál es la interpretación correcta?

**Comment by fdominguezclaro** [comment]
Mientras satisfaga las condiciones para hacer el match, el orden es por fecha. No importa si hay otro match posible que haga más "óptima" la transacción. 
Como dices, el enunciado está mal. 
Saludos

**Comment by mesantamaria** [comment]
En #80 dicen que se ordena primero según el mejor precio de venta o compra. Si ahí hubiera empate entre varias se tendría que ordenar por fecha.
Cuál de los 2 está bien?
