### ISSUE TITLE
Enunciado edificios, interacción contradictorio

### ISSUE THREAD

**Issue by masoto22** [IIC2233/syllabus#120]
Hola

Tengo una duda de enunciado. 

En la sección 3.3 Edificios dice "En el caso de que no hayan recursos o trabajadores suficientes para construir el edificio, se le deberá informar al usuario de esto y no permitir la construcción", pero en la sección 5 Interacción por consola, en el tercer punto, dice "Se debe indicar al usuario cuales son los edificios que se pueden construir, considerando los recursos del jugador, los edificios existentes y el límite de edificios por tipo". Cuál de estas dos instrucciones es la que se debe seguir? ya que según lo que entiendo, la primera sugiere que el usuario indica cualquier edificio y si no se puede, se responde que no y no se permite la cosntrucción; pero la segunda sugiere hacer un input con opciones de los edificios que se pueden construir y ahí el usuario elige. Entonces no sé cuál de los dos enfoques hay que seguir o lo que se quiso decir.

Gracias

**Comment by gatochico** [comment]
Hola! 

La respuesta a tu duda está en la issue #111 , Saludos!
