### ISSUE TITLE
Test 1 - rutas posibles

### ISSUE THREAD

**Issue by dasobarzo** [IIC2233/Syllabus#120]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Test 1 - rutas posibles

[Hola, en el test 1 el valor esperado con 1 estaciones intermedia es 1, pero según yo y leyendo el enunciado esto debería ser 0, ya que nunca llega a B con una estación intermedia solo hay
A-B-A
A-B-D
A-B-E
A-D-A
A-D-E

Y si podemos ver, nunca llega a B, como se pide]

[**def test_1(self):
        """
        Verificar cantidad de rutas con cantidad específica de estaciones intermedias
        y diagonales cíclicas.
        """
        conexiones = [
            [1, 1, 0, 1, 0],
            [1, 0, 0, 1, 1],
            [0, 1, 1, 0, 1],
            [1, 0, 0, 0, 1],
            [1, 0, 1, 0, 0],
        ]
        estaciones = ["A", "B", "C", "D", "E"]

        red = RedMetro(conexiones, estaciones)
        resultado_estudiante = red.rutas_posibles("A", "B", 1)
        resultado_esperado = 1

        self.assertEqual(resultado_estudiante, resultado_esperado)**]

**Comment by SSParzival** [comment]
Hola buenas, en ese test existe la ruta A-A-B, así que es correcto que sí existe una ruta con una estación intermedia de A hasta B (la estación intermedia puede ser cualquier estación).
