### ISSUE TITLE
Duda de Herencia en Clases

### ISSUE THREAD

**Issue by fernandolalanne** [IIC2233/syllabus#120]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

[Describe tu duda de manera detallada, explicando los contenidos en cuestión y ojalá colocando código o un caso de uso de ejemplo]
Hola! Escribo porque no me quedó muy claro la implementación de la herencia en clases. Por ejemplo en el código adjunto la clase Auto es una superase de la clase FurgónEscolar y cuando define la subclase se escribe un init con los atributos de la clase FurgónEscolar y después para heredar los métodos de Auto escribe nuevamente un init y en ese init incluye la palabra "kms" que en estricto rigor no está definida en los atributos de Auto entonces la verdad es que ahí me perdí y no entendí el formato de implementación.

Desde ya muchas gracias!
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

class Auto:
    
    def __init__(self, ma, mo, a, c, k):
        self.marca = ma
        self.modelo = mo
        self.año = a
        self.color = c
        self.__kilometraje = k
        self.__dueño = None

    def conducir(self, kms):
        print(f"Conduciendo {kms} kilómetros")
        self.__kilometraje += kms

    def vender(self, nuevo_dueño):
        self.__dueño = nuevo_dueño
        print(f"Auto vendido a {nuevo_dueño}")

    def leer_odometro(self):
        return self.__kilometraje

class FurgónEscolar(Auto): # Aquí se marca de donde hereda
    """Subclase de Auto"""
    
    def __init__(self, marca, modelo, año, color, kms):
        # Para inicializar algunos datos en la clase madre, llamamos explícitamente 
        # al __init__ de esa clase.
        Auto.__init__(self, marca, modelo, año, color, kms)
        # Este atributo existe únicamente para objetos de tipo FurgonEscolar, 
        # pero no para todos los objetos de clase Auto 
        self.niños_y_niñas = []
    
    # inscribir_niño_o_niña es un método específico de esta subclase.
    def inscribir_niño_o_niña(self, niño_o_niña):
        self.niños_y_niñas.append(niño_o_niña)

**Comment by tqmbanados** [comment]
Hola! Si te fijas, el último argumento del ```__init__()``` de la superclase ```Auto``` se llama ```k``` y representa el kilometraje actual del auto. El argumento ```kms``` en el ```__init__()``` de la subclase, se envía al llamado de la superclase que lo lee como ```k```.
