### ISSUE TITLE
Duda @staticmethod

### ISSUE THREAD

**Issue by bpardobravo** [IIC2233/syllabus#120]
Hola, podrían explicarme cuándo conviene usar static method o qué ventajas da?
Cuál es la diferencia entre:
1
```python
class Auto:
    @staticmethod
    def tiempo_revision(tipo):
        if tipo == 'auto':
            return 10
        elif tipo == 'moto':
            return 25
        return 30
    
    def __init__(self):
        self.tipo_vehiculo = choice(['moto', 'camioneta', 'auto'])
        self.tiempo_revision = self.tiempo_revision(self.tipo_vehiculo)
```
2
```python
class Auto2:
    def __init__(self):
        self.tipo_vehiculo = choice(['moto', 'camioneta', 'auto'])
        if self.tipo_vehiculo=='auto':
            self.tiempo_revision = 10
        elif self.tipo_vehiculo=='moto':
            self.tiempo_revision = 25
        else:
            self.tiempo_revision = 30
```
Gratitude

**Comment by KnowYourselves** [comment]
Hola @bpardobravo!

Los métodos estáticos son métodos que estrictamente hablando, no usan información del objeto (no utilizan el `self`) pero no tienen sentido fuera de la clase. En este caso la función `tiempo_revision` no tiene sentido si no es en el contexto de la clase. Es por esto que por temas de orden de código es mejor tener estas funciones dentro de la clase que fuera.

Ahora en cuanto a la diferencia entre los dos casos que propones, funcionalmente es lo mismo pero el primero es mucho más legible, ordenado y fácil de modificar.

Espero haberte ayudado!
