### ISSUE TITLE
Carta Cambio de Sentido

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#1200]
Cuando se ocupa la carta de cambio de sentido, ¿el jugador que la ocupa vuelve a jugar?.

**Comment by jirarrazabal** [comment]
Hola! No. Cuando se ocupa la carta le toca al jugador siguiente pero en el nuevo sentido. Por ejemplo, si el juego estaba fluyendo hacia la derecha, le toca a la persona a la izquierda del que jugó la carta. Suerte!
