### ISSUE TITLE
Mandar mensajes a todos los clientes funciona distinto cada vez que se corre el codigo

### ISSUE THREAD

**Issue by josefapv** [IIC2233/syllabus#1201]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, me surgió un problema extraño al tratar de cumplir la condición de que al momento de que se conecten x (en mi caso 4) jugadores se cierre la sala de espera y se abra la ventana de juego. Al cumplirse esta condición envió un mensaje a todos los clientes por medio de una función, el cual al ser captado debiese emitir las señales correspondientes para cerrar la sala de espera y abrir la ventana de juego. El problema es que este mensaje se envía cuando quiere. Al correr diversas veces mi código, cada vez se envía a distintos clientes, y solo algunas veces a todos, y efectivamente cuando esto sucede se cierra la sala de espera y se abre la ventana de juego. Lo anterior, me parece extraño ya que la función para enviar mensaje a todos los clientes me funciona en otras partes del código correctamente. Mi versión actual se encuentra subida a mi repositorio, para si por favor lo pueden revisar, ya que no entiendo a que se puede deber. Gracias de ante mano.

**Comment by aaossa** [comment]
Hola @josefapv , ¿pudiste solucionar este problema? Lo que te recomendaría para intentar detectar posibles errores es tratar de comentar los `try`/`except` que tengas relacionados con el envío de datos utilizando *sockets*. Ahora, es raro que algunos clientes funcionen y otros no, así que avísame si pudiste arreglarlo (si es así, cómo lo hiciste) y si no has podido arreglarlo intenta subir un nuevo avance a tu repositorio por si alcanzo a darle una mirada 😅 ¡Mucho ánimo con la tarea!
