### ISSUE TITLE
Serialización string e imagen

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#1201]
Hola, estoy medio confundido con la parte del envio de cartas. Para el id color estoy usando (ID).to_bytes(n_bytes, orden) como sugiere el enunciado y eso lo "extiendo"(extend) a un bytearray vacio, sin embargo, quedo en la duda con la parte de serializar el string. Tengo dos cosas en mente (no es mi codigo es un ejemplo de ayudantia):
import pickle
string = "hola"
string_serializado_1 = pickle.dumps(tupla)
string_serializado_2 = tupla.encode()
Cual es la formas correcta de serializar para luego poder hacer extend y meter este string serializado a mi bytearrey con la info?
Tambien, cual es la forma de serializar imagenes? Con encode() ? 
Otra pregunta más que tengo de lo mismo, luego de tener toda la info necesaria para enviar a los clientes dentro de mi bytearray, debo aplicarle a este el metodo .encode antes aplicar el metodo send??

Como pueden ver quede con una gran duda conceptual sobre esta materia, es la única actividad del curso que no pude hacer :(. Espero puedan guiarme con mi duda para poder entender mejor esta materia.

**Comment by matiasmasjuan** [comment]
Hola @dsepulveda3 !

No hay una forma correcta para serializar un objeto en particular, por lo que puedes utilizar tanto **pickle** como **encode** y ambas maneras van a estar **correctas**. Sin embargo, debes tener en cuenta que *encode()* es **sólo** para serializar *strings*, mientras que con **pickle** puedes serializar cualquier *string*, *integer*, *lista*, *objeto*, etc. Por lo tanto, si deseas serializar un *diccionario* a través de *encode*, deberás utilizar la librería **json** para *serializar* ese *diccionario* a *string* y posteriormente aplicarle el **método** *encode()*.

Una vez hecho esto, puedes realizar un **extend** a tu *bytearray()* original y de esta manera ir construyendo el mensaje.

Con respecto a serializar imagenes, dentro de los contenidos del curso, especificamente en **serialización** se dió un ejemplo en donde se abre un *archivo* en forma de *lectura de bytes*. Puedes utilizar esa información para agregar esos *bytes* de la imagen al mismo *bytearray* original.

Con respecto al método *send()*, no es necesario hacer un *encode()* a tu *bytearray()* original antes de enviarlo, ya que tu *bytearray* ya es un arreglo de **bytes**, por lo que se puede enviar sin problemas.

Lo que más te **recomiendo**, es que tengas mucho cuidado de **qué** cosas estas agregando a tu *bytearray* y en **qué** orden, pues a la hora de enviar la información al **cliente** (o del cliente al servidor) deberás **utilizar** el **mismo formato** de lectura para ir **deserializando** el contenido.

Por ejemplo, imaginemos que quiero mandar un mensaje diciendo "hola", en donde lo primero quiero enviar el **largo** de este en forma de bytes, y luego el mensaje de "hola". Al momento de enviar el *bytearray()* con el contenido, el receptor primero deberia recibir el mensaje del largo y luego el del mensaje "hola". Si se hace en el orden contrario, se produciría un error.

Espero que esto haya podido resolver tus dudas. Cualquier consulta me avisas

Saludos y mucho éxito con la tarea! 😄

**Comment by NikiHV** [comment]
De lo que dices entiendo que `encode()` serializa un _string_ a un _bytearray_, y que por tanto se puede ocupar para serializar el color o tipo de una carta y enviarla por los _socket_, pero entonces ¿qué pasa con la  issue #1219? que dice que el `encode` no podría ser un protocolo válido de serialización, pues solo codifica.

Además dices que si leo una imagen en _bytes_ no sería necesario serializarla para enviarla por los _socket_ porque ya está en _bytes_, pero en el enunciado dice que debe estar serializada esa información. Eso lo pregunté en la issue #1219 (porque encontré redundante serializar algo que ya estaba en _bytes_) y me respondieron que debía hacerlo de todas formas por lo mencionado en el enunciado de la tarea. De paso, ¿cómo serializo un _bytearray_?

Lo que yo tenía entendido es que `encode` codifica un mensaje y `pickle` o `json` lo serializan... pero ahora que lo pienso `pickle` serializa y a la vez codifica un objeto. Así que ahora `encode` también podría clasificar como que hace ambos... ya no sé qué hacer 😬

**Comment by matiasmasjuan** [comment]
Hola @NikiHV !

Entiendo que a veces estos contenidos tienden a confundir mucho 😅, por lo que intentaré ser lo más claro posible.

1. Tal como dices, ```encode()``` codifica sólo un *string*, por lo que si deseas *serializarlo* tendrías que utilizar otro método. Podrías usar un ```json.dumps(algo)``` y luego implementar un ```encode()``` al resultado, o bien podrías utilizar ```pickle``` e inmediatamente podrías serializarlo y codificarlo.

2. Hay múltiples formas de serializar una imagen. Para darte un ejemplo de manera simple, podrías leer la imagen y luego volver a serializarla. Y si, puedes volver a serializar un bytearray, aplicando nuevamente el método ```pickle.dumps(bytearray)``` (por ejemplo), pero depende de cómo estés modelando tu envío de información ver si es necesario hacer esto último.

3. ```pickle``` y ```json``` serializan, solamente que lo realizan en distintos formatos y tienen sus respectivas ventajas y desventajas. Lo que si debes hacer en caso de serializar por ```json```, es además aplicar el método ```encode()``` por que sino no podrás mandar la información de manera codificada.

En resumen, si crees que te estas complicando mucho, utiliza el mismo protocolo de serialización y codificación para todos tus objetos. En ese sentido, podrías utilizar ```pickle```. **Recuerda** que es **MUY IMPORTANTE** aplicar el **mismo** protocolo de recibimiento de información, vale decir, el proceso de deserialización.

Espero que esto haya podido aclarar un poco tus dudas, y mucho éxito con la tarea! 😄

**Comment by NikiHV** [comment]
Oooh muchas gracias!! Vi la luz jajajaja

Quedó todo bien claro y ordenado en mi cabecita, gracias!! 🤗

**Comment by beatrizacuna** [comment]
Hola!! Hice lo que dijiste ( @matiasmasjuan ) de serializar una imagen que ya es un bytearray con dumps, pero al intentar deserializarla en el cliente estoy teniendo problemas. Lo que hice fue: datos_deserializados3 = pickle.loads(datos3) (3 porque la imagen es lo "tercero" que se recibe en cuanto a mensaje que se guardarán), luego de haber escuchado al servidor e ir recibiendo el mensaje en chunks y uniéndolos a otro bytearray (datos3). Pero esto me esta tirando error del tipo:
![Captura de pantalla 2020-07-03 a la(s) 02 05 39](https://user-images.githubusercontent.com/48481963/86437085-b8a18000-bcd1-11ea-8e2c-5466129985a0.png)
No entiendo cuál es mi error :(

**Comment by matiasmasjuan** [comment]
Hola @beatrizacuna !

Entiendo lo que señalas. Lo mas probable es que ese error se deba a que estás utilizando distintos protocolos de serialización y deserialización. Por ejemplo:

```python
mi_arreglo_bytes = bytearray()
string_serializado = "ejemplo".encode()
mi_arreglo_bytes.extend(string_serializado)

# lo siguiente produce un error:
string_deserializado = pickle.loads(mi_arreglo_bytes)
```
Por lo tanto, intentaría revisar que no estás haciendo ningún protocolo de serialización para tu imagen que luego no se haga cuando se deserializa.

En caso de que esto no funcionara, la otra posibilidad es que estás teniendo problemas con el envío de chunks. Vale decir, si estas mandando un ```bytearray()``` con 100.000 ```bytes```, es posible que a través de los ```chunks``` al aplicar el ```recv``` no estés completando correctamente los 100.000 ```bytes``` enviados, lo que produce un posterior error en la serialización.

Saludos y avisame cómo te va! 😄

**Comment by beatrizacuna** [comment]
Yaa entiendo muchas gracias! 😸  vi la materia de serialización de nuevo, pero aún no entiendo bien cómo deserializar un bytearray (la imagen) que es serializado con pickle.dumps, y luego es leído por chunks, añadiendo cada chunk a otro bytearray. Hasta ahora lo estaba haciendo con pickle.loads, pero como dijiste, ahí se produce el error.

**Comment by matiasmasjuan** [comment]
Tal como se dijo en la ***Issue*** #1289 , en una de las **ayudantías** del [2019-2](https://github.com/IIC2233/syllabus-2019-2/tree/master/Ayudantias/AY08), se explica muy bien como **enviar** iterativamente paquetes **pequeños** de ```bytes``` en lugar de enviar toda la información de manera inmediata.

La idea es que vayas enviando estos ```chunks``` y almacenandolos en un ```bytearray()```, para finalmente después realizar un ```pickle.loads()``` al último ```bytearray``` y tener la información deserializada.

Suerte! 😄

**Comment by beatrizacuna** [comment]
Muchas gracias!! 😸
