### ISSUE TITLE
Carta válida 

### ISSUE THREAD

**Issue by amparostevens** [IIC2233/syllabus#1202]
Hola! 
En el enunciado sale que si la carta en el _pozo es un +2 no se puede jugar la carta color ni sentido_, pero eso aplica siempre o sólo en caso que el +2 me lo hayan tirado a mi y ahora yo como jugador tengo que tirar otra carta? 

Para que se entienda mejor pongo un ejemplo:
- Jugador 1 tira la **carta +2**
- Pozo tiene la **carta +2**
- Jugador 2 no posee otro +2 por lo tanto **saca 2** cartas del mazo.
- Pozo sigue teniendo la **carta +2**

Mi pregunta es si el jugador siguiente puede tirar una **carta sentido** (que posea el mismo color del +2) o **color**

**Comment by jirarrazabal** [comment]
Hola! El caso aplica solo si el +2 fue para mí, es decir que una vez que el jugador robo 2 cartas, el jugador que viene retoma el juego con normalidad, pudiendo tirar una carta sentido, color o cualquier otra que sea válida según el color que se está jugando. Suerte!

**Comment by amparostevens** [comment]
Gracias!!
