### ISSUE TITLE
Cambio de color enunciado

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1203]
Hola! En el enunciado dice que cuando se juega la carta de cambio de color se produce que  en el siguiente
turno solo se puedan jugar cartas del color que fue seleccionado u otra carta de cambio de color, esto significa de que en el siguiente turno, el cliente que esta afectado por la carta cambio de color, tampoco pueda robar cartas?

**Comment by DCCollao** [comment]
Hola RonaldoSosa!

No, lo que implica el cambio de color es que para poder jugar una carta, ésta debe ser del nuevo color u otra carta de cambio de color. Si el jugador al que le toca en este turno posterior al cambio de color no tiene una carta del color seleccionado(o cambio de color), deberá robar.

Espero que haya quedado claro!

**Comment by RonaldoSosa** [comment]
Entendido!Graciasss!
