### ISSUE TITLE
Duda con los pop ups

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#1204]
Hola! Tengo una duda con el uso de pop ups. El problema es que acabo de cachar que en el enunciado en el pie sale el uso de QDialog. Es necesario hacerlo con eso? Yo ya lo hice con un Qwidget que aparece al utilizar la carta color. Tendría que cambiarlo? 
Saludos!

**Comment by DCCollao** [comment]
Hola @tedroppelmann!

No, no es necesario utilizar QDialog para los pop ups, era solamente una recomendación. Mientras cumpla el objetivo y sus condiciones de activación, es válido usar la forma que te parezca más conveniente.
