### ISSUE TITLE
QWidget: Must construct a QApplication before a QWidget

### ISSUE THREAD

**Issue by BFry712** [IIC2233/syllabus#1205]
### Prerrequisitos

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holaaa! queria saber porque puede estar pasando este error :c me pasa cuando instancio el **controlador** de la interfaz al igual que en la AF05

**Comment by lucasprato** [comment]
Hola @BFry712, puedes porfa pushear tu tarea al repo?

**Comment by BFry712** [comment]
Hola @lucasprato !
ya está arriba! c:

**Comment by lucasprato** [comment]
Hola @BFry712, dos cosas:
1. El problema directo que ocurre es que en el `main.py` de la carpeta `client`, `APP = QApplication([])`debe instanciarse antes que `cliente = Cliente(host, port)`. Por ello sale el error _Must construct a QApplication before a QWidget_. Ojo con la variable`APP,` por PEP-8 debería ser `app`.
2. Ojo con el manejo de señales de la `Interfaz` para mostrar la ventana:
     - Para mostrar la ventana, la conexión que debes establecer es entre **una señal y el método de la ventana para mostrarla**.
     - El método `mostrar_ventana_espera` no debe llamar al método de la señal que muestra la ventana, sino que tiene que **emitir la señal** `show_ventana_espera`. De esta forma el flujo debería ser algo así: 
    En el cliente se acciona `self.controlador.mostrar_ventana_espera()`, quien va a emitir la señal `show_ventana_espera`, la cual está conectada en el `__init__` con el método correspondiente de la `VentanaEspera` que abre la ventana. Ejecuté lo que te señalé y funciona.

Éxito en la tarea!!!

**Comment by BFry712** [comment]
Buenisimaa! Muchas gracias @lucasprato !!! :D
