### ISSUE TITLE
Duda aviso cambio color

### ISSUE THREAD

**Issue by milosoria** [IIC2233/syllabus#1206]
Hola! En el enunciado dicen que es necesario aviar al resto de los participantes cuando un jugador juega una carta de cambio de color y elige uno. Es necesario que sea a través de un pop-up? Puede ser utilizando el label que indica el color del costado derecho?
![image](https://user-images.githubusercontent.com/61996784/86144844-33954b80-bac4-11ea-9e64-78c90a3c507b.png)

**Comment by jirarrazabal** [comment]
Hola! En el enunciado dice que debes avisar al resto de los jugadores el color seleccionado de alguna forma. Puede ser un pop-up o como tú lo desees. Mientras quede claro el nuevo color para los demás, puedes usar el label. Mucha Suerte!
