### ISSUE TITLE
Duda sobre casos de colocación de carreteras

### ISSUE THREAD

**Issue by dedmu5** [IIC2233/syllabus#1206]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, haciendo la tarea me surgieron dudas sobre ciertos casos de colocación de carreteras:
Notar que el numero de los nodos están escritos en la interfaz gráfica.
1.  Caso 1
![image](https://user-images.githubusercontent.com/65060602/100923147-86cd5900-34bd-11eb-8993-541509a61f9c.png)
¿Las carreteras de jugadores contrarios pueden unise?, y de ser así,  ¿cualquiera de los dos jugadores puede construir una carretera entre los nodos 21 y 22?

2. Caso 2 
![image](https://user-images.githubusercontent.com/65060602/100923582-2559ba00-34be-11eb-9216-cc283585a09c.png)
¿Puede darse este caso? (una carretera de un jugador conecta con una choza del jugador contrario)

**Comment by rodrigobj99** [comment]
Hola @dedmu5 !

En el caso 1 tu suposición es correcta, cualquiera de los dos jugadores puede poner una carretera entre los nodos 21 y 22, sin embargo recuerda que solo puede haber una carretera en cada camino o arista del hexágono, por lo tanto aquel que construya primero le impide construir al otro en esa arista.

En el caso 2 lo que preguntas también puede ocurrir, ya que cumple la regla de estar junto a una carretera ya existente del mismo jugador, lo que no podría pasar es que coloques otra carretera morada en la arista madera-arcilla, ya que en ese caso la carretera estaría junto a una choza rival y eso no se puede según las reglas de construcción.

Espero haber aclarado tus dudas, cualquier cosa me avisas!

**Comment by dedmu5** [comment]
> Hola @dedmu5 !
> 
> En el caso 1 tu suposición es correcta, cualquiera de los dos jugadores puede poner una carretera entre los nodos 21 y 22, sin embargo recuerda que solo puede haber una carretera en cada camino o arista del hexágono, por lo tanto aquel que construya primero le impide construir al otro en esa arista.
> 
> En el caso 2 lo que preguntas también puede ocurrir, ya que cumple la regla de estar junto a una carretera ya existente del mismo jugador, lo que no podría pasar es que coloques otra carretera morada en la arista madera-arcilla, ya que en ese caso la carretera estaría junto a una choza rival y eso no se puede según las reglas de construcción.
> 
> Espero haber aclarado tus dudas, cualquier cosa me avisas!

![image](https://user-images.githubusercontent.com/65060602/100945484-13890e80-34e0-11eb-8ccd-eecc6b75f9ca.png)
Y en este todos los jugadores pueden colocar una choza en el nodo 21??

**Comment by dedmu5** [comment]
![image](https://user-images.githubusercontent.com/65060602/100946944-42ed4a80-34e3-11eb-9aa4-8070b79276b6.png)
Gracias!!!
Y en este caso todos los jugadores pueden colocar una choza en el nodo 16?

**Comment by rodrigobj99** [comment]
En este caso todos los jugadores que cuenten con los recursos necesarios pueden colocar una choza en el nodo 16.

Saludos!
