### ISSUE TITLE
Personalizar botón de cerrar ventana

### ISSUE THREAD

**Issue by mc-cari** [IIC2233/syllabus#1207]
Hola, se puede personalizar el botón cerrar ventana de un Qdialog? por ejemplo, hacer que emita una señal al presionarlo con un clicked.connect()

**Comment by SamWeinstein** [comment]
Hola! Claro que se puede! Podrías intentar implementar algo así sobre escribiendo el closeEvent, que es el evento que se capta cada vez que se intenta cerrar una ventana. Recuerda mencionarlo y explicarlo claramente en tu README. 

Saludos!

**Comment by mc-cari** [comment]
ya, gracias.
