### ISSUE TITLE
Jugadores con la misma cantidad de caminos consecutivos

### ISSUE THREAD

**Issue by n4chin** [IIC2233/syllabus#1208]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
¿Qué pasa cuando hay dos jugadores con la misma cantidad de caminos consecutivos, o como no está en el enunciado quedaría a mi criterio a quien darle los puntos de caminos? 

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by EduardoIllanes** [comment]
Hola @n4chin! Como no esta especificado en el enunciado queda a tu criterio y no olvides mencionarlo en el README. Saludos!
