### ISSUE TITLE
que pasa cuando alguien gana

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2233/syllabus#1208]
Hola! tengo una duda sobre lo que pasa al ganar. Debería salir un mensaje o algo? o se termina el programa nomas?
gracias

**Comment by jirarrazabal** [comment]
Hola! Se debe informar a cada jugador si 
 ganó o perdió la partida. Suerte!

**Comment by jirarrazabal** [comment]
Hola! Cuando alguien gana se debe mostrar una ventana final o pop-up donde haya un label para cada jugador junto a si perdió o ganó, y un botón que redirija a la ventana de inicio. Suerte
