### ISSUE TITLE
Tipo de codificación

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#1209]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! tengo una duda con el método de codificación de mensajes, es que en el enunciado de la tarea sale que se hace con UTF-8 pero estaba leyendo las issues, y la mayoría preguntan por JSON,  cual de los dos hay que usar?

**Comment by matiasmasjuan** [comment]
Hola @Natydlb !

Tal como señala el enunciado:

![utf-8](https://user-images.githubusercontent.com/48495638/100940962-9fe30380-34d7-11eb-92ca-648538274415.png)

Esto es en el caso de que quieras transformar de ***strings*** a ***bytes***. Por lo tanto, si lo primero que haces es **serializar** por **Json**, entonces  tendrás un *string*. La idea es a este string le incluyas el formato **utf-8** al momento de especificar el *encoding*. A continuación se mostraría un ejemplo:

```python
mensaje_serializado = json.dumps(mensaje)
mensaje_bytes = mensaje_serializado.encode('utf-8')
```

De esta forma, luego de realizar el *json.dumps*, harás un *encoding* al *string* en el formato solicitado (**utf-8**).

Saludos y mucho éxito con la tarea! :smile:

**Comment by Natydlb** [comment]
muchas gracias!
