### ISSUE TITLE
carta cambio de sentido de dos jugadores

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2233/syllabus#1209]
Hola! tengo una duda sobre lo que pasa al jugar la carta "cambio de sentido" cuando hay dos jugadores. no tiene efecto o vuelve a jugar el que la puso?

**Comment by SamWeinstein** [comment]
Hola! Debería cambiar el sentido de la misma manera que lo hace cuando hay más jugadores, nada especial ni distinto debería pasar cuando sólo hay 2 jugadores. Entonces en este caso simplemente le toca jugar al otro jugador!
