### ISSUE TITLE
Crear Carpeta T01

### ISSUE THREAD

**Issue by fnberrios** [IIC2233/syllabus#121]
Hola! ¿Puedo definir una carpeta que contenga a los archivos contrincantes.csv, pilotos.csv, pistas.csv y vehículos.csv y luego solicitar que al momento de que el corrector revise mi tarea cree esta carpeta para el buen funcionamiento del código?
Gracias.

**Comment by jeschuwirth** [comment]
Hola!

Creo que esto no sigue el enunciado, pero es completamente razonable y es una manera mucho más correcta de modularizar, por lo que te recomiendo subir una carpeta **vacia** llamada archivos_csv o database y explicar en el readme que el ayudante debe colocar ahí los archivos .csv

Para evitar problemas te recomiendo citar esta issue en el readme, de ese modo te aseguras no tener problemas con la corrección

**Comment by cfalvarez2** [comment]
Sí, sí puedes hacerlo, pero debes especificar en el readme que guardaste los archivos .csv en una carpeta. Y recuerda también que los path se deben almacenar en ``parametros.py``.
Suerte con la tarea :)

**Comment by fnberrios** [comment]
Bkn, gracias!
