### ISSUE TITLE
puntajess

### ISSUE THREAD

**Issue by martin-santiago** [IIC2233/syllabus#121]
cuando al ejecutar un turno seleccionamos la opcion [2] salir, el puntaje que llevabamos en esa partida debe ser agregado al documento puntajes.txt?? o se debe simplemente borrar?

**Comment by JuaniAndres** [comment]
Hola @martin-santiago 
Si se selecciona la opción de salir del programa no se considera como que el usuario se rindió por lo que no se deberá guardar el puntaje de esa partida. Ojo igual que si el usuario elige la opción de rendirse en ese caso si tendrás que guardar su puntaje.
Espero haber aclarado tu duda
