### ISSUE TITLE
Quitar paréntesis de la fórmula de probabilidades

### ISSUE THREAD

**Issue by GHarrisB** [IIC2233/Syllabus#121]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

![image](https://user-images.githubusercontent.com/101297259/163077689-6bb61807-7985-44ed-aff7-189ab6d89e16.png)

Hola, me di cuenta de que el paréntesis que está antes de Favorito no está cerrado, por lo que me da la impresión de que puedo omitir este paréntesis con tal de que las probabilidades tengan mayor sentido, ya que de esta manera no serán casi siempre negativas. Mi duda es, si esta interpretación de la fórmula es posible argumentarla como un supuesto en mi README.md, o de lo contrario me bajarían puntos por detallar mal la fórmula.

**Comment by jtvaldivia** [comment]
Hola, 
debido a que falta ese parentesis vamos a dejar a criterio propio la decision de incluir, pero debes aclarar en el readme.md como lo dejaste expresado, y por que. Destacar que el resto de la formula debe mantenerse segun el enunciado.
