### ISSUE TITLE
Menú tiene que ser igual al enunciado?

### ISSUE THREAD

**Issue by Valind4** [IIC2233/Syllabus#121]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holi, quería preguntar si el menú debe ser igual al enunciado, mismos espacios y forma, o si también puedo como "decorarlo" para que se vea más bonito o por ejemplo si el dato que ingreso no existe devolver texto, por ejemplo "código no existe, intente nuevamente"
gracias<3

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by vgalfaro** [comment]
Hola! en el enunciado se da un ejemplo menú, por lo tanto puedes personalizarlo como gustes mientras cumplas con lo pedido, respecto a lo segundo, si una acción (visualizar, plantar, etc.) falla (en el enunciado dice cuales pueden fallar) se tiene que imprimir un mensaje en la terminal, queda a tu elección que dirá este mientras avises que falló, saludos!
