### ISSUE TITLE
Duda Balance inicial usuarios ya registrados

### ISSUE THREAD

**Issue by augustoas** [IIC2233/Syllabus#121]
Hola ! Tengo una duda en cómo calcular el balance inicial del sistema, el balance de los usuarios que están en los archivos .csv. Mi duda es si debo calcular según sus orders cuánta plata tienen de cada moneda o si tambien les tengo que sumar las 50.000 por registro en cada uno de los mercados en que ya están. Tambien debo asumir que las orders que se realizaron son válidas? es decir, que hayan querido comprar algún currency teniendo la plata o vendido algo que tienen. Eso, estoy medio perdido en cómo se calcula el balance inicial de los usuarios ya registrados anteriormente, Saludos !

**Comment by augustoas** [comment]
Se etendió la pregunta? No está especificado la plata inicial que tuvieron todos estos usuarios ya registrados, puedo suponer que partieron con un saldo inicial a mi criterio y ejecutar sus órdenes despues? o NO considerar esas ordenes iniciales y fijar un balance inicial a mi criterio?

**Comment by fnquinteros** [comment]
Hola 😄

queda a tu criterio como manejar el balance inicial del sistema, aunque deberías considerar las orders iniciales como válidas, si no no tendría sentido que te las demos 😅 saludos!

**Comment by augustoas** [comment]
Gracias ! Para aclarar entonces... Las orders válidas serían las que están activas verdad? esas obviamente las tengo que considerar pero el balance despues de las orders que ya hicieron match lo dejo a mi criterio? Saludos

**Comment by fnquinteros** [comment]
Así es :) saludos

**Comment by fnquinteros** [comment]
Hola, sorry por el problema, pero será necesario que el dinero inicial de cada usuario que exista previamente se calcule en base a sus asks y bids. Tu duda se encontraba respondida en la issue #41.

Perdón nuevamente 😞 
Saludos!

**Comment by augustoas** [comment]
Ok, no te preocupes. Saludos !!

**Comment by SarahEverke** [comment]
¿Que pasa si al calcular el dinero inicial de cada usuario que existe previamente en base a sus asks y bids, me dan valores negativos?

**Comment by sebacruzd** [comment]
@SarahEverke la idea de calcularlo es que no quede negativo. A lo más que quede en 0. Por ejemplo si estuviera quedando con -10.000, es porque en realidad hubiera tenido 10.000 más (haciendo que ahora si pueda gastarlos y quedar en 0).

Espero que se entienda la aclaración,
Saludos!

**Comment by SarahEverke** [comment]
Gracias!!
