### ISSUE TITLE
Enunciado, referido a "levantar"

### ISSUE THREAD

**Issue by BenjaMedinaPUC** [IIC2233/Syllabus#121]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! esperando que se encuentren bien, les escribo para saber si es que en la parte 2 de la tarea, cuando se habla de  "levantar" ¿refiere a notificar el error en consola o cerrar la consola? Estaré atento a su respuesta :)  
![image](https://github.com/IIC2233/Syllabus/assets/111039575/45823cb3-dd56-4a94-a284-fdec14291218)

**Comment by Dominique236** [comment]
Hola!
Efectivamente como dices, "levantar" se refiere a mostrar en consola (hacer _print_) uno o los dos mensajes según corresponda.
Cuéntame si esto resuelve tu duda 😊

**Comment by BenjaMedinaPUC** [comment]
Vale, comprendo. Muchas gracias!
