### ISSUE TITLE
Sacar archivos que no son de la tarea

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#121]
Hola!
Resulta que subí (git push) los archivos.csv al repositorio, pero me dí cuenta leyendo las otras dudas que no se deben subir ya que ustedes cuentan con ellos.
Cómo puedo bajarlos de ahí?
Gracias.

**Comment by gatochico** [comment]
Hola! 

Si borras los archivos de repo local y haces push deberían bajarse del repo remoto. Además, te recomiendo ir practicando el uso del[ `.gitignore`](https://riptutorial.com/es/git/example/885/ignorando-archivos-y-directorios-con-un-archivo--gitignore) para la siguiente tarea, ya que se usa exactamente para esos casos (trabajar con archivos en el repo local que no quieres que se suban al remoto).

Avísanos como te va!

**Comment by tzehnder** [comment]
para usar el .gitignore debo ponerlo al final del nombre de mi archivo?

**Comment by aaossa** [comment]
@tzehnder para usar `.gitignore` sobre un archivo debes agregar el nombre de dicho archivo en el `.gitignore`. Una vez que agregues la modificación del `.gitignore` en el flujo de git, se dejará de hacer seguimiento a los cambios en el archivo ignorado. Supongamos que tengo un archivo llamado `prohibido.xd` y quiero ignorarlo para no subirlo al repo. Entonces, en mi .gitignore, debo agregarlo, de forma que el archivo .gitignore queda así:

```
prohibido.xd
```

No debo modificar la extensión del archivo que quiero ignorar, sino que debo agregar su nombre al interior del archivo `.gitignore`. 

PS: Recuerda que un archivo .gitignore es un archivo sin nombre y de extensión `.gitignore`.

**Comment by kipasten** [comment]
Cómo se crea el archivo .gitignore?? desde la consola? o la interfaz del computador?

**Comment by aaossa** [comment]
Como más te acomode! Puedes hacerlo de ambas formas. En consola (también sirve _git bash_) puedes usar el comando `touch .gitignore` y se creara el archivo vacío, mientras que en la interfaz del computador puedes hacerlo como creas cualquier archivo normalmente.
