### ISSUE TITLE
Respecto a las copias

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus#121]
Con un amigo estamos conversando mientras escribimos código, y ambos estábamos pensando en usar un enfoque similar para la defensa y ataque de las civilizaciones. ¿Podria ser que esto se tome como copia? Ya que pienso que justamente lo mas optimo es realizarlo de esa manera y supongo que mas o menos va a quedar parecida esa linea, obviamente con mi respectiva estructura de clases y etc, y el con la suya.

**Comment by iqacevedo** [comment]
Hola @MartinAracena,

En primer lugar, no puedes compartir expresamente como planeas resolver una parte de la tarea públicamente, no puedes decir explicitamente : _"voy a ocupar estas funciones para esta parte especifica de la tarea"_ (por lo cual tu comentario se edito).  

Respondiendo a tu pregunta, discutir como realizar una parte de la tarea no se considera como copia, a menos de que toda su tarea sea muy parecida, lo que no pueden hacer es usar el mismo código. 

Saludos !
