### ISSUE TITLE
Forma de citar

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#121]
¿Se pide algún formato específico para citar o hacer referencias de código, cuando se busca código en stackoverflow u otra página similar?
¿los documentos oficiales de las librerías de python se deben citar ?

**Comment by fgbruna** [comment]
Con respecto a tu primera pregunta, el [estándar de facto](https://es.wikipedia.org/wiki/Est%C3%A1ndar_de_facto)  para citar código hecho por terceros
(y que no tenga una [licencia restrictiva](https://choosealicense.com/) en cuanto al uso de este) en python suele ser a través de [docstrings](https://www.python.org/dev/peps/pep-0257/).
Un ejemplo seria de la siguiente forma:
```python
def mi_metodo(mis_parametros):
       '''As seen at: <url o fuente>'''
       # código a citar
```
