### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by mvveram** [IIC2233/Syllabus#121]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, estaba revisando la parte de .gitignore de la tarea y no me abre el link de ayuda. También, tengo la duda de como se crea este en la carpeta T1.

Muchas gracias de antemano

**Comment by MrNachoX** [comment]
Hola @mvveram! Puedes encontrar un ejemplo de .gitignore [aquí](https://github.com/IIC2233/contenidos/blob/master/.gitignore) o visitar la documentación de git [aquí](https://git-scm.com/docs/gitignore).
Para crear el .gitignore se hace lo mismo que con el resto de archivos, lo creas en tu computador y luego haces git add, git commit y git push para subirlo a tu repositorio. Este archivo debe deberá estar **dentro de tu carpeta Tareas/T1/**, no se aceptará que lo pongan en otra parte aunque funcione. Recuerda que debes ignorar los archivos Enunciado.pdf, programones.csv, entrenadores.csv, objetos.csv, evoluciones.csv y también los archivos autogenerados como la carpeta \_\_pycache\_\_, la carpeta .vscode, entre otros.

**Comment by MrNachoX** [comment]
Hola, el .gitignore no es necesario para el avance.

**Comment by SofiaFigueroaa** [comment]
Hola!
Tenía una duda al crear el archivo .gitignore, al crearlo en la carpeta T1 me sale este error en el computador "No puedes utilizar un nombre que comience por un punto “.” porque este tipo de nombres están reservados para el sistema. Elige otro nombre.", y no me permite crear la carpeta con ese nombre (tengo Mac). He buscando info al respecto y no he encontrado nada, qué se puede hacer al respecto?
De antemano mil gracias!

**Comment by gabo1243** [comment]
Hola, sobre eso: Entonces ¿los archivos .csv y el enunciado no deberían aparecer en el repositorio de github (por lo del gitignore)?

**Comment by MrNachoX** [comment]
Efectivamente, los archivos .csv y el enunciado no deberían aparecer en la carpeta T1 de tu repositorio de github.
