### ISSUE TITLE
Carta +2

### ISSUE THREAD

**Issue by dchahuan** [IIC2233/syllabus#1210]
Al estar una carta +2 en el pozo, se tiene que robar una carta para que se active el pozo o si juego una carta equivocada tambien se activa??

**Comment by szabala** [comment]
Hola! A que te refieres con "activar el pozo" ?

**Comment by dchahuan** [comment]
a que el jugador que esta en su turno roba la cantidad de cartas acumuladas.

**Comment by szabala** [comment]
No se si entendí bien tu pregunta. Si hay un +2 en el pozo es por una de dos razones:

-  Se jugo un +2 en el turno anterior. En este caso, si el jugador actual no posee otro +2, roba la cantidad acumulada de cartas y termina su turno.
- Un jugador robo la cantidad acumulada en el turno anterior. En este caso, el jugador actual puede jugar una carta del mismo color que el ultimo +2 en el pozo.

Espero haber aclarado tu duda!
