### ISSUE TITLE
ModuleNotFoundError al intentar hace pickle.loads en el cliente, al recibir un objeto desde el servidor

### ISSUE THREAD

**Issue by IgorPeralta** [IIC2233/syllabus#1210]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Al mandar un objeto de clase ClaseX que está en un archivo llamado archivo_clasex desde el servidor al cliente, el cliente al hacer pickle.loads muestra el error ModuleNotFoundError: No module named "archivo_clasex"... y tengo un "import archivo_clasex" en el cliente.
También he probado a definir las clases a la fuerza en mi archivo y tampoco funciona. También importar solo la clase desde el archivo, pero nada, sigue apareciendo el mismo error
Probé instanciando a la fuerza algo para probar que el import archivo_clasex estaba funcionando y sí lo estaba haciendo.

Ayuda, no sé qué hacer jsjsjsjs

De antemano, muchas gracias!

**Comment by matiasmasjuan** [comment]
Hola @IgorPeralta !

Se habla de un tema similar en la **issue** #1188 . En todo caso, según lo que me dices, falta definir la **clase** en el ```archivo_clase_x``` del cliente, ya que sólo estás creando el módulo (según lo que indicas, quizás estoy equivocado)

Avísame cómo te va! :smile:

**Comment by IgorPeralta** [comment]
Sisi, leí esa issue y tal vez no estoy entendiendo lo que estoy haciendo, pero básicamente tengo el **mismo archivo** con las clases en el servidor y el cliente... y en ambos las estoy importando (de manera separada, onda cada uno con su propio archivo en su propio directorio)... pero no sé porqué a pesar de importar el archivo_clase_x, como que no lo "detecta" como definido el cliente??? No sé si eso hace sentido jajajaj

**Comment by matiasmasjuan** [comment]
Que extraño eso :thinking: . Hazle push a tu repo para que lo pueda revisar.

Saludos!

**Comment by matiasmasjuan** [comment]
Revisando tu código me di cuenta que el error se debe a los directorios de donde importas.  En el servidor importas ```clase_x```, mientras que en el cliente tienes: ```import carpeta.clase_x```. Esto claramente va a producir un error, ya que el **objeto** que se intenta **deserializar** con **pickle** en el **cliente**, se intenta buscar en el directorio ```clase_x```, pero no existe, ya que sólo está ```carpeta.clase_x```. Por lo tanto, si deseas **deserializar** con **pickle**, debes tener en cuenta que el objeto que se serializa y des-serializa debe tener su clase en un directorio con el **mismo** nombre (incluyendo la carpeta).

Saludos! :smile:

**Comment by IgorPeralta** [comment]
No lo puedo creer, llevaba horas intentando solucionar esto!!! Me funcionó altiro! Te pasaste, muchísimaaaas graciaaaaas! 😄😄😄
