### ISSUE TITLE
Envío de datos con pickle

### ISSUE THREAD

**Issue by fhola23** [IIC2233/syllabus#1211]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

Hola. Hasta ahora en mi tarea la comunicación entre cliente y servidor la he desarrollado utilizando únicamente JSON. Hace dos días estoy estancado ya que necesito mandar una clase de mapa desde mi servidor a mi cliente y no he logrado hacer la serialización con pickle. El ejemplo que esta en los contenidos muestra el envío de una clase de pickle pero sin un largo del mensaje al inicio y luego una división en x cantidad de bytes, como se especifica en la tarea. Quería saber si me podían guiar en crear un protocolo de serialización con pickle. Muchísimas gracias de antemano

**Comment by rodrigobj99** [comment]
Hola @fhola23 !
Al serializar con pickle el mensaje queda automáticamente en un bytearray, por lo que para ver el largo del mensaje puedes simplemente usar `len()` al mensaje ya serializado, por otra parte para enviarlo en bloques de 60 bytes puedes ir iterando sobre el bytearray de 60 en 60.

Espero te sirva, cualquier cosa me avisas!

**Comment by fhola23** [comment]
Hola! Muchísimas gracias por tu respuesta. Logré armarme un ejemplo y enviar datos serializados con pickle utilizando el protocolo, pero cuando envío diccionarios desde el servidor mi cliente no los recibe como diccionarios, sino que aparentemente como strings.

###Envío desde el servidor
![image](https://user-images.githubusercontent.com/69604465/101076083-a332c980-3581-11eb-9194-f189d46fa6bf.png)

Pero cuando los recibo en el cliente, no me deja acceder a los datos del diccionario, aunque si imprimo los datos se me imprimen como diccionario en el terminal, pero no son una instancia de diccionario. Adjunto error asociado:

![image](https://user-images.githubusercontent.com/69604465/101076173-c2315b80-3581-11eb-9b1c-36f49a03244a.png)
![image](https://user-images.githubusercontent.com/69604465/101076181-c3fb1f00-3581-11eb-9d8a-e415333bed05.png)

**Comment by rodrigobj99** [comment]
Hola!
Podrías subir lo que llevas a tu repo? para ver que puede estar fallando.

Saludos!

**Comment by fhola23** [comment]
Subido! Muchísimas gracias 😄

**Comment by rodrigobj99** [comment]
Hola! 
Esto ocurre porque en tu metodo enviar transformas tu mensaje a un string antes de enviarlo, al cambiar eso funciona perfectamente.

Saludos!

**Comment by fhola23** [comment]
Ahí lo solucioné!! Muchísimas gracias por toda la ayuda, te pasaste! 😄
