### ISSUE TITLE
Problema con QLabel clickeable

### ISSUE THREAD

**Issue by totaurt** [IIC2233/syllabus#1211]
Hola! Hacer un QLabel personalizado para poder clickear en él es muy sencillo según lo que he estado leyendo. Creo una subclase del QLabel, la cual ocupo para instanciar los QLabels de las cartas y estas, al ser presionadas, emiten una señal a algún método de la Sala de Juego. He hecho esto, modificando parcialmente la definición de la clase y el lugar donde conecto la señal en varios intentos, pero ninguno me ha funcionado:(. 
Creo que puede deberse a que los guardo los QLabels dentro de un Layout para que se vean ordenados en la ventana y el evento mousePressEvent le ocurre a este último y no a las cartas. Si fuera así ¿cómo puedo solucionarlo? No he encontrado información al respecto en internet. Por otro lado, hacer los clicks por coordenadas sería demasiado complicado por la manera en que he pensado el juego (cambian para cada carta por la cantidad de ellas en la mano y por la cantidad de jugadores).
Espero puedan ayudarme, gracias de antemano!!

**Comment by lily416** [comment]
Para aquellos que tengan dudas sobre esto, revisen la issue #1173 primero.
Si su problema no se resuelve con eso, hagan una nueva issue.
