### ISSUE TITLE
Formas de desconexión de cliente

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#1212]
Hola, se supone que cuando un cliente sale del juego de forma deliberada, en las otras pantallas aparece como derrotado? y, dentro de las posibles formas de desconexión, solo esta esta cierto? No entra en juego el posible hecho de que al cliente se le caiga el internet?

**Comment by SamWeinstein** [comment]
Hola @dlmed ! 
Para tu primera pregunta; si! Cuando el cliente se desconecta, para efectos prácticos se debería manejar como si hubiera perdido, es decir, debería mostrarse y comportarse todo tal cual como lo hace cuando un cliente pierde. 
Para tu segunda pregunta, la idea es poder manejar todas las situaciones bajo las cuales se pudiera perder la conexión con el cliente. Es decir, por ejemplo, si el cliente apaga su computador, el programa no debería caerse, sino que, debería manejarse como se especifica en el enunciado. Por eso te recomiendo buscar una manera mas genérica de determinar cuando se perdió la conexión con un cliente. De esta manera, con modelar ese caso genérico, tienes todos los distintos casos de desconexión resueltos. 
Saludos!

**Comment by dlmed** [comment]
Si, lo tengo modelado tal cual como dices. A lo que me refería con la segunda pregunta es que, en el caso que el cliente pierde la conexión física a la red, el server lo expulsa y se sigue jugando con normalidad, por lo que en el cliente no se cierra el juego, sino que sigue abierta la pantalla y como no hay conexión local, no se puede enviar un mensaje que avise al cliente que se debe desplegar una advertencia de que se cayó la conexión o que perdió. Literal en este caso el cliente queda aislado, ya que como el servidor es el cerebro del juego, el cliente no puede tomar decisiones por su cuenta. Mi duda es, ¿hay que preocuparse de un caso así de específico?

**Comment by lily416** [comment]
@dlmed no tienes que preocuparte por casos relacionados a problemas de Internet, principalmente porque las tareas se ejecutan dentro de un mismo computador. 

Espero te deje más tranquilo al respecto,
Saludos y éxito en la tarea 👋🎴
