### ISSUE TITLE
Duda sobre sistema de turnos

### ISSUE THREAD

**Issue by dedmu5** [IIC2233/syllabus#1212]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, no entiendo cómo debo hacer que el jugador pase el turno. ¿Tengo que poner un botón pasar?, de ser así, ¿Hay un tiempo limitado para que el jugador haga una jugada?, ¿El jugador puede pasar sin tirar los dados?

**Comment by matiasmasjuan** [comment]
Hola @dedmu5 !

Respoderé tus preguntas en orden:

1. **Sí**, debe haber un botón para pasar de turno. Esto sale especificado en el criterio **6.2** del enunciado.

2. **No**, no hay un tiempo limitado para que el jugador haga una jugada. Puede tomarse el tiempo que quiera.

3. **No**, el jugador **no** puede **pasar** sin antes lanzar los dados. Esto está especificado en el siguiente apartado:

![ninguna_accion](https://user-images.githubusercontent.com/48495638/100946589-7bd8ef80-34e2-11eb-9e97-910748c52278.png)

Como el jugador no puede realizar **ninguna acción**, esto incluye el hecho de **terminar el turno**.

Saludos y mucho éxito con la tarea! :smile:
