### ISSUE TITLE
Duda sobre intercambios

### ISSUE THREAD

**Issue by dedmu5** [IIC2233/syllabus#1213]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, tengo dos dudas sobre el tema:
¿Un jugador necesita estar en su turno para solicitar intercambiar recursos con otro?, ¿Un jugador necesita estar en su turno para aceptar una solicitud de intercambio de recursos con otro?
Saludos!!

**Comment by matiasmasjuan** [comment]
Hola @dedmu5 !

Responderé tus preguntas por orden:

1. **Sí**, ej jugador **solo** puede **solicitar intercambiar** si **está** en su turno. Esto está indicado en la sección **4.2.4** del enunciado.

2. **No**, no es necesario que un jugador **deba** estar en su turno para **aceptar** la solicitud de intercambio. La idea es que apenas se envíe la solicitud, le aparezca la notificación al usuario con el que deseas intercambiar.

Saludos, y mucho éxito con la tarea! :smile:

**Comment by dedmu5** [comment]
> Hola @dedmu5 !
> 
> Responderé tus preguntas por orden:
> 
> 1. **Sí**, ej jugador **solo** puede **solicitar intercambiar** si **está** en su turno. Esto está indicado en la sección **4.2.4** del enunciado.
> 2. **No**, no es necesario que un jugador **deba** estar en su turno para **aceptar** la solicitud de intercambio. La idea es que apenas se envíe la solicitud, le aparezca la notificación al usuario con el que deseas intercambiar.
> 
> Saludos, y mucho éxito con la tarea! 😄

Hola!
A partir de lo que me respondiste me surgieron otras dudas:
1. ¿Para enviar un intercambio se debe antes verificar que el jugador a negociar tenga los recursos que se piden?, digo esto porque, dado que el jugador a negociar puede aceptar cuando quiera la solicitud, puede que en el momento exacto en el que le llega esta no tenga los recursos, pero puede "guardarla" para después cuando si los tenga.
2. ¿Qué pasa si, estando en mi turno, le envío un intercambio a otro usuario y este lo acepta cuando él tiene los recursos que pedí, pero yo no los que ofrecí?
3. ¿Qué pasa si, estando en mi turno, le envío un intercambio a otro usuario y este lo acepta cuando él no tiene los recursos que pedí, pero yo si los que ofrecí?
4. ¿Un usuario puede tener más de una solicitud de intercambio activa?

Por otro lado, me cuesta saber qué dice exactamente el enunciado al respecto (lo he leído varias veces), por lo que me gustaría que me dejaras claro qué cosa puedo hacer a mi gusto, para así yo poder tomar la decisión que menos casos borde me genere.
Gracias!!!!!

**Comment by matiasmasjuan** [comment]
Hola @dedmu5 !

1. **Sí**, la idea es verificar de forma **inmediata** si es que el jugador a negorciar **posee** los recursos para llevar a cabo el intercambio, de lo contrario, **no** se **enviará** la solicitdud. **No es que** el otro jugador pueda **guardar** la solicitud, ya que esto sería **incorrecto**. La idea es que el jugador envía la solicitud, y en ese mismo instante, se debe esperar a que el **otro** jugadro responda. Como sigue estando en el mismo turno del jugador, no es posible que el otro jugador **gane** recursos, por lo que **nunca** ocurrirá la situación que dices.

2. **Esto tampoco puede ocurrir**. Apenas se trata de **enviar** la solicitud, se debe comprobar que tanto tú como el otro jugador posean los recursos asociados al intercambio.

3. Misma situación que antes. **No puede ocurrir**, ya que se comprueba antes de que al otro jugador le llegue la solicitud. Vale decir, se intenta enviar, y en caso de un error, se notifica al usuario.

4. **No**, ya que un jugador puede hacer **solo una acción** en su turno. Si ya se hizo un intercambio, no se puede hacer otro. Además, la idea es que la respuesta al intercambio finalice antes de terminar el turno, ya que se debe **terminar** la acción de intercambio antes de poder finalizar el turno.

5. **No**, no se puede. En el enunciado se señala que un jugador solo puede hacer **una** jugada por turno.

6. Dado que la respuesta de la 5 es **no**, entonces **no** se puede hacer.

Puede que el enunciado indica las acciones a realizar en un turno, señalando que solo puede realizar **una** por turno. Quizás la parte más complicada sea el tema del intercambio, ya que no se profundiza en detalle como correspondería. Espero que con las respuestas anteriores haya quedado un poco mas claro qué es lo que se pide, y en base a eso saber qué se debe hacer un cómo.

En caso de que algo no haya quedado claro, siempre puedes preguntar.

Saludos! :smile:
