### ISSUE TITLE
Logs - indicar tamaño del mensaje

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#1213]
Hola, en la página 8 del enunciado, al final, menciona que en los logs se debe indicar el tamaño del mensaje; a qué se refiere con esto? Será el tamaño del mensaje enviado por el socket o se refiere a otra cosa? Por último, de qué forma se debe mostrar esto en la consola del servidor?

**Comment by SamWeinstein** [comment]
Hola @dlmed !  Con logs se refiere efectivamente a avisos en consola (prints) indicando todos los elementos mínimos que se especifican en el enunciado. Una forma de implementar esto es mediante una tabla, donde se muestran el cliente involucrado, el tipo de mensaje que se está enviando y bajo la sección de detalles, podrías indicar el largo del mensaje (y también su contenido). Estos mensajes se refieren justamente a los enviados entre el servidor y el cliente como tu bien dices, por ende sí, son los mensajes enviados mediante sockets. 

Saludos!

**Comment by dlmed** [comment]
Oka. Es necesario que el "contenido" sea específico? o puede ser algo general respecto a lo que se está enviando?

**Comment by SamWeinstein** [comment]
El contenido puede ser genérico. Al fin y al cabo, el objetivo de los logs es ayudarte a ti a entender como esta funcionando tu programa y facilitarte la tarea de debuggear. Debería cumplir la misma función que los clásicos prints que se hacen a lo largo del programa para encontrar errores, sólo que de una forma más formal, estandarizada y a la altura del servidor. Define las columnas de la tabla y sus contenidos de la manera que te sea más conveniente y debería estar bien. 

Saludos!
