### ISSUE TITLE
Interfaz gráfica - elementos superpuestos

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#1214]
Hola, en la distribución de puntaje, en la sección de Interfaz Gráfica: General dice: "Se visualiza correctamente la información. Los elementos no se superponen entre sí.", pero si en mi interfaz esto lo hago a propósito? Es decir, muestro las cartas (tanto del jugador como oponentes) una encima de la otra, de tal forma que quepan más cartas en el tablero. Esto se consideraría como descuento si funciona correctamente? Aquí una imagen de referencia:
![aaaaa](https://user-images.githubusercontent.com/37181953/86172884-11fc8a00-baed-11ea-9cbd-855fc4fa31ff.png)

**Comment by SamWeinstein** [comment]
Hola! Mientras se vea la información de cada carta correctamente y esa pequeña "superposición" no sea perjudicial, no deberían haber problemas. Eso sí, esa implementación debe ser justificada, es decir, debe aportar a la estetica/funcionamiento del juego y no estorbar ni complicar la corrección. De todos modos, indica claramente la razón de esta decisión en tu README, explicando porque en tu caso preferiste hacerlo así y porque consideraste que esta era una mejor opción. De todos modos, si lo único que buscas solucionar al hacer esta pequeña superposición es que quepan más cartas en el tablero, una solución más lógica y conveniente para no tener problemas podría ser aumentar directamente el tamaño del tablero. 
Saludos!

**Comment by dlmed** [comment]
Oka, es más que nada por un tema estético y ya lo probé y no da problemas
