### ISSUE TITLE
Problema con los Locks de Threading

### ISSUE THREAD

**Issue by Francisco5674** [IIC2233/syllabus#1215]
Hola, mi problema es bastante simple, en realidad esta en que mi cliente no siempre recibe la información del servidor, me asegure que el server siempre la mande con varios prints, pero el cliente no siempre la recibe, cuando pongo un Lock() de Threading en la parte del cliente que decodifica los mensajes del server el problema es menor, pero de todas formas algunos clientes no reciben cartas o no reciben el cambio de turno, o por ejemplo no ceden su turno y otros clientes también juegan su turno al mismo tiempo, es horrible!!, supongo que es un problema de Locks y donde ubicarlos, porque me ayudaron a que no sea tan frecuente, pero de todas formas el programa funciona mal mientras se juega, es imposible jugar por más de 20 segundos sin que se bugee.

**Comment by fdoflorenzano** [comment]
Hola @Francisco5674,

Miré tu repositorio y no has subido actualizaciones desde hace dos días, así que no sé si pude mirar la última versión. De todas formas, de lo que vi, no me consta el problema sean los *locks*. Intuyo el problema puede ser algo como las *issues* #1223 y #1193. Revisa si puede ser el caso, o sube tu última versión y nos avisas para verlo bien.

Saludos.
