### ISSUE TITLE
Mensajes salen desde el servidor para todos los clientes pero no le llegan solo al último que ingresa

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#1215]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Me pasa algo muy raro. Cuando conecto 4 clientes (cantidad máxima) funciona perfecto: se abre la sala de juego con todas las imágenes y botones que se le ponen en la interfaz. Pero cuando aprieto un botón, el mensaje no le llega al último cliente conectado. ¿Por qué puede ser? Cuando aprieto el botón de lanzar dados me sale esto:

Terminal del servidor:
![Seleccionar C__Windows_System32_cmd exe - python  main py 02-12-2020 22_58_20](https://user-images.githubusercontent.com/68581172/100954106-b0ed3e00-34f2-11eb-85a2-e3231a5ea525.png)

Terminal del último cliente conectado:
![C__Windows_System32_cmd exe - python  main py 02-12-2020 22_58_42](https://user-images.githubusercontent.com/68581172/100954046-94e99c80-34f2-11eb-9122-cacd482ec624.png)

Terminal de otro cliente:
![Seleccionar C__Windows_System32_cmd exe - python  main py 02-12-2020 22_58_35](https://user-images.githubusercontent.com/68581172/100954119-b8144c00-34f2-11eb-921d-0a7db0fb073a.png)

De verdad no logro encontrar el error porque el servidor le envía el mensaje a todos y no le llegan al último conectado. Sin embargo, los demás mensajes si los recibe (como el mensaje de comenzar la partida para que aparezca la sala de juego). Es como que se instancia la interfaz y ahí deja de escuchar al último. Y esto solo pasa cuando son 4 jugadores. Si son 3, funciona con los 3.

**Comment by Juampisaez** [comment]
Hola @kalarconvl 
Estaba viendo tu avance para entender mejor el problema, pero a mi si me aparecen los mensajes como recibidos en todos los clientes (no hay diferencia). Lo unico distinto (no se si esta actualizado) es que no me aparece en consola el nombre especifico de cada cliente.

Quedo atento :)

**Comment by kalarconvl** [comment]
Hola! Subí todo esa vez. Ahora haré push de nuevo a ver qué onda. ¿Lo probaste con 4 clientes? Porque no me funciona el botón, me sigue saliendo ese error :(

**Comment by kalarconvl** [comment]
O sea, no es un error, pero los dados se cambian en todos los clientes menos en el último conectado
