### ISSUE TITLE
[Error] OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by JaviGuzman** [IIC2233/syllabus#1216]
Hola! Llevo días intentando solucionar un problema que se relaciona tanto con la AF06 y la Tarea, pues cuando ejecuto el main del cliente me aparece OSError: [Errno 9] Bad file descriptor.
Realmente he buscado mil maneras de arreglarlo, pero aun no lo consigo, por si alguien podría ayudarme.

Gracias de antemano!

**Comment by arturobugueno** [comment]
Yo también tengo un error de ese tipo, pero cuando termino de repartir las cartas a cada jugador una vez que se pasan de la sala de espera al juego. Por lo que estaba viendo, tiene que ver con la conexión del socket del servidor. Parece que una vez que el socket se cierra (por abc motivo) y tratas de escuchar algo de nuevo (porque esta en un while True), tira ese error. 

Ahora, no se por qué el socket del servidor se cerraría. Trata de ver si es algo así. La explicación la acabo de encontrar acá [https://stackoverflow.com/questions/19624684/oserror-errno-9-bad-file-descriptor-in-python-3](url). No se si sea tu caso o el mío porque estoy en proceso de verlo.

**Comment by fdoflorenzano** [comment]
Hola @JaviGuzman,

Como bien dice @arturobugueno, ese error suele aparecer a uno de los lados de la conexión porque el otro lado cerró un *socket* mientras el otro lado esperaba seguir usando dicho *socket*. En este tipo de errores es importante prestes atención a que ocurre tanto en cliente como servidor, ya que es posible que veas un error a un lado, cuando en realidad el problema está al otro, y simplemente porque se cayó un lado, provoca error al otro.

Me concentraré en la AF06 ya que es más fácil de seguir el error. En este caso era tu cliente quien lanza el error que indicas, pero si te fijas en los *prints* del servidor, sale explícitamente que se cierra el *socket* del cliente recién conectado. Entonces el cliente alega porque intenta interactuar con el servidor, pero este último cerró la conexión.

¿Por qué cierra la conexión? Porque por la estructura base del programa entregado, se cierra siempre después intentar escuchar al cliente, ya sea después de hacerlo exitosamente o después de que una excepción es levantada. Como la impresión de `except ConnectionResetError` no aparece, se puede intuir que otro tipo de excepción provoca el error, y que de hecho luego aparece entre las impresiones del programa del servidor. Te recomiendo mirar esa sección de código y encontrar el error al escuchar los mensajes del cliente.

Cualquier duda nos avisas por aquí,
Saludos.

**Comment by JaviGuzman** [comment]
Eso me ayudó a arreglar el problema que tenía! Muchisimas gracias!
