### ISSUE TITLE
Descargar commit

### ISSUE THREAD

**Issue by pabloist** [IIC2233/syllabus#1216]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola buenas!

Disculpa quería consultar sobre como podría descargar un commit especifico sin alterar el resto de los archivos de mi repostorio, esto ya que debo enviar a recorregir y en un push posterior a la tarea 2 se actualizaron ciertos archivos y necesito referenciar especificamente los que fueron revisados por el ayudantes.

Gracias de antemano!

**Comment by Mjtala** [comment]
Hola @pabloist! Sigue estos pasos y cuéntame como te va!
Anda a tu carpeta T03:
**https://github.com/IIC2233/pabloist-iic2233-2020-2/tree/master/Tareas/T03**
Luego en la parte superior derecha apreta History
![Captura](https://user-images.githubusercontent.com/62020259/101017054-5979bd00-3548-11eb-8562-5b83b568d9b7.PNG)
En esa parte podrás encontrar todas versiones de tus diferentes commits y para acceder a ellos debes apretar el siguiente botón (este copiará la versión a la que quieres acceder):
![boton](https://user-images.githubusercontent.com/62020259/101017249-96de4a80-3548-11eb-83a2-6b51528cff6c.PNG)
Finalmente anda a tu git bash y pon el siguiente comando 
**git checkout <versión que copiaste en el paso anterior>**

Para volver a tu versión original debes hacer:
**git checkout master**

Cualquier cosa que no te funcione o si te queda alguna duda escríbeme!

**Comment by pabloist** [comment]
Muchas graciaaas si funcionó!!
