### ISSUE TITLE
Efecto grito DCC4

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1217]
Hola! En el enunciado dice que cuando alguien grita dcc4 hay dos efectos verdad , en caso de exito hace que el que tiene una carta robe 4 y si falla el mismo debe robar 4 , ya pero esto significa de que se debe "inhabilitar" la opcion de jugar carta o basta con hacer que le llegue un anuncio a su interfaz para que le avise lo que tiene que hacer, digo esto en caso de que grite y sea su turno ?
Además dicho esto tengo la duda de que si esta situación es factible, gritar dcc4 cuando es su turno , ya que por ejemplo nadie que posea una sola carta va a evitar gritar, casi por obligacion, no creo que vaya a robar una carta ya que solo se perjudicaria asi que es posible decir que que cuando alguien este en su turno y decida jugar o robar una carta no hay nadie más con una sola carta por ende si dicho jugador , el que tiene el turno, gritara dcc4 solo provocaria que el mismo tenga que robar 4 cartas y lo haria de forma conciente lo que se me hace ilogico

**Comment by szabala** [comment]
Hola! como se explica en el enunciado, un jugador puede gritar DCCuatro **en cualquier momento de la partida**, incluyendo en su propio turno. En ese caso, si se equivoca, robaría 4 cartas y su turno terminaría automáticamente (como se explica en la sección de _Robar Cartas_).

En cuanto a la factibilidad de esto, imagina el caso en que el jugador anterior se queda con una carta y nadie se da cuenta en su turno. Luego, en tu turno, te das cuenta que este jugador tiene una sola carta, por lo que gritas DCCuatro! Sin embargo, otro jugador fue mas rápido que tu y por lo tanto tienes que robar 😮 

Espero haber aclarado tu duda :smile:

**Comment by RonaldoSosa** [comment]
Yaaa pero unas cuantas cosas más para estar seguro :( ,no es necesario que la opción de jugar cartas en el caso de que sea su turno quede inhabilitada cuando vaya a robar las cartas verdad? si aprieta el botón termina su turno debido a que roba las cartas verdad? y otra cosa cuando quieres hacer que este robe las cartas necesariamente debe hacerse desde el mazo habitual ?No seria factible hacer que le llegue un anuncio al jugado con un boton ahí para que las robe , lo digo porque  de esa manera no podría jugar las cartas

**Comment by szabala** [comment]
Tratare de responder las preguntas en orden:
1.  Como se explica en el enunciado, luego de que un jugador roba una o múltiples cartas, su turno termina automáticamente. Entonces no debería poder jugar una carta si grito erróneamente DCCuatro en su turno.
2. Si, su turno termina cuando roba las cartas.
3. Queda a tu criterio como hacer que el jugador robe en esta situación. Hacer un anuncio es una buena idea :smile:
Saludos 👍

**Comment by RonaldoSosa** [comment]
Yaaaa muchas gracias me quedo claro!!!!!

**Comment by francisca0308** [comment]
Hola! Tengo una duda que me surge más que nada por comparar DCCuatro con UNO. 
Si me pongo en el caso de que un jugador juega una de sus dos últimas cartas, quedando con una sola y grita, y justo después grita otro jugador porque intentó gritar antes que el primero, pero no lo logró; ¿qué sucede? Porque si lo pienso como el juego UNO, no pasaría nada debido a que no fue un error sino un intento fallido, por lo tanto, a pesar de que el segundo jugador teóricamente "grita mal", no se le aplica el castigo.

Es por eso que a mí no me haría sentido castigarlo. En este sentido, ¿se puede asumir que solo hay un grito DCCuatro por turno y este puede ser exitoso o no?
