### ISSUE TITLE
Threads de Server se congelan al hacer wait() en él

### ISSUE THREAD

**Issue by juanpaxd** [IIC2233/syllabus#1217]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Mi duda es que tengo al servidor con los threads escuchando a los clientes. Cuando hago un wait() en el servidor esperando un set() del cliente, los threads se congelan y por ende nunca puede recibir este set. No sé cómo arreglar el error, he buscado por todos lados y no encuentro nada similar. Pd: El event es un atributo de la clase Server, que se reiniciaría luego de que el wait se completara, pero nunca pasa :(
Quisiera saber si hay una forma de hacer esperar al server que ocurra algo en los threads pero que los threads sigan funcionando.

**Comment by aaossa** [comment]
Hola @juanpaxd , ¿pudiste solucionar este problema? Miré tu código y no encontré un `Event`, ¿lo quitaste y ahora te funciona como esperas la aplicación? Avísame si sigues con este problema 😅 ¡Mucho ánimo con la tarea!

**Comment by juanpaxd** [comment]
Siii lo solucioné cambiando la forma en la que se ejecuta el codigo, creando una funcion que hiciera lo que se hubiese hecho activada la señal, y que se ejecutara cada vez que llegara lo que hubiese activado la señal. Además la estructura quedó mas ordenada y puedo editar lo que hace esa funcion de mejor manera c:.
