### ISSUE TITLE
terminar partida

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2233/syllabus#1218]
hola! puedo hacer que cuando se termine el juego aparezca un boton para volver a comenzar y que aparezca los labels de quienes ganaron y quienes perdieron? que no me di cuenta que tenia que ser un popup.

**Comment by jirarrazabal** [comment]
Hola! Debe mostrarse una ventana final o pop-up, debido a que la ventana de juego ya tiene mucha información. En esta deben estar los labels que mencionaste, y un botón que redirija a la ventana de inicio. Suerte!
