### ISSUE TITLE
Serialización de las cartas

### ISSUE THREAD

**Issue by NikiHV** [IIC2233/syllabus#1219]
Copio mi duda en esta issue, la había comentado en otra, pero lleva días sin contestarse :c

Hola!! Me queda una duda que tengo que se pregunta en esta issue, pero que no me quedó clara la respuesta.

Para la información que se envía (fuera del id y el largo), es decir, el color, la imagen de la carta, etc., el enunciado dice que debe enviarse serializada, pero no dice (hasta donde leí) con qué tipo de serialización. ¿Nosotros debemos decidir el protocolo de serialización del contenido mismo? ¿Qué serialización me recomendarían usar?

¿Si lo envío como bytes nomás estaría mal? Porque en ese caso solo estaría codificando y no serializando como pide el enunciado 😥 (Pero encuentro medio extra estar serializando si con codificar en bytes ya es suficiente)

_Originally posted by @NikiHV in https://github.com/IIC2233/syllabus/issues/1116#issuecomment-650842439_

**Comment by vicentevegaulloa** [comment]
Hola @NikiHV ! 

Disculpa la demora. Como en el enunciado solo se te pide que lo serialices y lo codifiiques en tu bytearray, queda a tu criterio como serializar el respectivo objeto. Respecto a tu última pregunta, estaría mal si no serializas antes de codificar los objetos en tu bytearray, ya que esto si lo especifica el enunciado. 

Una vez más disculpa por la demora. Espero haberte ayudado y haber entendido bien tu pregunta.

PD: Siento que la issue #1186 podría ayudarte también

**Comment by NikiHV** [comment]
Siii me quedó muy claro, muchas gracias!!

Y gracias por la issue que citaste, ya la había leído y también me fue de utilidad :)
