### ISSUE TITLE
Mensajes en log de consola

### ISSUE THREAD

**Issue by JoMarchant** [IIC2233/syllabus#1219]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En la parte de los logs del enunciado se pide que se imprima cualquier otro tipo de mensaje que se envíe o reciba de un cliente.

¿Es necesario imprimir todo el contenido del mensaje?, o, ¿puedo tratar de buscar una palabra u oración que lo resuma? Si no, probablemente me quede el mensaje impreso en más de una línea de mi tabla. Y otra duda, ¿Qué pasa con el mensaje que indica un lanzamiento de dados o mensaje de cualquier otra acción que ya esta impresa en consola?

**Comment by lucasprato** [comment]
Hola @JoMarchant!

Es buena idea imprimir una frase/palabra que resuma el tipo de información que se entrega. Ahora bien, también debes imprimir el mensaje. Para que no se desconfigure el formato de tu tabla puedes "truncar" el mensaje a un máximo de caracteres que muestre. De esa forma se visualiza lo que se está enviando y no se desordena la tabla. Asegúrate que sea una cantidad lo suficientemente grande como para que sea claro que se está enviando el mensaje. Además, documenta esta decisión en el Readme.

> ¿Qué pasa con el mensaje que indica un lanzamiento de dados o mensaje de cualquier otra acción que ya esta impresa en consola?

Independientemente que se visualice en la ventana, debes imprimir el log.

Éxito en la tarea!

**Comment by JoMarchant** [comment]
Yaaa, muchas gracias!!

**Comment by lucasprato** [comment]
Hola @JoMarchant!

Leí la parte del enunciado y cambié mi respuesta anterior.

Es buena idea imprimir una frase/palabra que resuma el tipo de información que se entrega. Sería algo parecido a la columna `Evento` del enunciado. Como se ve en el enunciado, no es necesario imprimir explícitamente el mensaje que se envía, pero sí debe ser visualizable toda información que envía. 

Por ejemplo, si lo que envías es un json de la forma `{"accion" : "recibir recursos", "recurso": madera, "cantidad" : 2}` **debes imprimir toda la información que se envía de una forma comprensible para un usuario**.  Como muestra la tabla del enunciado, puedes imprimir el log como ` recibir recursos | 2 maderas ` siendo la primera columna el tipo de información que se envía, y la segunda la información que se envía expuesta de forma ordenada. Esto además te ayuda a reducir el largo de lo que vas a imprimir. En casos excepcionales (quizás un mensaje muy largo del bonus del chat), podrías truncar el largo del mensaje, pero normalmente se pedirá que se impriman todos los detalles de lo enviado.

Recuerda que en el enunciado se puede ser de gran ayuda y perdón por no haberte respondido bien la primera vez 😁

Éxito en la tarea!
