### ISSUE TITLE
Duda Menú sobre uso extra de prints en buscar_y_regar

### ISSUE THREAD

**Issue by el-Jay-C** [IIC2233/Syllabus#122]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Mi consulta es si podemos usar prints extras **en caso de que lo consideremos necesario**, como en la función buscar_y_regar() que, al no retornar nada, no sabemos si realiza algo o no. Esto con el fin de que al utilizarlo en el menú el usuario pueda ver si se regó el predio. Algo similar a la imagen

![image](https://github.com/user-attachments/assets/3d936c72-5226-4340-afac-dd6087f232a2)

**Comment by Agusrush21** [comment]
Si, si se puede mientras cumpla con lo necesario

Aqui la issue que ya respondieron #121

**Comment by Agusrush21** [comment]
No deberia, ya que no cumple lo que te piden en la función 
Pero si puedes hacer distintos prints en el menu a tu conveniencia (esto ultimo respondido en la issue #89)

**Comment by catalinaortegacalderon** [comment]
hola! 

En realidad si se pueden usar prints si es que lo consideras necesario. Esto no debería interrumpir el flujo de los tests.

Efectivamente, como comenta tu compañero, puedes utilizar prints a conveniencia en la parte del menú.

Pero también puedes usar prints en las funciones. Es especialmente recomendable para debuggear

Saludos!
