### ISSUE TITLE
Valores archivo parametros.py

### ISSUE THREAD

**Issue by cchauriye** [IIC2233/syllabus#122]
Hola!

En el archivo "parámetros.py" todos los valores son None. ¿Es normal? Según el enunciado ahí ya deberían estar incorporados los costos y constantes. 

Gracias 😃

**Comment by gatochico** [comment]
Hola! 

Efectivamente, está bien que todos los parámetros estén en `None`. La idea es que tú los rellenes con los valores que salen en el enunciado. Por otro lado, puedes rellenar cualquier parámetro que no tenga un valor explícito en el enunciado con los valores que tu quieras (y te sean útiles) para probar tu tarea. 

Saludos! :car:

**Comment by cristobalgon** [comment]
Pregunta acerca de esto... Para rellenar los valores al finalizar la tarea, le debemos poder algún número aleatorio o los dejamos como lo pusimos para probar la tarea?

**Comment by lily416** [comment]
@cristobalgon Suban el `parametros.py` con los mismo valores con los que probaron sus tareas 😉 

Saludos y éxito con la tarea 👋🛵

**Comment by cchauriye** [comment]
Perfect, gracias!

**Comment by jadawabe** [comment]
Hola! Los parámetros se completan a mano o los tiene que hacer el programa?

**Comment by jeschuwirth** [comment]
@jadawabe, parametros.py se escribe a mano

**Comment by jadawabe** [comment]
Muchas gracias @jeschuwirth !
