### ISSUE TITLE
Plazo

### ISSUE THREAD

**Issue by masoto22** [IIC2233/syllabus#122]
Hola

Igual me da cosa preguntar esto, pero supongo que no hago nada malo al hacerlo y mis amigos me convencieron. Existe la remota posibilidad que den más plazo para la tarea? Dado que justo estamos en semana de ies y todo eso? 

Perdón si suena barsa xd

**Comment by quememo** [comment]
jajaja

**Comment by masoto22** [comment]
@quememo tú eres el que empezó la tarea hoy, no yo

**Comment by Hernan4444** [comment]
Hola,

Los plazos de las tareas se mantendrán tal como se indica en el enunciado.

Saludos,

**Comment by masoto22** [comment]
Lo intenté jeje gracias por responder
