### ISSUE TITLE
Idioma comentarios Tarea 01

### ISSUE THREAD

**Issue by IchottMano** [IIC2233/Syllabus#122]
Buenos días,
Abro esta issue debido a que me entró la duda si los comentarios de mi tarea deben ser exclusivamente en español, ya que a veces las escribo en inglés sin darme cuenta, habrá algún descuento por esto? y si las escribo todas en inglés?
Muchas gracias.

**Comment by hanavarrete** [comment]
La idea es que los comentarios ayuden al corrector a entender tu código, por lo que recomendaría que estos fueran en español, debido a que el ayudante podría no hablar  no entenderlo. Saludos

**Comment by fnquinteros** [comment]
No te preocupes por eso :) saludos!

**Comment by GustavPrudencio** [comment]
no hay ningún descuento por escribir cosas en ingles y español mientras se entienda :) (puede que el ayudante no se maneje con el ingles)
