### ISSUE TITLE
Caracteres max grupo

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#122]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Titulo, y qué otras restricciones tienen, además de deber comenzar con 2 o más personas?

**Comment by fernandosmither** [comment]
Lo otro, puedo añadir la restricción de no utilizar comas en el nombre de un grupo?

**Comment by Tsbalart** [comment]
Hola @fernandosmither! No hay más restricciones que las que salen en el enunciado, puedes agregar esa restricción aunque igual podrías asumir que no se ingresaran nombres con comas. De todas formas especificalo en el readme! Exito con la tarea!

**Comment by fernandosmither** [comment]
Muchas gracias!
