### ISSUE TITLE
Crear archivo.py abridor de archivos.csv

### ISSUE THREAD

**Issue by RicciOff** [IIC2233/Syllabus#122]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, saben si se puede crear otro archivo.py como abridor de csv, guardando todo así en listas y después llamando a estas listas desde mi código principal; o incluyo este abridor de archivos dentro de parametros.py? Porque según lo que explicaban en otra issue #77 , los csv pueden ser entregados con distinto orden de columnas, y para hacer frente a ese caso aumentan mucho mis líneas de código y el archivo principal me queda muy largo. Gracias!

**Comment by Gsalinas1506** [comment]
Hola!
Es muy buena idea tener una función que se encargue de ller los .csv. Bajo ningún caso esta forma de abrir archivos debe ir en parámetros.py ya que en este archivo solo van constantes que nunca son modificadas en el programa (ya que son eso, parámetros del programa). Ten en cuenta eso sí que definir en un archivo una variable global que luego es importada a otro módulo se considera mala práctica, lo que implica un descuento en la tarea :scream:

Las variables globales son todas aquellas que no están dentro de un scope definido en el programa (dentro de un método, función, ciclo, etc ...) y que por lo tanto puedes ser llamadas desde cualquier punto de este.

Desde tu punto de vista, lo ideal sería implementar una forma de cargar los datos sin que se involucre una variables global, por ejemplo, con una función.

Mucho éxito con la tarea! 🎲🃏
