### ISSUE TITLE
Duda almacenamiento información asignación de recursos 

### ISSUE THREAD

**Issue by JoseValencia125** [IIC2233/Syllabus#122]
¿La información relacionada con la asignación de recursos e incendios que no se encuentra dentro de los archivos csv, como la ubicación de los recursos, recursos que han sido usados en un incendio, etc, debe ser guardada en algún archivo o solo debe persistir mientras dure la ejecución del programa?

**Comment by stephichau** [comment]
Hola @JoseValencia125 !

Del enunciado: 
> Cualquier cambio realizado durante la ejecución del programa deberá persistir en una próxima ejecución de éste. Lo anterior implica que se deben actualizar las bases de datos para reflejar los cambios.

saludos :)
