### ISSUE TITLE
Readme de Parte 1 - Funcionalidades

### ISSUE THREAD

**Issue by kai-yamamoto1** [IIC2233/Syllabus#122]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
No entiendo si para la Parte 1 - Funcionalidades es necesario completar el Readme o no, porque no veo la plantilla para hacerlo.
Muchas gracias

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by roahoki** [comment]
Hola @kai-yamamoto1! Tal como dices, **no** es necesario que explicites tu implementación de **la parte 1 corregida por tests** en tu readme. Sin embargo, eres libre de hacerlo para documentar que entiendes lo que hace tu programa :)
