### ISSUE TITLE
Duda sobre error en main.py

### ISSUE THREAD

**Issue by nataliameza** [IIC2233/syllabus#122]
Hola, al intentar correr el archivo main.py me entrega el siguiente error 
![imagen](https://user-images.githubusercontent.com/69607822/90980211-0eebac00-e528-11ea-978f-cdb452ff119f.png)
NUM_BARCOS si se me imprime, pero el tablero no. 
Además al correr el programa desde VSC con la flechita verde si me lo corre. ¿Qué puede ser?

**Comment by MatiasDuhalde** [comment]
Hola @nataliameza !

Con respecto a tu primer error, qué versión de Python estás ocupando? Esto lo puedes comprobar con el comando `python --version`, y la correcta debería ser Python `3.7.*`. El error que te aparece al ejecutar el código es porque Python está intentando decodificar/leer el archivo `tablero.py` usando el encoding `ASCII`, sin embargo, este se usa por defecto en las versiones `2.*`, y en las `3.*` se pasó a usar `utf-8` como encoding por default (el cual sería el encoding correcto para ejecutar el archivo).

De todas maneras, una manera de forzar un encoding específico a un archivo, sería agregando el siguiente "comentario" en la primera línea del archivo, como se explica [aquí](https://www.python.org/dev/peps/pep-0263/): `# -*- coding: utf-8 -*- `

Con respecto a tu segunda duda, estos errores no corresponden a errores del código en si, sino a errores del `linter` de Python, que tienen que ver con estilo, y no deberían afectar la ejecución de tu código.

**Comment by nataliameza** [comment]
Hola! Gracias por responder. Efectivamente al ejecutar el codigo qe me comentas en la terminal me aparece lo siguiente.
![imagen](https://user-images.githubusercontent.com/69607822/91052595-acf67980-e5ef-11ea-9418-693f0543bd57.png)

Esto me parece muy raro, ya que a principios del curso yo me desinstalé la versión de python anterior que tenía que era la 2.7 y me instalé la 3.7.8, que de hecho me aparece en mis carpetas. Creo que tengo dos versiones instaladas, pero nose como borrar la anterior, ya que no me aparece en mis aplicaciones. ¿Qué podría hacer?

**Comment by MatiasDuhalde** [comment]
Hola @nataliameza !

El comando que debes ejecutar es `python --version` (notar los guiones), pero a juzgar por el error que te retornó, estás con la versión 2.7 de Python. Una opción sería intentar ejecutando los archivos usando el comando `python3` (por ejemplo, `python3 main.py`), para forzar la ejecución del programa en la versión 3.7.8.

Para desinstalar Python 2.7 en tu sistema operativo, puedes usar el instalador que se descarga desde [python.org](python.org) (esto funciona bien en Windows, no estoy seguro si es igual en Mac OS). Otra opción si la primera no funciona, sería seguir el procedimiento de [esta respuesta](https://stackoverflow.com/questions/3819449/how-to-uninstall-python-2-7-on-a-mac-os-x-10-6-4) en StackOverflow. Sin embargo, ten mucho cuidado borrando archivos del sistema!

**Comment by nataliameza** [comment]
efectivamente al ejecutar python3 me funciona, estuve viendo las opciones que me dices y la primera no me funcionó y la segunda, en los comentarios recomiendan no hacerlo ya que se puede borrar el mismo sistema Mac Os X . 
Duda: si no borro python 2.7 y ejecuto todo con python3, al momento de ustedes bajar mi tarea tendrían problemas para verla?

**Comment by MatiasDuhalde** [comment]
Hola nuevamente! 

Si la tarea funciona en tu computador con el comando `python3`, no deberíamos tener problemas para evaluarla, ya que nosotros usamos la versión 3.7.* para ejecutar los programas. :sparkles:
