### ISSUE TITLE
Recoleccion Recursos Andromeda y EDCM

### ISSUE THREAD

**Issue by emeiese** [IIC2233/Syllabus#122]
Dada la issue #73, sigo sin entender lo siguiente:
Al momento de preguntarle al usuario si desea obtener su información (i.e.: la cantidad de minerales y deuterio de cada galaxia + planetas conquistados), se asume que al momento de hacer este pedido, a todos los planetas de la galaxia se le deben recolectar los recursos? O esta cantidad no se actualiza hasta que lo hace el usuario de manera manual?

Por ejemplo, si al momento de abrir el juego consulto sobre los minerales y deuterio de la Galaxia Andrómeda, el programa debería mostrarme que es 0 para cada uno, ya que en ningún minuto el usuario ha decidido recolectar sus recursos. Sin embargo, si abro el juego y decido ir directamente a recolectar los recursos del planeta Pandora de la galaxia Andrómeda y luego decido pedir por la información de esa galaxia, el programa debería mostrarme un numero mayor a 0 (dado por la fecha de creacion del planeta pandora, el ponderador del nivel de economía y su tasa de recolección)
Esto es correcto, o, cómo puse más arriba, se asume que al momento de consultar, la recolección es "instantánea"?

**Comment by IchottMano** [comment]
@emeiese Hola!
Como dice la issue #73 , tu recolectas los recursos del planeta que estas visitando y los pones en un "fondo común".
Lo que haces cuando deseas obtener la información, es similar a revisar el "estado de cuentas" de ese fondo, por lo que no tiene nada que ver con la recolección de los recursos, si no que solo intentas ver el estado acual del fondo.
Espero haber resuelto tu duda y mucha suerte con tu tarea!
Saludos!

**Comment by emeiese** [comment]
@IchottMano Mmm, sigue sin quedarme muy claro la verdad (es que no respondiste exactamente a lo que dije arriba ajaja)
Entonces, por lo que tu dices, si al momento de abrir el juego consulto inmediatamente sobre los minerales y deuterio de la Galaxia Andrómeda, el programa debería mostrarme que es 0 para cada uno, ya que en ningún minuto el usuario ha decidido recolectar sus recursos. Es correcto? 

Saludos, y muchas gracias.

**Comment by IchottMano** [comment]
@emeiese Efectivamente.
Sin embargo, recuerda que en el punto 6.4 se habla que al comenzar a jugar con una galaxia uno parte con 1000 minerales y deuterio, por lo que debería decir 1000 para cada uno.
Saludos!
