### ISSUE TITLE
"Editar 20 lineas"

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#122]
Hola!
No entiendo por qué mencionan que podemos editar hasta 20 lineas de código. Esto es en qué momento?
Gracias.

**Comment by gatochico** [comment]
Hola! Lo de editar hasta 20 líneas se refiere a lo siguiente:

Una vez entregada la tarea, tienes hasta el lunes para hacer entrega de un archivo `Readme.md`. Digamos que entre la fecha de entrega de la tarea y el README te das cuenta que tu tarea posee algún error que impide su ejecución, o que te descuenta puntos en algún item. Ya no puedes entregar de nuevo, pero puedes solicitar que el ayudante **modifique hasta 20 líneas de tu tarea** para arreglar dicho error.

Puedes indicar, por ejemplo:
```En la línea 20 del archivo main.py, agregar:
archivo = open("ejemplo.py","w")
archivo.write("Este es un ejemplo!")
archivo.close()
```

Y el ayudante lo realizará. Sin embargo, hay un descuento en décimas asociado a esto. (1 décima cada 4 líneas, con un máximo de cambiar 20 líneas). Por lo que tienes que pensar si conviene dicho arreglo o no.

Espero haber respondido tu duda! (:
