### ISSUE TITLE
Duda con recv()

### ISSUE THREAD

**Issue by andrea1vlib** [IIC2233/syllabus#1220]
Hola, tengo un problema en mi código, uso un while para recibir usuarios hasta que empieza la partida, pero me da la impresión de que se crearon más de los que necesitaba y quería saber si hay alguna forma de borrar los recv() que no me sirven, como "resetearlos" para poder continuar con la sig función. 
graciaaas

**Comment by gatochico** [comment]
Hola! A qué te refieres con "borrar los recv"? Borrar los usuarios que están por sobre el límite de la sala u otra cosa? 

Quedo atenta!

**Comment by andrea1vlib** [comment]
me refiero a que creo mas recv  de los que son necesarios, y despues la info les llega a estos recv y no a los que deberian, y por lo tanto la informacion se pierde

**Comment by gatochico** [comment]
Revisé tu último push en tu repositorio, y por lo que puedo ver, creo que hay un poco de confusión con el método recv() y los sockets de los clientes.

Cuando realizas el servidor, lo que debería pasar es que el servidor tenga un thread que sea exclusivamente dedicado para escuchar posibles nuevas conexiones con un cliente. Una vez que capta una conexión, el socket del servidor debe ejecutar el método accept para generar la conexión con un cliente y luego **crear un thread nuevo que se dedique a solo estar escuchando posibles mensajes del cliente que se acaba de meter**. De esta forma, estos thread están constantemente corriendo mientras la conexión con cualquier cliente se mantenga y cuando reciben un mensaje, sabemos de que cliente proviene, ya que dicho mensaje será captado por el thread de el cliente que lo mandó. Por ejemplo, digamos que tenemos un server y 2 clientes conectados. Los threads mínimos que habrían (los dedicados a escuchar y generar conexiones) serían:

- Thread que escucha conexiones
- Thread que escucha al cliente 1
- Thread que escucha al cliente 2

¿A que voy con esto? Bueno, en cada thread que escucha a un cliente debería estar ejecutandose un mecanismo de posible escucha. Y en estos mecanismos es donde está el método `socket_cliente.recv()`: lo que hace es estar atento a cualquier mensaje que haya mandado el cliente en particular al que estoy escuchando. 

En tu código tienes un solo thread para manejar a tanto las conexiones nuevas como la de los clientes que ya conectaste (la funcion `escuchar`). Ahí tienes la variable `socket_cliente`, la cual solo guarda el último socket que se conectó. EL resto de los sockets previos no son usados en el programa, por lo que ya dejarás de escuchar cualquier mensaje que estos manden cada vez que sobreescribas la variable. Quizás esa sea la causa la sensación de que se 'pierden mensajes', porque pierdes la referencia a los sockets anteriores y por ende ya no recibes su información.

El cómo modelar correctamente estos threads queda bastante grande para un solo comentario en issues, por lo que te recomendaría ver los ejemplos que hay en los contenidos de threading en más detalle y revisar el archivo server.py de la [AY10](https://github.com/IIC2233/syllabus/blob/master/Ayudant%C3%ADas/AY10/server.py), para que vayas comparando paso a paso como ahí se generan los códigos para escuchar clientes vs. cómo está en el servidor tuyo. 

Espero haberme explicado bien, o que el link que envié a la ayudantía te sirva para guiarte en como definir el código de ese proceso. Cualquier duda específica la puedes preguntar por aquí!

Éxito!

**Comment by andrea1vlib** [comment]
graciaaaas
