### ISSUE TITLE
Error al cerrar ventana

### ISSUE THREAD

**Issue by eliasbruchfeld** [IIC2233/syllabus#1220]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo un error en mi código que no me deja avanzar mucho. Cuando se conecta un cliente al servidor, el servidor manda un mensaje para que se abra la ventana de espera. Esto significa que si puedo estar conectado sin tener la ventana abierta porque primero se conecta y después abre la ventana (si se que suena obvio). Sin embargo, cuando cierro la ventana me sale el siguiente mensaje y se cae el servidor:

ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto

El hecho de que el mensaje esté en español y no en ingles me hace pensar que no es un error de python, sino que algo del computador pero no estoy seguro. No entiendo por que el servidor se cae, si se supone que este no depende de que esté la ventana abierta, como dije al principio.

Básicamente, si nunca abro la ventana, la conexión funciona perfecto, pero si la abro y después la cierro la conexión se cae, como si esta dependiera de que la ventana esté abierta (siendo que no es).

PD: mientras esta la ventana abierta si puedo enviar mensajes de buena manera.

**Comment by aaossa** [comment]
Hola @eliasbruchfeld , no es necesario que hagas una *issue* de nuevo si no tienes respuesta 😅 Les ayudantes están haciendo lo posible por responder todas las *issues* lo antes posible, así que evita abrir una *issue* duplicada. Si quieres agregar información, puedes editar la *issue*. Sobre tu duda en particular, ya ha aparecido un error similar en otras *issues* (puedes encontrarlas buscando el código de error en el buscador de *issues*), así que te recomendaría darles una mirada (si es que no lo has hecho) en lo que les ayudantes te responden

**Comment by eliasbruchfeld** [comment]
Lo se, es  que como había pasado un día y medio y nadie se la asigno pensé que no la habían visto. Igual mire todas esas issues y no me sirven porque ahí en verdad se estaba desconectando un cliente, en cambio acá no. De hecho por el solo hecho de abrir la ventana de juego me aparece el error.

**Comment by eliasbruchfeld** [comment]
Hola! Han pasado 3 días ya y de verdad todavía no puedo resolver esto. Si alguien me puede ayudar lo agradecería bastante

**Comment by gatochico** [comment]
Hola! Una duda, a qué te refieres con "cerrar la ventana"? Cerrarla a mano o alguna otra cosa?

**Comment by eliasbruchfeld** [comment]
Cerrarla a mano o cerrarla con ventana.close().
Como cuando quiero pasar de la ventana de espera a la de juego y pongo ventana_espera.close() me pasa. Por ahora para seguir avanzando lo estoy haciendo con hide() y ahi no se cae pero se me generan despues otros errores mas menores con threads.

**Comment by gatochico** [comment]
Traté de replicar tu error y no lo pude replicar: ¿Puedes enviarme una lista de pasos a hacer para replicar el error?

Por otro lado, mencionas unos errores menores de threads. Creo que estos se deben a que estas llamando a los hide y show de las ventanas desde el controlador (fuera de su thread principal), esto se debería solucionar cambiando los hide y show directos por señales para que estos métodos (hide, show) se llamen desde las clases de las Ventanas correspondientes.

Prueba con mi sugerencia anterior y avísame como te va!
