### ISSUE TITLE
Logs me lagean el juego

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#1221]
Hola, es una duda corta. Estoy usando el módulo `beautifultable` para los logs,  y cada vez que ocurre algo en el servidor, se añade una fila al log principal y se imprime entero. El problema es que no me había fijado que el enunciado dice que se debe reflejar en el log si 

> El servidor mande o reciba algún otro tipo de mensaje a algún cliente. Debe indicar a qué cliente, el tamaño del mensaje y su contenido

Tengo muchos mensajes que se envían entre servidor y cliente, y me di cuenta que el juego se pone bastante más lento considerando que tiene que imprimir el log completo cada vez que se envía o recibe un mensaje. Da lo mismo y lo debería dejar así?

**Comment by gatochico** [comment]
Hola! Debido a que una tarea se ejecuta múltiples veces durante la corrección, si este lag del servidor es considerable, puede entorpecer dicha corrección (y conllevar un descuento, en el peor de los casos u.u). Por lo que te recomendaría fuertemente solucionar esto.

Buscando la doc de `beautifultable`, aparentemente no tiene forma de solo imprimir filas nuevas. Algunas ideas:
- Siguiendo con `beautifultable`, en vez de imprimir el log completo, genera una tabla nueva por cada log nuevo (así solo imprimes la info nueva en vez de el log completo). Debes preocuparte que la 'tabla' siga entendiendose al momento de imprimirse y no se desordene mucho el formato.

- Podrías investigar otras formas de hacer el log. En la issue de librerías hay algunas que tienen enfoque en formato para que imprimas.

Saludos y éxito!
