### ISSUE TITLE
Recorrección

### ISSUE THREAD

**Issue by pabloist** [IIC2233/syllabus#1221]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola buenas!

Mi problema es el siguiente, en la tarea 02 recibi descuento a criterio del ayudante con respecto al siguiente error QObject: Cannot create children for a parent that is in a different thread.
(Parent is Musica_thread(0x458be38), parent's thread is QThread(0x153d9a8), current thread is Musica_thread(0x458be38); el problema es que ese error a mi nunca me apareció y ahora que he vuelto a descargar y probar el programa tampoco me aparece mi duda es la siguiente: **como puedo probar el programa en otro ordenador para comprobar dicho error? existe algún interpretador online o algo?** o si alguno de ustedes pudiera probarlo :8 muchas gracias de antemano
el commit asociado a mi tarea 2 es 2551254

**Comment by gatochico** [comment]
Hola @pabloist !

Qué SO usas y cómo ejecutas tu código?

Probé tu código en Windows 10, desde la terminal y sí pude replicar el error que indicas arriba 😱

**Comment by pabloist** [comment]
Hola muchas gracias por la respuesta!

Lo he probado desde dos computadores diferentes ambos con Windows 10, mi personal (I7, 16 RAM) y otro antiguo (I3, 4 RAM); y en ninguno en tenido tal problema; me podrías decir en que momento te aparece dicho error?

**Comment by gatochico** [comment]
En cuanto se presiona 'comenzar ronda', esto aparece en la terminal:

**Comment by pabloist** [comment]
Muchas gracias por tu respuesta; estoy viendo que puede ser por el interprete porque yo uso Pycharm y ahora probé el codigo en VScode y si aparece dicho error.
Disculpa que te moleste pero el programa se te cae con el error? que estoy viendo la estabilidad y como arreglarlo :(

**Comment by gatochico** [comment]
Por lo que noté el programa no parece caer solo por ese error, aunque no pude probar mucho ya que se cae por otro error al apretar/capturar las flechas
