### ISSUE TITLE
Uso de sprites propios

### ISSUE THREAD

**Issue by matiasfernandez1** [IIC2233/syllabus#1222]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda sobre el uso de sprites propios en la tarea, como iconos o fondos. ¿Si los coloco en la carpeta sprites, debo no ignorar la carpeta sprites o es preferible colocar mis imagenes en otra carpeta distinta?
Además tengo otra duda, ¿es válido cambiar los sprites de materias primas por ejemplo, por otros que me parezcan que van más acorde con la estetica de mi programa, obviamente explicando en el readme cuál es cuál y manteniendo sus nombres y dimensiones, o estoy obligado a usar los que se dieron en el syllabus?

**Comment by Juampisaez** [comment]
Hola @matiasfernandez1 
Puedes crear sprites propios, por otro lado, estos sprites deben ir en una carpeta distinta a la que nosotros te entregamos (la carpeta que nosotros te entregamos debes ignorarla). En tanto a tu segunda pregunta, puedes hacerlo en la medida que lo expliques en tu readme.
Ahora como consejo, esto que estas trantando de hacer te recomendaria hacerlo cuando ya tengas la mayor parte implementada.

Quedo atento si te queda alguna duda :)

**Comment by matiasfernandez1** [comment]
Ah perfecto, muchas gracias
