### ISSUE TITLE
Manejo de envío de datos cuando no es el turno del cliente

### ISSUE THREAD

**Issue by vWing7** [IIC2233/syllabus#1222]
Hola, tengo un usuario que interactua de alguna manera con su cliente cuando no es su turno, sin considerar gritar dccuatro que siempre debe enviarse al servidor. Es necesario manejar esto de alguna forma específica? Me refiero a si es necesario que se informe al servidor que el cliente quiere mandar algo, pero el servidor no lo acepta; si el cliente puede saber que no es su turno y no enviar información buscando interactuar; o queda a mi criterio.

Gracias

**Comment by vicentevegaulloa** [comment]
Hola @vWing7 !

Si entiendo bien tu pregunta, tu deberías permitir que el usuario envíe información al cliente sólo cuando esté en su turno (exceptuando el caso de gritar DCCuatro). De esa forma no tendrás que enfrentarte a una situación en la que el cliente envíe información fuera de su turno que no sea gritar DCCuatro. De todas formas, si lo modelaste de manera que el jugador puede intentar hacer cosas como robar o botar cartas fuera de su turno, queda a tu criterio como hacer que el servidor rechace la solicitud del cliente.

Espero haber entendido tu pregunta y haberte ayudado 😄
