### ISSUE TITLE
Dos sends seguidos // mensajes pegados

### ISSUE THREAD

**Issue by stgosuarez** [IIC2233/syllabus#1223]
Hola!, 
Me pasa que cuando mando las cartas iniciales del servidor a los clientes, a un cliente le llegan los mensajes pegados (todas las cartas en un solo bytearray) pero a los demás les llegan separadas y en orden y las manejan bien.
Esto sólo le pasa al cliente que se unió último en la sala de espera. Pero no sé por qué.
Hay algún problema con enviar dos sends seguidos del servidor al socket sin una respuesta? O qué podría estar causando un error así?
Gracias de antemano

**Comment by fdoflorenzano** [comment]
Hola @stgosuarez,

Se repondió algo relacionado a este tema en la *issue* #1193, te recomiendo leerla y si te quedan dudas vuelves a comentar aquí.

Saludos.

**Comment by stgosuarez** [comment]
Perfecto, eso era la ctd recibida. Gracias!
