### ISSUE TITLE
Ventana final, botón volver, servidor

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#1224]
Hola!
Cuando se presiona el botón volver a la ventana de inicio, el servidor aún debiera estar disponible? o se asume que se vuelve a ejecutar?

**Comment by KnowYourselves** [comment]
Hola @Camila-sty!

La disponibilidad del servidor es independiente de los clientes. Es decir, si un cliente se sale, el servidor no tendría porque parar.

Éxito!

**Comment by Camila-sty** [comment]
Sí obvio, pero cuando termina la partida, y un jugador vuelve a la ventana de inicio, y vuelve a ingresar para comenzar otro juego, el servidor debe reiniciarse? o debe seguir el mismo de la partida anterior?, no sé si se entiende la duda?

**Comment by KnowYourselves** [comment]
Ahora comprendí tu pregunta. Si, se debiése empezar una nueva partida desde 0.
