### ISSUE TITLE
Duda Asignación nombres para la ventana de espera

### ISSUE THREAD

**Issue by AlonsoZamorano** [IIC2233/syllabus#1224]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda Asignación de nombres aleatorios

Hola buenas tardes, quería consultar si es que ¿puedo crear una asignación de nombres manual a traves de una pantalla de inicio que te dirija a la sala de espera?. Esto sería una asignación manual, pero en el enunciado se propone establecer una asignación aleatoria de nombre. Si es que esto es necesario, ¿puedo permitirles a los usuarios cambiar su nombre en la sala de espera?

**Comment by Juampisaez** [comment]
Hola @AlonsoZamorano 
En el enunciado dice "se abrirá una Sala de espera donde se pueden ver al resto de jugadores conectados, con un nombre único asignado por el servidor".  Ahora, puede ser que al hacer eso te estes complicando mucho (es una parte que no posee mucho puntaje). En caso de querer hacerlo de todas formas, te recomiendo igual revisar la distribucion de puntajes. Yo te recomiendo hacerlo de la forma que dice el enunciado, creo que es mas facil.

Quedo atento si tienes otra duda :)

**Comment by AlonsoZamorano** [comment]
Aahh perfecto!. Muchas gracias! Eso haré
