### ISSUE TITLE
Error serializacion

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#1225]
Hola alguien me podría ayudar con este error porfa. No entiendo que significa. Me pasa que le estoy pasando la info de los mazos desde el servidor a clientes y mi listen thread me lee bien solo la info de la primera carta. Revise mis contadores y no veo el error.
HELPP XFA, llevo pegado en lo mismo todo el dia :(.

![image](https://user-images.githubusercontent.com/62180259/86204532-b73b5080-bb35-11ea-87fc-500abf72aee0.png)

**Comment by matiasmasjuan** [comment]
Hola @dsepulveda3 !

Se me ocurren dos opciones de lo que puede estar ocasionando ese error.

1. Asegúrate de utilizar el mismo tipo de codificación para *strings*. Vale decir, podrías hacer uso del método ```encode('utf-8')``` y ```decode('utf-8')```.

2. Es posible que no estés utilizando el mismo protocolo de envío y el de recibimiento. Asegúrate de ver si es que en un determinado punto estás mandando la **misma** cantidad de *bytes* desde el servidor al cliente y en el **mismo** formato de **serialización**. En otras palabras, si estas enviando por ejemplo una *lista* que tiene un largo de *x* bytes, utilizando la serialización por ```json```, deberás primero hacer un ```json.dumps(lista)```  y luego un ```encode('utf-8')``` a esto último. Luego, el cliente deberá recibir **exactamente** la **misma** cantidad de *bytes* de la lista en su ```recv(x)```, y posteriormente utilizar el mecanismo de **deserialización** contraría. Vale decir, primero aplicar un ```decode('utf-8')``` y luego un ```json.loads()```.

Avísame si lo pudiste solucionar!

Mucho éxito con la tarea! 😄

**Comment by dsepulveda3** [comment]
Hola Matias! Probé y le estoy pasando la misma cantidad de bytes. También trate con el encode("utf-8") y con el decode("utf-8"), no es nada de lo que dices :/

![image](https://user-images.githubusercontent.com/62180259/86301691-7ba39380-bbd4-11ea-8dd1-e1d3ac0b6001.png)

**Comment by dsepulveda3** [comment]
Es muy raro porque como te digo, la info de la primera carta me la deserializa perfecto. El problema es de la segunda en adelante.

**Comment by dsepulveda3** [comment]
Ya lo solucione. Borre el código y escribí otro. Al parecer pasar demasiados bytes no es lo mejor. Estaba enviando info de mas de 100.000 bytes

**Comment by matiasmasjuan** [comment]
Si te sirve de ayuda, en los mismos contenidos de **Networking** se habla del uso de ```chunks``` para mandar un flujo constante y adecuado de *bytes* para que no pasen este tipo de problemas.

Mucho éxito con la tarea! 😄

**Comment by etgutierrez** [comment]
holaaa, tengo el mismo error y no se como solucionarlo, si estoy utilizando chunks :/ si me pudieras ayudar sería hermoso

**Comment by matiasmasjuan** [comment]
Hola @etgutierrez !

¿Estás serializando y deserializando de la misma forma? 🤔 
Revisa la ***Issue*** #1201 ya que se habla del mismo tema de manera más detallada.

Cualquier cosa me avisas! 😄

**Comment by etgutierrez** [comment]
Sii, el problema es que las cartas se mandan directamente como bytearray, en cambio el resto de informacion la mando por diccionarios(usando json y encode/decode), (para que sepa que es una carta mando justo antes un diccionario que lo indica) pero creo que el codigo se confunde y no lee bien las cartas, gracias, leeré esa issue

**Comment by etgutierrez** [comment]
PS: mis funciones para codificar la info de la carta (generando el bytearray) y de decodificar el mismo (por el cliente), están bien, las probé separadas del resto, el problema es entre que envío la info y que el cliente la recibe.

**Comment by matiasmasjuan** [comment]
Entiendo lo que dices. A lo que voy es que posiblemente el proceso de deserialización de información no se esté llevando de manera correcta. En particular, pienso en dos posibilidades.
1. Estas recibiendo más información de la que envías (o al revés). Un ejemplo es que debes asegurarte que la misma cantidad de bytes que realizas en tu ```send()``` debe ser igual al total de ```bytes``` recibidos por el ```recv()```.

2. Es posible que no estés almacenando la información que llega al cliente de manera correcta. Tal como dices, si mandas la imagen en un ```bytearray```, la idea es que en la recepción de información crees un ```bytearray()``` **vació** y que poco a poco (a través de ```chunks```) vayas añadiendo los ```bytes``` que llegan a este ```bytearray()```.

Luego de esto, puedes utilizar esta información para cargar la imagen en el **front-end**.

Avísame cómo te va! 😄

**Comment by etgutierrez** [comment]
Lo del punto 2 es exactamente lo que hice, y respecto al uno, el largo del mensaje es de 4 bytes, y dps hago recv(4), la vdd no se donde está el problema, gracias.

**Comment by matiasmasjuan** [comment]
Me refería particularmente al tema del ```recv()``` de los ```chunks``` mas que el del largo del mensaje. Si puedes subir lo que tienes al repositorio tal ves lo pueda revisar.

Saludos!

**Comment by etgutierrez** [comment]
esta subido, muchas gracias

**Comment by matiasmasjuan** [comment]
Estuve revisando por bastante tiempo tu código, y el error se produce por el mismo error que comenté al inicio de la ***Issue***. Esto se debe a que no estás enviando y recibiendo la misma información, ni deserializando de forma correcta.

En primer lugar, intentaría ordenar un poco más el código. Lo primero que recibes es el largo del mensaje, equivalente a 4 bytes-Luego, estas intentanto formar un ```bytearray``` con todo el resto del mensaje por chunks. Esto claramente va a producir un error, ya que no estas utilizando correctamente el protocolo. Para el caso de las cartas, primero recibes 4 bytes por el id, luego 4 bytes por el tipo y asi... En tu caso, estas intentando decodificar todo ese largo, id, etc, en el mismo bytearray, lo que claramente induciría a un error al momento de deserializar.

Por otra parte, intentaría **no utilizar** ```try /except``` al momento de identificar lo que se llega es una carta o no, ya que pueden haber más errores asociados que solamente el ```UnicodeDecodeError```. Para solucionarlo, intenta verificar si lo que estás enviando una carta o no, y posteriormente, haces los ```recv()``` correspondientes a los chunks que envias.

Por último, utilizaría el tema del envio de ```chunks``` solamente para la **carta**, y agregas los chunks de la carta en un bytearray. Lo que estas intentando hacer es juntar muchos bytes que no contienen solo la carta, sino que más datos, como id, color, etc. Lo que luego provoca errores en la decodificación.

Espero haberte ayudado, y recuerda hacer **prints()** constantes sobre lo que estas enviando para saber si efectivamente el mensaje está llegando en el orden correcto y en el tamaño correspondiente.

Saludos! 😄

**Comment by etgutierrez** [comment]
muchisimas gracias, lo intentare
