### ISSUE TITLE
Bug puntal, Servidor no recibe información

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#1225]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! tengo un bug puntal en mi código, no tengo idea de por que ocurre, en la sala estuve con 2 ayudantes y me recomendaron hacer un push, asique eso hago.
El problema ocurre que no le llega la información al servidor cuando el segundo jugador tira los dados, debuggeando puedo ver que el cliente procesa bien el apretar el dado y envía la información, sin embargo nunca la recibe el sv, y al debbuggear ambos juntos se me cae el programa.
Este problema No es urgente, pero ns si afectara a mis otros procesos ya que no llevo tanto. 
Para llegar hasta ahí tienen que correr server.py en la carpeta servidor y 2 main.py en la carpeta cliente, tirar los dados con la ventana que se puede e inmediatamente pasar de turno.
advertencia, el código tiene comentarios personales que se pueden considerar no apropiados uwu

**Comment by Zenos-Paradox** [comment]
Tengo un problema parecido; cuando pruebo mi código con un solo cliente funciona perfecto pero si pruebo con dos el servidor no parece recibir los mensajes de los jugadores (que si envían, se ve en la consola).

**Comment by sa-Appel** [comment]
@Zenos-Paradox intenta debbuggear para ver hasta donde llega tu server, quizás tienes mal seteado como mandar la info.

respectó a mi problema literal se arreglo solo lol, so procedo a cerrar la issue.
