### ISSUE TITLE
Carpeta Sprites

### ISSUE THREAD

**Issue by vobrador** [IIC2233/syllabus#1226]
Hola, no tengo muy claro donde debe ir la carpeta de sprites. Según lo que vimos en la sala de ayuda de la semana pasada el cliente puede tener Logo en su carpeta pero no se como sería esto para la entrega de la tarea. No debería agregarlo en el gitignore y debería separarlo de la carpeta de sprites? En otras palabras entiendo que solo servidor debería tener acceso a los sprites, como hago para pasarle el Logo a clientes (frontend)? (Lo utilizo en mi ventana de inicio y me gustaría tenerlo por temas estéticos :) ). 

Graciasss

**Comment by gatochico** [comment]
Hola!

La carpeta sprites en sí debería ir dentro del servidor, ya que es este el que manejará la mayoría de los sprites (en este caso, las cartas). Ahora, como se dice, el cliente puede tener el logo. Esto puedes hacerlo simplemente moviendo la imagen (no la carpeta completa de sprites!) a la carpeta del cliente y usándola directo desde ahí. Luego, puedes o subir el logo en el lado del cliente (solo el logo) junto con la tarea, o ignorarlo e indicar en tu README que el corrector debe mover el logo a esa ubicación. 

Saludos y espero haya quedado claro!

**Comment by vobrador** [comment]
Buenisima!! muchas graciasssss :)))
