### ISSUE TITLE
ConnectionAbortedError: [WinError 10053]

### ISSUE THREAD

**Issue by MaximilianoZapata** [IIC2233/syllabus#1226]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Contenido

Hola, cuando interactuo con un boton en la ventana de espera del cliente me aparece este error:
ConnectionAbortedError: [WinError 10053] Se ha anulado una conexi?n establecida por el software en su equipo host
y no logro encontrar el problema ni la solución en internet. ¿Qué problema puede ser?

![Captura de pantalla (28)](https://user-images.githubusercontent.com/69761579/101082942-07a65680-358b-11eb-9860-d218da345dea.png)

P.D : ya revise la *issue* https://github.com/IIC2233/syllabus/issues/1162 y creo que la solucion puede ser distinta a la planteada en esa *issue* pero no estoy seguro.

Se agardece la ayuda :D

**Comment by Juampisaez** [comment]
Hola @MaximilianoZapata 
En primer lugar quiero saber si realizaste lo mismo que en la issue 1162

Quedo atento :)

**Comment by MaximilianoZapata** [comment]
Te refieres a borrar el deamon = True  del thread escuchar_servidor ? si es eso lo hice, y me sigui tirando el problema y luego borre el daemon = True del thread de escuchar_cliente (pensando que podia ser esto) y tampoco se soluciono.
Pd : Me base en el codigo de la AF05 para hacer lo que llevo de la tarea y subi lo que llevo al repositorio.
Pd2: Gracias por tratar de ayudarme de verdad agradecido con el de arriba :D

**Comment by Juampisaez** [comment]
Ya, estuvo revisando tu codigo y logre identificar dos cosas.
1. En la linea 43 del clente.py colocar `self.socket_clente` cuando deberia ser `self.socket_cliente`
2. El metodo que recibe el mensaje debe ser distinto, una issue que te puede ayudar es esta https://github.com/IIC2233/syllabus/issues/1115. Creo que explica bien el metodo que recibe información.

Avisame si estas dos cosas logran solucionar el problema.

**Comment by MaximilianoZapata** [comment]
Acabo de ver lo que me dijiste y resulta que si era eso (ahora me siento tonto), ademas encontre ese mismo error en ```Servidor.py```
Revisare la issue https://github.com/IIC2233/syllabus/issues/1115 para poder mejorar mi tarea :D
De verdad muchas gracias, perdon que haya sido un error simple :c

**Comment by Juampisaez** [comment]
Tranqui, cuando di el ramo me pasaba lo mismo, es solo cosa de tiempo para desarrollar el ojo de halcon en el codigo. Avisame si pudiste arreglar el problema :)

**Comment by MaximilianoZapata** [comment]
ya pude arreglar el problema, muchas gracias :D
