### ISSUE TITLE
Problemas con la función recibir, a veces me corta los diccionarios

### ISSUE THREAD

**Issue by IgnaciaJ** [IIC2233/syllabus#1227]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Holaaa, en la función recibir, hay veces que la lectura me corta los diccionarios(por el manejo de bytes en esa parte y literal me lo corta, osea no recibe por ejemplo "}" por lo que queda como que ni siquiera tiene un tipo de texto definido) sin embargo me pasa con un mensaje en especifico ya que los otros me funcionan perfecto. Subi mi código al repositorio, sería de gran ayuda si alguien me puede guiar con eso, ya que estuve literalmente una hora con una ayudante hoy en la hora de consultas. Muchas gracias!!

**Comment by IgnaciaJ** [comment]
cuando me lo codifica le esta agregando cosas por ejemplo a veces sale "triigo" en vez de trigo

**Comment by rodrigobj99** [comment]
Hola @IgnaciaJ !

Estuve revisando tu código y luego de probar muchas cosas logre encontrar el problema, la variable `cantidad` en la función `enviar` en `servidor.py` estaba mal definida y producía que a veces el diccionario no llegara completo, cambiando `4 * len(mensaje_bytes)//60` por `4 * (contador_de_veces - 1)` el código funciona correctamente. En `cliente`.py no es necesaria la linea donde defines la variable `resto`, ya que no se utiliza y además genera un error. Realizando esas dos modificaciones no debieras tener problemas con el envío de información.

Por otro lado, note que si bien estas agregando los número de bloques, estas enviando todo el mensaje junto y no por bloques, además no estas rellenando con bytes 0 (b'\x00') sino que simplemente con 0 (lo cual también puede generar errores), por lo que te recomiendo volver a leer esa parte del enunciado, también puedes usar la issue #1040 para despejar tus dudas con respecto al envío de información.

Espero te sirva, cualquier cosa me avisas!

**Comment by IgnaciaJ** [comment]
muchas gracias!!
