### ISSUE TITLE
Agregar Label a Widget con Layout

### ISSUE THREAD

**Issue by Miguel-Cox** [IIC2233/syllabus#1227]
Hola!, mi problema es que tengo un Widget creado en Qtdesigner el cual posee un Layout interno (pertenece al mismo widget) y al momento de agregar un label no forma parte de este Layout (Al crear el label, hereda del widget). ¿Qué me aconsejarían hacer?

**Comment by EstefanyOlmos** [comment]
Hola, me parece que lo que hay que hacer es, despues de crear el label, añadirlo al layout con layout.addWidget(label) con el nombre que tiene el layout en qtdesigner. Yo hice eso y me funciona.

**Comment by fdoflorenzano** [comment]
Hola @Miguel-Cox,

Si entiendo bien, quieres crear un nuevo *label* y agregarlo a un *layout* previamente creado mediante QtDdesigner. Si es el caso, lo que indica @EstefanyOlmos debería ser la forma de hacerlo. Busca el nombre asignado al *layout* en QtDdesigner, y con ese puede acceder mediante código y ejecutar `self.nombre_layout.addWidget`.

Espero te ayude, nos avisas como te va.
Saludos.
