### ISSUE TITLE
robar cartas dccuatro

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2233/syllabus#1228]
Hola! si alguien grita dccuatro se pueden robar las cartas automáticamente al que tenga que robar?

**Comment by vicentevegaulloa** [comment]
Hola @mariovaldesa!

No puedes robar auomáticamente por el jugador, ya que de acuerdo al enunciado, "El juego nunca robará una carta del mazo automáticamente por un jugador", esto aplica incluso en el caso de que lo único que pueda hacer sea robar cartas.
