### ISSUE TITLE
Empate carretera mas larga

### ISSUE THREAD

**Issue by syprent** [IIC2233/syllabus#1228]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Al calcular la **carretera mas larga, que ocurre si hay empate entre uno o mas jugadores**? Por ejemplo si un jugador posee 5 y otro jugador construye su 5ta carretera ¿Se le da el título y puntuación extra a ambos? El enunciado solo dice que se le quitarán los 2 puntos extra si ese récord de carretera es superado

**Comment by rodrigobj99** [comment]
Hola @syprent !
Con respecto a tu pregunta esto no puede pasar ya que el logro de carretera más larga solo lo puede tener un jugador, por lo tanto al empatar la carretera mas larga no pasa nada. La única forma de obtener los 2 puntos extra es superando a la carretera mas larga actual y no igualandola.

Espero te sirva. Saludos!
