### ISSUE TITLE
Dimesiones ventana en parametros.json 

### ISSUE THREAD

**Issue by vobrador** [IIC2233/syllabus#1229]
Holaa :)) Es necesario poner los valores de las dimensiones de las ventanas o objetos dentro de la interfaz en parametros.json? (es decir, todos los valores que estan en el .setGeometry(100, 200, 300, 300) o .move(100, 200) o alguna otra de este tipo).

Asimismo ¿alguno de los valores a continuación debería ir como parámetro?
1. lista[0]
2. pop(0)
3. valores de slicing, tipo byte[4:8]
4. el int o el número de bytes de (1).to_bytes(4, byteorder="big")
5. booleanos (True o False)

Perdón que lo pregunte asi, pero quería saber de forma específica pero no me ha quedado claro de veces pasadas que he preguntado. Agradecería mucho una respuesta de este sí y este no :) Graciasss

**Comment by vicentevegaulloa** [comment]
Hola @vobrador!

Respecto a esta pregunta:

> Es necesario poner los valores de las dimensiones de las ventanas o objetos dentro de la interfaz en parametros.json?

Puedes hacerlo si lo deseas, pero como lo especifica el enunciado queda a tu criterio si lo añades o no en los parametros.

Respecto a  tu última pregunta:

> ¿alguno de los valores a continuación debería ir como parámetro? ...

Esto depende absolutamente del contexto de tu programa. Por ejemplo, si el índice de tu lista representa la cantidad de clientes que pueden jugar, esto si debería ir como parámetro por ser algo que vas a querer editar en el futuro sin tener que "meter mano en el código", y además porque se te pide explícitamente en el enunciado. 

Espero haber entendido tu duda y haberte ayudado 😄

**Comment by vobrador** [comment]
Yaaa!!! Muchisimas gracias, me quedo clarisimoo! :)))
