### ISSUE TITLE
Bifurcación de carretera para conteo de más larga 

### ISSUE THREAD

**Issue by JoMarchant** [IIC2233/syllabus#1229]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Contando el largo de las carreteras a veces hay bifurcaciones.

**¿Se deben contar por separado ambas posibilidades?, o ¿Se suman todas las que estén conectadas pese a la bifurcación?**

**Comment by EduardoIllanes** [comment]
Hola @JoMarchant! Se debe contar por separado y ver que lado de la bifurcación tiene mas carreteras, ya que se le otorga al jugador que obtenga la mayo cantidad de carreteras **consecutivas** . Espero que se entienda, saludos! 😄

**Comment by JoMarchant** [comment]
Programando me surgieron dudas de si mí código está contando bien:
![image](https://user-images.githubusercontent.com/69648244/101167597-eab86480-3618-11eb-9ff1-9f9397c7de92.png)
**Ahí me esta contando 9 de la siguiente manera:**
![image](https://user-images.githubusercontent.com/69648244/101167873-539fdc80-3619-11eb-9b7a-f51d51beeb90.png)
**¿O debiese ser así?:**
![image](https://user-images.githubusercontent.com/69648244/101167992-8518a800-3619-11eb-846c-6375bf2de335.png)

**Comment by EduardoIllanes** [comment]
La que esta contando 9 es la correcta. Saludos 😄
