### ISSUE TITLE
Error test_09 para función cambiar_planos

### ISSUE THREAD

**Issue by Yagosepu04** [IIC2233/Syllabus#123]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Para el test_09 me aparece el error a continuación, pero he probado con diferentes archivos y he visualizado las nuevas redes creadas con "imprimir_red" de dcciudades y la función está retornando True luego de actualizar las redes y estaciones como corresponde. Me sale que dentro del test_09, está mal el test_0 y test_2:

FAIL: test_0 (tests_publicos.test_09_cambiar_planos.TestCambiarPlanos.test_0)

        Verificar lectura y modificación del nuevo plano.

----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Usuario\Desktop\Carpeta wena\REPOSITORIO\Yagosepu04-iic2233-2024-1\Tareas\T1\tests_publicos\test_09_cambiar_planos.py", line 26, in test_0
    self.assertEqual(red.cambiar_planos("test_1.txt"), True)
AssertionError: False != True
____________________________________________________________________
FAIL: test_2 (tests_publicos.test_09_cambiar_planos.TestCambiarPlanos.test_2)

        Verificar lectura y modificación del nuevo plano.

----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Usuario\Desktop\Carpeta wena\REPOSITORIO\Yagosepu04-iic2233-2024-1\Tareas\T1\tests_publicos\test_09_cambiar_planos.py", line 69, in test_2
    self.assertEqual(red.cambiar_planos("test_2.txt"), True)
AssertionError: False != True

Gracias de antemano :)

**Comment by SSParzival** [comment]
Hola buenas, considera que los archivos están en la carpeta `data` para la implementación del método, recuerda también que es necesario ejecutar los tests desde la carpeta `T1` o desde `test_publicos` para su comprobación individual.

**Comment by SSParzival** [comment]
Si estás ejecutando el test de manera individual, puede que no tengas la carpeta `data` dentro de la carpeta `tests_publicos`, lo cual provocaría que la ruta no sea encontrada y el método nunca pueda retornar `True`.

**Comment by Yagosepu04** [comment]
Hola! Pucha es que he intentado eso y también con todos los tests y aún no me funciona :/

**Comment by SSParzival** [comment]
Al menos en base al último commit de tu repositorio privado, el error parece estar en que no accedes a la carpeta `data` en el método, y, por tanto, no se puede encontrar el archivo de extensión `.txt`.

**Comment by Yagosepu04** [comment]
Ahí pude! Muchas gracias ;)
