### ISSUE TITLE
Archimago y Habilidad Maestro?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#123]
Si el archimago ataca uno de mis planetas cuya raza es la de archimago, que se debe hacer? Reducir la vida a la mitad?

**Comment by IchottMano** [comment]
@naquiroz Hola!
Ya que en el enunciado sólo se habla de que la habilidad del maestro reduce a la mitad el ejército enemigo (tal y como lo dicen tambien en la issue #77 ), no se especifica que es lo que pasa en el caso que se active la habilidad contra el archimago.
Por lo tanto, esto se deja a tu criterio como implementarlo.
Saludos!
