### ISSUE TITLE
Duda base de datos meteorología

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2233/Syllabus#123]
¿Qué se espera que se haga en pronósticos meteorológicos que tienen una fecha de inicio después de la fecha de termino ( como en el caso del pronostico de ID 31 del archivo meteorologia.csv)?

**Comment by akaminetzkyp** [comment]
Yo creo que es un error.

**Comment by stephichau** [comment]
Hola @frvalenzuela! 

Puedes asumir que esos incendios nunca existieron :)

**Comment by frvalenzuela** [comment]
Gracias @stephichau !
