### ISSUE TITLE
Tarea 1 testeo funcion reemplazar vs test_todos

### ISSUE THREAD

**Issue by benjasaldias** [IIC2233/Syllabus#123]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

En mi función "reemplazar" **los tests particulares de la funcion (usando test_tablero_reemplazar.py) todo sale correcto, pero al usar test_todos.py todos salen fallidos.** El error ocurre al acceder a una lista que creé, con el error [IndexError: list index out of range], lo que no ocurre con los otros tests... No adjunto foto de mi código para evitar plagio.

**¿A qué testeo debiera creerle?** Muchas gracias por su tiempo de antemano :)

**Comment by Hernan4444** [comment]
Hola @benjasaldias 

Revisé el código que tienes ahora en tu repositorio y todo me funcionó 🤔  si me meto al directorio "tests" y ejecuto "test_tablero_reemplazar.py" me sale todo correcto, si luego hago `cd ..` para estar en tu carpeta de la T1 y hago `python3 tests_todos.py` tambien me corren todos los de reemplazar. 

¿Puede ser que el código que probé ahora no es el mismo cuando hiciste esta issue?

Quedamos atentos,
Saludos!

**Comment by benjasaldias** [comment]
@Hernan4444 Hola profe!! Siii, logré arreglarlo. El problema estaba en cómo leía el archivo .txt. Gracias!! :)
