### ISSUE TITLE
Tarea 0 , Tamaño mapa

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#123]
Puedo obligar al jugador que el mapa sea de NxN, por temas de practicalidad y que se vea mas bonito? , puedo ponerle un max de grid al mapa?

**Comment by JuaniAndres** [comment]
Hola @sa-Appel 
Efectivamente el tablero tiene que ser de NxM osea que en algunos casos puede ser cuadrado como rectangular el tablero. Respecto a tu segunda pregunta los valores que pueden tomar tanto N como M tienen que pertenecer al rango [3,15] esto significa que el tablero más grande que se podrá formar es uno de 15x15 y el más chico uno de 3x3.
Espero haber aclarado tu duda

**Comment by tvallotton** [comment]
Hola, como yo lo tengo diseñado hasta ahora le doy 3 opciones al jugador: chico, medio y grande. donde el chico es de 5x5 y el grande es de 10x10. Esta bien si lo dejo así, o tengo que darle más libertad al usuario al momento de elegir el tamaño del mapa?

**Comment by sa-Appel** [comment]
@tvallotton no soy ayudante, pero tiene que ser de NxM en donde ambos están en el conjunto [3,15],esto acorde al pdf, supongo que como lo tienes tu vas a tener puntaje parcial

**Comment by JuaniAndres** [comment]
Hola @tvallotton 
Confirmando lo que dijo @sa-Appel en el enunciado dentro de la sección de crear partida dice:

> El programa debe permitir iniciar nuevas partidas. Al momento de iniciar una, se debe preguntar por el
tamaño que tendrá el tablero de ambos participantes. Para esto el jugador deberá ingresar dos enteros N y M
pertenecientes al rango [3,15] que representarán el número de filas y columnas del mapa, respectivamente.

Entonces no estarías cumpliendo a la totalidad con este punto, te recomiendo ajustar tu código para que obtengas todos los puntos de esa parte.
Éxito programando :D
