### ISSUE TITLE
Duda sobre uso de espacio " " al crear un usuario

### ISSUE THREAD

**Issue by RodrigoFritis** [IIC2233/syllabus#123]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, al momento de registrar un usuario, es permitido usar un espacio en el nombre nuevo? Por ejemplo si quiero registrar a un usuario llamado "soy rodrigo". Lo pregunto porque yo lo puse como una restricción dado que el espacio a veces da problemas al leer un archivo y cargarlo al flujo del programa, y quería saber si sacar o dejar dicha restricción. 
Gracias

**Comment by IgnaciaJ** [comment]
Hola @RodrigoFritis! En el enunciado sale que las únicas restricciones del input son las siguientes:
1. que tenga entre 3 y 15 caracteres 
2. que no posea comas
Por lo que tu programa debe estar preparado para recibir nombres de usuarios que posean un espacio(es decir borrar la restricción)
Éxito en tu tarea!!

**Comment by RodrigoFritis** [comment]
No sabia que no había que cerrar la issue lo siento ! Gracias por la respuesta @IgnaciaJ
