### ISSUE TITLE
Duda uso de **kwargs

### ISSUE THREAD

**Issue by JosefaATP** [IIC2233/Syllabus#123]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

No me queda muy claro como se usa **kwargs, en una función.
En este caso especificamente para la función de estudios_con_genero en la actividad 1.

Gracias!!

**Comment by 3rdPix** [comment]
Hola @JosefaATP!

Básicamente, `**kwargs` es un diccionario con sus propios pares llave:valor. Este diccionario se construye a partir de los argumentos entregados en la llamada a una función o método.

La principal diferencia entre exigir un diccionario como argumento e indicar `**kwargs` es la **obligatoreidad** de la existencia de tales argumentos. En el primer caso, necesito pasarle únicamente un objeto diccionario, en cambio, en el segundo le entrego *los mismísimos pares de valores llave:valor* (si, ellos mismos) Por ejemplo:

```python

def funcion_sin_kwargs(argumento1: int, argumento2: dict) -> None:
    # hacer cosas

def funcion_con_kwargs(argumento1: int, **kwargs) -> None:
    # hacer cosas

funcion_sin_kwargs(1, {'cosa': 1, 'otra_cosa': 2})
funcion_con_kwargs(1, cosa=1, otra_cosa=2)
```
En el primero hay un objeto `dict` que se le está pasando como argumento a la `funcion_sin_kwargs`, en el segundo, el diccionario lo construye internamente Python **a partir de los pares llave:valor** que son los argumentos.

La segunda forma de abordarlo permite mayor flexibilidad con el manejo de argumentos porque dentro de la función puedo aislar la lectura de estos valores, y solo utilizar los que me interesan mientras que los demás (spoiler) puedo pasárselos a otra función para que haga sus propias cosas. El valor de `**kwargs` lo verán con más detalle en los contenidos que vienen, asi que por esta actividad puedes quedarte con que `**estudios` es un diccionario cuyos valores son objetos del tipo `list`.

Como siempre, es fuertemente recomendado leer la [documentación oficial](https://docs.python.org/3/library/inspect.html#inspect.BoundArguments.kwargs) para ver en detalle el comportamiento de las funcionalidades del lenguaje.

Espero te haya servido, cualquier otra duda no temas en preguntar :D

**Comment by JosefaATP** [comment]
Me quedo más claro!

Gracias!! 😁
