### ISSUE TITLE
Como puedo usar una variable en una modularización que existe en el main.py pero no en otro archivque es donde lo uso en uo.py na función.?

### ISSUE THREAD

**Issue by nlewin99** [IIC2233/syllabus#123]
Tengo un main.py donde corro todo el DCCahuin sin embargo algunas funciones las modulariza y en ellas uso algunas variables que se van creando a medida que corre el main.py, como puedo entrelazarlas?
Muchas gracias!

**Comment by gatochico** [comment]
Hola! 

Como estas trabajando con un `main.py` compuesto de varias funciones, la forma de trabajar con dichas variables sería entregandolas a las funciones relevantes respectivas, y si dichas variables se crean dentro de la función, retornandolas una vez finalizada. Esto es debido a que la alternativa de utilizar **variables globales** (tener variables que pueden ser accedidas desde cualquier _scope_ sin importar donde fueron creadas) **es una mala práctica penalizada**.

Con lo que llevas de tu programa, trata de hacer un analisis de **qué variables son absolutamente necesarias de mantener a lo largo del código** o cuales pueden permanecer dentro de la función solamente ya que no tienen uso fuera de ellas. De la misma forma, analiza que variables del **main.py son absolutamente necesarias para poder ejecutar alguna función** y entrégaselas.

Espero haberte podido ayudar, sino vuelve a comentar aquí!
