### ISSUE TITLE
Duda sobre lo que ocurre cuando falta dinero al comprar un bebestible y al apostar cero de dinero.

### ISSUE THREAD

**Issue by NicolasOlmosQuiroga** [IIC2233/Syllabus#123]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tenia una duda sobre que pasa cuando al usuario le falta dinero para comprar un bebestible, puesto que en la siguiente imagen nos dicen que se deberia volver a desplegar la carta:

![Imagen bebestibles1](https://user-images.githubusercontent.com/101432060/163223358-824be4c0-54b7-49e3-a7f6-2a51eefce400.png)

Pero en la accion de jugador aparece que se deberia volver al menu principal:

![Imagen bebestibles2](https://user-images.githubusercontent.com/101432060/163223525-eee528c3-6525-4781-8aed-2a0f2317277a.png)

Entonces no estoy muy seguro de que hacer, ¿queda a elección mia nomas?

Aparte, tenia la duda de que si esta permitido apostar 0 de dinero en los juegos, en el archivo de juegos.csv en el juego de cara o sello esta permitido apostar 0, pero no se si eso tendria sentido o no, o sea, aun tacaño al apostar 0 puede recibir dinero gratis al ganar e incluso una bebida gratis a costa de energia y los efectos de perder/ganar.

Eso, ¡muchas gracias!

**Comment by jtvaldivia** [comment]
Hola, 
primero en caso de no tener el dinero necesario se debe volver a desplegar la carta de bebestibles. Y si se puede apostar 0 debido que no se especifica en el enunciado lo contrario, te recomiendo igualmente que lo coloques en el readme.md como un supuesto explicando porque lo hiciste.
