### ISSUE TITLE
contrincantes

### ISSUE THREAD

**Issue by bgfeuereisen** [IIC2233/syllabus#123]
Cada pista viene con una cantidad predeterminada de rivales, sin embargo en Flujo de carrera aparece que del archivo contrincantes se deberá elegir aleatoriamente la cantidad de rivales que tendrá cada pista. Por lo que mi pregunta es ¿utilizamos los contrincantes que vienen en cada pista o debemos escoger otros? 
gracias

**Comment by gatochico** [comment]
Hola! 

Nos faltó agregar el parámetro con el número de rivales por carrera :scream: . Deberás agregar un parámetro `NUMERO_CONTRINCANTES` a `parametros.py` donde se indique el número de contrincantes por carrera, que será siempre un entero positivo. A partir de eso:

- En el caso de que la cantidad de contrincantes de la pista sea **menor o igual** al parámetro, usas **todos** los contrincantes que posee la pista.
- En el caso de que la cantidad de contrincantes de la pista sea **mayor** al parámetro, eliges aleatoriamente de entre los contrincantes una **muestra del tamaño de dicho parámetro** (Ej: La lista de contrincantes tiene 5, pero el parámetro tiene valor 3, se elegirán 3 pilotos al azar de los 5 como contrincantes).

Disculpa por la tardanza y éxito en la tarea!

**Comment by bgfeuereisen** [comment]
Gracias por la respuesta anterior. 
¿La cantidad de contrincantes que defino en parametros.py es a mi antojo? ¿Es fijo para cada partida, o debe ir variando?

**Comment by gatochico** [comment]
Puedes ponerle el valor que quieras para probar tu programa, siempre y cuando recuerdes que como ayudantes podemos cambiar dicho valor (por uno válido, por supuesto!) y tu programa no se debería caer.

También puedes asumir que dicho valor será el mismo para cada partida.

Saludos!

**Comment by bgfeuereisen** [comment]
Muchas gracias!!

**Comment by burgosibarra** [comment]
Hola! Una consulta en cuanto a los contrincantes, vi que en el archivo vehículos un contrincante tiene varios vehículos.
Mi pregunta es: al empezar una carrera, cómo elegir el vehículo para cada contrincante?
Desde ya, muchas gracias

**Comment by gatochico** [comment]
La forma en que se eligen los vehículos para tu contrincante queda a tu libre criterio (Recuerda escribir en el README tu decisión!). Éxito!
