### ISSUE TITLE
Duda sobre programon llega al nivel 100

### ISSUE THREAD

**Issue by bernirosas** [IIC2233/Syllabus#123]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [V] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! En el enunciado, en la parte de programones sale: "Si el nivel llega a 100, la experiencia quedará en 0 y el entrenamiento ya no hará efecto". Mi duda es si cuando llega al 100 hay que aumentar los parámetros de vida, ataque, ... o no. Claramente si llegamos al nivel 101 no se aumentan pero no estoy tan segura de que pasa en el 100.
Saludos, gracias!

**Comment by Emiliax16** [comment]
Hola @bernirosas ! en el momento que el nivel llega a 100, ya no se pueden aumentar más las capacidades del programón. Por lo tanto: programón está en nivel 99 y su experiencia llega a >= 100, entonces nivel pasa a 100 y experiencia se vuelve 0, sin tener un efecto en las capacidades, ya que **el entrenamiento deja de tener efecto al llegar a nivel 100**. ESpero haya quedado claro, saludos!
