### ISSUE TITLE
Problema en civilizaciones.csv

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2233/syllabus#123]
Hola, en el archivo civilizaciones.csv hay un tag que está diferente de como está en el enunciado.
En el enunciado dice ~"poder_tecnologico"~ "puntos_de_tecnologia" y en el archivo dice ~"poder_tecnológico"~ "puntos_de_tecnología". Esto es importante porque resta funcionalidades al archivo, como implementar named tuples, y aparte es la unica tilde en todos los archivos. Quiero saber, esto está bien así o es un error?

EDIT: Cambie .py por .csv, como deberia ser
Edit 2: Cambie "poder_tecnologico" por "puntos_de_tecnologia"

**Comment by iqacevedo** [comment]
Hola @JJJGGGG 
Efectivamente es un error en el header del csv. Siempre nos regiremos por lo que dice el enunciado, ya actualizamos el archivo quitandole la tilde. 

De todas maneras, como fue un error nuestro, consideraremos correctas las tareas que lean la columna **poder_tecnológico**  y tambien las que lean **poder_tecnologico**.

¡ Saludos y exito en la tarea !

**Comment by RositaMunoz** [comment]
Una duda, con poder_tecnológico, se refieren a puntos_de_tecnología? porque en ninguna parte del archivo civilizaciones.csv está el header poder_tecnologico :worried:

**Comment by JJJGGGG** [comment]
Hola, quería informar que también hay un error de este tipo en el archivo edificios.csv: 'dccowork' está escrito como DCCowork. Gracias

**Comment by iqacevedo** [comment]
@RositaMunoz si es **puntos_de_tecnologia**.

**Comment by iqacevedo** [comment]
@JJJGGGG tenías razón, cambie los archivos según lo que decía en el enunciado.

**Comment by JJJGGGG** [comment]
Pero las variables van con guiones, no? Esto es importante para hacer bien los programas

**Comment by iqacevedo** [comment]
@JJJGGGG las variables son como se indica en el enunciado, pero tendremos en consideración al revisar que nos equivocamos en los archivos .csv con el nombre de algunas variables. En el caso de `centro_urbano `efectivamente era sin `_`, por lo que quedo como `centro urbano`.
