### ISSUE TITLE
Error al escuchar cliente

### ISSUE THREAD

**Issue by djrojas1** [IIC2233/syllabus#1230]
Hola, el programa me arroja el siguiente error al momento de conectar el cliente con el servidor
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\djroj\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\djroj\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\djroj\Desktop\servidor\servidor.py", line 46, in listen_client_thread
    bytes_largo = skt.recv(4)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto

**Comment by vicentevegaulloa** [comment]
Hola! Puedes hacer un push para revisar tu código y resolver el problema de manera más rapida?

**Comment by djrojas1** [comment]
Voy!!, gracias

**Comment by djrojas1** [comment]
Listoo

**Comment by vicentevegaulloa** [comment]
Estoy revisando tu código, espero encontrar el bug. Te puedo asegurar que el proble,a es con tu cliente y no tu servidor.

Esta issue #1093 habla sobre el mismo error. Podrías revisarla en una de esas encunetras el bug antes que yo.

**Comment by djrojas1** [comment]
lo reviso, te aviso si lo encuentro

**Comment by vicentevegaulloa** [comment]
Siguiendo lo indicado en la issue que te mencioné, probé cambiando tu listen(self). En la parte del thread cambié el deamon a False y ya no se caía con ese error pero se pegaba en la ventana. Prueba con eso, espero te funcione!

**Comment by djrojas1** [comment]
gracias!
