### ISSUE TITLE
Python dice Application not Responding

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#1231]
Hola! Haciendo correr el programa me aparece Application not Responding cuando abre python, la duda que tengo es ¿Por qué pasa? o ¿Cómo puedo debug esto?
Gracias!

**Comment by vicentevegaulloa** [comment]
Hola @CataSudo!

Estaba leyendo, y esto podría estar relacionado por como implementas el cliente y su interfaz. Si no los tienes correctamente separados  y conectandolos por señales, es muy probable que te ocurra este error. Revisa eso y si no lo es, podrías hacer un push para revisar tu código?

**Comment by CataSudo** [comment]
Hola! Hice un push! Toda ayuda sirve, muchas gracias!

**Comment by vicentevegaulloa** [comment]
Estuve probando tu código y no obtengo ese error pero el programa tampoco funciona como debería. Sin embargo, creo haber encontrado el problema y es muy similar a lo que te indicaba previamente. El cliente no está correctamente separado de la interfaz, esta última contiene al cliente como atributo. Esto evita que tus señales funcionen de la manera que se espera, por lo que te recomiendo fuertemente que separes el cliente de la interfaz y los comuniques sólo mediante señales.
