### ISSUE TITLE
Notificacion paso de Turno

### ISSUE THREAD

**Issue by pedroriosg** [IIC2233/syllabus#1231]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!
En el enunciado en el ítem 4.2.5, sale que si aún nadie ha ganado, se debe avisar a todos los jugadores que el turno del jugador actual ha acabado. Es suficiente con que se actualice un Label en la interfaz, indicando de quién es el turno (como sale en el enunciado)? O debemos hacer un pop - up o algo por el estilo.

Muchas gracias

**Comment by rodrigobj99** [comment]
Hola @pedroriosg !
Mientras se le avise a todos los jugadores que el turno actual ha acabado y que el siguiente jugador debe comenzar su turno, estará correcto. El método que uses para esto queda a tu criterio. Por otro lado el pop up o ventana adicional solo es necesario en caso de que un jugador haya ganado.

Espero te sirva. Saludos!
