### ISSUE TITLE
Exception: UnicodeEncodeError 

### ISSUE THREAD

**Issue by agustin18638937** [IIC2233/syllabus#1232]
![Captura](https://user-images.githubusercontent.com/62082728/86283703-77b14a80-bbaf-11ea-908f-62e84bbafd7c.JPG)
hola, al ejecutar el programa del cliente me arroja esta exception, siendo que he codificado todo en utf-8 (excepto la imagen que se decodificada con base64), he revisado mi código muchas veces y no tengo nada que se decodifique en ascii como para que aparezca eso. Además, me lanza esta exception antes de ocupar las funciones que reciben bytes, es decir, sin que tenga que decodificar algo
Alguna idea de como poder solucionarlo? 
gracias de antemano.

**Comment by RenatoVWS** [comment]
Holaa no soy ayudante, pero tuve un problema muy parecido. Me paso que me lanzaba el mismo error cuando decodificaba las imagenes y era porque no estaba recibiendo bien un archivo grande (en los contenidos sale que se van recibiendo por chunks). Al final lo cambié y me resultó. Ojalá te pueda servir!

**Comment by agustin18638937** [comment]
supuse eso, así que quite las funciones que emiten y reciben cartas del servidor y cliente respectivamente (con un # para que quedaran como notes), y aun así, teniendo el mismo código que antes (cuando si funcionaba) me aparece el mismo error:(

**Comment by fdoflorenzano** [comment]
Hola @agustin18638937,

¿Ese error te empezó a aparecer de la nada? ¿Habías podido ejecutar tu programa antes sin el error? ¿Cómo estás ejecutando tus programas? (Desde donde, como: editor de texto, consola, etc..., y de ser el caso cúal) ¿Podrías subir tus avances a tu repositorio para revisarlo?

Saludos.

**Comment by agustin18638937** [comment]
si, de hecho saque las funciones que había puesto desde la ultima vez que funciono bien (con un hashtag antes), aun así no corre. probé corriendo el archivo de cliente (backend) sin el main y sin correr el servidor antes, aun así me arroja la exception.
Estoy usando VSCode para editar pero ejecuto los programas con la cmd (en windows). Acabo de subirlos, gracias de antemano!!. Saludos

**Comment by fdoflorenzano** [comment]
Hola @agustin18638937,

Es el uso de `ñ` y un problema de como Python ejecuta y lee el contenido del módulo.  Evita usarlo simplemente.

Saludos.

**Comment by agustin18638937** [comment]
muchas gracias!! ahí me funciono, no me había dado cuenta
