### ISSUE TITLE
Problema con Popout

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#1233]
Actualmente me encuentro haciendo el PopOut encargado de mostrar si el usuario gano o perdio, ya que mi programa ya reconoce cuando sucede esto. Pero al momento de hacerlo (utilizando un QDialog), me salio el siguiente error:

     - QObject::setParent: Cannot set parent, new parent is in a different thread

ademas de que me indico que el QDialog fue cerrado para evitar un cracheo.

Por esto, procedi a hacer otro QDialog en QDesigner, para ademas tenerlo de manera mas personalizada. El problema esque no me abre, nunca se muestra, incluso ocupando .exec_() y .show().

Pero esto solo me sucede con este QDialog, pues ocupo otro de estos en el momento de seleccionar un color, al usar la carta cambio de color, y este funciona a la perfeccion.

gracias de antemano

pd: subi todos mis archivos por si son utiles.

**Comment by fdoflorenzano** [comment]
Hola @felipehen,

Hice un par de pruebas con el código de tu repositorio y efectivamente pasaba lo que indicas. Revisé, y la diferencia notoria era quien llamaba la aparición del *dialog*. Para el cambio de color era la respuesta a una señal (`mousePressEvent`) mientras que el otro era directamente un *thread* de *back-end* llamando al método `ganador`. Para hacerlo similar, cree una señal que al emitirse llame al método `ganador` y reemplacé la llamada directa por emisión de señal, además de agregar el `_exec` de *dialog*, y me apareció la ventana buscada.

Nuevamente, la solución para ser señales. Avísame si te funciona esto.

Saludos.

**Comment by felipehen** [comment]
Perfecto, voy a intentar, muchas gracias
