### ISSUE TITLE
Duda con Paths

### ISSUE THREAD

**Issue by bastian-perez** [IIC2233/syllabus#1233]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! 
No encontré en el enunciado (quiźas busqué mal y si es así lo siento mucho :(  ) algo que diga que los paths deben estar contenidos dentro del archivo parametros.json, si no es obligacion puedo dejarlos expresados directamente en el código ??
muchas gracias!

**Comment by lucasprato** [comment]
Hola @bastian-perez, si bien no se menciona directamente te recomiendo fuertemente hacerlo. No es buena práctica hardcorear parámetros dentro del código y esa es la razón por la cual lo hemos pedido en las tareas anteriores.
Éxito!

**Comment by YehudaGurovich** [comment]
@lucasprato Si para abrir el .json necesitamos el path de donde viene entonces no es posible colocar el path dentro de este.
