### ISSUE TITLE
Uso de ID's en los logs

### ISSUE THREAD

**Issue by totaurt** [IIC2233/syllabus#1234]
Hola! Tengo una duda en el caso que el servidor deba registrar un log al momento de que un cliente se conecte o se desconecte. Como su conexión ocurre antes de que ingresen un nombre, supongo que hay que asignarles un identificador cualquiera para hacer el log, como un número. En la tabla de ejemplo, los datos bajo el título "Cliente" siempre son nombres, por lo que no estoy segura si esto es válido.  
Por favor si me pueden aclarar esta parte, graciass.

**Comment by lily416** [comment]
Es válido usar ID u otro tipo de identificador para diferenciar los usuario. 😉 

Si usas IDs y nombres, podrías mantener ambos como una información constante, por ejemplo:
| ID | Cliente | Evento | Detalles |
|-|-|-|-|
| 1 | | Iniciando conexión | |
| 1 | | Nombre de usuario | Pepito |
| 1 | Pepito | Desconexión | |

No es obligatorio que lo hagas de esta forma, pero es una buena forma de mostrar el nombre y el ID del usuario. 🤓 


Saludos y éxito en la tarea 👋🃏

**Comment by totaurt** [comment]
Hola! Perdón lo tarde, pero mi duda específicamente tenía que ver con que al momento de conectarse aún no les atribuyo ningún ID como 1, 2, 3 o 4 que son los que ocupo para los jugadores, puesto que se pueden desconectar y no ingresar a la sala de espera para jugar. Lo que hago es usar su address para identificarlos anónimamente hasta que se registren. Así siempre son distintos a cualquier otro cliente que se conecte. ¿Está bien?

**Comment by lily416** [comment]
Puedes usarlo, pero debes tener ojo con que el _address_ sea un identificador único, así evitas que se sobrescriban clientes si es que comparte la misma _address_.

Saludos y éxito con lo que queda de la tarea 👋☃️
