### ISSUE TITLE
Duda Carreteras

### ISSUE THREAD

**Issue by bastian-perez** [IIC2233/syllabus#1234]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! 
Para poner las imagenes de los caminos en el mapa, decidí optar por la opción de poner solo una orientación de caminos, es decir no estarán todos alieneados con el grafo, hay descuento por esto ? o un poco de recolección del puntaje por ponerlos ? o está incorrecto hacerlo así ?

**Comment by matiasmasjuan** [comment]
Hola @bastian-perez !

¿A que te refieres con poner solo la orientación de caminos? Lo **importante** es que el camino sea fácil de ver y que el corrector sepa que en una arista específica hay una arista o no y de qué color. A fin de cuentas, no es relevante si está 100% alineada como dices. Lo importante es que se vea que en una arista hay un camino si corresponde.

Saludos! :smile:
