### ISSUE TITLE
Duda con carta color

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#1235]
Hola. Al momento de escoger un color queda a mi criterio como avisarle a los otros jugadores que color fue escogido? Yo elegí poner el color actual como sale en las figuras del enunciado pero no agregué un pop up señalando a los otros jugadores el color escogido. Con eso basta?

**Comment by fdoflorenzano** [comment]
Hola, esto ya fue preguntado en #1206. Recuerda buscar tus dudas previamente.
