### ISSUE TITLE
Cartas de desarrollo

### ISSUE THREAD

**Issue by bastian-perez** [IIC2233/syllabus#1235]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! 
La funcion "sacar_cartas" retorna una tupla con la información de la carta, pero para el caso de la carta de puntos de victoria, esta puede ser carta tipo1 (la verde) y tipo2 (la azul), esta información extra del color de la carta influye para efectos del juego ? puede ser que en la ventana de juego se encuentre solo un tipo de esta carta? es necesario diferenciar durante el juego el tipo de carta que salió ?
muchas gracias!

**Comment by rodrigobj99** [comment]
Hola @bastian-perez !
En el caso de la carta puntos de victoria esta puede ser verde o azul según lo que retorne la función `sacar_cartas`, la idea es que usando esta función tú determines si debes mostrar la carta azul o la carta verde al usuario y la implementes de esa forma. Frente a si el tipo de carta de victoria influye para efectos del juego la respuesta es no, sea verde o azul la carta tiene el mismo efecto que es +1 punto de victoria para el jugador.

Espero haber aclarado tu duda. Saludos!

**Comment by dedmu5** [comment]
> Hola @bastian-perez !
> En el caso de la carta puntos de victoria esta puede ser verde o azul según lo que retorne la función `sacar_cartas`, la idea es que usando esta función tú determines si debes mostrar la carta azul o la carta verde al usuario y la implementes de esa forma. Frente a si el tipo de carta de victoria influye para efectos del juego la respuesta es no, sea verde o azul la carta tiene el mismo efecto que es +1 punto de victoria para el jugador.
> 
> Espero haber aclarado tu duda. Saludos!

necesariamente hay que decirle al usuario si salio una carta monopolio o no?

**Comment by rodrigobj99** [comment]
Hola @dedmu5 !
El enunciado indica que al comprar una carta de desarrollo esta es devuelta al usuario y una vez que esta hace efecto (inmediatamente) la carta debe desaparecer del mazo de jugador, por lo tanto debe mostrarse ya que sino no puede desaparecer.

Espero haber aclarado tu duda. Saludos!

**Comment by dedmu5** [comment]
@rodrigobj99 

>  la carta debe desaparecer del mazo de jugador, por lo tanto debe mostrarse ya que sino no puede desaparecer.

No entendí esta parte. ¿Por qué no puede simplemente desaparecer?

**Comment by rodrigobj99** [comment]
Si deben desaparecer, luego de ser recibidas por el usuario y de haber hecho efecto (el cual debe ser inmediato).

Espero haber aclarado tu duda, saludos!
