### ISSUE TITLE
Envío de cartas con mas información

### ISSUE THREAD

**Issue by iankreisberguc** [IIC2233/syllabus#1236]
Hola, me queda una duda con respecto al envío de cartas, ¿puedo(respetando lo pedido) agregar otro "pedazo" con otro identificador (ej: 4) que me indique lo que voy a hacer con esa carta? o la idea es que esa información vaya aparte en otro envío??

**Comment by matiasmasjuan** [comment]
Hola @iankreisberguc !

Puedes revisar las siguientes **Issues**: #1069 , #1142, #1138, #1104, ya que en todas ellas se habla respecto tu misma duda.

**PD**: si puedes, pero debes especificar en tu *README*  cómo haces esta pequeña "modificación" sobre el envío de cartas.

Mucho éxito con la tarea! 😄
