### ISSUE TITLE
 100 caracteres por línea en JSON

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1237]
Para la corrección esta regla también aplica al archivo parametros.json es que con los paths que ingresen me exceden los 100 caracteres

**Comment by fdoflorenzano** [comment]
Hola @RonaldoSosa,

Esas reglas son para módulos de Python, no archivos de datos como lo es JSON.

Saludos.

**Comment by RonaldoSosa** [comment]
Entendido gracias por la aclaración!
