### ISSUE TITLE
Más de una persona con una carta

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1238]
Hola ! Cuando una grita DCCuatro y más de una persona posee una carta el grito le debería afectar a todas las personas ?
Leí en la issue #1030  pero no me quedo del todo claro

**Comment by fdoflorenzano** [comment]
Hola @RonaldoSosa,

Te pido hagas esta pregunta en la *issue* #1030 si trata sobre exactamente lo mismo. Así todas las dudas relacionadas se condensan ahí.

Saludos.
