### ISSUE TITLE
Main se caé al instanciar clase client

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#1238]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
En el main de prrograma del cliente instanció la clase del Cliente que contiene las funcionalidades para comunicarse con el server. Y también instanció las clases de las ventana de juego y sala espera. Sin embargo, al primero instanciar la clase Client el programa no sigue corriendo por el main por lo que no se alcanzan a instanciar las ventana. En el caso contrario, si instanció las clases de ventanas y luego la del client. Una vez que el programa llega a la Client el programa se cae.

**Comment by Mjtala** [comment]
Hola @enriquemolinare ! Puedes subir tu código porfa

**Comment by enriquemolinare** [comment]
sii, ya está subido

**Comment by Mjtala** [comment]
Hola @enriquemolinare! Primero, recuerda utilizar "host": "localhost" en tus archivos parametros.json.
Segundo, lo que hice fue 
1. Instancié la clase SalaEspera en Client (en def init)
2. LLamé a self.sala.show() en tu función listen en client.py y funcionó de manera correcta tu código
Revísalo y avísame si te funciona :)
