### ISSUE TITLE
Input generador_de_cartas.py

### ISSUE THREAD

**Issue by n4chin** [IIC2233/syllabus#1239]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola!!
No entiendo cuál es el input que se refiere en generador_de_cartas, la idea no es sacar simplemente una carta al azar cuando alguien pide sacar una carta de desarrollo? o todos los usuarios tienen un mazo de CANTIDAD_DE_CARTAS_MAZO cartas, y tienen que sacar cartas de ahí?

**Comment by Juampisaez** [comment]
Hola @n4chin
Para aclarar un poco mas este archivo, el generador de cartas lo que hace es retornar x (input) cantidad de cartas en el formato mostrado en el enunciado. La idea de este archivo es que te retorne la cantidad de cartas que quieres de forma aleatoria, de alguna forma simula un mazo, pero no tiene una cantidad limite de cartas. Sabiendo esto, respondo a tus preguntas:
1. Puede ser que desees sacar una carta a la vez, por lo que tu input siempre será 1, como también puedes decidir cuantas cartas comprar de una sola vez, esto depende de como lo implementes.
2. Como ya dije antes, es solo una funcion que retorna cartas aleatorias (no es precisamente un mazo).

Espero responder a tus dudas, cualquier cosa quedo atento :)
