### ISSUE TITLE
hacer una función al cerrar ventana

### ISSUE THREAD

**Issue by CamilaArgomedo** [IIC2233/syllabus#1239]
Existe alguna forma de que cuando el cliente cierre la ventana yo pueda asociar una función a eso? estuve buscando pero no encontré nada y necesito borrar los datos del jugador cuando este cierra la ventana saliendo de la sala de espera ( o no es necesario hacer eso?)

**Comment by vicentevegaulloa** [comment]
Hola @CamilaArgomedo!

Cuando un jugador se desconecta, ocurre un error en el thread donde el servidor escucha a ese cliente. Si manejas el error con `try/except`, podrías llamar a un método una vez que se desconecte el cliente. Creo que el servidor de la [AF06](https://github.com/IIC2233/syllabus/blob/master/Actividades/AF06/servidor/servidor.py) será de gran ayuda.

Espero haberte ayudado! 😃

**Comment by CamilaArgomedo** [comment]
hola! muchas gracias por la ayuda ¿cuando entra al except, no puedo desde ahí mandar un mensaje al cliente? me tira error haciendo eso ¿quizás debería manejarlo solo desde el servidor?

**Comment by vicentevegaulloa** [comment]
Una vez que cae en el except, es porque perdiste la conexión entre cliente y servidor, por lo que **no puedes**, enviar mas mensajes entre ellos. Como propones, deberías manejarlo solo desde el servidor.

**Comment by CamilaArgomedo** [comment]
oka! muchas gracias:)
