### ISSUE TITLE
Duda respecto a id's fijos/variables

### ISSUE THREAD

**Issue by nbnavarro** [IIC2233/syllabus#124]
En el archivo civilizaciones.csv se le asigna una id a cada civilización. 

Dicho id, será fijo? es decir, siempre Cobreloa tendrá el id=0 en los archivos que se usen? 
o podría cambiar y que, por ejemplo, la tarea se pruebe con un archivo en el que Cobreloa tenga id=1? 

Si es que cambian, los id's seguirán siendo del 0 al 2?

**Comment by Arcoirisky** [comment]
Hola!

Tu pregunta está respondida en la issue #88 :D 
A la próxima te recomiendo utilizar el buscador de las Issues con palabras clave de tu pregunta :D en este caso sería “id”
