### ISSUE TITLE
Significado de "hardcodeado"

### ISSUE THREAD

**Issue by allullk** [IIC2233/syllabus#124]
Hola 😄

¿Que significa la palabra _hardcodeado_? Esta aparece al final de la página 12 del enunciado de la tarea 01.

Gracias de antemano.

**Comment by DCCollao** [comment]
Hardcodeado se refiere a un valor que quita versatilidad a tu código. En este caso, un hardcodeo sería un parámetro que utilices directamente en tu ``main.py``, pudiendo haberlo importado desde ``parametros.py``.
 Una de las facilidades que otorga utilizar un archivo de parámetros es la sencilla modificación del valor incluido dentro del archivo, en lugar de modificar todas las líneas donde fue hardcodeado en tu main.

**Comment by allullk** [comment]
Muchas gracias DCCollao!!
