### ISSUE TITLE
Multiples Import

### ISSUE THREAD

**Issue by IchottMano** [IIC2233/Syllabus#124]
Buenos dias,
Tengo la duda de que si tengo 3 módulos, "A, B y C", si importo el módulo C en el archivo A y luego importo el A al B, es necesario importar también el C? 
Muchas gracias

**Comment by fdominguezclaro** [comment]
Si es que en el módulo B no vas a usar ninguna función o clase contenida en A, entonces no es necesario. 
En el caso contrario, si tienes que importarlo. 

Puedes probarlo por tu cuenta. 

Suerte!

**Comment by DquezadaO** [comment]
Hola, respecto a eso, si tengo 3 módulos "A, B y C" e importo en el B:

from decimal import Decimal

Después que tan legal es en la A decir:

from B import algunas_cosas, Decimal

**Comment by GustavPrudencio** [comment]
La idea de separar las clases por módulos es literalmente esa, que estas funcionen como piezas independientes, es preferible que el import sea desde el archivo original.
Saludos
