### ISSUE TITLE
Escribir un archivo

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#124]
Hola!
Puedo agregar datos de esta forma: ... ?

archivo = open('usuarios.csv','a')
#esto es de intro a la progra, y me funciona muy bien
print('string que quiero agregar', file=archivo) 
archivo.close()

En la materia de los "paths" sale esta forma de abrir y cerrar un archivo, pero recomiendan escribir mediante:

archivo.write('string que quiero agregar'+'\n')

Pero cuando voy a agregar el primer dato al archivo, este se salta una linea de código, pero al siguiente dato empieza a agregarse bien(sin saltos de linea vacia). Entonces no me funciona bien. o quizás lo estoy agregando mal, tampoco se cómo arreglarlo.

Otra consulta.
En la materia de los "paths" que ustedes nos subieron, sale como leer y escribir archivos de la forma "rt" y "wt".

Pero se supone (enseñado en intro) que al utilizar la "w", si el archivo no existe se crea, pero si el archivo ya existe, se borra y se empieza a crear de nuevo, entonces quería saber si yo podía utilizar la letra "a" (enseñada en intro) que es cuando un ya archivo existe pero se pueden agregar datos sin eliminar la información que ya tenía el archivo. Pregunto esto porque no indican este método en los "paths".

 Gracias.

**Comment by jeschuwirth** [comment]
Hola @Camila-sty,

En cuanto a tu primera pregunta, no hay problema con hacer uso de open() con el modo "a". Recomendamos utilizar el modo "w" y escribir todo de nuevo ya que suele ser más sencillo de entender.

El error de la primera línea vacía cuando haces uso de .write() debe ser por tu código, por lo que es difícil ayudarte a distancia. Si realmente necesitas ayuda puedes subir tu código a github y poner un comentario en esta issue para que lo revise :)

La última pregunta creo que va a lo mismo que la primera, no hay problema con usar:
`
 with open(path, "a"):
`
Si te quedan dudas o necesitas más ayuda sigue comentando en esta issue :D

Suerte!

**Comment by Camila-sty** [comment]
Ok, pero puedo usar "print('string que quiero agregar', file=archivo)" para escribir en el archivo?

**Comment by jeschuwirth** [comment]
También se puede !

Por lo general todo lo que sea **built-in** de python está permitido, a excepción de lo que diga la issue #4 (como por ejemplo exec()).
