### ISSUE TITLE
diagrama de clases

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#124]
El diagrama de clases tiene que estar en algun formato especifico?
puede ser una foto? por ejemplo

**Comment by rmsolari** [comment]
Hola, en pdf

**Comment by stephichau** [comment]
@jorgeriesco ojo que se debe entender el diagrama :)

**Comment by Arcoirisky** [comment]
¿Es necesario que sea como el visto en clases o con que explique bien el programa basta?

**Comment by rpalmaotero** [comment]
@Arcoirisky mientras uses la misma simbología y estructura no hay problema.
