### ISSUE TITLE
Duda ejercicio propuesto 1.1 de la semana 6

### ISSUE THREAD

**Issue by Crisax234** [IIC2233/Syllabus#124]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, no logro entender como tengo que instanciar iterables primos, ya que en el ejemplo de hacer una estructura iterable, los datos son instancias de nodos pero que están 'sobrepuestas' por decirlo de alguna manera y luego ese objeto se pasa al el iterador. Mi duda va en como hago un objeto para los números primos para poder iterarlo de la misma forma, ya que si hago una lista con los números primos del 1 al 25 se perdería el propósito del ejercicio o no?

**Comment by folivaresdc** [comment]
Hola @Crisax234, Como tu bien dices al hacer una lista pierde el sentido el ejercicio porque esta ya es un iterable. Para este ejercicio tienes que tu hacer el iterable y el iterador.

Para la clase IterablePrimos esta debe tener definida el método ```__iter__``` y devolver un iterador.

Ahora, creo que tu pregunta es cómo hacer la clase Iterador. Para esto deber recibir la clase iterable para saber cuál es el inicio y fin del rango donde buscar primos. después tienes que implementar el método ```__next__``` que vaya retornando los números que cumplen con el requisito. Puedes ayudarte creando un atributo en la clase iteradora que guarde en que número vas dentro del rango. también debes recordar implementar el método ```__iter__``` de la clase iteradora.

Espero que te haya servido, si tienes más dudas puedes responder este comentario.

**Comment by Crisax234** [comment]
Ya lo pude resolver, muchas gracias!
