### ISSUE TITLE
Tarea 1 solo con clases?

### ISSUE THREAD

**Issue by franco-anfossi** [IIC2233/Syllabus#124]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Quería saber si la tarea 1 se debe hacer completamente con clases o pueden haber algunas funciones para correrla y hacer funcionar algunas cosas?

**Comment by 3rdPix** [comment]
El enunciado dice que está enfocado en Clases, pero que no restringe lo demás; en particular, menciona que **debes** incluir al menos 1 vez, cada uno de los casos vistos en clase (polimorfismo, herencia, etc). Si tu programa ya cumple con tener de todo eso, y necesitas agregarle algo, no es necesario que sea una clase obligatoriamente.

**Comment by Emiliax16** [comment]
@franco-anfossi @3rdPix  complemento lo anterior con lo siguiente: si revisan la distribución de puntajes, se evalua que todas las entidades mencionadas en la sección **entidades** estén modeladas de forma correcta, lo que implica la utilización de clases, dado que existen diferentes atributos y métodos descritos en el enunciado. Por otro lado, puedes usar todas las funciones que veas necesarias y que se encarguen del flujo de tu tarea. Lo importante es que si el enunciado dice que la entidad `Colegio` tiene el método `asignar_sala` , efectivamente `asignar_sala` sea un método de la clase `Colegio`, y no una función externa a la clase. Coméntame si aclaré tu duda.  Saludos!
