### ISSUE TITLE
Duda usuarios en grupo y archivo contactos.csv

### ISSUE THREAD

**Issue by CarlosValleA** [IIC2233/syllabus#124]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!! Cuando un usuario agrega un contacto, el archivo contactos.csv se debe modificar para indicar la relación entre ambos usuarios. ¿Este comportamiento se debe repetir al crear grupos?

Por ejemplo si el user1 crea el grupo con user2 y user3, deberia actualizar contactos.csv con las relaciones:
```
user1, user2  
user2, user3
user3, user1
```

Gracias!

**Comment by RafaelEdwards** [comment]
Holaa!

Los usuarios que están en un mismo grupo no necesariamente deben tenerse guardados en sus contactos, por lo que al crear un grupo no deberías crear esa relación. 

Espero haberte ayudado y suerte con tu tarea :).
