### ISSUE TITLE
Plantar cultivos

### ISSUE THREAD

**Issue by MTGG123** [IIC2233/Syllabus#124]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Una pregunta sobre el enunciado de la tarea. A la hora de plantar un cultivo, debemos asumir que se nos entregará un numero entre el 0 y el 9 o debemos tenerlo en consideración y evitar que se pueda plantar un cultivo de código 10 (por ejemplo)?

**Comment by FernandoTFH** [comment]
Si bien el enunciado dice que debes asumir que el usuario ingresa correctamente los datos, también dice que los menús sean a prueba de errores, entonces si recibes un input malo tu programa no puede fallar o hacer algo que no estuvo programado a hacer, como tu ejemplo de 10, en donde no deberían existir cultivos de código 10 cuando se definió que los cultivos son del 0 al 9. 
Por la contracción entre el "asumir que el usuario ingresa correctamente los datos" y "menús sean a prueba de errores" yo creo que es mejor que hagas algo para evitar recibir input malos y lo indiques en el README.
