### ISSUE TITLE
class Tablero

### ISSUE THREAD

**Issue by fbehncke** [IIC2233/Syllabus#124]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el archivo tablero.py en el __init__ de Tablero, dice self.dimensiones = [len(tablero), len(tablero[0])], no entiendo porqué esto correspondería a las filas y columnas. 

Además, no entiendo por qué dice que tablero es una lista de Lists si en los ejemplos de tableros nunca está ese formato y no se aplica nunca en el init.

Muchas gracias desde ya por su tiempo:)

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Mcroquevielle** [comment]
Hola!! Primero, para self.dimensiones, si te fijas el primer elemento (len(tablero)) te dice la cantidad de elementos que tiene tablero, por lo que va a ser la cantidad de filas. Despúes, para len(tablero[0])) lo que hace es tomar la primera fila (podrías hacerlo con cualquier fila en verdad) y ve la cantidad de elementos que tiene esta (es decir, cantidad de columnas).
Es decir, en el siguiente ejemplo:
[["V4", "--"],
["--", "R3"],
["H1", "--""]]
len(tablero) nos va a devolver 3 (cantidad de filas) ya que la lista tiene 3 elementos y len(tablero[0]) nos va a devolver 2 (ya que la primera fila tiene 2 elementos).

Después, no entiendo a que se refiere tu segunda pregunta, ya que si te fijas en los ejemplos siempre los tableros son listas de listas.

Avísame si te queda claro (:

**Comment by fbehncke** [comment]
Hola si entiendo a lo que te refieres, pero no entiendo entonces si por ejemplo el tablero test_1,2,2,R2,--,PP,PP no será dado como atributo en este formato sino así: ["R2","--","PP","PP"]. Gracias desde ya:)

**Comment by Hernan4444** [comment]
Hola,

Cada vez que instanciemos tu `Tablero` lo hacemos entregando una lista de listas de string. Por ejemplo:

```python
tablero_str = [["V2", "--", "PP", "--", "H2"], ["H3", "--", "--", "PP", "R11"]]
instancia = Tablero(tablero_str)
```

Ahora bien, en tablero.txt, la línea está en otro formato, `test_1,2,2,R2,--,PP,PP` y el desafío es que en el método "reemplazar", tengas que abrir ese archivo, buscar el tablero correspondiente  y transformarlo en la lista de listas que corresponde. Esto es porque en todos los demás métodos, usarás tu `self.tablero` que estará en el formato de "listas de listas".  

En conclusión, no usaremos algo como: `["R2","--","PP","PP"]`, es decir, una lista de string, sino siempre será una lista de listas cuando instanciemos tu tablero, y en `reemplazar`, la mision es transformar el string en una lista de listas.

Esperamos haber logrado resolver tu duda, sino no dudes en preguntar c:
Saludosヾ(＾-＾)ノ

**Comment by fbehncke** [comment]
Holaa, entiendo pero tengo una ultima duda (perdón) en el menú de acciones cuando se selecciona la opción 1 de mostrar tablero, ¿basta con hacer uso de la función imprimir tablero o primero debo dejar el atributo tablero en el formato adecuado a partir de los ejemplos del archivo tableros.txt (similar a lo que se hace en el metodo remplazar).

Graciassss

**Comment by Mcroquevielle** [comment]
Hola! No te preocupes jajaja
Si te fijas, la función imprimir_tablero recibe como argumento un tablero en el formato de lista, por lo que debes asegurarte de que lo que le entregas esté en ese formato.
