### ISSUE TITLE
Ignorar DCCiudad en el commit causaría que el código no funcionase al revisarlo

### ISSUE THREAD

**Issue by FeZega** [IIC2233/Syllabus#124]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado, se menciona que, en el commit, se deben ignorar los archivos que no se deben modificar. Entre estos está dcciudad.pyc.
Como nuestros archivos dependen directamente de él, si el señor DCCiudad no está en nuestra carpeta del repositorio al momento de correr el código, este se caerá.
¿Es necesario subir dcciudad.pyc a mi repositorio? Si este no está, ¿los ayudantes se encargarán de ponerlo? 

Gracias. ( •̀ ω •́ )✧

**Comment by pedrozavalat** [comment]
Hola @FeZega 😄 !

No es necesario subir `dcciudad.pyc` a tu repositorio. Al momento de corregir, nos encargaremos de importar cualquier archivo o carpeta que debería ser ignorado según el enunciado. Recuerda que debes hacer un uso correcto de `.gitignore`, ya que si se suben archivos que no deberían subirse, se aplicará un descuento en tu nota.

Espero haber aclarado tu duda. ¡Éxito en tu tarea! 🚀
