### ISSUE TITLE
AYUDA, no puedo hacer git push

### ISSUE THREAD

**Issue by K4rl4Munoz** [IIC2233/Syllabus#124]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

No puedo realizar git push, primero me daba un error donde no me dejaba subir nada, ya que decia que tenia otra terminal abierta, y ahora me da este error :cccccc

![error git push](https://user-images.githubusercontent.com/101335687/163261948-fab7426a-ecff-4a9d-a604-e7fb5b929663.png)

**Comment by Franbelen** [comment]
(soy estudiante no ayudante), pero creo que eso no es un error, solo dice que no hay nada para hacer commit, si pones git status deberia salir todo lo trackeado en verde que significa que todo lo que has cambiado ya se ha subido, ya que al agregar todo ( con git add .)  no se agrego nada nuevo, es decir todos tus cambios ya estaban subidos , si quieres estar segura que se subieron tus ultimos cambios puedes revisar en tu repositorio en git hub
