### ISSUE TITLE
Mi fontend parece no recibir una señal

### ISSUE THREAD

**Issue by difischer** [IIC2233/syllabus#1240]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!, tengo un problema conectando las señales, no se por qué una en el frontend pareciera  no recibir nada.
Tengo todas las señales conectadas en main de la forma
``` backend.senal_a_mandar.connect(frontend.senal_a_recibir)```
Pero esta en específico no hace nada en el lado del frontend.
Dentro del backend tengo:
```self.senal_a_mandar.emit()```
(Y confirmé que la función que contiene el emit, está funcionado.)

Dentro del frontend la tengo conectada como todas las otras
```self.senal_a_recibir.connect(self.funcion_que_quiero_usar)```

No se si la señal no se estará emitiendo o si el frontend no está recibiendo, pero no entiendo por que esa señal en específico no funciona :(

**Comment by difischer** [comment]
Revisé conectando la señal dentro del mismo backend a un print y si funcionaba, pero haciendo lo mismo en main o en el frontend no pasa nada, es como si no estuviera saliendo del backend

**Comment by difischer** [comment]
Ya lo solucioné, pero me sigue quedando la duda, de por qué pasará que solo algunas señales no se mandan :(

**Comment by aaossa** [comment]
Hola @difischer , lo único que se me ocurre que podría explicarlo es que te faltaba heredar de `QObject` en alguna clase que contenía una `pyqtsignal` 🤔 Otra opción, que podría explicar el que no funcionara "a través de módulos" es que te faltara conectar una señal, que la conexión no estuviera correcta o que sobreescribieras de alguna manera la señal. Que bueno que te funcione bien ahora eso sí, pero ten ojo con las declaraciones de las señales y sus conexiones 🤓 Si algo te vuelve a fallar, pregunta por acá mismo no más 🙌
