### ISSUE TITLE
Recibir información de carta

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2233/syllabus#1241]
Hola! Tengo una duda con recibir la información de una carta desde el servidor al cliente. No entiendo si debo mandar todo el bytearray de la carta al cliente, y luego recibirlo y "separarlo" según el identificador 1, 2 y 3, para luego manejar el color, tipo y path como corresponde. 
O si se debe mandar primero todo lo que corresponda al identificador 1, luego todo lo del 2 y finalmente del 3. 
O si se debe mandar todo, y luego recibir la información de a poco?
Ojalá se haya entendido jaja 😄

**Comment by szabala** [comment]
Hola! La idea es que el servidor mande el _bytearray_ completo y luego el cliente lo vaya recibiendo de a poco (bloque por bloque por ejemplo). Fíjate que siempre sabes de cuantos _bytes_ es cada bloque (los primeros 2 son de 4 _bytes_ y el tercero se indica en el bloque anterior) , entonces puedes utilizar esto para ir recibiendo toda la información.

Ojo que para enviar la imagen de la carta NO debes enviar el path de esta, sino la imagen misma serializada (recuerda que el cliente no tiene acceso a las imagenes).

Espero haber aclarado tu duda!
