### ISSUE TITLE
Al correr distintos clientes, algunos se quedan pegados 

### ISSUE THREAD

**Issue by camisiilva** [IIC2233/syllabus#1241]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! estaba corriendo mi código y tengo el problema de que al actualizar los labels que indican los jugadores se me queda pegada una ventana de juego y no se actualiza. Corrí el mismo código en otro computador Windows (tengo mac), el cual no es mío, y funcionó sin errores. ¿A qué se deberá y qué puedo hacer?

**Comment by aaossa** [comment]
Hola @camisiilva , ¿pudiste solucionar esto? La verdad suena bien extraño, si la interfaz se bloquea normalmente es porque el *thread* principal está ocupado cuando debería estar libre para atender los eventos de la interfaz. El hecho de que en sistemas operativos funcione de manera distinta me parece raro 🤔 ¿Cómo ejecutaste el código en cada sistema operativo? Si utilizaste tu interfaz de desarrollo, prueba ejecutándolo directamente desde la consola. Si esto no funciona, ¿podrías subir tu código a tu repositorio? Avísame cómo te va 🙌 ¡Éxito con la tarea ✨!

**Comment by camisiilva** [comment]
Hola! en ambos computadores lo hice a través de la consola y ya subí mi tarea :) en verdad no se a qué se debe el error 😢

**Comment by aaossa** [comment]
Hola @camisiilva , la verdad no estoy seguro de qué podría estarlo provocando porque estoy desde Windows y me funciona bien tu código. Algunas cosas que cambian levemente entre los sistemas operativos son el manejo de rutas porque uno usa "/" y el otro "\" (si usas `os.path.join` esto no es problema). Algo que podría recomendarte para intentar pillar el error es comentar los `try`/`except` que tengas, por si alguna excepción está siendo capturada y haciendo que entres en un *loop* infinito en alguna parte. Avísame si encuentras el posible error (tanto la solución como si la consola te muestra un mensaje con la excepción) o tienes alguna idea de qué podría provocarlo. ¡Mucho ánimo y éxito con la tarea 🙌!
