### ISSUE TITLE
error al recibir el largo del mensaje en servidor

### ISSUE THREAD

**Issue by feliperojas123** [IIC2233/syllabus#1242]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

al recibir algunas veces los mensajes del cliente. el servidor me arroja este error BrokenPipeError: [Errno 32] Broken pipe, la verdad nose es. la cosa es que me funciona el leer el mensaje pero nose porque aveces pasa este error... esta subida mi tarea con el codigo correspondiente. graciaaaas

**Comment by feliperojas123** [comment]
he visto que es cuando termino a los clientes y los vuelvo a poner, ahi es cuando me arroja

**Comment by rodrigobj99** [comment]
Hola @feliperojas123 !
Estuve revisando tu código y me di cuenta de que esto probablemente ocurre debido a que no estas capturando el fin de la conexión `(ConnectionResetError)` al escuchar a clientes, y por lo tanto nunca eliminas el socket del cliente que se desconecta, produciendo que cuando se intente enviar el mensaje a ese socket obtengas el error `BrokenPipeError: [Errno 32]`.

Espero te sirva, cualquier cosa me avisas!
