### ISSUE TITLE
Envio de datos

### ISSUE THREAD

**Issue by FelipeSrojas96** [IIC2233/syllabus#1242]
Hola, 

Respecto al envio de cartas se que hay que enviarlas mediante la forma pedida. Pero que pasa si tengo que enviar por ejemplo un string de texto simple y lo codifico solo con encode?

En este caso es mejor crear un protocolo de comunicacion unico y distinguir en base a los primeros bytes por ejemplo?

**Comment by vicentevegaulloa** [comment]
Hola @FelipeSrojas96 !

En el enunciado se indica que queda a tu criterio como implementar la comunicación para el envío de información de cosas que no sean cartas. Tal como dices, una buena forma de hacerlo es indicando en los primeros bytes el tipo de información que se va a recibir. Por otro lado, también podrías enviar un diccionario con una key que te permita ver que tipo de información estas recibiendo. En la issue #1069 se habla de algo similar, por si necesitas más información.

Espero haberte ayudado! 😄
