### ISSUE TITLE
Proble al abrir la interfaz (WARNING)

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#1243]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, al intentar abrir la sala de juego tal como lo hago con la sala de espera, me aparece el siguiente mensaje en mi terminal
<img width="943" alt="imagen" src="https://user-images.githubusercontent.com/53887845/101130499-57fcd300-35e2-11eb-861a-0c051d5595ab.png">

**Comment by Juampisaez** [comment]
Hola @Margarita-Paz 
Estuve estuve viendo tu codigo, y no me aparece el error que mencionas en la terminal. Por otro lado, cache que estas haciendo los show dentro del controlador, esto deberias hacerlo directamente en la clase de la ventana (tal vez por eso no te muestra la ventana). Esto recomiendo hacerlo con señales.

Quedo atento si funciona lo anterior :)

**Comment by Margarita-Paz** [comment]
Hola! al final era una señal que me faltaba emitir 😢 
Puse los show en funciones guiándome de la AF05
¿Está bien así?

**Comment by Juampisaez** [comment]
Mientras no te tire error, todo bien. Lo que te dije fue porque aveces pyqt se pone mañoso y no manda bien las señales. Pero si a ti te funciona, no te preocupes, igual seria bueno que comentaras esto en tu readme, para que el ayudante sepa como lo implementaste.
