### ISSUE TITLE
Conexión a servidor

### ISSUE THREAD

**Issue by nachobascar** [IIC2233/syllabus#1243]
Hola!!
Tengo una duda sobre la conexión al servidor. 
Mi programa está hecho de modo que cuando se abra la ventana inicial, el cliente no esté conectado al server, sino que intenta conectarse una vez que se coloque el nombre y se oprima entrar (Tengo señales hechas para mandar feedback de vuelta al cliente, como si el nombre es erroneo o si el server está apagado). Y una vez que sea válido el nombre se mantiene abierta la conexión con el servidor.
¿Está bien implementar la conexión al server de esta manera? Ya que en ninguna parte se restringe, pero escuché que podría tener problemas por eso.

**Comment by DCCollao** [comment]
Hola @nachobascar!

No hay problema con que lo implementes como explicaste, siempre y cuando respetes las condiciones pedidas para la sala de espera (nombres válidos, sin repetir, cantidad máxima de jugadores).
