### ISSUE TITLE
uso de Locks

### ISSUE THREAD

**Issue by Mendez69** [IIC2233/syllabus#1244]
Hola! no he implementado Locks en mi código, al momento de enviar la información entre servidor - clientes algunas cosas salen pero nunca llegan, y esto me pasa solo a veces. Se arreglaría poniendo Locks?, lo otro es que no veo dónde irían, como solo tengo dos threads (cliente y juego). Gracias!

**Comment by Camila-sty** [comment]
eso no serán los logs?

**Comment by fdoflorenzano** [comment]
Hola @Mendez69,

No me queda clara tu duda, pero me suena a algo similar a lo que se respondió en la *issue*  #1193. Si no es eso, intenta explicar un poco tu problema.

Saludos.

**Comment by Mendez69** [comment]
> Hola @Mendez69,
> 
> No me queda clara tu duda, pero me suena a algo similar a lo que se respondió en la _issue_ #1193. Si no es eso, intenta explicar un poco tu problema.

> 
> Saludos.



> Hola @Mendez69,
> 
> No me queda clara tu duda, pero me suena a algo similar a lo que se respondió en la _issue_ #1193. Si no es eso, intenta explicar un poco tu problema.
> 
> Saludos.



> Hola @Mendez69,
> 
> No me queda clara tu duda, pero me suena a algo similar a lo que se respondió en la _issue_ #1193. Si no es eso, intenta explicar un poco tu problema.
> 
> Saludos.

Ahi me funcionó! Gracias!!!

**Comment by Mendez69** [comment]
> Hola @Mendez69,
> 
> No me queda clara tu duda, pero me suena a algo similar a lo que se respondió en la _issue_ #1193. Si no es eso, intenta explicar un poco tu problema.
> 
> Saludos.

Ahi me funcionó! Gracias!
