### ISSUE TITLE
Uso de "delays" en envío de información.

### ISSUE THREAD

**Issue by ClauMS** [IIC2233/syllabus#1244]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo un problema con el envío de información de servidor a cliente. Hay veces que ejecuto el mismo código 2 veces distintas y en una se consigue mandar un mensaje y en otra no (sin cambiar absolutamente nada), por lo que busqué soluciones y una de estas fue añadir un cierto "delay" con time.sleep entre envíos. También intenté evitar hacer esto mediante el correcto uso de Locks() pero sigue sucediendo lo mismo. Por lo que mi primera pregunta es **cuál puede ser la razón de que suceda lo anterior** y mi segunda pregunta es si **es posible utilizar time.sleep() para añadir delays pequeños (0.2s) entre envíos de información para evitar este tipo de problemas.**

**Comment by Mjtala** [comment]
Hola @ClauMS! Lo que dices se puede deber a que estas leyendo más de un mensaje  a la vez o no estás eliminando los bytes de relleno del último chunk. Revisa si tienes alguno de estos dos casos y me avisas!!

**Comment by ClauMS** [comment]
> Hola @ClauMS! Lo que dices se puede deber a que estas leyendo más de un mensaje a la vez o no estás eliminando los bytes de relleno del último chunk. Revisa si tienes alguno de estos dos casos y me avisas!!

Hola!, ya revisé y no es ninguno de los dos casos, es más, algo super importante que se me fue poner en el issue es que efectivamente el programa funciona perfecto con un delay de 0.2s, el cual utilizo al inicio de la función de envío de información de servidor a cliente con time.sleep()

**Comment by Mjtala** [comment]
Hola @ClauMS! El problema es que no estás borrando el relleno de bytes en el último chunk dentro de cliente.py. Si arreglas eso debería funcionarte bien :)
Los delay son solución parche a cuando no se están leyendo bien los mensajes, ya que como hay un delay, el servidor lo interpreta como  que no le quedan mensajes en cola por leer.
