### ISSUE TITLE
abrir archivos .json

### ISSUE THREAD

**Issue by feliperojas123** [IIC2233/syllabus#1245]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

holaaa buenas estuve leyendo las issues y buscando por internet como leer estos archivos, me salia hay que hay usar with open... y por las issues solo json.load(parametros.json), la verdad es que intente de las dos formas y resulta que me tira este error y nose como lograr leer estos archivos

json.decoder.JSONDecodeError: Expecting value: line 2 column 13 (char 14)

si me pudieran ayudar seria un gran favor. graciaas igual

**Comment by Mjtala** [comment]
Hola @feliperojas123 ! La verdad es que debes hacerlo utilizando with open y también json.load.
Te recomiendo revisar este link https://stackabuse.com/reading-and-writing-json-to-a-file-in-python/ donde en la segunda foto está lo que necesitas. A diferencia de la foto que te mandé recuerda que también puedes utilizar el siguiente with open: 
with open(<ruta>, 'r', encoding='Utf-8') as file:
Éxito!

**Comment by feliperojas123** [comment]
noooo @Mjtala me sigue tirando el mismo error usando lo que me enviaste, nose que hacer... con este codigo. literal tengo esto

self.parametros = self.open_file(os.path.join("parametros.json"))

    def open_file(self, path):
        with open(path, "r", encoding="utf-8") as archivo:
            datos = json.load(archivo)
        return datos

**Comment by feliperojas123** [comment]
yaaa ahoera siii lo pude haceeeer muchas graciaaaas te pasate @Mjtala
