### ISSUE TITLE
Locks

### ISSUE THREAD

**Issue by tocococa** [IIC2233/syllabus#1245]
Hola! Hay alguna forma de hacer que al iniciar un método como un thread de la siguiente manera:
```
t = Thread(target=func, args=args)
t.start()
```
esta parta con un `lock.aquire()` y al terminar lo libere?

He visto ejemplos de cosas parecidas, pero en general se hace dentro de la misma clase, y yo necesito que esta sea una función que se importa desde otro módulo.

**Comment by furcelay** [comment]
Se me ocurre que puedes hacer un *wrap* de la función target:
```python
def func_lock():
    with lock:
        func()

t = Thread(target=func_lock, args=args)
t.start()
```

Aunque tal vez para lo que buscas te sirva más un `Event` :eyes:

**Comment by tocococa** [comment]
Gracias! Voy a probar con el _wrap_. `Event` no me sirve porque necesito detener otras _threads_ porque si no al usar `set()` los hilos en espera podrían volver a generar el mismo conflicto que estoy tratando de evitar.

**Comment by Camila-sty** [comment]
Hola! qué es un locks¿? y por qué nos piden eso¿?

**Comment by KnowYourselves** [comment]
Hola @tocococa!

Lo que te propone @furcelay estimo que es una buena aproximación. Desde tu generador de _threads_ deberías definir un lock, y utilizar una función auxiliar que utilice ese lock con la verdadera función a ejecutar.

@Camila-sty, _locks_ son materia de _threading_ que fue vista la semana 8, especificamente en el capitulo de [concurrencia](https://github.com/IIC2233/contenidos/blob/master/semana-08/2-concurrencia.ipynb). Se lo pedimos a nivel de servidor, ya que en el servidor es probable que tengan múltiples threads accediendo concurrentemente a recursos del servidor, por lo cual se deben utilizar locks para que funcione correctamente.

Éxito!

**Comment by Camila-sty** [comment]
@KnowYourselves entiendo, entonces, si quisiera poner el locks en el servidor, tendría que hacerlo cuando escucha a algún cliente o cuando acepta la conexión?

**Comment by KnowYourselves** [comment]
No necesariamente.

En especifico, se usan locks cuando dos o más threads pueden acceder a un elemento a la vez.

**Comment by Camila-sty** [comment]
Sip, pero estaría bien si quisiera poner el locks en la función donde el servidor escucha al cliente?

**Comment by KnowYourselves** [comment]
Ah, si, claro, como ese es el thread, debiese ser usado dentro de esa función (o dentro de una función invocada por esa función).

**Comment by Camila-sty** [comment]
Yaa perfecto, gracias!
Una pregunta adicional, yo no tenía considerado el tema de los locks, entonces estaba teniendo problemas con que la información se juntaba, ósea que recibia información de ambos clientes, pero yo lo solucioné sin locks, obvio que sume mas código y todo, pero ahora que uso locks significa que en adelante ya no tendré problemas con esto. Pero, debo borrar el código adicional que cree para que la inf llegara de a una? y así usar el locks? o sólo lo olvido y sigo... ?

**Comment by KnowYourselves** [comment]
Debes usar Locks, ya que es considerado dentro de la distribución del puntaje.

Éxito!

**Comment by Camila-sty** [comment]
Hola :D
Estoy teniendo problemas con el locks que creo en mi función para escuchar a los clientes (en el server), la función es algo como esto:
![image](https://user-images.githubusercontent.com/59337116/86503775-3ec7d000-bd7f-11ea-9d76-aac0a1838793.png)
la zona crítica sería todo lo que pasa dentro del ```while True```, pero no me funciona así, el problema sería por el ```while True``` ?

**Comment by tocococa** [comment]
Si quieres usar un lock sobre el while, primero tienes que iniciar `listen_client_thread` como un `thread`, y luego usar `Lock.acquire()` y `Lock.release()` en tu sección crítica.

**Comment by KnowYourselves** [comment]
Hola @Camila-sty!

En esa función no hay ningún sector crítico. Tal vez dentro de la función `chat_management`, lo haya. Cualquier modificación a recursos compartidos del servidor debiese utilizar un Lock.

Éxito!

**Comment by Camila-sty** [comment]
@tocococa lo hice antes de llamar a esa función...

**Comment by Camila-sty** [comment]
@KnowYourselves entonces iría cuando el servidor manda la información al cliente?

**Comment by KnowYourselves** [comment]
Tampoco.

Supongamos que tienes una lista y dos threads, A y B. A agrega elementos a la lista de vez en cuando y B también. Sin embargo, puede pasar que tanto A como B realicen esta acción a la vez,  lo cual resultaría en que la lista resultara con información erronea. En este caso tanto A como B debieran compartir un lock y pedirlo cada vez que quieran escribir sobre la lista.

Ahora tu tienes que reconocer en tu servidor que casos caen en ese ejemplo.

Éxito!

**Comment by Camila-sty** [comment]
> Tampoco.
> 
> Supongamos que tienes una lista y dos threads, A y B. A agrega elementos a la lista de vez en cuando y B también. Sin embargo, puede pasar que tanto A como B realicen esta acción a la vez, lo cual resultaría en que la lista resultara con información erronea. En este caso tanto A como B debieran compartir un lock y pedirlo cada vez que quieran escribir sobre la lista.
> 
> Ahora tu tienes que reconocer en tu servidor que casos caen en ese ejemplo.
> 
> Éxito!

entonces puedo hacerlo cuantas veces quiera?

**Comment by KnowYourselves** [comment]
No, se evalua que uses Locks en las situaciones donde debiesen ser utilizados.

**Comment by Camila-sty** [comment]
@KnowYourselves  es tengo listas y diccionarios compartidos entre clientes, en el servidor guardo y edito la información que cambia en cada cliente, pero no he tenido problemas, entonces en ese caso no tendría por qué usar locks, pero en la pauta lo piden, entonces como lo hago?, en resumen, en mi clase server en ningún momento sucede que estas listas y diccionarios compartidos se editen al mismo tiempo... no sé si me explico.

**Comment by KnowYourselves** [comment]
Si, si te explicas!

Mira, el problema no es compartir recursos en si. Por ejemplo, si tienes un recurso que solo es leído, no hay ningun problema. 
Si tienes un recurso que es modificado por muchos threads, pero tienes absoluta seguridad que por como esta diseñado nunca se va a realizar esa accion simultaneamente, tampoco hay problema.

En cambio si tienes threads que **puede** escriban o escriban y lean **simultaneamente** un recurso, entonces si debes usar Locks. 

Ahora, un Lock no se utiliza en el thread entero, sino que especificamente en la acción sensible, sea lectura o escritura.

Espero quede más claro ahí.

**Comment by Camila-sty** [comment]
Entonces, si no hay problema, no uso locks y lo menciono en el README?

**Comment by KnowYourselves** [comment]
Si estas realizando la tarea en su totalidad, debiesen haber situaciones **done si o si debieses utilizar locks**, por ejemplo al gritar DCCuatro.

**Comment by Camila-sty** [comment]
mmmh aun no hago esa parte jajaja, bueno, entiendo, gracias :smile:
