### ISSUE TITLE
Imagenes de cartas en front-end. 

### ISSUE THREAD

**Issue by rtrubio** [IIC2233/syllabus#1246]
Hola! Llevo un par de días pegado intentando mostrar las cartas serializadas en la ventana de juego pero no me resulta. He ido de error en error corrigiendo pero ya no me tira ningún error en la consola, no me tira true/false con el .loadFromData, ni se muestra la imagen en la ventana y ya no se que más corregir. Creo haber intentado las diferentes soluciones de las respuestas a issues similares a esta pero aún no lo logro. No se si estaré haciendo mal la serialización de las cartas, si estoy leyendo mal el mensaje o si estoy cometiendo otro error que no me he dado cuenta. Acabo de hacer push de mi avance hasta el momento, cualquier tipo de ayuda me servirá mucho!
De antemano muchas gracias!

**Comment by vicentevegaulloa** [comment]
Hola @rtrubio!

Revisé tu código y antes de que sigas buscando el error, debo decirte que **no está permitido**  enviar el bytearray de cartas en un diccionario serializado, de acuerdo a lo que se indica en esta [issue](#1119).  Te recomiendo fuertemente que cambies tu código para enviar solo el bytearray. Siento que esta [issue](#1069 ) podría servirte.

Espero haberte ayudado 😄

**Comment by rtrubio** [comment]
Buenisimo! claramente no habia visto esas issues... muchas gracias por la ayuda!

**Comment by vicentevegaulloa** [comment]
De nada!
