### ISSUE TITLE
Puntos de Victoria iniciales

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2233/syllabus#1246]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!

¿Las construcciónes automáticas iniciales aportan puntos de victoria?
Pregunto porque técnicamente el jugador no las construye, y respecto a las carreteras se dice que "Cada carretera construida aportará +1 punto de victoria al jugador que la haya construido.", mientras que respecto a las chozas se dice que "Cada choza ubicada en el mapa aportará +1 punto de victoria para su dueño.", con lo que entiendo que las chozas iniciales aportan puntaje mientras los caminos no.

Gracias de antemano ☺️

**Comment by matiasmasjuan** [comment]
Hola @Sofia-Arratia !

Esta pregunta fue respondida en la issue #1172 .

Saludos! :smile:
