### ISSUE TITLE
Actualizar sala de espera

### ISSUE THREAD

**Issue by Etienne99** [IIC2233/syllabus#1247]
Hola! Tengo problemas para implementar que se actualicen los nombres en la sala de espera cuando se une otro cliente. Pensé en crear un ciclo para el cliente, en el cual reciba información del servidor 4 veces, hasta completar todos los nombres. El problema es que al implementar esta función, la ventana de sala aparece en blanco desde que el cliente ingresa su nombre, y no muestra ningún QLabel. Es algo similar a lo que pasa en la issue #1127, pero me parece que la respuesta que dan ahí ya está implementada en mi programa. Si necesitan más detalles sobre lo que hice intentaré explicarlo mejor. Saludos!

**Comment by gatochico** [comment]
Hola! Lograste solucionar el error? Si no es así, podrías subir lo que llevas a tu repositorio para revisar?
