### ISSUE TITLE
Parametro cantidad de jugadores:

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#1247]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola tengo una duda con la cantidad de jugadores, estos pueden ser de [2,4], por lo que intente implementar un random.randint para que me me generara la cantidad entre esos limites, pero no pude agregarlo a parámetros el random.randint, por lo que hice en parámetros un limite inferior y un limite superior de jugadores, mi duda es si esto esta mal como en el enunciado piden el parámetro numero de jugadores y yo no lo tengo así textual, muchas gracias de antemano!

**Comment by rodrigobj99** [comment]
Hola @Natydlb !
La cantidad de jugadores es un parámetro que siempre va a estar entre 2 y 4, por lo tanto tu programa debe estar diseñado para funcionar con 2,3 o 4 clientes, según el parámetro que ingreses en `parametros.json`. Por lo tanto no es necesario que le pongas limites, ya que solo se corregirá con esas cantidades de jugadores.

Espero haber aclarado tu duda, cualquier cosa me avisas!

**Comment by Natydlb** [comment]
muchas gracias!!
