### ISSUE TITLE
Flujo de turnos después de gritar DCCuatro

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#1248]
Hola, mi programa está implementado de tal forma que se tiene un contador que indica el turno en el cual se está, y que cuando se juega una carta o se termina de robar, cambia. De esta forma, ocupo dicho contador para solo permitir jugar carta o robar a quien se encuentre en su turno. Dicho esto (asumiendo flujo de turnos A -> B -> C -> D -> A), cuando el jugador A tiene una carta y no grita, y mientras se está en el turno del jugador C, el jugador D grita para penalizar al jugador A; cuándo este último roba las cartas? ya que siguiendo la lógica de mi implementación, para que en ese momento robe el jugador A, tendría que hacer que el turno sea de este, luego robe y le toque al jugador B de inmediato, ya que después de robar, se pasa al siguiente turno. Es esto válido? o debería hacer que el jugador A robe cuando sea su turno después de que le toque al jugador C y D?

**Comment by gatochico** [comment]
Hola! 

Para ese caso que dices, el jugador afectado por el grito debería robar de forma automática aunque no sea su turno, pero el orden en que seguía la partida debería mantenerse. En el caso que das, A debería recibir las cartas del DCCuatro mientras se está en el turno de C, pero el orden del juego debería mantenerse e ir a D luego de que C termine de jugar.

Saludos!
