### ISSUE TITLE
Problema conexión cliente.servidor 

### ISSUE THREAD

**Issue by Franco1208** [IIC2233/syllabus#1248]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Al correr ambos archivos me tira el siguiente error:

ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto

señalando el código "sock.send(msg_bytes)"  del servidor. Esto no me permite avanzar con el resto de la tarea.

**Comment by gatochico** [comment]
Hola! Pudiste resolverlo?

Si todavía no, puedes subir tu versión más reciente a tu repo para revisarlo.

Quedo atenta!

**Comment by Franco1208** [comment]
Hola Fran, muchas gracias por responder. Lo acabo de subir, pero ahora me tira otro error  En verdad he estado muy pegado y bloqueado con esta tarea☹. Me cuesta la lógica de cuales y como deben ser los mensajes que quiero enviar (no en bytes, sino que el mensaje mismo). También me cuesta entender como es el primer mensaje del juego, entiendo que es enviar el nombre del jugador del servidor al cliente, pero me cuesta muchísimo llevarlo al código☹. Quedo atento a tu respuesta. Franco Giubergia. Enviado desde Correo para Windows 10 De: Fran IbarraEnviado: sábado, 5 de diciembre de 2020 18:43Para: IIC2233/syllabusCC: Franco1208; AuthorAsunto: Re: [IIC2233/syllabus] Problema conexión cliente.servidor (#1248) Hola! Pudiste resolverlo?Si todavía no, puedes subir tu versión más reciente a tu repo para revisarlo.Quedo atenta!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by gatochico** [comment]
Hola! Bueno, respecto al error específico que te sale, es porque estas diviendo un bytearray por un número, cuando lo que quieres es dividir el **len** de dicho bytearray.

Respecto a tu otra duda: Dejamos a criterio libre qué formato tiene el mensaje interno que quieres enviar (puedes enviar un string, una lista cuyos elementos sean palabras claves para manejarlas en el cliente/servidor, un diccionario con llaves y valores que usarás en el manejo, etc...), de forma que pudieran usar el que se les hiciera más facil y les sirviera más en su código. Este mensaje con formato libre se transforma a bytes y luego debe ser de nuevo **codificado**, segun los pasos del enunciado (lo de enviar primero el largo, luego el número de bloque y bloques hasta que se termine el mensaje). En el enunciado hay un ejemplo paso a paso para esta codificación si lo necesitas!
