### ISSUE TITLE
Penalización gritar DCC4 y +2

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#1249]
Hola, suponiendo un caso en donde se tiene que el pozo ha acumulado un +2 y cuando le toca al jugador A, este posee una carta, y en ese mismo momento, el jugador B grita para penalizarlo; en ese caso, las 4 cartas que debe robar por penalización se suman a las que tenía que robar por la penalización o sólo tiene que robar las 4 cartas de la penalización?

**Comment by gatochico** [comment]
Hola!

Queda a tu criterio si: 

1) Roba las cartas correspondientes al grito DCCuatro y las del +2 y se acaba su turno de forma automática. 
2) Roba las correspondientes al DCCuatro,se le da la opción de jugar si es que tiene cartas adecuadas o robar las del +2 si no las tiene, y ahí termina el turno.

Saludos!
