### ISSUE TITLE
la lectura y el enviado de mensaje debe ser con json

### ISSUE THREAD

**Issue by feliperojas123** [IIC2233/syllabus#1249]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

holaaa buenaaas... tengo una duda con el enviado de mensaje y lectura de este, lo que nose es que es necesario para la tarea enviar los mensajes y leerlos con json o simplemente lo puedo hacer con encode y decode dandole el "utf-8" ??? 
o queda a mi criterio que forma usar para generar esto???

**Comment by rodrigobj99** [comment]
Hola @feliperojas123 !

Para esta tarea la única obligación es codificar los mensajes, por lo tanto no es necesario usar serialización. Sin embargo es recomendable usar serialización ya sea en pickle o json para enviar la información, ya que puede ser útil para enviar diversas estructuras de datos como listas, diccionarios o tuplas.

Saludos y éxito en la tarea!
