### ISSUE TITLE
Borrar archivo innecesario del repositorio remoto

### ISSUE THREAD

**Issue by juan-palma-1** [IIC2233/syllabus#125]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
Saludos, tengo una duda respecto de como borrar de **buena manera** un archivo en mi repositorio remoto de la Tarea 0 ya que este no es necesario para correr el programa. Este archivo fue subido en una iteración temprana de mi trabajo, posteriormente al modularizar el programa cambié el nombre de este a uno mas descriptivo. Actualmente se conserva una copia con el nombre antiguo(y desactualizado) y una con el nombre nuevo. No quiero incurrir en descuentos para mi tarea por archivos innecesarios, muchas gracias de antemano.

**Comment by RafaelEdwards** [comment]
Hola!

Para hacer lo que necesitas puedes usar el comando git rm, puedes encontrar más información sobre este comando en internet.

Espero haberte ayudado y suerte con tu tarea :).
