### ISSUE TITLE
Try/except para debuggear módulos 

### ISSUE THREAD

**Issue by jg-tuna** [IIC2233/syllabus#125]
Hola, lo que pasa es que estoy trabajando con subcarpetas para la tarea y estoy usando la clásica carpeta __init__.py e importaciones relativas (creo que estos se conoces como modulos (corrijanme si me equivoco plox)) . Lo que pasa es que si corro el archivo principal (a.k.a main.py) todo corre bien, pero cuando quiero debbugear un archivo en particular debo cambiar la importación, lo que se podría arreglar con un try (que esta prohibido). Con esto... hay un problema que no se puedan correr estos archivos .py (siendo que tanto script como readme va a tener comentado esto y como probar el script)? o mejor dejo todo en una sola carpeta?... o agrego las carpetas a la ruta por medio de sys.path(que no se si se pueda)?

**Comment by KnowYourselves** [comment]
Hola @jg-tuna!

Por lo que veo has investigado bastante cómo hacer tus propios módulos en _Python_ 👀 Good Job!
Respondiendo tu pregunta directamente, no hay ningún problema con que utilices `try` para debuggear tu código, el punto es que **no lo utilices como parte de la lógica de tu programa**. Es decir, una vez terminado tu debuggeo, tienes que eliminar todos los usos de `try`.

De todas formas, la creación de módulos propios no es verdaderamente necesaria en este curso, puedes simplemente importar archivos de python directamente.

Quedo atento!

**Comment by jg-tuna** [comment]
muchas gracias!!! :smiley_cat:
