### ISSUE TITLE
Selección de coordenadas para lanzar bombas

### ISSUE THREAD

**Issue by pilarjimenez** [IIC2233/syllabus#125]
Hola! 
En el menu de juego a la hora de preguntarle al jugador por las coordenadas a las que quiere lanzar una bomba se espera que sea en uno o varios inputs, las coordenadas de columnas con mayúsculas o minúsculas (o que se acepten ambas), o si bien, todo lo anterior queda a mi criterio?

**Comment by vicentevegaulloa** [comment]
Hola @pilarjimenez !

La cantidad de inputs no se especifica en el enunciado, por lo que queda a tu criterio. Por otro lado, se espera que tu programa acepte mayúsculas y minúsculas, ya que a eso nos referimos cuando hablamos de manejar el input de usuario de forma robusta.

**Comment by YehudaGurovich** [comment]
Tengo que indicarle al Jugador que coordenadas aun no han sido descubiertas para que seleccione entre ellas o simplemente con la impresion del tablero es suficiente?

**Comment by vicentevegaulloa** [comment]
Hola @YehudaGurovich!

Podrías hacerlo, pero no es necesario. Basta con la impresión del tablero 😄
