### ISSUE TITLE
Duda sobre mejora de simulacion

### ISSUE THREAD

**Issue by chuma9615** [IIC2233/Syllabus#125]
Hola, mi duda se refiere al punto. 5.2 en el cual se afirma que 

"En caso de que dos o mas condiciones meteorológicas del mismo tipo coincidan con un incendio, solo se debe tomar en cuenta la más reciente."

Es posible que pueda tomar en cuenta el efecto de ambos condiciones del mismo tipo para así tener una simulación aun mas precisa?

**Comment by arturodelreal** [comment]
Hola, debes considerar solo una condición meteorológica.
Salu9
