### ISSUE TITLE
Crear Planeta

### ISSUE THREAD

**Issue by auirarrazaval** [IIC2233/Syllabus#125]
Hola! Al crear un planeta, uno setea los atributos ademas de raza y nombre? Por ejemplo, en que porcentaje esta poblado, si tiene cuartel y/o torre, etc

Lo unico que encontre al respecto en el enunciado es cuando se crea una galaxia que todos los planetas no conquistados deben ser poblados en un 75% de su poblacion maxima, pero no se si eso aplica para este caso y aun deja la duda de los cuarteles y torre.

Muchas gracias

**Comment by IchottMano** [comment]
@auirarrazaval Hola!
En primer lugar puedes asumir que cualquier planeta no conquistado nuevo (es decir, que no haya sido del jugador en algun momento) no tiene edificios.
En cuanto a la población, tu mismo te respondes con lo que dijiste en tu segundo punto, al momento de crear un planeta este no esta conquistado, por lo que debe ser poblado.
Espero que esto resuelva tu duda.
Saludos!

**Comment by dedarritchon** [comment]
Que pasa con los planetas de raza mago? se reparte el 75% de la población máxima entre soldados y magos en partes iguales? @IchottMano

**Comment by IchottMano** [comment]
@dedarritchon Hola!
Con "raza mago" te refieres a la **raza maestro**?
De ser así, queda a tu criterio como repartes la población inicial.
Si no era eso a lo que te referías, por favor acláralo un poco más 😄
Saludos y éxito con tu tarea!
