### ISSUE TITLE
Duda con archivo acciones.csv

### ISSUE THREAD

**Issue by MGilB** [IIC2233/syllabus#125]
Hola, tengo una duda con el archivo.csv, ya que tiene acciones con los 3 id posibles. Lo que deberíamos hacer es ignorar las acciones que pertenezcan a la civilización del usuario y usar el resto??

**Comment by gatochico** [comment]
Hola! Estás en lo correcto, debes ejecutar unicamente las acciones de las civilizaciones que no sean la del usuario a partir de __acciones.csv__. Exito!
