### ISSUE TITLE
Contrincantes carrera

### ISSUE THREAD

**Issue by fmaturanaa** [IIC2233/syllabus#125]
Estimados, los contrincantes en la carrera también sufren daños a su auto? Están sujetos a la probabilidad de accidente? En los ejemplos sale que un piloto fue "descalificado" eso como podría suceder?  
Muchas gracias por su tiempo!

**Comment by gatochico** [comment]
Hola! 

Si, los contrincantes también son afectados por la probabilidad de accidente. Un piloto es descalificado de la carrera cuando su `chasis` llega a 0 (es destruido completamente).

Saludos y éxito! :car: :checkered_flag:

**Comment by muovalle** [comment]
hola!, si los contrincantes también se ven afectados por la prob de accidente, ¿Cual sería su chasis máximo? ya que ellos no compran mejoras en los pits. ¿Será igual a su chasis inicial?

**Comment by bpeirano1** [comment]
Hola! Los contrincantes si son afectados por la probabilidad de accidente. 
Respecto a tu pregunta, sí, su chasis máximo sería igual al chasis inicial. 

Éxito!

**Comment by muovalle** [comment]
Gracias! y tambien se les repara el vehículo automaticamente en los pits?

**Comment by bpeirano1** [comment]
Queda a tu criterio si es que los contrincantes entra o no a los pits. En el caso de que entre, se tiene que reparar automáticamente el chasis
