### ISSUE TITLE
Alcance Piezas Explosivas

### ISSUE THREAD

**Issue by fbehncke** [IIC2233/Syllabus#125]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Quería saber si las celdas que puede alcanzar una pieza explosiva debe considerar a las otras piezas explosivas, ya que sé que debe alcanzar las celdas vacías y no los peones pero no entiendo si se debe considerar como celda alcanzada otra pieza explosiva. Esto es para la property piezas_explosivas_invalidas de la clase tablero. Muchas gracias.

**Comment by Dominique236** [comment]
Hola! 
Te puedes guiar por el ejemplo que aparece en el enunciado de la _property_ piezas_explosivas_invalidas. Por ejemplo, se menciona que solo "V3" y "R6" son inválidas, por tanto "H3" si es válido y en este caso las celdas que alcanza esta pieza, marcadas con X, serian `[[X,X,X],[ , , ]]` que **si considera una posición ocupada por una pieza explosiva ("V3") y un peón**. Debes notar que la finalidad de esta _property_ es solo revisar si la cantidad de celdas a destruir es mayor al alcance máximo que tenga esta pieza.
Cuéntame si esto resuelve tu duda 😊
