### ISSUE TITLE
Duda sobre señales

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#1250]
Gracias a que nos entregaron la T02, pude darme cuenta como mi principal error en esta, era el mal uso de señales. Siendo bien honesto, entiendo como ocupar señales (ósea todo lo que es la importación, la emisión, la conexión, etc) pero no entiendo muy bien cuando hay que utilizarlas. 

Por esto mismo queria preguntar aquí, cuando es necesario usar señales, y cuando no, ya que en mi corrección, varias veces se me decía que debía usar señales, y ademas en otras partes se me decía que la señal era innecesaria, y debía usar el llamado directo de la función. 

Muchas gracias de ante mano.

**Comment by gatochico** [comment]
Hola!

Como regla general, siempre que el _frontend_ (quien solo se encarga de la parte gráfica de la tarea) deba interactuar con el _backend_ (donde debería ir toda lógica), esto debe hacerce mediante señales. Si te das cuenta en tu código que estás mezclando muchos elementos de interfaz (ej: modificar un label, o un pixmap) con lógica no-superficial (ej: todo el proceso de recibir un mensaje del servidor y decodificarlo) en una misma función, deberías  tratar de separarlo vía señales, ya que cierta parte de esa función es labor del frontend, y cierta parte es del backend y por ende, deberían estar en distintas funciones y modulos.

Si no quedó tan claro, quiza un ejemplo de la T02 ayude. Con respecto al movimiento del mesero, una forma de manejarlo con señales sería:
- El usuario aprieta una tecla para moverse.
- El _frontend_ percibe que tecla se presionó, según cual fue **le envía una señal al backend para manejar este caso**
- El _backend_ recibe la señal, revisa que pasa si el mesero se mueve en la direccion indicada (¿habrá colisión con paredes?¿habrá colisión con chefs/clientes?) Dependiendo si hay o no colisión, maneja el caso de forma apropiada.
- Según lo anterior, el _backend_ calcula la nueva posición del mesero y **le envía una señal al frontend con la nueva posición y el path al nuevo sprite**
- El _frontend_ recibe la señal y, como la validación completa de esta posición ya fue hecha por el backend, simplemente mueve el label a la posición que le dijeron y cambia el pixmap por el que le dieron. Solo se encargó de modificar la interfaz.

Espero se haya entendido y si no, no dudes en preguntar!
