### ISSUE TITLE
Derrepente una de la ventanas de los clientes deja de funcionar

### ISSUE THREAD

**Issue by TMagini** [IIC2233/syllabus#1250]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, me pasa que algunas veces (no siempre) una ventana de solo un cliente deja de funcionar, por ejemplo, voy a hacer un intercambio y sale un mensaje de Windows diciendo que dejo de funcionar la ventana. Mi pregunta es si es problema de rendimiento de mi pc o parte de mi código, por como dije, hay veces que me corre toda una partida.

**Comment by aaossa** [comment]
Hola @TMagini , no estoy 100% seguro de qué podría ser, pero ese error ocurre a veces cuando el código de la interfaz entra en un *loop* infinito o un "while True". Si es que tienes un while cerca de un `try`/`except`, intenta comentando el código del manejo de excepciones, ya que es posible que haya una excepción que se esté levantando frecuentemente y te "bote" el cliente. Espero se entienda, pero es solo una idea para intentar encontrar la raíz del error 😅 ¡Ánimo con la tarea 💪!
