### ISSUE TITLE
Gritar DCCuatro y Cambiar Color

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#1251]
¿Un jugador puede usar la carta color, y antes de elegir el color gritar dccuatro? Me refiero a que si en el momento en que se hace abre la ventana para elegir color, el jugador que la abrio puede gritar dcc cuatro.

**Comment by felipefuentesporras** [comment]
A y tambien, si un jugador con 1 carta, juega una carta de cambiar color. ¿Gana automaticamente o debe igual elegir color antes de ganar?

**Comment by DCCollao** [comment]
Hola @felipefuentesporras!

Este tipo de comportamientos son muy específicos, y como no les dimos una forma de manejarlos en el enunciado, la forma en que lo manejes queda a tu criterio y debes explicarlo en el `readme.md`.

**Comment by felipefuentesporras** [comment]
Dale, gracias!
