### ISSUE TITLE
Desconexión repentina

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#1252]
Hola.
No entiendo muy bien esta parte.
Cómo se podría desconectar un servidor o cliente de manera "repentina" ?
Se refiere a que se pierde la conexión por el port o host?
Se refiere a  simplemente cerrar la ventana de ejecución de cualquiera de éstos?
No se me ocurre como implementar esto. Si se cae alguno, cómo puedo saberlo a través de código?. Necesito evaluar esto para que luego ocurran las condiciones que corresponden luego de que uno de éstos se desconecte...

**Comment by vicentevegaulloa** [comment]
Hola @Camila-sty !

Intentaré responde todas tus dudas.

_Cómo se podría desconectar un servidor o cliente de manera "repentina" ?_

Supongamos tienes un error en tu código, y al ocurrir un evento en específico, tu cliente se cae. Al caerse el cliente, pierde inmediatamente la conexión con el servidor y se mostrará un error en este último `(ConnectionResetError)`.  La idea es que tu sepas manejar este tipo de error tanto en el cliente (si se desconecta el servidor) como en el servidor (si se desconecta un cliente).

> Se refiere a que se pierde la conexión por el port o host?

Se pierde la conexión con el **port y host** en el que se encuentra el emisor/receptor. Ya que se pierde la conexión con un programa que se encuentra en un puerto (port) de un computador (host). Recuerda la analogía vista en este [notebook](https://github.com/IIC2233/contenidos/blob/master/semana-14/1-conceptos-b%C3%A1sicos.ipynb), donde se compara el host con un edificio y el port como el numero de departamento.

> Se refiere a simplemente cerrar la ventana de ejecución de cualquiera de éstos?

Claro, simplemente cerrarla o detener el programa con `Ctrl+C`, o que se caiga por un error en el código.

> No se me ocurre como implementar esto. Si se cae alguno, cómo puedo saberlo a través de código?

Como mencioné anteriormente, al caerse el cliente, pierde inmediatamente la conexión con el servidor y se mostrará un error en este último `(ConnectionResetError)`. Ocurre lo mismo para el otro lado, por lo que con ese error sabrás que el problema está asociado a una desconexión repentina. Siento que el código de [esta](https://github.com/IIC2233/syllabus/blob/master/Actividades/AF06/servidor/servidor.py) te podría servir.

Espero haberte ayudado 😄

**Comment by Camila-sty** [comment]
entiendo, muchas gracias ! :smile:

**Comment by Camila-sty** [comment]
Tengo un problema, cuando un cliente pierde la conexión, el servidor emite el mensaje del usuario que se desconecta, pero, al seguir funcionando para otros clientes, en el próximo mensaje que un cliente intenta mandar al servidor se cae y emite el  mismo error ```(ConnectionResetError)```, qué debería hacer en este caso?

**Comment by vicentevegaulloa** [comment]
En este caso, el problema ocurre porque el cliente que se desconectó sigue dentro de tu lista de "jugadores activos" (asumiendo que los guardas en algún lado). Debes eliminar al usuario desconectado de este grupo de jugadores activos para que no se le alcance a enviar un mensaje, ya que este no lo recibirá.

**Comment by tedroppelmann** [comment]
Hola! Me pasa que cuando se desconecta el cliente o el servidor la excepción que cae es json.decoder.JSONDecodeError.  Influye en algo? en verdad no se por que pasa jajaja

**Comment by lily416** [comment]
@tedroppelmann, el excepción se debe a que se produce un error al tratar de decodificar el mensaje que te fue enviado. 
Si sigues teniendo dudas con respecto a esto te recomiendo: hacer otra _issue_, poner el error que te sale en consola e indicar el mensaje que estás enviando.

Saludos y éxito en la tarea 👋🃏
