### ISSUE TITLE
Envio de cartas desde el cliente al servidor

### ISSUE THREAD

**Issue by rodrigobj99** [IIC2233/syllabus#1254]
Hola, en el enunciado se menciona "implementar el envío de cartas entre el cliente y el servidor. Ese envío debes implementarlo según la siguiente especificación:". Mi pregunta es si esto es solo para enviar las cartas desde el servidor al usuario, o si también debe seguirse el formato para enviar cartas desde el usuario al servidor.

**Comment by vicentevegaulloa** [comment]
Hola @rodrigobj99 !

Sólo el servidor puede enviar cartas al cliente, no viceversa. Esto porque el servidor es el único que posee los sprites de las cartas. Pero si te refieres a enviar las cartas que el cliente decide botar, entonces este es otro caso, ya que no se pasa la imagen y queda a tu criterio la forma en que envías la información sobre la carta botada al servidor.

Espero que se entienda y cualquier cosa avísame! 😄

**Comment by cotefon** [comment]
en el enunciado dice que el jugador cada vez que quiera sacar una carta el servidor debe enviar la imagen, puedo al momento de crear el cliente enviarle TODAS las imágenes (tanto mis sprites, como los sprites de las cartas) y este las descarga y las trabajo a través de path? (al hacer esto el cliente las "descarga")

**Comment by vicentevegaulloa** [comment]
Hola @cotefon !

Respecto a tu primera pregunta, en el enunciado se pide que el servidor entregue al cliente todas las sprites de las cartas, por lo que **si puedes** almacenar en el cliente otras sprites distintas de las cartas. Respecto a tu segunda pregunta, lo correcto sería lo último que indicas. El servidor debería enviar cada carta cuando se necesite para que el cliente la use en ese momento, sin guardarla como archivo.
