### ISSUE TITLE
Problema para correr desde terminal

### ISSUE THREAD

**Issue by TeresitaS** [IIC2233/syllabus#1255]
Hola, estoy tratando de probar mi codigo para varios clientes y no lo estoy logrando. Al correr el main.py del servidor desde python me arroja el siguiente error:

Teresita-MacBook-Pro:servidor Teresita$ python main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from servidor import Servidor
  File "/Users/Teresita/Desktop/repolocal/TeresitaS-iic2233-2020-1/Tareas/T03/servidor/servidor.py", line 25
    print(f"Servidor escuchando en {self.host}:{self.port}")
                                                          ^
SyntaxError: invalid syntax

Pero al correrlo en el editor no tengo problema.

Lo mismo me pasa con el main.py del cliente que al correrlo en python me arroja el siguiente error:

Teresita-MacBook-Pro:cliente Teresita$ python main.py
  File "main.py", line 15
SyntaxError: Non-ASCII character '\xc3' in file main.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Pero al correrlo en el editor no tengo problema, pero puedo correr solo uno al mismo tiempo.

Necesito poder correrlo para ver si lo que estoy haciendo esta bien. 
SEND HELP

**Comment by gatochico** [comment]
Hola! Como estas usando MacOS, trata corriendo el comando `python3 main.py`, ya que para los Mac el comando `python` hace que ejecutes el programa con python 2 en vez de 3.

Avísanos si lo soluciona!

**Comment by TeresitaS** [comment]
Funciona! Muchas gracias! Eternamente agradecida!!
