### ISSUE TITLE
Python se cierra inesperadamente sin un error explícito

### ISSUE THREAD

**Issue by ElenaVillalon** [IIC2233/syllabus#1256]
Hola!
Necesito ayuda para resolver este error, ya que no se por donde abordarlo al no decir explícitamente lo que ocurre. Al ingresar la cantidad suficiente de jugadores a la sala de espera, el servidor se comunica con los clientes, y desde un método de los clientes se mandan dos señales a las interfaces, la primera para cerrar la ventana de la sala de espera, y la segunda para abrir la ventana de juego. Sin embargo, sólo se me abre la ventana del primer jugador, la del segundo jugador no se abre, y aparece un mensaje de que Python se cerró inesperadamente. ¿Es un error del código? Si es así, ¿por cuales razones se podría abrir una ventana y la otra no? (Lo único que se me ocurre, es que quizás como el último jugador ingresa y casi instantáneamente se abre la ventana de juego, las señales se confundan.)
En la consola no sale ningún error, más que la desconexión con el servidor: ConnectionResetError: [Errno 54] Connection reset by peer
Muchas gracias!

**Comment by fdoflorenzano** [comment]
Hola @ElenaVillalon,

En primera instancia se me ocurre sea algo de PyQt que no detectas. ¿Agregaste el *hook* de errores recomendado en los contenidos de interfaces gráficas ([el de al final de este cuaderno](https://github.com/IIC2233/contenidos/blob/master/semana-09/1-interfaces-gr%C3%A1ficas.ipynb))?
Si no, agregalo y ve si te da un poco más de información.

Saludos.

**Comment by ElenaVillalon** [comment]
Muchas gracias! Lo intentaré. 
Sólo para confirmar, el hook de errores se debería implementar en el archivo main de clientes? Es ahí donde instancio a los clientes, que tienen como atributos las instancias de las ventanas.

**Comment by fdoflorenzano** [comment]
Hola @ElenaVillalon,

Sí, para el archivo principal donde se comienza la interfaz gráfica, con `QAplication`.

Saludos.

**Comment by ElenaVillalon** [comment]
Estimado, aún no se me arregla el problema, y con el hook tampoco se imprime ningún error :(
Sigue ocurriendo que se logra inicializar la ventana de juego del primer jugador, pero el resto no.

**Comment by fdoflorenzano** [comment]
Hola @ElenaVillalon,

¿Cómo ejecutas las cosas? Porque me pasó lo que dices (la caida de algunos programas) pero los que se caen si me lanza un error, el siguiente:
```
Traceback (most recent call last):
  File "/*/ElenaVillalon-iic2233-2020-1/Tareas/T03/cliente/ventana_juego.py", line 260, in actualizar_labels
    dict_j = self.cartas_j1
AttributeError: 'VentanaJuego' object has no attribute 'cartas_j1'
```

**Comment by ElenaVillalon** [comment]
A mi también se me imprime eso en la consola de los clientes que no se les abre la ventana, pero ese no es el error que hace que se caiga, porque los atributos si existirían si se hubiera inicializado la ventana con la señal que envía el método (ya que la señal se conecta con el método de iniciar_gui que define dichos atributos, y luego hace self.show()). Ese error entiendo que es después, cuando actualizo los labels de los jugadores en la interfaz, pero ésta nunca existió.

**Comment by fdoflorenzano** [comment]
Hola @ElenaVillalon,

Lo que respondiste da la clave al posible error entonces. Al aparecer se acciona en esos clientes algo que altera la ventana, antes de que llegue el mensaje que le dice que aparezca efectivamente. Mirando los prints, si te fijas el cliente que no se cae imprime un `4` que corresponde a lo que gatilla que aparezca la ventana, mientras que los dos que se caen, reciben otros mensajes antes que el `4`. Intenté jugar un poco, y creo que el problema está desde el servidor. Algo pasa que no llegan en orden los mensajes. Tal vez esto te suene de donde puede ser, seguiré mirando a ver si lo encuentro.

Saludos.

**Comment by fdoflorenzano** [comment]
Ahí lo encontré, `comenzar_juego` le dice al primer jugador que comience, y **antes** de decirle a resto que comience, le manda las carta de reverso a todo el resto. Si procuras que envié todos "comiencen" y luego envias otras cosas, funciona :)

**Comment by ElenaVillalon** [comment]
Tiene toda la razón!!
Muchísimas gracias :D
