### ISSUE TITLE
Señales no funcionan en mi computador al parecer

### ISSUE THREAD

**Issue by stephenwpugh** [IIC2233/syllabus#1256]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola! Suena raro, pero he tenido muchos problemas durante la Tarea 3 porque **ninguna señal parecía funcionar**, busqué ayuda pero no se arreglaba, probando de todo. Para probar, corrí la AF05 (la versión corregida, mostrada en el video de cierre) y nuevamente las señales no responden! por lo que creo que es un problema de mi computador, o del setup de los programas que uso (aunque corro los programas en Bash). Qué cosas podría intentar? Hay muchas cosas de la T03 que no podré lograr si no es con señales :( 
Edit: quizás es una duda más para bienestar, pero dado que ya está aquí, vale la pena preguntar jajaja

**Comment by aaossa** [comment]
Hola @stephenwpugh , efectivamente es un problema muy raro. ¿Se ve la interfaz cuando ejecutas el archivo? ¿Lanza algún error? ¿Probaste con los ejemplos de los contenidos de esta materia (semana 9 me parece)? Por otra parte, intenta ejecutando estos archivos desde tu IDE (interfaz de desarrollo) o, mejor aún, directamente desde la consola (no desde Git Bash). Intenta con alguna de esas cosas.
