### ISSUE TITLE
Error al correr código del Cliente

### ISSUE THREAD

**Issue by AlonsoZamorano** [IIC2233/syllabus#1257]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda Error Loop infinito en codigo

Hola buenas tardes. Tengo un pequeño problema y no entiendo el porque ocurre. Esto me sucede al probar mi codigo del cliente (el main.py) y me arroja un loop infinito de texto con lo siguiente:
![image](https://user-images.githubusercontent.com/69593192/101247965-52df7700-36fb-11eb-8ff3-565a276d5c00.png)
(Foto Error)
No entiendo que es lo que puede estar pasando :(.

**Comment by aaossa** [comment]
Hola @AlonsoZamorano , ¿este es un código que tomaste de los contenidos o es algo que modificaste? Si es de los contenidos, dime cuál utilizaste para revisarlo, pero si es algo que modificaste tú intenta subirlo a tu repositorio y le coloco la etiqueta correcta a la *issue* 👌 ¡Éxito con la tarea 💪!
