### ISSUE TITLE
Cierre del servidor

### ISSUE THREAD

**Issue by tcouso** [IIC2233/syllabus#1257]
Hola!
He estado teniendo problemas para lograr que concluya el programa del servidor. Tengo implementado un método que cierra todos los sockets de los clientes, y logro que los clientes se cierren, pero el servidor nunca termina de ejecutarse y tengo que cerrarlo desde el administrador de tareas. He probado algunas de las aproximaciones de las actividades y ejemplos, pero hasta ahora sin resultado. Algún consejo sobre cómo implementar esta función?
Saludos!

**Comment by furcelay** [comment]
En la actividad AF06 hay un buen ejemplo, se usa `input` para recibir un comando de cierre desde la consola, revisa el archivo `main.py` del servidor.

**Comment by fdoflorenzano** [comment]
Hola @tcouso,

Revisé tu repositorio y noté ya cambiaste como manejar el funcionamiento del servidor. ¿Seguiste la recomendación de @furcelay? ¿Te funcionó?

Saludos.

**Comment by tcouso** [comment]
Hola @fdoflorenzano,

Lo intenté implementar con esa aproximación, pero pareciera ser que queda un proceso interno andando, y no logro verificar bien cual es. Sospecho que tiene que ver con hacer atómica la operación de cerrar los sockets y cerrar las puertas de los threads que escuchan a los clientes (con puertas me refiero a unos atributos booleanos que controlan el iterador while del thread, y que se setean a false cuando se cierra el servidor). Sin embargo, luego de implementar un lock para resolver ese tema, el problema persistió, y para no seguir estancado ahí comencé a desarrollar otras partes. Quizás estoy mal orientado con lo de implementar un lock, o quizás no lo estoy haciendo apropiadamente. 
Mi intuición del problema podría ir en buen camino?

Muchas gracias por toda la ayuda, y a @furcelay por los consejos!

**Comment by fdoflorenzano** [comment]
Hola @tcouso,

Revisé y tienes razón, aún no se termina y algunos procesos se cierran con interrupciones. Los que reconocí son los siguientes:

- El *thread* que acepta conexiones de nuevos clientes. Si bien cambias el *boolean* para que deje no vuelva a iterar en el proceso, lo más probable es que al momento de cambiarlo, la ejecución del proceso ya estaba dentro de una iteración y estaba esperando en la línea: `self.server_socket.accept()`. Al cerrar el *socket*, el *thread* se cae ya que la operación `accept` se rompe intentar actuar sobre un *socket* cerrado, y lanza un error.
- Los *threads* que escuchan clientes. Similar al caso anterior, si bien cambias el *boolean*, la ejecución del proceso ya estaba dentro de una iteración y estaba esperando en la línea: `player_socket.recv(4)`. Y también se cae al intentar operar sobre un *socket* cerrado.
- Hay un tercer *thread* de tu clase `GameBack` que sigue funcionando, y al ser no *daemon*, el programa le espera a que termine. Faltaría idear una forma de permitir salir del flujo del *thread* cuando se desea cerrar.

Para solucionar los primeros dos casos, una forma es capturar los errores en caso de caídas debido a forzar el cierre, pero es un poco forzado. Otra forma es idear una forma de que no se caiga al cerrar el *socket*. Googlié un poco y hay una forma de establecer que las operaciones bloqueantes de *sockets* duren un tiempo específico, pero habría que alterar el flujo del código para ver el caso de que no se acepten conexiones o mensajes en el tiempo. Aquí va el [enlace](https://stackoverflow.com/questions/7354476/python-socket-object-accept-time-out).

Espero se entienda y te ayude,
Saludos.
