### ISSUE TITLE
Es necesario ver carretera más larga y restricciones de construcción utilizando el grafo como tal.

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#1259]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, en la distribución de puntajes en la sección de grafo dice que _Se verifica que se cumplen las restricciones correspondientes para construir una choza._ y _Se calcula correctamente la carretera mas larga._ Mi pregunta es si esto puedo no hacerlo mediante el grafo como tal, es decir, hasta ahora cada vez que se construye una choza o carretera la información necesaria se va almacenando por lo que en ningún momento necesito realizar operaciones en el grafo ni cambiar valores en éste. Entonces se puede de esta forma?

**Comment by tolavarria** [comment]
Tengo una duda parecida. En mi caso es que he estado recorriendo valores de nodos sin necesariamente usar funciones de recorrido de grafos hasta encontrar el que quiero.

**Comment by Mjtala** [comment]
Hola @Gustav2000 y @tolavarria! Esa sección de grafo esta pintada amarilla (en la pauta de corrección) por lo que se revisa el código y si no se utiliza grafos entonces no podrás acceder a todo el puntaje. Sin embargo, no creo que demos 0 puntaje así que no se preocupen! 
Éxito!!
