### ISSUE TITLE
Error de conexion

### ISSUE THREAD

**Issue by domja** [IIC2233/syllabus#1259]
ConnectionAbortedError: [WinError 10053] Se ha anulado una conexión establecida por el software en su equipo host
Me empezo a salir este error, de que puede ser y como se podria arreglar, segun lo que dice tiene que ver con mi computador?

**Comment by fdoflorenzano** [comment]
Hola @domja,

Errores de ese estilo suele deberse a que uno de los programas se cae o cierra la conexión de *socket* cuando el otro sigue usándolo. Similar a las issues #1149 o #1093.

El número de error es distinto, así que no estoy compaletamente seguro. Tampoco has subidos tus avances a tu respositorio para probarlo. Intenta revisar si lo anterior es el caso, o en su defecto, sube tus avances para revisar tu código.

Saludos.
