### ISSUE TITLE
Formato de fechas en usuarios y orders

### ISSUE THREAD

**Issue by mebruna** [IIC2233/Syllabus#126]
El formato de las fechas será "DD/MM/AAAA", "DD-MM-AAAA" o será variable?

**Comment by TomasSalvadores** [comment]
Esta a tu criterio, pero ten ojo de que debe ser claro e intuitivo dentro de tu programa. Recuerda que no se debe caer por un input incorrecto por parte del usuario.

**Comment by naazocar** [comment]
Pero a la hora de probar el programa con otros archivos será tal cual está actualmente en orders.csv y users.csv (AAAA-MM_DD)?

**Comment by TomasSalvadores** [comment]
Nop, el formato de fecha se mantendrá en los archivos. Pero recuerda que cuando probemos tu programa podríamos variar un par de cosas en los archivos, ej. el orden de las columnas, y tu programa debe soportar eso!

**Comment by JPSF** [comment]
¿Entonces el programa tiene que ser capaz de reconocer los strings que aparecen en el encabezado(por ejemplo "amount:float")? ¿O estos encabezados también podrían variar su nombre?

**Comment by iqacevedo** [comment]
Hola

@JPSF los nombres de los encabezados serán los mismos (siempre tendrás uno con "amount:float"), pero pueden estar en distinto orden.

Saludos !

**Comment by JPSF** [comment]
Perfecto! Gracias @iqacevedo
