### ISSUE TITLE
duda archimago + restriccion nombre planeta

### ISSUE THREAD

**Issue by lucasalamos** [IIC2233/Syllabus#126]
Hola, tengo 3 dudas.
1. Que pasa si un archimago ''desconquista'' mi único planeta conquistado?
2. Si un archimago invade un planeta mio de raza maestro, puedo utilizar la habilidad del maestro?
3. Dentro de los archivos hay un planeta que se llama "Aiur" que no cumple con la restricción del nombre de un planeta (mínimo 6 letras o números) .. cuando corro mi programa no me deja crear ese planeta, debo cambiarle el nombre?

**Comment by rihanuch** [comment]
Hola @lucasalamos !!

1. Queda a tu criterio 💻
2. Esto no está especificado, así que también queda a tu criterio 🔨
3. ¡Puedes editar esa parte del script! Cuando corrijamos nos vamos a asegurar de que todos los nombres estén bien en cuanto a las restricciones 🔍

¡Éxito! 🍀

**Comment by dedarritchon** [comment]
A que te refieres con editar esa parte del script? que lscript? el que genera los archivos? no me queda claro

**Comment by dedarritchon** [comment]
A que te refieres con editar esa parte del script? el que genera los archivos? gracias @rihanuch

**Comment by rihanuch** [comment]
@dedarritchon que puedes cambiarle el nombre a ese archivo o simplemente ignorar ese caso!

Saludos ✌️

**Comment by Mariana-Ortega-del-Rio** [comment]
No entendí bien lo de cambiarle el nombre al archivo :D te refieres a cambiar el nombre del planeta Aiur en generar_archivos.py o donde? @rihanuch 
Gracias!!!
