### ISSUE TITLE
Ver Estado Entrenador y Ver Estado Campeonato no son interactivos -> no incluir "volver" y "salir"

### ISSUE THREAD

**Issue by 3rdPix** [IIC2233/Syllabus#126]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tal como dice el título; las opciones para ver el estado del entrenador, y ver el estado del torneo, solo son opciones para leer datos, no tienen ningún tipo de interacción extra. En este sentido, ¿puedo simplemente imprimir la información y devolver al jugador automaticamente al menu de entrenador? Ya que en el enunciado pareciese ser que insinuan que es un menu, porque muestra las opciones de "salir" y "volver". Pero esto es superfluo en estos dos casos: debería bastar con devolver al menu de entrenador y ya existen las opciones para salir y volver. Además, hace el flujo del juego más dinámico, sin la necesidad de que el jugador tenga que typear más de lo necesario (en este caso, solo eligiendo la opción para volver).

**Comment by Emiliax16** [comment]
Hola @3rdPix . Al inicio de la sección de `menus` dice que todo menú debe tener la opción de volver y salir, pero como bien tu dices, las opciones de ver estado del entrenador y ver el estado del torneo son sólo opciones del menú, no uno como tal. Por esto (y tomando en consideración que el enunciado no lo pide explícitamente), puedes implementar lo que dices, no sería necesario poner la opción de volver y salir desde estas opciones. Mencionalo en tu readme de todas maneras! Saludos 😸
