### ISSUE TITLE
Programa en ingles

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus#126]
Importa si hice todo el programa en ingles? Digamos, las clases, funciones, variables y cuando aplico guardar, se guardan en un archivo.csv, pero que los titulos estan en ingles. Pero se supone que el guardar y cargar estan dentro de mi programa y si no hay error en el formato u orden.

Ejemplos:
centro_urbano -> town_center
muralla -> wall

Ejemplo en archivo.csv:
centro_urbano,muralla
town_center,wall

**Comment by DCCollao** [comment]
Hola! 


Mientras tu función cargar sea capaz de soportar archivos .csv en español, que son los que utilizaremos para la corrección de la tarea, no debería haber problema! (Recuerda que podemos cambiar tus archivos por archivos propios nuestros, que siguen el formato dado en el enunciado)

Respecto a tu código, no hay problema con que esté en inglés.

Saludos y ánimo!
