### ISSUE TITLE
celdas_afectadas

### ISSUE THREAD

**Issue by fbehncke** [IIC2233/Syllabus#126]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, quisiera saber si el método celdas_afectadas de la clase Tablero debe filtrar si la pieza explosiva es valida o no o simplemente entregar el numero de celdas alcanzadas por cada pieza independiente de esto? Gracias:)

**Comment by roahoki** [comment]
Hola @fbehncke! lamento lo tarde de la respuesta. Sin embargo, en este caso queda a criterio tuyo verificar si es que la pieza explosiva que se indica es válida.

**Comment by roahoki** [comment]
hola @fbehncke 

Actualizando esta respuesta, este método recibe una posición(x, y) y luego hay 2 casos:
- Si en la posición hay una pieza explosiva, se debe retornar la cantidad de celdas afectadas por la explosión de dicha celda. Aquí hay que tomar en cuenta que un peón puede detener que la explosión continue en dicha fila/columna/diagonal. Aparte de eso, no importa si la pieza es inválida o no, solo queremos determinar cuantas celdas son afectadas por dicha pieza.
- Si en la posición no hay una pieza explosiva, se retorna -1

**Comment by sbarriag** [comment]
Aprovecho de preguntar acá si esta función considera el número asociado a la pieza explosiva, es decir, por ejemplo en el caso de que tenga una pieza vertical V2 por decir algo, cuento como celda afectada todo lo que esté en la misma columna antes de interponerse un peón o también tengo que ver que no me pase de ese 2 por ejemplo? que sería la suya mas una de arriba y la suya mas una de abajo por lo cual si arriba y abajo hay celdas en blanco su cant de celdas afectadas sería 3 porque no sigue contando? 
Muchas gracias
