### ISSUE TITLE
Coeficientes uso/eficiencia

### ISSUE THREAD

**Issue by cho19** [IIC2233/Syllabus#126]
Hola! Dos dudas:

1.) El coeficiente de uso, según enunciado, es la razón entre el tiempo total trabajado y el **tiempo total en stand by**. Mi pregunta es, ¿cuál es la fecha base para calcular el tiempo total en stand by? ¿El primer incendio para el cual se moviliza? ¿El primer incendio que se inicio en la base de datos (2017-03-01 11:11:00)? ¿O queda a criterio?

2.) Esta duda es mas conceptual: la tasa de extinción es la cantidad de pp que puede extinguir el recurso por hora, es decir, que la cantidad total de puntos extintos la podemos calcular multiplicando la tasa por el tiempo total trabajado, que luego se normaliza dividiéndola por la tasa de extinción (issue #84), y eso se divide por el tiempo total trabajado... es decir

               coef_e = ((tasa * tiempo_trabajado)/tasa)/(tiempo_trabajado) = 1...?

¿Hay una diferencia entre esos tiempos trabajados? Quizás uno incluye los tiempos de viaje (tiempo total) y el otro no (tiempo para calcular los pp_extintos). No se si soy yo el del error conceptual o en realidad esta planteado así...
Saludos y gracias de antemano

**Comment by gbordoni** [comment]
Una duda con respecto a esto; el tiempo trabajado también cuenta el tiempo de traslado o solo el tiempo que el recurso esta en el incendio?

**Comment by iqacevedo** [comment]
Hola!

@cho19 respecto a tu primera duda, tu decides cuando comienzas a contar, por lo que debes anotar en tu README que decisión tomaste. Respecto a la segunda pregunta, tu decides si en el tiempo de trabajo consideras los traslados, de ser ese el caso el coeficiente quedaría tal como tu lo escribiste. Te recomiendo que cuando decidas como considerar el tiempo de trabajo, pienses en que tiene más sentido con la tarea y lo documentes en el README.

@gbordoni queda a tu criterio, pero debes especificar en el README como lo hiciste.

Saludos!
