### ISSUE TITLE
Cada módulo de nuestra tarea debe estar en su propia carpeta?

### ISSUE THREAD

**Issue by enzoacvi** [IIC2233/Syllabus#126]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! 😊
Estaba repasando las especificaciones de la entrega de la tarea, y en el punto 7 - Restricciones y alcances de Enunciado.pdf dice "Tu programa debe estar compuesto por uno o más archivos de extensión .py que estén correctamente ordenados por carpeta".
Mi pregunta es si esto significa que **dentro T1\ deben haber una carpeta para cada módulo** (T1\main\main.py, T1\red\red.py, T1\modulo\modulo.py), o **si está bien que dentro de la carpeta T1\ estén directamente los módulos .py de nuestra tarea**, junto con el readme y el .gitignore 🤔.

**Comment by IanZmen** [comment]
Hola, así esta correcto "T1\los módulos .py de tu tarea", no es necesario añadir una carpeta por cada modulo. Saludos
