### ISSUE TITLE
Modificación de archivos

### ISSUE THREAD

**Issue by emneely** [IIC2233/syllabus#126]
Hola!

No entiendo a qué se refiere con que los archivos estáticos pueden cambiar, puede cambiar el orden de las cosas? Por ejemplo, en vez de ser Nombre,Tipo,Hielo me pueden poner Tipo,Nombre,Hielo y mi programa debe ser capaz de leerlo? 

Siempre van a venir con título los archivos? Me refiero a el nombre de cada columna, como "Nombre"   "Hielo"   "Rocas", y esos nombres pueden cambiar? O van a ser los mismos siempre

Muchas gracias!

**Comment by DCCollao** [comment]
Hola! 

- Con que pueden cambiar nos referimos a que al momento de revisar, no se utilizaran exactamente esos archivos para probar tu código, pues podemos agregar nuevos contrincantes, pistas, pilotos y vehículos.

- El orden de las columnas puede cambiar, tal como lo mencionas. En lugar de tener "Nombre", "Hielo", "Rocas"; estos podrían venir ordenados de cualquier forma y tu programa debe ser capaz de leerlo en cualquiera de ellas.

- Los títulos de las columnas sí serán los mismos siempre

Quedo atento a cualquier otra duda!

**Comment by Alonsortega** [comment]
El archivo "parametros.py" no se cambia cierto? hay parámetros adicionales que he estado agregando al archivo pero ahora tengo la duda de si ese se modificará o no

**Comment by DCCollao** [comment]
Hola!
Puedes y, de hecho **debes** cambiarlo agregando los parámetros que usas en tu tarea. Cualquier parámetro hardcodeado que debiese haber estado dentro de `parametros.py` significará un descuento en tu nota.

Éxito!
