### ISSUE TITLE
Jugador ya usó bombas especiales y las selecciona de nuevo

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#126]
Hola!!! En el enunciado aparece que el jugador solo puede usar la bomba especial una vez. Mi duda es: si ya la usó y vuelve a elegir tipo de bomba especial. ¿Tengo que mostrar en pantalla que ya usó la bomba especial de la partida y pasar el turno, o pedirle que vuelva a elegir el tipo de bomba para ese turno?

Gracias!!

**Comment by YehudaGurovich** [comment]
Yo estaba pensando en eso! Pense en sacar de las opciones para el jugador, lanzar bomba especial pero no se si se puede.

**Comment by vicentevegaulloa** [comment]
Hola @denisseleiva y @YehudaGurovich !

El programa debería avisarle al jugador que ya uso su única bomba especial en el juego y pedirle que vuelva a elegir el tipo de bomba.

**Comment by denisseleiva** [comment]
Gracias!!!
