### ISSUE TITLE
Actividad 1. Archivos que se deben subir

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#126]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Para la actividad 1 solo se debe subir a git hub el archivo main.py? el resto de archivos no se suben?

**Comment by 3rdPix** [comment]
Hola @martinpint !

Esto es un tema duplicado. Puedes encontrar los detalles en la _issue_ [# 87](https://github.com/IIC2233/Syllabus/issues/87#issuecomment-2302142834). A modo de resumen: con el `main.py` basta para esta actividad.
