### ISSUE TITLE
Eliminar carpeta del repositorio

### ISSUE THREAD

**Issue by SantinoDaloy** [IIC2233/syllabus#1260]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, subí sin querer la carpeta de sprites a mi repositorio y quería saber como se elimina. Gracias de atemano

**Comment by lucasprato** [comment]
Hola @SantinoDaloy,
creo que lo más sencillo es que elimines la carpeta `sprites` (como se haría normalmente con cualquier archivo de tu pc) y haces `git add .; git commit -m 'mensaje'; git push`. Si revisas github ya no verás la carpeta `sprites`. Después simplemente vuelves a agregar a `T03` la carpeta `sprites`. Para que no te vuelva a ocurrir, **es clave que agregues al `.gitignore`esta carpeta**.

Éxito en la tarea!
