### ISSUE TITLE
Senales en el servidor

### ISSUE THREAD

**Issue by domja** [IIC2233/syllabus#1260]
Se pueden usar senales en el servidor? ya que son del modulo pyqt5 que es de interfaces y se supone que en el servidor no pueden haber cosas relacionadas a interfaces.

**Comment by gatochico** [comment]
Hola! Te recomendaría leer la issue #1154, ya que ahí se discute al respecto esa misma pregunta (spoiler: sí se puede, pero lee igual la issue, es interesante uwu).
