### ISSUE TITLE
Problema con main_ventana cliente

### ISSUE THREAD

**Issue by MariaBarias** [IIC2233/syllabus#1261]
Hola :)

tengo un error extraño cuando quiere instanciar mi mainWindow (no me habia psado en las otras tareas)..

cuando hago correr **self.setupUi(self)** me aparece el error...

File "C:\Users\Mari\Desktop\MariaBarias-iic2233-2020-1\Tareas\T03\Cliente\ventana_main.py", line 22, in __init__
    self.setupUi(self)
  File "<string>", line 321, in setupUi
TypeError: argument 1 has unexpected type '**QPushButton**'

No entiendo por qué me aparece ahora y antes no :(

**Comment by fdoflorenzano** [comment]
Hola @MariaBarias,

A alguien ya le pasó esto en la *issue* #792 y encontramos el problema. Mírala y analiza como se puede traducir en tu caso. Nos cuentas como te va.

Saludos.

**Comment by MariaBarias** [comment]
Si al final encontramos el error en el designer.. resulta que los botones tenian nombre en ingles y parece que alguno coincidia con alguna función existente en el programa.. por lo que cambiando los nombre de mis botones se arregló el problema. 

Gracias :)
