### ISSUE TITLE
Jugar carta

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#1262]
Quería saber si es correcto que inicie el juego, repartir cartas pasando la info de las cartas desde el "servidor" a cada "cliente", y guardar la info de estas cartas en los "cliente" para luego poder chequear si la carta jugada desde la "ventana principal" es valida sin tener que preguntarle al "servidor" sino que al "cliente". Importante destacar que si es valida obviamente se mandaría una señal al servidor para actualizar las cartas que están en juego.
En fin mi pregunta va como a si las reglas del juego deben ser preguntadas al servidor o estas pueden estar en el cliente

**Comment by matiasmasjuan** [comment]
Hola @dsepulveda3 !

No, no puedes hacer eso. Todo el manejo de validación de cartas (y en general toda la validación del sistema de juego) debe hacerse en el servidor.

Saludos y mucho éxito con la tarea! 😄
