### ISSUE TITLE
corrección avance en T03

### ISSUE THREAD

**Issue by camolina2** [IIC2233/syllabus#1264]
Hola! 
Me dijeron que no obtuve el bonus de la Tarea 3 porque en windows le aparecía un error en el main del cliente. La verdad no entiendo por qué les aparecía esto porque a mi me funcionaba perfecto, tengo mac. Me preocupa porque quizás hay algo mal en mi tarea que no me aparece a mi y les producirá problemas para corregirla. Además lo considero injusto porque si había realizado el avance :( . Qué puedo hacer?

**Comment by DCCollao** [comment]
Hola @camolina2!

Corrí tu tarea en windows y tuve problemas con el port seleccionado. El problema se solucionó al cambiar en tu main:
```
HOST = socket.gethostbyname("")
```


por 

```
HOST = socket.gethostbyname("localhost")
```.

Seguramente es el mismo problema que tuviste con tu avance, así que te recomiendo recorregir :smile:

**Comment by camolina2** [comment]
muchas gracias :D :D :D
