### ISSUE TITLE
Eliminar archivo que ya no se ocupa de repositorio

### ISSUE THREAD

**Issue by juanpaxd** [IIC2233/syllabus#1265]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo un archivo .py que ocupaba en la carpeta al cliente, pero cambie mi codigo de tal forma que ya no es necesario, ¿Puedo eliminarlo del repositorio con rm? No aporta nada y se vería mucho mas ordenado sin este archivo

**Comment by lucasprato** [comment]
Hola @juanpaxd, si es un archivo que creaste y ya no lo necesitas, sí lo puedes eliminar. Puedes usar el comando de consola `rm` o también seguir los pasos de la issue [#1260](https://github.com/IIC2233/syllabus/issues/1260). En ambos casos, debes hacer pushear tu repo si es que en commits anteriores ya habías subido el archivo que quieres eliminar.

Éxito!
