### ISSUE TITLE
Gritos DCCuatro en un mismo turno

### ISSUE THREAD

**Issue by francisca0308** [IIC2233/syllabus#1265]
Hola! Tengo una duda que me surge más que nada por comparar DCCuatro con UNO.
Si me pongo en el caso de que un jugador juega una de sus dos últimas cartas, quedando con una sola y grita, y justo después grita otro jugador porque intentó gritar antes que el primero, pero no lo logró; ¿qué sucede? Porque si lo pienso como el juego UNO, no pasaría nada debido a que no fue un error sino un intento fallido, por lo tanto, a pesar de que el segundo jugador teóricamente "grita mal", no se le aplica el castigo.

Es por eso que a mí no me haría sentido castigarlo. En este sentido, ¿se puede asumir que solo hay un grito DCCuatro por turno y este puede ser exitoso o no?

**Comment by gatochico** [comment]
Hola!

Como ese caso no está explicitado en el enunciado, no hay problema con que lo manejes a tu criterio. Sin embargo, recuerda añadir esta decisión en tu README, para que el corrector sepa que es una decisión de diseño tuya y no un bug :bug:

Saludos y éxito!

**Comment by Aloncarrasco** [comment]
> Hola!
> 
> Como ese caso no está explicitado en el enunciado, no hay problema con que lo manejes a tu criterio. Sin embargo, recuerda añadir esta decisión en tu README, para que el corrector sepa que es una decisión de diseño tuya y no un bug 🐛
> 
> Saludos y éxito!

En ese sentido, si me queda 1 carta y alguien grita dccuatro entonces tengo que sacar 4 y si yo grito dccuatro nuevamente tendría que sacar 8 cartas? (por que cuando yo grité me equivoqué) o puedo decidir y ponerlo en el readme?

**Comment by gatochico** [comment]
Depende de cómo lo quieras implementar. La pregunta inicial refiere a si se puede restringir que **por cada turno se pueda gritar DCCuatro una sola vez** para evitar casos donde alguien apretó _justo_ después de la primera persona que lo hizo y así no haya doble penalización. 

Si el caso que indicas cumple con esa condición (que estos dos gritos de dccuatro caigan en el mismo turno), entonces sí, el cómo manejarlo queda a decisión tuya.
