### ISSUE TITLE
Desconexión inesperada

### ISSUE THREAD

**Issue by furcelay** [IIC2233/syllabus#1266]
Hola!
En la pauta de distribución de puntaje hay un ítem que dice: *"Se pueden desconectar múltiples clientes, de forma inesperda, sin afectar el funcionamiento del programa."* ¿se refiere a que por ejemplo se caiga la conexión de internet del cliente?

Si es así, por lo que he probado el programa sigue normalmente cuando ésto ocurre, pero como el cliente no alcanza a avisarle al servidor, éste tarda al rededor de 20 segundos en saber que el cliente se desconectó (cuando ocurre un `TimeoutError`), cerrar su socket y avisarle a otros jugadores. ¿ésto está bien o se espera una respuesta más inmediata?

**Comment by fdoflorenzano** [comment]
Hola @furcelay,

Sí, a eso se refiere, y sí, me parece válido. Si el resto de las cosas funcionan entre esos 20 segundos, me imaginaría estaría bien. Ese tipo de comportamiento lo acotaría en el README para que lo tengan considerado en la corrección.

Saludos.

**Comment by furcelay** [comment]
Que bien, muchas gracias!!
Intenté bajar el timeut con `socket.settimeout()` pero eso causó que a veces los clientes se caigan solos, así que lo dejaré en los 20s por defecto.
