### ISSUE TITLE
problema con QPixmap

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#1266]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! me sale un error del tipo "QPixmap::scaleHeight: Pixmap is a null pixmap" pero no entiendo por qué, si defino bien la función, le hice push a mi repositorio, esta específicamente en el archivo "ventana_principal"

**Comment by rodrigobj99** [comment]
Hola @Natydlb !
Estuve revisando tu código y me di cuenta de que este error ocurre porque no le estas dando correctamente el path al Pixmap. En el caso de los dados, nunca llamas a la función `crear(self, mensaje)` y por lo tanto el path que les estas dando es nulo, por lo cual no encuentra el pixmap y te tira ese error.

Espero te sirva. Saludos!

**Comment by Natydlb** [comment]
hola muchas gracias!! hice ese cambio y persiste el error y pense que era porque en el diccionario los numeros estan como str y yo al agregarle a la funcion el parametro se lo agrego como int, cambie ese error transformando los intr a str, pero no paso nada :(

**Comment by rodrigobj99** [comment]
Hola @Natydlb !
Estuve revisando tu código y al parecer ya no ocurre este problema. En caso de no ser así avisame para ver como ayudarte.

Saludos!

**Comment by Natydlb** [comment]
hola! ya no ocurre ese problema creo pero de igual forma no funciona porque se cierran las pestañas al momento de apretar el botón de dados :( no cambian las fotos según el dado que salga
