### ISSUE TITLE
Generador de mazos.py

### ISSUE THREAD

**Issue by Araos827** [IIC2233/syllabus#1267]
Hola! cada vez que llamamos a la funcion sacar cartas se crea un mazo nuevo y se entregan las cartas solicitadas al azar? No se van acabando las cartas?

**Comment by fdoflorenzano** [comment]
Hola @Araos827,

En #1027 se preguntó por el término del mazo. Por favor revisa esa *issue* y si te queda alguna duda, estaremos atentos a esa *issue*.

Saludos.
