### ISSUE TITLE
Duda serialización

### ISSUE THREAD

**Issue by Araos827** [IIC2233/syllabus#1268]
Hola! puedo crear mi propia funcion de serializacion distinta a las que se usan para personalizar la serializacion en json y pickle?

**Comment by fdoflorenzano** [comment]
Hola @Araos827,

No queda muy clara la pregunta. ¿Te refieres a si está permitido en la tarea? ¿O preguntas si es posible? Si preguntas dentro de la tarea, como serializar objetos es cosa tuya, mientras logres convertir objetos en *bytes* para poder enviarlos entre objetos, con la excepción de las imágenes de cartas que tienen un formato especificado.

Quedo atento a una aclaración.

Saludos.
