### ISSUE TITLE
Problema con conectar señales

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#1269]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

hola! me sale este problema 'PyQt5.Core.pyqtSignal' object has no attribute 'connect' pero no entiendo por que:( ayuda porfis muchas gracias!

**Comment by cristozille** [comment]
Hola! Este error surge de vez en cuando por problemas con vscode. En general se soluciona cerrando y abriendo  el programa o bien corriéndolo desde la terminal del computador. Haz la prueba y si te sigue pasando has un push de tus archivos para mirarlo en mas detalle :)
