### ISSUE TITLE
Cómo hacer una linea en Qtdesigner

### ISSUE THREAD

**Issue by jtmeyer98** [IIC2233/syllabus#1269]
Hola, esta es una pregunta muy básica jajaj, pero como no encontré como hacerlo pregunto por aca.
Quiero hacer lineas en la sala de juego (como las que aparecen en la foto del enunciado).

¿Alguién sabe como se hacen?

**Comment by furcelay** [comment]
Hola!
Hay un Widget para eso (en realidad es un frame de ancho 0)

![2020_07_02_17_56_52_Window](https://user-images.githubusercontent.com/61999313/86412771-adc4fc00-bc8d-11ea-85d3-867e7d4da168.png)

**Comment by jtmeyer98** [comment]
Buenisimo gracias!
