### ISSUE TITLE
Reglas del sistema de defensa

### ISSUE THREAD

**Issue by connandiaz** [IIC2233/Syllabus#127]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! tengo una duda en respecto al alcance de las fichas explosivas y la definición de tablero:
El tablero en el enunciado para la figura 1 sale que es 4x5, pero en ese caso iría desde 0 al 3 y de 0 al 4, no coincide la explicación con la imagen.
Respecto a la ficha explosiva, sobre todo de la reina. Considerando la figura 2, la reina R3 toma incluso alcance de 4, discrepando de la explicación, ¿cuál de las explicaciones debería considerar como alcance? y ¿Cómo considero el inicio del alcance si el número es par?

**Comment by connandiaz** [comment]
¿Cómo considero el alcance si el número es par?

**Comment by Mcroquevielle** [comment]
Hola! Como se mencionó en la issue #87, ese tablero es de 5x6 (es un error de enunciado).
Con respecto a tu segunda pregunta, la figura 2 muestre todas las casillas a las que alcanza una **pieza tipo reina**, sin importar el número que lo acompaña (esto último hace referencia a la cantidad de celdas que tiene que destruir). Entonces, el alcance de una pieza "R3" podría ser 13 o 7 (como se ve en la figura 2), sin embargo, al poner los peones hay que limitar este número a 3.
Avísame si te queda claro.
