### ISSUE TITLE
Radio de la Bomba - T0

### ISSUE THREAD

**Issue by margavicunas** [IIC2233/syllabus#127]
Hola!
Tengo una duda sobre las bombas especiales en la T0. En la sección 5.3 se ejemplifican distintas bombas con distintos radios pero en los parámetros.py entregados el radio de la bomba es constante e igual a 3. ¿Con qué radio debemos calcular las explosiones? Estoy un poco confundida de si en la corrección piensan cambiar esos parámetros para ver si el código funciona igual o se van a mantener.

Gracias :)

**Comment by MatiasDuhalde** [comment]
Hola @margavicunas !

Si bien el archivo que les entregamos tiene el valor `RADIO_EXP = 3`, deben tener en cuenta que este puede cambiar, y que para obtener el puntaje completo en el apartado, su programa debe poder soportar cualquier valor de `RADIO_EXP` (la única consideración es que este siempre será un `int` mayor o igual que 1).

**Comment by margavicunas** [comment]
Yaa súper! Gracias por responder tan rápido y x la aclaración :)
