### ISSUE TITLE
Duda sobre accion entrenador crear objetos

### ISSUE THREAD

**Issue by armas01** [IIC2233/Syllabus#127]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo una duda si puedo utilizar la accion del entrenador crear objetos fuera de la clase entrenador, aun que el enunciado diga que es una "accion" que la entidad puede hacer. 

Esto ocurre ya que para el Menu de creación de objetos que creé, importa los objetos de una carpeta "entidades", la cual tiene un inicializador __init__, el problema es que dentro de la misma carpeta se encuentra la entidad entrenador, y, de añadir una funcion de crear objetos, se llamaría el menu de creacion nuevamente, causando un loop.

Alternativamente, puedo crear la acción del entrenador de crear objeto y utilizar objeto dentro del menu del entrenador?

saludos.

**Comment by Emiliax16** [comment]
Hola @armas01 . Para tener el puntaje completo en la correcta modelación de la clase Entrenador, la acción _crear objeto_ debe ser un método de la clase Entrenador, ya que el enunciado lo describe de esa manera, de tal forma que sea algo propio de cada entrenador y no una función externa. Debes modificar tu implementación para que no exista este loop en las importaciones de archivos, ya que este problema hace que no se pueda correr tu tarea. Saludos!

**Comment by armas01** [comment]
Y puedo dentro de la función de entrenador, llamar la clase pertinente que cree el objeto?

**Comment by panchouc** [comment]
Me sumo a lo que pregunta @armas01, me gustaría saber si es que yo cree algo aparte, llámese función, clase, o lo que fuere. Si lo puedo llamar dentro de la clase `Entrenador`, ya que siento que queda más limpio si delego las funciones a cosas exteriores y no al entrenador, que según yo no tiene mucho que ver con como funciona la creación de un objeto, solo interesa el que se pueda crear, pienso yo.

**Comment by Emiliax16** [comment]
Si se puede! lo importante es que se cumpla lo solicitado en los métodos correspondiente. Si necesitan crear una instancia de la clase Objeto dentro del método **crear_objeto** de la clase Entrenador, es completamente válido. Mientras se respete la modelación descrita en cada entidad del enunciado, pueden agregar y utilizar funciones extras sin problemas. Otro ejemplo es que en un método de programones, creen una función externa que sirva sólo para calcular cierto puntaje, así solo la llaman en el método correspondiente para obtener el número. Cosas del estilo estarían igualmente bien modelada. Saludos.

**Comment by Josefinafp** [comment]
Hola!!  Tengo una duda. El enunciado dice "Crear este objeto gasta GASTO_ENERGIA_BAYA de energía y tiene una probabilidad de éxito de PROB_EXITO_BAYA", esto significa que por yo querer crear un objeto (resulte o no) se le gasta la energía al entrenador, y que el resltado de la creación sea exitoso se debe comparar con una prbabilidad aleatoria?
O que es primero ver si la probabilidad es mayor y ahí disminye la energía del entrenador?

**Comment by Emiliax16** [comment]
Hola @Josefinafp . Para mantener de las issues, te pido que hagas una issue nueva con esa pregunta y pronto la responderemos! saludos 😺
