### ISSUE TITLE
Modulo datetime, como eliminar los microsegundos

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#127]
Para la tarea 1 se pide usar el modulo datetime para la recoleccion de recursos, mi duda es como puedo eliminar los microsegundos ya que en los ejemplos de planetas creados estos vienen sin microsegundos.

**Comment by IchottMano** [comment]
@ljrodriguez1 Hola!
Para responder tu pregunta primero hay que explicar que es lo que retornan algunos métodos de la librería *datetime*, para esto empezaremos con una de las funciones mas utilizadas:
```python
from datetime import datetime
datetime.now()  #Esto retorna un objeto de clase datetime.datetime
```
Como verás, si intentas imprimir el output de este código obtendras un output parecido a
> 2018-03-31 18:59:03.204807

Ahora, esta clase tiene un método especial que nos permite aislar la parte del tiempo (sin la fecha), el cual es
```python
from datetime import datetime
datetime.now().time() #Retorna un objeto de clase datetime.time, la componente de tiempo
```
Obteniendo un output similar a
> 18:59:03.204807

Pero ahora digamos que queremos eliminar la componente de microsegundos. Por suerte esta clase (datetime.time) tiene un método muy útil que nos permite setear cualquiera de estos valores como queramos, este método es replace().

```python
from datetime import datetime
datetime.now().time.().replace(microsecond=0)
```
Obtenemos el output
> 18:59:03

Finalmente, esto nos dice que un datetime sin microsegundos es tan solo un datetime cuyos microsegundos son iguales a cero.

Espero esto resuelva tu duda.
Saludos!
