### ISSUE TITLE
usar import * a un módulo que yo cree

### ISSUE THREAD

**Issue by BenjaRubio** [IIC2233/syllabus#127]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Si cree un modulo principal y otro que solo contiene funciones que quiero importar al principal, ¿puedo usar la opción import * para no tener que escribir todas las funciones? considerando que conozco el módulo al cual le estoy importando todo.
gracias!

**Comment by aaossa** [comment]
Hola @BenjaRubio , el uso de `from modulo import *` se considera una mala práctica, por lo que no puedes usar esa opción, y si lo haces tendrás un descuento 😅 Los detalles de esto se explican en el contenido "2 - modularización" de la semana 0 ❌❌❌ Si tienes hartas cosas que importar y te preocupa el largo de la línea, te recomiendo escribirla así:

```python
from modulo import (
    funcion1, funcion2,
    clase1, clase2,
)
# Obviamente si te cabe en una sola línea esto no es necesario
```
