### ISSUE TITLE
Menu preparacion de carrera

### ISSUE THREAD

**Issue by enzoyacometti** [IIC2233/syllabus#127]
¿Como hay que presentarle al usuario las pistas cuando debe seleccionar una?
¿como pista helada? ¿o por el nombre de la pista? ¿o el nombre junto con el tipo de pista?

**Comment by gatochico** [comment]
Hola! 

Queda a tu criterio el como presentar las pistas. Piensa que podemos probar con archivos que tengan más de una pista del mismo tipo, como el entregado por la tarea (Ej: Pista "A" y pista "B" son dos pistas diferentes, pero ambas de hielo), así que trata de ser lo más descriptivo posible!

Saludos y éxito :car: :racing_car:

**Comment by tomasalvarez13** [comment]
Tengo que suponer que las pistas que estan en el archivo pistas.csv son las unicas con las que van a correr el programa? O al momento de revisarlo probarán con otro .csv?

**Comment by eugeizquierdo** [comment]
Hola!
Con respecto a las pistas, podría haber dos pistas del mismo tipo y con el mismo nombre? Lo pregunto para saber si basta mostrarle al usuario estas dos características de las pistas para que escoja. 

Gracias!

**Comment by gatochico** [comment]
Puedes asumir que no ocurrira que hayan dos pistas con mismo tipo y nombre! (:
