### ISSUE TITLE
Avance tarea

### ISSUE THREAD

**Issue by FelipeLara00** [IIC2233/syllabus#1270]
Hola! Tengo una duda con el avance de la tarea 03. En el feedback me escribieron que no se actualizaban los nombre de los jugadores que se conectaban en la ventana de espera, sin embargo, en el enunciado sale "No es necesario implementar (para este avance) la revision de nombres validos antes de entrara la Sala de Espera, ni una actualizacion en vivo de los usuarios dentro de ella.
Se tenian que actualizar de otra manera o efectivamente no se pedia actualizacion de esta ventana?

**Comment by lily416** [comment]
Hola @FelipeLara00, ciertamente tienes razón con eso sale en donde se explica el avance, fue un descuido al momento de realizar la corrección de los avances, lo siento por ello. 🙇‍♀️ 

El proceso de recorrección del puntaje de los avances se realiza junto a la recorrección de la tarea, por lo que cuando salga el form de recorrección te invito a contestarlo y poner lo mismo que pusiste en esta issue.

Saludos y éxito con lo que queda de la tarea 👋😄
