### ISSUE TITLE
Mi programa no lee los bytes ceros

### ISSUE THREAD

**Issue by pedroriosg** [IIC2233/syllabus#1270]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (htps://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Estoy teniendo problemas al leer los bytes, específicamente después de agregar los bytes ceros a mi último chunk. El programa se queda "pegado" solo a veces, otras corre bien. No sé que puede estar pasando... Estaría muy agradecido si  me pueden ayudar. Mi código está en mi repositorio. (en el archivo `cliente.py` y `servidor.py`  en sus métodos `enviar` y `recibir`)

Muchas gracias!!

**Comment by rodrigobj99** [comment]
Hola @pedroriosg !
Estuve corriendo tu código y no encontré ningún error, espero que hayas logrado solucionarlo, de no ser así avisame para ver como solucionarlo.

Saludos!

**Comment by pedroriosg** [comment]
Hola @rodrigobj99 ! Lo pude solucionar. Muchas gracias!!
