### ISSUE TITLE
Sobre Host y Puerto, donde especificarlo

### ISSUE THREAD

**Issue by mpenalozag** [IIC2233/syllabus#1271]
Se que sale en el enunciado que el host y el puerto va en parametros.json . Pero cuando envie la tarea para que la revisen tengo que decirles que deben cambiar el host y el puerto ahi ?

Gracias de antemano

**Comment by tocococa** [comment]
Yo tengo el puerto como un número cualquiera más o menos alto, y para el host puedes dejar 'localhsot', que creo debería funcionar en cualquier equipo.

**Comment by jirarrazabal** [comment]
Hola! Debes poner los parámetros host y port en parámetros.json. Los ayudantes ya sabemos que se encuentran ahí, para cambiar los valores en caso de que no funcionen. Para saber que parámetros utilizar, te recomiendo ver la Issue #1041 . Mucha Suerte!

**Comment by mpenalozag** [comment]
Gracias ! Otra duda, era necesario para el avance tener parametros.json implementado ? Porque la persona que vio mi avance no pudo conectarse al servidor ya que en el cliente estaba consiguiente la ip con socket.gethostname() en el mismo código, mientras que el servidor conseguia la ip desde parametros.json, donde coloque el nombre de mi red.  Debería pedir recorreción de eso ?

**Comment by lily416** [comment]
@mpenalozag, para la corrección del avance no era necesario tener implementados los parámetros, pero debes tener ojo con el _host_ que usas para ejecutar el cliente y el servidor. 

En tu caso tu avance tenía dos _host_ distintos: tu dirección IP y la del corrector (ya que usaste `gethostname()`). 

Te recomiendo que para la entrega hagas lo que sale en este [comentario](https://github.com/IIC2233/syllabus/issues/1041#issuecomment-647706093), ya que permitirá que el programa funcione sin importar el computador en que se ejecute y te asegurará que el _host_ sea un parámetro.

Saludos y éxito en la tarea 👋🎴
