### ISSUE TITLE
Desconexión repentina

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#1272]
Hola. La desconexión repentina considera solo el caso en que un usuario jugando cierre su juego? O también por ejemplo que la la consola en donde esta corriendo el juego se caiga? Esto último no se como hacerlo :(

**Comment by jirarrazabal** [comment]
Hola! tu duda fue resuelta en la Issue #1252 . Suerte!!

**Comment by tedroppelmann** [comment]
Acabo de cachar que cuando se desconecta el servidor o el cliente la excepción que agarra es json.decoder.JSONDecodeError. Por qué pasa? :(
