### ISSUE TITLE
Escuchar distinta información en el cliente desde el servidor

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2233/syllabus#1273]
Hola! 😄  Si el cliente le manda al servidor un mensaje para iniciar el juego, el servidor puede mandar dos mensajes manejados de distinta forma (en dos métodos distintos) de vuelta al cliente? En verdad ya lo hice y, según yo, está escuchando solo un mensaje de los dos.

**Comment by fdoflorenzano** [comment]
Hola @beatrizacuna,

Sí, es completamente posible. Para saber porque no se reciben ambos, habría que revisar más afondo. Te recomiendo hacer un seguimiento de lo que se envía a un cliente y lo que va recibiendo, para que veas como aparecen. Fíjate en cosas como el orden en envió, los largos de mensajes, para ver si todo efectivamente cruza. Los *prints* pueden ayudar mucho en estos casos.

Saludos.
