### ISSUE TITLE
Logs del servidor

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#1274]
Hola! He estado investigando distintas librerías para hacer la tabla con los logs. el problema es que todas piratean la tabla de una y no se como hacer para que vaya imprimiendo de a una :( si alguien sabe me ayudaría mucho

**Comment by matiasmasjuan** [comment]
Hola @tedroppelmann !

No es necesario hacer uso de una ```librería``` en particular para hacer la tabla de logs. Puedes hacer uso de la clásica función ```print``` de python. Si deseas darle un formato ordenado semejante al del enunciado, puedes hacer uso del método ```.format()```, de tal forma que puedas establecer espacios y separadores determinados. Aquí te dejo una documentación que puede ser de utilidad: [Haz click aqui](https://pyformat.info/)

Mucho éxito con la tarea! 😄
