### ISSUE TITLE
Supuestos consulta 4 y enunciado consulta 3

### ISSUE THREAD

**Issue by ssoliva** [IIC2233/syllabus#1274]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la actividad y no encontré una *issue* similar a la mía (No existe todavía :sweat_smile:)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! 
En la consulta 4 se puede asumir que las secciones que no tienen subsecciones nunca tendrán doble salto de línea al principio? O es particular de este ejemplo?
Y en la consulta 3 se solicita por las posiciones del contenido de las subsubsecciones, pero en el ejemplo dado para verificar dan las posiciones del nombre de la subsubsección. Es error de enunciado o del ejemplo?

Gracias de antemano!

**Comment by aaossa** [comment]
Hola @ssoliva , ahora que actualizamos el enunciado, está resuelta tu duda? Si no es así, comenta acá mismo cuál es tu duda para volver a darle una mirada 👌 Ojalá la actualización del enunciado te haya servido. ¡Éxito con la actividad ✨ !
