### ISSUE TITLE
libpng warning: sBIT: invalid

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2233/syllabus#1275]
Hola mi programa ayer estaba cargando bien las imagenes pero ahora me tira ese error y ya no se cargan los sprites de las cartas he buscado un poco pero no encuentro nada que me indique bien que es el error

**Comment by Aloncarrasco** [comment]
Ahora mi programa carga bien las imagenes, pero me sigue saliendo libpng warning: sBIT: invalid, aunque no afecta en nada, no se que ocurre.

**Comment by fdoflorenzano** [comment]
Hola @Aloncarrasco,

No estoy completamente seguro, pero mirando en Google, puede ser que te tire el aviso porque hay un problema con los *bytes* al cargar una imagen en `QPixmap`. Este de alguna forma espera *bytes* que representen una imagen PNG, pero tal vez algo pasa en tu envió o recepción que altera levemente los *bytes* y provoque  el aviso. Revisa si todo se está recibiendo completo y no hayan alteraciones a los *bytes* originales.

Saludos.
