### ISSUE TITLE
Duda con output_esperado_4 

### ISSUE THREAD

**Issue by festelle** [IIC2233/syllabus#1275]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la actividad y no encontré una *issue* similar a la mía (No existe todavía :sweat_smile:)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Al hacer la consulta 4 me salen resultados que no están en los outputs esperados de test.py. Por ejemplo, además de salirme solo ('Etymology', 2520, 3855) también me sale como match la sección de 'see also'. Revisé si esta sección cumplía lo pedido por la consulta y sí lo hace. El output esperado está incompleto o tengo que adecuar mi consulta para que me entregue solamente lo que sale en el output esperado?

**Comment by PDominguezW** [comment]
Me pasa lo mismo

**Comment by SebastianFerra** [comment]
![image](https://user-images.githubusercontent.com/69606956/101963648-fd6d0380-3bed-11eb-86e2-60d0b0bb94a3.png)

**Comment by nico-sv** [comment]
+1

**Comment by pills-lira** [comment]
creo lo mismo! En ese caso, además serían further reading y external links, q tmpc tienen subsecciones o no?

**Comment by nicovsj** [comment]
Hola a todos!

Tienen toda la razón, esas secciones (_See also_, _Further reading_ y _External links_) cumplen con lo pedido por esa consulta. Voy a pedir que se corrija el ejemplo del enunciado lo más pronto posible. Disculpen la confusión!

Saludos!
