### ISSUE TITLE
Uso de locks

### ISSUE THREAD

**Issue by fieterovich** [IIC2233/syllabus#1276]
Hola!

Me queda una duda con uso de locks, que en la distribución de puntajes está pero no se hace mención en el enunciado, ni en el compilado de issues hasta donde vi. ¿Si el cliente y el servidor esperan las respuestas y envíos de cada uno es suficiente o **debo** hacer uso de la clase Lock de threading? No se me ocurre dónde implementarlo en realidad, quizá no he avanzado lo suficiente.

Saludos!

**Comment by KnowYourselves** [comment]
Hola @fieterovich!

El problema es que el servidor podría recibir mensajes de múltiples clientes **al mismo tiempo**. Luego, si como respuesta a esos mensajes los _threads_ de los clientes deben acceder al mismo recurso, esperamos que utilices _locks_ correctamente para lidiar con la concurrencia.

Éxito!
