### ISSUE TITLE
Orden de las listas act Bonus

### ISSUE THREAD

**Issue by pills-lira** [IIC2233/syllabus#1276]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la actividad y no encontré una *issue* similar a la mía (No existe todavía :sweat_smile:)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

 **Es relevante el orden de nuestro output para cuando testeen el código?**Porque el enunciado no dice nada sobre el orden en el que tienen que aparecer las subsecciones, subsubsecciones (etc) y las del código de prueba no tiene un orden concreto, es como bastante al azar.

**Comment by nicovsj** [comment]
Hola @pills-lira!

El orden de los resultados no es relevante, los tests estarán diseñados para que esto no influya en la corrección. No te preocupes por eso.

Saludos!
