### ISSUE TITLE
intalar pyrematch

### ISSUE THREAD

**Issue by mleon17** [IIC2233/syllabus#1278]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

[Describe tu problema de manera detallada, explicando qué estás intentando hacer y explicando los errores o problemas que has encontrado. Se recomienda agregar fotos cuando sea posible]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mleon17** [comment]
Hola, instale pyrematch desde la terminal pero me aparece el siguiente error al tratar de correrlo en jupyter 
![Captura de Pantalla 2020-12-12 a la(s) 14 56 23](https://user-images.githubusercontent.com/69523923/101991254-35c21f80-3c8a-11eb-92c6-9b6c720e8c98.png)

**Comment by nicovsj** [comment]
Hola @mleon17, 

La verdad no estoy seguro del problema que tienes. Intentaste instalar pyrematch desde jupyter notebook colocando:
`!pip3 install --upgrade pyrematch`?

**Comment by mleon17** [comment]
Lo instale en la terminal y lo corri en jupyter. Tengo el mismo problema cuando lo importo en vscode 
![Captura de Pantalla 2020-12-14 a la(s) 08 39 58](https://user-images.githubusercontent.com/69523923/102077372-f578b380-3de7-11eb-8131-f994b7ca435d.png)

**Comment by aaossa** [comment]
Hola, seguramente esto es porque estás probando en entornos diferentes. Lo
instalaste en la consola pero probaste en Jupyter y en tu IDE, así que
seguramente son versiones paralelas de Python, no "el mismo Python".

Prueba lo que respondieron más arriba: si vas a probar en Jupyter, corre el
comando en el notebook de Jupyter. Si ya instalaste la librería por medio
de la consola, ejecuta los archivos desde ahí. En tu editor intenta usar la
versión de Python que tienes en consola, ya que al parecer lo tienes
conectado a una distinta.

Intenta las ideas que dejé y avísanos cómo te va. ¡Éxito con la actividad
💪!

**Comment by mleon17** [comment]
Gracias ahi me funciono!
