### ISSUE TITLE
Consulta Desconexion repentina

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#1278]
Citando al enunciado: 

-  "Si es el servidor quien se desconecta, cada cliente conectado debe mostrar un mensaje explicando la situación antes de cerrar el  programa."

Este mensaje, ¿tiene que ser entregado mediante una ventana? o ¿con que sea entregado en la terminal es suficiente?

**Comment by gatochico** [comment]
Hola! 

Este mensaje debe ser mostrado mediante la interfaz (¿Con qué widget? Ahí queda a tu criterio), ya que este es el medio por donde se comunican los clientes con el programa.

Éxito en la tarea!
