### ISSUE TITLE
Caracteres especiales

### ISSUE THREAD

**Issue by dani-sschlack** [IIC2233/syllabus#1279]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la actividad y no encontré una *issue* similar a la mía (No existe todavía :sweat_smile:)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

hola, al tratar de buscar un título que contiene caracteres especiales (consulta 3) me encuentro con un problema, puesto que REmatch no lo está tomando en cuenta, ya trate con usar "\(carácter especial)" y "." en el PATRON pero aun así no me aparece, lo cual es muy raro ya que sí me encuentra los otros títulos pero justo ese no :c
El problema es con "(", ")", y "-" como parte del texto o segmento. Busqué en internet pero no aparece nada al respecto 🤔.

**Comment by nicovsj** [comment]
Hola @dani-sschlack ,

Me parece que lo que ocurre es que estás intentando hacer match con los caracteres que son especiales en la sintaxis de expresiones regulares de rematch. Por ejemplo, el `.` indica que se debe hacer match con cualquier caracter. 

Para hacer match con estos caracteres especiales, debes escaparlos (i.e. colocar un backslash `\` antes). Por ejemplo, si quieres obtener todos los puntos presentes en un texto puedes usar la consulta `!x{\.}`.

Los caracteres "reservados" de rematch son `.*+?(){}[]|\-`

**Comment by dani-sschlack** [comment]
hola, efectivamente era eso xd, muchas graciasss
