### ISSUE TITLE
Error del tipo: UnicodeDecodeError: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by rldelafuente** [IIC2233/syllabus#1279]
Hola! Al enviar cierta información, me sale indicado este error:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 502: invalid continuation byte`

Importante decir que a veces sucede este error y otras veces no.

Gracias de antemano!

**Comment by matiasmasjuan** [comment]
Hola @rldelafuente !

Una duda similar surgió en la issue #1225 . En general el problema se puede deber a múltiples causas. Puede ser por errores al aplicar los métodos correspondientes de serialización, o porque en un determinado momento estás mandando una cantidad inmensa de ```bytes```. En caso de ser esto último, intenta ver la posibilidad de envío de información a través de ```chunks```. De esta forma, no se sobrecargará el envió de información y lo más probable es que no ocurra este error.

Avísame si esto funciona, y mucho éxito con la tarea! 😄
