### ISSUE TITLE
Recomendacion para lineas sobre 80 caracteres

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus#128]
Me esta pasando que cuando uso programacion funcional, muchas veces se me extiende mucho el codigo y queria saber como seria una buena practica de segmentar esto.

**Comment by valerojasm** [comment]
Hola!

En general el formato que se sigue para poder mantener legible el código y dentro de los márgenes del máximo de caracteres de la línea es el siguiente:

1. Cuando Python detecta que toda tu sintaxis pertenece a una misma línea explícitamente (es decir, por ejemplo, cuando hay contenido entre paréntesis), en general se usa que cada paréntesis va en una línea separada y que cada elemento dentro de el va en una línea nueva indentada. Me explico:

```
def function(
  parameter1,
  parameter2,
  parameter3,
)
```

Esto te ayuda a *verticalizar* tu código y a que cada elemento sea más distinguible. Esta última *trailing comma* es muy usada también, de forma que si quieres agregar más elementos solo estarás editando una línea en vez de dos - útil en un futuro cuando alguien tenga que revisar cambios en distintas versiones de tu código. 

2. Cuando Python no puede detectar esto, en general se ocupa un `\` para separar el contenido. Por ejemplo:

```
text = 'Esto es un string \
  muy largo partido en dos líneas'
```

Te dejo más ejemplos [acá](https://realpython.com/python-pep8/#maximum-line-length-and-line-breaking), así puedes ver qué se recomienda por ejemplo cuando hay operadores lógicos, para los `import`, etc.

Espero haberte ayudado.
Suerte!
