### ISSUE TITLE
Más dudas sobre completitud de datos: objetos

### ISSUE THREAD

**Issue by 3rdPix** [IIC2233/Syllabus#128]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Es posible asumir que **siempre**, todos los entrenadores que el juego recibirá, tendrán al menos 1 objeto? sea cual fuere su tipo? esto es independiente de si luego utilizan tal objeto y se quedan sin ninguno. Pero al momento de crear el entrenador según los datos de `entrenadores.csv` podemos asumir que habrá al menos un objeto?.

De forma similar, en `objetos.csv` podemos asumir que siempre existirá al menos un objeto de cada tipo? es decir, que no vendrán solo Bayas, o solo Pociones, o solo Caramelos, o alguna combinación que descarte una de esas 3. ¿?

**Comment by Emiliax16** [comment]
Hola @3rdPix ! asume que utilizaremos los mismos archivos entregados, por lo que no es necesario preocuparse de esos casos. Saludos!
