### ISSUE TITLE
Properties en Diagrama de clases

### ISSUE THREAD

**Issue by pazanelli** [IIC2233/syllabus#128]
Hola, en el archivo 5-diagrama-de-clases de la semana 02 sale que un recuadro debe indicar atributos y métodos de una clase. ¿También las Properties deben aparecer en el recuadro?

**Comment by lily416** [comment]
Sí, debes indicar las _properties_ de tus clases.

Por lo general estas se declaran en los atributos de la clase y se indica si la _property_ tiene definido el _getter_, _setter_ y/o _deleter_.

Por ejemplo, basándonos en las clases **`Puente`**, **`WebPage`** y **`Email2`** del [material sobre properties](https://github.com/IIC2233/contenidos/blob/master/semana-02/2-properties.ipynb), obtendríamos los siguientes diagramas de clases:

![image](https://user-images.githubusercontent.com/26393515/64138764-63a08f00-cdcc-11e9-842d-d29f8dd3d0e6.png)

Ojalá quede claro 😄 
Saludos y éxito con tu tarea 👋🛵
