### ISSUE TITLE
Duda sobre parámetros especiales en el input de chat

### ISSUE THREAD

**Issue by RodrigoFritis** [IIC2233/syllabus#128]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda sobre un posible input ya sea en el chat individual o grupal. Si se llega a ingresar por ejemplo "Hola como estas\volver", como se supone que debería responder el programa? Saliendo, escribiendo la linea? 
Gracias

**Comment by aljara97** [comment]
Hola @RodrigoFritis, los comandos especiales solo son válidos si se ingresa **solamente ese contenido** en el mensaje, por tanto, no aplicaría el caso que estás especificando para ejecutar la acción.

Saludos y mucho éxito con tu tarea 😄
