### ISSUE TITLE
iterables

### ISSUE THREAD

**Issue by santiago3c** [IIC2233/Syllabus#128]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

Hola, que no entiendo por qué este "iterable" que creé sí funciona con for a pesar de que el iterador no tenga self, si me podrían ayudar por favor
![image](https://github.com/IIC2233/Syllabus/assets/142272696/37fd486d-65f8-48ae-8e39-8b06268d7b0b)

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by santiago3c** [comment]
ya entendí, es que no funciona iterar el iterdor ya que no se puede acceder a __iter__, pero el iterable continuará funcionando normalmente ya que no usa el __iter__ del iterador

**Comment by mskdancers** [comment]
Hola! Claro, tu iterable funciona con el for ya que estás iterando a partir del iterable, no del iterador. Si quisieras iterar con el iterador, de la siguiente manera:
```python
iterador = iter(a1)
for i in iterador:
    print(i)
```
Tu código no funcionaría, ya que el iterador no tiene implementado el método **iter**.

Lo otro es que tu iterador no tiene condición de término en el método **next**, por lo que se va a iterar infinitamente, como se puede ver en el error que te dio en la terminal.

Saludos!

**Comment by santiago3c** [comment]
gracias!
