### ISSUE TITLE
Duda con verificacion de largo del prograpost

### ISSUE THREAD

**Issue by FelipeSrojas96** [IIC2233/syllabus#128]
Hola, 

Supongamos que al verificar el largo del prograpost este es de 150 lineas. En ese momento que tengo que hacer, que el user ingrese de nuevo el prograpost o tengo que detener la operacion y volver al menu? (ademas de indicarle al user que esta mal el input)

saludos y gracias

**Comment by Tito0906** [comment]
Holaa @FelipeSrojas96, el enunciado especifica que debes indicarle al usuario cuando no cumple con los requisitos, por lo que debes indicar en cualquier caso la razón por la que el post no se creó. Lo que sucede después ojalá cumpla con los aspectos generales del enunciado, es decir, ser amigable con el usuario y permitir volver o salir cuando corresponda. Si llevas al usuario al menú de posts entonces está bien. Recuerda aclarar los aspectos que no aparecen en el enunciado y que quedaron a tu criterio en el README por si tienes alguna duda.
