### ISSUE TITLE
Modificar una galaxia

### ISSUE THREAD

**Issue by mvcavieres** [IIC2233/Syllabus#128]
En modificar una galaxia, cuando dice aumentar la tasa de minerales por segundo de los planetas no conquistados, se refiere a ¿aumentar la tasa de minerales para todos los planetas no conquistados?, o ¿aumentar la tasa de minerales para solo un planeta que no este conquistado?

**Comment by nachocontreras** [comment]
Es para todos los planetas no conquistados 😁

**Comment by Arcoirisky** [comment]
Hola! 
El usuario debe elegir el planeta a modificar. No son todos al mismo tiempo c:
