### ISSUE TITLE
sobre pérdida de información

### ISSUE THREAD

**Issue by jereyes4** [IIC2233/Syllabus#128]
Se supone que las acciones realizadas durante una sesión del programa se guardan en los csv cierto?
Asumo también que el formato de guardado debería ser el mismo que el que nos dan. Todo esto tiene sentido si se busca que abriendo el programa nuevamente se mantengan los cambios realizados antes. Pero, como anteriormente se mencionó en otras issues, se pierde información con que si un usuario es investor o trader, pero no he visto nada sobre el dinero que deberían tener guardadas las personas...
Acaso se pierde también cada vez que el programa se cierra?
Debo asumir que los usuarios inscritos anteriormente se deben tratar como usuarios nuevos y darle los 100000 DCC correspondientes?
Se consideran como no inscritos en ningún mercado?
Necesariamente esto no concordaría con aquellos que tienen asks y bids, entonces cuánto se asume que tienen de cada moneda? Lo justo y suficiente para pagar los asks y bids que tienen guardados? Eso sumado a los 50000 que deberían tener en teoría por haberse unido al mercado, o el máximo entre los dos?
Se debe calcular su dinero usando la historia de orders en orders.csv a pesar de que pueda no ser fiable porque falta información respecto a su estado de trader?
Los intercambios a traves del banco tampoco se tienen guardados en los csv para realizar esa operación en cualquier caso.

Debería yo hacer lo que se me ocurra con todo eso?

Ayuda 😩

**Comment by Hernan4444** [comment]
@jereyes4 en #106 se dijo lo siguiente: 

> No puedes modificar ningún archivo en primera instancia (osea manual), tu programa debe ser capaz de leer el archivo que nosotros les damos al inicio y luego queda a tu criterio si modificas, creas o eliminas algo del archivo o incluso si cambias el formato y sigues con ese para las siguientes ejecuciones pero si llegamos a volver a poner el archivo en el formato inicial, tu programa debe saber como enfrentar eso.

Es decir, tu tienes que pensar en una alternativa que logré resolver esos problemas y considere que el archivo inicial que les pasamos tiene el formato descrito en el pdf.

Saludos!!
