### ISSUE TITLE
Duda bombas especiales

### ISSUE THREAD

**Issue by camilapavesi** [IIC2233/syllabus#128]
Hola!
El enunciado dice que no puedo disparar en lugares donde ya he disparado. Esto se refiere a:
1) No elegir las mismas coordenadas que un disparo anterior?
2) Al usar una bomba especial, ninguna celda alcanzada por la bomba debe haber sido disparada antes?
Gracias! :)

**Comment by vicentevegaulloa** [comment]
Hola @camilapavesi !

Esto se refiere a que no puedes ingresar coordenadas donde ya hayas disparado.

**Comment by amahns1** [comment]
Hola!

Eso corre para las bombas especiales también? Si el jugador lanza una bomba especial a un espacio ya descubierto, la bomba tiene el efecto para las otras casillas o se avisa la jugador que debe seleccionar otra casilla?

Gracias!

**Comment by vicentevegaulloa** [comment]
Hola @amahns1 !

Como se especifica en la issue #147, si la **coordenada de origen** de la bomba ya fue atacada, entonces se considera invalida y se vuelve a pedir.
