### ISSUE TITLE
ACT1: Me corren bien los test, pero en el VS me sale que tengo un problema con cargar_animes

### ISSUE THREAD

**Issue by Atun-conn-mayo** [IIC2233/Syllabus#128]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Hola, perdón por la hora, pero en la actividad 1 cuando corro los test por la terminal todo me sale bien, pero en el VS me arroja el siguiente error: FileNotFoundError: [Errno 2] No such file or directory: 'data\\ejemplo.chan'
Ese error se ubica en la línea en la  que abro el archivo, pero es raro porque como dije antes en la terminal los test me cargan bien

**Comment by Agusrush21** [comment]
Seguramente es porque no tienes ubicada la terminal de VSC en la carpeta

**Comment by Hernan4444** [comment]
Hola @Atun-conn-mayo 

Tal como indica Agusrush21, es muy probable que si revisas la posición de la terminal de VSCode, esta no está dentro de la AC1, sino dentro de otra carpeta (Actividades, o el repositorio privado). Aquí, lo que siempre recomendaremos es abrir la terminal, posicionarla dentro de la evaluación en particular que te interesa (usando `cd`), y luego hacer `python3 ARCHIVO.py`, esa es la forma enseñada para ejecutar los archivos.

Por otro lado, necesito recordar que **VSCode no es la herramienta para ejecutar los códigos**, todo código python (y los tests) **siempre siempre siempre** deben ser ejecutados desde la terminal. VScode es solo una herramienta para programar los códigos. 

Esto lo menciono porque toda AC y tarea será corregida exclusivamente ejecutando por consola (ya sea porque se hará `python3 main.py` o se ejecutará los tests de la misma forma que indica el enunciado). En caso que entreguen una evaluación que funciona si se ejecuta desde VSCode, pero no por terminal, entonces la evaluación no está correcta. Dado que es muy probable que, para hacer que funcionara en VSCode, se usaron paths que no son válidos con la forma que el curso ejecutará los archivos.

Saludos! 🦖
