### ISSUE TITLE
Entrega Tarea

### ISSUE THREAD

**Issue by josevalenzuelam** [IIC2233/Syllabus#128]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
Hola! quería preguntar como se si mi tarea esta entregada. Solo debo actualizarla en mi repositorio?

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by IanZmen** [comment]
Hola, tras hacer un commit y push, el nombre del commit debe aparecer en tu repositorio de github justo al lado de tu nombre. Tambien puedes ver que en los archivos que actualizaste dice el nombre de ese commit a la derecha del nombre del archivo, lo que indica que ese archivo fue actualizado. Por último, puedes entrar a tu archivo y ver tu mismo si el archivo corresponde a la última versión.
