### ISSUE TITLE
property con listas

### ISSUE THREAD

**Issue by Mendez69** [IIC2233/syllabus#1280]
Holaa, implemente un property donde el value es una lista. El problema es que cuando se le hacen appends o pop a la lista no está pasando por el setter que le puse. Alguna idea para arreglarlo??

**Comment by KnowYourselves** [comment]
Hola @Mendez69!

Lamentablemente las properties no funcionan muy bien cuando se intentan hacer con una estructura de datos:(

Esto se debe a que el _setter_ de la property solo intercepta el cambio directo de la variable, por ejemplo "self.valor = algo", mientras que no se va a activar para cambios internos de la variable, como "self.valor[indice] = algo".

La única forma de lograr un comportamiento similar a properties con una estructura de datos, sería que crearas una clase que heredara de tu estructura de datos a eleccion e sobreescribieras método __setitem__. 

Éxiot!

**Comment by Mendez69** [comment]
> Hola @Mendez69!
> 
> Lamentablemente las properties no funcionan muy bien cuando se intentan hacer con una estructura de datos:(
> 
> Esto se debe a que el _setter_ de la property solo intercepta el cambio directo de la variable, por ejemplo "self.valor = algo", mientras que no se va a activar para cambios internos de la variable, como "self.valor[indice] = algo".
> 
> La única forma de lograr un comportamiento similar a properties con una estructura de datos, sería que crearas una clase que heredara de tu estructura de datos a eleccion e sobreescribieras método __setitem__.
> 
> Éxiot!

Oka muchas gracias!
