### ISSUE TITLE
Efecto carta +2 

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1281]
Hola! En la issue #1217  me dijeron que el método para robar las cartas debido a gritar dccuatro quedaba a mi criterio , quería saber si esto también es así  . lo que quiero hacer es abrir un pop up avisandole al jugador, que es victima del efecto de la carta +2 ,y en el mismo pop up darle las opciones de robar el acumulado o jugar una carta +2 si es posibe

**Comment by DCCollao** [comment]
Hola @RonaldoSosa!

No hay problema con que lo hagas de la forma que describes, pues de todas formas le das al jugador las dos opciones de comportamientos posibles para esa situación, y no se pide una forma específica de implementación en el enunciado.

**Comment by RonaldoSosa** [comment]
Entendido!!! Graciasss!!!
