### ISSUE TITLE
Error al encontrar "="

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#1281]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la actividad y no encontré una *issue* similar a la mía (No existe todavía :sweat_smile:)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
En mi código cuando quiero buscar "=" no tengo problema. Pero si quiero buscar  el "=" junto a letras me tira error.
Para encontrar el "=" uso ... y me funciona
Luego para encontrar junto a una letra uso ... Pero no encuentra ningun patrón

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by nicovsj** [comment]
Hola @enriquemolinare, 

No entiendo muy bien a lo que te refieres, dices que si colocas `!x{=...}` no encuentra nada? 

Puedes decirme explícitamente que es lo que haces y el mensaje de error que te sale? (sin colocar la consulta completa por supuesto, solo la parte que dices)

**Comment by stgoct** [comment]
Me pasa lo mismo! al buscar = no respeta si tiene dos, tres o cuatro, agarra algunos (siempre los mismos) titulos sin importar si son titulos, subtitulos o subsubtitulos

**Comment by nicovsj** [comment]
@stgoct creo que eso es más bien parte de la dificultad de la tarea más que un error de la librería. Tus consultas deberían resolver ese problema si las haces bien. Si tienes una duda más particular quizás te puedo ayudar. Mucha suerte!

**Comment by sbcorrea** [comment]
Hola, a mí me pasó esto cuando incluí los `=` dentro del principio o final del patrón. Dentro del `(^|)` o `($|)` no respeta la cantidad de signos `=` pero afuera de esos paréntesis sí 🤗
