### ISSUE TITLE
No me funciona la implementación de ^ y $ 

### ISSUE THREAD

**Issue by pedroriosg** [IIC2233/syllabus#1282]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la actividad y no encontré una *issue* similar a la mía (No existe todavía :sweat_smile:)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Por algún motivo mi programa no reconoce cuando uso los caractéres `^` y `$`. (consulta 1). Si me pueden ayudar estaría muy agradecido.

Muchas gracias

**Comment by nicovsj** [comment]
Hola @pedroriosg,

Puedes elaborar más sobre cómo no te funcionan esos caracteres? No te entrega resultado en una consulta que si debiese entregar resultado? 

Recuerda que esos caracteres hacen match con el inicio (`^`) y final (`$`) del texto.

**Comment by pedroriosg** [comment]
Si!, por ejemplo, si hago una consulta con el siguiente patrón:

patron = `r"==  History =="`, mi programa reconoce el patrón, y lo puedo imprimir.

Mi outpu de `test.py` se ve así.
<img width="435" alt="Captura de Pantalla 2020-12-13 a la(s) 22 06 26" src="https://user-images.githubusercontent.com/69609154/102029963-75befa80-3d8f-11eb-81e6-dcf9f67b0e71.png">

Sin embargo, si ocupo el siguiente patron:

patron = `r"^==  History ==$"`

no me arroja ningún resultado.

Mis patrones van con una `r` al inicio ya que busqué en google y si no lo uso, no me deja usar `\w`

**Comment by nicovsj** [comment]
Me parece que estas confundiendo `^` y `$` con inicio y final de línea. Esto es algo que en una librería de regex común se puede hacer (colocando un flag de evaluación), pero pyrematch por ahora no lo tiene soportado. Es decir, `^$` sólo hacen match con inicio/final **del texto completo** en pyrematch.

Si quieres hacer match con un salto de línea debes colocar explícitamente `\n` en tu consulta.

Saludos!

**Comment by pedroriosg** [comment]
Nico, perdón pero no entendí muy bien la explicación. Por qué estaría mal usar:

patron = r"^== History ==$"

para encontrar el patron:

patron = r"== History ==" ??

**Comment by nicovsj** [comment]
Porque si utilizas la consulta `^== History ==$` estas diciendo que vas a hacer match solo si el texto es exactamente `== History ==`. Esto no es el caso del texto de la tarea pues hay muchas más líneas en él (dado que es una página de Wikipedia completa).

Te explico lo que ocurre con otro ejemplo: imagina que tienes el texto `ve como se ve o no se ve`. Si haces las consultas:
- `!x{ve}`: vas a obtener los 3 `ve`s presentes en el texto.
- `^!x{ve}`: obtienes solo el primer `ve` como match.
- `!x{ve}$`: obtienes solo el último `ve` como match.
- `^!x{ve}$`: no obtienes ningún match. 

Espero que con eso quede más claro. 

````

**Comment by pedroriosg** [comment]
Perfecto muchísimas gracias!!
