### ISSUE TITLE
No termina de correr y no imprime nada

### ISSUE THREAD

**Issue by TMagini** [IIC2233/syllabus#1283]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la actividad y no encontré una *issue* similar a la mía (No existe todavía :sweat_smile:)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Me pasa que instale la librería `wikipedia` y cree un archivo para probar el código:

```
import wikipedia

# Solicitar el contenido de la página en Wikipedia para chile
texto = wikipedia.page("Chile", auto_suggest=False).content

# Imprimir los primeros 2000 caracteres
print(texto[:2000], '...')
```

Y en VisualStudio me sale que esta corriendo pero se queda así para siempre, y no me imprime nada, para ser más especifico se queda pegado cuando define la variable `texto`, ya que intenté poniendo un print debajo de la variable y nunca se imprimió.

**Comment by aaossa** [comment]
Hola @TMagini , si no me equivoco esa función depende de una conexión a internet, por lo que podría ser que no tenías conexión al momento de ejecutar el archivo o tu IDE no está autorizada a hacer ese tipo de consultas. En cualquier caso, ¿ocurre lo mismo si ejecutas el archivo desde la consola (no desde la de VS Code)? Avísame si ya pudiste arreglarlo o si te funciona esa opción 👌 ¡Éxito con la actividad 🙌 !

**Comment by TMagini** [comment]
Hola profe, efectivamente era una autorización de los escudos de mi antivirus y la navegación web, lo ejecutaba desde consola o vs y ocurría lo mismo, no descubrí como darle permiso pero si desactivo los escudos me permite usar la librería, muchas gracias!
