### ISSUE TITLE
Registro de nombres 

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1283]
Hola tengo una duda con respecto a la parte en la que dicen que el nombre no deba repetirse , lo que pasa es que esto es siempre que el código este corriendo??? me refiero a que por ejemplo se corre el código por primera vez se colocan los nombres x1 y x2 se finaliza la partida sin embargo en lugar de volver al inicio con el boton se cierra el programa ,la terminal supongo, y luego se abre nuevamente la terminal y se inician los clientes , al intentar ingresar los nombres de los clientes en esta ocasion se podrían ingresar los nombres de x1 y x2 o no , además en el caso de se de click en el boton volver al inicio que sucedería se podría volver a ingresar los nombres x1 y x2?

**Comment by DCCollao** [comment]
Hola @RonaldoSosa!

Con que el nombre no deba repetirse nos referimos a que dentro de la sala de espera todos los usuarios deben tener un nombre único. No es necesario que lleves un registro de todos los jugadores que se han conectado alguna vez.

En el caso que propones, sí se podrían ingresar nuevamente los nombres de x1 y x2 en la segunda ejecución del programa.

Espero que te haya quedado claro!
