### ISSUE TITLE
Gitignore

### ISSUE THREAD

**Issue by IvaniaArias** [IIC2233/syllabus#1284]
Si en mi carpeta T03 tengo dos carpetas, cliente y servidor, cómo hago para ignorar la carpeta sprites u otro archivo que está dentro de una de estas? He buscado pero no funciona :(

Creo que el enunciado tampoco he podido ignorarlo en tareas anteriores jaja no se por qué :(

**Comment by DCCollao** [comment]
Hola @IvaniaArias!

Para ignorar una carpeta dentro de la otra, escribes el path de la carpeta que quieres ignorar.

En tu caso, sería algo como:

`/cliente/sprites`

**Comment by IvaniaArias** [comment]
Holaa! 
No se sube el enunciado ni la carpeta __pycache__, todo lo de mas si :(

Esto es lo que tengo, gracias de antemano!
![Captura de pantalla (477)](https://user-images.githubusercontent.com/61998881/86448570-ee9c2f80-bce4-11ea-8473-2f3e1c014130.png)

**Comment by DCCollao** [comment]
Vi tu último commit y lo único que se modificó fue el `.gitignore`, no se subió/actualizó nada más :o 

Quizás te falta borrar los archivos que habías subido antes de corregir tu `.gitignore` y ahora agregaste.

Si no es este el caso, quedo atento!

**Comment by IvaniaArias** [comment]
Ahi sii!
Borré todo y lo subí de nuevo jaja Muchas graciaaas!
