### ISSUE TITLE
Logs: "Cliente se conecte o desconecte del servidor"

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#1285]
citando del enunciado:

- Un cliente se conecte al o desconecte del servidor, identificando el cliente. Para identificarlo, se le debe asignar un nombre o id al cliente al conectarse.

Este evento, ¿debe suceder cuando el cliente se conecta?, o cuando ¿el cliente "entra a la sala de espera (confirmando su nombre)"?

**Comment by gatochico** [comment]
Hola! 

Este punto refiere a cuando cualquier cliente se conecta al servidor y el server acepta la conexión (básicamente, en cuanto se ejecuta una instancia del cliente nueva). Si te fijas, en esa misma parte más abajo se toma la acción "El cliente trate de entrar a la sala de espera" como algo distinto.

Saludos!
