### ISSUE TITLE
Duda de '21st century' en su output_esperado_5 

### ISSUE THREAD

**Issue by jpidrovo** [IIC2233/syllabus#1285]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la actividad y no encontré una *issue* similar a la mía (No existe todavía :sweat_smile:)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el output_esperado_5 para '21st century' colocaron que las posiciones deberían ser ('21st century', 19348, 21728), pero he estado toda la tarde y siempre llego a que es ('21st century', 19348, 21727), que es una posición corrida en una unidad a la que presentan en la posición 3 de la tuple.
No sé si el error es mio, pero todos lo demás me funciona bien, por lo que quería sacarme la duda de si quizás tuvieron un error en el output que presentaron. La única diferencia es que la posición final de la tuple está corrida en una unidad, y de todos los demás no presento ese problema.
Muchas gracias y perdón si es error mío.

**Comment by aaossa** [comment]
Hola @jpidrovo , parece que el problema está en tu expresión regular 🤔 Te recomendaría imprimir unos caracteres adicionales en el texto para ver cuáles no estás capturando apropiadamente. Ya sabes los índices en los que se encuentra el contenido, así que prueba imprimiendo el texto, por ejemplo hasta el índice 21735, y contando cuáles caracteres son parte del siguiente *match* y cuáles del que estás imprimiendo. ¡Éxito con la actividad 💪!

**Comment by nicovsj** [comment]
@jpidrovo, puede que haya un salto de línea que no estás considerando. La recomendación de @aaossa está buena para ver si efectivamente es eso. 

De todas formas los test que aplicaremos serán tal que, si hay un índice "corrido" debido a un whitespace no considerado (un espacio, un tab o un salto de linea), se tomará como buena la respuesta. El archivo test.py que se entregó es rígido en este sentido y no los considera como buenos. Esto esta pensado para que sus expresiones regulares estén lo más pulidas posibles acorde a lo que se pide por enunciado. Pero creo que sería injusto si pierden puntos completos por whitespaces en la correccion misma, y por ende esa consideración. 

Suerte!
