### ISSUE TITLE
Pixmap de Carta en Bytes

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#1286]
<img width="1201" alt="Screen Shot 2020-07-03 at 11 11 05" src="https://user-images.githubusercontent.com/62016215/86481399-f1ffdd00-bd1d-11ea-97f9-aa509afcbf6c.png">
Hola, he estado buscando online como hacer setPixmap(QPixmap(path)) donde el path esta en bytes pero no he encontrado buenos resultados. ¿Como muestro una carta en bytes? He intentado 
`cardpixmap = QtGui.QPixmap().loadFromData(self.data).scaled(70, 100)` 
y mostrarlo haciendo 
`card.setPixmap(cardpixmap)` 
pero me da como error 
`TypeError: setPixmap(self, QPixmap): argument 1 has unexpected type 'bool'`.

**Comment by fdoflorenzano** [comment]
Hola @CataSudo,

Como sugiere el error, el método `setPixmap` no acepta un objeto *bool* que le entregas en `cardpixmap`. Eso indica que probablemente en esa variable hay un objeto *bool* en vez de un *pixmap*. Probablemente porque  `loadFromData` retorna un *bool*, como indica la documentación en la web. Separa la definición de `cardpixmap` en múltiples líneas y debería funcionar.

Saludos.

**Comment by CataSudo** [comment]
Hola! A que te refieres en multiples lineas?

**Comment by fdoflorenzano** [comment]
La definición la hiciste en una línea: `cardpixmap = QtGui.QPixmap().loadFromData(self.data).scaled(70, 100)`. Con múltiples líneas me refiero a que separes esas llamadas en más de una línea, para que no quede el resultado de la cadena en la variable `cardpixmap`.

**Comment by CataSudo** [comment]
Ahhh, ok! Intente eso, pero me muestra la carta vacia, le hago el drag y funciona bien, pero. al hacerle drop no puedo ver la carta. Me muestra un rectángulo blanco.

**Comment by fdoflorenzano** [comment]
Hola,

Me perdí, ¿el error original se arregló entonces? ¿Implementaste *drag and drop*? ¿Qué funciona bien? ¿Sale alguna vez la imagen en si?

**Comment by CataSudo** [comment]
El error original si, y el drag and drop funciona. El unico problema es que no muestra una imagen cuando se le hace drop

**Comment by fdoflorenzano** [comment]
Entonces ese es otro problema. Revisa si al accionarse el *drop* se ingresa contenido válido de imagen a cargar. Revisa que el tamaño de la imagen corresponda al espacio. Pueden ser muchas cosas si no indicas un poco más de detalle de como funciona.

**Comment by CataSudo** [comment]
Ahora funciono! Era el setScaled
