### ISSUE TITLE
No module named 'wikipedia'

### ISSUE THREAD

**Issue by sbvillalobosm** [IIC2233/syllabus#1286]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la actividad y no encontré una *issue* similar a la mía (No existe todavía :sweat_smile:)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Cuando ejecuto el archivo test.py me aparece el error de 
Exception has occurred: ModuleNotFoundError
No module named 'wikipedia'

Ya instalé pyrematch y wikipedia desde la terminal. He estado buscando por qué aparece eso pero no logro resolverlo. Volví a hacer pip3 install --upgrade wikipedia pyrematch en la terminal por si había escrito mal esto y cuando le pongo enter me aparece esto

![image](https://user-images.githubusercontent.com/62085874/102233575-313a7880-3ecf-11eb-8ac8-ece9b813fde4.png)

Tampoco sé por qué me sale eso:(

**Comment by aaossa** [comment]
Hola @sbvillalobosm , ¿cómo ejecutas normalmente los archivos? ¿Desde qué consola instalaste PyQt5? Pregunto porque idealmente hay que instalar las librerías (usando `pip`) desde donde uno las usará después, por ejemplo cmd (o la línea de comandos de Windows). Si instalaste PyQt5, tienes que repetir el proceso, ya que también lo instalamos con `pip`. Ojalá te sirva pero si no funciona eso, con tus respuestas puedo tratar de guiarte mejor 🙌 ¡Éxito con la actividad ✨!

**Comment by sbvillalobosm** [comment]
Hola! Casi siempre los ejecuto en vsc y a veces desde la powershell. Todas las librerías las instalo desde la powershell, pero al ejecutar archivos en vsc no he tenido problemas hasta ahora (intenté ejecutarlo en ambos y me arroja el mismo error). En vsc la terminal es "python debug console" (desconozco si esto afecta en algo).

**Comment by aaossa** [comment]
@sbvillalobosm podrías mostrar el *output* de instalar solamente `wikipedia`? Imagino que sería algo como `pip install wikipedia` o tal vez con `pip3` en lugar de `pip`

**Comment by sbvillalobosm** [comment]
![image](https://user-images.githubusercontent.com/62085874/102283150-8ea2e980-3f10-11eb-88af-500eca04271b.png)

Esta es la imagen desde la powershell y me sigue saliendo el mismo error :(

![image](https://user-images.githubusercontent.com/62085874/102283202-aaa68b00-3f10-11eb-840d-3b8f80d53a03.png)

**Comment by aaossa** [comment]
En base a la primera captura parece que ya se instaló la librería. ¿Podrías
ejecutar tu archivo desde esa consola? Quizás en tu editor estás usando
otro entorno (otra "versión de Python")

**Comment by sbvillalobosm** [comment]
Esto me aparece al ejecutarlo desde git cmd
![image](https://user-images.githubusercontent.com/62085874/102286169-7b931800-3f16-11eb-89c3-4adeee4bab74.png)

Esto desde el símbolo del sistema
![image](https://user-images.githubusercontent.com/62085874/102286237-a3827b80-3f16-11eb-98f3-0da7353f7f8c.png)

Esto desde la powershell
![image](https://user-images.githubusercontent.com/62085874/102286281-c14fe080-3f16-11eb-96db-7694d223b6e0.png)

Y esto en vsc
![image](https://user-images.githubusercontent.com/62085874/102286306-cd3ba280-3f16-11eb-99fb-ab8f773dd36c.png)

No entiendo por qué sigue apareciendo el error en todos :((((

**Comment by aaossa** [comment]
@sbvillalobosm solo se me ocurren dos cosas:

1. Quizás estás usando otra versión de Python al instalarlo, pero es difícil que así sea. Si estás corriendo los archivos con `python archivo.py`, intenta instalar `wikipedia` con `python -m pip install wikimedia`
2. Otra opción es que el error al instalar esté causando problemas todavía. Intenta forzar la reinstalación con el siguiente comando: `pip install --upgrade --force-reinstall wikipedia`

**Comment by sbvillalobosm** [comment]
Intenté lo segundo y ahora sí me corre en la powershell :) Muchas gracias! 😄
