### ISSUE TITLE
Recorrección no revisada

### ISSUE THREAD

**Issue by pabloist** [IIC2233/syllabus#1287]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Hola buenas,

DIsculpa me acaban de subir la recorrección de la T02 y veo que no me han revisado ni comentado la sección más grande que envié a recorregir y necesito saber con quién me puedo comunicar para ver el tema

**Comment by lily416** [comment]
Hola @pabloist,

Tal como se comentó en el anuncio de hace unos minutos, cualquier problema con la recorrección de una evaluación podrás apelar a ella en la **recorrección de última instancia** que se realizará este lunes 21 de diciembre, horario por confirmar. 

En esta instancia podrás comunicarte con tu ayudante corrector y revisar los puntos que no fueron considerados en tu recorrección. 

Saludos y que tengas un buen día 👋🍬
