### ISSUE TITLE
Carta de front-end a back-end

### ISSUE THREAD

**Issue by mariajoseguerrero** [IIC2233/syllabus#1288]
Hola!! 

Tengo una duda sobre el envío de la carta al jugarla. En el enunciado no me queda muy claro como se hace el envío de la carta desde la ventana al cliente. He estado tratando de convertir el pixmap a bytes, pero no me funciona con el único código que encontré en google. Lo que he estado haciendo para las cartas es que envío solamente los bytes de la imagen al frontend, no se si se puede mandar toda la info de las cartas (tipo, color e imagen) y tenerlas en el frontend (no para no tener que mandar toda la info desde el servidor, sino que solo para el proceso de "vuelta" desde la ventana hasta el cliente). Si no se puede, les quería pedir un consejo para hacer esta parte :( 

Gracias!! :D

**Comment by szabala** [comment]
Hola!
> En el enunciado no me queda muy claro como se hace el envío de la carta desde la ventana al cliente 
> 

Ojo que el _front end_ no tiene porque enviar cartas al cliente. Recuerda que el servidor es el que provee esto al cliente, y luego este envia la(s) imagen(es) de las cartas al front-end segun se tengan que ir mostrando. Ahora, si es que el _front end_ tiene que avisarle al cliente que carta se jugo, no es necesario que le envie toda la informacion de esta carta (color, tipo, imagen). Puede, por ejemplo, decirle que se jugo la carta X de su mano y el cliente revisa a que carta corresponde.

>  Lo que he estado haciendo para las cartas es que envío solamente los bytes de la imagen al frontend
> 
Esta bien hacer esto! El front end no tiene porque tener toda la informacion de las cartas, solo necesita las imagenes para poder mostrarlas.

Espero haber aclarado tu duda 😄

**Comment by mariajoseguerrero** [comment]
gracias!! voy a intentar haciendo eso
