### ISSUE TITLE
orden de mi lista

### ISSUE THREAD

**Issue by feliperojas123** [IIC2233/syllabus#1288]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la actividad y no encontré una *issue* similar a la mía (No existe todavía :sweat_smile:)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

holaaa buenas lei una isuue y sale que el orden de los outputs esperados da lo mismo la verdad, lo que resulta es quepara el output 5 me sale erroneo por ese orden, entonces lo que nose si es que a uds al revisar esto ese orden les da lo mismo, o en verdad hay que respetar ese orden. graciaaas

**Comment by nicovsj** [comment]
Hola @feliperojas123 ,

El orden de los resultados da lo mismo, en la corrección automática vamos a ordenar tus resultados, y de ahí los compararemos con la solución ordenada. No te preocupes por eso.
