### ISSUE TITLE
Información sobre la evaluación de ultima instancia

### ISSUE THREAD

**Issue by ppvergara** [IIC2233/syllabus#1289]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola buenas, se me habia olvidado que para poder aprobar el ramo debo tener sobre 4 tanto en tareas como en actividades, y por esta razón y por temas de tiempo decidí no hacer la tarea T03, debido a esto ahora debo realizar la evaluación de ultima instancia. Por esto quiero preguntar en que consistiria esta, ya que no encontré en ningun lado esta información.

Saludos, Pedro Vergara.

**Comment by aaossa** [comment]
Hola @ppvergara , esta evaluación los últimos semestres ha consistido en un examen oral con preguntas de distintas partes de los contenidos (intentando cubrir todos) en distintos niveles de profundidad. Digo que así ha sido los últimos semestres, ya que aún no definimos al 100% cómo funcionará este, pero lo comento para que tengas una referencia. En cuanto tengamos el formato definido e información adicional lo avisaremos 👌

**Comment by ppvergara** [comment]
Perfecto, muchas gracias. Y mi otra duda, es si esta tendra una nota que se promediará con la de las tareas, en mi caso, sera un puntaje que ayudará a subir alguna decima la nota o si simplemente será un aprobado o reprobado.

Saludos

**Comment by aaossa** [comment]
Eso se indicó en el anuncio me parece, pero es así: si apruebas quedas con la nota que tendrías si no estuviera el requisito de aprobar tareas y actividades por separado, mientras que si repruebas quedas con 3.9. Es decir, el examen de por sí no tiene nota, solo se aprueba o reprueba, mientras que la nota se ve aparte

**Comment by ppvergara** [comment]
Ok, gracias por la respuesta tan rapida.
