### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by martin-quevedo** [IIC2233/syllabus#1289]
Al mandar la información de la carta en el formato del enunciado al cliente, cuando el codigo hace el decode() del recv(largo del mensaje) me tira un memory error, llevo mucho rato buscando pq pasa esto y todavía no encuentro la razon,
subi el codigo actual al repositorio

**Comment by gatochico** [comment]
Hola! Busque un poco al respecto y parece que ese error pasa cuando le das un valor muy alto al método `recv`. En tu cliente, veo que haces lo siguiente:
- Hacer recv  de 4 bytes para saber el tamaño de lo que vendrá, y almacenar esto en una variable `largo_x` (o largo_y, largo_z, etc...)
- Haces recv de `largo_x` bytes para recibir de una sola vez toda la información que viene.

Ahora, si justo antes de hacer el recv de `largo_x` haces print(largo_x) (y así con todos los valores de largo), te darás cuenta que se imprime un valor muy grande. Esta es probablemente la causa del error. 

Para solucionarlo, te recomiendo modificar tu método que recibe bytes para que, en vez de recibir el mensaje completo en un solo recv de valor potencialmente alto, vayas recibiendo chunks de tamaño menor de forma iterativa hasta que hayas recibido toda la información y luego unes todos estos chunks para tener el mensaje original. (En la ayudantía de _networking_ del semestre pasado [2019-2](https://github.com/IIC2233/syllabus-2019-2/tree/master/Ayudantias/AY08)) hay unos buenos ejemplos de como implementar el recv iterativo.

Saludos y éxito!

**Comment by martin-quevedo** [comment]
muchas gracias!!
