### ISSUE TITLE
No he podido correr ningun test

### ISSUE THREAD

**Issue by bgonzp** [IIC2233/Syllabus#129]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Vi las issues, y al hacer lo que me decian igual no me funciona. No he logrado correr ningún test, aca hay un ejemplo de lo que escribo y de lo que me responde.
<img width="575" alt="Captura de pantalla 2023-08-30 a la(s) 18 13 05" src="https://github.com/IIC2233/Syllabus/assets/141947842/34377273-3df3-4f01-8a23-1e489756c988">

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by dvillas28** [comment]
Estas en el path incorrecto, haz ``cd tests`` en ese path ahi vas a entrar al directorio `tests`, donde estan todos los tests.
 saludos!

**Comment by bgonzp** [comment]
Perfecto muchas gracias ahí me funciono!
