### ISSUE TITLE
Formatos menus y  tablas

### ISSUE THREAD

**Issue by solebravo** [IIC2233/Syllabus#129]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, me surgió una duda respecto al formato en el que aparecen los menús y las tablas, esto deben ser con tal formato (el titulo y las rayitas) o es libre? porque no entendí muy bien como se hacia para espaciar los outputs para que quedaran como tabla.
Muchas gracias y saludos

**Comment by martinjaraf** [comment]
Hola! Tal como dice en el enunciado el diseño de los menús que aparecen ahí son referenciales, así que puedes mostrarlos como tú desees, lo importante es que tenga toda la información que se pide.

**Comment by solebravo** [comment]
Muchas gracias! De todas formas hay algún recurso donde pueda revisar como se crean eso tipos de separaciones? tengo el recuerdo que hablaban un poco de eso en los contenidos de las semana 0, pero no se si hay algún lugar parecido o si se te ocurre como buscarlo para encontrar la información en google, que la verdad no se me ocurre alguna como "palabra clave" :)

**Comment by martinjaraf** [comment]
Puedes encontrar como mejorar la impresión de string en contenidos dentro la [semana-00/4-strings](https://github.com/IIC2233/contenidos/blob/master/semana-00/4-strings.ipynb).
