### ISSUE TITLE
Tamaño maximo grid

### ISSUE THREAD

**Issue by jchamorrou** [IIC2233/syllabus#129]
Hola, puede ser medio ridiculo, pero hay que contar en los casos que el jugador quiera jugar con mas de 26 columnas y por ende falten letras? Habria que implementar un tipo A, AA , AAA o podemos asumir que nadie va a querer jugar en un tablero asi jajajaj 
gracias de antemano

**Comment by DomingoCarvajal** [comment]
No soy ayudante, pero el enunciado dice el tamaño máximo y mínimo de columnas y filas.

**Comment by vicentevegaulloa** [comment]
Hola @jchamorrou y @DomingoCarvajal !

Confirmo.
