### ISSUE TITLE
valores por defecto en parametros.py

### ISSUE THREAD

**Issue by GuilleStanke** [IIC2233/Syllabus#129]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, no entiendo muy bien el uso de parametros.py, hay que definir las variables del formato especificado con cualquier valor posible (elegido arbitrariamente por nosotros)??, a la hora de corregir, los ayudantes usarán otros valores para cada variable en parametros.py o los que definamos nosotros?

**Comment by SantiagoDLCB** [comment]
Que ocurre en el caso de que guardo una partida ya sea por DCCavaCava.txt o con el nombre que sea?. Debo almacenar tambien los valores de parametros.py? Por ejemplo que ocurre si guardo una partida cuyo parametros.py  define una meta de 200 metros y 10 dias totales, pero posteriormente cargo la partida habiendo modificado el archivos.py a 100 metros y 7 dias, que ocurre en ese caso?, se actualizan los parametros en el torneo cargado? Podemos asumir que no van a cargar partidas con parametros distintos?

**Comment by mpiavf** [comment]
Hola!  Puedes guardar los valores de los parámetros o utilizar los mismos del programa al correrlo. Queda a tu criterio que opción elegir, de igual forma, lo que decidas debes dejarlo claro en el README. 
Saludos!
