### ISSUE TITLE
Cargar Archivos

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#129]
Al cargar los archivos galaxias.csv y planetas.csv, ¿podemos asumir que estos archivos existen y no estarán vacios? En caso contrario, ¿existe alguna forma de revisar si no existe tal archivo y/o si éste está vacio?

**Comment by Arcoirisky** [comment]
Hola!
Puedes asumir que existen y no estarán vacíos :D Además, si existe una forma de revisar si existen y/o están vacíos 🙈 con la librería "os".

**Comment by santilaguna** [comment]
Buena Gracias!!

**Comment by Arcoirisky** [comment]
@santilaguna Algo que no comenté antes 😱 (Me acaban de informar 😅) Los .csv siempre existirán PERO pueden no contener galaxias AUNQUE el Header de estos siempre existirá. 

Disculpa las molestias 😔

**Comment by santilaguna** [comment]
Oka doka gracias!

**Comment by Hernan4444** [comment]
@santilaguna si, el Header es la primera línea.(Disculpa la tardanza)

Saludos ✌️
