### ISSUE TITLE
Duda pistas.csv

### ISSUE THREAD

**Issue by prochotito-rises** [IIC2233/syllabus#129]
Hola! tengo una duda sobre algo relacionado a este archivo, tanto en 'hielo' como en 'rocas', el enunciado menciona que: 

"Si no es una pista de ____, el valor de este atributo no afecta ni debe ser leído. Puede que se omita o esté presente."

No entiendo si lo anterior se refiere a:

1. Al momento de cargar los datos de una pista, no se puede guardar en una variable (o atributo) el valor de 'roca' o 'hielo', si este no corresponde al tipo de pista.
2.  Se puede guardar en una variable (o atributo) el valor de 'roca' o 'hielo', si este no corresponde al tipo de pista, pero en tu código no debes usarlo porque es inútil.
3. En el archivo pistas.csv usado por los ayudantes, el valor de 'roca' o 'hielo' puede que no esté presente si no corresponde con el tipo de pista (en este caso, asumo que el formato que seguirá la línea de texto, será como la mostrada por el enunciado para está situación en particular)

Gracias por su tiempo!

**Comment by gatochico** [comment]
Hola! 

La frase que citas se refiere a dos cosas:
- Si el atributo no corresponde al tipo de pista (ej: atributo `rocas` en pista de hielo o viceversa), **este atributo no es de ninguna utilidad para dicha pista**. Ahora, respecto a si debes guardarlo y no utilizarlo, o no guardarlo ya depende de ti y como estés haciendo tu programa :speak_no_evil: Lo único que exigimos es que este atributo 'sobrante' nunca influya en la pista de ninguna forma. (Lo que sería una mezcla de la opción 1 y 2 que tu das)

- Tal como tu dices, a veces el valor de `roca` o `hielo` puede que no esté presente en la entrada de la pista si no corresponde al tipo de esta, y simplemente el espacio donde iría estará vacío (Habrán dos `,` seguidas).  Si, puedes asumir que en este caso el formato será como el del ejemplo del enunciado. (Así que tu opción 3 también estaría correcta).

Espero haber aclarado tu duda! :car: :racing_car:
