### ISSUE TITLE
ID civilizaciones

### ISSUE THREAD

**Issue by YoGandalf** [IIC2233/syllabus#129]
Las civilizaciones en juego son siempre por defecto 3?
Si quiero elegir la civilizacion DCC tengo que hacer que la civilizacion DCC que ya existia en el juego sea la mia o puedo agregar mi propia civilizacion DCC y jugar con 4 civilizaciones?
Y si es la segunda opcion la creo con los mismos atributos que la DCC antigua? Y le puedo poner el id que quiera?

**Comment by gatochico** [comment]
Hola! 
La respuesta a tu duda ya se contestó en la issue #64 , saludos!
