### ISSUE TITLE
Git no se "actualiza" al probar los tests

### ISSUE THREAD

**Issue by jx4jordan** [IIC2233/Syllabus#129]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Me habían corrido perfecto los tests, pero ahora, cuando hago cambios en el archivo, el git no lo detecta y corre el test sobre una version antigua. Incluso vacié el archivo y me seguía diciendo los mismos errores que antes, no se "da cuenta" que edito el archivo.

Ya probé reiniciando el pc, haciendo commit del archivo, y con otras funciones. 
Y sí, estoy en la ruta de archivo correcta.

**Comment by jorgee02** [comment]
Hola, a qué nivel de carpeta estás trabajando? Es decir, desde dónde tienes abierto VSCode.

**Comment by jx4jordan** [comment]
> Hola, a qué nivel de carpeta estás trabajando? Es decir, desde dónde tienes abierto VSCode.

Desde mi repositorio

**Comment by jx4jordan** [comment]
> Hola, a qué nivel de carpeta estás trabajando? Es decir, desde dónde tienes abierto VSCode.

No lo quería cerrar 🙃, desde mi repositorio lo tengo abierto

**Comment by jorgee02** [comment]
Trata de abrirlo a nivel de Tarea 1 si es que estás en eso

**Comment by jx4jordan** [comment]
Ahí lo arreglé, tenía dos archivos dccultivo y estaba editando sin querer el que no era. Gracias!
