### ISSUE TITLE
ABANDONAR_FRASE, o \salir

### ISSUE THREAD

**Issue by BValdes16** [IIC2233/syllabus#129]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, el usuario cuando decide abandonar un grupo, o volver al menú, ingresa el input "ABANDONAR_FRASE"/"VOLVER_FRASE" o ingresa el imput "\salir"/"\volver"?? En el caso del segundo, la idea es que el programa pueda funcionar con diferentes valores de ABANDONAR_FRASE o da lo mismo?

**Comment by matiasmasjuan** [comment]
Hola @BValdes16 !

Tal como sale en el enunciado:

![parametros](https://user-images.githubusercontent.com/48495638/113001547-474f0a80-9147-11eb-8e21-93a1748a51a3.png)

Por lo tanto, los **inputs** ingresados para abandonar un grupo o volver, deberán ser los mismos que los parámetros ***ABANDONAR_FRASE*** y ***VOLVER_FRASE***. Por lo tanto, deberás **importar** estos parámetros dentro de tu programa, de modo tal que el **input** que debas ingresar sea el **mismo** que el estos parámetros. De esta forma, la idea es que la forma de abandonar un grupo o volver esté dado por el valor de los parámetros ***ABANDONAR_FRASE*** y ***VOLVER_FRASE*** y no estén restringidos únicamente por "\salir" o "\volver", sino que puedan ser cualquier otro valor de *string*.

Espero haber respondido a tu pregunta, y mucho éxito con la tarea! :smile:
