### ISSUE TITLE
Cierre inesperado de ventana

### ISSUE THREAD

**Issue by josefeliuf** [IIC2233/syllabus#1290]
Como dice en el título, cuando pruebo el juego, a veces se cierra inesperadamente después de avanzar un par de turnos y no se registra ningún error. He intentado buscar de donde podría venir el problema mediante prints, pero no llegué a nada. Subí mi codigo por si alguien me puede ayudar :)
Gracias!

**Comment by lily416** [comment]
Primeramente, te recomiendo hacer lo que se indica en este [comentario](https://github.com/IIC2233/syllabus/issues/1256#issuecomment-653053522), ya que te permitirá ver los errores que causan que el programa se caiga. 

Si sigues teniendo dudas vuelve a comentar está _issue_ o crea una nueva donde se especifique más claramente el error.

Saludos y éxito en la tarea 👋🃏

**Comment by josefeliuf** [comment]
@lily416 Buenisima! ahí me aparece el error y no se cierra la ventana.
Muchas gracias!
