### ISSUE TITLE
No me funciona /s

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#1290]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1029)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! intente ocupar el comando /s por si solo pero no me funciono también intente ocuparlo hacia el otro lado \s y me produjo este error "libc++abi.dylib: terminating with uncaught exception of type std::logic_error: No mapping assigned to variable" no se como ocuparlo de otra forma :(

**Comment by nicovsj** [comment]
Hola @Natydlb,

Si quieres hacer match con whitespace debes utilizar `\s`. Por otro lado, el error que te sale es debido a que estás haciendo quizás  `match.span('x')`  o una función similar y tu expresión no tiene una variable `x` para capturar (por ej: `!y{\s}`).

Saludos!

**Comment by Natydlb** [comment]
muchas gracias!!!
