### ISSUE TITLE
Señal enviada dos veces al hacer click

### ISSUE THREAD

**Issue by sebaelsaca** [IIC2233/syllabus#1291]
Hola! Tengo un problema grande que no se como solucionarlo que es que cada vez que hago click en una carta, la señal se envía dos veces.  Mi carta es un clase heredada de QLabel de tipo:

class QlabelCarta(QLabel):
    clickled = pyqtSignal()

    def __init__(self,argumentos):
        QLabel.__init__(self)
        self.atributos = atributos x

    def mousePressEvent(self,event):
        self.clickled.emit()
        QLabel.mousePressEvent(self, event)

*Edité el código para mostarlo en el issue

**Comment by gatochico** [comment]
Hola! 

En tu archivo `main.py` del cliente tienes la línea `sala_de_juego.senal_enviar_carta.connect(cliente.enviar_carta)` puesta dos veces. Borró una de las líneas duplicadas y según los logs del servidor, se me dejó de enviar el mensaje de carta clickeada 2 veces.

Avísame si esto logra solucionar tu problema!

**Comment by sebaelsaca** [comment]
Era eso! Gracias
