### ISSUE TITLE
Problema con el envió continuo de mensajes.

### ISSUE THREAD

**Issue by nlewin99** [IIC2233/syllabus#1292]
Cuando se empiezan a enviar las cartas para formar las manos se generan problemas de lectura, ademas no logro leer la imagen para enviarla al front, acabo de hacer push para que se pueda ver.
Un ejemplo de los problemas de lectura son por ejemplo el color lo lee como rverde el tipo como r4 y cosas asi.
Ayuda

**Comment by fdoflorenzano** [comment]
Hola @nlewin99,

Mira, me ha costado hacer seguimiento de tus programas, porque me parece hay problemas de flujo tanto en cliente como servidor. Te recomiendo hacer por tu cuenta seguimiento mediante *prints* y otros para que revises que partes de tu código se ejecutan y que se envía y que no entre programas.

Por ejemplo, en servidor hay una sección donde se específica `msg_a_enviar["estado"] = "listo"`, que gatillaría en cliente que se muestre una ventana, pero el flujo en servidor es tal que no se envía `msg_a_enviar` con esa edición. 

En cliente al recibir cartas hay líneas del tipo `info = mensaje.decode()` y `info = json.loads(mensaje_completo)`, pero `mensaje` y  `mensaje_completo` están definidas en otra sección de flujo de tu programa, no es la información recién recibida. Eso tal vez está generando lectura erronea de mensajes.

Saludos.
