### ISSUE TITLE
No me coinciden las posiciones del enunciado. 

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#1293]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la actividad y no encontré una *issue* similar a la mía (No existe todavía :sweat_smile:)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Lo que pasa es que había hecho los tres primeros test y coincidían  perfecto con el output mostrado en el enunciado. Pero de la nada las posiciones que arroja mi código no son las mismas que las que están en el enunciado (y ahora los test me salen incorrectos). Y al momento de imprimir las posiciones del texto del enunciados me imprime algo que no es lo que es. ¿Puede ser que se haya actualizado la pagina de wikipedia y el orden cambio o algo así?. Que enserio llevo demasiado tiempo tratando de descifrar que es.

**Comment by TMagini** [comment]
Me ocurre lo mismo, siento que también se debe a la actualización de la página, antes tenia todos buenos y ahora en todos me tira error de coincidencia.

**Comment by jpidrovo** [comment]
+1

**Comment by Lord-Kelsier** [comment]
+1

**Comment by nicovsj** [comment]
Estimados, 

Efectivamente lo que ocurrió es que la página de Wikipedia de Chile fue actualizada, y eso hace que los tests fallen. Me comuniqué con el equipo docente para que se modifique test.py y se implemente este detalle de manera correcta. Así podrán seguir testeando sus consultas.

Dicho eso, den por seguro que la corrección automática se hará correctamente. Disculpen por no haber considerado este problema desde antes.

Saludos!

**Comment by jtagle2** [comment]
@diego-ayala-2000, @TMagini y @jpidrovo Se ha subido el `test.py`  actualizado.

**Comment by NelsonIMA** [comment]
Hola! Parece que se volvió a actualizar Wikipedia

Por ejemplo, en la consulta 3 me arroja esto:
![image](https://user-images.githubusercontent.com/42616922/102640740-b628ca80-4139-11eb-80ab-74ff6e67f943.png)

Siendo que sale esto en el test:
![image](https://user-images.githubusercontent.com/42616922/102640804-cb055e00-4139-11eb-82cb-8a3e6976c47f.png)

Gracias de antemano!
