### ISSUE TITLE
Seguir juego despues de gritar dccuatro

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2233/syllabus#1295]
Hola! tengo una duda, cuando uno grita erroneamente DCCuatro y roba cartas, eso cuenta como robar cartas normalmente y por lo tanto se acaba su turno? o despues de robar las 4 cartas puede jugar una carta? o es a criterio nuestro?

pregunto porque en la issue #1249 mencionan que se puede robar las 4 y despues jugar una carta +2, pero no me calza con el enunciado jajaj

**Comment by jirarrazabal** [comment]
Hola! Queda a tu criterio si el turno termina luego de robar las cartas por gritar DCCuatro incorrectamente, o si después de robarlas se debe seguir jugando en el turno hasta tirar una carta al pozo. Recuerda especificar estos supuestos en tu README. Suerte!

**Comment by maggiemunoz** [comment]
perfecto! otra pregunta, la persona que grita erroneamente debe robar enseguida? o puede esperar a que sea su turno?

**Comment by jirarrazabal** [comment]
Nuevamente queda a tu criterio, siempre y cuando el jugador se vea obligado a robar las 4 cartas antes de jugar su siguiente turno. Intenta que esto no interrumpa el flujo de tu juego.
