### ISSUE TITLE
Cambiaron las posiciones de los resultados, ¿qué hacer?

### ISSUE THREAD

**Issue by mt-garcia** [IIC2233/syllabus#1295]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la actividad y no encontré una *issue* similar a la mía (No existe todavía :sweat_smile:)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Antes las posiciones me calzaban con las del archivo ```test.py``` pero ya no y creo que es porque algo cambió en wikipedia. Mi pregunta es, para **corregir** el bonus, ¿esto estará considerado? Porque sé que se van a correr con testcase, pero no sé si estos testcases estarán actualizados 😞 
[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by nicovsj** [comment]
@mt-garcia, como tu dices, Wikipedia cambió la página de Chile en inglés, y eso hace que los test fallen hoy. Me comuniqué con el equipo docente para que se arregle test.py y puedan probar sus consultas. 

Sin embargo la corrección autómatica sí funcionará bien, esto ya esta contemplado, así que si te funcionaban los tests ayer entonces probablemente no habrá problema.

Saludos y disculpa por la confusión!

**Comment by Natydlb** [comment]
hola creo que aun no editan el test.py :( como puedo probar si mi codigo esta bien? :(

**Comment by panchotarud** [comment]
siii, como podemos probar el codigo si los outputs estan malos?

**Comment by jtagle2** [comment]
@Natydlb y @panchotarud, se subieron los tests actualizados.

**Comment by Natydlb** [comment]
Donde? 🥺 porque le hago git pull y no pasa nada

**Comment by aaossa** [comment]
@Natydlb se subieron los archivos al Syllabus, en la carpeta Bonus

**Comment by Natydlb** [comment]
perfecto! muchas gracias
