### ISSUE TITLE
Serializacion de imagenes e implementacion en el front end 

### ISSUE THREAD

**Issue by CristobalCarrascoD** [IIC2233/syllabus#1296]
Holaa! no entiendo que es lo que hay que serializar cuando piden que serializemos la imagen de las cartas, habría que serializar el path o la imagen misma? Pregunto porque lo que sea serializado, como lo ocupo después para cargar la imagen en la ventana, ya que creo que para poder hacer el pixmap y cargar una imagen en un label tendría que entregarle el path de la imagen, pero si este path es uno del servidor, no serviría donde se estaría cargando (ventana del cliente). Por esto,  en especifico, no entiendo como funciona todo esto, como se envía la imagen (que es lo que se envía) y como se carga esta información en la ventana.

**Comment by fdoflorenzano** [comment]
Hola @CristobalCarrascoD,

Por favor busca tus dudas en las *issues* antes de postear. Este tema está más que discutido. Por ejemplo, leyendo las siguientes se responde tu pregunta: #1039 #1139 

Saludos.

**Comment by CristobalCarrascoD** [comment]
Hola, perdón pero si había leído las issues pero no me había quedado claro mi pregunta con estas, por eso pregunte. Mas que nada mi pregunta va a que es la imagen que envía el servidor (un path? un objeto? un archivo? un diccionario?) antes de ser serializado como bytearray? osea que es lo que tengo que serializar? y después esto como lo ocupo en el front end para mostrarlo en la ventana, (con el loadfromdata de la issue  #1139?)

**Comment by tocococa** [comment]
La imagen la puedes leer directamente como bytes desde el path donde está guardada y enviar eso. Otra alternativa sería cargar la imagen como un QPixmap y después enviar el QPixmap como un QByteArray, o cargarla a algún otro objeto que te acomode y pasar ese objeto a bytes.

Con lo que tienes que tener más ojo es que si no la cargas como bytes, vas a tener que serializarla de alguna manera, mientras que si la lees en forma de bytes la puedes pasar directamente a un bytearray y no necesitas serializarla.

**Comment by fdoflorenzano** [comment]
Hola @CristobalCarrascoD,

OK, entiendo, solo que no se entendía esa duda de tu pregunta original. Efectivamente es necesario enviar el contenido de la imagen completa, porque el cliente no debería tener acceso directo a las imágenes. Como cualquier archivo, una imagen se pueden leer en modo *bytes* para obtener su contenido completo en ese formato, y eso es suficiente ya que está listo para enviarse. Pero como ejemplifica @tocococa, hay alternativas porque se pueden enviar en forma de QPixmap ya cargado. También hay alternativas para de como cargarlo en *front-end* que depende de como lo envíes, como `loadFromdata`, o desde archivos, o directamente con un `QPixmap` recibido. 

Saludos.

**Comment by CristobalCarrascoD** [comment]
Ok muchas gracias! ahí me quedo mas claro
