### ISSUE TITLE
Cambiar de clase un label (a un a clase heredada)

### ISSUE THREAD

**Issue by stgosuarez** [IIC2233/syllabus#1297]
Hola, le quiero agregar un método a un label creado por qtdesigner. Y creé una nueva clase LabelAlternativo(Qlabel) que hereda de QLabel. 

¿Cómo puedo cambiar de clase (o de type) los Qlabels que crea qtdesigner al mi labelalternativo? 

Es mala práctica hacer label1.__class__ = LabelAlternativo ???

**Comment by gatochico** [comment]
Hola! 

En este [link](https://www.learnpyqt.com/courses/qt-creator/embed-pyqtgraph-custom-widgets-qt-app/) se habla de una forma de usar custom widgets en designer (que sería tu caso), podrías echarle un ojo a ver si te sirve. La alternativa sería que hagas todo tu diseño en designer sin tu widget, dejando el espacio donde debería ir vacío, y luego cuando haces todo el proceso de setup de la interfaz agregues el widget a mano mediante código (lo instancies y lo ubiques en la interfaz).

Sobre lo de cambiar la clase de la instancia, [en este hilo de stackoverflow](https://stackoverflow.com/questions/15404256/changing-the-class-of-a-python-object-casting), hablan al respecto, e indican que los mismos docs de python no lo recomiendan ya que podría dar paso a bugs. Por lo que preferiría tratar con las dos opciones anteriores primero. 

Saludos y éxito!
