### ISSUE TITLE
se cae python con una señal

### ISSUE THREAD

**Issue by CamilaArgomedo** [IIC2233/syllabus#1298]
mando una señal de back-end (cliente.py) a front-end y se cae el programa, uso en otra ventana una señal de la misma forma y funciona bien, sigo la misma idea que la hoja de contenidos que habla de front y back end, alguna idea de porque se cae python? ayuda :(

**Comment by SamWeinstein** [comment]
Hola! Podrías proveer más información respecto al problema? Como por ejemplo, cual es el error que te aparece cuando se cae el programa? Porque pueden haber muchísimas razones por las que se puede estar cayendo el programa, pero con la información que estás dando no es suficiente para poder ayudarte.

**Comment by CamilaArgomedo** [comment]
no tira error, me pide cerrar python y cuando lo hago dice "Terminated: 15"

**Comment by SamWeinstein** [comment]
Está la última versión de tu código en tu repositorio? Le daré una mirada para ayudarte.

**Comment by CamilaArgomedo** [comment]
en la ultima versión comente el error para poder seguir trabajando, nose si puedes ver las versiones anteriores, seria el ultimo que subí a la hora de publicar esta issue, sino se puede no importa, gracias igual!
