### ISSUE TITLE
Duda orden output

### ISSUE THREAD

**Issue by Gjescalante** [IIC2233/syllabus#1299]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la actividad y no encontré una *issue* similar a la mía (No existe todavía :sweat_smile:)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! mi duda es si el return en cada consulta debe arrojar las tuplas en el mismo orden que el output esperado, porque me tira incorrecto en la consulta 5, y son los mismos elementos solo que en otro orden :(.

**Comment by aaossa** [comment]
Hola @Gjescalante , me parece que esto ya lo preguntaron en https://github.com/IIC2233/syllabus/issues/1288. Si tu duda es distinta, pregunta de nuevo por acá mismo 👌
