### ISSUE TITLE
Duda con gitignore 

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#1299]
Hola yo para hacer el logo en mi ventana de Inicio creo una carpet con solo los logos en mi carpeta cliente la llamo carpeta_de_logos esta carpeta tambien debe estar en el gitignore????

**Comment by SamWeinstein** [comment]
Hola! No me queda claro, son logos creados por ti? O los logos que se entregan en la tarea? Si son los logos normales, debes ignorarlos. De todos modos, te recomiendo reconsiderar y repensar la ubicación donde quieres que se encuentren estos logos. 
Saludos!

**Comment by RonaldoSosa** [comment]
Si son los logos que estan en la carpeta sprite, es que en una issue dijeron que podia mantener la imagen de ellos en mi carpeta cliente más no el de las cartas

**Comment by SamWeinstein** [comment]
Claro, ya vi la issue a la que te refieres, entonces tienes las siguientes dos opciones:
1. Efectivamente dejar los logos (y sólo los logos!) en la carpeta client.
2. Ignorar los logos pero indicar en el README que archivos se deben mover y hacia donde moverlos.

Saludos!
