### ISSUE TITLE
Fechas del calendario

### ISSUE THREAD

**Issue by HenryBlairG** [IIC2233/Syllabus#13]
hoola

Tuve un problema para visualizar el calendario en la pagina .io del curso y me bajé el archivo. Lo que pasa es que en el archivo la actividad 3 es el 5 de abril, lo que me hizo preguntar si el jueves 29 de marzo no habrá actividad. Y en el caso de ser un error, el resto de fechas tanto de actividades, como de controles y tareas están correctas o también se desfasaron de la misma forma?

Gracias :)

**Comment by nebil** [comment]
Es jueves santo libre de Python. :innocent:

**Comment by HenryBlairG** [comment]
Muchisimas Gracias!!

Otra Duda: Me sale el examen el 6 de Junio y ese si creo que debe estar mal, dado que hay contenidos no evaluados, lo cual es contrario al propósito del mismo. De todas formas si estoy equivocado no hay problema 😄 

Gracias :)
