### ISSUE TITLE
Duda en la parte 4.2 de la actividad 0

### ISSUE THREAD

**Issue by ssya333** [IIC2233/Syllabus#13]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Duda

Estoy en la parte 4.2 de ejecución del programa y no entiendo bien el punto 1. Al usar la función crear_usuario(aquí), se puede elegir lo que va dentro de los paréntesis y dejar definido el True o False? O hay que dejarlo tal que dependa de cada test case?

Gracias:)

**Comment by Hernan4444** [comment]
Hola @ssya333 

En `aquí` puede ir `True` o `False`, dado que el tests que verifica la parte 4.2 de ejecución tiene las 2 respuestas posibles como correctas, por lo tanto puedes usar la que quieras y si está todo lo demás bien, el tests dirá que está correcto.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ

**Comment by ShoshiC** [comment]
Con respecto al mismo punto, para las demás funciones que se deben implementar, no me queda claro que debo poner en sus respectivos paréntesis :"(

**Comment by Hernan4444** [comment]
Hola @ShoshiC 

Justamente es parte de esta evalución formativa que logren transformar las instrucciones a código mediante la lectura de las funciones entregadas (y enunciado) + la experimentación con ellas dentro del `if __name__ == "__main__":`. Y ojo que solo se pide implementar 2 funciones, todas las demás funciones ya existen en `utils.pretty_print.py` y solo se pide aplicarlas en cierto orden, pero no hay que implementar más funciones.

Mi recomendación, es que veas cómo está implementada cada función para entender sus parámetros, y junto a eso darle una vuelta al contenido [0-contenidos-minimos](https://github.com/IIC2233/contenidos-2024-2/blob/main/semana-01-introduccion/0-contenidos-minimos.ipynb) para poder repasar lo que funciones, y con eso ir de a poco a poco intentando transformar cada instrucción del enunciado en un código `.py`

¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ
