### ISSUE TITLE
KeyboardInterrupt

### ISSUE THREAD

**Issue by Alonsortega** [IIC2233/syllabus#13]
Cuando en el spreadsheet con la distribución de puntaje se menciona que el menú debe ser a prueba de todo tipo de errores, ¿esto incluye el KeyboardInterrupt?

**Comment by KnowYourselves** [comment]
Hola @Alonsortega!

No, no incluye al `KeyBoardInterrupt`, hace referencia al uso normal del menú. Por ejemplo, si tu menú me pide ingresar un número entre 0 y 4 y yo le ingreso `"hola como estai"`, no debería presentar ningún error y pedirme `input` de nuevo.

Espero haberte ayudado!

**Comment by Alonsortega** [comment]
Gracias!

**Comment by KnowYourselves** [comment]
PD: Otro ejemplo es que al momento de ingresar las dimensiones `N` y `M` del tablero estas deben estar en el rango 3, 15 _inclusive_.

**Comment by Alonsortega** [comment]
Si!, todo eso ya esta hecho, solo tenía dudas con el KeyboardInterrupt. Gracias!

**Comment by mfortiz** [comment]
Hola,
¿Cuál es la ventaja de ocupar el método isdigit() para el menú comparado con un else (que continúe pidiendo el input hasta que responda lo que quiero)?

**Comment by KnowYourselves** [comment]
Hola @mfortiz!

Creo que no he entendido tu pregunta, podrías dar un ejemplo?

**Comment by mfortiz** [comment]
![image](https://user-images.githubusercontent.com/37163461/63036491-1abf7f80-be8b-11e9-83cf-8b70fd1c0ef0.png)
Me refería a qué cuál es la funcionalidad de isdigit()
