### ISSUE TITLE
Contenidos que entran en actividadad AF1

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#13]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Entran los modulos 0 y 1 en la actividad de la proxima semana o solo el modulo 0?

**Comment by pabloist** [comment]
Hola buenas!

Te comento que la actividad formativa 1 consiste en el contenido de Builts-in, es decir, los contenidos de la semana 1. De todas formas los contenidos que se hayan visto anteriormente, como los de la semana 0, son considerados pasados y pueden aparecer de forma indirecta en las siguientes actividades por lo que es necesario repasar dichos contenidos de vez en cuando.

Saludos! :)

**Comment by Ignacioislae** [comment]
Ya, Gracias!
