### ISSUE TITLE
¿Cual es la diferencia entre descargar y "clonar" un repositorio?

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#13]
Hola!  buscando como descargar un repositorio desde la página del curso me encontré con este _issue_ (https://github.com/IIC2233/syllabus/issues/4) en el que se indicaba como clonar uno. Sin embargo encontré también la opción para descargarlo como `.zip`, y me di cuenta que el contenido era el mismo. Pero buscando por Internet encontré una página que decía que las funcionalidades entre clonar y descargar un repositorio no eran las mismas, y la verdad no entendí muy bien la razón de esto porque usaban términos relacionados con GitHub que aún no conozco :( . ¿Es muy importante este diferencia para el curso?

**Comment by tomasgv** [comment]
¡Hola @Gsalinas1506!

Aunque descargar y clonar un repositorio parezcan acciones similares, tienen una diferencia fundamental: al **clonar** un repositorio estás haciendo una copia del historial completo de este, incluyendo la carpeta `.git`. Esto permite que sea posible usar comandos de Git tales como `git add` o `git commit`. Por otro lado, al **descargar** un repositorio solo estás descargando (valga la redundancia) los archivos del _commit_ en el que se encontraba el repositorio, pero sin la carpeta `.git`. Esto significa que no es un repositorio de Git local, y **no** se podrán usar comandos propios de Git.

Para efectos de actividades y tareas del curso, tendrás que usar comandos de Git para subir archivos a tu repositorio, por lo que querrás clonar los repositorios en lugar de descargarlos.

¡Saludos! 🍉

**Comment by Gsalinas1506** [comment]
Yaa perfecto 😃 . Muuuchas Gracias!
