### ISSUE TITLE
WSL: "Interfaz no compatible".

### ISSUE THREAD

**Issue by javiverastegui** [IIC2233/Syllabus#13]
- **Sistema Operativo:**
Windows 10 Home Single Language 22H2
- **Programa a instalar:**
WSL (Ubuntu y/o Debian)
- Foto del error:
![imagen_2023-08-14_144851544](https://github.com/IIC2233/Syllabus/assets/106976943/95e6b9ae-93d2-4f4f-874b-b698262e4c14)
- Descripción del problema: Me dice que no puedo por el error 0x80004002 "Interfaz no compatible". Lo hago para tener la versión pedida de Python.

**Comment by javiverastegui** [comment]
Descargue primero WSL en Ubuntu, y me saltó el error. Luego lo reintente pero con Debian y me salto el mismo error.

**Comment by lily416** [comment]
Hola @javiverastegui 

Espero que te encuentres bien 😄. Con respecto a tu pregunta, estuve investigando un poco y si bien no logré encontrar lo que causa este error, aparentemente hay algunos comandos que puedes probar para ver si logras solucionar el error:

#### Opción 1
1. Ejecutar `wsl.exe --update`
1. Vuelve a ejecutar `wsl`

#### Opción 2:
1. Desactivar y volver a activar WSL en el panel de control:   
Panel de control > Programas > Activar o desactivar características de Windows > Subsistema de Windows para Linux

#### Opción 3:
1.  Desinstalar WSL
1. Ejecutar `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`
1. Volver a instalar WSL siguiendo los pasos de la guía de instalación.

#### Opción 4
1. Desinstalar WSL
1. Ejecutar `Get-AppxPackage |? { $_.Name -like "*WindowsSubsystemforLinux*" }` 
1. Después ejecutar `Remove-AppxPackage -Package "<packag-full-name>"`
1. Volver a instalar WSL siguiendo los pasos de la guía de instalación.


Lo que sí, es **MUY IMPORTANTE** que todos los comandos (tanto los anteriores como los de la guía de instalación) los ejecuten en la **PowerShell en modo administrador**, ya que de momento aparentemente los estás ejecutando desde la CMD. 

Ojala que algunas de estas alternativas te sirva para instalar WSL. Cualquier cosa, trataré de estar atenta a la issue.

Saludos y ojalá puedas instalar WSL :wave:🐢

**Comment by javiverastegui** [comment]
¡Logré solucionarlo !😁 
Eso si como observación. Use los dos primeros métodos. El primero me dijo de tirón que estaba con la ultima versión. Y con la segunda, me dijo que tenia que actualizar el sistema para que hiciera efectivo. De ahí recordé que tenia la actualización automática desactivada. Por lo que tuve que actualizar el computador de forma manual. Tal vez esa sea la situación que no me permitió que funcionará WSL.

¡Gracias por la ayuda! 😊
