### ISSUE TITLE
Cmd y Git 

### ISSUE THREAD

**Issue by aSPCA** [IIC2233/Syllabus#13]
Hola ! 

Me sucedio que clone el archivo privado de github, logre entrar al cmd y pude hacer que identificara la direccion de la carpeta contenedora del archivo, pero al momento de que hiciera git add _all me dice que
git no se reconoce como un comando interno o externo programa o archivo por lotes ejecutable

![image](https://cloud.githubusercontent.com/assets/26173407/23710307/08df0788-03fb-11e7-9b99-cc2fee7191d5.png)

Gracias de antemano

**Comment by arturodelreal** [comment]
Hola, el comando es git add --all. 
Salu2

**Comment by fvr1** [comment]
`git no se reconoce como un comando interno o externo`. Ese error es debido a que no tienes instalado git, o no está correctamente instalado. Por lo tanto, tu terminal no puede ejecutar ese comando. En esta [página](https://git-scm.com/) lo puedes descargar :)
