### ISSUE TITLE
Compilado Issues T0

### ISSUE THREAD

**Issue by matiasmasjuan** [IIC2233/Syllabus#13]
En la siguiente _issue_ encontrarás todas las _issues_ sobre la Tarea 0 que se han realizado hasta el momento, estas están divididas según diferentes temas.
Antes de hacer una nueva _issue_, revisa si tu duda ya fue realizada, así evitamos las _issues_ duplicadas. 😄

### Librerías permitidas, no permitidas y malas prácticas ✔️❌ 
1.  #12 
2. #42 
---

### Flujo del programa
1. 

---
### Tipos de Usuarios
1.  #30 

---
### Encomiendas
1. #50 
2. #62 

---
### Reclamos
1. 

---
### Menús
1. #35 
3.
---
### Archivos
* #### `parametros.py`
   1.

* #### archivos `csv`
   1. #26 
   3. #45 

* #### `.gitignore`
   1.
---
### Buenas prácticas
1.  #33 
4. #31 
5. #24 
6. #52 
7. #59 
8. #57 
---
### Otros
1. #29 
2. #40 
3. #60 
4. #65 
5. #64 
6. #61

**Comment by iangrosan** [comment]
Se puede utilizar breaks dentro del código? O es considerado una mala práctica?
