### ISSUE TITLE
Windows: Warning "The scripts are not on PATH" en la instalación de PyQt5, Jupyter y en el upgrade de pip

### ISSUE THREAD

**Issue by flocidae** [IIC2233/Syllabus#13]
### Prerrequisitos
* [ X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola! Me preocupé de marcar la casilla para agregar Python a PATH cuando lo instalé, pero cuando instalé PyQt5 (y PyQt5 tools), Jupyter e hice el upgrade de pip me aparecieron advertencias de que ciertos scripts no estaban en PATH y tampoco sé cómo agregarlos a este.
No sabía si esto afectaría el uso de las aplicaciones o no así que preferí preguntar :)

PyQt5 (el primer warning):
<img width="667" alt="Warning Pyqt5" src="https://user-images.githubusercontent.com/89219417/130341049-3cd87ebf-9703-4b82-80b6-5f4ac5f453c2.png">

PyQt5 tools (primer warning):
<img width="667" alt="Warning pyqt5 tools" src="https://user-images.githubusercontent.com/89219417/130341064-705ab336-dcf3-4113-a04d-b3e65013d7fb.png">

pip upgrade (primer warning):
<img width="672" alt="warning pip" src="https://user-images.githubusercontent.com/89219417/130341077-26867210-0380-4b33-b3b7-07dbbf2b5d66.png">

Jupyter:
<img width="959" alt="Warning jupyter" src="https://user-images.githubusercontent.com/89219417/130341082-573a78a2-61b3-4f10-a721-11ea2f4f2fa9.png">

Gracias! 🐧

**Comment by fernandosmither** [comment]
## Hola! Lo primero, bienvenid@ al curso.

Lo que estás viendo en la consola son `Warnings`, que sí bien es bueno considerarlas, en este caso **podrían** no ser relevantes. Sin embargo, para estar seguros, correremos unas pruebas para verificar que tu instalación de PyQt5 fue correcta y no te dará problemas más adelante en el curso. Si alguna de estas pruebas te falla, respóndeme en la issue y ya veremos cómo abordarlo.

### Prueba 1: Ejecutar un script que utiliza PyQt5
Con esta prueba veremos que efectivamente puedes utilizar PyQt5 sin problemas. Te pido que ejecutes el siguiente código en una IDE (en el caso que utilices una) y que también lo guardes en un `.py` y trates de ejecutarlo directamente (doble-click o correr en la consola `python {archivo}.py`
```python
import sys
from PyQt5.QtWidgets import QWidget, QApplication, QLabel


class MiVentana(QWidget):
    def __init__(self):
        super().__init__()
        self.setGeometry(200, 100, 300, 300)
        self.setWindowTitle('Mi Primera Ventana')
        self.label2 = QLabel('Todo está funcionando de maravilla =D', self)
        self.label2.move(10, 50)


if __name__ == '__main__':
    app = QApplication([])
    ventana = MiVentana()
    ventana.show()
    sys.exit(app.exec_())

``` 
Al correrlo debería aparecer la siguiente ventanita: 

<img src="https://user-images.githubusercontent.com/66154723/130480053-0b8e3f18-057a-4124-bcc1-763bfbd52590.png" width="300px">

### Prueba 2: Abrir designer

En el explorador de windows entra en la siguiente ruta: `C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\Lib\site-packages\qt5_applications\Qt\bin` e intenta ejecutar el programa "designer.exe" que se encuentra en la misma carpeta.
_NOTA: Luego de Users puse "Lenovo" ya que lo ví en tus pantallazos. Si otra persona está leyendo esta respuesta, debes colocar ahí **tu** nombre de usuario._

### Prueba 3: Abrir un Jupyter Notebook
[prueba_de_jupyter_notebook.zip](https://github.com/IIC2233/Syllabus/files/7033463/prueba_de_jupyter_notebook.zip)
Descarga el anterior archivo, descomprímelo, y [abre el jupyter notebook](https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/execute.html#:~:text=3.1.,-2.&text=To%20launch%20Jupyter%20Notebook%20App,new%20browser%20window%20or%20tab.)

Si logras pasar estas 3 pruebas, la instalación fue un éxito! 😄 
Coméntame por favor si te funcionó. Si tienes algún problema (no sabes como abrir el ipynb, no puedes guardar el archivo, etc) no dudes en comentarlo!

**Comment by fernandosmither** [comment]
Como nota final y para no solo responder a **qué** hacer, sino que al **porqué** de las warnings, resulta que como tú comentas, tu Python efectivamente está instalado en `path`. Lo que pip te marca en amarillo, es que PyQt5, las tools de PyQt5 y Jupyter Notebook son los que no están en `path`. Esto puede generar inconvenientes tales como el que quizás al escribir `jupyter notebook` en la CMD, este no se ejecute, al igual que si escribes `designer` este no abrirá.

Estos no son problemas graves y no debería afectar a tu rendimiento en el curso, sin embargo lo mejor es que puedas trabajar lo más cómod@ posible, y por lo tanto, respóndeme en especial si te funciona escribir `Jupyter Notebook`, de lo contrario arreglarlo no es para nada difícil. (Si a alguien más que está leyendo esto le ocurre, no dude en responder también y así hago un mini tutorial de como arreglarlo)

**Comment by fernandosmither** [comment]
Ahora sí, la última nota. La otra warning distinta es la de la versión de pip, la cual te marca que estás usando la 21.1.1 mientras la más nueva es la 21.2.4.

### De nuevo, **no te preocupes mucho por esto ya que no interferirá en el funcionamiento de la herramienta, pero sí es una buena práctica en computación en general el mantener el software lo más actualizado posible.**

En tu caso, instalaste la versión nueva, pero no la estás utilizando. Por lo mismo, me parece raro que no te la haya cambiado automáticamente. ¿Es posible que tengas más de una versión de python instalada?

**Comment by flocidae** [comment]
Hola! 🦭  Muchas gracias por tu respuesta :)
Lamentablemente no me funcionó ninguna de las pruebas 😭 lo siento jajaja, aquí abajo te especifico cada una:

## Prueba 1:
Ejecuté el código en PyCharm y me apareció este error:
<img width="704" alt="issue_pycharm" src="https://user-images.githubusercontent.com/89219417/130520894-5e2bb453-c1ce-4cda-8fd3-c642b034d663.png">

Y lo mismo en la consola:
<img width="396" alt="issue cmd" src="https://user-images.githubusercontent.com/89219417/130520971-cee78360-08eb-479c-8252-f59ae6529715.png">

## Prueba 2:
No logré encontrar designer en la ruta que me indicaste, me sale que no existe :( Pero sí me aparece en esta ruta (la encontré probando no más jaja):  `C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\qt5_applications\Qt\bin`. Pero logro abrir QtDesigner bien! (también puedo abrirlo si lo busco por el explorador de Windows)
<img width="608" alt="designer exe " src="https://user-images.githubusercontent.com/89219417/130521196-bc9a069c-5d1e-4d1c-be74-cab28453e11d.png">

## Prueba 3:
No pude abrir Jypyter, probé en la consola y no lo encuentra 😢 (extrajé el archivo que me indicaste en la carpeta "pruebas" en mi escritorio):
<img width="350" alt="issue jupyter" src="https://user-images.githubusercontent.com/89219417/130521315-53ce51b3-4c32-4c5f-b38a-0609c3bb6ea1.png">

De nuevo muchas gracias!! 🐧

**Comment by flocidae** [comment]
### Respecto a la última nota:
Creo que lo de la segunda warning se puede deber a que sin querer instalé jupyter antes de actualizar pip 😅 pero luego de actualizarla "volví" a instalar jupyter. Cuando lo hice, obviamente me aparecieron los mensajes de que ya lo tenía instalado.

Sobre la versión de python, antes había instalado la versión 3.9 y supuestamente la había desinstalado. El tema es que cuando busco las aplicaciones de python me aparecen ambas versiones:
<img width="380" alt="versiones python" src="https://user-images.githubusercontent.com/89219417/130523403-0052d009-03b1-4e17-b8cd-994a2d8dc9de.png">

**Peeeeeero** cada vez que intento desinstalarla me aparece como si ya lo hubiera hecho:
<img width="506" alt="desinstalar python 9" src="https://user-images.githubusercontent.com/89219417/130523502-7d4344fa-24e0-42d3-8231-ec9f37ed0c96.png">

**Comment by fernandosmither** [comment]
Ya, entiendo. Lo que te puedo recomendar por escrito ahora es que desinstales e instales todo en el orden correcto.

Si quieres escríbeme por discord y lo vemos de una, aunque si no puedes es posible que mañana hagamos una ayudantía de instalación y ahí puedas ir y preguntarlo.
