### ISSUE TITLE
Importar módulos

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#13]
Hola,
En la primera clase nos enseñaron a importar módulos de otros archivos .py, sin embargo no puedo encontrar eso en las slides. Agradecería me pudiesen explicar, ya que enseñaron que habían distintas formas para hacerlo, de forma que no era necesario correr todo el archivo al importar.

Saludos

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

Hay varias formas de importar módulos en Python, aquí hay tres de las opciones:

1. `import modulo`
2. `from modulo import funcion (o variable)`
3.  `from modulo import *`

Para este ejemplo hagamos uso del módulo `math`. 

Si haces uso de la opción 1. puedes acceder a **todas las funciones y variables del módulo** haciendo uso de `math.nombre`.

Si quieres usar solo una función, por ejemplo `cos`, la mejor opción es la 2., ya que al hacer `from math import cos` **solo cargas específicamente esa función** y puede ser utilizada simplemente haciendo `cos(numero)`. Sin embargo si usas esta opción tienes que tener la precaución de **no definir una función con el mismo nombre**, ya que si lo haces tu programa ejecutará tu función, no la del módulo `math`.

Debido a esto la opción 3. es ~~practicamente el diablo~~  _poco recomendable_, ya que al hacer eso importas **todas** las funciones sin tener en consideración que podrías sobrescribir.

**tl;dr:** la primera opción srive cuando usarán un módulo extensivamente, la segunda cuando usaran especificamente una cosa y la tercera solo sirve en casos extremadamente especificos.

### Bonus Track:

- Puedes importar múltiples módulos separandolos por coma:

```python3
import modulo_1, modulo_2, modulo_3
```
- Puedes importar múltiples funciones y variables separandolas por coma:
```python3
from math import sin, cos, pi
```
- Puedes renombar un módulo haciendo uso de `as`:
```python3
import ModuloConNombreDemasiadoLargo as m

m.funcion()
```

**Comment by mnbenimeli** [comment]
puedo renombrar una función del módulo con eso último?

**Comment by jmwielandt** [comment]
Sí puedes, acabo de hacer la prueba y funciona.

`archivo_2.py`
```python
def funcion_a():
    print("Hola mundo")
```
`archivo_1.py`
```python
from archivo_1 import funcion_a as funcion_b
funcion_b()
```
Pero al igual que los __star imports__ (`from module import *`) no lo recomiendo especialmente, pues no solo puedes estar sobreescribiendo algo sino también no saber qué función corregir en caso de tener algún bug.
