### ISSUE TITLE
Transición entre menús T00

### ISSUE THREAD

**Issue by Etienne99** [IIC2233/syllabus#13]
Hola!  En la sección 4.2 de la tarea aparece que una de las opciones del usuario debe ser "Volver al menú de inicio", por lo que entiendo que si selecciona esa opción se debe cerrar sesión. En la parte 4.3 una de las opciones del usuario es "Volver al menú anterior", por lo que entiendo que NO debería cerrar sesión, solamente volver al menú donde se pregunta si desea ver seguidores, prograposts o salir. ¿Estoy en lo correcto?

**Comment by aljara97** [comment]
Hola, lo que dices es un supuesto válido para el manejo de tu programa, aunque también volver al menú de inicio puede ser una opción razonable mientras se mantenga un flujo consistente entre los distintos menús del programa y le permita al usuario no tener dificultades. Te pido incluir este supuesto en tu README  y también citar esta issue, para que el ayudante que revise tu tarea tenga claridad de esto y no necesites una recorrección.

**Comment by Etienne99** [comment]
Ok, gracias por la aclaración :)
