### ISSUE TITLE
Error en vs code haciendo comentarios al código con # 

### ISSUE THREAD

**Issue by SebastianFerra** [IIC2233/syllabus#130]
hola, vscode me tira errores cuando hago comentarios con # pero solo a veces, por ejemplo en el archivo de la tarea 0, que tiene muchas lineas comentadas, me tira esto: (anexo código de main py sin editar, es decir sin código mío)

![image](https://user-images.githubusercontent.com/69606956/90989046-9dcae980-e565-11ea-81a4-45fddd9a0756.png)

si sirve de algo aquí está mi settings.json:

![image](https://user-images.githubusercontent.com/69606956/90989059-b6d39a80-e565-11ea-951c-9ef2e61801e8.png)

**Comment by FdoTorres1** [comment]
No soy ayudante, pero el error es por PEP-8 dado que no estás poniendo un espacio después de esos "#" si no me equivoco. Tienes instalada la extensión autopep8?

**Comment by MatiasDuhalde** [comment]
Hola @SebastianFerra !

Tal como dice @FdoTorres1 , este error es debido a que no hay un espacio después de `#`, por lo tanto para arreglarlo bastaría solamente con agregar uno. Sin embargo, este error sólo corresponde a una advertencia del linter que estás usando (pycodestyle), y no debería impedirte ni a tí ni a nosotros ejecutar el código.
