### ISSUE TITLE
Jugar en la galaxia

### ISSUE THREAD

**Issue by mvcavieres** [IIC2233/Syllabus#130]
En jugar en la galaxia, debemos dejar que el usuario elija cualquier galaxia aunque está ya tenga minerales y deuterio distintos de 1000, y hacer que esta galaxia tenga 1000 minerales, 1000 de deuterio y un planeta conquistado a elección del usuario?, o se le pide al usuario elegir entre las galaxias cuyos minerales y deuterio son 1000 y solo tienen un planeta conquistado?.

**Comment by ptflores1** [comment]
Hola !
Lee la issue #51, si no te queda claro pregunta denuevo.
Saludos !
