### ISSUE TITLE
Error al importar funciones de otros archivos py

### ISSUE THREAD

**Issue by fddelabarra** [IIC2233/syllabus#130]
ImportError: cannot import name '*' from '*'

**Comment by Tito0906** [comment]
Hola @fddelabarra! ¿Cómo estás importando las funciones?  Recuerda que la manera de importar elementos específicos de otros módulos es _from modulo import elemento_.  Si tu problema es otro por favor has push de tu código. 

Quedo atento.

**Comment by fddelabarra** [comment]
Por ejemplo 
from usuarios import iniciar_sesion, registrar_usuario

pero tambien intente:

from usuarios import iniciar_sesion
from usuarios import  registrar_usuario

**Comment by Tito0906** [comment]
@fddelabarra, ¿puedes subir el código que llevas a tu repositorio?

**Comment by fddelabarra** [comment]
si, ahora lo subo

**Comment by fddelabarra** [comment]
listo

**Comment by Tito0906** [comment]
@fddelabarra, tu problema se está produciendo porque ambos módulos se importan entre sí e interactúan fuertemente. Se explica con mayor detalle en esta issue https://github.com/IIC2233/syllabus/issues/108. 

Para solucionar tu problema, te recomiendo unir ambos archivos en uno solo (aprovechando que juntos tienen menos del límite permitido de líneas).  Copia todo el código del archivo usuarios antes del código del archivo manu.py y elimina los import que tenias en ambos.  

Por otro lado, si tienes tiempo trata de solucionar el problema de la interacción entre ambos módulos. Esto lo puedes hacer logrando que sólo uno de los archivos importe al otro (en este caso lo ideal es que sólo menú importe funciones desde usuarios)

Quedo atento por si tienes más problemas o dudas.

**Comment by fddelabarra** [comment]
ok gracias! intentare que no dependan una de la otra entonces
