### ISSUE TITLE
Duda enunciado menu

### ISSUE THREAD

**Issue by Jeremiah-PHP6** [IIC2233/Syllabus#130]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Al calcular la solución del tablero en la opción 3, hay que reemplazar la insancia del tablero original por la del solucionado, o solo basta con mostrarlo?

**Comment by Dominique236** [comment]
Hola!
En este caso, como por enunciado se revisa "que cada opción del menú llame, mediante código, a la función o método correspondiente", no importa si se actualiza la instancia del tablero o no porque **no se está evaluando el resultado en la parte de menú** (se evalúa con los test), por lo tanto **queda a su criterio reemplazar la instancia o solo mostrar el tablero**. Es importante notar que en la opción 2, _limpiar tablero_, si se indica por enunciado que se debe sobreescribir el tablero actual.
Cuéntame si esto resuelve tu duda 😊
