### ISSUE TITLE
Asumir bases de datos constantes?

### ISSUE THREAD

**Issue by bthompsonl** [IIC2233/Syllabus#130]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Holaa, me surgió una duda con respecto a cómo escribir mi código, ya que no sé si para programarlo tenemos que asumir que este debe ser válido para que se ejecute con cualquier base de datos arbitraria, o por el contrario, si es posible programar basado únicamente en los datos que nos dieron. Por ejemplo, en la base de datos **entrenadores.csv** hay sólo 16 entrenadores. ¿Puedo crear el programa en base a conocer los nombres, posiciones y cantidad de filas que tiene? ¿O tengo que hacerlo para que el código funcione dada una base de datos cualquiera? Por ejemplo un nuevo archivo **entrenadores.csv** que ahora contenga 17 entrenadores y todos los nombres distintos al anterior.

**Comment by 3rdPix** [comment]
En cuanto a la cantidad de datos, debería funcionar para una cantidad arbitraria; 17, 4, 100 entrenadores. En cuanto a la presentación de los mismos; es el punto del bonus **CSV Dinámico**. Para la tarea normal puedes asumir que las columnas son iguales en cualquier archivo que recibas; ahora, si implementas la posibilidad de que estas aparezcan en cualquier orden, entonces habrás realizado el bonus :)

**Comment by Emiliax16** [comment]
Hola @bthompsonl ! tal como dije en la issue [#128 ], puedes asumir que utilizaremos los mismos archivos entregados. Sin embargo,si quieres completar el bonus del enunciado, entonces si debes preocuparte de que el orden de las columnas pueden cambiar. Saludos!
