### ISSUE TITLE
[T01] Poder del Usuario

### ISSUE THREAD

**Issue by BibarelUsedFly** [IIC2233/Syllabus#130]
Según las instrucciones, los empleados de la ANAF pueden leer filas de las bases de datos de recursos, incendios y usuarios, pero
¿Pueden leer las contraseñas de otros usuarios?
No me hace mucho sentido.

**Comment by akaminetzkyp** [comment]
Según otro issue, si pueden leer las claves de otros usuarios.

**Comment by iqacevedo** [comment]
Justamente en #112 
Recuerda revisar las otras Issues antes de preguntar.
Saludos !
