### ISSUE TITLE
que pasa con el maximo de orders cuando son hechas por un match parcial?

### ISSUE THREAD

**Issue by ptflores1** [IIC2233/Syllabus#130]
En el enunciado dice que cuando hay un match parcial se debe ingresar una nueva orden de parte del mismo usuario, la pregunta es: hay que contar esta creacion de order en la cantidad de orders diarias que lleva el usuario?

Ejemplo:
El usuario1 que es trader ha ingresado 4 ordenes. El usuario2 ingresa una orden nueva que hace match parcial con una orden del usuario1 haciendo que el sistema ingrese una nueva orden a nombre del usuario1. Si el usuario1 quiere ingresar una nueva orden hoy podra hacerlo(ya que tecnicamente hoy se han ingresado 5 ordenes a su nombre)?

**Comment by cilopez** [comment]
@ptflores1  Te recomiendo que especifiques en tu *readme* la forma que implementaras para esta situación ya que no está explicitado en el enuncidado, ¡Saludos!
