### ISSUE TITLE
Duda respecto al uso de polimorfismo y duck typing

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#130]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, entre polimorfismo y duck typing, para el curso nos recomiendan implementar una tecnica antes que la otra? o dependiendo del caso la implementación de una será mejor que la de la otra?

Desde ya gracias.

**Comment by pabloist** [comment]
Hola :)

Te comento que en ciertas ocasiones pueden utilizarse de forma indistinta y corresponderá a un criterio propio la elección de alguna de ellas. Particularmente el Polimorfismo está relacionado y mayormente adaptado para casos de Herencia de Clases mientras que el Duck Typing puede ser utilizado para clases que no heredan de alguna común. Finalmente lo que permita mantener el código lo más limpio y claro posible será la opción correcta (Particularmente yo utilizo más el Duck Typing).

Saludos!

**Comment by JuanpaBC** [comment]
bkn muchas gracias
