### ISSUE TITLE
Mandar reverso Carta

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#1300]
¿El reverso de la carta tiene que seguir algun formato en especial de id?

**Comment by SamWeinstein** [comment]
Hola! Al no ser necesario saber el color, numero o tipo de carta (pues el reverso de la carta se está mostrando a alguien que no tiene la posesión de esa carta), entonces no debe seguir el formato descrito en "envío de cartas" del enunciado. Por ende, esta información cae en la otra categoría de información que se debe enviar entre el cliente y el servidor, es decir, queda a tu criterio. Te recomiendo explicarlo en tu README de todos modos para que no tengas problemas.
