### ISSUE TITLE
Usar Cartas sobre un +2

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#1301]
El jueves en la instancia de programaton del jueves, surgió la siguiente duda y se me sugirió hacer un issue al respecto. Respectio a las cartas que se pueden usar sobre un +2. 

Si el primer jugador juega un +2, el segundo puede jugar un +2 o robar. Si el segundo roba 2, ¿el tercer jugador puede entonces jugar encima del+2 (ya que esta carta ya no tiene efecto en el) cualquier carta especial? O sea si el +2 que uso el jugador 1, es azul, el jugador 3 podria usar una carta de cambio de color o cambio de sentido azul?

**Comment by tocococa** [comment]
Yo estoy permitiendo que una vez que se roba lo correspondiente a todos los +2 que se han puesto seguidos, después se puede poner otro +2, cambio de color o una carta del mismo color que el +2 original ~~que creo son las reglas del UNO~~.

Me imagino que hagas lo que hagas si lo aclaras en el README está ok.

**Comment by jirarrazabal** [comment]
Hola! Como dice @tocococa , esos detalles quedan a tu criterio. Solo recuerda especificar todo en tu README. Mucha Suerte!

**Comment by felipefuentesporras** [comment]
Perfect
