### ISSUE TITLE
Problema decodificando: AttributeError: 'bytes' object has no attribute 'a'

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#1303]
Los mensajes llegan, los puedo imprimir pero al decodificarlos me da este error. Que causa esto?

**Comment by vicentevegaulloa** [comment]
Hola @sofiuni!

Revisé tu código y en el cliente estás imprimiendo `...response_bytes_length.a.decode...`, probablemente pasaste a escribir ese ".a" pero basicamente estás intentando acceder a un atributo de `response_bytes_length` llamado `a`, el cual no existe. Basta con que borres la `a` y problema resuelto. (Línea 43 😉 )

Espero haberte ayudado! 😄

**Comment by sofiuni** [comment]
ahora me da "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte". Por que me da ese error?

**Comment by vicentevegaulloa** [comment]
Esto ocurre porque el encoding `'utf-8'` no reconoce ese byte. Trata cambiando el encoding o utiliza el parametro `errors` que puede tomar el valor de `errors="ignore"` (no decodifica ni codifica el caracter) o `errors="replace"` (reemplaza el caracter a decodificar por un `"?"` o codifica el caracter como `U+FFFD` si se busca codificar). Puedes encontrar más información de `errors` [aquí](https://docs.python.org/3/library/codecs.html#codec-base-classes)

**Comment by sofiuni** [comment]
Ahora funciona y todo pero no entiendo por que el print me da un numero- podria ser que se esta mandando la carta, o ser el string de que empieza la ronda. Que me esta entregando? Si es el string, como lo puedo convertir a string?

**Comment by vicentevegaulloa** [comment]
No se si aún te sirve, pero si te referías a el print de antes, este solo recibe 4 bytes, por lo que probablemente te está intregando un número con el largo del mensaje o algún id que significa el tipo de dato a recibir. Todo esto depende de como hayas modelado el envío de información.
