### ISSUE TITLE
Pozo +2

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#1304]
Si un jugador tiene que sacar 6 cartas producto del +2 acumulado, pero saca 2 y ya pierde. ¿Entonces el siguiente jugador a este debe sacara las otras 4 cartas o se cancela el pozo de +2 acumulado?

**Comment by SamWeinstein** [comment]
No está especificado en el enunciado así que quedaría a tu propio criterio (dejandolo claramente explicado en el README).  De todos modos, personalmente me parece mas lógico que no se le cobre las cartas al jugador siguiente y que termine ahi. 

Saludos!
