### ISSUE TITLE
pressevent en qbox

### ISSUE THREAD

**Issue by JulioGalvez** [IIC2233/syllabus#1305]
<img width="631" alt="Captura de pantalla 2020-07-04 a la(s) 02 24 31" src="https://user-images.githubusercontent.com/62029166/86506481-a3922300-bd9d-11ea-90ed-1969252b4025.png">

el click funciona bien sobre las imágenes, sin embargo, se extiende mas allá del margen de las imágenes como puede solucionarlo?

**Comment by gatochico** [comment]
Hola! 

La verdad es sin leer tu código, no podría darte una solución exacta. Lo que se me ocurre podría estar pasando es que el tamaño del QLabel sea mayor al de las cartas y por ende, el rango del click pareciese extenderse más alla de los límites de la imagen. Podrías revisar las dimensiones del label y modificarlas para que sean del tamañlo de la imagen a ver si se arregla. Intenta eso y si aún así no se arregla, sube tu avance a tu repositorio para echarle un ojo y ver si podemos ayudar.

Éxito!
