### ISSUE TITLE
Duda con jugador en modo espectador

### ISSUE THREAD

**Issue by totaurt** [IIC2233/syllabus#1306]
Hola! Tengo una duda respecto a cómo se muestra en la interfaz cuando un jugador pierde en la partida por superar el máximo. El enunciado pide hacer lo siguiente: "El área donde se encuentran las cartas propias debe ser reemplazado por un label que indique su derrota."
Personalmente, para mostrarlo hice que cada carta muestre las siglas 'RIP'. Mi duda es que si un jugador roba cartas y queda con más de 10 cartas, supera el máximo de cartas en la mano. ¿No importa? ¿O debo hacer que muestre justo 10? Gracias.

**Comment by gatochico** [comment]
Hola! 

No veo problemas con lo que hiciste, ya que el máximo de 10 es un límite para que el jugador se mantenga en la partida. Con tal de que este 'RIP' se note claramente en las cartas para avisar que perdió no debería haber problema. De todos modos, ponlo en tu README para que el corrector esté al tanto y no crea que es un problema. 

Saludos y éxito!!!!!!

**Comment by totaurt** [comment]
gracias!! :)
