### ISSUE TITLE
Ubicación Generador de Mazos

### ISSUE THREAD

**Issue by jitorralba** [IIC2233/syllabus#1307]
Hola! Hice una copia del archivo en la carpeta del servidor para importarlo directo desde ahí, ya que tenía más sentido que el servidor tuviera todos sus recursos en un mismo lugar, sin tener que recurrir a directorios padres en común. Se puede hacer eso? O debo importarlo desde el directorio padre?

**Comment by gatochico** [comment]
Hola! Está bien que ubiques el archivo dentro del servidor 👌 . Recuerda que debes ignorarlo con el gitignore al momento de subir tu tarea y poner en tu README en la sección correspondiente que el archivo se debe poner en esa ubicación, eso sí. 

Saludos!

**Comment by jitorralba** [comment]
Gracias!
