### ISSUE TITLE
Duda sobre el uso de variables globales

### ISSUE THREAD

**Issue by Raibruh** [IIC2233/syllabus#131]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hice una función recursiva con 'ifs' y 'elifs' y al hacer uso de un 'if' se vuelve a correr la función y puede ser que se utilize ahora otro 'elif', sin embargo quiero utilizar una variable que se creó en el primer 'if'. Después de varios intentos sólo logré hacer esto haciendo a mi variable una variable global. ¿Qué puedo hacer en este caso para no tener un descuento?

**Comment by aaossa** [comment]
Hola @Raibruh , no me pude imaginar bien la función que describes, pero te dejaré un ejemplo que creo que podría servir:

> Imagina que tienes una función recursiva también, que recorre todos los números hasta el 100, pero quieres ir acumulando algo: aquellos números que son divisibles por 7. En lugar de utilizar una variable global, puedes usar un *keyword argument* de la función para ir acumulando un valor y pasarlo a través de la recursión:

```python
def multiplos_de_7_menores_que_100(valor_actual, valor_acumulado=None):
    # Si estamos empezando la función recursiva, acumulamos valores en la lista
    if valor_acumulado is None:
        valor_acumulado = list()
    # Si estamos terminando la función recursiva, es porque se cumple esto:
    if valor_actual == 100:
        return valor_acumulado
    # Revisamos si el valor actual es divisible por 7
    if valor_actual % 7 == 0:
        # Agregamos el valor actual a la lista y vamos al siguiente número
        return multiplos_de_7(valor_actual + 1, valor_acumulado=valor_acumulado + [valor_actual])
    else:
        # No actualizamos la lista y vamos al siguiente número
        return multiplos_de_7(valor_actual + 1, valor_acumulado=valor_acumulado)

if __name__ == '__main__':
    X = multiplos_de_7(0, 100)
    print(X)

```

En este caso, la variable `valor_acumulado` "traerá" una lista desde la llamada recursiva anterior. Y al final, cuando llego a 100, retorno esa lista. ¿Crees que algo así te sirva? 🤔 Si no se entiende o no te sirve, pregunta por acá mismo 👌 ¡Éxito con la tarea!

**Comment by Raibruh** [comment]
No me expliqué bien, mala mía jajaja. Acá va un ejemplo de lo que quiero hacer, yo sé que la primera opción siempre será 'a', pero quiero guardar una variable para luego utilizarlo cuando la opción sea 'b'

def ejemplo(opcion):

    if opcion == 'a':
        numero = input("eliga un numero: '1' o '2':\n")
                       
        if numero == '1':
            variable = '1'
                       
        elif numero == '2':
            variable = '2'
            
        opcion = 'b'
        ejemplo(opcion)

    if opcion == 'b':
        print(variable)

ejemplo(input("eliga una opcion: 'a' o 'b':\n"))

**Comment by aaossa** [comment]
Creo que el ejemplo que te dejé igual puede servirte, si lo que quieres ir pasando son las opciones seleccionadas (a lo mejor en lugar de una lista te sirve otra estructura :eyes: ). Por otra parte, quizás te sirva también aislar el comportamiento de la opción A en su propia función, aunque no sé si ya lo tienes así.
