### ISSUE TITLE
Como manipular archivos .txt 

### ISSUE THREAD

**Issue by enriquerussi** [IIC2233/syllabus#131]
Hola, no se como manipular los archivos.txt en visual studio code.

**Comment by Tsbalart** [comment]
Hola @enriquerussi!
Deberías poder  abrirlo sin problemas, al seleccionarlo con el botón derecho >abrir con...>VS code. De todas maneras puedes modificarlo con la aplicación que tu quieras siempre y cuando te preocupes de estar trabajando en el archivo correcto y guardarlo bien, no es necesario que sea VS code.
Saludos! Exito con la tarea!

**Comment by pabloalvarez67** [comment]
> Hola @enriquerussi!
> Deberías poder abrirlo sin problemas, al seleccionarlo con el botón derecho >abrir con...>VS code. De todas maneras puedes modificarlo con la aplicación que tu quieras siempre y cuando te preocupes de estar trabajando en el archivo correcto y guardarlo bien, no es necesario que sea VS code.
> Saludos! Exito con la tarea!

Hola! yo tamibién tengo un problema al abrir "puntajes.txt" dentro de mi main, de verdad ni idea que estoy haciendo mal :(

**Comment by dchahuan** [comment]
Puede ser que esten en un current working directory que no tenga el archivo. Intenten en vscode, en la esquina izquierda arriba donde sale file poner Open Folder. Ahi les va a abrir la carpeta en el lugar correcto. Avisen si les funciono.

**Comment by pabloalvarez67** [comment]
> Puede ser que esten en un current working directory que no tenga el archivo. Intenten en vscode, en la esquina izquierda arriba donde sale file poner Open Folder. Ahi les va a abrir la carpeta en el lugar correcto. Avisen si les funciono.

Era justo eso! jajaja me lo respondieron en otra issue. gracias igual
