### ISSUE TITLE
Error al importar modulos

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2233/syllabus#131]
tengo un archivo.py creado con las funciones que quiero utilizar, y para probar si funcionaba importarlo tengo un codigo muy simple (literal imprimir una funcion que da true o false, nada mas) pero me tira este error gigante:

/Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/Maggie/Desktop/syllabus/Tareas/T00/T00.py': [Errno 2] No such file or directory

ambos archivos estan guardados en la misma carpeta en el repositorio, asi que no se cual puede ser el problema :(

**Comment by aljara97** [comment]
Hola @maggiemunoz, en la issue #64 un compañero tuvo tu mismo error y lo solucionó arreglando la forma en que hacía correr el código desde la consola. Te sugiero revisar los últimos comentarios de esta y ahí me cuentas cómo te va.

Suerte ✌🏻

**Comment by maggiemunoz** [comment]
mmm si lo lei pero no entiendo como corregirlo, cuando corria el archivo original se me abrian perfecto los archivos con datos, pero ya no me funciona :(

**Comment by aljara97** [comment]
De qué forma estás corriendo el archivo actualmente? Usas IDLE o solamente abriste el archivo en VSCode? Puede ser que tengas un problema parecido al de la issue #134, recuerda que para correr un archivo en la consola de ese editor debes situarte en la carpeta correspondiente, haciendo click en file y luego en open folder. 

Quedo atento :bird:

**Comment by maggiemunoz** [comment]
lo estoy corriendo en pycharm, iba a pasarlo a vscode cuando termine para corregir el formato y cosas asi porque no entiendo bien como funciona vscode para correr el codigo

**Comment by aljara97** [comment]
Entiendo, podrías mandar un pantallazo de la consola de pycharm luego de correr tu código?

**Comment by maggiemunoz** [comment]
![Captura de pantalla 2020-03-20 a las 16 57 37](https://user-images.githubusercontent.com/62019819/77201912-2089dd00-6acc-11ea-9921-c54c96f19a46.png)
el error sale cortado, pero dice 
Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/Maggie/Desktop/syllabus/Tareas/T00/T00.py': [Errno 2] No such file or directory

(este es el codigo de ejemplo que use para ver si se abria o no)

**Comment by aljara97** [comment]
El problema es la ubicación de tus archivos en la carpeta, si te puedes fijar en pycharm abres una carpeta Tarea00, pero en esta no se encuentra el archivo ```usuarios.py``` que es el que quieres importar, probablemente está dentro de la carpeta venv si no me equivoco. Te recomiendo cambiar módulo al mismo directorio en donde está el archivo que estás ejecutando y correr tu código con normalidad, luego de eso no deberías tener problema.

Espero haber sido de ayuda 🤓

**Comment by maggiemunoz** [comment]
Disculpa, no entendí, tengo que cambiar el archivo usuarios.py a la carpeta Tarea00? por que tambien tengo todos los archivos guardados en una misma carpeta
![Captura de pantalla 2020-03-20 a las 17 10 52](https://user-images.githubusercontent.com/62019819/77202819-ce49bb80-6acd-11ea-9b1c-78ebc63f50f9.png)

**Comment by aljara97** [comment]
Exacto, la idea es que el módulo ```usuarios.py``` esté en la misma carpeta que el archivo que quieras ejecutar. Lo que no me queda claro es si abriste el proyecto de pycharm en una carpeta Tarea00, la cual es distinta a T00 que corresponde a la del último pantallazo que muestras, porque si es T00 debería mostrarse el módulo usuarios en pycharm
