### ISSUE TITLE
Me dice error al importar utils

### ISSUE THREAD

**Issue by Couvenn** [IIC2233/Syllabus#131]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo la version de python 3.11.8 y al intentar hacer import utils me aparece, No se accede a "utils"Pylance
No se ha podido resolver la importación "utils".Pylanc, el archivo main esta en la misma carpeta asi que no entiendo cual podria ser el error

**Comment by FernandoTFH** [comment]
Si esto te lo esta diciendo tu editor, esto se contestó en la issue #113, y es que al editor le molesta algo, pero esto no afecta la ejecución de tu programa. (se explicó un como mas en la issue).  Si estoy equivocado por favor entrega mas información que te entrega al terminal cuando ejecutas el programa.

**Comment by Johan-10** [comment]
Donde estas ejecuntando el utils? porque la funcion utilis solo puede ser importada en el archivo de main.py no en dccultivo.py, si lo ejecutas allí te dará error.

**Comment by Couvenn** [comment]
Revise el issue #113 y ya vi que era un error de VSC, muchas gracias por la ayuda
