### ISSUE TITLE
Duda sobre galaxia en base a la duda de la issue #85

### ISSUE THREAD

**Issue by fcschiaffino** [IIC2233/Syllabus#131]
Hola C:
Tengo una duda que me surgió a partir de la issue #85 , pues ahí se menciona que no puedo asumir que existirá una galaxia desde el inicio. Esto significa que no se contemplan las galaxias que obtengo desde galaxias.csv, o se refiere a que las únicas galaxias existentes son las del archivo galaxias.csv y que si bien durante el Juego se van creando a medida que el usuario elija esta opción, una vez que se termine el jeugo estas no se guardan.
Quedo atenta a su respuesta :D

**Comment by ptflores1** [comment]
Hola !
Cuando se dice que no puedes asumir que habrán galaxias es como decir que tus archivos **pueden** venir vacios(sin información sobre galaxias o planetas), en este caso tu programa debe dejar al usuario crear galaxias. Cuando el usuario crea galaxias siempre deben ser guardadas. Espero haya respondido tus dudas.
Saludos !

**Comment by fcschiaffino** [comment]
Una duda del lenguaje, con "tus archivos" ¿a que se hace referencia?, se hace referencia a planetas.csv y galaxias.csv,pero que contiene la información de lo que agregué o sea ¿con las galaxias que fueron creadas?.
Al venir "vacios" se hace referencia a que si yo realizo una partida nuevamente, es decir corro nuevamente el programa, no es necesario que contenga la info de una partida anterior.
(Lo siento, pero estoy como un poco pegada/bloqueda con esto :(   )

**Comment by ptflores1** [comment]
Hola !
Al momento de ejecutar tu programa las únicas galaxias existentes son las que están en el archivo galaxias.csv por lo tanto **siempre** debes leer este archivo y tambien planetas.csv para iniciar el programa. Luego si el usuario crea nuevas galaxias **siempre** debes guardar su información en galaxias.csv, de esta manera al usar en otro momento el programa las galaxias que fueron creadas anteriormente tambien deben mostrarse (lo mismo para los planetas). Lo que se pregunta en 85 es basicamente que si puede asumir que siempre que se corra el programa `generar_archivos.py`  que les dimos, los archivos csv generados vendrán con información acerca de al menos una galaxia, esto no es asi, puede que se generen archivos csv que no tengan informacion acerca de galaxias y planetas, en este caso tu programa no debe obligar al usuario a crear una galaxia pero obviamente no debe dejar modificar galaxias ya que no existirian
Saludos !

**Comment by PhilippePotin** [comment]
Hola, una duda acerca de "Luego si el usuario crea nuevas galaxias siempre debes guardar su información en galaxias.csv", por ejemplo si yo creo una galaxia estoy obligado a guardarla? No puedo simplemente arrepentirme de haberla creado y salir del juego sin guardar?

**Comment by ptflores1** [comment]
Hola !
Tal como dije en #52, estas en lo correcto.
Saludos !
