### ISSUE TITLE
Premio vuelta carrera

### ISSUE THREAD

**Issue by allullk** [IIC2233/syllabus#131]
Hola!!

¿El dinero que el jugador gana por ser el mejor en una determinada vuelta se suma a sus fondos totales o a unos que solo existen durante la partida que luego de terminar la carrera desaparecen?

**Comment by jeschuwirth** [comment]
Saludos!

El dinero ganado en cada vuelta se suma a los fondos totales del jugador. Por lo tanto, si ganas la carrera ganarás el dinero base por salir primero, además del conseguido en cada vuelta.

Suerte!

**Comment by allullk** [comment]
Muchas gracias jeschuwirth!!
