### ISSUE TITLE
Defensa base

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#131]
Hola, la defensa base se calcula con los ciudadanos que no estén ocupados? (ocupado por recolección en el caso de los trabajadores u ocupado por atacar en el caso de los soldados)

**Comment by jmwielandt** [comment]
Como se menciona en el enunciado, para el cálculo de HPt se usa a **todos** los trabajadores.
Si una civilización ataca a otra, pero al mismo tiempo es atacada, sus soldados no participan en la defensa.
