### ISSUE TITLE
Comentarios Diagramas

### ISSUE THREAD

**Issue by stephichau** [IIC2233/Syllabus#131]
1. Cuidado en cómo ordenan su jerarquía. Recuerden que si heredan mal sus subclases podrían tener métodos no deseados.
2. Una correcta modelación (y tarea) no debiese permitir a los usuarios underaged tener acceso completo a las funcionalidades de los otros usuarios, aunque éstas no se vayan a usar.
3. Piensen bien la cardinalidad. Deben plantearse con cuidado cuántas instancias de cada objeto pueden haber y recuerden no poner cardinalidad en la herencia. 
4. Verifiquen qué clases están contenidos en cuáles, si es la aplicación la que tiene lista de orders, lista de mercados y lista de usuarios, o un objeto (como las orders) tienen como atributo a sus usuarios. Dependiendo de la modelación pueden llegar a recurrir a la modelación circular lo que no es una buena práctica. 
5. Si hacen clases Underage, Trader e Investor **revisen** cuáles atributos o métodos van a heredar de Usuario y cuáles serán nuevos para estas clases. No sirve crear 3 clases distintas que heredan de Usuario pero no tienen algo en particular que las diferencie entre ellas o de una instancia de Usuario.
6. Tengan cuidado con confundir composición con agregación.
7. Aprovechen el uso de properties.
8. Respecto al diagrama en sí, para marcar un atributo como privado es mejor usar - nombre_del_atributo (porque ese es el símbolo para indicar que es privado) en vez de + __nombre_del_atributo (que es como se lo indican a Python en su código).
9. Traten de cuestionar las decisiones que tomaron en cuanto a quién hereda de quién y qué clase contiene a otra de manera lógica. Por ejemplo, ¿tiene sentido que Trader esté heredando de Underaged? ¿Es el Trader un Underaged o en realidad ambos son usuarios y deberían heredar de otra clase?
10. Recuerden que el diagrama de clases es también para que ustedes entiendan el orden esquemático en que se plantean los objetos y sus relaciones, es decir, no es necesario que todo esté relacionado con todo, sino que sólo lo que corresponda a partir de Composición, Agregación y Herencia. 
Por ejemplo, si tengo un juego en el que existe un Menú - con atributos como “nueva partida”, “continuar partida”, etc-, no es necesario que ese Menú esté ligado a todos los objetos debido a que a partir de él llego a las diferentes opciones de juego. La idea es que puedan abstraerse de las relaciones explícitas y logren ver qué cosas realmente están ligadas entre sí y cuáles no para que así entiendan cómo están armando su programa. 
11. Hacer mejor uso de las herencias, recordar que si B hereda de A y C hereda de B entonces C también hereda de A, esto puede ahorrar un par de líneas de código.
12. Evalúen bien qué clases van a heredar de cuáles y cómo se diferencian las clases hijas entre ellas y de la clase madre. Si tienen dos clases hijas que hacen exactamente lo mismo, están modelando mal el problema.
13. Cuidado con las relaciones. Las orders son dependientes del mercado, pues ¿qué sería de una order si no existiera el mercado? También si piensan hacer herencia de otra herencia vean que ventaja esta les traerá, y, de no tener, mejor no hacerlo.
14. El diagrama debe incluir todos los métodos correspondientes a la clase. Si una clase hereda de otra, pero no posee métodos ni atributos nuevos significa que hay problemas de modelación y que podría estar pasando que la clase madre posea métodos que no le corresponden. No siempre la solución óptima será la más obvia. (Por ejemplo, es intuitivo pensar que una clase “Hombre” y “Mujer“ hereden de una clase “Persona” sin embargo puede que en el programa la mejor solucion sería que Persona tenga a Hombre y Mujer como atributos. Siempre todo dependerá de cómo piensen el problema.)
15. Puede que usar listas no siempre sea la mejor solución. Intenten usar diccionarios u otras estructuras de datos para que su vida se les simplifique
16. Aprovechen las herramientas aprendidas en el curso. Para esto, deben asegurarse de entenderlas bien en las actividades y luego cuando estructuren mentalmente su tarea deben identificar las oportunidades de usarlas. Si las aplican bien, les simplificarán mucho su trabajo. Por ahora no son muchas y ya se notan ausentes (herencia, properties y estructuras de datos). Tengan esto en cuenta para las siguientes tareas.

**Comment by Bneya** [comment]
¿Es realmente necesario usar @properties o usar herencia (a nivel de pauta) en la tarea?   ¿van a descontar puntaje si en ningún momento realmente _"necesité"_ usar herencia por ejemplo?

**Comment by andresfdezc** [comment]
@Bneya Sí.

**Comment by mjgutierrez1** [comment]
¿Importa si creo el menú del juego como una función menu() y no como una clase Menu?

**Comment by rihanuch** [comment]
@andresfdezc pero si por ejemplo nunca encontré la necesidad de usar properties más que una vez acá? (a pesar de que las entiendo bien y he programado con ellas) 😭

**Comment by andresfdezc** [comment]
@rihanuch La tarea es su oportunidad para demostrarnos que han aprendido los contenidos que se les están evaluando. Aprovechen de usarlos como herramientas para hacer su tarea de la mejor forma.

**Comment by nmaturana97** [comment]
Hola, anduve revisando el enunciado y en ninguna parte sale que el uso de properties y herencia es obligatorio. A esta altura del plazo se hace verdaderamente imposible cambiar el modelo que yo ya hice en mi tarea,  usando el tipo de usuario como atributo y no con herencia. 
En las actividades que hacemos en clases sale especificamente lo que debemos usar, pero en esta tarea no.
Considerando que la tarea fue subida antes de que en clases pasemos herencia (con su actividad correspondiente) y ademas que practicamente todos los ayudantes nos recomendaron no perder ningun minuto, encuentro injusto que digan ahora que descontaran por el no uso de herencia y properties.

**Comment by behrmann97** [comment]
Me pasa lo mismo que el que recién comentó, a estas alturas cambiar todo para lograr introducir una property requiere demaciado tiempo.

**Comment by luvalenz** [comment]
@nmaturana97 Como explicamos en la clase 0, las actividades y las tareas tienen objetivos distintos. Las actividades están pensadas para que ustedes se enfrenten a los conceptos que estudiaron en el material del curso, puedan aplicarlos y resolver dudas. Como deben ser resueltas en un periodo muy corto de tiempo, nosotros les decimos exactamente lo que deben hacer. Estas tienen un enfoque técnico, ya que ustedes no tienen que pensar qué herramientas usar, sólo aplicar los conceptos. 

El objetivo de las tareas, en cambio, es que ustedes puedan resolver un problema complejo usando de la mejor manera posible los conceptos vistos. Por lo tanto, no sólo deben entender las herramientas de programación, sino que deben pensar cómo usarlas de la mejor forma posible. En una tarea nunca les vamos a decir qué herramientas usar ni cómo usarlas, ya una de las cosas que se está evaluando es que ustedes puedan tomar estas decisiones.

En la tarea 1, específicamente se está evaluando que ustedes puedan usar los conceptos vistos de OOP y puedan tomar decisiones acerca de cómo usar de la mejor forma estos conceptos vistos. En el post anterior, el ayudante te "sopló" que era necesario usar properties y herencia. Considera esto como una pista sobre qué tipo de modelamiento resuelve de mejor manera el problema usando OOP. Sin embargo, esta pista no es necesaria, ya que es trabajo de ustedes pensar esto. En tareas siguientes tampoco les diremos cuál es la mejor forma de modelar los problemas, ya que, como indiqué antes, nos interesa que ustedes desarrollen esto. Las tareas se asemejarán lo más posible a un problema real, donde tampoco tendrán nadie que les diga cuáles son las herramientas que conviene usar.

Como último punto, quiero recordar que cuando la tarea se subió, ya se había publicado el material de herencia que ustedes tienen como obligación estudiar.

**Comment by nmaturana97** [comment]
Ok. ¿Y dentro de que parte del enunciado entraria este descuento? Solo para saber, ya que es imposible que a estas altura lo cambie.

**Comment by luvalenz** [comment]
Como dije antes, ustedes deben determinar dónde deben aplicar cada concepto. Por lo tanto, si te respondiera esta última pregunta, te estaría soplando la respuesta. Como ya te soplaron un poco, te puedo adelantar que aplicar herencia en usuarios, va obviamente en el ítem "Usuarios".

Finalmente te dejo un consejo:
Si bien es cierto que agregar herencia puede tomar tiempo si ya tienes el problema modelado de otra forma, implementar _properties_ debería ser algo bastante rápido de hacer. Te aconsejo que si tienes algo de tiempo, aproveches de crearlas.

**Comment by nmaturana97** [comment]
jajaja, mi pregunta no iba a eso. Si esta claro donde hay que usar herencia, pero encuentro que el problema se me hizo mas facil usar como atributo el tipo de usuario, por que al momento de cambiar de trader a investor, o cuando un underaged cumple la edad de 18, se hace mucho mas simple cambiar un atributo, por eso que no entiendo porque modelar el problema sin herencia es un descuento (citando lo que se dice en esta publicacion "es intuitivo pensar que una clase “Hombre” y “Mujer“ hereden de una clase “Persona” sin embargo puede que en el programa la mejor solucion sería que Persona tenga a Hombre y Mujer como atributos"). 
En cuanto a properties ya las estoy añadiendo.
Gracias de todas formas por el consejo.

**Comment by achadwicka** [comment]
@luvalenz Concuerdo totalmente en que debemos tratar de optimizar y hacer de la mejor forma la aplicación de los conceptos , pero no entiendo por que se descontaría puntaje al no usar lo que se nos enseñó. Si el código funciona y responde a todas las necesidades que se exigen en la tarea de verdad se descontaría por el hecho de que no se usaron properties? Claramente saldría mas fácil aplicar todo lo visto pero no existe solo una manera de modelar la tarea.

**Comment by luvalenz** [comment]
No hay una única manera correcta de hacer la tarea. Eso es verdad y será válido para las próximas tareas. Sin embargo, también es cierto que no sólo se les evaluará que la tarea funcione, sino que esté bien modelada y cumpla con estándares de buena calidad de código.
En el "mundo real" es así. Un código puede cumplir con todas las funcionalidades requeridas, pero si no cumple con estándares de calidad, difícilmente perdurará en el tiempo, ya que será muy difícil mantenerlo o ampliarlo cuando sea necesario.

**Comment by Regenschrim** [comment]
Hay algún formato en específico para entregar el diagrama? puede ser una hoja escaneada? No he encontrado en ningún lado eso :/
