### ISSUE TITLE
Uso de .gitignore

### ISSUE THREAD

**Issue by 18638333** [IIC2233/syllabus#1310]
Hola, para esta entrega, como son 2 subcarpetas, hay que hacer un archivo .gitignore en cada una de las subcarpetas?

**Comment by jirarrazabal** [comment]
Hola! Solo debe haber un archivo .gitignore, el cual debe tener los paths correspondientes de los archivos a ignorar en cada subcarpeta. Mucha Suerte!

**Comment by MINGOD24** [comment]
@jirarrazabal  hola, si subi un gitignore por cada subcarpeta me funciona bien, lo puedo dejar asi? y si ocupo el logo en clientes, lo dejo, o lo incluyo en el gitignore?

**Comment by jirarrazabal** [comment]
Hola @MINGOD24 ! Si ya lo hiciste así puedes dejarlo. Con respecto al logo, debes ignorarlo también, pero explicando en tu README donde se debe ubicar este archivo para poder corregir bien tu tarea.
