### ISSUE TITLE
Como hacer .gitignore

### ISSUE THREAD

**Issue by rldelafuente** [IIC2233/syllabus#1311]
Hola!

Busqué en issues y no encontré lo que necesitaba, que sería una serie de pasos de cómo hacer `.gitignore`. No se como hacerlo, usando VSCode. Lo que hice para la tarea pasada fue no subir los archivos que se querían ignorar, pero me descontaron puntaje igual.

Muchas gracias de antemano!

**Comment by benjavicente** [comment]
Hola! No soy ayudante, pero esto es lo que he hecho yo:

- **Crear un archivo con el nombre `.gitignore`**. En VSCode, se puede crear un archivo con `Ctrl + N` o  `File: New File`. Si el archivo fue creado con el nombre `.gitignore`, debería aparecer `Ignore` abajo a la derecha.
- **Escribir los archivos que quieres ignorar**. Existe un [sintax para añadir añadir carpetas o tipo de archivos](https://git-scm.com/docs/gitignore#_pattern_format). Puedes ver ejemplos en en el directorio [syllabus](https://github.com/IIC2233/syllabus/blob/master/.gitignore) y [contenidos](https://github.com/IIC2233/contenidos/blob/master/.gitignore).

Un ejemplo pequeño sería

```ignore
*.jpg
.vscode/
```

El cual ignora las imágenes `.jpg` y la configuración de VSCode del directorio.

**Comment by DCCollao** [comment]
Hola @rldelafuente!

Complementando la excelente respuesta de @benjavicente (muchas gracias!), te sugiero que veas la issue #1284, donde se trató un problema común a la hora de hacer tu `.gitignore` después de haber subido archivos que no querías al repositorio :smile:
