### ISSUE TITLE
Sobreponen Cartas

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#1312]
Hola, para hacer que las cartas nunca se tapen entre si, las mostre asi! Nunca no se va mostrar una carta asi, quería saber si cuenta como si las cartas de sobreponen?
<img width="789" alt="Screen Shot 2020-07-04 at 16 31 30" src="https://user-images.githubusercontent.com/62016215/86520568-ea226480-be13-11ea-83b5-65b45a4141e2.png">

**Comment by DCCollao** [comment]
Este tema se habló en #1214, pero en resumen, mientras no suponga problemas para la corrección e indiques en tu `readme.md` que decidiste hacerlo de esa forma, no hay problema.

Mucho éxito!
