### ISSUE TITLE
Problema con Locks

### ISSUE THREAD

**Issue by vtunon7** [IIC2233/syllabus#1313]
Hola! estoy tratando de usar Locks porque al repartir cartas a los jugadores en el inicio no se le entrega a todos por igual y trate de usar time.sleep() y Qt.Qtest.qWait() para tratar de "reemplazar" los locks pero sigue sin funcionar. Mi pregunta es en que parte deben ir ya que trato de ponerlos en donde recibo o envio los mensajes y dejan de funcionar los botones y todo

**Comment by fdoflorenzano** [comment]
Hola @vtunon7,

Tu pregunta fue un poco amplia como para responderla fácilmente. ¿Es un problema de concurrencia el que tienes para necesitar *locks*? ¿No habría sido otro el problema que llegaba información distinta a los clientes? ¿Te fijabaste en los mensajes y sus largos en el envío y recepción?

Si aún deseas solucionarlo, puedes escribir dando más detalles del problema.

Saludos.

**Comment by vtunon7** [comment]
Si, el problema es de concurrencia. Creo que es debido a que 2 clientes intentan enviar al mismo tiempo información al servidor (cuando sacan las cartas iniciales del mazo), por lo que utilice locks en en el cliente en mi método send() y al parecer funciono bien.
