### ISSUE TITLE
Cantidad de señales

### ISSUE THREAD

**Issue by benjaguiloff** [IIC2233/syllabus#1314]
Hola!

En mi código estoy usando muchas instancias de pyqtsignal, y tengo algunas que cumplen la misma función pero en distintas ventanas. Quería saber si existe alguna manera de reutilizar una misma en distintas ventanas, o si tendré crear la misma señal de nuevo para cada una?

**Comment by SamWeinstein** [comment]
Hola @benjaguiloff !

Te diría que no te preocupes por eso, porque podría complicar un poco la corrección, pero de todos modos contestaré tu pregunta.

Se me ocurren dos modos de "reciclar" esa señal y no repetir código, una buena forma y una mala forma, partamos por la buena: 

Puedes crear una clase que contenga la señal que quieres reutilizar, de modo que las clases que quieres que accedan a esta señal hereden de esta otra nueva clase que la contiene. 

La otra manera de enfrentar este problema no es una muy buena práctica y no te recomiendo usarla, pero te la menciono para para que puedas ampliar tus conocimientos y visión respecto a la programación:

Imagina que la señal que quieres reciclar la creas dentro de la clase 1, luego, dentro de la misma clase 1 instancias la clase 2 para mostrar su ventana. Al instanciar la clase 2 puedes pasar el self de la clase 1 como atributo y así acceder a este self (y por ende a todo lo de la clase 1) desde la clase 2, pero insisto, no te recomiendo utilizar esta técnica, solo la menciono motivos educativos. :)

Saludos!
