### ISSUE TITLE
Problema al usar .gitignore

### ISSUE THREAD

**Issue by josefeliuf** [IIC2233/syllabus#1315]
Hola! al incluir los archivos dentro del .gitignore que no quiero que se suban, el único que se ignora es Enunciado.pdf.
Si alguien me pudiera ayuda pls, que en la tarea pasada me bajaron decimas :(
Asi tengo el .gitignore:
Enunciado.pdf
/servidor/.vscode
/servidor/pruebas.py
/cliente/.vscode
.vscode
EDIT: Leí la issue #1311 pero no me sirvió

**Comment by SamWeinstein** [comment]
Hola! 

Puede ser que los archivos que estás intentando ignorar se subieron antes de que crearas el .gitignore? Porque en ese caso, al agregar esos archivos al .gitignore, no se borrarán en el repositorio remoto, simplemente evitará que se suban denuevo. En este caso debes eliminar estos archivos de tu repositorio remoto, luego, volver a hacer push y los archivos presentes en tu .gitignore no se volverán a subir. 

Si ese no era el problema, coméntamelo y te ayudo, pero creo que eso solucionará tu problema. 

Saludos!

**Comment by josefeliuf** [comment]
Ese era el problema! Pero lamentablemente no alcancé a eliminar los archivos antes de las 8 :(
