### ISSUE TITLE
Modularización en el repositorio personal

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2233/syllabus#132]
Hola, tengo una duda más por orden en mi repositorio la verdad. Los módulos que cree para complementar al código principal, idealmente los meto dentro de una carpeta del repositorio? me refiero a que estos preferiblemente no estén a la misma altura que mi main.py, para que no se acumulen tantos archivos.

No debería haber un problema con eso mientras mis paths estén bien o no?
También pregunto por que es lo que les acomoda a los ayudantes a la hora de corregir

Saludos!

**Comment by vicentevegaulloa** [comment]
Hola @pabloalvarez67 !

Puedes dejar tus archivos .py en la misma carpeta que el main o en una carpeta dentro de la carpeta donde esta el main. Esto solo afectará tu calificación si los paths están malos. Respecto a cuan cómodo es para los ayudantes, personalmente a mi me da lo mismo jaja pero lo más importante es que uses nombres descriptivos cuando modularices 😄
