### ISSUE TITLE
Acciones de CPU [Cantidad trabajadores]

### ISSUE THREAD

**Issue by quememo** [IIC2233/syllabus#132]
En el archivo acciones.csv existen algunas líneas como:
    -    6,1,Crear persona,trabajador;7
Cuando la CPU intenta llevar a cabo esta acción, pero digamos solo tiene recursos suficientes para crear 5 trabajadores y no 7, simplemente se salta el turno y crea 0 trabajadores o crea la mayor cantidad posible de acuerdo a sus recursos actuales? (Siendo en este caso 5 trabajadores)

**Comment by siescobedo** [comment]
hola, te respondieron esto o encontraste otro issue? tengo la misma duda

**Comment by Arcoirisky** [comment]
@siescobedo por si aún te sirve, la respuesta es que se omite la accion si es que no tiene los recursos suficientes para hacer lo que se pide. Si lo solucionaste de una forma diferente, puedes especificarlo en el README.md debido al tiempo.
