### ISSUE TITLE
Descuentos, typing y PEP8

### ISSUE THREAD

**Issue by CarlosValleA** [IIC2233/syllabus#132]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola !,

Surge la duda si se puede utilizar typing para definir las funciones de tal forma de que quede mas claro los inputs y los outpus. Estuve buscando y creo que typing no es parte de PEP8 (? no estoy seguro la verdad), por lo que me queda la duda si se haran descuentos por hacer eso.

Ejemplo:
Usar : 

```
def func(variable: str) -> int:
    if variable == "1"
        return 1
    else:
        return 0
```

En lugar de 
```
def func(variable) :
    if variable == "1"
        return 1
    else:
        return 0
```

Tambien lo podria agregar con comentarios en el texto, pero me parece que typing es mas claro. Gracias!

**Comment by hsazos** [comment]
Hola @CarlosValleA !

Esta pregunta la debes hacer en la issue #44, para que quede registro de la respuesta en el lugar correcto.  Ánimo con la tarea!
