### ISSUE TITLE
Error desconocido

### ISSUE THREAD

**Issue by Mario-uc** [IIC2233/syllabus#132]
'charmap' codec can't decode byte 0x9d in position 1527: character maps to <undefined>

no entiendo que significa ese error

**Comment by Tito0906** [comment]
Holaa @Mario-uc, es un error común que suele aparecer al leer un archivo sin el argumento _encoding_ de la función open() . Este error se trató en las siguiente issue: https://github.com/IIC2233/syllabus/issues/16. 

Quedo atento por si el problema persiste o tienes otras dudas.
