### ISSUE TITLE
pep8

### ISSUE THREAD

**Issue by ciquezada** [IIC2233/Syllabus#132]
¿es correcto escribir returns de la siguiente forma?

"return a if conditional else b"

**Comment by nebil** [comment]
Lamentablemente, no me sé el [PEP8](https://www.python.org/dev/peps/pep-0008/) de memoria, pero estoy casi seguro de que no estipula nada acerca de eso. En cualquier caso, lo que escribiste allí se conoce como _operador ternario_ (claro, porque toma tres argumentos) o también como  _expresión condicional_. Esto existe en muchísimos lenguajes de programación, implementado con distintas sintaxis. Generalmente, se utiliza algo como `condition ? value_if_true : value_if_false`. De hecho, esta _feature_ llegó relativamente tarde a Python, puesto que no había un acuerdo en la sintaxis. Si te sobra algo de tiempo, puedes leer más sobre esta ~apasionante~ discusión en la [PEP308](https://www.python.org/dev/peps/pep-0308/). Finalmente, Guido van Rossum, el [dictador benevolente](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life) de Python, [decretó](https://mail.python.org/pipermail/python-dev/2005-September/056846.html) que se escribiría como `value_if_true if condition else value_if_false`.

Ahora, estudiemos un breve ejemplo. Digamos que tienes una función que permite obtener el navegador favorito a partir de un usuario.

```python
def get_browser(user):
    if user.name == 'stephichau':
        return 'Internet Explorer 6'
    else:
        return '🔥🦊'
```

Sin embargo, esto podría ser escrito de manera más concisa…

```python
def get_browser(user):
    return 'Internet Explorer 6' if user.name == 'stephichau' else '🔥🦊'
```

Mmm… pitonesco. :drooling_face:

Bueno, el punto es que PEP8 no dice mucho al respecto. Hay casos en que hará el código más legible; en otros, quizá es mejor conservar una estructura clásica de `if-else`. Quedará, entonces, a tu criterio si es que vale la pena o no usar una expresión condicional.

**Comment by ciquezada** [comment]
Gracias!!
