### ISSUE TITLE
Duda main.py

### ISSUE THREAD

**Issue by vvialbarros** [IIC2233/Syllabus#132]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Para hacer el menu de la tarea te piden hacerlo en el archivo main.py, pero en mi carpeta de tarea no está ese archivo, en ese caso tengo que yo mismo crear un archivo de python y llamarlo main.py o si no está en la carpeta significa que hice algo mal?

**Comment by FernandoTFH** [comment]
Si tienes que tu crear el archivo main.py.

**Comment by vvialbarros** [comment]
Gracias!
