### ISSUE TITLE
Problema calendario curso

### ISSUE THREAD

**Issue by Julius9** [IIC2233/Syllabus#132]
Hola! tengo un problema con el calendario del curso y este no se despliega en mi computador ni en el navegador de mi celular, este problema lo tengo hace unos días y ya había escrito una Issues sobre esto (Contenidos Actividad 10/08 #22). Pero todavía no he podido arreglar esto y he usado varios navegadores ( Chrome, Safari, firefox) y en ninguno se despliega, incluso me he percatado que en algunas salas crisol como la de College los computadores tampoco lo muestran. He buscado en google alguna solución pero todavía no encuentro nada   : (

**Comment by andresfdezc** [comment]
¿Puedes intentar ingresando desde incógnito?

**Comment by flobarrios** [comment]
Hola!! 

Que raro lo que te ocurre y no sabría como solucionarlo a priori ya que a nadie más le ha pasado. La solución que te puedo dar es que te comparta directamente el calendario por google calendar. Déjame tu correo para hacerlo!

**Comment by sebacruzd** [comment]
Mientras solucionas el problema del calendario puedes ver la programación [acá](https://github.com/IIC2233/Syllabus/projects) :)

**Comment by Julius9** [comment]
- @andresfdezc tampoco se muestra ingresando desde incógnito 
- @flobarrios mi correo es jihuerta@uc.cl
- @sebacruzd no se me había ocurrido abrir la pestaña de projects, gracias por el dato!
He estado pensando que el problema quizá se origina por la falta de actualización de algunas herramientas como flash player, intentare si con eso lo resuelvo.

**Comment by flobarrios** [comment]
@Julius9 listo !
