### ISSUE TITLE
Avance de Tarea

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2233/syllabus#132]
Hola! ¿Para el avance de Tarea solo se debe entregar el diagrama de clases? ¿o tambien hay que incluir el codigo que llevamos hasta ahora hecho?

**Comment by DCCollao** [comment]
Hola!
En esta ocasión no se pide avance en código, así que es solamente el diagrama de clases.
Éxito!

**Comment by jfuentesg26** [comment]
Gracias!!

**Comment by Pdesolmi** [comment]
Es obligación entregar el avance?, o es para optar a las décimas adicionales.
Gracias
