### ISSUE TITLE
Sobre formato de string de "Modulos" con días que no comparten módulos

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2233/syllabus#1320]
Hola! No me quedó muy claro como es el formato del string correspondiente a los módulos, particularmente en el caso en que hayan dos días que no compartan el mismo módulo.
Por ejemplo, si tengo clase el lunes módulo 3 y el viernes módulo 4 tengo el siguiente diccionario:

{
 "AYU": [],
 "CLAS": [("L", 3), ("V", 4)],
 "LAB": [],
 "LIB": [],
 "PRA": [],
 "SUP": [],
 "TAL": [],
 "TER": [],
 "TES": []
 }

¿Pero cómo se vería su string? No se especifica este caso en el enunciado. 
Sería algo así:

"AYU;CLAS#L:3,V:4;LAB;LIB;PRA;SUP;TAL;TER;TES"

Y en ese caso, cómo se vería un lunes módulo 3, miercoles módulo 3 y viernes módulo 4.
¿Así?
"AYU;CLAS#M,L:3,V:4;LAB;LIB;PRA;SUP;TAL;TER;TES"

**Comment by igbasly** [comment]
@raimundomartinez :v:

Para los casos en que el horario de una clase no compartan día ni modulo específico, el separador que se utiliza es `"#". Así puedes ver que cada tipo de actividad estará separada por `";"` y dentro de ella los diferentes horarios con `"#"`.
Para el ejemplo que me planteas en particular, su *string* se vería así:
```json
    "Modulos": "AYU;CLAS#M,L:3#V:4;LAB;LIB;PRA;SUP;TAL;TER;TES"
```
**De todas formas, puede asumir que no ocurrirá esto con las bases de dato dadas y omitir este caso en particular.**

Saludos y éxito en la actividad 🙌 .

**Comment by JaviGuzman** [comment]
Hola! Me queda una duda de esta aclaración. El caso que podemos omitir es el segundo, que no habrán dos días que compartan horario y otro día que no comparta? O ambos ejemplos que plantean, considerando también el primero que pueden haber dos días distintos con distintos horarios?

Gracias de antemano! 😄

**Comment by igbasly** [comment]
Hola @JaviGuzman :v:

Disculpa la demora, en este caso se puede asumir que no habrán días distintos con módulos distintos, es decir, que solo habrá diferentes días (uno o más) que comparten mismos módulos (uno o más).
Algunos ejemplos de casos considerados:
`"...;CLAS#L,W,V:1,2,3;..."`
`"...;CLAS#S:2,4;..."`
`"...;CLAS#M,J:5;..."`

**El ejemplo que se menciona arriba `"...;CLAS#M,L:3#V:4;..."` no se considera y se puede omitir.**
Mucho éxito :muscle:.

**Comment by JaviGuzman** [comment]
Hola @igbasly, gracias por la respuesta, pero no me queda claro cómo sería el primer ejemplo que das.
`L:1, W:2 y V:3?`
 o 
`L:1,2,3 - W:1,2,3 - J:1,2,3 ?`

Ya que si es el primer caso, no veo la diferencia con el ejemplo que no se considera y se puede omitir.

Perdón por la insistencia, que no me queda 100% claro

**Comment by igbasly** [comment]
No hay problema 😅, para este caso en particular `"L,W,V:1,2,3"` diremos que los tres días `"L, W, V"` comparten los mismo módulos `"1, 2, 3"`, por lo tanto, para cada día debes agregar los tres módulos resultando lo siguiente:
```python
"CLAS": [
  ("L", 1), ("L", 2), ("L", 3),
  ("W", 1), ("W", 2), ("W", 3),
  ("V", 1), ("V", 2), ("V", 3)
  ]
```
Espero que quede más claro, estaré atento en caso de más dudas :v:

**Comment by JaviGuzman** [comment]
Muchas gracias!!
