### ISSUE TITLE
¿Librería itertools permitidas en evaluación recuperativa?

### ISSUE THREAD

**Issue by benjavicente** [IIC2233/syllabus#1321]
Hola! 

¿Se pueden utilizar librerías adicionales para la evaluación, como por ejemplo, `itertools`?

Gracias de antemano!

**Comment by fdoflorenzano** [comment]
Hola @benjavicente,

¿Puedes ser más específico con que parte de `itertools` deseas utilizar y para qué?

Saludos.

**Comment by benjavicente** [comment]
Para la función `product`, para sacar el [producto](https://en.wikipedia.org/wiki/Rule_of_product).
No se si mencionar _para qué_ sería dar una solución 👀

**Comment by fdoflorenzano** [comment]
Hola @benjavicente,

Sí, se puede utilizar `product` de `itertools`.

Saludos.
