### ISSUE TITLE
Test #0 traducir_modulos sale un {} vacio, ese cuenta como test?

### ISSUE THREAD

**Issue by FCamaggi** [IIC2233/syllabus#1322]
Al momento de correr test.py me tira un error el test 0 y al verlo es un diccionario vació, ¿esto esta a propósito así? y si es el caso, ¿debemos tomarlo en cuenta? ya que no veo un caso donde ese diccionario sea vacío.

**Comment by aaossa** [comment]
Hola @FCamaggi ,

Ese *test* está ahí solamente para mostrar que en caso de producirse una excepción en la función que se está evaluando, el código continúa ejecutando los demás casos de prueba. Esto mismo está comentado en el archivo, después del `if __name__ == "__main__":`.

https://github.com/IIC2233/syllabus/blob/c249c455c859df4e725bb62f5eaa821db8a9f7a5/Recuperativa/test.py#L75-L77

En el enunciado no se especifica que deba ocurrir alguna excepción específica o que deban hacer algo al respecto, así que siéntete libre de eliminar ese caso de prueba. Espero eso responda tu pregunta ✨

**Comment by FCamaggi** [comment]
Ya perfecto, muchas gracias
