### ISSUE TITLE
Consulta "filtrar_por_modulos" cómo filtrar mas de un modulo

### ISSUE THREAD

**Issue by FCamaggi** [IIC2233/syllabus#1323]
Al momento de filtrar si uso los módulos ('J',5), ('V', 5) ¿debo incluir solo secciones que tengas actividades en ambos módulos o con solo tener uno satisface la condición?

**Comment by fdoflorenzano** [comment]
Hola @FCamaggi,

Con solo tener uno satisface la condición. La frase *"...con alguna actividad durante esos módulos"* se refiere a eso, que basta con que coincidan en un módulo. 

Saludos.

**Comment by FCamaggi** [comment]
Yap, muchas gracias

**Comment by Tsbalart** [comment]
Me surgió una duda con esto, ya que en la frase que menciona dice "...con alguna actividad durante ESOS módulos", no significa esto que debería tener actividades en todos los módulos seleccionados. (así es como funciona Buscacursos)

**Comment by fdoflorenzano** [comment]
Hola @Tsbalart,

Como dicho en mi comentario anterior, no se refiere a eso. 

Saludos.
