### ISSUE TITLE
Cliente recive strings vacios (creo???)

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#1324]
Estoy tratando de implementar un protocolo en el que se manda primero un numbero que indica que va a mandar y despues el contenido, pero al imprimir lo que recive el cliente entra en un loop imprimiendo strings vacios. Por que pasa esto?

**Comment by fdoflorenzano** [comment]
Hola @sofiuni,

No estoy seguro si logré reproducir el error. ¿Podrías indicar como se ejecuta el programa en tu repositorio? 

De todas formas, en mi experiencia, lo que indicas sucede cuando alguno de los programas se cae o cierra pero no cierra el *socket* por el que interactuá con el otro programa. Por lo que indicas, es posible que el servidor se haya caído y el cliente se quedó escuchando un *socket* que no recibe nada nunca. Fíjate que el programa del servidor siga funcionando como corresponde.

Saludos.
