### ISSUE TITLE
Formato diccionario retornado por filtros

### ISSUE THREAD

**Issue by inarrgd** [IIC2233/syllabus#1325]
Me surgió la duda con el retorno de dicha función del módulo consultas.py, debido a que no se especifica la llave que debe tener el diccionario que se retorna, debe ser la sigla o el nombre del input curso?

Además, éste diccionario debe contener como valor los valores de los cursos en formato diccionario como se encuentran en la parte de cargar cursos, o las siglas o nombres?

Por último, en caso de que el curso tengo más de un prerrequisito, qué llaves se utilizan?

Muchas gracias! Saludos

**Comment by fdoflorenzano** [comment]
Hola @inarrgd,

El formato del diccionario entregado por todos los filtros se menciona en el párrafo previo al listado de filtros en el enunciado. Este dice que retornan un diccionario con la misma estructura que el diccionario `dicc_de_cursos`, el cual a su vez sigue el formato especificado en la sección de Representación de cursos.

Saludos.

**Comment by inarrgd** [comment]
Comprendo, de todas maneras, al generar el diccionario, tengo como llaves las siglas de los cursos prerrequisitos, y como valores el contenido original de cada uno generado en cargar_cursos, pero al utilizar la interfaz, me aparece el siguiente error:

for info_sec in info["Secciones"].values():
KeyError: 'Secciones'

Siendo que al menos ya tengo bien la parte de cargar cursos, y traducir módulos, por lo que no entiendo cuál es el problema.

Muchas gracias!

**Comment by inarrgd** [comment]
Me quedó claro, muchas gracias.
