### ISSUE TITLE
Duda sobre filtro por cupos

### ISSUE THREAD

**Issue by pablosbw** [IIC2233/syllabus#1326]
Hola, tengo una pequeña duda relacionada con filtrar por cupos, si no entiendo mal, cuando vemos los cupos tenemos que ver los cupos totales de las secciones, por ejemplo si IIC2233 tiene 3 secciones con 0, 3 y 7 vacantes disponibles y filtro por cursos que tengan mas vacantes que 5, el diccionario retornado debería contener a las 2 secciones que tienen 3 y 7 vacantes? (a pesar de que una en particular tiene menos que 5).

**Comment by fdoflorenzano** [comment]
Hola @pablosbw,

La consulta filtra a nivel de secciones, no a nivel de curso completo. Solo deja aquellas secciones que por si solas tengan las vacantes disponibles solicitadas. En tu ejemplo, solo la sección con 7 vacantes cumple y deberá aparecer en el resultado.

Espero se entienda,
Saludos.

**Comment by pablosbw** [comment]
Muchas gracias profe, me quedó claro.
