### ISSUE TITLE
Formato lista de Prerrequisitos

### ISSUE THREAD

**Issue by gianlucafalcone** [IIC2233/syllabus#1327]
Hola!. 
Tengo una duda respecto al enunciado en la parte de prerrequisitos. Como dice el enunciado "Es necesario transformar el valor en una lista de prerrequisitos que solo contengan cursos IIC", mi duda es si a los cursos que no tenían prerrequisitos y a los que solo tenían prerrequisitos de otras siglas se les debe asignar una lista de forma [] o [""].

Gracias.

**Comment by igbasly** [comment]
Hola @gianlucafalcone :v:

Lo correcto en esos casos sería una lista vacía, ya que de lo contrario la lista contendría un *string*, que pese a no decir nada contradice al enunciado al pedir *”... que solo contenga siglas IIC”*.

Éxito :raised_hands:

**Comment by gianlucafalcone** [comment]
Gracias!
