### ISSUE TITLE
Cursos duplicados en Prerrequisitos

### ISSUE THREAD

**Issue by josefeliuf** [IIC2233/syllabus#1328]
Hola!
Está bien que hayan cursos que tengan como prerrequisitos dos veces el mismo curso? como por ejemplo "Programación como herramienta para la Ingeniería" tiene dos veces el curso "IIC1102"

**Comment by igbasly** [comment]
Hola @josefeliuf :v:

Efectivamente esto no debería ocurrir, muchas gracias por avisarnos. Puedes programar asumiendo que en prerrequisitos solo habrá siglas únicas.

**Por lo mismo, ya puedes actualizar la bases de datos actualizados haciendo `git pull` en el syllabus.**

Discúlpanos y mucho éxito :muscle:.

**Comment by josefeliuf** [comment]
Oka! muchas gracias
