### ISSUE TITLE
Importar archivos Csv

### ISSUE THREAD

**Issue by AngelMatias** [IIC2233/Syllabus#133]
Hola, yo creo que demas ya la han respondido, pero tienen alguna forma oficial de importar las listas csv? si es asi cual es? hice intro a la progra hace como 6 años y entenderan que el contenido que recuerdo es igual a 0 😓

**Comment by andresfdezc** [comment]
[Aquí](https://github.com/IIC2233-2016-1/syllabus/tree/master/Repaso-IIC1103) hay un repaso de Introducción a la Programación. Ahí puedes ver cómo abrir archivos.

**Comment by fnquinteros** [comment]
Hola! 

Se te permite usar unicamente el buen y viejo open(), si no recuerdas bien como usarlo, puedes buscar en Google la documentación :) 

Saludos!

**Comment by fdominguezclaro** [comment]
Respondiendo también un poco tu pregunta, no hay una forma "oficial" de abrir los .csv
Prueba a abrirlo y leerlo como un archivo normal.

**Comment by AngelMatias** [comment]
perfect, entiendo ! 
pero en la lista users, que significa la columna orders: list ??
se supone que es el orden del usuario si este esta en una lista ?

**Comment by fnquinteros** [comment]
Revisa el enunciado, ahí está la respuesta a tu pregunta 😅 saludos

**Comment by AngelMatias** [comment]
Ups, gracias 😅
