### ISSUE TITLE
opciones menu inputs

### ISSUE THREAD

**Issue by santiago3c** [IIC2233/Syllabus#133]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* X[ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, con respecto al menu tengo la duda si hay que considerar crlt + c como entrada, si me lo pueden aclarar por favor

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by roahoki** [comment]
Hola @santiago3c! Lamento lo tarde de la respuesta. Respecto a tu pregunta, si es que te refieres al menú inicial, solamente debes esperar un input de [usuario] [nombre_tablero], esto será de la forma “python3 main.py [usuario] [nombre_tablero] tal como se comenta en el enunciado. Si es que continuas con la duda, por favor vuelve a responder esta issue.
