### ISSUE TITLE
¿Dónde se colocan las entidades y los inputs del usuario?

### ISSUE THREAD

**Issue by golosinas** [IIC2233/Syllabus#133]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo dos preguntas:

1. ¿Las entidades se definen en el mismo archivo donde definimos el flujo del juego? Es decir, en un archivo main.py, ¿o las definimos en parametros.py, o creamos otro archivo por completo para definirlas?

2. Lo mismo me pregunto sobre los inputs. Al decir que no podemos tener variables globales, esto significa que, las variables asiganadas a los inputs del usuario ¿también serán definidas en el archivo parametros.py? ¿O pueden/deben ir en el archivo principal donde se encuentra el flujo del juego?

Saludos y gracias de antemano. 😅

**Comment by Rotopikus** [comment]
Hola!!!

En primer lugar parametros.py es un archivo que contiene variables que son fijas para cualquier ejecución de tu código. Sirve principalmente para no hacer hardcoding. Por esto no debes definir clases o funciones aquí.

Con respecto a tu primera pregunta, queda a tu criterio como modularizar correctamente tu código (recuerda especificarlo en el Readme). Pero ten cuidado con no pasar las 400 líneas por archivo. 

Con respecto a tu segunda pregunta, para no usar variables globales, lo que puedes hacer es definir las variables (por ejemplo los inputs) dentro de una función o una clase.

Si te queda alguna duda con la explicación, no dudes en preguntar. Éxito!!
