### ISSUE TITLE
gitignore, README y README BASE

### ISSUE THREAD

**Issue by ssepul21** [IIC2233/Syllabus#133]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!
 En los archivos que hay que subir en la tarea, hay que omitir el archivo "README" que contiene las modificaciones? Van a aceptar que el README con la información de nuestro code se llame "README BASE" o debo cambiarle el nombre? 
 Lo pregunto para ver si debo incluirlo en el .gitignore, ya que no se especifica en el enunciado

Saludos!

**Comment by MaxAl100** [comment]
Hola! Debes subir un solo README, el BASE es para que tengas una base (😮) para hacer tu README. El otro lo puedes eliminar o ignorar, como prefieras.

**Comment by ssepul21** [comment]
Entiendo! Gracias ;)
