### ISSUE TITLE
Consulta formato de escritura e inputs

### ISSUE THREAD

**Issue by fernandolalanne** [IIC2233/syllabus#133]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
Hola!! quería preguntar dos cosas. La primera es sobre el formato de los inputs que deben tener la tarea. Sucede que al crear el código todos los inputs se deben ingresar escribiendo strings y ingresando números como sale en ejemplos de códigos de la tarea entonces quería saber si existe alguna restricción sobre como deben ser los inputs, por ejemplo, si deben ser strings, int, o cualquier formato es válido.

En segundo lugar, leí issues pasadas pero no me quedaron claras las respuestas y por eso pregunto nuevamente. Cuando debo utilizar la función VOLVER_FRASE o ABANDONAR_FRASE ¿en qué formato se deben utilizar? Por ejemplo lo que tengo hasta ahora es algo como

if input == VOLVER_FRASE:
    pasa algo
elif input == ABANDONAR_FRASE:
    pasa otra cosa

entonces quería saber si la forma en que presento el código es correcta o debo utilizar los comandos como \Salir o \volver, que corresponden a los valores de los parámetros entregados en un archivo.py de la T0. Y de ser correcto esto último el código debería verse como
if input == Volver:
    pasa algo
elif input == Salir:
    pasa otra cosa

Desde ya muchas gracias!
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by matiasmasjuan** [comment]
Hola @fernandolalanne !

Responderé a ambas preguntas por separado:

1. No existe ninguna restricción de cómo deben ser los *inputs*. Estos pueden ser tratados como *strings* o convertidos a *int*. En el enunciado se muestra el ejemplo de desplazarse entre menús utilizando los inputs como numéros, lo cual puede servir como ejemplo guía para la tarea (*Issue* #47 ).

2. Según la *Issue* #129 debes ser capaz de **importar** los parámetors ***VOLVER_FRASE*** y ***ABANDONAR_FRASE*** y utilizarlos en tu código. En ese sentido el primer ejemplo que señalaste sería el adecuado para esta tarea. La idea de importar este tipo de parámetros es que tu código sea fácil de modificar y sea **escalable**. Esto quiere decir que en caso de querer cambiar el input que se debe ingresar para volver o para abandonar un grupo, basta con cambiar estos valores directamente en el archivo ```parametros.py``` y no tener que ir a buscar en **todo** el código las líneas exactas de los valores y cambiarlos manualmente. Si bien en esta tarea puede que no sea tan complejo, al momento de trabajar con múltiples módulos si puede resultar sumamente complejo, por lo que utilizar **parámetros** e importarlos es considerado una buena práctica.

Espero haber respondido a tus preguntas, y mucho éxito con la tarea! :smile:

**Comment by fernandolalanne** [comment]
Perfecto!! La ultima duda, que no me quedó muy claro, es si me puedes explicar cómo funciona el código de importar parámetros.py porque lo que yo tengo hasta ahora es el primer código que escribí pero no importé ningún parámetro porque no cachaba bien cómo funciona, por ejemplo, qué implica el \salir que es el valor de ABANDONAR_FRASE, es decir, cómo sabe mi código qué significa \salir.

Gracias!

**Comment by matiasmasjuan** [comment]
Hola @fernandolalanne !

El código va a saber que el valor de la variable ***ABANDONAR_FRASE*** equivale a *\\\salir* debido a que así está definido en el archivo ```parametros.py```. Lo único que debes hacer es importar el módulo o importar los valores del modulo para poder ser utilizados en el archivo de tu código principal. En la sección de [contenidos/semana-00](https://github.com/IIC2233/contenidos/blob/main/semana-00/2-modularizaci%C3%B3n.ipynb) podrás encontrar ejemplos de cómo importar parámetros.

Saludos! :smile:

**Comment by Ignacioislae** [comment]
Disculpa no entendi. ¿Si el parametro ABANDONAR_FRASE equivale al string "\\volver", mi programa debe reaccionar con el input \volver (que es lo que vale \\volver al ingresarlo como parametro) o con \\volver que son los caracteres originales?

**Comment by matiasmasjuan** [comment]
Hola @Ignacioislae !

Debe reaccionar con el input del parámetro *ABANDONAR_FRASE*, independiente del valor que tenga. La idea es que reaccione directamente con el parámetro, no su valor. Por ejemplo, si queremos abandonar el grupo con el input *\exit*, solo se debe cambiar el valor de *ABANDONAR_FRASE* por *\exit*. En ese sentido, no es necesario tener que recorrer **todo** el código para buscar la sentencia de if input() == "\volver" y cambiarla por if input() == "\exit", ya que podría resultar muy tedioso.

Espero haber respondido a tu pregunta! Saludos! :smile:

**Comment by Ignacioislae** [comment]
@matiasmasjuan si, entiendo la parte de usar parametros. Mi pregunta va mas para al caso especifico de strings que guardamos con doble backslash porque su valor no es igual a los caracteres con que lo guardamos. ¿Como quieren que reaccione nuestro programa ante estos? 
Adjunto foto explicativa:
![imagen](https://user-images.githubusercontent.com/53800034/113078497-99c11300-91a9-11eb-9403-67ebe403f791.png)

**Comment by matiasmasjuan** [comment]
Efectivamente, este problema se debe a cómo *python* interpreta el "*\\*" en los *strings*. En el caso específico que mencionas, si el parámetro **VOLVER_FRASE** equivale a *"\\\volver"*, la idea es que el *input* ingresado sea *\\volver*. De todas formas, evitaremos poner valores de parámetros con varios *backslash* ya que podrían conducir a este tipo de problemas.

Saludos! :smile:
