### ISSUE TITLE
Instalar jupyter

### ISSUE THREAD

**Issue by misantacruzc** [IIC2233/syllabus#133]
- **Sistema Operativo:** mac
- **Programa a instalar:** jupyter

Realizo todos los comandos para instalar jupyter según lo que subieron. Y luego al intentar abrir jupyter notebook, me sale que el comando jupyter no se encuentra. 
Especificamente sale "-bash: jupyter: command not found"

**Comment by MatiasDuhalde** [comment]
Hola!

A veces los sistemas operativos ponen problemas para correr los comandos que no están instalados por defecto desde la consola. Generalmente se debe a que el directorio donde están instalados no se encuentra en la _variable de entorno_ **PATH**. La forma estándar para iniciar jupyter es con el comando:

`jupyter notebook`

Supondré que este comando no sirve en tu terminal, así que te recomiendo los siguientes pasos. Primero que nada, intenta correr el siguiente comando:

`python -m pip freeze`

Este comando lista todos los paquetes de python que están actualmente instalados en tu computador. Si no te deja correrlo es porque python no se encuentra en **PATH**, por lo que te recomiendo reinstalar Python (asegurate también de que tengas Python 3.7 o superior, no Python 2). Si es que el comando te corre y encuentras jupyter notebook en la lista, intenta abrir jupyter usando:

`python -m jupyter notebook`

Y si no aparece, debes instalarlo con `python -m pip install jupyter` tal como recomienda la wiki. Avisanos en esta issue si te funciona!

**Comment by tzehnder** [comment]
hola reinstale python 3.7 en mi pc (windows 10) pero no logro instalar jupyter, al intentar ejecutar el siguiente comando no me funciona sino que se salta una linea y vuelve a darme la opcion de escribir...
C:\Users\tomas\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.7>python3 -m pip install --upgrade pip

C:\Users\tomas\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.7>

tambien descargue el zip que en un video salia que era necesario para utilizar el pip Windows (x86-64 embeddable zip file) pero sigue sin funcionarme.

**Comment by MatiasDuhalde** [comment]
Hola @tzehnder !

Prueba en vez de usar el comando `python3` usar solamente `python`. Originalmente se usaba `python3` para hacer la distinción entre la version 2 y la versión 3 de Python, pero si nunca instalaste Python 2 en tu computador, el comando `python` va a ejecutar la versión 3 por defecto.

Salu2

**Comment by misantacruzc** [comment]
Hola!
Realice lo que me dijiste y al escribir python3 -m pip freeze me corre pero no me aparece jupyter notebook. Luego instalo jupyter y vuelvo a correr python3 -m pip freeze y sigue sin aparecer jupyter notebook.
Por lo mismo sigo sin poder abrirlo.

**Comment by aaossa** [comment]
@misantacruzc intentaste instalar jupyter con `python3 -m pip install jupyter`? Si no lo hiciste así, ¿qué comando usaste?¿Y te funciona el comando que escribí?

**Comment by MatiasDuhalde** [comment]
Hola!

Que aparece en tu consola exactamente cuando intentas instalar jupyter?
Se me ocurre que puede ser un error de privilegios. Intenta con `sudo python -m pip install jupyter` o con `python -m pip install --user jupyter`.

**Comment by misantacruzc** [comment]
Si intalo jupyter con el comando python3 -m pip install jupyter y me aparecen muchas líneas parecidas; adjunto una foto de las ultimas líneas.
Intente instalarlo con lo que me dijiste @MatiasDuhalde y sigue sin funcionar. Sigue saliendo que no encuentra el comando jupyter
<img width="571" alt="Sin título" src="https://user-images.githubusercontent.com/62073761/77214047-e0d2ed80-6aeb-11ea-968f-e12e8b271956.png">

**Comment by MatiasDuhalde** [comment]
Hola!

Me parece raro que no puedas correr `python3 -m jupyter notebook`. Según el output, los paquetes ya están en tu computador cuando intentas instalar. Lo único que se me ocurre es que haya habido un error en la instalación, así que te recomiendo reinstalar los programas de la siguiente forma.

`python3 -m pip uninstall jupyter`
`python3 -m pip uninstall notebook`
_Nota: **Te va a pedir confirmar tu decision, basta con que pongas "y" cuando lo haga**_

Luego para reinstalar los programas, basta con correr el comando de antes:
`python3 -m pip install jupyter`

Avísanos si cambia algo!

**Comment by misantacruzc** [comment]
Perfecto ahí me funciono!
Muchisimas gracias.
