### ISSUE TITLE
Encuesta Carga Académica sale cerrada

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#133]
Hola, abrí el link para la ECA minutos después de que me llegó al mail, y sale esto. Dejo pantallazo completo para que se vea link, fecha y hora 😢 
![image](https://user-images.githubusercontent.com/61999464/90990212-855ecd00-e56d-11ea-94a5-3e705666a140.png)
¿Soy yo o es la ECA?

**Comment by tcouso** [comment]
Me pasó lo mismo, será un error?

**Comment by lsschmitz** [comment]
Confirmo, me paso lo mismo

**Comment by Mamunoz42** [comment]
http://eca.ing.uc.cl/encuesta  
Este es el link

**Comment by lily416** [comment]
Ayer en la noche, el equipo de la ECA mandó un correo avisando que hubo un error con la plataforma y que el problema ya fue corregido, por lo que ya no deberían tener problemas para contestar la ECA.

Si siguen teniendo problemas para contestar la ECA, deben escribir un correo a [eca@ing.puc.cl](mailto:eca@ing.puc.cl) y, dentro de lo posible, traten de incluir pantallazos del error que les aparece.

Saludos y éxito en la semana 👋📝

**Comment by sbcorrea** [comment]
Me funcionó al final solo el link que daba @Mamunoz42, y no el del mail oficial del equipo ECA. Muchas gracias!
