### ISSUE TITLE
Avance Tarea

### ISSUE THREAD

**Issue by Pdesolmi** [IIC2233/syllabus#133]
Es obligación entregar un avance?, o es solo para optar a las décimas adicionales.

Gracias

**Comment by jeschuwirth** [comment]
Saludos,

El avance de esta tarea es entregar el diagrama para el miércoles 4, este avance va a entregar 2 décimas adicionales a la nota, además de esto, en la entrega final también se tiene que entregar el diagrama y este va a ser evaluado.

Te recomiendo hacer el diagrama hoy si no lo has hecho, ya que lo vas a tener que hacer de todos modos y hacerlo hoy te permitirá ganar 2 décimas extra (además de que te va a ayudar a guiarte para escribir tu código).

Suerte!
