### ISSUE TITLE
Opción "Guardar cambios"

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#133]
La opción de guardar los cambios realizados debe ejecutarse siempre que ocurra algo en particular o sólo cuando el usuario presiona dicha opción? Es válido si en mi código, el único momento en que se pueden guardar los cambios es cuando el usuario decide hacerlo? Puedo simplemente especificar eso último en el README?

**Comment by Arcoirisky** [comment]
Hola! Revisa la issue #131 a ver si responde tu duda :D

**Comment by ptflores1** [comment]
puede que #52  tambien te sirva 
Saludos !

**Comment by llloyola** [comment]
Entonces no es factible especificar en el readme que quiero guardar cambios sólo cuando el usuario lo desee? Cualquier galaxia creada o modificada hace que se guarden automáticamente los cambios realizados?

**Comment by Hernan4444** [comment]
@llloyola no es factible eso, el readme se utiliza para especificar algo que quedó a tu criterio en la tarea, pero en el enunciado se dice que crear un planeta altera de inmediato la base de datos, por lo tanto no es decisión del usuario si lo guarda o no. Lo que si es cierto, es que en la parte de modificar no quedó especificado eso de la base de datos. Ahí si puedes tomar alguna decisión de cuando guardar esas modificaciones (de inmediato o a través de una opción).

Saludos ✌️
