### ISSUE TITLE
Dudas diagrama de clases

### ISSUE THREAD

**Issue by malopez16** [IIC2233/Syllabus#133]
Hola!
Para el diagrama de clases, 
¿Hay alguna forma especial de escribir las properties o como un método cualquiera?
Si tengo un par de clases cuya relacion es de herencia y composición (tal como una clase abstracta), ¿cómo se unen entre sí?

**Comment by rrhurtado** [comment]
@malopez16
Como escribas las properties queda a tu criterio siempre que se entienda, pero si quieres ahondar más en el tema -> [https://goo.gl/q8qiNv](url) 
En el caso de una clase abstracta predominaría la herencia sobre la relación de composición, espero te ayude ese tip.
Saludos !

**Comment by akaminetzkyp** [comment]
Hola! El link de arriba no esta funcionando. Saludos!

**Comment by Hernan4444** [comment]
https://goo.gl/q8qiNv
