### ISSUE TITLE
Duda función "Filtrar por prerrequisitos"

### ISSUE THREAD

**Issue by josefeliuf** [IIC2233/syllabus#1330]
Hola!
En el enunciado dice que la función debe retornar un diccionario. Mi duda es, ¿Qué llave y valor debe llevar este? creo que no lo especifica. Lo digo porque se me haría más lógico que retorne una lista con los cursos que son prerrequisitos.

**Comment by fdoflorenzano** [comment]
Hola @josefeliuf,

Esto se responde en #1325 .

Saludos.

**Comment by josefeliuf** [comment]
oka! muchas gracias
