### ISSUE TITLE
Múltiples palabras en argumento de funcion "filtrar por" para profesores

### ISSUE THREAD

**Issue by gianlucafalcone** [IIC2233/syllabus#1331]
Hola!
Tengo una duda con el string que recibe esta función, en concreto mi duda es si es posible que se entreguen string de mas de una palabra, por ejemplo, en vez de entregar "cris" al filtrar por profesor se entregue "cris ruz". De ser así, ¿se debe tomar como que se está buscando al profesor Cristian Ruz o se debe ignorar?

Gracias!

**Comment by fdoflorenzano** [comment]
Hola @gianlucafalcone,

Es posible que el valor de `string` tenga múltiples palabras, pero no es necesario que las consideres como diferentes valores por la presencia por un espacio, debes considerarla como una única cadena y ver si el su valor completo está presente donde se busque.

En tu ejemplo, si se entrega `"cris ruz"` para filtrar por profesor, no entregaría a `"Cristian Ruz"` ya que no hay contención directa. Si existiesen profesores llamados `"Cris Ruz"` o `"Juan Cris Ruz"`, entonces a ellos sí.

Espero se entienda,
Saludos.

**Comment by gianlucafalcone** [comment]
Si se entendió, gracias.

**Comment by rldelafuente** [comment]
Hola! Me sumo a la pregunta con respecto a los argumentos de la función `filtrar_por()`, con relación a los profesores. 
¿Puede que una sección tenga más de un profesor o siempre tiene uno?

Si tiene más de uno:
- ¿Cómo se separan los profesores? ¿Con `","` , `";"` ?
- Si se indican los dos profesores al mismo tiempo, como por ejemplo "Juan Cris Ruz Cristian Ruz", ¿debería funcionar el código, filtrando el ramo que hacen estos dos profesores juntos?

Gracias de antemano!

**Comment by fdoflorenzano** [comment]
Hola @rldelafuente,

Puede que una sección tenga más de un profesor, pero **no es algo de lo que deban preocuparse o cubrir**. Como dice el enunciado, solo debe revisarse que el argumento `string` esté contenido en el valor correspondiente. Eso pasa tanto para NRC, Nombre, Sigla y Profesor.

De todas formas, como aclaración, al haber dos profesores, y se separan por coma y un espacio. Como consecuencia a lo dicho, el filtro **solo** cumpliría si hay una contención textual. Por ejemplo, hay una sección con valor de profesor **`"Baier Jorge, Lobel Hans"`**, donde los siguientes *strings* si están contenidos: `"baier jorge"`, `"lobel Hans"`, `"jorge, Lobel"`, `"ge, l"`, etc... Mientras que **no** a `"jorge baier"` (por el orden), `"jorge lobel"` (falta la coma). `"baier hans"` (falta mucho contenido para hacerlo calzar). Sería un filtro medio "malo" para el usuario, pero de nuevo, no es necesario que cubran ese caso específico.

Espero se entienda,
Saludos.

**Comment by Juampisaez** [comment]
No me queda claro como debe ser el criterio de busqueda en filtrar por para profesores, nombre del curso, sigla o nrc. Para filtrar los cursos, el string debe estar contenido en alguna de las llaves del dict? Para el caso de los profesores lo entiendo, si busco "cris" deberian filtrarse todos los profes que se llamen cristian o su nombre tenga relacion con el string. Pero en el caso de los nombres del curso, nrc o sigla, funciona igual?

**Comment by Alonsinho1** [comment]
Hola @Juampisaez, si insertas un string que no este dentro de los cursos deberia retornar un dict vacio o  una solucion similar. Mas que la key lo que debes buscar es que el string indicado este dentro del valor del diccionario cuando le entregas la llave "Nombre" o "NRC". imagínate que curso es el diccionario que contiene toda la informacion del curso. Luego, lo que deberias buscar es que el string que insertes este contenido dentro de curso["Nombre"] o curso["NRC"].  Ojala haya qeudado un poco mas claro.

**Comment by Juampisaez** [comment]
Claro, entiendo eso, pero tengo dos dudas.
- Si busco "progra" en el nombre del curso me deberia tirar introduccion a la proramacion, programacion avanzada, etc. Si busco "iic" o "2233" en sigla me deberia dar todos los cursos que tengan ese string en la sigla. Creo que eso es lo que se pide o no?
- Pero en caso del NRC, si busco "1" me debe mostrar todos los casos en que el "1" se encuentra en el NRC ? en ese caso me mostraría muchos cursos. Lo pregunto porque en el buscacursos de la universidad, si pongo "1" en el NRC, no me muestra ningun curso. Como debe ser el criterio en esta parte entonces?

**Comment by Alonsinho1** [comment]
Lo que dice en ambos casos es lo que deberia pasar. Con tal solo insertar el 1 te deberia salir todos los cursos que contengan el 1. La gracia de esto es que el sistema es un poco mas sensible en el caso de que se haya insertado un error y no necesariamente lo debereras buscar exacatamente como se pide. Que la funcion retorne muchos cursos no es un problema.

**Comment by Juampisaez** [comment]
Muchas gracias, ahora si me aclare!
