### ISSUE TITLE
¿Librería copy permitida en la tarea recuperativa?

### ISSUE THREAD

**Issue by Antonio-Fernandez-R** [IIC2233/syllabus#1332]
Hola, quería saber si la librería copy se puede usar. Específicamente la función deepcopy().

**Comment by fdoflorenzano** [comment]
Hola @Antonio-Fernandez-R,

Sí, puedes utilizar `deepcopy` de `copy`.

Saludos.

**Comment by Antonio-Fernandez-R** [comment]
Gracias!
