### ISSUE TITLE
Distintos tipos de módulos

### ISSUE THREAD

**Issue by JaviGuzman** [IIC2233/syllabus#1333]
Hola! No me quedan claro cuales son los módulos que debemos traducir, ya que al principio dice que son 7 tipos de módulos, que son los posibles valores de llaves:
AYU, CLAS, LAB, PRA, TAL, TER y TES.

Pero luego en el ejemplo aparecen 2 tipos más que son LIB y SUP.

Estos 2 tipos de módulos extras debemos eliminarlos, dejando solamente los 7 posibles valores de llave, o debemos considerar los 9 tipos de módulos?

Gracias!!

**Comment by igbasly** [comment]
Hola @JaviGuzman :v:

Los módulos que se deben considerar son los mencionados en el enunciado como posibles valores:
`"AYU", "CLAS", "LAB", "PRA", "TAL", "TER", "TES"`
Los otros dos `"LIB"` y `"SUP"` no son necesarios, así que puedes omitirlos y asumir que no estarán, ya que serán removidos pronto de las bases de datos.
De todas formas, si estás haciendo un proceso automático para convertirlos a un diccionario, no te preocupes por revisar si son alguno de estos y quitarlo, simplemente asumen que no estará y no se utilizarán.

Saludos y éxito en la actividad 🙌 .
