### ISSUE TITLE
Label cortado

### ISSUE THREAD

**Issue by dcastillo5** [IIC2233/syllabus#1334]
Holaa!
Un comentario que tuve en la T02 fue que muchos label  se veían cortados,  sin embargo cuando ejecuto la tarea  a mi me  aparecen en el tamaño correcto y completos.  Me gustaría saber por que ocurre este cambio y como evitarlo. 
Vale aclarar que la mayoría los hice directamente en Qt Designer y no creo que sea un problema de escalar imagen. 
Gracias !!

**Comment by lily416** [comment]
Hola, tengo una idea de lo que podría ser. Para confirmarlo me podrías indicar tu sistema operativo y agregar una foto de como se una de las pantallas. :)

**Comment by dcastillo5** [comment]
Tengo macOS. 
No entendí cual pantalla mostrarte jaja te dejo una del Qt Designer mientras tanto 
![Captura de pantalla 2020-07-08 a las 2 21 39 p m](https://user-images.githubusercontent.com/61330735/86955757-1694f400-c126-11ea-8603-01ac1904a0ec.png)

**Comment by lily416** [comment]
El problema que normalmente pasa normalmente cuando una interfaz se crea con QtDesigner en MacOS y posteriormente se corre en Windows.

Por ejemplo, así se ve la misma ventana en Windows:
![image](https://user-images.githubusercontent.com/26393515/86969444-cc1e7200-c13b-11ea-811a-5b62d2524b4c.png)

Y así se ve la ventana de juego:
![image](https://user-images.githubusercontent.com/26393515/86969637-199adf00-c13c-11ea-95f0-0a21665bdc9b.png)

No sé específicamente lo que lo causa, pero si se me ocurre cómo evitarlo. 😅 

Debe haber más de una forma de arreglarlo, pero hay dos que se me vienen a la mente: 
1. Puedes crear la interfaz directamente por medio de código.
1. Puedes fijar para todos los _labels_ una fuente y su tamaño. Generalmente puedes hacerlo seteando la fuente en el elemento principal que contenga al resto, en tu caso sería la _MainWindow_ o el _CentralWidget_.

   Para settear la fuente, puedes hacerlo por medio del _"property editor"_ o usando _"Change StyleSheet"_.

   Pero para lo que te nombro anteriormente pueda funcionar, debes tener ojo con los _labels_, ya que cuando se guarda el texto 
   estas usando texto enriquecido:
   ```html
   <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
   <html><head><meta name="qrichtext" content="1" /><style type="text/css">
   p, li { white-space: pre-wrap; }
   </style></head><body style=" font-family:'.SF NS Text'; font-size:13pt; font-weight:400; font-style:normal;">
   <p align="center" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:'.verdana'; font-size:18pt; color:#fdfefe;">REPUTACIÓN</span></p></body></html> 
   ```
   Esto dificulta el poder modificar el tamaño de la fuente, ya que hay que hacerlo directamente en el texto enriquecido. 😕

   Para evitar problemas con eso, lo mejor es usar texto plano y después agregar características al _label_ por medio del _"Change StyleSheet"_ o el _"property editor"_. 

   Por ejemplo, así quedaría uno de los _labels_ al usar texto plano y seteando en la _style sheet_ como `color: white; text-transform: uppercase;`:
   ![image](https://user-images.githubusercontent.com/26393515/86971196-bcecf380-c13e-11ea-87b7-ebbf370c92b8.png)


Espero que te sea de ayuda :)
Saludos y éxito en el fin de semestre 👋📚

PS: Si quieres mandar a recorregir sobre esto y pedir que se revise la interfaz en un MacOS, es perfectamente válido. 🤓

**Comment by dcastillo5** [comment]
Gracias por la explicación !!
