### ISSUE TITLE
Tengo complicaciones conectando el cliente a la interfaz

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#1335]
No comprendo bien como hay que conectar el hilo de cliente a la ventana. Tengo dos ventanas, la de sala de espera y la de la ronda. La sala de espera tiene un boton que va directo a la ventana de ronda. No entiendo como pasarle el texto (tengo el valor- ese no es el problema) al cliente para enviarlo y verificarlo en el servidor. Pensaba en implementar algo como [esto](https://www.geeksforgeeks.org/python-communicating-between-threads-set-1/) pero no se si funcionara, y no lo se implementar, ya que tengo dos ventanas, en distintos archivos, que deben compartir los valores. Como resuelvo esto?

**Comment by sofiuni** [comment]
Mi hora de entrega es a las 8 de la tarde, por si me pueden ayudar ahora

**Comment by fdoflorenzano** [comment]
Hola @sofiuni,

¿Has intentado usar señales para lo que buscas? Suena a un buen caso de uso. Puedes comunicar el *back-end* del cliente con su *front-end* para activar la ejecución de algo y además pasar un valor.

Saludos.

**Comment by sofiuni** [comment]
No logro entender como usar señales desde distintos archivos, la ultima vez cree una clase que tiene todas las señales pero me dijieron que eso es mala practica

**Comment by fdoflorenzano** [comment]
Hola @sofiuni,

¿Qué es lo que no entiendes? Pregunto para saber como ayudarte mejor. Aún cuentas con los ejemplos de los contenidos, ayudantías y actividades (como la [AF04)](https://github.com/IIC2233/syllabus/blob/master/Actividades/AF04/main.py) con ejemplo de lo que dices.

Saludos.
