### ISSUE TITLE
filtro por cupos

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#1336]
Hola me surgio una duda. Si el curso tiene secciones con cupos y otras secciones sin cupos. A la hora de mostrar los cursos, consideramos las solo las secciones del curso donde hayan cupos segun el parametro "cupos"?

**Comment by igbasly** [comment]
Hola @Juampisaez :v:

Tal como se menciona en el enunciado y en la issue #1326, este filtro solo debe retornar los diccionarios de los cursos considerando aquellas secciones con igual o mayor numero de vacantes que el dado en el argumento `cupos`.

Saludos y mucho éxito en la actividad :raised_hands:.
