### ISSUE TITLE
Tope de horario en argumento de filtrar_por_cursos_compatibles

### ISSUE THREAD

**Issue by Antonio-Fernandez-R** [IIC2233/syllabus#1337]
Hola! para la función de filtrar los cursos compatibles con el horario entregado ¿No puedo asumir que el horario entregado no tenga topes de horario? Lo pregunto por que para el ejemplo que se da para probar la función existen topes de horario entre los cursos y no se dice nada al respecto en el enunciado.

**Comment by fdoflorenzano** [comment]
Hola @Antonio-Fernandez-R,

No deberías necesitar asumir eso, ya que lo que busca el filtro es que secciones en `dicc_de_cursos` no tienen topes con cursos en `horario`. Si hay topes de horario entre secciones en `horario`, eso no afecta si hay/tiene tope con una sección específica en `dicc_de_cursos`.

Saludos.

**Comment by Antonio-Fernandez-R** [comment]
Ya! gracias!

**Comment by Juampisaez** [comment]
No me queda claro algo, si un nrc de la lista tiene tope de horario con algun curso del diccionario, entonces ese curso no lo incluyo en el diccionario que se retorna con los cursos posibles (eso contempla también los cursos de la propia lista de nrc), es decir, el diccionario solo contiene los cursos que no tienen tope con los cursos de la lista?

**Comment by fdoflorenzano** [comment]
Hola @Juampisaez,

No entendí qué no te quedó claro, pero lo que dices es correcto. Ojo solamente con que este filtro funciona a nivel de secciones, no de cursos, ya que son las secciones las con módulos horario, no los cursos completos.

Saludos.

**Comment by Juampisaez** [comment]
perfecto, era solo para saber si lo que pense estaba bien.
Gracias!!
