### ISSUE TITLE
Duda con función traducir módulo con varios horarios el mismo día

### ISSUE THREAD

**Issue by rldelafuente** [IIC2233/syllabus#1338]
Hola!

Me queda la duda con el siguiente ejemplo:
`"AYU#J:4;CLAS#J:5,6;LAB;PRA;TAL;TER;TES"`

En este ejemplo, ¿cual sería el formato de la llave "CLAS"? ¿`"CLAS": [("J", 5, 6)]`?

Gracias de antemano!

**Comment by igbasly** [comment]
Hola @rldelafuente :v:

Para estos casos, puedes visualizar esta etapa de conversión como tener que obtener los **módulos individuales**, es decir, en el formato de tupla `("str_dia", int_modulo)`. Por lo tanto, se puede interpretar que para todos los días del horario indicado (`"J"` en este caso) se tendrá clases en cada módulo descrito, lo cual obteniendo sus conversiones individuales resulta en:
```python
"CLAS": [("J", 5), ("J", 6)]
```

Saludos y mucho éxito 🙌 .

**Comment by CarlosOlivos** [comment]
Existe un caso donde hayan distintos días con distintos modulos, por ejemplo "CLAS#J:5,6{separador}V:4{separador}S:1" y si existe, cual seria el separador?

**Comment by igbasly** [comment]
@CarlosOlivos puedes asumir que esto no ocurrirá, pero en la issue #1320 se explica más al respecto :+1:.
