### ISSUE TITLE
Sobre orden de módulos al cargar

### ISSUE THREAD

**Issue by gonzaloconcha** [IIC2233/syllabus#1339]
¿Importa el orden en que se entreguen los módulos desde la función traducir_modulos o se pueden entregar en cualquiera?

**Comment by fdoflorenzano** [comment]
Hola @gonzaloconcha,

Buena pregunta, la respuesta es no, no importa. Uno de los arreglos que realizamos recientemente con los archivos de pruebas arregla justo eso, al revisarse automáticamente, el orden no es relevante y verifica por contenido.

Saludos.
