### ISSUE TITLE
Duda eventos

### ISSUE THREAD

**Issue by CmPoblete** [IIC2233/Syllabus#134]
En el punto 8 de la tarea dice que hay eventos que pueden ocurrir cada vez que se visitan planetas pero lo que no queda claro es si los eventos tambien pueden ocurrir al visitar planetas no conquistados.
Yo asumo que cuando se visita un planeta no conquistado el archimago no puede atacar pero que pasa con el asteriode?

**Comment by santilaguna** [comment]
Según entendi (no soy ayudante) cada vez que realizas la acción visitar planeta, independiente de si el planeta está conquistado o no, existe la probabilidad de un evento que afecta al azar uno de tu planetas conquistados (no necesariamente debe ser el planeta visitado).

**Comment by Hernan4444** [comment]
Hola, @santilaguna está en lo correcto, puedes revisar esta issue #95 para confirmar.
