### ISSUE TITLE
Como eliminar archivos de mi repositorio 

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2233/Syllabus#134]
Me di cuenta que subi a mi repositorio archivos no relevantes para la tarea. Existe una manera para eliminarlos?

**Comment by Hernan4444** [comment]
@Rudyjb24 Tienes que eliminar esos archivos de la carpeta y luego hacer git add "archivo" y luego el commit correspondiente
Si quieres eliminar algo llamado prueba.py, primero asegurate de que tu carpeta este actualizada con git pull, luego elimina ptueba.py, despues haces git add prueba.py, y de ahí se hace como cualquier commit y push

Saludos!
