### ISSUE TITLE
Parametros

### ISSUE THREAD

**Issue by fcartoni** [IIC2233/syllabus#134]
Hola! Tengo una duda de la implementación del archivo parámetros. La tarea dice que tiene que ser a prueba de todo tipo de errores. Esto se refiere que si el ayudante pone por ejemplo un número negativo o letras en un parámetro que yo estoy esperando enteros positivos, le tengo que decir que modifique el archivo parámetros o yo elijo números aleatorios? 
Gracias!

**Comment by jeschuwirth** [comment]
Hola,

El programa tiene que ser a prueba de errores para los inputs, puedes asumir que los parámetros entregados nunca van a ser incorrectos :)

Si no me equivoco las ruedas no son un parámetro, por lo que las puedes 'Hardcodear' a tu código, para evitarte problemas te recomiendo citar esta issue en el readme.

Suerte en la tarea!
