### ISSUE TITLE
Cargar partida a prueba de cambios (tramposos) en el archivo

### ISSUE THREAD

**Issue by quememo** [IIC2233/syllabus#134]
### Cuando se carga un archivo guardado:

1. Se tiene que verificar que los datos que se carguen sean correctos con ciertos valores que rigen el juego, haciéndolo **a prueba de tramposos** que quieran obtener ventaja editando el archivo **civilizaciones.csv** u otros?

2. O simplemente se asumirá que los archivos guardados mediante el programa, como también los iniciales de partida nueva (data) serán solo de lectura y con valores "correctos", evitando acceso malintencionado por parte de usuarios y valores que no soporte el programa? 

### Ejemplo:
El archivo **constantes.py** indica **MAX_POBLACION_DCC = 120**, sin embargo un usuario edita el archivo de su partida guardada e indica en **civilizaciones.csv** que tiene 300 soldados (antes digamos tenía 30), por lo que cuando se cargue su partida superaría el limite de población y ocasionaría problemas con el juego. Si ocurriera este caso, debería detectarlo al cargar la partida y notificar que no es posible cargarla o esto no ocurrirá?

**Comment by Arcoirisky** [comment]
Hola~ 
Los archivos si pueden modificarse pero no te preocupes por cosas como tener más población de lo que la máxima te permite. Puedes asumir que el tramposo será inteligente y no dejará pruebas de su astucia xD
