### ISSUE TITLE
Menu de inicio y crear predios

### ISSUE THREAD

**Issue by vvialbarros** [IIC2233/Syllabus#134]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Para la sección del menú de inicio, si el usuario presiona 1 se debe llamar a la funcion crear_predios definida en dccultivo.py, ya que la funcion crear_predios tiene como argumento el nombre de un archivo, le debo pedir el nombre del archivo al usuario y que lo escriba él o simplemente asumo que siempre se utilizará el archivo "predios.txt" que se encuentra dentro de la carpeta "data" para crear los predios. En el caso que el usuario deba escribir el nombre del archivo, el único archivo que podria usar sería predios.txt porque es el único archivo dentro de la carpeta data? O los ayudantes para corregir el menú tendrán otros archivos dentro de la carpeta data además de predios.txt?

**Comment by FernandoTFH** [comment]
Se habló de esto en la issue #51, dice todo lo que preguntaste.

**Comment by vvialbarros** [comment]
Perdon, no la habia visto muchas gracias!
