### ISSUE TITLE
Añadir Excavador al equipo

### ISSUE THREAD

**Issue by GuilleStanke** [IIC2233/Syllabus#134]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas, en los tesoros de calidad 1, se agrega un excavador al equipo, y el tesoro indica de qué tipo es este nuevo excavador... este nuevo excavador tiene que ser elegido aleatoriamente entre los excavadores del tipo indicado en excavadores.csv??

**Comment by TwoB-2B** [comment]
Una consulta, dado que lo importante es respetar el tipo del excavador, eso significa que puedo añadir un excavador que ya estaba en el equipo antes?

**Comment by mtaguero** [comment]
¡Hola @TwoB-2B!

Para no limitar el flujo del programa te recomiendo que sea posible volver añadir a un mismo jugador a tu equipo. Sin embargo, esto queda a tu criterio, dado que no se especifica en enunciado.

Sea cual sea tu decisión, no olvides mencionarlo en tus supuestos.

¡Éxito! 🎈
