### ISSUE TITLE
Error al interactuar con archivos dentro del archivo.py en Vs code 

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2233/syllabus#134]
hola tengo un problema que me surgió al hacer la tarea 0
tengo un archivo.py que interactua con otras archivos.csv en la misma carpeta,
el código me funciona al usar el IDLE de python, pero no funciona cuando lo corro con el VS code
el código de error en el Vs cose dice que no existen esos archivos.csv
nota: estos archivos.csv fueron copiados en mi carpeta de alumno, pero todavía no hago el git add ., git commit -m, git push, Pero dudo que eso influya

**Comment by matiasmasjuan** [comment]
Hola @vice-rosas99!

¿Qué error te muestra exactamente?

¿Estas trabajando con la carpeta abierta dentro de **VSCode**? (Para hacer esto, haz click en **file**, **open folder** y seleccionas la carpeta en la que estás trabajando)

**Comment by vice-rosas99** [comment]
me sale : FileNotFoundError: [Errno 2] No such file or directory: 'usuarios.csv'

**Comment by vice-rosas99** [comment]
no ,estoy trabajando solo con el archivo.py en vs code, intente teniendo el otro abierto también en el vs code pero no funciona

**Comment by vice-rosas99** [comment]
hice lo que dijiste de open folder, y sale que la carpeta está vacía (°o°)

**Comment by vice-rosas99** [comment]
ya ahí caché lo de folder, ahora sí funciona, así debe hacerse para todas las veces que yo interactue con archivos verdad?
Gracias Por Resolver

**Comment by matiasmasjuan** [comment]
Así lo he hecho yo siempre desde que trabajo con **VSCode**.

Éxito con la tarea!
