### ISSUE TITLE
Duda sobre guardar datos al fin o cierre del juego.

### ISSUE THREAD

**Issue by Dchungw** [IIC2233/Syllabus#134]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo dudas respecto a si debemos guardar cambios que se hagan durante una simulación de campeonato.  Se entrego una base de datos con entrenadores y programones ya asignados, la idea es para cada vez que se corra el programa se carguen los mismos datos iniciales o estos vayan cambiando según se simulen mas campeonatos, lo mismo con objetos.  Del enunciado se podría deducir esto pero no es explícito; se hace énfasis en que las características que describe son requerimientos mínimos entonces no me queda claro.

[**¿Debemos guardar información sobre entrenadores entre corridas diferentes del programa? **]

**Comment by Amandasandov** [comment]
Hola, no es necesario guardar la información de simulaciones anteriores una vez que sales del programa. Asume que cada vez que inicies el programa partes con la misma información disponible inicial en los archivos entregados.

**Comment by Dchungw** [comment]
Para salidas del programa ok me queda claro.  Ahora dentro de una misma corrida del programa se espera que esta pueda simular varios campeonatos? Y en este caso se tendrían que conservar cambios?  i.e: si en un primero campeonato logre subir mi programon a algún nivel para cierto entrenador, si simulo nuevamente un campeonato este entrenador tendrá subido a su programon.

**Comment by Amandasandov** [comment]
Cada vez que vuelvas al menú de inicio y selecciones a un entrenador, el campeonato se reinicia con la información inicial en los archivos, independientemente de que no hayas salido del programa.

**Comment by Dchungw** [comment]
Perfecto, me queda claro. Muchas gracias!
