### ISSUE TITLE
¿Se le puede transferir dinero a un underaged via banco?

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#134]
Hola queria saber si se le podia transferir dinero a un underaged, ya que el enunciado no dice nada acerca de eso. Gracias.

**Comment by Arcoirisky** [comment]
Hola!
Si no lo dice el enunciado entonces puedes hacerlo si quieres pero, recuerda decirlo en el Readme O:!! De todas formas el underaged no podría usar ese dinero o:
