### ISSUE TITLE
Encuesta Carga Académica

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#134]
cuando abro el link del mail que nos enviaron para responder la encuesta académica la página dice que la encuesta se encuentra cerrada.

**Comment by Tsbalart** [comment]
Hola @enriquemolinare!
Esto se debía a un problema directo de la ECA, pero ya te debiese haber llegado un mail con el link nuevamente.
Si no logras contestarla, escríbenos nuevamente.
Saludos!
