### ISSUE TITLE
Modularizacion cuando son menos de 400 líneas

### ISSUE THREAD

**Issue by nicolascamhi** [IIC2233/syllabus#134]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola! Si terminé la tarea y la hice en menos de 400 lineas es necesario separarla en distintos archivos igualmente?? Actualmente mi tarea tiene incluso menos de 300 lineas.

**Comment by matiasmasjuan** [comment]
Hola @nicolascamhi !

No es obligatorio modularizar siempre y cuando tengas menos de 400 líneas de código. Por lo tanto, no hay ningún problema si dejas tu tarea tal cual como está. Ahora bien, es **recomendable** modularizar ya que permite estructurar el programa de forma **ordenada**, lo cual lo vuelve mucho mas fácil de leer para alguien que no esté familiarizado con tu código. Quizás para esta tarea no es tan fácil de modularizar debido a su corta extensión. Sin embargo, para programas más complejos si va a ser necesario modularizar de forma correcta el código.

Algunas formas para poder modularizar el código es pensar en las distintas funcionalidades que tienes que hacer. Por ejemplo, separar todas las funciones encargadas de leer y guardar archivos en un determinado módulo, hacer otro que se encargue del flujo entre los menús, otro para procesar datos, etc. Para mayor detalle puedes revisar los [Contenidos](https://github.com/IIC2233/contenidos/blob/main/semana-00/2-modularizaci%C3%B3n.ipynb) del curso.

Saludos! :smile:
