### ISSUE TITLE
¿Hay que revisar inputs de funciones a completar?

### ISSUE THREAD

**Issue by meduenas** [IIC2233/syllabus#1340]
Hola hola! 😄 

Se puede asumir que los inputs de las funciones a completar serán siempre en el formato adecuado? O hay que revisarlos de alguna manera?

Edit: en particular, en el caso de cargar_cursos, el input 'semestre' que se le entregue, será en formato "_año-semestre_" y que el archivo 'semestre'.json efectivamente estará en la carpeta datos

**Comment by fdoflorenzano** [comment]
Hola @meduenas,

Sí, pueden asumir correctitud de argumentos, no es necesario que revisen. Eso incluye el caso que mencionas, y que los archivos estarán en una carpeta llamada `datos`, al mismo nivel de la ejecución del programa.

Saludos.
