### ISSUE TITLE
Formato de argumento curso en filtrar_por_prerrequisitos

### ISSUE THREAD

**Issue by rldelafuente** [IIC2233/syllabus#1341]
Hola!

Tengo una duda con el formato de los inputs de esta función. 
`def filtrar_por_prerrequisitos(curso, dicc_de_cursos):`

`curso` es un diccionario del estilo (donde los keys son "Nombre", "Retiro", etc):
`{'Nombre': 'Programación Avanzada', 'Retiro': 'SI', 'Aprobacion Especial': 'NO', 'Creditos': 10, 'Ingles': 'NO', 'Sigla': 'IIC2233', 'Prerrequisitos': ['IIC1103', 'IIC1102'], 'Secciones': {'1': {'Campus': 'San Joaquín', ...`

O es un diccionario como filtrado de dicc_de_cursos, (donde el key es "IIC2233"), como del estilo:
`'IIC2233': {'Nombre': 'Programación Avanzada', 'Retiro': 'SI', 'Aprobacion Especial': 'NO', 'Creditos': 10, 'Ingles': 'NO', 'Sigla': 'IIC2233', 'Prerrequisitos': ['IIC1103', 'IIC1102'], 'Secciones': {'1': {'Campus': 'San Joaquín', ...`

Gracias de antemano!

**Comment by fdoflorenzano** [comment]
Hola @rldelafuente,

El primero, representa un único curso.

Saludos.
