### ISSUE TITLE
Sobre más tests

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#1342]
Hola, queria saber si existen mas tests de los que muestra el archivo test.py. Solamente para asegurar la actividad

**Comment by aaossa** [comment]
Hola @Juampisaez , perdón por la demora en la respuesta 😅 La verdad es que no tenemos considerado entregar más _tests_, pero puedes crear tus propios ejemplos modificando lo que se encuentre bajo la línea de `if __name__ == "__main__":`. Éxito con la evaluación recuperativa ✨

**Comment by M-Altamirano** [comment]
Hola! Hice mas tests modificando las lineas bajo `if __name__ == "__main__":`, y fallaron todos los tests, pero los revise y los resultados de las funciones eran los mismos que el output esperado (eso sí, en lugar de poner a mano en cada lugar el output esperado hice archivos .json para almacenarlos y editarlos más cómodo). A lo que voy, es que los resultados estaban correctos, pero según los tests no lo estaban (revise a mano, entre medio me di cuenta en un error en una función y aún tras arreglarlo sigue tirando incorrecto a pesar de ser lo mismo que el output esperado)

Por eso pregunto: usarán la exactamente la misma estructura de `test.py` para corregir?

**Comment by aaossa** [comment]
Hola @M-Altamirano , probablemente el *output* con el que comparabas no era **exactamente** el mismo. Es posible que el problema se deba a que utilizaste JSON para almacenar los *outputs* esperados. En JSON no existe noción de "tuplas" y "listas", sino que de "arreglos", que se ven exactamente igual que las listas a la hora de serializar (Python convierte tuplas y listas a arreglos, por lo que se pierde la diferencia). Seguramente, si miras el JSON cargado, los módulos de horarios no están almacenados como listas de tuplas, sino que como listas de listas (en verdad, arreglos de arreglos), lo que explicaría la diferencia a la hora de comparar. Finalmente, respondiendo a tu pregunta, usaremos la misma estructura que les entregamos, pero para serializar los datos no utilizaremos `json`, sino que probablemente `pickle`.

Esto también se explica en el archivo `test.py`:

https://github.com/IIC2233/syllabus/blob/2b69831188bcf23e642b2b02f3a7fcda9bd2ec9f/Recuperativa/test.py#L133-L135

Confirmame si lo que produce la diferencia es el utilizar JSON por favor 🙌 Podrías confirmarlo colocando el *output* directamente en tu archivo `test.py` y verificando si el resultado del *test* es correcto.
