### ISSUE TITLE
¿Por qué "resultado_cargado.json" no tiene tuplas?

### ISSUE THREAD

**Issue by faaceituno** [IIC2233/syllabus#1343]
Hola, al momento de implementar cargar_cursos.py cambio la llave de modulos de acuerdo a lo señalado en el enunciado y me queda en el formato: [ (a , b), (c, d) ] con una lista cuyos elementos son tuplas con el dia y el modulo. 
Pero resulta que cuando cargo el archivo de prueba resultado_cargado.json, el diccionario que cargo trae el formato de los modulos como lista de listas y no lista de tuplas y nose porque se cambia si el diccionario que entrego tiene el formato pedido

**Comment by fdoflorenzano** [comment]
Hola @faaceituno,

Es simplemente por JSON, este formato no cuenta con el tipo de dato tupla, solo listas. Luego, al serializar una tupla, lo convierte en la alternativa directa: una lista. Para verificar si es de tipo tupla, mejor imprime el objeto directamente en vez de verlo en su versión serializada.

Saludos.

**Comment by faaceituno** [comment]
Ya muchas gracias, y si al imprimir el diccionario me sale en formato tupla, en ese caso el test estaría correcto?

**Comment by fdoflorenzano** [comment]
Hola @faaceituno,

Es un poco difícil decir si el test completo estará correcto solo por ese detalle. Si te refieres que cumple con que los módulos son tuplas, sí, es correcto. El resto puedes probarlo haciendo tus propias pruebas con `test.py`.

Saludos.
