### ISSUE TITLE
Duda sobre modulos

### ISSUE THREAD

**Issue by aipostigo** [IIC2233/syllabus#1344]
Hola! En los modulos pueden haber por ejemplo una clase con 2 modulos distintos en 2 dias distintos? o siempre seran del tipo L,W : 4 o L: 4,5? y si es que es lo primero cual es el formato?

**Comment by igbasly** [comment]
Hola @aipostigo :v:

Esta situación se trata en la issue #1320, ahí puedes ver los casos que son considerados y los que no.
Saludos y éxito :raised_hands:.
