### ISSUE TITLE
Return esperado función filtrar_por_cupos

### ISSUE THREAD

**Issue by meduenas** [IIC2233/syllabus#1346]
Hola hola! :smile:

El enunciado dice que el filtro por cupos dice que debe retornar _todos los cursos con secciones con igual o mas vacantes disponibles_

Mi pregunta es si este return debe incluir solamente las secciones con vacantes o si debe retornar el diccionario del curso tal cual a como se encuentra en el diccionario de input

Por ejemplo, un curso con 3 secciones pero solamente 2 con cupos disponibles (digamos 1 y 3). El return esperado sería el curso sin modificar o el curso solo con las secciones 1 y 3, no retornando la información de la sección 2

**Comment by igbasly** [comment]
Hola @meduenas :v:

Tal como se menciona en el enunciado y en la issue #1326, este filtro solo debe retornar los diccionarios de los cursos considerando aquellas secciones con igual o mayor numero de vacantes que el dado en el argumento cupos. Es decir, debe incluir toda la información del curo, pero solo las secciones con cupos.

Saludos y  mucho éxito :muscle:
