### ISSUE TITLE
¿Filtrar por cursos compatibles debe usar reglas de universidad?

### ISSUE THREAD

**Issue by EduardoIllanes** [IIC2233/syllabus#1347]
Hola tengo una duda al filtrar por cursos compatibles. Al referirse que no exista tope de horario se refiere a que no existe ningún tope entre los módulos? O al caso que no topen los `CLAS` o los`LABS` pero si puedan topar por ejemplos las `AYU` (como es en la realidad cuando uno toma cursos)
Gracias!

**Comment by fdoflorenzano** [comment]
Hola @EduardoIllanes,

Buena pregunta, se refiere a tope cualquiera de módulos, independiente del tipo de módulo (donde tipo es si es clase, ayudantía, etc...). Es que no tengan horario temporal igual, como que dos cursos ocupen el `('J', 4)` para algo. No es necesario repliquen las reglas de ayudantía-clase y otros de la universidad.

Espero se entienda,
Saludos.

**Comment by EduardoIllanes** [comment]
Si se entiende! Gracias!
