### ISSUE TITLE
Manejo de tildes en 'filtrar_por'

### ISSUE THREAD

**Issue by meduenas** [IIC2233/syllabus#1349]
Hola otra vez! 😅 

Cómo debiese manejar este filtro los caracteres con tilde? 

Por ejemplo, si le entrego el string _dominguez_, sin tilde (y la llave _'nombre'_), debiese retornar el/los cursos a cargo del profesor **Domínguez** (con tilde) o ignorarlos? Ya que los caracteres con y sin tildes se consideran distintos entre si

**Comment by fdoflorenzano** [comment]
Hola @meduenas,

No se pide que manejen las tildes en enunciado. Si el nombre de algo lleva tilde, debería buscarse con tilde. En tu ejemplo, si se busca un profesor con el *string* `"dominguez"`, entonces no aparecen los Domínguez (con tilde) en el filtro. Lo único que deben manejar, como explícito, es ser insensible a mayúsculas y minúsculas.

Saludos.
