### ISSUE TITLE
Git Push rejected por posibles cambios que no están en el repositorio local.

### ISSUE THREAD

**Issue by JSalas277** [IIC2233/Syllabus#135]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

Ayuda no puedo hacer git push en mi repositorio, cuando lo intento me sale esto:

 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/IIC2233/JSalas277-iic2233-2024-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by JSalas277** [comment]
Hice git status -> git add -> git commit -> git push y no me funciona

**Comment by ChupeteBecker** [comment]
Hola, trata de hacer git pull primero, porque dice qué hay cambios que tu no tienes, entonces antes de hacer push puede ser necesario un git pull.

Saludos.

**Comment by JSalas277** [comment]
Gracias, lo pude resolver
