### ISSUE TITLE
Se resta el dinero automáticamente al hacer bid/ask?

### ISSUE THREAD

**Issue by behrmann97** [IIC2233/Syllabus#135]
Mi pregunta es si es posible hacer un ask o un bid con el mismo dinero dos veces. Me explico:
por ejemplo user1 tiene 50 BAN, y decide hacer un bid en el mercado BANRIN y otro en el BANRUP, ambos vendiendo sus 50 BAN por X de las otras cantidades, esperando que alguno de los dos genere un match. 
¿Es posible esto, o al hacer el ask simplemente se le resta automáticamente el dinero a su cuenta?

**Comment by nebil** [comment]
Es posible que lo discutido en #67 responda a tu duda. :recycle:

**Comment by behrmann97** [comment]
oh perdon, busque y no había encontrado un issue relacionado. Gracias!
