### ISSUE TITLE
Duda sobre volver al menú de inicio 

### ISSUE THREAD

**Issue by gabo1243** [IIC2233/Syllabus#135]
### Duda

Hola, con respecto a volver al menu de inicio tengo entendido que se le da la opción al jugador de escoger nuevamente el entrenador. Al hacer esto ¿Se reinicia por completo el torneo, junto las distintas estadísticas de los programones y objetos de los entrenadores tal como aparecen en los archivos csv?
Gracias de antemano.

**Comment by Amandasandov** [comment]
Hola, aunque no está explicitado en el enunciado, pueden asumir que cada vez que se selecciona un entrenador en el menú de inicio el torneo se reinicia desde cero. De cualquier manera, mencionalo en tu README para evitar confusiones.
