### ISSUE TITLE
Mi juego, con sus archivos en que cree las clases, donde deben ir?

### ISSUE THREAD

**Issue by perezpefaur** [IIC2233/syllabus#135]
No se, si los pongo en la carpeta T01, o las carpetas adentro como data/.

**Comment by Arcoirisky** [comment]
Hola! La carpeta data es solo para los archivos .csv :D Si quieres crear carpetas extras para los módulos, estas en tu libre derecho siempre y cuando todas estén en la carpeta T01 ya que será esta la que se recogerá al final O:!
