### ISSUE TITLE
Problemas al definir área de riego

### ISSUE THREAD

**Issue by EmanunamE** [IIC2233/Syllabus#135]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Yo creo que para determinar si el centro de una celda se encuentra dentro del área, se tiene que usar el teorema de Pitágoras. Y siguiendo con esa lógica, **el ejemplo que se dio en la sección 2.2 del PDF no está mala?** la celda (1, 2) no debiese estar marcada ya que: (2, 4) - (1, 2) = (1, 2), por lo que (1, 2) se encuentra a una distancia $\sqrt{5} > 2$ del centro.

![Imagen de WhatsApp 2024-08-23 a las 17 45 09_d718dd4a](https://github.com/user-attachments/assets/d8c779d3-0b83-4598-9f0b-2739aaf3a2dd)

Esta es la única forma que se me ocurre :(
También pensé que quizás se refería a "área" como literalmente, el área del circulo, pero eso es mucho peor pjsskdjs.
**Realmente no entendí muy bien cuál es el criterio para determinar si una celda se encuentra adentro o afuera del circulo.**

**Comment by Johan-10** [comment]
Lee bien el enunciado recuerda que tomamos "el circulo" como un cuadrado al que se le eliminan las esquinas.

**Comment by EmanunamE** [comment]
> Lee bien el enunciado recuerda que tomamos "el circulo" como un cuadrado al que se le eliminan las esquinas.

a XD
