### ISSUE TITLE
Código un poquito largo en T00

### ISSUE THREAD

**Issue by daniela-carreno** [IIC2233/syllabus#135]
Hola! Estoy viendo que mi código capaz que exceda las 400 líneas permitidas, y se me ocurrió dejar en un archivo fuera del main.py todas las funciones que voy a utilizar. Esto es legal?? y si se permitiera, puedo subirlo aparte en mi repositorio? Gracias!

**Comment by yuwet15** [comment]
Hola, segun yo, la idea es hacer varios modulos apartes, y no dejar todo en un archivo(main.py) o eso creo

**Comment by MatiasDuhalde** [comment]
Hola @daniela-carreno !

Para esta entrega (y las siguientes), pedimos que sus módulos no sean excesivamente largos, por lo que está el límite máximo de 400 líneas por archivo. Tal como dice @yuwet15 , si tu código está más largo y no cabe todo en un solo archivo, la solución a esto sería aplicar modularización. Por lo que sí, sería legal agregar un archivo aparte con funciones, pero si lo haces así, después deberías importarlas desde el módulo principal (`main.py`), para que tu programa pueda ocupar correctamente el código de tus archivos "extra".

El concepto de modularización y las ideas detrás de esto se explican mejor en [este notebook](https://github.com/IIC2233/contenidos/blob/master/semana-00/2-modularizaci%C3%B3n.ipynb) de la semana 0 ;)
