### ISSUE TITLE
Error al leer el tablero en el metodo solucionar

### ISSUE THREAD

**Issue by lucasmv8** [IIC2233/Syllabus#135]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el metodo solucionar utilizo un codigo para obtener la cantidad de celdas que deben ser explotadas por la bomba. Este codigo lo he utilizado a lo largo de toda la clase Tablero y me ha funcionado bien en todas las ocasiones, pero al utilizarlo en el metodo solucionar me dice que la lista que le entrego esta vacia.
![Captura de pantalla (121)](https://github.com/IIC2233/Syllabus/assets/141937138/410b1f8f-0145-4446-b95d-0ba3c64cc748)

**El codigo al que hago referencia es este: rango = int(''.join(filter(str.isdigit, self.tablero[i][j]))). Donde tanto i como j provienen de un for in range**

**Comment by roahoki** [comment]
hola @lucasmv8! lamento lo tarde de la respuesta. Respecto a tu consulta, es dificil saber por qué ocurre que cierto método recibe una lista vacía cuando en realidad esta debería tener información. Sin embargo, te recomiendo que ocupes técinas de debuggeo como el uso de los prints a lo largo de la ejecución como también el uso de _breakpoint_ . Cualquier otra consulta, quedo atento

**Comment by Hernan4444** [comment]
Hola,

Complementando un poco lo anterior, lo que puede estar pasando es que en `self.tablero[i][j]` no haya una pieza explosiva, sino un peón o celda vacía ("--") y cuando haces `filter(str.digit, self.tablero[i][j])`, eso retornará finalmente un string vacío.  Luego, si intentas hacer `int("")` eso justo levantará el error que muestras.

Por otro lado, ojo que en issue de librerías prohibidas
https://github.com/IIC2233/Syllabus/issues/55

Se dice que no está permitido el uso de generadores. Y`filter` es un generador. Eso mismo se puede hacer con uso de for/while, funciones, string y listas.

Saludos!

**Comment by lucasmv8** [comment]
Muchas gracias por la ayuda, logre solucionar el problema.
Y gracias por lo del uso de filter, no me había dado cuenta de que estaba dentro de cosas prohibidas.
