### ISSUE TITLE
Varias dudas con el desarrollo de la T0

### ISSUE THREAD

**Issue by Icarus328** [IIC2233/syllabus#135]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo varias dudas con respecto a la T0.

Primero, hay que entregar los archivos .csv provistos tal y como nos los entregaron o los podemos modificar haciendo pruebas con el programa? (Creando grupos y usuarios que no estaban ahí, etc.)

Segundo, en el archivo usuarios.csv el primer nombre es usuario, trato esto como el "titulo" de la columna o como que hay un usuario registrado con el nombre "usuario"?

Tercero, a la hora de enviar nuevos mensajes es necesario también registrar la fecha y hora a la que fueron enviados.

Cuarto, si es posible importar el modulo os, ya que no recuerdo que diga nada de ese modulo en el enunciado.

Quinto, me gustaría saber si el codigo se revisara si o si desde la carpeta T0 o puedo especificar esas cosas en el readme, para poder así establecer mejor los paths relativos.

Sexto, si tengo que entregar todo únicamente en la carpeta T0 o si puedo crear subcarpetas adentro y así poder ordenarme mejor (colocando los modulos en una y los archivos en otra, por ejemplo)

Gracias.

**Comment by matiasmasjuan** [comment]
Hola @Icarus328 !

Dado que casi todas tus preguntas tienen relación a temas distintos, te pido que para la próxima vez intentes hacer ***issues*** distintas de modo tal que si algún otro compañero o compañera tenga la misma duda, les sea más fácil de buscar. De la misma manera también puedes buscar si este tipo de preguntas ya fueron contestadas en ***Issues*** anteriores.

A continuación responderé a tus preguntas en orden:

1. Te aconsejo ver la ***issue*** #54  ya que ahí se habla sobre el archivo ```.gitignore``` y la forma en que nosotros utilizaremos los archivos para la corrección de la tarea. En caso de no hacer uso del ```.gitignore```, entonces da igual si se entregan los archivos con modificaciones o no.

2. La idea es que todos los archivos ```*.csv``` entregados tienen un **encabezado**, por lo que se da a entender que para el caso de ```usuarios.csv``` ese *usuario* es el **título** o **encabezado** del archivo, no de un usuario registrado. Ahora bien, dado que en el enunciado no aparece de forma explícita, es válido considerar que el encabezado "usuario" corresponde a un usuario registrado, siempre y cuando se señale en el **README.md**.

3. **Sí**, es necesario registrar la fecha y hora. Te aconsejo ver la **issue** #67 . 

4. Para ese tipo de dudas, está la **issue** #44 . *Spoiler*: sí, se puede.

5.  **Todo lo necesario** para evaluar la **T0** debe estar contenido dentro de esta carpeta. Ahora bien, dentro de ella puedes añadir más carpetas y situar los paths como tú desees, siempre y cuando se señale en el README.md (más información en la **issue** #55 

6. Al igual que en la respuesta a la pregunta 5, revisa la **issue** #55 .

Saludos! Mucho éxito con la tarea! :smile:
