### ISSUE TITLE
Cuándo ocurren efectos en un ExcavadorTareo

### ISSUE THREAD

**Issue by TriniAguilera** [IIC2233/Syllabus#135]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! No me quedó muy claro cuándo ocurre el aumento de edad y pérdida de felicidad en ExcavadorTareo. Entiendo que la energía y la suerte aumentan cuando se consume un ítem consumible, pero no queda muy claro el hecho que provoca lo de edad y felicidad. Esto último ocurre por el simple hecho de que el excavador sea Tareo o hay algun evento? por ejemplo, consumir un item, cavar metros, u otro

**Comment by mtaguero** [comment]
¡Hola!

Todos los efectos para un excavador tareo ocurren luego de consumir un ítem del tipo consumible.

Si te queda cualquier duda, háznosla saber.

¡Éxito! 🎈
