### ISSUE TITLE
T01: Actualización de Enunciado

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233/Syllabus#135]
Hola,
 Se acaba de subir una versión nueva del enunciado. El **único cambio** es:

El diagrama de clases se entrega en **su repositorio**, no por el _google form_.

Saludos y éxito en la tarea ✌️

**Comment by Felipehanckes** [comment]
Que pasa con el escudo? no se da ninguna informacion de eso pero sigue siendo una opcion que debemos poder construir

**Comment by Hernan4444** [comment]
Tal como se dice en #23, el escudo se eliminó. No editamos esa parte del enunciado porque ya se había explicado en la issue.
