### ISSUE TITLE
eliminar archivo de github

### ISSUE THREAD

**Issue by simoneaston** [IIC2233/syllabus#135]
le cambié el nombre a mi módulo principal de la tarea y en ves de cambiarse también en github, ahora en github hay dos archivos, uno con el nombre nuevo y otro con el antiguo. ¿Cómo borro el antiguo? Gracias

**Comment by jeschuwirth** [comment]
Hola, @simoneaston !

Para hacer eso puede seguir los siguientes pasos:

1. Primero que nada es asegurarte de resguardar lo que llevas actualmente en otra carpeta.
2. Volver a hacer git pull de tu repositorio
3. Eliminar las carpetas o archivos que no quieres que estén
4. Hacer git rm "nombre archivo o carpeta"; el comando rm se ocupa del mismo modo que usarías git add para agregar un archivo
5. Commitear y pushear

Con eso debería estar todo arreglado

Si tienes problemas o no te funciona sigue comentando en esta issue :)

Suerte!

**Comment by simoneaston** [comment]
Funcionó, muchas gracias
