### ISSUE TITLE
Decodificación de carta no compatible

### ISSUE THREAD

**Issue by bcalfaro** [IIC2233/syllabus#1350]
Hola! Sigo con la T03 (me dieron extensión de plazo).
Estaba revisando mi codificación y decodificación de cartas y me di cuenta de que cuando busca crear un archivo desde la carpeta servidor a la carpeta clientes, la crea fuera de ambas carpetas y como archivo no compatible. ¿Alguna idea de qué pueda pasar?
Adjunto imágenes, gracias!

![image](https://user-images.githubusercontent.com/62023620/87119784-f57af300-c24c-11ea-8702-034cfbae7699.png)

![image](https://user-images.githubusercontent.com/62023620/87119802-0297e200-c24d-11ea-97ea-254c6d4198b1.png)

**Comment by bcalfaro** [comment]
Subí una versión de mi código a mi repositorio, el código del issue está en carpeta servidor, modulo prueba_code.py, por si necesitan verlo

**Comment by fdoflorenzano** [comment]
Hola @bcalfaro,

Revisé el archivo `prueba_code.py` que indicas, y encontré lo siguiente:

- La ubicación del archivo que creas se debe a la ruta especificada al escribir el archivo y al directorio de ejecución del programa. Como ese programa específico usa de ruta para acceder a la imagen original: `'servidor/sprites...'`, interpreto que el directorio de ejecución es `T03`, pero al momento de guardar el nuevo archivo, la ruta utilizada es  `carta.bmp`, lo cual indica que se guarde en el directorio actual (`T03`). 

- Sobre lo de archivo no compatible, hay varios temas. Primero, lo guardas con extensión BMP cuando los archivos originales son PNG, y segundo, lo que guardas es la codificación completa especificada en el enunciado, lo cual no es un formato válido de guardado de imágenes, y **nunca se indica que lo sea**, es la manera en que el servidor debe enviarle al cliente las cartas a través de *sockets*. Tu computador no lo reconoce porque no es algo que deba reconocer. 

Espero se entienda, si necesitas aclaraciones quedamos atentos,
Saludos.

**Comment by bcalfaro** [comment]
Muchas gracias!
