### ISSUE TITLE
Print no aparece en pantalla

### ISSUE THREAD

**Issue by dcastillo5** [IIC2233/syllabus#1351]
Hola!! Estoy haciendo aún la T03
Todo me estaba funcionando perfecto pero llegó un punto en donde intenté enviar una mensaje desde el servidor hacia el cliente siguiendo la misma logica, el cliente lograba recibir bien sin embargo parece no reconocer el mensaje así que agregue unos `print` para ver que pasaba y por alguna razón se saltan.
![Captura de pantalla 2020-07-10 a las 5 02 13 p m](https://user-images.githubusercontent.com/61330735/87203746-416f7b80-c2d1-11ea-9e05-3ddc6e99472e.png)
En la consola de la derecha se puede ver que  simplemente los ignora, igual se ejecuta bien hasta un punto en donde recibe un mensaje, hace el `print("mensaje recibido de servidor....") ` y hace un tipo de `continue` del `while True:` porque el resto de codigo que esta debajo no se ejecuta. 
![Captura de pantalla 2020-07-10 a las 5 00 34 p m](https://user-images.githubusercontent.com/61330735/87203757-48968980-c2d1-11ea-98da-d68f4326bffb.png)

Si alguien me puede explicar por que ocurre esto seria de gran ayuda.
Gracias!

**Comment by igbasly** [comment]
Hola @dcastillo5 :v:

No estoy seguro de haber entendido por completo tu problema, pero según lo que mencionas, en la consola de la derecha donde no se imprimen algunos mensajes, puede ocurrir que no se esté ejecutando los archivo correctos. Esto ya que es casi imposible que se imprima `"Mensaje recibido del servidor: {mensaje}"` sin haber impreso antes `"Primer print"`, lo que me indica que es posible que no esté ahí en el código ejecutado.

Ahora, no entiendo que se muestra en la consola izquierda, ya que parece tener sentido con lo definido antes en la imagen del código. De todas formas, te pido que subas tus cambios a tu repositorio y me des algo más de detalle en cuanto al contexto de lo que estás haciendo con tal de poder ver con más detención que pueda estar ocurriendo.

Quedo atento atento :smile:.

**Comment by dcastillo5** [comment]
Se arreglo magicamente :flushed:  no cambie nadaa y ya esta todo bien. 

Igual por si vuelve a ocurrir... Las consolas que te muestro son dos clientes que se están ejecutando al tiempo desde el mismo archivo, no tengo copias de los archivos ni versiones antiguas guardadas en el computador así que no pude haber ejecutado dos distintos. En esa parte ambos reciben la misma señal y debería mostrarse todo igual.

**Comment by igbasly** [comment]
¡Que bien :+1:!, me alegro que se haya arreglado. Puede ocurrir que hayas ejecutado una antes que la otra y luego agregaste los print sin reiniciar el cliente.
De todas formas, si sigues teniendo el mismo problemas escríbelo en esta issue 🙌 .
