### ISSUE TITLE
Llamar traducir_modulos en cargar_cursos

### ISSUE THREAD

**Issue by nlewin99** [IIC2233/syllabus#1353]
Tengo una duda respecto si luego de definir a función traducir módulos esta debe usarse en cargar cursos o lo correcto es dejarlas separadas.
Gracias

**Comment by fdoflorenzano** [comment]
Hola @nlewin99,

Como dice el enunciado, la transformación de módulos al cargarlos debe realizarse llamando a la función. Técnicamente si la transformas dentro de `cargar_cursos` usando la misma implementación que uses en `traducir_modulos` pero sin llamarla funcionará igual. Pero claro que puedes llamarla desde otra función, para eso está.

Saludos.
