### ISSUE TITLE
Error al ejecutar función en test #0

### ISSUE THREAD

**Issue by vobrador** [IIC2233/syllabus#1354]
Holaa, me aparece ese error ('NoneType' object has no attribute 'split') en el test de traducir modulo. Quería saber si es el error que mencionan que saldrá en el enunciado o si es un error mío. De ser así, alguna idea de porqué podría darse? He revisado harto mi código y no encuentro una parte donde pueda ocasionarse.
 
Gracias :)

**Comment by Alonsinho1** [comment]
Hola! efectivamente estas en lo correcto. El test 0 existe para probar que el programa no cae si encuentra errores, por ende no debes preocuparte. El error en especifico que arroje tampoco es relevante, ya que este dependera de como implementaste las funciones!

Animo animo animo!!!

**Comment by MariaBarias** [comment]
Preguntaa! 
No entiendo bien si debieramos estar preparados para un None type o por si alguien no pone nada, osea, string == "", o simplemente dejamos que salga el "Error"

espero que esten bien  :)

**Comment by Alonsinho1** [comment]
Hola, @MariaBarias !

Mi explicacion va a ser un poco densa para lo simple que es. Pero basicamente la respuesta es que si deberias estar preparada para este caso, sin embargo en la mayoria de los casos se termina haciendo casi que "automaticamente".

Una de las formas mas simple para ver si un string esta contenido dentro de otro string es utilizando la funcion _in_. Aqui viene la parte interesante, resulta que el string "" es justamente el string vacio, pero mas que contener nada lo puede ver como el pilar fundamental de un string, es decir todos los strings tienen incluyen el string "". (Lo puedes comprobar por ti misma!). Lo que estoy tratando de decir es que en la gran mayoria de los casos el insertar un string vacio no generara error debido a la naturaleza de este string en particular.

Quizas fue mucho mas engorroso de lo que debio ser, pero considero que es muy util saber esto. Perdon por si me fui por las ramas

**Comment by MariaBarias** [comment]
jajaja muuuuchas gracias!
