### ISSUE TITLE
Resultados test 

### ISSUE THREAD

**Issue by CarlosOlivos** [IIC2233/syllabus#1355]
Si obtengo lo siguiente al correr test.py:
Casos probados: 11
Correctos: 10
Incorrectos: 0
Errores: 1
Tests para función: filtrar_por.

Respuestas en test #0 coinciden

Casos probados: 1
Correctos: 1
Incorrectos: 0
Errores: 0

Puedo asumir que la actividad esta completa y esta todo bien ?

**Comment by igbasly** [comment]
Hola @CarlosOlivos :v:

El archivo `test.py` es solo una referencia de como se corregirá tu código después, por lo tanto, solo contiene un ejemplo para la función `traducir_modulos` y el filtro `filtrar_por`, lo que no implica que necesariamente todo programa esté correcto. Tal como se menciona en el enunciado, la idea de este archivo y la clase `Test` es que puédenla experimentar con ella y crear sus propias pruebas de como funcionaría el código.

De todas formas te invito a que tomes un par de cursos de los archivos originales y crees o evalúela tus propios *tests* con tal de ir verificando como funciona tu programa. Quedo atento a cualquier duda y mucho éxito :muscle:.

**Comment by sebaew98** [comment]
Hola @igbasly , yo no entiendo por que me tira 3 errores o hace 11 pruebas si solo hay 7 casos a probar, adjunto pantallazo
<img width="873" alt="Screen Shot 2020-07-11 at 19 42 37" src="https://user-images.githubusercontent.com/62079275/87235843-f035b980-c3ae-11ea-980b-cfc2279d5cf0.png">

**Comment by igbasly** [comment]
Hola @sebaew98 :v:

Puede ser algo confuso de leer al principio, lo que pasa es que no son solo 7 *tests*, si los cuentas verás que son 11, ya que hay *test* `"2b"`, `"6b"` y se comienza desde el 0 sin contar el primero que es un error. Por lo tanto, tienes 11 *tests* para `traducir_modulo` y 1 para `filtrar_por`.

Ahora, los 3 errores que te aparecen son precisamente por lo que se indica, en los 3 últimos casos no se coincide con el *output* esperado, estos son los *tests* "6", "6b" y "7". Puedes comprobarlo tu mismo viendo los 3 últimos elementos de cada lista (`argumentos` y `output_esperado`).

Espero que esto lo aclare, éxito y saludos 🙌 .

**Comment by sebaew98** [comment]
Sisi, ya los encontre, mi duda es que, segun este commit https://github.com/IIC2233/syllabus/issues/1320, no deberian haber cursos en el formato donde el horario tiene en mas de un dia varios modulos. como esta en el test.py
[(None,), ('CLAS;TES;LAB;TER;PRA;AYU;TAL',), ('AYU;CLAS#V:3;TES;TAL;LAB;PRA;TER',), ('PRA#J,V:2;TER;TES;AYU;CLAS;TAL;LAB',), ('TES;AYU;CLAS;PRA;LAB#M,J:7;TAL;TER#L,M:2',), ('LAB;PRA;TER;TAL;TES#L,W,V:1;AYU;CLAS',), ('TAL;AYU#L:5,6;CLAS;TES;PRA;LAB;TER',), ('TES;LAB;TAL;TER;PRA;AYU;CLAS#V:5,6,7',), ('AYU#**W,J:7,8**;PRA;CLAS;LAB;TER;TES;TAL',), ('TES#**M,J:3,4**;LAB;TER;AYU;PRA;CLAS#M,J:1,2;TAL',), ('PRA;TES;TAL#**M,W,J:3,4,5**;AYU;LAB;TER#M,W,J:3,4,5;CLAS',)]

Que son justamente desde el test 8 al 11 !
Muchas gracias

**Comment by sebaew98** [comment]
espera parece que no lo habia leido y me guiaba por lo que que un amigo me habia dicho eso pero leyo mal. Entonces si se puede tener ese formato?

**Comment by igbasly** [comment]
@sebaew98 si puede tener ese formarto, cuidado al confundir **distintos días con distintos módulos** y **distintos días con los mismos módulos**, ya que lo que se menciona en la issue #1320 es que **no habrá distintos días con distintos modulos**, por ejemplo `"V:4", "W:3"`. Pero **sí puede ocurrir que varios días tengan los mismo módulos**, como por ejemplo `"L:1,2", "M:1,2"` lo cual sería `"L,M:1,2"` que es lo planteado en los *tests*.

Espero que esto lo aclare, quedo atento :v:.

**Comment by sebaew98** [comment]
gracias! era un malentendido mio.

**Comment by igbasly** [comment]
No hay problema :simple:, mucho éxito en la actividad.
