### ISSUE TITLE
Duda con filtrar_por_cursos_compatibles: cursos incluidos en horario

### ISSUE THREAD

**Issue by M-Altamirano** [IIC2233/syllabus#1357]
Los cursos pueden incluir a los que contienen alguno de los nrc dados por el usuario, o deben ser excluidos?
Saludos 😄

**Comment by igbasly** [comment]
Hola @M-Altamirano :v:

Si lo ves de ese modo, ocurre que si uno de los cursos ya está incluido en el horario dado, significaría que este cursos tendría tope de horario en exactamente los mismo módulos(porque ya está dentro). Por lo tanto, bajo lo que el enunciado pide, no calificaría como un curso compatible.

Saludos y éxito 💪 .

**Comment by M-Altamirano** [comment]
El tema es que en el enunciado se especifica que cuando haya cursos donde algunas secciones pidan con lo requerido y otras no, entonces debería retornar el curso en el diccionario, pero solo con las secciones que cumplan con lo requerido.

Lo preguntaba porque podría ser que el usuario quiera buscar solo cursos que aun no haya agregado al horario, o bien incluir secciones de cursos que ya haya tomado pero tenga otras alternativas de horario.

**Comment by igbasly** [comment]
Si @M-Altamirano, disculpa mi confusión también 😅, cuando hablaba de **cursos** me refería a **secciones** en específico, ya que hay que recordar que los NRC son propios de las sección, por lo tanto, el fundamento sigue siendo el mismo. Si una sección ya contiene su NRC en el horario dado, entonces no puede ser retornada dentro de un cursos por lo expresado antes, no así otra sección del mismo cursos como tu dices, ya que efectivamente podría no compartir horario.

**Comment by M-Altamirano** [comment]
Entiendo eso, mi duda es si debo incluir o no los cursos que contengan alguna de las secciones pedidas. Por ejemplo, si solo pongo un nrc de 'calculo' en lista_nrc, debo incluir las secciones de calculo compatibles con ese nrc? O elimino 'calculo' completo nomas?

**Comment by igbasly** [comment]
@M-Altamirano este filtro funciona a nivel sección, por lo tanto, no debes incluir la sección específica a ese NRC, el resto deberás verificar si no posee tope de horario. Entonces solo en el caso en que para un cursos ninguna sección califique, no deberás incluirlo.

**Comment by M-Altamirano** [comment]
Ok, gracias!
