### ISSUE TITLE
Librería `functools`

### ISSUE THREAD

**Issue by NikiHV** [IIC2233/syllabus#1358]
Hola!
¿Está permitido usar el método `reduce` de `functools`?

**Comment by Alonsinho1** [comment]
Hola ! me podrias especificar para que quieres ocupar ese metodo?

**Comment by NikiHV** [comment]
Perdón, no sabía si especificarlo. Es para unir las listas de una lista en una sola.

**Comment by NikiHV** [comment]
Espero me puedas responder pronto :c

**Comment by Alonsinho1** [comment]
hola! no hay problema en que ocupes esa libreria! no respondi ayer por que como equipo docente no respondemos issues los domingos. Mucha suerte!
