### ISSUE TITLE
Trabajar con modulos traducidos

### ISSUE THREAD

**Issue by IvaniaArias** [IIC2233/syllabus#1359]
Holaa!
Me surgió la duda si en las funciones "filtrar_por" debemos trabajar (y retornar) un diccionario con los módulos traducidos o dejando los strings de la forma AYU;CLAS#L,W:2;LAB#J:5,6;PRA;TAL;TER;TES.

Graciaas!

**Comment by igbasly** [comment]
Hola @IvaniaArias :v:
La idea de la función `traducir_modulos` es que se utilice dentro del cargado de cursos, por lo tanto, todo el resto del programa funcionaría con los cursos en el formato indicado, es decir, con los prerrequisitos como lista y los módulos como un diccionario.
