### ISSUE TITLE
Es el Dccowork necesario instanciarlo?

### ISSUE THREAD

**Issue by JupaOlivares** [IIC2233/syllabus#136]
Hola!
Viendo que el dccowork no tiene relacion con el ataque y la defensa por lo que podria no instanciarse como edificio? obviamente las funciones que realiza se cubririan de otra forma...

**Comment by Arcoirisky** [comment]
Recuerda que estamos evaluando la modelación del enunciado O: 
Solo eso te puedo decir ouo)/
