### ISSUE TITLE
Parametros

### ISSUE THREAD

**Issue by cristozille** [IIC2233/syllabus#136]
Hola, no me quedó muy claro de dónde hay que obtener los valores de los parámetros para modificarlos en parametros.py, como por ejemplo los valores de las mejoras. 
Gracias!

**Comment by jmwielandt** [comment]
Hola!

No los debes sacar de ningún lado, tú debes decidir cuánto valen. Puedes ir ajustándolos a medida que testeas tu programa, así además te aseguras de que no haya errores o mejoras la interfaz para que sea más fácil testear las cosas y entregas una mejor tarea.

Saludos!

**Comment by jmwielandt** [comment]
Agregando a lo anterior, hay algunos que sí están en el enunciado como la contextura de los pilotos según su equipo.

Saludos~
