### ISSUE TITLE
git no me permite subir el README

### ISSUE THREAD

**Issue by simoneaston** [IIC2233/syllabus#136]
le puse: git add README.md y todo ok
luego pongo: git commit -m "mensaje" y me aparece lo siguiente:
```
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ../../README.md
        deleted:    tarea00oficial.py
```

**Comment by jeschuwirth** [comment]
Hola @simoneaston,

Tienes un problema de merge en tu github, la solución correcta puede ser complicada para este ramo. 

Para solucionarlo te recomiendo:

1. Guardar todo lo que llevas de la tarea
1. Borrar la carpeta donde tienes tu repo
2. Hacer git pull de tu repo
3. Colocar todos los avances de la tarea + readme en tu nuevo repo
4. Hacer add, commit, push

Si sigue tirando error comenta en esta issue :)

Éxito!

**Comment by simoneaston** [comment]
ya osea que borro la carpeta T00? y después hago otra igual con git pull?

**Comment by simoneaston** [comment]
No funcionó :(

**Comment by jeschuwirth** [comment]
Intentemos un reset completo.

Vuelve a clonar tu repo en una nueva carpeta, luego copia del repo actual todos los archivos de la T00 a tu nuevo repo.

Luego de eso puedes hacer el git add/commit/push de los cambios y debería funcionar.

Me avisas!

**Comment by aaossa** [comment]
Para complementar la recomendación de @jeschuwirth , es posible que tu problema se deba a que hiciste `git add README.md`, pero más abajo se ve que la ruta para llegar al README es `../../README.md`, por lo que el comando que debías ingresar es `git add ../../README.md`. Recuerda utilizar `git status` para ver la ruta a los archivos que quieres actualizar 🚀

**Comment by simoneaston** [comment]
finalmente hice el reset completo y funcionó
muchas gracias a ambos
