### ISSUE TITLE
Duda sobre archivo descriptivo del avance

### ISSUE THREAD

**Issue by gabo1243** [IIC2233/Syllabus#136]
### Duda

Hola, con respecto al avance se dice que debe haber un archivo .md que explique las clases del diagrama. Sobre este, ¿Debe ser un archivo distinto al ```README.md``` o las descripciones deben ir dentro del mismo ```README.md```?
Gracias de antemano

**Comment by Amandasandov** [comment]
Hola, el archivo de explicación del diagrama de clases debe ser distinto al README.md. Suerte.
