### ISSUE TITLE
Edades de Excavadores y edad máxima de ExcavadorTareo

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2233/Syllabus#136]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado se nos dice que los excavadores tienen edad **¿Que ocurre si el torneo se alarga por 365 dias? ¿Se le debe sumar 1 año a cada excavador?**

Adicionalmente en el caso del ExcavadorTareo este luego de cavar debe  aumentar su edad en EDAD_ADICIONAL_TAREO , pero  as u vez se nos indica que  los excavadores no pueden tener más de 60 años. En el caso en que al sumar dicha edad al excavador esta resulte ser mayor a 60 **¿Que ocurre con su edad?¿No aumenta más su edad y queda en 60 ? ¿O debe ser eliminado el excavador?**

**Comment by mtaguero** [comment]
¡Hola!

Como ninguna de estas dos cosas se especifica en el enunciado, siempre puedes escribir tus supuestos en el README y frente a esto hacer lo que estimes conveniente. Sin embargo, por simplicidad, te recomiendo no agregar funcionalidades extra si estas no son exigidas en el enunciado, sobretodo si son difíciles de implementar (comentario general).

**Ojo** 👀 que las características de un excavador tareo cambian al consumir un ítem del tipo consumible y no al terminar de cavar.

Si te quedó cualquier duda, no dudes en volver a preguntar.

¡Éxito! 🎈

**Comment by TriniAguilera** [comment]
Hola! si al aumentar la edad de un excavador y esta sobrepasa los 60 años, entonces debo quitar a esa persona del equipo de excavadores? Digamos que se jubila de su trabajo jajajaja

**Comment by mtaguero** [comment]
> Hola! si al aumentar la edad de un excavador y esta sobrepasa los 60 años, entonces debo quitar a esa persona del equipo de excavadores? Digamos que se jubila de su trabajo jajajaja

¡Hola @TriniAguilera!

No necesariamente.
Como se mencionó anteriormente, un excavador no puede sobrepasar los 60 años. Sin embargo, esto no significa que necesariamente deba salir del equipo. Pero es una opción válida si así lo desean, mientras lo específiquen en su README.

Otra opción totalmente válida es el caso en que si un excavador tiene 60 años y cumple más años, entonces su edad se mantiene (como se indicó en una de las preguntas).

Esto queda totalmente a criterio de ustedes. Lo importante es que cumplan lo dicho por el enunciado y que hagan todos los supuestos necesarios en su README. 

Espero que haya quedado más claro :)
