### ISSUE TITLE
Hay que eliminar los cultivos en todos los predios o solo en uno al ejecutar detectar_plagas()

### ISSUE THREAD

**Issue by Johan-10** [IIC2233/Syllabus#136]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Por lo que entendí del enunciado al ejecutar el método detectar_plagas en DCCultivo este:

Primero recibimos una lista de listas con un predio y coordenadas.
Segundo si hay un cultivo en esa posición hay que eliminar todo el cultivo de ese predio.

Acá es donde no entiendo si adicionalmente debo también buscar ese mismo cultivo en el resto de los predios y eliminarlo.

Y finalmente retornar una lista de listas con el nombre del predio y la cantidad de cultivos eliminados ya sea del predio individual o ir agregando a cada predio un valor de cultivos eliminados.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Agusrush21** [comment]
La lista de lista que te pasan, marca el predio en donde esta la plaga y las coordenadas
Al momento de eliminarlo solo hay que hacerlo en el predio especificado. Y tambien que puede ser mar de una vez que te indiquen eliminar una plaga en ese mismo predio

Ademas la lista de listas que debes retornar esta formada por cada predio y cantidad de plagas eliminadas **totales**

**Comment by vgalfaro** [comment]
Hola! creo que quedó claro con la respuesta de tu compañero, sólo debes eliminar los cultivos de tipo N (en el caso que haya en esas coordenadas) del predio en cuestión, los demás son independientes, saludos!

**Comment by Johan-10** [comment]
Si si quedo claro gracias.
