### ISSUE TITLE
Duda si es que se añade mal un contacto o se crea mal un grupo

### ISSUE THREAD

**Issue by matiasparodic** [IIC2233/syllabus#136]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola! Tengo una duda sobre lo que dice el enunciado si es que no se cumplen los requisitos para agregar un contacto o para crear un grupo. 
El enunciado dice que si no se cumplen las condiciones para cualquiera de estas dos, se debe notificar al usuario y volver al menú actual. Eso significa que debo volver a darle la opción de añadir un contacto o crear un grupo hasta que sea válido? (según sea el caso). O debo volver al Menú de Contactos y Grupos respectivamente?

**Comment by IgnaciaJ** [comment]
Hola @matiasparodic! Cuando en el enunciado se refiere al menú actual significa que se debe volver al último menú en donde se escogió la última acción y notificar mediante un print que no se pudo concretar la acción. En este caso ese menú corresponde al de contactos o de grupo. Éxito en tu tarea!
