### ISSUE TITLE
Problemas al abrir archivo.txt

### ISSUE THREAD

**Issue by enriquerussi** [IIC2233/syllabus#136]
necesito ayuda para abrir mi archivo.txt en visual studio code

**Comment by vsantelicest** [comment]
Hola! Dime como te ayudo

**Comment by Tsbalart** [comment]
Hola @enriquerussi ! Intenta no abrir nuevamente Issues con la misma pregunta, ya que esto entorpece la respuestas de estas mismas. La dejare conectada con la que ya habías hecho #131 
Si tu problema continua, no dudes en volver a escribir!
Exito en la tarea!
