### ISSUE TITLE
Fe de erratas

### ISSUE THREAD

**Issue by chuma9615** [IIC2233/Syllabus#136]
Holaa, Donde puedo dejar un fe de erratas que me equivoque en tipear una linea y no alcance a resubir la tarea, con esta linea mala mi programa no funciona! Ayuda porfa!

**Comment by Hernan4444** [comment]
@chuma9615 para esto disponen del Readme c:
Saludos!!

**Comment by chuma9615** [comment]
La pregunta es, se penaliza mucho un error de ese tipo o es secundario a todo el trasfondo de la tarea?

**Comment by rpalmaotero** [comment]
Hola! El foro está pensado para dudas sobre la materia, tareas y Python en general. Dudas de carácter administrativo debes verlas directamente con el coordinador.
