### ISSUE TITLE
Sobre función filtrar_por_cupos: curso sin secciones con cupos

### ISSUE THREAD

**Issue by rkarac** [IIC2233/syllabus#1360]
Hola, quería saber si el diccionario que se retorna en la funcion de filtrar por cupos debe tener el curso aún cuando ninguna de sus secciones tiene el cupo? Ej: Programacion avanzada....... "Secciones": {}, o no se incluye el curso?

**Comment by igbasly** [comment]
Hola @rkarac :v:

En ese caso se asume como que el curso completo no tiene cupos, por lo tanto, no es necesario retornarlo.
Saludos.

**Comment by rkarac** [comment]
muchas gracias !!
