### ISSUE TITLE
Argumento semestre de cargar_cursos.py

### ISSUE THREAD

**Issue by Scrodriguez1** [IIC2233/syllabus#1361]
Hola!

Quería saber qué tengo que poner en la variable semestre de cargar_cursos.py para probar el funcionamiento del código.
Estaba usando 

with open('./datos/2020-1.json as file:
    semestre = json.load(file)

y funciona pero no sé si es correcto esto.
Gracias de antemano.

**Comment by fdoflorenzano** [comment]
Hola @Scrodriguez1,

La idea es que a partir del argumento `semestre` cargues el archivo correspondiente. Su valor será `"2019-1"`, `"2019-2"` o `"2020-1"`. Si cargas siempre el mismo archivo no estarías cumpliendo lo pedido en enunciado.

Espero se entienda,
Saludos.
