### ISSUE TITLE
Error al buscar por prerrequisito en interfaz gráfica

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#1362]
Hola, usando la interfaz gráfica cuando busco por prerrequisitos de un curso me da el siguiente error en el archivo 'DDCusro.py'

line 42, in aplicar_filtro
    curso_de = self.cursos[valor.upper()]
KeyError: 'string_ingresado'

La unica fomar en que no me tire ese error es sies que, por ejemplo, busque 'iic2233' las siglas de progra avanzada, y recien ahi me da arroja las secciones de intro a la progra, que son los pre requisitos. Pero si en vez de poner 'iic2233', pongo 'programación avanzada' o  'iic' nomas, me da ese error. Mi duda es si es que DCCursos, se hizo de tal forma que solo se pueda buscar por la sigla del curso completa, o si es que tengo un error en la carga de datos.

**Comment by fdoflorenzano** [comment]
Hola @felipefuentesporras,

Tienes razón, efectivamente aparece un error en lo que señalas. La interfaz gráfica fue diseñada para recibir la sigla completa del curso solamente, y además no maneja bien el caso en que se ingrese un *input* no válido. Pero es un error de la interfaz gráfica, no del cargado ni es un caso que debas manejar o preocuparte.

Gracias por hacerlo notar.

Saludos.

**Comment by felipefuentesporras** [comment]
yaa buena, gracias!!
