### ISSUE TITLE
Tildes en cargar_cursos.py

### ISSUE THREAD

**Issue by miguel-mrtnez** [IIC2233/syllabus#1363]
Hola! La función ```cargar_cursos()``` me estaba arrojando un diccionario sin tildes al ejecutar ```cargar_cursos.py```, hasta que  incluí el argumento "ensure_ascii=False" a la función ```json.dump``` que escribe el archivo ```resultado_cargado.json```. ¿Estaré haciendo un mal manejo del diccionario y no era necesario agregar ese argumento? o en los tests con los que se va a corregir después la tarea se incluye este argumento a ```json.dump``` para asegurar que aparezcan los tildes.

Gracias desde ya!

**Comment by fdoflorenzano** [comment]
Hola @miguel-mrtnez,

No estoy completamente seguro que puede ser. ¿Al leer los datos específicas que se use `encoding='utf-8'`? ¿Cómo sabes lee sin tildes? ¿Al imprimir los valores no te salen los tildes? Porque por lo que dices, suena a que los tildes desaparecen/aparecen cuando guardas, lo que quiere decir que probablemente estén inicialmente en el diccionario que cargas en `cargar_cursos`. 

Quedamos atentos,
Saludos.

**Comment by miguel-mrtnez** [comment]
Los tildes de los archivos ```.json``` de la carpeta ```datos``` vienen en este formato:
![bug_0](https://user-images.githubusercontent.com/58334917/87319399-92f94f80-c4f7-11ea-93c1-0c6e56eba356.PNG)

El dump del diccionario obtenido como resultado de ejecutar ```cargar_cursos``` viene así por defecto, con utf-8 indicado:
![bug_2](https://user-images.githubusercontent.com/58334917/87319593-d489fa80-c4f7-11ea-83de-6fc2fffb37ab.PNG)

Cuando ejecuto lo anterior, los tildes en el archivo ```resultado_cargado.json``` se ven así:
![bug_1](https://user-images.githubusercontent.com/58334917/87319666-eb305180-c4f7-11ea-878f-d5db3f2ba675.PNG)

Ahora, con la modificación mencionada a ```json.dump```:
![bug_4](https://user-images.githubusercontent.com/58334917/87319719-013e1200-c4f8-11ea-8927-a9d6aa5dca0a.PNG)

Los tildes pasan al formato deseado:
![bug_5](https://user-images.githubusercontent.com/58334917/87319745-0c913d80-c4f8-11ea-844e-0d6f3200e9dc.PNG)

**Comment by fdoflorenzano** [comment]
Hola @miguel-mrtnez,

Entonces parece estás leyendo correctamente, no te preocupes. Los caracteres del estilo `'\u00ed'` son formas de codificar caracteres "raros" como los tildes, y como muestran tus fotos, si los estás leyendo como tales. Que no aparezcan tal cual en `resultado_cargado.json` no significa que no estén.

Saludos.

**Comment by miguel-mrtnez** [comment]
Muchas gracias profe! Saludos.
