### ISSUE TITLE
problema con git push

### ISSUE THREAD

**Issue by vobrador** [IIC2233/syllabus#1364]
<img width="571" alt="Captura de Pantalla 2020-07-13 a la(s) 11 31 47" src="https://user-images.githubusercontent.com/62116151/87323193-714e9700-c4fc-11ea-9af5-f45445b3c795.png">

Holaa, no he logrado subir la Recuperativa por este problema, no lo entiendo, podrían ayudarme porfavor

**Comment by igbasly** [comment]
Hola @vobrador :v:

El problema que se ve ahí es porque hay cambios en GitHub que no han sido descargaos en tu computador, esto se puede deber a que editaste algún archivo directamente en internet o los subiste desde otro dispositivo.
Debería poder arreglarse haciendo `git pull` antes de hacer `git push` nuevamente.

Quedo atento frente a otras complicaciones, saludos.

**Comment by vobrador** [comment]
Probaré con eso! Gracias. De todas maneras no edite desde internet ni subí archivos de otro dispositivo :( asique no se porqué se habrá dado. Te avisoo!!

**Comment by vobrador** [comment]
Holaa!! Me funcionó lo que me dijiste, muchas gracias :))  Eso si, se subió una actualización a la Tarea03 que hice post entrega, esta no debería ser considerada para la evaluación, ¿será un problema, o se revisa el push que quedó hecho antes de las 8pm el día de la entrega (sábado pasado) ?

**Comment by igbasly** [comment]
Me alegro!! 😄 Las actividades y tareas se recolectan a la hora indicada, cualquier cambio posterior no es considerado, así que no hay problema :+1:.

**Comment by vobrador** [comment]
Buenisimo! graciasss
