### ISSUE TITLE
Funcionalidad filtrar_por_modulos 

### ISSUE THREAD

**Issue by Christian-Klempau** [IIC2233/syllabus#1365]
Hola! Me surgió una duda respecto al filtro **filtrar_por_modulos** de la actividad Recuperativa. Los cursos que retorna deben tener **todos** los cursos de `modulos_deseados`  o mínimo uno?
Por ejemplo:
 `modulos_deseados = [("J", 1),  ("M", 1)]`
En ese caso devolveré los cursos que tengan **Jueves **y** Martes** 1, o en el caso que un curso tenga **sólamente Jueves** 1, sin tener Martes 1, también debe ser devuelto?

**Comment by Alonsinho1** [comment]
Hola, espero que te encuentres bien! 

Es la segunda opcion. Con tal de que el curso tenga una de esas opciones, debera ser retornado. Piensa que estas buscando cursos que cumplan alguno de los criterios mas que todos los criterios.

**Comment by Christian-Klempau** [comment]
Perfecto, me quedó claro. Muchas gracias!
