### ISSUE TITLE
Error al convertir diccionario a JSON: TypeError: Object of type type is not JSON serializable

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#1367]
`    with open("resultado_cargado.json", "wt", encoding="utf-8") as archivo:
        json.dump(cursos, archivo, indent=4)
`

esta parte de el codigo entregado me da error, no se por que si se le entrega un diccionario. Que debo hacer?

**Comment by fdoflorenzano** [comment]
Hola @sofiuni,

¿Sigues con este error? Me llama la atención el mensaje, ya que dice *Object of type **type***, lo cual me da la intuición se le estaba entregando un tipo de objeto, como `dict` en vez de una instancia de ese tipo. ¿Podría haber sido eso?

Saludos.
