### ISSUE TITLE
Seguridad y trazabilidad

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#137]
en especifico, que hay que poner de cada uno de los siguientes 
_Usuario_ consulta saldo
_Usuario_ consulta sus orders
_Usuario_ consulta los _orders vigentes_ o _hist ́oricas_ de un _mercado_ 
_Usuario_ consulta realiza un _order_ en un _mercado_
Sistema realiza un match entre dos _orders_

por ejemplo, que hay que poner de usuario; su username simplemente? o de las orders también; su id solamente, o su tipo, su precio, etc.. creo que se entiende a lo que me refiero en general. Gracias! 😬

**Comment by iqacevedo** [comment]
Hola,

Deberías guardar la información necesaria para que puedas identificar cada una de las acciones. Cuando decidas que guardar pregúntate ¿Con está información puedo mostrar la acción que se realizó?, de esa manera vas a saber si estás bien o no.

Saludos !

**Comment by rihanuch** [comment]
@iqacevedo entonces queda a criterio mío que considero relevante?

**Comment by iqacevedo** [comment]
Si debes usar tu criterio, pero debes considerar que si guardas menos de la información necesaria para identificar lo que sea que estás guardando no estará bien. Entonces, usa bien tu criterio, si se tiene todo bien modelado no deberían haber problemas para notar que es lo que se debe guardar.

Saludos ! 

Saludos !

**Comment by rihanuch** [comment]
@iqacevedo , entonces se deben crear archivos para los registros de la seguridad?

**Comment by iqacevedo** [comment]
Nuevamente eso es decisión tuya, existen distintas maneras en que se puede guardar la información y luego acceder a ella, aunque como dices en algún lugar tiene que quedar guardado.
