### ISSUE TITLE
Equipos

### ISSUE THREAD

**Issue by mvaldes12** [IIC2233/syllabus#137]
Hola
En los parámetros esta el diccionario de diccionarios Equipo, pero en el enunciado no sale cuando se usan. ¿Se tienen que usar para poner las características aleatorias de los pilotos?

**Comment by jmwielandt** [comment]
Hola!

El ser capaces de crear y usar adecuadamente los parámetros es algo que se busca evaluar en esta tarea, por lo que no te podemos responder cuándo deben ser usados.

En el archivo `parametros.py` se les proporciona un marco de trabajo o esquema en el que basarse, son libres de usarlo o definir sus parámetros de otra forma en función de qué les acomode más.

Lo que sí te puedo decir es que los parámetros que salen en el enunciado se corresponden a los que están en el archivo. Por ejemplo `EQUIPOS['TAREOS']['CONTEXTURA']['MIN']` sería el valor mínimo que toma la contextura de los tareos.

Saludos!
