### ISSUE TITLE
Pérdida de energía de ExcavadorHíbrido

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2233/Syllabus#137]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado se dice que el ExcavadorHibrido se comporta igual que el ExcavadorDocencio y ExcavadorTareo, pero con la diferencia que su gasto de energia se reduce a la mitad.

**¿El gasto energetico reducido a la mitad, tambien implica que la ENERGIA_PERDIDA_DOCENCIO se reduce a la mitad? ¿O cuenta solo para el gastar energia original? **

**Comment by SantiagoDLCB** [comment]
Entonces para aclarar entiendo que para todo otro tipo de gastos energéticos es la mitad pero dado la condición que el hibrido es un Docencio, la ventaja energética implica que el hibrido ¿No se le debe restar la ENERGIA_PERDIDA_DOCENCIO o que se le debe restar pero solo la mitad de ese valor?

**Comment by mtaguero** [comment]
Tal como dices, un híbrido es a la vez un docencio. Esto implica que cuando un híbrido termina de cavar, todos los efectos de un excavador docencio también lo afectan. Es decir, un híbrido también pierde energía adicional `ENERGIA_PERDIDA_DOCENCIO` .

Considerando que un híbrido siempre gasta la mitad de la energía que un docencio o un tareo, entonces por lógica debe ocurrir tu opción número 2.

Espero que esta vez te haga más sentido 🍃

**Comment by c4ebt** [comment]
Me surgió una duda sobre el mismo tema, y me pareció una mejor idea responder a la issue para que esté toda la información en un mismo lugar.

El punto 4.3.1 del enunciado, en la sección del ExcavadorHíbrido, dice "su energía total restante no puede descender de los 20, por lo que nunca necesitan descansar".

Dado que lo único en que afecta la energía de un excavador es en si está descansando o no, **¿se entiende lo anterior como que el ExcavadorHíbrido tiene energía _virtualmente_ infinita?**

**Comment by Mcroquevielle** [comment]
Hola! Tengo una pregunta con respecto a la pérdida de energía del Excavador Híbrido. En el enunciado sale que la energía perdida se reduce a la mitad. De ser este número un float (por ejemplo, si la energía perdida es 7, entonces la mitad es 3.5) ¿debería redondearlo? ¿O se le resta el float? 
Gracias!!

**Comment by mtaguero** [comment]
¡Hola @Mcroquevielle!

En el enunciado dice que la energía corresponde a un int, no a un float. En este sentido, como no se especifica, queda a tu criterio si redondearlo o truncarlo.

No olvides mencionarlo en los supuestos tu readme.

¡Éxito! 🎈

**Comment by gasparbenavente2** [comment]
Hola me surgió otra duda respecto a lo mismo.
En el caso de consumir un item que tenga el atributo de energía **negativo**, que se debe hacer cuando un excavador del tipo 'Hibrido' lo consume. Restarle la mitad de esa energía? O restarle la energía correspondiente al consumible?

**Comment by mtaguero** [comment]
¡Hola @gasparbenavente2!

El enunciado dice explícitamente "(...) la energía perdida al momento de excavar se ve redu- cida a la mitad". Entonces, respondiendo a tu duda, este efecto no aplica a los consumibles.

Espero haber aclarado tu duda. ¡Éxito! 🎈
