### ISSUE TITLE
Interacciones adicionales con consola

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#137]
Es posible agregar funcionalidades adicionales que no estén en la pauta para facilitar la interacción con la consola, por ejemplo había pensado que al desplegar las estadísticas muestre cuantos trabajadores ocupados hay y cuantos desocupados

**Comment by VicenteMerino** [comment]
Aprovechando esta issue, en desplegar estadísticas los soldados son los que han sido efectivamente creados o también los que están en proceso de creación (notar que dice que al estar creando un soldado, este automaticamente se suma a la poblacion total, por eso pregunto, ya que me imagino que tambien se suma a la poblacion de soldados)

**Comment by jmwielandt** [comment]
Puedes poner las funcionalidades adicionales que estimes convenientes, sin embargo debes tener en cuenta que no habrá puntaje extra por ello y, dado eso, te recomiendo que solo comiences a implementarlas una vez estés listo con todo lo que se pide.

Mucho  éxito 😄
