### ISSUE TITLE
Nombres de galaxias y planetas

### ISSUE THREAD

**Issue by pcseisdedos** [IIC2233/Syllabus#137]
En los puntos 5.1 y 5.2 se establece que tanto las galaxias como los planetas deben tener un nombre (identificador único) que contenga mínimo 6 letras o números, tengo dos preguntas al respecto:
1 Debemos considerar los espacios dentro del largo del identificador? Lo que me hace sentido es no contarlos, enconces el nombre "abc 12" no sería válido.
2 Debemos aceptar como nombres válidos aquellos que contengan caracteres diferentes a letras, números y espacios? (Algunos ejemplos: $ ^ * £ ₩ $ # @ ! × % + & )

**Comment by geduran** [comment]
Respecto a este mismo punto tengo una duda/queja, porque no se debe permitir nombre de planetas con menos de 6 caracteres y al mismo tiempo no podemos modificar 'generar_archivos.py', pero en este se genera un planeta llamado 'Aiur'....!

**Comment by Hernan4444** [comment]
@pcseisdedos no está especificado el tema de los espacios como el tema de símbolos distintos. Por lo tanto queda a tu criterio que hacer en esos casos, pero no olvides especificarlo en el Readme la decisión que tomaste.
@geduran #126  

Saludos ✌️
