### ISSUE TITLE
Duda .gitignore, parametros.py, y archivos.csv

### ISSUE THREAD

**Issue by jervaal** [IIC2233/syllabus#137]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!, tenia una duda con respecto al uso de .gitignore, se que no será evaluado pero como me esta costando un poco usarlo, quiero empezar desde ahora. 

Mi duda es sobre, si ocupamos el gitignore, y ya no me sube los archivos, pero si quedan en el repositorio las versiones antiguas de estos, ¿que puedo hacer para eliminarlos?, ¿el gitignore se usa al inicio siempre?

La otra duda con respecto al uso de los archivos en mi codigo, es que asumi que la ruta que seguirian es la de repositoriopersonal/Tareas/T0/T0/Archivos_T0/Archivosusados.csv (usuarios, mensajes, etc)

¿Como se si todos los archivos puedan abrirse para la revision y funcionen correctamente ? (dentro de .../T0/T0 cree 2 carpetas: DCConecta2 y Archivos_T0, por lo que al ejecutar el programa en la 1ra carpeta, los paths relativos, son en referencia a la carpeta en que se ubica, y todos tienen la forma de Archivos_T0/archivo.csv). Si explico en el README.md que para que funcione el codigo, se necesita que ambas carpetas (DCConecta2 y Archivos_T0) esten dentro de la misma carpeta, ¿Esta bueno?

Ademas, cree un archivo de .txt en Archivos_T0, para ir teniendo un registro sobre las modificaciones que se hacen. Si este archivo no esta en "Archivos_T0", el programa no funciona. ¿Puedo Explicitar que es necesaria su creacion en el README.md ?, o es correcto el uso de este?

De antemano muchas gracias!

**Comment by matiasmasjuan** [comment]
Hola @jervaal !

Respecto a la primera pregunta, **sí**, lo ideal es usar el ```.gitignore``` desde el comienzo, justamente para evitar este tipo de problemas. Ahora bien, si ya hiciste un *push* al repo con los archivos y despues realizaste el ```.gitignore```, tal vez puedes ver la ***issue*** #113 que habla acerca del tema.

En relación a lo segundo, puedes hacer todas las carpetas que desees, siempre y cuando especifiques en el ***README.md*** cómo se deben estructurar y qué archivos deben estár en cada uno (*issue* #55 ). Con respecto a lo del nuevo archivo ```.txt```, dado que es **crucial** para que tu programa funcione, lo mejor sería subirlo a tu repositorio en lugar de explicar que debe ser **creado** en el ***README.md***.

Espero haber respondido a tus preguntas, y mucho éxito con la tarea! :smile:

**Comment by jervaal** [comment]
Muchas gracias!
