### ISSUE TITLE
AC02 inconsistencia tests y enunciado

### ISSUE THREAD

**Issue by canija2000** [IIC2233/Syllabus#137]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

En la descripción de los inicializadores de la `clase Vehiculo`  se dice que la energía debe setearse por defecto en **111**, sin embargo en los *test públicos*  se evalúa en **111.5** 
¿Cual es el valor correcto?
Gracias!

**Comment by canija2000** [comment]
También hay errores respecto a los `str`que retornan los métodos **recorrer** , en el enunciado dice : 
- "... y eso consume ..." (enunciado)
- "... y gaste ..." (test)

**Comment by Hernan4444** [comment]
Hola @canija2000 

Muchas gracias por notar esta discrepancia. Respeto a lo que comentas:

1. La energía oficial es `111.5`, fue un _typo_ del enunciado olvidar poner el `.5` (así la energía es, en todo momento, un `float` como indica el enunciado).

2. Se arreglaron los tests. Lo importante es el enunciado así que deben usar `"... y eso consume ..."`. Los tests privados tambien serán consistente con el enunciado (usar `... y eso consume ...`).

Acabo de pushear la AC2 corregida con lo expuesto anteriormente, para que puedas hacer `git pull` del Syllabus y probar tu desarrollo con los nuevos tests.

 ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ

**Comment by xperseosses** [comment]
Hola, también en los test cases de la clase Tesla el enunciado dice: "Debe llamar al método de la clase padre para recorrer los kilómetros indicados. Luego, modificar el texto retornado por la clase padre para agregar **de forma muy inteligente** al final".
Pero en los test cases piden el output: "de forma inteligente"

**Comment by Hernan4444** [comment]
Hola @xperseosses 

Ahí se arregló el tests. Se dejó como indica el enunciado (con el "muy").

Muchas gracias por notarlo y notificarlo!

¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ

**Comment by leonardosuarez777** [comment]
Buenas tardes,
Quisiera agregar que en el enunciado dice que en los métodos de AutoElectrico y AutoBencina dice que los métodos de recorrer deben decir "Anduve {N}Km y eso consume {Z}...", pero los testcases tienen un "Anduve POR..."
Saludos,
Leonardo

**Comment by Hernan4444** [comment]
Hola @leonardosuarez777 

El enunciado es el que mandara al final. Así que se corregirán los tests públicos y los futuros privados a la brevedad para ser consistentes con el enunciado (se sacara el POR)

Muchas gracias por notarlo y notificarlo!

¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ

**Comment by Hernan4444** [comment]
Hola @leonardosuarez777 

Ahora se pusheo el código para ser consistente con el enunciado. Muchas gracias nuevamente por avisar.

Cualquier cosa extraña que detecten con los tests VS enunciado, se agradece que lo avisen por esta issue para verificar lo antes posible qué está pasando. 

¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ

**Comment by leonardosuarez777** [comment]
Buenas profesor,
El enunciado sigue diciendo "de forma muy inteligente", pero los tests te piden que diga "de forma inteligente".
Saludos,
Leonardo

**Comment by canija2000** [comment]
Gracias! ya hice el pull y todo ok! ⭐

**Comment by juanriveraf** [comment]
Hola! en la parte de la property energia() de la clase Vehiculo se debe retornar el valor de la energia en un float. Sin embargo, el test case que verifica que el valor de la energia debe ser 0 si la energia dada es negativa es un 0 en int, y no en float (0,0). Nose si esto es un error o la idea es que cuando sea 0 la energia sea un int. Muchas gracias!

**Comment by Hernan4444** [comment]
Hola @juanriveraf 

No es un error, solo que el test valida que el valor sea `0`, pero es lo mismo que `0.0` en este caso. Dado que no estamos validando el tipo de dato en ese caso, solo que mantenga el valor mínimo indicado. Si pones `0` o `0.0` el test lo tomará igual de correcto.

¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ

**Comment by RGutierrez21** [comment]
Otra duda con respecto a los tests. En particular a los tests referentes a ```FaitHibrido```. Al correr los tests, obtengo los errores 
![image](https://github.com/user-attachments/assets/64deb2e9-a1ac-44d7-9a46-11157dca45db)

Pero al crear una instancia con el mismo código, con los argumentos de las clases de las cuales hereda ```FaitHibrido```, no obtengo ningún error. Esto será referente a los tests o a mi definición de la clase en sí? PD: Revisé los tests de las otras clases y todos están OK.

Mil gracias!

**Comment by Hernan4444** [comment]
Hola @RGutierrez21 

Este caso no es error de los tests, es que te falta en cómo defines el `__init__`. Te recomiendo ver, en los tests, cómo estamos creando cada instancia y contrastar esa forma de instanciar un `FaitHibrido` con lo expuesto en el enunciado.

 ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ

**Comment by RGutierrez21** [comment]
Muchas gracias, profesor. Lo revisaré

**Comment by TomyGomez19** [comment]
Hola, en ```test_telsa.py```  en el método ```test_llama_recorrer_clase_padres``` dice "test de forma muy inteligente" en vez de "de forma muy inteligente" 🫨

**Comment by Hernan4444** [comment]
Hola @TomyGomez19 

Eso no es un error, lo que pasa es que ese tests modifica en "return" de la clase padre para que diga "test" y luego se verifica que telsa conecte dicho return de la clase padre ("test") con el texto solicitado ("de forma muy inteligente"). De este modo, si tu clase padre hubiera estado mal programada, igual podemos revisar que la clase telsa haga bien lo indicado en el enunciado.

¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ
