### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by fbehncke** [IIC2233/Syllabus#137]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Quisiera saber si es correcto que los unicos archivos que debo poner en el git ignore son Enunciado.pdf, imprimir_tablero.py,  tableros.txt y la carpeta tests?
(Copié toda la carpeta de la T1 a mi repositorio)

Muchas gracias desde ya!

**Comment by Hernan4444** [comment]
Hola @fbehncke 

Efectivamente esos son los 4 elementos que nosotros te entregamos y que debes ignorar según el enunciado:

![image](https://github.com/IIC2233/Syllabus/assets/15641721/eb503582-fbcf-44f1-a187-bab00b984384)

No obstante, recuerda que en **Bases Generales de Tareas** se indica que además debes ignorar cualquier archivo/carpeta autogenerado por algún otro programa, tales como: `__pycache__,` `ipynb_checkpoints`, `.idea`, `.DS_STORE`, `.vscode`. Para este punto, recomiendo (1) siempre ir viendo a qué cosas le estás haciendo `git add` y (2) investigar y hablitar la opción de ver archivos ocultos. Varias veces estos no se ven asimple vista a no ser que se active la opción 2.
 
![image](https://github.com/IIC2233/Syllabus/assets/15641721/e09a1766-3925-4d8e-8a09-85b109bdf0f0)

Si cumples con todo eso, entonces estás aplicando correctamente el `.gitignore`

¡Mucho éxito con la tarea!
Saludosヾ(＾-＾)ノ

**Comment by fbehncke** [comment]
Muchas gracias, lo revisaré también. Sin embargo, por alguna razón al hacer git push, en mi repositorio personal se suben los archivos del git ignore de todos modos, por qué podría estar pasando esto? Gracias nuevamente

**Comment by Hernan4444** [comment]
Hola @fbehncke 

Lo que puede estar pasando son 2 cosas: (1) el `.gitignore` no está correctamente escrito o (2) el `.gitignore` fue hecho despues de haber hecho push de los archivos. 

Cuando pasa lo segundo, es porque si ya hiciste push de ellos, git no lo puede ignorar. Por lo tanto, los pasos para solucionar eso es:
1. Mover `.gitignore` y todos los archivos que no querías subir a una carpeta fuera de tu repositorio
2. Hacer add commit y push para subir un cambio de "limpieza". Así tu repo ya no tendrá los archivos a ignora.
3. Poner el `.gitignore`, y subirlo con add commit push.
4. Poner los archivos en tu repositorio. Y verificar con `git status` que git no los está detectando. En caso de estar detectándolos, es que el archivo de gitignore no está correctamente escrito. Y siempre que uno hace`git add` verificar con `git status` qué cosas se están subiendo específicamente, para que no se suba algo no deseado.

Avísanos como te va con esto,
Saludosヾ(＾-＾)ノ

**Comment by emivenezian** [comment]
hola. me paso lo segundo. mi computador no me deja crear un archivo que comience con . por lo que lo cree desde terminal y ahi lo subi, pero despues de haber subido todo. Como hago el paso 2: Mover .gitignore y todos los archivos que no querías subir a una carpeta fuera de tu repositorio. Mover de mi repositorio en github o en mi computador? y como lo hago?

**Comment by emivenezian** [comment]
ya lo solucioneee
