### ISSUE TITLE
Duda radio de explosión excede tamañano de tablero

### ISSUE THREAD

**Issue by valerianazal** [IIC2233/syllabus#137]
Hola, tengo una duda sobre el radio de explosión de las bombas especiales. ¿Qué pasa si el radio no es válido, es decir, si es mayor al tamaño del trablero?

**Comment by vicentevegaulloa** [comment]
Hola @valerianazal !

En el enunciado no se especifica nada sobre esto, pero lo lógico sería que ocupara todo el espacio disponible del tablero y no ser considerado como input inválido.

**Comment by Benja-c** [comment]
Hola dado que ustedes van a tener el archivo parametros y no va a ser un input que se le pide al usuario , puedo suponer que no crearan un mapa con largo de filas y columnas que sea mas pequeño que el radio de explosion?

**Comment by vicentevegaulloa** [comment]
Hola @Benja-c !

El tamaño del tablero se define una vez iniciado el programa, no en los parametros. Además no puedes asumir que no haremos un tablero más pequeño que el radio de explosión ya que eso depende no solo del tamaño del tablero, sino del radio que elijamos. En otras palabras, tu programa si debería ser capaz de manejar el caso en que el radio sea mayor al tablero.

Espero haber aclarado tu duda!

**Comment by Benja-c** [comment]
OK pero por ejemplo radio de explosion es 3, y creo una partida con tablero de 3x3, si lanzo la bomba diamante en el centro esta me cubre todo el tablero. Entonces en ese caso que pasa? Gano la partida?

**Comment by vicentevegaulloa** [comment]
Claro, en ese caso ganarías la partida.

**Comment by Benja-c** [comment]
Ya bacan gracias!!

**Comment by sbcorrea** [comment]
Hola! me queda una duda... en el enunciado igual dice que una bomba lanzada hacia el lado del tablero, donde 'sobra' radio de explosion hacia un lado, es valida y tenemos que contemplar ese caso evitando que se caiga el programa. Cual es la diferencia entre que sobre radio hacia un solo lado, y sobre radio hacia ambos lados, como para permitir la primera opcion pero prohibir la segunda?

**Comment by vicentevegaulloa** [comment]
Hola @sbcorrea !

Ninguna opción está prohibida.Tu programa debe ser capaz de manejar ambos casos.

**Comment by sbcorrea** [comment]
> Hola @sbcorrea !
> 
> Ninguna opción está prohibida.Tu programa debe ser capaz de manejar ambos casos.

Ahhhh entonces el problema no es en sí el radio de la bomba, sino que en ese caso *solo si es bomba diamante* cubriría todo el tablero?

**Comment by vicentevegaulloa** [comment]
No entiendo muy bien tu pregunta, pero es importante que sepas que cualquier radio de bomba es valido, para cualquier bomba especial. Esto quiere decir que tu programa debe manejar todos los casos como indica el enunciado. En el caso de un radio que haga que la bomba diamante cubra todo el tablero, el jugador ganará la partida. Se que suena como un bug, y lo es jaja pero no dejes que eso te confunda.
