### ISSUE TITLE
Escribir en archivos sobre lineas preexistentes

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#137]
Hola! No logro poder escribir más texto en una linea del archivo que ya existe (no hacer una fila nueva). Hay alguna forma o comando que sirve para eso? 
Muchas gracias

**Comment by jeschuwirth** [comment]
Hola @jirarrazabal,

Por simplicidad te recomiendo usar "w" y borrar todo el archivo y volver a escribirlo en lugar de escribir sobre lo que ya está.

Dicho esto recuerda que una línea termina cuando se encuentra el carácter "\n" por lo tanto para seguir escribiendo en ella basta con borrar el "\n", escribir lo quieras en esa línea y luego volver a colocar el "\n".

Suerte!

**Comment by jirarrazaval** [comment]
Perfectoo muchas gracias!
