### ISSUE TITLE
Magic methods en diagrama de clases

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#138]
Hola!

Los magic methods (`__str__`,` __repr__`, `__gt__`, etc.) se escriben en los diagramas de clases?

Saludos!

**Comment by sebacruzd** [comment]
No es necesario, solo pon los métodos más importantes. En caso de que los hayas sobreescrito para hacer algo muy distinto, ahí podrías anotarlo.

**Comment by akaminetzkyp** [comment]
Graciasn
