### ISSUE TITLE
Consulta: Informacion planeta

### ISSUE THREAD

**Issue by alexaptib** [IIC2233/Syllabus#138]
Para esta consulta se debe recibir el nombre de un planeta, para luego entregar información sobre este. Que pasa si existen dos planetas con el mismo nombre, pero en distintas galaxias? Puedo asumir que no se repiten nombres de planetas en distintas galaxias?

**Comment by dedarritchon** [comment]
Sale en el enunciado
**5.2. Planetas:**
**Nombre:** es el identificador único del planeta, debe ser una palabra con mínimo 6 letras o números.
El nombre no se puede repetir con el nombre de un planeta de otra galaxia.
