### ISSUE TITLE
¿En el chat el usuario debe ingresar el nombre del parametro (VOLVER_FRASE) o debe ingresar su valor (\volver)

### ISSUE THREAD

**Issue by NiceGuyWorz** [IIC2233/syllabus#138]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[¿En el chat el usuario debe ingresar el nombre del parametro (VOLVER_FRASE) o debe ingresar su valor (\\volver)?]

[Se indica que se deben usar las variables VOLVER_FRASE y ABANDONAR_FRASE del archivo parametros.py de forma que cuando en el chat se escriba alguna de ellas una accion dada ocurra.

Pero no me queda claro si en el input del chat debo reconocer "VOLVER_FRASE" (que seria un STR y no el valor de dicha variable ya que los inputs suelen ser STRs) o si debo reconocer "\\salir" (que seria el valor de VOLVER_FRASE.]

**Comment by matiasmasjuan** [comment]
Hola @NiceGuyWorz !

Esta pregunta fue respondida en la *issue* #133 .

Saludos! :smile:
