### ISSUE TITLE
Duda PEP-8 VSC Windows

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#138]
Hola! Alguien que tenga paciencia me explicaría cómo activar correctamente desde cero eso de que me avise los errores porfi? Y cómo funciona? 😅  Veo que hablan de un archivo settings.json, logré abrirlo y poner lo del issue #22 y no me funciona o no lo entiendo. Me sigue diciendo que las líneas son más largas que 79 caracteres cuando puse que el máximo tenía que ser 100 y pone errores en la mitad de la nada y no entiendo por qué se abre una pestaña cuando aprieto el error para ver qué es. Tampoco entiendo las rayas azules a la derecha de los números de línea 😢 Y cuál es la diferencia entre flake8 y pycodestyle? Ayudaaaa

**Comment by gaspcr** [comment]
Yo estuve exactamente en la misma hasta como hace 4 días que aprendí como funciona todo, así que te explico cómo lo hice por si te funciona: (Yo utilizo pycodestyle como linter, la diferencia con flake8 es simplemente que son 2 linters distintos pero los dos son para pep8 si no me equivoco).

1) Para descargar pycodestyle debes escribir en cualquier terminal (cmd en windows o la de vsc) "**pip install pycodestyle**"
2) Luego de instalada abres la paleta de comandos de VSC (ctrl + shift + p) y escribe "**Python: Enable Linting**" y seleccionas "**on**", eso es para activar el linter.
3) Luego abres nuevamente la paleta de comandos y escribes "**Python: Select Linter**" y allí te mostrará todos los linter que se pueden usar en VSC, en este caso deberías seleccionar el de **pycodestyle** ya que es el que estás instalando.

Y ya debería estar, luego si quieres ignorar o designorar oreglas ya te debería funcionar modificando el settings.json.
PD: Debería funcionar también de la misma manera para los demás linters, solo que cambiando el paso 1) donde instalas el linter que quieras utilizar

PD2: Te dejo los links de las páginas oficiales por si quieres más info (están en inglés): [https://pypi.org/project/pycodestyle/](url)
[https://code.visualstudio.com/docs/python/linting](url)

**Comment by gaspcr** [comment]
PD3(xd): [https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes](url) <- Aquí están todas las reglas de pycodestyle (pep8), los códigos de error que indica y sus respectivas restricciones. Al inicio es confuso y no se entiende bien qué estás haciendo mal, pero con la práctica vas entendiendo qué significa cada error :), espero que te sirva!

**Comment by kalarconvl** [comment]
@gaspcr miiiil gracias ahora entiendo todo! Y muy útil el link con todos los posibles errores
