### ISSUE TITLE
Bonus formulas.py

### ISSUE THREAD

**Issue by enzoyacometti** [IIC2233/syllabus#138]
Hola,

En el enunciado (sección bonus) se dice que hay que agregar un módulo para todas las fórmulas matemáticas e importarlas para usarlas en los demas módulos, sin embargo, el titulo dice "archivo funciones.py".
¿Se debe llamar funciones.py o formulas.py?
Y si tengo funciones no matemáticas pero que implemento en los demás módulos, ¿tambien puedo agregarlas a ese archivo?

Gracias!

**Comment by KnowYourselves** [comment]
Hola @enzoyacometti!

Para efectos del bonus, tan funciones como fórmulas son nombres válidos para el archivo .py.
En cuanto a lo segundo, no, la idea es que solo estén las funciones en ese archivo. Cualquier otra función auxiliar que no tenga que ver con las fórmulas debe ir en otro archivo.

Espero haberte ayudado!
