### ISSUE TITLE
Problemas con la terminal

### ISSUE THREAD

**Issue by maidazuniga** [IIC2233/Syllabus#138]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido

Estoy teniendo un problema al correr los archivos en la terminal. Al correr un archivo cualquiera, solo se muestran un par de líneas y el resto me sale como "..." y luego no me deja utilizar otro comando. 

Esto me está mostrando al abrir "todos_tests.py"
![Captura de pantalla 2024-03-25 183156](https://github.com/IIC2233/Syllabus/assets/162502366/a91caf07-32ea-41b7-9158-e61a77e676cf)

**Comment by ChupeteBecker** [comment]
Hola, es posible que tengas algún ciclo infinito. Para finalizar la ejecución puedes hacer ctrl+c, si eso no te funciona, puedes cerrar la terminal y volver a abrirla.

Avísame si esto soluciona tu problema.

Saludos

**Comment by maidazuniga** [comment]
Muchas gracias, sí funcionó
