### ISSUE TITLE
Duda orders activas

### ISSUE THREAD

**Issue by augustoas** [IIC2233/Syllabus#138]
Tengo una duda con respecto al date_match en el archivo de orders. Que NO tenga date_match (que esté en blanco) quiere decir que esta order está activa?
El problema es que hay orders que no tienen date_match(activas) pero que sí hacen match,  ya que cumplen con el criterio de precio para haberse ejecutado. Por tanto debieran tener date match.

Me tinca que el error está en la generación de los archivos nomás ya que se ocupo un criterio aleatorio para determinar si las orders eran ejecutadas o activas y no el criterio de precio que corresponde. 
Me gustaría  corroborar si estoy entendiendo bien la situación, gracias !

**Comment by cilopez** [comment]
@augustoas Si estas seguro que estas *orders* hacen *match*, podrías definir que apenas se ejecute tu programa, el sistema haga el *match* y guarde la fecha en la que se esté ejecutando  el programa . ¡Saludos!

**Comment by augustoas** [comment]
Entonces para qué sirve el dato date_match ? estaba diferenciando las órdenes que tenían date_match en blanco como las que estaban activas

**Comment by cilopez** [comment]
Las que están en blanco están son *orders* que estan activas, pero tu mencionaste que *hay orders que no tienen date_match(activas) pero que sí hacen match*, frente a ese problema te planteo una solución para que tu programa funcione de manera correcta.

**Comment by augustoas** [comment]
Por eso, que estén en blanco entonces no implica que estén activas, a eso voy. Puede ser que ya hayan hecho el match.  Entonces igual hay que chequear todas la órdenes para ver si están activas o no? si es así, y hay orders que hacen match despues de ejecutar el programa, su date_match sería la fecha actual? Gracias !

**Comment by cilopez** [comment]
Si, su date_match sería la fecha actual en ese caso. :+1:
