### ISSUE TITLE
Energía entrenadores, después de simular ronda

### ISSUE THREAD

**Issue by VicenteGarayR** [IIC2233/Syllabus#138]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Cuando se termina la ronda se pide restaure al máximo la energía de los entrenadores, cuando pide volver al máximo, ¿pide volver a la energía asociada al entrenador (energía del archivo entrenadores) o que la energía del entrenador se ponga en 100?

**Comment by Sancauid** [comment]
Hola @VicenteGarayR! Esto ya se respondió en la issue #113
