### ISSUE TITLE
Ordenamiento de listas de objetos

### ISSUE THREAD

**Issue by Dnpoblete** [IIC2233/syllabus#138]
Hola, quería saber si existe alguna forma de ordenar una lista de objetos según un atributo que tengan en común los objetos, porque no se me ocurre como hacerlo :(

Gracias

**Comment by roberto009** [comment]
Hola!
Existen muchas formas de hacer lo que preguntas. Primero te recuerdo que la función `sort()` te permite agregarle un `key` que determina en base a que va a ordenar tu iterable.  Por otro lado,  existe la posibilidad de hacer overriding a los métodos que comparan las clases ( `__eq__, __lt_ ,__gt__`) , esto permite que la función `sort()` compare sin necesidad del `key`. 
Te recomiendo que busques en Google un poco más del tema y utilices el método que más te convenga para tu caso.
Éxito en la tarea!

**Comment by Dnpoblete** [comment]
Es que el problemas que según yo no podría usar sort si la key es un atributo del objeto, porque como escribiría la key?

**Comment by roberto009** [comment]
Por ejemplo: 
```python
objeto1 = Objeto
objeto2 = Objeto 
# suponiendo que los dos objetos tienen un atributo altura
lista_para_ordenar = lista[objeto1, objeto2]
lista_para_ordenar.sort(key = lambda x : x.altura)
```
Espero que te haya quedado más claro.

**Comment by Dnpoblete** [comment]
Muchas gracias :) y una ultima pregunta eso los ordena de menor a mayor no cierto?

**Comment by roberto009** [comment]
La función `sort()` ordena por defecto de menor a mayor, pero puedes modificarlo agregándole el parámetro `reverse = Ture` , para que sea de mayor a menor.

**Comment by Dnpoblete** [comment]
Muchísimas gracias :)
