### ISSUE TITLE
Duda acerca formalidad/legibilidad: funciones dentro de métodos

### ISSUE THREAD

**Issue by MathiasPrett** [IIC2233/Syllabus#138]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. Es mal visto definir funciones **dentro** de un método que estoy definiendo? En el caso de hacerlo, debo mencionarlo especialmente en el README o algo por el estilo? 

Gracias de antemano por la respuesta.

**Comment by Dominique236** [comment]
Hola!
Si entiendo bien te refieres a definir una función dentro de otra definición (un método según tu pregunta), por ejemplo
 ```
def mi_metodo(self,...)
       def mi_funcion(...)
          ...
```
Y **no hay ningún problema con esto**, por lo que si se puede hacer y no es algo especial que mencionar en el README.
Cuéntame si esto resuelve tu duda 😊
