### ISSUE TITLE
Máximo 400 lineas de codigo

### ISSUE THREAD

**Issue by rmaguilera** [IIC2233/syllabus#138]
Hola, tengo la duda de si en esas 400 lineas cuentas las lineas en blanco, y si de ser asi, es obligatorio que deje una linea de espacio entre cada linea de codigo?. Tambien tengo la duda de si esas 400 lineas son por modulo o si todas las lineas que escribo en los distintos modulos y main no deben pasar de las 400?

**Comment by MatiasDuhalde** [comment]
Hola!

Pasarte de las 400 líneas en un módulo implica un descuento de 5 décimas, según la [guía de descuentos](https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md). Las líneas en blanco y las que tengas comentadas **sí** se consideran al contar las 400 líneas. 

Dicho esto, tampoco esperamos que debido a esta restriccion borren todas las líneas en blanco de su programa para ahorrar espacio (recuerden que también hay descuentos si a los ayudantes se nos hace muy complicado revisar su código). PEP 8 aconseja separar las definiciones de clases y las _top level functions_ por 2 líneas, y los métodos por 1 linea en blanco según lo descrito [aquí](https://www.python.org/dev/peps/pep-0008/#blank-lines). Si bien esta regla específica no está en nuestro [subconjunto obligatorio](https://github.com/IIC2233/contenidos/blob/master/semana-00/1-gu%C3%ADa-de-estilo.ipynb), es muy recomendable que la sigan.

Las 400 líneas, como especifíca la guía descuentos, son por módulo. Su programa puede tener 1000 líneas, y no recibirán descuentos siempre y cuando se cumpla el máximo de 400 líneas por módulo.

Para consejos sobre cómo modularizar te recomiendo revisar [este jupyter](https://github.com/IIC2233/contenidos/blob/master/semana-00/2-modularizaci%C3%B3n.ipynb).

Éxito en tu tarea!

**Comment by sbcorrea** [comment]
> Su programa puede tener 1000 líneas, y no recibirán descuentos siempre y cuando se cumpla el máximo de 400 líneas por módulo.

¡Hola! Me complica esto 😅 no había cachado el límite de 1000, y aún sin alcanzar a implementar nada de la parte Acciones, acabo de contar y mi Tarea zafó raspando, con 936 líneas 😓 ¿El descuento por >1000 es el mismo que el de 400/módulo? ¿Los parámetros también cuentan ahí?
**¿Podría hacer un archivo con info—prints largos, las opciones y los nombres de los menús, etc.—que no sea de extensión `.py`, y cargarlo a mi tarea a través de funciones, para que no me cuente en la cuenta de líneas?** En la próxima Tarea me gustaría llegar un poco más cerca de terminar el código, jeje. Además me imagino que habrá más cosas que programar.... y no se, dudo que las lambda me ahorren suficientes líneas siendo que el largo máximo de línea según PEP8 también es 72 caracteres  😢 ayua?

**Comment by KnowYourselves** [comment]
Hola @sbcorrea!

Lo que dice @MatiasDuhalde no es que puedan escribir como máximo 1000 líneas de código, es que ustedes pueden escribir cuanto códio quieran y si mantienen todos sus archivos en menos de 400 lineas, no habrá descuento.

Espero quede claro!

**Comment by sbcorrea** [comment]
Ooooooh **BIG OOF**
Acabo de cachar cómo estaba escrito y el tremendo rollo que me pasé jeje muchas graciasssss!! habría muerto si había otro máximo jajaja
