### ISSUE TITLE
Duda enunciado, eliminar prograposts

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2233/syllabus#139]
Hola! en el menu de prograposts esta la opcion de eliminar un post, este debe ser un post que haya hecho el usuario que esta iniciado sesion, o puede eliminar cualquiera como si los estuviera "bloqueando"? o queda a eleccion de uno mismo?

**Comment by MatiasDuhalde** [comment]
Hola!

En la sección 2 del enunciado se especifica lo siguiente:
> Un usuario debe ser capaz de eliminar _prograposts_ **creados por si mismo**.
Por lo tanto un usuario solo debe ser capaz de borrar sus propios posts.

Suerte en tu tarea!

**Comment by maggiemunoz** [comment]
chuta, se me paso esa parte, perdon jajaj gracias!
