### ISSUE TITLE
Commit a revisar erróneo de AC04

### ISSUE THREAD

**Issue by mafillol** [IIC2233/Syllabus#139]
El commit a revisar para la AC04 tomó el último commit, el cual correspondía al Readme de la T01.

**Comment by Hernan4444** [comment]
@mafillol No te preocupes, el commit a revisar se encarga de definir hasta que punto (de tiempo) se va a acceder a tu repositorio para buscar la actividad, es decir, se cargará tu repositorio hasta ese commit y de ahí se obtendrá tu AC04. Si para ese commit del Readme ya tenias la AC04 subida, entonces no hay nada de que preocuparse.

Sauludos!

**Comment by mafillol** [comment]
@Hernan4444  Muchas gracias.
