### ISSUE TITLE
Problema con el test de IteradorDCCMax

### ISSUE THREAD

**Issue by martina-abello** [IIC2233/Syllabus#139]
Cuando testeo la clase en un archivo aparte me funciona sin problemas, pero en los tests por alguna razón entrega la lista sin ordenar. ¿Alguien sabe por qué podría estar pasando esto, y/o cómo arreglarlo?

**Comment by aangel-sama** [comment]
Dónde estas ordenando la lista? Podrías intentarlo hacerlo dentro del __next__. Si aún así no te funciona, intenta darme más info para ayudarte

**Comment by martina-abello** [comment]
Lo tenía en __iter__, como apareció en los ejemplos del syllabus. Con moverlo a __next__ sí me resultaron los tests :D 
Muchas gracias!

**Comment by aangel-sama** [comment]
Bieeen, felicidad. La verdad no le encuentro una explicación de porque no funciona en el iter, pero bueno. Que bueno que lo hayas resuelto

**Comment by MatiLaB** [comment]
Que raro, a mi también me pasó lo mismo. Espero que no haya inconvenientes en temas internos.

**Comment by iacampillay** [comment]
Confirmo, me paso lo mismo, lo tenia en el _**__iter__**_ y no me funcionaba, no veía el error, pero lo cambie a _**__next**_ y funciona.
