### ISSUE TITLE
Duda menu de inicio, crear predios y otras mas

### ISSUE THREAD

**Issue by jtvvtj** [IIC2233/Syllabus#139]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Lo lei en otras issue pero no me quedo claro, cuando dice en el enunciado "Crear predios: Se encarga de usar el método crear_predios de la clase DCCultivo. Luego de esto, se debe continuar inmediatamente al Menú de Acciones."

Esto quiere decir que:
1. El archivo siempre sera predios.txt?, es decir, no hay que pedir un input() ?, por lo que nosotros en el codigo del MENU, definimos ->  crear_predios(llamamos a predios.txt)?, por lo que siempre deberia ocurrir lo mismo si el usuario marca la opcion 1?
2. Ademas esta es una duda general, pero que pasa cuando un usuario escoge una opcion que no se encuentra entre las disponibles?, es decir, en menu de inicio, tengo la opcion: 1,2. Si el usuario marca 3 que deberia pasar?, o por ejemplo si en ell menu de acciones marca 234234234 que claro es una opcion que no existe, que deberia pasar? 
3. Ademas el texto del menu "'[1] Crear predios'" todo eso es un str, incluyendo el "[1]"?
4. Cuando se presiona la opcion 5, no dice en el enunciado pero para confirmar, sera necesario realizar un print(), aludiendo al cierre del programa?

**Comment by vgalfaro** [comment]
Hola!
1. Puedes suponer que el archivo a leer siempre esté en "data/predios.txt" o puedes pedir un input para que el usuario ingrese el nombre del archivo, en cualquiera de los dos casos, te recomiendo que lo especifiques en el readme.
2. Se pide robustez en los menús, es decir, si el usuario ingresa un input que no está entre las opciones, este debe seguir funcionando, lo que puedes hacer es un print avisando que la opción ingresada no es válida y que intente nuevamente. 
3. Sí, "'[1] Crear predios'" es un str, el print no debería influir en el input, ya que este solo muestra en consola las opciones y al recibir el input debes hacer la lógica por detrás.
4. Queda a tu criterio si agregar o no el print, el menú que aparece en el enunciado es una guía y ejemplo, puedes personalizar el menú, pero siempre cumpliendo con lo pedido.

Espero haber aclarado tus dudas, saludos!

**Comment by jtvvtj** [comment]
Entiendooooo, muchaaaaas graciaaaas por la aclaracioooon :)
