### ISSUE TITLE
Distribución Puntaje Tarea00

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#139]
Hola!, queria saber cuando van a subir ,aprox, la distribución de puntaje.

**Comment by danckoo1** [comment]
Hola! Debería estar a más tardar mañana, pero de todas formas esa fecha podría cambiar si tenemos algún inconveniente :)

**Comment by YehudaGurovich** [comment]
Igual uno puede mas o menos saber que cosas valen mas de acuerdo a la dificultad al hacerlas o no?
Seguramente las bombas valen mas que el menu de inicio y posiblemente sean lo de mas valor junto con la manipulación del tablero (van de la mano igual).
