### ISSUE TITLE
Asignacion saldo usuarios_base_dato 

### ISSUE THREAD

**Issue by tavalenzuelag** [IIC2233/Syllabus#139]
Hola!, a la hora de trabajar con los usuarios de la base de datos qué asumo respecto a su saldo??, considerando que no todas las orders han tenido match y que por lo tanto, las orders de estos usuarios podrían interactuar con las de usuarios nuevos...

**Comment by Javierdr** [comment]
Me sumo a la pregunta, puedo asumir que tienen un saldo random para iniciar ?

**Comment by tavalenzuelag** [comment]
Yo creo que sería bueno, aunque teniendo como restricción que sea mayor o igual a la suma de los montos de sus orders de compra para que sea coherente... Otra pregunta que se me ocurre es también la tasa de interés de los mercados de las bases de datos también es un random?

**Comment by naazocar** [comment]
Creo que lo respondieron en #121 y lo de las comisiones también en otra, como solo dice que es un numero entre 0 y 1 queda a criterio de cada uno

**Comment by iqacevedo** [comment]
Hola 

Respecto a la tasa de esos mercados, tal como dice @naazocar es un número entre 0 y 1, una vez que la tasa se escoge recuerda mantener esa tasa en ese mercado.

Hay muchas issues que hablan de la otra pregunta, recuerden leer antes de preguntar. 

Saludos !
