### ISSUE TITLE
Absolute path/ relative path

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#139]
Hola, no me queda muy clara la implementación que se debe dar del absolute path y relative path. Lo que entiendo por absolute path es que si llego y "a la mala" escribo C:\Users\vamer\OneDrive\Escritorio\VicenteMerino-iic2233-2019-1\Tareas\T01 para abrir/crear un archivo eso se considera absolute path, pero si uso una forma de obtener el directorio actual y lo concateno con la siguiente direccion: /subcarpeta eso si se considera relative. Eso está bien?
Espero me lo puedan corroborar.

Saludos

**Comment by DCCollao** [comment]
Hola!

Efectivamente, los ejemplos que comentas están correctos. Eso sí, debes tener ojo con el separador que utilizas, pues no todos los sistemas operativos utilizan el mismo(la librería __os__ tiene una herramienta útil para verificar cuál es el que corresponde).
