### ISSUE TITLE
Duda sobre aplicar objeto tipo caramelo

### ISSUE THREAD

**Issue by bthompsonl** [IIC2233/Syllabus#139]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Me surgió una duda. Al momento de aplicarle un objeto de tipo caramelo a un programón, si por ejemplo este tiene la vida al máximo pero aún puede mejorar el ataque, ¿se aplica de todas formas haciendo que la vida se mantenga constante?¿o se tiene que cumplir que para cada aspecto del programón exista margen de mejora?

**Comment by martinjaraf** [comment]
Hola! Si la vida está al máximo igual puede mejorar el ataque y viceversa. Eso sí asegúrate de que la vida no supere los márgenes dichos en el enunciado.
