### ISSUE TITLE
elección de personalidad en Equipo 'Hibridos'

### ISSUE THREAD

**Issue by maormeno** [IIC2233/syllabus#139]
En el enunciado dice que con probabilidad 50/50 las personalidades de los pilotos del equipo 'Hibridos' deben ser una u otra. Esta bien usar random.choice(lista_con_ambas_personalidades) para seleccionar aleatoriamente una personalidad cuando se crea un piloto del equipo 'Híbrido'? O esto no necesariamente implica 50/50?

**Comment by jeschuwirth** [comment]
Hola,

No hay problema con utilizar random.choice(), debería ser 50/50

Suerte!
