### ISSUE TITLE
Duda con  el formato de usuarios.csv

### ISSUE THREAD

**Issue by Icarus328** [IIC2233/syllabus#139]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda con respecto al formato del archivo usuarios.csv, y es que cada nombre, después de ser ingresado tiene \n (Por ejemplo, usuario\n) menos el ultimo, esto me está generando algunos problemas, por lo que me gustaría saber si puedo arreglar este problema desde mi computador (Es decir, modificando el archivo .csv directamente) o si tengo que arreglarlo usando el programa.
Gracias

**Comment by Icarus328** [comment]
> Hola @Icarus328 !
> 
> Debes hacerlo dentro del programa, ya nosotros usaremos los archivos que te entregamos sin modificar para corregir la tarea. Animo con lo que queda!

Gracias!, entonces esto significa que los archivos estarán creados no? y que no es necesario que mi programa cree ningun .csv, solamente que los modifique?

**Comment by hsazos** [comment]
> > Hola @Icarus328 !
> > Debes hacerlo dentro del programa, ya nosotros usaremos los archivos que te entregamos sin modificar para corregir la tarea. Animo con lo que queda!
> 
> Gracias!, entonces esto significa que los archivos estarán creados no? y que no es necesario que mi programa cree ningun .csv, solamente que los modifique?

Exacto, solo es necesario que lo modifique.
