### ISSUE TITLE
Consulta primer ejercicio propuesto; carga de archivo

### ISSUE THREAD

**Issue by fernandolalanne** [IIC2233/syllabus#14]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

[Describe tu duda de manera detallada, explicitando el ejercicio en cuestión y explicando qué has intentado y tu problema (no colocar el código que has hecho)]

Hola! Quería preguntar si es posible que me orienten en cómo cargar el archivo csv. para poder realizar el ejercicio 2.1 de los ejercicios propuestos de esta primera semana. En un principio se me ocurrió importar path pero me confundí un poco en el código y busqué en internet y existe una forma de importar directamente csv pero el código que encontré es para imprimir lo que tenga el excel, no para dejarlo cargado y usarlo cuando se necesite.

Desde ya muchas gracias!

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by tqmbanados** [comment]
Hola! Recuerda que los archivos .csv, al igual que los archivos .py o .md, son archivos de texto plano. Esto quiere decir que se pueden abrir y cargar normalmente como un archivo .txt, como se enseña en los contenidos de la semana 0. La extensión del archivo le proporciona información adicional al computador sobre el formato que pueda tener el archivo, pues hay programas, como Excel en el caso de .csv, que los puede cargar automáticamente de una manera determinada. Un archivo csv significa que el texto contiene *valores separados por comas* (coma separated values), y también saltos de línea. Excel puede identificar esto como instrucciones para llenar celdas, pero el bloc de notas, y python lo pueden abrir como un archivo de texto normal. 
Por esto, no debería ser necesario importar una librería externa para abrir el archivo. 
Espero haberte sido de ayuda!

**Comment by fernandolalanne** [comment]
pero una vez que abra el archivo cómo podría guardarlo en una lista y dejarla ahí hasta que la necesite?

Gracias!!

**Comment by tqmbanados** [comment]
La lista es un objeto de python, no de tu computador. Mientras estés corriendo tu programa, puedes guardar los valores en listas, pero si quieres guardarla como un archivo para usar después, deberías usar un formato como csv. 
Ahora si tu pregunta es como transformar el archivo de texto cargado a una lista de python, revisa los contenidos de la semana 0, en el notebook ```paths```.
Te recomiendo que pruebes averiguarlo tú, es bastante más simple de lo que parece!

**Comment by fernandolalanne** [comment]
Muchas gracias!! Me estaba equivocando en una tontera ajajaja.

**Comment by tqmbanados** [comment]
Suele pasar jajajaja Me alegro que lo hayas solucionado.
