### ISSUE TITLE
Restricciones programación 

### ISSUE THREAD

**Issue by cchauriye** [IIC2233/syllabus#14]
Hola! 
¿Se espera que utilicemos herramientas específicas de programación (como clases, objetos...) o es libre?
Gracias!

**Comment by KnowYourselves** [comment]
Hola @cchauriye!

El formato de esta tarea es libre. Lo único que se te exige es cumplir las restricciones del enunciado y no ocupar _built-ins_ y módulos prohibidos. 

Espero haberte ayudado!

**Comment by cchauriye** [comment]
Gracias!
