### ISSUE TITLE
git

### ISSUE THREAD

**Issue by dunkannn** [IIC2233/Syllabus#14]
hola intentando hacer push me dio el siguiente error

C:\Users\dntg\Desktop\repo_practica\repositorio-practica>git push
remote: Permission to dunkannn/repositorio-practica.git denied to Dunkan1.
fatal: unable to access 'https://github.com/dunkannn/repositorio-practica.git/': The requested URL returned error: 403

que lo pudo haber provocado?

**Comment by sebacruzd** [comment]
Ya hiciste log-in en git mediante el cmd? Si aún no lo has hecho, puede que eso sea el error.
Eso es porque necesitas los derechos para hacer push al repositorio.

Intenta con esto:
https://help.github.com/articles/set-up-git/
