### ISSUE TITLE
readme, actividad 01

### ISSUE THREAD

**Issue by jfpena1** [IIC2233/syllabus#14]
Queria saber si se puede subir una especie de readme al respositorio personal para hacer mas facil el proceso de revision de la tarea. Si ese es el caso, como se podría hacer?

**Comment by hbkim94** [comment]
Hola @jfpena1 !

Lamentablemente, todas las actividades se recolectan una vez que se llega al tiempo límite de entrega , por lo tanto cualquier cosa que se suba después de dicha hora no se considerará para la correción.

Lo que podría recomendarte para futuras actividades y tareas (en las tareas **sí o sí** tienes que incluir un archivo readme), es que comentes directamente sobre tu código, ya sea utilizando `#`  o agregando una breve descipción al comienzo, para facilitar la correción. I.e.

```python
def foo(self):
    '''
    Breve descripción del método. 
    '''
    pass
```

Comentar o no tu código queda a tu criterio, más aún cuando en las actividades se dispone de tiempo límitado (pueden buscar formas de comentar su código en Google). En general, siempre será mejor/ideal que tus métodos corran/funcionen correctamente aún en ausencia de comentarios, que el caso contrario.

Saludos!

**Comment by jfpena1** [comment]
gracias!
