### ISSUE TITLE
Contenidos mínimos para cada actividad?

### ISSUE THREAD

**Issue by Isipirisi23** [IIC2233/Syllabus#14]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Contenido

Podemos ver en alguna parte los contenidos mínimos que requerimos para realizar la act0, act1 y la prox T1? y para las futuras entregas. Para saber hasta qué semana debo estudiar con firmeza para poder desarrollar estas sin problemas. 

Gracias! :3

**Comment by Hernan4444** [comment]
Hola @Isipirisi23 

Respecto a las AC, en los contenidos se dejó un [Readme.md con el desglose de contenidos](https://github.com/IIC2233/contenidos/blob/main/README.md) donde se indica para cada contenido, si hay AC o experiencia. En caso de ser AC, implica que ese contenido es el **principal a evaluar**, pero como se indica en el programa, una AC puede incluir todo lo anterior sin problema, solo que el _focus_ será el contenido de dicha semana.

Por otro lado, tenemos la [Ruta de Aprendizaje](https://docs.google.com/spreadsheets/d/1yMEBG3uIg0OAYOEsOQfl19IzR117b-k0ZTgWaKCEgNU/edit?usp=sharing) donde se detalla la publicación de cada evaluación (Ev. escrita, tarea y actividad). En el caso particular de las tareas, estas pueden evaluar todos los contenidos que están disponible al momento de publica la tarea. Por lo tanto:

- **T1**: evalua hasta la semana 2 [entorno de trabajo]. Si bien se permite usar el contenido de la semana 3, no es necesario para un correcto rendimiento.

- **T2**: evalúa hasta la semana 5 [iteradores]. Dado que ese viernes se publica tanto el contenido de la semana 5 y la T2. Pero el _focus_ será hasta la semana 4 [OOP Avanzado].

- **T3**: evalúa hasta la semana 9 [Threading], pero el _focus_ será hasta la semana 8 [funcional].

- **T4**: evalúa hasta la semana 14 [IG2], y aquí, como una tarea integradora, si será necesario tener los contenidos interiorizados hasta IG2 para poder desarollar de forma correcta la tarea.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con el curso! 🦖
Saludosヾ(＾-＾)
