### ISSUE TITLE
Duda en contenidos semana00-3 ¿Que retorna os.walk?

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#14]
Holaa! Revisando los contenidos de la semana 00 encontré en `3-paths.ipynb` un método que me llamó la a atención. En la ventana 11 de código se usa el método `os.walk`, entiendo que para recorrer una carpeta con archivos, pero no entendí muy bien de que forma lo hace ni que se supone que retorna este método (una lista de tuplas? (las cuales a su vez pueden tener una lista dentro?)). Creo que el string `"data"` vendría siendo la carpeta desde la cual se comienza a explorar, pero no estoy 100% seguro. Tampoco entiendo la función del argumento `topdown = True`. Si alguien me pudiese explicar se lo agradecería

**Comment by furcelay** [comment]
Hola!
Primero que nada te recomiendo que clones el repositorio `contenidos` para poder ejecutar los *jupyter notebooks*, así podrás resolver tus dudas experimentando, algo que deberías intentar antes de publicar una *issue*...

Intentaré responder tus dudas:
1. Argumentos: `os.walk(top, topdown = False)` 
  * `top` es un *string* en formato de *path* que indica el directorio que vas a recorrer, en este caso la carpeta `data` que encuentras en `semana-00`. 
  * `topdown` es un *bool* que indica si se recorre de arriba a abajo (`True`) o de abajo a arriba (`False`).

Puede quedarte más claro con un ejemplo:
```python
for raiz, directorios, archivos in os.walk("data", topdown = True):
    print("Raíz:",raiz)
    print()
    print("Archivos:")
    for archivo in archivos:
        print(os.path.join(raiz, archivo))
    print()
    print("Directorios:")
    for directorio in directorios:
        print(os.path.join(raiz, directorio))
    print("-"*30)
```
Retorna:
```
Raíz: data

Archivos:
data/archivo.txt
data/archivo_de_texto.jpg
data/files.png

Directorios:
data/gato
data/perro
------------------------------
Raíz: data/gato

Archivos:
data/gato/juego_1.txt
data/gato/juego_2.txt

Directorios:
------------------------------
Raíz: data/perro

Archivos:
data/perro/juego_3.txt

Directorios:
------------------------------
```
Mientras que:
```python
for raiz, directorios, archivos in os.walk("data", topdown = True):
    print("Raíz:",raiz)
    print()
    print("Archivos:")
    for archivo in archivos:
        print(os.path.join(raiz, archivo))
    print()
    print("Directorios:")
    for directorio in directorios:
        print(os.path.join(raiz, directorio))
    print("-"*30)
```
Retorna:
```
Raíz: data/gato

Archivos:
data/gato/juego_1.txt
data/gato/juego_2.txt

Directorios:
------------------------------
Raíz: data/perro

Archivos:
data/perro/juego_3.txt

Directorios:
------------------------------
Raíz: data

Archivos:
data/archivo.txt
data/archivo_de_texto.jpg
data/files.png

Directorios:
data\gato
data\perro
------------------------------
```
2. Retorna un iterable (un objeto que se puede iterar, al igual que las listas, en concreto es un `generator` pero eso lo verán más adelante en el curso :eyes:), en cada iteración se obtiene una tupla `(raiz, directorios, archivos)`, los tres son *strings* que creo puedes intuir a qué corresponde cada uno..., `raiz` varía en cada iteración tomando los valores de `directorios` (si `topdown=True`).

Espero haber respondido tu duda, 
Saludos!

**Comment by Gsalinas1506** [comment]
Yaa, entendí. Muchas Gracias!
