### ISSUE TITLE
Formato de la fecha en archivos T00

### ISSUE THREAD

**Issue by Etienne99** [IIC2233/syllabus#14]
Hola! Al extraer la fecha de un post del archivo posts.csv ésta aparece en formato dd-mm-yyyy (1), mientras que en el enunciado de la tarea dice que se debe trabajar en yy/mm/dd (2). Entonces, ¿Debo usar el formato 1 al agregar posts al archivo (posts.csv) y el formato 2 para mostrar posts en la consola?

**Comment by gatochico** [comment]
Hola! Para ambos casos debes usar el formato **yyyy/mm/dd**. Si te fijas, el archivo posts.csv también está con este formato :o 

Quedamos atentos a cualquier duda!

**Comment by Etienne99** [comment]
Ok, gracias

**Comment by furcelay** [comment]
Entonces usamos para ambos el año completo (**yyyy/mm/dd** en vez de **yy/mm/dd**)?

**Comment by gatochico** [comment]
Idealmente sí, por temas de consistencia.
