### ISSUE TITLE
Uso Git con repositorio remoto

### ISSUE THREAD

**Issue by pacita08** [IIC2233/Syllabus#14]
Por razones de fuerza mayor me ausenté a la actividad 00 y aunque ya he repasado toda la materia para ésta semana, estoy intentando hacer ésta actividad (fuera de plazo). Pero hay algo que no me resulta:

Resulta que configuré git y también cloné el repositorio con git clone. Luego creo la carpeta AC00 dentro de la carpeta con el mismo nombre que mi repositorio que se encuentra en mi computadora (no sé si tenía que hacerlo de forma directa, pero cree la carpeta como normalmente se hace) y le agrego hello.py que pedian. Pero al momento de escribir git status el archivo no aparece debajo del untracked más que Actividades/AC00  ¿Me falta un paso o un comando para que aparezca hello.py? 

Gracias :)

**Comment by flobarrios** [comment]
Hola!

Eso es porque la carpeta completa esta _untracked_. Si haces git add Actividades/AC00 se te va a agregar el archivo hello.py. Lo otro que puedes hacer es en la consola ingresar:

```
cd Actividades/AC00
```

Y al hacer git status dentro de ese directorio te debiese aparecer el archivo!

**Comment by pacita08** [comment]
toda la razón ocupando git add. Gracias!

**Comment by pacita08** [comment]
Entonces otra consulta, siguiendo en esta línea, cuando quiera agregar el archivo hello.py en el staging area debo agregarla así:
git add Actividades/AC00/hello.py 
porque cuando intento escribir:
git add hello.py 
me sale error

**Comment by flobarrios** [comment]
Si! lo segundo te sale error porque hello.py no esta directamente en el directorio "raíz" sino que está dentro de un subdirectorio.

**Comment by pacita08** [comment]
Gracias!
