### ISSUE TITLE
contenido y actividades

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#14]
1. En el documento "01-Objetos.ipynb" de la semana-1 del repositorio de contenidos, entre In [7] y In [8], parece que hay un error porque dice:

Para sugerir fuertemente que el método o variable sea interna, usamos doble underscore: __ En este caso, el acceso no es tan directo. Para acceder debemos indi <---aquí sería el error porque no dice nada más.

2. ¿Desde cuándo empiezan las actividades evaluadas en clase?

**Comment by andresfdezc** [comment]
2. Este jueves

**Comment by andresfdezc** [comment]
1. Gracias por el aviso, lo corregiremos a la brevedad.

**Comment by luvalenz** [comment]
Muchas gracias por avisar el error. Lo acabo de corregir. Pueden descargar ahora el documento actualizado.
Saludos!
