### ISSUE TITLE
En Mac: problemas con el setup de Jupyter

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#14]
Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Problema

Al seguir el video tutorial de Jupyter de MacOS, llego aproximadamente hasta el minuto 3:38. 

Del video logré hacer el paso de 'pip3 install jupyter' correctamente. Después me estanqué.
Tengo problemas cuando debo especificar la carpeta, para luego hacer el comando jupyter notebook.  Primero, no sé como especificar la carpeta. Segundo, no sé qué carpeta especificar porque no se cual es el notebook que me estan pidiendo (¿es un archivo que hay que descargar? Si es así ¿desde donde se descarga?).

**Comment by Maxy15** [comment]
Hola! A lo que se refiere el tutorial es como abrir un archivo jupyter cualquiera (.ipynb). Puedes probar si funciona tu instalación de jupyter con los archivos de los contenidos del curso, colocando el comando jupyter notebook en la terminal y seleccionando uno de estos archivos .ipynb desde jupyter, que estarán donde tengas guardada la carpeta de copia del repositorio de los contenidos.

**Comment by Fernanda1232123** [comment]
Sí, gracias!
