### ISSUE TITLE
Duda con respecto a 400 lineas tarea

### ISSUE THREAD

**Issue by yuwet15** [IIC2233/syllabus#140]
Hola, si es que el archivo pasa los 400 lineas, pero no por lineas de codigo, sino por comentarios, estaría bien?

**Comment by DCCollao** [comment]
Hola @yuwet15!

Los comentarios sí se consideran para el conteo de las 400 líneas límite en tu código. La forma de evitar el pasarte de ese límite es creando módulos e importándolos en tu `main.py`.

Es importante mencionar que un buen código no debiese necesitar muchos comentarios para lograr entenderse, pues se debería ser entendible al solamente leerlo.

**Comment by yuwet15** [comment]
ok entiendo muchas gracias
