### ISSUE TITLE
Excavadores_iniciales

### ISSUE THREAD

**Issue by SantiagoOsorio3** [IIC2233/Syllabus#140]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola ! 

En una issues respondieron que hay que darle el valor arbitriario a la cantidad de exploradores iniciales. Sin embargo, en el enunciado sale lo siguiente: "Pueden asumir que este valor será mayor a 0 y menor que la cantidad total de excavadores dados en excavadores.csv". Por lo que hay que hacer algo para que se cumpla esto o no ?

Tambien tengo una pregunta de la cita... Ya que sale que debera ser un numero menor a la cantidad total de excavadores, es decir que nunca se va a poder partir con todos ?

Gracias.

**Comment by panchouc** [comment]
Hola!

Efectivamente, cuando dice que `CANTIDAD_EXCAVADORES_INICIALES` será mayor a 0 y menor a la cantidad total de excavadores en el archivo `excavadores.csv`, como es un parámetro, lo puedes ir cambiando como estimes conveniente, lo importante es que cumpla con esa condición.

Respecto a lo que dice que es menor, no está explícito si es menor estricto o no, entonces queda a tú criterio, pero recuerda especificarlo en el `README`.
