### ISSUE TITLE
Cuándo se está usando una variable global

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#140]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Tengo dudas sobre cómo identificar una variable global. Entiendo la idea general sobre lo que es, pero hay casos donde no sé si se está usando o no. Como los siguientes:

```python
import a

def funcion_2(parametro):
    parametro += ....
    return parametro

variable = a.funcion_1()

while variable == "algo":
    variable = funcion_2(variable)
```
O, por ejemplo:

```python
import a

def funcion(parametro):
    parametro.append("")
    return


variable_1 = a.funcion_1()
variable_2 = a.funcion_2()
variable_3 = a.funcion_3()

funcion(variable_1)
```
De verdad no sé si alguna de las anteriores implica alguna variable global. 😢.

**Comment by tqmbanados** [comment]
Hola! La respuesta a tu pregunta es Sí y No 🤔. Las *variables globales* son aquellas que defines **fuera** de una función, se llaman así por que aplican a todo el programa. Un ejemplo de la tarea son las variables del archivo parámetros: estos no se definen como parte de ninguna clase, función, o método, sin embargo deben ser usadas como parte de varias de estas. Si dentro de una función, existe una variable con el mismo nombre que una *variable global*, la función usará esta *variable local* con el valor asignado, y la *variable global* no se verá afectada.
Entonces, los ejemplos de arriba presentan múltiples instancias de variables globales, pues no están definidas **dentro** de una función. Sin embargo, ninguna función las ocupa, por lo que tampoco se hace un uso de variables globales activo.
Finalmente, recuerdo que salvo en casos específicos (como el archivo ```parametros.py```), usar variables globales es considerado una "mala práctica" y puede traerte descuento. En general, siempre prefiere que las funciones ocupen parámetros entregados y variables definidas dentro de la función; en el caso de métodos, también los atributos de la clase a la cual pertenecen.
