### ISSUE TITLE
Estructuras de datos

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#140]
¿Podrían dar un ejemplo de a qué se refieren con la siguiente nota y por qué no es recomendable usar listas en ese caso?¿tiene que ver con la característica mutable de las listas?

"NOTA: EVITA el uso de las listas para coleccionar distintos atributos de un objeto o bien usarlas con algún tipo de acceso similar al uso de vectores en C++, como por ejemplo, usarlas como histogramas para la cuenta de palabras [‘a’, 1, ‘b’, 2]. Esto necesita diseñar un algoritmo de acceso a los datos dentro de la lista que hace engorroso su manejo. En este caso preferir el uso de otro tipo de estructuras como diccionarios, named tuples u objetos."

**Comment by KnowYourselves** [comment]
A lo que se refiere la nota es que no es recomendable usar listas cuando quieres acceder de manera especial a sus contenidos ya que una lista solo te permite acceder a sus contenidos mediante el uso de index. 

Supongamos que tuvieras el siguiente código:

```
class AlumnoIIC2233:
    def __init__(self, a, b, c):
        self.nombre = a
        self.cafeína_consumida = b
        self.estrés = c
```

Ahora supongamos que quisieras guardar la información de una de las instancias de esta clase de alguna manera. Usar listas sería complicado. ¿Cómo se haría?

La única forma posible sería hacer algo de la forma:

`["nombre, "Rubencio", "cafeína_consumida", 0, "estrés", -1]`

Pero luego para poder acceder a esta información deberías crear una algoritmo que te detectara que parte de la lista es nombre del atributo y que parte es su definición. Esto nos hace ver claramente que las listas de python no están bien optimizadas para esta clase de problema, mientras que con diccionarios o named tuples el problema se vuelve trivial. 

En resumen, lo que quiere decir la nota es que si para hacer un auto tienen la opción de utilizar ruedas cuadradas o circulares, mejor utilicen ruedas circulares.

**Comment by mjgutierrez1** [comment]
ok muchas gracias
