### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by jtvvtj** [IIC2233/Syllabus#140]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Si por ejemplo importe "DCCultivo" para ser usado en el código de los MENUS, es necesario mencionar en el README que se importó aquello?, ya que hay que mencionar las librerías propias, DCCultivo sería una librería propia o no?

**Comment by 3rdPix** [comment]
Librerías propias refiere a aquellos módulos que creaste tú y no venían propiamente con la tarea. En el caso de DCCultivos, es un módulo que nosotros les entregamos y ustedes tenían que completar: sabemos y asumimos que lo utilizarán e importarán, por lo que no es necesario mencionarlo. Sin embargo, si crearas otro módulo que no venía por defecto en la tarea, sí deberías mencionarlo.

**Comment by Mgseverin** [comment]
Hola! Tengo una pregunta respecto a esto. En el README hay que poner que la ejecución considera el archivo dccultivo.py o basta con poner que la ejecución principal es en main.py?

**Comment by 3rdPix** [comment]
@Mgseverin lo más importante es que indiques el archivo principal de ejecución y cómo luce tu directorio, para conservar la estructura y que el intérprete de Python pueda encontrar los módulos que quieres importar

**Comment by jtvvtj** [comment]
Pero cuando dices como luce el directorio, eso no daría igual? En el sentido de que al final lo que importa es lo que esté en el repositorio remoto o no?

**Comment by 3rdPix** [comment]
El repositorio es un directorio en este caso

**Comment by jtvvtj** [comment]
Claro, pero entonces no sería necesario decir como luce, si al final vemos lo mismo o no? Me confundí

**Comment by 3rdPix** [comment]
Sí y no, recuerda que hay archivos que debes ignorar. Si tu tenías esos archivos ignorados en un sitio distinto al mío, el intérprete de Python no lo encontrará. Por último, a menos que hayas codificado tu módulo para que pueda manejar la ejecución desde cualquier directorio, también es importante explicar desde dónde estás ejecutando los archivos. 

Por ejemplo si tienes un módulo `funciones_pulentas.py` dentro de un directorio `otros_modulos/`, y lo importas como `from otros_modulos import funciones_pulentas`, eso asume que estás ejecutando tu `main.py` desde el mismo directorio que contiene `otros_modulos/`, y si yo intentara correr el archivo desde otro lado, por ejemplo (suponiendo que creé una carpeta con tu nombre) `python jtvvtj/main.py`, el intérprete no encontrará `funciones_pulentas` porque en el directorio donde estoy parado no existe `otros_modulos/`. Por eso es necesario explicitar en tu README cómo estructuraste tu directorio y desde dónde ejecutar cuál archivo.

**Comment by jtvvtj** [comment]
Entiendo muchas gracias por la aclaración :)
