### ISSUE TITLE
Duda sobre elemento que retorna el IteradorDCCMax

### ISSUE THREAD

**Issue by Pablo-Gonzalez-Calderon** [IIC2233/Syllabus#140]
Hola, compañeros 😁

Haciendo la Parte 3 de la actividad implementé el IteradorDCCMax, el cual *corrió todos los tests correctamente.* Sin embargo, me di cuenta de que se podía ejecutar el archivo ``funciones.py`` de forma independiente y este ejecutaba un código que usaba los comandos implementados en el archivo. Todo en ese código funcionó bien hasta el momento de usar el IteradorDCCMax. Adjunto el código que usa el archivo (viene por defecto en el archivo, así que espero que no se considere como plagio)

```python
print('> DCC Max')
for (estreno, pelis) in DCCMax(list(cargar_peliculas(RUTA_PELICULAS))):
    print(f'\n{estreno:^80}\n')
    imprimir_peliculas(pelis)
```

Este código arrojaba error debido a que espera una tupla ``(estreno, pelis)`` al obtener el siguiente elemento del iterable. Sin embargo, en los *test cases* que revisan el iterador, se está trabajando como si se retornase un namedtuple ``Pelicula``. Por ello quería saber si alguien más (además de mí) retorna namedtuples ``Pelicula`` en el IteradorDCCMax y le da el mismo error al correr `funciones.py` de forma independiente. O también quisiera saber si alguien retorna otro tipo de dato --pero por enunciado, creo se esperaba que fuera un namedtuple ``Pelicula``.

Gracias a los que respondan 🍀✨

**Comment by MatiLaB** [comment]
Lo probé y me sale un error también al llegar ahí. Me dice `ValueError: too many values to unpack (expected 2)`. No sé si será el mismo error que te refieres, pero los por lo menos todos los test case me funcionan y haciéndolo con namedtuples `Pelicula`. Debe ser un error de definición dentro de `funciones.py`, si te corren los test no me preocuparía tanto.

Aún así, si logras cachar algo al respecto comentantalo para ver si se puede solucionar :]

**Comment by Laefivy** [comment]
Me aparece el mismo error y me corren todos los tests :(

**Comment by Pablo-Gonzalez-Calderon** [comment]
> Lo probé y me sale un error también al llegar ahí. Me dice `ValueError: too many values to unpack (expected 2)`. No sé si será el mismo error que te refieres, pero los por lo menos todos los test case me funcionan y haciéndolo con namedtuples `Pelicula`. Debe ser un error de definición dentro de `funciones.py`, si te corren los test no me preocuparía tanto.
> 
> Aún así, si logras cachar algo al respecto comentantalo para ver si se puede solucionar :]

Sip, es el mismo error. Volví a revisar todo y al final creo que es lo que dices, debe ser un error de cómo hicieron esa parte de ``funciones.py``. Confiaré en los tests jsjsjs 🍀

**Comment by abraxvs** [comment]
Hola, estoy bastante seguro de que es un error de código, ya que aquel que confeccionó dicho código esperaba que el iterador DCCmax retornara instancias que posean 2 argumentos, cuando en el enunciado se pide que el iterador retorne instancias de película.
