### ISSUE TITLE
Entrenador pierde batalla

### ISSUE THREAD

**Issue by sofialarrain** [IIC2233/Syllabus#140]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Cuando el entrenador escogido pierde una batalla, el campeonato se debe terminar o se pueden seguir simulando las partidas sin este?

**Comment by martinjaraf** [comment]
Hola! Recuerda que después de cada simulación de una ronda debes mostrar un resumen de esta, por lo que las batallas de esa ronda se deben simular y mostrar en el resumen. En el caso que queden más rondas no es necesario realizar esas batallas (si quieres puedes hacerlo aunque no es necesario) pero en el enunciado (Flujo del programa) dice que si pierde tu entrenador se le debe notificar, y dal la opción de comenzar de nuevo en el menú de inicio o salir del programa.
