### ISSUE TITLE
Duda descuentos PEP-8

### ISSUE THREAD

**Issue by benjaurr** [IIC2233/syllabus#140]
En la los descuentos, entre los aspectos que se revisaran del archivo, se incluye:

> 2. Que no haya variables no declarativas ni aclarativas

A qué se refiere esto?

**Comment by KnowYourselves** [comment]
Hola @benjaurr!

Ese punto hace referencia a que tus variables **deben** ser declarativas y aclarativas, es decir, deben tener un nombre que nos entregue información respecto a **qué es** la variable y **cuál es su objetivo**.

Este tipo de código se ganaría un descuento:

```python3
a = funcion()
b = sort(a)
print(b)
```

Mientras que este no:

```python3
notas = funcion()
notas_ordenadas = sort(notas)
print(notas)
```

**Comment by benjaurr** [comment]
Gracias!
