### ISSUE TITLE
Duda herencia 

### ISSUE THREAD

**Issue by lucastack** [IIC2233/syllabus#140]
Hola!, tengo una consulta con respecto a hacer herencia "condicionada" (leí por ahí que se llamaba herencia dinámica). Por ejemplo, si tengo 4 clases: A, B, C y D una quinta clase: X me gustaría poder instanciar X con sólo uno de los métodos __init__ de las otras 4 clases dado que se cumpla alguna condición. Hice esto y el código me funciona bien, la pregunta es: ¿es válido desde los puntos de vista de la corrección y de las 'buena prácticas'?

**Comment by jeschuwirth** [comment]
Hola,

Cuando haces multi-herencia en python y llamas al .\_\_init\_\_() de las clases padre, ocupas la función super().\_\_init\_\_(). Si no te sirve el init de todos los padres, quiere decir que el hijo no funciona exactamente como el padre, por lo tanto deberías evaluar si tu modelo está bien o no.

**Hint**: Por lo general no se suele heredar de más de 2 padres al mismo tiempo

Suerte!

**Comment by lucastack** [comment]
Eso no es exactamente lo que quiero. Lo que yo quiero hacer es solo llamar a un padre dado que se cumpla algo. En el fondo nunca hay múltiples llamadas porque la condición no lo permite, aun así ¿persiste el problema?

**Comment by jeschuwirth** [comment]
Puedes dar un ejemplo para dejarlo más claro?

**Comment by lucastack** [comment]
Claro, mira:

Class Barcelona_FC:
    def __init__(self):
        self.polera = 'Azul grana'

Class Real_Madrid:
    def __init__(self):
        self.polera = 'Blanca'
        
Class Jugador:
    def __init__(self, nombre, equipo):
        if equipo == 'barcelona':
            Barcelona_FC.__init__(self)
        if equipo == 'real madrid': 
            Real_madrid.__init__(self)
        self.nombre = nombre
        self.equipo = equipo

La gracia de esto es que despues puedo hacer lo siguiente:
jugador1 = Jugador('messi', 'barcelona')
jugador2 = Jugador('joaquin', 'real madrid')
La ventaja es que permite llamar directamente a Jugador para cualquier instancia y no llamar las subclases para cada equipo. Esto permite, por ejemplo, que si tengo una lista de (nombre,equipo) puedo hacer un for y ahorrar los if instanciando directamente Jugador(nombre, equipo). Básicamente es para hacer una única forma de instanciar jugadores

**Comment by jeschuwirth** [comment]
Para evitar el descuento de pep8, las clases son escritas con CamelCase (en el curso se ocupa PascalCase en realidad pero lo llamamos CamelCase), deben ser definidas todo junto y con mayúsculas separando palabras.

Para tu duda, lo comenté un poco con @jmwielandt, otro ayudante del curso, y llegamos a la conclusión de que lo que quieres hacer se asemeja bastante a Metaclases, materia que decidieron sacar de los contenidos del curso hace 2 semestres.

Debido a que se deben utilizar metaclases para que funcione correctamente, por simplicidad y para evitar problemas con las correcciones (ya que algunos ayudantes tampoco han visto la materia), te recomiendo utilizar la herencia vista en clases en vez de herencia dinámica.

Felicidades de parte de algunos ayudantes por tu manera de resolver el ejercicio, pero te sugiero nuevamente ir por la herencia vista en clases.

Suerte con la tarea!

**Comment by lucastack** [comment]
Muchas gracias!

Saludos

**Comment by jeschuwirth** [comment]
Como comentario extra para ti y los siguientes con esta duda, en esta tarea se va a evaluar el uso de herencia y multi-herencia, por lo tanto si decides usar una lógica de herencia parecida a metaclases no vas a recibir los puntos de la rúbrica asociados a la herencia vista en clases, ya que no podemos evaluar que sabes implementarlas.
