### ISSUE TITLE
Duda con 100 caracteres PEP-8

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2233/syllabus#141]
Mi duda es si el maximo de 100 caracteres por línea incluye la identación que en verdad son solo espacios. Yo al menos estoy contando sólo lo que está escrito, no la identación

**Comment by DCCollao** [comment]
Hola @jorge-ovalle!

El máximo de 100 caracteres por línea sí incluye la indentación pues, tal como indicas, corresponde a espacios y los espacios son también caractéres. Piénsalo como si dibujaras una línea vertical en los 100 caracteres hacia abajo, de la cual no te debes pasar en ningún caso. Te dejo un ejemplo de cómo se ve en mi editor:
![image](https://user-images.githubusercontent.com/37167447/91058521-8e47b100-e5f6-11ea-920d-cd9cb6e30d89.png)
 Junto con las [instrucciones](https://stackoverflow.com/questions/29968499/vertical-rulers-in-visual-studio-code) para agregarlo en vscode.
https://stackoverflow.com/questions/29968499/vertical-rulers-in-visual-studio-code

**Comment by railira** [comment]
con respecto a los caracteres VS code tiene alguna funcion que me diga cuantos caracteres tiene una linea?
