### ISSUE TITLE
Ordenar el muro del usuario

### ISSUE THREAD

**Issue by Mario-uc** [IIC2233/syllabus#141]
¿Como se puede ordenar los posts según el segundo elemento?
No sé si sort() tiene algún truco que te permita esa función
Ya que usando solo el sort() ordena según el primer elemento, que es el usuario en este caso.

**Comment by matiasmasjuan** [comment]
Hola @Mario-uc!

Recuerda que con la función **sort()** puedes añadir un **parámetro** denominado ```key```, donde puedes definir cómo quieres ordenar tu **array**. Quizás [este link](https://docs.python.org/3.7/howto/sorting.html) puede serte útil. Suerte!
