### ISSUE TITLE
Vehiculos y pilotos

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#141]
Al cargar una partida, como se debería escoger el vehículo?? dado que puede haber más de uno. Lo mismo para los contrincantes. Saludos

**Comment by jeschuwirth** [comment]
Hola,

El jugador elige su vehículo después de seleccionar la pista:
![image](https://user-images.githubusercontent.com/37160256/64214706-86d84680-ce7f-11e9-84b6-ea16bee1b771.png)

En cuanto a los contrincantes, como no está en el enunciado queda a criterio, por lo tanto puedes hacerlo de la manera que te parezca más conveniente (puedes asumir que todos los contrincantes van a tener siempre al menos 1 vehículo).

Recuerda colocar en el readme cual decisión tomaste con los contrincantes para evitarte problemas.

Suerte!

**Comment by dgzmr** [comment]
Gracias
