### ISSUE TITLE
Dudas respecto al formato de entrega para la tarea, PEP8 y Linter.

### ISSUE THREAD

**Issue by olherreragz** [IIC2233/syllabus#141]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola tengo dudas respecto al formato. Son cosas que el Linter de VS Code me corrige o no me corrige, me da indicaciones pero no se si cumplan con las reglas de PEP8 usadas en el curso.

En primer lugar, sé que PEP8 sugiere ocupar espacios entre ```=``` pero al definir argumentos dentro de una función, tales como:

* ```f(..., a = append)```
*  ```f(..., maxsplit = X)```
*  ```f(..., encoding='utf-8')```
*  ```f(..., key=algo)```

El linter me corrige sugiriendo no usar espacios entre ```=``` **sólo cuando estoy definiendo argumentos al llamar una función**, en la siguiente forma: ```f(..., a=append)```.

**¿Cuál es la forma que se considera correcta para usar en la tarea?**

En segundo lugar, al hacer print de strings usando ```"""``` y estoy dentro de una indentación, al pasar a la siguiente línea dentro de las comillas se rompe con el formato de indentación si está dentro de un ciclo o algo. Si agrego espacios para seguir con el formato de indentación de forma de no distorsionar mucho visualmente, entonces me imprime corrido.

**¿Se considera que se cumple con el formato (PEP8) si dejo que lo que está adentro del print "rompa" la indentación?**

Adjunto imagen para ilustrar.

![image](https://user-images.githubusercontent.com/71905553/113060420-fbbc5100-9186-11eb-8e55-e2c7f5330eda.png)

Muchas gracias!

**Comment by aaossa** [comment]
Hola @olherreragz , espero que estas respuestas te ayuden:

1. **Sobre espacios después de `=` en la declaración de funciones**: La corrección de tu *linter* es correcta. Debes usar espacios cuando estés haciendo la declaración de una variable (`variable = valor`), pero cuando estás indicando un *keyword argument* el espacio no va. De hecho aparece justo eso en [la guía original](https://www.python.org/dev/peps/pep-0008/#other-recommendations) (tienes que bajar un poco para encontrar la captura):

![image](https://user-images.githubusercontent.com/10425834/113061516-8782ad00-9188-11eb-9122-785707bc1645.png)

2. **Sobre indentación en *strings* largos**: Más que algo estilístico solamente, creo que lo que más te puede servir es la siguiente forma de declarar *strings* largos. Al menos yo la prefiero en muchos casos porque me ahorro el problema que mencionas y también porque creo que se ve más limpio el código (comparado con otras soluciones):

```python
string_largo = (
    "Esta es la primera línea mi string"
    " y esta es la segunda... "
    "ojo con agregar los espacios entre líneas"
    " (al final o al comienzo, da lo mismo, elige una y sé consistente)"
    "y también con que no se imprimen los saltos de línea."
    "\nSi quieres un salto de línea debes agregar el caracter que corresponda"
    "Ah y también fíjate que no he usado comas (,) después de cada string,"
    " sino esto sería una tupla y no es lo que queremos :)"
    )

print(string_largo)
```

Ojalá te sirva esta respuesta ✌️, pero si algo no queda claro pregunta por acá no más. ¡Éxito con la tarea ✨ !

**Comment by Rerro-r** [comment]
Hola @aaossa c: Sobre la identación en strings largos, es necesario seguir lo que dices? Es que yo usé ''' ''' para que se viera más bonito al momento de imprimir (rompiendo la identación). ¿Está mal?

**Comment by olherreragz** [comment]
Precisa la respuesta, quedó todo muy clarito 👌🏽 👌🏽 🙌🏽 🙌🏽 

Intentaré implementar ese hábito en el futuro para ser consistente con una forma que no distorsione.

Muchas gracias ✨ ✨ ✨

**Comment by aaossa** [comment]
Hola @Rerro-r , es perfectamente legal hacerlo como lo hiciste, solo que al romper la indentación el código se ve feo 😅 En resumen, lo que hiciste funciona y es perfectamente válido, solo no es lo más "bonito" en cuanto a código. A futuro te recomendaría hacerlo como respondí más arriba
