### ISSUE TITLE
Codigo Menus

### ISSUE THREAD

**Issue by jtvvtj** [IIC2233/Syllabus#141]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Me queda la duda, si al momento de crear el archivo para los MENUS, es necesario importar la clase PREDIO o simplemente basta con importa DCCultivo?, en mi caso solo importe DCCultivo, y me funciona el código, entonces me queda la duda si de igual modo habrá que importar la clase PREDIO, para temas de corrección o alguna otra cosa?

**Comment by vgalfaro** [comment]
Hola! si tu tarea funciona correctamente en tu computador (al correr el archivo principal donde se muestran los menús etc.) no debería haber problema, saludos!

**Comment by vgalfaro** [comment]
Por convención al archivo donde se ejecuta el programa se llama "main", si quieres llamarle de otra forma también está bien, en cualquier caso debes especificar en el readme cual archivo hay que ejecutar para correr la tarea. En el caso de que importes de la forma "from dccultivo import DCCultivo, Predio" Predio aparece en azul porque no lo estas ocupando directamente en el archivo donde lo estás importando, pero lo ocupas en DCCultivo a través del archivo dccultivo.py, lo que está correcto.

**Comment by jtvvtj** [comment]
Muchas graciaaaas :)
