### ISSUE TITLE
Exceder población máxima

### ISSUE THREAD

**Issue by isidonoso** [IIC2233/syllabus#141]
Que pasa si me pide generar 10 personas y tiene los recursos necesarios pero al generarlas sobrepasa el máximo de personas? Debo generar hasta las que pueda o puedo elegir no generar ninguna ?

Gracias

**Comment by gatochico** [comment]
Hola! La respuesta depende de quien realiza la acción:

-Si la acción es de los rivales/CPU, debes seguir lo estipulado en la issue #86 , que indica que si la acción de una CPU es inconsistente esta no se realiza y la civilización no hará nada ese turno.
-Si la acción fue realizada por el usuario, queda a tu criterio el como proceder. Recuerda indicar tu decisión en tu README para evitar cualquier malentendido.

Saludos y éxito!
