### ISSUE TITLE
Tarea 1, problema corriendo el test en visual code

### ISSUE THREAD

**Issue by IgnacioParraguez** [IIC2233/Syllabus#141]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

ese es el error que muestra visual code, el cual esta conectado a WSL , pero en la terminal si me corre el test, así que quisiera saber que hacer. muchas gracias 
![image](https://github.com/IIC2233/Syllabus/assets/110941492/6374fb2a-ec60-45f3-be09-4b1201c0b5ae)

**Comment by ManuelV03** [comment]
Hola, Visual studio code es una herramienta para editar codigo, no para ejecutarlo, por esto pedimos que corran sus codigos en la terminal. Si tu codigo funciona bien en la terminal sigue ejecutandolo por ahí.  Avísame que tal.

**Comment by IgnacioParraguez** [comment]
comprendo, muchas gracias, y bueno todo bien por la terminal. muchas gracias
