### ISSUE TITLE
Duda modificar galaxia

### ISSUE THREAD

**Issue by frduran** [IIC2233/Syllabus#141]
Hola! Tenía entendido que la diferencia de estar jugando en una galaxia y modificarla es que cuando, por ejemplo, quiero crear nuevos soldados, al estar jugando, el programa me debería preguntar cuantos soldados deseo crear mientras que al modificar una galaxia, se trata siempre de llegar al máximo de soldados disponibles. Si es así, entonces aplicaría lo mismo para la tasa de minerales y deuterio (de tratar de llegar al máximo posible)?

**Comment by dedarritchon** [comment]
Según yo la diferencia es que al estar jugando tiene que ser en un planeta conquistado y los soldados y magos te cuestan minerales y deuterio. Y no necesariamente tendrías que aumentar al máximo los soldados y magos, o las tasas de minerales y deuterio de un planeta no conquistado cuando estás modificando. (Por ej. si quisieras invadirlo y conquistarlo en el juego te conviene que tengan menos soldados y magos) eso es lo que entendí yo por lo menos.

**Comment by frduran** [comment]
@dedarritchon gracias!

**Comment by santilaguna** [comment]
Según entendi, en modificar galaxia son solo los planetas no conquistados. Mientras que en jugar en la galaxia son solo los conquistados. En ambos casos sólo se puede aumentar la cantidad de los soldados

**Comment by Clemente24** [comment]
Ojo que en el enunciado, en el punto 6.2, las capacidades de modificación de los planetas no conquistados es SOLAMENTE aumentar las tasas o cantidades de soldados...
