### ISSUE TITLE
Uso de globals

### ISSUE THREAD

**Issue by Sforrego** [IIC2233/Syllabus#141]
Estaba pensando usar globals al definir cosas como el mercado, por ejemplo 
a = ["NEBCLP", "CLPNEB"]
for i in a:
    globals()[a] = Mercado(a)

podria servir a la hora de buscar el mercado al que queremos acceder o algo por el estilo.

Que opinion tiene del uso de globals()[]? 
Muchas gracias!

**Comment by fringlesinthestreet** [comment]
El uso de globals es __mala__ práctica.

Si quieres tener acceso a instancias de manera de manera "global" puedes hacer uso de atributos de clase. A continuación te muestro un ejemplo.

```
class InstanciasGlobales:
    '''
    Aquí definimos un atributo de clase. 
    Este siempre puede accederse a través de: NombreClase.nombre_atributo
    En este caso, InstanciasGlobales.instancias
    '''
    instancias = []

    
    def __init__(self):
        '''
        A medida que instanciamos, agregamos a la lista la instancia 
        En este caso llamada 'self'
        '''
        InstanciasGlobales.instancias.append(self)

```

De esta forma, podemos llamar a las instancias de la clase ```InstanciasGlobales``` siempre que queramos utilizando ```InstanciasGlobales.instancias```

**Comment by fgbruna** [comment]
Tengo una duda respecto a esta issue,es posible actualizar una variable de clase con cada ejecución de un script?
Es decir,si yo instancio un objeto en una ejecución y tengo escrito en el constructor que agregue la instancia a la lista de instancias,en mi próxima ejecución ese objeto estará en la lista?
