### ISSUE TITLE
Cantidad de opciones en menú

### ISSUE THREAD

**Issue by sofial21** [IIC2233/Syllabus#142]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Al momento de recibir una opción (entre las cuatro) en el menú, hay que volver a mostrar el menú hasta que se seleccione la opción 4? Por ejemplo, si el usuario marca 1, luego de mostrar el tablero se vuelve a mostrar el menú de acciones?

**Comment by Dominique236** [comment]
Hola!
Tal como mencionas, se debe volver a mostrar el Menú de Acciones hasta que se seleccione la opción _salir del programa_.
Cuéntame si esto resuelve tu duda 😊

**Comment by sofial21** [comment]
Sii, muchas gracias

**Comment by sofial21** [comment]
Sii, muchas gracias
