### ISSUE TITLE
Directorio solo visible en git

### ISSUE THREAD

**Issue by ploello** [IIC2233/syllabus#142]
Hola,
queria preguntar por que en la tarea al hacer `git status` una de las entradas esta entre comillas, con la estructura de un directorio 

> .gitignore
        Enunciado.pdf
        Readme.MD
        contrincantes.csv
        parametros.py
        pilotos.csv
        "veh\303\255c****.csv"

pero no puedo encontrar el directorio en mi computador

**Comment by jmwielandt** [comment]
Hola!

Ese archivo se corresponde a `vehículos.csv`. Pasa que la consola de git no es capaz de representar tildes por el encoding que ocupa.

<details>
<summary>Haz click en el triángulo para abrirme</summary>
<br>

![image](https://user-images.githubusercontent.com/37153467/64218945-93659a80-ce91-11e9-829a-e9460e82e6cf.png)

</details>

En el `.gitignore` no hay ningún problema con usar tildes.

<details>
<summary>Imágen 2</summary>
<br>

![image](https://user-images.githubusercontent.com/37153467/64218988-bbed9480-ce91-11e9-8914-fb2393881445.png)

</details>

Saludos~

**Comment by ploello** [comment]
Gracias!
