### ISSUE TITLE
Actividades Semanas Tarea

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#142]
Hola! , no recuerdo si esta en el programa, queria saber si vamos a tener actividades las semanas con tarea.

**Comment by Baelfire18** [comment]
Hola! Si abran actividades las semanas con tareas, más estas serán formativas, es decir, no serán una nota, será solo practica de los conocimientos asignados a esa semana. 
Serán solo para formar y ayudar practicar las mismas cosas que se verán. Aparte darán una bonificación al final de semestre como decimas.
Es altamnte recomendado ir a estas actividades. Ya que ayudan a llevar a la practica muchos conocimientos
