### ISSUE TITLE
Orden dentro de archivos .csv

### ISSUE THREAD

**Issue by tgellonag** [IIC2233/Syllabus#142]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, en los archivos .csv, arena.csv, tesoros.csv, etc. los atributos de cada objeto siempre estaran en el mismo orden?

Es decir por ejemplo para arena siempre sera:

nombre,tipo,rareza,humedad,dureza,estatica
 
o tambien podria cambiar a algo como 

nombre,tipo,humedad,estatica,rareza,dureza

**Comment by panchouc** [comment]
Hola!

En la página 13 del PDF se indica que puedes asumir que el orden de cada columna no variará, entonces para arena, por ejemplo, se mantendrá el orden que aparece en el enunciado.

**Comment by tremendapithon** [comment]
Una consulta los parámetros que tenga el archivo puede cambiar al momento que ustedes lo vayan a probar, tipo si la edad se supone que es un int, ustedes lo cambiaran por algún valor no numérico. Por ejemplo:

La edad es un entero igual a 18.
Y mi lo que pienso es que la edad sea por ejemplo dieciocho.

Lo anterior mencionado podría pasar, saludos.

**Comment by panchouc** [comment]
Hola, en la issue #202 se respondió ese caso. El tipo de datos está especificado en la parte de **5.Archivos** por lo que puedes asumir que el tipo de dato indicado no cambiará.
