### ISSUE TITLE
Posts

### ISSUE THREAD

**Issue by Mario-uc** [IIC2233/syllabus#142]
¿Al momento de ordenar, tenemos que considerar el caso de que dos posts se hayan hecho el mismo día, es decir, si se escribieron el mismo día importa cual va primero?
Por ejemplo si escribí dos posts seguidos (por lo que tienen el mismo día), ¿también se deber ordenar por cual escribí primero? (porque si uso sort () se ordenará según las letras del cuerpo del posts, ya que lo demás será igual)

**Comment by matiasmasjuan** [comment]
Hola @Mario-uc!

No, no importa en que orden se encuentren los posts ya que no hay parámetro de hora en los archivos otorgados, solo se diferencian por la fecha. Por lo tanto, no hay forma de diferenciar cuál post debe ir primero y cuál después en posts escritos el mismo día. En todo caso, esta pregunta fue tratada en la [Issue # 70](https://github.com/IIC2233/syllabus/issues/70). Suerte!
