### ISSUE TITLE
error al buscar archivo en la ruta relativa os.path.join

### ISSUE THREAD

**Issue by graci007** [IIC2233/syllabus#142]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! 
tome todos los archivos excel y los agregue a una carpeta, la cual se encuentra en el mismo directorio del código de la tarea 0, entonces al realizar lo siguiente -> path_usuarios = os.path.join("avanzada","usuarios.csv")  e intentar abrirlo me aparece el siguiente error **FileNotFoundError: [Errno 2] No such file or directory: 'avanzada\\usuarios.csv'**
estoy muy confundida ya que nose que mas hacer para poder abrir los archivos, gracias c:

**Comment by IgnaciaJ** [comment]
Hola @graci007 ! Desde que directorio se está corriendo tu terminal? Asegurate que esté en la carpeta T0! avisame! suerte:)

**Comment by IgnaciaJ** [comment]
En caso de que programes en vscode puedes abrir toda la carpeta T0 en tu editor de texto?

**Comment by graci007** [comment]
ahora me funciono al abrir la carpeta en vscode! muchas gracias!

**Comment by IgnaciaJ** [comment]
@graci007 bacan!! Éxito en tu tarea!!!
