### ISSUE TITLE
Formato borders.csv

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#142]
Hola!

Existe alguna razón por la que se utilizaron punto y comas (`;`) en vez de comas (`,`) en el archivo `borders.csv`? Ahora cuando abrimos el archivo en github no arma una tabla como antes. 😢

Saludos!

**Comment by sebacruzd** [comment]
Si quieres ver una tabla puedes abrirlo con Excel.
De todas maneras, el trabajo con un archivo csv que tiene ";" en vez de "," es prácticamente lo mismo.

**Comment by akaminetzkyp** [comment]
Gracias!
