### ISSUE TITLE
currencies

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#142]
¿Es necesario crear la Clase currency?

La duda la tengo por el hecho de que digan que una currency tiene nombre y símbolo. El tema es que el nombre no sirve de mucho; lo que se necesita es reconocer un símbolo para diferenciar currencies y saber la cantidad de cada tipo de currencie que tiene cada usuario.

Eso por ejemplo se podría hacer con un atributo del usuario llamado dinero que fuera un diccionario donde las keys son los símbolos de las currencies y los valores son la cantidad que tiene el usuario de esa currencie. Manejar la plata del usuario sería mucho más complicado usando una clase Currency.

**Comment by egromero** [comment]
Holaa, queda a tu criterio crearla o no, pero recuerda que la tarea es de modelación OOP.

Saludos!

**Comment by SarahEverke** [comment]
¿En el csv de Currencies está la moneda de DCCapital Exchange?

**Comment by cilopez** [comment]
@SarahEverke  En el archivo no estan pero ten en cuenta eso #54 , #64
