### ISSUE TITLE
Galaxia sin planetas

### ISSUE THREAD

**Issue by pcseisdedos** [IIC2233/Syllabus#142]
Tengo 2 dudas al respecto:
1. Al crear una galaxia debo exigirle al usuario que cree un planeta dentro de esta galaxia? o simplemente cuando quiera jugar en ella le debo decir que no tiene planetas y que si quiere jugar en ella o modificarla debe crear un planeta.
2. En caso que el usuario decida eliminar el único planeta de una galaxia, debo impedirlo? exigirle que cree otro planeta? o simplemente dejarlo y hacer lo mismo que en el punto 1.

**Comment by IchottMano** [comment]
@pcseisdedos Hola!
Tus dudas se resuelven en la issue #35 
En particular la segunda, queda a tu criterio.
Saludos!
