### ISSUE TITLE
Duda Error en la funcion crear_predios

### ISSUE THREAD

**Issue by JosefaATP** [IIC2233/Syllabus#142]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!
Al ejecutar los test_públicos para la función crear_predios, la terminal me arroja lo de las fotos. Pero no logro entender que es lo que sucede, entonces no sé que debo arreglar. 
Porque se que al tener algo malo la terminal imprime lo que se debe imprimir y lo que arroja mi código pero eso no lo hace.

Gracias!!
<img width="1067" alt="Captura de pantalla 2024-08-23 a la(s) 19 32 45" src="https://github.com/user-attachments/assets/36f1e433-e854-4de6-8e47-7109443b2f40">
<img width="1510" alt="Captura de pantalla 2024-08-23 a la(s) 19 33 21" src="https://github.com/user-attachments/assets/9ebdd1cd-bd38-40e7-bcd8-29a42a9d815d">

**Comment by Agusrush21** [comment]
Probablemente no estas retornando el mensaje que pide.
A lo mejor lo estas imprimiendo pero no retornando

**Comment by vgalfaro** [comment]
Tal como dijo tu compañero, el error en este caso se debe a que no estas retornando nada en la función crear_predios, te recomiendo ponerle ojo a eso, saludos!

**Comment by JosefaATP** [comment]
Si, ya después empezó a imprimir y no le cambie nada. 🤷🏻‍♀️

Gracias!!
