### ISSUE TITLE
Archivos en el repositorio

### ISSUE THREAD

**Issue by isidonoso** [IIC2233/syllabus#142]
Al hacer mi tarea necesito tener los archivos acciones, civilizaciones, etc. en mi repositorio para que funcione. Tengo que subir estos archivos cuando haga push? o solamente los que creé yo?

**Comment by jmwielandt** [comment]
No es necesario que subas los archivos del directorio `data/` (es mejor si no los subes) pero tampoco hay repercusiones en caso de que los subas.
