### ISSUE TITLE
Problemas para actualizar git de Syllabus (pull)

### ISSUE THREAD

**Issue by egbusch** [IIC2233/Syllabus#143]
Por alguna razón no me deja utilizar el comando git pull para actualizar los cambios que van realizando en la carpeta Syllabus. Lo raro es que estaba funcionando bien hasta hace unos dias. Alguna idea de como solucionarlo ? 
Este es el error que me arroja:

Last login: Fri Mar 24 22:45:11 on ttys000
MBP-de-Esteban:~ estebanbusch$ cd /Users/estebanbusch/Desktop/prograavanzada/Syllabus 
MBP-de-Esteban:Syllabus estebanbusch$ git pull
remote: Counting objects: 23, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 23 (delta 7), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (23/23), done.
From https://github.com/IIC2233/Syllabus
   fc561fe..624c2c5  master     -> origin/master
error: Your local changes to the following files would be overwritten by merge:
	.DS_Store
Please commit your changes or stash them before you merge.
Aborting
MBP-de-Esteban:Syllabus estebanbusch$

**Comment by akaminetzkyp** [comment]
El archivo `.DS_Store` guarda las propiedades (e.g. posición de los iconos) de la carpeta en la que está. También me ha aparecido ese error, y para mí, la solución más simple es borrar ese archivo. En la mayoría de los casos no debería importar. Para borrarlo, ve a la carpeta que lo contiene y escribe en terminal `rm .DS_Store`. Después deberías poder hacer `git pull` sin problemas. :)

Saludos!

**Comment by egbusch** [comment]
Finalmente solo borre la carpeta y la clone de nuevo, pero estaba curioso por el error. Gracias.

**Comment by akaminetzkyp** [comment]
De nada! :)

**Comment by fcgfaura** [comment]
Creo que si haces git stash se soluciona. Para la próxima prueba eso :)

**Comment by fvr1** [comment]
@egbusch efectivamente (como dice @fcgfaura) se soluciona ejecutando `git stash`. Este comando te permite eliminar todos los cambios que se hicieron desde el último commit. En este caso, te aparece que el archivo `.DS_Store` había cambiado e iba a ser sobreescrito al hacer `git pull`
