### ISSUE TITLE
[PyQt6] Usando WSL las ventanas aparecen en una posición random

### ISSUE THREAD

**Issue by dvillas28** [IIC2233/Syllabus#143]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda :skull:
Esto es algo que me pasó mientras estaba ejecutando los scripts de la semana 4. No lo noté al principio, pero cuando trate de setear la posicion de una ventana al origen (0,0) (esquina superior izquierda) la ventana simplemente se genera en una posicion aleatoria en la pantalla.

Se puede ver en la imagen que estoy poniendo a la ventana en (0, 0): `setGeometry(0, 0, 300, 300)`

![image](https://github.com/IIC2233/Syllabus/assets/128737225/fd32b944-b37e-4808-a1c4-8303bc67eb26)

Cabe decir que corri el mismo codigo desde Windows 10, y ahora obedecia, asi que supongo que tendra que ver con el WSL de algun modo (lei en varias otras *issues* que esta libreria esta dando varios problemas en WSL) . **Quiero saber si esto es necesariamente un problema para lo que se vaya a hacer mas adelante en el ramo o si la hago corta nomas a correr pyqt6 en win10**.

¿A alguien mas le ha pasado esto con WSL?
Saludos!

**Comment by catalinamirandah** [comment]
Hola ✨️,

Si, efectivamente algunos han tenido problemas cuando intentan utilizar PyQt6 desde wsl, pero no te preocupes, por esta vez tendrán permitido utilizar la consola de Windows para ejecutar sus códigos de interfaces gráficas. De todas formas, uno de los profesores en la issue #131 respondió algo similar, prueba qué tal te va con eso y sino utiliza cmd nomás. 

Saludos :D
