### ISSUE TITLE
Duda items en entidad Arena

### ISSUE THREAD

**Issue by RGutierrez21** [IIC2233/Syllabus#143]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda acerca de la entidad Arena. En particular, **con los items que esta pueda tener**. Leyendo con detención el enunciado, no se define con exactitud cuáles son los items que tendrá cada arena y en el .csv que contiene los datos y atributos de cada instancia de arena tampoco se encuentra información acerca de los items. **Se tendrá que aleatorizar el contenido de items de cada arena o simplemente cada vez que un Excavador realice la acción cavar tendrá una probabilidad de encontrar un item aleatorio?**

Muchas gracias!

**Comment by panchouc** [comment]
Hola!

Los ítems que puede tener una arena son los que están especificados en la parte de los consumibles (**4.4.1**) y tesoros (**4.4.2**). Estos ítems están definidos en `consumibles.csv` y `tesoros.csv`. Respecto a la probabilidad de encontrar un ítem aleatorio, está especificado en la parte **4.3** del enunciado.

![image](https://user-images.githubusercontent.com/94400598/231584178-3df25eae-0997-4253-9a73-b3ef6593fb8e.png)

**Comment by RGutierrez21** [comment]
Entendía esa parte, mi duda es con la parte 4.2 del enunciado, donde especifica que items corresponderá a conjunto de todos los items que pueden aparecer en la arena. Según lo que me respondes, entonces, este conjunto sería igual para todas las arenas?

Nuevamente, muchas gracias!

**Comment by panchouc** [comment]
Claro, de hecho en la misma parte 4.2 del enunciado, aparece esta descripción en la arena 
![image](https://user-images.githubusercontent.com/94400598/231602642-545d6032-717b-4888-b7f5-719a8bb58b53.png)
Lo que implicaría que son todos los ítems para la arena, sin importar que tipo de arena se está trabajando.

**Comment by RGutierrez21** [comment]
Muchas gracias! Quedó clarísimo.

**Comment by tremendapithon** [comment]
Hola buenas noches tengo una duda respecto a la PROB_ENCONTRAR_ITEM, no entiendo si es una variable de mi archivo parametros.py??

**Comment by Benjeeeh** [comment]
@tremendapithon 
Si, debe estar incluido en tu archivo **parametros.py**. Todos los parámetros que se encuentren en el enunciado en ESTE_FORMATO (en azulito) deben estar incluido en el archivo.
![image](https://user-images.githubusercontent.com/78326186/232668437-5f4280d5-9b3a-46d4-9bd6-4a8d7bcf4ed0.png)
La idea en este caso es que el valor que le otorgues haga sentido con la formula (y como se trata de una probabilidad se encuentre entre valores de 0-1)

**Comment by SantiagoOsorio3** [comment]
Hola ! cuando dice "Lo que implicaría que son todos los ítems para la arena, sin importar que tipo de arena se está trabajando.", se refiere a todos los items que se encuentran en el archivo ?

**Comment by panchouc** [comment]
Así es

**Comment by luc0i** [comment]
Hola! Tengo una duda con respecto a la probabilidad de encontrar un ítem.
Cuando dice: "Posterior a verificar si el excavador pudo obtener un ítem, si esta probabilidad acierta". 
No entiendo cómo verificar que se encuentre el ítem. 

Habría que hacer algo como lo que se hizo en la Actividad 2 en el método de robar_tortuga()?
`def robar_tortuga(self) -> bool:`
   `    # PROBABILIDAD_ROBAR de robar la tortuga`
   `    if random() < self.PROBABILIDAD_ROBAR:`
   `    self.notificar_robo`


Gracias!

**Comment by panchouc** [comment]
Claro, sería algo de ese estilo.
