### ISSUE TITLE
Print() respetando Pep-8

### ISSUE THREAD

**Issue by nicolascamhi** [IIC2233/syllabus#143]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Como puedo romper un print muy largo para cumplir con PEP8? Traté con \ pero en el terminal se ve mal.

**Comment by Juampisaez** [comment]
Hola @nicolascamhi
Mm, yo te recomendaria hacer lo mismo que dijiste jejeje, de igual manera hay mas formas.
Te dejo un [link](https://stackoverflow.com/questions/53162/how-can-i-do-a-line-break-line-continuation-in-python:) donde puedes encontrar mas información para respetar el PEP-8.

Avisame si te sirve, quedo atento :)

**Comment by aaossa** [comment]
Hola @nicolascamhi , esto es semi duplicado de #141 , por si quieres ver la conversación de allá ✌️

**Comment by nicolascamhi** [comment]
Si vi ese issue, pero eso no me sirve por ejemplo, para registrar mensajes en mensajes.csv. Al poner \ o romperlo en distintas lineas se generan espacios adicionales que luego traen problemas a la hora de leer los mensajes directamente del archivo. 

Eso me sirve para todo menos para cuando cuidar el formato es demasiado importante.

Puedo dejar un par de lineas >100 caracteres? Se perdonan algunas si son pocas?

**Comment by Juampisaez** [comment]
@nicolascamhi revisaste el link? ahi aparecen unas formas faciles de hacer un print para respetar el Pep-8.
Por ejemplo:
```
Print("Este es un codigo muy largo"
      "si quieres respetar Pep-8 tendras"
      " que separar las lineas")
```

De esta forma respetas el Pep-8 y puedes hacer un print largo en una sola linea.

Espero conteste a tu pregunta :)
