### ISSUE TITLE
Duda sobre output de la función detectar_plagas

### ISSUE THREAD

**Issue by Ignaciadiazgr** [IIC2233/Syllabus#143]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo una duda sobre el output de la función dtectar_plagas, si es que en uno de los predios con plaga no se elimina ninguna celda, igualmente se debe agregar a la lista de output el código de predio con celdas eliminadas = 0? o simplemente se omite este predio en el output? 

No me quedó claro esto con lo que dice en el enunciado. Gracias!

**Comment by Agusrush21** [comment]
Si las plagas eliminadas terminan siendo 0 en un predio, este no se agrega a la lista de listas que debes retornar.
Igual puedes probarlo con los test que ahi queda mas evidente.
