### ISSUE TITLE
Salir del Sistema

### ISSUE THREAD

**Issue by AndresGarciadelaHuerta** [IIC2233/Syllabus#143]
Hola, tengo una duda grande con respecto a lo que dice el pdf con respecto a salir del sistema. Cuando dice "...el programa debe cerrarse..." se refiere a que se le cierra la sesión y otro usuario puede ingresar (con todos los datos actualizados dentro de la aplicación) y seguir siempre dentro de la aplicación (corriendola en python todo el tiempo). O bien cerrar la aplicación, saliendo de python, abrir python de nuevo un rato después por ejemplo, correr la aplicación y que se inicie como quedó la última vez? Es decir, que al cerrar el programa debemos escribir todos los datos necesarios (muchos más que los que hay en los csv) en uno de los csv dados o incluso creando uno? Espero se entienda mi duda, gracias!

**Comment by iqacevedo** [comment]
Hola,

Se refiere a que se cierre la aplicación (cerrando Python) y que cuando se vuelva a abrir el programa tenga en el sistema todos los cambios echos por el usuario anterior. Por lo anterior en alguna parte debes escribir los datos de tu sistema para que no se pierdan (tú escoges el formato y como lo guardas porque la idea es que tú programa lea después esos mismos datos).

Saludos !

**Comment by bedefrunner** [comment]
Respecto a este mismo tema, puede ocurrir el siguiente escenario?:

El/la ayudante corre el programa por primera vez con los archivos users, currencies, orders orginiales o nuevos archivos, estos se van actualizando ya que el codigo es capaz de hacerlo, pero luego cierra la aplicacion, cierra python, abre  el archivo currencies.csv y cambia un dato: saca la moneda CLP. Luego, abre de nuevo la aplicacion. El programa, al iniciarse, leera el archivo currencies.csv y notará que ya no está la moneda CLP.

Si es que este escenario es posible, qué debe hacer el programa con todos los usuarios que tengan CLP en sus balances y/o que estén registrados en los mercados XXXCLP y/o CLPXXX? Qué pasa con los registros de bids/asks que se hicieron con en estos mercados? 

La pregunta aplica a modificaciones de cualquier archivo. Agregar datos a archivos ya existentes no seria problema, simplemente habria que leer mas datos que antes e iniciarlos en el programa, pero sacar un dato previamente existente es lo que me genera la duda.

**Comment by ewaugh2** [comment]
Hola,

respecto a la primera pregunta que se hizo en esta issue tengo otra duda.

En el apartado 3 del enunciado (DCCapital Exchange) aparece en el 5to parrafo lo siguiente:
> Ademas, se debe permitir que un usuario cierre sesion y luego otro usuario inicie sesion sin tener que reiniciar la aplicacion.
Pero mas adelante en el enunciado aparece lo referido en la primera pregunta:
> Cuando un usuario desee dejar de utilizar el sistema, el programa debe cerrarse...

Como se concilian esas dos instrucciones?

Gracias!

**Comment by ewaugh2** [comment]
Hola,

respecto a la primera pregunta que se hizo en esta issue tengo otra duda.

En el apartado 3 del enunciado (DCCapital Exchange) aparece en el 5to parrafo lo siguiente:
Ademas, se debe permitir que un usuario cierre sesion y luego otro usuario inicie sesion sin tener que reiniciar la aplicacion.

Pero mas adelante en el enunciado aparece lo referido en la primera pregunta:
Cuando un usuario desee dejar de utilizar el sistema, el programa debe cerrarse...

Como se concilian esas dos instrucciones?

Gracias!

**Comment by ewaugh2** [comment]
Hola,

respecto a la primera pregunta que se hizo en esta issue tengo otra duda.

En el apartado 3 del enunciado (DCCapital Exchange) aparece en el 5to parrafo lo siguiente:
"Ademas, se debe permitir que un usuario cierre sesion y luego otro usuario inicie sesion sin tener que reiniciar la aplicacion."

Pero mas adelante en el enunciado aparece lo referido en la primera pregunta:
"Cuando un usuario desee dejar de utilizar el sistema, el programa debe cerrarse..."

Como se concilian esas dos instrucciones?

Gracias!

**Comment by Arcoirisky** [comment]
@ewaugh2 Imagina que estás en Facebook con tu cuenta. Tú eres feliz posteando memes y comentando publicaciones, luego llega alguien más y te pide el computador, entoces sales de tu cuenta para que esta persona pueda hacer sus cosas en Facebook (cambio de usuario). Luego, cuando la persona se aburre, cierra la página (se cierra el programa) y se va. 

¿Se entiende? Tu programa debe permitir el cambio de sesión y cerrar el programa

**Comment by Arcoirisky** [comment]
@bedefrunner sobre tu caso hipotético, quédate tranquilo. Generalmente no tocamos los archivos de esa forma malévola. Es decir que, en teoría, no sacaremos datos previamente existentes de un archivo. Espero que eso te dejé mejor :D

**Comment by ewaugh2** [comment]
@Arcoirisky  ok gracias!

**Comment by Arcoirisky** [comment]
Tranquilo skdnsk no vamos a tocar nada. Sólo te daremos un .csv nuevo proyecto probar tu programa y luego no lo tocamos

**Comment by bedefrunner** [comment]
Pues que no hallo la forma de agradecerle por esta tan magnifica respuesta, milady.
