### ISSUE TITLE
Duda con avance diagrama de clases

### ISSUE THREAD

**Issue by crow-rojas** [IIC2233/syllabus#143]
Hola!

Quería saber si es necesario que cada clase de mi diagrama tenga si o sí todos los métodos y atributos que voy a implementar. Suena obvio, pero nunca está de más preguntar, aparte de que la idea de esto es realizarlo antes de pasar a código, se hace complicado imaginar cada detalle de cada clase y pasarlo directo al diagrama. Entonces, la idea de este avance es hacer una visión global a "grandes rasgos" de lo que será cada clase y cómo estarán relacionadas? Cómo se evaluará si el avance está bueno y serán efectivas las 2 décimas? Se me hizo esta interrogante porque en el enunciado dice que en ambos casos (avance y entrega final del diagrama), se tienen que cumplir una serie de condiciones.

Espero me puedan aclarar esto, gracias!

**Comment by jeschuwirth** [comment]
Hola,

Es muy normal que el diagrama del avance sea distinto al final que vas a entregar y también es normal que este sea diferente a tu código final. La idea del diagrama es que se hagan una base de como van a escribir el código y cuando se hace te das cuenta pronto de los problemas que podían traer ciertas implementaciones.

Para la evaluación, se va a evaluar el avance y se entregarán 2 décimas bonus a los diagramas bien hecho (no significa que tu código va a ser exactamente así), se va a subir un feedback general de todos los avances y luego se va a evaluar el diagrama final cuando subas tu código.

Espero se hayan aclarado tu dudas, suerte en la tarea :)

**Comment by Mahund** [comment]
Que gran respuesta @jeschuwirth !
Espero te haya sido útil @crow-rojas :D

**Comment by crow-rojas** [comment]
Gracias @jeschuwirth! Me aclaraste todo bien!
@Mahund lov u <3
