### ISSUE TITLE
Condiciones para crear objetos: energia y probabilidad

### ISSUE THREAD

**Issue by isajofre** [IIC2233/Syllabus#143]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Josefinafp: Hola!! Tengo una duda. El enunciado dice "Crear este objeto gasta GASTO_ENERGIA_BAYA de energía y tiene una probabilidad de éxito de PROB_EXITO_BAYA", esto significa que por yo querer crear un objeto (resulte o no) se le gasta la energía al entrenador, y que el resltado de la creación sea exitoso se debe comparar con una probabilidad aleatoria?
O que primero se tiene que ver si la probabilidad es mayor y ahí se disminuye la energía del entrenador?

-(Lo vi en otra issue pero la indicación decía que correspondía a una nueva y que había que crearla)

**Comment by martinjaraf** [comment]
Hola! Cuando intentas crear un objeto (independiente si fue éxito o fracaso) gastas la energía según el parámetro de cada objeto. Luego de ese gasto energético debes usar el parámetro de probabilidad para determinar si la creación fue exitosa o no.
