### ISSUE TITLE
T00 Flujo de la partida

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#143]
Tengo que darle las opciones al jugador del menu de juego antes de que juegue el oponente? Es decir el menú se habilita al final del turno completo (no se puede rendir antes que juegue el oponente) o se puede rendir en el medio del turno?
No se si me explico bien. :/

**Comment by jitorralba** [comment]
Hola @YehudaGurovich!
Los únicos instantes dentro de los cuales el jugador no está en su turno son aquellos donde se ejecuta el turno del oponente (automático y casi instantáneo). Por lo que el jugador debería tener todas las opciones del menú de juego cuando sea su turno.
Respondiendo más concretamente el caso de **Rendirse**, si, el jugador debería tener la opción de rendirse y de esa forma perder automáticamente la partida.
Avisame si te quedó claro!

**Comment by YehudaGurovich** [comment]
Aun me queda una duda. Mi pregunta era si el jugador podía rendirse antes que el oponente juegue.

**Comment by jitorralba** [comment]
Si! Debería poder rendirse

**Comment by YehudaGurovich** [comment]
Entonces no es inmediata la jugada del oponente. Tengo que agregar una opcion en el menu de juego que sea avanzar de turno (o jugada del oponente)

**Comment by jitorralba** [comment]
Recuerda que el menu de juego es de la forma: 

```
1. lanzar bomba
2. rendirse
3. salir
```

Y que el turno del oponente empieza solo cuando se lanza una bomba en una coordenada vacía, por lo tanto, si te rindes no estarías lanzando ninguna bomba y el turno no pasa nunca al oponente , por lo que la partida termina ahí con derrota para el jugador. Pasaría lo mismo con salir, ahí el programa se cierra sin esperar a que el oponente juegue, porque tampoco se lanzó ninguna bomba.

**Comment by YehudaGurovich** [comment]
Entonces no hay que dar la opcion de rendirse entre la jugada del usuario y la del oponente. (Que era la pregunta inicial, pero mi redaccion deja mucho que desear)

**Comment by jitorralba** [comment]
Efectivamente! Sólo cuando sea el turno del usuario

**Comment by YehudaGurovich** [comment]
Ahora me quedó claro! Gracias! Es mas facil asi que tener que interrumpir el flujo del juego en el medio.
