### ISSUE TITLE
Disparo repetitivo 

### ISSUE THREAD

**Issue by enriquerussi** [IIC2233/syllabus#144]
En las reglas básicas del juego aparece que no se puede disparar en una posición que ya se disparo.
Esto quiere decir que no se va a dar el caso en el el jugador ingrese una misma posición 2 veces por ser regla básica, o se refiere a que nos se va a aceptar por lo que si se llega a dar el caso, se tiene que desplegar un mensaje que diga que no se puede y que pida otra posición para disparar:

**Comment by DCCollao** [comment]
Hola @enriquerussi!

Lo correcto es la segunda opción que mencionas. Es posible que al probar tu programa ingresemos 20 veces la misma coordenada, para ver si manejaste correctamente ese caso. Esto tiene relación también con la sección menús, donde especificamos que ellos deben ser a prueba de cualquier error, es decir, deben ser capaces de manejar **cualquier** input. 

Quedo atento a cualquier duda!
