### ISSUE TITLE
En menu: consulta sobre el concepto de "aprueba de errores"

### ISSUE THREAD

**Issue by Juan-M-Ovalle** [IIC2233/Syllabus#144]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Si el usuario introduce una opción distinta a 1, 2, 3 o 4; se debe finalizar el programa o imprimir un mensaje y dar la opción de repetir la respuesta?

**Comment by Benjeeeh** [comment]
Hola!
Se debe volver a mostrar el menú y dar la oportunidad al usuario de ingresar un input correcto. Con _menú a prueba de todo error_ se refiere a esto, que si el usuario ingresa cualquier input que no sea 1, 2, 3 o 4, el programa no se cierre ni arroje algún error. La única forma de cerrar el menú sería cerrando el programa (opción 4).

Saludos!
