### ISSUE TITLE
Sobre archivos

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#144]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Existe alguna otra recomendación en cuanto a este tema que debamos tener en cuenta?

**Comment by hsazos** [comment]
Hola @fernandosmither ,

Sobre tu primera pregunta, si puedes asumir eso. Con respecto a tus otras 2 preguntas, puedes organizar el programa como estimes conveniente, mi recomendación es dejar todo bien detallado en el readme para que el ayudante que te corrija no tenga problemas. Ánimo con lo que queda de la tarea!
