### ISSUE TITLE
Duda respecto a la fecha de match

### ISSUE THREAD

**Issue by lootarola** [IIC2233/Syllabus#144]
Tengo una duda respecto al archivo orders.csv, debido a que para que exista una orden con una cierta fecha de match, es necesario que exista otra orden que la complemente con la misma fecha de creación que la fecha de match, puesto que de no ser asi, significaría que ambas ordenes estuvieron en el mismo mercado e hicieron match despues de un tiempo y no de forma inmediata. Mi duda es cómo debo emparejar las orders entregadas en el archivo, ya que podrían existir varias ordenes que pueden complementarse y hacer un match.

**Comment by iqacevedo** [comment]
Hola

En el archivo orders si hay orders que complementen a las que tienen match.¿Como emparejarlas?, debes responder la pregunta ¿Que datos en común deben tener para que estén emparejadas? No te puedo decir la respuesta pero con eso deberías poder hacerlo. 

Respecto a las orders que no tienen match y podrían hacer un eventual match con otra de la base de datos, tienes que revisar que ese match efectivamente se pueda hacer (que el usuario que compra tenga el saldo para pagar) y ahí podrías hacer el match tú mismo cuando incie el programa. 

Saludos !
