### ISSUE TITLE
Entrega Avance Tarea

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2233/syllabus#144]
Hola! El diagrama hay que subirlo al syllabus o a nuestro repositorio personal?

**Comment by KnowYourselves** [comment]
Hola @jfuentesg26!

En este curso **todo lo que vayas a subir será a tu repo personal**. El syllabus simplemente sirve como el punto donde se subirá todo lo que sea común a todos los alumnos como los enunciados. De hecho si intentaras subir algo al syllabus no te dejaría, ya que no tienes los permisos para hacerlo :eyes:.

Espero haberte ayudado!
