### ISSUE TITLE
extensión autopep8

### ISSUE THREAD

**Issue by Santat4** [IIC2233/Syllabus#144]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Quería saber si estaba permitido el uso de la extensión "autopep8" en la tarea. Gracias de antemano.

**Comment by 3rdPix** [comment]
Hola @Santat4,

El paquete que mencionas no es una librería que tenga funcionalidades en la implementación de tu código como tal, solo reordena cómo escribiste el texto, por lo que no está prohibida. **SIN EMBARGO**, la responsabilidad final de ver que se cumpla correctamente los estándares que te exigimos en la tarea son exclusivamente tuyos. Es decir, que si la extensión fallase por algún motivo, no es un argumento válido decir "pero si utilice una extensión que lo hacía bien por mí", o semejantes.

Como consejo, puedes utilizarlo para revisar si algo se te pasó por alto, pero deberías intentar escribir desde un inicio tu código cumpliendo las normativas de estilo porque esto es una buena práctica que te servirá más adelante. Por último, si la utilizas, debes revisar tu código para verificar que todo esté en orden.

Saludos.
