### ISSUE TITLE
incluir en parametros

### ISSUE THREAD

**Issue by solebravo** [IIC2233/Syllabus#144]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! tenia una duda sobre lo que tengo que agregar al archivo parámetros. Se que debo agregar todas las variables del enunciado, pero mi preguntaba si es que uso una formula solo una vez en el programa esta también debe ser planteada allí o puedo definirla como variable dentro de mi función o clase.
Gracias de antemano!

**Comment by Sancauid** [comment]
Hola @solebravo! La idea del archivo parametros.py es agregar todos los parámetros mencionados en el enunciado, cualquier constante que utilices en la tarea y los paths que utilices. Si la fórmula da un valor constante, por ejemplo si sumas dos parámetros, debe ser parte de parametros.py.
