### ISSUE TITLE
error: You have not concluded your merge (MERGE_HEAD exists). hint: Please, commit your changes before merging. fatal: Exiting because of unfinished merge.

### ISSUE THREAD

**Issue by nicolettadegoye** [IIC2233/Syllabus#144]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema
Al querer hacer git pull en la carpeta syllabus, me aparece este error:

error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

cómo lo soluciono?

**Comment by ChupeteBecker** [comment]
Hola, es posible que hayas hecho cambios dentro del syllabus, como empezar la tarea desde el syllabus y no desde tu repositorio, para confirmar esto adjunta una foto de lo que dice cuando haces git status por favor.

**Comment by nicolettadegoye** [comment]
Sii, movi la T1 a mi carpeta, pensé que la había copiado😔. Cómo lo arreglo? (Estoy en la u y no traje el computador)

**Comment by ChupeteBecker** [comment]
Si haces Git status verás que te aparecen todos los cambios que hiciste y no haz subido, dentro del mensaje del git status dice que puedes hacer git restore para restaurar los cambios.

Para restaurar todos los cambios en el syllabus ejecuta el siguiente comando:

git restore .

El “.” sirve para añadir todos los archivos al git restore (también sirve para el git add) en lugar de hacerlo 1 por 1.

Para tu tranquilidad, el ejecutar este comando solo restaurará el syllabus y no la carpeta T1 de tu repositorio personal.

Una vez hayas restaurado los cambios del syllabus, deberías poder hacer git pull sin problemas.

Para futuras tareas o actividades, recuerda siempre trabajar en tu repositorio personal y no directamente en el syllabus.

Avísame si te resulta.

**Comment by nicolettadegoye** [comment]
Me resulto! gracias!
