### ISSUE TITLE
eliminar prograpost

### ISSUE THREAD

**Issue by sebastianbreguel** [IIC2233/syllabus#144]
buenas noches, en la parte del menu de prograpost cuando uno quiere eliminar un prograpost puedo preguntar tanto el prograpost que quiere eliminar y la fecha de este?, para lograr hacer la diferenciacion entre post iguales pero distintas fechas. Tambien que pasaria si por ejemplo en el mismo dia esta dos veces la misma publicacion, se deben eliminar ambas? o una solamente?.

**Comment by aljara97** [comment]
Hola @sebastianbreguel, básicamente la idea es que elimines un solo prograpost por operación. En la issue #17 se encuentra explicado con más detalles.

Suerte :bird:
