### ISSUE TITLE
Nombre de galaxia e indentificador

### ISSUE THREAD

**Issue by sahermosilla** [IIC2233/Syllabus#144]
Buenas, ocurre que en el 5.1 dice que cada galaxia tiene un identificador único, una palabra de 6 caracteres mínimo, mi consulta. ¿Esto es distinto del nombre de la galaxia, y si lo es, ese identificador de guarda en "galaxias.csv"?¿Puedo elegirlo yo?
Desde ya muchas gracias.

**Comment by leolivares** [comment]
Hola! Revisa la issue #83.
Saludos.
