### ISSUE TITLE
Acciones pendientes

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus#144]
En el enunciado en las acciones pendientes no se toma en cuenta "sacar recursos" por lo que por ejemplo, si el cpu mando a sacar oro, luego yo grabo y salgo en mi segundo turno, entonces cuando cargue en acciones pendientes no va a haber un "1, cpu, sacar oro, 1". Ya que en el enunciado dice que acciones pendientes es solamente para edificios y personas creadas.

**Comment by MartinAracena** [comment]
O ahora que lo pienso, entonces se refieren a que todas las acciones pendientes se intentan generar en el turno del jugador? Y no en el respectivo turno del cpu? 
Digamos que cpu saca oro el turno 1, el recibe el oro en MI turno 2? Y asi mismo todas las acciones de los cpu, se reciben en MI turno?

**Comment by gatochico** [comment]
Hola!
Tu duda fue discutida más a fondo en la issue #55 , pero dejame decirte que tu segunda interpretación es la correcta. Aún así, revisa la issue adjunta para resolver cualquier duda. Éxito!
