### ISSUE TITLE
Habilidades Aprendiz y Asesino

### ISSUE THREAD

**Issue by antoniomunoz9** [IIC2233/Syllabus#145]
En el enunciado se dice que las razas Aprendiz y Asesino solamente pueden usar sus habilidades cuando invaden un planeta. Entonces la única forma en que estas habilidades tengan efecto sobre alguno de mis planetas conquistados es cuando soy invadido por un Archimago. ¿Puedo hacer que estas habilidades también puedan activarse cuando las razas asesino y aprendiz están defendiendo su planeta?

**Comment by ptflores1** [comment]
Hola !
No puedes.
Saludos !
