### ISSUE TITLE
Cómo hacer overriding a un Property?

### ISSUE THREAD

**Issue by KEKGUU** [IIC2233/Syllabus#145]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Por ejemplo, si tengo una clase A con un atributo que no desciende de 0, y tengo otra clase B que hereda de A, quiero que en B, además de no bajar de 0, tampoco exceda el 100.

**Comment by mskdancers** [comment]
Hola! Todo depende de tu modelación. Puedes hacerle overriding a las properties generalmente sin problema, pero hay cosas que debes tener en cuenta. Si tienes atributos fuertemente privados **(__atributo)**, las clases hijas no podrán acceder directamente a este atributo, y en esos casos se prefiere sugerir que los atributos son privados **(_atributo)**. Te dejo [aquí](https://stackoverflow.com/questions/26318836/getting-parent-private-or-protected-values-from-the-child-class) un link con más información al respecto. Además de esto, si quieres acceder al getter de una clase padre, puedes simplemente escribir  **super().atributo**, pero ojo que acceder al setter no es tan simple como escribir **super().atributo = value** 😥. [Acá](https://gist.github.com/Susensio/979259559e2bebcd0273f1a95d7c1e79) hay más info de por qué esto no funciona y una forma alternativa de hacerlo.

En resumen, hay varias maneras de hacerlo. Puedes comentarnos si es que tienes un problema específico o si es que te quedan más dudas. Saludos!
