### ISSUE TITLE
Problema al intentar subir avance de tarea 1

### ISSUE THREAD

**Issue by JDQF** [IIC2233/Syllabus#145]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, al momento de querer subir mi avance de la tarea al repositorio remoto me sale este error: remote: Permission to IIC2233/Syllabus.git denied to JDQF.
fatal: unable to access 'https://github.com/IIC2233/Syllabus.git/': The requested URL returned error: 403
**¿Qué debo hacer para arreglarlo?**

**Comment by jorgee02** [comment]
Hola! Veo que estás intentando subir cosas al Syllabus del curso, lo que no sería apropiado. 

La idea es que clones la dirección de tu repo personal, que es al cual tienes acceso. Por lo tanto, ahí debes subir tus cosas.
