### ISSUE TITLE
Encontrar item y Ocurrencia evento

### ISSUE THREAD

**Issue by TriniAguilera** [IIC2233/Syllabus#145]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!, en la sección 3.2.1 indican que primero todos los excavadores del equipo que no están descansando van a cavar, luego hay que ver si encuentran un ítem y finalmente está la ocurrencia del evento (si ocurre o no y sus respectivos efectos). Mi duda está en, suponiendo que ocurre el evento lluvia y se transforma arena normal a mojada, ahí la probabilidad de que un excavador encuentre un ítem es 1 (tesoro o consumible equiprobable). Sin embargo, en ese día, en teoría los excavadores ya realizaron la acción de encontrar_item. No se si esa condición de lluvia y modificación en la probabilidad de encontrar un item debería verse reflejada al siguiente día (comenzaría con arena tipo mojada y recién al final podría cambiar el tipo de arena si ocurre un nuevo evento).

Estaba pensando en dejar como supuesto que el evento (en caso de que ocurra) es al comienzo del día (sería antes de cavar y que excavadores encuentren item), pero se contradice con lo que está en el enunciado en la sección 3.2.1 :(

**Comment by mtaguero** [comment]
¡Hola!

La idea es mantener el orden que mencionaste, por enunciado. Entonces, si ocurre un evento que cambie la arena, esto debe verse reflejado al día siguiente con todos los cambios correspondientes.

Si te queda alguna otra duda con respecto a esto, feliz de responder.

¡Éxito! 🎈
