### ISSUE TITLE
Como usar Jupyter?

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#145]
Hola, mi duda es más respecto a como sacarle provecho a esta herramienta. 

Es decir puedo abrir jupyter notebook y leer la materia de clases, pero hoy en ayudantía como que escribían y ejecutaban codigo desde ahí? Como se hace eso? Donde se pueden encontrar tutoriales o info respecto a esto? Que hasta ahora solo encuentro guías de como abrir y cerrarlo. 

Gracias

**Comment by entamburini** [comment]
Hola! para correr cosas en el python notebook simplemente tienes que seleccionar el bloque de código a probar y apretar el botón donde está mi puntero 
![notebook](https://user-images.githubusercontent.com/20786198/29588301-5a0fb5d6-8767-11e7-9d2a-5a5a292db78d.jpg)

Ahora, para usos más específicos (no se me ocurre mucho ahora mismo) siempre puedes buscar el uso que le quieres dar en google. Por ejemplo en [esta](http://www.randalolson.com/2012/05/12/a-short-demo-on-how-to-use-ipython-notebook-as-a-research-notebook/) página puedes ver cómo se usa en un ambiente de investigación o en esta de [aquí](http://cs231n.github.io/ipython-tutorial/), se hacen los pasos más básicos (cómo correr código y cómo crear un nuevo documento) :)

**Comment by Kitaps** [comment]
Yaaa buena gracias, 

y otra duda, si modifico algo en el Jupyter notebook, se modifica en el archivo original que esta guardado en el pc también?
