### ISSUE TITLE
Ejercicio propuesto 2.1 semana 6

### ISSUE THREAD

**Issue by Francisco-Aguilera-xd** [IIC2233/Syllabus#145]
[X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
[X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
[X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
[X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
[X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola!
Llevo harto rato pegado con este ejercicio porque no me queda muy claro como aplicar los conceptos de map/filter en este ejercicio, ya que me imaginé que podría ir comparando las letras recorriendo cada texto, pero la función filter solo recibe un iterable. Entonces traté de componer una función map con filter pero no logré llegar a nada ¿Cómo podría abordar este ejercicio?
Gracias de antemano

**Comment by tqmbanados** [comment]
Hola! No quiero darte la respuesta así tal cual, pero te daré algunas pistas que podrían ayudarte:
1. Recuerda que la función `map` puede trabajar sobre dos iterables simultáneamente. Por ejemplo:
    ```python
    mapeo = map(lambda x, y: x + y, range(0, 21), range(20, -1, -1))
    ```
    Lo anterior genera un mapeo que en cada iteración retorna... 21
2. A mi me resultó mejor usar primero `map`, y luego `filter` sobre los mapeos.
3. No tienes llamar cada función sólo una vez, puedes llamarlas más de una vez. (Por ejemplo, una por cada par de textos...)

Cuéntame si con esos tips logras resolver el ejercicio!

**Comment by Francisco-Aguilera-xd** [comment]
Ahí si me resultó :). Muchas graciassss

**Comment by tqmbanados** [comment]
Me alegro!
