### ISSUE TITLE
Problema al abrir archivo.txt

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2233/syllabus#145]
Hola, tengo problemas para abrir el "puntajes.txt" en mi main.py, siendo que estos 2 están en la misma carpeta en mi repositorio personal.
Es lo único que no logro abrir de todos los archivos, y la verdad no sé que parte de mi código está mal.
Gracias de antemano!

**Comment by jirarrazaval** [comment]
Hola! Probablemente te aparece FileNotFound error.
En tu editor de texto tienes que estar dentro de la carpeta de la tarea!
Por ejemplo, si estás editando con VSCode, apreta file - open folder - y la carpeta de la tarea.
Ojalá te sirva!

**Comment by pabloalvarez67** [comment]
Eso estoy haciendo, ejecutando todo dentro de la misma carpeta!
como dije antes, puedo importar por ejemplo parametros.py y también tablero.py, pero no me deja abrir el puntajes.txt, nose porque.
ejecutando cuando quiero
archivo = open("puntajes.txt", 'rt')
            lineas = archivo.readlines()
            print(lineas)
me tira exactmente el error que me dijistes tu, no encuentra el archivo

**Comment by jirarrazaval** [comment]
Probé lo que me pusiste y funciona!
Estás seguro que apretaste file - *open folder* - ?

**Comment by pabloalvarez67** [comment]
Ahora si! no te habia cachado bien a que te referías con lo de open folder, muchas gracias!!

**Comment by jirarrazaval** [comment]
Buenísimo! Éxito con la tarea :)
