### ISSUE TITLE
al crear grupos debo agregar automaticamente al usuario que lo crea?

### ISSUE THREAD

**Issue by BenjaRubio** [IIC2233/syllabus#145]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Al crear un grupo, ¿el usuario que lo crea debe ser agregado automaticamente, o para agregarlo debe escribirse como uno más de los integrantes?
De agregarse automaticamente, al ingresar los integrantes de la forma: usuario1;usuario2;....  ¿bastaría con ingresar un solo usuario acá para que el grupo sea válido?
gracias!

**Comment by aljara97** [comment]
Hola @BenjaRubio, si bien no se especifica en el enunciado, es recomendable que se agregue al creador del grupo al grupo que creó, para poder comprobar esta funcionalidad. Además, como se menciona en la issue #102, queda a tu criterio cómo utilizar el input (incluir al usuario en sesión entre los usuarios a agregar o que se agregue por defecto), mientras te asegures de verificar los otros requisitos.

Te aconsejo especificar esto en tu README y citar esta issue, saludos y mucho éxito en tu tarea :)
