### ISSUE TITLE
atributos contrincantes

### ISSUE THREAD

**Issue by solebravo** [IIC2233/Syllabus#145]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, mientras revisaba el flujo del juego me entro una duda sobre la variación de los atributos de mi programon vs los de los contrincante. Por lo que entiendo uno realiza acciones sobre su propio programon que te permiten incrementar tus atributos como la vida, ataque, etc, pero en el caso de los contrincantes sus números siempre serán estáticos? y si no es así que acciones los afectan?
Gracias de antemano!

**Comment by Amandasandov** [comment]
Hola, efectivamente los atributos de los programones contrincantes se mantienen estáticos durante el campeonato. Suerte.

**Comment by gabo1243** [comment]
Hola, con respecto a esa duda, en el enunciado dice que cada tipo de programon tendrá un aumento de una estadística cuando gana una batalla (por ejemplo, si planta gana se le aumenta la vida). Sobre esto ¿Aplica para solo los programones del jugador o tambien para el resto de entrenadores?
Gracias de antemano

**Comment by Amandasandov** [comment]
Hola, el beneficio de ganar la batalla se le asigna a todos los programones que compitan. Suerte.
