### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#145]
Hola!
¿Qué significa esto: "Uso de espacios para indentación y no de tabulaciones."?
Gracias!

**Comment by Dnpoblete** [comment]
Hola @Camila-sty , esto se refiere a que no utilices el botón tab (el que tiene dos fechas opuestas) para indentar, ya que en pep8 se pide utilizar 4 espacios y puede ser que tu botón tab este configurado con una cantidad diferente de espacios. Esto se puede configurar según el programa que uses, pero siempre es más recomendable asegurarse y usar los espacios en vez de tab.

Espero haber aclarado tu duda, si no fue así avisame para poder ayudarte.

Éxito con la tarea! :smile:

**Comment by CamilaArgomedo** [comment]
si mi tab tiene 4 espacios es necesario igual escribir con 4 espacios?

**Comment by Dnpoblete** [comment]
Si esta configurado con 4 espacios no debería haber problema. Si ya lo hiciste con el tab configurado, revisa que de verdad sean 4 espacios, pero lo mejor sería que de ahora en adelante uses 4 espacios y te acostumbres, ya que si por abc motivo se desconfigura (y no es fácil darse cuenta) tendrás el descuento asociado en la tarea sin derecho a reclamo. 

Éxito con la tarea! :smile:

**Comment by CamilaArgomedo** [comment]
gracias!

**Comment by Dnpoblete** [comment]
De nada ☺️
