### ISSUE TITLE
Avance de la infeccion

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2233/Syllabus#145]
El enunciado dice: "Cada dıa una persona infectada puede contagiar entre 0 y 6 personas, con una distribucion uniforme discreta. El numero de personas infectadas se multiplica por 0,3 si el gobierno ha repartido mascarillas, y por la tasa de contagiosidad correspondiente al tipo de infeccion."

Esto significa por ejemplo que si el gobierno reparte mascarillas y un dia X se infectan 4 personas, tengo que multiplicar ese numero por 0,3? Y si la respuesta es si, que pasa si no obtenemos un numero entero? Redondeamos, tomamos la parte entera o queda a nuestro juicio?

**Comment by FernandoPieressa** [comment]
Exacto, multiplicas por 0,3 y si es un numero no entero queda a su criterio si redondeas u otra cosa, pero no puede quedar una cantidad no entera.

Saludos!
