### ISSUE TITLE
Problema al leer archivos

### ISSUE THREAD

**Issue by fcsanchez** [IIC2233/syllabus#145]
Hola! He estado trabajando en la parte de leer/modificar información de los archivos '.csv' y me ha pasado varias veces que al momento de leer la primera fila del archivo se agregan unos caracteres de esta forma:

['Nombre', 'Dinero', 'Personalidad', 'Contextura', 'Equilibrio', 'Experiencia', 'Equipo']

['\ufeffNombre', 'Dinero', 'Personalidad', 'Contextura', 'Equilibrio', 'Experiencia', 'Equipo']

sin embargo cuando abro el archivo con bloc de notas no aparecen estos, aparece normal. 

El problema no se debe a posteriores modificaciones en modo 'a' o 'w', ya que a veces a la primera lectura ocurre esto, como también después de modificar varias veces el archivo. Siempre abro el archivo con bloc de notas. 

Alguna idea de como solucionar esto?
Gracias

**Comment by RositaMunoz** [comment]
Hola!
Primero que todo, estás utilizando algún _encoding_ al momento de leer el archivo .csv?
Si es así, que _encoding_ estás utilizando? 
Muchas veces (la gran gran mayoría) hay que especificarle a la función ``open()`` de qué forma tiene que decodificar el archivo que le estamos pasando. El _encoding_ que necesitan los caracteres como "á" o 'ñ', es el 'utf-8', si especificas esto en la función ``open()`` te ahorrarás muuchos problemas de caracteres extraños.
De todas formas cuéntame como te va.

Éxito y ánimo con la tarea ^^

**Comment by fcsanchez** [comment]
Hola, si estoy usando encoding="utf-8"

**Comment by RositaMunoz** [comment]
Buscando tu problema encontré esto https://stackoverflow.com/questions/17912307/u-ufeff-in-python-string 
Efectivamente es el string '\ufeff' es un indicador para el _encoding_ 'utf-8' prueba utilizando 'utf-8-sig' y cuéntame que tal :0

**Comment by RositaMunoz** [comment]
Hola! estuvimos hablando de tu problema con @jmwielandt y llegamos a una mejor solución, abre el archivo en tu bloc de notas, ir a Archivo>Guardar Como y guardar con el _encoding_ UTF8 sin BOM de esta forma:
![imagen](https://user-images.githubusercontent.com/48262755/64269253-9602d700-cf07-11e9-884c-4b07de48469c.png)

Espero te ayude y así no ocupas el _encoding_ utf-8-sig, solo ocupas utf8

**Comment by fcsanchez** [comment]
Hola, los archivos ya estaban guardados con esa codificación, de todas maneras he estado usando el encoding  'utf-8-sig' y no ha vuelto a surgir el error. Gracias!! :D
