### ISSUE TITLE
civilizaciones.csv

### ISSUE THREAD

**Issue by cambrinKD** [IIC2233/syllabus#145]
Cuando guardas el archivo "civilizaciones.csv", deberias guardarlo en el mismo formato que antes no? Entonces, que pasa cuando lo cargas. Por ejemplo antes de guardar tengo 10 trabajadores, cada uno con un HP diferente. Despues de guardar ya tengo 10 trabajadores sin atributos, y cuando cargo mi juego de nuevo voy a necesitar que creerles de nuevo. Esta bien? Espero que tiene sentido

**Comment by jmwielandt** [comment]
Si por atributos te refieres al HP, la fuerza de los soldados y el IQ de los ayudantes, esto se responde en  #54 
Te recuerdo que deben revisar si lo que quieren preguntar ya fue contestado.

Saludos y mucho éxito~
