### ISSUE TITLE
Generar mas excavadores de los que aparecen en el archivo excavadores.csv

### ISSUE THREAD

**Issue by AntonioEscobar01** [IIC2233/Syllabus#146]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### ¿Puedo generar más de un excavador con la misma info entregada en excavadores.csv?

En algun punto del juego puede darse el caso de que se intente generar más jugadores de los que existen en el archivo o bien, requiero crear otro jugador de un cierto tipo (por ejemplo un excavador hibrido) y todos los excavadores de este tipo dentro del archivo ya han sido creados y forman parte del equipo.

Al no estar esta limitacion explicada en el enunciado, cabe la duda si hay un limite de excavadores que pueden estar en tu equipo o bien se puede reutilizar la informacion de los excavadores entregada.

**Comment by mpiavf** [comment]
Hola! En el caso de que se necesiten más jugadores de los que existen en el archivo `excavadores.csv` se puede elegir entre dos opciones:
1) Se advierte en consola que el tesoro no funciona ya que no existen más excavadores disponibles
2) Se repiten excavadores
Queda a tu criterio cual opción escoger. 
No se pueden inventar nuevos excavadores.
Saludos!

**Comment by Fopazov** [comment]
Holaa! Pregunta para verificar. Que "se repitan excavadores", ¿significa que se pueden tener excavadores repetidos ANTES de tener el número total de excavadores distintos (8 excavadores distintos en archivo de excavadores)? Por ejemplo, se podría tener dos excavadores "Beyoncé" en tu equipo si se tienen 4 excavadores en él?

**Comment by mpiavf** [comment]
Hola! Como no está especificado en el enunciado queda a tu criterio si ese caso es válido o no. Eso sí, debes especificar lo que decidas en tu README como un supuesto.
Saludos!
