### ISSUE TITLE
Habilidad de raza asesino

### ISSUE THREAD

**Issue by bmorrisc** [IIC2233/Syllabus#146]
Hola! En el enunciado  dice respecto a la habilidad de esta raza

>Sólo la pueden ocupar cuando invaden un planeta y en cada ataque hay un 40% de probabilidad de realizar el doble de daño. Por ejemplo, si durante la invasión de los Asesinos a otro planeta, los soldados tienen 3 intentos y estos hacen en total un daño de 40, en cada intento hay un 30% de hacer 80 de daño.

Mi pregunta es... dejamos la probabilidad en 40%? 
Asumo que debe ser error de tipeo en el ejemplo, pero de todas formas quería confirmar

**Comment by leolivares** [comment]
Hola! Revisa la issue #32.

**Comment by bmorrisc** [comment]
gracias! :)
