### ISSUE TITLE
AC2 def __next__ no me está retornando en el orden correcto

### ISSUE THREAD

**Issue by angedvq** [IIC2233/Syllabus#146]
Holaaa, estoy en la ultima parte de la A2 y siempre me devuelve los mismos fails que no encuentro como solucionarlos :P 

FAIL: test_IteradorDCCMax_next_2 (__main__.TestIterables)
Se comprueba que el IteradorDCCMax entrega las películas en el orden esperado.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/sarai/Documents/PUC/Programación Avanzada/GitHub/angedvq-iic2233-2023-2/Actividades/AC2/test.py", line 876, in test_IteradorDCCMax_next_2
    self.assertSequenceEqual(pelicula_next, pelicula_ordenado)
AssertionError: Sequences differ: Pelicula(id_pelicula=10, titulo='Forrest Gump', director='Rober[33 chars]=8.8) != Pelicula(id_pelicula=1, titulo='The Shawshank Redemption', dire[43 chars]=9.3)

First differing element 0:
10
1

- Pelicula(id_pelicula=10, titulo='Forrest Gump', director='Robert Zemeckis', estreno=1994, rating=8.8)
+ Pelicula(id_pelicula=1, titulo='The Shawshank Redemption', director='Frank Darabont', estreno=1994, rating=9.3)

======================================================================
FAIL: test_IteradorDCCMax_next_3 (__main__.TestIterables)
Se comprueba que el IteradorDCCMax entrega las películas en el orden esperado.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/sarai/Documents/PUC/Programación Avanzada/GitHub/angedvq-iic2233-2023-2/Actividades/AC2/test.py", line 896, in test_IteradorDCCMax_next_3
    self.assertSequenceEqual(pelicula_next, pelicula_ordenado)
AssertionError: Sequences differ: Pelicula(id_pelicula=16, titulo='Interstellar', director='Chris[35 chars]=8.6) != Pelicula(id_pelicula=17, titulo='Gone with the Wind', director=[38 chars]=8.1)

First differing element 0:
16
17

- Pelicula(id_pelicula=16, titulo='Interstellar', director='Christopher Nolan', estreno=2014, rating=8.6)
+ Pelicula(id_pelicula=17, titulo='Gone with the Wind', director='Victor Fleming', estreno=1939, rating=8.1)

======================================================================
FAIL: test_IteradorDCCMax_next_4 (__main__.TestIterables)
Se comprueba que el IteradorDCCMax entrega las películas en el orden esperado.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/sarai/Documents/PUC/Programación Avanzada/GitHub/angedvq-iic2233-2023-2/Actividades/AC2/test.py", line 916, in test_IteradorDCCMax_next_4
    self.assertSequenceEqual(pelicula_next, pelicula_ordenado)
AssertionError: Sequences differ: Pelicula(id_pelicula=5, titulo='Fight Club', director='David F[29 chars]=8.8) != Pelicula(id_pelicula=8, titulo='Goodfellas', director='Martin [31 chars]=8.9)

First differing element 0:
5
8

- Pelicula(id_pelicula=5, titulo='Fight Club', director='David Fincher', estreno=1999, rating=8.8)
?                      ^          ^^^^^^^ ^^             ^ ^^^^^   ^ ^              ^           ^

+ Pelicula(id_pelicula=8, titulo='Goodfellas', director='Martin Scorsese', estreno=1990, rating=8.9)
?                      ^          ^^^^^^ ^^^             ^ ^^  ++ ^^^ ^^              ^           ^

----------------------------------------------------------------------
Ran 35 tests in 0.215s
![Screenshot_18](https://github.com/IIC2233/Syllabus/assets/107944069/c071d2b0-42ad-455b-8b28-898fe95850e2)

**Comment by Arielmanriquez** [comment]
Por la forma en la que se desordenan, puede ser que el id_pelicula sea un string?. Fuera de eso no veo un problema en los metodos que mencionaste

**Comment by jrodriguezluna** [comment]
Tengo el mismo problema (hice algo muy parecido), como que el sort no hace efecto ;;

**Comment by Utmite** [comment]
Los estas ordenando mal
