### ISSUE TITLE
¿Qué es modularización? 

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#146]
Hola!
Cuando mencionan los "módulos que fueron creados", se refieren a los archivos.py que creamos para escribir nuestro código?

**Comment by aljara97** [comment]
Hola @Camila-sty cuando nos referimos a los módulos creados, nos referimos a los distintos archivos de python que fueron creados para separar tu código. Recuerda que es una buena práctica escribir en distintos archivos de python funciones o clases que tengan algún comportamiento común o se relacionen a un mismo tipo de actividad. Por ejemplo, en esta tarea se podría crear un archivo ```usuario.py``` que contenga una clase Usuario y funciones relacionadas con el manejo de este, o un módulo "archivos.py" que contenga funciones relacionadas a la apertura y escritura de archivos csv. Esto es importante para tener un código más ordenado y con menos líneas por módulo.

Éxito :bird:
