### ISSUE TITLE
Mismo puntaje en Ranking.

### ISSUE THREAD

**Issue by caroizquierdo** [IIC2233/syllabus#146]
me explico con este ejemplo
1) misi99   120 Pts
2) sushi   36 Pts
3) mario   34 Pts
4) mario   34 Pts
5) 0pitu0   0 Pts

Se puede? los de 3) y4)?

**Comment by vicentevegaulloa** [comment]
Hola @caroizquierdo !

Si se puede, por lo que el ejemplo que pusiste estaría correcto.

**Comment by vicentevegaulloa** [comment]
@caroizquierdo podrías escribir la pregunta completa en el comentario. Cambié el titulo de la issue para que se entendiera mejor. EL titulo anterior debería ir en la descripción.

**Comment by sa-Appel** [comment]
en caso de tener 2 puntajes que se repiten para el ultimo lugar o + .
por ejemplo:

misi99 120 Pts
sushi 36 Pts
mario 34 Pts
mario 34 Pts
0pitu0 7 Pts
Juan 7pts
Pedro 7 pts

y distintas variables que pueden tener, como selecciono el top 5? por orden alfabetico de el apado, o menciono todos aquellos que cumplan con el puntaje, para todos los lugares.

**Comment by sa-Appel** [comment]
@vicentevegaulloa puedo entonces, por ejemplo, dejar a los 5 primeros aunque estos tengan todos el mismo puntaje?

**Comment by vicentevegaulloa** [comment]
@sa-Appel si, siempre y cuando estos sean efectivamente los mejores.
