### ISSUE TITLE
Civilización Enemiga

### ISSUE THREAD

**Issue by isihirmas** [IIC2233/syllabus#146]
Hola!
Cuando el usuario elige su civilización, quedan otras dos civilizaciones disponibles. Esto significa que jugaré contra alguna de las dos al azar o necesariamente las dos quedan automáticamente como civilizaciones enemigas y ambas me pueden atacar?
Si es el segundo caso, en qué se basa quién ataca primero y a quién? Porque en el archivo acciones aparece esto:
21,1,Atacar civilización,2
Ese 2 sería el id de a quién está atacando?

Muchas gracias!

**Comment by iqacevedo** [comment]
Hola ! 
Estas preguntas se han respondido en otras issues. Porfavor revisa todas las issues antes de preguntar. Cuando escoges una juegas contra las otras dos, las acciones de las otras se definen por lo indicado en acciones.csv y el orden de acciones es primero jugador, después el orden en que salen las acciones en el archivo.

Saludos !
