### ISSUE TITLE
Daño al vehiculo

### ISSUE THREAD

**Issue by anvaldes** [IIC2233/syllabus#146]
El daño al vehiculo solo se debe tener en cuenta en pistas rocosas?

**Comment by anvaldes** [comment]
Y otra consulta, en la formula del daño al vehículo, no sería mas intuitivo que fuera minimo en vez de maximo?

**Comment by entamburini** [comment]
Hola @anvaldes, 

Te recuerdo que las reglas del foro dicen que no hagas preguntas repetidas ([la primera pregunta es la misma que esta](https://github.com/IIC2233/syllabus/issues/154))

La razón de por qué no fue respondida la issue es porque preguntaste dos veces lo mismo (duplicado de #154) y después nadie vio lo que preguntaste posteriormente :/ 

Más atento para la otra! :wink:
