### ISSUE TITLE
Duda sobre Aplicar Objeto en el Caramelo

### ISSUE THREAD

**Issue by reteuber** [IIC2233/Syllabus#146]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! En el inciso 4.4.1 del enunciado, definiendo el método "aplicar objeto" para Caramelo, sale "Los efectos que se aplican son tanto los de Baya como los de Poción". En ese caso se refiere al aumento de vida de la Baya, al aumento de ataque de la Pocion y también a los gastos de energía respectivos de cada uno? Además, también incluye el cálculo de probabilidad de cada uno? O solamente aumento de vida, ataque y gasto energético. O solo el aumento de los atributos?? No entiendo bien cuáles serían los efectos de Baya y Poción que también corren para Caramelo y cuáles no

**Comment by Amandasandov** [comment]
Hola, cuando se consume un objeto Caramelo, se aplican al aumento de la vida de la Baya y al aumento de ataque de la Poción, pero no sus gastos de energía ni sus probabilidades respectivas, ya que Craamelo tiene su propio gasto de energía y probabilidad asociada.

**Comment by reteuber** [comment]
perfect, muchas gracias :)
