### ISSUE TITLE
parametros

### ISSUE THREAD

**Issue by pascal1003** [IIC2233/syllabus#146]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] 
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo dudas sobre el archivo de parametros,
En primer lugar hay que editarlo o se tiene que dejar como esta.
Lo segundo es que si es necesario importarlos al archivo donde se esta corriendo el programa ( y en caso de que sea se importan igual que funciones?) o puedo poner algo así : 
![Captura de pantalla 2021-03-30 a las 8 14 45 p m](https://user-images.githubusercontent.com/80788210/113075805-105b1200-91a4-11eb-97e1-155e2f5116e1.png)

**Comment by matiasmasjuan** [comment]
Hola @pascal1003 !

Responderé las preguntas en orden:

1. No es necesario editarlo, pero al final no debería importar ya que lo que se guarda en el archivo es la **variable** ***VOLVER_FRASE***, el cual es importado. Si se cambia el valor, entonces ese sería el *input* a ingresar para volver al menú anterior.

2. **Sí**, deben importarlos. Te aconsejo revisar la ***issue*** #133 . En el ejemplo que mencionas sería una forma **incorrecta** de hacerla, ya que no se trata de usar el *string* "VOLVER_FRASE", sino de usar la **variable** ***VOLVER_FRASE*** que se encuentra definida en el archivo ```parametros.py```.

Saludos! :smile:
