### ISSUE TITLE
que pasa cuando uno se hace investor con las ordenes pasadas

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#146]
si uno se hace investor que pasa con las ordenes que fueron hechas como trader. pasan a ser de tipo "investor"?. lo pregunto para el momento que ocurre que 2 orders tienen el mismo price

**Comment by sebacruzd** [comment]
Hola,
No está especificado en el enunciado, por lo que puedes elegir qué hacer. Que esté en tu README.md para que quien te corrija lo sepa.

Saludos!
