### ISSUE TITLE
Ataque constante en Guerra(duda sobre issue 112)

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#147]
Mi duda es si para cada turno en ataque debe disminuir el ataque debido a que a disminuido el numero de soldados, en la issue 112 se señala que el numero de soldados solo se calcula al final pero esto me parece raro, de ser así, en cada turno el ataque es constante o debe ser calculado nuevamente pero con la cantidad de soldados inicial

**Comment by IchottMano** [comment]
@ljrodriguez1 Hola!
Efectivamente, aunque parezca raro, los soldados no "mueren" sino hasta que termina la batalla, esto es para facilitar la tarea un poco.
Saludos!
