### ISSUE TITLE
citar función de librería prohibida

### ISSUE THREAD

**Issue by santiago3c** [IIC2233/Syllabus#147]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, que estaba viendo cómo resolver una parte de la tarea y quería usar una función que es de una de las librerías que no se puede usar, pero en internet hay una parecida hecha a "mano", entonces si se puede copiar esa función en mi código y citarla o no se puede hacer eso

**Comment by Arielmanriquez** [comment]
Buenos dias, esta pregunta deberias hacerla en la misma issue #55 . La voy a cerrar para mantener el orden de las issues
