### ISSUE TITLE
Probabilidad de Contagio

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2233/Syllabus#147]
En el enunciado aparece la formula para calcular la probabilidad de que pais contagie a otro, pero cuanta gente en el pais de llegada se contagiara si el contagio ocurre? 
Si dos paises conectados estan ambos contagiados debemos seguir considerando esta probabilidad, ya que seria otra manera de que se sigan contagiando personas?

**Comment by arturodelreal** [comment]
Hola, se contagia a una persona del país de llegada.
Lo segundo queda a tu criterio, pero el efecto de esto es casi nulo considerando que solo se contagia a una persona al día.
