### ISSUE TITLE
Posible Empate si todas las civilizaciones atacan en mismo turno

### ISSUE THREAD

**Issue by quememo** [IIC2233/syllabus#147]
### Es posible que haya un empate si todas las civilizaciones atacan a otra en el mismo turno?

- Civilizacion A ataca a Civ B y tiene el poder para destruirla completamente **(Pa>=Pd)**
- Civilizacion B ataca a Civ C y tiene el poder para destruirla completamente **(Pa>=Pd)**
- Civilizacion C ataca a Civ A y tiene el poder para destruirla completamente **(Pa>=Pd)**

En este caso, todas las civilizaciones resultarían eliminadas a la vez y habría un empate?
Cabe mencionar que por mandar sus soldados a atacar, cada civilización tendría un Pd menor, por lo que siento que este caso podría ocurrir.

**Comment by DCCollao** [comment]
Hola, revisa #112 

__Recuerda leer las issues anteriores, esta pregunta ya se respondió antes. Si tienen más dudas del mismo tema, haganla en esa issue para mantener el mismo hilo y no tener diferentes issues sobre el mismo tema.__
