### ISSUE TITLE
Bombas especiales: Verificación de coordenadas

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2233/syllabus#147]
Hola! 
En el caso de las bombas especiales, al revisar la validez de las coordenadas, se debe revisar que en todos los lugares donde caerá la bomba (dependiendo del radio de expansión) no haya una celda descubierta antes o solo el centro de la bomba? ( es decir la coordenada donde te indican que debe caer, sin incluir las celdas extras en las que caerá por ser una bomba especial).

**Comment by kadroguett** [comment]
Hola @antoniaalcayaga 
Si bien no se especifica en el enunciado, solo deben verificar que la posición de origen sea una celda no descubierta. En el caso de que la bomba incluya posiciones descubiertas estas simplemente se ignoran.

**Comment by YehudaGurovich** [comment]
Justo me estaba preguntando eso. No se puede tirar la bomba especial en una posición descubierta? Pq puede ser que sea mejor para el jugador tirarla en una posicion descubierta para optimizar las coordenadas a descubrir.

**Comment by kadroguett** [comment]
Hola @YehudaGurovich, solo se puede lanzar en una posición no descubierta.
