### ISSUE TITLE
Nombre pista

### ISSUE THREAD

**Issue by Dafnemami** [IIC2233/syllabus#147]
Hola!, en la parte de entidades dice que pista tiene un nombre y un tipo. Es el usuario quién debe asignarle un nombre o el nombre coincide con el tipo de pista (y por ende se asigna por el juego)??

**Comment by gatochico** [comment]
Hola! 
En el archivo `pistas.csv` se encuentran los nombres de las pistas, que son diferentes al tipo de la pista.

Saludos! :car:
