### ISSUE TITLE
Duda sobre máximo de líneas en el archivo principal

### ISSUE THREAD

**Issue by gabo1243** [IIC2233/Syllabus#147]
### Duda

Hola, estuve revisando la pauta en Avanzada.app y encontré que había un descuento de 5 dec si un archivo excedía las 400 líneas de código. Si mi archivo con el código principal excede esta cantidad de líneas, ¿Puedo separarlo en varios archivos? (por ejemplo que cada uno contenga una clase).
Gracias de antemano

**Comment by Amandasandov** [comment]
Hola, efectivamente lo que se espera es que separen sus programas en módulos que se importen entre si para evitar generar archivos que superen las 400 lineas. Suerte.
