### ISSUE TITLE
Duda restriccion registro ";"

### ISSUE THREAD

**Issue by jervaal** [IIC2233/syllabus#147]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda ###

Hola!, me surgió una duda sobre las restricciones al momento de crear un nombre de usuario.

Además de las restricciones dadas en el enunciado de la tarea, me di cuenta que si, hay un nombre de usuario en el que contenga ";" (punto y coma), habrían problemas al momento de querer agregar este usuario a un grupo en la opción de crear grupo. ¿Ponemos esta restricción o queda a nuestro criterio?

de antemano muchas gracias!

**Comment by tqmbanados** [comment]
Hola! Efectivamente, un usuario con ";" en su nombre puede causar problemas para el programa, al menos que realices un trabajo extensivo que sortee las complicaciones. Esto no es parte de lo pedido, por lo que es sensato que incluyas la restricción. Gracias por notificarlo!

**Comment by tqmbanados** [comment]
Denada! Suerte en la tarea 😸
