### ISSUE TITLE
Duda clases

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#147]
Si tengo la clase "padre" Vehiculo y dos clases "hijas" auto y moto. La moto tiene dos ruedas, el auto tiene 4 ruedas. Existe alguna forma de:
a = Vehiculo(4)
b = Vehiculo(2)
que poniendo esos determinados atributos hacer que sean objetos del tipo auto, moto respectivamente de forma automática?

**Comment by fringlesinthestreet** [comment]
@movaldivia Sí existe pero se verá más adelante en el curso. 

A esta altura mejor realiza la instanciación de manera directa con la clase hija.

**Comment by movaldivia** [comment]
@fringlesinthestreet oka
