### ISSUE TITLE
Readme.MD

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#147]
Hola!
No entiendo dónde debo escribir el readme, qué archivo debo abrir y dónde está..?
Gracias!

**Comment by matiasmasjuan** [comment]
Hola @Camila-sty !
El **Readme.MD** es como un archivo de texto, pero que a diferencia de él, está en formato [MarkDown](https://es.wikipedia.org/wiki/Markdown). Esto quiere decir de que tiene una variedad de estilos de textos distintos que facilitan la lectura además de darle un diseño agradable al lector.
Actualmente, hay un **Readme.MD** que te puede servir de **guía** para la elaboración del **readme** de tu tarea. Esta se encuentra ubicada en **Syllabus/Tareas**. Puedes copiar y pegar ese archivo a la carpeta en la cual estas haciendo tu tarea (**/T00**). Luego debes **editarla** desde allí y **subirla** a tu repositorio.
Para **editarla**, puedes abrirla en un bloc de notas por ejemplo. Sin embargo, **recomendamos fuertemente** utilizar un editor de texto (como **VSCode**) ya que facilita su escritura.
Suerte!
