### ISSUE TITLE
Duda comando tarea 1

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#148]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holaa, vi en una issue algo al respecto, pero no me quedó claro. ¿Se puede usar break? y si es que sí se puede ¿Se descontará puntaje por utilizarlo?

**Comment by FernandoTFH** [comment]
Si, puedes usarlo. No hay descuento por usarlo.

**Comment by martinpint** [comment]
Y con el comando continue pasa lo mismo, ¿no se descontará puntaje por utilizarlo?

**Comment by FernandoTFH** [comment]
Debí haberte mandado a esta issue #52 desde el comienzo.

**Comment by martinpint** [comment]
Perdón la insistencia, ¿pero con continue tampoco se descontará puntaje, cierto?

**Comment by FernandoTFH** [comment]
Si, no habrá descuento por usar continue.
