### ISSUE TITLE
Setear valores de los parámetros

### ISSUE THREAD

**Issue by crow-rojas** [IIC2233/syllabus#148]
Hola, estuve leyendo issues anteriores pero no me quedó claro para responder mi pregunta. Por ejemplo, para los valores MIN y MAX del chasis de un automóvil, yo tengo que establecer esos valores? Y así sigue para cualquier parámetro que en el enunciado no estén dicho los valores explícitamente? (por ejemplo las demás partes de un vehículo) 

Y no así para valores establecidos como los de contextura, que ahí serían el MIN y MAX dados en el enunciado, no? 

Gracias!

**Comment by gatochico** [comment]
Hola!

Estás en lo correcto: tienes absoluta libertad para rellenar cualquier parámetro cuyo valor no se explicite en el enunciado con los valores que tu quieras. Incluso, puedes agregar parámetros nuevos si sientes que falta alguno. Recuerda también que para esta tarea `parametros.py` debe subirse.

Espero haber respondido tu duda! :racing_car:

**Comment by crow-rojas** [comment]
Gracias @gatochico! Entendí perfe!
