### ISSUE TITLE
Formato archivo acciones

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#148]
Hola se puede asumir que cada civilizacion realiza a lo más 1 acción por turno (dado el formato del archivo acciones)  o es necesario generalizarlo. Gracias

**Comment by hbkim94** [comment]
Hola!

Solo las civilizaciones enemigas se rigen por 1 acción por turno. El jugador debería poder realizar cuantas acciones los recursos que tiene a su disposición le permitan (exceptuando atacar, que es solo una vez por turno).

Ánimo en lo poco que queda!

**Comment by bvallejo1** [comment]
Hola, pero el acciones.csv lo dan para probar con 3 "computadoras"? no debería estar jugando el usuario y corriendo el archivo acciones. csv?

**Comment by hbkim94** [comment]
Hola @bvallejo1 !

En efecto, en el archivo se cuentran las acciones "default" para las tres civilizaciones. Sin embargo, las acciones de la civilización que el jugador eligió no se deben tomar en cuenta (porque la estamos manejando nosostroas), solo las de las civilizaciones enemigas.

Espero haber resuelto tu duda!

**Comment by jitorcas** [comment]
Con respecto a lo mismo, ¿mi código debe llamar al archivo "acciones.csv" para que el usuario tenga rivales o las acciones rivales serán ingresadas por la interacción con consola? 


En el caso que el usuario elija la civilización DCC (considerando que DCC tendrá id = 0) pasaría (1) o (2) ?

**(1) archivo "acciones.csv":**

# le pregunto al usuario que quiere hacer 
1,1,Recolectar recurso,oro;2
1,2,Recolectar recurso,madera;2

**(2) archivo "acciones.csv":**

1,0,Recolectar recurso,oro;2 # como tiene el id de la civilización que escogió no lo considero para correr el programa y le pregunto al usuario que quiere hacer 
1,1,Recolectar recurso,oro;2
1,2,Recolectar recurso,madera;2


con respecto a "no importa el id de las civilizaciones enemigas" eso no está dado en concreto por el archivos "civilizaciones.csv" ? ya que sí importa que civilización ejecuta las acciones dentro de "acciones.csv" porque cada una tiene poderes distintos y correrían diferente a lo esperado por la persona que corrija.

**Comment by hbkim94** [comment]
Hola @jitorcas! 

Respecto a lo primero, y si es que entendí bien tu duda (no veo la major diferencia entre el caso 1 y 2), tu código debe llamar al archivo y ejecutar las acciones de las civilizaciones enemigas al término del turno del jugador automáticamente. Supongo que esta opción alude al caso 1.

Respecto a lo srgundo, lo siento! Redacté incorrectamente lo que quería decir. A lo que realmente me refería es que los id no van a estar necesariamente en orden secuencial. Editaré mi comentario de inmediato!

Saludos!
