### ISSUE TITLE
Vs code error line too long

### ISSUE THREAD

**Issue by fcbahamondes** [IIC2233/syllabus#148]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola! Mi vs code esta configurado para indicar un error cuando la linea tiene mas de 79 caracteres. Queria saber si eso se puede editar y como? busque en internet pero nada funciono

**Comment by cristobalnic** [comment]
Hola @fcbahamondes! 

Antes que buscar otra solución, te voy a dejar aquí la issue #31 en que está explicado cómo configurar el linter pycodestyle; que debería ser el que tienes instalado; para que te indique sólo cuando se sobrepasa el máximo 100 en vez de 79.

Saludos!

**Comment by fcbahamondes** [comment]
Si me funciono, muchas gracias!!
