### ISSUE TITLE
¿Cuáles son las condiciones para citar código encontrado en internet?

### ISSUE THREAD

**Issue by NikiHV** [IIC2233/syllabus#148]
Hola!
No sé hasta qué punto tengo que ser estricta para citar código encontrado en internet. 
Pongo diferentes escenarios.

Leyendo páginas web (por ejemplo, respuestas en _stackoverflow_):
1. Encuentro un párrafo de código que me sirve para hacer algo y lo copio textual en mi tarea.
2. Encuentro varias líneas de código que me sirven, las ocupo en mi tarea para el mismo propósito que aparece en internet, pero no exactamente de la misma forma (sería como el parafraseo de un párrafo).
3. Encuentro un método de python que luego ocupo en mi código, implementándolo para el mismo propósito que aparece en internet, pero no exactamente de la misma forma (sería como un parafraseo, pero de una línea).
4. Encuentro un método que no conocía, lo ocupo en mi tarea, pero de forma distinta y con propósito diferente al de la respuesta de internet.

¿En cuál de estos casos es necesario citar la página web, y en cuáles no?

P.D: Para mí el 1. es obvio que hay que citarlo, el 2. y 3. no tengo idea, y el 4. creo que no sería necesario, pero me gustaría confirmación :)

**Comment by gatochico** [comment]
Hola! Vamos en orden:

1. Sí se debe citar.

2 - 3. Va dependiendo de qué tan específico es ese código usado. Si de donde lo recuperaste es una implementación muy específica de un usuario, que resuelve un problema muy específico (en general estos casos se ven más en la materia de interfaces gráficas) si deberías citarlo. Si no es así ("how to edit single lines in a file python", por ejemplo, que es una consulta super común), no es necesaria una cita.

4. No es necesario. 

Espero haber respondido tu duda! 🐦

**Comment by NikiHV** [comment]
Muchas gracias!! Quedó clarito :blush:
