### ISSUE TITLE
función de librería prohibida

### ISSUE THREAD

**Issue by santiago3c** [IIC2233/Syllabus#148]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, que pensando en cómo resolver una pregunta de la tarea si me ocurrió una posible idea que usa una función de una librería prohibida, pero el punto es que en internet también uno puede encontrar cómo crear uno por su cuenta esa función con toda la materia que ya hemos visto, entonces si puedo citar esa página de internet y extraer la función y ponerla en mi código

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Hernan4444** [comment]
Hola @santiago3c 

Si es que lo que encontraste utliza únicamente contenidos que ya se habían pasado al momento de publicar su tarea, no hay problema en ese caso con utilizarlo y citar. No obstante, si el código que encontraste utiliza contenido nuevo, por ejemplo `yield` (que ya se [dijo que está prohibido](https://github.com/IIC2233/Syllabus/issues/55#issuecomment-1698367184)), entonces no se aceptará citar ese código porque está ocupando elementos no permitidos.

El motivo de esto es que si la librería está prohibida, entonces es porque esta tarea no requiere de su uso para resolverla y eso incluye su código fuente, lo cual sería practicamente lo mismo que utilizar la librería prohibida. Si bien esta semana vimos más contenidos, por ejemplo, generadores,`yield`, `map`, `filter`, `reduce`. la tarea está diseñada para ser resuelta únicamente con los contenidos vistos hasta el momento de su publicación, por lo tanto, no se permitirá utilizar código "nuevo" porque no nos permite evaluar que sepan aplicar los primeros contenidos.

Reiterando lo anterior, si lo encontrado no hace uso de contenido nuevo, y lo hace solamente con material que ya vimos para cuando publicamos la tarea, entonces no hay problema con citarlo y usar dicho código. Al final estás utilizando y aplicando la materia que justamente queremos evaluar en esta evaluación 😄.

¡Mucho éxito con la tarea!
Saludosヾ(＾-＾)ノ

**Comment by santiago3c** [comment]
vale muchas gracias
