### ISSUE TITLE
.idea permitido?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#148]
Esta permitido subir la carpeta .idea generada por mi editor (pycharm) a la tarea?

**Comment by IchottMano** [comment]
@naquiroz Hola!
Si bien en esta tarea no se penalizará, en futuras tareas es muy probable que sí, además de ser una buena práctica.
Es por esto que te recomiendo leer [esta guía](https://git-scm.com/docs/gitignore) sobre como crear un archivo *.gitignore* para tu repositorio, a modo de evitar que git suba los archivos indeseados.
Espero resuelva tu duda.
Saludos!
