### ISSUE TITLE
Duda sprites de aliens luego de explosión

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#148]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado está explicado que luego de matar a un alien su sprite debe cambiar a su versión muerta y una explosión debe crearse, pero no se explica si el sprite del alien debe eliminarse de la pantalla o no. Supongo que sí debieramos hacerlo para que se vea más limpio, pero podría ser que no se viera el cambio del sprite vivo al muerto por la explosión que ocurre poco después de haber matado al alien.

**Comment by Emiliax16** [comment]
Hola @MaxAl100 ! Al dispararle a un _alien_ se debe cambiar inmediatamente al sprite que corresponde al _alien dead_, al mismo tiempo que se muestra la secuencia de la explosión. Sin embargo, la secuencia de la explosión tarda más que el cambio de sprite del _alien_, por lo que mientas ocurre esta explosión, el _alien dead_ debe caer en línea recta hasta llegar al panel de estadística, para luego desaparecer. Una de las imágenes del enunciado muestra la secuencia de pasos al disparar: 
![disparo f3](https://user-images.githubusercontent.com/69869381/167274110-21e7d902-9e54-4e63-b98f-8dbd84d0260e.png)

Espero se haya entendido! saludos c:

**Comment by Emiliax16** [comment]
Hola @MaxAl100 ! Al dispararle a un alien, debe suceder al mismo tiempo el cambio de sprite al _alien dead_ y las tres fases de la explosión. Sin embargo, luego de cambiar el estado del alien, éste debe caer en línea recta para luego desaparecer en el panel de estadísticas. En el enunciado se muestra una imagen de cómo debe funcionar la secuencia: 
![Inkeddisparo f3_LI](https://user-images.githubusercontent.com/69869381/167274289-42e5ddee-3fa0-4e3a-97e7-46df3180f05c.jpg)
Espero se haya entendido! saludos c:

**Comment by MaxAl100** [comment]
Sip, ahí se entendió! No había cachado que se estaba cayendo el alien muerto ni que había que "animar" una caída hasta el panel de estadísticas, así que muchas gracias!
