### ISSUE TITLE
Duda sobre actividad ExcavadorDocencio y ExcavadorTareo (Duda enunciado)

### ISSUE THREAD

**Issue by plourido** [IIC2233/Syllabus#149]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola que tal, buenas noches. Les escribo ya que tengo una duda en cuando ocurren ciertas acciones:
1.  En ExcavadorDocencio: el aumento de felicidad y fuerza adicional se da al terminar de cavar o después de otra acción?
2. En ExcavadorTareo: el aumento de edad y disminución de felicidad se da al consumir el ítem consumible ?  o después de otra acción? (esto ya fue preguntado creo)

Muchas gracias.

**Comment by mpiavf** [comment]
Hola! Tal como dice el enunciado, para el ExcavadorDocencio, el aumento de felicidad y fuerza adicional se realizan cuando el excavador termina de cavar en el día. 
En el caso de ExcavadorTareo, los cambios que mencionas se dan al momento de consumir el ítem de tipo consumible.
Saludos!

**Comment by tremendapithon** [comment]
Hola, tengo una duda con ese tipo de variables que aumentan la felicidad o la fuerza, u otro ejemplo es "PROB_ENCONTRAR_ITEM", esas variables se escogen de forma arbitraria ??

**Comment by mpiavf** [comment]
Hola! Exactamente, este parámetro al igual que todos los que sean de ese formato vas a tener que definirlos en el archivo  `parametros.py` .
Saludos!

**Comment by mpiavf** [comment]
Hola! La idea del archivo `parametros.py`es que los parámetros sean fijos y no funciones. Si quisieras implementar algo como lo que dices, tendría que ser por ejemplo a = random.randint(1,parametros.prob_algo), en donde prob_algo este definido desde antes en el archivo.
Saludos!
