### ISSUE TITLE
Espacios pep8

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#149]
Hola, los espacios cuentan como caracteres en pep8?

**Comment by jmwielandt** [comment]
Los espacios cuentan como caracteres, por lo tanto, cuentan para PEP8.
Si utilizas un editor de texto mínimamente decente verás que en la parte de abajo te dice `Col` y un número, eso indica cuántos caracteres hay desde el inicio de la línea hasta donde está el cursor.

![image](https://user-images.githubusercontent.com/37153467/55677242-c7289e00-58ba-11e9-9251-016823ebaf38.png)

[https://www.python.org/dev/peps/pep-0008/](PEP8)
