### ISSUE TITLE
Papelera de reciclaje en WSL?

### ISSUE THREAD

**Issue by javiverastegui** [IIC2233/Syllabus#149]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

[Describe tu problema de manera detallada, explicando qué estás intentando hacer y explicando los errores o problemas que has encontrado. Se recomienda agregar fotos cuando sea posible]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola!
Me ocurrió un pequeño GRAN percance.
Intentando subir la T1 a github, borre accidentalmente toda la T1, (tenia en mi repositorio personal el directorio de la tarea como "Directorio Personal/T1/T1/"Tarea", y quería cambiarlo a "Directorio Personal/T1/"Tarea"), por lo que en una maniobra que ni yo entendí termine borrando toda la T1. 

La pregunta es si ***hay alguna sección como "papelera de reciclaje" que me permita acceder a ese contenido?*** O estoy destinado a realizar la Tarea 1 de nuevo?

PD : 
En la papelera de Windows no aparece la carpeta.

![imagen_2023-09-02_182903488](https://github.com/IIC2233/Syllabus/assets/106976943/296e6898-e159-41dd-9e3f-9da34293febb)

**Comment by javiverastegui** [comment]
Por lo que he investigado WSL ***NO PRESENTA UN SISTEMA DE PAPELERA*** por lo que tendre que hacer la tarea 1 de nuevo :)))

**Comment by Hernan4444** [comment]
Hola @javiverastegui 

Lamentablemente WSL no viene con defecto con un sistema de papalera. No obstante, la gracia de que usamos `git` en el curso es que ahí vamos guardando nuestros avance. Similar a un juego donde podemos ir guardando nuestros _checkpoints_ constantemente. Por lo tanto, lo que uno puede hacer es volver a un commit anterior para recuperar los archivos o cualquier cambio que uno no quería perder.

Para hacer esto, hay varias alternativas (`git revert`, `git reset`, `git checkout`, etc). Por simplicidad, mostraré uno de lo más directo de entender.

1. Primer hacer `git log -n 5 | cat` Esto nos imprimirá en consola los últimos 5 commits que tengamos en el repositorio. Ese 5 se puede cambiar por otro número para ver más commits.
2. Para cada commit se indica una palabra compuesta por letras y números. Ese es el hash del commit que es un identificador único. Por ejemplo. En la siguiente foto hice log de los últimos 2 commits del Syllabus. `2299a48a6abc428338dbbc6ad0a2df45197407da` es el hash del último commit y `8edf6b455b30c3713b78bf027626ac6b06bdf51d` es el hash del penultimo commit.

<img width="350" alt="image" src="https://github.com/IIC2233/Syllabus/assets/15641721/d6101d18-3407-4af0-ac57-41d844607451">

3. Luego hay que hacer `git checkout COMMIT` donde COMMIT es ese hash que uno saca del paso (2).  Esto nos permitirá "viajar" al commit que queremos. Aquí viajaré al commit previo a subir la actividad, es decir, al commit donde subimos el PDF de la clase.

<img width="563" alt="image" src="https://github.com/IIC2233/Syllabus/assets/15641721/6ac62c8a-ffc2-4545-803b-3cd3d3b3d8d5">

4. Una vez estando en ese commit, podemos copiar los archivos que queremos recuperar y los pegamos en otra carpeta.
5. Luego hacemos `git checkout main` para volver al "presente". Y ahí pegamos los archivos que habíamos copiado en (4). 
6. Finalmente, hacer `git add` `git commit` y `git push` para subir los nuevos cambios donde "recuperamos" lo de un commit pasado.

Cómo dije antes, hay otras formas de volver a un commit, por ejemplo, investigando el uso de `git revert`, pero considerando que estamos empezando a usar git, opté por explicar esta forma. Más adelante del curso, cuando ya tengamos más interiorizado `git`, podemos explicar cómo usar `git revert` para volver a otro commit 😄 

¡Mucho éxito con la tarea!
Saludosヾ(＾-＾)ノ
