### ISSUE TITLE
Abandonar grupo y sobre parametros.py

### ISSUE THREAD

**Issue by mjsifri** [IIC2233/syllabus#149]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!! Tengo dos dudas distintas jajaja
Primero, cuando un usuario decide abandonar un grupo, se debe mostrar al tiro el mensaje??, o solamente se guarda en mensajes.csv y el resto de los integrantes al revisar su historial pueden ver el mensaje de que el usuario ha abandonado el grupo?? 
Por otro lado, a pesar de leer las issues y el enunciado me entra la duda de si el archivo parametros.py debe estar en el .gitignore ?? Ya que en el programa se debe importar este archivo, por lo que no se si agregándolo al .gitignore habrán problemas despues cuando el ayudante lo corrija.
Gracias!!

**Comment by RafaelEdwards** [comment]
Holaa!

Sobre tu primera pregunta, el usuario debe enviar de forma automática el mensaje donde se informa que ha abandonado el grupo, luego instantáneamente se debe eliminar a este usuario del grupo. En definitiva, el mensaje al abandonar el grupo debe mostrarse como el último mensaje del usuario.

En cuanto a tu segunda pregunta, tal como dice en la issue #54, debes agregar parametros.py al .gitignore. El ayudante no tendrá ningún problema para correr el código ya que el tendrá a mano este archivo, de todas formas debes especificar en tu README que se debe importar el archivo para correr tu código.

Espero haberte ayudado y suerte con tu tarea.
