### ISSUE TITLE
En la ECA ¿Diferencia entre "lectura del material" y "trabajo autónomo"?

### ISSUE THREAD

**Issue by sebapfu** [IIC2233/syllabus#149]
No me queda clara la diferencia :(

**Comment by aaossa** [comment]
Hola @sebapfu , buenísima pregunta ✨ Cuando solicitamos tener secciones personalizadas teníamos algo así en mente:

* **Lectura y preparación del material**: Estudio de los contenidos, considera la ayudantía
* **Actividad**: Considera resolución de la actividad durante el plazo correspondiente
* **Tarea**: Considera resolución de la tarea durante el plazo correspondiente
* **Trabajo autónomo**: Otro tiempo no incluído en los ítems anteriores

(La verdad no sé si les aparece la descripción en la ECA 😮 )

Como notarás "trabajo autónomo" es como un `else` 😅 (no pude evitar hacer esta asociación). Si bien estudiar el material es trabajo autónomo, la intención es que el estudio de los contenidos vaya al primer ítem 🙌 ¡Ojalá te sirva! Y gracias por responder la ECA 💯

**Comment by sbcorrea** [comment]
Y resolver los ejercicios propuestos, cuenta como lectura del material o trabajo autonomo?

**Comment by aaossa** [comment]
Hola @sbcorrea , mil perdones porque se me pasó este correo 😭.  Parece ser que lo mejor es considerarlo dentro de **trabajo autónomo**, ya que no son parte de los contenidos en sí, y el tiempo destinado a resolverlos es variable entre distintos pares de estudiantes, y depende del intento de resolverlos. Si respondiste el otro ítem, no hay ningún problema de todas formas, no habíamos considerado este caso 😅

**Comment by sbcorrea** [comment]
¡No se preocupe! Perfecto, muchas gracias
