### ISSUE TITLE
Archivo README.md

### ISSUE THREAD

**Issue by MrEarle** [IIC2233/Syllabus#149]
Con alcances y funcionamiento del sistema, ¿A que se refiere?

**Comment by hanavarrete** [comment]
Explicar sobre tu código, que cosas hace y cuales no. Lo importante explicar y ayudar a que el ayudante entienda lo que intentaste hacer. Saludos!

**Comment by hanavarrete** [comment]
Aclaración: La idea es que tampoco expliques tu código **función por función**. A nivel macro está bien, y que **indiques que cosas asumiste**.

**Comment by FernandoPieressa** [comment]
Hola! Mas información en issue #151
