### ISSUE TITLE
Creación de objetos

### ISSUE THREAD

**Issue by pgaguilera** [IIC2233/Syllabus#149]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

¿Para crear objetos se debe comparar la probabilidad de éxito, definida en parametros.py, con la probabilidad que te arroje la función random, y observar que si esta última es mayor que la del archivo .py se crea el objeto?
¿Se puede asignar un objeto con el mismo nombre a dos entrenadores distintos?

**Comment by Emiliax16** [comment]
Hola @pgaguilera ! precisamente debes hacer eso para la creación de objetos. Cada objeto tiene una probabilida de éxito de creación dado su tipo, por lo que tienes que arrojar un random y ver si este número es mayor o igual a la probabilidad del objeto.

Respecto a tu segunda pregunta, el enunciado no especifica ese tema, por lo que puedes asumir que dos entrenadores pueden poseer mismos objetos. Saludos 😸
