### ISSUE TITLE
Ataque Archimago con solo un planeta conquistado en la galaxia

### ISSUE THREAD

**Issue by Panckx** [IIC2233/Syllabus#149]
Hola! Qué debería ocurrir cuando solo tengo un planeta conquistado en la galaxia y visito otro planeta? Podría ser que el Archimago no tenga la opción de atacar mi único planeta conquistado? Lo digo por dos razones; uno, podría perder el único planeta conquistado, haciendo que la galaxia quede injugable, y dos, porque si decido atacar con mi único planeta conquistado a otro planeta y justo me ataca el Archimago, lógicamente el planeta atacado por el mismo se encuentra sin ejército (porque el ejército está invadiendo otro planeta), entonces la resistencia al Archimago es nula y es como decir que cada vez que se ataca a un planeta teniendo uno solo conquistado hay un 20% de probabilidades de perderlo.

**Comment by Arcoirisky** [comment]
Hola! Tú pregunta está respondida en otra issue O:

**Comment by Panckx** [comment]
No la puedo encontrar :(

**Comment by pcseisdedos** [comment]
Por lo que entiendo de la issue #143 es posible que una galaxia quede sin conquistas, la única posibilidad es que el único planeta conquistado sea vencido por un Archimago, ya sea cuando el usuario decide visitar ese planeta o invadir otro dentro de la galaxia
respecto a 
> cada vez que se ataca a un planeta teniendo uno solo conquistado hay un 20% de probabilidades de perderlo.
según yo sería 10%
PD: no soy ayudante

**Comment by Arcoirisky** [comment]
Prueba con la #126 O: 
En principio, el archimago puede atacar tu único planeta conquistado y ganarlo. Si te lo desconquista no puedes hacer más y ahí entra lo que dice la #126 :D

**Comment by pcseisdedos** [comment]
de #143  entiendo que si puede pasar lo que tu dices
respecto a
>  cada vez que se ataca a un planeta teniendo uno solo conquistado hay un 20% de probabilidades de perderlo.
no debería ser 10%?
PD: no soy ayudante

**Comment by Panckx** [comment]
Muchas gracias!!
