### ISSUE TITLE
Preguntas sobre varios temas de la tarea

### ISSUE THREAD

**Issue by anvaldes** [IIC2233/syllabus#149]
Preguntas

1. La probabilidad de accidente no debe estar entre 0 y 1? No faltaría algo del tipo si es menor que 0 entonces que sea 0 y si es que es mayor que 1, entonces que sea 1.
 
2. En la sección de calcular la probabilidad de accidente. La durabilidad máxima chasis es la máxima capacidad del chasis que ha tenido el auto en toda su historia, en la carrera o el valor máximo que puede tener ese parámetro?

3. ¿El daño a los vehiculos solo se da en pistas rocosas?

4. Como sabemos en las bases de datos que nos dan hay valores que ya vienen listos. ¿Que pasa si esos valor estan fuera del rango de nuestros parametros? Ejemplo: Que en mi base venga que chasis es 5, pero en mis parametros yo tengo que el minimo es 10. Lo que dice mi intuición es que se deje tal cual y que si se mejora entonces ahí cambiaría el valor de chasis y el minimo que podría tomar sería 10.

5. ¿Para los contrincantes se calcula la velocidad al igual que para nuestro personajes? 

6. En velocidad recomendada, más del 90% de las combinaciones de todos los datos me da negativa, entonces estuve revisando y es porque el factor de dificultad de la pista es de orden mucho mayor a velocidad base, creo que si se dejara la formula como:

velocidad_recomendada = velocidad_base + (traccion_ruedas - hielo_pista) + 0.01*(experiencia_piloto-dificultad_pista)

Sería mejor porque lo unico que estamos haciendo es disminuyendo el orden al factor que involucra dificultad de la pista. Porque lo malo de que la velocidad recomendada sea mayoritariamente negativa es que eso implica que la velocidad intencional tambien sea negativa y al momento de calcular la velocidad real, en la mayoría de los casos estaría elegiendo la velocidad minima que viene dada por mis parametros y así las carreras serían casi entre puros autos que tienen la misma velocidad y es la velocidad minimima.

NOTA: Es importante notar que la velocidad recomendada no depende de mis parametros, por ende, no se puede hacer más que modificar la formula para cambiar los resultados.

**Comment by gatochico** [comment]
Hola! Por temas de orden y para facilitar la búsqueda de issues en el foro, te pedimos que hagas una issue **separada** para cada pregunta, o por lo menos agruparlas por tipo (fórmulas, parámetros, daños, etc.,). 
Gracias de antemano!
