### ISSUE TITLE
Duda ventana de ranking

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#149]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado es explicado que desde la ventana de inicio se puede abrir la ventana de ranking sin cerrar la ventana de inicio y desde la ventana de ranking se puede volver a la ventana de inicio ya sea apretando un botón o simplemente cerrando la pestaña.
Mi pregunta es la siguiente: **¿Si apretamos el botón debemos sólo cerrar la pestaña de ranking o debemos abrir una pestaña de inicio? En el caso de que debamos abrir la pestaña de inicio, ¿no puede haber un problema ya que se podrían crear infinitas pestañas?**

**Comment by Emiliax16** [comment]
Hola @MaxAl100 ! el enunciado no dice específicamente eso. Se dice que, desde la ventana inicio, al presionar la opción de abrir el ranking, se debe mostrar esta ventana. Al abrirse la ventana de ranking, se debe cerrar la de inicio, al igual que si seleccionas el opción de Jugar y se muestra la ventana principal. 

Por otro lado, la ventana de ranking se debe cerrar al seleccionar volver o cerrando la pestaña, para luego mostrar la ventana de inicio. De esta manera, no se creará un loop entre las ventanas. Saludos.
