### ISSUE TITLE
error charmap al leer posts.csv

### ISSUE THREAD

**Issue by ElTurkos** [IIC2233/syllabus#149]
[redacted]
![imagen](https://user-images.githubusercontent.com/10425834/77229016-06064100-6b6a-11ea-9000-5effa09b3a09.png)

**Comment by jeschuwirth** [comment]
Hola @ElTurkos,

Ese error se debe a que al momento de abrir el archivo, se intentan decodificar los caracteres usando CP-1252 (el default de windows). Como esa codificación no tiene tildes ni la letra ñ hay problemas al decodficar archivos en español.

La respuesta la entrega @benjavicente en la siguiente issue #16 

Suerte!

**Comment by ElTurkos** [comment]
Lo hice y me da este error
![Captura](https://user-images.githubusercontent.com/62064830/77228866-f3d7d300-6b68-11ea-8d05-931896a2ba42.PNG)

**Comment by jeschuwirth** [comment]
Creo que copiaste y pegaste de una página el with open, por lo tanto copió los " como unas comillas dobles especiales.

Las comillas dobles en tu "r" son distintas a las comillas dobles en "utf-8", intenta colocar las mismas que tienes en "r" por si funciona.

**Comment by ElTurkos** [comment]
Funciono, muchas gracias!!!

**Comment by aaossa** [comment]
@ElTurkos cuando pidas ayuda sobre un error particular pudes colocar el mensaje de error obviamente, pero en las capturas que colocaste agregaste código de tu tarea lo que puede interpretarse como compartir código y detectarse copia con otras tareas. Es por esto que edité tus imágenes. Sé más cuidadoso por favor, e intenta no compartir código de tu tarea en las *issues* (o lo menos posible 👀 )
