### ISSUE TITLE
Reglas del foro (issues)

### ISSUE THREAD

**Issue by sebacruzd** [IIC2233/Syllabus#15]
# Issues
Este foro está hecho para que **compartan sus dudas**. También será usado para **publicar información relevante** en algunos casos. 

Este es un **medio oficial de comunicación** por lo que es tu deber **revisarlo periódicamente**, ojalá todos los días, para que no estés desinformado/a.

### Reglas del foro:

 1. Revisar si alguien más ya preguntó por tu duda. Si se repite algo ya preguntado en otro issue, se cerrará el repetido y no se responderá/ se linkeará al correcto.

 2. Googlear antes de crear un issue. Si no está en internet, o no te queda claro, crea una issue.

 3. No puedes postear código de tus tareas. Si tienes una duda puedes crear un código de ejemplo, que no entregue suficiente información, con tal de que no puedan copiarte.

 4. El foro no es un medio de reclamos. Cualquier mensaje de este tipo debe ser enviado mediante el formulario de contacto encontrado en la página principal. Procura ser respetuoso/a.

5. Si ya se ha resuelto tu duda en un issue que creaste, ciérralo con "Close Issue".

**Comment by jorgeriesco** [comment]
Por favor, ¿Pueden adjuntar la pagina del curso?

**Comment by iqacevedo** [comment]
@jorgeriesco es https://iic2233.github.io/
Saludos !
