### ISSUE TITLE
No se muestra ninguna versión de Python en VScode habiendo seguido todos los pasos :(

### ISSUE THREAD

**Issue by nprohens** [IIC2233/Syllabus#15]
- **Sistema Operativo: Windows 11**
- **Programa a instalar: Python**

- Foto del error: 
![image](https://github.com/IIC2233/Syllabus/assets/131835598/4f609605-8237-447b-8340-90eaaf86c345)

- Descripción del problema: Al llegar al paso de "Escribe o pega en la barra de texto ext install ms-python.python y presiona Enter para instalar la extensión de Python.
Teniendo la extensión, puedes seleccionar tu versión de Python en la barra de estado (sector inferior izquierdo)", no me aparece ninguna version de python en la barra de texto luego de haber ejecutado el comando de instalación y tener instalada la extensión. Hice todos los pasos posteriores solo me falta ese paso que ya es de configuración de vscode.

**Comment by Hernan4444** [comment]
Hola @nprohens 

¿Nos puedes indicar en qué parte de los tutoriales de la wiki se pide hacer este paso? lo busqué, pero no lo encontré, para saber bien qué quieres hacer específicamente.

Quedamos atentos,
Saludos

**Comment by nprohens** [comment]
Hola
El paso esta como en la última sección donde ponen como un link para ir al apartado de los visores de código, como donde sale vscode, sublime, etc. En la sección de vscode está el paso que menciono.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Hernan4444** [comment]
Perfecto, ahí lo encontré,

Justamente eso se va actualizar, ya no es en el sector izquierdo, sino que en el derecho (mando foto)

<img width="800" alt="" src="https://github.com/IIC2233/Syllabus/assets/15641721/e23d3cc7-235a-4ec2-bd32-63a613085e78">

Ahí debes hacer click y luego seleccionar la versión de Python que quieres ocupar. En este caso, la 3.10.X que instalaste. 


Ahora bien, puede ser que VScode no detecte tu python dado que WSL se puede ver como "otro pc" donde ahí tienes python instalado, mientras que VSCode está en tu windows.

Así que la solución es:
1. Abrir terminal con WSL
2. Escribir `code .`
3. Con se abrirá VSCode desde WSL, lo cual implica que ahí si detectará el Python. Luego, en ese "otro PC", asegurarse de tener los archivos que quieras ejecutar, por ejemplo, tu repositorio de github y el syllabus.

Es importante recarcar que WSL se puede ver como "otro PC" y por lo tanto, los archivos que tengas en tu windows no son accesibles fácilmente desde WSL, así que siempre que quieras ejecutar un archivo, este debe estar en la carpeta de WSL. Si tienes algo en windows y quieres moverlo a WSL, entonces una opción es escribir `explorer.exe .` para abrir tu explorador de archivos, y asegurarte de mover los archivos de windows a la carpeta de WSL. Con eso estarás listo.

Avísanos como te va con esto,
Saludosヾ(＾-＾)ノ

**Comment by nprohens** [comment]
Oka voy a probar y lo veo gracias

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nprohens** [comment]
No se si se mandó bien el mensaje pero lo mando de nuevo por si acaso.
Sigue sin detectar bien la versión de Python. Así se ve mi interfaz de vscode para ver si pueden pillar el error.
Y por ejemplo puse print algo y no reconoce el lenguaje.
Perdón por la hora también pero no hay apuro en la respuesta 🙂.
[cid:aaabd28f-d9fe-4ab1-a2ba-13009d7e6634]
________________________________

**Comment by nprohens** [comment]
Hola ayer mande una respuesta muy tarde y no se si la vieron
________________________________

**Comment by Dvckhv** [comment]
Hola! No es visible la foto que enviaste :(, pero, en la terminal de wsl puedes abrir un entorno de python? Para eso escribe en tu consola de ubuntu `python3`, me cuentas :)

**Comment by nprohens** [comment]
Ahí adjunto la foto para ver si lo pueden ver.
En cuanto a abrir Python en wsl ahora no tengo mi pc, pero lo pruebo en la tarde.
________________________________

**Comment by Hernan4444** [comment]
Hola @nprohens 

No se ve la foto. Lo que pasa es que estás respondiendo esto via email

![image](https://github.com/IIC2233/Syllabus/assets/15641721/c5ab1c06-43ed-44a3-9a2b-505cb7fc00e7)

Y de esa forma no funciona enviar fotos. Debes acceder a la página desde tu navegador: https://github.com/IIC2233/Syllabus/issues/15 y ahí pegar la foto.

Saludos

**Comment by nprohens** [comment]
Antes lo habia subido por github y tampoco se pudo ver no se como mas lo puedo hacer

**Comment by Hernan4444** [comment]
Hola, ahí si se ve la imagen

El tema es que estás abriendo VSCode fuera de WSL, por lo tanto, VSCode no detecta el python.  Debes abrir WSL con (aquí hay un [tutorial oficial de VSCode donde explican eso](https://code.visualstudio.com/docs/remote/wsl#_open-a-remote-folder-or-workspace)).

Y ahí si, en la esquina izquierda inferior deberías ver esto

![image](https://github.com/IIC2233/Syllabus/assets/15641721/4e7341b7-e35d-4d9b-a6e4-54e514832588)

Una vez se logre eso, en la esquina derecha inferior, donde dice "Python" y "Select interpreter", te debería salir el python que instalaste en WSL.

Por el momento, intenta abrir VSCode con WSL y luego seguiremos al siguiente paso.
Saludos!

**Comment by nprohens** [comment]
Ya ahora lo logre hacer, volvi a hacer todos los pasos pero ahora dentro de wsl, y al ejecutar python con un comando cualquiera me sale un error de directorio.
![image_2023-08-16_135221170](https://github.com/IIC2233/Syllabus/assets/131835598/e3b8c4e1-6f3c-4951-ab2e-947289ccf62b)

**Comment by Hernan4444** [comment]
Hola @nprohens 

Lo que pasa es que estás intentando que VSCode ejecute el archivo, pero en este curso no se usará VSCode para ejecutar, sino que se usará la terminal. Recomiendo ver [este video para ejecutar archivos desde la terminal](https://www.youtube.com/watch?v=TSBZMwZmKcg&list=PLQI-jYMgXtz-siHH3SpdiHBApkQ7z1Q54&index=5).

Y el primer paso, es que el archivo que quieras ejecutar debe estar en la carpta de WSL, no en "Downloads" porque dicha carpeta está tu pc windows y WSL es un pc con Ubuntu. Imagina que ahora tu computador tiene 2 PC, y python está en el PC de WSL,así que ejecuta cosas de dicho PC y no cosas que estén en windows.

¿Cómo se logra esto?

1. Abres tu terminal con WSL
2. Escribes `code .` para abrir VScode con WSL **dentro de la carpeta de WSL**
3. Ahí creas un archivo .py (puedes usar VScode para crear un archivo o bien escribir `touch main.py` para crear un archivo llamado "main.py").
4. Desde tu terminal que abriste en (1), escribes `python3 main.py`


Otra opción,  es que escribas, en tu terminal con WSL, `explorer.exe .` para abrir la carpeta donde estás parado. Y ahí pegar un archivo .py que ya tengas creado. Este [video que acabo de encontrar](https://www.youtube.com/watch?v=XIsTDd7o8yk) muestra visualmente cómo usar `explorer.exe` para mover archivos de windows a WSL (ver solo los primeros 4 minutos). Y así puedes mover tu `hola.py` a WSL y ahí si hacer `python3 main.py` desde tu terminal.

Lo importante de todo esto es comprender que cómo python está instalado en WSL, hay que ejecutar archivos que estén dentro de WSL, y la carpeta "downloads" no está en WSL y por eso te falla.

Avísanos cómo te va con todo esto.

**Comment by nprohens** [comment]
Ok muchas gracias te pasaste

**Comment by santiago3c** [comment]
Hola, yo también tengo un problema parecido y no lo he podido solucionar, que es que no he podido usar python en Visual Studio Code. Intento seleccionar un interpreter pero no me aparece. Abro Visual Studio Code desde WSL y me aparece lo siguiente, no se si esto puede ayudar
![Captura de pantalla (145)](https://github.com/IIC2233/Syllabus/assets/142272696/8bad23aa-a49d-4a31-8e27-5675e7f6770e)

**Comment by Hernan4444** [comment]
Hola @santiago3c 

Respecto al problema indicado, solo es que VSCode no confía en WSL, pero basta con ponerle "Allow" porque nosotros si confiamos en WSL. Luego, dentro de VSCode te preguntará nuevamente si "confiar en los archivos" y tienes que poner que sí confías.

Si lo indicado no funciona, te recomiendo crear otra issue indicando este problema y que ya intentaste la solución indicada en esta issue. Así podemos entregar una solución específica a tu problema y lo dejamos en una issue específica sobre el uso de `code .`

Saludos y quedamos atentos a tu situación,
