### ISSUE TITLE
Problemas al cerrar el host de jupyter

### ISSUE THREAD

**Issue by maurobsp** [IIC2233/syllabus#15]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)

### Problema

Hola estaba revisando el video de instalación de Jupyter y puedo abrirlos desde mi computador pero cuando quiero cerrar el host de Jupyter que se abre en el navegador web según el video si introduzco Ctrl+C dos veces en la consola cmd donde abrí el Jupyter se debería parar el Jupyter y darme la opción de cerrar desde el navegador pero al hacer esto no pasa nada y no se como cerrar el Jupyter del navegador. por ahora lo estoy cerrando al cerrar el navegador completo lo que es incomodo.

**Mi duda es si existe otra forma de cerrar Jupyter desde la consola ya que Ctrl+C no me funciona**

**Comment by igbasly** [comment]
Hola @maurobsp :v:

Efectivamente, Jupyter funciona como un servidor corriendo en la terminal, lo cual te permite ver una interfaz en el navegador. Por lo tanto, cerrando la ventana del navegador, no se detiene Jupyter.

Esto nos deja dos opciones para hacerlo:
1. Como te mencionaban en el tutorial, puedes ir a la terminal y "terminar el programa" con `CTRL + C` lo cual hará que Jupyter te pregunte si quieres terminar o no (en la misma terminal). Te darás cuanta si el programa termino porque probablemente verás la línea de comandos vacía y lista para ingresar algún comando `C:/.../$ `.
2. Como segunda opción, Jupyter permite cerrar el servidor directamente desde la interfaz. Si vas a la pestaña de Jupyter en tu navegador, en la parte superior derecha habrá un botón que dice "Quit", cuando lo presiones deberá terminar el proceso y en la venta de la terminal podrás ver nuevamente la línea de comandos lista.

Espero que esto te ayude y no dudes en preguntar cualquier otro problema que pueda surgir :smile:.

**Comment by jamigone** [comment]
Holaa @maurobsp, yo tenía el mismo problema y, si bien no pude solucionarlo, descubrí que existe la extensión de Jupyter en Visual Studio Code. Si usas este editor de código te recomiendo que lo descargues, a mi juicio es muchísimo más cómodo en vez de abrirlo con el navegador web :)

Aquí una foto de cómo se ve, si te fijas arriba a la derecha aparece Jupyter junto a un logo de "conectado"

![imagen](https://user-images.githubusercontent.com/50121013/111913375-a24c7780-8a4c-11eb-8a38-1a34f5848a3b.png)

**Comment by cristobalnic** [comment]
> Holaa @maurobsp, yo tenía el mismo problema y, si bien no pude solucionarlo, descubrí que existe la extensión de Jupyter en Visual Studio Code. Si usas este editor de código te recomiendo que lo descargues, a mi juicio es muchísimo más cómodo en vez de abrirlo con el navegador web :)
> 
> Aquí una foto de cómo se ve, si te fijas arriba a la derecha aparece Jupyter junto a un logo de "conectado"
> 
> ![imagen](https://user-images.githubusercontent.com/50121013/111913375-a24c7780-8a4c-11eb-8a38-1a34f5848a3b.png)

Muchas gracias por el aporte @jamigone !

**Comment by cristobalnic** [comment]
@jamigone, muchas gracias por el aporte!
