### ISSUE TITLE
Error con Git bash

### ISSUE THREAD

**Issue by Naogaz** [IIC2233/syllabus#15]
Al ejecutar algun comando en git bash me salta el siguiente mensaje:
$ git add main.py
fatal: Unable to create 'C:/Users/nicol/Desktop/Programacion/Naogaz-iic2233-2019-1/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

este error me estuvo dando problemas en el día de la actividad 1

**Comment by Arcoirisky** [comment]
El error dice que hay un proceso corriendo en tu repositorio y, en pocas palabras, se te está bloqueando el manejo de tu repositorio hasta que ese proceso termine. 

Una forma fácil de resolverlo es habilitando la opción de ver archivos ocultos, ahí aparecerá una carpeta .git en tu repositorio y si tomas el archivo index.lock que te molesta y lo borras puedes continuar con normalidad.

Sugiero siempre hacer git pull antes de intentar agregar o modificar algún elemento de tu repositorio. Si bien la solución que te doy funciona, deberías tener cuidado con lo que haces. Hacer un git status y ver lo que te sale es una buena idea para saber si algo raro pasa.

¡Buenas noches~ y ve a descansar que es tarde!

**Comment by Naogaz** [comment]
Muchas gracias, el problema queda resuelto.
(no tengo idea de como se cierra el post o algo asi).
