### ISSUE TITLE
Commit a revisar

### ISSUE THREAD

**Issue by jahernandez2** [IIC2233/Syllabus#15]
Hola! El commit a revisar en las Actividades, queda establecido como el que nos mandaron al mail? Pregunto para ver si tengo cuidado en pasar a hacer un commit en todo mi repositorio cuando estoy haciendo la tarea. Lo mismo me pregunto en el caso inverso: si en una actividad luego de una tarea, hago un commit en todo mi repositorio y se cambia la tarea, pasa algo? 
Saludos.

**Comment by magdalenanario** [comment]
Hola @jahernandez2 ! Sí, el commit que se revisará será el que te llegó al mail.  Es decir, si es que ahora haces otro commit y se cambia algo de tu actividad eso no será revisado. En las tareas pasa lo mismo, serán revisadas las del último commit registrado antes de la hora de entrega, sin importar los cambios que se puedan generar después en la misma tarea
