### ISSUE TITLE
Método para abrir archivos.csv

### ISSUE THREAD

**Issue by iastruque** [IIC2233/syllabus#15]
Que método debo ocupar para abrir los archivos usaris.csv, posts.csv, etc.?
He buscado en internet y me recomiendan solo librerias prhoibidas en el ramo.

**Comment by nachobascar** [comment]
Puedes usar el método open() y abrirlos como textos

**Comment by m-meza** [comment]
```
with open(path) as file_name:
    file = file_name.readlines()

```
Puedes usar esto

**Comment by jeschuwirth** [comment]
Hola @iastruque,

Como te respondieron anteriormente puedes usar la función open() de python.

Personalmente lo que más recomiendo es hacer lo que dice @m-meza o lo siguiente:
```
with open(path) as archivo:
    for linea in archivo:
        print(linea)
```

Si te quedaron dudas puedes seguir comentando en la issue :)

Suerte!

**Comment by based-on-what** [comment]
> Hola @iastruque,
> 
> Como te respondieron anteriormente puedes usar la función open() de python.
> 
> Personalmente lo que más recomiendo es hacer lo que dice @m-meza o lo siguiente:
> 
> ```
> with open(path) as archivo:
>     for linea in archivo:
>         print(linea)
> ```
> 
> Si te quedaron dudas puedes seguir comentando en la issue :)
> 
> Suerte!

Hola, copié un código de ese mismo estilo y no hay caso con mi archivo de "usuarios.csv", no entra al ciclo de leer línea por línea, revisé los paths de ambos archivos (el .csv y el .py) y el de .csv empieza con c:, mientras que el de .py empieza con C:, eso influye en algo? Por favor gracias

**Comment by jeschuwirth** [comment]
Hola @based-on-what,

Para evitarte muchos problemas te recomiendo trabajar con el path relativo en lugar del path absoluto.

Con esto me refiero, en lugar de tener un path como este: 
"C:\Users\jeschuwirth\Desktop\Python\Tests\usuarios.csv"

Si tienes el archivo usuarios.csv y tu archivo main.py en la misma carpet (en el ejemplo anterior sería la carpeta Tests).

Entonces puedes abrir el archivo haciendo:

```
with open(usuarios.csv) as archivo:
    for linea in archivo:
        print(linea)
```
