### ISSUE TITLE
Directorio para archivos txt

### ISSUE THREAD

**Issue by nicoguz** [IIC2233/syllabus#15]
Hola!
Tengo una duda sobre donde guardar (y crear desde el archivo de python) los archivos de txt (puntaje, ranking, etc) porque en este minuto los estoy guardando en mi repositorio pero la dirección que ingreso en el codigo es exclusiva a mi pc (C:\Users...). ¿Funcionará aún si se corre desde otro pc?

**Comment by KnowYourselves** [comment]
Hola @nicoguz!

Exactamente, tu código no funcionaría en otro computador 😭, por ejemplo, mi carpeta `User` probablemente va a ser distinta a la tuya. La solución para esta problemática es el concepto conocido como _**Path Relativo**_.

De forma muy resumida, un _path_ es la ubicación de un archivo o carpeta dentro del computador, este puede ser **absoluto** o **relativo**. 

1. **Path Absoluto**:
    Este tipo de _path_ especifica una **ubicación exacta**. Parte con un `/` o con el disco en el que se está buscando (por ejemplo `C:`)- El problema con esto es que no podemos asegurar que la estructura de carpetas sea la misma entre distintos computadores y sistemas operativos.
2. **Path Relativo**
    Este tipo de _path_ especifica una **ubicación relativa a la carpeta desde donde fue ejecutado el programa**. Nunca parte con un `/`. Por ejemplo, si ejecuto un programa en el escritorio el _path_ `imagenes/gatos/long_cat.jpg` será interpretado **desde el escritorio**, es decir, buscará la carpeta `imagenes`, dentro del escritorio, luego la carpeta `gatos` dentro de `imagenes` y finalmente el archivo `long_cat.jpg` dentro de la carpeta `gatos`.

Esto quiere decir que para asegurar que tu programa funcione en todo computador debes utilizar _paths_ relativos  y especificar en tu `README` que carpetas/archivos necesitan estar presentes para el correcto funcionamiento de tu programa. Si te interesa el tema y quieres buscar una explicación más extensa, la puedes encontrar en [este jupyter](https://github.com/IIC2233/contenidos/blob/master/semana-01/3-paths.ipynb) de los contenidos.

Espero haberte ayudado!

**Comment by nicoguz** [comment]
Oka, Gracias!

**Comment by burgosibarra** [comment]
Hola! En qué carpeta se guardan los archivos que contienen los puntajes o ranking? En el mismo que estén los archivos principales?

**Comment by KnowYourselves** [comment]
Hola @burgosibarra!

Eso queda a tu criterio.

Éxito!

**Comment by burgosibarra** [comment]
Gracias!
