### ISSUE TITLE
pip y jupyter no me funcionan

### ISSUE THREAD

**Issue by ewaugh2** [IIC2233/Syllabus#15]
Tengo Python 3.6.2 instalado pero cuando intento usar "pip (o pip3)" o "jupyther notebook" en la linea de comandos me responde:

`"pip" (o "pip3" o "jupyter notebook") no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable.`

¿Cual puede ser la causa? 
¿Que puedo hacer para arreglarlo?

(Tengo Windows 10 por si acaso)
Gracias en adelantado.

**Comment by jtagle2** [comment]
Prueba lo que se dijo en #7 
Saludos

**Comment by egromero** [comment]
Hola!
Te funcionan comandos propios de windows, como `ipconfig` o `ping` ? Si te sale el mismo error, es probable que se te haya desconfigurado una variable de entorno de windows (por lo general una llamada PATH) En internet hay varios tutoriales de como arreglarlo.

Saludos

**Comment by ewaugh2** [comment]
Lo que decía en el #7 me sirvió. Muchas gracias.

(Esto es para el que tenga el mismo problema).
Por miedo a hacer algo mal en el `Path` desinstalé y volví a instalar python pero en la reinstalación puse la opción _Agregar la carpeta Python 3.6 al PATH_ y se hace solo (a mi me pasó que el buscador de windows no encontraba la carpeta tampoco).

**Comment by ewaugh2** [comment]
Como pongo que el issue fue resuelto? jajaja

**Comment by Arcoirisky** [comment]
(Estoy en el celular pero en computador debe ser lo mismo) Abajo de la casilla comentarios sale close y comment. Si comentas y quieres cerrar la issue el botón Close se transforma en Close and comment c: así se sabe. Inténtalo tu mismo O:!!

**Comment by ewaugh2** [comment]
jaja ya gracias
