### ISSUE TITLE
Jupyter Notebook no corre celdas.

### ISSUE THREAD

**Issue by fffonceca** [IIC2233/Syllabus#15]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

El problema surge al entrar a la aplicación usando `jupyter notebook` en la consola de comando donde están los archivos `.ipynb`. Usando el shortcut `Ctrl + Enter` no es posible correr las celdas dentro de este. Para instalar jupyter y python usé los tutoriales de canvas. La única diferencia que podría existir es que yo contaba con Python 3.7.9, por lo que tuve que desintalarlo e instalar Python 3.8.10 (la versión que se recomienda en el curso).

Corrí comandos de esta [issue](https://github.com/ipython/ipython/issues/10346) sin mucha ayuda. Corrí de este repositorio el comando `pip install --upgrade ipykernel` y no funcionó. En el localhost:8888 si reviso el Kernel aparece que está en _Shutdown_ . Lista de paquetes y versiones:
```
Package             Version
------------------- ----------
ipykernel           6.2.0
ipython             7.26.0
ipython-genutils    0.2.0
ipywidgets          7.6.3
Jinja2              3.0.1
jupyter             1.0.0
jupyter-client      7.0.1
jupyter-console     6.4.0
jupyter-core        4.7.1
jupyterlab-pygments 0.1.2
jupyterlab-widgets  1.0.0
```
Actualmente estoy usando un Windows Home de 64bits.

**Comment by fernandosmither** [comment]
Hola! podrías enviar una SS del indicador del kernel?

![image](https://user-images.githubusercontent.com/66154723/130485594-c85fb135-2bea-4b42-949d-ff2443241d02.png)

btw: No soy experto en Jupyter Notebook, pero el shortcut que yo siempre he usado es `Shift + Enter`

**Comment by fffonceca** [comment]
Esta foto te sirve?

![imagen](https://user-images.githubusercontent.com/48364596/130502388-7a53ea07-9f58-49d3-bb29-ef727e38246d.png)

**Comment by fernandosmither** [comment]
> Esta foto te sirve?
> 
> ![imagen](https://user-images.githubusercontent.com/48364596/130502388-7a53ea07-9f58-49d3-bb29-ef727e38246d.png)

Buenísima! Lograste al final correr la celda de 2+2. ¿Ese era tu problema?

**Comment by fffonceca** [comment]
@fernandosmither Efectivamente puedo correr celdas propias, pero por algún motivo no se retorna output de las celdas del curso.

**Comment by fernandosmither** [comment]
> @fernandosmither Efectivamente puedo correr celdas propias, pero por algún motivo no se retorna output de las celdas del curso.

Podría ser que no les estés dando a trust. Te escribo en discord?

**Comment by fffonceca** [comment]
@fernandosmither No hay problema!

**Comment by fernandosmither** [comment]
Resuelto con lo hablado arriba!

**Comment by fffonceca** [comment]
El problema me lo hizo notar @fernandosmither . Al final estaba corriendo sin querer el texto markdown en vez de una celda de código.
