### ISSUE TITLE
Tamaño máximo de filas y columnas del tablero

### ISSUE THREAD

**Issue by mati-gonz** [IIC2233/syllabus#150]
Hola, tengo una duda de como está escrito el intervalo máximo de filas y columnas en el enunciado de la tarea, este dice _**"el jugador deberá ingresar dos enteros N y M pertenecientes al rango [3,15] que representarán el número de filas y columnas del mapa, respectivamente"**_.
Mi duda es que, tanto las filas como las columnas deben estar en ese rango? (mínimo 3 y máximo 15) o las filas deben ser máximo 3 y las columnas máximo 15?

**Comment by jitorcas** [comment]
Hola @mati-gonz 👋🏻 

Tal como dijiste, ambos enteros deben estar dentro del **intervalo [3, 15]**. Las filas pueden estar entre [3, 15] y las columnas pueden estar entre [3, 15], incluyendo los extremos en ambos casos. 

Espero que haya solucionado tu duda.

Éxito en la tarea!! ⚓️
