### ISSUE TITLE
Duda fin de nivel

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#150]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado es mencionado que "se debe mostrar una animación de Terminator-Dog riéndose una vez finalizado
el nivel" pero en la misma oración siguiente se dice que "debe aparecer una animación de Terminator-Dog mostrando el resultado de la cacería". **¿Debemos mostrar una animación y cuando esta finalice mostrar la siguiente animación?**

**Comment by nzamorano** [comment]
Hola, tal como dices, se debe mostrar primero a _Terminator-Dog_ riéndose y luego la otra.
