### ISSUE TITLE
 Puedo crear nuevos métodos en la clase Tablero para acceder a las property?

### ISSUE THREAD

**Issue by espeescobar** [IIC2233/Syllabus#150]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Puedo crear nuevos métodos en la clase Tablero para acceder a las property?

Al intentar acceder a las property de la clasee me retorna <property object at 0x7f25... , por o que quiero intentar hacer un método para acceder al valor númerico de la property, se puede hacer esto o no está permitido para la tarea?

**Comment by roahoki** [comment]
hola @espeescobar! te recomiendo que tengas ojo con la forma en que estás tratando de acceder a la property. Además, tal como se menciona en el enunciado para la parte 1: "_Para cada clase, método y property indicada a continuación, no puedes modificar su nombre, agregar nuevos argumentos o argumentos por defecto. Puedes crear nuevos métodos, archivos y/o funciones
si estimas conveniente, pero debes mantener el formato de los métodos entregados. En caso de no respetar
lo indicado, la evaluación presentará un fuerte descuento._". Si es que quedas con alguna duda, vuelve a responder esta issue por favor :)
