### ISSUE TITLE
CamelCase o camelCase?

### ISSUE THREAD

**Issue by Dnpoblete** [IIC2233/syllabus#150]
Hola, al ver los descuentos decía que hay que usar adecuadamente "CamelCase" y "snake_case", pero buscando en internet sale que se escribe camelCase, tomando la primera en minúscula, por lo que talvez se refieren a PascalCase, entonces no sé si usar la primera en minúscula o en mayúscula.
También agradecería mucho si me pueden aclarar cuando usar camelCase y cuando snake_case.

Gracias :)

**Comment by KnowYourselves** [comment]
Hola @Dnpoblete!

### CamelCase

Cuando uno hace referencia a este término hay dos opciones:
1. CamelCase (que como vien dices es más conocida como PascalCase)
2. camelCase

En este caso nos referimos a la opción 1, ya que esa es la que está estipulada en la guía de estilo PEP 8. 

Respecto a su uso, CamelCase es principalmente usado para nombres de clases.

### snake_case:

snake_case se utiliza principalmente para nombres de funciones/metodos y de variables/atributos.

### Ejemplo:

```python3
class ClaseMuyImportante:  # CamelCase
    def funcion_algo_util(self, n):   # snake_case
         variable_muy_inutil = n  # also snake_case
         return variable_muy_inutil
```

Espero haberte ayudado!

**Comment by Dnpoblete** [comment]
Sii, muchas gracias!
