### ISSUE TITLE
Duda sobre funciones

### ISSUE THREAD

**Issue by Benjadef** [IIC2233/Syllabus#150]
Hola, tengo una duda, me gustaría saber porque esto se puede hacer con metodos de una clase y no con funciones
gracias! y saludos 

![captura de pantalla 2018-04-06 a la s 01 20 43](https://user-images.githubusercontent.com/37145976/38403398-9e2edefc-3939-11e8-8eb8-99e48c4ea452.jpg)

**Comment by hanavarrete** [comment]
Hola! hay algo que no te funciona o no se ejecuta tu código? En python no hay ningún problema usando kwargs. De todos modos, te dejo [este link](http://blog.thedigitalcatonline.com/blog/2015/02/11/default-arguments-in-python/) por si no entiendes como se usan los _**keyword arguments**_

**Comment by Benjadef** [comment]
Al final no era un problema, pense que no funcionaba pero si funciona, solo que pycharm lo deja como en gris cuando defines una variable y luego no la usas, por eso se quedaba en gris, mala mia 
gracias de todas formas!!
