### ISSUE TITLE
Estadisticas

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2233/Syllabus#150]
En las estadisticas de Resumen del dia y Muerte e Infecciones por dia, se debe poder saber cuanta gente se infecto y cuanta murio por dia.
Esta informacion se hace a nivel mundial? O tiene que haber un resumen por pais?

**Comment by DiegoAndai** [comment]
Ambos :)

**Comment by nivek0o0** [comment]
@DiegoAndai ¿cómo ambos? Según entiendo **Resumen del día** corresponde a cifras a nivel mundial y **Por País** corresponde a cifras de dicho país.

**Comment by stephichau** [comment]
@Rudyjb24 Lo correcto es lo que dice @nivek0o0. 
Saludos!

**Comment by acrojas2** [comment]
[Solo para confirmar]
Entonces si por ejemplo el jugador ingresa al juego el día 10 lo que habría que mostrar es:
Del dia 1:
se infectaron: x1, murieron: y1
Del dia 2:
se infectaron: x2, murieron: y2
.
.
.
Del dia 10:
se infectaron: x10, murieron: y10
(????)
