### ISSUE TITLE
Tipos de currencies y DDCs

### ISSUE THREAD

**Issue by norman123123** [IIC2233/Syllabus#150]
Hola, tengo una pregunta acerca de que tipos de currencies se usan en la tarea. 
Se supone que hay que crear currencies como SIM, KAM, WUB, etc, además del DCCryptoCoin (DDC).  Esto significa que debemos crear los tickers KAMSIM, KAMWUB, SIMWUB (todas las combinaciones)  también? o solo SIMDCC, KAMDCC y WUBDCC, etc ?? 

Además veo que en el ejemplo hay pesos (CLP), también hay que hacer lo mismo con CLP o no hay pesos y solo DCC? Se supone que cada uno parte con 100.000 DCC y 50000 de ambas currencies que se transen en el mercado en el que este inscrito. (no pesos, dcc's) 

Es necesario crear mercados para todas las combinaciones o si un usuario quiere cambiar KAM por WUB puede vender los KAM por DCC y después comprar los WUB con los DCC que consiguió ? (lo dejo a mi criterio? en este caso paga doble comision pero es mas fácil así que filo o no?)

**Comment by iqacevedo** [comment]
Porfavor antes de preguntar revisa las otras issues, tus dudas se responden en algunas que tienen el label de Importante incluso #54 y #64.
