### ISSUE TITLE
Ocurrencia evento y apertura tesoro

### ISSUE THREAD

**Issue by TriniAguilera** [IIC2233/Syllabus#150]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Tal como me dijeron en otra issue, la ocurrencia del evento ocurre al final del día (después de que los excavadores busquen los ítems), por lo que hay que considerar al día siguiente el evento que ocurrió el día anterior por si la probabilidad de encontrar un ítem se ve afectada debido al cambio del tipo de arena por el evento (a mojada o magnética). Mi duda es la siguiente: podría pasar que después de simular el día del torneo (excavadores cavan, encuentran ítems y ocurre el evento, en ese orden) el usuario decide usar un tesoro. En caso de hacerlo y que este sea de calidad 2, va a cambiar el tipo arena del torneo. Entonces, hay dos opciones:

1. Al día siguiente, considero el último cambio de arena (abrir tesoro), por lo que, a pesar de que haya ocurrido un evento en el que llueve y se cambia arena normal a mojada (por ejemplo), la probabilidad de encontrar un item (no es = a 1) y de que este sea tesoro o consumible nos equiprobable (uso datos de parametros.py). Lo anterior se debería porque al final la arena para el día siguiente no sería de tipo mojada por el evento, sino del tipo de cambio del tesoro.

2. A pesar de abrir el tesoro después de la ocurrencia del evento y que se cambie el tipo de arena, se considera al día siguiente al momento de encontrar un ítem que su probabilidad es = 1 (debido a la ocurrencia del evento que generó estas condiciones) y que sea tesoro o consumible equiprobable. En este caso, pasaría que el tipo de arena actual (apertura tesoro) no sea el mismo al tipo de arena que resultó luego del evento (si llueve y se cambia de normal a magnética, podría pasar que al abrir tesoro se cambie a rocosa).

**Comment by jtvaldivia** [comment]
Hola Trinidad,
si simulas un dia, lo ultimo que pasa es pasar al dia siguiente. De esta manera, el tesoro solo lo puedes abrir antes de simular el dia y nunca despues de simular el dia.
