### ISSUE TITLE
menus aprueba de todo tipo de errores

### ISSUE THREAD

**Issue by rmaguilera** [IIC2233/syllabus#150]
cuando en la tabla de distribución de puntajes dicen eso, esto incluye que si le pido al usuario que ingrese un numero e ingresa un string o un espacio vacio el programa deberia seguir corriendo?

**Comment by jeschuwirth** [comment]
Hola @rmaguilera,

Si, si el usuario ingresa cualquier input (incluido string vacío), tu programa no se debe caer. Sino que debería avisar al usuario input inválido y seguir corriendo.

**Comment by rmaguilera** [comment]
muchas gracias!

**Comment by Camila-sty** [comment]
Hola!
No entiendo muy bien como puedo hacer que el código continue cuando el usuario no ingresa algo correcto. Yo por ejemplo le pido un *input* al usuario pero no un *int(input)*, porque así supuse que podría ingresar cualquier cosa, entonces, para ese *input* tengo varias condiciones que dependen de éste, pero yo en cada condición *if,elif,else* pongo la condición de si *int(input)* es tal, ocurre bla bla. Entonces probando el código, yo puedo ingresar cualquier número y no se me cae el programa, pero cuando se ingresa un *str* se cae, y creo que no debería ser así ya que yo no estoy condicionando el *input*. No sé qué estoy haciendo mal.

También quiero mencionar que mediante la utilización del *input* como lo describí anteriormente, me arroja un error que no me aparece siempre, y por esto mismo, no sé que significa, ni por qué ocurre. Adjunto la imagen del error.

![error de input](https://user-images.githubusercontent.com/59337116/79300082-b3dbe580-7eb3-11ea-8e3c-e4a69764aad0.PNG)

**Comment by jeschuwirth** [comment]
hola @Camila-sty,

Excelente que estes posteando tu duda en una issue que esta muy asociada :D

Te recomiendo eso si no hacerlo si la issue anterior ya está cerrada, en este caso puedes simplemente crear una nueva.

La duda es muy entendible y para solucionarla te recomiendo dos opciones:

1. Hacer que tus `if/elif` comparen `strings` en lugar de `ints`:

```
if opcion == '1':
     #hacer algo
elif opcion == '2':
    #hacer otra cosa
```

1. Otra forma de hacer es checkear que el input sea correcto y una vez que sepas que es correcto usarlo en tu ifs de la misma forma que lo estas haciendo:

```
if opcion not in range(0, n_opciones):
    #hacer algo 
else:
    if opcion == 1:
         #hacer algo
    elif opcion == 2:
        #hacer otra cosa
```

Una forma más bonita de escribir lo mismo sin tanta indentación:

```
if opcion not in range(0, n_opciones):
    #return "Error", hacer break o algo que evite que el código siguiente corra
if opcion == 1:
    #hacer algo
elif opcion == 2:
    #hacer otra cosa
```

Éxito!!!
