### ISSUE TITLE
Duda respecto a la ubicación de los archivos .csv

### ISSUE THREAD

**Issue by CGR0** [IIC2233/syllabus#150]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! Se pueden tener los archivos .csv dentro de un sub/directorio que se ubica en el mismo directorio de la tarea 0_
[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by RafaelEdwards** [comment]
Hola!

No hay problema con que incluyas los archivos en una carpeta dentro de tu tarea. De hacerlo así es importantísimo que lo indiques en tu README para que el ayudante que corrija tu tarea no tenga problemas con la ruta de los archivos a la hora de correr tu código. Esto ya se mencionó en la issue #55, por lo que para la próxima intenta revisar el compilado de issues :).

Éxito con tu tarea!

**Comment by CGR0** [comment]
Muchisimas gracias!
