### ISSUE TITLE
Problemas con repositorio, se borra solo y aparece como corrupto

### ISSUE THREAD

**Issue by fddelabarra** [IIC2233/syllabus#151]
He tenido problemas con el repositorio, he copiado la carpeta data en mi repositorio privado, luego cuando vuelvo a encender el computador y entro a la carpeta, la carpeta esta vacia, segui copiandolo, ya que pense que solo era un error, pero siguio sucediendo.
Luego intente subir los archivos mediante el bash a github, pero no me dejaba, me decia que el archivo estaba corrupto, luego se me borro todo el codigo que tenia hecho, no supe recuperarlo, asi que empece de nuevo, pero esta vez subi de inmediato lo poco que tenia.
Ahora volvi a meterme al repositorio desde el pc despues de que mi computador se suspendio un rato, pero cuando entro, mi repositorio clonado estaba vacio, use git status, y me salio que no era repositorio ya que no poseia el archivo .git/, en resumen se borro todo nuevamente (esta vez el repositorio completo, ya no se que hacer, ni que pasa
Que debo hacer en esta situacion? si sigo avanzando el la tarea solo se borrara todo de nuevo

**Comment by naquiroz** [comment]
Hola! Podrías colocar el mensaje de error que aparece en tu consola?

**Comment by fddelabarra** [comment]
Emm despues de eso solo borre el repositorio y lo clone de nuevo, ahi funciono, subi lo poco que hice para asegurarme, pero ahora solo se borro todo, no me ha vuelto a aparecer nada :/

![error](https://user-images.githubusercontent.com/42189391/55678285-170c6280-58c5-11e9-937e-f6eedeb5edf6.jpeg)

**Comment by naquiroz** [comment]
oka! y la foto que adjuntaste fue de el repositorio anterior?

**Comment by fddelabarra** [comment]
si!, el repositorio de ahora solo esta vacio y me dice que no es repositorio por que no tiene el .git/
el anterior lo borre, ya que de todos modos se borro todo lo que habia hecho :(
solo espero que no se vuelva a borrar, volvi a clonarlo recien

**Comment by jmwielandt** [comment]
Partamos por algo simple, qué sistema operativo tienes, versión completa, y en qué path estaba el repositorio cuyo contenido se te borró?

**Comment by fddelabarra** [comment]
emm la verdad no se mucho de eso, pero creo que te refieres a que uso Windows 10(?)
y con version, te refieres al pc?
el PATH seria D:\2019 Primer Semestre\Programacion avanzada\fddelabarra-iic2233-2019-1\Tareas\T01
eso?, lo tengo en un pendrive, ya que mi computador no tiene mucha memoria libre :( (tiene como 3 GB libres) :/

**Comment by jmwielandt** [comment]
Dime que no extraes el USB de forma no segura (sin darle a la opción, en la barra de tareas), pls...

**Comment by fddelabarra** [comment]
no lo hago!!! siempre lo hago de manera segura, y si no me deja le pongo expulsar desde disco local C, ahora no se si es normal, pero cuando el pc se suspende, y luego vuelvo a entrar, se abre la carpeta como si se hubiera desconectado, eso es malo? (lo hace el computador solo :( )

**Comment by Arcoirisky** [comment]
Si usas windows10 activa la casilla para ver archivos ocultos con tu pendrive conectado! Deberías poder encontrarlo fácilmente entre las opciones del buscador de archivos O:!

Cuéntanos si aparece algo!

**Comment by fddelabarra** [comment]
es que como dije, ya borre el repositorio anterior :(, en todo caso intente usar la consola de git bash y use ls -a, pero no aparecia nada :(

**Comment by Arcoirisky** [comment]
Si es que no haz formateado el pendrive donde tenías todo tu repositorio puede que estén como archivos ocultos. Además, hay un programa con el cual puedes recuperar archivos de tus pendrives (yo lo he usado y si funciona) se llama Recuva. 

Igual la idea es que recuperes tu tarea ;—;

**Comment by fddelabarra** [comment]
jajaa ya casi recupere todo (de casualidad tenia unos pantallazos :') ) gracias igual, solo queria evitar que pasara de nuevo por eso queria saber por que ocurria lo de "archivo corrupto" :(

**Comment by Arcoirisky** [comment]
Aaah, que bueno que recuperaste tu tarea 😰

A veces solo son virus que tienen los pendrives o archivos que bajas y contaminan todo ;—;

 A mi me pasó en intro :( Toda mi tarea.py aparecía en blanco aun cuando el tamaño del archivo no era de 0. Luego simplemente desaparecían ;—; Ahí conocí los archivos ocultos y aunque me salía archivo corrupto podía ver su interior. Así que con copy paste a otro módulo salvé para luego salvar lo que pude cual titanic y limpiar mi computador más los pendrives. 

De todas formas, anda con cuidado :eyes: sube todo y siempre usa la consola de git tanto para el pull como para el push con el pendrive bien conectado 😱

**Comment by fddelabarra** [comment]
Gracias :D para la próxima haré eso >~<

**Comment by fddelabarra** [comment]
mu computador se suspende, vuelvo a entrar y se borro nuevamente el repositorio :( esto ya me esta hartando :'(

**Comment by Arcoirisky** [comment]
Ya lo intentaste con el repositorio en una carpeta local? Aunque tu computador no tenga casi nada de memoria. 

Creo que podría ser que tu pendrive ya pasó a mejor vida. 

Si el problema te persiste en local, piensa seriamente en el formateo :( Tendrás más espacio pero instalarás todo de nuevo ;—;

**Comment by fddelabarra** [comment]
si, eso iba a probar ahora U_U maldito pendrive :'( era nuevo

**Comment by jmwielandt** [comment]
Cuál es la capacidad de tu disco/ssd?
Y desactiva la suspensión de tu equipo, al menos mientras tengas este problema.

**Comment by fddelabarra** [comment]
disco/ssd? te refieres al dico local C? es de 118 GB
No se que es eso de suspension :(, lo siento no se mucho de computadores :c

**Comment by Arcoirisky** [comment]
https://www.aboutespanol.com/activar-o-desactivar-la-hibernacion-en-windows-10-3507818

Aquí habla de la hibernación pero también está la opción de suspensión O:

**Comment by fddelabarra** [comment]
ah! lei mal jajajja, ya entendi, lo siento, gracias!!
