### ISSUE TITLE
Librería Intertools

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#151]
Hola!!

¿Está permitido utilizar la librería intertools?

Gracias :)

**Comment by dchahuan** [comment]
Te refieres a itertools o intertools?

**Comment by amahns1** [comment]
Itertools, discupla.

**Comment by dchahuan** [comment]
Este estilo se responden en la issue de librerias donde tienes que poner que que libreria quieres usar y para que

**Comment by dchahuan** [comment]
Asi puedan revisar bien si se puede o no

**Comment by amahns1** [comment]
Vale gracias!
