### ISSUE TITLE
Pequeño error 

### ISSUE THREAD

**Issue by valerojasm** [IIC2233/Syllabus#151]
Estoy probando mi método agregar planeta, de mi clase galaxia. Esta función agrega un planeta a un dict que tengo con ellos (los keys son el nombre y su value es una instancia de planeta), sin embargo al correrla me sale el siguiente error:

```python
Traceback (most recent call last):
  File "prueba2.py", line 90, in <module>
    dict_galaxias2["Andrómeda"].agregar_planeta(venus, asesino)
NameError: name 'venus' is not defined
```

dict galaxias es un diccionario con la misma forma, key es el nombre y value una instancia de galaxia, y mi agregar planeta efectivamente recibe solo dos argumentos (o 3, pero el otro está seteado). Qué puedo hacer? Busco pero me quedé pegada. Gracias!

**Comment by hanavarrete** [comment]
En base al error que muestras, no tienes definida la **_variable_** "venus". Estás llamándola bien? Tal vez quieres que en vez de ser una variable sea un **_string_**. Saludos

**Comment by valerojasm** [comment]
Oh sí es que lo probe con strings, pero me tira este:

```
  File "prueba2.py", line 90, in <module>
    dict_galaxias2["Andrómeda"].agregar_planeta("venus", "asesino")
  File "prueba2.py", line 19, in agregar_planeta
    if planeta != nombre and planeta["galaxia"] != nombre:
TypeError: string indices must be integers

```
y ese nombre que recibe sería venus

**Comment by hanavarrete** [comment]
Ahora tienes otro error, estás indexando planeta con una _**key**_ cuando no puedes hacer eso en un _string_. Por ejemplo, dado que planeta es un _string_, perfectamente puedes realizar la comparación: 
```python
planeta != nombre
```
Ahora, no puedes tratarlo como tratas usualmente a tus diccionarios, es decir: **NO** puedes realizar:
```python
planeta["galaxia"]
```

Pero **SI** puedes hacer:
```python
planeta[0:-1]
```
dado que son solo índices.
