### ISSUE TITLE
PROTIPS README

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233/Syllabus#151]
¡Hola! Algunos de ustedes han preguntado acerca de qué deben poner en el **README**. Éste se pide para darles una oportunidad de clarificar sus decisiones de modelación y especificar cosas que no estaban en el enunciado. De esta forma, facilita la corrección por parte de los ayudantes (generalmente, a mejor calidad de README, menor probabilidad de entrar a luchar en recorrecciones). Aquí van algunas recomendaciones:

**Dejar claro lo que NO pudieron implementar y lo que no funciona a la perfección. Esto puede sonar innecesario pero permite que el ayudante se enfoque en lo que sí podría subir su puntaje.**

- No explicar cómo se les ocurrió hacer lo que sí funciona, a menos que hayan asumido cosas que no estaban en el enunciado y deban especificarlas.
- Si hay algún pedazo de código relevante,  y que creen que podría ser necesario una explicación de su lógica, darla.
- Si su repo está desordenado o la modularización no es clara, pueden poner una descripción muy breve de lo que contiene cada módulo.
- Sean concisos, pero que no falte nada.
- Siempre se agradece el uso del humor.
- Por último, recordar que el README no es un archivo .txt, sino .md, lo que significa que pueden agregarle distintos estilos (colores, destacados, tablas, código). [Les recomiendo este editor](http://dillinger.io/)

**EXTRA:** si van a explicar qué hace especificamente un método, no lo coloquen en el README mismo. Pueden hacerlo directamente comentando el método en su archivo. Por ejemplo:

```python
class Corrector:

    def __init__(self):
          pass

    # Este método coloca un 1 en las tareas que recibe
    def corregir(self, tarea):
        tarea.nota  = 1 
        return tarea
```

Si quieren ser más formales, pueden usar alguna convención de documentación. Google tiene la suya, Python tiene otra y hay muchas más. La de Python es la [PEP287, conocida como reST](https://www.python.org/dev/peps/pep-0287/). Lo más básico es documentar así:

```python
def funcion(argumento):
    """
    Mi función hace X con el argumento
    """
    return argumento_modificado
```
Lo importante es que expliquen qué hace la función y que si saben que alguna parte puede quedar complicada de entender o tienen alguna función mágica usen los comentarios/documentación para que el ayudante entienda sus intenciones.

**Comment by hanavarrete** [comment]
@MrEarle
