### ISSUE TITLE
Menú de compra de vehículos

### ISSUE THREAD

**Issue by mimadri** [IIC2233/syllabus#151]
Hola! 
En el menú de compra de  vehículos dice "debe tener la opción de comprar uno de los vehículos o de regresar al menú de inicio." Con menú de inicio se refiere al menú principal o al menú de sesión?

**Comment by lily416** [comment]
Se refiere al Menú principal.

Saludos y éxito en la tarea 👋🚗

**Comment by mimadri** [comment]
Gracias!
