### ISSUE TITLE
Modificación dificultad Arena normal

### ISSUE THREAD

**Issue by AndreaPGS** [IIC2233/Syllabus#151]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evXaluación puede ser considerado una falta a la ética.

### Duda

Hola, a la hora de ponderar la dificultad de la arena normal (4.2.1 del Enunciado) por POND_ARENA_NORMAL al **cavar**, cuando se dice "cavar", ¿se refiere al evento de **Cavar dentro de la opción de Simular Torneo** o la **característica de Cavar de cada excavador**? En ambos casos, ¿el valor nuevo de la dificultad se debe guardar y volver a recalcular cada vez que se cave (o sea que por cada día o cada excavador que cave disminuirá hasta terminar le torneo si la arena sigue siendo la misma) o simplemente se conserva constante al transcurrir los eventos?

**Comment by Rotopikus** [comment]
Hola!!!

La dificultad de la arena se utiliza para calcular la metros de arena que un excavador puede cavar. Pero tiene sentido que este valor se mantenga constante si el tipo de arena puede cambiar?

Si te queda alguna duda con la explicación, no dudes en preguntar. Éxito!!

**Comment by vicenterodas** [comment]
No me quedó clara la respuesta para la segunda pregunta del compañero. 
Puedo asumir que se multiplicara por el ponderador cada vez que un día inicie con el mismo tipo de arena que el día anterior (refiriéndome al caso de la arena normal), ya que en el enunciado no se encuentra especificado.

**Comment by Rotopikus** [comment]
Hola!!!

Puede que te estes sobrecomplicando. La idea es que al inicio de cada día calcules la dificultad de la arena. Es un valor independiente al de los días anteriores. Puedes verlo como una especie de "reseteo".

Si no te queda claro, no dudes en preguntar.
