### ISSUE TITLE
duda agregar un prograpost

### ISSUE THREAD

**Issue by MariaBarias** [IIC2233/syllabus#151]
Hola :)
quería saber bien cual sería el formato para agregar un prograpost.

este debiera venir tipo "nombre,00/00/00,Textooooo" como estan en el archivo post.csv? o solo escriben post?

graciaaas

**Comment by jeschuwirth** [comment]
Hola @MariaBarias,

Cuando se crea un prograpost este se debe guardar del mismo modo que los demás posts. De ese modo puedes cerrar el programa y luego volver a correrlo con el nuevo post creado.

Éxito!
