### ISSUE TITLE
Dudas sobre corrección de Tarea

### ISSUE THREAD

**Issue by diegocostares** [IIC2233/Syllabus#151]
### Prerrequisitos
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
Hola revisando la pauta y los comentarios que me hizo el corrector de mi tarea 0 me surgió una duda, en los parámetros yo había importado la librería os para que el path a los archivos se cambiara dependiendo del sistema operativo, pero en la evaluación me descontaron puntos por hacer esto (sigo sin entender del todo por que esta mal) y me gustaría saber, ¿cual es la forma correcta de poner las rutas en parámetros, si quiero considerar que el programa se puede ejecutar desde distintos sistemas operativos? (O tal vez no debería ponerlo en parámetros, pero no se)

**Comment by matiasmasjuan** [comment]
Hola @diegocostares !

Tal como se mencionó en el enunciado, el objetivo del archivo ```parametros.py``` es indicar todos aquellos valores que se mantendrán **fijos** a lo largo de la ejecución del programa. Por lo tanto, no es correcto hacer uso de la librería ```os```, ya que el objetivo de este archivo es almacenar parámetros para luego ser importados y utilizados en el programa, sin contener librerías extras o lógica incorporada. Ahora bien, para poder almacenar correctamente los *paths* y que estos sean adapatables dentro de cualquier sistema operativo, lo recomendable es tener un parámetro que indique el nombre del archivo, y luego en **otro** módulo  del programa se importe este parámetro y se genere el *path* correcto a través de la librería ```os```. En caso de que el *path* del archivo sea una serie de directorios, se puede almacenar el valor del parámetro como una tupla separada por nombres de los directorios hasta el archivo. Luego, en otro módulo se deberá importar este parámetro y generar el *path* correspondiente con la librería ```os```.

Si consideras que la corrección de tu tarea fue incorrecta, puedes responder al formulario de recorrección ubicado en el anuncio de canvas.

Saludos!

**Comment by diegocostares** [comment]
Ahhhh yaaaa perfecto! Muchas gracias! 
y no creo que sea necesario mandar a recorregir en mi caso, hicieron buen trabajo 🙌🏻✨
