### ISSUE TITLE
Duda con clase programo y objeto

### ISSUE THREAD

**Issue by Couyoumdjian13** [IIC2233/Syllabus#151]
Holaa tengo una duda. No se como hacer para que cuando un programon se coma un tipo de objeto, le aumente la vida, ataque, etc.
Ya que tengo que hacer q la baya por ejemplo, le aumente un atributo (vida) al programon

**Comment by Emiliax16** [comment]
Hola @Couyoumdjian13 . Una forma simple de modificar un atributo es simplemente decir, por ejemplo, `instancia_objeto.atributo += n`. Esa es la manera más directa, combinado con el control de flujo correspondiente para que el atributo sólo se modifique cuando un programon se coma un tipo objeto. Sin embargo, en los contenidos se vio una mejor manera de tener un control de las modificaciones en los atributos, las denominadas **properties**. Te recomiendo fuertemente que leas a profundidad el contenido de la semana 2, te dejo el link aquí:
[https://github.com/IIC2233/contenidos/blob/master/semana-02/2-properties.ipynb](url)
Recuerda que esta es una manera segura de poder modificar los atributos de una clase y te permitirá ocupar los contenidos mínimos a evaluar para tu tarea. Saludos!! 😺
