### ISSUE TITLE
Subir un archivo de prueba de códigos en mi T1 (.gitignore)

### ISSUE THREAD

**Issue by mxmauoc0** [IIC2233/Syllabus#151]
* [ X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

***¿Puedo subir un archivo prueba.py en mi T1?*** 

En el archivo prueba.py probe códigos que luego utilice en mi dccultivo.py, puede que sea considerado importante. (no importe ninguna función desde prueba.py por lo tanto es totalmente funcional sin este archivo)
Me gustaría saber si por el contrario, es innecesario, y debo agregarlo al .gitignore

¡Muchas gracias!

**Comment by vicho14** [comment]
Hola!
Si el archivo fuese fundamental para tu entrega mientras lo menciones en tu README está bien, pero como me dices que es un archivo con funciones que probaste y luego las agregaste a dcccultivo.py me parece que no fuese tan necesario para la entrega en sí. En ese caso debieses agregarlo al .gitignore. Espero haberte ayudado :).

**Comment by mxmauoc0** [comment]
¡Gracias!
