### ISSUE TITLE
Duda sobre mensaje nuevo en el chat

### ISSUE THREAD

**Issue by fcontardo** [IIC2233/syllabus#151]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Al momento de generar un **nuevo mensaje** en un chat entre dos **usuarios**, e imprimir el **historial de chats**, NO me incluye el nuevo mensaje que acabo de escribir. 
Hay algo que pueda revisar o alguien con quien pueda hablar? 
He hecho debugs por harto rato sin poder encontrar el error.

**Comment by hsazos** [comment]
Hola @fcontardo !

Podrías subir a tu repositorio la última versión de tu código e indicarme por acá en que líneas crees que se encuentra el problema? Así podemos ver que onda los ayudantes.
