### ISSUE TITLE
Duda código C+I+A

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#151]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado se explica que el código C+I+A debe pasar al jugador al siguiente nivel. **¿Esto significa que no se va a ganar ningún punto ni nada del estilo por el nivel actual? Es decir, al no pasar por la ventana de postjuego no se tiene en cuenta esto, ¿cierto?**

**Comment by Emiliax16** [comment]
Hola @MaxAl100 . Al utilizar el cheatcode `C + I + A`, se debe mostrar la ventana post nivel con las estadísticas que se lograron calcular para ese momento. Saludos!
