### ISSUE TITLE
Fotos se ven en el Designer pero no en el programa de VSCode

### ISSUE THREAD

**Issue by paulmacguire** [IIC2233/Syllabus#152]
Hola!
He estado haciendo las ventanas en el Designer y me ha funcionado todo bien, sin embargo a la hora de importar los archivos .ui y correrlos en el prorgama, las ventanas contienen todo lo que les puse en el Designer menos las fotos y nose por qué pasa eso si a la hora de ejecutar la ventana en el Designer se ven todas las fotos y todo correcto.
Gracias de antemano :)

**Comment by diegocostares** [comment]
Puede deberse a la forma en que estás subiendo las fotos a designer, es un error bastante comun utilizar la opcion de "Recursos", pero esta siempre trae problemas en python, lo mejor es subir las imágenes como archivos directamente.
Otra opción es que estés moviendo la ruta de las imágenes, procura dejarlas en una carpeta designada y no moverla.

Me cuentas como te va!

**Comment by IgnacioHqz** [comment]
Hola, me sumo a la consulta anterior ya que si bien en QtDesigner se ve bien mi ventana diseñada, no se puede mostrar desde python, me dice que el nombre del recurso no existe. Si cargo las fotos como archivo como dices, cómo tendría que hacerlo? ya que si lo hago directamente desde "Abrir" me tira error. Gracias

**Comment by diegocostares** [comment]
@IgnacioHqz Es que hay dos formas de subir imágenes en QtDesigner, si lo estas haciendo con la opcion de `recurso`, no va a funcionar.

En esta imagen se ve que al apretar a la derecha aparecen dos opciones. Tienen que apretar la segunda opción.
<p align="center"><img width="325" alt="Captura de Pantalla 2022-05-10 a la(s) 2 42 30 p  m" src="https://user-images.githubusercontent.com/62116423/167699855-e90f42bf-ce1b-40e3-9260-959cb17bee0d.png"></p>

**Comment by IgnacioHqz** [comment]
Valee gracias te pasaste, ahora me funciona!

**Comment by ccellcynthia** [comment]
Hola, a mi me sigue sin funcionar, al tratar de abrir la ventana me dice que no existe un modulo, no sé a que se refiere.

**Comment by diegocostares** [comment]
@ccellcynthia usaste lo de cargar archivo como explique? si te aparece lo del módulo es porque creaste un recurso en designer
