### ISSUE TITLE
Guardado de archivos

### ISSUE THREAD

**Issue by meretamal** [IIC2233/Syllabus#152]
Hola!! Al guardar los archivos, pueden estar en el orden que quiera o tienen que guardarse en el orden del archivo original?

**Comment by Arcoirisky** [comment]
No está especificado en el enunciado, así que queda a tu criterio como guardar los archivos xD Si tu programa puede leerlos después de ambas maneras genial :D

**Comment by IchottMano** [comment]
@kenzoak Hola! 
Mientras tu programa pueda leerlo de ambas maneras, tu puedes guardar los datos como tu desees, sin embargo, debes tener en cuenta que el ayudante al momento de corregir tu tarea usará un csv con los headers de forma "nivel_ataque: int"
Saludos!
