### ISSUE TITLE
undergrade puede ser trader 

### ISSUE THREAD

**Issue by MatiasIgnacioGalleguillosCespedes** [IIC2233/Syllabus#152]
¿un undergrade puede convertirse a Trader cuando cumple la mayoría de edad, puede ademas tener dinero(pero no usarlo hasta ser mayor de 18 años ), cuando cumple 18 años, el sistema lo convierte automáticamente en Trader o tiene que pagar por ello  ?

**Comment by iqacevedo** [comment]
#82
