### ISSUE TITLE
Probabilidad_de_choque

### ISSUE THREAD

**Issue by JoseIgnacioGajardoRojas** [IIC2233/syllabus#152]
En la fórmula de probabilidad de choque,  ¿que es la durabilidad_actual_chasis si no este tiene fórmula de daño? Y si no es así ¿que es la durabilidad_máxima_chasis?.

**Comment by jmwielandt** [comment]
Hola!

La durabilidad máxima del chasis es la durabilidad que tiene el vehículo de base, pero agregando todas las mejoras que tenga a esta parte. Todas las carreras parte con la durabilidad al máximo.

Por otro lado, la durabilidad actual se corresponde a la durabilidad máxima menos el daño que haya ido recibiendo. Te pongo un ejemplo:

Imagina un troncomóvil que tiene:

|parte|nivel base|nivel mejora|
|------|-----------|-------------|
|chasis|24|5|
|carrocería|12|3|

Además:
```python
EFECTO = 2
cantidad_rocas = 150
```

La durabilidad máxima en este caso se calcula como 

durabilidad\_máxima = nivel\_base * EFECTO <sup>nivel\_mejora</sup>, que en este caso es 24 * 2 <sup>5</sup> = 768.

De la misma forma, la defensa\_carrocería = 12 * 2 <sup>3</sup> = 96.

Luego, usando la fórmula del daño recibido, nos da que recibe: daño\_recibido = 150 - 96 = `54` de daño. Por lo que en la primera vuelta recibirá 54 puntos de daño y la durabilidad actual en la segunda vuelta será 768 - 54 = 724.

Espero haberte ayudado.
Saludos!


PD: la fórmula del cálculo de daño tenía los valores intercambiados en el enunciado. Esta es la real:

![image](https://user-images.githubusercontent.com/37153467/64286944-6e723580-cf2c-11e9-9495-2fba5cb43880.png)

**Comment by dpacevedo** [comment]
Hola!

Ante esta respuesta me surgió una duda. Arriba se indica que todas las carreras parte con la durabilidad del chasis al máximo, eso alude a que el valor que tomar el atributo chasis de un auto, al iniciar una carrera, es igual a:
1. Valor calculado con los valores MAX y MIN de parametros.py
2. (Valor calculado con los valores MAX y MIN de parametros.py) * (EFECTO de chasis de parametros.py)

Si es la segunda fórmula indicada, el usuario al acceder a los pits y decidir mejorar el chasis, ¿ volvería a multiplicar la durabilidad máxima por el EFECTO?

En este mismo sentido, ¿la durabilidad_inicial de chasis es simplemente valor calculado con los valores MAX y MIN de parametros.py?

Gracias de antemano!! 😊

**Comment by jmwielandt** [comment]
Hola! 😄

Se calcula de la segunda forma que indicas, como mencioné antes. El valor de la durabilidad máxima se debe actualizar durante la carrera, en caso de que el jugador decida mejorar el chasis. Además, como al pasar por los pits se repara el vehículo, después del paso por estos `durabilidad_actual` = `durabilidad_máxima` (el valor nuevo).

 Y sí, el cálculo de la durabilidad inicial se hace con los valores MIN y MAX de parametros.py.


Saludos~

**Comment by mvaldes12** [comment]
Hola! leí todo pero no me quedó claro cual es chasis inicial, cual es el máximo y cual es el actual.
Del máximo tampoco entendí de donde salió esa formula porque no la encontré en el enunciado (ni qué es el nivel de mejora)
Muchas gracias

**Comment by fcartoni** [comment]
Hola! Qué es el nivel de mejora? De dónde sale? 
Gracias

**Comment by jmwielandt** [comment]
Hola!

@mvaldes12 
Cuando creas un vehículo usas alguna función random para determinar el valor inicial de las partes de este, en este caso, chasis inicial. El nivel máximo es el valor del chasis inicial pero considerando todas las mejoras que tenga. Si se ha mejorado 3 veces, tendríamos que el valor del chasis sería `chasis_inicial * (EFECTO ** 3)`.

<details>
<summary>El valor que obtiene chasis_inicial y la cantidad de mejoras que se aplican se explica en esta parte del eneunciado</summary>
<br>

![image](https://user-images.githubusercontent.com/37153467/64535803-4ac53b80-d2ee-11e9-8bdb-cdd2c323c878.png)

</details>

@fcartoni 
Nivel de mejora es una variable que uso para la explicación, solo eso. Representa la cantidad de veces que mejoras una parte del vehículo. Como por el enunciado, al mejorar una parte se multiplica el valor de esta por `EFECTO`, si se mejora 5 veces el valor de la parte se puede calcular como `valor_inicial * (EFECTO ** 5)`. Me disculpo si causó demasiadas confusiones.

De todas formas quiero aclarar que no es necesario que guarden el valor de `chasis_inicial` ni nada de eso, lo uso solo para esta explicación. Con que en su código hagan algo como:

```python
def mejorar(...):
    # ...
    chasis *= EFECTO
    # ...
```
