### ISSUE TITLE
Solicitud de publicar archivos de AY04 y E2

### ISSUE THREAD

**Issue by plourido** [IIC2233/Syllabus#152]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido

Hola que tal, espero que se encuentren bien. Les escribo para solicitarles si pueden publicar en el syllabus la experiencia 2 (E2) y Ayudantía 4 (AY04) por favor.
Muchas gracias de antemano :)

**Comment by Hernan4444** [comment]
Ups, lamentamos lo tardisimo de la respuesta, pero ya están publicadas 😅 (se hizo el día que hiciste la issue, pero olvidamos avisarte en esta issue 😞 )

Saludosヾ(＾-＾)ノ
