### ISSUE TITLE
Pep8

### ISSUE THREAD

**Issue by ticastro** [IIC2233/syllabus#152]
Hola!
Dudo sobre el pep8. Los comentarios cuentan dentro de los 80 caracteres máximos o son una excepción ?

Gracias de antemano

**Comment by hbkim94** [comment]
Hola!

Es buena costumbre que los comentarios también sigan el formato de pep8. Así se ve bonito y ordenado.

Ánimo!!

**Comment by flogaido** [comment]
Van a descontar si los comentarios son mas largos que 80 caracteres?

**Comment by Hernan4444** [comment]
Hola, tal como sale en el link indicado anteriormente (https://www.python.org/dev/peps/pep-0008/#maximum-line-length), el máximo de línea también considera  los comentarios, por lo tanto que sean más largo de 80 caracteres implica no respetar pep8 y podrá llegar a ser descuento.

Saludos

**Comment by Oisangui** [comment]
Los 80 caracteres se cuentan desde el comienzo de línea o desde que se empieza a escribir?
```python
'''soy una linea de 36 caracteres'''
          '''soy de 47 caracteres o de 57 caracteres??'''
```

**Comment by Hernan4444** [comment]
Desde el comienzo de una línea

Saludos ✌️
