### ISSUE TITLE
Doble oportunidad de disparo

### ISSUE THREAD

**Issue by jarvasquez** [IIC2233/syllabus#152]
Hola!

En el enunciado dice que cuando el jugador da con un barco del oponente puede volver a lanzar otra bomba. Para el oponente (el bot) ¿también debe cumplir esta regla?

**Comment by josefinareyes** [comment]
Hola! El bot oponente sigue las mismas reglas que el jugador (a excepción de las bombas especiales), por lo que debería volver a lanzar una bomba si da con un barco del jugador!

**Comment by jarvasquez** [comment]
Gracias!
