### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by ElTurkos** [IIC2233/syllabus#152]
![Captura](https://user-images.githubusercontent.com/62064830/77230442-f0e1e000-6b72-11ea-87c9-d6cd9b115de7.PNG)

**Comment by entamburini** [comment]
Hola @ElTurkos, 

Algún comentario a veces ayuda para ayudarte a superar el error :sweat_smile:. El error que tienes es un error de codec, quizás probando con otro te ayude (latin-1?). Si dices qué intentas hacer podamos ayudarte más.

Saludos! :v:

**Comment by ElTurkos** [comment]
se arreglo usando latin-1. Gracias!!!!

**Comment by entamburini** [comment]
no problemo! :+1:
