### ISSUE TITLE
Error de PyQt6 - Contenidos semana-04

### ISSUE THREAD

**Issue by vichoassadi** [IIC2233/Syllabus#152]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola. Al momento de ejecutar los archivos de la carpeta ```scripts``` de la semana-04, me tira este error (tengo PyQt6 instalado correctamente, se supone). **Cómo lo arreglo?**
Gracias.

![image](https://github.com/IIC2233/Syllabus/assets/133837937/47cc0f43-4ba4-4dd7-897f-c374d5c3d0bf)

**Comment by Hernan4444** [comment]
Hola @vichoassadi 

Recuerda que las reglas del foro indican que primera busques entre las issues si alguien ya preguntó por esto mismo (y el segundo checkbox es justamente recordarles sobre la busqueda entre las issues). Recalco esto porque justamente el error que indicas fue expuesto en la siguiente issue:
* https://github.com/IIC2233/Syllabus/issues/131

Y la idea no es duplicar las issues 😄 
Saludos!

**Comment by vichoassadi** [comment]
Upss mala mía, no la había encontrado. Gracias!
