### ISSUE TITLE
¿Puedo utilizar otros parámetros en Parámetros.py?

### ISSUE THREAD

**Issue by cegalleta** [IIC2233/syllabus#152]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!
Ya "terminé" la tarea, sin embargo, no entiendo muy bien qué hacer con parametros.py. ¿Hice toda la tarea con 0 para volver y -1 para abandonar, entonces debiese reemplazar por esos valores el parámetros.py y los lugares donde se instancian 0's y -1's? ¿En ese caso lo anoto en el README y lo saco del .gitignore? Con los valores del parametros.py no me corre bien el código :(

**Comment by RafaelEdwards** [comment]
Hola!

Recuerda que en vez de 0s o -1s debías importar parametros.py y utilizar VOLVER_FRASE y ABANDONAR_FRASE. Lo que hiciste ahora fue "hardcoderalo" (lo contrario a parametrizar), por lo que tendrías un descuento en tu tarea. Para no tener este descuento cambia los 0s y -1s por sus parámetros respectivos, de tal forma en que sea posible cambiar las palabras claves directamente desde parametros.py. 

Espero haberte ayudado y suerte con tu tarea :).

**Comment by cegalleta** [comment]
Muchas gracias :)
