### ISSUE TITLE
asignar clase a una copia sin cambiar la original 

### ISSUE THREAD

**Issue by menorq3** [IIC2233/Syllabus#153]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola, mi duda es si es posible asignarle la clase a una lista copia de la original sin cambiar la original:
original=self.tablero.copy()
tablero_2=Tablero(original)
tablero_2.tablero[0][0]="hola"
y que self.tablero siga siendo igual (sin "hola"), de antemano muchisimas gracias <3

**Comment by roahoki** [comment]
hola @menorq3! te recomiendo que investigues el uso de la libreria copy de python para que puedas ocupar una copia sin referenciar a la original y de esa manera no tengas problemas.
