### ISSUE TITLE
Probabilidad de accidente

### ISSUE THREAD

**Issue by anvaldes** [IIC2233/syllabus#153]
1. La probabilidad de accidente no debe estar entre 0 y 1? No faltaría algo del tipo si es menor que 0 entonces que sea 0 y si es que es mayor que 1, entonces que sea 1?

2. En la sección de calcular la probabilidad de accidente. La durabilidad máxima chasis es la máxima capacidad del chasis que ha tenido el auto en toda su historia, en la carrera o el valor máximo que puede tener ese parámetro?

**Comment by jmwielandt** [comment]
Hola!

Muchas gracias por tu observación. Corregiremos el caso en el que la fórmula de un valor no acotado por _[0, 1]_.

El resultado es este:

![image](https://user-images.githubusercontent.com/37153467/64287764-92367b00-cf2e-11e9-80e3-2baa7a6ba30a.png)


La idea es que el ir más lento no compense el hecho de que la durabilidad llegue a cero.

Tu segunda pregunta fue contestada en #152 

Saludos y nuevamente, muchas gracias!
