### ISSUE TITLE
Propagacion y cura

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#153]
Preguntas:

1) Cuando uno selecciona un país para comenzar a propagar la infeccion, ¿como se determina el numero de contagiados para ese primer dia?

2) Sale que que una persona puede contagiar de 0 a 6 personas por día, y sale también que ese numero se multiplica por 0,3 en caso de uso de mascarillas y por la tasa de contagiosidad, pero ¿que me da ese calculo? ¿el numero final que contagia la persona ese dia? ¿que pasa si es decimal?

3) Sale que la probabilidad de que una persona muera depende de la tasa de mortalidad del pais y de los dias que lleva ese virus en el país, nada en relacion a la person. ¿Esta bien eso?

4) ¿El progreso de la cura se refiere a su elaboración y por tanto no su propagación o a su propagación y por tanto se elabora instantáneamente?
En caso de ser cualquiera de las dos formas, ¿Como se propaga la cura si pensamos que avanza de país en país? ¿o de que forma influye la cura en el contra-ataque de la enfermedad?

5) ¿Las acciones del gobierno son solo cuando saben de la enfermedad o pueden ocurrir igual sin que sepan?

**Comment by arturodelreal** [comment]
1. se parte con un infectado.
2. El resultado representa el numero de personas que contagia una persona, si el numero da decimal queda a tu criterio lo que haces (#145).
3. Si.
4. Hubo un cambio en el enunciado donde se especifica esto.
5. Solo ocurren estos cambios una vez descubierta la enfermedad. 
saludos
