### ISSUE TITLE
Orden archivo acciones

### ISSUE THREAD

**Issue by matioprts** [IIC2233/syllabus#153]
Hola! Mi programa lee el archivo acciones guiándose por los headers, debido a que tengo entendido que modificaran las columnas, pero, ¿modificarán también las filas? Esto debería ser irrelevante en el caso de los archivos edificios y civilizaciones, pero en el caso de acciones es un poco distinto debido a que imagino que las acciones deben ser seguidas en el orden que nos las entregan, vale decir, por sus filas. Mi forma de leer este archivo contiene un sort para facilitar el popleft. Pero el sort me los ordena en un formato [turno, id, ....] vale decir, [1,0, ....] va antes que [1,1, .....] y este va antes que [1,2, ....]. Si reordenan las filas y yo aplico el sort, quizas estoy ejecutando un [1,0,....] antes de un [1,2,....] que por el orden modificado de filas que podría entregar el archivo, debería ir primero. Gracias de antemano!

**Comment by lily416** [comment]
Hola :)

Se habló de tu duda en esta issue #62. 👀 
**Recuerda leer las issues anteriores.** Si tienes más dudas del mismo tema, hazlas en esa issue para mantener el hilo del tema y no tener diferentes issues sobre el mismo tema. 😉 

Saludos y éxito con la tarea. 👋 🏰
