### ISSUE TITLE
importar modulos

### ISSUE THREAD

**Issue by TriniVial** [IIC2233/syllabus#153]
hice tres modulos uno para cada menu, pero cuando los importo más de una vez se termina de ejecutar el programa. que puedo hacer?

**Comment by gatochico** [comment]
Hola! ¿Cómo estás importando los módulos? ¿Haces un `import modulo.py` cada vez que necesitas dicho módulo y por ende, hay más de un import por módulo? 

Si es así, ese podría ser el problema, ya que solo necesitas importar un módulo **una sola vez** en tu programa principal. Si quieres llamar a sus contenidos más de una vez, deberías transformar dichos menús en una función y llamar a **la función** múltiples veces cada vez que sea necesario.

Si no es así y solo estás importando cada módulo 1 sola vez, podrías subir tu código al repositorio para mirarlo?

Quedamos atentos! 🤓

**Comment by TriniVial** [comment]
gracias!
subi el codigo a mi repositorio

**Comment by gatochico** [comment]
Revisando tu código, de forma preliminar hay 3 problemas importantes que pueden ayudar a resolver tu error:

1) Tienes módulos importandose entre ellos (menu_de_inicio importa a menu_de_seguidores y menu_de_posts, y tanto menu_de_posts como menu_de_seguidores importan a menú de inicio.). Esto es modelación circular, lo que es considerado mala práctica y puede traer errores en el funcionamiento del código. Debes ver bien el modelamiento de tu programa y elegir qué modulos importarán a otros según el flujo principal de este.

2) El código termina de ejecutar ya que no estás definiendo bien los ciclos. Por ejemplo, la parte del código que se activa cuando inicias sesión y eliges ir a un menú no está dentro de ningun ciclo, y por ello el código termina cuando se sale de los otros submenús, ya que no hay nada en el código del menú principal que haga que se repita/vuelva a pedir input. (Revisar líneas 60 a 77 de menu_de_inicio.py)

3) Cada uno de tus módulos tiene un flujo principal, en vez de estar encapsuladas en funciones que puedas llamar múltiples veces. Esto tiene que ver con lo que indiqué en el comentario anterior: Si hay un código de un módulo que quieres usar múltiples veces (como los submenús de seguidores y de posts), no debes importar dicho modulo cada vez que lo quieras usar. Lo que debes hacer es encapsular el código que quieres reutilizar en una función, importar 1 sola vez el módulo en tu codigo principal, y llamar a dicha función las veces que quieras. Esto lo digo por las líneas 70-74 de menu_de_inicio.py

En resumen, tienes que echarle una revisada a tu flujo principal que es el que posee errores. Piensa cuales ciclos deben repetirse, qué cosas deben ser encapsuladas en funciones, y trata de reorganizar eso.

Espero haberte ayudado! 💪

**Comment by TriniVial** [comment]
Muchas gracias!!!!!!!! te pasaste
