### ISSUE TITLE
Como hacer que mi codigo reiba tildes correctamente? (en vez de "QuÃ© tal?")

### ISSUE THREAD

**Issue by airiquelme** [IIC2233/syllabus#153]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Cuando cargo el archivo mensajes, me lo devuelve sin los tildes, y en vez de eso unos caracteres raros, que hago?

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by matiasmasjuan** [comment]
Hola @airiquelme !

Esta pregunta fue respondida en la ***issue*** #97 .

Saludos! :smile:

**Comment by airiquelme** [comment]
Gracias!! Y eso q había buscado si había un issue así antes :(

**Comment by matiasmasjuan** [comment]
Recuerda que puedes revisar el **Compilado de Issues** #45 para buscar de forma más rápida y ordenada.

Saludos! :smile:
