### ISSUE TITLE
Funcionalidad registro de orders

### ISSUE THREAD

**Issue by jerosalazar** [IIC2233/Syllabus#153]
En el enunciado, dentro de funcionalidades aparece el siguiente punto:

> Lista de orders: Se deberá dar la opción de desplegar en consola, de forma ordenada, una lista de todos los orders del día, una fecha específica, entre dos fechas o de un mercado en particular.
>
Pero, en el apartado de usuarios, dice que los usuarios _Trader_ solo pueden acceder al registro de _orders_ de los últimos 7 días.
Con respecto a estas 2 instrucciones, ¿un _Trader_ debe poder ver solamente _orders_ en fechas posteriores a los 7 días indicados o debe ser posible que ingrese otro periodo de tiempo/ fecha específica?

**Comment by cilopez** [comment]
Respecto a tu primera duda, tu programa debería avisarle a los usuarios *Trader* que su consulta no se puede realizar si la fecha está mas allá de los últimos siete días.

**Comment by jerosalazar** [comment]
Reitero, debe mostrar las activas, las que han hecho match o ambas?
