### ISSUE TITLE
Duda caso extremo en función buscar_y_plantar

### ISSUE THREAD

**Issue by Igufu** [IIC2233/Syllabus#153]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Saludos!, Tengo una pregunta respecto a varios casos extremos en la función `buscar_y_plantar`. El tema es que mi función ocupa un algoritmo de complejidad alrededor de `O(n^4) + O(n^2)` y en casos donde el alto y el ancho exceden las 500k unidades, la función tardará más de 10 segundos. 

Mi duda es si pongo el item como incompleto o no, ya que no soporta (en tiempo realista) casos donde el cultivo a plantar es más de 500000*500000 unidades, y tuve que acotar la función retornando falso.

Gracias!

**Comment by FernandoTFH** [comment]
Te recuerdo que esta tarea es conocimiento de introducción a la programación, es decir que no se te va a exigir que tus programas tengan complejidad o(n), el tema del tiempo es para que tus algoritmos no sean de complejidad o(n!). En general siempre se va a probar con valores "normales".  Si se quisiera usar input grandes y que el algoritmo lo haga en poco tiempo, se te indicará que debes usar numpy o otra librería enfocadas en la optimización.
Si tu algoritmo para un input razonable funciona bien, entonces está bien.

**Comment by Igufu** [comment]
Gracias por resolver mi duda! :)
