### ISSUE TITLE
Menu del Juego - Opción salir

### ISSUE THREAD

**Issue by ignaciovilla** [IIC2233/syllabus#153]
Hola, si el usuario elije la opción salir del juego, se debe calcular su puntaje igualmente, o se acaba la ejecución del código sin guardar su puntaje?
Muchas gracias

**Comment by jitorralba** [comment]
Hola @ignaciovilla!
En la sección **Puntajes** se detalla que sólo se actualiza cuando hay victoria, derrota o el usuario se rinde, por lo tanto, como no se detalla la opción **Salir**, esto no es necesario, si decides hacerlo recuerda mencionarlo en tu README.
Éxito en tu tarea!

**Comment by ignaciovilla** [comment]
Muchas gracias!
