### ISSUE TITLE
Duda Layouts

### ISSUE THREAD

**Issue by TTrincado** [IIC2233/Syllabus#153]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, quería preguntar si era necesario el uso de layouts, si se iba a evaluar que cuando se agrandara la ventana a pantalla completa los widgets debían ajustarse de manera que quede proporcional.

**Comment by diegocostares** [comment]
Hola! En primer lugar, te recomiendo siempre revisar la distribución de puntajes de las tareas.
Ahora, respondiendo a tu duda, quedas libre de hacer las ventanas como quieras, tienes libertad creativa (Así que si decides definir un tamaño fijo para tu ventana, adelante). 

Pero por ejemplo, puedes poner los layouts para centrar tu ventana y "encerrar" el espacio de juego con un QWidget o con un QFrame que tenga un tamaño fijo, así cuando pones la pantalla completa, el cuadrado que encierra estos elementos quedara centrado y con un tamaño fijo. Te recomiendo probar y buscar en Google otras alternativas. 👽
