### ISSUE TITLE
Restauración de la energía de los contrincantes

### ISSUE THREAD

**Issue by gabo1243** [IIC2233/Syllabus#154]
### Duda

Hola, en el enunciado aparece que cuando finaliza una ronda, la energía de los entrenadores vuelve al máximo, lo que tiene sentido para el entrenador del jugador, pero para los entrenadores contrincantes no me hace mucho sentido ya que estos nunca pueden gastar energía. Mi pregunta es si ¿Es necesario cambiar la energía de los entrenadores contrincantes también o puedo solo cambiar la del jugador?
Gracias de antemano

**Comment by Amandasandov** [comment]
Hola, lo importante es que cada vez que comienze una nueva ronda todos los entrenadores tengan los valores iniciales dados en los archivos. Si en ningún momento del campeonato cambia la energía del contrincante, entonces no es necesario cambiarla.

**Comment by bernirosas** [comment]
> 

Hola

> Hola, lo importante es que cada vez que comienze una nueva ronda todos los entrenadores tengan los valores iniciales dados en los archivos. Si en ningún momento del campeonato cambia la energía del contrincante, entonces no es necesario cambiarla.

Hola! En otro issue pusieron que los valores de energía se restauraban a 100!
