### ISSUE TITLE
Daño a los vehiculos

### ISSUE THREAD

**Issue by anvaldes** [IIC2233/syllabus#154]
El daño a los vehiculos solo se da en pistas rocosas?

**Comment by jmwielandt** [comment]
Hola!

Se da en pistas rocosas y supremas (en las pistas que tienen rocas).

Saludos!

**Comment by mvaldes12** [comment]
Cuando se usa esta formula? No está relacionada con niguna otra

**Comment by jmwielandt** [comment]
Hola @mvaldes12 

El daño al vehículo debe calcularse durante cada vuelta, tal y como indica el enunciado.

![image](https://user-images.githubusercontent.com/37153467/64627334-ce059080-d3c5-11e9-8cde-a23081a1eeec.png)

Calcularlo y aplicarlo al chasis antes o después del cálculo de probabilidad de accidente queda a su criterio, pero **deben** especificarlo en su readme.

Saludos 😄

**Comment by pazanelli** [comment]
Hola, sobre los accidentes, el código debe realmente hacer que el chasis sea 0? No basta con descalificar al jugador de la carrera. Pregunto porque tengo entendido que al terminar la carrera y volver al menú principal, si quisiera guardar mi partida, el chasis se guardaría como si estuviera reparado e incluso con mejoras. También, los contrincantes no se editan por lo que me parece innecesario hacer que el chasis sea 0 si en una linea siguiente el chasis va a volver a la normalidad sin consecuencias

**Comment by jpperez5** [comment]
¿Como debo utilizar el valor de la probabilidad de accidente? Basta con que de un valor mayor a uno para que el accidente suceda o debo utilizar alguna otra librería como random?

**Comment by pvarela5** [comment]
¿Se le de debe dañar al vehiculo a los contrincantes en la carrera? Ya que estos no tienen oportunidad de ir a los pits tienen mas posibilidades de tener accidentes. Si no se les daña, entonces: ¿solo se pueden retirar tomando en cuenta la prob. accidentes relacionada con la velocidad?

**Comment by jmwielandt** [comment]
Hola @jpperez5 

Tal como indica el enunciado, deben usar alguna función de la librería random. Lo que recomendamos es que usen `random.random` ya que es el método más directo para este propósito.

Según cómo lo definas, según la comparación entre el valor aleatorio y la probabilidad de ocurrencia, el evento tendrá lugar o no.

![image](https://user-images.githubusercontent.com/37153467/64912969-bd2e8500-d70d-11e9-858c-b06440d9c32b.png)


Hola @pvarela5 

Eso también sale en el enunciado y fue respondido en la issue #125 . También se menciona algo sobre la entrada de los contrincantes a los pits.

Como mencioné en la issue #261 (aunque en el contexto de los parámetros), el balance del juego no es algo de lo que se deban preocupar, no es parte de la evaluación.

Saludos y ánimo con lo que queda~ 👍
