### ISSUE TITLE
Parametros indefinidos

### ISSUE THREAD

**Issue by aliciagarciadelah** [IIC2233/Syllabus#154]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]
En el enunciado, se menciona que los metros a cavar están definidos por **METROS_META**, sin embargo no se explicita como se define este parámetro.
Lo mismo pasa con los parametros ** FELICIDAD_ADICIONAL_DOCENCIO**, **FUERZA_ADICIONAL_DOCENCIO**, **ENERGIA_PERDIDA_DOCENCIO **, **ENERGIA_ADICIONAL_TAREO**, **SUERTE_ADICIONAL_TAREO**,**EDAD_ADICIONAL_TAREO **, **FELICIDAD_PERDIDA_TAREO**.

¿Como se definen?

**Comment by mpiavf** [comment]
Hola!! En el enunciado, en el apartado `parametros.py` se explica lo que pasa con los parámetros que mencionas. Tal como sale ahí, tú los completas con los valores que estimes conveniente. 
Saludos!

**Comment by tremendapithon** [comment]
Hola, tengo una duda con los parámetros en la clases de arena, esos pueden ser arbitrarios?? y lo otro, debo especificar esos valores?

**Comment by mpiavf** [comment]
Hola! Las características que tendrá cada arena las podrás encontrar en el archivo `arenas.csv` por lo que ya hay un valor dado para las características de cada arena. Ahora bien, en el archivo  `parametros.py` se deben especificar los parámetros que a lo largo del enunciado están en el formato ESTE_FORMATO, tal como dice el enunciado.
Si te quedo alguna duda no dudes en preguntar.
Saludos!

**Comment by BenzoylMorexide** [comment]
Hola! consulta, también tengo duda con los valores de las probabilidades para item. Puedo darle un valor arbitrario o debo crear un valor aleatorio para `prob_encontrar_tesoro` y `prob_encontrar_consumible` cada vez que quiero ver si cuál saldrá seleccionado?

**Comment by Benjeeeh** [comment]
Hola @BenzoylMorexide 
Ambos parámetros son determinados por ti, siendo importante que ambas probabilidades sumen 1, como lo dice el enunciado:
![image](https://user-images.githubusercontent.com/78326186/232260829-07f2c14a-8aa9-4b60-9674-8101d9782fec.png)
La idea es que elijas un número y según tu forma elegir en que probabilidad cae, determinar que tipo de ítem se obtiene, pero este número debe ser aleatorio cada simulación para que represente de buena manera la probabilidad. 
En resumen, los valores de prob_encontrar_tesoro y prob_encontrar_consumible son constantes ya que deben estar en **parametros.py**, y el número que determine en que probabilidad cae debe ser aleatorio cada simulación.

**Comment by BenzoylMorexide** [comment]
Vale, muchas gracias!

**Comment by Benjeeeh** [comment]
Hola @BenzoylMorexide 
Ambos parámetros son determinados por ti, siendo importante que ambas probabilidades sumen 1, como lo dice el enunciado:
![image](https://user-images.githubusercontent.com/78326186/232260829-07f2c14a-8aa9-4b60-9674-8101d9782fec.png)
La idea es que elijas un número y según tu forma elegir en que probabilidad cae, determinar que tipo de ítem se obtiene, pero este número debe ser aleatorio cada simulación para que represente de buena manera la probabilidad. 
En resumen, los valores de prob_encontrar_tesoro y prob_encontrar_consumible son constantes ya que deben estar en **parametros.py**, y el número que determine en que probabilidad cae debe ser aleatorio cada simulación.
