### ISSUE TITLE
Pasar varibles locales a globales 

### ISSUE THREAD

**Issue by nataliameza** [IIC2233/syllabus#154]
Hola! tengo una duda de cómo utilizar una variable creada en una función, como una variable global.
Por ejemplo, si tengo 

def crear_variable():
 ___ variable = input(" Ingresa variable: ")
 ___  return variable 

crear_variable()

Estoy intentando hacer esto, me aparece el input y le entrego un valor, pero lugo,al momento de consultar por la variable en el prgrama global, me aparece:
NameError: name 'variable' is not defined 

Qué deno hacer para que me reconozca esa variable?

**Comment by yuwet15** [comment]
Podrias intetar afuera de la funcion usar variable=crear_variable() 
Creo(?

**Comment by kadroguett** [comment]
Hola @nataliameza, @yuwet15  se me adelantó. Pero como el dice, fuera de la función debes crear una variable para almacenar la que retorna la función `crear_variable():`.
