### ISSUE TITLE
Cargar archivos: no me lee los tildes

### ISSUE THREAD

**Issue by bjbarias** [IIC2233/Syllabus#154]
Hola!
Cuando mi programa lee el archivo no lee los tildes (Andrómeda).
y aunque hice una funcion para quitar los tildes, no se aplica a las variables guardadas.
Me funciona para todo lo que no tiene tilde.

El output es este:
_**Traceback (most recent call last):
  File "C:\...\T01\cargar_universo.py", line 36, in <module>
    print(modificar_galaxia.clases_galaxias['Andr�meda'].planetas)
AttributeError: 'int' object has no attribute 'planetas'**_

No se que hacer para que no se guarde asi (Andr�meda)

**Comment by Arcoirisky** [comment]
Cuándo abres los archivos ¿Pones en el open <<encoding = 'utf-8'>>? (Sin Los <<,>>)

**Comment by bjbarias** [comment]
ahora lo puse y me funciona!
gracias!
