### ISSUE TITLE
Duda "restricción alfanumérica"

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#154]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
En la sección de ventana principal se menciona que el nombre del jugador debe cumplir la "restricción alfanumérica" pero nunca se explica qué significa...

Significa que...

1) ...debe tener letras y números pero puede tener otros dígitos
2) ...debe estar hecho de letras o números pero sólo puede tener letras y números
3) ...debe tener letras o números pero debe tener al menos uno de cada uno

![image](https://user-images.githubusercontent.com/43099597/167274532-f3cf9a9d-0afd-4f73-9948-13a13600ded5.png)

**Comment by Emiliax16** [comment]
Hola, la restricción alfanumérica*/ quiere decir que cumpla con tener letras y/o números. Ejemplos:

1. vhGC76
2. Holaaa
3. 52412653SJAa
4. 9999

Estaría mal si se ingresa algo de este estilo: jkdashGHF565*dsf (presencia de un alterisco).
Saludos.
