### ISSUE TITLE
Propagación de la enfermedad - Cura - Estadísticas

### ISSUE THREAD

**Issue by nivek0o0** [IIC2233/Syllabus#154]
Hola, tengo unas dudas bien específicas.

1.- En la sección _3.6. Propagación de la enfermedad entre países_, al calcular la prob. de contagio entre un país infectado y un país limpio, cuando se habla del numero de conexiones del país se refiere a
a) conexiones entre el país infectado y solo un país limpio 
b) entre el país infectado y todas sus fronteras 
c) entre el país infectado y todos los países limpios fronterizos?

2.- No entiendo como funciona la cura y el enunciado no habla mucho de ella. 
a) ¿Qué pasa si el desarrollo llega al 100%? 
b) ¿Cuándo o con qué probabilidad se traslada de país la cura? o ¿cómo se reparte la cura desde el país escogido al azar?
c) ¿Las personas infectadas se van sanando de algún modo cuando la cura llega a su país?

3.- En la parte de las estadísticas. 
a) ¿_Muertes e infecciones por día_ debe estar separado según país o corresponde a un historial desde el día 1 hasta la fecha? 
b) ¿Los _promedios de muertes e infecciones_ se calculan a través de los días, a través los países o ambos?

Gracias!!

**Comment by stephichau** [comment]
@nivek0o0 Sobre tus dudas:

1. Es la b
2. Estamos trabajando para usted :)
3. a) Son datos globales y se separan por día 
Por ejemplo 
`Dia 1: Murieron X personas alrededor del mundo y se infectaron Y`

b) (Del enunciado) "(...)del día actual o el acumulado hasta la fecha". Esta información contempla los datos de todos los países.

**Comment by FernandoPieressa** [comment]
@nivek0o0 

2. Enunciado arreglad2 y subi3

Saludos!

**Comment by nivek0o0** [comment]
@stephichau gracias!

**Comment by asdegoyeneche** [comment]
Hola! Quiero confirmar algo del punto 3.a de Kevin.. : El enunciado dice "Muertes e infecciones **por** día:  Debe mostrar una lista de las infecciones y muertes por día". 

Con "por" día: se alude a que cada día que se pregunta por esta estadística se deben mostrar las muertes e infecciones de ese día? Es decir, mostrar algo como lo que mostró @stephichau para un único día. O se debe guardar esta estadística desde el primer día y mostrar algo como:

` Dia 1: Murieron X1 personas alrededor del mundo y se infectaron Y1`
`Dia 2: Murieron X2 personas alrededor del mundo y se infectaron Y1`
`...`
`...`
`...`
`Dia n: Murieron Xn personas alrededor del mundo y se infectaron Yn`

Gracias!

**Comment by stephichau** [comment]
@asdegoyeneche corresponde a un único día (el día actual).

**Comment by asdegoyeneche** [comment]
@stephichau gracias!
