### ISSUE TITLE
ciclos for y PEP8

### ISSUE THREAD

**Issue by Icarus328** [IIC2233/syllabus#154]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola,}

Tengo la duda si a la hora de hacer ciclos del tipo "for i in x" o "for i in range(n)" es necesario usar nombres descriptivos, como es indicado en el documento de PEP8 para las variables (Es decir, usar en su lugar "for 'nombre_descriptivo' in x") o si estos ciclos, por su simplicidad, son la excepción a la regla.

Gracias!

**Comment by pabloist** [comment]
Hola!

Para estos casos no es necesario utilizar nombres descriptivos por lo que que _for i in x_ es considerado correcto. De todas formas un nombre descriptivo ayuda a que tu código sea más entendible y claro para los ayudantes correctores :).

Saludos!
