### ISSUE TITLE
Duda Os

### ISSUE THREAD

**Issue by Dnpoblete** [IIC2233/syllabus#154]
Tengo una duda sobre el comando os.chdir(), si estoy dentro de una carpeta que esta dentro de la carpeta a la cual quiero cambiar, este comando me permite retroceder o no?

Gracias

**Comment by jmwielandt** [comment]
`os.chdir` te permite moverte entre directorios como si estuvieras usando el comando `cd` de la línea de comandos.
`.` es el directorio en el que estás.
`..` es el directorio anterior.
y luego tienes los elementos de tu directorio.

![image](https://user-images.githubusercontent.com/37153467/55686848-49a17400-5934-11e9-9190-ddc1f20aadca.png)

![image](https://user-images.githubusercontent.com/37153467/55686870-8f5e3c80-5934-11e9-8367-ffb726f0e566.png)

**Comment by Dnpoblete** [comment]
Muchas gracias, y otra pregunta relacionada con esto, es que cuando trato de cambiar de directorio a veces me sale asi / y otras veces así \ las líneas entre directorios, que puedo hacer para que queden solo para un lado, porque a veces me las toma y aveces me tira error o si puedo escribirlo de alguna forma en que el computador lo lea para el lado que corresponde? :(

**Comment by jmwielandt** [comment]
En los sistemas UNIX (de donde salen Linux y MacOS) para los paths se usa `/`, mientras que en windows `\`, aunque últimamente en Windows se ha ido dando soporte al slatch normal (`/`) como separador, por ejemplo, en la PowerShell de las imágenes de arriba.
`os.sep` te retorna el separador de tu sistema operativo.

Para más información, IIC2333 😃

**Comment by Dnpoblete** [comment]
Ya muchas gracias 😃
