### ISSUE TITLE
La comision puede ser 0 ó 1?

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#154]
Hola, la comision puede valer exactamente 0 ó 1? O deben ser valores entre 0 y 1 sin incluirlos?

gracias!

**Comment by iqacevedo** [comment]
Hola,

El enunciado solo específica que sea un real entre 0 y 1, así que puedes incluirlos, pero para que sea más real  los puedes dejar afuera si quieres.

Saludos !

**Comment by bedefrunner** [comment]
Pues muchas gracias noble señor!
