### ISSUE TITLE
Utilizar lambda en Tarea

### ISSUE THREAD

**Issue by Pipelao** [IIC2233/Syllabus#155]
Hola!
Una pregunta, ¿puedo utilizar lambda para poder ordenar una lista a través de key = lambda x :x[1] en la tarea?
Gracias de ante mano

**Comment by IchottMano** [comment]
@Pipelao Hola!
No hay ningún problema con eso!
Saludos!

**Comment by Pipelao** [comment]
@IchottMano 
Gracias
Saludos
