### ISSUE TITLE
Problema git push

### ISSUE THREAD

**Issue by aescobar4** [IIC2233/syllabus#155]
Me aparece esto cuanto hago git push... Que puedo hacer??
![Captura de pantalla 2019-04-07 a la(s) 14 06 02](https://user-images.githubusercontent.com/48262100/55687735-5b881480-593e-11e9-9fd0-02be167f2b2d.png)

**Comment by entamburini** [comment]
Hola! 

Te recomiendo leer el error completo, si te fijas dice claramente lo que deberías hacer:

> "Las actualizaciones fueron rechazadas porque el último commit de tu rama actual está detrás de su contraparte remota. Integra esos cambios remotos (ej: git pull ...) antes de pushear de nuevo."

En este caso, el error fue porque creaste/subiste tu README.md en la página de github y luego no hiciste git pull

Fíjate en lo que dice el bash porque es **altamente probable** que la solución esté justo ahí... frente a ti ;)
