### ISSUE TITLE
Fronteras por pais o totalidad

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#155]
Cuando un pais decide cerrar su frontera terrestre, se cierra a todos los paises o solo a uno en particular?

**Comment by hanavarrete** [comment]
@benjamimo1 La cierra a todos. Saludos!

**Comment by KnowYourselves** [comment]
@hanavarrete me sumo a la pregunta pero con los aeropuertos, cuando un gobiero decide cerrar aeropuertos se asume que todos los aeropuertos que ese país quedan nulificados? o solo algunos?

**Comment by FernandoPieressa** [comment]
Si se cierra el aeropuerto del país ya no se puede ingresar ni salir mediante ese método.

Saludos

**Comment by benjamimo1** [comment]
Segun el enunciado puedo cerrar aeropuerto "**o**" frontera y se cierran aeropuertos "**y**" fronteras. Es eso correcto? Las fronteras y aeropuertos se abren en forma conjunta

**Comment by iqacevedo** [comment]
@benjamimo1 Puedes cerrar los aeropuertos o las fronteras de forma separada, ya que tienen requisitos distintos. Del mismo modo cuando ya no se cumplan las condiciones de mantenerlos cerrados, puedes abrir fronteras o aeropuertos (es decir puedes abrir en un momento las fronteras y en otro los aeropuertos), en caso de que el motivo de abrirlos sea la cura se abren aeropuertos y fronteras juntos.

Saludos!

**Comment by nivek0o0** [comment]
@iqacevedo si la cura solo se reparte por aire, por qué debería abrir la frontera a causa de la cura?

**Comment by iqacevedo** [comment]
@nivek0o0 es sólo porque en el enunciado se indica así !
