### ISSUE TITLE
Opción 'volver atrás' necesaria EN TOOOODO MOMENTO?

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#155]
¡Hola! En la sección *4. Menús* del enunciado, dice que "Todos los menús deben (...) tener la opción de volver atrás", pero me queda una duda. ¿Eso significa que también absolutamente **cada funcionalidad de los mismos menús** tienen que tener la opción de volver atrás?
**Por ejemplo**, cuando pido que alguien cree un nombre de usuario para registrarse, ¿tiene que poder elegir volver atrás *aparte* de volver atrás automáticamente si escribe un nombre de usuario que no sirve? En este ejemplo bastaría con cambiar el print para avisarle al usuario que si presiona enter sin escribir nada vuelve atrás, pero en otras partes parecidas puede ser más difícil de incluir, por eso pregunto.
Gracias de antemanoo 😄

**Comment by Tito0906** [comment]
Holaa @sbcorrea, todos los menús **deben** tener la opción de volver atrás. Por otro lado, las funcionalidades se pide que sean aprueba de errores y que idealmente no entren en situaciones como loop infinitos porque no serían fáciles de usar. Si la funcionalidad cumple con volver atrás automáticamente y avisar que hay un error, entonces está bien. De cualquier manera, deja en claro en el README tu decisión. 

Saludos y éxito en la tarea!

**Comment by sbcorrea** [comment]
Muchas graciaaaas
