### ISSUE TITLE
Pyqt6 ejecución código - could not load the qt platform plugin

### ISSUE THREAD

**Issue by DaniloCordova13** [IIC2233/Syllabus#155]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola!!
Al momento de probar las cosas indicadas en los contenidos de la semana 4, me tira el siguiente error a pesar de que tenga instalado pyqt6. ¿Qué hago?
![Captura de pantalla (16)](https://github.com/IIC2233/Syllabus/assets/141789725/790c8efd-0c48-456a-aede-7431c0904537)

**Comment by catalinamirandah** [comment]
Hola ✨️,

Al parecer más de uno ha tenido problemitas utilizando PyQt6 desde wsl. Te sugiero seguir los pasos que indicó el profesor Hernán en la issue #131 para probar si te funciona ese código que dejó o en su defecto utilizar la terminal de Windows mientras.

Si ninguna de esas opciones te sirve, coméntame aquí abajito.

Saludos :D

**Comment by Hernan4444** [comment]
Hola, por si acaso,

Si es que no has logrado solucionar pyqt6 en wsl, por favor intentar con el siguiente comando:

`sudo apt install libqt6multimedia6 libpulse0 python3-pyqt5 libxcb-cursor-dev`

Y nos avisas cómo te fue con esto.

Saludosヾ(＾-＾)ノ
