### ISSUE TITLE
Valores predeterminados de la base de datos

### ISSUE THREAD

**Issue by anvaldes** [IIC2233/syllabus#155]
Como sabemos en las bases de datos que nos dan hay valores que ya vienen listos. ¿Que pasa si esos valor estan fuera del rango de nuestros parametros? Ejemplo: Que en mi base venga que chasis es 5, pero en mis parametros yo tengo que el minimo es 10. Lo que dice mi intuición es que se deje tal cual y que si se mejora entonces ahí cambiaría el valor de chasis y el minimo que podría tomar sería 10.

**Comment by jmwielandt** [comment]
Hola!

Debes dejarlos tal cual. No debes cambiarlos ni interrumpir el flujo del juego. 😄 

Saludos!
