### ISSUE TITLE
Pregunta sobre movimiento fluido de la mira del arma

### ISSUE THREAD

**Issue by SVenegasA** [IIC2233/Syllabus#155]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [S] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado cuando piden que el movimiento del arma sea fluido (en el punto 5.1.), no entiendo a qué se refiere. Osea, ¿por cada vez que se presione la letra (por ejemplo) "w", la mirilla avance una cantidad determinada por nosotros, pero que esta distancia la recorra poco a poco usando un QThread? y en ese caso ¿La distancia determinada a recorrer no podría ser muy pequeña?

**Comment by lfb1206** [comment]
Hola, la velocidad con la que se mueve la mira la determinan ustedes. La idea es que se mueva lo suficientemente rápido como para alcanzar los aliens, pero que este movimiento sea fluido. Con fluido se hace referencia a que esta no se mueva de una esquina a la otra al presionar una de estas teclas, en otras palabras, que se pueda tener cierta precisión con ella.
