### ISSUE TITLE
Referencia codigo externo 

### ISSUE THREAD

**Issue by Amath3o** [IIC2233/Syllabus#155]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, Quería hacer una duda solo para asegurarme, pero el uso de código externo considera buscar el funciona el funcionamiento del método de alguna librería? o sería para casos muy específicos

**Comment by FernandoTFH** [comment]
El tema del uso de un código externo, es que tu copies y pegues un código de alguien mas, y tu en el mismo código lo cites o en lo cites en el README (indicar de donde lo sacaste). Todo el tema de buscar cómo funciona y/o buscar si existe un método, nativo o de una librería específica, no se considera como uso de código externo.

**Comment by Amath3o** [comment]
Entiendo, gracias 😺
