### ISSUE TITLE
Duda sobre si es necesario guardar rondas en un archivo

### ISSUE THREAD

**Issue by ibgarrido** [IIC2233/Syllabus#155]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Para la tarea es obligatorio que se tenga que guardar el campeonato en un archivo (Por ejemplo si alguien elige un entrenador X, y ese entrenador X juega hasta la ronda 2 o 3, y luego quiere guardarla y continuar a futuro), o simplemente cada vez que se inicie el juego se parta desde cero con el campeonato?

**Comment by Amandasandov** [comment]
Hola, cada vez que se eliga a un entrenador en el menú de inicio el campeonato parte desde cero, no se deben guardar partidas anteriores.
