### ISSUE TITLE
Duda sobre os.system() y time

### ISSUE THREAD

**Issue by OrregoSilva** [IIC2233/syllabus#155]
Hola!
Queria saber si usar `os.system()` para limpiar la consola de vez en cuando entorpeceria al ayudante al momento de corregir, la razon por la cual quiero usarlo es para que se muestre solo lo que se esta usando en el momento y asi mejorar un poco el  como se ve el juego desde afuera.
Por otro lado, vi en una issue que decia que no usaramos `time` ya que puede generar tiempo extra en la correccion, por lo que queria preguntar si podemos agregar una opcion para activarlo o desactivarlo en caso de quererlo por parte del ayudante (lo de activar/desactivar tambien aplica para `os.system()`)
Gracias por adelantado!

**Comment by DCCollao** [comment]
Hola @OrregoSilva! Esta clase de dudas debe ir en la issue dedicada a librerías permitidas/prohibidas. Te recomiendo incluir los mismos detalles que en esta issue, pues está muy bien explicado! 

La issue a la que me refiero es #87.

**Comment by OrregoSilva** [comment]
Buena muchas gracias!
