### ISSUE TITLE
Dudas con el envio correcto de mensajes y su visualización

### ISSUE THREAD

**Issue by Icarus328** [IIC2233/syllabus#155]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola,

Encontré una issue similar a mi problema pero no es exactamente lo mismo, lo que pasa es que a la hora de enviar mensajes en mi programa estos no se imprimen en primer momento, pero el mensaje se guarda con el formato adecuado en el archivo "mensajes.csv", solamente hay que salir del chat y volver a entrar para visualizar los mensajes nuevos. Entonces tengo la duda de que si debería corregir esto, ya que los mensajes están siendo correctamente enviados, solamente no está disponible su visualización inmediata, y en el enunciado no dice que esto ultimo sea necesario (Solo se especifica la necesidad de imprimir el historial al abrir el chat con el contacto)

Gracias!

**Comment by aljara97** [comment]
Hola @Icarus328, el enunciado dice "Cabe destacar que si envías un mensaje deberás modificar el archivo nuevo `mensajes.csv` y luego deberás volver a mostrar el historial de conversación". Es decir, es necesario que el historial de chats se actualice y se reimprima en la consola. Creo que es bueno que te tomes el tiempo de arreglar esto, ya que, facilitará la corrección por parte del ayudante y obtendrías la mitad del puntaje en los puntos "Se muestra cada mensaje de forma separada, mostrando la fecha, hora, emisor y el contenido." debido a que no se muestran siempre que corresponda.

Saludos y mucho éxito en lo que queda de tarea 😄
