### ISSUE TITLE
Fechas de orders en funcionalidades

### ISSUE THREAD

**Issue by jerosalazar** [IIC2233/Syllabus#155]
En la funcionalidad que aparece a continuación:
>Lista de orders: Se deberá dar la opción de desplegar en consola, de forma ordenada, una lista de todos los orders del día, una fecha específica, entre dos fechas o de un mercado en particular.
>
se refiere a las ordenes activas que se crearon en esas fechas, las orders que hicieron match en esa fecha o ambas?
Ademas, cuando dice que un usuario Trader puede acceder al "registro de orders realizadas en los últimos 7 días" se refiere a las activas y creadas dentro de ese periodo de tiempo o a las que ya han hecho match. Si se refiere a las que han hecho match, su fecha de creación o fecha de match debe estar dentro de ese periodo?

**Comment by fdominguezclaro** [comment]
Muestra ambas (creadas y los matchs), y ordénalas por fecha de creación. Con eso te respondo las dos preguntas yo creo. 

Saludos

**Comment by jerosalazar** [comment]
@fdominguezclaro que pasaria si un usuario Trader tiene quiere realizar una oferta (ask o bid) en un mercado especifico y en este mercado hay una order activa (que no ha hecho match) desde 2 semanas atras, el usuario no podria ver los detalles de esa orden por llevar mas de 7 dias creada. 
Que pasaria en ese caso?

**Comment by iqacevedo** [comment]
Hola,

El usuario no podría verla al consultar orders activas, pero el sistema si podría hacer un match en caso de que se cumplas las condiciones adecuadas, lo cual si puede ver el usuario. 

Saludos !!
