### ISSUE TITLE
Duda enunciado menu prograposts opcion volver a menu inicio

### ISSUE THREAD

**Issue by mjbaeza** [IIC2233/syllabus#156]
hola! Por enunciado tengo entendido que en el menu de prograposts solo es necesaria la opcion de volver a menu de inicio (aparte de crear, eliminar y ver posts). Probando el programa me parecio extraño que no tenga la opcion de llegar al menu de seguidores sin tener que iniciar sesion nuevamente. Es necesario?

**Comment by jeschuwirth** [comment]
Hola @mjbaeza,

Para evitar tener que iniciar sesión nuevamente podrías hacer que el botón de volver atrás regrese a este "submenu" del menú de inicio:

![image](https://user-images.githubusercontent.com/37160256/77234772-da964d00-6b8f-11ea-8467-d92d6a4bb00b.png)

Si sigues teniendo dudas comenta en esta issue :)

**Comment by CamilaArgomedo** [comment]
hola! siguiendo esta duda en este submenu se puede cambiar el salir por volver al menú de inicio y que desde ahí se pueda salir?

**Comment by jeschuwirth** [comment]
Hola @CamilaArgomedo,

No debería haber problema con solo volver atrás y después tener la opción de salir, pero ya que la opción de salir es fácil de implementar te recomiendo tener ambas opciones en ese submenu y así evitas tener que recorregir en caso de que te descuenten.

Éxito!
