### ISSUE TITLE
Dudas sobre grupos, para añadir un usuario debe ser tu contacto/Formato de añadir usuario

### ISSUE THREAD

**Issue by Icarus328** [IIC2233/syllabus#156]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola,

Tengo dos dudas respecto a los grupos.

La primera, para poder añadir a un usuario a un grupo es necesario que esté en mis contactos?

La segunda, el formato señalado en el enunciado es de integrante1;integrante2;... , es decir, todo junto y sin espacios (Por lo menos me parece a mi a la vista) esto tiene que ser así? sería también valido cambiarlo ligeramente a, por ejemplo integrante1;integrante2;....; (Es decir, que tenga que acabar en ; también).

**Comment by IgnaciaJ** [comment]
Hola @Icarus328 !
Respecto a tu primera pregunta, no es necesario tener al usuario guardado en tus contactos :), solo basta con que exista en el csv. En cuanto a tu segunda pregunta, te recomiendo que sigas tal cual el formato que dice el enunciado, ya que al momento de la revisión el ayudante será el que probará los inputs al crear grupos (y probablemente no pruebe con inputs que terminen con ";"), por lo que tu programa entregará un error en el formato del input, donde según el enunciado está correcto! :) . Éxito en tu tarea!
