### ISSUE TITLE
Computador se calienta mucho cuando corro el código

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#156]
Hola!! Tengo una duda media random. He hecho varios módulos para la tarea y los he conectado entre ellos y con el main.py
Me pasa que cada vez que corro el código mi pc se calienta mucho y empiezan a funcionar los ventiladores a full. ¿Es normal? ¿Estoy haciendo algo mal?¿Cómo puedo arreglarlo?
Mi computador debe tener como dos años y es mac

ayuda :(

**Comment by sbcorrea** [comment]
Holaa, no soy ayudante pero mi computador hacía cosas parecidas hace un tiempo y me recomendaron cambiar de VSCode a Sublime y correr el código en consola en lugar de dentro de la IDE. Quizá con eso baste si estás en VSCode? Ojalá te sirva :hugs:

**Comment by denisseleiva** [comment]
Bueeena, gracias por el dato!!!

**Comment by Juampisaez** [comment]
Hola @denisseleiva 
Existen muchas causas posibles si tu mac se calienta mucho, averiguando en internet encontre [esto](https://support.apple.com/es-lamr/HT201640).
Desde mi experiencia personal, te recomiendo no correr tantos programas a la vez y también ocupar tu laptop en una mesa (evita usarlo en la cama), normalmente en estas situaciones ocurre que se calienta.
