### ISSUE TITLE
Escritura archivos en la base de datos

### ISSUE THREAD

**Issue by martin412** [IIC2233/Syllabus#156]
Tengo una duda con respecto a lo anterior, si bien los archivos(users.csv , orders.csv)son entregados en desorden es  necesario escribirlos de la misma manera?

**Comment by Arcoirisky** [comment]
¿Te refieres a escribirlos desordenados? 

Puedes hacerlo cómo te acomode, siempre y cuando lo hagas actualizando los archivos con la información respectiva a cada uno (por regla de enunciado) aunque debes recordar especificarlo en el Readme por si acaso O:!
