### ISSUE TITLE
Prioridad de cerrar fronteras

### ISSUE THREAD

**Issue by Jaluco** [IIC2233/Syllabus#156]
En el enunciado nos dicen que para saber la prioridad de cerrar las fronteras usamos el promedio de los porcentajes de los paises infectados dividido en 100, esto se revisa cuando ya se cumplen las condiciones para cerrar la frontera? u ocurre independiente de la poblacion infectada?

**Comment by Jaluco** [comment]
Ademas se establece que : 
"Todas las posibles propuestas del mundo se agregan a una cola de prioridades. Al final de cada dı́a se
escogen las 3 acciones con mayor prioridad y se ejecutan. Luego se recalculan las posibles acciones."

Esto significa que independientemente de la cantidad de paises que tengan sus acciones del mundo solo tres son implementadas?

**Comment by eiherrera** [comment]
La probabilidad de cerrar la frontera se toma en cuenta sólo cuando se cumplen las condiciones para clausurarla. Respecto a las acciones de los países, efectivamente, sólo tres son implementadas por día.
