### ISSUE TITLE
Duda sobre contenidos necesarios para T1

### ISSUE THREAD

**Issue by luc0i** [IIC2233/Syllabus#156]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

Hola!
Que contenidos son necesarios para realizar la Tarea 1? Hasta los contenidos de la semana 3?

Gracias!

**Comment by PipeXtz** [comment]
Hola, @luc0i !

Efectivamente, como mencionas, son los contenidos hasta la semana 3, que corresponden a todo lo de programación orientada a objetos. 

Cualquier duda quedo atento.

**Comment by luc0i** [comment]
Perfecto, gracias!!
