### ISSUE TITLE
No funciona abrir ventana

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#156]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola,

Estoy repitiendo el ramo y copié y pegué lo que hice el semestre pasado para abrir ventanas. Pero, no sé por qué no me abre las ventanas, ni tampoco da error. Corrí el código del semestre pasado y sí se abre, así que no es un problema de la instalación de pyqt5.
Subí lo que llevo a mi repositorio privado, ¿me lo podría revisar alguien y darme un feedback?

Gracias

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by diegocostares** [comment]
@Fernanda1232123 Mire a la rápida y no vi ningún error aparente (Quizás lo único es que haces .show() a todas las ventanas y tu programa se cae al tratar de mostrarlas todas a la vez), recomiendo revisar la última actividad para que tengas un mejor referente. Como consejo personal te recomiendo que hagas las ventanas de la tarea con Designer (Revisa la ayudantía).

Intenta también testear cada ventana de forma individual, agregando una variación del siguiente comando al final de cada .py de tu frontend:
```python
if __name__ == "__main__":
    app = QApplication(sys.argv)
    ventana = VentanaInicio()
    # ventana.mostrar()
    sys.exit(app.exec_())
```
