### ISSUE TITLE
problema con python

### ISSUE THREAD

**Issue by Pelaysen** [IIC2233/Syllabus#156]
no puedo correr python: en cuanto elijo python como interpeter para pycharm  me sale:
```python
Cannot set up a python SDK 
at Python 3.6 (Tarea 1) (C:\Users...   ...Tarea 1\venv\Scripts\python.exe).
The SDK seems invalid.

```
y al correr el programa tira el siguente error:
```python

Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
Current thread 0x000018c4 (most recent call first):
```
no he podido solucionarlo desde anteayer. es un problema de python no de mi programa, he reinstalado python y pycharm pero nada, y stackoverflow no ayuda.

**Comment by Arcoirisky** [comment]
¿Qué sistema eres? ¿Windows, Linux, otro?
¿Estabas trabajando en Pycharm antes del error?
