### ISSUE TITLE
Descuento gitignore

### ISSUE THREAD

**Issue by flogaido** [IIC2233/syllabus#156]
Solo para corroborar, en esta tarea no hay ningún archivo que no debamos subir cierto?

**Comment by lily416** [comment]
Hola 😄 

En esta ocasión no se evaluará el uso de `.gitignore`, por lo que no se les descontará si suben archivos que no son necesarios para correr la tarea.
Aunque igual se agradece que no suban archivos innecesarios (i.e. la carpeta `data/`) los computadores de sus ayudantes tienen memoria limitada 💻💔.  
  
  
Saludos y éxito con la tarea 👋 🏰
