### ISSUE TITLE
Aumentos al evolucionar 

### ISSUE THREAD

**Issue by Andresutro** [IIC2233/Syllabus#156]
* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!, cuando un programon evoluciona, no entiendo muy bien que se debe aumentar. Por ejemplo en el caso de la vida, supongamos que es un programon con 25 de vida y con un parámetro de MEGA_VIDA = 100, se debe aumentar la vida a 125, o aumentar el limite de la vida de 255 a 355, teniendo su vida actual en 25?

**Comment by MrNachoX** [comment]
Hola @Andresutro! si un programon tiene 25 de vida y el parámetro de MEGA_VIDA es 100, entonces la vida aumenta a 125. El límite de la vida siempre se mantiene en 255.
