### ISSUE TITLE
Duda sobre 'Consola' y 'Modularización'

### ISSUE THREAD

**Issue by mVal919** [IIC2233/Syllabus#156]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, buenas tardes. Con respecto al README.md, en la sección de menú, ¿a que se refiere con Consola y Modularizacion? Osea, ¿que hay que poner ahi en especifico?
Muchas gracias.

**Comment by vgalfaro** [comment]
Hola! entiendo que consola refiere a que efectivamente se implementaron los menús y la interacción con el usuario, podrías mencionar los prints e interacción, la modularización alude a si se modularizó (valga la redundancia) la tarea y de que forma, no es necesario, mas es una buena práctica modularizar el código para que este sea más limpio y ordenado, aquí podrías decir si creaste algún módulo para esto y mencionar brevemente los archivos .py de la tarea. Saludos!
