### ISSUE TITLE
Interpretación de mensaje de errores de tests

### ISSUE THREAD

**Issue by sbarriag** [IIC2233/Syllabus#156]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda de cuando uno corre los test y estos fallan en la consola se arroja un mensaje, por ejemplo este 
![image](https://github.com/IIC2233/Syllabus/assets/127463084/d12406cc-48b8-46d0-a357-2d5ae51e5b9f)
De esto puedo interpretar que mi respuesta fue 0 y que la respuesta correcta debería ser 30? o es al revés? 
Muchas gracias

**Comment by Mcroquevielle** [comment]
Hola!! Tu respuesta es 0, y debería ser 30. Si te fijas arriba sale que compara tu respuesta con 30 (en el paréntesis)

**Comment by sbarriag** [comment]
Gracias
