### ISSUE TITLE
Duda compatibilidad con unix/linux

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#157]
Hola, uso windows.
¿Mi programa debe ser compatible con macOS y linux?
Estoy incluyendo os.system("pause") en mi código y no sé si eso al ejecutarlo en linux o mac hará que explote el universo, python llore o algo parecido.
Gracias~

**Comment by rihanuch** [comment]
Hola!!
Tranquilo, la gracia de la libreria os es que es cross platform!!
Saludos y éxitos en lo que queda de la tarea! 🍀

**Comment by rihanuch** [comment]
Perdon! Mala mia!!!🙈🙈 eso si va a arrojar un error! Si quieres detener el juego puedes hacerlo por un tiempo con el modulo time y time.sleep(segundos)


Perdón por el error!!!!!

**Comment by rihanuch** [comment]
En este sentido, si, debe serlo. Si quieres seguir utilizando esa funcion, entonces debes encontrar su equivalente en mac y linux para programar bien tu programa, ya que a priori no sabes quien va a correr tu tarea!
