### ISSUE TITLE
abandonar_frase

### ISSUE THREAD

**Issue by nnovoag** [IIC2233/syllabus#157]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

hola, cuando alguien abandona el grupo tengo que  guardar el mensaje '/salir' igual en mensajes.csv?? o solo sacarlo del grupo

**Comment by hsazos** [comment]
Hola @nnovoag ,

Según enunciado, cuando un usuario abandona el grupo usando el comando, el último mensaje que se debe guardar es "El usuario <Usuario> ha abandonado el grupo". Espero que eso resuelva tu duda. Ánimo con la tarea!

**Comment by mjsifri** [comment]
Hola, ese mensaje tiene que ir en el mismo formato que los otros? es decir, que imprima la fecha, luego al usuario y luego el mensaje de que ha abandonado el grupo?

**Comment by hsazos** [comment]
Hola, como es un mensaje debe cumplir el formato de todos los mensajes. Lo que incluye lo que tu dices.
