### ISSUE TITLE
Duda al guardar partida

### ISSUE THREAD

**Issue by MGilB** [IIC2233/syllabus#157]
Hola, tengo una duda con el guardado, se tiene que dar la opción de sobrescribir una partida o asumimos que cada vez que se guarde una partida va a tener nombre diferente.
Gracias

**Comment by hbkim94** [comment]
Hola!

Queda a tu criterio si es que la partida se sobreescribe o si le das al usuario la opción de generar un nuevo save. Del enunciado, lo único que se pide es que tenga el nombre del usuario, así que lo demás depende de como hayas modelado tu programa.

Te recomiendo que incluyas tu elección en tu readme.

Mucha suerte!
