### ISSUE TITLE
Velocidad Recomendada

### ISSUE THREAD

**Issue by anvaldes** [IIC2233/syllabus#157]
En velocidad recomendada, más del 90% de las combinaciones de todos los datos me da negativa, entonces estuve revisando y es porque el factor de dificultad de la pista es de orden mucho mayor a velocidad base, creo que si se dejara la formula como:

velocidad_recomendada = velocidad_base + (traccion_ruedas - hielo_pista) + 0.01*(experiencia_piloto-dificultad_pista)

Sería mejor porque lo unico que estamos haciendo es disminuyendo el orden al factor que involucra dificultad de la pista. Porque lo malo de que la velocidad recomendada sea mayoritariamente negativa es que eso implica que la velocidad intencional tambien sea negativa y al momento de calcular la velocidad real, en la mayoría de los casos estaría elegiendo la velocidad minima que viene dada por mis parametros y así las carreras serían casi entre puros autos que tienen la misma velocidad y es la velocidad minimima.

NOTA: Es importante notar que la velocidad recomendada no depende de mis parametros, por ende, no se puede hacer más que modificar la formula para cambiar los resultados.

**Comment by jmwielandt** [comment]
Hola!

Lo que haremos será actualizar la fórmula del enunciado agregando nuevos parámetros que ponderen el peso de los términos distintos a la velocidad base en la fórmula que mencionas. El resultado es este:

![image](https://user-images.githubusercontent.com/37153467/64288840-12f67680-cf31-11e9-8065-4c24123bab92.png)



Saludos~

PD: en la fórmula que indicas te falta el efecto de las rocas en la velocidad.

**Comment by humbertoortuzar** [comment]
Hola! Los ponderadores debo definirlo yo en el archivo parametros.py o vienen dados?
Saludos

**Comment by JuaniAndres** [comment]
Tu tienes que definiros en parametros.py
#174

**Comment by jmwielandt** [comment]
Hola!

Es tal como dice @JuaniAndres 

Saludos!
