### ISSUE TITLE
Diagrama de Clases Tarea 2

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#157]
Como tenemos que crear nuestras propias estructuras de datos, tenemos que incluir estas en el diagrama?

**Comment by hanavarrete** [comment]
Tienes que incluir en el diagrama toda estructura de datos que no sea la "auxiliar" a la que no puedes usar en la tarea. Por ejemplo, si creas tu propia lista, esta no debe estar en el diagrama, en cambio, si la tarea exige crear tu propio Arbol, este si debe estar. Espero que eso aclare tu duda, saludos!

**Comment by KnowYourselves** [comment]
Muchas gracias!, by the way, cambiaron el enuncioado de la tarea por el de la tarea de matematicas discretas

**Comment by FernandoPieressa** [comment]
@KnowYourselves Esto nunca paso :)

**Comment by KnowYourselves** [comment]
@FernandoPieressa what has been seen cannot be unseen.
