### ISSUE TITLE
Lista de orders

### ISSUE THREAD

**Issue by mebruna** [IIC2233/Syllabus#157]
En el enunciado, cuando dice:

> Lista de orders: Se deberá dar la opción de desplegar en consola, de forma ordenada1, una lista
de todos los orders del día, una fecha específica, entre dos fechas o de un mercado en particular.

se refiere a las orders del usuario que está consultado o de todo el sistema en general? Y la misma pregunta para lo que dice después:

> Lista de orders activas: Se deberá dar la opción de desplegar en consola de forma una lista de
todos los orders que están activos (no han hecho match todavía).

**Comment by Arcoirisky** [comment]
Tu pregunta se responde en la issue #101 y es para las órdenes de todo el sistema en general.
