### ISSUE TITLE
Bombas Especiales

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#157]

**Comment by enriquemolinare** [comment]
en el caso que el jugador ya haya utilizado la habilidad de bomba especial y me entregó la posición de su jugada, puedo asumir que  su jugada como su fuera  una bomba regular

**Comment by emiliaup** [comment]
Para las bombas especiales, el jugador elige que bomba especial? o es random? Cruz, Diamante o X

**Comment by YehudaGurovich** [comment]
@enriquemolinare creo que en la issue #126 hablan de eso.

**Comment by DCCollao** [comment]
Hola @enriquemolinare! 
Efectivamente se trató en #126, como menciona @YehudaGurovich.

@emiliaup Del enunciado:

> Además de las Bombas Regulares, dispondrás de tres tipos de bombas las cuales podrán ser utilizadas
  una única vez por partida. Esto significa que solo podrás hacer uso de una bomba especial a lo largo de
  la partida, independiente del tipo que hayas escogido.

En resumen,  sí, el jugador elige.

**Comment by emiliaup** [comment]
gracias 
:)
