### ISSUE TITLE
Duda pull

### ISSUE THREAD

**Issue by ElTurkos** [IIC2233/syllabus#157]
Hola, trato de hacer pull para recuperar los archivos .csv del syllabus pero no me resulta, los archivos estan borrados
![Captura](https://user-images.githubusercontent.com/62064830/77231673-4326ff00-6b7b-11ea-884b-c08d55b69889.PNG)

**Comment by DCCollao** [comment]
Hola!

Puedes intentar borrando y pulleando nuevamente el syllabus. Es la vieja confiable para este tipo de problemas :smile:

**Comment by ElTurkos** [comment]
La carpeta entera?

**Comment by DCCollao** [comment]
Síp, el syllabus completo

**Comment by ElTurkos** [comment]
Gracias!
