### ISSUE TITLE
Duda funcion plantar

### ISSUE THREAD

**Issue by Franastel** [IIC2233/Syllabus#157]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Segun las instrucciones en plantado de cultivos, "se priorizará siempre insertar el bloque de cultivo partiendo en la primera celda superior izquierda disponible" pero la funcion recibe coordenadas de posicionamiento del bloque como una lista, entonces cual de las dos instrucciones se prioriza?

**Comment by FernandoTFH** [comment]
El método de plantar de la clase Predio, asume que los datos que recibe son válidos, es el método de buscar_y_plantar el que busca donde plantarlo con las condiciones indicadas en Plantado de cultivos.
