### ISSUE TITLE
Duda con instrucción de usar 4 espacios en vez de tabulaciones.

### ISSUE THREAD

**Issue by Segismundios** [IIC2233/Syllabus#157]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo las siguientes dudas respecto a la instrucción de usar espacios en vez de tabulaciones:
- Si tengo configurado el vscode con "Spaces: 4", ¿Esto hace automáticamente que cuando yo use tabs, se aplique como 4 espacios en vez de tabulación? De no ser así, ¿Será necesario que los borre y rellene el código con espacios manualmente?  
- ¿Qué diferencia existe entre usar uno u otro?

**Comment by Benjeeeh** [comment]
Hola!
No habría problema, si la tabulación en tu caso equivale a cuatro espacios, entonces sería lo mismo que agregar cuatro espacios de manera manual, así que no habría problema y no tendrías que reemplazarlos en tu código.

En general no existe una diferencia, ya que en el fondo es lo mismo y en la mayoría de los casos VsCode trae como predeterminado que 1 tab = 4 espacios. La idea es que todos los estudiantes tengan esta convención y aplique la misma regla de tabulación para todos (ya que si un alumno tiene un tab de 2 espacios, cabrían más caracteres en una línea de código no sería justo, y estaría afectando a la evaluación de PEP-8 por ejemplo).

Éxito con la tarea!

**Comment by Segismundios** [comment]
Nicee, muchas gracias!
