### ISSUE TITLE
Modularizacion. (Lineas de una ventana)

### ISSUE THREAD

**Issue by ancontardo** [IIC2233/syllabus#158]
Cuanto es el máximo de lineas de código que puede tener una ventana, para no tener que modularizar

**Comment by gatochico** [comment]
Hola! El máximo por módulo es de 400 líneas. Toda esa información se encuentra en la página de [descuentos](https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md).

Saludos y éxito 🤓
