### ISSUE TITLE
Problemas con import parametros

### ISSUE THREAD

**Issue by Lexiesm** [IIC2233/Syllabus#158]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia
 
Hola! tengo una duda, tengo la archivo parametros.py en mi carpeta de T2, el tema es que cuando quiero hacer correr un código que se encuentra en ...T2/frontend/ventana_inicio.py (mi código esta en ese archivo .py) me sale el error "ModuleNotFoundError: No module named 'parametros' ", y cuando meto el archivo parametros.py a la misma carpeta frontend funciona, como puedo hacer para que me reconozca parametros.py sin tener que meter este archivo a la carpeta frontend? de antemano gracias!

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Emiliax16** [comment]
Hola @Lexiesm ! Para que te funcione la importación de `parametros.py` desde la carpeta T2, debes abrir la misma carpeta T2 en tu editor. Si sólo abres la carpeta frontend, te tirará el mismo error que mencionas. 

Por otro lado, me gustaría recomendarte que en estas ocasiones donde se quiere diferenciar entre frontend y backend, utilices main para la importación de todo lo que necesites en tus otros módulos, de tal manera que en main se inicialicen las clases y funciones que requeriran los parametros importados. Por lo que tu `main.py` estará dentro de la carpeta T2 y ahí no debería haber ningún problema con importar `parametros.py` y podrás pasar todos sus datos como argumento para tus funciones y clases. Saludos!

**Comment by Lexiesm** [comment]
Es que tengo abierta la carpeta T2 en mi editor, no solo la de frontend :( por eso me parece raro u.u

**Comment by KrishnaChaparro** [comment]
Hola a mi me pasa exactamente lo mismo que a él y también abro la carpeta T2 en el editor, no se como solucionarlo.

**Comment by Lexiesm** [comment]
Al final lo solucioné con lo del main.py (lo que Emilia dijo en el segundo párrafo jiji). Gracias!

**Comment by Emiliax16** [comment]
@KrishnaChaparro lo mejor es que todos los archivos los importes desde `main.py` y los pases como argumentos a los módulos que necesites, así se evitan malas prácticas y errores con el tema de la importación y la corrección. Saludos.
