### ISSUE TITLE
Ejercicio propuesto 2.3 semana2: prevenir creación del objeto

### ISSUE THREAD

**Issue by jpgarcia96** [IIC2233/syllabus#158]
En el ejercicio 2.3 se pide que el objeto usuario sólo se cree cuando se cumplen ciertas condiciones. ¿Cómo lo puedo hacer para que  en la creación del objeto este se "aborte" si no los cumple?
Este es el setter de una de las condiciones (para el atributo email). ¿Debo poner algo más dentro del setter?
```python
    @mail.setter
    def mail(self, value):
        if value[-6::]=='@uc.cl':
            self.__mail = value
        pass
```

**Comment by furcelay** [comment]
Hola!
Te recomiendo revisar el ejemplo *Ejemplo: definiendo una clase Email* del contenido de properties, la idea es que el mail se ingrese solo si cumple las condiciones, en otro caso quede en `None`.

Con respecto a tu duda, no debes abortar la creación del objeto, para eso deberías validar los datos antes de su creación y esa no es la idea del ejercicio, pero el enunciado indica *"debes implementar un método de DCCgram que agregue nuevos usuarios a la plataforma, pero solo lo haga si cada nuevo usuario cumple con todos los requisitos y si su username no existe previamente."*, es decir, puedes crear un usuario inválido pero no debe ser añadido a DCCgram.

Espero que eso haya aclarado tus dudas,
Saludos!
