### ISSUE TITLE
Problema al Guardar Archivos

### ISSUE THREAD

**Issue by Jj1martinez** [IIC2233/Syllabus#158]
Hola, tengo un problema que al parecer es de mi pc. 
corro el código para escribir un archivo txt y no se crea nada. 
por ejemplo

```python
archivo = open("arhivo1.txt", 'w')
archivo.write("Hola")

archivo.close()
```

Luego no aparece en la carpeta. Que puede estar sucediendo?

**Comment by Arcoirisky** [comment]
¿Estás buscando en la carpeta indicada? Quizás tu working directory es otro y no te estés dando cuenta O:!

**Comment by Jj1martinez** [comment]
Si, el read me trabaja perfecto. Y el codigo del write corre sin ningun error, el problema es solamente que no se crea el archivo o si existe, no lo modifica

**Comment by Arcoirisky** [comment]
Sino, prueba con with open

**Comment by Jj1martinez** [comment]
Solucionado! graciaass
