### ISSUE TITLE
Ignorar los archivos innecesarios en git

### ISSUE THREAD

**Issue by glbello** [IIC2233/Syllabus#158]
¡Saludos!, quería saber si alguien sabe como ignorar los archivos Currencies.csv, csvgenerator.py ... etc. acudo aquí porque llevo mucho rato buscando por aquí y allá y las opciones que vi no me han resultado, por lo que acudo aquí por si alguien ya sabe eso.

**Comment by akaminetzkyp** [comment]
Si te refieres a ignorarlos al momento de subir tu tarea a git, puedes escribir los nombres de los archivos a ignorar en un archivo llamado `.gitignore` en tu repo. :)

**Comment by sebacruzd** [comment]
Aparte, te invito a leer la [documentación de gitignore](https://git-scm.com/docs/gitignore), para que veas más funcionalidades que tiene. Hay maneras de ignorar todos los archivos de un formato, por ejemplo.

**Comment by glbello** [comment]
@akaminetzkyp ese el punto! no me funcionó 😞 
@sebacruzd oh vi ahí algo diferente a lo que he encontrado, lo probaré, muchas gracias 👍

**Comment by stephichau** [comment]
@glbello quizás [esto](https://stackoverflow.com/questions/7927230/remove-directory-from-remote-repository-after-adding-them-to-gitignore) te sirva :)
