### ISSUE TITLE
Exportacion Diag. de Clases

### ISSUE THREAD

**Issue by jchernandez22** [IIC2233/syllabus#158]
Hola:
Cree mi diagrama de clases en draw.io y cuando lo exporto como PDF se ve muy mal. Por ejemplo, este es el que subí para el avance:
[T1 Diag. de clases.pdf](https://github.com/IIC2233/syllabus/files/3051973/T1.Diag.de.clases.pdf)

**Comment by lily416** [comment]
Hola :)

Para arreglar lo de la exportación puedes:

1. Seleccionar tu diagrama y exportarlo como una imagen (.png, .jpeg, .svg)
1. Agrandar el tamaño de la página y exportarlo como un pdf.
   Para agrandar el tamaño de la página debes abrir el Format Panel (`Crtl + Shift + P`) y cambiar el Paper Size.

Saludos y éxito con la tarea 👋 🏰
