### ISSUE TITLE
Duda al descontar energía entrenador al entrenar un programon

### ISSUE THREAD

**Issue by gianpisani** [IIC2233/Syllabus#158]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda cuando nos encontramos en el menú de entrenamiento y seleccionamos entrenar un programon. Ya que aquí debemos descontar al entrenador una cantidad ENERGIA_ENTRENAMIENTO de energía. Al realizar esto, la experiencia del programón elegido aumenta en un entero aleatorio entre MIN_AUMENTO_EXPERIENCIA y MAX_AUMENTO_EXPERIENCIA. **Mi duda recae en que pasa si mi entrenador tiene 7 de energía pero pierde 8 (por ENERGIA_ENTRENAMIENTO) por lo tanto, quedando en 0 de energía** de entrenador, **en este caso la experiencia del programón aumenta también a pesar no tenga esa suficiente energia que le quitan?** o en ese caso no aumenta?

**Comment by TarekHirmas** [comment]
Holaa, en el enunciado dicen que en caso de que el entrenador no cuente con suficiente energía no se llevará a cabo el entrenamiento.
