### ISSUE TITLE
problemas con el test_tablero_solucionar

### ISSUE THREAD

**Issue by JPBarrosG** [IIC2233/Syllabus#158]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Al ejecutar el  test_tablero_solucionar me terminan casi todos los test fallando y despues de revisar varias veces que el return de la funcion sea correcto y similar al pedido en el enunciado, este continua sin funcionar. analizando el archivo del test resulta que este si me logra arrojar el test como correcto cuando cambio la linea 238 de "tablero = Tablero(copy.deepcopy(tablero_str))" a "tablero = Tablero(tablero_str)", no se que implicancias tiene este cambio pero se que no deberia tener que modificar este archivo para pasar los test. adjunto una imagen donde se ve por medio de un print el tablero original y luego el tablero ya modificado por el programa para el test del tablero 2x2 por si existe alguna variable en el formato que no tuve en cuenta.
![image](https://github.com/IIC2233/Syllabus/assets/142442997/04ac83ab-5393-429d-b1da-af0ecc2612b6)
tambien adjunto una imagen de un fragmento del test donde se puede observar que la tabla que arroja mi programa se encuentra dentro de las respuestas.
![image](https://github.com/IIC2233/Syllabus/assets/142442997/76e9a038-3acf-4660-b658-8cb1a10caf80)
por ultimo tambien adjunto una imagen del porque, segun el panel de control, el test me esta fallando.
![image](https://github.com/IIC2233/Syllabus/assets/142442997/59f74e50-4c20-4d68-bab4-174e48c97b30)

**Comment by Hernan4444** [comment]
Hola @JPBarrosG 

Lo que ocurre no es que tu solución esté mala, lo que pasa es que ese método dice:

![image](https://github.com/IIC2233/Syllabus/assets/15641721/9dd2d9f5-b6e4-4511-bb43-729727b1246f)

Y la línea del _test_ donde se cae tu código es la que justo verifica que el tablero original que te dimos a tu `Tablero` sea igual al tablero que tu tienes post ejecutar el método de `solucionar()`.En otras palabras, cuando ejecutas `solucionar()`, estás modificando el contenido de tu tablero (`self.tablero`) y eso va en contra del método. 

Antes de empezar a llenar con los peones, debes asegurarte de estar trabajando sobre una correcta copia de tu tablero y no sobre el original. Ahí parte del desafío es investigar como hacer una copia de una lista de listas 😄 

¡Mucho éxito con la tarea!
Saludosヾ(＾-＾)ノ
