### ISSUE TITLE
Ruedas de Vehiculos

### ISSUE THREAD

**Issue by Jprampad** [IIC2233/syllabus#158]
Hola!
Quisiera saber si el tener más ruedas, genera una mejor tracción, es decir, que el automóvil posee más tracción que la motocicleta, o no genera ningún beneficio que un vehículo tenga más ruedas que otro.
Gracias de antemano

**Comment by jeschuwirth** [comment]
Hola @Jprampad,

El número de ruedas no afecta la tracción de un vehículo, sólo afecta en el cálculo del equilibrio cuando hay 2 de ellas.

Suerte!

**Comment by Jprampad** [comment]
Gracias!
