### ISSUE TITLE
Duda sobre archivo puntajes.txt

### ISSUE THREAD

**Issue by nicolasgarciaes** [IIC2233/Syllabus#159]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola buenas, tengo una duda sobre el archivo "puntajes.txt", al momento de la revisión siempre se utilizará como mínimo el archivo original que se encuentra el Syllabus? o dicho archivo podrá venir modificado?
En particular, mi código debe estar preparado para el caso en que el archivo puntajes.txt venga vacío? o siempre habrá algún registro de puntaje de un usuario?

**Comment by nzamorano** [comment]
Hola @nicolasgarciaes, el archivo de _puntajes.txt_ no necesariamente será igual al de ejemplo. Debes estar preparado para leer cualquier contenido del archivo, eso si, el archivo siempre seguirá el formato del ejemplo mostrado en el enunciado. Entonces, si el archivo está vacío, no se deberán mostrar puntajes en el ranking.
