### ISSUE TITLE
Iniciar Juego

### ISSUE THREAD

**Issue by Cschavez** [IIC2233/Syllabus#159]
Hola! Quisiera saber si al iniciar el juego hay que dar la opción de partir desde cero y cargar archivos? o solo tengo que cargar los archivos? 
Muchas gracias !

**Comment by Arcoirisky** [comment]
Hola!!
No está especificado en el enunciado así que queda a tu criterio :D Recuerda mencionarlo en el Readme!! 
(Y ojo, porque si permites partir desde cero y el usuario nombra una galaxia igual a alguna del csv y luego carga pueden pasar cosas malas :S)
