### ISSUE TITLE
Varias dudas con respecto a mi código en la T0

### ISSUE THREAD

**Issue by mbozo2214** [IIC2233/syllabus#159]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo un par de dudas con respecto a mi desarrollo de la T0:

1. Usé los parámetros (VOLVER_FRASE y ABANDONAR_FRASE) sólo para lo respectivo a contactos y grupos y registro-inicio sesión de usuario, es decir, mis menús principales de selección ("iniciar sesión" , "registrarse" y "salir", por ejemplo) están en inputs numéricos (1 para la primera opción, 2 para la segunda y así, y 0 para salir). ¿Puedo dejar el "salir" como 0 o esto siempre debe ser con VOLVER_FRASE?

2. Leí en una issue-aporte que un usuario con ";" da error: ¿esto será evaluado o debo restringir también el uso de este?

3. En el enunciado.pdf se dice que, si se ingresa al iniciar sesión un nombre inexistente, se debe enviar directamente al menú. En mi programa, se permite intentar de nuevo y se recuerda que se da la opción de volver al menú con VOLVER_FRASE (en parte porque lo encontré más práctico, a diferencia de tener que volver al menú y hacer todo de nuevo) . ¿Debo hacer exactamente lo que dice el enunciado o puedo dejar mi código tal como está?

Muchas gracias de antemano.

**Comment by mbozo2214** [comment]
También tengo una última duda que olvidé escribir, que es con respecto a PEP8: se menciona que es mala praxis hacer muchos prints seguidos y que se recomienda tabular y escribir todo en una línea. Para algunos menú estoy utilizando .center() y leí en internet que esto toma en cuenta una sola línea, pues al utilizar \n junto a éste no se toma en cuenta o la siguiente línea no queda centrada. ¿Hay algún problema si utilizo .center() y hago 2-3 prints seguidos (sin abusar obviamente de la cantidad de estos)?

**Comment by Juampisaez** [comment]
Hola @mbozo2214 
Uff jajajaj muchas preguntas. Aqui vamos:

1. No entiendo bien esta pregunta. Una aclaración, los parametros VOLVER_FRASE y ABANDONAR_FRASE **solo se ocupan en los chats** (para el regular se ocupa solo el VOLVER_FRASE y para el grupo se pueden ocupar los dos, como dice el enunciado). Para los menus en donde se muestran las opciones, por ejemplo el inicial que ya comentaste, puedes dejar las opciones ("iniciar sesión" , "registrarse" y "salir", etc) como tu quieras, pero te recomiendo hacer algo parecido a las imagenes del enunciado para que no complicarte. (insisto no se ocupan los parametros para estos menus).
2. No se evaluara eso, las unicas restricciones que tiene el usuario es que no posea comas "," y que tenga un largo de caracteres entre 3 y 15 (y que tampoco este registrado).
3. En este caso, debes guiarte por el enunciado ya que esta especificado ahi. Si no lo estuviera podrías dejarlo a tu criterio, pero este no es el caso. OJO: nuevamente te digo que los parametros solo se ocupan en los solo en los chats. (no te compliques).
4. Mientras cumplas el Pep-8 no creo que habría problema, tambien puedes ocupar .cente() si te es util. Te dejo tambien un link por si llegas a tener problemas con cumplir la cantidad de caracteres maximos por linea [link](https://stackoverflow.com/questions/53162/how-can-i-do-a-line-break-line-continuation-in-python:).

Por ultimo te recomiendo fuertemente revisar la distribucion de puntaje de la T00, ya que ahi se muestra como se evaluara cada parte.
Espero haya quedado claro, si se me paso algo quedo atento.
Animo :)
