### ISSUE TITLE
Que es la bomba diamante?

### ISSUE THREAD

**Issue by enriquerussi** [IIC2233/syllabus#159]
Bomba diamante corresponde a la "suma" de la bomba cruz con la X o si es otro tipo diferente. Lo que pasa es que en el PDF, el ejemplo es justamente con r=3, pero no podría decir con certeza que forma tendría de ser otro radio de explosión.

**Comment by yuwet15** [comment]
Según yo tengo entendido debe ser como un rombo, ojalá no me haya equivocado que así lo hize

**Comment by vicentevegaulloa** [comment]
Hola @enriquerussi y @yuwet15 !

Exacto, debe ser como un rombo relleno, por lo que no es la suma de la bomba diamante y la bomba X. En el ejemplo del enunciado el radio coincidió con que la suma de ambas bombas fuera igual, pero no es asi. Espero haberlos ayudado 😄
