### ISSUE TITLE
Comparación entre un string y un atributo.

### ISSUE THREAD

**Issue by caantivil** [IIC2233/syllabus#159]
Buenas tardes, me pasa que tengo una lista de listas donde cada elemento de una sub_lista es un string, al comparar un elemento de mi sub-lista con un atributo, a pesar de ser idéntico al atributo, no lo reconoce.
Los comparo de esta forma :
self.blabla=="string"

**Comment by jeschuwirth** [comment]
Hola @caantivil,

Utilizar self.blabla=="string" debería funcionar, te recomiendo hacer lo siguiente:

Antes del 'if self.blabla=="string"'. Printea self.blabla y "string" de ese modo vas a poder comparar a mano las diferencias que tienen y quizás encuentres el error.

Si luego de imprimir ambos son iguales comenta un pantallazo del código y la ejecución (ojalá enviando la menor cantidad de código de tu tarea), para ayudarte de mejor manera.

Suerte!
