### ISSUE TITLE
Confusión multiples gastos de energia al crear objeto

### ISSUE THREAD

**Issue by TarekHirmas** [IIC2233/Syllabus#159]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo una gran confusión con respecto a la creación de objetos y creo que el enunciado no lo deja claro.

Los entrenadores buscan crear objetos y por eso gastan ENERGIA_CREAR_OBJETO, por otro lado, los objetos tiene un gasto asociado por crearlo GASTO_ENERGIA_XXXXX (XXXXX es el nombre del objeto). **Entonces si un entrenador busca crear un objeto como funciona el descuento de energías? Por intentar crear solo se gasta ENERGIA_CREAR_OBJETO y si es que la creación fue exitosa nuevamente se descuenta GASTO_ENERGIA_XXXXX?**
 O lo que quisieron decir en el enunciado es que al intentar crear un objeto se gasta ENERGIA_CREAR_OBJETO (**la cual es la misma que GASTO_ENERGIA_XXXXX, es decir, estos dos parámetros mencionados son iguales**) y por lo tanto si se crea o no el gasto solo será de GASTO_ENERGIA_XXXXX (equivalente a ENERGIA_CREAR_OBJETO).

Si no se entiende bien la duda la puedo reescribir.

Gracias

**Comment by MrNachoX** [comment]
Hola @TarekHirmas ! Es lo segundo que dices. Al momento de crear un objeto debes gastar GASTO_ENERGIA_BAYA, GASTO_ENERGIA_POCION o GASTO_ENERGIA_CARAMELO dependiendo del tipo. ENERGIA_CREAR_OBJETO es un nombre genérico para referirse al gasto de algún objeto (es lo mismo que GASTO_ENERGIA_XXXXX).
