### ISSUE TITLE
Duda con PEP8 | Largo de linea

### ISSUE THREAD

**Issue by ancontardo** [IIC2233/syllabus#159]
Cuando estaba corrigiendo mi tarea me di cuenta que PyCharm considera un largo de linea de 120 caracteres (creo), pero en los contenidos dice que debe ser de máximo 100. 

¿Cual es la norma que debemos considerar?
Gracias.

**Comment by DCCollao** [comment]
Hola! 

El largo que considera PyCharm es configurable, así que si lo deseas, lo puedes cambiar a 100; que es lo que deben considerar para su programa.
Éxito!
