### ISSUE TITLE
Descuento por archivos

### ISSUE THREAD

**Issue by bvallejo1** [IIC2233/syllabus#159]
El archivo de descuentos dice que está permitido tener 3 archivos de 600 lineas, si tengo un archivo con menos de 100 lineas puedo tener otro con más de 600? o debo pasar contenido de un archivo a otro para respetar ese máximo de 600 lineas?

**Comment by hbkim94** [comment]
Hola!

Tienes que respetar el máximo de 600 líneas independiente de tus otros archivos.

Ánimo!!

**Comment by MartinAracena** [comment]
O sea, eso solamente cuando te pasas de 3 archivos con 600 lineas no? Porque si tengo solo 1 archivo que pasa de las 600+ lineas, pero sigue respetando menos de 800 lineas. Entonces no deberia tener descuento no?

**Comment by gatochico** [comment]
En ese caso no hay descuento, a menos que hayan otros dos archivos con más de 600 lineas.
