### ISSUE TITLE
Uso de .format()

### ISSUE THREAD

**Issue by felipecr00** [IIC2233/Syllabus#159]
Como se puede usar format para imprimir en consola una tabla que va variando en datos e información?
Ej. para un __repr__
  '''             Mercado
         Precio    | Cantidad
 Ask|      {}       |       {}        |
  bid|      {}       |       {}        | '''.format(dato1,dato2,dato3,dato4)

Quiero ir mostrando la info pero si tengo mas ask's o mas bid's logicamente ira creciendo, o nose si hay otra forma mejor de hacerlo.
Saludos 💃

**Comment by stephichau** [comment]
Hint: acuerdate que puedes concatenar strings

**Comment by sebacruzd** [comment]
Si quieres hacerlo con format, revisa [esta página](https://pyformat.info/). Tiene muchos ejemplos de su uso.

**Comment by felipecr00** [comment]
Mmmm, lo que pasa es que me veo enfrentado a este problema, queria ver si con format existe la forma de escribir sobre algo que va iterando, o si es que existe una forma correcta de hacer lo que intento hacer jajajaja
```    
TypeError: __str__ returned non-string (type NoneType)

def imprimir_mercados(self):
        for i in self.ordenes:
            print("Precio: " + str(i.precio) + " |" + "Cantidad: " + str(i.cantidad) + " |" +
                  "Fecha match/acitvo: " + str(i.date_match) )

    def __repr__(self):

        #for i in range(len(self.usuarios_inscritos)):
        print("Mercado " + self.ticker)
        return self.imprimir_mercados()

**Comment by stephichau** [comment]
Si sobreescribes ```__repr__``` debes retornar un string. En tu caso, retornas un método que no retorna nada.

Intenta darle una vuelta al hint que te di antes!
