### ISSUE TITLE
Duda con "volver atras"

### ISSUE THREAD

**Issue by Alonsinho1** [IIC2233/syllabus#16]
Hola tengo una duda a cuando se menciona que debemos dar la opción de "volver atras" cuando se necesario. Que significa esto? significa que tenemos que del menu de juegos nos devolvamos al menu principal? o cuando el usuario este viendo los puntajes permita ver volver al menu principal?

**Comment by gatochico** [comment]
Hola! 

Con "volver atras si es necesario" nos referimos a casos como el segundo que propones, de poder volver atrás si se están viendo los puntajes y se desea ir nuevamente al menu principal. Otro ejemplo: Digamos que eliges destapar una baldosa y seleccionas esa opcion en el menu de juego. El juego te entrega la opcion de elegir la coordenada de que baldosa destapar, pero te arrepientes y ya no quieres destapar ninguna baldosa. En este caso, se deberia poder volver atrás al menú de juego con todas las otras opciones disponibles anteriores. 

En general, si llegas a hacer submenús en tu programa, debe haber un "volver atrás" que te lleve al menu principal de cada parte (Inicio/Juego). No es necesario que haya un volver atrás desde el menú de juego al menú de Inicio, ya que ambos son menús distintos, por decirlo así (: 

Saludos y exito! :computer:
