### ISSUE TITLE
Instalación de Jupyter

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233/Syllabus#16]
Hola, cómo puedo instalar Jupyter sin instalar Anaconda? intenté con pip3 y no me funciona, de hecho esto me arroja la consola
![image](https://user-images.githubusercontent.com/20783549/29086078-55f2c9bc-7c3f-11e7-8581-9ce18e1ebdc7.png)

**Comment by vijuarez** [comment]
Hola!

Para windows `pip` se ejecuta desde la consola de comandos (puedes llegar con TECLAWINDOWS + R y luego cmd -> aceptar), no desde powershell. Tienes que asegurarte que python y pip esten bien instalados, #7 puede tener información útil si te encuentras con algún problema. 

Saludos!

**Comment by sebacruzd** [comment]
Hola, te funciona pip de alguna manera?
Sino, es porque falta añadirle el PATH de Python a Windows.

La manera más fácil es que reinstales python y marques la casilla de "Add to PATH..." que aparece en la primera ventana del instalador.

La otra, es seguir [estas instrucciones](http://www.anthonydebarros.com/2015/08/16/setting-up-python-in-windows-10/), que no son para nada complicadas. Busca en la parte que se refiere a PATH.

Saludos!

**Comment by gabrielpinkman** [comment]
Gracias a todos!
