### ISSUE TITLE
Duda Autoevaluacion

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2233/syllabus#16]
Hola, buenas tarde/noche/mañana
 Gostaria de saber hasta cuando tenemos para entregar y donde la entregamos?

**Comment by Hernan4444** [comment]
Hola @csantiagopaz 

La autoevaluación es solo para las actividades no evaluadas a contar de la otra semana, por lo tanto se les avisará eventualmente el plazo y forma de realizar dicha autoevaluación.

Saludos ✌️
