### ISSUE TITLE
No me encuentra la ruta al escritorio en el sistema de control.

### ISSUE THREAD

**Issue by 141400mm** [IIC2233/Syllabus#16]
Me funcionó la instalación de phyton pero cuando quise encontrar la ruta al escritorio para correr el archivo setup_test esta no me la encuentra.
![Captura de pantalla 2021-08-23 013017](https://user-images.githubusercontent.com/89371019/130395519-57f869db-73b4-4ff7-a36e-49aa14cd8be2.png)

**Comment by fernandosmither** [comment]
### Hola! Bienvenid@ al curso. Para responder tu duda, primero te daré 2 hipótesis de por qué creo que no puedes encontrar la carpeta `Desktop`, y luego una solución general que te ayudará a explorar tu PC utilizando la consola.

<details>
  <summary>

#### Hipótesis 1: Tienes windows 10</summary>

En windows 10 por defecto viene activado el Onedrive, por lo tanto, la ruta que antes en windows 7 (y de toda la vida) para el escritorio era `C:\Users\{usuario}\Desktop` pasó a ser `C:\Users\{usuario}\OneDrive\Desktop` . 

De ser así, puedes cambiarlo entrando desde el explorador de Windows (explorer.exe) en el escritorio -> click derecho -> Propiedades y en la pestaña ubicación deberías ver lo siguiente:

<img src="https://user-images.githubusercontent.com/66154723/130473723-82207971-cfbc-4075-880e-ab7bfe6a8623.png" width="500px">

Si estás utilizando OneDrive, evidentemente te recomiendo no cambiarlo. De lo contrario, si no lo estás usando de manera activa, **en lo personal (OPINIÓN de @fernandosmither , no relacionada al curso)** te recomendaría [desactivar OneDrive por completo](https://support.microsoft.com/en-us/office/turn-off-disable-or-uninstall-onedrive-f32a17ce-3336-40fe-9c38-6efb09f944b0) por temas de rendimiento y privacidad.

</details>

<details>
  <summary>

#### Hipótesis 2: La carpeta se llama "Escritorio" y no "Desktop"</summary>

Si tu distribución de Windows se instaló en español (así lo veo en tu pantallazo) podrías corroborar que en mi caso, ambas hipótesis son ciertas. (La carpeta se llama 'Escritorio' y además está dentro de [..]Users\OneDrive.

</details>

<details>
  <summary>

### Solución: El comando `dir`
</summary>

En resumen el comando `dir` te permite visualizar el directorio actual, incluyendo archivos y carpetas. Si hubieses ejecutado el comando `dir`, no habrías tenido el problema, ya que te habrías dado cuenta de qué estaba pasando. A modo de ejemplo, te muestro lo que yo veo dentro de mi carpeta de usuario.

<img src="https://user-images.githubusercontent.com/66154723/130474761-f1eb7c8b-92f9-4ad9-a78c-ef5053ecd39b.png" width="300px">

Y ahí se ve claramente que está presente la carpeta OneDrive.

</details>


Si te interesa este tema, te recomiendo ver [este](https://dev.to/iamprogrammmer/command-prompt-basic-commands-you-should-know-cmd-4aj) artículo con 10 comandos útiles que se utilizan todo el tiempo!

Por favor coméntame si te resultó útil, y éxito en el curso!

**Comment by 141400mm** [comment]
Muy útil, no sabía que estaba usando OneDrive. Lo pude solucionar. Muchas gracias
