### ISSUE TITLE
Manejo de errores

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#16]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Mi duda es cómo hay que elegir cuales errores explicitarles al usuario, ya que en la tarea solo dice "se
debe notificar el error respectivo", pero no qué sucede al haber más de un error. ¿En estos casos hay que **explicitar cada error** o hacerlo según un orden de importancia, como por ejemplo **el orden en que son mencionados** en la tarea?

**Comment by magdalenanario** [comment]
Hola @MaxAl100 ! En el caso de que haya más de un error se deben notificar todos los errores, y queda a tu criterio el orden en el que son mencionados. 
Saludos!

**Comment by MaxAl100** [comment]
> Hola @MaxAl100 ! En el caso de que haya más de un error se deben notificar todos los errores, y queda a tu criterio el orden en el que son mencionados. Saludos!

Muchas gracias! Esto respondió mi pregunta :)
