### ISSUE TITLE
Diferencia tuplas v/s listas

### ISSUE THREAD

**Issue by fernandolalanne** [IIC2233/syllabus#16]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

[Describe tu duda de manera detallada, explicando los contenidos en cuestión y ojalá colocando código o un caso de uso de ejemplo]
Hola!! ayer estaba estudiando el módulo de listas y tuplas de la semana 1 (entendí las diferencias teóricas) y luego intenté hacer el ejercicio propuesto correspondiente a la materia sin embargo, me surgió la duda de cuál es la verdadera utilidad de una tupla si, en teoría, siempre puedo trabajar con una lista; ¿en qué casos estoy obligado a trabajar con tuplas?.

Muchas gracias!!
Saludos.
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by nicoguz** [comment]
Hola!!
Es una buena pregunta ya que a simple vista las listas parecen más útiles en cualquier situación. Sin embargo existen algunos casos en los que utilizar tuplas sería una mejor decisión.
Por ejemplo, si estás programando un sistema que almacena personas con sus datos (nombre, rut, sexo, etc.) trabajar con listas implica que eventualmente estos datos se pueden cambiar, lo cual puede producir errores en el sistema. Además, en el ejemplo anterior, un tercero con intenciones maliciosa puede 'hackear' el sistema y cambiar los datos con mayor facilidad.

En los casos que los datos sean inmutables por naturaleza (rut, marca de un auto, color del cielo, cosas que son de cierta forma y no se pueden cambiar, etc.) es recomendable utilizar tuplas sobre listas.

Otra ventaja que tienen las tuplas es que por ser de un largo definido y tener sus elementos definidos estas ocupan menor memoria y toman menos tiempo cuando se busca un elemento en ellas. Si estas programando un sistema que trabaja con una gran cantidad de datos, es muy recomendable utilizar tuplas sobre listas (si es posible) por el tiempo y memoria que se ahorra a la hora de ejecutarlo.

En [esta página](https://towardsdatascience.com/python-tuples-when-to-use-them-over-lists-75e443f9dcd7) hacen una comparación en código de la diferencia de tiempo y de memoria para la lista v/s la tupla.

Espero que te haya servido!!!
Avisame si sigues con dudas.
