### ISSUE TITLE
Error al abrir archivo post.csv: UnicodeDecodeError

### ISSUE THREAD

**Issue by EmeraldMP** [IIC2233/syllabus#16]
Al abrir el archivo post.csv me aparece este error, como puedo solucionarlo? (al abrir los otros archivos no presenté este error)
"Exception has occurred: UnicodeDecodeError
'charmap' codec can't decode byte 0x9d in position 1527: character maps to <undefined>
  File "C:\Users\princ\Desktop\Programacion_Avanzada\EmeraldMP-iic2233-2020-1\Tareas\T00\Extra", line 2, in <module>
    posts1 = archivo.readlines()"

Gracias!

**Comment by RonaldoSosa** [comment]
Me aparece un error similar, también solo en el archivo posts.csv  
Traceback (most recent call last):
  File "C:\Users\ripley\Desktop\Tarea 0.py", line 14, in <module>
    for cada_post in leer_posts:
  File "C:\Users\ripley\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1527: character maps to <undefined>

**Comment by benjavicente** [comment]
Tuve el mismo problema!

Resulta que, por defecto, [python utiliza la codificación predeterminada del sistema](https://docs.python.org/3/library/functions.html#open). En el caso de Windows, utiliza [Windows-1252](https://es.wikipedia.org/wiki/Windows-1252), o como aparece en el mensaje de error, `cp1252`.
> File "C:\Users\\{usuario}\AppData\Local\Programs\Python\Python37\lib\encodings\\**cp1252**.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1527: character maps to

Para arreglar esto, hay que entregar a la función `open` el *keyword argument* `encoding`, con la codificación de caracteres correspondiente, que en este caso es `UTF8`.

**Comment by RonaldoSosa** [comment]
Me funcionó, muchas gracias!

**Comment by EmeraldMP** [comment]
También me funcionó, te pasaste!

**Comment by drosselot** [comment]
Me pasó lo mismo, pero ahora que hice eso,  solo puedo correr el programa una vez. La segunda vez me tira el mismo error pero en vez de 'charmap' dice 'UTF8'

**Comment by igbasly** [comment]
Hola @drosselot 😄:
Efectivamente como tú compañero @benjavicente decía, este error se puede deber a un mal formato de lectura de los archivos. Esto deriva de cómo, dónde y en qué lenguaje se escriben los archivos que tú quieras abrir, ya que ciertos idiomas como el español posee caracteres que no son reconocidos por la codificación por defecto asociada al inglés.

La recomendación para abrir archivos, especialmente en español, es utilizando el *keyargument* del método `open`: `encoding`, con la codificación deseada como argumento, donde se recomienda principalmente **'utf-8'**.

Un ejemplo de esto sería:
```python
open(“filename.ext”, “r”, encoding=“utf-8”)
```

Espero que puedas resolver el problema y no dudes en escribir si esto persiste :ok_hand:.

**Comment by drosselot** [comment]
Ya lo pude solucionar. El problema era lo mismo, solo que cuando abría el archivo para escribir, no tenía el parámetro de encoding, por lo que el programa dejaba de ser con encoding "utf-8". Gracias.

**Comment by jorgemayol** [comment]
tenia el mismo problema pero al solucionarlo con utf-8, ya no me deja hacer split sobre las ", "  y no lo puedo pasar a listas

**Comment by Juampisaez** [comment]
tengo este error PermissionError: [Errno 13] Permission denied:
y para abrir el archivo ocupe archivo_post = open("posts.csv", "w", encoding="utf-8")

a diferencia de los demas, le puse una "w" en vez del "r"
Ayudaaa

**Comment by igbasly** [comment]
Hola @jorgemayol!
No entiendo bien tu problema, ¿es acerca del formato de codificación del archivo o ya un problema de manejo del contenido del archivo?
De todas formas agradecería un poco más de información.

Quedo atento,
Ian :v:

**Comment by jorgemayol** [comment]
Hola @igbasly !!
Ya lo logre solucionar, muchas gracias!!
