### ISSUE TITLE
Problema con Jupyter

### ISSUE THREAD

**Issue by Toridonco** [IIC2233/Syllabus#16]
- **Sistema Operativo:**
- windows 11
- **Programa a instalar:**
Jupyter
- Descripción del problema:
- al ejecutar el comando  jupyter notebook o python3 -m notebook, no se abre ninguna ventana, y tambien sale este texto
" No web browser found: Error('could not locate runnable browser')"

**Comment by Hernan4444** [comment]
Hola @Toridonco 

Te recomiendo revisar las issues ya existentes, en particular:
* https://github.com/IIC2233/Syllabus/issues/3

Donde justamente se trata dicho problema 😄

Saludosヾ(＾-＾)ノ

ps: no hay que olvidar revisar las [reglas del foro](https://github.com/IIC2233/Syllabus/issues/1) donde la primera es buscar si es que hay una issue repetida antes de crear una nueva, así tal vez puedas llegar a la solución de tu problema muuucho antes 😸
