### ISSUE TITLE
Problema con error en tests públicos de la A0

### ISSUE THREAD

**Issue by MeuDeuz** [IIC2233/Syllabus#16]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Al ejecutar los tests públicos solo me salta el error "La ejecución no entrega el output esperado según las instrucciones", pero ya revisé el enunciado y tengo tanto el orden como lo que entiendo de contenido (porque en cargar los ítems no se si hago lo que me piden por ejemplo). Entonces no se si no entiendo algo o es porque en un punto use 2 líneas para lo que piden y debe ser en 1 o algo más

**Comment by Hernan4444** [comment]
Hola @MeuDeuz 

En este caso, recomiendo [revisar el _test_](https://github.com/IIC2233/Syllabus/blob/main/Actividades/AC0/tests_publicos/test_salidas_terminal.py#L22) donde puedes ver cuál es el `print` esperado (está la opción con subscripción y sin subscripción). Luego, ejecutar tu archivo main.py y contrastar si la ejecución del main tiene lo mismo que el tests. Si no tienen lo mismo, puede ser que tu `main.py` tiene algo que no corresponde o no está 100% correcto. 

En otro caso, si tienes lo mismo y el tests igual dice que hay un error. Entonces recomiendo subir tu actividad a tu repositorio privado (usar git para esto), y así un miembro del cuerpo docente puede echarle un ojo para verificar si hay un error en el código o en el tests.

Quedamos atentos, ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ

**Comment by MeuDeuz** [comment]
Gracias profe ahí salió, lo que si el enunciado no especifica lo que hay que hacer así que, ¿Le digo que falta y se corrige o se deja esta Issue y listo?

**Comment by Hernan4444** [comment]
Hola @MeuDeuz 

Menciona por aquí qué faltó para que quede un registro. (Y ahí vamos a evaluar con los profes si es necesario subir nuevamente ese enunciado o queda en esta issue dicho error).

Quedamos atentos 🦖
Saludosヾ(＾-＾)ノ

**Comment by MeuDeuz** [comment]
En la primera línea en el ítem 4.2 del código de ejemplo dice "Crear usuario...", pero en los tests me da error si no se imprime y en ninguna parte se especifica que se imprima

**Comment by Hernan4444** [comment]
Hola @MeuDeuz 

Lo que ocurre es que el mismo método de `crear_usuario` se indica que deben imprimir su información usando la función `print_usuario`. Y por eso en el ítem 4.2 no se indica que hagan dicha acción, dado que ya fue realizada de forma "interna" en `crear_usuario`.

Avísanos si cumpliendo con esa restricción, el punto 4.2 ahora si está correcto.
Saludosヾ(＾-＾)ノ

**Comment by MeuDeuz** [comment]
Perdón profe no se leer JWHSHSYWYH había escrito algo que no era por tabular y no releer la línea 😭

**Comment by Hernan4444** [comment]
Hola @MeuDeuz 

No te preocupes, es mejor preguntar y verificar si fue solo una falta de re-leer una parte o efectivamente había un error por nuestro lado y era necesario corregir lo antes posible.

Saludosヾ(＾-＾)ノ 🦖
