### ISSUE TITLE
Tiempo y colas

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#16]
En el archivo 03-colas.ipynb dice:

"Buscar el elemento 5000000 en el deque se demoró     0.005168914794921875 segundos
Buscar el elemento 5000000 en la lista se demoró     6.29425048828125e-05 segundos
La búsqueda en deque fue 82.12 veces el tiempo de list."

¿Es más rápida una lista o una queue?

**Comment by MrEarle** [comment]
De la [documentación de Python](https://docs.python.org/3/library/collections.html#collections.deque):

_Deque:_
> Deques are a generalization of stacks and queues (the name is pronounced “deck” and is short for “double-ended queue”). Deques support thread-safe, memory efficient **appends and pops from either side of the deque with approximately the same O(1) performance in either direction**.

Osea que un deque es rápido para acceder/modificar elementos que están en los extremos (Tanto el extremo izquierdo como el derecho).

_Lista:_

> Though list objects support similar operations, they are optimized for fast fixed-length operations and incur **O(n) memory movement costs for pop(0) and insert(0, v) operations** which change both the size and position of the underlying data representation.

Las listas requieren de mayor procesamiento para acceder a los elementos del extremo izquierdo.

Esto significa que para agregar/eliminar/acceder elementos en los extremos de la estructura, los deque son más rápidos y eficientes.

Pero en el Deque:

> Indexed access is O(1) at both ends but **slows to O(n) in the middle**. For fast random access, use lists instead.

Por lo que acceso a elementos que se encuentran en la mitad de tu estructura son más rápidos en una lista que un deque.


Aquí es donde viene la decisión del programador, elegir qué es lo que quiere privilegiar en términos de rendimiento para su aplicación, acceso a los extremos o acceso a los elementos en el centro.

**Comment by jmwielandt** [comment]
Muchas gracias!
No había visto el e-05 ^_^U

**Comment by fgbruna** [comment]
@jmwielandt no cierres tus issues apenas te las responden, alguien mas puede tener la misma duda y es mas fácil que se mantengan abiertas para que todos las puedan ver apenas entran a la pagina, deja que l@s ayudantes y o profesores se preocupen de cerrar las issues 😀

**Comment by jmwielandt** [comment]
@fgbruna ah, ok
Solo lo hacía porque las reglas del foro lo piden ("Una vez resuelto el problema, dar las gracias y cerrar la issue.") jaja
