### ISSUE TITLE
Grupos actividad 02

### ISSUE THREAD

**Issue by aeperalta** [IIC2233/Syllabus#16]
Hola, no me encuentro en el archivo de la actividad 2. Se puede solucionar?

**Comment by josemlira** [comment]
Tengo el mismo problema

**Comment by bamavrakis** [comment]
Hola! Ambos tienen repo?

**Comment by sebacruzd** [comment]
Hicieron pull correctamente?
Si aun no saben usar bien git pueden ver los grupos [acá](https://github.com/IIC2233/Syllabus/blob/master/Actividades/AC02/Readme.MD)

**Comment by josemlira** [comment]
Yo si tengo

**Comment by bamavrakis** [comment]
Te acabo de enviar un correo. Saludos!

**Comment by aeperalta** [comment]
sí, yo también creé mi repo

**Comment by fcgfaura** [comment]
Hola, yo tampoco estoy en la lista :/

**Comment by jtagle2** [comment]
@aeperalta, creaste tu repositorio? O te registraste en la [página](https://iic2233.github.io/) del curso y te asignaron un repositorio privado?
Si es lo primero, ~debías~ debes registrarte en la página del curso para que te den un repositorio para el curso.
Saludos

**Comment by bamavrakis** [comment]
Todos los que no están en la lista el día de hoy tendrán que hablar con el ayudante que está pasando la lista para explicarle su situación y que los agregue a mano. También deberán enviarme a mi la actividad por correo antes de las 17:00. Saludos!

**Comment by aeperalta** [comment]
@jtagle2 tienes razón, pensé que con solo registrarme en github bastaba, pero ya entré a la pagina del curso en registro y otorgué los permisos. Con esto, el repositorio privado debería aparecer en un tiempo? Gracias por la info, saludos!
