### ISSUE TITLE
Duda acerca de archivo en .gitignore: Funcion imprimir_tablero

### ISSUE THREAD

**Issue by MathiasPrett** [IIC2233/Syllabus#160]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. Tengo una duda acerca de los archivos que pide el enunciado de la T1 añadir al .Gitignore . Se trata del archivo imprimir_tablero.py, donde no entiendo por que nos piden ignorar su subida al repositorio, si de todas formas debemos importar la función contenida e implementarla en nuestro código. Será que ustedes manejan su propio archivo y función para imprimir el tablero, y efectivamente no debemos subir ese archivo al repo?? No me queda claro. Gracias!

**Comment by Mcroquevielle** [comment]
Hola!! Este archivo no se tiene que incluir porque nosotros lo vamos tener cuando corrijamos. Esto no afecta tu código ya que vamos a poner los archivos con los mismos nombres en la carpeta de tu tarea
