### ISSUE TITLE
Tipos de Arenas

### ISSUE THREAD

**Issue by MariaJoseSilva** [IIC2233/Syllabus#160]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola!

Mi duda es respecto a cuando se describen los tipos de arenas (sec 4.2.1 pag 10), por ejemplo, en el caso de la Arena Mojada parte por decir "cuando llueve la arena normal se transforma en arena mojada" y luego termina por explicar los cambios en la forma en que los excavadores pueden encontrar ítems estando en una arena mojada. 

Mi pregunta es si al decir "cuando llueve..." es solo para dar contexto o se refiere a cuando ocurre el evento de lluvia. Esto afectaría en el caso en que el juego inicie con una arena magnética, como al iniciar no ha ocurrido ningún evento todavía, implicaría que aún no ocurre el evento lluvia, en este caso ¿se debe cambiar la probabilidad en que los excavadores encuentran items o esto solo cambia cuando se tiene una arena mojada luego de haber ocurrido un evento lluvia el día anterior?

Muchas gracias!

**Comment by Benjeeeh** [comment]
Hola!
Esa parte del enunciado es básicamente para recalcar lo que dice en la parte del evento de lluvia, en que transforma la arena normal a mojada. La siguiente descripción es solo el efecto que tiene la arena mojada sobre la probabilidad de encontrar ítems, por lo que este efecto es solo dependiente de la tierra y no del evento lluvia, por lo que si llueve y estás en arena magnética estas probabilidades no cambian y la lluvia solo afectaría a los parámetros de los excavadores por ocurrir un evento (bajar felicidad, etc).

Saludos y éxito con la tarea!

**Comment by Benjeeeh** [comment]
Hola!
La primera parte de la frase es básicamente para recalcar lo que dice en la parte del evento de lluvia, en que transforma la arena normal a mojada. La siguiente descripción es el efecto que tiene la arena mojada sobre la probabilidad de encontrar ítems, por lo que este efecto es dependiente de la tierra y no del evento lluvia, así que la arena magnética si debería compartir el mismo comportamiento de la arena mojada en cuanto a la probabilidad de encontrar objetos.
Saludos y éxito con la tarea!
