### ISSUE TITLE
Problemas con "utf-8"

### ISSUE THREAD

**Issue by Cschavez** [IIC2233/Syllabus#160]
Hola! Añadí el encoding =" utf-8" y al probarlo la primera vez me resultó bien, luego solo me sale error, pero al parecer no es de mi mismo programa y no he podido solucionarlo, esto es lo que me dice en el error: 

```
Traceback (most recent call last):
  File "C:/Users/Camila/Desktop/Camila/Cschavez-iic2233-2018-1/Tareas/T01/prueba2.py", line 6, in <module>
    chau.leer_galaxias("galaxias.csv")
  File "C:\Users\Camila\Desktop\Camila\Cschavez-iic2233-2018-1\Tareas\T01\Chaucraft.py", line 16, in leer_galaxias
    primera_linea = linea.readline()
  File "C:\Users\Camila\AppData\Local\Programs\Python\Python36\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 51: invalid continuation byte
```
Busqué en internet y lo cambie por 'latin-1' pero eso no lee las tildes del archivo, que es finalmente lo que quiero lograr hacer. No sé que más puedo hacer. Estoy trabajando en Pycharm.
Muchas gracias!

**Comment by Arcoirisky** [comment]
Por esas casualidades ¿Intentaste reiniciar Pycharm? Es raro que te funcione una vez y luego muera

**Comment by Cschavez** [comment]
Si lo reinicie y sigue igual. Leí en internet que podía ser por algo sobre el formato de mis archivos(? No entendí muy bien y traté con las soluciones que proponían y nada

**Comment by Cschavez** [comment]
También intenté reiniciando el computador. Tampoco me lee los planetas, o sea si no pongo "utf-8" me funciona todo super bien solo que las palabras con tildes salen con caracteres raros.
esto me sale:
![image](https://user-images.githubusercontent.com/37157327/38467690-8546a5b6-3b12-11e8-9fcb-0327d484eb6c.png)

**Comment by Arcoirisky** [comment]
Tenemos todo parecido, viste [esta](https://stackoverflow.com/questions/19591458/python-reading-from-a-file-and-saving-to-utf-8) respuesta?

**Comment by Cschavez** [comment]
Graciaas! ahí me funciono :)

**Comment by Cschavez** [comment]
Pucha ya no, de nuevo funcionó solo una vez y luego volvió a tirar el mismo error

**Comment by Arcoirisky** [comment]
Damn incluido el de ignorar el error? (El último comentario del link si no me equivoco) Veré si alguien más sabe del problema O:!

**Comment by Arcoirisky** [comment]
Ya probaste abrir archivos con with open? 
En plan:

with open(galaxia, 'r', encoding = 'utf8') as data:
       #Haces Lo que quieras aquí con el archivo y la función lo cierra solo

**Comment by Cschavez** [comment]
así los estoy abriendo

**Comment by Cschavez** [comment]
Ya lo arreglé, fue un error mio en otra función que estaba corriendo. Perdón por las molestias y muchas gracias por la ayuda :D

**Comment by entamburini** [comment]
El problema era que no estabas usando el  `encode` para guardar los archivos, lo dejo aquí por si alguien más tiene este error :)

**Comment by sahermosilla** [comment]
El nombre de la galaxia andrómeda, la ó con tilde me sale como un caracter japonés muy raro jaja, no sé lo qué pasa :(

**Comment by Arcoirisky** [comment]
@sahermosilla ¿Y eso te lanza error o sólo aparece así? Si al hacer "ó" == tuletrachina te da True no pasa nada O: a mí los / me los cambiaba por ¥ pero puede ser el idioma del computador.
