### ISSUE TITLE
Duda nueva partida

### ISSUE THREAD

**Issue by camaruri** [IIC2233/syllabus#160]
Tengo una duda cuando se parte una nueva partida, el jugador parte con algo de dinero predeterminado, o con algun vehiculo estandar.
Mi duda es porque si no tiene dinero ni auto no puede empezar a jugar, ya que no puede empezar niguna carrera

**Comment by tomasgv** [comment]
Hola!

Al iniciar una nueva partida, el jugador deberá escoger un vehículo inicial (el cual no tendrá costo y puede ser de cualquier tipo) y le tendrá que asignar un nombre, así como está señalado en la sección 6.3.1:

![Captura de pantalla 2019-09-04 a la(s) 19 22 15](https://user-images.githubusercontent.com/48303402/64300028-62e13780-cf49-11e9-83c8-fda5bdfa67df.png)

Saludos!

**Comment by dpacevedo** [comment]
Hola!

Ante esta issue me surgió una duda, el día martes en la ayudantía preguntaron sobre el dinero que tiene un jugador que decide crear una partida, y dijeron que era un parámetro que nosotros podíamos definir e indicar en el archivo parametros.py, para que sea posible comprar autos posteriormente. Esto sigue siendo así o el jugador parte sin dinero?

Gracias de antemano!!

**Comment by lily416** [comment]
@dpacevedo Queda a su criterio si al crearse una nueva partida se obtiene un dinero inicial o no. En el caso de que se obtenga deben indicar la cantidad de dinero como un parámetro.

Saludos y éxito con la tarea. 👋🛵

**Comment by Crespy98** [comment]
el nombre del vehículo tiene alguna restricción como el nombre del usuario?

**Comment by tomasgv** [comment]
Si! Tiene las mismas restricciones que el nombre de usuario, como se menciona en la _footnote 16_: 

![Captura de pantalla 2019-09-10 a la(s) 14 06 00](https://user-images.githubusercontent.com/48303402/64634666-293e7f80-d3d4-11e9-9049-c550cf1b1bde.png)
