### ISSUE TITLE
Abrir archivo posts.csv

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#160]
Hola!
Hace poco muchos teníamos el problema que al abrir el archivo posts.csv, no se podía porque le faltaba un código, donde nos dijeron que lo solucionáramos así: open ('archivo','r', encoding='utf-8'), el tema es que al principio el archivo se abre y funciona todo ok, pero cuando el archivo posts.csv empieza a recibir cambios especialmente la acción "eliminar un posts", y luego quiero abrir el archivo nuevamente para leerlo, éste produce el mismo error que se mencionada antes (a pesar de que estoy abriendo el archivo de la misma manera). Qué hago?

Bueno, yo probando como abrirlo nuevamente cambie la forma de como abrirlo sacándole el "encoding" quedando de la forma "open ('archivo','r')" Y ABRE, FUNCIONA.!
Pero el problema es que cuando ustedes prueben el código van a utilizar este archivo, pero no se va a abrir si está como  "open ('archivo','r')", se abre con "open ('archivo','r', encoding='utf-8')" . Pero esto pasa solo al principio.....
Entonces cuando el archivo reciba cambios que especialmente me pasa con "eliminar un posts", ya no se podrá abrir de la misma forma :(.
Qué hago?

Les adjunto la foto del error por si acaso.
![Captura](https://user-images.githubusercontent.com/59337116/77231918-ae250580-6b7c-11ea-9e5d-314d1040315f.PNG)

**Comment by gatochico** [comment]
Hola! Revisando tu código, veo que no incluyes el encoding utf-8 en los modos write y append. ¿Has probado agregando eso?

**Comment by jeschuwirth** [comment]
Agregando a lo que dijo @gatochico, el error esta resuelto en la issue #16 

Avisa si se resuelve :)
