### ISSUE TITLE
Borrar un archivo despues de un git push

### ISSUE THREAD

**Issue by panchotarud** [IIC2233/syllabus#160]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, cree un archivo de para probar funciones de la T0 y lo agregué al .gitignore, aún así se subió a mi repositorio en github. Hay alguna manera de borrarlo? o da lo mismo? Por que no está referenciado en el ReadMe, puesto que no es parte del código de mi programa.

Ojalá me puedan ayudar, saludos.

**Comment by RafaelEdwards** [comment]
Hola, para eliminar archivos de tu repositorio puedes utilizar git rm. Acá te dejo un link donde explican como usarlo:

https://www.bufa.es/git-borrar-archivos-carpetas/

Espero haberte ayudado y suerte con tu tarea :)

**Comment by panchotarud** [comment]
Gracias!
