### ISSUE TITLE
Como utilizar iter y next 

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#160]
En el punto 5 no entiendo a que se refeire con que nuestras implementaciones tienen que ser "iterables e iteradores", especificamente no entiendo como utilizar `__iter__` y `__next__`.

**Comment by stephichau** [comment]
@KnowYourselves Te recomiendo revisar el material de clases :). [Revisar aca](https://github.com/IIC2233/contenidos/blob/master/03-FUNCTIONAL/3-Built-ins-Functional.html)

**Comment by AmbrosioV** [comment]
404, not found.
Tambien me interesa saber bien de esto, salu4

**Comment by hanavarrete** [comment]
@AmbrosioV  Como @stephichau les recomienda, eso está en el material en la parte de functional. Revisen el siguiente link: https://github.com/IIC2233/contenidos/tree/master/05-FUNCTIONAL
