### ISSUE TITLE
archivos.csv

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus#160]
Como lei en otras issues, los archivos se pueden cambiar el orden de los headers, por lo tanto se mueven todas las columnas que hay dentro de los archivos. Pero tengo la duda de en acciones.csv esta el header "input", esa columna esta en formato "recurso;cantidad". 
Mi duda esta en que ese DENTRO de ese header no se cambia nada o si? Porque ya estaria modificando "headers" dentro de headers.
Ejemplo:

1,0,Recolectar recurso,oro;2
Las columnas por comas se pueden mover, pero no la de ";".

**Comment by gatochico** [comment]
Hola! 
Si te refieres a que pongamos, por ejemplo, "2;oro"en vez de "oro;2", puedes asumir que eso no ocurrirá. Saludos!
