### ISSUE TITLE
Partida Nueva T00

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#160]
Hola!, no me queda claro si para volver a jugar una partida nueva, se tiene que dejar una opcion, o cuando se acaba una partida automatico volver a partir un juego nuevo, o si puedo dejarlo con hacer control+F5  para correr el programa

**Comment by kadroguett** [comment]
Holaa @sa-Appel cuando se acabe una partida debes mostrar  el resultado junto al puntaje final y volver al menú de inicio, lo dice el enunciado en la sección 2
