### ISSUE TITLE
Duda PEP8

### ISSUE THREAD

**Issue by Cristobal-Hevia** [IIC2233/Syllabus#161]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Cuando escribo un mensaje en el código en el formato: mi_cultivo.predio() # mensaje explicando la función 
y este mensaje pasa los 100 caracteres, también infringe el formato PEP8?

**Comment by FernandoTFH** [comment]
Yo entiendo que si cuenta, dado al propósito de la regla de que toda la información esté visible y no tengas que moverte para los lados para ver todo la información. Pero puedes usar la comillas para poner tu información. Si te fijas, en los test, se tiene comentarios encerrados entre tres comillas. Este es un ejemplo de uno de los test:     
   """
  Caso esquina, bloque pequeño. Plano vacío 7x7, código_predio = 7.
  código_cultivo = 5, dimensiones 1x1, plantar en (6,0).
  """
De esta manera puedes poner tus comentarios dentro de los 100 caracteres, y el algunos editores, cuando te paras encima de una función o método que tiene estos mensajes entre las tres comillas, el editor te muestra ese mensaje.
