### ISSUE TITLE
Recompensas por mejor vuelta

### ISSUE THREAD

**Issue by macagamerre** [IIC2233/syllabus#161]
Hola! 
En el enunciado de la tarea, en la sección del flujo del juego dice:
"Durante una competencia, se medir´a el tiempo que demora cada competidor en dar una vuelta. Como recompensa parcial, el menor tiempo por vuelta obtendrá dinero y experiencia". 

De esto entiendo que los contrincantes también tienen recompensa, pero al revisar contrincantes.csv no se cuenta con el parámetro de dinero. 

Entonces, tengo dos dudas:
1. ¿Entendí mal y los contrincantes no reciben recompensa?
2. El hecho de que sea "recompensa parcial", ¿quiere decir que no se mantiene luego de finalizar la competencia?

Gracias desde ya!!

**Comment by jeschuwirth** [comment]
Hola @macagamerre:

te respondo tus dudas,

1. los contrincantes no reciben recompensa, sólo evitan que la gane el jugador.
2. Si el jugador sale primero en una vuelta y gana dinero, ese dinero **no** lo pierde al terminar la carrera, por lo tanto **no** es una recompensa parcial.

Suerte en la tarea!
