### ISSUE TITLE
Duda respecto al menu: List index out of range

### ISSUE THREAD

**Issue by angedvq** [IIC2233/Syllabus#161]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, al testear el menu, sin importar que tablero indique, me sale el error list index out of range. No tengo del todo claro por qué puede estar pasando esto. Además, me surge la duda sobre qué tableros podemos usar como testeo, aquellos que están en tableros.txt o algún otro?

**Comment by Arielmanriquez** [comment]
Es un poco dificil responder esto si no puedo ver tu codigo, pero si dice list index out of range con cualquier indice, es probable que la lista este vacía, verifica que la lista se este llenando de manera correcta.
