### ISSUE TITLE
Edad excavador 

### ISSUE THREAD

**Issue by rominaarancibia** [IIC2233/Syllabus#161]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! No me queda claro que sucede si la edad del excavador no esta entre 18 y 60. Se cambia de excavador en ese caso? O bien se acomoda la edad tipo si tiene 17 que tenga 18. Gracias!

**Comment by Benjeeeh** [comment]
Hola! Lo recomendable es que siempre se mantenga dentro de los valores de 18-60 años, tal como se menciona en la parte 4.3 de Entidades: 
![image](https://user-images.githubusercontent.com/78326186/232161185-2500b546-ea3a-4f99-84e2-7a81124d887b.png)
Por ende, si se agrega edad de acuerdo a X circunstancia y ya se encuentra en 60 años, que se mantenga ahí, de manera de que este valor actúe como un límite. Por otra parte (por tu ejemplo), en el archivo excavadores.csv no se encuentra ningún excavador menor a 18 años.

Saludos y éxito!
