### ISSUE TITLE
Duda sobre ventana principal

### ISSUE THREAD

**Issue by TatyFlores** [IIC2233/Syllabus#161]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Mi duda es sobre cuando se despliega la ventana principal para elegir el modo de juego, el nombre, etc. Porque el enunciado dice que se ejecuta cuando se ingresa un usuario correctamente en una partida nueva, pero en el flujo del programa aparece que una vez elegida la opción de jugar se redirige a la ventana para elegir la dificultad y el nombre. ¿Debemos pedir un usuario y compararlo con los del archivo de puntajes? 

**Descripción en 4.5 Ventana Principal del Enunciado**

![image](https://user-images.githubusercontent.com/101210892/167525447-23574e76-4bea-4a8a-9793-ff01ae49eeb5.png)

**Descripción en 2. Flujo del programa.**

![image](https://user-images.githubusercontent.com/101210892/167526148-a540707d-92b1-4c73-be4d-1070419fe117.png)

**Comment by nzamorano** [comment]
Hola @TatyFlores, no debes revisar que el usuario esté en _puntajes.txt_, pues puede ser que sea un usuario nuevo. Solo debes revisar que el nombre de usuario cumpla la restricción alfanumérica y que sea no vacío.
