### ISSUE TITLE
Datos perdidos en ids de user y fecha de match en orden

### ISSUE THREAD

**Issue by AngelMatias** [IIC2233/Syllabus#161]
Que hacer si algunas ordenes del archivo users no tienen id y tampoco fechas de match en el archivo order ??

**Comment by iqacevedo** [comment]
Hola,

En cuanto al archivo user.csv, me imagino que te refieres a algún usuario que no tengan ninguna id de orders, si ese es el caso significa simplemente que no tiene ninguna.
En cuanto a las fechas de match de ordes.csv, si no esta, simplemente significa que esa order aun no ha hecho match.

Saludos!
