### ISSUE TITLE
Uso de namedtuples en OOP

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#161]
Hola! Cuando en una clase quiero usar una namedtuple para guardar los atributos del objeto, tengo que definir la namedtuple fuera de la clase, en el mismo método de la clase en el que lo voy a usar o en un método aparte de la clase?

**Comment by danckoo1** [comment]
Hola! Diría que depende del código que estés creando, si necesitas la namedtuple para diversos métodos de tu código, quizás sea mejor crearla como una variable en el main y entregársela a cada método cuando los llames, sin embargo si solo un método la utiliza, lo mejor sería definirla localmente dentro del método, saludos:)

**Comment by kalarconvl** [comment]
@danckoo1 Y cuando la usan varios métodos dices que la almacene fuera de la clase o como un método de la clase aparte? Gracias!

**Comment by danckoo1** [comment]
En ese caso desconozco si existe una opción más correcta que la otra. En lo personal crearía un método que la retorne, ya que si la guardo en una variable fuera de la clase la mayor parte del tiempo estaría gastando memoria innecesaria. (De todas si trabajas con pocos datos ambas opciones son igual de eficientes 🤷🏽‍♂️)
