### ISSUE TITLE
Archivos a subir al repositorio y Readme: parametros.py (librería externa o propia)

### ISSUE THREAD

**Issue by colobos** [IIC2233/syllabus#161]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

¿Qué archivos se deben de subir al repositorio personal (todos los .csv y .py? o solamente los archivos .py modificados y/o creados) y el modulo de parametros.py, se adjuntan en el readme como librería externa o propia?,
Muchas gracias.

**Comment by IgnaciaJ** [comment]
Hola @colobos ! Al repositorio personal se suben todos los archivos .py creados y/o modificados (incluyendo parametros.py ya que sin este tu programa no correrá), los archivos csv los debes ignorar en el .gitignore ya que los ayudantes usaremos archivos csv con estructura idéntica. 
En cuanto al README parametros.py cuenta como una librería propia, ya que tu la modificas y no viene incluida como un módulo de python :) Para escribir tu README te recomiendo que te guies por los ejemplos subidos al syllabus!
Éxito en tu tarea!!

**Comment by colobos** [comment]
Ok, muchas gracias!!

**Comment by Bizonte28** [comment]
No hay descuento por el no uso de .gitignore en esta ocasión, cierto? Si subí los archivos csv no debería haber problema?

**Comment by IgnaciaJ** [comment]
@Bizonte28  A partir de la T1 habrá descuento por el .gitignore!
