### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#161]
No entiendo que tengo que poner en esta parte del Readme, como se cual es la parte X1, X2 , X2_2, etc 
![readme](https://user-images.githubusercontent.com/48294819/55690594-9d768200-5961-11e9-8af2-7db07234f7c0.PNG)

**Comment by gatochico** [comment]
Hola!
Aunque no es necesario que sigas ese formato al pie de la letra (por ejemplo, puedes poner una lista de todo lo que *no* hiciste y decirnos que todo lo demás está completamente funcional), esos *<X<sub>n</sub>>* usualmente corresponden a los índices y subíndices del enunciado de la tarea. Un ejemplo:

* Parte **3 (Civilizaciones)**: Hecha completa
* Parte **4 (Funcionalidades)**: Me faltó hacer <insertar qué cosa faltó>
    * Parte **4.1 (Ataque y defensa)**: Hecha completa
    * Parte **4.2 (Tecnologías)**: Me faltó hacer <insertar qué cosa faltó>

Te recomiendo seguir esta estructura, ya que así se nos hará más fácil corregir tu tarea, algo que también te beneficiará a tí. Saludos!
