### ISSUE TITLE
Dudas Tarea 2

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2233/Syllabus#161]
Hola!
- Puedo usar string.split(";") para leer el archivo?
- Sobre el diagrama de clases: 1) Aún no entiendo, en qué formato tengo que entregarlo? 2) Qué pasa si entrego el diagrama una semana antes y de ahí a la entrega del código cambio cosas?
Graciaas

**Comment by hanavarrete** [comment]
@ChayoPerez  Tal como se explica en la issue #162  debes castear en tus propias estructuras. Te recomiendo ver el ejemplo de esa issue en específico. Saludos!
