### ISSUE TITLE
Que hacer con los archivos.csv (al finalizar el codigo)

### ISSUE THREAD

**Issue by faaceituno** [IIC2233/syllabus#161]
Hola, al comienzo del código abro los archivos y los utilizo en un formato para poder realizar todos los pasos de la tarea.
Mi duda es si al correr el codigo, se debe devolver los archivos actualizados en formato .csv o se debe crear nuevos archivos o no es necesario exportar archivos actualizados?

**Comment by gatochico** [comment]
Hola! 

Sí, al terminar de correr tu código los archivos deben reflejar cualquier cambio que se realizó en el programa (añadir un usuario, un post, seguir a alguien, etc...). Además, recuerda que deben **actualizarse los archivos originales** (debe haber siempre 1 sola copia de cada archivo.) y deben **mantener en todo momento el formato original**.

Éxito con tu tarea! 🐦

**Comment by faaceituno** [comment]
Vale, muchas gracias!

**Comment by dchahuan** [comment]
Una pregunta parecida entonces, uno abre el archivo solo una vez y lo deja como variable global o se abre y se cierra cada vez que es necesario?

**Comment by gatochico** [comment]
@dchahuan Resuelto en la issue #174
