### ISSUE TITLE
prograpost " "

### ISSUE THREAD

**Issue by rmaguilera** [IIC2233/syllabus#162]
un prograpost que solo sea " " cumple el minimo de 1 caracter??

un prograpost que sea " "*141 se excede del maximo? aun que no diga nada?

**Comment by matiasmasjuan** [comment]
Hola @rmaguilera !
Recuerda que el **enunciado** señala que un carácter puede ser cualquier tipo de símbolo, incluyendo los espacios. Por lo tanto, un **prograpost** que solo sea  " " **sí** cumple con el requisito de un carácter,  y un **prograpost** con " "*141 **no** cumple con los requisitos ya que excede el máximo permitido. En todo caso, esta pregunta fue contestada en la [Issue #72](https://github.com/IIC2233/syllabus/issues/72).
Éxito con la tarea!

**Comment by rmaguilera** [comment]
Muchas gracias!
