### ISSUE TITLE
Duda sobre Clases Abstractas y __init__

### ISSUE THREAD

**Issue by etoteiza** [IIC2233/syllabus#162]
Hola!! tengo una pequeña duda sobre el uso de las clases abstractas. Tengo entendido que estas funcionan como un 'molde', también tengo entendido que se crear métodos abstractos. pero como funciona en el caso del constructor, cómo debo manejarlo ahí? Debo crear también cómo método abstracto, o bien una vez que cree una subclase de la clase abstracta armo el constructor con los atributos de éstos? 

Muchas gracias de antemano!

**Comment by gatochico** [comment]
Hola! Todo depende de que quieras hacer:
- Puedes no poner `__init__` en la clase padre, y solo ponerlo en la clase hijo y todo funcionara bien :+1: :
-![Screenshot from 2019-09-06 01-45-33](https://user-images.githubusercontent.com/37161120/64403889-2fd19d80-d048-11e9-9236-69f771a9a8c4.png)
![Screenshot from 2019-09-06 01-46-53](https://user-images.githubusercontent.com/37161120/64403922-42e46d80-d048-11e9-9bcc-1cbbddac9db1.png)

- Digamos que quieres que todas las clases que hereden de padre tengan el mismo `__init__`, y para no tener que repetir código por cada clase hija que tengas, podrías poner un `__init__` en la clase padre:
![image](https://user-images.githubusercontent.com/37161120/64404118-da49c080-d048-11e9-9b7b-f4f503b2089e.png)
![image](https://user-images.githubusercontent.com/37161120/64404159-0107f700-d049-11e9-8dcf-a9fdbd253e68.png)

O, si quieres ser muy muy muy precavido, podrías ponerle también un `@abstractmethod` al `__init__` :eyes: :
![image](https://user-images.githubusercontent.com/37161120/64404451-fdc13b00-d049-11e9-931e-9a1b341d5844.png)
![image](https://user-images.githubusercontent.com/37161120/64404461-04e84900-d04a-11e9-8549-5987c8d80f26.png)

El único ejemplo donde se me ocurrió que ponerle `@abstractmethod` al `__init__` en una clase abstracta haría una gran diferencia es cuando tienes una clase abstracta que **solo tiene `__init__`** y no tiene más métodos abstractos. En ese caso específico, si no pones el decorador sobre el init, podrás instanciar la clase abstracta de forma directa, cosa que no debería pasar.
Si no tienes ese caso, puedes usar cualquiera de las opciones que mostré arriba. 

Saludos y disculpa la demora!

**Comment by etoteiza** [comment]
Muchas gracias!! 😊 👌
