### ISSUE TITLE
como borrar un objeto y duda con escritura de archivos

### ISSUE THREAD

**Issue by ptflores1** [IIC2233/Syllabus#162]
Intente hacerlo con `del` pero no lo borra, estoy intentandolo desde un metodo de otra clase y solo borra la variable y no al objeto en si. Hay alguna forma de hacerlo de manera que se borre de todo el programa ? 

Sobre los archivos tengo un metodo que abre un archivo en modo append, escribe y al final cierra, lo que no entiendo es porque los cambios se ven después de cerrar el programa y no después de que el metodo haya cerrado el archivo

**Comment by sebacruzd** [comment]
Hola,

Para eliminar un objeto, todas las referencias hacia él deben ser eliminadas. No basta con eliminar la "original" o primera que hayas hecho.
Para más info, mira las respuestas de [esta página](https://stackoverflow.com/questions/16686788/python-how-to-kill-a-class-instance-object).

Sobre los archivos, qué haces con ellos? Los abres constantemente para revisar si hay cambios o lo haces solo una vez?

**Comment by ptflores1** [comment]
Gracias!
@sebacruzd  Los abro constantemente para escribir

**Comment by sebacruzd** [comment]
Qué tipos de cambio son los que no ocurren?
En todo caso, si es para que se pase de trader a inversionista, está permitido que el cambio ocurra cuando se vuelva a abrir el programa.
