### ISSUE TITLE
Cómo hacer que el label del alien quede posicionado detrás del label de la mira

### ISSUE THREAD

**Issue by SVenegasA** [IIC2233/Syllabus#162]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Saludos, yo definí 2 Qlabels pero no estoy consiguiendo hacer que la mira quede apuntando al alien y que este no tape la imagen de la mira

**Comment by CristobalPerez-Cotapos** [comment]
Hola!! Por lo que entiendo quieres controlar en que orden se da el solapamiento de los elementos, de tal forma que puedas definir que queda al frente y que queda al fondo. 
Esto se puede hacer de varias formas, una alternativa es reordenar el orden de creación de lo labels, llamando después a los que quieres que queden al frente.
Otra alternativa que te recomiendo más es hacer uso del metodo raise_() de los Qlabels, que los lleva al frente, puedes leer más sobre esto en la documentación de pyqt5 (https://doc.qt.io/qt-5/qwidget.html)
Avísame si te resulta alguna de estas alternativas 😄
