### ISSUE TITLE
Error al llamar a funcion

### ISSUE THREAD

**Issue by aayale** [IIC2233/syllabus#162]
Hola! Cree una funcion en un modulo distinto de donde lo estoy llamando y al escribir print(Modulo.Nombrefuncion)
Me aparece el siguiente error
function Nombrefuncion at 0x0000019F69664708
 ¿que puedo hacer para que funcione?

**Comment by DCCollao** [comment]
Hola @aayale!
Lo que estás haciendo es intentar imprimir directamente la función, sin hacer el llamado a ella. Es como si le estuvieras preguntando al computador cómo se llama la función en lugar de pedirle que la ejecute!

Es parecido a hacer:
```Python3
print(len)
```
(esto da como output `<built-in function len>`)

En lugar de 
```Python3
print(len(lista))
```
(esto da como output el largo de `lista`.

Lo que te falta para poder ejecutar correctamente tu función es agregarle los paréntesis al final, junto con los argumentos que esta reciba!

Por ejemplo, en caso de que no reciba argumentos:
`print(Modulo.Nombrefuncion())`

Otro ejemplo, pero esta vez recibiendo 2 argumentos:
`print(Modulo.Nombrefuncion(argumento1, argumento2)`

Quedo atento a cualquier duda!

**Comment by aayale** [comment]
Aaaa buenisimo, muchas gracias!
