### ISSUE TITLE
No puedo subir mi programa al git

### ISSUE THREAD

**Issue by Fermario** [IIC2233/syllabus#162]
Cuando escribo cualquier comando en el git, me aparece el siguiente mensaje:

"Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue."

He verificado que no tengo ninguna otra ventana de git abierta y también reinicié el equipo, pero el problema persiste.

**Comment by jeschuwirth** [comment]
Saludos,
En el siguiente link se encuentran posibles soluciones a tu problemas

https://stackoverflow.com/questions/38004148/another-git-process-seems-to-be-running-in-this-repository

Personalmente, aunque no sea muy buena practica, si git te sigue mandando problemas después de probar de todo, puedes guardar tu código en el escritorio, clonar nuevamente el repositorio anterior, luego pegar tu código y hacer add/commit/push. 

En general los errores de git te dicen como solucionarlos. Pero entiendo que hay algunos mensajes que no son tan sencillos de leer.

Suerte con la entrega y ojalá te ayude :)

**Comment by bimartinez** [comment]
Hola!

Complementando la respuesta de @jeschuwirth. Probablemente se abrió un editor de texto al hacer un commit y lo cerraste de mala manera, lo cual dejó creado un archivo `index.lock` en tu carpeta `.git` el cual deberás borrar como se menciona en la solución propuesta [acá](https://stackoverflow.com/questions/38004148/another-git-process-seems-to-be-running-in-this-repository)
