### ISSUE TITLE
archivos en crear_predios

### ISSUE THREAD

**Issue by Vicu20** [IIC2233/Syllabus#162]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by vgalfaro** [comment]
Hola! vi que editaste la issue y borraste la duda, cerraré esta para mantener el orden, si tienes otra duda abre otra issue por favor, gracias!!
