### ISSUE TITLE
mas de un objeto con el mismo nombre

### ISSUE THREAD

**Issue by solebravo** [IIC2233/Syllabus#162]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! tenia la duda que si un mismo entrenador puede poseer dos del mismo objeto, tanto porque creo un objeto igual a otro que ya tenia o porque creo dos iguales. Esta duda me surge ya que cuando un entrenador logra crear de manera exitosa un objeto de un tipo especifico, se le debe entregar aleatoriamente uno de tal tipo, por lo que no se si debiese eliminar los que se podrian repetir o no.
Saludos

**Comment by franco-anfossi** [comment]
Hola! a mi me surge la misma duda y si es que se puede (que un entrenador tenga dos o mas objetos iguales) al momento de ingresar al menú, utilizar objetos, estos tienen que aparecer independientemente o solo un nombre para la cantidad que haya.
Ejemplo (imaginemos que tiene 2 objetos "raro")
Así:
[1] raro
[2] raro
...
_______
O así
[1] raro
...
*lo elige*
[1] raro (sigue apareciendo porque le queda otro)
...
______

**Comment by MrNachoX** [comment]
Hola @solebravo ! Sí, un entrenador puede tener dos objetos iguales. En el issue #115 ya se había respondido.

@franco-anfossi con respecto a tu duda, el formato del menú utilizar objetos queda a tu juicio. Los menús mostrados en las imágenes del enunciado son de referencia, puedes hacerlos como quieras mientras cumplas con lo mínimo que pide el enunciado. Si lo haces como el segundo ejemplo, debes mostrar de alguna manera la cantidad de objetos repetidos para que el jugador sepa cuantos tiene disponibles.
