### ISSUE TITLE
Borré mi Token de GitHub y saqué otro 

### ISSUE THREAD

**Issue by jahernandez2** [IIC2233/Syllabus#162]
Hola. Borré el token que saqué al comienzo del curso porque expiró (no sabía que se podía regenerar el mismo) y saqué otro. Ahora puedo subir mis avances a mi repositorio, pero me sigue saliendo esto (adjunto foto 1) en Git. He buscado y no se me ocurre que hacer para poder solucionarlo definitivamente. Quedo atento a cualquier cosa. 
Saludos.

![image](https://user-images.githubusercontent.com/62116520/135859890-07eba020-5d96-409b-b993-ba9343f66105.png)

**Comment by 1862507J** [comment]
Hola!, no soy experto en los tokens y git, pero tengo el resto de la tarde libre por si quieres que te ayude a solucionar tu problema. Solo escríbeme al Discord (En discord estoy como 1862507J) cuando estes disponible :raised_hands:
