### ISSUE TITLE
Leer archivos csv 

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#162]
Para poder pasar la información de los archivos csv a mi clase de listas es legal usar el comando `csv.reader(file)` e iterar sobre el?

**Comment by FernandoPieressa** [comment]
No puedes usar estructuras de python, por lo tanto tienes que castearlas en tus propias estructuras.

![screenshot_2017-03-27-00-15-24](https://cloud.githubusercontent.com/assets/13782155/24339575/e838b074-1282-11e7-93e4-e0bb1262ca4b.png)



saludos!

**Comment by KnowYourselves** [comment]
Comprendo la parte de args y ya la implemente!, pero tengo otra duda, en el código de ejemplo `separa2` sigue siendo de todas formas un objeto de clase list, por eso, es ilegal ocupar listas al hacer un for loop con el metodo reader?, es decir sería ilegal ocupar esas listas como argumento para transformar la información y a mi lista?

**Comment by sebacruzd** [comment]
Es ilegal que se reciban como argumento, debes recibirlas como *args de la manera especificada en el ejemplo.
