### ISSUE TITLE
Duda sobre las funciones cargar (AC2)

### ISSUE THREAD

**Issue by Toridonco** [IIC2233/Syllabus#162]
Tengo una pregunta sobre las funciones cargar película y géneros. Es sobre la descripción de las funciones, estas dicen " retornando instancias de Película según el contenido del archivo." ¿Esto se refiere a que la función debe retornar algo del tipo 
"yield Película (id_pelicula, titulo, director, estreno, rating)" o algo diferente?
Pregunto esto ya que me dan estos errores al correr el test:
"py:153: ResourceWarning: unclosed file <_io.TextIOWrapper name='peliculas_1.csv' mode='r' encoding='cp1252'>
  datos = funciones.cargar_peliculas('peliculas_1.csv')
ResourceWarning: Enable tracemalloc to get the object allocation traceback". Y no se si es que el test falla o es otro error.

**Comment by abraxvs** [comment]
Hola @Toridonco el **__Resource warning__** que te aparece es porque no cerraste correctamente el archivo en la función mencionada, recuerda que puedes hacer: nombre_del_archivo.close() para conseguir esto. Además te comento que dicha función debe retornar, si no me equivoco, instancias de las __'named tuples'__ *Película* y *Género*.
Saludos!
