### ISSUE TITLE
Cuando elegir al programón para simular ronda (Antes de conocer el programón rival o después)

### ISSUE THREAD

**Issue by VicenteGarayR** [IIC2233/Syllabus#163]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Mi duda es cuando el usuario tiene que elegir el programon con el cual va a luchar, ya que si este se escoge antes es muy complicado ganar la liga, ya que depende mucho de la suerte, en cambio si uno lo elige cuando ya sabe contra que programon se va a enfrentar, ganar la liga dependería más si conoces los tipos de los programones

**Comment by MrNachoX** [comment]
Hola @VicenteGarayR ! Primero se debe elegir el programon para luchar y después de eso se asignan aleatoriamente las parejas de la ronda. Esto significa que al momento de elegir programon el entrenador no sabe con quién va a luchar y tal como dices, ganar el campeonato depende en cierto grado de la suerte del entrenador.
