### ISSUE TITLE
usernames tienen que ser unicos tomando en cuenta mayusculas y minusculas?

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#163]
Hola! Si ya existe un usuario con username "mynigga", puede registrarse  un nuevo usuario con username "Mynigga" ? Es decir, la diferencia en una letra a mayuscula o minuscula cuenta como username unico? O todos los usernames deben tener derechamente al menos un caracter distinto?

**Comment by ayudantesIIC2233** [comment]
Queda a tu criterio, saludos!

**Comment by bedefrunner** [comment]
ah pues muchas gracias amiguitos
