### ISSUE TITLE
Duda función crear_predios de DCCultivos caso extremo

### ISSUE THREAD

**Issue by Igufu** [IIC2233/Syllabus#163]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Saludos!, tengo una duda respecto a la función `crear_predios`, mi duda es si se puede asumir la existencia de un archivo llamado `predios.txt`, ya que mi código arrojará un error si ese archivo no existe. Hay una manera que conozco de verificar la existencia de un archivo pero no es parte de la materia. Dado esto puedo asumir que siempre existirá el archivo? Gracias!

**Comment by vgalfaro** [comment]
Hola! no puedes asumir que existirá, ya que debes ser capaz de controlar el caso donde no se pueda cargar la info (i.e. que el archivo no exista, hint: revisar la librería os), también, te recomiendo leer #139 donde se habla sobre el tema. Saludos!

**Comment by mxmauoc0** [comment]
> Hola! no puedes asumir que existirá, ya que debes ser capaz de controlar el caso donde no se pueda cargar la info (i.e. que el archivo no exista, hint: revisar la librería os), también, te recomiendo leer #139 donde se habla sobre el tema. Saludos!

¿Eso quiere decir que puedo usar la librería "os" (import os)? :) gracias

**Comment by vgalfaro** [comment]
Sí, puedes ocupar la librería os, las librerías permitidas están en #10, de hecho, ahí aparece el método que te podría servir :).
