### ISSUE TITLE
Duda Import Funciones

### ISSUE THREAD

**Issue by aayale** [IIC2233/syllabus#163]
Hola, al importar **Funciones** ¿tengo que hacer el path, o eso es solo para archivos?

**Comment by jitorralba** [comment]
Hola @aayale! 
Si te refieres a funciones creadas por ti en un módulo aparte (es decir, otro archivo .py), debes importarlas de la misma forma que una librería (`from archivo import funcion`), esto en caso de que este se encuentre en el mismo directorio que el .py al cual lo quieres importar, en caso contrario, deberías usar el método `sys.path.insert`, para moverte de directorio, pero no lo veo necesario, ya que de igual forma necesitas subir todos los archivos, así que lo mejor es tenerlo todo en el mismo directorio.
Avisame si te quedo claro!

**Comment by aayale** [comment]
Sí, clarísimo, muchas gracias!
