### ISSUE TITLE
Duda compra de vehiculos

### ISSUE THREAD

**Issue by ivan-sandoval** [IIC2233/syllabus#163]
Hola,
En el enunciado sale un ejemplo para la compra de vehiculos y muestran los 4 tipos de vehiculos, con sus respectivos precios. Mi duda es si solo se deben ofrecer esos 4 vehiculos y si yo escoger los precios para cada uno, o bien se deben mostrar un numero random de vehiculos y con precios y caracteristicas distintas.

**Comment by jeschuwirth** [comment]
Hola @ivan-sandoval,

Las características de los autos vienen dadas por el MIN y MAX en el diccionario en parametros.py

![image](https://user-images.githubusercontent.com/37160256/64304921-ae044600-cf5b-11e9-8573-74b85f8f24e2.png)

Si no lo has visto te recomiendo revisar el parametros.py que les entregamos. 

En cuanto al precio de los vehículos se nos paso a los ayudantes, por lo que queda a criterio de los alumnos. Te recomiendo colocar el precio de cada vehículo como parámetro en parametros.py, de ese modo cuando se llega al menú correspondiente puedes ofrecer los 4 tipos de vehículos con sus respectivos precios y luego asignarle los parámetros respectivos dependiendo del MIN y MAX.

Si te quedaron dudas sigue comentando en la issue :)

Suerte en la tarea!

**Comment by ivan-sandoval** [comment]
Gracias, ya entendía lo de los parametros, era solo la duda de los precios y cantidad de vehículos.
Por ahora todo me quedó claro 😀
