### ISSUE TITLE
"Error" en vscode 

### ISSUE THREAD

**Issue by thiaaare-sp** [IIC2233/syllabus#163]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, luego de subir la tarea quise probarla de nuevo en mi pc y al hacerlo me aparece una serie de "líneas" que no entiendo, no sale que es un error como tal porque de hecho el programa sigue funcionando bien después de estas "líneas"
No sé si es algo de mi pc o si esto también pasará cuando revisen mi tarea o si afectará en algo :( 
Adjunto foto, aquí se ve solo un trozo, pero este se repite unas 3 o 4 veces 
<img width="960" alt="Error " src="https://user-images.githubusercontent.com/69615603/113215607-794c9380-9251-11eb-8101-29ccec2bb7ac.png">

**Comment by aaossa** [comment]
Hola @thiaaare-sp , ¿pudiste solucionar este problema? 🤔 La verdad no lo he visto antes, pero no ocupo ese editor así que no estoy seguro de qué podría ser. El error parece ser con algo relacionado con la consola más que con tu código, ¿te había ocurrido antes o es algo nuevo? Si pudiste solucionarlo avisa cómo lo lograste 😅

**Comment by thiaaare-sp** [comment]
Hola! sí y no jajaj después de cerrar todo y volver a probarlo dejó de salir, así que no sé qué habrá sido :sweat_smile:
