### ISSUE TITLE
Última colección de hace días

### ISSUE THREAD

**Issue by sahermosilla** [IIC2233/Syllabus#163]
Al probar con los archivos galaxias.csv y planetas.csv que generé hace unos días, resulta que su ultima recoleccion fue hace mas de una semana, si colecto entonces ¿Debo obtener por todos los segundos de todos los dias que pasaron? si hago eso obtendria millones de cada uno.
¿Al probar el programa los ayudantes generarán los archivos ahi mismo?

**Comment by IchottMano** [comment]
@sahermosilla Hola!
Efectivamente si la última recolección fue hace semanas, obtendrás muchos recursos, se cuenta cada segundo desde la última recolección.
Saludos!
