### ISSUE TITLE
descansar Excavador y energia recuperada

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2233/Syllabus#163]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado se nos dice que cuando los excavadores lleguen a energía 0 deben descansar una cantidad de días y recargan la energía a 100. 
Dado lo anterior si por ejemplo mi excavador debe descansar 5 días **¿Es necesario que recupere los 100 de energía al quinto día?**o  **¿Puede recuperar los 100 de energía a penas empieza a descansar pero manteniendo que trabaje hasta que terminen sus días de descanso?

**Comment by panchouc** [comment]
Hola!

Lo importante es que cuando ya pueda cavar de nuevo, tenga nuevamente toda la energía.

**Comment by pulpaulaa** [comment]
@panchouc Tengo una duda similar sobre los excavadores descansando. 
En la sección 3.2.1 se indica que al simular un día del torneo, se indica el orden en que se debe simular (cavar, encontrar item y ocurrencia evento). Si al cavar un excavador se queda sin energía, ¿debe descansar inmediatamente? o ¿empieza a contar desde el día siguiente? Y quizás se me pasó en alguna parte del enunciado, pero me parece que no leí nada sobre qué implica estar descansando en términos de encontrar items y ocurrencia de eventos. ¿Los excavadores que están descansando encuentran items? Y si ocurre un evento, ¿pierden felicidad?
Además aprovecho de preguntar si importa cuándo se imprime el mensaje _"Nombre_excavador decidió descansar..."_ al imprimir el resultado del día, dado que en el ejemplo está al final del mensaje, pero me preguntaba si podría imprimirse entre medio de otros mensajes como los de los metros cavados, ya que puede ser que se le acabe la energía en ese momento.

Gracias!

**Comment by panchouc** [comment]
Hola @pulpaulaa. Respecto al gasto de energía, este se realiza al final del día, ya que es un gasto por día excavado.
![image](https://user-images.githubusercontent.com/94400598/232554254-277cc015-5f77-4fea-9015-4a5cc0173108.png)
Entonces, si queda sin energía al final del día 2, en el día 3 no puede trabajar y debe descansar por el tiempo que se le asigne. Respecto a lo de encontrar ítems y cavar mientras descansa estas acciones no ocurren.

 Respecto a la felicidad, esto también debería de afectarles, ya que el enunciado dice que le afecta a todos los excavadores, por lo que independiente de si está descansando o no, debería de verse afectado. 

Lo de imprimir el mensaje que mencionas respecto al descanso, eso si aparece en el flujo del programa, por lo que debes indicar todos los excavadores que están descansando.
![image](https://user-images.githubusercontent.com/94400598/232554802-99474eaa-5ba0-485f-bf27-b9b27dbd72a8.png)

**Comment by BenzoylMorexide** [comment]
Tengo otra duda con el tema de gastar energía. Si mi excavador tiene al día dos 30 de energía y al excavar perdería 50 de energía, **¿debiese permitirle excavar, haciendo que gaste solamente la energía que tiene disponible?** ¿o debiese **hacerlo descansar** en ese día dos para que recupere su energía?
Gracias!

**Comment by panchouc** [comment]
Dependiendo de en que parte coloques el gastar energía, suponiendo que esto se hace al final del día, luego de que haya ejecutado todas sus acciones. Podría trabajar con esa energía, y al final del día cuando le restes toda la energía, al día siguiente ya debería estar descansando.

**Comment by BenzoylMorexide** [comment]
Es correcto si hago la suposición de que excave y ahí gaste la energía y luego si es que le queda, busque items?

**Comment by Mcroquevielle** [comment]
Hola! Una pregunta
Según lo que entendí, en el Enunciado primero se cava y después se gasta energía, por lo que, al momento de gastar energía determino cuando un excavador decide descansar.
Considerando esto, cuando uso un Item que deja la energía en cero antes de simular día, ahí debería poner que se pone a descansar? O al elegir simular día se revisa si tiene energía antes de cavar? No se si se entiende mi pregunta, pero al final en esos casos de quedarse sin energía por items no entiendo bien qué debería hacer

**Comment by MariaJoseSilva** [comment]
Hola! 
Respecto al mismo tema, la fórmula que determina los días de descanso es int(edad/20), para los excavadores que tienen menos de 20 años, el resultado de la fórmula sería 0. Teniendo eso en consideración ¿ los excavadores de 18 y 19 años no necesitan descansar?
Gracias

**Comment by panchouc** [comment]
Respondiendo a sus dudas

@BenzoylMorexide, no es correcto ya que se contradice con lo que dice el enunciado. El tema del descanso se ve al finalizar el día.
@Mcroquevielle Dado que el tema del gasto de energía se ve al final del día, el excavador puede cavar aun cuando no queda energía ya que no está decansando. Pero al llegar el final del día va a empezar a descansar dado que ahí se realiza la verificación.
