### ISSUE TITLE
Funciones que retornan estructuras prohibidas

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233/Syllabus#163]
Si necesitas usar alguna función perteneciente a algún módulo de la librería estándar de Python que
retorne alguna de las estructuras prohibidas, deberás desempaquetar los valores de la estructura mediante el operador * y luego usarlos en tu propia implementación. Por ejemplo, el siguiente código es válido:

``` python

class MiLista:
    def __init__(self, *args):
        for arg in args:
            # do something
            pass
separa2 = "lorem ipsum dolor sit amet".split(" ")
lista_legal = MiLista(*separa2)
lista_legal.mi_append("consectetur")

```

Saludos!

**Comment by Jaluco** [comment]
Se considera válido que mi lista reciba la lista de python sin el *?

**Comment by sebacruzd** [comment]
No, tu lista debe recibir *args tal como está ejemplificado. (Su __init__ recibe *args)
No debería haber gran diferencia en trabajarlo de la manera que dices y como debería ser.

**Comment by malopez16** [comment]
Debe recibir necesariamente el *args el __init__? o puede ser un método cualquiera que reciba el *args

**Comment by stephichau** [comment]
@malopez16 se puede en cualquier método. Acá se explica bien el uso de [*args](https://pythontips.com/2013/08/04/args-and-kwargs-in-python-explained/) :)

**Comment by cho19** [comment]
¿se pueden utilizar map/filter/reduce? con este mismo sistema (ej: List(*map(lambda ...)))

**Comment by Hernan4444** [comment]
@cho19 si puedes usarlo mientras el iterable usado en esas funciones sea creación tuya y el resultado se lo entregues a una estructura de datos tuya. `MyLista(map(funcion, MyLista))`
