### ISSUE TITLE
Permission error al abrir un archivo

### ISSUE THREAD

**Issue by kipasten** [IIC2233/syllabus#163]
Hola! 
Me pasó que al momento de correr el programa y abrir el archivo usuarios.csv, que hasta el momento podia editar y abrir sin problemas, me salta un PermisionError, diciendo que no tengo permiso para poder abrir el archivo, 
![image](https://user-images.githubusercontent.com/62030666/77232604-dd3d7600-6b80-11ea-812e-46f433b541b7.png)
también ocurre ese error al editar el archivo seguidores

**Comment by kipasten** [comment]
se solucionó, pero aun no se porque ocurre ❓

**Comment by MatiasDuhalde** [comment]
Hola!

**Comment by kipasten** [comment]
muchas gracias 😄
