### ISSUE TITLE
Import circular

### ISSUE THREAD

**Issue by Lucas-Purcell** [IIC2233/Syllabus#163]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Mi archivo tablero.py importa funciones de un archivo que creé yo con funciones útiles funciones.py, que a su vez utiliza la clase Tablero por lo que si importo Tablero al comienzo del documento creo un import circular. Si coloco el import dentro de la función justo en la parte donde se utiliza el problema se soluciona pero no tengo claro si esto es una mala práctica y se me descontará por esto o no. Quería saber cual es la forma más apropiada de resolver este problema.

**Comment by Arielmanriquez** [comment]
Un import que no esté al inicio del programa se considera una mala practica. Lo que puedes hacer seria definir las funciones que utilizan la clase tablero como metodos, o utilizar un tercer archivo para las funciones que necesiten de tablero.py.
Ten en cuenta que los archivos tienen un limite de lineas de 400, pero no hay un limite de archivos, asi que si te organizas mejor de esa forma, siempre puedes crear un archivo extra para poner otras funciones.

**Comment by Hernan4444** [comment]
Hola,

Complementando esta respuesta, la cual justamente es una excelente práctica (tener varios archivos para modularizar todo). Otra opción es enfrentar la referencia circular usando solo `import` y no `from XX import YY`.

Por ejemplo, digamos que tengo 2 archivos `tablero.py` y `modulo1.py`

```python
# ESTE ARCHIVO ES tablero.py
import modulo1


class Tablero:
    
    def saludar(self):
        modulo1.funcion()
        print("saludar")


if __name__ == "__main__":
    tab = Tablero()
    tab.saludar()

```

```python
# ESTE ARCHIVO ES modulo1.py
import tablero


def funcion():
    print(tablero.Tablero())
    print("funcion")
```

¿Qué va a pasar aquí? Cuando hacemos `import` solo se genera un llamado al archivo, pero no estamos buscando línea por línea  algun dato en específico. Si es que ejecutamos `tablero.py` el import hará que llamemos a `modulo1` y su import hará que se llame a `tablero.py`, pero este último ya fue llamado al momento de ejecutar el archivo, así que ya está listo.  El único **pero** de todo esto, es que se puede generar una recursión de llamados. Por ejemplo, si `saludar` de `Tablero` llama a `modulo1.funcion` y `modulo1.funcion` utiliza el método `saludar` de `Tablero`, entonces eso será una recursión que no acabará. Así que mucho ojo con eso.

La duda que puede surgir es: ¿porqué con `from` no funciona 🤔  ? Porque `from` obliga a leer línea por línea el archivo para encontrar lo solicitado. Por ejemplo, si tuvieramos 2 archivos (`tablero.py` y `modulo1.py`)  donde cada uno tiene:
* en tablero.py: `from modulo1 import funcion`
* en modulo1.py: `from tablero import Tablero`

Cuando ejecutemos tablero.py, ese `from` nos obligará a cargar `modulo1` para buscar `funcion`, pero justo se encuentra con la línea `from tablero import Tablero` y ahora debe ir a `tablero.py` para buscar `Tablero`.... pero ahí se encuentra con `from modulo1 import funcion` y bueno, ahí comienza la recursión de referencia circular.

## Opción 2

Y bueno, otra opción es que simplemente tu función reciba una instancia de tablero. Algo como:

```python
import funciones

class Tablero:
     def solucionar(self):
           funciones.solucionar(self)
```

```python
# Este es funciones.py

def solucionar(instancia_tablero):
     print(instancia_tablero)
```

Y con eso, tu función "solucionar" tiene uns instancia de tablero el cual posee todos los métodos que tu necesites.

## Comentario final


En lo personal, recomiendo fuertemente utilizar la solución entregada por @Arielmanriquez  de generar un tercer archivo con las funciones necesarias para tus 2 archivos originales, así queda más claro que ambos (tanto tu módulo para solucionar, como tu módulo de tablero) necesita ciertas funciones en común.

Quise extender esta respuesta porque puede servir de apoyo para las siguientes tareas donde tal vez alguien más tenga dificultades con referencia circular y así los podemos re-dirigir a esta issue.

¡Mucho éxito con la tarea!
Saludosヾ(＾-＾)ノ
