### ISSUE TITLE
¿Se puede usar una librería que no está ni en librerías permitidas ni no permitidas?

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#164]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

¿Se puede usar una librería que no está ni en librerías permitidas ni no permitidas?

**Comment by nzamorano** [comment]
Hola, @Fernanda1232123, si quieres usar una librería que no está en las librerías permitidas y no permitidas, debes preguntar en la misma issue #146 con el formato que se dice al inicio de esta. Siempre asume que una librería no se puede usar hasta que se diga lo contrario y no dudes en preguntar cualquier cosa 😉.
