### ISSUE TITLE
Duda distribución puntares

### ISSUE THREAD

**Issue by itplanella** [IIC2233/syllabus#164]
Hola! En la distribución de puntajes, hay una parte que dice: "Utiliza correctamente relaciones de agregación pilotos." Quería saber a que se refiere ya que no la entiendo mucho. Gracias de antemano.

**Comment by jeschuwirth** [comment]
Hola @itplanella,

Acaban de editar la repartición de puntajes, para que revises de nuevo, si tienes dudas sobre que es una relación de agregación lo puedes ver en el ppt de la [clase 2](https://github.com/IIC2233/syllabus/blob/master/Clases/Semana%2002%20-%20OOP.pdf), desde la diapo 17 a la 19.

Si no te queda muy claro como funciona puede seguir comentando en la issue :)

Suerte!
