### ISSUE TITLE
"problema" al correr codigo T00

### ISSUE THREAD

**Issue by fddelabarra** [IIC2233/syllabus#164]
Es una pregunta mas persona, la cosa es que corro el codigo, llega una parte de un input, entrego input y el codigo o programa se detiene, no me salta error alguno, pero no logro averiguar por que se detiene el programa

**Comment by Tito0906** [comment]
Hola @fddelabarra, en la línea 306 de tu programa estás realizando una comparación entre un _int_ y un _string_. Debes convertir la variable _conteo_ con _str(conteo)_. Por otro lado, una vez arreglado este error, tu programa **no** esta borrando correctamente los post, por lo que te recomiendo revisar la función.

Saludos y éxito en la tarea!

**Comment by fddelabarra** [comment]
ok, muchas gracias!

**Comment by fddelabarra** [comment]
acabo de revisar y lo borro sin problema, solo me confundi con el nombre del archivo que reescribió, o habia otro? no lo encuentro :c (si esta pregunta no puede hacerse, lo lamento)

**Comment by Tito0906** [comment]
Holaa, cuando revisé el error anterior no revisé el problema que causaba por qué la función no eliminaba los posts. Revisando nuevamente parece que efectivamente el problema era el nombre del archivo.

Éxito en la tarea!

**Comment by fddelabarra** [comment]
Gracias!!!!
