### ISSUE TITLE
Pep-8 y # comentarios 

### ISSUE THREAD

**Issue by emivenezian** [IIC2233/Syllabus#164]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

En el formato pep8, se incluyen los comentarios en el conteo de los 100 caracteres por linea? Todo mi codigo cumple con eso, pero si cuento los caracteres de los comentarios muchas lineas se pasan de los 100.

**Comment by Mcroquevielle** [comment]
Hola!! Los comentarios no cuentan al contar los caracteres

**Comment by Hernan4444** [comment]
Hola @emivenezian 

Lamento indicar esto, pero la respuesta entregada no estaba correcta. Los comentarios si cuentan en todo, ya sea en los 100 caracteres  y en para las 400 líneas.

De todas formas, para la T1 vamos a tener en consideración que aquí se dijo que los comentarios no cuentan para los 100 caracteres por línea. Por lo tanto, no se descontará por eso y en que se nos pase algún descuento relacionado al PEP8 por los comentarios, en la recorrección se quitará dicho descuento. 

Desde la T2 si aplicaremos desde un inicio que los comentarios cuentan para todo, los 100 caracteres y las 400 líneas, para que en esta segunda evaluación, tengan precaución en no fallar en PPE8 o modularización.

Saludosヾ(＾-＾)ノ
