### ISSUE TITLE
Ingresar un float en consola

### ISSUE THREAD

**Issue by felipecr00** [IIC2233/Syllabus#164]
Tengo problemas para ingresar un float por consola
Ingreso algo del estilo r=12.2, pero cuando le coloco type(r) para saber que es, me dice que es un string.
Cuando recibo el parametro desde la consola tengo una funcion que verifica que es, si no corresponde a un float entonces te vuelve a pedir la info, por eso no puedo hacer algo del estilo float(r)

Aiuda :(
saludos!!

**Comment by sebacruzd** [comment]
Hola, esto es porque cualquier cosa que ingreses mediante el comando input() va a ser un string.

Si luego de verificar que es un número con isdigit() o isnumeric() por ejemplo, recién ahí podrías re-definirlo como float.
Por ejemplo:
```python
ingresado = input("Ingresa un número")  # alguien ingresa un número, "4".
print(type(ingresado))

if ingresado.isnumeric():
    ingresado = float(ingresado)  #  --> si era numero, ahora va a ser un float.

print(type(ingresado))  # --> va a darnos el tipo de objeto que es. si se ingresó un número será un float.

```
Espero que te sirva el ejemplo, pruébalo!

Saludos!

**Comment by felipecr00** [comment]
Estoy usando efectivamente eso, pero si el usuario ingresa algo del estilo 12.2
```
r = (input("> Ingrese numero: "))
#print(type(r))
if` isinstance(r,float):
         r = float(r)
else:
         print("estas mal")
Me arroja al else, y lo uso para comprobar efectivamente si el usuario puso un float o no :/

**Comment by stephichau** [comment]
como dijo @sebacruzd: ``` **cualquier cosa que ingreses mediante el comando input() va a ser un string** ```

**Comment by sebacruzd** [comment]
En el caso de ingresar un float, está la opción de usar un `replace` y luego `isnumeric`, pero te propongo encontrar la solución usando lo que recién mencioné, para que pienses la solución :wink: 
Se puede hacer, créeme.

**Comment by felipecr00** [comment]
solucionado! muchas gracias ;)
