### ISSUE TITLE
Duda Sobre Issue #140

### ISSUE THREAD

**Issue by franco-anfossi** [IIC2233/Syllabus#164]
Hola! Recuerda que después de cada simulación de una ronda debes mostrar un resumen de esta, por lo que las batallas de esa ronda se deben simular y mostrar en el resumen. En el caso que queden más rondas no es necesario realizar esas batallas (si quieres puedes hacerlo aunque no es necesario) pero en el enunciado (Flujo del programa) dice que si pierde tu entrenador se le debe notificar, y dar la opción de comenzar de nuevo en el menú de inicio o salir del programa.

_Originally posted by @martinjaraf in https://github.com/IIC2233/Syllabus/issues/140#issuecomment-1238845963_

Hola tengo una duda respecto a lo que dice aquí arriba (que se respondió en una issue), ya que en el enunciado no dice que se deba dar la opción de comenzar de nuevo en el menú de inicio o salir del programa, sino que se debe reiniciar el programa y volver al menú de inicio. Supongo que si el enunciado lo dice debemos hacerlo así no? Lo pregunto para asegurarme de que no estará malo :)

**Comment by MrNachoX** [comment]
Hola @franco-anfossi ! Ambas opciones son válidas. Lo importante es que después de perder se reinicie el campeonato y puedas volver al menú de inicio. 
Si tienes más dudas con si algo será considerado malo o no recuerda que puedes ver la pauta de la tarea en AvanzadaApp. Utilizaremos eso para corregir.

**Comment by Juampisaez** [comment]
Holaa @franco-anfossi 
Revisa nuevamente la respuesta, se editó la respuesta para no dejar ambiguedades.

Quedo atento si surgen mas dudas :)
