### ISSUE TITLE
Llamar al método crear_predios desde el Menú de Inicio

### ISSUE THREAD

**Issue by elisaorchard** [IIC2233/Syllabus#164]
* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola. Ya leí varias issues relacionadas a esto, pero aún así no entiendo.

Al definir el método crear_predios de la clase DCCultivo, se nos pide, en el caso de que el archivo no exista, retornar un mensaje que falló la carga del archivo. Sin embargo, al marcar la opción 1 en el Menú de Inicio, somos nosotros quienes llamamos al método crear_predios, por lo que no entiendo por qué se ingresaría el nombre de un archivo que no existe. 

También tengo entendido que es una mala práctica ingresar valores directamente en el código fuente del programa, como lo sería el nombre del archivo "data/predios.txt", pero tampoco tiene sentido pedirle al usuario que lo ingrese como input?

Gracias.

**Comment by FernandoTFH** [comment]
Lo primero, si en el menú, uno usa directamente "data/predios.txt", eso lo se comentó en la issue #51. El método crear_predios el retorno es principalmente para los test. 
Lo segundo, si es mala práctica dejar datos en duro en un código, en general uno crea un archivo.py en donde se escriben constantes y luego uno las importa. Pero para esta tarea no se le exige hacer esto, en general se dice directamente en los enunciados de las tareas si es una exigencia o no. Si quieres lo puedes hacer, pero no es necesario y no habrá descuento por ello.
