### ISSUE TITLE
duda ejecutar codigo en sublime

### ISSUE THREAD

**Issue by LucianaMedel** [IIC2233/syllabus#164]
hola! tengo un computador mac muy viejo por lo que siosi tengo que usar sublime, el tema esque cuando meto inputs el codigo deja de correr (probe hasta con ejemplos muy faciles) mi teoria es que no conozco el comando pa seguirlo corriendo y no lo encuentro en internet ayuda xfis

**Comment by aaossa** [comment]
Hola @LucianaMedel ! El código que ejecutas se detiene porque queda esperando a que se ingrese un *input*, y el problema con Sublime Text es que no hay una forma (nativa) de entregar este *input*. Aquí tienes dos opciones (que también se mencionan en #55 ):

1. **Instalar SublimeREPL**, un paquete para ST3 que te genera una nueva pestaña donde sí puedes ingresar *inputs* (puedes ver ejemplos de cómo se ve en [esta página](https://packagecontrol.io/packages/SublimeREPL)) 📦 
2. **Ejecutar el código desde la consola** cuando tengas que correr código que requiera *input*. Esto es, ir a la carpeta donde se encuentra tu archivo *.py (digamos, ejemplo.py) y usar el comando `python ejemplo.py` (o `python3 ejemplo.py`) para correrlo 🏃 

Yo también ocupo Sublime Text 3 y lo que hago es la segunda opción, pero lo importante es que pruebes ambas y elijas la que más te acomode ✨ Ojalá te sirva, y si tienes alguna otra duda pregunta acá mismo no más 👌

**Comment by LucianaMedel** [comment]
trato de hacer la segunda opcion y me tira error (con python y python 3)(python: can't open file 'codigo.py': [Errno 2] No such file or directory) ni tampoco abre ningun archivo de ese nivel, y la primera opcion hice todos los pasos pero sigue sin correr nada :(

**Comment by aaossa** [comment]
@LucianaMedel sobre SublimeREPL, ¿lo instalaste con Package Control? ¿Cuáles pasos seguiste? [Aquí](https://sublimerepl.readthedocs.io/en/latest/) encontré algunas instrucciones adicionales por si no las has visto. 

En cuanto a ejecutar el código, al parecer no estás en la misma carpeta o tu archivo no se llama `codigo.py`. Te recomendaría utilizar el comando `ls` antes de ejecutar `python codigo.py` para asegurarte de que estás en la carpeta correcta (si no es así, recuerda que puedes usar `cd` para moverte entre directorios)
