### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by jfpena1** [IIC2233/syllabus#164]
Hola, en que parte del syllabus puedo encontrar la recomendacion para el formato a seguir en el readme?

muchas gracias.

**Comment by KnowYourselves** [comment]
Hola @jfpena1!

En tu repo personal, en cada carpeta de las tareas hay un archivo llamado **Readme.md** que contiene una guía de como debería ser tu Readme. En caso de que hayas borrado el que estaba en la carpeta de la Tarea 1, puedes encontrarlo en la carpeta de la Tarea 2 o 3 de tu repo.

Espero haberte ayudado!

**Comment by jfpena1** [comment]
Muchas gracias!!, efectivamente habia borrado el de la T1.
