### ISSUE TITLE
Duda sobre base de datos y archivo "connections_generator.py"

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2233/Syllabus#164]
En los archivos population.csv y borders.csv países de dos palabras tienen nombre, como por ejemplo Costa Rica, tienen una mayúscula en cada palabra, pero en el archivo airports.csv esos mismos países solo tienen una mayúscula, como por ejemplo South korea en vez de South Korea. ¿A qué tipo de formato debemos dejar el nombre de los países?

Otra duda, ¿podemos ocupar el archivo "connections_generator.py", o debemos imitar uno nosotros ocupando estructuras de datos hechas por nosotros?

**Comment by stephichau** [comment]
@frvalenzuela da lo mismo el formato :). Sobre el archivo connections_generator.py, debes importarlo y ejecutar la función generate_connections para crear el archivo que entrega las conexiones de las rutas de los paises con aeropuertos.

Saludos!

**Comment by frvalenzuela** [comment]
Entendido, muchas gracias !
