### ISSUE TITLE
Error en VSCode ejercicios propuestos 2.2 - 2.3 semana 2: Direct kernel connection broken y jupyter notebook

### ISSUE THREAD

**Issue by jervaal** [IIC2233/syllabus#164]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! mi duda surge al momento de realizar los ejercicios propuestos 2.2 y 2.3. Al momento de definir las clases y lo correspondiente a estas (sus metodos, properties, etc) no tengo ningun problema, pero al momento de correr el codigo en vscode (utilizo una extension para leer archivos jupyter) me aparece el error "Direct kernel connection broken". Crei que se debia a que encapsule mal un atributo de la clase, pero revise si era eso y encapsule bien los atributos de clases, pero aun asi me sigue apareciendo ese error (y no me deja correr el codigo).

Ademas, intente abrir el archivo contenidos desde el cmd y me aparece que ### "jupyter" no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable.###

¿que podria hacer para solucionar esto u.u?

**Comment by aaossa** [comment]
Hola @jervaal , esta pregunta parece ser lago más de *setup* que de contenidos, porque se relaciona con como estas ejecutando los Jupyter. En particular en el curso recomendamos usar el comando `jupyter notebook` directamente en la consola, pero entiendo que lo estás haciendo por medio de tu editor. ¿Te funciona bien el ejecutar los contenidos utilizando el comando fuera de tu editor? 🤔 Dudo que podamos ayudarte con la configuración de tu editor para ejecutar Jupyter porque no es lo que usamos en el curso 😅

**Comment by jervaal** [comment]
no, no me funciona el comando desde fuera del editor. Intento abrirlo desde el cmd y no me reconoce el comando u.u

**Comment by aaossa** [comment]
Al parecer es un *bug* en la extensión que (asumo) estás usando: https://github.com/microsoft/vscode-jupyter/issues/1706. Por lo que entiendo, el parche debería salir pronto, pero quizás sea mejor que intentes usar jupyter directamente en la consola (al menos mientras se soluciona).

Sobre que no te reconozca el comando, es posible que (1) no tengas instalado jupyter o (2) Python no esté en tu PATH. Para lo primero tienes que usar `pip install jupyter` o alguna de sus variantes, como aparece en la [Wiki de Software Obligatorio](https://iic2233.github.io/wiki/software). Para lo segundo, debería depender de tu sistema operativo, y en primer lugar el comando `python` debería funcionarte (puedes verificar con `python --version`, o `python3 --version` si es que lo anterior te dice que es una versión de Python2). Desde ambos puntos, las instrucciones de la Wiki deberían poder ayudarte, pero si algo no te funciona puedes preguntar por acá mismo 👌
