### ISSUE TITLE
Añadir atributo static a Tablero

### ISSUE THREAD

**Issue by endlessloop2** [IIC2233/Syllabus#165]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Quería consultar si, considerando que el enunciado dice que no se debe modificar la clase Tablero (al menos en el sentido de su constructor), si esta permitido añadir un atributo estático a Tablero, el cual luego uso dentro de metodos de la clase.

Me refiero por ejemplo a atributos a los que accedo de forma `Tablero.atributo`.

Gracias.

**Comment by mtaguero** [comment]
¡Hola @endlessloop2!

Tal como dice el enunciado, no se debe modificar la clase Tablero en ningún aspecto. Esto se debe a que si ustedes cambiaran la estructura de las clases entregadas por el equipo docente, lo más probable es que comenzaran a fallar los testcases. En este sentido, te recomiendo planificar bien cómo vas a utilizar el código entregado.

Avísame si quedó claro y/o si tienes alguna otra duda.

¡Éxito! 🎈

**Comment by endlessloop2** [comment]
Hola, gracias por la respuesta, me queda claro y probablemente use un módulo en lugar de cambiar la clase Tablero.

Saludos.
