### ISSUE TITLE
Corrección Actividades

### ISSUE THREAD

**Issue by negutierrez** [IIC2233/Syllabus#165]
Tengo una duda, las correcciones de las actividades llegan a los issues de los dos integrantes?, o sólo al cuya carpeta se corrigió?
Pregunto porque mis issues están vacíos y me gustaría revisar el feedback.

**Comment by fvr1** [comment]
Hola en teoría deberían haber estado subidas anoche. Puede ser que hubo un problema con el sistema. Vamos a tratar de arreglarlo lo antes posible !
Perdón por la demora

**Comment by akaminetzkyp** [comment]
Ya están arriba. :)

**Comment by bamavrakis** [comment]
Tus 2 issues están vacíos?

**Comment by negutierrez** [comment]
ok, muchas gracias!
