### ISSUE TITLE
S02 ejercicio 1.1: tupla vacía en argumentos Sala

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#165]
Hola! Estoy solucionando el ejercicio propuesto 1.1 para la semana 02, y me encontré con algo raro en el código base. En la línea que instancia `Sala`, para el parámetro `lista_alumnos`, se entrega como argumento una lista de tuplas con `nombre, numero_alumno` para cada alumno inscrito inscrito en el curso. Pensaba recorrer esa lista de manera simple con un `for` desempaquetando los valores de las tuplas, pero me encontré que el último elemento de la lista una tupla con dos strings vacíos: `("", "")`. Esto me hace pensar que el ejercicio está diseñado para recorramos la lista de tuplas con un `while nombre != "" and numero_alumno != "":`. Mi pregunta sería: **¿borro simplemente la tupla vacía del código base si me resulta más cómodo, o la idea es que practique resolverlo con esa incomodidad?**
Gracias de antemano!

**Comment by Juampisaez** [comment]
Hola @sbcorrea 
No es necesario que borres esa tupla ya que lo que te piden es verificar al final si (nombre, numero alumno) se encuentra en la *lista_alumnos*. Si lo anterior se cumple debes agregar la sigla a los cursos asistidos por el alumno, en caso contrario el alumno se estará colando.
Si te acomoda puedes eliminar la tupla ("", "") ya que no representaría a ningún alumno, pero eso **no debería afectar al resultado.**
Espero consteste a tu pregunta, cualquier cosa quedo atento.

**Comment by sbcorrea** [comment]
Clarísimo! Muchas gracias
