### ISSUE TITLE
Readme, comentarios código

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#165]
Hola, se que el Readme dice que no hay que explicar nada del código y hacerlo en el archivo mismo, sin embargo en vista al tiempo no comenté nada. Hay alguna repercusión si omito esto y aun así comento los métodos en el Readme mismo, de esta forma puedo facilitar la corrección del ayudante.

**Comment by Arcoirisky** [comment]
Comenta las funciones que sean complicadas de entender O: si tienes una función suma(x,y) que realiza la suma entre x e y, entonces no tienes por qué comentarla en el README.md ouo)/ 

Si crees o sientes que alguna parte de tu código no se entendería, al README.md de una 😱

Sobretodo casos que podrían generar errores de cualquier tipo.
