### ISSUE TITLE
PILOTOS.CSV URGENTE

### ISSUE THREAD

**Issue by bfigueroa1** [IIC2233/syllabus#165]
SE PUEDE HACER GIT PULL OTRA VEZ PARA RECUPERAR UN ARCHIVO QUE SE EDITO MAL?

**Comment by jeschuwirth** [comment]
Hola @bfigueroa1,

Si quieres recuperar el archivo que les entregamos la mejor forma de hacerlo es borrar el archivo editado de tu computador y hacer git pull :)

Suerte!

**Comment by bfigueroa1** [comment]
no me funciono git pull
tuve que hice git stash primero y después git pull
pero ya esta 
gracias
