### ISSUE TITLE
Duda sobre cambiar una línea de mi tarea

### ISSUE THREAD

**Issue by matiasparodic** [IIC2233/syllabus#165]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola! No tengo muy claro cuál es el procedimiento que se tiene que hacer si es que se quiere cambiar una línea del código de la tarea. Me podrían explicar por favor?

**Comment by aljara97** [comment]
Hola, en caso de que quieres cambiar líneas de tu tarea debes indicarlo en tu Readme de la manera más clara posible, indicando el archivo, línea, contenido actual y contenido por el que lo quieres reemplazar. Por ejemplo: "Me gustaría que se cambie la línea 85 del archivo `main.py`, actualmente dice `prnt("DCConectados")`, pero debería ser  `print("DCConectados")` para un correcto funcionamiento del programa.

Considera también que hay un descuento asociado, el que puedes consultar en la distribución de puntaje. 

Saludos y mucho éxito

**Comment by matiasparodic** [comment]
Perfecto! Gracias
