### ISSUE TITLE
UnicodeDecodeError? No se que significa

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2233/syllabus#165]
quiero correr un archivo con una sola funcion, me funciono perfecto en todo momento, y he abierto los archivos siempre de la misma forma, y sin cambiar nada cuando lo quise correr denuevo me tiraba este error?

Traceback (most recent call last):
  File "/Users/Maggie/Desktop/syllabus/Tareas/T00/pposts.py", line 49, in <module>
    print(ver_perfil("hola"))
  File "/Users/Maggie/Desktop/syllabus/Tareas/T00/pposts.py", line 37, in ver_perfil
    linea = posts.readline()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 1259: invalid start byte

dice linea 322 y ninguno de mis archivos tiene mas de 150 lineas...

**Comment by jeschuwirth** [comment]
Hola @maggiemunoz,

Puede que tu error sea el comentado en la issue #160 

Revisa todos tus open() y asegúrate que tantos lo que abren en modo "r" como en modo "w" tengan `encoding="utf-8"`

Me avisas :)

**Comment by maggiemunoz** [comment]
como deberia escribirlo? open.("posts.csv", "r",encoding="utf-8") ?

**Comment by jeschuwirth** [comment]
Si, pero también cuando escribas en ellos debe ser `open("posts.csv", "w", encoding="utf-8")`

**Comment by maggiemunoz** [comment]
lo escribí de esa forma y me tira el mismo error, y todos los otros archivos los abro sin el encoding y me funcionan perfectamente con todos los modos :(

**Comment by jeschuwirth** [comment]
Intenta reiniciando todos los archivos .csv (volver a descargarlos y reemplazar los antiguos). Luego agrega el `encoding = "utf-8"` a todos tus open

Con eso debería funcionar

**Comment by maggiemunoz** [comment]
me tira el mismo error, y ese es mi unico open en este archivo

**Comment by maggiemunoz** [comment]
Vi que en issues anteriores hablaban de como el error pasa por como windows lee los archivos, yo tengo mac, no se si influye en algo

**Comment by jeschuwirth** [comment]
Que leas los archivos en mac no debería influir. 

Como ya estamos en horario del domingo de descanso no debería seguir contestando la issue, pero con la información de otras issues y reiniciando tus .csv debería funcionar.

Revisa el compilado #7 por si aún no logras solucionarlo, quizás encuentres algo que te ayude ahí.

**Comment by maggiemunoz** [comment]
como puedo reiniciarlos? los borro y le hago git pull denuevo nomas?
