### ISSUE TITLE
puedo asumir que se ingresan los datos correctamente?

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#165]
Perdon por la pregunta rebuscada, pero puedo asumir que cuando yo le pido al usuario que ingrese un dato, este lo ingresa de forma correcta? Por ejemplo, si un usuario quiere registrarse, al pedirle su fecha de nacimiento quiero que me la entregue en formato dd-mm-yyyy, puedo asumir que lo hara bien? O mi programa tiene que revisar que todos los inputs correspondan a lo que pido?

**Comment by ayudantesIIC2233** [comment]
Hola, tiene que revisar todo. Tu programa debe ser a prueba de inputs (: Suerte :D

**Comment by martin412** [comment]
😥😥😥😥

**Comment by Arcoirisky** [comment]
Ánimo que sólo son un poco más de código :D

**Comment by Kitaps** [comment]
Pero con que sea a prueba de inputs, se refieren a que no se caiga o que pueda leer a lo q se refiere el usuario y responderle correctamente?

**Comment by iqacevedo** [comment]
Hola,

Ambos, su programa no se debería caer y también debería leer lo que ingrese el usuario (si ustedes dicen que si escribe 1 se abrirán sus orders, deben abrirse cuando escriba 1).

Saludos !

**Comment by Kitaps** [comment]
sisi, pero si le digo q escriba la fecha a consultar como yyyy-mm-dd
y escribe 7 de febrero de 1991
entonces chao nomas no?

**Comment by Arcoirisky** [comment]
En teoría, debería pedirlo de nuevo xD si tu específicas una forma, que el
usuario lo haga hasta que te la de xD piensa en ellos como monos que
intentan hacer funcionar tu programa (ejemplo drástico pero funciona)
