### ISSUE TITLE
TypeError en clases abstractas 

### ISSUE THREAD

**Issue by rosario-frugone** [IIC2233/Syllabus#165]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

hola!! llevo harto rato pegada con un TypeError cuando intento implementar clases abstractas en la tarea, por lo mismo, intenté correr un código de los contenidos del curso y me aparece el mismo error. No sé si será un problema de mi computador o que hay algo que sigo haciendo mal. Espero que me puedan ayudar! 
Dejo el código que copié y pegué de los contenidos:

`from abc import ABC, abstractmethod`

`class Base(ABC):`

    @property
    @abstractmethod
    def valor(self):
        return '¿Llegaremos aquí?'

`class Implementacion(Base):`

    @property
    def valor(self):
        return 'Propiedad concreta'

`b = Base()
print(f'Base.value: {b.valor}')`

`i = Implementacion()
print(f'implementacion.valor: {i.valor}')`

output:

`Traceback (most recent call last):
  File "/Users/rosariofrugone/Desktop/progra 2021/rosario-frugone-iic2233-2021-2/Tareas/T1/hola.py", line 44, in <module>
    b = Base()
TypeError: Can't instantiate abstract class Base with abstract methods valor`

**Comment by tqmbanados** [comment]
Hola! El problema es que estás tratando de instanciar un objeto de clase `Base()`, siendo que esta es abstracta y con métodos abstractos. Recuerda que las clases abstractas están hechas para **no ser instanciadas**. Si cambias la línea 44 a `b = Implementacion()` debería funcionarte.
