### ISSUE TITLE
Donde encuentro lo que se puede revisar mediante lectura de codigo?

### ISSUE THREAD

**Issue by Icarus328** [IIC2233/syllabus#166]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, vi en la guia de descuentos 

* Especificar el archivo y línea donde se puede encontrar cada ítem de la distribución del puntaje que puede ser evaluado mediante la lectura de código.

Pero no estoy muy seguro donde puedo encontrar las partes que pueden ser evaluadas mediante lectura de código, o que significa eso exactamente, solo corre para las partes en las que mi codigo no funciona como debería? entonces si mi codigo es, en teoría, 100% funcional, ignoro ese punto?

Gracias!

**Comment by aljara97** [comment]
Hola @Icarus328, los items que se revisarán a nivel de código son los que se encuentran pintados de amarillo en la distribución de puntaje.

Esto se refiere a que el ayudante que revise tu tarea, para evaluar estos items tendrá que ver los módulos que implementaste y verificar que esta funcionalidad esté implementada de manera adecuada.
