### ISSUE TITLE
Escribir sobre un archivo

### ISSUE THREAD

**Issue by fbarrosalcalde** [IIC2233/syllabus#166]
Hola! Como puedo escribir en un archivo exel? Traté pero no aparece nada.

**Comment by jeschuwirth** [comment]
Hola @fbarrosalcalde,

la finalización 'excel' de un archivo es sólo para que los humanos sepan que es y para que los computadores sepan como mostrártelo, sin embargo funciona igual que un bloc de  notas.

la finalización .csv viene del inglés _coma separated value_, por lo tanto no es más que un bloc de notas con los valores de las celdas separados por punto y coma.

Te entrego aquí unos pantallazos con ejemplos:

Si guardas el siguiente .csv:
![image](https://user-images.githubusercontent.com/37160256/64360296-31fc1380-cfd8-11e9-93c1-569986be5172.png)

y lo abres en un editor de texto se ve así:

![image](https://user-images.githubusercontent.com/37160256/64360320-3f190280-cfd8-11e9-8d19-1d2466dd7723.png)


Y en python su lectura se vería así:

![image](https://user-images.githubusercontent.com/37160256/64360374-5a840d80-cfd8-11e9-8680-b068594ef924.png)


Ojalá las imágenes te ayuden con el programa :)

Suerte!

**Comment by fbarrosalcalde** [comment]
Ya gracias!
