### ISSUE TITLE
Cómo borrar un archivo .py de mi repositorio online?

### ISSUE THREAD

**Issue by dlmed** [IIC2233/Syllabus#166]
Necesito borrar un archivo que subí hace tiempo a mi carpeta de T01, pero que ya no es parte necesaria de mi tarea. Esto en mi repositorio online.

**Comment by ptflores1** [comment]
Hola ! 
Revisa [esto](https://stackoverflow.com/questions/2047465/how-can-i-delete-a-file-from-git-repo), espero que te sirva
Saludos !
