### ISSUE TITLE
Error al recorrer users.csv

### ISSUE THREAD

**Issue by Mariana-Ortega-del-Rio** [IIC2233/Syllabus#166]
Hola! Tengo un procedimiento que me abre y trabaja con los archivos "Currencies.csv" y "orders.csv" perfectamente, pero al  momento de tratar de ocuparlo para el archivo "users.csv" me tira error y no entiendo por qué si el archivo tiene la misma estructura que los otros dos. 
Me di cuenta que ni siquiera me funciona este código para el archivo "users.csv":
a = open("users.csv")
for line in a:
     print(line)
Y ese mismo código funciona correctamente para los archivos "Currencies.csv" y "orders.csv".
Es distinto en algo el archivo users.csv?
Adjunto una foto del error que me tira.
![error python](https://user-images.githubusercontent.com/30672931/29739401-4a12e0aa-8a13-11e7-9bf8-da4a3593d1b3.PNG)

**Comment by vijuarez** [comment]
Hola!

Eso se respondio en #116, ojalá esa respuesta te sirva a ti también.

Saludos!

**Comment by Mariana-Ortega-del-Rio** [comment]
siiiiii!!!Muchas gracias :) :) :) :) :) :)
