### ISSUE TITLE
Jupyter rechaza list.join()

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#166]
Hola! Estaba tratando de usar el método join en Jupyter...
![image](https://user-images.githubusercontent.com/61999464/91190340-79841f80-e6c1-11ea-92d5-236c5739f664.png)

pero no me lo reconoce:
![image](https://user-images.githubusercontent.com/61999464/91190587-bd772480-e6c1-11ea-9877-cef22f163e58.png)

¿Es por alguna diferencia en versión de Python? ¿O algo particular a Jupyter?
En cualquier caso, sé que almacenar esos datos como lista solo para concatenarlos como string es poco eficiente. Por lo tanto, me surge la duda: ¿cuál sería la sintaxis para crear 'strings por comprensión'?
Gracias de antemano!

**Comment by furcelay** [comment]
Hola!
El problema es que `join()` no es un método de listas, es un método de strings, donde el string es el separador de los ítems del iterable (lista), se usa de la siguiente manera:
```python
'\n'.join(["a", "b", "c"])
```
En el ejemplo anterior el resultado sería `a\nb\nc`.

Saludos!

**Comment by sbcorrea** [comment]
AAAAH ya! Jajajaj muchas graciasss
