### ISSUE TITLE
Duda con abrir ventana

### ISSUE THREAD

**Issue by IgnacioHqz** [IIC2233/Syllabus#166]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, estoy intentando abrir la ventana del menú para elegir uno de los 3 niveles, a la hora de hacer un click dentro del botón "jugar" de la ventana de inicio. Pretendo hacer dos archivos, cada uno para hacer el frontend de cada ventana, (cada una la hice con QtDesigner por lo que tuve que cargarlos en los .py). Sin embargo no he podido conseguir que la señal que envío desde el .py de la ventana de inicio le llegue al .py de la ventana del menú y no he encontrado nada en internet que me pueda servir siguiendo mi idea de usar dos archivos. Entonces no sé realmente qué es lo que estoy haciendo mal, ya que el archivo que debe recibir la señal emitida heredo el archivo .py que contiene la ventana de inicio, pero llevo casi todo el día buscando entre la materia y no encuentro mi error. Gracias

**Comment by Emiliax16** [comment]
Hola @IgnacioHqz . No entiendo bien lo que quieres hacer, pero todo el envío de señales debes hacerla desde `main.py`. En este módulo, instancias todas las clases (tanto de frontend como backend) y te encargas de todas las señales que las relacionan entre ellas, de tal manera que no tienes que hacer que desde `ventanaX.py` se mande una señal a `ventanaY.py`, sino que la señal llega a main y de aquí la envias a la otra ventana. De todas maneras, puedes pushear tu tarea y así puedo revisar bien qué es lo que estás tratanto de hacer. Saludos!
