### ISSUE TITLE
Subir Readme 

### ISSUE THREAD

**Issue by constanzacontreras** [IIC2233/syllabus#166]
Hola! Intente agregar el archivo Readme.md por el terminal con git add Readme.md, git commit-m y git push pero no se por que no me funcionaba, por lo que lo subí directamente desde github.. ¿Está bien?, y ahora al revisar la carpeta de t01 en github me sale actualizado pero dice que lo subí hace 22 horas.

**Comment by Arcoirisky** [comment]
¿Podrías comentar el error que aparecía? O:

**Comment by constanzacontreras** [comment]
![WhatsApp Image 2019-04-08 at 18 37 09](https://user-images.githubusercontent.com/48296666/55761496-738a9180-5a2d-11e9-98be-94e05a630b4c.jpeg)

**Comment by Arcoirisky** [comment]
Por casualidad hiciste git pull antes de intentar subir el archivo?

**Comment by constanzacontreras** [comment]
no, no hice git pull, tenia que hacerlo?? :(

**Comment by Arcoirisky** [comment]
Siempre es bueno hacer git pull antes de subir un archivo. En este caso lo subiste desde la página, así que intentar hacer un cambio desde git, el mismo git te detendrá diciendo “¡Hey! Detente!!! Que tu carpeta local (la del pc) no es igual a la que tiene github >:0” sin contar los cambios que intentas subir O: 

Pero si le haces git pull te sincroniza todo y te debería dejar hacer push uwu 

Intenta hacer pull ahora y luego un git status para ver que aparece O:!

**Comment by constanzacontreras** [comment]
![Captura de pantalla 2019-04-09 18 45 23](https://user-images.githubusercontent.com/48296666/55761803-8f426780-5a2e-11e9-9a1c-02321f0d5b08.png)

**Comment by constanzacontreras** [comment]
Me aparece eso, es muy raro,como de la actividad 1, y hice git pull en el repositorio mio

**Comment by tatanpoker09** [comment]
Quedó un merge sin terminar, si ya tienes todo subido solo borra MERGE_HEAD (dentro de tu .git (carpeta oculta)) e intenta hacer git pull denuevo. De esta manera git no tomará en cuenta el merge anterior

**Comment by constanzacontreras** [comment]
gracias!! pero como se elimina un merge??? desde mi repositorio y adentro la carpeta tarea??

**Comment by Arcoirisky** [comment]
La carpeta .git está oculta en tu repositorio local. Activa ver archivos ocultos y podrás acceder a ella :D

**Comment by constanzacontreras** [comment]
¿Pero esta mal si subi la tarea por github? porque al apretarla me sale la tarea correcta.

**Comment by tatanpoker09** [comment]
No debería, aunque es poco recomendable. pero te refieres al readme?

**Comment by constanzacontreras** [comment]
sii al readme

**Comment by tatanpoker09** [comment]
Si desde github lo ves bien, entonces está buen pues eso se evaluará. Sin embargo, es recomendable siempre que se suba por git para prevenir inconsistencias de versiones. (Y que tengas problemas donde tengas que hacer merge, como ahora).

**Comment by Arcoirisky** [comment]
Osea, no esta mal en el sentido de que seguirá siendo la misma tarea y habrá sido subida. Pero, la idea de todo esto es que hagan todas las entregas por git. 

Además te ahorras estos problemas :( Por eso se han hecho talleres, documentación, de todo para que aprendan a usar correctamente git. Ya que es con esta herramienta con la que trabajarán de aquí en adelante en ramos del DCC e incluso fuera de la universidad O: 

Mejor aprender a hacerlo ahora que después :(

**Comment by constanzacontreras** [comment]
Ya muchas gracias!!

**Comment by constanzacontreras** [comment]
![Captura de pantalla 2019-04-09 19 27 29](https://user-images.githubusercontent.com/48296666/55763334-7a68d280-5a34-11e9-9cbb-d5a0272a8fd1.png)
entregue la tarea ayer, y me sale del 8 de abril pero hace 23 horas. esta bien?? Que me hace dudar que salga 8 de abril
Muchas graciasss!!

**Comment by tatanpoker09** [comment]
Acabo de entrar a tu repositorio, puedo confirmar que aparte del titulo del nombre de la tarea, el readme se ve editado por ti.

**Comment by constanzacontreras** [comment]
Yaa muchas gracias
