### ISSUE TITLE
[Linux Mint 21.1 Cinnamon] Problema al tratar de ejecutar codigo interfaces gráficas

### ISSUE THREAD

**Issue by jrodriguezluna** [IIC2233/Syllabus#166]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Me salió el infame "This application failed to start because no Qt platform plugin could be initialized" al tratar de ejecutar código de interfaces gráficas (ejemplo abajo). Hice la prueba de importar el modulo dentro de un archivo para ver si está instalado (que sale en la wiki) y no me causa problemas. Tengo entendido que otros ya tuvieron este problema en wsl pero en mi caso estoy con Linux así que no me explico qué pasa ;;;. Traté re-ejecutando el código para instalar PyQt6 y el terminal solo me informa que ya está instalado. También intenté utilizar "sudo apt-get install  libxkbcommon-x11-0 libpulse0" (como le habían recomendado a alguien con wsl) pero tampoco hizo nada. 

![Screenshot from 2023-09-04 17-04-02](https://github.com/IIC2233/Syllabus/assets/141784036/2babad2a-1848-41d9-8a4c-3a6b298259ce)

**Comment by Hernan4444** [comment]
Hola @jrodriguezluna 

Puedes intentar con este estos dos comando

> `sudo apt install libqt6multimedia6`
> `sudo apt install python3-pyqt5`

Al parecer, la raíz de otro no era WSL con pyqt6, sino linux con pyqt6 😭 

Quedamos atentos a tus comentarios!
Saludosヾ(＾-＾)ノ

**Comment by jrodriguezluna** [comment]
Saludos!
Probé los dos comandos porque el primero no me funcionó (aunque realizó la instalación perfectamente). Al instalar el segundo y probar me fijé en el error que sale y es distinto (ahora dice que si lo encontró pero que no lo pudo cargar).

![image](https://github.com/IIC2233/Syllabus/assets/141784036/9d8483d1-88f0-461b-a9ca-a1a290325cdf)

**Comment by Hernan4444** [comment]
Hola @jrodriguezluna 

Por el momento, si haces `python3 -m pip install pyqt5` y luego vas a la carpeta `PyQt5` de los contenidos. ¿Te corre algún script? En caso que no ¿qué error te sale?

Quedamos atentos!

**Comment by Hernan4444** [comment]
Complementando a lo anterior,

Puedes probar con el siguiente comando

> `sudo apt install libxcb-xinerama0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-randr0`

Estaba leyendo en un foro que al parecer qt dejó de instalar ciertas cosas de `xcb` necesarias para su correcta ejecución.

Quedamos atentos a lo anterior y a este nuevo comando.
Saludos!

**Comment by jrodriguezluna** [comment]
Después de probar utilizando el comando python3 -m pip install pyqt5 me aparece lo siguiente:
![image](https://github.com/IIC2233/Syllabus/assets/141784036/20ff9248-5ee5-42f8-ab42-fb420adf1e01)
esto es parecido a lo que me apareció cuando traté de reutilizar el comando de pyqt6 anteriormente.
Después de entrar a la carpeta pyqt5 y probar noté que puedo correr todo el código de la carpeta sin problemas 🤔 
Finalmente, después de usar el segundo comando que sugirió sudo apt install libxcb-xinerama... me aparece lo siguiente:
![image](https://github.com/IIC2233/Syllabus/assets/141784036/bd534405-95d8-40b0-9575-db63eeae6d79)

**Comment by jrodriguezluna** [comment]
Busqué el comando para corroborar las versiónes de pyqt5 y pyqt6 y aparece lo siguiente:
![image](https://github.com/IIC2233/Syllabus/assets/141784036/43628363-fab9-4a5b-816f-479ed6cb9562)
no sé si es de utilidad, espero su respuesta (muchas gracias 😭)

**Comment by Hernan4444** [comment]
Ya. por el momento utiliza PyQt5. Los contenidos son 99% igual para lo que necesitamos del curso. Así que no tendrás problema para aprender y aplicar los contenidos cómo el uso de Layout, Botones, Widgets, señales. Incluso, podrás notar que muchos de los códigos de pyqt5 son lo mismo que pyqt6, pero se cambió `from PyQt6 ....` por `from PyQt5`.

Estamos investigando cuál puede ser el problema que pyqt6 no está funcionando en tu Linux,

Saludos!

**Comment by Hernan4444** [comment]
Por el momento, porfa pon

`export QT_DEBUG_PLUGINS=1`

y luego ejecuta un archivo de pyqt6. Luego mandanos toooodo el log que te salga (solo copialo aquí, que no sea foto). Eso nos dará una mayor panorámica de qué puede estar fallando y por donde seguir buscando el error.

E igual, por el momento sigue estudiando con los script de pyqt5, para que no te quedes atras. Las diferencias entre pyqt6 y 5 son mínimas. 

Estaremos atentos al log que nos mandes,
Saludos!

**Comment by jrodriguezluna** [comment]
Después de aplicar export QT_DEBUG_PLUGINS=1 y ejecutar python3 2-elementos-graficos-basicos-ejemplo_6.py el log es:

qt.core.plugin.factoryloader: checking directory path "/home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms" ...
qt.core.plugin.factoryloader: looking at "/home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqminimal.so"
qt.core.plugin.loader: Found metadata in lib /home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "archlevel": 1,
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("minimal")
qt.core.plugin.factoryloader: looking at "/home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so"
qt.core.plugin.loader: Found metadata in lib /home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archlevel": 1,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("xcb")
qt.core.plugin.factoryloader: looking at "/home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqvnc.so"
qt.core.plugin.loader: Found metadata in lib /home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqvnc.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vnc"
        ]
    },
    "archlevel": 1,
    "className": "QVncIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("vnc")
qt.core.plugin.factoryloader: looking at "/home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqvkkhrdisplay.so"
qt.core.plugin.loader: Found metadata in lib /home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqvkkhrdisplay.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vkkhrdisplay"
        ]
    },
    "archlevel": 1,
    "className": "QVkKhrDisplayIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("vkkhrdisplay")
qt.core.plugin.factoryloader: looking at "/home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqwayland-generic.so"
qt.core.plugin.loader: Found metadata in lib /home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqwayland-generic.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland"
        ]
    },
    "archlevel": 1,
    "className": "QWaylandIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("wayland")
qt.core.plugin.factoryloader: looking at "/home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqminimalegl.so"
qt.core.plugin.loader: Found metadata in lib /home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "archlevel": 1,
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("minimalegl")
qt.core.plugin.factoryloader: looking at "/home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqlinuxfb.so"
qt.core.plugin.loader: Found metadata in lib /home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "archlevel": 1,
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("linuxfb")
qt.core.plugin.factoryloader: looking at "/home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqoffscreen.so"
qt.core.plugin.loader: Found metadata in lib /home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "archlevel": 1,
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("offscreen")
qt.core.plugin.factoryloader: looking at "/home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqwayland-egl.so"
qt.core.plugin.loader: Found metadata in lib /home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqwayland-egl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland-egl"
        ]
    },
    "archlevel": 1,
    "className": "QWaylandEglPlatformIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("wayland-egl")
qt.core.plugin.factoryloader: looking at "/home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqeglfs.so"
qt.core.plugin.loader: Found metadata in lib /home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "archlevel": 1,
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("eglfs")
qt.core.plugin.factoryloader: checking directory path "/usr/bin/platforms" ...
qt.core.library: "/home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so" cannot load: Cannot load library /home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so: (libxcb-cursor.so.0: cannot open shared object file: No such file or directory)
qt.core.plugin.loader: QLibraryPrivate::loadPlugin failed on "/home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so" : "Cannot load library /home/jeff/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so: (libxcb-cursor.so.0: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, xcb, vnc, vkkhrdisplay, wayland, minimalegl, linuxfb, offscreen, wayland-egl, eglfs.

Aborted (core dumped)

**Comment by jrodriguezluna** [comment]
Estaré atento! gracias por su ayuda.

**Comment by Hernan4444** [comment]
Sigamos intentando jejeej

Puedes probar con 

`sudo apt install -y libxcb-cursor-dev`

y decirnos si se mantiene el error o fue otro.
Quedamos atentos!

ps: Lamento mucho hacerte probar tantos comandos 🙇‍♂️🥺

**Comment by Hernan4444** [comment]
Si ese no te funciona, probar con

`sudo apt install -y libxcb-cursor`

Quedamos atentos a estos 2 intentos!

**Comment by jrodriguezluna** [comment]
Funcionó!
sudo apt install -y libxcb-cursor-dev arregló el problema
Muchas graciass
