### ISSUE TITLE
Librerías permitidas, no permitidas y malas prácticas T2

### ISSUE THREAD

**Issue by gecoli** [IIC2233/Syllabus#166]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:
 
> Puedo usar la librería nombre_librería para hacer explicación_de_lo_que_quiero_hacer
 
¡Recuerden especificar en su README qué librerías utilizan!
 
---
 
## ✅ **Librerías Permitidas**
- ABC
- collections 
- random
- os (excepto os.system('cls'))
- typing
- copy
- string
- math
- sys.argv
- sys.exit
- _ _ future _ _

## ❌ **Librerías Prohibidas**
- sys
- csv
- pandas
- numpy
- JSON
- pickle
- threading
- re
- glob
- time
- py_cui

## **Malas prácticas**
El uso de las siguientes prácticas será considerado una mala práctica:
-  except Exception: o únicamente except: (excepciones bien capturadas sí estarán permitidas).
- Variables globales de cualquier tipo.
- Import * o _imports_ que no se encuentren al inicio del programa.
- Uso de _paths_ (absolutos o relativos) que no permita ejecutar la tarea correctamente en cualquier computador siguiendo las instrucciones del enunciado.

## ☠️ **_Built-ins_ Prohibidos**

El uso de alguna de las siguiente funciones es automáticamente un 1,0 sin discusión: 😭
- exec ([explicación](https://github.com/IIC2233/syllabus-2020-1/issues/591#issuecomment-616773839))
- eval ([explicación](https://github.com/IIC2233/syllabus-2020-1/issues/591#issuecomment-616773839))

 
¡Éxito en sus tareas! 🐈⚔️

**Comment by KaopyHK** [comment]
Si la libreria sys esta prohibida, como se debe manejar los argumentos que ejecutan el programa, es decir, las distintas dificultades?

**Comment by gecoli** [comment]
> Si la libreria sys esta prohibida, como se debe manejar los argumentos que ejecutan el programa, es decir, las distintas dificultades?

Buenas tardes, @KaopyHK !

Gracias por el alcance, está agregado ese método como permitido!

Que tengas una buena tarde ✨

**Comment by tomasvasquezp** [comment]
no logro entender como poder importar sys.exit y sys.argv, porque traté de hacer from sys import exit, argv pero luego no me deja usarlas. Cuál es el proceso correcto para importarlas?

**Comment by Drpinto1** [comment]
¡Hola @tomasvasquezp!

No estoy seguro de a qué se debe tu problema, ya que al realizar lo que comentas debería funcionar. Puede que haya algún error en la forma que estás importando o haciendo las llamadas, así que te recomiendo intentar usando `import sys` y luego `sys.exit` y `sys.argv` para ver se si resuelve el problema.

**Comment by tomasvasquezp** [comment]
Ahí pude al final, hice from sys import exit, argv y ahí me funcionó, mi duda estaba en que si sys está dentro de las librerías prohibidas, no sabía si debía importar el módulo completo o solo las 2 funciones

**Comment by KaopyHK** [comment]
Una consulta: puedo usar la libreria py_cui [https://jwlodek.github.io/py_cui-docs/](url) para hacer una interfaz interactiva y algo mas producida pa la tarea?

**Comment by gecoli** [comment]
> Una consulta: puedo usar la libreria py_cui (https://jwlodek.github.io/py_cui-docs/) para hacer una interfaz interactiva y algo mas producida pa la tarea?

¡Buenas tardes, @KaopyHK !

Dado que esa librería debe instalarse **no puedes ocuparla**, ya que no puedes asegurar que la persona que vaya a corregirte tenga la librería también instalada. 

¡Éxito en tu tarea! ꒰ᐢ. .ᐢ꒱₊˚⊹

**Comment by escontre** [comment]
Hola, si es que quisiera usar solamente time.sleep() para permitir tener un flujo de prints en el combate sin que salgan todos de una, se podría usar?

**Comment by gecoli** [comment]
> Hola, si es que quisiera usar solamente time.sleep() para permitir tener un flujo de prints en el combate sin que salgan todos de una, se podría usar? 

Buenas tardes, @escontre !

Como aparece al inicio, la librería time **por completo** está prohibida.

¡Éxito en tu tarea! ꒰ᐢ. .ᐢ꒱₊˚⊹

**Comment by Vicente1824** [comment]
¿Puedo importar ```annotations``` de ```__future__``` para poder hacer que uno de los métodos de combatiente tenga de retorno una clase Combatiente? De la forma:
```py
from __future__ import annotations

class Combatiente:
    def metodo(self) -> Combatiente:
        pass
```

**Comment by gecoli** [comment]
> ¿Puedo importar `annotations` de `__future__` para poder hacer que uno de los métodos de combatiente tenga de retorno una clase Combatiente? De la forma:
> 
> ```python
> from __future__ import annotations
> 
> class Combatiente:
>     def metodo(self) -> Combatiente:
>         pass
> ```

¡Buenas tardes, @Vicente1824 ! 

Lamento la tardía respuesta, pero sí, se puede ocupar la función `annotations` del módulo `__future__`.

¡Éxito en tu tarea! ꒰ᐢ. .ᐢ꒱₊˚⊹

**Comment by FiuProgra** [comment]
Hola @gecoli! Quería consultar si es que se puede usar la extensión `autopep8` (https://marketplace.visualstudio.com/items?itemName=ms-python.autopep8) en VSCode o herramientas similares (como la disponible en https://pypi.org/project/autopep8/) para asegurar que el código entregado cumpla con la guía de estilo PEP8. Muchas gracias!

**Comment by gecoli** [comment]
> Hola @gecoli! Quería consultar si es que se puede usar la extensión `autopep8` (https://marketplace.visualstudio.com/items?itemName=ms-python.autopep8) en VSCode o herramientas similares (como la disponible en https://pypi.org/project/autopep8/) para asegurar que el código entregado cumpla con la guía de estilo PEP8. Muchas gracias!

¡Hola, @FiuProgra !

Puedes ocupar **la extensión** pero bajo tu propio riesgo, puesto que ésta no siempre detecta todo. 

¡Éxito en tu tarea! ꒰ᐢ. .ᐢ꒱₊˚⊹

**Comment by FelipeFuentesG** [comment]
Hola!

¿Es mala práctica utilizar y modificar el atributo "__class__" de un objeto cualquiera?

**Comment by cholalat** [comment]
Se puede utilizar cualquier función incluida en python que no esté explícitamente prohibida aquí, a pesar de que no se hayan visto en el curso como materia? Por ejemplo, .isdigit() o .index()

**Comment by gecoli** [comment]
> Hola!
> 
> ¿Es mala práctica utilizar y modificar el atributo `__class__` de un objeto cualquiera?

¡Buenas tardes, @FelipeFuentesG !

No es considerado una mala práctica.

¡Éxito en tu tarea! ꒰ᐢ. .ᐢ꒱₊˚⊹

**Comment by gecoli** [comment]
> Se puede utilizar cualquier función incluida en python que no esté explícitamente prohibida aquí, a pesar de que no se hayan visto en el curso como materia? Por ejemplo, .isdigit() o .index()


¡Buenas tardes, @cholalat !

Todo built-in de python está permitido (más no de librerías externas), a excepción de los señalados acá. Los que señalas son métodos/funciones básicas, permitidas.


¡Éxito en tu tarea! ꒰ᐢ. .ᐢ꒱₊˚⊹

**Comment by Jpdelaf** [comment]
hola, soy quien hizo la issue #252, quería ver si me podrían decir si puedo hacer uso de ese código.

**Comment by BrucherBeta** [comment]
hola!! Tengo una duda respecto al uso de remove(), pues no se si es una funcion permitida dentro del curso

**Comment by gecoli** [comment]
> hola, soy quien hizo la issue #252, quería ver si me podrían decir si puedo hacer uso de ese código.

¡Buenas tardes, @Jpdelaf !

Dado que ese método entorpecería la corrección, no está permitido que lo ocupes. 

¡Éxito en tu tarea! ꒰ᐢ. .ᐢ꒱₊˚⊹

**Comment by gecoli** [comment]
> hola!! Tengo una duda respecto al uso de remove(), pues no se si es una funcion permitida dentro del curso

¡Buenas tardes, @BrucherBeta !

Depende de a qué `remove()` te refieras, pero si es el método de listas/set, está permitido. 

¡Éxito en tu tarea! ꒰ᐢ. .ᐢ꒱₊˚⊹

**Comment by vicentekrebs** [comment]
¡Hola! ¿A qué se refiere con que "no se pueden usar variables globales de cualquier tipo"? No me queda claro, porque en el archivo parámetros tenemos que agregar los parámetros fijos que se usan en los distintos archivos de la tarea y eso justamente sería hacer uso de variables globales o no? Saludoss!

**Comment by carlosmartellus** [comment]
Hola, puedo usar str.format para los print?

**Comment by gecoli** [comment]
> ¡Hola! ¿A qué se refiere con que "no se pueden usar variables globales de cualquier tipo"? No me queda claro, porque en el archivo parámetros tenemos que agregar los parámetros fijos que se usan en los distintos archivos de la tarea y eso justamente sería hacer uso de variables globales o no? Saludoss!

¡Buenas tardes, @vicentekrebs !

En el caso de los valores en `parametros.py` es distinto, dado que los **importan** y mantienen su valor, simplemente leyéndolos desde el archivo de origen, en cambio las variables globales son consideradas una mala práctica pues están al alcance de todo el programa y estas **podrían cambiar su valor**, cosa que no queremos. Las variables globales están definidas fuera de una función, método de clase, etc., es decir, al alcance global, y ustedes sólo pueden ocupar variables que estén definidas en su propio *scope*, es decir, que sean accesibles sólo desde donde están definidas (sea una clase o una función).

¡Éxito en tu tarea! ꒰ᐢ. .ᐢ꒱₊˚⊹

**Comment by gecoli** [comment]
> Hola, puedo usar str.format para los print?

¡Buenas tardes, @carlosmartellus !

Sí puedes ocuparlo. 

¡Éxito en tu tarea! ꒰ᐢ. .ᐢ꒱₊˚⊹

**Comment by R3Y3X** [comment]
hola, puedo usar Path de pathib, para verificar si existe el path donde se encuentran los archivos?

**Comment by R3Y3X** [comment]
hola, puedo usar except ValueError para verificar que los datos que me entregan en los archivos y en el input son int ?

**Comment by waknaudt** [comment]
Hola, se pueden usar otras cosas del modulo abc aparte de la clase ABC?

**Comment by Arielmild** [comment]
Hola, ¿se podría usar frozenset()?

**Comment by gecoli** [comment]
> hola, puedo usar Path de pathib, para verificar si existe el path donde se encuentran los archivos?
> hola, puedo usar except ValueError y try para verificar que los datos que me entregan en los archivos y en el input son int ?

¡Hola, @R3Y3X !

Sí puedes ocupar pathlib, en cuanto a las excepciones, puedes ocuparla siempre que sea **una en específico** y no genérica, así que lo que señalas sería válido.

¡Éxito en tu tarea! ꒰ᐢ. .ᐢ꒱₊˚⊹

**Comment by gecoli** [comment]
> Hola, se pueden usar otras cosas del modulo abc aparte de la clase ABC? por ejemplo abstractmethod

¡Buenos días, @waknaudt !

Sí, puedes ocupar otros elementos.

¡Éxito en tu tarea! ꒰ᐢ. .ᐢ꒱₊˚⊹

**Comment by gecoli** [comment]
> Hola, ¿se podría usar frozenset()?

¡Buenos días, @Arielmild !

Sí se puede.

¡Éxito en tu tarea! ꒰ᐢ. .ᐢ꒱₊˚⊹

**Comment by UnFedaykin** [comment]
Hola, buen día, ¿se permite el uso de __dict__ de un objeto para obtener sus atributos?

**Comment by gecoli** [comment]
¡Buenas tardes, @UnFedaykin !

Sí se permite su uso. 

¡Éxito en tu tarea! ꒰ᐢ. .ᐢ꒱₊˚⊹

**Comment by KaopyHK** [comment]
Holaa, buenas noches! queria consultar si era posible el uso de os.system('pause') para pausar los printeos entre menus, por ej: luego de printear el ejercito desde el menu principal, hacer uso de ese comando en la terminal para ver el ejercito con calma y luego ser redirigido al menu principal

**Comment by UnFedaykin** [comment]
Hola, buenos días, ¿se permite el uso de os.listdir()? Esto, para obtener los nombres de los elementos de un directorio.

**Comment by gecoli** [comment]
¡Buenas tardes, @UnFedaykin  !

Sí se permite su uso.

¡Éxito en tu tarea! ꒰ᐢ. .ᐢ꒱₊˚⊹

**Comment by josevalenzuelam** [comment]
Hola! se puede usar global para modificar una variable que es definida fuera de las funciones?

**Comment by gecoli** [comment]
Buenas tardes, @josevalenzuelam 

Lo que señalas es equivalente a ocupar una variable global, y eso está penalizado con descuento.

¡Éxito en tu tarea! ꒰ᐢ. .ᐢ꒱₊˚⊹
