### ISSUE TITLE
built -ins

### ISSUE THREAD

**Issue by rmaguilera** [IIC2233/syllabus#166]
Se pueden ocupar todos los built-ins que no fueron explicitamente prohibidos? (exec, eval, exception)
De no ser así, alguno de los siguientes métodos están prohibidos para esta tarea o hay alguna forma de ocuparlos que este prohibido?
.isdigit(), .isalpha(), .isalnum(), .split(), .join(), .sort(), open(), .closed(), .write(), .read(), .readlines(), .splitlines().
También tengo la duda de si se pueden crear listas por comprensión, por ejemplo:
lista = [x.metodo() for x in otra_lista if x.metodo() != valor]

**Comment by CamilaArgomedo** [comment]
tengo una duda con esto también, tengo un error al salir en mi código desde el sub menú (menú donde se elige menú) al poner salir tengo que elegir esa opción un par de veces hasta que finalmente sale y quería saber si puedo usar "import sys" y "sys.exit()" para corregir esto

**Comment by igbasly** [comment]
Hola @rmaguilera y @CamilaArgomedo 😄
Respecto a las dudas acerca de qué librerías o módulos pueden utilizar para su Tarea, deben utilizar la issue #4. Ahí podrán visualizar todas las librerías autorizadas y prohibidas, además, si tiene dudas acerca de alguna en particular que no esté mencionada, deben realizar la consulta como un comentario siguiendo el formato indicado.

Éxito :v:
