### ISSUE TITLE
Funcionalidad no usada en nuestra estructura

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#166]
Hola!

En el punto 5 del enunciado de la tarea 2 dice:

> Tus implementaciones deben replicar la funcionalidad básica de sus contrapartes

Si nuestra estructura tiene una funcionalidad que no usaremos, podemos no implementarla? Por ejemplo si nunca uso slices con mi clase KamiList, puedo no implementar el manejo de estos??

Saludos!

**Comment by sebacruzd** [comment]
Solamente las que salen en el enunciado son obligatorias, el resto de las EDD son opcionales y en esos casos debes implementar solamente lo que quieres usar.

Saludos!

**Comment by akaminetzkyp** [comment]
Oka, gracias!

**Comment by sebacruzd** [comment]
P.D:

`__setitem__, __getitem__, __delitem__, __next__, __iter__, __len__`

son las obligatorias :)

**Comment by akaminetzkyp** [comment]
😁

**Comment by akaminetzkyp** [comment]
Las listas no son iteradores, por lo que no tienen __next__. Tambien debemos incluirlo en nuestra lista?

**Comment by sebacruzd** [comment]
Como dices, las listas no son iteradores, pero sí **iterables**. No debes implementarlo si es que originalmente no lo tiene, **pero sí debe estar implementado en las EDD que sí lo tienen y al menos una vez en tu tarea cada uno de los obligatorios**.

**Comment by akaminetzkyp** [comment]
Perfecto, gracias!

**Comment by akaminetzkyp** [comment]
Hola!

Perdón por reabrir esto por segunda vez, pero me acabo de dar cuenta que ninguna de las EDD que implementaré tiene `__next__`. Mis EDD propias serán listas y diccionarios, y las originales de python no tienen este método. Sin embargo, los métodos `__setitem__, __getitem__, __delitem__, __next__, __len__` serán implementados correctamente.

Como ninguna de mis EDD tienen el método `__next__`, ¿puedo no implementarlo en mi programa?

Saludos!

**Comment by negutierrez** [comment]
Si no voy a usar ninguna edd del tipo "diccionario", igualmente tendría que implementar __next__? Aun cuando no lo vaya a usar....

**Comment by acrojas2** [comment]
Alguien me podría explicar eso de que las listas no son iteradores pero si iterables?  qué significa que no sea un iterador? tampoco entiendo que es lo que hace __next__ ... por favor si alguien me lo puediera explicar con detalle para poder entenderlo bien :)

**Comment by Minjor** [comment]
me sumo a lo pedido por @acrojas2 y @negutierrez previamente

**Comment by rrhurtado** [comment]
1. Los métodos pedidos como obligatorios deben ser implementados, aún cuando no se haga uso de alguno de ellos en una solución en particular.
 

2. Sin entrar en mucho detalle, un iterable es un objeto que implementa el método `__iter__`, el cual retorna un **iterador**. Este objeto iterador es el que finalmente define la lógica de la iteración , en la que se hacen consecutivas llamadas al método `__next__ ` para acceder a los elementos del contenedor uno a la vez y en orden hasta que éstos se acaban. 

La diferencia principal entonces, es que uno puede hacer `next(Iterator)` sin problemas, mientras que `next(List)` por ejemplo devuelve error.  

`s = 'dog'    # Los strings también son iterables `
`it = iter(s)    # Conversión a iterador `
`next(it)`
-> 'd'
`next(it)`
-> 'o'
`next(it)`
-> 'g'
`next(it)`
-> Error

Espero haya servido, igual nunca está de más un link a la documentación para profundizar
https://docs.python.org/3/tutorial/classes.html#iterators

**Comment by akaminetzkyp** [comment]
Entiendo que tengamos que implementar los métodos en las EDDs que los posean, pero las listas y diccionarios de python no tienen el método `__next__`, por lo que encuentro que no tendría sentido implementarlo en nuestras EDD. Saludos!

**Comment by rrhurtado** [comment]
Tal como ya respondío sebacruzd, debe estar cada método de los obligatorios implementado por lo menos una vez en tu tarea. En qué EDD agregarlas queda a su criterio.
