### ISSUE TITLE
Mejoras de un vehiculo

### ISSUE THREAD

**Issue by anvaldes** [IIC2233/syllabus#167]
Las mejoras a los vehículos pueden aumentar tanto como quieran ciertas características de mi vehículo? o el máximo sería el valor que esta indicado en el archivo parametros.py

**Comment by cfalvarez2** [comment]
Hola @anvaldes 
Como dice el enunciado, queda a tu criterio si se puede elegir solo una mejora por cada vuelta, o las que se permitan con el dinero que posee. El máximo y el mínimo del archivo ``parametros.py`` son los valores que permitirán crear a los vehículos al momento de comprarlos. Por lo que, en cuanto a las mejoras, al comprarlas, cada mejora tendra un efecto que viene dado por una constante y que se explica en el enunciado en la parte de Vehiculo.
Espero haber aclarado tu duda :)

![image](https://user-images.githubusercontent.com/37164236/64366447-3f1eff80-cfe4-11e9-9a91-0799afcdac2b.png)

**Comment by anvaldes** [comment]
Hola! Gracias por la respuesta, aunque mi pregunta iba dirigida a si por ejemplo tengo un valor de chasis = 10 y luego aplico muchas mejoras y llego 1.000.000. Sin embargo en mi archivo de parametros me dice que el valor maximo de chasis es 1.000, en ese caso:

¿Debo dejar el valor del chasis como 1.000.000 o como 1.000?

**Comment by cfalvarez2** [comment]
Entiendo, en el enunciando no se menciona sobre restringir las mejoras al aplicarlas, en tu caso podría llegar a 1.000.000 siempre y cuando tengas el dinero suficiente. 
Saludos
