### ISSUE TITLE
Registrarse en un mercado para poder ver su información

### ISSUE THREAD

**Issue by mesantamaria** [IIC2233/Syllabus#167]
Hola,
en el enunciado dice que para que los Underaged puedan ver la información de los mercados, tienen que estar registrados en ellos. Esto aplica para cuando pregunten por cualquier cosa? Por ejemplo si preguntan por las orders activas del sistema, por orders en alguna fecha o por el historial de matches, les mostramos solo las de los mercados que tienen registrados?

Supongo que esto es para los Traders también.

**Comment by Arcoirisky** [comment]
Hola! La idea es que sí estén inscritos para preguntar sobre cosas de ese mercado O:! Y al preguntar también deberían ser de los mercados inscritos, ya que "en teoría" no le interesarían las orders de otros mercados. De todas formas, lo último puedes especificarlo en el Readme dependiendo de cómo lo decidiste hacer para que nos enteremos c: 
Suerte!!
