### ISSUE TITLE
.gitignore no funciona con archivos ya subidos

### ISSUE THREAD

**Issue by rmaguilera** [IIC2233/syllabus#167]
cree un archivo .gitignore, para esto escribí en el terminal:
git commit
git touch .gitignore
git vim .gitignore
después escribí los nombres de los archivos que quiero ignorar:
Enunciado.pdf
seguidores.csv
usuarios.csv
posts.csv
pero al hacer git push se siguen subiendo los archivos ignorados, (no les puse git add)
qué tengo que hacer para que no se suban al repositorio privado??

**Comment by MatiasDuhalde** [comment]
Holaa!

Lo que pasa es que los archivos que pusiste ya están subidos a tu repositorio privado, por lo tanto el `.gitignore` no tiene efecto. Para que funcione, tienes que "borrarlos" primero. Para borrarlos de tu repo remoto pero no de tu carpeta local tienes que usar el siguiente comando:
`git rm --cached archivo_a_borrar.csv`
Y después hacer un commit para aplicar los cambios. Después de eso te debería funcionar el archivo `.gitignore`

Avisanos si te funcionó :)
