### ISSUE TITLE
Problema para importar con ruta relativa

### ISSUE THREAD

**Issue by rodrigoogalde** [IIC2233/Syllabus#167]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola!
Con respecto al problema para importar parámetros desde una sub carpeta, traté de utilizar import .., lo que me generó el mismo problema que en la AS3. Esta permitido utilizar el comando que nos entregaron en la actividad para solucionar ese problema?

**Comment by Emiliax16** [comment]
Como mencioné en la issue #158 , la mejor manera de evitar problemas de importación es que importes todos los archivos necesarios en el main, y desde ahí los pases a los demás módulos. De todas maneras, ¿podrías enviar el código que fue entregado para la activdad? 👀
