### ISSUE TITLE
[Tarea 2 - 3.6] Duda formula probabilidad de contagio

### ISSUE THREAD

**Issue by asdegoyeneche** [IIC2233/Syllabus#167]
Hola!

Dos preguntas, en el punto 3.6 se da la formula para la probabilidad de contagio. Esta incluye el numero de conexiones del pais de origen: supongo que se refiere a las conexiones **abiertas**. Sí?

Y lo otro, no me calza que la probabilidad de contagio disminuya a medida que tenga más conexiones, esta bien la formula? o entendí algo mal? :/

Gracias!

**Comment by arturodelreal** [comment]
Hola, si se refiere a las conexiones abiertas. Y la formula está bien, disminuye porque en teoría hay más países donde viajar. Como aclaración esa formula se usa con cada conexión.
Salu2

**Comment by asdegoyeneche** [comment]
Buena perfecto, gracias!
Salu3
