### ISSUE TITLE
Duda con TestCase test_3x4_alcance_1_sin_peon

### ISSUE THREAD

**Issue by sbarriag** [IIC2233/Syllabus#167]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, me queda la duda con el siguiente test case puesto que según el, para la reina (R3) en (2,0) debería arrojar 8 celdas afectadas, sin embargo no entiendo porque no es **7** si al desplazarse 3 a la derecha no parte contándose a si mismo como 1?
![image](https://github.com/IIC2233/Syllabus/assets/127463084/54a10e87-12c4-478b-87d7-bd70260648ee)

![Sin título](https://github.com/IIC2233/Syllabus/assets/127463084/0c505ae5-0fb8-47c2-acaf-3c9d8fc0f69d)

Muchas gracias

**Comment by maromero-21** [comment]
Tienes en total:
* 1 para la misma celda: (2,0)
* 2 hacia arriba: (1,0) y (0,0)
* 3 hacia la derecha: (2,1), (2,2) y (2,3)
* 2 Diagonales hacia arriba y la derecha: (1,1) y (0,2)
Por lo que en total SÍ son 8 celdas afectadas.

**Comment by sbarriag** [comment]
Perfecto muchas gracias
