### ISSUE TITLE
Impresión tablero propio y enemigo

### ISSUE THREAD

**Issue by sreitze** [IIC2233/syllabus#167]
Hola, tengo un problema con imprimir mi tablero. Una vez creados ambos tablero e ingresados los barcos aleatoriamente, estoy imprimiendo estos como listas (sin función print_tablero) para verificar que realmente se hayan ingresado los barcos correctamente. Todo funciona bien hasta aquí, pero al usar la función print_tablero(*,*), me imprime ambos tablero en el formato correcto pero sin los barcos del tablero de arriba. Saludos
![Anotación 2020-08-25 113357](https://user-images.githubusercontent.com/69603335/91195460-041b4d80-e6c7-11ea-9a3d-8ec7f5ccd5eb.png)

**Comment by matiasmasjuan** [comment]
Hola @sreitze !

Esto no es ningún problema, ya que la función ```print_tablero(tablero_rival, tablero_propio)```oculta los **Barcos** del **Oponente**.

Esto se puede ver de manera clara en la **línea 13** del archivo ```tablero.py```:

![linea_13_tablero](https://user-images.githubusercontent.com/48495638/91196437-2497d780-e6c8-11ea-805d-8d7db36dfe11.png)

Como podrás notar, por cada **elemento** de cada **sublista** del tablero, se imprime el '■' sólo si el **elemento** es un espacio (' '), o una 'B'.

La razón de por qué fue hecho así se debe a que en una partida sería **ilógico** o muy **tramposo**  poder visualizar los barcos del oponente :sweat_smile:, ya que se sabría de manera inmediata dónde disparar.

Si quieres probar donde se ubicarían los barcos del oponente, bastaría con cambiar la **línea 13** del archivo ```tablero.py```, borrando la sentecia ```or x == 'B'```. De esta forma, te quedaría así:

```python
tablero_rival = [['■' if x == ' ' else x for x in y] for y in tablero_rival]
```

Espero que esto te sirva de ayuda, y mucho éxito con la tarea! :smile:

**Comment by sreitze** [comment]
Muchas gracias! también me parecia lógico que fuera asi.
