### ISSUE TITLE
Compilado de Issues T2

### ISSUE THREAD

**Issue by gecoli** [IIC2233/Syllabus#167]
En la siguiente _issue_ encontrarás todas las _issues_ sobre la Tarea 2 que se han realizado hasta el momento, estas están divididas según diferentes temas.
Antes de hacer una nueva _issue_, revisa si tu duda ya fue realizada, así evitamos las _issues_ duplicadas. 😄

### Librerías permitidas, no permitidas y malas prácticas ✔️❌ 
1.  #217 
2. #252 
3. #257
4. #262  

## Programación Orientada a Objetos
1. 

## Preparación programa
1.  #235 
5. #241 

## Entidades
1.  

### Ejército
1. #191 
2. #244 
6. 

### Combatientes
1. #171 
7. #175 
8. #178 
9. #200
10. #206 
11. #209 
12. #213 
13. #219 
14. #218 
15.  #226 
16. #227 
17. #238 
18. #250 
19. #243 
20. #245 
21. #248 
22. #255
23. #272
24. #277
25. #279

### Ítems
1. #204
3. #211 
4. #225 
5. #275
6. #274
## Flujo del programa
1. #223 
2. #243 
3. #247 

### Menú de Inicio
1. 

### Menú Tienda
1.  #176 
4. #240
5. #271

### Selección de Gato
1. #221 

### Fin del Juego
1. #192 
6. #214 
8. #229 
9. #247 
10. #258

### Robustez
1. 

## Archivos
1. #205 
10. #210
11. #230 
12. #254 

### Archivos .txt
1. #201
2. #246 
3. #253 
4. #261 
6. #264
7. #270
8. #273

### parametros.py
1. #169 
5. #216 
9. #231 
10. #232 
11. #239 
12. #269
   
---
### Otros
1. #188
2. #208
5. #220 
6. #256

**Comment by ignanuyens** [comment]
Valor de los parámetros.
Tengo una duda sobre el archivo parametros.py. Una vez que cree el archivo con todos los parámetros que fueron marcando a través del enunciado ¿qué valor les pongo?
Muchas gracias de antemano.
