### ISSUE TITLE
items posibles de encontrar

### ISSUE THREAD

**Issue by GuilleStanke** [IIC2233/Syllabus#167]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

hola buenas... cuanto un item es encontrado, este se debe borrar de los items que tiene la arena?, es decir, un mismo item se puede encontrar dos veces? o al ser encontrado se elimina y así no se puede encontrar nuevamente

**Comment by Benjeeeh** [comment]
Hola!
Como no se específica en el enunciado, queda a tu criterio el como manejas esta situación, especificándolo en tu README. De la manera que elijas, deberás tener en cuenta los casos de si se repite un ítem (no eliminarlo del lote de ítems) o de que si se van eliminando, contemplar el caso de que la cantidad de ítems sea igual a 0 y que no provoque una caída del programa.

Éxito en la tarea!

**Comment by tremendapithon** [comment]
Hola buenas noches, tengo una consulta respecto a si cada vez que el equipo gana un item, yo lo tengo que eliminar de los items de la arena?

**Comment by Benjeeeh** [comment]
Buenas noches @tremendapithon (buen nombre)

Como se discutió arriba, queda a tu criterio si eliminas o dejas de manera infinita los ítems, solo tienes que especificarlo en tu README.

**Comment by tremendapithon** [comment]
gracias mi estimado
