### ISSUE TITLE
Duda modulo libraría

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#167]
Hola, no entiendo muy bien la diferencia entre módulo y librería (que poner en cada parte):

![image](https://user-images.githubusercontent.com/47841749/55761584-cc5a2a00-5a2d-11e9-9170-d089d878c41d.png)

**Comment by iqacevedo** [comment]
Hola,

Creo que [aquí](https://www.quora.com/What-is-the-difference-between-Python-modules-packages-libraries-and-frameworks) está muy buen explicado.

¡ Saludos !
