### ISSUE TITLE
Repositorio

### ISSUE THREAD

**Issue by nnovoag** [IIC2233/syllabus#167]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, al abrir mi repositorio, me aparece que hay una issue que se llama AF1 que la mando alguien del ramo, mi duda es que ahí aparece un link donde yo entro supuestamente a mi repositorio, pero cuando entro, no esta con todas las cosas que realmente tiene.... no se que onda eso
Gracias de antemano!

**Comment by aaossa** [comment]
Hola @nnovoag , el mismo día de la actividad les enviamos un anuncio explicando todo esto 😅, te recomiendo revisar ese anuncio ("Post Evaluación: Proceso de recolección de evaluación 🤖📝: Programacion Avanzada") en Canvas. El *link* muestra el estado del repositorio al momento de la recolección, que es (de cierta manera) lo que verán les ayudantes al momento de corregir. Si tienes alguna duda adicional pregunta por acá mismo no más 👌

**Comment by nnovoag** [comment]
Bknn! Gracias por la aclaración :)
