### ISSUE TITLE
AC2 Duda enunciado método recorrer

### ISSUE THREAD

**Issue by RGutierrez21** [IIC2233/Syllabus#167]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

En la descripción del método ```recorrer```  de las clases ```AutoBencina``` y ```AutoElectrico``` se menciona cómo calcular el gasto del movimiento, pero no me termina de quedar claro el cómo calcularlo. 

![image](https://github.com/user-attachments/assets/e695b840-7831-43dc-bff7-86434a974a7d)

**En particular, no entiendo bien la parte ```kilometros\_recorridos/self.rendimiento```, la parte "```kilometros\_recorridos```" es un typo?**

Muchas gracias!

**Comment by dani-oviedo** [comment]
por lo que yo entendí así llamaron a la variable nada mas, tu a lo mejor le pusiste otro nombre pero son los kilómetros que alcanzo a recorrer según lo que te dice el enunciado, de que si sobrepasa o no lo que dice la autonomía y los kilómetros que te entrega recorrer, eso lo divides en el self.rendimiento para saber al final cuanta energía consumiste.

**Comment by Hernan4444** [comment]
Hola @RGutierrez21 

Jutamente como dice dani-oviedo, era solo el nombre que le pusimos a la variable, pero se nos pasó el `\` es un typo, debía ser (`kilometros_recorridos / self.rendimiento`). Era para indicar que el gasto corresponde a la cantidad de "kilómetro recorridos" dividido en el "rendimiento" del vehículo. Y kilómetros recorrecido va a depender de la autonomía.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ

**Comment by RGutierrez21** [comment]
Muchas gracias! Me quedó súper claro
