### ISSUE TITLE
Ganar batalla

### ISSUE THREAD

**Issue by mvveram** [IIC2233/Syllabus#167]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!

En otra issue vi que al perder la batalla todos los atributos parten con el valor original. Ahora, mi duda es al ganar las cuatro batallas, o sea al ser campeón, también todos los atributos parten con el valor original o se mantienen porque se gano. En esta misma línea, mientras uno sigue en el juego y va ganando partidas se mantiene los atributos hasta que pierda?

Muchas gracias de antemano

**Comment by mvveram** [comment]
Hola, 

Si cache eso, pero me refería (no lo puse antes) sobre que pasa con los atributos del programón si gana las 4 batallas y cuando va ganando de a una. Es decir, si usamos una baya, luego de la ronda 1 se va o se mantiene hasta perder.

**Comment by Emiliax16** [comment]
Si se gana el campeonato (o se comienza una nueva partida), se aplica lo mismo que dije antes: todos los atributos deben volver a sus valores originales. Ahora, si se gana una partida en la que usaste un objeto, estos cambios se mantienen en todo el campeonato para el programon. Saludos c:

**Comment by mvveram** [comment]
Muchas gracias!!
