### ISSUE TITLE
aun no me llega el link de mi repsitorio

### ISSUE THREAD

**Issue by feliperojas123** [IIC2233/syllabus#168]
mmm... sucede que respondi la encuesta el jueves pasado y aun no me llega el link de mi repsitorio y como la tarea es para el sabado igual me preocupa que no me llega para tal fecha... si me lo pueden responder seria de gran ayuda... graciaaas

**Comment by lily416** [comment]
Hola @feliperojas123,

Hace unos momentos te volví a enviar la invitación a tu repositorio del curso, fíjate en que:
* Al correo que usaste para registrarte te haya llegado un mail de parte de noreply@github.com, o que
* Al ingresar a tu cuenta de GitHub, en el menú superior izquierdo te aparece una notificación invitándote al repositorio.


Cuentame como te va 👋 :octocat:

**Comment by feliperojas123** [comment]
muchaaaas graciaaaas te pasaste... solucionado todo❤️

**Comment by feliperojas123** [comment]
si lo hice pero mi correo del github no es el de la institucion...

**Comment by lily416** [comment]
Hola @feliperojas123,

No hay problema que no hayas usado tu correo UC para crear la cuenta, eso solo implica que las notificaciones te llegarán a ese correo y tendrás más dificultades para acceder al GitHub Student Pack.

Aún así, si lo deseas puedes cambiar tu dirección de correo en Settings > Emails.

Saludos 👋📬
