### ISSUE TITLE
problema al correr visual studio code

### ISSUE THREAD

**Issue by tzehnder** [IIC2233/syllabus#168]
hola desde hoy en la mañana he tenido varios problemas con visual studio al correr mi codigo. en un principio intente guardar variables y no me estaba dejando. luego al intentar imprimir una linea de uno de los archivos entraba en un loop de impresion hasta que yo ponia que se detuviera.
ahora nisiquiera es capaz de imprimir una letra como "a", 
PS C:\Users\tomas>  ${env:DEBUGPY_LAUNCHER_PORT}='50355'; & 'C:\Users\tomas\AppData\Local\Programs\Python\Python37\python.exe' 'c:\Users\tomas\.vscode\extensions\ms-python.python-2020.3.69010\pythonFiles\lib\python\debugpy\wheels\debugpy\launcher' 'c:\Users\tomas\Desktop\tzehnder-iic2233-2020-1\Tareas\T00\prueba.py'
llega hasta esa parte de la impresion y no pasa nada mas.
vale decir que lo estoy corriendo con "run without debugging"

**Comment by fddelabarra** [comment]
como no te responderan por ser domingo, te dire como avanzar mientras, espero te sirva
Yo uso sublime, y como no se si se puede correr diretamente de ahi, uso el propio git bash, como es una consola es mejor para correr los programas, la manera de hacerlo es si tienes un archivo llamado main.py por ejemplo, pon en la consola "py main.py", mientras no te responden, espero te ayude!
