### ISSUE TITLE
Conexiones bidireccionales en aeropuertos

### ISSUE THREAD

**Issue by IriSalazar** [IIC2233/Syllabus#168]
Pregunta!

Puedo asumir que todas las conexiones de los aeropuertos son conexiones bidireccionales? Cualquier avion puede llegar a cualquier aeropuerto?

Gracias!

**Comment by sebacruzd** [comment]
Las conexiones de los aeropuertos son bidireccionales.

Los aviones solo pueden llegar a los aeropuertos de países a los que tienen conexiones (dado por el archivo random_airports.csv)

Por ejemplo, Chile solo puede llegar a Australia con lo de la foto.

![image](https://cloud.githubusercontent.com/assets/14894992/24383402/1206d4f2-1333-11e7-9240-fbfbb322ac11.png)



Saludos!

**Comment by seba608** [comment]
Una consulta con este tema. Si las conexiones son bidereccionales, por qué el archivo random.airports repite algunas conexiones? Por ejemplo:

![foto1](https://cloud.githubusercontent.com/assets/26118304/24583880/d4c89dd6-172f-11e7-994c-d1a54f69ed89.PNG)

Aquí se ve que se generó por ejemplo Austria, Costa rica, pero no Costa rica, Austria, pero como son bidireccionales igual lo debería generar yo cierto? En cambio para Austria, Germany también se genera el Germany-Austria y no entiendo para qué, porque sería redundante esa linea si fuesen bidireccionales

**Comment by fdominguezclaro** [comment]
@sebacruzd Que paso con la pregunta de @seba608 ??

Gracias!!

**Comment by stephichau** [comment]
El .py que genera los archivos, solo genera conexiones de un pais a otro. Por ende, pueden existir conexiones reduntantes.
