### ISSUE TITLE
Representar returns en diagrama de clases 

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#168]
Hola! Tengo una consulta... Qué pasa si en un método, tengo distintos tipo de retornos, dependiendo del caso? Por ejemplo:

```
from random import random

class A:

    def metodo(self):
        if random() <= 0.5:
            return ["Hello", "World!"]
        else:
            return "Hello World!"
```

Claramente, este no es ningún método de mi tarea, pero representa mi caso: un método que tiene distintos tipos de return. No sé cómo representar eso en el diagrama de clases. Gracias de antemano :)

**Comment by llloyola** [comment]
Otra consulta... Qué pasa si en la clase Planeta, tengo un atributo self.raza que corresponde a la raza del planeta, pero como clase raza, no como string. 
Dado que este atributo puede tomar el valor: Asesino(), Maestro() o Aprendiz(), no sé cómo representar el atributo self.raza para la clase Planeta en el diagrama de clases.

**Comment by naquiroz** [comment]
Hola, no soy ayudante, pero tenia la misma duda que tu hace un tiempo, y encontre la respuesta [aquí](https://stackoverflow.com/questions/42864003/uml-class-diagram-what-do-i-put-the-output-type-for-a-function-that-can-return).

Basicamente lo que dice el link es que si tienes que retornar mas de algun tipo de dato, probable que tu programa puede ser modelado de una mejor manera, pero hay veces donde si es valido retornar difernetes tipos y en esos caso se usa:
```
{ int | exception }
```
donde int y exception son los dos posibles retornos.
