### ISSUE TITLE
Problema con self.tablero_transformado

### ISSUE THREAD

**Issue by martina-abello** [IIC2233/Syllabus#168]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Pensé que ya tenía esa property lista, pero haciendo otros tests me di cuenta de que usarla me altera también el tablero original, aunque use [:] o .copy() para copiarlo. 

Sin embargo, y esto es lo que en verdad me llama la atención, todos los testcases de test_tablero_transformado me entregan 'ok', lo que _debería_ significar que la lista original no cambia. Por eso no me había dado cuenta de que tenía un problema. 

O sea, algo no cuadra. ¿Podría haber un error en los testcases también?

En todo caso, agradecería ayuda para arreglar la property.

**Comment by ManuelV03** [comment]
Hola, debido a la naturaleza del tablero de ser una lista de listas, lo más probable es que esos métodos para copiar la lista no cumplan tu objetivo de que no se modifique la lista original. Para lograr esto te recomiendo usar la función deepcopy de la libreria copy. En el siguiente link puedes encontrar toda la información que necesitas para esto https://www.geeksforgeeks.org/copy-python-deep-copy-shallow-copy/ Avísame que tal te va.

**Comment by martina-abello** [comment]
Ahí me funcionó, muchas gracias!

Igual me preocupó que los tests no me avisaran del problema :P casi entrego mala la cuestión
