### ISSUE TITLE
Volver en el menu de entrenamiento

### ISSUE THREAD

**Issue by pgaguilera** [IIC2233/Syllabus#168]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Si decido voler al menu de inicio después de entrenar a mi programon, y vuelvo a elegir al mismo entrenador y al mismo luchador ¿este mantiene el aumento de atributos que genera el entrenamiento?

**Comment by Emiliax16** [comment]
Hola @pgaguilera . Volver al menú de inicio cuenta como volver a empezar, por lo que se sigue el mismo razonamiento explicado en otras issues: siempre que se vuelva al inicio se resetean todos los valores originales de las entidades. Tómalo como que todo lo que hagas con un entrenador sólo cuenta para esa jugada, si ganas o pierdes el campeonato o vuelves al inicio, se reinician los atributos cambiados. Saludos 😸
