### ISSUE TITLE
Contrincantes

### ISSUE THREAD

**Issue by mvaldes12** [IIC2233/syllabus#168]
¿Para asignarle un vehículo a los contrincantes lo debo hacer buscando en vehículos los nombres de los contrincantes?
Si es así, ¿Qué pasa si un contrincante tiene dos vehículos? ¿Cual ocupo para la carrera?
Gracias

**Comment by cfalvarez2** [comment]
Hola
Te recomiendo mirar la issue #123 hasta el final, ahí se comenta al respecto. 
Si no es lo que buscas puedes volver a comentar esta.
Espero te haya servido.
