### ISSUE TITLE
Referencias de código externo en README

### ISSUE THREAD

**Issue by tamyhan** [IIC2233/syllabus#168]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola! Las referencias que hay que incluir son si es que copié un código largo o si es que usé alguna función no vista en clases que encontré en internet? O en ambos casos?

**Comment by aaossa** [comment]
Hola @tamyhan , yo diría que aplica para ambos casos.

Otra cosa que diría es que **ante la duda siempre es mejor referenciar** (solo por si acaso). En general, lo que se referencia es cualquier idea/código que no provenga de tu autoría. Por ejemplo, hay un ejemplo muy bueno en la documentación de Python y baso un método de una clase completamente en cómo está en la documentación: entonces lo referencio porque de ahí saqué la idea. También si encontraste una respuesta en StackOverflow donde aparece una función que hace justo lo que necesitas y la copias directamente, es necesario referenciar por el mismo principio anterior.

En general, referenciar siempre ayuda tanto para ti mientras estás haciendo la evaluación (por si cambiaste algo y después te arrepientes y quieres revisarlo de nuevo), así que es 100% recomendado ir referenciando esas cosas ✨ Si tienes alguna otra duda pregunta quedo atento 👌
