### ISSUE TITLE
git add Tarea 1

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#168]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holaa, si es que ya tengo listo el archivo .gitignore, ¿debo hacer git add de la carpeta entera de la tarea 1? ¿o solo debo hacer git add de main, dccultivo y README??

**Comment by canija2000** [comment]
(soy estudiante tb) Si tienes el gitignore con los archivos a ignorar, aunque hagas `git add .` , git va a respetar lo que esta en ese archivo, asi que solo se van a pushear esos archivos

**Comment by vicho14** [comment]
Hola! , es exactamente lo que dice tu compañero :). Es la forma mas simple y efectiva.
