### ISSUE TITLE
Diagrama de T1

### ISSUE THREAD

**Issue by Ameliasch** [IIC2233/Syllabus#168]
Hola, queria saber como escribir en mi diagrama que los metodos son abstractos? En un parentesis dentro del metodo ?

**Comment by Juampisaez** [comment]
Hola @Ameliasch 
Puedes colocar antes del nombre del metodo _@abstractmethod_ para identificarlo.  
Otra forma que existe (que a mi me gusta) para colocar las clases abstractas, es colocar el nombre de la clase y los metodos abstractos en cursiva. 

Espero te sirva :)
