### ISSUE TITLE
Rangos características excavadores

### ISSUE THREAD

**Issue by rominaarancibia** [IIC2233/Syllabus#168]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! En el punto 4.3 página 10 se define que las características, por ejemplo, fuerza o suerte corresponden a int entre 1 y 10. Sin embargo, en el ejemplo de mostrar estado torneo (figura 5, página 7) estas mismas características (fuerza, suerte, etc) aparecen con valores mucho más grandes como 35, entre otros. Entonces mi duda es: estas características ¿tienen limites en sus valores , por ejemplo, entre 1 y 10 o bien pueden tomar cualquier valor ilimitadamente incluyendo negativos?.
Muchas gracias

**Comment by osillano** [comment]
Hola @rominaarancibia!

Esas características sí tienen límites, debes guiarte por lo que se dice en el punto 4.3. La figura 5 está ahí solo para dar una idea de la información que se debería mostrar al elegir la opción de mostrar el estado del torneo.
