### ISSUE TITLE
Extraer los datos solicitados de una QComboBox

### ISSUE THREAD

**Issue by jimmygallardo** [IIC2233/Syllabus#169]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Durante esta tarea la pestaña principal la realice con qt desinger, pero a la hora de extraer los datos solicitados (nombre, ambiente y alien) me surgen unos problemas, creo haberlos definido con las opciones correctas, el nombre lo extraigo correctamente en mi codigo python, pero tanto el ambiente como el alien me arrojan error (se solicitan en el mismo formato (QComboBox) con las alternativas correspondientes, bueno cuando en el codigo lo quiero extraer con el codigo .text() este me arroja el siguiente error:

AttributeError: "QComboBox" object has no attribute "text"

y bueno la verdad no se como extraer la infomacion de los QComboBox

**Comment by CristobalPerez-Cotapos** [comment]
Hola!! Efectivamente combo box no tiene el método text_(), pero si tiene el método currentText() que funciona de forma similar.
Puedes leer más acá
 https://www.google.com/amp/s/www.geeksforgeeks.org/pyqt5-getting-the-text-of-selected-item-in-combobox/amp/

Coméntame si te funciona!! 😄

**Comment by jimmygallardo** [comment]
siiii, ya me funciono, muchas gracias. <3
