### ISSUE TITLE
Durabilidad de las mejoras

### ISSUE THREAD

**Issue by anvaldes** [IIC2233/syllabus#169]
Si a mi chasis por ejemplo pasa de valer 10 a 20, termino la carrera y cierro el programa. Ahora si vuelvo a abrir el programa el chasis de ese auto en especifico debe seguir valiendo 20 o eso debe pasar solo si se guardo la partida cuando se de la opción?

**Comment by jeschuwirth** [comment]
Hola!

La partida sólo si guarda si el usuario va al menú principal y elige la opción `guardar partida`, por lo tanto no es necesario que hagas un 'autosave' que guarde automáticamente después de cada carrera.

Suerte!
