### ISSUE TITLE
Ayudantia Listas Ligadas y Arboles

### ISSUE THREAD

**Issue by jfpena1** [IIC2233/syllabus#169]
Hola, Dante dijo en la ayudantia que subirian la modelacion "alternativa" a la del contenido para arboles y nodos. Se mostraron un par de formas de modelarlo y despues se hizo el ejercicio de actividad, sin embargo solo esta subido el ejercicio. Seria de mucha ayuda si pueden subir lo otro tambien Muchas Gracias.

**Comment by Drpinto1** [comment]
Saludos!
Efectivamente hay un error con el archivo subido, lo actualizaré lo antes posible :smile:

**Comment by Drpinto1** [comment]
Ya subí la solución correcta al Syllabus, gracias por el aviso!
