### ISSUE TITLE
Problema al imprimir tablero

### ISSUE THREAD

**Issue by nimorales97** [IIC2233/syllabus#169]
Hola, estoy recién empezando la tarea y aún no he hecho ningún cambio en ninguno de los archivos. Corrí `main` sólo para ver si imprimía el tablero en el ejemplo pero me tira el siguiente error:
![image](https://user-images.githubusercontent.com/30670006/91205853-3a12fe80-e6d4-11ea-997c-dda6b2d38d7b.png)
¿Es un error en mi pc? ¿Qué debo hacer?

**Comment by vicentevegaulloa** [comment]
Hola @nimorales97 !

Estas teniendo un problema de encoding, intenta cambiando a `False` o `True` en el argumento `utf8` de la función `print_tablero(tablero_rival, tablero_propio, utf8)`.

En el enunciado se explica esto en la seccion tablero.py:

> utf8: booleano (es decir True o False) que indica si el tablero se imprimirá con caracteres UTF-8 o
no, ya que dependiendo de la fuente que utiliza tu consola, el tablero puede presentar problemas para
mostrar los caracteres UTF-8 o deformarse. El valor por defecto de esta variable es True, en dicho
caso el tablero imprimirá los caracteres UTF-8, mientras que si es False, estos no se imprimirán.
Por lo tanto, si es que tu tablero no se está mostrando correctamente te recomendamos dejar el
valor de este argumento como False.

**Comment by nimorales97** [comment]
Ahí funcionó! Muchas gracias!

**Comment by vicentevegaulloa** [comment]
De nada!!

**Comment by gatochico** [comment]
@nimorales97 Recuerda no cerrar las issues por si alguien más tiene la misma duda! Nosotros las cerraremos cuando llegue el momento.
