### ISSUE TITLE
Valor de los parámetros

### ISSUE THREAD

**Issue by ignanuyens** [IIC2233/Syllabus#169]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Tengo una duda sobre el archivo parametros.py. Una vez que cree el archivo con todos los parámetros que fueron marcando a través del enunciado ¿qué valor les pongo?
Muchas gracias de antemano.

**Comment by Benjeeeh** [comment]
Hola, buenos días!
Tú debes asignar el valor que estimes conveniente para cada parámetro, y que por supuesto tengan sentido entre sí, **a excepción de los parámetros en azul que tengan un valor ya asignado**, como los stats de Combatiente, que se muestra en la siguiente imagen:
![image](https://github.com/IIC2233/Syllabus/assets/78326186/ebf75e1d-6601-4a77-be53-0390f59c3edc)

¡Mucho éxito!

**Comment by jisalasc** [comment]
Entonces debo crear un parametro llamado VIDA_MAXIMA en parametros.py??

**Comment by Drpinto1** [comment]
¡Hola @jisalasc!

A lo que se refería @Benjeeeh es que hay texto en el enunciado con el mismo color y formato que los parámetros, pero que no corresponde a parámetros, si no a constantes o números fijos.

El ejemplo que da con la vida máxima es para decir que el 0 y el 100 que aparecen en el enunciado **no deben ser parámetros**, si no simplemente los valores indicados.

Cuéntame (o reacciona a este mensaje) si queda más claro :)

¡Saludos!

**Comment by gmoran77** [comment]
Hola! 
A mi no me queda claro. Yo quiero saber de donde obtener el valor de los parámetros, por ejemplo de CANSANCIO% o PROB_MDB, etc. En el fondo todos los parametros que se encuentran en el enunciado con texto azul, no veo claro donde encontrar el valor de ellos.
Gracias!

**Comment by Benjeeeh** [comment]
@gmoran77 
Hola!
Son valores que tu debes definir! Todos los valores que salgan en azul (y que ya no tengan un valor definido, es decir, que no sean constantes) como los que mencionas tu, deben ser definidos por ti. Por ejemplo, si defines a PROB_MDB como 50, entonces el Mago de Batalla tiene un 50% de activar su ataque especial.

¿Quedó claro?

**Comment by Joomkin** [comment]
@Benjeeeh 
Hola! Lo que no me quedo del todo claro es el tema de los nombres de los parametros. ¿Los nombramos como salen, es decir, "CANSANCIO" queda tal cual, o debemos ponerles otros nombres? 
Gracias!

**Comment by Benjeeeh** [comment]
@Joomkin 
Si, los nombres que menciona el enunciado deben mantenerse, solo debes fijar los valores.

**Comment by agustinvaldesz** [comment]
Hola! a mi no me quedo muy claro, los valores que ya estan definidos, como vida maxima, para asignarles su valor hay que hacer un random por ejemplo entre 0 y 100, o siempre parten en el valor mas alto?
