### ISSUE TITLE
En que Hacer diagrama de clase

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#169]
Tal como dice el titulo, me pregunto con que aplicación hacen el diagrama de clase, ya que lo tengo escrito y me falta traspasarlo a computador

**Comment by mfanselmo1** [comment]
Hola! 
Puedes usar draw.io

**Comment by Jj1martinez** [comment]
Sólo se puede a computador?

**Comment by Cschavez** [comment]
Hola! una duda sobre el diagrama: creo haber entendido que en los atributos de una clase van solo los que se colocan en el __init__(self, *atributos), quisiera saber si esto en verdad es así o tambien tengo que considerar los atributos internos que haya definido. 
Muchas gracias !
