### ISSUE TITLE
Que tanto hay que comentar la tarea?

### ISSUE THREAD

**Issue by JavierOrmazabal** [IIC2233/Syllabus#169]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Que tantos comentarios se consideran correctos a lo largo del código para explicarlo, no se si debo comentar cada linea de mi codigo, o solo explicar a grandes rasgos cada funcion. Tampoco comprendo si debo hacer esto en todos los archivos del codigo ni si existen algunas "reglas" para comentar.

**Comment by roahoki** [comment]
Hola @JavierOrmazabal! En la práctica, como mínimo te pedimos que completes con tu información la suerte de template que les dejamos del README.md. Por otro lado, una muy buena práctica es comentar tu código y para responder a tu duda, la verdad es que depende de ti. Lo más general es dejar un comentario de lo que logra hacer alguna función que implementaste y/o explicar algún flujo de código que quizás no sea tan fácil de entender para un tercero. De todas maneras, repito, comentar tu código es una excelente práctica que puedes emplear. Nosotros como equipo docente, particularmente te pedimos que expliques tu tarea en el README.md y que te apegues a las reglas de la tarea. Cualquier otra duda, por favor responde esta issue 🐈

**Comment by roahoki** [comment]
Complementando lo anterior, te recomiendo que le eches una mirada a esto: [Comments in code: best practices and mistakes to avoid](uhttps://swimm.io/learn/code-collaboration/comments-in-code-best-practices-and-mistakes-to-avoid#:~:text=A%20good%20best%20practice%20to,the%20intent%20of%20the%20code.rl)

**Comment by JavierOrmazabal** [comment]
> Complementando lo anterior, te recomiendo que le eches una mirada a esto: Comments in code: best practices and mistakes to avoid
Donde veo eso?

**Comment by roahoki** [comment]
arreglé el comentario, el link no habia cargado 🙃

**Comment by Segismundios** [comment]
Hola, no sé si se permite agarrarse de una pregunta jajaja, pero agarrándome, me pregunto qué tanto hay que explicar el código. Yo explicité qué ejecutar y qué archivos deben estar en la carpeta, pero no expliqué mi código más allá de los comentarios que hice en el mismo código. Tampoco expliqué partes que consideré autoexplicativas. Eso es insuficiente?

**Comment by roahoki** [comment]
hola @Segismundios , lo que ya escribiste califica para ser suficiente. Es importante recordar que más _no_ es mejor, asi que basta con que el código se entienda con la cantidad de comentarios adecuada (considerando que un tercero lo leerá) como para que esté bien :)

**Comment by Segismundios** [comment]
Valee, muchas gracias!

**Comment by roahoki** [comment]
Para eso estamos :)
