### ISSUE TITLE
Tiempo en programa 

### ISSUE THREAD

**Issue by Mariana-Ortega-del-Rio** [IIC2233/Syllabus#169]
Hola! No entiendo cómo debemos tratar la variable tiempo en nuestro programa. Entiendo que las bases de datos solo incluyen información del "pasado" y hay que cargarlas en el programa, pero cuando un usuario haga una nueva orden al correr el programa ¿qué fecha se le debe poner en date_created? ¿Debe ser la fecha actual de hoy día por ejemplo 26/08/2017? ¿o se le debe preguntar la fecha al usuario?
Gracias de antemano!

**Comment by cilopez** [comment]
No esta explicito en el enunciado como se debe hacer por lo que puedes modelarlo como quieras, si quieres que el programa corra en el tiempo actual existen librerías que pueden ayudarte.

Por otra parte si quieres que el usuario ingrese la fecha **debes**  manejar que ingrese fechas correctas y que estén después del ultimo dato de la base., para que todo tenga sentido ¡Saludos!
