### ISSUE TITLE
Linter VSCode

### ISSUE THREAD

**Issue by vcrb18** [IIC2233/syllabus#17]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

[En el tema de la configuración de VSCode, en la Wiki del curso aparece que hay que seleccionar como Linter "pycodestyle", en cambio en el video sale que ocupemos el flake8. ]

[**¿Cuál Linter debemos ocupar entonces? ¿pycodestyle o flake8?**]

**Comment by pedroriosg** [comment]
Hola @vcrb18 ✌️ !

Un `linter` es una herramienta que te ayudará a seguir la **guía de estilo** de tu código fuente. Para este curso, se usará la guía de estilo `PEP8` explicada en los contenidos; y el `linter` en VSCode que te ayudará es el que sale en la Wiki del curso `pycodestyle`.

De todas maneras, el `linter` `flake8` también sigue normas de `PEP8`, aunque algunas como los espacios a cada lado entre operadores, no los corrige.

Espero haberte ayudado!
