### ISSUE TITLE
Error de falta de interpretador de python en vscode

### ISSUE THREAD

**Issue by ChupeteBecker** [IIC2233/Syllabus#17]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

Haciendo el ejericio propuesto 3 de la semana 01, me tiraba un error (abajo a la derecha)  de que no tenia seleccionado un interpretador de python en vscode y al hacer click para seleccionar uno, me salia (en la barra de busqueda de vsc) que no habian interpretadores de python encontrados, al hacer click en ese mensaje me llevo a la microsoft store para instalar uno, y termine instalando un python 3.11.4 pero en la consola de ubuntu me salia el python 3.10.12, no se si hice algo mal o si con ese interpretador que descargue esta listo y no me deberia preocupar.

**Comment by Hernan4444** [comment]
Hola @ChupeteBecker 

Para el tema de los contenidos, no habrá problema, porque esos son solo para que puedas practicar. Lo importante (y que veremos mañana en la experiencia) es que cuando ejecutes tus códigos de tareas y actividades, uses python 3.10 y justamente mañana practicaremos todo eso con la terminal 😄 

Saludos!
