### ISSUE TITLE
Duda sobre utilizar funciones de AF1 en T0

### ISSUE THREAD

**Issue by rominaansaldo** [IIC2233/Syllabus#17]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Utilizar funciones de AF1 en T0 

Hola! Tengo la duda si es que se puede usar una función que sale en el archivo main.py de la actividad formativa 1 (por supuesto citando que viene de ahí) en la tarea 0.  Muchas gracias!

**Comment by benjaaguila** [comment]
Hola @rominaansaldo ! Sí, siempre puedes utilizar código externo de actividades, contenidos, buscando en Google siempre y cuando este referenciado.
