### ISSUE TITLE
Uso de deques como stacks en vez de listas.

### ISSUE THREAD

**Issue by Oisangui** [IIC2233/syllabus#17]
He estado pensando que quizás la estructura deque es mejor, o al menos igual de eficiente, para stacks que las listas, y en internet he encontrado que algunos prefieren deque para esta estructura, e.g., [link1](https://www.reddit.com/r/Python/comments/1wehgw/pythons_deque_is_the_stack_object_you_want_to_use/). Además la [documentación](https://docs.python.org/3.6/library/collections.html#collections.deque) oficial de python 3.6 habla del deque como la generalización de queues y *stacks*.

Aunque la documentación también habla de [listas](https://docs.python.org/3/tutorial/datastructures.html#using-lists-as-stacks) como stacks, Raymond Hettinger, un *core developer* de python  [dijo](https://stackoverflow.com/questions/23487307/python-deque-vs-list-performance-comparison) que el deque es efectivamente más rápido en el *long run* en operaciones de pop y append.

La pregunta es, ¿puedo implementar stacks como deques en vez de listas en una tarea o actividad sin que se reste puntaje?

**Comment by Arcoirisky** [comment]
¡Claro que puedes hacerlo!

A menos que se te indique lo contrario, puedes usar cualquier estructura de datos que desees :D
