### ISSUE TITLE
Duda con guardar la partida y salir de la partida con/sin guardar

### ISSUE THREAD

**Issue by BelenMadariaga** [IIC2233/syllabus#17]
Holaaaa! Quisiera saber cuál es la diferencia entre las tres: guardar la partida y salir de la partida con o sin guardar. 

En el caso de guardar la partida con o sin salir (lo que sería un sub-menú(? en base a lo dicho en la issue #16), ¿se le dan la opciones al jugador de indicar el nombre de usuario o volver atrás?, si efectivamente se guardó la partida, pero sin salir de ella, ¿se vuelve al menú de juego (sería como guardar el progreso)? Y en cuanto a salir de la partida con/sin guardar, luego de hacer cualquiera de las dos, ¿se vuelve al menú de inicio?

**Comment by KnowYourselves** [comment]
Hola @BelenMadariaga!

Contestaré tus dudas en orden:

1. Si se guarda (con o sin salir) se utiliza el nombre que el usuario ingresó al iniciar la partida.
2. Si se guarda sin salir la partida continua normalmente.
3. Si se sale de la partida queda a tu criterio si volver al menú de inicio o cerrar el programa, lo que te acomode más.

Espero haberte ayudado!

**Comment by BelenMadariaga** [comment]
Gracias 💃
