### ISSUE TITLE
Abstract base class

### ISSUE THREAD

**Issue by Mariana-Ortega-del-Rio** [IIC2233/Syllabus#17]
Las clases abstractas pueden tener atributos abstractos? Estaba buscando ejemplos y siempre importan abstractmethod y ocupan decoradores, pero no veo que le coloquen atributos a esa clase. Más que nada le ponen pass a esos métodos abstractos, entonces no entiendo bien la utilidad más allá de no poder instanciar esa clase. Agradecería si pudieran explicarme esto un poco más :) 

Gracias de antemano!

**Comment by rihanuch** [comment]
Hola!!
Sí, si pueden. Al final la clase abstracta es para "modelar" una idea 💡 y evitar que se instancie esta idea (aunque sea por error 🚫 ). Por ejemplo digamos que quieres modelar San Joaquín (Tarea 4 2017-2 💻 ), tu no quieres que existan sólo "personas", sino que quieres que existan miembros de la universidad, ya que una persona 👩  no tendría sentido para la modelación (porque no cumpliría un rol dentro de esta )

```python
class Persona(metaclass=ABCMeta):
    """Se hace un generico del cual todos heredarán"""

    def __init__(self, nombre, apellido, edad, fecha, replica=False):
        self.nombre = nombre
        self.apellido = apellido
        self.edad = int(edad)

    @property
    def nombre_entero(self):
        """Cada persona tiene un nombre entero que es su nombre + apellido"""
        return self.nombre + " " + self.apellido


class MiembroUC(Persona, metaclass=ABCMeta):
    """Hereda de clase abstracta Persona"""

    def __init__(self, preferencias_almuerzo, preferencias_snack, llegada,
                 hora_comer, ir_a_comprar, paciencia, snacks, *args,
                 **kwargs):
        super().__init__(*args, **kwargs)

        self.llegada = f_llegada
        self.hora_comer = f_hora_comer
        self.ir_a_comprar = f_ir_a_comprar
        self.paciencia = f_paciencia
        self.hora_snacks = f_snacks

        self.hora_llegada_sj = self.f_llegada()
```

Tu no quieres que se instacie una ```Persona``` cualquiera, sino que quieres que exista un ```MiembroUC```, por lo con el uso de ```ABCMeta``` ⬆️  vas a estar evitando esto, ya que sino el sistema se podría poblar con personas cualquiera y esa no es la idea 💀 .

Al fin y al cabo sirve para organizarse mejor y tener un código más limpio 🌟  y lógico dentro del marco y contexto en que se esté programando 😄

**Comment by Mariana-Ortega-del-Rio** [comment]
Muchas gracias!! La clase abstracta puede tener métodos no abstractos? Onda un repr o str?

**Comment by Mariana-Ortega-del-Rio** [comment]
Muchas gracias!!!
