### ISSUE TITLE
README Repositorio Personal

### ISSUE THREAD

**Issue by borquezmartin** [IIC2233/syllabus#17]
Holaa, respecto al README en el repositorio personal, ¿es posible modificarlo libremente?
pregunto esto porque consideraba usarlo para adjuntar links de utilidad que podría usar a lo largo del curso.

**Comment by igbasly** [comment]
Hola @borquezmartin :v:

Efectivamente, eres libre de modificar el README principal de tu repositorio para lo que estimes conveniente. Solo tu y el cuerpo docente  tiene acceso a este contenido.
Como dato :bulb:, este tipo de cambio es en los README hazlos desde un editor en tu computador y luego súbelos, en lo posible no los edites directamente en la página de GitHub, ya que puede generar conflictos más adelante.

Saludos 🙌
