### ISSUE TITLE
Diagrama de Clases: Diccionarios

### ISSUE THREAD

**Issue by glbello** [IIC2233/Syllabus#17]
Saludos, quería consultar respecto al diagrama de clases. En la materia del curso aparece:
![uml_composition](https://user-images.githubusercontent.com/13740193/29092348-0b272990-7c54-11e7-8dba-47971cafd70f.png)
Dentro de los atributos de SerieDeTiempo, está **observaciones: Observaciones[]**, aquí ¿se refiere a una lista de clases de Observacion?, de ser así, ¿Cómo debería ser en caso de un diccionario?, además creo que para un diccionario, es más complejo porque puede haber una infinidad de datos por el asunto de key y value... estoy un poco confundido

**Comment by sebacruzd** [comment]
Hola, exacto, se refiere a que es una lista.
Para un diccionario podría ser de la siguiente manera:
`+ observaciones: Observación{}` (siguiendo la manera de cómo de hizo con la lista)
o sino:
`+ observaciones: dict`

No siempre tiene que ser lo más detallado posible, ya que si entras en detalle para cada atributo terminaría siendo más enredoso que útil para entenderlo.

Hay distintas maneras de hacerlo, pero si queda claro que será un diccionario debería estar bien.

Acá hay un ejemplo que encontré en internet:
![image](https://user-images.githubusercontent.com/14894992/29093580-4cd9beee-7c58-11e7-9346-113d3cbba71f.png)
Si notas, en este ejemplo se aclaran las keys y tipos de values que tendrán los *values* del diccionario
