### ISSUE TITLE
Eliminar prograpost

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#17]
Buenas noches,respecto a la parte en la que te pide que crees una forma de eliminar un prograpost el usuario de que manera seleccionara el prograpost que desea eliminar , a esto me refiero a que lo hará por fecha o por el contenido , o yo puedo decidir de que manera seleccionara dicho prograpost?

**Comment by gatochico** [comment]
Hola! 
Queda a tu criterio ver como se selecciona el prograpost a eliminar. Sin embargo, te recomiendo usar una forma que asegure borrar **únicamente el post pedido, y ningun otro más.** Esto lo digo ya que un usuario podría crear dos posts en la misma fecha, o hacer dos posts con el mismo contenido, y necesitarás usar una forma que pueda diferenciar ambos posts y borrar el que el usuario realmente pide.

Cualquier duda quedamos atentos! :bird:

**Comment by RonaldoSosa** [comment]
Entendido, muchas gracias!
