### ISSUE TITLE
Versión requerida: x > 10 o x ≥ 10?

### ISSUE THREAD

**Issue by agucova** [IIC2233/Syllabus#17]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema
En la [wiki](https://iic2233.github.io/wiki/software) del curso dice:
> La versión de Python que usaremos en esta versión del curso será: 3.8.X, siendo X cualquier valor mayor a 10.

Sin embargo, Python 3.8.11, la única versión que cumple el criterio estricto (`x > 10`) no tiene un instalador disponible en [python.org](https://www.python.org/downloads/release/python-3811/), por lo que muchas personas estuvieron preguntando por Discord y WhatsApp si instalar la 3.8.10 o intentar instalar la 3.8.11 (disponible en pyenv, homebrew y algunos repos), especialmente dado que el video de instalación recomienda la 3.8.10.

**¿Podemos usar la 3.8.10?**

**Comment by 1862507J** [comment]
Hola!
Sí se puede usar la 3.8.10. De hecho, creo que es lo más recomendable

**Comment by agucova** [comment]
Gracias, eso resuelve mi duda.

Como una sugerencia, el script de setup_test no verifica la versión parche por lo que varias personas con versiones de Python menores a 3.8.10 no notaron la discrepancia. Esto se puede solucionar con:

```diff
30,31c30,31
<         major, minor, *_ = sys.version_info
<         if (major, minor) == (3, 8):
---
>         major, minor, patch, *_ = sys.version_info
>         if (major, minor) == (3, 8) and patch >= 10:
34c34
<             print('Versión de Python incorrecta, debes instalar la 3.8.X')
---
>             print('Versión de Python incorrecta, debes instalar la 3.8.X con x > 10.')
```
