### ISSUE TITLE
Orden de ejecución

### ISSUE THREAD

**Issue by maxfreymo** [IIC2233/Syllabus#170]
Cuando seleccionamos la opción "Pasar de día" ¿Cuál es el orden de ejecución de los acontecimientos? Por ejemplo:

1. Descubrir infección
2. Ejecutar acciones de la cola de prioridades (si es que existen).
3. La infección avanza dentro de país.
4. Las personas que deban morir, se mueren.
5. La infección se propaga entre países.
6. Progresa la cura.

Además ¿"El descubrimiento de la cura" ocurre instantáneamente cuando se descubre la infección?

**Comment by jorgeriesco** [comment]
Sale en el enunciado que hay un progreso de la cura diario. Eso se refiere a su elaboración o aproximacion a ser descubierta. En otras palabras no se descubre instantáneamente, sino que se comienza a elaborar a penas es descubierta la infección y luego se descubre.

**Comment by maxfreymo** [comment]
¿@jorgeriesco eso quiere decir que cuándo el progreso de la cura llegue a 100% es descubierta?

**Comment by arturodelreal** [comment]
@maxfreymo Efectivamente cuando llega a 100% es descubierta.
El orden de los sucesos queda a tu criterio, recuerda especificarlo en el README
