### ISSUE TITLE
Método atacar de la clase Combatiente

### ISSUE THREAD

**Issue by ignanuyens** [IIC2233/Syllabus#170]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

En el enunciado en el apartado 4.2.1 Tipos de combatientes se especifica cómo atacaran los diferentes de combatientes, dependiendo si activa o no sus poderes, sin embargo me quedan algunas dudas al respecto.
En Mago, cuando ataca con poder, sólo se ignora un red_mag% de la defensa del enemigo en el ataque, o a parte ¿se debe cambiar el valor de la defensa del enemigo (el stat) de forma permanente?
En Paladín, ataca con prob_pal% de probabilidad de activar sus poderes de caballero según enunciado. Pero en el caso de que no active esos poderes, ¿debe activar los poderes de guerrero? 
En Mago de Batalla sucede algo parecido al paladín, en caso que no active sus poderes con prob_MDB% al atacar ¿cómo ataca al enemigo?

Muchas gracias de antemano.

**Comment by tebi01** [comment]
Hola!

Respecto al efecto del ataque en el enemigo, es correcto lo primero que mencionas: El poder del mago de ignorar stats enemigas se manifiesta únicamente durante ese ataque. No es necesario modificar el atributo de defensa
Por otro lado, para tres clases que nombraste, en caso de no activar su poder, atacarán como Guerreros.

Espero que te haya sido útil :)

**Comment by lucianopkfreerunning** [comment]
En el caso del caballero también es momentáneo la disminución del poder del enemigo ?

**Comment by tebi01** [comment]
Hola!
Tengo entendido que al reducir el ```poder``` del enemigo, se refiere a modificar su atributo. Por lo tanto, se asume que es un cambio permanente, dado que no especifica que será por el próximo turno o momento en particular.

De todas maneras, puedes especificar la interpretación que tomaste en tu archivo ```README.md```.

Espero haberte ayudado!
