### ISSUE TITLE
widgets en clases

### ISSUE THREAD

**Issue by santiago3c** [IIC2233/Syllabus#170]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

Hola, que no entiendo por qué hay que pasarle como parámetro self a un widget como por ejemplo QLabel, porque he visto códigos que crean widgets fuera de clases y no se les pasa la instancia de la ventana. No entiendo cuándo se tiene que hacer y cuándo no, si alguien me puede explicar por favor

[Describe tu duda de manera detallada, explicando los contenidos en cuestión y ojalá colocando código o un caso de uso de ejemplo]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by santiago3c** [comment]
o por qué  self.grilla = QGridLayout() no recibe self

**Comment by fvidalf** [comment]
Hola @santiago3c!

En general, cuando le pasas la ventana al widget, lo que estás haciendo es *settear* inmediatamente su widget padre (*parent*). Esto es usualmente lo que queremos cuando creamos cosas como labels, o buttons, porque queremos agregarlos a la ventana en la que estamos trabajando. De lo contrario, no serían visibles.

Para los QLayouts sucede lo mismo. Si no tienen una referencia a la ventana, no son visibles, solo que en este caso, solemos usar .setLayout, en lugar de entregar un self (a pesar de que también puede hacerse de esa forma).

```python
# Esto
self.layout = QVBoxLayout()
self.setLayout(self.layout)

# Tiene el mismo resultado que
self.layout = QVBoxLayout(self)

# Como esto
self.label = QLabel("Hola!", self)

# Tiene el mismo resultado que
self.label = QLabel("Hola!")
self.label.setParent(self)
```

En definitiva, todo depende de como las cosas *settean* su parent. Esto puede hacerse de varias formas, como entregando inmediatamente un padre con *self*, o después de haberlo creado con el método .setParent(*parent*). Algunas de esas formas suceden sin que nos demos cuenta: Por ejemplo, al agregar un widget a un layout que ya tiene un QWidget parent, automáticamente se le asigna el mismo parent a ese widget.

Y así existen hartas reglas específicas 😅 , pero puedes quedarte con que, si quieres que algo se vea en tu ventana, en *algún momento*, se le debe asignar un parent, por cualquier método (al crearlo, usando .setParent, incluyendolo en un QLayout, como hijo de otro widget que ya tiene de parent a la ventana, etc etc).

Espero no haberte confundido mucho :D y si tiene más dudas sobre esto, puedes responder esta misma issue. 

Saludos ✌🏽

**Comment by santiago3c** [comment]
Clarísimo, gracias
