### ISSUE TITLE
Propuesta futuras tareas

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#170]
Hola, 

Abro esta Issue, para dar una propuesta sobre las futuras tareas, y esta es que la materia de los talleres de materia adicional (realizados durante las semanas de las tareas) sean subidos a la par que son subidas las tareas. Esto debido a que muchos (al menos así fue mi caso) empezamos la tarea con mucha anticipación, y pese a que aplicar los contenidos nuevos hubiese sido de mucha utilidad en la tarea, esto se hacía un poco infactible de hacer dado que de hacerlo tendríamos que haber cambiado toda la estructura de la tarea, no así si hubiésemos leído el material adicional antes de programar (además no creo que desincentive la asistencia a los talleres, ya que a fin de cuentas, actualmente, la diferencia de tiempo entre los que asisten y los que no sobre el acceso al material es mínimo).

Dejo esta propuesta para que lo vean entre los profesores/ayudantes y vean la factibilidad de implementar esto o no.

Saludos

**Comment by iqacevedo** [comment]
Hola,

Muchas gracias por tu propuesta, la estamos evaluando junto a los profesores. Como esta es la primera versión del curso con talleres, estamos evaluando como mejorarlos.

¡Saludos!
