### ISSUE TITLE
repetir por disparo especial

### ISSUE THREAD

**Issue by eliasbruchfeld** [IIC2233/syllabus#170]
Hola! Si es que tiro una bomba especial y encuentro 2 barcos de una, despues tengo que repetir disparo 2 veces? o solo una, como si hubiese encontrado un barco

Obviamente la misma pregunta si es que encuentro 3 barcos de un tiro, etc.

**Comment by jitorralba** [comment]
Hola @eliasbruchfeld!
Como no se detalla en el enunciado eso queda a tu criterio, pero lo lógico en terminos jugabilísticos (y creo que lo más fácil de hacer) sería que tuviera sólo 1 disparo extra independiente de cuantos barcos hubiese impactado.
Avísame si te quedan dudas.
Éxito en tu tarea!

**Comment by YehudaGurovich** [comment]
Puedo hacer que solamente repita el tiro si en la coordenada que se ingresó había un barco? o tiene que ser que necesariamente si encuentra un barco en cualquiera de las posiciones de la bomba especial repite el turno.

**Comment by jitorralba** [comment]
@YehudaGurovich disculpa la demora
Debería ser en caso de que impacte en cualquiera de las coordenadas, de lo contrario no sería consistente con el flujo del programa que se detalla en el enunciado
