### ISSUE TITLE
Duda ejerc prop 1.1 s-03 

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#170]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, no quede muy seguro del diagrama de clases que hice para este ejercicio, por lo que agradecería cualquier feedback ya sea de errores en ella o de mejores formas para dibujarlo.

![WhatsApp Image 2021-04-02 at 12 40 00](https://user-images.githubusercontent.com/80859173/113430841-402b3500-93b1-11eb-91c9-c720a00abf17.jpeg)

Desde ya gracias. Buena semana santa!

**Comment by tqmbanados** [comment]
Hola! En general se ve bien, sin embargo tienes que marcar con mejor claridad las herencias. Mirando el diagrama, sin saberlo, podría interpretar que ReyDelNorte hereda de GuardiaDeLaNoche. Está bien que unes las flechas y líneas (se ve muy confuso cuando hay demasiadas), pero la persona que ve el diagrama tiene que tener total claridad de donde parten y donde comienzan. Espero que entiendas dónde está la confusión!

**Comment by JuanpaBC** [comment]
Vale muchas gracias!
