### ISSUE TITLE
Entrega de código, respecto a forma de leer archivos.

### ISSUE THREAD

**Issue by 18638333** [IIC2233/syllabus#170]
Para leer los archivos en vsc, me es necesario poner la ruta completa del directorio, ya que cuando pongo solamente el nombre del archivo.csv, no me funciona.
Para subir el código, lo dejo como me funciona a mi, o le pongo solo el nombre del archivo.csv?

**Comment by DCCollao** [comment]
Hola @18638333

Tu pregunta está enfocada a si debes utilizar [_path_](https://github.com/IIC2233/contenidos/blob/master/semana-00/3-paths.ipynb) relativos o absolutos.

Si es que llegases a entregar tu tarea con _path_ absoluto, no correría en el computador del ayudante que te corrija, pues la carpeta `C:/tu_usuario/desktop/progra/tu_repo/Tareas/t00` no existiría, y caería en un error. Esto significará un descuento, pero el error sería arreglado y tu tarea corregida de todas maneras.

La forma correcta de utilizar paths es haciéndolos relativos, pues asegura que tu tarea correrá siempre que la ubicación de los archivos (respecto al `.py` que se debe ejecutar) sea la misma que en el momento en que escribiste el código.
