### ISSUE TITLE
Duda sobre la entidad objetos

### ISSUE THREAD

**Issue by mvveram** [IIC2233/Syllabus#170]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!

Existe alguna diferencia entre el `costo`, el cual es la energía de intentar de crear el objeto, y `ENERGIA_CREAR_OBJETO`, que es lo que gasta al crearlo. Me queda la duda de que el primero sea antes de crearlo y la otra sea después de crearlo o  que en realidad son lo mismo.

Muchas gracias de antemano

**Comment by kolk3y** [comment]
https://github.com/IIC2233/Syllabus/issues/159#issuecomment-1242759429

**Comment by mvveram** [comment]
Hola, si vi esa issue, pero mi pregunta es acerca del atributo `costo` de Objetos y la `ENERGIA_CREAR_OBJETO`, porque en esa issue preguntaban si era lo mismo que cambiar objeto por baya y esa no es mi duda.

Muchas gracias de antemano

**Comment by PSepulvedaS** [comment]
Hola!

Al final corresponde a lo mismo, el costo es la energía que se le debe quitar al entrenador al crear el objeto.
