### ISSUE TITLE
Creación de mercados y currencies y duda trader

### ISSUE THREAD

**Issue by Mariana-Ortega-del-Rio** [IIC2233/Syllabus#170]
Tengo una pregunta sobre la creación de mercados y currencies. Leí en otra issue que se podían crear nuevas currencies y las del archivo Currencies.csv eran solo un ejemplo. Entonces, ¿un usuario puede llegar y "crear" un nuevo mercado al querer ingresar a un mercado que todavía no existe? ¿Y de esta forma se crean además las dos nuevas currencies(en caso de no existir)? ¿O el programa debe ofrecer crear nuevos mercados?

Sobre los trades el enunciado dice que Trader "pueden acceder a un registro de las orders realizadas en los últimos 7 días". ¿Esto se refiere a las orders de los mercados en los que participa ese usuario o las orders de TODOS los mercados de los últimos 7 días?

**Comment by fnquinteros** [comment]
Tus dudas ya han sido contestadas en otras issues :/ te sugiero que busques bien, incluyendo las que estén cerradas. 

Saludos!
