### ISSUE TITLE
Cola de prioridades

### ISSUE THREAD

**Issue by maxfreymo** [IIC2233/Syllabus#171]
Una vez ejecutadas las 3 acciones con mayor prioridad ¿La cola de prioridades se borra para comenzar un nuevo día cierto?

**Comment by arturodelreal** [comment]
@maxfreymo Puedes borrarla y crear una nueva, o puedes modificar la original.

**Comment by frvalenzuela** [comment]
¿Es necesario que se cree una estructura de datos que sea una cola, o podemos ocupar lista ligadas que asemejen una cola?

**Comment by monicabelen** [comment]
¿Cuál es el criterio para escoger una acción sobre otra si tienen la misma prioridad?

**Comment by stephichau** [comment]
@monicabelen lo decides tú :).

**Comment by hanavarrete** [comment]
@frvalenzuela  La idea es que sea una cola. Saludos!
