### ISSUE TITLE
Duda con los ataques de las clases hibridas

### ISSUE THREAD

**Issue by yonieeh** [IIC2233/Syllabus#171]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Cuando las clases hibridas atacan con sus poderes de sus clases individuales, por ejemplo, cuando el mago de batalla ataca como mago, **los efectos negativos de esos ataques igualmente aplican?** 

Por ejemplo, si el mago de batalla ataca como mago, debe igualmente disminuir su resistencia y agilidad? O esto solo debe ocurrir con las clases simples

**Comment by Dominique236** [comment]
Hola! Tal como mencionas si se deben aplicar todos los efectos de la clase original. Para esto te recomiendo aprovechar los contenidos de clase. 
Cuéntame si esto resuelve tu duda y suerte en la tarea! ☘️

**Comment by elneitans** [comment]
Bueno saberlo, ya que al no mencionarse eso en el enunciado, uno creería que solamente los efectos a las stats mencionadas para esta clase evolucionada son las que actúan, y no los defectos de las clases involucionadas. Es decir que en el caso de Mago de Batalla, solamente hay que hacer "Luego de cada ataque, su Agilidad disminuye en un CANSANCIO %, pero su defensa aumenta en un DEF_MDB %", y no "Mago se fatiga, disminuyendo su Resistencia y su Agilidad en un CANSANCIO % cada una".

**Comment by yonieeh** [comment]
@Dominique236 si los efectos de las clases individuales también aplican, eso significaría que, por ejemplo, cuando el mago de batalla ataca como mago, **su agilidad se disminuiría dos veces**, una por el ataque como mago y una por el efecto de los magos de batalla. Teniendo en cuenta que ambas veces la agilidad se reduce en CANSANCIO%, esta doble disminución debe ser **multiplicativa o aditiva?** O esto debe ser a criterio de nosotros?

Y tengo la misma duda en los casos donde hay una disminución y luego un aumento, como en el caso del caballero arcano. Cuando el caballero arcano ataca como mago, su agilidad disminuiria durante ese ataque por un factor de CANSANCIO%, y luego por efecto del caballero arcano, su agilidad aumenta por un factor de AUM_CAR%. Cuando ocurra esto, **debo primero disminuir y luego aumentar sobre el valor ya disminuido? o debería restar los porcentajes y aplicar la diferencia sobre el valor?** 

Muchas gracias :)

**Comment by Drpinto1** [comment]
¡Hola @elneitans!

Uno de los objetivos principales de la tarea es modelar y resolver un problema complejo, lo que incluye tomar decisiones de diseño. Este tipo de cosas no se mencionan en el enunciado precisamente para que se hagan estas preguntas y puedan tomar decisiones de acuerdo a su criterio, siguiendo las instrucciones del enunciado.

Particularmente para los combatientes, si comparas las descripciones de del `paladín` y `mago de batalla` con la del `caballero arcano`, en la primera hablamos de "activar sus poderes", mientras que en la segunda decimos específicamente "atacar como X".
Tomando el enunciado literalmente, podrías considerar que para los primeros dos casos no es necesario aplicar los efectos adicionales, es decir, estarías asumiendo que los efectos adicionales no son parte de los poderes o podrías considerar que todos los efectos son parte del ataque. Por el contrario, para el `caballero arcano` dice específicamente "atacar como Caballero/Mago", lo que deja menos libertad para decisiones.

En la respuesta de @Dominique236 se está recomendando aplicar todos los efectos, pues la programación de esto es más simple y aplica para todos los casos (según enunciado), mientras que si quieres asumir algo distinto deberías diferenciar entre las 3 clases "híbridas", sin embargo esto no significa que esta es la única modelación válida, si no que es más una recomendación general que sirve para los 3 casos.

Espero que esto aclaré las dudas ya preguntadas y la razón por la que redactamos el enunciado de la forma que lo hicimos.

¡Saludos!

**Comment by Drpinto1** [comment]
¡Hola @yonieeh!

Disculpa la demora, respondí el otro comentario y se me pasó responderte directamente también. 

Respecto a la doble reducción, queda a su criterio cómo la realizan (ya sea de forma aditiva o multiplicativa o si consideran que no tiene sentido, la aplican una sola vez, por ejemplo). Esto mismo aplicaría para los aumentos, mientras apliques los efectos de manera razonable y todos los efectos sean aplicados, será considerado correcto.

¡Saludos!

**Comment by Vicente1824** [comment]
Holi, una duda sobre más o menos lo mismo. En la clase de Caballero Arcano, el Caballero Arcano podría atacar dos veces? Una vez como Caballero y otra como Mago? O si ataca como Caballero luego no puede volver a atacar?
Si el caso es el último, entonces, si no alcanza ni la posibilidad de atacar como caballero ni como mago, luego no haría ningún daño?

**Comment by josefinaabbott** [comment]
Hola! En la clase de Paladín, dice que puede activar sus poderes de caballero si se cumple con la probabilidad establecida, en caso contrario tenemos que asumir que va a atacar de igual manera que Guerrero?

**Comment by coniverav** [comment]
Misma duda, asumo que si no se activan los poderes de Caballero/Mago en Paladín/Mago de batalla respectivamente, **asumo que atacan como la otra clase que heredan** (Guerrero/Guerrero)? Es decir, la misma dualidad de Caballero Arcano.

Una segunda duda sobre esto mismo, es que para el caso del Caballero Arcano, se puso en formato azul y mayúsculas el parámetro PROB_CAR y 1-PROB_CAR. Dado esto, **solo debo definir PROB_CAR en el archivo de parámetros, no?** dado que el otro solo es el complemento.

**Comment by Dominique236** [comment]
Hola @Vicente1824 @josefinaabbott @coniverav !

Disculpen la demora, dado que los tres tienen en esencia la misma duda, aprovecho de responderles a la vez.
La clase Caballero Arcano tiene PROB_CAR % de probabilidades de atacar como un Caballero, si esta probabilidad no se cumple, entonces atacará como Mago (tal como dice el enunciado con 100-PROB_CAR % de probabilidad). En otras palabras, si no se cumple una probabilidad, entonces se cumple la otra. Por lo tanto, no hay forma de que no ataque o no haga ningún daño.
Lo mismo ocurre con las clases Paladín y Mago de Batalla.

Sobre definir 1-PROB_CAR en el archivo de parámetros, tal como mencionas, no es necesario.

Ojalá esto haya resuelto sus dudas :)

**Comment by Daniel-M-P** [comment]
En resumen después de todo lo leído, entonces todos los combatientes si o si generean cierto daño, si no es activando sus poderes es como guerrero (exceptuando el caso del caballero arcano). Y las clases que heredan es necesario que apliquen los efectos negativos de atacar como mago, caballero o guerrero? o eso es decisión de diseño y yo podría separar la activación de poderes? y de esa manera los gatos evolucionados no tendrían los efectos negativos al atacar de sus clases padres.

**Comment by Daniel-M-P** [comment]
Porque por lo menos para el Paladín y Mago de Batalla habla sobre activar poderes, entonces sería valido decidir solo activar los poderes y de esa manera no tener los efectos negativos de atacar del mago ni el caballero?

**Comment by Dominique236** [comment]
Hola @Daniel-M-P !
Todo lo que mencionas fue resuelto mas arriba por @Drpinto1 , te recomiendo volver a leer su respuesta. 
Sin embargo, en resumen se dice que para el caso de Paladín y Mago de batalla, tomando el enunciado literalmente, podrías considerar que no es necesario aplicar los efectos adicionales, es decir, estarías asumiendo que los efectos adicionales no son parte de los poderes o podrías considerar que todos los efectos son parte del ataque. Por el contrario, para el Caballero Arcano dice específicamente "atacar como Caballero/Mago", lo que deja menos libertad para decisiones. 
Se hace la recomendación de aplicar todos los efectos, pues la programación de esto es más simple y aplica para todos los casos (según enunciado).
