### ISSUE TITLE
Choque entre aliens

### ISSUE THREAD

**Issue by nkantorn** [IIC2233/Syllabus#171]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!! Tengo un duda sobre qué pasa cuando chocan dos aliens. En el enunciado no se especifica nada,  así que asumo que no pasa nada, pero de todas formas quería saber si es necesario hacer que reboten entre ellos en caso de chocar.

Muchas gracias!!

**Comment by nzamorano** [comment]
Hola @nkantorn, como tu dices en el enunciado no se especifica porque no debe pasar nada, solo debes preocuparte de las colisiones con los bordes 😉.
