### ISSUE TITLE
Error encontrado en código base de ejerc prop 1.1 s-03 (GoT)

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#171]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola, me parece haber encontrado un error en el código base de este ejercicio en lo respectivo a la definición de los atributos de todas las clases que son subclases de otras, pues en ninguna de ellas se aplica el método super( ) para implementar los métodos \__init__  de sus respectivas superclases, de manera que no heredan los atributos de ellas.

**Comment by pedroriosg** [comment]
Hola @JuanpaBC ✌️ 

Tienes razón, no está el `super()` en las subclases del ejercicio. Sin embargo, recuerda que el objetivo de este, es realizar un **diagrama de clases**, para ello no necesitas que el código funcione, sino solo mirar y concluir qué tipo de relaciones hay entre las clases.

Espero haberte ayudado! Saludos!

**Comment by JuanpaBC** [comment]
Vale!
