### ISSUE TITLE
Duda con distribución de puntajes

### ISSUE THREAD

**Issue by Cristobal-Hevia** [IIC2233/Syllabus#171]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
En la distribuicion de puntajes descuentas puntos por "CAMBIOS DE LINEAS" y no estoy seguro que quiere decir si me lo pueden explicar porfavor.

**Comment by R3Y3X** [comment]
hola, espero que estés bien , el "CAMBIO DE LINEAS" es una opción en la cual luego que tengas tu nota, se te permite reescribir líneas en tu código, si deseas acceder a esta opción se te darán mas detalles de cuantas líneas puedes cambiar, principalmente se recurre a esta opción porque no funciona tu tarea correctamente, debido a que los archivos no se leen, usaste un built-in o librería prohibida o ejemplo: hay un error donde una función que recibe un int se le entrega un str tirando error. En caso de que aun quedes con dudas hazmelo saber. Exito en tu tarea ⚡⚡
