### ISSUE TITLE
Guardado de minerales y deurario actual

### ISSUE THREAD

**Issue by Regenschrim** [IIC2233/Syllabus#171]
Me entro al duda de como guardar la cantidad de materiales que tiene actualmente cada planeta, ya que en los archivos no hay una columna que represente eso. ¿Podemos agregas columnas a los archivos o es mejor que usemos los totales de cada galaxia (de minerales y deuterio) y los repartamos de forma equitativa?

**Comment by Hernan4444** [comment]
Creo que aquí respondo tu duda #73 

Saludos ✌️

**Comment by Regenschrim** [comment]
Ah si, ahi mismo esta jaja no la vi porque no revisé las cerradas :P Gracias!
