### ISSUE TITLE
Problema con el calendario

### ISSUE THREAD

**Issue by felipecs13** [IIC2233/syllabus#171]
Viendo la wiki del curso, no puedo acceder al calendario del curso: El error que aparece es el siguiente: "La página sso.uc.cl ha rechazado la conexión." Es error de mi conexión o un problema en la wiki?

**Comment by entamburini** [comment]
Hola!,

De ninguno de los dos, lo que pasa es que si no estás con la sesión UC iniciada, no podrás ver el calendario. Si crees que estás con la sesión iniciada, prueba con una pestaña de incógnito e inicia sesión, después me dices si se ve :D 

Saludos!

**Comment by felipecs13** [comment]
Solucionado, mucha gracias.
