### ISSUE TITLE
ARCHIVO "user.csv" Error? 

### ISSUE THREAD

**Issue by martin412** [IIC2233/Syllabus#171]
en el archivo users.csv en las orders_id de un usuario "Isaac" hay una fecha "01-01-1900" Que significa? o es un error?

**Comment by egromero** [comment]
Holaa, Puedes correr el script nuevamente y si sale alguna fecha de ese estilo, tu escoges como abordarlo (detalla en el readme). De todas maneras tranquilo, porque cuando corrijamos, usaremos un archivo que tendrá fechas entre rangos aceptables!

Saludos

**Comment by martin412** [comment]
<img width="336" alt="sin titulo" src="https://user-images.githubusercontent.com/30805158/29745242-ec588ae0-8a8b-11e7-9766-c611c304af8d.png">
Me refiero a esto

**Comment by egromero** [comment]
Al parecer es una interpretación que está haciendo Excel (o el programa que ocupaste para abrir el csv), trata de hacer print linea por linea con python, si sale correcto ahí, esta todo bien.

Suerte!

**Comment by martin412** [comment]
Si sale correcto en cada caso, gracias!
