### ISSUE TITLE
Cambio de tipo arena

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2233/Syllabus#171]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En la tarea existen dos métodos por los que se puede cambiar de tipo de arena, uno es mediante un tesoro y otro es mediante un evento. Ademas en el enunciado se dice justo debajo de la explicacion de los eventos que `Para cambiar de una arena a otra, se debe seleccionar de manera aleatoria cualquiera de las arenas del archivo arenas.csv filtrando las que son del tipo de arena correspondiente.` Mi pregunta es **¿Lo que cite solo aplica para los eventos o tambien para los tesoros?**, mas especificamente, los tesoros solo cambian el tipo de arena manteniendo todo el resto de atributos como el nombre y la dureza o tambien cambian por completo la arena con una aleatoria?

**Comment by Benjeeeh** [comment]
Hola!
Como en los Tesoros no se menciona específicamente si debe ser aleatorio o no, queda a tu criterio, especificando cada supuesto que realizaste en el README.
Por ende, al hacer el cambio puedes elegir una arena aleatoria de las ya instanciadas del tipo elegido por el tesoro o traspasar los atributos de la arena anterior a la nueva y cambiar el tipo, lo que quizás pueda generarte más trabajo.

Éxito con la tarea!

**Comment by SantiagoDLCB** [comment]
Y en el evento derrumbe que el enunciado dice ` transforma cualquier tipo de arena en arena normal. ` **¿Esto incluye la propia arena normal?** Osea tambien debo buscar una arena aleatoria normal para remplazar a la actual arena normal?

**Comment by Benjeeeh** [comment]
@SantiagoDLCB Como en los otros casos, cualquier evento que realice un cambio de arena a otra y esta ya se encuentre en este estado (por ejemplo, lluvia en arena mojada) no tendrá efecto. En este caso, Derrumbe solo tendrá efecto en arenas mojadas, rocosas y magnéticas. Como no se menciona explícitamente en el enunciado, puedes asumir esto a partir de los otros eventos que si menciona en que arenas no tiene efecto para tener consistencia en estos casos, pero debes indicarlo en tu README.

**Comment by Benjeeeh** [comment]
@SantiagoDLCB Como en este caso no se hace exclusión de que no afecte a una arena (se menciona que afecta a todo tipo de arena), este evento también afecta a la arena normal, por lo que si ocurre se deberá cambiar por otro tipo de arena normal.
