### ISSUE TITLE
Chasis para las siguientes carreras

### ISSUE THREAD

**Issue by fbarrosalcalde** [IIC2233/syllabus#171]
Hola! En el enunciado de la tarea sale que el daño de un vehículo en una carrera no se toma en cuenta para las siguientes. Por ejemplo si mi chasis inicial es 50, luego de los daños este disminuye a 30 y gracias a las mejoras (ponderador 2) aumenta a 60. Mi pregunta es, que valor de chasis considero para la carrera siguiente? 
- Chasis inicial por ponderador (2) = 100 (mejoras aplicadas al chasis inicial, sin considerar los daños).
- 60 (chasis final).
- 60 pero sin considerar los daños (+20) = 80.

**Comment by RositaMunoz** [comment]
Hola!
En en enunciado, en la parte de Flujo de la Carrera, dice: 
"Antes de comenzar la siguiente vuelta, se debería mostrar el Menú de carrera. **En el caso de que se seleccione entrar a los Pits, se procederá a reparar el vehículo de forma automática**, lo cual añadirá un tiempo de reparación dado por la fórmula Tiempo en los Pits, el cual será agregado al tiempo de la siguiente vuelta."
Entonces, si tu chasis inicial es 50, y luego de los daños queda en 30, como las mejoras solo se pueden hacer en los Pits, primero se repara el chasis automáticamente (quedando en 50 de nuevo) y luego se pueden mejorar sus partes, por lo que si tienes un ponderador 2, el valor del chasis mejorado queda en 100.
Espero haberte ayudado
Éxito con tu tarea! :)

**Comment by fbarrosalcalde** [comment]
Ya perfecto gracias!
