### ISSUE TITLE
Nota AF01

### ISSUE THREAD

**Issue by anamanzana** [IIC2233/syllabus#172]
Buenas tardes,

No entiendo donde se publica o donde aparecen los comentarios acerca de la actividad formativa AF01.

Muchas gracias de antemano,
Ana Mahns

**Comment by entamburini** [comment]
Hola @anamanzana! 

Como sale en el readme del [syllabus](github.com/iic2233/syllabus), se publicarán las "notas" de la AF01 y de todas las actividades en un link que aún no está disponible (básicamente porque aún no hay notas jajajja). Te recuerdo que las actividades formativas sólo tienen un punto de nota:

- 0: no logrado
- 0.5: medianamente logrado
- 1: logrado

Cuando sea el momento de publicación se les notificará por canvas seguramente :) 

Que estés bien! :v:
