### ISSUE TITLE
Poblacion en population.csv

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#172]
Están bien los datos que fueron publicados?, todos los países tienen poblaciones en los rangos de cientos de millones, por lo cual al tratar de calcular las probabilidades de muerte de cada infectado se vuelve practicamente imposible :(

**Comment by benjamimo1** [comment]
Me sumo al problema. No puedo simular contagio a otros paises por el tiempo de simulacion que conlleva contagiar al porcentaje de la poblacion necesario para eso.

**Comment by arturodelreal** [comment]
Pueden hacer una aproximación, por ejemplo si el país tiene 15.000.000 infectados pueden calcular el promedio de 15 probabilidades y multiplicarlo por 1.000.000.

**Comment by nivek0o0** [comment]
¿no habría que multiplicar ese promedio por los 15.000.000? porque sigue siendo una probabilidad por persona. Entiendo que el promedio se hace para ahorrarnos repetir el procedimiento 15 millones de veces.

**Comment by arturodelreal** [comment]
@nivek0o0 Efectivamente, me equivoque en dar la formula.
