### ISSUE TITLE
T00 - Uso de letras como la Ñ

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#172]
Puedo asumir que los ayudantes pueden correr los programas con uso de letra Ñ tanto en el codigo como en los inputs?

**Comment by vicentevegaulloa** [comment]
Hola @YehudaGurovich !

Si puedes 😄

**Comment by YehudaGurovich** [comment]
Justo me iba a contestar que de hecho no se puede en los inputs pq en la funcion que nos dieron del tablero no la considera.

**Comment by vicentevegaulloa** [comment]
Claro pero a la hora de elgir un nombre de usuario si deberias poder ingresar la "ñ".

**Comment by YehudaGurovich** [comment]
Perfecto!

**Comment by vicentevegaulloa** [comment]
Igual si estás teniendo problemas con la "ñ" no te preocupes, se decidió que no se descontará para en el caso específico de la "ñ" 👀
