### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by ewaugh2** [IIC2233/Syllabus#172]
Mi codigo esta dividido en varios modulos. Desde el modulo principal llamo al modulo "Users" para hacer una order:
`import Users
o = Users.Order(order_id=1, amount=1, price=1, "ask", "AAABBB") # el resto esta en default`

 y me aparece este error:
`Traceback (most recent call last):
  File "C:/Users/Enrique/Desktop/Proga Avanzada/ewaugh2-iic2233-2017-2/Tareas/T01/System.py", line 235, in <module>
    o = Users.Order(1, 1, 1, "ask", "AAABBB")
  File "C:\Users\Enrique\Desktop\Proga Avanzada\ewaugh2-iic2233-2017-2\Tareas\T01\Users.py", line 99, in __init__
    self.order_id = order_id
AttributeError: can't set attribute`

**Comment by ewaugh2** [comment]
Que puede ser lo que lo causa y como lo arreglo?
Agradecería una respuesta rápida.

Muchas gracias de antemano

**Comment by Hernan4444** [comment]
@ewaugh2 , con la información que nos otorgas (y buscando en nuestro gran amigo google sobre ese error) tenemos la hipotesis de que error es generado por las properties. Te sugiero revisar como estás definiendo el setter de ellas y tambien buscar sobre `property` y `can't set attribute.`

Saludos

**Comment by ewaugh2** [comment]
Si justo caché.
Muchas gracias igual :D
