### ISSUE TITLE
Cual es el significado de "consola" dentro del Readme de la Tarea 1

### ISSUE THREAD

**Issue by VAMarques** [IIC2233/Syllabus#172]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Dentro de "Cosas implementadas y no implementadas" se encuentra una parte llamada consola, que me parece redundante pues ya hay una seccion sobre el menu, **¿cual diferencia tienen estas 2 partes de la tarea?**

Gracias

**Comment by Benjeeeh** [comment]
Hola!
Se refiere específicamente a la parte en que uno entrega los argumentos (Usuario y tablero) por medio de la consola, en los cuales los siguientes puntos son evaluados:
![image](https://github.com/IIC2233/Syllabus/assets/78326186/a36304f8-53ac-47c4-8b0d-472185efd08a)

De igual manera, si es parte del menú, pero se refiere a estas interacciones principalmente.
Saludos!
