### ISSUE TITLE
Formato entrega T1

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2233/Syllabus#172]
En mi repositorio para la T1 tienen que estar mis módulos con extensión .py o la de jupyter notebook .ipynb? D:

**Comment by tomasrivera** [comment]
Tienen que tener extensión .py

**Comment by ValentinaAlvarezG** [comment]
y los archivos .csv tienen que estar ahí en el repositorio, da lo mismo o derechamente NO tienen que estar?
