### ISSUE TITLE
Duda sobre disparo a un Alien

### ISSUE THREAD

**Issue by nhi1016** [IIC2233/Syllabus#172]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! quería saber cuándo se considera un disparo válido, cuando el alien está dentro de la mira (círculo pequeño) o cuando el label de la mira colisiona con el label del alien.

Por otro lado, quería saber si considero a la mira como un rectángulo o tendría que fijarme dónde están los bordes del círculo.

Gracias de antemano.

**Comment by Emiliax16** [comment]
Hola @nhi1016 ! se considera válido cuando el alien está dentro del círculo pequeño de la mira. Respecto a lo segundo, puedes considerar a la mira como un rectángulo, de hecho Qtdesigner tiene algunos métodos bien útiles para chequear las colisiones a partir de un rectángulo que se crea alrededor de la figura. Saludos!

**Comment by isidoraabumohors** [comment]
Hola!

Tengo una duda respecto al disparo de los Aliens. Puedo definir arbitrariamente el rango de coordenadas en que se le logra disparar al alíen, mirando manualmente las coordenadas de la imagen? Por ejemplo, al revisar mi código, me doy cuenta que se debería considerar exitoso el disparo cuando la posición de la mira esta entre x e y pixeles menos que la posición del alíen. Puedo utilizar eso para definir el disparo exitoso? O es necesario que defina esa cantidad de pixeles en términos de los parámetros del tamaño de las imágenes u otros parámetros conocidos?

Espero se entienda mi duda.
Gracias!
