### ISSUE TITLE
Duda ejercicio 4.3 clases de cultivos

### ISSUE THREAD

**Issue by simone1919** [IIC2233/syllabus#172]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

[ Hola!, tengo una duda con el ejercicio 4.3. Realicé todo lo pedido en el enunciado. Complete todos los métodos con las fórmulas pedidas. Al momento de correr el código me dice que las utilidades son ceros. De hecho hice un print en el método de calcular_utilidad(self) de la clase Campo, para ver que valores tomaba self.beneficio y self.costo y siempre son ceros. No sé que me faltó por hacer para conectar esas variables con la de las clases CampoPapas y CampoArandanos. Espero que me puedan ayudar.
Gracias 
Saludos

**Comment by sr-kk** [comment]
Hola, eso pasa porque al momento de rellenar el metodo calcular_utilidad lo haces como self.utilidad = self.beneficio - self.costo. Esto siempre te va a dar cero (0 - 0 = 0) puesto que no haz llamado en ningun momento a los metodos calcular_beneficio ni calcular_costo.
Espero que te haya guiado un poco :)

**Comment by simone1919** [comment]
Si, solucionado. Muchas gracias!!
