### ISSUE TITLE
Problema al heredar properties

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#172]
Hola, estoy tratando de heredar las properties de una clase madre a otra. Mi código mas o menos es:
```python
class Madre:
    def __init__(self, atributo=None):
        self.__atributo = None
        self.atributo = atributo

    @property
    def atributo(self):
        return self.__atributo

    @atributo.setter
    def atributo(self, valor):
        if valor == None:
            self.__atributo = 5
        else:
            self.__atributo = valor
```
La clase que hereda tiene esta forma
```python
class Hija:
    def __init__(self, atributo=None):
        super().__init___(atributo)
```
El problema es que cuando instancio la clase hija sin argumentos, es decir `atributo=None` , a pesar de ingresar al setter no cambia el valor de `self.__atributo`. Ademas cuando imprimo `hija.__dict__` en lugar de salir `atributo: None` dice `_Madre.__atributo: None`
No cacho lo que puede estar pasando, necesito heredar las properties de la manera mas corta posible. Saludos

**Comment by igbasly** [comment]
Hola @dgzmr! 
Según lo que me indicas debería estar todo bien, al heredar de la clase `Madre` tu nueva clase `Hija` posee todos los atributos, métodos y *properties* que `Madre` posea, por lo tanto puedes hacer uso de la *property* sin problemas. Por otro lado, como la *property* está heredada, al hacer `.__dict__` te va a aparecer como `_Madre.__atributo` ya que finalmente ese es el atributo donde se guarda la información. Hablando en términos simples, `atributo` para python es un método de la clase que está decorado por el decorador `@property` que se comporta como un atributo. 
Algo confuso jejeje 😅 
De todas formas la herencia está bien, espero haber sido de ayuda y si sigues teniendo problemas te pido que des más detalles 😊

**Comment by dgzmr** [comment]
@igbasly gracias, era solo un problema de sintaxis jeje
