### ISSUE TITLE
Herencia OOP

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#173]
Hola! Cuando creo una superclase y una subclase de esta, se pueden crear en archivos diferentes? Y cuál archivo tiene que llamar al otro con modularización? No me deja poner en ambos archivos como que A llama a B y B llama a A. Y sobre esto cómo lo puedo hacer si ambas clases necesitan llamarse entre sí?

Por ejemplo:

class MenuInicio:

    def __init__(self):
        self.apodo = ""
        self.ranking = []
        etc...
    
    def mostrar_menu(self):
        
    def opciones(self):
        if opción == "iniciar partida":
            partida = EmpezarJuego()
            partida.opciones_de_juego()
        else:
            ...

class EmpezarJuego(MenuInicio):
    """Subclase"""

    def __init__(self):
        self.tablero = []
        etc...

    def opciones_de_juego(self):
        opción = input()
        if opción == "volver al menu":
            partida.mostrar_menu()
        else:
            ...

Algo así, si no se entiende subí lo que llevo de la tarea a mi repositorio

**Comment by Juampisaez** [comment]
Hola @kalarconvl 
Respondiendo a tu primera pregunta, si es posible hacerlo, basta con que definas la clase padre en un archivo y en otro archivo crees una sub-clase que herede la clase padre (para esto debes importar la clase padre en el archivo de la sub-clase).
La forma en que estas tratando de hacerlo generaría un loop infinito, ya que estarías importando un _archivo_1_ en el _archivo_2_ y viceversa, es decir, cada vez que importes el _archivo_2_ en el _archivo_1_, estarías importando nuevamente el _archivo_1_ en el _archivo_2_, y así mismo hasta el infinito.
Para guiarte un poco, basta que definas por separado cada clase (sin necesariamente ocupar Herencia, debería bastar con lo visto en Intro), que llames a tu clase _empezar_juego_ en alguna parte de la clase _menú_inicio_, y en la clase _empezar_juego_ definas un _método_ para salir de esa clase (que no haga nada) y así volver el menú anterior.

Espero te ayude un poco, cualquier cosa quedo atento.

**Comment by kalarconvl** [comment]
Gracias! Así lo había hecho al principio pero no entiendo cómo puedo en ese método volver al menú si no importé la clase de MenuInicio en el archivo de EmpezarJuego, estaría llamando una clase que no existe en ese archivo?

**Comment by kalarconvl** [comment]
Todo esto es porque quiero separar las clases en dos archivos distintos así no me queda un archivo eterno

**Comment by Juampisaez** [comment]
Respondiendo a esa duda,
Si llamas a tu clase Empezar_juego en la clase _Menu_Inicio_, y luego implementas un metodo que no de instrucciones en _Empezar_Juego_, entonces se dejara de ejecutar esa clase (no tendra ninguna instrucción mas) por lo que el codigo seguirá ejecutandose justo despues de haber llamado a _Empezar_Juego_ en _Menu_Inicio_.
Da lo mismo si implementas ambas clases en el mismo archivo o en dos distintos.

Espero se entienda mejor ahora.
