### ISSUE TITLE
valor de PONDERADOR_X

### ISSUE THREAD

**Issue by alvaritions** [IIC2233/Syllabus#173]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Cuando el enunciado se refiere a que el valor de un ponderador debe estar en un rango, ¿este debe ser aleatorio o puede estar definido?. Por ejemplo, si el *PONDERADOR_TUTORIAL* puede definirse como 0.95. De lo contrario pensé en usar *random.uniform* pero quiero estar seguro de si es necesario :)

**Comment by nzamorano** [comment]
Hola @alvaritions, los ponderadores debes definirlos tú en el archivo de parámetros 😉.

**Comment by MaxAl100** [comment]
> Hola @alvaritions, los ponderadores debes definirlos tú en el archivo de parámetros 😉.

¿Esto significa que pueden ser aleatorios o fijos, como queramos?

**Comment by nzamorano** [comment]
Como ustedes quieran.
