### ISSUE TITLE
Modularización

### ISSUE THREAD

**Issue by iankreisberguc** [IIC2233/syllabus#173]
Hola, al modularizar, creo varios archivo .py, y todo bien, luego para correrlos los importo con
 import archivo
 y este corre, el problema es que si lo vuelvo a importar una segunda vez este no corre.
Cual podrá ser el problema?

**Comment by gatochico** [comment]
Hola! Si entendí bien lo que estás haciendo, el problema yace en **que no debes importar el mismo módulo dos veces en el mismo archivo**. Cuando importas un módulo por primera vez, el programa lo necesita cargar y es por ello que te corre sin problemas. Sin embargo, cuando haces import de nuevo, el programa no corre nuevamente el módulo, sino que te entrega una referencia al módulo que fue ya obtenida cuando lo importaste la primera vez.

Tienes que encapsular el código de un módulo en una o más funciones, y llamar a estas funciones en tu flujo principal si deseas utilizar alguna parte más de una vez.

Espero haberte ayudado! 🤓
