### ISSUE TITLE
Creación objeto caramelo

### ISSUE THREAD

**Issue by mvveram** [IIC2233/Syllabus#173]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!

Me surgió la duda de si al crear caramelo siempre se deben subir los atributos de vida y ataque, o se debe aplicar el mismo procedimiento que a una baya o poción. Es decir, si se crea el caramelo si o si sube defensa, pero dependerá si sube los otros atributos debido a sus propias probabilidades. O al crear el caramelo, la vida y el ataque suben siempre aleatoriamente según los parámetros?

Muchas gracias de antemano

**Comment by PSepulvedaS** [comment]
Hola!

Al crear el caramelo, la vida y el ataque aumentan según los parámetros de baya y poción. Por otro lado, la defensa (que es propia de caramelo), aumenta según AUMENTO_DEFENSA. 

Espero haber podido resolver tu consulta.
