### ISSUE TITLE
Actividades de Grafos de Semestres Anteriores

### ISSUE THREAD

**Issue by NevadaStreets** [IIC2233/syllabus#173]
Estimad@s, 

Esta issue es para dejarles actividades de semestres anteriores que evaluaron la mismos contenidos que evaluará la siguiente **Actividad Sumativa** (grafos). La idea es que puedan tener material complementario para poder ejercitar todo lo que quieran.  

2015-1:
https://github.com/IIC2233-2015-1/syllabus/tree/master/Actividades%20en%20Clases/Actividad%2005

2015-2:
https://github.com/IIC2233-2015-2/syllabus/tree/master/Actividades/AC05

2016-1:
No hubo actividad de grafos

2016-2:
https://github.com/IIC2233-2016-02/Syllabus/tree/master/Actividades/AC04

2017-1:
https://github.com/IIC2233/Syllabus-2017-1/blob/master/Actividades/AC04

2017-2:
https://github.com/IIC2233/Syllabus-2017-2/blob/master/Actividades/AC04

2018-1:
https://github.com/IIC2233/Syllabus-2018-1/blob/master/Actividades/AC03

2018-2:
https://github.com/IIC2233/syllabus-2018-2/tree/master/Actividades/AC07

Si tienen dudas de alguna de estas actividades pueden preguntar en el syllabus. Finalmente, **no aseguramos que la próxima actividad sea similar a alguna de estas, pero sí que evaluará los mismos contenidos.**

¡Les deseamos mucho éxito en la actividad! Y recuerden que este jueves 19 de abril no hay clases.

**Comment by jfpena1** [comment]
Hola, me surgio la duda de como implementar los property que se piden en la actividad de 2018-2. La verdad es que me es natural en la modelacion no utilizar properties para definir los terrenos y las calles de la ciudad. Por ejemplo al añadir una calle, si mis calles son una lista de tuplas (origen, destino), al hacer append de una nueva tupla, como hago que la property se actualize?, sería mas facil que el atributo calles de la clase ciudad fuese simplemente una lista que va siendo actualizada pero esto no se permite por enunciado.

Espero haya quedado clara mi duda, muchas gracias.

**Comment by fdoflorenzano** [comment]
¡Hola @jfpena1!
La idea es similar a cosas que hemos hecho antes con *properties*. Antes, generalmente teníamos un atributo "escondido" que era el que tenía el valor que luego la *property* retornaba. Algo como lo siguiente era lo que obteniamos:
```python
class A:
    def __init__(self, atributo):
        self._atributo = atributo

    @property
    def atributo(self):
        return self._atributo

    def aumenta_atributo(self, valor):
        self._atributo += valor
```
Nota que es `_atributo` quien guarda el valor actual que `atributo` (la *property*) retorna. Además, recuerda que el acceder a la *property* funciona como un método, se ejecutará el código definido de la *property* cada vez que es accedido. Entonces, pasaría lo siguiente, por ejemplo:

```python
a = A(1)
print(a.atributo) # imprime 1
a.aumenta_atributo(5)
print(a.atributo) #  imprime 6
``` 
Si `a.atributo` no se calculara cada vez, entonces el segundo `print` no hubiese retornado `6`. 

Las *properties* que te piden siguen la misma lógica. Puedes tener un atributo interno del objeto que almacena los terrenos y calles. Cuando implementas los otros métodos, debes alterar esos atributos internos. Las *properties* para `terrenos` y `calles` se ejecutarán cada vez que se necesiten y usarán el valor actual de tus atributos internos.

Digamos internamente tienes todos tus terrenos (de clase `Terreno`) en una lista: `self._terrenos`.
Luego, la *property* que te piden podría ser algo así:
```python
@property
def terrenos(self):
    nombres = set()
    for terreno in self._terrenos:
        nombres.add(terreno.nombre)
    return nombres
```
Así, cada vez que llamen a `terrenos`, calculará el `set` de nombres con los terrenos actuales dentro de objeto `Ciudad`.

Espero se haya entendido. Avisanos si no.
Saludos.
