### ISSUE TITLE
PyQt6 problemas - No puedo instalar con sudo apt

### ISSUE THREAD

**Issue by Shoesuke** [IIC2233/Syllabus#173]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema
<img width="853" alt="Captura de pantalla 2023-09-05 012231" src="https://github.com/IIC2233/Syllabus/assets/130422187/5483472e-7636-4ccc-b763-992c5c3a0786">
Holaa, tengo el siguiente error, estaba leyendo las issues y me di cuenta de que la issue #166 tenía un error similar, al principio tenía otro error pero usando comandos de las mismas issues llegue al que tengo ahora, un avance supongo, el caso es que al probar los comandos que se le recomiendan en la issue me da con ambos el siguiente error, es algo extendo entonces mando 2 fotos.
<img width="851" alt="Captura de pantalla 2023-09-05 013123" src="https://github.com/IIC2233/Syllabus/assets/130422187/b2e5c729-68d3-4ad6-804c-6c03fb1d6440">
<img width="850" alt="Captura de pantalla 2023-09-05 013157" src="https://github.com/IIC2233/Syllabus/assets/130422187/8f82c66a-5bc1-4822-8c72-47d7362dca36">

Intenté hacer sudo apt get-update y me encuentro con esto

<img width="859" alt="Captura de pantalla 2023-09-05 013454" src="https://github.com/IIC2233/Syllabus/assets/130422187/a84de6c3-7cf6-45ba-bdfa-0357c122c720">

**Comment by maromero-21** [comment]
Me sumo a este error:
![image](https://github.com/IIC2233/Syllabus/assets/89163594/6d16e105-ebf2-4838-8148-e12685de9797)

**Comment by Hernan4444** [comment]
Hola @Shoesuke 

Estaba investigando tu error, y al parecer es porque el reloj interno de tu pc no está bien ajustado. Puedes intentar con el siguiente comando `sudo timedatectl set-ntp on` y luego hacer `sudo apt-get update`. 


Hola @maromero-21 

Para confirmar, ¿ya probaste instalando los diferentes paquete sugeridos en la [otra issues](https://github.com/IIC2233/Syllabus/issues/166)? Puesto que se han sugerido instalar varias cosas para enfrentar ese problema

> libqt6multimedia6,  libpulse0,  python3-pyqt5 y libxcb-cursor-dev

¿Te sale un error cuando intentaste instalar estas? Para poder descartar esas opciones como posibles soluciones y ver donde puede estar el error.

Saludos!

**Comment by Shoesuke** [comment]
Holaa @Hernan4444, hice el primer comando, pero aún asi me sigue saliendo el mismo error al hacer sudo apt-get update
<img width="847" alt="Captura de pantalla 2023-09-05 171543" src="https://github.com/IIC2233/Syllabus/assets/130422187/b70a574f-500e-4570-9f0d-2daaf2da30ff">
y en consecuencia no puedo instalar las otras librerias

**Comment by Hernan4444** [comment]
Hola @Shoesuke 

Intentemos con:

> `sudo hwclock --hctosys`

Luego, cerrar completamente WSL y abrirlo de nuevo, para ahí intentar con "apt-get update".  Si eso no funciona, intentar con

```cmd
sudo apt install ntp 
sudo service ntp restart 
```


Luego, cerar complemente WSL y abrirlo de nuevo. Si ya eso no funciona,  intentemos con

> `sudo apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update`

Si el segundo comando funcionó, puede ser que sea necesario desactivar el checkeo del reloj interno para instalar las cosas.


Probemos estas 3 opciones por ahora.
Estamos atentos,
Saludos!

**Comment by Shoesuke** [comment]
@Hernan4444 se me solucionó con la segunda opción y pude hacer `sudo apt install libqt6multimedia6 libpulse0 python3-pyqt5 libxcb-cursor-dev` sin problema, ahora puedo ejecutar los .py , la cosa ahora es que aquí tengo especificado que la ventana aparecerá en (0,0) pero al correr el código me aparece aleatoriamente en la pantalla
<img width="799" alt="Captura de pantalla 2023-09-05 175532" src="https://github.com/IIC2233/Syllabus/assets/130422187/7951e758-80d6-4448-beb1-62e877dbed9a">

**Comment by Hernan4444** [comment]
Hola @Shoesuke 

Que bueno que funcionó la segunda opción. Respecto al problema que estás teniendo, estamos investigando eso, pero por el momento no es nada crítico, puesto que la ventana se posiciona aleatoriamente, pero siempre se verá (si defines que el ancho y largo sea igual a tu pantalla, siempre empezará en la posición 0,0 xD). Así que no es nada grave lo que ocurre. Igual estamos investigando cómo arreglarlo.

@maromero-21 respecto a tu caso, hay una issue con exactamente el mismo error y ahí se entregó una solución. Si no funciona, porfa responde esa issue, porque esta issue surgió bajo otro problema (no poder hacer `sudo apt install`). Te dejo aquí referencia a la issue que te menciono

* https://github.com/IIC2233/Syllabus/issues/155

Finalmente, esta issue la dejaré como resuelta dado que logramos solucionar el problema original de `sudo apt`, y respecto a la posición aleatoria, eso lo responderemos en la issue donde se levantó dicha duda.

* https://github.com/IIC2233/Syllabus/issues/143

Saludosヾ(＾-＾)ノ
