### ISSUE TITLE
Contagio entre personas

### ISSUE THREAD

**Issue by Jaluco** [IIC2233/Syllabus#173]
En el enunciado se dice que una persona infectada tiene una probabilidad de contagiar entre 0 y 6 personas, esto significa que en cada país debemos calcular la probabilidad de que CADA infectado contagie entre 0 y 6 personas, ¿o podemos asumir que todos los infectados contagian la misma cantidad de personas?

**Comment by benjamimo1** [comment]
Agrego duda, los contagiados nuevos puede dar decimal, lo aproximamos a entero no?

**Comment by arturodelreal** [comment]
#172 ahí se da una posible solución
