### ISSUE TITLE
Duda respecto a la función "Cavar" proveniente de los Excavadores

### ISSUE THREAD

**Issue by benhacks300** [IIC2233/Syllabus#173]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Buenas, tengo una duda respecto a la función "Cavar" proveniente de la clase "Excavadores", esta consiste en si es posible usar la función "round" para evitar posibles casos donde se retorne un float de más de 3 decimales y concervar el orden del programa y facilitar su desarrollo.

**Comment by Benjeeeh** [comment]
Hola!

Para la función Cavar si se debe utilizar round, redondeando a los 2 decimales, como lo dice la formula:
![image](https://user-images.githubusercontent.com/78326186/232259767-ec221b9a-81d5-4f32-9787-c4c1eac0b136.png)
Al utilizar round, el primer término equivale a los cálculos con uso de los parámetros, y el segundo término a '2' que equivale el redondeo al segundo decimal.

Éxito con la tarea!

**Comment by benhacks300** [comment]
Genial!, muchas gracias por la tan temprana respuesta, me acabo de dar cuenta que no tenía actualizado el enunciado XD. 
Que tengas una buena noche!
