### ISSUE TITLE
Volver al menú puede ser en cualquier momento?

### ISSUE THREAD

**Issue by valeria-adasme** [IIC2233/Syllabus#173]
Hola :) quería terminar de entender bien si el usuario puede acceder a la opción de volver al menú en cualquier momento. Por ejemplo, en medio de la creación de su usuario o después de registrar su usuario y estar registrando el mercado al que quiere ingresar. Es decir, cancelando lo que está haciendo para volver al menú, o puedo asumir que el usuario terminará la acción antes de volver al menú?

Gracias

**Comment by Arcoirisky** [comment]
Según yo no está especificado pero, la idea es que pueda cancelar lo que haga para volver al menú si lo desea :D Imagina que se equivoque y quiera regresar D:! No podría!! 
Eso :D Suerte!!! y ¡recuerda mencionar tu decisión en el Readme!

**Comment by valeria-adasme** [comment]
Oka, aprovechando que tengo su atención...
¿El regalo del benevolente magnate Nebil es para todos los usuarios o sólo para los nuevos?
Es que no tendía registro monetario de los pre-inscritos del archivo users.csv en caso de ser sólo para los nuevos :c 🌵

**Comment by iqacevedo** [comment]
Hola,

Esa duda está respondida en issues anteriores #41, #121, no recuerdo exactamente en cuál pero en otra también respondimos que esos usuarios al inscribirse en un mercado nuevo reciben los 50.000 de las monedas.

Saludos !
