### ISSUE TITLE
Clases Abstractas: Significado de "tomar vida"

### ISSUE THREAD

**Issue by CarlosValleA** [IIC2233/syllabus#173]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola ! en el contenido de la semana 3 se menciona en varios lugares sobre que las clases "toman vida", no entiendo bien a que se refiere eso y cuando una clase toma vida.

Gracias!

**Comment by pedroriosg** [comment]
Hola @CarlosValleA ✌️ !

Una clase abstracta `(ABC)` se crea con el objetivo de modelar de mejor manera clases que heredan de ella. Piénsala como un "molde" para otras clases. No se crea con el objetivo de ser instanciada, por lo tanto, la clase abstracta nunca "toma vida" por sí misma (pues nunca se instancia).

La clase abstracta "toma vida" una vez que se instancia una **clase que hereda de ella** (subclase). Así, se pueden (a través de la herencia) acceder a sus métodos y atributos.

Espero que esto te haya aclarado un poco más! Cualquier duda pregunta nomás!
