### ISSUE TITLE
Error al hacer git pull

### ISSUE THREAD

**Issue by aayale** [IIC2233/syllabus#174]
Hola, hice git pull desde git bash para actualizar el syllabus de mi compu y me salio esto:

error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

y anteriormente me habia salido una cosa gigante (tengo la foto). ¿Qué se hace en este caso?

**Comment by kadroguett** [comment]
Hola @aayale, puedes hacer un `git status` y mostrarme que te aparece por favor

**Comment by aayale** [comment]
esto me sale:

On branch master
Your branch and 'origin/master' have diverged,
and have 2 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes to be committed:
        new file:   "Ayudant\303\255as/AY02/Ayudantia.ipynb"

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   Actividades/AC00/main.py

**Comment by aayale** [comment]
igual, como decia, me habia salido un mensaje gigante antes pero tengo la foto y no sé subir fotos aqui

**Comment by kadroguett** [comment]
Pasa que modificaste los archivos que menciona ahí, por lo que no concuerda lo que está en tu carpeta con lo que está en el syllabus. Prueba usando `git restore` y luego `git pull` (en caso que los archivos que modificaste te sirvan guárdalos en otra carpeta antes de hacer esto)

**Comment by aayale** [comment]
yaaa, hice el git restore y sale 
git restore
fatal: you must specify path(s) to restore

E intente poniendo ej: syllabus y no funciona, no se como escribir el path en este caso

**Comment by kadroguett** [comment]
prueba con `git restore .`  (esto restaurará todos los archivos del directorio)

**Comment by aayale** [comment]
pucha, lo intenté y no me sale
E hice git status de nuevo y me sale esto ahora:
On branch master
Your branch and 'origin/master' have diverged,
and have 2 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes to be committed:
        new file:   "Ayudant\303\255as/AY02/Ayudantia.ipynb"

**Comment by kadroguett** [comment]
Prueba removiendo el archivo "Ayudant\303\255as/AY02/Ayudantia.ipynb" y haciendo un `git status`

**Comment by aayale** [comment]
![error 2 (2)](https://user-images.githubusercontent.com/69651451/91229158-67bd6f00-e6f7-11ea-803d-775e93961539.png)

**Comment by kadroguett** [comment]
Eso es lo primero que te apareció o te apareció ahora luego de borrar el archivo ?

**Comment by aayale** [comment]
intente borrarlo, no funcionó y salio eso

**Comment by kadroguett** [comment]
Prueba con el comando `rm .git/.COMMIT_EDITMSG.swp` para borrar este archivo que menciona git. Este archivo contiene los cambios que habías hecho a los otros archivos. Luego haz un git status y dime que te aparece

**Comment by aayale** [comment]
Esto me sale

![Captura](https://user-images.githubusercontent.com/69651451/91232769-c4238d00-e6fd-11ea-884a-ed797f706547.PNG)

**Comment by kadroguett** [comment]
Yaa ahora prueba `git merge -- abort` borra el archivo que te aparece ahí, luego un `git status` y me muestras que aparece por fa

**Comment by aayale** [comment]
al hacer `git merge -- abort` me salió
![1](https://user-images.githubusercontent.com/69651451/91237815-95131880-e709-11ea-8349-f2b23e3b39ee.PNG)

**Comment by kadroguett** [comment]
y con `git status` que aparece?

**Comment by aayale** [comment]
Creo que lo mismo que antes

![2](https://user-images.githubusercontent.com/69651451/91238747-c2f95c80-e70b-11ea-9561-2464a50089bc.PNG)

**Comment by kadroguett** [comment]
Prueba con los siguientes comandos:
`git fetch origin`
`git reset --hard origin/master`
Estos borrarán los cambios que tienes y se hará el pull correctamente (esperemos)
Muéstrame que te aparece cuando lo haces

**Comment by aayale** [comment]
Buenisimooo, lo lograstee

![3](https://user-images.githubusercontent.com/69651451/91240827-07d3c200-e711-11ea-8b68-5d73d4bfe803.PNG)

Sorry por molestarte tanto, muchas gracias por todo!

**Comment by kadroguett** [comment]
Uff por fin!! No te preocupes para eso están las issues, feliz de poder ayudarte 😸 éxito en tu tarea!
