### ISSUE TITLE
Fecha entrega tarea 1 por semana universitaria

### ISSUE THREAD

**Issue by Draggertw** [IIC2233/Syllabus#174]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

Tengo dudas respecto a la entrega de la tarea 1, dado que esta semana es la semana universitaria y conserjería académica comunicó que esta semana no pueden haber evaluaciones y eso equivale a pruebas, trabajos, tareas , etc. Todo aquello que sea con nota. Aun asi a pesar de la comunicación de conserjería académica va a quedar para mañana la entrega?

**Comment by Hernan4444** [comment]
Hola,

Se mantiene la fecha. Consultamos sobre qué pasa en semana universitaria y solo se solicita no tener evaluaciones presenciales, para que el estudiantado pueda asistir a cualquier actividad en la U sin problema. Pero evaluaciones que son para la casa si son permitidas dado que el alumno tiene la decisión de ver cuando la desarrolla.

Saludos 🦖
