### ISSUE TITLE
Consulta QLabel en backend

### ISSUE THREAD

**Issue by Astugol** [IIC2233/Syllabus#174]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola buenas! Tenia una consulta con respecto al backend, más específicamente cuando hablamos de la "lógica del juego", lo que pasa es que para hacer este ".py" me guié mucho con respecto a la AS3 (en concreto de "logica_juego.py"), y ahí en la clase Topo dentro del backend (que en este caso podría representar una supuesta clase Alien) definen un QLabel que le proceden a ingresar una imagen, y hoy día en clases le consulté sobre una parte de mi código a un ayudante y vió de re-ojo mi clase Alien (que estaba guiada de la clase Topo de la AS3) y me dijo que no podía definir un QLabel dentro del backend, pero me causó mucha duda ya que al ver que estaba en el mismo código que nos dieron en la AS3 pensé que estaba correcto, ¿Qué se puede hacer en este caso?

**Comment by Emiliax16** [comment]
Hola @Astugol ! efectivamente QLabel() es utilizado en la AS3, por lo que puedes usarlo en la lógica de tu tarea. Eso si, es importante seguir respetando la separación frontend-backend, por lo que cualquier cambio del estado de los _aliens_ debe ser transmitido al frontend mediante el uso de señales, y aquí es donde se hacen los cambios visibles en la interfaz. Todo lo que manejes en el backend se debe actualizar en el frontend. Espero haya quedado claro, saludos!

**Comment by fffonceca** [comment]
Entiendo tu inquietud (porque también me basé en ese código), y siento que da lo mismo en términos de programación, ya que es inevitable desacoplar totalmente la estructura de Alien. Por ejemplo, si tuvieses que definir **Alien** en el frontend tendrías que definir variables propias del backend como la posición, la velocidad, y cosas que no deberían ir ahí.

Otra opción sería que al crear una instancia de backend, crearas también una de frontend, pero siento que esto hace el código más engorroso y largo. Si existe alguna discrepancia con lo que digo, podrían agregarla acá.
