### ISSUE TITLE
Duda ponderadores

### ISSUE THREAD

**Issue by itplanella** [IIC2233/syllabus#174]
Hola! en la seccion Formulas, para calcular la velocidad recomendada, se usan los valores POND_EFECT_HIELO,POND_EFECT_ROCAS y POND_EFECT_DIFICULTAD. estos valores se deben crear en los parametros o se sacan mediante otras formulas? Gracias de antemano

**Comment by gatochico** [comment]
Hola! 

Esos tres valores son parámetros que deberás añadir a `parametros.py` y asignarles los valores que prefieras.
