### ISSUE TITLE
Archivos

### ISSUE THREAD

**Issue by dchahuan** [IIC2233/syllabus#174]
Tengo una duda, los archivos se abren una vez al principio y se guardan como variable global o se van abriendo y cerrando a medida de que los vayamos necesitando??
Muchas gracias 
Diego Chahuan

**Comment by gatochico** [comment]
Hola! Si te fijas bien, el uso de variables globales [está penalizado](https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md) en la sección de descuentos de las tareas. Por lo tanto, te recomendaría la segunda opción. Éxito!
