### ISSUE TITLE
Infeccion a otros paises

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#174]
La infeccion a otros paises se realiza cuando 
> infecta al menos un 20% de la poblacion del paıs infectado.

Con poblacion se refiere a poblacion original o de la que quede viva?

**Comment by arturodelreal** [comment]
@benjamimo1 de la original.

**Comment by jorgeriesco** [comment]
@arturodelreal Puedo usar la viva?

**Comment by arturodelreal** [comment]
@jorgeriesco Es de la original, porque de esta forma se representa una "evolución" de la infección. La implementación no debiese ser muy distinta.
