### ISSUE TITLE
Cantidad de archivos a crear

### ISSUE THREAD

**Issue by ignanuyens** [IIC2233/Syllabus#174]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Tengo una duda sobre la cantidad de archivos que debo crear. Entiendo que debo tener un archivo con los parámetros y un main.py, pero no sé si debo tener un archivo para cada menú o debo crear todos los menús en el main.py.

Muchas gracias de antemano.

**Comment by tebi01** [comment]
Hola! Te comento que la creación de archivos más allá de ```parametros.py```, ```main.py```, o cualquier archivo pedido en algún enunciado, va según tu criterio. Puedes destinar un archivo al propósito que estimes conveniente, con tal que ayude a que tu código sea más legible y ordenado. De esta manera, también te ayudas a respetar PEP8 y sus restricciones de líneas. (Máximo 400 líneas por archivo)

Personalmente, te recomiendo
que agregues un archivo donde definas las clases, otro para funciones extras si es necesario y uno más para los menús. Luego, puedes importar los archivos a medida que los necesites en tu ```main.py```  (o entre ellos, cuidándote de no provocar _importación circular._) y sólo utilizar este último para ejecutar tu tarea. De esta manera, te aseguro que tu flujo de trabajo será mucho más ordenado y eficiente.



Espero haya sido de ayuda!
