### ISSUE TITLE
nivel 100

### ISSUE THREAD

**Issue by mvveram** [IIC2233/Syllabus#174]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En otras issues preguntaban sobre que pasa al entrenar cuando el programón llega al nivel 100. Mi duda es, en las otras partes, por ejemplo, si ganó una batalla, era del tipo agua y tenía nivel 100, tampoco se le sube la velocidad en `AUMENTAR_VELOCIDAD_AGUA` o ahí si. O en ninguna parte más se le aumenta algún atributo.

Muchas gracias de antemano

**Comment by PSepulvedaS** [comment]
Hola!!

El enunciado no especifica qué ocurre en estos casos pero al llegar al nivel 100 nada debería generarle un efecto al programón. Es por esto que AUMENTAR_VELOCIDAD_AGUA, como el resto de los parámetros que se aplican al ganar una batalla, no deberían generar efecto alguno.

Saludos
