### ISSUE TITLE
Duda sobre el Ejercicio 2.1: Autos deportivos

### ISSUE THREAD

**Issue by jadaam** [IIC2233/syllabus#174]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda sobre el **Ejercicio 2.1: Autos deportivos**

Hola, no comprendo el sentido de usar properties en un método que no se llama igual a un atributo de la clase. Según lo que estudié (pudiendo estar equivocado) usamos properties cuando queremos modificar el comportamiento (get, set, del) de un atributo encapsulado a través de un método, este último debe tener el mismo nombre que él atributo.  
En este ejercicio se está usando property en un método que no se llama igual al atributo, por lo tanto no comprendo su funcionalidad y la finalidad del ejercicio. Quedo atento y muchas gracias de antemano.

**Comment by tqmbanados** [comment]
Hola! Al parecer tienes una confusión con lo que son los properties. Por el contrario, la property **no** debe llamarse igual a un atributo o habrá un error. Lo que pasa es que usualmente la property está unida a un atributo, de manera que es recomendable que tengan casi el mismo nombre. El principal uso, de hecho, es para usar y cambiar un *atributo privado*, cuyo nombre partiría con ```_``` o ```__```. Por eso, una property de nombre ```nombre``` usualmente estará relacionada a un atributo privado llamado ```_nombre```. Si se llamaran igual, al correr la línea ```clase.nombre```, el programa no sabría si nos referimos a la property o al atributo. 

Sin embargo, también es usual definir *properties* no relacionadas a un atributo en específico, como en el ejercicio. Por ejemplo, supongamos una clase ```Termómetro``` que mide la temperatura en Kelvin, Celsius y Fahrenheit. Podríamos tener un atributo distinto para cada uno de ellos, pero sería un desperdicio de memoria. Nos conviene más sólo tener un atributo, que puede ser Kelvin, y definir Celsius y Fahrenheit como properties que retornan un valor según la conversión. Además, si queremos setear la temperatura, pero sólo nos manejamos en Celsius, el setter de Celsius tiene que cambiar el valor de Kelvin, también convirtiendo el valor ingresado a la cantidad apropiada en Kelvin. 

Ojalá me haya explicado bien! 

PD: el ejemplo es sólo para explicar, alguien podría argumentar que las properties definidas de Celsius y Fahrenheit ocupan más memoria que un atributo…🤔

**Comment by jadaam** [comment]
Muchas gracias por tu explicación ! Me quedó muy claro.
