### ISSUE TITLE
Detalles en los contenidos

### ISSUE THREAD

**Issue by Oisangui** [IIC2233/syllabus#174]
En la clase Grafo de ```2-operaciones-básicas-y-recorrido.ipynb``` el método ```obtener_valor_vertice``` no entrega el valor del nodo, que sería la persona, sino su lista de vecinos dirigidos.

El método ```remover_arista``` tiene un typo en el nombre. (dice ```remover_arsita```)

El init de Grafo es:
``` python
def __init__(self, lista_adyacencia=None):
        self.lista_adyacencia = dict() if lista_adyacencia is None else lista_adyacencia
```
pero no es algo redundante colocar el if en vez de poner:
```python
def __init__(self, lista_adyacencia=dict()):
        self.lista_adyacencia = lista_adyacencia
```
?

**Comment by KnowYourselves** [comment]
Hola @Oisangui!

La respuesta sería **no, no es para nada redundante**, de hecho es **_completamente necesario_**.

Esto se debe a que los valores por defecto en _Python_ _están_ pensados para ser algo **inmutable**, como por ejemplo, un número, o un _string_, cosas como de este estilo:

```python3
def funcion(a=2):
     ...
```
Lo que pasa con los valores por defecto es que estos se ejecutan solo **una vez**, es decir, cuando empiezas tu programa **automaticamente** _Python_ asigna los valores por defecto. En el caso del ejemplo `funcion`, _Python_ asocia a la variable `a` el valor `2`, por lo cual cada vez que tu ejecutes esta función sin explicitar el valor de a, tomará el 2.

El problema es que solo le asigna **un** dos, es decir solo crea **un objeto int** para representar el valor por defecto. Qué pasaría entonces si nosotros por defecto quisieramos tener un `dict`?

Veamos:

```python3
def funcion(llave, diccionario=dict()):
    diccionario[llave] = "Grafos"
    print(diccionario)

funcion("Bastante")
funcion("Extraño")
```

El  _output_ de este código va a ser:

```python3
{'Bastante': 'Grafos'}  # Primer llamado
{'Bastante': 'Grafos', 'Extraño': 'Grafos'}  # Segundo llamado
```

Esto se debe a que _Python_ solo crea **un diccionario** para el valor por defecto, el cual es compartido por todas las llamadas a la función. Debido a que los diccionarios son mutables los cambios que hagas en una llamada permaneceran para las próximas.

Es debido a esto que si uno quiere tener un atributo que tome por defecto un valor mutable se ocupa `if variable is None`, de hecho el siguiente código de ejemplo si funciona correctamente:

```python3
def funcion(llave, diccionario=None):
    diccionario = dict() if diccionario is None else diccionario
    diccionario[llave] = "Grafos"
    print(diccionario)

funcion("Bastante")
funcion("Extraño")
```

Espero haberte ayudado!

**Comment by fdoflorenzano** [comment]
Hola @Oisangui, 
¡Gracias por avisar de los errores! A veces se nos pasan cosas así y con esto podemos mejorar siempre el material. Subí unos arreglos al material para que los actualices.
Saludos.
