### ISSUE TITLE
"de forma una lista"

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#174]
En el enunciado dice:
"Lista de orders activas: Se deberá dar la opción de desplegar en consola de forma una lista de
todos los orders que están activos"

Con " de forma una lista" se refiere que trenemos que imprimir una lista con las orders? Eso se vería desordenado. No sería mejor imprimirlas para abajo simplemente con datos como el Ticker, precio etc?

**Comment by Arcoirisky** [comment]
No se refiere a una lista tipo list() (si es que entendí bien tu pregunta xD)

**Comment by Arcoirisky** [comment]
La idea es que se vea de forma ordenada, tal como lo dices tu. Puedes verlo como que debería verse una tabla con los datos que mencionas
Tranquilidad, animo y suerte!! <3

**Comment by Kitaps** [comment]
Ya buena gracias. 
Y algo que es casi igual de parecido: Aquí se piden igual que se muestren los detalles, no solamente los ids de las orders verdad?

**Comment by Arcoirisky** [comment]
Exacto xD Esperamos más que los ids. Onda, fecha de emisión, fecha de match, lo que se ha transado etc :D

**Comment by Kitaps** [comment]
gracias :)
