### ISSUE TITLE
Población - mascarillas - abrir aeropuerto/frontera

### ISSUE THREAD

**Issue by nivek0o0** [IIC2233/Syllabus#175]
Hola, tengo algunas dudas:

1.- En el cálculo de prioridad de una acción o al momento de proponer una acción (cerrar aeropuertos, entregar mascarillas, etc.), cuando se habla de la mitad de la población se refiere a la población base o a la población viva? En otras palablas, "la **población** de un país" es sanos+infectados o sanos + infectados + muertos = poblacion base?

2.- ¿Las mascarillas se entregan 1 sola vez y duran para siempre?

3.- Del enunciado entiendo que se propone abrir aeropuerto y frontera al mismo tiempo cuando se descubre la cura en el país, pero en un día normal (sin cura) la frontera y aeropuerto se podrían abrir por separado? (cuando alguno deje de cumplir las condiciones de cierre obviamente)

**Comment by Okhan97** [comment]
Cps

**Comment by AmbrosioV** [comment]
Me sumo a la pregunta 2, la 1 la respondieron en #204 y la 3 en #193

**Comment by nivek0o0** [comment]
yo creo que el enunciado sugiere que la entrega de mascarillas dura para siempre.

Por otra parte, que curioso que se respondan las preguntas repetidas más recientes que las más antiguas. Parece que la estrategia será preguntar una y otra vez las cosas

**Comment by stephichau** [comment]
Tal como dice @arturodelreal en #208 , **las acciones duran para siempre**.
