### ISSUE TITLE
Valores de atributos enemigos

### ISSUE THREAD

**Issue by CristobalGonzalezSepulveda** [IIC2233/Syllabus#175]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Cada una de las características de un combatiente tiene ciertas restricciones. Por ejemplo, el poder es un entero entre 1 y 10. ¿Es necesario corroborar que las características sean acorde a las restricción en los combatientes de nuestro equipo y el del enemigo o basta solamente con el de nuestro equipo? (por ejemplo, que el del enemigo tenga poder 12)

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Benjeeeh** [comment]
Hola!
Los enemigos también son instanciaciones de la clase Combatiente, por lo que se deben respetar todas las características mencionadas en ambas partes, exceptuando algunas acciones innecesarias y que se omiten en estos.

Saludos!

**Comment by Benjeeeh** [comment]
Recuerda también todo supuesto que realices, debe ser especificado en el README!

Mucho éxito :)

**Comment by lucianopkfreerunning** [comment]
y entonces que debo hacer si hay un inconveniente?, por ejemplo si la defensa de unos de los gatos se le asigna como "18", ¿Qué debo hacer? ¿Lo corrijo hasta su límite o arrojo un error y paro todo lanzando un print()?

**Comment by francorreaandrades** [comment]
Una duda con respecto a hasta que punto se deben respetar las restriciones de rangos definidos de cada una de las características de un combatiente.

Cuando se utiliza el método acatar de cada subclase, este modifica sus atributos, pero al modificarlos hay que procurar que estos nuevos valores respeten los rangos establecidos iniciamente en el enunciado o esos solo importan al momento de instanciar la clase??

Por ejemplo, en el encuenciado dice:
"Resistencia: Corresponde a un int entre 1 y 10 que representa la resistencia de un peleador a lo largo del combate." 
Pero con el metodo atacar de la clase Caballero, su resistencia disminuye... al modificar este parámetro, hay que revisar si toma valores inferiores a 1?? En caso de tomarlos, se redefine self.resitencia como 1, o asumo que eso no pasa antes que el combatiente muera en la batalla??
