### ISSUE TITLE
Dinero Por vuelta

### ISSUE THREAD

**Issue by tcperez** [IIC2233/syllabus#175]
Hola!

En la página 6 del enunciado sale "En el caso de que el jugador quede en primer lugar al terminar una vuelta, se le otorgará una cantidad de dinero señalada según la fórmula Dinero por vuelta". Cuando uno ve la fórmula en la sección Fórmulas, se indica "cada vuelta que sobrevivas es una una nueva puerta que se abre ante ti. Conseguirás dinero por cada una".

No entiendo, ¿se otorga dinero si se posiciona en primer lugar, o siempre?

Gracias de antemano!

**Comment by gatochico** [comment]
Hola! 

Se otorgará el dinero definido por la fórmula al jugador solo cuando llegue en primer lugar en una vuelta.

Cualquier duda comenta y saludos!
