### ISSUE TITLE
Duda tiempo al fin del nivel

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#175]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Si al final del nivel, durante la animación de terminator-dog con un alien en la mano, el tiempo que se ve en la pantalla es igual a 0 segundos, pero luego al ir a la ventana de postnivel el tiempo que quedaba al final de la partida se muestra bien, ¿hay algún problema?

**Comment by Emiliax16** [comment]
Hola @MaxAl100  ! se evalua la consistencia y progreso correcto de las estadísticas, por lo que trata de que al final de la partida el tiempo mostrado sea el correcto. De todas maneras, puedes ver la distribución de puntaje e ir calculando cuando te afecta cada detalle! saludos c:
