### ISSUE TITLE
Optimizar imports

### ISSUE THREAD

**Issue by ian-fell** [IIC2233/syllabus#175]
Hola. Para mi archivo principal necesito importar muchas funciones de un mismo módulo, lo que hace que tenga una línea muy grande del tipo: from "modulo" import "fun1", "fun2", "fun3", ...... y así. No quiero hacer simplemente import "modulo", ya que cada función tendría que antecederla de un "modulo.". Puedo hacer 2 lineas importando de un mismo módulo y dividir las funciones en esas dos lineas para acortarlas? O sino como podría importar todas las funciones sin tener que usar el import "modulo"?

**Comment by kadroguett** [comment]
Hola @ian-fell, lo que puedes hacer es hacer `import modulo as f` y luego para acceder a las funciones cuando las necesites deberías escribir `f.fun1`, `f.fun2`, etc.

**Comment by ian-fell** [comment]
Claro, pero de todas formas tendría que anteceder las funciones por algo, en ese caso con un "f.". Hay alguna forma de importar muchas funciones y no tener que antecederlas por el módulo?

**Comment by kadroguett** [comment]
La otra opcón es hacer `from modulo import *` pero esto es una mala práctica que conlleva un descuento 👀👀

**Comment by ian-fell** [comment]
Ah perfecto, gracias
