### ISSUE TITLE
Idioma en el código

### ISSUE THREAD

**Issue by rieg-ec** [IIC2233/syllabus#175]
Holaa, por costumbre y comodidad escribo los nombres de clases, variables, comentarios etc. dentro de mi codigo en inglés, mi pregunta es si está bien o debo si o sí programar en español :c (el readme está en español)

**Comment by aljara97** [comment]
Qué opinan? Es para el amigo que tiene el código en inglés 

Hola @rieg-ec, si bien no te puedo asegurar que el ayudante que corrija tu tarea tenga un manejo lo suficientemente adecuado del inglés para entender tu código, debido al tiempo que queda por esta vez te sugiero dejarlo así e introducir comentarios en español y ser más explícito en tu README con lo que hace cada clase y cada función. Sin embargo, para las próximas tareas es necesario incluir una mayor cantidad de variables y por consecuencia debemos leer más líneas de codigo, por tanto, ahí deberás programar en español para facilitar la corrección de tu tarea.

Éxito :bird:

**Comment by aljara97** [comment]
Consulté con otros ayudantes y están de acuerdo que programes en inglés por el resto del curso, debido a que es considerado una buena práctica por la universalidad de ese idioma y te puede ser útil en otros cursos. Eso sí, te sugerimos incluir comentarios en español, que nos permitan entender de mejor forma tu código, además de ser claro con tu readme como te mencioné anteriormente

Saludos ✌🏻
