### ISSUE TITLE
Entregar_ruta Actividade 07 2018-2

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2233/syllabus#175]
![image](https://user-images.githubusercontent.com/42182095/56238818-6852e980-605d-11e9-9d6d-316199f97b56.png)
Para la maioria de los casos me funciona ese codigo, pero para algunos casos no. Ejemplo : Ciudad.entregar_ruta("A","F") del easy.txt (Encontrar la Ruta desde A hasta F) existe una ruta [A, C, E, F] pero ese código no lo encontra (el problema es que en visitados ya esta C Pues vas de A->C->B->D y en D solo hay B y como C ya esta en visitados me retorna que no hay camino, queria saber como puedo solucionar eso, gracias de cualquier forma ☻

**Comment by fdoflorenzano** [comment]
¡Hola @csantiagopaz!
Disculpa la demora, pero me era necesario leer y entender la actividad a que hacías referencia para poder entender el problema.

Creo entender lo que pasa. Tu código sigue una buena estructura recursiva para lograr el objetivo, pero tiene varios detalles. El que preguntas tú, de por qué no encuentra el camino, se debe a la sección de código más anidada que muestras:

```python
for camino in self.conexiones[origen]:
    if camino not in visitados:
        return self.entregar_ruta(camino, destino, visitados)
```
Con esta porción intentas buscar el siguiente camino que seguir en la ruta, lo cual está súper, el problema es que se lanzará `return` para el primer `camino` que no esté en tu ruta actual, independiente si el camino que construya hacia adelante llega al destino. En el caso que muestras, cuando `origen` es `"C"`, `visitados` hasta el momento es `["A", "C"]`, este ve la primer camino conectaco a `"C"`, que es `"B"` y hace `return self.entregar_ruta("B", "F", ["A", "C"])`. Al hacer return directamente, esa llamada a la función terminará y retornará sí o sí el resultado de `self.entregar_ruta("B", "F", ["A", "C"])`. Luego, como no hay un camino entre `"B"` y `"F"`, tu código retornará `"No tiene camino"`, para ambas llamadas.

Lo que le falta a tu código, es dejarle la posibilidad de que **pruebe con los distintos caminos** y solo retorne aquel que **logre llegar al destino**. El tuyo por ahora solo intenta con el primero que encuentra, y retorna ese. Entonces, debería intentar construir una ruta usando cada camino, y solo en caso de que no le entregue `"No tiene camino"` el resultado, retornará efectivamente ese camino. Para el caso que mencionas, debería computar (sin retornar) `self.entregar_ruta("B", "F", ["A", "C"])`. Luego debería verificar el resultado y reconocer si encontró un camino a `destino`. Como sabemos que retorna`"No tiene camino"`, tu código debería reconocer eso e intentar con el siguiente `camino` en `self.conexiones[origen]`, lo que eventualmente lo llevará a probar con `"E"`, que si llega a `"F"`, entonces `self.entregar_ruta("E", "F", ["A", "C"])` **no** le va a retornar `"No tiene camino"`.

## Otros detalles:
Hay varios detalles en tu código que me llaman la atención, que quería que pensaras:

- El enunciado de la actividad dice que la función no debe retornar `"No tiene camino"`, si no que una lista vacia `[]`. Alterar el código anterior para ese caso no es díficil, pero es importante notar ya que es mejor práctica que tus funciones retornen el mismo tipo de objeto siempre: en este caso, siempre retornará una lista.
- La variable `por_visitar` que defines nunca se usa. Solo se actualiza y agregan cosas en ella, pero nunca hacer una revisión de contención con ella. ¿Será necesaria para el método?
- Dentro del primer `if` del método, revisas si `origen` está en `self.conexiones.items()`. Recuerda que `dict.items()` retorna tuplas de la forma `(llave, valor)`. Y yo creo que no es eso lo que buscas. ¿Qué te arroja si llamas a `self.entregar_ruta("A", "A")`?

Y otras preguntas sobre la estructura de tu código, que puede que lo mejoren:
- El primer `if` solo funciona para el caso en que se llame con `origen == destino`. Nota que este ignora completamente el valor que le den de `visitados`. ¿Podría haber otro caso en que se use este caso base?
- Esto está tal vez relacionado con la anterior, pero, ¿es la sección que revisa si `destino in self.conexiones[orgien]` necesaria? Si te fijas, de todas maneras vas a revisar después en las conexiones vecinas si se puede hacer un camino.

Espero esto sea de ayuda, si tienes más dudas, nos avisas.
Saludos.

**Comment by csantiagopaz** [comment]
Muchas gracias Fernando, si fue de mucha ayuda !!
Estoy arreglando mi código y si tengo otra duda te aviso, y de verdad muchas gracias!
Saludos

**Comment by csantiagopaz** [comment]
Hola Fernando indo a la ayudantia aprendemos a hacer una ruta más corta ocupando backtracking , al copiar el código y adaptar a el encontrar_ruta_corta me genera un error al ocupar más de una vez la función.
![image](https://user-images.githubusercontent.com/42182095/56697841-e6e30300-66bd-11e9-8c0b-914f64f4546f.png)
aca esta un ejemplo de lo que pasa
![image](https://user-images.githubusercontent.com/42182095/56698204-25c58880-66bf-11e9-9f37-bb3a994285ec.png)

**Comment by fdoflorenzano** [comment]
¡Hola @csantiagopaz !
Se debe al valor por defecto que tiene la función `ruta_corta` para `visitados`. Al ser un `set`, este es un objeto mutable y por lo tanto se utiliza el **mismo**  `set` en cada llamada. Es por eso que las siguientes dejan de funcionar, ya que tienen `visitados` con nodos dentro.

Se explica en detalle esto en la issue #174, en la respuesta de KnowYourselves.
Saludos.
