### ISSUE TITLE
Duda sobre Polimorfismo - Duck typing

### ISSUE THREAD

**Issue by ag-contreras** [IIC2233/syllabus#175]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Utilididades practicas del Duck typing (?)

Respecto al Duck typing, si bien se explica que python es capaz de interpretar una función ```def``` con métodos fuera de una clase para un objeto que su clase tiene definido un(os) método(s) con es(os) nombre(s), realmente cual es la utilidad practica de crear una función ```def``` nuevamente si su clase ya los incorpora? Solo para ejecutar varios métodos al mismo tiempo en lugar de tener que escribirlos uno por uno?

Gracias por su tiempo, espero que se entienda mi duda.

**Comment by pabloist** [comment]
Hola!

Te comento que creo que tienes alguna confusión con las definición, a continuación te aclaro cada una de ellas

   -Duck Typing: Corresponde a la capacidad del lenguaje de interpretar métodos de dos clases diferentes que poseen el mismo nombre y hacer el llamado de la clase correspondiente. El DuckTyping es útil dado que no necesitamos dar nombres únicos a los métodos para poder diferenciarlos, ya que Python lo interpreta automáticamente.
   -Polimorfismo: Hace referencia a la posibilidad de "sobreescribir" un método heredado por la clase, es decir, deseo que la clase que estoy definiendo y que está heredando sus métodos de una clase madre "A", realice otros procesos. Utilizamos el "overriding" cuando la función definida de la clase madre "A" no cumple los objetivos designados para la clase que hereda.

Utilizar uno u otro depende del contexto, lo importante es reconocer que podemos definir métodos que sintácticamente sean iguales, pero que al ejecutar el algoritmo son ejecutados de forma diferentes, cumpliendo los objetivos particulares de cada uno.

Espero sea de ayuda :) y cualquier cosa puedes comentar en esta misma issue.

**Comment by ag-contreras** [comment]
Me quedo todo muchísimo más claro, gracias por la ayuda y aclaración :)
