### ISSUE TITLE
duda velocidad_recomendada

### ISSUE THREAD

**Issue by Afro27** [IIC2233/syllabus#176]
Si la pista en la que el piloto este corriendo es de hielo o de rocas, hielo o rocas pueden no tener valores asignados. Mi pregunta es al calcular la velocidad_recomendada se dice influye:
(traccion_ruedas - hielo_pista)
(defensa_carroceria - rocas_pista)
hielo_pista y rocas_pista se deben considerar 0 en caso de no haber rocas o hielo y multiplicar el valor de traccion y defensa por los ponderadores correspondientes? Ya que según la lógica, que no haya rocas o hielo deberia hacer que la velocidad recomendada sea mas alta.

**Comment by jcechavarri** [comment]
Hola @Afro27 !

Como bien dices, si los valores de *hielo_pista* o *rocas_pista* no han sido definidos los debes considerar como cero en tus formulas.  En cualquier caso, recuerda que **no** puedes modificar el archivo `pistas.csv`.

Espero te haya ayudado, saludos! :smile:

**Comment by SamWeinstein** [comment]
Hola! En esta misma formula, donde están los valores de POND_EFECT_HIELO, POND_EFECT_ROCAS Y POND_EFECT_DIFICULTAD?

**Comment by Afro27** [comment]
@SamWeinstein  Tengo entendido los tenemos que inventar nosotros en parametros.
