### ISSUE TITLE
Repetición de combatiente en equipo

### ISSUE THREAD

**Issue by CristobalGonzalezSepulveda** [IIC2233/Syllabus#176]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
A la hora de comprar combatientes, ¿puedo comprar dos del mismo tipo en la misma ronda? y si es que se puede, ¿Qué ocurre si sale elegido dos veces el mismo combatiente del archivo de unidades?¿Es posible esto o debo asegurarme de que no ocurra?

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Benjeeeh** [comment]
Hola!
El limite de acciones dentro de una ronda es ilimitado hasta que se realice un combate, ya que esto determinará si pasas a la siguiente ronda o pierdes. Como no se específica si el combatiente comprado solo se puede una vez o no, está en tu decisión el como manejas este caso, es decir, tu decides si los combatientes son infinitos o una vez que lo compres se elimina de la tienda, manejando obviamente los potenciales errores que pueden ocurrir en ambos casos.

Saludos!

**Comment by Benjeeeh** [comment]
Recuerda también que todo supuesto que realices, debe ser especificado en el README!

Mucho éxito :)
