### ISSUE TITLE
Metodos en grafos de los contenidos

### ISSUE THREAD

**Issue by fediaz3** [IIC2233/syllabus#176]
Hoola

Tengo una duda en los contenidos:

Dentro de las operaciones básicas de un grafo nos dicen que:
    obtener_valor_vertice(G, x) obtiene el valor asociado al vértice x.
    fijar_valor_vertice(G, x, v) asigna el valor v al vértice x.

En el ejemplo: Usamos que un nodo tiene un atributo valor, donde 
vamos a almacenar un objeto de class Persona
~~~
class Nodo:
    def __init__(self, valor):
        self.valor = valor
~~~

Y luego en los metodos de los grafos...
según la definicion, el metodo obtener_valor_vertice(x),
no deberia retornarnos el objeto de class persona del nodo x?,
envés de retornar el set que apunta a sus vecinos?
(porque el metodo que retorna el set que apunta a los vecinos está hecho en el método
vecinos(self,x) )
~~~
    def obtener_valor_vertice(self, x):
        return self.lista_adyacencia.get(x, None)
~~~

Por la misma razón deberia, haber también una modificacion en el método:
~~~
    def fijar_valor_vertice(self, x, v):
        self.lista_adyacencia[v] = self.lista_adyacencia.pop(x)
~~~
de manera que cambie el nodo.valor y se asigne una nueva persona?

Gracias por sus respuestas

**Comment by fdoflorenzano** [comment]
Hola @fediaz3, esto se responde parcialmente en #174, la sección que hablas ya fue alterada, creo que estás viendo la versión anterior.

Se habían actualizado los contenidos con unos arreglos sobre este tema. Pero, con tu pregunta, noté que había otro arreglo que hacerle a  `fijar_valor_vertice`. 

La implementación que estaba funcionaba, pero estaba incompleta. Lo que hace en vez de alterar el valor encapsulado en el nodo, es simplemente reemplazar el nodo completamente, reemplazándolo en la estructura de lista de adyacencia. Lo que le faltaba era además reemplazar su valor en las referencias de todas las otras llaves de la lista. Antes, se hubieran quedado con el valor antiguo de `x` si otro nodo le hacía referencia.

Ahora, tu pregunta realmente es sobre por qué retornamos nodos en vez de personas directamente, ¿no? Es una duda muy válida, y podría alterarse ambos métodos para que trabajen con el `x.value`, en vez de `x` completo. 

La justificación detrás de la implementación del material, es que la implementación de la clase `Grafo` es agnóstica a la implementación de los nodos. El escribir `x.value` dentro de la clase `Grafo` la hace dependiente de que `x` tiene que tener un atributo `value`. Si quisiéramos usar otra clase para los vértices, se caería el programa si esa clase no tiene un atributo `value`. Pero de esta forma, nota que para los valores de los vértices podemos usar prácticamente lo que sea, incluso instancias de la clase `Persona` directamente.

Todo esto son decisiones de modelación. Distintas implementaciones tienen distintos razonamientos por detrás y pueden ser igual de válidos. Una implementación de `Grafo` puede usar por detrás a `Nodo` como contenedor (y por lo tanto acceder a `x.value`. Esa también puede tener sus ventajas (hace incluso tal vez más flexible que cosas almacenar en los nodos).

Espero haber respondido tu duda. Si te quedan o surgen más, no dudes en responder.

¡Saludos!
