### ISSUE TITLE
__pycache__ folder

### ISSUE THREAD

**Issue by benjastraub** [IIC2233/Syllabus#176]
Hola, en la carpeta que estoy haciendo la tarea se creó una carpeta que se llama `__pycache__`

¿Debería subir esa carpeta al git o no es necesario?

**Comment by Hernan4444** [comment]
@benjastraub ese tipo de carpetas no son necesarias de subir e incluso, recomiendo no subirlas puesto que no aportan a la tarea en sí, te sugiero investigar sobre `.gitignore` para que git ignore ese tipo de carpetas, en esta issue #158 está lo que me refiero. 

Saludos 

ps: Si ya la subiste, no importa. No hay ninguna clase de descuento en hacer eso 👍  (por ahora ... 🙀 (?) )
