### ISSUE TITLE
Duda bala dorada

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#176]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

¿Que la bala dorada aparezca "una vez por partida" significa que si uno le hace click no aparece más o si aparece una vez ya no va a aparecer más? Además, supongo que estas 3 balas extra que uno gana duran sólo ese nivel específico cuando uno le hace click, ¿no?

**Comment by nzamorano** [comment]
Hola @MaxAl100 , tal como dice el enunciado la bala debe **aparecer** solo 1 vez por partida (independiente si se selecciona o no). Respecto a lo segundo, sí, las balas extra duran solo por ese nivel, pues las balas no son acumulables de un nivel a otro.
