### ISSUE TITLE
Duda test_09_detectar_plagas.py

### ISSUE THREAD

**Issue by Vicho03** [IIC2233/Syllabus#176]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [x ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Estaba viendo el código del test case 09 y en el test 2 en la lista de plagas está el siguiente elemento:
["0", [3, 5], ["Z", [7, 8]], en donde la lista del predio "0" no está cerrada. ¿Esto debería ser así o habré cambiado algo por sin darme cuenta?

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by individuocomunycorriente** [comment]
Hola!
Revisé el test y el apartado que tiene este error no es más que un comentario (por lo que no influye en la eficacia del test), si te fijas en la linea 223 se encuentra escrita correctamente la lista.
Saludos.

**Comment by Vicho03** [comment]
Vale, efectivamente el test funciona bien. ¡¡Muchas gracias!!
