### ISSUE TITLE
Duda sobre codigo preexistente en main.py

### ISSUE THREAD

**Issue by Laefivy** [IIC2233/Syllabus#176]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! El siguiente código que viene en el archivo main.py lo debo dejar o lo puedo eliminar? Pregunto porque se incorpora en mi menú de acciones y no sé si está presente únicamente para demostrar el uso de sys.argv o por otra razón
<img width="324" alt="Captura de pantalla 2023-09-05 a la(s) 12 52 49" src="https://github.com/IIC2233/Syllabus/assets/141865857/601de351-7db1-4628-a985-9fcf561bdc27">

**Comment by roahoki** [comment]
hola @Laefivy , eso solo fue puesto para demostrar el uso de sys.argv, asi que no afecta en tu evaluación lo que hagas allí :)
