### ISSUE TITLE
[003] Cardinalidad de las relaciones

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#176]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

![image](https://user-images.githubusercontent.com/66154723/113492188-31757880-94ac-11eb-995e-9877f0b2df3e.png)

**Comment by riadeane** [comment]
Hola @fernandosmither! 😄 

La diferencia entre tener una relación de 1 o de 0 es más que nada la _opcionalidad_ de la relación. En el caso de tener una relación de 1...\*, estás diciendo que la relación **debe** tener una o más instancias de la clase. Por otro lado, el caso de tener una relación de 0...\* se refiere a que **puede** tener una o más instancias de la clase. 

Por ejemplo, en el caso de los contenidos, del Ejército y Goomba, un Ejército **debe tener** por lo menos a un Goomba. Si existiera un Ejército que puede consistir tanto de Goombas, Shy Guys y Koopa Troopas, **no es necesario** que tenga por lo menos a un Goomba.

Espero que con eso te haya quedado más claro! 🌺

**Comment by fernandosmither** [comment]
> Hola @fernandosmither! 😄
> 
> La diferencia entre tener una relación de 1 o de 0 es más que nada la _opcionalidad_ de la relación. En el caso de tener una relación de 1...*, estás diciendo que la relación **debe** tener una o más instancias de la clase. Por otro lado, el caso de tener una relación de 0...* se refiere a que **puede** tener una o más instancias de la clase.
> 
> Por ejemplo, en el caso de los contenidos, del Ejército y Goomba, un Ejército **debe tener** por lo menos a un Goomba. Si existiera un Ejército que puede consistir tanto de Goombas, Shy Guys y Koopa Troopas, **no es necesario** que tenga por lo menos a un Goomba.
> 
> Espero que con eso te haya quedado más claro! 🌺

### Comprendo, entonces en el último ejemplo que planteas, sería una relación 0 ; 0..* ?

**Comment by riadeane** [comment]
Hola @fernandosmither!

Exacto, el primer caso sería una relación de 1...\* y el segundo sería de 0...\* 😄
