### ISSUE TITLE
__delitem__

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#176]
Cuando dicen a que si la estructura es ordenada debe responder bien a la indexación, cuando se refieren al __delitem__ se refieren  a que hay que ser capaz de retornar un trozo de la estructura de datos  (por ejemplo [i:j] como en las listas) o bien se refiere a sacar a ese elemento de la estructura de datos (una especie de deleter) ?

**Comment by arturodelreal** [comment]
__delitem__ es un deleter.
