### ISSUE TITLE
Duda con entrega de tarea

### ISSUE THREAD

**Issue by diegogarcia98** [IIC2233/syllabus#176]
Hola!

Me llegó un mail diciendo que mi tarea será revisada con el commit  babe454 y según tengo entendido, hay que entregarlo en Master. ¿Podrían aclarar esta dudad porfavor? He subido todo a mi repositorio con branch master.

Agradecido de antemano,

Diego García

**Comment by entamburini** [comment]
Hola @diegogarcia98!

- Primero que todo, ese mail es autogenerado porque se creo una [issue en tu repositorio](https://github.com/IIC2233/diegogarcia98-iic2233-2020-1/issues/1) y por defecto está configurado de esa manera. 
- Lo segundo es que si te fijas bien, se avisa del commit a revisar para la **AF01** y no para la tarea, cuya recepción de commits es hasta hoy lunes a las 20 hrs. 
- Tercero, tienes una confusión con la definición de commits y Master. Master es la rama que revisamos para ver sus entregas, eso es cierto y en Master es donde ustedes deben hacer los commits (que son algo así como registros de cambios). El commit a revisar indica el estado de tu repositorio (y de Master) el cual utilizaremos para revisar tu actividad.

Ojalá haya sido lo suficientemente claro :D
