### ISSUE TITLE
Error al imprimir tablero

### ISSUE THREAD

**Issue by franciscastanke** [IIC2233/syllabus#176]
Hola, al hacer una prueba para imprimir el tablero me sale este error:
![image](https://user-images.githubusercontent.com/69608412/91217044-e6f57780-e6e4-11ea-8da1-bb85c400691d.png)
Ya intente cambiando el utf8 de True a False y me sale el mismo error.
¿Es un problema del computador?, ¿Qué puedo hacer?

**Comment by kadroguett** [comment]
Hola @franciscastanke, puedes subir lo que llevas a tu repositorio por favor

**Comment by franciscastanke** [comment]
Ok, listo, ya lo subi.

**Comment by kadroguett** [comment]
probando tu archivo con los archivos del syllabus me corre bien, hiciste alguna modificación en `tablero.py` ? puedes probar usando los archivos del syllabus sin modificar a ver si te funciona bien. (Foto de la prueba que hice con tu archivo)
![image](https://user-images.githubusercontent.com/31357861/91220043-959bb700-e6e9-11ea-958a-28d7c1e8c207.png)

**Comment by franciscastanke** [comment]
No, no le hice ninguna modificación al archivo de tablero, use el que esta en el syllabus. Puede ser que es un problema de mi computador??

**Comment by kadroguett** [comment]
Puede que sea un problema de tu computador, tienes un Mac? . Una solución que puedo darte es que en el archivo tablero cambies los cuadrados por un guión bajo (_) en las lineas 13 y 14,  y especifiques en el readme que hiciste esa modificación.

**Comment by DCCollao** [comment]
Hola @franciscastanke! El error que obtienes al intentar correr el archivo es porque estás utilizando una versión equivocada de python.
Sucede que mac trae instalada por defecto la versión 2 de python, y es esa la que se ejecuta al correr comandos del tipo `python file.py`. Para cambiar esto, y utilizar python3 en lugar de python2, debes ejecutar el comando siguiente:
`python3 file.py`.

En caso de que no te funcione hacerlo de esta forma, tal como mencionó mi compañero, puedes cambiar los caracteres indicados.

Quedamos atentos!

**Comment by franciscastanke** [comment]
Yaa, muchas gracias, poniendo python3 file.py me funcionó.
