### ISSUE TITLE
Estructura de datos strings y +

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#176]
Hola
Vamos a considerar a los strings como estructuras de datos?
Se puede usar locals() y globals() para crear y retornar atributos de clases?
Tienen referencias material para crear estructuras de datos más "complejas" como las listas o diccionarios? Llevo días buscando y solo encuentro tutoriales de cómo usar listas u.u La idea es tener referencia a todas las posiciones de la lista o diccionario para no tener que iterar cada vez que quiera modificar o leer un valor.
Gracias.

**Comment by cilopez** [comment]
- No hay problemas con los strings, pero cuidado con los métodos de strings que retornan listas tales como split

- No puedes usar locals y globals ya que llaman por debajo a un diccionario.

- En general te recomiendo partir buscando sobre tablas hash, otra buena idea sería analizar como se implementan estructuras de datos en otros lenguajes donde existe mayor documentación acerca de este tema tales como C o C++ , a partir de eso traspasarlo a python . Trata de no complicarte tanto, en general deberías poder resolver la tarea con las estructuras de datos vistas en clases.

**Comment by jmwielandt** [comment]
Sí, podría usar las listas ligadas, árboles y grafos (usando listas ligadas para guardar todo adentro) pero para crear una lista que funcione por índices o un diccionario, no son nada óptimas, pues son FIFO o LIFO según cómo las programe pero para sacar el elemento 199, si son 200, tengo que pasar previamente por los 198 anteriores (si las hago en una dirección) o puede haber complicaciones (o algo así dijeron en una issue hace tiempo) si las hago bidireccionales porque estaría usando programación circular.
El enunciado también habla de que se evaluará la eficiencia de los algoritmos que implementemos en las estructuras de datos y además el corrector puede penalizar la nota por lo mismo.

**Comment by jmwielandt** [comment]
Update: las tres implementaciones de hash tables que encontré usan listas para guardar las keys T.T

**Comment by cilopez** [comment]
@jmwielandt No puedo darte más detalles acerca de que hacer porque son objetivos de la tarea, te recomiendo que te sigas cuestionando donde y porqué usar una estructura de datos específica.

**Comment by visalasc** [comment]
@cilopez , por lo que he estudiado las tablas de hash, hay dos opciones de implementación, pero ambas se basan en el uso de arrays. Sería posible usar las listas de python como array?, por ejemplo usar solo un tipo de dato y largo constante?
Saludos
