### ISSUE TITLE
Recuperar energía de todos los entrenadores

### ISSUE THREAD

**Issue by MarquezFelipe** [IIC2233/Syllabus#176]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Buenas, en el enunciado se menciona "Al final de cada ronda, se restaura al máximo la energía
de todos los entrenadores asociados." Mi duda es que tan necesario es restaurar la energía siendo que por lo que entiendo solamente el entrenador que el usuario está usando gasta energía.

**Comment by PSepulvedaS** [comment]
Hola!!

Al final uno está usando un entrenador para crear objetos, pero si el enunciado dice que hay que restaurarle la energía a todos los entrenadores asociados, eso es lo que tiene que cumplir tu código.

Saludos
