### ISSUE TITLE
Duda sobre bombas especiales y doble oportunidad de tiro

### ISSUE THREAD

**Issue by allisonaguilar** [IIC2233/syllabus#177]
Hola! mi duda es sobre que ocurriría si se descubren dos bombas o más con un solo tiro especial, tendría dos tiros extra el jugador o solo uno? 

Gracias!

**Comment by jitorralba** [comment]
Hola @allisonaguilar! 
Esa duda se encuentra resuelta en la issue #170 
En resumen, queda a tu criterio siempre que lo detalles en tu README
Espero haberte ayudado, suerte con tu tarea!

**Comment by allisonaguilar** [comment]
Gracias!
