### ISSUE TITLE
Ejercicio 2.3: DDCgram - como obtener lista de objetos

### ISSUE THREAD

**Issue by Piolawa** [IIC2233/syllabus#177]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Hola!, en este ejercicio solo me falta que al imprimir la lista self.usuarios , los objetos no se vean de la siguiente forma:
 [<__main__.Usuario object at 0x000001BEE1D0F0C8>] 

Implementé los métodos ´´´__str__´´´ y ´´´__repr__´´´ de distintas formas, en la clase Usuario y en DCCgram, y ninguna a resultado.

El último código que probé era de la forma:
```python
def __str__(self):
    return str([g.group_name for g in self.group_list])
```

Ese trozo de código lo saqué de:
https://www.reddit.com/r/learnpython/comments/4isdtr/help_with_printing_out_a_list_of_objects_from_a/

Ayuda por fa 😿

**Comment by catalina-arcila** [comment]
Hola, debes recordar la diferencia entre "__str__" y "__repr__", si quieres que te devuelva en la consola string debes usar "__repr__". Ahora tienes que pensar el flujo de tu código si este llama a "dcc_gram.usuarios" esta será una lista de la clase Usuarios por lo que tu código irá a cada clase y lo imprimirá. Por lo que debes colocar tu "__repr__" en la clase Usuarios. ☺☺
Espero que te haya quedado claro, avísame como te va!

**Comment by Piolawa** [comment]
Graciaas! resultó con eso uwu
