### ISSUE TITLE
Feedback AC03 - EDD

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233/syllabus#177]
# Feedback AC03

A continuación se detallan _tips_ y errores comunes encontrados en las actividades entregadas para la AC03. No duden en comentar dudas o postear issues con dudas relacionadas a esta. Pueden etiquetar issues al usar el signo gato (#) y el número de la issue. En este caso, #177. 

## `agregar_instalación`

Cuando se trabaja con árboles (y eventualmente con grafos) el proceso de agregación se separa siempre en dos casos distintivos: 

1. El nodo que recibo debe ser mi hijo directo. Por lo tanto, lo agrego a mis hijos.
2. El nodo que recibo no debe ser mi hijo directo, sino que debe estar más abajo en la jerarquía. En este caso, busco a mi hijo más adecuado para recibirlo.

(Para el caso de grafos, en vez de hijo, sería vecino).

Entonces, es buena idea separar estos casos por un if/else pudiendo crearse funciones auxiliares como `es_hijo` (que revise si debiese ser hijo directo) u `obtener_hijo` (que obtenga un hijo apropiado para agregar). Aterrizando esto a la actividad, una forma de verlo es: siempre que agrego una instalación debería ocurrir el siguiente proceso: Le pregunto a la instalación si lo que voy a agregar debiese ser mi hijo (ej: si yo soy una Generadora entonces mi hijo debería ser una Distribuidora Regional), si es así la agrego y salgo del método, de lo contrario recorro a mis hijos y hago el llamado recursivo del método a solo uno de mis hijos.

En la actividad, la clase `Instalacion` modela a **todos** los tipos de nodos: a la Generadora, Distribuidoras y Casa (pudimos haber usado clases distintas para cada una y aprovechado el polimorfismo, pero no fue el caso). Al construir árboles, usualmente se instancia un nodo inicial (la raíz) y a través de este nodo se puede acceder al árbol completo; y posteriormente se agregan más hijos. Como todos los nodos pertenecen a la clase `Instalacion`, es necesario hacer múltiples casos dentro de sus métodos dependiendo del tipo de instalación con que estamos trabajando. No es lo mismo agregar una instalación a una Generadora que a una Distribuidora Regional. Esta idea es general para árboles, donde todos los nodos (tanto raíz, nodos internos y hojas) tienen comportamiento similar.

En algunos casos se ve que no lograron comprender que los hijos de la Central Generadora representan sólo a los hijos directos (Distribuidoras Regionales), pensando erróneamente que contiene a todos los nodos del árbol hacia abajo (esos se llaman descendientes). Recomendamos revisar bien el material en las partes que explican la naturaleza recursiva de los árboles, ya que son estructuras que se pueden manejar fácilmente y de manera más general usando recursión que iteración, sobre todo si tenemos que trabajar con árboles cuya altura desconocemos.

Casi todos lograron implementar de manera correcta el método ```agregar_instalación```. Y los que no, fue por pequeños errores de implementación (como no verificar que la región y la comuna fueran las mismas). Por ejemplo, muchos hacían calzar la región **Y** la comuna al buscar en los hijos, cuando sólo se debía hacer calzar una de las dos, según el caso.

Aún así, muchos se quedaron pegados en este método, lo que perjudicó el tiempo que tenían para el resto de la actividad. En varios casos observamos que aún no se adopta bien la idea de **recursividad**, lo que causó que gasten mucho tiempo pensando en cómo implementar de forma recursiva o bien implementando de forma **iterativa** que parece más fácil de pensar, pero que en el caso de los árboles es más complejo.

Gran parte de los alumnos, incluyendo los que lograron completar la actividad, codificaron de forma iterativa, lo cual es **completamente válido**. Sin embargo, como hemos dicho, la estructura de árboles es naturalmente recursiva (todo nodo es a vez un árbol más pequeño con o sin hijos), entonces pensar iterativamente se puede lograr pero es más difícil de generalizar, sobre todo cuando no se conoce la altura del árbol. La recomendación para todos es que revisen la implementación recursiva de `agregar_instalacion`

Tengan cuidado cuando agregan nodos a un grafo de manera recursiva, ya que si lo agregan recursivamente a más de un hijo, pueden hacer que el nodo aparezca como hijo de distintos nodos, y la estructura deja de ser un árbol. Las condiciones que utilizan deben asegurar que cada nodo se agregar como hijo de, a lo más, un nodo.

Muchos hicieron uso de diccionarios para representar la jerarquía, como en el ejemplo de clases. Si bien, ésto no era obligatorio, sí es una buena práctica y les facilita mantener la jerarquía del árbol. Procuren analizar cómo se aprovechó el uso de diccionarios en estos ejemplos.

Al usar `if`/`elif`/`else` para el método `agregar_instalación`, en algunos casos se complican más de lo normal utilizando contadores y expresiones redundantes o muy largas, lo que lleva a un código mucho menos legible. Para evitar esto recomendamos (si es que, después de todo lo indicado `aún` quieren implementar la versión iterativa) utilizar los métodos de recorrer árboles descritos en los contenidos del curso, donde se realiza de una manera mucho más clara y ordenada utilizando _stacks_ y _queues_, lo que a su vez les permite aplicar lo aprendido en estructuras de datos _built in_.

A continuación un ejemplo de implementación de `agregar_instalacion`:
```python
def agregar_instalacion(self, instalacion):
	if instalacion.tipo == Instalacion.hijos[self.tipo]:
		self.hijos.append(instalacion)
	else:
		if instalacion.tipo == “Distribuidora Comunal”:
			distribuidora_regional = self.get_region(instalacion)
			distribuidora_regional.agregar_instalacion(instalacion)
		elif instalacion.tipo == “Casa”:
			distribuidora_regional = self.get_region(instalacion)
			distribuidora_comunal = distribuidora_regional.get_comuna(instalacion)
			distribuidora_comunal.agregar_instalacion(instalacion)

```

## `distribuir_energia`

El método ```distribuir_energia``` fue bien logrado por muchos.

En un caso hubo un error de concepto al calcular el consumo (probablemente por no leer bien el enunciado). Se entendió el ```consumo``` como la suma de los consumos de los hijos en vez de ser interpretado como el consumo del nodo mismo. El consumo total solo se consideraba para las estadísticas. 

Para el caso de este método, algunos se olvidaban de aplicar la recursividad sobre **todos** los hijos, y se limitaban a hacerlo en solo uno. No se olviden de hacer `for hijo in hijos: funcion(hijo) `. Si no hacen esto están avanzando por solo una de las ramas del árbol.

Notar que lo anterior es válido solo para este método, ya que estaba encargado de distribuir energía a todos sus hijos. En cambio, el `agregar_instalacion` solo debía ser llamado a lo más por uno de los hijos, de acuerdo a lo descrito en la sección anterior, y no por todos. Tengan muy en cuenta qué es lo que debe hacer cada método.

A continuación un ejemplo de implementación de `distribuir_energia`:
```python
def distribuir_energia(self, energia):
	cantidad_hijos = len(self.hijos)
	self.energia = energia
	for hijo in self.hijos:
		energia_hijo = (self.energia - self.consumo) / cantidad_hijos
		energia_hijo = max(0, energia_hijo)
		hijo.distribuir_energia(energia_hijo)
```

### Errores generales de programación
Recordar que al separar líneas para no pasarse del máximo de caracteres permitidos también hay reglas, como indentar la continuación de la línea larga.

En la programación muchos de los contenidos se complementan, por lo que traten de aplicar contenidos anteriores a la hora de escribir su programa. En este curso no sirve olvidar la materia recién pasada. Para ejemplificar, hay casos donde tienden a ocupar solamente y terminan escribiendo un código muy complejo que podría haber sido escrito más fácilmente usando un diccionario. Hay que aprovechar lo que el lenguaje (en este caso Python) ya nos provee. 

Cuidado al dividir por el número de hijos, puede resultar que dividas por cero.

### Dudas generales vistas durante actividad
Esto es un comentario tanto por lo visto en sus códigos como por lo visto en vivo y en directo. Recuerden que existen los **atributo de clase**. Algunos no sabían “que se puede escribir algo antes del `__init__` ”. Esto se revisó en uno de los repasos al inicio de la clase. De tener dudas, pueden buscar en Google o publiquen una _issue_, ya que son útiles para compartir valores entre distintas instancias de una clase.

Recuerden que siempre es bueno tener una idea clara de cómo se desarrolla el problema antes de empezar a programar. Escribir o dibujar los casos a considerar son buenas ideas para visualizarlo. De acuerdo a las preguntas que hicieron durante la actividad, parece que muchos empiezan a escribir código antes de entender bien el problema. 

Por lo general todo el código que se les provee tiene alguna utilidad para ustedes, en las cosas que deben implementar; intenten usarlo en las cosas que deben completar, ya que suele ahorrarles harto trabajo.

No desaprovechen las issues. No son únicamente para las tareas. Puede publicar una issue sobre un tema y eso nos permite saber que hay algún tema o contenido que no está claro y nos permite tomar medidas rápidamente. No las desaprovechen.

### Atomicidad

Si a veces están muy perdidos en cómo hacer un método/función, descompónganlo en funciones más pequeñas que hagan acciones más simples. 

Algunos implementaron el método ```resumen_sistema``` de manera correcta, pero sin crear métodos auxiliares ```contar_consumo``` y ```contar_instalaciones```. Esto está bien, pero puede ser complejo cuando el mismo método tiene que hacer muchas acciones (como contar el consumo y contar las instalaciones, cada uno de los cuales usa un algoritmo distinto). Una mejor práctica es crear métodos adicionales que se encarguen de cada caso (un método que solo cuenta consumo, y un método que solo cuenta instalaciones). De esta manera construir el método ```resumen_sistema``` se hace más sencillo, legible, y hace más fácil detectar los errores.

Recuerden que el enunciado dice que se les da total libertad para crear funciones nuevas, aparte de las obligatorias. 

### _Tip_ contra errores de importación

Al importar un módulo propio, puede que su editor de texto no lo reconozca a pesar de que todo funcionase de maravillas hace solo un momento atrás. La forma de solucionarlo es agregar un punto antes del módulo. Por ejemplo, si ```from leer_archivos import obtener_sistema``` no funciona, sólo debe quedar de la forma ```from . leer_archivos import obtener_sistema``` para más información pueden ver este [link](https://realpython.com/absolute-vs-relative-python-imports/). Esto es solo para que puedan seguir trabajando de forma tranquila. Es un error que Pycharm suele lanzar dependiendo cómo abren sus archivos.

### No subir archivos innecesarios

Hay archivos que no necesitan ser subidos a su repositorio. En general, archivos comunes que nosotros les otorgamos no necesitan ser subido ya que podemos copiarlos. Para esta actividad, éstos archivos correspondían a la carpeta ```sistemas/```, el archivo ```leer_archivos.py```, el enunciado y el ```README.md``` con la asignación de puestos de la actividad. Ojo con esto; desde ahora el buen uso de ```.gitignore``` será evaluado como parte de la nota de las tareas.

### Uso de programación funcional

Felicitaciones a quienes utilizaron programación funcional en esta actividad. ¡Sigan así!

### No alcanzar a terminar

Muchos no alcanzaron a terminar la actividad. Un importante número de alumnos dejó en blanco (o casi en blanco) los métodos ```resumen_sistema```, ```comuna_mayor_gasto``` y ```casas_insuficiencia``` (en especial los últimos dos). Es recomendable que las revisen e intenten implementarlas. Son buenos ejercicios de consultas a hacer sobre un sistema.

A pesar de que esta actividad no sea evaluada, agradecemos mucho que suban a su repositorio todo lo que lograron avanzar en la actividad. De esta manera, podemos revisar su código y entregarles un _feedback_ más completo.

No olviden que, aunque no alcancen a terminar, ¡esta es una tremenda oportunidad para practicar! La práctica hace al maestro, y todo esto en un futuro les parecerá trivial (quizás no tanto esta materia). Piensen que este ramo es bastante distinto a lo que están acostumbrados, si bien hay que leer contenido, el foco del ramo es práctico y la mejor forma de preparar sus evaluaciones es programando, programando, programando, buscando en google, programando, y documentando las cosas que van aprendiendo!

**Comment by perezpefaur** [comment]
No entiendo muy bien la parte del codigo que dice:
if instalacion.tipo == Instalacion.hijos[self.tipo]:
		self.hijos.append(instalacion)
en agregar_instalacion

**Comment by fdoflorenzano** [comment]
¡Hola @perezpefaur!
Faltó hacer referencia a esa porción, y sin contexto se entiende poco. Esa sigue la misma idea que se vio en el ejemplo durante repaso de la clase, donde guardamos en alguna estructura el orden de la jerarquía entre instalaciones. En este caso, mediante un diccionario guardado como atributo de clase (por eso `Instalacion.hijos`), se guarda cual es el tipo de instalación que se conecta directamente al tipo de la llave asociada. Es decir, `"Distribuidora Regional"` se conectan a `"Generadora"`, `"Distribuidora Comunal"` se conecta a `"Distribuidora Regional"`, etc... En código se vería algo como esto:
```python
class Instalacion:
    hijos = {
        "Generadora": "Distribuidora Regional",
        "Distribuidora Regional": "Distribuidora Comunal",
        "Distribuidora Comunal": "Casa",
        "Casa": None
    }
    def __init__(self, **kwargs):
    ...
```
¡Saludos y disculpa la demora!
