### ISSUE TITLE
Duda con TestCase test_tablero_solucionar

### ISSUE THREAD

**Issue by NicoPuc** [IIC2233/Syllabus#177]
* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ ]X Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ]X Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ]X De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

No entiendo porque el siguente tablero no es una de las soluciones permitidas para test_tablero_4x4 (tests.test_tablero_solucionar.TestSolucionar):
```
[['V2', '--', '--', 'H4'],
 ['--', 'PP', 'PP', '--'],
 ['PP', '--', 'R4', '--'],
 ['PP', '--', 'PP', 'PP']]
```
 Tampoco entiendo por que el tablero de test_tablero_3x3_sin_solucion:
```
 [
    ["--", "--", "--"],
    ["--", "R3", "--"],
    ["--", "--", "V2"],
] 
```

no tiene solucion

**Comment by Mcroquevielle** [comment]
Hola!! En el test_tablero_4x4 si te fijas R4 tiene alcance 5, cuando el máximo de celdas que puede alcanzar es 4. Por eso, no puede ser solución.
Después, si intentas solucionar el tablero 3x3, vas a ver que no hay manera ya que te quedarían más de 2 peones juntos (para que R3 tenga alcance 3), que no se puede según la Regla 3.
