### ISSUE TITLE
Sobreposición aliens-perro

### ISSUE THREAD

**Issue by nicolasgarciaes** [IIC2233/Syllabus#177]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda con respecto a quien debe ir sobre quien, en particular, entre los aliens y el perro, tengo entendido que los aliens deben ir por detrás de la mira y del disparo efectuado en caso de que acertar, pero no se si deben ir también por detrás del perro.

**Comment by Emiliax16** [comment]
Hola @nicolasgarciaes ! no lo especifica el enunciado, pero podrías dejar que el _alien_ caíga por detrás del perro para mantener la consistencia de que los sprites de los _aliens_ siempre estén por detrás de los otros elementos. De todas maneras escríbelo en tu readme! Saludos 🐱
