### ISSUE TITLE
Menu desde el cual desplegar las consultas

### ISSUE THREAD

**Issue by mebruna** [IIC2233/Syllabus#177]
Desde qué menu se debe acceder para consultar los siguientes datos? Y cualquier usuario que haya iniciado sesión puede consultar estos datos o solo trader/investor?

> -  Información de usuarios: Despliega la información básica de todos los usuarios registrados en
> el sistema, es decir, nombre, apellido, agrupados por tipo de usuario.
> 
> -  Historial de matches: Despliega el historial de todos los matches realizados hasta la fecha.
> 
> - Consultar información de una moneda: despliega el nombre y código de la moneda. Además,
> debe indicar: cantidad de mercados con órdenes activas, precio actual en cada uno de los
> mercados abiertos y fecha de la última orden en cada mercado.

**Comment by Arcoirisky** [comment]
El menú lo ves tú pero, esas consultas dependen de si eres Trader/Investor o Underaged. Eso sí puedes verlo en la sección Usuarios del enunciado. Tú ves si quieres que todos vean el mismo menú pero debes cuidar que se cumplan las reglas de las acciones. Saludos y recuerda decir en el Readme tu decisión! :D
