### ISSUE TITLE
Pauta Tarea

### ISSUE THREAD

**Issue by faaceituno** [IIC2233/syllabus#177]
Hola, quería saber donde puedo ver la pauta de la tarea con las asignaciones de puntaje que el otro dia la vi pero ahora no lo encuentro :(

Gracias!

**Comment by MatiasDuhalde** [comment]
Hola!

Al parecer lo que estás buscando está en [este link](https://docs.google.com/spreadsheets/d/1SgQlv1EL57C-DoC0ldShzXupAgMnnLkaDnUwStjjRd4/edit#gid=0). Lo habíamos mandado por Canvas, así que no olviden revisar esa plataforma para avisos del curso!

Suerte con lo que queda!

**Comment by vblopez** [comment]
Hola! es esta la pauta que hay que ocupar para el readme? me confunde que la del readme de ejemplo tiene numero

**Comment by MatiasDuhalde** [comment]
Hola @vblopez 

La pauta de la tarea es la que puse en el comentario de arriba ([esta](https://docs.google.com/spreadsheets/d/1SgQlv1EL57C-DoC0ldShzXupAgMnnLkaDnUwStjjRd4/edit#gid=0)), y [esta](https://github.com/IIC2233/syllabus/tree/master/Tareas) es la base del `README.md`. Tienes que rellenar la sección de _cosas implementadas y no implementadas_ según la pauta. [Acá](https://github.com/IIC2233/syllabus/tree/master/Tareas/Ejemplos%20Readmes) hay archivos `README` de semestres pasados que puedes ocupar como ejemplo.

Ojalá eso responda tu duda c:
