### ISSUE TITLE
Diferencia entre overriding y método abstracto

### ISSUE THREAD

**Issue by mpbascunan** [IIC2233/syllabus#177]
Hola! tengo dudas respecto a los métodos abstractos porque según los contenidos estos si o sí deben ser reescritos en la clase hija, pero ¿cuál sería la diferencia entre hacer el método abstracto y simplemente hacer overriding de un método normal de la clase madre?, porque en ambos casos no se puede instanciar la clase madre por el hecho de que es abstracta. 
Por ejemplo,  func_1() es método abstracto y func_2() es uno normal, y ambos funcionan sin problemas.
![clase abstracta](https://user-images.githubusercontent.com/53798683/64449570-372b9200-d0ae-11e9-8259-2c0ac4b9a955.png)
Entonces, no me queda claro el propósito de utilizar @abstractmethod si podría hacer overrinding de func_1().

**Comment by jcechavarri** [comment]
Hola @mpbascunan !

Los *abstractmethods* son una forma de obligar a hacerle *override* a un método. Estos se utilizan como buena práctica, debido a que si no defines un método como abstracto, *python* te permitirá  crear una instancia de este aun cuando no lo hayas sobreescrito. 

siguiendo tu ejemplo, si corremos este código en el cual se nos olvidó definir `func_2`:

![image](https://user-images.githubusercontent.com/42159312/64454335-b45c0480-d0b8-11e9-91e1-903fb53ed6a2.png)

Podemos ver que no arrojó ningún error, pero pasó algo que no esperábamos (entramos a una parte dónde no deberíamos haber llegado).

![image](https://user-images.githubusercontent.com/42159312/64454359-c76ed480-d0b8-11e9-83db-87c829a75419.png)


Ahora, si se nos olvida definir el método abstracto  `func_1`:

![image](https://user-images.githubusercontent.com/42159312/64454538-3ba97800-d0b9-11e9-8c07-62b207987e12.png)

Vemos que no nos deja instanciar la clase debido a que se nos olvidó el método.

![image](https://user-images.githubusercontent.com/42159312/64454631-77444200-d0b9-11e9-9bcb-1d065f65006d.png)

Acá puedes ver que si bien al hacer que una clase herede de `ABC`, prohíbes que esta sea instanciada, no estás prohibiendo que una clase hija de esta herede correctamente los métodos. Al definirlos con `abstractmethod` lo que haces es prohibir instanciar la clase a menos de que se le haga *override* al método.

Espero haberte ayudado! 😄

**Comment by mpbascunan** [comment]
Entonces si hago una clase abstracta ¿es obligación que todos sus métodos sean abstractos para que no puedan ser instanciados por una clase hija?

**Comment by jcechavarri** [comment]
No, tu clase abstracta podría tener métodos que son comunes para todas las clases hijas. En ese caso no es necesario hacer *override* de este método y por lo tanto no es necesario definirlo como `abstactmethod`. Te dejo otro ejemplo:

![image](https://user-images.githubusercontent.com/42159312/64479388-8d6b0480-d184-11e9-967f-794d6c69d7c2.png)


Como puedes ver, cada animal (en este ejemplo) come de la misma manera, pero habla distinto. Por esto, definimos `hablar` como un *abstractmethod* para obligar que este método sea sobreescrito.

**Comment by mpbascunan** [comment]
Ahora sí me quedó super claro 😄, muchas graciaas!

**Comment by burgosibarra** [comment]
Puede una clase abstracta tener properties comunes?
desde ya, muchas gracias

**Comment by jcechavarri** [comment]
Hola @burgosibarra !
Si pueden tener, properties comunes! Es igual que con los atributos y métodos! :smiley:
