### ISSUE TITLE
Crear un método nuevo 

### ISSUE THREAD

**Issue by magdafernandez** [IIC2233/Syllabus#178]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!, dentro de la tarea puedo crear un método nuevo?, es para no tener que repetir una parte del código varias veces

gracias!

**Comment by Benjeeeh** [comment]
Hola!
Si, eres libre de crear los métodos que creas convenientes! Lo que si tienes que respetar es la no modificación de los métodos ya existentes y que se indiquen que no debes modificar, además de no agregar más argumentos.
Adjunto lo que menciona el enunciado:
![IMG_6899](https://github.com/IIC2233/Syllabus/assets/78326186/5b23a0ff-1d70-40da-b5e8-ccec7291351f)

Saludos y éxito con la tarea!

**Comment by mariapazmunoz** [comment]
Hola! En el readme debo comentar estos nuevos métodos creados? Que en la estructura había una parte dedicada a librerías creadas por uno. Si es así lo indico en esa parte o al no ser librerías es en otro lado?
