### ISSUE TITLE
Añadir sprites

### ISSUE THREAD

**Issue by Chumi-sun** [IIC2233/Syllabus#178]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Duda:

Entendí que la carpeta sprites no se sube. Pero eso me causa una duda, si yo quisiera agregar un fondo en la ventana principal, específicamente de un png del espacio exterior que me gusta, entonces no lo podría hacer no? O puedo subir la imagen en otra carpeta? Dentro de eso mismo, tampoco podría cambiar yo los sprites de los aliens por otros sprites y subir esos sprites también en una carpeta?

**Comment by Emiliax16** [comment]
Hola @Chumi-sun ! lo que se suele hacer es crear una carpeta nueva (a la misma altura de la carpeta sprites y sonidos) que se llame **extras** y contenga los sprites extras que te gustaría incluir . Esta carpeta **NO** debe ser ignorada, sino tu tarea no correrá por problemas de path. Por otro lado, la carpeta sprites y sonidos si debe ser ignorada.  Recuerda que puedes agregar sprites siempre y cuando sean opciones extras y **no reemplacen** a los sprites que debe usarse por enunciado. Coloca una descripción de la carpeta extras y su contenido en tu readme, saludos!
