### ISSUE TITLE
Tasa de muerte

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#178]
En el enunciado sale que la probabilidad de una persona de morir está definida por la tasa de mortalidad.
Mi pregunta es ¿Que tasa? ¿Como la saco? ¿Es el promedio de gente que muere por dia desde que empezó la infección en ese país?

En las estadísticas sale que hay que mostrar la tasa de mortalidad y de vida del dia y el acumulado. ¿Por dia se refiere a un promedio por hora en ese día? ¿y acumulado a un promedio por dia en todo el periodo?

**Comment by Arcoirisky** [comment]
La Tasa de mortalidad la sacas de la tabla 4 en las instrucciones de la tarea O:!

**Comment by stephichau** [comment]
@jorgeriesco la respuesta a tu primera pregunta es lo que contestó @Arcoirisky. Con respecto a la otra, por día se refiere a lo que pasó en el dia actual y el acumulado es lo que ha pasado hasta el dia actual. Ojalá se entienda :)

**Comment by jorgeriesco** [comment]
Mi pregunta va a como hago la tasa, porque al final tasa es como un promedio, entonces me pregunto que es lo que tengo que promediar, ¿Las muertes diarias? ¿La gente muerta diaria? ¿La gente viva diaria? La gente viva por pais (promedio de eso)?

**Comment by rrhurtado** [comment]
La tasa de mortalidad describe el número de personas que han muerto por día. Puedes calcularla respecto a solo el día actual, en cuyo caso representa cuántas personas murieron en este día en particular, o utilizar todos los días hasta la fecha para así obtener la tasa acumulada.

Espero responda a la pregunta, saludos !

**Comment by djcontador** [comment]
Hola! para la tasa de vida, hay que entregar la cantidad de gente que sigue viva en ese día (gente no contagiada + gente curada) o es la tasa de gente que se a "desinfectado" con la cura?

**Comment by rrhurtado** [comment]
Para la tasa de vida debes entregar la cantidad de gente no contagiada en ese día.

**Comment by sfga** [comment]
> Para la tasa de vida debes entregar la cantidad de gente no contagiada en ese día.

@rrhurtado: Para la tasa de vida acumulada y la tasa de vida por día, ¿sus valores serían iguales?

**Comment by rrhurtado** [comment]
La tasa de vida acumulada tiene en cuenta todos los días hasta la fecha,
por tanto es distinta al valor de la tasa de vida para un día en particular.

**Comment by sfga** [comment]
> Para la tasa de vida debes entregar la cantidad de gente no contagiada en ese día.

@rrhurtado Disculpa, a lo mejor no me explique bien con la duda: Estoy considerando la "cantidad de gente no contagiada ese día" como la cantidad de gente que no se infectó, por tanto, la cantidad total de personas sanas en ese día. De considerar una tasa acumulada de vida, sería el mismo valor (duda que tengo) dado que sería la cantidad de gente que no se ha infectado hasta la fecha. 

Como me dices que no es lo mismo se me ocurren opciones: 

1. tasa acumulada como la suma de la gente sana en cada día, para cada día, hasta un día n (gente_sana_dia1 + gente_sana_dia 2 + ... + gente_sana_dia_n).
2. tasa de vida por día como la diferencia entre (población sana terminado el día) y (población infectada ese día), que da como resultado, la (gente que estaba sana antes de la "infeccion del día").

Te agradecería mucho que clarificaras este punto, dado que me cuesta entender el cálculo que están solicitando.

**Comment by acrojas2** [comment]
Me nació una duda respecto a este punto del enunciado, puesto que de las instrucciones se puede desprender que podemos elegir si calculamos la tasa de vida y muerte acumulada o las del día (porque dice "o" y no "y").  Puedo elegir cuál elegir y especificarlo en el README (?).

**Comment by arturodelreal** [comment]
@acrojas2 debes implementar ambas funcionalidades.

**Comment by nivek0o0** [comment]
¿ Es tasa de muerte y tasa de vida (no contagiados)  o tasa de vida y tasa de infecciones como dicen en la issue #249 ?
