### ISSUE TITLE
Pueden dos excavadores encontrar el mismo item en la arena?

### ISSUE THREAD

**Issue by SuperFunnyShark1** [IIC2233/Syllabus#178]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

La arena tendrá una cierta cantidad de items que podrán ser encontrados por un excavador , cuando esto ocurre, **ese item debe ser eliminado de la lista de items contenidos por la arena?**

**Comment by PipeXtz** [comment]
Hola @SuperFunnyShark1 !

En cada arena se pueden encontrar todos los ítems entregados en los archivos csv, luego de determinar el tipo, se escoge uno aleatoriamente dentro del tipo que salió.

Sobre si se van eliminando de la arena, esto no está especificado en el enunciado, así que queda a tu criterio cómo lo manejas y colócalo en el readme. Todo esto mismo se habló en la issue #167 para que la revises. 

Un ejemplo válido o es que sí se puedan ir repitiendo, ya que nada evita que la arena tenga varias veces el mismo objeto, y así tampoco sería necesario ir borrando los que ya salieron. En cambio, si haces que se elimines, tienes que tener ojo con que no te quedes sin objetos.

Espero que te haya quedado claro, quedo atento.

**Comment by tremendapithon** [comment]
Hola buenas madrugadas, entonces el equipo puede tener items repetidos, siempre cuando yo especifique eso en le readme.md??

**Comment by PipeXtz** [comment]
Hola @tremendapithon !

Efectivamente, tú ves como lo manejas, si quieres que la arena tengs los objetos más de una vez y que se pueda sacar más de 1 vez el mismo objeto se puede hacer, solo especifícalo en el readme. 

Para que no se te sature tanto, te recomiendo darle atención a los valores de los parámetros.

Espero haya quedado claro!
