### ISSUE TITLE
PEP8: nombre de variable en función

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#178]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Es legal (en pep8) aquí utilizar los nombres no descriptivos que están en los parámetros (ma, mo, a, c, k)?
![image](https://user-images.githubusercontent.com/66154723/113493627-718e2880-94b7-11eb-8a40-7d41e104e424.png)

**Comment by pabloist** [comment]
Hola :)

Te comento que todos los nombres de variables que son definidos (incluso aquellos de alguna clase o método) deben ser descriptivos, pudiéndose considerar en caso contrario, el descuento correspondiente. Recordemos que la idea de utilizar PEP8 es mantener claridad en el código, ya sea tanto para uno mismo como para otros programadores que pudieran utilizarlo (o en nuestro caso, evaluarlo).

Saludos!

**Comment by fernandosmither** [comment]
> Hola :)
> 
> Te comento que todos los nombres de variables que son definidos (incluso aquellos de alguna clase o método) deben ser descriptivos, pudiéndose considerar en caso contrario, el descuento correspondiente. Recordemos que la idea de utilizar PEP8 es mantener claridad en el código, ya sea tanto para uno mismo como para otros programadores que pudieran utilizarlo (o en nuestro caso, evaluarlo).
> 
> Saludos!

Muchas gracias!, lo preguntaba porque era un ejemplo del _notebook_. Solucionado!
