### ISSUE TITLE
Archivos entregados

### ISSUE THREAD

**Issue by smoralesw** [IIC2233/syllabus#178]
Hola, existe algún inconveniente si los archivos entregados (particularmente el de posts) están en un orden distinto al original, pero manteniendo el formato y con los cambios correspondientes bien hechos?

**Comment by gatochico** [comment]
Hola! Al momento de corregir tu tarea, no probaremos el código con los archivos `.csv` que subas a tu repositorio, sino que con una copia de los originales del syllabus. Si tu código funciona sin problemas con estos archivos, no hay problema con que tu tarea los edite cambiándoles el orden. (siempre y cuando el formato se mantenga y los cambios estén buenos, por supuesto :eyes:)

Espero haber respondido tu duda!

**Comment by smoralesw** [comment]
Oka, gracias
