### ISSUE TITLE
Recorreción y sugerencias de esta

### ISSUE THREAD

**Issue by tomasrodriguez1** [IIC2233/Syllabus#178]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Es necesario incluir la materia vista en **TODA LA TAREA**?

En la corrección del avance, él o la ayudante me recomendó usar cierto material para algunas clases (usar clases abstractas, entre otros). Sin embargo, yo solo lo ocupe una vez ya que es lo que piden. Si es que puedo hacer bien el juego, es decir, funciona bien sin la necesidad de este contenido ¿Esta bien que lo deje así y no implemente los contenidos en todo el juego? 
Según lo que tengo entendido, el programa se hace bajo la comodidad de uno, siempre y cuando cumpla con los requisitos de la pauta. Cabe destacar que no quiero ser mal agradecido con la recomendación, sino que me inquietó ya que en la pauta sale lo que yo plantié.

**Comment by Emiliax16** [comment]
Hola @tomasrodriguez1 ! efectivamente el enunciado dice que los contenidos mínimos se deben ocupar al menos una vez y **debes descubrir donde implementarlos según el enunciado**. Por esto, basta con implementar todo una vez, pero debes leer muy entidades y poder relacionarlas de forma correcta, de tal manera que sepas donde implementar cada contenido. Se evalua que cada entidad esté bien modelada. 

En resumen, la tarea podría tener varias veces implementados los contenidos mínimos, no sólo una vez, pero queda a tu criterio si lo implementas solo una vez  en las clases que se esperan encontrar. Quizás la recomendación de tu ayudante fue una señal de que cierta clase requiera ese contenido en específico, pero si ya lo implementaste y consideras que está bien y era lo esperado según el enunciado, deberías estar bien, ya que es normal que se modelen las cosas de manera diferente mientras no se caiga en malas prácticas.
Espero haber aclarado tu duda. Saludos! 😺
