### ISSUE TITLE
Duda con herencia de list (contenidos 02- 3)

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#178]
Hola! Tengo una duda con respecto a los contenidos de la semana 2 `3-herencia`. En una parte del notebook aparece esto:
![image](https://user-images.githubusercontent.com/68198662/91219135-2b364700-e6e8-11ea-884c-2b436e8cc71c.png)

Entiendo que se está creando una subclase a partir de la clase `list`, que queremos tener los mismos métodos de listas de siempre y agregarle uno nuevo. Lo que no entiendo es por qué no se está incluyendo el característico `__init__` de las clases. En los ejemplos anteriores del notebook cuando una clase heredaba los atributos de otra invocábamos al inicializador de la super clase, pero en esta subclase ni siquiera se hace mención de este. ¿Por qué no es necesario ponerlo?
¿Tiene algo que ver con que la clase de la cual estamos heredando es un `built in`?
¿Como reconoce python que atributos tiene esta subclase?

Muchas Gracias si llegaste hasta acá 😃

**Comment by MatiasDuhalde** [comment]
Hola @Gsalinas1506 !

Te pongo un ejemplo bien sencillo:
```python
class ClaseA:
    def __init__(self, atributo):
        print("ME ACABAN DE INICIALIZAR")
        self.atributo = atributo

class ClaseB(ClaseA):
    def metodo_extra(self):
        print("Este es un método extra")
        print("Este es mi atributo:", self.atributo)

if __name__ == "__main__":
    objeto = ClaseB(12345)
    objeto.metodo_extra()
```
Output:
```
ME ACABAN DE INICIALIZAR
Este es un método extra
Este es mi atributo: 12345
```
Aquí, creamos una ClaseA (con el `__init__` definido), y creamos una ClaseB que hereda de ClaseA, y agrega un método (`metodo_extra`). Dado que en ClaseB no redefinimos ni redeclaramos el `__init__`, se hereda (es decir, se mantiene) el que ya estaba definido dentro de ClaseA.

Pasa básicamente lo mismo con el ejemplo de los contenidos, `ContactList` hereda de `list`, pero dado que `ContactList` no redefine el método `__init__`, hereda (mantiene) el `__init__` proveniente de `list`. Dado que no queremos modificar de ninguna manera el `__init__` de la clase madre, no necesitamos redeclararlo. Respondiendo a tu pregunta, de esta manera reconocería Python los atributos que posee la clase hija.

Cabe destacar que esto no solo funciona con los métodos especiales como `__init__`, sino que con cualquier método que la clase madre posea.

**Comment by Gsalinas1506** [comment]
Ahhh perfecto, entendí. Muuuchas gracias
