### ISSUE TITLE
Autoevaluación AC03

### ISSUE THREAD

**Issue by eugeizquierdo** [IIC2233/syllabus#178]
Hola!! 
No me ha llegado ningún mail para contestar la autoevaluación de la Actividad 3. Será via mail, o donde la puedo encontrar?

Gracias!

**Comment by entamburini** [comment]
Hola @eugeizquierdo, 

El link para la autoevaluación, está disponible en la página final del enunciado de la actividad. Por eso no hay aviso al respecto :wink:

Que tengas buen finde! :man_dancing:
