### ISSUE TITLE
DFS vs BFS

### ISSUE THREAD

**Issue by isihirmas** [IIC2233/syllabus#178]
Hola! Revisando el segundo contenido de la semana 6, no me queda claro el programa para dfs que se muestra ahí. Al dibujarlo en papel y hacer el "recorrido" con un lápiz para el dfs se ve como se revisan todos los hijos primero, lo que sería bfs y no dfs. 
Comparando los códigos se ve que el dfs utiliza pop(), que saca el último de los vecinos, y el bfs utiliza popleft(), que saca el primero. Mi pregunta es que no entiendo cómo esa diferencia en el código hace que se pueda recorrer de distinta manera, porque al dibujarlo no lo logré ver.
Perdón lo largo, gracias de antemano!

**Comment by Hernan4444** [comment]
¡Hola!

¡Que buena pregunta! a mi también me costó en su momento entenderlo. Para esto haremos un ejemplo paso a paso, lo cual creo que es la mejor forma de entender las diferencias (o la mejor que se me ocurre c: ). Primero debemos recordar que a medida que uno recorre un grafo, va guardando en una cola los vecinos del nodo que está visitando. Dado esto ¿que diferencia produce sacar el primero elemento al último de dicha cola? Digamos que tenemos estas relaciones:

* Hernán es amigo de Fernando, Hugo y Felipe
* Felipe es amigo de Fernando
* Hugo es amigo de Felipe y Nicolas
* Fernando es amigo de Nicolas
* Nicolas es amigo de Felipe, Hernán y Hugo
* **Importante**: Esto es solo a modo de ejemplo, cualquier parecido con la realidad es pura coincidencia. 
 
Dadas estas relaciones, podemos decir que los nodos son: Hernán, Fernando, Hugo, Felipe y Nicolas. Y los vecinos de cada uno son:
```python
Hernán.vecinos = [Fernando, Hugo, Felipe]
Hugo.vecinos = [Felipe, Nicolas]
Fernando.vecinos = [Nicolas]
Felipe.amigos = [Fernando]
Nicolas.vecinos = [Felipe, Hernán, Hugo]
```

## Apliquemos **DFS** Desde Hernán
1. La cola empieza con Hernán y el set de visitados vacío.
    a. `deque=[Hernán]`
    b. `visitados=set()`

2. Se saca el último de `deque` (Hernán), **lo ingresa al set de visitados** y agrega todos los vecinos de Hernán al final de la `deque` (Fernando, Hugo, Felipe).
    a. `deque=[Fernando, Hugo, Felipe]`
    b. `visitados=set(Hernán)`

3. Se saca el último de `deque` (Felipe), **lo ingresa al set de visitados ** y agrega todos los vecinos de Felipe al final de la `deque` (Fernando).
    a. `deque=[Fernando, Hugo, Fernando]`
    b. `visitados=set(Hernán, Felipe)`

4.  Se saca el último de `deque` (Fernando), **lo ingresa al set de visitados** y agrega todos los vecinos de Fernando al final de la `deque` (Nicolas).
    a. `deque=[Fernando, Hugo, Nicolas]`
    b. `visitados=set(Hernán, Felipe, Fernando)`

5. Se saca el último de `deque` (Nicolas), **lo ingresa al set de visitados** y agrega todos los vecinos de Nicolas al final de la `deque` (Felipe, Hernán, Hugo).
    a. `deque=[Fernando, Hugo, Felipe, Hernán, Hugo]`
    b. `visitados=set(Hernán, Felipe, Fernando, Nicolas)`

6. Se saca el último de `deque` (Hugo), **lo ingresa al set de visitados** y agrega todos los vecinos de Hugo al final de la `deque` (Felipe, Nicolas).
    a. `deque=[Fernando, Hugo, Felipe, Hernán, Felipe, Nicolas]`
    b. `visitados=set(Hernán, Felipe, Fernando, Nicolas, Hugo)`

7. Se saca el último de `deque` (Nicolas), pero este ya está en `visitados` (lo vimos en 5). No se hace nada.
    a. `deque=[Fernando, Hugo, Felipe, Hernán, Felipe]`
    b. `visitados=set(Hernán, Felipe, Fernando, Nicolas, Hugo)`

8. Se saca el último de `deque` (Felipe), pero este ya está en `visitados` (lo vimos en 3). No se hace nada.
    a. `deque=[Fernando, Hugo, Felipe, Hernán]`
    b. `visitados=set(Hernán, Felipe, Fernando, Nicolas, Hugo)`

9. Notar que esto pasará también con Hernán, Felipe, Hugo y finalmente Fernando porque los 4 están en `visitados`.

El orden de ver los nodos desde Hernán fue: `set(Hernán, Felipe, Fernando, Nicolas, Hugo)`. Aquí se puede ver que Hugo, amigo de Hernán, fue visto después que Nicolas, quien no es amigo de Hernán, es decir, no se partió viendo todos los vecinos de Hernán al Inicio.

## Apliquemos **BFS** desde Hernán

Pondré de nuevo los vecinos de cada nodo para no tener que hacer scroll.
```python
Hernán.vecinos = [Fernando, Hugo, Felipe]
Hugo.vecinos = [Felipe, Nicolas]
Fernando.vecinos = [Nicolas]
Felipe.amigos = [Fernando]
Nicolas.vecinos = [Felipe, Hernán, Hugo]
```
1. La cola empieza con Hernán y el set de visitados vacío.
    a. `deque=[Hernán]`
    b. `visitados=set()`

2. Se saca el primero de `deque` (Hernán), **lo ingresa al set de visitados** y agrega todos los vecinos de Hernán al final de la `deque` (Fernando, Hugo, Felipe).
    a. `deque=[Fernando, Hugo, Felipe]`
    b. `visitados=set(Hernán)`

3. Se saca el primero de `deque` (Fernando), **lo ingresa al set de visitados** y agrega todos los vecinos de Fernando al final de la `deque` (Nicolas).
    a. `deque=[Hugo, Felipe, Nicolas]`
    b. `visitados=set(Hernán, Fernando)`

4. Se saca el primero de `deque` (Hugo), **lo ingresa al set de visitados** y agrega todos los vecinos de Hugo al final de la `deque` (Felipe, Nicolas).
    a. `deque=[Felipe, Nicolas, Felipe, Nicolas]`
    b. `visitados=set(Hernán, Fernando, Hugo)`

5. Se saca el primero de `deque` (Felipe), **lo ingresa al set de visitados** y agrega todos los vecinos de Felipe al final de la `deque` (Fernando).
    a. `deque=[Nicolas, Felipe, Nicolas, Fernando]`
    b. `visitados=set(Hernán, Fernando, Hugo, Felipe)`

6. Se saca el primero de `deque` (Nicolas), **lo ingresa al set de visitados** y agrega todos los vecinos de Nicolas al final de la `deque` (Felipe, Hernán y Hugo).
    a. `deque=[Felipe, Nicolas, Fernando, Felipe, Hernán, Hugo]`
    b. `visitados=set(Hernán, Fernando, Hugo, Felipe, Nicolas)`

7. Se saca el primero de `deque` (Felipe), pero este ya está en `visitados` (lo vimos en 5). No se hace nada.
    a. `deque=[Nicolas, Fernando, Felipe, Hernán, Hugo]`
    b. `visitados=set(Hernán, Fernando, Hugo, Felipe, Nicolas)`

7. Se saca el primero de `deque` (Nicolas), pero este ya está en `visitados` (lo vimos en 6). No se hace nada.
    a. `deque=[Fernando, Felipe, Hernán, Hugo]`
    b. `visitados=set(Hernán, Fernando, Hugo, Felipe, Nicolas)`

9. Notar que esto pasará también con Fernando, Felipe, Hernán y finalmente Hugo porque los 4 están en `visitados`. 

El orden de ver los nodos desde Hernán fue: `[Hernán, Fernando, Hugo, Felipe, Nicolas]`. Podemos ver que iniciamos viendo a Hernan y a todos sus amigos en el mismo orden que él los tiene, luego terminamos con Nicolas porque este era amigo de Fernando, pero no de Hernán.

Espero que este ejemplo haya servido de guía para diferenciar como hacer `pop` y `popleft` cambia el orden en que se recorre el grafo 😄.

Cualquier consulta, no dudes en hacerla en esta issue o en otra para seguir ayudando en tu estudio.
Saludos ✌️

**Comment by isihirmas** [comment]
Me sirvió muchísimo! Muchas gracias! :)
