### ISSUE TITLE
Menus con clases

### ISSUE THREAD

**Issue by raimundoloeser** [IIC2233/syllabus#179]
Con respecto a los menus, si quiero llamar dentro de un menu (ejemplo, menu principal) un metodo de otro menu (ejemplo recibir_input de menu de CompraVehiculo)  debo tener todos los menus instanciados? o es mas eficiente dentro del metodo "comprar_vehiculo" instanciar el menu de CompraVehiculo y ahi llamar el metodo?

**Comment by SamWeinstein** [comment]
Tengo la misma pregunta! Pues dentro del MenuPrincipal existe el metodo de comprar_vehiculo(), pero como comprar un vehiculo se hace mediante su propio menu, tambien existe la clase MenuCompra, y no se bien como manejar esto. Debe instanciarse el menu de compra dentro del metodo de comprar_vehiculo? o será mejor escribir todo el menu dentro del metodo y no hacer una clase nueva? esto ultimo se puede hacer para el bonus o tengo que hacer el menu de compra con una clase separada?

**Comment by jeschuwirth** [comment]
Hola!!

Muy buena pregunta :D 

Los menus nunca deberían tener 2 instancias de si mismos al mismo tiempo, ya que para esta tarea nunca vas a estar en 2 menus concurrentemente.

Por esta razón te recomiendo fuertemente tener una clase Juego que tenga como atributos todos los menus y que maneje correctamente el flujo de ellos. En el ejemplo de @SamWeinstein, tu menu de sesion (donde creas tu piloto) deberá moverte al menu de compra vehículo, donde podrás comprar el primer vehículo de ese piloto.

El problema que tiene instanciar el menu de compra dentro del menu de sesion, es que puedes crear un loop muy grande de menus dentro de menus, este ejemplo se ve muy claro entre los menus de parada pits y carrera.

El menú carrera imprime la primera vuelta, luego el jugador entra a los pits y se crea el primer menu de pits, luego el jugador vuelve a la carrera, la forma correcta sería ir al menú de vuelta ya instanciado, pero lo que proponen es crear un nuevo menu de carrera.

Un mensaje importante es que el puntaje por menus es bonus y hay muchas formas de hacerlo, los párrafos anteriores son recomendaciones y cosas en las que tienen que tener cuidado, pero no son obligatorias, por lo que el ayudante les entregará el puntaje de todos modos si lo deciden hacer de otro modo que también esté correcto.

Si tienen dudas pueden seguir comentando, pero recuerden que la idea de ese bonus es que practiquen hacer menus de manera correcta y entiendan porque es una buena práctica separarlos.

Suerte !

**Comment by raimundoloeser** [comment]
Voy a seguir con eso de la clase juego! pero de igual manera tengo que instanciar los menus antes de instanciar el juego (para poder agregarlos como atributos)
gracias

**Comment by burgosibarra** [comment]
Hola!
Para conseguir el bonus de Clases y seguir las reglas de la tarea
Puedo llamar desde una clase (Menú) a una función que este en una archivo "archivocualquiera.py"
O necesariamente las funciones que se apliquen dentro de la clase deben ser métodos de la clase?
