### ISSUE TITLE
Mi código funciona en VS, pero no cumple con los tests

### ISSUE THREAD

**Issue by FrancoMedalla** [IIC2233/Syllabus#179]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Qué tal?
He ido probando mi código en Visual Studio con ejemplos arbitrarios como los que aparecen en los tests y funciona correctamente, sin embargo, me aparece error en los tests al correrlos. Intenté verificar lo que arrojaban, pero los resultados en VS y en estos difieren. Adjunto fotos de la terminal VScode/cmd, al correr test_00_crear_plano.
![captura dccultivo](https://github.com/user-attachments/assets/60ccc3ae-ba20-41ae-9a1c-4a4d003f9929)
En esta imagen se ve que llegué hasta la función eliminar cultivo y todo funcionó bien. También he corroborado que funcionen los planos de riego.
![terminal dccultivo](https://github.com/user-attachments/assets/ff6988b8-a7c6-4ec5-8e1b-73873c062f6d)
En esta imagen se muestra que el plano ni siquiera se crea con la función crear_plano. Tampoco aprueba el test_1_plantar, por ejemplo.

Agradecería mucho que me ayuden a entender lo que pasa, ya que no sé si el código está mal.

**Comment by FrancoMedalla** [comment]
Acabo de leer una Issue igual a esta que no había notado, sin embargo, quien la escribió resolvió el problema por sí mismo, entonces no puedo resolver mi duda jajajajaj. Muchas gracias de antemano.

**Comment by Johan-10** [comment]
¿Revisaste que si entregaste el **return** como era?, explico en una issue que tenia (la #165) me apareció ese mismo error de "result[0]=func(*args,**kwargs)" y resulto que el error se basaba en que esta printenado el resultado desde el mismo método cuando en verdad la función debía era retornar ese resultado y no hacer nada mas.

**Comment by FrancoMedalla** [comment]
Hola! Sí, efectivamente no printeo y hago return. Incluso creo que el return de self.plano está de sobra, pero bueno, al menos se descarta ese error. Te agradezcoo igual!

**Comment by FrancoMedalla** [comment]
Ya ví que pasaba jajajajajaj. Al final tuve que chequear el enunciado y me di cuenta que estuve trabajando tanto el menú como la definición de funciones en main.py. Así, cuando el test importaba las funciones desde dccultivo.py estas no estaban desarrolladas.
