### ISSUE TITLE
Consulta: condieración de properties

### ISSUE THREAD

**Issue by BenjaMedinaPUC** [IIC2233/Syllabus#179]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! esperando que se encuentren bien el día de hoy quería preguntar sobre lo siguiente ¿como van a considerar que las propertyes que solicitan en las tareas estén correctas por el alumno? que cumplan con los test y la sintaxis correspondiente (@property) o que tenga uno crear un atributo a la clase que se debe actualizar con la funcionalidad de @getter y @setter a la función pedida? Estaré atento a su repuesta :)

**Comment by mtaguero** [comment]
¡Hola @BenjaMedinaPUC!

Se considerará todo lo mencionado. Testcases, sintaxis correspondiente y `@getter` y `@setter` según corresponda.
Confirmame si esto soluciona tu duda o si tienes alguna otra relacionada al tema.

¡Éxito! 🎈

**Comment by BenjaMedinaPUC** [comment]
Pero es necesario crear el atributo dentro la clase (en el __init__) para las funciones que me piden usar property o ya definiendo la funcion como property y retorne lo pedido ya se considera que estoy usando las properties?

**Comment by mtaguero** [comment]
Ya terminó el plazo para la tarea, perdón :( Aún así, te responderé.

Ambas opciones podrían a llegar a ser válidas según la construcción de la clase, sin embargo, lo que se hace en general es lo segundo que mencionas: definir métodos con el decorador `@property` directamente en la clase, ya que es más concisa y es más común de ver en Python.

Espero que lo hayas logrado solucionar.

¡Mucho éxito! 🎈
