### ISSUE TITLE
¿Existe algún método para usar la inversa de una función que yo definí?

### ISSUE THREAD

**Issue by tcouso** [IIC2233/syllabus#179]
Por ejemplo, F(x) toma un str de cierto formato A y retorna una lista en un formato B, quiero una función F^-1(x) que tome una lista de formato B y retorne un str en formato A.

**Comment by MatiasDuhalde** [comment]
Hola!

En general, **no, no hay una forma simple de pasarle el return a una función y que te devuelva un parámetro**. Las funciones en Python son muy distintas a una función matemática. El intérprete no tiene cómo saber si la función que intentas invertir es biyectiva o si cumple cualquier otra propiedad que haría a la función "invertible".

Imagina una función a la que le pasas un número y te retorne `True` si es par y `False` si es impar. Si le pasas cualquier número obtendrías un resultado lógico (`True` o `False`), pero si intentas el procedimiento inverso (ejemplo, darle `True` a la función inversa como argumento) ¿cómo sabría Python que número entregarte de vuelta?

Ahora, volviendo a tu pregunta, **la única opción sería definir otra función que haga el procedimiento inverso paso por paso**.

Ojalá eso responda to pregunta y suerte con tu tarea :)
