### ISSUE TITLE
Radio de alcance Bomba Cruz

### ISSUE THREAD

**Issue by jarvasquez** [IIC2233/syllabus#179]
Hola!

En el enunciado para describir el alcance de esta bomba es de la siguiente manera:

con r = 4
_________________
|  _  _  _ X _  _  _ |
|  _  _  _ X _  _  _ |
|  _  _  _ X _  _  _ |
| X  X X X X X X |
|  _  _  _ X _  _  _ |
|  _  _  _ X _  _  _ |
|  _  _  _ X _  _  _ |
------------------

Pero no se puede apreciar si la bomba sigue (pero no se muestra porque está fuera del tablero) o si la bomba tiene efectivamente ese radio.

Gracias!

**Comment by MatiasDuhalde** [comment]
Hola @jarvasquez !

Tienes razón, esto pudo haber dado lugar a ambiguedades. Recuerda que una bomba especial de r = 1 es "puntual", y cada aumento en el radio agregaría una casilla hacia afuera. Por lo tanto, en la imagen del enunciado, la bomba de r = 4 no se saldría del tablero, sino que calzaría justo. Te pongo un ejemplo con un tablero más grande para que quede más claro:
```python
| _ _ _ _ _ _ _ _ _ |
| _ _ _ _ X _ _ _ _ |
| _ _ _ _ X _ _ _ _ |
| _ _ _ _ X _ _ _ _ |
| _ X X X X X X X _ |
| _ _ _ _ X _ _ _ _ |
| _ _ _ _ X _ _ _ _ |
| _ _ _ _ X _ _ _ _ |
| _ _ _ _ _ _ _ _ _ |
```

Ojalá esto aclare un poco las cosas :)

**Comment by jarvasquez** [comment]
Perfecto! Muchas gracias!
