### ISSUE TITLE
Estrella de la muerte y bomba de hielo

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#179]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
La estrella de la muerte dice que puede aparecer en cualquier parte del nivel, pero no menciona cuando. ¿Aparece al comienzo del nivel hasta que se acabe su tiempo? ¿O puede aparecer en cualquier momento? ¿Puede aparecer sólo una vez por nivel o puede hacerlo varias veces en uno?

Las mismas dudas tengo con la bomba de hielo, ya que tengo entendido que su aparición funciona de manera similar.

**Comment by nzamorano** [comment]
Hola @MaxAl100, en el enunciado se dice que la _Estrella de la Muerte_ puede aparecer en **cualquier** parte de la partida (tanto en la ventana como en algún momento aleatorio del nivel). Respecto a lo segundo, como no se menciona en el enunciado queda a criterio suyo, mientras lo escriban en el **readme**. Como sugerencia, podrían hacerlo de la misma manera que la _Bala Dorada_, pero es decisión suya.

La _Bomba de Hielo_ funciona de igual forma.
