### ISSUE TITLE
Guardar balance de los usuarios

### ISSUE THREAD

**Issue by jvlara** [IIC2233/Syllabus#179]
Hola, lo que pasa es que debido a que todas las operaciones son realizadas con Decimal al guardar el diccionario donde tengo las monedas con sus respectivas cantidades hay monedas con muchos decimales, ¿que debería hacer en este caso?, debido a que guardarlas truncaría a los números 27 dígitos después de la coma.

**Comment by Arcoirisky** [comment]
No está especificado en el enunciado, ve tú como abordas el problema y mencionarlo en el Readme :D Ánimo y Suerte <3
