### ISSUE TITLE
Como se que items tiene una arena

### ISSUE THREAD

**Issue by benjalvear** [IIC2233/Syllabus#179]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [si ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ si] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ si] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ si] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ si] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ si] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ si] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Como puedo saber que items tiene cada arena? o cada arena tiene todos los items que nos entregan?.
 Cuando un excavador encuentra un item, ese item desaparece de la lista de items o sigue estando ahi?
Muchas gracias por la respuesta!

**Comment by PipeXtz** [comment]
Hola @benjalvear  !

Te invito a revisar las issues #178 y #167, que hablan exactamente de esto resolviendo las preguntas que haces. En resumen, puedes encontrar todos los objetos en la arena, y si se van eliminando queda a tu criterio, solo especifícalo en el readme.

Espero haya quedado claro, quedo atento.
