### ISSUE TITLE
Consulta entrega README.md

### ISSUE THREAD

**Issue by mblejeune** [IIC2233/Syllabus#179]
Hola! Tengo una duda con respecto a subir el archivo README, como debe ser entregado dentro de la carpeta T01, y esta contiene además los archivos python, entre otros, que fueron subidos correctamente a tiempo. Debo hacer git add, commit y push de toda la carpeta T01 o es recomendable hacer esto con la direccion de ... /T01/README.md ? De hacerlo de la primera forma, ¿importa si se actualiza la tarea 1? Yo creo que no ya que ya fue recolectada pero de todas maneras quiero asegurarme. Gracias!!

**Comment by cilopez** [comment]
Las tareas ya fueron recolectadas así que si lo subiste como señalas al final no hay problemas, en el caso contrario ojalá agregues con la dirección del README.

**Comment by mblejeune** [comment]
eso hice al final! subirlo con la direccion de README, muchas gracias!!!
