### ISSUE TITLE
Duda ejercicios 3.2 Rockgramación Avanzada 

### ISSUE THREAD

**Issue by Piolawa** [IIC2233/syllabus#179]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, al imprimir el tipo de clase, sugieren usar type(instancia)__name__ , no logro entender como usarla, porque la instancia se crea afuera de la clase entonces como la llamo para definir el tipo?

**Comment by DomingoCarvajal** [comment]
Hola @Piolawa!

Recuerda que para llamar la instancia de una clase dentro de su definición se usa la palabra "self".

**Comment by Piolawa** [comment]
Ahi si, graciaas!
