### ISSUE TITLE
Duda de enunciado y relación de este con el código

### ISSUE THREAD

**Issue by SebastianRosselot** [IIC2233/Syllabus#179]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, tengo dos dudas respecto a instrucciones del enunciado y el cómo aplicarlas.

Primero, en el enunciado, respecto a properties, herencia, clases abstractas y polimorfismo dice que "cada uno de estos elementos debe ser incluido en el programa al menos una vez, y deberás descubrir dónde implementarlos según lo propuesto por el enunciado". Esto quiere decir que, sea como sea que los implemente, si lo hago al menos una vez y mi código funciona bien, cumplo con lo expuesto? O por el contrario, hay clases y/o métodos que obligatoriamente deben ser abstractas, a pesar de que no siéndolo ejecuten correctamente su función?

Y segundo, en la parte del enunciado donde explican la entidad Programon, dice que el programon "se va a ver involucrado en las siguientes mecánicas del juego",  refiriéndose luego a la mecánica de Entrenamiento y a la de Luchar. Quiere esto decir que esas mecánicas deben implementarse como una acción desde la entidad Programon? O bastaría que los programones fueran parte de esas mecánicas sin importar donde sean implementadas?

Gracias de antemano por la ayuda :)

**Comment by Emiliax16** [comment]
Hola @SebastianRosselot ! respecto a tu primera duda, se contestó gran parte en la issue [#178](url) . Si hay clases que se espera que contengan necesariamente los contenidos mínimos, por eso debes leer bien el enunciado y descubrir donde aplicarlos.

Respecto a tu segunda pregunta, las dos mecánicas nombradas deben implementarse como una acción de la entidad programón.

Saludos!
