### ISSUE TITLE
Duda sobre uso de código encontrado en internet

### ISSUE THREAD

**Issue by Pdesolmi** [IIC2233/syllabus#18]
Encontré un codigo en stackoverflow que me ayuda para el manejo del tablero, utiliza listas por comprensión y una función lambda, puedo hacer uso del código y referenciarlo?
Gracias

**Comment by DCCollao** [comment]
Hola!

Mientras en el código que encontraste no se utilice nada [prohibido](https://github.com/IIC2233/syllabus/issues/3) en la tarea y referencies en tu `README.md` indicando el link de donde sacaste el código, para qué y dónde lo utilizaste, no deberían haber problemas. También es buena idea indicar en qué líneas y módulos usaste el código.

Éxito!
