### ISSUE TITLE
Error al instalar pyqt5-tools en macOS

### ISSUE THREAD

**Issue by sabquit** [IIC2233/syllabus#18]
Hola! Al seguir el video de instalación para pyqt5-tools, la terminal me entregó el siguiente error:

**ERROR: Could not find a version that satisfies the requirement pyqt5-tools (from versions: none)
ERROR: No matching distribution found for pyqt5-tools**

Al buscar en google se recomendaba actualizar pip, pero el error persiste. ¿Qué puedo hacer?

**Comment by tomasgv** [comment]
¡Hola @sabquit!

Lamentablemente `pyqt5-tools` no parece tener versiones compatibles con macOS por el momento 😢 . Sin embargo, solo utilizaremos `pyqt5-tools` para tener QtDesigner, aplicación que también puedes descargar desde [este link](https://build-system.fman.io/qt-designer-download) (es la página que se muestra en el video de instalación).

¡Espero haberte ayudado! 🎉

**Comment by sabquit** [comment]
Entiendo, gracias! 😋
