### ISSUE TITLE
En el csv de seguidores hay uno con una coma de más

### ISSUE THREAD

**Issue by Mendez69** [IIC2233/syllabus#18]
se la saco o es parte de la dificultad? (hace que no me corra el código)
sale:
nabenit3z,

**Comment by lily416** [comment]
@Mendez69 se acaban de actualizar los archivos, si encuentras algún otro error (esperemos que ya no queden 😭) por favor avísanos. 😉

Saludos y éxito en la tarea 👋🐦

**Comment by Mendez69** [comment]
gracias 🐛
