### ISSUE TITLE
Error: Problemas con el WSL

### ISSUE THREAD

**Issue by BenjaMedinaPUC** [IIC2233/Syllabus#18]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido
Hola! esperando que te encuentres bien, quería saber si existe la posibilidad de desinstalar el WSL y así poder hacer el procedimiento nuevamente, ya que me han surgido varios problemas y ahora finalmente no me abre el programa para poder ejecutar comandos

**Comment by Hernan4444** [comment]
Hola @BenjaMedinaPUC 

Te recomiendo revisar [esta página](https://programacionfacil.org/blog/como-desinstalar-completamente-wsl-ubuntu-en-windows-10/) donde se explican formas de desinstalar WSL. Por lo que tengo entendido, tambien debería funcionar con windows 11 (en caso que no tengas windows 10). 

Avísanos cómo te va con eso,

**Comment by BenjaMedinaPUC** [comment]
Muchas gracias! tuve que desinstalar mas programa para lograr el cometido ya que no lograba ningún cambio, como "linux for windows" y "debian" y así empezar de cero. También que en la página de Software obligatorio me confundo ya que no especifica el terminal correspondiente cuando se habla en el procedimiento.

¡que tengan un buen fin de semana!
