### ISSUE TITLE
Lecturas Actividad 16/03

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#18]
Hola!

Hasta donde tenemos que leer para la actividad de la próxima semana?

Saludos!

**Comment by FernandoPieressa** [comment]
Hola!

Entra toda la carpeta de EDD sin contar arboles y grafos.

Saludos!

**Comment by akaminetzkyp** [comment]
Gracias! Busqué y sale EDD1 nomas. :(
