### ISSUE TITLE
instalación librerias

### ISSUE THREAD

**Issue by jgespinosa10** [IIC2233/Syllabus#18]
pongo los códigos para instalar las librerías (pip install --upgrade simpy, pip install numpy y pip install --upgrade matplotlib) y me aparece un error. En el error sale que hay un problema de permisos. ¿Que puedo hacer?
![problema ddescargas de libreria](https://user-images.githubusercontent.com/30691527/29096284-3dd461f6-7c62-11e7-8f18-d96ab41a0c49.png)

**Comment by jtagle2** [comment]
Intenta abrir la consola de comandos como administrador (boton derecho -> ejecutar como administrador).

**Comment by naazocar** [comment]
En ubuntu al menos los problemas de permisos en general se solucionaban poniendo sudo (super user do) al principio, no sé si será igual en windows. Suerte :D

**Comment by jgespinosa10** [comment]
me funciono, muchas gracias

**Comment by jtagle2** [comment]
@naazocar, sudo no sirve para windows, pero es el mismo concepto (sudo = superuser do = ejecutar como administrador).
Saludos! Y gracias por animarte a responder dudas de tus compañeros, se agradece.
