### ISSUE TITLE
Métodos abstract base class

### ISSUE THREAD

**Issue by Mariana-Ortega-del-Rio** [IIC2233/Syllabus#18]
Me surgió otra duda con respecto a las clases abstractas. Pueden tener métodos que NO sean abstractos?
Por ejemplo quiero que todas las clases que heredan de la clase Persona ocupen el método str o repr de la misma forma. Le tengo que colocar @abstractmethod o no a ese método para que los alumnos, profesor, ayudantes, etc tengan ese método repr?

Gracias!!

**Comment by tvillalobos** [comment]
Hola!

Citaré el material de clases (disponible [aquí](https://github.com/IIC2233/contenidos/blob/master/semana-01/06-AbstractBaseClass.ipynb)):

> Las clases abstractas tienen métodos abstractos, que deben ser implementados por las subclases. La idea es que cada subclase tenga una implementación diferente de ese método.

> **También tienen métodos normales**, que están implementados en la clase abstracta y que no es necesario re-implementar en las subclases. **La idea es que sean métodos que se comporten igual en todas las subclases**.

Por lo tanto, si es posible lo que tú mencionas y no sería necesario colocar `@abstractmethod` antes de ese tipo de métodos (ni tampoco implementarlo en cada subclase). Además, respondiendo a tu pregunta específica, una clase abstracta por definición puede o no tener métodos abstractos, todo dependerá de la modelación del problema.

 Como recomendación, para dudas de contenidos de este tipo, siempre es bueno revisar el material de clases, ya que generalmente la respuesta está ahí. Sin embargo, si aún te queda alguna duda, siempre puedes abrir una issue :smile:




Espero haber respondido tu pregunta, saludos!

**Comment by Mariana-Ortega-del-Rio** [comment]
Gracias!!

**Comment by Mariana-Ortega-del-Rio** [comment]
Gracias!! Lo había leído y no se por qué no registré esa parte jaja
