### ISSUE TITLE
No logro permitir el acceso a las carpetas para acceder desde la terminal (IOS)

### ISSUE THREAD

**Issue by lsilvabw** [IIC2233/Syllabus#18]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Mi terminal no tiene acceso a ninguna carpeta (aún cuando le di los accesos desde "preferencias del sistema") por lo que no logro correr los códigos o acceder/leer/editar archivos. Me aparece **'permisson denied'** cuando intento de acceder a cualquier carpeta o archivo desde la terminal. Todo esto me pasa en un computador MacBook Pro 2020 con todas las respectivas actualizaciones al día.
Gracias 
<img width="1169" alt="Screen Shot 2021-08-23 at 12 50 20" src="https://user-images.githubusercontent.com/89400260/130487309-83f40986-326f-4839-9f94-ed5dcfeb543e.png">

**Comment by Maxy15** [comment]
Hola! Es probable que tu terminal de VS Code tenga problemas al correr los programas, a muchas personas con Mac les pasa que la terminal de VS Code no funciona. Te recomiendo ir a la terminal del Mac (cmd + espacio y escribes terminal) y acceder desde ahí a la carpeta donde está el archivo (cd PATH). Luego, escribes Python nombrearchivo.py y debería correr. Avísame si tienes problemas!

**Comment by lsilvabw** [comment]
El codigo si me corrio pero aún tengo problemas para acceder y escribir en las carpetas.
Saludos

<img width="564" alt="Screen Shot 2021-08-23 at 13 49 02" src="https://user-images.githubusercontent.com/89400260/130493429-510a6f56-6114-4adc-bc23-4975b337269b.png">

**Comment by Maxy15** [comment]
Para acceder a las carpetas tienes que escribir cd antes de la ruta, es decir, cd /Users/lucas/.../

**Comment by lsilvabw** [comment]
Eso era, gracias!
