### ISSUE TITLE
Enunciado propuesto 2.1, valores ataque y defensa.

### ISSUE THREAD

**Issue by QuestionMyLife** [IIC2233/syllabus#18]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X ]Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! En el ejercicio propuesto 2.1, se describe en el enunciado que "Al realizar el ataque, se comparan los puntos de ataque del atacante con los puntos de defensa del defensor; la carta con menor valor debe ser descartada de la mano del jugador.". 

Sin embargo, no me queda claro que hacer si ambos tienen el mismo valor, es decir, si ptos_ataque = ptos_defensa. 

Revisé en el excel cartas.csv y en efecto, esta es una situación que podría ocurrir.

**Comment by tqmbanados** [comment]
Hola! Dado que es un ejercicio propuesto, detalles como este no son tan importantes. Puedes escoger lo que te hace más sentido a ti, y aplicarlo a tu código. Lo importante es que resulte bien, y te hagas cargo de todos esos casos "no enunciados". Lo más probable es que no tengas que cambiar casi nada tu código para abarcar todas las posibilidades. 

Personalmente, creo que me hace más sentido que el ataque tenga que superar a la defensa para ganar, pero podrías introducir elementos aleatorios, u cualquier cosa que se te ocurra. Como un pequeño desafío, podrías agregar un texto nuevo para ese caso!

**Comment by QuestionMyLife** [comment]
Entiendo, muchas gracias!
