### ISSUE TITLE
Duda Parametros.py y tipos de combatientes en la T2

### ISSUE THREAD

**Issue by vichovargas** [IIC2233/Syllabus#180]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola tengo una serie de dudas: 
1) ¿se pueden poner otros parámetros o variables en el archivo parametros.py?
2) en los tipos de combatientes se menciona que después de cada ataque ocurre algún cambio, mejora o peora, este cambio se realiza cada vez que el combatiente ataque, o es cuando se activa el poder, es decir, cuando se cumple la probabilidad.
3) En el tipo Caballero arcano sale que un parámetro azul es 100-PROB_CAB, este parametro debemos crearlo como uno nuevo con un nombre que elijamos nosotros, o cuando queramos utilizarlo en el main se llama como 100-PROB_CAB.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by tebi01** [comment]
Hola!

Responderé tus preguntas en el mismo orden.

1. Sí, se pueden agregar los valores que tú desees a ```parametros.py```. Siempre y cuando sean _valores fijos_ y que funcionen como lo que es un parámetro: "un valor fijo que se use a lo largo de tu código para calcular u obtener cosas". Por lo tanto, no modifiques ese valor durante ese código (no es una variable). Puedes incluir paths y otras cosas fijas que estimes convenientes en tu archivo de parámetros, con tal de evitar usar líneas largas o repetir varias veces un mismo valor fijo. Recuerda que debes utilizar TODOS los parámetros que crees, obligatorios o no.

2. Respecto a esta pregunta, te recomiendo que trates de ser lo más literal posible al momento de interpretar el enunciado, ya que se especifica que hay algunos efectos que ocurren cuando se activa un poder, mientras que otros se activan para todo ataque de este tipo de guerrero.

![image](https://github.com/IIC2233/Syllabus/assets/106035073/a7343bc5-6da0-4c0d-ba5a-a9c10bd5d224)

- Para el caso del caballero, se especifica que su "power-up" ocurre cuando se activa su poder, o sea que el ataque se modifica sólo para ese turno.
- De lo contrario, su ataque se calcula como el de un guerrero.
- Para cualquier ataque (da lo mismo si activó su poder o no, su resistencia disminuye en un factor.

Nota: si el enunciado directamente dice que se reduce el atributo de un enemigo o uno propio, se reduce de forma permanente, mientras que si dice que atacará de una forma o 
ignorará cierto atributo, será sólo por ese instante.

3. Eres libre de tomarlo de esa forma, pero dejarlo como ```100-PROB_CAB``` está bien de todas formas.


Espero te haya sido de ayuda!

**Comment by asapsanchez** [comment]
hola, segun la respuesta anterior, por ejemplo, si la resistencia de un combatiente mio se reduce, al pasar la ronda, esta resistencia toma el valor original? o se mantiene reducida?
