### ISSUE TITLE
diccionario.get

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#180]
No entiendo cual es la utilidad de hacer diccionario.get( x, set( )), cual es la diferencia con el comando  diccionario[x]?
![borrar](https://user-images.githubusercontent.com/48294819/56463009-67da8b80-639a-11e9-84d9-0239ae5f5809.PNG)

 y ademas de que sirve poner set() ya que por ejemplo invente el siguiente código
![2222](https://user-images.githubusercontent.com/48294819/56463049-1ed70700-639b-11e9-9afa-ba6c89d2173c.PNG)
y el 6 si esta repetido, así que no entiendo la función de set().

**Comment by KnowYourselves** [comment]
Hola @jalliende!

El problema con diccionarios es que si intentas acceder a un valor que **no existe** se levantará el error `KeyError`.

Esto quiere decir que si a la función `remover_arista` le ingresáramos un nodo que no existe, nos tiraría error. La forma de prevenir esto es haciendo uso de la función `get` de los diccionarios. Esta función recibe dos parámetros, el primero es el elemento a buscar en el diccionario y el segundo es lo que queremos que la función retorne si no encuentra el elemento.

Esto quiere decir que si ingresamos un `x` que no está en el grafo `self.lista_adyacencia.get(x, set())` retornará un `set` vacío. La gracia de hacer esto es que permite que la siguiente linea, `if y in vecinos_x` funcione correctamente independiente de si `x` está en el diccionario o no.

Espero haberte ayudado!

**Comment by jalliende** [comment]
gracias
