### ISSUE TITLE
Efecto de Bomba Especiales

### ISSUE THREAD

**Issue by enriquerussi** [IIC2233/syllabus#180]
Si una bomba especial hunde un barco, se tiene el turno nuevamente o pasa a ser turno del oponente?

**Comment by vicentevegaulloa** [comment]
Hola @enriquerussi!

Como indican las reglas del enunciado, se tiene el turno nuevamente. 😄

**Comment by JoseTomasSoto** [comment]
el rango de una bomba especial puede disparar en un lugar donde ya se disparó?

**Comment by vicentevegaulloa** [comment]
Hola @JoseTomasSoto !

Si puede. Lo que no se puede es elegir como coordenadas de origen de la bomba unas que ya se hayan ocupado.

**Comment by cnillanes** [comment]
Hola! Qué pasa cuando le bomba especial le da a más de un barco? repite turno esa cantidad de veces o solo uno?
Gracias!

**Comment by vicentevegaulloa** [comment]
Hola @cnillanes !

Repite una sola vez.

Saludos 😄
