### ISSUE TITLE
Duda sobre Ranking

### ISSUE THREAD

**Issue by manuel-2112** [IIC2233/Syllabus#180]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Mi duda es si en la ventana ranking se debe hacer un orden de los 5 mayores puntajes o de los 5 mayores puntajes de jugadores diferentes.

Ej caso 1:
1 - Matiasmasjuan, 890
2 - Gatochico, 760
3 -  Gatochico, 748
4 - Matiasmasjuan, 380
5 - Emiliax16, 210

Ej caso 2:
1 - Matiasmasjuan, 890
2 - Gatochico, 760
3 - Maxy15, 430
4 - Diegocostares, 370
5 - Emiliax16, 210

**Comment by Emiliax16** [comment]
Hola @manuel-2112 ! queda a elección del estudiante cual de esas dos opciones implementar, pero **debe especificarse en el readme**. Sin embargo, recomendamos mostrar los mejores puntajes, independiente de si se repiten jugadores o no, como lo demuestra tu caso 1. Saludos!
