### ISSUE TITLE
Cantidad de entrenadores simular_ronda( )

### ISSUE THREAD

**Issue by rodridelafuente** [IIC2233/Syllabus#180]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo una duda con la simulación de rondas en el campeonato y la cantidad de entrenadores que participan. En el enunciado, en la sección de simulación ronda del campeonato, aparece que se puede "pensar esto como octavos de final y asumir que siempre habrán 16 entrenadores compitiendo, incluyendo el que se utiliza". Sin embargo, la entidad Liga Programón tiene un atributo con los perdedores del campeonato, por lo tanto, no me queda claro si siempre competirán los 16 entrenadores o si se irá reduciendo el número de estos, eliminando a los perdedores, hasta llegar a cuartos de final, semifinales y una final. 
Muchas gracias de antemano!

**Comment by Emiliax16** [comment]
Hola @rodridelafuente ! en realidad lo que el enunciado quería decir es que siempre tendrás 16 competidores (incluyendo el entrenador que elegiste) al iniciar el campeonato. Es lo mismo que asegurarte que el archivo `entrenadores.csv` siempre tendrá justo 16 entrenadores. Por lo que la Liga programón irá almacenando a cada perdedor de cada ronda y, por ende, el número de competidores al pasar las rondas se irá reduciendo. Saludos!
