### ISSUE TITLE
Infecciones

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#180]
Con respecto a las infecciones: 
1) un jugador X elige una infección para un país, mi pregunta es cómo las personas comienzan a infectarse. Por ejemplo, el jugador le tira un virus a Argentina ¿¿cuántos infectados hay en ese momento (día 0 de la infección)?? Tengo esta duda ya que según yo la tasa de contagiosidad es de persona a persona y en ninguna parte del enunciado se refieren a cuántas personas se infectan el lanzar la infección a un país. 

2) ¿un país puede ser afectado por más de una infección?

**Comment by ranieto** [comment]
1. En otro issue ya se dijo que se empieza con una persona, lo mismo cuando se transmite a otro país.

2. ¿Cómo sería eso?, ¿no hay solo una infección por juego?

**Comment by jorgeriesco** [comment]
Según yo si hay una infección pero en las estadísticas se pide las infecciones por día jajaj ¿Que es eso?

**Comment by ranieto** [comment]
@jorgeriesco creo que se refiere a cantidad de personas que se infectaron por día.

**Comment by jorgeriesco** [comment]
@ranieto jaja tiene mucho sentido, gracias
