### ISSUE TITLE
README: "crear los siguientes archivos y directorios adicionales:"

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#180]
Qué significa que en la realización del README nos pidan:
"crear los siguientes archivos y directorios adicionales:"
1. archivo.ext en ubicación
2 . directorio en ubicación
3. .....

**Comment by DCCollao** [comment]
La idea es que si necesitas que nosotros creemos algún archivo adicional, lo pongas ahí.
También, si necesitas que tus archivos `.csv` estén en una ubicación en específico, debe quedar escrito en esa sección.

**Comment by Camila-sty** [comment]
Pero en el caso de que los archivos "csv" que ocupamos solo deben estar en la misma carpeta que los módulos que yo cree para mi tarea, debo incluir esto también?

**Comment by DCCollao** [comment]
No, no es necesario que incluyas eso, pues esa es la ubicación 'por defecto' que les entregamos nosotros. Es así como pondremos los archivos en el caso de que no exista algún comentario en esa parte del `readme.md`
