### ISSUE TITLE
Lista de instancias de la clase A como atributo de la clase A

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#180]
Hola! Es correcto tener como atributo de la clase A una lista de instancias de la clase A? En mi tarea tengo una lista con todas las instancias de la clase User, pero tengo esta lista como atributo de otra clase porque asi empece mi programa no mas, entonces es mas correcto tenerla como atributo de la misma clase User o da exactamente igual?

**Comment by hanavarrete** [comment]
Cuando dices "tengo esta lista como atributo de otra clase" te refieres a otra del tipo A?

**Comment by bedefrunner** [comment]
no, me refiero a otra clase B. Es decir, tengo una lista con instancias de la clase A, y esta lista la tengo como atributo de la clase B. Me suena más logico tener esa lista de instancias de la clase A como atributo de la misma clase A.
