### ISSUE TITLE
Duda orden detectar_plagas

### ISSUE THREAD

**Issue by JorgeUribeGo** [IIC2233/Syllabus#180]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo una duda sobre un caso específico de detectar_plagas.
Cuando eliminamos igual cantidad de cultivos de predios que se llamen "P1", "P2", "P13"; se supone que el orden entregado debe ser "P1", "P2", "P13" (Y no "P1", "P13", "P2"), como se dijo en otra issue.

El problema es que algunos de los tests públicos que tenemos incluyen predios que se llaman "A", "B", "C", que no va de acuerdo con el enunciado donde nos dicen que los nombres son "P" seguido de algún número.
Lo que me hace sentido es hacer mi código según el enunciado, pero hacerlo así me hace tener errores en el test de detectar plagas, lo que me da desconfianza porque no sé si los tests reales van a ser así o no.

¿Debería hacerlo para cumplir con el caso de los nombres "A", "B", "C" aunque eso implique entregar el orden "P1", "P13", "P2"?

**Comment by individuocomunycorriente** [comment]
Hola!
Respondiendo a tu pregunta, debes hacerlo considerando que los códigos de los predios pueden ser cualquier string, entiendo la confusión con el inicio del enunciado de la tarea, pero en ningún momento (ya sea con métodos o inicializando alguna clase) se comprueba que el código realmente tenga la estructura P seguido de un número, por ende, para que tu código sea aprueba de todo, se debe hacer de esta manera. Y respecto a los test reales, no te preocupes, no son iguales pero son representativos.
Saludos.

**Comment by JorgeUribeGo** [comment]
Entonces no le hago caso al enunciado?
Me pasa que no se puede hacer el orden a prueba de todo, tengo que elegir si hacerlo a prueba de cualquier string o si hacerlo considerando strings de la forma "P" con un número.

Si lo ordeno considerando que el string puede ser cualquier cosa, voy a llegar al problema de ordenar "P1", "P13", "P2" en el ejemplo que dije antes. Eso está bien?

**Comment by individuocomunycorriente** [comment]
Conversé con el equipo docente y se encontró una issue en la cual aparece la respuesta que mencionas, sin embargo la persona que respondió no es ayudante del curso y proporcionó una respuesta errónea.

Así que a modo de resumen, debes considerar que el código de los predios puede ser cualquier string y debes ordenarlos alfabéticamente, por lo que si tres predios con códigos P1, P2 y P13 poseen la misma cantidad de plagas, el método debe retornar en el orden P1, P13 y P2. 
Espero haber resuelto tu duda, saludos :)

**Comment by JorgeUribeGo** [comment]
Yaa perfecto, muchas gracias!
