### ISSUE TITLE
Equipo y afinidad

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#180]
Hola, leyendo el enunciado de la tarea 2 me surgieron 2 dudas:

Cómo cambiar jugadores que están dentro de la cancha por los que están en la banca, si los equipos deben ser de 11 jugadores. ¿Permitimos cambiarlos por jugadores que no estén en ningún equipo o los equipos deben ser más grandes y los titulares se escogen al azar?

En caso de que los equipos tengan banca. Al momento de calcular la afinidad entre dos jugadores que no se conocen ¿Podemos asumir que la afinidad entre dos jugadores no será negativa? (lo cual siempre ocurre si los equipos son de máximo 11 personas)

**Comment by Pipelao** [comment]
Hola :)
Lo que vi del código de Interfaz.py es que tienen una función cambio e intercambio, entonces ocupan internamente una para hacer el intercambio de posición (que supongo que es intercambio) dentro de la cancha y otro que es cambiar (supongo que cambio) con alguien fuera de la cancha quién tiene datos distintos pero que en el programa el equipo sigue teniendo al mismo jugador que salió en cuanto a sus datos por lo que el equipo dentro del código continúa igual no así el equipo en la interfaz que es distinto.
¿Es así?

**Comment by pcseisdedos** [comment]
Entonces el método cambio_jugador no debe hacer nada si el parámetro "en_cancha" es False?

**Comment by behrmann97** [comment]
Hola,
@santilaguna @Pipelao @pcseisdedos Al momento de iniciar la GUI, le entregarás 200 jugadores y al menos 16 equipos. Luego, podrás armar tu equipo de 11 jugadores a partir de los 200 jugadores. Es irrelevante si estos jugadores están en otro equipo o no. Al hacer cambios en tu equipo, se debe actualizar la esperanza de ganar del equipo de la GUI. Una vez listo el equipo, podrán ir a la sección campeonato, donde deberán simular el campeonato como se muestra en el enunciado. Es dentro de éste campeonato donde los equipos no tienen banca ni pueden hacer cambios.
@Pipelao No debes preocuparte de lo que hace la GUI internamente, pero sí, sí hace los cambios necesarios para mantener los datos actualizados, es decir, al cambiar un jugador por uno fuera de la cancha, sí cambian los datos del jugador.
@pcseisdedos Debe cambiar la esperanza de ganar del equipo dependiendo de las afinidades del nuevo jugador que entró con los jugadores que lo rodean, como se explica en la sección 4.2.3 del enunciado.

Espero haber aclarado sus dudas, cualquier cosa pregunten :)

**Comment by pcseisdedos** [comment]
Por lo que entiendo al iniciar la GUI debo extraer 200 jugadores aleatoreamente y entregar 16 equipos de 11 integrantes cada uno, lo que no entiendo bien del item 4.2.1 es:
1. Donde dice que el grafo de afinidades debe ser conexo, al realizar un cambio de jugadores es posible que el grafo de afinidades deje de ser conexo, ¿debo preocuparme de eso?
2. ¿Es posible que con 200 jugadores random no se puedan crear 16 equipos de 11 jugadores cada uno con un grafo de afinidades conexo?

**Comment by behrmann97** [comment]
@Pipelao Al momento de hace  el equipo en la GUI, cambias los jugadores y las posiciones del equipo. Luego en el campeonato no hay banca ni cambios, sólamente se simulan los partidos.

@pcseisdedos Siempre serán conexos, no debes preocuparte de eso.

@Pipelao @pcseisdedos Para la GUI, los 16 equipos son simplemente 16 nombres con cierta esperanza de ganar, por lo tanto los 200 jugadores pueden ir en el equipo del usuario, los equipos los armaron antes y para la GUI es irrelevante qué jugadores están en los equipos, sólo importa el del usuario principal. Se ha updateado la GUI para que la vean con el ejemplo con 20 jugadores. Como verán, primero el usuario seleccionará 11 jugadores para su equipo y luego puede utilizar los otros 9 jugadores para cambiarlos. Una vez listo, puede ir a la sección de campeonato para simular un campeonato con los otros equipos que ingresó.

**Comment by Cschavez** [comment]
Hola! hay una cosa que no me queda claro, el campeonato ocurre o más bien, se tiene que programar también dentro de "Demo.py"  en métodos aparte de los que ya están?  y cuando dices que "siempre serán conexos" eso es entre cualquier grupo de 200 que se tomen de los 5500 jugadores ? o te refieres especialmente a que siempre serán conexos los equipos que se formen con esos 200 jugadores?
Muchas gracias!

**Comment by Cschavez** [comment]
Además, cuando dice que para entregar los 200 jugadores no se pueden ocupar listas se refieren a las listas de python? o incluso a una lista ligada creada por mi? 
Gracias!!!

**Comment by Cschavez** [comment]
Y, por último, la esperanza de los equipos que se entregan es un número al azar? lo pregunto porque en ninguna parte dice cuales son los integrantes de ese equipo. 
gracias!
