### ISSUE TITLE
Leer y escribir archivos.csv

### ISSUE THREAD

**Issue by ranelson1** [IIC2233/syllabus#180]
Hola! 

Nuestro programa debe ser capaz de escribir y leer los archivos en el orden de headers que nos den? O, podemos escribirlos en el orden que queramos?

**Comment by gatochico** [comment]
Hola!

Tu programa debe poder leer archivos csv **cuyas columnas estén en cualquier orden** (y que tengan los atributos que indicamos en el enunciado para cada archivo, por supuesto) sin caerse.

Lo mismo con respecto al escribir archivos, ya que piensa que los archivos donde debes escribir, como `pilotos.csv`, ya podrían venir con información preescrita, la cual nuevamente podría tener sus columnas en cualquier orden. Por lo tanto, al momento de escribir tu programa debería adecuarse al formato que ya podría traer este archivo y escribir en el mismo orden la información nueva.

Éxito con la tarea :racing_car: :checkered_flag: !!

**Comment by ranelson1** [comment]
yaa perfeecto, gracias!
