### ISSUE TITLE
03-2: Duda sobre super() en multiherencia

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#180]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Al final se nos da el siguiente ejemplo:
![image](https://user-images.githubusercontent.com/66154723/113518616-6db0e380-9555-11eb-93d4-fcd0bf712644.png)

### Y el código final fue:
<details>
  <summary>Código</summary>

```python
class Investigador:

    def __init__(self, area='', **kwargs):
        print(f"init Investigador con area {area} y kwargs:{kwargs}")
        super().__init__(**kwargs)
        self.area = area
        self.num_publicaciones = 0


class Docente:

    def __init__(self, departamento='', **kwargs):
        print(f"init Docente con depto {departamento} y kwargs:{kwargs}")
        super().__init__(**kwargs)
        self.departamento = departamento
        self.num_cursos = 3


class Academico(Docente, Investigador):

    def __init__(self, nombre, oficina, **kwargs):
        print(f"init Academico con nombre {nombre}, oficina {oficina}, kwargs:{kwargs}")
        super().__init__(**kwargs)
        self.nombre = nombre
        self.oficina = oficina


print(Academico.__mro__)
p1 = Academico("Emilia Donoso", oficina="O5", area="Inteligencia de Máquina", departamento="Ciencia De La Computación")
print("--------")
print(p1.nombre)
print(p1.area)
print(p1.departamento)
```

</details>

#### Entiendo que Académico y Docente incluyan el ``super().__init__``, para no llamar 2 veces a ``object``, y asumo que si no lo tuvieran, object sería llamado dos veces. Hasta ahora no veo el problema (funcionaría igual que el código de ejemplo que se mostró antes en este _ipynb_), pero al parecer al borrar ambos super() y correr el código nos aparece un error:
![image](https://user-images.githubusercontent.com/66154723/113518759-49093b80-9556-11eb-9ea9-7893e49f2d4e.png)

### Lo cual me confunde, ya que pensé que ``object`` se ejecutaría 2 veces y ya está, pero es más, veo que este error en realidad se produce cuando se lo quitamos a la class Docente, ya que cuando solo comentamos este,
![image](https://user-images.githubusercontent.com/66154723/113518866-e6fd0600-9556-11eb-8244-c6c5cf24cf93.png)
### Se produce el mismo error...
![image](https://user-images.githubusercontent.com/66154723/113518870-f2e8c800-9556-11eb-987d-0227ff1f323b.png)

#### ¿Hay algo en cómo entendí esta materia completamente erroneo, o es algún detalle minucioso? Lo que tampoco termino de entender es cómo podría comentar la linea de Docente, causar que Investigador no guarde self.area? ya que según entiendo yo, la siguiente línea es la encargada de ejecutar primero docente y luego investigador por si sola
![image](https://user-images.githubusercontent.com/66154723/113518929-4ce98d80-9557-11eb-8562-0910460c27f9.png)

**Comment by tqmbanados** [comment]
Hola! Es una buena pregunta, nunca había pensado en ese detalle. La solución esta en lo que significa el llamado ```super()```. Como dice el notebook de multiherencia, *llama a las super-clases en el __orden de resolución de métodos__*, es decir, de izquierda a derecha cuando se definió la herencia de la sub-clase. Pero lo importante saber, y que produce el error, es que llamar a ```super()``` en la sub-clase no llamará automáticamente todas las super-clases, si no que *cada una debe llamar a la anterior* con su propio llamado a ```super()```. Es por eso, que al sacarlo de la inicialización de ```Docente```, el proceso de llamados terminara ahí, y no se moverá hacia ```Investigador```. Anteriormente, no era necesario que ```super()``` estuviera en las super-clases pues ```Academico``` llamaba manualmente los ```__init__()``` de cada super-clase.
Espero haberte ayudado con tu duda!

PD: Esto no es parte del curso, pero por ejemplo mover en que momento del ```__init__()``` llamas el ```super()``` en la super-clase puede tener sus beneficios según el caso. Te invito a seguir investigando más si te interesa!

**Comment by fernandosmither** [comment]
> Hola! Es una buena pregunta, nunca había pensado en ese detalle. La solución está en lo que significa el llamado `super()`. Como dice el notebook de multiherencia, _llama a las super-clases en el **orden de resolución de métodos**_, es decir, de izquierda a derecha cuando se definió la herencia de la sub-clase. Pero lo importante saber, y que produce el error, es que llamar a `super()` en la sub-clase no llamará automáticamente todas las super-clases, si no que **cada una debe llamar a la siguiente** con su propio llamado a `super()`. Es por eso, que al sacarlo de la inicialización de `Docente`, el proceso de llamados terminara ahí, y no se moverá hacia `Investigador`. Anteriormente, no era necesario que `super()` estuviera en las super-clases pues `Academico` llamaba manualmente los `__init__()` de cada super-clase.
> Espero haberte ayudado con tu duda!
> 
> PD: Esto no es parte del curso, pero por ejemplo mover en que momento del `__init__()` llamas el `super()` en la super-clase puede tener sus beneficios según el caso. Te invito a seguir investigando más si te interesa!

#### Creo que te entendí, pero sigo con la duda de porqué el error sí se causa cuando le quitamos la llamada ``super()`` a ``Docente``, pero no pasa nada cuando se la quitamos a ``Investigador``.  Yo entendí que ``super()`` en el caso de Docente e Investigador llamaría a ``object``, pero sigo sin entender por qué el error es como si implícitamente dijera que no se ejecutó ``Investigador``, siendo que ``super()`` solo afectaria a la ejecución de ``object``. No sé si se entiende mi duda.

#### Respecto a lo último, claro que me interesaría investigar más sobre el tema!, tienes algún enlace o keywords para que yo pueda buscarlo? Muchas gracias y saludos.

**Comment by tqmbanados** [comment]
Bueno, acá nos estamos metiendo en un territorio más complejo (donde yo tampoco tengo las respuestas tan claras). Lo que ocurre es que la clase interna de python ```object``` es especial en que es llamada automáticamente sin necesidad de usar un ```super```. **No** es llamado en el caso de la multiherencia, donde hay un ```super()``` que llama el ```__init__()``` de otra clase, como el caso de ```Docente```. ```Investigador``` está al final del orden, por lo que aunque técnicamente se rompa la cadena de ```super().__init__()```, la única clase que faltaba por instanciar es ```object```, que lo hace automáticamente. Si hubiera una tercera super_clase de ```Academico```, o ```Investigador``` heredara de otra clase, ahí tendrías un error al sacar el ```super()```.

Espero te quede más claro ahí! Estuve buscando páginas que puedan serte útiles, pero no encontre nada demasiado concreto. Pero puedes buscar "python 3.7 super()" y variables que te metan en un lugar más interno de cómo funcionan por detrás las clases. En todo caso, estas son cosas bien avanzadas que yo tampoco manejo mucho, quizás podrías escribirle a tu profesor para que te dirija a un mejor lugar para aprender.

**Comment by fernandosmither** [comment]
@tqmbanados 
Muchas gracias por tu respuesta, pero me quedan algunas dudas.
> ``object`` [...] No es llamado en el caso de la multiherencia, donde hay un super() que llama el __init__() de otra clase, como el caso de Docente.

estás diciendo que ``super().__init__`` de ``docente`` no está llamando al init de object? pensé que object al ser su superclase, se dirigía a él. En este caso, a dónde apunta ese super()?

y finalmente el problema de quitar ese super() en Docente significaría que no se ejecuta Investigador? (si lo entendí bien y es así, por qué Docente tendría que ver con la llamada a Investigador?)

**Comment by tqmbanados** [comment]
Lo que pasa es que lo retornado por ```super()``` depende de quien lo llama y en qué contexto. 
Cuando ```Academico``` llama super(), python genera el "orden" en el cual serán inicializadas las super-clases. Bajo ese contexto, si ```Docente```, que es el siguiente en la lista, llama ```super()```, estará llamando a ```Investigador```. Si ```Docente``` llamara a ```super()``` sin estar dentro ya de una llamada ```super()``` con el orden de resolución de métodos, llamaría a ```object``` normalmente. 
Mira, ojalá con los siguientes diagramas explique mejor. Este es el caso original, donde ```Academico``` llama manualmente los ```__init__()``` de sus super-clases. Como ```object``` se inicializará siempre, independiente si se hace manual, no es necesario que ```Docente``` e ```Investigador``` tengan ```super()```.

<img width="286" alt="Explicación 1" src="https://user-images.githubusercontent.com/69922599/113760462-43d9f700-96e4-11eb-8f1d-759a143383f1.png">

En el segundo caso (el caso ideal), tanto ```Academico``` como ```Docente``` tienen el llamado a ```super().__init__()```. La primera vez que se llama a ```super()```, en ```Academico```, python genera automáticamente el orden en el cual se realizarán los siguientes llamados al ```__init__()``` en cada super-clase. En este caso, ```object``` **siempre** irá al final, y **siempre** será llamado. Por eso, el ```super()__init__()``` en ```Investigador``` es de cortesía y una buena práctica, pero no necesario. Y como ```object``` *siempre* va al final, ```Docente``` no hace el llamado al ```__init__()``` de ```object```, por que la siguiente clase en el orden es ```Investigador```, entonces, el ```super()``` de ```Docente``` hace referencia a ```Investigador```, el siguiente en el orden. 
*(Puedes imaginarlo como que en ese caso, ```Investigador``` es una super-clase de ```Docente```)*
<img width="286" alt="Explicación 2" src="https://user-images.githubusercontent.com/69922599/113761227-37a26980-96e5-11eb-92de-2085cef6dcd4.png">

Finalmente, lo que generó tu error: Aquí, ```Academico``` hace un llamado a inicializar las super-clases con ```super().__init__()```, haciendo que python genere el orden de resolución de métidos (mro). Sin embargo, ```Docente()``` **no** tiene el llamado a inicializar la super-clase, por lo que no ocurre un llamado al inicializador de ```Investigador```. Recuerda que donde se definen los atributos del objeto es en el ```__init__()```, por lo que si no está presente, los atributos definidos dentro de ```Investigador``` (en este caso ```self.area```), no serán parte de esa instancia de ```Academico```. Al pedir ese atributo, lanzará un error como el que te salió a tí. De todas formas, como ```object``` **siempre** tiene que ir al final y siempre se va a llamar, python se salta a ```Investigador``` y llama a ```object``` para completar el orden. 
![Expliación 3](https://user-images.githubusercontent.com/69922599/113761948-0a09f000-96e6-11eb-8eed-f18138d10816.jpg)

**Comment by fernandosmither** [comment]
> Lo que pasa es que lo retornado por `super()` depende de quien lo llama y en qué contexto.
> Cuando `Academico` llama super(), python genera el "orden" en el cual serán inicializadas las super-clases. Bajo ese contexto, si `Docente`, que es el siguiente en la lista, llama `super()`, estará llamando a `Investigador`. Si `Docente` llamara a `super()` sin estar dentro ya de una llamada `super()` con el orden de resolución de métodos, llamaría a `object` normalmente.
> Mira, ojalá con los siguientes diagramas explique mejor. Este es el caso original, donde `Academico` llama manualmente los `__init__()` de sus super-clases. Como `object` se inicializará siempre, independiente si se hace manual, no es necesario que `Docente` e `Investigador` tengan `super()`.
> 
> <img alt="Explicación 1" width="286" src="https://user-images.githubusercontent.com/69922599/113760462-43d9f700-96e4-11eb-8f1d-759a143383f1.png">
> 
> En el segundo caso (el caso ideal), tanto `Academico` como `Docente` tienen el llamado a `super().__init__()`. La primera vez que se llama a `super()`, en `Academico`, python genera automáticamente el orden en el cual se realizarán los siguientes llamados al `__init__()` en cada super-clase. En este caso, `object` **siempre** irá al final, y **siempre** será llamado. Por eso, el `super()__init__()` en `Investigador` es de cortesía y una buena práctica, pero no necesario. Y como `object` _siempre_ va al final, `Docente` no hace el llamado al `__init__()` de `object`, por que la siguiente clase en el orden es `Investigador`, entonces, el `super()` de `Docente` hace referencia a `Investigador`, el siguiente en el orden.
> _(Puedes imaginarlo como que en ese caso, `Investigador` es una super-clase de `Docente`)_
> <img alt="Explicación 2" width="286" src="https://user-images.githubusercontent.com/69922599/113761227-37a26980-96e5-11eb-92de-2085cef6dcd4.png">
> 
> Finalmente, lo que generó tu error: Aquí, `Academico` hace un llamado a inicializar las super-clases con `super().__init__()`, haciendo que python genere el orden de resolución de métidos (mro). Sin embargo, `Docente()` **no** tiene el llamado a inicializar la super-clase, por lo que no ocurre un llamado al inicializador de `Investigador`. Recuerda que donde se definen los atributos del objeto es en el `__init__()`, por lo que si no está presente, los atributos definidos dentro de `Investigador` (en este caso `self.area`), no serán parte de esa instancia de `Academico`. Al pedir ese atributo, lanzará un error como el que te salió a tí. De todas formas, como `object` **siempre** tiene que ir al final y siempre se va a llamar, python se salta a `Investigador` y llama a `object` para completar el orden.
> ![Expliación 3](https://user-images.githubusercontent.com/69922599/113761948-0a09f000-96e6-11eb-8eed-f18138d10816.jpg)

### Deberíamos tener un ``hall-of-fame`` de mejores respuestas de ayudantes, y hasta ahora, la tuya @tqmbanados definitivamente estaría en el puesto # 1.

Muchas gracias!

**Comment by tqmbanados** [comment]
ahdfhgdasfhgdash muchas gracias!! :cat: Me alegro que se te haya aclarado
