### ISSUE TITLE
Consulta Max 100 caracteres Tarea 00

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#181]
hola! , quiero ver que priorizar, ya que por tema de facilidad de lectura de código y estética al momento de interactuar tengo algunas lineas con mas de 100 caracteres , alrededor de 120 aprox , las cuales corresponden a prints.
es posible obviar el limite de 100 caracteres en este caso?
o recorto la linea a pesar de que esto cueste legibilidad del programa y estética al momento de correrlo.
quedo atento saludos!

**Comment by vicentevegaulloa** [comment]
Hola @sa-Appel !

Estoy de acuerdo con que esto afecta a la estética, pero es necesario respetar PEP8. Debes recortar la línea para evitar el descuento por exceso de caracteres. 

Saludos!

**Comment by YehudaGurovich** [comment]
@sa-Appel Hay formas en python de continuar en la linea siguiente de codigo pero en la misma funcion.

**Comment by vicentevegaulloa** [comment]
Si! Si se te acaba el espacio de la linea mientras escribes los argumentos de una funcion puedes con "Enter" cambiar de linea sin problema. En otros casos puedes usar el caracter "\".  Por ejemplo:

    a = dostuff(blahblah1, blahblah2, blahblah3, blahblah4, 
      blahblah5, blahblah6, blahblah7)

o 

    if a == True and \
        b == False

**Comment by vikicontardo** [comment]
¿En el caso de que tanga un línea que sobrepasa los 100 caracteres por agregar un comentario # (el cual explica qué hace esa línea), eso también se considera para el descuento?

**Comment by vicentevegaulloa** [comment]
Hola @vikicontardo !

Disculpa la demora 😢. El descuento de los 100 caracteres por linea no distingue del tipo de linea, por lo que tampoco puedes pasarte del límite ne le caso de los comentarios. Espero que esto te sirva paralas próximas tareas 😄
