### ISSUE TITLE
es posible que hayan matches en la base de datos preexistente?

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#181]
Hola! Es posible que en la base de datos de orders preexistente hayan ordenes activas que debieran hacer match apenas se inicializa el pograma? Por ejemplo, en la base de datos "orders.csv" hay un ask  hecho por el user juanito que esta activo, vende 100 DCC en 20.000 CLP la unidad y hay un bid del user pedrito que esta activo y quiere comprar 100 DCC en 20.000 CLP la unidad.  En ese caso el programa debiera hacer match apenas se inicializa el programa. Puede ocurrir eso?

**Comment by Arcoirisky** [comment]
Hola!
Tu pregunta está respondida en otra issue :) No recuerdo cual exactamente O:! Pero búscala entre issues cerradas :D ¡Suerte!
