### ISSUE TITLE
Matriz de incidencia

### ISSUE THREAD

**Issue by catorres8** [IIC2233/syllabus#181]
Hola :relaxed:, En el material sobre grafos y representación se menciona que una de las múltiples representaciones de grafos es la matriz de incidencia y que se vería en este curso. El tema es que al final no está en el material, por lo que ¿No tiene importancia que lo veamos, es igual a la matriz de adyacencia o hay alguna otra razón? 

A continuación coloco el fragmento en el que se menciona:
> ## Estructura

> Existen múltiples formas para representar grafos. En este curso examinaremos cuatro de ellas: representación con nodos, listas de adyacencia, matrices de adyacencia y **matrices de incidencia**.

**Comment by fdoflorenzano** [comment]
¡Hola! 
Gracias por mencionarlo. Matrices de incidencia fue una representación que omitimos del material en esta versión del curso. Se nos pasó eliminar las referencias que mencionas simplemente. No es necesario que la revisen o conozcan para esta versión del curso. 

Pero, si estás curiosa, puedo comentar aquí esa porción del material. 😄 
Saludos.
