### ISSUE TITLE
Dudas congelamiento bomba de hielo

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#181]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

¿El congelamiento de la bomba de hielo debe sólo tener efecto en aliens vivos o en los cadáveres cayendo también? ¿En caso de dispararle a un alien congelado, debe su cadáver quedarse congelado hasta que se vaya el efecto del congelamiento o empieza a caer de inmediato? ¿Si llegan más aliens luego de activar la bomba de hielo, son estos afectados también por esta bomba o no?

**Comment by Emiliax16** [comment]
Hola @MaxAl100 ! la bomba de hielo debe afectar sólo a los _aliens_ vivos. Si le disparas a un _alien_ congelado, este cambia a su sprite de _alien dead_ y cae normalmente en línea recta. Los _aliens_ se congelan al momento de dispararle a la bomba y el tiempo de congelamiento sólo se aplica a los _aliens_ que se encuentran congelados, por lo que si le disparas a todos los _aliens_ que se encuentran congelados, estos caen y entran los siguientes _aliens_, a los cuales no les afecta la bomba de hielo (incluso si aun no se acaba el tiempo de congelamiento) . Espero se haya entendido, saludos!
