### ISSUE TITLE
README: Partes implementadas y errores en el programa

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#181]
Hola!
Quería preguntarles que tan específicos debemos ser a la hora se escribir lo que implementamos y lo que no?. Por ejemplo, si yo implementé todo lo que nos piden en el enunciado de la tarea, significa que está todo implementado?, y lo NO implementado sería lo que no hice y sí se pedía en el enunciado?
Ahora en cuanto al funcionamiento del programa. Yo por ejemplo tengo todas las funciones y acciones que se pide que la red social haga, pero a través de las acciones van ocurriendo cosas que se pueden considerar como "fallas" (a pesar de que cumpla la función que se nos pide) esto debe ir comentado en "Consideraciones generales" o en "Supuestos y consideraciones adicionales "?. Pregunto esto porque a un "fallo" (que es considerado así porque no debería pasar) yo sé como solucionarlo y finalmente lo puedo explicar, pero no sé en qué ítem del README debo considerarlo.
Gracias!

**Comment by DCCollao** [comment]
Si implementaste todo lo pedido en la tarea, efectivamente está todo implementado.

Lo segundo que planteas, respecto al funcionamiento del programa, debería ir en `Supuestos y consideraciones adicionales`.

De todas maneras, en la carpeta de tareas en el syllabus subimos algunos ejemplos de buenos `readme.md`

**Comment by Camila-sty** [comment]
Sí, leí todos los ejemplos, pero igual no me sacaba de mi duda.
Ahora sí, gracias.
