### ISSUE TITLE
Errores de input

### ISSUE THREAD

**Issue by pgaguilera** [IIC2233/Syllabus#181]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Para manejar los posibles errores de un usuario al ingresar un input ¿se debe emplear excepciones como herramienta o se puede tratar de otra manera?

**Comment by Emiliax16** [comment]
Hola @pgaguilera ! puedes implementar `try/except` sin ningún problema, pero siempre debes especificar la excepción, sino, se considerará mala práctica y tendrá descuento (puedes leer más sobre eso en la issue de librerías permitidas [#107 ](url)). Igualmente puedes manejar los errores de inputs tu mism@, sin el uso de `try/except`. Esto puede ser a través de iteradores, control de flujo, etc . Lo que estimes conveniente c: Saludos!
