### ISSUE TITLE
Países repetidos en population.csv

### ISSUE THREAD

**Issue by ranieto** [IIC2233/Syllabus#181]
Hay algunos países que aparecen dos veces, con distinto número de habitantes cada vez. Hasta ahora noté estos repetidos: Saudi Arabia, South Korea, United States, Costa Rica y United Arab Emirates. Quizás haya más.

**Comment by AmbrosioV** [comment]
De momento yo los trato como paises diferentes, ya que no tienen el mismo nombre porque unos tienen algunas mayusculas que los distinguen.
