### ISSUE TITLE
Pueden haber piezas explosivas superpuestas? y que pasa si dos piezas explosivas se encuentran en las respectivas celdas afectadas?

### ISSUE THREAD

**Issue by matix3000** [IIC2233/Syllabus#181]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Mi pregunta la coloque de manera bastante explícita en el título, me surgio la duda, pues no encontre norma que impidiera que dos piezas explosivas se encuentren en la misma celda, ni si afectan de alguna manera las celdas afectadas, la superposición de la explosión.

**Comment by Mcroquevielle** [comment]
Hola!! Hay solo 1 elemento por posición (que puede ser un peón, una pieza explosiva o una celda vacía), por lo que no podrían haber 2 piezas explosivas superpuestas. Con respecto a que se superponga el alcance, no pasa nada, lo importante es que cada una afecte a la cantidad de celdas que dice su número. Por ejemplo, en la siguiente foto (figura 3 del enunciado):
![image](https://github.com/IIC2233/Syllabus/assets/127401753/ed2d4130-329c-454b-b5e7-ca60e9b3c69f)
Se puede ver que el alcance de R6 "topa" con el de "H5", y da lo mismo
