### ISSUE TITLE
Problemas para borrar archivos de mi repositorio

### ISSUE THREAD

**Issue by ComPups** [IIC2233/Syllabus#182]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Tengo una duda con el .gitignore, resulta que yo hice push mucho antes con todos los archivos de la tarea, lo que hizo que el pdf, los csv, etc estuvieran incluídos. Ahora que estaba armando el .gitignore me di cuenta que no puedo borrar directamente los archivos del repo, cosa que según yo antes si podía. Trataría de usar git reset pero me da miedo dejar la embarrada :c. Hay algun método para hacerlo? hice push del git ignore ya, pero todo sigue igual

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Emiliax16** [comment]
Hola @ComPups ! para borrar archivos simplemente ejecuta la siguiente línea en tu terminal **desde el directorio de tu repositorio**:

`git rm -r --cached nombre_archivo`

Como ya los tienes ignorados, al volver a hacer commit y push de tus cambios no se deberían volver a subir. Igualmente si te da cosa borrar algo que no debes, puedes respaldar tu carpeta completa en otro lugar en caso de necesitarlo.
Saludos!

**Comment by ComPups** [comment]
Muchas gracias ! Ahí lo solucioné
