### ISSUE TITLE
Consulta respecto demo.py y .gitignore

### ISSUE THREAD

**Issue by aecanales** [IIC2233/Syllabus#182]
Hola! Estuve leyendo el enunciado de la T02 pero hay un detalle que no me quedó claro.

Si entendí correctamente, debemos rellenar las funciones `demo.py` como `consulta_usuario()`, `consulta_ganadores()`, etc. con nuestro código propio de manera que ejecute la funcionalidad pedida.

En la sección 4.6, respecto la implementación de `.gitignore` se dice que

> **deberás** agregar un tu carpeta `Tareas/T02/` un archivo llamado `.gititgnore`* de tal forma de **no** subir los archivos de la carpeta `gui`...

Sin embargo, `demo.py` se encuentra en la carpeta `gui`, por lo que no se subiría al repositorio. ¿Es necesario mover `demo.py` a otra carpeta entonces? ¿O entendí mal cuando pensé que tenemos que rellenar `demo.py`?

¡Gracias de antemano!

**Sí, está así en el enunciado, es un typo*

**Comment by jachavarri** [comment]
Tengo la misma duda

**Comment by aecanales** [comment]
Al final decidí que voy a hacer mi propio script "`main.py`" afuera de la carpeta GUI pero copiando el código de `demo.py` (no le he probado pero debería funcionar...), de esa manera pudiendo ignorar toda la carpeta. ¯\_(ツ)_/¯

**Comment by ptflores1** [comment]
Hola !
Lo unico que pueden subir de la carpeta `gui` es` demo.py`
Saludos !
