### ISSUE TITLE
comando all

### ISSUE THREAD

**Issue by benjadelgado** [IIC2233/Syllabus#182]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola y gracias de antemano, mi pregunta es si puedo usar el comando all, no recuerdo si lo pasamos explícitamente en intro a la progra. Quedo atento, saludos!

**Comment by vgalfaro** [comment]
Hola! sí puedes ocupar all(), fue contestado en #10 ([aquí](https://github.com/IIC2233/Syllabus/issues/10#issuecomment-2310445934)), saludos!
