### ISSUE TITLE
Contenido primera actividad sumativa

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#182]
Hola!
Para la primera actividad sumativa mencionaron que entraba sólo el contenido de la semana 2, pero igual quería preguntar si era posible que incluyeran el contenido de la semana 1.¿?
Gracias!

**Comment by Drpinto1** [comment]
¡Hola!

En general, para todas las actividades del curso necesitarás una cierto entendimiento de la materia vista hasta el momento, sin embargo, **solamente se va a evaluar la materia de la semana**.

En particular la materia de las primeras semanas (paths, modularización, estructuras de datos y OOP) es escencial para el resto del curso, por lo que te la encontrarás repetidamente y es importante que la entiendas, pero, por ejemplo, para este jueves será más importante modelar correctamente el programa que elegir la estructura de datos más eficiente. 

¡Saludos!
