### ISSUE TITLE
error al usar git pull y git push

### ISSUE THREAD

**Issue by JPBarrosG** [IIC2233/Syllabus#182]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

intentando subir unos archivos parece que se me a divergido los archivos entre los distintos repositorios, intentando arreglar el problema con codigos de internet la situacion termino empeorando, esto son los mensajes que me salen al intentar hacer un git pull y in git push:
![image](https://github.com/IIC2233/Syllabus/assets/142442997/786648ae-0240-4f12-a21c-498c45758b32)
tambien al usar el comando "git merge --abort" y tratar de hacer un "git pull" se me abre la siguiente interfaz:
![image](https://github.com/IIC2233/Syllabus/assets/142442997/1d404fa4-d53b-4da5-9282-ca4a3518598a)
que puedo hacer para arreglar esto y poder subir al repositorio los avances de mi tarea?

**Comment by Hernan4444** [comment]
Hola @JPBarrosG 

Para efectos de este curso, primero es recordar que siempre se haga `git pull` cuando vayas a trabajar para evitar este caso. Ahora que ya ocurrió, recomiendo hacer `git clone` de tu repositorio en otra carpeta, abrir esa carpeta y pegar los nuevos archivos, luego hacer add commit push. Finalmente, la carpeta anterior que tiene conflictos eliminarla.

Saludos!
