### ISSUE TITLE
Duda ejerc prop 2.2 s-03 (Bonito Diamante)

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#182]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, tengo la duda de si se puede hacer uso de kwargs en el código de este ejercicio de manera que funcione bien (que el mismo código del final se ejecute sin problemas), y si es que sí, cómo sería.

Desde ya gracias.

**Comment by aaossa** [comment]
Hola @JuanpaBC , tal como dice el ejercicio, solo debes copiar y pegar una vez el método y el atributo presentados en el ejercicio, y sin modificarlos. Si haces eso, deberías encontrar una forma en la que el código pueda ejecutarse sin arrojar excepciones (consejo: lee bien el código del final 👀 )

**Comment by JuanpaBC** [comment]
Hola Antonio, mi duda no era orientada a cómo lograr el objetivo del ejercicio, sino a las preguntas que plantean al final una vez que se logra hacer funcionar el código, para las cuales imagino que podrían tener que ver con el uso de kwargs, pero aún asi no siento tener respuestas seguras para ellas, por si me pueden orientar un poco.

Adjunto una foto con las preguntas a las que me refiero:
![image](https://user-images.githubusercontent.com/80859173/113747220-26e9f780-96d5-11eb-84cd-bd290150c171.png)

De todas maneras gracias.

**Comment by aaossa** [comment]
Hola @JuanpaBC , en verdad usar `**kwargs` es una de las opciones. Y estuve luchando un rato con el código para poder confirmar que funciona. El problema se produce porque las clases `HibridoTarea` e `HibridoDocencia` heredan de `FullTarea` y `FullDocencia` en disinto orden, esto implica que el MRO de ambas clases es distinto:

```python
>>> print(HibridoTarea.__mro__)
(<class '__main__.HibridoTarea'>, <class '__main__.FullTarea'>, <class '__main__.FullDocencia'>, <class 'object'>)
>>> print(HibridoDocencia.__mro__)
(<class '__main__.HibridoDocencia'>, <class '__main__.FullDocencia'>, <class '__main__.FullTarea'>, <class 'object'>)
```

La solución más intuitiva es dejar el mismo orden en ambas clases, pero esto no es correcto 😅 No deberías asumir el orden de la multiherencia porque este puede variar según las necesidades de quien esté programando la subclase, además que sería un comportamiento no esperado (el que tengas que heredar en cierto orden). En los mismos ejemplos de los contenidos se introduce el uso de `super()` para solucionar esto, lo que está súper bien 👌 

Ahora, si quieres usar `**kwargs`, tienes que tener ojo al instanciar las clases (y también al usar `super`) de ir pasando los argumentos por palabra clave, es decir, `HibridoDocencia(nombre="A", mensaje="B")`. Esto funcionaría y no sería tan limitante como tener que condicionar el orden de la multiherencia, pero también tiene sus limitaciones. 

Por otra parte, me propuse intentar hacer una implementación lo más completa posible. No estoy seguro de si dejar todo el código acá porque prefiero que le des un par de vueltas, pero puedo dejarte algunos consejos:

* Mira la modelación, ¿hay comportamiento o atributos que sean comunes entre las clases? La respuesta es sí, de hecho por eso ya hay multiherencia de `FullDocencia` y `FullTarea`, pero fíjate en estas dos últimas clases. Hay comportamiento similar que podría dejarse en una clase aparte y así sabes que el MRO de todas las clases siempre termina en esta nueva clase. Esto significa que sabes donde puedes dejar de llamar a `super()`, o al menos donde llegarán finalmente todos tus argumentos.
* También ten ojo con cómo pasas los argumentos al hacer esto. Ya tienes bien la idea de que hay que usar `super()`, pero como adelanto te puedo decir que aquí no es necesario usar `**kwargs` y solo tuve que usar un `*args`, por lo que no tuve que cambiar el código principal 🙌 

Si te tinca, puedes intentar hacerlo de esta última manera y preguntar por acá por si tienes alguna idea o duda (bueno, en verdad la invitación es para cualquier persona). Lo encontré un buen ejercicio y quedé feliz con el resultado 😅 ¡Mucho éxito con tu estudio 💪 !

**Comment by JuanpaBC** [comment]
Muchas gracias Antonio! Intentaré con *args en cuanto pueda pero ya estoy muy agradecido con todo el feedback que me has dado hasta ahora!

**Comment by JuanpaBC** [comment]
Hola Antonio, finalmente traté de implementar los tips que me dejaste para una mejor solución, y pude conseguir que el código funcionara bien creando la superclase Ayudante, donde se definen los atributos "nombre" y "mensaje_de_apoyo", y de la que heredan las clases FullDocencia y FullTarea. En los __init__ de ambas clases anteriores ocupe el método super() para llamar al __init__ de ayudante, entregando al respectivo método los parámetros "nombre" y "mensaje", de la siguiente forma:
![image](https://user-images.githubusercontent.com/80859173/113938713-f7b4b280-97c8-11eb-84a6-36b8bb1a40dc.png)

No sé si calza con la solución que encontraste tu, si es que no, podrías compartirmela?

Muchas gracias por toda la ayuda!

**Comment by aaossa** [comment]
Hola @JuanpaBC , la solución a la que llegué se ve bastante parecida, dejando los atributos en la clase común `Ayudante` y pasando los valores que recibe el `__init__` a las superclases para no tener problemas sobre si una clase tiene o no el atributo 👌 ¡Éxito mañana en la actividad! 🙌

**Comment by JuanpaBC** [comment]
gracias!
