### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#182]
No entiendo como usar el comando, y leí por ahí (no me acuerdo donde) que desde la actividad de mañana se va evaluar el saber utilizarlo, alguien me podría explicar como utilizarlo por favor.

**Comment by iqacevedo** [comment]
Hola !
[Aquí](https://stackoverflow.com/questions/27850222/what-is-gitignore-exactly/27850270) puedes encontrar información sobre este archivo.
