### ISSUE TITLE
Puntaje cuando el usuario se rinde

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#183]
Hola!!
Cuando el usuario solicita rendirse ¿Su puntaje debe ir a puntajes.txt?

**Comment by amahns1** [comment]
Si!! En el enunciado aprece.

**Comment by DCCollao** [comment]
Me ganó @amahns1 😞 pero confirmo! En la sección de puntajes sale que se asigna puntaje en caso de victoria, derrota o rendición.

**Comment by Margarita-Paz** [comment]
Gracias!
