### ISSUE TITLE
Tabulación vs Espacios

### ISSUE THREAD

**Issue by jturquiza** [IIC2233/syllabus#183]
Hola, leyendo los puntos a considerar por PEP8, aparece que se deben usar espacios y no tabulaciones. Mi pregunta es ¿como puedo saber si mi codigo presenta la identación con tabulaciones? 
Muchas gracias de antemano

**Comment by Dnpoblete** [comment]
Hola @jturquiza, lo que preguntas se respondió en la issue #145. De todos modos, lo de las tabulaciones se refiere al uso del botón tab (el que tiene dos flechas opuestas) y lo deberías de saber ya que probablemente recuerdas si ocupaste o no ese botón. De todos modos lo puedes revisar verificando que cada indentación sean 4 espacios efectivamente.

Espero haber respondido tu duda y si no fue así avisame para poder ayudarte :smile:
