### ISSUE TITLE
Duda tiempo entre muerte de alien y aparición del siguiente par

### ISSUE THREAD

**Issue by nicolasgarciaes** [IIC2233/Syllabus#183]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda con respecto al tiempo que pasa mientras el segundo alien "murió" y este "muerto" va cayendo hacia abajo.
Dicho tiempo en que el alien va bajando, se considera como tiempo de la ronda efectivo? es decir, si la ronda dura 10 seg por ejemplo, el tiempo mientras va bajando el alien, se debería congelar? con el fin de no perjudicar al jugador, hasta que aparezca el nuevo par de aliens.

**Comment by Emiliax16** [comment]
Hola @nicolasgarciaes ! la ronda comienza cuando se inicia el nivel y termina una vez se haya acado el tiempo, por lo que considera que la caía de los _aliens_ dentro del tiempo. Igualmente, el enunciado dice: 
_" Luego de haberles disparados a ambos, aparecerán los otros dos"_ . Por lo tanto, basta con dispararles para que aparezcan los demás, por lo que tampoco debería haber un tiempo perdido en la ronda. Saludos!
