### ISSUE TITLE
Ocupar listas ligadas de contenidos de clases

### ISSUE THREAD

**Issue by akrebs2** [IIC2233/Syllabus#183]
Hola.

Si quisiera ocupar el código de listas ligadas que aparece en el documento "01-arboles y listas ligadas" de los contenidos del curso, debo citar? Es válido ocuparlo?

Lo mismo para cualquier otra estructura de ese tipo que aparezca en los documentos de los contenidos

**Comment by Mariana-Ortega-del-Rio** [comment]
Hay alguna forma específica de citarlo? Lo ponemos en el read.me? o  con # en el codigo?
