### ISSUE TITLE
ask y bid de un mismo usuario

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#183]
¿Un usuario puede hacer un ask y un bid en un mismo mercado? En ese caso podría haber match y el usuario se vendería monedas a sí mismo, por lo que perdería plata debido a la comisión del mercado

**Comment by egromero** [comment]
Hola, no está especificado en el enunciado, así que queda a tu criterio. No olvides anotarlo en el README. 

Saludos
