### ISSUE TITLE
Menú, opción 1: ¿qué tablero mostrar?

### ISSUE THREAD

**Issue by sguridirt** [IIC2233/Syllabus#183]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En la opción `[1] Mostrar tablero`, ¿qué tablero hay que mostrar?

Al inicio del programa, si se abrió un tablero válido, mostraría el tablero original. **Pero si se limpia el tablero al seleccionar la opción [2], al seleccionar nuevamente la opción [1]**, ¿el programa debe mostrar el original o el limpio? 

El enunciado es poco explícito respecto al tema. Hasta ahora, tengo un supuesto para explicar mi procedimiento.

**Comment by Hernan4444** [comment]
Hola @sguridirt 

Cómo se indica en el enunciado

![image](https://github.com/IIC2233/Syllabus/assets/15641721/1914d863-0cfd-4dd6-b657-a34a666d9a13)


Si es que escoges la opción 2, desde ese momento todas las demás opciones deben hacer uso del tablero limpio. Por lo tanto, si luego pones la opción 1, debes mostrar el tablero límpio.

Saludos!
