### ISSUE TITLE
Ortografía parámetros

### ISSUE THREAD

**Issue by cchauriye** [IIC2233/syllabus#183]
Hola!

En los parámetros podemos encontrar todo escrito en mayúscula y sin tildes, mientras que en los archivos se encuentra en otro formato. Por ejemplo en el archivo parametros.py dice "AUTOMOVIL" mientras que en vehiculos.csv se encuentra como "automóvil". ¿Puedo modificar manualmente los parámetros para que estén en el mismo formato o solo puedo hacerlo a través de código?

Gracias

**Comment by jeschuwirth** [comment]
Hola!

Como parámetros te entrega nombres de variables no debería ser problema el formato en el que están. 

Para simplificar el trabajo del ayudante a la hora de corregir **no** cambies el nombre de las variables definidas en parametros, ya que así cuando el ayudante lea tu código va a saber que es lo que viene de ese archivo y que cosas definiste en tu código.

Suerte!

**Comment by ranelson1** [comment]
recomiendan abrir los codigos con encoding = "utf-8" o no? Porque algunos tienen tilde y el editor de texto y terminal no me los estan reconociendo como tildes

**Comment by jeschuwirth** [comment]
Hola!

Por lo general siempre se va a utilizar encoding= "utf-8" para tareas de avanzada, de todos modos está muy bien que lo preguntes antes de asumirlo.

Suerte!
