### ISSUE TITLE
% de infectados o muertos

### ISSUE THREAD

**Issue by JoseValencia125** [IIC2233/Syllabus#183]
Del enunciado "La infección esta capacitada para transmitirse por via aerea despues de haber contagiado un 4 % de la poblacion mundial", ¿después de eso queda para siempre con la capacidad de trasmitirse por aire? ¿ese 4% es de la población mundial viva o total? Cuando solo quede por ejemplo un 10% de la población inicial y de ese 10% el 4% esté infectado ¿se transmite por el aire?

**Comment by arturodelreal** [comment]
Se considera un 4% de la población total inicial, y la capacidad dura para siempre.

**Comment by gbordoni** [comment]
En la misma linea de la pregunta, para la cola de prioridades cuando dice: 

> El gobierno propondrá
> cerrar su frontera si más de la mitad de la poblacion esta infectada o un cuarto de la poblacion muerta.

Se refiere a la mitad de la poblacion infectada con respecto a la poblacion inicial o respecto a la poblacion viva?

**Comment by consuvalencia** [comment]
yo creo que se refiere a la población viva para hacer ambos cálculos.. porque si no, no se podrían volver a reabrir los aeropuertos o fronteras nunca (a menos que se encuentre la cura). Pero no estoy segura jaja

**Comment by gbordoni** [comment]
@arturodelreal zzzzz

**Comment by arturodelreal** [comment]
Consideren la población total.

**Comment by consuvalencia** [comment]
no entiendo a que te refieres con población total.. la actual? inicial? total mundial?

**Comment by arturodelreal** [comment]
La inicial del país
