### ISSUE TITLE
Instancia vs Subclase

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#183]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Intenté buscando esto en internet, pero no entendí las respuestas que encontré, pues a veces se ponían muy técnicos, pero me gustaría saber bien la diferencia entre instancia y subclase, y algún ejemplo de objetos que uno sea instancia pero no subclase, y uno donde sí sea subclase pero no instancia.
![image](https://user-images.githubusercontent.com/66154723/113524986-4c192180-9580-11eb-890b-d002831b5d54.png)
## La duda me surgió cuando vi el uso de esos operadores.

**Comment by Christian-Klempau** [comment]
Hola! voy a comenzar explicándote que es una instancia y qué es una subclase:
- **instancia**: se denomina una instancia a un objeto que fue creado y guardado en memoria. Por lo tanto, lo puedes entender como una _entidad_ creada a partir de otra cosa, que guarda información. Por ejemplo dada una clase `Perro`, con un atributo `nombre`. Acá, `perrito = Perro("juan")`, la variable `perrito` almacenaría la **instancia**, con sus datos respectivos, como lo es su nombre. Nótese que `Perro` no almacena ningún nombre, sino que simplemente actúa como plantilla en ese caso, para que las instancias puedan guardar el dato en específico. 
Ahora, como Python es un lenguaje orientado a objetos, prácticamente todo es un objeto. Las clases son objetos, los ints, los strings, etc. Por lo mismo, si yo defino: `a = 3`, este `a` vendría siendo una **instancia** de int. En este mismo caso, `a` no sería una subclase de **int**, por el hecho que `a` NO es una clase, pero `a` SÍ sería una instancia de int.

- **subclase**: una subclase corresponde a una clase, que mediante herencia, obtuvo una clase padre/madre. Siguiendo el ejemplo, supongamos que tenemos la clase `Animal`, de la cual hereda `Perro`. En este caso, como `Perro` hereda de `Animal`, `Perro `sería una subclase de `Animal`. Aún así, Perro NO sería una instancia de Animal, ya que no está guardado como entidad específica aparte. Ahora, en el mismo caso, `perrito` sí sería una instancia de `Animal`. 
¿Por qué? Esto sucede porque, técnicamente `perrito `es una instancia de `Perro` (de hecho, `isinstance` arroja verdadero en este caso), pero TAMBIÉN es una instancia de `Animal`. Esto sucede debido a la herencia, ya que todo Perro debe ser Animal, debido a la herencia.

Espero se haya entendido la explicación. Si te quedaron dudas, no dudes en preguntar!

**Comment by fernandosmither** [comment]
> Hola! voy a comenzar explicándote que es una instancia y qué es una subclase:
> 
> * **instancia**: se denomina una instancia a un objeto que fue creado y guardado en memoria. Por lo tanto, lo puedes entender como una _entidad_ creada a partir de otra cosa, que guarda información. Por ejemplo dada una clase `Perro`, con un atributo `nombre`. Acá, `perrito = Perro("juan")`, la variable `perrito` almacenaría la **instancia**, con sus datos respectivos, como lo es su nombre. Nótese que `Perro` no almacena ningún nombre, sino que simplemente actúa como plantilla en ese caso, para que las instancias puedan guardar el dato en específico.
>   Ahora, como Python es un lenguaje orientado a objetos, prácticamente todo es un objeto. Las clases son objetos, los ints, los strings, etc. Por lo mismo, si yo defino: `a = 3`, este `a` vendría siendo una **instancia** de int. En este mismo caso, `a` no sería una subclase de **int**, por el hecho que `a` NO es una clase, pero `a` SÍ sería una instancia de int.
> * **subclase**: una subclase corresponde a una clase, que mediante herencia, obtuvo una clase padre/madre. Siguiendo el ejemplo, supongamos que tenemos la clase `Animal`, de la cual hereda `Perro`. En este caso, como `Perro` hereda de `Animal`, `Perro `sería una subclase de `Animal`. Aún así, Perro NO sería una instancia de Animal, ya que no está guardado como entidad específica aparte. Ahora, en el mismo caso, `perrito` sí sería una instancia de `Animal`.
>   ¿Por qué? Esto sucede porque, técnicamente `perrito `es una instancia de `Perro` (de hecho, `isinstance` arroja verdadero en este caso), pero TAMBIÉN es una instancia de `Animal`. Esto sucede debido a la herencia, ya que todo Perro debe ser Animal, debido a la herencia.
> 
> Espero se haya entendido la explicación. Si te quedaron dudas, no dudes en preguntar!
## Solucionado.
Más claro que agua de Bodrum. Muchas gracias!

**Comment by Christian-Klempau** [comment]
Genial, de nada!
