### ISSUE TITLE
Error sobre test_04: crear_predios

### ISSUE THREAD

**Issue by csneira** [IIC2233/Syllabus#184]
![Captura de pantalla 2024-08-25 230729](https://github.com/user-attachments/assets/ab89266f-d6e6-47ee-b4d9-b2bbd995e227)

### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[No entiendo el error, he editado muchas veces la función **crear_predios**, la he revisado mil veces y pruebo el test específico y no logro visualizar en qué me equivoco] PD: De las funciones anteriores, todas pasan los test cases, excepto función regar ()

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by individuocomunycorriente** [comment]
Hola!
Ese test específicamente se encarga de verificar que tu método **crear_predios** de DCCultivo esté completando correctamente el atributo **plano_riego** de las clases Predios. 
Sin embargo, el error que muestras en la imagen es porque (siguiendo el enunciado) tu método no está encontrando el archivo donde se extraerá la información para crear los predios, te recomiendo verificar que tengas intacta la carpeta /data de tu tarea (a esto me refiero sin cambios en el archivo que contiene) y que en tu método estés accediendo correctamente a un archivo hipotetico de la carpeta /data que posea el nombre **nombre_archivo**. Recuerda manejar **nombre_archivo** como una variable y no hardcoodear el nombre del archivo que se encuentra en la carpeta /data.
Quedo atento a tu respuesta.

**Comment by Johan-10** [comment]
Mmm me paso algo parecido cuando ejecutaba este test, al final resulto que el error estaba en que estaba "printeando" la respuesta en vez de **retornarla** recuerda que el metodo crear_predios() **retorna** un del resultado string y no hace print del resultado.

**Comment by mmleivad** [comment]
Hola, tengo el mismo error y no me quedo del todo claro. ¿Se debe asumir que todos los archivos nombre_archivo utilizados en los test case pertenecen a la carpeta /data, como si fuera alguna ruta relativa o absoluta? O simplemente puedo acceder a nombre_archivo?

**Comment by individuocomunycorriente** [comment]
Hola!
Así es, se debe asumir que el archivo siempre se encuentra en la carpeta data/ y para manejar las rutas te recomiendo investigar sobre path.join de la librería os.
Saludos.
