### ISSUE TITLE
Duda sobre cheatcodes 

### ISSUE THREAD

**Issue by Fernanda-Bley** [IIC2233/Syllabus#184]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
*¿A que se refiere cuando dice "Esta combinación pasa inmediatamente al siguiente nivel de la partida." con C+I+A?*
Fui capaz de hacer que detecte la combinanción pero no que se salte el menú final ¿Es necesario que lo salte? Actualmente lo que pasa cuando se escribe C+I+A ganas por default.
¿Puedo dejarlo así o se descontaran puntos?
Quedo atenta a su respuesta,
Fernanda

**Comment by Emiliax16** [comment]
Hola @Fernanda-Bley ! parte de lo que dices se responde en la issue #151 . Efectivamente esa combinación de teclas hace que se gane (por lo que en la ventana post-nivel debes ser capaz de pasar al siguiente), pero las estadísticas que se muestran deben las que se lograron calcular hasta el momento de ejecutar el cheatcode. Saludos!
