### ISSUE TITLE
Volver del menú de entrenador al menú de inicio.

### ISSUE THREAD

**Issue by TarekHirmas** [IIC2233/Syllabus#184]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Si en el menú de inicio elijo a un entrenador y posteriormente en el menú de entrenamiento selecciono volver, que se supone que el menú de inicio le mostrará los entrenadores disponibles y le hará seleccionar una opción, asumo que en ese caso se puede cambiar de entrenador o no es posible?

**Comment by TarekHirmas** [comment]
En otras palabras más simples, si alguien decide volver al menú de inicio puedo suponer que se esta iniciano una nueva partida desde cero?

**Comment by bthompsonl** [comment]
Para el caso del _**Menú del entrenador**_, al volver al menú de inicio, si es que había un torneo en curso, hay  que continuarlo? o al elegir de nuevo al entrenador se empieza el torneo desde cero?

**Comment by TarekHirmas** [comment]
@NicolasBenavides me referia justo a lo que preguntó @bthompsonl

**Comment by NicolasBenavides** [comment]
@bthompsonl @TarekHirmas si vuelves al menú de inicio es para dar inicio a un nuevo torneo, todo lo hecho en el torneo anterior vuelve a su estado principal.
