### ISSUE TITLE
Duda con método "promedio_evaluaciones" ejer prop 3.1 s-03 (Concurso de Hamburguesas)

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#184]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, entiendo que el método "restar_stock" y "numero_clientes" de la clase abstracta "Hamburguesería" funcionan mejor como métodos no abstractos y conviene definirlos en la definición de la clase abstracta, ya que para todas las subclases este método ocupa atributos de la superclase (o sea, compartidos por todos) y de la misma forma. Por otro lado, el método "promedio_evaluaciones" entiendo que lo mejor es sobrescribirlo en cada subclase, ya que ocupa atributos específicos de cada subclase, pero mi duda es si hacer este metodo un método abstracto o no, pues no veo tanta diferencia entre ambos casos en cuanto a utilidad.

Desde ya gracias.

**Comment by nanglada** [comment]
Hola Juanpa 😀

Las clases abstractas son súper útiles cuando estás buscando instanciar métodos que no necesariamente planeas utilizar en tu superclase pero si en las subclases que heredan de esta. Es importante recordar que, al crear una superclase con x cantidad de métodos abstractos, en las subclases estos métodos deben ser instanciados o tu programa te tirará error.

 Tal como lo dijiste tu, "restar_stock" y "numero_clientes" son métodos que todas las subclases utilizan (sin modificaciones) por lo que no se debe poner como abstracta. En cambio, "promedio_evaluaciones" se debe instanciar como abstracta ya que necesitas que cada subclase sea capaz de hacer "overriding" y escribir específicamente lo que necesita. Siempre que un método de la superclase vaya a ser sobreescrito por la subclase, utiliza métodos abstractos.

Aunque esto parezca no ser tan útil a primera vista, te recomiendo que siempre intentes ocuparlo por un tema de buena práctica. En general, al utilizar métodos abstractos, le otorgas un orden y una claridad a tu código que permite que esta sea más legible y fácil de entender por un tercero, como pueden ser los ayudantes que corrijan tus tareas y actividades. De esta manera, si un tercero lee tu código, puede entender de inmediato que el método abstracto definido en la superclase debe ser modificado en las subclases. 

Ojalá te haya quedado todo un poquito más claro! Suerte 🙌

**Comment by JuanpaBC** [comment]
Muchas gracias Nati, me quedo más claro!
