### ISSUE TITLE
Duda sobre como eliminar archivos del repositorio personal

### ISSUE THREAD

**Issue by angedvq** [IIC2233/Syllabus#184]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

Hola, según el enunciado de la tarea 1, en el .gitignore debemos incluir ciertos archivos. Yo ya hice git push anteriormente a manera de tener un respaldo de mi avance de la T1 antes de crear el .gitignore, por lo que tengo subidos a mi repositorio esos archivos que debíamos ignorar. No sé como eliminarlos. Probé con git rm pero no me deja. Hay alguna manera de hacerlo?

**Comment by Hernan4444** [comment]
Hola @angedvq 

Recomiendo revisar la siguiente issue donde se toca ese tema y se da una solución para eliminar archivos que debían ser ignorados.

* https://github.com/IIC2233/Syllabus/issues/137

Saludos!

**Comment by angedvq** [comment]
gracias! solucionado
