### ISSUE TITLE
Donde Guardar El Diagrama

### ISSUE THREAD

**Issue by AngelMatias** [IIC2233/Syllabus#184]
Tal vez ya lo preguntaron, pero como es eso del cuestionario Siding para guardar el diagrama ??? 😰

**Comment by AngelMatias** [comment]
y necesario, en el diagrama, agregarle todos los metodos y atributos en el recuadro de la clases???

**Comment by andresfdezc** [comment]
![screen shot 2017-08-27 at 8 26 41 pm](https://user-images.githubusercontent.com/11430184/29754949-28646b14-8b66-11e7-9614-e0b1aed23bf0.png)
![screen shot 2017-08-27 at 8 26 49 pm](https://user-images.githubusercontent.com/11430184/29754950-298cb668-8b66-11e7-8215-e9639577636c.png)

**Comment by AngelMatias** [comment]
perfect, pero y necesario, en el diagrama, agregarle todos los metodos y atributos en el recuadro de la clases???

**Comment by andresfdezc** [comment]
Sí.

**Comment by AngelMatias** [comment]
perfect! gracias

**Comment by AngelMatias** [comment]
y algun formato en especial? porque lo estoy haciendo en power point

**Comment by andresfdezc** [comment]
Puedes crearlo en PowerPoint, pero entrégalo en algún formato de archivo de imagen, no en pptx.

Aquí hay una acotación sobre los atributos que se agregan en el diagrama: #69 .

**Comment by AngelMatias** [comment]
ok gracias !

**Comment by felipecr00** [comment]
Si cuando lei el enunciado interprete mal y pense que se subia junto con el repositorio hay alguna opcion que lo consideren. :/

**Comment by FernandoPieressa** [comment]
@felipecr00 El diagrama sera corregido sin embargo tendrá un descuento en ese ítem dentro de la corrección.
