### ISSUE TITLE
Cómo entrar a más de un except

### ISSUE THREAD

**Issue by fabarros** [IIC2233/Syllabus#184]
Hola, tengo una duda de la materia de esta semana.  Cómo puedo hacer que el programa maneje más de una excepción a la vez? En la ayudantía vimos un caso en el que los datos ingresados "cumplían con más de un error a la vez" pero al manejar las excepciones sólo puedo atrapar la primera que detecta. Por ejemplo hice una pequeña modificación del In[12] del material de manejo de excepciones:
```python    
    try:
        print(dividir(-4.5, 0))

    except TypeError as err:
     # Este bloque opera para los tipos de excepciones definidos en la tupla entregada.
        print("Error: {}".format(err))
        print("Revise los datos de entrada\n")
    
    except ZeroDivisionError as err:
        print("Error: {}".format(err))
        print("Revise el denominador")
    
    except ValueError as err:
        # Este bloque sólo maneja excepciones del tipo ValueError
        print('Error: {}'.format(err))
        print('Cambie los valores de entrada\n')`
```

en este caso la salida es `Error: Los números deben ser del tipo int
Revise los datos de entrada`, es decir, sólo atrapa el primero y no los otros. Pero, y si quiero manejar todos los posibles errores?

**Comment by fabarros** [comment]
Entiendo, pero ¿hay laguna forma de que el programa ejecute el código que está dentro de más de un `except`? Siguiendo con mi ejemplo, si dentro del primer `except` cambio los parámetros que son `float` por `int`, ¿cómo puedo verificar que no sigue ocurriendo ningún otro error? (ya que en este caso sigue ocurriendo que se divide por cero)

**Comment by MrEarle** [comment]
No existe ninguna forma directa de hacer eso. Podrías tener una función que se encargue de los try except, para que cuando llames a división vuelva a entrar a un try y maneje el ZeroDivisionError.
Por ejemplo:
```
def division_manejo_excepcion(a, b):
try:
    print(dividir(a, b))

except TypeError as err:
 # Este bloque opera para los tipos de excepciones definidos en la tupla entregada.
    print("Error: {}".format(err))
    print("Revise los datos de entrada\n")
    print(division_manejo_excepcion(a_nuevo,b))

except ZeroDivisionError as err:
    print("Error: {}".format(err))
    print("Revise el denominador")

except ValueError as err:
    # Este bloque sólo maneja excepciones del tipo ValueError
    print('Error: {}'.format(err))
    print('Cambie los valores de entrada\n')`
```

O la otra opción (menos limpia) sería que pongas otro try/except adentro del except. Personalmente no te recomiendo la última, Ya que deja tu código con muchas líneas repetidas innecesariamente.

**Comment by fabarros** [comment]
Qué grande, esa recursión era lo que andaba buscando. Muchas gracias :D
