### ISSUE TITLE
T00 - Repetir turno luego de acertar

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#184]
Luego de que el jugador encuentra un barco abrimos el menú de juego, dando la opción de rendirse o tiene obligación de tirar una bomba nuevamente hasta no encontrar barco, luego juega el oponente y recien ahi abrimos el menú de juego, dando ahora la opción de rendirse.

**Comment by DCCollao** [comment]
Según enunciado:

> Una vez ingresadas las coordenadas del disparo, si estas son válidas, se actualizarán los tableros y se volverá a mostrar el Menú de Juego.

Independientemente de si el jugador encuentra un barco o no, se debe abrir el menú de juego luego de realizar un disparo.

**Comment by YehudaGurovich** [comment]
Dale! Esque en el enunciado tambien dice:
"Si no aciertas a un barco oponente, se pasa al turno del contrario. Si le das a un barco oponente, puedes volver a disparar" y me estaba guiando con eso, y no queda tan claro de esa parte del enunciado pero ahora quedo clarisimo. Sorry :/
