### ISSUE TITLE
Malas practicas uso variables globales

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#184]
En el archivo descuentos dice lo siguiente:
Si se encuentran malas prácticas en el código de la tarea, como el uso de variables globales, será penalizado. Cualquier duda con este descuento, haga una issue.

A que se refiere cuando dice uso de variables globales?

**Comment by KnowYourselves** [comment]
Hola @dsepulveda3!

Variables globales son todas las variables que no han sido definidas dentro de una función y se utilizan de todas formas. Un ejemplo:

```python3
nombre = "DDCollao"

def print_nombre():
    print(nombre)
```

Aqui estás haciendo uso de la variable `nombre` globalmente, en vez de recibirla como argumento de la función. También esta prohibido el uso del _built-in_ `global`.

Espero haberte ayudado!
