### ISSUE TITLE
Uso de "sorted"

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#184]
Hola!

Podemos usar la función `sorted` para ordenar nuestras estructuras? Estoy consciente que esta función retorna una lista, por lo que esta sería desempaquetada inmediatamente en una de nuestras EDD.

Saludos!

EDIT: El sorted solo sería usado para hacer la función sort. :)

**Comment by acrojas2** [comment]
Con respecto a esta pregunta:
Yo entendí que teníamos que implementarlo nosotros mismos... ¿Hay que hacerlo o no?

**Comment by akaminetzkyp** [comment]
Me faltó decir que el sorted sería parte de nuestro método sort. No usaría el sorted suelto. :)

**Comment by nvielva** [comment]
que ocurrio con esta pregunta?? se puede usar sorted?

**Comment by stephichau** [comment]
Tienen que crear su propio algoritmo de ordenamiento.

Saludos!
