### ISSUE TITLE
Duda probabilidad accidente

### ISSUE THREAD

**Issue by itplanella** [IIC2233/syllabus#184]
Hola! En la formula de probabilidad accidente, la parte de (durabilidad_maxima_chasis - durabilidad_actual_chasis)/durabilidad_maxima_chasis, esta dentro de un parentesis cuadrado o se refiere a que se utiliza la funcion piso? Gracias de antemano

**Comment by jmwielandt** [comment]
Hola! 😄

No es un paréntesis cuadrado, es `⌊cosa⌋` que tal como dices, es la función piso. 👍 

Te recomiendo revisar el link del footnote 17 del enunciado, ya que esta función aparece en varias fórmulas. 😅 

![image](https://user-images.githubusercontent.com/37153467/64476977-c3e45780-d163-11e9-976b-407e5a4bfc48.png)

(Está al final de la página 13).

Saludos~
