### ISSUE TITLE
Sobre contenidos de años anteriores

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2233/syllabus#184]
Hola.
Este año, el nivel de exigencia del curso bajó mucho comparado con otros años, según me he enterado. Esto está bien en cuanto a los créditos que tiene, pero los contenidos que se pasan este año son muchos menos que los años anteriores. Yo, personalmente, quiero seguir en el área de programación y computación, por lo que me interesa fuertemente tener acceso a contenidos suplementarios a los que se pasan en el curso este año. Por esta razón, quisiera pedir que habilitaran los contenidos de semestres anteriores, para poder aprender más.

Por otro lado, como sugerencia, podrían poner contenidos opcionales para los interesados, que quisieran profundizar en las diferentes partes del curso.

Gracias

**Comment by fdoflorenzano** [comment]
¡Hola @JJJGGGG!

Efectivamente hicimos cambios en el curso para bajar la carga que tiene sobre los alumnos. Pero, a diferencia de como dices, no son muchos menos contenidos que el semestre pasado. Fueron solo 3 temas los que se removieron como mínimos del curso este semestre, debido a que estos se cubren en futuros cursos de la especialidad.

Sobre lo que pides, ya nos adelantamos. Esto es exactamente lo que son los talleres: proporcionar  temas eliminados del programa como opcionales. Los temas revisados en los talleres de este semestre no son mínimos del programa de esta versión del curso (y por eso nunca los evaluamos), y corresponden exactamente a los temas eliminados. El primero era Programación Funcional, y se subió el material correspondiente a semestres pasados durante el periodo de la T01.

Nos alegra escuchar que te interesa seguir por el mundo de la computación 😄. Una de las gracias de este curso es abrir tu perspectiva a la programación y que seas capaz de empezar a investigar por tu cuenta. Internet es una vasta fuente de conocimiento, y puedes profundizar en el muchos de los contenidos y encontrar unos nuevos. Si quieres seguir aprendiendo aún más, puedes empezar buscando.

También no dudes en publicar *issues* preguntando por referencias de temas anexos específicos, tal vez conocemos fuentes ajenas al curso que podemos recomendarte.

Saludos.
