### ISSUE TITLE
Evaluación ítems de la pauta

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#185]
Hola,
En la pauta leí qué hay algunos ítems como el uso de multi-herencia, pero yo al modelar y pensar como voy a hacer la tarea pensé que no era 100% necesario utilizar multi-herencia. Si este ítem sale en la pauta, significa que si o si lo debo implementar para obtener el puntaje o este puntaje se asigna solamente si alguien usa multi-herencia?

**Comment by tomasgv** [comment]
Hola! 

Dado que en la pauta se evaluará el uso correcto de multi-herencia, deberás implementarla para obtener todo el puntaje en ese ítem. Por lo tanto, si no la implementas no tendrás puntaje en esa sección.

Saludos y éxito en tu tarea! 🎊
