### ISSUE TITLE
Consulta README errores

### ISSUE THREAD

**Issue by aleuribej** [IIC2233/Syllabus#185]
Hola! Tengo una consulta con respecto a la parte de explicar lo que no funciona bien 😔. Tengo que explicar a grandes rasgos lo que no funciona, o puedo explicar porque falla mi código en ciertas partes (Ej: Linea 18 : list index out of range) ?

**Comment by Arcoirisky** [comment]
Si explicas el porqué más detallado nos ayudaría a entender mejor tu error O: ¡Trata de dar a entender cómo funciona tu programa lo mejor que puedas! Ánimo

**Comment by aleuribej** [comment]
Muchas gracias 😄 !!
