### ISSUE TITLE
Duda respecto al poder de los combatienetes

### ISSUE THREAD

**Issue by enzoacvi** [IIC2233/Syllabus#185]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola,

En el enunciado se dice que los distintos tipos de combatientes tienen una cierta probabilidad de activar sus poderes (p.e. prob_cab%), que es un atributo con un valor int de 0 a 10. Sin embargo, no entiendo qué implica esto debido a que el atributo poder del combatiente no se utiliza para calcular su ataque.

![issue t2 avanzada](https://github.com/IIC2233/Syllabus/assets/127432390/8d313c53-36ef-4ef9-89ab-bee409845f13)

No sé si quizás "sorprender al rival" significa activar el poder, pero en todo caso, no veo dónde el valor int de poder influye en esto.

Lo que quiero preguntar es: **¿dónde está la relevancia del atributo poder, si para que se active se requiere un parámetro externo y tampoco participa del cálculo del ataque del combatiente?** Esto lo pregunto para saber dónde se utiliza el atributo, dado que no me queda claro del enunciado.

De antemano muchas gracias 😊

**Comment by tebi01** [comment]
Hola!
El atributo ```poder``` de un peleador representa una cantidad de poder, no el "power-up" del combatiente, por así decirlo.

Este es usado en la siguiente fórmula, la cual calcula el atributo de ataque del Combatiente:

![image](https://github.com/IIC2233/Syllabus/assets/106035073/15aa63bc-662c-4c4f-b620-052576ee0f02)

Por lo tanto, deberías cuidarte de que al modificar el atributo poder de un enemigo, se recalcule su ataque mediante esa fórmula.

Saludos!

**Comment by enzoacvi** [comment]
Oh entiendo, gracias!

**Comment by IsidoraCarmona** [comment]
y con respecto a eso mismo, entonces activar su poder se refiere a sorprender al rival?

**Comment by tebi01** [comment]
Hola! @IsidoraCarmona 
Lamento la tardanza y espero que hayas podido aclarar tu duda antes de esta respuesta, pero claro, "activar el poder" se refiere a que se cumpla lo que se especifica en el enunciado (para cada tipo de Combatiente). En este caso, el poder activado del Caballero es la sorpresa al rival, lo que implica ese efecto en el daño provocado.
