### ISSUE TITLE
Ejercicio propuesto 2.2 Semana 2

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#185]
En el ejercicio "2.1: Autos deportivos" la variable fecha_actual no esta definida previamente ni se pide como parámetro al momento de ejecutar el método depreciacion_acumulada, eso es un error o como trabajo con esa parte?

**Comment by fdoflorenzano** [comment]
Hola @RonaldoSosa,

No es un error, es simplemente una referencia a la fecha actual en la que se haga el ejercicio. Si te fijas, las fechas que se usan al hacer instancias son simplemente el año. Puedes usar entonces el año actual como valor para `fecha_actual`. 

Saludos.

**Comment by RonaldoSosa** [comment]
Entendido, muchas gracias
