### ISSUE TITLE
Duda Con correr test_tablero_solucionar

### ISSUE THREAD

**Issue by SReynolds2022** [IIC2233/Syllabus#185]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

![t1 foto](https://github.com/IIC2233/Syllabus/assets/101474286/3b621691-a9da-4721-8faa-262571dbc1ca)

### Duda

Hola, Siento que ya termine la parte 1 de la tarea, al momento de correr los test cases de solucionar(), los primeros 4 test corren pero despues se queda pegado en el test case 4x4, espere unos minutos y no ha avanzado, hay alguna manera de resolverlo? saludos.

**Comment by Hernan4444** [comment]
Hola @SReynolds2022 

Si se quedó pegado, es que tu método de solucionar no está correctamente implementado y quedó en algún tipo de loop infinito o es que es muy lento para generar soluciones de tablero de 4x4 (lo cual no debería pasar porque siguen siento tableros pequeños).

Lo que recomendamos es probar en otro archivo utilizar tu método solucionar con el tablero del tests case 4x4, y agregarle `print` a tu código para determinar qué está pasando y tal vez identificar si faltó algún caso por programar.

Saludos!

**Comment by SReynolds2022** [comment]
Oka, Muchas gracias !
