### ISSUE TITLE
Duda sobre indexación

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#185]
Hola, al final ya me resultó avanzar pero en mi estructura de datos la indexación por defecto parte en 1... ¿lo puedo dejar así? Sé que normalmente se parte en 0 pero los strings y tablas (estructura de datos) de Lua (lenguaje de programación) tienen esa indexación que parte en 1 en vez de en 0 (y lo hicieron los de la PUC de río de janeiro, dato freak).
Se puede corregir MUY fácil pero igual encuentro que no habría mucho problema con dejarlo así.
Gracias :D

**Comment by Arcoirisky** [comment]
Hola! 
Puedes hacerlo, es tu estructura :D Igual déjalo escrito en el Readme en cualquier caso :)
