### ISSUE TITLE
Duda sobre la utilidad del uso de properties definiendo clases y sobre la manera de ocuparlos

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#185]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, aún después de revisar las clases, los ejercicios y las issues aun no he podido lograr entender bien cuándo conviene definir properties en una clase, para qué situaciones se ocupan en general y cómo se usan. 

Hasta el minuto tengo esta idea de que sirven si quiero existan restricciones para modificar ciertos atributos de la clase, pero no entiendo si se usa en ese caso las properties porque no hay otra manera de hacerlo o porque por alguna razón es más conveniente usarlas en esos casos.

Respecto al modo de usar las properties, entiendo que operan sobre atributos privados cuyos nombres parten con "_" o "__", pero he visto ciertos ejercicios donde no veo que se definan estos atributos privados en el método \__init__ pero sí en otra parte como en el getter de una propiedad, situación que me confunde harto porque no sé si al final se define o no el atributo privado. Un ejemplo de código que me hace surgir una confusión como la descrita, es el siguiente código usado en la guía 3 de la semana 03 (clases abstractas) para ejemplificar el uso de clases abstractas, con la property "energía":
![image](https://user-images.githubusercontent.com/80859173/113525130-2f311e00-9581-11eb-89e4-ab4d61782b84.png)

Desde ya gracias.

**Comment by aaossa** [comment]
Hola @JuanpaBC , intentaré responder a tus dos preguntas en el orden que las hiciste. 

**¿Cuándo usar una *property*?**: Primero, ¿qué ganamos al usar una *property*? La principal ventaja es que puedes introducir comportamiento o lógica cuando quieras pedir el valor de un atributo (*getter*), cuando quieras definir el valor de un atributo (*setter*) y cuando quieras eliminar un atributo (*deleter*). Ahora, ¿qué ejemplos de comportamiento podríamos querer introducir? Los típicos ejemplos son para definir los límites de un atributo numérico (que algo no sea menor que 0 o que no sea mayor que un límite) o para calcular un atributo que en verdad es una función de otros atributos (por ejemplo la energía total de un auto que se va moviendo, sería una lata tener que cambiar el atributo velocidad y energía cada vez, mejor usar una *property* para que se calcule sola la energía en base a la velocidad), pero esa es solo la punta del *iceberg*. Personalmente, no he usado *deleter*, pero sí he usado algunos *setter* y *getter* para sus usos tradicionales, (aunque también he usado un *setter* para hacer *debugging* y encontrar cuándo una variable cambiaba a un valor que no le correspondía, si hubiera hecho un método para esto hubiese tenido que cambiar cada lugar en el que se definiera la variable).

Ahora, **¿qué rayos ocurre en ese código?**. Tienes razón en que normalmente definimos una variable privada en la que conservamos el "verdadero valor" del atributo, lo que hacemos en el `__init__` de una clase con la línea `self.__variable = 0`. Aunque es cierto que no siempre lo necesitamos, como en el ejemplo de la energía, donde podríamos tener algo así:

```python
class Auto:

	def __init__(self, masa):
		self.masa = masa
		self.velocidad = 0

	@property
	def energia_cinetica(self):
		return self.masa * (self.velocidad ** 2) / 2

if __name__ == '__main__':
	mi_auto = Auto(2900)
	print(mi_auto.energia_cinetica)
	mi_auto.velocidad = 5
	print(mi_auto.energia_cinetica)
```

Ahora, ¿cuál es la diferencia puntual entre `self.__energia = energia` y `self.energia = energia`? La diferencia está en que la segunda pasa por el *setter*, pero la primera no. Esto significa que si usaramos la primera opción podríamos inicializar nuestra clase con un valor no válido, que es exactamente lo que no queremos que ocurra (por eso definimos esa *property*). Al usar `self.energia = energia`, estamos forzando a que la inicialización de cada instancia pase por nuestro *setter* (que actúa como función validadora).

Espero que mi respuesta te sirva y te lo haya dejado un poco más claro. Quizás las *properties* no parezcan gran cosa al inicio porque simplemente actúan como atributos, pero la gracia está en que las *properties* son una herramienta que podemos usar cuando necesitemos y cuyo potencial solo depende de qué hagamos con ellas. Si tienes alguna otra duda pregunta por acá mismo no más 👌 ¡Éxito con tu estudio y en la actividad!

**Comment by JuanpaBC** [comment]
Muchas gracias Antonio, me quedó muchísimo más claro con el ejemplo y la explicación!

**Comment by matyjjn14** [comment]
Hola! Estaba leyendo la respuesta de esta consulta ya que también estaba muy confundido con la funcionalidad de las properties y si bien entendí la idea básica no puedo llegar a comprender la dinámica que se muestra en la imagen. En específico, aún no logro entender por qué ese self.energia en la property se retorna como self.__energia. 
Por lo que entendí las properties se usan para atributos privados (que tienen "__" al comienzo? o estoy mal?

**Comment by matyjjn14** [comment]
entre esas comilla luego del "que tienen" van los __

**Comment by aaossa** [comment]
Hola @matyjjn14 , primero que todo, tal como expliqué en mi respuesta anterior no necesariamente necesitas un atributo privado para usar *properties*, solo es la forma más común de usarlas. Lo que te recomiendo para tener una idea más clara es es ver qué es lo que pasa cuando agregas unos `print` al código para que veas en qué orden ocurren las cosas:

```python
class Personaje:

    def __init__(self, nombre, energia):
        self.nombre = nombre
        print("(1) Creando atributo self.energia")
        self.energia = energia
        print("(2) Ya se creó el atributo self.energia")

    @property
    def energia(self):
        print("(get) Llamando al getter de energia")
        return self.__energia
    
    @energia.setter
    def energia(self, valor):
        print("(set) Llamando al setter de energia")
        self.__energia = max(valor, 0)

if __name__ == '__main__':
    yo = Personaje("Antonio", 100)
```

El *output* de ese código es el siguiente:

```
(1) Creando atributo self.energia
(set) Llamando al setter de energia
(2) Ya se creó el atributo self.energia
```

Si te fijas, mientras estamos inicializando la clase (dentro del `__init__`) se llama al *setter* del atributo, donde se declara `self.__energia`.  Ahora, cuando pidas el valor del atributo `energia`, es decir cuando llames al *getter*, Python va a ejecutar el método que declaraste y retornar el valor de `self.__energia`:

```python
>>> yo.energia
"(get) Llamando al getter de energia"
```

Con lo que creo que debes quedarte es que si tienes una *property*, cada vez que pidas el valor de ese atributo se llamará al *getter*, y cada vez que le des un nuevo valor se llamará al *setter*. Es solo eso. Las variables privadas son una de las formas de implementarlas (como la del ejemplo), pero no siempre las necesitas (el ejemplo de mi última respuesta). Si alguna de estas cosas no queda claras pregunta de nuevo no más 👌 La idea es que no quedes con dudas ✨ ¡Éxito con tu estudio!

**Comment by matyjjn14** [comment]
@aaossa ahora me quedó claro!! muchas gracias!!
