### ISSUE TITLE
Cantidad de Aliens que pueden aparecer al mismo tiempo

### ISSUE THREAD

**Issue by SVenegasA** [IIC2233/Syllabus#185]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Saludos,
Estoy muy confundido por una parte del enunciado, quizás lo estoy entendiendo mal, pero en el 3.2 cuando dice que ", no deben aparecer todos estos aliens al mismo tiempo, sino que deben ir apareciendo en parejas de manera que al destruir a ambos aliens, aparezca la siguiente pareja", **¿El enunciado quiere decir que solo pueden aparecer números pares de aliens, o sea 2, 4, 6, ... (en una misma pantalla)?, o **¿directamente el máximo de aliens que se encuentren de forma simultanea es 2?**, mi confusión viene porque se habla de que "al destruir a **ambos aliens**, aparezca la siguiente pareja"

**Comment by Emiliax16** [comment]
Hola @SVenegasA ! Supongamos que estás en el nivel 2, en este caso se aplica la fórmula para saber cuántos _aliens_ en total aparecerán durante la ronda:

`cantidad_aliens = nivel * 2`
`cantidad_aliens = 2 * 2`
`cantidad_aliens = 4`

Por lo tanto, en esa ronda aparecerán en total 4 _aliens_ (en el caso que no pierdas por quedarte sin balas o se te acabe el tiempo antes). Primero aparecerán 2 _aliens_ y una vez que termines de dispararle al segundo, inmediatamente aparecen los otros dos. Este es el mecanismo. Básicamente el máximo de _aliens_ vivos que pueden encontrarse en la pantalla son 2, por lo que la aparición del resto ocurrirá en parejas al momento de dispararle al último del par anterior. 
Avísame si me logré explicar correctamente. Saludos 😸

**Comment by SVenegasA** [comment]
Ahora lo entiendo, muchas gracias
