### ISSUE TITLE
Cierre y apertura de fronteras y aeropuertos

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#185]
Con respecto a esto, cuando el gobierno decide cerrar fronteras por ejemplo ¿Este cierra todas las fronteras? o ¿Cierra solo algunas de acuerdo a algún criterio?
Me parece que cierra todas pero quiero estar seguro.

**Comment by akaminetzkyp** [comment]
Según el issue #155 cierra todas.

**Comment by jorgeriesco** [comment]
buena
