### ISSUE TITLE
Módulo Logging para tareas.

### ISSUE THREAD

**Issue by nhorellana** [IIC2233/syllabus#186]
Hola! Estaba estudiando y me encontré con el módulo Logging para ir registrando errores en el código en un archivo externo, es recomendable implementar esto para las tareas o es nada que ver con la complejidad de lo que se pide?

**Comment by naquiroz** [comment]
Hola! :wave:

Personalmente creo que la librería `logging` es una librería muy útil de Python. Sin embargo, nunca he sabido de una tarea que la pida, o sea necesaria. Supongo que en su debido momento, podrás preguntar en la issue correspondiente si se puede usar la librería, siempre y cuando estimes que es útil.

Saludos!
