### ISSUE TITLE
Experiencia por vuelta

### ISSUE THREAD

**Issue by itplanella** [IIC2233/syllabus#186]
Hola! En el enunciado dice que si el jugador gana una vuelta se le dará dinero y experiencia, sin embargo, solo aparece la formula de experiencia para cuando el jugador GANA UNA CARRERA, y no la formula para cuando gana una vuelta. Mi pregunta es si se tiene que usar la misma formula, y de ser así, si ventaja_con_ultimo_lugar en ese caso debiera ser el tiempo de la vuelta y no el total. Muchas gracias de antemano.

**Comment by gatochico** [comment]
Hola!
Tienes razón, no hay una fórmula específica para la experiencia por vuelta :see_no_evil: Debido a esto, queda a tu criterio si:
- Haces que se gane experiencia por vuelta, con la misma fórmula, utilizando los tiempos como tu explicas (con tiempo de vuelta en vez de total).
- Simplemente, no se gane experiencia por vuelta.

Como siempre, pon tu decisión en el README para evitar cualquier problema. 
Lamentamos la confusión y saludos!

**Comment by francodonati** [comment]
Respeto a la experiencia ganada, ¿qué sucede en caso de que los contrincantes sean descalificados por accidentes o pérdida de chasis? ya que en ese caso, no tendrían un "tiempo asignado" ¿para esto debo considerar la diferencia de tiempo solo con los que terminaron la carrera? en caso de que ningún contrincante la termine, ¿asigno la experiencia a mi criterio?

Gracias

**Comment by gatochico** [comment]
Todo lo que indicaste es correcto!

- La experiencia se calcula con el tiempo de los que terminaron la carrera.
- Si nadie más terminó la carrera, queda a tu criterio cuanto asignar :0 (Como siempre, pon en el README que criterio usaste en ese caso).
