### ISSUE TITLE
Control Mañana

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#186]
El control de mañana correspondería a los contenidos de la semana 2 o 3? Si es que se puede saber 😅

**Comment by nebil** [comment]
Este control sólo evaluará los contenidos de la **tercera semana**. Luego, para mañana, la materia a estudiar vendría siendo acerca de listas ligadas, árboles y grafos.

**Comment by llloyola** [comment]
Gracias! Ahora, sé que ponerme a estudiar 🤓
