### ISSUE TITLE
parametros.py

### ISSUE THREAD

**Issue by TriniAguilera** [IIC2233/Syllabus#186]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! En el archivo parametros.py puedo dejar ciertos parámetros aleatorios? Por ejemplo, la cantidad de excavadores iniciales hago que sea un número random entre 1 y 8 (cantidad de excavadores en archivo csv) o necesariamente debo dejarlo como una constante? Esta pregunta también va para la elección de las probabilidades. Actualmente las tengo como random entre 0-1 porque en el enunciado nunca dicen que deben ser constantes. Por supuesto me preocupo de que estas sumen 1 cuando corresponda.

**Comment by Rotopikus** [comment]
Hola!!!

No. Los valores de las variables en parametros.py deben ser fijos. Ojo que en ese archivo no se pueden importar librerías, por lo que no deberías importar random ahí.

Espero haber aclarado tu duda. Éxito!!
