### ISSUE TITLE
puntaje negativo

### ISSUE THREAD

**Issue by enriquerussi** [IIC2233/syllabus#186]
Si el oponente gana el puntaje seria negativo según la formula.

**Comment by yuwet15** [comment]
Ammm la resta es de los barcos descubierto por mi - barcos eliminados por el pc, creo y eso da positivo

**Comment by jitorcas** [comment]
Hola! @enriquerussi 

<img width="899" alt="Captura de Pantalla 2020-08-25 a la(s) 17 15 30" src="https://user-images.githubusercontent.com/48298300/91228699-b3234d80-e6f6-11ea-984d-77d35952ae5d.png">

La fórmula toma el **máximo** valor, por lo tanto en el caso que te de puntaje negativo, debes dejarlo en 0. 

Éxito en la tarea!

**Comment by enriquerussi** [comment]
> Ammm la resta es de los barcos descubierto por mi - barcos eliminados por el pc, creo y eso da positivo

No se si estoy re perdido pero si el pc gana, la cantidad de barcos descubiertos por el pc va a ser mayor que la cantidad descubiertos por mi, dando un puntaje negativo

**Comment by jitorcas** [comment]
@enriquerussi Así es, en ese caso siguiendo la fórmula tu puntaje sería 0.

**Comment by mati-gonz** [comment]
Yo no entiendo esa formula. Hay que ponerla así? o simplemente podemos poner una condición de que cuando sea  menor que 0 de 0?

**Comment by jitorcas** [comment]
@mati-gonz 

Existen muchas maneras de implementarlo, sin embargo, la idea es que se aprenda a utilizar distintas fórmulas en python, es por ello que si no utilizas la fórmula que te entregamos probablemente no tengas puntaje completo. ¿Que no comprendes de la fórmula? Para poder ayudarte

**Comment by mati-gonz** [comment]
Como lo hago para ponerla en ese formato entonces? Tengo que ocupar alguna función de estadística?

**Comment by jitorcas** [comment]
@mati-gonz 

Puedes utilizar el método `max()` que te entrega el máximo valor. 

Ejemplo:

```python 
a = max(1, 2, 3)
print(a)
```
> 3
