### ISSUE TITLE
Problema al usar el botón pausa en ventana juego

### ISSUE THREAD

**Issue by SVenegasA** [IIC2233/Syllabus#186]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Por alguna razón, desde que agregué un pushbutton para pausa y otro para salir, cada vez que presiono espacio (Que sí estaba funcionando para disparar) como que funciona a modo de click. O sea, intento disparar y en vez de hacerlo, solo se está presionando el botón menú (Como si le estuviera haciendo click) **¿Qué puedo hacer para solucionarlo?**

**Comment by Emiliax16** [comment]
Hola @SVenegasA . Es un poco difícil responder concretamente sin ver tu código, pero creo que es bien probable que tengas un problema con las señales que implementaste en la ventana de juego. ¿Será que usaste el mismo nombre para más de una señal? te recomiendo ir paso a paso revisando cada señal y haciendo hartos `print` para verificar en donde estará tu error. En cualquier caso, puedes pushear tu avance hasta ahora y así puedo ayudarte con más detalle. Saludos c:

**Comment by SVenegasA** [comment]
Listo, ahora hice git push

**Comment by SVenegasA** [comment]
Donde hago conexión de señales es main.py
No he usado el mismo nombre para señales distintas y los pushbutton de ventana_juego no mandan ninguna señal así que sería raro que el problema esté con las señales

**Comment by Emiliax16** [comment]
@SVenegasA ya caché. Es porque pushbutton viene por default con la propiedad de que tanto con click como con la tecla espacio, se active. Cambia la tecla que viene por default para el botón o directamente desactivala. Te recomiendo ver el siguiente link para entender cómo funciona pushbotton:

[https://doc.qt.io/qt-5/qpushbutton.html](url)

Saludos!

**Comment by RodrigoRenco** [comment]
tengo el mismo problema, me lei la pagina y no logro encontrar como cambiarle el default

**Comment by SVenegasA** [comment]
Prueba usando QPushButton.setDisabled(bool) reemplazando bool por True o False. Con True desactivas el botón y deja de ser molesto (Y con bool = False puedes volver a activarlo después)
