### ISSUE TITLE
Duda sobre volver al menu de acciones

### ISSUE THREAD

**Issue by Sangarcia993** [IIC2233/Syllabus#186]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

1) El enunciado dice que se tiene que "regresar al Menú de Acciones" despues de cumplir una accion. Puedo añadir un input() antes de esto, por lo que despues de cumplir una accion se debe apretar enter antes de continuar al menu? De esta manera es mas facil ver el resultado de la accion.

2) Ademas, se puede en los for loops usar como variable la letra i. Por ejemplo, for i in range(numero o len(lista))?

Gracias de antemano.

**Comment by individuocomunycorriente** [comment]
Hola!
1- Puedes hacerlo, pero te recomiendo agregarlo en el README, explicar a grandes rasgos porqué decidiste hacerlo de esta forma (comodidad en el código, comodidad para imprimir en la consola) y ojalá imprimir en consola un mensaje del tipo "Presione enter para volver al menú de acciones".
2- Si se puede, pero debes tener cuidado al momento de diferenciar un **for i in range(lista)** de un **for i in lista** ya que i adquiere valores distintos en ambos for

Saludos.

**Comment by Sangarcia993** [comment]
Gracias!
