### ISSUE TITLE
Descuento malas prácticas

### ISSUE THREAD

**Issue by Maria-josee** [IIC2233/Syllabus#186]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, una pregunta, los descuentos por malas prácticas es uno fijo ? resulta que hice un archivo pero como me pase de las lineas lo separe en dos para que no me descontaran, entonces para hacer que funcione importe al inicio como se debe pero me tiraba un error de importación circular, por lo que tuve que hacer la importación al final de un archivo para evitarlo.
Lo otro, si hiciera un buen README explicando en que linea y el por qué, se podría aplicar el des-descuento?

**Comment by martinjaraf** [comment]
Hola! En la sección de descuentos dice: "Se descuentan 5 décimas si uno o más archivos exceden las 400 líneas de código". Por ende intenta evitar excederte de las 400 líneas. S

Sobre lo otro, se aplica el des-descuento si todo el README está claro y preciso, indicando las funciones, módulos, posibles errores, etc. La cantidad de décimas queda a criterio del ayudante, pero como máximo pueden ser 5.

**Comment by Maria-josee** [comment]
Mi pregunta es por la importación, no por el descuento de las líneas

**Comment by martinjaraf** [comment]
Ah! Perdón, te recomiendo leer la sección de descuentos, ahí se especifíca la cantidad de décimas a descontar según el error y la cantidad de veces que se repite (en tu caso import).

**Comment by Maria-josee** [comment]
Si revise solo que ese descuento está dentro de la categoría mala práctica, pero no se especifica si cada mala práctica son 5 décimas menos o si hay un descuento diferente por cada una, entonces por eso mi duda es de que si importe abajo y no arriba son 5 décimas menos por eso ?

**Comment by GonzaAlegria** [comment]
Hola María José! Espero que te encuentres muy bien
El conjunto de malas prácticas te puede descontar desde 0 a 5 décimas en tu tarea. Una mala práctica por si sola (a no ser que sea muy relevante) es difícil que llegue a bajarte 5 décimas, pero si se hace en reiteradas ocasiones o son varias malas prácticas cambia el panorama. Espero que esto aclare tu duda!
Saludos <3
