### ISSUE TITLE
Rondas en los combates

### ISSUE THREAD

**Issue by ignanuyens** [IIC2233/Syllabus#186]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Tengo dudas sobre las rondas de los combates. En el enunciado dice:

**Un combate entre dos ejércitos consiste en tres rondas, donde cada ronda está compuesta por varios enfrentamientos entre dos gatos, uno de cada ejército.  Entre las rondas del combate, el jugador podrá hacer cambios y mejoras a su ejército.  [...]
En cada ronda, el primer gato de cada ejército se enfrenta contra el otro, un Ataque a la vez según lo indicado en Enfrentamientos (En enfrentamiento básicamente dice que dos gatos se van a atacar con el método hasta que alguno, o los dos, muera).
Después de que termine el enfrentamiento, si uno de los gatos sobrevive, este continuará luchando contra el gato siguiente del Ejército rival, manteniendo sus stats actuales, es decir, sin recuperarse. Esta secuencia se repite hasta que uno de los equipos se quede sin Gatos Combatientes. Si consigues ganar, avanzarás a la siguiente ronda, obteniendo ORO_GANADO y volviendo al Menú de Inicio para invertir este dinero en tu Ejército. En el caso contrario, perderás el juego y deberás volver al Menú de Inicio regresando a la ronda 1, con un Ejército vacío y una cantidad de dinero igual a ORO_INICIAL. **

Siento que hay una confusión respecto a las rondas. Me confunde el hecho que sean 3 rondas, pero después dice que la secuencia se repite hasta que no queden combatientes. Entonces lo que no entiendo es si:  tomo mis primeros gatos 🡢 se atacan 🡢 muere alguno 🡢 ¿se termina la primera ronda? y gano oro_ganado / permito hacer cambios al ejercito 🡢 tomo los siguientes (o el siguiente) 🡢 muere alguno 🡢 ¿se termina la segunda ronda?  y gano oro_ganado / permito hacer cambios al ejercito 🡢 tomo los siguientes (o el siguiente) 🡢 muere alguno 🡢 ¿se termina la tercera ronda? y gano oro_ganado / permito hacer cambios al ejercito 
En ese proceso me quedaría la duda que no se generaría eso de que el proceso ocurra hasta que no queden combatientes en el ejercito enemigo

o más bien
tomo mis primeros gatos 🡢 se atacan 🡢 muere alguno 🡢 (se repite el proceso hasta que no queden más gatos en algún ejercito)  🡢 ¿se termina la primera ronda? y; gano oro_ganado vuelvo al menú de inicio y permito hacer cambios al ejercito ó   vuelvo al inicio a la ronda 1 con ejercito vacío y oro_inicial. (supongamos que gané la primera ronda) 🡢 Parte la segunda ronda 🡢 ahora que maté a todo el ejercito contrario, ¿contra quien voy a pelear y repetir el proceso tomar los gatos, que se ataquen y muera y repetir? considerando que ya maté a todo el ejercito del archivo del nivel que elegí inicialmente. Tendría que pasar al siguiente nivel? 

Perdón si me expliqué mal, pero agradecería si me explican bien  o de forma más el proceso de rondas y combates :)

**Comment by diegoftpxd** [comment]
Hola @ignanuyens, las rondas son más parecidas a tu segundo ejemplo. El sistema de cada enfrentamiento es el siguiente.

En cada ejercito se compone de varios combatientes, los enfrentamientos se hacen 1vs1 osea que en todo momento solo existe 1 enfrentamiento sucediendo.

Luego una ronda serían varios enfrentamientos uno tras otro, al eliminarse una unidad el ganador sigue peliando y el siguiente enfrentamiento es entre la unidad ganadora y la siguiente unidad en el ejercito perdedor. Finalmente la ronda termina cuando uno de los ejercitos se haya quedado sin unidades.

Los ejercitos enemigos con los que peleas cambian en cada ronda, por ejemplo si elijes la dificultad de fácil  y estás en la primera ronda, debes luchar contra el ejecito que se encuentra en la primera linea del archivo facil.txt. En la segunda ronda se lucha contra la segunda linea del mismo archivo y así sucesivamente. Si esto no es claro revisa la sección 6.1 del enunciado.

No sé si esto responde tu duda.

**Comment by jisalasc** [comment]
Entonces es correcto asumir que son siempre 3 rondas?

**Comment by diegoftpxd** [comment]
@jisalasc como se especifica en la sección 2 del enunciado, si logras completar las 3 rondas de combate ganarás la partida. Osea que son siempre 3 rondas máximo.
