### ISSUE TITLE
Ejericicio 2.3 de la semana 2

### ISSUE THREAD

**Issue by anamanzana** [IIC2233/syllabus#186]
Hola!

En el Ejercicio 2.3: DCCgram, piden el método a implementar para poder verlo en lista, puesto que estoy imprimiendo:
```python
[<__main__.Usuario object at 0x1050355d0>, <__main__.Usuario object at 0x1050a86d0>, <__main__.Usuario object at 0x10509f390>, <__main__.Usuario object at 0x1050fda10>]
```

Que puedo hacer?

**Comment by KnowYourselves** [comment]
Hola @anamanzana!

Esto sucede porque esa es la forma por _default_ que tiene _Python_ para mostrar objetos en pantalla. Tomemos el siguiente ejemplo:

-  `<__main__.Usuario object at 0x1050355d0>`: Esto nos dice que en el archivo `__main__` (el archivo que fue ejecutado) existe un objeto de la clase Usuario, en la dirección de memoria `0x1050355d0` (este es un numero en hexadecimal).

En [este archivo de los contenidos](https://github.com/IIC2233/contenidos/blob/master/semana-02/4-polimorfismo.ipynb) puedes encontrar las herramientas que _Python_ tiene para modificar la forma en que los objetos son impresos.

Éxito!

**Comment by anamanzana** [comment]
Muchas gracias!

**Comment by KnowYourselves** [comment]
Recuerda no cerrar tus Issues, para que otros las puedan ver fácilmente. 

Éxito!
