### ISSUE TITLE
Modificacion de T01 en el repositorio

### ISSUE THREAD

**Issue by aleuribej** [IIC2233/Syllabus#186]
Hola! Tengo una consulta sobre modificar el archivo de la tarea. 
Lo que pasa es que revisando los errores de mi tarea para incluirlos en el README  modifique un modulo de mi tarea y queria saber si recolectan las tareas igual que las actividades para saber si puedo hacer push.
Y si no puedo modificarlo, queria saber si puedo ocupar el comando git checkout o tambien afectaria el repositorio? 😢💔

**Comment by sebacruzd** [comment]
Hola, si puedes hacer push ya que se recolecta el commit con la fecha y hora especificada en el enunciado :)

**Comment by aleuribej** [comment]
Muchas gracias!! 😄
