### ISSUE TITLE
Duda sobre la utilidad del uso de métodos abstractos

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#186]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, habiendo visto las clases y hecho los ejercicios propuestos de la semana 03, aun no logro entender bien la utilidad del uso de métodos abstractos. Si se definió en una superclase abstracta un método para que sea compartido por todas sus subclases pero se quiere al mismo tiempo que en cada subclase ese método se ejecute de forma distinta, ¿por qué no simplemente definirlo como un método regular en la superclase y sobrescribirlo de la forma particular que se quiera en cada subclase?, ¿en qué aporta definirlo como un método abstracto en la superclase?

Desde ya gracias.

**Comment by tqmbanados** [comment]
Hola @JuanpaBC! El principal uso que en este curso tiene definir una clase abstracta es aprender "etiqueta" de código, y mejorar tu escritura. El método abstracto es importante, por ejemplo, si uno de los métodos definidos de la super-clase llama a este método, pero el método en sí no tiene sentido definirlo como super-clase, pues lo retornado depende exclusivamente de las sub-clases. En este caso, estás asegurándote que no haya ningún error cuando corras tu código, y además, si hipotéticamente alguien fuera a ocupar la super-clase en su código (lo que en equipos de trabajo es usual), le estas diciendo de forma clara que requiere definir ese método para que funcione la sub-clase correctamente. 
El método abstracto se define así pues ocupa menos memoria que definir un método real que al final nunca sería utilizado. En general, cuando escribes código, es importante que definas bien que cosas y debería hacer una super-clase, pues te ayuda a ti y a quienes lean tu código a entender tu proceso mental. En las tareas de este curso terminarás por escribir más de 2000 líneas, por lo que te resultará super útil manejar clases abstractas para mantener tu proceso claro. 

Un ejemplo que se me ocurre es una *super-clase* ```Pais```, que tiene un atributo ```lider```. Definamos el método genérico ```renuncia_del_mandatario()```, que cambia el atributo ```lider``` a una string vacío, llama al método ```protocolo_de_emergencia````, y llama al método ```elecciones()```.  Sin embargo, cada país tiene un protocolo y sistema de elecciones diferente, y muy complejos ambos, por lo que no tiene sentido definir estos métodos en la super-clase abstracta. Cada sub-clase debe definir estos métodos por separado. Al definir estos dos métodos como abstractos obliga a que las sub-clases también los definan, por que si llega a haber un llamado a ```renuncia_del_mandatario()``` y uno de estos métodos no está definido, ocurriría una ~~Excepción~~ Crisis Política aún mayor.

**Comment by tqmbanados** [comment]
Hola!  Aprender a definir y ocupar métodos abstractos es más que nada para mejorar tu etiqueta y limpieza de código. Hay varias utilidades que tienen que ver con la memoria, pero la principal utilidad que tendrán en este curso es para prevenir errores, y enseñarte métodos de programación muy útiles a la hora de trabajar con equipos más grandes🤜🤛. 
El método abstracto es importante cuando un método "normal" del super-clase necesita llamar al método abstracto para funcionar, pero no tiene sentido definir el método como parte de la super-clase. Entonces, te aseguras que las sub-clases definan el método, y evitas errores. Cuando trabajas en un proyecto grande con más personas, alguien quizás esté a cargo de definir la super-clase y otra persona las sub-clases. Usando métodos abstractos se comunican mejor y no hay que preocuparse tanto de que sus códigos sean "compatibles", pues la persona que hace la sub-clase sabe exactamente lo que tiene que programar para que funcione. Además, también será importante para ti en las tareas, que pueden tener más de 2000 líneas a través de muchos módulos. Tener orden en la escritura, claridad en como defines las clases y sub-clases, y tener claro que método hace qué y lo que necesita para funcionar mejorará muchísimo tu rendimiento. 
Te presento un ejemplo: supongamos la clase abstracta ```Pais```. Esta clase tiene un atributo ```lider```, y un método ```renuncia_de_lider()```, que como dice, vacía el atributo ```lider```, llama al método ```protocolo_de_emergencia()``` y luego ```elecciones()```. Si bien el método ```renuncia_de_lider()``` es común para todas las sub-clases, cada país tiene sus propios protocolos y sistema de elecciones. Entonces, esos dos métodos no tendría sentido definirlos en la super-clase ```Pais```. Pero, si no son definidos en la sub_clase, en el caso que ocurra una ```renuncia_de_lider()``` se desencadenará una ~~Excepción~~ Crisis Política. En este caso, resulta muy útil definir los métodos como abstractos, pues estás asegurándote que quien cree las sub-clases (aunque seas tú) sepa bien los métodos que es importante definir, y previene posibles errores 😊.

Espero que haya contestado tu pregunta, sino, de todas maneras dime que aún no te queda claro!

**Comment by JuanpaBC** [comment]
Muchas gracias, siento que tengo una mejor idea ahora! Por lo que cache, a veces es util definir ciertos métodos de la superclase como abstractos para obligar a que se escriba en las subclases la manera en que se ejecutará en éste el respectivo método, y así quede el código más claro.

**Comment by tqmbanados** [comment]
Si, es en general eso! Implementar un método que no será usado sólo gasta memoria, pero si ese método es necesario para que la clase cumpla su función, es buena práctica definirlo como abstracto, y así te aseguras que lo van a implementar en la sub-clase. Quizás en el curso no parezca tan "útil", pero es para que aprendan buenas prácticas de programación, que te servirán para este curso y en el futuro si trabajas con código ya hecho, o creas código para que usen otras personas.

**Comment by JuanpaBC** [comment]
vale muchas gracias!
