### ISSUE TITLE
Duda con PEP8 Sublime Text

### ISSUE THREAD

**Issue by RenatoVWS** [IIC2233/syllabus#187]
Hola, estaba viendo que cada línea del código tenía que tener un máximo de 100 caracteres y Sublime Text me lo ajusta a 120. ¿Es posible ajustarlo a 100 caracteres? ¿Y cómo lo puedo hacer? Gracias!

**Comment by gatochico** [comment]
Hola! Según lo que encontré [aquí](https://stackoverflow.com/questions/25900954/80-characters-right-margin-line-in-sublime-text-3), deberías ir a `Preferences -> Settings-User`, y debería abrirse un archivo de texto con preferencias. En dicho archivo debes pegar lo siguiente:

```
{
    // set vertical rulers in specified columns.
    // Use "rulers": [80] for just one ruler
    // default value is []
    "rulers": [100],

    // turn on word wrap for source and text
    // default value is "auto", which means off for source and on for text
    "word_wrap": true,

    // set word wrapping at this column
    // default value is 0, meaning wrapping occurs at window width
    "wrap_width": 100
}
```
Si ya hay preferencias escritas en el archivo, trata de no sobreescribirlas al momento de agregar las de arriba.

Avísanos cómo te va!

**Comment by RenatoVWS** [comment]
Si me funcionó! Muchas gracias!
