### ISSUE TITLE
Duda mala práctica print()

### ISSUE THREAD

**Issue by jocttan** [IIC2233/syllabus#187]
Hola, quería saber si se considera mala práctica poner muchos print() seguidos en vez de ocupar \n, ya que al menos yo siento se ve mejor utilizando varios print().
Gracias!

**Comment by Tsbalart** [comment]
Hola @jocttan!
No se considera mala practica, pero debes considerar que te ocupa mas lineas, por lo que debes tener ojo de no pasarte del máximo.
Exito con la tarea!
