### ISSUE TITLE
Problema con el sonido del disparo

### ISSUE THREAD

**Issue by nicoperez12** [IIC2233/Syllabus#187]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo un problema al implementar el sonido del disparo porque cuando corro el código y disparo, por alguna razón se me congela como por un segundo el juego y de ahí vuelve, pero si corro el código sin el sonido me anda bien. Será porque mi computador se demora un poco en procesar el sonido? Gracias.

**Comment by CristobalPerez-Cotapos** [comment]
Hola!! por lo que me comentas me imagino que tu que el sonido se está ejecutando en el mismo thread que tu ventana de juego, por lo que durante ese segundo se demora en procesar y se te congela toda la ventana. 
En este caso mi consejo es que intentes inicial el sonido de disparo en un thread aparte, de tal forma que este se ejecute de manera independiente y tu ventana de juego se comporte de manera fluida. 
Intenta implementarlo de esta manera y coméntame si te resulta, suerte!! 😄

**Comment by M4rtinL4gies** [comment]
Hola! Me quería sumar a la pregunta, pues tengo el mismo problema. Estuve harto rato intentando solucionarlo, e incluso con la ejecución del sonido en un thread aparte se pega un rato la pantalla. Lo que es extraño, es que este tiempo parece variar (el primer disparo es siempre el que más rato congela la pantalla, mientras que si realizo disparos continuos, la pantalla no se pega). Tenía, entonces, la misma duda: si era posible que el juego se congelara porque el computador se demora en procesar el sonido. 
pd: si quito la ejecución del sonido, el juego tampoco se congela.

**Comment by M4rtinL4gies** [comment]
Estuve revisando mi código, y efectivamente, en cada una de las soluciones que se me ocurrieron, estuve implementando únicamente uno de los dos puntos que mencionas, no ambos a la vez. Ahora modifiqué unas lineas y funciona correctamente. Muchas gracias por la ayuda!

**Comment by CristobalPerez-Cotapos** [comment]
De nada!! suerte con el resto de la tarea 😉

**Comment by agustind1** [comment]
Hola! A que se refieren con iniciar el sonido en un Thread aparte? 
Por ejemplo enviar una señal desde la ventana del juego a la lógica? Tengo el mismo problema con el sonido y no me funciona.

**Comment by CristobalPerez-Cotapos** [comment]
Hola!! Lo que pasa es que si mandas una señal al backend este mandara una señal de vuelta que se unirá al thread principal de la ventana (y por lo tanto la volverá más lenta). 
La idea entonces es crear un thread que funcione independiente de la ventana y que tenga como objetivo hacer sonar la música. 
Si te quedan dudas cuéntame!!

**Comment by agustind1** [comment]
> Hola!! Lo que pasa es que si mandas una señal al backend este mandara una señal de vuelta que se unirá al thread principal de la ventana (y por lo tanto la volverá más lenta). La idea entonces es crear un thread que funcione independiente de la ventana y que tenga como objetivo hacer sonar la música. Si te quedan dudas cuéntame!!

Probé creando una clase Qthread y tambien con threading, pero no me funcionó con ninguna de las dos opciones. No se si te refieres a hacer algo así o a otra cosa

**Comment by CristobalPerez-Cotapos** [comment]
No te puedo decir mucho más, por que sería darte la respuesta 🤐, pero no es necesario crear una clase qthread, sino que basta con hacer una instancia que se dedique a efectuar el sonido y que funcione independientemente de las ventana de juego
