### ISSUE TITLE
Nueva partida de menú de inicio

### ISSUE THREAD

**Issue by TriniAguilera** [IIC2233/Syllabus#187]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Tengo la pregunta si cada vez que inicio una nueva partida, se debe volver a elegir una arena (y tipo) de manera aleatoria y un nuevo equipo (y cantidad de excavadores que lo componen). Esta duda me surge para el caso de que vuelva de otro menú al menú inicial e inicie una nueva partida. No se si se debe partir completamente desde cero o hay que mantener el tipo de arena y la cantidad de excavadores iniciales. Actualmente yo tengo que el tipo de arena inicial y la cantidad de excavadores iniciales son parametros random, por lo que se vuelven a escoger cada vez que hago una nueva partida. Quiero saber si al final dichos parametros solo debo elegirlos la primera vez que ejecute el menú inicial y elija una nueva partida o cada vez que elija una nueva partida.

**Comment by mpiavf** [comment]
Hola! Está bien lo que hiciste, cada vez que se inicie una *nueva partida* la arena y el equipo deben ser nuevos. Solamente en el caso de que se haya guardado una partida con anterioridad y luego se *cargue la partida* hay que ocupar la arena y el equipo de la partida guardada.
Saludos!
