### ISSUE TITLE
funcion bsf y dsf en el Material 02-Grafos

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#187]
Hola, tenía una duda respecto que es lo que representan y que hacen estas funciones, ya que me cuesta entender el codigo. 

Gracias

**Comment by fringlesinthestreet** [comment]
Las funciones ```dfs``` y ```bfs``` significan _Depth-First Search_ y _Breadth-First Search_ respectivamente.

El método ```dsf(graph, start)```  se utiliza para recorrer el grafo ```graph``` de forma de comenzar en el nodo ```start``` y recorrer a cada amistad de forma completa, es decir, se revisa la primera amistad y luego a las amistades de ese hasta que se repitan o se acaben. Luego de eso pasa al próximo vecino. 
En cambio, el método ```bsf(graph, start)``` se utiliza para recorrer el grafo explorando a todos los vecinos primero y luego recorrer a los vecinos del primero, luego del segundo y así. 

Son dos formas de explorar un grafo. Es análogo en un árbol a las búsquedas en profundidad o amplitud.

**Comment by Kitaps** [comment]
ahhh duh, cmo no caxe

gracias
