### ISSUE TITLE
Problema función utils magic numbre 

### ISSUE THREAD

**Issue by dbarraza01** [IIC2233/Syllabus#187]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Tengo python 3.11.9 instalado y al correr el archivo main.py en la terminal tengo el problema de "magic number". En otra issue vi que el problema podía se debía a que se tiene una versión inferior o superior a python 3.11.X con X = 7. Pero tengo una versión que si debería correr el codigo o no?
Cuál podría ser mi problema?

![2024-08-26 (1)](https://github.com/user-attachments/assets/1aa8f28c-021d-4316-80d5-79561a5447f6)
![2024-08-26](https://github.com/user-attachments/assets/2129f947-d755-4f74-a194-f5a957ec2a1e)

**Comment by dbarraza01** [comment]
Disculpa, pero, me detecta un virus y no me deja descargarlo 
![image](https://github.com/user-attachments/assets/bb109a62-8090-43bb-8dd3-ca84f3c26837)

**Comment by vgalfaro** [comment]
Hola! cuidado con lo que envían, no te recomiendo descargar esos "fix", esa persona ni siquiera es del curso, la segunda captura corresponde a cmd o a la terminal de vscode?

**Comment by dbarraza01** [comment]
menos mal no se descargó el virus. 
La segunda captura del primer comentario corresponde a cmd 
pero, en vscode tengo esto 
![image](https://github.com/user-attachments/assets/6e9a3d51-d5fe-44d1-83b2-16affc8f0c28)

**Comment by vgalfaro** [comment]
Intenta descargando la versión 3.11.7 de python, te adjunto el [link](https://www.python.org/downloads/release/python-3117/), recuerda eliminar la versión que tienes ahora y actualizar el interpretador en vscode.
