### ISSUE TITLE
Overriding vs "recursividad" en la llamada de un método de una subclase hacia una superclase

### ISSUE THREAD

**Issue by minsoos** [IIC2233/syllabus#187]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
¿En qué momento, al llamar a un método de una subclase, este hace overriding y en qué otro llama a todos los métodos de las superclases que son madres de este?

> En el ejemplo del furgón escolar, en Herencia, en la semana 2, tema 3, al definir conducir en la subclase se hace overriding, y el método definido reemplaza a los definidos en la superclase correspondiente.

`class Auto:

    
    def __init__(self, ma, mo, a, c, k):
        self.marca = ma
        self.modelo = mo
        self.año = a
        self.color = c
        self.__kilometraje = k
        self.__dueño = None

    def conducir(self, kms):
        print(f"Conduciendo {kms} kilómetros")
        self.__kilometraje += kms

    def vender(self, nuevo_dueño):
        self.__dueño = nuevo_dueño
        print(f"Auto vendido a {nuevo_dueño}")

    def leer_odometro(self):
        return self.__kilometraje

    
class FurgónEscolar(Auto):
    """Subclase de Auto"""
    
    # Estamos haciendo overriding del __init__ original
    def __init__(self, marca, modelo, año, color, kms):
        # Aún queremos usar el __init__ original para setear los otros datos. Así es como podemos llamarlo.
        Auto.__init__(self, marca, modelo, año, color, kms)
        self.niños_y_niñas = []
    
    # inscribir_niño_o_niña es un método específico de esta subclase.
    def inscribir_niño_o_niña(self, niño_o_niña):
        self.niños_y_niñas.append(niño_o_niña)
        
    # Estamos haciendo overriding del método conducir original
    def conducir(self, distancia):
        # Acá no queremos usar la versión original de conducir
        print(f"Conduciendo con cuidado {distancia} kilómetros")
        
        
furgón = FurgónEscolar('Kia', 'Sportage', 2000, "Blanco", 135000)
furgón.conducir(20)`

> En cambio, en el ejemplo del método llamar(), en la semana 3, tema 2, al llamar al método desde la subclase este llama a todos los métodos de las superclases que tengan el mismo nombre.

`class ClaseB:
    
    num_llamadas_B = 0
    
    def llamar(self):
        print("Llamando método en Clase B")
        self.num_llamadas_B += 1

class SubClaseIzquierda(ClaseB):
    
    num_llamadas_izq = 0
    
    def llamar(self):
        print("Estoy en Subclase Izquierda")
        ClaseB.llamar(self)
        print("Llamando método en Subclase Izquierda")
        self.num_llamadas_izq += 1

class SubClaseDerecha(ClaseB):
    
    num_llamadas_der = 0
    
    def llamar(self):
        print("Estoy en Subclase Derecha")
        ClaseB.llamar(self)
        print("Llamando método en Subclase Derecha")
        self.num_llamadas_der += 1

class SubClaseA(SubClaseIzquierda, SubClaseDerecha):
    
    num_llamadas_subA = 0
    
    def llamar(self):
        print("Estoy en Subclase A")        
        SubClaseIzquierda.llamar(self)
        SubClaseDerecha.llamar(self)
        print("Llamando método en Subclase A")
        self.num_llamadas_subA += 1

s = SubClaseA()
s.llamar()
print()
print(f"Llamadas en Subclase A: {s.num_llamadas_subA}")
print(f"Llamadas en Subclase Izquierda: {s.num_llamadas_izq}")
print(f"Llamadas en Subclase Derecha: {s.num_llamadas_der}")
print(f"Llamadas en Clase B: {s.num_llamadas_B}")`

> Mi duda es en qué momento el comportamiento es uno u otro

**Comment by pabloist** [comment]
Hola!

Creyendo haber entendido tu duda te comento lo siguiente:

   -En el primer ejemplo que mencionas, simplemente se realiza un "overriding" del método de la clase que FurgónEscolar hereda de Auto. ¿Qué quiere decir esto? Significa que cuando hemos definido una nueva función conducir() y la hemos sobreescrito por sobre el método de la clase madre y que por lo tanto ya no tiene "conexión" con ella (por esto no se llama el método de Auto).
   -Por otro lado en el segundo ejemplo que mencionas, no solo se realiza un overriding del método al volver a definir la función llamar() de cada subclase, sino que además dentro de dicha función que estamos sobreescribiendo, hacemos un llamado al método de la clase madre (_super().llamar()_) y debido a esto es que no se pierde "conexión" con los métodos de la clase madre.

Dependiendo de los casos, podría ser útil utilizar uno sobre otro, pero te comento que lo más común es hacer un overriding y sobreescribir los métodos de la clase madre (en caso que eso se desee).

Cualquier duda me comentas, saludos!

**Comment by minsoos** [comment]
No me había dado cuenta de esa parte del código, muchas gracias!
