### ISSUE TITLE
Al imprimir una instancia de una subclase, python parece omitir su __str__ y sólo ve el __str__ de la superclase

### ISSUE THREAD

**Issue by enzoacvi** [IIC2233/Syllabus#187]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!

He estado intentando implementar la acción de presentarse a las clases mediante el método `__str__`, pero me he encontrado con el problema de que por algún motivo python no parece leer este método en las subclases y solamente en la clase de la que heredan. 
He buscado en internet pero no he visto nada relacionado a esto. He probado dejando solamente `__str__` en las subclases pero python no parece ver el método, arroja: `<__main__.Caballero object at 0x0000026829B5BD90>`

Mi pregunta es, **por qué sucede esto y de qué forma puedo hacer que python vea el método `__str__` en las subclases?** 🤔

**Comment by diegoftpxd** [comment]
Hola @enzoacvi, si no entiendo mal tu problema. Tienes una clase padre la cual tiene definidido su metodo `__str__` pero en las clases hijo esto no parece estar heredando correctamente y al utilizar el método `__str__` en una instancia Caballero te entrega el mensaje `<__main__.Caballero object at 0x0000026829B5BD90>`.

Primero que nada yo revisaría si efectivamente estás heredando al definir la clase Caballero. Osea que en algún lado diga algo parecido a `class Caballero(Padre)`.

Lo segundo que podrías probar es ver si al hacer print a una instancia de la clase padre esto devuelve efectivamente lo que quieres. así descartas que el problema esté en como defines el método `__str__` en la clase padre.

Si esto ya está, probaría a ver si se están heredando corectamente otros métodos de la clase padre. Con esto puedes descartar un problema al definir la herencia.

Finalmente si nada de lo anterior funciona podrías reescribir el metodo `__str__` en la clase hijo y llamar mediante super() al metodo `__str__` de la clase padre. Esto último no debería ser necesario debido a que acabo de realizar una prueba y el metodo `__str__` se heredó correctamente desde una clase padre a una clase hijo pero igualmente vale la pena intentarlo.

Espero esto te pueda ayudar 😄.

**Comment by enzoacvi** [comment]
Hola @diegoftpxd, gracias por la ayudaa

Había definido el `__str__` en la superclase y también en la clase hija llamando a super(). Lo que he visto es que python parece omitir el `__str__` de la clase hija (la que he instanciado), y se salta directamente al método `__str__` de la clase padre, imprimiéndolo sin revisar el método de la clase hija (lo he probado mediante prints).

Chequeé que la clase Caballero sí está heredando correctamente con `__mro__`: (`(<class '__main__.Caballero'>, <class '__main__.Combatiente'>, ` ...).

Al parecer lo que no va bien es el overriding TT

**Comment by diegoftpxd** [comment]
Siempre es una opción en vez de utilizar el `super()` hacer uso de directamente de `Combatiente.__str__()` pero ahí tienes que tener mucho cuidado con el **Probelmas del diamante** ahí tendrías que decidir si es una opción viable según el problema

**Comment by enzoacvi** [comment]
Sí, pero aún así python ignora el método `__str__` de la clase hija 😓

Otra cosa extraña que está pasando es que `Combatiente` hereda de `ABC`, y a su vez `Caballero` de `Combatiente`, y si defino el `__str__` de Combatiente como **abstractmethod** y implemento este método en sus clases hijas, python me dice: `TypeError: Can't instantiate abstract class Caballero with abstract method __str__`, cuando esto no debería pasar TT

**Comment by JJJGGGG** [comment]
@enzoacvi Tienes subido tu código a tu repositorio? Que archivos son?

**Comment by enzoacvi** [comment]
Hola! Sí, está en Tareas/T2, es clases.py

**Comment by JJJGGGG** [comment]
Me hace ruido estas líneas que tienes en el str de caballero:
```py
        def __str__(self) -> str:
            presentacion = Combatiente.__str__()
            print(presentacion)
```

Al hacer Combatiente.__str__() estas llamando al metodo str sin el argumento self, quizas ese es el problema? Por que no lo cambias al formato que usas en las otras clases (usando super)

**Comment by enzoacvi** [comment]
Disculpa, es que he estado probando varias cosas y dejé esa parte así. De la misma forma que en las demas clases tampoco funciona

**Comment by JJJGGGG** [comment]
Y si instancias al mago te pasa lo mismo?

**Comment by enzoacvi** [comment]
Con mago no me pasa, pero con caballero y guerrero sí

**Comment by enzoacvi** [comment]
Perdón , solo me pasa con caballero

**Comment by JJJGGGG** [comment]
Encontré tu problema.

En Caballero y sólo Caballero, haces print pero no retornas nada. En el método str **debes** retornar un string, si no parece que python no toma el método como válido y lo busca en el padre. Se arregla retornando lo que printeas (ahora hay un return sin valor).

Saludos!

**Comment by enzoacvi** [comment]
Sí, en la versión que subí al repositorio porque se me había olvidado cambiar eso, pero poniendo lo mismo que en mago, por ejemplo, también ocurre esto. Subiré de nuevo el archivo al repositorio

**Comment by JJJGGGG** [comment]
No me cuadra que sólo te pase en la clase Caballero, revisa bien porque si te pasa en una te debería pasar en todas, o confirmame que es verdad que sólo pasa en caballero.

**Comment by enzoacvi** [comment]
Listo, subí de nuevo el archivo en la versión que lo estoy probando. 

Lo que sucede es que el `__str__` de `Caballero` es igual que el de `Mago`, `Guerrero` y las demás subclases de `Combatiente`, sin embargo es la única es donde python parece ignorar su `__str__` y toma directamente el de `Combatiente`

Estoy ejecutando el archivo en consola, imprimiendo una instancia de cada subclase, y las única instancias donde se retorna el `__str__` de `Combatiente` es para la clase `Caballero`. Luego también sucede que para la instancia de `CaballeroArcano`, se está imprimiendo el `__str__` de `Mago` y no el de `Caballero` (del que hereda primero)

**Comment by JJJGGGG** [comment]
Lo unico que se me ocurre es que tengas un problema de indentacion y que python no tome el metodo como parte de la clase. Intenta borrar el metodo y escribirlo todo de nuevo.

**Comment by enzoacvi** [comment]
😮 era esooooo

muchas muchas gracias
