### ISSUE TITLE
Duda formula tiempo por vuelta

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#187]
hola la formula tiempo por vuelta ocupa ceiling?
supongo que si porque tiene los paracentesis de floor pero invertidos 
 prefiero verificar gracias de antemano

**Comment by tomasgv** [comment]
Hola!

Efectivamente, _tiempo_vuelta_ usa la función techo. Puedes usar la función **math.ceil** para facilitarte este cálculo.

Saludos!! 😄

**Comment by JuaniAndres** [comment]
ok muchas gracias

**Comment by Jprampad** [comment]
¿No debería ser la función ´´´math.floor()```?
Saludos

**Comment by tomasgv** [comment]
Hola @Jprampad! 


La función **math.floor** se representa usando `⌊x⌋`, mientras que la función **math.ceil** se representa usando `⌈x⌉`. Ojo! en la fórmula _tiempo_vuelta_ se utiliza esta última:

![Captura de pantalla 2019-09-11 a la(s) 09 23 10](https://user-images.githubusercontent.com/48303402/64696851-dcab8080-d475-11e9-91fe-c0a10c735665.png)


Espero haber resuelto tu duda! 😄
