### ISSUE TITLE
Como funcionan los PATHs?

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2233/syllabus#188]
hola! ya durante todo el tiempo que hice la tarea abría los achivos usando solo algo = open("archivo.csv","r"). Y al estar guardado todo en la misma carpeta me funciona sin problemas, pero ahora leyendo denuevo todas las instrucciones veo que se menciona mucho los paths absolutos y paths relativos, y no entiendo como hacerlo, ya que osea, me funciona, pero no se si esta correcto o si a ustedes les va a funcionar cuando lo corrijan :/

**Comment by lily416** [comment]
Te recomiendo revisar el material sobre [paths](https://github.com/IIC2233/contenidos/blob/master/semana-00/3-paths.ipynb). 
Si después de revisarlo sigues con dudas, no dudes en volver a preguntar :)

Saludos 👋📂

**Comment by maggiemunoz** [comment]
sisi lo habia leido pero creo que lo hice bien, ustedes van a corregir con todos los archivos en la misma carpeta verdad?

**Comment by lily416** [comment]
Si, vamos a corregir con los archivos dentro de la carpeta `T00/`.

Saludos y éxito en la tarea 👋🐦

**Comment by maggiemunoz** [comment]
gracias!
