### ISSUE TITLE
Demora en procesamiento de datos

### ISSUE THREAD

**Issue by akrebs2** [IIC2233/Syllabus#188]
Hola. Quisiera saber si existe un límite de tiempo máximo para el procesamiento de datos en esta tarea? Pregunto esto dado que me he encontrado con problemas de ese tipo al manejar los 18.000 datos de jugadores que hay en los archivos.

**Comment by akrebs2** [comment]
Acabo de ver que han reducido el número.. Aún así, la pregunta sigue en pie para esos 5.000 datos

**Comment by llloyola** [comment]
Acaban de actualizar la base de datos. Ahora, son menos jugadores 😄

**Comment by cilopez** [comment]
¿Que tipo de problemas tienes?, ¿Al leer el archivo? o Al aplicar una función a la base de datos. Dependiendo de eso te podría decir que tiempos deberías manejar.

**Comment by cilopez** [comment]
@llloyola  Nuevamente estamos analizando la magnitud de los datos, por mientras puedes correr tu tarea leyendo 500 jugadores.

**Comment by llloyola** [comment]
Al leer sólo los primeros 500 no existe la posibilidad de que el grafo deje de ser conexo?

**Comment by cilopez** [comment]
Con 700 sé con certeza que es conexo , con 500 no he revisado.

**Comment by cilopez** [comment]
@ljrodriguez1  podrías subir tu código a tu repo, para ver si efectivamente lo estás haciendo de una forma eficiente.  Con 700 jugadores son 47.723 relaciones, yo he estado trabajando con una librería que se demora 0.53 segundos con estos números  por lo que calculo que demorarse mas de 100 segundos es poco eficiente.

**Comment by ljrodriguez1** [comment]
Perdón no entendía todavía de que se trataba esa parte, lo estaba haciendo de la manera menos eficiente, pero ya trabajo en otra

**Comment by santilaguna** [comment]
Hola! Me sucede lo mismo, aún reduciendo la cantidad de jugadores a 700 , me demoro aproximadamente 3 minutos para crear una matriz. ¿Existe una forma de iterar más rápido en una lista ligada que con el método __iter__?

**Comment by pcseisdedos** [comment]
Yo implemente iter y next en mi lista y tarda  1:35.865168 (~96 secs) en cargar las afinidades de los primeros 700 jugadores, está bien?

**Comment by cilopez** [comment]
@santilaguna  @pcseisdedos  quizás sus problemas no sean las estructuras de datos puede ser la forma como están leyendo la base de datos o como están creando sus relaciones.  Necesitaría más información para saber el porqué de sus tiempos.

**Comment by pcseisdedos** [comment]
Cambié mis listas por las de python y lo hice correr denuevo para probar, tarda 4.775264 (~5 secs) así que claramente mi estructura de datos es ineficiente. :/
Pero no se me ocurre como hacerlo mejor.

**Comment by santilaguna** [comment]
Me ocurre que al leer los jugadores y armar la matriz de incidencia se demora poco (como 5 segundos) pero al buscar la afinidad entre 2 jugadores que no son de grado uno se demora como 1 minuto. Las relaciones las contrui como una matriz de incidencia, pero en vez de usar diccionarios uso una lista de listas.

**Comment by PhilippePotin** [comment]
Hice lo mismo que @pcseisdedos y se tarda muy poco tiempo, por lo que también mis estructuras de datos son ineficientes. No se como hacer para que estas sean mas eficientes.
