### ISSUE TITLE
Duda ejercicio 2.2 Un error misterioso

### ISSUE THREAD

**Issue by FVivess** [IIC2233/syllabus#188]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Hola, no entiendo muy bien que se espera que se arregle en el ejercicio. Si borro la última linea de código deja de tirar error, lo que cumpliría lo que pide el enunciado, pero no creo que ese sea el objetivo.

**Comment by JuanpaBC** [comment]
Me parece que el único error es que tanto en el getter como en el setter de la property "atributo" se hace un mal llamado al atributo "_atributo". Si te fijas en ambos métodos se llama al atributo con "self.atributo", siendo que el atributo se definió con un underscore (probablemente para indicar que es un atributo privado), por lo que debería ser llamado como "self._atributo".

A mi por lo menos me funcionó el código bien haciendo ese cambio.
