### ISSUE TITLE
Duda archivos que subir Tarea 1

### ISSUE THREAD

**Issue by jtvvtj** [IIC2233/Syllabus#188]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Al final los archivos mínimos que habría que subir para la entrega de la Tarea 1, serían: 
1. README.md
2. dccultivo.py
3. main.py (se supone que así se llama el archivo que nosotros tuvimos que crear para los menus?)

Y con eso estariamos listos ciertos?

**Comment by jtvvtj** [comment]
y en este mismo al final, el archivo que ejecutaran los ayudantes sera el "main.py"?, en el cual se importa "dccultivo.py"?

**Comment by vgalfaro** [comment]
Hola, debes subir todos los archivos necesarios para el funcionamiento de tu tarea, te recomiendo leer #189 donde también hablan de cuales archivos hay que ignorar, respecto al archivo main.py, así es, es convención que este sea el archivo principal de tu tarea, pero debes especificar en el readme esto (que la tarea se debe ejecutar desde main.py), saludos!

**Comment by jtvvtj** [comment]
claro claro, pero estan los minimos y los que ademas yo creo. En este caso esos serían los minimos?

Entonces en main.py esta el menu, y en dccultivo esta todo el codigo de DCCultivo y Predio. 

Por lo que con esos 3 archivos deberia estar bien?

Diciendo que en el README que el que se ejecuta es el main.py?

Sorry que soy algo inseguro sdjsdj

**Comment by vgalfaro** [comment]
Sí, en este caso son mínimos, con esos archivos debería estar bien :) más adelante en el ramo las tareas se vuelven más complejas y es conveniente modularizar más para mantener el orden, en el readme debes explicar la finalidad de cada archivo, en particular, que en el main se ejecuta la tarea, saludos!

**Comment by jtvvtj** [comment]
Muchas graciaaas ya subi la tarea y con el readme explicado :)
