### ISSUE TITLE
deamon threads

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#188]
No entiendo por que estos dos códigos me arrojan el mismo resultado:

![Captura 1](https://user-images.githubusercontent.com/48294819/57202362-48cf2280-6f72-11e9-8a4d-b13c4ef34130.PNG)

y 
![Captura 2](https://user-images.githubusercontent.com/48294819/57202368-5b495c00-6f72-11e9-8180-63d08ddace76.PNG)

ya que se supone que como son deamon en el segundo caso como no se esta haciendo un .join() no deberia salir el segundo print

**Comment by Mahund** [comment]
Hola @jalliende !

Me parece que debe ser un error con Jupyter Notebook. Al menos cuando replique tu código en un archivo .py y lo ejecute por consola tuve los resultados esperados.

Intenta probar corriéndolo por consola a ver si funciona correctamente.

Saludos!
