### ISSUE TITLE
Problemas para actualizar la información y usar.gitignore

### ISSUE THREAD

**Issue by cmingom** [IIC2233/Syllabus#188]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hace un par de días actualicé mi repositorio usando hit add y hit push, subiendo material que pedían explícitamente no hacerlo y para arreglarlo, por error elimine la carpeta T1 completa, la cual restaure descargándola directo del computador (no me dejaba hacer push ni pull, ya que decía que había una divergencia) y al no entender el funcionamiento por completo no se como arreglarlo, para hacer que no diverja y como cambiar la información anterior por la nueva, ya que el .gitignore no me está funcionando como esperaba

**Comment by Hernan4444** [comment]
Hola @cmingom 

Lamento la tardanza de esto, respondo esta issue de todas formas para que encaso de volver a ocurrir algo así en la T2 o T3, tengan respuesta de qué hacer.

En particular, cuando hay divergencia, es porque en el repo de la nube hay cosas diferentes al repo de tu computador y el`push`o `pull` no saben qué hacer. Para esto recomendamos ver esta issue 

* #198 

En ella se dan los pasos a pasos para enfrentr el problema de divergencia.
Saludosヾ(＾-＾)ノ
