### ISSUE TITLE
Problema con países de 2 o mas palabras (Ej. Costa Rica)

### ISSUE THREAD

**Issue by Minjor** [IIC2233/Syllabus#188]
Estoy poblando el mundo con los países, al momento de conectarlos por frontera y aeropuerto y resulta que "Costa Rica" en population.csv es diferente a "Costa rica" de aeropuertos.csv, por la diferencia entre "R" y "r" no me reconoce que estoy hablando del mismo país entonces no me los conecta con nada, eso es algo que debería solucionar yo o es un error del archivo csv? Esto por lo que veo sucede con todos los países que tienen nombres de mas de 1 palabra como "Dominican Republic", "United Arab Emirates".

**Comment by Minjor** [comment]
podria ocupar lowercase o uppercase y corregirlo pero igual quiero saber :)

**Comment by KnowYourselves** [comment]
`str.title()`, `"Costa rica".title()` -> `Costa Rica`

**Comment by stephichau** [comment]
Ya se arreglaron los archivos!

**Comment by seba608** [comment]
Los nombre de el archivo airports siguen diciendo por ejemplo Costa rica y el de population Costa Rica. Es un error en los archivos o mi programa se tiene que encargar de que sepa que es el mismo pais? @stephichau
