### ISSUE TITLE
Duda sobre como hacer herencia particular.

### ISSUE THREAD

**Issue by gato1108** [IIC2233/Syllabus#188]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas.

Me encuentro con el siguiente problema:

Supongamos que las clases A y B definen 2método abstracto (digamos met1 y met2), provenientes de una clase padre abstracta  X. A y B definen de forma distinta a met1 y met2. Se crea una clase C que hereda de A y B. Quiero que la clase C defina el método met1 como lo hace A y met2 como lo hace B.

La única solución que se me ocurrió fue copiar todo el código de met1 (de A) y met2 (de B) y reescribir. Sin embargo, encuentro esta solución poco elegante, por lo que me gustaría saber si hay otra mejor.

Otra pregunta que tengo es si es posible definir métodos de clases dentro de un if, tipo:
if [evento]:
    def met1():
        [Defino de una forma]
else:
    def met1():
        [Defino de otra forma]

En caso de no ser posible que herramientas puedo usar para solucionarlo?

Muchas gracias de antemano,
Diego :)

**Comment by wintermelyn** [comment]
Hola @gato1108!

Recuerda que si escribimos una línea de la forma `SuperClase.metodo(self, argumentos)`, podemos invocar directamente la ejecución del método de la superclase. Para el ejemplo en particular que planteas

```python
from abc import ABC, abstractmethod

class X(ABC):
    @abstractmethod
    def met1(self):
        pass

    @abstractmethod
    def met2(self):
        pass

class A(X):
    def met1(self):
        print("Implementación de met1 en A")

    def met2(self):
        print("Implementación de met2 en A")

class B(X):
    def met1(self):
        print("Implementación de met1 en B")

    def met2(self):
        print("Implementación de met2 en B")

class C(A, B):
    def met1(self):
        # usar implementación de met1 en A
        A.met1(self)

    def met2(self):
        # usar implementación de met2 en B
        B.met2(self)


c = C()
c.met1() # Implementación de met1 en A
c.met2() # Implementación de met2 en B

```

Si decides implementar ese tipo de acercamiento al problema es muy importante que siempre consideres la posibilidad de "El problema del diamante", por lo que también te recomiendo mirar la sección de dicho problema en el cuaderno de contenidos de 3-multiherencia de la semana-04

**Comment by diegoftpxd** [comment]
Hola @gato1108. Respecto a la primera pregunta, por suerte si existe una forma más elegante!. Tienes la opción de sobre-escribir met1 en C y utilizar el `super()` para esta labor. La única diferencia que debes realizar es especificar en el `super()` desde donde quieres empezar a heredar.
Por ejemplo digamos que quieres llamar al metodo de Padre2 en la clase Hijo1. Puedes hacer algo parecido a:
```python
class Padre1:
    def __init__(self) -> None:
        self.nombre = "padre"
    def __str__(self):
        return f"Mira logré heredar :) {self.nombre}"

class Padre2:
    def __init__(self) -> None:
        self.nombre = "padre"
    def __str__(self):
        return f"AHORA TENGO EL CONTROL"

class Hijo1(Padre1, Padre2):
    def __init__(self) -> None:
        self.nombre = "Hijo"
    def __str__(self):
        return super(Padre1, self).__str__()
```
Fijate que en la clase hijo se está  llamando a `super(Padre1, self)` para llamar al metodo de la clase Padre2. Esto es porque de esta forma le decimos al super que empiece **DESPUÉS** de Padre1 a buscar el método. Como definí la herencia en el orden (Padre1, Padre2). Esto lleva a que Padre2 venga después de Padre1.
Así te proteges del problema del diamante de una forma más elegante.

Con respecto a la segunda duda, he hecho pruebas y parece no funcionar pero no descarto que haya alguna manera. Si quieres un comportamiento de este estilo puede servir poner el if dentro de la función y así cuando el evento sea True el metodo hará lo que le corresponde.

Espero te ayude 😄.

**Comment by gato1108** [comment]
Super :)
Muchas gracias a ambos <3
