### ISSUE TITLE
Estructura de datos

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#188]
Hola! estaba revisando las actividades de semestres anteriores (junto con los contenidos para apoyarme y también las ayudantías) y me di cuenta de que en ninguna actividad permiten el uso de estructuras de datos ya existentes (tupas, listas, diccionarios, etc), pero en todas las ayudantías y contenidos se utilizan estructuras ya existentes. 
Mi pregunta radica en cual sería la forma de almacenar la información e alguna manera sin poder tener una estructura. Saludos!

**Comment by fringlesinthestreet** [comment]
@rihanuch Hola

Efectivamente en las actividades de semestres pasados no se permitía el uso de estructuras de Python (Las built-in: ya sean listas, tuplas, etc). 
La idea era que ustedes crearan sus propias estructuras para almacenar información, específicamente con listas ligadas. Con estas pueden tener una 'lista' completamente funcional para almacenar distintas cosas.
Sin embargo, para la AC de esta semana sí se podrán utilizar (dentro de ciertos márgenes).
