### ISSUE TITLE
Dinero de usuario recién creado

### ISSUE THREAD

**Issue by anvaldes** [IIC2233/syllabus#188]
Cuando dinero se le debe asignar a un usuario recién creado? Porque en teoría no tiene autos y necesita comprar alguno para comenzar a correr. Y además no esta especificado en parámetros tal cifra. Lo que yo haría en verdad sería crear un valor en parametros.py que indice el dinero inicial.

**Comment by tomasgv** [comment]
Hola! 

Te recomiendo ver la issue #160. Como respuesta corta: queda a tu criterio agregar o no este parámetro 😄 

Saludos! 🚗 🚲
