### ISSUE TITLE
Atributos variables en Diagrama de Clases

### ISSUE THREAD

**Issue by MarquezFelipe** [IIC2233/Syllabus#188]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Buenas, mi duda es como representar en el diagrama de clases de la la tarea un atributo que inicie como string y luego sea un objeto.
Por ejemplo:
atributo1: str
atributo2: int
atributo_variable: str/object
No se si es correcto indicar ambos tipos o si solo indico el inicial o el final

**Comment by GonzaAlegria** [comment]
Hola Felipe, espero que estés super! 
La idea es declarar el tipo de variable según el valor que perdure mas tiempo en la tarea, en otras palabras, el tipo de variable que mas uses. Recuerda que puedes poner este tipo de supuestos en el README para facilitar la corrección.
¡Saludos!

**Comment by GonzaAlegria** [comment]
Hola Felipe, espero que estés super!
La idea es declarar el tipo de variable según el valor que perdure mas tiempo en la tarea, en otras palabras, el tipo de variable que mas uses. Recuerda que puedes poner este tipo de supuestos en el README para facilitar la corrección.
¡Saludos!

**Comment by GonzaAlegria** [comment]
Hola Felipe, espero que estés super!
La idea es declarar el tipo de atributo según el valor que perdure mas tiempo en la tarea, en otras palabras, el tipo de atributo que mas uses es el que debes poner en el diagrama. Recuerda que puedes poner este tipo de supuestos en el README para facilitar la corrección.
¡Saludos!
