### ISSUE TITLE
Doble impresión de tableros

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#188]
Hola!!! En el enunciado aparece que hay que imprimir el tablero cada vez que se ejecuta un disparo o se inicia el menú de juego. Entonces, ¿Cuando juega el oponente y luego el jugador tengo que imprimir el tablero dos veces? 
Pregunto porque cuando juegue el oponente habrá disparado (entonces hay que imprimir el tablero), y luego en el turno del jugador se imprime el menú de juego (y nuevamente habría que imprimir el tablero), entonces me queda el mismo tablero impreso dos veces seguidas. No sé si me expliqué bien 😔

**Comment by vicentevegaulloa** [comment]
Hola @denisseleiva!

No te preocupes si se repite inmediamente la impresión del tablero, el enunciado dice que se debe imprimir despues de un disparo y en el menú de juego, por lo que estarñia correcto si se imprime dos veces seguidas.

**Comment by denisseleiva** [comment]
Daleee, muchas gracias!!

**Comment by vicentevegaulloa** [comment]
Denada!!

**Comment by YehudaGurovich** [comment]
Wait... si lo imprimo una vez esta mal? pq lo habia regulado para no tener que imprimirlo 2 veces.

**Comment by vicentevegaulloa** [comment]
@YehudaGurovich te recomiendo fuertemente que lo imprimas dos veces, ya que eso es estrictamente lo que dice el enunciado. De todas formas comparto que se ve raro jaja pero el enunciado manda 😕

**Comment by YehudaGurovich** [comment]
Ok! Gracias!

**Comment by YehudaGurovich** [comment]
Cuando dice ejecute un disparo se refiere a un disparo del jugador, disparo del oponente o ambos?
Dice el enunciado en la parte 5.1: "Cada vez que se inicie el Menú de Juego o se ejecute un disparo, deberás representar en consola el tablero de juego." De ahi uno no necesariamente pensaría que son 2 veces que se imprime el tablero sino que esa expresión está para agregar que cuando uno inicie el menu de juego por primera vez se imprima el tablero a pesar que nadie ha disparado.

**Comment by vicentevegaulloa** [comment]
@YehudaGurovich se refiere a un disparo de ambos. Hay un ejemplo en el enunciado donde se muestra como se debería ver la consola despues de un disparo enemigo.
