### ISSUE TITLE
Problema al utilizar la tecla espacio al disparar

### ISSUE THREAD

**Issue by MarieCaussade** [IIC2233/Syllabus#188]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Cuando intento disparar con la tecla de espacio, el computador no la reconoce por lo que no se realiza ninguna acción. Intenté usando el número 32 (encontré en internet que este número corresponde al espacio), Qt.Key_Space, y " ", pero ninguno de los anteriores sirve. Todas las demás teclas me funcionan y puedo disparar con ellas utilizando los números correspondientes, por lo que estoy ocupando la tecla h (número 72) en lugar del espacio para disparar. ¿Existe alguna manera que no haya mencionado antes, que sirva para reconocer la tecla espacio?

**Comment by diegocostares** [comment]
Intenta poniendo un print de la tecla que está recibiendo

**Comment by MaxAl100** [comment]
[No soy ayudante]
Igual esto no es el fin del mundo, ya que en el enunciado dice que uno puede hacer que otra tecla sea la de disparar mientras uno lo mencione en su README.md. 
![image](https://user-images.githubusercontent.com/43099597/168620546-3aeab8e4-5250-4ca0-9e47-e430711854ba.png)

**Comment by FelipeBurgos** [comment]
[No soy ayudante]

Pude solucionar eso utilizando lo siguiente:
self.boton = QPushButton()    (defino mi botón)
self.boton.setFocusPolicy(Qt.NoFocus)    (hace que no se aprete con el espacio)

pd: Qt viene de PyQt5.QtCore
