### ISSUE TITLE
clases abstractas y herencia de properties

### ISSUE THREAD

**Issue by pazanelli** [IIC2233/syllabus#189]
Hola
respecto a las properties en clases abstractas:
Entiendo que puedo crear @abstractproperties dentro de una clase abstracta para luego hacer overriding en una subclase. El tema es si quiero que esa propertie tenga un setter, ¿debería definir el setter dentro de la clase abstracta tambien?, o ¿dejo solo el getter definido como abstractpropertie y en la Subclase defino el setter?

**Comment by jeschuwirth** [comment]
Hola!

Un gran consejo para estas dudas es probar por ti mismo como funciona, personalmente no estoy seguro y sé que muchos ayudantes tampoco lo saben de memoria, pero muchos de nosotros crearíamos un archivo `test.py` donde definiríamos la clase y probaríamos ambas formas para ver cual funciona.

Te recomiendo hacer lo mismo ya que es una muy buena practica a la hora de programar :)

Si lo intentas y no llegas a una conclusión sigue preguntando en la issue e intentaré lo mismo para ver si llego a una respuesta y te la mando.

Suerte!
