### ISSUE TITLE
README: ¿Qué son los módulos creados?

### ISSUE THREAD

**Issue by BorjaLarrain** [IIC2233/Syllabus#189]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! 

Leyendo la plantilla de README que nos dieron no entiendo bien que son los módulos creados. Por ejemplo si creo un archivo con una función y luego hago import de ese archivo y función, ¿Eso sería un módulo creado? 

Si hago import de una clase de otro archivo, ese archivo sería un módulo?

**Comment by Benjeeeh** [comment]
Hola! 
Exactamente, todo lo que crees o agregues como método/función sería un módulo que creaste.
El archivo que creaste con tu función debería quedar como lo siguiente: 
**libreria_x: Ubicada en archivo_x, contiene a función_x, etc...** 
No es necesario que seas tan específico y expliques cada uno, si no que si creaste un archivo expliques brevemente lo que contiene y que hace.
Ojo que es solo para lo que crees, también sirve si es que agregaste un nuevo método a una clase (aunque también lo puedes comentar en el propio código), pero si importaste algo que ya estaba hecho (como los archivos.py adicionales que entregamos) no es necesario que lo agregues ahí ya que tu no lo creaste.

Saludos y éxito con la tarea!
