### ISSUE TITLE
Try y Except en importación de módulos

### ISSUE THREAD

**Issue by TomasArancibia** [IIC2233/Syllabus#189]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Se puede usar try y except para importar módulos de forma que la ventana creada en donde se quiere importar puede ser abierta tanto en el main como en el modulo en donde se esta creando, de esta forma es mas cómodo para el debug, ¿Se puede usar esto o se considera como una mala practica? A continuación hay un ejemplo de a lo q me refiero.

try:
    from frontend.rutas import RUTA_LOGO, BOTTON_STYLE, BACKGROUND
except ImportError:
    from rutas import RUTA_LOGO, BOTTON_STYLE, BACKGROUND

**Comment by CristobalPerez-Cotapos** [comment]
Hola Tomas!! Lo que me comentas te puede resultar útil para comprobar que partes específicas de tu código están funcionando, pero al momento de la entrega debes borrarlo ya que no es una forma "adecuada" de hacer las importaciones. 
Igual puedes tener en cuenta que solo se ejecutará el archivo que especifiques en el readme a la hora de corregir 😉

**Comment by TomasArancibia** [comment]
okk muchas gracias
