### ISSUE TITLE
No entiendo diferencia entre __str__ y __rep__

### ISSUE THREAD

**Issue by Kevinnevik** [IIC2233/syllabus#189]
Hola, leí el material y busque en internet pero aun no entiendo su diferencia

**Comment by MatiasDuhalde** [comment]
Hola @Kevinnevik !

`__str__` y `__repr__` son métodos especiales de los objetos en Python. Ambos métodos retornan strings, pero su uso es un poco distinto. `__str__` apunta a ser la forma en "string" del objeto, mientras que `__repr__` busca ser la representación misma del objeto. Si creamos nuestras propias clases, y luego intentamos imprimir el objeto mismo, nos va a retornar la dirección de memoria en la cual está el objeto, como se puede ver en el siguiente ejemplo:
```python
class MiClase:
    pass

objeto = MiClase()
print(objeto)
```
Output:
```
<__main__.MiClase object at 0x000001E509C0A248>
```
Sin embargo, en general, esto no es muy útil, y nos gustaría tener algo más descriptivo. Es por esto que existen los métodos especiales `__str__` y `__repr__`.

Con respecto a sus diferencias conceptuales, la idea de `__str__` es obtener una representación del objeto clara y legible por el usuario. Quizás al usuario le interesaría conocer ciertos atributos especificos del objeto, más que el objeto en su totalidad, y en esa información debería centrarse `__str__`.

La idea de `__repr__` es entregar una representación concisa del objeto, que indique sin ambiguedades el origen y las características de este. Una buena práctica para definir el output de `__repr__` es usar el siguiente formato: `NombreClase(valor_atributo1, valor_atributo2, ...)`.

Con respecto a sus diferencias de funcionamiento, como se explica en los contenidos, si en una clase no se define el método `__str__`, se usa directamente el output del método `__repr__`. El output de `__str__` aparece cuando transformamos el objeto a string usando `str(objeto)`, y también en otras ocasiones como cuando los queremos imprimir directamente con `print(objeto)` (la función `print` convierte al objeto en string por detrás antes de mostrarlo).

Por otra parte, el output de `__repr__` aparece cuando no se definió `__str__`, como se mencionó anteriormente, cuando llamamos a `repr` directamente (usando `repr(objeto)`), o en otras ocasiones, como por ejemplo cuando imprimimos una lista que contiene a dichos objetos. 

Usando el ejemplo de los contenidos para aclarar un poco las cosas:
```python
class Fraccion: 
    def __init__(self, numerador, denominador): 
        self.numerador = numerador 
        self.denominador = denominador
        
    def __repr__(self):
        return f"Fraccion({self.numerador}, {self.denominador})"
    
    def __str__(self):
        return f"{self.numerador} / {self.denominador}"
    
fraccion = Fraccion(6, 5)
lista_fracciones = [Fraccion(3, 4), Fraccion(2, 9), Fraccion(10, 3), Fraccion(23, 7)]
print(fraccion)
print(lista_fracciones)
```
Output:
```
6 / 5
[Fraccion(3, 4), Fraccion(2, 9), Fraccion(10, 3), Fraccion(23, 7)]
```
La primera línea del output usaría el método `__str__`, y la segunda `__repr__`.


Si quieres probar código por tí mismo y ahondar un poco más, te recomiendo intentar el ejercicio 4.1 de los ejercicios propuestos de la [semana 2](https://github.com/IIC2233/contenidos/blob/master/semana-02/ejercicios_propuestos.ipynb).

Ojalá esto quede un poco más claro, y si continúas con dudas, háznoslas saber!
