### ISSUE TITLE
Ejercicio 3.2 Semana 2: Herencia

### ISSUE THREAD

**Issue by fernandolalanne** [IIC2233/syllabus#189]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Hola! Estaba practicando herencias pero la verdad es que estoy medio confundido. Intenté hacer el ejercicio del título de la issue y quería saber si está bien. El código lo adjunto más abajo. En este sentido, en el caso de que esté bien escrito quería saber si SIEMPRE debo definir la subclase con los mismos parámetros de la superase. Por ejemplo qué sucede si tengo una subclase definida con un init (a,b,c) y mi superase se define con un init (a,b,c,d). ¿Qué sucede en esos casos? ¿Python arroja un error?.

Desde ya muchas gracias!!

```python
############ CODIGO ###########
 
class Musico:
    
    def __init__(self, nombre, afinidad,tipo):
        # Completar
        self.nombre = nombre
        self.afinidad = afinidad
        self.tipo = tipo
        pass
    
    def presentarse(self):
        print(f"¡Hola! Mi nombre es {nombre} y soy {tipo}.")
        pass

class Cantante(Musico): 
    
    def __init__(self, nombre, afinidad, tono):
        Musico.__init__(self, nombre, afinidad, tipo)
        self.tono = tono
        pass
    
    def cantar(self):
        if self.tono == "Bajo":
            self.afinidad = int(self.afinidad) * 2
        elif self.tono == "Soprano":
            self.afinidad = int(self.afinidad) * 0.5
        elif self.tono == "Tenor":
            self.afinidad = int(self.afinidad)
```

**Comment by aaossa** [comment]
Más allá del código del ejercicio, responderé tu pregunta sobre qué ocurre cuando una superclase requiere más argumentos que los que tiene la subclase. Primero que todo, no he visto que una situación así ocurra en un modelamiento, y tampoco me hace mucho sentido que ocurra, por lo que a primera vista diría que algo no está bien modelado. Lo que tienes que preguntarte es en primer lugar si tu modelo hace sentido. Por ejemplo, para definir una instancia de una clase `Persona` necesito su nombre y RUT. Luego, para definir una subclase de persona, digamos `Estudiante`, ¿cuándo sería razonable que no me entreguen alguno de esos dos argumentos? Es difícil encontrar un ejemplo así, porque en general en una buena modelación eso no debería ocurrir. De todas maneras, veamos "qué pasaría sí":

```python
class Superclase:

    def __init__(self, a, b, c):
        self.a = a
        self.b = b
        self.c = c

class Subclase(Superclase):

    def __init__(self, a, b):
        super().__init__(a, b, ???)

if __name__ == '__main__':
    sub = Subclase(1, 2)
    print(sub.a, sub.b, sub.c)
```

¿Qué le pasamos como tercer argumento a la `Superclase`? Puede ser cualquier valor que te parezca razonable en tu modelación. Por ejemplo, el atributo `c` puede ser siempre 5, aunque en ese caso quizás sea mejor que `c` sea un atributo de la subclase. ¿Y si tenemos otras subclases con otros valores para `c`? Quizás en ese caso haga más sentido que siempre definas el atributo en el `__init__` de la subclase y que no se pase a la superclase. También podrías definir un valor por defecto para la `Superclase` y solo pasarlo si es necesario a través del super en la Subclase (`super().__init__(a, b, c=5)`). En resumen, difícilmente encontrarás la situación que planteas porque en general podrás modelarlo de una mejor forma.

**Comment by fernandolalanne** [comment]
Gracias ahi entendí!!

Saludos!
