### ISSUE TITLE
Cerrar fronteras

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#189]
Para obtener la prioridad acerca de la" medida" de cerrar la frontera: 
Lo que yo entiendo es que se calcula solo si se cumplen las condiciones (50% o mas de población infectada o 25% o mas de personas muertas en el país) y sino según yo cerrar frontera tiene cero prioridad ¿o no?. Por otra parte si se cumplen las condiciones que mencioné anteriormente, para calcular la prioridad: ¿Debo considerar si es que alguno de los países vecinos cerró su frontera? o ¿se calcula el promedio del % de infectados de los países fronterizos sin importar si ellos tienen cerrada su frontera? --> Esto último implicaría que cada país toma los resguardos sin importar si los países vecinos ya tomaron los propios (cerrar frontera).

Dudas extras: 
a) Si A -> B ->C donde -> significa que hay conexión (fronteriza por ejemplo), se considera entonces que A -> C ??

b) en el enunciado dicen que las conexiones se generan aleatoriamente en cada partida, esto significa que el jugador inicia una partida con ciertas conexiones aéreas  y cuando vuelva a entrar esas conexiones se deben mantener?

**Comment by FernandoPieressa** [comment]
Exacto, solo si se cumplen las condiciones se puede cerrar la frontera y entrar en la lista de prioridades, sino se cumple no va a entrar en la lista de acciones del gobierno porque no es una accion que necesiten tomar.  Las decisiones del gobierno país no dependen de los otros por lo tanto no se consideran si los vecinos cerraron su frontera.

Respecto a las dudas extras:

a) No, las fronteras no funcionan asi,  o podrias decir por ejemplo que Chile tiene frontera con Brazil, sin embargo el B si podría ser contagiado por A para que llegue el virus hasta C despues.

b) Al iniciar una partida nueva se generan conexiones aleatorias, pero si quieres guardar para seguir mas adelante tiene que mantenerse las conexiones aleatorias iniciales.


Saludos!
