### ISSUE TITLE
Ejericicio 3.3 de la semana 2

### ISSUE THREAD

**Issue by anamanzana** [IIC2233/syllabus#189]
El codigo me corre y me arroja:

Soy Pedro y sus resultados son:
Muy bien
None
Muy bien
None

Asumo que no programe bien la función programar_tarea().
Me gustaría saber, que debería arrojar? Entiendo que se crea una clase y esta debería contener el input?

**Comment by Tito0906** [comment]
Holaa @anamanzana, lamentablemente no te puedo decir exactamente la solución del ejercicio, pero la función programar_tarea(), debe crear un objeto de tipo Tarea, donde uno de sus argumentos es el nombre que recibe la función. El objetivo de esta función es que retorne el objeto Tarea (junto con sus atributos correctamente definidos) para poder utilizarlo en la función corregir_tarea del ayudante corrector. 

Saludos y éxito con el estudio!

**Comment by anamanzana** [comment]
Pero que debería devolver en vez de None?

**Comment by Tito0906** [comment]
Holaa @anamanzana , como se puede ver en el ejercicio, el último ayudante en llamar a un método es el TutorDocente que llama el único método que contiene. Este método debe tener (según enunciado) tres posibles return: "Tarea no corregida por el ayudante", "No Corregido" o "Muy bien". Por último, se puede ver que el TutorDocente sólo llama a su método dos veces, por lo que deberían obtenerse sólo 2 prints.

Saludos y éxito con el estudio!

**Comment by anamanzana** [comment]
Al final tenia print en vez de return en la función xD

Muchas gracias!
