### ISSUE TITLE
Archivo log.md

### ISSUE THREAD

**Issue by Simon-Cabrera** [IIC2233/Syllabus#189]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, 

tengo un pequeña pregunta con respecto a los archivos de la tarea 2 **¿Que se debe hacer con el archivo log.md?**

Saludos, buen fin de semana.

**Comment by diegoftpxd** [comment]
Hola! @Simon-Cabrera  , el log.md es un archivo donde se va a ir actualizando información relevante de la tarea. Lo van a ir actualizando en el syllabus con el tiempo y la idea es que lo vayan viendo de vez en cuando. No es necesario que los alumnos lo modifiquen.

**Comment by Vicente1824** [comment]
Holi, en ese caso, podemos añadir el log.md al gitignore? O debe estar en nuestro repo si o si?

**Comment by diegoftpxd** [comment]
Hola @Vicente1824 , Como log.md no es necesario para el funcionamiento de tu tarea es recomendable ponerlo en el .gitignore.
