### ISSUE TITLE
Material de arboles

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#189]
Hola me surgio una duda con respecto a las funciones para encontrar todos los nodos. 
Por ejemplo en este:

```python
class ArbolPostOrder(Arbol):
    # Heredamos de la clase original del Arbol e implementamos el PostOrder para el recorrido del arbol
    def __repr__(self):
        def recorrer_arbol(raiz):
            # primero recorremos recursivamente los hijos
            for hijo in raiz.hijos.values():
                recorrer_arbol(hijo)
            
            # Finalmente visitamos el nodo raíz
            self.ret += "nodo_id: {}, id_padre: {} -> valor: {}\n".format(raiz.id_nodo, raiz.id_padre, raiz.valor)
            return self

        self.ret = ''
        recorrer_arbol(self)
        return self.ret
```

No entiendo la existencia del "return self" en todos los metodos que mostraron. ¿Para que sirve?

**Comment by movaldivia** [comment]
Si me surgió la misma duda ya que en principio además las cosas que pasan dentro de la función deberían ser locales pero aquí son "globales" (dentro del metodo)

**Comment by fringlesinthestreet** [comment]
@nmaturana97 En este caso el ```return self``` no aporta nada, de hecho se puede comentar. Probablemente se puso porque como la función ```recorrer_arbol``` recibe un nodo, por lo que al finalizar lo retorna.

@movaldivia Esto sucede porque la función ```recorrer_arbol``` no es un método de la clase ```ArbolPostOrder```, sino que es sólo una función. El que el atributo ```self.ret``` se comporte como ''_global_'' es porque es mutable. Veamos un ejemplo:

```
def funcion(*argumentos):

    for item in argumentos:
        lista_args.append(item)

lista_args = list()
funcion("arg1", "arg2")
print(lista_args)  # Imprime ["arg1", "arg2"]
```

En este ejemplo la función toma un número indefinidos de argumentos y se los ingresa a una lista llamada ```lista_args```. Esta lista si te fijas está definida afuera del _scope_ de la función y se utiliza en ella. Como las listas son objetos mutables, una vez fuera del _scope_ de la función los cambios hechos dentro se mantienen.
Esto no pasa con objetos inmutables como podemos ver en el siguiente ejemplo:

```
def funcion(value):

    value += 3
    print(value)  # Imprime 8

variable = 5
funcion(variable)
print(variable)  # Imprime 5
```

En este caso el cambio __no__ se mantiene. Las clases, como en este caso ```ArbolPostOrder```, son objetos mutables por lo que los cambios a alguno de sus atributos sí se mantiene luego de salir de una función.

**Comment by movaldivia** [comment]
@fringlesinthestreet En verdad muchas gracias por la explicación !!! Me quedo muy claro. Si se pudiese dar triple likes te lo daría.
