### ISSUE TITLE
Sobre join en threading

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2233/syllabus#189]
Estaba viendo los contenidos, y me encontré con este código:
```python
with open("files/salida.txt", "w") as archivo:
    # Creamos los threads
    cantidad_threads = 7
    threads = [EscritorArchivo(i, archivo) for i in range(cantidad_threads)]
    
    # Hacemos partir los threads
    for thread in threads:
        thread.start()

    # Esperamos a todos los threads antes de cerrar el archivo
    for thread in threads:
        thread.join()
```
Al final, se pide que el main thread espere que terminen todos los otros threads antes de cerrarse. Mi duda es, por qué esto es necesario si los threads no son daemon? O el thread principal es daemon necesariamente? Intentaría adivinar que es simplemente un ejemplo pedagógico para recordarnos el uso de ```Thread.join()```, pero no me queda claro.

**Comment by Mahund** [comment]
Hola @JJJGGGG !

La idea de cada thread es que mediante *Locks* puedan escribir cada uno una linea en un archivo.

La sentencia `join()` en este caso la ocupamos para esperar que todos los threads terminan para salir del `with`, para asi evitar que un thread intente escribir en un archivo que ya fue cerrado.

Recuerda que al no ser deamon lo que pasa es el el *MainThread* o *Codigo Principal* al finalizar espera a los threads, pero en este caso eso incluyo el cierre del archivo que estan trabajando.

Espero te haya quedado claro, saludos!
