### ISSUE TITLE
Archivo .keep

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#189]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holaa, tengo una duda sobre un archivo que se creó en mi carpeta de la Tarea 1, es el archivo ".keep". Al momento de crear el .gitignore agregué el archivo .keep, sin embargo, al momento de subir mi Tarea a GitHub, se subió el archivo .keep. Entonces mi pregunta es si debo eliminarlo de mi repositorio en GitHub, o lo dejo subido?

**Comment by individuocomunycorriente** [comment]
Hola!
Según el enunciado, solo debes ignorar mediante .gitignore carpetas/archivos tales como (el enunciado, utils.pyc, data/, test_publicos/, README_inicial.md). Además no te debes preocupar de .keep dado que (como dato geek) este archivo se usa para garantizar que un directorio se mantenga en tu repositorio aunque se encuentre vacío (lo que no tiene relevancia en este curso) y por lo que cuentas .gitignore no puede hacer nada contra este archivo xd (desconozco lo ultimo mencionado).
Saludos.

**Comment by martinpint** [comment]
Hola, entonces debo quitar .keep de .gitignore??

**Comment by individuocomunycorriente** [comment]
Según el enunciado está demás incluir **.keep** en **.gitignore**, así que no lo incluyas.
