### ISSUE TITLE
Librerías permitidas, no permitidas y malas prácticas T1

### ISSUE THREAD

**Issue by mpiavf** [IIC2233/Syllabus#19]
Para consultar sobre una librería deben responder esta *issue* con una pregunta de la siguiente forma:
 
> **¿Puedo usar la librería `nombre_librería` para hacer `explicación_de_lo_que_quiero_hacer`?**
 
¡Recuerden especificar en su README qué librerías utilizan!
 
---
 
## ✔ **Librerías Permitidas** 
- itertools
- copy
- pprint
- os.path.join
- sys.exit
- sys.argv
- pathlib
- os.path.exists
- os.path.isfile
- math
- collections.deque
- os.path.dirname
- os.path.basename
- os.path (Tengan **ojo** de usarlo correctamente para que no cause problemas en la correción desde otro computador)
- os.listdir
- sum
- copy.deepcopy

## ✅  **Contenidos permitidos**

- Todo material visto al momento de publicar la tarea
- Contenidos que veremos en la semana 2 (diccionario, list comprehension, etc).

 
## ❌ **Librerías Prohibidas**
- csv
- json
- pickle
- shutil
- glob
- pandas
- numpy
- ast
- curses
- io
- re
- sqlite3
- beautifultable
- sys.path
 
## ☠️ **_Built-ins_ Prohibidos** 

El uso de alguna de las siguiente funciones es automáticamente un 1,0 sin discusión: 😭
- exec 
- eval

## Malas prácticas
El uso de las siguientes prácticas será considerado una mala práctica y puede repercutir en descuento a la evaluación.
-  `except Exception:` o únicamente ` except:` (excepciones bien capturadas sí estarán permitidas).
- Variables globales de cualquier tipo
- `Import *` o _imports_ que no se encuentren al inicio del programa.
- Uso de paths (absolutos o relativos) que no permita ejecutar la tarea correctamente en cualquier computador siguiendo las instrucciones del enunciado.
- No añadir _encoding_ al momento de trabajar archivos.
 
¡Éxito en sus tareas! 🚈🐈

**Comment by elneitans** [comment]
Hola, ¿estará permitido os.path.exists?

**Comment by mpiavf** [comment]
Hola @elneitans !
Sí, está permitido usar `os.path.exits` , te recuerdo que siempre menciones para qué quieres usar la librería :D
Saludos

**Comment by lil-kuo** [comment]
Hola, ¿Se pueden usar list comprehension en la tarea?

**Comment by mpiavf** [comment]
Hola @lil-kuo !
Sí puedes usar ´list comprehension´, dado que es un contenido **ya visto** en clases c: 
Saludos

**Comment by arturopachecoh** [comment]
Hola, puedo usar os.path.isfile para comprobar si un archivo existe?

**Comment by AndresFerrerC** [comment]
Hola, puedo usar math?

**Comment by mpiavf** [comment]
Hola!
@arturopachecoh  Sí puedes usar os.path.isfile :D
@AndresFerrerC  Sí puedes usar math c:
Saludos

**Comment by ddonosoh** [comment]
Hola! ¿puedo usar la función deque() de la librería collections para leer la red del archivo en cambiar_planos?
y puedo usar diccionarios en la T1? (contenido semana 2)?

**Comment by mpiavf** [comment]
Hola @ddonosoh !
Si puedes usar deque() de la librería collections.
Si puedes usar diccionarios, ya que es un contenido que se ve durante esta semana :D
Saludos

**Comment by Eoweo** [comment]
Hola, ¿puedo hacer uso de las funciones os.path.dirname y os.path.basename, para generar path absolutos ejecutables en cualquier os? y una consulta general, ¿se pueden hacer uso de todas las librerías que se ocupen en los contenidos?, dado que por ejemplo os.path.dirname no aparece en las librerias permitidas

**Comment by mpiavf** [comment]
Hola @Eoweo !
Sí puedes hacer uso de os.path.dirname y de os.path.basename.
No se pueden hacer uso de las librerias que se utilicen en los contenidos hasta que sean **preguntadas por aquí** y se tenga una respuesta favorable, esto porque en el enunciado se dice que toda librería está **prohibida** a no ser que se indique lo contrario en la issue de las librerías c:
Saludos

**Comment by MathItYT** [comment]
Hola. ¿Se puede usar la función *built-in* `sum`? ¡Gracias!

**Comment by Bennjapa** [comment]
Hola, ¿os.listdir() esta permitido?

**Comment by mpiavf** [comment]
Hola!
@MathItYT Sí, se puede usar sum 
@Bennjapa Sí, se puede usar os.listdir
Saludos :D

**Comment by Snick2004** [comment]
Hola buenas, se puede usar copy.deepcopy()?

**Comment by mpiavf** [comment]
Hola @Snick2004 !
Sí, puedes usar copy.deepcopy c:
Saludos

**Comment by Eoweo** [comment]
consulta, se pueden importar librerías y generar funciones nuevas en dentro de red.py? o se debe realizar un documento nuevo e importar todo junto a red.py?

**Comment by mpiavf** [comment]
Hola @Eoweo, si puedes, te recomiendo ver las issues #86 y #41 para que quede mas claro.
Saludos

**Comment by carlosmartellus** [comment]
Hola, se puede utilizar un except de archivo no encontrado?

**Comment by mpiavf** [comment]
Hola @carlosmartellus !
Siempre y cuando el except de archivo no encontrado esté bien capturado si puedes :D
Saludos

**Comment by coniverav** [comment]
Hola, en PEP 8 se indica que se deben usar "variables aclarativas y descriptivas", esto también aplica para las variables de contador usadas en "_for **i** in range..._"? O es mejor optar por ponerles _contador1_, _contador2_...?

**Comment by vruizz22** [comment]
Holaa!! Si implemente Try y except ValueError para mi archivo main.py cuando existan errores de valores ingresados para las opciones (1,2,3 o 4) donde hago que el usuario vuelva al menú si el valor ingresado no es un número. ¿Entonces el try/except esta bien capturado?

**Comment by josefinaabbott** [comment]
Hola! Se puede usar getattr?

**Comment by Yeps3nM** [comment]
Hola!! Si implemento el try except en el menú en caso de que me arroje error por alguna dificultad con las funciones de red.py , para que aún así vuelva a mostrar el menú. Estaría permitido?

**Comment by mpiavf** [comment]
Hola!
@coniverav Sí, aplica para todas las variables, el ejemplo que das no cumple con eso. 
@vruizz22 Sí, ya que es ValueError.
@Yeps3nM Sí, siempre y cuando esté bien capturado y no sea except a secas o except Exception.

**Comment by d0minga** [comment]
no hay que añadir encodings? o una mala práctica es no añadir encodings?

**Comment by coniverav** [comment]
EL readme se debe subir con el nuevo nombre "README BASE.md" o hay que ponerle "README.md" como estaba en un inicio?

**Comment by mpiavf** [comment]
Hola !
@d0minga Es una mala practica **no añadir encoding al trabajar con archivos**.
@coniverav El nombre debe ser **README.md**. 
Saludos

**Comment by Palik375** [comment]
Hola!, Se puede ocupar os.system("cls") para limpiar la consola?

**Comment by UnFedaykin** [comment]
Hola! Se permite usar os.chdir() para acceder a una carpeta?

**Comment by mpiavf** [comment]
Hola !
@Palik375 No se puede usar os.system("cls").
@UnFedaykin No se puede usar os.chdir().
Saludos

**Comment by mpiavf** [comment]
[Aclaración]
@vruizz22 @Yeps3nM Hola,  respecto a la respuesta que les di con anterioridad **no pueden** utilizar **try/except** ya que es un contenido que no se ha visto en el curso todavía D:, solamente pueden utilizar **excepciones bien capturadas**. 
Saludos

**Comment by mpiavf** [comment]
@Yeps3nM 

Hola

Con bien capturadas es que justamente  el except tenga al lado la excepción específica que quieren capturar.

Tener algo como 

try:
    ...
except:
    ...

o 

try:
    ...
except Exception:
    ...

No está permitido, dado que más adelante del curso aprenderemos correctamente este contenido y veremos por qué es mala práctica lo expuesto anteriormente. Si se desea utilizar este contenido (try/Except), se deberá investigar cómo utilizar correctamente, o bien utilizar los contenidos que hemos aprendido hasta ahora para enfrentar la tarea.
