### ISSUE TITLE
Opción "Revisar el estado de encomiendas realizadas"

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#19]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el menú de usuario se pide acceder a "el estado de las encomiendas realizadas" que son por el usuario de la sesión. Estas sólo tienen que ser aquellas que se hayan creado dentro de esta misma, ¿no?
Pregunto esto ya que en la tarea no se considera esto en la información de cada encomienda, es decir no se guardan luego de que el programa se cierre. Esto también se observa al no estar incluida esta información (de quién origina la encomienda) en el .csv de encomiendas que venía junto a la tarea.

----------------------------

Imagen donde se pide lo descrito anteriormente:
![image](https://user-images.githubusercontent.com/43099597/159135894-f6a8dd0a-46fb-4c68-b3bf-d9ba2477d68a.png)

Imagen de ejemplo de encomiendas donde se observa que no aparece el origen de la encomienda:
![image](https://user-images.githubusercontent.com/43099597/159135917-9b2f1cb7-fd07-4d2f-b9a4-e9ac40bd77c6.png)

**Comment by benjaaguila** [comment]
Hola @MaxAl100! Sí, debes considerar las encomiendas en **tiempo real**, es decir, las que se han realizado dentro de la misma sesión.

**Comment by MaxAl100** [comment]
Ok, muchas gracias! :)

**Comment by cristhanos** [comment]
@benjaaguila Hola, sigo sin entender para qué sirve el archivo "encomiendas.csv", si no sé qué usuario realizó cada encomienda. 
Lo que piden es mostrar el nombre del artículo y el estado de las encomiendas realizadas por el usuario de la sesión; puedo almacenar las encomiendas nuevas que realice cada usuario en una lista de diccionarios, pero no voy a saber quién realizó las que se encuentran en el archivo por defecto. Tampoco sería bueno agregar las encomiendas nuevas al archivo "encomiendas.csv", ya que tendría que cambiar el formato en que están organizadas (tendría que agregarle: "emisor).
Por favor sean más detallados al explicar!
Gracias :)))

**Comment by Daniel-Guajardo** [comment]
> Hola @MaxAl100! Sí, cuando se pide revisar el estado de encomiendas realizadas debes considerar las encomiendas en **tiempo real**, es decir, las que el usuario ha realizado dentro de la misma sesión.

@benjaaguila eso podría funcionar manteniendo guardadas de forma temporal en una variable las encomiendas creadas por un usuario, pero a la hora de cerrar el programa y abrirlo otra vez, estas encomiendas ya no podrán revisarse. Para un software de encomiendas encuentro que es poco práctico no tener acceso a las encomiendas realizadas por un usuario sólo empleando el archivo **encomiendas.csv**. Por otro lado, si se mostraran sólo las encomiendas agregadas dentro de la misma sesión, sería absurdo que pidieran que se mostrara el estado, ya que éste siempre sería **"Emitida"**.

Creo que esta operación dentro del software está algo confusa.

**Comment by benjaaguila** [comment]
Hola @cristhanos  ! Para la opción de revisar el estado de encomiendas realizadas se deben desplegar las encomiendas realizadas dentro de la **misma sesión**, es decir, una vez cerrado el programa y abierto nuevamente las encomiendas realizadas parten de cero. Por lo tanto, las encomiendas que vienen por defecto en el archivo encomiendas.csv no deben ser desplegadas en **esta opción**.

Sin embargo, es importante que al crear una nueva encomienda esta **si quede registrada** en el archivo encomiendas.csv en el mismo formato entregado(sin agregarle el atributo "emisor"). También deben desplegarse todas las encomiendas del archivo en la opción de **actualizar encomiendas** del **Menú de administrador** para que así el administrador pueda ir actualizando las encomiendas y también debe ir **actualizándose el archivo encomiendas.csv**.

**Comment by benjaaguila** [comment]
Hola @Daniel-Guajardo ! No es absurdo que pidamos que se muestre el estado de las encomiendas, ya que tal como mencione arriba, siempre que se cree una nueva encomienda, esta **debe quedar registrada** en el archivo encomiendas.csv. Así como también a medida que el administrador vaya actualizando el estado de las encomiendas esto también **debe quedar registrado** en el archivo encomiendas.csv. Por lo tanto aunque el usuario la vea como emitida, el administrador seguirá pidiendo actualizar su estado(modificando el archivo encomiendas.csv) así que si tiene sentido.

**Comment by Daniel-Guajardo** [comment]
Creo que ahora sí me queda más claro cómo funciona esa operación. Gracias por la explicación.
