### ISSUE TITLE
No se instala Jupyter luego de escribir el comando necesario

### ISSUE THREAD

**Issue by bgonzp** [IIC2233/Syllabus#19]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema
Hola como estan? Mi problema es que luego de escrbir el codigo de update me parece que todo esta bien, pero luego al usar el codigo de instalar jupyter nunca me sale que se instalo correctamente, luego al poner jupyter notebook, no se me habre ni ma aparece ningun link.
[Describe tu problema de manera detallada, explicando qué estás intentando hacer y explicando los errores o problemas que has encontrado. Se recomienda agregar fotos cuando sea posible]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]
![Captura de pantalla 2023-08-16 133640](https://github.com/IIC2233/Syllabus/assets/141947842/bb86c39d-9bbe-48f1-9c96-effe427ea3fa)
![Captura de pantalla 2023-08-16 133802](https://github.com/IIC2233/Syllabus/assets/141947842/2b40a44f-c18e-483f-a622-495ac71670a4)

![Captura de pantalla 2023-08-16 134139](https://github.com/IIC2233/Syllabus/assets/141947842/e0403597-10ce-4268-950e-c4f5450c9c08)

**Comment by Hernan4444** [comment]
Hola @bgonzp 

Por el momento intentemos esto:

1. Cerrar la terminal
2. Abrir powershell como administrador. Para esto, buscar powershell, botón derecho y "abrir como administrador" o "run as adminsitrator".
3. Ahí si escribir "WSL"
4. Escribir `jupyter notebook`

Si eso no funciona, mandanos una foto de todo lo que te sale cuando haces `python3 -m pip install notebook` para ver si entre dicho log hay algo que falló.

Quedamos atentos,

**Comment by bgonzp** [comment]
Ahi logre hacerlo, pero para lograrlo fue necesario poner jupyter notebook --allow-root. Ademas no me sale en jupyter vacio hay un par de archivos.
![Uploading Captura de pantalla 2023-08-16 151235.png…]()

**Comment by Hernan4444** [comment]
Hola @bgonzp 

Recuerda que en las reglas del foro se indica que no cierren las issues, esto lo haremos nosotros c: 

ps: por otro lado, no se ve la imagen 😞  pero me imagino que no sale vacío porque WSL por defecto ya tiene algunos archivos y carpetas creadas dentro de ella.

Saludos!
