### ISSUE TITLE
Archivos .csv en repositorio personal

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#19]
Tengo que subir los archivos .csv entregados nuevamente a mi repositorio personal? esto con el fin de que al ejecutar el programa los archivos sean buscados en la misma carpeta.

**Comment by jeschuwirth** [comment]
Hola @tedroppelmann,

No es necesario que subas los archivos entregados al repositorio. Puedes evitar que estos se suban sin sacarlos de la carpeta en la que estas trabajando haciendo uso del archivo .gitignore, ese archivo está explicado en la sección .gitignore del enunciado.

El uso correcto de .gitignore será evaluado para las siguientes tareas, por lo que te recomiendo aprender a usarlo desde ahora. Si tienes dudas acerca de como funciona puedes seguir comentado en esta issue :)

Suerte!

**Comment by tedroppelmann** [comment]
Pero al momento que ustedes evalúen el programa, donde estarán los archivos .csv que ocuparán? mi duda es respecto a si tengo que hacer una ruta más especifica para encontrar dichos archivos en el programa. o asumo que están en la misma carpeta?

**Comment by jeschuwirth** [comment]
Puedes asumir que van a estar en el mismo lugar que se les entregaron, es decir en la carpeta T00.

De todos modos puedes dejar detallado en tu README que esos archivos van en otra parte, por ejemplo una nueva carpeta data.
