### ISSUE TITLE
Duda sobre __init__ en subclases

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2233/syllabus#19]
En los apuntes del curso, me encontré con este fragmento de código:
```python
class FurgonEscolar(Auto):
    """Subclase de Auto"""
    
    # Estamos haciendo overriding del __init__ original
    def __init__(self, marca, modelo, motor):
        # Usamos el __init__ original para setear los otros datos. Así es como podemos llamarlo con super().
        super().__init__(marca, modelo, motor)
        self.ninos = []
    
    # inscribir_nino es un método específico de esta subclase.
    def inscribir_nino(self, nino):
        self.ninos.append(nino)
        
    # Estamos haciendo overriding del método conducir original
    def conducir(self, distancia):
        # Acá no queremos usar la versión original de conducir
        print(f"Conduciendo con cuidado {distancia} kilómetros")
```
Mi duda es, cuando se inicializa la clase FurgonEscolar se llama al inicializador de la superclase. Como es que, al llamar esa función, la subclase (en este caso FurgonEscolar) hereda los atributos de la superclase (en este caso, Auto (no se muestra aqui))

**Comment by ariel-m-s** [comment]
Hola @JJJGGGG!

Para responder tu duda es necesario que, en primer lugar, comprendas qué significa el argumento ```self``` que le pasamos al método ```init``` de las instancias. Este argumento, como dice su nombre, corresponde a la instancia en sí con la que estamos trabajando. En _Python_, este es entregado de manera implícita.

Pensemos en el siguiente ejemplo:

```python
class Persona:
    def __init__(self1, nombre):
        self1.nombre = nombre


class Estudiante(Persona):
    def __init__(self2, nombre, promedio):
        super().__init__(nombre)
        self2.promedio = promedio


juan = Estudiante("Juan", 6)
```

Si bien el código que se está ejecutando al llamar al método ```super().__init__``` es el de la super-clase sugerida por el [MRO](https://medium.com/technology-nineleaps/python-method-resolution-order-4fd41d2fcc) (que en este caso es la clase ```Persona```), la instancia que se le está pasando como parámetro ```self``` es la de la clase desde la que se llamó (que en este caso sería una instancia de la clase ```Estudiante```).

La manera correcta de verlo sería que ```super().__init__``` recibe tres argumentos: la instancia ```juan```, el string ```"Juan"``` y el entero ```6```. Por lo tanto, al ejecutarse la sentencia ```self.nombre = nombre``` de la clase ```Persona```, lo que estaría sucediendo es que ```self``` sería igual a la instancia ```juan```, por lo que, en realidad, la sentencia sería semánticamente equivalente a decir ```juan.nombre = "Juan"```.

Saludos.
