### ISSUE TITLE
Sobre git status y la subida de contenidos en general

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#19]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Git status para los contenidos
Cloné la carpeta de contenidos del [GitHub oficial](https://github.com/IIC2233/contenidos) en mi PC antes de que los contenidos de la semana 00 y 01 fueran subidos. Mi duda es, ¿por qué al hacer un git status no me avisó del cambio (la subida de los archivos), pero sin embargo al ejecutar un pull, logré descargar los archivos?
![Duda1](https://user-images.githubusercontent.com/66154723/111924478-9039fb80-8a83-11eb-9a79-31c6c7639819.png)

### Contenidos en general

¿Siempre que se actualicen los contenidos, estos serán linkeados desde canvas?

### Sobre las Issues

¿Cómo le añadimos labels a las Issues, o esto lo manejan los ayudantes?

**Comment by fernandosmither** [comment]
Ps. Sé que en las reglas habla sobre no hacer multiples preguntas en una Issue, pero puse la 1 y la 2 ya que están relacionadas, y la tercera pensé que es muy corta como para un Issue separado

**Comment by Sofia-Arratia** [comment]
Hola! 
Respecto a tu primera pregunta, "git status" solo reporta cambios locales en los repositorios, es decir, cuando se cambia algo desde el computador en el cual se encuentran almacenados, por lo que los cambios realizados en github (online) no serán reportados.
Respecto a la segunda, todos los contenidos serán avisados por Canvas cada semana junto a su link correspondiente.
Finalmente, las labels son colocadas exclusivamente por lxs profesores y ayudantes, por lo que no deberás preocuparte por eso.
Espero haber aclarado todo ☺️

**Comment by fernandosmither** [comment]
> Hola!
> Respecto a tu primera pregunta, "git status" solo reporta cambios locales en los repositorios, es decir, cuando se cambia algo desde el computador en el cual se encuentran almacenados, por lo que los cambios realizados en github (online) no serán reportados.
> Respecto a la segunda, todos los contenidos serán avisados por Canvas cada semana junto a su link correspondiente.
> Finalmente, las labels son colocadas exclusivamente por lxs profesores y ayudantes, por lo que no deberás preocuparte por eso.
> Espero haber aclarado todo ☺️

Muchas gracias por la respuesta!, ahora ¿cómo puedo revisar los cambios hechos en linea, respecto a mi versión local?, y en base a lo mismo, ¿Qué sucede si se hace un cambio via web, y sin darme cuenta subo una versión nueva? ¿Te avisa Git o solo llega y reemplaza?

**Comment by Sofia-Arratia** [comment]
Los cambios hechos en linea tendrás que ir revisándolos mediante Canvas, donde también se envían avisos/notificaciónes en caso de que se suba algo al syllabus o a los contenidos (a excepción de las actividades, que se subirán en su horario determinado). Por otro lado, y si entendí bien tu duda, el sistema te deja modificar solo tu repositorio personal, por lo que si accidentalmente haces _push_ de un archivo tuyo al syllabus o a los contenidos, simplemente se te denegará el acceso y lo más probable es que te salga un error.
Espero haber respondido tu duda c:

**Comment by fernandosmither** [comment]
### @Sofia-Arratia Gracias por tu respuesta. ¿Y qué sucede por ejemplo en un repositorio mío?

Si en un repositorio mío modifico algo vía web, o en otra plataforma, u otra persona que está programando conmigo hace push, ¿cómo verifico la versión actual local versus la actual en github?

Y lo otro, de no verificarlo, digamos que mi compañero modificó algo en el archivo "main.py". Si yo subo otro, me avisará git que estuve trabajando en algo desactualizado o llegará y lo reemplazará?
y de ser así, cómo evito que me suceda? buenas prácticas o algunos comandos que no conozco?🤔

Saludos 😁

**Comment by Sofia-Arratia** [comment]
Para propósitos de este curso, donde el trabajo es 100% individual, realmente no es necesario que conozcas la respuesta a estas preguntas, ya que nadie más que tú estará modificando tu repositorio. Sin embargo, y dada tu curiosidad, la organización de trabajos en equipos de múltiples personas a través de github puede ser organizado mediante el uso de _[ramas]_(https://docs.github.com/es/github/collaborating-with-issues-and-pull-requests/about-branches) o _branches_ , las cuales usamos como ayudantes para trabajar en las actividades, tareas y ayudantías del curso. Dado que es contenido externo al curso, te invito a hacer tu propia búsqueda de información sobre el tema, o incluso volverte parte del cuerpo de ayudantes el próximo semestre para aprender sobre esto ☺️

**Comment by fernandosmither** [comment]
> Para propósitos de este curso, donde el trabajo es 100% individual, realmente no es necesario que conozcas la respuesta a estas preguntas, ya que nadie más que tú estará modificando tu repositorio. Sin embargo, y dada tu curiosidad, la organización de trabajos en equipos de múltiples personas a través de github puede ser realizada mediante el uso de _[ramas](https://docs.github.com/es/github/collaborating-with-issues-and-pull-requests/about-branches)_ o _branches_ , las cuales usamos como ayudantes para trabajar en las actividades, tareas y ayudantías del curso. Dado que es contenido externo al curso, te invito a hacer tu propia búsqueda de información sobre el tema, o incluso volverte parte del cuerpo de ayudantes el próximo semestre para aprender sobre esto ☺️

Will do, gracias! 😀
