### ISSUE TITLE
Mejorando la impresión de los strings

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#19]
Hola!

No me quedo muy claro el uso de las herramientas para mejorar la impresión de los strings. Dónde podría verlo más en detalle?

Gracias  :)

**Comment by Juampisaez** [comment]
Holaa, me queda un poco la duda de a que te refieres con "mejorar la impresion de los strings". VSCode es una buena herramienta para poder trabajar durante el curso y poder ir verificando si tu codigo va funcionando o posee errores. A la vez, esta herramienta posee algunas extensiones para mejorar la visualización de tus outputs sin necesidad de usar directamente la consola, una extension para esto es "Code runner". También debes tener instalada la extension "Python" para que todo esto funcione.
Espero haber contestado a tu pregunta, quedo atento igualmente.

**Comment by amahns1** [comment]
Holaa, me refiero a la última parte del contenido de strings. Al final se muestran aplicaciones de los "f" strings que permiten centrar el outpout de la consola. No me queda claro cómo funcionan.

Graciaas.

**Comment by Juampisaez** [comment]
Perfecto, si te fijaste en los contenidos existen dos formas para poder estandarizar los strings. Una es con el .format y la segunda es la que mencionas con el f"". Ambas apuntan hacia lo mismo, poder editar la forma en que se producen las salidas en la consola. 
Un ejemplo para el f"" puede ser: 
```
name = "programación avanzada"
string = f"He tomado el ramo {name}"
print(string)
```
En este caso *name* corresponde a una variable definida anteriormente, de esta manera, el *string* depende del valor que tome *name* en el tiempo, es decir el valor de la variable que se encuentre dentro de las llaves {}.
El codigo anterior retornaria:
`He tomado el ramo programación avanzada`
En lo personal creo que el uso del f"" es mejor para cumplir el PEP8, simplica la cantidad de caracteres comparado con el uso de .format. Tambien permite agregarle caracteristicas a las variables en los strings, como por ejemplo ^9d (que aparece en los contenidos)
En cuanto al .format, te dejo un breve ejemplo en este [link](https://www.w3schools.com/python/ref_string_format.asp)

Espero que te sirva, cualquier cosa quedo atento.
