### ISSUE TITLE
Sacar un archivo del repositorio

### ISSUE THREAD

**Issue by cristozille** [IIC2233/syllabus#19]
Hola, subí un archivo al repositorio de GitHub por accidente, como lo puedo eliminar?

**Comment by KnowYourselves** [comment]
Hola @cristozille!

Para esto puedes utilizar el commando `git rm <nombre_archivo>`. Por ejemplo, si subiste un archivo `test.txt` debes hacer los siguientes comandos:

1. `git rm test.txt`
3. `git commit -m"algun mensaje cualquiera"`
4. `git push`

Debes hacer `commit` y `push` porque eliminar un archivo es un cambio como cualquier otro a ojos de git. 

**OJO**: `git rm` también eliminará el archivo de tu computador. Si quieres eliminar el archivo de tu repo, pero no de tu computador, debes agregar la opción `--cached` al primer comando, de la forma:

`git rm test.txt --cached` 

Espero haberte ayudado!
