### ISSUE TITLE
Problema al cargar archivo

### ISSUE THREAD

**Issue by domja** [IIC2233/syllabus#190]
Hola! Al cargar posts.csv asi:
with open('posts.csv', 'r') as file:
        for line in file.readlines():
no se porque los 'line' repiten la fecha que sale en la linea, por ejemplo si pongo print(line) me da:
MatiasDuhald3,2020/02/17,2020/02/17, you need a good imagination and a pile of junk.” – Thomas Edison
y como repite la fecha me mata todo el codigo.
Saben porque puede ser?

**Comment by jeschuwirth** [comment]
Hola!

Si estas usando los .csv más nuevos, estos están comprobados que no tienen ninguna fecha repetida, por lo tanto el error debe estar en tus líneas en modo write `with open('posts.csv', 'w')`. 

Revisa esas lineas y asegúrate que no estés agregando dos veces la fecha ahí.

Me avisas!

**Comment by domja** [comment]
No creo que la este agregando en el write!! Porque el problema sale justo despues de que abro el archivo!! Lo unico que hago es abrirlo y su imprimo ese 'line' ya viene la fecha repetida y no tengo idea porque.
    with open('posts.csv', 'r') as file:
        for line in file.readlines():
            print(line)

**Comment by jeschuwirth** [comment]
Me disculpo, no me expliqué correctamente:

Revisa los archivos .csv a mano y asegúrate que no tengan la fecha escrita 2 veces, si si la tienen escritas 2 veces, entonces el problema está en tus líneas `with open('posts.csv', 'w')` ya que estas guardaron la fecha 2 veces.

Si las fechas no están 2 veces en el .csv avisa :)
