### ISSUE TITLE
Duda sobre Luchar 

### ISSUE THREAD

**Issue by rodridelafuente** [IIC2233/Syllabus#190]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! En la parte de ```Luchar``` de la sección ```Programón``` en el enunciado, no me queda claro si solo debo calcular el *puntaje de victoria* o también debo compararlo con el del rival en ese mismo método. Personalmente, se me hace más cómodo calcular solamente el *puntaje de victoria* en ```Luchar``` y compararlo con el del rival en otra parte del código, entonces ¿podría hacerlo de esa forma y dejarlo explicado en mi README?

**Comment by Amandasandov** [comment]
Hola, en el método solo es necesario calcular el puntaje de victoria del programón, donde hacer la comparación queda a tu criterio. Suerte.
