### ISSUE TITLE
Paises - Population

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#190]
tengo mis dudas de si son los mismos paises porque a pesar de que se llamen igual, las mayusculas son distintas y sus poblaciones tambien
United Arab Emirates 137829862    United arab emirates 80715765

entonces que deberia hacer, contarlos como iguales y escoger una poblacion cualquiera o decir que son dos paises distintos y hacer las conecciones de cada uno?

**Comment by stephichau** [comment]
@Dunkan1 Ya se arreglaron los archivos :).
