### ISSUE TITLE
WSL: no me deja acceder contraseña

### ISSUE THREAD

**Issue by BenjaMedinaPUC** [IIC2233/Syllabus#190]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

Hola! esperando que se encuentren bien el día de doy, escribo para saber si es normal que no me salga nada en la pantalla cuando estoy escribiendo la contraseña en la consola de wsl (adjunto imagen) y me parece raro ya que issues anteriores pregunté de como re instalar correctamente y había anotado mis credenciales correctamente pero no me sale ningún asterisco ni tampoco me acepta la contraseña
¿Influye en la revisión de la tarea? porque hacer ls comandos git(git pull, git push, entre otros) me deja pero como entrar por consola a la tarea no me esta dejando
estaré atento a su respuesta
![image](https://github.com/IIC2233/Syllabus/assets/111039575/d6251322-f00a-4e6a-be7f-9c8e0db6ad67)

**Comment by gatochico** [comment]
Hola! @BenjaMedinaPUC 
Sobre tus dudas:
El comando "python" te dice `command not found` ya que en WSL para correr python debes hacer `python3` y `python3.10`, no `python` a secas. En caso de querer ejecutar un programa debería ser `python3 main.py` (reemplazar la segunda palabra por el nombre de archivo a ejecutar).

Para tu segunda pregunta, es normal que al escribir contraseña en WSL no aparezca nada: sí se está escribiendo, solo que en Linux por seguridad no te muestra nada, ni siquiera asteriscos (piensa en que se está escribiendo, pero en color transparente). Entonces cuando te pida contraseña tu solo la ingresas (aunque no se vea nada) y haces enter, y funcionará.

Saludos
