### ISSUE TITLE
Readme y Diagrama de Clases

### ISSUE THREAD

**Issue by TriniAguilera** [IIC2233/Syllabus#190]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Quería saber si el detalle de los atributos, métodos, clases abstractas, properties y todo eso puedo detallarlo en el archivo de Markdown del diagrama de clases y no en el Readme principal. En este último detallo sobre el flujo del programa, modularización, bonus y esas cosas. Pregunto esto porque sino siento que va a quedar muy denso y desordenado el Readme principal.

También quiero saber si hay algún problema con crear una carpeta dentro de la carpeta T1 que contenga la imagen del Diagrama de Clases y su respectivo documento explicativo.

**Comment by matiasmasjuan** [comment]
Hola @TriniAguilera : 

**Si**, todo lo relacionado al detalle de las clases puede ir especificado en el diagrama de clases y **no es necesario** que lo especifiques en el *Readme.md*. Tal como dices, el objetivo del *Readme* es especificar temas de flujo, modularización, aspectos implementados y no implementados, además de cualquier supuesto realizado y citas de código externo. Sobre lo segundo, **sí**, puedes crear una carpeta dentro de la T1 que contenga tanto la imagen como la explicación del diagrama. Recuerda especificar en el *Readme* su ubicación y el nombre de la carpeta.

Saludos!
