### ISSUE TITLE
Nombre nuevo usuario

### ISSUE THREAD

**Issue by Pdesolmi** [IIC2233/syllabus#190]
Cuando creo un nuevo usuario, es necesario que su nombre no se encuentre dentro de los contrincantes o sólo reviso los pilotos ya creados?

**Comment by jeschuwirth** [comment]
Hola,

Eso no está explicado en el enunciado, por lo tanto queda a tu criterio siempre y cuando lo escribas en el readme :)

Personalmente revisaría ambos archivos, pero si quieres hacerlo de otra manera no hay problema.

Suerte!
