### ISSUE TITLE
UnboundLocalError: local variable 'variable' referenced before assignment

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2233/syllabus#190]
Hola! estoy teniendo un problema con mi código, mi "variable" es la del ataque regular de la cpu, una funcion. Y resulta que antes me funcionaba perfecto, mi oponente interactuaba bien conmigo.
Ahora desde que hice unos cambios ya no me funciona esto, mi problema es que no se en que momento dejo de funcionar.
Mi funcion tiene 3 parametros, el error se da necesariamente por la funcion? o puede ser tambien por los parametros?

Muchas gracias de antemano.

**Comment by danckoo1** [comment]
Hola, el error explicado de forma simple es que estás utilizando alguna variable local antes de crearla. En este caso el error te dice que la variable problemática se llama ‘variable’; de esto me surge una duda, tú mencionas qué variable es en realidad una función, por lo que quizás en alguna parte de tu código tienes un error de tipeo y en vez de llamar a la función como variable() olvidaste los paréntesis y el intérprete lo lee como una variable, avísame si entendí algo mal!

**Comment by pabloalvarez67** [comment]
> Hola, el error explicado de forma simple es que estás utilizando alguna variable local antes de crearla. En este caso el error te dice que la variable problemática se llama ‘variable’; de esto me surge una duda, tú mencionas qué variable es en realidad una función, por lo que quizás en alguna parte de tu código tienes un error de tipeo y en vez de llamar a la función como variable() olvidaste los paréntesis y el intérprete lo lee como una variable, avísame si entendí algo mal!

Nunca estuve seguro de cual fue el error, pero elimine esa función y lo meti mas manual en el código, que me quedo un poco más feo pero al menos funciona. Gracias igual!
