### ISSUE TITLE
Sobre dataTypes

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#190]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Sobre los dataTypes, tengo la siguiente 'cheat-sheet', que creo que proyectaron luego de una revisión de la actividad.
![image](https://user-images.githubusercontent.com/66154723/113653175-5102d180-9663-11eb-97cd-b05ac60aee0f.png)

Es cierto que me ha ayudado mucho al principio en conceptos básicos como para saber en cual se puede insertar o no, lo que siento que no ayuda es el tema de la velocidad computacional,  ya que por ejemplo todas tienen 1 tick en búsqueda por valor, sin embargo todavía no sé bien, en un caso hipotético donde tengo un array de datos (que no se repiten), cuál es el datatype más rápido para ver si cierto valor existe o no.

Aparte de ese caso hipotético, me preguntaba si tenían alguna otra 'cheat-sheet' que sea más completa para este tipo de preguntas. Muchas gracias

**Comment by cruz** [comment]
Más que un _cheat sheet_, es como una referencia rápida de qué estructura (de las básicas) es mejor para qué operación.

La idea de "buscar por valor" es "dado un valor, ver si se encuentra en la estructura". En ese sentido, todas requieren mirar todos los elementos, así que el _tick_ más bien indica "sí, se puede hacer", mientras que los tres _ticks_ intentan decir "se puede hacer y muy rápido".

Dicho eso, es discutible el caso del _set_. Técnicamente un _set_ es como un diccionario pero solamente con llaves, así que si quieres buscar un valor, en verdad estás buscando una llave, lo que es **muy** eficiente. Podríamos pensar que es más preciso decir que en ese caso "no aplica", ya que los valores son llaves (o derechamente decir que la búsqueda es muy eficiente ya que en verdad estamos haciendo una búsqueda por llave), pero debemos también considerar que podemos querer buscar dentro de un conjunto de valores _no-hasheables_. Supón que tenemos una estructura que contiene listas, y queremos buscar si una lista particular se encuentra entre ellas. No podemos poner listas en un _set_ porque no son _hasheables_, así que tendríamos que usar alguna otra estructura en que estaremos obligados a mirar cada lista, una a una, para ver si es igual a la que buscamos. En ese caso, más general, ninguna de estas estructuras es particularmente eficiente.

Tampoco hay que darse por vencido, eso sí. Hay estructuras más complejas que se pueden construir (más adelante veremos árboles y grafos) donde podemos introducir los datos de manera que podamos encontrar varios tipos de elementos en tiempos más acotados. Eso sí, son estructuras bastante genéricas y no profundizaremos mucho en casos más específicos de búsquedas eficientes en árboles o grafos, pero en el curso _**Estructuras de Datos**_ sí los verán más en detalle.

Espero haberte ayudado :)

**Comment by fernandosmither** [comment]
> Más que un _cheat sheet_, es como una referencia rápida de qué estructura (de las básicas) es mejor para qué operación.
> 
> La idea de "buscar por valor" es "dado un valor, ver si se encuentra en la estructura". En ese sentido, todas requieren mirar todos los elementos, así que el _tick_ más bien indica "sí, se puede hacer", mientras que los tres _ticks_ intentan decir "se puede hacer y muy rápido".
> 
> Dicho eso, es discutible el caso del _set_. Técnicamente un _set_ es como un diccionario pero solamente con llaves, así que si quieres buscar un valor, en verdad estás buscando una llave, lo que es **muy** eficiente. Podríamos pensar que es más preciso decir que en ese caso "no aplica", ya que los valores son llaves (o derechamente decir que la búsqueda es muy eficiente ya que en verdad estamos haciendo una búsqueda por llave), pero debemos también considerar que podemos querer buscar dentro de un conjunto de valores _no-hasheables_. Supón que tenemos una estructura que contiene listas, y queremos buscar si una lista particular se encuentra entre ellas. No podemos poner listas en un _set_ porque no son _hasheables_, así que tendríamos que usar alguna otra estructura en que estaremos obligados a mirar cada lista, una a una, para ver si es igual a la que buscamos. En ese caso, más general, ninguna de estas estructuras es particularmente eficiente.
> 
> Tampoco hay que darse por vencido, eso sí. Hay estructuras más complejas que se pueden construir (más adelante veremos árboles y grafos) donde podemos introducir los datos de manera que podamos encontrar varios tipos de elementos en tiempos más acotados. Eso sí, son estructuras bastante genéricas y no profundizaremos mucho en casos más específicos de búsquedas eficientes en árboles o grafos, pero en el curso _**Estructuras de Datos**_ sí los verán más en detalle.
> 
> Espero haberte ayudado :)

Me ha quedado clarísimo!, Gracias @cruz
