### ISSUE TITLE
Visualizador archivos .ipynb

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#190]
Hola
Quería saber si existe algún programa para leer los archivos .ipynb (no modificar) en windows o si pueden subir el material de las clases también en formato pdf.
Gracias~

**Comment by IchottMano** [comment]
@jmwielandt Hola!
Te recomiendo que leas [esta guía](http://jupyter.readthedocs.io/en/latest/install.html) donde se muestra como instalar jupyter, una herramienta muy útil para visualizar, modificar y correr código de un ipynb!
Eso si, recomiendo **fuertemente** que lo instales usando *pip*, ya que mucha gente tiene problemas al instalar anaconda en su compitador.
Saludos!
