### ISSUE TITLE
PEP8 revisión

### ISSUE THREAD

**Issue by jtvvtj** [IIC2233/Syllabus#190]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Existe alguna forma de revisar si todo mi código cumple con PEP8 según el PEP8 que se usa en el ramo (es decir, como por ejemplo, 100 máximo de caracteres, en vez de 80). O esto se hace de forma manual?

**Comment by ignacio-sp** [comment]
Hola @jtvvtj, una forma fácil de revisar el largo de líneas es agregando una regla vertical en el lugar donde se alcanzan los 100 caracteres, en [este video](https://youtube.com/shorts/cTE0ec3IurE?si=D3tfd5TeFBUVS-3L) se muestra brevemente como configurarlo, así puedes revisar fácilmente qué líneas están cerca del límite pedido, personalmente lo encuentro bastante cómodo de utilizar.

Espero resulte útil, estoy atento!

**Comment by jtvvtj** [comment]
Entiendo muchaaaas gracias por la recomendaciooon :), sí me fue utiiil
