### ISSUE TITLE
Material AC04, "if nodo"

### ISSUE THREAD

**Issue by fabarros** [IIC2233/Syllabus#190]
Hola, tengo una duda en la In [27] del material de la semana 4. 
Dentro de la clase Arbol hay una función que se llama "obtener_nodo" y al final hay un "if nodo:".
No entiendo qué es "nodo", según yo es una instancia de la Clase Arbol pero ahí se usa como un booleano :s 
Alguien me puede explicar esa función?

**Comment by fringlesinthestreet** [comment]
@fabarros Este método es utilizado por la clase ```Arbol``` para recorrer todos sus nodos y comparar sus atributos ```id_nodo``` con el buscado. La idea de hacer ```if nodo:``` es ver si la variable nodo no es ```None```.

En cada nodo se realiza lo siguiente:
- Primero, se verifica si el nodo actual es el buscado, comparando su ```id_nodo``` con el entregado como argumento. Si es ese el nodo, se retorna, si no, continúa.
- Si el nodo actual no es el buscado, se comienza a buscar en sus hijos, iterando sobre ellos. Si uno de ellos llega a ser el nodo buscado, entonces el llamado a 
```nodo = hijo.obtener_nodo(id_nodo)```
retornó un nodo válido por lo que la sentencia ```if nodo:``` va a ser ```True```, y, por esto, se retornará ese nodo. 
Si ninguno de sus hijos encontró al nodo, entonces todos esos llamados retornaron ```None``` por lo que la sentencia ```if nodo:``` siempre fue ```False```. Dado lo anterior, se termina de iterar sobre los hijos y como "no se retorna nada" se termina retornando ```None``` (se retorna ```None``` por defecto en las funciones).

**Comment by indonoso** [comment]
Los objetos de python se pueden parsear a booleanos (hay excepciones en algunas librerías) y siempre tendrán el valor `True`. Si una variable no apunta a ningún objeto, es decir, tiene como valor `None` el parseo transforma el `None` en `False`.

**Comment by fabarros** [comment]
Clarísimo :) muchas gracias.
