### ISSUE TITLE
Duda método Presentarse en Combatiente y Ejército.

### ISSUE THREAD

**Issue by Vicente1824** [IIC2233/Syllabus#191]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Sobre el método ```presentarse()``` en Combatiente, el enunciado dice:
```Imprime en consola un string que presente el nombre del combatiente, su tipo, vida máxima, vida actual, ataque y defensa. Este método debe implementarse sobreescribiendo el método __str__ de la clase```
No entiendo muy bien a qué se refiere con sobreescribir el método ```__str__```. Quiere decir que debería hacer algo como lo siguiente?
```py
Class Combatiente:
    def __str__(self):
        return "datos combatiente: bla bla bla"
        
    def presentarse(self):
        print(self)
```
¿O que directamente ```presentarse()``` haga ```print("datos combatiente: bla bla bla")```?

**Comment by Benjeeeh** [comment]
Hola!
Exactamente, no debes crear un metodo presentarse(), si no que esos datos de presentación deben estar incluido dentro de __str__, de modo de que al hacer print sobre la clase arroje esta información.

Mucho éxito!

**Comment by Vicente1824** [comment]
¡Ya, muchas gracias!
