### ISSUE TITLE
PyQt6 instalado correctamente pero sin poder importar modulos: libQt6Core.so.6

### ISSUE THREAD

**Issue by joacopython** [IIC2233/Syllabus#191]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### problema
instale correctamente PyQt6 en ubuntu, sin embargo al intentar importarlo me aparece este error 
![image](https://github.com/IIC2233/Syllabus/assets/141943350/a1cfd324-9f20-4b4f-a4cc-c372cbd4b320)
Luego probe este comando 
![image](https://github.com/IIC2233/Syllabus/assets/141943350/0de3f2d9-04d4-4830-a159-48aa115f2a75)
pero no se logró correctamente la instalación dando este error como resultado 
![image](https://github.com/IIC2233/Syllabus/assets/141943350/141e9648-fc86-4338-9a37-351fff74bb56)
y al volver a intentar ejecutar el primero codigo seguía apareciendo el mismo error

**Comment by Hernan4444** [comment]
Hola @joacopython 

Si es que la instalación no se pudo efectuar, entonces primero vamos a tener que solucionar eso. Por el momento, intentemos con lo que el mismo mensaje recomendado en la foto:

`sudo apt-get update`

Si ese comando no funciona, recomiendo revisar esta [página](https://futurestud.io/tutorials/how-to-fix-ubuntu-debian-apt-get-404-not-found-repository-errors) que explican que es necesario actualizar ubuntu o ciertos archivos para poder hacer funcionar el comando para instalar cosas (`apt install` o `apt-get install`).

Una vez que logremos instalar los elementos de ese comando gigante (`sudo apt install libqt6multimedia6 libpulse0 python3-pyqt5 libxcb-cursor-dev`). Ahí veremos qué pasó con pyqt6.

Avísa en este misma issue cómo te va con esta solución.
Saludos!

**Comment by joacopython** [comment]
Hola profesor.
La solucion me sirvio, ahora si me dejó instalar este comando "sudo apt install libqt6multimedia6 libpulse0 python3-pyqt5 libxcb-cursor-dev". pero aun no me reconoce la otra libreria 
![image](https://github.com/IIC2233/Syllabus/assets/141943350/1eeb3598-d60d-4966-aec1-083da7f36cdf)

**Comment by Jeremiah-PHP6** [comment]
> sudo apt install libqt6multimedia6 libpulse0 python3-pyqt5 libxcb-cursor-dev

Tenía el mismo problema y se solucionó con el comando. Gracias profesor.
