### ISSUE TITLE
Estados del chasis

### ISSUE THREAD

**Issue by DonJavi-538** [IIC2233/syllabus#191]
Cuál es la diferencia entre "durabilidad_maxima_chasis" , "durabilidad_inicial_chasis" y "durabilidad_actual_chasis"?

**Comment by jeschuwirth** [comment]
Hola,

Revisé el enunciado por tu issue y llegue a la siguiente conclusión, en la fórmula **Tiempo en los pits**

![image](https://user-images.githubusercontent.com/37160256/64481211-5f49ec80-d1a5-11e9-8869-d9af55d1dcb5.png)

La durabilidad actual es la durabilidad que tenía el chasis a la hora de entrar a los pits, es decir la durbilidad máxima- la que perdió por accidente en la carrera y la durabilidad inicial es la máxima que tiene el chasis actualmente, o sea incluyendo todas las mejoras que tiene.


En la fórmula **accidentes durante las vueltas**:
![image](https://user-images.githubusercontent.com/37160256/64481219-aa63ff80-d1a5-11e9-8dda-cdff8debad25.png)

Se habla de durabilidad máxima, esta es la misma que la durabilidad inicial en la primera fórmula, es decir, la vida 'máxima' que tiene el vehículo

Ojalá haya quedado claro, cualquier duda sigue preguntando en la issue :)

Suerte!

**Comment by Jprampad** [comment]
Hola! 
Qué sucedería si mejoro mi chasis, generando uno mejor que el que tenía anteriormente, ahí mi vida 'máxima' cambiaría, no es así?
