### ISSUE TITLE
Material del curso, errores de escritura

### ISSUE THREAD

**Issue by jadiaz6** [IIC2233/Syllabus#191]
Hola, he notado que en casi todas las guías de contenidos hay errores ortográficos o de redacción. Si bien se entienden de todas maneras, estos dificultan el entendimiento de la lección, haciendo que uno avance más lento.

Es solo una sugerencia, para que tengan presente esta falla.

Saludos.

**Comment by andresfdezc** [comment]
Gracias por sugerirlo. Lo tenemos presente y estamos tratando de mejorar el material lo más que podamos. Lo revisaremos de nuevo para que sea más entendible.
