### ISSUE TITLE
Ejercicio 1.2 GrandPrix - Semana 3

### ISSUE THREAD

**Issue by alvarocisternas** [IIC2233/syllabus#191]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

No estoy entendiendo bien como crear la clase MonsterTruck que hereda de Camion y AutoRally.

si al crearla escribo:
** class MonsterTruck(Camion, AutoRally) **
después va un init con todos los atributos de MonsterTruck y luego cómo realizo el método super() si hereda de dos clases??

**Comment by alvarocisternas** [comment]
ya lo solucioné :) con **kwargs

**Comment by riadeane** [comment]
Hola @alvarocisternas! 🤗

Aunque lo hayas solucionado, creo que es bueno explicar todo :)

Si viéramos el  `__mro__` de `MonsterTruck(Camion, AutoRally)` para ver el orden de herencia, se imprimiría lo siguiente:
`(__main__.MonsterTruck, __main__.Camion, __main__.AutoRally, __main__.Vehiculo, object)`. El uso del método `super()` nos permite hacer la herencia en este orden lineal. Al llamar `super().__init__()` de `MonsterTruck`, por el orden de herencia se llamaría al `__init__()` de `Camion`. Luego, si tenemos `super().__init__()` en el inicializador de `Camion` (que deberíamos, dado que hereda de `Vehiculo`), por MRO se llamaría al inicializador de `AutoRally`. Finalmente, en esta clase, con `super().__init__()` en su inicializador se hace el llamado a `Vehiculo`.

Sin embargo, tal como planteas, entramos a un problema con los argumentos para los inicializadores de las superclases. No podemos poner, por ejemplo, 3 argumentos en el `super().__init__()` de `MonsterTruck` si `__init__()` de `Camion` solo recibe 2 argumentos. La mejor forma de resolucion a este problema es utilizar `**kwargs`. ¿Qué eran los `kwargs`? Son secuencias de argumentos de largo variable, donde cada elemento de la lista tiene asociado un _keyword_  (como una llave y su valor en un diccionario). Esto significa que los argumentos no se asignan a la función por su posición en el orden en que se entregan (como es lo habitual) sino por su _keyword_ asociado.

Entonces, si en ves de definir los argumentos de `MonsterTruck` y sus superclases como argumentos posicionales, los definimos como argumentos tipo _keyword_, podemos pasarle los `**kwargs` a cada `super().__init__()` y las superclases irán utilizando los argumentos que les corresponden por su _keyword_ y le dejaran los restantes a  la superclase que sigue.

Un muy buen ejemplo de como funciona se encuentra en los contenidos:
```
class Investigador:

    def __init__(self, area='', **kwargs):
        print(f"init Investigador con area {area} y kwargs:{kwargs}")
        super().__init__(**kwargs)
        self.area = area
        self.num_publicaciones = 0


class Docente:

    def __init__(self, departamento='', **kwargs):
        print(f"init Docente con depto {departamento} y kwargs:{kwargs}")
        super().__init__(**kwargs)
        self.departamento = departamento
        self.num_cursos = 3


class Academico(Docente, Investigador):

    def __init__(self, nombre, oficina, **kwargs):
        print(f"init Academico con nombre {nombre}, oficina {oficina}, kwargs:{kwargs}")
        super().__init__(**kwargs)
        self.nombre = nombre
        self.oficina = oficina

print(Academico.__mro__)
p1 = Academico("Emilia Donoso", oficina="O5", area="Inteligencia de Máquina", departamento="Ciencia De La Computación")
print("--------")
print(p1.nombre)
print(p1.area)
print(p1.departamento)
```

```
(<class '__main__.Academico'>, <class '__main__.Docente'>, <class '__main__.Investigador'>, <class 'object'>)
init Academico con nombre Emilia Donoso, oficina O5, kwargs:{'area': 'Inteligencia de Máquina', 'departamento': 'Ciencia De La Computación'}
init Docente con depto Ciencia De La Computación y kwargs:{'area': 'Inteligencia de Máquina'}
init Investigador con area Inteligencia de Máquina y kwargs:{}
--------
Emilia Donoso
Inteligencia de Máquina
Ciencia De La Computación
```

En este caso, tenemos la clase `Academico`, que hereda tanto de `Docente` como `Investigador`. Podemos ver que al inicializar cada clase va utilizando los `kwargs` que les corresponden por el nombre del _keyword_, y todo lo restante entra a `super().__init__(**kwargs)`

Espero que con esto haya quedado mas claro, y que le sirva a alguien mas en caso de necesitarlo! 🌺

**Comment by alvarocisternas** [comment]
te pasaste! muchas gracias!
