### ISSUE TITLE
Como es el uso de QEvent?

### ISSUE THREAD

**Issue by Franbelen** [IIC2233/Syllabus#191]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola mi duda es con el uso de QEvent para esperar que algo pase ( de manera similar a threading.event) ya que al usarlo me dice que me falta parametros y leyendo no he podido entender cuales son los parametros que faltan, y al usar Event la ventana se queda cargando sin poder interactuar con esta.
Esto lo quiero usar para que se espere a que el jugador elija el planeta que quiere jugar para cargar las caracteristicas especificas de cada planeta (como el fondo, tipo de alien, etc)

**Comment by Emiliax16** [comment]
Hola @Franbelen ! efectivamente a QEvent se le debe entregarun parámetro, el cual corresponde al tipo de evento al que quieres que reaccione. Hay muchísimos tipos que podrían serte útil para la tarea, te dejo aquí su documentación para que entiendas a cabalidad su funcionamiento:

[https://doc.qt.io/qt-5/qevent.html](url)

saludos!
