### ISSUE TITLE
funcion lectora de simbolos

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#191]
Hay alguna funcion que pueda identificar si una palabra posee una letra? Algo asi como es string.isalpha()?

**Comment by aljara97** [comment]
Hola @dsepulveda3, no puedo decirte exactamente cuál método usar para esto. Sin embargo, te recomiendo revisar el siguiente [link](https://docs.python.org/3/library/stdtypes.html#string-methods)  con algunos métodos de string que se publicó en el enunciado.

Ánimo con lo que queda 🐦
