### ISSUE TITLE
Diagrama de Clases

### ISSUE THREAD

**Issue by pcsalvo** [IIC2233/Syllabus#191]
Hola!! Quisiera saber cuando abrirán el cuestionario para subir el diagrama de clases al siding, ya que el fin de semana no se si tenga internet, y me gustaría poder subirlo antes

**Comment by akaminetzkyp** [comment]
Los diagramas no se suben a GitHub?

**Comment by ranieto** [comment]
@akaminetzkyp para este caso no, revisa el punto 7.1 del enunciado.

**Comment by akaminetzkyp** [comment]
Ohh, no había visto eso. Gracias!

**Comment by flobarrios** [comment]
Ya está abierto el cuestionario!!

**Comment by pcsalvo** [comment]
@flobarrios Gracias!! :D
