### ISSUE TITLE
error con git commit 

### ISSUE THREAD

**Issue by rosario-frugone** [IIC2233/syllabus#191]
hola!! no me funciona el git commit, hice git add y git status y me sale que el archivo se modificó, pero cuando pongo git commit m- "puse mi nombre" (que es el mensaje que quería poner) terminal me dice esto:

error: pathspec 'm-' did not match any file(s) known to git.
error: pathspec 'Puse mi nombre' did not match any file(s) known to git.

ayudaaa

**Comment by josefinareyes** [comment]
Hola! El commit es ```git commit -m "explicacion"```, no m-, fíjate que estés poniendo el guión antes de la m!

**Comment by rosario-frugone** [comment]
gracias!!
