### ISSUE TITLE
Clase privada: "class __ClasePrivada:"

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#191]
Hola, tengo una clase con métodos y todo que necesito, pero no quiero que "el usuario" tenga acceso directo a instanciarla, como se hace con los double underscores para atributos y métodos dentro de una clase, **pero** necesito instanciarla dentro de otra clase. ¿Cómo es el _name mangling_ para esto?

**Comment by fringlesinthestreet** [comment]
Hola @jmwielandt 

Como ya debes saber, el Python no existe nada realmente privado. Para hacer esto, se hace una convención de utilizar un guión bajo antes del nombre del método o clase.

Por ende, para crear tu "clase privada", lo que debes hacer es simplemente utilizar un guión bajo antes del nombre que le pusiste. Ejemplo:

```python
class _InternalClass:
    pass
```

El _name mangling_ que tu hablas (doble guión bajo) se utiliza para evitar que cuando defines un atributo __no__ sobrescribas un atributo o _property_ de una superclase (o clase Padre). No se utiliza para prevenir acceso externo a los atributos o métodos, ya que igual se puede acceder de forma externa.

Si quieres saber más puedes ver [esto](https://stackoverflow.com/questions/7456807/python-name-mangling).
