### ISSUE TITLE
Definición Acciones "excavador"

### ISSUE THREAD

**Issue by Fopazov** [IIC2233/Syllabus#191]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo dudas sobre como definir las acciones de los excavadores. ¿La idea es que sean métodos que modifiquen las características de la instancia torneo? A mí por lo menos me resulta más intuitivo definirlas como properties y llamarlas en el caso que sea necesario. ¿Es posible hacer esto último o no está permitido?

**Comment by Rotopikus** [comment]
Hola!!!


En realidad depende de la modelación de tu programa. Pero debes tener en cuenta de que las properties son “propiedades” de un objeto que se basan en sus atributos, en cambio los métodos son “acciones” del objeto que podrían tener repercusión en alterar sus atributos. 

Es importante que analices en qué caso es más conveniente utilizar uno u otro, porque en teoría una property no debería cambiar un atributo de un objeto.


Espero haber aclarado tu duda. Éxito!!

**Comment by Fopazov** [comment]
Vale, graciasss! Se entiende.
