### ISSUE TITLE
C01

### ISSUE THREAD

**Issue by gtquiroga** [IIC2233/Syllabus#192]
Done se encuentran las notas del C01?

**Comment by ciquezada** [comment]
Perdon, pero yo tampoco se, ¿donde se encuentran?

**Comment by flobarrios** [comment]
Hola!  Están acá: https://docs.google.com/spreadsheets/d/1nauE6bSXYRD1OY0eoLIPTNqJju7zt48E3oh7lO8AH8Y/edit#gid=1120413644

Esta es la planilla donde iremos subiendo todas las notas del curso 😄

**Comment by fringlesinthestreet** [comment]
Hola @jpsiegel 

Los controles se encuentran disponibles en el casillero de Programación Avanzada. Este casillero está en el DCC (4to piso del edificio San Agustín). Si tienes dudas sobre cómo encontrar el casillero puedes preguntarle a Yessenia (la secretaria). 

Para poder recorregir, debes hacerlo a través del [formulario](https://docs.google.com/forms/d/1PCkmDKvMlt0bYGkBd386JtkCDntrDD_ZeBWr19y5640/edit) de recorrecciones. Tienen hasta el jueves 19 de Abril para hacerlo.
