### ISSUE TITLE
Dudas sobre properties

### ISSUE THREAD

**Issue by FVivess** [IIC2233/syllabus#192]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Tengo una duda sobre el uso de properties cuando ya se tiene un atributo con el mismo nombre. Estaba viendo issues similares, y en la issue #174 dice que "la property no debe llamarse igual a un atributo o habrá un error", sin embargo, en la issue
 #79 el setter y el getter utiliza el mismo nombre que el atributo, y el código funciona bien.
Además, intenté experimentar con el ejemplo de la issue #79 y al borrar la parte del código setter, el programa dice "AttributeError: can't set attribute". **No entiendo por qué el setter hace que el código se ejecute sin error, y tampoco entiendo cuando se pueden repetir el nombre de un atributo y de una property.**
![Duda properties](https://user-images.githubusercontent.com/80867403/113798932-9f879d00-9743-11eb-8d16-d9b6b7cbb5b1.png)

**Comment by tqmbanados** [comment]
Hola, que bueno que escribiste. En la issue #79 el código está escrito de manera que al inicializar la instancia, se llama al "setter" del atributo para cambiar el valor de ```self.__nota```. Se ve confuso, pero básicamente lo que ocurre es esto:

1.- Se crea la clase ```Alumno```. Esta viene con la property ```self.nota```, que ocupa el atributo interno ```self.__nota```.
2.- Al instanciar un objeto de la clase, lo primero que se hace es crear y definir el atributo interno ```self.__nota```. En la línea siguiente, se usa la property ```self.nota```, para setear el valor de ```self.__nota```. 
*en el ```__init__()```, la línea que dice ```self.nota = nota```  __no__ es la definición de un atributo, es una referencia a la property ya creada con la clase*
El error ocurre por que al sacar el método setter, python no sabe como asignar valores a la property ```self.nota```, y por ende al atributo ```self.__nota``` al cual esta relacionado. Entonces, en el ```__init__()```, la línea ```self.nota = nota``` tira un error: se le pidió al programa que usara un método setter que no existe. 
Entonces, no se rompe ninguna regla en el código original: la property **no** tiene el mismo nombre que un atributo, sólo pasa que se llama a la propery en el ```__init__()```, lo que pareciera ser la definición de un atributo. 
Espero que te quede más claro.

**Comment by FVivess** [comment]
Gracias por responder. Aún no me queda 100% claro. Por lo que entiendo ahora, la clase Alumno solo tiene un atributo (self.__nota), y el self.nota es una property. Entonces, con la línea de código "AlumnoJP = Alumno("JuanPablo", 0)", ¿el atributo interno self.__nota ya tiene valor, o sigue como None? También me cuesta entender bien la parte del setter, porque en ningún momento en el código se llama al setter de la forma nota(nueva_nota), sin embargo, el código igual hace el cambio de la nota 0 a 1.0, y no estoy seguro cómo lo hace.

**Comment by tqmbanados** [comment]
Me parece que tienes algunas confusiones en los properties, te sugiero que repases un poco la materia por las dudas. Recuerda que el setter de una property no se llama con ```setter()```, como un método o función, sino que se asigna con ```self.propery = valor```. En la línea ```AlumnoJP = Alumno("JuanPablo", 0)```, ocurre lo siguiente en orden:

1) Se inicializa una instancia de ```Alumno```.
2) Se crea el atributo ```self.nombre``` y se le asigna el valor del parámetro ```nombre```, es decir ```"JuanPablo"```.
3) Se crea el atributo ```self.__nota```, y se le asigna el valor ```None```.
4) Usando la property de la clase ```Alumno``` ```self.nota```, se asigna el valor ```0```. Sin embargo, vemos que en el setter definidio en la clase para ```self.nota```, si el valor es menor a ```1.0```, se asigna el valor ```1.0```, es decir, el valor ```0``` es inválido.
5) Finalmente, usando este método setter, se le asigna el valor ```1.0``` a ```self.__nota```. 

Trata de ver cada línea de código del ejemplo, y compararlo con las instrucciones de arriba en "lenguaje humano"; para entender que ocurre exactamente en el código. Cuéntame cómo te va!

**Comment by FVivess** [comment]
Ahora si me quedó claro. Muchas gracias!

**Comment by tqmbanados** [comment]
Me alegro! Suerte 🐱

**Comment by raibd** [comment]
Hola, justo tenía una duda sobre esto y no quiero escribir un issue ya que aqui casi se responde. Mi pregunta es porque no se puede eliminar la linea `self.nota = nota` y escrbir `self.__nota = nota` directamente? Funcionaria igual al menos con los ejemplos que hice. Sera por buena practica para separar el atributo encapsulado del no encapsulado?

**Comment by tqmbanados** [comment]
Hola @raibd! Eso se para que el filtro del setter (el valor debe estar entre 1.0 y 7.0) se aplique desde el comienzo. Si te fijas, en el ejemplo de los contenidos, la nota inicial al instanciar el objeto es 0. Eso quiere decir que si asignamos el valor a ```self.__nota```, el valor inicial no estará dentro de los parámetros definidos, entonces el objeto inicial no funcionaría como debe. Usar de inmediato el setter para asignar los valores asegura que siempre funcione correctamente.

**Comment by raibd** [comment]
Gracias, ahora me queda mas claro.

**Comment by tqmbanados** [comment]
Me alegro!
