### ISSUE TITLE
Duda sobre opción Combatir y Ejercito

### ISSUE THREAD

**Issue by juliettegramatges** [IIC2233/Syllabus#192]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda sobre opción Combatir y Ejercito

Hola! Tengo un par de dudas.
1. No me queda muy claro cómo funciona cada ronda. Por lo que entendí, 1 ronda está compuesta de varios enfrentamientos, y para terminar la ronda uno de los ejércitos debe quedar sin combatientes. Si el equipo del usuario queda sin combatientes debo comprar nuevos gatos... ***¿Qué pasa si me quedé sin combatientes y sin oro?¿Se reinicia el juego?.*** 
2. Otra cosa, si yo gano una ronda ***¿Debo seguir en el combate (ya que en enunciado dice que un combate equivale a 3 rondas)?***. En ese caso qué pasa con el equipo rival, ***¿tengo que restaurarlo a como estaba en un comienzo?***
3. Me quedan dudas acerca de las 3 rondas. ***¿Debo asumir que una vez termino las 3 rondas veo quién tuvo más victorias?***. Pero eso no tendría sentido porque reinicio todo el juego si pierde el ejercito del usuario (entendí que es como si empezara desde 0 las rondas).  ***¿O se refiere a que si gano 3 rondas gano el combate ? (y en ese caso, cuál sería la diferencia con ganar una ronda y oro? o eso queda a mi elección?)***
4. Por último no me queda claro lo que piden si selecciono "Ejercito" en el menú de inicio en enunciado, ***¿acá solo presento al ejercito?***

Gracias de antemano :)

**Comment by wintermelyn** [comment]
Hola @juliettegramatges!

1. Tu entendimiento de las rondas es correcto, una ronda esta compuesta de varios enfrentamientos 1v1 entre los primeros combatientes de cada ejercito y la ronda solo acaba cuando uno de los ejércitos pierde todas sus unidades, aquí tienes otra issue similar al respecto -> https://github.com/IIC2233/Syllabus/issues/186#issuecomment-2053684771. Ahora sobre tu pregunta en particular:

> "¿Qué pasa si me quedé sin combatientes y sin oro?"

Si te quedas sin combatientes significa que perdiste la ronda anterior, esto vendría siendo "Game Over", y la idea es que todo el juego vuelva a su estado inicial, es decir, vuelves al Menú de Inicio con ronda 1, con un ejercito vació y una cantidad de dinero igual a ORO_INICIAL. También implica que el ejercito enemigo recupera todas las unidades que haya perdido, como si hubieras ejecutado el programa desde 0.

También recuerda que al ganar cada ronda ganas ORO_GANADO y la idea es que estos parámetros siempre te sirvan para comprar 1 o mas unidades, curar ejercito, comprar mejoras, etc. La cantidad en particular quedará a su criterio.

2. Responderé tus 2 preguntas por separado

> Si yo gano una ronda ¿Debo seguir en el combate (ya que en enunciado dice que un combate equivale a 3 rondas)?

Una vez ganes tu tercera ronda seguida significa que ganaste el juego ~~(derrotando a la tiránica gatochico)~~ por lo que deberás imprimirlo en consola y finalizar el programa.

> En ese caso qué pasa con el equipo rival, ¿tengo que restaurarlo a como estaba en un comienzo?

Cada archivo de dificultad en la carpeta `data/` tiene 3 lineas, las cuales corresponden a los combates de cada ronda. Es decir, si se elige la dificultad "facil" las rondas serian las siguientes:

```
Esteban,CAB,60,10,5,8,5;Diego,MAG,55,9,10,6,5;Benjamin,GUE,70,15,7,5,7  # <- Ronda 1
Cristobal,GUE,70,15,7,5,7;Julio,CAB,60,10,5,8,5;Clemente,MAG,55,9,10,6,5  # <- Ronda 2
Julian,MAG,55,9,10,6,5;Carlos,CAB,60,10,5,8,5;Diego,GUE,70,15,7,5,7 # <- Ronda 3
```

En caso de que el jugador gane una ronda avanzará a la siguiente y en el caso de que pierda debes restaurar los ejércitos y volver a la ronda 1.

3. Responderé tus 2 preguntas por separado

> ¿Debo asumir que una vez termino las 3 rondas veo quién tuvo más victorias o se refiere a que si gano 3 rondas gano el combate?

Como te menciono anteriormente el jugador solo puede avanzar de ronda si gana la anterior. Por lo que puedes asumir que si el jugador pierde cualquiera de las rondas es "Game Over" y debe volver a empezar. El jugador solo puede ser declarado ganador si sale victorioso en las 3 rondas seguidas.

> ¿Cuál sería la diferencia con ganar una ronda y oro, o eso queda a mi elección?

Cada vez que ganes una ronda ganas ORO_GANADO de oro. Si pierdes una ronda vuelves al estado inicial teniendo ORO_INICIAL de oro.

4. Estas en lo correcto, si se selecciona la opción ejercito solo debes printear la instancia de ejercito del jugador, lo cual presentara a cada unidad que posea actualmente.

Espero haberte ayudado, me comentas si tienes alguna duda 😊.

**Comment by juliettegramatges** [comment]
Perfectoooo! Muchas gracias!!
