### ISSUE TITLE
Problema con el encoding al leer los posts

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2233/syllabus#192]
Hola! hace unos dias hice un issue sobre un error que me salía al usar el encoding utf-8, ya que no me dejaba leer el archivo posts.csv. lo logre resolver usando encoding=latin-1, pero ahora cuando el programa se encuentra con ciertos simbolos como apostrofes, el programa se para, no tira ningun error, solo deja de imprimir el texto y no te deja seguir haciendo nada. Hay alguna forma de solucionarlo? impacta mucho la nota si explico esto en el readme?

**Comment by maggiemunoz** [comment]
ayuda porfa

**Comment by lily416** [comment]
¡Qué error te sale cuando utilizas `utf-8`?

**Comment by maggiemunoz** [comment]
UnicodeDecodeError, el de la issue #165

**Comment by lily416** [comment]
Vuelve a clonar el syllabus del curso y sustituye los archivos que estas utilizando (solo copia y pegalos en la carpeta).

**Comment by maggiemunoz** [comment]
eso me dijeron que haga en el issue pero no me resulto, y quedan 5 minutos :(( que tanto afectaria quedarme con ese error?

**Comment by lily416** [comment]
Depende del corrector y los problemas que le cause al momento de corregir 😞 
Así que no te puedo decir con seguridad cuanto puede afectar

**Comment by maggiemunoz** [comment]
pucha no te preocupes, pero el encoding latin=1 esta bien? porque a mi me funciona pero no se si es porque mi archivo esta distinto o que :(

**Comment by lily416** [comment]
Lo más correcto sería utilizar `utf-8`, pero dada tu situación lo mejor es que lo dejes con el encoding que estas usando.
En tu readme explica tu error y referencia esta issue.

**Comment by maggiemunoz** [comment]
ya perfecto gracias

**Comment by lily416** [comment]
Revisando tu código (muy a la rápida) puede que el error se deba a que al momento de escribir en los archivos (`Tarea00.py` y `usuarios.py`) no defines un encoding al abrir el archivo, prueba agregar el encoding a todos los `open()`, definirlo como `utf-8` y utilizar archivos nuevos para testear.

**Comment by maggiemunoz** [comment]
vale la pena si ya pasaron las 8? siento que el descuento me bajaría mas que el error :(

**Comment by lily416** [comment]
En caso de que funcione puedes:
1. Indicar en el readme las líneas que el corrector debe cambiar, lo que significará un descuento según líneas cambiadas.
1. Entregar atrasado con los cambios realizados, lo que significará un descuento según la hora del commit a revisar.

Depende de ti (si es que lo del comentario anterior llegara a ser la solución) ver cual opción te conviene más, para eso te recomiendo revisar la [guía de descuentos](https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md).

Y no te desanimes, aún quedan muchas tareas y actividades por delante 😄

**Comment by lily416** [comment]
> vale la pena si ya pasaron las 8? siento que el descuento me bajaría mas que el error :(

Si son menos de 20 líneas, conviene indicar en el readme el cambio, ya que el descuento es de `techo(c_lineas/4)` décimas, donde `c_lineas` es la cantidad de líneas a cambiar.

Si son más de 20 líneas, depende de la hora (push) del commit a corregir, ya que el descuento es de `5 + 15t/24` décimas, donde `t` es el tiempo transcurrido. 
En este caso, lo mejor es que hagas el commit y compruebes con la distribución de puntajes el puntaje asociado a lo que no se podría corregir y el descuento que tendrías si es que entregaras tarde, para así ver qué te conviene hacer.

**Comment by maggiemunoz** [comment]
yaya, voy a intentar de solucionarlo primero :( porque pongo el utf-8 y aun me falla no entiendo por que

**Comment by lily416** [comment]
Si quieres podemos seguir intentando solucionarlo :)
Mándame una foto del error que te aparece en consola (ojalá se alcance a ver todo el texto).

**Comment by maggiemunoz** [comment]
ahora con lo que tengo problemas es con clonar el syllabus de nuevo, quizas no lo estoy haciendo bien, debo borrar el que tengo y despues clonarlo de nuevo?

**Comment by lily416** [comment]
Sí, borralo y pon en la consola `git clone https://github.com/IIC2233/syllabus.git`.

**Comment by maggiemunoz** [comment]
mira, me pasó algo muy raro, hice eso, corri el codigo usando utf-8 y funciono perfecto, abri el archivo para ver si se habia editado, cerre el archivo, lo corri denuevo y me tiro error con el encoding

Este:
File "/Users/Maggie/Desktop/syllabus/Tareas/T00/prograposts.py", line 43, in ver_muro
    linea = prograposts.readline()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 1259: invalid start byte

**Comment by lily416** [comment]
¿Qué programa usaste para abrir el archivo?

**Comment by maggiemunoz** [comment]
se abre con excel

**Comment by lily416** [comment]
Cuando utilizas Excel, este modifica el archivo y le agrega el carácter que no puede leer el encoding `utf-8`, después te voy a dejar una issues donde se habla más sobre este problema (si la encuentro). 

Para abrir los archivos, lo mejor es que utilices la IDE que estas utilizando, así puedes revisar el contenido del archivo, sin que sea modificado.

**Comment by maggiemunoz** [comment]
aaaahhh eso explica harto jajajaja, como con la IDE?

**Comment by lily416** [comment]
La IDE (Interfaz de desarrollo), además de crear y editar archivos de código (en el caso del curso .py), también permite abrir y editar otro tipo de archivos, como archivos de texto, csv, entre otros. 

Para abrirlo, basta con abrir la carpeta en la que quieres trabajar (en el caso de la imagen, T00) y seleccionar el archivo que quieres ver.

![image](https://user-images.githubusercontent.com/26393515/77373178-44585780-6d46-11ea-8fa9-017317712b91.png)

**Comment by maggiemunoz** [comment]
ya que bueno, creo que me conviene hacer el cambio de lineas nomas porque son solo 4 lineas entonces una decima nomas, mil gracias! nunca mas excel entonces jajajajaja
