### ISSUE TITLE
Duda sintaxis ayudantia

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#192]
En la ayudantia sale ese fragmento de código no entiendo pq no simplemente se pone  `self.childs[child[0]] = Node() `

```python
else:
    new = Node()
    self.childs[child[0]] = new
    new.add_child(child[1:])
```

**Comment by jtagle2** [comment]
Era simplemente para una lectura más fácil del código. Es más, se comentó durante la ayudantía que el problema quedaría mejor utilizando en vez de un diccionario normal, un defaultdict que usara nodos por defecto, de esa forma nos ahorramos todos esos if.
Saludos!
