### ISSUE TITLE
DESBONIFICACION_OSADO

### ISSUE THREAD

**Issue by itplanella** [IIC2233/syllabus#192]
Hola! quisiera saber si me podrian explicar de mejor manera en que consiste y que valores debe tener el parametro DESBONIFICACION_OSADO que se utiliza para calcular la experiencia al ganar una carrera. Por ejemplo si los valores deben estar en 0 y 1, o si debe ser un valor negativo, etc. Gracias de antemano.

**Comment by jeschuwirth** [comment]
Hola!

Como la fórmula es:
![image](https://user-images.githubusercontent.com/37160256/64481234-f0b95e80-d1a5-11e9-9f29-86f94a94f78a.png)

y queremos que los pilotos osados ganen menos experiencia que los precavidos, entonces el valor de `DESBONIFICACION_OSADO` debe ser un número entero positivo o 0; si el valor es 1, entonces el piloto ganan toda la experiencia; si es 0 significa que no ganan nada; cualquier valor intermedio representa que gana experiencia pero menos de la 'normal', el valor también podría ser mayor a 1 y representa que ganan más experiencia de lo normal.

Sumándome a la misma idea el valor de `BONIFICACION_PRECAVIDO` es un valor número entero positivo o 0, por lo general este valor es mayor al de `DESBONIFICACION_OSADO`, pero no debe ser necesariamente así.

Ojalá haya quedado claro, cualquier duda sigue comentando en la issue.

Suerte!

**Comment by Jprampad** [comment]
Esta desbonificación, que va entre 0 y 1, se elige con un randint entre ese números?, ese parametro tiene que estar en parametros.py?

**Comment by jeschuwirth** [comment]
Hola @jprampad, 

Como se puede ver en el formato del nombre de la variable (escrita todo en mayúsculas), es un parámetro que tiene que estar en parámetros.py

**Comment by pwillmer** [comment]
Hola! , en parametros.py se encuentra como BONIFICACION_OSADO. debemos cambiarlo  a DESBONIFICACION_OSADO ?
Gracias de antemano.

**Comment by lily416** [comment]
@pwillmer Queda a tu criterio si lo dejas como `BONIFICACION_OSADO` o lo cambias a `DESBONIFICACION_OSADO`, cualquier decisión que tomes avisalo en tu readme :)

Saludos y éxito en la tarea 👋 💪
