### ISSUE TITLE
Error en instalación de PyQt

### ISSUE THREAD

**Issue by bvallejo1** [IIC2233/syllabus#192]
Hola, abrí el CMD para instalar el PyQt y al momento de poner el comando de instalación y ejecutarlo me lanzaba el siguiente mensaje:
"pip3" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
Después de probar distintas funciones busqué en google la solución lo que me llevo a cambiar ciertas direcciones en el PATH (variables de entorno).
Esto no me brindó la solución ya que ahora me aparece el siguiente mensaje al ejecutar el comando python -V:
"python" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Que puedo hacer?
Muchas gracias.

**Comment by KnowYourselves** [comment]
Prueba haciendo uso de `py -v` y dime que sucede!

**Comment by bvallejo1** [comment]
Me arroja ese comando.

Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by KnowYourselves** [comment]
Eso quiere decir que para tu sistema operativo (_windows_ me imagino), pudes acceder a python haciendo uso de `py` no de `python` o `python3`, de hecho, si haces `py -V` debería darte como resultado `Python 3.7.1`. 

Esto quiere decir que cada vez que quieras ejecutar algo en _python_ debes utilizar el comando `py`.  Con esto en mente puedes seguir los pasos para instalar _PyQt5_.

Cualquier otra duda dime!

**Comment by bvallejo1** [comment]
Sigue diciendome que no reconoce pip3 como comando interno, ahora traté de instalar pip y me arroja el siguiente mensaje al comando py get-pip.py:

C:\Users\borja\Anaconda3\python.exe: can't open file 'get-pip.py': [Errno 2] No such file or directory

**Comment by KnowYourselves** [comment]
Ese error ocurre porque el programa que estas intentando ejecutar (`get-pip.py`) no se encuentra en el lugar donde esta abierta la consola de comandos.

Anda a la carpeta de tu computador donde tienes `get-pip.py`,  una vez ahí haz Ctrl + Shift + Click Izquierdo y te dará la opción de abrir la consola de comandos aquí. Una vez hecho eso prueba haciendo `py get-pip.py`.

**Comment by bvallejo1** [comment]
No existe una carpeta con ese nombre.

**Comment by KnowYourselves** [comment]
En este [link ](https://www.liquidweb.com/kb/install-pip-windows/) puedes encontrar instrucciones detalladas de como instalar `pip`, específicamente en la sección _Installing Pip_ parte 1, puedes encontrar un link al archivo `get-pip.py`, descárgalo, abre la consola de comandos en la carpeta donde el archivo fue descargado y luego haz uso del comando `py get-pip.py`

**Comment by bvallejo1** [comment]
Hice lo que me dijiste y me sale esto:
ERROR: Could not find a version that satisfies the requirement pip (from versions: none)
ERROR: No matching distribution found for pip

**Comment by KnowYourselves** [comment]
Considerando que estás usando `Anaconda` escribe el comando `conda`  y ve si funciona.

Si el comando funciona utiliza los siguientes comandos para instalar pyqt5:

```
conda update --all
conda install qt
conda install pyqt
```

En caso de que esto tampoco funcione te recomendaría desinstalar anaconda e instalar `Python 3.6` desde la página oficial de _Python_.
