### ISSUE TITLE
Ingreso de coordenadas a atacar

### ISSUE THREAD

**Issue by nicolascamhi** [IIC2233/syllabus#192]
Hola! En qué formato entrega el jugador las coordenadas del tablero que va a atacar?? Es libre o necesariamente se entregan como [columna, fila]??

**Comment by vicentevegaulloa** [comment]
Hola @nicolascamhi !

Esto no está especificado en el enunciado, por lo que queda a tu criterio. 😄 En la issue #125 se habla de algo similar.
