### ISSUE TITLE
Modifique algo que no debia modificar y ahora todos los tests me salen errados

### ISSUE THREAD

**Issue by EnriqueVildosola** [IIC2233/Syllabus#192]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Quería saber el output que estaba obteniendo y modifique algo del test_tablero_celdas_alcanzadas.py y ahora todos los tests con relacion al tablero que antes tenía buenos me los entrega con fail y no se como arreglarlo. Ya borré lo que había puesto en el test y no pasa nada. Ayuda por favor

**Comment by dvillas28** [comment]
prueba a reemplazarlos con los archivos del syllabus

**Comment by Benjeeeh** [comment]
Hola Enrique!
Prueba reemplazando con el código original de los archivos entregados, y agregándole lo que tu tienes para ver si se restaura, quizás pasaste a llevar algo que no se debía modificar.
Te recomiendo subir tus avances a tu repositorio, para poder echarle un ojo y ver si puedo identificar lo que te faltó.

**Comment by EnriqueVildosola** [comment]
Muchas gracias por la sugerencia, ya logré solucionarlo :)
