### ISSUE TITLE
Propagacion cura

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#192]
El enunciado dice esto:

Dentro de cada país, la cura afectara de la siguiente manera: Cada persona infectada tendrá por día un 25% de curarse y esta se tiene que multiplicar por el nivel de resistencia a la medicina que tenga el tipo de infección.

¿Esto quiere decir que la probabilidad diaria de que la persona se cure es de (25 * resistencia a medicina)/ 100?

Si no es eso, no se que es.

**Comment by gbordoni** [comment]
0.25 * resistencia

**Comment by stephichau** [comment]
@jorgeriesco es lo que dice @gbordoni :)
