### ISSUE TITLE
En el README es necesario explicar los módulos desarrollados que fueron solicitados por el enunciado?

### ISSUE THREAD

**Issue by joseinfantec** [IIC2233/Syllabus#193]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Al desarrollar el README no se si colocar los módulos como limpiar o solucionar como módulos creados por mi. Yo simplemente los modifique. ¿Hay que colocarlos? o  simplemente colocamos aquellos que creamos nosotros y que no son parte de los módulos solicitados

**Comment by roahoki** [comment]
hola @joseinfantec ! idealmente tienes que explicar todo lo que hayas implementado :)

**Comment by joseinfantec** [comment]
Buenisimo. Y en relación a la ejecución, a que se refiere con los archivos y directorios adicionales?

**Comment by Benjeeeh** [comment]
Hola!
Lo de archivos y directorios adicionales se refiere a que si para la corrección necesitamos crear archivos adicionales (valga la redundancia) o necesitamos meter ciertos archivos a una carpeta especial creada por ti para que funcione. En general poca gente crea estos archivos especiales, por lo que si no creaste nada que necesitemos y que no entregues en tu repositorio puedes eliminar o dejar vacía esa parte.

Sobre la parte del menú, márcalo con un ticket verde si es que cumples lo que se pide en la distribución de puntaje de la tarea sobre el uso de consola:
![image](https://github.com/IIC2233/Syllabus/assets/78326186/8f6e643a-9ac4-4641-b348-9f7d55660578)
En general esa parte evalúa la entrega del nombre de usuario y el tablero a realizar.

Saludos y éxito!
