### ISSUE TITLE
Abrir aeropuertos y fronteras

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#193]
¿Puedo abrir los aeropuertos y fronteras por separado? Es decir ¿Ponerlos como acciones independientes en la cola de prioridades del gobierno? 

Ya que, aunque podría ser obvio, en el enunciado siempre se mencionan juntas como si fueran una sola acción, pero no queda claro y quiero estar seguro.

**Comment by acrojas2** [comment]
tengo la misma duda!

**Comment by nivek0o0** [comment]
esto lo pregunté hace más de 2 días y aún no se responde

**Comment by arturodelreal** [comment]
Fronteras y aeropuertos funcionan por separado. 
Salu2
