### ISSUE TITLE
Duda ejercicio propuesto 3.1 Semana 02 - "Intento de Influencer"

### ISSUE THREAD

**Issue by FVivess** [IIC2233/syllabus#193]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Para realizar esta actividad, ¿solo se debe rellenar el primero código que nos dan? (y dejar los otros intactos, solo ejecutar los 3 juntos).
Si es así (que es lo que hice), ¿si mi código solo imprime "Muser" está bien el resultado?

**Comment by riadeane** [comment]
Hola @FVivess! 🙌

Exacto! Las otras dos celdas solo las debes ejecutar. Si la ultima celda imprime "Muser", debería estar bien tu código 😎

Éxito en el estudio! 🌺

**Comment by FVivess** [comment]
Gracias!
