### ISSUE TITLE
Duda sobre ataque de combatiente tipo Mago

### ISSUE THREAD

**Issue by SebaPassi** [IIC2233/Syllabus#193]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!

Tengo una pregunta en torno al método atacar de combatiente tipo Mago. En el enunciado dice que tiene la habilidad de reducir la defensa del enemigo con sus hechizos. Sin embargo, después habla de "ignorar". Entonces, en caso de activar su poder, ¿debo restarle permanentemente a la defensa del enemigo el porcentaje especificado o simplemente ignoro ese porcentaje para el calculo del ataque del mago?

Muchas gracias!

**Comment by tebi01** [comment]
Hola, @SebaPassi!

La parte de "reducir la defensa del enemigo" es sólo descriptiva y provee un resumen de lo que puede hacer la clase.

En la práctica debes ignorar el porcentaje calculado, sólo mediante ese ataque.

Espero haberte ayudado!!

**Comment by SebaPassi** [comment]
@tebi01 muchas gracias!
