### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5'

### ISSUE THREAD

**Issue by mjgarrido1** [IIC2233/syllabus#193]
Me aparece este error cuando trato de importar PyQt5 en un archivo python. 
Instalé todo bien y al escribir los comandos de nuevo en consola me dice lo siguiente:
```
pip3 install pyqt5
pip3 install pyqt5-tools
```
"Requirement already satisfied" en cada una de las lineas anteriores. 

que puedo hacer?

**Comment by Arcoirisky** [comment]
¿Como lo estás importando? D:

**Comment by Arcoirisky** [comment]
Más específico: 
¿Eres mac por casualidad? 
¿Tienes/tenías instalado anaconda o similar?
¿Tienes mas de una versión de Python?
Si inicias Python en consola ¿puedes importarlo?

**Comment by mjgarrido1** [comment]
`import PyQt5`


No soy mac, soy win10, tampoco tengo anaconda ni más de dos versiones python :(
Me fijé que no estaban instalados los paquetes en pycharm así que debi hacerlo manual en configuración de pycharm. Creo que me está funcionando todo bien pero no sé si hice lo correcto al instalarlos manual

**Comment by Arcoirisky** [comment]
Instalaste Python en una carpeta distinta a la default? Quizás por eso no te los tomaba pycharm 🤔

**Comment by mjgarrido1** [comment]
tanto python como pycharm los tengo en la carpeta descargas

**Comment by mjgarrido1** [comment]
no miento jaja los .exe están en descargas, los programas están dde se instalan por defecto

**Comment by Arcoirisky** [comment]
Akdnkskd el susto! 

Entonces quizás sea cosa de Pycharm 🤔 pero si te funciona, genial akndms

**Comment by martucoss** [comment]
Yo tuve el mismo problema, que es que pycharm viene por defecto con python 2.7, lo que tienes que hacer es dentro de pycharm elegir 3.6 y no habría problema

**Comment by fediaz3** [comment]
Hola! Necesito ayuda
Estoy en la misma situación, pero me sale otro error 
`pip3 install pyqt5 `
`pip3 install pyqt5-tools`

"Requirement already satisfied" en cada una de las lineas anteriores.

y luego al ejecutar:
`import PyQt5`

"import" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

**Comment by tavalenzuelag** [comment]
Tuve el mismo problema, sin embargo, ejecutando la terminal desde pycharm y ocupando los comandos de instalación de PyQt5 logré que funcionara correctamente.

**Comment by fediaz3** [comment]
Gracias! 
me resultó como dijo tavalenzuelag y ahora puedo importar PyQt5, pero en el proceso me salio un error... 
¿Te sale lo mismo?  @tavalenzuelag  
¿Algún ayudante sabe si este error puede tener inconvenientes mas adelante?, 
por el momento el único problema es : para poder usar PyQt5 debo hacer el mismo proceso para cada proyecto nuevo que cree.


Desde el terminal de pycharm hice:
 1) pip3 install pyqt5 (carga bien)
 2) python -m pip install --upgrade pip 
(carga y despues sale el error... ) 

Foto:
![error_instalarPyqt5_pycharm](https://user-images.githubusercontent.com/48292836/57573030-5f510000-73f0-11e9-9604-d21334baee68.jpg)

**Comment by tavalenzuelag** [comment]
Toda la razón @fediaz3 , no me había percatado de que tenía que repetir el procedimiento cada vez que creara un nuevo proyecto. Me ocurre lo mismo y no sé como solucionarlo...

**Comment by Arcoirisky** [comment]
Por casualidad, los que no tienen anaconda, ¿están creando un env de cada proyecto? ó ¿usan Python 3.6 puro? (Como intérprete, si usan env en cada proyecto debería aparecerles como intérprete junto a Python3)

Los que tienen anaconda: He sabido -y vivido- que anaconda tiene la mala costumbre de consumir todos los paquetes que intentan instalar sus usuarios. Personalmente, diría que desinstalen anaconda y se aseguren de borrar todo rastro de que existiera porque si es ese el problema, no se solucionará hasta que desaparezca por completo :(

**Comment by tavalenzuelag** [comment]
Finalmente me funciona utilizando un "intérprete" ya existente al momento de crear un proyecto. No sé el motivo ni nada por el estilo, pero funciona. Por alguna razón cuando no hago esto y dejo que use uno nuevo en cada proyecto no termina reconociendo pyqt.

**Comment by gatochico** [comment]
Hola! Si estas creando un proyecto nuevo y eliges usar un interprete nuevo, lo más probable es que hayas elegido utilizar un [Virtual environment](https://rukbottoland.com/blog/tutorial-de-python-virtualenv/) para dicho proyecto. En el link hay información al respecto, pero en resumen lo que hacen es aislar las librerías que utiliza cada proyecto. Es por esto que no te reconoce pyqt5, ya que en este nuevo entorno virtual aislado que creaste no has instalado la librería todavía. 

Si seleccionaste "utilizar un interprete ya existente " y ahora te funciona, probablemente utilizaste el intérprete global de python de tu computador, que posee todas las librerias que has instalado hasta la fecha. No deberías tener más problemas con pyqt5 en ese proyecto (:

En general utilizar entornos virtuales es una buena práctica al momento de programar, pero no es un conocimiento pedido por el curso. Si aún así te gustaría saber al respecto, avisanos y podemos ayudarte a configurarlo para trabajar. Saludos!

**Comment by tavalenzuelag** [comment]
Gracias!!
