### ISSUE TITLE
Matriz de Incidencia

### ISSUE THREAD

**Issue by nachocontreras** [IIC2233/Syllabus#193]
En los contenidos de grafos, en la parte de matriz de incidencia, el grafo_dirigido no hace referencia a la imagen siguiente:

<img src="https://raw.githubusercontent.com/IIC2233/contenidos/3b7c6480ed77f9424565d1d3c05651c1c5128dee/semana-4/img/grafos.png">

Sale que el grafo dirigido es:
```
[1, 0, 0, -1, 0]
[0, -1, 1, 0, 0]
[0, 1, -1, 1, 0]
[0, 0, 0, 0, 1]
[-1, 0, 0, 0, -1]
```
Pero no debería ser:
```
[1, 0, 0, 0, 0]
[-1, 1, 0, 0, 0]
[0, -1, 1, 1, 0]
[0, 0, -1, 0, 1]
[0, 0, 0, -1, -1]
```

?? 🤔

**Comment by akaminetzkyp** [comment]
Tienes toda la razón. Lo arreglaremos inmediatamente.
