### ISSUE TITLE
Formulario entrega atrasada

### ISSUE THREAD

**Issue by tolavarria** [IIC2233/syllabus#193]
Hola.
No entiendo bien a que formulario se refiere el mensaje de canvas donde dice que para enviar una tarea pasada las 20 horas de hoy se debe llenar uno.

**Comment by radoslavyuras** [comment]
x2

**Comment by lily416** [comment]
Una vez terminada la entrega les llegara un aviso en el cual se les indicara el link del form. En caso de que quieras entregar tu tarea después de la hora de entrega (20:00 de hoy para la T00), debes rellenar ese form y se te hará un descuento asociado al tiempo de atraso.

Saludos y éxito en la tarea 👋🐦

**Comment by tolavarria** [comment]
Gracias!

**Comment by alvaritions** [comment]
En donde debería aparecer este mensaje del form? No lo encuentro :(

**Comment by lily416** [comment]
En los anuncios de Canvas les debería aparecer el mensaje.

**Comment by alvaritions** [comment]
Gracias!
