### ISSUE TITLE
fatal: cannot lock ref 'HEAD': unable to resolve reference 'refs/heads/main': reference broken

### ISSUE THREAD

**Issue by iangrosan** [IIC2233/Syllabus#193]
* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Cuando intenté subir mi avance de la tarea, recibo el error en el titulo, traté haciendo un git reset pero no he logrado subir la tarea. Pareciera ser que cuando hice el "git add ." me trackeó carpetas padre, y no las subcarpetas, lo que me pareció raro.

**Comment by Emiliax16** [comment]
Hola @iangrosan . ¿Pudiste solucionar el error? si no es el caso, porfavor adjunta pantallazos del error que te sale en la terminal. Saludos.

**Comment by iangrosan** [comment]
Si. Tuve que reclonar la carpeta

Gracias
