### ISSUE TITLE
Que pasa cuando un jugador se rinde?

### ISSUE THREAD

**Issue by cnillanes** [IIC2233/syllabus#193]
Hola! no me queda claro si cuando un jugador se rinde el programa debe parar su ejecución o dar la opción de volver al menú de inicio.

Por otra parte, que pasa con el puntaje de una partida incompleta? lo considero como 0 por abandono o no lo incluyo al txt ya que rindió sin terminar?

**Comment by matiasmasjuan** [comment]
Hola @cnillanes !

Ambas respuestas se encuentran en el **enunciado**:

1. El **Flujo de Juego** señala:

![rendirse_menu](https://user-images.githubusercontent.com/48495638/91240918-5da86a00-e711-11ea-93fc-3163d71341da.png)

Por lo tanto, si el jugador ingresa la opción de **Rendirse**, **no** se debe parar su ejecución, sino que simplemente se debe volver al **Menú de Inicio**.

2. La sección **Puntajes** señala:

![puntajes_](https://user-images.githubusercontent.com/48495638/91241037-b11ab800-e711-11ea-9f4f-5822c00809e5.png)

Por lo tanto, si el jugador ingresa la opción de **Rendirse**, se debe **calcular** su puntaje de todas formas, y guardarlo en el archivo ```puntajes.txt```. **Ojo** que es distinto a la opción **salir**, ya que en ese caso se debe **salir** del programa sin **guardar** el puntaje.

Saludos y mucho éxito con la tarea! :smile:
