### ISSUE TITLE
Duda al crear una nueva partida

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#193]
Hola si el usuario esta creando una nueva partida, ya me entrego su nombre , equipo y los guarde en el csv. La pregunta es si el usuario tiene la opción de volver/cancelar en el instante en que esta eligiendo su vehículo inicial o este esta obligado en ese punto a continuar y elegir su vehículo.
Otra pregunta el Usuario tiene que tener la opcion de volver/cancelar cuando le estoy pidiendo el nombre o el equipo?

**Comment by jeschuwirth** [comment]
Hola @JuaniAndres,

Para la primera duda tienes que seguir lo que dice el enunciado:
![image](https://user-images.githubusercontent.com/37160256/64481305-8e615d80-d1a7-11e9-86f1-9b2c84cb6ede.png)

En cuanto a la segunda duda; como no está explicito queda a criterio del alumno, por lo tanto tu eliges si agregas la opción de volver o no.

Suerte!

**Comment by JuaniAndres** [comment]
el tema es que me refiero con la primera pregunta al menú de sesión específicamente a crear una nueva partida porque se me ocurrió que como se guarda el piloto antes de que elija un vehículo en el caso hipotético de que se pueda volver en ese instante puedo terminar con un usuario que no tenga ningún vehículo asociado
![partida](https://user-images.githubusercontent.com/48482216/64481510-9242af00-d1aa-11e9-914d-7a653b267e72.PNG)

**Comment by jeschuwirth** [comment]
Hola,

Es verdad que quedaría un piloto sin vehículo asociado y también lo encuentro raro, pero como en el menú de preparación de carrera dice lo siguiente:

![image](https://user-images.githubusercontent.com/37160256/64482081-6b8b7500-d1b8-11e9-81e0-f790deefa5ae.png)

El usuario no podrá elegir un vehículo por lo que el programa quedará pegado en ese menú y no se iniciará la carrera, por lo general eso es malo y debería existir un botón de regresar, pero como no se pide queda a criterio que se hace en ese caso.

Como no encontré ningún otro error que pueda traer tener un piloto sin vehículo no veo el problema con tener la opción de volver al menú inicial en vez de comprar un vehículo.

**PD:** Buen pantallazo de la tarea, es bonito no tener que buscar en enunciado :)

**Comment by JuaniAndres** [comment]
yap yo creo que simplemente voy a agregar un código que revise al cargar una partida que el usuario tenga vehículos y que lo solucione en caso que no los tenga

**Comment by Juan379** [comment]
Hola! Sigo teniendo dudas yo con este punto. El enunciado solo especifica que en el **Menú de compra de vehículos** este tiene que dar la opción de poder comprar o volver.
Sin embargo, cuando un usuario crea una nueva partida dese el _Menú de Sesión_, se le pide automáticamente que eliga un nombre, equipo, vehículo y nombre para el vehículo. Estas opciones en teoría no son menús pedidos por el enunciado y son mas bien "prompts" que derivan del _Menú de Sesión_ por ende mi pregunta es la siguiente:

Cuando un usuario crea una nueva partida, puedo hacer que el eliga su nombre, equipo, vehículo de elección (lo esta eligiendo sin costo no esta comprando uno desde el Menú de compra de Vehículo) y nombre para este vehículo sin tener la opción de volver atrás?

Posteriormente entraría al **Menú Principal** donde si tendría la opción de volver atrás (pero el usuario ya quedaría guardado en los archivos pertinentes con la información mencionada)

Gracias!

**Comment by naviera** [comment]
Hola, lo que yo hice para no tener el problema de tener guardado un piloto sin un vehículo fue ofrecer el menú de crear piloto, luego ofrecer volver o crear vehículo, y si crea el vehículo ahí recién guardo el piloto y el vehículo en los csv. Esto implica que si crea el piloto y luego no crea el vehículo, el piloto no se guarda en el csv, es esto válido?
gracias!

**Comment by jeschuwirth** [comment]
Hola @naviera,

Si es válido :)

Te recuerdo colocarlo lo más corto posible en el readme y luego citar esta issue para evitarte problemas.

Saludos!
