### ISSUE TITLE
Puntaje de nivel perdido

### ISSUE THREAD

**Issue by FranciscoPinto1138** [IIC2233/Syllabus#194]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Holaa, mi duda es si el puntaje que se obtiene en un nivel en el que se pierde es 0 o se calcula usando la fórmula dada. Gracias.

**Comment by svilaza** [comment]
Hola @FranciscoPinto1138! Las dos opciones son validas por lo que queda a criterio del estudiante cual forma implementar, en cualquier caso es importante mencionar en el README cual forma se implementó. Saludos!
