### ISSUE TITLE
Sobre densidad de contenidos de interfaz gráfica

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2233/syllabus#194]
Hola. Recién publicaron los contenidos de interfaz gráfica, por lo que les eché un vistazo. Me preocupa la cantidad de información que tienen, ya que mañana sale la tarea 2, y es casi imposible aprender tanto sobre PyQt en tan poco tiempo. Por esto, propongo que den un set de ejercicios para ejercitar el uso de PyQt. Esto ayudaría enormemente a procesar toda la información descrita en los contenidos, y facilitaría mucho el avance en la tarea 2 (que muy seguramente va a tener una dificultad mucho mayor a la tarea 1).

**Comment by Hernan4444** [comment]
¡Hola! ✋ 

Primero es necesario aclarar un punto: según el calendario de clases, la tarea se sube oficialmente el domingo. De llegar a subirse antes, es solo porque el enunciado quedó refinado con anticipación y optamos por subirlo apenas pudieramos. Así, podrán leer el enunciado con más tiempo. Pero reitero que la fecha oficial es el domingo y no mañana. Por otro lado, te recomiendo revisar el material extra donde hay buenos ejemplos para aprender PyQt5 😄.

En relación al set de ejercicios solicitado: el curso cuenta con todas las actividades desde el 2015-1 hasta 2018-1. A continuación te dejo un link directo a cada actividad de interfaz, **pero ordenado según lo que considero que más te puede servir con el fin de practicar PtQt5 para la T02.**  Agregué un comentario en lo que creo que te puede servir hacer esa actividad. 

> **Importante**: Todas involucran de un modo u otro crear un _backend_ para procesar la información y un _frontend_ para permitir la interacción con el usuario, solo que dada la temática de la actividad, algunas creo que ponen en práctica más un contenido que otro y ese contenido es el que agregaré como comentario en cada actividad

1. [2018-2](https://github.com/IIC2233/syllabus-2018-2/blob/master/Actividades/AC10/Enunciado.pdf) Sirve para practicar movimiento en la interfaz.
2. [2017-2](https://github.com/IIC2233/Syllabus-2017-2/blob/master/Actividades/AC11/ac11-iic2233-2017.pdf) Sirve para practicar la creación de interfaz con muchos elementos que cambian cada cierto tiempo.
3. [2018-1](https://github.com/IIC2233/Syllabus-2018-1/blob/master/Actividades/AC10/AC10.pdf) Sirve para el manejo de _layout_ y _labels_.
4. [2016-1](https://github.com/IIC2233-2016-1/syllabus/blob/master/Actividades/AC11/Actividad%2011.pdf). Sirve para poner en práctica `hide` y `show` para una interfaz que varía según las acciones.
5. [2016-2](https://github.com/IIC2233-2016-02/Syllabus/blob/master/Actividades/AC11/main.pdf) Sirve para poner en práctica la lógica de 2 jugadores.
6. [2015-2 QtDesigner](https://github.com/IIC2233-2015-2/syllabus/blob/master/Actividades/AC20/Enunciado/main.pdf) Sirve para poner en práctica la creación de un formulario con diferentes _inputs_.
7. [2017-1](https://github.com/IIC2233/Syllabus-2017-1/blob/master/Actividades/AC11/Enunciado.pdf) Sirve para poner en práctica una interfaz con una lógica de _backend_ más elaborada. 
8. [2015-1 QtDesigner](https://github.com/IIC2233-2015-1/syllabus/blob/master/Actividades%20en%20Clases/Actividad%2018/Enunciado.pdf) Crear interfaz con diversas acciones a realizar según el _input_ ingresado por el usuario
9. [2015-2 PyQt](https://github.com/IIC2233-2015-2/syllabus/blob/master/Actividades/AC19/main.pdf) Sirve para poner en práctica botones que cambian contenido de forma dinámica.
10. [2015-1 PyQt](https://github.com/IIC2233-2015-1/syllabus/blob/master/Actividades%20en%20Clases/Actividad%2017/actividad%2017.pdf) Sirve para poner en práctica botones que cambian contenido de forma dinámica.

> Recalcar que este orden está totalmente basado en mi experiencia y opinión, y no necesariamente es compartida por cada miembro del cuerpo docente 😅.

Finalmente, en cada semestre, hubo una ayudantía de interfaz gráfica, ahí podrás encontrar más ejemplo de mini códigos con los cuales puedes practicar PyQt5 y ver los efectos de ir modificando dichos códigos.

Saludos ✌️
