### ISSUE TITLE
ayudantia 4  keyError vs ValueError 

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2233/Syllabus#194]
hola!
no me queda clara la distinción que se hizo para keyError y ValueError en el siguiente extracto del codigo de la ayudantía, ¿Podrían ser los 2 un ValueError?

 def add_course(self, course, section):

        if  '  '  in course:
            raise KeyError('Ingrese una sigla sin espacios entre medio')
            
        if  'section'  in section: 
            raise ValueError('la seccion debe ser solo un numero')

**Comment by nmaturana97** [comment]
Tecnicamente, que no vaya un espacio ahi es un ValueError. Por otro lado, estamos llamando despues a un diccionario con llave course, por lo que no existe la llave y eso es un KeyError.

**Comment by fringlesinthestreet** [comment]
Hola @joaquineichholz 

Efectivamente esa excepción corresponde a un `ValueError`, ya que la función está hecha para recibir un string con cierto formato pero lo recibió con uno incorrecto.

Sin embargo, ese semestre (tal como se dijo en ayudantía) se evaluaba que se levantaran las excepciones que "naturalmente" se levantarían, sólo personalizando el mensaje que se muestra.

Es por esto que en la ayudantía se levanta un `KeyError` en vez de un `ValueError`, pero semánticamente estás en lo correcto!
