### ISSUE TITLE
Problema con vscode

### ISSUE THREAD

**Issue by tamyhan** [IIC2233/syllabus#194]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

[Hola, desde hace unos días que cada vez que abro vscode el computador me empieza a sonar muy fuerte como si estuviera corriendo un programa. Sin embargo, he revisado varias veces cuando me pasa eso y no estoy ejecutando nada. 
Cuando me empieza a sonar, me meto al monitor de actividad y aparece como que Python me está usando más del 100% de la CPU. Qué hago para que no me pase eso? No se por qué algo como que se activa y empieza a usar python]

**Comment by igbasly** [comment]
Hola @tamyhan :v:

Por lo que me cuentas, pareciera ser que VSCode ejecuta Python al encender por algún proceso o extensión instalado. Según lo que estuve leyendo, es posible que se pueda arreglar agregando algunas configuraciones de VSC.
Para ello, debes hacer lo siguiente:
1. Ve al menú `Code` del programa y accede a `Configuraciones` (o Settings).
2. Ahí en el menú lateral izquierdo, ve a `Extensiones`.
3. Busca la extensión `Python`.
4. Dentro de sus configuraciones, busca `Python: Language Server` y selecciona `Jedi`.
5. Dentro de las mismas configuraciones de Python, ahora busca `Python: Jedi Memory Limit` e ingresa `0`.
6. Reinicia VSCode.

Intenta haciendo estos pasos y coméntame cómo funciona. Quedo atento 😉.
Ian.

**Comment by tamyhan** [comment]
Hola!! Intenté hacer lo que me dijiste, pero los ajustes ya estaban así de antes, y después de un rato de abrir vscode me volvió a pasar lo mismo.

**Comment by igbasly** [comment]
Entiendo, seguí buscando al respecto y pareciera ser que esto lo hace VSCode al reconocer que hay ciertos archivos dentro del espacio de trabajo que necesitan Python. Ahora, se supone que debería suceder al iniciar el programa y detenerse luego de unos minutos. ¿Sucede que se detiene después de unos minutos o el proceso sigue durante todo el uso de VSC?

Dentro de las recomendaciones que logré encontrar, lo más "fácil" para detectar que está generando este problema es desactivar todas tus extensiones e ir iniciándolas de a una, hasta encontrar aquella que es responsable de esto.
Para hacer lo anteriores, debes hacer lo siguiente:
1.  Ir al menú `Code´ -> `Preferencias` -> `Extensiones`.
2. Te abrirá un panel con todas las extensiones, sobre la barra de búsqueda a la derecha habrá un menú de 3 puntitos `...`. Debes hacer click y seleccionar `Desactivar todas las extensiones`.
3. Si tu PC sigue con el ventilador al máximo y la CPU al 100%, cierra VSCode, espera a que tu computador se enfríe e inícialo nuevamente.
3. En el mismo menú `...` ingresa a `Vistas`(Views) y selecciona `Instaladas`(Instaled) y `Desactivadas` (Disabled).
4. Luego en la lista de extensiones que ahí aparece debes ir **una a una** ingresando en el engranaje y seleccionado `Activar`(Enable).
5. Cada vez que actives una extensión, intenta modificar por unos minutos algún archivo de python con tal de analizar con qué extensión es que Python se activa.

Hasta ahora es lo mejor que he encontrado para detectar el problema, te invito a que lo intentes y me comentes tus resultados.

**Comment by tamyhan** [comment]
Parece que funcionó! Muchas gracias!! :)
