### ISSUE TITLE
Incluir prints adicionales en buscar_y_plantar

### ISSUE THREAD

**Issue by dathmaru** [IIC2233/Syllabus#194]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Quería saber si es posible realizar los print de éxito o fallo al plantar los cultivos directamente desde el método buscar_y_plantar, para así poder incluir en el mensaje el predio en el que fue plantado el cultivo. Mi duda en concreto es si esto va a interferir o no con los tests al momento de corregir la tarea. Gracias!

**Comment by vgalfaro** [comment]
Hola! te recomiendo que no agregues prints a las funciones que no lo pidan, ya que éstas tienen un return específico y puede que intervenga con los tests, saludos!
