### ISSUE TITLE
Como usar .gitignore

### ISSUE THREAD

**Issue by enriquerussi** [IIC2233/syllabus#194]
Hola, quisiera saber como utilizar técnicamente el comando .gitignore

**Comment by YehudaGurovich** [comment]
.gitignore no es un comando... es un nombre de un archivo que tiene extensión .gitignore (va sin nada antes del punto). En la issue #88 (compilado) sale que en la issue #93 y #119 hablan del .gitignore. La idea de la issue #88 es revisarla antes de abrir nuevas issues porque puede ser que ese tema ya se está tratando en otra issue.

**Comment by DCCollao** [comment]
Muchas gracias por la respuesta, @YehudaGurovich. Respecto a cómo crear un `.gitignore`, puedes escribir `touch .gitignore` en la gitbash.
