### ISSUE TITLE
Librerías Permitidas y No Permitidas

### ISSUE THREAD

**Issue by stephichau** [IIC2233/Syllabus#194]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:

> ¿Puedo usar la librería {nombre_librería} para hacer {explicación_de_lo_que_quiero_hacer}?

¡Recuerden especificar en su README qué librerías utilizan!

---
## **Librerías Permitidas**
- os
- random
- sys.exit
- string
- copy
- abc
- PyQt5

## **Librerías Prohibidas**
- re
- collections
- simpy
- pickle
- json
- csv
- numpy
- codecs
- yield (y cualquier generador)
- UserDict

## **Built-ins prohibidos**
- eval (:skull:)
- exec (:skull:)
- _list comprehension_

## **ESPECIALMENTE PROHIBIDO**
- listas
- diccionarios
- tuplas
- sets
- En general, estructuras de datos de este tipo provistas por python

En caso de tener problemas con funciones que retornen alguna de las estructuras prohibidas, deben poder llevarlas a sus propias estructuras. [(ver esto)](https://github.com/IIC2233/Syllabus/issues/195)

**Comment by felipesanchezvaras** [comment]
La librería csv se puede o no se puede usar ?

**Comment by stephichau** [comment]
@felipesanchezvaras prohibida , disculpa la confusión

**Comment by dialvarez1** [comment]
¿El que las comprensiones de lista estén prohibidas incluye también a todo tipo de generador?
Por ejemplo, ¿es válido esto?:
`MyList(i ** 2 for i in range(10))`

**Comment by hanavarrete** [comment]
@dialvarez1  no se pueden usar generadores! Saludos

**Comment by rihanuch** [comment]
A que se refieren con un "generador"?

**Comment by sebacruzd** [comment]
@rihanuch con lo que preguntó @dialvarez1, por ejemplo. Está en los contenidos del curso, pero aún no se ven y no están permitidos porque trabajar con ellos sería casi equivalente a tener listas y se perdería toda la idea de la tarea.

**Comment by rihanuch** [comment]
@sebacruzd pero yo puedo definir mi propia lista con listas enlazadas ! Ademas el enunciado dice que podemos hacer nuestras nuestras propias clases de "estructuras" que imiten a las dadas por python!!! No que no se puede usar nada del estilo, solo dice que no se pueden utilizar las *dadas*

**Comment by sebacruzd** [comment]
@rihanuch, creo que no tienes claro el concepto de generadores.
Un generador, por ejemplo, es algo así:
`(i for i in range(10)) `
@dialvarez1 le entregó un generador como argumento a una clase. Eso no se puede hacer a menos que sea desempaquetando los valores (como ya es explicado más arriba).

Lo que sí pueden usar son clases creadas por ustedes para imitar comportamiento de edd's de python, o crear edd's con comportamientos que necesiten.

Espero haber aclarado tu duda.

**Comment by ptflores1** [comment]
para la implementacion de` __getitem__` ` __setitem__` ` __delitem__` se puede usar indexación como `my_objeto[1,2]` ya que al recibir el `1,2` es en forma de tupla, obviamente lo primero que hare en los metodos sera desempaquetarla y no trabajarla como tal

**Comment by depedraza** [comment]
Asumo que tampoco se podrá utilizar la librería UserDict para la implementación de mi clase de diccionario "MiDiccionario"? o sí? :0

**Comment by sebacruzd** [comment]
@depedraza no se puede, saludos!

**Comment by SarahEverke** [comment]
para implementar el iterado puedo usar yield?

**Comment by mundurragac** [comment]
Se puede usar la libreria de numpy para hacer las matrices de adyacencia en grafos??

**Comment by sebacruzd** [comment]
@mundurragac no se puede.

**Comment by sebacruzd** [comment]
@SarahEverke si se puede.

**Comment by iqacevedo** [comment]
@SarahEverke no se puede usar yield.

Saludos !

**Comment by josefinabengoa** [comment]
Se puede usar codecs para abrir el archivo y luego usar mis propias estructuras para leerlo?

**Comment by aleuribej** [comment]
No es una libreria pero queria saber si esta permitido ocupar for i in range() ? O se debe hacer ocupando mis propias estructuras?

**Comment by iqacevedo** [comment]
@aleuribej si puedes!

**Comment by glbello** [comment]
no se si sea una librería, pero ¿puedo usar ```zip```? para hacer 
``` python
for i, j in zip(lista1, lista2)
```

**Comment by behrmann97** [comment]
Hola, ¿ puedo usar sys.stdout para evitar ciertos prints?

**Comment by Fhguinez** [comment]
time está permitido? lo quiero usar para sacar el borde resaltado después de unos segundos de presionada a tecla 'h'
