### ISSUE TITLE
Duda nombre de usuario

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#194]
Un nombre de usuario que empieza con espacios es válido? Y que pasa si el nombre de usuario esta constituido SOLO por espacios? Se debe aceptar o rechazar?
Ejemplo:
1)          hola       
2)                
Las 2 líneas de arriba serían ambas válidas como nombre de usuario? (Me acabo de dar cuenta que github borra los espacios innecesarios, pero el 2do nombre son 5 espacios seguidos y nada más)

**Comment by gatochico** [comment]
Hola! 
Quedará a tu criterio si deseas aceptar o prohibir dichos nombres de usuario. Recuerda poner tu decisión en el README, para que sepamos que nombres poner y cuales no :sunglasses: .

Un tip para que tomes en cuenta en tu decisión: si ocupas el método `strip()` para strings en alguna parte del manejo de usuarios, puede que tengas problemas con usuarios cuyo nombre sean unicamente espacios en blanco, ya que `strip` por defecto (cuando no defines otro carácter como argumento) borra dichos espacios :scream: . 

Saludos y éxito!
