### ISSUE TITLE
Duda respecto a si el jugador gana o pierde 

### ISSUE THREAD

**Issue by Sebastian-Assereto** [IIC2233/Syllabus#194]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas, una consulta respecto a si el jugador gana o pierde en las batallas, resulta que leí algo en una issue, pero igualmente quedé con la duda, el tema es que si el jugador gana o pierde, le di 2 opciones, que cierre el juego (es decir que el programa acabe) o que regrese al menu de início para elegir a otro entrenador y volver a jugar.
No sé estoy en lo correcto al haber hecho eso, yo consideraría que si, ya que al jugar no le veo lo raro a directamente cerrar el juego apenas aparece el mensaje de perdida o victoria, y así no tener que volver al menu de início, puedo mantener esta parte así?
Saludos

**Comment by Amandasandov** [comment]
Hola, lo más correcto es que tras ganar o perder se de la opción de volver al menú de inicio o salir, pero como no está especificado en el enunciado, las dos maneras son aceptables. Suerte.
