### ISSUE TITLE
Valores hielo y rocas

### ISSUE THREAD

**Issue by itplanella** [IIC2233/syllabus#195]
Hola! Al momento de probar mi codigo, casi nunca los contrincantes ni mi piloto se ven afectados por el daño (en caso de automovil, troncomovil y motocicleta) ni por el hielo, debido a que los valores de HIELO y ROCAS en pistas.csv son muy bajos en comparacion a los valores de carroceria de los vehiculos y contextura de los corredores. Por esto se complica bastante la prueba del codigo ya que nunca se verian afectados y los tiempos en todas las vueltas son los mismo. Agradeceria mucho si me respondieran si es posible cambiar los valores de HIELO y ROCAS en las pistas para poder realizar mas pruebas del codigo. Muchas gracias.

**Comment by itplanella** [comment]
Algo similar ocurre con la probabilidad de accidente, donde en la mayoria de los casos se hace 1 y todos quedan descalificados en la primera vuelta.
La única manera de cambiar esto es cambiando los valores de los ponderadores, sin embargo, probando con distintos valores, los que tengo actualmente me sirven en otra parte ya que al poner otros valores las diferencias en tiempos de vueltas es mucha (un corredor demora 100 y otro 76000). Quizás seria mejor si se dieran los valores que se deben usar en los parámetros.
Gracias de antemano y disculpa si no se entiende mucho la redacción.

**Comment by itplanella** [comment]
Algo similar pasa con la probabilidad de accidente, solo que en este caso casi siempre arroja 1. Para que eso cambie tendria que cambiar los parametros, sin embargo, despues de mucho probar logre usar parametros que no generan diferencias tan grandes en las velocidades de los vehiculos (unos iban a 150 y otros 76000). Por lo que arreglar los parametros para arreglar la probabilidad de accidente generaria problemas en otra parte. Quizas si se nos dieran los parametros seria mas sencillo. Disculpen la extension y espero se entienda. Gracias de antemano.

**Comment by DCCollao** [comment]
Hola! 

Para probar tu código puedes hacerlo con los valores y parámetros que estimes convenientes, como también podrías modificar las fórmulas  aumentando o disminuyendo ponderaciones. Lo anterior corre solamente para el testeo del código, pues al momento de entregar, las fórmulas deben ser las que fueron pedidas en el enunciado. 

Por último, no podemos entregarte valores para que testees, ni revelar cuáles serán utilizados.
Mucho éxito!!
