### ISSUE TITLE
Duda sobre excavadores iniciales y arena inicial

### ISSUE THREAD

**Issue by SantiagoOsorio3** [IIC2233/Syllabus#195]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

**### Duda**

Hola ! entiendo que en excavadores iniciales y arena inicial debe elegir un numero aleatorio y una arena tambien de forma aleatoria. Sin emabrgo, despues de eso, en el caso que la arena sea rocosa, debo denuevo de manera aleatoria elegir dentro de las arenas que se encuentran en mi archivo arenas.csv, una arena rocosa y todas sus propiedades respectivamentes, y esa sera mi arena inicial ?? o como se hace ?
En el caso de los tabajadores_iniciales, si es que me dio por ejemplo 3, mis 3 trabajadores seran los 3 primeros que se encuntran en el archivo trabajadpres.csv ??

**Comment by mpiavf** [comment]
Hola! Efectivamente es así en el caso de la arena, en el caso de los excavadores puedes definir el parámetro `CANTIDAD_EXCAVADORES_INICIALES` según estimes conveniente, respetando el rango pedido en el enunciado, y luego dependiendo de esta cantidad y de manera **aleatoria** seleccionas a los excavadores, no necesariamente los primeros del archivo. Le puedes dar una mirada a las issue #139 y #140 para que te quede más claro.
Saludos!
