### ISSUE TITLE
Act 6, Método me dicen que es un bool

### ISSUE THREAD

**Issue by crvargasu** [IIC2233/syllabus#195]
Hola, Estaba haciendo la actividad 6 y se me presentó el siguiente error

![4](https://user-images.githubusercontent.com/48322767/57540115-eda68280-7319-11e9-8621-7e0dc6a2a7b0.PNG)

Cuando mis dragones intentan entrar por segunda vez al método comer(), me dice que este es un bool. ( La primera vez que lo hacen funciona bien )

Comer() es un método de la clase dragon, el cual se llama dentro del método run() de la clase dragón (llamo a un método en otro método de la misma clase)

El método comer está definido de la siguiente manera

![1](https://user-images.githubusercontent.com/48322767/57540370-9359f180-731a-11e9-9abf-8200c5f0df5b.PNG)

La parte del Método run(), donde se llama a comer():
![2](https://user-images.githubusercontent.com/48322767/57540426-b389b080-731a-11e9-90bb-68de17879210.PNG)

Y el método convencer (que se llama en el método comer), es de la clase Dany(), el cual está definido de la siguiente manera:

![3](https://user-images.githubusercontent.com/48322767/57540497-dd42d780-731a-11e9-9bc1-d96853fc78fe.PNG)

No sé porque toma como bool el método comer cuando un dragón entra por segunda vez

**Comment by entamburini** [comment]
En `convencer` haces `dragon.comer = False` haciendo un overriding a tu método 👀

**Comment by crvargasu** [comment]
Gracias! No me habia dado cuenta
