### ISSUE TITLE
Error al importar módulos

### ISSUE THREAD

**Issue by masoto22** [IIC2233/Syllabus#195]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda sobre un error que me aparece, que antes no me sucedía pero creo que era porque VS Code estaba utilizando Python 3.7, luego lo desinstalé e instalé nuevamente Python 3.8, y en la cmd volví a instalar pyqt5 y pyqt5, pero me sigue apareciendo una línea roja bajo estos from, pero no entiendo pq :( 

Gracias
![Screenshot_2](https://user-images.githubusercontent.com/48321094/168695891-438b64fa-61a3-4df3-b979-624ca3a5008e.jpg)

**Comment by diegocostares** [comment]
Como volviste a instalar pyqt5? Si aparece asi es porque probablemente volviste a instalar pyqt en la version 3.7 que quedo como predeterminada, te recomiendo que le eches un ojo al siguiente [link](https://es.stackoverflow.com/questions/324183/instalar-y-direccionar-librerias-para-dos-versiones-de-python-instaladas)

_PD: También te recomiendo que intentes con la versión 3.8.10, funciona mejor_
_PD2: Si nada de eso funciona, puedes tratar de desinstalar la versión antigua de tu computador (Tampoco es bueno tener muchas versiones gastando memoria)_
