### ISSUE TITLE
'return' en la mitad de un ciclo

### ISSUE THREAD

**Issue by tqmbanados** [IIC2233/syllabus#195]
Hola!
Tengo una pregunta bien simple. ¿Es correcto usar return en una función en la mitad de un ciclo? ¿O es mejor esperar a que el ciclo termine antes de retornar?

**Comment by dchahuan** [comment]
Se puede hacer y es correcto solo tomar en consideracion que el return corta la funcion y no se ejecuta mas codigo despues de que es llamado.

**Comment by tqmbanados** [comment]
Gracias!

**Comment by dchahuan** [comment]
Ey te abri el issue por si un compañero tuyo tiene una duda similar lo pueda ver. Trata de no cerrar issues
