### ISSUE TITLE
T02 seccion 4.1.2. Consultas y estadisticas: el fichaje estrella

### ISSUE THREAD

**Issue by jachavarri** [IIC2233/Syllabus#195]
Hola! Tengo la duda de que en esta parte dice:

    "Considera a todos los jugadores con grado 1 de relación, es decir todos los amigos cercanos o amigos lejanos o conocidos."

Pero más arriba dice que los de grado 1 son mejores amigos solamente, no amigos lejanos ni conocidos. ¿De qué forma lo consideramos?

**Comment by cilopez** [comment]
Un **punto** de afinidad es **distinto** a un **grado**, un grado de relación es el numero de aristas que existen entre dos jugadores. Por ende si es un grado de relación  considerarás en este cálculo a todos los jugadores que sean **mejores amigos solamente o amigos lejanos o conocidos**.

**Comment by Pipelao** [comment]
Hola @cilopez 
Sigo sin entender cómo se obtiene el fichaje estrella. Pienso que dado el nombre de un jugador se ve la afinidad con todos los jugadores y los que tengan afinidad 1 se les calculará la chispeza y aquel que tenga mayor chispeza será el fichaje estrella. El problema es que me demoraría mucho tiempo calculando la afinidad con todos los jugadores.
Gracias de ante mano, Saludos.

**Comment by cilopez** [comment]
- Como mencione antes, solo considerarás en este cálculo a todos los jugadores que sean mejores amigos solamente o amigos lejanos o conocidos. Es decir en un jugador solo analizas los jugadores que están relacionado directamente con este. 
- Si Alexis tiene relación solo con Vidal y Medel, solo uno de esos puede ser el fichaje estrella, los que no estén relacionados directamente no cuentan.

**Comment by Pipelao** [comment]
Ahh perfecto, ahora lo leí bien y lo entendí, disculpa por haberte preguntado por algo que ya habías explicado, aunque con el ejemplo me quedó mucho más claro.
Gracias @cilopez

**Comment by cilopez** [comment]
@Pipelao  de nada , no te disculpes por las preguntas siempre sirven .

**Comment by beayancan** [comment]
Una pregunta respecto de lo mismo, ¿debo considerar a todos los jugadores que presenten alguna relación con el jugador para calcular el que tenga  mayor chispeza o debo ir considerando solo los que presenten mayores grados de afinidad?

Por ejemplo: Alexis tiene como amigos a Vidal y Messi. Con Vidal existe una afinidad 1 y con Messi 0.9. Donde si calculo la Chispeza, Messi tiene una chispeza mayor que Vidal, con lo cual ¿el fichaje estrella debe ser Messi?
