### ISSUE TITLE
Form de atraso

### ISSUE THREAD

**Issue by matix3000** [IIC2233/Syllabus#195]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]
Hola buenas!
Disculpen quería preguntar donde estaba el form para informar atraso?
Un saludo y muchas gracias!

**Comment by Dominique236** [comment]
Hola! 
El _form_ de atraso se habilita luego del plazo de entrega. Más tarde se enviará un aviso sobre esto.
Cuéntame si respondí tu duda y suerte en tu tarea! 😊

**Comment by matix3000** [comment]
Ah perfecto, muchas gracias! y perdón, quizá entendí mal, pero avisar atraso, no quiere decir que uso mis cupones, esos se usan solo para que el atraso no me quite nota no? o sea puedo tener tantos atrasos quiera en las tareas
