### ISSUE TITLE
Funciones que retornan estructuras prohibidas

### ISSUE THREAD

**Issue by stephichau** [IIC2233/Syllabus#195]
Si necesitas usar alguna función perteneciente a algún módulo de la librería estándar de Python que
retorne alguna de las estructuras prohibidas, deberás desempaquetar los valores de la estructura mediante el operador * y luego usarlos en tu propia implementación. Por ejemplo, el siguiente código es válido:

```python

class MiLista:

    def __init__(self, *args):
        for arg in args:
            # do something
            pass


separa2 = "lorem ipsum dolor sit amet".split(" ")
lista_legal = MiLista(*separa2)
lista_legal.mi_append("consectetur")
```

**Comment by Mariana-Ortega-del-Rio** [comment]
No me queda claro en qué caso puedo ocupar las "estructuras prohibidas" si enverdad puedo ocuparlas y después las desempaqueto. ¿Podría sacar la información de los csv ocupando listas mientras después las desempaquete y las use en mi propia implementación?

**Comment by gabrielpinkman** [comment]
No entiendo bien tampoco qué es lo que realiza el operador * antes de la lista, significa que le paso muchos argumentos a mi lista? Cómo es que se deberìa hacer eso?

**Comment by gabrielpinkman** [comment]
ya entendí, gracias!

**Comment by B-Dominguez** [comment]
Hola, se puede usar un
_for i in range(x):
    pass_
y puedo usar
_def func_1():
    rerturn a, b
a_proc = func_1[0]
b_proc = func_2[0]_
?
