### ISSUE TITLE
Duda con respecto a las probabilidades de las subclases

### ISSUE THREAD

**Issue by cholalat** [IIC2233/Syllabus#195]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola!
Al momento de implementar la clase paladin, me dicen que hay una PROB_PAL de usar sus poderes de caballero. Esto significa que de usar los poderes de caballero, tengo que usar el PROB_CAB para ver si se usa un ataque especial propio de la clase caballero o directamente uso el ataque especial de la clase caballero, sin tener que calcular PROB_CAB. Esta pregunta aplicaría tambien para la clase MagoDeBatalla y  CaballeroAracano.

**Comment by tebi01** [comment]
Hola! @cholalat
La idea de la tarea, es que dejes que la decisión se tome de tal manera, que al cumplir la condición del evento (se cumple la probabilidad), tu ```Combatiente``` llame directamente al método de su Clase Padre.

Para esto, te puedo sugerir utilizar la siguiente notación:
```super.(ClasePadreElegida, self).metodo()```
Esto hará que se llame a la función ```metodo()``` de la clase ```ClasePadreElegida```.

Si no te parece, puedes manualmente escribir el código de ataque y dejar muy clara la forma en la que interpretaste tu idea en tu archivo ```README.md```. (Ya sea que directamente se active el poder de ```Caballero```, o si se vuelve a calcular la probablilidad ```PROB_CAB```).

Espero haberte ayudado!

**Comment by cataruze** [comment]
Hola, todavía no entiendo bien a que se refiere PROB_PAL, si es que se refiere a que use las habilidades de caballero, que pasa si no cae en esa probabilidad?, sigue actuando como caballero o como guerrero?

**Comment by tebi01** [comment]
Hola nuevamente! @cataruze 

```PROB_PAL``` debería funcionar tal que, si se cumple tal probabilidad, se active el método de ataque de un ```Caballero```. De lo contrario, atacará como un ```Guerrero``` (ataque default sin poderes especiales).

Va en ti el cómo funciona el método de ataque de un ```Caballero```, si dentro de este método incrustas la probabilidad ```PROB_CAB``` o asociados, o si directamente usas esa condición fuera, y tienes dos métodos de ataque (uno de ```Caballero``` y otro de ```Guerrero```) para cada caso. Personalmente, te recomiendo la última opción, pero como dije, si prefieres utilizar alguna interpretación de tu gusto, puedes incluirla y justificarla en tu archivo ```README.md```, en su apartado correspondiente.

**Comment by Drpinto1** [comment]
¡Hola!

Complementando las respuestas de @tebi01 y en caso que la duda sea un poco más conceptual que de código, `PROB_PAL` será un valor entre 0 y 100, que indica que porcentaje de las veces el paladín atacará como un `Caballero`.

Por ejemplo, si tienes el parámetro `PROB_PAL = 20`, cada vez que el paladín atatque, tendrá un 20% de probabilidad de atacar como `Caballero` y un 80% de probabilidad de atacar como `Guerrero`

Cuéntame si queda más claro :)
