### ISSUE TITLE
mi tarea tiene varios archivos .py

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2233/syllabus#195]
hola mi tarea tiene varios archivos .py no me quedó claro como señalar cual es el primero que se ejecuta para que funcione el programa.
Solo en el REadme?

**Comment by Tito0906** [comment]
Holaa @vice-rosas99, tal y como dices, solo debes dejar claramente explicado en el README la manera en que se debe correr tu tarea. Esto incluye cual/es archivos se deben correr para hacerla funcionar. Para todo esto, junto con otra información de su tarea, se les entregó un archivo README.md que ustedes pueden completar con los datos según corresponda.

Saludos y éxito en la tarea!

**Comment by vice-rosas99** [comment]
ok muchas gracias
