### ISSUE TITLE
Contagiar a otros paises

### ISSUE THREAD

**Issue by gbordoni** [IIC2233/Syllabus#195]
Buena cabros
Tengo un problema; no estoy logrando infectar a otros paises desde el pais de origen. Revise el codigo y parece estar bien, y ahora revise la formula de 3.6 y cache que ahi esta el problema. 
La gente infectada (en el numerador) es muy poca al inicio. A medida que va creciendo, esta crece y crece, y en poco tiempo llega a ser practicamente igual a la poblacion viva (en el denominador). Ahora, en el mejor de los casos van a ser iguales por lo que podriamos simplificar esos dos terminos, quedandonos que la probabilidad es **(0.07 / nro. conexiones)** lo cual sigue siendo bajisimo, casi despreciable, y creo que por eso la enfermedad no se expande. Les hace sentido?

**Comment by JoseValencia125** [comment]
Tengo el mismo problema, en el mejor de los casos la probabilidad es de un 0,07% (considerando toda la gente infectada, ningún muerto y solo una conexión) la cual es bajisima y no permite la continuidad en el juego

**Comment by ranieto** [comment]
Estoy bastante seguro que 0.07 = 7%

**Comment by arturodelreal** [comment]
@ranieto Efectivamente es un 7%

**Comment by gbordoni** [comment]
@arturodelreal Es un 7% en el **mejor de los casos posibles** ; casi siempre es menor al 1% ...

**Comment by acrojas2** [comment]
@arturodelreal  entonces la probabilidad seria:
               P(contagio) = min((7 * g.infectada_pais/(g.viva*conexiones)),1)
con respecto a conexiones en esta formula: son las que están abiertas (tanto aereas como terrestres) en el momento o las que hay inicialmente (todas las conexiones, tanto aereas como terrestres)?

**Comment by arturodelreal** [comment]
Son todas las conexiones abiertas, aéreas y terrestres.

**Comment by JMOrellana** [comment]
Hola! Tengo la siguiente duda, se supone que un país limpio es contagiado por uno infectado cuando la probabilidad de contagio es igual a 1 o se determina de una forma distinta? Porque según la fórmula dada creo que la probabilidad no será igual a 1 nunca ): 

Gracias de antemano!

**Comment by iqacevedo** [comment]
Hola,

@JMOrellana se determina de forma distinta, la probabilidad es que tan probable es que ocurra un 
determinado suceso de un evento aleatorio. En tu programa debes encontrar la manera de simular esta probabilidad (en cualquier día un país infectado que tenga la manera de conectarse a uno no infectado puede infectarlo, la probabilidad solo lo hará mas o menos probable, cuando es 0 tienes certeza de que no ocurrirá, mientras que cuando es 1 ocurre si o si.)

Espero quede claro.
Saludos !
