### ISSUE TITLE
Problema con kernel

### ISSUE THREAD

**Issue by gonzaga2000** [IIC2233/syllabus#195]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Cuando ejecuto algún código que tenga setter o getter, osea algún self.__valor, me sale una ventana de error con el siguiente mensaje: "Error: Direct kernel connection broken". Alguna forma de solucionarlo?

**Comment by igbasly** [comment]
Hola @gonzaga2000 :v:

Necesitaré un poco más de contexto de tu error, ¿A qué te refieres con "ejecuto algún código"? ¿Lo haces en VSCode, en la terminal, en un notebook de jupyter?

Quedo atento a la información :smile:
Ian.
