### ISSUE TITLE
Se puede heredar de estructuras prohibidas?

### ISSUE THREAD

**Issue by MrEarle** [IIC2233/Syllabus#196]
Al crear una clase para tener mi propia implementación de una lista (por ejemplo), se puede heredar de la clase list?

**Comment by FernandoPieressa** [comment]
Hola! No se puede.

Saludos!

**Comment by sebacruzd** [comment]
Hola,

La idea de esta tarea es que no se utilice ninguna estructura de datos de python.
Por lo tanto, es su deber crear las clases que les acomoden para realizar la tarea. A la vez, estas clases deben ser pensadas eficientemente (esto será evaluado).
