### ISSUE TITLE
Energia Excavador

### ISSUE THREAD

**Issue by rafarencoretg** [IIC2233/Syllabus#196]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo una pregunta, si mi excavador tiene por ejemplo 2 de energía y si lo manso a cavar, realiza un gasto de energía de 4, la energía me quedaría en -2 (0 porque la energía va entre 0 y 100). Mi pregunta es, ante un caso así, lo mando a cavar igual, sabiendo que se puede dar ese caso, o chequeo que hay "energía disponible para gastar" antes de dar la orden cavar()?

**Comment by emolaba** [comment]
Hola @rafarencoretg ! Si le queda energía, va a trabajar, da igual el resultado de la resta. Si tiene 0 de energía debería estar descansando, entonces, no va a cavar.
Espero haber resuelto tu duda, quedo atento cualquier cosa!
