### ISSUE TITLE
El fichaje estrella: chispeza

### ISSUE THREAD

**Issue by jachavarri** [IIC2233/Syllabus#196]
Hola! Si quiero saber quién es el fichaje estrella del Jugador-1 necesito calcular la chispeza, y supongamos que un candidato es el jugador-2. Luego, ¿para calcular la chispeza se utiliza el overall del jugador-2?

**Comment by cilopez** [comment]
Si así es, se utiliza el _overall_ del jugador 2. Los datos del jugador 1 no influyen en esta consulta
