### ISSUE TITLE
Pauta Control 1: Diagrama de clases

### ISSUE THREAD

**Issue by fvr1** [IIC2233/Syllabus#196]
# Pauta Control 1: Diagrama de Clases

Como no hay un único modelo correcto, hice tres requerimientos que deberían tener todos los modelos de los problemas dados para que se consideren correctos:
**(3 ptos) R1**: Clases, atributos y métodos
- Deberían identificar las clases necesarias para resolver el problema.
     - Problema Programación Avanzada: Instructor, Ayudante (de los cual hereda TPD Jefe Mentor), Profesor, Ayudantía y Cátedra ( que podían contener o heredar Sala de Clases), IIC2233 que contiene a todas las secciones y/o material de clases, Sección que contiene a los instructores Ayudantía y Cátedra.
     - Problema El Agujero: Restaurante, Cocina Baño Piso (opcional), Mesa (encuentro que se ve más bonito y simple con una clase así, pero hay modelos válidos que lo ponían como un int) Jefe Cocina y Administrados (ojalá que heredaran ambos de una clase), Mesero y Ayudante de Cocina (ojalá que heredaran de una clase), Plato, Cliente.
- Deberían identificar los atributos necesarios para herencia, composición y agregación.
    - Si un objeto hereda de otro, no había que escribir los atributos del objeto padre en la clase hija.
    - Si un objeto componía a otro, el otro debía tener un atributo para guardar al objeto.
    - Básicamente el diagrama debía tener los atributos y funciones necesarias para que cuando se pasara a código no tuviese que agregar un atributo o función.

**(1 pto) R2**: Tipos de datos.
- **(0.5 ptos)** por ponerle el tipo de dato a TODOS los atributos.
- **(0.5 ptos)** por ponerle parámetros y retorno a TODAS las funciones.

**(2 ptos) R3**: Composición, herencia y agregación.
- Tenían que identificar correctamente los tres tipos y ojalá justificar algunas relaciones de agregación y composición. Esto puede variar según los supuestos que hicieron.
 - La composición y agregación tiene que ver con la relación de existencia de una clase y otra. Por ejemplo, si uno elimina la clase `A`, que está *compuesta* por la clase `B`, entonces la clase `B` dejaría de existir. Si la clase `B` estuviese *agregada*, entonces al eliminar la clase `A` no se eliminaría la clase `B`
 - Problema Programación Avanzada:
      - Los profesores y ayudantes heredaban de Instructor
      - El instructor estaba agregado a la Sección
      - IIC2233 está compuesto por Secciones
      - La Sección está compuesta por cátedra y Ayudantía
      - La Sala de Clases estaba agregada a la Cátedra y Ayudantía
 - Problema El agujero:
      - El restaurante estaba compuesto por un Jefe de Cocina, Administrador, Meseros, Ayudantes de Cocina, Mesas, Cocina.
      - Los Meseros podían tener agregradas Mesas.
      - Los Platos podían estar agregados a la Cocina y a los Clientes.
      - Las Mesas podían tener agregadas Clientes.
 

### Errores Comunes
1. A muchos se les olvidó la cardinalidad de las relaciones!
1. Algunos dijeron que una clase `A` estaba compuesta por la clase `B`, pero la clase `A` no tenía un atributo para que pudiese efectivamente contener a la clase `B`.  Visto en código, uno no hubiera podido acceder a la clase `B` a partir de la clase `A`.
1. Si las clases `B` y `C` heredan de `A`, no era necesario redefinir los atributos de `A` en `B` y `C`.

Uno a partir de un diagrama de clase, debería poder hacer un programa coherente. Antes de mandar a recorregir el control, traten de hacer un programa utilizando SOLO los atributos y funciones que están en su diagrama.

**PD:** los invito a aclarar sus dudas sobre el diagrama de clases en esta issue!! ❤️

**Comment by Dunkan1** [comment]
que pasa si defino una clase dentro de otra?

**Comment by fvr1** [comment]
@Dunkan1  podrías dar un ejemplo un poco más específico? te refieres a instanciar una clase adentro de otra?

**Comment by Dunkan1** [comment]
class bla:
      def __init__():
             self.bla
      def imprime():
             self.bla
      class no_bla:
             def __init___():
                   self.no_bla
       def bla+no_bla:
                instanced = self.no_bla()
               return self.bla+instanced.no_bla
bueno el codigo es malo pero espero se entienda la idea

**Comment by Dunkan1** [comment]
class bla:
------def init:
---------self.bla
------class no_bla
-----------def init
---------------self.no_bla
------def bla+no_bla:
-----------palabra= self.no_bla()
-----------return self.bla+palabra.no_bla
o algo asi, espero se entienda la idea

**Comment by fvr1** [comment]
@Dunkan1 declarar una clase adentro de otra es una mala práctica. Si quieres que compartan atributos, para eso existe herencia y multiherencia!

**Comment by Dunkan1** [comment]
es que lo use para definir una clase _iterador que despues era llamada por __iter__ 
:( tengo que cambiarlo?

**Comment by negutierrez** [comment]
sobre la cardinalidad, todos los diagramas de clases deben incluirla? recuerdo que para la AC0 un ayudante me dijo que no era necesario.

**Comment by maxfreymo** [comment]
En donde dice "ponerle parámetros y retorno a todas las funciones" ¿Esto quiere decir a los métodos de las clases ? Si es así ¿Puedes dar un ejemplo?

**Comment by iqacevedo** [comment]
@maxfreymo justamente a eso se refiere. 
Puedes ver el ejemplo que se entregó en los contenidos del curso:
![image](https://cloud.githubusercontent.com/assets/13748732/24558858/040dcada-1613-11e7-9f61-1efb3171bc13.png)
Si te fijas, el metodo agregar_observación recibe magnitud (que es un float), tiempo (que es un int) y error (que es un float), puedes ver que el método no retorna nada por lo que se indica con None. Además, los otros métodos si retornan algo.

Saludos !

**Comment by asdegoyeneche** [comment]
Me sumo a @negutierrez. Por lo que recuerdo, en mi sección la profesora dijo que no era necesaria poner la Cardinalidad, al menos para las primeras actividades y tarea 2, no estoy seguro si también lo dijo para el control. Por lo que, dado que no lo incorporamos en las actividades anteriores, no lo agregué al control...

**Comment by fvr1** [comment]
@negutierrez y @asdegoyeneche, hablé con la profe y tienen razón! voy a cambiarlo

**Comment by asdegoyeneche** [comment]
@fvr1 bacan, muchas gracias! :)

**Comment by Dunkan1** [comment]
una duda si tengo una clase que usa a otra en un metodo, esto no cuenta como agregacion o composicion cierto? ya que segun tengo entendido, solo cuenta cuando se usa en el init

**Comment by Dunkan1** [comment]
que pasa si un atributo puede recibir cualquier cosa
eje:
Nodo:
-----init
--------valor
pero como es un nodo entonces valor puede ser un int, float, str, o una clase

**Comment by fvr1** [comment]
@Dunkan1
1. no cuenta como agregación o composición. 
2. hmm yo pondría un `*` de tipo de dato y especificaría que eso significa cualquier tipo de dato.
**PD:** para escribir código y que quede indentado y todo puedes usar   tres de ` antes y después
```
Nodo:
     init
         valor
```

**Comment by Dunkan1** [comment]
```  
aaaa!
      ya
          veo
 ```

**Comment by maxfreymo** [comment]
Cuando tengo:

@property
def nombre (self):
       #Código

...en el diagrama de clases ¿lo colocó como atributo o método?
