### ISSUE TITLE
Your branch and 'origin/main' have diverged, and have 1 and 1 different commits each, respectively.

### ISSUE THREAD

**Issue by EnriqueVildosola** [IIC2233/Syllabus#196]
Hola eliminé un archivo de manera directa en github web y ahora que quiero hacer git push me arroja el siguiente problema.
¿Qué debo hacer?
<img width="960" alt="Captura de pantalla 2023-09-06 193724" src="https://github.com/IIC2233/Syllabus/assets/110938625/203ecae2-f3a6-45ff-b92c-e7810b8143a7">

**Comment by Hernan4444** [comment]
Hola @EnriqueVildosola 

Lamento mucho la tardanza, entre tantas issues se nos pasó esta. Respecto al caso que nos indicas, revisa la siguiente issue
* #198

Ahí pasó algo similar y se indicó el paso a paso de cómo solucionarlo.

Saludosヾ(＾-＾)ノ
