### ISSUE TITLE
Encuesta de Carga Académica

### ISSUE THREAD

**Issue by mVal919** [IIC2233/Syllabus#196]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Contenido

Hola, buenas tardes.
¿Dónde subieron la encuesta? Es que no la pillo.
Eso, muchas gracias.

**Comment by Hernan4444** [comment]
Hola @mVal919 

En canvas debería aparecer una pestaña que es "Encuesta Académica II"

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con el curso! 🦖
Saludosヾ(＾-＾)
