### ISSUE TITLE
Diferencia entre herencia y clases abstractas

### ISSUE THREAD

**Issue by ElKrra** [IIC2233/syllabus#196]
Hola! Todavía siento que me cuesta diferenciar el concepto de herencia con clases abstractas. Por bastante tiempo pensé que era prácticamente lo mismo pero al releer los documentos semanales me di cuenta de que para la herencia hay que llamar al init de la superclase, mientras que en la clase abstracta no es necesario, al instanciar una subclase ya sería posible utilizar los métodos normales de la clase abstracta. Alguien me podría explicar con algún ejemplo donde ocupar cada una? Gracias!

**Comment by gatochico** [comment]
Hola!!

Herencia y clases abstractas son dos cosas distintas. Es más, las clases abstractas funcionan mediante herencia al hacer que el hijo herede de la clase abstracta padre :0. 

Digamos que se tienen las siguientes dos clases, `padre` e `hija`. Aquí un breve tip para saber cuando una clase padre debe ser abstracta o no:

- Si tiene sentida que **la clase padre pueda ser instanciada por si sola**, utilizas **herencia sin clases abstractas**. Un ejemplo:
``` 
# clase padre 1
class Camara:
    def __init__(self, megapixeles):
        self.megapixeles = megapixeles
    def sacar_foto(self):
        print("Estoy sacando una foto!")
# clase padre 2
class Parlante:
    def __init__(self, volumen):
        self.volumen = volumen
    def tocar_musica(self):
        print("Estoy tocando una canción!")
# clase hija, que hereda de las dos de arriba
class Celular(Camara, Parlante):
    def __init__(self, megapixeles, volumen, numero):
        Camara.__init__(self, megapixeles)
        Parlante.__init__(self, volumen)
        self. numero = numero
    def llamar(self):
        print("Llamande desde el numero", numero)
```
Aquí, `Celular` hereda de `Camara` y de `Parlante`, sin embargo, es lógicamente posible que una cámara o un parlante existan por si solos, por lo que dichas clases **no** son abstractas. En este caso, podríamos hacer sin problemas:
```
camara = Camara(10)
parlante = Parlante(20)
celular = Celular(12, 21, 123456789)
```

-  Por otro lado, si **no tiene sentido que la clase padre sea instanciada por si sola**, debe ser una clase abstracta. Piensa una clase abstracta como un molde para una subclase, donde se indican métodos y properties que la subclase debería tener de forma obligatora, por decirlo así. Otro ejemplo:
```
# clase padre abstracta
# un __init__ no es obligatorio para la clase abstracta, pero se puede poner si se desea
class Animal(ABC):
    # este metodo será abstracto
    @abstractmethod
    def mover(self):
        pass
    # este no será abstracto
    def existir(self):
        print("Soy un animal y existo!")

class Perrito(Animal):
    def __init__(self, nombre):
        self.nombre = nombre
    # la clase abstracta padre tenía este abstractmethod, así que debo incorporarlo en mi clase hija
    #o se caerá el programa
    def mover(self):
        print("Caminando!")

class Pez(Animal):
    def __init__(self, nombre):
        self.nombre = nombre
    # la clase abstracta padre tenía este abstractmethod, así que debo incorporarlo en mi clase hija
    #o se caerá el programa
    def mover(self):
        print("Nadando!")
```
Lógicamente, es posible que exista un perro y un pez, pero no que exista el concepto de animal por si solo, por lo que la clase Animal no debería ser instanciada sola. Por ende, la clase animal es abstracta. Todos los animales se mueven, pero de forma distinta, y por ende `mover()` es un método abstracto de la clase `Animal`, ya que debe ser redefinido dependiendo del animal. 
Ojo, que la clase abstracta `Animal` posee el método no abstracto `existir()`. Como este método se comporta de igual forma para todos los animales, no es necesario que sea un método abstracto que deba ser redefinido en las clases hijas.

Espero haber ayudado, y cualquier cosa pregunta! :nerd_face:

**Comment by raimundoloeser** [comment]
Tengo una duda a la hora de instanciar la clase con multiherencia, ya que si tengo que las 2 clases padres reciben los mismos parametros para su __init__, la segunda se quedaria sin elementos para instanciarse. Mi problema va a que tengo 2 clases, donde una tercera hereda los metodos de ambas 2, pero para instanciar las primeras 2 clases reciben los mismos elementos

gracias!

**Comment by burgosibarra** [comment]
Si tengo una clase que no tiene sentido ser instanciada por si sola, es decir, abstracta, puedo agregarle properties que son comunes para las otras clases que hereden de esta? (contexto T01)
gracias

**Comment by gatochico** [comment]
No habría problema con respecto a lo que dices, puedes pasarle los mismos parámetros a ambas clases y no habra problema. Mira:
![image](https://user-images.githubusercontent.com/37161120/64625478-a4973580-d3c2-11e9-99f1-ed6c2e09948d.png)
![image](https://user-images.githubusercontent.com/37161120/64625490-abbe4380-d3c2-11e9-9599-e0e018d012ee.png)
 Eso si, ojo con el **sobreescribir métodos o atributos**. Si tienes atributos en común, setearás los atributos con la última clase padre que instanciaste en el init. Por ejemplo:
![image](https://user-images.githubusercontent.com/37161120/64625700-0192eb80-d3c3-11e9-80d6-10ac2c8b1e30.png)
![image](https://user-images.githubusercontent.com/37161120/64625716-09eb2680-d3c3-11e9-93f7-08c0941c684b.png)

**Comment by ElKrra** [comment]
Muchas gracias!
