### ISSUE TITLE
Ejercicio 2.2.3 propuesto de esta semana

### ISSUE THREAD

**Issue by cristiannvg** [IIC2233/syllabus#196]
Hola!,
Tengo una duda con los ejercicios propuestos de esta semana, especialmente en las properties.
Cuando se definen las properties de email, rut, etc. A que se refiere con ese value a la cual se le deberían entregar?. ¿Estos ya deberían ir especificados en la clase usuario desde ya?.
![2 2 3](https://user-images.githubusercontent.com/69771644/91241603-4cf8f380-e713-11ea-8d4f-834de6b43052.PNG)

Con respecto a eso, tengo otra duda, estaría correcto hacer la relación de que si se cumplen las condiciones podemos cambiar aquellos self.__username=self.username?

De antemano, muchas gracias

**Comment by MatiasDuhalde** [comment]
Hola @cristiannvg !

Los setters se llaman/invocan cuando se modifica el valor de una property. Para modificar el valor de una property, lógicamente se le debe entregar un nuevo valor. En este caso, el "nuevo valor" estaría guardado en la variable `value`. Por ejemplo, usando la misma clase del ejercicio, si yo creo un usuario:
```python
usuario1 = Usuario('usuario1', 'usuario1@uc.cl', 17, '00000-0')
```
Posteriormente, si quisiera cambiar el valor de uno de los atributos de `usuario1`, debería hacer lo siguiente.
```python
usuario1.username = "octocat"
```
Esta última línea llamará al setter de la property `username`, y el valor de la variable `value` será `"octocat"`. Debido a que queremos cambiar el valor de `username`, la manera correcta de definir el setter sería:
```python
@username.setter
def username(self, value):
    self.__username = value
```

Notar que en el `__init__` del ejemplo, al hacer `self.username = username` estamos llamando al setter de la property `username`, y `value` pasaría a ser lo que haya en `username` (`'usuario1'` en el ejemplo de arriba).

No entendí muy bien a qué te referías con tu segunda pregunta, pero con la explicación anterior puedes darte cuenta que `self.__username = self.username` sería lógicamente incorrecto, debido a que el valor de `username` seguiría siendo el mismo.

La idea del ejercicio es que dentro de la misma clase `Usuario`, hagas "validaciones" dentro de los setters, para evitar que los atributos tomen ciertos valores no permitidos (como por ejemplo, que la edad sea menor que 18).

Ojalá esto aclare un poco el ejercicio, y si esto aún sigue siendo confuso, no dudes en preguntar!

**Comment by cristiannvg** [comment]
Me quedó clarisimo :D, muchisimas gracias!
