### ISSUE TITLE
Los excel se tenían que subir?

### ISSUE THREAD

**Issue by CristobalUrzua** [IIC2233/syllabus#196]
:(

**Comment by DCCollao** [comment]
Hola @CristobalUrzua!

Primero que nada, los  `.csv` no son archivos excel, aunque el computador los abra con dicho programa!

No había que subir los `.csv`, pues son parte de los archivos que debían incluirse en tu `.gitignore`, pero no será evaluado en esta ocasión. Te recomiendo leer la sección 9 del enunciado para más detalles
