### ISSUE TITLE
Duda sobre la tarea 2 colores-perro terminator

### ISSUE THREAD

**Issue by Rafa192022** [IIC2233/Syllabus#196]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Mi duda es sobre si existe un color nesesario en el fondo del juego como obligatorio o es a eleccion del alumno, y otra duda terminator dog siempre debe estar en cada ventana?

**Comment by nzamorano** [comment]
Hola @Rafa192022, no existe un color de fondo obligatorio, sino que queda a elección suya mientras se cumplan los requisitos mínimos, las ventanas del enunciado son solo a modo de ejemplo. Y respecto a _Terminator-dog_, en el enunciado en la sección de este personaje en _Mecánicas de Juego_ se dice que debe estar presente durante la partida, y como no se especifica para las otras ventanas queda a criterio suyo 😉, puedes especificarlo en el _readme_ para aclararlo.
