### ISSUE TITLE
Presentación Ejército

### ISSUE THREAD

**Issue by coniverav** [IIC2233/Syllabus#197]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, me confunde un poco la manera en que se redactaron los requerimientos de la clase ejército, ya que me piden que haga un método que los presente usando \_\_str\_\_, pero luego me repite la misma instrucción más abajo con otras palabras... Solo me está repitiendo lo que tengo que hacer o me pide que haga otro método aparte para hacer una presentación diferente?

<img width="482" alt="image" src="https://github.com/IIC2233/Syllabus/assets/162245893/36daa54e-c8ea-4724-b639-90f5247ef5d5">

Gracias de antemano:)

**Comment by tebi01** [comment]
Hola! @coniverav 

Claro, parece redundante la idea si lo ves en ese orden.

La última parte donde dice que en tu ejército deben poder presentarse y agregar combatientes es más como un resumen de lo que debería poder hacer, considerando todos los puntos anteriores. No te preocupes!

Si de igual manera te confunde, puedes agregar en tu archivo ```README.md``` la interpretación que tuviste de la idea en el apartado correspondiente.

Espero haberte ayudado!

**Comment by coniverav** [comment]
gracias!!
