### ISSUE TITLE
problema libreria pyqt5

### ISSUE THREAD

**Issue by Pelaysen** [IIC2233/Syllabus#197]
instale la libreria pyqt5 con pip3 instaler etc, se insatlo correctamente, pero al correr el demo me dice que no hay un modulo llamado pyqt5.

**Comment by fgbruna** [comment]
Que resulta si corres el siguiente comando en la linea de comandos?:
`pip3 show pyqt5`

**Comment by Pelaysen** [comment]
me sale esto:
Name: PyQt5
Version: 5.10.1
Summary: Python bindings for the Qt cross platform UI and application toolkit
Home-page: https://www.riverbankcomputing.com/software/pyqt/
Author: Riverbank Computing Limited
Author-email: info@riverbankcomputing.com
License: GPL v3
Location: c:\users\pelay\appdata\local\programs\python\python36-32\lib\site-packages
Requires: sip

**Comment by rihanuch** [comment]
Intenta con pip!! (No con pip3)

**Comment by fgbruna** [comment]
@Pelaysen, entonces si tienes instalado el paquete.
Como estas corriendo `demo.py`?

**Comment by fgbruna** [comment]
@Pelaysen porfavor sigue los pasos que mencioné y dime que resulta de ejecutar lo que te recomendé.

**Comment by Javierdr** [comment]
Quizás estas corriendo tu programa en un entorno virtual en el cual PyQt5 no esta incluido. Un entorno virtual aisla librerias con el fin de controlar el entorno de ejecución. Si estas en pycharm intenta ir a **file** --> **settings** --> **project: nombre_del_proyecto** --> **project interpreter**. Ahi te aparecera una lista de los modulos que se pueden importar en tu entorno virtual. Chequea que entre esos esté PyQt5. Saludos.

**Comment by Seld0nn** [comment]
Tengo el mismo problema que @Pelaysen. tambien me arroja el mismo output al escribir:  "pip3 show pyqt5" en la linea de comandos por lo cual se que la librería esta bien instalada. Por otro lado, al intentar lo que sugiere @fgbruna ("python Demo.py" en linea de comandos) me arroja el siguiente error:

 Traceback (most recent call last): File "Demo.py", line 1, in <module>                                                                                       from Interfaz import Window                                                                                           
File "Interfaz.py", line 1, in <module>                                                                                                                     from PyQt5.QtGui import QImage, QBrush, QPalette, QFont,QStandardItem,\                                             ImportError: No module named 'PyQt5'

**Comment by Javierdr** [comment]
Intentaron lo que les dije mas arriba ?

**Comment by njgarrido** [comment]
Hice lo que pusiste ahí y me funcionó!
