### ISSUE TITLE
Duda sobre si es posible hacer el movimiento de la mira con el Mouse

### ISSUE THREAD

**Issue by FabriRandon** [IIC2233/Syllabus#197]
Hola.
Quería consultar si es posible en vez de utilizar las teclas "A", "S", "W", "D" para poder mover la mira, ¿utilizar el ratón del mouse? Lo que ocurre es que lo hice de esa forma y al presionar las teclas del mouse dispara, creo que de esa forma mejora la jugabilidad. Si lo coloco y especifico en el readme estaría bien? Gracias

**Comment by nzamorano** [comment]
Hola @FabriRandon, **NO** es posible utilizar el ratón del mouse para mover la mira, debe ser como se menciona en el enunciado. Lo que sí puedes hacer es utilizar teclas distintas (en caso que tengas problemas con las del enunciado), mientras lo menciones en tu *readme* :wink:.
