### ISSUE TITLE
Crear objeto y energía

### ISSUE THREAD

**Issue by TarekHirmas** [IIC2233/Syllabus#197]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Sobre crear un objetos, el enunciado dice que: "La creación o no de los objetos depende de PROB_EXITO_OBJETO", entonces si alguien que no posee la energía que cuesta crearlo, puede crearlo de todas maneras y quedar con energía en 0 (ya que no puede haber energía negativa) o es necesario también cumplir con energía para crearse?

**Comment by MrNachoX** [comment]
Hola @TarekHirmas!
Para intentar crear un objeto el entrenador debe tener la energía necesaria para hacerlo. Si no tiene energía suficiente entonces no puede crear el objeto.
