### ISSUE TITLE
Dudas enunciado

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#197]
Hola! Queria aclarar algunas dudas que tengo sobre el enunciado par comprenderlo mejor 😄 

1. Los "Métodos de la GUI" nos son entregados? Es decir, estos los puedo utilizar o los tengo que crear yo mismo? (Si se tuviesen que crear seria una buena implementación de properties por ejemplo 👀 )
2. El enunciado dice que los jugadores toman turnos en forma alternante, pero el demo entrega a veces dos piezas del mismo color, es esto correcto?
3. Se dice que se debe sobreescribir los métodos de "GameInterfaz", como por ejemplo "rotar", pero como yo (como usuario que juega) le indico la dirección, o queda a disposición mía el sentido de rotación?
4. Como se obtienen las posiciones indicadas por el jugador? A esto me refiero con que si tengo que hacer la tarea en modelos diferentes (obviamente por un tema de orden) como es que se debe hacer para conectar mi clase "Jugador" (por ej) a la interfaz gráfica?

Muchas gracias!

**Comment by indonoso** [comment]
Hola! Cómo dijimos en la clase **NO** debes hacer una issue con títulos poco explicativos y debes hacer una issue por cada uno de los puntos que tienes arriba. Esto es para facilitar el trabajo de todos en este curso al momento de buscar y responder issues.
