### ISSUE TITLE
__getitem__ con multiples argumentos

### ISSUE THREAD

**Issue by Genaron** [IIC2233/Syllabus#197]
En la tarea 2, tengo una clase Matriz, que es de R^{n x n}. Quería poder obtener el elemento [ i, j ] de esta matriz, pero el método __getitem__ acepta solo un argumento. Quería saber si puedo definir ese método como aparece en [esta respuesta](http://stackoverflow.com/a/17478302), de manera que códigos como el siguiente estarían correctos
```
matriz = Matriz(...)
for i in range(n):
    for j in range(n):
        a = matriz[i,j]
        ...
```
O si bien el hecho de hacer
```
def __getitem__(self, tup):
    i, j = tup
    ...
```
Usa de manera 'escondida' las tuplas y eso está prohibido..

**Comment by stephichau** [comment]
@Genaron  Puedes crear tu propia tupla!
