### ISSUE TITLE
gitignore y plazo de entrega

### ISSUE THREAD

**Issue by connandiaz** [IIC2233/Syllabus#197]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

¿Qué tan necesario es que rellene el formulario de atraso si mi tarea y README fueron subidos antes de las 20:00 pero mi giticnore no se subió (por errores de guardado) y quedó después de la hora?
De hecho acabo de revisar y quedó en el repositorio pero afuera de la carpeta T1

**Comment by Hernan4444** [comment]
Hola @connandiaz 

Lamento informar que todo cambio posterior a las 20:00 de ayer que quieras que nosotros tomemos en cuenta repercutirá en alguna penalización. Lo que recomendamos es que revises el commit a revisar que te fue notificado en canvas, veas la pauta y las [bases generales de tareas](https://github.com/IIC2233/Syllabus/blob/main/Tareas/Bases%20Generales%20de%20Tareas%20-%20IIC2233.pdf). Con esa información contrastes qué te beneficia más (o qué te perjudica menos): si entregar 1 día tarde, lo cual acota tu nota a máximo 6.0 o bien aceptar el descuento que incurra no subir el `.gitignore`.

Saludos!
