### ISSUE TITLE
Problema con git push

### ISSUE THREAD

**Issue by dani-sschlack** [IIC2233/syllabus#197]
holaa, estaba de lo mejor haciendo la tarea cuando voy a hacer unos cambios en mi repo  y subirlos a git y la verdad, no se que hice mal xd; ya no puedo subir mis avances, me aparece esto:

<img width="605" alt="Captura de Pantalla 2020-08-25 a la(s) 20 42 39" src="https://user-images.githubusercontent.com/69522104/91241785-b842c580-e713-11ea-941f-0cc405ae3171.png">

parece que después de lo que hice ya no me reconoce :c, como que no tengo acceso a mi repo para subir pero si puedo hacer git pull
antes me había dicho algo de que usara git config name.user... o algo así y y git config @mail ... o algo así, asi que lo utilice con mi info y parece que después de eso no me dejo subir los cambios 👎🏼 
help me please xd
p.d: ya trate de borrar mi repo y clonarlo de nuevo pero no funciono :cccc

**Comment by kadroguett** [comment]
Hola @dani-sschlack, probablemente ingresaste tus credenciales mal. 
Tienes que borrar los datos que pusiste en git, para esto apreta CMD + espacio y busca "llaveros", en la sección contraseñas busca github y elimina las credenciales que tengas. 
Después de borrarlas intenta hacer `git push` y cuentame como te va

**Comment by dani-sschlack** [comment]
Ahora  sí me funciona de nuevo !!!!
Muchas gracias !!! 👍🏼 👍🏼 🥇

**Comment by kadroguett** [comment]
De nada, éxito en tu tarea!
