### ISSUE TITLE
Duda respecto a heredar de clases abstractas

### ISSUE THREAD

**Issue by maurobsp** [IIC2233/syllabus#197]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Tengo dudas respecto a porque al momento de definir una subclase si heredo de una super-clase normal para iniciar el los atributos utilizamos super()--init--(self, a, b, c).
```python
class Auto:
    
    def __init__(self, ma, mo, a, c, k):
        self.marca = ma
        self.modelo = mo
        self.año = a
        self.color = c
        self.__kilometraje = k
        self.__dueño = None

class FurgónEscolar(Auto): # Aquí se marca de donde hereda
    """Subclase de Auto"""
    
    def __init__(self, marca, modelo, año, color, kms):

furgón = FurgónEscolar('Kia', 'Sportage', 2000, "Blanco", 135000)

```

Pero al definir una subclase si heredo de una super-clase abstracta no se inicializan los atributos con el comando super()--init--(self)
```python
class Base(ABC):

    def __init__(self, nombre):
        self.nombre = nombre
        self.contador = 0

class SubClase1(Base):

    def metodo_2(self):
        self.contador += 3

instancia_1 = SubClase1("1")

```
Me podrían explicar por que con las clases abstractas no es necesario utilizar el super()--init--

**Comment by igbasly** [comment]
Hola @maurobsp :v:

Es una excelente pregunta y feliz te explico lo que ocurre.
Primero aclarar que no es que no sea necesario utilizar el `super().__init__` al heredar de clases abstractas, sino que acá solo ocurrió un caso específico.

Esto quiere decir, las clases abstractas son clases "base" que no se quiere instanciar, sino que usar de referencia para hacer otras clases. Para ello uno puede definir métodos que todas las clases compartan y de esta forma no escribir el mismo código varias veces, o uno puede utilizar `@abstractmethod` para obligar a definir ciertos métodos en las sub-clases.

Si tú defines un método "normal" (no `@abstractmethod`) en la clase abstracta, este por concepto de herencia simple, se heredará a todas las clases hijas sin tener que definirlo nuevamente. Por ello, en el caso que mencionas simplemente ocurre que el `__init__` no se definió porque se utilizaría el mismo que en la clase padre, **que en este caso era una clase abstracta**.
Esto **no significa** que no puedas re-redefinirlo o agregarle más funcionalidades, en cuyo caso deberás agregar el `super().__init__`.

Espero que esto haya aclarado tu duda, y me comentes cualquier cosa :smile:
Saludos,
Ian.

**Comment by maurobsp** [comment]
duda podria hacer lo mismo al herenciar de una super clase normal, me refiero a si no redefino un nuevo __init__() entonces crearia la instacia con el __init__() de la super clase, osea si pasaria lo mismo con el caso de la clase abstracta??

**Comment by igbasly** [comment]
Efectivamente, esto es una propiedad de herencia en general, aplica a cualquier tipo de clases 👌
