### ISSUE TITLE
Fecha de entrega README

### ISSUE THREAD

**Issue by sebadelorenzo** [IIC2233/syllabus#197]
El readme se puede entregar hasta mañana? Esto es por si nos damos cuenta de algo en nuestro código lo cual podemos destacar en el readme?

**Comment by aljara97** [comment]
Hola @sebadelorenzo, el plazo de entrega del README es hasta mañana (martes) a las 20:00 horas. Así que puedes revisar tu código con calma e indicarnos los ajustes necesarios, recuerda que un buen README nos facilita una mejor corrección de tu tarea.

Éxito :bird: ✌🏻
