### ISSUE TITLE
daños, mejoras infinitas y vueltas de los contrincantes

### ISSUE THREAD

**Issue by jiisamitt** [IIC2233/syllabus#197]
Hola! Tengo 3 preguntas.

¿Carrocería = Defensa, 🛡 
Chasis = Vida, ❤️ 
Ruedas = Velocidad, 💨 
Motor o zapatillas = Velocidad? 💨

Al ser lo anterior cierto, si es que mejoro todos los atributos del vehículo una vez, todos se quedan para siempre con sus mejoras (mientras esté corriendo en el mismo juego o lo guarde), excepto el chasis (que puede verse afectado en la carrera correspondiente o en otra)?

Pondré un ejemplo en el que sólo me fijaré en las características del auto:

(Empieza a correr "Jugador 1", con las siguientes características en su vehículo)
Carrocería = 100
Chasis = 100
Ruedas = 100
Motor o zapatillas = 100

(Da la primera vuelta y queda con esto)
Carrocería = 100
Chasis = 90
Ruedas = 100
Motor o zapatillas = 100

(Va a los pits y automáticamente queda así)
Carrocería = 100
Chasis = 100
Ruedas = 100
Motor o zapatillas = 100

(Decide mejorar su vehículo)
Carrocería = 120
Chasis = 120
Ruedas = 120
Motor o zapatillas = 120

(Da otra vuelta y termina la carrera, su vehículo ahora queda así)
Carrocería = 120
Chasis = 120
Ruedas = 120
Motor o zapatillas = 120

Y lo otro, ¿Los contrincantes al dar una vuelta, la probabilidad de accidente se calcula de la misma manera que el jugador, pero el daño que reciben lo hacen al igual que el jugador? ¿Entonces ellos van a los pits, si es que sí, cómo, o si es que no, cómo se recuperan?

Disculpa lo largo 🤓

**Comment by tomcan127** [comment]
Hola!
1) El atributo ruedas representa la tracción del vehículo, mientras que motor o zapatillas la potencia. Ambas, si bien no representan la velocidad, afectan esta, al igual que la carrocería,  (como puedes ver en las formulas de velocidad_recomendada).

2) Revisa la issue #169 y la #171 
P.D: cada atributo del vehículo se mejora por separado.

3) Si, la probabilidad se calcula de la misma forma, reciben el mismo daño y también pasan a los pits a regenerarse automáticamente.
Si tienes mas dudas mira la issue #125

**Comment by jiisamitt** [comment]
Gracias!

**Comment by mscuturrufo** [comment]
Hola! No me queda claro el que los contrincantes también pasan a los pits, pensé que solamente el vehículo del usuario podía pasar, ya que en el enunciado no lo especificaban.  Esto queda a criterio de cada uno ejecutarlo u obligatoriamente todos deben pasar por los pits?
