### ISSUE TITLE
Prints poco serios

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#198]
Hola! , a modo de hacer la experiencia un poco mejor, quiero hacer prints "poco" serios, sin ser ofensivo, es posible?

**Comment by jitorralba** [comment]
Hola @sa-Appel!
Mientras se pueda visualizar bien, entender y sea consistente con todo lo que se pide en el enunciado, manteniendose como tu mismo dices, el respeto, dale rienda a la creatividad. 
Siempre es bienvenido corregir una tarea entretenida!
