### ISSUE TITLE
Iniciar evento

### ISSUE THREAD

**Issue by rominaarancibia** [IIC2233/Syllabus#198]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, al momento de describir la entidad torneo "iniciar evento" a que se refiere? Porque luego se menciona algo muy similar dentro de simular día torneo (ocurrencia evento). Gracias

**Comment by mpiavf** [comment]
Hola! Es una de las características que tiene la entidad, por **día** se va a activar y por ende va a poder ocurrir o no algún evento dependiendo de la `PROB_INICIAR_EVENTO` . Luego en Simular día Torneo se mencionan las acciones que se realiza en un día de torneo y debes mostrar en consola, una de estas son los **eventos** que ocurren en el día y está determinado por la misma carácteristica de la entidad Torneo **iniciar evento**.
Si sigues con dudas no dudes en preguntar.
Saludos!

**Comment by rominaarancibia** [comment]
Sí, comprendo. Entonces, en iniciar evento se espera solamente que se indique si ocurre o no evento y en ocurrencia de evento dentro de simular dia se espera que se defina que evento ocurre a partir si ocurrió o no de "iniciar evento". ¿cierto?
Gracias
