### ISSUE TITLE
Precios de Vehículos y Mejoras

### ISSUE THREAD

**Issue by Alonsortega** [IIC2233/syllabus#198]
Hola! Respecto a los precios de los vehículos y las mejoras, estos estarán (o deben estar) en parametros.py o debemos "hardcodearlos"?

**Comment by gatochico** [comment]
Hola!
**Deben ir obligatoriamente en `parametros.py`**, ya que son parámetros que podríamos cambiar al momento de corregir la tarea. El no hacerlo conllevará un descuento en dicho item de la pauta.
Saludos y éxito! :bike: :motor_scooter:
