### ISSUE TITLE
Dudas sobre daño en combatientes

### ISSUE THREAD

**Issue by cataruze** [IIC2233/Syllabus#198]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Holaa, en la parte de Combatientes, especificamente en tipos de combatientes se habla sobre el daño, este re refiere a la vida que reduce un combatiente a su oponente? por ejemplo, en el caso de guerrero seria round(ataque - defensa_oponente).
Y el daño se tiene que considarar como algo propio de la instancia?

Muchas gracias de antemano.

**Comment by tebi01** [comment]
Hola!

Así es, el daño realizado es la vida que se le resta a tu oponente. Este daño sólo es parte del cálculo y no es parte de los atributos de tus clases. Por lo tanto, sólo debería ocurrir esto:

```vida -= daño```

Donde ```vida``` es el atributo de vida de la instancia atacada y ```daño``` es el resultado del cálculo pertinente de las demás variables en juego.  (No necesitas guardar ese daño en otro lugar)

Espero que esto haya aclarado tu duda!

**Comment by franquijada** [comment]
Holaa! tengo una duda respecto a el daño, si es que este valor resultara ser negativo (en el caso del  guerrero significaria que la defensa del oponente es mayor a el ataque) significa que no hay daño o que el daño es 1? 
Pregunte hoy en clases y un ayudante me dijo que no hay daño pero leyendo mejor el enunciado me di cuenta que decia esto:
![Captura de pantalla 2024-04-19 004454](https://github.com/IIC2233/Syllabus/assets/162580026/d9c84d4f-657a-4a99-86f0-781ce9e2467e)

**Comment by tebi01** [comment]
Hola! @franquijada 

El enunciado es ley. Si se especifica explícitamente que debe ser un int mayor o igual a 1, debes asegurarte que así se cumpla. Puede que algún ayudante no se haya percatado de ese apartado del enunciado y te haya dado una sugerencia orientada al sentido común (no podría haber daño negativo).

Espero eso aclare tu duda!
