### ISSUE TITLE
Duda ducktyping ejemplo 

### ISSUE THREAD

**Issue by nnovoag** [IIC2233/syllabus#198]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
en este ejemplo la p de pato debiese estar en mayúscula o no? Dentro del activar
![7D17C0D4-3FE8-4B1B-AB53-E7B372043C3C](https://user-images.githubusercontent.com/62225957/114039183-86b8dd80-9850-11eb-881b-fc3d6b00a05c.jpeg)

**Comment by Christian-Klempau** [comment]
Hola!
En este caso, el nombre de la variable es irrelevante, pero sí debes utilizarla al igual que como la defines en la definición de la función `activar()`, que corresponde a `pato`.
En general los nombres de las clases inician con mayúsculas por convención (**CamelCase**), pero las variables o instancias de clases, ocupan (**snake_case**). En este caso la variable `pato` corresponde a un uso de **snake_case**, por lo que lo adecuado es efectivamente llamarla `pato`.
En el ejemplo que mostraste, ocurre lo siguiente:
- la clase Pato tiene mayúsculas, que es lo correcto, al igual que persona (**CamelCase**)
- definimos las variables `donald `y `juan` con **snake_case**, y ambas son instancias de `Pato` y `Persona` respectivamente
- Luego, construimos la función `activar()`. En este caso, el nombre del parámetro no es relevante (ni relacionado necesariamente) a las clases que llaman. Por ejemplo, podrías ponerle simplemente: `instancia`, `elemento_a_llamar`, etc.

El por qué usamos la variable `pato` va para ilustrar el uso del `ducktyping`, donde dos clases comparten un mismo nombre de método, entonces independiente de lo que recibiría, siempre ejecutaría el método `gritar()` y `caminar()` de la instancia que reciba. 
Espero haya quedado claro, sino puedes preguntar lo que no entendiste! :D
