### ISSUE TITLE
Utilización métodos GUI

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#198]
Los "Métodos de la GUI" nos son entregados? Es decir, estos los puedo utilizar o los tengo que crear yo mismo? (Si se tuviesen que crear seria una buena implementación de properties por ejemplo 👀 )

**Comment by Arcoirisky** [comment]
Eso está explícito en el enunciado sección GUI. Vuelve a leer el enunciado un par de veces y con más tranquilidad si es que te pierdes mucho o:

**Comment by iqacevedo** [comment]
Además, corre el archivo demo.py, y fíjate cómo funcionan los métodos que están definidos en la clase que hereda de GameInterfaz
