### ISSUE TITLE
Error? Países en borders.csv que no aparecen en population.csv

### ISSUE THREAD

**Issue by ranieto** [IIC2233/Syllabus#198]
Por ejemplo: Bolivia, North Korea y varios otros.

**Comment by iqacevedo** [comment]
Hola 
Lo estamos arreglando.
Saludos !

**Comment by nfbalbontin** [comment]
También hay dos South Korea! con diferente población y diferencia en la "k". Es a propósito?

**Comment by nfbalbontin** [comment]
y también dos United Estates con la misma diferencia

**Comment by nfbalbontin** [comment]
y también dos Hong - Kong

**Comment by nfbalbontin** [comment]
Hola, también en el archivo population.csv se repiten tanto South Korea, como United Estates, como Hong Kong, como Costa Rica, como Saudi Arabia, como United Arab Emirates, con diferentes cantidades de población. Esto es a propósito o error?
