### ISSUE TITLE
Ejercicio 4.3 de la semana 2

### ISSUE THREAD

**Issue by anamanzana** [IIC2233/syllabus#198]
Resolvi el ejercicio, me arroja de manera adecuada el resultado. Pero quisiera saber si estaba permitido resolver dentro de la clase Campo, la función calcular_utilidad de esta forma:

```python
def calcular_utilidad(self):
    campo_papas.calcular_beneficio()
    campo_papas.calcular_costo()
    campo_arandanos.calcular_beneficio()
    campo_arandanos.calcular_costo()
    self.utilidad = int(self.beneficio) - int(self.costo)
    return self.utilidad
```

**Comment by Tito0906** [comment]
Holaa @anamanzana , por lo que parece, hiciste un llamado los métodos de las clases _Campo_papas_ y _Campo_arandanos_ en el interior de la clase _Campo_. Esto no se debe hacer porque la clase _Campo_ es la clase de la que heredan las clases _Campo_papas_ y _Campo_arandanos_. Por esta razón, no es bueno que la clase _Campo_ llame a otros objetos que heredaron de ella. En el ejercicio, la idea es que la clase _Campo_ utilice sólo sus propios métodos y atributos.

Saludos y éxito en el estudio!

**Comment by anamanzana** [comment]
Lo arregle, muchas gracias!

**Comment by tzehnder** [comment]
Hola tengo una duda sobre la misma parte del ejercicio pero no logro implementar el metodo sin llamar las clases que heredan. intente con la siguiente linea de codigo pero no me funciono..
`def calcular_utilidad(self):
        beneficio = self.calcular_beneficio
        costo = self.calcular_costo
        self.utilidad = beneficio - costo
        return self.utilidad`

Me arroja el siguiente error:
`TypeError: unsupported operand type(s) for -: 'method' and 'method'`

No entiendo porque no funciona si esas funciones a pesar de retornar algo en las clases que heredan ya estan definidas en la superclase.

**Comment by Tito0906** [comment]
Holaa!  me parece que tu error puede estar en cómo llamas los métodos. Acuérdate que para llamarlos tienes que agregar los paréntesis. De otra forma, sólo estás asignando los métodos a las variables, por lo que no tienes almacenado el resultado del método, sino que el método mismo. 

Mucho éxito con el estudio!!

**Comment by tzehnder** [comment]
muchas gracias !
