### ISSUE TITLE
Problema al conectar por señales el front-end y back-end del ranking

### ISSUE THREAD

**Issue by 0Cris0** [IIC2233/Syllabus#198]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, estoy separando mi ventana de ranking entre front-end y back-end, por ello creé 2 archivos para cada uno que uno mediante señales. Dentro de las funciones que uso con esa separación está la de leer los puntajes guardados, mandarlos al front-end y crear así un ranking con los elementos correspondientes.
El problema está en que mis señales parecen no funcionar porque no se genera ninguna reacción del back-end una vez se emite la señal desde el front-end, esto me confunde debido a que para unir ambos archivos ocupé el mismo esquema que he utilizado en las actividades pasadas y en las demás ventanas de la T2 (en las cuales funciona)

**Por ello, mi pregunta es si es que alguien podría ver mi código y ayudarme a entender cómo solucionar mi problema**

Muchas gracias

**Comment by 0Cris0** [comment]
Al final me funcionó, pero tuve que implementar como un "paso" antes de mostrar los rankings donde se presiona un boton. No hay problema con eso cierto?

**Comment by CristobalPerez-Cotapos** [comment]
a que te refieres con un paso? 🤔
