### ISSUE TITLE
Error actualizar GitHub para entrega T1

### ISSUE THREAD

**Issue by isidoragutierrez** [IIC2233/Syllabus#198]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Actualicé el README en la página de git y luego cuando quise hacer git push de la versión final de mi tarea me tiraba error, por lo que no se pudo actualizar en github la última versión de mi tarea.
Tengo pantallazos que verifican que intenté subirla antes de la hora de plazo y así todo no pude (sigo sin poder).
Qué puedo hacer al respecto? Tendré penalización de todas maneras?

<img width="712" alt="Captura de Pantalla 2023-09-06 a la(s) 20 04 01" src="https://github.com/IIC2233/Syllabus/assets/111446584/e62e43f1-d3b6-4129-b445-7cc3bc1de299">

**Comment by Hernan4444** [comment]
Hola @isidoragutierrez 

Lo que pasó es que despues de  editaste algo desde la página web de github, no hiciste "git pull" en tu PC. Esto provocó que tuvieras un "conflicto" dado que la nube tiene una versión de los archivos y tu PC tiene otra versión, así que no sabe cómo hacer push de esos commit. Por esto mismo todo cambio hay que hacerlo desde el pc y hagan "git add", "git commit" y "git push", y no les comentamos que editen cosas desde la página web de github, eso siempre trae problemas 😖.

Adicional a eso, en tu consola se ve que haces git add, pero no hacer git commit. Eso también puede generar problemas a git porque te estás saltando un paso.

Para solucionar todo esto, lo que recomiendo es

1. Volver a clonar tu repositorio en otra carpeta. Ese nuevo repo ya está totalmente actualizado con la nube. (aquí es usar el comando git clone)
2. A esa nueva carpeta hacerle cualquier cambio que desees hacer, ya sea subir un nuevo archivo, editar algo, etc.
3. Desde esa nueva carpeta hacer git add, commit y push.
4. La carpeta vieja que tiene problemas, eliminarla. Así solo te quedas con la carpeta que está todo bien que obtuviste del paso (1)

Respecto a la penalización, lamentablemente si es que quieres que te acepten un cambio posterior a las 20:00, si se aplicará el descuento, aunque empezaste antes, el cambio fue reportado finalmente posterior a la fecha de entrega, así que está fuera de plazo.  No obstante, si ese cambio a ti no te influye, puedes quedarte con el último commit que está dentro del plazo (el cuál ya fue notificado ayer) y así no tener ninguna penalización. Eso ya queda a tu criterio, pero en caso de pedir que te acepten algo posterior a las 20:00, se aplicará la penalización correspondiente, esa es la regla del curso.

Saludos!
