### ISSUE TITLE
Readme en actividades

### ISSUE THREAD

**Issue by Martinrsts** [IIC2233/syllabus#199]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, no me queda claro si en las actividades sumativas también hay un plazo para subir un readme.

**Comment by aerotecnia99** [comment]
Hola! Hay entrega de readme solo para las tareas no para las actividades ●‿●
