### ISSUE TITLE
Sobre threads: errores en prints y detener threads

### ISSUE THREAD

**Issue by matioprts** [IIC2233/syllabus#199]
Buenas,

Mi duda es la siguiente, corrí 3 veces mi main.py de esta actividad sin hacer absolutamente **ninguna modificación** al código. La primera vez que lo corrí simplemente se demuestra que los dragones son capaces de llegar a tiempos distintos y que el programa se detiene cuando un dragón llega y su jinete descifra el pergamino. **Output** de la consola en el **try 1**:

C:\Users\opmat\Desktop\Universidarks\matioprts-iic2233-2019-1\Actividades\AC06>python main.py
--------------------------------------------------------
Los equipos comienzan la travesía!
--------------------------------------------------------
--------------------------------------------------------
El Dragón Rhaegal y su Jinete Johnny han emprendido vuelo.
--------------------------------------------------------
--------------------------------------------------------
El Dragón Viserion y su Jinete Gnomo han emprendido vuelo.
--------------------------------------------------------
--------------------------------------------------------
El Dragón Drogon y su Jinete Jaimito han emprendido vuelo.
--------------------------------------------------------
--------------------------------------------------------
El Dragón Viserion ha llegado al campo de batalla!
--------------------------------------------------------
--------------------------------------------------------
El Dragón Drogon ha llegado al campo de batalla!
--------------------------------------------------------
--------------------------------------------------------
El Dragón Rhaegal ha llegado al campo de batalla!
--------------------------------------------------------
--------------------------------------------------------
El Jinete Johnny ha descifrado el pergamino
--------------------------------------------------------
 Tres veces volé a Silverwing por encima del Castillo Negro, y tres veces intenté llevarla al norte más allá del Muro', le escribió Alysanne a Jaehaerys, 'pero cada vez viraba hacia el sur de nuevo y se negaba a ir. Nunca antes se había negado a llevarme a donde yo quería ir. Me reí de eso cuando volví a bajar, para que los hermanos de negro no se dieran cuenta de que algo estaba mal, pero me preocupó entonces y me preocupa aún
--------------------------------------------------------
Fin de la travesía!

En el **try 2** se demuestra que el programa es capaz de detener mis daemon threads (dragon/jinetes) si es que el programa termina (el programa termina cuando algún equipo de dragon y su jinete cumplen sus objetivos respectivos) ya que termina aún cuando un dragón no llegaba. **Output** del **try 2**:

C:\Users\opmat\Desktop\Universidarks\matioprts-iic2233-2019-1\Actividades\AC06>python main.py
--------------------------------------------------------
Los equipos comienzan la travesía!
--------------------------------------------------------
--------------------------------------------------------
El Dragón Rhaegal y su Jinete Johnny han emprendido vuelo.
--------------------------------------------------------
--------------------------------------------------------
El Dragón Viserion y su Jinete Gnomo han emprendido vuelo.
--------------------------------------------------------
--------------------------------------------------------
El Dragón Drogon y su Jinete Jaimito han emprendido vuelo.
--------------------------------------------------------
--------------------------------------------------------
El Dragón Viserion ha llegado al campo de batalla!
--------------------------------------------------------
--------------------------------------------------------
El Dragón Rhaegal ha llegado al campo de batalla!
--------------------------------------------------------
--------------------------------------------------------
El Jinete Johnny ha descifrado el pergamino
--------------------------------------------------------
 Tres veces volé a Silverwing por encima del Castillo Negro, y tres veces intenté llevarla al norte más allá del Muro', le escribió Alysanne a Jaehaerys, 'pero cada vez viraba hacia el sur de nuevo y se negaba a ir. Nunca antes se había negado a llevarme a donde yo quería ir. Me reí de eso cuando volví a bajar, para que los hermanos de negro no se dieran cuenta de que algo estaba mal, pero me preocupó entonces y me preocupa aún
--------------------------------------------------------
Fin de la travesía!

En el **try 3** las cosas se ponen ***realmente feas***. En este try pasan varias cosas, lo primero es el error en el orden de los prints de mis separadores de linea, esto tengo entendido que se debe a la forma en que se alternan los threads a nivel computador y como está programada la función print, por lo que entiendo que arreglar este problema en los prints de mis separadores de linea sea algo quizás imposible de hacer (a pesar de que me moleste ver mis separadores de linea separando aire).
Sin embargo mi problema o duda principal radica en los otros errores:
* Tal parece que jinete Jhonny y jinete Jaimito logran descifrar el pergamino al mismo tiempo, y dado que sus dragones respectivos ya estaban en el campo de batalla el programa "termina" 2 veces, por el print Fin de la travesía! que solo debería salir una vez
* Además luego de que ambos jinetes y dragones terminaran sus objetivos, luego de que el programa "terminara" 2 veces, se realiza el print de que el jinete restante logra descifrar también el pergamino. Y el programa procede a finalizar. **Output** del **try 3**:

C:\Users\opmat\Desktop\Universidarks\matioprts-iic2233-2019-1\Actividades\AC06>python main.py
--------------------------------------------------------
Los equipos comienzan la travesía!
--------------------------------------------------------
--------------------------------------------------------
El Dragón Rhaegal y su Jinete Johnny han emprendido vuelo.
--------------------------------------------------------
--------------------------------------------------------
El Dragón Viserion y su Jinete Gnomo han emprendido vuelo.
--------------------------------------------------------
--------------------------------------------------------
El Dragón Drogon y su Jinete Jaimito han emprendido vuelo.
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
El Dragón Viserion ha llegado al campo de batalla!
El Dragón Drogon ha llegado al campo de batalla!
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
El Dragón Rhaegal ha llegado al campo de batalla!
--------------------------------------------------------
--------------------------------------------------------
El Jinete Johnny ha descifrado el pergamino
--------------------------------------------------------
--------------------------------------------------------
 Tres veces volé a Silverwing por encima del Castillo Negro, y tres veces intenté llevarla al norte más allá del Muro', le escribió Alysanne a Jaehaerys, 'pero cada vez viraba hacia el sur de nuevo y se negaba a ir. Nunca antes se había negado a llevarme a donde yo quería ir. Me reí de eso cuando volví a bajar, para que los hermanos de negro no se dieran cuenta de que algo estaba mal, pero me preocupó entonces y me preocupa aún
El Jinete Jaimito ha descifrado el pergamino
--------------------------------------------------------
--------------------------------------------------------
 Tres veces volé a Silverwing por encima del Castillo Negro, y tres veces intenté llevarla al norte más allá del Muro', le escribió Alysanne a Jaehaerys, 'pero cada vez viraba hacia el sur de nuevo y se negaba a ir. Nunca antes se había negado a llevarme a donde yo quería ir. Me reí de eso cuando volví a bajar, para que los hermanos de negro no se dieran cuenta de que algo estaba mal, pero me preocupó entonces y me preocupa aún
--------------------------------------------------------
Fin de la travesía!
Fin de la travesía!
--------------------------------------------------------
El Jinete Gnomo ha descifrado el pergamino
--------------------------------------------------------
 Tres veces volé a Silverwing por encima del Castillo Negro, y tres veces intenté llevarla al norte más allá del Muro', le escribió Alysanne a Jaehaerys, 'pero cada vez viraba hacia el sur de nuevo y se negaba a ir. Nunca antes se había negado a llevarme a donde yo quería ir. Me reí de eso cuando volví a bajar, para que los hermanos de negro no se dieran cuenta de que algo estaba mal, pero me preocupó entonces y me preocupa aún
--------------------------------------------------------

***EDIT***: Ya arreglé el primer problema de que ambos equipos terminaran al mismo tiempo, dentro de un While (equipos aun no terminan sus respectivos objetivos):
recorría los 3 equipos cada 1 segundo para chequear si cumplieron y terminar el programa, a este for equipo in equipos le faltaba un break además de declarar la variable del While para romper el ciclo, cosa de que si chequeaba que un equipo lograba terminar, dejara de chequear al resto de los equipos.

**Comment by Polea012** [comment]
Hola! 
Para resolver la otra duda restante, podrías subir la versión más reciente de esa actividad a tu repositorio (en la carpeta de la actividad correspondiente) con un push? Para así poder ver el código con más detalles.

Saludos.
