### ISSUE TITLE
Tablero: Input fuera del rango

### ISSUE THREAD

**Issue by lorenzosilva** [IIC2233/syllabus#199]
En la tarea no especifican que pasa si es que mi usuario no ingresa un número fuera del rango. Se puede dejar el código para que funcione solo si el usuario ingresa los números correctos? o tengo que crear un ciclo?

**Comment by kadroguett** [comment]
Te refieres a que pasa si ingresa un número fuera del rango? en ese caso en el enunciado se especifica que se debe verificar que esté dentro del rango, de no estarlo debes notificar al usuario y volver al menú de inicio. 
Si entendí mal tu pregunta puedes explicarla de nuevo por favor
