### ISSUE TITLE
Modificacion pequeña despues de la hora de entrega

### ISSUE THREAD

**Issue by JPBarrosG** [IIC2233/Syllabus#199]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, un rato despues de entregar mi tarea revise por si acaso habia salido todo bien y resulta que a la hora de poner comentarios no me di cuenta y el return de uno de los modulos lo puse como comentario, no sabia si el ayudantia encargado de revisar la tarea se fijaria en ese detalle que hace que tenga una parte importante de la tarea mala, por lo que lo cambie poniendo en el commit una disculpa, queria saber si existe una forma que la tarea no cuente con atraso o si no se llegara a revisar este cambio que tuve que realizar a ultimo minuto, habia una forma de poder contactar o avisar al ayudante encargado de corregir las tareas de este desliz.

**Comment by Hernan4444** [comment]
Hola @JPBarrosG 

Lamento informar que todo cambio posterior a las 20:00 de ayer repercutirá en alguna penalización. Una opción es completar el formulario de entrega atrasada y se aceptará cualquier cambio que hagas en el nuevo commit a informar. Mientrs que otra opción es recurrir el descuento por cambio de línea, el cual durante la recorrección de la tarea puedes pedir cambiar la línea como tu quieras, lo cual incluye descomentar alguna línea.

<img width="1247" alt="image" src="https://github.com/IIC2233/Syllabus/assets/15641721/1902e1b5-980c-4f39-8599-d2e313c68bce">

Por otro lado, considerando que la primera parte de la tarea es 100% automatizada, no hay una persona que vea ese código y lo prueba, sino que es un _script_ que pasará por cada tarea y nos entregará el puntaje por ítem. Por lo cual, el ayudante a cargo no editará partes del código de la primera parte, dado que eso ya estará revisado. Lo que pasará es que en la recorrección, ahí los estudiantes podrán pedir cambio de línea, y el ayudante a cargo de corregir se encargará de (1) aplicar el cambi de línea, (2) asignar el descuento correspondiente y (3) correr nuevamente los tests de ser necesario. Por lo tanto, ahí si se podrá arreglar cualquier detalle necesario.

Saludos!
