### ISSUE TITLE
Duda respecto a la probabilidad de que un excavador encuentre un ítem

### ISSUE THREAD

**Issue by benhacks300** [IIC2233/Syllabus#199]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Buenas, tengo una duda respecto al funcionamiento de los excavadores a la hora de encontrar un ítem, esta consiste en que si la probabilidad obtenida por parte del excavador es menor o igual a la probabilidad de encontrar un consumible o un tesoro, ¿este obtendra su respectivo? o  la obtención solo será si las probabilidades son iguales?. 

Saludos!

**Comment by antoniamarin** [comment]
Hola! No me queda claro aun viendo la sala de ayuda. En esa se compara un valor aleatorio con uno fijo. Mientras que acá se comparan 2 fijos. La probabilidad de encontrar item asociada a un excavador puede ser por ejemplo 0.9 y la de la arena 0.8.  En ese caso no encuentra item porque la probabilidad es mayor. Esto lo digo pensando en el caso de la arena mojada que su probabilidad es 1. Por lo tanto siempre debiera encontrar un excavador un item. Entonces, ¿Se debe comparar ambas probabilidades "fijas" asociadas a las entidades? ¿O es algo más?  Muchas gracias
