### ISSUE TITLE
jugador asociado a piezas entregadas

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#199]
El enunciado dice que los jugadores toman turnos en forma alternante, pero el demo entrega a veces dos piezas del mismo color, es esto correcto?

**Comment by stephichau** [comment]
El archivo ```demo.py```es solo un ejemplo. Ustedes deben agregar cada una de las reglas que aparecen en el enunciado :).

**Comment by rihanuch** [comment]
pero lo que si o si tiene que tener nombres correspondientes (incluido el nombre de clase) son los métodos de "MyInterface"?

**Comment by iqacevedo** [comment]
Sip la idea es que tu heredes de GameInterface, en el demo se llama MyInterface, y tú clase heredada debe tener los mismos métodos que salen en el demo.py, ya que estos métodos son los que son llamados cuando se interactúa con la interfaz.

Saludos !

**Comment by felipecr00** [comment]
Algo que no entendi muy bien es si se trabaja sobre el archivo demo.py (que ya tiene una implementación de la herencia) o ese lo ignoramos completamente y era solo para echar un vistazo.

**Comment by iqacevedo** [comment]
Si quieres puedes usar el mismo archivo o utilizar otro, queda a tu criterio, la idea de demo.py es que vean como se trabajaba con los métodos que interactuan con la interfaz.

Saludos !
