### ISSUE TITLE
Cargar y guardar partidas

### ISSUE THREAD

**Issue by raimundoloeser** [IIC2233/syllabus#199]
Asumimos que los archivos 'vehiculos.csv' y 'pilotos.csv' siempre existen? o lo vemos igual que con la tarea 00 (reviasndo con path.exists().
Me bajo la duda porque en esta tarea te pasan esos archivos y vienen con datos.
Gracias

**Comment by DCCollao** [comment]
Hola!

Puedes asumir que existirán y se encontrarán dentro de la carpeta donde revisaremos tu tarea (T01), pero no que serán iguales a los que te entregamos. Para más información #126
