### ISSUE TITLE
Duda tamaños de ventanas

### ISSUE THREAD

**Issue by mvvaldes** [IIC2233/Syllabus#199]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, mi duda es que si debo escribir mi programa pensando en que el tamaño de las ventanas puede cambiar o lo puedo considerar como el que fijé yo. Por ejemplo para cuando la mira debe aparecer a la mitad de la pantalla o cuando el alien rebota en el borde.

Gracias!

**Comment by lfb1206** [comment]
Buenas noches, puedes hacer el supuesto de que no se modificará el tamaño de la ventana durante la ejecución del código. Si de todas formas quieres que la mira quede en el centro de la pantalla, independiente del tamaño de esta, puedes utilizar métodos de pyqt para conseguir el tamaño de la ventana, te dejo un link que muestra estos métodos.
https://doc.qt.io/archives/qt-4.8/application-windows.html#window-geometry
