### ISSUE TITLE
Librerias pre instaladas  Readme

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2233/syllabus#199]
hola tengo una duda, las librerias preinstaladas de python como math, os, random, etc
deben ser especificadas en el Readme?
porque solamente hay una sección de librerias pero es para poner librerías que requieren instalación externa

**Comment by lily416** [comment]
Con "Librerías externas" se refiere a módulos que tu no creaste y que importas en tu código. Por lo que debes especificar todas las librerías que utilizaste en tu código, ya sean que vengan preinstaladas o no.

Te recomiendo revisar los [Readme de ejemplo](https://github.com/IIC2233/syllabus/tree/master/Tareas/Ejemplos%20Readmes) que se encuentran en el Syllabus, para que veas distintas formas de organizar su contenido.

Saludos 👋🐦
