### ISSUE TITLE
Cura de la poblacion

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#199]
No entiendo bien que hace el progreso de la cura (a que se le aplica este progreso, que hace, etc). Por favor si alguien me lo pudiera explicar bien.
Otra cosa que no entiendo es cuando se descubre la cura y se elige un pais para propagar la cura, cada persona infectada por dia se cura en un 25% o cada persona infectada tiene una probabilidad de 0.25 de curarse y esto se multiplica por la tasa resistencia a la medicina de la infeccion.

**Comment by iqacevedo** [comment]
Hola !
Respecto al progreso de la cura funciona de la siguiente manera:
i) Humanos intentan descubrir la enfermedad
ii) Una vez que se descubre la enfermedad deben descubrir la cura. Entonces el progreso de la cura es el porcentaje que se ha descubierto de la cura (parten en 0% y deben llegar a 100%).
iii) Una vez que se termina de descubrir la cura, esta se comienza a repartir en un país. Cada persona infectada de ese país tiene 0.25 * resistencia_a_la_medicina probabilidad de curarse por día.

Espero que te quede claro.
Saludos !
