### ISSUE TITLE
Dónde encontrar el archivo setup_test.py 

### ISSUE THREAD

**Issue by lsschmitz** [IIC2233/syllabus#2]
- **Windows :**
- **Python :**

- Foto del error:
![image](https://user-images.githubusercontent.com/69091789/90079171-2a0f1e00-dcd5-11ea-9cdb-fb7132d70ac0.png)

- Descripción del problema:en el video la ayudante usa un archivo para comprobar que instalo python de forma corretca, de donde se descarga ese archivo? Que ya descargue python pero no se si instale bien pyqt5

**Comment by lily416** [comment]
Hola @lsschmitz, 

Primero que todo/nada, muchas gracias por avisar 🙇  
Acabamos de subir los archivos a Canvas y prontamente se subirán al Siding de la sección 4.

Saludos y que tengas una buena semana 👋🐍
