### ISSUE TITLE
Mac (m2)

### ISSUE THREAD

**Issue by Cataarenas** [IIC2233/Syllabus#2]
- **Sistema Operativo:** MacOS Ventura
- **Programa a instalar:** PyQt5

- Foto del error:

- Descripción del problema:
 No reconoce el comando brew, ustedes pusieron otra opción (si no me equivoco con Pipe, pero no lo reconoce) busque en internet como hacer que reconozca brew, pero no me funciona pese a que según los pasos lo hice bien.

**Comment by tomastrivino** [comment]
Holi, no soy profe pero hace un tiempo tuve dramas para instalar PyQt5 en mi Mac M1. La verdad es que podría ser más complejo, por temas de compatibilidad, instalar PyQt en un mac basado en ARM, pero se puede :D 

Mientras tanto, te comento que brew es un comando al que tienes acceso una vez que instalas Homebrew en tu Mac. Puedes acceder a la guía de instalación en el enlace siguiente --> https://brew.sh/.

**Comment by franciscares** [comment]
Hola @Cataarenas ! Te recomiendo ver la issue [#3 ](https://github.com/IIC2233/Syllabus/issues/3)
