### ISSUE TITLE
Configuración de PyQt5

### ISSUE THREAD

**Issue by benjastraub** [IIC2233/Syllabus#2]
Instalé PyQt5 y sale todo bien, pero cuando ocupo `import PyQt5` para verificar que esté instalado correctamente  me aparece lo siguiente: `-bash: import: command not found`

**Comment by fringlesinthestreet** [comment]
Si estas en la terminal debes primero inicializar python. Escribe `python3` en el terminal y luego prueba el `import PyQt5`.

**Comment by benjastraub** [comment]
Ahora lo hice y me aparece `Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5'`

**Comment by fringlesinthestreet** [comment]
Eso quiere decir que no se instaló correctamente.

¿Qué sistema operativo tienes?, ¿Seguiste los pasos de la wiki del curso?

**Comment by benjastraub** [comment]
Tengo macOS 10.12.6. Seguí los pasos de la wiki, de hecho, si trato de instalarlo de nuevo me dice que ya está instalado

**Comment by fringlesinthestreet** [comment]
Prueba con este [link](https://stackoverflow.com/questions/30145751/python3-cant-find-and-import-pyqt5).

**Comment by fringlesinthestreet** [comment]
Avisa si funciona o no :P.

**Comment by jerosalazar** [comment]
Hola, tengo iOS  10.11 y llegue al mismo problema tratando de realizar `import  PyQt5`. Cuando intente con `pip3 uninstall pyqt5`, me dice "Cannot uninstall requirement pyqt5, not installed". Finalmente viendo el link del foro no entendí bien cuando hablaban acerca de Python Path

**Comment by MarceloSaldias** [comment]
Me pasa lo mismo que a benjastraub (No module named PyQt5) pero yo estoy utilizando Ubuntu :c

**Comment by akaminetzkyp** [comment]
Si tienen Mac o Ubuntu prueben esto.

1. Abrir el terminal.
2. Escribir `cd`.
3. Escribir `nano .bash_profile`.
4. Se va a abrir un editor de texto. Agregar lo siguiente: `export PYTHONPATH=`brew --prefix`/lib/python3.6/site-packages:$PYTHONPATH`.
5. Apretar ctrl+o para guardar y después ctrl+x para salir del editor.
6. Escribir `source ~/.bash_profile` en el terminal.

A uno de sus compañeros le funcionó esto. Cuéntenme qué onda! :)

**Comment by benjastraub** [comment]
Me funcionó desinstalando e instalándolo de nuevo varias veces 🙃

**Comment by cfernandez9** [comment]
Hola, probé instalar con pip3 install pyqt5 y me salen muchas lineas rojas de error y también probé con brew y me sale -bash: brew: command not found, qué puedo hacer?? muchas gracias

**Comment by fringlesinthestreet** [comment]
Que salga `-bash: brew: command not found` es porque brew no está instalado.

¿Podrías mostrar el mensaje de error que sale al poner `pip3 install pyqt5`? Si es error de permiso puedes probar con `sudo pip3 install pyqt5`

**Comment by cfernandez9** [comment]
<img width="1186" alt="captura de pantalla 2017-08-09 a las 19 08 02" src="https://user-images.githubusercontent.com/30667450/29147663-72aed094-7d36-11e7-8e6d-c3b0a09b9ec6.png">

**Comment by aurodriguez** [comment]
Hola, me aparece esto cuando copio y pego en el terminal para instalar Homebrew:

![screen shot 2017-08-09 at 20 32 04](https://user-images.githubusercontent.com/28511788/29149367-9ed5c73a-7d41-11e7-91ff-12ac63cda63b.png)

Y esto cuando corro el script de prueba: 

![screen shot 2017-08-09 at 20 34 03](https://user-images.githubusercontent.com/28511788/29149396-dd1f3e40-7d41-11e7-951c-5a2c48284627.png)

¿Que puedo hacer?

**Comment by andresfdezc** [comment]
@aurodriguez Ese tipo de error es típico de versiones muy antiguas de MacOs o OS X. Lo único que te puedo recomendar es que actualices el sistema operativo de tu mac, aunque sea una lata.
