### ISSUE TITLE
error al instalar python

### ISSUE THREAD

**Issue by Liper1** [IIC2233/Syllabus#2]
- Windows 11
- python 3 en debian

- Foto del error:
![image](https://github.com/IIC2233/Syllabus/assets/130397899/e88d04cf-edb3-455e-a400-ffef98ec52be)

- Descripción del problema:
- segui paso a paso la guia de instalacion pero al momento de poner " sudo apt install python3.10 python3-pip" me da error

**Comment by Hernan4444** [comment]
Hola @Liper1 

Dado que "glob" no está encontrando python3.10, vamos a intentar instalarlo de una forma más "manual"

Lo primero será verificar que esté todo actualizado en debian.

```cmd
sudo apt update && sudo apt upgrade 
```

Lo segundo será instalar muchas cosas que necesita debian. Para esto, escribir el siguiente comando (que es largo)

```cmd
sudo apt install wget build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev  
```

Luego, instalaremos python. Para esto, correr los siguientes comandos (uno por uno)

1.  (descargar python) `wget https://www.python.org/ftp/python/3.10.8/Python-3.10.8.tgz `
2. (descomprimir archivo) `tar xzf Python-3.10.8.tgz `
3. (acceder a la carpeta de python) `cd Python-3.10.8 `
4. (activar configuración) `./configure --enable-optimizations `
5. (instalar) `make altinstall `

Luego de terminar esos pasos, si en esa terminal haces `python3.10 -V`. Debería salir `"Python 3.10.8"`. En ese caso ya estamos listos. Luego, cada vez que nosotros pidamos hacer `python3` o `py`, tu tendrías que hacer `python3.10`.

Avisanos cómo te va con esta opción, sino para buscar alternativas,
Saludosヾ(＾-＾)ノ

**Comment by Liper1** [comment]
Hola @Hernan4444 me ayudo lo que me diste, pero al momento de poner "make altinstall" dio error, pero busque el error y salía que pusiera "make" lo puse y después de muchos minutos termino, ahí puse nuevamente "make altinstall" y si me funciono, muchas gracias, problema solucionado. O(∩_∩)O

**Comment by JosefaInostroza7** [comment]
Hola, tuve el mismo problema e intenté con el paso a paso que dejó acá pero al momento de correr el comando  "make altinstall" me arroja error, aún intentando lo que comentó mi compañero. Adjunto imagen. También tengo Windows 11.
![Captura de pantalla 2023-08-10 173836](https://github.com/IIC2233/Syllabus/assets/141850856/27da1a4d-e445-475d-a4fd-ee5516d1340a)

**Comment by Hernan4444** [comment]
Hola @JosefaInostroza7 

Lo que ocurre es que no tienes permisos para ejecutar ese problema. En ese caso, te recomiendo abrir PowerShell como administrador y ahí hacer `WSL` para entrear al modo subsystem, y ahí si ejecutar el comando.

Otra opción, es hacer `sudo make altinstall`, con el comando `sudo` podrás activar el modo administrador y ahí si tendrás los permisos.

Intenta con estas opciones y nos cuentas c:
Saludosヾ(＾-＾)ノ

**Comment by NicholasRoch** [comment]
hola! esto me aparece de problema! como lo soluciono? mas adelante tratando de isntalar jupyter no puedo porque me indica que no tengo instalado pip, que puedo hacer? 


https://imgur.com/a/CPSn7lq

**Comment by Hernan4444** [comment]
Hola @NicholasRoch 

El error es que estás poniendo un punto (`.`) al final de cada comando, hay que hacer `python3 -V`

Luego, para el segundo tema, ¿qué te sale si haces `python3 -m pip -V` ?

**Comment by JosefaInostroza7** [comment]
> Hola @JosefaInostroza7
> 
> Lo que ocurre es que no tienes permisos para ejecutar ese problema. En ese caso, te recomiendo abrir PowerShell como administrador y ahí hacer `WSL` para entrear al modo subsystem, y ahí si ejecutar el comando.
> 
> Otra opción, es hacer `sudo make altinstall`, con el comando `sudo` podrás activar el modo administrador y ahí si tendrás los permisos.
> 
> Intenta con estas opciones y nos cuentas c: Saludosヾ(＾-＾)ノ

Ya pude instalarlo! Muchas gracias ^^

**Comment by Dvckhv** [comment]
Hola @BenjaMedinaPUC  por orden del foro, ¿podrias crear una nueva issue con tu problema? Ya que esta fue marcada como resuelta y tu duda no se relaciona a esto.
