### ISSUE TITLE
Hola! En la página de python no pude instalar una versión 3.8 por lo que instalé la versión 3.9.6. Me servirá esta versión?

### ISSUE THREAD

**Issue by gonzaloi21** [IIC2233/Syllabus#2]
- **Sistema Operativo:**
- **Programa a instalar:**

- Foto del error:

- Descripción del problema:

**Comment by Christian-Klempau** [comment]
Hola Gonzalo!
En rigor, si tienes instalada una versión de Python superior, pero no utilizas ningunas de las _features_  nuevas de dicha versión, lo más probable es que Python no te falle si ejecutas un programa para una versión anterior.

De igual manera, mi recomendación personal es tratar de no hacerlo, ya que si al momento de corregir los ayudantes tienen un problema relacionado a la discrepancia de versiones, no nos haremos responsables y no tendrás puntaje, ya que lo solicitado es utilizar `3.8.X`.

Por lo mismo, te recomiendo tratar de re-instalar Python con la versión 3.8. ¿Qué sistema operativo tienes, y por qué no pudiste instalar 3.8?

**Comment by Christian-Klempau** [comment]
Lo pudiste resolver? Trata de no cerrar las issues, para que otros alumnos las puedan ver!

**Comment by gonzaloi21** [comment]
Sii, pude instalarlo sin problemas! Aah no caché, para la próxima lo dejaré abierto. Gracias!
