### ISSUE TITLE
Mini distorsión de pantalla cuando abro Bash. Problemático?

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#2]
Hola! Muy corto: cuando abro git bash, me acomoda ponerlo en una mitad de mi pantalla, y de repente me di cuenta que la otra mitad tenía unas líneas delgadas horizontales en las que la imagen sale distorsionada, que casi no se notan. Creí que se me estaba empezaaaando a echar a perder la pantalla en general (a.k.a. vi mi vida pasar frente a mis ojos), hasta que caché que solo se veía así con la ventana de bash abierta—incluso desaparece cuando está minimizada. Le pasa al resto? Debería preocuparme?

Gracias de antemano :)

P.D.: tengo Windows 10 y mi computador ya tiene un año pero gracias a las maravillas de las SSD sigue corriendo bacán, a veces me fallan temas de conexión pero nunca ha tenido problemas de imagen

**Comment by entamburini** [comment]
Hola! :D 

La verdad es que ese tipo de errores son muy específicos del computador que estás usando. Las distorsiones que ves en tu pantalla puede deberse a la combinación de colores que genera git bash y tu escritorio estén provocando esa distorsión. 

No puedo decirte si es algo normal o no, pero si te puedo preguntar si es que usas el powershell, te sigue apareciendo esa distorsión?, si es sólo de un programa en específico puedes probar actualizando los drivers :) 

Saludos! :v:

**Comment by sbcorrea** [comment]
Muchas gracias!
