### ISSUE TITLE
Repositorio - error during import 

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#2]
Estaba en esta parte
![imagen](https://user-images.githubusercontent.com/37153467/37107895-4ea77952-2214-11e8-957f-f8e99dcd6584.png)

y luego me salió esto
![imagen](https://user-images.githubusercontent.com/37153467/37107967-8ba25804-2214-11e8-90ca-c169fe17db5f.png)

y mi repo está así
![imagen](https://user-images.githubusercontent.com/37153467/37108012-a62de8c8-2214-11e8-8d67-4a868a7ecb00.png)
![imagen](https://user-images.githubusercontent.com/37153467/37108045-b9814500-2214-11e8-8095-e6ddc1e30547.png)

**Comment by naquiroz** [comment]
Me paso algo similar, envie un correo al correo de ayudantes y lo solucionaron.

**Comment by jmwielandt** [comment]
También se solucionó el mío
Gracias!
