### ISSUE TITLE
El form a llenar "Usuario Github" no permite poner Usuario UC y problemas con fechas de evaluaciones.

### ISSUE THREAD

**Issue by Juan379** [IIC2233/syllabus#2]
Hola!
Me acaba de llegar el mail de los profesores de bienvenida y en este se incluye un link a la página oficial del curso y también un form que hay que llenar para la inscripción a este.
Escribo este issue ya que al tratar de llenar el form con mi usuario UC no lo pude hacer ya que solo permite llenar con usuarios que no contengan "caracteres especiales", en mi caso mi usuario contiene un punto por lo que no lo puedo llenar.
Por otro lado, para poder organizar el semestre busque las fechas de las evaluaciones e instancias recuperativas pero todas estas tienen fechas del semestre pasado, por lo que supongo que necesitan actualización!

Muchas gracias de antemano!

**Comment by entamburini** [comment]
¡Hola! :D 

El tema del form ya ha sido solucionado. Para las evaluaciones, te recomiendo que revises el [calendario](https://iic2233.github.io/calendario/), ahí está toda la planificación. ¿Donde estás viendo las fechas? :o

**Comment by Juan379** [comment]
Muchas gracias!
Estoy viendo las fechas en el link proporcionado del programa oficial completo del curso que esta en la sección Información del curso de la página.

**Comment by entamburini** [comment]
Todo revisado y actualizado, gracias por el aviso Juan! :)
