### ISSUE TITLE
registro

### ISSUE THREAD

**Issue by lefischer** [IIC2233/Syllabus#2]
hola
al intentar registrarme me aparece error 404

**Comment by FernandoPieressa** [comment]
@aaossa @bamavrakis

**Comment by bamavrakis** [comment]
Hola! El registro aún no está completamente implementado. Cuando esté listo les avisaremos para que se registren.
Saludos!

**Comment by FranSchiaffino934** [comment]
Hola! Tengo una consulta 
¿Cómo se puede hacer para abrir el calendario (o el archivo que lo contiene), solo me aparece calendario.md demo?
Saludos :)

**Comment by FernandoPieressa** [comment]
Tampoco esta listo, estará disponible próximamente

**Comment by aaossa** [comment]
@FranSchiaffino934 la página ya está actualizada. Puedes descargar el `.ics` y ver el calendario en la misma página (agregalo a tu propio calendario con el `+` de la esquina inferior derecha del *iframe*). Puedes ver el calendario [aquí](https://iic2233.github.io/calendario/)

**Comment by FranSchiaffino934** [comment]
Gracias :)

**Comment by aaossa** [comment]
La aplicación ya está funcionando :grin:
