### ISSUE TITLE
Abrir archivos .ipynb jupyter mac

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#20]
Hola! Ya instalé Jupyter por el terminal (soy mac) pero al intentar abrir algún archivo .ipynb, como los de la ayudantía, el computador me dice que "no hay ninguna aplicación definida para abrir el documento *.ipynb".

**Comment by andresfdezc** [comment]
En el terminal, dirígete a la carpeta donde está el archivo que quieras abrir. Luego ejecuta:
```bash
$ jupyter notebook
```
Esto abrirá la aplicación en tu navegador o te dará un link para abrirla. Desde ahí puedes editar el notebook o correrlo.

**Comment by ifcarrera** [comment]
Hola! Tal como dice Andrés debes hacerlo desde tu terminal, no sirve que abras el archivo haciendo "doble click".

Y para complementa un poco, desde la terminal te cambias de carpeta con el comando cd.

Saludos

**Comment by bedefrunner** [comment]
Muchas gracias a los dos! Ahora entendí jajaj

**Comment by akaminetzkyp** [comment]
Un comentario para todos! Si no tienen instalado Jupyter, los archivos .ipynb también se pueden ver directamente en GitHub
