### ISSUE TITLE
Herencia en POO

### ISSUE THREAD

**Issue by mskdancers** [IIC2233/Syllabus#20]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Tengo una duda no se nada
- uno 
- dos 
- tres

**Comment by 3rdPix** [comment]
Hola @mskdancers ! Te recomiendo estudiar los contenidos ☺️
