### ISSUE TITLE
Librerías permitidas, no permitidas y malas prácticas T0

### ISSUE THREAD

**Issue by gecoli** [IIC2233/Syllabus#20]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:
 
> Puedo usar la librería nombre_librería para hacer explicación_de_lo_que_quiero_hacer
 
¡Recuerden especificar en su README qué librerías utilizan!
 
---
 
## ✅ **Librerías Permitidas**
- collections
- dataclasses
- datetime
- os
- random
- string
- sys.exit
- copy
 
## ❌ **Librerías Prohibidas**
- csv
- functools
- itertools
- numpy
- pathlib
- pandas
- shutil
- re
- pickle
 
## ☠️ **_Built-ins_ Prohibidos**
El uso de alguna de las siguiente funciones es automáticamente un 1,0 sin discusión. 😭
- exec ([explicación](https://github.com/IIC2233/syllabus-2020-1/issues/591#issuecomment-616773839))
- eval ([explicación](https://github.com/IIC2233/syllabus-2020-1/issues/591#issuecomment-616773839))
- exception `(try/except)` (el uso correcto de `try/except` es contenido que se verá en una futura semana del curso, por lo que se espera que las tareas previas a esa fecha puedan ser resueltas sin este `built-in`)
 

¡Ánimo y éxito en sus tareas! 💣🐢🏰

**Comment by GuilleStanke** [comment]
Puedo usar la librería math para calcular una raiz cuadrada?

**Comment by gonzalezguerra** [comment]
Puedo usar la función isnumeric() para saber si un str esta formado por numeros

**Comment by SantiagoDLCB** [comment]
se puede utilizar la libreria copy para realizar deepcopy?

**Comment by matiasmasjuan** [comment]
Holaa!
@gonzalezguerra : **Sí**, puedes usar el _built-in_ ```ìsnumeric()``` para saber si un ```str```está formado por números.
@SantiagoDLCB : **Sí**, puedes usar ```deepcopy```

**Comment by Mcroquevielle** [comment]
Hola! Una pregunta, se puede usar el comando os.path.exists () para ver si un archivo existe?

**Comment by c4ebt** [comment]
Puedo usar la librería `itertools` para generar todas las permutaciones de una lista?

**Comment by matiasmasjuan** [comment]
Hola @c4ebt !

**Comment by tomastrivino** [comment]
Hola, se puede usar la librería math?

**Comment by matiasmasjuan** [comment]
Hola @tomastrivino ! ¿Para qué la quieres utilizar?

**Comment by DieguinBombin** [comment]
Hola, de casualidad se puede importar la libreria time para que no sean tan "de golpe" algunas ejecuciones de la consola? gracias de antemano

**Comment by matiasmasjuan** [comment]
@DieguinBombin: **No puedes** ```time```. Si bien es cierto que agregar *delays* puede hacer que el programa sea mas realista, el uso de pausas en el código puede ocasionar molestias al momento de corregir 😢. Imaginen que en la corrección ejecutamos su tarea varias veces, al momento de tener pausas lo único que ocasionas es que el tiempo de revisión aumente considerablemente.

**Comment by Matoclip** [comment]
Hola, se puede utilizar el comando `break` para terminar un `for in range`? De antemano muchas gracias por la respuesta!

**Comment by pedrozavalat** [comment]
Hola @Matoclip!,
es valido usar ```break```, y no será considerado mala practica. 
Saludos :)

**Comment by pablolagosE** [comment]
Hola!
Tengo dos preguntas
1) Recuerdo que en los contenidos de la semana 0 se mencionaba que ocupar "from modulo import * " era una mala práctica. ¿Se descontará puntaje por eso? (es mas cómodo para no escribir más lineas de código ni pasarme de los 100 caracteres permitidos)

2) ¿Se puede ocupar el modulo typing (también aparecía en la semana 0) para declarar que una función puede recibir un argumento que no se sabe su tipo?
Sería algo del estilo:
def funcion(input: Any) -> bool:

**Comment by MariaJoseSilva** [comment]
Hola! Espero estén super

En los descuentos hay una sección "Cambio de líneas" que indica  "por tarea, se permite cambiar hasta 20 líneas de código. Esta solicitud de cambio solamente se puede realizar mediante el mismo README o bien en el formulario de recorrección de la tarea"
A qué se refiere con esto?
Muchas gracias!

**Comment by tremendapithon** [comment]
Tengo una duda respecto a la utilización del módulo time con su función sleep(), si es válida usarla y que sea especificado en el readme.

**Comment by Hernan4444** [comment]
Hola @pablolagosE 

1. Si se descontará puntaje. `import *` tambien es una mala práctica en PEP8, así que por ese lado se puede aplicar descuento.
2. Si, puedes usar `typing`.

------------

Hola @MariaJoseSilva 

Viendo el caso de la recorrección, puede ser que una vez recibida la nota, te das cuenta que algunos ítems no tuviste puntaje, pero que se puede arreglar cambiando un par de líneas. En ese caso puedes pedir que te cambien esas líneas (se aplicará un descuento proporcional al número de líneas cambiadas) y se corregirá nuevamente la tarea para poder otorgar el puntaje donde corresponda. Cuando se acerque el proceso de re-corrección se explicará más detalle sobre la política de cambio de línea 😄 

Sobre hacer esto en el Readme, puede ser que a últimas horas de entregar la tarea te das cuenta de algún detalle, pero no alcanzas a editar el código y testearlo, así que solo pides, a traves del readme, que te cambien esas líneas. Esto ocurre en algunos casos donde el estudiante no tiene el pc en mano para programar, pero edita el readme desde la página web (no es recomendao hacer eso).

------------

Hola @tremendapithon, te dejo la respuesta que le entregamos a otro alumno en esta misma issue:

> DieguinBombin: **No puedes** `time`. Si bien es cierto que agregar _delays_ puede hacer que el programa sea mas realista, el uso de pausas en el código puede ocasionar molestias al momento de corregir 😢. Imaginen que en la corrección ejecutamos su tarea varias veces, al momento de tener pausas lo único que ocasionas es que el tiempo de revisión aumente considerablemente.

------------

Saludos a todos c:

**Comment by tremendapithon** [comment]
Hola buenas tardes puedo usar "\" cuando sobrepaso las 100 líneas?

**Comment by pedrozavalat** [comment]
Hola @tremendapithon !,
¿Te refieres a usar ```"\"``` para evitar sobrepasar las 100 lineas de código?. En este caso, no será considerado una mala práctica.
Saludos :)

**Comment by TomasAguirrebena** [comment]
con respecto a los 100 caracteres por linea de codigo, que pasa si tengo no se 90 caracteres de codigo, puedo poner un comentario a su lado que pase los 100 caracteres ? y si no puedo como podria comentar esa linea en especifico.

**Comment by gecoli** [comment]
¡Hola, @TomasAguirrebena !
Los comentarios suelen contarse dentro de los 100 caracteres, así que te recomiendo que realices el comentario en la línea inferior a la cual quieres comentar. 

Respecto al path, no es normal que una ruta relativa tenga más de 100 caracteres, así que deberías ver que estás trabajando con la ruta correcta 😊

**Comment by TomasAguirrebena** [comment]
Hola, @gecoli, gracias por responder y perdón por la hora.
Y para las funciones atómicas las líneas de comentarios no cuentan supongo, y con respecto al path no me encontraba la dirección del archivo que quería introducir el usuario entonces puse el path desde C: y por eso es tan largo, no supe hacerlo de otra manera.

**Comment by gecoli** [comment]
@TomasAguirrebena 
La ruta que me describes es precisamente la que no deben ocupar (una path global). Las rutas relativas son aquellas que dependen de la carpeta donde estén. Por ejemplo, si en la misma carpeta están dos archivos, `example.py` y `functions.py`, la ruta relativa de cada una es únicamente su nombre. Si `functions.py` estuviera en la carpeta `/views` dentro de la carpeta donde está `example.py`, entonces la ruta relativa sería `/views/functions.py`




Aquí hay una explicación similar
https://www.discoduroderoer.es/rutas-relativas-y-absolutas/


Respecto a lo otro, los comentarios no se consideran como líneas de código ☺️

**Comment by TomasAguirrebena** [comment]
@gecoli 
logre entender lo de la ruta relativa pero no se por que aun python no logra encontrar el archivo, lo probe en mi entorno local y si lo logre pero no veo las diferencias en mi respositorio.

**Comment by MariaJoseSilva** [comment]
Hola! 

Dentro de los descuentos se encuentra el "Uso de variables globales", esto se refiere a que no se pueden usar? o qué hay que usarlas de cierta manera?

Muchas gracias!

**Comment by tnaspee** [comment]
Hola! Se puede ocupar `math` para calcular factoriales?

**Comment by matiasmasjuan** [comment]
@TomasAguirrebena : Si estas trabajando con vscode, recuerda siempre abrir el repositorio como carpeta dentro del editor. Para esto basta con pulsar la opción de _open folder_ de vscode y seleccionar la carpeta T0 en la que estas trabajando. De esta forma no tendrás problemas con los paths relativos.

@MariaJoseSilva : Las variables globales son todas aquellas variables que son definidas fuera de cualquier función o método. En general son una mala práctica ya que si bien te permiten definirlas en cualquier parte, también pueden ser alteradas dentro de cualquier función o método. Es decir, puede que dentro de una función definas una nueva variable con el mismo nombre que tu variable global fuera de la función, y sin querer puedes cambiarle el valor de dicha variable. A simple vista no se ve tan terrible, pero a medida que los códigos crecen es posible que esto conduzca a errores muy difíciles de _debuggear_ y por lo mismo lo consideramos dentro del descuento del Pep8. Ahora bien, para efectos del curso solamente descontaremos por el uso explicito de ```global <nombre_variable>``` dentro del código.

@tnaspee : **Sí**, puedes usar ```math```para calcular el factorial de un número ```N```.

Saludos 😄 !

**Comment by Coder-Mushroom** [comment]
Hola!
Una consulta, ¿se puede usar `sys.setrecursionlimit()` para aumentar la cantidad de recursiones posibles? (a un número menor que 10⁷)

**Comment by matiasmasjuan** [comment]
Hola @Coder-Mushroom : Puedes usar ```sys.setrecursionlimit()```, pero **debes** notificar en tu readme sobre esta decisión y mencionar cómo desactivarlo en caso de que ocasione problemas al momento de ejecutar tu programa. De todas formas, insistimos que al ejecutar tu tarea probaremos tableros simples, por lo que no debería ser necesario utilizar esa función.
Saludos! 😄

**Comment by amundaca02** [comment]
Hola!, entiendo que no se puede usar la libreria "itertools", sin embargo en la documentacion de python de la libreria hay definida una función equivalente a un metodo de esta que me podría servir. Puedo utilizarlo citandolo adecuadamente?

**Comment by matiasmasjuan** [comment]
Hola @amundaca02 : En general si prohibimos una librería es porque no queremos que ocupen herramientas que buscamos evaluar en una tarea (en este caso, contenidos de introducción a la programación) y lo mismo para casos de funciones que realicen algo similar. En particular, si esta función que mencionas ocupa comandos como ```yield```, entonces dicha función está **prohibida**, ya que no buscamos evaluar temas de generadores. Si esta función no tiene estas cosas, mejor dime cuál es para explorarla.

Saludos!

**Comment by gsinay** [comment]
Hola! Se puede ocupar la librería ```pprint```?

**Comment by gsinay** [comment]
@matiasmasjuan Perdona :sweat_smile:. Básicamente para imprimir listas grandes de forma ordenada pero sin tener que llamar a un for loop.

**Comment by matiasmasjuan** [comment]
Si, puedes usar **pprint** para eso. Pero recuerda que esto no es necesario en la tarea. En ningún momento pedimos imprimir listas, sino que son tableros que deben visualizarse a través de la función ```imprimir_tablero```.

Saludos!
