### ISSUE TITLE
Instalar Jupyter 

### ISSUE THREAD

**Issue by lsschmitz** [IIC2233/syllabus#20]
![image](https://user-images.githubusercontent.com/69091789/90253321-f6d0aa00-de0e-11ea-9d01-e045bf10e3e8.png)
En el video de jupyter muestran un archivo que hay que abrir (foto adjunta), pero no lo encuentro. Alguien me podria decir donde esta?

**Comment by gatochico** [comment]
Hola! 

El archivo `1-guía-de-estilo.ipynb` es el primer notebook de los contenidos de la [semana 0](https://github.com/IIC2233/contenidos/blob/master/semana-00/1-gu%C3%ADa-de-estilo.ipynb). 

Para descargar estos contenidos debes clonar el repositorio en tu computadora. Primero debes tener descargado Git en tu computador, luego debes abrir Git Bash y moverte mediante el [comando cd](https://www.youtube.com/watch?v=jLEGKsMoSIY) al directorio/carpeta donde desees descargar los contenidos. De forma alternativa, puedes abrir la carpeta/escritorio de forma normal y hacer **click derecho > Git Bash Here** para que se te abra git bash ubicado en esa dirección de forma inmediata. 

Una vez abierta la terminal de Git Bash, puedes descargar los contenidos mediante el comando `git clone https://github.com/IIC2233/contenidos.git` y se deberían descargar en la carpeta donde abriste/te posicionaste con Git Bash. Dentro de los contenidos encontrarás el archivo .ipynb y podrás seguir el video 🎉 

Todos los pasos que mencioné anteriormente corresponden al uso de Git, herramienta que se trabajará en la clase de la próxima semana en el curso. 

Cualquier duda que quede, no dudes en comentar!
