### ISSUE TITLE
Error al configurar Atom

### ISSUE THREAD

**Issue by matioprts** [IIC2233/syllabus#20]
Buenas. Estoy intentando configurar Atom como se indica en la página del curso, instalé los packages de linter y linter-pylint sin problemas a través de cmd, pero al intentar descargar linter-flake8, linter-pycodestyle/linter-pep8 y script me muestra este tipo de error, que ocurre tanto al descargarlo a través de Atom como a través de una consola cmd o git bash. Tanto pep8, pycodestyle y flake8 se encuentran instalados correctamente en la carpeta de scripts de python. Ya agregué al path: pip, apm y npm. Gracias de antemano.
![error npm](https://user-images.githubusercontent.com/48302183/54498287-27dc4080-48e4-11e9-9ca3-50129577a442.jpg)

**Comment by bimartinez** [comment]
Hola @matioprts 

Sorry lo tarde, lograste solucionarlo? Si no,  puedes probar reinstalando Atom:atom:. Y mientras puedes enviar los datos del archivo `.log` que te dice ahi?

Saludos!

**Comment by matioprts** [comment]
Buenas, logré instalar algunos packages pero no todos los que
quiero/necesito. Ya instale chrome, reinstale atom 2 veces, instalé node.js
y todos los paths estan bien. El error que me indica al intentar instalar
minimap y autocomplete-python (los 2 packages que me faltan por instalar)
es el siguiente: (adjunto .txt con los datos del debug.log)

npm ERR! Unexpected end of JSON input while parsing near

**Comment by matioprts** [comment]
Buenas, logré instalar algunos packages pero no todos. Ya instale chrome, reinstale atom 2 veces, instalé node.js y todos los paths estan bien. El error que me indica al intentar instalar minimap y autocomplete-python (los 2 packages que me faltan por instalar) es el siguiente: 
npm ERR! Unexpected end of JSON input while parsing near

El archivo debug.log contiene:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\opmat\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\opmat\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\opmat\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\opmat\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/autocomplete-python/versions/1.14.0/tarball',
1 verbose cli   '--runtime=electron',
1 verbose cli   '--target=2.0.18',
1 verbose cli   '--dist-url=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v8.9.3
4 verbose npm-session 6e242cb0cf97b034
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://www.atom.io/api/packages/autocomplete-python/versions/1.14.0/tarball 4120ms
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/autocomplete-python/versions/1.14.0/tarball fetched in 4342ms
9 timing stage:loadCurrentTree Completed in 8568ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule autocomplete-python@1.14.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/fuzzaldrin-plus 548ms (from cache)
18 silly pacote range manifest for fuzzaldrin-plus@^0.3.1 fetched in 554ms
19 silly resolveWithNewModule fuzzaldrin-plus@0.3.1 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/kite-installer 593ms (from cache)
21 silly pacote range manifest for kite-installer@^3.7.0 fetched in 600ms
22 silly resolveWithNewModule kite-installer@3.7.0 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/underscore 601ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/atom-space-pen-views 608ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/space-pen 608ms (from cache)
26 http fetch GET 304 https://registry.npmjs.org/mixpanel 613ms (from cache)
27 silly pacote range manifest for underscore@^1.8.3 fetched in 623ms
28 silly resolveWithNewModule underscore@1.9.1 checking installable status
29 silly pacote range manifest for mixpanel@^0.5.0 fetched in 640ms
30 silly resolveWithNewModule mixpanel@0.5.0 checking installable status
31 silly pacote range manifest for atom-space-pen-views@~2.1.0 fetched in 650ms
32 silly resolveWithNewModule atom-space-pen-views@2.1.1 checking installable status
33 http fetch GET 304 https://registry.npmjs.org/selector-kit 651ms (from cache)
34 http fetch GET 304 https://registry.npmjs.org/atom-slick 654ms (from cache)
35 silly pacote range manifest for atom-slick@^2.0.0 fetched in 663ms
36 silly resolveWithNewModule atom-slick@2.0.0 checking installable status
37 silly pacote range manifest for space-pen@^5.1.2 fetched in 661ms
38 silly resolveWithNewModule space-pen@5.1.2 checking installable status
39 silly pacote range manifest for selector-kit@^0.1 fetched in 678ms
40 silly resolveWithNewModule selector-kit@0.1.0 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/fuzzaldrin 183ms (from cache)
42 silly pacote range manifest for fuzzaldrin@^2.1.0 fetched in 191ms
43 silly resolveWithNewModule fuzzaldrin@2.1.0 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/grim 107ms (from cache)
45 http fetch GET 304 https://registry.npmjs.org/jquery 145ms (from cache)
46 silly pacote range manifest for grim@^1.0.0 fetched in 166ms
47 silly resolveWithNewModule grim@1.5.0 checking installable status
48 silly pacote version manifest for jquery@2.1.4 fetched in 166ms
49 silly resolveWithNewModule jquery@2.1.4 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/underscore-plus 284ms (from cache)
51 silly fetchPackageMetaData error for underscore-plus@1.x Unexpected end of JSON input while parsing near '...org/underscore-plus/-'
52 timing stage:rollbackFailedOptional Completed in 0ms
53 timing stage:runTopLevelLifecycles Completed in 9749ms
54 silly saveTree apm-install-dir-119223-1604-8bfp1w.3f537
54 silly saveTree `-- autocomplete-python@1.14.0
54 silly saveTree   +-- atom-slick@2.0.0
54 silly saveTree   +-- atom-space-pen-views@2.1.1
54 silly saveTree   | +-- fuzzaldrin@2.1.0
54 silly saveTree   | `-- space-pen@5.1.2
54 silly saveTree   |   +-- grim@1.5.0
54 silly saveTree   |   `-- jquery@2.1.4
54 silly saveTree   +-- fuzzaldrin-plus@0.3.1
54 silly saveTree   +-- kite-installer@3.7.0
54 silly saveTree   | `-- mixpanel@0.5.0
54 silly saveTree   +-- mixpanel@0.5.0
54 silly saveTree   +-- selector-kit@0.1.0
54 silly saveTree   +-- space-pen@5.1.2
54 silly saveTree   `-- underscore@1.9.1
55 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...org/underscore-plus/-'
55 verbose stack     at JSON.parse (<anonymous>)
55 verbose stack     at parseJson (C:\Users\opmat\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
55 verbose stack     at consumeBody.call.then.buffer (C:\Users\opmat\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
55 verbose stack     at <anonymous>
55 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
56 verbose cwd C:\Users\opmat\AppData\Local\Temp\apm-install-dir-119223-1604-8bfp1w.3f537
57 verbose Windows_NT 10.0.17134
58 verbose argv "C:\\Users\\opmat\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\opmat\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\opmat\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\opmat\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/autocomplete-python/versions/1.14.0/tarball" "--runtime=electron" "--target=2.0.18" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style"
59 verbose node v8.9.3
60 verbose npm  v6.2.0
61 error Unexpected end of JSON input while parsing near '...org/underscore-plus/-'
62 verbose exit [ 1, true ]

**Comment by naquiroz** [comment]
Hola matiorpts ! El paquete que estás tratando de instalar está `deprecated`:💀. Eso significa, como el error dice, que no está siendo mantenido.❌🔨 Yo no uso `Atom` pero recuerdo que cuando lo usaba, me avisaban que iban a dejar de mantenerlo. Mis recomendaciones son dos:

1. Instalar `VSCode` que a mí parecer es mejor que Atom ✔️✔️
2. Instalar la extensión  `atom-ide` que te convierte Atom en un básico `IDE`. Luego instalas el lenguaje de Python en el ide, y estás listo.
Cualquier cosa comentas!
Saludos :v:

**Comment by valerojasm** [comment]
Hola!

Efectivamente como dice @naquiroz, el error que sale en tu screenshot es que el paquete linter-flake8 está deprecado - sin embargo existen otros linters específicos para Python que puedes ocupar. 

Un poco de contexto: el package que se encarga del trabajo de revisar tu código es linter, y para saber qué lenguaje estás ocupando necesitas instalar paquetes complementarios para cada uno de ellos; flake8 es para Python como lo es pylint. Acá te dejo una lista de ellos para que puedas bajar otro: https://atomlinter.github.io

En cuanto a tu segundo error, las últimas versiones de Atom tienen el paquete autocomplete incluido, por lo que puede que tengas un problema por ahí si es que no lo trae y te tira errores instalarlo - revisa por si acaso. El error específicamente dice que no puede parsear un archivo porque está incompleto. Puedes intentar instalarlo por consola también con el comando apm, que es el package manager de Atom. 

Nos avisas cómo te va, saludos!

**Comment by matioprts** [comment]
Pude instalar linter-python sin problemas, en los core packages que incluyen "autocomplete" no se encuentra ninguno que pueda decirse pertenece a python. Al intentar instalar tanto autocomplete como minimap sigue terminando como output el error: npm ERR! unexpected end of JSON input. Existe alguna solución para esto? en caso contrario, ya me estoy acostumbrando a sublime text, que packages recomiendan instalar para esta interfaz? tengo el package control, autopep8 y sublimelinter :)

**Comment by iqacevedo** [comment]
En el semestre 2017-2 estaba [esta guia](https://github.com/IIC2233/Syllabus-2017-2/wiki/Interfaces-de-Desarrollo) en la wiki. Ahí sale sublime y los paquetes que necesitas para trabajar en el curso de manera correcta 😊.
