### ISSUE TITLE
Compilado Issues T0

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/Syllabus#20]
En la siguiente _issue_ encontrarás todas las _issues_ sobre la Tarea 0 que se han realizado hasta el momento, estas están divididas según diferentes temas.
Antes de hacer una nueva _issue_, revisa si tu duda ya fue realizada, así evitamos las _issues_ duplicadas. 😄

### Librerías permitidas, no permitidas y malas prácticas ✔️❌ 
1. #21 
2. #24 
---

### Menu inicio
1. 

### Funcionalidades
1. #81 

### Puntajes
1.

---
### Menú de Juego
1. #58 
2. #42 

### Tablero
1. #27 
3. #30 
4. #45 
5. #51 
6. #63 
7. #66 
8. #77
9. #79 
10. #82 

### Bestias
1. #37
2. #52
3. #43 
4. #69

### Guardado de partida
1. #31 
5. #39 
6. #45 
11. #52
12. #54
13. #55
14. #47 
15. #60 
16. #62
17. #73 
18. #90
19. #91 

---
### Fin del juego
1. #34 
2. #45 
3. #88 

### Puntajes
1. #45 
2. #59 

---
### General
1. #23 
3. #44
5. #32 
7. #52
8. #54
9. #56

---
### Bonus
1. #48 

---
* #### `.gitignore`
   1.
---
### Buenas prácticas
1. #28 
2. #65 
3. #67 
4. #64 
5. #93 

---
### Otros
1. #26 
6. #38 
20. #40 
21. #53
22. #61
23. #68 
24. #76
25. #80 
26. #92

**Comment by felipeschmidt01** [comment]
Hola!

Me gustaría saber si al crear una partida nueva, esta debe tener de nombre de usuario que no se encuentre en las partidas guardadas. Finalmente, mi pregunta se traduce también en: ¿existe la posibilidad de tener más de una partida guardada con el mismo nombre de usuario? En caso de que sí se pueda, ¿queda a criterio mío el cómo diferencio aquellas dos partidas, para eventualmente cargar una específica de esas dos o más?

**Comment by Juampisaez** [comment]
Holaa 👋 @felipeschmidt01 
En primer lugar, para la siguiente ocasión debes realizar una issue (no comentar esta issue).
Sobre tu duda, no esta especificado en el enunciado lo que mencionas, por lo que queda a tu criterio. De igual forma, hace sentido que si guardo una partida con un usuario que ya se guardó, el archivo correspondiente se sobrescriba.

Espero haya quedado mas claro, si tienes otra duda, haz otra issue 🙏
