### ISSUE TITLE
Problema con el Formato UTF de python (tildes)

### ISSUE THREAD

**Issue by rodrigoogalde** [IIC2233/Syllabus#20]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, cuando imprimo las observaciones de los reclamos o las ciudades de entregas, pasa que hay algunos con tildes (como Chillán) y python utiliza formato UTF para el texto, por lo que me muestra algo así "ChillÃ¡n", ¿como puedo hacer para que reconozca los tildes o da lo mismo?
Gracias!

**Comment by benjaaguila** [comment]
Hola @rodrigoogalde ! Tal como dice el enunciado es obligatorio el uso de **encoding='utf-8'**. Puede que al utilizar la función **open()** no estés utilizando el argumento **encoding** y por eso se te imprime así.

**Comment by rodrigoogalde** [comment]
buenisimo!
Gracias!
