### ISSUE TITLE
Caracteres por línea (100)

### ISSUE THREAD

**Issue by JavaBravo** [IIC2233/syllabus#20]
¿Se puede hacer uso de la función Word Wrap Column del editor de texto para evitar superar los 100 caracteres por línea?

**Comment by MatiasDuhalde** [comment]
En primera instancia **no**, por las siguientes razones:

1. La función que nombras es es específica al editor de tu computador. Es decir, si tienes Word Wrap activado y envías el archivo, nosotros los ayudantes (que no tenemos Word Wrap activado) veríamos las líneas gigantes :(

2. Justamente hacemos esta restricción porque tener líneas muy largas es considerado como una mala práctica (no solo por el curso, sino que por la comunidad de Python en general), y usar Word Wrap no soluciona realmente el problema.

Generalmente los problemas de líneas muy largas se pueden solucionar usando variables auxiliares, paréntesis o "backslash". 

Por ejemplo:
```python
enlace_web = "https://github.com/IIC2233/syllabus/issues/20"
resultado = 2 + 4 * 3 + 12 / (5 * 3) - 234

print(enlace_web) # https://github.com/IIC2233/syllabus/issues/20
print(resultado) # -219.2
```

Se pueden separar usando backslash y paréntesis de la siguiente manera


```python
enlace_web = ( "https://github.com/"
               + "IIC2233/syllabus"
               + "/issues/20")
resultado = 2 + 4 * 3 \
            + 12 / (5 * 3) \
            - 234

print(enlace_web) # https://github.com/IIC2233/syllabus/issues/20
print(resultado) # -219.2
```
