### ISSUE TITLE
TIEMPO_MONEDA y DURACION_MONEDA

### ISSUE THREAD

**Issue by catorres8** [IIC2233/syllabus#200]
Hola, en la sección **6. Monedas** no me quedó clara la diferencia entre estos 2 parámetros(`TIEMPO_MONEDA`, `DURACION_MONEDA`). Por lo que leí, entendí que ambas determinan el tiempo que se muestra una moneda pero ¿Es así? ¿podrían explicarme de mejor forma la diferencia y a que está enfocada cada una?.

A continuación coloco el fragmento en el que son definidas:

> Las monedas aparecen ocasionalmente en cualquier parte del mapa, en periodos fijos en segundos, definido por el parámetro TIEMPO_MONEDA. Estas monedas estarán en el campo de batalla durante una cantidad fija de tiempo en segundos, almacenado en DURACION_MONEDA, y luego desaparecerán

EDIT: Dándole otra vuelta, creo que `TIEMPO_MONEDA` se refiere a la frecuencia con la que aparecen las monedas, pero de todas formas agradecería que me explicaran

**Comment by gatochico** [comment]
Hola! 

TIEMPO_MONEDA se refiere a la frecuencia entre apariciones de monedas. Por otro lado DURACION_MONEDA se refiere a una vez aparece la moneda en el mapa, cuantos segundos durará antes de desaparecer nuevamente. 

Exito!
