### ISSUE TITLE
VSCODE Autocompletado no activado para elementos de modulo PyQt6

### ISSUE THREAD

**Issue by MathiasPrett** [IIC2233/Syllabus#200]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### VsCode: Autocompletado

Hola. Logre instalar correctamente PyQt6 y no me ha dado problemas para ejecutar archivos que utilicen esta librería. Sin embargo he notado un problema, que no se si tiene relación con la librería misma, y es que al escribir mi código **no se me permite la opción de autocompletar el resto de la palabra de los métodos y todo relacionado al PyQt6.** En la ayudantía que tuve ayer vi que a mi ayudante le salía un listado enorme de métodos de los widget que vsCode le sugería rellenar. A mi no se me ofrece eso. También uso VsCode.

![image](https://github.com/IIC2233/Syllabus/assets/142269948/b3e5b85b-ba99-46c4-943a-5fd25072b830)

Como se ve en la imagen, no se me permite autocompletar. Pero apenas termino de escribir el método si se me reconoce...

**Como configuro esto??** Son tantos métodos los que integra la librería que encuentro imprescindible tenerlos a mano.
Gracias

**Comment by MathiasPrett** [comment]
**SOLUCIONADO** 💯 

No tengo idea por qué, pero por alguna razón ahora si me entrega un listado de métodos de autollenado. No se que hice

![image](https://github.com/IIC2233/Syllabus/assets/142269948/8358507b-87cd-4430-b6ef-be8dd40f065a)

**Comment by Hernan4444** [comment]
Hola @MathiasPrett 

Que bueno que lo solucionaste. Probablemente lo que ocurría es que VSCode no detectaba tu Python que si tenía pyqt6, ahí lo importante es asegurar que VScode detecte el python correcto. En caso de estar en WSL, asegurar que VSCode se conecte a WSL y ahí detectará el python dentro de WSL.

Saludosヾ(＾-＾)ノ
