### ISSUE TITLE
propagación aerea de la cura

### ISSUE THREAD

**Issue by egbusch** [IIC2233/Syllabus#200]
Hola,

Cuando se descubre la cura en un país (abre sus fronteras y aeropuertos) y este la exporta al resto de los países vía aérea. 
1) Es necesario que los países que recibirán la cura tengan sus aeropuertos abiertos ? 
2) Se puede asumir que el al momento de ir a entregarles la cura abren sus fronteras y aeropuertos ya que también tendrán la cura ?

**Comment by stephichau** [comment]
@egbusch  revisa la issue #155 !

**Comment by egbusch** [comment]
@stephichau hay algo que no me queda claro sobre las respuestas de ese pots. 
En el enunciado sale `También se propondrá abrir los aeropuertos y fronteras si es que se descubre la cura a la infección **en** el país.`, y en el descubrimiento de la cura sale `Si ocurre el descubrimiento de la cura, se elegirá un país inicial al azar para que esta sea repartida. Por día, cada país que tenga la cura entregara a todos los países **que tenga acceso** mediante aire la cura.` 
Entonces tengo las siguientes dudas:
1. El país que descubre la cura, propone abrir sus fronteras y aeropuertos con prioridad 1, ó las abre si o si ?
2. Los países que están conectados vía aire (**potenciales para tener la cura**) abren si o si sus fronteras y aeropuertos para recibir la cura, proponen abrirlas con prioridad 1, ó   deben estar abiertas por condiciones propias del país para que la cura  pueda entrar?

**Comment by stephichau** [comment]
del enunciado:
<img width="500" alt="screen shot 2017-04-02 at 11 53 42 am" src="https://cloud.githubusercontent.com/assets/16126322/24588248/229055f2-179b-11e7-9217-13294f506b85.png">
:)
