### ISSUE TITLE
sobreescritura de gameinterfaz a pesar de funcionar

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#200]
Se dice que se debe sobreescribir los métodos de "GameInterfaz", como por ejemplo "rotar", pero como yo (como usuario que juega) le indico la dirección, o queda a disposición mía el sentido de rotación?

**Comment by Arcoirisky** [comment]
El enunciado explica cómo funciona cada método. Tu ejemplo se explica bien con la Demo. Tómate un tiempo para jugar un poco con la demo y ve viendo cómo funciona todo :D
