### ISSUE TITLE
Duda parametros.py valores no usados

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#200]
Hola los parametros que nunca voy a ocupar como por ejemplo el MIN Y MAX de motor de una bicicleta la cual no tiene motor  los puedo dejar como None o tengo que asignarle un valor igual

**Comment by pwillmer** [comment]
Misma duda

**Comment by gatochico** [comment]
Hola! 
Queda a tu criterio si llenarlos o dejarlos como `None`, siempre y cuando tu programa no presente problemas (no se caiga) debido a tu decisión. No estaría demás, eso si, que incluyas en tu README o en el mismo archivo `parametros.py` en forma de `#comentario` cuales parámetros dejaste de forma intencional como None y tu justificación para que el ayudante sepa que fue una decisión intencional :see_no_evil: 
Éxito con la tarea! :racing_car: :car:
