### ISSUE TITLE
Duda cheatcode balas infinitas y puntaje nivel

### ISSUE THREAD

**Issue by manuel-2112** [IIC2233/Syllabus#200]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Mi duda es que al ocupar el cheatcode de las balas infinitas y luego finalizar el nivel, el puntaje obtenido es afectado por la cantidad de balas restantes, que se hace en esta situacion??

**Comment by nzamorano** [comment]
Hola @manuel-2112, el puntaje del nivel **sí** es afectado por las balas restantes al ocupar el *cheatcode*, de manera de respetar siempre la fórmula para el cálculo del puntaje.

**Comment by manuel-2112** [comment]
En el enunciado sale:

> O + V + N + I: Esta combinación **otorga balas infinitas** exclusivamente por el nivel en el que te encuentras.

De esto yo entiendo que la cantidad de balas pasa a ser infinito. Luego, si ocupo _n_ balas y paso el nivel, mi cantidad de balas restantes sigue siendo infinito, ya que (infinito - _n_ = infinito). Por lo tanto no entiendo como aplicarlo a la formula de puntaje, ya que va a dar infinito, independiente de los otros valores.

Por ejemplo:
```
import math

cantidad_de_balas = math.inf
balas_utilizadas = 20

balas_restantes = cantidad_de_balas - balas_utilizadas

print(balas_restantes) #inf
```

**Comment by nzamorano** [comment]
No es necesario que las balas sean realmente infinitas, basta con sumarles un número muy grande, de esta manera puedes calcular el puntaje sin que se dispare al infinito.
