### ISSUE TITLE
form entrega atrasada

### ISSUE THREAD

**Issue by rieg-ec** [IIC2233/syllabus#200]
hola, me di cuenta que habia un bug en mi tarea que hacia que al registrar un usuario si el archivo .csv no tenia una linea vacia al final,  se creaba en la misma linea del ultimo usuario

tengo que cambiar 2 lineas, pero cómo lo hago? relleno el formulario con el commit donde lo arreglo o lo especifico en el readme?

**Comment by lily416** [comment]
Hola, te recomiendo ver el contenido de este [comentario](https://github.com/IIC2233/syllabus/issues/192#issuecomment-602905978) y el que le [sigue](https://github.com/IIC2233/syllabus/issues/192#issuecomment-602908158).

Quedo atenta en caso de dudas. 😸
