### ISSUE TITLE
no me corren los códigos de ejemplo de los contenidos del curso

### ISSUE THREAD

**Issue by rosario-frugone** [IIC2233/syllabus#200]
hola!!

quería probar los códigos que ponen de ejemplo en los contenidos pegándolos en vs code pero ninguno me funciona, literalmente los copio y pego. Aquí dejo una foto del ejemplo de "Otras maneras de definir properties" que no me corre :(

[
![Captura de pantalla 2020-08-25 a la(s) 22 49 42](https://user-images.githubusercontent.com/69985117/91251090-a586bb80-e728-11ea-8871-221dcd833633.png)
](url)

**Comment by yuwet15** [comment]
Creo que podrías probar borrar todas las identaciones y volver a identar, quizás sea porque hay ideaciones de diferentes tipos

**Comment by aaossa** [comment]
Hola @rosario-frugone , no ocupo VS Code, pero al parecer estás corriendo los archivos de una manera distinta. Podrías probar con lo que dice este comentario en otra *issue*: https://github.com/IIC2233/syllabus/issues/27#issuecomment-674467937 . El código en sí no tiene problemas, de hecho podrías correrlo desde consola, solo que tu editor está intentando correrlo en modo "interactivo" al parecer (no estoy seguro de que ese sea el nombre).

**Comment by rosario-frugone** [comment]
se arreglo con format selection!! gracias! :)
