### ISSUE TITLE
Metodo evolucionar

### ISSUE THREAD

**Issue by cataruze** [IIC2233/Syllabus#200]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holaaa, no entiendo bien el método evolucionar de los combatientes.

**Comment by Benjeeeh** [comment]
Hola! ¿Cuál es tu duda específica?

En general el método evolucionar debe ser el que maneje todos los términos que cambien la clase del combatiente, es decir, debe manejar la validez de un ítem (dependiendo de la clase) y luego modificar todos los parámetros necesarios dependiendo de la evolución respectiva (guerrero a paladín, u otros).

Si tienes una duda más específica sientete libre de responder en esta issue!

**Comment by javibust** [comment]
Hola, me gustaría saber si necesariamente "evolucionar" debe estar definido dentro de las clases o si se puede definir externamente una forma que conlleve al mismo resultado?

**Comment by Benjeeeh** [comment]
@javibust 

Exactamente, solo debe estar definido dentro de la clase, ya que así lo menciona el enunciado.

Saludos!

**Comment by Daniel-M-P** [comment]
Porque se habla de modificar los parámetros si siguen siendo los mismos? Al evolucionar no puedo crear una instancia del gato nueva de la evolución para que tenga los métodos correspondientes y eliminar la instancia actual? 

Por ejemplo si se evoluciona de un guerrero a mago de batalla, eliminar el guerrero y crear un mago de batalla? esto es válido de hacer?

**Comment by sloyols** [comment]
Y siguiendo con esta consulta, esto de crear una nueva instancia de clase y eliminar la anterior es válido si el proceso ocurre dentro del método evolucionar del gato antiguo?

**Comment by coniverav** [comment]
Sobre esto, en el enunciado se menciona que "los peleadores pueden realizar las siguientes acciones: -Atacar -Curarse -Evolucionar -Presentarse". Esto me da a entender de que es una acción que pueden realizar, pero no necesariamente debe ser un método de su instancia, por lo que podría hacer que el método evolucionar sea de los ítems y que estos puedan aplicarse sobre los combatientes evolucionen, no es así?
En caso de que no, agradecería que me dijeran si hay algo en el enunciado que yo no haya notado sobre esto.
<img width="473" alt="image" src="https://github.com/IIC2233/Syllabus/assets/162245893/7372243d-7527-48e4-9382-b42b19f89c95">

**Comment by nicolasoyarcegUC** [comment]
Tengo la misma duda de Daniel-M-P

tambien me estaba preguntando si se permite mutar una instancia de una clase a una de sus subclases, por ejemplo si tengo una clase llamada Naranja y esta tiene una subclase llamada NaranjaJugosa y tengo un objeto "a" que es una instancia de Naranja y quiero mutarlo, osea que "a" se convierta en una instancia de NaranjaJugosa, segun https://stackoverflow.com/questions/2887643/mutate-an-object-into-an-instance-of-one-its-subclasses esto si es posible pero dicen que se considera mala practica, asi que no se si tendra descuento si lo hago

**Comment by Eoweo** [comment]
@Daniel-M-P @Benjeeeh, agradecería responder estas preguntas, dado que poseo las mismas

**Comment by gecoli** [comment]
Estimados estudiantes, 

La duda que les surge es válida de abordar de la manera que quieran, ya sea como un método de la clase, eliminando la anterior instancia o, de hecho, **mutándola**, pero tomen en consideración que se refieren a "evolucionar" en la pauta como un **método**. 

Fuera de esto, no es una mala práctica mutar una clase, tampoco el eliminarla y crear una nueva, sólo deben ser consistentes para que la funcionalidad deseada se refleje. 

Siéntanse libres de preguntar si aún quedan con dudas.

@Daniel-M-P @sloyols @coniverav @nicolasoyarcegUC @Eoweo

**Comment by coniverav** [comment]
No me quedó claro, entonces sí es válido poner el método evolucionar en las clases ítem y no en las clases combatientes? (mencionándolo en el readme claro)

**Comment by gecoli** [comment]
@coniverav ,

Hay que poner el método de evolucionar donde se pide (según el enunciado y la distribución de puntaje)

**Comment by Eoweo** [comment]
Y una consulta al usar un ítem, este podría hacer que guerrero.evolucionar cree la nueva clase y todo, y el ítem se encargue de indicar dos cosas: a que clase debe evolucionar guerrero y eliminar la clase antigua y reemplazarla por la nueva?
