### ISSUE TITLE
Método iter

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#200]
Hola
Hice una implementación del método iter en mi estructura de datos pero no sé si cumple con el requerimiento de no usar un generador (básicamente porque no sé qué es un generador).
No puedo mostrar ni describir lo que hice por acá (por obvias razones), pueden ver el código en mi repo y decirme si es o no legal lo que hice? :(

**Comment by rihanuch** [comment]
Hola @jmwielandt !
No utilizas generadores 👌🏼, pero si acuerdate de citar codigo si lo sacaste de internet!
Recuerda que la idea es que tu aprendas a usar este tipo de estructura de datos 🤓 (asumo que no lo hiciste tu porque sino sabrias que hiciste (?)😬)

Saludos! 🍀

**Comment by jmwielandt** [comment]
O sea, sí lo hice yo (dejé la fuente) y entiendo lo que hace, pero no sé si cuenta como generador o no n_nU
Gracias!!

**Comment by IchottMano** [comment]
@ljrodriguez1 Hola!
Efectivamente no usas generadores 😄 
Admás esta muy bien citado.
Saludos y mucha suerte con tu tarea!
