### ISSUE TITLE
duda sobre setter

### ISSUE THREAD

**Issue by pascal1003** [IIC2233/syllabus#200]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido 
* [ ] (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

En los contenidos aparece que al momento de crear un setter se escribe:
    @personas.setter
    def personas(self, p):
        ....
y al momento de llamarlo:
puente.personas += 5

Mi pregunta es, si p = 5  o p = puente.personas + 5
[Describe tu duda de manera detallada, explicando los contenidos en cuestión y ojalá colocando código o un caso de uso de ejemplo]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by aaossa** [comment]
Hola @pascal1003 ,

Imagino que tu pregunta se responde un poco con esta primera parte: cuando realizas una operación tipo `contador += 1`, esa operación es equivalente a `contador = contador + 1`. En ese caso, es evidente que tu programa hace dos pasos:

```python
# Esta operación
contador += 1

# Es equivalente a...
contador = contador + 1

# Que es una forma corta de escribir...
nuevo_valor = contador + 1
contador = nuevo_valor
```

Ahora, fíjate en la última representación. Primero tengo que buscar el valor actual de `contador` y sumarle uno, y luego defino el nuevo valor de `contador`. Utilizando el vocabulario de las *properties*, esto significa que algo del tipo `self.atributo += 1`, primero llamará al *getter* del atributo y luego a su *setter* con el nuevo valor. Esto lo puedes confirmar agregando un par de `print` al código del ejemplo:

 ```python
class Puente:

    def __init__(self, maximo):
        self.maximo = maximo
        self.__personas = 0

    @property
    def personas(self):
        print("Getter", self.__personas)
        return self.__personas

    @personas.setter
    def personas(self, p):
        print("Setter", p)
        if p > self.maximo:
            self.__personas = self.maximo
        elif p < 0:
            self.__personas = 0
        else:
            self.__personas = p


if __name__ == '__main__':
    puente = Puente(10)
    # puente.personas = puente.personas + 7
    puente.personas += 7

```

Entonces... el *getter* retornará el valor actual del atributo (0) y luego el *setter* recibirá como nuevo valor 0+7=7. Ojalá esta explicación te permita ver más claro lo que ocurre cuando utilizas una línea de ese estilo 👌

**Comment by BenjaRubio** [comment]
Profesor, y si acá en el setter hubiera puesto al final:
else:
    self.__personas += p

¿cuál sería la operación que python realiza?
En la AS1 tenía la duda de cómo escribirlo para que sumara las utilidades correctamente, y me di cuenta que si hacía lo que acabo de escribir acá se hacían mucho mayores pero no comprendo bien porqué-
Gracias!

**Comment by aaossa** [comment]
Hola @BenjaRubio , la operación que describes es equivalente a `self.__personas = self.__personas + p`, por lo que en lugar de estar quedandote con el nuevo valor estás sumándolo al anterior. Recuerda que el *setter* "settea"/define el nuevo valor. No recibe el cambio en el valor, por lo que en este caso usar `+=` dentro del *setter* solo va a hacer que tus resultados crezcan como mencionas. Intenta quedarte con eso, el *setter* recibe el nuevo valor (no el cambio en el valor). Si tienes más dudas preguntas por acá mismo no más 👌
