### ISSUE TITLE
Duda sobre dificultad de arena magnética

### ISSUE THREAD

**Issue by masoto22** [IIC2233/Syllabus#201]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola

Me surgió una duda respecto a la dificultad de la Arena Magnética. Por lo que entendí la Arena Mojada mantiene la fórmula que se da al presentar las características y propiedades de Arena(clase padre). En tanto, Arena Rocosa tiene otra fórmula para dificultad. En este caso, al tener el mismo comportamiento de Arena mojada y Arena rocosa, qué fórmula ocuparía? Me confundí bastante jajaj

Gracias

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Benjeeeh** [comment]
Hola!
Te lo dejo planteado de la siguiente manera: Si magnética es mezcla entre mojada y rocosa, y tomo la dificultad de la arena mojada para definir esta nueva arena, ¿Se ve reflejado el comportamiento de la arena rocosa en la magnética?

Éxito en la tarea!!

**Comment by mayafzt** [comment]
hola yo tengo la misma duda y no entendi la respuesta

**Comment by Benjeeeh** [comment]
Hola @mayafzt 
Puedes revisar la issue #210 que respondo esta misma pregunta pero más detallado. Cualquier cosa me dices si no te quedó claro.
