### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by hagarces** [IIC2233/Syllabus#201]
Estaba haciendo una clase para listas y me sale el error UnboundLocalError ayuda porfavor :(
```python
class nodo:
    def __init__(self):
        pass

class lista:
    def insert(self,posicion,valor):
        contador = 0
        nod = nodo(valor)      < ----- aqui me manda el error
        nodo = self.cabeza
        agregado = False
        if posicion < 0:
            raise ValueError("La posicion debe ser positiva")
        bla
```

**EDIT jtagle2:**  Te edito el código para que se vea mas fácil. Para que se entiendan mejor tus preguntas, intenta utilizar markdown al momento de escribir códigos de python.

**Comment by akaminetzkyp** [comment]
Hola! Por lo que veo, tu clase nodo no recibe ningún atributo, pero tu le estás metiendo "valor". Saludos!

**Comment by hagarces** [comment]
no no la clase nodo esta bien definida, la puse así para no poner todo el código.
class nodo:
    def __init__(self,valor):
        self.valor = valor
        self.siguiente = None
asi está

**Comment by stephichau** [comment]
@hagarces cual es el error completo ?

**Comment by hagarces** [comment]
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    lista.insert(0,3)
  File "C:\Users\Hecto\Desktop\Progra Avanzada!\Tareas\Tarea2\tests.py", line 58, in insert
    nod = nodo(valor)
UnboundLocalError: local variable 'nodo' referenced before assignment

**Comment by stephichau** [comment]
@hagarces 

```python
class nodo:
    def __init__(self):
        pass

class lista:
    def insert(self,posicion,valor):
        contador = 0
        nod = nodo(valor)      < ----- aqui me manda el error
        #nodo = self.cabeza    <------ comenta esta linea
        agregado = False
        if posicion < 0:
            raise ValueError("La posicion debe ser positiva")
        bla
```

**Comment by jtagle2** [comment]
@hagarces Por patologías como estas es que les pedimos que usen buenas prácticas como **camelcase**, snakecase, pep8, etc... En este caso, utiliza camelcase (o bien, cámbiale el nombre a la variable que está en la línea que está después del error). El error se origina básicamente porque al llamar a una variable nodo (mismo nombre que tu clase), al momento de compilar, el compilador ve que en el scope del método insert, hay una variable llamada nodo, por lo que la define como una variable local para ese scope, y se pierden las referencias a todas las variables que están afuera del scope que tienen el mismo nombre (es decir, la clase nodo deja de existir para el metodo insert).
Saludos!

**PD:** Para que vean que cuando los ayudantes los molestan para que se acostumbren a pep8, camelcase, snakecase y todas esas cosas, es por su propio bien :).
