### ISSUE TITLE
Validez archivos

### ISSUE THREAD

**Issue by M4TI4D4CZ** [IIC2233/Syllabus#201]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Una pregunta sobre la validez del formato para la creacion de un combatiente. Para que el formato se cumpla, ¿hay alguna restriccion para los nombres de los gatos? Por ejemplo, que solo pueda ser alphanumerico, o tambien ¿puede un gato llamarse "GUE", y por lo tanto ser valido? 

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Benjeeeh** [comment]
Hola!
El enunciado no menciona ninguna restricción respecto al nombre del combatiente, **solo que debe ser un string**, por lo que puede llamarse de cualquier forma y pueden haber casos que se llame 'GUE' y luego en clase sea 'GUE' nuevamente. Lo importante es verificar la validez del archivo, es decir, que siga el formato que se menciona en el enunciado.

Saludos!
