### ISSUE TITLE
obtención posiciones jugada

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#201]
Como se obtienen las posiciones indicadas por el jugador? A esto me refiero con que si tengo que hacer la tarea en modelos diferentes (obviamente por un tema de orden) como es que se debe hacer para conectar mi clase "Jugador" (por ej) a la interfaz gráfica?

**Comment by iqacevedo** [comment]
Las posiciones que indica el jugador las obtienes cuando clickea en la interfaz gráfica, lo que llama al método colocar_pieza y le entrega las posiciones en que se clickeo.

**Comment by rihanuch** [comment]
entonces como se puede poner de forma inicial la pieza aleatoria? (probe y si uno trata de darle coordenadas como 1,1 la interfaz se ve así
<img width="960" alt="captura de pantalla 2017-09-01 a la s 13 29 48" src="https://user-images.githubusercontent.com/26392931/29978914-a59c938e-8f19-11e7-9a93-b97d9feebfc6.png">

**Comment by iqacevedo** [comment]
El método addPiece(i, j) de la gui, coloca la pieza que se encuentra en el espacio de las piezas por lo tanto siempre tienes que previamente llamar al método nueva_pieza antes de usarlo, si lo haces no deberías tener problemas. En caso que tu error persista vuelve a comentar para revisar si es algún error que quedo sin que lo detectáramos en la gui. 

Saludos !

**Comment by mfanselmo1** [comment]
Hola, yo sigo teniendo problemas con esto. Si trato de usar el metodo `gui.add_piece(i,j)` desde el init me pasa lo mismo que puso Rodrigo en la foto, independiente de donde ponga `gui.nueva_pieza()`.  Podria ponerlo en el metodo de MyInterface `colocar_pieza`, pero ahi para que se ponga la primera pieza al azar el usuario tendria que hacer click primero

**Comment by rjgalvez** [comment]
Hola, yo tambien tengo el mismo problema con la interfaz
No es un error del programa?

**Comment by ptflores1** [comment]
Me pasa lo mismo !

**Comment by iqacevedo** [comment]
Hola, 

Efectivamente no se podía agregar una pieza al iniciar el tablero, esto se debía a que MyInterface era instanciada antes de que la interfaz en sí fuera instanciada, por lo que para solucionarlo simplemente se cambio la linea en que se instancia MyInterfaz. Ya se encuentra la gui corregida y se anuncio en #233.

Saludos !
