### ISSUE TITLE
Sobre cómo modificar un atributo con properties

### ISSUE THREAD

**Issue by fernandolalanne** [IIC2233/syllabus#201]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Quería preguntar si me pueden explicar cómo modificar un atributo constantemente a través de properties. Por ejemplo en la AS1 trabajaban con el atributo "utilidades" y éste se definida por medio de una property entonces mi pregunta es si defino a self.utilidades = 0 y luego escribo la property como:

@ property
def utilidades(self):
    return self.utilidades

@utilidades.setter
def utilidades(self, valor):
    ........

Y luego por cualquier motivo debo modificar las utilidades cómo lo hago? por ejemplo podría escribir self.utilidades += 7 si quisiera modificarla en 7? Y de ser así cómo se asocia lo anterior con el setter de utilidades, en ese caso el valor corresponde a self.utilidades + 7?

Gracias!

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by aaossa** [comment]
Hola @fernandolalanne , creo que respondí algo parecido que podría servirte en #200 , por si quieres darle una mirada. Lo que debes recordar es que las *properties* quedan definidas cuando se define la clase (ojo, la clase, no la instancia). Ahora, cuando creas una instancia, Python ya sabe que `self.utilidades` es una *property* y que si intentas usar `self.utilidades` debe ejecutar el *getter* o el *setter* que hayas definido.

Ahora, tu código de la pregunta es medio confuso, porque cuando intentes acceder al valor de `self.utilidades` (cuando uses el *getter*) vas a caer en una recursión infinita: lo que estás retornando es una nueva llamada al *getter*. Imagino que tu pregunta se debe a que en el `__init__` de tu clase se utilizó `self.utilidades`, lo que significa que estás utilizando la *property* ya definida (recuerda lo que mencioné en el primer párrafo). 

No estoy seguro de si respondí 100% tu pregunta 😅 Si no era lo que preguntabas o algo no te queda claro pregunta por acá mismo no más 👌

**Comment by fernandolalanne** [comment]
Perfecto ahi me quedó más claro leyendo la issue 200 sin embargo, me quedó una última duda. Haciendo referencia a la AS1, en ésta las utilidades estaban encapsuladas de la forma self.__utilidades = 0 entonces debido a lo anterior es que se debía definir la property para poder trabajarla y de ahí el código que escribí más arriba. En base a lo anterior mi pregunta es cómo modifico mis utilidades, por ejemplo si quiero sumar 1 a mis utilidades ¿es correcto escribir objeto.utilidades() += 1?, que era lo que justo pedían en la actividad, y cómo se relaciona eso con el método setter al recibir un valor del estilo:

@utilidades.setter
def utilidades(self, valor)

.....

Basicamente me confundo en qué significa ese "valor" para Python una vez que se modificaron las utilidades.

Desde ya muchas gracias profesor!

**Comment by aaossa** [comment]
Cuando haces `instancia.atributo = nuevo_valor`, ese mismo valor es el que recibe el *setter* de la *property*. Por otra parte, cuando tienes una *property*, la ocupas como si fuera un atributo cualquiera, te olvidas que lo implementaste como un método, entonces tu `objeto.utilidades() += 1` no es correcto. Si quieres sumar 1 a tus utilidades, solo ocupas `objeto.utilidades += 1`.

**Comment by fernandolalanne** [comment]
Gracias profesor! Todo claro.
