### ISSUE TITLE
#2 Tarea

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#201]
Hola, disculpa la molestia, pero me llego un email donde en la tarea me dice #2, ¿Qué significan?

**Comment by entamburini** [comment]
Hola @CataSudo 

Ese #2 indica que es la segunda issue que se creo en tu repositorio. Para cada entrega, tanto de tarea como de actividad, se crea una issue indicando lo que se va a revisar.

Saludos! :v:
