### ISSUE TITLE
input de tipo de bomba a usar

### ISSUE THREAD

**Issue by keac1** [IIC2233/syllabus#201]
Hola, tiene que ser un solo input o pueden ser varios? y son por numero (Así por ejemplo imprimo un mini-menu y le asigno a la bomba cruz el numero 1) o el input va a ser un string "bomba cruz".

**Comment by jitorcas** [comment]
Hola! @keac1 

La manera en que lo hagas queda a tu criterio, siempre y cuando las bombas estén en el menú correspondiente. Es una muy buena opción crear un menú para las bombas y recibir el input mediante un número. 

Recuerda que todos los menú deben ser a prueba de errores. 

Éxito en la tarea! ⚓️
