### ISSUE TITLE
Jugadores con datos incompletos

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#201]
Hola! No pude evitar notar que en la base de datos hay jugadores que no tienen liga ni club. Esto podría presentar un problema en la tarea?

Ejemplo:
176733,M. Berg,Marcus Berg,,,Sweden,80
169195,Renato Augusto,Renato Augusto,,,Brazil,80
170733,Gervinho,Gervais Yao Kouassi,,,Ivory Coast,79
Y así para varios casos más.

**Comment by cilopez** [comment]
No hay problemas con este tipo de jugadores, son jugadores no contratados.

**Comment by mblejeune** [comment]
Tengo una duda con respecto a esto, en este caso, los jugadores no tienen ni liga ni club, pero tienen nacionalidad y esta puede coincidir con la de otros jugadores por lo que pasarían a ser "conocidos" y por tanto formarían parte del grafo, debo considerarlos en el grafo o simplemente obviarlos ? (al realizar las conexiones de afinidad -> 4.1)
