### ISSUE TITLE
Cargar Partida

### ISSUE THREAD

**Issue by sgonzler** [IIC2233/syllabus#201]
Una duda, en la ayudantía se dijo que debemos de poder cargar a los pilotos y vehículos aun si es que mueven el orden de los atributos, ¿es verdad?

**Comment by lucastack** [comment]
si lo dijeron, yo estaba presente

**Comment by gatochico** [comment]
Hola! 
Toda la información que se entregue en la sala de ayuda cuenta como **oficial** para la tarea. En este caso, probaremos tu tarea con archivos con las columnas cambiadas, por lo que debes preocuparte de ese caso.
Saludos y éxito! :car:
