### ISSUE TITLE
Archivos y repositiorios adicionales en ReadME

### ISSUE THREAD

**Issue by Bjnazar** [IIC2233/Syllabus#201]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! A qué se refieren en el readme (en ejecución) con la lista de archivos y directorios adicionales que se deben crear? Si yo ya subo los archivos adicionales creados (por ejemplo parametros.py) tengo que ponerlos en esta parte del README?
gracias!

**Comment by MrNachoX** [comment]
Hola @Bjnazar!
Si tu programa necesita que se cree alguna carpeta o archivo antes de ser ejecutado, lo puedes indicar en el README. Por ejemplo, para la T0 podías indicar si era necesario crear la carpeta "partidas" antes de ejecutar el juego. Si ya subiste todo a tu repositorio entonces no es necesario. Lo que sí es necesario es señalar cual es el archivo principal de la tarea que se debe ejecutar.
