### ISSUE TITLE
Posible error en mapa_2.txt

### ISSUE THREAD

**Issue by catorres8** [IIC2233/syllabus#201]
Revisando los archivos de la tarea, noté que en el archivo **mapa_2.txt** el espacio de inicio (S) ubicado en la fila 6 col 1 no tiene ningún camino adyacente, siendo que en el enunciado se menciona que los espacios de inicio siempre tendrán al menos un espacio contiguo de tipo camino (C). ¿Hay que modificar el archivo?? o los enemigos deben ser capaces de moverse al espacio de inicio adyacente??

**Comment by hbkim94** [comment]
Hola! 

En efecto se trató de un pequeño error de escritura. Tal y como dices, los espacios **S** siempre tendrán al menos un espacio de tipo **C** aledaña.

La versión arreglada se encuentra ya disponible en el repositorio de la tarea, para que le hagan pull o lo arreglen uds mismos. Muchas gracias por el aviso! :tada:

**Comment by tomascortes** [comment]
Y es valido que un enemigo se mueva de el punto 'S' al 'S' adyacente? , o está obligado a salir al camino?

**Comment by Hernan4444** [comment]
Hola,

Eso queda a tu criterio, puede ser válido como no, solo no olvides mencionarlo en el readme como un supuesto c:.

Saludos :v:
