### ISSUE TITLE
clase paladín

### ISSUE THREAD

**Issue by cataruze** [IIC2233/Syllabus#202]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Holaa, tengo dudas con respecto a la clase paladín, este es una mezcla entre guerrero y caballero, pero no entiendo cuando activa el uso de guerrero y cuando el de caballero, y también me surge la duda de que cuando actúa caballero me dan otra probabilidad de que active sus poderes, distinta a la que tiene la clase caballero de por si, lo cual lo encuentro extraño, a que se refiere esa probabilidad (PROB_PAL)?. También si este actúa como un caballero o guerrero, además de usar su tipo de ataque también tiene los otros efectos, como en guerrero que después de atacar disminuye su agilidad?

Muchas gracias de antemano

**Comment by tebi01** [comment]
Hola! @cataruze 

Te recomiendo que revises la issue #195, que tiene una duda muy parecida a la que tienes.

Respecto a lo último, podría decirte que lo dejes a tu interpretación. Idealmente que esta interpretación quede muy bien explicada en tu archivo ```README.md```, en la sección de supuestos y en la definición de los métodos de cada ```Combatiente```.

Espero haberte ayudado!

**Comment by Drpinto1** [comment]
¡Hola @cataruze!

Respondí la issue #195, pero repito mi comentario acá para facilitar la lectura/búsqueda de issues para quienes tengan la misma duda.

Complementando las respuestas de @tebi01 y en caso que la duda sea un poco más conceptual que de código, PROB_PAL será un valor entre 0 y 100, que indica que porcentaje de las veces el paladín atacará como un Caballero.

Por ejemplo, si tienes el parámetro PROB_PAL = 20, cada vez que el paladín atatque, tendrá un 20% de probabilidad de atacar como Caballero y un 80% de probabilidad de atacar como Guerrero

Cuéntame si queda más claro :)

**Comment by pedrorobles7** [comment]
holaa, tengo una duda respecto a este tema y a la respuesta, cuando dices que tiene PROB_PAL = 20, por lo que tendrá un 20% de probabilidad de atacar como caballero, esto quiere decir que debe entrar luego a PROB_CAB y ver si ataca como caballero o guerrero, y luego el otro 80% es como guerrero, o bien solo quiere decir que este 20% de probabilidad hace que ataque directamente con la fórmula de ataque del caballero? muchas gracias :))

**Comment by tebi01** [comment]
Hola! @pedrorobles7
Lo ideal sería que directamente llames al método de su clase padre , ```Caballero``` o ```Guerrero```, si es que se cumple la condición de PROB_PAL.

Ahora, respecto a si se vuelve a calcular la probabilidad ```PROB_CAB```, eso dependerá de cómo definiste el método de ataque de esa clase (si el código que pide esa probabilidad estaba dentro o fuera del método que hace el daño especial).

Considero que el Enunciado es poco claro en ese aspecto y te recomiendo que lo interpretes a tu manera (Elige uno de los casos que mencionaste), especificando ese supuesto para ese caso en tu archivo ```README.md``` en su sección correspondiente.

Ojalá eso te haya dejado más tranquilo!
