### ISSUE TITLE
Dudas sobre "Salir" en  juego.

### ISSUE THREAD

**Issue by nicolasgarciaes** [IIC2233/Syllabus#202]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola buenas, tengo una duda con respecto al botón salir durante del juego, lo que debería suceder luego de apretar el botón es que, se guarde su puntaje actual, es decir el puntaje acumulado hasta el nivel anterior, se escriba en puntaje.txt y luego se deberá abrir la ventana de inicio?

**Comment by svilaza** [comment]
Hola @nicolasgarciaes! Al apretar el botón salir durante el juego se debe guardar en el archivo de puntaje.txt solo el puntaje alcanzado en los niveles anteriores, sin considerar el puntaje que se "obtenga" en el nivel actual, y efectivamente luego de apretar el botón se debe volver a la ventana de inicio.
