### ISSUE TITLE
Llamar a variable definida dentro de un metodo.

### ISSUE THREAD

**Issue by SamWeinstein** [IIC2233/syllabus#202]
Hola! Como estoy manejando los menus mediante clases, hay algunas variables que defino dentro de métodos que luego necesito usar dentro de otras clases, pero como fue definida dentro de un método, no puedo acceder a esta variable fuera de esa clase. Existe alguna forma de "globalizar" variables definidas dentro de metodos/clases para poder ser llamadas dentro de otras clases? Pues como estoy trabajando los menus como clases, todo lo que defina quedará limitado a alguna clase :( 
¡GRACIAS!
#EDIT: Se que existe una forma para hacer lo que digo (usando 'global'), pero no se permite en la tarea... Cual sería una forma alternativa de esto o que estoy haciendo mal en el manejo de menus para tener este problema?

**Comment by lucastack** [comment]
algo como esto? 
[https://stackoverflow.com/questions/41409352/pycharm-warns-local-variable-might-be-referenced](url)

**Comment by SamWeinstein** [comment]
No me refiero a eso @lucastack jeje pero gracias por el intento!

**Comment by KnowYourselves** [comment]
Hola @SamWeinstein!

Tu última reflexión es lo correcto. Cuando uno hace programación orientada a objetos y se ve en la necesidad de tener variables globales es porque está modelando mal el problema.

Piensa lo siguiente, tus menús como clases no tienen que hacer nada más que pedir input al usuario y manejar el flujo del juego, no es mucha la interacción que tienen que hacer con el resto de tus clases aparte de utilizarlas como cajitas negras.

Lo que te tienes que asegurar es que al momento de instanciar tus clases tengas toda la información necesaria de forma tal de que no tengas la necesidad de agregarle más cosas a futuro.

Espero haberte ayudado!
