### ISSUE TITLE
Archivos CSV

### ISSUE THREAD

**Issue by fdominguezclaro** [IIC2233/Syllabus#202]
Tengo 2 dudas con respecto a la tarea:

1. En el issue #162 no me quedo muy claro. Al leer un archivo.csv, puedo implementar lo siguiente?

```
with open('population.csv', 'r') as f:
    reader = csv.reader(f)
    paises = edd.ListaLigada() #Mi lista ligada
    for row in reader:
        paises.append(row)
```

2. En esta tarea igual debemos considerar que las columnas pueden venir en desorden?

Muchas gracias,

**Comment by stephichau** [comment]
@fdominguezclaro 

1. No. Le tienes que pasar a tu ListaLigada el valor de reader
2. Si, pueden venir desordenadas

saludos! :)

**Comment by acrojas2** [comment]
@stephichau a que te refieres con que pueden venir desordenadas ? onda primero puede venir el dato de la poblacion y despues el pais?  en el generador de conexiones aereas se podría estar el pais de llegada y despues el pais de origen?

**Comment by stephichau** [comment]
@acrojas2  exacto!
