### ISSUE TITLE
Sprites

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#202]
Mirando los distintos sprites que hay siento que hay varios que no son necesarios de ocupar, ya que sirve como para decorar los mapas, puede ser así? o es necesario ocuparos todos?

**Comment by gatochico** [comment]
Hola! No es obligación utilizar todos los sprites, siempre y cuando se pueda distinguir de alguna forma elementos claves en la interfaz (un enemigo normal de un enemigo kamikaze, por ejemplo). Recuerda, si es que usas los sprites de la carpeta, no cambiar los nombres de los archivos y todo estará ok!
