### ISSUE TITLE
obtención información de las piezas

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#202]
como es que se puede obtener la información de las piezas que se juegan, porque se colocan y se realizan los métodos, pero no retornan nada, por lo que es imposible obtener su información sin la modificación del código por detrás? Por ejemplo si quiero verificar que una pieza se puede colocar de verdad en un lugar como puedo obtener la información de la que está al lado, no tengo como sabe el código que existe detrás de add_piece(i,j) y como usarlo para poder obtener ?

**Comment by Arcoirisky** [comment]
Puedes sobrescribir desde tu código el archivo que te damos para que puedas obtener esa información. No puedo ser más clara ya que eso es algo que debes pensar tú, usa tu creatividad sin ir en contra del enunciado :) Suerte

**Comment by nachocontreras** [comment]
Al decir "el archivo que te damos", se refiere a los archivos de la carpeta gui? 🤔

**Comment by Arcoirisky** [comment]
Eso mismo 😅

**Comment by rihanuch** [comment]
no querrías darnos el nombre del archivo? 😅 digo yo para ahorrar un poquito de tiempo buscando entre tantas funciones que se llaman entre ellas 😬

**Comment by Arcoirisky** [comment]
Me corrijo porque no me expliqué nada bien xD
No es que debas modificar los archivos de la carpeta gui (Además de que no puedes subir la gui así que todo cambio que hagas en ella no se verá) sino que para usar las funciones debes seguir el caso de ejemplo que se muestra en demo.py O: 
Perdón por no haber sido clara 😰

**Comment by rihanuch** [comment]
@Arcoirisky quede en las mismas jajajaja, si entendí que podríamos sobre escribir los métodos de las clases GUI, pero tampoco le veía mucha lógica. El tema es que no se puede trabajar sin la información de la pieza que se esta poniendo...
la otra alternativa es que expliquen como funciona el código que genera las piezas 😲

**Comment by Hernan4444** [comment]
@rihanuch te sugiero darle una vuelta más al enunciado porque si existe forma de saber el tipo de pieza y eso está explicado en el enunciado (Acabo de revisarlo para confirmar).

Saludos!

**Comment by rihanuch** [comment]
@Hernan4444 , te refieres a que sabemos cuales tipos de piezas hay por o tanto podemos usar eso para crear las piezas y así saber cual va a aparecer?

**Comment by Hernan4444** [comment]
@rihanuch precisamente 👍

**Comment by rihanuch** [comment]
en ese caso podríamos hacer un random.choice de la lista ya implementada en el GUI? 🙄

**Comment by Hernan4444** [comment]
@rihanuch a que te refieres con:
> la lista ya implementada en el GUI??

Quieres usar un atributo de la GUI? De ser así, **no puedes**. En el enunciado se especifica que deben hacer para obtener dicha información y no es accediendo a los atributos de la interfaz.

Saludos

**Comment by rihanuch** [comment]
gracias! (😭)
