### ISSUE TITLE
Duda carpeta diagrama de clases

### ISSUE THREAD

**Issue by franco-anfossi** [IIC2233/Syllabus#202]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!! En la parte del enunciado sobre el diagrama de clases, al final habla sobre que el diagrama y la explicación de su modelación deben **ubicarse en la misma carpeta de entrega de la tarea**. Esto se refiere a que estas dos cosas deben ir juntas en una carpeta dentro de la carpeta de entrega o que deben ir sueltos en la carpeta de entrega.

**Comment by MrNachoX** [comment]
Hola @franco-anfossi ,
Lo importante es que los dos archivos esten dentro de la carpeta T1 de tu repositorio. Si quieres puedes dejar los dos juntos dentro de una carpeta, pero no es necesario.
