### ISSUE TITLE
Commit a revisar 

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#202]
me a llegado un mail, diciendo:

Commit a revisar, junto con un link y  un codigo.

Al entrar a dicho codigo me manda a mi repositorio, "mostrandome" los espacios donde estaban codigos antiguos que tome la decision de borrar hace unos dias.

queria saber que significa este mail y si tiene alguna importancia mayor en el ramo, o si solo es una notificacion de pagina.

**Comment by entamburini** [comment]
Hola @felipehen! 

La idea detrás de esto es que revisen si es que las cosas que vamos a revisar corresponden a lo último que ustedes subieron dentro del plazo. También es para que sepan qué cosas veremos en su repositorio y en casos extremos, si es que ese último `git push` hecho en la hora límite entró o no. 

Es importante revisarlo para saber que todo está bien. Sólo es eso :v:

**Comment by felipehen** [comment]
y que pasa si este no es el archivo que quiero que revisen???

Porque mi ultimo git push fue uno que use para borrar 2 archivos copia que tenia en mi carpeta. haciendo que cuando entre al archivo que ustedes vean sea un archivo "borrado"

**Comment by entamburini** [comment]
En la issue damos un link para que revises los archivos que veremos. Si hay algo que no te agrada y prefieres que revisemos una versión anterior, puedes rellenar el form de entrega atrasada y especificar el commit a revisar. Si es un commit anterior a la hora de entrega **no hay descuento** así que puedes especificarlo sin problema :)

**Comment by Daniel-SebastianGaete** [comment]
¿Qué pasa en caso de que quiero que revisen una versión más nueva a la que le di commit pero no corresponde al archivo que aparece en el commit?
Pasa que en mi repositorio está el archivo actualizado, pero por alguna razón no aparece en el historial del commit. ¿Se debe a que lo subí con el mismo mensaje? ¿Qué hago en ese caso?

**Comment by Daniel-SebastianGaete** [comment]
Entonces, ¿Las líneas marcadas en verde serán las que SI se revisen mientras las que en rojo NO?

**Comment by entamburini** [comment]
@Daniel-SebastianGaete, 

Creo que estás confundiendo las cosas 😅. Las líneas marcadas en verde son los cambios nuevos (lineas agregadas) hechas a un archivo en dicho commit. Las líneas rojas son líneas que tu eliminaste (o cambiaste) en el mismo commit. Nosotros no revisamos los cambios.

Lo que nosotros revisaremos son los archivos que estén en dicho commit, si te fijas en la issue autogenerada hay un **link** (con este mismo nombre) donde puedes ver el estado del repositorio en dicho commit. Ahí verás el estado de tus archivos en el commit que veremos.

Saludos! :v:
