### ISSUE TITLE
Estructura de Datos

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#202]
No me queda claro si para toda la tarea no tengo permitido usar listas, diccionarios, etc o si es que solo para cuando instancie la Gui como dice en la tarea. es decir, puedo usar listas para calcular la afinidad entre los jugadores?

**Comment by yoavnavon** [comment]
Hola! No puedes utilizar ninguna lista ni diccionario para toda la tarea.
