### ISSUE TITLE
formato archivo puntaje.txt

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2233/syllabus#202]
Hola!
Tengo duda sobre que formato tendrá el archivo puntaje.txt, ya que entiendo que por ejemplo este podría tener o no salto del lineal al final ( como se menciono en un issue anterior) , sin embargo mi duda es que mas podría cambiar. Tipo ¿ podría ser que me entreguen todos los puntajes que se llevan hasta ahora en una sola linea separados por un espacio ?  o podria pasar que la separación entre dos puntajes sean dos saltos de linea en vez de uno? . Quiero saber que tanto podria cambiar el formato del archivo para ver en que casos tengo que ponerme

**Comment by DCCollao** [comment]
Hola @antoniaalcayaga!

Si tu programa funciona con el archivo `puntajes.txt` que les entregamos, y funciona también con el mismo archivo luego de que tu programa guarda nuevos puntajes en él; significa que está perfecto. No debes preocuparte de que cambie el formato de las formas que mencionas.
