### ISSUE TITLE
eliminar_cultivo modifica self.plano?

### ISSUE THREAD

**Issue by Isipirisi23** [IIC2233/Syllabus#202]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!
En eliminar_cultivo se especifica que retorna la cantidad de celdas eliminadas, pero no menciona nada sobre si debemos guardar en self.plano las modificaciones realizadas al eliminar los cultivos

**Comment by FernandoTFH** [comment]
Si la idea del método eliminar_cultivo, es hacer el cambio en el plano, se podría decir que esa es su función principal y la de retorna la cantidad de celdas eliminadas es su tarea secundaria.

**Comment by Isipirisi23** [comment]
Me queda claro, gracias!
