### ISSUE TITLE
Duda con robustez y datos proporcionados por archivos

### ISSUE THREAD

**Issue by BenzoylMorexide** [IIC2233/Syllabus#202]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Mi duda viene básicamente de qué tipo de archivos serán con los que se hagan pruebas y si estos vendrán con "typos". Como por ejemplo que en el csv, en lugar de un int indicando la suerte, haya un str cualquiera. En algunas partes de mi código, por ejemplo, convierto todos los strings de números indicados a ints para poder instanciar un excavador, y temo que mi código pierda robustez y se caiga el programa si es que no manejo con properties todas las posibles excepciones a cada posible archivo que se le dé al programa.

En resumen la pregunta es ¿qué tan robusto o qué tan atento debiese estar a archivos con valores extraños para instanciar los objetos?, y no solamente para instanciar, sino que en general. ¿O debiese enfocarme en manejar excepciones para inputs erróneos en los menús?

Gracias!

**Comment by tremendapithon** [comment]
Hola, creo que aquí tenemos algo importante: "manejando potenciales errores de formato" y me pregunto si los archivos csv que van a ejecutar con nuestro programa va venir con str en vez de int???

**Comment by panchouc** [comment]
Hola, respecto a el formato de archivos y los valores que potencialmente pueden estar ahí, en la sección **5.Archivos**, se menciona el nombre de una cierta columna y al lado el tipo de dato. En el caso de suerte, en el tipo de dato asociado corresponde a un **int**, por lo que puedes asumir que ese tipo de dato siempre será un **int** y no uno distinto.

**Comment by vicenterodas** [comment]
No me quedo clara la respuesta. Los archivos con los que harán las pruebas serán iguales a los que tenemos actualmente ? 
Al decir iguales, me refiero al tipo de dato (si podrían eventualmente agregar excavadores o ítems).
