### ISSUE TITLE
Problema con Pyqt6 en Mac

### ISSUE THREAD

**Issue by Laefivy** [IIC2233/Syllabus#203]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

Hola, estoy corriendo el codigo 1-interfaces-graficas-ejemplo_1.py de la semana 4 y me aparece el siguiente error y no sé como solucionarlo.
<img width="694" alt="Captura de pantalla 2023-09-07 a la(s) 15 33 43" src="https://github.com/IIC2233/Syllabus/assets/141865857/4ee70207-5f92-405e-99ff-1471c22c0ed2">

**Comment by Laefivy** [comment]
Ojalá me puedan ayudar pronto, porque no he podido realizar ningún ejercicio de la semana 4 ni practicar la materia.

**Comment by mskdancers** [comment]
Hola!
Buscando un poco me encontré con el siguiente código que podría servirte. Anda a tu terminal, y ejecuta el siguiente comando:
```
python3 -m pip install opencv-python-headless
```
Si es que eso no funciona, podrías tratar desintalando pyqt6 y luego volviéndolo a instalar. Ejecuta el siguiente código en tu terminal:
```
python3 -m pip uninstall pyqt6
```
Y luego vuelve a instalarlo, con el mismo comando pero con ```install``` en vez de ```uninstall```.
Avísanos como te va con eso, saludos!

**Comment by Hernan4444** [comment]
Hola,

Complementando está respuesta, si intentas instalar pyqt5 (python3 -m pip install pyqt5) y luego ejecutar los archivos que están en scripts/pyqt5, te sale un error?

Esto es para saber si hay algún problema en pyqy6 en particular o es python con cualquiera de las 2 librerías de pyqt6.

Avísanos qué te sale con esta opción y la indicada por @mskdancers 

Saludos!


PD: recuerda que en este curso, hay que ejecutar los archivos desde la terminal haciendo python3 archivo.py. Por la foto que mandas, parecería que no estás haciendo eso, sino solicitando a VSCode que ejecute los archivos, y esa forma no es la que vemos en este curso porque fácilmente puede provocar problemas 🥺😔

**Comment by Laefivy** [comment]
<img width="562" alt="Captura de pantalla 2023-09-09 a la(s) 20 08 10" src="https://github.com/IIC2233/Syllabus/assets/141865857/33e7043a-93a0-42e7-8a6c-24e4fc3a81b6">
Lamentablemente probé ambas cosas y sigue sin funcionar :( y corriendolo desde la terminal sucede lo mismo

**Comment by gatochico** [comment]
Hola @Laefivy , por lo que veo en tu pantallazo estás en la carpeta `scripts`. Estos `scripts` usan pyqt6. Por favor prueba entrando a la carpeta `pyqt5` dentro de la carpeta `scripts` (`cd contenidos/semana-04/scripts/pyqt5`) y ejecutar los códigos dentro de la carpeta, los cuales hacen los imports de pyqt5. Si sale algún error, por favor manda el pantallazo nuevo de lo que te salga.

Saludos
