### ISSUE TITLE
Duda sobre spawn

### ISSUE THREAD

**Issue by MGome** [IIC2233/syllabus#203]
Los personajes tienen restringido el movimiento sobre los spawnings? Es decir, actúan como obstáculos?

**Comment by hbkim94** [comment]
Hola!

Queda a tu criterio como manejar dicha situación. En general, puedes realizar supuestos cuando algo no sale 100% especificado en el enunciado (al menos que sea algo que de verdad signifique un impacto grande en tu tarea; en ese caso sí recomendaría que preguntaras por una issue), y ponerlo en tu `Readme.md` para que podamos entender como funciona tu programa bajo estos.

Suerte con la tarea!
