### ISSUE TITLE
Jupyter en MacOS Catalina: “zsh: command not found: jupyter”

### ISSUE THREAD

**Issue by CamilaVaras** [IIC2233/syllabus#203]
Hola, tengo unos problemas para instalar Jupyter, tengo sistema macOS Catalina 10.15.3. Hace un tiempo yo había instalado Jupyter a través de Anaconda, sin embargo, ya no puedo entrar por la terminal como antes porque actualice algo en la terminal relacionado con zsh . Me sale el siguiente error: 

zsh: command not found: jupyter

Por lo mismo intente instalarlo como muestran en el video tutorial pero no me funciono.

¿Cómo la puedo instalar?

**Comment by igbasly** [comment]
Hola @CamilaVaras 😄
Según lo que me mencionas, actualizaste bash de tu sistema a zsh como terminal. Por favor coméntame si tienes Python 3.7 instalado y funciona bien desde la terminal. Puedes probarlo con el comando `python` o `python3.7` y debería mostrarte la consola de Python indicando la versión a utilizar (para salir ingresa `exit()`).

Si lo anterior funciona y tienes Python instalado, entonces puedes intentar instalar Jupyter mediante el comando:

`brew install jupyter`

Y cuando esto finalice intentar ingresar mediante el comando `jupyter notebook` o `jupyter-notebook` como en el bash.

Inténtalo y coméntame cómo te va 👍

**Comment by CamilaVaras** [comment]
Si tenía python 3.7 instalado así que intente el comando brew y me funcionó 😄 ¡Muchas gracias!
