### ISSUE TITLE
Duda ejer prop 1.1 s-04 (Levantando errores simples)

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#203]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, tengo la duda de si en este ejercicio solo debemos agregar un mensaje personalizado para cada tipo de error, o si además tenemos que crear un código que contenga el tipo de error específico (que fue lo primero que interpreté). Luego de tratar esto último, que fue lo primero que se me ocurrió cuando leí en el enunciado "levanta un tipo de excepción distinta en cada una", me salieron outputs que me confundieron harto como los siguientes:

(En este código si bien me informó del error, yo esperaba que me avisara con el mensaje personalizado y no lo hizo)
![image](https://user-images.githubusercontent.com/80859173/114270323-b9daa880-99d9-11eb-8205-63ea03edafeb.png)

(En este código no sé por qué en la descripción del error se destaca en amarillo parte del mensaje personalizado que definí para el error, tampoco sé por qué destaca en amarillo tanto los paréntesis del print dentro de la función como el ":", y además la flecha verde esperaba que indicara el código de abajo, donde está el NameError)
![image](https://user-images.githubusercontent.com/80859173/114270341-d37bf000-99d9-11eb-85f0-e86d87953f95.png)
 
(Este código lo ejecuté sin poner nada para probar, y me confunde que me avise que hay un error de todas formas, pensé que la función "raise" solo agregaba un mensaje personalizado a los avisos de errores específicos)
![image](https://user-images.githubusercontent.com/80859173/114270464-89473e80-99da-11eb-9181-3c3391dae065.png)

(En este código probé incluso escribir un código sin el error, pero me avisó que había un error igual, de nuevo subrayando parte de lo que definí como el mensaje personalizado)
![image](https://user-images.githubusercontent.com/80859173/114270558-08d50d80-99db-11eb-9150-d89a7b59ef22.png)

En fin, no sé si estuvo mal usar backslash, o si no había que simular un error de código (tampoco me quedó muy claro del enunciado). También me complicó el hecho de que no se explicara en alguna parte (en el enunciado o en la guía) el cómo y para qué se ocupa la palabra reservada "raise".

Desde ya gracias.

**Comment by aaossa** [comment]
Hola @JuanpaBC , tal como dices, lo que se espera en ese ejercicio es que solo lancen la excepción, es decir, que solo escriban la línea con `raise`. Veamos cada una de tus capturas:

1. Aquí el error es porque el intérprete no alcanza a llegar al final de la celda antes de ejecutarla, porque definiste una función. Lo que te falta son los `:` después de la definición de la función. Puedes verificar que la definición de la función ocurre antes que la ejecución del código cambiando el `raise` por un `print`, cuyo *output* nunca verás mientras la sintaxis no sea correcta.

2. Sobre este error entiendo tu duda, y lo que hice fue probar definiendo el *string* de otra forma:

```python
raise NameError("Hola como \
	estas")

raise NameError(("Hola como "
	"estas"))
```

En la primera ya viste que el error se reporta en la segunda línea, mientras que en la segunda el error se reporta en la primera. Lo que dices en verdad me hace sentido y también esperaría que la línea reportada fuera justamente donde está el `raise`. De todas maneras, al parecer esto ya fue reportado como un *bug* en Python ([reporte 1](https://bugs.python.org/issue12458), [reporte 2](https://bugs.python.org/issue37647)) y está corregido en las últimas versiones (esta captura es de Python 3.9.2):
 
![image](https://user-images.githubusercontent.com/10425834/114404267-8b90d080-9b73-11eb-8486-6be91b6dbf3d.png)

3. Tal como dices y se explica en los contenidos, `raise` lanza la excepción, no solo imprime o agrega el mensaje, sino que en verdad reporta a Python que ha ocurrido una excepción. Perfectamente podrías dejar solo la línea del `raise` y aún así tu programa se detendría (es lo que esperamos hagan en este ejercicio).


En resumen, da lo mismo como definas el *string*, de todas formas la excepción es lanzada y reportada a Python. Sobre el ejercicio, es suficiente con que escriban la línea con `raise` para lanzar la excepción. Y el uso de `raise` es para poder elegir cuál es la excepción que se quiere lanzar y de paso agregar un mensaje explicativo, todo con el fin de reportar mejor a quien programa qué es lo que está produciendo la excepción. 

Si algo no te queda claro o sigues con dudas pregunta por acá no más 👌 ¡Éxito con tu estudio!

**Comment by JuanpaBC** [comment]
Hola Antonio, muchísimas gracias por tu respuesta y tu investigación, siento que entiendo mucho mejor!
