### ISSUE TITLE
Duda aplicación de contenidos para esta tarea.

### ISSUE THREAD

**Issue by oscars810** [IIC2233/syllabus#203]
Hola!
Me dí cuenta que he usado más la materia de estructuras de datos que clases para modelar algunas cosas como las pistas y autos. ¿Eso no debería ser motivo de descuento no?

PD.: Aclaro que igual he usado herencia y multiherencia.

**Comment by KnowYourselves** [comment]
Hola @oscars810!

Para esta tarea se va a evaluar que **las entidades de tu programa estén representadas por clases**. Por ejemplo, si para ti una pista está representada por un diccionario o algo símil **no tendrás puntaje completo**, ya que no estás modelando con objetos.

La idea es que todas las entidades estén asociadas a una clase y luego puedas ocupar las estructuras de datos que conoces para hacer que la implementación de funcionalidades de estas clases sea más simple.

Éxito!
