### ISSUE TITLE
Duda con cada valores de los parámetros

### ISSUE THREAD

**Issue by tomasvasquezp** [IIC2233/Syllabus#203]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! mi duda está en que no se si los valores de los parámetros que vaya agregando a parámetros.py se los tengo que asignar yo, es decir, si tengo CANSANSIO,yo le pongo el valor que quiera a CANSANCIO o lo tengo que calcular de alguna parte?

gracias!

**Comment by Drpinto1** [comment]
¡Hola @tomasvasquezp!

Efectivamente los valores de los parámetros los debes ir decidiendo tu, teniendo cuidado de que tengan sentido.
Por ejemplo los valores que son un porcentaje, como `CANSANCIO` o `PROB_CAB`, solo tienen sentido con un valor entre 0 y 100, mientras que los costos, como `ORO_GANADO` y `PRECIO_CURA` tendrán valores arbitrarios que podrás decidir más libremente.

Cuéntame si te quedan más dudas relacionadas y responde o reacciona a este mensaje con un emoji si queda claro 😄

**Comment by Andrssilva** [comment]
El porcentaje en que aumentan la resistencia, ataque, agilidad, etc, debe ser multiplicativo, aditivo, o lo podemos decidir nosotros?
