### ISSUE TITLE
Problema con tamaño de la ventana al ejecutar Demo.py

### ISSUE THREAD

**Issue by Drpinto1** [IIC2233/Syllabus#203]
Hola! Ejecuté el módulo Demo.py para ver como funcionaba la interfaz que nos entregaron, pero la ventana generada es más grande que mi pantalla, por lo que hay varios botones y elementos que no se ven; además cada vez que se ejecuta obtengo el siguiente output en la terminal:

> QImage::scaled: Image is a null image
QPixmap::scaled: Pixmap is a null pixmap

Con la segunda línea se repitiéndose 28 veces; podría intentar arreglar manualmente el problema de la ventana, pero claramente no es el objetivo de la tarea y no sé exactamente qué representa o como arreglar el problema que se muestran en consola :(
 Existe una manera simple de arreglar el problema?
Gracias de antemano!

**Comment by bimartinez** [comment]
Iba a comentar precisamente lo mismo, tengo el mismo problema de el output en la terminal además que el fondo de la pantalla de inicio está en negro.

Saludos!

**Comment by IchottMano** [comment]
@Drpinto1 @bimartinez Hola!
Descargaron la carpeta con las imágenes necesarias?
Ese error puede deberse a que intentan correr el script directamente desde la carpeta "GUI".
Intenten ver si tienen el mismo error corriendo el archivo fuera de la carpeta o usando *pycharm* en un *proyecto* que esté fuera de GUI.
Si no funciona, manden por favor un pantallazo de que sucede.
Saludos!

**Comment by Drpinto1** [comment]
No tenía el problema de del inicio, pero intenté seguir las instrucciones dadas, moviendo el script fuera de la carpeta GUI, al hacerlo, levantó errores al importar desde los otros módulos; moviendo los demás móduos, todas las pantallas se veían negras, pues no habían Assets, mover la carpeta de Assets junto a las otras no tiene sentido, pues sería replicar la carpeta GUI en otra carpeta. Luego de esto, moví todo de vuelta a la carpeta y comencé a tener el error mencionado por @bimartinez, al iniciar, además de tener botones fuera de la pantalla, la pantalla inicial está en negro, intenté borrar la carpeta completa y bajarla nuevamente del Syllabus, pero el error persiste; me di cuenta que si al abrir el juego, entro a  "Mi Equipo" o "Campeonatos" y vuelvo al menú principal (con el botón que asumo dice Atrás), el fondo aparece, sin embargo cada vez que ejecuto el módulo, este parte en negro con los botones visibles. El output de la terminal no cambió, por lo que adjunto las imágenes de las Pantallas de menú con los botones y aparentemente el puntaje (basado en las imagenes del enunciado) fuera de rango, el menú de inicio con fondo negro y el output en la terminal (Obtengo lo mismo ejecutando desde PyCharm)


![campeonatos](https://user-images.githubusercontent.com/26233548/38760960-8eb84270-3f55-11e8-9b96-7452d7a4aacb.png)
![mi_equipo](https://user-images.githubusercontent.com/26233548/38760962-8f581462-3f55-11e8-9693-9c7f59f05731.png)
![menu_inicial](https://user-images.githubusercontent.com/26233548/38760961-8f37351c-3f55-11e8-88be-cf4fe14465ea.png)
![terminal](https://user-images.githubusercontent.com/26233548/38760963-8f768528-3f55-11e8-83c5-49a0e9808f91.png)

**Comment by IchottMano** [comment]
@Drpinto1 
Bueno, el error que veo en la segunda y cuarta imagen que envías se debe probablemente a que no tienes las fotos de los jugadores en tu carpeta *assets*.
Si lees el enunciado mas cuidadosamente en una parte dice que debes entrar a [este link](https://drive.google.com/drive/u/1/folders/1tpkfgtRwoEzmS3I58szN0yX-9lQQSPfg) donde hay un archivo .zip con las imágenes de los jugadores dentro (Esto se debe a que las imágenes son muy pesadas y github no permite subir archivos muy grandes). Descomprime  el archivo y mueve la carpeta resultante directamente a tu carpeta de assets.
El error a primera vista se debe a que QPixmap está tratando de escalar un pixmap (imagen) que no encuentra, por lo que es *null*.
Hazme saber si esta solución te funciona.
Saludos!

**Comment by Drpinto1** [comment]
Hice exáctamente eso, pero no se arregló el problema, sin embargo, revisando el código de los módulos _clases.py_ e _interfaz.py_ me di cuenta de inconsistencias en los paths a las imágenes, pues en ocasiones aparecen las palabras _Fondo_ y _Assets_ escritas con y sin mayúsculas, reescribiéndolas todas para que fueran concordantes con los nombres de imágenes y carpetas del Syllabus se atteglan el problema del fondo y los sprites (que continuaba al tener descargadas las imágenes).
Asumo que los demás problemas también pueden deberse a erroes de código, debería seguir revisando   los módulos de la carpeta GUI o esperar? Gracias de antemano

**Comment by Drpinto1** [comment]
Logré arreglar todos los problemas que tenía con la GUI, a pesar de que el enunciado dice que no debemos alterarla, no sé como solucionarlo de otra forma pues son errores de código, si alguien más tiene los mismos problemas (que persisten luego de la actualización de GUI que nos anunciaron por correo) estás son las soluciones que encontré:<br /><br />

-  __Fondo Negro__: Módulo _Interfaz.py_, línea 18, cambiar la F en fondo a minúsculas; nueva línea:

oImage = QImage("Assets/fondo").scaled(1366, 697)  # Ponemos el Background<br /><br />

- __Imágenes de Jugadores__: Módulo _clases.py_, líneas 122, 153, 163, cambiar la a de assets a mayúsculas, líneas nuevas:

122: self.label.setPixmap(QPixmap('Assets/photo/' + id).scaled(100 * scaled, 100* scaled))
153: self.label.setPixmap(QPixmap('Assets/photo/' + self.id).scaled(100 * self.scaled, 100* self.scaled))
163: self.imagen.setPixmap(QPixmap('Assets/photo/' + jugador.id).scaled(100, 100))
<br /><br />

- __Botón atrás__: Módulo _Interfaz.py_, línea 50, cambiar el primer argumento de la llamada (1275) por un valor menor hasta que el botón _atrás_ quede dentro de la ventana, en mi caso este valor es 1210, nueva línea:

self.boton_atras.setGeometry(1210, 1, 90, 40)<br />
<br />

- __Indicador Esperanza__: Módulo _Interfaz.py_, línea 105, cambiar el primer argumento de la llamada (1200) por un valor menor hasta que el indicador de _Esperanza_ quede dentro de la ventana, en mi caso este valor es 1135, nueva línea:

self.label_puntaje.setGeometry(1135, 520, 160, 40) <br />
<br />

Espero que le ayude a alguien que tenga el mismo problema :smile:

**Comment by santilaguna** [comment]
@behrmann97 intente la solución que se propone y no me funciona =( ayuda veo todo negro, he hecho todo lo que aparece en las issues

**Comment by santilaguna** [comment]
@IchottMano 
Tal vez esta información puede ayudar a orientarme con la solución,
Cuando ejecuto el demo.py desde adentro de la GUI (cambiando los import) si me corre. Y cuando lo ejecuto afuera, si funciona pero no me carga ninguna imagen

**Comment by FJavierOss** [comment]
Por si a alguien le sirve a estas alturas. Yo cambie "Assets/fondo" por "GUI/Assets/fondo" en Interfaz.py, y
"Assets/cancha_inferior" por "GUI/Assets/cancha_inferior". Haciendo eso es la única forma en la que he logrado importar correctamente (en terminos de que las imagenes no aparezcan en negro) desde mi archivo main.py la clase Juego perteneciente a demo.py
