### ISSUE TITLE
[Probabilidad muerte]

### ISSUE THREAD

**Issue by Okhan97** [IIC2233/Syllabus#203]
Hola, esta bien la formula de probabilidad de muerte ?
Pregunto porque el "min" de mas afuera es inutil, pues en el mejor de los casos el 1er valor (del min de mas afuera) daria 0,3, y SIEMPRE seria mas bajo que 1.

Otra opcion que veo mas logica seria que el "min" de adentro sea realmente un "max"

**Comment by gbordoni** [comment]
Todos los min de las formulas son inutiles xd

**Comment by maxfreymo** [comment]
@Hernan4444 ayuda :(

**Comment by Hernan4444** [comment]
@Okhan97 @maxfreymo Al final se decidió que considera el min de adentro como un max.

Saludos!!
