### ISSUE TITLE
Problema con error en importación

### ISSUE THREAD

**Issue by AaronPantoja** [IIC2233/Syllabus#203]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola!, cuando quiero correr una función que tengo en mi código principal, me sale el error que voy a poner abajo que parece que es por una importación circular que no se como poder arreglarla o que puedo estar haciendo mal.

File "c:\Users\ap7on\Desktop\progra av\AaronPantoja-iic2233-2022-2\Tareas\T1\principal_.py", line 1, in <module>
    from clases import Programon_agua, Programon_fuego, Programon_planta, Programon, Objeto, Baya, \
  File "c:\Users\ap7on\Desktop\progra av\AaronPantoja-iic2233-2022-2\Tareas\T1\clases.py", line 1, in <module>
    from menus_y_funciones import instancias_objets, instancias_trainers
  File "c:\Users\ap7on\Desktop\progra av\AaronPantoja-iic2233-2022-2\Tareas\T1\menus_y_funciones.py", line 1, in <module>
    from clases import Programon_agua, Programon_fuego, Programon_planta, Programon, Objeto, Baya, \
ImportError: cannot import name 'Programon_agua' from partially initialized module 'clases' (most likely due to a circular import) (c:\Users\ap7on\Desktop\progra av\AaronPantoja-iic2233-2022-2\Tareas\T1\clases.py)]

**Comment by MrNachoX** [comment]
Hola @AaronPantoja ,
Esto sucede cuando tienes dos o más módulos que se importan uno al otro y es una señal de que debes reorganizar la estructura de tu código. Según lo que entendí del error, tienes la siguiente importación circular:

![imagen1](https://user-images.githubusercontent.com/89955800/190397613-fccaf171-9644-4f16-872d-8bd0072d8404.jpg)

Para solucionarlo debes intentar reorganizar tu código moviendo funciones para eliminar uno de estos imports. También puedes intentar mover las funciones que son requeridas por ambos archivos a un nuevo archivo.

![imagen2](https://user-images.githubusercontent.com/89955800/190397625-ba058b46-f060-4c6f-bc9f-89a349892a50.jpg)

Espero que se entienda. Quedo atento por si sigues con dudas.
