### ISSUE TITLE
Problema con PYQT5

### ISSUE THREAD

**Issue by behrmann97** [IIC2233/Syllabus#203]
Al hacer el import "from PyQt5.QtWidgets import QApplication" del gui, me reconoce PyQt5, pero da el error "from PyQt5.QtWidgets import QApplication
ImportError: DLL load failed: No se puede encontrar el módulo especificado."

**Comment by iqacevedo** [comment]
Hola, 

Intenta probar con alguna de las soluciones que en aparecen en [Google](https://www.google.cl/search?q=python+Pyqt5+ImportError%3A+DLL+load+failed&oq=python+Pyqt5+ImportError%3A+DLL+load+failed&gs_l=psy-ab.3..0i71k1l4.33716.33716.0.33912.1.1.0.0.0.0.0.0..0.0....0...1.1.64.psy-ab..1.0.0.giv1Sf89iTY).
Tambien puedes probar [aca](https://github.com/IIC2233-2016-02/Syllabus/issues/204) con la solucion que se dio a un problema similar pero con PyQt4 en el semestre 2016-2.
Tambien puedes intentar lo que comentan [acá](https://stackoverflow.com/questions/36666225/pyqt5-the-dll-load-failed-the-specified-module-could-not-be-found).

Nos cuentas si es que encuentras alguna solución que te sirva, en caso contrario vuelve a preguntarnos.

Saludos!

**Comment by behrmann97** [comment]
Hola, probe todo lo sugerido, pero lo más "lejos" que llegué fue que me diera el error
 " DLL load failed: %1 is not a valid Win32 application"
He probado de todo (32 y 64) y no logro hacerlo funcionar :(

**Comment by iqacevedo** [comment]
Algunas preguntas para tener más claridad, ¿que sistema operativo tienes ?. Si es Windows de 64 bits probaste desinstalándolo completamente Python de 32 bits e instalando todo de nuevo pero con Python de 64 bits? ¿Tienes instalada otra versión de Python además de la 3.6?.

**Comment by Sforrego** [comment]
![whatsapp image 2017-09-02 at 18 42 30](https://user-images.githubusercontent.com/26422390/29998990-d3b9e1cc-900e-11e7-91f9-f7e690dccd52.jpeg)


porfavor ayudenlo esta desespera3

**Comment by cfernandez9** [comment]
¡Hola! instalé brew en mi computador y me apareció "Installation succesfull" y después instalé PyQt5, pero me aparecen varios errores. Traté de arreglarlos y lo instalé de nuevo, pero todavía sale que no existe el comando:

Warning: pyqt 5.9_1 is already installed
MacBook-Pro:~ CFV$ import PyQt5
-bash: import: command not found

**Comment by iqacevedo** [comment]
@cfernandez9 prueba abriendo Python primero en la consola, escribe `python`, `py` o `py3`, después que se abra Python prueba escribiendo `import PyQt5`, si se importa correctamente debería estar bien instalado, por lo que te recomendaría probar la interfaz de la T02 para asegurarte de que puedas correrla sin problemas.

Saludos !

**Comment by cfernandez9** [comment]
Gracias

**Comment by AngelMatias** [comment]
A mi simplemente no me lo reconoce
<img width="577" alt="captura de pantalla 2017-09-03 a la s 20 51 50" src="https://user-images.githubusercontent.com/30705123/30007664-85a493d8-90ea-11e7-8dc9-f21a554ee01a.png">

**Comment by iqacevedo** [comment]
@AngelMatias puedes darnos más información acerca de tu error ? Que te aparece en la consola cuando intentas correr demo.py, si en la consola abres Python y escribes `import PyQt5`, que te aparece ?

Saludos !

**Comment by AngelMatias** [comment]
Eso aparece
![Uploading Captura de pantalla 2017-09-04 a la(s) 10.16.52.png…]()

**Comment by AngelMatias** [comment]
Eso aparece
<img width="1280" alt="captura de pantalla 2017-09-04 a la s 10 16 52" src="https://user-images.githubusercontent.com/30705123/30028298-de2d9b74-915a-11e7-93ad-dfc8a7a73235.png">

**Comment by stephichau** [comment]
@AngelMatias ese error dice que no tienes instalado PyQt5

**Comment by AngelMatias** [comment]
y como lo instalo?

**Comment by stephichau** [comment]
@AngelMatias revisa la (wiki)[https://github.com/IIC2233/Syllabus/wiki]

**Comment by AngelMatias** [comment]
pero PyQt5 es un paquete? una libreria?
sorry lo básico de la pregunta, pero tuve intro hace 6 años y no recuerdo nada 😓

**Comment by AngelMatias** [comment]
Cual de todas D: ?
<img width="263" alt="captura de pantalla 2017-09-04 a la s 10 56 28" src="https://user-images.githubusercontent.com/30705123/30029470-bcda6c90-915f-11e7-9542-68ab498cebbb.png">

**Comment by AngelMatias** [comment]
Descargue esto, pero como lo instalo ?? :(
que alguien me ayude que estoy terrible perdido 😩
<img width="401" alt="captura de pantalla 2017-09-04 a la s 15 57 51" src="https://user-images.githubusercontent.com/30705123/30036455-e9f5b106-9189-11e7-97a6-a0fb6a72a08b.png">

**Comment by gabrielpinkman** [comment]
creo que en la wiki sale pasos para instalarlo con pip, no sé si en mac también se puede, pero la wiki explica bastante al respecto, y suponiendo que todxs lxs encargadxs del ramo son empáticos con la gente UC debería existir algún modo de instalar PyQt5 en mac

**Comment by gabrielpinkman** [comment]
@AngelMatias revisé y no se llama pip, se llama brew o algo así, en la wiki si salen pasos de como instalar PyQt5 en un mac
