### ISSUE TITLE
Uso libreria os.

### ISSUE THREAD

**Issue by Benjamin-Valdesa** [IIC2233/Syllabus#204]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Mi duda es si es posible ocupar la libreria os.

De esta ocupe la funcion path.join(), con el fin de unir de manera correcta la ruta hacia el archivo "predios.txt". 

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by FireGopherr5925** [comment]
Hola, si se puede, en el mismo #10 salen las librerias permitidas. Específicamente hablando de os. se permiten, os.path.join, os.path.exists, os.path.isfile, os.path.dirname, os.path.basename, os.path y os.listdir. Espero haberte ayudado!

**Comment by Hernan4444** [comment]
Hola @Benjamin-Valdesa 

Por favor no olviden revisar que los "check" que les pedimos completar. Justo el tercer check es que tu dude "**no** se trata sobre una librería o built-in, ya que eso se pregunta en la issue creada para ello", cosa que no ocurre aquí. Hay una issue específica para todo lo que es librerías permitidas.

¡Éxito con el curso! 🦖
Saludosヾ(＾-＾)
