### ISSUE TITLE
Duda primer tipo de error en ejer prop 1.2 s-04 (Menú simple sin manejo de excepciones)

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#204]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, para el siguiente error que pruebo en el código:
![image](https://user-images.githubusercontent.com/80859173/114271397-1b514600-99df-11eb-92a4-826e59f0d40e.png)
esperaba que la excepción fuera del tipo TypeError, por ingresar un string a la función "int( )" que debiera recibir solo valores int.
Agradecería si me pueden ayudar a entender por qué es ValueError.

Desde ya gracias.

**Comment by nanglada** [comment]
Hola Juanpa 🙌

La diferencia entre el TypeError y el ValueError es súper sutil así que no es raro que te haya confundido. 
TypeError se refiere a los problemas cuando el tipo de dato que se entregó no corresponde con lo pedido. En cambio, el ValueError es aquel donde el tipo de dato que se dio está bien, pero el valor específico que toma este no es correcto. 

Específicamente con el ejemplo que das tú, el int( ) debe recibir un string que pueda ser convertido en un número entero, de la forma '5' o '1000'. Por lo tanto, cuando tu le entregas un string 'c', el tipo de dato está correcto. El problema ahí es el valor específico del string que le das. Es por eso que se produce un ValueError. 

Para que se provocara un TypeError, tendrías que entregarle a tu programa un tipo de dato que bajo ninguna circunstancia pueda convertirse en un int. Por ejemplo, si tu input fuera una lista de la forma [1], al intentar hacer int([1]), obtendrás un TypeError ya que ningún tipo de lista, sin importar el valor que tome, podrá ser convertido a un int.

![duda errores](https://user-images.githubusercontent.com/62104901/114279479-e9ea7180-9a02-11eb-9687-910f117d7bdd.PNG)

Ojalá te haya quedado un poco más claro. Suerte! 🤩

**Comment by JuanpaBC** [comment]
Muchas gracias Nati, me quedo clarísimo!
