### ISSUE TITLE
colocar pieza

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#204]
en el enunciado se dice "Al momento de colocar una pieza, si un lado est ́a en contacto con otra pieza, ambas deben poseer el mismo tipo de segmento. En caso contrario, no se debe permitir poner la pieza en esa orientaci ́on."

se pide que todos los puntos de contacto sean iguales?

**Comment by fnquinteros** [comment]
Hola! lo que se pide es que, si 2 piezas están en contacto, deben tener el mismo tipo de lado en contacto. Esto es, si una pieza con borde de ciudad tiene a otra pegada por ese lado, la pieza pegada debe tener un pedazo de ciudad también. Ojalá haya quedado más claro 😅 Saludos!

**Comment by Arcoirisky** [comment]
¿A qué te refieres con eso? 
Se supone que tú pieza debe de tener 6 lados designados con P,G,C y R. Estos se deben juntar con ellos mismos. No puedes juntar P con otro que no sea P y lo mismo con los otros :0

**Comment by rihanuch** [comment]
entiendo que no pueda pasar esto:
<img width="501" alt="captura de pantalla 2017-09-01 a la s 19 56 11" src="https://user-images.githubusercontent.com/26392931/29990313-abd979de-8f4f-11e7-9056-1927b7a3ce30.png">

pero mi duda es si puede pasar esto:
<img width="141" alt="captura de pantalla 2017-09-01 a la s 19 56 18" src="https://user-images.githubusercontent.com/26392931/29990318-b33665c0-8f4f-11e7-8cc0-775aca124f66.png">

**Comment by rihanuch** [comment]
porque se esta topando una C con un G ( arriba de la iglesia ⛪️ (?))

**Comment by fnquinteros** [comment]
No puede pasar

**Comment by Arcoirisky** [comment]
No, porque tienes una ciudad con un pasto y pasto con ciudad (C-G y G-C)

**Comment by stephichau** [comment]
Efectivamente hay un error en esa imagen, pero era de ejemplo para ilustrar la sección de historial.
