### ISSUE TITLE
Error "distro-info" al instalar PyQt6 y requests. 

### ISSUE THREAD

**Issue by Kareen45** [IIC2233/Syllabus#204]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

Tengo problemas para instalar pyqt6 y requests, a pesar de que pude instalar correctamente ubuntu. En ambos casos, me aparece un error relacionado con "distro-info".
![a](https://github.com/IIC2233/Syllabus/assets/127404892/fd197dae-8481-4fde-baa5-9108547a8120)
![b](https://github.com/IIC2233/Syllabus/assets/127404892/ed5cebcf-ecfa-41ad-a2a6-26f3db75e7f4)

**Comment by mskdancers** [comment]
Hola!
¿Te corren los archivos de interfaces gráficas? No veo que te de un error específico, hay veces que la terminal da advertencias pero los códigos no tienen problema al correr. Avísanos si es que te corren los archivos y si no, manda una foto del error que te da al correr el archivo. Saludos!
