### ISSUE TITLE
Problema atributos adicionales subclases

### ISSUE THREAD

**Issue by jpperez5** [IIC2233/syllabus#204]
Estoy teniendo un problema a la hora de definir variables pertenecientes a una subclase.
Mi clase madre se ve mas o menos así:
class Mainclass:
    def __init__(self, a1, a2, a3, a4, a5, a6 = 0):
        self.a1 = a1
        self.a2 = a2
        self.a3 = a3
        self.a4 = a4
        self.a5 = a5
        self.a6 = a6

y la subclase la definí así:
class Subclass(Mainclass):
    def __init_(self, a1, a2, a3, a4, a5, a6, a7):
        super().__init__(self, a1, a2, a3, a4, a5, a6)
        self.a7 = a7

El problema es que cuando trato de definir una variable cualquiera:
var = Subclass(b1, b2, b3, b4, b5, b6, b7)

Me sale el siguiente error: __init__() takes from 6 to 7 positional arguments but 8 were given
Incluso si intento definir la variable anterior con un argumento menos, y trato de llamar a var.a7, el error me indica que Subclass no tiene un atributo a7.

**Comment by bpeirano1** [comment]
Hola!
Primero, el método init tiene que estar escrito como __init__.
Segundo, prueba super().__init__(a1, a2, a3, a4, a5, a6), ya que no hay que entregarle un "self" al super. Ahí te debería funcionar.

Suerte!

**Comment by jpperez5** [comment]
el init lo tengo bien escrito, hice lo que recomendaste y me manda el mismo error.

**Comment by bpeirano1** [comment]
Hola, sube el archivo a tu repositorio e indícame el nombre del archivo y  en que linea lo estas definiendo, para poder revisarlo.
