### ISSUE TITLE
Duda sobre PEP8

### ISSUE THREAD

**Issue by sofiaolmedos** [IIC2233/syllabus#204]
Hola! Quería saber si para PEP8, o al menos en lo que se considera para esta tarea, existe alguna reglas sobre como ordenar objetos y funciones. ¿Estaría mal si pongo como una función, después una clase y de nuevo otra función?

**Comment by DCCollao** [comment]
Hola @sofiaolmedos!

La especificación completa de lo que consideramos para el curso de PEP8 se encuentra en este [link](https://github.com/IIC2233/contenidos/blob/master/semana-00/1-gu%C3%ADa-de-estilo.ipynb). No se exige un orden específico entre clases y funciones, por lo que el tenerles intercalados no significaría un descuento. Aún así, el hacerlo de esta forma podría afectar la legibilidad de tu código y así dificultar su escritura.
