### ISSUE TITLE
Dar items a gatos

### ISSUE THREAD

**Issue by M4TI4D4CZ** [IIC2233/Syllabus#204]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, respecto a los items. Cuando compro un item y se lo doy a un gato, este puede recibir otro item y por lo tanto, tener dos items?  o en el caso de que este pueda recibir nuevamente un item, se reemplaza el item anterior? o apenas le doy un item a un gato este no puede volver a aparecer en el menu para otorgarle un item?

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Benjeeeh** [comment]
Hola!
En el enunciado se menciona lo siguiente:
![image](https://github.com/IIC2233/Syllabus/assets/78326186/92b30302-5cd5-4e2f-ba38-dcbc8ed20368)
Por lo que los diferentes tipos de ítems solo se pueden usar en las clases mencionadas para cada una, y no se podrían utilizar en Combatientes ya evolucionados, ya que en estricto rigor son clases nuevas (¿Aparte a qué evolucionarían?).

Saludos! Cualquier consulta no dudes en preguntar.

**Comment by M4TI4D4CZ** [comment]
Hola, no me refiero a eso, me refiero a que si le compro un  item a un combatiente, no necesariamente evoluciona, al menos no se menciona eso directamente. Por ejemplo, a un mago en la ronda le compro una lanza y se la equipo. Vuevo a la tienda y quiero comprar una armadura, como aun no utilizo el metodo evolucionar en el mago, aun es un mago, y por lo tanto compatible con la armadura, en este caso en particular, puedo reemplazar su item? o asumo que apenas le equipo el item la unidad va a evolucionar

**Comment by Benjeeeh** [comment]
@M4TI4D4CZ 

Si se debe evolucionar inmediatamente, ya que el menú tienda debe manejar todos los criterios para seleccionar un combatiente y asignarle un item, por lo que debería generarse el efecto del item dependiendo de la clase. Luego en otros menús no tienes la opción para manejar la evolución de los combatientes. Si bien no se utilizan las palabras que expliciten esto, es lo que se espera que hagan.

A raíz de esto, podrías realizar un supuesto que le permita asignar más de un item y luego crear toda una opción de evolución manual, pero sería trabajar de más.

Saludos!
