### ISSUE TITLE
AYUDA: Cometí un grave error y borré T2 del repositorio. 

### ISSUE THREAD

**Issue by JulianTR96** [IIC2233/Syllabus#204]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Realizaré una pequeña cronología. Hoy en la AF3 hice commit con mi código, sin embargo, como ocupe add --all, se hizo commit todo lo que llevo de la T2 hasta el momento. El problema con eso es que aún no creaba .gitignore por lo que subió todo! Entonces intentando arreglar eso yo mismo terminé borrando T2 del repositorio y no veo (quizás no tengo permiso) cómo crear la carpeta de nuevo. Así que en eso intente hacer un push para que apareciera T2 y git me imprimió que no se podía y que es posible que deba hacer primero un git pull, algo que ciegamente hice y pues como T2 ya no existe en el repositorio se borró todo en el repositorio local mío. Por alguna razón VSCode me mantuvo los archivos abiertos y pues me dediqué a copiar y pegar el código, pero parece que me faltan cosas o detalles. En fin, creo que rescaté todo lo importante, pero sería bueno poder volver a lo que tenía antes si fuese posible y si no, pues poder tener nuevamente T2 en mi directorio para realizar mis commit.

De antemano, muchas gracias

**Comment by Gsalinas1506** [comment]
Hola!
Al menos yo puedo ver que en tu repo tienes lo siguiente:
![image](https://user-images.githubusercontent.com/68198662/169456642-a7fa447b-ab6b-44f5-a222-80c082667956.png)
Puedes hacer click en la parte donde dice "32 commits", lo que te llevará a un historial de todos tus commits realizados.

En este punto deberías ver todos los commits que has realizado. Al costado derecho de cada uno tienes el botón `<>`, lo que te permitirá ver todos los archivos que tenías en ese commit. Según lo que entendí, alcanzaste a pushear todos los cambios que habías hecho en tu tarea antes de borrar la carpeta. Desde aquí ya podrías recuperar todo lo que alcanzaste a subir antes de que borraras tu directorio de la T2.

Deberías poder de crear la carpeta de nuevo (créala al nivel de las otras carpetas primero, has un push y debería poder subirse correctamente). Una vez hecho eso sube todos los archivos que quieras recuperar y pushea normalmente.

Dime si te funcionó! Saludos

**Comment by JulianTR96** [comment]
Hola! En su momento, pude salvar todo mi progreso y he continuado programando :). Sin embargo, no he podido crear esa carpeta T2 a través de dos métodos.

1) Crearla desde github.com en mi repositorio:
Por alguna razón me deja crear archivos, pero no carpetas y lo más probable es que se deba a mi inexperiencia, pero no veo cómo crearla yo. Es posible que no tenga los permisos...

2) Crearla en mi repositorio local y pushear:
Tengo ya la carpeta creada en mi repositorio con todos los archivos de mi tarea y cuando realizo el git add, commit, no hay problemas, pero al hacer push me entrega el siguiente mensaje:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/101663046/169683376-fc218382-626e-440b-a88d-31dafc6247ec.png">
De antemano, muchas gracias y disculpa por recién responder, me he estado enfocando en el programa :)

**Comment by Gsalinas1506** [comment]
Hola! Perdón por responder un Domingo, pero creo que esto podrá ayudarte.

[En este link](https://victorhckinthefreeworld.com/2018/09/21/como-crear-una-carpeta-en-un-repositorio-git-desde-la-interfaz-web-de-github/) se explica como crear carpetas desde la interfaz web de Github.

Sin embargo, el mensaje que te aparece en la consola se debe a que tienes cambios en tu repositorio remoto (Github) que no tienes en tu repositorio local (tu computador), lo cual se soluciona haciendo git pull de tu repo. Sin embargo, desconozco (o no recuerdo) si esta acción podría generar conflictos con el trabajo que actualmente tienes en tu carpeta, por lo que te recomiendo hacer lo siguiente:
- Respalda **toda** tu información que tengas en tu repositorio local en alguna parte
- Has git pull para tener los cambios del remoto en tu computador
- Crea `T2` dentro del directorio `Tareas`
- Incorpora los cambios que quieras hacer en tu trabajo tu repo, por ejemplo incluir los archivos que necesites en T2 (si algo desapareció o no está donde debería aprovecha el respaldo que hicimos antes) como si estuvieras trabajando normalmente
- Has el commit y git push

¡Listo! Deberías tener todo arreglado como antes

Si bien existen formas más pulcras de resolver estos conflictos de forma más limpia, creo que sería complicarte un poco más la vida. Mejor dejar la resolución de conflictos en git para otro ramo 😉 (IIC2143 - Ingeniería de Software goes brrr)

Estaré atento!

**Comment by JulianTR96** [comment]
¡Hola! 
No, por el contrario, muchas gracias a ti por responder. LO LOGRÉ. Resulta que había problema en el "merge" y me pedía que lo hiciese manual, así que busqué un par de cosas en la web y pude hacerlo. El link que mandaste me sirvió y pude crear el directorio correctamente. Si echas un vistazo a mi repositorio verás que tengo muchísimos commits y eso es porque tuve varios problemas entendiendo lo del merge y finalmente subiendo mi archivo. Además, cuando hice el backup, por alguna razón pensé que la carpeta sonidos y sprites iban en frontend así que el .gitignore había colocado esa dirección y se volvieron a subir, así que tuve que hacer el proceso nuevamente jajaj. Pero bueno, así es como se aprende más no?

Nuevamente, muchas gracias por tu ayuda :)

**Comment by Gsalinas1506** [comment]
Excelente! Me alegro que lo hayas solucionado.

Éxito con la Tarea :D

**Comment by victorhck** [comment]
> [En este link](https://victorhckinthefreeworld.com/2018/09/21/como-crear-una-carpeta-en-un-repositorio-git-desde-la-interfaz-web-de-github/) se explica como crear carpetas desde la interfaz web de Github.

Me alegro si el artículo sirvió de ayuda o guía para resolver el problema!! ;)
