### ISSUE TITLE
Grilla para Mapa

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#204]
Para realizar el mapa se me ocurrió utilizar un grilla, (estoy solo viendo como es la disposición, no que tengan la imagen correcta) y me pasa que lo elementos de la grilla quedan separados entre si (como se ve en la foto). Existe alguna forma de evitar que la grilla me separe las imágenes? o no es posible utilizar grillas para lo que quiero hacer?

![Captura](https://user-images.githubusercontent.com/48294819/57576394-e91ebe80-742c-11e9-97c6-a408ff3d4493.PNG)

**Comment by jmwielandt** [comment]
Hola! 😄 

Primero, te recomiendo indicar qué objeto de PyQt5 estás ocupando, con Grilla supongo que te refieres a una QGridLayout, pero podría ser otro tipo de grilla dentro de los tantos objetos que tiene PyQt. En relación a tu duda, buscando "qgridlayout qt5 "en google  nos aparece este [link](https://doc.qt.io/qt-5/qgridlayout.htm). 
![image](https://user-images.githubusercontent.com/37153467/57576523-73682200-742f-11e9-8518-8bb9feea16d8.png)

Aunque no es la documentación en python de PyQt, es la documentación original y puede ser de muuucha utilidad. 

![image](https://user-images.githubusercontent.com/37153467/57576532-985c9500-742f-11e9-883e-abe119b5e4c2.png)

Entre los métodos (que llaman _public functions_) puedes ver `setSpacing`, que de nombre suena a algo como lo que quieres.

![image](https://user-images.githubusercontent.com/37153467/57576539-c641d980-742f-11e9-89fd-5449d1b6e31e.png)
![image](https://user-images.githubusercontent.com/37153467/57576542-d3f75f00-742f-11e9-951a-07407db4e521.png)

¿Está en PyQt5? Confirmemos! 🤔

![image](https://user-images.githubusercontent.com/37153467/57576551-14ef7380-7430-11e9-90b3-0abf1072f505.png)

No parece la gran cosa esa "ayuda", pero no solo te confirma que está, sino que recibe un `int` como parámetro, podrías probar a ponerlo en 0.
Y funciona! 🎉 🎉🎉🎉
![image](https://user-images.githubusercontent.com/37153467/57576664-9ac0ee00-7433-11e9-964e-3bf665d6849f.png)

 Pero si cambias el tamaño de la ventana entonces se comienzan a separar. Eso te lo dejo a ti~

Mucho ánimo y échale un vistazo a toda la documentación si te quedan dudas 😄. También te recomiendo seguir viendo en los demás resultados de google, puede que encuentres incluso ejemplos de código que te pueden ser de utilidad (lo digo por experiencia personal).
 
#### PD: ten en cuenta que la grilla no te servirá para mostrar imágenes de elementos que puedan estar en posiciones no restringidas a esta, como el personaje.
