### ISSUE TITLE
Deshacer Jugada

### ISSUE THREAD

**Issue by leolivares** [IIC2233/Syllabus#205]
Hola! Tengo una duda con la opción de anular la ultima jugada que hizo el jugador.
Entiendo que para colocar una pieza debe estar conectada a otra, pero en cuanto a remover la pieza no encuentro alguna condición en el enunciado. Entonces, mi duda seria : ¿Esta permitido quitar la pieza en el caso de que otra, que este conectada a ella, quede sin piezas alrededor? ¿Seria este uno de los casos que retorna (-1,-1)?
Me parece que no se debería permitir, pero queria verificarlo.
Gracias!

**Comment by Arcoirisky** [comment]
Al deshacer una pieza estás retrocediendo en el historial entonces si tienes tres piezas seguidas y quitas la segunda, eso significa que la tercera nunca fue puesta. Es cómo volver en el tiempo. Esa sería una forma de verlo 😺

**Comment by leolivares** [comment]
Gracias! Pensé que era solo la pieza.

**Comment by MarceloSaldias** [comment]
Para dejarlo mas claro, en la siguiente situacion:

**Pieza inicial del tablero esta en (1,3)**

- Jugador 1 pone una pieza en (2,3)
- Jugador 2 pone una pieza en (3,3)
- Jugador 1 decide deshacer su jugada.

Al deshacer su jugada, en el tablero quedan las piezas en (1,3) y (3,3)? O tambien se deshace lo realizado por el jugador 2?
No me quedo muy claro porque la respuesta anterior me hace mas sentido cuando uno de los jugadores hace click en alguna de las secciones guardadas de la partida .-.

**Comment by Arcoirisky** [comment]
Ya entendí bien la pregunta. La respuesta que di anteriormente si es más para el historial. Cuando suceden casos como el que describen sí pueden quedar piezas sueltas en el tablero, para que el jugador 1 no le quite la jugada al jugador 2. 
¿Se entiende? 

Las reglas para las piezas se deben cumplir al agregarlas pero, si quitas una aplicando lo dicho en la sección "ctrl-z", entonces pueden quedar piezas solas en el tablero. 

Espero que ahora sí se haya respondido su pregunta 😅

**Comment by rihanuch** [comment]
Entonces solo puedo deshacer _**mi**_ jugada anterior?

**Comment by Arcoirisky** [comment]
Básicamente, si.

**Comment by leolivares** [comment]
Entonces, el único caso en que la función retroceder() retornaría (-1,-1) es que el jugador no haya jugado ninguna pieza todavía?

**Comment by MarceloSaldias** [comment]
@Arcoirisky Gracias por la aclaracion c:

**Comment by Arcoirisky** [comment]
@leolivares Es lo único que queda con sentido. Si nunca haz puesto una pieza, entonces no puedes retroceder.

**Comment by caespinoza5** [comment]
Una consulta respecto a este mismo tema:
Qué ocurre si, por ejemplo, jugador 1 coloca una pieza, luego jugador 2 coloca otra pieza y hace plot - twist, cambiando de color la pieza que jugador 1 recién había puesto, y luego jugador 1 hace retroceder? se elimina la última pieza que jugador 1 colocó y que además pertenece a sus piezas?

**Comment by mesantamaria** [comment]
Tengo la misma duda que @caespinoza5  
En ese caso no se podría retroceder porque la pieza ya no le pertenece al jugador 1 o no?

**Comment by bawas** [comment]
tengo la misma duda que @caespinoza5  y  @mesantamaria  :S

**Comment by stephichau** [comment]
@caespinoza5 @bawas Es correcto lo que dice @mesantamaria. La pieza no le pertenece al jugador 1 :)
