### ISSUE TITLE
Readme Tarea0

### ISSUE THREAD

**Issue by rifibla** [IIC2233/syllabus#205]
Hola, sucede que ayer leyendo mil veces el enunciado me di cuenta que mi tarea cuenta con un error enorme.
Pasa que el archivo seguidores es de la forma:

> Usuario,persona a la que sigue, persona a la que sigue,...

Y por error cada vez que me metía a ver el enunciado entendía que el archivo usuarios era de la siguiente forma:

> Usuario,seguidor del usuario, seguidor del usuario.
En base a esto tengo las siguientes dudas:
Dentro de la rubrica, aunque las formas de ver el archivo "seguidores.csv" son diferentes desde el punto de vista del enunciado. Siento que la intención de seguir un usuario va enfocada a la manipulación correcta de como buscar y escribir información en archivos con python, por lo que aun así, aunque el enunciado y mi tarea difieran en el formato de como llevar a cabo esta función, siento que la esencia es la misma. Considerando esto, ¿Me bajaría de forma significativa el puntaje relacionado a la función "seguir" si dejo tal como está mi tarea?  ¿Sería una buena idea cambiar esas cuantas lineas para que el formato de mi tarea respete el formato del enunciado ó lo informo en el readme para que asi mas adelante este punto sea considerado en la corrección de mi tarea?
Perdón, se que es un gran error mio. 
De antemano muchas gracias.

**Comment by gatochico** [comment]
Hola! Si revisas la distribución de puntaje, podrás ver que hay una celda dedicada a trabajar de forma correcta con los 3 archivos con extensión .csv . Por lo que habría un descuento en dicha sección.

Ahora, sobre si conviene o no arreglar el error, todo depende de cuántas líneas de código quieres cambiar vs. el descuento que tendrías en esa sección. Recuerda que el descuento por líneas cambiadas es 1 décima cada 4 líneas.

Con esas dos cosas piensa cuál de las opciones te conviene más. Finalmente, independiente de cuál elijas, menciona el error en tu README, para ayudar a la corrección. Espero haber ayudado! (:

**Comment by rifibla** [comment]
Muchas gracias @gatochico !
