### ISSUE TITLE
Error al volver a entrar al juego

### ISSUE THREAD

**Issue by Ilancf** [IIC2233/Syllabus#205]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Mi juego corre bien, pero al ganar y querer jugar el siguiente nivel a pesar de entregarle los datos en una señal al inicio igualmente quedan los de la partida pasada y se sobreponen, por ejemplo en la ProgressBar trata de avanzar desde 0, pero también trata de avanzar desde el valor que quedo anteriormente, a pesar de que le seteo el valor en 0 al inicio del juego. También por ejemplo, la mira cuando comienza aparece en donde le puse que aparezca pero luego al apretar para moverla se coloca automáticamente en donde se quedó en el nivel anterior

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by CristobalPerez-Cotapos** [comment]
Hola!! lo que comentas es un error muy común, y tiene que ver con como reinicias los datos de la partida pasada. 
Para la mira, me imagino que el problema es que actualizas la posición en la ventana pero no en el backend, por lo que se inicia correctamente pero luego se actualiza desde los valores guardados en el backend.
Para la progres bar me imagino que puede pasar algo similar, pero además se te pueden mezclar dos timers en un mometo determinado, por lo que actúa de dos maneras distintas, ten ojo en como terminas los timers al cerrar la ventana de juego.
Mi concejo es que reinicies TODOS los valores necesarios (tanto en el frontend como backend) al momento de cerrar la ventana de juego, y que detengas todos los timers y threads de una partida para que no afecten la siguiente. 
Suerte!!

**Comment by Ilancf** [comment]
Y como se reinician correctamente todos los datos, porque creo que lo estoy haciendo bien, pero no me resulta, ademas cuando hago self.hide() al final igual al entrar de nuevo se me sobreponen los datos de la partida nueva sobre la pasada y esto solo se arregla poniendo al final "nombre de lo que quiero ocultar".hide(), pero esto me trae otros errores despues entonces no entiendo. a demas cada ves que comienzo el juego devuelta le seteo el valor de la progrrsbar en 0, pero igual no se setea bien, entonces no entiendel error ni como solucionarlo.

**Comment by CristobalPerez-Cotapos** [comment]
Hola!! Si es que se te sobreponen en el codigo eso es por qué estás instanciando los labels y la progress bar de nuevo, por lo que se cargarán y una tapará la otra.
Ahí las alternativas son dos: o recetas todos los labels a sus valores iniciales al terminar la partida (y dejas de instanciarlosnde nuevo) o borras los labels de la partida anterior y mantienes solo los nuevos. 
Cuéntame si te resulta alguna de estas!! 😉

**Comment by Ilancf** [comment]
Pero aun no me dices como lo puedo hacer, si se que debo borrar el label, pero busque en internet y en los apuntes y no encontré como se hace se hace self."nombre".clear() o como se hace para poder borrar el anterior?

**Comment by CristobalPerez-Cotapos** [comment]
No estoy seguro si existe un método que lo "borre" pero puedes hacerles hide(), que en la práctica es similar.

**Comment by Ilancf** [comment]
Así lo hago, pero igual hay veces que falla y no se oculta la info anterior, es muy raro, yo creo que eso ya es una problema de pyqt5 porque he estado desde el viernes con el mismo problema y es puntual para 2 casos que falla a pesar que se hace lo mismo que en las demás ocaciones.

**Comment by CristobalPerez-Cotapos** [comment]
Hola!! Seguramente hay algún problema en la forma que estás usando hide, pero ahora revisándolo no lo he podido encontrar. 
Cómo estamos en la fecha de entrega, te recomiendo para esos dos elementos no complicarte y solo cambiarles el contenido, con métodos como setText() y similares
