### ISSUE TITLE
archivo puntajes.txt siempre existe?

### ISSUE THREAD

**Issue by cefierro** [IIC2233/syllabus#205]
Hola, en el enunciado nos dicen que debemos indicar cuando no hay puntajes registrados, mi duda es si podemos asumir que el archivo puntajes.txt existe, pero vacio en ese caso.

**Comment by DCCollao** [comment]
Hola @cefierro! Puedes asumir que el archivo existirá en la carpeta base de tu tarea al momento en que ejecutemos tu tarea.
