### ISSUE TITLE
Pauta T1

### ISSUE THREAD

**Issue by rodridelafuente** [IIC2233/Syllabus#205]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Estaba haciendo el ```README.md``` para mi tarea y me di cuenta de que en la sección _"Cosas implementadas y no implementadas"_  no me aparecen los items para evaluar mi rendimiento. Por lo tanto quería preguntar, **¿Dónde puedo encontrar la pauta de evaluación de esta tarea?** Espero su respuesta para así completar de manera adecuada el  ```README.md```.

**Comment by MrNachoX** [comment]
Hola @rodridelafuente ,
En la carpeta ```Tareas\T1``` del Syllabus hay una plantilla del README con los items ya puestos. La pauta completa de la tarea la puedes encontrar en AvanzadaApp.

**Comment by rodridelafuente** [comment]
Muchas gracias! ¿En qué parte de AvanzadaApp puedo encontrar la pauta completa? Porque la estuve buscando y no la encontré.

**Comment by MrNachoX** [comment]
Está en el menú lateral en la sección Mis entregas (tienes que iniciar sesión).
![photo1663248866](https://user-images.githubusercontent.com/89955800/190417960-65777d6c-501e-4b06-ade1-f1f078636955.jpeg)

**Comment by rodridelafuente** [comment]
![image](https://user-images.githubusercontent.com/105672234/190419401-e1bc5236-7c8f-4799-a468-27bb37d38c26.png)
No me sale eso, y además, me acabo de dar cuenta que la AS1 me sale como no entregada, cuando yo la hice y la entregué bien, antes del tiempo máximo de hecho. ¿Debería mandar un correo a iic2233@ing.puc.cl?
