### ISSUE TITLE
Varias dudas T02

### ISSUE THREAD

**Issue by anavarro01** [IIC2233/Syllabus#205]
Hola, tengo 3 dudas sobre la tarea 2:

1. En la parte de estadísticas, dice que se pueden pedir las infecciones y muertes por día. Se refiere a cuantos infectados y muertos ha habido en cada día que ha transcurrido?

2. En la parte de estadísticas, dice que se puede puede pedir el promedio de muertes e infecciones. Se refiere a #Muertos/#Días_transcurridos y #Infectados/#Días_transcurridos?

3. En la probabilidad de que una persona muera, claramente no hay que simular persona por persona la muerte (seria una simulación extremadamente larga), sino que ver que porcentaje de infectados va a morir y que esa cantidad muera, pero con este método se genera un problema: 
Se deberían morir solo la parte entera de la multiplicación de la cantidad de infectados X probabilidad de muerte. Con el resto, como lo hacemos? Porque, por ejemplo, puede pasar que queden 10 humanos, pero si la probabilidad de que mueran nunca es mayor o igual al 10%, nunca van a morir. Con este resto de personas habría que simularlo por cada una?

**Comment by gbordoni** [comment]
Me sumo al punto 3....a mi me pasa que llego a un minimo de 4 humanos pero como la probabilidad es tan baja no puedo matarlos.

**Comment by rrhurtado** [comment]
Hola, en la primera duda es tal como señalas, se refiere al número de infectados y muertos en cada día.

Respecto a la segunda duda, en el siguiente issue se aclaró el promedio de muertes e infecciones #178.

Si en efecto al correr tu programa se nota que esas 10 por ejemplo nunca mueren, pero se arregla al simular ese resto una por una, puedes dejarlo especificado en el readme y no debería haber problema. 

Saludos !
