### ISSUE TITLE
Round

### ISSUE THREAD

**Issue by vicenterodas** [IIC2233/Syllabus#205]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, tengo el siguiente problema. Utilice el método round -con dos decimales: round (numero, 2)- en cada momento que es pedido (dificultad, metros cavados, etc), pero aun así en algunos casos la cantidad de metros cavados es un decimal infinito (10.20000001) por ejemplo. Puede ser que esto ocurra de vez en cuando o  sin dudas es un error de mi código. Muchas gracias

**Comment by Benjeeeh** [comment]
Hola!
No es un error de tu código, es simplemente como funciona python al tratar con números decimales, lo cual puede ser muy poco preciso y es por esa razón el hecho de que aparezcan muchos decimales. De forma simple, Python al tratar con números decimales, los asimila como números infinitos (por ejemplo, el número 13.95 en realidad es 13.949999999999999, y así) debido a que el computador lee estos valores de manera binaria y las trabaja con bits, y al obtener una serie de bits estas son concatenadas formando números infinitos.  Puedes probar este caso en una consola de python escribiendo 0.1 + 0.2, en que debería obtenerse 0.3 pero no es así.
Existen diversas soluciones, pero para no ahondar en librerías, podrías:
1) Volver a aplicarle round al valor obtenido.
2) Crear una función que trunque tu número obtenido por la función pasándolo a string y cortarlo manualmente a 2 decimales y volver a pasar el valor obtenido a float para cálculos posteriores.
Estaré atento a cualquier consulta.

Mucho éxito con la tarea!!

**Comment by vicenterodas** [comment]
Perfecto gracias!
