### ISSUE TITLE
"str".split(",")

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#205]
esta funcion retorna una lista, esto significa que no la puedo utilizar y debo buscar otra manera de hacer el split, por ejemplo corriendo un for, o hacer a, b, c, d = "str".split(","). con e segundo ejemplo al almacenarlo cada uno en una variabla significaria que no estoy usando listas y que esta bien?

**Comment by IchottMano** [comment]
@ljrodriguez1 Hola!
Esto se responde en la issue #174 
Saludos!
