### ISSUE TITLE
Duda de "runtime", interpretacion de Python

### ISSUE THREAD

**Issue by luzmagurzua** [IIC2233/syllabus#205]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Estoy estudiando "excepciones" y no entiendo muy bien ¿a que se refiere que Python "sea un lenguaje interpretado"? 

Texto: Recordemos que las excepciones en Python solo se detectan en tiempo de ejecución (runtime) ya que es un lenguaje interpretado. 

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Julius9** [comment]
Hola @luzmagurzua 😄 En resumen existen lenguajes de programación interpretados (como Python) y compilados (como C++) ambos traducen el código a lenguaje maquina para poder ser ejecutados, pero difieren en el método de hacer esto. Un lenguaje interpretado va "traduciendo" linea a linea el código y por lo tanto cuando salta un error es cuando se esta ejecutando el programa. En cambio un lenguaje compilado necesita hacer un paso extra llamado compilación para poder ser ejecutado, en este se "traduce" de golpe todo el código y por lo tanto los errores te saltan en la compilación no cuando estas ejecutando el programa, por que para esa altura ya tienes arreglado el código. Ambos métodos tienen sus ventajas y desventajas obviamente 

Por eso en el contenido se explicita que los errores en Python solo se detectan en tiempo de ejecución, no antes.

Si tienes mas dudas respecto a este tema te recomiendo leer la info del siguiente link 📖 :  https://blog.makeitreal.camp/lenguajes-compilados-e-interpretados/
