### ISSUE TITLE
Error al importar PyQt5

### ISSUE THREAD

**Issue by YoGandalf** [IIC2233/syllabus#205]
No puedo importar PyQt5 no se por que.
Tambien me pasa que en anaconda prompt cuando hago [pip install pyqt5] o [pip3 install pyqt5] me dice [Requirement already satisfied:] y cuando lo hago en el cmd normal me dice ["pip" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.]
No se que estoy haciendo mal

**Comment by jeschuwirth** [comment]
Saludos, perdón por tardar tanto con la issue.

Tener problemas al instalar librerías es muy común y si vas por la malla de computación te va a pasar muy seguido que para un ramo te pidan librerías o software que tu computador no tiene ganas de instalar y gastaras mucho sólo tiempo en eso.

En tu caso tu problema viene de anaconda, el instalador de python te recomienda instalarlo con anaconda y suele traer muchos problemas a la hora de instalar librerias como el que estas teniendo ahora.

Lo que más te recomiendo es desisntalar python por completo y luego seguir los pasos en el siguiente link:
https://tutorial.djangogirls.org/es/python_installation/

Es importante que agreges el path durante la instalación como explican en el link.

Si todo sale bien deberías podes instalar PyQt5 sin problemas, si sigues sin poder instalarla comenta en la issue para poder seguir ayudandote

Suerte y ojalá todo funcione bien :)
