### ISSUE TITLE
Como se hace el README?

### ISSUE THREAD

**Issue by Mario-uc** [IIC2233/syllabus#206]
¿Hay algún lugar que diga como se hace el README? o hay que llenar los espacios con las respuestas correspondientes?

**Comment by KnowYourselves** [comment]
Hola @Mario-uc!

En tu repositorio, en cada carpeta de tareas puedes encontrar un ejemplo de README. Puedes ocupar este como ejemplo y rellenarlo, viene con una explicación de que tipo de cosas deberían ir en un buen README.

Quedo atento a cualquier duda!
