### ISSUE TITLE
dejar que se levante una excepcion

### ISSUE THREAD

**Issue by ptflores1** [IIC2233/Syllabus#206]
Si en alguna parte de mi programa tengo un `raise` y luego desde otro lado hago un `try` que podría captar tal `raise` pero quiero dejarlo pasar, es decir quiero que efectivamente se levante la excepcion como deberia hacerlo ? esta bien algo como esto:
```python
try:
    # Genera el levantamiento de la excepcion
except IndexError as err:
    raise err
```

**Comment by andresfdezc** [comment]
Si quieres que la excepción no sea tratada, simplemente no pongas el bloque `except` particular de dicha excepción.

Conceptualmente, lo que propones no sería una buena práctica, a pesar de que funcione. La idea es usar `raise` en el lugar exacto donde se genera el error. De esa forma, Python te va a poder llevar a la línea de código donde ocurrió el problema.

**Comment by ptflores1** [comment]
jajaja esta pregunta tenia mas sentido cuando la hice, gracias!
