### ISSUE TITLE
tablero-dimensiones int

### ISSUE THREAD

**Issue by rodrigopg908** [IIC2233/syllabus#206]
se puede asumir que al pedir las dimensiones del tablero, siempre se entregara una variable int? o puede  que te entreguen una variable str?

**Comment by jitorcas** [comment]
Hola! @rodrigopg908 

No puedes asumir que siempre te entregarán un int. Recuerda que los menú deben ser a prueba de errores, por lo que puede que recibas un carácter. 

Éxito en la tarea! ⚓️

**Comment by jitorcas** [comment]
@rodrigopg908 recuerda revisar el compilado antes de abrir una issue nueva. La pregunta fue respondida en la issue #103
