### ISSUE TITLE
Importar utils

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#206]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, cuando importo utils en el archivo main.py se me subraya de color amarillo, sin embargo funciona todo bien mi código. No sé si debo hacer algo o es normal que pase eso cuando se importa utils.

**Comment by FernandoTFH** [comment]
No hay nada malo, el tema es que el editor no puede ver el contenido el utils.pyc y eso le "molesta" el editor pero solo eso, no afecta al programa. En esta issue #113 se hizo una explicación un poco mas extensa, por si te interesa.
