### ISSUE TITLE
Comenzar y terminar pausa con "P"

### ISSUE THREAD

**Issue by nicolasgarciaes** [IIC2233/Syllabus#206]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola buenas, quisiera saber si es completamente necesario que se pueda pausar y despausar con la tecla P o con alguna tecla en general, ya que, actualmente puedo solo pausar y despausar apretando el botón "Pausa", por lo tanto, quería saber, si mencionándolo en el readme es suficiente o es necesario que se deba pausar con alguna tecla para obtener el puntaje completo.

**Comment by nzamorano** [comment]
Hola @nicolasgarciaes, **sí** es necesario que se pueda pausar el juego con la letra **P** (o con alguna otra tecla mientras lo menciones en tu readme), pues esto se pide explícitamente en el enunciado.
