### ISSUE TITLE
Duda sobre diminución de agilidad guerrero

### ISSUE THREAD

**Issue by matikasakoff** [IIC2233/Syllabus#206]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ]x De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Al definir a los combatientes guerreros, me dicen que luego de atacar su agilidad disminuye en un cansancio% y la agilidad de un combatiente según lo que dice el enunciado corresponde a un int que va de 1 a 10. Si al diminuirla luego de atacar y llego a un valor menor a 1 debo considerar que el guerrero ya no puede seguir o debo mantenerlo en 1 que es el mínimo?

**Comment by Benjeeeh** [comment]
Hola!

Exactamente, la agilidad, así como los parametros que lo indican, no deben salirse del rango ya sea por cualquier modificación que les afecte. En el ejemplo que das, debe mantenerse en 1.

Existe una materia en el curso que sirve mucho para manejar estos casos 👀

Saludos y mucho éxito!

**Comment by VicenteIgnacioSotoGonzalez** [comment]
En este mismo contexto, si algún atributo es aumentado/disminuido y el resultado final es un float, que se debe hacer al respecto? Se podría redondear?

**Comment by Benjeeeh** [comment]
@VicenteIgnacioSotoGonzalez 
Si, ya que el enunciado pide que estos valores siempre sean del tipo **int** :)

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Perfecto, muchas gracias!

**Comment by asapsanchez** [comment]
hola, una pregunta, esa disminución en la agilidad del caballero dura toda la ronda? o solo durante el ataque? y otra pregunta, si es que dura toda la ronda, y la ronda es ganada, los valores de agilidad y resistencia por ejemplo, restablecen? o quedan dañados
