### ISSUE TITLE
Experiencia 2 - control_remoto.py, problema con el atributo text()

### ISSUE THREAD

**Issue by constanza-norambuena** [IIC2233/Syllabus#206]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido

Hola, tengo una duda con respecto a la Experiencia 2 vista hoy en clases.
Al momento de ejecutar ```control_remoto.py``` y apretar los botones del control remoto, me tira el siguiente error 

![issue2](https://github.com/IIC2233/Syllabus/assets/141878091/1e2cfa64-d6c0-4bf8-a25c-af69ba2f821c)

Donde ```text()``` se utiliza específicamente en el método ```actualizar_canal``` y ```actualizar_volumen```.

![issue](https://github.com/IIC2233/Syllabus/assets/141878091/b0481043-7235-40b2-9866-695a75d7f15f)

 La profe mencionó que puede tener que ver con la falta de instalación de alguna librería, ya que al momento de posar el mouse sobre ```text()``` no se reconoce. Me podrían ayudar, por favor?

**Comment by dvillas28** [comment]
cuando defines al sender, te faltaron unas () al parecer
`sender = self.sender()`

ojala te sirva!

**Comment by mskdancers** [comment]
Hola!
Exacto, como dijo tu compañero, si es que ejecutas el código ```sender = self.sender``` estás diciendo que **sender** es igual al **método** ```self.sender```, y este método no tiene un atributo **text** (eso explica el error que te muestra la terminal, ```'builtin_function_or_method' object has no attribute 'text'```). Si es que cambias el código a ```sender = self.sender()```, estás especificando que **sender** es igual al **resultado** del método  ```self.sender```, y te debería funcionar. Avísanos si tienes cualquier otra duda, saludos!

**Comment by constanza-norambuena** [comment]
Síi era eso, muchas gracias!
