### ISSUE TITLE
Al crear una imagen con QPixmap, esta no se muestra en la ventana creada

### ISSUE THREAD

**Issue by pedrozavalat** [IIC2233/Syllabus#206]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

Hola tengo una duda cuando creamos una imagen utilizando QPixmap, ya que al momento de ejecutar el codigo, solo me aparece una ventana vacia sin la imagen. No se que error podria ser, ya que en el contenido de 'elementos-graficos-básicos' de la semana 6 (Interfaces gráficas), la imagen 'python.jpg' no se muestra en la ventana que se crea al ejecutar el codigo de ejemplo, siendo que esta se encuentra en la carpeta 'img', cuya ubicacion es la misma del archivo que estoy ejecutando. 
<img width="565" alt="Captura de Pantalla 2022-09-17 a la(s) 10 09 40" src="https://user-images.githubusercontent.com/105678668/190861618-94830184-de52-4331-ac3a-4735f19c0b4e.png">

Gracias!

**Comment by pedrozavalat** [comment]
Complementando  la duda, tambien debo comentar que cuando descargue la librería PyQt5, presento problemas en mi computador, por lo que no me aparecia en el terminal de VsCode. Asi que, tuve que crear un nuevo terminal abriendolo con 'Rosetta' y ahi soluciono mi problema. No se si eso tambien involucre errores para la utilizacion posterior del modulo PyQt5.

**Comment by pedrozavalat** [comment]
Solucione mi problema, dado que al principio del curso tuve un problema al descargar la libreria PyQt5, teniendo que crear un nuevo terminal abriendolo con 'Rosetta'. Asi que, al momento de ejecutar mi codigo utilizando python3 <archivo>, deben estar ubicados en el directorio donde se encuentra el archivo.

**Comment by DiegoMillaUC** [comment]
Hola Pedro! Claro, al momento de ejecutar python debes asegurarte de ejecutar el código con el terminal que posea una version funcional de python y pyqt5, y a su vez, debes fijarte que el directorio en el que se encuentra la terminal debe ser donde se encuentra el archivo.
