### ISSUE TITLE
Elementos de librería PyQt5 utilizables

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2233/syllabus#206]
Hola. Estaba revisando en la documentacion de qt y descubrí que la librería es muy extensa, y existen **muchos** elementos que no están en los contenidos. Podemos usarlos en la tarea?

Como ejemplo estaría ```PyQt5.QtWidgets.QGraphicsScene``` o ```PyQt5.QtGui.QPixmap```

Y más que nada, hay algún elemento de la librería que nos esté prohibido usar?

**Comment by Hernan4444** [comment]
Hola

Si pueden ocupar cualquier elemento de la librería 👍.  **No obstante,** los ayudantes no se manejan en general con cada objeto de dicha librería, sino con los esperados a utilizar en la tarea. Por lo tanto, ocupar alguno rebuscado como QGraphics (y derivados) hará que ante un error, los ayudantes no puedan ayudarte a buscar y solucionar dicho error.

Saludos ✌️

**Comment by JJJGGGG** [comment]
Pero más importante aún, qué debemos usar para cargar los sprites? Y para usar de "fondo"?

**Comment by Hernan4444** [comment]
Para eso, si se recomienda `QPixmap`. El comentario de cosas rebuscadas era principalmente para los QGraphics(y derivados) que tienen una forma de funcional diferente a los QObjects que estamos acostumbrados a ocupar.

Saludos ✌️

**Comment by JJJGGGG** [comment]
Y es posible hacer todas las funcionalidades de la tarea usando las funciones que están en los contenidos (aunque sea en extra)?

**Comment by Hernan4444** [comment]
Si y no, unos de los objetivos de la tarea es que busquen también en la documentación de ciertos objetos para hacer tales cosas. **Si es posible hacer cada funcionalidad** con todo las clases que están en contenidos y extras (aunque deberán ver la documentación para ver todos los métodos y atributos que hay), **pero hay otros objetos que pueden facilitar muuuucho más el trabajo** y tenemos fe que la encontrarán 😄. Por ejemplo, para ver la barra de vida se puede resolver con `QLabel`, `QPixmap` y editar el ancho de estos, pero hay un `QObject` que simplifica todo ese trabajo. 

Como _hint_: si buscas juegos realizados en PyQt5, puede que encuentres diversas cosas que pueden ser útil en el juego, aunque si llegas a encontrar algo que copiarás directamente, no olvides citarlo para no tener problemas con el plagio intelectual 😓.

Saludos ✌️

**Comment by jitorcas** [comment]
Hola! he estado trabajando con `QGraphicsView`  y me han surgido bastantes dudas que pueden significar que modelar la tarea usando `QGraphicsView` no sea buena opción :disappointed_relieved:. Quiero plantear mis dudas y en base a eso evaluar si modelar de nuevo la tarea o seguir buscando información.

He modelando clases `QGraphicsItem` que interactúan en el juego, como el personaje principal, enemigos, etc. Me ha servido bastante para representarlo gráficamente con los comandos `scene.removeItem()` y `scene.addItem()` siendo scene del tipo `QGraphicsScene()`, hasta el momento solo he modelado el cuadro del juego, sin los botones adicionales que permiten todas las funcionalidades ( botón "empezar", "mejoras en las torres", etc) encontré como hacerlo agregándole las funcionalidades mediante código pero el problema surge cuando quiero implementar una interfaz creada en Qt designer y hacerla funcionar con mi cuadro de juego. Es posible relacionar ambas? o solo podré implementar las funcionalidades mediante código? :grimacing:

Otra duda que hizo replantearme el modelo, es que al crear las monedas que aparecen en el juego logro hacer que aparezcan y desaparezcan, pero leyendo de nuevo la tarea pensé en que las monedas podrían ser un objeto `Thread`, actualmente las tengo como instancias de una clase que hereda de `QGraphicsItem` y no sé si es posible que las monedas hereden de ambas clases o tendré que hacerlas que hereden de `Thread` y tengan un método que cree una imagen (de clase `QGraphicsItem` ) de ellas para poder ponerlas en scene ?  :grimacing:

Lo siento lo extenso, la verdad es que me preocupa que las clases que estoy utilizando hasta el momento no me permitan cumplir con los requisitos de la tarea y me dé cuenta tarde :cold_sweat:, hasta el momento las soluciones que he encontrado son con librerías no permitidas, por eso recurro a ustedes para saber si continuar o no con el modelo.

**Comment by Hernan4444** [comment]
Hola

Yo usé QGraphics hace 3 años y con PyQt4 y si pude relacionar ambas cosas (interfaz creada en Qt Designer y hacerla funcionar con mi cuadro de juego). Hace varios semestres lo pasé todo a PyQt5 (cambiar unos métodos que ya no existían y la importación de módulos) y funcionó todo bien, así que puedo asegurar que funciona lo que quieres hacer.  ¿Como lo hice? Ya no recuerdo bien, fue hace mucho tiempo y por lo mismo no recomendaba usar `QGrahics`, porque no es un contenido que si o si manejen los ayudantes.

Sobre la segunda duda, el comportamiento de la moneda debe ser controlado por algún thread, pero la implementación gráfica puede ser controlada de otras formas y cuando nos referimos a "ser controlado por algún thread" es que tiene un comportamiento paralelizado dentro de la interfaz y esto se puede lograr de muchas formas, la más típica es heredar de `Thread`, `Qthread` o `Qtimer`, pero puede ser un `QGraphicsItem` mientras tengas en tu código un Thread encargado de ver cuando aparece y cuando desaparece.  Si es que tienes eso, entonces vas bien.

Lo que puedo afirmar, es que con `QGraphicsIItems` y derivados si puedes cumplir con todos los requisitos (y sin usar librerías prohibidas), si al final el `QGraphicsIItems` es un simil a `QLabel`, solo que con métodos diferentes para hacer las cosas. Así que no te preocupes.

Saludos :V:
