### ISSUE TITLE
Acceder a path relativo de los archivos 

### ISSUE THREAD

**Issue by Juan379** [IIC2233/syllabus#206]
Hola!
Estoy teniendo problemas al acceder a los paths relativos de los archivos de los cuales necesito sacar la informacion.

Intente con el uso de os.path.relpath(path, inicio) utilizando path como T01/pistas.csv e inicio como T01, sin embargo me dice que este archivo no existe y al hacer os.path.isfile() con este path me tira False.

De la misma forma intente usar os.path.join(T01, pistas.csv) para poder utilizarlo y tambien sin utilizarlo con la carpeta T01 pero tampoco me funciona.

Algun consejo? Gracias!

**Comment by gatochico** [comment]
Hola! 

Todo depende desde donde se ejecute el archivo en realidad! Un ejemplo, tengo las siguiente carpeta `Playground`, con una carpeta llamada `T01`, con el archivo `uwu.py` y `pistas.csv` dentro:
![Screenshot from 2019-09-09 10-13-53](https://user-images.githubusercontent.com/37161120/64533790-9970d680-d2ea-11e9-8290-95045bef7628.png)
Con el siguiente código en el .py:
![image](https://user-images.githubusercontent.com/37161120/64533814-a7bef280-d2ea-11e9-8486-ebc235ac323a.png)
Ahora, veamos lo que imprime el archivo dependiendo desde donde ejecuto dicho archivo. En el primer comando, lo ejecuto estando situado en la carpeta `Playground`, mientras que el segundo lo ejecuto estando situado en la carpeta `T01`:
![image](https://user-images.githubusercontent.com/37161120/64533936-e5bc1680-d2ea-11e9-95e7-ece37f08ad2e.png)

Probablemente te lanza error ya que estás ejecutandolo como en el segundo caso, estando situado dentro de la carpeta `T01`. Esto no está mal, por lo que para que te resulten los comandos, deberías ocupar los paths como en la línea 4 que mostré en la segunda imagen.

Espero haberte ayudado!

**Comment by Juan379** [comment]
Me pasa algo que no entiendo bien.
Tengo la siguiente distribucion de archivos: Tareas/T01, dentro de T01 tengo los dos archivos que estoy tratando: prueba.py y pistas.csv.

Al correr os.path.isfile("pistas.csv") en prueba.py desde Atom, me tira False.
Sin embargo al correr el mismo comando desde el bash estando dentro de la T01 me lo corre correctamente.
Esto me dice que el path relativo esta correcto, sin embargo, como Atom me tira False no puedo tratar estos archivos para la tarea.

**Comment by gatochico** [comment]
Hola! Podrias mandar un pantallazo de la pestaña de atom donde se muestran las carpetas y archivos que tienes abiertas? Algo similar a esto:
![Screenshot from 2019-09-09 10-13-53](https://user-images.githubusercontent.com/37161120/64559787-74498b80-d31d-11e9-8649-7aab3c6b01db.png)
Pero en Atom.
Tu problema podría deberse a que carpeta abriste como raíz para trabajar en atom, ya que si es distinta a T01, ocurre el caso anterior que dí en el ejemplo (donde se abria desde una carpeta que contenía a la carpeta T01).

**Comment by Juan379** [comment]
Esto era! Tenia abierta otra carpeta abierta como root. Gracias!
