### ISSUE TITLE
Problema git push

### ISSUE THREAD

**Issue by Elisapv** [IIC2233/syllabus#206]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ]X Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema
No me funcionaba git push entonces busque el problema en internet y seguí las instrucciones que me recomendaban y ahora no me pide un token, que no se lo que significa. No se si pueden ayudarme a arreglarlo.

**Comment by aaossa** [comment]
Hola @Elisapv , ¿a qué te refieres con que "no me pide un token"? 🤔 Si ya solucionaste los conflictos que tenías pero el comportamiento de tu repositorio no es el esperado, podrías clonar de nuevo tu repositorio. En tal caso, asegúrate de tener tu repo remoto actualizado (que no te falte subir código) y luego utiliza el nuevo clon. Espero que esto te sirva, pero si tienes alguna duda adicional pregunta por acá no más ✨

**Comment by Elisapv** [comment]
Hola, no he podido solucionar el error, hice lo que me recomendaste pero tampoco funciono. No se si es posible en la ayudantía compartir pantalla y que algún ayudante me ayude con el problema? Muchas gracias por tu respuesta.

**Comment by aaossa** [comment]
Hola @Elisapv , ¿podrías colocar el *link* con la página que seguiste para tratar de solucionar el problema? 🤔 ¡Gracias 🙌 !

**Comment by Elisapv** [comment]
Hola, ya lo pude solucionar! Borre las carpetas clonadas como me dijiste y además elimine git de mi computador, descargue de nuevo git y hice todo el proceso de nuevo. Muchas gracias por tu ayuda
