### ISSUE TITLE
Error en funcion gui.set_points

### ISSUE THREAD

**Issue by Polea012** [IIC2233/Syllabus#207]
Al parecer hay un error en el código gui para la función gui.set_points que genera error al invocarla.

En el archivo "__init__.py":
dice:
def set_points(points):
    __game.setPoints(points)

debiera decir??:
def set_points(player_numb, points):
    __game.set_points(player_numb, points)

**Comment by iqacevedo** [comment]
Hola,

Efectivamente existía un error, muchas gracias por notarlo. Acabo de subir el código con el error corregido, que era tal y como tu lo decías.

Saludos !

**Comment by JPSF** [comment]
El error continúa en el archivo init.py.Ahora es:
def set_points(player_numb, points):
__game.se**tP**oints(player_numb, points)

Y debe ser:
def set_points(player_numb, points):
__game.set_points(player_numb, points)

Saludos

**Comment by iqacevedo** [comment]
@JPSF tienes toda la razón , pido disculpas por haberme equivocado, ya está corregido 

Saludos!
