### ISSUE TITLE
problemas con git push

### ISSUE THREAD

**Issue by chechinnnn** [IIC2233/Syllabus#207]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

Hola, al realizar git push para la actividad, me sale el siguiente mensaje:

  ! [rejected]        main -> main (non-fast-forward)
error: falló el empuje de algunas referencias a 'https://github.com/IIC2233/chechinnnn-iic2233-2024-1.git'
ayuda: Updates were rejected because the tip of your current branch is behind
ayuda: its remote counterpart. If you want to integrate the remote changes,
ayuda: use 'git pull' before pushing again.
ayuda: See the 'Note about fast-forwards' in 'git push --help' for details.

Que puedo hacer?

**Comment by JJJGGGG** [comment]
Hola @chechinnnn ! Esto ya fue respondido en #132 

Saludos!
