### ISSUE TITLE
PyQt5 - PyCharm

### ISSUE THREAD

**Issue by jitorcas** [IIC2233/syllabus#207]
Hola!
Al instalar PyQt5 y correrlo en Pychar me lanza este error al crear mi primera ventana:

**2019-05-12 02:03:20.843 Python[2863:126604] isPrefsCreateCacheFromEnabledAndDefaultInputSources - can't find anything from GetInputSourceEnabledPrefs, use defaultASCIIKeyLayoutDict = <CFBasicHash 0x7f9347873f80 [0x7fff844058f0]>{type = mutable dict, count = 3,
entries =>
	0 : <CFString 0x7fff84473eb8 [0x7fff844058f0]>{contents = "InputSourceKind"} = <CFString 0x7fff844b93f8 [0x7fff844058f0]>{contents = "Keyboard Layout"}
	1 : <CFString 0x7fff844a5538 [0x7fff844058f0]>{contents = "KeyboardLayout ID"} = <CFNumber 0x5737 [0x7fff844058f0]>{value = +87, type = kCFNumberSInt64Type}
	9 : <CFString 0x7fff8446ebb8 [0x7fff844058f0]>{contents = "KeyboardLayout Name"} = <CFString 0x7fff844f7418 [0x7fff844058f0]>{contents = "Spanish - ISO"}
}**

He buscado por google cual puede ser la causa, pero no aparece nada concreto. Alguien podría ayudarme? ya que la ventana creada me aparece de todas formas. 

adjunto una captura de pantalla. 
<img width="1374" alt="Captura de pantalla 2019-05-12 a la(s) 02 11 25" src="https://user-images.githubusercontent.com/48298300/57578486-7547da80-745b-11e9-8d71-f1dc51513750.png">

**Comment by iqacevedo** [comment]
Hola @jitorcas 

No hemos encontrado aún una solución a tu error.¿ Lo lograste solucionar tu ? ¿ aún tienes problemas con este mismo error?

**Comment by jitorcas** [comment]
No! Pero estoy ocupando otro editor, gracias!
