### ISSUE TITLE
Mensajes al levantar y manejar excepciones

### ISSUE THREAD

**Issue by namadatzis** [IIC2233/syllabus#207]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Estaba realizando los ejercicios propuestos y me surgió una duda. Cuando levantamos una excepción añadimos un mensaje:

`raise Error("Mensaje")
`

Sin embargo, cuando manejamos el error con` try/except` e imprimimos en pantalla se omite el mensaje que pusimos en raise y sólo aparece el mensaje que hay en except. En base a esto, para qué usamos mensajes en raise si son omitidos y el código funciona sin estos?

**Comment by aaossa** [comment]
Hola @namadatzis , creo que tu duda podría solucionarse con esto: usar `raise` no implica que vas a usar `try/except`. Mi código perfectamente podría ser este:

```python
def division(numerador, denominador):
    if denominador == 0:
        raise ZeroDivisionError("Oye no hagas eso >:(")
    return numerador / denominador


if __name__ == '__main__':
    division(5, 3)
    division(5, 0)
```

En este caso, sí se imprime el mensaje de error que yo definí:

```
Traceback (most recent call last):
  File "...\ejemplo.py", line 9, in <module>
    division(5, 0)
  File "...\ejemplo.py", line 3, in division
    raise ZeroDivisionError("Oye no hagas eso >:(")
ZeroDivisionError: Oye no hagas eso >:(
```

Son dos necesidades diferentes. Si necesitas reportar la excepción con un mensaje personalizado utilizas `raise`, pero si quieres capturar la excepción utilizas `try/except`. Si quieres capturar la excepción pero también necesitas el mensaje... no suena a algo correcto 🤔 (Si necesitas el mensaje porque quieres levantar la excepción, no uses el `try/except`, pero si quieres el mensaje para elegir cuál excepción levantar, tienes que definir bien la excepción y no en el mensaje) Si tienes alguna otra duda pregunta por acá no más 👌 ¡Éxito con tu estudio!
