### ISSUE TITLE
Duda con el bonus de los Menus

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#207]
Hola para el bonus de los menús tengo necesariamente que tener:
-Menú de sesión
-Menú principal
-Menú de compra de vehículos
-Menú de preparación de carrera
-Menú de carrera
-Menú de los Pits
Mi duda es si puedo por ejemplo juntar el menu de preparacion de carrera dentro del menu carrera como metodo o necesariamente ambas tienen que ser clases?

**Comment by DCCollao** [comment]
Hola!
No puedes juntar diferentes menús dentro de una sola clase. En el enunciado se especifica que cada menú y submenú **debe** ser una clase distinta.

Éxito!

**Comment by JuaniAndres** [comment]
ok gracias
