### ISSUE TITLE
terminar programa

### ISSUE THREAD

**Issue by santiago3c** [IIC2233/Syllabus#207]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

Hola, de lo que tengo entendido, sys.exit(app.exec()) lo que hace es que se deja al programa andando de tal forma que siempre este recibiendo eventos, hasta que se cierren todas las ventanas del programa. Entonces cómo yo puedo cerrar el programa si pongo sys.exit(app.exec()) pero no creé una ventana, ya que en ese caso no puedo cerrar ninguna ventana y terminar el programa.
[Describe tu duda de manera detallada, explicando los contenidos en cuestión y ojalá colocando código o un caso de uso de ejemplo]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Hernan4444** [comment]
Hola @santiago3c 

En caso de usar WSL o mac, lo que se puede hacer es CTLT + Z para suspeder el proceso. Esto te dirá un mensaje como
> `[1]  + 8152 terminated  python3 1-interfaces-graficas-ejemplo_1.py`

Luego puedes hacer `kill N` donde N es ese número que corresponde al ID del proceso que suspendiste. `kill 8152`. Con esto, matas totalmente el proceso cuando no hay ventana.

En caso de windows, creo que solo queda abrir el administrador de tareas y ahí eliminar el proceso de python.

Otra opción creo que es cerrar la terminal, si esta se cierra, el programa que se está ejecutando tambien se cierra.

Avísanos si estas opciones logró solucionar el problema, sino para buscar otros medios que no impliquen reiniciear el computador (esa solución siempre apaña, pero no es la idea)

Saludosヾ(＾-＾)ノ

**Comment by santiago3c** [comment]
gracias
