### ISSUE TITLE
Duda dias 

### ISSUE THREAD

**Issue by mmleivad** [IIC2233/Syllabus#207]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Contenido

Hola, me bajó la duda si los días extra son 2 por tarea o son 2 días en total para todo el semestre. Agradecería si me pueden aclarar esto. 
Gracias!

**Comment by Hernan4444** [comment]
Hola @mmleivad 

Cada tarea cuenta con 2 días de entrega atrasada. Lo único es que tienes 2 cupones **en todo el semestre** que puedes ocupar para reducir la penalización por atraso en las tareas.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con el curso! 🦖
Saludosヾ(＾-＾)

**Comment by VittoTassara** [comment]
Hola, me gastaría saber a que hora se abre el formulario para entregas atrasadas, ya que tenia entendido que era al momento de cerrarse el periodo de entrega de la tarea.
Gracias!:)

**Comment by Hernan4444** [comment]
Hola @VittoTassara 

Ya está abierto, lamento la tardanza 🦖 🙇‍♂️

Saludosヾ(＾-＾)
