### ISSUE TITLE
duda sobre encontrar ítem, si es solo excavando o no

### ISSUE THREAD

**Issue by camiloEscorza** [IIC2233/Syllabus#207]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Holaa, mi duda es que en el enunciado aparece Encontrar Ítem: Cada día los excavadores tendrán la probabilidad de encontrar un Ítem. Esto significa que independiente de lo que haga el excavador, si está cavando o si está descansando, puede encontrar un item?. O solo los que hayan excavado pueden encontrar item?

**Comment by PipeXtz** [comment]
Hola @camiloEscorza !

Más temprano en el enunciado se menciona lo siguiente: "Además, mientras los Excavadores cavan, podrás encontrar diferentes Ítems que podrás utilizar al finalizar el día."

Por lo que cuando estén descansando no podrán encontrar ítems, será solo cavando.

Espero haya quedado claro, quedo atento.

**Comment by camiloEscorza** [comment]
Ya perfe gracias
