### ISSUE TITLE
No hice el .gitignore y ya hice un push

### ISSUE THREAD

**Issue by stephenwpugh** [IIC2233/syllabus#207]
Holaa! Cuando se subió la tarea la bajé, pasé a mi repo personal y la commitié solo con los archivos "de base" que habían ahí (menos el enunciado), me entró la duda si todavía estoy a tiempo de hacer una carpeta .gitignore y meter todo ahí antes de hacer un push de nuevo (y borrar los archivos que ya subí antes), o mejor sigo actualizando el github y no hago el .gitignore por esta vez

**Comment by DCCollao** [comment]
Hola @stephenwpugh!

Sí, aún estás a tiempo de subir tu **archivo** `.gitignore`. Ojo con esto, no es una carpeta donde metas los archivos que quieres ignorar. Para esto, debes crear tu archivo `.gitignore` y subirlo, y además debes eliminar los archivos que ya subiste a github y querías ignorar. 

Quedo atento a cualquier duda!

**Comment by stephenwpugh** [comment]
Gracias @DCCollao !! Dime si estoy bien, **(1)**cree un archivo `.gitignore`, **(2)** escribí adentro los nombres de los archivos que hay que saltarse (junto con otros que son temporales para mi código), **(3)** Hice un *push* solo de `main.py` y los módulos que tengo y **(4)** Eliminé `tablero.py` y otros de mi repo.
Si eso esta bien, considero resuelta la *issue*, muchas gracias por la ayuda!!

**Comment by DCCollao** [comment]
Te falta pushear tu `.gitignore`! El resto debería estar todo bien.
