### ISSUE TITLE
Imports cruzados

### ISSUE THREAD

**Issue by enriquerussi** [IIC2233/syllabus#208]
Hola, mi código funciona en base a funciones, y para no sobrepasar las 400 lineas por modulo, lo separe en 2 pero ocurre que las funciones que se encuentran en ambos módulos se llaman entre si, por lo que no me deja importarlas respectivamente.

**Comment by vicentevegaulloa** [comment]
Hola @enriquerussi !

Podrías separar tu código de manera las líneas donde defines esas funciones queden juntas. O esas funciones toman en total más de 400 lineas?

**Comment by enriquerussi** [comment]
Las funciones toman más de 400 lineas :/

**Comment by enriquerussi** [comment]
> Hola @enriquerussi !
> 
> Podrías separar tu código de manera que las líneas donde defines esas funciones queden juntas. O esas funciones toman en total más de 400 lineas?

Las funciones toman más de 400 lineas :/

**Comment by vicentevegaulloa** [comment]
Lo que tienes es una **dependencia circular**, donde dos funciones dependen una de la otra. Esto es considerado una mala práctica, ya que es muy probable que te genere problemas en el futuro. Para poder separar tu código correctamente y no sufrir por esto después te recomiendo que subdividas cada función en otras más pequeñas y que le des una vuelta a tu modelación. Se que esto es una lata y se siente como un gran retroceso, pero es mejor que te ocurra ahora que más adelante con funciones o clases más grandes y un avance mayor en tu tarea.

**Comment by Drpinto1** [comment]
¡Hola @enriquerussi!

Complementando un poco la respuesta de @vicentevegaulloa, la idea de las funciones sean relativamente cortas y puedan llamarse varias veces a lo largo del código.

Por ejemplo, si estás programando un juego de cartas como el UNO, y quieres modelar el funcionamiento de un turno del juego, en lugar de tener una función `turno()` que se encargue de todo el proceso, puedes tener una función `recoger_carta()`, una función `jugar_carta()` y otra función `aplicar_efecto()`. Estas funciones estarán encargadas de tomar una carta del mazo y agregarla a la mano del jugador, eliminar una carta de la mano del jugador y agregarla a la pila de descarte y aplicar el efecto de la carta si es que es una carta especial, respectivamente.

De esta manera, la función `turno()` que diseñes deberá encargarse solamente de llamar a estas 3 funciones en el orden que corresponda, verificar que el jugador tenga una carta jugable en mano y otras cosas más simples y además podrás reutilizar la función `recoger_carta()` para usarse cuando un jugador utilice una carta +2 o +4.

Cuéntame si se entiende mi ejemplo (que asume que has jugado, o al menos conoces las reglas del UNO :open_mouth:)

¡Saludos!
