### ISSUE TITLE
Acción de los gobiernos - implementación y duración (Tarea 2)

### ISSUE THREAD

**Issue by egbusch** [IIC2233/Syllabus#208]
Hola, la pregunta es la siguiente:

Cada gobierno decide sus propuestas y se ponen en la cola general del mundo, una vez al día se revisan esas propuestas y solo se ejecutan las 3 de mayor prioridad. Pero esas 3 propuestas solo se llevan a cabo en los países donde se originaron, o todo el mundo (creo que solo en el país de origen)? de ser llevadas a cabo, su duración es de 1 día o para siempre? (se reparten mascarillas por siempre o dejan de repartirse en algún momento, lo mismo para las fronteras) 

En un par de posts anteriores se mencionó esta pregunta, pero no encontré la respuesta.

**Comment by arturodelreal** [comment]
Hola, las acciones duran para siempre, en el caso de las fronteras y aeropuertos se pueden volver a abrir, pero esto solo ocurre si el gobierno toma esa decisión.

**Comment by egbusch** [comment]
gracias

**Comment by rjdelrio** [comment]
hola tengo una pregunta sobre esto mismo que pasa si un país propone dos propuestas las ponga en la cola igual aun que sean del mismo país. 
y otra cosa mas si un país tiene por ejemplo 1 infectado y por lo tanto el gobierno no va a elegir ninguna acción puedo asumir que el valor de ninguna acción es 0.

**Comment by rpalmaotero** [comment]
@rjdelrio seguir en #226.

**Comment by rfenzo** [comment]
una pregunta, el 0.3 del uso de mascarillas multiplica al calculo de nuevos infectados dia a dia, o multiplica al total de infectados del pais?
