### ISSUE TITLE
Class Error

### ISSUE THREAD

**Issue by barbaracalderonr** [IIC2233/syllabus#208]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola!, tengo dudas en los ejercicios 3.1 y 3.3, me confunde cuando piden que lleve como una "cuenta" de los errores dentro de la clase, no entiendo bien como podría implementar esto de forma que no se reinicie la cuenta cada vez que se instancia la clase.

**Comment by tqmbanados** [comment]
Hola @barbaracalderonr! Recuerda que en python puedes definir "atributos de clase", es decir, atributos que pertenecen a la clase en sí y no a una instancia particular de ella. Al modificar uno de estos atributos, se modifica para todas las instancias presentes y futuras. Esto se realiza definiendo el atributo afuera del ```__init__()``` como en el siguiente ejemplo:
```python
def Clase:
    atributo_de_clase = 0
    def __init__():
        atributo_de_instancia = "string" 
```
Espero que esto te de alguna idea de como resolver los ejercicios!
Cuéntame cómo te va :)

**Comment by barbaracalderonr** [comment]
Muchas gracias!!, aun no comprendo muy bien como hacer que cambien los valores de los atributos de clases, por ejemplo en el caso de el ejercicio 3.1, el atributo estudiantes_copiones, debe agregar los alumnos copiones, pero no he podido hacerlo dentro de la clase, existe algún tipo de método especial para hacerlo??

**Comment by tqmbanados** [comment]
para cambiar estos atributos de clase tienes que hacerlo muy similar a si fueras a cambiar un atributo de la instancia, usando ```self.atributo```. También puedes usar el nombre de la clase: 
```python
class Clase:
    atributo_de_clase = 0
    def __init__(self):
        self.atributo_de_instancia = "string"

instancia = Clase()
instancia.atributo_de_clase += 1
Clase.atributo_de_clase += 1
```
Aquí, si imprimimos ```Clase.atributo_de_clase```, dará como resultado 2. Te invito a probarlo en tu IDE!
Esto es muy útil si por ejemplo queremos asignarles un *id* a cada instancia:
```python
class Clase:
    class_id = 0
    def __init__(self):
        self.id_ = Clase.class_id
        Clase.class_id += 1

inst1 = Clase()
inst2 = Clase()
inst3 = Clase()
```
Si printeamos el atributo id_ de cada una de esas instancias, tendrán un número distinto.

**Comment by barbaracalderonr** [comment]
Yaa bacan muchas gracias!
