### ISSUE TITLE
modificación de items en la arena

### ISSUE THREAD

**Issue by camiloEscorza** [IIC2233/Syllabus#208]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, quería preguntar si en vez de hacer una lista en la clase arena con todos los items, puedo hacer dos atributos de arena, una para los tesoros y la otra para los consumibles? gracias

**Comment by PipeXtz** [comment]
Hola @camiloEscorza! 

Efectivamente puedes añadir nuevos atributos, cómo dice el enunciado, no obstante, debes implementar los mínimos que se piden en el enunciado, por lo que el atributo "Ítems" de la clase Arena debe ir de igual manera, ya sea si agregas otros atributos o no.

"Debes incluir como mínimo las características nombradas a continuación, pero siéntete libre de añadir nuevos atributos
y métodos si lo estimas necesario"

Por lo que sería un poco redundante añadir estos atributos si ya existe el de ítems.

Espero haya quedado claro, quedo atento.

**Comment by camiloEscorza** [comment]
Ya buena, otra pregunta. Como sé con cuantos items empieza cada arena? es aleatorio, se me deja a mi criterio o va en algún lado en parametros.py? gracias

**Comment by PipeXtz** [comment]
Hola, muchas issues ya hablaron de esto, te invito a las siguientes: #178  y #179.
