### ISSUE TITLE
Cambio de lineas en la Entrega

### ISSUE THREAD

**Issue by francisca0308** [IIC2233/syllabus#208]
Hola!
Según lo declarado en la guía de descuentos, se puede hacer un cambio de líneas en la entrega sujeta a un descuento entre 1 y 5 décimas.
Cómo accedo a esa opción?

**Comment by gatochico** [comment]
Hola! Para realizar un cambio de líneas, escribe en alguna sección de tu README de forma **clara y precisa** qué lineas deseas cambiar (p. ej "En la línea 78 de main.py agregar lo siguiente: ....") 📖
