### ISSUE TITLE
PyQt6 instalado correctamente pero existen errores

### ISSUE THREAD

**Issue by matiaraos** [IIC2233/Syllabus#208]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

Hola la verdad cuando intento ejecutar un archivo importando PyQt me sale este error:

![image](https://github.com/IIC2233/Syllabus/assets/141788398/1b302f38-d0e8-400b-b9b3-5b4e2d6e7990)

Y no me acuerdo ver a nadie con ese error en las issues.

**Comment by matiaraos** [comment]
### Actualización
Al final investigando mucho en internet me encontre este link en un foro:

https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

Donde básicamente nos pedían hacer en la consola de windows una actualización del WSL, así que escribí en el cmd:

```wsl --update```

y se me solucionó, la verdad ni idea porque ya que se supone que la actualización que permitía las GUIS en WSL salió antes que lo descargaramos, pero bueno.

**Comment by domingolira** [comment]
Hola!
Tuve exactamente el mismo problema, con un output muy similar por parte de la terminal de Ubuntu.
Al tratar de actualizarlo por Windows Powershell me decía que WSL ya se encontraba en su versión más actualizada, así que lo actualice desde el mismo terminal de Ubuntu, pero al intentar ejecutar un archivo, el output sigue siendo el mismo.
![image](https://github.com/IIC2233/Syllabus/assets/141957431/2aea82f9-2df9-489b-8e82-58811afa4918)

**Comment by gatochico** [comment]
Hola @domingolira !

Trata con los dos siguientes comandos!
`sudo apt install qtwayland5`
`sudo apt install qt6-wayland`

Y cierras tu terminal y corres el código. En caso de no funcionar, qué sistema operativo de windows tienes?

**Comment by domingolira** [comment]
Funcionó!
Muchísimas gracias!

**Comment by Washaaaan** [comment]
> Hola @domingolira !
> 
> Trata con los dos siguientes comandos! `sudo apt install qtwayland5` `sudo apt install qt6-wayland`
> 
> Y cierras tu terminal y corres el código. En caso de no funcionar, qué sistema operativo de windows tienes?

Buenas, justamente me pasaban esos mismos errores y al intentar seguir lo de `sudo apt install qtwayland5` y `sudo apt install qt6-wayland` me aparece esto:


![Captura de pantalla 2023-10-03 211837](https://github.com/IIC2233/Syllabus/assets/130397986/e059a941-41a5-4fb0-9245-d1aa135a02e8)
