### ISSUE TITLE
Como instalo el Pycharm de la U ?

### ISSUE THREAD

**Issue by AngelMatias** [IIC2233/Syllabus#208]
Eso. Estoy ocupando la version de prueba y me dura hasta 4 dias mas :(

**Comment by egromero** [comment]
Hola, puedes poner pycharm for students en google y van a salir varios links

Me cuentas si no cachas algo
Saludos

**Comment by Arcoirisky** [comment]
https://account.jetbrains.com/login

Ahí entras, te creas tu cuenta con el correo UC y luego de que te acepten y confirmes correo y todo eso te metes en tu cuenta y te saldrá como que tienes 1 licencia "JetBrains Product Pack for Students" Entre todas las opciones que te dan aparecerá Pycharm y aplicas el download now. De ahí eliges si quieres el professional o el community. Toda la info aparece ahí :D Suerte!

**Comment by AngelMatias** [comment]
y cual es la diferencia entre el professional y el community ??

y.. este es el community ??
<img width="131" alt="captura de pantalla 2017-09-02 a la s 18 58 18" src="https://user-images.githubusercontent.com/30705123/29999057-e60f846a-9010-11e7-8619-a03c055bf218.png">

**Comment by Arcoirisky** [comment]
La verdad es que la diferencia no la sé. Si no me equivoco yo instalé el community porque el professional me dio miedo :sweat_smile: pero intenta con cualquiera, total, puedes descargar cualquiera de los dos :see_no_evil: Y el mio dice Jetbrain Pycharm O: quizás porque lo descargué de ahí!

**Comment by iqacevedo** [comment]
Hola,

También aparecía en la wiki del curso, si quieres probar alguna otra Interfaz de desarollo, te recomiendo leerla [acá](https://github.com/IIC2233/Syllabus/wiki/Interfaces-de-Desarrollo).

Saludos !

**Comment by AngelMatias** [comment]
pero se supone que el community es gratis y el professional es de pago ?

**Comment by iqacevedo** [comment]
Así es, el professional tiene más características que el community, pero es de pago. Si te registras con el correo de la universidad puedes utilizarlo de manera gratuita, ya que te darán una licencia que dura un 1 año, cuando esa licencia este por caducar, puedes volver a expandirla gratis por otro año (y así cada año seguir expandiendola).

**Comment by AngelMatias** [comment]
Perfecto entiendo ! gracias. Pueden cerrar este post.
