### ISSUE TITLE
parametros.py

### ISSUE THREAD

**Issue by pwillmer** [IIC2233/syllabus#208]
Hola!, mi consulta es: ¿debemos asumir que los parámetros relacionados a cálculos vendrán en int()  o deben ser a aprueba de errores?

**Comment by KnowYourselves** [comment]
Hola @pwillmer!

Puedes asumir que los parámetros verán en el formato adecuado. Es decir, efectivamente los parámetros numéricos serán `int`.

Éxito!

**Comment by pwillmer** [comment]
Gracias!
