### ISSUE TITLE
Duda sprite personaje

### ISSUE THREAD

**Issue by Dnpoblete** [IIC2233/syllabus#208]
Hola, estaba viendo las sprites de personajes y no hay ninguna en la que el personaje femenino y masculino mire a la derecha, eso esta bien que este así y hay algo que no me di cuenta? o de verdad hacen falta esas sprite?

Gracias y quedo atenta a la respuesta :)

**Comment by lily416** [comment]
Hola 😄 

Es cierto que a las sprites del personaje les falta el movimiento hacia la derecha (y a los enemigos también).
Como tanto el personaje como los enemigos deben tener su animación de caminata hacia la derecha tienes dos opciones:
1. **Dar vuelta las imágenes con un editor** 
   - Las imágenes giradas deberás guardarlas en una carpeta distinta a `sprites/` para asegurarte que se suban a tu repositorio y que no sean ignoradas por el `.gitignore`.
   - Evita usar paint ya que al girar las imágenes ya que les quitará el fondo transparente 😢

1. **Girar las imágenes con PyQt**
   - Te recomiendo más está opción, ya que te ahorras el tener que subir las imágenes a una carpeta diferente y el tener que girar las animaciones que uses para la derecha 🤔 
      > (2 bandos x 2 tipos de enemigos + 1 personaje) x 3 animaciones a girar = por lo menos 15 imágenes a girar 🙀 

   - En el caso de que uses `QPixmap` para abrir las imágenes te dejo el siguiente [link](https://stackoverflow.com/questions/5960994/reflect-the-qpixmap) :wink:
      En la respuesta de ingenium a Bart te explica como usar `transformed` para girar una imagen.
      Para importar `QTransform` debes importarlo desde QtGui


Ánimo y éxito en la tarea 😺🐧

**Comment by Dnpoblete** [comment]
Hola, durante el día he estado tratando con el código del link que me mandaste, pero me tira error todo el rato, me podrías explicar como usarlo o en que parte tendría que ponerse en relación a la imagen porfavor 😢

**Comment by lily416** [comment]
La idea es la siguiente:
```python
# Importas las imágenes y el "transformador"
from PyQt5.QtGui import (QPixmap, QTransform) 

# En el interior de tu ventana
    # Cargas la imagen, es decir, la instancias un label y setteas su geometría.
    self.label1 = QLabel('', self)
    self.label1.setGeometry(ancho, alto)

    # Cargas la imagen
    imagen = QPixmap(os.path.normpath(path_imagen))
    imagen = imagen.scaled(ancho_imagen, alto_imagen)

    # Transformas la imagen
    imagen = imagen.transformed(QTransform().scale(-1, 1))

    # Y la asignas al label
    self.label1.setPixmap(imagen)
```
Haciendo lo anterior, puedes cargar las imágenes del movimiento de la izquierda como si fuera el movimiento de la derecha 😃 

Ojala ahora quede claro ☺️ 

PD: Cualquier duda que tengas con respecto a las funcionalidades disponibles en PyQt5 o cómo y qué hacen te recomiendo leer la documentación de [Qt](https://doc.qt.io/qt-5/index.html), ya que en ella se basa PyQt5.

**Comment by Dnpoblete** [comment]
Muchisimas gracias, ya me funciona!!!! ☺️

**Comment by mimunoz11** [comment]
no es más fácil subir los sprites?
saludos

**Comment by lily416** [comment]
@mimunoz11 Es decisión de cada uno que opción le parece más fácil, por eso les damos dos formas de hacerlo.

Saludos 👋🐈🐧

**Comment by lily416** [comment]
@mimunoz11 Recuerda que si giras las _sprites_ con un editor de imágenes debes subirlas a tu repositorio, pero **no debes subir las otras _sprites_ que te damos**, es decir, únicamente puedes subir las sprites de movimiento hacía la derecha de los enemigos y el personaje.
