### ISSUE TITLE
Editar parametros

### ISSUE THREAD

**Issue by lothardp** [IIC2233/syllabus#209]
Hola. 
Podemos editar el tipo de estructuras en el archivo parametros.py? Especificamente queria convertir los 4 diccionarios de AUTOMOVIL, MOTOCICLETA, TRONCOMOVIL y BICICLETA, en un solo diccionario VEHICULOS de 4 entradas, donde cada una son los diccionarios anteriores. Esto me facilitaría el acceso de la información. 
En el fondo, al probar la tarea lo hacen con nuestro archivo parametros.py y editan solo sus valores, o usan uno estandar de ustedes?
Gracias!

**Comment by KnowYourselves** [comment]
Hola @lothardp!

Si, puedes hacer lo que describes, ya que nosotros probaremos tu programa con **tu archivo de parametros, por lo cual debes asegurarte de subir este a tu repositorio**. 

Éxito!
