### ISSUE TITLE
Error de instalacion "ImportError: libGL.so.1: cannot open shared object file: No such file or directory" PyQt6

### ISSUE THREAD

**Issue by anticarasosman** [IIC2233/Syllabus#209]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

[Hola, estaba intentando hacer los problemas propuestos de la semana 4, tengo PyQt6 instalado pero me sale el siguiente error:

![imagen_2023-09-08_221635021](https://github.com/IIC2233/Syllabus/assets/94928628/334a4695-bf68-4450-add9-ec155f51dfbf)

Ya intente con sudo "apt-get update", pero eso no cambio nada.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Hernan4444** [comment]
Hola @anticarasosman 

Para confirmar, lo expuesto en la issue

* #7 

Ya fue intentado? Sino para que pruebes primero con eso y ahí nos cuentas si te aparece el mismo error u otrro.

Quedamos atentos!

**Comment by anticarasosman** [comment]
> Hola @anticarasosman
> 
> Para confirmar, lo expuesto en la issue
> 
> * [Error: Problema con PyQt6 #7](https://github.com/IIC2233/Syllabus/issues/7)
> 
> Ya fue intentado? Sino para que pruebes primero con eso y ahí nos cuentas si te aparece el mismo error u otrro.
> 
> Quedamos atentos!

Lo intente hacer ahora pero me sale lo siguiente:

![imagen_2023-09-10_144611154](https://github.com/IIC2233/Syllabus/assets/94928628/7a30416c-94b9-4a7b-b30a-77174f0afb59)

Intente desinstalar PyQt6 como menciona la Issue 7 pero me dice que no esta instalado, pero cuando lo intento instalar de nuevo me dice que ya lo esta.

**Comment by Hernan4444** [comment]
Hola @anticarasosman 

En tu caso, el tema que diga que no está instalado es porque hiciste `sudo python3.10 -m pip uninstall PyQt6` pero para tu caso es `python3` (sin el .10, ese .10 se lo dije en dicha issue porque el alumno en particular usaba python3.10 en sus comandos).

Por otro lado, luego de intentar esto, si intentas ejecutar un archivo python con pyqt6, ¿te sale el mismo error?

Quedamos atentos!

**Comment by Hernan4444** [comment]
Ya, intenta con

1. Ejecutar este comando `sudo apt install libqt6multimedia6 libpulse0 python3-pyqt5 libxcb-cursor-dev`.
2. Cerrar WSL y volver a abrirlo.
3. Luego, intentar desinstalar, pero sin usar sudo `python3 -m pip uninstall pyqt6`.
4. Intentar instalar nuevamente, `python3 -m pip install pyqt6`.
5. Ejecutar un archivo.

Y para tener toda la información posible, desde el paso 2 (despues de abrir WSL). Porfa copia todo lo que ocurra en consola y lo pegas aquí. Aunque se vea feo, así podemos tener todo el _output_ de los comandos e invesgar más al respecto. No subas foto por favor, solo copia el texto y lo pegas, luego nosotros le pondremos formato bonito para poder leer todo.

¡Quedamos atentos!

**Comment by anticarasosman** [comment]
> Ya, intenta con
> 
> 1. Ejecutar este comando `sudo apt install libqt6multimedia6 libpulse0 python3-pyqt5 libxcb-cursor-dev`.
> 2. Cerrar WSL y volver a abrirlo.
> 3. Luego, intentar desinstalar, pero sin usar sudo `python3 -m pip uninstall pyqt6`.
> 4. Intentar instalar nuevamente, `python3 -m pip install pyqt6`.
> 5. Ejecutar un archivo.
> 
> Y para tener toda la información posible, desde el paso 2 (despues de abrir WSL). Porfa copia todo lo que ocurra en consola y lo pegas aquí. Aunque se vea feo, así podemos tener todo el _output_ de los comandos e invesgar más al respecto. No subas foto por favor, solo copia el texto y lo pegas, luego nosotros le pondremos formato bonito para poder leer todo.
> 
> ¡Quedamos atentos!

Perdona pero ¿Cómo puedo desinstalarlo sin el comando de pip uninstall? Intente buscarlo pero solo encontré instrucciones para instalarlo.

**Comment by anticarasosman** [comment]
Siiii eso era, muchas gracias. Ahora funciona perfecto.
