### ISSUE TITLE
cambio en parametros segun tipo de arena

### ISSUE THREAD

**Issue by cataguzmanw** [IIC2233/Syllabus#209]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, tengo una pregunta con respecto a los parámetros que cambian con los distintos tipos de arena, por ejemplo, en arena magnética los valores de humedad y dureza cambian, si después la arena cambia a normal, los valores de humedad y dureza quedan los iniciales o los finales? Tengo la misma duda con las probabilidades en la arena mojada, cuando deja de ser mojada, vuelven a los valores que se tenían en los parámetros originales o quedan para siempre con los indicados en arena mojada?

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Rotopikus** [comment]
Hola!!!

Estos valores siempre deben ser los correspondientes a la arena donde se está desarrollando el torneo.

Espero haber aclarado tu duda. Éxito!!
