### ISSUE TITLE
Clase Caballero y duda sobre activar poderes

### ISSUE THREAD

**Issue by 999luu** [IIC2233/Syllabus#209]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

![image](https://github.com/IIC2233/Syllabus/assets/141879475/eeccba18-0565-4aa0-820e-803b40d67258)
Cuando se habla de que el caballero tenga una probabilidad de sorprender (...) y luego se menciona que, "Si el Caballero activa su poder (...)". Cuando se habla de que el caballero activó su poder, ¿se refiere a que ocurrió lo de sorprender al rival, luego atacar con ATQ_CAB % de su ataque, o se refiere a que cuando activa su poder reduce la vida del oponente en la fórmula expuesta, o las dos cosas ocurren cuando activa su poder? No entiendo a raíz de que la clase Mago tiene una probabilidad de activar su poder y que ocurran sus propiedades de atacar, y de la misma forma que la clase Caballero, cuando no lo activan atacan como Guerrero. muchas gracias :'v

**Comment by wintermelyn** [comment]
Hola @999luu! ✨

Primero que nada te recomiendo muchísimo leer toda esta issue pues trata temas similares de la activación de poderes: #171 

La respuesta es que ocurren ambas cosas, pero igualmente intentaré explicártelo con otras palabras:

Cuando un Caballero ataca tiene PROB_CAB% de activar su poder:

- **Si se activa su poder:**
     
   - Reduce el poder de su enemigo en RED_CAB%
   - Ataca con la formula de daño de caballero
![image](https://github.com/IIC2233/Syllabus/assets/111166713/c653ca46-4906-488c-a6c8-15d4bbc58343)
   - La resistencia del caballero disminuye en CANSANCIO%
   
- **Si no se activa su poder:**

   - Su daño se calcula como el de un guerrero
![image](https://github.com/IIC2233/Syllabus/assets/111166713/c6c9a35b-d056-4fb6-a28e-16373787a696)
   - La resistencia del caballero disminuye en CANSANCIO%

**Comment by asapsanchez** [comment]
Hola, tengo una duda respecto a esto. Cuando se habla de que el caballero tiene una probabilidad "prob_cab" de activar su poder, esto significa que cuando ataque a mis oponentes, de manera aleatoria se elegirá si se activa o no? o bien, debo especificar que quiero atacar con el poder de cada clase. Ojalá se entienda.

**Comment by wintermelyn** [comment]
Hola @asapsanchez!

Si entiendo bn tu duda, la respuesta es lo primero que dices. Es decir cada vez que tu caballero ataque existe una probabilidad aleatoria PROB_CAB de que active su poder (no dependiendo de alguna decision del jugador), puedes apoyarte de la librería `random` para esto.

Si no entendí bn tu pregunta 😔 me comentas o si entendí bn reacciona a este msj.

**Comment by cgonzalezw** [comment]
Hola! Para esto mismo, no entiendo el parámetro ATQ_CAB%. En el enunciado dice que se reducirá el poder del enemigo en un RED_CAB%, para luego atacar con un ATQ_CAB% su ataque. Esto se refiere a que cuando se ocupa el ataque en la formula puesta después solo se ocupa un porcentaje del ataque del caballero para hacer daño al oponente?

**Comment by wintermelyn** [comment]
Hola @cgonzalezw!

> Esto se refiere a que cuando se ocupa el ataque en la formula puesta después solo se ocupa un porcentaje del ataque del caballero para hacer daño al oponente?

Si te das cuenta en la formula ya estas ocupando un porcentaje del ataque del caballero para hacer daño al oponente:
![322921601-c653ca46-4906-488c-a6c8-15d4bbc58343](https://github.com/IIC2233/Syllabus/assets/111166713/bf1b673a-7e21-4775-8d0e-d3ed44cb864d)
El valor de ATQ_CAB puede ser el que estimen conveniente pero para ilustrarlo tomemos que ATC_CAB% = 110. Esto Significaria que la formula quedaria:
![ej1](https://github.com/IIC2233/Syllabus/assets/111166713/f95cca67-9d11-4a42-a3c9-cbc1df081a44)
![ej2](https://github.com/IIC2233/Syllabus/assets/111166713/35665ad1-6542-45f4-816f-145fc27451c7)
Lo cual es equivalente a decir que usamos un 110% de nuestro ataque o un 10% extra de ataque.

Aprovecho de recomendarte como extra sobre la parte del enunciado: "se reducirá el poder del enemigo en un RED_CAB%" la siguiente issue: #180

**tldr (aunque leanla igual no es tan larga 😭):** Poderes como la reducción de poder ocurren sólo durante el ataque, es decir, antes de pegarse con el enemigo deberían aplicarse los cambios de atributos.
