### ISSUE TITLE
[Duda con print]

### ISSUE THREAD

**Issue by Okhan97** [IIC2233/Syllabus#209]
Hola, quiero hacer que los mensajes de mi juego se printeen de a poco (es decir caracter por caracter), para esto intenté usar:
a="hola como estas"
for i in a:
    print(i,end="")
    time.sleep(.5)

Sin embargo no ocurrio como esperaba, lo que hacia era esperar .5*(numero de caracteres) y luego printear todo el mensaje de una, ¿alguien me puede explicar por que pasa esto? ¿como puedo lograr lo que quiero?

**Comment by iqacevedo** [comment]
Hola!
Lo que sucede es que python es output buffering por defecto. No sé cómo explicarlo en palabras simples, pero lo que sucede es que se retienen los outputs antes de mostrarse en pantalla, acá encontré explicaciones más en detalle: 
 
-http://stackoverflow.com/a/10019605
-https://www.quora.com/What-is-output-buffering-in-Python

Para tu problema puedes probar remplazar `print (i, end="")` por `print(i, end="", flush=True)`, lo que forzará a `print` para que no retenga nada.

Saludos!

**Comment by Okhan97** [comment]
Muuuuchas gracias :D
