### ISSUE TITLE
Duda ej. 2.3 propuesto semana 2

### ISSUE THREAD

**Issue by Gjescalante** [IIC2233/syllabus#209]
Hola! tengo dudas con el funcionamiento de las properties en este ejemplo, no entiendo como hacer que verifique los atributos de la clase Usuario al momento de entregarle argumentos, y tampoco me quedo claro el uso de los atributos "self.__ = None" , cómo se usan para verificar? este fue mi intento de algo xD Gracias por su tiempo. 
![image](https://user-images.githubusercontent.com/48481711/77464191-91d7d180-6de5-11ea-9567-6d2e14c0b093.png)
![image](https://user-images.githubusercontent.com/48481711/77464260-ab791900-6de5-11ea-8a4f-b408d5e01d2b.png)

**Comment by KnowYourselves** [comment]
Hola @Gjescalante!

Para resolver tu duda, te presentaré otro problema más simple (para no dar la solución 👀) Supongamos que tenemos la siguiente clase:

```python3
class Circulo:
    def __init__(self, radio):
        self.radio = radio
        self.area = self.radio ** 2 * 3.14
```

Esta clase tiene dos problemas:
1. Si cambiamos el radio, también tenemos que cambiar el área (esta no se recalcula automáticamente).
2. Podemos modificar el radio arbitrariamente, podríamos cambiarlo por un _string_.

Solucionemoslo:

### Problema del Área

Para esto podemos transformar al área en un property que se recalcule cada vez:

```python3
class Circulo:
    def __init__(self, radio):
        self.radio = radio

    @property
    def area(self):
        return self.radio ** 2 * 3.14
```

Lo que hace el `@property` es definir un `getter` para `area`, es decir, cada vez que accedamos al tributo área, pasaremos a esa función y obtendremos el valor que nos retorne. Como en esta función calculamos el área cada vez, siempre obtendremos el valor actualizado sin importar cuanto cambiemos el valor de radio. (En tu código te faltan los return, obtendrías None al intentar acceder a esos valores) 

### Problema del Radio

Para esto podemos definir un `setter` para el radio que no nos permita actualizar el valor a menos de que este sea de la clase `int`. Para esto podemos utilizar la función `isinstance`. Para definir un _setter_ tenemos sin embargo que definir un _getter_. En primera instancia podríamos hacer algo como esto:

```python3
class Circulo:
    def __init__(self, radio):
        self.radio = radio

    @property
    def area(self):
        return self.radio ** 2 * 3.14

    @property
    def radio(self):
        return self.radio

    @radio.setter
    def radio(self, valor):
        if isinstance(valor, int):
            self.radio = valor
```

Sin embargo este programa nos va a dar un **error de recursión**. ¿Por qué?, Pues veamos, en el _init_ entramos a `self.radio = radio`, pero `self.radio` es una _property_ asi que nos vamos a su definición, donde retornamos `self.radio` que es una _property_, asi que nos vamos a su definición... 💀 .

Es por esto que nace la necesidad de crear un valor intero donde guardar el valor de radio para evitar el ciclo infinito. Para esto es que cambiamos las instancias de `self.radio`,  `self.__radio` (se utilizan dos guiones bajos por convención para denotar que es una variable privada).

```python3
class Circulo:
    def __init__(self, radio):
        self.__radio = radio

    @property
    def area(self):
        return self.radio ** 2 * 3.14

    @property
    def radio(self):
        return self.__radio

    @radio.setter
    def radio(self, valor):
        if isinstance(valor, int):
            self.__radio = valor
```
Sin embargo aqui hay otro problema, en el _init_ estamos modificando el valor privado de radio directamente, por lo cual **no va a entrar al setter**. Es por eso que dejamos `self.__radio` definido como `None` e igualamos el valor a `self.radio` (como en el código de Usuario) porque así pasamos los valores que nos pasaron por nuestro filtro en el setter:

```python3
class Circulo:
    def __init__(self, radio):
        self.__radio = None
        self.radio = radio

    @property
    def area(self):
        return self.radio ** 2 * 3.14

    @property
    def radio(self):
        return self.__radio

    @radio.setter
    def radio(self, valor):
        if isinstance(valor, int):
            self.__radio = valor
```

Finalmente, ¿Como funciona exactamente el `setter`?. Lo que hace un `setter` es **interceptar el operador `=`**. Cada vez que utilicemos el operador `=`, accederemos al setter y su argumento será **todo lo que está a la derecha del operador**. Por ejemplo:

```python3
# Sea circulo un objeto de la clase Circulo

# Aqui entramos al setter con valor = 5
circulo.radio = 10

# Aqui entramos al setter con valor = "hola" 
# (no se va a modificar porque no pasa nuestro filtro)
circulo.radio = "hola"

# Aqui entramos al setter con valor = self.radio + 5
# Al hacer self.raido entramos al getter y obtenemos 15,
# por lo cual valor = 15
circulo. radio = 15
```

### Otros Problema

Actualmente esta modelación tiene dos problemas:

1. Permitimos que se cambie el área.
2. Calculamos el área demasiadas veces.

Como propuesta a pensar, de que forma podrías utilizar _properties_ para solucionar esos dos problemas?

Espero haber aclarado tus dudas!
