### ISSUE TITLE
Ubicación ejercicios propuestos semana 2

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#209]
Hola, donde se encuentran los ejercicios propuestos de la semana 2?

**Comment by tocococa** [comment]
Hola @En-clases ! Los ejercicios propuestos están en un _notebook_, junto a los contenidos de la semana, en el repositorio con el contenido del ramo: [acá](https://github.com/IIC2233/contenidos/tree/master/semana-02).

**Comment by En-clases** [comment]
no lo había visto :c, gracias
