### ISSUE TITLE
Hackerman

### ISSUE THREAD

**Issue by JorgeBdelaT** [IIC2233/Syllabus#209]
Hola, estoy viendo de crear mi propio diccionario y buscando en internet encontre los siguiente:

`class Diccionario(object):

    def __init__(self, init=None):
        if init is not None:
            self.__dict__.update(init)`

Mi duda es si está permitido utilizar `__dict__` Saludos!

**Comment by Hernan4444** [comment]
@JorgeBdelaT no se puede utilizar `__dict__` a no ser que lo implementes tu, en otro caso estás recurriendo a un diccionario que posee la clase y eso es utilizar una `built-in` de Python.

Saludos ✌️
