### ISSUE TITLE
Duda ejercicio propuesto 2.3 - semana 4

### ISSUE THREAD

**Issue by Piolawa** [IIC2233/syllabus#209]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola! No entiendo que colocar dentro del _try_ en el método  __getitem__ , probé con self[llave] pero después caché que esto se realiza implícitamente fuera de la clase.
Y tampoco tengo muy claro que atributos  y parte de __getitem__ de la clase **dict** está utilizando la clase **MiDefaultDict**

Otra duda, cuando hice self[llave] se me cayó jupyter, salia un error diciendo que el kernel murió y que se reiniciaría automaticamente, ¿por qué sucedió eso?

**Comment by ignacio-urrutia** [comment]
Hola @Piolawa la idea de usar self[llave] está muy bien, el único problema es que haciéndolo tal cual como dices estarás llamando al mismo método que estás definiendo y se creará un loop (Por eso probalemente murió el kernel , minuto de silencio por el kernel).  Una posible solución, es aprovechar la herencia y llamar a la función del padre, y si esta te levanata un error, lo capturas y lo resuelves como se pide. 
Con respecto a tu otra pregunta, te sugiero revisar la parte de overriding en herencias, pero en esencia, lo que estás haciendo al escribir el método `__getitem__` en `MiDefaultDict` es escribir de nuevo ese método, si quieres llamar al método tal como está implementado en un diccionario normal (dict) debes llamar a la función `__getitem__` de la clase dict (o la clase padre). Hint: usar super().
Espero haber solucionado tu duda, cualquier cosa estaré atento a tu respuesta.
