### ISSUE TITLE
Programa se cae

### ISSUE THREAD

**Issue by cristhanos** [IIC2233/Syllabus#209]
En mi programa por ahora se mueven los aliens y puedo mover la mira, pero de a poco se van quedadando pegados y el programa se cae. Pasa como el 90% de las veces. No sé qué pasa.

**Comment by JJJGGGG** [comment]
Hola @cristhanos ! Lo primero que se me ocurre es que se te acabe la RAM del computador. Para saber si realmente es eso, tienes que responderte algunas preguntas:
* Guardas los aliens en una lista?
* Eliminas un alien de esa lista cuando sale de pantalla?
* Generas aliens automaticamente y cada cierto tiempo?

Si generas los aliens, los guardas en una lista pero no los eliminas, entonces debe ser problema de manejo de memoria. Es probable que tu computador se quede completamente pegado cuando te pase. La razon son 2 cosas:

1. La lista está cada vez mas llena, pero se salta los aliens muertos. Sin embargo igual debe pasar por todos los aliens muertos antes de llegar a los vivos, lo que aumenta el tiempo por "tick" cada vez más
2. Las variables se guardan en la RAM. Como la lista va creciendo cada vez más, va ocupando más espacio en la RAM hasta que ya no queda espacio disponible y tiene que hacer <a href="https://www.enterprisestorageforum.com/hardware/what-is-memory-swapping/" target="_blank">swapping</a>

Lo que debes hacer entonces es quitar los aliens de la lista cuando ya estén muertos. Una forma no muy eficiente pero que te podría servir es usar una comprensión de lista para el efecto que quieres (o filter, si ya lo sabes utilizar):

```py
aliens = [alien for alien in aliens if not alien.dead]
```
o el equivalente para tu codigo. 

EDIT: ví tu repo y demas de filtrar la lista, ya que tus aliens son threads, debes ver si está fuera de la pantalla y en tal caso detener el thread (poner un break en el while true), para liberar memoria porque si no los aliens siguen moviendose, alejandose de la pantalla sin proposito (incluso luego de ganar el juego o pasar a otra ronda).

**Comment by IgnacioHqz** [comment]
Hola!, se me recomendó revisar esta issue ya que tambien tenía este mismo problema. El asunto es que en mi caso no ocupo un alista para guardar los aliens, sino que ocupo dict() para ir guardandolos. Pero mi pregunta es, sólo tengo 2 aliens guardados y no he guardado las imagenes de los aliens muertos y aun asi cuando lo corro se mueven pero despues se pegan y se cierra la ventana. También puede ser que lo mio sea por RAM o por otra razon?

**Comment by cristhanos** [comment]
Hola, muchas gracias por la respuesta. Lo que pasa es que sólo he creado dos alliens.

**Comment by JJJGGGG** [comment]
@cristhanos @IgnacioHqz si solo tienen 2 aliens es dificil que sea por la ram. Algo debe estar actuando como cuello de botella cada cierto tiempo y provoca que el programa se quede pegado.
