### ISSUE TITLE
Qtdesigner asignación de eventos

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2233/syllabus#209]
Hola,
Cómo hago para hacer un evento entre dos objetos distintos en qtdesigner ( yo logró mandar y recibir señales en qtdesigner solo si está en la misma ventana, ejemplo de un dialog para el mismo dialog)

**Comment by Arcoirisky** [comment]
Realmente, te sugiero hacer eso a mano en tu editor favorito y dejar qtdesigner para diseño de ventanas más que nada 😱 

Pero si te interesa, yo no mantendría dos ventanas abiertas intentando comunicarse entre sí, sino que de la primera, dejaría la segunda como MainWindow y F la primera. 

So, sigues tu vida con la nueva y te olvidas de la que queda (igual terminaría usando la vieja confiable -a mano- para entregar parámetros y eso. Pero, según internet puedes mantener múltiples ventanas comunicándose entre sí ¿Será más simple hacerlo con Qtdesigner? 

Personalmente, no lo creo ni lo recomiendo :s
