### ISSUE TITLE
Instalación de Linux Ubuntu en una partición

### ISSUE THREAD

**Issue by nimorales97** [IIC2233/Syllabus#21]
Hola! Quizás esta pregunta no es exactamente sobre contenido. Ocurre que mi computador últimamente me ha dado muchos problemas, principalmente con el tema de actualizaciones (aún así pude instalar todo el software que se pedía). Se pone muy lento y se queda actualizándose durante horas (hasta 10 horas). Quiero instalar Linux Ubuntu en una partición del equipo (lo tengo en una máquina virtual) atendiendo igual a lo que nos recomendó el profe, que nos va a servir para cursos posteriores, busco ayuda para hacerlo, he usado linux antes pero nunca lo he instalado y no sé hacer una partición, quisiera saber a quién o dónde puedo pedir ayuda. Agradeceré sus respuestas.

**Comment by vijuarez** [comment]
Hola!

En la mayoría de los casos, la instalación de Ubuntu es muy fácil, ya que el wizard de instalación hace todo el trabajo (particiones, configuración inicial, etc...) por ti. Si quieres hacer dual boot (que estén disponibles tanto Windows como Ubuntu) se complica la cosa, pero la última vez que instale Ubuntu (hace unas 2 versiones atrás) era cosa de seguir [las instrucciones oficiales](https://help.ubuntu.com/community/WindowsDualBoot) y todo debería salir bien. El wizard seguirá haciendo el trabajo duro. Además de que es muy difícil romper algo en tu PC (siempre y cuando hagas backup de tu información), así que no te asustes si algo sale mal. Como hacer particiones (y más importante, que son y como funcionan) y otras cosas esotéricas lo puedes ir aprendiendo más adelante.

El primer paso es lograr que haga boot el liveCD de Ubuntu, pero en la página de descarga de Ubuntu deberían haber instrucciones.

Y si, se escapa un poco del contenido, pero creo que puede ser información útil para varios compañeros. No tengas miedo de seguir preguntando, y si necesitas ayuda más personal o inmediata puedes contactarme a mi u otro ayudante.

Saludos!

**Comment by sebacruzd** [comment]
Hola,

Yo hace poco instalé ubuntu y tuve que aprender varias cosas por problemas que hubo, así que te podría ayudar a instalarlo mañana. Tengo libre el 2do módulo.

Saludos!

**Comment by naazocar** [comment]
Hola ! 

Mira yo hice una partición e instalé ubuntu 16.04 en ella via usb sin tener idea previa de nada. Hay muchos tutoriales en youtube y en línea. Si te dedicas un rato a investigar no deberías tener problema. 

Suerte :)

**Comment by MarceloSaldias** [comment]
Yo instale Ubuntu para el curso ahora también y seguí  [esta guía](https://www.tecmint.com/install-ubuntu-16-04-alongside-with-windows-10-or-8-in-dual-boot/), aunque recomendaría mucho que alguien que conozca más del tema te ayude.
Suerte!

**Comment by fgbruna** [comment]
Hola,yo ocupo Ubuntu hace más o menos  7 meses y creo que he pasado por todos los problemas habidos y por haber,pero no por culpa del mismo sistema operativo si no por lo conflictiva que puede ser la **BIOS** o **UEFI** de los computadores con windows para el tema del boot con otro _so_.
Yo te recomiendo instalar Ubuntu borrando el sistema operativo que tienes ya que los problemas de Linux por si solo están mucho mas documentados y pueden ser mucho más fáciles de arreglar que los generados entre Linux y otro sistema.

**Comment by IchottMano** [comment]
Hola buenas, la cosa es que tengo un computador bastante nuevo, que esta especializado para juegos, entonces mi duda es si instalar ubuntu afecaría mucho la velocidad del computador y de no ser asi que tan riesgoso es la instalacion (conozco gente que intentando instalar ubuntu tuvo muchisimos problemas y termino volviendose a windows pero este sin licencia). Muchas gracias

**Comment by vijuarez** [comment]
@IchottMano Hola!

En general Linux funcionara más rápido en lo que es velocidad pura (cuantas cosas puedes tener abiertas o cálculos pesados) que Windows, sencillamente porque vienen con mucho menos software corriendo a tus espaldas. Una fuente mayor de problemas puede ser la GPU (o tarjeta gráfica), ya que suele ser más difícil encontrar drivers que funcionen (esto cada vez menos) e incluso cuando lo logres no encontraras muchas aplicaciones que la sepan utilizar de manera adecuada. En general, tareas como diseño en 3 dimensiones, edición de video/fotos o juegos funcionarían mejor en Windows tanto por desempeño como catalogo de software (al menos en mi experiencia).

En lo demás, Linux suele ser mucho más estable (debido también a que hay menos software a tus espaldas que puede hacer que se caiga el sistema) y funcionar de manera más consistente. Ya pasaron los años en que cada actualización podía matar tu sistema, aunque es verdad que es mucho más fácil matar un Linux que un Windows (estas a un `dd if=/dev/zero of=/dev/hda` de borrar todo tu disco en Linux). Sin embargo, debido a la facilidad para trabajar con herramientas más avanzadas sigue siendo recomendable usar Ubuntu o alguna otra distribución de Linux (mis favoritas son Antergos y Fedora c;) para lo que son los cursos IIC.

Por lo demás, me di cuenta que mi link esta bastante desfasado, así que recomiendo el de @MarceloSaldias como reemplazo.

**Comment by IchottMano** [comment]
Si mi computador tiene 2 discos, uno sólido de aprox 128gb y uno normal de 1tb, puedo instalar ubuntu en el disco mas grande? o tiene que ser necesariamente en el disco solido?

**Comment by sebacruzd** [comment]
Puedes instalarlo donde quieras, pero es más cómodo que sea en el mismo disco por el tema del dual boot.
Si lo instalas en el otro disco tendrías que cambiar el boot sequence cada vez que quieres cambiar de SO.
Te recomiendo que ambos estén en el SSD.
Saludos!

**Comment by nimorales97** [comment]
Muchas gracias por sus respuestas.
Visité las páginas que me dieron e hice todo el proceso para instalar ubuntu, pero al parecer no se instaló correctamente y no inicia. Alguien me puede ayudar con esto despues de clase?

**Comment by IchottMano** [comment]
Tengo un problema similar, sin embargo yo no puedo instalar ubuntu
