### ISSUE TITLE
Error(? pequeño en 4-strings, sobre formato de enteros

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#21]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Sobre formato de enteros

Mi duda proviene del cuarto _notebook_ de contenidos para la semana 00, el de _strings_ :

![image](https://user-images.githubusercontent.com/66154723/111934681-a99d7080-8aa0-11eb-92f2-19d16ae68059.png)

Sin embargo, cuando quité el espacio rellenó con espacios, y no con ceros

![image](https://user-images.githubusercontent.com/66154723/111934767-d5b8f180-8aa0-11eb-81c8-85852ae24cbe.png)

Lo mismo sucedió con los floats

![image](https://user-images.githubusercontent.com/66154723/111934802-ea958500-8aa0-11eb-80d7-cb395832b68d.png)

¿Por qué no rellenó con ceros?
¿Por qué para Floats se usa F, pero para Integers no se usa I, pero se usa D?

Por último, ¿donde puedo encontrar más documentación sobre este tipo de formatting de strings? Me pareció muy interesante y era un contenido que no recuerdo haber visto en intro a la progra.

Gracias de antemano!

**Comment by fernandosmither** [comment]
Por si fuera relevante, tengo instalado Python 3.7.9, y después de verlo en el Jupyter Notebook lo corrí también en el VScode para corroborar.

**Comment by aaossa** [comment]
Hola @fernandosmither , al parecer tienes razón, ocurre lo mismo cuando lo ejecuto yo. Quizás sea un error de los contenidos, por lo que dejaré esta *issue* abierta hasta saber bien si ocurre algo o solo es un error de tipeo 😅. ¿Quizás esa parte se refería a `subtotal` que es de tipo *float*? En ese caso sí se rellena con ceros, aunque no depende del caracter de relleno, así que difícilmente sea eso.

Sobre tus otras preguntas:

* **¿Por qué para Floats se usa F, pero para Integers no se usa I, pero se usa D?**: Eso tiene que ver exactamente con la representación del entero y a que la `'d'` significa "decimal". Puedes encontrar otros valores de representación un poquito más abajo [en esta parte de la documentación](https://docs.python.org/3/library/string.html#formatspec), pero aquí te dejo un ejemplo:

```python
>>> entero = 110 
>>> print(f"{entero:<5f}")  # Formato de punto fijo o "float"
110.000000
>>> print(f"{entero:<5d}")  # Entero decimal
110
>>> print(f"{entero:<5b}")  # Formato binario
1101110   
```

* **¿Dónde puedo encontrar más documentación sobre este tipo de formatting de strings?**: Mientras trataba de encontrar el error de tu primera pregunta encontré información sobre *f-strings* en [esta parte de la documentación](https://docs.python.org/3/library/string.html#formatspec) y desde ahí fui explorando. También podrías encontrar buena información [aquí](https://realpython.com/python-f-strings/) y [aquí](https://zetcode.com/python/fstring/), aunque cubren cosas similares a los contenidos.

¡Gracias por el aviso sobre el primer error! Éxito con tu estudio ✨

**Comment by fernandosmither** [comment]
> Hola @fernandosmither , al parecer tienes razón, ocurre lo mismo cuando lo ejecuto yo. Quizás sea un error de los contenidos, por lo que dejaré esta _issue_ abierta hasta saber bien si ocurre algo o solo es un error de tipeo 😅. ¿Quizás esa parte se refería a `subtotal` que es de tipo _float_? En ese caso sí se rellena con ceros, aunque no depende del caracter de relleno, así que difícilmente sea eso.
> [...]
> ¡Gracias por el aviso sobre el primer error! Éxito con tu estudio ✨

## Respecto al tema,

Primero que nada, agradecer el tiempo que te tomaste para responder mi pregunta 😁, voy a leer la documentación que enviaste.

Luego, probando por mi cuenta me di cuenta que _float_ efectivamente rellena con 0's, pero solo luego de la coma, al menos en mi _setup_ siempre **rellena todo el resto con espacios** antes del número, con lo cual tampoco sería necesario agregar el _whitespace_ al inicio de los _floats_! (en contraste a lo que indica el _notebook_)

_Adjunto imagen_
![image](https://user-images.githubusercontent.com/66154723/112064146-47e11300-8b41-11eb-954e-eaa13ee57c3f.png)

Con esto queda mi primera duda más que resuelta. ¡Muchas gracias!
