### ISSUE TITLE
Duda sobre el codigo base del Ejercicio Propuesto 2.1

### ISSUE THREAD

**Issue by cristobalba** [IIC2233/Syllabus#21]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, estaba intentando realizar el ejercicio propuesto de esta semana "Ejercicio propuesto 2.1 _¡A jugar Pro-Gra-Oh!_" y dentro del código base que venía hecho no entiendo lo siguiente:
`def atacar(self, atacante, defensa):`
        `ptos_ataque = atacante.ataque`
        `ptos_defensa = defensa.defensa`
        `# Rellenar aquí`
**Específicamente, no me queda claro como están definidas las variables "ptos_ataque" y "ptos_defensa", no entiendo qué vendría siendo "atacante.ataque" y "defensa.defensa" en cada caso**

Muchas gracias, saludos
Cristobal :)

**Comment by fernandosmither** [comment]
Hola!

Para esa parte podrías aprovecharte del builtin `namedtuple` para crear los mazos a partir del archivo .csv incluido, de tal manera que al ingresar la namedtuple `atacante` se pueda acceder al valor `.ataque`

**Comment by cristobalba** [comment]
Perfecto! muchas gracias.
Nose si te puedo hacer otra pregunta del mismo ejercicio, que en la variable del mazo "self.mazo" quedarian almacenadas las cartas restantes que no se repartieron a los jugadores? o del archivo .csv deberia pasarlas a esta variable "self.mazo" y luego de repartir cartas a cada jugador eliminar esas cartas del mazo?

**Comment by fernandosmither** [comment]
> Perfecto! muchas gracias.
> Nose si te puedo hacer otra pregunta del mismo ejercicio, que en la variable del mazo "self.mazo" quedarian almacenadas las cartas restantes que no se repartieron a los jugadores? o del archivo .csv deberia pasarlas a esta variable "self.mazo" y luego de repartir cartas a cada jugador eliminar esas cartas del mazo?

Quizás otro ayudante tenga otra opinión, pero de mi perspectiva eso ya es a criterio tuyo, lo más importante es que utilices los built-ins más óptimos en cada situación y seas capaz de tomar datos de un archivo para trabajarlos en un programa.

**Comment by cristobalba** [comment]
Graciaas, me quedo todo claro 👍
