### ISSUE TITLE
Pregunta sobre la base de datos de la T01

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2233/Syllabus#21]
Respecto a los archivos: incendios.csv ; recursos.csv ; meteorología.csv ;  usuarios.csv . ¿ Estos archivos debemos crearlos nosotros ?

**Comment by LuisFros** [comment]
![image](https://cloud.githubusercontent.com/assets/21247721/23802682/cb7eaaf8-0592-11e7-8eba-9fcc65104aee.png)

**Comment by frvalenzuela** [comment]
Ah perfecto, perdón no había leído el correo.
