### ISSUE TITLE
Problemas instalando jupyter

### ISSUE THREAD

**Issue by kisco99** [IIC2233/syllabus#21]
- **Sistema Operativo:** Windows 10
- **Programa a instalar:** Jupyter

- Foto del error:
![image](https://user-images.githubusercontent.com/53839911/62972064-2f473d80-bde1-11e9-96b7-ebe29eb921b7.png)

- Descripción del problema:

Instalo jupyter por medio de pip en la cmd y me dice "requirementes already satisfied"; pero cuando pongo jupyter no me reconoce el comando.

**Comment by jmwielandt** [comment]
Hola!

Se me ocurre que quizás no tienes python agregado al path. Para revisar eso prueba lo siguiente:
1. Abre la cmd.
2. Escribe `python`.
3. Presiona enter.

Si funciona, necesito que revises si hay un archivo. Asumiendo que instalaste python en AppData,
1. Presiona `windows + r`.
2. Copia `%AppData%\..\Local\Programs\Python\Python37\Scripts`.
3. Haz click en aceptar. Se te debería abrir una carpeta.
4. Busca si tienes un archivo llamado `jupyter.exe`.

Si no funciona, en equipo haz click derecho > propiedades > configuración avanzada del sistema > variables de entorno
2. En el recuadro de arriba, en la fila que dice `Path` haz doble click.
3. Haciendo click en "Nuevo", pega las dos siguientes direcciones:
- `C:\Users\francisco valdés\AppData\Local\Programs\Python\Python37\`
- `C:\Users\francisco valdés\AppData\Local\Programs\Python\Python37\Scrits\`

Por último, Aceptar > Aceptar > Aceptar.

Ahora prueba ejecutar `jupyter notebook` en la cmd.

Dinos si funciona~
Saludos!

**Comment by jmwielandt** [comment]
**Update:**

Otra cosa que puedes intentar es corriéndolo con: `python -m notebook`. Si eso funciona es posible que tengas dos instalaciones de python discutiendo el path 🤔.

Por cierto, ¿lo instalaste con `pip install jupyter`?

Saludos!

**Comment by kisco99** [comment]
Hola!
Tengo python en el path pues me lo reconoce en la cmd. Cuando me meto a esta dirección "C:\Users\francisco valdés\AppData\Local\Programs\Python\Python37\Scripts" no encuentro jupyter.exe (probablemente porque ayer me metí a esa dirección a eliminar todo lo que tuviera que ver con jupyter).

Cuando pongo python -m notebook tampoco me funciona.

Sigo probando "jupyter" en la cmd y me dice que no reconoce el comando. 

Realmente nosé que más hacer jajajaja. Eliminé a mano todo lo de jupyter que estaba en Scripts y además puse pip -autoremove jupyter; lo vuelvo a instalar y no me funciona. Si alguien se le ocurre alguna solución se lo agradecría mucho (y si nos podemos juntar presencialmente mejor). Desde ya, muchas gracias.

**Comment by jmwielandt** [comment]
Estoy en la Álvaro Campos (una sala de estudio con muchas pizarras) ahora, puedes venir si estás libre.
(Es adentro del DCC, Edificio San Agustín, 4to piso. Tienes que entrar con la TUC (como alumno de avanzada ya la tienes habilitada)).

~

**Comment by jmwielandt** [comment]
Ya me fui~

Lo que tienes que hacer, a priori es:
- desinstalar todo lo de python
- borrar todos los archivos de python
- reinstala python (agregándolo al path y solo para tu usuario)
- instala jupyter notebook con `pip install jupyter`
- prueba si te funciona.

Creo que al borrar cosas a la mala, quedaron cosas sin borrar y cree que lo tienes instalado ^^u

Saludos~

**Comment by kisco99** [comment]
Perdón! Acabo de leer tu mensaje!! ¿Te tinca si nos juntamos hoy día más tarde o el lunes? Es que tengo miedo de borrar todo y que después no me funcione. Desde ya, muchas gracias

**Comment by jmwielandt** [comment]
Dale, ¿a las 14:15 en la álvaro campos puedes?

**Comment by kisco99** [comment]
Puedo desde ahora hasta las 2. Luego puede de 3:30 a 5

**Comment by kisco99** [comment]
Mejor falto a electro y voy a las 14:15 para no molestarte a otra hora

**Comment by jmwielandt** [comment]
@kisco99

Nos vemos a las 3:40 en la Álvaro Campos

Saludos.

**Comment by kisco99** [comment]
Ahí estaré. Gracias!
