### ISSUE TITLE
FileNotFoundError: VSCode no encuentra ruta especificada

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#21]
Holaa! Publiqué en este _issue_ (https://github.com/IIC2233/syllabus/issues/14) una duda que tenia sobre los contenidos de la Semana 00 `3-paths.ipynb`. Me recomendaron hacer pruebas con los métodos que me daban ahí, pero al momento de hacerlo tuve algunos problemas, pues ni programa no encontraba la "ruta" a la carpeta que quería abrir.

Intenté usar los métodos con una carpeta de archivos que hice yo para probar (`base`), pero al no funcionar decidí clonar el repositorio de la Semana 00 y luego copiar la carpeta `data` al lugar donde estaba trabajando (pensando que a lo mejor había hecho algo mal), para intentar hacer exactamente lo mismo que había en el Notebook, pero el error persistía.

 Estoy trabajando en el archivo `prueba` editado en VSCode, e incluso estando este programa dentro de la misma carpeta que contiene a `data` no puedo acceder a su interior. ¿Que estoy haciendo mal? Por cualquier cosa mi Sist. Operativo es Windows 10 Pro versión 1903 (18362.778)
![duda1](https://user-images.githubusercontent.com/68198662/90274108-ff84a880-de2d-11ea-9a19-01fffeffa505.png)
![duda2](https://user-images.githubusercontent.com/68198662/90274348-64d89980-de2e-11ea-9397-272d088aa3a2.png)

**Comment by igbasly** [comment]
Hola @Gsalinas1506 :v:

Acá  ocurre un error bastante común, no significa que estés haciendo algo mal, solo que faltó un paso entremedio 😅 .
Para contextualizar el origen de este problema, hay que entender que no importa dónde esté el archivo de código a ejecutar, sino **desde dónde se está ejecutando este archivo**. Se puede ver que el archivo son solo instrucciones, por lo que serán relativas a cada quien (python) que las lea.

Para ser más particulares al caso, tu código revisa el contenido de un directorio `/data`, por lo que si ejecutas el archivo `prueba.py` dentro del directorio que a `/data` y a `prueba.py`, digamos `/carpeta_1`, entonces si encontrará el path relativo `/data` y te entregaría su contenido `archivo_1`.
```
|-- /usuario
   |-- /carpeta_2
   |-- /carpeta_1
      |-- prueba.py
      |-- /data
         |-- archivo_1
```

Pero si por ejemplo, lo ejecutaras el archivo `prueba.py` desde el directorio `/carpeta_2` (que está vacía), como `/data` no está dentro de `/carpeta_2` y las instrucciones son busca el directorio `"data"`, no lo va a encontrar.

Esto mismo ocurre con VSCode, como solo abriste el archivo directamente en el editor, este por defecto está ubicado en la carpeta del usuario (que es como la principal), lo cual puedes comprobar viendo lo que te indica la última línea de la terminal del editor:
`C:\Users\gusta>`
**Las terminales siempre indicarán en esa línea cuál es su ubicación en los directorios.**
Es por esto que no se puede encontrar el directorio `"data"`, ya que se está buscando dentro de `Users/gusta`.

Para solucionarlo, te puedo ofrecer las principales opciones:
1.  Desde VSCode ir a
`Archivo/File` > `Abrir.../Open...` > Seleccionas la carpeta del archivo python.
Ejecutar el archivo normalmente.
1. Directamente en la terminal que tienes en VSCode, donde dice `C:\Users\gusta>`
Ingresa `cd <ruta_a_la_carpeta>`
Donde `<ruta_a_la_carpeta>` es la ruta que aparece en la barra superior de la carpeta como de URL, pero debes considerar que solo debes ingresar lo que está después de `C:\Users\gusta`. También sirve arrastrar la carpeta principal (`/Programacion Avanzada`) hasta el `cd ` y la ruta se ingresa automáticamente.
1. Abrir PowerShell o GitBash desde la carpeta principal (`/Programacion Avanzada`) y ejecutar el archivo con `python prueba.py`.

Con eso no deberías tener problemas, lo siento por lo largo, pero creo que es importante que quede claro y entiendas porque se produce junto a las diferentes soluciones que hay.
No dudes en preguntarnos en caso de cualquier duda :smile:, Saludos!

**Comment by Gsalinas1506** [comment]
Yaa perfect, entendí el funcionamiento detrás, Muchas Gracias por eso! Pero me quedan eso si un par de dudas con el listado de procedimientos que pusiste, pues con ninguna pude examinar la carpeta. Puse un `string `después del método para verificar al menos que el código se estaba corriendo

1. Hice lo que me dijiste, poner `Open Folder` para abrir `/Programación Avanzada`, pero al ejecutar el código si bien la terminal me indica que estoy en esa carpeta, tampoco me examina el directorio `/data`

![image](https://user-images.githubusercontent.com/68198662/90291773-9e210180-de4e-11ea-8da9-ee08c8cda735.png)

2. Si hago eso de cambiar el directorio con cd hasta llegar a Programación Avanzada, tampoco logra examinar la carpeta que busco. Solo aparece ese texto azul y amarillo (que asumo indica al computador abrir el archivo en cuestión con Python) y se imprime el _string_ 

![image](https://user-images.githubusercontent.com/68198662/90292058-28696580-de4f-11ea-9961-daa46b022c2e.png)

3. Al intentar ejecutarlo con Git solo se imprime el _string_

![image](https://user-images.githubusercontent.com/68198662/90292740-834f8c80-de50-11ea-9582-c75d8e80d9c1.png)


¿Que es lo que puede estar mal?

**Comment by igbasly** [comment]
Me alegro que haya funcionado 😃, de hecho las tres fotos que muestras indican que funcionó correctamente :+1:.
Ahora ocurre ya un problema de programación, lo que pasa es que nunca imprimes lo que `os.listdir("data")` entrega, solo lo dejas guardado en la variable `lista_de_contenidos`. Recuerda que para mostrar cualquier cosa en Python es necesario agregar el `print`, lo que aquí sería `print(lista_de_contenidos)`.

Con eso ya deberías estar al otro lado 👌.

**Comment by Gsalinas1506** [comment]
jajajajajajaja me volé, pero ya entendí. Muuchas Gracias!!

PD: Ok, entendí mi error ¿Pero porqué en el .ipynb 03 no se pone el print, y sí logra imprimirse la lista?¿Es algo propio de este tipo de archivos?

**Comment by igbasly** [comment]
Jajajaja son cosas que nos pasan a todos. 😅

Lo otro se debe a como funciona Jupiter, lo cual hace en base a IPython que un [REPL](https://en.m.wikipedia.org/wiki/Read–eval–print_loop) o consola de lenguaje. Esto es similar a que abrieras un terminal en tu computador e ingresaras `python`, lo cual te va a abrir la consola de Python que te permitirá programar en ella ejecutando los comandos a medida que los vayas ingresando.
En este caso Jupiter va leyendo las líneas y ejecutándolas.

Volviendo al tema específico, las consolas por lo general agregan algo así como un print implícito cuando colocas solo el nombre de una variables, lo que te permite mostrar su contenido. Pero cuando ejecutas un archivo, esto ya no pasa por una consola y solo lo que el lenguaje indique se debe mostrar será retornado, en este caso aquellas cosas que pasen por un `print`.

**Comment by Gsalinas1506** [comment]
Ahhh entiendo. Ahora todo me queda mucho más claro. Muuuuuchas Gracias!
