### ISSUE TITLE
Error wsl

### ISSUE THREAD

**Issue by AgustinSaavedra1** [IIC2233/Syllabus#21]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

<img width="549" alt="image" src="https://github.com/IIC2233/Syllabus/assets/141973713/3f573cf4-d8c9-4b84-888d-9464f44af320">

Al intentar instalar el wsl me entrega un error que dice que hay una característica no instalada. Intente desinstalar el wsl con unos comandos que se mencionaron en un problema de otro alumno pero también me entregaba un error.

**Comment by Hernan4444** [comment]
Hola @AgustinSaavedra1 

Puedes revisar esta issue please
* https://github.com/IIC2233/Syllabus/issues/13

Si bien no es el mismo error, tal vez te pueda servir las alternativas entregadas por la profesora (en especial la solución 2 creo que es la necesario). Luego, si esas 4 solucionen no funcionan, avisarnos en esta issue. Así al menos ya podemos descartar esas opciones y buscar por otro lado la solución.

Tambien, cómo se indicó en esa misma issue, verificar que tengas todas las actualizaciones de tu pc instalado. Puede ser que falta actualizarlo para que WSL esté activado.

Quedamos atentos,

**Comment by AlvaroNorambuena** [comment]
Hola tenia el mismo problema y como bien dijiste la solucion 2 me sirvio a mi, muchas gracias.

**Comment by AgustinSaavedra1** [comment]
> Hola @AgustinSaavedra1
> 
> Puedes revisar esta issue please
> 
> * [WSL: "Interfaz no compatible". #13](https://github.com/IIC2233/Syllabus/issues/13)
> 
> Si bien no es el mismo error, tal vez te pueda servir las alternativas entregadas por la profesora (en especial la solución 2 creo que es la necesario). Luego, si esas 4 solucionen no funcionan, avisarnos en esta issue. Así al menos ya podemos descartar esas opciones y buscar por otro lado la solución.
> 
> Tambien, cómo se indicó en esa misma issue, verificar que tengas todas las actualizaciones de tu pc instalado. Puede ser que falta actualizarlo para que WSL esté activado.
> 
> Quedamos atentos,

Hola, utilice la solucion dos del issue mencionado y con eso pude solucionar el problema, muchas gracias
