### ISSUE TITLE
Duda contenido 6: uso de super().__init__ dentro de superclase.

### ISSUE THREAD

**Issue by jfpena1** [IIC2233/syllabus#21]
Hola, en los contenidos, especificamente en la parte 6 de multiherencia, no entiendo porqué en el ejemplo final se llama al super().__init__(**kwargs) DENTRO de los init de las superclases Investigador y Docente, respectivamente. Entiendo su uso en la subclase Academico, sin embargo no me queda claro porque tambien se incluye en ambas clases de las cuales Academico hereda.

Adjunto una foto del codigo para clarificar:
![codigo](https://user-images.githubusercontent.com/39381457/54568448-f03dc900-49b5-11e9-8082-79ad27a51fa5.JPG)

Gracias!

**Comment by naquiroz** [comment]
Hola! A mi parecer no es necesario, dado que ambas clases no están heredando de nada (mas que de `object` dado que todo en _python_ hereda de `object`), sin embargo, no es mala práctica hacerlo, por lo que no le hace daño a nadie 😄 . Espero haber respondido tu duda ✌️

**Comment by fdoflorenzano** [comment]
¡Hola! 
Como dice @naquiroz, no es necesario en ese caso específico. Se incluyeron para ser más general. En el caso de que incluso esas clases heredaran de otras, como tal vez una clase: `Persona`, entonces poder seguir con la cadena de paso de argumentos.
Saludos.

**Comment by jfpena1** [comment]
gracias!
