### ISSUE TITLE
Comando git status no reconoce cambios (Windows 10)

### ISSUE THREAD

**Issue by LucaSpiniello** [IIC2233/syllabus#21]
cuando cambio algún archivo de mi repositorio personal desde los archivos del computador y luego ejecuto git status en git bash, este no reconoce el cambio y me arroja:
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

**Comment by MatiasDuhalde** [comment]
Hola! Tu problema se puede deber a distintas razones, pero la más probable es que estés ejecutando el comando `git status` desde otro directorio distinto a tu repositorio personal. Recuerda que puedes cambiar el directorio desde la consola usando el comando `cd` (esto se explicó en la [clase de la semana 0](https://github.com/IIC2233/syllabus/blob/master/Clases/Semana%200%20-%20Bienvenida.pdf) que ya está subida al syllabus, por si la queres revisar). 

Otra opción (que funciona en Windows 10) sería abrir la carpeta donde hiciste el cambio, hacer click derecho en algún lugar de la carpeta, y presionar `Git Bash Here`.

![Untitled](https://user-images.githubusercontent.com/46191755/76786248-a7218000-6795-11ea-99cc-efbebdc8e615.png)

Eso abrira una consola Bash en el directorio de la carpeta, y ahí si te debería funcionar el comando `git status`.
