### ISSUE TITLE
Duda archivos dificultad y unidades

### ISSUE THREAD

**Issue by SebaPassi** [IIC2233/Syllabus#210]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Tengo una pregunta sobre los posibles errores que pueden surgir con los archivos de "dificultad" y el de "unidades.txt". ¿Se puede asumir que siempre serán de la forma "Nombre, tipo de gato, valores numéricos para cada atributo"? Obviamente ahí debiésemos revisar que la cantidad de argumentos por gato sea la correcta, que los valores numéricos estén dentro del rango de cada atributo, y que el tipo de mago sea válido, ¿pero se puede asumir que siempre se seguirá ese orden? O podría darse el caso donde se nos entregue una línea de código donde el "nombre" del gato sea un número (por ejemplo), es decir, "2, MAG, 100, 50, 20, 10, 10".

Espero haberme explicado bien, muchas gracias!

**Comment by diegoftpxd** [comment]
Hola @SebaPassi !. Si puedes asumir que siempre están en ese orden. Pero mucho ojo con el ejemplo que entregaste, porque en ese caso, como el primer término es el nombre, el 2 debe interpretarse como el string "2". Por lo que es un nombre válido.

Espero haberte ayudado.

**Comment by SebaPassi** [comment]
¿Entonces el nombre no tiene ninguna restricción o no?
