### ISSUE TITLE
coma en vez de punto y coma en archivo csv_generator.py

### ISSUE THREAD

**Issue by rakarachon** [IIC2233/Syllabus#210]
Hola, me di cuenta que en el archivo csv_generator.py el archivo pieces.csv se crea con una coma (',') en vez de punto y coma. ¿No se si esta bien o es un error? Me hace más sentido que fuera ';', como es un archivo csv... Además en el enunciado el formato del archivo pieces.csv se muestra en dos columnas, y con la coma queda todo en una sola columna. No se en realidad si este detalle afecta demasiado el desarrollo de la tarea, pero se me imagina que podría hacerlo eventualmente, cuando tengamos que abrir el archivo.

**Comment by sebacruzd** [comment]
Hola, csv significa _"comma separated values"_, por lo que son **valores separados por comas**.

Como dices tu, también hay archivos csv que son separados por ";", pero estos son otras variaciones de csv. A veces también es con "-" y con muchos otros caracteres para separar los datos.

Para asegurarte que lo harás bien, simplemente abre el archivo .csv o leelo con python y haz print de una línea. 

Finalmente, para informarte más, te recomiendo leer [esta página](https://es.wikipedia.org/wiki/Valores_separados_por_comas).
Saludos!

**Comment by rakarachon** [comment]
Si abrí el archivo csv que se creó después de ejecutar el archivo csv_generator.py, y quedó todo en una sola columna (y la coma aparecía entre medio, como si la hubiera tomado como un caracter cualquiera). En realidad no me complica , o sea que no creo que manejar el archivo vaya a ser un problema, como sea que quede, preguntaba solo para estar segura.

Igual, pensaba que los csv solo se podían separar con punto y coma porque en verdad nunca los había manejado de otra forma. Gracias por la aclaración!

**Comment by sebacruzd** [comment]
Esa es la idea del .csv. Es una linea con varios elementos separados por comas, ya que no se pretende trabajar como una hoja de cálculos, sino que con un programa que lo lea y lo procese.


Es bastante fácil procesar eso con python, te lo dejo sin la solución para que tú lo pienses.

Suerte :)

**Comment by rakarachon** [comment]
Si, tienes razón, no tiene porque ser una hoja de cálculos; o sea, para efectos del programa da lo mismo. Y si, en verdad no es dificil procesarlo con python, como sea que esté separado. Muchas gracias!
