### ISSUE TITLE
Ayudantía semana 2

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2233/syllabus#210]
Hola, quería saber si van a subir el video de la ayudantía de hoy a alguna parte, o si ya la subieron, dónde está :) graciaas

**Comment by Drpinto1** [comment]
¡Hola!

Estamos evaluando la opción de subir el video, pero en cuanto esté disponible se les mandará un aviso. Lo que si se subirá en unos minutos es la solución de la ayudantía (en la carptea de ayudantías del Syllabus)

Saludos :D
