### ISSUE TITLE
Dificultad arena magnetica

### ISSUE THREAD

**Issue by cataguzmanw** [IIC2233/Syllabus#210]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Lei los otros issues con respecto a este tema y no me quedaron muy claros, la dificultad de la arena magnética hereda de la mojada y rocosa, como se cual usar en este caso? En el caso de usar la dificultad de la arena rocosa, los parámetros humedad y dureza a reemplazar en la formula son los nuevos aleatorios verdad?

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Benjeeeh** [comment]
Hola!

Como magnética comparte las mismas características de mojada y rocosa, piensa en que hace única a cada arena. Para el caso de mojada, no se menciona ningún atributo especial respecto a la dificultad, solo respecto a ítems, por lo que la dificultad de esta sería la clásica de arena normal. Por otra parte, la rocosa varía en dificultad respecto a las arenas convencionales. Entonces, para preservar las características de cada arena y que se reflejen en magnética, deberías tomar cada atributo que hace especial a estas.
Esto mismo se menciona en la issue #201 

Respecto a los parámetros de humedad y dureza, sí, se deben usar valores aleatorios por cada simulación.

Éxito!!
