### ISSUE TITLE
Duda ejercicio 3.1 semana 4: Problema con atributos de clase

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#210]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Funcionamiento de atributos de clase

Tengo este ejercicio mas o menos terminado, pero hay unos detalles de los atributos de clase que no he logrado solucionar, por ejemplo, para contar los casos de copia deje una atributo de clase igual a 0 que luego se suma 1 cada vez que hay copia, sin embargo, no me di  cuenta que esto resetea la variable cada vez que se instancia una copia.

Por otro lado, hice algo similar para guardar a los copiones, pero en este caso, mi estructura de datos no se resetea, y estoy seguro de esto porque al final si imprime a los estudiantes que realizaron copia.

Al final mi pregunta es, ¿Cómo puedo hacer que un contador no de resetee cada vez que se instancie un error? también. si hice esencialmente lo mismo para guardar los copiones ¿Por que no se resetea mi base de datos también? (use un set)

**Comment by ignacio-urrutia** [comment]
Hola @Pabloski100! Cuando hice el ejercicio me pasó exactamente lo mismo que a ti así que tu duda me sirvió para aprender algo nuevo. que aprendí tras una breve investigación en internet, te cuento:
Cuando intentas modificar una variable de clase utilizando `self.nombre_de_la_variable = algo` lo que ocurre es que se crea un atributo dentro de la instancia con el mismo nombre y por ende, al modificarla, solo estás alterando el atributo de la instancia. Si lo que deseas es modificar el atributo de la clase, lo que debes hacer es en lugar de llamar a la variable como `self.nombre_de_la_variable` debes hacerlo de la forma `NombreDeLaClase.nombre_de_la_variable = algo` y de esta forma estarás accediendo directamente a la variable de clase. 
Esto no ocurre con otras estructuras de datos como los sets, ya que al agregar un elemento con `add`, lo estás agregando directamente  la memoria asignada a esa estructura, en cambio cuando haces, po ejemplo `self.a + = b`, lo que estás haciendo en realidad es análogo a escribir `self.a =  self.a + b` lo que el computador lo interpreta como `self.a` (atributo de la instancia) `=self.a` (variable de clase) + b.

Espero te sirva mi explicación. En cualquier caso , [aquí ](https://www.geeksforgeeks.org/g-fact-42-changing-class-members-python/)está la página de la que saqué la información por si la quieres revisar.

Cualquier consulta no dudes en preguntar por ese mismo medio. Mucho éxito!
