### ISSUE TITLE
Citar código de bombas en tarea

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2233/syllabus#210]
Hola, queria reutilizar un codigo de bombas que tenia desde intro a la programacion. El tema esque en ese momento hice el codigo con una persona y actualmente tambien esta dando el ramo. Es problema que ocupemos la misma base del funcionamiento pero ahora cada uno hace los cambios que considere necesarios para que el codigo sirva en la tarea?

**Comment by gatochico** [comment]
Hola!

Primero que todo, te recomendaría fuertemente que en vez de reutilizar ese código de forma directa, trataras de **reescribir** esa funcionalidad desde cero, tomando en cuenta tus experiencias en otros cursos de programación y las modificaciones extra que se le deberían hacer para integrarlo en esta tarea. Esto hará que tu código sea más 'único' y no se asemeje al de tus compañeres. 

Ahora, con respecto a **citar** material: Les recordamos que pueden citar material de internet, o que haya sido publicado o entregado en otros cursos (por ejemplo, clases de Intro), pero NO pueden citar código de entregas que no sean de este curso, pues no puede ser verificado por el corrector. Fuera de lo que está legalmente citado, todo el código entregado debe ser desarrollado por ustedes.

Finalmente, recuerden que las evaluaciones del curso son de caracter **individual**, por lo que compartir código entre estudiantes está prohibido.

Espero se haya entendido y éxito con tu tarea! 🚢
