### ISSUE TITLE
¿Como pedirle información al backend, desde el frontend?

### ISSUE THREAD

**Issue by dvillas28** [IIC2233/Syllabus#210]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Estoy tratando de implementar un frontend donde antes de inicar los widgets, se necesita de un diccionario de datos que quiero que el backend sea el que los posea en su metodo `__init__`. Esto para que el frontend inicie sus widgets (un drop-menu especificamente) con una serie de datos por defecto, incluidos en el diccionario. 

Estoy tratando de implementarlo usando señales para que *el frontend se los pida al backend*, pero no logro conseguir el resultado que necesito. No logró hacer que el backend entregue el diccionario, luego se emitir la señal de pedida de datos en el frontend

La duda se resume entonces en **¿como pedir un diccionario desde el frontend, al backend, usando señales?**

Agredeceria que alguien me explicase como se podria hacer, o si lo estoy pensando mal y existe una mejor forma de hacerlo
Saludos

**Comment by CarlangaUC** [comment]
Hola buenas!

Para mandar distintos tipos de datos basta especificar en la señal el *tipo* de dato que envias, te dejo el ejemplo de una ventana con un boton que pide el diccionario del inicializador al backend , para luego imprimir la primera key, me comentas si entiendes lo que te plantee :) !

# frontend
```python
from PyQt6.QtWidgets import QVBoxLayout, QPushButton, QWidget
from PyQt6.QtCore import pyqtSignal

class Ventana(QWidget):
    
    pedir_diccionario = pyqtSignal()
    
    def __init__(self,*args,**kwargs):
        
        super().__init__(*args,**kwargs)
        self.setWindowTitle("TESTEO")
        self.setGeometry(0, 0, 500, 500)

        layout_vertical = QVBoxLayout()
                
        boton_mandar = QPushButton("RECIBIR", self)
                
        boton_mandar.clicked.connect(self.metodo_pedir_diccionario)
        
        layout_vertical.addStretch(1)
        layout_vertical.addWidget(boton_mandar)
        layout_vertical.addStretch(1)
        
        self.setLayout(layout_vertical)
    
    def metodo_recibir_diccionario(self, diccionario):
        
        self.diccionario = diccionario
        print(self.diccionario[0])
        
        
    def metodo_pedir_diccionario(self):

        self.pedir_diccionario.emit()

```

# backend
```python
from PyQt6.QtCore import QObject,pyqtSignal
class Logica(QObject):
    
    senal_mandar_diccionario = pyqtSignal(dict)
    
    def __init__(self,diccionario,*args,**kwargs):
        
        super().__init__(*args,**kwargs)
        self.diccionario = diccionario
        
    def mandar_diccionario(self):
        
        self.senal_mandar_diccionario.emit(self.diccionario)
```
# main.py
```python
import sys
from PyQt6.QtWidgets import QApplication
from frontend.ventana import Ventana
from backend.logica import Logica
if __name__ == '__main__':
    
    app = QApplication([])
    testeo = Ventana()
    logica = Logica({0:"Hola",1:"Como",2:"Estas"})

    testeo.show()

    testeo.pedir_diccionario.connect(logica.mandar_diccionario)
    logica.senal_mandar_diccionario.connect(testeo.metodo_recibir_diccionario)
    
    sys.exit(app.exec())
```

**Comment by dvillas28** [comment]
Ya, estaba enredándome en querer iniciar todo el layout de una con los datos incluidos, pero creo que es mejor iniciarlos vacíos nomas y después que una función (la que recibe el diccionario) se encargue de ir metiéndolos donde corresponda

muchas gracias!
