### ISSUE TITLE
Juego se cae/cierra

### ISSUE THREAD

**Issue by IgnacioHqz** [IIC2233/Syllabus#210]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x]  De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, hace poco pude lograr que los aliens se pudieran mover dentro de la pantalla, pero el problema que tengo es que si bien se mueven bien, a veces el programa se queda pegado o simplemente la ventana se cierra. Qué podría ser? sospecho de que tal vez sea que el tiempo en hacer mover los aliens es más rapido que el tiempo que tarda el programa en realizar unos pasos previos que he creado antes de mover los aliens, y tal vez por esto se pegue, pero no sé si sea eso. Gracias!

**Comment by JJJGGGG** [comment]
Hola, la issue #209 tiene un problema muy similar al tuyo. Intenta ver si por ahí lo puedes resolver.
