### ISSUE TITLE
Ayudantía QtGridLayout() y manejo de pixeles

### ISSUE THREAD

**Issue by isihirmas** [IIC2233/syllabus#210]
Hola! En la ayudantía de mañana pueden hacer un ejemplo de cómo cargar los archivos png con QtGridLayout()? En el material no queda tan claro. 
Y también en el caso de la tarea, hay imágenes para el mapa que tienen pedazos de pasto y pedazos de camino, entonces no sé cómo distinguirlos a nivel de código para implementar objetos u otros elementos. (Tal vez se puede ver con el tamaño de pixeles de la imagen pero tampoco encontré material sobre eso).

Muchas gracias!

**Comment by Hernan4444** [comment]
¡Hola!

Lamento informar que no podremos hacer eso para la ayudantía. Los principales motivos son:
1.  Cargar archivos PNG con el uso de `QtGridLayout` hará que muchos alumnos vayan por ese camino y no queremos/podemos tendenciar dicha forma de enfrentar la tarea. Por otro lado, para quienes no lo quieran hacer así no les servirá la ayudantía y tenemos que priorizar ese modulo para hablar y mostrar cosas que le pueden servir a la mayor cantidad de alumnos.

2. Por cosas de tiempo, la ayudantía ya está planificada para hacer otras cosas que necesitamos que todos los alumnos que asistan lo vean.

Sobre los sprites, hay varios que no tienen ningún pedazo (como el [236](https://github.com/IIC2233/syllabus/blob/master/Tareas/T02/sprites/mapa/towerDefense_tile236.png)), puedes usar específicamente esos para representar caminos o espacios libres. La idea de pasarles tantos es para quien quiera adornar más su mapa, puede identificar esquinas en el mapa y poner sprites con pedazos en las esquinas. Pero para tener todo el puntaje, no es necesario ocupar esos. Por lo tanto, puedes dejar predefinido en `constante.py` algo como:
```python
PATH_CAMINO = "sprites/mapas/towerDefense_tile236.png"
PATH_OBSTACULO = "sprites/mapas/towerDefense_tile237.png"
```

Lamento no poder ayudar con esto durante la ayudantía, pero cualquier duda, puedes hacer una issue con dudas respecto a dicho material para poder explicar mejor esa parte.

Saludos :v:
