### ISSUE TITLE
Duda Test FaitHibrido 

### ISSUE THREAD

**Issue by sunrayito** [IIC2233/Syllabus#210]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Hola, encontré una inconsistencia en los test cases de FaitHibrido, en los test cases se espera que los primeros 10km sean recorridos en auto eléctrico, sin embargo en el enunciado se especifica que son los primeros 10.0km, por lo que al poner 10.0 tira error porque el output esperado es 10 (sin .0). Debería llamar a la función utilizando 10 o es problema de los test cases? 

![image](https://github.com/user-attachments/assets/c1d4bcc5-c377-4bb1-ba08-55b85767cf09)

**Comment by Hernan4444** [comment]
Hola @sunrayito 

Es un error en el tests (el enunciado siempre manda), pero dado que ya estamos a martes y la entrega se hace el jueves, se corrigió el tests para aceptar ambas versiones (usando 10 o 10.0). De este modo, si alguien no revisa esta issue, igual lo tendrá bueno en los tests privados (mientras use 10 o 10.0 y no otro valor 😅). 

Muchas gracias por notarlo y notificarlo!

¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ
