### ISSUE TITLE
Duda sobre entidades

### ISSUE THREAD

**Issue by jbulness** [IIC2233/syllabus#210]
Hola, quería saber si es necesario crear una clase para cada entidad (por ejemplo, una clase para cada tipo de vehículo). Pregunto esto porque me resulta más simple no hacerlo de esta forma, pero no sé si se descuenta puntaje por no hacerlo así. De igual forma tengo aplicada herencia y multiherencia para otras entidades y de otras formas.

Gracias por su tiempo.

**Comment by jaromero6** [comment]
Hola
No puedo responder directamente a tú pregunta cuál forma de hacerlo es mejor, pues este es precisamente uno de los objetivos que busca la tarea. Sin embargo puedo darte algunos consejos que ayuden a orientarte y decidir cual manera sería la correcta:
- ¿Debe ser toda entidad del problema que busco modelar una clase? Dependerá de como quieras que dicha entidad  se relacione con el resto de entidades en tú programa.
- Recuerda que OOP es un modelamiento escalable, es decir, te facilita en un futuro añadir nuevas funcionalidades o entidades a tú código: ¿Qué manera de modelar o contenido visto en el curso ayudaría a realizar esto?

Espero haberte ayudado
