### ISSUE TITLE
Problema con git , recuperar archivos

### ISSUE THREAD

**Issue by negutierrez** [IIC2233/Syllabus#211]
Hola, hice un git pull a mi repositorio privado desde mi carpeta T02, con lo que todos los archivos y modulos que tenía ahí fueron reemplazados por un solo archivo que había subido antes a mi repo...
 hay alguna forma de recuperar estos archivos?! 

gracias

**Comment by stephichau** [comment]
@negutierrez si trabajas con PyCharm, ésta guarda una copia de los archivos con los que has trabajado recientemente ([leer acá](https://www.jetbrains.com/help/pycharm/2016.3/viewing-local-history-of-a-file-or-folder.html)). Además, si lograste hacer un commit de los archivos, puedes moverte a commits pasados siguiendo [estos pasos](http://stackoverflow.com/questions/4114095/how-to-revert-git-repository-to-a-previous-commit) :)

**Comment by negutierrez** [comment]
ya los recuperé, gracias!
