### ISSUE TITLE
Solución ejercicios propuestos

### ISSUE THREAD

**Issue by rldelafuente** [IIC2233/syllabus#211]
Hola! Me entró la duda si es que suben las soluciones de los ejercicios propuestos de las clases semanales, ya que en enunciado dice:  _"Si tienes dudas sobre algún problema o alguna solución...."_ . Si suben las soluciones, dónde las puedo encontrar?

**Comment by Drpinto1** [comment]
¡Hola!

En esa parte del enunciado se refiere a tus propias soluciones, pues las de los ejercicios propuestos no se suben.

Saludos :D
