### ISSUE TITLE
¿Qué se puede hacer con la gui y que cosas no?

### ISSUE THREAD

**Issue by JPSF** [IIC2233/Syllabus#211]
En el enunciado dice que se pueden usar ciertos métodos (aunque son funciones que llaman a métodos) que se encuentran en el archivo __init__.py. No me queda tan claro qué cosas son legales de hacer y cuales no lo son.
1. ¿Sólo puedo usar dichas funciones para acceder a los métodos de la gui, o también puedo llamar a los métodos directamente?
2. ¿Se puede crear instancias pertenecientes a las clases de la gui (aparte de la interface)?
3. ¿Puedo cambiar o llamar a algún atributo de una instancia de la gui directamente? #

**Comment by iqacevedo** [comment]
Hola ,

1-. Sip, solo puedes acceder a través de esas funciones, no directamente.
2-. Nop, la idea es que solo utilicen GameInterfaz para interactuar con la gui.
3-. Por lo mismo anterior no pueden, se espera que en lo relativo a interactuar con la gui solo utilicen las funciones descritas en el enunciado y las de GameInterfaz, cuando sobreescriben estas últimas (usando herencia como en el ejemplo de demo.py).

Saludos !

**Comment by AngelMatias** [comment]
Se supone que aca debemos implementar nuestros propios codigos que hagan la accion de los respectivos metodos ?
<img width="453" alt="captura de pantalla 2017-09-04 a la s 17 16 16" src="https://user-images.githubusercontent.com/30705123/30037811-f4195e98-9194-11e7-94d6-ada3fadaf2ee.png">

**Comment by Sforrego** [comment]
@AngelMatias 
estoy casi seguro de que es aca:

![image](https://user-images.githubusercontent.com/26422390/30038682-beddad02-919d-11e7-8252-8e38073b7f6a.png)

**Comment by AngelMatias** [comment]
Pero ese es el demo, entiendo que eso es un ejemplo nomas o ese es el que hay que editar ??? (Estoy confundido 🤦🏼‍♂️)

**Comment by fabarros** [comment]
Eso sale en el enunciado. Dice que debemos editar los métodos que salen en el Demo.py para que la interfaz haga lo que se explica en el enunciado que tiene que hacer, es decir, implementar las reglas, puntos, etc.

**Comment by iqacevedo** [comment]
Hola !

Pueden simplemente editar demo.py, o crear un nuevo archivo en el que importen la gui y que tengan una clase similar a MyInterface, que aparece en demo.py (debe heredar de GameInterfaz). De todas maneras es más sencillo que solo sobrescriban los métodos de demo.py. Eso si @AngelMatias no deben modificar ningún archivo dentro de la carpeta gui.

Saludos!

**Comment by AngelMatias** [comment]
Pero no entiendo como esta funcionando Demo.py , en que momento el codigo ejecutan las animaciones, o abre la interfaz, etc. Por eso no entiendo que cambios podria darle, por ej en los metodos de MyInterface solo salen prints

**Comment by iqacevedo** [comment]
Hola, 

Las animaciones y la interfaz en si misma, son ejecutadas a través de los archivos de la carpeta gui, específicamente la interfaz es la clase Game que encontrarás adentro, pero ustedes no deben modificar nada de lo que está ahí porque es materia que aun no han visto. 

Lo que hace la interfaz es que cada vez que haces click en ella, emite una señal que llama a la función de MyInterfaz (nuevamente lo de la señal es de PyQt5), que es la que estas sobrescribiendo en demo.py para que tu hagas algo, tiene prints para que se pudiera ilustrar que cuando aprietan algo se ejecuta la función que están sobrescribiendo. Cuando quieres cambiar algo de la interfaz gráficamente debes llamar a alguna de las funciones que se muestran en el enunciado del tipo gui.funcion(x, y), estas funciones interactuan directamente con la interfaz haciendo lo que sale en el enunciado que hacen.

Espero que te haya queda más claro, pero esto es materia que verán en un futuro y no es necesario que entiendas como se implemento en si la interfaz, solo necesitas saber como ocuparlo y es tan simple como sobrescribir las funciones para que hagan lo que tu quieras cuando son llamadas.

Saludos!

**Comment by AngelMatias** [comment]
🤔 pero entonces solo ocupo las del tipo, por ejemplo, gui.add_piece ?

**Comment by iqacevedo** [comment]
sip, son las únicas funciones que tu debes llamar, salen todas en el enunciado y en la issue #232 se agrego otra más.

**Comment by AngelMatias** [comment]
yaaa perfect, pero antes debo crear un objeto del tipo git.GamerInterface o bien crear una clase que herede esas caract ?

**Comment by iqacevedo** [comment]
Puedes crear una clase que herede de gui.GameInterface, tal como lo hace MyInterface, aunque la manera más simple es sobreescribir los métodos de MyInterface y no tendrías que crear una nueva clase  que tenga los mismos métodos.

**Comment by AngelMatias** [comment]
yaaa perfect ! entiendo, y otra duda, sabes porque pycharm me marca en rojo al importar gui?
<img width="291" alt="captura de pantalla 2017-09-05 a la s 16 52 28" src="https://user-images.githubusercontent.com/30705123/30080643-a8359bce-925a-11e7-8b9e-05d09e1cb717.png">

**Comment by Hernan4444** [comment]
@AngelMatias desde donde abriste el proyecto de python?? 
Pycharm a veces se confunde cuando abres un proyecto desde una carpeta muy "alejada" del archivo que estás usando (La sources root es por ejemplo la carpeta Tareas o tu repositorio) y los `import` no los reconoce como que estás importante la librería `gui` que hicimos. 

Si quieres solucionar eso, hay 2 opciones:
1. Intenta "Abrir Proyecto" y selecciona tu carpeta T02, con eso pycharm abre solo tu carpeta T02 y ahí debería reconocer la gui
1. A la izquierda está la barra de Project, tienes que hacer `click derecho` en la carpeta T02, poner el mouse en la opcion "Mark Directory as" y seleccionar Sources Root.

Ahí me cuentas si te dejó de salir rojo.
Saludos ✌️
