### ISSUE TITLE
Jugadores con atributos iterables

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#211]
Hola! Una consulta... En la sección 4.3 dice que los jugadores deben tener atributos iterables en el mismo orden que la base de datos. Eso quiere decir que no puedo trabajar con una clase Jugador con sus respectivos atributos, sino que debo sí o sí ingresar la información de cada jugador a una estructura de datos creadas por mí?

**Comment by IchottMano** [comment]
@llloyola Hola!
Efectivamente, la idea es que la información de los jugadores se encuentre en una estructura de datos que tu hayas creado.
Saludos!

**Comment by vextraz** [comment]
Pero esa estructura de datos debe ser la misma tanto para la GUI como para hacer y consultar los grafos de afinidad?

**Comment by IchottMano** [comment]
@vextraz Eso queda a tu criterio.
Saludos!

**Comment by llloyola** [comment]
Entonces...

- A la GUI hay que pasarle sí o sí una estructura de datos iterable que contenga la información de los jugadores?

- Para el caso de los cálculos de afinidad y consultas, eso sí lo puedo hacer con una clase Jugador que contenga la información de cada jugador?

**Comment by IchottMano** [comment]
@llloyola Hola!

En primer lugar, tu a la GUI solo le entregas datos con las funciones dadas en el enunciado, la GUI se encarga de hacer el resto.

En segundo lugar la idea es que uses tu estructura de datos para contener la información de los jugadores y hacer los cálculos a través de esta.

Espero esto resuelva tus dudas.
Saludos!

**Comment by llloyola** [comment]
Creo que es hora de que borre (**muchas**) líneas de mi código... Jajaj 
Gracias! :+1:

**Comment by IchottMano** [comment]
@llloyola Jajaja eso es algo que suele pasar en estas tareas...

Mucho éxito con tu tarea!

**Comment by llloyola** [comment]
😄
