### ISSUE TITLE
duda posibilidad de errores en predios.txt T1

### ISSUE THREAD

**Issue by ManoCarva** [IIC2233/Syllabus#211]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

El enunciado dice que predios.txt siempre seguirá el mismo formato pero, ¿no debemos preocuparnos por si es que está mal formateado a propósito?
También aunque está dicho explícitamente quería asegurarme. ¿Suponemos en el menú que el usuario nunca escribirá datos erróneos o en un formato incorrecto cuando escriba el input?

**Comment by ignacio-sp** [comment]
Hola @ManoCarva, el formato de predios.txt siempre se mantendrá, por lo que no tienen que verificar que tenga la forma incorrecta, lo que sí puede cambiar, son los códigos de los predios y las dimensiones, pero el orden se mantiene.

Para el menú, hay casos que en el enunciado se indica que se puede asumir que se ingresarán datos correctamente, sin embargo, hay que manejar casos en donde el usuario puede ingresar algo incorrecto sin romper el formato ni contradecir el enunciado (ej: ingresar un código de predio erróneo)

Espero se haya entendido, estoy atento!
