### ISSUE TITLE
Duda sobre clases vehículos

### ISSUE THREAD

**Issue by fsmc** [IIC2233/syllabus#211]
Hola! Es necesario hacer una superase vehículo y que sus subclases sean cada tipo de vehículo? O se puede hacer una clase solo de vehículo que tenga todos los atributos de los vehículos?

**Comment by jaromero6** [comment]
Hola
Lamentablemente no te puedo responder esa pregunta, pero la issue #210 tiene algunos hints que podrían ayudarte a decidir sobre que manera sería mejor de hacerlo.
Espero te sirva
