### ISSUE TITLE
ruta puntajes.txt

### ISSUE THREAD

**Issue by jo00** [IIC2233/syllabus#211]
Hola, respecto a la ruta que debemos escribir para los puntajes no entiendo si debemos asumir que se accederá a este desde syllabus o desde nuestro repositorio personal.

**Comment by DCCollao** [comment]
El archivo de puntajes estará en la carpeta de la tarea 0 en tu repositorio personal.

**Comment by jo00** [comment]
Estoy confundida porque en el enunciado sale que deberia enviarse a .gitignore entonces en rigor cuando lo subamos no estaria ahi o si?:(

**Comment by DCCollao** [comment]
Cuando lo suban no debería estar.
Al momento de ejecutar su tarea los ayudantes tendremos una copia local de `puntajes.txt`. Esa copia la pondremos dentro de las carpetas de sus tareas, que habremos descargado.

**Comment by jo00** [comment]
ok muchas gracias, no me habia quedado muy claro eso .
