### ISSUE TITLE
Duda conectar tres ventanas a un metodo de una clase

### ISSUE THREAD

**Issue by ccellcynthia** [IIC2233/Syllabus#211]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, tengo un problema al tratar de conectar 3 ventanas (que corresponden a los 3 ambientes del juego) a un metodo de una clase en el backend. Al parecer la misma señal que envio del backend al frontend no puede conectarse a las 3 ventanas al mismo tiempo, que deberia hacer?, gracias!

**Comment by Emiliax16** [comment]
Hola @ccellcynthia ! una solución rápida que se me ocurre es simplemente que generes un flujo de condiciones para saber cuál ambiente se eligió. Tu señal puede contener un string que haga referencia a esto y luego corroborrar a qué ventana quieres conectarte y ahí haces la conexión sólo a una y no a las tres. O bien, creas 3 señales diferentes dependiendo del ambiente y realizas el mismo procediminto para saber a cuál ventana en específico quieres conectarte. Saludos.
