### ISSUE TITLE
Duda clase Item

### ISSUE THREAD

**Issue by francorreaandrades** [IIC2233/Syllabus#211]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!! 
Tengo una duda respecto a si es necesario crear una clase Item o si simplemente el método evolucionar de los diferentes tipos de combatiente puede recibir un string con el tipo de item que se esta adquiriendo. 

En caso de tener que crear una clase, puede ser una clase madre que solo tenga el atributo self.nombre indicando el tipo de item o tiene que tener algún método y/o más atributos definidos?? Que en el enunciado se especifica que hacen los diferentes tipos de item sobre los combatientes pero no se expresa nada respecto a las caracteristicas propias que debiese tener esta clase.

**Comment by CrisDonosoMaass** [comment]
Hola!

En la pauta en la sección de "Entidades"->"Items",  indica "Modela correctamente la clase Item, utilizando los contenidos de OOP". Por lo tanto sí debe ser una clase, respecto a como crearla queda a tu criterio como hacerlo.

**Comment by BenjaMedinaPUC** [comment]
Hola, sumándome a la pregunta, o sea si creo las clases objetos pero que no tenga definidas ni atributos ni métodos pero que cumpla con el contenido de OOP ¿significa que cumple con el objetivo de la tarea? 

algo como

class xxxx:
    pass

**Comment by CrisDonosoMaass** [comment]
> Hola, sumándome a la pregunta, o sea si creo las clases objetos pero que no tenga definidas ni atributos ni métodos pero que cumpla con el contenido de OOP ¿significa que cumple con el objetivo de la tarea?
> 
> algo como
> 
> class xxxx: pass

Hola! No, para que se considere una clase correcta debe tener al menos un atributo o un metodo. Una clase vacía no va a hacer nada a nivel de código. 

Si te está quedando una clase vacía probablemente estás usando más clases de las necesarias para modelar items.

**Comment by BenjaMedinaPUC** [comment]
Vale, entonces para que me quede claro, por enunciado debo incorporar una clase Item la cual debe estar incorporado con OOP y que a la vez el método de la Clase Guerrero pueda recibir esa Clase instanciada como parámetro?

**Comment by CrisDonosoMaass** [comment]
Exacto, después para el método evolucionar tu puedes ver como implementarlo.
