### ISSUE TITLE
Bomba Diamante radio 2

### ISSUE THREAD

**Issue by alejita97** [IIC2233/syllabus#212]
tengo una duda la visualización de una bomba Diamante de radio dos se vería como una cruz:
" ", "X", " ",
"X", "X", "X",
"  ", "X", " ",
o como un cuadrado??  
"X", "X", "X",
"X", "X", "X",
"X", "X", "X",
De antemano muchas gracias :)

**Comment by jitorcas** [comment]
Hola! @alejita97 

Una bomba diamante radio 2 se vería como una cruz. Tal como lo pusiste en el primer ejemplo.

Éxito en la tarea! ⚓️
