### ISSUE TITLE
Usos de valores numéricos en la tarea

### ISSUE THREAD

**Issue by kylevon** [IIC2233/syllabus#212]
Buenas tardes profesores, ayudantes y compañeros,
En el enunciado de la tarea dice: 
>Su tarea **no debe contener ningún valor numérico en su código, sino que todos ellos deben estar en parametros.py. No respetar esta indicación provocará un descuento.**

Mi pregunta es:
en caso de parámetros como:
```self.setGeometry(0, 0, PARAMETRO1, PARAMETRO2)```
¿debo poner 0 en un parámetro LEFT y 0 en un parámetro TOP o puedo simplemente usar 0 en mi código?
Además en códigos como:
```while i>0:```
¿también debo poner 0 en un parámetro ZERO?
y si quiero iterar algo dos veces:
for i in range(2)
¿también debo poner esos elementos en parámetros? (Esto es para el GUI inicial)

**Comment by KnowYourselves** [comment]
Hola @kylevon!

Todo valor que no cambie como funcione tu tarea no tiene por que ir en `parametros.py`. En este archivo tiene que ir todo valor que al ser cambiado cambie de alguna forma significativa el funcionamiento de tu programa. 

Es decir, no habrá ningún descuento asociado a ocupar valores numéricos en los contextos que mencionas.

Éxito en la tarea!
