### ISSUE TITLE
Duda parametros

### ISSUE THREAD

**Issue by Afro27** [IIC2233/syllabus#212]
Debemos ajustar los valores de parametros.py hasta que al testear el juego, el juego este "balanceado". O simplemente los rellenamos sin preocuparnos de que el juego quede balanceado, como por ejemplo que los automoviles sean considerablemente mas rapidos qie las bicicletas o cosas por el estilo.

**Comment by DCCollao** [comment]
Hola! 
No es necesario que quede balanceado, pero eso podría facilitar tus pruebas de la tarea 👀

Al momento de corregir usaremos distintos valores para los parámetros que mencionas.
Éxito!
