### ISSUE TITLE
Duda archivo Unidades Disponibles

### ISSUE THREAD

**Issue by francorreaandrades** [IIC2233/Syllabus#212]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!!

En la seccion 6.2 del enunciado dice: "NO puedes asumir que el archivo tendrá un gato de cada tipo básico o que el archivo no contendrá gatos de los tipos que no pueden ser comprados, por lo que deberás asegurarte de que el archivo es correcto al momento de cargarlo, imprimiendo un mensaje de error y terminando el programa si no es el caso."

Eso significa que si en el archivo unidades.txt vienen 10 gatos y solo 1 es inválido el programa termina igual?? O simplemente debo considerar los gatos que me entregan que si cumplan los requisitos establecidos, es decir, solo los válidos?? 

Admás, en caso de tener un archivo unidades.txt válido, si este tiene solo 2 gatos de tipo mago disponibles y compro 1, este se elimina de la lista de posibilidades de compra en el futuro?? O si quisiera comprar en 1 misma ronda 3 gatos de tipo mago lo puedo hacer aunque se "repitan" las instancias??

**Comment by Gcamposbriceno** [comment]
Hola!

Con respecto a tu primera pregunta, el enunciado dice que en el caso de que los valores de alguno de los gatos sea inválido, se debe tomar el archivo completo como inválido.

Acerca de tu segunda pregunta, puedes comprar cada gato una sola vez. Por lo que debes asegurarte que los gatos ya comprados no sigan siendo elegibles para futuras compras.

Saludos!!

**Comment by francorreaandrades** [comment]
Pero en caso de perder contra alguno de los ejercitos enemigos, los gatos disponibles se reinician asi como cuando la cantidad de oro vuelve a ser ORO_INICIAL?? O si ya compre los 6 gatos que se instancian en el ejemplo que se da del archivo unidades.txt no hay más opciones de compra hasta salir del programa?? 

En caso de que se tenga que hacer lo dicho en la 2da opción, si no puedo comprar más gatos y no tengo integrantes en mi ejercito, se pierde automaticamente y se termina al programa??
