### ISSUE TITLE
Formulario de atraso

### ISSUE THREAD

**Issue by DaniFantasy** [IIC2233/Syllabus#212]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Contenido

Sobre el formulario de atraso, debe subirse el hash del ultimo commit creado no?,

**Comment by Hernan4444** [comment]
Hola @DaniFantasy 

Debe subirse el hash del commit que te interesa que revisemos. Generalmente es el último, pero si haces otro que no quieres que te revisen, entonces ahí sería el antepenultimo. Lo importante es que el commit esté dentro del plazo máximo, pero puede ser el que tu quieras.

Saludos!
