### ISSUE TITLE
Probabilidad de descubrimiento Cura

### ISSUE THREAD

**Issue by malopez16** [IIC2233/Syllabus#212]
Hola!
En el calculo de probabilidad del descurbrimiento de la enfermedad, se utiliza la cantidad de gente infectada. Se refiere a todos los que se infectaron y luego podrían haber fallecido? o los vivos e infectados a la vez?  Suena lógico que sea los vivos infectados, pero al reemplazar valores (por ejemplo, en un mundo de 100 personas, en el que han muerto 99 y hay 1 infectado), no me hace coherencia (como si nunca fuera a llegar la probabilidad a 1),

Gracias :)

**Comment by iqacevedo** [comment]
Hola tal como tú dices puede que nunca llegue a ser 1, lo cual ocurre porque se trata de una probabilidad. Lamentablemente puede existir el caso de que nunca se descubra la enfermedad y todos mueran :(

Saludos !
