### ISSUE TITLE
Duda sobre frontend y backend

### ISSUE THREAD

**Issue by FabriRandon** [IIC2233/Syllabus#212]
Estimados.

Quería consultar porque en mi código tengo a los aliens, la mira, etc... en una carpeta de entidades donde implementan la capacidad de movimiento. Mi duda es si esta implementación está mal y debería ir en el frontend? porque las entidades las tengo en el backend.
Saludos y muchas gracias.

**Comment by Emiliax16** [comment]
Hola @FabriRandon . La implementación que mencionas estaría correcta. Recuerda que el frontend lleva todo lo que el usuario directamente observa e interactua, como lo son las ventanas y sus elementos. Saludos!
