### ISSUE TITLE
Duda ejercicio 2.7 - semana 4

### ISSUE THREAD

**Issue by Piolawa** [IIC2233/syllabus#212]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Hola,
No entiendo que hacer con los errores al capturarlo, colocarle un pass?
Y al correr el código me sale:
![image](https://user-images.githubusercontent.com/80898544/114597989-62e60500-9c5f-11eb-9b47-df2f64bb0804.png)

No entiendo que significa el error y como solucionarlo :c

**Comment by camilagonzalezp** [comment]
¡Hola @Piolawa!

En ese ejercicio el principal objetivo es detectar los posibles errores, levantar los errores correspondientes en ```guardar_lineas()```, y luego capturar dichos errores en el ```main``` del programa. En esta última parte el foco está en capturar los errores más que en qué hacer luego de capturarlos, por lo que podrías imprimir el error para tener más información o dejar el pass, pero más que nada lo importante es capturarlos correctamente para que el ciclo pueda seguir iterando sobre la lista de textos.

Por otra parte, con respecto al error que mencionas, este no tiene relación con la dinámica del ejercicio en sí, sino que se produce por un error específico en la forma en que estás manejando el archivo, dado que probablemente al abrirlo no especificaste el encoding con el que quieres leer el archivo. Para esto te sugiero utilizar ```utf-8```, de la forma ```with open(path, "rt", encoding="utf-8") as archivo```. A lo mejor esto pueda parecer un poco confuso ahora, pero te va a hacer mucho más sentido cuando veas la materia de Input/Output y Bytes. De cualquier forma si quieres saber un poco más sobre esto me puedes decir y te cuento :)

Avísame como te va y si hay algo que no te queda claro no dudes en volver a preguntar 🙌🏻

¡Éxito! ✨
