### ISSUE TITLE
Entregable T02

### ISSUE THREAD

**Issue by bmorrisc** [IIC2233/Syllabus#212]
Hola! 
Hay algo que no me queda claro sobre el entregable de la tarea... Entiendo que hay que especificar algoritmos para realizar consultas de afinidad, es decir, esto se refiere a las consultas especificadas en la sección 4.1.2? De ser así sería necesario especificar el procedimiento a seguir para cada tipo de consulta o se puede dar una idea general de acuerdo a un algoritmo que todas las consultas tengan en común?

**Comment by monicabelen** [comment]
Hola! Sí, se refiere a las consultas de la sección 4.1.2. Puedes dar una descripción general de cómo lo adaptarías a las consultas pedidas.

**Comment by mramirez7** [comment]
Hola, para el entregable puedo asumir que el grafo ya está instanciado? y explicar 2 algoritmos para recorrerlo y contestar a las consultas nomás? O explico también como generar el grafo?
