### ISSUE TITLE
duda mostrar puntajes

### ISSUE THREAD

**Issue by eliasbruchfeld** [IIC2233/syllabus#213]
Hola! tengo 2 preguntas respecto a los puntajes que se muestran. 
¿que pasa si el 5to y el 6to mejor puntaje son iguales? ¿tengo que mostrarlos a ambos a pesar de que solo se pide los mejores 5?

Y la otra pregunta es si dos personas se ponen el mismo nombre, ¿esta bien mostrar sus puntajes como usuarios distintos?

**Comment by DCCollao** [comment]
Esta duda fue resuelta en #146. Si luego de leer esa issue te queda alguna duda, hazla en los comentarios.
