### ISSUE TITLE
Duda traccion_ruedas

### ISSUE THREAD

**Issue by Afro27** [IIC2233/syllabus#213]
Si el atributo ruedas de un vehiculo es 30, su traccion_ruedas tendra un valor de 30 o depende de cuantas ruedas tenga el vehiculo, por ejemplo oara un automovil de 4 ruedas: 
traccion_ruedas = 30 * 4 ruedas?
o para una bicicleta: traccion_ruedas = 30 * 2 ruedas?
O simplemente la traccion_ruedas es igual al valor dado de ruedas sin importar la cantidad de ruedas del vehiculo?

**Comment by gatochico** [comment]
Hola!
La `traccion_ruedas` es igual al valor dado, sin importar la cantidad de ruedas del vehículo, por lo que tu último caso sería el correcto. En la issue #158 se especifica para cual cálculo es útil el número de ruedas y para cual no.
Saludos!
