### ISSUE TITLE
Dudas sobre afirmaciones en control 2

### ISSUE THREAD

**Issue by minsoos** [IIC2233/syllabus#213]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, quería preguntar por tres afirmaciones del control 2 y 3:
*Control 2*
1. Si creamos en una subclase Jet que hereda de una clase Aeronave, ¿cuál(es) de las siguientes afirmaciones es/son verdadera(s) respecto a la subclase?
         Si ambas clases definen un método volar(), al hacer Jet().volar() se llamará primero al método volar de la clase padre, y 
         luego al de la clase hija. (Creo que es falsa y aparece como verdadera)

2. ¿Cuál(es) de las siguientes afirmaciones es/son falsa(s) en torno al concepto de properties?
         Toda property debe tener un getter y un setter.  (Esta creo que es falsa y aparece como verdadera).

*Control 3*
1. SystemExit , KeyboardInterrupt y SyntaxError heredan de la clase BaseException (Esta se marca como falsa y creo que es verdadera)

*Esta es una duda surgida del control 3*
Al hacer el control, me di cuenta que un return en un finally siempre se prioriza a un return en cualquier otra parte del código. ¿Hay otro comportamiento "anómalo" de finally que no sepamos?

Gracias de antemano.

**Comment by aaossa** [comment]
Hola @minsoos , mientras revisamos los controles, ¿podrías hacer tu última pregunta (que sí es sobre contenidos) en una *issue* aparte? Así en esta vemos el tema del control. Por ahora me voy a dejar asignado y en algún momento volvemos con una respuesta al respecto 😅
