### ISSUE TITLE
[Semana 5] Ejercicio propuesto 2.1 Ayudantes en restorán

### ISSUE THREAD

**Issue by rodrigooflores** [IIC2233/Syllabus#213]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Realizando el primer ejercicio propuesto de concurrencia, intenté solucionarlo utilizando **lock_global** afuera de la definición de la función **atender_pedidos(cola, clientes, lock_global)**, usando **lock.acquire()** y **lock.release()** justo afuera del **while** de esa función. Lo que hice resolvió el problema de la coordinación, pero al imprimir el nombre del **thread** para saber qué trabajador hacía el pedido, obtuve que solo el trabajador 1 preparaba los pedidos y no permitía que los otros trabajadores participen. Me gustaría saber si hay alguna manera de arreglar esto, ya que no creo que el objetivo del ejercicio sea que solo un trabajador se quede preparando los pedidos. Adjunto una imagen de el output (configuré la función para que el pedido no se le caiga nunca).
Saludos!

![Duda_propuesto_concurrencia](https://github.com/IIC2233/Syllabus/assets/141890277/806012cd-6413-49b4-8843-047a8e38cdf7)

**Comment by mskdancers** [comment]
Hola! ¿Cómo están posicionados el ```lock.acquire()``` y el ```lock.release()```? Si ambos están afuera del while tendrás el problema de que el primer thread que llegue va adquirir el ```Lock```, y tendrá que ejecutarse todo su ciclo ```while``` hasta que el ```Lock``` sea liberado, es decir se va a llevar toda la cola para él solo, ya que el ```while``` se ejecuta mientras queden elementos en la cola 👀. Podrías mandar una foto de tu código actual para poder ayudarte mejor. Saludos!

**Comment by rodrigooflores** [comment]
> Hola! ¿Cómo están posicionados el `lock.acquire()` y el `lock.release()`? Si ambos están afuera del while tendrás el problema de que el primer thread que llegue va adquirir el `Lock`, y tendrá que ejecutarse todo su ciclo `while` hasta que el `Lock` sea liberado, es decir se va a llevar toda la cola para él solo, ya que el `while` se ejecuta mientras queden elementos en la cola 👀. Podrías mandar una foto de tu código actual para poder ayudarte mejor. Saludos!

Claro comprendo que ese es el problema, pero no sé muy bien como se podría arreglar. Aquí adjunto una foto de mi código actual. Saludos :)
![Duda_propuesto_concurrencia_código](https://github.com/IIC2233/Syllabus/assets/141890277/bffaf27f-fabc-46c5-88f4-85686779278b)

**Comment by mskdancers** [comment]
Prueba metiendo el ```acquire``` y ```release``` del ```Lock``` dentro del ciclo ```while```. Por como está hecho el código, el trabajador primero lee el primer elemento de la cola, y después (si es que no se le cayó), saca el elemento de la cola. Por eso debes asegurarte de que si un trabajador lee un elemento de la cola, su ```thread``` no se pause antes de que saque el pedido de la cola, lo que podría causar que dos trabajadores entreguen el mismo pedido.
Además, ya teniendo el ```Lock``` implementado, tienes que asegurarte que la cola no esté vacía al momento de que  un trabajador saque un pedido de ella 👀. Avísame como te va!

**Comment by rodrigooflores** [comment]
No me funcionó :sweat_smile:, me hace sentido que el `acquire` deba ir dentro del `while` y antes de que un trabajador empiece a preparar un pedido de un cliente (`cola[0]`) específico, y que el `release` vaya una vez que lo preparó para que otro trabajador pueda empezar a preparar otro pedido, mi código quedo así:
```python
lock_global = threading.Lock()
def atender_pedidos(cola, clientes, lock):
    while len(cola) > 0:
        nombre = threading.current_thread().name
        lock.acquire()
        print(f'Pedidos restantes: {len(cola)}')    
        cliente, comida = cola[0]
        print(f"Yo {nombre} prepararé la comida: {comida} para {cliente}")
        time.sleep(1)
        if randint(1, 1) == 1:
            bandeja = clientes[cliente]
            bandeja.append(comida)
            print(f"Pedido de {comida} entregado a {cliente}")
            cola.popleft()
        else:
            print("¡Se me cayó!")
        lock.release()
```

Pero obtengo el mismo resultado de antes (solo trabajador 1 prepara pedidos) y además luego el trabajador 2 intenta preparar un pedido, entrando al `while` a pesar de que `len(cola)` es 0, provocando que se salga del rango como muestro a continuación, supongo que es por algo relacionado con el `aquire` tal vez(?.
![Duda_propuesto_concurrencia_nuevo_output](https://github.com/IIC2233/Syllabus/assets/141890277/c2f52846-4766-4106-8486-4df417f47a16)

**Comment by mskdancers** [comment]
Claro, me parece que el problema que tienes ahí no es de modelación estrictamente sino que simplemente la primera ```Thread```, como es la que se ejecuta primero, está haciendo todo muy rápido y las otras threads no alcanzan a agarrar el ```Lock```. A veces los ```Threads``` son medios impredecibles en eso, ya que no sabes cuando se va a pausar uno para dar paso al otro. Si cambias el ```sleep``` para que espere _antes_ de adquirir el ```Lock```, me parece que debería funcionar.

```python
lock_global = threading.Lock()
def atender_pedidos(cola, clientes, lock):
    while len(cola) > 0:
        time.sleep(1)
        nombre = threading.current_thread().name
        lock.acquire()
        print(f'Pedidos restantes: {len(cola)}')    
        cliente, comida = cola[0]
        print(f"Yo {nombre} prepararé la comida: {comida} para {cliente}")
        if randint(1, 1) == 1:
            bandeja = clientes[cliente]
            bandeja.append(comida)
            print(f"Pedido de {comida} entregado a {cliente}")
            cola.popleft()
        else:
            print("¡Se me cayó!")
        lock.release()
```
Ojo que con esta modelación todavía tendrás el problema de acceder a una lista vacía, pero eso puedes evitar que pase usando una condición (i. e. si la lista no tiene elementos, entonces no queremos acceder a ella).

**Comment by rodrigooflores** [comment]
Muchísimas gracias! con eso lo pude resolver :blush:, el código solucionando lo de la lista vacía quedó de la siguiente manera :handshake::
```python
lock_global = threading.Lock()
def atender_pedidos(cola, clientes, lock):
    while len(cola) > 0:
        time.sleep(1)
        nombre = threading.current_thread().name
        lock.acquire()
        print(f'Pedidos restantes: {len(cola)}')    
        if len(cola) > 0:
            cliente, comida = cola[0]
            print(f"Yo {nombre} prepararé la comida: {comida} para {cliente}")
            if randint(1, 1) == 1:
                bandeja = clientes[cliente]
                bandeja.append(comida)
                print(f"Pedido de {comida} entregado a {cliente}")
                cola.popleft()
            else:
                print("¡Se me cayó!")
        lock.release()
```
![Duda_propuesto_concurrencia_solucionada](https://github.com/IIC2233/Syllabus/assets/141890277/410a7dfd-fff8-4e86-a300-b4177b9f90dc)
