### ISSUE TITLE
Duda, Formulario de entrega atrasada

### ISSUE THREAD

**Issue by gabrielgngora** [IIC2233/Syllabus#213]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Contenido

Consultita, quiero entregar la tarea con atraso y usaré un día de descuento, el tema es que el formulario me pide obligatoriamente escribir el último commit a revisar y pues aún no existe ya que no he subido la versión definitiva de la tarea. Que hago?

**Comment by Hernan4444** [comment]
Hola @gabrielgngora 

El descuento es aplicado en base de la fecha de push del commit, no cuando respondes el formulario. Por lo tanto, solo es necesario asegurar que el commit sea hecho dentro de la fecha, pero el formulario puede ser respondido ahora o incluso mañana y el descuento se calcula en función de cuando hiciste push.

Saludos!
