### ISSUE TITLE
Puntaje Caminos

### ISSUE THREAD

**Issue by Pipelao** [IIC2233/Syllabus#213]
Hola, buenas :)

Quería preguntar qué significa borde de la grilla, lo mencionan en la parte de puntajes en caminos, es por ejemplo, ¿un camino que va desde una ciudad hasta el borde del tablero?

Y mi otra pregunta es ¿qué puntaje se asigna cuando se unen dos ciudades completas?, o ¿no se pueden unir dos ciudades completas?

De ante mano, gracias.

**Comment by fnquinteros** [comment]
Hola! Con respecto a tu primera pregunta, el borde de la grilla es justamente lo que dices (el borde del tablero). Con respecto a la segunda, como no está especificado en el enunciado, queda a su criterio la asignación de puntaje en ese caso. Saludos!

**Comment by Pipelao** [comment]
Ahhh ok, muchas gracias :)

**Comment by Regenschrim** [comment]
¿También queda a nuestro criterio cuando un río une dos ciudades completas? ¿O simplemente no asignamos puntaje, ya que solo habla de conexiones con al menos una ciudad incompleta?
