### ISSUE TITLE
Duda sobre mensaje de error o pop-up al ingresar un nombre de usuario incorrecto.

### ISSUE THREAD

**Issue by NicolasOlmosQuiroga** [IIC2233/Syllabus#213]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

¡Hola!, en la parte de ventana principal aparece lo siguiente:

"Si el jugador desea iniciar una partida nueva, se deberá verificar si el nombre de usuario cumple la restricción alfanumérica y que no sea vacío. En el caso de que no cumpla, se deberá notificar mediante un mensaje de error o pop-up"

Y me surgio la duda si es que es necesario que aparezca una ventana pequeña de error o simplemente puede mostrarse un mensaje en la casilla donde se ingresa el usuario diciendo que este es incorrecto.

Eso, ¡muchas gracias!

**Comment by Emiliax16** [comment]
Hola @NicolasOlmosQuiroga ! precisamente a eso nos referiamos con _"se deberá notificar mediante un mensaje de error o pop-up"_ 😸 Puedes simplemente mostrar en el label que el nombre ingresado es incorrecto, o bien mostrar una mini ventana (pop-up) diciendo que el nombre es incorrecto. Saludos!
