### ISSUE TITLE
Importar Qrect de QtCore

### ISSUE THREAD

**Issue by jfpena1** [IIC2233/syllabus#213]
Hola al tratar de importar Qrect de QtCore, me sale el siguiente error:

ImportError: cannot import name 'Qrect' from 'PyQt5.QtCore' (C:\Users\Julio\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyQt5\QtCore.pyd)

![image](https://user-images.githubusercontent.com/39381457/57660722-edc2ae80-75b5-11e9-930c-8959c7074bcf.png)

He tratado de buscar en google, pero no soy capaz de solucionarlo, PyQt me funciona porque he corrido los contenidos subidos. Muchas gracias!

**Comment by KnowYourselves** [comment]
Hola @jfpena1!

Tu error se debe a que los módulos de `PyQt` empiezan todos con mayúscula, es decir, le módulo que quieres importar se llama **QRect**, no **Qrect**.

Espero haberte ayudado!
