### ISSUE TITLE
Fin del combate

### ISSUE THREAD

**Issue by francorreaandrades** [IIC2233/Syllabus#214]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!!
Con respecto al fin del juego, cuando el ejercito del usuario gana las 3 rondas seguidas contra los ejercitos enemigos se imprime un mensaje anunciado su victoria?? Además, se debe cerrar automáticamente el programa o se vuelve al menú de inicio??

**Comment by CrisDonosoMaass** [comment]
Hola!

Queda a tu criterio implementar un print de victoria, pero creo que es útil implementarlo de todas maneras para saber que termino la partida.

Respecto a tu segunda pregunta, tú puedes decidir que implementar, puedes cerrar el juego automáticamente, preguntarle al jugador si quiere jugar otra partida, etc. 

Espero que te sirva!
