### ISSUE TITLE
Restricciones para crear EDD propias

### ISSUE THREAD

**Issue by fgbruna** [IIC2233/Syllabus#214]
No me queda claro que cosas si está permitído usar para hacer nuestras estructuras de datos,por que por ejemplo si aprovecho lo dicho en [#195](https://github.com/IIC2233/Syllabus/issues/195) puedo siempre inicializar un objeto del tipo `MiLista` usando uno del tipo `list` sin preocuparme de inicializarlo yo a mano desde cero, y me parece que esto es casi análogo a heredar de la clase `list`.
En resumen, para crearlas solo tenemos a disposición las clases `int`,`str` y los métodos de `object` ?

**Comment by andresfdezc** [comment]
Lo que #195 te está tratando de decir que si usas un método de Python (no escrito por ti) que retorna una lista, diccionario, etc, tienes que inmediatamente convertirlo en alguna de tus estructuras propias antes de hacer cualquier cosa con esos datos.

Esto no significa que siempre vas a poder inicializar tu objeto `MiLista` con uno de tipo `list`. Solo podrás en el caso que describe #195 cuando se retorna de un método incluido en Python.

**Comment by behrmann97** [comment]
Hola,¿ puedo utilizar una lista dentro de uno de los métodos de Mylist, la cual no es ni retornada ni entregada como parámetro, sino que se usa para dentro de la misma función tener un orden?

**Comment by andresfdezc** [comment]
@behrmann97 No, porque no se pueden usar listas de Python.

**Comment by behrmann97** [comment]
Y es posible usar esto?

![aaa](https://user-images.githubusercontent.com/26407766/30076873-b5f2c30e-9250-11e7-9d7b-a665be4c763f.png)

**Comment by stephichau** [comment]
@behrmann97 no, revisa el ejemplo de la issue #195 :)

**Comment by Kitaps** [comment]
Y no se puede usar una lista/tupla/diccionario de python para guardar los tipos y cantidad de pieza?

**Comment by andresfdezc** [comment]
@Kitaps No, porque está prohibido usarlos.

**Comment by Kitaps** [comment]
gracias :(
