### ISSUE TITLE
Señales Distribución del puntaje

### ISSUE THREAD

**Issue by jahernandez2** [IIC2233/Syllabus#214]
Hola! En la Distribución de puntaje de la tarea aparece que se evaluará el correcto uso de señales para funciones como crear una nueva partida e ingresar a la ventana de ranking. Esto se pude hacer perfectamente sin el uso de estas, ya que no hay nada que emitir a través de las señales, así que quería sabre si, por un lado es estrictamente necesario ya que sería complicarse de más y en caso de que lo sea, como puedo utilizar señales sin nada que emitir. 
Saludos y gracias de antemano.

**Comment by Emiliax16** [comment]
Hola @jahernandez2 . El no uso de señales tendrá una penalización en el puntaje del item específico que lo evalua, por lo que considera que hacerlo de otra manera no te dará el puntaje completo. Por otro lado, las señales facilitan la comunicación entre frontend y backend, así que veo más complicado el realizar la tarea sin estas 🤔 .

Respecto a tu segunda pregunta, si sólo quieres usar una señal y que ésta no contenga nada, basta con no darle ningún argumento a la hora de definirla (ej: senal = pyqtSignal()). Por el contrario, si necesitas que se envie algún tipo de información, le das un argumento declarando el tipo de variable que enviaras. Para esto te recomiendo repasar la semana 07 de los contenidos del curso, en específico el contenido **eventos y señales**. Saludos.

**Comment by jahernandez2** [comment]
Pero entonces para simplemente abrir (por ejemplo) la ventana de ranking, no bastaría con utilizar lo de la siguiente imagen que está en la materia de señales, pero no usa señales? No entiendo cual sería el rol del backend y la señales en este caso por ejemplo, en donde solo hay que abrir una ventana si se decide esa opción. 

![Progra avanzada señales](https://user-images.githubusercontent.com/62116520/169710759-32b16e26-45c9-48ae-8234-4b8d8e53fccd.png)

**Comment by jahernandez2** [comment]
Gracias!
