### ISSUE TITLE
No puedo importar modulos en VSCode

### ISSUE THREAD

**Issue by fmitjans** [IIC2233/syllabus#214]
Hola, cuando trato de importar un módulo en Visual Studio Code el programa no me lo reconoce (el módulo está en la misma carpeta). Cuando corro el mismo código en IDLE  me funciona bien.

![VSC](https://user-images.githubusercontent.com/48566055/64559857-9d6a1c00-d31d-11e9-956f-230c85ea5ead.png)

**Comment by dgzmr** [comment]
@fmitjans a lo mejor no tienes al autoguardado activado. A mí me pasó eso.

**Comment by KnowYourselves** [comment]
Hola @fmitjans!

Cómo estás ejecutando tu código?

Quedo atento!

**Comment by fmitjans** [comment]
Lo estaba ejecutando con click derecho -> "Run Current Text File", "Run Python File in Terminal" y "Run Selection/Line in Python Terminal".
Ahora lo ejecuto en el terminal y me funciona bien
