### ISSUE TITLE
T00 - BOMBAS ESPECIALES - TURNOS Y "SOBREESCRIBIR"

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2233/syllabus#214]
Hola! ¿Cuando le doy a un barco con una bomba especial se repite turno? Entiendo que no puedo lanzar inicialmente una bomba especial donde ya he lanzado una bomba antes, sin embargo ¿se pueden "sobreescribir" los lanzamientos anteriores con el alcance de estas bombas especiales?
Desde ya muchas gracias!

**Comment by vicentevegaulloa** [comment]
Hola @ignacioarteaga99 !

Respecto a lo de repetir turno, esto también aplica a bombas especiales, por lo que si le das a un barco enemigo con una bomba especial, debes repetir turno. Respecto a la otra pregunta, no hay problema con que el alcance de las bombas especiales incluya celdas donde ya se disparó. Lo único que importa es que la coordenada de origen de tu bomba no haya sido utilizada previamente. 😄

**Comment by ignacioarteaga99** [comment]
Muchas gracias!
