### ISSUE TITLE
Tamaño mapas

### ISSUE THREAD

**Issue by egarnham1** [IIC2233/syllabus#214]
Hola! nuestro programa tiene que soportar mapas de otro tamaño que el de los ejemplos? (son todos del mismo)

**Comment by hbkim94** [comment]
Hola!

Tal y como dices, sus programas tienen que efectivamente soportar mapas de otros tamaños (por lo que tienen que sí o sí hacer que su programa lea los elementos del mapa directamente de los archivos que les entregamos para poder armarlo).

Mucho éxito en la tarea!

**Comment by quememo** [comment]
que tanto más grande podrían ser los mapas? Ya que dependiendo de eso, creo que podría faltarme resolución en mi pantalla para ver todo el juego

**Comment by hbkim94** [comment]
Hola @quememo ,

No te preocupes, piensa que serán de tamaños muy similares a los que ya te entregamos; lo más importante es que tu programa funcione independiente de dónde pongamos los caminos, obstáculos y la base (respetando lo que se dice en el enunciado). Más aún, por eso se te pide que tengas el tamaño de las casillas dependiendo del parámetro N, cosa de que podamos cambiar el tamaño de las casillas de ser necesario.

**Comment by quememo** [comment]
Gracias!
