### ISSUE TITLE
Avance de la infeccion

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#214]
3.3.1 Tengo una duda con respecto a la formula para que avance la infección:
Si es que hay mascarilla sería: 0.3 * tasa_contagiosidad * randint(0, 6)
Si no hay mascarilla: tasa_contagiosidad * randint(0, 6)
 ¿Es así? ... De serlo: Hay veces que los números dan fraccionarios, ¿se aproximan para arriba o abajo? o simplemente no se aproximan...
De no ser así: ¿Cuál sería la formula?

**Comment by nivek0o0** [comment]
Yo creo que la fórmula es así como lo dices y que puedes aproximar el número como tu quieras pero dejarlo especificado en el Readme.

**Comment by acrojas2** [comment]
no se si solo me pasa a mi, pero el avance de la infección es muy muy lento :( , onda la probabilidad de contagio a otros países es muy muy baja...

**Comment by Veenty** [comment]
@acrojas2 has jugado el juego? Tienen que haber millones de infectados en un pais para que llegue a otro.

**Comment by stephichau** [comment]
@acrojas2 da lo mismo, pero especifícalo en el README. Sobre el avance de la infección, es normal que sea así.

Saludos!
