### ISSUE TITLE
importar imagenes Designer

### ISSUE THREAD

**Issue by diegocostares** [IIC2233/Syllabus#214]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Estaba probando a hacer menus con Designer y al importarlo como nos enseñaron me arrojo un error y no sé cómo solucionarlo... lo mando por acá por si alguien lo identifica... Creo que está relacionado con lo de cargar imágenes dentro de designer, pues puse una ruta a una imagen y esta no funciona (se guardó en formato res.qrc), estoy usando el navegador de recursos para cargar las imágenes (tal vez sea eso). Adjunto el error que me salió en consola y capturas de lo que hice.

<p align="center"><img src="https://i.ibb.co/tpsGLVv/1.png" height="150px" /></p>
<p align="center"><img src="https://i.ibb.co/rsHzgh9/2.png" height="150px" /></p>
<p align="center"><img src="https://i.ibb.co/jvwhHBZ/3.png" height="150px" /></p>

ERROR:
```
 File "/Users/diegocosta/Downloads/Programacion/test/ventanatest/frontend/ventana_login.py", line 14, in <module>
    window_name, base_class = uic.loadUiType("designer/pantalla_login.ui")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PyQt5/uic/__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "<string>", line 121, in <module>
ModuleNotFoundError: No module named 'res_rc'
```

**Comment by cegalleta** [comment]
¡Hola!

Por lo que pude entender de [aquí](https://stackoverflow.com/questions/41301204/importerror-no-module-named-resource-rc) efectivamente el problema se origina al cargar la imagen desde Qt-Designer, ya que ocupas un archivo con extensión .qrc que almacena los recursos, pero en python se requiere que la extensión sea .py. Puedes tratar la solución del link, cambiar la extensión manualmente o podrías tratar de settear el fondo directamente en el código en vez de usar Designer para ello (sería lo que yo haría). Esto último se puede realizar mediante el método ```.setStyleSheet``` de un widget o de tu ventana poniendo los mismos parámetros que en Designer.


¡Espero que te sirva!

**Comment by diegocostares** [comment]
Muchas gracias! Justamente había hecho lo de .setStyleSheet!

**Comment by cegalleta** [comment]
Ya!! Qué bueno!! Lamento no haber contestado antes :(.
Éxito en la tarea!
