### ISSUE TITLE
Duda sobre uso de .join()

### ISSUE THREAD

**Issue by juanivegam** [IIC2233/Syllabus#214]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola, que me surgio una duda sobre el uso del método .join. Cuando yo hago un_thread.join( ), es decir no le entrego argumentos a join, se ejecuta predeterminadamente sobre el mainthrad? Y si yo quisiera ejecutarla sobre otro thread, yo lo debo incluir dentro del parpentesis del join?

Muchas gracias de antemano

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by gatochico** [comment]
Hola @juanivegam!

El único argumento que recibe el método `.join()` de los threads es el valor de `timeout`, que es el que puede definir un máximo de tiempo a esperar antes de seguir. Según la documentación de python, el método no recibe nada más que eso.

Sin embargo, si es posible hacer que un thread que no sea el principal espere a otro con `join()` . Veamos primero este ejemplo en donde el join está en el hilo principal:
```python
import threading

def contador(tiempo):
  print("Contando...")
  while tiempo > 0:
    print(tiempo)
    tiempo -= 1
  print("Termine!")



mi_thread = threading.Thread(target=contador, args=(5,))

mi_thread.start()
mi_thread.join()

print("Estoy después del join")
```

En ese código, en el hilo principal creamos un thread que ejecuta la función contador, almacena el thread en la variable `mi_thread`, y luego lo ejecuta con `.start()` y espera a que termine con `.join()`. Lo importante de este ejemplo es que almacenamos la referencia al thread en el programa (en este caso, mediante una variable llamada `mi_thread`).

Ahora, una modificación del código anterior para que tenga dos threads, y uno espere al otro con join:

```python
import threading

def contador(tiempo):
  print("Contando...")
  while tiempo > 0:
    print(tiempo)
    tiempo -= 1
  print("Termine!")

def espera_contador(thread):
  thread.join()
  print("El otro thread terminó!")

mi_thread = threading.Thread(target=contador, args=(5,))
mi_otro_thread = threading.Thread(target=espera_contador, args=(mi_thread, ))

mi_thread.start()
mi_otro_thread.start()

mi_otro_thread.join()


print("Estoy después de que el segundo thread terminó")
```

Con esto, pudimos hacer que el segundo thread, `mi_otro_thread` (que ejecuta la función espera_contador) hiciera `.join()` del primer thread antes de terminar. ¿Cómo se hizo? Como uno de los parámetros de la función que ejecuta `espera_contador()` se envió la referencia al thread que queríamos esperar.

Entonces, como resumen, si queremos que un thread que no sea el principal espere a otro, de una forma u otra tenemos que hacer que dicho thread consiga la referencia al que queremos esperar. Esto se puede hacer pasando la referencia como parámetro de la función, o haciendo que el thread que espere sea el que cree y lance el thread a esperar, entre otras formas.

Saludos y espero haya servido!
