### ISSUE TITLE
Path relativo

### ISSUE THREAD

**Issue by tolavarria** [IIC2233/syllabus#214]
Holaaa, tengo una duda: me leí el [archivo](https://github.com/IIC2233/contenidos/blob/master/semana-00/3-paths.ipynb) de los paths, pero aún no estoy seguro si los entendí e implementé correctamente. Si todos los archivos .py los subí a la carpeta T00, al abrir archivos de texto dentro de cada .py uso el path 'archivodetexto.csv' ¿este path cuenta como path relativo? ¿y es el que debería usarse?
saludos

**Comment by KnowYourselves** [comment]
Hola @tolavarria!

Efectivamente, lo que utilizaste es un _path_ relativo. El resumen de _paths_ es el sig:

1.  **Absoluto**: Parte con `/` y empieza desde la primera carpeta del disco. Si tu programa fue ejecutado en el disco `C:` por ejemplo, intentara encontrar esa ruta desde ahí.

2. **Relativo**: Parte sin `/` y empieza desde la carpeta donde fue ejecutado el programa.

Esto quiere decir que si yo ejecuto tu programa dentro de la carpeta `T00` el path `archivodetexto.csv` sería un archivo de ese mismo nombre, en exactamente la misma carpeta que tu programa.

Espero haberte aclarado la duda!
