### ISSUE TITLE
Evaluaciones semana feuc san agustin 

### ISSUE THREAD

**Issue by Trinihi** [IIC2233/Syllabus#215]
hola! con quien puedo hablar, ya que estamos en semana universitaria feuc niver universidad y por calendario no se pueden poner tareas o evaluaciones, es mas en todos los ramo han corrido las evaluaciones para la semana que viene, ya que no pueden haber evaluaciones, por algo es que se ponen estas restricciones! si es que se puede hablar por mail aca lo dejo. mthirmas@uc.cl

**Comment by Hernan4444** [comment]
Hola,

Cómo indican las reglas del foro, 

> El foro no es un medio de reclamos. Cualquier mensaje de este tipo debe ser enviado mediante el mail de coordinación ([coordinacion.iic2233@gmail.com](mailto:coordinacion.iic2233@gmail.com)) encontrado en la página principal.

De todas formas, aquí ya se respondió la consulta:

* https://github.com/IIC2233/Syllabus/issues/174

Saludos!
