### ISSUE TITLE
Entregable

### ISSUE THREAD

**Issue by cfernandez9** [IIC2233/Syllabus#215]
En el enunciado dice que hay que entregar un entregable el 6 de septiembre, en qué consiste eso? es un diagrama de clases igual que en la tarea 1 o qué es?

**Comment by fnquinteros** [comment]
Hola! Es más bien un manual de usuario que explique cómo funcionan las estructuras de datos que implementaste. Saludos!

**Comment by AngelMatias** [comment]
Es decir, que solo tenemos hasta ese dia para programar las estructuras que utilizare ? pues si se me ocurre modificarlas o agregar otras despues de ese dia (lo cual es muy probable) no voy a poder ??

**Comment by fgbruna** [comment]
Me sumo a la pregunta de @AngelMatias , la entrega del 6 es preliminar o debe contener *todas* las estructuras con *todos* los métodos definidos que usaremos para la tarea?

**Comment by FernandoPieressa** [comment]
Hola!

La idea de hacer estas entregas preliminares en las Tareas es que ustedes piensen que necesitaran para realizar una buena tarea antes de ponerse a programar, y que después nosotros les podamos dar feedback acerca de estos para que después ustedes puedan mejorar su modelación y lograr una mejor tarea antes de que el plazo termine.

Es por esto que la idea no es que sea sus estructuras finales con todos los modelos exactos sino mas o menos como piensan crearlas y que tendrán para que nosotros podamos ayudar a mejorarlas. Estas no tienen puntaje en la evaluación como la idea es que reciban feedback que los ayude, sin embargo SI tiene descuento de no ser entregadas.

Saludos!

**Comment by mjgutierrez1** [comment]
¿A qué se refieren con que además se deben indicar los métodos que serán necesarios para el correcto modelamiento del problema? ¿Se refieren sólo a los métodos de las clases de las nuevas estructuras de datos creadas por mi, o a los métodos de todas las clases creadas para hacer la tarea?

**Comment by movaldivia** [comment]
@FernandoPieressa En un principio es entregar la idea o las funciones en código?

**Comment by Regenschrim** [comment]
Me sumo a la duda, ¿hay que entregar un diagrama de clases con las estructuras que usaremos o una especie de texto que explique como funcionan y que harán dichas estructuras?

**Comment by FernandoPieressa** [comment]
La idea no es ni código ni diagrama de clases, lo que tienen que entregar es un archivo markdown donde escriban que estructuras de datos piensan implementar y mas o menos que métodos estos tendrían que tener y que harían con ellos.

Saludos!

**Comment by AngelMatias** [comment]
Puede ser en .txt ?
