### ISSUE TITLE
Borders

### ISSUE THREAD

**Issue by aSPCA** [IIC2233/Syllabus#215]
Al momento de definir cuales son las fronteras entre paises, el que haya un chile - argentina, y un argentina - chile implica que hay 2 conexiones terrestres distintas para metodos del programa o que debo ser capaz de poder identificar una sola de ellas y agregar que hay una sola conexion terrestre?

salu2

**Comment by stephichau** [comment]
@aSPCA Es la misma conexión! Lo que dice es que la relación es bidireccional :).

**Comment by fdominguezclaro** [comment]
Entonces las relaciones son todas unidireccionales? (Aeropuertos y fronteras)

**Comment by stephichau** [comment]
No, las relaciones son bidireccionales

**Comment by rjdelrio** [comment]
entonces si en el archivo borders sale Chile-argentina y luego no sale nada mas sobre dichos países, entonces asumo una dirección unidireccional o bidimencional

**Comment by bamavrakis** [comment]
![captura2](https://cloud.githubusercontent.com/assets/11377744/24590299/1526fe54-17c1-11e7-9fbd-0ba31534daa8.PNG)
