### ISSUE TITLE
T00- duda COORDENADAS

### ISSUE THREAD

**Issue by dvaldesg** [IIC2233/syllabus#215]
disculpa, no he leído tooodas las issues pero
las coordenadas deben ser de la forma:
a) A, 1
b) A1
c) como yo quiera

y... puedo hacer que sea válido reordenar y que funcione
a1 o 1a o 1A?

**Comment by vicentevegaulloa** [comment]
Hola @dvaldesg!

El formato con el que se pide el input al usuario no está especificado en el enunciado, por lo que queda a tu criterio (opción c). Sin embargo, debe quedar claro que las columnas se representan con letras y las filas con numeros.

**Comment by dvaldesg** [comment]
@vicentevegaulloa perfectoo!! gracias

**Comment by lsschmitz** [comment]
Y se podria usar dos numeros? por ejemplo en vez de A,1 pedir el numero de la fila=1 y de la columna=1

**Comment by vicentevegaulloa** [comment]
Eso no estaría correcto ya que en el enunciado se dice que las columnas se representan con letras y las filas con números.

**Comment by stephenwpugh** [comment]
Dentro de las posibilidades "como yo quiera" está  pedir primero fila * (letra) * y después en otra linea la columna * (numero) *?
