### ISSUE TITLE
Tarjetas en partidos

### ISSUE THREAD

**Issue by jeschuwirth** [IIC2233/Syllabus#215]
El pdf no dice mucho acerca de las tarjetas aparte de que os jugadores pueden ganarlas, entonces, ¿un jugador con tarjeta roja o ambas aun puede seguir jugando por todo el campeonato?

**Comment by monicabelen** [comment]
Claro, el jugador sigue en el campeonato. Ojo que debes guardar la cantidad de tarjetas obtenidas dado que esa información puede ser pedida en consola.
