### ISSUE TITLE
no pude subir el README.md "T00"

### ISSUE THREAD

**Issue by faesepulveda** [IIC2233/syllabus#215]
Hola estuve tratando de subir el README.md a mi repositorio pero git me dice:

"fatal: cannot do a partial commit during a merge."

y no logre subirlo :(

que puedo hacer?

**Comment by lily416** [comment]
Vuelve a clonar tu repositorio en otra carpeta, agrega el readme y sube los cambios.

Lo más probable es que obtengan el descuento por no entregar el readme a tiempo, pero puede que el corrector lo vea y eso lo guíe en la corrección de tu tarea.

**Comment by faesepulveda** [comment]
ok gracias
