### ISSUE TITLE
Evaluación de Señales

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#215]
En la asignación de puntajes sale que los recuadros azules se evaluara el correcto uso de señales. En caso de cumplir con lo que pide el recuadro pero no hacerlo haciendo uso de señales que es lo que pasa? Y no entiendo lo de los cuadros rojos. Gracias.

**Comment by Arcoirisky** [comment]
Lo de los cuadrados rojos es que se puede revisar mirando código, si no es rojo entonces solo se evalúa lo que muestra la interfaz.

Sobre el primer punto, si no existe manejo de señales tampoco existe buen uso de señales, entonces no habría puntaje :(

Sugiero usar señales 🤔 son maravillosas y con un poco de estudio + práctica salen solas :D

**Comment by Arcoirisky** [comment]
Mi error, tienen como máximo la mitad del puntaje 😅

**Comment by jalliende** [comment]
Gracias, y con respecto al avance, tiene alguna bonificacion??

**Comment by Hernan4444** [comment]
La bonificación es que no tendrás que después implementar esa parte con señales 😅 (pero no hay más décimas). Pueden hacerlo sin señal en el avance, pero como recomendación personal, hacer eso solo hará que luego tengas que editar dicho código para implementar señales (lo que no es bonito) o no va a funcionar como esperas.

Saludos ✌️
