### ISSUE TITLE
Mantener alíen en el cuadro de juego

### ISSUE THREAD

**Issue by KrishnaChaparro** [IIC2233/Syllabus#215]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, no puedo lograr que el alíen se mantenga en el cuadro de juego, he intentado hacer if con las posiciones de x e y respecto al porte del label del fondo, intente con el metodo traslate y moveTo, pero aun asi lo maximo que he logrado es que se buguee en el borde, ya no se que hacer.

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by CristobalPerez-Cotapos** [comment]
Hola!! Es raro que se te bugee en el borde si lo mueves de la misma forma que antes, te recomiendo poner un hook para capturar un error si eso es lo que pasa.
Una opción es que no estés haciendo los if y elif de forma correcta para controlar el flujo, para comprobar esto pon prints en todos los movimientos para chequear lo que está pasando.
Otra alternativa es que hayas creado más de un timer de movimiento de Alien cuando rebota, de manera que ambos timers funcionan simultáneamente moviendo al Alien y causa comportamiento inesperado.
Cuéntame si algo de esto te funciona 😉
