### ISSUE TITLE
Duda ejercicio 3.2 - semana 4

### ISSUE THREAD

**Issue by tamyhan** [IIC2233/syllabus#215]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola, no entiendo cómo relacionar el número de ticket en la property cantidad_repeticiones para que se hagan distintas sumas dependiendo del número de ticket. No se si se entiende mi pregunta, pero me pasa que al ir sumando 1 cada vez que hay una repetición, me suma a una misma cantidad para todos los tickets.

**Comment by camilagonzalezp** [comment]
¡Hola @tamyhan!

A lo mejor te podría servir utilizar un atributo de clase para llevar un registro de las repeticiones de cada ticket, ya que recuerda que los atributos de clase son compartidos por todas las instancias de la clase, por lo que podrías fácilmente acceder a la información almacenada en este.

Ojalá te sirva, cualquier cosa no dudes en volver a preguntar 🙌🏻

¡Éxito! ✨

**Comment by tamyhan** [comment]
Sii, eso hice, pero me pasa que cada vez que hay un error, se va sumando una repetición para todos los tickets.

**Comment by tamyhan** [comment]
Gracias!! Lo logré! :)

**Comment by camilagonzalezp** [comment]
¡Genial!
