### ISSUE TITLE
Relación Excavador/Ítems con Torneo y duda sobre eventos

### ISSUE THREAD

**Issue by masoto22** [IIC2233/Syllabus#216]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Por temas familiares no pude subir mi avance de tarea la semana pasada y ahora la estoy sufriendo con una parte de la tarea porque estoy demasiado enredada en la relación de Torneo con las entidades de Excavador e Items. Debo asumir que los excavadores solo existen si se lleva a cabo un torneo? Porque sé que un **conjunto** de excavadores forma parte del torneo, pero si elimino el torneo deberían seguir existiendo? La misma duda con ítems, si no hay arena (que según yo depende de la existencia del torneo), hay igual ítems? Creo entender que sí deberían existir porque son objetos aparte, que pueden ser tesoros o consumibles, pero estoy enredadísima con eso.

Otra pregunta que tengo es si es necesario tener una entidad Evento o no en rigor? Esa duda me surgió porque en el enunciado dice que mínimo deberá haber una vez composición, agregación, herencia, clase abstracta, polimorfismo y properties, pero yo no tenía agregación y dado esa inquietud me surgieron estas dos dudas jajja espero que se puedan responder de alguna forma, lo siento si es muy lesa la pregunta.

Gracias! 😄

**Comment by CarolinaMezaCh** [comment]
Hola @masoto22!!

Respecto a la primera pregunta, la relación entre Torneo y Excavadores no necesariamente deben tener esa dependencia de existencia como dices, puedes hacerlo si es que te acomoda de esa forma para realizar el flujo del programa,  pero también puedes hacerlo aparte. Como se menciona en el enunciado se deben tener como entidades principales:  Torneo, Arena, Excavadores e Ítems. Para relaciones, por ejemplo, entre Ítems, Consumibles y Tesoros, te aconsejo revisar los contenidos relacionados a herencia de clases (lo puedes ver en contenidos de la semana 02 y 03).

En cuanto a la segunda pregunta, en el enunciado se mencionan las entidades principales que debe tener el programa, pero puedes definir otras si te acomoda. Es importante que se encuentren estos elementos en el programa al menos 1 vez: herencia, clases abstractas, polimorfismo, properties y relaciones, que pueden ser de **agregación o composición**.
Espero haber aclarado tu duda!!

**Comment by masoto22** [comment]
Gracias, me quedó mucho más claro 😸
