### ISSUE TITLE
Líneas blancas entre if, elif, else, for y while

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#216]
Hola! Leí la guía de PEP 8 y sobre las líneas blancas solo sale que entre definiciones de clases y funciones tiene que haber 2 líneas y entre los métodos de una clase tiene que haber una línea en blanco. Pero no dice nada sobre los iteradores y condicionales. Entre poner una línea blanca y poner todo junto, qué es mejor? Tienen alguna regla sobre eso? Digo:

Es mejor así:

if a == 1:
    print("hola mundo")
elif a == 2:
    print("chao mundo")
else:
    pass

o así?:

if a == 1:
    print("hola mundo")

elif a == 2:
    print("chao mundo")

else:
    pass

Cuando estas condiciones son más largas se puede ver confuso sin líneas que las separen, misma pregunta con los for y while.

**Comment by cristozille** [comment]
Hola! La separación va solo entre las definiciones de funciones y entre las clases. Entre los if, for y while no es necesario, pues alarga mucho el código.

**Comment by kalarconvl** [comment]
@cristozille entonces es mejor dejarlo sin espacios? Igual no me paso de la cantidad de líneas poniendo espacios blancos. Según yo se ve más ordenado, no es así? 😅

**Comment by MatiasDuhalde** [comment]
Hola @kalarconvl !

Complementando la respuesta de @cristozille , no existe obligación para agregar líneas en blanco entre bloques if-else. Sin embargo, [PEP8](https://www.python.org/dev/peps/pep-0008/#blank-lines) específicamente recomienda:
> Use blank lines in functions, sparingly, to indicate logical sections.

Además, la guía de estilo de [Google](https://google.github.io/styleguide/pyguide.html#35-blank-lines), dice lo siguiente:

> Use single blank lines as you judge appropriate within functions or methods.

En resumen, quedaría a juicio tuyo si decides colocar lineas en blanco entre secciones de código. Si crees que mejorará la legibilidad de este, adelante! Para un ejemplo tan sencillo como el que colocaste en tu pregunta, recomendaría NO colocar líneas en blanco.

**Comment by kalarconvl** [comment]
@MatiasDuhalde gracias!
