### ISSUE TITLE
Avance, legibilidad del codigo

### ISSUE THREAD

**Issue by tomascortes** [IIC2233/syllabus#216]
Hola!, 
Queria preguntar si el avance debe ser un codigo comentado, con pep-8 , ..., etc o solo tiene que funcionar.

Muchas Gracias

**Comment by gatochico** [comment]
Hola! Para el avance, pedimos más que nada que el código sea **funcional** y **legible** (pues la idea es saber como están implementando algunas cosas :0 ). Así que podemos dejar pasar algunas faltas de pep-8, o que no esté todo perfectamente comentado, pero siempre **recuerda solucionar todos esos puntos al momento de la entrega final de la tarea**, pues ahí evaluaremos todo de forma más estricta. 

Saludos!
