### ISSUE TITLE
PyQt5

### ISSUE THREAD

**Issue by nhbravo** [IIC2233/Syllabus#216]
Hola! Soy usuario Mac y no puedo instalar aun PyQt5, por lo que no me corre la interfaz de la tarea. ¿Alguien sabe como lograr instalarlo?

**Comment by fgbruna** [comment]
[Leíste la wiki?](https://github.com/IIC2233/Syllabus/wiki/Software-Obligatorio#macos-2)
Si no te funciona (Probablemente si es que no instalaste `python` a traves de `brew`), deberia ser tan simple como ejecutar lo siguiente en la terminal:
```sh
pip3 install --user pyqt5
```
