### ISSUE TITLE
Problema con import utils, hace que mi codigo no funcione bien o funcione distinto

### ISSUE THREAD

**Issue by Matias-desu** [IIC2233/Syllabus#216]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

tengo un problema al importar el utils ya que al momento de hacer el menu las funciones que hice no funcionan como deberían, revise si era mi código pero incluso un código de ejemplo simple como:
```python
seguir = True
while seguir :
          opcion = input("1")
          if opcion == "1":
              print("salir")
              seguir = False
```
hace que me pida 2 veces input y que salga 2 veces salir como si hubiese iterado 2 veces a pesar del seguir = false, incluso si dentro de la def pongo un return o un break vuelve a hacer una iteracion mas antes de poder salir del while. Y esto no ocurre al no importar utils. que puedo hacer :( (mi version de python es de 3.11.9)

**Comment by Hernan4444** [comment]
Hola @Matias-desu 

A priori, el error que se me ocurre es que ese código lo tienes en `dccultivo.py` y hacer `import utils`, pero en ese archivo no hay que hacer `imports utils`, ahí solo van las clases solicitados. El código de los menus debe ir en otro archivo según el enunciado y desde dicho archivo, si importas `utils`, no deberías tener problemas.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito en tu tarea! 🦖
Saludosヾ(＾-＾)ノ
