### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by nvielva** [IIC2233/Syllabus#216]
Hola, me acabo de dar cuenta de que cerraron el cuestionario para subir el diagrama de la tarea.. En el enunciado de la tarea dice que la fecha de entrega es el Domingo 2 de abril a las 23:59 no a las 00:00.. ¿Existe la posibilidad de extender el cuestionario a la fecha/hora que indica el enunciado?
Saludos!

**Comment by Dunkan1** [comment]
ya lo abrieron

**Comment by akaminetzkyp** [comment]
Esta cerrado. :(
