### ISSUE TITLE
Duda con error "QObject::setParent: Cannot set parent, new parent is in a different thread"

### ISSUE THREAD

**Issue by IgnacioHqz** [IIC2233/Syllabus#216]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, el programa a la hora de disparar sobre un alien ve tira el siguiente error: 'QObject::setParent: Cannot set parent, new parent is in a different thread'. Buscando en internet, llegué a la conclusión que tal vez la forma en que estoy diseñando el mover los aliens y comenzar la ejecución de la animación de explosión una vez que la mira coincida con el alien me esté dando el error.
Actualmente estoy haciendo que cada X segundos se muevan todos los aliens, pero si se presiona una tecla que tengo definida para el disparo, se emite una señal para que comience el análisis (si se le achuntó al alien) para posteriormente comenzar con las explosiones (todo esto, mientras siguen moviendose los aliens en un método). El problema es que he intentadp varias formas de que las expolsiones se ejecuten dentro de este mismo 'loop' que hace que se muevan los aliens, pero honestamente ya no sé cómo arreglar este problema. Mi idea era generar otro proceso mientras se están moviendo los aliens para así mostrar las explosiones pero no sé si esta forma tenga solución. Gracias
[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by JJJGGGG** [comment]
Estas utilizando la libreria threading? A veces no funciona bien con pyqt
