### ISSUE TITLE
Ejercicios propuesto materia 2 número 1

### ISSUE THREAD

**Issue by santiago3c** [IIC2233/Syllabus#216]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola, que no se como resolver el primer ejercicio de los ejercicios propuestos, que si pongo el candado antes del while solo se ejecuta uno, y si lo pongo después también solo se ejecuta solo uno y además arroja un error... si me pueden orientar

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mskdancers** [comment]
Si te refieres al ejercicio de _Ayudantes en restorán_, en la [Issue #213](https://github.com/IIC2233/Syllabus/issues/213) tuvimos una discusión con un compañero sobre cómo mejor abordar este ejercicio 🤔. En resumen, poner los ```Locks``` afuera del ciclo ```while``` hace que el primer ```Thread``` que llegue ejecute todo su ciclo antes de soltar el ```Lock```, vaciando la lista antes de que los otros ```Threads``` accedan a esta. Cuando ponemos el ```Lock``` adentro del ciclo, tenemos que asegurarnos de dos cosas: que no se acceda a una lista vacía, y que no sea un único ```Thread``` el que se lleve toda la carga. La primera la podemos evitar usando condiciones, mientras que la segunda puede que nos pase aunque la modelación no esté estrictamente errónea, ya que los ```Threads``` a veces son un poco impredecibles; si es que el primer```Thread``` suelta el ```Lock``` y luego sólo tiene que ejecutar unas pocas líneas de código hasta poder adquirirlo de nuevo, puede que ese ```Thread``` lo suelte por tan poco tiempo que las otras ```Threads``` simplemente no alcancen a llegar a adquirirlo. Podemos arreglar esto usando un ```sleep``` para que la ```Thread``` suelte el ```Lock```, duerma un segundo, y luego lo trate de adquirir de nuevo, dando suficiente tiempo a las otras ```Threads``` para adquirir el ```Lock```.

Cabe destacar que esto es un comportamiento común en los ```Threads```, ya que, estos son una simulación de concurrencia y los procesos no están ocurriendo _realmente_ al mismo tiempo, por lo que es imposible saber cuando una ```Thread``` se va a pausar para dar lugar a otra (a menos que se lo pidamos explícitamente, usando ```Locks``` o ```join```).  

Saludos y felices fiestas patrias! 🥳

**Comment by santiago3c** [comment]
vale gracias
