### ISSUE TITLE
Duda sobre parametros constantes

### ISSUE THREAD

**Issue by Bennjapa** [IIC2233/Syllabus#216]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

** Hola, ¿Puedo hacer que algunos de mis parametros como oro inicial o el precio de las tropas, varien cada vez que se inicie el archivo y se mantengan constantes hasta que se cierre? **

**Comment by CrisDonosoMaass** [comment]
Hola!

No hay restricciones que te impidan variarlo entre cada partida, pero asegúrate de que no provoque errores como por ejemplo, tu oro inicial es menor que el precio de todas las tropas entonces no puedes comprar nada.

Espero que te ayude!

**Comment by Bennjapa** [comment]
Ya me aseguré de que no me provoque errores, Muchas gracias!
