### ISSUE TITLE
Tiempo vuelta contrincante

### ISSUE THREAD

**Issue by fbarrosalcalde** [IIC2233/syllabus#216]
Hola! Al calcular el tiempo de un contrincante en cada vuelta, me pasa que el tiempo para ese contrincante es siempre el mismo, independiente de la vuelta. Estuve analizando las fórmulas y creo que es porque lo único que hace variar el tiempo de un contrincante de una vuelta a otra es la hipotermia, que de acuerdo a la información de los archivos que nos dan (pistas y contrincantes) casi siempre es 0, porque contextura - hielo casi siempre da un número positivo y por lo tanto de acuerdo a la fórmula, el resultado de la hipotermia sería 0. No sé si no tiene sentido o algo estoy calculando o entendiendo mal?

**Comment by jeschuwirth** [comment]
Hola!

Tienes razón 🤔, llego un rato mirando el enunciado y tampoco encuentro nada más que varíe la velocidad de los contrincantes.

Por razones como esta pedimos como bonus un archivo formulas.py, ya que nos permite cambiar la fórmula en el código de manera rápida y poder corregir más eficientemente.

Felicidades por lo avanza de la tarea :D

**Comment by dpacevedo** [comment]
Hola! :blush:

Corriendo mi código me pasa exactamente lo mismo, todos los participantes de una vuelta tienen el mismo tiempo por vuelta, lo cual no debería ocurrir. Lo he revisado varias veces y no sé si es un error de fórmula o de los valores de parámetros. Cualquier ayuda es bienvenida!

Gracias de antemano :raised_hands:

**Comment by jeschuwirth** [comment]
Hola @dpacevedo,

No quedo muy claro en mi respuesta anterior por lo que lo digo claro ahora.

Es normal que los contrincantes no varíen sus tiempo excepto en las canchas con hielo o si son eliminados de la carrera en un choque.

Suerte !
