### ISSUE TITLE
Ejercicio 2.8 - semana 4

### ISSUE THREAD

**Issue by Piolawa** [IIC2233/syllabus#216]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola!,
Al ingresar numeros a recibir_instrucciones, al guardarlos el *args, me los convierte a str,  y si intento convertir los argumentos del arg a numeros si es que fue a probado por la funcion isdigit(), no funciona porque los metodos creados para realizar las operaciones esperan los argumentos de la forma *args :c no entiendo que mas hacer unu

**Comment by DomingoCarvajal** [comment]
Hola @Piolawa!!

Los *args que son introducidos en el input siempre van a ser strings, ya que están escritos desde la consola, por lo tanto habría que cambiarlos de string a int en alguna parte del código. No se de que manera estás convirtiendo los datos en tu código, pero si estás creando una lista o tupla debería funcionar. Recuerda que los métodos reciben `*args`, por lo que si tienes un lista con los valores llamada `lista`, debes pasar como parámetro `*lista`.
