### ISSUE TITLE
Completacion de ciudad

### ISSUE THREAD

**Issue by andreslyon** [IIC2233/Syllabus#216]
No tengo muy claro como se completa una ciudad. en el enunciado dice; _una ciudad se dice completa o cerrada si las piezas exteriores que la conforman están rodeadas con murallas_.  Sin embargo en ninguna parte del enunciado se define lo que es una muralla, y tampoco es un tipo de segmento. 
gracias

**Comment by fnquinteros** [comment]
Hola! Para que quede más claro, una ciudad está cerrada cuando no hay ningún borde en que puedas colocar una pieza que agrande la ciudad.

Saludos!

**Comment by andreslyon** [comment]
perfecto, muchas gracias. Otra duda que tengo respecto a las ciudades y sus conexiones.
![pieces example](https://user-images.githubusercontent.com/26236216/30005880-741ab868-90c2-11e7-9995-e46eb22f00a4.png), En la imagen adjunta, habría una ciudad completa, y en la posición aledaña a la de un segmento de ciudad un segmento del tipo camino. La pregunta es si que una ciudad se dice conectada por un camino o un rió **si y sólo si** un segmento de camino (o río) esta justamente al lado de un segmento de ciudad. o bien basta que haya en la misma ficha un segmento de estos tipos para que se puede decir conectada?

**Comment by nmaturana97** [comment]
up(?)

**Comment by movaldivia** [comment]
@fnquinteros No me quedo muy clara la explicación, lo puedes explicar de otra forma o de manera gráfica?

**Comment by fnquinteros** [comment]
¡Hola!

@movaldivia Intentaré aclarar mi explicación. una pieza tiene 6 bordes, los cuales pueden ser de ciudad, pasto, río o camino. Sólo puedes conectar piezas que, por los lados donde estarán conectadas, tengan el mismo tipo de segmento (ciudad con ciudad, pasto con pasto, etc...). Al ir juntando piezas con bordes de ciudad, probablemente llegues a tener una ciudad cerrada. Esto se da cuando a la ciudad **no le puedes pegar otra pieza por el borde de ciudad**. Es un poco difícil de ver visualmente con las imágenes de las piezas, pero la imagen que puso @andreslyon arriba es un buen ejemplo de una ciudad cerrada. Si ves donde se juntan las 2 C's, **no hay ningún borde contiguo a esas 2 piezas que permita "agrandar" la ciudad**, por lo que se considera cerrada. **¡OJO!** deben considerar los **nombres** de las piezas (sus bordes) y _NO cómo se ven en la gui_.

@andreslyon Con respecto a tu pregunta, basta con que haya un segmento de camino/río en la misma pieza que la ciudad, para que esta se considere conectada al camino/río

Espero que se haya entendido todo 😅 

¡Saludos!

**Comment by movaldivia** [comment]
@fnquinteros Vale ahora si me quedo muy claro, gracias !!!

**Comment by MrEarle** [comment]
Y en el caso siguiente:
![image](https://user-images.githubusercontent.com/30664457/30120924-9888a51c-9300-11e7-9b2e-4bb3b74c83f4.png)
La segunda pieza puede ser cualquiera de las 2 que se muestran al lado.
La que muestra 2 ciudades distintas, se considera como parte de la misma ciudad?

**Comment by Arcoirisky** [comment]
Nop. No se considera parte de la misma. Con. Esa pieza como que cierras y abres otra ciudad. Es como tener una metropolis y al ladito ir formando un pueblito ¿Se entiende? No son parte de la misma ciudad pero sí del mismo jugador O:

**Comment by MrEarle** [comment]
Pero las 2 piezas que se muestran a la derecha tendrían el mismo nombre para cierta orientación (GGCGGC). Sin el apoyo visual, no hay forma de diferenciarlos.

**Comment by Arcoirisky** [comment]
Las 24 piezas tienen nombres únicos. Sí que existe forma de poder diferenciarlas en cómo se encuentran según la cantidad de rotaciones que el usuario haya hecho (: Tomate un tiempo para pensarlo si es que no lo tienes tan claro aún. 

Puedes pensarlo de la siguiente forma: Si fueras tú a quien le entregan la información de cada ficha y te dicen que esa persona las puede rotar a su conveniencia ¿Cómo saber cuál pieza es cuál si no las puedes ver? O mejor, busca un patrón y piensa en cómo puedes obtener la información que te falta de las funciones dadas 😺

Suerte :D

**Comment by MrEarle** [comment]
Ok, pero en ese caso, que pasa si completan la ciudad que parte de un lado de la ficha y después se completa la que parte del otro lado. Quien se queda con esa ficha? Al reflejar eso en el tablero (Como sale en el Plot Twist), a cual elijo?

**Comment by Arcoirisky** [comment]
Que eso quede a tu criterio aunque ¡no olvides escribir en el Readme tu decisión!
