### ISSUE TITLE
Fecha entrega diagrama de clases

### ISSUE THREAD

**Issue by jnhasard** [IIC2233/Syllabus#217]
El cuestionario del Siding esta otra vez cerrado, el enunciado dice que es hasta el 2 de abril a las 23:59. Podrían abrir (ojala pronto) el cuestionario de nuevo

**Comment by akaminetzkyp** [comment]
Por favor abranlo. 🙏

**Comment by fvr1** [comment]
listo!

**Comment by akaminetzkyp** [comment]
Gracias!
