### ISSUE TITLE
Clase Jugador

### ISSUE THREAD

**Issue by andresplass** [IIC2233/Syllabus#217]
Quería saber que era exactamente el argumento "parent" en la clase Jugador que se nos da.
Tenemos que usar esta clase y no crear una nueva para instanciar nuestros datos de jugadores del excel, cierto?

**Comment by IchottMano** [comment]
@andresplass Hola!

En la clase Jugador está el argumento parent, el cual le dice al jugador donde se muestra, esto lo verán mas adelante cuando vean Interfaces Gráficas, el argumento parent en este caso es la ventana principal donde estarás viendo el juego.
Por lo demas, como dice la sección 4.3.1 del enunciado, **no** puedes usar los métodos o atributos de clases.py.

Para instanciar los datos de los jugadores en el csv (no es un "excel") debes usar tu propia estructura de datos. Para interactuar con la GUI debes usar los métodos dados en el enunciado.

Saludos!

**Comment by IchottMano** [comment]
@Pipelao Hola!
No está prohibido usar clases para modelar a los jugadores, pero la idea :wink::wink: es que uses una estructura de datos.
Saludos!

**Comment by jmwielandt** [comment]
@IchottMano Probé armar el gráfico usando una clase "jugador" y usando mi estructura de datos... Con la clase jugador se armó en 106 segundos (se demora entre 90 y 110) y guardando los datos en mi estructura de datos se demoró 833 segundos en la prueba que hice... ¿Pierdo algo al dejar la clase jugador para meter los jugadores en el grafo? (puntaje de la tarea)
