### ISSUE TITLE
Factor regularizador de accidentes?

### ISSUE THREAD

**Issue by anvaldes** [IIC2233/syllabus#217]
Se puede poner un parametro que este entre 0 y 1 que multiplique a la probabilidad de accidentes? lo que pasa es que en muchos casos el auto tiene accidente, entonces si pudiera multiplicar por un factor regularizador sería algo igual bueno porque sigue cumpliendo el tema de que la probabilidad este entre 0 y 1 y en caso de que quieran ponerse en el caso inicial, solo habría que hacer que el factor valga 1.

**Comment by gatochico** [comment]
Hola! Si deseas agregar este factor **unicamente con fines propios, para probar tu codigo**, eres libre de hacerlo! Sin embargo, para el momento de entrega de la tarea, **todas las fórmulas deben estar según el enunciado**. Por lo tanto, podrías agregarlo mientras pruebas tu programa, y luego sacarlo antes de entregar la tarea :eyes: 
Saludos!
