### ISSUE TITLE
Ejercicio propuesto 3.1 semana 2

### ISSUE THREAD

**Issue by NikiHV** [IIC2233/syllabus#217]
Hola! 
Resolviendo el ejercicio propuesto 3.1 de la semana 2, me lanza un error en la implementación de la herencia. Me pasa que al definir el `__init__` de las subclases, si ocupo el método `super().__init__` todo anda bien, mas si lo reemplazo por `Usuario.__init__`, donde `Usuario` es el nombre de la superclase, me lanza el siguiente error al momento de instanciar la subclase:
`TypeError: __init__() missing 1 required positional argument: 'likes'`

Las clases las definí de esta forma:
```python
class Usuario:
    def __init__(self, user, comentarios, likes):
        self.user = user
        self.comentarios = comentarios
        self.likes = likes

class Muser(Usuario):
    def __init__(self, user, comentarios, likes, shared):
        Usuario.__init__(user, comentarios, likes)
        self.shared = shared
```

Quiero recalcar que el solo hecho de cambiar `Usuario.__init__` por `super().__init__` se soluciona todo y no lanza error. Intenté buscar el problema con el debugger de vscode o en internet, pero no he encontrado qué es lo que tengo mal o por qué pasa. Según el cuaderno de contenidos 3-herencia, ambas son formas correctas de implementar la herencia en Python... ¿en qué me estoy equivocando?

**Comment by KnowYourselves** [comment]
Hola @NikiHV!

Esto se debe a que la clase padre necesita a `self`, la referencia al objeto creado, para poder funcionar. La función `super` lo hace solo, en cambio si quieres explicitar la clase padre, debes entregar `self` de la siguiente forma:

```python3
class Muser(Usuario):
    def __init__(self, user, comentarios, likes, shared):
        Usuario.__init__(self, user, comentarios, likes)
        self.shared = shared
```

De hecho el error sucede porque al no entregar `self`, la clase `Usuario` interpreta el argumento `user` como `self`, `comentarios` como `user` y `likes` como `comentarios` y se queda sin el argumento `likes`, por ende el error.

**Comment by NikiHV** [comment]
Muchas gracias!! Tienes razón, ahí se arregló 😄 

Entonces aprovecho de mencionar que el cuaderno 3-herencia tiene un error en el primer código que aparece después del subtítulo de _overriding_, al definir el `__init__` de la clase `FurgónEscolar`. Ojalá lo puedan corregir!!

Saludos!

**Comment by KnowYourselves** [comment]
Toda la razón!

Muchas gracias, lo arreglaremos en breve.

**Comment by fdoflorenzano** [comment]
¡`contenidos` arreglado! @NikiHV , gracias de nuevo.
