### ISSUE TITLE
threading con deque

### ISSUE THREAD

**Issue by santiago3c** [IIC2233/Syllabus#217]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

Por qué en el siguiente código solo trabaja trabajador1?
![Captura de pantalla (191)](https://github.com/IIC2233/Syllabus/assets/142272696/077dfa81-58af-40ee-9e99-1154964662eb)

**Comment by mskdancers** [comment]
Hola! Similarmente a lo que te comentaba en la [Issue #216](https://github.com/IIC2233/Syllabus/issues/216), lo que me parece que está pasando se debe a lo impredecibles que pueden ser las ```Threads``` a veces. Lo que pasa es que el primer trabajador toma el ```Lock``` ejecuta el código que está dentro, y luego de soltarlo tiene que ejecutar tan poco código antes de volver a adquirirlo de nuevo (sólo la comparación del ```while```), que el otro trabajador no le da tiempo para adquirir el ```Lock```. El ```.acquire()``` de los ```Locks``` no están garantizado a seguir un orden FIFO, es decir, el primer ```Thread``` que pida el ```Lock``` no necesariamente será el primero que lo obtenga, por lo que estas cosas pueden pasar. Puedes probar añadiendo más código entre las líneas 11 y 12 (como algunos prints, o un ```sleep```) y la distribución se irá viendo más balanceada. 

Ojalá te haya quedado claro, saludos!!

**Comment by santiago3c** [comment]
vale gracias
