### ISSUE TITLE
Dimensiones de ventanas T2

### ISSUE THREAD

**Issue by jsilvalavin** [IIC2233/Syllabus#217]
* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/111)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Tengo una pregunta... En cuanto a las ventanas de las tareas, es necesario que los elementos sean _Layouts_ y entonces que soporten dimensiones distintas, o puedo hacer la tarea suponiendo ciertas dimensiones fijadas por mi y que no se cambian las dimensiones de la ventana?
Gracias! :)

**Comment by mmunoz12** [comment]
Hola @jsilvalavin! 
No es necesario que utilices Layouts y tampoco es obligatorio que soporten dimensiones especificas. De esta manera, queda a tu criterio las dimensiones de tu ventana y sus elementos. Si lo deseas, puedes dejar las dimensiones como parámetros, pero los ayudantes no cambiarán estas al revisar tu tarea de modo que sea vea tal cual como tu esperabas al hacerla ☺️. 

Espero haber resolviendo tu duda, saludos!!

**Comment by jsilvalavin** [comment]
gracias! Me solucionaste la vida jajaja
