### ISSUE TITLE
MaterialError: el material sobre excepciones tiene una excepción

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#217]
En 02-manejo-excepciones.ipynb en el material de esta semana no se ve un diagrama:

![error](https://user-images.githubusercontent.com/30670535/30006327-7119a070-90cc-11e7-8745-d00ffa0f13bf.png)

**Comment by andresfdezc** [comment]
Gracias por avisar. Corregiré el problema en 2 minutos.

**Comment by andresfdezc** [comment]
Ahí quedó arreglado.
