### ISSUE TITLE
HP Torres

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#217]
Hola, en el enunciado en ninguna parte dice que las torres posee HP, pero se señala que los enemigos las pueden atacar, hay  que crear un parámetro HP_TORRE?

**Comment by roberto009** [comment]
Hola!
Solo existen dos formas de destruir una torre.
1. Con *autodestrucción*
2. Con *Destrucción torre*  (autodestrucción)
Es por esto que las torres **no** necesitan vida! 
Éxito  con la tarea :smile:

**Comment by roberto009** [comment]
Debido a una confusión en el enunciado, quiero hacer un par de aclaraciones:
⋅⋅* Las torres **no** pueden ser dañadas por enemigos normales, solo por *kamikazes*. 
⋅⋅* Cuando un *kamikaze* ataca una torre, la destruye por completo.
⋅⋅*Cuando se utiliza *Destrucción torre* (autodestrucción), la torre muere y "aturde" a las torres que están en el rango, pero no las daña.

Queda a tu elección si modelas las torres con Hp o no,  pero debes asegurarte que mueran en esas esas determinadas situaciones.
