### ISSUE TITLE
Duda sobre Menú de juego

### ISSUE THREAD

**Issue by JDomingoSilva** [IIC2233/syllabus#217]
Hola, quería preguntar sobre lo que piden del menú de juego en el enunciado.

Hay que mostrar el menú al inicio del turno del jugador, pero el enunciado dice que también hay que ir al menú de juego luego de realizar un disparo valido.

El problema es que en ese caso, si el disparo es valido pero no hunde un barco enemigo, pasa a ser el turno del enemigo, pero por enunciado también se debe ir al menú de juego, que incluye las opciones correspondientes, pese a no deber poder usarlas

**Comment by vicentevegaulloa** [comment]
Hola @JDomingoSilva !

Si entiendo bien tu pregunta, tu dices que se debe mostrar el menu de juego cuando es el turno del enemigo, tal como se muestra el menu de juego cuando es el turno del jugador. Esto no es correcto ya que cuando el jugador no acierta y es el turno del oponente, el turno se simula y en pantalla solo se muestra el resultado de su acción, no un menú intermedio. En otras palabras, el menu de juego solo se le muestra al usuario, no existe menú para el oponente.

Espero haber entedido bien tu pregunta, corrígeme si estoy equivocado 😄

**Comment by JDomingoSilva** [comment]
Gracias por la aclaración, lo que pasa es que el enunciado dice textualmente:
"Una vez ingresadas las coordenadas del disparo, si estas son válidas, se actualizarán los tableros y se volverá a mostrar el Menú de Juego."

Lo que entendí que implicaba que al realizar tu disparo, aunque no aciertes y pase a ser turno del oponente, habrá que volver al menú de juego... pero tu aclaración me da a entender que lo que quieren es que en ese caso no habría que volver al menú, si no solamente mostrar los tableros actualizados

**Comment by vicentevegaulloa** [comment]
Si hay que volver al Menú de Juego, inmediatemente después de actualizar el tablero con las acciones del oponente (en caso de no haber acertado).

**Comment by JDomingoSilva** [comment]
Aaa dale, gracias c:

**Comment by vicentevegaulloa** [comment]
La issue #188 habla de algo similar para que la revises.
