### ISSUE TITLE
Duda enunciado metodo recorrer para clase FaitHibrido

### ISSUE THREAD

**Issue by vhernnda** [IIC2233/Syllabus#217]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema
No me queda claro si en la parte:

Finalmente, el retorno de este método varía según si logra o no recorrer más de 10 kilómetros.

*  Si recorre 10 o menos kilómetros, solamente retornará el texto de la clase padre correspondiente al auto eléctrico.
 
 * En otro caso, debe retornar la concatenación de ambos textos del método recorrer de las
 clases padre, considerando un espacio entre ellos, y respetando el orden de primer andar
 como un auto de bencina y luego como un auto eléctrico.

¿Existe la posibilidad de que el metodo reciba un valor mayor a 10 pero que la bencina y energia disponibles no sean suficientes para superar los 10 Km, de manera que el metodo debe entregar lo indicado para el primer caso?

**Comment by Hernan4444** [comment]
Hola @vhernnda 

El retorno del método solo depende de cuantos kilómetros va a recorrer que lo determina el _input_ del método. Por lo tanto, si te llega un número mayor a 10, si o si es la concatenación de los 2 métodos. Lo que va a ocurrir en el caso indicado, es por ejemplo algo como lo siguiente:

```python
# Auto con muy poca energía que ni le da para rendir para rendir los 10 km
auto = FaitHibrido(rendimiento=1, marca="c2", energia=1.2, bencina_favorita=95)
res = auto.recorrer(100)
print(res) # "Anduve 1.2Km y eso consume 1.2L de bencina Anduve 0.0Km y eso consume 0.0W de energia electrica"
```

Es decir, se llamará el método `recorrer` de auto bencina con 10.0 y del auto electrico con 90.0, pero cuando se ejecute al auto electrico, este no tendrá energía, así que los km recorridos serán 0 y eso aparecerá en el `print`.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ
