### ISSUE TITLE
Ejercicio propuesto 2.1 (Semana 2)

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#218]
Hola! 
Estoy un poco confundida sobre las cosas que me piden en el ejercicio :(
¿Tengo que tomar uno de los atributos que me dan y volverlo privado?

**Comment by MatiasDuhalde** [comment]
Hola @Margarita-Paz !

Para el ejercicio 2.1 (Autos deportivos), los puntos a completar son:
1. Implementar el método `adquisicion`
2. Implementar el getter de la property `depreciacion_acumulada`
3. Imprimir los atributos y llamar a `adquisicion` para ambas instancias dentro de `if __name__ == "__main__"`

El primer punto es bastante directo.
En el segundo punto, debes completar el código dentro de `def depreciacion_acumulada(self):`, retornando el valor obtenido con la fórmula (el valor de `fecha_actual` puedes hardcodearlo).
En el tercer punto, bastaría con usar prints y llamar al método `adquisicion`. Una forma de imprimir los atributos es llamándolos directamente en los prints dentro de `if __name__ == "__main__"`, o modificando el método `__str__` de la clase.

La idea principal de este ejercicio es practicar y ver como funciona el getter de una property. De esta manera, cada vez que se llame a la property `depreciacion_acumulada` (es decir, usando ` barato.depreciacion_acumulada`), en vez de entregar un valor guardado en la memoria, se calcularía nuevamente su valor con la fórmula. Esta técnica es bastante útil para definir atributos que cambian en base al valor de otros atributo.

Ojalá haya quedado un poco más claro, y si sigues con dudas, avísanos!

**Comment by Margarita-Paz** [comment]
Me sirvió mucho! solo que no logro entender la forma de imprimir ese getter :(

**Comment by MatiasDuhalde** [comment]
Hola de nuevo!

Para poder obtener el valor que sale del getter, solo bastaría con "obtener" `depreciacion_acumulada` tal como si fuera un atributo normal. Por ejemplo:
```python
# Se crea el objeto super_caro
super_caro = Deportivo('SuperCaro', 'DCC', 'IIC2233', 10000, 2017)
# de esta manera, se imprime el valor de la depreciación acumulada
print(super_caro.depreciacion_acumulada)
```
Si lo definiste de manera correcta con la fórmula, el output debería ser:
```
3000.0
```

Un tip más que puedo ofrecer y que quizas pueda causar confusión, es que el getter debe retornar un valor, es decir, se definiría de la siguiente manera:
```python
@property
def depreciacion_acumulada(self):
    return (self.precio / 10 ) * ....
```
 
Ojalá ahora quede un poco más claro :D

**Comment by Margarita-Paz** [comment]
Ahora me funcionoooo, es que estuve escribiendo todo el rato "despreciación" y era "depreciación" ajjajaja
Muchas gracias por la ayuda!!!
