### ISSUE TITLE
Problema con reconocimiento y autocompletado de métodos

### ISSUE THREAD

**Issue by MathiasPrett** [IIC2233/Syllabus#218]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido

Hola.
Hace un tiempo hice una issue similar, respecto a que no me estaba funcionando el autocompletado de metodos de la libreria PyQt6. Se solucionó y todo parecía estar en orden. Ahora me esta pasando lo mismo con los metodos que se definen dentro de mi propio codigo:

![image](https://github.com/IIC2233/Syllabus/assets/142269948/a1767a86-bc1e-48ff-aeb5-0cbabafced2a)

No se me da la opción de autocompletar lo que resta del método. En clases, lo vi con el profesor y el ayudante. Descbrimos que se trataba de una incompatibilidad directamente relacionada con la extensión de Pylance. No supieron como ayudarme, pero me recomendaron buscar en StackOverflow si alguien tenía el mismo problema. Hay varios reportes similares, pero ninguna de las soluciones me sirvieron.

Alguien sabe como tratar este problema?? Lo he intentado de todo porque seguir programando sin esa herramienta me es muy incomodo. He incluso reinstalado VsCode por si se solucionaba, pero nada ha cambiado. 

Gracias.

**Comment by Hernan4444** [comment]
Hola @MathiasPrett 

Lo que sucede es que VScode (o cualquier otro editor de texto) no tiene como saber que tipo de dato es lo que está dentro de la lista para poder recomendar sus métodos. Una forma para hacer eso es investigar cómo utilizar  `type hinting` (pusimos un [contenido bonus en la semana 0](https://github.com/IIC2233/contenidos/blob/main/semana-00/bonus-annotations-typing.ipynb) donde hablamos de esto). 

Usando esto, VSCode podrá leer el _type hinting_, y ahora si podrá recomendarte métodos asumiendo que esa variable es del tipo de dato que tu indicas.

Como un ejemplo, como VSCode **no ejecuta el código mientras lo escribes**, no sabe que la lista le hice `append` de `"1"`, y por eso no me recomienda nada sobre `str`

![image](https://github.com/IIC2233/Syllabus/assets/15641721/3ab92a84-6d90-4fc8-8eb6-e914c94bbd40)

No obstante, si agrego la línea `x: str`. Ahora VSCode entiende que `x` es del tipo `str` y me podrá recomendar cosas. 

![image](https://github.com/IIC2233/Syllabus/assets/15641721/156669bd-a879-4cc7-96c5-d3290690dc3a)

Igual, como este es un contenido "complementario" del curso, simplemente lo dejamos subido por quien tiene ganas de aprender más cosas, pero no es un contenido que nosotros vamos a exigir o evaluar. Por lo tanto, de querer saber más, quedará a tu responsabilidad investigar sobre el uso de _type hinting_ 😄 

Saludos!

**Comment by MathiasPrett** [comment]
Me salvaste de casi volverme loco de no saber por que no me estaba funcionando, me quedó clarísimo. Un millón de gracias!
