### ISSUE TITLE
Entregable

### ISSUE THREAD

**Issue by dlmed** [IIC2233/Syllabus#218]
Hola, revisé el enunciado y las issues y no encontré la dirección del formulario en donde se envía el entregable. Agradecería la dirección :D

**Comment by dlmed** [comment]
jeje

**Comment by IchottMano** [comment]
@dlmed Hola!
https://goo.gl/forms/sGE0LxmHd7x4isTq2
Saludos!

**Comment by dlmed** [comment]
Gracias! sorry por no leer bien el enunciado
