### ISSUE TITLE
Error que no encuentra el módulo "parametros.py"

### ISSUE THREAD

**Issue by simonmb12** [IIC2233/Syllabus#218]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/111)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!
Haciendo la tarea me he encontrado mucho rato con el mismo error. Cree el archivo de parametros.py, este se encuentra al mismo nivel que una carpeta "frontend". Cuando abro importo el archivo parámetros.py desde un archivo que está dentro de la carpeta frontend, y luego corro el código, me tira un error que dice que no encuentra el módulo "parámetros.py". Viendo esto, traté de solucionarlo creando dos archivos de parámetros distintos: uno para el front y otro para el back, los cuales se encuentran dentro de las carpetas respectivas. Al principio me corrio bien, pero luego de seguir trabajando, me tiró el mismo error que antes (siendo que ahora están en el mismo nivel).
En verdad no entiendo que pasa. Busqué en internet y no encontré la causa.

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Christian-Klempau** [comment]
Hola @simonmb12 !
Python al tratar de buscar librerías propias, las busca a partir de **dónde se está ejecutando el script**. Por ejemplo, si me ubico en `T2` (donde está mi archivo `main.py`), Python buscará en la carpeta base (es decir, T2) los archivos.

Por ejemplo, dada la siguiente estructura:

```
T2
├── backend
│   └── archivo_backend.py
├── frontend
│   └── archivo_frontend.py
├── main.py
└── parametros.py
```
Tú debes posicionar la consola en `/T2`, y luego ejecutar `python main.py`. Luego, dentro de tus archivos de backend y frontend, puedes hacer: `import parametros`. Ojo acá, que aunque estos archivos estén dentro de otra carpeta, la búsqueda de imports se mantiene desde donde tú ejecutaste el **script principal** (el primero). Por lo mismo, los archivos de backend y frontend encontrarán `parametros.py` :D

Si quieres importar un archivo de frontend que se llame `parametros_frontend.py`, dentro de la carpeta frontend, debes hacer:
`import frontend.parametros_frontend as p`

En este caso, te recomiendo ejecutar los archivos por consola. Si quieres ejecutarlo en VSCode, debes hacer "Abrir como carpeta" / "Open Folder", para `T2`.

Suerte!
