### ISSUE TITLE
Problema Error Flujo/import Circular 

### ISSUE THREAD

**Issue by FelipeIGS** [IIC2233/Syllabus#218]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola,
Entiendo que pueden ver mi codigo por lo que pregunto por un problema que estoy teniendo con el error de flujos circulares o import circular. Esto se debe a que cree un archivo en donde se leen los archivos y otro con todas las entidades. En este archivo de lectura se importa el modulo de las entidades y se llama a las subclases como ExcavadorTareo e intento crear una lista de clases, sin embargo, el error aparece. También hago un import modulo_lectura en el modulo de entidades (por si llegara a afectar). Cómo soluciono este problema?

**Comment by CarolinaMezaCh** [comment]
Hola @FelipeIGS!!

Por lo que entendí de tu código, el problema surge porque estás importando las entidades en tu readfiles.py, y la vez, importando readfiles con funciones de este archivo en entidades.py. Es por esto que aparece ese error de "import circular". Lo que podrías hacer es crear otro archivo aparte, y desde allí importar las entidades y/o funciones para hacer el flujo del programa general y que no te genere ese error.
Espero te sea de ayuda!!

**Comment by FelipeIGS** [comment]
Perfecto! Eso si al crear este nuevo archivo que transformaría la lista en clases, ahora tendría que importar tanto el modulo readfiles como aquel de entidades. No seguiría teniendo el mismo problema de antes, ya que se estaría importante este nuevo modulo, llamemoslo "definicion clases", en entidades para poder hacer bien la funcion Torneo?

**Comment by CarolinaMezaCh** [comment]
Claro, la idea de hacer un tercer archivo es que sólo importes los módulos a ese, y no entre ambos para que no vuelva a ocurrir el error.  Algo como de este estilo (puedes revisar la parte que dice " Resolving circular import issues"): https://bobbyhadz.com/blog/python-importerror-cannot-import-name 

Otra cosa que podrías hacer es cambiar el tipo de import de:
python
# module1
from module2 import func2
 
def func1():
    func2()

# module2
from module1 import func1
 
def func2():
    func1()

El módulo 1 intenta buscar una función del módulo 2, y viceversa, módulo 2 intentará buscar una función del módulo 1. Para esto podrías hacer lo siguiente:
# module1
import module2

def func1():
    module2.func2()

# module2
import module1
 
def func2():
    module1.func1()

Quizás podrías renombrar esos imports, como mencioné y ver si funciona.
Espero haber solucionado la duda! 🙌
