### ISSUE TITLE
Presencia de Multiherencia en el código

### ISSUE THREAD

**Issue by fjherrera** [IIC2233/Syllabus#218]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola.
En la rública existe un apartado que dice "Incluye y aplica Multi Herencia en un contexto correcto de la tarea". **¿Significa que obligatoriamente hay que utilizar multiherencia?** Y en caso de que así sea, **¿Es decisión mía donde incluyo multiherencia?**

**Comment by Dominique236** [comment]
Hola @fjherrera !
Tal como mencionas, la rubrica de la tarea dice "Incluye y aplica Multi Herencia en un contexto correcto de la tarea", por lo que en la tarea se evaluara que este presente el uso de _multiherencia_. Además, sobre tu pregunta de donde incluirla, esto es algo que debes resolver al desarrollar tu tarea, pero te recomiendo revisar los contenidos del curso sobre este tema para que así te quede mucho mas claro donde deberías usarla.
Cuéntame si esto resuelve tu duda y suerte en la tarea 😊.
