### ISSUE TITLE
Avance, Sprites

### ISSUE THREAD

**Issue by jerrymendoza** [IIC2233/syllabus#218]
Hola, 
En el pdf mencionan 

> Mostrar un personaje **con las imágenes dadas** y un obstáculo en el mapa..

> Mostrar un enemigo **con las imágenes dadas** y un obstáculo en el mapa..

Se refieren a que esten funcionando lo sprites? o con mostrar un personaje (que se mueva, pero sin animación) estaría bien?
Pregunto porque no ocupare los sprites dados (por ser de tamaño irregular)

**Comment by Hernan4444** [comment]
Hola,

Precisamente tienes que mostrar al personaje o enemigo con un Sprite pero no animado. Te recomiendo que para el avance le pongas uno de los sprites que te damos, pero luego lo cambias a lo que quiere. 

Saludos :v:
