### ISSUE TITLE
Persona infectada->curada ->infectada

### ISSUE THREAD

**Issue by rfenzo** [IIC2233/Syllabus#218]
quería saber si una persona que ha sido curada puede volver a infectarse

**Comment by akaminetzkyp** [comment]
Yo creo que sí. En mi opinion, lo ideal es no tratar a las personas individualmente, ya que simular cada persona sería muy exigente para el computador. En mi caso, al curar personas va a bajar el número de individuos infectados y nada más.

**Comment by rfenzo** [comment]
ya, gracias

**Comment by FernandoPieressa** [comment]
Tal como dijo @akaminetzkyp  alguien infectado si puede volver a infectarse

Saludos!
