### ISSUE TITLE
Raise Exception duda.

### ISSUE THREAD

**Issue by Sforrego** [IIC2233/Syllabus#218]
hola buenas :)

Queria saber si en un codigo lo ideal es crear un error o evitarlo, por ejemplo:
```python
l = ['a','b','c']
x=input()
```
y piden l[x]

lo ideal seria que yo pusiera un `if x < 0 or x > 2: print ("index fuera de rango!")`
o un `raise ValueError("index fuera de rango")`

dentro de una funcion seria igual? 

no me queda tan claro el uso del raise, quizas para poder usar el except y tratarlo(?), no estoy muy convencido, gracias :D.

**Comment by KnowYourselves** [comment]
Piénsalo de esta manera:

- `raise`: Código hecho por tí que otra persona usará.
- `try/except`: Código hecho por tí haciendo uso de código hecho por otra persona.

Supongamos que el módulo math no existiera, y tu como ávido programador cansado de no poder realizar operaciones matemáticas complejas decides crear un package de python que las facilite. Esto quiere decir que harías muchas funciones que hacen distintas cosas donde pueden ocurrir muchos errores. Como tu sabes que este módulo sera ocupado por otros programadores (o en su defecto un yo de tu futuro) Haces uso de `raise` para informar a un usuario que está ocupando mal el módulo.  
Por ejemplo, si tu tienes una funcion que te eleva un número y un usuario pasa un string, no es muy viable que dentro de tu modulo hagas todo un proceso para preguntarle de nuevo por input, es más simple y directo informarle al usuario de su error con un `raise TypeError`.

En el otro lado del espectro cuando tu haces uso de módulos externos, o tu código empieza a hacerle largo o si trabajas con input del usuario es viable usar `try/except` para analizar los errores.  Por ejemplo en el caso que tu muestras podrías hacer lo siguiente:

```python
lis = [1,2,3]
index = input()

try:
    lis[int(index)]
except IndexError:
    print("Index Invalido")
except ValueError:
    print("Debe Ingresar un número")
```
La gracia de esto es que al interceptar los errores puedes actuar de manera distinta dependiendo del error, lo cuál facilita hacer que el programa no se caiga.

Un ejemplo del uso de raise está en los archivos .py que vienen incluidos en su tarea 2, si lo analizas verás como se hace uso de rasie para informarle a los usuarios (como tú) cuando estan utilizando los funciones de manera erronea.

**Comment by andresfdezc** [comment]
Complementando, para errores de índices se usa `IndexError` en vez de `ValueError`. Además, te recuerdo que `input()` retorna un string (`str`) que no sirve como índice directamente y es necesario convertirlo en un `int`.

**Comment by Sforrego** [comment]
@KnowYourselves  me quedo clarisimo muchas gracias!

y gracias por la info @andresfdezc , lo del input lo tenia claro y lo hice a la rapida, lo del index no lo sabia :).
