### ISSUE TITLE
Duda herencia

### ISSUE THREAD

**Issue by MeuDeuz** [IIC2233/Syllabus#218]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema
Se pueden heredar atributos privados y propiedades y si es así, como se hace? Porque mi código funciona, pero solo en la super clase y no me salió (o no se puede) heredar propiedades y atributos privados de otra clase :(

**Comment by carlosmartellus** [comment]
Hola @MeuDeuz,

Efectivamente, python permite heredar properties y atributos tipo `self._atributo`. Ahora te muestro un ejemplo para que lo puedas ver, probar y manipular si así lo deseas:

```
class Madre:
    def __init__(self, arg1):
        self.arg1 = arg1
        self._arg2 = None
    
    @property
    def arg2(self):
        return self._arg2

    @arg2.setter
    def arg2(self, value):
        self._arg2 = value


class Hija(Madre):
    def __init__(self, arg1):
        super().__init__(arg1)


instancia = Hija(12)
instancia.arg2 = "Hola"

print(instancia.arg2)
```

**Comment by MeuDeuz** [comment]
Dale así me queda super claro. Muchas gracias ❤️

**Comment by carlosmartellus** [comment]
Hola, noté que quizás mi código fue un poco ambiguo dado que uno podría pensar que lo que estoy haciendo en ```instancia.arg2 = "Hola" ``` es asignarle un nuevo atributo. Para ahora sí visualizar que la clase hija hereda la propiedad, podrías probar este código:

```
class Madre:
    def __init__(self, arg1):
        self.arg1 = arg1
        self._arg2 = None
    
    @property
    def arg2(self):
        
        return self._arg2

    @arg2.setter
    def arg2(self, value):
        if value == "Hola":
            self._arg2 = 1
        else:
            self._arg2 = 2


class Hija(Madre):
    def __init__(self, arg1):
        super().__init__(arg1)


instancia = Hija(12)

instancia.arg2 = "Hola"

print(instancia.arg2)
```

**Comment by carlosmartellus** [comment]
Hola, para poder analizar y entender tu problema podrías hacer push, pero a priori, diría que no manejas o no defines correctamente el setter de la property.

**Comment by carlosmartellus** [comment]
Ya mira, el error podría ser que estás definiendo el ```__init__``` ya que el archivo que se te entrega tiene únicamente ```bencina_favorita```, ```*args```, ```**kwargs```, por lo tanto, el ```super()``` se debería hacer únicamente considerando estos tres argumentos. Si aún cambiando esto sigues con errores, te recomiendo que asistas mañana a la cátedra ya que el segundo módulo será dedicado para dudas de la actividad. Un saludo!

**Comment by MeuDeuz** [comment]
Muchas gracias, mañana pregunto entonces porque si le quito cosas del `__init__` muere, si le quito argumentos muere y si le quito las propiedades muere NJDFHDSJ
