### ISSUE TITLE
Tildes en el archivo csv

### ISSUE THREAD

**Issue by jpperez5** [IIC2233/syllabus#218]
Estoy teniendo problemas al abrir los archivos de texto debido a que hay palabras escritas con tildes (automóvil, troncomóvil). ¿Puedo volver a generar los archivos sin los tildes para que mi código no detecte carácteres extraños, o eso afectaría en la nota?

**Comment by jeschuwirth** [comment]
Hola!

Para leer el archivo te recomiendo usar la siguiente función:
 `with open(fname, "rt", encoding="utf-8") as f:`

el argumento opcional encoding="utf-8" te permite abrir el archivo con ese encoding, el cual debería ser capaz de leer las tildes sin poblemas.

Suerte!
