### ISSUE TITLE
Plazo entrega Readme T0

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#218]
Hola! En la issue #197 @aljara97 dijo que el Readme se entregaba ayer martes, ¿esto es verdad?

Yo todavía no subo el mio, ya que en el enunciado de la T0 al final en "11. Restricciones y alcances" sale explícito: "[t]endrás hasta 48 horas después del plazo de entrega de la tarea para subir el README a tu repositorio".

Como la entrega de la T0 se postergó para el lunes, el plazo para subir el Readme debiera ser para hoy a las 20hrs 😲

**Comment by entamburini** [comment]
Hola @jamigone,

Como es un aplazamiento extraordinario, no rigen las mismas normas de siempre. En el momento de aplazamiento y en el anuncio hecho se dijo el plazo del Readme.

Puedes subir tu readme para ayudar al corrector a ver tu código, tendrás el descuento igual, pero nos ayudarás a entender tu lógica :)

Saludos!

**Comment by jamigone** [comment]
Pucha, ¿debo rellenar algún formulario por entregar el Readme atrasado?

Si es así y fuera el mismo que el de la tarea atrasada, ¿actualizo el commit que puse ahí?

**Comment by entamburini** [comment]
Nop, para los readmes simplemente tienes que subirlo, nosotros nos encargamos del resto :D

**Comment by sbcorrea** [comment]
Hola, me pasó lo mismo pero recién abrí el tree/9f9f94e4090fe61885a55cc4cae2cce31deab663 para revisar el estado de mi Tarea, como decía el issue en mi repositorio, y ese no tiene el readme... está bien? igual lo va a ver quien me corrija?

**Comment by entamburini** [comment]
Hola @sbcorrea!,

Seguramente está bien, esa recopilación fue hecha el día anterior a la entrega del readme :eyes: es para que revises si los archivos de la tarea están bien :)

Si subiste el readme a tiempo, todo estará bien :D

**Comment by sbcorrea** [comment]
Pucha no, no lo subi a tiempo de hecho me pasó lo mismo que la persona que
creó este issue... Solo preguntaba pa que le ayudante tenga mi readme como
guia :(

**Comment by entamburini** [comment]
Bueno, para tu alivio, el readme si será leído y según el documento de descuentos, el no entregarlo no significa un descuento muy grande :)

**Comment by sbcorrea** [comment]
No eran 5 decimas?

**Comment by entamburini** [comment]
[Revísalo aquí :eyes:](https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md)

**Comment by sbcorrea** [comment]
Aa bacan! Gracias
