### ISSUE TITLE
Vida inicial combatientes

### ISSUE THREAD

**Issue by francorreaandrades** [IIC2233/Syllabus#219]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!!

Al instanciar las clases de los distintos tipos de combatientes a partir de los archivos dificultad o unidades, la vida inicial de cada combatiente es su vida máxima??

**Comment by cataruze** [comment]
Holaaa, yo tampoco entendí esta parte del enunciado, ya que en la parte 6.1 Dificultad, en los datos que se entregan de cada combatiente no se nombre que se dará la vida inicial.

**Comment by CrisDonosoMaass** [comment]
Hola!

Cada vez que se instancia un combatiente por primera vez este está completamente sano por lo tanto su vida inicial es su vida maxima.
 Espero haber resuelto su duda, suerte!
