### ISSUE TITLE
Archivos .txt en la tarea

### ISSUE THREAD

**Issue by tqmbanados** [IIC2233/syllabus#219]
Hola :)

Hasta el momento, no he subido los archivos .txt al repositorio pues nos pidieron que no lo hiciéramos, pero para la "entrega final", si queremos subir un archivo de texto, ¿cómo lo hacemos? ¿El archivo de puntajes.txt lo tenemos que subir también?

**Comment by vicentevegaulloa** [comment]
Hola @tqmbanados !

Como dice el enunciado, se recomienda que usen el .gitignore para que aprendan a trabajar con el en esta tarea. Para ignorar todos los archivos `.txt` debes escribir en tu gitignore: `*.txt`. Pero si quisieras solo ignorar `puntajes.txt` basta con que escribas el path del archivo dentro del directorio de la T00 en el .gitignore (en este caso seria escribir solo `puntajes.txt`) para que este sea ignorado y los demás archivos `.txt` puedan ser subidos.

Esta es una forma de hacerlo, pero si buscas algo distinto se les da [este](https://github.com/IIC2233/syllabus/blob/master/.gitignore) gitignore de ejemplo y [aquí](https://git-scm.com/docs/gitignore) puedes encontrar la documentación de gitignore. Además [aquí](https://gist.github.com/jstnlvns/ebaa046fae16543cc9efc7f24bcd0e31) tienes un pequeño resumen de como usar gitgnore.

Espero haberte ayudado! 😄

**Comment by tqmbanados** [comment]
Hola, gracias por tu respuesta!
He estado usando .gitignore como dices para no tomar en cuenta los archivos punto .txt en el control de versión. Mi pregunta es si puedo agregarlos solamente al "último" commit, para que sean parte de la tarea.

**Comment by vicentevegaulloa** [comment]
Si puedes, debes cambiar el gitignore justo antes de hacer ese último commit. De esa manera estarías ignorando todos los archivos .txt, y al momento de hacer el último commit cambias el gitignore explicitando que solo quieres ignorar puntajes.txt y al hacer `add` deberían añadirse todos menos puntajes.txt. Lo otro sería hacer add de cada archivo de manera manual pero eso es más tedioso.

**Comment by tqmbanados** [comment]
Muchas gracias!

**Comment by DCCollao** [comment]
No cierres las issues cuando son resueltas! Tu duda le podría servir a alguien más. Les ayudantes nos encargaremos de eso cuando llegue el momento.
