### ISSUE TITLE
Ventana de Post - Nivel

### ISSUE THREAD

**Issue by agustinbc7** [IIC2233/Syllabus#219]
* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/111)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, tengo una duda. En el enunciado, en la ventana post-nivel (4.6), dice que debo mostrar el tiempo restante, pero en la imagen no aparece, sino que en cambio aparece el puntaje total. ¿Debo colocar ambos o es solo uno de esos dos?

Gracias de antemano.

**Comment by sebaguerrap** [comment]
Hola @agustinbc7 ! La ventana de post-nivel debe tener todo lo pedido en el enunciado, es decir, debe incluir el tiempo restante. Sobre el puntaje total, no es necesario ponerlo pero no se descontará por ponerlo.
