### ISSUE TITLE
jugadores y equipos

### ISSUE THREAD

**Issue by aamedinaj** [IIC2233/Syllabus#219]
hola :3
[asumiendo que puedo usar Demo.py en su totalidad]:

1. Donde en Demo.py muestran los 20 jugadores ¿ahí mismo dejo (reemplazando) los 200 jugadores al azar que saque de la base de datos?

2. En Demo.py están los 15 equipos 'por defecto'. ¿Los dejo ahí o tengo que crear por mi cuenta 15 equipos rivales? (mi atención se centra en los nombres, porque es claro que voy a tener que calcular denuevo la esperanza de ganar)

3. Al usuario lo dejo seleccionar sus 11 jugadores....¿de los 200 originales, o de los 35 restantes (después de repartir 11 a cada uno de los 15 equipos rivales)? 

D.A.G. ✌️

**Comment by mora4** [comment]
Hola, tengo una pregunta relacionada con el punto 3:

¿Cómo debe elegir el usuario los 11 jugadores de su equipo? ¿Debemos "printear" los 200 jugadores al azar y darle la opción de elegir 11?

**Comment by llloyola** [comment]
Tengo las mismas dudas

**Comment by mramirez7** [comment]
Me sumo a la pregunta 2, dejar los equipos que vienen por defecto sería como escribirlos uno a uno según la pauta?
