### ISSUE TITLE
Ayuda, OOP, Conexiones

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#219]
En mi modelamiento tengo una clase Pais y una clase Mundo, la clase Mundo dentro de sus atributos tienen una lista con instancias de la clase Pais (todos los que están en population.csv), luego dentro de los métodos que tiene la esta clase se encuentra el "cargar_mundo" que basicamente lee el archivo "population.csv" y crea los instancias de la clase Pais y los agrega al atributo paises. Por otra parte, para identificar las conexiones (fronterizas por ahora) y similarmente a lo que hice para "cargar el mundo" tengo un método en la clase Pais que lee el archivo "borders.csv" y agrega el pais de llegada si es que el pais de origen coincide con el atributo nombre de la instancia Pais. El problema, es que me agrega string del nombre del pais de llegada, y yo quiero agregar la instancia del pais de llegada para luego hacer una especie de diccionario (no funciona tan bien como uno de python, pero es un simil usando mi lista ligada) que represente el grafo de conexiones fronterizas y recorrerlo para poder infectar. 
Las preguntas del millón es:
-> ¿cCómo agrego las instancias y no los string con los nombres de los paises con los que hay conexion? 
->¿Está bien instanciar un Mundo dentro del método que agrega las conexiones y poner un for que recorra los paises de esa instancia Mundo y revise si el nombre del pais de llegada coincide con el pais.nombre y asi agregar esa instancia de pais a las conexiones? (notar que instanciar el mundo implicaria leer el otro archivo dentro del metodo agregar conexiones)  o ¿es mejor opción darle el mundo de parámetro?

Les agradecería mucho si pudieran responderme esto !

**Comment by fvr1** [comment]
Yo creo que lo mejor es que tu clase mundo tenga dos métodos, el `cargar_mundo` que habías mencionado y el que se encarga de leer las conexiones de `borders.csv` y hacerlas. Si haces esta última función dentro de `Mundo` puedes recorrer su lista ligada con los países y así puedes obtener la instancia del país para crear la conexión según lo que dice el archivo.

**Comment by acrojas2** [comment]
@fvr1  o quien sea que pueda responderme:
Hice lo que me sugeriste, me pareció muy buena idea, para ello implementé dos funciones que son las siguientes:
    def conectar_fronteras(self):  #Recorre los paises y llama a la funcion conexion_frontera 
        for pais in self.paises:
            self.conexion_frontera(pais)

    def conexion_frontera(self, pais):
            -----> aca leo el archivo... (abrir y leer line1)
            if dato_1 == "﻿Pais 1":
                   (leo las lineas que siguen)
                    if pais_origen == pais.nombre:
                        for p in self.paises:
                            if p.nombre == pais_llegada:
                                pais.conexiones_tierra.append(p)
            else:
                (se hace lo mismo que en if anterior pero considera el caso que las columnas inviertan su ordeb)

El problema que tengo ahora es que agrega las conexiones solo del primer país y no se qué pasa que en las iteraciones siguientes, hice mil prints y llegué a la conclusión de que apenas termina de encontrar la conexión para el primer país, esto se detiene y no sigue iterando.  Llevo horas tratando de encontrar la falla... AYUDAAA!!

**Comment by acrojas2** [comment]
la funcion 1 era: 
     def conectar_fronteras(self):
        for pais in self.paises:
            self.conexion_frontera(pais)
