### ISSUE TITLE
tipos de segmentos

### ISSUE THREAD

**Issue by AngelMatias** [IIC2233/Syllabus#219]
No entiendo, porque se supone que en esta parte del enunciado estan describiendo las caracteristicas de los segmento, pero al leerlo pienso que estan describiendo entidades. Que onda al final?
<img width="816" alt="captura de pantalla 2017-09-03 a la s 19 21 47" src="https://user-images.githubusercontent.com/30705123/30007114-e76f5f4c-90dd-11e7-93c3-9e4bfe57a468.png">

**Comment by fnquinteros** [comment]
Hola! Lo que pasa es que las piezas tienen segmentos de estas entidades. Por ende, al unir varias piezas con un determinado segmento, puedes formar una entidad. Se entiende?

**Comment by AngelMatias** [comment]
aaa perfect, pero las caract que describen van a las entidades y no a los segmentos?

**Comment by fnquinteros** [comment]
Claro, van más bien a las entidades en sí.

**Comment by fnquinteros** [comment]
Te están diciendo cuáles son los bordes de las piezas y qué puedes formar con ellas.

**Comment by AngelMatias** [comment]
Entiendo gracias ! :)
