### ISSUE TITLE
Posibles consecuencias negativas de cambiarse el nombre de usuario

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#219]
Hola, existen consecuencias negativas en este curso si cambio mi nombre de usuario de Github?

**Comment by entamburini** [comment]
Hola @dlmed,

Si, para mi es un tremendo problema porque tu repositorio tiene tu nombre de usuario, porque estás registrado en el sistema así, por eso en el form avisamos que piensen bien el nombre de usuario.

Entre las consecuencias está el que no te recopilemos las cosas :sweat_smile:. Si finalmente lo haces, me tienes que avisar

**Comment by dlmed** [comment]
si, tranqui no lo voy a hacer 😅
