### ISSUE TITLE
Como escribir objetos de la GUI

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#219]
Hola, cual es la forma correcta de escribir los nombres de los objetos de una interfaz gráfica como los botones, por ejemplo para las clases es CamelCase, funciones snake_case. Cómo sería en este caso, ya que en los ejemplos combinan mayusculas y minusculas, por lo que me parece que es un modo de escritura distinto a estos dos, por lo cual va mi segunda pregunta: de ser distinto a snake_case y CamelCase habrá descuento por no respetar dicha forma?

Saludos

**Comment by Hernan4444** [comment]
Hola, 

Cuando vas a instanciar una objeto de una interfaz como un botón, eso seguirá siendo un atributo o variable, por lo tanto se usa snake_case. Por lo tanto sería algo como:
```python
push_botton = QPushButton("Texto")
```

Si esto no responde bien tu duda, por favor poner un código de ejemplo con el que tienes conflictos y te digo de inmediato como debería escribirse. Así todos quedamos conformes con la respuesta.


Saludos ✌️

**Comment by VicenteMerino** [comment]
En algunos casos (ayudantias pasadas) escriben keyPressEvent, esto a que corresponde?

**Comment by Hernan4444** [comment]
Lo que pasa es que `keyPressEvent` es un método de los `Qwidget` que ya está definido así, por lo tanto se tiene que escribir igual para sobreescribirlo y hacer que tenga el comportamiento que nosotros queremos. En ese caso, no hay descuento.

Saludos :v:
