### ISSUE TITLE
Posible fe de erratas Semana-06 archivo "3-pyqt-miscelaneo.ipynb"

### ISSUE THREAD

**Issue by SSParzival** [IIC2233/Syllabus#219]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

En el archivo de contenidos de la semana-06, `3-pyqt-miscelaneo.ipynb`, en la sección de "*isAutoRepeat* en *KeyPressEvent*", se menciona cuando el método `isAutoRepeat()` retorna True o False, mas en el archivo para ambas instancias distintas se coloca que el método retorna `True`. Según lo investigado, pienso que la primera mención debiese decir `False` en vez de `True`. 

Se adjunta imagen que evidencia el error encontrado; específicamente encontrado en el segundo párrafo. 

![image](https://github.com/IIC2233/Syllabus/assets/86897103/8e30db77-60f6-4b87-bb5e-a2606a2e884a)

**Comment by isidoragutierrez** [comment]
Me sumo a la duda.

**Comment by Hernan4444** [comment]
Hola,

Confirmo que el primer `True` debía ser `False`. El texto se debe ver así:

![image](https://github.com/IIC2233/Syllabus/assets/15641721/845b83fa-a97b-43c4-8473-40903cc45d74)


Vamos a actualizar los contenidos para corregir ese _typo_.

Saludos!
