### ISSUE TITLE
Duda diccionarios funciones (ej 5.3)

### ISSUE THREAD

**Issue by crisalcaino99** [IIC2233/syllabus#22]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda (Ej 5.3)

Hola, en el ejercicio 5.3 de los propuestos de esta semana tengo que usar diccionarios para mover el tablero. Entendi (gracias a 
stackoverflow) como se hace eso, pero cuando lo corro y empiezo a usar las teclas las posiciones no cambian de "o" a "-" si no que quedan todas registradas, tambien me pasa que no puedo llegar a una esquina. Empiezo a pensar que es problema del codigo y no mio :(. Ayuda xfis

**Comment by tqmbanados** [comment]
Hola! Por las dudas probé el ejercicio y está todo bien el código base.
Es posible que te estés complicando más de lo necesario, por que la verdad no se me ocurre como podrían pasarte esas cosas si las funciones están ya creadas. Recuerda que no tienes que editar las funciones ya hechas, solamente llamarlas, recibir los valores que retornan, y asignarlas a las variables ```tablero``` y ```pos```. El diccionario se usa para economizar el código al llamar las funciones. 

Un ejemplo:
```
funcion_1():
    print("hola")

funcion_2():
    print("chao")
    
diccionario = {"saludar": funcion_1,
               "despedirse: funcion_2}
## Ojo que las funciones dentro del diccionario van sin paréntesis     

```

En ese caso, llamar ```diccionario["saludar"]()``` sería equivalente a llamar ``funcion_1()``.

**Comment by ctoro05** [comment]
A mi me pasa que al crear el diccionario se me ejecuta la función automáticamente dentro del diccionario. Como puedo evitar eso?

**Comment by tqmbanados** [comment]
Probablemente es por que al definir el diccionario, las funciones que contiene las escribes con paréntesis, es decir llamándolas. Si las escribes sin paréntesis, el diccionario contendrá la función misma, y la puedes llamar como en el siguiente ejemplo:
```
def funcion():
    print("Esta es la definición de una función")
    return "string"
   
variable = funcion     # la variable a es un puntero a la función, y ahora podemos llamar a la variable
variable = funcion()  # la variable contendrá el valor que retorna la función, en este caso un string.

diccionario = {"llave_funcion": funcion,
               "llave_string": funcion()}  
```

En el diccionario, ```llave_funcion```  contiene la función misma, mientras que ```llave_string``` va a llamar la función en la definición del diccionario, y guardar el valor que retorna, en este caso un string.
Espero serte de ayuda!

**Comment by tqmbanados** [comment]
@crisalcaino99 Hola! Por favor confírmanos si pudimos resolver el problema.

**Comment by ctoro05** [comment]
Gracias!!
