### ISSUE TITLE
Aporte: pep8 en vscode

### ISSUE THREAD

**Issue by alterdieg0** [IIC2233/syllabus#22]
Hola, estaba leyendo sobre el subconjunto de reglas de pep8 que van a considerar para el curso en el archivo _[1-guía-de-estilo.ipynb](https://github.com/IIC2233/contenidos/blob/master/semana-00/1-gu%C3%ADa-de-estilo.ipynb)_ de contenidos y hay una regla que no la resuelve los linter y formatter por defecto que trae vscode la cual es **espacio entre los operadores** y que se tiene que activar a mano cambiando una configuración en settings.json de vscode.

### Contexto:
- un _linter_ te avisa cuando estas escribiendo mal código (lo muestra como un warning o como error)
- un _formatter_ corrige el código por ti cuando se lo indiques (por defecto vscode tiene habilitada la función formatOnSave por lo tanto el código se autoarregla cada vez que se guarda el archivo)
- se pueden activar linters y formatters para python en vscode casi automáticamente (los sugiere el programa al inicio)

El linter [pycodestyle](https://code.visualstudio.com/docs/python/linting#_pycodestyle-pep8) avisa para pep8 y su guía se encuentra [aquí](https://pycodestyle.pycqa.org/en/latest/intro.html#example-usage-and-output).

En la guía nos dicen que el código de error de pep8 (E226) que corresponde a **espacio entre operadores** está desactivado (ignorado por defecto)

E226 (*) | missing whitespace around arithmetic operator
-- | --

Para cambiar las configuraciones del linter se debe agregar la siguiente linea en settings.json de vscode

```
 "python.linting.pycodestyleArgs": ["arg1==propiedad", "arg2==propiedad"],
```

### Problema:
No podía encontrar un arg que "designorara" la regla E226 intenté con el comando ```"--select=E226"``` pero ese arg hace que solo se evalúe esa regla.

### Solución

Luego de ensayo y error descubrí que la forma correcta de "designorar" la regla es escribiendo ```"--ignore=!E226"``` con el signo de exclamación como negación. (cursed indeed...)

por otro lado, la guía de estilo para el curso también decía que el largo máximo de linea es 100 caracteres y en pep8 el máximo por defecto es 79, eso se arregla con el comando ```"--max-line-length=100"```

finalmente a mi settings.json de vscode le agregue la siguiente linea:

> ```""python.linting.pycodestyleArgs": ["--max-line-length=100", "--ignore=!E226"]```

y voilá, ahora _pycodestyle_ avisará cuando no tenga espacios entre operadores.

_autopep8_ tiene reglas similares a _pycodestyle_ asi que para que esta regla se autocorrija también al grabar se debe agregar la siguiente linea

 > ```"python.formatting.autopep8Args": ["--max-line-length=100", "--ignore=!E226"]```

espero haberles ahorrado un dolor de cabeza

![Anotación 2020-08-14 161737](https://user-images.githubusercontent.com/28828655/90289359-b5a9bb80-de49-11ea-990a-49c5f09acaab.png)

**Comment by Gsalinas1506** [comment]
Hola! No entendí muy bien donde hay que agregar las dos lineas de código que mencionaste. ¿Puedes indicarme en que archivo/lugar debo escribir eso porfavor? 😅

**Comment by alterdieg0** [comment]
@Gsalinas1506 los ajustes en vscode estan en un archivo que se llama settings.json el cual se puede acceder desde el mismo editor apretando `ctrl + shift + p` y empezando a escribir settings dice `Preferences: Open settings (JSON)`, ahí le agregas las 2 lineas para el linter y formatter

**Comment by MartinPinedaCatalan** [comment]
Vale gracias! deberia quedar asi:
![image](https://user-images.githubusercontent.com/69638653/90298956-396fa200-de62-11ea-9dc3-fad6ae39d541.png)

@alterdieg0 Donde aprendiste lo de los archivos JSON?

**Comment by alterdieg0** [comment]
@MartinPinedaCatalan que cosa específicamente de los archivos JSON? que los linter se editan desde ahí? está aquí [https://code.visualstudio.com/docs/python/linting](https://code.visualstudio.com/docs/python/linting)

**Comment by MartinPinedaCatalan** [comment]
En verdad es sobre que es un [https://es.wikipedia.org/wiki/JSON](archivo JSON) pero ya entendí. Y gracias por el link sobre edicion de linters!

**Comment by YehudaGurovich** [comment]
¿Usan tambien PyFormat?
¿Saben como hacer para que tab se considere como los 4 espacios automáticamente?

**Comment by difischer** [comment]
@YehudaGurovich yo agregué esto al settings.json
   "[python]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 4
    }

lo comprobé luego abirendolocon el notepad y efectivamente los tabs eran 4 espacios :)
Salu2!

**Comment by FdoTorres1** [comment]
Hola, @alterdieg0 o cualquiera que sea... Agregué la línea para el linter y me aparece así en settings.json:
<img width="644" alt="Screen Shot 2020-08-23 at 8 48 14 PM" src="https://user-images.githubusercontent.com/69602127/90993334-80584880-e582-11ea-9fc9-cd3bc26a83dd.png">

**Comment by difischer** [comment]
@FdoTorres1 ¡Te falta una coma después de la tercera línea!
