### ISSUE TITLE
Contenidos Actividad 10/08

### ISSUE THREAD

**Issue by Julius9** [IIC2233/Syllabus#22]
Hola! revisando el calendario del curso ( https://iic2233.github.io/calendario/ ) veo que este no se despliega por lo cual mi pregunta es ¿ Que contenidos entran en especifico en la actividad de mañana ?

**Comment by akaminetzkyp** [comment]
Modelación OOP. :)

**Comment by flobarrios** [comment]
Hola! entra todo lo que se encuentra en la carpeta semana-1 del repositorio contenidos. Por otro lado, que raro que no se te despliegue! Acabo de revisar y lo puedo ver perfectamente. Que browser usas ?

Saludos!

**Comment by Arcoirisky** [comment]
Lo probé y a mi me funciona bien. Dice que la Actividad 1 es de Modelación OOP

**Comment by entamburini** [comment]
Hola! igual puedes ver en el repositorio de contenidos, como se avisó en su momento, la materia entra hasta lo último subido :) (en el caso de controles, hasta la semana anterior) 
Que estés bien!
PD: Si me funciona el calendario :/ quizás no estás con una buena conexión :o

**Comment by Julius9** [comment]
Gracias por sus respuestas! :D 
@flobarrios uso Chrome pero quizás sea un problema de conexión como dice @entamburini por que por el navegador del celu tampoco se despliega, lo raro es que antes no tenia este problema.
