### ISSUE TITLE
Uso Namedtuple

### ISSUE THREAD

**Issue by etoteiza** [IIC2233/syllabus#22]
Hola! tengo una duda que no lo puedo aclarar.
Porque al usar namedtuples, el segundo argumento, en algunos casos los escriben como una lista de strings, y en otros casos lo escriben simplemente como un string separados por espacios.
ejemplo:
````
a = namedtuple("ejemplo", ["esto", "es", "un", "argumento"])

#es lo mismo a:

a = namedtuple("ejemplo", "esto es otro argumento")
````

**Comment by Mahund** [comment]
Hola @etoteiza!

Esto es debido **namedtuple** fue definido para que funcione bajo ambos *protocolos*.

En palabras simples los **nombres** para los atributos los puedes ingresar tanto con una lista como con un string separado por espacios.

Si quieres el detalle lo puedes ver [acá](https://docs.python.org/3.6/library/collections.html#collections.namedtuple)!

Espero te haya servido 😄
