### ISSUE TITLE
contraseña olvidada

### ISSUE THREAD

**Issue by cristobalmm** [IIC2233/Syllabus#22]
instalé Ubuntu pero olvide la contraseña de mi usuario por lo que no puedo instalar nadas más.

**Comment by lauracid** [comment]
Holaa @cristobalmm ! Si no has instalado nada te recomiendo que borres Ubuntu y lo instales de nuevo. Te recomiendo que revises la siguiente issue donde responden como realizarlo :)
* https://github.com/IIC2233/Syllabus/issues/18

**Comment by cristobalmm** [comment]
lo desinstale como decia en el foro. Sin embargo, cuando lo volvi a instalar me tiro error.[]
![Screenshot 2023-08-16 225327](https://github.com/IIC2233/Syllabus/assets/141957563/97b3ddf1-9228-4b85-9c20-b705d638c673)

**Comment by lauracid** [comment]
Holaa @cristobalmm 
Puede ser que se desinstaló ubuntu desde cmd y no desde powershell. Intenta desinstalarlo, luego abrir powershell como administrador y ahí instalar. Cuéntanos como te va!

**Comment by MrMcLean25** [comment]
Holaa, tengo el mismo problema, ya desintale ubuntu, lo volvi a instalar desde powershell administrador y sigo teniendo el mismo error.

**Comment by MrMcLean25** [comment]
Buenas tardes profesor, pude solucionar el problema, adjunto el link de la solucion: https://superuser.com/questions/1758361/error-code-wsl-service-createinstance-mountvhd-error-file-not-found

De igual manera muchas gracias por su preocupación.

**Comment by Hernan4444** [comment]
Hola @MrMcLean25 

Que bueno que lo lograste!! @cristobalmm puedes intentar con lasolución del link entregado en el comentario anterior y avisarnos si lograste solucionarlo please 😄 

Saludos!

**Comment by cristobalmm** [comment]
tambien lo logre, un compañero me ayudo la clase pasada
