### ISSUE TITLE
Problema con VSCode

### ISSUE THREAD

**Issue by Ignaciomendezp** [IIC2233/syllabus#22]
Hace un tiempo que tengo un problema con vscode, en el que no me corre el código tablero.py, el cual nos entregaron. Pregunté al respecto esto hoy en la ayudantía pero los ayudantes no pudieron ayudarme mucho. Al parecer, mi vscode esta usando la versión de python 2.7, ya que me tira un error que corresponde a esa versión, la cosa es que en la barra de estado (en la parte inferior izquierda de la pantalla) me sale que efectivamente la versión que esta usando  vscode es la del 3.7. Desinstalé vscode, lo volvi a configurar y me paso lo mismo. Mi código corre perfecto en el IDLE, pero al probarlo en vscode me tira el error en el tablero. Quería saber cómo es posible arreglar esta situación.
Muchas gracias

**Comment by KnowYourselves** [comment]
Hola @Ignaciomendezp! 

Antes de poder ayudarte, te tengo dos preguntas:

1. Que sistema operativo tienes?
2. Como estás ejecutando tu programa?

Quedo atento!

**Comment by Ignaciomendezp** [comment]
Tengo macOS
Lo ejecute con ctrl + alt + n = Run code, aca me tira el error del tablero
Y con 'Run python file in  terminal' me tira el erroe de 'can't open file (mi codigo) [Errno 2] No such file or directory'

**Comment by KnowYourselves** [comment]
Para correr tu programa en VSCode correctamente haz lo siguiente:

1. Haz click en la pestaña terminal de las opciones de la barra de herramientas superior.
2. Haz click en abrir una nueva terminal, esto abrirá una terminal dentro de VSCode.
3. En la terminal escribe `python3 <programa>`, donde `<programa>` sería el archivo py a ejecutar.

Cuentame como te va!

**Comment by Ignaciomendezp** [comment]
Me da  el mismo error que con 'Run python file in terminal' (can't open file <mi codigo> [Errno 2] No such file or directory')

**Comment by KnowYourselves** [comment]
Podrías mandar un pantallazo de como lo estás ejecutando?

**Comment by Ignaciomendezp** [comment]
Ya lo logré ejecutar, lo que pasa es que no me encontraba en la carpeta correspondiente al ejecutar el código. Ahora para ejecutarlo, siempre tengo que abrir el terminal o hay un 'atajo' de teclas para ejecutar el código?

**Comment by KnowYourselves** [comment]
Yo en lo personal uso VSCode y la terminal para ejecutar mi código. Si quieres un atajo puedes instalar una extensión de VSCode llamada _Code Runner_ que te permite correr el código con un _shortcut_.

Espero haberte ayudado!
