### ISSUE TITLE
Problema path relativo

### ISSUE THREAD

**Issue by iastruque** [IIC2233/syllabus#22]
Tengo un archovo T00.py en mi repositorio en la catpeta Tareas/T00 y en ella tengo guardados los archivos entregados para la tarea (seguidores.csv, usuarios.csv, etc.). Pero a la hora de abrir los archivos solo me funciona con este path:
path_usuarios = os.path.join("Desktop", "iastruque-iic2233-2020-1", "Tareas", "T00", "usuarios.csv")
y no con:
path_usuarios = os.path.join("usuarios.csv")
para luego abrir con:
with open(path_usuarios, 'rt', encoding="utf-8") as archivo:
    usuarios = archivo.readlines() 

Hasta ahora e trabajado con el primer path mencionado, pero se que no es lo correcto mantenerlo así.
¿Que me recomiendan?

**Comment by Tito0906** [comment]
Holaa! @iastruque, 

¿Podrias especificar cuál es el error que te aparece cuando lo intentas con _path_usuarios = os.path.join("usuarios.csv")_ ? 
¿Además, estás completamente seguro de que el archivo T00.py que creaste está en la misma carpeta que los demás archivos (usuarios,csv, etc)?

**Comment by iastruque** [comment]
Al usar esto --> path_usuarios = os.path.join("usuarios.csv") me aparece
PS C:\Users\ignac> & C:/Users/ignac/AppData/Local/Programs/Python/Python37/python.exe c:/Users/ignac/Desktop/iastruque-iic2233-2020-1/Tareas/T00/T00.py   
Traceback (most recent call last):
  File "c:/Users/ignac/Desktop/iastruque-iic2233-2020-1/Tareas/T00/T00.py", line 10, in <module>
    with open(path_usuarios, 'rt', encoding="utf-8") as archivo:
FileNotFoundError: [Errno 2] No such file or directory: 'usuarios.csv'

El archivo T00.py lo creé en Visual Studio y luegolo guarde en la carpeta T00 de mi repositorio junto a los archivos .csv

**Comment by Tito0906** [comment]
Es posible que Visual Studio esté trabajando desde una carpeta diferente a la que contiene el archivo T00.py. 

Prueba haciendo lo siguiente desde Visual Studio:

- En el menú superior apreta en File (o archivo)
- Selecciona en Open Folder (o abrir archivo)
- Entra por este menú hasta la carpeta donde tienes tu archivo (entra a tu repositorio y a la carpeta T00)
- prueba correr el archivo con el path (usuarios.csv)

**Comment by felipehen** [comment]
hola!! Estoy teniendo este mismo problema, y e realizado todo lo que nos han sugerido que hagamos, la verdad es que esto me soluciono los problemas que tenia en los archivos de Usuarios y Seguidores, pero sigo sin poder hacer funcionar el archivo Posts.

ocupando los siguientes comandos:

with open(ArchivoPost) as archivo:
    for linea in archivo:
        print(linea)

llego al siguiente error:
Traceback (most recent call last):
  File "c:\Users\felip\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "c:\Users\felip\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1527: character maps to <undefined>

**Comment by DCCollao** [comment]
@felipehen ese problema ya fue tratado en la issue #16. Si aún así no logras solucionarlo, por favor comenta dentro de esa issue, así mantenemos los temas ordenados.

**Comment by iastruque** [comment]
Muchas gracias al abrir la carpeta me resultó

**Comment by DCCollao** [comment]
@iastruque No cierres las issues cuando resuelvan tu problema, pues le podría servir a alguien más!
