### ISSUE TITLE
Error con importar y abrir dcciudad.pyc

### ISSUE THREAD

**Issue by bozziuc** [IIC2233/Syllabus#22]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

Viendo los archivos entregados para la Tarea 1, sin modificar nada, veo que tanto ejemplo.py y red.py me dan un error. El nombre del módulo dcciudad está subrayado con unas "olas" amarillas, los nombres de los archivos aparecen en amarillo en vez de blanco, y con un 1 amarillo al lado. ¿Cómo puedo arreglar ese problema?
De antemano muchas gracias.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by josevalenzuelam** [comment]
Tengo la misma duda, me aparece que no se puede abrir (dcciudad.pyc) con la versión 3.11.8 siendo que según el enunciado esta si lo debería aceptar. Como se puede solucionar?

**Comment by navila1** [comment]
A mi tampoco me funciona abrir dcciudad.pyc en VS, me aparece lo siguiente: "The file is not displayed in the text editor because it is either binary or uses an unsupported text encoding."

**Comment by j0secr** [comment]
Yo también tengo el mismo error, pero asumí que fue un error de dedo y que el archivo era "py." para poder continuar con la tarea,

**Comment by Hernan4444** [comment]
Hola a todos/as,

Lo que ocurre con el archivo `.pyc` (no es un error de dedo, es `.pyc`)  es que corresponde a un archivo Python **Compilado**. 

Que un archivo esté compilado es que se tomaron cada línea del código original (del archivo `.py`) y se transformaron en otro lenguaje que una máquina si o si entenderá (en este caso Python), pero que ya no es legible al ojo humano, y tampoco para VSCode o cualquier IDLE. Pueden ver esto como un `.exe` o un `.dmg` es son archivos que se ejecutan con doble click, pero no sabemos cómo está por dentro construido. Esto es lo mismo con un `.pyc`, este ya está 100% listo para ser usado, pero no podremos ver su contenido.

En este caso, un archivo `.pyc` se debe tratar igual que un archivo `.py`. Es por esto que les entregamos `ejemplo.py` donde se hace `import dcciudad` y se ocupan sus 3 funciones de `dcciudad` sin ningún problema. Luego, cuando ejecutamos este archivo python (desde la terminal escribir `python3 ejemplo.py`), se puede ver en consola que todo funciona bien. 

Ahora, si es que a alguien, sin modificar nada de `ejemplo.py` hace `python3 ejemplo.py` (o `py ejemplo.py` o `python ejemplo.py`) y no le funciona, ahí si hay un error de que su computador no está logrando ejecutar `dcciudad.pyc` correctamente y necesitamos que nos avisen, indicando qué error sale, para poder analizarlo y resolverlo.


Respecto a que en un módulo esté subrayado en amarillo, eso no implica que haya un error, solo es un warning de la IDLE (asumo que VSCode) porque no logra entender qué es dcciudad o algún warning similar, pero no olvidar que VSCode solo es para programar, pero quien ejecutará todo es python desde la terminal. Por lo tanto, lo importante es que desde la terminal puedan hacer `python3 archivo.py` y todo funcione bien.


Saludosヾ(＾-＾)ノ

ps: recuerden que hay diferentes tipos de issues, dado que el `.pyc` es un archivo de la T1, mejor hacer una issue del tipo "Tarea" para que así sea más fácil diferenciar la temática de cada issue.

**Comment by j0secr** [comment]
Gracias por la aclaración!

**Comment by bozziuc** [comment]
¡Muchas gracias!

**Comment by josevalenzuelam** [comment]
A mi me sigue saliendo error, me arroja lo siguiente.
ImportError: bad magic number in 'dcciudad': b'\xef\xbf\xbd\r'

**Comment by Hernan4444** [comment]
Hola @josevalenzuelam 

¿Cómo estás ejecutando el archivo? (con qué comando ejecutas `ejemplo.py` en tu consola?)

Una vez identificado ese comando, ya sea `py3`, `python`, `python3`. Intenta hacer:

`[COMANDO] --version` y nos puedes indicar qué aparece en tu consola?

Por ejemplo, en mi computador yo ejecuto todo con `python3`. Así que en consola hice `python3 --version`

![image](https://github.com/IIC2233/Syllabus/assets/15641721/23dc45b7-570b-497b-8953-0622fe4ef80d)

Quedamos atentos

**Comment by josevalenzuelam** [comment]
Hola! Con python 3.11.8 
Creo que lo solucione, no estoy segura ya que sigue saliendo problema pero almenos ahora si corre. 
Adjunto imagen
![T1_ejemplo](https://github.com/IIC2233/Syllabus/assets/157542870/c501bba3-b46d-4baf-965c-b4440b97e467)

**Comment by Hernan4444** [comment]
Respecto al error que me comentas despues

Primero: por favor no editar el comentario agregando más información, sino escribir otro comentario. En otro caso, ocurre lo que pasó aquí donde mi respuesta no hace mención de tu error sobre pylance porque al momento de redactar mi respuesta, no estaba ese tecto.

Segundo, sobre ese error es solo que Pylance (una extensión de Python de VScode) no logra entender dcciudad, y eso es lo comentado en la respuesta anterior

>  la IDLE (asumo que VSCode) no logra entender qué es dcciudad o algún warning similar, pero no olvidar que VSCode solo es para programar, pero quien ejecutará todo es python desde la terminal. Por lo tanto, lo importante es que desde la terminal puedan hacer python3 archivo.py y todo funcione bien.

Así que no te preocupes, esto ocurre cuando un programa externo (Pylance de VScode) intenta entender el archivo compilado y no lo logra. Mientras desde terminal funciona todo bien, es que estás bien encaminado.

Saludosヾ(＾-＾)ノ

**Comment by josevalenzuelam** [comment]
Buenisimo!! mil gracias, así lo haré

**Comment by coniverav** [comment]
Hola, no entendí bien lo que hay que hacer con el archivo dcciudad.pyc.
Al final lo dejamos como está (que no lo puedo visualizar pero sí ejecutar) pues no es necesario verlo para la tarea, o entendí mal? 🙃

**Comment by coniverav** [comment]
gracias!
