### ISSUE TITLE
Posible error en el script generar_archivos.py

### ISSUE THREAD

**Issue by maguerrap** [IIC2233/Syllabus#22]
Creo que hay un error en el script generar_archivos.py, ya que leyéndolo me pareció que ser mago es una raza y no aparece en ninguna parte la raza maestro. Pregunto porque creo que no puedo modificar el script.

**Comment by Hernan4444** [comment]
@maguerrap, gracias por avisar. Fue un error mio 😅. Acabo de pushear el _script_ arreglado.
Saludos!!
