### ISSUE TITLE
Error al instalar pyqt5-tools

### ISSUE THREAD

**Issue by teverde** [IIC2233/syllabus#220]
Al instalar pyqt5 no tengo problemas, pero cuando intento instalar pyqt5-tools me aparece un mensaje pidiendo que actualice pip siendo que ya lo hice

![image](https://user-images.githubusercontent.com/48270797/57714622-e8f80c00-7642-11e9-90a2-f1ad1f0dceb4.png)

**Comment by Arcoirisky** [comment]
Tienes otras versiones de Python por casualidad?

**Comment by teverde** [comment]
> Tienes otras versiones de Python por casualidad?

revisé y es la versión 3.6.8

**Comment by Arcoirisky** [comment]
Pero no tienen ningún Python 2.Algo ¿no?

Además ¿probaste con instalar las librerías directo en el cmd en vez de la consola de Pycharm?

**Comment by teverde** [comment]
> Pero no tienen ningún Python 2.Algo ¿no?
> 
> Además ¿probaste con instalar las librerías directo en el cmd en vez de la consola de Pycharm?

buena idea, probé hacerlo desde el cmd y lo logré instalar bien.
Por si alguien lo lee, saqué las instrucciones de acá:
[https://datatofish.com/upgrade-pip/]

**Comment by DCCollao** [comment]
Hola! Para que más gente lo vea es mejor que no cierres las issues una vez está respondida tu duda.
