### ISSUE TITLE
Duda sobre Thread en ejercicio 1.2 | Semana 5

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#220]
Hola!
Estuve haciendo el ejercicio 1.2 de la semana y no entiendo por qué no ocurre paralelismo en los threads que creé. Debiese comenzar con los print del "hilo_3" e "hilo_2" porque su periodo del time.sleep es menor, pero se ejecutan los print de manera secuencial como si no existiese paralelismo 😮

edit: ahora dejé hilo_1.start() en la última línea y ocurre el mismo print 😮😮

![imagen](https://user-images.githubusercontent.com/50121013/115098981-26393880-9f01-11eb-835d-dcda0d728fb0.png)

**Comment by aaossa** [comment]
Hola @jamigone , lo que pasa es que en `target` estás invocando la función `deletrea_palabra`, no estás pasando la función como argumento 🤔 Recuerda que si quieres pasarle al *thread* una función que requiere argumentos, debes usar el constructor de la siguiente manera:

```python
t = Thread(target=funcion, args=(arg1, arg2), kwargs={"arg3": arg3})
```

Si tienes alguna otra duda pregnta por acá mismo no más ✌️ ¡Éxito con el estudio!

**Comment by jamigone** [comment]
Gracias @aaossa 😄 ! Ahora sí funcionó
