### ISSUE TITLE
Coordenada a lanzar luego de bomba especial

### ISSUE THREAD

**Issue by nogalde** [IIC2233/syllabus#220]
Hola, cuando lanzo una bomba especial, luego puedo volver a disparar en alguna casilla que haya sido "afectada" por la bomba especial?

**Comment by vicentevegaulloa** [comment]
Hola @nogalde !

No puedes. Miralo de esta manera, si la celda está marcada con una X o una F, no puedes elegir como **input** esa coordenada.
