### ISSUE TITLE
duda equipos en parametros

### ISSUE THREAD

**Issue by Afro27** [IIC2233/syllabus#220]
Puedo modificar el diccionario EQUIPOS en parametros.py para cambiar los nombre de los equipos que estan en MAYUSCULAS a solo la primera letra mayuscula para que este de acuerdo con los recibido de el archivo contrincantes.csv y pilotos.csv .

**Comment by jeschuwirth** [comment]
Hola!

Por lo general no sería problema, pero es sencillo trabajar con el nombre en mayúscula y la idea de que lo parámetros estén siempre en mayúscula es que el ayudante sepa inmediatamente que viene de ahí y que no. 

**HINT:** te recuerdo el siguiente métodos de string:
```
>>> s = 'sdsd'
>>> s.upper()
'SDSD'
```
- Ejemplo sacado del siguiente [link](https://stackoverflow.com/questions/9257094/how-to-change-a-string-into-uppercase)

Por esas razones no puedes cambiar los nombres de los equipos en parametros.py

Suerte!.
