### ISSUE TITLE
Duda sobre parametros.py

### ISSUE THREAD

**Issue by FabriRandon** [IIC2233/Syllabus#220]
¿Puedo crear una carpeta constante con diferentes tipos de clasificaciones de parámetros para ordenar mejor mi código?

Me refiero a tener por ejemplo un archivo llamado parametros_backend.py, textos_juego.py etc...

**Comment by Francisco-Aguilera-xd** [comment]
Hola!
No hay problema! De hecho, vuelves más ordenado tu código :)
