### ISSUE TITLE
Entregable

### ISSUE THREAD

**Issue by julioag** [IIC2233/Syllabus#220]
Hola, tengo una duda con respecto a los algoritmos, si es que llegase a encontrar un algoritmo "mejor" que los que ya elegí, si decidiera optar por este en cambio, me bajarían la nota?
Gracias.

**Comment by IchottMano** [comment]
@julioag Hola!

La idea del entregable es que nosotros los ayudantes tengamos una idea de como están resolviendo el problema a modo de saber como ayudarlos mejor.
Si encuentras un mejor método para resolver tu tarea, no se te descontará puntaje, asi que no debes preocuparte!

Saludos y mucha suerte con la tarea!
