### ISSUE TITLE
Usar Códigos Ayudantias

### ISSUE THREAD

**Issue by stgoa** [IIC2233/Syllabus#220]
Puedo copiar partes de los códigos de las ayudantías?
podría cambiarle el nombre a las variables pero me gusta los que ya les dieron...

**Comment by diegonavarrovergara** [comment]
Me sumo a la pregunta

**Comment by fringlesinthestreet** [comment]
Sí se puede utilizar el código de las ayudantías, al igual que el de las clases.

**Comment by stephichau** [comment]
Si puede, pero no olviden dar referencia de donde lo sacaron :).
