### ISSUE TITLE
Ejercicio propuesto semana 02: Ejercicio 3.2

### ISSUE THREAD

**Issue by rldelafuente** [IIC2233/syllabus#220]
Hola! Tengo una duda con la función presentarse: [_¡Hola! Mi nombre es {nombre} y soy {tipo}. (Hint: puedes usar type(instancia).__name__ _]

Esto fue lo que hice:
**Clase Madre**: Músico. **Clase hija:** cantante, guitarrista y baterista. No se cómo implementar esta función, ya que se encuentra en mi clase madre, pero debe cambiar para cada tipo de clase hija (si es cantante, guitarrista y baterista). Puede ser que no entienda el Hint...

En resumen, ¿como hago que un método de una madre vaya cambiando para una clase hija? Podría crear un método presentarse para cada tipo de clase, pero creo que no es la idea si nos están enseñando herencia.

**Comment by fdoflorenzano** [comment]
Hola @rldelafuente,

En general, si requieres distinto comportamiento en cada subclase, entonces lo más directo es re-implementar el método en cada subclase. El hecho de que esté `presentarse` en la clase madre, no significa necesariamente que ahí debe implementarse solamente.

Ahora, este es un caso específico donde puede que se pueda implementar el mismo comportamiento en la clase madre, y a eso va el _hint_.  Al ejecutar `type(instancia)`, este retornará el nombre de la clase a la cual se instancio, y accediendo a `__name__`, se tendrá el nombre de ella. Intenta usar ese código y ejecutalo para ver como se comporta, tal vez ahí de haga más sentido.

Saludos.
