### ISSUE TITLE
Caso de enviar archivo erróneo que estaba sin terminar al terminar

### ISSUE THREAD

**Issue by Felipe-Lopeh** [IIC2233/Syllabus#220]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Ayer en la tarde de ayudantía de progra, estaba terminando mi archivo main.py y lo logré, haciendo una función recursiva para esta, lo que salía bien, al hacer push en mi repositorio al ver que se enviaron los archivos me di por hecho que los había enviado bien, lo que revisé esta mañana haciendo pull a los repositorios para actualizarlos y revisar la AC2, quise ver si me pude haber equivocado en algo de la tarea, el archivo dccultivo estaba bien, el readme también pero cuando revisé el main.py, era el archivo sin terminar que tenia al principio, y al haber hecho pull, en todas los repositorios, no se me guardó el archivo main.py terminado.

Y eso que expliqué del main en el readme, pero no se si me dejen enviar un ultimo commit con nota maxima 6, ya que obvio pasaron 2 dias ya, así que no se que hacer ya que se consideraría que el readme está incompleto lo que me bajaría más la nota, si me ayudaran con este tema lo agradecería mucho, y si ya no puedo hacer nada, que me lo mencionen.

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Hernan4444** [comment]
Hola @Felipe-Lopeh 

Lamento informar que lo solicitado no es posible sin que utilices algún cupón. El descuento se calcula únicamente en base a 2 factores:
- El atraso que tenga el commit a revisar.
- Cantidad de cupones utilizados.

Si un archivo no se subió correctamente, eso justamente es una responsabilidad del estudiante, ya que al momento de hacer push se debe comprobar que todo salió correctamente.

Por lo tanto, si quieres optar a nota máxima 6, deberás contestar el formulario de entrega atrasada indicando el commit de hoy, pero con 1 cupón. De este modo, la penalización será de solo 1 día de atraso. 

De todas formas, ten en consideración que la T1 es la que menos ponderación de las 4 tareas, y solo dispones de 2 cupones en todo el semetre.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con el curso! 🦖
Saludosヾ(＾-＾)ノ

**Comment by Felipe-Lopeh** [comment]
Ahh ok, bueno, para la proxima revisaré bien lo que envio, gracias por los comentarios
