### ISSUE TITLE
Problema al designar variables dentro de clase

### ISSUE THREAD

**Issue by tomasvasquezp** [IIC2233/Syllabus#220]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Estoy teniendo problemas al crear las variables de la clase combatientes, en donde, por ejemplo, la variable vida_maxima recibe el tipo de gato y no la cantidad de vida maxima del gato como debería ser, como se puede arreglar??

gracias!

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by CrisDonosoMaass** [comment]
Hola!
Puede que estés heredando mal la clase gato al combatiente. Puedes explicar que hiciste para heredar porfis?

**Comment by tomasvasquezp** [comment]
lo que hice fue hacer súper.().__init__(todas las variables van acá, incluyendo *args, **kwargs) y listo, eso sería

**Comment by tomasvasquezp** [comment]
igualmente hice git push por si quieres verlo con más detalle

**Comment by CrisDonosoMaass** [comment]
Revise tu repo, parece que cuando usar super() agregas self como argumento, esto puede estar causando que no te calcen los valores. 

Trata de hacer un print de un gato_combatiente en combatiente.py y dime como te va.

**Comment by tomasvasquezp** [comment]
me seguía saliendo lo mismo, pero probe poniendo los atributos directamente, es decir, sin utilizar super().__init__ y poniendo exactamente como estaba en la clase padre, eso cuenta como herencia?

**Comment by tomasvasquezp** [comment]
ahí al final no se que hice jajaj, pero me terminó saliendo, al final puse super().__init__ sin el self y algo más y me terminó saliendo, gracias por la ayuda!
