### ISSUE TITLE
Mapa del juego: Número de partes

### ISSUE THREAD

**Issue by Dafnemami** [IIC2233/Syllabus#220]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En la sección flujo del programa se señala que el mapa está divido en dos partes. Luego, en la sección 4.5  Ventana de juego se señala que deben ir 3 áreas, como muestra la fig 8. Me quedo con lo segundo?

**Comment by ivanvlam** [comment]
Hola @Dafnemami ! Exacto, en la sección de flujo se hace referencia a que existen carreteras y ríos como dos tipos de áreas. Sin embargo, al crear el mapa debes incluir 3 áreas de juego, que contenga como mínimo una carretera y un río, la tercera puede ser cualquiera de las dos y queda a tu elección.
