### ISSUE TITLE
no utilizar "else" al menos que sea necesario es considerado mala práctica?

### ISSUE THREAD

**Issue by cperez20** [IIC2233/syllabus#221]
Hola, mi pregunta va por el lado en que muchas veces en mi código yo realizo "if/elif" pero si no se cumple ninguna simplemente quiero que siga corriendo el código de mas abajo (considerando que me asegure que no se imprima o realice alguna acción que no quiero). Respecto a esto muchos usuarios de stackoverflow dicen que no agregarían el "else" en ese caso para ahorrar código y porque lo consideran más legible, mientras que unos pocos lo agregarían de todos modos por la misma razón de que sería más entendible el código para ellos de esa manera.

Por mi parte, yo encuentro más cómodo no utlizar "else" al menos que sea necesario pero podria considerarse mala práctica?

**Comment by danckoo1** [comment]
Hola! Si te lo preguntas por los descuentos de malas prácticas de la tarea, no se considera como una mala práctica. De igual forma en cualquier otro contexto, yo creo que es más un tema de preferencia personal, ya que nunca he escuchado que sea catalogado como una mala práctica.
