### ISSUE TITLE
Problema con el encoding de pyqtSignal

### ISSUE THREAD

**Issue by FGarciaVarela** [IIC2233/Syllabus#221]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo un problema utilizando pyqtSignal, debido a que cuando intento implementarlo me arroja;
UnicodeEncodeError: 'ascii' codec can't encode character '\xf1' in position 2: ordinal not in range(128)

Busqué en goolgle y no encontré nada al respecto pero probando me di cuenta que era al guardar una pyqtSignal (tipo; variable = pyqtSignal() ).

Muchas gracias por su tiempo.

**Comment by tqmbanados** [comment]
Hola @FGarciaVarela! Tu problema nace de ocupar una `ñ` en tu programa de alguna forma no permitida, o sin agregar el *encoding* correcto. En las tablas ASCII básicas (un sistema que ocupa código hexadecimal para codificar varios de los caracteres comunes) `\xf1` es una posición inexistente. Sin embargo, en las tablas ASCII extendidas, ese valor *hex* corresponde a la `ñ`. Te recomiendo buscar donde puedes estar codificando erróneamente tu programa valores con ñ.

**Comment by FGarciaVarela** [comment]
Gracias!

> Hola @FGarciaVarela! Tu problema nace de ocupar una `ñ` en tu programa de alguna forma no permitida, o sin agregar el _encoding_ correcto. En las tablas ASCII básicas (un sistema que ocupa código hexadecimal para codificar varios de los caracteres comunes) `\xf1` es una posición inexistente. Sin embargo, en las tablas ASCII extendidas, ese valor _hex_ corresponde a la `ñ`. Te recomiendo buscar donde puedes estar codificando erróneamente tu programa valores con ñ.

**Comment by ignaciacorrea** [comment]
Hola! Tengo el mismo error, pero busqué y no tengo ninguna ñ, entonces no se cómo arreglarlo.
Gracias
