### ISSUE TITLE
Problema ejecución ProgressBar

### ISSUE THREAD

**Issue by jahernandez2** [IIC2233/Syllabus#221]
Hola, pasa que no entiendo por qué mi barra de progreso no se va actualizando en el for a medida que avanza. Tengo desordenadas las posiciones en mi ventana, pero debería ejecutarse de igual manera. Adjunto foto y gracias de antemano.
![progra ussue](https://user-images.githubusercontent.com/62116520/169775923-ce178161-fe44-41c9-890e-13fb8b43b934.png)

**Comment by JJJGGGG** [comment]
Qt funciona pésimo si usas sleep. Mejor usa un qtimer para manejar la actualizacion de la progress bar.
