### ISSUE TITLE
paths en parametros.py

### ISSUE THREAD

**Issue by japachecoc** [IIC2233/Syllabus#221]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda en esta parte del enunciado:

<img width="1165" alt="Captura de Pantalla 2023-04-20 a la(s) 23 35 49" src="https://user-images.githubusercontent.com/127993063/233535102-8be561bb-2718-40c4-92f5-1fe0fb3cc08e.png">

No se a que se refiere con "Además, debes agregar cualquier valor constante en tu tarea, junto con los paths que utilices". **Esto quiere decir que podemos agregar todos los paths que usemos en el main al archivo parametros.py y tambien cualquier valor constante que podamos tener?**

**Comment by Rotopikus** [comment]
Hola!!

Si, los valores fijos de tu código debes guardarlos en el archivo parametros.py. Esto se hace para evitar que se haga hardcoding en el código.

Espero haber aclarado tu duda!!
