### ISSUE TITLE
Duda ejercicio 3 de "ejemplos y aplicaciones" (Semana 5): Codigo funciona correctamente sin necesidad de usar Locks (Creo).

### ISSUE THREAD

**Issue by MathiasPrett** [IIC2233/Syllabus#221]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

Hola. Tengo una duda con el ejercicio 3 de "ejemplos y aplicaciones" de la semana 5. El ejercicio es el del **Circo**. Resulta que de acuerdo a lo que me dice el enunciado, es que debo intervenir el código para que se venda correctamente la cantidad de entradas que se deben vender. Por lo cual decidí agregar un **Lock** a cada de las funciones de los vendedores que venden entradas al circo. Sin embargo, me di cuenta que **no poniéndole un Lock** a esas funciones, se venden las 1.000.000 entradas igualmente. **En pocas palabras el código me funciona bien con o sin Lock**.

Lo esperable es que no funcione, y a lo largo del flujo un problema ocurra cuando uno de los tres locks "chocan" en algún momento. Una hipótesis es que solo un Thread (un solo trabajador) esté funcionando, y que por eso no ocurren problemas. Pero no se como verificar eso, y probablemente como este hecho el código, sí están funcionando los 3 simultáneamente.

En resumen, quiero saber si hay algo que estoy haciendo mal, o si efectivamente no es necesario implementar un Lock para este caso, para que se vendan las 1.000.000 entradas correctamente.

Gracias!

![image](https://github.com/IIC2233/Syllabus/assets/142269948/788d0ecc-19c3-4592-a30e-4d5172b677cf)

**Comment by Dvckhv** [comment]
Hola @MathiasPrett !

Estuve investigando y dentro de la actualización 3.10 de python se "arregló" **algunas** cosas relacionadas con el uso de threads y operaciones no atomicas. 
No encontré donde lo especifican para citarlo pero puedes probar correr el codigo con una version anterior de python y generará problemas. Adjunto un codigo y su resultado ejecutandolo en python 3.9.x y 3.10.x.

**Comment by MathiasPrett** [comment]
@Dvckhv Perfecto, entiendo. Muchas gracias!
