### ISSUE TITLE
Duda menú gatos

### ISSUE THREAD

**Issue by francorreaandrades** [IIC2233/Syllabus#221]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!!

En caso de que en el menú en el que el usuario debe seleccionar qué combatiente quiere evolucionar se asume que el input ingresado es válido?? O también debe ser a prueba de errores?? Que en el enunciado se especifica que se debe hacer en los otros 2 menús, pero no se dice nada de que debe hacer el programa en este caso.

**Comment by CrisDonosoMaass** [comment]
Hola!

Todos los menús deben ser a prueba de errores. Si bien no sale específicamente en ese menu, en el primer párrafo de menús dice que deben ser todos.

Suerte!

**Comment by francorreaandrades** [comment]
y en ese caso se vuelve a imprimir el menu de gatos o se pone error y no se efectua la compra, regresando al menu de tienda??

**Comment by CrisDonosoMaass** [comment]
Hola!

Ustedes deben ver como gestionar los errores en los menús, pero te recomiendo siempre hacer print de que error ocurrió para que el usuario entienda que hizo mal.
