### ISSUE TITLE
Duda sobre funcionamiento de las threads

### ISSUE THREAD

**Issue by imuoz** [IIC2233/syllabus#221]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Me llama la atención la forma en la que se ejecutan los threads y no logro entender como el computador decide que tarea hacer y cuál no. **En si mi pregunta es, ¿Cómo decide el sistema operativo qué threads ejecutar y cuantas instrucciones?**

**Comment by Juampisaez** [comment]
Hola @imuoz 
No se si entendi bien tu pregunta. Pero a mi lo que me ayudaba a entender como funcionaban los threads, era una forma de ejecutar instrucciones automaticamente, y estas instrucciones tu se las vas dando dentro de la funcion o metodo que quieras ejecutar. Normalmente estos se hacen dentro de un ciclo, mientras se cumpla una condición por ejemplo, y tu decides en que momento ejecutar el thread a nivel de codigo.

No se si conteste bien tu pregunta, o me desvie.
Quedo atento :)

**Comment by imuoz** [comment]
Claro, pero me refiero a que si tengo dos threads funcionando a la vez a veces se ejecutan dos instrucciones de uno, después una del otro y así de forma que pareciera ser aleatoria, por eso salia el problema del contador que sale en los contenidos. Pero me surge la duda de si es realmente aleatoria

**Comment by Juampisaez** [comment]
Perdón lo tarde, en el caso que tu comentas de los contenidos, mas que sea aleatoria cada thread va a ejecutarse por separado y va tener instrucciones que serán independientes entre los threads, pero como trabajan sobre el mismo contador, se muestran de forma distinta. De todos modos existen formas para poder controlar el orden en que se ejecuta cada thread, en los contenidos creo que esta muy bien explicado.
