### ISSUE TITLE
Error game.py

### ISSUE THREAD

**Issue by tomasrivera** [IIC2233/Syllabus#221]
Al final del modulo sale game.py

```python
    def keyPressEvent(self, event):
        if event.key() == Qt.Key_S:
            variables.GAME_INTERFACE.save_game()
```
No debería ser guardar_juego()?

**Comment by andresfdezc** [comment]
Funciona igual, pues si te fijas más arriba `save_game()` utiliza `guardar_juego()`:
```python
    @staticmethod
    def save_game():
        variables.GAME_INTERFACE.guardar_juego()
```

**Comment by iqacevedo** [comment]
Hola, 

No debes preocuparte por eso, en el enunciado se especificó que guardar_juego solo se llamará cuando se oprima el botón Guardar. No usaremos la tecla S para llamar a la función guardar_juego.

Saludos !

**Comment by tomasrivera** [comment]
Bueno gracias, solo preguntaba porque me tiraba error :smile:
