### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by andreslyon** [IIC2233/Syllabus#221]
cuando un atributo de mi clase puede ser cualquier cosa (int, float, str o algun objeto), que debo poner
despues del atributo? es decir, + atributo_cualquiera: ???

**Comment by fvr1** [comment]
Puedes poner `*` de tipo de dato y especificar que eso significa cualquier tipo de dato.

**Comment by asdegoyeneche** [comment]
Es necesario incluir las clases de las estructuras de datos en el diagrama de clases?

**Comment by rpalmaotero** [comment]
@asdegoyeneche sí
