### ISSUE TITLE
Error Qtimer

### ISSUE THREAD

**Issue by nrrosenberg** [IIC2233/syllabus#221]
hola, 

Al crear un Qtimer dentro de una objeto de clase Qobject, y timer.start(), me tira el error: 
"QObject::startTimer: Timers can only be used with threads started with QThread"

**Comment by lily416** [comment]
Hola 😄 

¿Podrías subir tu código a tu repositorio y decirnos en qué archivo llamas al QTimer? 
Es para que podamos ver qué es lo que está pasando, tenemos varias teorías de lo que podría ser, pero necesitamos ver el código para estar seguros :eyes:

**Comment by nrrosenberg** [comment]
lo acabo de subir, es el archivo enemigo.py

**Comment by lily416** [comment]
Aparentemente los QTimer sólo sobrevive si se encuentra dentro del _loop_ del `app exec` 🤔
 
Por lo que si pones:
```python
if __name__ == '__main__':
    app = QApplication([])
    enemigo_prueba = Enemigo_normal()
    sys.exit(app.exec_())
```
en vez del: 
```python
enemigo_prueba = Enemigo_normal()
``` 
parece funcionar correctamente.

Ojala que esto arregle el problema 🙏 
Pruebalo y avísanos si funciona 😉

**Comment by nrrosenberg** [comment]
Ahi funciona, Muchas gracias!!
