### ISSUE TITLE
Slices

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#221]
Hola, 
Getitem usa slices para sacar varios elementos a la vez... ¿los slices cuentan como estructuras de datos de python -> no podemos usarlos -> nuestro getitem solo responde a ints? ¿O **debemos** usarlos y que getitem responda a slices?

EDIT: Lo mismo para setitem, porque ahí los slices complican todo :(

**Comment by yoavnavon** [comment]
Hola! No tienes para que implementar slices en tus estructuras, si quieres puedes hacerlo pero depende de ti.
