### ISSUE TITLE
inicializar en herencias

### ISSUE THREAD

**Issue by Mendez69** [IIC2233/syllabus#221]
no entendí bien cuándo es necesario agregar el Clase.__init__ en los atributos de una sub clase y cuándo no se hace nada. Gracias!

**Comment by fdoflorenzano** [comment]
Hola @Mendez69,

Si se llama a el constructor de la superclase desde una subclase, mediante `SuperClase.__init__(self, ...)` o `super().__init__(...)`, es por que se desea ejecutar el código dentro de `SuperClase.__init__`. Si no se llama, es porque no se desea ejecutar esa sección de código.

¿Qué consecuencias tiene lo anterior? Los constructores suelen ser el lugar donde se inicializan los atributos de una instancia. Al ejecutarse ese código, se crean los atributos. Si `SuperClase` tenía una definición de atributos en su `__init__` y `SubClase` no lo llama, entonces las instancias de `SubClase` no tendrán los atributos definidos en `SuperClase`, a menos de que `SubClase` los defina por separado en otra sección de código. Pero, si `SubClase` si llama a `SuperClase.__init__`, entonces las definiciones de atributos si quedarán definidas en las instancias de `SubClase`  también.

Hay un ejemplo de código en la cápsulas de dudas donde se menciona esto, en esta [parte](https://youtu.be/bqMi28PUCqU?t=861).

Espero se entienda, cualquier duda nos avisas.
Saludos.
