### ISSUE TITLE
Posibilidad de subir soluciones de Tareas pasadas

### ISSUE THREAD

**Issue by MathiasPrett** [IIC2233/Syllabus#222]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido

Hola. Primero disculparme si mi duda se contesta en alguno de los reglamentos, que estoy casi seguro que se ha mencionado pero no lo he podido encontrar. La cosa es que me puse a revisar tareas pasadas de los syllabus antiguos , en contreto, la tarea 2 de 2022-2 de plantas vs zombies. La encontré interesante y buena ayuda de estudio para lo que se podría hacer más adelante. **Existe la posibilidad de que se nos puedan subir soluciones de algunas tareas pasadas??** Trate de buscarla, pero no la he logrado encontrar.
Gracias.

**Comment by pacalein** [comment]
Hola hola!
En el curso manejamos subir soluciones sólo para las Experiencias y algunos de los ejercicios propuestos. Para Tareas de este semestre y de semestres pasados no subimos soluciones. La razón detrás de esto es que las Tareas son procesos complejos que pueden solucionarse de muchas formas, y al subir una solución podríamos estar indicando que esa es la forma preferida/óptima/oficial... y no es la idea. Están usualmente diseñadas para llegar de varias formas a la solución, y eso es lo que queremos potenciar en el curso. Además, muchos de los elementos de las tareas los utilizamos como material didáctico durante las clases o incluso como base de actividades. Te invito a intentar resolver partes de las tareas pasadas a tu manera y con lo que llevamos visto hasta ahora ✨ 

Finalmente recordar que las Experiencias y Actividades si están planeadas para ser material de estudio.

**Comment by MathiasPrett** [comment]
> Hola hola! En el curso manejamos subir soluciones sólo para las Experiencias y algunos ejercicios en clases. Para Tareas de este semestre y de semestres pasados no subimos soluciones. La razón detrás de esto es que las Tareas son procesos complejos que pueden solucionarse de muchas formas, y al subir una solución podríamos estar indicando que esa es la forma preferida/óptima/oficial... y no es la idea. Están usualmente diseñadas para llegar de varias formas a la solución, y eso es lo que queremos potenciar en el curso. Además, muchos de los elementos de las tareas los utilizamos como material didáctico durante las clases o incluso como base de actividades. Te invito a intentar resolver partes de las tareas pasadas a tu manera y con lo que llevamos visto hasta ahora ✨
> 
> Finalmente recordar que las Experiencias y Actividades si están planeadas para ser material de estudio.

Entendido, muchas gracias igualmente!
