### ISSUE TITLE
AC2, problemas con test de vehiculos, _energia, "Verifica que la energía de vehículo no parta siendo 0"

### ISSUE THREAD

**Issue by MigoWithTigo** [IIC2233/Syllabus#222]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Al correr el ```test_vehiculo```  obtengo un error al probar que ```la energía de vehículo no parta siendo 0```, cosa que al parecer se refiere a que la energía no sea negativa al iniciar, y si lo es, entonces debemos _setearla_ a 0.

El error en sí es que si defino energía como un atributo "privado", como se nos es indicado en el enunciado, el test fallará debido a que buscará por ```energia``` en vez de ```_energia```.

```
test_init_con_restriccion_energia (tests_publicos.test_vehiculo.VerificarClaseVehiculo.test_init_con_restriccion_energia)
Verifica que la energía de vehículo no parta siendo 0 ... ERROR
```
```
======================================================================
ERROR: test_init_con_restriccion_energia (tests_publicos.test_vehiculo.VerificarClaseVehiculo.test_init_con_restriccion_energia)
Verifica que la energía de vehículo no parta siendo 0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jessica/Documents/Git/Avanzada/MigoWithTigo-iic2233-2024-2/Actividades/AC2/tests_publicos/test_vehiculo.py", line 34, in test_init_con_restriccion_energia
    self.assertEqual(auto.energia, 0)
                     ^^^^^^^^^^^^
AttributeError: 'Vehiculo' object has no attribute 'energia'

======================================================================
```
Mis dudas son: 
* ¿"Verifica que la energía de vehículo no parta siendo 0" significa que la energía debe ser positiva o 0?
* ¿Debemos definir el atributo energía como ```_energia```?

Muchas gracias por su disposición y sorry por la hora de publicación :O

![:3](https://media1.tenor.com/m/a6Vbw5RczH8AAAAC/cat-smile.gif )

**Comment by BoPe3p** [comment]
Hola, si ves los test cases, aquellos que son: "Verifica que la energía de vehículo no parta siendo 0" en el primero te dan energia = 32.1 y en el segundo, energia = -999.2

El test significa que la energia, cuando es un número positivo, energía quede seteado a ese valor y cuando sea negativo, sea seteado a 0 : "self.assertEqual(auto.energia, 0)" -> Eso es cuando te dan energia negativa.
Escribo el comentario intentando responder tu primera duda, pero también me gustaría saber que pasa si nos dan energia = 0, ya que no sale en el enunciado.

**Comment by MigoWithTigo** [comment]
Muchas gracias bro :D

**Comment by Hernan4444** [comment]
Holaaa,

Efectivamente hay un typo en la **descripción** del tests. ESte solo verifica que el número no sea negativo. Es decir, que si te dan un número menor a 0, sea 0. 

Sobre el caso que la energía sea 0, entonces se deja como 0. Al final lo importante es que nunca sea negativa.

Respecto a la segunda duda, si todavía tienes consulta, avisanos por aquí!

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ
