### ISSUE TITLE
Cargador Perdido sala A1

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#222]
Hola, la clase del jueves olvidé mi cargador de notebook HP en la sala A1. Quería saber si algún ayudante o alguien lo guardó.

Gracias!

**Comment by rrhurtado** [comment]
Hola, yo estuve el día de la actividad que se te quedó el cargador. Lo dejamos en los lockers del DCC, ubicados en la primera sala frente a la secretaria (la Sole), casillero número 2. Puedes ir y preguntarle a ella si te prestaría la llave explicando tu situación.

Saludos !

**Comment by B-Dominguez** [comment]
Ya lo fui a buscar, muchas gracias!
