### ISSUE TITLE
Discord Yuqw52Y cerrado, ¿se reabrirá hoy 14:00 para AS01?

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#222]
Hola! No estuve para la actividad formativa de la semana pasada, así que quería agregar el server de Discord ahora antes de la AS01, pero me sale que es inválido o está vencido. ¿Es el mismo código que se reabre a las 14:00, o tengo que fijarme en los anuncios de CANVAS a las 14:00?

Gracias de antemano :)

**Comment by fdoflorenzano** [comment]
Hola @sbcorrea,

¿Estás segura que es inválido? El enlace se hizo específicamente para que no expirara.
Puedes tratar con este enlace: https://discordapp.com/invite/Yuqw52Y

Saludos., quedo atento.

**Comment by sbcorrea** [comment]
Ahí sí, ¡gracias! Por alguna razón me funcionó este, pero no el link del anuncio en CANVAS para la AF01 ni escribir el invite code manual :thinking:
