### ISSUE TITLE
T00 - puntajes.txt

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#222]
Me gustaria saber como va a ser el archivo puntajes.txt con el que los ayudantes van a corregir. Existe la opcion de tener lineas vacias entre los puntajes de los jugadores? Hay una linea vacía al final del archivo? (relevante si hay menos de 5 puntajes).
Hay un formato estandar o tenemos que asumir que puede haber cualquier cosa en el archivo y solamente utilizamos las lineas que tengan el formato de: nombre,puntaje

**Comment by vicentevegaulloa** [comment]
Hola @YehudaGurovich !

Supongo que quisiste decir `puntajes.txt`. Intentaré responder todas tus preguntas.

1.  Existe la opcion de tener lineas vacias entre los puntajes de los jugadores?
 No, ya que ese no es el formato descrito en el enunciado.
2.  Hay una linea vacía al final del archivo?
 No hay una línea vacía al final del archivo. La última linea del archivo debe ser el ultimo puntaje mostrado.
3. Hay un formato estandar o tenemos que asumir que puede haber cualquier cosa en el archivo y solamente utilizamos las lineas que tengan el formato de: nombre,puntaje?
 El formato que se utiliará para corregir es el mismo que se muestra en el enunciado y que se entrega de ejemplo en el repositorio. 

Espero haberte ayudado 😄

**Comment by YehudaGurovich** [comment]
Tienes razon! ya lo cambie para evitar confusiones! lo que pasa es que el enunciado dice que es un ejemplo y no me habia quedado claro si era siempre así o si era una de las maneras en las que podia venir. Gracias!

**Comment by vicentevegaulloa** [comment]
De nada!
