### ISSUE TITLE
Diferencia número de fase e id

### ISSUE THREAD

**Issue by Pipelao** [IIC2233/Syllabus#222]
Hola buenas!
Quería preguntar acerca de la diferencia entre el número de fase e id. Sé que son diferentes pero no sé cuáles son los números de fase que me podrían entregar para la consulta de Información por fase de la sección 4.2.5.
Gracias de ante mano, Saludos.

**Comment by ignaciohermosillacornejo** [comment]
¿A que te refieres con el número de fase?

**Comment by Pipelao** [comment]
@ignaciohermosillacornejo Hola :)
En el enunciado sección de consultas 4.2.5 en Información por fase dice : "Dado el número de una fase se debe mostrar los equipos (...)"
Gracias de antemano, Saludos.

**Comment by auirarrazaval** [comment]
Cual seria el numero de cada fase entonces?
