### ISSUE TITLE
Estadísticas después de activación de poder especial

### ISSUE THREAD

**Issue by bozziuc** [IIC2233/Syllabus#222]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Varios poderes especiales afectan estadísticas en función de porcentajes. Por ejemplo, el poder especial del caballero reduce el poder del rival en un RED_CAB%.
Cuando instanciamos los combatientes, el poder debe ser un int. Mi pregunta es, luego del poder especial del caballero, qué hacemos si el poder del rival, luego de la pérdida, resulta en un valor que no es un int? Deberíamos dejarlo en el nuevo valor, o redondearlo?

Muchas gracias

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by CrisDonosoMaass** [comment]
Hola!

Poder debería ser un int por lo tanto debes aproximarlo a int más cercano.

Ojalá resuelva tu duda!
