### ISSUE TITLE
Término del juego 

### ISSUE THREAD

**Issue by valeria-adasme** [IIC2233/Syllabus#222]
Hola, tengo una duda del enunciado:
'6. El juego termina cuando un jugador no puede poner su pieza, cuando no quedan más, o bien, cuando se logra completar la snitch dorada'

Con la primera afirmación, ¿quiere decir que no pueda cancelar el anterior movimiento y que no pueda, con ninguna rotación, colocar la pieza entregada? ¿O solamente se refiera a que no puedo poner la pieza que tengo? Creo que el juego se podría extender bastante si sólo deshago mis jugadas a lo largo del tablero... ¿o hay un límite?

Con respecto a la segunda afirmación, 'cuando no quedan más' espacios disponibles?

Gracias :D 👍

**Comment by Arcoirisky** [comment]
Cuando no puedes colocar tú pieza es cuando literalmente no la puedes poner ni siquiera rotandola, incluso puede darse el caso en que quedes sin movimientos a pesar de haber retrocedido tu jugada anterior o:

Cuando no quedan más espacios es en el caso de que tanto el jugador 1 como el dos lo hayan hecho súper bien y se haya completado todo el tablero. 

¿Respondo a tu pregunta? O:

**Comment by valeria-adasme** [comment]
Hmmm, sí, gran parte.
Otra duda que me surge en base a esto es si hay un número de piezas límite? o los jugadores tienen piezas infinitas en este juego?

**Comment by iqacevedo** [comment]
Hola,

@valeria-adasme eso sale en el enunciado :P

![img_3154](https://user-images.githubusercontent.com/13748732/30010564-f75f0c1c-9106-11e7-9358-974daf69449b.PNG)

Saludos !
