### ISSUE TITLE
Duda parametros.py

### ISSUE THREAD

**Issue by CarlangaUC** [IIC2233/Syllabus#223]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

No entiendo el archivo parametros.py, ¿Tengo que escribir en el mismo todos los valores pedidos con random antes de iniciar cualquier partida ? o simplemente decido de antes los valores en el archivo y empiezo el juego

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]d

**Comment by Rotopikus** [comment]
Hola!!

En el archivo parametros.py se deben guardar variables fijas. Cuidado porque no se pueden importar librerías en este archivo (no se puede importar random). 
Este archivo sirve para evitar el hardcoding en el código.

Espero haber aclarado tu duda!!

**Comment by CarlangaUC** [comment]
Entonces, tengo que definir mis parámetros en ese archivo de acuerdo a las condiciones del enunciado y los que no , es a criterio propio? Asumo que todo esto antes de partir el juego cierto?

**Comment by Rotopikus** [comment]
Exactamente, pero recuerda explicitarlo en el Readme.
