### ISSUE TITLE
Duda con test_tesla

### ISSUE THREAD

**Issue by mVal919** [IIC2233/Syllabus#223]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Buenos días. Tengo una duda sobre test_llama_recorrer_clase_padres de test_tesla.
![image](https://github.com/user-attachments/assets/03742e12-a2d6-4119-be7e-bb57697f3c2c)
No comprendo muy bien como interpretar el error, considerando que todos los otros ejercicios de esa y las otras clases están bien, excepto ese.
Eso, no se si me podrían orientar con respecto a lo que pide el test.

**Comment by Hernan4444** [comment]
Hola @mVal919 

Ese texto intenta decir que se esperaba que se ejecutara el  el método `recorrer` de la clase Padre **1 vez**, pero en tu código fue ejecutado 0 veces.  Por lo tanto, algo le falta al método `recorrer` de `telsa` para que está 100% correcto.

Respecto al número de llamados, aquí te dejo un ejemplo más ilustrativo:

```python
class A
    def metodo(self):
        pass


class B(A)
     def metodo(self):
         super().metodo()
         super().metodo()
```

Aquí podemos decir que `método` de la clase B llama 2 veces al método de la clase Padre.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ
