### ISSUE TITLE
Problema al importar/trabajar con Qt Designer

### ISSUE THREAD

**Issue by Allmaito** [IIC2233/Syllabus#223]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, estoy haciendo una parte con Qt designer y cuando hago lo de importar y ejecutó en main, me da un error de que no encuentra un módulo llamado "imagen_rc". La verdad no se a que se refiere porque busqué en mis directorios y nada se llama así y seguí los mismos pasos para poder importar el .ui con el que trabajo.
Gracias de antemano!

**Comment by cegalleta** [comment]
¡Hola!
Vi una issue similar que no había sido respondida de hace unos días. Creo que el problema se origina a partir de que Designer usa recursos de archivos con extensión .qrc cuando este debería convertirse en un archivo con extensión .py como sugiere este [link](https://python-catalin.blogspot.com/2018/11/python-qt5-setstylesheet-example.html). Personalmente lo que haría yo sería no complicarme y no cargar imágenes o archivos desde Qt-Designer, básicamente hacer sólo una plantilla "vacía" de la ventana para después cargar las imágenes y settear los atributos a nivel de código. Se puede utilizar ```.setStyleSheet()``` para ello, usando el mismo formato que se ocuparía en Designer.
