### ISSUE TITLE
Duda ejercicio 4.3 semana 01

### ISSUE THREAD

**Issue by cotefon** [IIC2233/syllabus#223]
Hola! quiero hacer el ejercicio del movimiento en la matriz usando diccionarios, y para ello hice el siguiente dict:
jugadas_dict = { 'w' : subir(tablero, pos), 'a' : izquierda(tablero, pos), 's' : bajar(tablero, pos), 'd' : derecha(tablero, pos)}

el problema es que al momento de utilizarlo no usa la función de la letra llamada, sino que usa todas las funciones que contiene. ¿Se puede hacer un dict donde yo aprete  por ejemplo 'w' y ejecute únicamente dicha función?

**Comment by KnowYourselves** [comment]
Hola @cotefon!

Excelente idea!, Estuviste muy cerca de implementarla correctamente. Lo que puedes hacer es guardar funciones en diccionarios y llamarlas cuando accedas a ellas. Me explico, supongamos el sig . diccionario:

```python3
funciones = {
    "llave_1": funcion_1,
    "llave_2": funcion_2,
    "llave_3": funcion_3,
}
```

Luego al hacer, por ejemplo `funciones["llave_1"]()` estaría ejecutando `funcion_1`. Si es que la función tuviera argumentos sería simplemente `funciones["llave_1"](argumento1, argumento2, ...)`.

Espero haya quedado claro!

**Comment by cotefon** [comment]
me acaba de funcionar! muchas gracias!
