### ISSUE TITLE
Batalla "interminable"

### ISSUE THREAD

**Issue by Vicente1824** [IIC2233/Syllabus#223]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

¡Hola! Me pasó que, en una batalla, en la ronda 2 del archivo ```facil.txt```, entre Amanda (un gato de ```unidades.txt``` que evolucioné a Mago de Batalla) y Carlos (un Caballero), la pelea dejó de avanzar, porque ninguno de los gatos le hacía daño al otro. Esto probablemente pasó porque el ataque disminuye después de cada ataque debido a la disminución de los stats de los gatos y también porque perdieron vida. En este caso sería un empate eterno, ¿qué puedo hacer? Si pasa esto al momento de evaluar la tarea, ¿cuenta como un error o se puede ignorar? Podría intentar que después de una ```n``` cantidad de repeticiones si nadie ha ganado que ambos sean eliminados pero no está en el enunciado.
En la foto se muestra esta situación. Los gatos al principio si se hacían daño, pero disminuyó hasta llegar a 0 para ambos, por eso les falta algo de vida.
![image](https://github.com/IIC2233/Syllabus/assets/76407650/30c9dade-6b02-4f2b-bf14-c7bd22ac68bc)

**Comment by Jpdelaf** [comment]
no soy ayudante ni nada, en el enunciado, pagina 8 dice,  " Sin importar el tipo de ataque que se realice, el daño
final debe ser un int mayor o igual a 1. "

**Comment by CrisDonosoMaass** [comment]
Hola!

Lo que dice @Jpdelaf  es cierto. Verifica que estés implementando eso y además revisa que los parámetros que estableces no estén provocando que se lleguen a situaciones extremas como esta.

**Comment by Vicente1824** [comment]
¡Muchas gracias @Jpdelaf y @CrisDonosoMaass! No había leído esa parte, solo la parte de ataque.
Entonces una pregunta más, ¿el valor que elija para los parámetros no importa o sí? O sea, la idea sería no llegar a esta situación, pero si se llega no es tan terrible, ¿o cuenta como malo porque elegí mal los parámetros?

**Comment by CrisDonosoMaass** [comment]
Exacto, ideal que no ocurra pero no es malo si llega a pasar.
