### ISSUE TITLE
Duda sobre Readme de la tarea

### ISSUE THREAD

**Issue by FabriRandon** [IIC2233/Syllabus#223]
Estimados.

Junto con saludar les escribo para consultar acerca de que se me olvidó agregar en el readme de que para poder disparar se debe apretar la tecla "L". Existe alguna forma de hacer llegar esa información a los ayudantes o no afectaría en nada?

Al estar bajo presión por la entrega se me olvidó agregar ese detalle tan importante 🙏

Saludos cordiales.

**Comment by Emiliax16** [comment]
Hola @FabriRandon ! Gracias por la aclaración, lo tendremos en consideración al momento de corregir tu tarea 😄
