### ISSUE TITLE
Compilado de Issues T1

### ISSUE THREAD

**Issue by gatochico** [IIC2233/syllabus#223]
En la siguiente _issue_ encontrarás todas las _issues_ sobre la Tarea 1 que se han realizado hasta el momento, estas están divididas según diferentes temas.
Antes de hacer una nueva _issue_, revisa si tu duda ya fue realizada, así evitamos las _issues_ duplicadas. 😄

### Librerías permitidas, no permitidas y malas prácticas ✔️❌ 
1. Librerías permitidas, no permitidas y malas prácticas T1 #222 
---

### Flujo del programa
1.  ¿Si un barco no puede pagar la salida el simulacro continua hasta terminar? #235 
2. Robo por piratas #241
3.  Flujo de barcos dentro del canal #251
4. Uso de probabilidad en la simulación #294 
5.  Duda con la frecuencia de probabilidad de desencallar #302 
6.  Frecuencia de eventos de barcos #303 
7.  Que puedo hacer cuando se encalla un barco #304 
8.  Duda sobre método desencallar_barco #308 
9.  Formula de probabilidad de encallar #325  [IMPORTANTE]
10.  Contradicción de PONDERADOR_DIFICULTAD #305 
11.  Efectos de la opción "Volver atrás" #315 
12.  Duda fin del programa por dinero igual a 0 #352 
13. Cambio de probabilidades por evento especial #314
14. Confusión entre simular nueva hora y avanzar barcos #370 
15. Ingreso barco al canal. #371
16.  Sin fondos #377
17.  Orden de revisado de encallamiento #366 
18.  Barcos en canal, su posicion y colision y otras dudas. #375 
19.  Sobre instanciar varias veces #387 

---
### Entidades
* #### Barcos
  1. Pasajeros de barco carguero #229
  2. Duda sobre divisas de cada barco #231
  3. Evento especial barco pasajeros #247
  4. Contradiccion enunciado #250 
  5. Flujo de dinero evento especial barco pasajeros #277 
  6.  Duda DINERO_INTOXICACION #326 
  7.   Puede ocurrir un evento en un barco encallado? #317 
  8.  Duda sobre DINERO_INTOXICACION #336 
  9. Fondos barco y COSTO_DESENCALLAR #359 
  10.  Avería de un buque #285
  11. Barco encallado = el resto sigue avanzando hasta cierto límite? #242
  12.  Sobre barcos encallados y eventos #382 
  13. Sobre repeticiones de tripulantes/mercancias #386 
  14. Reinicio de barco #388 
* #### Cajas de Mercancía
  1. Método expirar() #307
  2.  Sobre pago en la expiración #384 
* #### Tripulación 
  1.  Duda sobre la tripulación de cada barco #267
  2.  Duda efecto_especial de los tripulantes #329 
  3.  Duda efecto especial DCCapitán #342 
* #### Canales
  1.  Costo mantención de barcos #379 

---
### Menús
1.  Duda si es que hay que agregar menús #252 
2.  Asunciones de menús #334 
3. Opción de salir en menús #350
---
### Archivos
* #### `parametros.py`
   1.  Parametros #224
   2.  No encuentro el archivo parametros.py #225  
   3.  Valores de los parametros #226 
   4. Duda parametros.py #266 
   5.  Duda sobre parametros permitidos #327 
   6.  Duda uso de parametros #353|
   7. Importación de parámetros #306
   8. ¿Está permitido importar librerías en parametros.py? #343

* #### archivos `csv`
   1. Consulta sobre asumir un supuesto relacionado con los archivos.csv #248
   2.  Duda archivos .csv #278 
   3. ¿Se actualizan los archivos .csv? #279 
   4.  Duda sobre archivo de canales #280 
   5. Duda sobre tripulantes en tripulantes.csv y en barcos.csv #365 

* #### `.gitignore`
   1. GitIgnore #385 
---
### Otros
  1. [General] Uso de variables globales #259 
  2.  currencyconverter #268
  3.  Problemas con librería Currency_Converter #275
  4.  Uso de código tarea anterior #270
  5.   Commit entrega avance T1 #276 
  6.  problema con PATH al instalar CurrencyConverter #299 
  7.  definicíon de error/robustez en el programa. #319 
  8.  Asunción adecuada? #322 
  9.  Duda poseer relaciones de composicion y agregacion #330 
  10.  error de caracteres pero en git bash #339 
  11. Encallar o no #296
  12. Uso de probabilidad de encallar #294
  13. Distribución de puntajes, Simulaciones, crear una o más simulaciones #367 
  14. Redistribuir metodos #374 
  15. Uso de properties #390

**Comment by Nicolasramos411** [comment]
Hola! Una duda, si un barco carguero es robado por piratas entonces no podrá pagar la tarifa de salida del canal. ¿Esto implica que tendremos que pagar un costo de mantención por hora al barco por cada hora que siga durando la simulación?

Gracias!

**Comment by Nicolasramos411** [comment]
Hola! Una duda, ¿Si un barco se encalla, los barcos detrás de él deben detenerse en ese instante o en el transcurso de las horas podrán avanzar hasta llegar a la posición de el barco encallado?

**Comment by valedt** [comment]
Hola, leyendo el enunciado encontré que la explicación sobre los barcos encallados es ambigua. Pues en el caso de que un barco se encalla o no tenga dinero para pagar la salida ¿Qué sucede con la simulación? ¿Continua funcionando hasta quedar en bancarrota o se termina de una?

**Comment by sebamoreno2811** [comment]
En el enunciado se dice que los barcos cargueros solo llevan mercancia, pero en el .csv tienen pasajeros asignados, entonces estos pasajeros se consideran los calculos para el barco carguero?
