### ISSUE TITLE
Equipos con grafo de afinidades conexo

### ISSUE THREAD

**Issue by pcseisdedos** [IIC2233/Syllabus#223]
En el item 4.2.1 dice que el grafo de afinidades entre los 11 jugadores de un equipo debe ser conexo, entiendo que se refiere a las afinidades inciales (definidas en 4.1) no a las afinidades entre jugadores que no se conocen (definido en 4.1.1) ya que de lo contrario todos los grafos de afinidades de cualquier subconjunto del grafo inicial serían conexos, porque el grafo inicial lo era, por lo tanto existe al menos un camino para llegar a cualquier otro jugador y de este modo se puede calcular la afinidad como se establece en 4.1.1
Sin embargo el grafo de la figura 4 no sería conexo (según las afinidades iniciales), entonces, ese equipo no sería válido?

**Comment by yoavnavon** [comment]
Hola! Creo que no quedo demasiado claro en el enunciado, pero el equipo debe ser conexo según el grafo grande, por lo que cualquier combinación de 11 jugadores será conexa, por lo que no tienes que preocuparte.
