### ISSUE TITLE
Preguntas varias tarea

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#223]
1.  ¿Se pueden conectar nos lados de fichas en que ambos son ciudad, pero uno es una muralla de ciudad y otro es interior de ciudad?
2. Cuando se dice que se debe ver reflejado en la interfaz quién es el dueño de alguna entidad completa, por ejemplo una ciudad completa, ¿significa que una vez que un jugador, por ejemplo el azul, completa una ciudad, todas las fichas que componen esa ciudad deben ponerse de color azul?
3. No me quedó clara la asignación de puntajes para el caso de la ciudad: si se tuviera una ciudad completa de 8 piezas, ¿tanto el jugador rojo como el azul recibirían 30x8 puntos cada uno, además de que el jugador dueño de esa ciudad recibiría 40 puntos más?
4. ¿Cómo es el puntaje de caminos que conectan 2 ciudades completadas? (Sólo salen los casos de caminos que conectan ciudades incompletas o ciudad con el borde de la grilla).
5. Creo que nunca vi la función que le dice a Gui qué puntajes mostrar en la interfaz al terminar el juego.
6. ¿Podrían subir la pauta de la tarea para saber los puntajes que se asignaran a cada cosa que se haga?

**Comment by mjgutierrez1** [comment]
7. Otra cosa que no caché es cuándo estamos usando/ importando PyQt5, porque al fina vamos a usar los métodos de Gui como gui.add_piece y Gui se encarga de agregar la pieza a la interfaz.

**Comment by Arcoirisky** [comment]
1) Sí se puede. No te fijes tanto en lo visual, lo que importa es que los lados se junten según sus letras asignadas. Lo que dices quedaría como un City-City por lo que es una unión correcta.

2) Síp. Por ejemplo, el naranjo tiene una ciudad incompleta por una pieza y llega el azul para completarla, entonces todas las piezas de esa ciudad se vuelven azules :D

Pd: Sugiero que vayas haciendo una issue por Pregunta. Así cuando otra tengan tu misma duda puedan encontrarla fácilmente :)

**Comment by iqacevedo** [comment]
Hola, 

5-. Tu debes manejar que puntajes debes mostrar, basta con que ocupes la función `set_points` de la gui para ello.
6-. No tenemos una pauta de como debería ser la tarea, ya que hay muchas maneras de resolver un mismo problema, por este motivo entregamos un feedback. Ustedes ya tienen en el enunciado los porcentajes de cada parte de la tarea.
7-. Te refieres a cuando efectivamente se utiliza PyQt5?, si es así se utiliza en las funciones `init` y `run` del archivo \_\_init__.py, en ellos se importa Game, que es la ventana en la que se ve todo.

Saludos !

**Comment by cilopez** [comment]
4.- Fijate en la regla **plot twist**

**Comment by FernandoPieressa** [comment]
Hola!

Para que el resto de los alumnos puedan buscar mejor sus dudas dentro de las issues es importante recordar que tienen que poner nombres explicativos en las issues de la pregunta y si no son dudas relacionadas entre sí solo 1 pregunta por issue.

Recuerda que tu duda puede ser la duda de alguien más!

Saludos!
