### ISSUE TITLE
Ejercicio Propuesto 2.3, semana 2

### ISSUE THREAD

**Issue by rosariodominguezm** [IIC2233/syllabus#223]
Hola! Es que no estoy entendiendo mucho cómo funcionan las properties en el 2.3. 
Me confunde que haya un self.__edad = None y un self.edad = edad. ¿Cómo relaciono ambos? ¿ A qué se refiere con validar los atributos?

`class Usuario:
    
    def __init__(self, username, mail, edad, rut):
        # Así validamos de inmediato los atributos
        self.__username = None
        self.__mail = None
        self.__edad = None
        self.__rut = None
        self.username = username
        self.mail = mail
        self.edad = edad
        self.rut = rut
    
    @property
    def username(self):
        return self.__username
    
    @username.setter
    def username(self, value):
        pass
    `

**Comment by rosariodominguezm** [comment]
Ojala me lo puedan responder! Gracias

**Comment by tocococa** [comment]
Hola @rosariodominguezm ! Por convención, los atributos que comienzan con `__foo` se conocen como atributos privados, y sólo deben ser modificados/accedidos usando _properties_ (`@property @foo.setter @foo.getter @foo.deleter`), mientras que la versión sin guión bajo, `foo`, es el atributo público, con el que el resto del programa (o la misma clase) puede interactuar. 

En particular para `self.edad` y `self.__edad` tienes que definir las _properties_ de `__edad`:
```Python
@property
def edad(self):
    #hacer algo con __edad
    pass
    
@edad.setter
def edad(self, value):
    # hacer algo con __edad y value
    pass
```
Con eso escrito, en el `__init__` se parte definiendo `self.__edad = None` porque a priori la clase no sabe que edad tiene la persona, peeero, nosotros sí lo entregamos como argumento en `__init__`, por lo que al decir `self.edad = edad`, el programa va a ir a `@edad.setter`, va a revisar que que el argumento `edad` sea válido, en el enunciado te dan una restricción para la edad, a eso se refiere con validar los atributos. Finalmente debiese cambiar (o no) el valor de  `self.__edad`.

Espero haber aclarado tus dudas un poquito, pero si sigues teniendo preguntas vuelve a comentar acá mismo.

**Comment by rosariodominguezm** [comment]
Sii perfecto!! Me salió.
Muchas gracias!!
