### ISSUE TITLE
Logré descargar Pyqt5 pero no me funciona.

### ISSUE THREAD

**Issue by juanpacl111** [IIC2233/syllabus#223]
Me arroja:
ImportError: DLL load failed: No se encontró el proceso identificado.

¿Cómo puedo solucionar esto?

**Comment by Arcoirisky** [comment]
Mira si te sirve lo que se responde en este link:

https://github.com/IIC2233/Syllabus-2017-2/issues/203

Al parecer también sucedió un caso similar semestres atrás.
