### ISSUE TITLE
Aclaración de uso de "relaciones de agregación" en T01

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#223]
No me queda muy claro como es que se debe implementar este ítem dentro de la tarea. Según lo que entendí revisando las clases nuevamente, estas relaciones son cuando se "agrega" una objeto de una clase a otra clase, pero si se llega a eliminar la clase a la que se le agregó, entonces el objeto de la clase original sigue existiendo.
Según esto, como exactamente se debe implementar en la tarea? Me podrían dar un ejemplo para entender mejor esto?

**Comment by tomasgv** [comment]
Hola! Aquí va un ejemplo simple, simulando un carrito de compras:
```python3
# creo las clases Carrito, Vegetal y Fruta
class Carrito:
    def __init__(self):
       self.productos = []


class Vegetal:
    def __init__(self, nombre):
        self.nombre = nombre


class Fruta:
    def __init__(self, nombre):
        self.nombre = nombre


carro_compras = Carrito()
zanahoria = Vegetal('Zanahoria')
manzana = Fruta('Manzana')

# agrego la zanahoria y la manzana
carro_compras.productos.append(zanahoria)
carro_compras.productos.append(manzana)

# saco la manzana
carro_compras.productos.remove(manzana)

# la manzana sigue existiendo
print(manzana.nombre)

# output: 'Manzana'
```
