### ISSUE TITLE
Estadisticas

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2233/Syllabus#223]
El ultimo item de la parte de estadisticas dice:
"Promedio muertes e infecciones: Debe mostrar la tasa de vida y muerte de las personas del dia actual o el acumulado hasta la fecha."
Que significa exactamente tasa de vida y tasa de muerte? Gente viva/poblacion total y gente muerta/poblacion total?

**Comment by rrhurtado** [comment]
Hola, esa duda ya fue respondida en la siguiente issue #178 

Saludos !
