### ISSUE TITLE
Problema multiherencia

### ISSUE THREAD

**Issue by jnlarrain** [IIC2233/Syllabus#224]
Tengo un problema al heredar varias clases con super() dentro de otra clase, como por ejemplo:

```
class A:
    def __init__(self):
        self.a1 = "hola"

class B:
    def __init__(self):
        self.a2 = "como estas"

class C(A, B):
    def __init__(self):
        super().__init__()

c=C()
c.a2
```

me tira error que c no tiene atributo a2.... trate tambien poniendo dos super con las clases que quiero heredar en cada uno.... y tampoco funciona....

**Comment by ranieto** [comment]
Tienes que poner el `super().__init__()` en A y B también.

**Comment by jnlarrain** [comment]
lo hice y no funciona, llevo un par de dias con el problema

**Comment by jnlarrain** [comment]
@ranieto se te ocurre otra forma?? para intentar con esa tambien

**Comment by ranieto** [comment]
@jnlarrain copié y pegué lo que pusiste ahí arriba y agregué el `super().__init__()` en el init de A y B y funcionó perfecto.
Me imagino que tu código debe tener más cosas? Así que quizás el problema está en otra parte.
Si no... esto es poco probable, pero en tu mensaje original tenías el init sin los guiones bajos, y veo que el mensaje fue editado por un ayudante. El código que estás probando sí tiene esos guiones bajos... ¿cierto?

**Comment by jnlarrain** [comment]
@ranieto tenias razon el ejemplo funcionaba bien, cambie algo y funciono, fuera del __init__ asi q no se que fue... muchas gracias en todo caso!!!
