### ISSUE TITLE
Ejecutar código en la consola

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#224]
Hola.
Para la tarea estoy trabajando con varios módulos (todos en una carpeta) y quería correr el principal en la consola, para ver como funcionaba, estableciendo mi directorio en la carpeta en donde tengo todos los modulos ejecuto:

python nombre_del_codigo_principal.py 

Pero me tira error, en visual studio me corre a la perfeccion y me asegure de guardarlo antes de correrlo en la terminal, que podria estar pasando?

Muchas gracias.

**Comment by DCCollao** [comment]
Hola!
¿Qué error te muestra al correrlo en terminal?

**Comment by diego-ayala-2000** [comment]
<img width="559" alt="Captura de Pantalla 2020-08-26 a la(s) 21 53 04" src="https://user-images.githubusercontent.com/69765490/91374594-89495400-e7e6-11ea-9876-e5d74c3a6723.png">

**Comment by DCCollao** [comment]
¿Podrías incluir el error completo en la foto?

**Comment by rosariodominguezm** [comment]
A mi tampoco me funciona! Y en VS me funciona perfecto. 

<img width="571" alt="Captura de Pantalla 2020-08-26 a la(s) 22 52 52" src="https://user-images.githubusercontent.com/69605743/91378661-fe208c00-e7ee-11ea-8e85-6982869f5fbf.png">

**Comment by DCCollao** [comment]
Hola @rosariodominguezm!

En tu caso el error se debe a que en mac viene instalada por defecto la versión 2 de python, y es esta la que se ejecuta al correr el comando `python` en la terminal. 
Si deseas ejecutar la versión 3, debes utilizar `python3 main.py`.

**Comment by diego-ayala-2000** [comment]
<img width="580" alt="Captura de Pantalla 2020-08-27 a la(s) 07 47 54" src="https://user-images.githubusercontent.com/69765490/91438612-a4917f00-e839-11ea-9bce-fa8fde6c1433.png">
 ahí una foto de la consola entera, gracias por la ayuda

**Comment by DCCollao** [comment]
¿Intentaste usando el comando python3 en lugar de python al momento de correr tu tarea?

**Comment by diego-ayala-2000** [comment]
Ahí me funciono, muchas gracias, hay alguna forma de dejar puesto que se ejecute Python 3 por defecto?

**Comment by DCCollao** [comment]
Realmente no tenía idea de si era posible o no, pero una búsqueda rápida en google me llevó hasta este [link](https://opensource.com/article/19/5/python-3-default-mac), donde hay instrucciones de cómo hacerlo.
Avísame cómo te va!
