### ISSUE TITLE
Tesoros de calidad 1

### ISSUE THREAD

**Issue by GuilleStanke** [IIC2233/Syllabus#224]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas, cuando abro un tesoro del tipo 1, agrego un excavador al equipo, mi duda es si debo eliminar la posibilidad de que ese excavador con esas características pueda volver a ser elegido o no...
es decir, agrego un excavador al equipo y no se puede volver a agregar nuevamente (quedar con dos o más excavadores inicialmente iguales) o sí se puede

**Comment by CarolinaMezaCh** [comment]
Hola @GuilleStanke!!

Según entiendo lo ideal es que fuesen distintos excavadores, ya que no tiene sentido tener a la misma persona repetida 2 veces en el equipo, pero sí puedes incluir 2 excavadores distintos que sean del mismo tipo. Igualmente, si te surge cualquier complicación respecto a ese tema, quedo atenta a tus comentarios.
Éxito con la tarea!!

**Comment by GuilleStanke** [comment]
buenísima, muchas gracias! Tengo una duda entonces, cuando no quedan más excavadores de un tipo para añadir al equipo (ya añadí a todos los excavadores del tipo al equipo), no hago nada? o imprimo que ya no quedan excavadores de ese tipo para añadir?

**Comment by CarolinaMezaCh** [comment]
Claro, cuando te quedes sin excavadores para añadir, podrías agregar esa restricción a nivel de código y advertir al usuario. También puedes dejarlo comentado en el código para que el corrector entienda esa parte.

Éxito con la tarea!!

**Comment by CarolinaMezaCh** [comment]
Encontré esta issue (#146) que te puede servir también para responder a tu duda. Lo puedes dejar a tu criterio igualmente.
https://github.com/IIC2233/Syllabus/issues/146
