### ISSUE TITLE
Problema con Git Bash

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#224]
Hola, al momento de intentar hacer git pull para obtener los ejercicios de la semana 3 me apaece el siguiente error:
"$ git pull
error: Your local changes to the following files would be overwritten by merge:
        semana-02/3-herencia.ipynb
Please commit your changes or stash them before you merge.
Aborting
Updating 480a534..871de37"

**Comment by KnowYourselves** [comment]
Hola @RonaldoSosa!

Esto sucede porque modificaste el archivo de herencia al momento de probar las celdas o cambiar código, por lo cual la versión de este archivo que tienes en tu computadora es distinto al que esta en github, por ende, te tira un error. Si no te molesta revertir los cambios realizados sobre este archivo puedes hacer los siguientes comandos en orden:

```bash
git add semana-02/3-herencia.ipynb
git stash
git pull
```

El primer comando agrega los cambios que realizaste sobre el archivo, el segundo mueve estos cambios a un contenedor terminal (similar a la papelera de tu computador), por lo cual el archivo volverá a su estado original, y finalmente al hacer pull no habrá ningún problema.

Espero haberte ayudado!

**Comment by RonaldoSosa** [comment]
Me funcionó, muchas gracias!
