### ISSUE TITLE
[Ejercicio Propuesto 1 Semana 6] QThread congela la ejecucion de la GUI

### ISSUE THREAD

**Issue by dvillas28** [IIC2233/Syllabus#224]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Estoy tratando de hacer el ejercicio propuesto de seguir al cuadrado. Cree un front end que se encarga de iniciar la gui y el cuadrado verde, y el backend (otro archivo .py) que se encarga de enviar señales de inicio del programa al frontend y ademas **crear un QThread cada vez que el cuadrado verde es clickeado**. A continuacion explico como tengo programada la funcionalidad hasta ahora

Cuando se clickea el cuadrado verde, el front este envia una señal al backend, donde se ejecuta un metodo que crea el QThread y este realiza los calculos y envios de señales al front para ir moviendo el cuadrado. Al ejecutar esto me tira `QThread: Destroyed while thread is still running` Buscando informacion al parecer esto ocurre ya que el metodo del backend termina y el Qthread es abortado. Para resolverlo, hice que el progrma principal esperase a la ejecucion del thread llamando al metodo `wait()` (analogo a `join()` en pyqt). Esto hace que se pueda ejecutar el thread, pero ahora el frontend queda congelado por la ejecucion del thread en el backend y los cambios en la posicion no se reflejan.

Estoy casi seguro que mi error esta en como estoy iniciando la ejecucion del thread (en un metodo del backend) y en los ejemplos entregados he visto que crean los threads y los inician en el mismo archivo en el que esta la ventana principal y su ejecucion. Pero no se me ocurre **como hacer que se ejecute el thread desde el backend, y se vaya actualizando la gui en el frontend** durante la ejecucion.

Agradezco alguna aclaracion sobre como resolver esto 
Saludos :)

**Comment by dvillas28** [comment]
Buu ya borre el codigo. Pero el back lo tenia mas o menos asi
el `senal_enviar_posicion` de `Logica` envia las cordenadas calculadas al front para mover al cuadrado

```python

class IconoThread(QThread):
    def __init__(self, x, ,y, tamano_v, tamano_c ,senal_mov):
        super().__init__()
        self.x = x
        self.y = y
        self.tamano_v = tamano_v
        self.tamano_c = tamano_c
        self.senal_mover = senal_mov

    def mover(self):
    # va realizando calculos para mover el cuadrado
    # ....
    self.senal_mover.emit(self.x, self.y)


    def run(self):
        while self.moverse:
            self.mover()
            time.sleep(p.DURACION_MOVIMIENTO / 1000)

class Logica(QObject):
    senal_iniciar_programa = pyqtSignal()

    # (x, y, tamano)
    senal_crear_icono = pyqtSignal(int, int, int)

    # (x, y)
    senal_enviar_posicion = pyqtSignal(int, int)


    def __init__(self, tamano_ventana, tamano_cuadrado):
        super().__init__()
        self.tamano_ventana = tamano_ventana
        self.tamano_cuadrado = tamano_cuadrado

    def iniciar_programa(self):
        self.crear_icono()
        self.senal_iniciar_programa.emit()

    def crear_icono(self) -> None:
        dif = self.tamano_ventana - self.tamano_cuadrado
        x = randint(0, dif)
        y = randint(0, dif)
        self.senal_crear_icono.emit(x, y, self.tamano_cuadrado)

    def mover_posicion(self, x, y) -> None:
        print(f'> Backend: Cuadrado en ({x}, {y})')
        print(f'> Backend: Creando thread de movimiento')

        # thread que ejecuta el movimiento del thread
        th = Mover_Icono(x, y, self.tamano_ventana, self.tamano_cuadrado, self.senal_enviar_posicion)

       # iniciar thread
       th.start() # esto por si solo me tira el error
       # th.wait() colocar esto me congela la GUI
```
Saludos!

**Comment by fvidalf** [comment]
Okei, creo que lo tengo.

Si te fijas en cuando creas tu thread en el método `mover_posicion`, lo asignas a una variable `th`. El problema de esto, es que esa variable va a dejar de ser alcanzable (o *reachable*) una vez termine el método, pues solo está definida dentro del *scope* del método.

Luego, para Python esa variable es inaccesible, y en algún momento intentará borrarla, por lo que si el thread sigue en ejecución, naturalmente lanzará el error de `QThread: Destroyed while thread is still running`.

Una solución a ese problema es guardar el thread como atributo del objeto lógico. De esa forma, aunque el método termine, el thread sigue "existiendo". Si te fijas, en los ejemplos se suele guardar los threads como atributos, o como elementos en una colección del objeto (como una lista o diccionario)l.

Prueba algo por el estilo, y si sigues teniendo el problema, responde esta misma issue :D 

Saludos ✌🏽

**Comment by dvillas28** [comment]
Vale, entonces es almacenar el thread previamente en una colección del objeto `Logica` lo q resolvería el problema

Muchas Gracias!
