### ISSUE TITLE
Movimiento del personaje... ¿Debe poder ser diagonal?

### ISSUE THREAD

**Issue by StroveLight** [IIC2233/syllabus#224]
Hola, en la ayudantía de hoy me dijieron que para el avance de la tarea debe de tener el personaje moviendose en diagonal. Pero no hay sprites para eso, lo que casuaría un efecto visual poco agradable a quien vea el programa (ademas de que, en los pokemon de la generación del sprite, el personaje no se movía en diagonal). Ademas de lo anterior, en el avance, solo se pide que el personaje se mueva "en las 4 direcciones con las teclas WASD".
Por lo anterior pregunto: ¿El personaje necesariamente se debe mover en diagonal en el avance y en la tarea?

**Comment by gatochico** [comment]
Hola! Con movimiento diagonal nos referimos a que si se presionan dos flechas al mismo tiempo, como **W+A** por ejemplo, el personaje debe empezar a moverse en ambas direcciones de forma interlazada (arriba, abajo, arriba, abajo, etc...), simulando un movimiento "diagonal". No es necesario que tengas un sprite de movimiento diagonal! 
Saludos!

**Comment by gatochico** [comment]
**EDIT IMPORTANTE**: No es necesario manejar movimiento diagonal. Puedes asumir que el personaje solo se moverá en cuatro direcciones (W A S D). Saludos!

**Comment by StroveLight** [comment]
gracias~

**Comment by jfernandez7** [comment]
Hola! Aclararon que no era necesario para el avance, pero es necesario para la tarea que se mueva en diagonal?
Gracias!

**Comment by gatochico** [comment]
Hola ! No, tampoco es obligatorio que tu personaje se mueva en diagonal para la tarea final.
