### ISSUE TITLE
Duda enunciado carreteras (aparición de autos)

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2233/Syllabus#224]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
En la parte de carreteras del enunciado dice que los autos deben aparecer y moverse ya sea de derecha a izquierda o de izquierda a derecha (aleatoriamente), sin embargo después dice que los autos deben aparecer cada TIEMPO AUTOS.
No entiendo como tienen que aparecer, aleatoriamente o no?

**Comment by ivanvlam** [comment]
Hola @vice-rosas99 ! Los autos si deben aparecer cada TIEMPO_AUTOS, lo que es aleatorio es el sentido en el que se mueven los autos en cada pista de la carretera, es decir, si los autos en esa pista se mueven de izquierda a derecha o de derecha a izquierda. Por último, recuerda que todos los autos en cada pista se mueven en el mismo sentido.

**Comment by vice-rosas99** [comment]
Entonces en un principio es aleatorio la dirección de cada carril, y por lo que queda de la partida ese carril solo tendrá una única dirección? o puede cambiar cuando no hay autos presentes?

**Comment by ivanvlam** [comment]
Durante la ronda cada carril tendrá una única dirección, que será elegido aleatoriamente.

**Comment by vice-rosas99** [comment]
vale, así está más claro, gracias

**Comment by svilaza** [comment]
Para la carretera es necesario que las los movimientos sean intercalados o pueden haber dos lineas seguidas que tengan la misma dirección? (e.g izq - izq - der)

**Comment by diegocostares** [comment]
@ivanvlam Hola, entiendo bien el enunciado, pero para agregar más dinamismo me gustaría hacer el supuesto de que el TIEMPO_AUTOS y el TIEMPO_TRONCOS fuera un intervalo aleatorio, ¿Está permitido? Asi establecería una tupla con el mínimo de tiempo que tienen que aparecer y un máximo para que estén separados entre sí. Claramente lo agregaría en el readme

**Comment by ivanvlam** [comment]
Hola @svilaza ! No es necesario que los sentidos de los carriles de los autos sean intercalados, es decir, puede haber dos carriles seguidos con autos en el mismo sentido. Sin embargo, tal como dice el enunciado, el movimiento de los troncos si debe ser intercalado.

**Comment by ivanvlam** [comment]
Hola @diegocostares ! Si puedes hacer que TIEMPO_TRONCOS y TIEMPO_AUTOS sea un intervalo, pero debes preocuparte de que estos valores sigan cumpliendo con la condición de que no se superpongan troncos ni autos. Además, **no se puede importar `random` en parámetros**, por lo que deberás implementar el random del intervalo a nivel de código. Recuerda especificarlo en tu README.

**Comment by Dafnemami** [comment]
Hola @vice-rosas99. Un auto debe aparecer en pantalla en TIEMPO_AUTOS segundos en cada hilera?
