### ISSUE TITLE
Uso de NamedTuple como clase

### ISSUE THREAD

**Issue by nsumonte** [IIC2233/syllabus#224]
Hola!,
Es valido el uso de las NamedTuples como clases de las que se evalúa a nivel de codigo?
Realizando la tarea me percaté que se evalúa un alto porcentaje por el uso de las clases, sin embargo, cree todas las clases como NamedTuples. Las cuales, luego, junto todas para crear el flujo del juego. 
Muchas Gracias!

**Comment by KnowYourselves** [comment]
Hola @nsumonte!

Lamentablemente, eso tendría medio puntaje 😢.

Esto se debe a que las `namedtuples` si bien útiles, no te permiten modelar del todo bien con objetos. Cosas como herencia simple y múltiple, clases abstractas y properties (todas cosas que serán evaluadas en esta tarea) no son posibles de hacer con `namedtuples`.

Te recomiendo definir y ocupar clases y modelar con herencias, properties, clases abstractas etc. Recuerda en la modelación correcta de esta tarea deberías ocupar estos conceptos al menos una vez 👀.

Éxito!
