### ISSUE TITLE
Duda sobre información en ReadMe del disparo

### ISSUE THREAD

**Issue by nhi1016** [IIC2233/Syllabus#224]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda sobre información relevante del disparo

Hola buenas noches! Tal como el compañero de la issue anterior mencionó, quería notificar también se me olvidó agregar en el ReadMe de que para poder disparar se debe apretar la misma tecla "L". De todas maneras, acabo de hacer un nuevo push con el único gran cambio que en el mensaje del commit le puse "SE DISPARA CON LA L" y en el nombre de la tarea del ReadMe también, pero no para que me corrijan ese commit, más bien para que de alguna manera se le notifique al ayudante que se dispara con L.

De antemano, pido disculpas por las molestias. A última hora siempre se nos pasan pequeños detalles. 🙏

Saludos cordiales.

**Comment by matiasmasjuan** [comment]
Hola @nhi1016. Al igual que en la issue #223 Gracias por la información. Lo tendremos en cuenta al corregir tu tarea :ok_hand:
