### ISSUE TITLE
NO SE INSTALAR EL PyQt5 😩😩😩 !!

### ISSUE THREAD

**Issue by AngelMatias** [IIC2233/Syllabus#224]
Tengo esto pero no caxo que hacer 
<img width="401" alt="captura de pantalla 2017-09-04 a la s 15 57 51" src="https://user-images.githubusercontent.com/30705123/30036515-7e43d202-918a-11e7-8c4b-38462fc0ed1d.png">

**Comment by sebacruzd** [comment]
Intentaste hacer `pip3 install pyqt5` en la consola antes de bajarte eso?

**Comment by AngelMatias** [comment]
sii si la vi y con la wiki llegue a esos que descargue, pero estoy super desorientado la verdad, para instalarlos solo escribo eso en la consola de pycharm o en la terminal ??

**Comment by sebacruzd** [comment]
En la terminal

**Comment by AngelMatias** [comment]
al final lo solucione de otra forma, gracias man !
