### ISSUE TITLE
Parametros

### ISSUE THREAD

**Issue by mathimadsen17** [IIC2233/syllabus#224]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holaa, tengo una duda con los parametros, los tenemos que inventar?? O nos van a dar los parametros para implementarlos, es que en el enunciado dice que deberemos completar el archivo parametros.py con los parametros mencionados en el enunciado, pero no encontré los valores de esos parametros en ninguna parte.

**Comment by Emiliax16** [comment]
Holaa! efectivamente debes crear el archivo` parametros.py`. En la sección de archivos, dice que se debe rellenar con todos los valores constantes que ocupes y con los que están en ESTE_FORMATO durante todo el enunciado. Los valores los debes asignar tú, teniendo cuidado de cumplir con rangos y condiciones que se especifican.

**Comment by Emiliax16** [comment]
Hola! efectivamente debes crear los parámetros, todos los que aparezcan en  **ESTE_FORMATO** debes incluirlos en el archivo `parametros.py`. Para saber qué valores pueden tomar esos parámetros, te recomiendo probar con distintos valores que coincidan con las condiciones del enunciado y que favorezcan la fluidez de tu programa.
