### ISSUE TITLE
Diagrama de clases y composicion

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2233/Syllabus#225]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Si por ejemplo tengo la clases  A1 y A2 que herdan de la clase abstracta A, estas dos tienen  clases tienen relacion de agregacion con las clases B1,B2 las cuales heredan de la clase abstracta B. **¿Es necesario que ponga la linea de para cada combinacion de agregacion o puedo poner unicamente que la clase abstracta A tiene relacion de agregacion con la clase abstracta B?**

**Comment by Benjeeeh** [comment]
Hola!
Depende netamente del grado de especificidad de tus clases hijas. ya que en el caso de que cualquier tipo de A pueda unirse a cualquier tipo de B, sería válido pensar que cualquier clase que herede de A va a tener relación de agregación con B y se podría realizar esta única línea. En el caso contrario, si las clases hijas A tienen una relación específica de agregación con un tipo específico de B, por ejemplo de que A1 solo tiene relación B1, se tendría que realizar esta relación y agregar cada línea en tu diagrama. 

Espero que haya quedado claro, éxito con tu tarea!!
