### ISSUE TITLE
Salto hacia los lados

### ISSUE THREAD

**Issue by diegocostares** [IIC2233/Syllabus#225]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola queria preguntar si tienen (y si nos pueden facilitar) las imágenes de las ranas saltando hacia los lados, los sprites que nos entregaron solo vienen con los saltos hacia al frente y cuando la rana salta hacia atrás o hacia los lados queda muy mal 😿

**Comment by sebaguerrap** [comment]
Hola @diegocostares ! Los sprites de salto para los lados no existen por lo que simplemente hay que hacer que la rana se mueva una cierta cantidad de pixeles en el sentido que esté mirando.

**Comment by vice-rosas99** [comment]
hola, entonces es posible nunca usar los sprites de salto?, o esos son para realizar una 'animación'?
por ejemplo presiono spacebar, entonces el sprite cambia a salto_1, una décima de segundo después el sprite cambia a salto_2, una décima de segundo después, el sprite cambia a salto_3 mientras que se mueve?

**Comment by sebaguerrap** [comment]
Hola @vice-rosas99 ! Efectivamente es posible nunca usar los sprites de salto. Si bien usarlos hace que el programa se vea mejor, se evaluará que cumplan con el movimiento de `PIXELES_SALTO` pixeles en la dirección en la que se está mirando.
