### ISSUE TITLE
Polimorfismo ejemplo (Semana 2)

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#225]
<img width="1059" alt="Captura de Pantalla 2020-08-26 a la(s) 21 36 42" src="https://user-images.githubusercontent.com/53887845/91373490-80f01980-e7e4-11ea-91ca-091def607a30.png">

Hola! no entiendo muy bien la parte del código cuando dice "otro.pan, otro.leche y otro.agua" :(

**Comment by DCCollao** [comment]
El _dunder method_ `__add__` se utiliza para modelar el comportamiento de una clase cuando se enfrenta a una suma. Como argumento, en este caso, está recibiendo `otro`, que representa a **otro objeto que tenga los atributos pan, leche y agua**, pues dichos atributos son los necesarios para realizar la suma. 
En el siguiente ejemplo agregué un par de `print` para que quede más claro:
![image](https://user-images.githubusercontent.com/37167447/91375329-599b4b80-e7e8-11ea-9c1b-8611042e80ff.png)
El primer `print` corresponde al primer objeto a sumar, en este caso `carro_1`.

El segundo `print` corresponde al segundo objeto a sumar y corresponde en este caso a `carro_2`.

En resumen, en términos de los argumentos que se le entregan al _dunder method_ `__add__`, `carro_1` equivale a `self`, mientras que `carro_2` equivale a `otro`.

Si hago otra pequeña modificación al código, invirtiendo el orden de la suma:
![image](https://user-images.githubusercontent.com/37167447/91375648-4341bf80-e7e9-11ea-89df-a739f1132a72.png)
`carro_2` pasa a ser `self` y `carro_1` es `otro`!


Avísame si no te queda claro!

**Comment by Margarita-Paz** [comment]
comprendo!! muchas gracias ;)
