### ISSUE TITLE
labels sobre labels

### ISSUE THREAD

**Issue by cambrinKD** [IIC2233/syllabus#225]
Es necesario tener QtWidgets sobre otros. Por ejemplo para los obstaculos, debería tener un label de un obstaculo sobre un label de un imagen de cesped. O para el personaje que siempre tiene que ser sobre el mapa. Como se hace esto? Hay un coordenada z?

**Comment by jeschuwirth** [comment]
Saludos!

Por lo general cuando existe colisión entre QtWidgets siempre queda el más antiguo por debajo y el nuevo por encima tapándolo en las partes donde colisionan.

Esto no es un problema, ya que es normal que tu personaje o una torre se superponga a los sprite del mapa, mientras el juego se pueda ver correctamente (que tu personaje o enemigos no se metan debajo del mapa) no deberías tener problemas.

El método raise() de QWidget te permite levantar un sprite anterior y que se vea encima de los más nuevos.

Suerte en la Tarea :D
