### ISSUE TITLE
Cambio de color en fichas

### ISSUE THREAD

**Issue by andreslyon** [IIC2233/Syllabus#225]
Por lo que entendí del enunciado cada vez que un jugador pone una ficha en el tablero, es turno del otro y además cada jugador tiene un colo (azul o rojo) sin embargo, al ejecutar demo.py y simular un juego, los colores de las fichas no salen intercalados (y su atributo color tampoco).
Es porque nosotros tenemos que implementar eso?

**Comment by sebacruzd** [comment]
Exacto.
