### ISSUE TITLE
Menu preparación carrera

### ISSUE THREAD

**Issue by pwillmer** [IIC2233/syllabus#225]
Hola!, al momento que el jugador debe preparar la pista debe escoger el tipo y luego se asigna una aleatoria de ese tipo? o la debe escoger por el nombre de ella?

**Comment by gatochico** [comment]
Hola! 

El jugador debe elegir **la pista en específico** en la cual desea participar. Por lo tanto, si hay dos pistas del mismo tipo (dos pistas de hielo, por ejemplo), el usuario debería poder elegir entre cual de las dos usar para la carrera. Ahora, queda a tu criterio ver como ingresar el input (input numérico, por nombre, etc.,)
Saludos!

**Comment by pwillmer** [comment]
Entonces, en primera instancia escoge si quiere Hielo, Rocas o Suprema y luego escoge las disponibles de ese tipo? No podría mostrar las 6 pistas disponibles indicando de qué tipo son?
Ej con 4 pistas:

"nombre1" -- Pista Helada
"nombre2" -- Pista Helada
"nombre3"--- Pista Rocosa
"nombre4"---Pista Suprema

**Comment by gatochico** [comment]
Queda a tu criterio como mostrar las pistas a elegir! Si quieres que primero escoja el tipo, y luego las disponibles de ese tipo, es válido. Por otro lado, si quieres mostrar todas las pistas de inmediato como muestras en el ejemplo, también es válido! :rainbow:

**Comment by pwillmer** [comment]
Perfecto, gracias :)
