### ISSUE TITLE
Duda ejemplo 2-concurrencia sem 5

### ISSUE THREAD

**Issue by magdafernandez** [IIC2233/Syllabus#225]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola!, espero estén bien, tengo una duda de la semana 5, 2-concurrencia en el ejemplo en se usa los métodos `set()`, `clear()`, `wait()`, `is_set()` de los *threads* en un mismo problema (el del jefe y el trabajador). No entiedo porque al correrlo ocurre lo siguiente:
![image](https://github.com/IIC2233/Syllabus/assets/106499547/e271f019-a1e3-4594-8a02-2d67e98f7070)
A pesar de que el trabajador le pide el pago, el jefe dice que no se lo han pedido. 
¿Porque puede estar ocurriendo esto? 
Gracias! 
Magda.-

**Comment by catalinamirandah** [comment]
Hola Magda✨,

Si bien en este código se utiliza  join en ambos threads, esto no garantiza necesariamente que los hilos se ejecuten de manera completamente intercalada y sincronizada como se espera en tu caso.

Una forma rápida que se me ocurre para arreglar eso en este ejemplo en particular es cambiar el time.sleep(1) de la función trabajar_trabajador(semanas) por time.sleep(1.1). Lo que estamos haciendo en este caso es evitar que ambos ciclos ocurran al mismo tiempo, lo cual le permitirá al jefe enviar todos sus mensajes antes que el trabajador lo haga.

Me imagino que pueden haber más formas de arreglarlo, eso fue lo que se me ocurrió ahora cuando leí esta pregunta. Podrías ir jugando con el código para intentar hacerlo de otras maneras utilizando los contenidos del curso.

Saludos 🤗
