### ISSUE TITLE
README - Tecla de disparo

### ISSUE THREAD

**Issue by martingonzalezs** [IIC2233/Syllabus#225]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X - X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Disparo - README
Buenas, sumándome a mis compañeros de las issues anteriores, comento que se me olvidó mencionar cuál es el botón para disparar en mi código. Cuando ya se está en la ventana de juego, **se dispara con la letra K** en vez del espacio, ya que presenté problemas para implementar el disparo con esta tecla.
Pido disculpas las molestias, sin más que agregar,
Martín González.

**Comment by octavioaguila** [comment]
Hola! Olvidé exactamente lo mismo que mi compañero al no especificar la tecla de disparo en el README. En mi tarea también se ejecuta el disparo con la **letra K**. Espero que este sea el medio para comunicarlo, quedo atento. Disculpen las molestias, muchas gracias!

**Comment by matiasmasjuan** [comment]
Hola @martingonzalezs, @octavioaguila . Gracias por la información. Lo tendremos en cuenta al corregir sus tareas :ok_hand:
