### ISSUE TITLE
Tiempo de carga base de datos

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#225]
Hola, 
Mi código se está demorando entre 90 y 110 segundos en cargar la base de datos con todos los jugadores y sus relaciones en memoria (solo los que se conocen) en el grafo. ¿Es demasiado? 😰 😰 😰 
Como son 5501 jugadores no puedo hacer menos de 15133251 iteraciones aprox  😟 😟

**Comment by cilopez** [comment]
Sigue esta issue #188
