### ISSUE TITLE
Duda con property setter

### ISSUE THREAD

**Issue by rldelafuente** [IIC2233/syllabus#225]
Hola! Tengo dudas con el uso de property setter.
- Por ejemplo, esto se podría haber usado para la tarea 00, en la parte de crear un usuario nuevo que cumplas ciertas características? En la tarea 00 yo ocupé un while con una condición booleana, que paraba cuando cumplía todas las condiciones de validación, pero me quedó la duda si esto se podría haber hecho con property.

- Otro caso, si tengo una ejemplo como el del ejemplo del puente y su capacidad máxima. Si tiene una capacidad máxima de 20 personas, lo que hacía el ejemplo era fijar este como máximo si se excedía. Puedo hacer que haya un input al usuario de cuántas personas quiere que hayan en el puente y que si este excede el máximo, diga “excede el máximo” y vuelva a pedir un input, usando solo property setter, sin while boolenaos asociados?

Gracias de antemano!

**Comment by KnowYourselves** [comment]
Hola @rldelafuente!

Respecto a lo primero, lo del `while` está bien, solo que con el uso de `setter` hubiera quedado más ordenado. Lo que se podría haber hecho es que la clase `Usuario` partiera con `username = None` y no aceptara modificar ese valor si es que se quería cambiar por algo inválido, por ejemplo si hubiéramos tenido la sig. modelación:

```python3
class Usuario:
    def __init__(self, username):
        self.__username = None
        self.username = username

    @property
    def username(self):
        return self.__username

    @username.setter
    def username(self, valor):
        if valor cumple mis condiciones:
            self.__username = valor
````

El código para pedir el nombre de usuario pudo haber sido simplemente:

```python3
username = input("Ingrese su nombre de usuario:" )
user = Usuario(username)
while not user.username: # Mientras el username haya sido inválido
    user.username =  input("Ingrese su nombre de usuario:" )
```

En cuanto a lo segundo, no se puede lograr el comportamiento que describes sin un ciclo. Esto se debe que no vas a saber de antemano cuantos intentos le va a tomar al usuario ingresar un valor válido, pueden ser 10, o 10000, más aún, si bien sería buena práctica usar un setter de todas formas, en ese contexto no te sirve ni ahorra demasiado código, ya que el caso que te describi en el párrafo anterior sirve cuando se quieren inicializar valores, más bien no cuando estos se quieren modificar.

Espero haberte ayudado!

**Comment by rldelafuente** [comment]
Perfecto!!! Muchas gracias. ;)

**Comment by KnowYourselves** [comment]
Recuerda no cerrar tus issues!, Es para que el resto las pueda ver bien. 

Que bueno que te haya servido la ayuda! :D
