### ISSUE TITLE
Duda acerca clase Item

### ISSUE THREAD

**Issue by enzoacvi** [IIC2233/Syllabus#225]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola,

En la pauta dice que debemos crear la clase `Item` y que, según lo mencionado en la issue #211 debe contener al menos un método y un atributo. Mi duda radica en que en el enunciado la funcionalidad de evolucionar se le atribuye a los combatientes y en la issue #200 esto se reitera.

Entonces **¿Está bien si el método corresponde solamente al `__str__`?** Porque al parecer la funcionalidad de evolucionar (a nivel de código) debe estar en los combatientes, y no a los ítemes.

**Comment by CrisDonosoMaass** [comment]
Hola! Mientras item no esté vacío está correcto por lo tanto __str__ sí sirve en este caso.

**Comment by enzoacvi** [comment]
Ok, muchas gracias!
