### ISSUE TITLE
Mensaje de error en el juego

### ISSUE THREAD

**Issue by ferperezh** [IIC2233/Syllabus#226]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola el mensaje de error o pop-up q se debe enviar por ciertos problemas debe ser enviado a la terminal o a la interfaz y como hago un pop-up?

**Comment by tamyhan** [comment]
Hola @ferperezh ! El mensaje puede ser mostrado en la interfaz (en la ventana que se está mostrando en ese minuto) o como un pop-up. Para hacer los pop-ups se debe abrir una ventana nueva que notifique el error, en el momento que ocurrió. Te recomiendo investigar sobre los _QMessageBox_ para implementar los pop-ups.
