### ISSUE TITLE
Duda valores límite en evolución

### ISSUE THREAD

**Issue by BrucherBeta** [IIC2233/Syllabus#226]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!!!! Tengo una duda con la tarea sobre el enunciado. Los valores de defensa, poder, agilidad, etc. por enunciado dice que solo puede llegar hasta un cierto valor, pero en el caso de las evoluciones tienen un buff de poder, queria preguntar que ¿ocurre en caso que el buff supere algun limite de los atributos? Si el valor maximo de defensa es 10 y con el buff llega a 12, cual mantengo?

**Comment by BrucherBeta** [comment]
Me confundi con el titulo y el texto de la duda. Pido disculpas

**Comment by CrisDonosoMaass** [comment]
Hola!

Los valores máximos no se pueden superar por lo tanto cuando un buff aumente un atributo más allá del límite debes mantener el máximo.

Ojalá haya respondido tu pregunta!
