### ISSUE TITLE
medidas del gobierno

### ISSUE THREAD

**Issue by rjdelrio** [IIC2233/Syllabus#226]
hola tengo una pregunta que pasa si un país propone dos propuestas las ponga en la cola igual aun que sean del mismo país.
y otra cosa mas si un país tiene por ejemplo 1 infectado y por lo tanto el gobierno no va a elegir ninguna acción puedo asumir que el valor de ninguna acción es 0.

**Comment by rpalmaotero** [comment]
No entiendo muy bien tu pregunta. Puedes redactarla de nuevo?
