### ISSUE TITLE
Décimas AC01

### ISSUE THREAD

**Issue by tomasalvarez13** [IIC2233/syllabus#226]
Hola, que puedo hacer si no recibí décimas por la actividad formativa 1 y sin embargo la realicé y respondí el form?

**Comment by mfortiz** [comment]
A mi igual me pasó, la rellené a las 16.50 el mismo día

**Comment by visalasc** [comment]
A mi también :(

**Comment by Drpinto1** [comment]
Hola :D

Se abrirá un form para que puedan apelar a las décimas de la AC. En cuanto este se habilite se les mandará un anuncio con el link para hacerlo.

¡Saludos!
