### ISSUE TITLE
Valores de los parámetros 

### ISSUE THREAD

**Issue by lfb1206** [IIC2233/syllabus#226]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Donde encontramos los valores que vayan a tener los diferentes valores constantes que escribimos en parámetros.py. ¿Estos serán puestos por los ayudantes que corrijan nuestras tareas o están en algún archivo?

**Comment by santiagovegaf** [comment]
Hola @lfb1206!

Para los parámetros que no tiene un valor definido es tu deber completarlos con datos a gusto.  Puedes definirlos de la misma forma que los que el resto de los parámetros de `parametros.py`.

Debes tener en cuenta que estos pueden ser modificados al momento de la corrección, por lo que tu programa debe soportar estos cambios.

Éxito en el desarrollo de tu tarea!
