### ISSUE TITLE
Método rotar pieza (a la izquierda)

### ISSUE THREAD

**Issue by paula-ds** [IIC2233/Syllabus#226]
Hola!, tengo una duda, el método rotar pieza recibe una orientación, pero el método de por sí (el de  game.py) no recibe nada y rota hacia la derecha porque así está escrito, hay que hacer que de alguna forma rote a la izquierda también? o no hay que meterse con ese método?

**Comment by Sforrego** [comment]
tengo la misma duda :/

**Comment by iqacevedo** [comment]
Hola, 

Consideren que siempre se va a rotar hacia la derecha (orientation siempre será derecha). No necesitan hacer que rote a la izquierda, así que no se preocupen, si por algún motivo desean rotar hacia la izquierda roten 5 veces hacia la derecha. (En #233 se actualizo la gui)

Saludos!
