### ISSUE TITLE
Cambio de arena que ya habia sido seleccionada

### ISSUE THREAD

**Issue by GuilleStanke** [IIC2233/Syllabus#226]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, si tengo una arena, llamemosla Arena 1, y la cambio (por algún tesoro o evento) por la Arena 2, si luego se tiene que hacer un cambio a una arena que sea del tipo de la Arena 1, tenemos que hacer que sea imposible que se seleccione nuevamente la Arena 1?, o no importa que una arena que ya estuvo esté de nuevo en el torneo?

**Comment by Benjeeeh** [comment]
Hola!
Como en el enunciado no se menciona de que se imposibilite usar una arena que haya sufrido cambios, esta se puede volver a seleccionar y tendría sentido la verdad que no se imposibilite ya que después de X cambios se llegaría a un bloqueo en las arenas y no se podrían hacer cambios. Lo importante más que nada de este hecho es que la elección de cada arena sea de manera aleatoria.

Mucho éxito con la tarea!!
