### ISSUE TITLE
Duda sobre avance.

### ISSUE THREAD

**Issue by nhorellana** [IIC2233/syllabus#226]
Hola! Tengo una duda que puede ser media tonta, pero para el avance sol solo solo se evualua que se cargue el mapa y se pueda jugar? Como tipo ventana unica. O tambien hay que implementar la ventana de inicio y que dandole click a jugar aparezca lo otro.

Otra cosa, esta version alpha debe modificarse con los distintos mapas.txt que puedan haber o puede ser una version"estatica"?.

**Comment by hbkim94** [comment]
Hola!

En primer lugar,  **ninguna duda es tonta**! Para eso están las issues :) 

En segundo lugar, si. Lo mínimo que se pide para el avance es que se muestre una ventana con lo pedido en la sección de avance. Por ejemplo, para la versión del personaje, pedimos que se mueva con las teclas correspondientes y se maneje la situación en que haya mínimo un obstáculo  (que no lo pueda atravesar);  además del uso de señales. Si bien pedimos que utilices los sprites, para este avance no es necesario que cargues los mapas a partir de los archivos txt. 

Espero haber respondido tus dudas!

**Comment by Dnpoblete** [comment]
Una duda relacionada con esto, si logre que todas las x, sean representadas con un fondo de una X en el mapa y el personaje no las puede atravesar esta bien?  o tengo que poner piedras por el mapa y que el personaje no las pueda atravesar?

**Comment by ByronHidalgo1** [comment]
Una consulta, acabo de subir mi avance a mi repositorio junto con un readme que explica una situación respecto a la ventana de inicio. En ningún lugar de la sección avance se señala que deba pedir nombre de usuario o elegir bando, por ende solo agregué un botón que permite jugar (una acotación incluída en el readme) y salir de la partida, ¿es suficiente para el avance?

**Comment by hbkim94** [comment]
@Dnpoblete Con tal que estés usando imágenes para el personaje (ya sean las que te entregamos o tuyas propias), todo bien !

**Comment by hbkim94** [comment]
@ByronHidalgo1 En efecto, no pedimos ningún tipo de ventana para ingresar usuario/menú para este avance. En ese aspecto, es más que suficiente : )
