### ISSUE TITLE
Duda sobre código en if __name__ que aparece mucho en distintos ejemplos

### ISSUE THREAD

**Issue by isidoragutierrez** [IIC2233/Syllabus#226]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola! Esta duda no es de algún contenido en específico, es sobre una porción de código que me ha tocado ver mucho en ejemplos de distintos contenidos que no entiendo para qué sirve.
Específicamente me refiero al código que se muestra en la siguiente imagen:

<img width="325" alt="Captura de Pantalla 2023-09-21 a la(s) 11 21 10" src="https://github.com/IIC2233/Syllabus/assets/111446584/ff03988d-ed2e-4bc1-a421-249c66064e81">

¿Para qué sirve? Intenté comentando todo lo que está dentro del if __main__ que aparece en la imagen adjunta y el código no cambiaba su funcionalidad. Me ha tocado mucho verlo en ejemplos de PyQt, seguido de alguna otra porción de código que sí es vital para le funcionamiento de éste, como en los ejemplos de "Conexión entre Ventanas". 

Muchas gracias de antemano!

**Comment by fvidalf** [comment]
Hola @isidoragutierrez!

La razón principal es que PyQt como librería maneja muchas cosas de forma diferente y propia (en parte, por ser una "máscara" sobre el Qt original escrito en C++). Una de esas cosas es el manejo de excepciones. Usualmente, si una excepción no es manejada (i.e. usar try/except), se llama al `sys.__excepthook__` por defecto, que solo imprime la excepción a la consola. PyQt no es tan confiable en ese aspecto. Hay ocasiones en las que por la forma en que PyQt maneja la excepción (y como se recibe por tu IDE como VSCode), se termina por no llamar al `sys.__excepthook__`.

¿La solución? Obligar a PyQt a que lo use 😄, y eso se hace reimplementando el `sys.__excepthook__`. Básicamente, al reimplementar el `sys.__excepthook__` (según [esta](https://www.riverbankcomputing.com/static/Docs/PyQt5/incompatibilities.html#unhandled-python-exceptions) parte de la documentación), se fuerza a que PyQt lo utilice para las excepciones no manejadas. Basta que el nuevo `sys.__excepthook__` imprima el error y el traceback, y te aseguras que siempre (y en cualquier plataforma) se muestren los mensajes de error correctamente.

tldr: Es para que siempre te muestre los errores que surgen en una app de PyQt :)

Saludos ✌🏽

**Comment by isidoragutierrez** [comment]
@fvidalf perfecto!!! Ahora que me dices, me acuerdo que al principio de la materia de PyQt nos entregaban ese código para usar como debuggeo en PyQt6.

Muchas gracias!!!!!
