### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by aayale** [IIC2233/syllabus#226]
Hola, leo leo y leo esto y no logro comprender que es lo que tengo que hacer. :( 
¿Me podrían explicar de nuevo plis? ¿y si es totalmente necesario hacerlo?

**Comment by josefinareyes** [comment]
Hola! El ```.gitignore``` es un archivo que debes crear para ignorar otros archivos que no es necesario subir a tu repositorio personal, ya que no son necesarios para la corrección de tu tarea y serán ignorados por git cuando hagas ```git push```.

Tienes que crear un archivo llamado ".gitignore" (exactamente llamado así, nada más) dentro de la carpeta de tu tarea, y dentro de él, en líneas distintas, escribir los nombres de los archivos que ignorarás (respetando mayúsculas y minúsculas y con sus respectivas extensiones), que corresponden a todo lo que se te entregue y que no modifiques, como archivos de Python que no modifiques, archivos .csv, enunciados, etc.

**Comment by aayale** [comment]
a buenisimoo ya entendí, muchas gracias

**Comment by denisseleiva** [comment]
Holaa tengo una duda con respecto a esa issue. No sé cómo crear el archivo .gitignore dentro de la carpeta. Intenté con git touch desde la terminal pero no pasa nada, y si dentro de la carpeta hago click derecho dentro de la carpeta no me aparece la opción como de crear un archivo (será porque tengo mac?) ¿De qué otra forma puedo crearlo?

**Comment by josefinareyes** [comment]
Qué editor de código estás usando? Si usas VSCode puedes abrir la carpeta de tu tarea en el editor y apretar el ícono de archivo nuevo que aparece al lado del nombre de tu carpeta, lo nombras ".gitignore", y listo!

**Comment by denisseleiva** [comment]
Gracias!!! me funcionó. Otra pregunta, me aparece un archivo README.log, ¿Este tiene que ir en el .gitignore?

**Comment by josefinareyes** [comment]
Además de los módulos de tu tarea, solo tienes que subir el ```README.md``` a tu repositorio. Otros archivos generados que no sean parte de la tarea deberías ignorarlos!

**Comment by denisseleiva** [comment]
Buenisimoo, muchas gracias!!!! 😁😁
