### ISSUE TITLE
Duda con reduccion de poder en ataque de caballero

### ISSUE THREAD

**Issue by Martinluco** [IIC2233/Syllabus#227]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] 
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

En caso de que se active el poder del caballero se habla de una reducción de poder del enemigo, esta reducción es permanente? o es solo durante el ataque? si es la segunda, que función tendría realmente dado que el poder del enemigo no influye al momento del ataque? Muchas gracias :)

**Comment by Martinluco** [comment]
tambien aplica en las otras clases con poderes :)

**Comment by CrisDonosoMaass** [comment]
Hola!

Poderes como la reducción de poder ocurren sólo durante el ataque, es decir, antes de pegarse con el enemigo deberían aplicarse los cambios de atributos. Luego del ataque las características vuelven a como deberían estar normalmente sin la reducción.

Respecto a tu segunda pregunta, el poder si influye en los ataques del enemigo, adjunto formula de cómo se calcula el ataque:
![Attack_Power](https://github.com/IIC2233/Syllabus/assets/106105065/7d7fa9d0-e63f-43de-8ea8-91b98b73be4b)

**Comment by Martinluco** [comment]
Gacias! Pero ese es el poder de la clase que ataca, pero al momento de atacar reduce el poder de la clase que está siendo atacada, el cual no influye, ya que lo que se tiene en cuenta es su defensa
