### ISSUE TITLE
Imagen cortada en celda grilla

### ISSUE THREAD

**Issue by tavalenzuelag** [IIC2233/syllabus#227]
Hola!, por algun motivo cuando cargo la imagen respectiva a cada celda de la Qtgridlayout que representa al mapa, esta aparece cortada, es decir, en cada celda de la grilla tengo la imagen correspondiente pero cortada. He buscado bastante para corregir este problema sin embargo sigo sin poder solucionarlo. Les agradecería si pudieran facilitar información al respecto.
Saludos!

**Comment by KnowYourselves** [comment]
Hola @tavalenzuelag!

Tal vez la _issue_ #204 te sea útil.

Espero haberte ayudado!

**Comment by tavalenzuelag** [comment]
No tengo problemas con la separación de cada celda, sino con el contenido esta (en este caso una label (imagen)) que no aparece completa .

**Comment by KnowYourselves** [comment]
Te recomiendo el siguiente proceso para identificar el problema:

1. Prueba instanciando los QLabel fuera del QGridLayout, Si siguen cortados, entonces es un problema de como estas usando QLabel. 
2. Si es que las imagenes ya no están cortadas, entonces es un problema de como estás usando QGridLayout.

En ambos casos te recomiendo leer la documentación de [QLabel](https://doc.qt.io/qt-5/qlabel.html) y [QGridLayout](https://doc.qt.io/qt-5/qgridlayout.html#details). Si ya hiciste esto, o no logra encontrar la solución dime y te sigo ayudando!

Independiente de todo esto, es probable que tu imagen se corte porque no estás escalando el Pixmap al tamaño del QLabel. (Te recomiendo investigar la función `scaled` de [QPixmap](https://doc.qt.io/qt-5/qpixmap.html))

**Comment by isihirmas** [comment]
Tengo el mismo problema! Y sí instancié las QLabel fuera del QGridLayout. También le hice resize y no funcionó.

**Comment by Hernan4444** [comment]
¡Hola!

Hay un método para los `QLabel` llamado `setScaledContents` que puede ser de utilidad, esto te va a escalar el contenido lo cual hará que no se corte. Te dejo un código de ejemplo de como usarlo.

```python
class MainGame(QWidget):
    # en el init
        self.grid = QGridLayout(self)
        self.label = QLabel(self) 
        pixmap = QPixmap("PATH").scaled(QSize(20, 20)) # El 20, 20 es el tamaño
        self.label.setPixmap(pixmap)
        self.label.setScaledContents(True)
        self.grid.addWidget(self.label, 0, 0)
```

Saludos ✌️

**Comment by tavalenzuelag** [comment]
Gracias!

**Comment by isihirmas** [comment]
Lo usé pero la interfaz gráfica se sigue viendo igual, tampoco logro que me aparezca la ventana completa:



<img width="1440" alt="mapa_malo" src="https://user-images.githubusercontent.com/43628848/57744507-7b29ff80-7697-11e9-819f-6acaec651341.png">

**Comment by Hernan4444** [comment]
Hola, creo que eso pasa porque estás usando tamaño de pixeles demasiado grandes y estás definiendo el tamaño de la pantalla como menor, algo así como poner 100 cuadros de 20x20 cada uno, pero la ventana es de 50x50, no caben todos. Puedes verificar que el tamaño máximo admitirá el mapa según el "N" que le estás dando?

**Comment by isihirmas** [comment]
Es que incluse probé el caso de N=1 en el resize, y el set geometry de la ventana del juego es self.setGeometry(0, 0, 100, 100) y me entrega exactamente el mismo resultado, solo que sin el cuadradito de la esquina de antes que estaba extra.

**Comment by Hernan4444** [comment]
pero probaste con el código que pasé, ahí no se ocupa resize, sino que el método `scale`? Porque hice eso mismo con resize y no me funcionaba, pero si me funcionó con `scale`

**Comment by isihirmas** [comment]
Sí, probé con ambos :(

**Comment by Hernan4444** [comment]
puedes subir tu código please, para ver lo que estás haciendo 😄

**Comment by isihirmas** [comment]
listo! gracias!

**Comment by Hernan4444** [comment]
Revisé tu código y en el archivo `frontend.py` creas los QPixmap pero no le pusiste el scale. Los acabo de agregar y ahí se me vió todo. Te dejo un ejemplo de como lo dejé: (recuerda importar QSize de QtCore)

`celda.setPixmap(QPixmap("sprites/"+self.bando+"/base_cuadrada.png").scaled(QSize(20, 20)))`

Saludos :v:

**Comment by isihirmas** [comment]
Muchas gracias! Pero con este scale ya no sirve el setSpacing()?

**Comment by Hernan4444** [comment]
No estoy seguro, te recomiendo probar los efectos de setSpacing con diferentes valores y si nada cambia, entonces justamente ese método ya no sirve, pero como dije, no estoy seguro, lo mejor en computación ante estos casos es probar.

Saludos ✌️

**Comment by isihirmas** [comment]
Muchas gracias!!
