### ISSUE TITLE
DUDA AC2 sobre property en def autonomia

### ISSUE THREAD

**Issue by JosefaATP** [IIC2233/Syllabus#227]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema
Hola!
No entiendo muy bien aquí lo del property, ósea las instrucciones son porque eso es lo que debe hacer el setter? o solo el property? pero y el setter de esa property?

Gracias! 😁

![image](https://github.com/user-attachments/assets/b85cafea-39d4-4585-a7c4-ff3abd3aba62)

**Comment by carlosmartellus** [comment]
Hola @JosefaATP!

Vamos parte por parte, lo primero es que el enunciado solo menciona la ```property```.

Lo segundo es que hay properties que pueden no tener ```getter```.

Si te quedan más dudas acerca del tema, te recomiendo volver a los contenidos o buscar documentación.

Éxito en tu actividad!

**Comment by JosefaATP** [comment]
Ahhh!
Entiendo, había entendido que los properties siempre tenían que tener setter.

Gracias!
