### ISSUE TITLE
Duda de excavadores descansando

### ISSUE THREAD

**Issue by GuilleStanke** [IIC2233/Syllabus#227]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

buenas tardes! Una pregunta, para los excavadores que están descansando... si usamos un consumible que otorga energía, los excavadores que están descansando dejan de descansar si llegan a 100 de energía gracias a ese consumible?, o los consumibles no le servirían a los que están descansando?...
en caso de que sí les sirvieran, en cuanto aumento su energía? ya que solo nos indican que un excavador llegará a 100 de vida al cumplir los días de descanso, pero no se menciona si hay que ir aumentándole de a poco su energía a medida va cumpliendo sus días de descanso

**Comment by CarolinaMezaCh** [comment]
Hola @GuilleStanke!!

El efecto de usar los consumibles aplica para todos los integrantes del equipo, según el enunciado:
"Usar consumible: Para cada uno de los excavadores dentro del equipo, se aplicará los efectos del
consumible seleccionado". Respecto a cuánto aumentará el nivel de energía, dependerá del atributo de energía de ese consumible encontrado según lo que aparece en consumible.csv.
En cuanto a los días de descanso puedes dejarlo a tu criterio, es decir, podrías escoger que cumpla los días aunque haya llegado al 100 de energía o puedes acortarlos con una restricción en el caso que haya llegado al 100 de energía (antes de cumplir los días) al consumir los consumibles encontrados.
Espero haber aclarado tu duda!
