### ISSUE TITLE
Cómo eliminar archivos del repositorio

### ISSUE THREAD

**Issue by gaspcr** [IIC2233/syllabus#227]
Hola, resulta que subí el archivo '_parametros.py_' ya que lo estaba utilizando para guardar algunas variables de mi código. Luego de leer varias issues donde se comenta que este no debe estar en el repositorio personal decidí cambiar mis variables a otro '_.py_' y dejar ese como estaba en un comienzo. La cuestión es que ya realicé '_git push_' a ese archivo y me gustaría saber como sacarlo de mi repositorio con **git bash**, ya que recuerdo que dijeron que no debíamos modificar nuestro repositorio desde el navegador para evitar errores de versiones entre el repositorio de la nube y la carpeta de nuestro ordenador.

Desde ya muchas gracias! :D

**Comment by DCCollao** [comment]
Hola!

Si borras los archivos de tu repositorio local y luego haces push, deberían bajarse del repo remoto. Si realmente lo quieres hacer con git bash, podrías intentar utilizando el comando `git rm`, pero te recomiendo que [leas](https://docs.mikelgoig.com/git-github/git-rm-eliminar-archivos.html) un poco sobre las diferencias entre cada uno antes de irte por la segunda opción:
