### ISSUE TITLE
Falta acceso a rotar en gui

### ISSUE THREAD

**Issue by Polea012** [IIC2233/Syllabus#227]
Una consulta:

En mi logica necesito dibujar las piezas colocadas rotadas cuando se refresca el juego (por ejemplo, al recuperar una versión guardada). ¿Como se podría acceder a un metodo que las dibuje (por ejemplo, al gui.rotate_piece) ? Ya que no está disponible en la interfaz.

**Comment by iqacevedo** [comment]
Hola, 

Tienes razón, por este motivo se actualizo la gui, se comunico en esta issue #233.

Saludos !
