### ISSUE TITLE
Cantidad de conexiones

### ISSUE THREAD

**Issue by nachojarasaez** [IIC2233/Syllabus#227]
- En la tarea se señala que para calcular la probabilidad de propagación debemos dividirlo por el numero de conexiones. El numero de conexiones va a ser la suma de todas las conexiones tanto terrestres como aéreas del país infectado o va a ser la suma de conexiones con el país que estoy revisando (en el segundo caso el valor de numero de conexiones es 0 o 1 o 2).
- En relación a la propagación dentro de un país, lo calculo persona a persona (cuantos infecta cada persona) o calculo un random entre 0 y 6, lo multiplico por lo indicado, y multiplico por la cantidad de personas??

**Comment by stephichau** [comment]
1. El número es la suma de todas las conexiones 

2. Puedes calcular un random y multiplicarlo por el número de personas
