### ISSUE TITLE
[Interfaces gráficas] Alineación de texto en input

### ISSUE THREAD

**Issue by renataramirez** [IIC2233/Syllabus#227]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Creé la GUI que adjunto en el siguiente código, y me gustaría saber como puede alinear el texto del output para tenerlo en el centro de la casilla desde el momento en que se empieza a ingresar, ya que de la forma en la que está ahora solo lo alinea una vez que apreto el botón.

```python
import sys
from PyQt6.QtWidgets import QApplication, QWidget, QLineEdit, QPushButton, QTextEdit, QVBoxLayout
from PyQt6.QtGui import QIcon
from PyQt6.QtCore import Qt


class MyApp(QWidget):
    def __init__(self):
        super().__init__()
        self. setWindowTitle("hola app")
        self.setWindowIcon(QIcon("feliz"))
        self.resize(300, 100)  # ancho, alto

        layout = QVBoxLayout()
        self.setLayout(layout)

        # Wigets
        self.inputField = QLineEdit()
        button = QPushButton("&Haz click aquí", clicked=self.decirHola)
        # button.clicked.connect(self.decirHola)
        self.output = QTextEdit()

        layout.addWidget(self.inputField)
        layout.addWidget(button)
        layout.addWidget(self.output)

    def decirHola(self):
        inputText = self.inputField.text()
        self.inputField.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.output.setText("¡Hola, {}!".format(inputText))
        self.output.setAlignment(Qt.AlignmentFlag.AlignCenter)


# app = QApplication()
app = QApplication(sys.argv)

window = MyApp()
window.show()

sys.exit(app.exec())

**Comment by diegobas10** [comment]
Hola @renataramirez 

Lo razón por la que pasa esto es porque la ventana no se está actualizando a tiempo real, al no tener una señal que le avise que cambie al momento de editarla, por eso cambia al apretar el botón.
Para arreglar esto puedes ocupar la siguiente línea para que se actualice al momento de escribir.
self.inputField.textChanged.connect(self.on_text_changed)

**Comment by diegobas10** [comment]
Hola @renataramirez 
La razón por la que pasa esto es porque la ventana no se esta actualizando a tiempo real, al no tener una señal que le avise que cambie al momento de editarla, por eso al momento de apretar el botón recién se actualiza, ya que esta llama a la función decirHola donde se pone la alineación al centro y no antes.
Por lo tanto para arreglar tu problema tienes poner la alineación a la hora de definir self.inputField de la siguiente manera.
```
class MyApp(QWidget):
    def __init__(self):
        super().__init__()
        self.inputField = QLineEdit()
        self.inputField.setAlignment(Qt.AlignmentFlag.AlignCenter)

```
O si quieres que se actualicen multiples cosas del QLine puedes definir una función que actualiza el texto a todo momento de escribir con una señal,
```
class MyApp(QWidget):
    def __init__(self):
        super().__init__()
        self.inputField = QLineEdit()
        self.inputField.textChanged.connect(self.alinear)
   def alinear(self):
        self.inputField.setAlignment(Qt.AlignmentFlag.AlignCenter)

```
Quedo atento a cualquier duda
Saludos
