### ISSUE TITLE
for i in range()?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#227]
Está permitido usar ` for i in range()` en la tarea 2?

**Comment by IchottMano** [comment]
@naquiroz Hola!

Lamentablemente, ya que lo retornado por la función *range* es un objeto *built-in* de python, no puedes usarlo a menos que lo *desempaquetes* con tu propia estructura. *(Hint: Para desempaquetar range debes desempaquetar list(range()), de otro modo no puede ser desempaquetado)*

Saludos!
