### ISSUE TITLE
Parámetro CARGA_MAXIMA_X

### ISSUE THREAD

**Issue by barbaracalderonr** [IIC2233/syllabus#227]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X]  Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X]  Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X]  Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X]  Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!; me confunde un poco lo de la carga máxima de cada barco, por que viene ya en el archivo barcos para cada barco, pero además cuando específica el tipo de barco, dice que debería estar en los parámetros...
no sé si la carga máxima de un barco al final es la que viene en el csv, o depende de si es carguero, pasajero o buque ....

**Comment by gatochico** [comment]
¡ Hola @barbaracalderonr !

Mala nuestra 😅 , tal como dices, la carga máxima de cada barco debe ser extraida del archivo `barcos.csv`. Se ha modificado el enunciado para eliminar este parámetro.

Gracias por avisar!
