### ISSUE TITLE
Carrocería y velocidad autos

### ISSUE THREAD

**Issue by agustin-rios** [IIC2233/syllabus#227]
Hola! me preguntaba si es que la carrocería podia recibir daño (y como?) para que así la velocidad de los autos en la carrera cambie

**Comment by gatochico** [comment]
Hola! Según el enunciado, **solo el chasis recibe daño**, por lo que no, la carrocería no debería recibir daño. Con respecto a la velocidad, sólo debes regirte por las fórmulas del enunciado y no agregar nada extra (aunque sea para hacer que la velocidad de los autos cambie). :car:

**Comment by muovalle** [comment]
A que se refiere con mencionar si su velocidad se vio afectada por algún objeto u obstáculo en la pista. Si hubo daño a su vehículo? o si en la formula de velocidad me afectaron hielo o rocas? No entiendo como ver esto, porque si es la segunda siempre se vera afectada ya que siempre hay hielo o rocas.

**Comment by gatochico** [comment]
Ese punto principalmente se refiere a si hubo daño al vehículo, sin embargo, si quieres asegurarte e incluir la forma en que afecta la pista en sí a la velocidad (por hielo, o rocas), no estaría demás indicarlo también :see_no_evil: (nos ayudaría a corregir, pero no es necesario :0 ).

**Comment by muovalle** [comment]
ya perfecto! y no importa que daño al vehículo no este relacionado con la velocidad?
