### ISSUE TITLE
Duda animacion Sprites T2

### ISSUE THREAD

**Issue by Ikilly0** [IIC2233/Syllabus#227]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X]  Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X]  De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Muy simple, queria saber si existe una manera 'optima' segun ustedes de usar los sprites de caminar, si no mal entiendo, creo que quieren que usemos setPixmap sobre la label del pj coordenada con un thread que corre de manera continua para cambiar el sprite. Que exactamente del proceso quieren que quede en back-end y que en front-end. Personalmente, entiendo que los parametros para el archivo de los sprites se leen en el front end, pero no se que trabajo le deja eso al back end? ser el thread-reloj?. Muchas gracias por la aclaracion.

**Comment by mmunoz12** [comment]
Hola @Ikilly0! 👋🏻
Como bien dices, el front-end se debe ocupar de toda la parte gráfica de _DCCrossy Frog_, pero para que se lleven a cabo las mecánicas del juego y los movimientos de Froggy, es sumamente necesario el uso del backend. Debes preocuparte que tu frontend **no contenga la parte lógica del juego y que sólo posea lo necesario para modificar las entidades dedicadas a lo visual**. 

Por lo tanto para el movimiento de Froggy, luego de que se reciba una señal (pulso de una tecla) se debe enviar al backend para que este revise la acción de mover a Froggy, para que luego el frontend tenga el “visto bueno” de hacer las modificaciones visuales necesarias. Si sólo se utilizase el frontend para realizar los todos los movimientos, a simple vista todo iría bien, pero las demás mecánicas del juego no estarían enteradas de lo que esta pasando y cómo deben responder a ello para cumplir con lo esperado, por eso es importante la separación frontend-backend. 

Avisame si te quedan dudas! Mucha suerte en tu tarea ☺️

**Comment by jsilvalavin** [comment]
Hola! pregunta si tengo cosas en el front-end como limitaciones en los movimientos o checkeos de colisiones, eso deberia moverlo al backend? gracias :)
