### ISSUE TITLE
Entidad Torneo caracteriítica eventos

### ISSUE THREAD

**Issue by rominaarancibia** [IIC2233/Syllabus#228]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! En el enunciado dice que la característica "Eventos" corresponde al conjunto de los eventos que pueden ocurrir durante el torneo.  ¿es necesario ocuparla obligatoriamente alguna vez en el programa dandole una funcionalidad? o bien puedo tenerla pero no ocuparla.  
Gracias

**Comment by CarolinaMezaCh** [comment]
Hola @rominaarancibia!!

La forma en que ocupes la parte de características de Eventos dependerá de cómo hayas definido tu diagrama de clases. Queda a tu criterio sobre cómo la ocupes, pero tienes que tomar en cuenta ese conjunto por si ocurre la probabilidad de iniciar evento, ya que las probabilidades de ocurrencia dependerán del tipo de evento.
Espero haber aclarado la duda!

Éxito con la tarea!!
