### ISSUE TITLE
Librerías permitidas y no permitidas T2

### ISSUE THREAD

**Issue by mpiavf** [IIC2233/Syllabus#228]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:
 
> ¿Puedo usar la librería `nombre_librería` para hacer `explicación_de_lo_que_quiero_hacer`? 
 
¡Recuerden especificar en su README qué librerías utilizan!
 
---
 
## ✅ **Librerías Permitidas**
- ABC
- collections 
- random
- os.path
- typing
- copy
- string
- math
- sys.argv
- sys.exit
- statistics 
- Unidecode
- _ _ future _ _

## ❌ **Librerías Prohibidas**
- sys (excepto las dos funciones permitidas)
- csv
- pandas
- numpy
- JSON
- pickle
- threading
- re
- glob
- time
- py_cui
- PyQt5
- PyQt6

## ☠️ **_Built-ins_ Prohibidos**

El uso de alguna de las siguiente funciones es automáticamente un 1,0 sin discusión: 😭
- exec 
- eval 

 
¡Éxito en sus tareas!

**Comment by xperseosses** [comment]
Creé esta función para limpiar la terminal usando la librería os y platform, es algo solo visual.
**¿Estaría permitida para la entrega?**

<img width="317" alt="Captura de pantalla 2024-09-03 a la(s) 11 13 02 p  m" src="https://github.com/user-attachments/assets/f61aea8f-9c5f-4930-a1c4-18ad92a5251a">

**Comment by mpiavf** [comment]
> Creé esta función para limpiar la terminal usando la librería os y platform, es algo solo visual. **¿Estaría permitida para la entrega?**
> 
> <img alt="Captura de pantalla 2024-09-03 a la(s) 11 13 02 p  m" width="317" src="https://private-user-images.githubusercontent.com/174909447/364448034-f61aea8f-9c5f-4930-a1c4-18ad92a5251a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0ODA2NTAsIm5iZiI6MTcyNTQ4MDM1MCwicGF0aCI6Ii8xNzQ5MDk0NDcvMzY0NDQ4MDM0LWY2MWFlYThmLTljNWYtNDkzMC1hMWM0LTE4YWQ5MmE1MjUxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQyMDA1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWJmMzI2YTRmMjBmNDk1YWU2NDM1ZWU4Zjg5NGZhZjhmMmFhY2M2YmZjZDQ3ZjM0M2UzZGY2MTVkYzc4MzNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o5qq7jg3WKdKe0Kf28QYt0rQO7GF6PCokAblPDBtInE">

Hola @xperseosses ! El uso de estas librerías no está permitido, esto se debe a que para temas de corrección se necesita que la consola no se esté limpiando constantemente.
Saludos!

**Comment by NicolasPhilippi** [comment]
Hola, se puede usar la función incorporada de python isinstance() ? La use para filtrar si un valor obtenido es float o no.

**Comment by mpiavf** [comment]
> Hola, se puede usar la función incorporada de python isinstance() ? La use para filtrar si un valor obtenido es float o no.

Hola @NicolasPhilippi ! Si se puede utilizar!
Saludos!

**Comment by fgarl** [comment]
Hola! Se puede usar la función built-in hasattr()?

**Comment by TarzanDeMaceta** [comment]
Hola, quería consultar si se puede utilizar la función "get_terminal_size()" que se encuentra en las librerias "os" y "shutil", esto para centrar los prints en la terminal de acuerdo al tamaño de esta.

**Comment by Mariana-Julia** [comment]
¿Puedo usar la librería NumPy para usar numpy.mean() para sacar el promedio entre dos valores?

**Comment by mpiavf** [comment]
> Hola, quería consultar si se puede utilizar la función "get_terminal_size()" que se encuentra en las librerias "os" y "shutil", esto para centrar los prints en la terminal de acuerdo al tamaño de esta.

Hola @TarzanDeMaceta! Sí, puedes utiilzar esta función!
Saludos!

**Comment by Toastins** [comment]
Hola! Tengo dos preguntas. 

Primero, puedo utilizar el modulo warinings? Quiero tener una forma mas limpia para informar de errores no fatales.

La segunda, puedo utilizar try except? Quiero utilizarlo no como una forma rapida para lidiar con un error desconocido, sino como una forma mas "correcta" de lidiar con errores del usuario. 
Por ejemplo, si el archivo `plantas.txt` tiene un valor fuera de rango, hacer un `raise ValueError(Tu valor esta fuera de rango)` y que el codigo tenga un bloque except ValueError en el cual le informa al usuario del error en forma de una warning, e informa que seguira leyendo la siguente linea y omitira la linea erronea.

**Comment by mpiavf** [comment]
> ¿Puedo usar la librería Unidecode para normalizar los inputs, tipo convertir "Jardín" a "jardin" y así evitar casos puntuales como tildes se consideren un ValueError?

Hola @F-Pino ! Si puedes utilizar esta librería para ello. 
Saludos!

**Comment by mpiavf** [comment]
> Hola! Puedo usar la librería Colorama para decorar el menú? O sería mas recomendable que si quiero hacer algo similar lo haga usando los codigos ANSI?

Hola @JVeloz19 ! La librería Colorama no puede utilizarse ya que debe instalarse. Lo que me comentas puedes hacerlo con ANSI.
Saludos!

**Comment by mpiavf** [comment]
> Hola! Tengo dos preguntas.
> 
> Primero, puedo utilizar el modulo warinings? Quiero tener una forma mas limpia para informar de errores no fatales.
> 
> La segunda, puedo utilizar try except? Quiero utilizarlo no como una forma rapida para lidiar con un error desconocido, sino como una forma mas "correcta" de lidiar con errores del usuario. Por ejemplo, si el archivo `plantas.txt` tiene un valor fuera de rango, hacer un `raise ValueError(Tu valor esta fuera de rango)` y que el codigo tenga un bloque except ValueError en el cual le informa al usuario del error en forma de una warning, e informa que seguira leyendo la siguente linea y omitira la linea erronea.

Hola @Toastins ! Respecto a la primera pregunta no puedes utilizar el modulo warinings. Con respecto a la segunda pregunta, se permite solo si están bien usadas las excepciones (no usar except genérico) tal como se menciona en las bases generales de las tareas. 
Saludos!

**Comment by chalaelchala** [comment]
Hola! ¿puedo usar la librería scipy.stats para usar la distribución bernoulli para seleccionar dos eventos?

**Comment by mpiavf** [comment]
> Hola! ¿puedo usar la librería scipy.stats para usar la distribución bernoulli para seleccionar dos eventos?

Hola @chalaelchala ! El uso de la librería no está permitido, ya que la libreria scipy debe instalarse.
Saludos!

**Comment by mpiavf** [comment]
> Buenas noches, ¿se puede utilizar en la tarea 2 la función map() ? , No nos la han enseñado así que tengo mis dudas :(. Es para printear una lista por comprensión!!!

Hola @mxmauoc0 ! Sí puedes utilizar esta función.
Saludos!

**Comment by VerditoRaccoon** [comment]
Hola! Aprovechando preguntas de funciones, se puede ocupar random.choice / random.choices / hasattr? Las primeras para abarcar lode escoger de manera al azar y la tercera para poder verificar si un objeto en revision tiene una determinada funcion definida. Esop ^^" No sé si serían válidas de ocupar.

**Comment by ssya333** [comment]
Hola, quería saber si se puede usar la función getattr() de la librería sys. Mi idea era usarla para usar un input (string) para instanciar una clase que ya tengo creada -> getattr(sys.modules[name], str)

**Comment by mpiavf** [comment]
> Hola! Aprovechando preguntas de funciones, se puede ocupar random.choice / random.choices / hasattr? Las primeras para abarcar lo de escoger de manera al azar y la tercera para poder verificar si un objeto en revision tiene una determinada funcion definida. Esop ^^" No sé si serían válidas de ocupar.

Hola @VerditoRaccoon ! Sí, puedes utilizar estas funciones que mencionas.
Saludos!

**Comment by nsvega** [comment]
Hola! Se puede ocupar la función .get()?

**Comment by mpiavf** [comment]
> Hola, quería saber si se puede usar la función getattr() de la librería sys. Mi idea era usarla para usar un input (string) para instanciar una clase que ya tengo creada -> getattr(sys.modules[name], str)

Hola @ssya333 ! No puedes utilizar esta función, la librería sys está prohibida menos las dos funciones permitidas mencionadas en la issue. 
Saludos!

**Comment by mpiavf** [comment]
> Hola! Se puede ocupar la función .get()?

Hola @nsvega ! Sí puedes utilizar esta función.
Saludos!

**Comment by lucasmvrtn** [comment]
hola! Se puede el type(self)? Quería usarlo en un condicional dentro de una clase, por el tema de la multiherencia.

**Comment by fgallard** [comment]
se puede usar random.random para probabilidades?

**Comment by BoPe3p** [comment]
Holaa, se puede usar la función sleep para printear con delay?

**Comment by mpiavf** [comment]
> hola! Se puede el type(self)? Quería usarlo en un condicional dentro de una clase, por el tema de la multiherencia.

Hola @lucasmvrtn ! Sí, puedes utilizar type(self).
Saludos!

**Comment by mpiavf** [comment]
> se puede usar random.random para probabilidades?

Hola @fgallard ! Sí, puedes utilizarlo.
Saludos!

**Comment by mpiavf** [comment]
> Holaa, se puede usar la función sleep para printear con delay?

Hola @BoPe3p ! No está permitido el uso de sleep en esta tarea.
Saludos!

**Comment by crainerip** [comment]
hola, se puede usar el comando del para eliminar objetos ?

**Comment by fgallard** [comment]
se puede utilizar random.sample?

**Comment by dremaker16** [comment]
Hola, puedo utilizar la clase Fraction del módulo fractions?

**Comment by mpiavf** [comment]
> hola, se puede usar el comando del para eliminar objetos ?

Hola @crainerip ! Si se puede usar.
Saludos!

**Comment by mpiavf** [comment]
> Hola, puedo utilizar la clase Fraction del módulo fractions?

Hola @dremaker16 ! Si se puede ustilizar.
Saludos!

**Comment by basy-medy** [comment]
hola, se puede utilizar @classmethod?

**Comment by vicenciomf2** [comment]
Hola! Buenas tardes, disculpa, se puede usar textwrap.dedent()? Es para escribir strings multilínea indentadas, ya que si le quito la indentación, no cumpliría con la PEP, pero si la indento, entonces queda el espacio en la string, he aquí un ejemplo

```python
    encabezado = dedent("""\
    ============================
     Se han regado tus plantas
    ============================
    """)
    
    encabezado2 = ("============================\n"
                   "Se han regado tus plantas\n"
                   "============================\n")
```

La segunda manera es la que está en contenidos, primera semana, pero se sigue viendo un poco raro, en especial cuando se tienen que hacer interpolaciones

Muchas gracias de antemano:)

**Comment by mpiavf** [comment]
> hola, se puede utilizar @classmethod?

Hola @basy-medy ! Si puede utilizarse.
Saludos!

**Comment by mpiavf** [comment]
> Hola! Buenas tardes, disculpa, se puede usar textwrap.dedent()? Es para escribir strings multilínea indentadas, ya que si le quito la indentación, no cumpliría con la PEP, pero si la indento, entonces queda el espacio en la string, he aquí un ejemplo
> 
> ```python
>     encabezado = dedent("""\
>     ============================
>      Se han regado tus plantas
>     ============================
>     """)
>     
>     encabezado2 = ("============================\n"
>                    "Se han regado tus plantas\n"
>                    "============================\n")
> ```
> 
> La segunda manera es la que está en contenidos, primera semana, pero se sigue viendo un poco raro, en especial cuando se tienen que hacer interpolaciones
> 
> Muchas gracias de antemano:)

Hola @vicenciomf2 ! Esta librería no está permitida ya que debe instalarse.
Saludos!

**Comment by vicenciomf2** [comment]
> > Hola! Buenas tardes, disculpa, se puede usar textwrap.dedent()? Es para escribir strings multilínea indentadas, ya que si le quito la indentación, no cumpliría con la PEP, pero si la indento, entonces queda el espacio en la string, he aquí un ejemplo
> > ```python
> >     encabezado = dedent("""\
> >     ============================
> >      Se han regado tus plantas
> >     ============================
> >     """)
> >     
> >     encabezado2 = ("============================\n"
> >                    "Se han regado tus plantas\n"
> >                    "============================\n")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > La segunda manera es la que está en contenidos, primera semana, pero se sigue viendo un poco raro, en especial cuando se tienen que hacer interpolaciones
> > Muchas gracias de antemano:)
> 
> Hola @vicenciomf2 ! Esta librería no está permitida ya que debe instalarse. Saludos!

Hola! Gracias por la respuesta (aún en semana de receso D:), pero podría revisar si es que se debe instalar? Creo que es un módulo built-in en python 3.11.7>

Le deseo felices fiestas patrias, ¡saludos!

**Comment by mpiavf** [comment]
> > > Hola! Buenas tardes, disculpa, se puede usar textwrap.dedent()? Es para escribir strings multilínea indentadas, ya que si le quito la indentación, no cumpliría con la PEP, pero si la indento, entonces queda el espacio en la string, he aquí un ejemplo
> > > ```python
> > >     encabezado = dedent("""\
> > >     ============================
> > >      Se han regado tus plantas
> > >     ============================
> > >     """)
> > >     
> > >     encabezado2 = ("============================\n"
> > >                    "Se han regado tus plantas\n"
> > >                    "============================\n")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > La segunda manera es la que está en contenidos, primera semana, pero se sigue viendo un poco raro, en especial cuando se tienen que hacer interpolaciones
> > > Muchas gracias de antemano:)
> > 
> > 
> > Hola @vicenciomf2 ! Esta librería no está permitida ya que debe instalarse. Saludos!
> 
> Hola! Gracias por la respuesta (aún en semana de receso D:), pero podría revisar si es que se debe instalar? Creo que es un módulo built-in en python 3.11.7>
> 
> Le deseo felices fiestas patrias, ¡saludos!

@vicenciomf2 Efectivamente es como dices! Por lo tanto, si puedes utilizarla para lo que mencionas, mi error en la respuesta anterior.
Saludos!

**Comment by vicenciomf2** [comment]
> > > > Hola! Buenas tardes, disculpa, se puede usar textwrap.dedent()? Es para escribir strings multilínea indentadas, ya que si le quito la indentación, no cumpliría con la PEP, pero si la indento, entonces queda el espacio en la string, he aquí un ejemplo
> > > > ```python
> > > >     encabezado = dedent("""\
> > > >     ============================
> > > >      Se han regado tus plantas
> > > >     ============================
> > > >     """)
> > > >     
> > > >     encabezado2 = ("============================\n"
> > > >                    "Se han regado tus plantas\n"
> > > >                    "============================\n")
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > La segunda manera es la que está en contenidos, primera semana, pero se sigue viendo un poco raro, en especial cuando se tienen que hacer interpolaciones
> > > > Muchas gracias de antemano:)
> > > 
> > > 
> > > Hola @vicenciomf2 ! Esta librería no está permitida ya que debe instalarse. Saludos!
> > 
> > 
> > Hola! Gracias por la respuesta (aún en semana de receso D:), pero podría revisar si es que se debe instalar? Creo que es un módulo built-in en python 3.11.7>
> > Le deseo felices fiestas patrias, ¡saludos!
> 
> @vicenciomf2 Efectivamente es como dices! Por lo tanto, si puedes utilizarla para lo que mencionas, mi error en la respuesta anterior. Saludos!

Muchas gracias! Ten un buen día y semana:)
