### ISSUE TITLE
propietario de las entidades

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#228]
Si pongo la última ficha de una ciudad me vuelvo su dueño y sus fichas se ponen de mi color. Si el otro jugador es el que completa un camino (o río) que une mi ciudad con otra ciudad, él se hace dueño de ese camino. ¿Quién de los dos es el dueño de la ficha en que se une mi ciudad con su camino?

**Comment by mjgutierrez1** [comment]
Por ejemplo esa ficha, si la ciudad y el camino fueran completados, qué criterio se utilizaría para saber quién es el dueño de esa ficha

![image](https://user-images.githubusercontent.com/30670535/30061927-bb4dc294-921f-11e7-86c4-be11187ef22e.png)

**Comment by TomasSalvadores** [comment]
En ese caso se prioriza la ciudad. Lo mismo se aplica para el rio.
Saludos!

**Comment by mjgutierrez1** [comment]
Ok, muchas gracias, y si se completara un río y una ciudad que también tienen fichas en común, ¿cuál entidad se prioriza?

**Comment by Arcoirisky** [comment]
Si entiendo bien tu pregunta, estás completando una ciudad y, a la vez, el río con la misma pieza. Si este Río está finalizado (Tiene inicio y final ya sea por el lago o por la grilla) entonces deberías de quedarte con la ciudad (por haberla completado) y con el río (por lo mismo. Completarlo hace la gracia de quedartelo). Caso contrario, sólo deberías quedarte con la ciudad, porque sería lo único que completaste.

¿Se entiende? Y lo más importante ¿Te respondí a tu pregunta? 😅

**Comment by mjgutierrez1** [comment]
@Arcoirisky Sí se entiende, gracias, pero eso si lo entendía, en mi pregunta me refería a que si una jugador A completa una ciudad y un jugador B completa un río, si esa ciudad y ese río tienen una pieza en común no queda claro si esa pieza será de A o de B. Supongo que esa ficha se la queda el que completó la ciudad, análogamente a lo que me contestaron más arriba para el caso ciudad-camino. Sin embargo, todavía me queda la duda de qué pasa cuando se trata de una ficha en común entre un río y un camino.

**Comment by iqacevedo** [comment]
@mjgutierrez1 se la queda el que completó la ciudad.
