### ISSUE TITLE
[Experiencia 3] Estilo de iconos clickeables

### ISSUE THREAD

**Issue by renataramirez** [IIC2233/Syllabus#228]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Tomando la solución de la experiencia 3 como código base, **me interesa editar la apariencia de los iconos clickeables en la pantalla**. Sin embargo, me cuesta bastante evaluar la mejor forma de hacerlo, ya que no me queda claro como implementar lo siguiente:

1. Implementar una función similar a 'hover' de los objetos 'QPushButton'.
2. Establecer un margen gris por defecto en cada uno de los iconos y que cuando se haga click en cualquiera de ellos, este borde sea de color verde. Sin embargo, solo un icono puede tener su borde verde a la vez, para simbolizar la selección.
3. Modificar la apariencia del botón, haciéndolo "hundible".

Hasta el momento, he hecho lo siguiente en el archivo 'ventana.py' de la carpeta 'frontend':

```python
from PyQt6.QtCore import Qt, pyqtSignal, QUrl
from PyQt6.QtWidgets import QMainWindow, QLabel
from PyQt6.QtGui import QPixmap, QIcon, QAction, QMouseEvent
from PyQt6.QtMultimedia import QMediaPlayer, QAudioOutput
from os.path import join
import frontend.parametros_frontend as p


class IconoClickeable(QLabel):
    # 'QLabel': pizarra o etiqueta que muestra texto e imágenes

    senal_click = pyqtSignal(str)
    # senal personalizada que llevara consigo una cadena de texto

    def __init__(self, tipo: str, parent):
        super().__init__(parent=parent)
        # 'super' llama al constructor de 'QLabel' antes de agregar
        # codigo a 'IconoClickeable'
        self.tipo = tipo
        # 'tipo' pasa a ser un atributo de la instancia de la clase
        self.setStyleSheet('border: 2px solid grey;')

    # TODO: QLabel especial que avisará cuando hagamos click en él
    def mousePressEvent(self, evento: QMouseEvent):
        # Este metodo se llama cuando se hace clic en el widget
        # 'IconoClickeable'

        if evento.button() == Qt.MouseButton.LeftButton:
            # Se verifica si el boton presionado del mouse es el izquierdo
            self.senal_click.emit(self.tipo)
            # se emite la senal 'senal_click', con 'tipo' como el argumento
            self.setStyleSheet('border: 2px solid green;')

# En resumen, esta clase crea un QLabel especial que emitirá una señal
# cuando se haga clic en él.
```

![image](https://github.com/IIC2233/Syllabus/assets/141946327/81b1b58f-5bce-4c79-a264-ecabb42c9d11)

Además, me sorprende que el borde no se ajuste a la silueta circular de las imágenes png.

De antemano, muchas gracias.

**Comment by Hernan4444** [comment]
Hola @renataramirez 

Esperando que estés bien, las preguntas que haces ya se escapan de lo que vemos en este curso, el tema de "hover" o cambiar borde son cosas que se ven específicamente en cursos como IIC2026 o IIC2513. Además, se ven en otros lenguajes (JS + CSS). Te recomiendo partir investigando por ese lado, aquí hay un [enlace](https://www.w3schools.com/cssref/sel_hover.php) que te puede servir.

Sobre lo del borde que nos indicas, lo que pasa es que las imágenes son cuadradas, solo que tienen fondo transparente, pero el borde se adapta a la imagen, no a su contenido. Ahí habría que investigar como hacer `round` de la imagen o como recortarla. Pero nuevamente, eso ya se escapa totalmente de lo que veremos en este curso. En esto queda intentar documentarse personalmente o bien esperar a tomar los cursos indicados, y ahí aprender dicho contenido, hay que ir piano a piano 😅

De todas formas, nunca evaluaremos la estética o el "estilo" de las interfaces. Para que no te preocupes si no logras aprender este contenido "adicional" que estás intentando enfrentar.

Saludosヾ(＾-＾)ノ
