### ISSUE TITLE
Duda con multiherencia

### ISSUE THREAD

**Issue by Martinluco** [IIC2233/Syllabus#228]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Las subclases con multiherencia (paladin, caballero arcano, mago de batalla) presentan sus propias disminuciones y aumentos de estadisticas despues de cada ataque. En caso de que llamen a los poderes de las clases heredadas, tambien tendrán las disminuciones de estas? Ej: Paladín: Los paladines son seres de luz que se rigen por el valor de la lucha. Es la combinación entre un Guerrero y un Caballero. Debido a su vasta experiencia en el combate, tienen un PROB_PAL % de probabilidad de activar sus poderes de Caballero. Además, luego de cada ataque aumentará su Resistencia en un AUM_PAL %. En este caso tendría que sufrir la disminución en resistencia de la clase caballero y aparte despues aumentar su resistencia? Gracias :)

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Dominique236** [comment]
Hola @Martinluco !

Te recomiendo revisar la issue #171 donde creo que se resuelve la misma duda que tienes.

**Comment by Martinluco** [comment]
Muchas gracias! Pense que habia revisado bien las otras issues :)
