### ISSUE TITLE
Error al subir la tarea

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#228]
Hola! Quise subir la tarea y me sale esto:

![MINGW64__c_Users_kaala_Documents_Universidad_iic2233_kalarconvl-iic2233-2020-2_Tareas 26-08-2020 23_07_00](https://user-images.githubusercontent.com/68581172/91379509-df22f980-e7f0-11ea-999c-919283732a29.png)

Creo que es porque eliminé unos archivos que subí antes a mi repositorio como puntajes.txt y los otros antes de haber leído lo del gitignore. Qué puedo hacer?

**Comment by vicentevegaulloa** [comment]
Hola @kalarconvl !

El error dice que tienes cambios en github que no están en tu computador. Intenta correr `git pull` primero y luego haces `add`, `commit `y `push`.

**Comment by kalarconvl** [comment]
@vicentevegaulloa Graciaas ahí me funcionó!

**Comment by vicentevegaulloa** [comment]
Buenisimo! De nada!!

**Comment by kalarconvl** [comment]
@vicentevegaulloa No funcionó el .gitignore :( se subieron igual los archivos que no tenían que subirse. Cómo se hace un .gitignore? Yo solo creé un archivo .gitignore y le escribí los nombres de los archivos con su extensión

**Comment by kalarconvl** [comment]
Apreté sin querer el close

**Comment by vicentevegaulloa** [comment]
Debes usar el comando `git rm --cached path_de_tu_archivo` con los archivos que quieras sacar. Lo que ocurre es que git solo ignora archivos que no estén en tu repositorio aún. Una vez que los añades con un `git add` estos no pueden ser ignorados.

**Comment by kalarconvl** [comment]
@vicentevegaulloa me tira error:

![MINGW64__c_Users_kaala_Documents_Universidad_iic2233_kalarconvl-iic2233-2020-2_Tareas 26-08-2020 23_36_07](https://user-images.githubusercontent.com/68581172/91381252-f49a2280-e7f4-11ea-86a1-4e29239efd6d.png)

**Comment by kalarconvl** [comment]
![MINGW64__c_Users_kaala 26-08-2020 23_39_01](https://user-images.githubusercontent.com/68581172/91381413-55295f80-e7f5-11ea-9955-f2a97ca653d8.png)

**Comment by vicentevegaulloa** [comment]
Debes usar el path relativo. debes ubicarte dentro de tu repo local, y escribir el path desde esa carpeta hacia adentro. Ejemplo: Si te ubicas en T00, el comando debe ser `git rm --cached puntajes.txt`

**Comment by vicentevegaulloa** [comment]
Si estás ubicada en /Tareas, el path es `T00/puntajes.txt`

**Comment by kalarconvl** [comment]
Graciaas!

**Comment by vicentevegaulloa** [comment]
De nada!
