### ISSUE TITLE
Abrir aeropuertos y fronteras

### ISSUE THREAD

**Issue by berrazuriz1** [IIC2233/Syllabus#228]
Mi duda es muy simple, las condiciones para abrir las fronteras (aire y tierra) son que estén cerradas, obviamente, y que no se cumplan las condiciones para mantenerlas cerradas, pero entonces los países que ya cerraron sus fronteras no podrán nunca abrirlas, ya que la única forma de revertir las condiciones que mantienen las fronteras cerradas es curando la gente, ¿y como vamos a curar a la gente si nunca llega la cura al país?. La única forma sería que la cura fuera descubierta en el país mismo. De echo van a haber países que nunca abrirán sus fronteras, porque murieron el 20% y no hay forma de revertir eso. Mi duda en conclusión es, ¿que tengo que hacer con los países que no cumplen las condiciones para abrir los aeropuertos?, ¿los dejo morir?

**Comment by stephichau** [comment]
@berrazuriz1 exacto, están condenados a morir.

**Comment by berrazuriz1** [comment]
Woow, thats rough.

**Comment by berrazuriz1** [comment]
@stephichau  otra duda que se que ya respondieron pero se me olvido, ¿cuando me piden el porcentaje de infectados o muertos es sobre la poblacion inicial o sobre la sana?

**Comment by timellado** [comment]
Lo que yo entendí del enunciado es que si se descubre la cura, todos los países trataran de abrir sus aeropuertos, haciendo una propuesta con valor de acción 1 para tratar de salvarse, sin haber cambiado obviamente las condiciones de cierre. ¿Estoy bien o lo dejamos como que solo se salva el país que recibe la cura y a los países que les pueda llegar (que tengan abiertos sus aeropuertos y conectados a países con cura) ?

**Comment by arturodelreal** [comment]
@timellado estas bien, pueden volver a abrirse las fronteras
