### ISSUE TITLE
función del costo de uso de cada barco

### ISSUE THREAD

**Issue by SofiaP419** [IIC2233/syllabus#228]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado sale que existe una parámetro de costo de uso asociado a cada tipo de barco (COSTO_USO_XXXX), pero no entiendo para qué sirve. Según el enunciado, el barco debe pagar por usar el canal un COBRO_USO_PRINCIPIANTE/AVANZADO, entonces ¿cumplen la misma función o son cosas distintas?. Leí el enunciado varias veces y no logro entender eso.

**Comment by gatochico** [comment]
¡Hola @SofiaP419 !

Mala nuestra 😓 dichos parámetros quedaron de una iteración anterior del enunciado, y ya no tienen utilidad. Se han publicado una versión nueva del enunciado que elimina los parámetros `COSTO_USO_X` (siendo X el tipo de barco) de este. 

Gracias por avisar!
