### ISSUE TITLE
Duda ejemplo vector

### ISSUE THREAD

**Issue by CristobalUrzua** [IIC2233/syllabus#228]
En la clase de polimorfismos está este ejemplo:

```python3
import math

class Vector: 
    """Vector desde el origen"""
    
    def __init__(self, x, y): 
        self.x = x 
        self.y = y
        
    @property
    def magnitud(self):
        return math.sqrt(self.x ** 2 + self.y ** 2)
    
    def __lt__(self, otro_punto):
        return self.magnitud < otro_punto.magnitud

v1 = Vector(2,4)
v2 = Vector(8,3)
print(v1 < v2)
```

Hasta ahí funciona bien. Lo que no entiendo, es por qué cuando le saco el @property el código no corre y dice: '<' not supported between instances of 'method' and 'method'.
No entiendo muy bien la función del property en este ejemplo.
Ayuda

Gracias.

**Comment by KnowYourselves** [comment]
Hola @CristobalUrzua!

De la matería de _properties_ hay que recordar que lo que hace una `property` es enmascarar un método como un atríbuto. 

Por ejemplo,`magnitud` es un método, ya que es una función dentro de una clase con un `return`, sin embargo gracias a `@property` esta se va a comportar **exactamente igual que un atributo**, es decir, **no es necesario llamarlo para acceder a él**.

Los métodos, al igual que las funciones deben ser llamados, es decir se les tiene que invocar haciendo uso de paréntesis, en cambio un atributo se accede inmediatamente.

Lo que pasa entonces es que si sacás el `@property` `magnitud` pasa a comportarse como un método. Luego, al llegar a `v1 < v2` entrarás al método mágico `__lt__` y se realizará la acción `self.metodo < otro_punto.magnitud`, sin embargo, `magnitud` **ya no es un atributo, es un método, porque no tiene `@property`**. Entonces, como el operador `<` no esta definido para métodos, te da ese error.

Espero haya quedado claro!
