### ISSUE TITLE
Duda dimensiones/pixeles

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#228]
Hola, no me queda muy claro a que se refiere cuando se menciona que cada elemento es de N x N pixeles, esto quiere decir que debo modificar el tamaño por defecto de cada imagen de las sprites?

**Comment by VicenteMerino** [comment]
Sobre esta misma linea, los personaje/enemigos tambien deberian ajustarse a este tamaño N x N, o solo los elementos del mapa?

**Comment by gatochico** [comment]
Hola! Si, debes modificar el tamaño de los sprites del mapa y a los enemigos/personaje para que sean de dimensión N x N .
