### ISSUE TITLE
Puntajes formulas

### ISSUE THREAD

**Issue by camaruri** [IIC2233/syllabus#228]
En la distribución de puntajes de la tarea esta en amarillo, que se corregira si los distintos puntajes se calculan bien según la formula. Mi duda es si que tenemos bien el archivo funciones.py con todas las formulas bien calculadas, pero estas no estan bien aplicadas al juego igual se obtendrá todo el puntaje por formulas bien calculadas?
Gracias

**Comment by lily416** [comment]
Hola @camaruri 🤗

Lamentablemente no podemos dar el puntaje completo por fórmulas que no interactúan con el resto del código, pues el objetivo de la tarea no es crear funciones con formulas correctas, si no que lograr un programa que funcione correctamente.

Ánimo y éxito con la tarea 👋🚗
