### ISSUE TITLE
Duda Conexión de señales en QTDesigner con backend

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2233/Syllabus#228]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Tengo una duda sobre como comunicar (conectar) un evento de un qwidget definido previamente en QtDesigner
por ejemplo un botón para después procesar la acción del botón en el back.

**Comment by cegalleta** [comment]
¡Hola!

Los botones tienen un método para saber si es que el botón ha sido apretado o no, de la misma forma, puedes sobre-escribir el evento que se ejecute en caso de apretar una tecla, te daré ejemplos de ambos para que puedas usarlos.

Tomemos el caso de un botón, supongamos haces una ventana en Qt-Designer con un botón para iniciar sesión, este botón tiene un método ```clicked``` que verifica si el botón ha sido apretado o no, de esa forma, podrías definir una acción a seguir en caso de que el botón sea apretado como sigue:

```python

class Ventana(...):
    senal_botón = pyqtSignal(str)

    def __init__(self):
        (...)

        self.boton.clicked.connect(self.accion_boton)
    
    def accion_boton():
        self.senal_boton.emit("me apretaron :D")

```

Esto hará que puedas enviar al backend mediante ```senal_boton``` el string "me apretaron :D" cada vez que se apriete el botón correspondiente. Aquella informacion podrás utilizarla como sea conveniente conectando ```senal_boton``` a algún método de una clase ```QObject``` del backend. 

En caso de presionar una tecla tendrías que sobre-escribir el método ```.KeyPressEvent(self, event)``` para que emita una señal al backend al presionar una tecla determinada. 

Finalmente, muchos de los widgets funcionan de forma similar para obtener información, por ejemplo, para obtener la tecla que fue presionada puedes usar ```event.key()``` dentro del método mencionado anteriormente, para otros objetos y widgets de PyQt generalmente existe un método que te entrega el estado del widget, por ejemplo, el texto adentro de QLineEdit, si un RadioButton está seleccionado o no, o qué se eligió en un SpinBox. 

Espero que te haya servido la explicación, si quedan dudas dime nomás :)

**Comment by cegalleta** [comment]
Oh! Acabo de ver que los definiste en Designer, es lo mismo!! En designer puedes ver el nombre de tus widgets y con ```Ventana.nombre_widget``` deberías poder hacer uso de ellos sin problema, de la forma que puse arriba.

Perdón si leí mal!!

**Comment by vice-rosas99** [comment]
pero el problema es que están enterrados en un mar de widgets, poer ejempol losbotones están en un widget que a su vez está en otro wwidget, que a su vez está en un qmainwindow, no hay un metodo para ver todos los elementos en un qobject?

**Comment by cegalleta** [comment]
En Designer debieses poder ver el ObjectName de cada parent (subventana/widget que contiene a los otros widgets), mediante ese nombre podrías referenciar el objeto que quieres utilizar, por otro lado, si tienes muchos elementos encerrados dentro de un parent, tras investigar un poco creo que podrías utilizar el método .findChild o .findChildren de un QObject. Estoy averiguando más información, pero por mientras te dejo esto por si te es útil.

¡Espero que te ayude! Igual por mientras voy a indagar más en el asunto.

**Comment by cegalleta** [comment]
Recuerda que no deberías complicarte tanto, puedes acceder a los widgets con el mismo nombre de designer y conectar las señales normalmente, si te lanza error a nivel de código podrías hacer un push para ver qué estás haciendo e intentar ayudarte mejor :)
