### ISSUE TITLE
Pasajeros de barco carguero

### ISSUE THREAD

**Issue by SofiaP419** [IIC2233/syllabus#229]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado sale que el barco carguero se dedica exclusivamente a llevar mercancía por el canal, con eso yo entendí que no lleva pasajeros y sólo lleva mercancía, pero en el archivo barcos.csv los cargueros si tienen pasajeros. Entonces ¿Los barcos cargueros si pueden llevar pasajeros o nosotros debemos modificar este dato?

**Comment by Juampisaez** [comment]
Hola @SofiaP419 
En el punto 3.1 se menciona que todos los barcos pueden llevar pasajeros, por lo que no debes modificar ese dato.

Espero quede mas claro :)
Quedo atento de igual modo
