### ISSUE TITLE
Duda reposición de gatos en tienda

### ISSUE THREAD

**Issue by francorreaandrades** [IIC2233/Syllabus#229]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!!
En caso de perder contra alguno de los ejercitos enemigos, los gatos disponibles para comprar en tienda se reinician asi como cuando la cantidad de oro vuelve a ser ORO_INICIAL?? O si ya compre los 6 gatos que se instancian en el ejemplo que se da del archivo unidades.txt no hay más opciones de compra hasta salir del programa??

En caso de que se tenga que hacer lo dicho en la 2da opción, si no puedo comprar más gatos y no tengo integrantes en mi ejercito, se pierde automaticamente y se termina al programa??

**Comment by CrisDonosoMaass** [comment]
Hola!

En caso de perder contra un ejercito enemigo pierdes la partida completa, por lo tanto deberías volver al menú inicial como si estuvieses partiendo la partida desde cero. Citando el enunciado: "Si todos tus gatos son eliminados, perderás el juego y deberás volver a comenzar desde la
primera ronda ..... en caso de sufrir una derrota podrás volver a comenzar
desde la primera ronda, donde al igual que en un inicio, contarás con un ejército vacío y el dinero inicial."

Espero que te haya ayudado!
