### ISSUE TITLE
Duda Properties

### ISSUE THREAD

**Issue by Brocoleta** [IIC2233/syllabus#229]
Tengo una property para la posición x y la y del personaje, que se van actualizando a medida que se le suma o resta un valor, pero me di cuenta de que al sumarle un valor por ejemplo a self.x, este valor se almacena y la próxima vez que trato de sumarle un valor a self.x el valor anterior se suma y el actual se almacena y asi sucesivamente , esto se debe a una mala escritura del código o por que las propertys funcionan asi?

**Comment by gatochico** [comment]
Hola! Por lo que entiendo, en tu codigo ocurre un "desfase" al momento de sumar un valor a una property? (eso entiendo cuando te refieres a que "se suma el valor anterior" y que "el actual se almacena", que los efectos aplicados a la property están desafados por una iteración) Si ese es el caso, efectivamente es un error de código. Si todavía tienes ese problema, sube a tu repositorio la última versión de tu código (la que tienes actualmente se cae en la ventana de juego, y no puedo revisar lo de las properties :s ) y podremos ayudarte !
