### ISSUE TITLE
SI CAMBIAN EL ENUNCIADO DEBERIAN AVISAR

### ISSUE THREAD

**Issue by stgoa** [IIC2233/Syllabus#229]
y por lo menos ponerle T02 version 2 para saber que cambió

**Comment by stgoa** [comment]
andar escrutando los issues cerrados para enterarse de los cambios del pdf es contraproducente

**Comment by stgoa** [comment]
falta cambiar el min de adentro del min por un max en la pag 3

**Comment by bamavrakis** [comment]
AMIGO POR QUÉ GRITAS

**Comment by cmgainza** [comment]
cambiaron el enunciado?!

**Comment by fvr1** [comment]
Cambió una fórmula, van a avisar y actualizar el enunciado en un rato.
