### ISSUE TITLE
Orden de Header al guardar

### ISSUE THREAD

**Issue by ceosorio** [IIC2233/syllabus#229]
Hola!

Quería saber si puedo guardar el header del csv de la forma que yo quiera o debo guardarlo en la forma que tiene inicialmente el archivo. No tengo problemas para cargarlo en cualquier orden pero quería saber si al guardar, debo mantenerlo.

**Comment by jaromero6** [comment]
Hola @ceosorio 
Puedes guardar el header del CSV de la forma que estimes conveniente
Ánimo con la entrega!!

**Comment by ceosorio** [comment]
Ah ok! Muchas gracias!
