### ISSUE TITLE
Git Detached Head

### ISSUE THREAD

**Issue by LuceroLu0** [IIC2233/Syllabus#229]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Git Detached Head

Hola. Cuando trato de subir archivos a mi repositorio me aparece este error

![Captura de pantalla 2023-09-28 161305](https://github.com/IIC2233/Syllabus/assets/141850473/281834d6-ada0-46e9-9ef0-fd79d2d79024)

Lo que me impide subir archivos. ¿Cómo puedo arreglarlo?

**Comment by Hernan4444** [comment]
Hola @LuceroLu0 

Puede ser que por "x" motivo ya no estás en la _bracn_ main. Para contextualizar, las branch se pueden ver como diferentes "multiversos" de tu código donde puedes ir trabajando ir luego combinar (_merge_) todo en un solo universo (main). Tal vez se moviste a otra brnach sin darte cuenta (por ejemplo, `git checkout` provoca esto).

Para solucionarlo, lo que más recomiendo es ir a otro directorio y hacer `git clone ....` de tu repositorio, así tienes una versión nueva con todo ya arreglado. Luego tomar los archivos de tu **viejo repositorio**, pegarlos en el **nuevo repositorio** y hacer `add` `commit` y `push`. Finalmente, eliminar la carpeta del **viejo repositorio** para quedarte solamente con el nuevo.

AquÍ: https://github.com/IIC2233/Syllabus/wiki/8.-Comandos-de-Terminal-relevantes-(nuevo) hay algunos comandos que te pueden apoyar en el proceso.

Avísanos como te vá con eso,
Saludos!
