### ISSUE TITLE
Duda sobre la utilización de Messagebox

### ISSUE THREAD

**Issue by gabo1243** [IIC2233/Syllabus#229]
### Duda

Hola, estuve viendo el enunciado y pide que para errores al ingresar el usuario (que exceda máximo o que no sea alfanumérico), se entregue un mensaje de error tipo pop-up. Mi pregunta es: ¿se puede utilizar QMessageBox de QtWidgets junto a sus métodos de exec_(), setWindowTitle() y setText()?

Gracias de antemano

**Comment by Lord-Kelsier** [comment]
Hola @gabo1243, claro puedes ocupar todo lo disponible en el modulo PyQt5
