### ISSUE TITLE
Crear Estructuras de datos especiales

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#229]
Puedo crear estructuras de datos con funciones completamente optimizadas para la resolucion de tares, por ejemplo una clase diccionario que cree un diccionario pero a la vez al instanciarla, esta por ejemplo busque la afinidad entre dos nodos, asumiendo que siempre que ocupe esa estructura me sera util realizar eso

**Comment by monicabelen** [comment]
Claro, puedes crear estructuras de datos personalizadas :)
