### ISSUE TITLE
Material Excepciones Personalizadas

### ISSUE THREAD

**Issue by fabarros** [IIC2233/Syllabus#229]
Hola, no entiendo muy bien cómo funcionan las excepciones personalizadas. 
En el `In[17]` dice (perdón por la pésima indentación):
```
class Excepcion(Exception):
  def __init__(self, a, b):`
     #Sobreescribimos el __init__ para cambiar el ingreso de los parámetros`
     super().__init__("Alguno de los valores {0} o {1} no es entero \n".format(a, b))
```
Se puede cambiar los parámetros de una clase heredada usando `super().__init__`?
Cómo es que los cambia por un String?

**Comment by indonoso** [comment]
0. Arreglé la identación de tu código. Para código en bloques puedes usar tres acentos al revés (``` ) antes y después del código.

1. En el código no están cambiando los parámetros de la clase heredada. Exception solo recibe `*args` y los guarda en la variable `args` del objeto. Lo que hace este código es crear la clase `Excepcion` que recibe dos argumentos e inicializa a su clase base con un parámetro. No entiendo tu pregunta.
