### ISSUE TITLE
Cómo inicializar clase que hereda de varias superclases

### ISSUE THREAD

**Issue by NikiHV** [IIC2233/syllabus#229]
Hola!
Haciendo el ejercicio 1.2 de la semana 3 me surgió la duda. Si tengo una subclase que hereda de varias superclases, ¿cómo inicializo estas superclases (que son varias) dentro del `__init__` de la subclase?
Porque cuando era una relación uno a uno lo hacíamos con `super().__init__(...)`, pero ahora el `super()` ¿cómo sabe a qué superclase referirse?

**Comment by NikiHV** [comment]
Perdón, me di cuenta que sale explicado en el siguiente cuaderno jajajaja pero no puedo eliminar el issue 🤦‍♀

**Comment by JosefaPaz** [comment]
Hola! No te preocupes, solo se cierra la issue y listo, éxito en el estudio!
