### ISSUE TITLE
Turno después de acertar a barco enemigo-T00

### ISSUE THREAD

**Issue by Andres-Pizarro** [IIC2233/syllabus#229]
Hola! tengo una duda acerca de a qué menú se debe acceder después de acertar a un barco enemigo. En el enunciado dice que tiene la oportunidad de disparar de nuevo, lo cual da a entender que se debe dirigir al menú de bombas nuevamente no? Es decir, selecciona bomba y después ataca, sin las opciones de Salir o Rendirse.

**Comment by DCCollao** [comment]
Hola @Andres-Pizarro! Te recomiendo revisar la issue #184. Si luego de eso quedas con dudas, hazla por favor en los comentarios de esa misma issue, para centralizar las dudas.

**Comment by Andres-Pizarro** [comment]
Resuelto! Gracias!
