### ISSUE TITLE
duda sobre codigo 2 

### ISSUE THREAD

**Issue by LunaGarces** [IIC2233/Syllabus#229]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Duda

buenas, tengo una duda sobre un error que me arroja mi programa, pero no lo arroja siempre, en donde tengo creado torneo (torneo.py) en simular torneo, mi codigo esta dividido en 3 partes (las tres partes pedidas en la tarea(#P3 ocurrenci evento)) que vendría siendo la linea 93 aprox por alguna razón algunaz veces mi código se frena en esa parte, ya intenté hacer debug y lo único que logre ver es que en esta parte

            check = False
            if True: #true lo estaba usando para que siempre pasara y sea mas facial el debug
                if True: 
                    check = True 
                    self.evento = 'Derrumbe' 
                    self.metros_cavados -= p.METROS_PERDIDOS_DERRUMBE

por alguna razón se 'devuelve' al check = False y no estoy implementando un while en esa parte

**Comment by Hernan4444** [comment]
Hola @LunaGarces 

Viendo el código, me percaté de 2 detalles:
1. Que esa parte de verificar evento la tienes dentro de `for` de los excavadores, es decir, por cada excavador que cava, estás haciendo el checkeo de los eventos. Esto hace que se ejecute todo ese código una vez por cada excavador que tengas, pero en el enunciado se explica que la ocurrencia de un evento pasa 1 vez al día. 
2. Ojo con **qué es `self.arena_en_juego` ¿es un string? ¿es un objeto?** Veo que tus `whiles` usan ese atributo, pero no es consistente el cómo lo estás ocupando. Revisa qué hay de diferente entre tus `print()`y los `while` que tienes en esa parte del código.

Saludosヾ(＾-＾)ノ

ps: Finalmente recomiendo revisar el código que subimos de Sala de Ayuda para la T1 sobre probabilidades de eventos, hay ciertas diferencia entre lo que haces tu y cómo lo enseñamos en la sala de ayuda.

**Comment by LunaGarces** [comment]
Graciassss

Saludos cordiales

On 22-04-2023, at 13:04, Hernan Valdivieso ***@***.***> wrote:

﻿

Hola @LunaGarces<https://github.com/LunaGarces>

Viendo el código, me percaté de 2 detalles:

  1.  Que esa parte de verificar evento la tienes dentro de for de los excavadores, es decir, por cada excavador que cava, estás haciendo el checkeo de los eventos. Esto hace que se ejecute todo ese código una vez por cada excavador que tengas, pero en el enunciado se explica que la ocurrencia de un evento pasa 1 vez al día.
  2.  Ojo con qué es self.arena_en_juego ¿es un string? ¿es un objeto? Veo que tus whiles usan ese atributo, pero no es consistente el cómo lo estás ocupando. Revisa qué hay de diferente entre tus print()y los while que tienes en esa parte del código.

Saludosヾ(＾-＾)ノ

ps: Finalmente recomiendo revisar el código que subimos de Sala de Ayuda para la T1 sobre probabilidades de eventos, hay ciertas diferencia entre lo que haces tu y cómo lo enseñamos en la sala de ayuda.
