### ISSUE TITLE
Cargar imagen sobre Qrect y colisiones

### ISSUE THREAD

**Issue by Francisco-Aguilera-xd** [IIC2233/Syllabus#229]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola! Quería preguntar si hay alguna forma cargar una imagen en un qrect. Pregunto porque en los contenidos por lo general cargabamos imagenes mediante el método ```setPixmap``` en un qlabel, pero este método al parecer no existe para los qrect. Mi duda surgió por el tema de hacer las colisiones dentro de la tarea y se nos sugiere hacer uso de un método de qrect para hacerlo, pero no sé como hacer lo de antes.

**Comment by tamyhan** [comment]
Hola @Francisco-Aguilera-xd ! Los QLabel tienen como atributo un QRect con su tamaño y posición, que puedes usar para comprobar las colisiones. Para obtener ese QRect te recomiendo investigar sobre la clase de los QWidget :)

**Comment by jsilvalavin** [comment]
Hola! Tengo una duda relacionada a esto... tengo un QLabel con el sapito que se mueve con QLabel.move(x,y), pero cuando trato de sacar su qlabel (con QLabel.qrect() ) me aparece que este no cambia a medida que se mueve, como soluciono esto?
Por otro lado, su "hitbox" (es decir el rectangulo que detecta intersecciones) es gigante con respecto al QLabel y parece colisionar mucho antes que los sprites parezcan tocarse, como arreglo esto? gracias :)

**Comment by tamyhan** [comment]
Hola @jsilvalavin ! Quizás tienes mal definidas las dimensiones del QRect. Ojo que el atributo del QLabel para obtener el QRect es rect() no qrect(). Además, con respecto a que el rectángulo que detecta las colisiones es más grande que tu QLabel podría deberse a que no estás ajustando el tamaño de la imagen para que ocupe todo el tamaño del label, lo que hace que tu imagen en la interfaz se vea más pequeña del tamaño real del label. Para arreglar eso último investiga sobre el atributo de los labels que se encarga de ajustar la imagen a ellos.

**Comment by jsilvalavin** [comment]
gracias! @tamyhan
