### ISSUE TITLE
Autoenvío

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#23]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

No está mencionado en ninguna parte y, *supongo* que no es un problema no hacerlo, pero hay que limitar el envío de empaques de un usuario a sí mismo?

**Comment by catalina-arcila** [comment]
Hola @MaxAl100 al no aparecer en el enunciado no es _obligatorio_ hacer esa restricción. Sin embargo, tendría todo el sentido del mundo hacerlo, por lo que lo recomiendo.
Recuerda incluir en el _README_ cualquier restricción externa a lo dicho en el enunciado!

**Comment by MaxAl100** [comment]
> Hola @MaxAl100 al no aparecer en el enunciado no es _obligatorio_ hacer esa restricción. Sin embargo, tendría todo el sentido del mundo hacerlo, por lo que lo recomiendo. Recuerda incluir en el _README_ cualquier restricción externa a lo dicho en el enunciado!

Yap, muchas gracias! Esto responde mis dudas :)
