### ISSUE TITLE
Duda con el .gitignore

### ISSUE THREAD

**Issue by covial** [IIC2233/syllabus#23]
En el enunciado nos recomiendan incluir los archivos entregados (parametros.py y tablero.py) en el .gitignore, dado que no son pertinentes para el funcionamiento de nuestra tarea. Pero obviamente, sí lo son, dado que se importan sus funciones y variables en la ejecución del programa. ¿Qué hago, los subo de todos modos a mi repositorio? De no hacerlo, al importar los archivos creo que Python arrojaría un error.

**Comment by gatochico** [comment]
Hola! 

Efectivamente, queremos que **no subas los archivos parametros.py y tablero.py** a tu repositorio privado. Como son archivos que se entregaron en conjunto con el enunciado, ya los tenemos al momento de corregir y los añadiremos a tu tarea para que esta funcione correctamente. 

Saludos y éxito!

**Comment by covial** [comment]
Ok, muchas gracias!!
