### ISSUE TITLE
Cuenta GitHub

### ISSUE THREAD

**Issue by ghost** [IIC2233/Syllabus#23]
Hola, Por extrañas circunstancias borre mi cuenta de GitHub y perdí mi repositorio, como puedo solucionar este problema, ya que trate de crear la cuenta de nuevo pero no puedo acceder a nada

**Comment by sebacruzd** [comment]
Hola, si te refieres a que quieres recuperar archivos o repositorios, esto no es posible.
Esto sale en la [página oficial](https://help.github.com/articles/deleting-your-user-account/) de github, por lo que no hay manera de recuperarlo. Deberás volver a registrar un nuevo repo. 
![imagen](https://user-images.githubusercontent.com/14894992/29149835-a1846628-7d44-11e7-8f20-f7889b559d40.png)

**Comment by flobarrios** [comment]
A penas registres el nuevo repo, por favor mándame un correo con tu nuevo user
