### ISSUE TITLE
Aclaración acerca de posibles edificaciones

### ISSUE THREAD

**Issue by kenzoak** [IIC2233/Syllabus#23]
En el punto 5.4 se especifica que se pueden construir 2 tipos de edificio, el cuartel y la torre de defensa, pero en el punto 6.4.1 se habla también de la construcción de un escudo.  Son sólo 2 edificios?
Gracias.

**Comment by Hernan4444** [comment]
Si, son solo 2 edificios. El escudo se eliminó, cualquier referencia a él debe ser ignorada 🙈.
Saludos!

**Comment by kenzoak** [comment]
Gracias!!

**Comment by fgbruna** [comment]
@kenzoak no cierres las issues apenas te las responden, **especialmente** si son dudas sobre las tareas, los ayudantes nos preocuparemos de cerrarlas cuando sea pertinente.
