### ISSUE TITLE
Duda sobre manera general de hacer ejercicio 3

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#23]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda sobre metodo del ejercicio 3

[Hola, estaba intentando hacer el ejercicio propuesto 3 y me surgió una duda, el método que se pide implementar depende mucho desde que torre y a que torre se mueve un disco, específicamente, me causa conflicto como quitar y añadir los discos a las torres, ya que a priori solo se me ocurre usar ifs para detectar cada caso, (a que torre quitar y a cual poner el disco) pero intuyo que esa no es una buena manera (busque un poco sobre el tema, pero encontré cosas que me parece que escapan del curso)]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by DomingoCarvajal** [comment]
Hola Pablo!

Tienes razón. Generalmente no es una buena idea usar "ifs" para decidir cada caso si es que se puede generalizar el proceso. Una manera de hacerlo es crear una estructura de datos (lista, tupla, etc) que contenga a cada pilar de la Torre de Hanoi, y que se puede referenciar a cada uno de ellos con el argumento que reciba la función, que en este caso es el número de cada pilar.
