### ISSUE TITLE
Problema para la instalación de Requests

### ISSUE THREAD

**Issue by matthycc** [IIC2233/Syllabus#23]
- Sistema Operativo: Windows 11
- Programa a instalar: Librería Requests en Ubuntu

- Foto del error:
![image](https://github.com/IIC2233/Syllabus/assets/141888897/ad102bc0-7313-491f-9fce-f94f6569dbab)

- Descripción del problema: No me deja instalar la librería y me sale que tengo problemas con la versión.

**Comment by lily416** [comment]
Hola @matthycc y @espeescobar 

Espero que se encuentres bien 😄. Con respecto a sus dudas:
* @matthycc: Según lo que te aparece en la consola, aparentemente la librería `requests` se instalo correctamente. Para verificar lo anterior, pasa al [siguiente paso de la Wiki](https://github.com/IIC2233/Syllabus/wiki/3.-Software-Obligatorio#configuración-de-requests) para así comprobar si `requests` se instalo correctamente o no. Si no funciona correctamente, vuelve a comentar esta issue.

* @espeescobar: Tu error se debe a que estás instalando la librería equivocada (`request` sin `s` al final), para instalar la librería prueba el siguiente comando: `python3 -m pip install requests`

Saludos y espero que logren solucionar sus respectivos errores 👋🐢
