### ISSUE TITLE
Utilización de módulos/archivos que no se modifican.

### ISSUE THREAD

**Issue by BoPe3p** [IIC2233/Syllabus#23]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Hola, me ocurre que no sé en general el orden o cómo utilizar los módulos y archivos que nos entregan para realiazar las tareas/actividades. Por ejemplo, en la AC0 tenemos que leer el archivo "items.dcc" o en la AC1 utilizar "ejemplo.chan". Estaba haciendo las actividades desde el repositorio personal, pero claramente no puedo leer el archivo ya que se encuentra en 'Syllabus'. ¿Tenemos que mover "arrastrando" estos archivos a nuestro repositorio y después entregar nuestro trabajo devolviendo los archivos o tenemos que hacer otra cosa? Igualmente, aunque copié el archivo "items.dcc" en mi repo, igualmente me sale el error:
"
FileNotFoundError: [Errno 2] No such file or directory: 'items.dcc' (Estoy en la carpeta de Actividades)
"
<hr style="border-top: 5px; margin-top: 1px; margin-bottom: 1px"></hr>

Aprovecho para decir que me ocurre lo mismo con los módulos, me sale "module not found" cuando en el testeo de la AC0 se hace el import main.

Gracias de Antemano!!

**Comment by Agusrush21** [comment]
mira aun no estoy informado al 100% de como funciona exactamente, pero por solo prueba y error te puedo decir que si quieres ocupar un modulo tiene que estar al mismo nivel en la carpeta donde tienes tu archivo main. Por otra parte si te complica lo anterior seria usar la ruta de la carpeta que necesitas e importar el modulo.
Con los archivos termina siendo lo mismo

acá un link a un video donde lo explican mejor la parte de los módulos:
[https://youtu.be/hWbD_6xhYe0?si=EjFiwswK8N-rZm7m](url)

**Comment by Hernan4444** [comment]
Hola @BoPe3p 

Para tener mejor claridad del _pipeline_:
1. Desde el Syllabus, deben copiar todos los archivos de una actividada en su repo privado. Es decir, si AC1 tiene 3 archivos y 2 carpetas, entonces todo eso (3 archivos y 2 carpetas) deben ir a la carpeta AC1 de tu repo privado.
2. Completar el archivo que les pedimos modificar en el repositorio privado. 
3. **Siempre** tener la terminal posicionada dentro de la carpeta de la AC que estás desarrollando. No en "Actividades" o en tu repositorio, sino en "AC0", "AC1", etc.
4. Subir (con git) al menos el archivo que se pide entregar. Los otros archivos, para una actividad, puedes (1) no subirlos, (2) ignorarlos usando un `.gitignore` o (3) subirlos. Los que nos interesa es que el archivo que dice "Entregar" si esté subido y funcionando correctamente. Aquí tampoco hay problemas con subirlo, no es lo ideal pero no se penaliza (en actividades).

Sobre el punto (4), de todas formas recomiendo hacer la opción 2, para practicar siempre el uso de `.gitignore` que en las tareas ya es un requisito su investigación y uso, así que mejor practicar desde antes.

---

Respecto a tu error, lo que puede pasar es que `main.py` está en la carpeta `AC0` y los archivos pedidos están dentro de `AC0/utils`. Por lo tanto, ahí las rutas de paths y los imports son distintas. Recomiendo revisar los contenidos de la semana 2 (2-modularización.ipynb y 3-paths.ipynb). Y darle un ojo a la siguiente issue donde dieron un ejemplo de cómo importar un archivo que está dentro de una carpeta.

* #12

Finalmente, respecto al video dado por @Agusrush21 ¡¡está muy bueno!!, solo tengan ojo que en una parte se hace:

- `import *` y esto es una muy mala práctica que es penalizada en el curso. Para que no la hagan 🙅.
- `sys.path.append` y la librería `sys.path` está prohibida, por lo tanto no lo intenten ocupar o tendrán una penalización.


Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ

**Comment by TomyGomez19** [comment]
Hola, ya copié y pegué la carpeta utils y entities.py en mi repositorio privado. Esto lo hice directamente desde VSC, además estoy empleando correctamente el orden del path usando el módulo **os**, al momento de ejecutar el código me sigue saliendo _FileNotFoundError_ :( 
En mi repositorio privado (visto a través de VSC), veo que la carpeta con el nombre de mi repositorio y las carpetas que copié desde _Syllabus_ me salen con letra verde y con una U que por lo visto significa _Untracked_ ¿Será esto lo que no me permite aún seguir el path y poder trabajar con los archivos? :(

**Comment by MaxAl100** [comment]
Hola! Eso de significa que todavía no consideras ese archivo para temas de got (ya sea que no hayas hecho add o commit de estos archivos). 
El problema que probablemente tienes es que  la ruta relativa no está siendo bien identificada o algo del estilo.
Mi recomendación es que desde visual studio code/consola abras solo la carpeta en que vas a trabajar, esta quiere decir que abras la carpeta de AC0 o AC1 o T1, etc...
Desde dentro de VSC puedes hacer esto apretando en file(archivo) y luego seleccionar open folder (abrir carpeta), seleccionando luego la carpeta en que quieres trabajar. Esto te permitirá tener todos los archivos a mano y puede que te resuelva el problema de las rutas.

Avísame si te funciona o no, para poder seguir ayudando en caso de ser necesario

**Comment by TomyGomez19** [comment]
Me funciono! Muchas graciass c:
