### ISSUE TITLE
Buena o mala practica?

### ISSUE THREAD

**Issue by jnlarrain** [IIC2233/Syllabus#23]
¿Es una mala practica abrir un archivo.txt dentro de una funcion y cerrarlo en la misma?¿o debo abrirlo al principio del programa y cerrarlo al final?

**Comment by FernandoPieressa** [comment]
No es mala practica, de hecho dejar abierto siempre el archivo no es recomendable, intenta siempre cerrar el archivo después de usarlo o de guardar la información que te interesa dentro de tu programa .

Saludos!

**Comment by jnlarrain** [comment]
Gracias!!
