### ISSUE TITLE
Duda creación de nuevos archivos T0

### ISSUE THREAD

**Issue by panchouc** [IIC2233/Syllabus#23]
¡Hola!.
Tengo una duda respecto si existe algún impedimento o restricción/prohibición para la creación de archivos respecto a la tarea 0. Por ejemplo, si encuentro apropiado el organizar mi código en una carpeta `src` y ahí poner mi código, y dentro de esta misma carpeta crear quizás subdirectorios junto a distintos archivos `.py` que yo pueda crear, o también, por ejemplo, crear un archivo `main.py` donde ponga solamente la ejecución del flujo de mi programa. De antemano gracias por la respuesta, saludos.

**Comment by Juampisaez** [comment]
Holaa @panchouc 
No existe ningun impedimento en este caso, puedes crear esta carpeta y poner tu código ahí, recuerda explicar esto en tu `Readme`.
Como consejo, te recomiendo modularizar según lo estimes necesario, tal vez crear muchas carpetas o archivos pueda no ser tan necesario 👀.

Quedo atento a cualquier duda :)
