### ISSUE TITLE
Concepto de abstracción

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#23]
Hola!!

Cuando se habla de abstracción o niveles de abstracción, a qué se refiere exactamente? Buscando en Internet entendí que en la programación orientada a objetos se deben enfatizar ciertos atributos a elección del observador o programador.
Quería preguntar si el concepto de abstracción se refiere a esto o si se refiere a algo más detallado.

Muchísimas gracias :)

**Comment by Juampisaez** [comment]
Hola, efectivamente la abstracción se utiliza en la programación orientada a objetos, de hecho en un par de semanas aparecerán en los contenidos del curso. Igualmente para responder a tu pregunta, en programación existe lo que llamamos clases abstractas y que en general usamos solamente como parte del modelamiento de otras clases, es decir, una clase que sera heredada por una subclase.
Un ejemplo podria ser una clase *Ingeniero* con varios metodos abstractos (las funcionalidades cambian segun la clase que la herede). Una clase que heredaria la clase *Ingeniero* podria ser la subclase *Ingeniero_en_computación* y que poseeria los metodos abstractos y no abstractos de *Ingeniero* y tambien sus propios metodos.
Espero esto te aclare un poco mas, cualquier cosa quedo atento.

**Comment by Juampisaez** [comment]
Puede que cuando leíste niveles de abstracción, te hayas referido a los niveles que poseen los distintos lenguajes de programación como por ejemplo python (lenguaje más abstracto) o assembly (lenguaje muy poco abstracto). Llevándolo a la programación orientada a objetos, esto solo se encuentran en lenguajes abstractos (lenguajes de alto nivel) como *Java*, *C#*, *Python*, *JavaScript*. En general el concepto de abstracción puede considerarse como tomar las características comunes de sistemas u objetos, y de alguna forma generalizar o modelar. Los lenguajes de programación tienen distintos tipos de abstracción. 
Si quieres mas detalles sobre el tema te dejo un [link](https://en.m.wikipedia.org/wiki/Abstraction_(computer_science)) donde puedes aprender mas sobre el tema.
