### ISSUE TITLE
Cómo heredar una property y setter de una superclase o clase abstracta 

### ISSUE THREAD

**Issue by cncosta** [IIC2233/syllabus#23]
realizando el ejemplo de la ayudantía de hoy y probando mi código, veo que la property que le pongo a vida en la clase abstracta no se hereda, como hago para solucionar este error.
adjunto fotos de mi codigo.
el error es que al realizar un ataque deja la vida en valores negativo 

![Captura de pantalla 2019-03-19 a la(s) 23 04 36](https://user-images.githubusercontent.com/42576884/54654063-b3e49880-4a9b-11e9-8af4-f08f7dbe8690.png)

![Captura de pantalla 2019-03-19 a la(s) 23 04 55](https://user-images.githubusercontent.com/42576884/54654013-85ff5400-4a9b-11e9-9cf5-31a071398f94.png)

**Comment by naquiroz** [comment]
Ojo 👀!, la _property_ si se hereda, lo que pasa es que en el ejemplo se usó el atributo privado (`self._vida`, notar el guión al principio), lo cual, ahora que lo veo, no tiene mucho sentido. Si le borras el guión, debería pasar por la property y no el atributo.

Saludos ! ✌️
