### ISSUE TITLE
Duda sober método consumir()

### ISSUE THREAD

**Issue by golosinas** [IIC2233/Syllabus#230]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Según el enunciado, el funcionamiento de consumir en la sección de los excavadores consiste en actualizar los atributos del excavador según los atributos que posee el consumible, y este proceso ocurre _dentro del método._ Mi problema es que estoy usando properties, y al sumarle el valor correspondiente al atributo, el código no entra al setter y el valor actualizado se escapa del rango en la que debiese estar.

Se me ocurre cómo actualizar el atributo de forma correcta, pero la actualización del atributo no ocurriría dentro del método sino afuera. ¿Estaría permitido esto?

Saludos y gracias de antemano. 😃

**Comment by Benjeeeh** [comment]
Hola! 
Es necesario que en **consumir** se utilice el consumible y de aquí se extraiga la información para modificar los parámetros. Según lo que describes, no habría problema en este caso de usar properties en esos casos, ya que este método podría llamar a las funciones setter y darles los valores a modificar y así no se salgan de los límites. Revisando tu código, me percaté de que estás asignando mal los valores debido a que estás modificando los valores desde consumir (usando +=), siendo que desde aquí se debería entregar el valor solamente (estás bien encaminado, pero hay un símbolo de más en tu operación).

Éxito con la tarea, cualquier duda me dices.

**Comment by tomastrivino** [comment]
Hola! @Benjeeeh , me confundió lo último que dijiste al referirte a "Revisando tu código, me percaté de que estás asignando mal los valores debido a que estás modificando los valores desde consumir (...)". ¿Podrías explicarlo nuevamente? Lo que pasa es que mi método ```consumir()``` de un excavador recibe una instancia de la ```Consumible```, extrae los datos de la misma y luego lo agrega al self.energia + = ... etc etc. El código está en [mi repositorio](https://github.com/IIC2233/tomastrivino-iic2233-2023-1/blob/main/Tareas/T1/excavadores.py). Agradecería una aclaración para ver si tengo que cambiar algo o no. Gracias :)

**Comment by Benjeeeh** [comment]
Hola @tomastrivino

Lo que le mencioné a la persona anterior era referente al problema de que a pesar de realizar las modificaciones en consumir, las properties no funcionaban y no hacían la función de mantener el valor dentro de los rangos especificados.
Revisé tu código y tienes el mismo problema, ya que estás **realizando la operación (+=) directamente desde el método consumir y no dándole el valor al setter de la property**, lo que ocasione que si se añadan los valores del consumible a los atributos correspondientes, ya que si se puede acceder directamente ya que el método está dentro de la clase pero que exista la posibilidad de salirse de los rangos. Te recomiendo también revisar los mismos ejemplos que le mencioné a tu compañero y ver bien en lo que estás fallando (fijate bien en el operador que estás usando). Estás bien encaminado, pero no le estás dando el valor a la property.

Estaré atento a cualquier duda, éxito!

**Comment by tomastrivino** [comment]
Hola @Benjeeeh , resulta que estoy utilizando atributos privados. Es decir, mi clase tiene un atributo ```self.__energia```y una property ```energia```, que modifica la primera variable mencionada. Aun no encuentro el error ni lo he visto reflejado en las simulaciones de mi código :c. En ```consumir()```, la operación ***+=*** es llamada sobre ```self.energia```, que al final es mi property. ¿No sería eso darle el valor al setter de la property?

**Comment by Benjeeeh** [comment]
@tomastrivino Sí, perdón, revisé bien tu código y funciona correctamente, no vi bien el detalle y pensé que era igual o similar al caso anterior.

Saludos.

**Comment by tomastrivino** [comment]
Gracias!

**Comment by golosinas** [comment]
Hola @Benjeeeh ! Intenté reescribir la manera en que estaba fijando el nuevo valor en el setter, pero sigo teniendo el mismo problema. Al actualizar los atributos de consumir(), aún se me salen algunos atributos del rango especificado. ): Lo he intentado de distintas formas, y no lo logro solucionar.

**Comment by Benjeeeh** [comment]
Hola @golosinas 
Revisé tu código y sigues bypasseando las properties, por eso sigue ocurriendo de que se salgan de los atributos deseados. Tu método se encuentra bien, pero desde **consumir** sigues modificando directamente los atributos privados, y aquí es donde radica el problema, ya que si le sumas directamente al atributo privado (__fuerza, por ejemplo), se aplica directamente la suma y no pasa por la property respectiva (que es fuerza, sin __), así que asegúrate de darle el valor a la property y no al atributo directamente (solo tienes que borrar algo, estás muy cerca!!)

Avísame cualquier duda.
