### ISSUE TITLE
Consulta musica

### ISSUE THREAD

**Issue by diegocostares** [IIC2233/Syllabus#230]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, tengo unas cuantas dudas sobre este apartado...
1. Quería saber si puedo subir una canción distinta para la entrega, pues tengo una de 8 bits muy buena 🤖 .
2. ¿Es posible crear una especie de lista de reproducción para que cuando termine una comience otra música distinta?, actualmente estoy ejecutando la música con QSound y también sé hacerlo con QSoundEffect, pero lamentablemente QMediaPlayer no me está funcionando en mac. 
3. ¿hay una forma de poner un loop infinito en QSound?, desde QMediaPlayer pude sin ningun problema, pero la documentación del primero no la entendí muy bien
4. Cuando el enunciado dice "reiniciándose cada vez que se cambie de ventana" ¿significa que abrir el ranking (que se sobre pone al menu de inicio) tambien se tiene que reiniciar?

**Comment by catalinacarter** [comment]
Hola @diegocostares! Es mejor si sigues al pie de la letra el enunciado, es decir "deberás utilizar como música el archivo WAV entregado junto al enunciado" :) 

En QSound si es posible poner loop infinito. Te dejo este link que te puede servir donde se muestra un método para poner loops y como hacer que este sea infinito.  https://het.as.utexas.edu/HET/Software/PyQt/qsound.html#QSound
A pesar de que es para la librería PyQt4, también sirve para PyQt5, así que no te preocupes por eso. 

Respecto al reinicio de la música, efectivamente debe reiniciarse cada vez que se cambie de ventana. El ranking es parte de la Ventana Ranking, por lo tanto también se debe reiniciar al abrir esa ventana.
