### ISSUE TITLE
Elección valores en parametros.py

### ISSUE THREAD

**Issue by mVal919** [IIC2233/Syllabus#230]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, estaba leyendo el enunciado, y no me quedo clara una cosa.
Los parámetros que se muestran a lo largo del pdf ¿hay que elegirlos nosotros? O los dan a lo largo del enunciado y hay que deducirlos.
Eso, muchas gracias.

**Comment by diegoftpxd** [comment]
Hola!, los valores de los parametros que se encuentran en el enunciado **tienen que ser elegidos por ustedes**, ten en cuenta que deben tener sentido para el juego. Con esto me refiero a que DURACION no debe ser un número negativo debido a que es la cantidad de días de juego.

**Comment by mVal919** [comment]
Ya, buena buena
Muchas gracias
