### ISSUE TITLE
Con que debemos compara los cambios de velocidades?

### ISSUE THREAD

**Issue by Alonsinho1** [IIC2233/syllabus#230]
Hola

En el enunciado se señala que después de cada vuelta le tenemos que indicar al usuario cambios en su velocidad. Sin embargo, a que se refiere esto, a la velocidad intencional comparado a la real. O a la velocidad real de la vuelta anterior con la actual. Y si es asi en la primera vuelta su velocidad anterior a esta, seria su velocidad base?

Muchas gracias

**Comment by tomcan127** [comment]
Hola
Debes mostrar si la velocidad se vio afectada por algún objeto u obstáculo en la ultima vuelta.
![image](https://user-images.githubusercontent.com/44327650/64715806-84857600-d497-11e9-9518-7ea7337cc5be.png)
P.D: recordar que esto es solo un ejemplo, si quieres mostrar cuanto cambio (en porcentaje o valor), queda a tu criterio.

**Comment by muovalle** [comment]
No entiendo, en la issue #227 me respondieron que se refería a si el vehiculo tuvo daño o no.

**Comment by tomcan127** [comment]
Se refiere a que si el vehiculo se encontro con algun objetgo en la pista, que haya afectado alguna de sus propiedades.

**Comment by muovalle** [comment]
Perdón, sigo sin entender. Pero por lo que entiendo la única propiedad que se puede ver afectada es el chasis por la formula de "daño al vehículo", entonces se refiere a si hubo daño al vehículo?

**Comment by tomcan127** [comment]
Correcto, se refiere al daño al vehículo.
Pero tambien puedes agregar como llos efecto de la pista afectan la velocidad

**Comment by muovalle** [comment]
ok gracias!

**Comment by Alonsinho1** [comment]
Hola para aclarar

Si el vehiculo se encontro con algun obstaculo ( es decir si recibio daño) tengo que imprimir.

“Tu velocidad se vio afectada”

Y si es que no

“Tu velocidad no se vio afectada”

Eso nomas?
