### ISSUE TITLE
Numero de piezas

### ISSUE THREAD

**Issue by NoemiCC** [IIC2233/Syllabus#230]
Hola,
Se que cuando se ejecuta *csv_generator.py* se crea el archivo *pieces.csv*, donde sale el numero de piezas (en total son como 234) pero no entendí si hay que repartir esas piezas entre los 2 usuarios, osea darles 117 a cada uno, o si se le dan 234 a cada uno.
Gracias.

**Comment by Arcoirisky** [comment]
Hola! :DD

Esa es la cantidad de piezas en total del juego! 
Tu decides cómo quieres repartirlas O:

**Comment by movaldivia** [comment]
@Arcoirisky no me quedó muy claro. Pueden haber más piezas de las que necesita el programa, entonces las reparto entre los dos jugadores, y luego, en cada turno, le doy al jugador correspondiente una pieza al azar de su respectivo "reparto" es correcto?
