### ISSUE TITLE
Haiti y Republica Dominicana [Imposible ganar]

### ISSUE THREAD

**Issue by ignacioaraya1995** [IIC2233/Syllabus#230]
Haiti solo tiene frontera terrestre con Republica Dominicana.
Ninguno de ellos tiene aeropuertos.

Si comienzo en uno de esos 2 países, el virus no se propagará a ningún otro país.
Si comienzo en otro pais, el virus nunca llegará a ellos.

Por lo tanto es impone ganar

**Comment by FernandoPieressa** [comment]
Hola!

Esos países están preparados para sobrevivir al parecer.

Puedes borrarlos si es que quieres, o sino ponerle manualmente un aeropuerto o como gustes para arreglar este problema. La verdad es que no es muy relevante a lo que intentamos evaluar por lo tanto puedes hacer supuestos de eso.

Saludos!

**Comment by gbordoni** [comment]
Yo no conte a esos paises porque no aparecen en el `population.csv` .
