### ISSUE TITLE
Esperanza de ganar

### ISSUE THREAD

**Issue by fabarros** [IIC2233/Syllabus#230]
Hola, para calcular la esperanza de ganar se usa la afinidad promedio del **grafo de afinidad del equipo**. Se menciona que se calcula el _promedio de las afinidades de un jugador_ con sus vecinos en el grafo de afinidad del equipo, ahora, obviamente aquí todos están relacionados con todos, cierto? Pregunto porque el ejemplo que sale en el enunciado es un grafo donde no están todos los jugadores relacionados, sin embargo, al calcular las afinidades del grafo de los 5501 jugadores, yo tengo afinidades para todos los posibles pares de jugadores, sólo que quizás algunos sean cero.

**Comment by yoavnavon** [comment]
Hola! Efectivamente se calcula solo con los vecinos, es decir, se calcula la afinidad (ya sea por jugadores conocidos o no relacionados) de los 3 o 4 vecinos que tenga un jugador, y se saca el promedio de estos valores. Espero se haya entendido!

**Comment by pcseisdedos** [comment]
De que forma determino cuales son los jugadores vecinos? porque tal como dice @fabarros se puede determinar la afinidad para cualquier par de jugadores, entonces todos podrían ser vecinos.
En la figura 4 se calcula la afinidad del equipo considerando como vecinos a los que están al lado del jugador 1 según las posiciones dentro del equipo, sin embargo en la sección 4.3.1 se establece que el orden de la interfaz es irrelevante.

**Comment by yoavnavon** [comment]
Creo que hay un problema en el enunciado, pero la posición si importa. Es decir, solo se calcula la afinidad con los 2 o 3 jugadores que estén al lado.

**Comment by pcseisdedos** [comment]
De ser así, cómo accedo a la posición de la interfaz?

**Comment by Cschavez** [comment]
hola! tengo la misma duda que @pcseisdedos. Además no entiendo como la afinidad entre dos jugadores puede ser 0.3 o 0.76, para obtener esos números tengo que calcular la afinidad con el grafo de 200 jugadores utilizando el algoritmo para calcular "la mayor afinidad" ? Muchas gracias!

**Comment by yoavnavon** [comment]
@pcseisdedos Si notas en Demo.py, al apretar los jugadores de la banca, estos siempre se ponen en el mismo orden, con esto, puedes saber que jugador está en cada posicion, y al llamar a la funcion `cambio_jugador`, puedes ir intercambiándolos.

@Cschavez Para obtener las afinidades entre vecinos, las calculas según el grafo con todos los jugadores (el de 5000), con el algoritmo para "mayor afinidad".

**Comment by sicorrecto** [comment]
@yoavnavon Entonces por "vecino" entendemos los unidos por linea roja en la figura 4 del enunciado?

**Comment by yoavnavon** [comment]
@sicorrecto Exactamente.
