### ISSUE TITLE
Posición inicio personaje

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#230]
En qué posición debe empezar el personaje?

**Comment by gatochico** [comment]
Hola! Queda a tu discreción el donde empieza el personaje, siempre y cuando sea en un lugar válido (no sobre obstáculos, por ejemplo) :cat: Saludos!

**Comment by Dnpoblete** [comment]
Hola, puede ser que inicie en "S" al igual que los enemigos?, es que no dice en el enunciado si el personaje puede pasar por ahí o no.

**Comment by gatochico** [comment]
Si, puede iniciar en "S"!
