### ISSUE TITLE
Coordenadas de las piezas

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2233/Syllabus#231]
Hola! Em mi pyqt5 no está funcionando bien aún así que no he visto la interfaz.
Cómo son las coordenadas de las piezas? No entiendo el panal de abejas ._. y quiero partir trabajando en algo. 
(i,  j) i es la fila en zigzag...? y j la columna? 
<img width="533" alt="ejemplo numeracion tamblero" src="https://user-images.githubusercontent.com/26146191/30076582-b9ab7a14-924f-11e7-84c5-26f67c6a8cc0.png">

Gracias

**Comment by MrEarle** [comment]
Por lo que he visto, es tal cual como lo pones.

**Comment by Arcoirisky** [comment]
Es exactamente como lo dices! (Aunque la imagen esté dada vuelta sigue el mismo principio 😅)

![img_20170906_080218](https://user-images.githubusercontent.com/26121402/30108736-d6d93f9c-92d9-11e7-8fcf-714417bd190d.jpg)

**Comment by ChayoPerez** [comment]
Bkn, gracias! :)
