### ISSUE TITLE
Aclaración sobre movimiento fluido de la rana 

### ISSUE THREAD

**Issue by Francisco-Aguilera-xd** [IIC2233/Syllabus#231]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Cuando se pide un movimiento "fluido" de la rana, se refiere a que cuando se presiona una tecla del movimiento cambien **un frame** de esa dirección o que se muestre una secuencia de frames cada vez que se presione? o sea, se muestre el frame 1,2 y 3 cada vez que se presione. Pregunto porque si es esto último, volvería el movimiento normal "discreto" mientras que tenía entendido que solo los saltos son los movimientos discretos.

**Comment by mmunoz12** [comment]
Hola @Francisco-Aguilera-xd!👋🏻

El movimiento animado consiste en que Froggy deberá **cambiar su sprite (sólo una vez) cada vez que se presione una tecla**, la cual debe corresponder con la dirección dada según esta. De esta manera, se deberán usar las 3 sprites que se dieron para cada una de las direcciones, idealmente siguiendo el orden “dirección_1”, “dirección_2” y “dirección_3” y así sucesivamente (puedes aplicar el orden inverso si deseas). Por ejemplo, si presiono la tecla D, se deberá cambiar el sprite a “right_1” y si vuelvo a presionar D, se cambiará a “right_2”, y así sucesivamente. 

Espero haber resolvido tu duda, quedo atenta a cualquier cosa! Saludos!☺️

**Comment by Francisco-Aguilera-xd** [comment]
Ahhh ya perfecto. Muchas gracias por la aclaración!
