### ISSUE TITLE
Pregunta sobre entrega

### ISSUE THREAD

**Issue by notyourlasagna** [IIC2233/syllabus#231]
Hola, quería preguntar qué archivos debemos incluir en nuestra carpeta T00 de nuestros repositorios, y qué archivos no. Tipo aparte del main y los módulos que creamos para el juego. Deberíamos subir puntajes.txt? o parametros.py? o cuáles?

**Comment by DCCollao** [comment]
Hola @notyourlasagna! En la issue #93 se habla bastante sobre este tema. Si te queda alguna duda, escríbela en esa issue por favor!
