### ISSUE TITLE
Duda sobre divisas de cada barco

### ISSUE THREAD

**Issue by fsotomutoli** [IIC2233/syllabus#231]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! tengo una consulta, al momento de tener que transformar el costo de mantención del barco, todos los valores de las divisas varían a cada día (sumado a que tendremos que leer al ojo el csv línea por línea para identificar todas las divisas usadas aparte del dolar). **¿Es posible que se nos entregue el número de divisas distintas para que no tengamos que revisar todas las divisas antes de comenzar a programar?**

**Comment by Juampisaez** [comment]
Hola @fsotomutoli 
No es necesario, en el enunciado se les entrega una libreria para poder hacer de mejor forma las conversiones, [CurrencyConverter](https://pypi.org/project/CurrencyConverter/).

Espero quede mas clara esta parte.
Quedo atento de igual manera :)
