### ISSUE TITLE
Valor de parámetros

### ISSUE THREAD

**Issue by elshavi** [IIC2233/Syllabus#231]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Los parámetros asociados a probabilidades, debemos darles un valor arbitrariamente, o corresponde que este se les asigne por medio de un randint?

**Comment by Dominique236** [comment]
Hola @elshavi !

Tal como se menciona en la sección 6.3 del enunciado, un parámetro de probabilidad se vería de la forma
`PROBABILIDAD_TORMENTA = 0.2`, por lo que no debe ser por medio de un _randint_, esto también por que usamos el archivo _parametros.py_ para almacenar valores constantes requeridos en el código principal.

**Comment by yonieeh** [comment]
Hola! 
Me surge una duda, ya que en el enunciado se menciona como dices que el formato de los parametros de probabilidad seria en decimal, sin embargo, en la sección 4.2.1 se habla de, por ejemplo, CANSANCIO%, lo cual al menos yo entiendo no seria consistente con representar las probabilidades como decimales, ya que si el enunciado menciona así el CANSANCIO%, entiendo yo que entonces cansancio sería un número entre 1 y 100, como por ejemplo 20, quedando asi 20% en CANSANCIO%, opuesto a 0.2% en CANSANCIO%, por ejemplo.
Esa es una decisión de diseño que debemos tomar nosotros? O a la hora de evaluar nuestras tareas se ocupara un archivo de parametros distinto al que hayamos creado nosotros? Gracias!

**Comment by Dominique236** [comment]
Hola @yonieeh !
En el comentario anterior no me refiero a que la probabilidad necesariamente debe ser un decimal, sino que debe ser un valor arbitrario constante. Con eso en mente, tal como tu mencionas, el valor que le dan al parámetro corresponde a una decisión de diseño que deben tomar ustedes. 
Ojala haber aclarado tu duda :)
