### ISSUE TITLE
Usar yield en __iter__

### ISSUE THREAD

**Issue by sfga** [IIC2233/Syllabus#231]
Hola,

   ¿puedo usar un `yield` en el `__iter__` de una lista ligada?

**Comment by indonoso** [comment]
sí

**Comment by sfga** [comment]
Gracias por contestar. De paso, te pido disculpas, ya que en realidad, me quería referir a otra tema (Tarea 2) con el uso de `yield` y no lo detallé suficientemente. Voy a crear una issue con el mensaje corregido.

**Comment by indonoso** [comment]
Puedes corregir tu pregunta en la misma issue. No es necesario que crees otra.

Puedes usar `yield` en un método `__iter__`.
