### ISSUE TITLE
Recorrido enemigos

### ISSUE THREAD

**Issue by Jbijit** [IIC2233/syllabus#231]
Se puede hacer que los enemigos no hagan un camino aleatorio y que al pasar por un espacio de manera "inteligente" no pueda volver a pasar?

**Comment by Hernan4444** [comment]
Hola, si puedes 👌🏻

Solo asegura que esa forma inteligente que implementes te asegure hacer cargo del caso donde un enemigo no quede siempre lejos de una torre y por ello no termine la ronda 

Saludos :v:
