### ISSUE TITLE
Duda sobre ponderador diurno

### ISSUE THREAD

**Issue by karlamunoz14** [IIC2233/Syllabus#231]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
El ponderador diurno debe ser 0,9 o debe ser un entero definido por mi?
ya que en el momento en el que se habla de la función dice que el ponderador debe ser un int
![funcion intervalo aparicion](https://user-images.githubusercontent.com/101335687/193437943-99235e2e-5913-4aa3-8a91-7731fd598f85.png)
Y al mostrar las caracteristicas del jardin de la abuela se dice que el ponderador tiene un valor de 0,9
![PONDERADOR_DIURNO](https://user-images.githubusercontent.com/101335687/193438009-4dc935b6-d223-48b1-9ae1-a7acb42ceece.png)

Y lo mismo con el ponderador  nocturno

**Comment by Lord-Kelsier** [comment]
Hola @karlamunoz14 , buena observación tenemos que corregir eso. Les subiremos una nueva función.
