### ISSUE TITLE
Creo que rompí algo en mi repo :(

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#231]
Hola, 
Intenté hacer una nueva branch con el comando 
> ```git branch [nombre]``` (sin los corchetes) 

y luego cambié a esa branch con 
> ```git checkout [nombre]``` (sin los corchetes) 

y me imprime 
> M  -path-/nombre_archivo

para dos archivos que agregué hace semanas. Luego intento hacer 
> ```git add .``` 

y no dice nada. 
> ```git commit -m "MENSAJE DESCRIPTIVO"``` 

y me dice:
> On branch [nombre]
Changes not staged for commit
modified: ../../-path-/el_nombre_de_antes
no changes added to commit

Luego intento, por ejemplo, borrar un archivo de mi repo, 
> ```git add .```
```git commit -m "Mensaje descriptivo"```

y me muestra los cambios
luego
> ```git push```

y dice:
> fatal: The current branch [nombre] has no upstream branch.
To push the current branch and set the remote as upstream, use
git push --set-upstream origin [nombre]

En mi repo de github no aparece la nueva branch. Intenté crear una nueva desde ahí y "funcionó", puedo seleccionarla en github perno al usar el comando 
> ```git branch```

solo sale la que creé desde la consola de git
Intento eliminar la nueva con 
> ```git branch -d [nombre]```

y me lloró porque las branches no estaban completamente combinadas y pedía que la 'd' fuera mayúscula. Lo hice y eliminó la branch que creé en la consola, ahora tengo mi branch master en git y github pero la que creé en github sigue ahí y ```git branch``` no la muestra.
Para finalizar, intenté mover la carpeta de la tarea 2 como respaldo y me dice que no puedo porque otro programa la está usando (ya había cerrado la consola de git).
No sé qué hacer 😢

**Comment by MrEarle** [comment]
Posibles soluciones:
- Descarga tu tarea de GitHub para tenerla de respaldo.
- Reinicia tu computador. Una vez me pasó algo parecido y después de reiniciar volví a poder tener acceso a mis archivos.
- Puedes hacer Pull a una branch en específico para traerla a tu repositorio local (`git pull origin NombreBranch`)

Un par de tips para la próxima:
- `git push origin NombreBranch` Sube tu branch a GitHub. (Y te evita el error del 'set upstream origin')
- `git branch -D NombreBranch` te deja eliminar una branch que no ha sido combinada. Cuidado con borrar algo que te sirva.

Ojalá te sirva!

**Comment by jmwielandt** [comment]
Reinicié y recuperé el acceso, gracias!
Ahora quería saber qué puedo hacer con esta branch que hice desde github (en git no la muestra)
![image](https://user-images.githubusercontent.com/37153467/38787437-35c729be-4104-11e8-9917-bb010dcd55d2.png)

**Comment by MrEarle** [comment]
Puedes hacerle pull a esa branch para que te aparezca en tu computador:
`git pull origin no-slices`

**Comment by jmwielandt** [comment]
😟 
![image](https://user-images.githubusercontent.com/37153467/38787648-c602319e-4105-11e8-93f5-235f3e1843a0.png)

**Comment by MrEarle** [comment]
Puedes hacer checkout en no-slices?
Has hecho algún commit en esa branch?
Aveces git no muestra una branch que no tiene nada.
