### ISSUE TITLE
Importaciones mutuas entre dos archivos.

### ISSUE THREAD

**Issue by Juan379** [IIC2233/syllabus#231]
Hola!
Estoy teniendo algunos problemas ya que preliminarmente hice todos los menus con funciones del estilo menu_sesion(), menu_principal() etc. El problema es que dentro del archivo donde esta la funcion del menu de sesion importo el archivo donde esta la funcion del menu principal y viceversa, ya que de esta manera puedo controlar el flujo. 
Esto me genera un problema del tipo:
 
AttributeError: module 'Menu_Principal' has no attribute 'menu_principal'

Que pasa cuando desde el archivo Menu_Sesion (que tiene la funcion del menu sesion) importo Menu_Principal y llamo de este la funcion menu_principal() que tiene el menu principal. Este ultimo archivo a su vez tambien importa Menu_Sesion con su funcion mencionada.

Encontre una solucion en
 https://stackoverflow.com/questions/1250103/attributeerror-module-object-has-no-attribute
la cual implica importar los archivos en la funcion que se neceseiten y no al principio del archivo como especifica PEP8. Esto tendria algun tipo de descuento??

**Comment by StroveLight** [comment]
Hola! Como dices, importar circularmente (es decir el importar mutuamente entre dos archivos), es una mala práctica que no cumple con el PEP8. 

Es posible que estes necesitando importar circularmente al llamar mutuamente entre dos funciones, en vez de retornar en una y volver, lo que necesitas es hacer que una función retorne para volver a la que la llamó

He aquí un ejemplo:

```python
def submenu():  # funcion que es llamada por el bigmenu
    print('Bienvenido al submenu!\n'
          '¿Qué deseas hacer?\n'
          '[1] no salir\n'
          '[0] salir')
    respuesta = int(input())
    while respuesta != 0:
        print('¿Qué deseas hacer\n'
              '[1] no salir del submenu\n'
              '[0] Salir del submenu')
        respuesta = int(input())
    print('regresas al bigmenu')
    return  # return para regresar al bigmenu, se usa esto en vez de llamarlo desde aquí


def bigmenu():
    print('Bienvenido')
    print('escoge una opcion\n'
          '[1] entrar a submenú\n'
          '[0] salir')
    number = int(input())
    while number != 0:
        submenu()  # aqui es donde se entra al submenu
        print('escoge una opcion\n'
              '[1] entrar a submenú\n'
              '[0] salir')
        number = int(input())
    print('Sales del programa')

bigmenu()  # Aquí es donde lo ejecutas

```
