### ISSUE TITLE
Lista de funciones y su posterior ejecucion

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#232]
Al momento de que le gobierno desea tomar acciones, defini una funcion para cada una de dichas acciones (las cuales son metodos de la clase Pais). Como es la sintaxis para retornar o crear una lista que incluya dichas funciones?
Ej: Debiese usar `output.agregar_nodo(self.cerrar_aeropuertos)` o `output.agregar_nodo(self.cerrar_aeropuertos())` o `output.agregar_nodo(cerrar_aeropuertos)` 
Ninguno parece funcionar
Mi plan final es luego ejecutar: `for f in lista: f()`

**Comment by indonoso** [comment]
No entiendo tu modelación. El gobierno tiene un país? o al revés? Dónde se están agregando los métodos a  `output`? Para obtener las funciones lo correcto es `objeto_que_tiene_la_funcion.funcion`. Esta línea `objeto_que_tiene_la_funcion.funcion()` ejecuta función.

No estoy muy segura de que hacer una lista de funciones sea la mejor idea para ejecutar las acciones del gobierno. Parece una modelación extraña.
