### ISSUE TITLE
Semana 03: multiherencia, duda con ejemplo clase Académico

### ISSUE THREAD

**Issue by NikiHV** [IIC2233/syllabus#232]
Hola!!
Tengo una duda con la solución del ejemplo de la clase Académico del cuaderno 2-multiherencia de la semana 03 (es el último código que aparece en el cuaderno).
¿Por qué en todas las clases se llama a `super().__init__(**kwargs)`?

Cuando trabajábamos con herencia "única" solo usábamos el `super()` en la subclase, no se llamaba en la superclase, ¿por qué en la multiherencia (o en este ejemplo) se llamó al `super()` en todas las clases, sean sub o superclases? ¿de qué sirve usarlo en las superclases?

Me puse a jugar un poco: agregué un kwarg extra en la instanciación de `Academico` y me puse a comentar las líneas donde hay `super()`s. Lo que pasó es que el programa solo funcionó bien, sin tirar error, cuando tenía el llamado del `super()` en `Academico` (obviamente) y `Docente`, pero no en `Investigador` (ahí lo tenía comentado). En todos los otros casos o posibles combinaciones de tener o no el `super()` me tiró error. En resumen, fue interesante pero no entendí nada de cómo funciona. Help.

**Comment by igbasly** [comment]
Hola @NikiHV :v:

Me alegro que hayas jugado con la aplicación de `super` al interior de las clases 👏 . Los resultados que obtuviste se debe a como funciona `super`, lo cual además es la razón por lo que se utiliza.

Como se menciona, `super` verifica y sigue la jerarquía de clases utilizada en python, es decir, de izquierda a derecha en las superclases. Para este caso en particular, esa jerarquía es:
`Academico` -> `Docente` -> `Investigador`

Es por esto que `super` va a ir por cada una de estás clases iniciando el constructor, en el orden mencionado.
Si vamos más adentro, cuando en `Academico` se ejecuta `super().__init__(**kwargs)`, lo que hace es llamar al `__init__` de la siguiente clase de la jerarquía, `Docente`. Ahí dejar todo lo que contenga `kwargs`, donde la propia clase utilizara el *key*  `departamento` y lo restante lo pasará nuevamente al `super().__init__(**kwargs)` que `Docente` contiene, quien a su vez seguirá con la jerarquía, es decir, con la clase `Investigador`.

Como la jerarquía de este modelo lleva `Docente` antes que `Investigador`, sin el `super` en el constructor de `Docente` no se puede llegar a al constructor de `Investigador`, pero al ser `Investigador` la última clase a instanciar, la presencia de `super` es ligeramente irrelevante.

Una forma de comprobar esto, es que en la linea donde se define 
```python
class Academico(Docente, Investigador):
```
 intercambies las clases heredadas, ya que estas son las que definen la jerarquía. De esta forma si mantienes solo el `super` de `Docente`, debería arrojarte un error.

Ahora, se utiliza el `super` en ambas clases para manejar todos los casos, es decir, que da lo mismo el orden en que las clases heredadas se ingresen, nosotros sabemos que va a funcionar.

Espero haber aclarado tus resultados, no dudes en comentar cualquier inquietud 👍 .

**Comment by NikiHV** [comment]
Gracias!! Me quedó clarito!! 😄 

Ahora qué pasaría si, ocupando la jerarquía original del ejercicio, la clase `Docente` estuviera heredando de otra clase, supongamos `Educador`. Cuando instanciemos `Academico`, el `super` de Docente ¿llamaría a `Investigador` (siguiendo la línea de `Academico`) o iniciaría su ruta hacia `Educador`? En el segundo caso, el `**kwargs` que le entreguemos a la instancia de `Academico` debería considerar los argumentos necesarios para inicializar `Educador` también ¿no?

**Comment by igbasly** [comment]
Que bien 😃! 

Respondiendo a tu nueva pregunta, si agregas la clase `Educador` como padre de `Docente`, este quedaría después de `Docente` en la jerarquía y no después de `Investigador`. 
Puedes ver la jerarquía siguiendo cada padre y sus ascendencia de izquierda a derecha desde la clase a evaluar. Por ejemplo si agregases otra clase, llamémosla `Científico`, como padre de `Investigador`, la jerarquía se vería así:
**`Academico` -> `Docente` -> `Educador` -> `Investigador` -> `Cientifico`**

Y respecto a lo segundo, sí, siempre debes considerar los argumentos de la ascendencia al momento de llamar al `super`, para este caso en `Academico` se deben entregar los argumentos con sus respectivos *key* para toda su ascendencia. De esta forma te aseguras que serán distribuidos como corresponde y las clases serán instancias de forma correcta.

Buen trabajo con tus preguntas :raised_hands: y no dudes en preguntar si algo no quedó claro.
