### ISSUE TITLE
Duda multiherencia de ABC y  QThread

### ISSUE THREAD

**Issue by diegocostares** [IIC2233/Syllabus#232]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, estoy intentando crear una clase que herede de ABC y de QThread que herede las características de una clase padre, pero me han surgido varios errores de multi herencia que no he podido solucionar, les dejo un ejemplo de lo que quiero hacer y del error que me aparece:

```python
class ClasePadre(ABC): 
   def __init__(self, ....):
          super().__init__()
        ...
class ClaseHija(QThread, ClasePadre):
   def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
````
Y el error que me arrroja es el siguiente:
```
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by diegocostares** [comment]
Dejo constancia que modifique mi pregunta porque con el avance hice otra cosa y ahora tengo una dificultar muy relacionada, pero que es ligeramente distinta...

**Comment by Christian-Klempau** [comment]
Hola! Tu problema es algo bastante complejo que se debe a una particularidad de Python respecto a las **Metaclases**.
Una manera de solucionarlo es lo siguiente:
```python
from PyQt5.QtCore import QThread
from abc import ABC

class MetaClase(type(ABC), type(QThread)):
    pass

class ClasePadre(ABC): 
   def __init__(self, abst):
          self.atributo_abstracto = abst
          super().__init__()

class ClaseHija(ClasePadre, QThread, metaclass=MetaClase):
   def __init__(self, abtibuto_hijo, *args, **kwargs):
        self.abtibuto_hijo = abtibuto_hijo
        super().__init__(*args, **kwargs)


miThread = ClaseHija(1, 2)
print(miThread.abtibuto_hijo)
print(miThread.atributo_abstracto)

>>> 1
>>> 2
```
Los detalles más profundos se salen de mi conocimiento, pero puedes leer acá sobre el tema: https://realpython.com/python-metaclasses/

En resumen, lo que ocurre es que las clases mismas tienen que tener un **tipo**, como el tipo de `1` es `<class 'int'>`, mientras que el tipo de una clase es `<class 'type'>`. El error que mencionas sucede ya que la clase ABC y la clase QThread tienen metaclases distintas, entonces python no sabe cuál asignar al momento de construirla. Con el kwarg de `metaclass` puedes forzarla a que sea una metaclase que hereda de ambos tipos, solucionando el problema.
Suerte!
