### ISSUE TITLE
Consulta archivo parametros.py

### ISSUE THREAD

**Issue by fcsanchez** [IIC2233/syllabus#232]
Hola, he leído en varias issues que la tarea será corregida con el archivo parametros.py que subiremos cada uno. Quisiera saber si los correctores además utilizarán otro archivo parametros.py para probar la tarea o modificarán los valores que hay en el archivo que subamos.
Saludos

**Comment by RositaMunoz** [comment]
Hola!
Para corregir modificaremos los valores en el archivo `parametros.py` que ustedes nos entreguen.

Éxito con la tarea!

**Comment by fcsanchez** [comment]
Gracias!
