### ISSUE TITLE
errores encontrados en parte D del ejerc prop 1.4 s-05 (Minando en la DCCueva)

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#232]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, me parece que en el ejercicio que menciono,  en el código base para la parte D, donde sale "if cantidad < 1:" en la definición del método "demoler" de la clase "Demoledor", debiera ser "if cantidad > 1:", pues así tendría sentido ocupar plural para referirse a la cantidad de muertos. Adicionalmente, en el mismo código hay un error de tipeo en la definición del atributo de instancia "cantidad" en el método \__init__ de la subclase "Minero".

**Comment by aaossa** [comment]
Hola, gracias por el aviso. En verdad creo que el cambio más correcto en el `if` sería a `if cantidad != 1`, ya que el singular solo lo usamos cuando hay un elemento (usamos plural en el 0... cosas del español supongo). También encontré un error en el uso de la variable `chequeador`, que después se ocupa como `checkeador`. De todas maneras, cambiaré esto internamente, para no tener que modificar nuevamente los archivos y producir problemas de sincronización con quienes hayan ejecutado los archivos localmente. Después de los cambios, el código quedó así:

```python
import time
import random
from threading import Thread


class Demoledor:

    def __init__(self, trabajadores):
        self.trabajadores = trabajadores

    def demoler(self):
        print('La DCCueva ha sido derrumbada')
        chequeador = [trabajador.adentro for trabajador in self.trabajadores]
        if True in chequeador:
            cantidad = chequeador.count(True)
            if cantidad != 1:
                print(f'Que desastre, han muerto {cantidad} trabajadores')
            else:
                print(f'Que desastre, ha muerto {cantidad} trabajador')
        else:
            print('Buen trabajo, ningun trabajador salio herido')


class Minero(Thread):

    def __init__(self, nombre):
        super().__init__()
        self.daemon = True
        self.nombre = nombre
        self.velocidad = random.randint(2, 4)
        self.cantidad = 0
        self.adentro = False

    def recolectar_recursos(self):
        cantidad = random.randint(5, 15)
        tiempo = cantidad / self.velocidad
        self.adentro = True
        time.sleep(tiempo)
        print(f'Trabajador {self.nombre} ha recolectado {cantidad} DCCriptoMonedas')
        self.adentro = False

    def run(self):
        for i in range(3):
            print(f'Trabajador {self.nombre} ha entrado a la DCCueva')
            self.recolectar_recursos()


t1 = Minero('John')  # Eres libre de modificar los nombres :)
t2 = Minero('Alex')  # Eres libre de modificar los nombres :)
t3 = Minero('Peter')  # Eres libre de modificar los nombres :)
demoledor = Demoledor([t1, t2, t3])

# Acá debes iniciar los threads y asegurarte de que el Demoledor los espere

# No modificar
demoledor.demoler()
```

¡Gracias por el aviso 🙌 !

**Comment by JuanpaBC** [comment]
por nada
