### ISSUE TITLE
ImportError de PyQt5

### ISSUE THREAD

**Issue by tamarabend** [IIC2233/syllabus#232]
Al intentar importar PyQt5 en PyCharm aparece este error:
```python
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/QtWidgets.so, 2): Symbol not found: __os_activity_create
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore
```

Y al escribir el comando para instalar pyqt5 con pip en el terminal me aparece
```python
Requirement already satisfied
```

Tengo mac y la version 3.6.8 de python, y he intentado desinstalar y reinstalar pyqt desde el terminal y desde la pagina de internet de pyqt y no me funciona. Por favor ayuda :smiley: :pray:

**Comment by fediaz3** [comment]
Intenta instalar PyQt5 desde el terminal, pero de Pycharm no en cmd.
A mi me arrojaba otro error pycharm y eso me sirvió,  quizás puede servir en tu caso

**Comment by tamarabend** [comment]
@fediaz3 intenté eso pero tampoco me funcionó :(

**Comment by Arcoirisky** [comment]
hiciste pip en mac o brew? D:

**Comment by tamarabend** [comment]
hice pip porque mi computador es muy antiguo y no puedo instalar brew

**Comment by Arcoirisky** [comment]
oh vaya, según entiendo el error no encuentra el archivo a importar dónde debería de estar, muchos mueven sus archivos a donde los pide pycharm (hay otra issue con esa solución) y pareció funcionar

**Comment by tamarabend** [comment]
Esque tengo una amiga que hizo eso y tuvo que resettear su computador porque se le echó, entonces quiero ver si hay otra manera de arreglarlo jajaj :(

**Comment by jmwielandt** [comment]
Por si llega alguien con el mismo error, se resolvió en la issue #296 😄
