### ISSUE TITLE
Actualización de GUI

### ISSUE THREAD

**Issue by iqacevedo** [IIC2233/Syllabus#233]
Estimados, 

Se ha actualizado la `GUI` debido a los errores que han detectado. Si encuentran algún otro error, coméntenlo en esta issue. El cambio más importante que tiene esta versión es que ahora pueden utilizar la función `rotate_piece`. Ésta no recibe argumentos y rota la pieza actual hacia la **derecha**. Del mismo modo en que cuando se presiona el botón rotar, esta función llama al método `rotar_pieza` que **ustedes deben sobreescribir**. Finalmente, para llamar a esta función solo deben escribir `gui.rotate_piece()`.

EDIT: No se preocupen si no existe el método agregar_pieza no es necesario que lo implementen, solo deben preocuparse de calcular y mostrar el puntaje final de ambos jugadores al final de la partida.

EDIT: Las imágenes de las piezas "CGGCGG.png", "CGGGCC.png", "CGGPPG.png" se han modificado, a parte de que la pieza "GCCRPG.png" cambió su nombre a "GCCRPR.png" y la imagen de esta se mejoró para que cumpliera con las características del nombre.

¡Saludos!

**Comment by bedefrunner** [comment]
Hago git pull estando en la carpeta tareas y me dice que esta todo al día. No debiera actualizarse?

**Comment by Calomi** [comment]
Hola!
Es algo tal vez insignificante... pero, la imagen "GCCRPG.png" 
![gccrpg](https://user-images.githubusercontent.com/5609537/30091781-cb4683b2-9291-11e7-9383-b33595ec0a5e.png)

no debería llamarse "RCCRPG.png" o RCRGPG?
Sé que ya dijeron en algunas issues y en el enunciado que hay que guiarse solo por la sigla y no la imagen, pero esta imagen claramente tiene dos lados que son río y puede llegar a ser molesto cuando uno esté testeando/jugando, no creen? (y los csv también usan "GCCRPG")

**Comment by Arcoirisky** [comment]
Hagan pull al Syllabus, se actualizaron varias imagenes y el nombre de esa pieza que dices @Calomi por GCCRPR.png" 
Saludos :)

**Comment by Calomi** [comment]
Hola de nuevo!
dentro de gui, en variables.py en la linea 23 aun sigue los nombres viejos que supongo que es lo que genera la issue #290, podrían cambiarlo :D? aunque ya queda poco xd jaja
saludos!
