### ISSUE TITLE
Properties

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2233/syllabus#233]
Hola! me quedó una duda de la semana pasada 🙍  es que no sé cuando se me tiene que "ocurrir" usar properties en cierto problema sin que me lo pidan explícitamente. Gracias de antemano 😄

**Comment by KnowYourselves** [comment]
Hola @beatrizacuna!

Las _properties_ se utilicen más comunmente en dos casos:

1. Cuando una variable depende de otra.
2. Cuando queremos sanitizar el seteo de una variable.

El caso 1. es por ejemplo, si tengo un circulo que tiene área y radio y yo se que el radio va a cambiare mucho, por ende, como el área depende del radio puedo usar una property para que este se actualice automáticamente.

El caso 2. es como en la tarea, donde el nombre de usuario debía cumplir ciertas caracteristicas, entonces podemos usar un _setter_ para que solo acepte cambiar el valor de usuario si es válido. También aplica cuando una variable que es cambiada constantemente tiene que mantenerse en un rango.

Espero haberte ayudado!
