### ISSUE TITLE
Duda enunciado

### ISSUE THREAD

**Issue by jervaal** [IIC2233/syllabus#233]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! me surgió una duda sobre enunciado. Al momento de definir Barco, tenemos que tiene el atributo de probabilidad de encallar, este atributo ¿Es el mismo que el tend_encallar que se utiliza para la formula en el metodo de Encallar? ¿o son 2 cosas distintas?

Ademas me surge la duda similar sobre el coste de mantencion de la clase barco, en los tipos de barcos, ¿este es el mismo valor de COSTO_USO_BUQUE?

De antemano muchas gracias!

**Comment by DomingoCarvajal** [comment]
El coste de mantención no es un parámetro de cada tipo de barco, si no que viene en el archivo `barcos.csv`. Es distinto para cada barco y viene en el tipo de moneda de cada barco también.

**Comment by DomingoCarvajal** [comment]
En cuanto al atributo de la probabilidad de encallar, si es el mismo que tend_encallar.

**Comment by jervaal** [comment]
Muchas gracias!
