### ISSUE TITLE
Probabilidad accidente

### ISSUE THREAD

**Issue by dtgazmuri** [IIC2233/syllabus#233]
Hola
En la fórmula para calcular la probabilidad de accidente, 
_(durabilidad_max_chasis - durabilidad_actual_chasis)/durabilidad_max_chasis_ 
se encuentra dentro de una función piso. Esto haría que esto siempre fuera igual a 0. ¿Esto no debería ser así, cierto?

**Comment by jaromero6** [comment]
Hola!
Efectivamente como dices con la función piso se haría siempre 0. Si esto te incomoda puedes quitarle la función piso y **especificarlo en el readme**.

**OJO:** Puedes quitar la función piso, pero **no** puedes redondear o usar la función techo.
Ánimo con la tarea!!
