### ISSUE TITLE
POSIBLE ERROR EN EL ARCHIVO EXCAVADORES.CSV

### ISSUE THREAD

**Issue by tremendapithon** [IIC2233/Syllabus#233]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola buenas tardes tengo una duda sobre el archivo de excavadores.csv, ya que hay algunos excavadores que tienen parámetros iguales a 0 y se supone que el valor deberia ser entre 1 y 10

**Comment by Benjeeeh** [comment]
Hola!

Al momento de revisar las tareas nos aseguraremos de revisar con el archivo que tenga valores entre 1-10 para tener consistencia con lo que se dice en el enunciado. Gracias por darte cuenta! Para esto puedes editar tu archivo de excavadores.csv en los valores de suerte que sean iguales a 0.

Por otra parte, aunque si bien puede considerarse un error en este contexto, existen formas para asegurarse de que los atributos se encuentren en cierto rango esperado al definir sus atributos, el cual fue un contenido visto en clases y es útil en estos casos para mejorar la robustez de tu programa. Esto lo dejo como moraleja, pero lo importante es lo primero en este caso de lo que estamos evaluando.

Éxito en la tarea!

**Comment by tomastrivino** [comment]
Hola @Benjeeeh , yo me di cuenta de este error y para solucionarlo hice que al momento de instanciar mis clases del tipo Excavador (dentro del __init__), se hiciese un llamado a los setters respectivos para corregir esa cantidad (desde 0 a 1). ¿Está bien esa implementación?

Gracias

**Comment by Benjeeeh** [comment]
@tomastrivino No habría problema, si te funciona déjalo así y no te preocupes. De igual manera nos encargaremos de usar archivos (los mismos en realidad, pero con los valores corregidos) para que no hayan valores fuera de los intervalos dichos en el enunciado.
Éxito!!
