### ISSUE TITLE
Señales no reconocen funciones con "event"

### ISSUE THREAD

**Issue by FGarciaVarela** [IIC2233/Syllabus#233]
* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, tengo una duda sobre señales ya que emito una señal hacia mi ventana juego, y mediante prints, veo que se ejecutan todos excepto los que entran a una función de estilo:
def "nombre"(self,event):
      ... 
      ...

No entiendo por qué ocurre ya que debería entrar por igual como al resto de las funciones. Muchas gracias por su tiempo.

**Comment by catalinacarter** [comment]
Hola @FGarciaVarela! Las funciones del estilo que mostraste reciben un evento que simplemente ocurre y realizan un efecto, sin necesidad de ser activadas por una señal. Es decir, ocurre un evento (eventos de mouse, eventos de teclado, entre otros) y se ejecuta la función. El evento activa la función. Ahora, lo que ocurre al ejecutarse la función es variado y depende de lo que busques. Algunos ejemplos vistos en los contenidos: ocultar/mostrar un label, mostrar/ocultar texto o emitir señales personalizadas, entre otros. Este último es lo más típico. 
Por ejemplo: ocurre el evento, se ejecuta la función definida como "nombre"(self, event) y se emite una señal, y los métodos conectados a esta señal se llamarán automáticamente.
Espero que te sirva!
