### ISSUE TITLE
*args y **kwargs

### ISSUE THREAD

**Issue by DaniloCordova13** [IIC2233/Syllabus#233]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda
Hola!!!
Tengo una confusión con el uso de *args y **kwargs. No entiendo por qué en el ensayo del midterm en la pregunta 9 (adjunto foto), la alternativa D es correcta, ya que estamos poniendo un argumento después de colocar el *args, entonces sólo tendría como opción ser un argumento con keyword, y no es así. No entiendo por qué estaría correcto.
![Captura de pantalla (26)](https://github.com/IIC2233/Syllabus/assets/141789725/e3f1c0cb-66b2-4179-be80-23183b6f7ecb)

De antemano muchas gracias!

**Comment by Dvckhv** [comment]
Hola!
La regla con args y kwargs es que luego de un kwarg no puede ir un arg, osea, no se incumple si luego de un arg va un arg. Notar que en la respuesta A) primero **no es un kwarg!!** solo tiene un comportamiento definido en caso de no ser recibido dentro de la llamada a la función. Cuentame si se entiende :)

**Comment by DaniloCordova13** [comment]
Siii, al final de los contenidos de *rags y **kwargs estaba esa aclaración que no recordaba! Muchas gracias 🤗
