### ISSUE TITLE
Movimiento personaje

### ISSUE THREAD

**Issue by jerrymendoza** [IIC2233/syllabus#233]
El personaje puede moverse tanto en celdas 'C' como en 'O'? o solo en 'C'?

Gracias

**Comment by Hernan4444** [comment]
Estimado, 
Esa información está en el enunciado.  Si recuerdo bien, debería ser en la sección 5.2: cuando se habla del personaje y que cosas no atravesar.

Saludos ✌️

**Comment by jerrymendoza** [comment]
Hola, si ..leí ese apartado, solo me entro la duda ya que parece innecesario que camine por los ‘O’ , las monedas nunca estarán ahí 🤔

**Comment by Hernan4444** [comment]
>  las monedas nunca estarán ahí 🤔

¿Por qué? Estoy 99.999% seguro que hay un párrafo que dice que las monedas pueden aparecer tanto en caminos como en espacios libres ("o"). Verifica eso, porque si no aparecen en espacios libres, no estaría totalmente bien tu ítem de que las monedas aparecen en el mapa de forma aleatoria.

Saludos ✌️

**Comment by jerrymendoza** [comment]
Cierto, la información que no encuentre en 5.2 estaba en la sección 4...

Gracias 😁
