### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Cschavez** [IIC2233/Syllabus#234]
Hola! cuando pido imprimir una instancia de jugador (ya está implementado su método str correspondiente) me tira este error:

```
Traceback (most recent call last):
  File "C:/Users/Camila/Desktop/Camila/Cschavez-iic2233-2018-1/Tareas/T02/grafo.py", line 179, in <module>
    print(grafo.jugadores[4])
  File "C:\Users\Camila\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0107' in position 546: character maps to <undefined>
```
Al leer el archivo lo lee bien y guarda a todos los jugadores, pero al intentar imprimir es cuando a veces me pasa eso, traté de encontrar una solución pero no pude. 
Muchas gracias!

**Comment by IchottMano** [comment]
@Cschavez Hola!
Una pregunta, como abres la base de datos?
Saludos!

**Comment by Cschavez** [comment]
Asi:
`with open(path, "r", encoding = "utf8") as file:`

**Comment by IchottMano** [comment]
Y que es lo que intentas imprimir?

**Comment by Cschavez** [comment]
cuando leo una linea creo una instancia del jugador y lo guardo en mi lista, luego tomo cualquier indice de la lista con los jugadores y lo imprimo, lo estaba haciendo solo para probar. A veces me imprime un jugador y otro no (tienen método __str__, que imprime su nombre, club, liga, nacionalidad y los jugadores con los que está unido en el grafo)

**Comment by IchottMano** [comment]
@Cschavez podrías hacer push a tu repo para poder ver bien el código?

**Comment by Cschavez** [comment]
listo !

**Comment by Cschavez** [comment]
en "grafo" está el código que me tira el error

**Comment by IchottMano** [comment]
@Cschavez Acabo de correr el código sin problemas, intenta vovler a descargar la base de datos y reemplazarla por la que tienes en tu carpeta, luego dime si sigue tirandote el error o no

**Comment by IchottMano** [comment]
Lo mas probable es que se deba a que algunos de los nombres de los jugadores tienen letras no ASCII, en este caso la letra específica es una ć

**Comment by Cschavez** [comment]
es que hay veces que me pasa y otras que no, por eso intento con indices al azar. Y si es como tú dices, como puedo hacer para que no me tire un error si es que el nombre de los jugadores tiene esa letra?

**Comment by IchottMano** [comment]
Intenta, en tu código para leer el archivo, escribir
```python
with open(path, "r", encoding="utf8", errors="ignore") as file:
```
Lo mas probable es que esto pueda arreglar el error, de lo contrario, por favor avísame
Saludos!

**Comment by Cschavez** [comment]
Me sigue saliendo el mismo error

**Comment by IchottMano** [comment]
Viendo mas cercanamente tu error (no he podido hasta el momento replicarlo en mi computador, aun al intentar imprimir 300 jugadores por separado), veo que python esta accediendo a
```
C:\Users\Camila\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py
```
lo cual no debería hacer, ya que significa que python esta ocupando encoding cp1252.
Ahora, si cambias el "utf8" en tu encoding por "utf-8"? Puede que eso solucione el problema. 
De todos modos, seguiré buscando a ver cual puede ser el problema.

**Comment by IchottMano** [comment]
@Cschavez Buscando una solución encontré una que puede serte útil:
```python
import io

with io.open(path, 'r', encoding='utf-8') as file:
    # code
```

**Comment by IchottMano** [comment]
Pero insisto en que (si no lo has hecho ya) vuelvas a descargar la base de datos y no la abras, ya que a veces esto puede generar un problema

**Comment by IchottMano** [comment]
@Cschavez Una pregunta, estas usando pycharm? Si ese es el caso, podrías ir a 
File > Settings... > Editor > File Encodings 
y mostrarme una captura de pantalla de lo que aparezca?

Saludos!

**Comment by IchottMano** [comment]
Pregunto porque al fin logré replicar el error y creo saber como arreglarlo, lo que debes hacer es ir al lugar que acabo de especificar 
![encoding](https://user-images.githubusercontent.com/26393051/38790506-194d0592-4118-11e8-965b-f6093fc9e879.png)
 Y ahí debes cambiar "Global Encoding" y "Project Encoding" a UTF-8.
El error lo repliqué cambiando esos dos valores a CP-1252, por lo que lo mas probable es que ese sea el problema.

Espero esto al fin solucione el problema y lo siento por las inefectivas respuestas anteriores 😓 

Saludos y mucho éxito con tu tarea!

**Comment by Cschavez** [comment]
Te pasaste en serio! Mil gracias, por el momento no me ha vuelto a aparecer el mismo error. 
Muchas gracias !
