### ISSUE TITLE
Contenidos semana 9 - falla ejemplo_base

### ISSUE THREAD

**Issue by Osiries1111** [IIC2233/Syllabus#234]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda
Estaba corriendo el archivo servidor_tcp.py del ejemplo_base, y se me quede como pegado en esto y no se si esto es normal o es un problema

![image](https://github.com/IIC2233/Syllabus/assets/130408574/a7bfdc7e-830e-49db-985f-6d43b3204d47)

**Comment by dvillas28** [comment]
El server esta esperando una conexión de un cliente, debes ejecutar el archivo del cliente igual

**Comment by Osiries1111** [comment]
Pregunta, tendría que ejecutarlos los dos a la vez? perdón si es una pregunta media tonta

**Comment by dvillas28** [comment]
sii, abriendo dos terminales y ejecutas a los dos 👌

**Comment by Osiries1111** [comment]
Ahora si me funcionó!! gracias!
