### ISSUE TITLE
No puedo acceder a los contenidos

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#234]
Hola, estoy intentando acceder a los contenidos de la semana 2 pero estos no me abren correctamente. 
No puedo ver lo que contienen los archivos:

![imagen](https://user-images.githubusercontent.com/69520590/91468886-9c990580-e860-11ea-9bbb-dd74d469d01a.png)

**Comment by aaossa** [comment]
Hola, justo respondí esto en #233 😅 Cerraré esta *issue* por lo mismo (TLDR: Es un problema de Github, así que no podemos hacer nada 🐛 )
