### ISSUE TITLE
Duda parte C del ejerc prop 1.4 s-05 (Minando en la DCCueva)

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#234]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, espero que te encuentres bien.

La solución que hasta el momento tengo para este ejercicio es hacer que las instancias de la subclase de threads "Minero" sean deamon threads, de manera que el codigo principal espera 5 segundos luego de ejecutar a los threads mineros, y dado que estos son deamon, al acabarse el código principal se termina el programa. El problema que tengo con esta solución es que siento que en el fondo no estoy de verdad haciendo que los mineros solo trabajen el tiempo necesario (5 segundos) como el enunciado te pide, y se evidencia en uno de los outputs que arroja mi actual solución: 
![image](https://user-images.githubusercontent.com/80859173/115131059-e3d83000-9fc2-11eb-8f3e-7dd35c9f45da.png)
como se aprecia, transcurridos los 5 segundos de espera del codigo principal, uno de los mineros alcanza a printear el resultado de su recolección de criptomonedas antes de que el thread principal acabara de ejecutarse.

por si es de ayuda, dejo el codigo de mi solución actual que generó este output:

**EDIT (@aaossa): Código eliminado por ser una solución**

Ya vi el resto de las guías, pero no recuerdo haber encontrado una forma de detener la ejecución de un threat en determinado momento o después de determinada cantidad de tiempo. Si me lo perdí favor indicarme donde encontrarlo, y si no, agradecería cualquier orientación en el asunto.

Desde ya gracias.

**Comment by aaossa** [comment]
Hola @JuanpaBC , primero que todo, eliminé tu código porque estás publicando una solución a un ejercicio propuesto. Si bien esto no está prohibido, le quita un poco "la gracia" a intentar hacer el ejercicio por su propia cuenta a tus compañeres y prefiero eliminarlo. Y por favor evita subir tu solución a la primera, no siempre es necesario ver el código para responder las *issues*. Ahora responderé tu pregunta.

Lo que comentas es perfectamente posible por como está escrito el código del ejercicio. Hay un `sleep` y luego vienen las últimas líneas (`print`) que deberían tomar muy poco tiempo. Es posible que justo mientras se ejecutan esas últimas líneas se imprima el resultado de la operación de un *thread*, pero esto no debería ocurrir consistentemente y debería ser muy poco probable. Si es algo que te ocurre **siempre**, habría que dar una mirada para ver que ocurre, pero si solo ocurre a veces no hay problema. ¡Éxito con tu estudio!

**Comment by JuanpaBC** [comment]
vale gracias, cuidaré no volver a hacer lo de subir código. Me queda claro de tu respuesta que no hay problema con el output que muestro (pues me pasa solo a veces). Aun así, hay una forma de establecer un tiempo de vida para los threads (una determinada cantidad de tiempo que quiero que el thread este vivo)?

**Comment by JuanpaBC** [comment]
ya bkn muchas gracias!
