### ISSUE TITLE
Archivos.csv

### ISSUE THREAD

**Issue by pablogw** [IIC2233/syllabus#234]
En el enunciado se señala que el orden de las columnas puede variar del originar a la hora de revisar la tarea, mi duda es que la cantidad de pistas/contrincantes va a ser la misma o esta igual puede variar?

**Comment by gatochico** [comment]
Hola! Si te refieres al número de filas de los archivos, sí, puede variar. Si te refieres a la lista de contrincantes que tendrá cada pista en el archivo `pistas.csv`, sí, también puede variar.
Saludos!
