### ISSUE TITLE
Conectar mapa con personaje

### ISSUE THREAD

**Issue by Dnpoblete** [IIC2233/syllabus#234]
Hola, ya logré crear el mapa que nos piden y el personaje, con los movimientos. Cuando los corro por separado funcionan bien, pero cuando los junto el personaje me aparece en un fondo blanco con el tamaño que corresponde. 
Alguna idea de que podría estar pasando?, trate de arreglarlo cambiando en donde pongo el show(), pero no funciona.
(para hacer el mapa use QPainter, no se si tenga algo que ver)

Agradecería mucho si alguien me puede ayudar

**Comment by hbkim94** [comment]
Hola @Dnpoblete !

Bajo el supuesto de que estás usando `QPixmap` y que estás usando archivos `.png`, ¿has probado con usar `setStyleSheet` o `setFlags`? Como ejemplo para el primer caso:
 
```python
foo = QLabel()
foo.setPixmap(QPixmap("bar.png"))
foo.setStyleSheet("background-color: transparent;")
``` 

Quedo atenta!

**Comment by Dnpoblete** [comment]
Hola, pucha ya lo había arreglado en la mañana, al final era que tenía mal puesto el show() y sys.exit(app.exec_()), pero igual gracias :)
