### ISSUE TITLE
Duda sobre atributos fuera de límites

### ISSUE THREAD

**Issue by navila1** [IIC2233/Syllabus#234]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! En el enunciado se dice que si me entregan un archivo "unidades" con  atributos de los gatos que se encuentran fuera de los límites se debe cerrar el programa. ¿Es posible modificar los atributos correspondientes que estén fuera de los rangos para que se incluyan dentro del rango permitido?

Por ejemplo si me dan un gato con 1000 de vida, es posible que yo corrija eso en mi código y dicho gato tenga la máxima vida permitida (vida maxima = 100) y ejecutar mi juego?

**Comment by CrisDonosoMaass** [comment]
Hola!

Si bien es una buena idea, la pauta exige específicamente en  "Preparación programa"->"Inicio de la partida" que "El programa se cierra, imprimiendo un mensaje de error, si los archivos de base no cumplen con el formato correcto".

Espero haberte ayudado!
