### ISSUE TITLE
Conjunto Eventos en Clase Torneo

### ISSUE THREAD

**Issue by maxo2727** [IIC2233/Syllabus#234]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Estoy confundido con respecto al atributo "eventos" de la clase Torneo, ya que en el enunciado dice que este atributo es el conjunto de eventos que pueden suceder. Pero, no tenemos un conjunto de eventos específicos definidos previamente (como lo es con excavadores, arenas, etc) para poder crear el conjunto de eventos. Y para la función iniciar_evento(), parece no ser necesario utilizar algun conjunto de eventos, simplemente sería suficiente basarse en la probabilidad de cada evento y determinar su impacto en la partida. 

Entonces, es necesario crear algun conjunto de eventos nosotros mismos? o podemos no utilizar este atributo en nuestro programa?

**Comment by Benjeeeh** [comment]
Hola!
Si bien se puede definir de muchas maneras, incluyendo de la forma que mencionas, lo que se menciona en el enunciado se debe establecer si o si, por lo que Eventos debe estar. La idea de Eventos es tener **almacenado** de la forma que prefieras la información que creas necesaria de estos tres eventos y que luego en iniciar_evento se **utilice** esta información directamente desde donde está almacenado.
La lógica de esto es que el Torneo maneja todo lo que sucede dentro de la competencia, y por ende, también debe tener control sobre los eventos y no que cada vez que suceda esto alguien más provea la información necesaria para que ocurra.

Cualquier duda me avisas, éxito en la tarea!

**Comment by camilamartinf** [comment]
Hola! @Benjeeeh 
respecto a esta duda, podríamos asumir que, una vez que hayan ocurrido todos los eventos posibles para un torneo, no ocurran más eventos aunque la probabilidad de iniciar evento sea 1 ?
Pregunto esto porque consideré una probabilidad para cada tipo de evento (la suma =1) y además consideré que hay una cantidad de veces que estos eventos pueden ocurrir (usando el atributo eventos de Torneo). Siento que es más realista restringirlo así para que, mientras más dure un torneo, menos días hayan eventos (que en la vida real es más probable) y que si por ejemplo la lluvia es más probable que un terremoto, si ya han ocurrido suficientes terremotos, entonces solo haya la posibilidad de lluvia. 
Quizás es irrelevante, pero preferí preguntar. Gracias desde ya!

**Comment by Benjeeeh** [comment]
Hola @camilamartinf
En el enunciado se dice que por día debe existir una probabilidad de que ocurra o no uno de estos eventos, pero estos debe ser constante durante la duración del torneo y aparte un mismo evento puede repetirse las veces que sean. Por ende, no es posible implementar lo que pides ya que quitas esta regla de constancia y en mi opinión es mucho más complicado. Si quieres implementarlo, puedes hacerlo pero post-tarea, ya que implementar esto 1) No seguiría lo que dice el enunciado, lo que puede implicar descuentos y 2) Dificulta la recorrección.

Cualquier duda estaré atento, éxito con la tarea!!

**Comment by FelipeIGS** [comment]
Hola @Benjeeeh 
Cuando dices almacenar informacion en eventos, a que te refieres especificamente? Y me pasa que como decian inicialmente, no es necesaria informacion para iniciar evento, entonces no entiendo cual es la informacion que deberiamos agregar a iniciar evento (como parametro esta nueva info?).
De la misma manera, no se que cosa agregar a self.eventos porque no me quedo claro con lo que dijiste.
Muchas gracias!!

**Comment by Benjeeeh** [comment]
Hola @FelipeIGS
Te recomiendo almacenar por ejemplo los parámetros necesarios de probabilidad junto a un identificador que te diga a que evento pertenece esta probabilidad, y desde este parámetro realizar lo necesario en iniciar evento para que sean utilizados.
