### ISSUE TITLE
Como editar Demo.py

### ISSUE THREAD

**Issue by AngelMatias** [IIC2233/Syllabus#234]
Hace rato lo estoy preguntando y nadie me responde :( .
Estoy super confundido, no entiendo como editar el Demo.py, pues veo metodos como el rotar_pieza de la clase MyInterface que solo tienen un print() y no entiendo como es posible que haga tanto (abrir consola, rotar la imagen, etc)

**Comment by iqacevedo** [comment]
Te respond en #211.

**Comment by AngelMatias** [comment]
man aun no entiendo :( , caxa que intento crear un objeto de la clase MyInterface() y llamar al metodo colocar_pieza(3,5) y me tira este error
<img width="1280" alt="captura de pantalla 2017-09-05 a la s 20 24 24" src="https://user-images.githubusercontent.com/30705123/30087664-48b7eecc-9278-11e7-8d53-90ca023ccbd2.png">

**Comment by Hernan4444** [comment]
@AngelMatias para colocar una pieza primero debes crearla con `nueva_pieza`.
