### ISSUE TITLE
Atributo vida

### ISSUE THREAD

**Issue by monejo1** [IIC2233/Syllabus#234]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

Tengo una duda, cuando estoy definiendo la clase planta, y tengo una atributo vida, ¿deberia poner esto como un parametro? es decir, una planta puede ser creada con menos de su vida maxima, o ¿siempre empieza con la vida maxima y despues sube o baja dependiendo de lo que ocurra en el transcurso del jeugo? Porque lo natural es que empieze con el maximo de vida, pero pregunto por si acaso.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by monejo1** [comment]
Ya caché, ya leí que es un parametro, por que se entrega en el archivo.

**Comment by augustayanez** [comment]
@monejo1 Efectivamente, la vida inicial es entregada en las líneas del archivo plantas.txt!
