### ISSUE TITLE
Probabilidad de expansión a otro país

### ISSUE THREAD

**Issue by anavarro01** [IIC2233/Syllabus#235]
Según el enunciado, la probabilidad de que un pais infecte a uno vecino es:

> min( 0.07 * gente_infectada / (gente_viva * numero_conexiones) )

Esta probabilidad, si se calcula, como se dijo en otra issue, da como máximo 0.07, en el mejor de los casos.
En esa misma issue, alguien dijo que usó 7 en vez de 0.07, pero no fue una respuesta muy clara.
Si, en gente_infectada, se incluyen a la gente_muerta ( que alguna vez ESTUVO infectada), podría ser mas lógica esta probabilidad, con valores mas reales y que permitan la expansión de la enfermedad.

Hay que dejar la probabilidad como esta o hay que modificar algo?

**Comment by rfenzo** [comment]
Me sumo a la pregunta, usando la formula actual, el pais de origen se muere antes de contagiar  a otro pais en la mayoria de mis simulaciones, no se si será por mi codigo o por la formula de contagio.

**Comment by AmbrosioV** [comment]
Me pasa la mismo que a @rfenzo, mueren demasiado rapido. Ademas es a lo maximo 0.07 y considerando que cada pais tiene cmo 25 conexiones deja un valor mucho mas bajo. 
Para testear el codigo subi el 0.07 a valores mayores y recien ahi comenzaba a expandirse algo, y me sumo a si ay que modificar algo para darle mayores probabildiades al contagio

**Comment by anavarro01** [comment]
También note que la infección se expande tan rápido que antes de que se propague, cierran todas las fronteras. O muchas veces pasa que tienes solo un día en el que el porcentaje de infectados esta entre 20 y 40, y hay solo un día posible para contagiar. Como es tan baja la probabilidad de contagio a otro país, (casi) nunca pasa

**Comment by GustavPrudencio** [comment]
+1  los ordenes de las probabilidades no permiten que se expanda la infeccion

**Comment by benjamimo1** [comment]
No se me expanden mis plagas. +1

**Comment by arturodelreal** [comment]
Pueden cambiar esta formula si gustan, pero déjenlo claro en el readme.

**Comment by negutierrez** [comment]
@arturodelreal puedo cambiar solo esta (prob_contagiar), o también ponderar alguna otra, como la probabilidad de descubrir la enfermedad o el progreso de la cura ?

**Comment by arturodelreal** [comment]
@negutierrez solo esta, se avisará si se puede cambiar otra.
