### ISSUE TITLE
¿Si un barco no puede pagar la salida el simulacro continua hasta terminar?

### ISSUE THREAD

**Issue by valedt** [IIC2233/syllabus#235]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, leyendo el enunciado encontré que la explicación sobre los barcos encallados es ambigua. Pues en el caso de que un barco **se encalla** o **no tenga dinero** para pagar la salida ¿Qué sucede con la simulación? **¿Continua funcionando hasta quedar en bancarrota o se termina de una?**

**Comment by santiagovegaf** [comment]
Hola @valedt!

En el caso de encallar un barco tienes dos opciones, no desencallarlo y esperar lentamente a quedar en bancarrota y terminar la simulación, o intentar desencallarlo, donde si no te alcanza el dinero para hacerlo también termina la simulación por bancarrota. 

En el caso de que un barco no tenga dinero para pagar la salida, como puede ser por los piratas, este sale sin pagar y el canal no recibe ingresos. 

Importante destacar que la simulación nunca termina de a una, solo lo hace cuando el canal se queda sin ingresos.

Espero que quede más claro!

**Comment by Juan-Carlos-Ferrer-Barros** [comment]
**Cada barco tiene su propio dinero?** Leí el enunciado y no encontré dónde sale que el barco lo tenga.
Gracias de antemano!

**Comment by santiagovegaf** [comment]
Hola!
 
Modifique un poco la respuesta original para que quede más claro. Sobre el manejo de dinero de los barcos, se aclara en #253

Espero quede más claro!
