### ISSUE TITLE
Dificultad inválida

### ISSUE THREAD

**Issue by coniverav** [IIC2233/Syllabus#235]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Si una dificultad dada en un inicio del juego mediante consola no es válida, debo pedir que se ingrese como input otra opción o simplemente termino la ejecución del programa?

**Comment by CrisDonosoMaass** [comment]
Hola!

¿Cuándo dices una dificultad no valida te refieres que se da un nombre incorrecto como "falcil" o que el entregado tiene malo el formato? Si es el primer caso tú puedes decidir que hacer, si es problema de formato debe terminarse si o si.

Saludos!

**Comment by jofre-bermudez** [comment]
Hola. Me sumo a esta duda porque siento que chocan el enunciado con la pauta.

La pauta da puntos por _El programa se cierra, imprimiendo un mensaje de error, si los archivos de base no cumplen con el formato correcto_ mientras que en el enunciado dice _deberás verificar que se esté recibiendo solamente un parámetro y que corresponda a una de las dificultades válidas, ejecutando el programa si es el caso e imprimiendo un mensaje de error si no lo es._. La pauta dice cerrar el programa, pero el enunciado dice imprimir mensaje de error, lo que deja espacio a que le de la opción al usuario de ingresar nuevamente el parámetro.

¿Por formato haces referencia al contenido del archivo `{dificultad}.txt` o a ingresar varios parámetros u otro error relacionado con la apertura del programa como poner "super facil"?

Según la respuesta anterior me quedó la sensación que cualquier error en ingresar el parámetro (poner "fasil", "super facil" o cualquier otro error de typeo o cantidad) es a nuestro criterio si cerramos el programa o no, pero si el archivo contiene un formato inválido (entendiendo esto como tener un combatiente sin la clase "MAG", por ejemplo) o tiene valores inválidos (vida = -10, por ejemplo) ahí sí o sí hay que cerrar el programa. Espero puedan confirmar si es así.

Muchas gracias!!
