### ISSUE TITLE
Problema de merge en git bash

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2233/Syllabus#235]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema
Hola, tengo un problema con gitbash, en el cual no me deja hacer git pull, por lo que entiendo hice cambios a algún archivo en mi carpeta de syllabus, y ahora cada vez que intento actualizar mi carpeta sylabous local me aparece lo siguiente:

![Error gitbash](https://user-images.githubusercontent.com/62083572/140186215-13048806-124c-490e-987c-d30a6fe4c09a.PNG)

**Comment by Christian-Klempau** [comment]
Hola @vice-rosas99 !
La solución más simple que se me ocurre es volver a clonar el Syllabus :)
Si tienes ningún archivo importante modificado en Syllabus, podrías simplemente borrar la carpeta y volver a clonarla, pero si es que tienes archivos importantes modificados te recomiendo guardarlos en otro lado, y después volver a clonar el repositorio. Suerte! :D

**Comment by vice-rosas99** [comment]
ok gracias
