### ISSUE TITLE
Tamaño de pixeles.

### ISSUE THREAD

**Issue by nhorellana** [IIC2233/syllabus#235]
Hola! Creo que estoy teniendo un problema con el tamaño de las celdas del mapa, instancié el mapa como un qgridlayout de 4x4 y le puse una torreta a una de las celdas pero creo que es gigante en comparación con el personaje, o es normal?
<img width="537" alt="Screen Shot 2019-05-14 at 10 32 18 PM" src="https://user-images.githubusercontent.com/25572781/57744979-5171d800-7699-11e9-8440-1433f19cf900.png">

**Comment by lily416** [comment]
Hola 😄 

Lo que pasa es que debes reescalar las imágenes, ya sea del personaje o de las celdas del mapa.
- Para reescalar el _label_ haces: `setGeometry(pos_x, pos_y, ancho, alto)`
- Para reescalar el _QPixmap_ haces: `scaled(ancho, alto)`

Con eso debes hacer que el personaje (y los enemigos) tengan un tamaño razonable en comparación a las celdas, por ejemplo que tengan la misma altura.

Ojala te sirva 🙏 
Ánimo y éxito con la tarea 🐈 🐧

**Comment by nhorellana** [comment]
Gracias! Y otra cosa, es legal hacer setFixedSize para que no se pueda agrandar la ventana y no tener problemas con la separacion de las celdas?

**Comment by lily416** [comment]
Sí, puedes usar `setFixedSize` mientras que la ventana tenga un tamaño razonable.

Saludos 👋😸
