### ISSUE TITLE
tiempo pits

### ISSUE THREAD

**Issue by mvaldes12** [IIC2233/syllabus#235]
Si por ejemplo, el chasis inicial = 10
Por daños en la carrera quedó en 8
Al entrar a los Pits queda el chasis actual automáticamente = 10
Si decido arreglar el chasis, el chasis actual queda = 10 * efecto
Para calcular el tiempo en los pits se debe hacer chasis inicial - chasis actual, pero según lo calculado esta resta siempre será negativa, lo que da un tiempo negativo.
¿Qué hago? Esta mal lo que entendí? 
gracias

**Comment by pazanelli** [comment]
Sobre lo mismo, el tiempo en los pits se calcula en base al arreglo automático del chasis o tambien considero si le hago una mejora al chasis?:
OP1) tiempo_pits = chasis_inicial - (chasis_reparado * efecto)
OP2) tiempo_pits = chasis_inicial - chasis_reparado

**Comment by cfalvarez2** [comment]
Hola @mvaldes12 y @pazanelli !
Les recomiendo mirar la issue #191 ahí se explica claramente al valor de chasis que deben colocar en la fórmula de tiempo en los ***pits***. Si sus dudas persisten pueden seguir comentando.
Saludos.

**Comment by Jprampad** [comment]
Esa issue no contesta la duda presentada acá... hay problemas en las formulas entregadas en el enunciado
