### ISSUE TITLE
Error de f string al ejecutar codigo en la terminal

### ISSUE THREAD

**Issue by jchamorrou** [IIC2233/syllabus#235]
Hola, queria probar el codigo en la terminal pero me paso esto con hartos f-strings que uso durante el codigo, me dice que esta mal 

![Screen Shot 2020-08-27 at 13 06 06](https://user-images.githubusercontent.com/48953202/91473141-737b7380-e866-11ea-8f18-72543f00acbd.png)
![Screen Shot 2020-08-27 at 13 06 44](https://user-images.githubusercontent.com/48953202/91473153-770efa80-e866-11ea-8f41-9a373ed2f06d.png)

Pero el codigo me corre perfect en vscode, que puedo hacer para no tener que cambiar todos los fstrings?? Gracias

**Comment by DCCollao** [comment]
Hola @jchamorrou!
¿Pasa lo mismo si ejecutas `python3 archivo_a_ejecutar.py`?

**Comment by jchamorrou** [comment]
Ahi funciono! Muchas gracias jejeje

**Comment by DCCollao** [comment]
Eso pasa porque mac trae instalada por defecto la versión 2 de python, y es esa la que se ejecuta al llamar `python`. 
De nada!!
