### ISSUE TITLE
Facilidad encontrar item en arena mojada luego de evento o siempre

### ISSUE THREAD

**Issue by camilamartinf** [IIC2233/Syllabus#235]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, del enunciado entiendo que la condición: "**siempre** un excavador va a poder encontrar un ítem. Además, el ítem encontrado tendrá la misma probabilidad ser un Tesoro o bien un Consumible" **solo aplica** luego de que la arena normal se haya transformado en mojada, es decir, a causa de un evento o tesoro. 
Mi duda es si esta interpretación es correcta o si, mientras la arena sea mojada, aplica esta condición. Por ejemplo, si el torneo iniciara con una arena de tipo mojada, los excavadores **siempre** encontrarán un item. 
Muchas gracias!

**Comment by Benjeeeh** [comment]
Hola!
Lo de al principio es solo para añadir contexto y recalcar de que si llueve en una arena normal esta pasa a mojada. Siempre cuando se trabaje en una arena mojada, se debe aplicar esta condición, ya que es la característica de esta arena, por lo que si el torneo comienza con una de estas arenas debe haber un 100% de probabilidad de encontrar un ítem y aplicar la igualdad de condiciones de que este sea consumible o tesoro.

Éxito.

**Comment by tremendapithon** [comment]
Hola buenas tengo una duda con la cantidad de ítems de la arena mojada, tipo por cada día que pasa yo puedo encontrar en la arena mojada uno ítem o más ítems? Por lo que entiendo, me hace sentido que sea solo uno.
Saludos

**Comment by Benjeeeh** [comment]
@tremendapithon Como es un atributo de los excavadores, y existe un 100% de probabilidad de encontrar algo, debería obtenerse un ítem por excavador (que haya cavado y no esté descansando).

**Comment by FelipeIGS** [comment]
Hola @Benjeeeh !
Tengo una duda respecto a como acceder a los excavadores de Torneo que es necesaria para que cada excavador encuentre un item en arena mojada, ya que hasta ahora las clases (Arena y sus tipos, excavadores y sus tipos) las tengo creadas fuera de Torneo y no puedo acceder a tal lista de excavadores. Lo que se me ocurre es crear las clases dentro de Torneo, pero como accedería a la lista necesaria, con Torneo.excavadores?? 

Una alternativa seria checkear si la arena es mojada despues de ver si ocurre un evento en simular_dia. Si lo es, que cada uno encuentre un item. Es legal esta opcion?

Además, que tan importante es que cree las clases adentro de Torneo y que errores o modificaciones podria conllevar???

Muchas gracias!
