### ISSUE TITLE
¿Es legal usar tareas anteriores?

### ISSUE THREAD

**Issue by leonardosuarez777** [IIC2233/Syllabus#235]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Contenido

¡Hola! Me surge la duda de si usar código de tareas anteriores es posible. Por ejemplo, imaginemos que no sé hacer algo en una tarea y quisiera revisar si hubo algo parecido en semestres pasados. Ahora supongamos que yo contacto a alguien, que dio el ramo en un año N, me muestra sus tareas y me doy cuenta que una de sus tareas se trataba de la fauna chilena y tiene un método de ordenar_fauna() que me parece bastante útil para yo usarlo en mi tarea cambiado específicamente para este caso, por ejemplo, el mismo código, pero pongo ordenar_plantas(). Si cito esto en mi código como Tarea "Nombre de la persona" Año N Semestre 2, ¿es legal hacerlo? O va en contra de la ética igualmente.
Gracias de antemano.
Saludos,
Leonardo

**Comment by PkAlvaro** [comment]
Buenas tardes @leonardosuarez777, ¿como estás? 😄 

Considerando lo que expones y en citando al reglamento del curso, este indica lo siguiente en base a lo que estás preguntando:

1. "En primer lugar, se permite el uso de codigo encontrado en internet u otra fuente 
de informacion similar, **siempre y cuando su autor sea externo al semestre actual del curso, y su publicacion sea previa a la liberacion del enunciado.**"

2. "Por 
ultimo, **el compartir o utilizar codigo correspondiente a una evaluacion actual o pasada del curso** y el uso de herramientas de generacion de codigo se encuentran estrictamente prohibidos y seran considerados como faltas a 
la etica."

Lo que te quiero decir con esto es lo que consultas iría en contra del reglamento del curso y podrías estar faltando a la ética, por lo que te sugiero que no uses esa función aún cuando la tarea de ese entonces sea otra.

Espero que hayas podido resolver tu duda y desearte éxito en tu T2. Si necesitas más información al respecto te sugiero revisar el programa del curso que se encuentra en el Syllabus.

Ten una buena tarde! 👍

**Comment by Yeps3nM** [comment]
Hola! Tampoco está permitido usar tareas que hayamos realizado nosotros si es que no es primera vez que estamos en el ramo? 

Saludos

**Comment by PkAlvaro** [comment]
Hola @Yeps3nM! Lamentablemente tampoco es posible ya que eso se considera autoplagio y es técnicamente material del curso igualmente.

Saludos!

**Comment by Hernan4444** [comment]
Hola @Yeps3nM 

Aquí hubo un pequeño error en la respuesta. Para efectos **de este curso**, si es que es no es tu primera vez haciendo el curso y quieres aprovechar algo que **tu desarrollaste** un semestre anterior, si puedes. No obstante, debes tener cuidado con:

1. Que el código original haya sido **100% de tu autoría**. En este sentido, si usas una tarea tuya de otro semestre, pero esa tarea no fue creada 100% por ti (por ejemplo, se hizo alguna parte con IA y/o ayuda de terceros), será penalizado este semestre por falta a la ética e integridad académica. Esto aplica sin importar si ese otro semestre no fue detectada la falta. 

2. Se aplican las mismas restricciones a cualquier material externo que uses. En este sentido: que entiendas en su totalidad ese código, seas capas de explicarlo y si modificamos algo de este, sepas qué ocurre. En consecuencia, decir algo como: "fue un código que hice otro semestre, pero ahora no entiendo qué hace" no es válido, y en ese caso, te recomendamos no utilizarlo. 

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito en tu tarea! 🦖
Saludosヾ(＾-＾)ノ
