### ISSUE TITLE
Duda Semana santa

### ISSUE THREAD

**Issue by javiermarhuich** [IIC2233/syllabus#236]
Hola.
Por casualidad la próxima semana habrá alguna actividad? Puesto a que la próxima semana es semana santa y normalmente la U cesaba actividades los jueves a las 13:00 esa semana.
Saludos.

**Comment by aaossa** [comment]
Hola @javiermarhuich , según nuestro calendario (disponible en el programa y la página del curso) no tendremos actividad precisamente por la razón que comentas 👌
