### ISSUE TITLE
Metodo setColumnStretch/setRowStretch

### ISSUE THREAD

**Issue by LucianoDavico** [IIC2233/syllabus#236]
Hola!

Hice el mapa del juego con QGridLayout y tengo el problema de que cuando se maximiza la imagen se separan proporcionalmente las imágenes. Sé que el problema se arregla con los métodos `setColumnStretch()` y `setRowStretch()`, los cuales "fijan" la grilla, pero python (pycharm) no me los reconoce al momento de querer ocuparlos. Lo raro es que al tratar de importar el método directamente como `from PyQt5.QtWidgets.QGridLayout import setColumnStretch` ahí me aparece que existe, pero luego no me lo reconoce en el código.

**Comment by jeschuwirth** [comment]
Saludos,

Si no me equivoco, setColumnStretch() es un método de la clase .QGridLayout, así que no es necesario que importes nada y prueba con la siguiente linea:

`tu_grilla.setColumnStretch(int numero_columna, int stretch)`

Ojalá te sirva, si no funciona comenta en la issue y buscaré un poco más cual puede ser el problema :)

Suerte en la tarea !

**Comment by LucianoDavico** [comment]
Hola, intenté ocupar el método de esa forma pero no me lo reconoció. De todas maneras dejé de ocupar QGridLayout para generar el mapa así que me ahorré el problema : )

Gracias!
