### ISSUE TITLE
método __iter__

### ISSUE THREAD

**Issue by Nicolasvegam** [IIC2233/Syllabus#236]
Hola,
No logro hacer recorrer un for dentro de otro con mis listas, sólo me toma uno (y he intentado formular de varias formas el __next__ y el __iter__)

    def __iter__(self):

        return self

    def __next__(self):
        if self.cabeza is None:
            raise StopIteration()

        result = self.cabeza.valor
        self.cabeza = self.cabeza.siguiente
        
        return result

Al hacer esto:

    u=Lista(10,3,5,6,4,5,6,6)
    p=Lista(1,2,4,5,6)
    for i in u:

        for t in p:
            print(i,t)

Sólo recorre el primero de la lista u (10) con todos los elementos de p, pero no sigue entrando para los otros elementos de p

**Comment by glbello** [comment]
¿Por qué cerraron esta issue? ¿ha hecho algo incorrecto?

**Comment by glbello** [comment]
Perdon ahora recien vi que el creador de esta issue fue quien la cerro

**Comment by glbello** [comment]
Perdon ahora recien vi que el creador de esta issue fue quien la cerro
