### ISSUE TITLE
Funciones instanciadas en diccionario

### ISSUE THREAD

**Issue by mamitagolosa** [IIC2233/syllabus#236]
Hola, tengo una duda de código:
si inicio un diccionario del tipo:
`diccionario = { 'funcion_mejora_1': Vehiculo.mejorar_1(parametro),
                          funcion_mejora_2': Vehiculo.mejorar_2(parametro)
                          funcion_mejora_3': Vehiculo.mejorar_3(parametro)}`

para después usar esas funciones ya instanciadas sacándolas por el key `funcion_mejora_x`, ¿las funciones se instacian sólo si es que saco la función del diccionario, o al crear el diccionario los cambios son hechos en el objeto al llamar a la función ahí dentro?

**Comment by gatochico** [comment]
Buena pregunta! Probemos a ver que pasa:

![image](https://user-images.githubusercontent.com/37161120/64695937-a10fb700-d473-11e9-97a8-9a034642a3a9.png)
![image](https://user-images.githubusercontent.com/37161120/64695952-abca4c00-d473-11e9-9787-d8f5b8e768f8.png)
Puedes ver que no imprimió nada! Así que no se llamo al instanciar el diccionario con ella dentro. Ahora, probemos llamarla:
![image](https://user-images.githubusercontent.com/37161120/64696011-cac8de00-d473-11e9-98f2-89db8f788d08.png)
![image](https://user-images.githubusercontent.com/37161120/64696024-d0262880-d473-11e9-8233-c8735c07b214.png)
Aquí si se imprimió algo en la consola (: 

Por lo tanto, la función no es llamada cuando creas el diccionario, sino solo cuando llamas a la función con su llave en específico. 

Saludos! :cat:
