### ISSUE TITLE
Extender property para excavador híbrido

### ISSUE THREAD

**Issue by BenzoylMorexide** [IIC2233/Syllabus#236]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! mi duda tiene que ver con herencia y extensión de properties. Básicamente inicializo la energía en la clase abstracta Excavador, donde tengo además la property getter y setter, como suele hacerse. Luego, se pide en el enunciado que para el excavador híbrido no pueda bajar la energía de 0, por lo que intento hacer override del set, pero no funciona. Intenté evitar el mangling con _Excavador.__energia = value, pero aún así no funciona. 
Muchas gracias de antemano!

**Comment by panchouc** [comment]
Recuerda que si pones un atributo como `self.__energia`, Python lo sobreescribe con otro nombre, intenta probando eliminando los dobles underscore y deja uno solo, para que quede, por ejemplo, como `self._energia`

**Comment by BenzoylMorexide** [comment]
Hola! no entiendo bien dónde exactamente debería sacar los dos underscore y si dejo solamente uno, debo cambiarlo todo para abajo también? tipo incluyendo los del método getter de la clase tanto abstracta:
`@property
    def energia(self):
          return self._energia`
como los de la hija?

**Comment by panchouc** [comment]
Sería en todas las partes en las que utilizas los atributos con dos underscore, con eso se debería arreglar. Aquí igual te dejo un enlace de stackoverflow donde hablan más sobre esto https://stackoverflow.com/questions/1301346/what-is-the-meaning-of-single-and-double-underscore-before-an-object-name

**Comment by luc0i** [comment]
Hola! Yo también tengo una duda con este tema.
Si defino la clase Excavador con una property abstracta de energía, es válido definir nuevamente esta property en una clase "nieta" de Excavador, como lo sería ExcavadorHíbrido?
Me entra la duda porque ExcavadorHibrido no hereda directamente desde Excavador.
Gracias!

**Comment by panchouc** [comment]
Si es que ExcavadorHíbrido hereda de los otros, y estas últimas clases heredan de Excavador, entonces debería estar disponible esta property en la clase de ExcavadorHíbrido si es que están definidas en las clases de las cuales hereda sin necesidad de redefinirlo nuevamente. Pero lo puedes hacer si lo crees necesario.
