### ISSUE TITLE
Ejercicio propuesto 2.1 Semana 2

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#236]
Hola, no entendí muy bien el uso de properties. Para este ejercicio debo crear un nuevo atributo "privado" para la depreciación acumulada?
Otra duda, cuando ya tengo definido el setter de depreciacion_acumulada, como debo llamar a esta funcion para que me entregue un valor? Por ejemplo, debería hacer "barato.depreciacion_acumulada(2020)"?

**Comment by MatiasDuhalde** [comment]
Hola @En-clases !

Respondiendo tu pregunta, no, no es necesario que creen un nuevo atributo privado para guardar la depreciación acumulada.
Acabo de responder una issue muy similar que te puede ayudar aquí: #218 .

Si sigues con dudas, puedes comentar allá!
