### ISSUE TITLE
Duda  con los archivos que tienens que ser ignorados .gitignore 

### ISSUE THREAD

**Issue by jtvaldivia** [IIC2233/Syllabus#236]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, mi duda es, los archivos como puntajes.txt se deben ignorar?
que como no especifican en el enunciado que este tipo de archivos (los .txt) se deban ignorar.
De ante mano gracias por responder.

**Comment by rodrigobj99** [comment]
Hola @jtvaldivia ! Tal como lo mencionas, los archivos que deben ser ignorados según el enunciado son: 
- El enunciado.
- La carpeta de sprites entregada junto al enunciado.
- La carpeta de música entregada junto al enunciado.

Por lo que **no** debes ignorar el archivo _puntajes.txt_, ya que no es mencionado en la parte correspondiente a _.gitignore_ del enunciado.

**Comment by narispe** [comment]
Hola, en caso que modifiquemos o agreguemos imágenes a la carpeta sprites, ¿debemos mencionar esto en el readme y podríamos subir toda la carpeta para asegurar que el programa funcione?

**Comment by rodrigobj99** [comment]
Hola @narispe ! En ese caso puedes agregar las sprites en otra carpeta y subirla o agregarlas en sprites y subirla también, en cualquier caso debes ignorar todo lo demas y dejarlo especificado en el Readme.
