### ISSUE TITLE
Implementacion aumento potencilantro

### ISSUE THREAD

**Issue by monejo1** [IIC2233/Syllabus#236]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

En la distribución de puntaje en la sección de entidades sale que tengo que implementar el aumento de potencial que dan los potencilantros dentro de la entidad, entonces yo pienso que tengo que hacerlo de algún modo dentro de la clase. Pensaba implementar una función o algo, pero no tengo ni idea de como hacerlo porque la clase no tiene acceso al jardin ni las posiciones de las otras plantas alrededor del potencilantro. Mi solución sería hacer el aumento a la bruta dentro del archivo del menú pero no es la idea. ¿Cómo se implementa esto?

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by AndreaVict** [comment]
Hola @monejo1. Es parte de la evaluación el que encuentren la manera de implementar lo que se pide en el enunciado, por lo que puedes realizar el aumento de potencial como estimes correcto, siempre y cuando se cumpla lo estipulado en el enunciado. Mucha suerte :3
