### ISSUE TITLE
Tamaño de ventana, y posibilidad de expandir

### ISSUE THREAD

**Issue by VicenteGarayR** [IIC2233/Syllabus#236]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Mi duda es sobre si es necesario poder expandir las ventanas, por ejemplo mis ventanas de inicio tienen un tamaño determinado y su uno las expande los elementos no se mueven, y también me gustaría saber que tamaño se recomienda para la ventana de juego, si es necesario que sea a pantalla completa o puede ser cualquier tamaño

**Comment by PedroDP99** [comment]
Hola @VicenteGarayR  @ibgarrido!
Efectivamente no es necesario que sean expandibles. Lo importante para el tamaño de la ventana es fijarte que te quepan todos los elementos que se piden sin superponerse. Finalmente, queda a tu criterio si la quieres hacer a pantalla completa o no.
