### ISSUE TITLE
Dudas varias dudas

### ISSUE THREAD

**Issue by gbordoni** [IIC2233/Syllabus#237]
Buena cabros, tengo un par de dudas:

1. Implemente una lista ligada. Solo eso. Lei lo que hace el `iter` y el `next `pero no lo entendi completamente, asi que les pregunto a ustedes: tengo que implementar `iter `y `next` en mi lista ligada?

2. En la estadistica de `Muertes e Infecciones por dia`, es necesario imprimir dia por día el numero de infectados y muertos? Onda, `Dia 0: Infectados : 1, Muertos: 0` ? Y si es así, mostramos el numero de personas que se infectaron/murieron ese mismo día, o el número total de personas infectadas/muertas que habían en ese día?

3. Los archivos en donde guarde los datos para guardar el estado de una partida tienen que ser .csv? O pueden ser .txt nomá?

Saludos y gracias de antemano

**Comment by FernandoPieressa** [comment]
Hola!

1) si tienes que implementar iter y next en alguna estructura de datos como tu lista ligada, pero no necesariamente en la misma estructura

2)en muertes y infecciones por dia se muestra cuantos se infectaron y murieron especificamente en ese dia, la informacion de total hasta el dia actual es en otra consulta. Y como no esta especificado, puedes imprimir todo de todos los dias o dejar que el usuario eliga un dia para entregar los datos.


3) tiene que ser todo con .csv

Saludos!

**Comment by gbordoni** [comment]
@FernandoPieressa Gracias por las respuestas! Pero sabes que me pasa algo raro con el iter y el next. Cree una lista ligada y al hacer `iter(lista ligada)`, esto funciona y transforma mi lista ligada en un iterador (y obviamente despues tambien puedo hacer `next(lista ligada)` , todo esto sin haberlo implementado en mi clase ListaLigada. ¿Quizas esto funciona porque iter() solo necesita que este implementado el  `__getitem__` para transformar un iterable en un iterador??

En fin, mi problema es que el iter funciona sin haberlo implementado, y la lista ligada es la unica estructura que implemente para hacer la tarea, y no quiero que me bajen puntos por no haber implementado el iter.

**Comment by Hernan4444** [comment]
@gbordoni solo por si acaso, te funciona hacer `next(lista ligada)`
Espero tu respuesta

Saludos!!

**Comment by gbordoni** [comment]
@Hernan4444 Si no hago `iter(lista ligada)` primero, no.

**Comment by Hernan4444** [comment]
Lo que sucede es tal como dices, `iter(lista)` funciona teniendo el `getitem` sobreescrito, esto es porque con `getitem` se logra interpresat tu lista como una secuencia (uno de los requisitos para `iter`) pero al hacer eso estas **creando un iterador a partir de tu lista**, pero tu lista no es un iterador. Eso se comprueba con el `next(lista ligada)` donde el next necesita que su argumento sea un iterador. 
Para no perder puntaje, te sugiero que implementes como corresponde el metodo next para poder hacer `next(lista ligada)` y con eso demuestras que tu lista es un iterador :smile: 

Saludos!
