### ISSUE TITLE
Hackerman: Aspectos legales

### ISSUE THREAD

**Issue by geduran** [IIC2233/Syllabus#237]
Hola, tengo una duda de enunciado respecto a la parte Hackerman. Resulta que estoy teniendo algunos problemas con respecto a programar mis estructuras de datos porque es muy lento trabajar sobre 5500 datos y cada vez que corro el programa se demora varios minutos (como a otros también les ha pasado). Obviamente uno piensa que quizás es buena opción omitir la parte hackerman y hacer el resto de la tarea (yolo) con el fin de poder tener un mejor resultado.

Mi pregunta es: se van a dar máximo puntaje en ese 30% de hackerman solamente por no utilizar estructuras de dato de Python, aunque el programa sea un bodrio? O va de la mano con el resultado que uno obtenga en el programa en general?

**Comment by Hernan4444** [comment]
@geduran,
  El 30% de hackerman es por programar **debidamente** las estructuras de datos y crear los método solicitados. Pero tal como está en el enunciado, Restricciones y alcances, 
> No se corregirán partes de código que utilicen estructuradas dadas por python....

Por lo tanto, deben programarlas para ser utilizadas en toda la tarea, pero el puntaje de hacerlas bien junto a los métodos solicitados estará en hackerman. No puedo especificar más de como se dará el puntaje.

Saludos ✌️
