### ISSUE TITLE
Valor armadura en Defensauce

### ISSUE THREAD

**Issue by monejo1** [IIC2233/Syllabus#237]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

En el enunciado dice que armadura es un valor int de defensauce, y yo lo puse como parametro de la clase adicional. Lo que pasa es que no dice en el enunciado si tenemos que darle un valor nosotros a esta armadura, y en plantas.txt los defensauces reciben la misma cantidad de valores que las otras plantas. ¿Puedo suponer entonces que armadura es un valor que yo declaro en parametros.py? 

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by rodrigoaguilera15** [comment]
Hola, qué tal? Exactamente, todos los valores que no estén dados por los archivos deben ser declarados en parametros.py. De hecho, todos los valores fijos o constantes, tanto si están dados por enunciado como si, en su defecto, eres libre de elegirlos, deben declararse en parámetros y no en otro módulo. Espero que mi respuesta sea satisfactoria.
