### ISSUE TITLE
uso de QRect

### ISSUE THREAD

**Issue by tnmarin** [IIC2233/syllabus#237]
hola, 
estoy tratando de comprobar colisiones de muros con mi personaje usando Qrect, pero no logro pillar ejemplos o información de como usarlo, si hago que mis clases personaje y muro lo hereden no me funciona llamar a la función intersect(), tienen alguna sugerencia de como se usan?.

gracias

**Comment by catorres8** [comment]
Hola, yo tenía/tengo el mismo problema y para no calentarme más las cabeza (luego de mirar mucho la documentación), hice que los objetos se enviaran los datos posicionales (x, y, anchura) y cuando son recibidos creo en el momento un objeto QRect(x, y, n, n) para usar intersects() (o 2 de ser necesario)
Ojalá esto te ayude

**Comment by lily416** [comment]
Es como dice @catorres8 (Te ganaste una estrellita 🌟)

Debes usar los `QRect` de los dos objetos para ver si estos se intersectan, para esto tienes dos opciones:
1. Mandar los datos del `QRect` (pos_x, pos_y, ancho, alto), creas los dos `QRect` en la función y compararlos.
1. Mandar directamente el `QRect` o accedes a este desde la función y así evitas tener que crearlos en la función.

Es importante que aprendan a buscar ejemplo y leer la documentación de [PyQt5](https://www.riverbankcomputing.com/static/Docs/PyQt5/) o [Qt5](https://doc.qt.io/qt-5/) para que así puedan descubrir y aplicar las distintas funcionalidades de está librería. 😄 

Saludos 👋🐈🐧
