### ISSUE TITLE
Lanzaguisante perma-disparo

### ISSUE THREAD

**Issue by 3rdPix** [IIC2233/Syllabus#237]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado, cuando se describe a los lanzaguistantes, indica que estos "dispara proyectiles simples cada vez que pasa un tiempo INTERVALO_DISPARO ". Esto quiere decir, que apenas la planta ingrese en el campo de juego, comienza a disparar, sin importar **la existencia de zombies en la fila respectiva**. Es decir, no es necesario verificar si hay, o no, zombies antes de disparar, la planta solo dispara y si le llega a alguien, genial, sino, da igual.

**Comment by iespinazac** [comment]
Hola @3rdPix!
Como bien dices, la planta empieza a disparar con cierto intervalo cuando ingresa al campo de juego y no importa si hay o no zombies, por lo que no es necesario verificar previamente si hay zombies en el carril.
