### ISSUE TITLE
Archivos por datos inválidos

### ISSUE THREAD

**Issue by coniverav** [IIC2233/Syllabus#237]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Cuando en la sección 6.1 de archivos se menciona que se debe "informar al usuario del error", basta con mencionar que existen datos no válidos en el archivo o es necesario decir cuál fue el error? (con esto último me refiero, por ejemplo, a "El dato 'Poder 11' no es válido porque poder debe estar entre el rango 1 a 10")

<img width="676" alt="image" src="https://github.com/IIC2233/Syllabus/assets/162245893/bae585d4-eeed-451a-8854-1d7c13e66e51">

Por otro lado, quisiera saber si uno de los datos puede ser un float? en ese caso, tengo que determinarlo como dato inválido (dado que solo se admiten int) o puedo truncarlo y hacerlo válido como int? 
Con truncar me refiero a, por ejemplo:
`x = 1.9 # float `
`x= int(x)`

**Comment by CrisDonosoMaass** [comment]
Hola!

Tu puedes decidir como informar el fallo del archivo, pero basta con sólo decir que fallo.

Respecto a tu segunda duda, en caso de haber un float debe ser considerado como invalido y no debe ser corregido.

Espero haber respondido tu duda!
