### ISSUE TITLE
Pedido para tener las soluciones a las actividades 

### ISSUE THREAD

**Issue by ConiCollector** [IIC2233/syllabus#237]
Estimados profesores

En Discord leí que un compañero preguntó si era posible tener las soluciones a las actividades una vez pasado el horario de entrega. Personalmente creo seria una buena idea, dado que, a veces no se alcanza a terminar la actividad y quedan dudas de como se debe terminar de forma correcta o que fue lo que se implemento de forma incorrecta. Además, en vez de responder varios correos con dudas de las actividades sería más eficiente liberar la solución en formato guiado. De modo que, la mayoría de las dudas serian resueltas y sería otro buen material educativo especifico para el curso. No obstante, si no es posible entiendo perfectamente la decisión del cuerpo docente.

Agradece y se despide
Constanza

**Comment by entamburini** [comment]
Hola @ConiCollector 

No soy profesor jajaja, de todas formas te responderé porque esto ha sido una petición que ocurre todos los semestres desde que soy alumno. 

La respuesta como ayudante que te puedo dar, es que no se puede porque nos basamos tanto en actividades anteriores como en la creatividad de cada ayudante para hacer las actividades. Por lo tanto subir la solución exigiría a los ayudantes a hacer nuevos problemas que seguramente sean más difíciles para los compañeros que vienen al futuro, complicando artificialmente el ramo con eso. 

Otro motivo y el de real peso aquí, es que en la programación no hay un solo mecanismo para llegar a una respuesta. Códigos completamente diferentes pueden dar como resultado el mismo output (de hecho, por eso es relativamente fácil detectar copia). Entonces darles una solución puede limitarlos a creer que existe una manera "buena" de hacer las cosas y eso en este mundo no es así.

Y por último, este ramo es poco convencional, acá si puedes comprobar si una respuesta está bien o no corriendo tu código, de hecho buena cantidad de respuestas son del tipo "¿has intentado corriendo el código?" porque así es como se aprende en programación :D 

Por estas razones (y quizás alguna más que se me olvida), no se han hecho públicas las soluciones de las actividades desde el 2015-2 hasta la fecha :wink: 

Espero que estés bien! :)

**Comment by Araos827** [comment]
Hola! me imagino que pasa lo mismo con los ejercicios propuestos no?

**Comment by entamburini** [comment]
Así es @Araos827, 

Los ejercicios propuestos son otra instancia de práctica que se implemetó el semestre pasado y que creemos que ha funcionado (al menos así nos lo han hecho saber los compañeros que estuvieron antes). Subiéndoles la solución caeríamos en el segundo punto que expliqué arriba :o

Y no puedo dejar de reiterar que corriendo el código puedes darte cuenta si el programa que haces está bueno o no, por eso no es necesario una pauta :)

**Comment by fdoflorenzano** [comment]
Hola,

Para complementar lo que dijo @entamburini, queríamos escribir de parte de los profesores, debido a que no hemos tenido oportunidades presenciales para comentar al respecto este semeste.

Los aspectos importantes a destacar son los que están relacionados a su aprendizaje. Como mencionado en la primera clase, este es un curso de programación, y esta solo se aprende de una forma: programando. La realidad es que leyendo y revisando ejemplos solo te puede llegar hasta cierto punto como desarrollador, y es mediante la práctica y prueba y error cuando más se aprende.

Eso último, más los conceptos abstractos que se transmiten en el curso, son lo que en nuestra experiencia diferencian a un **programador** de un **desarrollador**, y que apuntamos a que lleguen todos los estudiantes del curso.

El plantear soluciones lamentablemente no incentiva este tipo de aprendizaje al que apuntamos en el curso. La justificación usual es para tener más ejemplos de aplicación, pero esto ya se cumple con el extenso material que se otorga mediante los contenidos, ejercicios propuestos y ayudantías, sin mencionar el material de semestres pasados que también está disponible.

Finalmente, dudas más aterrizadas siempre se pueden hacen en el foro del curso, y estamos atentos y atentas en el equipo docente para ojalá dejar claro las ideas y mejorar nuestro material en base a eso 😄. Esta semana que está terminando recibimos varias dudas en forma de *issue*, que es exactamente lo que esperamos cuando tienen dudas 😊.

Espero se entienda el espíritu. Si quieren continuar con este dialogo, somos todo oídos.

Saludos.

**Comment by sgallardo95** [comment]
hola, no entendí la diferencia entre programador y desarrollador :(

**Comment by ConiCollector** [comment]
Hola

Gracias por las aclaraciones, ahora entiendo varias cosas y para futuras dudas no dudare tanto en hacer un issues.

Saludos

**Comment by fdoflorenzano** [comment]
Hola @sgallardo95,

Sí, la redacción de esa parte está cuestionable. Un(a) programador(a) podría verse como una persona que es capaz de escribir código y solucionar problemas mediante prueba y error constante, mientras que desarrollador(a) apoya ese proceso con conceptos teóricos que le ayudan a generar mejores soluciones. Ambos escriben código, pero el nivel de entendimiento de soluciones es distinto.

De todas formas, esta es una definición personal de los términos. El punto es que en el curso queremos impartir ambas partes de la disciplina: el aprendizaje mediante prueba y error de código, apoyado de ideas y conceptos teóricos que enriquezcan este proceso y la creación de soluciones.

Espero se entienda,
Saludos.

**Comment by Pelaysen** [comment]
Perdón, no sé si interpreté mal esto, citando arriba: "subir la solución exigiría a los ayudantes a hacer nuevos problemas que seguramente sean más difíciles para los compañeros que vienen al futuro, complicando artificialmente el ramo con eso.", entendí que si entregan las soluciones, el ramo sería más fácil por lo que tendrían que hacer actividades más difíciles y así el ramo más difícil. 

El objetivo de pasar un ramo es aprender, no pasar un ramo difícil, al igual que la carrera forma ingenieros y no gente con un titulo en la mano.

"en la programación no hay un solo mecanismo para llegar a una respuesta. Códigos completamente diferentes pueden dar como resultado el mismo output (de hecho, por eso es relativamente fácil detectar copia). Entonces darles una solución puede limitarlos a creer que existe una manera "buena" de hacer las cosas y eso en este mundo no es así."

Es verdad que no existe una manera "buena" de hacer las cosas pero si existen unas maneras más optimas o mejores que otras, por esto es que solicitamos las soluciones.

disculpen las molestias.

**Comment by fdoflorenzano** [comment]
Hola @Pelaysen,

Responderé en orden:

>  entendí que si entregan las soluciones, el ramo sería más fácil por lo que tendrían que hacer actividades más difíciles y así el ramo más difícil.

Esa extrapolación no la compartimos, @entamburini se refiere a que los ejercicios posibles serían cada vez más artificiales y difíciles de entender. Eso hace más complejo el curso en términos de formulación docente. De todas formas, no creemos haya una correspondencia entre publicación de soluciones con la "dificultad" del curso desde la vista del estudiante.

> El objetivo de pasar un ramo es aprender, no pasar un ramo difícil, al igual que la carrera forma ingenieros y no gente con un titulo en la mano.

Compartimos tu visión sobre el aprendizaje de un curso, y como comentado en nuestra aclaración previa, es por esto que no subimos soluciones. Consideramos que la experiencia formativa que involucra probar el código y alternativas es más rica que revisar o comparar con una solución. Este proceso se puede cerrar completamente mediante las guías explicitadas en los cierres o simplemente preguntando en el foro del curso.

> Es verdad que no existe una manera "buena" de hacer las cosas pero si existen unas maneras más optimas o mejores que otras, por esto es que solicitamos las soluciones.

Nuevamente, no encontramos una real consecuencia entre la razón que indicas y la necesidad de soluciones. El publicar soluciones no implica que un estudiante va a conocer la forma de realizarlo más optima ni tampoco todas las alternativas. En el curso nos enfocamos más en explorar prácticamente y valorar la diversidad de soluciones de cada persona. Esto último si incentiva el conocimiento de alternativas y potencialmente conocer mejores soluciones. Además, las correcciones ya vendrán con indicaciones de mejoramiento de prácticas, que también apuntan en esa dirección.

Espero se entienda, cualquier duda nos avisas.
Saludos.
