### ISSUE TITLE
Duda sobre salto de Froggy

### ISSUE THREAD

**Issue by simonmb12** [IIC2233/Syllabus#237]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! En la parte del salto de la rana, se dice que esta funcionalidad existe para poder atravesar los troncos. Cuando uno enfrenta el río, solo puede salir de un tronco saltando hacia adelante y hacia atrás. Mi duda es si se puede implementar el salto únicamente para la sección del río. De otra forma, la parte de la carretera se vuelve demasiado trivial. En el enunciado no queda muy claro en que caso implementar esta funcionalidad, ya que también se dice que pueda saltar lateralmente (izq, der), pero eso no se puede hacer en el río, y en la carretera me parece innecesario.
### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by sebaguerrap** [comment]
Hola @simonmb12 ! Efectivamente la funcionalidad se pensó para ser usada en el río pero por temas de simplicidad de la tarea se dejó que se usara siempre. Es por esto que el salto debe estar implementado en cualquier parte del nivel y no solo en el río.

**Comment by Dafnemami** [comment]
@sebaguerrap Holis, ¿es válido implementar solo el salto hacia adelante y atrás para todo el mapa?, dejando de lado el salto hacia los lados.

**Comment by sebaguerrap** [comment]
Hola @Dafnemami ! En el enunciado se especfica que el salto debe poderse efectuar hacia todos los lados. Sin embargo, en la distribución de puntaje dice que si se está sobre un tronco solo se puede saltar hacia adelante o atrás. Es por esto que sí se debe implementar el salto para los lados en el resto del mapa (todas partes menos en los troncos).

**Comment by Dafnemami** [comment]
https://github.com/IIC2233/Syllabus/issues/239#issuecomment-962511473 En esa respuesta dijeron que se puede implementar el salto hacia todos los lados, no diagonal, en el todos los lugares del mapa. Es distinto a lo que me dices tú.
