### ISSUE TITLE
Duda class vehiculo

### ISSUE THREAD

**Issue by Afro27** [IIC2233/syllabus#237]
Es necesario crear una clase distinta para cada tipo de vehiculo? Estaba pensando que lo unico que diferencia a los vehiculos es categoria y motor o zapatillas. Por lo tanto podria simplemente crear un atributo bool que diga si el vehiculo tiene motor o no y asi me ahorraria tener que crear 4 clases distintas, lo cual ocuparia muchas lineas. Si bien dicen que es necesario para evaluar herencia, esto puede ser evaluado, en otras clases como pistas o menus. En fin mi pregunta es si se penalizaria no usar herencia en vehiculos, siendo que ocupo herencia para otras clases.

**Comment by jaromero6** [comment]
Hola!
Respecto a tu duda no puedo responder directamente un si o un no a si es necesario crear una clase distinta para cada vehículo, te recomendaría mirar esta #210 issue para orientarte a ver si lo que estás haciendo está bien o no.
Respeto al último punto, hay entidades en el enunciado que están pensadas para que se use herencia, por lo que ni usarlas en esta si provocaría una penalización en puntaje, aún cuando existan otras funcionalidades que puedan haber usado herencia en tu programa.
Espero haber respondido tu pregunta

**Comment by Afro27** [comment]
Citando la issue #210 "¿Debe ser toda entidad del problema que busco modelar una clase? Dependerá de como quieras que dicha entidad se relacione con el resto de entidades en tú programa.". No creo que eso sea asi, ya que el programa lo debemos hacer segun la pauta que se sube y según lo que ustedes nos piden. No creo que la unica forma de evaluar herencia sea a traves de los vehiculos. Si bien se supone el uso de herencia de clases deberia ahorrar codigo. En el caso de los vehiculos, pude implementar ambos metodos y resulta considerablemente mas corto y a la vez funcional no utilizar herencia para los vehiculos. No me parece que se deba descontar puntaje.

**Comment by KnowYourselves** [comment]
Hola @Afro27!

Tienes la razón!, Efectivamente, hay múltiples formas de modelar este problema y múltiples formas en las que podemos evaluar herencia, sin embargo, para simplificar el proceso de corrección hicimos el problema de forma tal de que no haya muchas formas correctas de modelarlo.

En cuanto al descontar puntaje, **si, se debe descontar en este caso**. Las razones son dos:

1. **Esta tarea evalúa específicamente modelación orientada a objetos**, es decir, nosotros buscamos que nos muestres que lograste entender como encapsular funcionalidades haciendo uso de clases y relacionándolas correctamente. Es cierto, se puede lograr algo similar con `namedtuples` o ciertas estructuras de datos, pero el enfoque de la evaluación es objetos.

2. **En este curso se busca que aprendan buenas prácticas de programación**, en ese sentido, una de las mejores prácticas a aplicar en programación es entender que **ningún programa es estático**. No existe un caso donde tu hagas un programa y nunca más tengas que cambiarlo, por lo cual una buena modelación **también es fácil de expandir y modificar**.  <br>
En este caso efectivamente no hay diferencias muy grandes entre cada tipo de vehículo, pero, ¿Qué pasaría si en una siguiente versión del juego se agregaran funcionalidades a cada vehículo, únicas y más específicas?, ¿O si se agregaran 5 nuevos vehículos? ¿Sería fácil implementar estos cambios con tu actual modelación, o sería más fácil hacerlo con herencia?

En conclusión, la idea de programación orientada a objetos no es ahorrar lineas de código, o hacer código eficiente en términos del tiempo de ejecución, la idea es poder hacer un código con las **funcionalidades claramente encapsuladas** y que sea **simple de modificar y expandir**. Es en base a esto que se descuenta puntaje en caso de modelaciones que si bien concisas, no aplican correctamente estos principios.

Espero que esta explicación haya aclarado tu duda!

**Comment by Afro27** [comment]
@KnowYourselves me parece una buena explicacion, gracias!
