### ISSUE TITLE
Aparición de autos y troncos, y limites de aparición

### ISSUE THREAD

**Issue by MatiSick** [IIC2233/Syllabus#238]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Tengo dos dudas importantes. La primera es que si al momento de iniciar el juego, los troncos y autos deben aparecer en una posición aleatoria (acorde a sus trayectorias), o podemos preestablecer un punto de aparición predeterminado. Mi otra pregunta, es que independiente de lo anterior, cuantos troncos/autos pueden haber a la vez por carril?, y al momento de que un objeto entre a la escena este debe hacerlo poco a poco, desde su limite de la imagen o debe aparecer de una vez completo?

Gracias!.

**Comment by ivanvlam** [comment]
Hola @MatiSick ! Respecto a la primera duda, no tiene mucho sentido que los troncos y autos aparezcan en la mitad del río y de la carretera, por lo que deben aparecer en los extremos, respetando la dirección del carril.

En segundo lugar, el límite de troncos y autos por carril es arbitrario mientras no interfiera con el desarrollo del juego. Sin embargo, este número estará determinado por la velocidad y los parámetros de tiempo de aparición.

Por último, la idea inicial era que tanto troncos como autos aparecieran poco a poco, pero como esto no está explícito en el enunciado, queda a tu criterio si aparecen poco a poco o de una vez completo, recuerda especificarlo en tu README.

**Comment by MatiSick** [comment]
Muchas gracias por la aclaración, me quedó claro!.

**Comment by ferperezh** [comment]
Hola sobre este mismo tema de la aparición de autos/troncos, creo q no me quedo claro si yo puedo elegir la dirección previamente, en vez de ser aleatoria ?

**Comment by ivanvlam** [comment]
Hola @ferperezh ! Tal como dice el enunciado, la dirección de los autos es completamente aleatoria, es decir, puede haber 3 carriles con el mismo sentido.

En cuanto a los troncos, la dirección es aleatoria, pero el sentido de los carriles debe ser intercalado, es decir, para un río basta con determinar aleatoriamente la dirección de un carril, ya que los otros dos dependen de este y deben respetar el orden. Por ejemplo: si los troncos en el carril del medio van de izquierda a derecha, tanto los troncos del carril de arriba como los del carril de abajo deben desplazarse de derecha a izquierda.
