### ISSUE TITLE
Quien comienza jugando

### ISSUE THREAD

**Issue by camilapavesi** [IIC2233/syllabus#238]
Hola! Solo para confirmar, siempre parte jugando el jugador cierto? Y luego continúa el oponente.
Gracias!

**Comment by matiasmasjuan** [comment]
Hola @camilapavesi !

Si bien no se señala **explícitamente** en el enunciado, puedes asumir que el **jugador** es quien **parte jugando**. De todas formas, queda a tu **criterio** en caso de que desees que sea de forma **inversa**. Si haces esto último, recuerda indicarlo en tu ***README.md*** para que los correctores estén al tanto al momento de correr tu programa.

Mucho éxito con la tarea! :smile:
