### ISSUE TITLE
Comentarios Generales Diagramas de Clases T02

### ISSUE THREAD

**Issue by flobarrios** [IIC2233/Syllabus#238]
Hola!! Revisamos sus diagramas y éstos fueron los principales comentarios que surgieron. Esperamos que les sirvan! 

* Comentario: No todo debe ser atributo de una clase, aprovechar más las capacidades de las properties para modelar atributos que están condicionados por otro (Por ejemplo: la población actual = población inicial - muertos, contagiosidad y todas las cosas que dependen de parámetros fijos) 
* Pequeña observación de cómo escribir el diagrama:
  * Utilizar correctamente la herencia en el diagrama, no hay que indicar los atributos de 3 clases distintas si son atributos heredados de una clase madre
  * No es necesario escribir el "self" para los atributos de una clase
* Redundancia en métodos y atributos: no crear clases que puedan simplificarse a una, con métodos y atributos similares, por ejemplo con clases Mundo y País. No pensar en las relaciones de las clases lógicamente como en el mundo real, pensar en estas como objetivo a lograr una eficiente programación (por ejemplo a veces aunque la relación pareciera lógicamente ser de composición, por efectos de programación es mejor hacerla por herencia)
* Me fijé que algunas personas intentan tener una clase A que se agregue de instancias de una clase B y que a su vez la clase B se agregue de instancias de clase A (esto en base a algunas dudas en la u y un diagrama). Esto una mala práctica.
* Falta claridad en cuando usar composición y agregación. Recordar que la composición la clase base que usamos se construye a partir de la inclusión de otros objetos al igual que en la agregación, pero, en esta última el tiempo de vida del objeto es independiente del objeto que lo incluye. :c
* Muy poco uso de clases considerando el uso de un lenguaje orientado a objetos, es buena idea aprovechar las ventajas que permiten estos lenguajes para el modelamiento. Hay relaciones pero no son demostradas en los atributos que contiene la clase.  :D
* Usan muy pocas clases, y no relacionan del todo bien sus clases existentes. Algunas relaciones están mal hechas, mientras que hay algunas que faltan. Para un programa tan grande crearon pocas clases. 
* Una buena práctica que vi fue que se separaba las clases dedicadas a la interacción con el usuario de las clases que modelaban el problema en si. Tenian una clase menú con una pequeña estructura de clases que se comunicaba con el programa principal, esto es una buena práctica que emula como realmente se trabaja backend y frontend, no todos lo hacen eso sí.
* Tratan de englobar el problema en clases gigantes, a veces les falla la full = agrandar_en_bit(n_significante, max_sig)modularizacion o no notan que separando las funcionalidades puede quedar mucho más ordenado su código y fácil de trabajar con este.
* Ya sea por intuición, o porque hubo un análisis riguroso del enunciado, en general se tiene una idea de que se debe separar la capa lógica de la capa que interactúa con el usuario. Ésto ayuda a modularizar el problema y evitar el antipatrón de diseño ‘god object’, a la vez que reduce el número de funciones por clase, de manera que se asegura una única responsabilidad definida a cada componente.
* Dentro del mismo marco, también existen modelaciones en que la clase Menu por ejemplo puede ser separada en dos o incluso tres clases distintas. En cuanto al nombre de los parámetros y en especial de las funciones, logran ser lo suficientemente descriptivos para tener una idea inicial acerca de cómo se comporta el flujo del programa.
* Diferenciar entre la modelación de la tarea y las clases auxiliares que utilizaran en la tarea
* No hay necesidad de crear dos clases que tengan exactamente las mismas características 
* Las clases no deberían poder acceder a todas sus instancias
* Muchas de las clases deberían ser métodos
* A modo de comentario general, lo más importante es que piensen y modelen el problema antes de empezar a programar. Me tocó revisar algunos diagramas que decían algo como “aún no hago esta parte” y la idea de modelar es justamente la contraria, pensar el problema a modo global y modelar todas las interacciones, para luego programarlas y no al revés.
* Diferenciar bien entre composición y agregación. Si el mundo deja de existir, debiera ocurrir lo mismo con los países (composición).
* Hay métodos o atributos vacíos, escritos como “()”. Explicar al pie de página a qué se refiere con esto. En general, si ponen algo que se les ocurre, deberían explicarlo para que se pueda entender y no sea omitido o malinterpretado.
* Extra: Sacar bien las fotos en caso de hacerlo a mano. Hay uno (edit: varios) que no está bien enfocado y es incómodo para leer. 
* Hay un par de diagramas que no indican el tipo de variables, por ej. int, float, str, etc. Esto encuentro que es bastante importante para entender más rápidamente un diagrama. En uno hay un atributo llamado visibilidad, que podría ser int, variando en un rango (por ejemplo 0 es sin visibilidad, 1 es un poco… 10 es lo máximo) pero también podría ser bool, siendo True o False solamente.
* Clase Menu muy extensa, el menú debiese limitarse a ser un selector de acciones y no ser parte del backend del programa.
* Hacer listas doblemente ligadas puede hacer más fácil el uso de algoritmos de ordenación
* Si su clase va a necesitar una clase que emule el comportamiento y funcionalidad de una lista, ésta y sus métodos también deberían estar presentes en el diagrama.
* Su diagrama de clases debe incluir TODAS las clases que va a usar con sus métodos correspondientes, no dupliquen información, si en la clase principal tienen la lista de países no creen una segunda lista de países en otra clase para otros fines, usen la misma lista que se encuentra en la interfaz. Si van a subir una foto de su diagrama procuren qu este tenga buena letra y sea entendible, ya que a veces el tamaño y calidad de la foto podría reducirse y en ese caso es crucial que lo hayan hecho claro desde un principio. No olviden escribir la cardinalidad de las relaciones entre clases en sus diagramas.

**Comment by acrojas2** [comment]
Dudas varias:

->Si las clases tienen atributos de estructuras de datos (ejemplo: conexiones = Lista() )que contienen objetos de otras clases, necesariamente se ocupan los métodos respectivos a las estructuras de datos... Estos métodos se deben incluir en el diagrama de la clase que tiene atributos de este tipo (?). De ser así, si tuvieramos una clase que tiene como atributo un objeto que pertenece a otra clase también se deben agregar los métodos de la clase a la que pertenece ese objeto en el diagrama de clases (?)

-> En el modelamiento de la tarea, hasta el momento, tengo las clases necesarias como para poder armar el juego (Poblacion, Pais, Mundo, etc) con los métodos suficientes para propagar y actualizar los estados de los paises, etc. Ahora, tengo planeado hacer una clase que se llame Pandemic y  que esta contenga todos los métodos para que el juego se lleve a cabo (que no es mas que llamar a los métodos de las otras clases que son como el esqueleto del programa, según la lógica en que deberían ocurrir los sucesos), es decir, que realice la propagación inicial, propagaciones sucesivas  en cada partida, intente descubrir la cura, etc. Ahora bien, es necesario crear una clase Jugador y que la instancia del jugador interactúe con la clase Menu y que esta clase Menu acceda a los métodos de Pandemic para que todo funcione (?) o es redundante la clase Pandemic y desde el menú debería acceder a los métodos del Mundo por ejemplo para que ocurran las cosas (?).

-> Con respecto al modelamiento general del juego, no me queda claro qué clase debería incluir el paso horizontal del tiempo, Pandemic o  Mundo u otro (?).

-> Con respecto al modelamiento de las infecciones: dado que son 3 y los atributos de las infecciones tienen valores fijos y que no cambian en el juego, vale la pena hacer subclases (que hereden de una clase Infeccion) correspondientes a cada infección (?), o es mas fácil y simple hacer solo la clase infección y hacer las variables respectivas a cada infección e importarlas en el modulo que se necesite (?) (cuál sería la buena práctica).

**Comment by diegonavarrovergara** [comment]
Una pregunta: Mi programa tiene varios cambios con respecto al diagrama de clases que entregué. Es importante eso? Qué puedo hacer?
