### ISSUE TITLE
Equipo conexo

### ISSUE THREAD

**Issue by vjlira** [IIC2233/Syllabus#238]
Un equipo tiene que ser conexo solo considerando a los jugadores del equipo? O consideranto el resto de los jugadores de los otros equipos?

**Comment by monicabelen** [comment]
No te preocupes de eso, van a ser siempre conexos!

**Comment by mora4** [comment]
No se si entendí bien, el enunciado dice: "El usuario debe ser capaz de crear su propio equipo con 11 jugadores de su preferencia. Puede incluir cualquier jugador siempre que el grafo de aﬁnidades entre los 11 jugadores sea conexo."

Si hago un grafo con los 11 jugadores que se eligieron y este grafo no es conexo entonces no lo debería dejar armar ese equipo?

**Comment by pcseisdedos** [comment]
A mi en #223 me respondieron:

> Hola! Creo que no quedo demasiado claro en el enunciado, pero el equipo debe ser conexo según el grafo grande, por lo que cualquier combinación de 11 jugadores será conexa, por lo que no tienes que preocuparte.

Básicamente entiendo que todos los equipos son conexos porque el grafo inicial lo es
