### ISSUE TITLE
Formulas de desplazamiento y encallamiento

### ISSUE THREAD

**Issue by pascal1003** [IIC2233/syllabus#238]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] 
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola,
Estaba leyendo el enunciado y en la formula de la La probabilidad de encallar y de desplazamiento no me quedo muy claro que simbolizaba el min y el max

**Comment by pascal1003** [comment]
Intente cambiar el nombre del archivo pero el computador no me deja
![Captura de pantalla 2021-04-18 a las 9 47 05 a m](https://user-images.githubusercontent.com/80788210/115147857-0aca4c80-a02b-11eb-9aba-6d7201638d86.png)

**Comment by santiagovegaf** [comment]
Hola @pascal1003!

`max` y `min` son dos funciones de python que retornan al máximo y mínimo de un set de valores recibidos respectivamente. Puedes leer más sobre estas aqui: https://www.geeksforgeeks.org/max-min-python/

Por ejemplo, en la probabilidad de encallar no puede ser mayor a 1 (que es equivalente al 100%) por los ponderadores de *trend_encallar* y *dif_canal*.
Suerte en tu tarea!

**Comment by pascal1003** [comment]
Muchas gracias

**Comment by nicolaspoli** [comment]
@santiagovegaf  Hola! perdona si uso este issue en vez de uno nuevo, pero es sobre el mismo tema.

No entiendo si el valor del desplazamiento debe ser un valor aleatorio entre el min o el max o si literalmente se espera que asigne max(0,1(min(blablabla) a una variable en mi codigo.

**Comment by santiagovegaf** [comment]
Hola @nicolaspoli!

El valor de desplazamiento no es random, sino que el resultado de la fórmula del enunciado. Es decir, si la fórmula de desplazamiento te entrega un valor de X, el barco avanza X unidades. 

Entiendo que el ejemplo que di antes dio espacio a interpretar que desplazamiento podría ser un valor aleatorio, pido disculpas si genero algún inconveniente. 

Suerte y quedo atento a cualquier duda!
