### ISSUE TITLE
Duda con multiherencia

### ISSUE THREAD

**Issue by amparostevens** [IIC2233/syllabus#238]
Hola!
Acabo de ver el video de cierre de la AF02 y no me ha quedado claro la multiherencia. Se supone que dependiendo de la clase de jugador, éste iba a tomar distintos valores para los atributos. Por ejemplo la clase JugadorInteligente debía tomar el nerviosismo de JugadorMesa y la inteligencia de JugadorCartas, pero ¿cómo es que efectivamente la clase sabe cuál de los valores de los atributos elegir? 
En el cierre sale simplemente que hereda de las otras 2 clases pero no se especifica si es que elige, porque, por ejemplo, el atributo nerviosismo podría tomar el valor por defecto o el de JugadorMesa.
Hice la prueba de correr el código como sale en el video cierre y definiendo "a la mala" los atributos (sin usar la multiherencia) y los valores de los atributos no me dieron igual.

**Comment by fdoflorenzano** [comment]
Hola @amparostevens,

Esta duda es bastante común, y en general se debe a una confusión a como se refleja la herencia en Python, específicamente, la de atributos. Tu duda tiene varias aristas, así que intentaré ir en orden.

Primero, el concepto de herencia consiste en una clase que especializa otra, por lo tanto tiene al menos los mismos métodos (comportamiento) y atributos (estado). Pero lo que uno se puede dar cuenta al probar código de herencia en Python, es que al declararse herencia, son solo los métodos los que se heredan inmediatamente, mientras que los atributos de instancia no se heredan directamente. ¿A qué me refiero con eso? Toma el siguiente ejemplo:

```python
class A:

    def __init__(self):
        self.a = 1
        self.b = 2

    def metodo(self):
        print("funciona")

class B(A):

     def __init__(self):
         self.c = 3

x = B()
```

Aquí se define una superclase `A`, se declara una subclase `B` y se crea una instancia de `B`. Al declarar la herencia (`class B(A):`), Python automáticamente le otorga acceso a todas las definiciones que están al primer nivel de la clase, es decir, lo que generalmente son solo los métodos. En este caso, la definición de `__init__` y `metodo` quedan disponibles para todas las instancias de `B` mediante `self`. Si se continua con la definición de la clase `B`, nos encontramos con una nueva declaración de `__init__`, por lo que ahora reemplaza el método que se accede mediante `self` en las instancias de `B`, a lo que se expresa en el código (`self.c = 3`).

Entonces, al instanciar `B` en la variable `x`, el código que se efecuta es la última definición de `__init__` en la herencia, en este caso, la definida en `B`. Este código entonces declara un atributo de instancia `c` con el valor `3`, **y eso es todo, no tiene más atributos**. ¿Por qué, si está heredando? Porque las definiciones de métodos se heredan directamente, en cambio para generar atributos de instancia, se debe **ejecutar código que las defina**, y en este caso, no se ejecuta código en el `__init__` de `B` que defina los atributos `a` y `b`. Puedes probar copiando y pegando ese código, y si intentas acceder a `x.c` y `x.metodo()`, funcionará ya que `metodo` si lo hereda, y `c` se creo en `__init__`. Pero si pruebas `x.a` y `x.b`, te lanzarán errores ya que no existen los atributos en esta instancia.

Lo que se puede concluir de lo anterior, es que para definir atributos de instancia, entonces cada instancia debe ejecutar código que le defina tales atributos, ya sea en su propio `__init__` o mediante otros mecanismos, como `super`. Se arregla nuestra situación anterior con este código:

```python
class A:

    def __init__(self):
        self.a = 1
        self.b = 2

    def metodo(self):
        print("funciona")

class B(A):

     def __init__(self):
         super().__init__()
         self.c = 3

x = B()
```

¿Por qué? Porque ahora cada vez que se instancia `B` y se ejecuta su `__init__`, la primera línea de este llama a la definición de `__init__` de `A`, la cual tiene código que define atributos `a` y `b` para la instancia. Se termina esa ejecución y luego continuá con `__init__` de `B`, el cual define el atributo `c`. Ahora `x` tiene atributos `a`, `b` y `c`.

Eso es un aspecto, pero otro es como se ejecuta en multiherencia. En [el material](https://github.com/IIC2233/contenidos/blob/master/semana-03/2-multiherencia.ipynb) se explica que con el uso de `super` en multiherencia, se pueden hacer llamadas en cadena entre clases que pasan una por una. Por ejemplo, con:
```python
class A:
    def __init__(self):
        self.a = 'a'
        self.b = 'a'
        self.c = 'a'
        self.d = 'a'

class B(A):
    def __init__(self):
        super().__init__()
        self.b = 'b'

class C(A):
    def __init__(self):
        super().__init__()
        self.c = 'c'

class D(B, C):
    def __init__(self):
        super().__init__()
        self.d = 'd'
````
Por cómo se declaro la herencia y los llamados, el orden de llamados de los métodos `__init__` desde `D` es: `D` --> `B` --> `C` --> `A`. Además nota que cada `__init__` llama al siguiente `__init__` , y **luego** se asigna un valor de atributo, entonces la última asignación será la que determine el valor restante en la instancia.
Con el orden de llamados en cuenta, y cómo se estructura el código en cada `__init__`, las instancias de `D` tendrán de valores de atributos: `a = 'a'`, `b = 'b'`, `c = 'c'` y `d = 'd'`.
Intenta ver tu mismo, ¿qué valores les quedarían a los atributos de instancias de `B`, `C` y `D`?


Una explicación un poco larga para tu pregunta, pero que noté ayer en varios casos no tenían claro estos dos aspectos grandes de ejecución de código en instancias de clases. Luego, para responder tu pregunta original: ¿cómo sabe una clase que atributos heredar? Pues depende de como ordenes y estructures el código, asegurándote que el orden de ejecución y asignación produzca lo que esperas.

Espero se entienda, cualquier duda, ¡escríbanla!
Saludos.

**Comment by amparostevens** [comment]
Muchas gracias!!! Ahora me quedó claro cómo funciona
