### ISSUE TITLE
Duda respecto a salto izquierda y derecha de froggy dentro de un tronco

### ISSUE THREAD

**Issue by Nicromanker** [IIC2233/Syllabus#239]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Puedo implementar que froggy salte del tronco por la izquierda o la derecha? En el enunciado dice que solo puede salir para arriba o para atras, pero me parece un poco extraño no dar la opcion

**Comment by mmunoz12** [comment]
Hola @Nicromanker!

Es importante notar que el enunciado sí pide implementar el salto y esto considera todas las direcciones (al igual que el caminar), por lo que froggy no sólo debería saltar hacia adelante y atrás sino que a la izquierda y derecha, según la dirección en la que se encuentre.

Dado que los ríos van de un lado hacia otro y sólo hay bordes de pasto arriba y abajo de estos, si Froggy salta hacia los lados fuera del tronco, se caería al río y perdería.  Recuerda que la aparición de troncos esta dado por TIEMPO_TRONCOS, y este parámetro no será disminuido al momento de la revisión para que los troncos no colisionen. Debido a esto, dependiendo del TIEMPO_TRONCOS dado según cada uno, las distancias entre los troncos pueden variar, por lo que lo único asegurado (al momento de la revisión) será avanzar por los troncos que pasarán por la fila de adelante.

En resumen, se deben implementar saltos en todas las direcciones, los cuales deberán poder realizarse tanto en el pasto como en el río y en la carretera. Luego, si Froggy esta pasando el río sobre un tronco y salta hacia los lados de este (y Froggy cae al agua), simplemente se perderá la partida.

Espero que haya quedado claro! Avísame si te quedan dudas :)

**Comment by Nicromanker** [comment]
Perfecto. Hay algun problema si hago que mi salto sean cuatro saltos discretos (pequeños), para asi poder utilizar los sprites que nos dieron y que este tenga una animacion? En el enunciado dice que debe ser discreto pero no se si sea ilegal jajajajaja

**Comment by mmunoz12** [comment]
Depende de cómo lo implementes, el único requerimiento es que sea posible pasar de un tronco a otro (y al pasto) mediante un toque de la barra espaciadora (o el botón que utilices para saltar), sin que pase de largo. Si con 4 saltos discretos te refieres a presionar la barra espaciadora 4 veces, entonces no estaría del todo correcto ya que con un sólo salto Froggy debe volver a quedar con el sprite normal (no saltando) y moverse PIXELES_SALTO pixeles.

Algo que se me ocurre es que podrías hacer es que cada sprite dure un tiempo muy pequeño, de modo que pasen las sprites de las animaciones desde que se presiona la barra espaciadora hasta antes de que “termine” de saltar. 

Mucha suerte con tu entrega!

**Comment by drcid98** [comment]
Hola, aprovechando que yo tenía la misma duda, me gustaría preguntar algo extra relacionado a esto: al hacer el salto hacia los lados o atrás, que sprites deberíamos usar? digo, ya que el sprite que se nos entrega para el salto serviría solo para saoltos hacia adelante.

**Comment by mmunoz12** [comment]
Hola @drcid98!

Perdona la demora en mi respuesta 🥺. Al ser un **salto discreto**, no es necesario implementar sprites de salto. Sólo se debe cumplir con lo especificado en el enunciado lo cual sería que Froggy se mueva PIXELES_SALTO hacía adelante (o en la posición en la que se encuentre) cada vez que se presione la barra espaciadora.

Las sprites de Froggy saltando (nombre “jump_x") se dejaron para quienes **quieran** utilizarlas, pero como bien dices, no se encuentran las sprites de saltos hacia los lados. Por lo tanto, podrías simplemente no implementar los cambios de sprites para saltos a la izquierda/derecha o si deseas podrías crear estas sprites. Queda a tu criterio y recuerda comentarlo en tu README si se crean nuevas sprites ☺️. Saludos!
