### ISSUE TITLE
Duda sobre multiherencia

### ISSUE THREAD

**Issue by etoteiza** [IIC2233/syllabus#239]
Hola! tengo una duda sobre la multiherencia, he visto que se usa en situaciones en que una clase hija comparte los mismos atributos que sus clases padres (siendo que las clases padres tienen distintos atributos entre sí). Pero que pasa si las clases padres comparten atributos y además tienen algunos atributos que difieren entre sí, y la clase hija hereda de ambos. Mi problema es que no logro correctamente poner ```*args``` y ```**kwargs```. Pongo el siguiente ejemplo:

```python3
class Padre:
    def __init__(self, nombre, edad, poleras):
        self.nombre = nombre
        self.edad = edad
        self.cantidad_poleras = poleras

class Madre:
    def __init__(self, nombre, edad, pantalones):
        self.nombre = nombre
        self.edad = edad
        self.cantidad_pantalones = pantalones

class Hijo(Madre, Padre):
    def __init__(self, nombre, edad, pantalones, poleras):
        pass
```

Ahi podemos ver que hijo además de heredar los atributos nombre y edad, hereda una cantidad de poleras del padre y pantalones de la madre. Sin embargo, como tienen atributos compartidos las clases Padre y Madre no logro poner bien el inicializador super().__init__().
Sé que está raro las clases, pero es un ejemplo random. Espero que se entienda la duda.

Gracias de antemano!

**Comment by KnowYourselves** [comment]
Hola @etoteiza!

En primer lugar (se que no es la idea del ejemplo, pero prefiero dejarlo claro) hay que tener cuidado con confundir agregación y composición con herencia. En este caso `Hijo`, por herencia **es también `Madre` y `Padre`**, lo cual no hace mucho sentido 👀. En este caso Hijo sería una clase sin herencia alguna, y estaría relacionada por composición o agregación a sus padres, de la forma _"Una/un madre/padre tiene un hijo"_, o _"Un hijo tiene padres"_.

En segundo lugar, asumamos que fueran clases genéricas A, B y C. Como A y B comparten atributos, para poder hacer funcionar la herencia deberías tener una clase D que definiera todo lo que tiene en común A y B. 

Por ejemplo, podríamos agregar una clase `Persona`, de la cual heredan `Padre` y `Madre`, la cual contiene lo que tienen en común, `nombre` y `edad`. Luego `Hijo` podría correctamente heredar de `Madre` y `Padre`.

Sin embargo esto te crea **un problema de herencia diamante** 😱, en los contenidos podrás encontrar la forma correcta de pasar los argumentos a las clases padres para poder instanciar correctamente.

Espero haberte ayudado!
