### ISSUE TITLE
Archivo .vscode en .gitignore

### ISSUE THREAD

**Issue by FdoTorres1** [IIC2233/syllabus#239]
Hola, tengo un archivo .vscode que me apareció en mi directorio cuando empecé a usar pycodestyle como linter. Se está viendo así:
<img width="161" alt="Screen Shot 2020-08-27 at 4 58 27 PM" src="https://user-images.githubusercontent.com/69602127/91494300-9ddd2900-e886-11ea-9662-6563e2d10222.png">
Mi duda es, mi .gitignore debiera contenerlo? Si la respuesta es sí, está bien que mi .gitignore quede así (considerando que solo ocupo main.py):

```
puntajes.txt
parametros.py
tablero.py
__pycache__/
.vscode
```

**Comment by MatiasDuhalde** [comment]
Si, efectivamente tu archivo `.gitignore` debería ignorar todo tipo de archivos y directorios autogenerados que no sean parte de la tarea, como `__pycache__/`, `.vscode/`, `.DS_STORE`, entro otros!

Nota: Fíjate que `.vscode` no es un archivo, sino un directorio, por lo que lo correcto sería agregar `.vscode/` (con el slash) en el `.gitignore` (aunque esto es sólo por estilo, funcionará de igual manera sin el slash).

**Comment by FdoTorres1** [comment]
> Si, efectivamente tu archivo `.gitignore` debería ignorar todo tipo de archivos y directorios autogenerados que no sean parte de la tarea, como `__pycache__/`, `.vscode/`, `.DS_STORE`, entro otros!
> 
> Nota: Fíjate que `.vscode` no es un archivo, sino un directorio, por lo que lo correcto sería agregar `.vscode/` (con el slash) en el `.gitignore` (aunque esto es sólo por estilo, funcionará de igual manera sin el slash).

Gracias! Y por qué el `.DS_STORE` ?

**Comment by MatiasDuhalde** [comment]
@FdoTorres1 `.DS_STORE` lo incluí sólo como ejemplo! Es un archivo oculto que se crea automáticamente en algunos directorios en sistemas operativos `Mac OS`, la página de Si trabajas en Windows no es necesario que te preocupes de el, pero nunca está de más agregarlo al `.gitignore`!
