### ISSUE TITLE
Peor Amigo

### ISSUE THREAD

**Issue by andresplass** [IIC2233/Syllabus#239]
Queria saber si peor amigo solo incluye a quienes estan unidos por un arista directamente (es decir de afinidad 0.9, 0.95 o 1) o tendría que buscar dentro de todos los caminos, la persona que tenga la menor afinidad siguiendo la fórmula dada por el enunciado. (esa de 1 - suma etc...)

**Comment by IchottMano** [comment]
@andresplass Hola!
Se refiere a lo segundo que planteaste.
Saludos!

**Comment by andresplass** [comment]
Lo mismo para mejor amigo? o podemos asumir que siguiendo la fórmula dada por el enunciado, la afinidad solo puede bajar mientras avanza el camino entonces en ese caso solo tomaremos en cuenta los que están unidos directamente?

**Comment by IchottMano** [comment]
@andresplass Precisamente es como tu lo dices.
Saludos y mucho éxito con tu tarea!

**Comment by pahaeussler** [comment]
Hola, considero extraño revisar los  jugadores que no tienen grado 1 de relación, debido a que esas personas no las conoces, por lo tanto no son tus amigos.

**Comment by andresplass** [comment]
@pahaeussler claro, no obstante lo que planteo es que no está precisamente escrito. 
Surgen varias preguntas si lo pones así, si quieres las numero:
1- Si estamos viendo solo amigos al momento de buscar mejor amigo, entonces esto incluye amigos lejanos, amigos cercanos Y conocidos? Ya que literalmente un conocido no sería tu amigo por lo que por enunciado solo revisaríamos amigos cercanos y lejanos (ya que tienen la palabra amigo). Entonces pasaría a preguntar si jugador "conocido" cuenta como amigo o no. 
2- No consideraría extraño revisar jugadores que no tienen grado 1 de relación por dos aspectos: primero, viendo el enunciado, para mejor amigo solo dice "encontrar el jugador con quien tiene mas afinidad" pero no se hace la distinción como en "Fichaje estrella" donde se determina que solo se considerarán grado 1 de relación. Dicho esto, imaginemos que tenemos un amigo cercano, y éste también tiene otro amigo cercano. Si hacemos la suma de aristas, también tendríamos una afinidad de 1 con el amigo de nuestro amigo y eso que no estamos a grado 1 de relación. Puesto que después de todo, el amigo de mi amigo, es mi amigo.

**Comment by ljrodriguez1** [comment]
puedo tener con el peor amigo una afinidad negativa, o al tener afinidad 0, ya no me puede caer peor

**Comment by ljrodriguez1** [comment]
muchas gracias! y de acuerdo con lo anterior al buscar la afinidad debería esperar que los caminos encontrados sean de maximo 5 jugadores o podría ocurrir que encuentro un camino más largo pero donde la afinidad es 1 entre muchos nodos por lo tanto igual sería más corto?

**Comment by ciquezada** [comment]
hola, aun no tengo clara la consulta de peor amigo, ¿puedo pedir una explicacion mas concreta?, sobre todo con el tema de las aristas de distancia al jugador consultado, gracias
