### ISSUE TITLE
Parámetros

### ISSUE THREAD

**Issue by carlosmartellus** [IIC2233/Syllabus#239]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Si el enemigo tiene parámetros según la dificultad, los parámetros que tenemos que elegir son en base a los mismo que los enemigos o los elegimos nosotros independientemente?

**Comment by Benjeeeh** [comment]
Hola!
¿Podrías especificar más o explicar de otra forma tu duda? No me queda claro del todo tu consulta.
Si te refieres a que si se debe separar cada parámetro para tu equipo y también para el enemigo, no, estos son globales. Lo esperable es que los enemigos también son instancias de Combatiente y por ende las mismas reglas se le aplican a ellos.

**Comment by carlosmartellus** [comment]
Pasa que nos dicen que x parametro está entre 1 y 10 por ejemplo, entonces nosotros elegimos ese o tenemos que sacarlo de "unidades.txt"?

**Comment by Benjeeeh** [comment]
@carlosmartellus 
Esas son consideraciones que se deben tener y que se deben mantener a lo largo del juego.
Al instanciar combatientes, deben ser con los valores designados en los diferentes archivos, pero luego dentro del juego, por ejemplo, en los combates, estos parametros deben siempre mantenerse dentro de los rangos que indica el enunciado.

En un ejemplo más grafico, X combatiente realiza 1000 de daño a un combatiente con 10 de vida, este normalmente debería bajar a -990 de vida, pero por los limites del enunciado este debe quedarse en 0.

En resumen: Respetar los valores que indica cada archivo, y respetar los valores constantes que indica el enunciado. Estos no son parametros que debes fijar! Puedes revisar la issue #169 que se habla un poco de esto.

Espero que haya quedado más claro, saludos!

**Comment by carlosmartellus** [comment]
La verdad no entiendo. Nosotros le asignamos el valor a la vida maxima, poder, agilidad, resistencia y defensa que nosotros estimemos convenientes o eso lo tenemos que sacar de algún lado?

**Comment by Benjeeeh** [comment]
Los valores al instanciar tus combatientes los debes sacar del archivo **unidades.txt**, mientras que la de los combatientes enemigos es de **facil.txt, intermedio.txt o dificil.txt**. En la sección 6.1 y 6.2 del enunciado se específica que significa cada separación en los archivos. Aquí es donde se asignas los valores de vida máxima, poder, entre otros.

No los confundas con los parámetros que están en ESTE_FORMATO y en color azul, que esos deben ir en parametros.py y tu les debes asignar un valor. Hay otros valores en color azul, como los de rangos entre 1 y 10 de poder, que son constantes y deben si o si ser esos valores.

Espero que haya quedado más claro. Cualquier consulta no dudes en preguntar!

**Comment by carlosmartellus** [comment]
En caso de algo, para mejorar la legibilidad, puedo hacer un diccionario en parametros.py de cada una de las unidades para que tambien se me facilite a la hora de instanciar las clases?

**Comment by BenjaMedinaPUC** [comment]
Hola! espero que se encuentren bien, tengo dos consultas
-La primera es: puedo poner palabras claves dentro del archivo "parámetros.py"? o son solo números que puedo agregar?
-Mi segunda consulta es sobre si es que yo puedo asumir que siempre me entregaran la misma cantidad de datos y en el orden estipulado a pesar de que estén erróneos, o tengo que verificar que las línea que me entregan de dificultades.py o unidades.py van a esta exentas de errores de valores, tipo de datos, cantidad de datos o mal posicionamiento de los datos?

Estaré atento a tu respuesta

**Comment by Benjeeeh** [comment]
@carlosmartellus 
No te lo recomiendo, la idea es que se instancien dentro del juego, accediendo desde el archivo.
@BenjaMedinaPUC 
¿A que te refieres con palabras claves? ¿Cómo palabras que se utilicen mucho dentro de este? Si es así no habría problema, puedes añadir todo parámetro que te parezca y que tenga sentido.
Sobre tu segunda consulta, si, debes verificar que la cantidad de parámetros que se entregan son los correctos. Tienes que verificar todo posible error que se te ocurra, los que mencionas están muy bien!

**Comment by BenjaMedinaPUC** [comment]
perdón, me expresé mal, a lo que iba es que si en el archivo "parametros.py" puede tener otros tipo de variables que no tengan relacion a la probabilidad o ints, como por ejemplo una lista de strings de palabras claves.

**Comment by Benjeeeh** [comment]
@BenjaMedinaPUC 
Si, ningún problema! :)
