### ISSUE TITLE
Equipo excavadores en entidad Torneo

### ISSUE THREAD

**Issue by constanzarojasch** [IIC2233/Syllabus#239]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola mi duda trata sobre el equipo de excavadores en la entidad torneo, no me queda claro si estos deben ser los excavadores iniciales o el conjunto de todos los excavadores disponibles en el csv.

**Comment by Benjeeeh** [comment]
Hola!
Debe ser el equipo de excavadores que trabajen para ti y puedan cavar, es decir, son los excavadores iniciales + los excavadores que se unan a tu equipo por tesoros. Recuerda que si lo necesitas, puedes crear atributos y no necesariamente deben estar solo los mencionados en el enunciado, por lo que si necesitas crear uno que comprenda todos los excavadores del archivo, puedes hacerlo.

Éxito en lo que queda de tarea!
