### ISSUE TITLE
Compilado issues T01

### ISSUE THREAD

**Issue by lily416** [IIC2233/syllabus#239]
En la siguiente issue encontrarás todas las issues sobre la Tarea 1 que se han realizado hasta el momento, estas están divididas según diferentes temas.
Antes de hacer una nueva issue, revisa si tu duda ya fue realizada, así evitamos las issues duplicadas. 😄

### Librerías permitidas, no permitidas y malas prácticas ✔️❌ 
1. Librerías permitidas, no permitidas y malas prácticas T01: #240 
1. Uso obligatorio diccionarios, `args`/`kwargs`: #262
1. `try`/`except` #281
1. ¿Qué es una variable global? #424
1. Prohibición `eval`/`exec` #591

### Comentarios Avance
1. Comentarios Avance T01: #458

### Flujo del programa
1. Rangos de atributos: #416
1. Determinar ocurrencia de acciones y eventos: #270
1. Días transcurridos: #275
1. Adoptando primera criatura: #284
1. Días sin comer: #294 #316
1. Día siguiente - inicio del día: #298 #489 
1. Duda pagar/fiscalizar/aprobación: #309
1. Siguiente día - pérdida puntos de salud: #323
1. Determinar ocurrencia comportamientos especiales criaturas #332 
1. Orden de sucesos al alimentar DCCriatura (Buñuelo): #341
1. Regeneración energía actual al volver o salir: #398 
1. Orden sucesos criaturas al pasar de dia #412
1. Mostrar en pantalla las perdidas de energía y sickles: #464 
1. Orden de multas y fiscalización de Magizoologos: #459

### Menús
1. "Volver atras" al crear DCCriatura: #297
1. "Volver atrás" y "salir" en acciones: #303 #503 #541 
1. Uso de recursión para pedir input: #395 
1. Acciones antes de salir del juego: #449
1. Volver al menú de acciones: #517
1. Volver atrás y salir al adoptar una DCCriatura o comprar alimento: #530 
1. Sensibilidad mayúsculas/minúsculas en menú de inicio: #533
1. La opción salir termina el programa en cualquier menu #537 
1. Paso del día y habilidad de las DCCriaturas: #561 
1. Imprimir las razones de multas, DCCriaturas, etcétera, al pasar el día: #562 
1. Menu volver atras al ingresar nombre magiozoologo #376 

### Magizoólogos
1. Sickles iniciales: #243 
1. Restricciones nombre Magizoólogos: #251
1. Agregar atributos: #261 
1. Cómo escoger el tipo de Magizoólogo: #264
1. Aumento de salud por Magizoólogo Híbrido: #276
1. Aumento de salud por Magizoólogo Híbrido v/s aumento de salud alimento: #359 
1. Aumento de salud total Docencio #434 
1. Nombres de DCCriaturas y Magizoólogos: #280 #348 
1. Recuperar DCCriatura: #285
1. Probabilidad recuperar criatura #385 
1. Aumento de salud por Magizoólogo Tareo: #318 
1. Nivel de aprobación inicial: #319
1. Valor energía Magizoólogos: #329 
1. Cargar y crear Magizoólogos: #334
1. Alimento inicial de Magizoólogo: #335
1. Nivel Energía Total Docencio: #340
1. ¿Cuándo un nombre de usuario es alfanumérico?: #381
1. Energía al tratar de alimentar una criatura sin alimentos: #393 
1. Recuperar licencia: #482 
1. Arrepentimientos camino a crear Magizoologo #532 
1. Nivel de energía actual al crear Magizoologo #439 
1. Éxito al sanar con puntos de salud actuales mayores a nivel mágico: #558

### DCCriaturas
1. DCCriaturas caracteres alfanuméricos: #266
1. Error formula de DCCriatura - Probabilidad enfermarse: #272
1. DCCriaturas fuera de cautiverio: #273
1. Criatura que ataca al ser alimentada: #279
1. Nombres de DCCriaturas y Magizoólogos: #280
1. Factor `salud_maxima_criatura` corresponde a la salud total de DCCriatura: #286
1. Alimentar a una criatura cuando tiene salud máxima: #289 
1. Influencia de salud sobre si una criatura está satisfecha: #360
1. Habilidad especial Augurey: #290
1. Cuándo se puede recuperar una DCCriatura: #291
1. Confusión con puntos de salud total: #306
1. Estado de Salud: #311
1. Días consecutivos de una criatura enferma: #326
1. ¿Cuando una criatura escapa deja de pertenecer al magizoólogo?: #327
1. Comportamiento de Erkling: #336
1. Habilidad especial Erkling #441 
1. Diferencia entre puntos de salud actuales y puntos de salud totales: #379
1. Rechazar Buñuelo de Gusarajo y Atacar: #388
1. Salud actual, nivel de hambre y días sin comer iniciales de crear criatura: #391 
1. Identificar criaturas escapadas: #392 
1. Pérdida de salud de las criaturas: #394
1. Orden entre alimentar y probabilidad de ataque DCCriatura: #406 
1. Ataque por alimentar #344
1. ¿Recuperar antes de fiscalizar?: #440
1. Salud mínima de la DCCriatura: #479 
1. Criaturas escapadas y uso de habilidad especial al pasar dia #539
1. visualizar criaturas cargadas ya escapadas: #546 
1. Restablecer el nivel de salud de la criatura: #556
1. Primera DCCriatura: #374 
1. Dueños de las DCCriaturas: #375 
1. Efecto agresividad tras comer Tarta de Melaza: #534 
1. Pasar de satisfecha a hambrienta según cantidad de días: #524

### Alimentos
1. Entidad Alimentos: #256 #333 
1. Duda formato Alimentos: #339
1. Primer Alimento: #384
1. Rechazar Buñuelo de Gusarajo y Atacar: #388
1. Modelación de clases: Alimento y DCC: #396 
1. Orden entre alimentar y probabilidad de ataque DCCriatura: #406 
1. Formato al escribir Alimentos : #538 
1. Habilidades especiales magizoologos y Buñuelo #357 
1. Quedarse sin Alimentos: #428 

### DCC
1. DCCriaturas consideradas para nivel de aprobación: #414 
1. Estado Magizoólogo y DCCriaturas: #247
1. DCC: utilidad funciones vender criatura y alimentos: #263
1. Precios de Alimentos y Criaturas para adoptar: #290
1. Comprar criatura al DCC: #308 
1. Fiscalizar criaturas escapadas: #265 
1. Fiscalización de eventos ocurridos en un día: #369
1. Fiscalizar magizoologo sin licencia: #408 
1. Manejo del DCC: #330 
1. Modelación de clases: Alimento y DCC: #396
1. Herencia con DCC: #397 
1. Imprimir estado alimentos: #486 
1. Mostrar estado Magizoologo: aprobacion y licencia: #522 

### Archivos
1. Manejo archivos `.csv`: #253 #504 
1. Actualización de archivos `.csv`: #274, #417 
1. Archivos csv: Magizoólogo con criatura inexistente: #338
1. Consistencia en el formato de los nombres en archivos .csv: #535
1. Mayusculas y Minusculas en archivos: #463 
* #### `magizoologos.csv`:
   1. Error de tipeo en magizoólogos: #255 
   1. Criaturas en archivo `magizoologos.csv`: #288
* #### `criaturas.csv`
   1. Criaturas.csv: EstadoEsc y EstadoSal #271
* #### `parametros.py`
   1. Variables random en `parametros.py`: #252
   1. Tipo de contenido `parametros.py`: #254
   1. Funcionalidad `parámetros.py`: #257
   1. Uso parámetros: #258 #269 
   1. Utilización de `parámetros.py`: #278 #545 
   1. Aclaración `parámetros.py`: parámetros hardcodeados: #312
   1. Contenido `parametros.py`: #313 #347 
   1. Uso funciones en parámetros #446 
   1. Uso diccionario #422 
   1. Poner strings "constantes" #380 
   1. Uso de paths en parametros: #544 

### _Bonus_
1. Bonus: nota máxima y cálculo de promedios: #267
1. Bonus Super Magizoólogo DocencioTareoHíbrido: #337
1. Peleas entre DCCriaturas: #447
1. Bonus: daño de una DCCriatura: #484
1. Bonus Pelea y su apuesta inicial: #523 

### Diagrama de clases
1. Entrega Diagrama de clases: #268 
1. Clases abstractas en diagrama de clases: #259
1. Formato diagrama de clases: #293
1. Evaluación avance: #295 #328 
1. Relación Criatura-Mago: #304
1. Diagrama de clases: herencia de properties: #321
1. Fecha de entrega avance: #355
1. Dudas funciones que llaman funciones y de retorno variable: #555
1. Formato de properties en diagrama de clases: #581

### `.gitignore`
1. Creación de `.gitignore`: #241 
1. `.gitignore` en Tareas y Actividades del repositorio personal: #249 
1. Actualización de archivos en syllabus: #302
1. Gitignore desde Mac: #598 

### Distribución de puntajes
1.

### Otros
1. Reutilizar código propio: #242
1. Duda saltos de línea en el código: #250
1. Nivel de modularización: #282
1. Importar con `*`: #283
1. `if __name__ = "__main__"`: #287
1. Cómo aplicar las probabilidades a los eventos: #292 #325
1. Lineas de código: moduralización, import y límite de archivos: #307
1. Duda respecto a properties: #315
1. Herencia: Definir getter y setter en clases distintas: #317
1. Error al usar getter dentro del __str__(): #331
1. Herencia en módulos distintos: #343
1. Cómo utilizar funciones min y max: #377
1. Python no encuentra el archivo `magizoologos.csv`: #401
1. Identación: #440
1. Uso adecuado de lower(): #470
1. Limite 100 caracteres: #471
1. Comportamiento inesperado en multiherencia y uso de super: #531 
1. Variables globales: #514 
1. Definición de probabilidades: #460
1. Sickles y nivel de aprobación de tipo int: #547
1. ¿Variación de valores incluye los extremos?: #487

**Comment by CataSudo** [comment]
Hola, tengo una duda respecto al sickle. En la tarea dice que todos empiezan con 500, pero en el archivo csv no es cierto. Mi duda es, ¿Qué número usamos?

**Comment by jeschuwirth** [comment]
Hola @CataSudo,

Recuerda postear tus dudas en una nueva issue en lugar de comentar en este compilado.

Cuando un usuario decide crearse un magizoólogo este comienza con 500 sickle, sin embargo este número puede variar a medida que alimenta a sus criaturas.  El archivo `magizoólogos.csv` contiene la info **actual** de distintos magizoólogos que ya fueron creados.

Espero que haya quedado clara la duda.

Éxito!
