### ISSUE TITLE
Referenciar siguiente Label de la grilla

### ISSUE THREAD

**Issue by fecoppa** [IIC2233/syllabus#239]
Hola!, tengo una duda: digamos que estoy en una posición (i , j) y quiero ver si hay un label especifico en la posición (i, j+1). hay alguna forma de referenciar el siguiente label que vendra a través de las posiciones si utilice un QGridLayout()? ... espero se entienda.

**Comment by teverde** [comment]
Tengo la misma duda. Lo resolví por el momento incorporando una variable que guardara los elementos del mapa (literalmente leído del archivo mapa_1.txt) y con eso puedo revisar que hay en esa celda

**Comment by jeschuwirth** [comment]
Hola!
puedes utilizar el método .itemAtPosition(row, column) de QGridLayout.

más información acerca del método en: https://doc.qt.io/qtforpython/PySide2/QtWidgets/QGridLayout.html#PySide2.QtWidgets.PySide2.QtWidgets.QGridLayout.itemAtPosition

Suerte en la Tarea !
