### ISSUE TITLE
Pieza debe desaparecer del tablero

### ISSUE THREAD

**Issue by cfernandez9** [IIC2233/Syllabus#239]
En el enunciado dice que si el jugador elige deshacer la última jugada, la pieza debe desaparecer del tablero. ¿Se refiere a la pieza que estaba en el tablero o a la que tenía la posibilidad de poner? ¿Desaparece para siempre o después puede volver a estar dentro de las opciones para colocar?

**Comment by Arcoirisky** [comment]
Hola :D Tal como dices la pieza que está en el tablero es la que debe de desaparecer. Se supone que tu buscas retroceder la última pieza que pusiste en el tablero, no la que tienes en la mano a punto de colocar. 
¿Se entiende mejor así? O:

**Comment by cfernandez9** [comment]
entendido, muchas gracias :)

**Comment by tomasrivera** [comment]
Cuando se pone deshacer, debería cambiar de turno? 
Si es así no debería cambiar la pieza actual también?

**Comment by Arcoirisky** [comment]
@tomasrivera tu primera pregunta se responde en el enunciado, al final de la sección ctrl-z :) y sobre la segunda, no se específica, por lo que queda a tu criterio. De todas formas, piensa en que la ficha debe cambiar de jugador :) 

@cfernadez9 que bueno que entendiste \o/

**Comment by Drpinto1** [comment]
Al deshacer una jugada, que pasa con la última ficha colocada por el otro jugador?, pues si solo se remueve la ficha del jugador actual, puede darse el caso en que la ficha jugada en el turno anterior no tenga vecinos, lo que, por enunciado, es una jugada inválida.

**Comment by Arcoirisky** [comment]
@Drpinto1 esa pregunta ha sido contestada en otra issue, prueba buscarla entre las cerradas si no la encuentras entre las que aún siguen abiertas 😃
