### ISSUE TITLE
Utilizar codigo actividad

### ISSUE THREAD

**Issue by solebravo** [IIC2233/Syllabus#239]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! quería saber que tendría que hacer si quiero utilizar algún código de la AS3 en mi tarea, tengo que citarlo? y si es así como se citaría? es legal hacer esto?
Gracias de antemano!

**Comment by Hellonston** [comment]
Hola @solebravo! claro que puedes utilizar código de la AS3 para tu tarea, para esto al igual que sacar extractos de código de sitios externos, debes hacer referencias a este en el **README.md**. Aparece bien explicativo en el template del readme acerca de como se referencia, en cuanto al link que se pide puedes copiar y pegar el link al github de la AS3. En general todas las actividades que se hacen en el curso ya sean formativas, sumativas o los propios ejercicios de contenidos pueden ser ocupados si se citan correctamente(esto incluye los de semestres anteriores).
Mucho éxito con la tarea! 😄

**Comment by solebravo** [comment]
Muchas gracias! y otra pregunta, si utilizo parte del código de la actividad que yo cree (de las secciones de completar), también tengo que citarlo?

**Comment by Hellonston** [comment]
Sí, **Todo** trabajo **hecho anteriormente por ti en el curso y que sea posible verificar**, es decir que el corrector pueda acceder a el código que se está citando, se puede utilizar, también se debería citar y nombrar el método, función etc en que te inspiraste del código elaborado por ti y un link a tu AS3(para que el corrector pueda verificar) en el **README.md**.
Saludos!
