### ISSUE TITLE
Duda sobre nombres de usuario y guardar partida

### ISSUE THREAD

**Issue by mdalamos** [IIC2233/syllabus#24]
Hola! Cuando una persona con un mismo nombre de usuario guarde una segunda partida, esta se guarda encima de la anterior? Es decir, cuando un usuario quiera abrir una partida solo va a poder abrir la última que jugó? Las anteriores se eliminan? 
Gracias!

**Comment by DCCollao** [comment]
Hola! 

La forma de resolver ese problema queda completamente a tu criterio, pero recuerda explicar tu decisión en tu `README.md`.

**Comment by mdalamos** [comment]
gracias!
