### ISSUE TITLE
Duda sobre linea en __init__ en ejemplo  de colas.

### ISSUE THREAD

**Issue by yoomaaly** [IIC2233/syllabus#24]
hola! sobre la materia de la semana 1, específicamente en 3-colas, en el primer ejemplo de uso de deque(), hay lineas de codigo que no entiendo qué es lo que hacen.  Esta es la clase

```
class Auto:
    @staticmethod
    def tiempo_revision(tipo):
        if tipo == 'auto':
            return 10
        elif tipo == 'moto':
            return 25
        return 30
    
    def __init__(self):
        self.tipo_vehiculo = choice(['moto', 'camioneta', 'auto'])
        self.tiempo_revision = self.tiempo_revision(self.tipo_vehiculo)
        
    def __str__(self):
        return self.tipo_vehiculo
    print(self.tiempo_revision)
```

mi duda es qué hace la linea:
`self.tiempo_revision = self.tiempo_revision(self.tipo_vehiculo)` 

pues no había visto algo así antes en __init__  
gracias

**Comment by KnowYourselves** [comment]
Hola @yoomaaly!

Cada auto debe tener un tiempo de revisión. Para calcularlo se definió la función `tiempo_revision` que nos devuelve el tiempo que cada auto se demora en ser revisado.

Con esto en mente, la linea `self.tiempo_revision = self.tiempo_revision(self.tipo_vehiculo)` llama a `self.tiempo_revision` con el tipo de vehículo, lo cual devolverá el número adecuado y se iguala a `self.tiempo_ revision` sobreescribiendolo. 

En resumidas cuenta sobre escribe la variable para que pase de ser la función al número correcto.

Espero haber ayudado!

**Comment by yoomaaly** [comment]
Muchas gracias! entendí
