### ISSUE TITLE
Duda Evolución Tarea 1

### ISSUE THREAD

**Issue by alfa-labarca** [IIC2233/Syllabus#24]
En el enunciado de la tarea, al calcular el nivel de evolución de cada planeta, dice que sumemos (Cantidad de magos y soldados)/Población total.
¿La Población total se refiere a la población de cada planeta (en cuyo caso, el resultado de la división siempre será 1), a la población de la galaxia o a la población máxima del planeta?
Muchas gracias.

**Comment by ayudantesIIC2233** [comment]
se refiere a la población máxima 💯

**Comment by alfa-labarca** [comment]
Gracias
