### ISSUE TITLE
Función verificar_alcance_bomba()

### ISSUE THREAD

**Issue by GuilleStanke** [IIC2233/Syllabus#24]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/syllabus/issues/21)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](https://github.com/IIC2233/syllabus/issues/20)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En la función verificar_alcance_bomba(tablero: list, coordenada: tuple) -> int, hay que retornar el alcance de la bomba antes de colisionar con un borde o una tortuga, si "colisiona" con otra bomba, ¿se sigue contando o pasa lo mismo que si colisionara con una tortuga o borde?

**Comment by Hernan4444** [comment]
Hola @GuilleStanke ,

Se sigue contando. Solo se deja de contar cuando hay un borde o una tortuga.

Saludos c:

**Comment by GuilleStanke** [comment]
Muchas gracias, otra pregunta respecto esta función... si por ejemplo tengo una bomba representada por un numero 2, y esta tapada por tortugas o bordes hacia abajo, hacia la izquierda, y hacia la derecha, pero hacia arriba tiene más de 2 espacios vacíos, el alcance de esa bomba es mayor que dos? o llega hasta 2? (entiendo que sumando todas las celdas que alcanza hacia los lados el alcance puede ser mayor a dos, la duda es en el caso específico que sobrepasa su valor sólo en una dirección)

**Comment by Hernan4444** [comment]
Hola @GuilleStanke 

Se suma en todas las direcciones y se evalúa el total de celdas afectadas, es decir, cuantas celdas son afectadas hacia arriba, abajo a la derecha y a la izquierda + la celda donde está el número. Por ejemplo:
```
- - - -
- - - -
- 2 - -
- - - -
```

Esa bomba con el 2, por el momento su alcance es de 7. 
```
- - - -
- - - -
- 2 T -
- T - -
```

Y ahora pasó a tener un alcance de 4 (una a la izquierda + la celda del 2 + dos hacia arriba).

```
- - - -
- - - -
T 2 T -
- T - -
```

Y ahora tiene un alcance de 3 (la celda del 2 + dos hacia arriba).

Por eso, la idea de todo DCCeldas es poner tortugas hasta hacer que el alcance de la bomba sea igual al número que representa. 

Espero que este ejemplo haya quedo más esclarecedor 😄 
Saludos c:

**Comment by iagschampke** [comment]
hola, si una bomba llega a "colisionar" con otra, entonces ambas explotan o sólo se considera como una celda más? en caso de que sea una explosión "en cadena", cómo se calcularía el alcance de las bombas?

**Comment by Hernan4444** [comment]
Hola, 

No existe eso de colision entre bombas, cada bomba es independiente y para ellas, otra bomba es solo una celda blanca más. 

Saludos c:

**Comment by iagschampke** [comment]
gracias!

**Comment by Hernan4444** [comment]
Hola @BenzoylMorexide 

El alcance de la bomba es independiente al número, es la cantidad de celdas que afecta la explosión. Luego, la idea de DCCeldas es poner tortugas para asegurar que el alcance de cada bomba sea igual al número que tiene. Por este motivo, el alcance en el primer ejemplo es 7, puesto que hay 6 celdas blancas + la misma celda del 2 que serán afectadas por la explosión. Y solo agregando tortugas, hacemos que esa explosión alcance a menos celdas hasta llegar a 2 que es el número indicado.

Saludos c:
