### ISSUE TITLE
Revelar archivos ocultos para meterlos al gitignore

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2233/Syllabus#24]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

[Hola, quería saber como revelar todos los archivo en mi repositorio (incluso los ocultos) para poder saber bien que meter en el git ignore]

**Comment by vice-rosas99** [comment]
ok gracias

**Comment by vice-rosas99** [comment]
otra duda que tengo es si importa en que parte de la rama de archivos se encuentre el gitignore, por ejemplo si debe ir en la misma carpeta y al mismo nivel donde están los archivos a ignorar o si puede estar en la carpeta padre a esta ( o en su defecto más atras)?

**Comment by Juampisaez** [comment]
Debe ir en cada carpeta de las tareas, es decir, tendrás un gitignore dentro de cada carpeta las tareas (T0, T1, T2 y T3). Dentro del gitignore, tu colocas los archivos que no quieres subir de cada tarea.

Espero haberme explicado,
Quedo atento por si no se entendió algo :)

**Comment by vice-rosas99** [comment]
ok perfecto, muchas gracias
