### ISSUE TITLE
Invalid SDK, PyCharm

### ISSUE THREAD

**Issue by jadiaz6** [IIC2233/Syllabus#24]
Hola, al hacer un nuevo proyecto en PyCharm me pide ligar Python con el programa. Al hacerlo el programa me dice que la SDK es inválida. Es Python 3.6 64-bit.

**Comment by sebacruzd** [comment]
Hola, 
Si bien el foro es de ayuda, deberías googlear los problemas y ver si los puedes solucionar antes de pedir ayuda. Estoy seguro que googleando "Pycharm project having problems with SDK" podrás encontrar varias soluciones.

Saludos!

**Comment by jadiaz6** [comment]
ya lo hice... No dice nada

**Comment by sebacruzd** [comment]
De casualidad tienes más de una version de Python?

**Comment by jadiaz6** [comment]
No, tengo sólo una, y es primera vez que instalo Python en este pc.
