### ISSUE TITLE
Problema con el os.path

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#24]
Estoy intentando crear un path para acceder a los distintos archivos que hay que usar para la tarea 0 (seguidores, usuarios y posts), pero al intentar usar el comando os.path.join("direccion") me sale:

name 'os' is not defined

pd: las lineas de mi codigo tienen forma:
ArchivoSeguidores= os.path.join("syllabus","Tareas","T00","seguidores")

**Comment by Tito0906** [comment]
Holaa! @felipehen ,

el problema probablemente se debe a que olvidaste importar la libreria os.  Prueba agregar en la primera línea de tu código: import os.
