### ISSUE TITLE
Funcionamiento test cases 

### ISSUE THREAD

**Issue by nicolaslindl** [IIC2233/Syllabus#24]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

¿Cómo se ocupan los test cases de la primera parte de la tarea para comprobar si los métodos que termino funcionan bien? No entiendo que archivo debo ejecutar, y cuales y en donde debo importar.

**Comment by MaxAl100** [comment]
Hola! Hay dos maneras de probar tus métodos con tests. 
Una opción es usando ``python3 todos_tests.py`` en la carpeta de la tarea, que va a correr todos los tests, probando todas las funciones.
Si quieres probar solo una funcionalidad específica, entonces puedes correr ``cd tests_publicos/nombre_test.py`` para probar esa funcionalidad en sí.
Espero que te haya ayudado! Si no he resuelto tu duda, avísame y te puedo seguir ayudando.

**Comment by MaxAl100** [comment]
Perdón! Hice un pequeño error en mi respuesta anterior, la segunda opción, para probar una funcionalidad específica. Para hacer esto debes hacer 2 pasos:
Primero ``cd tests_publicos`` que te llevará a la carpeta con los tests. Luego con ``python3 nombre_tests.py`` corres el programa para probar la funcionalidad específica.
Avísame si te funciona! :smiley:

**Comment by IsidoraCarmona** [comment]
ahh me funcionó pero primero tuve que sacar los test de la carpeta tests_publicos, y dejarlos individualmente en la carpeta de T1, o si no ahi me pasaba lo que tu decias, que estaban en distintas carpetas

**Comment by MaxAl100** [comment]
> ahh me funcionó pero primero tuve que sacar los test de la carpeta tests_publicos, y dejarlos individualmente en la carpeta de T1, o si no ahi me pasaba lo que tu decias, que estaban en distintas carpetas

Que bueno que te haya funcionado así, pero no es la idea y puede que cuando los ayudantes corrijamos tu tarea no nos funcione (y saques mala nota 😱), por lo que te recomiendo devolver los archivos a tests_publicos y realizar los pasos que te describí en mi segunda respuesta.

**Comment by elneitans** [comment]
Hola, todavía no me queda claro cómo he de trabajar, perdón 😿  . ¿red.py debe estar en la carpeta T1 de mi repositorio, y la carpeta de tests_publicos seguir en T1 del syllabus? Lo que estaba haciendo era tener red.py en T1 del repositorio, y ahí sí todo funciona como me dices. O debería pasar todo lo que está en el T1 del syllabus al T1 de mi repo? Muchas gracias!!

**Comment by MaxAl100** [comment]
Hola! red.py es tu código y debe estar en tu repositorio para poder ser evaluado.
Para poder copiar los tests, debes copiar la carpeta de tests_publicos a tu carpeta también, pero ten en consideración que debes ignorar esta carpeta (revisa el enunciado para ver que otras cosas debes ignorar!)
Lo de syllabus **NO** debieses cambiarlo dentro de sus carpetas, ya que si luego algún profesor o ayudante cambia algo, van a haber problemas al intentar descargar el nuevo contenido con git pull. 
Mi recomendación es que siempre copies el contenido nuevo de las actividades o tareas a tu repositorio personal para evitar situaciones molestas a futuro. Espero haberte ayudado y si tienes más dudas me dices no más 😃
