### ISSUE TITLE
Par de errores en notebooks y duda corta sobre una función

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#24]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

_las referencias a sets son todas referentes a los de la semana '01'_
## Par de errores
En los _notebooks_, cuando se quiere comparar la velocidad de cómputo entre distintos tipos de datos, cuando la ejecución es muy rápida por algún motivo devuelve el _float_ 0.000000 y cuando se intenta dividir, da origen al error. Por alguna razón, incluir un `sleep(n)` con un tiempo n arbitrario y luego restarlo, nos ha funcionado en algunas ejecuciones, —cuando estábamos revisando esto— para no tener el error.

_Estos suceden en el 4-colas y en el 6-sets:_

![image](https://user-images.githubusercontent.com/66154723/112085728-cd78b900-8b69-11eb-947d-1b50d3741ab0.png)
![image](https://user-images.githubusercontent.com/66154723/112085747-d5d0f400-8b69-11eb-85c8-1713bc043af2.png)

## Duda sobre función
En el _notebook_ 4-colas, se muestra el siguiente algoritmo recursivo para encontrar palíndromos,
![image](https://user-images.githubusercontent.com/66154723/112086044-51cb3c00-8b6a-11eb-96e6-c40b5d6d56b7.png)
Me preguntaba cuál es la utilidad de añadir el valor por defecto '= None', ya que al ejecutar el código sin argumentos, de todas maneras retorna un TypeError al intentar introducir un None al `deque()`

<details>
<summary>Código</summary>

```python
from collections import deque

class Palabra:

    def __init__(self, palabra):
        self.letras = deque(palabra)

    def es_palindrome_rec(self):
        if len(self.letras) > 1:
            return self.letras.popleft() == self.letras.pop() \
                    and Palabra(self.letras).es_palindrome_rec()
        else:
            return True

p1 = Palabra("reconocer")
p2 = Palabra("espectaculo")
p3 = Palabra("ana")
p4 = Palabra("OssO")

print(p1.es_palindrome_rec())
print(p2.es_palindrome_rec())
print(p3.es_palindrome_rec())
print(p4.es_palindrome_rec())
```
</details>

**Comment by pabloist** [comment]
Hola :)

Respondiendo a tus preguntas:

1.- Efectivamente la búsqueda de elementos en ciertas estructuras se realiza en un tiempo despreciable tendiendo a 0, razón por la cual se genera la excepción debido a que no está permitida la división por 0. Una forma de poder apreciar los órdenes de diferencia entre los tiempos de búsqueda y completar la actividad, es efectivamente agregar un time.sleep(n) con algún n lo suficientemente bajo para no incidir en los resultados.

2.- Con respecto a lo que consultas, no hay diferencias prácticas entre lo que comentas y como se ha escrito el código, es más que nada una formalidad al momento de escribir funciones.

Saludos!

**Comment by aaossa** [comment]
Solo para agregar a la respuesta ya entregada: en verdad lo segundo es prácticamente un error. Si bien no falla en los contenidos, sí es confuso y necesita ser arreglado. Dejaré esta *issue* abierta hasta arreglarlo en el repositorio privado de contenidos 😅

**Comment by fernandosmither** [comment]
Muchas gracias @pabloist y @aaossa ! 😄
