### ISSUE TITLE
Libreria tabulate para la Tarea 0

### ISSUE THREAD

**Issue by aLotOfGluten** [IIC2233/Syllabus#24]
¡Hola! Puedo usar la librería tabulate para hacer hacer tablas en la tarea 0?

**Comment by Juampisaez** [comment]
Hola @aLotOfGluten 
Recuerda que las preguntas sobre libreria se realizan en la issue [Librerías permitidas, no permitidas y malas prácticas T0](https://github.com/IIC2233/Syllabus/issues/21).
Ahora bien, contestando a tu duda, **no se puede ocupar esa librería** ya que suponiendo el caso que la ocupes para realizar el ranking, la idea es que puedas crear este desde cero. Es decir, que inventes tu el formato en que quieres mostrar este u otra cosa.

Quedo atento a cualquier otra duda :)
