### ISSUE TITLE
Pregunta sobre indentacion segun estandares del curso

### ISSUE THREAD

**Issue by juacob** [IIC2233/Syllabus#24]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola no me quedo claro a lo que se refiere que no podemos usar tabs y que debemos usar 4 espacios para la indentacion, al menos en pycharm la configuracion estandar es que un tab equivale a 4 espacios, en estos casos si se puede usar tab? o el usar la tecla tab afecta el codigo de otra manera?

**Comment by fffonceca** [comment]
Hola @juacob , no soy ayudante pero creo que puedo responder esto. Se usan los 4 espacios para no tener problemas de compatibilidad entre editores de texto. Si PyCharm poner cuatro espacio al "tabear" entonces no debería haber ningún problema, igual puedes corroborar revisando tu mismo código.

Saludos!

**Comment by Emiliax16** [comment]
Hola! tal como dice @fffonceca , pueden haber hartos problemas de compatibilidad si no se usa la indentación pedida (4 espacios). Si estas utilizando PyCharm, revisa bien que ese tab marque los 4 espacios. En muchos editores viene por defecto que el tab **deje el mismo espacio** que al hacer **4 espacios**, pero no necesariamente cumple el mismo rol. Por ejemplo, la identación la puedes ver de estas dos maneras:

-Utilizando 4 espacios
`....`

-Utilizando un tab (que equivale a 4 espacios)
`____`

Como se puede ver, no es lo mismo. Por eso se debe tener mucho ojo con ese detalle! En otros editores como SublimeText y Vscode debes configurarlo tu mismo para dejar predeterminado que el tab te haga efectivamente los 4 espacios. Espero que se haya entendido. Saludos!

**Comment by juacob** [comment]
> Hola! tal como dice @fffonceca , pueden haber hartos problemas de compatibilidad si no se usa la indentación pedida (4 espacios). Si estas utilizando PyCharm, revisa bien que ese tab marque los 4 espacios. En muchos editores viene por defecto que el tab **deje el mismo espacio** que al hacer **4 espacios**, pero no necesariamente cumple el mismo rol. Por ejemplo, la identación la puedes ver de estas dos maneras:
> 
> -Utilizando 4 espacios `....`
> 
> -Utilizando un tab (que equivale a 4 espacios) `____`
> 
> Como se puede ver, no es lo mismo. Por eso se debe tener mucho ojo con ese detalle! En otros editores como SublimeText y Vscode debes configurarlo tu mismo para dejar predeterminado que el tab te haga efectivamente los 4 espacios. Espero que se haya entendido. Saludos!

Hola si, entiendo hay alguna forma de asegurarme de que la indentacion que uso sea la misma que pide el curso?, porque pycharm dice que son 4 espacios pero quiero asegurarme. Gracias!

**Comment by Emiliax16** [comment]
@juacob en realidad si te aparece que son 4 espacios, deberías estar bien 😸 Aunque siempre puedes chequear las configuraciones. Te dejo un link de cómo se haría:

https://programmerclick.com/article/18061365851/

Saludos!

**Comment by juacob** [comment]
> @juacob en realidad si te aparece que son 4 espacios, deberías estar bien 😸 Aunque siempre puedes chequear las configuraciones. Te dejo un link de cómo se haría:
> 
> https://programmerclick.com/article/18061365851/
> 
> Saludos!

Gracias!
