### ISSUE TITLE
Problema con CMD en windows para abrir Jupyter

### ISSUE THREAD

**Issue by jorge-schenke** [IIC2233/syllabus#24]
Cuando trato de abrir un .py con jupyter no la consola no entra a la carpeta en la que lo tengo guardado y dice "El sistema no puede encontrar la ruta especificada", cómo lo puedo solucionar?

**Comment by igbasly** [comment]
Hola @jorge-schenke :v:

No estoy seguro de entender bien cuál es tu problema, por favor indícame más detalles al respecto o adjunta una captura de la terminal. De esta forma puedo colocar todo más en contexto.

Saludos, quedo atento :smile:.
