### ISSUE TITLE
Variacion del mapa entre niveles

### ISSUE THREAD

**Issue by svilaza** [IIC2233/Syllabus#240]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola tengo una duda respecto a la distribución del mapa cuando se pasa de nivel. La distribución del mapa tiene que ir cambiando entre niveles o puede mantenerse igual para todos los niveles? Es decir,  si primero la distribución es carretera-rio-carretera puede mantenerse igual o tiene que ir variando a otras como por ejemplo rio-rio-carretera (obviamente respetando el enunciado de tener necesariamente un rio y una carretera)?

**Comment by catalinacarter** [comment]
Hola @svilaza! Puede mantenerse igual si quieres, ya que en el enunciado no se hace referencia a modificar la distribución del mapa cuando se pasa de nivel. Solo debe existir como mínimo un área de río y una de carretera, siendo la tercer área elegida por ti (río o carretera). Como aparece en el enunciado: "queda a tu criterio cómo implementar el mapa con sus respectivas áreas , considerando que se cumpla con lo anteriormente especificado" :)
