### ISSUE TITLE
Solucion ayudantia 3

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#240]
Hola van a subir la solución de la ayudantia 3?
Es para poder estudiar de ella para la actividad de esta semana 
Gracias de antemano

**Comment by Drpinto1** [comment]
Hola!

Se subirá la solución durante el día de hoy y se mandará un anuncio cuando esté arriba.
(La idea era subirla antes, pero encontramos un error extraño que queremos solucionar antes de subirla)

¡Saludos!

**Comment by JuaniAndres** [comment]
ok muchas gracias
