### ISSUE TITLE
Error Pycharm

### ISSUE THREAD

**Issue by jfpena1** [IIC2233/syllabus#240]
Hola, cada vez que trato de correr mi programa me salta un error:
Process finished with exit code -1073741819 (0xC0000005)

Lo busqué en google y trate de reolverlo con lo que decian pero no me funcionó, nose si alguien ha tenido ese error y puede ayudarme con su experiencia. Muchas gracias.

**Comment by roberto009** [comment]
Hola!
Lo que pasa es que tu programa debe tener algún error, pero al usar PyQt5 este no te lo muestra.
Prueba cambiando el `sys.__excepthook__`  por el `hook` que les dan en los contenidos. Este puedes encontrarlo en la sección *Debuggeo en Pyqt5* del material de __Main Window__.
Saludos y éxito en la tarea !

**Comment by lfuenzalida2** [comment]
Hola, me esta ocurriendo el mismo error, trato de debuggearlo y no me deja, me sigue apareciendo el mismo error y lo hice tal cual como dice en el jupyter
