### ISSUE TITLE
Distribucion cura

### ISSUE THREAD

**Issue by Jaluco** [IIC2233/Syllabus#240]
Cuando se descubre la cura esta comienza a distribuirse via aire. Pero cuando alguna de las conexiones cerró su aeropuerto con el pais que tiene la cura, esta se abre porque su vecino tiene la cura? Si un pais y su vecino tienen los aeropuesrtos cerrados el vecino tambien abre su aeropuesrto si el pais con la cura lo abre?

**Comment by FernandoPieressa** [comment]
Como sale en la seccion de gobierno, cuando un pais tiene el aeropuerto cerrado y su vecino tiene la cura, el gobierno popondra abrir el aeropuerto con prioridad muy alta (1) y de ahi cuando sea elegido por la cola de prioridades sera abierto. Respecto al primer pais con la cura este abrira su aeropuerto para poder entregarla a los otros paises.

Saludos!

**Comment by berrazuriz1** [comment]
Pero no puede abrir sus fronteras si sigue cumpliendo con los requisitos que las cerraron en primer lugar, o eso sale en el enunciado. Por lo que abrir fronteras es imposible, a menos que los infectados hayan disminuido por que se murieron. ¿Es así o no importa si siguen cumpliendo con los requisitos de cierre, si un vecino tiene la cura abren sus fronteras si o si?.

**Comment by nivek0o0** [comment]
Yo entiendo que cuando hay cura, todo lo demás deja de importar.
