### ISSUE TITLE
Consulta Jugadores Totales 4.1.2

### ISSUE THREAD

**Issue by emeiese** [IIC2233/Syllabus#240]
Hola! En la parte 4.1.2 de la Tarea dice "calcular estadísticas tanto para jugadores como para la población de jugadores totales". Con esto se refiere a consultar sólo para el grupo de 200 jugadores que se inician con la GUI o hay que calcular considerando a los 5000 jugadores de la base de datos?

**Comment by cilopez** [comment]
Es considerando la cantidad **total de jugadores** en la base de datos, acuérdate que en esta parte las consultas son por consola.

**Comment by jachavarri** [comment]
Perdón si no entendí completamente el enunciado pero ¿quieres decir que tenemos que hacer un programa aparte de `demo.py` solo para las consultas?

**Comment by cilopez** [comment]
@jachavarri  supongo que estas modularizando, en ese caso  tendrías las consultas en un modulo aparte de `demo.py`, en aquel modulo puedes escribir `if __name__ == "__main__"` para que se puedan probar tus consultas de sin necesariamente usar la GUI.
