### ISSUE TITLE
aumento vs AUMENTO_NUTRIENTE / potencilantro

### ISSUE THREAD

**Issue by xperseosses** [IIC2233/Syllabus#240]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Me queda la duda si es que AUMENTO_NUTRIENTE% es lo mismo que aumento en la formula de abajo, porque entonces no debería estar dividido por 100.

<img width="1022" alt="Captura de pantalla 2024-08-31 a la(s) 9 11 08 p  m" src="https://github.com/user-attachments/assets/94953a6b-ea72-4178-8859-c12bb8fb07c1">

**Comment by rodrigoaguilera15** [comment]
Sí, es lo mismo. Respecto al parámetro y la fórmula son referenciales en ese sentido, tú puedes decidir si defines el parámetro como un número de orden 10 o más y luego lo divides por 100 en la fórmula, o si por el contrario lo defines como un número de orden 0.1 o más y entonces no lo divides. Espero que quede claro, quedo atento.
