### ISSUE TITLE
Buena/Mala práctica - Ejecutar función externa con "self" como argumento

### ISSUE THREAD

**Issue by ljgonzalez1** [IIC2233/syllabus#240]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda:

Quería saber si se considera una mala práctica meter a una instancia de una clase como argumento para otra función.

Pongo un código que contiene el caso:

```
 1 import random
 2
 3 class MiClaseA:
 4     def hacer_algo(self, clase)
 5         clase.atributo1 *= 1.7
 6
 7
 8 class MiClaseB:
 9     def hacer_algo(self, clase)
10         
11         clase.atributo2 += 2
12 
13 class MiClaseC:
14     def __init__(self):
15         self.atributo1 = 1
16         self.atributo2 = 0
17         self.clases = (MiClaseA(), MiClaseB())
18     
19     def cosa_misteriosa(self):
20         funcion = random.choices(self.clases).hacer_algo
21         funcion(self)
```

Las únicas alternativas que se me ocurren para ejecutar la función seleccionada en el random son:
**Opción 1** (La que estoy usando ahora)
```
21         funcion(self)
```

**Opción 2**: La encuentro más confusa en programas más complejos por temas de longitud y cantidad de variables involucradas. La única ventaja que le veo es que sé que todo los cambios en instancias de MiClaseC ocurren dentro de ésta.
```
 4     def hacer_algo(self, atributo1, atributo2)
 5¹        atributo1 *= 1.7
 5²        return atributo1, atributo2

 9     def hacer_algo(self, atributo1, atributo2)
11¹        atributo2 += 2
11²        return atributo1, atributo2

21         self.atributo1, self.atributo2 = funcion(self.atributo1, self.atributo2)
```

**Opción 3**: 
¿Sugerencias? No se me ocurre más que no implique agregar como 20 líneas innecesarias.

**Comment by aaossa** [comment]
Hola @ljgonzalez1 , estoy algo medio confundido con tu código 😅 Espero poder responderte de todas maneras. Lo que veo que estás preguntando difiere un poco de lo que muestras, así que intentaré responder a "¿Puedo usar una instancia de una clase como argumento de una función?" y "¿Cómo puedo ejecutar una función sobre la instancia actual (`self`)?".

Si le das una vuelta, todo el tiempo estamos entregando instancias de clases a nuestras funciones... por ejemplo mira este pedazo de código de la AF2, que recibe una instancia de una clase definida en otro modulo:

https://github.com/IIC2233/syllabus/blob/7921bc5a43cb61b3bc1ec9891ab34b87660bd35a/Actividades/AF2/calcular_ruta.py#L4-L11

Entonces, la respuesta a tu primera pregunta es "Claro que yes". En particular, imagina que tienes una lista de instancias de clase `Estudiante` y yo quiero seleccionar una instancia al azar para pedirle que responda una pregunta mientras estamos haciendo el repaso en la clase: `random.choice(estudiantes)` me va a retornar dicha instancia. Si quieres ejecutar una función sobre más de una instancia solo ocupas la variable 🤔 

```python
# Guardo mis instancias en una lista
estudiantes = [Estudiante(*datos_estudiante) for datos_estudiante in datos_de_estudiantes]
# Selecciono al azar
estudiante_que_responde = random.choice(estudiantes)
# Ejecuto un método (nada de self)
estudiante_que_responde.responder()
```

Ahora, sobre si se puede ejecutar una función sobre la instancia actual (`self`), la respuesta también es sí. Usar `funcion(self)` es perfectamente posible, pero la verdad no he visto algo así que recuerde ahora 😅, pero eso no significa que sea mala práctica, solo que quizás haya una mejor forma de hacerlo (un método tal vez, o llamar la función fuera de la clase). 

**PS:** Justo antes de terminar de responder creo que identifiqué otra pregunta 😅 "¿Puedo modificar atributos de una clase en un método de otra clase?" La respuesta es que en teoría (y en la práctica) sí puedes. Sin embargo, más adelante en el curso vamos a ver que esto no es muy buena práctica, porque oculta comportamiento que podría convertirse en inesperado y además genera un problema con las "responsabilidades" de cada clase. Siempre es mejor que una instancia sea quien aplique cambios (en los atributos) sobre sí misma, porque es lo que hace más sentido. El llamar un método de otra clase como en tu ejemplo para modificar un atributo propio no es intuitivo y sí es mala práctica. Lo que tienes que preguntarte ahí es por qué necesitas que otra clase lo haga. Quizás solo necesites tirar el dado (el random) y hacer el cambio, o tal vez modificar tu propio atributo antes de llamar al método de la instancia.

Creo que estás enredándote un poco en lo que quieres hacer, pero si entendí mal tu pregunta responde y vamos conversando por acá. ¡Mucho éxito en tu estudio ✨!

**Comment by ljgonzalez1** [comment]
Muchas gracias.

Quedé sólo con una duda aquí:
_"Lo que tienes que preguntarte ahí es por qué necesitas que otra clase lo haga. Quizás solo necesites tirar el dado (el random) y hacer el cambio, o tal vez modificar tu propio atributo antes de llamar al método de la instancia"._

Si en el código que había escrito al principio, `MiClaseA` o `MiClaseB` tienen una influencia sobre los lo que ocurre en `MiClaseC`, ¿qué recomendarías para modificar los atributos en la última para poder hacer los cambios de forma eficiente?¿Tener un método en `MiClaseC` para cada posible `MiClase_i` que pueda estar en la tupla `MiClaseC.clases`?
¿O ver cómo abordar el problema de forma completamente distinta?

No sé si me explico muy bien. Pero extendiendolo a _n-1_ casos, esta es la idea general de la situación a la que me enfrento y no sé cómo tratar adecuadamente sin usar malas prácticas:

```
 1 import random
 2 
 3 class MiSuperClase:
 4     pass
 5 
 6 # --------------------------        
 7 
 8 class MiClaseA(MiSuperClase):
 9     def hacer_algo(self, clase)
10         clase.atributo1 *= 1.7
11         
12 class MiClaseB(MiSuperClase):
13     def hacer_algo(self, clase)
14         clase.atributo2 += 2
15         
16 class MiClaseD(MiSuperClase):
17     def hacer_algo(self, clase)
18         ...
19                 
20 class MiClaseE(MiSuperClase):
21     def hacer_algo(self, clase)
22         ...
23         
24 ...
25 
26 class MiClaseN(MiSuperClase):
27     def hacer_algo(self, clase)
28         ...
29 
30 # --------------------------        
31         
32 class MiClaseC:
33     def __init__(self):
34         self.atributo1 = 1
35         self.atributo2 = 0
36         self.atributo3 = 'texto'
37         ...
38         self.atributo_m = dict()
39         
40         self.clases = random.sample(
41             [MiClaseA(), MiClaseB(), MiClaseD(), 
42              MiClaseE(), MiClaseF(), ..., MiClaseN()],
43             k=random.randint(5, 10)
44            )
45     
46     def cosa_misteriosa(self):
47         funcion = random.choices(self.clases).hacer_algo
48         funcion(self)
```

Tengo un numero indeterminado de clases que son instanciadas dentro de otra y "hacen algo" sobre los atributos de la última.
Las clases _A_ a la _N_ (exceptuando la _C_) son algo completamente distinto a la _C_ en temática y funcionamiento. Casi tanto como para tenerlos en módulos distintos, por eso no defino el contenido de las _n-1_ clases dentro de _C_.

**Comment by aaossa** [comment]
Hola @ljgonzalez1 , en verdad me cuesta encontrar un caso en el que realmente se de una situación así, al menos no recuerdo haber visto o tenido un problema como ese 🤔 En primer lugar creo que el problema es confuso porque idealmente quieres evitar tener una doble referencia en cuanto a modificaciones de una clase sobre otra. A lo que me refiero es que una clase `A` puede hacer cambios sobre una clase `B`, pero difícilmente la clase `B` hará a su vez cambios sobre la clase `A`, ya que en este caso `A` es quien controla las acciones. Digo difícilmente porque no me parece que, asumiento una buena modelación, se justifique esa doble relación. Personalmente, lo que creo que haría es algo así:

```python
class SubclaseA(Superclase):
    # ...
    def hacer_algo(self):
        # ...


class ClaseEnCuestion:
    # ...
    def cosa_misteriosa(self):
        instancia_elegida = random.choice(self.instancias)
        instancia_elegida.hacer_algo()
        if isinstance(instancia_elegida, SubclaseA):
            self.atributo = 1
        elif isinstance(instancia_elegida, SubclaseB):
            self.atributo = 2
        # ...
```

Entiendo también tu preocupación sobre cómo crecería el código extendiendo a un caso de N clases, pero difícilmente este sea el caso en la práctica. No te preocupes de optimizar tan tempranamente cuando no hay certeza de que dicha optimización vaya a ser útil/necesaria a futuro.

Viendo tu nuevo ejemplo también se me ocurrió que quizás podrías almacenar en un atributo de tus "N clases" la "modificación" que sufre la clase principal. Aunque me cuestionaría si esto es realmente un atributo de la clase. Si bien el código va a verse más limpio, quizás en la modelación no haga mucho sentido o no se justifique, por lo que probablemente me quedaría con la primera solución. De todas maneras, el código que pensaba sería algo así:

```python
class SubclaseA(Superclase):

    def __init__(self, ...):
        # ...
        self.factor = 1.5
        # ...


class ClaseEnCuestion:
    # ...
    def cosa_misteriosa(self):
        instancia_elegida = random.choice(self.instancias)
        instancia_elegida.hacer_algo()
        self.atributo = self.atributo * instancia_elegida.factor
```

O también puedes calcular el nuevo valor del atributo en cada subclase. Nuevamente, solo haría esto si hiciera sentido con la modelación (lo que es difícil de saber ahora considerando que estamos hablando con nombres de ejemplo en las clases):

```python
class SubclaseA(Superclase):
    # ...
    def calcular_valor(self, valor_inicial):
        # ...


class ClaseEnCuestion:
    # ...
    def cosa_misteriosa(self):
        instancia_elegida = random.choice(self.instancias)
        self.atributo = instancia_elegida.calcular_valor(self.atributo)
        # ...
```

Espero que alguno de estos ejemplos haga sentido con tu modelación 🤔 Es un buen problema el que planteas, y probablemente haya una solución "correcta" (desde un punto de vista del diseño de software), pero prefiero plantear más de una solución posible siempre destacando que lo importante es que la modelación haga sentido. ¡Gracias por tu pregunta 👌!

**Comment by ljgonzalez1** [comment]
Muchas gracias
