### ISSUE TITLE
Compra de gato

### ISSUE THREAD

**Issue by javibust** [IIC2233/Syllabus#240]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Buenas tardes.

El enunciado dice que cuando compro un gato, este se obtiene aleatoriamente del archivo unidades.
¿Al comprarlo, se elimina la opción de poder comprarlo nuevamente? ¿Es decir, debo eliminarlo de las opciones aleatorias de una próxima compra? 
En caso de no eliminarse nuevamente,¿ se considera como un gato nuevo aunque tenga los mismos atributos que un gato ya perteneciente a los combatientes de mi ejército? ¿O si se compra por segunda vez se cobra el costo pero no se suma al ejército? Ya que al instanciar dos veces un mismo gato de unidades, cuando muere uno, el otro pasa a tener vida 0.

Muchas gracias de antemano.

**Comment by coniverav** [comment]
Cuando se habla de que se compra un gato "aleatorio", significa que se compra una instancia cualquiera de la lista de unidades (por ejemplo, siempre la primera aparición) o se refiere a literalmente a usar un `random`?
