### ISSUE TITLE
Mejor/peor amigo

### ISSUE THREAD

**Issue by antoniacobo** [IIC2233/Syllabus#241]
Hola! En la consulta del mejor o peor amigo, debemos entregar uno o todos los que tengan mayor/menor afinidad? Si tengo dos jugadores con afinidad 1, debería entregar esos dos jugadores o con uno basta.

**Comment by cilopez** [comment]
Como no se detalla en el enunciado puedes especificarlo en tu  `readme.md` , personalmente creo que lo correcto sería entregar a todos pero esto queda a tu criterio.
