### ISSUE TITLE
POND_EFECT_... (T01)

### ISSUE THREAD

**Issue by mmrodriguez5** [IIC2233/syllabus#241]
No entiendo a que corresponde POND_EFECT_HIELO, POND_EFECT_ROCAS, POND_EFECT_DIFICULTAD, ya que estos no estan en parametros.py y el enunciado no los especifica.
Agradeceria mucho que me aclararan la duda

**Comment by mjvarela** [comment]
Hola! Revisa la issue #174 ahí responden la misma duda. Suerte!
