### ISSUE TITLE
Duda puntaje ventana de juego

### ISSUE THREAD

**Issue by catalinacifuentes** [IIC2233/Syllabus#241]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Tengo una duda con el enunciado en la parte de puntaje. En el apartado "Puntaje y vidas" dice "Al completar un nivel se obtendrá un puntaje que se se calculará según la siguiente fórmula...". Como dice al completar un nivel, y ademas la formula depende del tiempo restante, pensé que el puntaje se otorgaba una vez que se terminaba el nivel. Pero luego en la Ventana de Juego se pide que mostremos el puntaje obtenido en el nivel, por lo tanto ¿Se tendría que ir calculando cada segundo? ¿O debería mostrar el puntaje acumulado en el juego?

**Comment by ivanvlam** [comment]
Hola @catalinacifuentes ! En el enunciado dice que se tiene que mostrar el puntaje de la ronda, pero como el puntaje se calcula al final, siempre será cero, entonces no tiene mucho sentido (pero dado que está en el enunciado, hay que ponerlo). Si además quieres poner el puntaje total que lleva de rondas anteriores también lo puedes poner. Eso si, el puntaje total no reemplazaría al puntaje de la ronda, así que tendrías que poner los dos: puntaje actual y puntaje acumulado (pero esto es solo si quieres, ya que lo mínimo es poner lo del puntaje de la ronda).

**Comment by catalinacifuentes** [comment]
Super! Muchas gracias :)
