### ISSUE TITLE
Creación de .gitignore

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#241]
Hola!
Cómo podría crear el archivo .gitignore ? y éste debo crearlo cada vez que haga una tarea?, porque se supone que ahora para la T01, el gitignore debe estar dentro de la carpeta T01.
Me podrían explicar cómo crearlo y dejarlo en la carpeta que me piden, por favor :). Gracias.

**Comment by JosefaPaz** [comment]
¡Hola Camila!

Para crear el .gitignore que debes usar en las tareas puedes hacer dos cosas:

**1.  Usar el .gitignore del syllabus**

El gitignore del syllabus se encuentra aquí: [https://github.com/IIC2233/syllabus/blob/master/.gitignore](url), lo descargas y después añades a este archivo todos los documentos que desees ignorar. Lo guardas en tu carpeta de la tarea (en este caso T01) y luego lo subes junto a los otros archivos a tu repo en github. :octocat: 

**2. Crear un archivo .gitignore desde 0:**

Para crear un archivo .gitignore desde 0 puedes crear un documento de texto - esto puedes hacerlo con el bloc de notas - y guardarlo como ".gitignore" _(eliminando la extensión .txt que tiene por defecto)_. Dentro de este documento de texto escribes los archivos que deseas ignorar en tu repositorio y lo subes junto a tus otros archivos al repo de la tarea que corresponda. 😸

**Comment by Camila-sty** [comment]
Ok, ya lo tengo y lo dejé en la carpeta T01, pero cuando lo abro me abre el bloc de notas, a pesar de que lo guardé como ".gitignore", está bien?. 
Debo escribir los archivos que no quiero subir en el mismo bloc de notas?
Tengo otra duda, por ejemplo estando en la carpeta T01, donde tengo los archivos csv, el enunciado de la tarea, y ahora el ".gitignore", como sabe este último cuales son los archivos que quiero ignorar?, es porque deben estar en la misma carpeta?, por ejemplo si yo no hubiera guardado el enunciado en T01, y de igual forma quiero escribir este archivo prohibido en el ".gitignore", igual lo considerará?

**Comment by JosefaPaz** [comment]
- Sí, está bien que se abra en el un bloc de notas 😄 
- Sí, debes escribir los archivos que no quieres subir a tu repositorio en este bloc de notas ".gitignore".

Respecto a tu otra duda, el .gitignore sabe qué archivos debe ignorar porque claro, se encuentran en la misma carpeta y además porque tú escribiste dentro de .gitignore los archivos que debía ignorar, un ejemplo como este es el que sale en el syllabus:

![imagen](https://user-images.githubusercontent.com/41802643/78455380-6c17bb80-7674-11ea-9c5e-a8b2925af46a.png)

Si tú no hubieses guardado el enunciado en T01 pero de igual manera lo quieres ignorar en el .gitignore no pasará nada, solo no encontrará este archivo para ignorar 🐱

**Comment by Camila-sty** [comment]
Ok. Gracias!!!! :D

**Comment by Camila-sty** [comment]
Una duda mas jajaj. Los archivos que quiero escribir en ".gitignore" , debo escribirlos con su extensión? por ejemplo, el enunciado, lo escribiría como "Enunciado.pdf"?

**Comment by JosefaPaz** [comment]
jajaja sí! deben tener la extensión del archivo 🦄

**Comment by Camila-sty** [comment]
Ya, entonces sería algo como esto:

![Captura](https://user-images.githubusercontent.com/59337116/78455998-b8b0c600-7677-11ea-832b-4d4ea9f4991e.PNG)

Perdón por lo intensa, pero quiero estar segura de que esté bien y necesito que me lo confirmen jaja :D

**Comment by JosefaPaz** [comment]
No te disculpes! Está bien que quieras estar segura. Está bien, pero para que puedas confirmarlo te recomiendo subir los archivos a tu repositorio y luego revisarlo desde la plataforma de github, así podrás verificar bien si estás haciéndolo bien 😄

**Comment by Camila-sty** [comment]
Ya gracias :100: 
Para subirlo, bastaría hacer "git add . " para que se suba todo y de por sí el archivo ".gitignore" hace el trabajo de no subir lo que escribí en el?. Igual no tengo ningún archivo ".py" , por lo tanto al usar "git add . ", se subiría éste mismo, mas el README que también esta en la carpeta.... ¿?

**Comment by JosefaPaz** [comment]
¡Exacto! Pasaría todo lo que dijiste :)

**Comment by Camila-sty** [comment]
Muchas gracias por tu ayuda :+1:

**Comment by JaviGuzman** [comment]
Tengo una duda de esto mismo. Hice el archivo de texto desde sublime text (en mac) y al guardarlo como ".gitignore" me dice que al empezar con un . el archivo estará oculto, por lo que después de escribir los archivos que no quiero que se suban dentro de este archivo, el archivo .gitignore no me aparece en la carpeta T01. De esta forma no puedo volver a abrirla y cambiar los archivos que quiero ignorar.

**Comment by JosefaPaz** [comment]
@JaviGuzman,

Deberían poder abrir el archivo de igual forma en un editor de texto aunque aparezca oculto. De todas formas, para ver los archivos ocultos puedes apretar ``` cmd + shift + . ``` dentro de la carpeta T01, ahí debería aparecerte y vas a poder editarlo 😄

**Comment by dsepulveda3** [comment]
![image](https://user-images.githubusercontent.com/62180259/79782006-61b01f80-830c-11ea-94b4-59fe0c5a1f9c.png)

Hola subi esto a mi respositorio pero me siguen apreciendo los archivos magizoologos.csv, criaturas.csv y Enunciado.pdf.
Alguna pista de porque podría estar pasando?
Saque el archivo del syllabus, lo copie y pegue en mi carpeta. Le elimine todo y escribí lo que dice en la foto. Luego lo subí

**Comment by JosefaPaz** [comment]
¡ Hola @dsepulveda3 !

El error puede deberse a que estos archivos ya se encontraban arriba en tu repositorio antes de subir el .gitignore, por lo que intenta eliminar estos del repositorio, y luego subirlos nuevamente junto con el .gitignore para ver si funciona correctamente.

Avísame!

**Comment by dsepulveda3** [comment]
Buenísimo! Ahí me funcionó. Gracias
