### ISSUE TITLE
Puntajes no especificados - caminos

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#241]
Holaa, cuánto puntaje suma cuando:
1.- Un camino junta dos ciudades ambas completas.
2.- Un camino o río tiene uno o ambos de sus extremos que no conecta nada, no suma puntos? Y si el camino o río tiene bifurcaciones, y dos extremos conectan dos ciudades, pero el tercer extremo nada, las fichas de las bifurcaciones suman de igual manera?
3.- Los 40*n puntos adicionales cuando se conectan n>2 ciudades, son por ficha o es un bonus fijo?

Gracias!

**Comment by MariaJosefinaAlliende** [comment]
A mí no me queda claro si los cruces de caminos en este juego se toman como bifurcaciones del mismo camino o  si el camino se termina al llegar a una bifurcación (como en Carcasonne).  Mi duda es realidad es  si el camino tras una bifurcación es una identidad nueva o no.

**Comment by stephichau** [comment]
@B-Dominguez fijate en #223
@MariaJosefinaAlliende no entendí tu duda :(

**Comment by MariaJosefinaAlliende** [comment]
@stephichau  Gracias por responder :). Mi problema es que las fichas  GGPGPP y PPGPPG tienen caminos con cruces, es decir donde en el dibujo el camino no continúa, sino que se separa en partes y esto hace que la ficha tenga 3 o más lados con caminos. No entiendo si si en este tipo de fichas los caminos pasan a ser caminos diferentes o si tengo que considerar las dos ramas del camino como si fuesen de uno solo . Si fuese la primera opción, al poner una ficha con cruce el camino se consideraría cerrado y por lo tanto los caminos nuevos que salgan de los cruces podrían ser de otro jugador, o aunque fuesen  del mismo, afectaría a la hora de considerar si el camino conecta o no a dos ciudades...

**Comment by stephichau** [comment]
@MariaJosefinaAlliende en el caso de la pieza GGPGPP:
![ggpgpp](https://user-images.githubusercontent.com/16126322/30249461-8790249a-9613-11e7-83ff-62b3e58272e3.png)
son tres caminos que terminan en ese punto.
Por otra parte, en el caso de la pieza PPGPPG
![ppgppg](https://user-images.githubusercontent.com/16126322/30249471-b2ea78ac-9613-11e7-9aa7-2e7cbc87f67b.png)
son cuatro caminos que terminan en ese punto.

Espero que te haya quedado más claro :)

**Comment by MariaJosefinaAlliende** [comment]
@stephichau  Buenísimo! Muchas gracias!! :)

**Comment by B-Dominguez** [comment]
@stephichau pero en ese caso nunca habrían caminos que conecten n>2 ciudades, y por lo tanto nunca se asignaría ese puntaje bonus (_40*n puntos adicionales_)
No pierdo puntaje por eso?

**Comment by Sforrego** [comment]
Tengo la misma duda que B-Dominguez

**Comment by cilopez** [comment]
@B-Dominguez  @Sforrego mencionen en su _readme_ esta situación, pero en teoría su juego debería tener de todas formas el algoritmo de calculo si existen _n_ ciudades, porque hipotéticamente podría existir una nueva pieza que haga cumplir esta condición.
