### ISSUE TITLE
Probabilidad de muerte #queVuelvaELmin

### ISSUE THREAD

**Issue by stgoa** [IIC2233/Syllabus#241]
si proba_de_muerte:=min(max(0.2 ; dias^2 / 100000) , 1)

eventualmente (316 dias) mueren todos los infectados del pais inicial y el juego se corta.*  (de hecho no es necesario que pasen 141 dias.. la proba ya es muy significativa a los pocos dias)

*La forma en que la probabilidad de muerte crece es demasiado grande en comparacion a la proba de contagio entre paises.. luego el juego se estabiliza muy rapido pues todos los infectados iniciales mueren... 

yo creo que queda mejor con proba_de_muerte:=min(min(0.2 ; dias^2 / 100000) , 1)

asi no crece mas allá de 0.2 y la infeccion puede llegar a otros paises antes de que todos los infectados mueran...

salu3

**Comment by AmbrosioV** [comment]
#queVuelvaELmin en #235 se plantea lo mismo pero al revés, o se aumenta la tasa de contagio o se tienen que morir menos, porque francamente es casi imposible expandirse a un buen ritmo sin exterminar a los infectados que se necesitan para expandirse

**Comment by benjamimo1** [comment]
+1

**Comment by rfenzo** [comment]
+1, la verdad es que llevo como 3 dias perdidos tratando de que la simulacion alcance a llegar a otro país, ya no se que hacer, he revisado el codigo artas veces y creo que son las fortmulas mal balanceadas, una vez que la infeccion está apta para contagiar otros paises solo tiene uno o dos días para contagiar (con una probabilidad bajísima) antes de que se cierren las fronteras, en ese momento el pais ya esta condenado a morir. Por favor arreglen esto lo antes posible...

**Comment by ranieto** [comment]
@rfenzo si el problema fuesen las fórmulas entonces a nadie le funcionaría. A mí por lo menos sí me funciona y se demora ~30 días en contagiar otro país.
En todo caso, en #235 se dijo que podían cambiar la fórmula para infectar otros países.

**Comment by FernandoPieressa** [comment]
Hola!

Si encuentran que la formula no funciona como lo esperan pueden cambiarla un poco para que cumpla y tenga sentido. Eso si, de hacerlo TIENEN que escribir en el readme que cambio hicieron.

saludos!

**Comment by acrojas2** [comment]
@FernandoPieressa  puedo cambiar todos los min por max, para poder infectar mas rapido ?

**Comment by Hernan4444** [comment]
@acrojas2 si puedes pero no olvides especificarlo.

Saludos!
