### ISSUE TITLE
Cantidad de palabras en argumento línea de consola

### ISSUE THREAD

**Issue by augustayanez** [IIC2233/Syllabus#241]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Para el caso de el argumento que se recibe en la consola, que se supone que tendrá el formato python main.py dificultad , *si es que después de la dificultad hubiesen más argumentos pero la dificultad fuese válida, debo considerar el archivo como válido?*
Con esto me refiero a un argumento como este: python main.py intermedio unidades

**Comment by Benjeeeh** [comment]
Hola!
No, no debería considerarse válido. Esto es parte de la robustez, y el enunciado menciona explícitamente que solo debe entregarse un parámetro, por lo que si se entregan más debería arrojarse un mensaje de error:
![image](https://github.com/IIC2233/Syllabus/assets/78326186/1313f407-aaf3-4626-b7a0-5f1c67e7d9fd)
