### ISSUE TITLE
Personaje atrás del mapa

### ISSUE THREAD

**Issue by isihirmas** [IIC2233/syllabus#241]
Hola! Logré cargar el mapa con QGridLayout(), pero me pasa que el personaje esta "atrás" del mapa, como "debajo" de los cuadrados.
Saben como puedo arreglar esto?

Gracias!

**Comment by LucianoDavico** [comment]
Hola, creo que si cargas el mapa antes de cargar el personaje te va a salir el personaje "encima" de la grilla.

**Comment by isihirmas** [comment]
Hola, hice el cambio de poner el def_ init_GUI antes del  init del juego y no me funcionó.

**Comment by jalliende** [comment]
creo que existe la función  raise() por lo que leí en otra issue .

**Comment by isihirmas** [comment]
que issue es? no la encontré. Intenté hacer self.frontend_character.raise() pero me dice que QLabel() no tiene raise.

**Comment by Hernan4444** [comment]
Hola, lo que dice @LucianoDavico  solucionará el problema. Para detallar más, el no dice que pongas el `def init_GUI(self)` antes del `__init__`, sino que primero ejecutes las líneas que cargan el mapa y luego ejecutes las líneas que cargan el personaje. 

Saludos :v:

**Comment by isihirmas** [comment]
Lo que hice fue crear una ventana solo de mapa y desde ahí llamé a MainGame, pero tampoco aparece el personaje :(

**Comment by jeschuwirth** [comment]
> que issue es? no la encontré. Intenté hacer self.frontend_character.raise() pero me dice que QLabel() no tiene raise.

Hola!

La issue de la que se habla es la #225 

Ojalá te ayude!

**Comment by isihirmas** [comment]
me sirvió gracias!
