### ISSUE TITLE
T0 bomba especial que cubre todo el tablero

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2233/syllabus#241]
hola, tengo una duda respecto de las bombas especiales, por ejemplo si la bomba rombo tiene un radio muy grande, puede ser que cubra todo el tablero y sea un win automático?, o debemos definir un máximo para r?

**Comment by kadroguett** [comment]
Hola @vice-rosas99, esta pregunta fue respondida en la issue  #137

**Comment by vice-rosas99** [comment]
ups perdon, busque por bomba y no había encontrado nada
