### ISSUE TITLE
Stackeo en aumentos en produccion

### ISSUE THREAD

**Issue by monejo1** [IIC2233/Syllabus#241]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

Los aumentos de producción se stackean? es decir, si yo tengo dos potencilantros a distancia aumentable de un mismo solaretillo, se aumentará el porcentaje una sola vez o 2 veces?

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by rodrigoaguilera15** [comment]
Hola qué tal? Respecto a eso, no está explícito en el enunciado entonces puedes decidir si stackean o no. Recuerda dejar claro lo que hiciste en el README. Saludos.
