### ISSUE TITLE
¿Barco sin mercancia == Costo de mantención infinita?

### ISSUE THREAD

**Issue by Nicolasramos411** [IIC2233/syllabus#241]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Una duda, si un barco carguero es robado por piratas entonces no podrá pagar la tarifa de salida del canal. ¿Esto implica que tendremos que pagar un costo de mantención por hora al barco por cada hora que siga durando la simulación?

Gracias!

**Comment by santiagovegaf** [comment]
Hola @Nicolasramos411!

Si un barco es atacado por piratas este sale del canal sin pagar tarifa, ya que no tiene cómo hacerlo. Se podría entender como hacer "perro muerto" en un restaurante. Espero que se entienda.

Éxito en tu tarea!
