### ISSUE TITLE
Error al Subir Archivo al Repositorio

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2233/syllabus#242]
Hola, sin querer subir un archivo de otro codigo al repositorio de la Tarea. Queria saber como podia sacarlo para que no genere confusion

**Comment by vicentevegaulloa** [comment]
Hola @conyfernandezt !

Debes usar el comando `git rm --cached path_de_tu_archivo ` con los archivos que quieras sacar. Recuerda usar el path relativo del archivo que quieres sacar. Para no subirlo nuevamente recuerda incluirlo en tu .gitignore!
