### ISSUE TITLE
Reservas de un equipo

### ISSUE THREAD

**Issue by mora4** [IIC2233/Syllabus#242]
Hola,

No entiendo de donde salen los reservas que se muestran en el GUI, si en el enunciado dice "El usuario debe ser capaz de crear su propio equipo con **11** jugadores de su preferencia".

Gracias!

**Comment by behrmann97** [comment]
La GUI la llamarás con 200 jugadores, con los cuales armarás un equipo de 11 jugadores con la GUI.

**Comment by behrmann97** [comment]
Actualizamos la GUI hace unos dias, el equipo parte vacío y puedes elegir los 11 jugadores iniciales. Al hacerles click se llama una funcion en demo.py con el nombre del jugador
