### ISSUE TITLE
Duda respecto al área del Cilantrillo

### ISSUE THREAD

**Issue by diego-herreras00112** [IIC2233/Syllabus#242]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Tengo dudas de como funciona el area nueva que afecta cilantrillo ya que dice que "genera soles y potencia en un cuadro de 8 casillas", no entiendo como se puede hacer un cuadrado de 8 casillas donde hay una casilla central. La unica diferencia con Potencilantro es que la casilla donde esta puesta esta planta tambien se potencia? o es en definitva un area nueva de potenciamiento?

**Comment by rodrigoaguilera15** [comment]
Hola qué tal? Como el enunciado dice que el cilantrillo potencia 8 casillas **y** a sí mismo, entonces efectivamente son 9 casillas. Entonces tal como tú dices, es la misma área de 3x3 casillas, pero en caso del potencilantro sin la casilla central, mientras que en caso del cilantrillo sí considerando la casilla central. Quedo atento.
