### ISSUE TITLE
Entidad Pista como tupla

### ISSUE THREAD

**Issue by SamWeinstein** [IIC2233/syllabus#242]
Hola! En mi programa, los datos de las pistas son fijos (no cambian) y ademas no tengo métodos específicos para la clase Pista. ¿Puedo manejar los datos de las pistas con namedtuple? Pues como los datos son inmutables y no necesito métodos específicos, me parece mucho mas lógico y eficiente manejar las pistas con tuplas en lugar de una clase. ¿Se me descontará puntaje? 
Aclaro que he modelado todas las otras entidades con clases (incluyendo los menus) pero esta me parece innecesario.
Gracias!

**Comment by RositaMunoz** [comment]
Hola @SamWeinstein!
En esta tarea se evalúa el uso de OOP, teniendo eso en cuenta, recomendamos fuertemente utilizar ésto. No te puedo decir si lo que estás haciendo está bien o no. 

Éxito con la tarea ^^
