### ISSUE TITLE
¿Barco encallado == barcos detrás siguen avanzando hasta cierto limite? 

### ISSUE THREAD

**Issue by Nicolasramos411** [IIC2233/syllabus#242]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Una duda, ¿Si un barco se encalla, los barcos detrás de él deben detenerse en ese instante o en el transcurso de las horas podrán avanzar hasta llegar a la posición de el barco encallado?

**Comment by matiasparodic** [comment]
Hola! Tengo la misma duda!

**Comment by manearaya** [comment]
Hola @Nicolasramos411 y @matiasparodic! Como se menciona en la issue #251, cuando un barco encalla los barcos que están detrás de él pueden seguir avanzando hasta esa posición: no se detienen inmediatamente, sino que cuando se topan con el barco encallado.

Espero que se entienda!
