### ISSUE TITLE
Clase Iterable e Iterador

### ISSUE THREAD

**Issue by fgbruna** [IIC2233/Syllabus#242]
No me queda claro por qué es necesario hacer un Iterable fuera de la EDD sobre la cual quiero iterar y fuera del iterador mismo.
Es posible definir el método `__iter__` dentro de la misma estructura ?

```python
""" 
No incluyo todos los metodos de mi modelacion,
solo los relacionados a la iteracion de manera simplificada
"""
class MiLista:
  def __init__(self, valor):
      self.head = None
      self.tail = None

  def __iter__(self):
      return IteradorDeMiLista(self.head)
  
  def append(self, valor):
       blablabla

class IteradorDeMiLista:
  def __init__(self, iterable):
        self.iterable = iterable.head

    def __iter__(self):
        return self

    def __next__(self):
      """
      Los objetos como self.tail y self. head tienen un atributo,
      llamado siguiente que es el que usa next.
      """
```
No sé si es una mala práctica o simplemente la forma de hacerlo en el material tiene algún sentido más adelante,pero por ahora,por lo menos para mi modelación ( Si es que se entiende :sweat_smile:) si me funciona usar `for`.

**Comment by fgbruna** [comment]
Alguien ? :cold_sweat:

**Comment by iqacevedo** [comment]
Hola,

Tal como dices no es necesario y puedes hacerlo sin definir esa clase extra.

Saludos !

**Comment by fgbruna** [comment]
Gracias @iqacevedo  !
