### ISSUE TITLE
Progreso de la cura

### ISSUE THREAD

**Issue by maxfreymo** [IIC2233/Syllabus#242]
En el enunciado dice que "Por día, cada país que tenga la cura entregara a todos los países que tenga acceso mediante aire la cura." 
¿Que pasa con aquellos países que no tienen aeropuerto? ¿Están destinados a morir si la infección llega a ellos?

**Comment by iqacevedo** [comment]
Eventualmente pueden morir u.u
Su única esperanza es que los infectados mueran antes de contagiar a toda su población 😨.
