### ISSUE TITLE
Duda sobre datos entregados en "unidades.txt"

### ISSUE THREAD

**Issue by ssepul21** [IIC2233/Syllabus#242]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!
 Si el archivo que me entregan pasa que, por ejemplo, la vida máxima de uno de los gatos combatientes es mayor a 100 (1000, por ejemplo), **¿cómo se debe tratar con el archivo?** Me queda la duda de si debo decir que el archivo entregado es completamente erróneo y solicitar otro, si debo eliminar el gato combatiente o si debo dejarlo y limitarlo al máximo posible del atributo (en este caso, sería 100). 
 La misma duda me queda con respecto a si la vida máxima es 0: **¿hay alguna solución concreta al respecto?**

 Saludos!

**Comment by elshavi** [comment]
Tengo la misma duda, por ejemplo si un combatiente ya sea de unidades.txt o de dificultad.txt tiene en su atributo de vida un 0, se debe decir que el archivo es inválido?

**Comment by diegoftpxd** [comment]
Hola, con respecto a esto. En el enunciado no se pide en ningún momento que se modifique el archivo. Según lo pedido al encontrar un dato erroneo bastaría con imprimir un mensaje notificando el fallo y posteriormente **terminando la ejecución**. Por lo que básicamente se espera que alguien **cambie el archivo unidades.txt** para que funcione el programa.

Con respecto a la vida máxima, en caso de haber una vida máxima igual a 0, la unidad no dería válida ya que su vida máxima generaría que no pudiera pelear.
