### ISSUE TITLE
no se muestra cambio de color de camino/rio

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#243]
hola! bueno, creo que el titulo es bastante autoexplicativo jajaja, no se por que no me muestra la pieza siendo que la remuevo, la creo, y después la pongo 😢 eso jajaja. O sea, se muestra, pero solo en las ya puestas, la que se intenta poner (arriba del camino recto) no se muestra
dejo las fotos para contextualizar un poco, no se que podrá ser 😞 
<img width="831" alt="captura de pantalla 2017-09-06 a la s 15 15 36" src="https://user-images.githubusercontent.com/26392931/30127762-b5742262-9316-11e7-91e6-f0573cb67f8d.png">
<img width="851" alt="captura de pantalla 2017-09-06 a la s 15 15 44" src="https://user-images.githubusercontent.com/26392931/30127763-b6ef3ece-9316-11e7-9f7e-fda87f42448c.png">

**edit jtagle2**: Imágenes censuradas por ir en contra de las reglas del foro

**Comment by jtagle2** [comment]
No puedes subir código de tu tarea, pues se presta para que haya copia. Está en los reglamentos del foro. Saludos!
