### ISSUE TITLE
Utilizar if/elif dentro del init

### ISSUE THREAD

**Issue by lfb1206** [IIC2233/syllabus#243]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

¿Es posible utilizar condiciones dentro del __init__ de una clase?

**Comment by Julius9** [comment]
Si es Posible 😄 pero debes tener en cuenta que debes inicializar correctamente todas las variables de instancia que usaras después o te arrojara un AttributeError
