### ISSUE TITLE
¿Qué hacer en caso de que la energía gastada incluya una división por 0?

### ISSUE THREAD

**Issue by IrarrazavalP** [IIC2233/Syllabus#243]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Con algunos items, la fuerza de un excavador puede llegar a ser 0 y con ello la energía gastada incluye una división por cero y ello arroja error. 

¿Qué hacer en este caso?

**Comment by Benjeeeh** [comment]
Hola!
Como específica el enunciado, la fuerza no puede llegar a ser 0, si no que solo comprende valores entre 1-10, al igual que otros atributos similares, por lo que tu código debe resguardarse de estos casos.
![image](https://user-images.githubusercontent.com/78326186/233996815-590a1975-6b7f-47bc-90d1-dc2865987fac.png)

Éxito en la tarea!
