### ISSUE TITLE
plantas.txt / congelación = bool

### ISSUE THREAD

**Issue by xperseosses** [IIC2233/Syllabus#243]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el archivo plantas.txt, el 5to elemento de cada línea debería ser un booleano según el enunciado, sin embargo en el archivo son ceros. ¿Hay que interpretar 0 = False y 1 = True?

<img width="579" alt="Captura de pantalla 2024-09-01 a la(s) 7 11 21 p  m" src="https://github.com/user-attachments/assets/0550fd8e-3320-40b0-aedc-358255986abe">

<img width="616" alt="Captura de pantalla 2024-09-01 a la(s) 7 10 26 p  m" src="https://github.com/user-attachments/assets/567ba33d-fbae-45aa-b8a7-346f36c4e3f8">

**Comment by rodrigoaguilera15** [comment]
Hola, efectivamente 0 para false y 1 para true. Dato curioso: si haces un if, y la condición es un int = 0, valdrá False, mientras que si  es un 1 (o cualquier número distinto de 0) valdrá True. Saludos.

**Comment by xperseosses** [comment]
Me surgio otra duda a partir de plantas.txt, estas dos plantas de tipo "C" poseen atributos correctos, entonces ¿Cuál de los dos escojo para inicializar los objetos planta?
<img width="216" alt="Captura de pantalla 2024-09-01 a la(s) 7 44 52 p  m" src="https://github.com/user-attachments/assets/f7231af2-7b1d-4331-b656-0c1419922c33">

**Comment by rodrigoaguilera15** [comment]
Hola, te recomiendo ver la issue #245 , efectivamente hubo un error pero se corrigió para que siempre hayan 6 líneas erróneas. Así que tienes que bajar los archivos de nuevo.
