### ISSUE TITLE
Movimiento personaje: discreto o continuo

### ISSUE THREAD

**Issue by teverde** [IIC2233/syllabus#243]
Para esta entrega es necesario que el sprite del personaje se mueva de forma suave a través de las grilla o basta con que con que avance de celda en celda?

**Comment by jalliende** [comment]
Un supuesto que yo hice es que N/SPEED_PLAYER es la velocidad con la que se demora en moverse un cuadrado, con lo que solucione que solo se mueva de celda en celda

**Comment by Hernan4444** [comment]
Hola, 

Creo que hay una confusión (espero que sea así, pero mejor aclarar), el personaje tiene un movimiento continuo, es decir, **él puede quedar entre 2 casillas**, mientras que el enemigo tiene un movimiento discreta que es por cada casilla. Para el avance es aceptará que sea un movimiento entre celda mientras cumplan con los requisito del avance, es decir, la presencia de un obstáculo impide el movimiento del personaje o enemigo. Si lo hicieron discreto, se recomienda fuertemente cambiarlo a continuo lo antes posible para no olvidarlo y así en la corrección tengan todo el puntaje.

Saludos :v:

**Comment by jalliende** [comment]
Hola Hernan, no veo el error en el supuesto que realicé, ya que es correcto que N/SPEED_PLAYER es el tiempo que el personaje demora en desplazarse una casilla. Es imposible que le movimiento sea 100% continuo,  por lo tanto considero que mi supuesto es valido.

**Comment by Hernan4444** [comment]
Hola, quiero aclarar que no dije que el supuesto estaba mal, solo preferí aclarar para que nadie confunda que el personaje se mueve **de una casilla a otra** con velocidad "N/SPEED_PLAYER", sino que puede moverse a esa velocidad, pero este puede quedar entre 2 casillas.

Saludos :v:

**Comment by isidonoso** [comment]
Cuando se refieren a que el movimiento de los enemigos es discreto es como que el enemigo aparee y desaparece entre casillas? osea, aparece su imagen en una casilla y luego desaparece y aparece en la de al lado?

**Comment by Hernan4444** [comment]
Así es 👍 

Saludos

**Comment by FelipeCampbell** [comment]
@Hernan4444 
Hola (: 
En cuanto al movimiento de los enemigos, si es una forma válida que salten de un cuadrado al otro, ¿es también adecuado en cuanto a su animación que esta cambie de cuadrado en cuadrado (se notaría solo si avanza dos veces en la misma dirección [está ocurre en el lugar solo si choca contra un obstáculo])?

**Comment by Hernan4444** [comment]
Si,  es válido.

**Comment by FelipeCampbell** [comment]
Gracias :)
