### ISSUE TITLE
Soles obetnidos por girasol = soles de girasol + soles por recolección

### ISSUE THREAD

**Issue by 3rdPix** [IIC2233/Syllabus#243]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Los soles obtenidos por recoger un sol producido por un girasol, debe no ser solamente los producidos por la planta, sino agregar además "SOLES_POR_RECOLECCION"?

**Comment by drcid98** [comment]
Hola, no se si entiendo bien tu duda. Los girasoles producen una cierta cantidad de soles cada cierto intervalo de tiempo. Esa cantidad producida debe ser la obtenida al recolectarlos. 
Si no entendí tu duda, te pido explicar un poquito más a que te refieres para poder ayudarte.

**Comment by 3rdPix** [comment]
El problema es el siguiente:
![image](https://user-images.githubusercontent.com/86542704/194794041-3a57426e-f8dc-4fe1-a9be-0c3ffdacbd37.png)
Aquí dice que cuando recolectamos soles debemos agregar 2*SOLES_POR_RECOLECCION... en un principio uno piensa que se refiere a los soles que caen, y que en el caso de la noche, se deben agregar la mitad de esa cantidad por los soles que caen... pero esta parte
![image](https://user-images.githubusercontent.com/86542704/194794128-e7835cd8-12f9-48a1-be78-6cbfa09feb26.png)
Dice que en la noche no caen soles, solo se pueden recolectar a través de los girasoles... por supuesto, los girasoles por su parte producen su propia CANTIDAD_SOLES
![image](https://user-images.githubusercontent.com/86542704/194794299-9d6596b8-6474-499f-a67b-e0bdf58e49ce.png)
Con todo esto... no queda claro **¿Qué son los soles por recoleccion?**, y cuando se debe aplicar la mitad de esa cantidad. La solución que se me ocurrió es lo que planteé en el titulo de la issue... que cuando uno recoje soles de los girasoles, se agrega la cantidad natural que producen los girasoles, y además una cantidad fija "por recoleccion", la que se divide a la mitad durante la noche.

**Comment by drcid98** [comment]
Entiendo, súper buena pregunta ya que puede ser un poco confuso. Te explico de la mejor manera que se me ocurre:
En la sección 5.4.1, el parámetro SOLES_POR_RECOLECCION y 2 * SOLES_POR_RECOLECCION corresponden a la cantidad de soles que se deben recolectar y que puedes usar (por ejemplo, si estás en el escenario de día y SOLES_POR_RECOLECCION = 2, se deberían sumar 4 al total de soles cuando recolectes los producidos por un girasol). Por otro lado, CANTIDAD_SOLES es un parámetro que representa la parte visual de la aparición de los soles, es decir, cada vez que los girasoles generen soles, deben apareces (visualmente) CANTIDAD_SOLES, independiente de los que se vayan a recolectar cuando los apretes.

En resumen, SOLES_POR_RECOLECCION se relaciona a los soles que puedes usar y se suman a tu contador, mientras que CANTIDAD_SOLES se relaciona a la parte visual del juego. 
Espero haya solucionado tu duda.

**Comment by 3rdPix** [comment]
Entiendo, una última consulta respecto a este acercamiento; por una parte CANTIDAD_SOLES refiere a un `int` que indica *cuántos* soles deben aparacer cerca del girasol que los produce. Por otra parte, SOLES_POR_RECOLECCION refiere a la cantidad de soles que se agrega al *banco de soles* del jugador, cuando este recoge los soles. La pregunta final es; 

SOLES_POR_RECOLECCION debe obtenerse por cada uno de los CANTIDAD_SOLES, o solo una vez? Me explico:
- *Girasol 1* produce soles
- Aparecen CANTIDAD_SOLES al lado de *Girasol 1*. Supongamos para este ejemplo que CANTIDAD_SOLES = 3
Luego hay dos opciones:
*A*. Usuario hace clic en cada uno de los soles, de modo que se le agrega al banco SOLES_POR_RECOLECCION por cada uno de esos soles, obteniendo así; SOLES_POR_RECOLECCION * CANTIDAD_SOLES.
*B*. Usuario hace clic en cada uno de los soles, pero como todos esos soles, eran parte de la misma *tanda de producción*, solo se agrega SOLES_POR_RECOLECCION una vez, independientemente de cuántos soles cliquee el usuario.

Si se trata de la opción *B*, hay alguna indicación especial que diga que al hacer clic en el primer sol, ya se debe agregar al banco de soles, el parámetro de recolección, o solo cuando recoja el último de los 3 soles visuales, se agregará SOLES_POR_RECOLECCION.

**Comment by drcid98** [comment]
Hola! La opción "A" que mencionas es la que deberías implementar.
