### ISSUE TITLE
Campeonato

### ISSUE THREAD

**Issue by Cschavez** [IIC2233/Syllabus#243]
Hola! hay una cosa que no me queda claro, el campeonato ocurre o más bien, se tiene que programar,  dentro de "Demo.py" en métodos aparte de los que ya están?
En la [Issue #180 ](https://github.com/IIC2233/Syllabus/issues/180)  un ayudante dice "siempre serán conexos" eso es entre cualquier grupo de 200 que se tomen de los 5500 jugadores ? o se refieres especialmente a que siempre serán conexos los equipos que se formen con esos 200 jugadores?
Además, cuando dice que para entregar los 200 jugadores no se pueden ocupar listas se refieren a las listas de python? o incluso a una lista ligada creada por mi?
La esperanza de los equipos que se entregan es un número al azar? lo pregunto porque en ninguna parte dice cuales son los integrantes de ese equipo.
Sorry por tantas dudas
Muchas gracias!

**Comment by behrmann97** [comment]
Hola, sí, cualquier grupo de 200 jugadores que tomes siempre será conexo. Las listas que no puedes ocupar son las de python (ni cualquier estructura de datos de python), las tuyas sí puedes :). La esperanza de los otros equipos las puedes definir como quieras, mientras a la GUI le pases los nombres y esperanzas como se pide. 
Saludos!

**Comment by Cschavez** [comment]
Gracias! 
el campeonato es aparte de los métodos que hay que hacer para el Demo.py ?

**Comment by Cschavez** [comment]
Gracias!
