### ISSUE TITLE
Orden Ataque

### ISSUE THREAD

**Issue by leonidasmontes** [IIC2233/Syllabus#243]
Hola!

Quería preguntar si importa el orden de quien ataca primero. Entiendo que sale 'al mismo tiempo' en el enunciado, pero el que ataque primero tiene una ventaja ya que puede afectar los atributos del enemigo. por ejemplo el Caballero puede reducir el 'poder' del enemigo, y el ataque del enemigo sería más débil.

Por ahora pienso poner en el readme supuesto de que yo ataco primero.

Gracias!

**Comment by vichorosen** [comment]
Hola! Me sumo a tu consulta, ya que no queda claro en el enunciado. 
Además el que ataca primero tiene aún más ventaja ya que le baja la vida al enemigo, por lo que, cuando este ataque, su ataque va a ser más débil porque este atributo depende de la vida actual que tiene.

**Comment by Benjeeeh** [comment]
@leonidasmontes @vichorosen 
Hola!
Como el enunciado menciona solamente que ambos deben atacar en la ronda, está en su decisión como realizarlo. Lo importante es que **no por atacar uno primero y bajé a 0 la vida del enemigo, este no pueda atacar, el daño se debe ejecutar igual.**
Deben poner en sus READMES como ejecutan esto, ya sea uno atacando primero, aplicando los efectos y haciendo daño y luego ataca el enemigo, y así sucesivamente, u otra forma que les parezca. Lo importante es que si o si ambos combatientes realicen su ataque!

Saludos.
