### ISSUE TITLE
Mala práctica al instanciar

### ISSUE THREAD

**Issue by jbulness** [IIC2233/syllabus#243]
Hola, quería saber si se considera una mala práctica el instanciar una clase de la siguiente forma:
class Ejemplo:
    def __init__(self):
        self.numero = 0

ejemplo = Ejemplo()
ejemplo.numero = 1

**Comment by RositaMunoz** [comment]
Hola!
Efectivamente, hacer lo que indicas es una mala práctica, puesto que no estás encapsulando correctamente las funcionalidades de tu clase. 
La forma correcta de hacerlo sería:
```python3
class Ejemplo:
    def init(self, numero=0)
    self.numero = numero
```
y de esta forma al instanciar tu clase Ejemplo sería:

```python3
ejemplo = Ejemplo(1)
```

Espero haber solucionado tu duda, de todas formas quedo atenta!

Éxito con la tarea!

**Comment by jbulness** [comment]
Muchas gracias!

**Comment by burgosibarra** [comment]
es una mala practica si hago esto:
`ejemplo = Ejemplo(1)`
y en otro archivo modifico el atributo
`ejemplo.numero = 6`
desde ya, muchas gracias

**Comment by RositaMunoz** [comment]
Hola @burgosibarra!
En particular, no es una mala práctica ya que inicializaste el valor de numero dentro de tu clase, afuera puedes cambiarla. Idealmente sería hacerlo dentro de la clase, pero si lo haces así, no es mala práctica.

Éxito con la tarea!
