### ISSUE TITLE
Problemas al descargar la AF de hoy dia 

### ISSUE THREAD

**Issue by lsschmitz** [IIC2233/syllabus#243]
No pude hacer la actividad formativa hoy y la quiero descargar para hacerla ahora, pero no se bien como hacerlo

**Comment by dchahuan** [comment]
Hola, para poder hacer la actividad haz git pull en tu carpeta del syllabus y luego copia los archivos creados en la carpeta AF01 y copialos a tu repositorio personal ahi puedes desarrollar la actividad por ti mismo.

**Comment by lsschmitz** [comment]
Si lo habia tratado de hacer, pero me tira un error. Dice que hay otro proceso en marcha 
![image](https://user-images.githubusercontent.com/69091789/91505244-21097980-e89d-11ea-90e6-fa38e2812112.png)

**Comment by dchahuan** [comment]
La forma mas facil de arreglar eso, es sacar cualquier cosa importante que tengas en el syllabus que quieras guardar, borrar la carpeta y ahi hacer git clone denuevo.
