### ISSUE TITLE
Deshacer jugada vs. Historial

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233/Syllabus#244]
Hola, aún no entiendo cuál sería la diferencia entre volver a una jugada anterior y deshacer una jugada. En ese sentido deshacer una jugada cuenta en el historial?

**Comment by Arcoirisky** [comment]
El deshacer es eliminar la jugada anterior del turno en el que estás parado sin modificar las jugadas del jugador 2. En cambio, el historial puede dar saltos más largos y modifica también las piezas jugadas de tu contrincante. 

¿Se entiende algo mejor?

**Comment by augustoas** [comment]
Hola ! Tengo una duda de esto, deshacer una jugada lo entiendo perfect y es una opción del jugador en cada turno envés de jugar una pieza. En el historial tengo dudas, por ejemplo si estoy en la jugada 10, y vuelvo usando el historial a la jugada 2, el próximo turno se hace desde la jugada 2? o el historial es solo algo visual y el próximo jugador debe ser desde la jugada 10?

**Comment by cilopez** [comment]
Si se deshace la ultima jugada que hay antes del historial, es decir si estoy en la jugada diez y vuelvo a la cuatro, luego al deshacer la jugada, deshago la jugada anterior a la cuatro. Si no entendí tu duda hazme saber porfavor, saludos!
