### ISSUE TITLE
Excesivo numero de poblacion

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#244]
Hay una issue que habla de esto, pero no responde a la siguiente pregunta:
¿Está bien si para las distintas funcionalidades del programa, como cuando itero sobre un range del largo de la población, lo hago justamente iterando persona a persona?

Digo esto porque están les recomendaciones de dividir la población en 100 por ejemplo y ver la propagación de la infección por ejemplo por grupo y así el computador soportará o será más eficiente a la hora de calcular estos números considerando que las poblaciones de los países son en el orden de 300 millones.

Sin embargo, me pregunto si sigue estando correcto que implemente for´s que iteren sobre cada persona de la población. Con correcto me refiero a que no me bajaran puntaje con esto.

Lo pregunto porque ya lo tengo implementado de esta manera y quisiera ahorrar el tiempo que significaría arreglarlo. Ademas considerando que, en teoría, la forma que use es correcta, pero no se si "en teoria" es suficiente.

Obviamente explicaré en el readme lo que termine haciendo.

**Comment by nivek0o0** [comment]
En otra issue dijeron que calcules una tasa de infección constante, es decir, randint(0,6)  * tasa_contagiosidad * 0,3 si se repartieron las mascarillas, y ese valor lo multipliques por la cantidad de infectados, para obtener así los nuevos contagiados. En otras palabras, asumir una cantidad de contagios constante para cada infectado.

**Comment by acrojas2** [comment]
@nivek0o0 esto quiere decir entonces que cada individuo de la población contagia a la misma cantidad de personas dados por el randint(0, 6) ?

**Comment by acrojas2** [comment]
@jorgeriesco  me sumo a lo que tu dices respecto a la funcion que itera por persona para contagiar al parecer lo hicimos de manera similar y cumpliendo con lo que dicen en el enunciado (que por cada individuo tira el random (0,6) y se infecta al resto), yo creo que arreglarlo a  estar alturas igual toma tiempo (que es escaso). Sin embargo, creo que hacer lo que dice @nivek0o0  disminuye considerablemente el tiempo de contagio ya que disminuyes las iteraciones a solo 1 ( en lugar de 1 por cada infectado).

**Comment by akaminetzkyp** [comment]
@nivek0o0, sabes en que issue dijeron eso? Saludos!

**Comment by arturodelreal** [comment]
#172
