### ISSUE TITLE
Incongruencia entre información item 3 e información ítem 5

### ISSUE THREAD

**Issue by lfb1206** [IIC2233/syllabus#244]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el item 3 del enunciado, al momento de definir las clases nos dicen cuales son los tipos de valores (str, int, float, etc..) la cosa es que me di cuenta que, por ejemplo, costo de mantencion es float en el ítem 3 y luego en el ítem 5 nos dicen que es int. Sucede lo mismo con velocidad base. 
¿Por cual tipo de valor nos guiamos? ¿El que nos dicen en el ítem 3 o el del ítem 5?

**Comment by Ignacioislae** [comment]
Tengo la misma duda.

**Comment by sperezmasri** [comment]
Hola, @lfb1206. Efectivamente en el enunciado salen dos tipos distintos para el cobro de mantención y la velocidad base. En este caso quédate con que costo de mantención es un **int** y velocidad base es un **float**, ya que esto hace más sentido en el contexto de la tarea. :smile:
