### ISSUE TITLE
inputs no validos

### ISSUE THREAD

**Issue by nataliasuarez99** [IIC2233/syllabus#244]
Hola!! queria preguntar que tengo que hacer cuando alguien ingresa un input no valido (ademas de mostrar un mensaje diciendo que el input no es valido) deberia tambien volver al paso anterior(el paso antes de que ejecutaran mal el input)??Se que en los menu si aplica eso pero nose si aplica para todo el programa.
:-)

**Comment by kadroguett** [comment]
Hola @nataliasuarez99, cuando se ingresa un input no válido debes notificar que este no lo es y dar la opción de volver atrás o de ingresar nuevamente el input. Esto aplica para todo el programa. 😸

**Comment by stephenwpugh** [comment]
Hola! la opción de volver atrás la puedo ofrecer con el input que yo quiera? (siempre y cuando esté especificado), tipo **1. Volver**

**Comment by kadroguett** [comment]
Exacto, tu decides que opciones le das al usuario siempre y cuando lo especifiques
