### ISSUE TITLE
Mantener música entre ventanas

### ISSUE THREAD

**Issue by 3rdPix** [IIC2233/Syllabus#244]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado menciona que la música deberá reiniciarse cada vez que se abra una ventana... pero esto afecta bastante la experiencia del usuario; es posible que se permita mantener en algunos casos la música sonando aun cuando se cambie entre ventanas? esto obviamente para ventanas que estén relacionadas y que "mantengan el vibe" de la ventana anterior. Por ejemplo, entre la ventana de inicio y la ventana de ranking... irrumpir el sonido entre estas no tiene mucho sentido desde el usuario. En cambio, entre ventana principal y ventana juego si tiene sentido reiniciar la música y hasta cambiar el archivo que se reproduce para generar un ambiente diferente.

**Comment by Juampisaez** [comment]
Holaa 👋 @3rdPix 
Sobre lo que mencionas, dado que se trata de un bonus, se evaluará especificamente lo que aparece en el enunciado. Es decir, _"La música debe ejecutarse durante todo momento en el programa, reiniciándose cada vez que se cambie de ventana. Además, cuando se pause el programa, la música debe detenerse y reanudarse una vez el programa se reanude."_.

Espero quede más claro, quedo atento si surge otra duda :)
