### ISSUE TITLE
Properties

### ISSUE THREAD

**Issue by cristobalgon** [IIC2233/syllabus#244]
Hola, estoy trabajando hace mucho con una duda y aun no la puedo resolver.
Cuando tengo por ejemplo esto:

```python3
@property
def dinero(self):
    return self.dinero()

@dinero.setter
def dinero(self):
    if not self.dinero:
        self.dinero = 2000
```

me sale que dinero dinero() esta recibiendo dos parámetros en ves de uno, no sé por qué pasa eso si cuando le paso a la clase el atributo dinero, este es None o un único valor... ¿Qué es lo que anda mal?

espero se haya entendido la pregunta.
de antemano muchas gracias

**Comment by KnowYourselves** [comment]
Hola @cristobalgon!

## Respuesta a tu pregunta

Bueno, la respuesta simple a tu pregunta es que **estás ocupando mal _properties_** 👀.

Veamos como sería ocupar _properties_ correcamente en este caso. Ocupemos la siguiente clase como ejemplo:

```python3
class Billetera:
    def __init__(self, dinero):
        self.dinero = dinero
```
Supongamos que ahora queremos que la variable `dinero` sea un property, para esto necesitamos hacer un **getter** y un **setter**. Veamoslo en orden:

1. **getter**:

Función que será llamada cuando accedamos a la _property_. Usualmente retornamos un variable privada o una mezcla de otras variables. En este caso queremos retornar la variable dinero, asi que la cambiamos a privada y definimos el getter:

```python3
class Billetera:
    def __init__(self, dinero):
        self.__dinero = dinero

    @property
    def dinero(self):
        return self.__dinero
```

2. **setter**:

Función que será llamada cuando cambiemos el valor de una _property_. Debe llamarse **exactamente igual que el _property_** y usualmente cambia los valores que se retornan por detrás. También debe tener un argumento, que sería el valor al cual queremos _setear_ la variable. En este caso debe ser definida de la siguiente forma:

```python3
class Billetera:
    def __init__(self, dinero):
        self.__dinero = dinero

    @property
    def dinero(self):
        return self.__dinero

    @dinero.setter
    def dinero(self, value):
        self.__dinero = value
```

Y voilá! Con esto quedá una propertie funcional. Ahora en el _setter_ podríamos agregar más funcionalidades, por ejemplo, limitar el valor mínimo que puede tomar dinero a 0 o cosas así.

 En cuanto a tu código tus problemas fueron los siguientes:

1. En tu getter llamaste recursivamente a la property en vez de ocupar una variable privada.
2. En tu setter no ingresaste el argumento value.

## Bonus Track: Dudas Generales

1. Como vimos en el ejemplo, definimos `self.__dinero`?,  Por que no definir simplemente `self.dinero = dinero`? 

Esto se debe a que si no ocupamos un valor por detrás y definieramos el _getter_ con el mismo nombre de la variable **nos quedaría un _loop_ infinito**. Ya que cuando hagamos `objeto.dinero` entraríamos al _getter_ llamado dinero, el cual nos retornaría `self.dinero`, lo cual entraría al _getter_ dinero... y así sucesivamente.

2. Exactamente como funciona el argumento `value` del setter?

El argumento `value` toma el valor de **lo que sea que esté a la izquierda del operador igual. Veamos algunos ejemplos:

- Si hacemos `self.dinero = 20`, vamos a entrar al setter con `value = 20`. 
- Supongamos que el valor actual de dinero es 50 y hacemos `self.dinero += 20`, esto es equivalente a hacer `self.dinero = self.dinero + 20`, lo cual es equivalente a hacer `self. dinero = 50 + 20`, por lo cual entramos al _setter_ con `value = 70`.

3. Es necesario definir un _setter_ para toda _property_?

No!, Hay casos donde **no vas a cambiar el valor de una property directamente**. Por ejemplo, si tenemos una clase que círculo que tiene un radio, podemos definir su área como una _property_ de la siguiente forma:

```python3
class Circulo:
    def __init__(self, radio):
        self.radio = radio

    @property
    def area(self):
        return 3.14 * self.radio ** 2 
```

Como no tiene sentido que cambiemos el área directamente no es necesario que definamos un _setter_ para este. También como el área depende del radio y de nada más, no es necesario definir una variable privada para el área. Con este código el área es calculada correctamente en función de cualquiera sea el valor del radio.

# 
Espero haberte ayudado!

**Comment by cristobalgon** [comment]
Se entiende a la perfección, muchas gracias!!

**Comment by cristobalgon** [comment]
Una ultima duda con respecto a esto mismo... cómo yo llamo a __dinero? 
en el ejemplo que diste sería Billetera.__dinero += 20?
muchas gracias

**Comment by KnowYourselves** [comment]
No, debería ser siempre `self.dinero`, de esa manera accedes al setter. Si hicieras `self.__dinero` no entrarías al setter.
