### ISSUE TITLE
No me funciona Pyqt5 Ayuda! :) 

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2233/Syllabus#244]
Hola, tengo problemas para in stalar  #pyqt5

- **Windows 10**
- **Pyqt5**

Esto es lo que hice en la consola:

c:\Users>pip3 install pyqt5
Collecting pyqt5
  Downloading https://files.pythonhosted.org/packages/6c/63/89f888968ee0c7e7ffb2ea7604fae3ef85f7bc86f57dd07019805aa78798/PyQt5-5.10.1-5.10.1-cp35.cp36.cp37.cp38-none-win32.whl (68.6MB)
    100% |████████████████████████████████| 68.6MB 58kB/s
  The scripts pylupdate5.exe, pyrcc5.exe and pyuic5.exe are installed in 'c:\users\asus\appdata\local\programs\python\python36-32\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pyqt5-5.10.1

c:\Users>pip3 install pyqt5-tools
Collecting pyqt5-tools
  Downloading https://files.pythonhosted.org/packages/f2/65/3432d3a0b96cd027d78d79793aa0464f413ab24cfaca0fbafe5ec45562b8/pyqt5_tools-5.9.0.1.2-cp36-none-win32.whl (30.8MB)
    100% |████████████████████████████████| 30.8MB 344kB/s
Installing collected packages: pyqt5-tools
Successfully installed pyqt5-tools-5.9.0.1.2

c:\Users>

- Descripción del problema: Hice esto y no me funciona el demo, me tira el error ModuleNotFoundError: No module named 'PyQt5'

**Comment by fgbruna** [comment]
>`The scripts pylupdate5.exe, pyrcc5.exe and pyuic5.exe are installed in 'c:\users\asus\appdata\local\programs\python\python36-32\Scripts' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.`

Intentaste agregar la carpeta al `PATH` como te recomienda `pip`?

**Comment by alfa-labarca** [comment]
Si estás usando PyCharm, tienes que instalarlo desde el Project Interpreter, ctrl+alt+S -> Project -> Project Interpreter, aprietas el '+' verde, y ahí buscas PyQt5

**Comment by joaquineichholz** [comment]
gracias! ahora me funciono
