### ISSUE TITLE
Issue librerías prohibidas tarea 0

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#244]
Hola, dónde quedaron las librerías prohibidas de la tarea 0? saludos. Lo borraron parece :(

**Comment by DCCollao** [comment]
Hola!

No borramos la issue de librerías prohibidas, sino que fue cerrada para dar lugar a las issues de la T01.
Si quieres volver a ver las issues de la T00, debes filtrar por issues cerradas marcando la siguiente opción:
![image](https://user-images.githubusercontent.com/37167447/78458734-fc143000-7689-11ea-9fbf-eb16a00121b3.png)

En este caso, la issue que buscas es la #4 .
