### ISSUE TITLE
metodo de creacion base para plantas

### ISSUE THREAD

**Issue by Amath3o** [IIC2233/Syllabus#244]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, por lo que vi no se especifica como se deben crear las plantas a excepción de las mutadas, por lo que puedo interpretar que es de libre disposición (siempre que se utilice al menos una vez cada concepto clave de la materia)? o se deben crear de una manera concreta

**Comment by R3Y3X** [comment]
hola, espero que estés bien.Siii es de libre disposición siempre y cuando utilices como mínimo cada concepto de la materia, recuerda dejarlo claro en el README las consideraciones/suposiciones que hiciste, Éxito en tu tarea ⚡
