### ISSUE TITLE
Usar Windows en vez de WSL para la T2

### ISSUE THREAD

**Issue by ceojedab** [IIC2233/Syllabus#244]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/Syllabus/issues/243)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](https://github.com/IIC2233/Syllabus/issues/241)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, buenas. Escribo este issue pues no entiendo si para la T2 es mejor utilizar Windows directamente para programar, debido a los problemas de WSL con PyQt6, o  si debería hacer todo en WSL y sólo correr los códigos desde la terminal de Windows.

Por cierto, el Label de la Issue se puso automáticamente como para la T1, pero debería decir T2.
Muchas gracias.

**Comment by AntonioVenegas** [comment]
Hola!, mejor sigue usando windows directamente para asi partir lo antes posible la tarea, saludos :)
