### ISSUE TITLE
Más de una linea válida en 'plantas.txt'

### ISSUE THREAD

**Issue by Dielastros** [IIC2233/Syllabus#245]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, ¿Qué se debe hacer si en el archivo de plantas.txt se encuentra más de una linea válida respecto a uno de los tipos de plantas?
En el enunciado se especifica que siempre existirán 12 lineas con 6 listas erroneas, pero, según tengo entendido, en el archivo de prueba 'plantas.txt' enviado, ambas lineas de datos de la planta 'C' son válidos, y no se si debo quedarme con la primera linea o la segunda.

Muchas gracias por la atención.

**Comment by mpiavf** [comment]
Hola @Dielastros ! El archivo tenía un pequeño error, se actualizó **plantas.txt** para que contenga 6 líneas erróneas. 
Saludos!
