### ISSUE TITLE
No se me mueven los nuevos autos creo

### ISSUE THREAD

**Issue by Francisco-Aguilera-xd** [IIC2233/Syllabus#245]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Me está pasando que cuando creo autos nuevos cada ```TIEMPO_AUTOS``` estos no se mueven a pesar de que tengo implementada la funcionalidad de mover autos. Cuando abro la ventana de juego veo que los autos que ya estaban se están moviendo, pero cuando se crea uno nuevo, este no se mueve. Intenté utilizando con el método ```repaint()``` pero no logré solucionar esto. ¿Cómo lo puedo arreglar?
Gracias de antemano

**Comment by Francisco-Aguilera-xd** [comment]
Avancé en el código y los autos si existen, pero no se ven. O sea que colisiono con autos "invisibles" y no entiendo como lograr que los autos se vean

**Comment by Maxi1805** [comment]
Hola @Francisco-Aguilera-xd, por lo que pude ver, tal vez el problema no es que no se actualice, lo que estaría haciendo el repaint, sino que las labels no se están mostrando, prueba a hacer que las labels se muestren cada vez que se cree un auto. 
Espero te sirva.

**Comment by Francisco-Aguilera-xd** [comment]
Siiii, al hacer .show() a las labels ahora me aparecen! Muchas gracias
