### ISSUE TITLE
Duda sobre NUM_BARCOS y tamaño del tablero.

### ISSUE THREAD

**Issue by feliperojas123** [IIC2233/syllabus#245]

**Comment by vicentevegaulloa** [comment]
Hola @feliperojas1231

Podrías describir tu duda en la descripción. No me queda claro tu pregunta porque está a la mitad en el titulo jaja

Gracias! 😄

**Comment by feliperojas123** [comment]
sucede que en parametros.py me sale que siempre sera 3.. entonces el tamaño del tablero debe si o si soportar los 3 barcos?

**Comment by feliperojas123** [comment]
dnksdndkn sii que la vendi y aprete enter sin querer dndnkdns

**Comment by vicentevegaulloa** [comment]
Si entiendo bien tu pregunta, tu dices que `NUM_BARCOS` siempre será 3 y que las dimensiones del tablero deben soportar esos 3 barcos. De ser así, estás equivocado al decir que `NUM_BARCOS` siempre será 3, ya que al ser un parámetro podría tomar varios valores. Sin embargo, como dice el enunciado, no debes preocuparte de que el tablero no pueda soportar la cantidad de barcos, ya que estos siempre seránenos que la cantidad de celdas del mapa. Espero haber respondido tu duda 😄
