### ISSUE TITLE
Foro preguntas anónimas

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#245]
Hola cómo accedo al foro de preguntas anónimas?

**Comment by DCCollao** [comment]
Hola!

Este es el [link](https://docs.google.com/forms/d/e/1FAIpQLSfGlM7GTOKARUzDQeCvXZ9aMWZ7IKCyrh99D6SLjb4kD1Fqsw/viewform) del form de dudas anónimas.
