### ISSUE TITLE
args y kwargs

### ISSUE THREAD

**Issue by nhbravo** [IIC2233/Syllabus#245]
Se pueden usar args y/o kwargs o se asumen como estructuras built-in?

**Comment by santilaguna** [comment]
Sumando a la pregunta anterior, si le otorgo *args a una funcion y luego quiero iterar los valores, sin utilizar for dato in args (para no llamar indirectamente a una lista) ¿como se hace en este caso para no llamar a la lista de python o simplemente no se puede?

**Comment by Drpinto1** [comment]
No soy ayudante, pero hay un ejemplo en [174](https://github.com/IIC2233/Syllabus/issues/174) que habla de eso, espero que les ayude :smile:

**Comment by santilaguna** [comment]
No me refiero a utilizar el operador * (que ya habían dicho que es válido) sino más bien entregar *args  a una función y luego utilizar args para iterar sobre los valores simplemente)
