### ISSUE TITLE
(T01) stackoverflow

### ISSUE THREAD

**Issue by mgbriones** [IIC2233/syllabus#245]
si encuentro una función en https://es.stackoverflow.com que me resulta útil tal cual esta, es posible usarla en mi código? donde debe ser referenciada de ser el caso?
gracias

**Comment by gatochico** [comment]
Hola! Idealmente deberías seguir lo siguiente para usar código externo:
- Dentro del archivo `.py`, idealmente antes de la sección de código que sacaste, en un comentario:
``` 
# Este código lo saqué de https://stackoverflow.com/questions/15286401/print-multiple-arguments-in-python
print("Total score for %(n)s is %(s)s" % {'n': name, 's': score})
```
- En tu README, bajo la parte de 'Referencias de código externo'. Debes citar el link **exacto a la pregunta de donde sacaste el código**, e indicar indicar en qué módulo y líneas de tu programa lo utilizaste. 

Con eso deberías estar bien.
Saludos!
