### ISSUE TITLE
Duda colisión

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#245]
Holas,

Puedo asumir que si hay un objeto obstáculo a "3 pasos" y mi personaje avanza "5 pasos" cada vez que se mueve, puedo asumir que se quedará en el lugar, o es necesario que se quede inmediatamente un paso antes del objeto?

Saludos

**Comment by jmwielandt** [comment]
Hola! Primero necesito aclarar que la forma "correcta" de interpretar la velocidad de los **enemigos**, a diferencia de la del personaje, es como "tiempo que tarda en avanzar una casilla", no "casillas que avanza en cierto tiempo". 
Por tanto, nunca avanzará "5 pasos" de golpe, sino que dará un paso muy rápido o muy lento. Como sale en el enunciado, el movimiento de los enemigos es casilla a casilla. 😄 

![image](https://user-images.githubusercontent.com/37153467/57897253-f7e8e500-7821-11e9-8ef5-9cca90dce78e.png)

Si te refieres al movimiento del **personaje**, esto queda a tu criterio (siempre y cuando lo especifiques en tu **readme** y no vaya en contra de otros puntos del enunciado).
