### ISSUE TITLE
Duda con los métodos de ataque de las entidades

### ISSUE THREAD

**Issue by vichorosen** [IIC2233/Syllabus#245]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo una duda respecto a como implementar los métodos de ataque para cada entidad. La explico con un ejemplo.

El caso es que, por ejemplo, en Caballero, este tiene una probabilidad P% de usar su ataque de caballero, y si no se activa, ataca como Guerrero. De ahí, si es que Paladín hereda de Caballero, al momento de este atacar, tiene una probabilidad Q% de usar sus poderes de caballero, por lo que el enunciado me indica creer que si esto se cumple, "hereda" el método de ataque de caballero. Pero ahí existiría una doble probabilidad, ya que al momento de que salga el Q%, depende también de la probabilidad P% para ver si efectivamente ataca como caballero o como guerrero, por como funciona el ataque de un caballero, lo cual me genera dudas y me gustaría confirmar.
Lo otro que se me ocurre es directamente, cuando salga el Q%, hacer que efectivamente haga un ataque de caballero, ignorando la P%, pero siento que esto no se desprende del enunciado y no aplicaríamos los conceptos de herencia como creo que se busca en la tarea.

Estaría bien utilizar el primer caso, justificando en el ReadMe, o debo cambiar mi enfoque de esta parte?

Gracias de antemano!

**Comment by Benjeeeh** [comment]
Hola!
Es exactamente lo que describes al comienzo, puede que no sea el mejor estilo de batalla pero así atacan los paladines! Lo segundo que mencionas no te lo recomiendo, ya que va en contra de lo que se menciona en el enunciado, que quizás sea una forma más efectiva de pelear viéndolo desde un punto de vista de un guerrero real pero el enunciado menciona explícitamente que **esta probabilidad es para activar los poderes de caballero**, y si funciona así es porque debe hacerse así.

Saludos!

**Comment by emivenezian** [comment]
Entonces si no se cumple esa probabilidad Q, no activa sus poderes de caballero, y que activa? Asumimos que ataca como caballero?

**Comment by Benjeeeh** [comment]
@emivenezian 
Atacaría como lo menciona la clase caballero en caso de no cumplirse la probabilidad, como un guerrero y se disminuiría su resistencia.
