### ISSUE TITLE
Probabilidad de encallar 

### ISSUE THREAD

**Issue by barbaracalderonr** [IIC2233/syllabus#245]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!, tengo dudas sobre cuando un barco encalla, ya que aparece como calcular la probabilidad de que encalle, pero en ningun momento aparece cuando un barco realmente encalla... 
lo mismo para desencallar, se calcular la probabilidad, pero no existe un mínimo de por ejemplo, si la probabilidad es mayor a algo, entonces se puede desencallar el barco, o algo así

**Comment by DomingoCarvajal** [comment]
Los eventos "encallar" y "desencallar" son eventos probabilísticos, es decir que no van a ocurrir el 100% de las veces.  Entonces estos eventos no necesitan tener una probabilidad mayor a un número en particular para ocurrir, si no que se tienen que comportar aleatoriamente, pueden ocurrir o no ocurrir. Y la probabilidad de que ocurra el evento es lo que se calcula con la fórmula. En el código ustedes tienen que implementar que cada evento se comporte de esta manera.

**Comment by barbaracalderonr** [comment]
yaa graciaas

**Comment by mjsifri** [comment]
Hola, a mi me quedo una duda, emtonces hay que asumir que estos eventos ocurren solamente cuando la probabilidad es 1?

**Comment by DomingoCarvajal** [comment]
Hola @mjsifri! 

Estos pueden ocurrir siempre y cuando la probabilidad sea mayor a 0.

**Comment by Rerro-r** [comment]
Holaa, sobre este tema también tenía una duda. Entonces, según las probablilidades, ¿el programa va a elegir si ocurre o no?, digo para hacer los cobros y que se ejecuten las consecuencias de un encallamiento. ¿Esto sería con algún método de `random`? por dar un ejemplo.

**Comment by DomingoCarvajal** [comment]
Hola @Rerro-r .

Perdón por la demora. Si el programa se encarga, la librería `random` se puede utilizar para esto.
