### ISSUE TITLE
Duda sobre POND_ARENA_NORMAL

### ISSUE THREAD

**Issue by tomastrivino** [IIC2233/Syllabus#245]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo una duda, resulta que en el enunciado dice lo siguiente: 
<img width="834" alt="image" src="https://user-images.githubusercontent.com/98418205/233887587-ef51a071-d157-4757-a3ba-95167a196213.png">
Aquella ponderación de la arena normal, ¿debe ser sólo una vez y al momento de instanciar la arena? ¿o debe ser cada vez que simulo un día? Resulta que yo estoy ponderando cada vez que llamo a mi función de simular día, en el siguiente orden:
simular_dia() : pondera arena -> excavadores cavan -> encuentran items -> se pone en descanso a los necesarios -> etc etc. La cosa es que, si pondero la dificultad de la arena normal cada vez que simulo un día, y no ocurre ningún evento (se mantiene mi arena por varios días y le sigo ponderando la dificultad), podría llegar a tener una dificultad 0.00, y por ende un error del tipo ZeroDivision.

Un caso de ejemplo: si comienzo con una arena del tipo suave, cuya dificultad es 0.13, y tengo un ponderador de 0.3:
Simulo día 1: Se altera dificultad a 0.04. No ocurren eventos, se mantiene esa arena.
Simulo día 2: Se pondera nuevamente la dificultad de la arena, en esta oportunidad 0.04x0.3 = 0.01. No ocurre evento.
Simulo día 3: Como no ocurrió ningún evento, se mantiene la misma arena que partió desde el día 1, en donde ahora se pondera la dificultad 0.01x0.3 dando como resultado 0.003, lo que es redondeado por el programa a 0.00 y, por tanto, generando error de división y/o cantidades ridículas de metros cavados.

**Comment by PipeXtz** [comment]
Hola @tomastrivino !

Si la arena no está cambiando con el paso de los días tiene sentido que fuese aplicado solo al inicio el ponderador, y así te evitas que la dificultad pueda llegar a ser 0.00. No obstante, estas es una de las formas de solucionarlo, ya que al no ser especificado por el enunciado, queda a tu criterio como lo manejas, solo especifícalo en el readme.

Espero haya quedado claro, quedo atento.

**Comment by tomastrivino** [comment]
@PipeXtz entonces no hay problema si agrego una condición al setter, tal que si round(nueva, 2) == 0.00 se haga que self.__dificultad = 0.01 ? A pesar de que esto me provoque cantidades altas de metros cavados.

**Comment by PipeXtz** [comment]
@tomastrivino Cualquier cosa/supuesto que planees hacer, como solucionar la división por cero, que es súper válido, agrégalo en el readme :).
