### ISSUE TITLE
no se muestra cambio en color de rio/camino

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#245]
hola! bueno, creo que el titulo es bastante autoexplicativo jajaja, no se por que no me muestra la pieza siendo que la remuevo, la creo, y después la pongo 😢 eso jajaja. O sea, se muestra, pero solo en las ya puestas, la que se intenta poner (arriba del camino recto) no se muestra
dejo las fotos para contextualizar un poco, no se que podrá ser 😞
<img width="831" alt="captura de pantalla 2017-09-06 a la s 15 15 36" src="https://user-images.githubusercontent.com/26392931/30128156-f42f3ac2-9317-11e7-9520-a8396a698896.png">
<img width="851" alt="captura de pantalla 2017-09-06 a la s 15 15 44" src="https://user-images.githubusercontent.com/26392931/30128155-f425080e-9317-11e7-8c2b-1b7716f51d17.png">

tengo una función que tras poner una ficha que tiene un pedazo de camino conectado con otro actualiza el tablero y los colores de las fichas mediante los métodos
`gui.pop_piece(i,j)`
`gui.nueva_pieza(color_nuevo,tipo_de_pieza)`
`gui.add_piece(i,j)`

pero por alguna motivo no se muestran las fichas como se ve en las imágenes

**Comment by Arcoirisky** [comment]
Dale una vuelta a tu código y fíjate si estás haciendo todo bien 😅 Eso, en teoría, más que un error es algo que no te está funcionando porque la función que ubica piezas de distinto color funciona ¡Sigue intentando y ánimo!

**Comment by rihanuch** [comment]
lo unico que hago es iterar sobre mi lista que contiene información de las piezas en manera de un simple y mero `for i in` 😢

**Comment by iqacevedo** [comment]
Hola,

Revise y si se puede hacer sin problemas lo que quieres hacer con los métodos de la interfaz. Cómo se mencionó en otra issue este tipo de error ocurre cuando se usa `add_piece` sin que previamente se haya ejecutado `nueva_pieza`. No te podemos decir más que eso porque es tarea tuya ver cómo solucionar este tipo de errores, así que revisa bien todo, y mucho ánimo, que es más que seguro que lograras resolverlo! 

Saludos !
