### ISSUE TITLE
Cola de prioridades

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#245]
Solo para estar seguro:

La cola de prioridades son las propuestas de todos los países ordenadas según su calculo de prioridad. Por lo tanto es una cola que podría tener muchas propuestas (más de 5) y se eligen solo las tres primeras para ser implementadas.

¿Está bien eso?

**Comment by chuma9615** [comment]
Segun yo asi es, eso sale en el enunciado
