### ISSUE TITLE
Para evitar posibles errores

### ISSUE THREAD

**Issue by fediaz3** [IIC2233/syllabus#246]
Quería consultar si es mala practica hacer una clase que herede de varios QtCore, como Qobject, Qrect, etc?
Lo encuentro útil, pero recuerdo un contenido de OOP que nos hablaban de un problema del diamante.
Por el momento, no veo error, pero prefiero preguntar antes de llegar a algo que no se pueda arreglar o tener descuento por mala practica

**Comment by gatochico** [comment]
Hola! Según la documentacion de [PyQt5...](https://www.riverbankcomputing.com/static/Docs/PyQt5/gotchas.html#multiple-inheritance)
![image](https://user-images.githubusercontent.com/37161120/57815467-8f2c3a80-7745-11e9-9379-51bc7152b3cc.png)
...No es posible hacer una clase que herede de más de una clase Qt, busca una forma de modelar lo que quieres sin tener que heredar de dos clases al mismo tiempo. Saludos!!

**Comment by fediaz3** [comment]
Gracias !
