### ISSUE TITLE
botones para objetos de tienda

### ISSUE THREAD

**Issue by Maria-josee** [IIC2233/Syllabus#246]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!, mi duda es que para los objetos de la tienda que se compran con el click izquierdo pueden ser estos botones y ahí verificar si se presionó con ese click ? o tienen que ser como Qlabels con imágenes y ahí verificar si se tocaron con el click izquierdo?

**Comment by Lord-Kelsier** [comment]
Hola @Maria-josee, puedes implementarlo de cualquiera de las dos formas, de igual modo especifica tu elección en el Readme

**Comment by Sebastian-Assereto** [comment]
ósea que no habría problema en utilizar un botón? digo porque en el enunciado pagina 15 como que se enfatiza mucho el tema de utilizar el click izquierdo. Entonces crei que era de otra forma, pero supongo que el boton seria la forma indicada

**Comment by Lord-Kelsier** [comment]
Pusimos enfasis en la diferencia entre click izquierdo y derecho ya que al momento de **plantar** podias querer recoger un sol por lo que si fuera con el mismo click, recogerias el sol y plantarias en un lugar que no quieres.
