### ISSUE TITLE
[`validar_direccion`] Podemos considerar a un cañon de zanahorias equivalente a una pared?

### ISSUE THREAD

**Issue by dvillas28** [IIC2233/Syllabus#246]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/Syllabus/issues/243)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](https://github.com/IIC2233/Syllabus/issues/241)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Podemos asumir que que un cañon es equivalente a una pared?, es decir, que no nos podemos mover a la posicion de este. Pregunto esto en referencia a como programar la funcion `validar_direccion`

saludos!

**Comment by dvillas28** [comment]
Acabo de notar que en los test cases que no revisan eso, aun así, mantengo la duda por si acaso hay que programarlo para un caso borde que surja por ahi

**Comment by CrisDonosoMaass** [comment]
Hola, efectivamente los cañones cuentan como paredes por lo que la entidad del conejo no se puede superponer a estos.

**Comment by dvillas28** [comment]
perfecto! muchas gracias ඞ
