### ISSUE TITLE
Consulta formato para la línea de comando

### ISSUE THREAD

**Issue by brunoley** [IIC2233/Syllabus#246]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola!, he revisado como utilizar el módulo sys.argv y me di cuenta que, usando el formato que aparece en la tarea (“python3.11 main.py nombre_jardin nombre_dificultad”), el código me arroja error. En cambio, si utilizo el formato “py main.py nombre_jardin nombre_dificultad”, ahí el código corre sin problemas. 
No sé si será posible asumir que el formato que se entregará será este último que si me funciona. 
Gracias de antemano!

**Comment by augustayanez** [comment]
Está perfecto! El “python3.11” del principio puede ser remplazado por “python” o “py”, dependiendo de con cual de esos tres corre tu código.

**Comment by brunoley** [comment]
Super! Muchas gracias!
