### ISSUE TITLE
puntaje rios

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#246]
en el puntaje de los ríos se dice "55 puntos si el río conecta dos ciudades (una de ellas **no completas**)"  y "En el caso que los ríos conecten más de dos ciudades (con al menos una no completa), se entregarán 45*n puntos adicionales"
que pasa si conecta dos ciudades **completas**? (para cada caso por si solo)(aplico README nomas? 😅 )

**Comment by Arcoirisky** [comment]
Eso está especificado en el enunciado. Sección 3.8 si no me equivoco 😃

**Comment by rihanuch** [comment]
@Arcoirisky se me fue poner que el río tenia menos de tres piezas 😅  jajaj, que pasa en ese caso?

**Comment by Arcoirisky** [comment]
Hmmmm... Dime si me equivoco pero, creo que esa combinación no es posible 😮 (Lo digo con lo que recuerdo de las piezas 😅) y en caso que lo sea, si no está especificado en el enunciado entonces queda a tu criterio :D y aplicas README :)

**Comment by rihanuch** [comment]
Gracias!! 🙃🙃🙃
