### ISSUE TITLE
Duda sobre ejercicio 2.1: Uso de locks en ciclos

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#246]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### No entiendo bien por que el lock que puse no funciona

Para este ejercicio se me ocurrió encerrar lo que esta dentro del ciclo while con lock.acquire() y lock.release(), creí que así
lograría que cada thread siguiera su ciclo sin descoordinarse, sin embargo, se descoordinan igual.

Sospecho que puede ser debido al ciclo while que los threads se pelean el acquire, pero no estoy seguro, también, use
global para ingresar el lock dentro del scope de la función, no se si eso pueda interferir. (como código, hice prácticamente
lo mismo que en el primer ejemplo de uso de locks del cuadernillo 2)

**Comment by aaossa** [comment]
Hola @Pabloski100 , lo que describes está casi correcto. En primer lugar, no debería ser necesario el uso de `global` dentro de la función. Si creaste el `Lock` fuera de esta, es suficiente. Por otra parte, fíjate que antes de entrar al `while` ya hay una operación que depende del contenido de la cola, por lo que esa operación también debería ir dentro del *lock*. Otra cosa que puedes hacer es pasar el *lock* como argumento de la función, con lo que te aseguras de usar el mismo objeto (además que es más correcto a mi juicio). Si esto no te funciona, explica a qué te refieres exactamente con que se descoordinan los *threads* o cómo identificas esto. ¡Mucho éxito con tu estudio 🙌!

**Comment by Piolawa** [comment]
Hola, 
siguiendo la pregunta de este ejercicio, encapsulé la seccion critica poniendo el lock.acquire() antes del print("Haré un pedido!") y el lock.release() despues del print del else, pero en la linea del else.

Funciona, pero al final me tira un error IndexError, y no entiendo que falta por agregar, porque no deberia modificar las lineas que ya hay :c

**Comment by aaossa** [comment]
Hola @Piolawa , me hicieron ver que te dejé el visto hace mil años, aún tienes la duda? 😅
