### ISSUE TITLE
Datos unidades.txt

### ISSUE THREAD

**Issue by VicenteIgnacioSotoGonzalez** [IIC2233/Syllabus#246]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Buenas tardes, junto con saludar quería preguntar si podemos asumir que los datos numéricos de los combatientes en unidades.txt tendrán siempre valores que no son flotantes, osea que no sucede que un combatiente sea por ejemplo Esteban,CAB,260,10,5,8,5.5. Gracias de antemano.

**Comment by Benjeeeh** [comment]
Hola!
Dentro de los requisitos que pide el enunciado es verificar que el formato del archivo sea correcto, y eso toma en cuenta que:
1) Tenga las líneas y separaciones adecuadas
2) Que el formato indicado para atributo sea el correcto. 
En el último punto, se pide que algunos datos sean **str**  y puede que no haya mucho que hacer en este caso, ya que se puede pasar todo a ese formato, pero los demás atributos todos piden que sean **int**, por lo que si hay un valor en **float** el archivo no debe ser válido y se debe rechazar.

Saludos!

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Perfecto, muchas gracias!

**Comment by BenjaMedinaPUC** [comment]
Hola! esperando que se encuentren bien, escribo para saber si es que uno puede asumir que me van a entregar la misma cantidad de datos en el archivo siempre? onda, si al momento de verificar que si los datos entregados esten buenos o no, no tenga que ver el tema de que falten algun dato como estadistica, tipo o nombre?

**Comment by Benjeeeh** [comment]
@BenjaMedinaPUC 
Hola!
No, no puedes asumir que se te van a entregar la misma cantidad de datos siempre. El enunciado remarca en que se te van a entregar en ese formato las líneas de combatientes, por lo que debes verificar todo tipo de error que se te ocurra, como cantidad de parámetros, tipo de dato que se entrega, etc.

Saludos!

**Comment by pedro1ani** [comment]
### Error y Detención del Programa ###

[ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
[ x] Busqué en las issues si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
[ x] Revisé el compilado de dudas de la tarea y no encontré una issue similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/Syllabus/issues/167)).
[ x] Mi duda no se trata sobre una librería, built-in o mala práctica, ya que eso se pregunta en la issue creada para ello ([click aquí para ir a esa issue](https://github.com/IIC2233/Syllabus/issues/166)).
[x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso ([coordinacion.iic2233@gmail.com](mailto:coordinacion.iic2233@gmail.com)).
[x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
[x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.


Buenas noches, a la hora de verificar la validez del archivo unidades, el error y subsecuencia detención del programa debe ser al ejecutar este o al momento de comprar gatos
