### ISSUE TITLE
Desaparición de autos y troncos

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2233/Syllabus#246]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
hola tengo una duda respecto a la desaparición de objetos movibles, como los troncos y los autos
yo debo desaparecerlos cuando hayan salido por completo del borde del mapa, o puedo dejarlos seguir avanzando en la zona invisible de la ventana?
2do, que debe pasar en el caso que la rana se quede en un tronco y el tronco siga avanzando hasta desaparecer, la rana se debe caer al agua una vez el tronco haya salido por completo de la zona visible del juego?

**Comment by catalinacarter** [comment]
Hola @vice-rosas99! Como aparece en el enunciado "cuando el extremo final del auto alcance el límite del mapa, el auto **deberá desaparecer**" y "al momento en que el extremo del tronco alcance el límite del mapa, **deberá volverse invisible al usuario**".  Respecto a la segunda pregunta, debes considerar que **en caso de caer al agua o de colisionar con uno de los bordes del mapa** , perderás una vida y
Froggy tendrá que volver a la franja de pasto al inicio del nivel.

**Comment by vice-rosas99** [comment]
ok pero, el tronco debe detenerse cuando la rana esté sobre el o debe seguir moviendose hacia los lados (desplazando tambien al jugador horizontamente por el río?

**Comment by vice-rosas99** [comment]
para dejarlo claro, se tendría el mismo efecto esperado dejar que el tronco avanzara hasta salir del campo visible del usuario y detenerlo en esa posición?
