### ISSUE TITLE
Duda username

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#246]
es posible combiarse el nombre durante el curso, o por temas del repo-personal y los bots no recomiendan

**Comment by lily416** [comment]
Hola @sa-Appel, 

Debido a los repositorios fueron creados con sus nombre de usuario actuales les recomendamos no cambiarlo hasta que haya terminado el curso, ya que este se utiliza para descargar sus entregas y para obtener estadísticas sobre su actividad en github.

Saludos y que tengas un buen viernes 👋👨‍💻
