### ISSUE TITLE
Consulta sobre modelación y buenas prácticas

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#246]
¿Sería una mala practica entregar parametros de una `ClaseA` a una `ClaseB` para que la última cálcule cosas siendo que `ClaseB` está contenida en `ClaseA` como dentro de una lista?
Debería hacer todo dentro de `ClaseA`?? Me refiero a la relacion entre un vehiculo y una pista.
Saludos

**Comment by KnowYourselves** [comment]
Hola @dgzmr! 

Una de las cosas que uno busca con programación orientada a objetos es **encapsular las funcionalidades**. Respetando este principios hay dos opciones:

1. Se necesita directamente un atributo de `ClaseA`. <br> 
En este caso simplemente puedes hacer `instancia_a.atributo` dentro de `ClaseB` sin ningún problema, ya que todo esta encapsulado, es claro lo que estás haciendo, necesitas un atributo de las instancias de `ClaseA` y los estás obteniendo.

2. Se necesita obtener un valor que depende de atributos de `ClaseA` <br>
En este caso si tienes que hacer cálculos con los atributos de `ClaseA` para obtener lo que necesitas entonces **estos cálculos deberían hacerse dentro de un método en `ClaseA`, luego en `ClaseB` harías algo de la forma `instancia_a.obtener_valor()`. Cabe recalcar que esto también podría ser una _property_.

Como ejemplo tomemos una clase `Familia`, que tiene una lista con instancias de la clase `Persona`. 

1. Si dentro de un método de la clase `Familia` quisieras obtener el `dinero` que tiene cada persona, puedes simplemente hacer `persona.dinero`. 

2.  Si dentro de un método de la clase `Familia` quisieras obtener el gasto mensual promedio de cada persona, pero este no esta disponible directamente como atributo, entonces deberías definir un método o property en la clase `Persona` que lo calcule. Luego en `Familia` harías `persona.gasto_mensual()` (Sin paréntesis si fuera una _property_)

Espero haberte ayudado!

**Comment by dgzmr** [comment]
Creo que entiendo pero no sé si los ejemplos aplican a mi caso. Para ponerlo mas claro, dentro de la clase `Pista` tengo una lista de `Pilotos`, tenía pensado hacer un metodo `pista.iniciar_carrera()` que activara por todos los pilotos `piloto.correr()`. Ya que los pilotos son los que tienen que "correr"  pero a la vez para hacer esto necesito parametros de la pista en la que se encuentran a lo mejor debería hacer los calculos (con las funciones de funciones.py) en `pista.iniciar_carrera()` en vez de llevar los parametros al metodo del piloto como `piloto.correr(hielo_pista)`. Gracias por la ayuda.

**Comment by KnowYourselves** [comment]
Por tema de encapsulamiento de funcionalidades la opción `piloto.correr(hielo_pista)` es preferible y considerada mejor modelación. 

Ahora este tipo de problema específico tiene muchas formas correctas de ser solucionado!, La que propones es una de ellas.

Éxito!
