### ISSUE TITLE
Forma de retornar la posición de un elemento en un QGridLayout()

### ISSUE THREAD

**Issue by Liks96** [IIC2233/syllabus#247]
Hola!
Es creo que segunda vez que abro un thread, pero tengo una duda que me ha dejado pegado bastante rato. Hay alguna forma de poder recibir el valor "global" de posición de un widget en la ventana principal? Estoy intentando mostrar sprites sobre ciertas casillas específicas del mapa (que pertenecen a un QGridLayout pero la posición siempre pareciera que la define como "0" y nada más (siendo que lo deseable es que aparezcan sobre la tile en particular).

**Comment by hbkim94** [comment]
Hola!

La verdad no sé si entendí muy bien tu pregunta. Para saber la posición de un `QWidget`, tienes tres opciones:

```python
QWidget.x() #Retorna la coordenada x (int)  
QWidget.y() #Retorna la coordenada y (int)  
QWidget.pos() #Retorna un objecto QPoint, al que también le puedes sacar información.
```

Para más información, puedes revisar la [documentación de QWidget en C](https://doc.qt.io/qt-5/qwidget.html).

Ahora, si te referías a saber las posiciones de todas las particiones de un QGridLayout, honestamente desconozco si existe una forma. Lo que sí tengo entendido es que puedes ir metiéndole cosas a la grilla en orden de forma indexada, pero creo que eso ya se escapa de tu pregunta.

**Comment by hbkim94** [comment]
Oh! Creo que alguien si encontró una forma de obtener la posición de un item en una grilla. Revisa la función que se menciona en la issue https://github.com/IIC2233/syllabus/issues/249

**Comment by Liks96** [comment]
Muchas gracias por la respuesta! Estoy usando esos mismos métodos (x() e y()) para obtener la posición, pero parecieran no tomar la posición correcta, sino que 0. Seguiré dandole vueltas!

**Comment by fediaz3** [comment]
Hola! tengo el mismo problema, consulto la posición y me dan puros pares (0, 0)...
alguien sabe a que se debe el problema u otro método que rescate bien la posición? no he podido encontrar solucion

Gracias

**Comment by lily416** [comment]
@fediaz3 Revisa la issue #423.
