### ISSUE TITLE
Archivos a subir Tarea 2

### ISSUE THREAD

**Issue by Sergio-Cabrera** [IIC2233/Syllabus#247]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, estoy un poco complicado con los archivos que se deben subir, puedo subir 3 archivos ? ej: main.py, entidades.py y parametros.py? o subir 4 archivos?

**Comment by augustayanez** [comment]
Puedes crear todos los archivos que necesites o creas necesarios y modularizar tu tarea como tu quieras mientras lo expliques lo que hiciste y que contiene cada archivo en tu README.
