### ISSUE TITLE
Codigo corre doble

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#247]
Hola,
Nose porque razón hoy al abrir mi código de la tarea cierto modulo se ejecuta doble, lo he revisado completo y no encuentro razón para que lo haga, lo enviaría pero contiene una parte de la tarea.
Necesito ayuda, me estoy muriendo por dentro.

**Comment by dfloreaa** [comment]
mood

**Comment by jitorralba** [comment]
Hola @diego-ayala-2000!
El modulo que se ejecuta doble es uno que estás importando?
De ser así puede ser porque en el archivo del cual importas lo está ejecutando, entoces el main lo vuelve a ejecutar.

**Comment by diego-ayala-2000** [comment]
En parte si, en parte no. En este modulo tengo varias funciones, algunas tienen funciones importadas otras no, al momento de ejecutar cualquiera de ellas, se ejecutan dos veces

**Comment by jitorralba** [comment]
Puedes hacerle git pull a tu repo personal? Así podré revisar tu código sin mostrarlo por acá

**Comment by diego-ayala-2000** [comment]
Ya ahí lo subí, el modulo se llama Nueva_Partida.py y esta en la carpeta Combate Naval

**Comment by jitorralba** [comment]
Lo que pasa es que en `Nueva_Partida.py` estás importando `Menu_00.py` y `Menu_Juego.py`, pero en estos dos últimos importas a `Nueva_Partida.py`, por lo tanto el código de este se ejecuta también en los archivos en los que lo estás importando. No se si se entiende mucho pero es un tema recursivo.
En `Nueva_Partida.py` importo a `Menu_00.py`, por lo que se ejecuta, pero también en `Menu_00.py` importo a `Nueva_Partida.py`, por lo que este se vuelve a ejecutar.
Esto se arregla generando módulos independientes entre sí, esto no quiere decir que no puedas importar un módulo A en un módulo B, sino que no puedes importar un módulo A en un módulo B que a su vez tiene importado al módulo A.
Avisame si te quedó claro
Pd: Independiente de este problema está bacán lo organizada que está tu tarea.

**Comment by diego-ayala-2000** [comment]
Enserio muchas gracias por darte el tiempo. Me parece que entendí, veré que puedo hacer con lo que me dijiste.
