### ISSUE TITLE
USAR CODIGO

### ISSUE THREAD

**Issue by AngelMatias** [IIC2233/Syllabus#247]
Puedo usar este codigo 😬?

**Comment by andresfdezc** [comment]
Por favor lee las reglas del foro nuevamente. Al publicar código que planeas usar en tu tarea, se puede considerar como que estás facilitando la copia. Pueden inspirarse en código que les hayamos entregado en los repositorios. Este no es el caso.

El objetivo de la tarea es que implementes la estructura tú y el puntaje entregado se corresponderá con ese objetivo.

**Comment by AngelMatias** [comment]
ok gracias.
