### ISSUE TITLE
Función para captar errores y uso de exec_

### ISSUE THREAD

**Issue by kolk3y** [IIC2233/Syllabus#247]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Para el desarrollo de la tarea estoy usando el código facilitado para captar los errores de la interfaz gráfica, como el usado en la AS3:

if __name__ == '__main__':
    def hook(type_, value, traceback):
        print(type_)
        print(traceback)
    sys.__excepthook__ = hook

    juego = DCCubitos(sys.argv)
    juego.iniciar()
    sys.exit(juego.exec())

Mi pregunta es si esta permitido hacer esto, dado que se hace uso del built-in exec, el cual esta prohibido.
Junto con esto, me preguntaba si es posible utilizar el método exec_, perteneciente a la clase QDrag.

Gracias de antemano por la respuesta 🤯🤯🤯.

**Comment by Hellonston** [comment]
Hola @kolk3y! Acá hay un alcance de nombres. **Sí se puede utilizar**, ya que en ```juego.exec()``` llama al método ```exec``` de la librería **PyQt5** ya que es propio de **PyQt** y no tiene ninguna relación con el *built-in* ```exec``` de python

Saludos!
