### ISSUE TITLE
Jugadores incompletos (agregue duda a issue relacionada pero no se ha visto)

### ISSUE THREAD

**Issue by mblejeune** [IIC2233/Syllabus#247]
Tengo una duda con respecto a esto, en este caso, los jugadores que no tienen ni liga ni club, pero tienen nacionalidad y esta puede coincidir con la de otros jugadores por lo que pasarían a ser "conocidos" y por tanto formarían parte del grafo. Debo considerarlos en el grafo o simplemente obviarlos ? (al realizar las conexiones de afinidad -> 4.1)

Agregue mi duda hace 12 hrs a esa issue! pero quizas no se avisa que agregué un comentario por eso preferí usar otra issue :) Gracias!!

**Comment by cilopez** [comment]
Debes considerarlos en el grafo.

**Comment by mblejeune** [comment]
Gracias!!
