### ISSUE TITLE
Comportamiento de ítems con excavadores hibridos

### ISSUE THREAD

**Issue by criism0** [IIC2233/Syllabus#247]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola buenas! tengo una duda con respecto al comportamiento de los ítems que hacen perder energía y los excavadores híbridos, por ejemplo tenemos un ítem que nos hace perder 80 de energía a nuestros excavadores y uno de ellos es un excavador hibrido con 70 de energía, supongamos que hacemos uso del ítem en cuestión, ¿el excavador deberá descansar? o dado que tienen una reserva de energía su energía quedará en 20 y podrá seguir cavando. Muchas gracias de antemano

**Comment by criism0** [comment]
Respecto a esto, en el caso de excavadores de otro tipo, que al consumir un ítem que los deja sin energía, el excavador debe ponerse a descansar inmediatamente? o va a esperar a que el siguiente día termine para hacerlo?

**Comment by Benjeeeh** [comment]
@criism0
Como consumir un ítem se realiza antes de cavar, al quedar en 0 este debería entrar en descanso y estar imposibilitado de realizar acciones.

**Comment by criism0** [comment]
Perfecto!, y en el caso de que tengamos un excavador descansando y tomemos un ítem que nos sume energía , esto hará que deje de descansar? o el excavador se mantendrá descansando hasta que cumpla la cantidad de dias?

**Comment by Benjeeeh** [comment]
@criism0 
Podrías asumir lo mismo, ya que en sí el estado de descanso es cuando su energía = 0, entonces al darle un ítem y sumarle energía sale de este estado y podría realizar acciones como cavar.
