### ISSUE TITLE
Dudas sobre cuando terminar o no el programa

### ISSUE THREAD

**Issue by francorreaandrades** [IIC2233/Syllabus#247]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!!

Tengo varias dudas sobre que hacer en distintos casos cuando se corre el main.py 

1. Si cuando en la consola se debe ingresae "python3 main.py dificultad " se ingresan más argumentos de los permitidos o un nivel e dificultad invalido se debe cerrar el programa luego de indicar el tipo de error al usuario??
2. Si luego de abrir el archivo de diciltad este es invalido, se le informa al ausuario y se cierra el programa??
3. Si al cargar el archivo de unidades disponibles el archivo es invalido, se imprime el error y se cierra el programa??

Es correcto suponer que para todos estos problemas se debe cerrar el programa??

**Comment by Benjeeeh** [comment]
Hola!
Si, todos los casos que mencionas se menciona en el enunciado que el programa debe cerrarse.
El punto 1 y 2 se menciona en el apartado 6.1 de Dificultad:
![image](https://github.com/IIC2233/Syllabus/assets/78326186/453996eb-5c17-42a2-801e-767aa2d3c1aa)
![image](https://github.com/IIC2233/Syllabus/assets/78326186/4ceb69b9-b8d0-40f6-943e-14092dc2b1ec)
Y el punto 3 se menciona en el apartado 6.2 de Unidades disponibles:
![image](https://github.com/IIC2233/Syllabus/assets/78326186/89f360f7-c9dc-4a27-bfd6-4d282d01c9f4)

Saludos!

**Comment by francorreaandrades** [comment]
Okiii, muchas gracias.

Que en la tarea 1 me comentaron: "La idea era verificar que el input sea el esperado, luego si es malo avisas que debe ingresar un input de tal formato y no cierras el programa". 

Entonces me confundí, pero todo claro ahora, gracias!!

**Comment by Benjeeeh** [comment]
Si! Bajo ese contexto está bien, ya que la idea era trabajar con el menú y que se realizara el loop esperado, y no que por un input se cierre todo el programa. En el menú de esta tarea se espera que hagas lo mismo, el menú se ejecute en loop y logre tomar un input erróneo y que no se cierre, si no que te pida otro hasta ingresar uno correcto, así que ojo ahí!

Sobre los casos que mencionas en la issue, es correcto que se cierre ya que uno es por un error en el terminal, por lo cual no se ejecuta nada, y los otros dos errores son por fallas en los archivos, ya que si estos están erróneos no podría seguir el juego!
