### ISSUE TITLE
Testear con estructuras prohibidas

### ISSUE THREAD

**Issue by glbello** [IIC2233/Syllabus#248]
¡Holas! quería saber si puedo testear mi clase ```milista``` usando estructuras prohíbidas. Por ejemplo, referenciando la ayudantía de testing:

```python
import unittest


class FraccionTest(unittest.TestCase):

    def setUp(self):
        self.tuplas_fraccion = [(3,4),(20,80),(1,27)]
        self.tuplas_error = [(4,0),(1.4,2),("2","7")]
        self.trivial = Fraccion(1,4)
```

En este caso está testeando la clase fracción, y usa listas y tuplas (para este caso prohíbidas), pero esto solo para testear.

**Comment by glbello** [comment]
Bueno, en realidad no es necesario que suba el ```test.py```, asi que no influye en mi tarea la verdad...

**Comment by sebacruzd** [comment]
Hola, sí puedes, ya que como dices no es necesario que lo subas porque no se evaluará testing en esta tarea (y si lo subes, pon en tu README que no lo revisen).

Aparte, el testing es para probar funcionalidad, por lo que debería poderse hacer con todas las herramientas que quieras.

Saludos!

**Comment by glbello** [comment]
Perfecto. Muchas gracias por la respuesta
