### ISSUE TITLE
Pauta controles

### ISSUE THREAD

**Issue by pita-horn** [IIC2233/Syllabus#248]
Hola! Quería saber si suben la pauta de los controles a alguna parte y si podemos ir a retirarlos para ver si podemos recorregir o ver donde nos equivocamos u.u

**Comment by jorgeriesco** [comment]
la pauta la suben en tu repositorio en la parte que esta tu actividad guardada

**Comment by sebacruzd** [comment]
Van a estar en el DCC. Se avisará cuando estén disponibles para su recorrección. Se subirá una pauta para poder ver si les corrigieron mal.

**Comment by fvr1** [comment]
Los controles van a estar mañana en el DCC, se subió una pauta del control 2 a la carpeta de controles en el Syllabus y la pauta del control 1 está en esta [issue](https://github.com/IIC2233/Syllabus/issues/196)
