### ISSUE TITLE
importacion de modulos cruzada

### ISSUE THREAD

**Issue by F-arellano** [IIC2233/syllabus#248]
termine creando bastantes clases y para poder ubicarlas mas facilmente quise separarlas en 2 modulos, pero al parecer no me permite importar un modulo A a uno B cuando el modulo A ya esta utilizando a B, por lo cual no me permite heredar de la clase principal a una subclase definida en el otro modulo. ¿hay alguna solucion? pensé en importar solo la clase dentro del codigo para que no colapse, pero como para la tarea hay que importar todo el modulo al principio no estoy seguro de como solucionarlo

**Comment by matioprts** [comment]
Hola F-arellano!

Sí, lo que hiciste se conoce como programación circular y es algo que hay que evitar. Intenta separar tu código de manera que todo lo que hagas en el módulo A, sea usar código del mismo módulo o de otros módulos importados que no ocupen código del módulo A. Y si luego quieres importar a un módulo B todo el código usado en el módulo A, incluyendo los import que hiciste en el módulo A, basta con hacer import del módulo A.

Aplicando un ejemplo, tienes 2 funciones en el módulo Z, creas un módulo A con una clase Inicial, y acá importas el módulo Z para ocupar esas 2 funciones en tu clase Inicial. Luego creas un módulo B donde importas SOLO el módulo A, y creas una clase Final que hereda de la clase Inicial. Esta clase Final tendrá acceso a todas las funciones de la clase Inicial, incluyendo las funciones del módulo Z.
