### ISSUE TITLE
Movimiento hacia la derecha

### ISSUE THREAD

**Issue by YoGandalf** [IIC2233/syllabus#248]
Algunas sprites que estan subidas no tienen imagenes de los personajes moviendose hacia la derecha. Hay que darlas vuelta nosotros mismos o faltan imagenes por subir o que se hace con eso?

**Comment by DCCollao** [comment]
Hola! Revisa #208. Si te queda alguna duda, hazla como comentario en esa misma issue, para evitar tener varias del mismo tema.
Éxito!
