### ISSUE TITLE
Error ingreso usuario

### ISSUE THREAD

**Issue by solebravo** [IIC2233/Syllabus#248]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! en el enunciado, en la seccion de Ventana de inicio, se pide que si existe un error al ingresar el usuario se muestre en la pantalla el motivo del error, pero que sucede si existe mas de un error? (ej: clave = d?e), deberian aparecer ambos en la consola?
Gracias de antemano!

**Comment by favallem** [comment]
Hola, puedo tener solo un mensaje que muestra los 2 errores posibles en todos los casos? O necesariamente debe especificar qué condición gatilla el error?
