### ISSUE TITLE
Problema al colocar un label sobre otro

### ISSUE THREAD

**Issue by nolate26** [IIC2233/Syllabus#248]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ]X Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ]X De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Me pasó que tengo instanciado el ***label de froggy*** pero al correr el programa los ***labels de los troncos*** se superponen al label de froggy por lo  que no se ve de manera apropiada ya que se ve el tronco por encima de este. ¿Cómo puedo ***superponer*** el label de froggy por encima de el de los troncos?

**Comment by rodrigobj99** [comment]
Hola @nolate26 ! Tal como comento tu compañero @drcid98 existen los metodos lower() y raise_() que permiten traer al frente o enviar al fondo diversos label.
