### ISSUE TITLE
Consulta sobre asumir un supuesto relacionado con los archivos.csv

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#248]
Hola!

Quisiera saber si es un supuesto válido (colocándolo en el README) que los _archivos.csv_ tendrán exclusivamente los tipos de datos que se señalan en el enunciado. En particular, mi pregunta es si estos archivos pueden venir **sin** la primera línea que señala a qué corresponde cada columna.

Por ejemplo, en el archivo _canales.csv_ la segunda columna son del tipo _int_ excepto la primera línea, la cual es una palabra/string que menciona que esa respectiva columna hace referencia al "tamaño" del canal. ¿Puedo asumir que la primera línea no existirá, declarándolo en el README?

![imagen](https://user-images.githubusercontent.com/50121013/115162713-fb6ef180-a072-11eb-8807-2c508ea179b2.png)

**Comment by Juampisaez** [comment]
Hola @jamigone 
Al igual que la tarea pasada, los archivos venian en el mismo formato, la idea es que manejes este tipo de situaciones. En particular, bastaria con omitir la primera linea si lo deseas, como también podrias ocuparla como apoyo al crear tus estructuras de datos por ejemplo. En resumen, no puedes hacer ese supuesto.

Espero conteste a tu pregunta :)
Quedo atento de igual forma.

**Comment by jamigone** [comment]
jajajaja pucha. gracias por la respuesta :)

**Comment by Juampisaez** [comment]
@jamigone Pero no te desanimes, aprovecha esas lineas para complementar tus estructuras de datos.

**Comment by jamigone** [comment]
Eso haré jajajja. Aunque me desanimo porque fallé haciendo ese mismo supuesto en la tarea 0 😅
