### ISSUE TITLE
Respecto a .gitignore en syllabus

### ISSUE THREAD

**Issue by ConiCollector** [IIC2233/syllabus#248]
Hola

Es posible que agreguen en el .gitignore de syllabus la extencion .ipynb_checkpoints/ para ignorar. Dado que, tras hacer un cambio de cualquier tipo en las ayudantias con jupyter se me genera una carpeta con esta extensión. Por tanto, cuando hago git status me sale el anuncio de que existen y es un poco molesto visualmente.   

Gracias de antemano 
Constanza

**Comment by KnowYourselves** [comment]
Hola @ConiCollector!

Parte de las habilidades que esperamos que desarrollen en este ramo es el uso debido de `.gitignore`. Intenta modificar el `.gitignore` del _syllabus_ para que ignore los archivos que te están molestando (es exactamente en este tipo de casos donde se utiliza). 

En caso de que no logres hacerlo, o haya algo que no entiendas, comenta nuevamente esta _issue_ y te ayudaré a hacerlo.

Éxito!

**Comment by ConiCollector** [comment]
Hola 

En mi `.gitignore` de mi carpeta del computador ya había arregle ese problema, pero no estaba segura si podía hacer un `git add` y luego `git commit -m ` de ese arreglo, dado que el _syllabus_ lo compartimos todos y según tenía entendido es de manejo de los ayudantes y los profesores. Entonces, mi pregunta ahora sería si ¿puedo actualizar el `gitignore` del _syllabus_?

Saludos

**Comment by aaossa** [comment]
@ConiCollector efectivamente como dices, para cambiar el archivo habría que hacer un *commit* y hacer *push* al Syllabus, lo que no puedes hacer 😅 Lo cambiaré en unos minutos para que no tengas problemas. Vuelvo en seguida 🙌

**Comment by aaossa** [comment]
Listo, agregué una sección en el `.gitignore` para ignorar los *checkpoints* 💯 (Aquí puedes ver el commit: 247f6aa4a1e0eacf481721d05aef82363983d458). También agregué una explicación de qué se está ignorando, por si quieres darle una mirada 🤓 Si tienes algún problema ocupando `git pull` ahora pregunta acá mismo, por si tienes que hacer pasos adicionales para que te funcione bien 👌 Gracias por el aviso!

**Comment by ConiCollector** [comment]
Hola 

Muchas gracias quedo de pana banana y funciono perfecto, además ahora cada vez que hago `.git status` esta todo en orden y no salen lineas en rojo.

Saludos Constanza
