### ISSUE TITLE
Duda con función separar_mensaje

### ISSUE THREAD

**Issue by gaspar-mr05** [IIC2233/Syllabus#248]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](https://github.com/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. Tengo una duda con respecto a la funcion separar mensaje. En esta funcion tenemos separar un mensaje en tres partes: A, B y  C, segun el enunciado. Y yo entiendo que se refiere a la parte 7.1.4, y de eso yo entendi que cada mensaje debe separarse en una secuencia ABCCBA y asi consecutivamente. Y asi se ve en el ejemplo, ya que se tiene b0b1b2b3b4b5b6b7b8b9. Y cada "b" se va guardando en un orden ABCCBA, b0 a A, b1 a B, b2 a C, b3 a C, b4 a B, b5 a A y asi consecutivamente ABCCBA. De esta forma tambien se hace en el ejemplo de la funcion separar_mensaje. Sin embargo, en los test_cases de la tarea, separan todos de la forma ABCABC... no ABCCBA... .Lo cual no va acorde a lo que dice en el enunciado. Esto tambien afecta a la funcion siguiente (encriptar_mensaje), ya que en esa se necesita separar_mensaje.

**Comment by dvillas28** [comment]
confirmo, en los tests, los arrays se encuentran encriptados de otra forma.

**Comment by Laefivy** [comment]
Sii, tengo la misma duda

**Comment by LudwigUC** [comment]
Hola, efectivamente hay un error en la función separar mensaje correspondiente a los test cases, les notificaremos cuando sea corregido, muchas gracias por notificar esto ;)
Guíense por lo que dice el enunciado, esa es la forma correcta de encriptación del mensaje!

**Comment by matix3000** [comment]
Hola! disculpen, creo que el test 07 de separar mensaje sigue malo, por ejemplo tomando 
"Hola Mundo"
H \in A, o \in B, l \in C, a \in C, _ \in B, M \in A, u \in B n \in C, d \in C, o \in B
A = {HM} != {HMu}
B = {o uo} != {o n}
C = {land} != {lado}
El error se da que se añade a A, M y u, en lugar de solo M, quizá tengo yo un problema en la comprensión de la encriptación, un saludo!
