### ISSUE TITLE
Duda metodo atacar

### ISSUE THREAD

**Issue by francorreaandrades** [IIC2233/Syllabus#248]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!!

Un par de dudas de los métodos atacar de los diferentes tipos de combatiente:

1. En la clase Guerrero, primero se ataca la vida del oponente y luego se disminuye la agilidad del combatiente o no??
2. En el Caballero, cuando ataca se menciona que reduce el poder de su enemigo, eso es solo para ese ataque o para siempre??
3. En el Paladin, si no se activa el modo atacar del Caballero, ataca como Guerrero??
4. En el Mago de Batalla, si no se activa el modo atacar del Mago, ataca como Guerrero??
5. En el Caballero Arcano, al hablar de la probabilidad PROB_CAR y 100-PROB_CAR, significa que si la probabilidad aleatoria es menor a PROB_CAR ataca como Caballero y sino ataca como Mago?? 

Por otro lado, cuando 2 combatientes pelean y se atacan, esto debiese ser simultáneamente, pero como no se puede hacer en paralelo, puede atacar el combatinte del ejercito del usuario y luego el del ejercito enemigo?? 
Pues el orden en el que se atacan influye en la disminución/aumento de los parámetros de ambos combatientes. Por ejemplo, el que ataca segundo ataca con peores parametros que cuando se estan por enfrentar inicialmente. Que se hace en este caso??

**Comment by Benjeeeh** [comment]
Hola!
Responderé punto por punto:
1) Si! El enunciado menciona que después de cada ataque se reduce su agilidad, porque se cansa.
2) Los efectos son para siempre! En el caso de que no se mencione algo específico en el enunciado, puedes asumir y tomar uno de los dos casos, que se aplique por ronda y luego se restablezca (mucho trabajo) o para siempre.
3) Si.
4) Sip.
5) Sip, en otras palabras, si no se cumple una probabilidad, entonces se cumple la otra.

En lo último, lo más importante es que si o si se realicen los dos ataques que corresponden, uno de tu combatiente y uno del enemigo. En caso de que uno muera por atacar primero, igual se debe ejecutar el otro ataque. Fuera de esto, puedes realizar supuestos de que tu atacas primero ganando un poco de ventaja. Puedes leer la issue #243 que preguntaron lo mismo!

Saludos :)
