### ISSUE TITLE
Duda enunciado archivos/pistas

### ISSUE THREAD

**Issue by Molin1234** [IIC2233/syllabus#249]
En el enunciado (Punto 6.Archivos, Pg.13) nos dicen "Considera que el contenido y el orden de las columnas de estos archivos puede variar".
Mi duda es si con que varía contenido se refiere a que mi programa debe ser susceptible a correr por ejemplo un archivo que en vez de 6 pistas tenga 7 (o cualquier número de pistas)?

**Comment by Juan379** [comment]
Tu programa debe ser capaz de poder correr una cantidad indefinida de pistas (los ayudantes pueden ir cambiando esta cantidad) y a su vez, las columnas en si te las pueden ir cambiando de orden (los ayudantes las cambiaran por ende tu programa debe considerar estos cambios).
Por ejemplo si tienes Nombre, Categoria, Chasis; debe ser capaz de leer Nombre, Chasis, Categoria de la misma forma sin caerse,

**Comment by Molin1234** [comment]
Vale lo primero no me había quedado claro en el enunciado, muchas gracias!!

**Comment by jaromero6** [comment]
Hola!
Efectivamente es como dice @Juan379 , puede variar tanto el número de filas como el orden en que están las columnas.
Ánimo con la tarea!!
