### ISSUE TITLE
Duda sobre el uso de una libreria no nombrada en las reglas

### ISSUE THREAD

**Issue by dalcalde5150** [IIC2233/syllabus#249]
Hola, una vez me llego una foto donde aparecia las librerias permitidas y las prohibidas del curso, ya no encuentro el archivo de donde fue sacada, pero basandome en esta, veo que la libreria operator no aparece ni permitida ni prohibida. Esta libreria la uso en mi tarea para ordenar una lista de tuplas en el ranking de jugadores. 

Entonces mi duda es ¿Puedo usar esta libreria o esta prohibida?

**Comment by DCCollao** [comment]
Hola @dalcalde5150!

La foto que te llegó debe haber sido de la issue #87, que se trata justamente de las librerías permitidas y prohibidas en **la tarea**(no necesariamente el curso). Cada tarea tendrá una issue así para que pregunten por las librerías que quieran usar.
Esa issue se encuentra también **pinneada** para que la encuentren fácilmente. Es ahí donde debes realizar esta misma pregunta.

Espero que haya quedado claro!
