### ISSUE TITLE
Ciudades completas

### ISSUE THREAD

**Issue by tomasrivera** [IIC2233/Syllabus#249]
> Una ciudad se considera completada si está totalmente rodeada por murallas.

En caso de tener esas piezas:

![cggcgg](https://user-images.githubusercontent.com/26392989/30131937-fabf0d9c-9324-11e7-9229-c3527f4e13f3.png)
![ggcggc](https://user-images.githubusercontent.com/26392989/30131938-faca626e-9324-11e7-8bec-1a0e334a5e46.png)

CGGCGG y GGCGGC que son casi iguales (ambas tienen dos orillas de ciudad con pasto en el resto), ¿se puede diferenciar una de las dos piezas para que el algoritmo la reconozca?, pregunto por si van a ser las mismas piezas las que se usarán para la corrección.

**Comment by Arcoirisky** [comment]
Si, se usarán las mismas piezas para revisar la tarea. No te preocupes por eso, no aparecerá una pieza mágica que no esté en la tabla del enunciado 😅

**Comment by behrmann97** [comment]
Que pasa con la pieza con pasto entre medio,¿ las ciudades son distintas? y en este caso cómo hacemos para diferenciar ambas piezas, ya que una une dos ciudades y la otra las separa.

**Comment by Sforrego** [comment]
creo que tenemos que asumir que son la misma pieza :)
