### ISSUE TITLE
Duda sobre parametros para Solaretillo

### ISSUE THREAD

**Issue by Vicho03** [IIC2233/Syllabus#249]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Los parámetros CONSTANTE_SOLES, POTENCIAL_SOLARETILLO_MIN y POTENCIAL_SOLARETILLO_MAX, ¿ son todos números naturales cualesquiera o pueden ser decimales?

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by AndreaVict** [comment]
Holaa, es tu decisión asignarle el valor a los parámetros mencionados, por lo que ambas opciones que mencionas son válidas. Eso si, recuerda que los valores asignados tienen que ser acorde al enunciado. Es decir, CONSTANTE_SOLES no puede ser un número menor a 0. Espero que haya quedado claro, mucho éxito en la tarea.

**Comment by Vicho03** [comment]
¡¡Muchas gracias!!!
