### ISSUE TITLE
grilla.itemAtPosition(x,y)

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#249]
que pasa si ocupo esta función pero hay dos items en en una posición de la grilla? 
cual de los dos me retorna?

**Comment by jmwielandt** [comment]
Hola
Esas cosas se recomienda mejor programarlas con un mini ejemplo y ver que sucede. Esto te permitirá no solo ver que pasa ante este caso, sino ante otros casos como ¿si no hay nada? ¿retorna None, una lista, un raise?.

Ánimo con la tarea! :D
