### ISSUE TITLE
threading args, int con coma(?

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#249]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Por qué la coma?

![image](https://user-images.githubusercontent.com/66154723/115166086-53abf080-a07f-11eb-88ce-77303d1828a1.png)

**Comment by aaossa** [comment]
Hola @fernandosmither , en ese constructor *args* debe ser una tupla. Lo que ves ahí es el uso de la sintaxis de Python para declarar una tupla con un solo valor. Cuando queremos declarar una tupla con un solo valor no podemos hacer `(valor)` porque Python evalúa eso como si no estuviera el paréntesis. Entonces, al poner la coma, estamos explicitando que eso es una tupla. Puedes verificar esto imprimiendo el `type` de `(10)` y de `(10,)` 👌 Cuéntame si tienes otra duda, ¡éxito con tu estudio!

**Comment by fernandosmither** [comment]
> Hola @fernandosmither , en ese constructor _args_ debe ser una tupla. Lo que ves ahí es el uso de la sintaxis de Python para declarar una tupla con un solo valor. Cuando queremos declarar una tupla con un solo valor no podemos hacer `(valor)` porque Python evalúa eso como si no estuviera el paréntesis. Entonces, al poner la coma, estamos explicitando que eso es una tupla. Puedes verificar esto imprimiendo el `type` de `(10)` y de `(10,)` 👌 Cuéntame si tienes otra duda, ¡éxito con tu estudio!

SSentiende.
Gracias!
