### ISSUE TITLE
copiar una self.caracteristica sin que sean el mismo objeto

### ISSUE THREAD

**Issue by antoniablanco** [IIC2233/Syllabus#249]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Como puedo copiar una característica self.caracteristica de una clase, y que al modificar la copia no se modifique tambien el valor original. Porque al realizar 
Caracteristica = self.caracteristica
caracteristica is self.caracteristica
True

**Comment by Christian-Klempau** [comment]
Hola @antoniablanco !
Podrías usar el método `copy()` del módulo `copy` de la librería estándar de Python.
Es decir: `caracteristica_copiada = copy(caracteristica)`. Esto retorna una copia del objeto. Si tu objeto contiene objetos dentro o es más complejo, puedes usar `deepcopy()` de la misma librería.
Eso sí, si lo quieres usar para alguna tarea recuerda preguntar si su uso está permitido.
Suerte! :D
