### ISSUE TITLE
Ataque Mago

### ISSUE THREAD

**Issue by coniverav** [IIC2233/Syllabus#249]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, cuando en la descripción de los ataques de los magos se menciona que "ignoran" un porcentaje de la defensa del enemigo, esto quiere decir que se enfrenta a él _como si_ tuviera menos defensa durante ese ataque, o efectivamente tengo que disminuirle ese porcentaje a su atributo?
<img width="781" alt="image" src="https://github.com/IIC2233/Syllabus/assets/162245893/d6defdaa-1c5d-4022-9fa9-2c8344b31464">

**Comment by gasparbenavente2** [comment]
Hola! Ese porcentaje es solo para el cálculo y no tienes que modificar los atributos
