### ISSUE TITLE
Estadisticas: Promedio muertes e infecciones

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#249]
Estimados,

Se que es la milesima vez que se pregunta sobre este punto, pero nunca me quedó claro.
Pido encarecidamente que se explique este punto ojala con peras y manzanas, por favor.

Para ayudar a la explicación, quiero hacer ver por que no se entiende lo que aparece escrito:
1) El titulo dice **Promedio de muertes e infecciones** y luego en la descripción habla de **tasa de vida y muerte**, lo cual es claro que es un error de tipeo. ¿"Muertes e infecciones" o "muertes y vida"?
2) Dice luego **muertes de personas del día actual**. No entiendo esto, ya que ya se pide la cantidad de muertes del día actual en otra estadística, entendiendo esto solo como un numero y no un promedio. Si se refiriera a un promedio, no se dice con respecto a que es ese promedio, es decir, no se entiende si es por país (osea dividir en la cantidad de países) o si es por hora (osea dividir en 24). Para el acumulado asumo que se divide en la cantidad de días que han pasado, ya que no se ve otra opción.
3) Ademas no entiendo que es **tasa de vida**. Podría ser cuanto ha curado la cura por día y dividir en la cantidad de días o también podría ser cuanta gente hay viva al día y dividir en la cantidad de días (hablando del caso acumulado hasta la fecha).

Si había una issue que respondió a esto ya, me disculpo y agradecería el link de esta, sino me gustaría que se aclare esto para poder avanzar. Gracias

**Comment by FernandoPieressa** [comment]
1)Muertes y infecciones

2)Tal como dices el acumulado es el promedio por día, sin embargo como por día no esta especificado, queda a tu criterio

3)Como dije en el 1, es muertes e infecciones por lo tanto no importa

Creo que lo había escrito en otra issue pero no la encontré asique lo escribo denuevo.

Saludos!

**Comment by nivek0o0** [comment]
¿ Es tasa de muertes y tasa de infecciones o tasa de muerte y tasa de vida (no contagiados) como dicen en la issue #178 ?

**Comment by FernandoPieressa** [comment]
Nuestro objetivo era promedio infecciones y promedio de muerte,  pero si hiciste lo de tasa vida en vez de infecciones también sirve.

**Comment by nivek0o0** [comment]
Sigo sin entender lo que se está pidiendo en la última estadística. He leído todas las issues relacionadas y las respuestas no son directas. **¿Qué es lo que hay que promediar?** 

Para "el acumulado":
¿Hay que calcular el Total de personas infectadas por mi virus durante el juego (que es distinto a los actuales infectados, ya que algunos podrían haberse sanado o muerto) dividido en el número de días transcurridos? Me imagino esta estadística como una forma de medir la efectividad de la infección escogida.

Para "el día actual":
Si fuese Calcular la cantidad de infecciones en ese día..¿no se muestra el mismo número en la estadística **Resumen del día**?

Gracias por el tiempo.

**Comment by FernandoPieressa** [comment]
Son las personas infectadas durante todo el juego dividido el numero de días transcurridos tal como dices.

Para el día actual, depende porque esta a su criterio, pero podría ser sacar la cantidad de infecciones de cada país en un día y después dividir en cantidad de países o alguna cosa similar, pero esta a su criterio al no estar especificado.

**Comment by nivek0o0** [comment]
Gracias!
