### ISSUE TITLE
Lintern en VScode

### ISSUE THREAD

**Issue by abraxvs** [IIC2233/Syllabus#25]
### Problema

**¿Qué significa la siguiente advertencia?**
En un contexto de instalación de VScode, estoy poniendo el lintern pycodestyle
![Captura de pantalla 2023-08-17 150921](https://github.com/IIC2233/Syllabus/assets/112010846/f28861b3-3634-4859-9342-748de0997be1)

**Comment by Hernan4444** [comment]
Hola @abraxvs 

Ese warning explica que si bien se instaló el linter, este fue instalado en una carpeta que no está en PATH. 

¿Qué significa que no esté en PATH?  🤔 

Que si en consola quisieras escribir `pycodestyle` no lo va a detectar tu terminal porque no hay ningún PATH que apunte a ese archivo. Por ejemplo, python si fue instalado en una carpeta que si está en PATH y por eso puedes hacer "python3" en tu terminal de WSL.

En este curso no usaremos esa librería como comando de terminal, así que no te preocupes. Lo importante es que si haces click en `"Problems"` ahí te aparezca qué errores de PEP8 tiene tu código.

Quedamos atentos a tus comentarios,
Saludosヾ(＾-＾)ノ
