### ISSUE TITLE
Registrar PyCharm

### ISSUE THREAD

**Issue by jadiaz6** [IIC2233/Syllabus#25]
Por más simple que paresca no he podido registrar PyCharm. Descargué la versión completa, ya que se supone que si eres estudiante te lo dan gratis. Me registré y el programa aceptó, el problema es que para activar PyCharm full, debo dar un codigo de registro, no sé dónde está. He estado buscando por mucho tiempo ya.

Gracias y saludos

**Comment by fnquinteros** [comment]
Entraste aquí? https://www.jetbrains.com/shop/eform/students

**Comment by naazocar** [comment]
Cuando creas la cuenta con el mail uc te piden verificar la cuenta y bla bla, luego vas a tu perfil en JetBrains y tienes un codigo a la derecha que dice license ID, creo que ese era. O si no había que usar los datos de tu cuenta. Disculpa la poca precisión, lo instalé hace tiempo. 

Suerte :)

**Comment by jadiaz6** [comment]
gracias gracias, voy ver ahi
