### ISSUE TITLE
Asistencia AC02

### ISSUE THREAD

**Issue by dabalada** [IIC2233/syllabus#25]
Para conseguir las décimas de la actividad es necesario estar presente en la sala y puesto que me corresponde?

**Comment by Hernan4444** [comment]
¡Hola @dabalada!

Así es, es necesario estar presente y en el puesto asignado. Además es necesario que subas a tu repositorio, en la carpeta AC02, una muestra de que hubo un intento de realizar la actividad dentro del plazo de clases y finalmente realizar la autoevaluación.

Saludos ✌️
