### ISSUE TITLE
eliminar archivos en git

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#25]
intentando crear el .gitignore, resulta que e terminado subiendo una carpeta del mismo nombre a mi repositorio, y quería ver si existe la posibilidad de borrarla

**Comment by DCCollao** [comment]
Hola @felipehen !

Puedes usar el comando `git rm path_carpeta` para eliminar de tu repositorio el archivo que desees. En el caso que la carpeta `.gitignore` tenga archivos dentro, deberás usar la flag `-r`, quedando el comando de la siguiente forma:
`git rm -r path_carpeta`.

Una vez hayas seguido los pasos anteriores, solo queda hacer un commit y push.

Quedo atento a cualquier duda!
