### ISSUE TITLE
Posibles problemas con usar anaconda

### ISSUE THREAD

**Issue by CarlosValleA** [IIC2233/syllabus#25]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola!,

En la ayudantia indican que no es recomendable utilizar anaconda para el curso, dado que hay problemas para correr algunos codigos aun cuando es python 3.7.x. Mi duda es ¿que problemas pueden surgir? para tenerlos en cuenta. Utilizo anaconda para otras cosas por lo que se me hace dificil borrarlo por completo.

El ambiente que cree en anaconda lo hice de la siguiente forma:

`conda create -n progra python=3.7`

Luego instale todos los paquetes utilizando `pip`, tendre algun problema ?

Gracias!!

**Comment by pabloist** [comment]
Hola cómo estás?

Te comento que todos los IDE y otro tipo de librerías realizan una interpretación del código de Python. ¿Qué significa esto? Significa que en determinadas ocasiones puede que Anaconda no interprete errores o no emule finalmente el comportamiento buscado en las tareas o actividades que finalmente revisa un ayudante, o sea, puede que tu código funcione perfectamente en Anaconda en tu computador, pero que al revisarlo no muestre lo que tu ves o levante excepciones.

En virtud de tratar de evitar estas problemáticas, recomendamos **encarecidamente** utilizar los software indicados. En última instancia, puedes realizar tus desarrollos en Anaconda, pero siempre corroborando a posterior que el código funcione en los software indicados.

Saludos! :)
