### ISSUE TITLE
Funcionamiento general tarea y función cargar archivo.

### ISSUE THREAD

**Issue by BenzoylMorexide** [IIC2233/Syllabus#25]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

**¿Para qué existe el archivo solución con su archivo asociado que tiene solamente las bombas?**
No comprendo por qué exactamente están ambos archivos y cuál debiese ser cargado si el usuario pide cargarlo. Es decir, ¿debiese comprobar si existe el archivo 2x2 por ejemplo simplemente?

Además, me confunde un poco con qué archivo cargar al momento de hacer uso de la función cargar_archivo() porque no sé si debo cargar el archivo solución y revisar si es válido, cargar el archivo solamente con las bombas y revisar si es válido para luego, a través de código poner yo las tortugas y hacer una revisión última de que todo esté en orden cumpliendo las reglas (usando las funciones) o si debo tomar ambos archivos y hacer algo con ambos al mismo tiempo.

**Comment by Hernan4444** [comment]
Hola @BenzoylMorexide 

En el menú de incio se pide indicar el nombre del archivo a cargar y ese es el que cargas. Si escribo `"2x2.txt"`, es ese archivo el que usaremos en el siguiente menú, y si escribo `"2x2_sol.txt"`, será ese otro archivo a cargar. 

Considera cada archivos de forma independiente. Solo que nosotros usamos ese formato para que supieras que `"2x2_sol.txt"` es una solución para el archivo `"2x2.txt"`.


Luego, en el segundo menú, donde el archivo ya está cargado, todas las opciones son referentes al archivo selecionado:
- Imprimir el tablero del archivo seleccionado
- Solucionar ese tablero y guardarlo como `"{nombre_original}_sol.txt"`
- etc

Ahora bien, como hay opciones del menú para validar el tablero (opción 2 y 3), les entregamos tableros ya resueltos para que tengan algunas casos adicionales para probar sus funciones. 

Respeto a la función `cargar_archivo` esta recibe el nombre del archivo a cargar y ese es el único que cargas. No busca ningún segundo archivo, solo carga lo que el argumento `nombre_archivo` te indica.

Espero que esta explicación haya ayudado a entender mejor el funcionamiento general de la tarea, sino, estaremos atentos a las issues.

Saludos c:

**Comment by gsinay** [comment]
Hola @Hernan4444 !

Aprovecho este espacio para hacer una pregunta relacionada al issue. Dado a que nos entregan archivos "nxn_sol.txt", al resolver los archivos "nxn.txt" y guardarlos como nos piden en la página 6 del enunciado, no estaríamos teniendo mas de un archivo con el mismo nombre en el directorio :/?
