### ISSUE TITLE
Duda con guardar partida

### ISSUE THREAD

**Issue by ceosorio** [IIC2233/syllabus#25]
Hola! 
Sobre el .txt de la partida guardada solo se puede guardar la información de los legos y del tablero descubierto? O puedo por ejemplo guardar las dimensiones del tablero de esa partida?

**Comment by KnowYourselves** [comment]
Hola @ceosorio!

No hay problema con que guardes las dimensiones del tablero en el `.txt`. 😄 

Éxito!

**Comment by ceosorio** [comment]
Perfecto, Gracias!

**Comment by mscuturrufo** [comment]
Hola! No entiendo bien si en el .txt guardo la información que me sea útil o hay requisitos (como el que mencionaron antes de la cantidad de legos)??

**Comment by KnowYourselves** [comment]
Hola @mscuturrufo!

El único requisito es que guardes todo lo necesario para cargar la partida correctamente.

Éxito!

**Comment by Pabloinz** [comment]
Hola! Cuando se refieren a "[guardar] todo lo necesario", implica estrictamente solo lo necesario? Por ejemplo, si añado algún dato extra que técnicamente no es necesario añadir para cargar la partida, pero hace que el proceso de cargado de partida sea más sencillo, se puede guardar?

**Comment by lily416** [comment]
@Pabloinz sí, puedes agregar al archivo todo lo que encuentres necesario y/o que facilite la carga del archivo. 😄 

Saludos y éxito con la tarea 👋 💪
