### ISSUE TITLE
Poblacion inicial planetas

### ISSUE THREAD

**Issue by alfa-labarca** [IIC2233/Syllabus#25]
En el enunciado de la tarea, dice que al crear una nueva galaxia, los planetas deberán ser poblados con el 75% de su población máxima.
Esto debe ser con soldados, a pesar de que el planeta no tenga cuartel?

**Comment by maguerrap** [comment]
Además, sale que un planeta nace por defecto con 0 soldados y 0 magos (sección 5.2)

**Comment by ptflores1** [comment]
@maguerrap Los planetas siguen naciendo por defecto con 0 soldados y 0 magos, esto no afecta a lo que se dice en 6.1:

> ... Todos los demas deberan ser poblados con el 75 % de su poblacion maxima.

porque son poblados despues de su creacion.

@alfa-labarca No importa que no hayan cuarteles al momento de poblar de esta manera los planetas. Los cuarteles son importantes cuando el usuario juega con la galaxia para poder crear sus propios soldados y/o magos (en el caso correspondiente). Por este motivo dejamos a su criterio si crean o no un cuartel para los planetas al poblarlos segun lo que se dice en 6.1.

**Comment by jeschuwirth** [comment]
que hacemos en el caso de los aprendices que tienen una población máxima de 150 unidades y, por lo tanto no poseen un 75% exacto, ¿lo dejamos a nuestro criterio?

**Comment by ptflores1** [comment]
Sii!

**Comment by mramirez7** [comment]
Hola, en el caso de que la raza del planeta sea Maestro, el 75% de población se distribuye de alguna manera en particular entre soldados y magos?

**Comment by Unknomads** [comment]
Hola. ¿El planeta que se conquista también se debe dejar con un 75% de su población maxima o con 0?

**Comment by Hernan4444** [comment]
#54
