### ISSUE TITLE
Duplicar carpeta clonada de Git

### ISSUE THREAD

**Issue by pedroriosg** [IIC2233/syllabus#25]
Hola! Quería saber si al duplicar (en el Escritorio) una carpeta clonada de Git, la carpeta duplicada queda "anclada" a Git? o adquiere las mismas funcionalidades que la original?

**Comment by furcelay** [comment]
Hola!
¿Cuando dices duplicar quieres decir copy-paste? 
Tu repositorio local tiene una carpeta (oculta) `.git` que es la que la identifica como repositorio git y mientras exista puedes usar los comandos git sin problemas, así que si copias y pegas todo el directorio de Git debería funcionar (ambas copias podrán sincronizarse con el repositorio en la nube).

Sin embargo **copy-paste no es la forma recomendada**, **lo mejor es clonar nuevamente el repositorio** (comando `git clone ...`), podrás usar ambas copias sin problemas.
Saludos!
