### ISSUE TITLE
Duda función plantar

### ISSUE THREAD

**Issue by xperseosses** [IIC2233/Syllabus#25]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Quiero programar la función plantar de manera que retorne un bool, sin embargo cuando lo hago, el test case arroja que True is not None (evidentemente), ¿Esto tiene efectos en la revisión de la Tarea?.

**Comment by SSParzival** [comment]
Hola buenas, lo que comentas sí tiene efecto en la revisión de la tarea, debido a que la parte de los tests es automáticamente corregida, así que el fallar los tests de cualquier modo tiene incidencia negativa en tu nota.

Sin embargo, lo que podrías hacer es crear una función auxiliar extra que haga lo que desees, y así no tendrías problema con pasar los tests.

Quedo atento a cualquier duda que te quede.
