### ISSUE TITLE
Duda Herencia atacar()

### ISSUE THREAD

**Issue by fmandiolafellay** [IIC2233/Syllabus#250]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Cuando por ejemplo se dice que el Paladín puede tener características de un Mago, se puede asumir que funcionará tal como un Mago? Osea que tendrá posibilidad de activar sus poderes y si no actuará como Guerrero.
Espero se entienda.

**Comment by fmandiolafellay** [comment]
(Me refería al Mago de Batalla no Paladín)

**Comment by Dominique236** [comment]
Hola @fmandiolafellay !

Si te refieres a que Mago de Batalla puede activar sus poderes de Mago y actuar como tal, la respuesta es si, y tal como mencionas, si esto no ocurre, es decir, no se cumple la probabilidad PROB_MDB %, este actuará como Guerrero.

Ojalá esto haya resuelto tu duda, de todas formas te recomiendo revisar issues sobre el tema ya resueltas, como la #171 o #248 :)

**Comment by fmandiolafellay** [comment]
Creo que me expliqué mal o no entendí tu respuesta jaja. Por ejemplo Mago de batalla tiene probabilidad de ser un Mago o de ser un Guerrero. El hecho de ser Mago implica que existe una posibilidad de activar tus poderes, o no. Entonces el Mago de Batalla al actuar como Mago, naturalmente también tiene posibilidad de que no se activen sus poderes. Puedo asumir todo lo anterior?

**Comment by Dominique236** [comment]
Ok, había entendido mal tu pregunta. Lo que dices es correcto, puedes asumir toda la secuencia que mencionas.
