### ISSUE TITLE
Duda sobre uso de clase abstracta en Tarea 2

### ISSUE THREAD

**Issue by matiasherrerar** [IIC2233/Syllabus#250]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola quería preguntar,  cómo es obligatorio utilizar clases abstractas en alguna parte de la tarea, para poder cumplir con esto, ¿podría definir una clase abstracta sin métodos abstractos? ¿o no tiene mucho sentido?

Esto ya que en los contenidos se dice que para que una clase sea abstracta debe tener al menos un método abstracto. Sin embargo la única posibilidad que veo de utilizar clase abstracta en la Tarea, ésta no necesitaría utilizar métodos abstractos.

**Comment by AndreaVict** [comment]
Holaa, la definición de clase abstracta para el curso indica que debe existir al menos un método abstracto dentro de ella. Por tanto  no es válido lo que mencionas. Debes encontrar una manera de incluir esta clase dentro del desarrollo de tu tarea. Mucho éxito :3

**Comment by mxmauoc0** [comment]
anidando mi pregunta a las clases abstractas
¿ @ABC es equivalente a @abstractmethod ?
