### ISSUE TITLE
Variables globales

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2233/syllabus#250]
Hola! 
Tengo claro que no se pueden usar variables globales, sin embargo me surge la duda de que se considera un variable global, ya que en mi código el número de barcos y radio lo importo de parametro.py y los defino al principio, esto hace que el parámetro número de barcos, por ejemplo, pueda entrar a mis clases y funciones sin llamarlo o ingresarlo como atributo. No estoy segura de si esto se considera una variable global o no y de ser así como puedo hacer para que deje de ser variable global ya que lo único que hice fue definirlo arriba al momento de importarlo. (podría llamarlo desde la función o clase sin embargo sería totalmente innecesario por que funciona sin eso)

**Comment by josefinareyes** [comment]
Hola, como estás importando parámetros, que son valores fijos para tu programa, no hay problema en que los guardes como  variables al principio y los uses como lo estás haciendo para el resto de tu programa. Lo que no está permitido es usar el comando ```global``` para definir variables globales, esto fue respondido más específicamente en [este comentario](https://github.com/IIC2233/syllabus/issues/87#issuecomment-680066131) :)
