### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by santiago3c** [IIC2233/Syllabus#250]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/Syllabus/issues/243)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](https://github.com/IIC2233/Syllabus/issues/241)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, que ¿en el gitignore se debe poner que se debe ignorar la carpeta test_publicos (en el enunciado hace mención a una carpeta llamada tests) , pero no hay que ignorar el archivo run_public_tests.py?
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by LudwigUC** [comment]
Hola! El enunciado señala ignorar la carpeta test, esta corresponde a `test_publicos`. En cuanto a el archivo `run_public_tests.py` puedes elegir agregarlo o no a tu gitignore, lo importante es **no ignorar los archivos vitales** es decir, aquellos que tu creaste y son necesarios para correr el programa. Saludos!

**Comment by santiago3c** [comment]
gracias
