### ISSUE TITLE
Color del primer turno

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2233/Syllabus#250]
Tengo dos dudas: - Al inicio del juego se debe poner una pieza, esta debe ser de algún color en específico o está la opción de que no tenga color.
- Debe haber alguna manera de elegir al color que empieza o podemos asumir que siempre empieza uno, por ejemplo, el azul siempre empieza

**Comment by iqacevedo** [comment]
Hola, 

Ninguna de tus preguntas está explícita en el enunciado, así que puedes usar tu criterio y hacerlo como te parezca conveniente. Recuerda especificar en el README tus decisiones.

Saludos !

**Comment by josefinabengoa** [comment]
¿Como puedo saber el tipo (si es CCCGCC, o GGCCCC, etc) de la primera ficha que sale al azar? Para guardarla, y asi ver dónde es válido poner la siguiente ficha y las otras.

**Comment by iqacevedo** [comment]
@josefinabengoa eso es parte de las cosas que ustedes deben resolver. Así que mucho animo, se que lo pueden resolver !!!!

Saludos !
