### ISSUE TITLE
Felicidad perdida en los excavadores derrumbe

### ISSUE THREAD

**Issue by cataguzmanw** [IIC2233/Syllabus#250]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### La felicidad que pierde el equipo con un derrumbe corresponde a la suma de las felicidades que pierde cada excavador que no se encuentra descansando? O los que estan descansando tambien pierden?

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mtaguero** [comment]
¡Hola @cataguzmanw!

El enunciado dice:

> Es necesario tener en cuenta que cada evento adverso genera infelicidad a tus excavadores. Por
lo tanto, cada excavador pierde FELICIDAD_PERDIDA unidades de felicidad luego de que ocurra
cualquier evento.

Esto quiere decir que cuando ocurre un derrumbe, entonces hay un parámetro con determinado valor que se le resta a cada excavador.  Notar que el enunciado dice que **CADA EXCAVADOR** pierde felicidad. De todas formas, siempre puedes hacer algunos supuestos para desarrollar tu código. Mientras estos tengan sentido y no contradigan directamente el enunciado, se evaluará tu código considerando aquellos supuestos mencionados en tu readme.

¡Éxito! 🎈
