### ISSUE TITLE
Contradiccion enunciado

### ISSUE THREAD

**Issue by sebamoreno2811** [IIC2233/syllabus#250]
En el enunciado se dice que los barcos cargueros solo llevan mercancia pero en el .csv tienen pasajeros asignados, entonces esos pasajeros se utilizan en los calculos o se deben considerar como 0?

**Comment by Emiliax16** [comment]
Efectivamente el barco carguero puede llevar pasajeros. En la parte 3.1 se indica que todo barco puede llevar pasajeros, quédate con esa condición! c:
