### ISSUE TITLE
Respeto de mayusculas y minúsculas

### ISSUE THREAD

**Issue by maormeno** [IIC2233/syllabus#250]
En el enunciado dice que deberemos respetar el uso de mayusculas y minúsculas al guardar partida... Eso significa que no debemos aceptar nombres de pilotos o vehículos cuyas palabras no empiecen con mayuscula ("auto rojo" estaría mal y solo se debería aceptar "Auto Rojo")? O significa que se pueden diferenciar por las mayusculas ("AUTO rojo" distinto de "Auto ROJO").
Gracias!

**Comment by gatochico** [comment]
Hola! Con esto nos referimos al segundo caso que propones: Debes guardar los nombres tal como se escribieron por el usuario (Ej: "AuTiTo" debe guardarse como tal, y no como "autito"). :nerd_face: Éxito con la tarea!
