### ISSUE TITLE
Duda respecto al comportamiento tras cerrar distintas ventanas

### ISSUE THREAD

**Issue by EnzoMorata** [IIC2233/Syllabus#250]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola mi duda es respecto a que se debería esperar tras cerrar ciertas ventanas en el programa. Me surgio esta duda, ya que concretamente en el enunciado para la ventana de ranking se esperar que tras cerrar la ventana se vuelva a la ventana de inicio. Pero, en el resto de ventanas (Ventana de juego y Ventana Post-Nivel) no se detalla un comportamiento en específico, entonces quería saber si **esto podría quedar a nuestro criterio o si directamente sería preferible terminar con el programa** por defecto.

**Comment by rodrigobj99** [comment]
Hola @EnzoMorata ! Dado que el enunciado no especifica que hacer en esos casos, queda a tu criterio el como manejarlos. Saludos!

**Comment by EnzoMorata** [comment]
Ya, muchas gracias!
