### ISSUE TITLE
Tarea 02: métodos magicos

### ISSUE THREAD

**Issue by AmbrosioV** [IIC2233/Syllabus#250]
En el punto 5 del enunciado se especifica que se deben implementar varios métodos especiales para las estructuras de datos que definamos, pero si hay alguno que nunca uso a lo largo de mi tarea ¿esto es necesario? por ejemplo, nunca utilizo `__delitem__` ni `sort`.
 Además mi lista ligada no tiene ni `__next__` ni `__iter__` (es del código que se podía sacar de una ayudantía). 
Es necesario implementar cada uno de los métodos o no?

**Comment by Hernan4444** [comment]
#166 
Saludos!

**Comment by AmbrosioV** [comment]
A pesar de nunca usarlos? si es asi hago una clase aparte y defino los métodos para que no estorben con lo que ya tengo

**Comment by Hernan4444** [comment]
Tienes que crear una edd con esos métodos y por lo tanto la clase que crees, aunque sea externa, debe comportarse cómo una estructura de datos.  Su mala implantación será considerado al momento de evaluar. 

PD: si creas una issue duplica3 y se te indica la otra issue donde se habla de eso, por favor continuar con las preguntas ahí,  solo por esta vez se contestó esta issue pero no será así para la próxima. 

Saludos
