### ISSUE TITLE
Contagio entre paises

### ISSUE THREAD

**Issue by ofvera** [IIC2233/Syllabus#251]
Me hace ruido que el numero de conexiones disminuya la probabilidad de contagio. No es más probable contagiarse si llega gente de todos lados?
Esto lo pregunto por otra duda que surge y es que para los vuelos la probabilidad de contagio es tan baja que no se alcanza a propagarse en lo absoluto. Quizás nisiquiera considerando lo dicho anteriormente se propagaría, ya que recién multiplicando la probabilidad por 100 parece ser levemente relevante su contagio.
Asumimos que es muy difícil su expansión y por ende ganar el juego? O podemos ajustar y justificar la interpretación de la probabilidad, como por ejemplo, multiplicar directamente la probabilidad por la población viva del destino, y así generar un crecimiento más constante?

**Comment by Hernan4444** [comment]
@ofvera Si puedes pero no olvides especificar en tu Readme cual fue tu cambio y porqué consideras que ese cambio es el indicado

Saludos!
