### ISSUE TITLE
Tuplas

### ISSUE THREAD

**Issue by atbusch** [IIC2233/Syllabus#251]
Tengo 2 dudas respecto a las tuplas:
1. En demo.py se entregan los equipos en una lista con tuplas, por lo tanto estoy obligado a crear una estructura de datos de tuplas?
2. Puedo hacer un método que retorne mas de un valor? Porque esos valores también quedan guardados en una tupla
Gracias!

**Comment by IchottMano** [comment]
@atbusch Hola!

Si haces un método que retorne mas de un valor, este va a retornar una tupla, en ese caso lo que debes hacer es desempaquetar la tupla en cuestión en una de tus estructuras de datos.

Queda a tu creiterio si creae una estructura de datos que simule a las tuplas.

Saludos!
