### ISSUE TITLE
Duda de cuando barcos encallan

### ISSUE THREAD

**Issue by gonzaga2000** [IIC2233/syllabus#251]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Tengo dudas sobre que pasa cuando un barco encalla, en primer lugar, cuando simulo una nueva hora e ingreso un nuevo barco, debo calcular inmediatamente si el barco encalla o no. En el caso de que ese barco recién ingresado encalle, en que posicion en el canal quedara encallado, en el origen del canal? o encallara despues de haber avanzado y debido a esto quedaria encallado en "distancia_avanzada".

Lo segundo, cada vez que simulo una nueva hora, tengo que revisar si cada barco que este actualmente en el canal encalla, en el caso de que encallen, en que posicion lo haran? en la poscion que avanzaron en el turno anterior? o incluyendo lo que avanzarian en el turno actual?

**Comment by santiagovegaf** [comment]
Hola @gonzaga2000!

Esta parte del flujo se menciona en el punto 4.3.2 del enunciado.
![image_2021-04-19_102804](https://user-images.githubusercontent.com/57118271/115252939-ebe6bb80-a0f9-11eb-95c7-0d00ea64dc02.png)

 Espero que te pueda ayudar y quedo atento a cualquier duda!

**Comment by BValdes16** [comment]
Tengo la misma duda que mi compañero. Lo que me enreda es que en esa parte se dice eso, pero antes se dice:

4.2.2. Desencallar Barco
Si se elige esto, se desplegaran en la consola un listado de todos los barcos que actualmente se encuentren
encallados y se dará la opción de seleccionar uno. Se deberá primero verificar que se tengan suficientes
fondos y en caso de no poseerlos, se deberá impedir la acción.

EL problema es que según 4.3.2, nunca va a haber más de un barco encallado, por lo que no tiene sentido el menú  Desencallar barcos.

**Comment by gonzaga2000** [comment]
Eso mismo! como que esos dos puntos se contradicen

**Comment by BValdes16** [comment]
También en mostrar riesgo de encallamiento se debe mostrar la probabilidad de los barcos que están dentro del canal, lo cual tampoco tiene sentido si solo se encalla al principio

**Comment by santiagovegaf** [comment]
Hola, 
Respondiendo a la duda inicial, se verifica que si los barcos encallaron primero y luego avanzan (lo que no es posible si este se atasca, es decir, no avanza en ese caso). Esto ocurre con todos los barcos en cada simulación, por lo que un basco se puede quedar pegado en cualquier parte del canal.  

Lo que nos dice el menú de simulaciones es que al canal pueden ingresar barcos siempre y cuando el canal esté desbloqueado (similar al canal de Suez real, donde al encallar el Ever Given, dejaron de entrar nuevas naves). Esto permite que varios botes circulen simultáneamente, abriendo la posibilidad a que uno o más se atasquen. 

Aquí es donde entra en juego la opción de desencallar del menú, ya que en el caso de estar dos barcos atascados, puedes elegir a cual intentar de liberar primero. Por ejemplo, una estrategia puede ser intentar desencallar el barco que está más adelante, para que los de atrás puedan seguir avanzando,  o intentar con el que sea más barato, esto queda en manos del usuario. 
Importante destacar que la opción desencallar del menú no es parte de la simulación, sino que ocurre entre dos horas distintas, y se podría entender que ocurre de manera instantánea. Permitiendo que en la siguiente simulación de hora puedan entrar nuevos barcos si todo sale bien. 

Finalmente, sobre la opción de ver el riesgo de encallamiento, esta función es útil para el usuario ya que como los barcos se pueden atascar en cualquier punto, esta información puede ayudar a tomar decisiones. Por ejemplo, si ya están circulando muchos botes por el canal y tienen una alta probabilidad de encallar, tal vez no sea conveniente seguir enviando barcos el próximo turno.

La respuesta esta un poco extensa :open_mouth:, espero se entienda bien. quedo atento a cualquir cosa!

**Comment by gonzaga2000** [comment]
Entonces, lo que entiendo es que encallar es al inicio de la simulación, es decir primero verifico si el barco encalla, y luego en caso de no encallar este puede avanzar. 

Por otro lado en el caso de que haya un barco encallado, los barcos detrás de este podrán avanzar hasta la posición del barco encallado. Esto significa que si hay un barco encallado en el canal, no podrán entrar nuevos barcos, pero los que ya encuentren en el canal podrán avanzar hasta ciertos puntos (donde se encuentran barcos encallados).

Podrías confirmar que es así? de antemano gracias!

**Comment by santiagovegaf** [comment]
Exactamente! :tada:

**Comment by santiagovegaf** [comment]
El orden entregado es: Revisar encallamiento -> Evento especial -> Avanzar, lo que se repite para cada barco todas las horas hasta que salen del canal, siempre y cuando no encalle! 

![image_2021-04-19_142451](https://user-images.githubusercontent.com/57118271/115284696-00877b80-a11b-11eb-9d30-e93656fed552.png)

**Comment by magdalenanario** [comment]
Hola! Tengo una duda con esto mismo! Entiendo que si un barco encalla, en esa misma hora, los demás pueden avanzar hasta la posición del barco encallado. Pero en el caso de que, antes de partir una nueva simulación, haya un barco encallado, ¿Los demás barcos que están dentro del canal pueden avanzar? ¿o simplemente no podrían porque el barco encallado impide la simulación de hora?

**Comment by santiagovegaf** [comment]
Hola, en #373 esta la respuesta!
