### ISSUE TITLE
Consulta sobre máximo de lineas de código

### ISSUE THREAD

**Issue by TomasRiquelme** [IIC2233/Syllabus#251]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Buen dia! Me preguntaba si es que hay un máximo de lineas de código totales para esta tarea, pues entré al territorio de tener poco más de 400 lineas entre los módulos que cree. De ser el caso, cual es la penalizacion para quienes superan esa cantidad de lineas? muchas gracias
[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by blampasona18** [comment]
> Hola @TomasRiquelme !
> 
> No hay un máximo de líneas para la tarea. Lo que sí tiene descuento es superar en uno o más módulos las 400 líneas, a lo que le corresponde una penalización de 5 décimas (Distribución de puntajes T1). Si entre todos tus módulos sumas más de 400 líneas de código no hay problema, siempre y cuando cada uno cumpla con la cantidad de líneas máxima.
> 
> Espero haya quedado claro, quedo atento.

Hola, para esta tarea existe la opción de no hacer esta penalización o dar más flexibilidad con las líneas? Al haber tantas properties hay muchas líneas que obligatoriamente se tienen que poner. Además, al intentar hacer las clases en distintos módulos, me tira error de "importación circular", ya que las clases se deben llamar entre ellas.
Espero la respuesta!
