### ISSUE TITLE
Validar dirección de casilla "Entrada"

### ISSUE THREAD

**Issue by jcdo** [IIC2233/Syllabus#251]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](https://github.com/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Para la función **validar_direccion** existen tests para verificar la salida del laberinto como una dirección valida, pero no la entrada. Entiendo que el mapa en todo el borde son paredes menos la entrada, por lo que me hace creer que esa sería una direccion no valida (*al menos para moverse ya que el conejo luego hace respawn ahí*) pero esto nunca se especifica.

**¿Es la casilla de entrada una dirección valida?**

**Comment by LudwigUC** [comment]
Efectivamente, en ese caso sería una dirección no válida, pues conejochico no puede avanzar más allá del límite del mapa, dado en este caso por la entrada, pues no hay más casillas.

**Comment by bea-or** [comment]
Hola, no me quedo claro. ¿No es valido que el conejo se mueva a la casilla de entrada?

Por ejemplo, si tengo el siguiente tablero (reducido):
P P P P
P -  - S
E C - P
P P P P 
y el conejo se quiere mover hacia la izquierda (tecla S) donde esta la entrada, esto no es valido?

**Comment by LudwigUC** [comment]
Hola, si es válido que el conejo se mueva a la casilla de entrada.
Lo que no es válido por ejemplo, es que quiera moverse a la izquierda en la siguiente situación:
P P P P
P - - S
C - - P
P P P P

**Comment by jcdo** [comment]
> Hola, si es válido que el conejo se mueva a la casilla de entrada. Lo que no es válido por ejemplo, es que quiera moverse a la izquierda en la siguiente situación: P P P P P - - S C - - P P P P P

Creo que mi pregunta original no se entendio. Con esto queda mas claro, gracias!
