### ISSUE TITLE
Añadir Qrect a Qgridlayout

### ISSUE THREAD

**Issue by cambrinKD** [IIC2233/syllabus#251]
Hay una manera de hacer esto?

Estoy empezando a pensar que usar Qgridlayout no fue una buena idea

**Comment by Hernan4444** [comment]
Hola,

Si hay maneras, pero creo que no directas. Si recuerdo bien, cuando intenté hacer eso, puse un QLabel dentro del `Qgridlayout` y a los `QLabel` les ponía un `QPixmap`. Finalmente usaba el método `frameGeometry()` para obtener el `QRect`. De este modo, accedía al `QRect` del `QLabel` que estaba dentro del `Qgridlayout`. Te recomiendo buscar sobre esos objetos que puse y el método descrito c:

Saludos ✌️
