### ISSUE TITLE
Duda sobre el descarte de líneas en plantas.txt

### ISSUE THREAD

**Issue by TarzanDeMaceta** [IIC2233/Syllabus#251]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. En mi código, para descartar las estadísticas incorrectas en el archivo "plantas.txt" asumí que siempre habrá la misma cantidad de datos en el orden que se encuentran en el enunciado, y para descartar cree dos listas con los valores extremos y una lista auxiliar con los índices que me interesa comparar, esto lo hice para no tener que hacer una cadena de if / elif, **quería preguntar si esto corresponde a hard-coding o no**.

Le pregunte a un ayudante y me recomendó hacer una issue al respecto.

**Comment by rodrigoaguilera15** [comment]
Hola. Será hard-coding si tienes los valores de la lista definidos dentro del mismo archivo en que estás haciendo el descarte. Lo mejor sería tener esos valores, o las listas completas, dentro de parámetros. Parámetros no necesariamente tiene que ser solo variables int o float, pueden haber diccionarios, listas, etc. Quedo atento.

**Comment by TarzanDeMaceta** [comment]
Vale gracias
