### ISSUE TITLE
Cálculo de puntajes en T00

### ISSUE THREAD

**Issue by martin-iturralde** [IIC2233/syllabus#251]
Hola, estaba viendo el enunciado de la tarea y el cálculo que decia que se usaba era:
max (0,(filas × columnas × NUM_BARCOS × (enemigos_descubiertos − aliados_descubiertos))) 
Ahora mi pregunta, esta función se deja así nomás? Es decir, no es necesario sacarle el max o el 0 que viene antes de las variables?
Gracias de antemano!

**Comment by josefinareyes** [comment]
Hola! Esa función ```max()``` retorna el máximo valor entre los parámetros que le entregues, por lo que el 0 indica que no puede retornar un valor negativo, y el máximo está dado por la multiplicación del paréntesis, así que la tienes que dejar tal como está en el enunciado! 😃

**Comment by martin-iturralde** [comment]
Gracias! Te pasaste
