### ISSUE TITLE
Vehiculo de contrincantes en la carrera

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2233/syllabus#251]
hola tengo una duda, como entiendo, tengo que calcular las velocidades, hipotermia y ademases para todos los competidores en la carrera, y el calculo de "dificultad_control" depende del vehículo que se usa, entonces como se que vehículo usara cada contrincante ?, o debo escoger al azar en caso de que posea mas de uno ?.

De antemano, muchas gracias.

**Comment by gatochico** [comment]
Hola! Tal como dice la issue #141 , queda a tu criterio el cómo los contrincantes eligen sus vehículos (puedes asumir que siempre tendran por lo menos 1).
Saludos!!
