### ISSUE TITLE
Duda  si es que hay que agregar menús

### ISSUE THREAD

**Issue by Nicolemarin** [IIC2233/syllabus#252]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Canales realiza la accion "Ingresar barco al canal". Mi duda es cuándo y dónde debería accionarse éste, debido a que en los Menús que nos piden, no existe un menú que pida  "Ingresar barco al canal".

Dónde deberíamos pedirle al usuario que ingrese un barco? Lo mismo me pasa con otras acciones ej: Avanzar barcos.
Tendría que agregar otro menú? en qué parte?

Gracias

**Comment by Emiliax16** [comment]
Hola! respecto a la acción "ingresar barco al canal", en el menú acciones está la opción de simular nueva hora, ahí debes incluir la acción de ingresar barcos (en caso de que no haya ninguno atascado). Lo mismo ocurre con la acción "Avanzar barcos", el cual debe accionarse si efectivamente puede ingresar un barco. Recuerda que no todos los métodos de las entidades deben estar en el menú, si no que deben ser el funcionamiento de las opciones de este!

**Comment by Nicolemarin** [comment]
Pero me queda las siguientes dudas:
1. Al comenzar el programa, los canales están con **cero** barcos en su interior? o sea para que un barco entre a un canal tengo que si o sí haber selecciono "simular hora"?
2. entran **automáticamente**? uno tras otro?
3. en que **orden** deben entrar los barcos cuando "simulo hora"?

**Comment by Emiliax16** [comment]
1. Exacto. Entrará sólo 1 barco por hora simulada. Si nunca simulas una hora, asume que no ha entrado ningún barco al canal.
2. Cada vez que se simula una hora, puede entrar **sólo** un barco.
3. Como entra un barco por hora simulada, el barco ingresado se posicionará automáticamente de los últimos en el canal.
Avísame si quedó más claro !
