### ISSUE TITLE
Reemplazar diagrama de clases por el final

### ISSUE THREAD

**Issue by pulpaulaa** [IIC2233/Syllabus#252]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Tengo la duda de si hay que reemplazar el diagrama de clases que se entregó como avance por el diagrama de clases final, o si hay que subirlo aparte en el repositorio.

Gracias.

**Comment by Benjeeeh** [comment]
Hola!
Te recomiendo reemplazarlo para evitar confusiones en la corrección de esta. En el caso de que subas dos archivos distintos, asegúrate de mencionar en el README el archivo a revisar, aunque en cualquiera de los dos casos es importante mencionar el directorio en que se encuentra tu diagrama de clases y el nombre de este archivo.

Éxito en la tarea!

**Comment by pulpaulaa** [comment]
@Benjeeeh Gracias! Ah y otras pregunta sobre el diagrama de clases, noté que en el enunciado sale que no es necesaria la cardinalidad ni la visibilidad de los atributos y métodos, pero en el feedback de los avances dice deberíamos mostrar que hay properties, y que eso lo hagamos con el - antes del atributo, que entiendo que es visibilidad, y solo dice que no es necesaria la cardinalidad. ¿Entonces la visibilidad es necesaria o no es necesaria?

**Comment by Benjeeeh** [comment]
@pulpaulaa 
No es necesaria la cardinalidad ni la visibilidad de los atributos, esto refiriéndose a los números en cada relación ni que se deben agregar los underscores (__energia, por ejemplo). No confundir los underscores con una forma que se puede presentar una property, que se basa en decir `- nombre_property: tipo_atributo`, que es lo contrario al + que se usa usualmente. 
Te recomiendo revisar el anuncio en canvas relacionado al feedback de la tarea, especificamente en la parte de como implementar las properties, que lo adjunto ahora:
![image](https://user-images.githubusercontent.com/78326186/234093537-fa8e8e39-0cd0-4004-a3d6-00d15586a487.png)

Cualquier duda me avisas!

**Comment by pulpaulaa** [comment]
@Benjeeeh Sí lo revisé, pero entonces quizás entendí mal, porque yo pensaba que la visibilidad es el + o - que se coloca antes del atributo, entonces como dijeron que no era necesaria la visibilidad pensé que no era necesario colocar un signo. Entonces, para indicar que es una property basta con poner un "-" antes de la property, como hiciste recién? Es decir, en ese caso no sería necesario indicar el getter y setter? Porque no sé cuál de las dos formas que salen en el anuncio de canvas es mejor para la tarea, y no sé en qué basarme para tomar esa decisión.

**Comment by Benjeeeh** [comment]
@pulpaulaa 
Si, la visibilidad no se relaciona con el signo antes de mencionar cada atributo, si no directamente a la privacidad si es que hay en tu código. Por ejemplo, si tienes una property y decidiste poner el atributo fuerza como atributo privado (__fuerza), no es necesario ponerle los underscores, si no que solo nombrarlo como fuerza. Personalmente, te recomiendo utilizar la forma que contempla los <>, ya que es más específico y menciona si es getter o setter, en cambio la otra forma es general y solo dice el nombre de la property.

**Comment by pulpaulaa** [comment]
@Benjeeeh Muchas gracias por aclararlo y la recomendación. En el caso de la forma con <>, sería solo una línea en la parte de los atributos como por ejemplo `+ <get/set> fuerza: int`? O se debe separar el get y el set en dos atributos/métodos distintos? Perdón por preguntar tanto pero quiero estar segura.

**Comment by Benjeeeh** [comment]
@pulpaulaa 
Tranqui! pregunta todo lo que quieras. Según lo que tengo entendido, la manera convencional debe ser separado, es decir, una línea por cada get y una línea por cada set, es decir:
`<get> fuerza: int`
`<set> fuerza: int`
Si bien puede ser tedioso, también puedes agregar la convención <get/set> como tu lo ejemplificaste, para indicar que el método tiene los dos tipos y así también reducir estas repeticiones, pero esto debes explicarlo en tu README de diagrama de clases para explicar el por qué de esto y así también no te quede un diagrama gigante tampoco, lo cual es entendible.
