### ISSUE TITLE
Contenido parametros.py

### ISSUE THREAD

**Issue by SebaZegers** [IIC2233/Syllabus#252]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Puedo definir las plantas y las clases en el archivo de parametros.py? O Tengo que crear un nuevo archivo especial para definir las clases?

**Comment by augustayanez** [comment]
El archivo parametros.py es exclusivamente para los parámetros que se mantendrán un valor constante durante todo tu programa (como los declarados en ESTE_FORMATO en el enunciado), parámetros que dependen de otros parámetros constantes y paths. Para definir clases u otras variables cuyo valor no será constante, tiene que ser en otro archivo.
