### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by cambrinKD** [IIC2233/syllabus#252]
Es necesario usar esto para el avance? Por que creen que es una buena idea añadir tanto contenido???

**Comment by KnowYourselves** [comment]
Hola @cambrinKD!

No es necesario el uso de `.gitignore` para el avance, pero si será necesario para la entrega final de la tarea. Respecto a lo segundo, si tienes algún reclamo, puedes enviarlo al mail de ayudantes que puede ser encontrado en la [página del curso](https://iic2233.github.io/contacto/), debido a que el foro no es medio de reclamos.

Espero haberte ayudado!

**Comment by constanzacontreras** [comment]
Hola!! Aprovechando esta pregunta, ¿Debemos subir la carpeta completa? ¿O solo los archivos python creados ahora?
Muchas graciass!!

**Comment by KnowYourselves** [comment]
Hola @constanzacontreras!

Por tema de orden de sus repos, es preferible que suban el avance dentro de su propia carpeta.
