### ISSUE TITLE
Consulta sobre el cambio de nombre de la carpeta

### ISSUE THREAD

**Issue by karlamunoz14** [IIC2233/Syllabus#252]
Al decir que se cambiara el nombre de la carpeta, debemos hacer un cambio en nuestros paths o si los dejo dentro de la carpeta es suficiente? no me quedo muy claro
Muchas gracias

**Comment by Hernan4444** [comment]
Hola @karlamunoz14 


Si los paths están definidos para funcionar desde dentro de tu carpeta T2, entonces no habrá ningún problema. Solo si alguien hace algo como

* "repositorio/Tareas/T2/...."
* "Tareas/T2/...."
* "T2/...."

Tendrá problemas de corrección por los paths. Por ejemplo, puedes revisar la solución de la experiencia 2 y 3, que si cambias el nombre de la carpeta "solución" por cualquier otro nombre, el código igual funcionará porque todos los paths fueron pensados asumiendo que tu consola está posicionada dentro de dicha carpta y hará "python3 main.py" por lo tanto, no afecta en nada si esa carpeta se llamaba "solution", "EX", "UWU", etc.

Saludos!
