### ISSUE TITLE
Estructuras de datos uso de atributos en diccionario propio T02

### ISSUE THREAD

**Issue by FJavierOss** [IIC2233/Syllabus#252]
Queria saber si es "legal" ocupar los atributos de un objeto para formar un diccionario propio para la tarea. Le pregunte a un ayudante que no era de tarea y me respondio que probablemente no fuera legal dado la tarea, pero no me lo podia asegurar. Basicamente cada atributo seria un "key" del diccionario en cuestión, y los obtengo o los remuevo o los cambio según se pida y logra todas las funcionalidades correspondientes. Necesito conocer si es legal o no para ver si tengo que borrar mi diccionario o no :C

**Comment by IchottMano** [comment]
@FJavierOss Hola!

Lamentablemente segun lo que me dices es ilegal lo que estás haciendo, ya que técnicamente los atributos son un diccionario, por lo que estarías manipulando un diccionario y por lo tanto una estructura prohibida.

Saludos y éxito con la tarea!

**Comment by contranton** [comment]
Para aclarar, esto quiere decir que el uso de `getattr` y `setattr` esta prohibido para las implementaciones propias?

**Comment by IchottMano** [comment]
@contranton Hola!
Puedes usar getattr, pero el uso de setattr está prohibido ya que lo que have este método usa diccionarios.
Saludos!
