### ISSUE TITLE
Variables random en parametros.py 

### ISSUE THREAD

**Issue by mpenalozag** [IIC2233/syllabus#252]
Hola, es posible tener variables que utilicen módulos como por ejemplo "random"?

**Comment by moquezada** [comment]
Hola @mpenalozag!

En el enunciado, precisamente en las notas al pie de páginas de las páginas 7 y 9, se recomienda utilizar ciertas funciones de la librería `random` para lograr definir ciertos atributos y la ocurrencia de ciertos eventos.  Por lo tanto, sí es posible tener variables o atributos que utilicen dicho módulo.

Recuerda que además de estar especificado en el enunciado el uso de esta librería, existe la issue de librerías permitidas y no permitidas #240 😄 

Espero haberte ayudado :)

**Comment by jeschuwirth** [comment]
Hola @mpenalozag,

Agregando a lo que dijo @moquezada, ten mucho cuidado al importar parámetros creados con la librería random. Si tienes por ejemplo el parámetro:

RESULTADODADO = random.randint(1,6)

y luego en tu código haces por ejemplo:

```
valor anterior = RESULTADODADO
while valor anterior == RESULTADODADO:
    valor anterior = RESULTADODADO
```
nunca vas a salir del loop, ya que al definir RESULTADODADO este va a ser un valor random de 1 a 6 y **no** va a cambiar durante la ejecución de tu código.

**Comment by mpenalozag** [comment]
Gracias !
