### ISSUE TITLE
Confusión haciendo gui.run()

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233/Syllabus#252]
Hola!
Estoy un poco confundido; si deseo hacer una clase (llamemosla hipotéticamente ControlJuego) que a través de la modelación de los turnos (del juego en realidad en general) vaya ocupando métodos de la clase MyInterface, ¿cómo puedo realmente modularizarlo? Si pienso en crear un objeto MyInterface que pase como atributo de mi clase ControlJuego, ¿cuál sería la forma correcta de hacer gui.run()?

Será que tendría que hacer algo así como:

```
if __name__ == '__main__':
    def hook(type, value, traceback):
        print(type)
        print(value)
        print(traceback)

    sys.__excepthook__ = hook

    gui.set_scale(False)  # Any float different from 0
    gui.init()
    gui.set_quality("ultra")  # low, medium, high ultra
    gui.set_animations(False)
    gui.init_grid()
    gui.set_game_interface(ControlJuego.MyInterface())  # GUI Listener
    gui.run()
```

**Comment by iqacevedo** [comment]
Hola,

En teoría debería funcionar lo que planteas, recuerda eso si que el objeto que tengas que sea del tipo MyInterface debe tener definidos todos los métodos que aparecen en demo.py, ya que ellos van a ser llamados cuando se interactúa con la interfaz. Un detalle importante, el ideal es que MyInterfaz sea instanciada después de la línea que dice `gui.init_grid()`, ya que en eso momento ya está cargada la interfaz y lista para recibir órdenes desde donde quieras! (Aunque se verá realmente cuando se ejecute `gui.run()`).

En cuanto a cuando hacer gui.run(), escríbelo al final, tal cómo está en demo.py,  ya que ahí se quedará el programa mientras se interactúa con la interfaz (es decir ,no se va a correr ninguna línea que este después, hasta que se cierre la interfaz).

Saludos !
