### ISSUE TITLE
Maneras de importar módulos

### ISSUE THREAD

**Issue by amorande1** [IIC2233/syllabus#252]
Hola! Necesito ayuda para saber porqué al importar un módulo como: "_import Tarea_00_funciones_", 
o bien como: "_import tablero_". Obtengo el siguiente error:  "_NameError: name '<Nombre función>' is not defined_".
Sin embargo, cuando las llamo como: "_from Tarea_00_funciones import matriz_", 
o bien como: "_from tablero import print_tablero_" sí se importan correctamente.
__

**Comment by jitorcas** [comment]
Hola! @amorande1 

Puedes utilizar dos maneras para importar módulos a tu código, que te describiré a continuación:

**Utilizando únicamente la sentencia 'import'**
Mediante esta manera traes todo el módulo a tu código, y la sintaxis que debes utilizar es la siguiente:

```python
import mimodulo

mimodulo.funcion()
```

deberás anteponer el nombre del módulo en cada atributo que deseas utilizar, sin embargo, para evitar tener que escribir el nombre del módulo tantas veces, podrías asignarle un alias de la siguiente manera:

```python
import mimodulo as m

m.funcion()
```

**Utilizando la sentencia 'from'**

Mediante esta sentencia cargas solo los atributos especificados. La sintaxis es la siguiente: 

```python
from mimodulo import funcion1, funcion2

funcion1()
funcion2()
```
👀  Hay una manera de poder importar todo sin especificar, pero es una **mala práctica** tal como se especificó en la issue #175 

Con respecto a tu problema en particular, es probable que te haya faltado anteponer el nombre de tu módulo en las funciones que utilizaste. 

Si no fui claro, puedes volver a preguntar!
Éxito en tu tarea! 💯
