### ISSUE TITLE
math.ceiling

### ISSUE THREAD

**Issue by norman123123** [IIC2233/Syllabus#252]
Necesito la funcion techo (math.ceil), esto lo puedo usar?
es porque me sale que tengo "gente y media" contagiada y quiero aproximar para arriba.

**Comment by akaminetzkyp** [comment]
Podrías usar int() y sumarle uno también.

**Comment by norman123123** [comment]
cool

**Comment by IriSalazar** [comment]
si se puede! esta en la issue #141 bien abajo... aplica ctrl+F math si queres buscarlo jajaa

**Comment by Dunkan1** [comment]
o podrias dividir por parte entera  numero_float//1

**Comment by nivek0o0** [comment]
o puedes usar round(x, 0)

**Comment by sebacruzd** [comment]
Esto se pregunta en el issue de librerías permitidas/ prohibidas
