### ISSUE TITLE
Requisitos de la interfaz del juego

### ISSUE THREAD

**Issue by ElTioAndresCabezas** [IIC2233/Syllabus#252]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Saludos!
En el enunciado de la tarea, colocan esta imagen como referencia de como se debería ver la ventana del juego
https://prnt.sc/1ysx8e7

Si prefiero, en lugar de añadir una barra de información grande, tal como muestran en el ejemplo, prefiero dejar la información solicitada de forma superpuesta (asi como se hace en otros videojuegos, para dejar más espacio de la pantalla para el juego), y colocar los botones de "Pausa" y "Salir" en otra esquina, ¿esta permitido?

**TL;DR: ¿Puedo tomar cierta libertad creativa para mostrar la información del juego, de una forma distinta a la mostrada?**

**Comment by catalinacarter** [comment]
Hola @ElTioAndresCabezas! Los ejemplos de ventanas expuestas son solo para que te hagas una idea de cómo se deberían ver :) **queda a tu criterio como implementarlas**, siempre y cuando pongas todo lo solicitado en el enunciado. En el caso de la ventana de juego, además del mapa,  debe estar presente como mínimo: vida actual del jugador, nivel actual, puntaje obtenido en el nivel, tiempo restante, cantidad de monedas atrapadas en total, botón de pausa y salir.

**Comment by ElTioAndresCabezas** [comment]
Perfecto. Muchas gracias! :D
