### ISSUE TITLE
Accidentes/daño vehiculo

### ISSUE THREAD

**Issue by SamWeinstein** [IIC2233/syllabus#253]
Hola! No me queda claro como implementar el daño al vehículo. Quiero confirmar si es asi:

Con probabilidad_accidente() determino si habrá o no un accidente.
En caso de haber un accidente, el daño que este produce se calcula con:
daño_por_vuelta=max(0, rocas - carrocería) 
¿Este daño se lo quitamos a chasis? Porque de no ser asi, en que momento cambiaría el chasis para calcular:
tiempo_pits = TIEMPO_MIN_PITS + (chasis_inicial - chasis_actual)*VELOCIDAD_PITS

Ademas, en probabilidad accidente tambien se usa el chasis_actual y chasis_inicial entonces no entiendo nada de como modelar todo esto de eventos durante la carrera. 
GRACIAS!

**Comment by naviera** [comment]
Hola, la parte que no entiendo, es que dice que al encontrarse con objetos u obstáculos podrá aumentar o disminuir la velocidad, y que estos obstáculos dañan al vehículo, afectando su chasis. No entiendo cómo podría verse afectada la velocidad, ya que aunque se dañe el chasis, este no aparece en ninguna fórmula de velocidad, y por lo tanto no debería afectarla.

**Comment by tomasgv** [comment]
Hola @naviera!

Esa parte se refiere a que la presencia de obstáculos afecta tanto al chasis como a la velocidad.
Como mencionaste, es cierto que el chasis no afecta a la velocidad. Sin embargo, los obstáculos en las pistas sí lo hacen, en la fórmula de velocidad recomendada:

![Captura de pantalla 2019-09-14 a la(s) 13 03 56](https://user-images.githubusercontent.com/48303402/64910745-58186680-d6f0-11e9-91cf-6ca7060becd6.png)

Espero haber resuelto tu duda!
