### ISSUE TITLE
Dict de clases: variable global?

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#253]
Hola! Descubrí que las clases se pueden instanciar a través de un dict de la forma `clases = {dato_hasheable: NombreDeClase}` haciendo `clases[dato_hasheable]()`. En base a eso, me gustaría enumerar todas las clases de un módulo dentro de un dict para ahorrarme varias líneas de ifs y elifs en el main. Mi pregunta es, ¿hay alguna manera de construir e importar ese dict tal que no se considere una variable global?
Gracias de antemanooo

**Comment by vicentevegaulloa** [comment]
Hola @sbcorrea !

Entiendo lo que quieres decir, sin embargo te recomiendo fuertemente que no hagas el diccionario de clases. Si bien esto te ahorraría ifs, haría tu código mucho menos legible. Además, las formas que se me ocurren de que esto no sea una variable global son poner el diccionario en parametros.py, que significaría importar tus clases en parametros.py y no tendría mucho sentido. Espero haberte ayudado (y convencido de no hacerlo jaja) 😄

**Comment by sbcorrea** [comment]
Jajaja, convencidísima! Gracias ☺️

**Comment by vicentevegaulloa** [comment]
De nada!
