### ISSUE TITLE
Módulos tarea 2

### ISSUE THREAD

**Issue by MGome** [IIC2233/syllabus#253]
Revisando la asignación de puntajes de la tarea 2 me surgió la duda si es que sólo se puede utilizar un módulo (parametros.py)? o se refieren a que las constantes se encuentren ahí, pero se pueden usar otro módulos para procesar señales, etc?

**Comment by gatochico** [comment]
Hola! Puedes (y probablemente debas, ya que el nuevo límite de líneas por módulo ahora es de 400 :eyes:) usar cuantos módulos quieras para correr tu tarea. Lo único que pedimos es que si o si debe ir uno que sea para parámetros. Saludos!
