### ISSUE TITLE
Disparos de Zanahoria

### ISSUE THREAD

**Issue by DaniloCordova13** [IIC2233/Syllabus#253]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola!
Tengo una duda sobre los disparos de las zanahorias y el limite de los lobos. Si es que hay un cañón **horizontal** entre conejochico y un **cañón vertical hacia ariba**, ¿conejochico está fuera de peligro ya que la zanahoria que dispara CU sería detenida por el CL o CR?
Esto es pensando en la función riesgo_mortal
Saludos!

**Comment by LudwigUC** [comment]
Hola según entiendo haces referencia a la siguiente situación `[ ['-','-','C'], ['-','-','CL'], ['-','-','CU'] ]` 
En ese caso efectivamente no correría riesgo conejochico, pues la zanahoria de CU no puede traspasar CL, este actúa como una pared para las diferentes entidades.
