### ISSUE TITLE
Problema con pyqtSignal

### ISSUE THREAD

**Issue by ElTioAndresCabezas** [IIC2233/Syllabus#253]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Saludos!
Al intentar enviar una señal dentro de mi codigo, el metodo que debe recibir la señal jamas se ejecuta. Tuve este problema durante la sesión de ayuda de la semana pasada, y el ayudante no supo que era, y si bien logre resolver el problema cambiando la forma de realizar la tarea, ahora estoy teniendo este problema nuevamente.
Destacar que todo se esta ejecutando sin ningun problema, sin errores en el terminal y sin crashearse, pero la señal no funciona.
En mi repo del curso pueden encontrar mi codigo. Añadi anotaciones en los lugares en donde se declara, emite y conecta la señal.
Gracias de antemano!

**Comment by Maxi1805** [comment]
Hola @ElTioAndresCabezas, por lo que pude ver en tu código tienes que fijarte que la señal no se envíe antes de que las señales se conecten en tu código, puedes probar a colocar algún print después de enviar la señal y antes de conectarla, si estoy en lo correcto debería aparecerte algo como lo siguiente:
![image](https://user-images.githubusercontent.com/79774281/140823613-78d67b25-a254-4c49-9f12-59046f3dc307.png)
Espero que te sirva.

**Comment by ElTioAndresCabezas** [comment]
Muchas gracias! Ahi funcionó.

Saludos!
