### ISSUE TITLE
Manejo de archivos .csv

### ISSUE THREAD

**Issue by JavaBravo** [IIC2233/syllabus#253]
Hola, ya que en los nombres de las DCCriaturas, y de los Magizoólogo, se consideran indistintamente las mayúsculas de las minúsculas, ¿puedo guardar todos los nombres en minusculas en los archivos?

**Comment by mpsubiabre** [comment]
Hola @JavaBravo !

Primero que todo, debes tener en cuenta que al momento de revisar tu tarea se utilizaran archivos que contengan nombres con mayúsculas, por lo que ese cambio que mencionas de guardar los nombres con minúsculas puedes hacerlo siempre y cuando sea manejado a nivel de código, así cualquier archivo que se disponga tendrá esos cambios.

Espero haber aclarado tu duda, de lo contrario comenta esta issue :)

**Comment by JavaBravo** [comment]
Claro, mi intención es a través del código cambiarlos a minúsculas, ¿en ese caso se podría entonces?

**Comment by mpsubiabre** [comment]
Claro, no habría problema :)
