### ISSUE TITLE
Manejo de dinero del programa

### ISSUE THREAD

**Issue by matildeotte** [IIC2233/syllabus#253]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo varias dudas con respecto al dinero:
1) Cuando el canal paga plata por cada barco en cada hora simulada, esta plata la reciben los barcos o sólo se descuenta del canal? Si los barcos reciben la plata, debemos conocer el flujo de dinero para cada barco? Es decir que pierdan plata en eventos especiales y cuando salen del canal. En caso de lo anterior, si un barco se queda sin dinero dentro del canal qué pasa?
2) Al desencallar un barco, el costo de desencallar lo asume el canal o el barco?
3)En el evento especial de intoxicación, el barco pierde una cantidad de dinero, este se le paga al canal? 
4) Cuando expira una mercancía, el barco debe pagar una multa, esta multa la recibe el canal?

**Comment by rfigueroa314** [comment]
tengo las mismas dudas!

**Comment by DomingoCarvajal** [comment]
En general, el programa se centra en el manejo de dinero del canal, ya que nosotros "controlamos" a este, por lo que no es necesario llevar una cuenta del dinero de cada barco. Pueden considerar que el barco siempre tendrá dinero para pagar a menos que el enunciado diga lo contrario.

Para todos los eventos que mencionas está bien explicado en el enunciado quien debe asumir el costo y quien recibirá dinero. Pero igualmente recuerda que todos los eventos donde se tiene pagar deben afectar de alguna manera al canal, ya sea recibiendo dinero o perdiendo dinero.

**Comment by kraksiplus** [comment]
Aprovechando el issue, el seteo de cuanto dinero tiene el canal, cuanto cobra el canal los seteamos por nuestra cuenta no??

**Comment by Nicolasramos411** [comment]
Hola @kraksiplus! No soy ayudante, pero esa duda está resulta en el issue #226 ,

Ojalá te sirva!
