### ISSUE TITLE
Problema con gui.add_piece()

### ISSUE THREAD

**Issue by ManuelOchagavia** [IIC2233/Syllabus#253]
Hola, 
Tengo un problema con la add_piece(), según el enunciado debería arrojar una excepción al intentar ponerla en una casilla que ya estuviera ocupada. Pero, al hacer correr el código y clickear varias veces en el mismo casillero, la función no nos da ninguna excepción. Quería saber si esta mala o debemos hacer algo cambiándola para que si devuelva una excepción. Gracias

**Comment by sebacruzd** [comment]
Hola,

La idea es que ustedes implementen eso. Por ahora en el demo solo están métodos básicos para que ustedes entiendan cómo funciona, pero tienen que ustedes manejar todo tipo de eventos para que el programa funcione como corresponde.

Saludos!

**Comment by inmadariaga** [comment]
Si ya programe como si me arrojase la excepcion, puedo seguir usandola asi? o tengo que adaptarme al print?

**Comment by iqacevedo** [comment]
El problema con el error es que no sabrías de qué tipo es, por lo que si lo implementaste usaste:
~~~
try: 
    ...
    ...
except Exception:
    ...
    ...
~~~
Lo cual no es una manera correcta de manejar un error porque no sabes realmente que error ocurrio. Por lo anterior, no puedes ocuparlo como si te arrojará una excepción.

Saludos !
