### ISSUE TITLE
Duda sobre validez de unidades.txt

### ISSUE THREAD

**Issue by Jugonzalo** [IIC2233/Syllabus#253]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En la parte de unidades disponibles dice que no podemos asumir que hay un gato de cada clase en el archivo. ¿esto significa que un archivo unidades.txt sin un gato de cada clase es invalido? ¿o simplemente puede no estar?

**Comment by Benjeeeh** [comment]
Hola!
El enunciado considera estos casos como errores, por lo que se debe terminar el programa en caso de que suceda. Debe haber un gato guerrero, mago y caballero como mínimo. 
![image](https://github.com/IIC2233/Syllabus/assets/78326186/bd54ac55-bb35-41f2-ae78-6529afa04c98)

Saludos!
