### ISSUE TITLE
Properties en clases abstracta con herencia

### ISSUE THREAD

**Issue by Juan379** [IIC2233/syllabus#254]
Hola!
Para poder definir los vehiculos defini una clase abstracta Vehiculo que es padre de Automovil, Troncomovil, etc...
Para poder afectar los atributos de estas clases quiero utilizar properties con setters. Con relacion a esto me surgio la duda de si deberia utilizar el getter y setter para atributos como Chasis, Carroceria, etc en la clase padre abstracta y luego hacer override en las subclases, o si deberia utilizar las properties en las subclases mismas?

**Comment by Drpinto1** [comment]
¡Hola!

Lamentablemente este tipo de dudas no pueden responderse fácilmente pues **no existe una sola respuesta correcta** y depende mucho de **tu modelación**. 
Por lo anterior, si te recomendáramos alguna de las opciones que mencionas por sobre la otra, estaríamos cerrándonos a las distintas posibilidades y maneras de resolver el problema que podrían ser igualmente correctas si están bien implementadas.

Dicho esto, algunos consejos que si te podemos dar para que puedas tener una idea más clara de si tus decisiones son o no correctas son los siguientes:

* Para decidir si algún atributo debería o no ser una property puedes preguntarte, ¿Es el valor de este atributo dinámico?, es decir, ¿Varía el número a lo largo del programa? y en particular para decidir si la property necesita de un `setter` ¿Necesito manejar el caso en que una clase externa intenta cambiar el valor de este atributo?
* Para decidir si hacer un método/atributo en la clase padre o en las clases hijas puedes preguntarte, ¿Todas los tipos de {clase} poseen este {método/atributo}?; en este caso ¿Todos los tipos de vehículo tienen carrocería/chasis?
* Para decidir si hacer o no override de un atributo/método de la clase padre, puedes preguntarte, ¿Todos los {clase hija} tienen el mismo {atributo/método} que los demás {clase padre}?. E.g: ¿Todos los automóviles tienen el mismo chasis que los demás vehículos?

Espero que estas preguntas te ayuden a decidir sobre tu modelación.
¡Saludos!

**Comment by Drpinto1** [comment]
Lo que preguntas es una decisión de diseño que tu debes tomar, ya que no existe solamente una manera correcta de hacer lo que explicas.

Existen varias issues sobre el uso de herencia y properties, quizás leyéndolas puedas hacerte una idea de algunas maneras de hacer lo que comentas. 

Saludos :D
