### ISSUE TITLE
Error en Pycharm

### ISSUE THREAD

**Issue by masoto22** [IIC2233/syllabus#254]
Hola, estaba repasando el material e intenté correr los códigos de interfaz gráfica y me aparece esto 😢 
"File was loaded in the wrong encoding: 'UTF-8'"

Aiuda 🆘

**Comment by masoto22** [comment]
Ya lo solucioné xD Borré los tildes y era jejej

**Comment by gatochico** [comment]
Que bueno que lo arreglaste!!! Si te llega a aparecer de nuevo el error, podrías echarle un ojo a este [link](https://stackoverflow.com/questions/43153703/file-was-loaded-in-the-wrong-encodingutf-8-in-intellij-idea) (Si, el ejemplo es para otra IDE, pero Pycharm funciona igual)
