### ISSUE TITLE
Duda de manejo de archivos

### ISSUE THREAD

**Issue by mjadresic** [IIC2233/syllabus#254]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Mi codigo debe estar hecho para correr los archivos entregados tal cual estanr, o debe estar hecho para correrlos en caso de ser modificados? Por ejemplo, para mostrar los canales, basta con imprimir "panama y suez" o debe ser capaz de leer el archivo canales.csv y imprimir todos los canales que se agreguen al archivo canales.csv posterior a la entrega?

**Comment by sperezmasri** [comment]
Hola @mjadresic. Efectivamente tu programa debe leer y manejar los archivos ```.csv```, ya que es uno de los puntos a evaluar de esta tarea. Los archivos **si podrían ser distintos** a los que se entregan como base, así que tu programa debe considerar esto. Eso si, los archivos siempre mantendrán la estructura y formato que se describe en el enunciado.
