### ISSUE TITLE
Paises incontagiables

### ISSUE THREAD

**Issue by ofvera** [IIC2233/Syllabus#254]
Llevo una buena cantidad de intentos contagiando al mundo, aumentando sustancialmente la probabilidad de contagiar por aeropuertos a otros países. Cambiando el requerimiento a 0.004 de la población mundial, y la probabilidad de contagio x 1000, hasta le cambie la formula de muerte devuelta a min por que se morían muy rápido, y así le daba más tiempo a la expansión.
Sin embargo, hay un conjunto de países que parecieran ser inmunes si no son infectados de un principio (debido a su relación geográfica y probabilidad de contagio separada y baja de cada una): [Haiti,New Zealand,South Africa,Dominican Republic,United Kingdom]. Y si los infecto al principio termino perdiendo más rápido aun por su aislamiento.
Lo dejamos así? Ignoramos el hecho que es muy difícil ganar? O puedo dejar y aumentar más aun los supuestos que considero para que eventualmente se puede ganar alguna partida?

**Comment by josemlira** [comment]
Quizás es porque los países en el archivo airports.csv están escritos diferentes al resto de los archivos: New zealand, South africa....

**Comment by ofvera** [comment]
lo paso todo a .lower() para las comparaciones, asi que no creo que sea eso

**Comment by josemlira** [comment]
#230
