### ISSUE TITLE
Duda con validez Archivo Dificultades

### ISSUE THREAD

**Issue by rinsoni** [IIC2233/Syllabus#254]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda con la validez en el formato de los archivos de dificultades. ¿Podemos asumir que los valores que deberían ser numericos (como vida_max, poder, etc) siempre serán strings convertibles a int? Estaba programando una función que se encargue de verificar la validez, y debido a que todos los valores son strings, para "verificar que un valor sea int" en verdad tengo que revisar si ese valor pueda ser convertido de str a int, y para verificar eso tendría solo se me ocurre usar try / except en una función.

**Comment by Benjeeeh** [comment]
Hola!
Hay muchas formas de verificar que un dato es un int, y la forma que tu mencionas en realidad no tendría problema. Solo procura de que maneje todos los casos de posibles errores, así como capturar bien las excepciones (No caigas en malas prácticas ya que acarrea descuentos!)

Saludos.
