### ISSUE TITLE
100 caracteres dentro de un IF

### ISSUE THREAD

**Issue by vmunozgarachena** [IIC2233/Syllabus#254]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, quería saber como se contaban los caracteres dentro de algo como un IF, el límite de 100 es solo para lo que está escrito o también cuentan los espacios previos, por ejemplo en este código lo seleccionado tiene 99 caracteres pero contando los espacios antes del print se tienen 107, eso sería penalizado?
![image](https://user-images.githubusercontent.com/127339460/234103401-1b7f28eb-0f16-47db-8f35-3c9f8c4df36b.png)

**Comment by mtaguero** [comment]
¡Hola @vmunozgarachena!

Los espacios igual se incluyen dentro del conteo de carácteres para las reglas de PEP-8. Si tienes alguna línea que sobrepase el límite (contando los espacios), te recomiendo investigar las diferentes opciones que tienes para poder dividirla.

¡Éxito! 🎈
