### ISSUE TITLE
Inventario Plantas - Jardin 

### ISSUE THREAD

**Issue by canija2000** [IIC2233/Syllabus#254]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Se especifica en el enunciado que la clase Jardin debe tener el parametro`inventario_plantas `, y que este se va llenando a medida **llegan plantas** , luego, si el jardin (en su creación) tiene plantas, estas no son consideradas en el inventario? (no encontré en ninguna parte que se especificara esto)
gracias!

**Comment by AndreaVict** [comment]
Holaa, tal y como mencionas, las plantas que vienen conjunto a la creación del jardín no deben ser consideradas en el inventario, puesto que ya están cultivadas. El parámetro inventario_plantas solo contiene plantas que llegan y que aún no están posicionadas dentro del tablero. Espero que haya quedado claro. Mucho éxito en la tarea!!

**Comment by canija2000** [comment]
Ok! gracias!
