### ISSUE TITLE
 App.exec() para abrir ventana

### ISSUE THREAD

**Issue by PolloDK** [IIC2233/Syllabus#254]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En las librerías prohibidas sale que de ninguna manera deberíamos utilizar exec() y eval(), pero para poder ejecutar la ventana desde el archivo main necesitamos el código para ejecutarla:

`if __name__ == '__main__':
    app = QApplication([])
    app.exec()`

¿Hay algún reemplazo para ese código o en ese caso no importa?

**Comment by fernandosmither** [comment]
Hola @PolloDK , recuerda que el builtin prohibido es la función `exec()` ya que puede ser utilizada para ejecutar código malicioso. Sin embargo, si te das cuenta, `app.exec()` es un método de PyQt, el cual es completamente distinto al builtin de python.

> TL;DR: `app.exec()` **es legal**

Avísame si esto responde tu pregunta :smiley:
