### ISSUE TITLE
EDD personalizadas y de python

### ISSUE THREAD

**Issue by aamedinaj** [IIC2233/Syllabus#254]
Quiero ver si me quedó claro (porque los ayudantes de cátedra me dijeron que abriera una issue):
 En #174  ponen de ejemplo el método .split() pero, en general ¿se puede tomar CUALQUIER función de python que retorne listas, tuplas, etc. y volverla "legal"[1] en la linea inmediatamente siguiente?

[1] volver legal= desempaquetarla dentro de mi EDD y guardarla como tal

gracias :3

**Comment by monicabelen** [comment]
Claro, en resumen no puedes iterar sobre estructuras prohibidas en toda la tarea, pero SÍ puedes desempaquetarlas en tu propia EDD y trabajar con ella.
