### ISSUE TITLE
Problemas al hacer git commit (Changes not staged for commit / Untracked files)

### ISSUE THREAD

**Issue by LukasGuthrie** [IIC2233/syllabus#254]
Hola! Estoy intentando hacer git commit a un archivo de mi T00 y me tira este error
![2020-08-28](https://user-images.githubusercontent.com/69617185/91565008-839b5d80-e90f-11ea-8377-2a0b922a0fa2.png)
me parece super raro porque hace referencia a archivos de la AF01 y no he modificado ninguno de esos archivos. Ayer después de la AF01 también commitee archivos de mi T00 no me tiró ningún error :c

**Comment by vicentevegaulloa** [comment]
Hola @LukasGuthrie !

Esto no debería afectar en que subas tu T00, pero si estás intrigado y quieres ver el cambio que se menciona en el archivo de la AF01, puedes ubicarte en la carpeta de la AF01 y utilizar el comando `git diff`` que te señalará enque linea o lineas está el cambia no guardado.

**Comment by LukasGuthrie** [comment]
Sirvió, muchas gracias!

**Comment by vicentevegaulloa** [comment]
De nada!
