### ISSUE TITLE
Método "mouseMoveEvent" y "mousePressEvent" no funcionan en la ventana de juego

### ISSUE THREAD

**Issue by benhacks300** [IIC2233/Syllabus#254]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido

Hola buenas, quería comentar un problema que tengo a la hora de la utilización de los métodos de "mouseMoveEvent" y "mousePressEvent" que permiten mostrar la ubicación del mouse. Lo que sucede es que en mi ventana de partida (creada con qtDesigner), no detecta los ejes X e Y en donde el mouse clickee o esté recorriendo la ventana, siendo nula la emisión de una señal que me permita seguir con la programación del juego, siendo que ya prácticamente todos los elementos de la ventana tienen activada la función de mouseTracking. 

Espero puedan ayudarme frente a este problema :c

**Comment by iespinazac** [comment]
Hola @benhacks300!
¿Podrías realizar un push en tu repositorio para poder ayudarte con tu problema?
Me avisas por este mismo medio cuando ya lo hayas hecho 😄

**Comment by benhacks300** [comment]
holaa, no te preocupes, ya pude solucionar el problema :3, igualmente muchísimas gracias por la respuesta ♡
