### ISSUE TITLE
Contenido parametros.py

### ISSUE THREAD

**Issue by jonanortizvega** [IIC2233/syllabus#254]
Hola, ¿Qué tipo de datos pueden ir en parametros.py?
¿Solo se pueden poner valores y path, o también se pueden poner stings definidos o diccionarios?
Saludos

**Comment by matiasmasjuan** [comment]
Hola @jonanortizvega !
Si, se pueden utilizar strings definidos y diccionarios como **parámetros** siempre y cuando sus nombres sean **descriptivos** y reconocibles a simple vista.
Éxito con la tarea!

**Comment by rmaguilera** [comment]
se pueden usar listas como parametros?

**Comment by matiasmasjuan** [comment]
Hola @rmaguilera !

Te sugiero que visites el ***Compilado de Issues*** #239 y mires todas las preguntas relacionadas con en archivo ***parametros.py***, ya que se ha **respondido** varias veces a la misma pregunta.
*spoiler*: si, si puedes usar listas como parámetros, siempre que sus nombres sean **descriptivos**.

Saludos! 😄
