### ISSUE TITLE
Recompensas por vuelta

### ISSUE THREAD

**Issue by mpbosnic** [IIC2233/syllabus#255]
Hola! Tengo una duda acerca de las recompensas por vuelta.

En el enunciado dice que hay una "recompensa parcial" donde el menor tiempo por vuelta recibe dinero y experiencia. ¿Esto es aparte del dinero ganado por vuelta que se premia si el jugador va primero? ¿Se asigna cada vuelta o al final de la carrera?

Gracias!

**Comment by enzoyacometti** [comment]
Hola, el enunciado dice que es "el menor tiempo por vuelta", vale decir, la vuelta más rápida... puede que esta sea del primer lugar, o del tercero, o del último.

Solo para confirmar, la recompensa de dinero es para el que logre el MEJOR tiempo en la vuelta actual o el que va primero??

**Comment by gatochico** [comment]
Hola! Como estamos tomando el tiempo como acumulado, este sería quien va primero en cada vuelta.

**Comment by lucastack** [comment]
Hola, que sucede cuando sólo el jugador termina la carrera (y por lo tanto gana). Quién se consideraría 'ultimo' ?
