### ISSUE TITLE
Error de tipeo en Magizoologos

### ISSUE THREAD

**Issue by LissScarlett** [IIC2233/syllabus#255]
Hola!!
En el archivo magizoologos.py hay un error de tipeo en donde debiese decir "docencio" dice "docecio" (En todas las filas que lo contiene)... Me pregunto si lo tratamos así o se puede corregir para que podamos trabajar con el nombre que nos entrega el enunciado.

Saludos :)

**Comment by aljara97** [comment]
Hola @LissScarlett, gracias por avisarnos de este error. Pronto se subirá una versión corregida de este archivo, por tanto, maneja tu código como si estuviera escrito de manera correcta, para coincidir con el enunciado.

Saludos 🧙‍♂️

**Comment by Juampisaez** [comment]
Hola sobre esto mismo, en vez de Hibrido sale HÃ-­brido, ademas, hay mas errores de estos. Hay que trabajar asi?, o como se puede solucionar?

**Comment by Dnpoblete** [comment]
Hola @Juampisaez eso ocurre por el tilde, pero utilizando encoding = “utf-8“ no tendrás problemas!

**Comment by Juampisaez** [comment]
gracias!

**Comment by Juampisaez** [comment]
sigo teniendo problemas, ya puse el encoding = "utf-8"

**Comment by Juampisaez** [comment]
![image](https://user-images.githubusercontent.com/48323752/78616115-560b2600-7841-11ea-87ee-69c3a24dde6f.png)

**Comment by mpmunoz13** [comment]
Hola! Trabajamos con Docencio entonces? Que sigue saliendo Docecio en magizoologos.csv

**Comment by lily416** [comment]
@mpmunoz13 el archivo `magizoologos.csv` se encuentra actualizado en el _syllabus_, debes hacerle _pull_ y cambiar los archivos que estás usando para probar tu tarea.
![image](https://user-images.githubusercontent.com/26393515/79022173-552d0980-7b4b-11ea-8191-7661cf46fa37.png)

Saludos y éxito en la tarea 👋🦄
