### ISSUE TITLE
duda sobre enfrentamientos y poderes especiales de combatientes

### ISSUE THREAD

**Issue by asapsanchez** [IIC2233/Syllabus#255]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola, tengo una duda respecto a la dinámica de ataque. Por ejemplo, si un caballero mio ataca con su poder especial, reducir el poder del oponente, pero que pasa si el ataque de mi oponente a mi combatiente también es el poder especial de caballero, por lo que se reduciría el poder de ataque de mi combatiente. La pregunta es que si siempre atacare yo primero, o bien, atacan al mismo tiempo. Ojalá se entienda.

**Comment by Benjeeeh** [comment]
Hola!
Lo importante es que en cada ronda si o si se ejecute el ataque de cada Combatiente, independiente del outcome. Como tu manejes cada ronda, si atacas tu primero, etc, son supuestos que debes poner en tu README. Te recomiendo leer las issues #243 y #248 que se consultan cosas similares. 

Saludos!
