### ISSUE TITLE
Mejor manera de armar un diccionarío?

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#255]
Hola, como no podemos usar diccionarios, me gustaría armar mi propia EED diccionario, para que cuando quiera sacar el tipo de una pieza lo busque como llave y no recorra toda la lista de piezas disponibles.

El problema es que no encuentro como hacer diccionarios, solo como usarlos/instanciarlos.

tnx

**Comment by TomasSalvadores** [comment]
Hola, la idea de que tengan que crear sus estructuras es que tengan que razonar ustedes mismos el como funcionan y como armarlas. Por eso no puedo ayudarte. Si te recuerdo que no se evaluara la optimalidad de tus estructuras, solo su funcionalidad.
De todos modos felicitaciones por querer profundizar mas solo por gusto! Te invito a seguir averiguando, a ver que logras ;)

**Comment by Hernan4444** [comment]
@Kitaps, si quieres implementar un diccionario tal como indicas, te recomiento buscar sobre Tablas Hash. Lo que si recuerda que evaluaremos estructuras óptimas para la tarea y que no necesariamente el diccionario es la mejor para todo.

Saludos!
