### ISSUE TITLE
Posible error tests función separar mensaje

### ISSUE THREAD

**Issue by DaniloCordova13** [IIC2233/Syllabus#255]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Estaba haciendo la funcion separa mensaje (entrega intermedia) y al momento de probar los tests publicos me di cuenta que creo que están mal. En el enunciado dice que debemos separar en grupos a, b y c en el orden:
a b c c b a a b c...
de ser así, en el test 01 por ejemplo, los tres grupos deberian ser HMu, o n, lado. Mientras que en la solucion aparece [b"Hauo", b"o n", b"lMd"]), como si siguiera el patron a b c todo el rato.
![Captura de pantalla (28)](https://github.com/IIC2233/Syllabus/assets/141789725/657285a6-54f6-47a1-b771-7217e00172a2)
![Image (8)](https://github.com/IIC2233/Syllabus/assets/141789725/4a955309-f70e-486e-acfa-09fbca064c89)

**Comment by ignacio-sp** [comment]
Hola @DaniloCordova13 ! Puedes ver la issue #248 que también se refiere a esto, pero sí, corresponde a un error en los tests, lo correcto es lo que se pide en el enunciado, saludos!
