### ISSUE TITLE
Nombre de usuario tarea

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#255]
Hola! Me entró la duda, cuando dicen que los requisitos del usuario son "una extensión mínima de cinco caracteres, los que deben ser alfanuméricos (números o letras), pudiendo incluir tanto mayúsculas como minúsculas a la vez" quiere decir que tiene que tener al menos una letra, una minúscula y una mayúscula o no es necesario tener al menos uno de cada cosa? "12345" es válido?

**Comment by Juampisaez** [comment]
Hola @kalarconvl 
Tal como dice el enunciado, el usuario puede **tener números o letras**, es decir, puede tener solo números, solo letras o ambas. En cuanto a lo de las letras mayúsculas y minúsculas, puedes elegir tener solo mayúsculas, solo minúsculas o ambas al mismo tiempo, **si es que incluyes letras**. Para la implementacion de esto, te sugiero revisar la [documentacion](https://docs.python.org/3/library/stdtypes.html) el uso de _isalnum()_.

Espero contestar tu pregunta a modo general.

**Comment by kalarconvl** [comment]
Gracias! Lo que pasa es que lo leí mal antes entonces ya lo hice con el requisito de que puede tener número y letras, pero si o si al menos una mayúscula y una minúscula, puedo comentarlo en el README y dejarlo así o mejor lo cambio?

**Comment by Juampisaez** [comment]
Sobre eso que comentas, **debes cambiarlo** ya que no es lo que se pide en el enunciado. En este caso no puedes considerarlo como una suposición valida, ya que te dicen textualmente la forma en que debe estar el nombre del usuario.
