### ISSUE TITLE
Número de jugadores a cargar

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2233/Syllabus#255]
Hola! En el enunciado dice que la gui debe poder ser instanciada con 200 jugadores al azar. El tema es, ¿es necesario que agregue en el grafo los jugadores que no deben ser instanciados en la gui? (O sea, no sé si tengo que hacer un grafo de 200 nodos o de 5500)

**Comment by pcseisdedos** [comment]
Para las consultas necesitas considerar a todos según #240 
PD1: Ahora la base de datos es dde 1650 jugadores
PD2: No soy ayudante
