### ISSUE TITLE
Dudas sobre costo de avanzar e intervalo de caida de soles

### ISSUE THREAD

**Issue by gabo1243** [IIC2233/Syllabus#255]
### Duda

Hola, el costo de avanzar la ronda (antes de matar todos los zombies) ¿es siempre el mismo independiente de la ronda? y con respecto a la generación de soles (no por el girasol, sino por el ambiente) ¿Cuál es el intervalo de caída de soles en el jardín de la abuela?

Gracias de antemano

**Comment by Juampisaez** [comment]
Holaa 👋 @gabo1243 
Sobre tus dos dudas:
1. El enunciado no menciona que costo para avanzar cambia, asi que puedes asumir que no.
2. Existe un parametro llamado "INTERVALO_APARICION_SOLES", recomiendo revisar el enunciado.

Quedo atento si surgen más dudas :)

**Comment by Isiirribarra** [comment]
Hola, es necesario que los soles caigan desde la parte de arriba ? ya que en el enunciado se menciona que aparecen en lugares aleatorios al jardin

**Comment by Juampisaez** [comment]
Holaa 👋 @Isiirribarra 
Nosotros les pedimos que sea aleatoria, sin embargo, si lo deseas hacer como mencionas (caigan del cielo), tambien lo puedes hacer.

Espero que quede mas claro :)
