### ISSUE TITLE
Definir varias variables ¿Es legal?

### ISSUE THREAD

**Issue by RickyUC** [IIC2233/Syllabus#255]
1. Revisando mi código me di cuenta que uso cosas como:   variable1, variable2 = valor1, valor2
¿Es legal hacer eso? ¿Usa tuplas de python o alguna estructura prohibida?

2. Por favor respondan la ultima pregunta de la issue #163
¿Se pueden hacer cosas como: ListaLigada(*map.(...))

**Comment by sebacruzd** [comment]
#1 Si puedes hacerlo, ya que es permitido por PEP8 y no utiliza ninguna estructura prohibida. Sin embargo, personalmente yo no lo recomiendo. Si tienes errores y no sabes donde están y resulta que es por alguna de esas variables, se te dificultará más la búsqueda y arreglo del error.

#2 Ya la respondieron :)
