### ISSUE TITLE
Duda método Encontrar Ítem

### ISSUE THREAD

**Issue by luc0i** [IIC2233/Syllabus#255]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Tengo una duda con respecto a la probabilidad de encontrar un ítem.
Cuando dice: "Posterior a verificar si el excavador pudo obtener un ítem, si esta probabilidad acierta". 
No entiendo cómo verificar que se encuentre el ítem. 

Habría que hacer algo como lo que se hizo en la Actividad 2 en el método de robar_tortuga()?
`def robar_tortuga(self) -> bool:`
   `    # PROBABILIDAD_ROBAR de robar la tortuga`
   `    if random() < self.PROBABILIDAD_ROBAR:`
   `    self.notificar_robo`

Gracias!

**Comment by CarolinaMezaCh** [comment]
Hola @luc0i!

Claro, la idea es comparar la probabilidad con la que definiste en parametros.py. Como mencionas, puedes utilizar la librería random ya que se encuentra permitida. También puede ver más ejemplos de comparación de probabilidades en la sala de ayuda que hay para la tarea T1.

Éxito con la tarea!!
