### ISSUE TITLE
Duda sobre uso de import

### ISSUE THREAD

**Issue by cseverino99** [IIC2233/syllabus#255]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Holaa, si estoy creando una sub clase que no tiene un atributo de su super clase y para describir este atributo (self.nombre = ??) quiero llamar al modulo de parametros y darle uno de estos valores presentes en este modulo, para ello al inicio del modulo de clases hago import paramatros..... 
Si para el main también necesito importar parametros de este modulo, y uwlvo a importar parametros... y además importo clases... se produce un error por importar y tantas veces un módulo?

**Comment by sperezmasri** [comment]
Hola @cseverino99. No debería producirse un error por importar varias veces un modulo desde distintos módulos. Como dices tu, si importas ```parametros.py``` en ```clases.py``` y luego importas ```parametros.py``` y ```clases.py``` en ```main.py```, no debería haber problema.

Eso si, ten cuidado al hacer las importaciones, ya que por ejemplo, podría pasar que tratas de hacer importaciones "cruzadas" y esto si generaría un error. Con esto último me refiero por ejemplo que de un modulo ```main.py``` importes un modulo ```test.py``` pero al mismo tiempo en ```test.py``` importes ```main.py```, esto si generaría errores.
