### ISSUE TITLE
Problemas para visualizar ventana

### ISSUE THREAD

**Issue by HAWK-EF2021** [IIC2233/Syllabus#255]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Tengo un problema con VSCode para visualizar las ventanas que estoy creando. Cuando hago la previsualización en el QT Designer las ventanas me aparecen con el tamaño correcto, pero cuando los paso al VSCode la ventana y los elementos se vuelven más pequeños, perdiendo su formato. Traté de correr el archivo en el terminal del computador y pasó lo mismo. El problema con esto es que para  la ventana de juego necesito ver el funcionamiento del código sin errores en la ventana. ¿Hay manera de arreglar esto?

P.S. Mi computador corre con Windows 10

**Comment by mmunoz12** [comment]
Hola @HAWK-EF2021!
Puede ser que tu computador tenga una escala diferente al 100%, esto puede cambiarse en los ajustes en la parte de pantallas > escala y diseño (puede que me equivoque pero algo así debería ser). Avísame si con eso se soluciona! Saludos.
