### ISSUE TITLE
Error señales

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#255]
No entiendo por que me tira un error. Mi codigo es:
![1](https://user-images.githubusercontent.com/48294819/57823908-38375d00-7767-11e9-8f61-59c0711286f4.PNG)

y me arroja el siguiente error:

![2](https://user-images.githubusercontent.com/48294819/57823923-3ff70180-7767-11e9-8b2d-34978ce2a90a.PNG)

**Comment by gatochico** [comment]
Hola! Si buscas en internet el error que obtuviste, encontrarás esta [pregunta](https://stackoverflow.com/questions/2970312/pyqt4-qtcore-pyqtsignal-object-has-no-attribute-connect) de stackoverflow  como uno de los primeros resultados...

Intenta mover la primera definición de self.señal fuera del constructor de tu clase, de forma que quede:

```
class A(QtCore.QThread):
    #Define primero aquí las señales
    senal =pyqtSignal()

    def __init__(self):
        # todo lo demás que tiene tu clase... 
```
Nos cuentas como te va!

**Comment by jalliende** [comment]
Si ahí me resulto,  gracias. También había visto esa respuesta y no me resulto antes y no se porque ahora si
