### ISSUE TITLE
¿Qué hacer con las señales?

### ISSUE THREAD

**Issue by jearaneda** [IIC2233/syllabus#256]
Aún no entiendo lo que se busca evaluar con señales, particularmente en los keypress. Sabemos que se puede hacer un override de keyPressEvent fácilmente para hacer algo en cuanto se presiona una tecla pero, qué hago ahí?

La idea es que yo a partir de eso genere una señal? 
```
def keyPressEvent(self,event):
    senal = pyqtSignal()
```

O que, como eso es de cierto modo una señal, simplemente llame un método que bien puede estar en backend.py por así decirlo?

```
def keyPressEvent(self,event):
   backend.mover_personaje(self.event)
```

**Comment by lily416** [comment]
El uso de señales están hechas para tener una correcta separación entre el _backend_ y el _frontend_ evitando de esta forma que se produzca modelación circular. Además están optimizadas lo que hace que la comunicación entre el _backend_ y el _frontend_ sea más fluida y eficiente.

La idea de que cuando quieras usar señales es que hagas lo siguiente:
1. Crees una señal y guardarla como una **variable de clase**, no dentro de la función. Puedes ver un ejemplo en la issue #255.
2. Conectas las señal con una función, ya sea del _backend_ o del _frontend_, para esto usas el método `connect()`.
3. Dentro de una función (i.e. `keyPressEvent`) emites la señal que creaste antes y le pasas el input si es necesario, para esto debes usar el método `emit()`. El _input_ que le entregas depende de lo que hayas indicado cuando creaste la señal, es decir, si haces:
   - `pyqtSignal()` no recibe un _input_.
   - `pyqtSignal(object)` recibe un `object` como _input_.
   - `pyqtSignal(int)` recibe un `int` como _input_.
4. La función con la que se encuentra conectada la señal, la recibe como _input_ y si trae información con ella (i.e. un `object` o un `int`) la procesa. 

Te aconsejo **mucho** que repases el [material](https://github.com/IIC2233/contenidos/blob/master/semana-09/2-eventos-y-señales.ipynb) y que busques ejemplos en internet. También aprovecha la clase de hoy día para preguntar y aclarar tus dudas sobre el tema. 

Saludos y éxito con la tarea. 👋 🐈🐧

**Comment by lily416** [comment]
Fijate que al hacer: 
```python
def keyPressEvent(self,event):
   backend.mover_personaje(self.event)
```
1. **No estás usando señales** para comunicarte con el _backend_. 
2. Al llamar a `backend` puede que se esté produciendo **modelación circular**, ya que puede que `backend` se comunique de la misma forma con el `self` (la clase que lo llama).
3. **No estás procesando el evento**, puede que le estes pasando a `mover_personaje` más información de la que sea verdaderamente necesaria, tal vez en lugar de pasar el evento completo sea mejor pasar una string con un `'up'`, `'down'`, `'left'` o `'right'` dependiendo de lo que se produzca en el evento.
