### ISSUE TITLE
Cuantos archivos puedo crear para la tarea

### ISSUE THREAD

**Issue by Johan-10** [IIC2233/Syllabus#256]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Para la tarea tenemos que crear un archivo main.py el cual ejecuta la tarea, mi pregunta es si puedo crear mas archivos para así modular la tarea, por ejemplo, crear un plantas.py para los objetos planta o un jardin.py para la entidad jardín que nos piden en la tarea.

**Comment by AndreaVict** [comment]
Holaa!!, te recomiendo que revises la issue #247, ya que se pregunta algo similar a lo que indicas. ≽^•⩊•^≼
