### ISSUE TITLE
Duda sobre .gitignore

### ISSUE THREAD

**Issue by josziga** [IIC2233/Syllabus#256]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, tengo una duda sobre el .gitignore, en el feedback de la tarea 1 me pusieron que utilicé mal el .gitignore, porque se pone un punto al comienzo. Y no entiendo qué tengo malo, para corregir para las próximas entregas...

Gracias

**Comment by Benjeeeh** [comment]
Hola!
Si, el archivo como tal debe llamarse ".gitignore", ya que así lo reconoce git y permite realizar su función. Este es un archivo, no tiene extensión .txt ni nada similar.
¿Pusiste el . en tu archivo al momento de crearlo? Al momento de revisar se quita el . del archivo para que no se quede oculto en tu repositorio, y puede que se haya traspapelado la persona a cargo de revisar (somos humanos uwu) y se haya aplicado el descuento. Por lo que revisé de tu repo está todo okay, por lo que te recomiendo mandar a recorrección para verificar este caso! Gracias por hacerlo saber.

De igual manera dejo un poco de información adicional frente al .gitignore:
Recomiendo descargar el archivo del [repositorio base ](https://github.com/IIC2233/Syllabus/blob/main/.gitignore) que se encuentra en el syllabus y rellenar desde ahí! Utiliza ese mismo archivo, elimina los comentarios y agregas los archivos que te pide esta tarea y lo agregas a tu T2 para que cada vez que subas a tu repositorio se suba todo menos lo contenido en .gitignore.
También puedes leer la [documentación oficial](https://git-scm.com/docs/gitignore) que está en inglés y puede que arroje información adicional, pero por si te interesa.
