### ISSUE TITLE
Propagacion de la enfermedad entre paises.

### ISSUE THREAD

**Issue by hagarces** [IIC2233/Syllabus#256]
En el enunciado la formula de probabilidad de contagio de países es muy pequeña, por lo que antes de que el país tenga la posibilidad de contagiar a otros  cierra sus fronteras y la infección no se esparce. :(

**Comment by sebacruzd** [comment]
En #235 está la respuesta a esto. Puedes adaptar la fórmula para que funcione de la manera que tu esperas.
