### ISSUE TITLE
Join a final de ejemplo en 2-concurrencia

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#256]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Cuál es la utilidad de utilizar los _join()_ aquí? veo que me dan prácticamente el mismo _output_
![image](https://user-images.githubusercontent.com/66154723/115313080-a1d4f880-a140-11eb-9aa4-3eee6f02d0e7.png)
![image](https://user-images.githubusercontent.com/66154723/115313100-ad282400-a140-11eb-8107-f6f116951bf6.png)

<details>
  <summary>Código</summary>

```python
# Ejemplo sacado de http://zulko.github.io/blog/2013/09/19/a-basic-example-of-threads-synchronization-in-python/

import threading
import time


# Tenemos dos eventos o señales.
# Esta es para avisar que el video ya está listo para ser reproducido.
video_cargado = threading.Event()
# Esta es para avisar que el audio ya está listo para ser reproducido.
audio_cargado = threading.Event()



def reproducir_video(nombre):
    print(f"Cargando video {nombre} en t={time.time():.6f}")
    # Supongamos que se demora 3 segundos
    time.sleep(3)
    print(f"¡Video cargado! en t={time.time():.6f}")
    # Avisamos que el video ya está cargado
    video_cargado.set()
    # Esperamos a que el audio ya se haya cargado
    audio_cargado.wait()
    # ¡Listo!
    print(f"Reproduciendo video en t={time.time():.6f}")
    
    
def reproducir_audio(nombre):
    print(f"Cargando audio {nombre} en t={time.time():.6f}")
    # Supongamos que se demora 5 segundos
    time.sleep(5)
    print(f"¡Audio cargado! en t={time.time():.6f}")
    # Avisamos que el audio ya está cargado
    audio_cargado.set()
    # Esperamos a que el video ya se haya cargado
    video_cargado.wait()
    # ¡Listo!
    print(f"Reproduciendo audio en t={time.time():.6f}")
    
    
t1 = threading.Thread(target=reproducir_audio, args=("'No Te Enamores' - Paloma Mami",))
t2 = threading.Thread(target=reproducir_video, args=("'No Te Enamores' - Paloma Mami",))

t1.start()
t2.start()

t1.join()
t2.join()
```
</details>

**Comment by aaossa** [comment]
Tienes razón en ese sentido, solo harían diferencia si los *threads* fueran instanciados con `daemon=True`. Me parece que esos `join` quedaron ahí solamente porque el código está en una celda de Jupyter, por lo que la celda "sigue ejecutandose" mientras está en el `join`, para asegurar que el *output* quede en la celda correcta. Buena observación de todas formas 👌

**Comment by fernandosmither** [comment]
> Tienes razón en ese sentido, solo harían diferencia si los _threads_ fueran instanciados con `daemon=True`. Me parece que esos `join` quedaron ahí solamente porque el código está en una celda de Jupyter, por lo que la celda "sigue ejecutandose" mientras está en el `join`, para asegurar que el _output_ quede en la celda correcta. Buena observación de todas formas 👌

Como siempre profesor, gracias!
