### ISSUE TITLE
Entidad Alimentos 

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#256]
Tenemos que crear una clase Alimnetos, o podemos simplemente desarollarlo como un dictionario?

**Comment by moquezada** [comment]
Hola @CataSudo!

Esto es algo que no podemos responder directamente, pues la idea de la tarea es que ustedes puedan tomar sus propias decisiones a la hora de modelar. Por otra parte, para ayudar a la decisión de si una entidad debe o no ser una clase puedes realizarte las siguientes preguntas:

- ¿Cómo se relaciona esta entidad con el resto de entidades? ¿Cómo se comporta a lo largo de la ejecución del programa?

- Dado cómo se relaciona esta entidad y considerando su comportamiento , ¿esta debe ser una clase?

Debes tener en cuenta que OOP es un paradigma de programación y analizar si sus características y ventajas se ajustan a la modelación de tu entidad.

Espero haberte ayudado! 😄

**Comment by aljara97** [comment]
Hola, para complementar lo que dijo @moquezada. Uno de los objetivos de esta tarea es que sean capaces de utilizar clases y multiherencia, por tanto, sí podemos pedirles que algunas de estas entidades sean modeladas como clases y no como un diccionario. Por eso, considera las sugerencias del comentario anterior y revisa la distribución de puntaje, la que debería publicarse pronto, para que estés segura de que estás modelando correctamente tu programa.

Éxito 🧙‍♂️
