### ISSUE TITLE
Duda sobre uno de los parametros

### ISSUE THREAD

**Issue by franco-anfossi** [IIC2233/Syllabus#256]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo una pregunta con los parámetros ya que en el Enunciado sale que uno de estos es INTERVALO_APARICION_SOLES que no esta en el archivo .py y tenia la duda de si la teníamos que poner nosotros dentro del archivo.

**Comment by Juampisaez** [comment]
Holaa 👋 @franco-anfossi 
Ojo que no necesariamente están todos los parametros en el archivo, es más bien una ayuda para la creación del archivo. De igual manera pueden hacer cambios, tanto en los valores de los parametros como en la posibilidad de agregar parametros necesarios (en tu caso, que aparecen en el enunciado).

Quedo atento si surgen mas dudas :)
