### ISSUE TITLE
Diagrama de clases: Relaciones de agregación y composición

### ISSUE THREAD

**Issue by pulpaulaa** [IIC2233/Syllabus#256]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, esta es una duda de contenidos, pero la pregunto porque necesito hacerlo en la tarea. A pesar de que he buscado muchas veces en el contenido y en internet, no logro entender bien cuándo se debe usar la relación de composición y cuándo se debe usar la de agregación. Usaré una pequeña parte de la tarea (de forma más simplificada) como ejemplo.
Si yo tengo una clase llamada `Torneo`, la cual tiene un atributo llamado `arena`, que contiene una instancia de la clase `Arena`, yo pensaría que tienen una relación de composición, ya que esa instancia fue creada dentro de torneo, sin embargo, sigue siendo solo una instancia y, teóricamente, si el torneo deja de existir, la arena de la playa claramente puede seguir existiendo por su cuenta (relación de agregación), sin embargo, nadie la estaría instanciando porque todo el código funciona por medio de los métodos de la clase `Torneo`, por lo que si yo no llamo a `Torneo`, no va a pasar absolutamente nada. 
Entonces, si una clase no es instanciada, ¿puede seguir 'existiendo' de igual forma? 

Espero que se entienda mi pregunta, es media filosófica pero es que de verdad no entiendo bien.

Duda extra: En el enunciado dice que el diagrama deberá "contener todas las relaciones existentes entre las clases: agregación, composición y herencia". Quizás esta duda se me aclare con la respuesta de la otra pregunta, pero no sé qué hacer si mi diagrama solo tiene de herencia y composición o de herencia y agregación. ¿Es muy terrible que no haya de la tercera? Porque no me hace sentido que existan las 3 en mi código.

**Comment by Rotopikus** [comment]
Hola!!!

Si una clase no es instanciada, va a existir en tu código (está escrita y puede tener atributos, métodos, etc), pero no hará nada, entonces es como si no estuviese implementada.
Por otro lado, las relaciones entre clases, no necesariamente tienen sentido en el mundo real, lo importante es que deben tener sentido en el contexto en el que se está modelando un código. Por ejemplo, imagina que te indican que se quiere modelar un programa de los cursos de la U, donde el curso no puede existir si no hay un profesor. En la realidad los cursos pueden existir con un profesor “por fijar”, pero en el contexto del código no.
En esta tarea se está evaluando que implementes en tu código los tres tipos de relación pedidos en el enunciado. Por lo tanto es importante que estén presentes.

Espero haber aclarado tu duda. No dudes en preguntar si no se entiende. Éxito!!
