### ISSUE TITLE
¿En qué parte del código deberían estar contenidas las animaciones?

### ISSUE THREAD

**Issue by ribik20** [IIC2233/Syllabus#257]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Entiendo que es recomendable ser ordenado en la división de frontend y back end. ¿Las animaciones de un juego deberían ser parte del front o del back? Me confunde porque para hacer animaciones es necesario configurar timers y funciones internas para cuando gatillarlas.

**Comment by Juampisaez** [comment]
Holaa 👋 @ribik20 
Todo depende de como lo modeles tu. Para darte una ayuda, en el frontend debes ir actualizando la visualización de los elementos de la ventana según lo que vaya ocurriendo en el backend. Si tienes mas dudas, recomiendo revisar los videos subidos junto al anuncio de la tarea 2 en canvas.

Quedo atento si surgen más dudas :)
