### ISSUE TITLE
Error en test 8 de Encriptar mensaje

### ISSUE THREAD

**Issue by flcarvallo** [IIC2233/Syllabus#257]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el octavo test de la función "encriptar_mensaje" me da AssertionError. Realicé el ejercicio a mano y no cambió mi resultado.
¿Es posible que haya un error en este test?

**Comment by LudwigUC** [comment]
Hola Florencia, el octavo test está correcto, efectivamente al realizarlo a mano da un resultado distinto, pero dado el manejo de bytes en Python se llega al resultado especificado. Si tienes más consultas no dudes en preguntar, saludos!

**Comment by FraMqueli** [comment]
Hola, creo que en efecto el test esta malo puesto que en vez de estar en formato nABC o n nBAC está en formato nACB o nBCA
