### ISSUE TITLE
seleccion 'volver' en menu principal

### ISSUE THREAD

**Issue by GuilleStanke** [IIC2233/Syllabus#257]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, si el usuario inicia una nueva partida, y sin guardarla selecciona la opción 'volver' desde el menu principal, se debe voler al menu de inicio... la pregunta es: si luego de hacer eso, selecciona nuevamente 'nueva partida', se debe volver a la partida que no guardo pero que estaba iniciada? o debe empezar una nueva perdiendo el proceso que llevaba?

**Comment by CarolinaMezaCh** [comment]
Hola @GuilleStanke!!

Si el usuario no guarda la partida nueva y vuelve al menú de inicio, debería empezar desde una nueva partida, ya que no se podría cargar porque no se habría guardado en el archivo DCCavaCava.txt. Entonces en teoría no podrías cargar la partida, debido a que no estaría registrada en tal archivo. En caso de que selecciones la opción de cargar la partida, deberías manejar el error de forma adecuada para que el flujo del programa sea continuo y no arroje ese error.

Espero haber aclarado la duda!
