### ISSUE TITLE
Funcionalidad parámetros.py

### ISSUE THREAD

**Issue by anamanzana** [IIC2233/syllabus#257]
Hola!

Me surgió una duda respecto al archivo que se debe crear parámetros.py. La idea es poner los parámetros que no varían y "llamarlos" cuando son requeridos?  Entonces, seria como un archivo que es llamado para buscar estos parámetros? No entiendo bien su función o utilidad.

Gracias de antemano!

**Comment by matiasmasjuan** [comment]
Hola @anamanzana !
Es exactamente lo que tu dices. La idea es crear un archivo que contenga todos los parámetros que **no varían** y deberán ser **importados** como un **módulo**. Es un **archivo** que **sólo** contiene parámetros. La idea de esto, es que tu código pueda ser capaz de **modificarse** fácilmente y que sea **escalable**.

Por ejemplo: imagínate que en tu código debes abrir varías veces un archivo con un **path** específico, y para ello debes escribir muchas líneas iguales. (open("nombre_archivo.ext")). Ahora ponte en el caso que por alguna razón, debes cambiar la **ruta** de ese archivo. Esto implicaría que deberás cambiar una por una las líneas de los **open()**, ya que la ruta fue alterada, lo cual es un trabajo muy tedioso y podría consumir mucho tiempo.

En cambio, si hubieras definido desde un principio el **parámetro**: **RUTA** = carpeta/"nombre_archivo.ext", y hubieras escrito el modo de abrir los archivos como: open(RUTA), si deseas realizar algún cambio en el **path**, sólo basta con modificar el parámetro "**RUTA**" y automáticamente todos tus métodos open() se adaptarán al nuevo valor de tu **RUTA**, sin necesidad de cambiarlos manualmente uno por uno.

Esto mismo se puede extrapolar para distintas situaciones, por lo que es muy importante aprender de esta buena práctica. Espero que se haya entendido el ejemplo, y mucho éxito con tu tarea!

**Comment by drosselot** [comment]
Entonces los parámetros no son solo numeros?

**Comment by matiasmasjuan** [comment]
Hola @drosselot !
Tal como dice el enunciado en la parte de **parametros.py**, *Para esta tarea deberás crear y subir un archivo **parametros.py** el cual contenga todos los parámetros nombrados anteriormente, además de todos los paths y cualquier otro valor constante que vayas a utilizar en tu código.*

Por lo tanto, los **paths** o distintas **constantes** que pueden ser *strings*, *diccionarios*, etc. **También** son considerados como **parámetros**. Por lo que no necesariamente son **sólo** números. 

Espero haberte ayudado, y mucho éxito con tu tarea!

**Comment by anamanzana** [comment]
Hola!

Gracias por responder la Issue. Me quedo una ultima duda, se podría importar el archivo?

**Comment by matiasmasjuan** [comment]
Exactamente. Uno de los objetivos de esta Tarea es que ustedes sean capaces de **importar** correctamente el archivo **parametros.py** a cualquier otro módulo dentro de su tarea, y usar los parámetros que se encuentran dentro.

Suerte! 😁

**Comment by anamanzana** [comment]
Muchas gracias 😁
