### ISSUE TITLE
Duda pequeña sobre PyCharm y supuestos errores de importación 

### ISSUE THREAD

**Issue by HenryBlairG** [IIC2233/Syllabus#257]
sucede que yo uso Pycharm y me gusta mucho darle en el gusto a la revisión automática que hace, al punto de que googleo cómo escribir correctamente en inglés las palabras y ver así el glorioso ( ✔️ ) en la esquina superior. Esto se frustra cuando tengo que importar pues para darle gusto al Pycharm tengo que hacer:
import .mi_archivo.py
o
from .mi_archivo.py import mi_funcion
Y cuando hago eso y corro mi código me tira error (Obviamente, esto en el caso de que mi_archivo esté en el mismo directorio donde esta el archivo donde están esas lineas). 
De hacerlo de forma correcta me sale en la esquina ( ❗️ ).
Mi pregunta es: ¿Hay alguna forma de o apagar ese error de importado detectado por pycharm? 
Gracias y disculpen la pregunta tonta, pero no logro encontrar respuesta por mi lado
Esta es una duda por la vanidad de que el programa ratifique que mi código está bien escrito y nada más, no se sientan apresurados para responderme. 😉

**Comment by sebacruzd** [comment]
Hola, sé que en _Settings_ de PyCharm hay una opción para desactivar o cambiar el nivel de los _warnings_.

Al abrir _Settings_, hay un buscador. Ahí escribe "warning", "error" o "detect" (cualquier palabra clave que creas te sirva para llegar a lo que buscas) y al encontrar lo que necesitas configurar, modifícalo.

Una vez lo hice así y pude disminuir el nivel de advertencias que me daba PyCharm. Ahora no lo tengo, por lo que no puedo decirte exactamente cómo se llama esa parte de configuración.

Si nada de lo anterior sirve, nuestro fiel amigo, [google](www.google.cl) nos puede ayudar a encontrar la solución.

Saludos!

**Comment by fdominguezclaro** [comment]
Buena! 
Una forma más rápida también, es poner el mouse arriba del import malo, se te van a aparecer varias opciones, y ponle que ignore ese tipo de errores. 
Saludos!!

**Comment by HenryBlairG** [comment]
Gracias!!!
