### ISSUE TITLE
Ejecución de modulo al importarlo

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#257]
Hola, de antemano gracias por la ayuda.

Me pasa que al importar un modulo este se ejecuta. Pongo

import nombre_modulo()

 y se ejecuta el código al interior de ese modulo. Mi pregunta va a que entonces cada vez que uno importa un modulo este modulo se corre en la consola por defecto de python?, y como se hace para importar un modulo cuando solo me importan las funciones de adentro y no quiero que este se ejecute.

**Comment by DCCollao** [comment]
Hola @diego-ayala-2000!

Para explicar esto, tengo que explicarte antes un poco de cómo maneja python los _import_.

Primero, cada vez que importas un archivo python ejecuta todo el archivo buscando las cosas que necesita. Aunque ya las haya encontrado, el archivo se ejecuta hasta el final, y ese es el motivo por el cual se te está ejecutando el código al importar
tu módulo. 

Además, cuando el intérprete de python lee un archivo, le asigna un nombre para manejarlo de forma interna. Cuando se corre un archivo de forma directa, el nombre que se le asigna a este es '`__main__`'.

Ahora supongamos que el archivo que quieres correr se llama `tarea1.py`: Al correr el script
directamente(`python tarea1.py`), el nombre que python le asignará al archivo es `'__main__'`.

Como ahora sabemos el nombre que python le da al archivo que corremos directamente, podemos utilizar esto a nuestro favor:
Es posible crear un condicional que permita ejecución de código solamente cuando el nombre interno del archivo
sea `'__main__'`, y así evitar el problema de ejecución cuando intentamos importar funciones.

Por ejemplo, supongamos que desde un archivo `main.py`(el que ejecutaremos por consola), queremos importar
el módulo `tarea1.py` en busca de una función `foo()`; pero tenemos el problema de que `tarea1.py` dentro de su código
incluye un `print("hola mundo")` que no queremos ejecutar al importarlo. Para hacer esto, podemos estructurar
el código de la siguiente forma:

[**`main.py`**]
```Python3
import tarea1 as tarea
tarea.foo()
```


[**`tarea1.py`**]
```Python3
def foo():
    print("estoy ejecutando la función foo")

if __name__ == '__main__':
    print("hola mundo")
```

El resultado de ejecutar `python main.py` sería entonces:
```Python3
estoy ejecutando la función foo
```

En cambio, si no hubiésemos utizado `if __name__ == '__main__'`, obtendríamos:
```Python3
hola mundo
estoy ejecutando la función foo
```

Espero que haya quedado claro! Por favor avísame si te queda alguna duda.

**Comment by diego-ayala-2000** [comment]
Me quedo muy claro muchas gracias.
