### ISSUE TITLE
archivos

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#257]
Hola en la parte de abrir el archivo con los jugadores cada vez que lo abro no puedo  lograr guardar bien sus datos , pero al pasar gran parte del archivo a otro y abrir ese me resulta todo perfecto. Que me podra estar pasando.

**Comment by Arcoirisky** [comment]
¿Será que estás leyendo de alguna forma que tú computador explote en el proceso de leer el archivo grande? Si puedes leer gran parte, algo debes estar pasando por alto para la parte que te queda O: (Se me ocurre a mi, al menos)
