### ISSUE TITLE
Duda sobre como hacer que una QLabel aparezca sobre otras

### ISSUE THREAD

**Issue by CataLebe** [IIC2233/Syllabus#257]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Holaa, me pasa que en mi ventana de juego los troncos aparecen sobre la rana. He visto en internet algunas formas de traer QWidgets al frente. Mi problema es que los troncos y la rana están dentro de un mismo widget, pero son Qlabels diferentes. Habra una forma de sobreponer una label sobre otra ? 

Muchas gracias de antemano :)

**Comment by ivanvlam** [comment]
Hola @CataLebe ! Tal como se mencionó en la issue #248, existen los metodos lower() y raise_() que permiten traer al frente o enviar al fondo un determinado label.

**Comment by CataLebe** [comment]
Genial, gracias.
