### ISSUE TITLE
Impedimento de barco al salir del canal

### ISSUE THREAD

**Issue by antoniafuica** [IIC2233/syllabus#257]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo una pregunta cuando el barco quiere salir del canal. Por que este no podría salir del canal si ya se desplazo el largo del canal?

**Comment by DomingoCarvajal** [comment]
Hola @antoniafuica!

El barco debería poder salir del canal una vez se haya desplazado el largo de este. Si es que viste en el enunciado algo que dijera lo contrario me podrías decir en que parte?

**Comment by antoniafuica** [comment]
En la parte 4.2.3 Simular nueva hora. 
_"Una vez que un barco haya terminado de desplazarse, se debe verificar si este salió del canal. Cuando una embarcación termina de cruzar el canal, le paga a este el costo de uso de utilizar el canal. Por el contrario, por cada hora que un barco se mantenga en el canal, este último deberá pagarle al barco su costo de mantención, debido a costos logísticos y operacionales"___
Mi pregunta es porque razón el barco se mantendría en el canal, haciendo que el canal le pague por hora al barco

**Comment by DomingoCarvajal** [comment]
Ahora te entiendo!

Los barcos a los que se refiere esa frase son los barcos que todavía no han llegado hasta el final del canal. Mientras los barcos están avanzando por el canal, o detenidos en él, cobrarán un costo de mantención, pero una vez que llegan al final del canal ya no cobrarán ese costo.

Espero haya quedado claro!
