### ISSUE TITLE
Duda sobre atributo de probabilidad de encallar

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#258]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### No se bien como definir el atributo "probabilidad de encallar"

Hola, tengo la modelación de mis barcos casi lista, pero me surgen dudas al momento de tener que implementar ese
atributo, el calculo de ese valor depende de la dificultad del canal, que será un atributo del canal, por eso, no entiendo
bien como un barco podría acceder al atributo de una instancia de canal.

Al menos a mi me hace mas sentido implementar eso como un metodo, pero ya que el enunciado dice que
esas deben ser características mínimas no se si puedo hacer ese cambio libremente.

**Comment by sperezmasri** [comment]
Hola @Pabloski100. Lo que se pide con respecto a esto es que modeles la acción **Encallar**, de manera que en cada hora que un barco este en el canal, pueda "encallarse", lo que va a depender de la probabilidad definida en el enunciado. Efectivamente puedes utilizar un método para modelar esto, pero este método tiene que ser propio de la entidad **Barco**, ya que así es como esta definido en el enunciado.

**Comment by Rerro-r** [comment]
Hola! ¿**tendencia a encallar** podría ser atributo de clase y no de instacia? o eso trasgrede los límites de la tarea?

**Comment by sperezmasri** [comment]
Hola @Rerro-r! Efectivamente **tendencia a encallar** puede ser un atributo de clase. Esto implícitamente hace que todas las instancias de esa clase también tengan ese atributo al ser instanciadas. Si te queda alguna duda escríbeme, saludos! 😄

**Comment by Benyo27** [comment]
Hola ¿los atributos de clase van en el diagrama de clases igual?

**Comment by sperezmasri** [comment]
Hola @Benyo27! En el diagrama de clases no se diferencia entre atributo de clase y atributo de instancia. **Todos** los atributos **deben** ir en el diagrama. Saludos!
