### ISSUE TITLE
QThreads

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#258]
Busque en Internet y no pude encontrar la forma de que las hacer QThread.start(arg), es decir entregarle un argumento a la función start().(trate de usar directamente la función pero el programa se quedaba pegado. La única solución que encontré fue definir el argumento arg como un atributo de la instancia, pero eso me lleva a trabar con programación circular. hay alguna otra manera de solucionarlo?

**Comment by StroveLight** [comment]
No se si te sirva, pero lo que yo hice fue crear otra funcion que guardase los argumentos en el self, y luego realizaba self.start() desde esa funcion, y luego usaba los atributos guardados en el self

**Comment by roberto009** [comment]
Hola!
Al igual que los *Threads* de la librería *threading*, no es posible agregarle argumentos al método `start()`.
Recuerda que cuando usas `supuesto_thread.start()` se llama al método `run()` de la clase. 
Si es que estas haciendo que una clase herede de *QThread* lo más fácil es agregarle los parametros  que necesitas al `__inint__` de esa clase y luego llamarlos en el método `run()` como  `self.parametro`.

Espero que eso solucione tu problema.
Éxito en la tarea 😃
