### ISSUE TITLE
tamaño de las columnas

### ISSUE THREAD

**Issue by feliperojas123** [IIC2233/syllabus#258]
sucede que le puse 30 a las columnas para ver como printeaba la funcion tablero que nos dieron... y sucede que al pasar de los 26.. ya no tira ninguna letra mas... por ende el numero de columnas debe ser <= 26??

**Comment by DCCollao** [comment]
Hola @feliperojas123
Del enunciado:
![image](https://user-images.githubusercontent.com/37167447/91609476-80bb5f80-e945-11ea-99c4-9ff927cc457a.png)
Además, esto fue tratado en la issue #150. Si tienes una duda adicional, hazla como comentario dentro de esa issue.
