### ISSUE TITLE
rect() no me reconoce la posicion de los qlabels 

### ISSUE THREAD

**Issue by clementestreeter** [IIC2233/Syllabus#258]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ]X Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ]X De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! 
Estaba en el discord de la ayudantía hace un rato y me dijeron que preguntara mi duda por aquí.
Mi problema es que tengo dos widgets pero el rect de estos me aparece que siempre esta en la posición (0,0,algo) cuando en realidad estos se mueven y nunca están en esas coordenadas. Saben que puede estar ocasionando esto?
Muchas gracias!!

**Comment by tqmbanados** [comment]
Lo logré! Tuve que jugar un poco con tu código, y me acordé de cual era el problema (una vez más disculpa por no haber cachado antes, sabía que sería algo muy chico y efectivamente lo era).

Bueno, básicamente, los `QWidgets` tienen dos métodos para retornar un `QRect`:
1. `rect()`: el que usas tu, que retorna un rectangulo genérico, en posición (0,0), pero con las dimensiones del widget.
2. `geometry()`: el que deberías usar, que retorna el **rectángulo real del widget**, con la posición incluida. 

Básicamente, donde dice `rect`, debe decir `geometry`. Espero que se entienda el motivo de esto, y no lo copies solamente!

**Comment by clementestreeter** [comment]
Entendí perfecto!!!! Muchísimas gracias por la ayuda!!!!
