### ISSUE TITLE
Instancia torneo en menú (bonus de 3 décimas)

### ISSUE THREAD

**Issue by Fopazov** [IIC2233/Syllabus#258]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. Tengo una duda con respecto a la instancia que se estaría manejando en el menu. Estoy tratando de optar a las decimas del bonus (guardar multiples torneos). Tengo entendido que no se puede usar una variable global para definir la instancia a manejar (cosa que me serviria). Si hago esto, ¿cuanto sería el descuento si la defino (UNA variable global)? 

- Lo otro que se me ocurrio fue crear un menu 'principal' especificado para partidas ya iniciadas. En este caso esa funcion recibiria un torneo instanciado. ¿Esto se puede hacer? ¿O solo se permiten crear los menús del enunciado?

**Comment by Benjeeeh** [comment]
Hola!
Por lo primero, el uso de una variable global podría llevar el descuento de 1 décima o incluso 2, pero también existe la posibilidad de que se anule el bonus por implementarlo a través de una mala práctica, lo cual no es lo que uno espera, sería como 'hacer trampa', por lo que podría no convenir demasiado. 
De lo último, no sería válido ya que se espera que se añada la opción de guardar partida dentro del menú principal y que se pueda cargar desde el menú de inicio, lo que ambos casos corresponden a modificaciones de menús y no creaciones de nuevos menús.
Lo que si puedes realizar es creación de una clase o una función específica que se encargue de recabar la información necesaria para guardarlas en distintos archivos.

Éxito con la implementación del bonus!!

**Comment by Fopazov** [comment]
Vale, se entiende. ¡Gracias!
