### ISSUE TITLE
Empate

### ISSUE THREAD

**Issue by cataruze** [IIC2233/Syllabus#258]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Holaaa, en los combates que pasa si hay un empate en una ronda? Esto puede pasar? Y si es así la cuento como ronda ganada o perdida?

Muchas gracias de antemano.

**Comment by wintermelyn** [comment]
Hola @cataruze!

> En los combates que pasa si hay un empate en una ronda? Esto puede pasar?

Como los ataques de cada enfrentamiento ocurren **al mismo tiempo** si puede darse el caso de un empate! esto ocurre si los últimos 2 combatientes de cada ejercito se eliminan entre ellos.

> Y si es así la cuento como ronda ganada o perdida?

El enunciado solo especifica que "Ganarás el juego si logras completar 3 rondas de combate. Al contrario, si todos tus gatos son eliminados, perderás el juego y deberás volver a comenzar desde la primera ronda.". Por lo tanto si empatas en cualquier ronda que no sea la 3° puedes considerarlo como un GAME OVER (reiniciando el juego desde la primera ronda) pues todos tus gatos fueron derrotados.

Como el caso particular en el que empatas la 3° ronda (~es decir derrotas a gatochico pero mueres en el intento 😔~) es un caso borde no tratado por el enunciado puedes modelarlo como prefieras, pero recuerda mencionarlo en tu README.md
