### ISSUE TITLE
Aclaracion uso parametros.py

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#258]
Hola!
No entiendo qué tiene que ir en el módulo "parametros.py".
Cuando se menciona que debemos poner "todos los parámetros mencionados anteriormente" se refiere a los archivos "csv" , a los menús y a las entidades ?
Tampoco entiendo lo que esta prohibido hacer en éste módulo.
no entiendo la oración " Cualquier uso del archivo parametros.py que no sea vinculado al almacenamiento de parámetros implicará un descuento en tu nota. Finalmente, cualquier parámetro que se encuentre hardcodeado dentro de tu cádigo, tambián conllevaría a un descuento." Podrían ser un poco mas específicos por favor, darnos un ejemplo sería una buena idea :smile: 
Gracias :ok_hand:

**Comment by mpsubiabre** [comment]
Hola @Camila-sty!

Tratare de explicarte lo mejor psible una por una tus dudas.
1) En el módulo "parámetros.py" tienen que ir todos los valores que permanecerán constantes al momento de ejecutar tu código, como lo son, por ejemplo, la probabilidad asociada a que una criatura se escape, o la cantidad de Sickles iniciales. La utilidad de esto, es que cuando escribas tu código, en vez de escribir la constante que representa, escribas la variable que lo contiene (el parámetro). Así, si deseas cambiar algún valor, no tengas que buscar en el código todas las veces que fue usado, sino con tan solo cambiar el valor de este parámetro bastará. 

2) Cuando se dice "todos los parámetros mencionados anteriormente", hace referencia a los datos que permanecerán constantes, como lo por ejemplo el efecto de salud de algún alimento, podrás notar que estarán pintados en azul.

3) Cuando dice " Cualquier uso del archivo parametros.py que no sea vinculado al almacenamiento de parámetros", quiere decir que en ese archivo deben ir única y exclusivamente parámetros, no se deben escribir clases, ni funciones.

4) Cuando se dice "cualquier parámetro que se encuentre hardcodeado dentro de tu código", hace referencia a que, además de definir los parámetros, debes hacer uso de ellos. No utilizar constantes cuando debería ir el parámetro definido para esa constante.

Espero haber aclarado tus dudas, de lo contrario comenta esta issue :)

**Comment by Camila-sty** [comment]
Entiendo...
Ahora con respectos a los path.
- Puedo guardar los datos que cada arvicho "csv" tiene, para ser utilizados en otro módulo?, Si es así, puedo generar una simple lista con los datos de cada archivo? o debo definir cada parámetro? como por ejemplo [Camila,21,chilena]:
nombre = Camila
Edad = 21
Nacionalidad = chilena
Debe ser así? o basta con definir un parámetro que sólo contenga la lista de datos?
- Mis archivos "csv" sólo debo abrirlo en este módulo parametros.py ?
- Si quiero editar un archivo "csv", también debo hacerlo en el módulo parametros.py ?, o solo basta que éste módulo guarde sus datos?

**Comment by mpsubiabre** [comment]
Sobre el tema de los path, este hace referencia únicamente a la ruta en la que se encuentran los archivos. Esto permite que, si otra persona corre tu código en otro computador, el cual tiene los archivos .csv en otra carpeta, bastara con cambiar el parámetro PATH respectivo. (Por ejemplo PATH_CRIATURAS = "archivos/criaturas.csv")

Los datos de los archivos.csv no entrarían en la clasificación de parámetro, ya que no son datos que se mantienen constantes durante toda la ejecución del código. Si deseas guardarlos para usarlos posteriormente no debe ser hecho en el modulo de parámetros, porque no entran en esa clasificación. Los parámetros son datos que se establecen antes de correr el código, y no cambian durante toda la ejecución.

El manejo de estos archivos, ya sea abrirlos o editarlos, la única relación que tiene con el archivo parametros.py es que usara el parámetro de la ruta del archivo (por ejemplo PATH_CRIATURAS). Esta ruta se mantiene constante durante toda la ejecución del código por eso es considerada parámetro.

Espero que te haya quedado claro :)

**Comment by Camila-sty** [comment]
Entendí perfecto todo, gracias! :smiley:
