### ISSUE TITLE
¿Qué pasa con las piezas removidas?

### ISSUE THREAD

**Issue by Regenschrim** [IIC2233/Syllabus#258]
Si un jugador decide remover una pieza en su turno, ¿esa pieza se pierde para siempre? ¿O se puede crear una EDD que contenga todas las piezas y que al removerla del tablero la devuelva a la EDD? Creo que no sale especificado en el enunciado.

**Comment by sebacruzd** [comment]
Hola,

Ten en cuenta que se pueden deshacer jugadas o moverse a través del historial al pasado.

Saludos!

**Comment by Regenschrim** [comment]
Aaaaah entiendo, gracias! :D
