### ISSUE TITLE
Agregar parámetros

### ISSUE THREAD

**Issue by sunrayito** [IIC2233/Syllabus#259]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Me gustaría saber si todos los parámetros que agrego deben estar en parámetros.py. Se pide que los que están por enunciado estén en ese archivo, sin embargo me gustaría añadir más parámetros, pero no sé si tienen que estar necesariamente en ese archivo.

**Comment by augustayanez** [comment]
Te recomiendo ver la issue #252 donde se habla sobre el contenido de parametros.py, cuales variables corresponden a este y cuales no.

**Comment by sunrayito** [comment]
> Te recomiendo ver la issue #252 donde se habla sobre el contenido de parametros.py, cuales variables corresponden a este y cuales no.

Me refería a si quiero crear otra variable que se mantiene constante pero que no está definida por enunciado como parámetro tengo que agregarla en parámetros.py o puedo agregarla en otro archivo.
Por ejemplo si quisiera mantener como constante las vidas iniciales de las plantas debo definirlas en parámetros o puedo definirlas en otra parte para mejor organización (el enunciado no menciona que deba definir esa variable). 
El otro issue se refería a si puede agregar algo no constante al archivo de parámetros, sin embargo mi pregunta es si puedo definir algo constante que no es obligatorio por el enunciado en otro archivo. Espero que se haya entendido.
