### ISSUE TITLE
Clases abstractas en Diagrama de clases

### ISSUE THREAD

**Issue by drosselot** [IIC2233/syllabus#259]
Hola, quería saber como debo representar los métodos abstractos en el diagrama de flujos. ¿Debo ponerlo en la clase padre y las subclases? Saludos.

**Comment by aljara97** [comment]
Hola @drosselot, no es necesario que los métodos y/o atributos de la clase padre estén representados en las clases que heredan de esta. Se da a entender que las posee con la relación correspondiente. Si deseas apoyarte más en esto, puedes ver la sección de contenidos del curso.

Mucha suerte 🧙‍♂️

**Comment by drosselot** [comment]
Vale, gracias
