### ISSUE TITLE
Atributos excavadores .csv

### ISSUE THREAD

**Issue by Fopazov** [IIC2233/Syllabus#259]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el archivo .csv algunos excavadores tienen atributos con valor 0. Cosa que contradice el enunciado ya que todos (ej: suerte) van de 1 a 10. ¿Puedo cambiar el archivo csv? Si no cambio la suerte (no se usa el setter en el program), puede que en la ejecucion algunos excavadores tengan suerte = 0. Cosa que supongo que está mal.

**Comment by Benjeeeh** [comment]
Hola! Efectivamente se trata de un error, te recomiendo revisar la issue #233 que habla de esto, pero si puedes editar los valores que sean iguales a 0 por uno dentro del rango indicado.

Éxito con la tarea!!

**Comment by Fopazov** [comment]
Vale! No había visto la issue. ¡Gracias!
