### ISSUE TITLE
leer el archivo pieces.csv y pieces_name.csv desde demo.py

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#259]
Hola! Puedo yo desde demo.py leer directamente los archivos pieces.csv y pieces_name.csv o solamente puedo interactuar con los métodos de la gui y nada mas?

**Comment by iqacevedo** [comment]
Hola,

Si puedes, solo preocúpate de tener una buena modularización de tu código (¿Tiene sentido que se lean csv en el módulo que interactúa con la interfaz? ).

Recuerda que lo único que no puedes hacer es acceder a métodos de la gui que no estén en el enunciado y en la issue en el que se agrego uno.

Saludos !

**Comment by bedefrunner** [comment]
Gracias! Y puedo agregarle métodos a demo.py?

**Comment by iqacevedo** [comment]
Si puedes, solo preocúpate de que tenga sentido que estén ahí y no en otro lugar, para que tengas un buen código.

Saludos !
