### ISSUE TITLE
Duda enunciado 3.2 Niveles y dificultad

### ISSUE THREAD

**Issue by Jeremiah-PHP6** [IIC2233/Syllabus#259]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
En la parte final del párrafo, si un usuario completó el tercer nivel, al volver a jugar no debería partir desde el cuarto (y no primero)?
![image](https://github.com/IIC2233/Syllabus/assets/101214501/25973b57-9768-4e4b-b8d9-d9af0d6d7fbf)

**Comment by AntonioVenegas** [comment]
Hola @Jeremiah-PHP6!, en el juego solo hay tres niveles, por lo que si el usuario llega al tercer nivel, el juego se termina y se guarda su nombre y puntaje (y se espera que el jugador salga del programa con el botón salir o cerrando la ventana). Saludos :)
