### ISSUE TITLE
[General] Uso de variables globales

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#259]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### En qué casos es legal el uso de variables globales, cuenta por ejemplo para los parámetros que no se modificarán y serán iguales para todos los objetos? O siempre el global será _frowned upon?_

**Comment by fernandosmither** [comment]
(Paréntesis, sí leí al final del documento de issues sobre la tarea que se puede globales para los parámetros, pero solo para confirmar, esto significa que recomiendan comenzar los inicializadores con unos ``global x`` ?

**Comment by Emiliax16** [comment]
Hola! como aparece en el el documento de la T1, apartado **malas práticas** el uso de variables globales (global x) implicaría un descuento en tu tarea. Para usar variables en varios módulos, están los parámetros, los cuales deben contener valores constantes.

**Comment by fernandosmither** [comment]
> Hola! como aparece en el el documento de la T1, apartado **malas práticas** el uso de variables globales (global x) implicaría un descuento en tu tarea. Para usar variables en varios módulos, están los parámetros, los cuales deben contener valores constantes.

Claro, entiendo esto, sin embargo en una hipotética implementación, yo leería solamente 1 vez el archivo de parámetros, guardaría estos en unas variables, y luego en cada función comenzaría con (global variable_global), o quieren que abramos el archivo de parámetros cada vez que creemos un módulo?

**Comment by fernandosmither** [comment]
Gracias! entendido

**Comment by Rerro-r** [comment]
Hola! Para los parámetros entonces sólo bastaría con importarlos de `parametros` y usarlos, ¿cierto?

**Comment by Emiliax16** [comment]
Exactamente, cuida de importarlos al principio de los módulos para que no tengas descuentos por malas prácticas.

**Comment by Pabloski100** [comment]
Hola, me surgió una duda respecto a este tema, por ejemplo, si en la simulación cargo bases de datos y los dejo almacenados en variables, se consideran variables globales? si bien estarían en el scope global del programa, el como se arman las bases de datos dependen de los parámetros, así que no estaría "hardcodeado"

**Comment by Emiliax16** [comment]
Hola! cargar los archivos y guardarlos en variables no sería una variable global, por lo que puedes hacerlo sin problemas.
