### ISSUE TITLE
Duda sobre QTimer y su función STOP

### ISSUE THREAD

**Issue by simonmb12** [IIC2233/Syllabus#259]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! tengo un QTimer que funciona en intervalos de 10 segundos, y le aplico un stop en el segundo 5, y luego lo vuelvo a iniciar (Start), el QTiimer va a volar a contar 10 segundos para activar la función a la que está conectado, o contará desde el segundo 5 en el que se le aplico el stop anterior??

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by sebaguerrap** [comment]
Hola @simonmb12 ! De lo que pude encontrar en la documentación de Qt, al utilizar start siempre parte con la cantidad de segundos asignados al intervalo del timer (en tu caso 10 segundos), sin importar cuando se pausó. De todas formas si quieres asegurarte de que tenga X tiempo restante al reiniciarlo, antes de hacerlo haz setInterval(X).
