### ISSUE TITLE
Sprites y movimiento

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus#259]
Se pueden cambiar los sprites del personaje principal? Me molesta que no esten en la misma resolucion todos los sprites. Y se de que juego son los sprites especificamente, pero tendria que cambiarlos por los de un pokemon y no los de un humano. Puedo hacer eso? Y tambien con los otros sprites si quisiera?

Ademas de eso, pueden los personajes caminar en diagonal? Lo digo porque por defecto el personaje principal no tiene sprite de caminar en diagonal... Solo los pokemones.

**Comment by gatochico** [comment]
Hola! Puedes cambiar cualquier sprite que quieras por alguno propio, siempre y cuando recuerdes subir los sprites nuevos a tu repositorio (e incluyas cualquier archivo que dimos desde un inicio en tu .gitignore).

Con respecto al movimiento diagonal, puedes asumir que el personaje principal solo debe moverse en 4 direcciones, por lo que no necesitas un sprite de personaje en diagonal.

Saludos!

**Comment by Oisangui** [comment]
En lo personal hace poco terminé de recortar screenshots para implementar el juego totalmente como Age of Empires II, solo que con modificaciones para hacer que los gatos parezcan gatos, por ejemplo. Tengo todo ordenado en carpetas.
