### ISSUE TITLE
Duda con respecto al botón salir de la ventana de juego  y la ventana post Juego en ese caso

### ISSUE THREAD

**Issue by gabo1243** [IIC2233/Syllabus#259]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, con respecto al botón salir de Ventana de juego, en el enunciado dice que después de apretarlo te muestra la ventana Post-Juego. En ese caso, ¿Debería salir que perdiste? 
Por otro lado, al guardar puntajes: ¿Se debe reescribir el puntaje en caso de que haya alguien con el mismo nombre?

Gracias de antemano

**Comment by franco-anfossi** [comment]
El enunciado dice que cuando se presione el botón salir se debe volver a la pantalla de inicio

**Comment by gabo1243** [comment]
Hola, mi duda venía por lo  que aparece en la siguiente imagen:

<img width="1373" alt="Captura de Pantalla 2022-10-09 a la(s) 14 01 40" src="https://user-images.githubusercontent.com/105672974/194769938-59666873-955a-4c10-a4fb-216745b16fed.png">

Entonces, antes de volver al inicio (por botón salir) ¿se debe mostrar la ventana post-ronda o no?
Y, al guardar el puntaje, si hay otro nombre igual ¿Se reescribe con el último?

Gracias

**Comment by Lord-Kelsier** [comment]
Hola @gabo1243 .
Exacto, al salir se debe mostrar la ventana de post ronda y decir que perdiste ya que te has rendido. 
Con respecto a reescribir el nombre, esto queda a tu criterio, no es muy relevante.
