### ISSUE TITLE
Archivo .gitignore para carpeta contenidos del curso

### ISSUE THREAD

**Issue by ConiCollector** [IIC2233/syllabus#259]
Estimados
 
Seria posible que al archivo .gitignore de la carpeta contenidos le agregaran los comando para que no tome en cuenta los JupyterNotebook que se modificaron para el estudio en los computadores personales de cada uno, pues es molesto visualmente ver las letras en rojo sobre que un archivo no ha sido actualizado que aparecen cuando uno consulta con git status. Además, considero que puede crear confusiones.

Lineas de código 
### JupyterNotebook ###
.ipynb_checkpoints
*/.ipynb_checkpoints/*

Agradece y se despide 
Constanza Morales

**Comment by aaossa** [comment]
Hola @ConiCollector!

La verdad es una buena sugerencia, pero al parecer no es posible técnicamente (o no de una manera directa). Cuando un archivo ya es seguido por Git, aunque esté en el .gitignore seguirás viendo los cambios hechos. Las líneas que agregaste, ya son parte del .gitignore de los contenidos (puedes verlas [aquí](https://github.com/IIC2233/contenidos/blob/master/.gitignore#L14-L15)), y esos archivos no deberían aparecer al hacer `git status`. Lo que estás viendo en rojo, al parecer, son los cambios que haces al correr los Jupyter (puedes confirmar esto con el *output* de `git diff`).

De todas maneras, hay comandos de Git que pueden ser útiles tanto si te importa conservar los cambios que hagas como si no:

* **Si te interesa guardar los cambios**, antes de hacer `git pull` puedes hacer `git stash`. Esto toma los cambios locales que tengas, los "mete en un bolsillo" y así puedes hacer `git pull` sin problemas. Posteriormente, puedes volver a aplicar tus cambios locales con `git stash pop`. Entonces, cada vez que quieras bajar los contenidos puedes hacer: `git stash`, `git pull` y `git stash pop`, para actualizar tu repositorio sin perder tus cambios.

* **Si NO te interesa guardar los cambios**, puedes borrar todos tus cambios locales con solo un comando. Lo dejaré acá pero agrego la advertencia de que es peligroso, ya que es muy posible que estos cambios sean permantes: `git reset HEAD --hard`. Como recordatorio, si un comando tiene `--hard` afecta tus archivos locales (lo que podría borrarlos), mientras que si se usa `--soft` no cambia los archivos, evitando la pérdida de información (pero es el efecto contrario al que queremos lograr aquí). También, puedes usar `git stash` y nunca hacer `git stash pop`, pero yo lo siento menos... elegante (?)

Ojalá alguna de estas opciones te sea de ayuda (yo ocupo harto la primera opción), y que quienes lean esto hayan aprendido un poquito de Git ✨

**Comment by ConiCollector** [comment]
Estimado 

Por un lado, encontré otra linea que podría ser mejor en el uso para ignorar los cambios que se hacen en los repositorios locales de cada para que git bash no los detecte, la cual es la siguiente: 

.ipynb_checkpoints
*/.ipynb_checkpoints/*

Por otro lado, gracias por tu respuesta la cual fue muy completa y buen fin de semana
