### ISSUE TITLE
Configurar Pycharm para que use Python 3.5

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#26]
Hola!

Estoy teniendo problemas para configurar Pycharm para que use Python 3.5 y no 3.6. No se como cambiarlo, y en internet no encontré una solución.

Gracias!

**Comment by FernandoPieressa** [comment]
Hola, primero apretas editar configuraciones y te deberia aparecer una pantalla como esta:

![foto123](https://cloud.githubusercontent.com/assets/13782155/23827382/65bdee68-0691-11e7-8626-fe3b2b665f00.png)

Ahi donde sale Python Interpreter lo cambias a Python 3.5 y funcionara perfecto. Eso si, recuerda que necesitas tener instalado python 3.5 para poder ponerlo como interprete.

Saludos!

**Comment by akaminetzkyp** [comment]
Perfecto! Había hecho algo parecido, pero no me aparecía Python 3.5. Lo instalé desde esta [página]( https://www.python.org/downloads/release/python-353/). Ahora aparece en la lista pero sale como "invalid".

<img width="1031" alt="screen shot 2017-03-11 at 7 40 38 pm" src="https://cloud.githubusercontent.com/assets/11022568/23827470/dccf780e-0692-11e7-9412-e671d304010d.png">
