### ISSUE TITLE
Duda en agregar usuario en usuario.csv

### ISSUE THREAD

**Issue by rominaansaldo** [IIC2233/Syllabus#26]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Duda en agregar usuario en usuario.csv

Hola! Tengo la duda de si es que al agregar un usuario o registrar un nuevo usuario es necesario agregarlo al csv de usuario o simplemente lo podemos agregar al built-in que usamos para procesar los datos de ese csv. Espero que se entienda la pregunta :)

**Comment by fffonceca** [comment]
Hola @rominaansaldo , creo que da lo mismo siempre y cuando quede guardado ese respaldo al cerrar el programa o al tratar de iniciar nuevamente el usuario al volver al menú de inicio. Es decir, si creas la cuenta y cierras el programa inmediatamente, debería de estar en el archivo `usuarios.csv`

Así lo intepreté yo, quizás un ayudante podría complementar el raciocinio.

@ayudantesIIC2233Bot

**Comment by Emiliax16** [comment]
Hola! @rominaansaldo @fffonceca la idea es que al registrar un nuevo usuario, si o si lo guardes en el archivo `usuarios.csv`. La actualización de este archivo se debe ver en cualquiera de las otras opciones de los menús. Por ejemplo, si registrar a Pepita (y compruebas que cumpla con los requerimientos mínimos), Pepita debe estar en `usuarios.csv` para que pueda ingresar encomiendas y estas puedan ser visualizadas por el admin, todo dentro del mismo flujo de programa. Saludos!
