### ISSUE TITLE
Vida soldados y magos

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#26]
Dentro de un ejército, todos los soldados tienen la misma cantidad de vida? De ser así, pasa lo mismo con los magos?

**Comment by Arcoirisky** [comment]
Hola!
Si te fijas bien en el enunciado dice

"Tanto el ataque como la vida de los soldados y magos está definida como un número aleatorio, que distribuye de forma uniforme dentro de un rango. Este rango depende exclusivamente de cada raza." Sección Raza, párrafo 2.

¿Responde a tu pregunta? o:!

**Comment by llloyola** [comment]
No :(
Entiendo que la vida es un número aleatorio de distribuye de manera uniforme, pero mi duda es si, dentro de un ejército, cada soldado tendrá por vida un número aleatorio distinto o si todos los soldados del ejército tendrán el mismo número aleatorio por vida.

**Comment by Arcoirisky** [comment]
cada soldado es único dentro de cada ejercito. Sea soldado o mago c:

**Comment by llloyola** [comment]
Entonces la cantidad de vida entre los soldados es independiente entre sí, no? Creo que entendí. Gracias! :)

**Comment by Arcoirisky** [comment]
Exacto :) Ánimo y suerte!!!

**Comment by AlexanderBarrera** [comment]
Hola, sigo con una duda, en el punto 7, para calcular los sobrevivientes de la batalla, la "vida de un soldado" y la "vida de un mago" hacen referencia a un promedio de la vida de los soldados/magos que se tenga, o es solo el numero aleatoreo dentro de los rangos correspondientes?

**Comment by Arcoirisky** [comment]
Hola! 
Para el cálculo de sobrevivientes, no quedó especificado qué vida de soldado usar. Eso queda a tu criterio :D Puede ser el promedio, un nuevo random. Lo importante es que de mantenga con sentido, no pueden sobrevivir más soldados de los que habían inicialmente.

**Comment by auirarrazaval** [comment]
Hola, al respecto, el ataque de un soldado o mago tambien seria inherente de cada "individuo" cierto?

**Comment by Hernan4444** [comment]
Una vez que se crea un soldado, este genera un ataque según el rango adecuado y se mantiene durante toda la ejecución del juego en dicha galaxia. Ese ataque sólo se verá modificado si es que el soldado sobrevivió la conquista de un planeta. En resumen, es inherente a cada individuo y no cambia en cada ataque.
