### ISSUE TITLE
No aparece el repositorio personal en la pagina

### ISSUE THREAD

**Issue by Jpdelaf** [IIC2233/Syllabus#26]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema
hoy durante la clase me di cuenta de que en mi pagina no aparece mi repositorio personal. de lo que tengo entendido este se creaba luego de responder el forms del mail, El cual yo si me acuerdo de haber contestado, pero nunca me llego un mail en el que se me indicara la creación del repositorio. 
no se si debería ver responder nuevamente el forms o que debería hacer.

**Comment by lily416** [comment]
Hola @Jpdelaf

Espero que te encuentres bien 😄. En cuanto a tu duda, revisando las respuestas del [formulario de inscripción](https://forms.gle/7nWDjic7qb96etWt6) no aparece ninguna respuesta con tu usuario de Github. El formulario está programado para que les llegue un correo con sus respuestas cuando envíen la respuesta, por lo que revisa tu correo para ver si te enviaste correctamente el formulario, en caso contrario, deberás responderlo nuevamente. Una vez respondido, te deberá llegar la respuesta del formulario y una invitación a tu repositorio de Github. 

Ojalá pronto tengas acceso a tu repositorio privado. Saludos 👋🐢
