### ISSUE TITLE
Duda tareas atrasadas

### ISSUE THREAD

**Issue by emilianomm** [IIC2233/syllabus#26]
Hola, quería saber que pasa en el caso de que haga un push en mi carpeta de tarea después de la hora limite sin la intención de que este sea corregido, ya sea por error o por querer agregar algo extra, es decir, que estoy satisfecho con la ultima entrega dentro del plazo y no quiero que la mas reciente sea considerada. ¿De todas maneras me descontaran por atraso?

Saludos

**Comment by lily416** [comment]
Cuando se acabe el plazo para entregar la tarea (en este caso el sábado a las 20:00 hrs) se recolectarán automáticamente todas las tareas. Para aquellos que quieran entregar atrasado, deberán rellenar un _form_ (que les mandaremos por mail) con el _commit_ a corregir. Por lo que no se realizará el descuento por atraso si subes cambios a tu repositorio **mientras** no respondas el _form_.

Saludos y éxito con la tarea. 👋🍀
