### ISSUE TITLE
Duda respecto a la utilización de match

### ISSUE THREAD

**Issue by panchouc** [IIC2233/Syllabus#26]
¡Hola!.
Tengo una duda si se puede usar una de las nuevas cosas que viene implementada en Python 3.10, que es el tema de `match`. Si bien no lo hemos visto en el curso, quería saber si lo puedo ocupar de todas maneras, ya que encuentro que queda más limpio que las sentencias if, elif y todo eso.

Por ejemplo, en vez de:

```python
a: str = input("Ingresa un número")
if a == "1":
    # Hacer algo

elif a == "2":
    # Hacer otras cosas
```
Puedo utilizar
```python
a: str = input("Ingresa un número")

match a:
    case "1":
        # Hacer algo
    case "2":
        # Hacer otras cosas
```
De antemano muchas gracias por la respuesta, saludos!

**Comment by Juampisaez** [comment]
Hola @panchouc 
Si, puedes ocupar estas herramientas que te permite la versión de `Python 3.10` que les decimos que utilicen.

Quedo atento a cualquier otra duda :)

**Comment by panchouc** [comment]
Oka! Gracias nuevamente juampi (sorry si he preguntado mucho :c)
