### ISSUE TITLE
Duda usuario github autoevaluación

### ISSUE THREAD

**Issue by bpardobravo** [IIC2233/syllabus#26]
Al llenar el campo "usuario github" en la autoevaluación con mi usuario, me sale el error "no es el mail uc". Se supone que debisémos poner el mail de nuestra cuenta github o está mal formateado?

**Comment by Oisangui** [comment]
A mí no me deja entrar con ninguna combinación de palabras clave.

**Comment by jotanavarrete** [comment]
A mí me sale "No debe contener" en ambos campos, al ingresar usuario UC y usuario Github.

**Comment by jearaneda** [comment]
Me sale 'Must not contain' sin importar lo que ponga

**Comment by IngisRedd** [comment]
Prueba con añadir una arroba: "@" antes de tu usuario de github. Ej: @IngisRedd

**Comment by entamburini** [comment]
Hola! :)

Fue un error al crear el form. Ahora deberian ser capaces de rellenarlo sin problemas :D

En usuario UC deben poner lo que está antes del @uc.cl (pej: pepinazo@uc.cl -> pepinazo)

En usuario GitHub ya saben qué hacer :)
