### ISSUE TITLE
 Revisar quienes siguen por parte del usuario

### ISSUE THREAD

**Issue by Pflagos** [IIC2233/syllabus#26]
Hola buenas tardes, en el enunciado no encontré una sección en la que se especifique que el usuario sea capaz de ver a los usuarios que lo siguen, ¿es necesario que vea a quienes lo están siguiendo?

**Comment by jeschuwirth** [comment]
Hola @Pflagos,

No es necesario que el usuario sepa quienes o cuantos usuarios lo siguen, por lo tanto no es necesario que lo agregues a tu tarea. De todos modos, si lo quieres agregar no es problema :)

Suerte!

**Comment by Pflagos** [comment]
muchas gracias
