### ISSUE TITLE
Existencia de archivo con path

### ISSUE THREAD

**Issue by blampasona18** [IIC2233/Syllabus#26]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, leí el adjunto de la librería os y logré comprender como saber si un archivo existe o no (si su path es válido o no). Pero lo estoy probando con paths de mi computador. Intenté poner un path relativo desde el nombre de mi repositorio en adelante y me retorna False. Mi pregunta es **Al recibir el input con el nombre del archivo, cuál es el path que debo verificar si existe o no?**

**Comment by Hernan4444** [comment]
Hola,

Lo esperado que es la tarea funciones estando desde la carpeta `T0/`. Por lo tanto, lo esperado es  ejecutar los archivos asumiendo que estamos parados (el workspace) sea la carpeta T0 y usar rutas relativas consistentes a que ejecutaremos todo estando dentro de la T0.

Aquí recomiendo revisar los contenidos de la semana 0, en especial los de terminal. Ahí se explica un poco el tema de ejecutar un archivo desde determinada carpeta junto con el tema de los paths a utilizar.

Si quedas con más dudas, estaremos atentos a las _issues_
Saludos c:

**Comment by 00nrs** [comment]
Hola @Hernan4444, entonces podemos asumir que los archivos que ustedes ingresen estarán dentro de la carpeta "Archivos"? Mi pregunta va a que, por ejemplo, si ingresan un archivo que existe pero **fuera** de la carpeta "Archivos", mi programa debería cerrarse cierto? ¿Y lo mismo si ingresan un archivo que no existe dentro de la carpeta, pero si a fuera de ella?

**Comment by Hernan4444** [comment]
Hola @00nrs 

Efectivamente. Los archivos que podemos hablar desde la consola son unicamente aquellos dentro de la carpeta Archivos. Si hay otro tablero fuera de esa carpeta, para tu programa no existe ese tablero.

Saludos c:
