### ISSUE TITLE
Error Test publicos (estudio_genero) AC1

### ISSUE THREAD

**Issue by nachotagle** [IIC2233/Syllabus#26]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Hola! Tengo una duda sobre el ultimo **test publico de la AC1**, el test_consulta_estudio_genero. El problema que me sale al correr los test, es que en cada test donde piden que la lista entregada que esperan, los nombres de **los estudios parten con minúscula**, mientras que en las listas de los animes que nos entregan los nombres de los estudios están escritos **con mayúscula**, como 'Shonen' o 'Nippon_Animation', y de hecho en lo esperado en el enunciado esta la lista escrita así, con la mayúscula ['Nippon_Animation].
Fui a revisar el archivo de los test, y efectivamente la respuesta esperada en los test es una lista con los nombres de los estudios con minúscula, como ["sunrise", "ghibli"], y como menciones antes, nos entregan la lista con los nombres com mayúscula.

**No sé si esperan que cambiemos los nombres a minúsculas para entregarlos**, o es un **error en la respuesta esperada**. También no sé si cambiarlo porque quizás en los test privados si están correctas las respuestas esperadas.

* En este test se logra apreciar la respuesta esperada con minúsculas.
![image](https://github.com/user-attachments/assets/a97ce943-023a-42b8-ab36-c8050da3a8da)

Gracias!!

**Comment by Hernan4444** [comment]
Hola @nachotagle 

Tanto el tests como lo pedido está correcto. Lo que pasa es que dicha función tiene algo en particular relacionado con el operador `**`. Recomiendo ver con mucho detalle el segundo párrafo de dicha función en el enunciado, donde se indica el elemento específico a utilizar para crear la lista de estudios ( _hint_: el nombre de cada estudio lo recibes 2 veces, en el operador `**` y dentro de la nametupled... ¿cuál es la diferencia de ambos? )


Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ
