### ISSUE TITLE
Problema con jupyter notebook en sistema macOS

### ISSUE THREAD

**Issue by fcbahamondes** [IIC2233/syllabus#26]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema
Hola, durante la semana tuve problemas para abrir un jupyter notebook en mi computador, al momento de instalarlo me aparece que el proceso fue exitoso, pero al intentar abrir alguno de las actividades me aparece que el comando no existe. 

<img width="324" alt="Captura de pantalla 2021-03-23 a las 15 03 41" src="https://user-images.githubusercontent.com/80771151/112196218-934efc00-8be9-11eb-9aba-3a8e19aee4ca.png">

<img width="541" alt="Captura de pantalla 2021-03-23 a las 15 03 55" src="https://user-images.githubusercontent.com/80771151/112196286-a2ce4500-8be9-11eb-9421-d763f682eea7.png">

### Mi duda es que, no se cual es el error. He buscado en internet y hoy un ayudante intento buscarlo, pero no fue satisfactorio.

**Comment by dfloreaa** [comment]
Hola!

Si bien no tengo un computador Mac, encontre [este hilo](https://github.com/jupyter/help/issues/317) en la página de GitHub de Jupyter en donde alguien tiene un error similar al tuyo.

Por lo que uno de los usuarios informa, puede ser porque jupyter se está instalando en la versión de Python 2.7 que viene por defecto en los Mac, te recomiendo intentar instalarlo mediante ``pip3 install jupyter`` o bien ``python3 -m pip install jupyter``

En caso contrario, intenta instalarlo con ``brew`` usando el comando: ``brew install jupyter``, aparentemente eso le funcionó a quien hizo la pregunta en primer lugar.

Avísame como te va! ☺🦝

**Comment by fcbahamondes** [comment]
No me funciono pip3 install jupyter ni python3 -m pip install jupyter. Al intentar ocupar el brew install jupyter, no me reconocía el comando brew, buscando en internet decía que era necesario descargar homebrew en la consola. Descarge homebrew, y me funciono jupyter notebook sin ocupar la linea brew install jupyter, no se cual fue la logica, pero ya puedo abrirlo!!! gracias por el dato.

**Comment by dfloreaa** [comment]
Me alegro que terminó funcionando ☺, un saludo!
