### ISSUE TITLE
Validación de acciones por parte del servidor

### ISSUE THREAD

**Issue by vichoassadi** [IIC2233/Syllabus#260]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!

Una consulta sobre la validación de las acciones del cliente, por parte del servidor. En el enunciado dice que toda acción realizada por el cliente debe ser validada por el servidor. En ese caso, acciones como la posición del conejo, moverse en alguna dirección, perder una vida, etc., o validar que el nombre del usuario cumpla los requisitos de largo, mayúscula y número, ¿También tienen que ser validadas por el servidor? ¿O son solamente acciones relacionadas con puntaje y pasar de nivel?

Muchas gracias.

**Comment by AntonioVenegas** [comment]
Hola @vichoassadi, el  servidor solo verifica que el nombre de usuario no este en la lista de usuarios bloqueados, mientras que el backend del cliente puede revisar que el nombre cumpla las condiciones (especificadas en el enunciado 6.2.1). Además, el servidor se debe encargar de validar los inputs del cliente. Por ejemplo, si el jugador quiere moverse hacia arriba pero hay una pared, el jugador envía el movimiento al servidor y este verifica que es invalido, por lo que el jugador no se mueve (no se actualiza el cliente).
Saludos! :)

**Comment by pacalein** [comment]
Hola! Contrario a la respuesta anterior: Lo especificado en **7.2 Roles**  es lo único que debe ser validado por el servidor. Es decir: información de nivel completado y el nombre de usuario. Las acciones de movimiento, cambios en el tablero o inputs de teclado no deben enviarse al servidor.

**Comment by Joako5848** [comment]
> Hola! Contrario a la respuesta anterior: Lo especificado en **7.2 Roles** es lo único que debe ser validado por el servidor. Es decir: información de nivel completado y el nombre de usuario. Las acciones de movimiento, cambios en el tablero o inputs de teclado no deben enviarse al servidor.

Eso significa que la función de la etapa intermedia "validación_formato" no sirve? pues es para el cliente y el enunciado dice que las validaciones son en el server
