### ISSUE TITLE
Duda sobre crear funciones externas.

### ISSUE THREAD

**Issue by armas01** [IIC2233/Syllabus#260]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Quisiera saber si puedo crear funciones externas que reciban de parametro un self para permitir que mi código de logica_juego no pase las 400 líneas. Por ejemplo, tengo una funcion llamada instanciar_timers(self) que crea todos los timers, pero es una funcion EXTERNA de la clase y recibe de parámetro el SELF. Esto se considera mala práctica? o está permitido? si no me veré complicado a reducir las líneas de código.

**Comment by Lord-Kelsier** [comment]
Hola @armas01. Esto no se puede hacer ya que self no es un parametro cualquiera. Self hace referencia a la instancia de la clase, es por esto que no se le entregan argumentos. Ejemplo:

```python
class A:
  def saludar(self):
    print("holi")

instancia = A()
instancia.saludar() # no lleva argumentos
```
Por como lo planteas entiendo que tienes una clase completa que va a sobrepasar las 400 lineas. Esto es un problema de modelacion, ya que las clases no deberian ser tan grandes. Lo que puedes hacer es delegar responsabilidades a funciones externas, pero no se podra usar el self en ellas ya que estan fuera de la clase

**Comment by armas01** [comment]
Entonces, estaría permitido crear una función que instancie los timers y les añada un intervalo? (Esta función retornaría la lista y ahí en la lógica guardaría los timers, no recibirá ningun parámetro)

**Comment by Lord-Kelsier** [comment]
Claro!
