### ISSUE TITLE
Tendencia a encallar 3.1.1

### ISSUE THREAD

**Issue by alvarocisternas** [IIC2233/syllabus#260]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!
En la parte 3.1.1 veo que existen 3 parámetros:
TENDENCIA_ENCALLAR_PASAJEROS
TENDENCIA_ENCALLAR_CARGUERO
TENDENCIA_ENCALLAR_BUQUE

revisé todo el documento y no encontré los valores de estos parámetros, ¿qué valores son?

**Comment by sperezmasri** [comment]
Hola @alvarocisternas. Si no se especifica en el enunciado puedes darles valores que a ti te parezcan convenientes a esos parámetros. Al final, la idea de dejar esos valores como parámetros es que se puedan modificar fácilmente y no queden "hardcodeados".  De hecho, te recomiendo que al probar tu código cambies los valores de los distintos parámetros, para ver si funciona de forma correcta. 

Por último, independiente del valor que tu le des a los parámetros el ayudante que te corrija puede probar con sus propios valores, así que no debería afectar mucho los valores que tu elijas. :smile:

**Comment by alvarocisternas** [comment]
Muchas gracias @sperezmasri !
Otra consulta con respecto al mismo tema, el atributo "Probabilidad de encallar"  de la Clase Barcos es lo mismo que la "tendencia a encallar" que se encuentra en la fórmula de método Encallar.

**Comment by sperezmasri** [comment]
La probabilidad de encallar corresponde al valor calculado en la acción "Encallar" de los barcos (el que se calcula con una formula larga). Por otro lado la tendencia a encallar es un atributo de cada barco que depende del tipo. En el enunciado el atributo aparece como "probabilidad de encallar" pero este debería decir "tendencia a encallar". No se si queda claro ahí, si no avísame cualquier cosa! :smile:

**Comment by alvarocisternas** [comment]
me quedo claro, muchas gracias!
saludos!
