### ISSUE TITLE
Apodo t00

### ISSUE THREAD

**Issue by aayale** [IIC2233/syllabus#260]
Hola, me acaba de surgir la duda de si es necesario que el apodo sea alfanumerico, o sea es obligacion. O PUEDE ser alfanumerico.

**Comment by jitorralba** [comment]
Hola @aayale!
El apodo puede estar compuesto sólo de letras, sólo de numeros o una mezcla de ambos, no es estrictamente necesario que tenga ambos tipos.
Éxito con lo que queda de la tarea!
