### ISSUE TITLE
Tarea 3

### ISSUE THREAD

**Issue by fcgfaura** [IIC2233/Syllabus#260]
En el calendario del curso aparece que la tarea 3 será subida el 21 de abril, es así?

**Comment by FernandoPieressa** [comment]
Si, se sube el 21 de abril!

Pueden descansar de las tareas... 

por ahora... ;)

**Comment by dfvasquez** [comment]
Muchas graciaaaaas! Buenísima 😄

**Comment by diegonavarrovergara** [comment]
Hola, por favor súbanla lo antes posible para tener algo más de tiempo! Nos vendría muy bien a todos.

**Comment by arturodelreal** [comment]
@diegonavarrovergara El tiempo de cada tarea es siempre de 2 semanas.
