### ISSUE TITLE
metodo agregar_puntaje no existe en demo.py

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#260]
Hola! En el enunciado dice que se debe sobre escribir el método `agregar_puntaje(self, num_jugador, cantidad)`, pero este método no existe en el `demo.py`, por lo tanto, ¿debemos crearlo y luego sobreescrbirlo, o simplemente podemos usar de forma directa el `gui.set_points(player_number, points)`? 🤔 
Eso, gracias!

**Comment by iqacevedo** [comment]
Hola,

No te preocupes, no es necesario que escriban este método, solo es importante que se calculen los puntajes cuando el juego finalice y se muestren en la pantalla, como dices puedes usar `set_points` para eso.

Saludos !

**Comment by rihanuch** [comment]
@iqacevedo gracias!
