### ISSUE TITLE
Duda con declarar variables globales

### ISSUE THREAD

**Issue by tomasvasquezp** [IIC2233/Syllabus#260]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, estoy teniendo problemas para modificar las variables que estan en parametros.py, me sale el siguiente error: UnboundLocalError: cannot access local variable "variable" where it is not associated with a value

En todo caso si declaro la variable como global, utilizando global "variable", se me soluciona el error. se puede hacer esto?

Gracias!!

**Comment by gasparbenavente2** [comment]
Hola! El uso de variables globales es una mala practica por lo que usarlo trae un descuento.

Tu error se puede tratar de un problema asociado a la forma en que estás importando las variables desde parámetros. Debes asegurarte de importar en cada archivo las variables de ```parametros.py``` que sean utilizadas

**Comment by tomasvasquezp** [comment]
ya, perfecto, muchas gracias!
