### ISSUE TITLE
keyPressEvent desconectado de QMainWindow

### ISSUE THREAD

**Issue by bmurtagh01** [IIC2233/syllabus#260]
Hola, tengo un problema donde tengo mi MainWindow que contiene mi juego como CentarlWidget, eso si estoy intentando utilizar el keyPressEvent para controlar mi personaje, pero al parecer no detecta mi teclado. He creado una conexion para que el juego modifique el statusbar de MainWindow y funciona perfectamente, incluso funciona mousePressEvent.

Para probar si no era un error distinto probe un codigo Qwidget y el keyPressEvent detectaba perfectamente cuando interactuaba con el teclado, por lo que me hace creer que es un probema o de interferencia entre el MainWindow y el Widget del juego o no se estan comunicando.

Muchas gracias por la ayuda

**Comment by gatochico** [comment]
Hola! Podrías subir la última versión de tu código a tu repositorio?

**Comment by JJJGGGG** [comment]
Prueba con
```python
self.setFocusPolicy(Qt.StrongFocus)
```
Tienes que importar```Qt``` de ```PyQt5.QtCore```

**Comment by mjespinoza** [comment]
Holaa, tengo el mismo problema, y utilice el comando self.setFocusPolicy(Qt.StrongFocus), pero no funciona, cuando coloco self.hasfocus() me sigue saliendo falso.

**Comment by jmwielandt** [comment]
@bmurtagh01 a quién le pusiste el keyPressEvent? tiene que estar en el widget que sea tu CentralWidget.
