### ISSUE TITLE
Almacenamiento informacion .txt

### ISSUE THREAD

**Issue by Fopazov** [IIC2233/Syllabus#260]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. Duda corta. Al crear archivos de almacenamieto de informacion de las instancias torneo, ¿importa que las lineas de los archivos .txt no superen los 100 caracteres? (no sé si aquí aplicaría la regla del pep 8. ¿Si es así, de cuánto sería el descuento? ¿Podría optar al bonus de 3 décimas?
Gracias de antemano

**Comment by Rotopikus** [comment]
Hola!!!

Pep8 no aplica para este tipo de archivos. Solo para archivos de código Python.

Mucho éxito!!

**Comment by Fopazov** [comment]
Vale, gracias!
