### ISSUE TITLE
Abrir y cerrar menu de pausa apretando P

### ISSUE THREAD

**Issue by benja20029** [IIC2233/Syllabus#260]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Buenas, queria saber si es que de casualidad algun ayudante tenia alguna documentacion o algo donde obtener informacion para poder detectar si una ventana esta activa para con ello, saber si hacer aparecer una ventana al apretar p por favor. 

Estuve probando distintos comandos como IsActiveWindow, IsEnabled pero ninguna de esas funciono, tambien busque por harto rato en internet pero al menos con las palabras claves que busque no encontre nada.

Muchas gracias de antemano!!

**Comment by tamyhan** [comment]
Hola @benja20029 ! No estoy segura si entiendo bien a lo que te refieres con detectar si una ventana está activa o no. Pero la idea del botón de pausa es, valga la redundancia, pausar o reanudar el juego (no hacer aparecer una ventana aparte). Es decir, al apretar el botón de pausa lo que debe ocurrir es que los autos y troncos se dejen de mover, los objetos dejen de aparecer y desaparecer, y el personaje no se mueva si se aprietan las teclas WASD. Y luego, al volver a apretar el botón, se debe volver a activar todo desde donde quedó.

**Comment by benja20029** [comment]
O sea, entiendo esa parte en realidad, no estoy teniendo problemas al pausar el juego, el tema es que al pausarlo, las señales que puse para que se reanudara el juego no se estan tomando, por lo que la unica forma de volver a reanudar el juego es presionando el boton o presionando escape, he estado buscando informacion para ver si puedo pausar y posteriormente reanudar el juego presionando P, pero no he llegado a nada util. No se si ahora se entiende la problematica. Es por eso que queria saber si algun ayudante tenia una documentacion que me pudiera ayudar para lograr reanudar el juego presionando P, por favor.

**Comment by tamyhan** [comment]
Ahh, entiendo tu problema. No creo que exista alguna documentación específica sobre las pausas, pero probablemente tu problema tiene que ver con tu definición e implementación de las señales. Es raro que te funcione con el botón pero no con la tecla. Fíjate si tienes bien definidas las señales, por ejemplo, que la señal de reanudar el juego que usas con el botón (que si te está funcionando) sea la misma o active lo mismo que la que se emite al presionar la tecla P. Si no te funciona podrías tratar con otra tecla (y dejarlo claro en tu README en caso de cambiarla). 

Avísame si lo logras arreglar!
