### ISSUE TITLE
Error al ejecutar demo.py

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#260]
Hola, al ejecutar demo.py no se me cargan las imágenes, hoy le pregunté a dos ayudantes y si bien lograron solucionar que no se me abriera el archivo, el error de las imágenes persiste. El problema es similar al de la issue #203. Sin embargo, cuando intenté corregir según como menciono Drpinto1 tampoco funcionó, espero alguien sepa como solucionarlo.
los errores que señala python son:
 QImage::scaled: Image is a null image
QPixmap::scaled: Pixmap is a null pixmap
PD: ya descomprmi las fotos de los jugadores en assets según como aparecía en el enunciado e he intentado lo que aparece en otras issues

**Comment by Arcoirisky** [comment]
Hola! ¿Viste si las carpetas tienen mayúsculas? O ¿En el código al llamar a las carpetas? Si tienes todo guardado dónde corresponde, ese puede ser el problema.
