### ISSUE TITLE
 [Herencia] [Clases Abstractas] Duda sobre buenas prácticas para herencia de atributos

### ISSUE THREAD

**Issue by tomasladrix** [IIC2233/syllabus#261]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Mi duda tiene relación más bien sobre buenas prácticas de programación, más que de un problema en específico. En particular, sobre los atributos que manejan las clases abstractas. La duda me surgió haciendo la Tarea 1, pero lo trataré de explicar usando un ejemplo sospechosamente similar :)

Supongamos tengo una clase abstracta llamada ```Animal()```. Luego, tengo diferentes clases tales como ```Caballo()```, ```Humano()```, etc. en donde cada subclase tiene un atributo llamado ```numero_pies```. Ahora bien, todo animal puede avanzar, y **la cantidad que avanza es distinta dependiendo de ```numero_pies```** (cero relación con barcos y cuánto se desplazan según su tipo). Por lo tanto, me resulta lógico implementar un método ```avanzar()``` en la superclase ```Animal```, sin embargo, para esto necesito saber ```numero_pies```, el cual está definido en la subclase y por lo tanto ```Animal``` no puede acceder a este.

Una solución directa sería, al momento de realizar el ```super().__init__()``` en la subclase, pasar como parámetro el atributo ```numero_pies```, e implementar ```avanzar()``` en la superclase y es ahí donde viene mi problema. Yo no quiero que la superclase maneje ```numero_pies```, ya que eso es pega de la subclase. Encuentro un poco contradictorio pasar información específica de la subclase a la superclase, ya que se rompe esta idea de "herencia" e independencia entre clases y terminan siendo más bien como dos clases interconectadas (quizás es sólo idea mía y me estoy complicando de más).

La otra solución es simplemente definir el método ```avanzar()``` en cada subclase, pero si siempre es la misma fórmula que va a depender de ```numero_pies``` es bastante repetitivo implementar el mismo método en todas las subclases. Qué es lo que se hace en estos casos? Da lo mismo que la superclase herede atributos que en teoría no le corresponden? En este caso que ```Animal``` tenga un atributo ```numero_pies``` igual tiene sentido pero supongamos que no, ya que "no es propio de un ```Animal```".

Mis disculpas por la extensión, pero son justo este tipo de dudas las que me dejan mucho tiempo dando vueltas sin saber cuál es la manera "correcta" de abordarlo (o la mejor forma de desarrollar software), ya que las dos alternativas funcionan, pero no estoy seguro cuál es la mejor forma de enfrentar situaciones así.

Muchas gracias de antemano!
Tomás

**Comment by tomasladrix** [comment]
Bueno, creo que me solucioné la duda sólo. Lo que se me ocurrió es efectivamente no definir ```numero_pies``` en la clase ```Animal```, sino que definirlo como atributo en la subclase (lo cual era la intención orginal). Luego, para no repetir la misma función en todas las subclases, una solución es definir en la superclase el método ```avanzar(numero_pies)```, de forma que se pase como parámetro y así se pueda tanto definir en la superclase como utilizar en las subclases sin la necesidad de pasar ningún atributo no adecuado a la superclase.

Era bien directa la solución, pero en su momento no se me ocurrió :sweat_smile:. De todas formas lo dejo acá por si a alguien le llegase a servir.

Saludos!

**Comment by igbasly** [comment]
Hola @tomasladrix :v:

Pese a que pareciera que te respondiste, vengo porque preguntas sobre las buenas practicas de programación (muy importante jeje).
La lógica de herencia es bastante simple, si tienes un caso en que crees que todas las clases hijas tendrán un mismo atributo, entonces se pude generalizar a decir que la clase madre lo tendrá, ya que así es más sencillo definirlo y es algo que todas las subclases comparten. Ahora, con los métodos ocurre algo similar, si el método se comporta de la misma manera en todas las subclases y utiliza atributos que todas las subclases comparten, entonces no habría problemas en tener ese método en la clase madre. Para las clases abstractas aplica el mismo concepto.

Una forma de ver si se está modelando correctamente es analizar las clase de la siguiente forma:
- Las subclases siempre deben poder hacer todo lo de la clase madre, si una subclase no debe utilizar un método que se definió en su clase madre, entonces probablemente haya un error de modelación.
- Las subclases comparten todos los atributos de la clase madre. Si una subclase no debe tener o no utiliza algún atributo definido en su clase madre, entonces probablemente haya un error de modelación.
- En el sentido contrario aplica lo mismo, si hay un atributo o método que se repite en todas las subclases entonces es mejor que vaya en la clase madre.

Espero que esto te oriente un poco y no dudes en preguntar cualquier cosa 😉 
Saludos,
Ian.

**Comment by tomasladrix** [comment]
Qué buenos tips, me hacen mucho sentido y está muy útil tenerlos a mano.

Gracias!! 🙌
