### ISSUE TITLE
Duda código en parametros.py

### ISSUE THREAD

**Issue by JorgeUribeGo** [IIC2233/Syllabus#261]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda sobre esta línea en el enunciado:

_"Cualquier información no relacionada con parámetros almacenada en este archivo resultará en una penalización en tu nota"_

Estaba pensando si los valores de inicio de cada tipo de planta (en plantas.txt) deben/pueden ser guardados en este archivo, y si es así, si el código para leer el archivo puede estar dentro de parametros.py o si tengo que leerlo y guardar la información en otro módulo. Imagino que lo segundo no, porque son constantes que voy a estar ocupando durante la tarea, pero no sé si es válido poner código dentro de parametros.py.

Gracias!

**Comment by CrisDonosoMaass** [comment]
Hola! Si te refieres al valor que se lee del archivo entonces no, los valores de inicio de las plantas no deben ser guardados en parametros.py, ese archivo es exclusivamente para el almacenamiento de constantes tipo CONSTANTE_ENUNCIADO y otras que consideres necesarias. Por lo tanto, el código que uses para leer plantas.txt tiene que estar en otro módulo. Queda a su criterio como prefieren almacenarlo.

Si te refieres a los valores válidos entre los que puede estar cada valor, esos sí pueden estar en parametros.py como por ejemplo MIN_RESISTENCIA.

Espero haberte ayudado!

**Comment by JorgeUribeGo** [comment]
Yaa gracias!

Ahora que lo dices, es necesario que valores como MIN_RESISTENCIA estén en parametros.py?

**Comment by CrisDonosoMaass** [comment]
Dado que son constantes, sí deberían estar en parámetros. De lo contrario se podría considerar hard-coding y eso tiene descuento.

**Comment by JorgeUribeGo** [comment]
Perfecto, muchas gracias!
