### ISSUE TITLE
duda con valides de unidades.txt

### ISSUE THREAD

**Issue by Martinluco** [IIC2233/Syllabus#261]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Afirmándome de la issue #253 , si hay un gato de cada tipo (CAB, MAG, GUE) pero aparte hay alguno de los otros tipos (PAL, MAR, MDB), si es que todos los parámetros están dentro de los valores correspondientes, el archivo se considera válido??
Muchas gracias :)

**Comment by Dominique236** [comment]
Hola @Martinluco !
Como se menciona en el enunciado, "NO puedes asumir que el archivo tendrá un gato de cada tipo básico o que el archivo
no contendrá gatos de los tipos que no pueden ser comprados (...)", por lo que el archivo **no puede contener gatos de tipos que no pueden ser comprados**, estos son 'CAR', 'PAL' y 'MDB'.
Ojalá esto aclare tu duda :)

**Comment by Martinluco** [comment]
muy claro gracias! en caso de que tenga uno de estos tipos se termina la ejecución o se realiza sacando los gatos no permitidos del archivo?

**Comment by Dominique236** [comment]
En el enunciado se menciona que "En caso de que el formato del archivo o los valores para alguno de los gatos sean inválidos, se deberá informar al usuario del error, **terminando la ejecución del programa**."

**Comment by Martinluco** [comment]
muchas gracias!!
