### ISSUE TITLE
Comportamiento de la rana sobre el tronco.

### ISSUE THREAD

**Issue by CataLebe** [IIC2233/Syllabus#261]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

En el enunciado cuando se menciona; "El personaje podrá moverse de forma libre dentro del tronco,
pero sólo podrá salir de este mediante un salto hacia adelante o hacia atrás (no hacia los lados ni en
diagonal)" se refiere a que simplemente el programa no lo permita ? O que en el caso de que la rana salga del hacia los lados o en diagonal automáticamente deberá perder una vida ? (entendiendo que al hacer eso cae al rio).

Desde ya muchas gracias

**Comment by tamyhan** [comment]
Hola @CataLebe ! Es lo segundo que dices. Al estar sobre un tronco, el programa no debe permitir que el personaje salte hacia los lados. Solo podrá caminar dentro del tronco siempre y cuando no se salga de él, y podrá saltar hacia adelante o hacia atrás para salir del tronco.

**Comment by CataLebe** [comment]
Entiendo, muchas gracias !

**Comment by svilaza** [comment]
Respecto a este comportamiento, para poder subirse al primer tronco y salirse del ultimo, es necesario que sea con un salto o en ese caso puede caminar libremente a ellos y luego salirse de estos con saltos?

**Comment by tamyhan** [comment]
Sí, debe entrar y salir de todos los troncos con un salto
