### ISSUE TITLE
README

### ISSUE THREAD

**Issue by ian-fell** [IIC2233/syllabus#261]
Hola. Estaba terminando de escribir el README cuando me surgió la duda; hay que eliminar todo lo que viene a modo de tutorial en el README para entregarlo? O puedo simplemente rellenar con la información necesaria y dejar todo el resto?

**Comment by furcelay** [comment]
Hola!
No hay problema que uses como base el README entregado, pero no es la idea dejar contenido que no tenga ninguna relación con la tarea (como los ejemplos de como poner código en el README, etc.). Deja solo lo que tenga sentido en relación a tu tarea.

Saludos!
