### ISSUE TITLE
Duda sobre sprites.

### ISSUE THREAD

**Issue by nhorellana** [IIC2233/syllabus#261]
Hola! Para la tarea puedo crear una nueva carpeta con una selección de los spirtes que subieron y a estos cambiarles el nombre? Creo que contaría como "subir mis propios sprites" pero de forma flaite jajaja

**Comment by gatochico** [comment]
Hola! No puedes hacer eso :( Ya que al fin y al cabo, seguirían siendo los mismos sprites que dimos con la tarea. Una forma de "cambiarle" el nombre a los archivos es haciendo un diccionario cuyas llaves sean el nuevo nombre que quieres dar a tus sprites, y los valores sean las rutas hacia cada imagen. Citando al enunciado: 
![image](https://user-images.githubusercontent.com/37161120/57889404-be54b180-7802-11e9-9cdc-aa60a685ebeb.png)
Saludos!

**Comment by JJJGGGG** [comment]
Y ese diccionario, puede estar en el módulo ```parametros.py```, o debe estar en otro módulo

**Comment by Hernan4444** [comment]
Si, puede estar en `parametros.py, incluso se recomienda ahí para tener todas esas constantes en un archivo y si algún día quieres cambiar los _sprints_, sepas donde están los rutas a las imágenes.

Saludos :v:
