### ISSUE TITLE
jugar y al azar 

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2233/Syllabus#261]
hola, tengo un par de dudas:

1.-  ¿que pasa cuando el jugador pone jugar o al azar, cual es la diferencia? 

2.- ¿En el campeonato los equipos que se enfrentan en cada etapa siempre es random?

**Comment by monicabelen** [comment]
Hola! 

1. Si te refieres a cuando el juego empieza, la única forma de jugar es creando tu propio equipo. No existe la opción de crear un equipo al azar. 

2. Sí, siempre es aleatorio entre los equipos que pasan a la fase siguiente.
