### ISSUE TITLE
 Agregar atributos 

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#261]
Hola!
Puedo agregar más atributos aparte de los que me piden en el enunciado?, y estos tienen que reflejarse también en el diagrama de clases?

**Comment by mpsubiabre** [comment]
Hola @moquezada!

En ese sentido eres totalmente libre en agregar atributos, puedes agregar todos los que estimes necesarios. Y si, en la entrega final del diagrama de clases debe reflejarse fielmente la modelación, por lo que deben reflejarse todos los atributos.

Espero haber contestado tu duda :)
