### ISSUE TITLE
retorno de funciones

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#261]
digamos que tengo mi función
```python
foo():
   ...
   return ret_1, ret2, ret3
```
es posible que mi función retorne más de un elemento? o se considera como si estuviese retornando una tupla? (en caso de ser no poderse, se podría retornar como `mylist` con los elementos en ese orden, cierto? (solo que sería mas cacho para hacerlo...))

**Comment by andresfdezc** [comment]
Puedes desempaquetar la tupla inmediatamente, que es lo que suele hacer con este tipo de funciones:

```python
resultado1, resultado2, resultado3 = foo()
```

**Comment by rihanuch** [comment]
ahh, entonces todo ok! eso estaba haciendo 😅 , solo que me había entrado la duda jajaja, muchas gracias!
