### ISSUE TITLE
Funcion riesgo mortal

### ISSUE THREAD

**Issue by emivenezian** [IIC2233/Syllabus#261]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Para determinar si el conejo puede ser afectado por una zanahoria o lobo tenemos que considerar las paredes entremedio? O solo si es alcanzable. Es decir, si en una misma columna esta el conejo y un lobo vertical, pero hay una pared de por medio, debemos retornar True?

**Comment by AntonioVenegas** [comment]
Hola @emivenezian!, efectivamente, si hay una pared entremedio de un conejo y un lobo o cañon apuntando a conejo, el conejo no estaría en riesgo.

Saludos :)

**Comment by BenjaMedinaPUC** [comment]
Hola! espero que se encuentren bien, mi consulta con respecto al tema va de que quiero saber si puedo asumir que Conejo se puede encontrar con un enemigo máximo (ya sea por columna o fila ) o no se puede asumir esa suposición? Muchas gracias

**Comment by ignacio-sp** [comment]
Hola @BenjaMedinaPUC! No estoy muy seguro de entender tu duda ¿Podrías detallar un poco más? De todas formas, basta con que al menos una zanahoria o lobo impacte con el conejo para que este se encuentre en riesgo.

**Comment by BenjaMedinaPUC** [comment]
vale, mi duda va acerca sobre si se puede asumir que es un enemigo maximo por columna/fila, onda :

["P", "-", "-", "CR", "-", "-", "-", "C", "-", "P", "P", "P", "-", "-", "P", "P"]

o puede haber mas de uno':

["P", "-", "-", "CR", "CR", "-", "-", "C", "-", "P", "P", "P", "-", "-", "P", "P"]

**Comment by ignacio-sp** [comment]
Como no se especifica en el enunciado, puedes hacer tu propio supuesto. Sin embargo, en el caso que muestras, el conejo estaría en riesgo (el segundo cañón impactaría al conejo). Un caso distinto sería el siguiente:

```
["P", "-", "-", "CR", "-", "CL", "-", "C", "-", "P"]
```
Ya que el cañón actuaría como una pared, el conejo no estaría en riesgo pues las zanahorias de los cañones impactarían entre ellos.

Para que lo tengas en consideración, no existirán casos particulares en los test privados que no aparezcan en los tests que les entregamos, consideren aquellos casos similares a los que ya se encuentran. Saludos!
