### ISSUE TITLE
Ejecutable Python Mac

### ISSUE THREAD

**Issue by LuisFros** [IIC2233/Syllabus#262]
Hola! Estoy tratando de poder exportar un programa .py para que sea un ejecutable tipo .exe. Encontre que para Windows se puede usar Py2exe, pero quiero poder crear uno que se pueda abir en Mac OS. Tienen alguna recomendacion? Exportarlo desde Windows a Mac

**Comment by sguerra2** [comment]
Hola! Justo anoche estuve haciendo unos experimentos... me resultó lo que sale por acá: http://www.marinamele.com/from-a-python-script-to-a-portable-mac-application-with-py2app

**Comment by LuisFros** [comment]
Gracias! Voy a probarlo,

**Comment by LuisFros** [comment]
El unico problema es que mi pc es Windows, y parece que py2app solo funciona desde Mac

**Comment by Hernan4444** [comment]
@LuisFros por mi parte, yo uso cx_freeze para hacer los exe,

Saludos!

**Comment by sebacruzd** [comment]
Para windows yo uso pyinstaller, me ha funcionado bien

**Comment by LuisFros** [comment]
Estoy usando pyinstaller y me funciona muy bien! Gracias a todos
