### ISSUE TITLE
snitch dorada/finalizar juego

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#262]
hola! en el enunciado dice que se termina el juego cuando se logra la snitch dorada, lo que no me queda claro es como la representamos y hacemos que se finalice el juego (por el minuto le estoy dando un puntaje ridículamente alto al jugador que la obtiene). Al apretar el botón de "terminar juego" que debe ocurrir aparte de calcular los puntajes, un `quit()` ? (Pongo las preguntas juntas porque al final apuntan a lo mismo (que hacer cuando se termina el juego (ya sea apretando el botón o simplemente ganando))

**Comment by Sforrego** [comment]
y que hacer cuando no se puede poner pieza en el primer turno, se termina igual?

gracias!

**Comment by stephichau** [comment]
@rihanuch cuando se habla de terminar el juego, se refiere a que no se puede seguir jugando. En otras palabras, no se pueden poner más piezas en el tablero y se debe calcular el puntaje indicando el ganador. El ```quit()``` lo hará el usuario al cerrar la ventana :)

@Sforrego sí, se termina

**Comment by rihanuch** [comment]
@stephichau como le decimos al usuario que ya no se puede seguir jugando? 🤔

**Comment by iqacevedo** [comment]
@rihanuch tal como dice @stephichau, no se pueden poner más piezas en el tablero (si intento poner otra pieza no debería pasar nada).

Saludos !
