### ISSUE TITLE
[corto] Diagrama, sobre herencia

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#262]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Otra cosa, en herencia qué pasa si determino que solo debo reescribir una función, dejo vacío el espacio de variables (feo) ?
![image](https://user-images.githubusercontent.com/66154723/115339476-da8dc580-a172-11eb-9f64-0d7ac8dd8106.png)

**Comment by aaossa** [comment]
Hola @fernandosmither , en los contenidos ya aparece un ejemplo de herencia, donde se ve que en la subclase solo tenemos que agregar los atributos y métodos que esa subclase declara por su cuenta:

![image](https://user-images.githubusercontent.com/10425834/115426967-02127b80-a1cf-11eb-9b29-6b257460b58c.png)

Ahora, si por ejemplo estuvieramos hablando de métodos y la clase `Ladrillo` tuviera un método `destruir` este iría en el cuadradito de dicha clase. Si la clase `LadrilloMoneda` lo tuviera que sobreescribir tendrías que agregar algo, para mostrar que ese *overriding* existe explícitamente. Si solo agregas la firma de la función (o sea, haces lo mismo que hiciste en `Ladrillo`) ya estás declarando que existe un método con el mismo nombre, por lo que quien vea el diagrama podría inferir que el método se sobreescribe. 

En resumen, dado que sabemos que cuando una clase hereda de otra todos los métodos y atributos se repiten, basta con declarar nuevamente el método en el diagrama para explicitar que "esta clase también implementa el método (*overriding*)". Espero se entienda la idea y también te sea intuitiva. ¡Éxito con tu tarea 💪!

**Comment by fernandosmither** [comment]
Gracias, resuelto.
