### ISSUE TITLE
imagenes

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2233/Syllabus#262]
hola, al correr el archivo demo me aparecen solamente 2 fotos de jugadores y el resto de los jugadores son cuadrados en blanco sin foto, al seleccionar los jugadores del equipo, me muestra la información de todos los jugadores, por lo tanto es un problema meramente de las fotos y no del jugador en sí, alguna idea de porque puede suceder esto? (no he tocado la base de datos ni las fotos)

**Comment by behrmann97** [comment]
Hola, a algunos les está pasando, intenta aplicar lo que dijo Drpinto1 en la isue #203 :

    Fondo Negro: Módulo Interfaz.py, línea 18, cambiar la F en fondo a minúsculas; nueva línea:

oImage = QImage("Assets/fondo").scaled(1366, 697) # Ponemos el Background

    Imágenes de Jugadores: Módulo clases.py, líneas 122, 153, 163, cambiar la a de assets a mayúsculas, líneas nuevas:

122: self.label.setPixmap(QPixmap('Assets/photo/' + id).scaled(100 * scaled, 100* scaled))
153: self.label.setPixmap(QPixmap('Assets/photo/' + self.id).scaled(100 * self.scaled, 100* self.scaled))
163: self.imagen.setPixmap(QPixmap('Assets/photo/' + jugador.id).scaled(100, 100))


    Botón atrás: Módulo Interfaz.py, línea 50, cambiar el primer argumento de la llamada (1275) por un valor menor hasta que el botón atrás quede dentro de la ventana, en mi caso este valor es 1210, nueva línea:

self.boton_atras.setGeometry(1210, 1, 90, 40)


    Indicador Esperanza: Módulo Interfaz.py, línea 105, cambiar el primer argumento de la llamada (1200) por un valor menor hasta que el indicador de Esperanza quede dentro de la ventana, en mi caso este valor es 1135, nueva línea:

self.label_puntaje.setGeometry(1135, 520, 160, 40)

Estos cambios a los archivos de la GUI sí estarán permitidos, pero cualquier otro cambio está prohibido.
