### ISSUE TITLE
Intervalos atributos clase Planta

### ISSUE THREAD

**Issue by vvialbarros** [IIC2233/Syllabus#262]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
En el enunciado de la tarea en la seccion de la clase planta dice lo siguiente:
Vida Máxima: Corresponde a un int entre 0 y 100 que representa cantidad máxima de puntos de vida que puede tener la planta.
Para este caso y el resto de atributos de planta que tambien dicen entre 2 valores debo incluir los valores de los extremos? En este caso debo incluir el 0 y el 100?

**Comment by AndreaVict** [comment]
Holaa si, los valores extremos están incluidos en el intervalo válido. Es decir, el intervalo de la vida máxima corresponde a los valores del [0, 100]. Esto aplica para el resto de atributos de plantas.
