### ISSUE TITLE
imprimir coordenada de lanzamiento en pantalla

### ISSUE THREAD

**Issue by cnillanes** [IIC2233/syllabus#262]
Hola! El enunciado de la tarea menciona que "al acabar el turno del oponente **se deberá imprimir las coordenadas de la casilla a la que lanzó una bomba**, seguido del mapa de ambos jugadores con las casillas actualizadas" Esto solo se indica para el oponente verdad? O es necesario que cuando lance el jugador tambien muestre ese mensaje refiriendose a las casillas que está disparando?

**Comment by jitorcas** [comment]
Hola! @cnillanes 

En el enunciado no se especifica que se deban imprimir las coordenadas de ataque del jugador, sin embargo, podrías imprimirlas indicando donde se está efectuando el ataque. 

Queda a tu criterio la implementación de funcionalidades adicionales, siempre y cuando dichas funcionalidades respeten el flujo y reglas del enunciado. 

Éxito en la tarea! ⚓️
