### ISSUE TITLE
Tamaño ventana

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#262]
Hola, hoy probé mi programa en un computador con una pantalla más chica, con lo que la ventana se salía del tamaño de la pantalla del computador, lo cual era facilmente corregible al disminuir el tamaño N de las sprites. Puedo asumir que cuando un ayudante corrija mi tarea lo hará en unos intervalos de N adecuados (los cuales podría indicar previamente yo en el Readme).

Saludos

**Comment by gatochico** [comment]
Hola! Si es que definiste un parámetro facilmente cambiable para el tamaño N de las celdas, no habrá problema con tu tarea. Saludos (:
