### ISSUE TITLE
T01- uso obligatorio diccionarios, args/kwargs

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#262]
Hola!
Es obligación usar diccionario, args o kwargs?
No lo mencionan en los objetivos de la tarea, pero para asegurarme :laughing:

**Comment by jeschuwirth** [comment]
Hola @Camila-sty,

No se obliga a utilizar ninguna materia para esta tarea. Sin embargo las tareas están pensadas con la materia que se ha visto hasta ahora y es probable que te faciliten el código si las usas ;)

Éxito!

**Comment by Camila-sty** [comment]
Hola.
Con respecto a lo que dices; *No se obliga a utilizar ninguna materia para esta tarea.*
Me queda la duda. En la pauta de la tarea que subieron, sale que se evalúan las herencias, clases abstractas, o properties que hayan sido utilizadas, pero esto es sólo si se ocupan?
Y sobre el diagrama de clases, que se debe entregar si o si. Qué es lo que se pide en sí?, porque si yo no apliqué ninguna materia simplemente porque no encontraba necesario, entonces no tengo herencias, ni clases abstractas, ni properties, y por lo tanto, debería presentar solo el uso de clases? que de alguna manera tiene solo características de composición y agregación, pero ninguna otra.

**Comment by jeschuwirth** [comment]
Lo siento mucho por la respuesta anterior, fue un error mio entregar esa respuesta antes de tener la pauta.

Efectivamente en esta tarea se evalúa código, como dices en tu respuesta todas las celdas en amarillo de la rúbrica se revisan por código, por lo tanto la tarea debe estar modelada usando la materia de clases.

Las clases abstractas y properties se evalúa su uso correcto, por lo tanto si tienes una clase que debería ser abstracta y no lo es, o no usas una clase abstracta esperada podría tener descuento.

Por lo anterior anterior, el diagrama de clases debe ser considerando todas las clases necesarias para modelar el problema.

No te puedo pedir que cambies todo tu programa en base a esta nueva respuesta en tu issue. Por lo tanto te pido que intentes usar la materia de clases en tu tarea y si tienes muchos problemas para hacer el cambio me mandes un correo a jeschuwirth@uc.cl para comentar que podemos hacer.

**Comment by Camila-sty** [comment]
Entiendo que se evalúa el uso cuando debiese aplicarse, o cuando se aplica incorrectamente. Pero esto es solo si la clase necesitaba usar una materia? Como por ejemplo *herencia, clase abstracta, properties* ..? 
Bueno, yo partí haciendo las clases de entidades que se mencionan en el enunciado, y que donde aconsejan a usar esta materia. Pero yo en ese momento me dí cuenta por tema de espacio (líneas de código) y por la idea que tenia de hacer las acciones que se piden para cada identidad, no necesitaba usar herencia ni clase abstracta, lo único que utilicé fue usar properties en una clase en particular, pero nada más. Ahora la duda que tengo es que si esto está bien? Ósea, puede llegar a pasar que no me descuenten por no usar herencia ni clase abstracta (porque en ninguna clase era necesario) ?, puede pasar esto? . O simplemente por no haber ocupado la materia de herencia y clases abstractas obtendré descuento? .

**Comment by Camila-sty** [comment]
Otra consulta, se evalúa el uso de *herencia, clase abstracta, properties *  SOLO en la parte de “entidades” de la tarea? (que es donde mencionan que debemos aplicar esto),  o puedo implementar cualquier otra clase que sea necesaria para el funcionamiento de mi programa y aplicar esta materia? , y que esté bien dentro de lo que se evalúa en la pauta? .

**Comment by jeschuwirth** [comment]
En cuanto al primer comentario, para la corrección se espera el uso de herencia y clases abstractas, si crees que no es necesario para tu código puedes justificarlo en tu _readme_. Sin embargo como agregar una clase abstracta padre no es dificil si ya tienes programas las clases hijo, te recomiendo programar en base a la materia entregada y así te evitas problemas con el ayudante y tener que mandar a recorregir.

En la pauta todo lo que está en naranjo/amarillo se corrige por código, por lo tanto se espera el uso correcto de la materia apropiada (clases en este caso). Si quieres utilizar esa materia para el resto de tu código no hay problema :)

**Comment by Camila-sty** [comment]
Es que ese el tema. quizás se esperaba que yo hiciera una clase padre de magizoologo y que sus clase hijas fueras los tipos, pero yo no hice clases de los tipos, entonces no necesitaba aplicar herencia, no se si me doy a entender?. Lo mismo que para la clase DCCcriatura, yo no les hice clases a los tipos de criatura, entonces tampoco necesité herencia, y menos clases abstractas. Mis clases no tienen relación con las otras, solo en sistema de composición y agregación. Mi pregunta puntal es que puedo NO aplicar herencia o clases abstractas? (obvio, siempre cuando no sea necesario, lo que es mi caso, no me hes necesario)

**Comment by jeschuwirth** [comment]
@Camila-sty, sorry por lo muy tarde de la respuesta. 

Como la idea de esta tarea es evaluar conocimiento de la materia orientada en clases no te puedo decir exactamente donde debes ocupar que materia, solo te puedo avisar que el contenido de abtracción y herencia se evalúa. 

Como hay varias formas de codificar una solución te recomiendo justificar en el readme porque decidiste hacerlo a tu manera en lugar de otra que ocupe los contenidos vistos. 

Junto a lo anterior, cita esta issue en tu readme para evitar problemas con el ayudante que te corrija

Me disculpo nuevamente, se me pasó la issue entre todos los mensajes ):
