### ISSUE TITLE
Optimización revisión de colisiones entre zombies y guisantes

### ISSUE THREAD

**Issue by panchouc** [IIC2233/Syllabus#262]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

¡Hola!, quería saber si alguien me pudiese ayudar con algún tip o algo por el estilo para mejorar el tema de las colisiones entre los guisantes y los zombies. Resulta que mi código funciona, pero demora muchísimo en actualizar todos los guisantes, debe de haber una forma muchísimo más rápida para revisar las colisiones, que por ejemplo `for loops`, quizás señales, pero no sé muy bien en verdad. O tampoco sé si es mejor quizás implementar un Thread para revisar cada zombie al mismo tiempo, en vez de un thread que revise todo al mismo tiempo, para todos los guisantes y todos los zombies. Resulta que voy revisando cada guisante, y al momento de que llega, si en el loop todavía no llego, pasa de largo y no se produce la colisión, de antemano muchas gracias, saludos.

**Comment by Lord-Kelsier** [comment]
Hola @panchouc. En este tipo de casos, para poder optimizar debes buscar que cada objeto haga la menor cantidad de comprobaciones posibles. Por ejemplo si tienes una lista con todos los zombies y cada guisante revisa en toda esta lista, una optimizacion seria que los zombies muertos dejaran la lista asi revisas menos. Otra opcion es revisar solo los zombies que estan actualmente en pantalla, ahi reducen aun mas los checkeos. Estas soluciones pueden cambiar drasticamente la modelacion que tenias por lo que mirando tu mismo debes descubrir cual encaja sin romper todo lo que tienes
