### ISSUE TITLE
Feedback AC06 - Threading

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233/syllabus#263]
# Feedback AC06

## Locks como atributos de clase

Recuerden que los atributos de clase son únicos para todos las instancias de una clase, y por lo tanto son muy útiles para utilizar __locks__ que sean compartidos por todos los __threads__ que posean una instancia de esa clase.

```python
# CORRECTO: Esto permite que las instancias de esta clase usen el mismo lock
class Dany:
    lock = threading.Lock()

    def __init__(self):
        pass
    # Resto del código...
```

En cambio, si un __lock__ fuera un atributo de instancia, cada __thread__ que acceda a un __lock__ de una instancia distinta de `Dany` estaría ejecutando sobre variable distintas y, por lo mismo, sobre objetos distintos.

```python
# INCORRECTO: Al hacer esto, todas las instancias tendrán su propio lock
# y nunca sabrían cuando otro thread está en la sección crítica
class Dany:
    def __init__(self):
        self.lock = threading.Lock()
    # Resto del código...
```

## Modelación del método `convencer` de `Dany`

Varios llamaron al método `convencer ` de la forma `Dany.convencer()`. A diferencia del __lock__ de Dany, el método `convencer` del archivo entregado **no era un método de clase**, por tanto debían instanciar un objeto de clase Dany para poder llamar a ese método. Otra opción era convertir el método `convencer` en un método de clase, la cual era un poco más elegante que instanciar una `Dany` cada vez, lo que podían lograr utilizando `@classmethod` o `@staticmethod`. Finalmente, podían convertir a Dany en un `Lock`, pero debían ser consistentes en su uso a lo largo del código.

```python
# Opción 1: Funciona bien si se instancian múltiples Danys
class Dany:
    lock = threading.Lock()
    # Método convencer como método de instancia

# Opción 2: Funciona bien al usar convencer() como método de clase
class Dany:
    lock = threading.Lock()
    
    @classmethod
    def convencer(cls, ...):
        # ....


# Opción 3: Otra opción que podía resultar en un mejor modelamiento
class Dany(threading.Lock):
    @classmethod
    def convencer(cls, …)
        # ...
```

## Uso de locks

Grave error que se debe evitar a toda costa: instanciar los `Lock` inmediatamente antes de adquirirlos. Este error se ve más o menos así:

```python
def función_compartida_que_deseo_proteger(...):
    lock = threading.Lock()
        with lock:
            # sección protegida
```

Lo anterior no sirve de nada, pues un _thread_ nunca se va a encontrar con el mismo `Lock` ya siendo ocupado por otro _thread_. Lo que hay que hacer es utilizar **un mismo `Lock`** que debe ser accesible por todos los elementos del programa. Esto se vería más o menos así:

```python
lock = threading.Lock()  # código independiente de cada thread
.
.
.
def función_compartida_que_deseo_proteger(...):
    with lock:
        # sección protegida
```

## Verificando si el `lock` está tomado

Para pedir el `lock` de Dany, debían mantener un loop mientras el `lock` estuviera ocupado (`while Dany.lock.locked(): ...`) para continuar con la simulación mientras esperaban que Dany se desocupara.

```python
while Dany.lock.locked():
    # Mientras no podemos “ocupar” a Dany, esperamos
    time.sleep(1)
    # ...
# Si llegamos aquí, es porque Dany ya no está ocupada...
with Dany.lock:
    # … asi que la ocupamos nosotros usando su método convencer
```

## Locks con context manager

Recuerden que la operación de `lock.acquire()` y `lock.release()` también pueden hacerlo con el *context manager* `with lock: ...`, asi ustedes no deben preocuparse de liberar el lock una vez que realicen las funcionalidades que deseen, ya que esta sentencia lo hace por ustedes!

```python
# Este código…
lock.acquire()
try:
    # Sección crítica
finally:
    lock.release()

# … es equivalente a este
with lock:
    # Sección crítica
```

## Creación de Threads

En un objeto de una clase que hereda de `threading.Thread`, el método `run()` es el método que se ejecuta cuando se ejecuta `objeto.start() `. Es bueno recordar esto, porque es dentro de ese método es donde se debe implementar el comportamiento del __thread__. Un error común fue crear objetos a partir de una clase que heredan de `threading.Thread`, lo que es suficiente para crear un __thread__, sin embargo luego ejecutaban ´threading.thread(target=instanciaclasethread)´, lo que crea más objetos de los necesarios (un _thread_ B para correr un _thread_ A, en lugar de solo correr el _thread_ A que ya está instanciado).

## Simulación

Gran parte de esta actividad consistía en implementar una **simulación síncrona**, es decir, un programa que ejecuta acciones que involucran dejar pasar el tiempo. En particular muchas acciones debían ocurrir cada segundo. Para esto, una manera sencilla de implementarlo es:

```python
while distanciaHastaLaBatalla > 0:
    # Ejecutar lo que deba hacer durante ese segundo
    time.sleep(1)
```

De esta manera se “simula” que cada iteración del while corresponde a un segundo de la simulación. 
Dentro del método `run()` de los _threads_, en general se utiliza un ‘while’ con alguna condición para poder mantener al _thread_ funcionando hasta que se cumpla dicha condición. No se deben usar ciclos ‘for’ para esto ya que no se sabe en cuántas iteraciones del thread se va a satisfacer la condición debido a que, como se explica en los contenidos, los threads se ejecutan cada ciertos intervalos pequeños de tiempo que no son fijos.

Al hacer la simulación, hacerlo de manera continua (cada instante) puede ser muy problemático, es más costoso y con threads el coordinar cada suceso se vuelve difícil. En esta actividad bastaba con simular segundo a segundo, con eso si un dragón se pasaba de los 500m no importaba (porque ya habría llegado :D). 

## Término de _threads_ y _daemons_

Las clases `Dragon` y `Jinete` son __threads__, y en este caso el programa debía terminar luego de que una pareja lograra el objetivo, y no esperar a que todas terminen. La mejor forma de modelar esto es mediante el uso de *daemons*, definiendo ´self.daemon = True´. 

## Bloqueo de __threads__

Recuerda que cuando el dragón se pone a comer, no puede hacer nada más, por lo que es necesario indicar que está comiendo o evitar que haga otras cosas de algún modo cuando lo hace, no es válido solo indicarlo con un `print`.

```python
if esta_bloqueado:
    print(f’El dragón {nombre_dragon} se detuvo a comer en el segundo {tiempo_llegada}, la Dany está tratando de convencerlo’)
```

## Asociación Dragón-Jinete

Cuidado como están agregando parejas, en este caso Dragón-Jinete, a los equipos. Quizás fue la presión del tiempo pero una buena forma es agregarlos como tuplas de la forma `self.equipo.append((dragon,jinete))`. Eviten realizar instrucciones del tipo ```[jinete, dragon].append(self.equipo)``` si lo que se busca es agregarlos a la lista `self.equipo` porque no funcionará, ya que intentas agregar los equipos a la lista y si no guardas esta referencia estarás perdiendo lo que realiza finalmente el método `agregar`.

## Locks para escribir archivos

Muchos olvidaron que debían adquirir un lock antes de leer o escribir un archivo, lo que causaba que varios Jinetes escribieran al mismo tiempo, obteniendo un archivo final erróneo con líneas mal escritas y/o repetidas.

## Uso de events

Si bien el uso de `threading.Event` no era necesario para esta actividad, varios lo utilizaron y algunos lo hicieron bastante bien! Siempre es bueno explorar ideas, y el contenido enseñado en clases y talleres, solo recuerden hacerlo de manera precavida.

## Properties

Muchos controlaron la velocidad del dragón mediante un ´if´ en la secuencia ´while´ del método ´run´ del dragon. Cuando tienes atributos que vas a modificar constantemente y debes controlar el cambio puede ser mejor el uso de *properties*.

## Varios

Si bien no se evaluaba directamente en esta actividad, se volvió a ver mal uso de *args y **kwargs (los usan para llamar a la instancia, en vez de usarlos para definir un método de la clase o función). Además, se ve muy poco avance en algunos casos (un método definido y lo demás con pass), si a veces se atascan con alguna parte del enunciado y no pueden seguir avanzando, intenten realizar otra funcionalidad y luego vuelven. También a veces tratan de hacer las más difíciles o comprender mejor la idea del enunciado una vez completan ciertas funcionalidades que no necesariamente son las primeras que se les piden.

En general, no es buena idea alterar código pre-hecho para una actividad. Generalmente estos dan una orientación de para donde va la solución del ejercicio, y cambiarlas, te hace dejar de verlos.

La mayoría de las actividades revisadas tenían el 50% o más hecho, se notan que han mejorado en las actividades y que **los que van** a las actividades formativas realmente se esfuerzan por hacerla bien. 

Muchos construyen la función sobre los `pass` que tienen al comienzo (los dejan escritos al final). Si bien en general no debería pasar nada (a no ser que los dejen entre medio o al principio o algo así), la idea es que entreguen un código limpio aunque no alcancen a terminarlo.

**Comment by tomascortes** [comment]
Hola!, 
Me queda una duda, en la parte de "Verificando si el lock está tomado", al usar 
`while Dany.lock.locked():
    # Mientras no podemos “ocupar” a Dany, esperamos
    time.sleep(1)
with Dany.lock:`
Esto es una recomendación para que la usemos en futuro? o había que usarlo en la actividad para que esta esté correcta.
Ya que en este caso no había que ejecutar nada más mientras el dragon esperaba y hacer un while vacío era lo mismo.

Gracias

**Comment by roberto009** [comment]
Hola @tomascortes !
Esa parte era para este caso especifico.  Como la simulación se basaba en eventos que ocurrían cada un segundo, y muchas veces tenías que ir contando el tiempo transcurrido para luego imprimirlo en las estadísticas, era necesarios saber cuantos segundos se esperaron hasta poder entrar al `lock`. 

Normalmente, utilizar un `with lock ...`  es suficiente, ya que el programa espera hasta que el `lock` se libere para poder seguir ejecutándose.

Espero que eso resuelva tu duda 😄 
Saludos!

**Comment by tomascortes** [comment]
Gracias!
