### ISSUE TITLE
Dudas varias: Historial y deshacer jugada

### ISSUE THREAD

**Issue by augustoas** [IIC2233/Syllabus#263]
Hola ! Tengo dudas en el historial y el deshacer jugada. 

Historial: Por ejemplo si estamos en la jugada 10 y queremos volver a la 3 usando el historial, cómo sigue el juego en curso? Al próximo jugador que le toca vuelve a jugar desde la jugada 3? o el historial es solo algo visual y luego si se quiere seguir jugando se parte desde la jugada 10 nuevamente? En el caso que se siga jugando desde la jugada 3, las piezas que se pusieron desde la 4 hasta la 10 se vuelven a repartir? o esas piezas ya fueron jugadas?. Si se vuelven a repartir, el juego podría no terminar nunca, siempre se va a poder volver a estados anteriores y nunca habría un ganador. Por otro lado, si las piezas no se vuelven a repartir, el juego terminaría cuando se acaben estas, pero tambien va a estar la opción de que en la última jugada se pueda volver al estado 1 y siempre termine en empate. Si pudieran aclararme estos puntos sería bacán. 

Deshacer jugada: Acá tengo dudas en cómo calcular el puntaje, por ejemplo si el jugador 1 pone su primera pieza, luego el jugador 2 pone su primera pieza pegada a esta y el jugador 1 vuelve a poner otra en la misma linea y justo completa un río. En este momento se debería otorgar el puntaje por completar el río al jugador 1. Sin embargo, si el jugador 2, en su próximo turno, decide deshacer su movimiento anterior, quedaría un espacio entre medio de las piezas del jugador 1 y ahora el río no estaría completo. Cómo se otorga el puntaje en este caso? Debería restarle el puntaje que se obtuvo por completar el río al estar ahora incompleto? o el puntaje se calcula cuando ya está terminado el juego y se ve cómo quedó el tablero final? 

Gracias !

**Comment by Arcoirisky** [comment]
Sobre la pregunta de Deshacer jugada. Tu puedes elegir cuando calcular el puntaje así que puedes hacerlo al final o ir modificandolo a medida que se va jugando. Elige el que prefieras y no olvides el README :D
