### ISSUE TITLE
Parametros en los enunciados tarea 1

### ISSUE THREAD

**Issue by juanesjeep** [IIC2233/syllabus#263]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### El costo, tendencia y carga son parametros?

En el enunciado en 3.1 aparecen por ejemplo el costo de cierto tipo de barco en formato de parametro pero en el archivo aparecen que dependen de cada barco, entonces ¿se definen los parametro o no? y si es asi ¿donde se nececitarian?

**Comment by sperezmasri** [comment]
Hola @juanesjeep. A qué costo te refieres?  Si te refieres al costo de mantención, este atributo viene especificado en el archivo ```barcos.csv``` y es "personal" para cada barco. No encontré un costo que esté parametrizado en el ítem 3.1 🤔. 

Quedo atento a tu respuesta, saludos.
