### ISSUE TITLE
Formato "n" función encriptar_mensaje() entrega intermedia

### ISSUE THREAD

**Issue by k0rval4n** [IIC2233/Syllabus#263]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Buenas tardes, ¿en la función encriptar_mensaje() el "n" debe ir en el formato b"0" o en el formato b"\x00"? En el enunciado aparece como b"\x00" pero en los tests corregidos aparece como b"0". Gracias.
![image](https://github.com/IIC2233/Syllabus/assets/141952843/81d3ca84-62fa-410b-bed9-d4ea3411b82c)
![image](https://github.com/IIC2233/Syllabus/assets/141952843/a2db75e1-a5ae-4ef9-ba04-b61d47f38a0a)

**Comment by cverz** [comment]
Hola, tengo la misma duda :c

**Comment by nicolasaat** [comment]
Misma duda por acá, en los dos ejemplos del enunciado está en formato **b'\x00'** o **b'\x01'** , pero todos los tests públicos siguen el formato **b'0'** o **b'1'**

**Comment by ManuelGarreton** [comment]
Hola, tuve ese mismo problema, pero logre que se pusiera el número en b'0' y no en b'x00' pasando el int a un str y usando bytearray en utf-8

Algo así
n =  **suma de los bytes de A, B y C  en formato int** 
suma_bytes = bytearray( str( n ).encode('utf-8') )

ojala les sirva, pero aún así no entiendo si debe quedar en ese formato o en hexadecimal como en el ejemplo del enunciado :(

**Comment by LudwigUC** [comment]
Hola! efectivamente, deben utilizar n = bytearray(b'm'), siendo m igual a 0 ó 1 según corresponda.
Éxito en la tarea!

**Comment by gatochico** [comment]
¡Hola! 

Para complementar, efectivamente el enunciado tenía el formato b'\x00' o b'\x01', mientras que los tests usaban el formato b'0' o b'1'.

 Para solucionar dicho problema, haremos que los tests acepten ambos formatos para el `n` de la encriptación. Si revisan el syllabus, se han actualizado los casos del test08 para que acepten ambos casos como correctos.

Saludos y disculpen las molestias 🙏

**Comment by rleteliers** [comment]
Hola, no logro entender cuando cambia de "n' a 0 o 1, pense que era pon la cantidad de los bytearray a y c, pero no me resulta. preguntaba para saber que condicion debe pasar para que se un opcion o la otra

**Comment by LudwigUC** [comment]
> Hola, no logro entender cuando cambia de "n' a 0 o 1, pense que era pon la cantidad de los bytearray a y c, pero no me resulta. preguntaba para saber que condicion debe pasar para que se un opcion o la otra

Hola! te recomiendo leer la sección 7.1.4 del método de encriptación donde se describe esta condición, si te queda alguna duda nos dices ;)
