### ISSUE TITLE
Uso de jardines.txt para evaluar

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#263]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas. Tengo una duda, ¿los jardines que están en jardines.txt son los mismos jardines con los que nos evaluarán en la revision de la tarea? o habrán más jardines al momento de revisarnos?

**Comment by CrisDonosoMaass** [comment]
Hola! Se van a evaluar con los mismos jardines que les entregamos, pero para probar que el código sea funcional en todos los casos, los correctores tendrán que manipular el archivo jardines.txt. Así que en conclusión son los mismos jardines pero con pequeñas modificaciones, así que podrías considerarlos como que son totalmente nuevos.
