### ISSUE TITLE
[Recoreccion]

### ISSUE THREAD

**Issue by Okhan97** [IIC2233/Syllabus#263]
Hola buenas, tengo entendido que el medio oficial de recorrecciones es el formulario que se encuentra disponible para nosotros.
Sin embargo ya he mandado como 2 o 3 peticiones de recorreccion de la AC02 y no me responde nadie, mi nota no cambia y ni si quiera me llega un mail diciendo que ya lo revisaron o algo así ... ya que no funciona ese medio de contacto ¿ cual seria mi opción para que me puedan corregir esa actividad ? (Tengo un 1 por "inasistencia" pero si estuve esa clase) (La AC03 tambien necesito que me la recorrijan pero como no responden no he mandado peticion de esa en especifico)

**Comment by bamavrakis** [comment]
Estimado, el día Sábado envié un anuncio avisando que los resultados de la recorrecciones estarían durante el transcurso de esta semana (la cual al parecer aún no ha terminado). Se publicarán todas las recorrecciones juntas, así que solo te queda esperar. Si cuando se publiquen las recorrecciones aún no estás satisfecho con tu nota, deberás comunicarte con nosotros vía el formulario de contacto o bien con los profesores.
Saludos :)
