### ISSUE TITLE
QTimer y solapamiento de asignaciones

### ISSUE THREAD

**Issue by narispe** [IIC2233/Syllabus#263]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Hola tengo una duda sobre los efectos que puede tener el uso de varios timers para actualizar valores que se comparan o se manipulan entre sí. En el siguiente código como ejemplo, cuando algunos de los `timeout` de los timer_actualizar_... coincida con el `timeout` principal o justo mientras `funcion _principal` hace la comparación con los elementos de la lista, no tengo claro que pasará. ¿Los valores a comparar (valor o lista) se actualizarán desde ese instante y se seguirán comparando, o `funcion_principal` terminara de ejecutarse con los valores previos y se volvera a ejecutar casi de inmediato con los valores actuales, o la función es "reiniciada" sin terminar y se ejecuta con los valores actualizados?
~~~
def actualizar_lista():
    lista = [elem + 5 for elem in lista]


def actualizar_valor():
    valor = valor + 1


def funcion_principal():
    if any([valor == elem for elem in lista]):
        ...


timer_actualizar_lista = QTimer()
timer_actualizar_valor = QTimer()
timer_principal = QTimer()

timer_actualizar_lista.setInterval(500)
timer_actualizar_valor.setInterval(100)
timer_principal.setInterval(1500)

timer_actualizar_lista.timeout.connect(actualizar_lista)
timer_actualizar_valor.timeout.connect(actualizar_valor)
timer_principal.timeout.connect(funcion_principal)

lista = [ ... ]
valor = 0
timer_actualizar_lista.start()
timer_actualizar_valor.start()
timer_principal.start()
~~~

**Comment by Christian-Klempau** [comment]
Lo que pasará es que todos los timers se ejecutarán y harán lo que tengan que hacer en el código. Ahora, el **orden** en el cual los que coinciden se van a ejecutar no lo puedes predecir, ya que depende del sistema operativo cuál elige primero y segundo. Si quieres garantizar un comportamiento atómico, debes usar lock en una situación de este estilo.
