### ISSUE TITLE
 Duda : Vida Maxima

### ISSUE THREAD

**Issue by RichardUC** [IIC2233/Syllabus#263]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda respecto a los valores de la vida maxima en la seccion de ```Entidades - Combatientes```. En el enunnciado aparece:

```Vida Máxima: Corresponde a un int entre 0 y 100 que representa cantidad máxima de puntos de vida que puede tener el peleador```

1. **¿Puedo hacer el supuesto que la vida maxima se entre 1 y 100, para que asi no haya un combatiente "muerto"?**
2. **Y en caso de que no este permitido hacer el cambio ¿Debe de cargarse el combatiente, combatir y despues fallecer?**
3. **¿Ademas debe poder realizar todas las opciones de evolucionar, curarse, etc ?**

**Comment by gasparbenavente2** [comment]
Hola! Podrías suponer que la vida máxima va entre 1 y 100. De hecho si la vida maxima fuera 0 se indefine el calculo de ataque. 
<img width="483" alt="Screenshot 2024-04-20 at 4 32 15 PM" src="https://github.com/IIC2233/Syllabus/assets/127339088/e48631d7-05e3-4bfe-8623-42c07c88e0ee">
