### ISSUE TITLE
Tamaño del tablero - Tarea 00

### ISSUE THREAD

**Issue by scovarrubias** [IIC2233/syllabus#263]
Puedo asumir que siempre me van a entregar un int cuando se soliciten las coordenadas?

**Comment by jitorcas** [comment]
Hola! @scovarrubias 

La respuesta es no 😔, en las issues #103 y #199 responden de forma completa a tu pregunta! 

Éxito en la tarea ⚓️

**Comment by scovarrubias** [comment]
Gracias! Mala mía al no verlos antes.
