### ISSUE TITLE
DCC: utilidad funciones vender criatura y alimentos

### ISSUE THREAD

**Issue by jaimecoloma** [IIC2233/syllabus#263]
Hola! Tengo una duda respecto sobre cual es la utilidad de las funciones vender criatura y alimentos al magizoólogo del DCC. Si el magizoólogo ya tiene la capacidad de adoptar y comprar criaturas y alimentos que es lo que se espera que hagan las funciones nombradas del DCC? Genera algún cambio?

**Comment by Dnpoblete** [comment]
Hola @jaimecoloma lo que pasa es que como bien dices los magizoólogos tienen las habilidades de de adoptar DCCriaturas y de comprar alimentos (ojo que no existe la opción de vender DCCriaturas), pero estás acciones solo se pueden realiza en el menú DCC, por lo que dependen de esta entidad para poder realizar estás acciones y a su vez está debe revisar que se cumplan todos los requisitos para dar autorización a los magizoólogos. 

Espero haber respondido tu duda, y si no fue así responde esta issue para poder ayudarte! Éxito con la tarea 😄

**Comment by jaimecoloma** [comment]
Mmm la verdad es que no quede muy claro, me refería a que el DCC puede vender criaturas y alimentos y el magizoólogo adoptar y comprar, pero no entiendo si debo crear módulos para los dos porque según yo lo interpreto, siento que son lo mismo, y en el código usar ambas sería redundante. Entonces quiero saber bien cómo deben funcionar estas! 
Te agradezco la ayuda!

**Comment by Dnpoblete** [comment]
@jaimecoloma, lo que pasa es que no realizan lo mismo, por un lado los magizoólogos realizan la acción de adoptar y comprar, mientras que el DCC es el que fiscaliza que los magizoólogos puedan realizar esa acción, como por ejemplo revisar que tengan los sickles necesarios y en el caso contrario decir que no se puede. Adicionalmente, cuando se les entregue la distribución de puntajes, ahí se pide que tanto los magizoólogos como el DCC sean clases diferentes y que realicen acciones diferentes. 

Otra forma de plantearlo es que veas al DCC como un vendedor y a los magizoólogos como clientes, por lo que no hace sentido que solo uno compre y venda al mismo tiempo, pero si tiene sentido que el DCC venda y el cliente compre, ya que si bien son acciones complementarias, no son lo mismo y ambas se requieren por separado.

Por lo que lo ideal sería que los magizoólogos tengan un método comprar o algo por estilo, mientras que el DCC tenga uno de vender en donde verifica que se cumplan todas las condiciones.

Espero haber aclarado un poco más tu duda, en caso de no ser así avisame para explicarlo de otra forma! Éxito con la tarea :sparkles:

**Comment by jaimecoloma** [comment]
@Dnpoblete Entonces tendría que llamar al modulo del DCC de vender para que vea si el usuario es capaz de comprar o adoptar y luego según ese resultado llamar al modulo de adoptar o comprar del magizoólogo? sería como una función dividida en la parte del vendedor y del comprador?

**Comment by Dnpoblete** [comment]
Si cuando dices módulo te refieres a método de la clase la respuesta es sí! 😄

**Comment by jaimecoloma** [comment]
@Dnpoblete jaja ups, a eso me refería precisamente, muchas graciaas!!
