### ISSUE TITLE
Asignación de VARIABLES_ENUNCIADO

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#264]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas, una consulta, todas las variables del enunciado que tienen la forma "VARIABLE_ENUNCIADO" las cuales van en parametros.py debemos darles nosotros un valor??

**Comment by CrisDonosoMaass** [comment]
Hola! Sí, ustedes deben darle el valor pero deben asegurarse que tengan sentido y cumplan con las restricciones del enunciado. Por ejemplo, TEMP_INICIAL, la crean ustedes pero tiene que estar en el intervalo (-5, 25).

Espero haber respondido tu pregunta!
