### ISSUE TITLE
duda sobre archivo unidades

### ISSUE THREAD

**Issue by Martinluco** [IIC2233/Syllabus#264]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

En el enunciado sale que el archivo unidades tendrá igual formato que el archivo dificultad, pero en los archivos de la tarea no son iguales. Cual forma de archivo tomamos como definitiva?? Un solo texto separando gatos con ";" (dificultad) o gatos separados por linea como el archivo unidades.txt original
Muchas gracias :)

**Comment by wintermelyn** [comment]
Hola @Martinluco!

Cuando el enunciado menciona que el archivo unidades.txt tendrá el mismo formato que el usado en dificultad se refiere a que los parámetros de cada gato estarán en el mismo orden, es decir:

```txt
nombre,tipo,vida_maxima,defensa,poder,agilidad,resistencia
```

Por lo tanto puedes asumir que en el archivo unidades.txt solo tendrás un gato por linea, como el archivo entregado en su repositorio:
```txt
Natalia,GUE,70,15,7,5,7 # Gato 1
Patricio,GUE,90,16,7,7,7 # Gato 2
Amanda,MAG,55,9,10,6,5 # Gato 3
...
```

Por otro lado en el archivo de dificultad cada linea representa una ronda y cada gato de la misma ronda es separado por un `;` quedando de la siguiente manera:

```txt
Esteban,CAB,60,10,5,8,5;Diego,MAG,55,9,10,6,5;Benjamin,GUE,70,15,7,5,7 # Ronda 1
Cristobal,GUE,70,15,7,5,7;Julio,CAB,60,10,5,8,5;Clemente,MAG,55,9,10,6,5 # Ronda 2
Julian,MAG,55,9,10,6,5;Carlos,CAB,60,10,5,8,5;Diego,GUE,70,15,7,5,7 # Ronda 3
```

Espero haberte aclarado la confusión 😔

**Comment by Martinluco** [comment]
Todo muy claro, muchas gracias!!
