### ISSUE TITLE
PyQt4 vs PyQt5

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#264]
Hola!

Estuve viendo que en la materia de interfaces gráficas se usa PyQt4. Este semestre va a seguir así? Si es así, por qué usaremos PyQt4 en vez de PyQt5?

Saludos! 😄

EDIT: Acabo de ver que en el wiki dice que usaremos PyQt5. Podemos estudiar la materia subida? O hay muchas diferencias entre los dos PyQt?

**Comment by sebacruzd** [comment]
Se usará PyQt5. Aun no se actualiza la materia, pero se cambiará la actual por una con PyQt5.

Tiene varias similitudes y diferencias a la vez, personalmente no te recomiendo aprender qt4 porque después tendrás que aprender las diferencias y podrías enredarte.

Saludos!

**Comment by akaminetzkyp** [comment]
Perfecto, muchas gracias!
