### ISSUE TITLE
Ej propuesto 2.2 semana 5

### ISSUE THREAD

**Issue by isinahum** [IIC2233/syllabus#264]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Mi duda es sobre el uso de Event() en el ej propuesto 2.2 de la semana 5. El codigo hace lo que debería hacer si es que solo agrego lo siguiente:

![image](https://user-images.githubusercontent.com/48421382/115428310-43575b00-a1d0-11eb-8ae2-2a25863a14f2.png)

Asumo que hacer esto es hacer "trampa" porque deberíamos aplicar set() y wait() en la función, pero he probado aplicando el lock de eventos dentro de la función y ninguna de las combinaciones que probé hasta ahora me da el mismo resultado que concatenar start() y join(), como en la imagen. ¿Cómo puedo lograr esto mismo pero haciendo uso de Event?

**Comment by Julius9** [comment]
Hola @isinahum 😄  el siguiente código funciona bajo la misma idea de tu ejemplo

```
import threading
import time

def jugar_nivel(nivel, evento_nivel):

    #requiere la señal de nivel terminador
    evento_nivel_terminado.clear()

    print(f"¡Jugando nivel {nivel}!")
    time.sleep(1)
    print(f"Batallando en el nivel {nivel}")
    time.sleep(3)
    print(f"Terminando el nivel {nivel}")

    # se manda la señal de nivel terminado
    evento_nivel.set()
    

evento_nivel_terminado = threading.Event()

n1 = threading.Thread(target=jugar_nivel, args=[1, evento_nivel_terminado])
n2 = threading.Thread(target=jugar_nivel, args=[2, evento_nivel_terminado])
n3 = threading.Thread(target=jugar_nivel, args=[3, evento_nivel_terminado])
n4 = threading.Thread(target=jugar_nivel, args=[4, evento_nivel_terminado])

# =========== SOLO AGREGAR CÓDIGO DESDE AQUÍ HACIA ABAJO =============

evento_nivel_terminado.set()
n1.start()

evento_nivel_terminado.wait()
n2.start()

evento_nivel_terminado.wait()
n3.start()

evento_nivel_terminado.wait()
n4.start()
```

La estrategia es la siguiente, el main thread tambien puede parar su ejecución y esperar una señal de evento. Cuando se ejecuta la función ```jugar_nivel``` la señal se reseta con ```clear()```y el main thread para la ejecución, finalmente cuando termina la función se emite la señal con el ```set()``` y la ejecución sigue en curso.
