### ISSUE TITLE
Duda sobre archivo JSON

### ISSUE THREAD

**Issue by vichoassadi** [IIC2233/Syllabus#264]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo dudas de qué es lo que hay que escribir en el archivo con formato JSON en el servidor. ¿Es un archivo que se nos pasa más adelante del cual hay que sacar info? ¿O lo creamos nosotros con info del servidor?

Muchas gracias!

**Comment by CrisDonosoMaass** [comment]
Hola! El archivo JSON deben crearlo ustedes mismos y rellenarlo con información que consideren necesaria para el funcionamiento del servidor. Por ejemplo, el puntaje de todos los jugadores se guarda en el servidor, mientras que el cliente no tiene eso guardado en ninguna parte, porque en ningún momento utiliza el de todos los jugadores, solo recibe el TOP N para mostrar el ranking.
