### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#264]
Hola,
En mi diagrama de clases yo originalmente había creado una clase llamada "InitialP" que "conectaba" todas las clases (como pistas, vehiculos, pilotos, etc.) entre sí. Después de hacer mi código yo finalmente no hice esa clase, sino que hice que cada menú sea una función y además hice una función especial llamada "correr" para simular las carreras.
Con mi código, por lo tanto, no tengo ninguna "clase" exactamente que conecte todas las clases que nombré antes, sino que más bien serían funciones. Como debo mostrar esto en el diagrama de clases? Se puede conectar todas las clases a una función?

**Comment by aljara97** [comment]
Hola @FelipeA7 , creo que lo ideal es que crees una clase que contenga todas esas funciones y clases, ya que, el diagrama de clases se encarga de mostrar la interacción y relación entre estas últimas.

Dada la hora, te sugiero subir lo que llevas de tu tarea y que guardes el commit en caso de que haya algún problema al crear la clase que contenga los cambios relacionados, así podrás volver a ese commit y seguir trabajando desde ahí.

En el caso de que no logres crear la clase, te recomiendo especificar detalladamente en tu readme la inconsistencia entre el diagrama y el código.

Estaré averiguando si hay una forma de relacionar funciones con clases en un diagrama, pero lo más probable es que no sea posible.
