### ISSUE TITLE
Duda sobre archivo puntajes.txt

### ISSUE THREAD

**Issue by v1toco** [IIC2233/Syllabus#264]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

El archivo puntajes.txt lo debo crear yo, o mi código tiene que revisar primero que no exista este archivo y si no existe crear un archivo puntjaes.txt?

**Comment by catalinacarter** [comment]
Hola @v1toco! Lo segundo, tu código deberá encargarse de crear el archivo en caso de no existir al momento de ejecución, y luego cuando ya existe debe encargarse de actualizarlo correctamente cuando se agreguen puntajes :) En resumen: debe encargarse de **generar y actualizar el archivo.**
