### ISSUE TITLE
Primera pieza del juego

### ISSUE THREAD

**Issue by paula-ds** [IIC2233/Syllabus#264]
Hola, en mi programa cuando se abre el juego se imprime un mensaje en la consola de "Haz click en cualquier parte del tablero para poner la primera pieza al azar" entonces solo cuando el jugador hace click en el juego se coloca la primera pieza, ¿esta forma está mala? ¿y de no ser así, puede que me descuenten por esto?

**Comment by stephichau** [comment]
Queda a criterio tuyo.

Saludos!

**Comment by Kitaps** [comment]
Respecto a la primera pieza, por parte de la GUI, esta se selecciona al azar, pero nose de donde sale.
Me gustaría tener poder sobre esta (decidir yo donde poner, como tambien el color y tipo de esta) como hago eso?
Porque tengo gui.nueva_pieza como tambien un metodo backend_nueva_pieza, pero al inicial el juego donde se está ejecutando el gui.nueva_pieza para modificarlo?

**Comment by Jiparavich** [comment]
Up

**Comment by nlvargas** [comment]
@Kitaps Aquí lo explican bien: https://github.com/IIC2233/Syllabus/issues/252

**Comment by rakarachon** [comment]
Hola, otra duda respecto a la primera pieza (la que aparece al inicio del juego en el mapa en una posicion aleatoria). ¿Es necesario que esta pieza pertenezca al 'set de piezas' que nos dan en pieces.csv? O sea que si por ejemplo la pieza que sale al azar es tipo 'CCCCCC' y en pieces.csv dice que tengo x de esas piezas, después que esta pieza sea agregada al tablero al inicio tendré x-1 piezas 'CCCCCC' para pasarle a los jugadores.  De antemano gracias!!

**Comment by stephichau** [comment]
@rakarachon no es lo mismo? cualquier cosa, queda a tu criterio cómo se elige

**Comment by rakarachon** [comment]
@stephichau En verdad si, o sea de cualquier manera que lo haga la primera pieza sera aleatoria, que es lo que se pide, pero queria estar segura :) Gracias!!
