### ISSUE TITLE
Nuevos Archivos CSV T02

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233/Syllabus#264]
Hola! Actualizamos la base de datos de la T02 con los siguientes cambios: 

- Hemos reducido la cantidad de jugadores en el archivo `players_db.csv` de **5.501**  a **1.600** jugadores, esperamos que esto simplifique la resolución de la tarea. (El grafo sigue siendo conexo) 

- Subimos una segunda base de datos aun mas chica, de **200** jugadores solamente, para que puedan asegurar que funcione correctamente su tarea (También conexa)

- Por favor actualicen el archivo realizando `git pull` en sus repositorios de Syllabus

Es muy importante destacar que no evaluamos eficiencia con la Tarea, por lo que si se demora en correr no se preocupen! Mientras funcione, será corregido correctamente. (Siempre y cuando sea un tiempo razonable, menor a 10 minutos en el csv de mayor tamaño).

Animo con lo que queda de la tarea!

**Comment by llloyola** [comment]
Quizás sea un poco tonta mi pregunta, pero sirve 10.3 minutos? Eso me acabo de demorar en el csv de mayor tamaño 😢

**Comment by llloyola** [comment]
Estoy usando el algoritmo de Dijkstra para calcular la afinidad entre un jugador y sus desconocidos. En eso me estoy demorando 10.3 minutos, usando el csv de mayor tamaño 😢 Está muy mal?
