### ISSUE TITLE
Cómo escoger el tipo de Magizoólogo

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#264]
Hola! Cuando se crea un nuevo usuario, el elige el tipo de magizoologo que será o es aleatorio? No encontré esa información en el enunciado.

**Comment by moquezada** [comment]
Hola @tedroppelmann, en el segundo párrafo de la sección 3.1 se menciona lo siguiente:  

![Captura](https://user-images.githubusercontent.com/43896576/78556660-5a9df300-77dd-11ea-8bb3-e2086cc7fc90.PNG)

Por lo tanto, el usuario debe poder escoger el tipo de magizoólogo 😄
