### ISSUE TITLE
Ventanas importando .ui

### ISSUE THREAD

**Issue by Witomi** [IIC2233/syllabus#264]
Hola!

Tengo el problema que cuando creo una ventana en Qt   designer y la guardo, al tratar de abrirla en python me salen algunos labels cortados en el sentido que no se ven completamente las palabras como muestra la imagen, no he cambiado en nada las dimensiones de los labels en python y si me fije de que el cuadrado donde se pone el label fuera del tamaño suficiente para que se vea(enQt designer):(.
![Labels afectados](https://user-images.githubusercontent.com/48265428/57891858-ea743080-780a-11e9-9a71-5fb7a4631a47.jpg)
Muchaas gracias!!

**Comment by hbkim94** [comment]
Hola @Witomi ,

Prueba poniendo esto al principio de tu archivo de frontend, justo después de tus imports:

```python
QApplication.setAttribute(Qt.AA_EnableHighDpiScaling, True)
```

Cuando yo hice el ramo, tuve problemas similares debido a conflictos con la resolución de mi pantalla, y me resultó. Espero que también sea el caso para ti!

**Comment by Witomi** [comment]
> Era justo eso!!!! muchas gracias 👍😄

**Comment by Witomi** [comment]
Hola!

me pasó que despues del menú al mostrar la ventana del juego me aparece gigante, y al parecer se arregla poniendo QApplication.setAttribute(Qt.AA_DisableHighDpiScaling, True), lo cual pongo antes de instanciar la clase front_Juego, pero aun así se ve muy grande, sin embargo, si lo hago justo despues de los import en donde puse tu codigo "QApplication.setAttribute(Qt.AA_EnableHighDpiScaling, True)" ahi se ve bien la ventana del juego pero no la del menú :(
