### ISSUE TITLE
Importar venatana con gridLayout ui

### ISSUE THREAD

**Issue by fivaldivia** [IIC2233/syllabus#265]
Hola, quería saber si me pueden ayudar, ya que al crear el mapa sin importar una ventana de Qt Designer se crea bien, pero si importo una ventana que contiene un gridLayout, me quedas asi:
[Duda progra.docx](https://github.com/IIC2233/syllabus/files/3189340/Duda.progra.docx)
Hay algun comando que me permita arreglarlo desde la consola, ya que depende del tamaño del gridLayout a mi parecer, y probe cambiando en Qt designer pero no pude.
Muchas Gracias

**Comment by hbkim94** [comment]
Hola @fivaldivia !

Si al armar tu ventana usando QtDesigner todo se ve bien pero no al correr tu programa desde consola, intenta usar el método mencionado en la issue https://github.com/IIC2233/syllabus/issues/264 (si es que no lo has hecho). Espero que te resuelva el problema!
