### ISSUE TITLE
Duda altura planta

### ISSUE THREAD

**Issue by Agusrush21** [IIC2233/Syllabus#265]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, mi duda es que en el enunciado especifica un valor de la altura de la planta, que por lo que veo en imagenes esta altura se ve representada en el tablero, como por ejemplo: 
![Screenshot_23](https://github.com/user-attachments/assets/38526337-0642-4c1a-9aa8-1c09b1cfe723)
Donde entiendo, por el ejemplo, en este caso hay una planta solaretillo que tiene una altura de 2 celdas, entonces si al momento de cultivar una planta, el usuario quiere colocar una justo donde intercepta la altura de otra, ¿la planta en cuestión se elimina para colocar la nueva? o ¿solo se elimina esa extension de la planta y coloco la nueva en la posicion requerida?

**Comment by CrisDonosoMaass** [comment]
Hola! Lo que se ve en el tablero no es la altura de las plantas, es su posición en el jardín. Lo que tú dices que es una planta de altura 2, son realmente dos solaretillos uno en [2,1] y el otro en [3,1]. La altura sólo es un atributo que usa la planta para sus métodos, pero no representa nada en el tablero.

**Comment by Agusrush21** [comment]
Vale vale, ahora todo me quedo claro, muchas gracias.😁
