### ISSUE TITLE
Valores Afinidad Figura 4

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#265]
Hola! Sólo para salir de la duda... En la Figura 4 del enunciado, sale una cancha con jugadores y sus distintos valores de afinidad. Eso valores de afinidad son arbitrarios (inventados) o son valores que pueden darse entre jugadores desconocidos? Pues casi ninguno de mis valores de afinidad de desconocidos calza con los de la figura, lo cual me hace pensar que voy (**muy**) mal encaminado.

**Comment by iqacevedo** [comment]
Hola, 

Los valores de afinidad de esa figura son arbitrarios (inventados), así que no te preocupes de que calcen con los que te dan a ti.

Saludos !

**Comment by Cschavez** [comment]
y esos mismos valores de afinidad (para el campeonato), se calculan con el grafo de 1600 jugadores o con el grafo de 200 jugadores que se le entra al Demo?

**Comment by ignaciohermosillacornejo** [comment]
Hola @Cschavez
Si creo que te entiendo, te refieres a que los valores del enunciado para el campeonato los calculamos con el grafo de 1600 jugadores o el de 200? Te contesto que esos numeros son inventados, por lo que no tienen ninguna relación con lo que te podría estar dando a ti. 
En todo caso tu debes poder calcular esos valores independiente del grafo que le pasemos a tu tarea, por lo que tu solución debe ser genérica. Piensa que podemos corregir tu tarea con cualquier grafo que queramos.
