### ISSUE TITLE
Como crear y usar .gitignore

### ISSUE THREAD

**Issue by enriquerussi** [IIC2233/syllabus#265]
Hola, entiendo que necesitamos usar .gitignore para juntar los archivos que no nos interesan para correr el programa pero ¿como TÉCNICAMENTE se crea  y usa esto del .gitignore?

**Comment by Tsbalart** [comment]
Hola @enriquerussi!
Lo que debes hacer es crear un archivo cuyo nombre sea ".gitignore", en el debes escribir el nombre de los archivos y/o las carpetas que deseas que sean ignorados al hacer git push.
Puedes encontrar un ejemplo y una explicación mas detallada de este archivo en la carpeta principal del syllabus https://github.com/IIC2233/syllabus/blob/master/.gitignore
Espero que se haya entendido, cualquier duda puedes volver a comentar esa issue.
Saludos y éxito con la tarea!
