### ISSUE TITLE
Agregar parámetros a métodos de demo.py

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#265]
Hola! Puedo agregar más parámetros a los métodos de la demo.py? Por ejemplo, puedo convertir el método colocar_pieza(self, i, j) en colocar_pieza(self, i, j, nuevo_parametro) ?

**Comment by TomasSalvadores** [comment]
Claro! Puedes sobreescribirlos como se dice en el enunciado, pero recuerda que no puedes modificar nada de la carpeta gui, por lo que esos cambios deben ser para interactuar con tu programa y no con la interfaz.
