### ISSUE TITLE
Fiscalizar criaturas escapadas

### ISSUE THREAD

**Issue by EmeraldMP** [IIC2233/syllabus#265]
Hola!

Quisiera saber si en fiscalizar magizoologo tengo que revisar cada criatura que tenga y por cada una de ella pagar la multa o basta que una se haya escapado, esté enferma o tenga salud baja para aplicar la multa solo una vez.

Gracias

**Comment by mpsubiabre** [comment]
Hola @EmeraldMP!

Como bien dice el enunciado, múltiples eventos del mismo tipo deben ser revisados de forma separada, por lo que debes revisar cada criatura. Por ejemplo, si en un mismo día se escaparon dos criaturas, debes realizar dos procesos de fiscalización por cada una de ellas.

Espero que te haya quedado claro, si aun tienes dudas comenta esta issue:)

**Comment by EmeraldMP** [comment]
Perfecto, gracias!

**Comment by moquezada** [comment]
@EmeraldMP no cierres las issues que realices por favor, ya que a otros les puede ser de utilidad. El cuerpo docente se encargará de cerrarlas cuando sea oportuno 😄

**Comment by MINGOD24** [comment]
Hola,
Que sucede si tengo una criatura que se escapo hace varios dias, se debe cobrar una multa todos los días que se encuentre escapada, o solo una vez?

**Comment by mpsubiabre** [comment]
Hola @MINGOD24 !

Tu duda esta resuelta en la issue #369 :)

De lo contrario comenta para poder ayudarte, pero estoy segura que con esa issue te quedara claro 😄
