### ISSUE TITLE
Tener muchas labels hace que el programa vaya más lento? ¿Se pueden eliminar?

### ISSUE THREAD

**Issue by Francisco-Aguilera-xd** [IIC2233/Syllabus#265]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! en la medida que voy avanzando en la tarea he notado que a veces se relentiza el programa, en el cual voy creando muchos labels. ¿La cantidad de labels que existan afectan en el rendimiento del computador, o se debe a los Threads/Timers que uno pueda tener?
Si los labels consumen memoria y relentizan el programa, ¿Hay alguna forma de eliminarlos para que el programa ande mejor?
Gracias de antemano

**Comment by Maxi1805** [comment]
Hola @Francisco-Aguilera-xd, pueden afectar sobre todo en este tipo de actividades donde las labels están en constante cambios por el uso de timers y threads, por ejemplo mientras mas labels de autos tengas, mas trabajo que hacer tu código para ir moviendo cada una de ellas a una posición distinta. Por lo que pude ver en tu código te diría que uses el método deleteLater() en las labels y además quites el auto de la lista para reducir las iteraciones.
Espero te sirva.

**Comment by Francisco-Aguilera-xd** [comment]
Vale perfecto, muchas gracias!
