### ISSUE TITLE
No entiendo la clase Tipos de Combatientes

### ISSUE THREAD

**Issue by JSalas277** [IIC2233/Syllabus#265]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Resulta que al tratar de armar la clase, para cuando quiero crear el init resulta que me confundo al ver cuales son los elementos que deberia tener, ¿pongo los nombres de las clases? ¿o las probabilidades y demas? ¿No se supone que todos esos datos deberian estar en combatientes? ¿O es que acaso debo hacer una clase por tipo? Necesito alguna explicacion que pueda aclararme esto.

**Comment by gasparbenavente2** [comment]
Hola! Depende de ti como lo quieras implementar pero lo ideal sería tener distintas clases para los tipos de combatientes, aunque fíjate que comparten atributos/métodos por lo que puede ser más conveniente que de alguna forma estén relacionados. Te recomiendo revisar contenido de herencia.
