### ISSUE TITLE
Duda con el evento de barco carguero

### ISSUE THREAD

**Issue by Icarus328** [IIC2233/syllabus#265]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo la duda de que, cuando ocurre el evento del barco carguero, elimino posteriormente el barco del juego? ya que dice que este no puede cruzar el canal, o lo encallo?

Gracias

**Comment by santiagovegaf** [comment]
Hola @Icarus328!

Como no se especifica que el barco carguero debe ser eliminado o encallado después de un ataque pirata, se puede asumir que este continúa en el canal como un barco cualquiera. Esto ocurre hasta que recorre todo el canal y sale sin pagar.

Espero que esto aclare tu duda y quedo atento a cualquier comentario!

**Comment by tamyhan** [comment]
Hola! En este caso, mientras el barco sigue en el canal se le sigue pagando el costo de mantención?

**Comment by santiagovegaf** [comment]
Hola! 

En el enunciado se especifica lo siguiente: 

![image_2021-04-27_130543](https://user-images.githubusercontent.com/57118271/116282854-45ce2d80-a759-11eb-9566-f79b8cfb79f5.png)

Como no se menciona nada sobre lo que pasa si a un barco carguero  le ocurre un evento especial, **es correcto asumir que se le seguirá cobrando hasta que salga!**

Espero que se aclare tu duda!
