### ISSUE TITLE
DCCriaturas caracteres alphanuméricos

### ISSUE THREAD

**Issue by MariaJoseCovarrubias** [IIC2233/syllabus#266]
Hola! En el enunciado dice que los nombres de las criaturas debe estar compuesto por caracteres alfanumericos, sin embargo, en el archivo criaturas.csv, los nombre sólo tienen letras. 
Nos quedamos con que el nombre puede estar formado solo por letras?

**Comment by jeschuwirth** [comment]
Hola @MariaJoseCovarrubias, 

Entiendo la confusión con la T0, los caracteres alphanumericos son tanto letras como números, sin embargo no es obligatorio que estén ambos, por lo tanto si esta compuesto por solo letras es efectivamente alphanumerico aunque no tenga números.

En la T0 se pedía que los nombres de usuario sean alphanumericos (no tengan caracteres que no sean letras ni números como / # $ %), y además se pedía que estén compuestos por letras **y** números.

Éxito!
