### ISSUE TITLE
Duda parametros.py

### ISSUE THREAD

**Issue by criss199** [IIC2233/syllabus#266]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola tengo una duda con los valores de los parametros, que debemos incluir en el archivo "parametros.py", en el enunciado nos dicen que debemos incluir todos los que sean de ESTE_FORMATO, mi duda esta en los valores de los parametros, estos deben ser definidos por nosotros o estan en algun lado, que no los encuentro... por ejemplo DINERO_INTOXICACION, como defino el valor que debe tener

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]
``

**Comment by Emiliax16** [comment]
Hola! la issue [#226 ](url) habla de esto. De todas maneras, te recomiendo que los defina de acuerdo a las condiciones del enunciado. Ej.: si necesitas que un evento pueda ocurrir con mayor probabilidad, prueba varios valores de los parámetros hasta que lo obtengas.

**Comment by Emiliax16** [comment]
Hola! la issue [#226](https://github.com/IIC2233/syllabus/issues/226) habla de esto. De todas maneras, te recomiendo que los defina de acuerdo a las condiciones del enunciado. Ej.: si necesitas que un evento pueda ocurrir con mayor probabilidad, prueba varios valores de los parámetros hasta que lo obtengas.
