### ISSUE TITLE
boton para poner plantas

### ISSUE THREAD

**Issue by solebravo** [IIC2233/Syllabus#266]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! queria saber si seria "legal" implementar un boton para posicionar las plantas (los 4 de tienda mas uno que apretar tras hacer click) o si seria un descuento muy grave, claro que especificándolo en el ReadMe.
Gracias de antemano!

**Comment by Lord-Kelsier** [comment]
Hola @solebravo, no estoy muy seguro si entiendo lo que propones, te refieres a que haces click donde quieres plantar y luego apretas un boton que recuerde el ultimo click?

**Comment by solebravo** [comment]
Hola! si algo de ese estilo, primero apretas el boton de la tienda, luego el cuadrado de pasto donde quieres poner la planta y luego un boton de "plantar" para que este retenga la ultima coordenada

**Comment by Lord-Kelsier** [comment]
Si, es valido, igualmente ten ojo ya que al hacer clic  en el boton se te podria reescribir esta ultima coordenada
