### ISSUE TITLE
Vida Máxima 0

### ISSUE THREAD

**Issue by coniverav** [IIC2233/Syllabus#266]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

La característica vida máxima de los combatientes se debe definir en un rango de 0 a 100, pero qué pasa si la vida es 0? descarto al tiro al combatiente, sin dar ningún ataque al combatir?
Además, cómo calcularía el ataque si quedaría una división por 0?

<img width="557" alt="image" src="https://github.com/IIC2233/Syllabus/assets/162245893/68235d68-da96-402f-9b95-e804c2a21731">

**Comment by wintermelyn** [comment]
Hola @coniverav!

Esta duda ya fue respondida en la issue #263 😉
