### ISSUE TITLE
Cambiar teclas de Cheatcodes

### ISSUE THREAD

**Issue by Dyotson** [IIC2233/Syllabus#266]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, encontre un problema con los cheatcodes, especificamente el V+I+D, donde la tecla D tambien esta asociada al movimiento, por lo cual no se pueden hacer las dos cosas al mismo tiempo. ¿Existe la posibilidad de cambiar el cheatcode a algo más?

**Comment by rodrigobj99** [comment]
Hola @Dyotson! Este caso no tiene porque ser un problema ya que lo puedes manejar de acuerdo a la situación, por ejemplo puedes hacer que D solo realice un movimiento si las dos teclas apretadas anteriormente no son V e I (en caso de que estes implementando el presionar en orden) o que D solo realice un movimiento si no se estan apretando al mismo tiempo V e I (en caso de que estes implementando el presionar simultaneamente).

Espero te sirva, cualquier cosa me avisas, saludos!
