### ISSUE TITLE
Método secreto para usar *args en mis EDD

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#266]
¿Existe algún método secreto con el que pueda configurar el uso del asterisco, para que si tengo una lista (de la clase Lista creada por mi), si hago *lista desempaqueta la lista?

**Comment by mjgutierrez1** [comment]
Ya busqué en google pero no pude encontrar porque todo lo que me salía era cómo usar *args y *kwargs

**Comment by diegovaras97** [comment]
Un poco con el tema, si es que no hay un método se puede usar *args/*kwargs?

**Comment by cilopez** [comment]
@mjgutierrez1 si bien no estoy seguro que exista esa implementación, puedes crear tu función en tu estructura que sea ``desempaquetar(self)`` que entregue cada elemento de tu estructura, que para términos prácticos sería lo mismo.
@diegovaras97 como le respondo a Mauricio, el método lo puedes crear tu pero no tendrías la sintaxis ``*Mi_estructura`` nose muy bien si esta sintaxis sirve para tu duda
