### ISSUE TITLE
Menú intermedio

### ISSUE THREAD

**Issue by ClementeCW0** [IIC2233/syllabus#266]
Hola!

En el enunciado dice que si el usuario escoge la opción "Iniciar una partida" en el menú de inicio se le debe pedir un nombre, y de ingresar este incorrectamente, ofrecer la opción de ingresar uno nuevo o volver al menú de inicio. Una vez ingresado el nombre correctamente, se le deben pedir las dimensiones del tablero.

Pregunta:
¿Puede suceder todo esto en un menú intermedio?

 Por ejemplo, una vez que el jugador escoge la opción "Iniciar una partida", se abra un menú en donde el jugador puede ingresar su nombre, ingresar el tamaño del tablero, seguir al menú de juego (si ya ingresó los datos necesarios) o volver al menú de inicio. En este ejemplo si el usuario no escogiera un nombre válido, se le ofrecería la opción de volver al **menú intermedio** o volver a ingresar su nombre, por lo que se crearía un pequeño conflicto con el enunciado :(

Gracias de antemano!

**Comment by matiasmasjuan** [comment]
Hola @ClementeCW0 !

Si bien puedes crear **Menús extras** si lo estimas conveniente, debes cumplir como **mínimo** todos los requerimientos dados en el **enunciado**. En este caso, puedes crear el **Menú Intermedio** **siempre y cuando** ofrezcas la opción en **ese Menú** de **Volver al Menú de Inicio**. De esta forma, en caso de cometer algún error al ingresar el nombre o las dimensiones del tablero, se pueda **volver** al **Menú de Inicio**.

Espero haber respondido a tu pregunta, y mucho éxito con la tarea! :smile:

**Comment by ClementeCW0** [comment]
Perfecto! Muchas gracias :)
