### ISSUE TITLE
Dudas Demo.py

### ISSUE THREAD

**Issue by sicorrecto** [IIC2233/Syllabus#266]
Hola, lei las issues y sigo con muchas dudas.

1. Según lo que entendí la parte del grafo de afinidades y las consultas sobre este se hacen aparte en otro código. Cierto?

2. En Demo.py hay un método entra_jugador y cambio_jugador que no tienen nada escrito, pero al correr Demo.py puedo meter y sacar jugadores de la cancha sin ningun problema. No entiendo para que serian estas funciones.

3. En Demo.py hay un ejemplo de jugadores y equipos, la idea es que borremos esas listas de listas y pongamos una función nuestra que devuelva una lista nuestra (no de python) en el mismo formato (iterable y los valores como string en ese orden)?

4. En Demo.py, los métodos que debemos rellenar, deben devolver métodos de la GUI para ver los cambios en la interfaz o solo deben llamarlos y no devolver nada?

**Comment by behrmann97** [comment]
Holaa,
1. Sip
2. entra_jugador se llama para los primeros 11 jugadores que el usuario clickea para armar su equipo. cambio_jugador se llama siempre que se haga un cambio de dos jugadores. Estos métodos se llaman con los nombres completos de los jugadores, de manera que tú puedas escribir un código que actualize la esperanza de ganar del equipo dependiendo de los cambios (recuerda que no debes cambiar interfaz.py ni clases.py).
3. Sip
4. Deben llamarlos, no es necesario que retornen estos métodos, a exepción de algunos que se especifica lo que deben retornar. Por ejemplo, al llamar a agregar_resultado("equipo_1 2 - 0 equipo_2"), se agregará ese resultado a la tabla de resultados del campeonato, sin necesariamente haber retornado algo.

Espero que te sirva, saludos 😄
