### ISSUE TITLE
Uso de Qrect para modelar intersecciones

### ISSUE THREAD

**Issue by MGome** [IIC2233/syllabus#266]
Para usar QRect para fijar los obstáculos y así poder encontrar las intersecciones es más conveniente fijarlos al momento de hacer el mapa? o al momento de realizar un movimiento?

**Comment by jmwielandt** [comment]
Hola, ambas opciones son igual de válidas, una prioriza memoria mientras la otra procesamiento, tienes que elegir tú cual prefieres implementar 🙂
