### ISSUE TITLE
Se puede usar el isinstance?

### ISSUE THREAD

**Issue by santiagofh1** [IIC2233/Syllabus#266]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

se puede usar la built-in "isinstance" en la tarea?

**Comment by CrisDonosoMaass** [comment]
Hola! Sí pueden usarlo ya que es una función built-in de python.
