### ISSUE TITLE
Elección de quien parte jugando

### ISSUE THREAD

**Issue by tolavarria** [IIC2233/syllabus#267]
Hola,
Durante el transcurso del programa, puedo implementar alguna línea de código que implique un input del usuario mas allá de los que me piden en el enunciado?
Ejemplo: para decidir quién empieza jugando quiero entregar la opción de que el usuario elija cara o sello y a partir de eso tirar una "moneda virtual" que lo decida.
Esto implica una funcionalidad extra y no sé si está permitido hacer este tipo de 'bonus' al código.
Saludossss

**Comment by Tsbalart** [comment]
Hola @tolavarria!
Esta bien que quieres implementar cosas extra, siempre y cuando no contradigas el enunciado, y especifiques muy bien tus funcionalidades extras en tu readme.
