### ISSUE TITLE
Duda sobre la tripulación de cada barco

### ISSUE THREAD

**Issue by enriquerussi** [IIC2233/syllabus#267]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Dado que cada barco tiene una tripulación de entre 1 a 3 personas, ¿los roles de estas personas en el barco se pueden repetir? Por ejemplo, que un barco tenga 3 tripulantes y todos son capitanes, por lo que podrían desencallar el barco automáticamente 3 veces.

**Comment by Emiliax16** [comment]
Los tripulantes de un barco nunca tienen roles repetidos, independiente del número de tripulantes que haya.
