### ISSUE TITLE
Duda puntos del bonus

### ISSUE THREAD

**Issue by bpeirano1** [IIC2233/syllabus#267]
Hola,
Si mis enemigos se mueven siguiendo el camino mas corto y mi tarea tiene una nota menor a 5.0,
¿igual obtengo el puntaje en la pauta por el movimiento de los enemigos, aunque estos no se muevan aleatoriamente?

**Comment by jmwielandt** [comment]
Hola!
Sí tendrás puntaje si el movimiento está bien hecho.

Ánimo con la tarea~
