### ISSUE TITLE
Recurcion error, buscar afinidad

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#267]
He implementado un método para encontrar la afinidad, y en algunos casos ocurre un recursión error, ya que son jugadores muy alejados, será esto un problema, si fueran menos de 1000 jugadores esto nunca ocurriria

**Comment by yoavnavon** [comment]
Hola! Justamente como dices, al ser muchos datos, quizás un algoritmo recursivo se caiga, ya que los computadores tienen un limite de recursiones posibles. Si te está pasando esto, quizás puedes transformarlo a un algoritmo iterativo, ya que por ejemplo no hay limite de cuantas veces se pasa por un `while`. Espero se haya entendido!
