### ISSUE TITLE
Nombre de variables y metodos

### ISSUE THREAD

**Issue by TomasAguirrebena** [IIC2233/Syllabus#267]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo la duda de que si es obligatorio usar los nombres que nos dan para los métodos y variables, por ejemplo si al gato mago lo quiero llamar knight cat o al método combatir fight, básicamente que tengo la costumbre de usar mis variables en ingles, o por temas de revisión automatizada necesito que tengan los nombres dados.

**Comment by gasparbenavente2** [comment]
Hola! Puedes usar los nombres de variables/métodos que funcionen mejor para ti siempre y cuando se pueda reconocer entre ellos. Si los nombres son poco descriptivos o no tienen sentido se podría aplicar descuento de malas practicas o PEP8, pero por hacerlo en inglés no hay ningún problema.

**Comment by TomasAguirrebena** [comment]
vale gracias !!!
