### ISSUE TITLE
Borrar estados historial

### ISSUE THREAD

**Issue by Sforrego** [IIC2233/Syllabus#267]
queria saber si puedo no usar la funcion:

![image](https://user-images.githubusercontent.com/26422390/30241374-91c62b50-9558-11e7-8b25-6dd4ecc4f003.png)

viene definida con demo.py pero no creo que sea la mejor manera para tratar con el historial, si la respuesta es un si, simplemente la borro y lo escribo en el readme, o mejor la dejo ahi y no la uso(?).

y queria asegurarme, supongamos que yo tengo los estados 1, 2, 3 y 4, y decido volver al estado 2, se borran los estados 2, 3 y 4 cierto?

muchas gracias!

**Comment by stephichau** [comment]
Puedes usar la función, pero no te lo recomiendo. Con respecto a tu otra pregunta sí, se borran.

Saludos!
