### ISSUE TITLE
emit no conecta 

### ISSUE THREAD

**Issue by LunaGarces** [IIC2233/Syllabus#267]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[el emit que se hace en la clase Principal2 ]

**Comment by DiegoMillaUC** [comment]
Hola Luna! El error por el que te salía <unbound PYQT_SIGNAL )> era debido a que estabas imprimiendo la señal luego de instanciarla, en la imagen se aprecia:
![image](https://user-images.githubusercontent.com/80900494/195216095-c53da50d-bb82-4b77-9e24-02867b393f2e.png)

**Comment by Lord-Kelsier** [comment]
Hola @LunaGarces, no se si @DiegoMillaUC ya respondio a tu duda pero encontre otro problema, en la clase Principal2, en efecto la señal nunca se emite. Esto se debe  a que cuando conectas las señales en la funcion conectar de main.py

`self.f_principal.senal_jugador.connect(self.juego.jugador)`

estas conectando la señal de `self.f_principal` que lo instanciaste en el init
pero  en la linea 34 de visualizacion.py:
`self.ui = Principal2()`  estas creando una nueva instancia de `Principal2`, y esta nueva instancia es quien al apretar el boton comenzar manda la señal, pero como la señal estaba conectada a la primera instancia nunca es recibida por `Juego`.

**Comment by Lord-Kelsier** [comment]
Otra cosa, para solucionar esto tendrias que modificar varias partes del codigo, pero existe una solucion mas simple, usar un patron de diseño _(esto se ve en ingenieria de software)_ , en particular el patron **Singleton**, esto implica que solo puede existir 1 instancia de los objetos y al crear una nueva, se retorna la que ya existia. [Aqui una forma de implementar singleton en una clase en python](https://refactoring.guru/design-patterns/singleton/python/example#example-0)

**Comment by LunaGarces** [comment]
Gracias!! Era el error que no encontraba
