### ISSUE TITLE
El keypressevent Space no funciona cuando hay QPushButtons

### ISSUE THREAD

**Issue by PolloDK** [IIC2233/Syllabus#267]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Si tengo en el KeyPressEvent el siguiente código y además botones en la misma ventana, al apretar espacio se presiona el primer botón y no se ejecuta correctamente el código para el salto. Saqué los botones para probar el salto y funciona perfecto, pero con los botones no se ejecuta. ¿Hay alguna manera de solucionar este problema?

`    def keyPressEvent(self, event):
        if event.key() == Qt.Key_Space:
            self.senal_tecla.emit("_")`

**Comment by Crisax234** [comment]
Me pasa exactamente lo mismo hay alguna manera de solucionarlo?

**Comment by try-except** [comment]
Podrían sobreescribir el método `event` de la clase `QPushButton` y dentro de ese `event` capturar todos los `event` que cumplan con `event.type() == QEvent.KeyPress` y si la tecla presionada es un espacio, emitir la señal que quieran.

Post de SO de referencia: https://stackoverflow.com/a/50935602

**Comment by vice-rosas99** [comment]
a mi me pasaba que al apretar la space bar no levantaba un keyevent, pero si aprieto 'alt' empieza a funcionar
