### ISSUE TITLE
Feedback tarea 1

### ISSUE THREAD

**Issue by chapito96** [IIC2233/Syllabus#267]
En el mail del 12 de abril mencionaban que en la tarde de ese día recibiría el feedback de la tarea 1.
Apelando a un atraso administrativo, decidí esperar hasta hoy, pero aún no me ha llegado.
Quedan 3 días para mandar corrección de la T1 y me gustaría tener el feedback para hacerlo

**Comment by FernandoPieressa** [comment]
Hola! No tienes feedback porque tu tarea no fue corregida como la subiste mal.

El formato de entrega de cada tarea es:

Cada tarea debe estar contenida en una carpeta llamada TXX donde XX es el numero de tarea: Como por ejemplo la tarea 1 tiene que estar en T01, mientras que tu pusiste T1

Tendrás que mandar la solicitud para que sea recorregida junto al descuento por mal subida.

Saludos!
