### ISSUE TITLE
Duda con la paleta de colores de las ventanas

### ISSUE THREAD

**Issue by ItsSancer** [IIC2233/Syllabus#267]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!

Mi duda es que en las imagenes de ejemplo del enunciado, el fondo de las ventanas, el inventario y el hall of fame tiene una paleta de colores rosada que combina con el logo del juego y con las sprites del conejo y del laberinto, pero no encuentro esos colores en especifico en el archivo parametros. Tengo que obligatoriamente usar esa paleta de colores o puedo usar otra que combine con los spites? (por ejemplo turquesa o rojo pastel)

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by ignacio-sp** [comment]
Hola @ItsSancer! Son libres de escoger los colores que ustedes prefieran para el frontend, siempre y cuando se siga que el diseño sea cohesivo y de bajo acoplamiento.

**Comment by oliviallanosj** [comment]
hola, para los estilos de texto y el tamaño de las palabras también hay que hacerlos exactamente como en la foto del enunciado?

**Comment by ignacio-sp** [comment]
Hola @oliviallanosj, no es necesario que los textos se vean exactamente igual a los del enunciado, pueden cambiar los estilos y tamaños si así lo desean
