### ISSUE TITLE
Duda sobre máximo caracteres PEP8 

### ISSUE THREAD

**Issue by elisaorchard** [IIC2233/Syllabus#267]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. Estoy haciendo la Tarea 2 y tengo un problema para cumplir los 100 caracteres por línea del PEP8. Al definir por ejemplo el método inicializador de Plantas, como recibe tantos parámetros, supera el máximo. No sé qué podría hacer para arreglar esto? Gracias.

**Comment by CatalinaBO** [comment]
Hola, si bien puedes hacer cambios de línea utilizando una barra (\), lo más recomendable es establecer una variable descriptiva por cada parámetro y luego utilizar estas al inicializar cada método.

**Comment by 3rdPix** [comment]
Para complementar la respuesta de Catalina, puedes mirar esta _issue_ que se preguntó hace un tiempo y trata un tema similar: #59
