### ISSUE TITLE
Error con  'encoding = utf-8'

### ISSUE THREAD

**Issue by Iamchotiado** [IIC2233/syllabus#267]
Hola! Al correr mi programa no habia ningun problema, sin embargo sin razon alguna comenzó a arrojarme este error: 
"'utf-8' codec can't decode byte 0xf1 in position 595: invalid continuation byte"
Busque la solucion en internet y en uno de los foros de stackoverflow (https://stackoverflow.com/questions/19699367/unicodedecodeerror-utf-8-codec-cant-decode-byte) 
me apareció que al abrir archivos si remplazaba el  'encoding = utf-8' por  
'encoding = ISO8859-1' el problema se iba a solucionar. Al Cambiar el encoding el programa volvió a funcionar perfectamente, sin embargo en el foro no especificaba que hace exactamente ese cambio. Por lo que mi pregunta es si puedo dejarlo así, o si mi programa deberia funcionar con UTF-8.
Muchas gracias

**Comment by jmwielandt** [comment]
Hola!

Sin entrar en demasiados detalles de parte de la materia de serialización que se verá más adelante en el curso, un string en realidad es una secuencia de bytes que son interpretados como caracteres. Como un byte solo puede tomar hasta 256 valores diferentes, esto limitaría mucho la cantidad de caracteres diferentes con la que se puede escribir y lo más grave sería que no habrían emojis 😭 😱  (sí, son caracteres). Como nadie quiere vivir en un mundo tan horrible, existen cosas llamadas "encoding", que establece convenciones para interpretar conjuntos de bytes como un solo caracter y así expandir las posibilidades.

Uno de los más usados es "UTF-8", pero probablemente abriste los csv con bloc de notas o algún otro editor de texto (o quizás excel o libreoffice o algo) y al guardar le cambiaste el encoding. Por el encoding que tiene, probablemente fue bloc de notas.

Para arreglarlo puedes hacer un programa simple que al ejecutarse abra el archivo con el encoding nuevo (en este caso ISO8859-1), lo lea entero, cierre el archivo, lo abra en modo escritura con el encoding correcto y lo reescriba.

Tal como dice el enunciado, el encoding de los archivos es, será y debe continuar siendo UTF-8 durante la ejecución de tu programa.

Mira, un emoji en bloc de notas 😄 

![image](https://user-images.githubusercontent.com/37153467/64910599-87c66f00-d6ee-11e9-84f2-cd881540eaf0.png)

Como dice la imagen, saludos y ánimo con lo que queda~ 👍
