### ISSUE TITLE
Ninguna pieza del tablero calza con la pieza que me entrega el juego

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#268]
Que debería hacer si es que el juego me entrega una nueva pieza para que yo la ponga pero esta no calza por ningún lado con ninguna de las piezas que ya están en el tablero? Por ejemplo, me sucedió que mi programa puso como primera pieza aleatoria en el tablero la pieza CCCCCC y me mostró la pieza GGGGPP. Como no calza por ningún lado, el jugador no puede ponerla. Como tampoco puede volver atrás en jugadas ya que es el primer turno, el jugador realmente no tiene nada que hacer.

**Comment by fnquinteros** [comment]
Hola! 

> El juego termina cuando un jugador **no puede poner su pieza**, cuando no quedan m´as, o bien, cuando
se logra completar la snitch dorada. 

Enunciado 3.3.6

Saludos!

**Comment by bedefrunner** [comment]
Aaaah cierto, perdón! Gracias!
