### ISSUE TITLE
Entrega diagrama de clases

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#268]
Hola, para el avance se debe subir un diagrama de clases y para el push final de la tarea también, a estos archivos les pongo el mismo nombre? renombrándose así cuando haga la versión final del diagrama o les pongo nombres distintos? i.e. `diagrama_avance.pdf` y `diagrama_final.pdf`. Misma pregunta para la explicación de este. Aparte, estos se deben dejar en la carpeta T01 o en una subcarpeta de esta?

**Comment by aljara97** [comment]
Hola @dlmed, no es necesario que los subas con nombres distintos. Ya que, los diagramas correspondiente al avance serán recolectados de los repositorios cuando se cumpla la fecha límite de entrega de este, mientras que el diagrama final se recolectará cuando termine el plazo de entrega de la tarea. Puedes agregarlos a una subcarpeta si quieres, pero recuerda que deben estar dentro de la carpeta T01. 

Saludos y mucha suerte 🧙‍♂️

**Comment by rldelafuente** [comment]
Hola! 
¿Hasta cuándo se puede subir este diagrama de clases?

**Comment by aljara97** [comment]
Hola @rldelafuente, hay dos instancias para entregar un diagrama de clases:

- **Avance de la tarea:** El plazo máximo es este miércoles a las 20:00 hrs.

- **Diagrama final:** Se entrega junto con la tarea, es decir, el plazo máximo es el 18 de abril a las 20:00 hrs.

Éxito 🧙‍♂️

**Comment by sebalepe** [comment]
el avance de la tarea se sube al depositorio personal en T01 o en depositorio del syllabus en T01?

**Comment by aljara97** [comment]
Hola @sebalepe, debes subirlo a tu repositorio en la carpeta ```T01```
