### ISSUE TITLE
Duda sobre importacion entidades

### ISSUE THREAD

**Issue by dianafuentesc** [IIC2233/syllabus#268]
Hola, queria verificar si esta permitido lo que hice en mi tarea, dare un ejemplo

Tengo una lista de perritos en perritos.csv
La funcion para procesar la info esta en un archivo procesador.py
En ese mismo archivo, hay una variable que se llama perritos, en que me entrega la info en una base de datos, de la siguiente forma
perritos = funcion(perritos.csv)

en mi archivo main, puedo hacer lo siguiente?:
from procesador import perritos

o seria una variable global?

saludos!

**Comment by lily416** [comment]
Hola :)

Lamentablemente `perritos` sería una variable global :(
Lo que puedes hacer es tener una clase general que contenga toda la información del programa (i.e. `Juego`) y que sea la clase con la que inicie la ejecución del programa. 

Por lo que estaría bien hacer:
```python3
from procesador import función

class Juego
    def __init__(...):
        # ...
        self.perritos = función('perritos.csv')
        # ...

```
 Así cargas los perritos y no haces uso de variables globales :D

Ojo que para acceder a la información de los perritos debe ser mediante la interacción de clases y no que se llame globalmente a la instancia  de la clase `Juego`.


Saludos y éxito con tu tarea 👋🐶
