### ISSUE TITLE
[entrega final] ¿Podemos copiar nuestras funciones de la entrega intermedia a cualquier ubicacion?

### ISSUE THREAD

**Issue by dvillas28** [IIC2233/Syllabus#268]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado dice que podemos mover `parametros.py` a la ubicacion que mas nos acomode, podemos hacer lo mismo con las funciones de la entrega intermedia?, es decir, copiarlas y colocarlas donde necesitemos?
Saludos!

**Comment by gasparbenavente2** [comment]
Hola! Para la entrega final de la tarea puedes crear y usar las funciones que estimes convenientes, incluyendo las de entrega intermedia.

**Comment by dvillas28** [comment]
okey muchas gracias!
