### ISSUE TITLE
Auto evaluación Formativa 3 

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2233/syllabus#268]
Hola, en la pregunta 3 y 10 de la autoevaluacion formativa 3 me sale un candado en vez del diagrama.

![Examen_ 🤔 Autoevaluación Formativa 3_ POO (parte 2) - Google Chrome 28-08-2020 22_00_30](https://user-images.githubusercontent.com/69614275/91626107-36a0a100-e97a-11ea-8f80-2faa3707ccab.png)

**Comment by bimartinez** [comment]
Hola @Lord-Kelsier,

Muchas gracias por avisar, hay algo raro en como Canvas está manejando las imágenes, por lo que en las instrucciones de la AEF agregué los links hacia las dos imágenes. Si tienes dudas vuelve a preguntar nomás 😄 

Saludos!

**Comment by Lord-Kelsier** [comment]
Los links llevan a la misma imagen, y el enunciado de la pregunta 10 hace referencia a una imagen diferente.

**Comment by bimartinez** [comment]
Ohh disculpa, no se que pasó ahí. Lo estoy corrigiendo ahora, en 5 minutos debería estar listo. Nuevamente muchas gracias!

Saludos!
