### ISSUE TITLE
Cheat Codes

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#268]
Hola una duda, los cheat codes tienen que funcionar cuando las teclas se apretan de manera simultanea o puede ser secuencial? es decir, tengo que tener por ejemplo apretadas las teclas E,N y D al mismo tiempo o puede ser apretar primero la tecla E luego la N y finalmente la D?

**Comment by jmwielandt** [comment]
Hola!

Como se menciona en el enunciado, las teclas se deben ingresar secuencialmente.

![image](https://user-images.githubusercontent.com/37153467/57898349-a8f17e80-7826-11e9-8d34-88fb66873bfb.png)

Saludos y ánimo con la tarea~

**Comment by tomascortes** [comment]
Hola, y si escribo por ejemplo 'E' 'N', luego muevo al personaje y presiono 'D', asumo que eso ya no es secuencia verdad?

**Comment by jmwielandt** [comment]
@tomascortes 
Queda a tu criterio, pero en general, no sería secuencial (la secuencia se interrumpe). Si haces otra cosa especifícalo en tu readme.
