### ISSUE TITLE
Corrección Tarea 1 

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2233/Syllabus#268]
Hola, 
Subí la tarea 1 al tiempo correspondiente y no obtuve retroalimentación - ni nada- con respecto a esta. Mantuve cierta comunicación con la ayudante Florencia Barrios con respecto a mi caso, y me dijo que si no había subido la tarea de forma pertinente entonces no tenía derecho a recorrección. Revisé los commits realizados, y fueron hechos al tiempo solicitado. El único cambio fue el del nombre de la carpeta que poseía el documento, de "T1" a "T01", quizás eso pudo haber influenciado en algo. 
Espero poder saber qué pasó :(. 
Saludos! 

Atte Nicolás Balbontín

**Comment by jtagle2** [comment]
La recolección de tareas (y actividades) se hace de manera automática, y se espera que tengas una carpeta llamada T0X (con X el número de la tarea) o ACXX. Si no cumples eso, al momento de la recolección no se encontrará tu carpeta, por lo que no le llega tu entrega al ayudante corrector, por lo que no recibes un feedback.
Eso es lo que pasó :/
Saludos

**Comment by fvr1** [comment]
Nicolás, 
Existe un form para las recorrecciones! Las issues **NO** son el medio para hacer solicitudes de este estilo.
Te van a corregir la tarea, pero **a partir de la T03 y AC06 no se corregirán los programas en carpetas con nombres equivocados.**

**Comment by nfbalbontin** [comment]
gracias  :)
