### ISSUE TITLE
Aumento del Potencilantro y sus hijos es acumulativo?

### ISSUE THREAD

**Issue by gracie-14** [IIC2233/Syllabus#268]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

¡Hola! Para la Tarea 2, si hay un Solaretillo que está al lado de más de un Potencilantro (o una de sus subclases que también tiene potención), ¿se acumula el aumento, o solo se aumenta una vez?

Por ejemplo, si hubiera un jardín así:

["X" "P" "P"]
["X" "S" "X"]
["X" "X" "X"]

¿la producción de soles sería
round(constante_soles x potencial x (temperatura/25) x (altura/30) x **(1 + aumento/100)**) <-- aumenta 1 vez
o
round(constante_soles x potencial x (temperatura/25) x (altura/30) x **(1 + aumento/100) x (1 + aumento/100)**) <-- aumenta 2 veces?

**Comment by CrisDonosoMaass** [comment]
Hola! Dado que no se específico en el enunciado puedes implementar cualquiera de las dos pero recuerda mencionar cuál en tu README.

**Comment by gracie-14** [comment]
Ok gracias!
