### ISSUE TITLE
URGENTE - No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión

### ISSUE THREAD

**Issue by anais-mv** [IIC2233/Syllabus#268]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! estaba intentando hacer el ejercicio propuesto 2.2 y me tira este error
**No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión**

Lo busqué en google y por lo que encontré tiene que ver con los puertos, yo corrí el código con el mismo puerto que nos dan en el ejercicio, también intenté cambiar el puerto pero me sigue tirando el mismo error. Pensé igual que quizás podía ser algo con como intenté hacer el ejercicio así que intenté hacer el que sigue, el ejercicio propuesto 3. Primero quise correr el código que nos daban ya listo, el # Código cliente de EnZurg. Pero me lanza el mismo error, y como este código ya está implementado supongo que tiene que ser un problema con mi pc que necesita darle acceso a algo y me gustaría poder solucionarlo lo más pronto posible por si me tira el mismo error mañana durante la actividad:(.

Aquí está el pantallazo del error cuando intentó correr el código cliente de EnZurg.
![image](https://user-images.githubusercontent.com/89219471/141199030-9dc97909-ea70-405a-9315-c3c7e5b22163.png)

**Comment by Christian-Klempau** [comment]
Contexto, estás abriendo primero el servidor y luego el cliente?
El servidor está aceptando conexiones?
Estás en la misma máquina que el server?
Siempre puedes probar reiniciar el pc también

**Comment by Christian-Klempau** [comment]
También podrías probar otro puerto. O tal vez tienes un VPN instalado, o algún modificador de red. Por ejemplo Hamachi, u otro servicio de red. Podrías tratar deshabilitandolos.

**Comment by anais-mv** [comment]
Hola! sí abro primero el servidor en el ejercicio 2.2, igual intenté hacerlo al revés, el error me aparece en el servidor. Cuando echo a correr el cliente me dice que fue no posible conectarse al pc. Estoy en la misma máquina que el servidor pero lo estaba corriendo en terminales distintas.

Probé otros puertos igual pero me seguía tirando error. Cómo se deshabilitan los servicios de red?:(

**Comment by Christian-Klempau** [comment]
Podrías subir tu código a alguna carpeta del repositorio para que podamos verlo?

**Comment by anais-mv** [comment]
Lo subo a mi repositorio personal nms?

**Comment by Christian-Klempau** [comment]
> Lo subo a mi repositorio personal nms?
Sip, a alguna carpeta distinta.
Respecto a los servicios de red, te recomiendo buscar si tienes algún programa ejecutandose que sea VPN (generalmente en el nombre dice X VPN).

**Comment by anais-mv** [comment]
Listo, los acabo de subir a una carpeta que se llama ejercicios propuestos.

**Comment by tocococa** [comment]
Hola @anais-mv, estuve revisando el código que subiste, y el error está en que estabas llamando `socket.connect()` a un socket TCP pero se trata de conectar a un puerto que no está abierto si lo primero que corres es el servidor, y se cae por eso. Además al socket UDP le falta hacer `bind()`, ya que UDP es conectionless. Luego hay un par de typos en otras cosas que no llegué a revisar, pero no es un problema con tu computador ni tu configuración de red.

**Comment by anais-mv** [comment]
Ok, muchas gracias! pero el código que ya estaba implementado también me tiraba ese mismo error (el del ejercicio 3), o es porque no funcionará hasta implementar el resto? 

De nuevo muchas gracias y disculpen por las molestias.

**Comment by tocococa** [comment]
Emmmm, no estoy 100% seguro de eso, pero puedes probar corriendo ese servidor y luego el cliente? Si te funciona podemos descartar totalmente que sea un problema de tu computador.
[test_echo.zip](https://github.com/IIC2233/Syllabus/files/7522312/test_echo.zip)
o

**Comment by anais-mv** [comment]
Ok, lo intentaré después de la actividad. Muchas gracias! :D
