### ISSUE TITLE
Duda mouseClickevent

### ISSUE THREAD

**Issue by Sebastian-Assereto** [IIC2233/Syllabus#268]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo una duda sobre métodos del clickevent, ya que he estado buscando en internet y no he logrado encontrar algo que solucione mi problema.
Resulta que necesito hacer uso de este tipo de evento, pero solo quiero que se "active" a partir de haber realizado cierta acción (apretar un botón) el problema es que cuando lo defino en mi ventana dentro del visual studio code, este tipo de evento siempre se encuentra activo, por lo cual no se si hay forma de desactivarlo mientras no toque el botón o como puedo activarlo únicamente cuando yo haga cierta acción 
Cuando hablo de haber presionado un botón, no hago referencia a un botón del mouse, si no que me interesa al momento de presionar un botón de pyqt5 cómo tal poder usar la información del click , ya que si no apretó el botón de pyqt5 q deseo, y apretó de forma aleatória igualmente realiza la acción, es por esto que tengo la intención de solo activar el clickevent una vez yo haya apretado un botón creado por mi 
Espero puedan ayudarme

**Comment by Lord-Kelsier** [comment]
Hola @Sebastian-Assereto, no conozco la existencia de algo similar pero te propongo cambiar la vision del problema. Tu quieres que al apretar un boton la informacion del click pueda ser usada, para esto puedes crear una variable que sea `boton_x_presionado = False` cuando se presione el boton hacerla `True` y que en un click se mire si este boton fue clickeado. 
Espero te sirva, saludos

**Comment by Sebastian-Assereto** [comment]
intente hacer algo de ese estilo, tipo al mousepress event darle otro parametro que por defecto es False, el problema es que cuando llamo a la funcion, me dice que "event" tambien requiere definirse con algo y no sabria que darle de argumento

**Comment by Lord-Kelsier** [comment]
recuerda que debes reescribir la funcion, no usarla. Esta se llama sola cuando se hace click, tu no la llamas

**Comment by Sebastian-Assereto** [comment]
realmente, no logro comprender como podria "reescribir" la funcion, osea como tal yo ya defini que es lo que hace el "mousePressEvent" el problema es que siempre esta activo, pero yo no quiero hacer eso, yo quiero que se active solo cuando toco un boton, el tema es que intente poner un if con una variable , que por defecto es falsa, y la idea seria que al clickear el botón, esta variable se convierta en verdadera, pero no se como poder hacer eso, no se si quizá sea más conveniente que haga un push y te diga cual es el archivo para ver si asi entiendes mejor mi problema

**Comment by Lord-Kelsier** [comment]
Si revisas los contenidos de la semana 6, eventos y señales veras algo como lo siguiente:
![image](https://user-images.githubusercontent.com/69614275/195251137-391ea1ae-42e1-44fb-b9b7-d0b3139bca82.png)
esto es override de una funcion, aqui puedes implementar lo que quieras, pero no puedes llamarla ya que debes tener evento que maneje Pyqt por dentro

**Comment by Sebastian-Assereto** [comment]
esque literalmente tengo eso escrito, pero obviamente con el codigo que yo necesito, el tema es que como ya mencione, solo quiero que este metodo se active cuando antes yo presiono un boton (para que me entiendas, si puedes ve mi archivo llamado "ventana_juego_abuela.py" en la linea 46, y veras que yo hice eso mismo

**Comment by Lord-Kelsier** [comment]
pero no se puede directamente, como te digo puedes hacer:

```python
def mousePressEvent(self, event):
  if self.funcion_x_habilitada == True:
    ejecuta_x()

```

**Comment by Sebastian-Assereto** [comment]
oooo yaa DFHDS sii ahi cache, Muchisimas graciasss !! de verdad jaja era muy simple se me fue totalmente

**Comment by Lord-Kelsier** [comment]
oki, no hay problema
