### ISSUE TITLE
eficiencia busqueda binaria? Unicidad de nombres?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#268]
### Pregunta 1
Digamos que en la tarea 2, tengo un árbol binario cuyos nodos guardan un `int` único y un `string`, y `OtrasCosas`.

Si quisiera buscar esas `OtrasCosas` por el `string`(que no sé si es único) como sería mas eficiente?
Tengo tres opciones:

1. Crear otro árbol binario que solamente relacione el `int` único con el `string`, pero en este los datos estarían ordenados binariamente a partir del string ( dado que  `"abc" < "bbc"` en python). Lo que haría entonces sería buscar primero el `int` único en éste árbol, para luego buscar por el número único en el árbol orignal.

2. Ordenar el árbol binario inicial, a partir del `string` (y suponer que es único) y no del número único y así buscar directamente en ese árbol  a partir del `string`.

3. Realizar una _búsqueda BFS_ en el árbol binario, en vez de una búsqueda binaria.

### Pregunta 2

Los nómbres de los jugadores en el juego, son únicos?

**Comment by jtagle2** [comment]
### Pregunta 1

La verdad, la estrategia más eficiente dependerá de lo que tu quieres hacer más eficiente. ¿Quieres hacer tu programa más eficiente en términos de memoria o en términos de tiempo? Te dejo un pequeño análisis en cada opción. Asumiré que estuviste investigando respecto a al eficiencia de las distintas estructuras de datos y algoritmos, y en algún momento te topaste con el concepto de la [big O notation](https://rob-bell.net/2009/06/a-beginners-guide-to-big-o-notation/). Si no es así, imagina que podemos definir el uso de memoria y el tiempo de ejecución de tus algoritmos, poniendonos en el peor caso posible de ejecución y obtener una expresión en función del numero de nodos que tienes.

1.- Esta opción es un poco menos eficiente en memoria, pues requiere utilizar dos árboles binarios para almacenar los datos, por lo que el uso de memoria sería O(2n) (pues almacenas 2 nodos por cada dato que llega), pero la búsqueda sería encontrar primero el id en un árbol, y luego encontrar lo que estás buscando en el otro árbol (*¿Por qué en el primer árbol estarías guardando el id, y no la referencia al objeto? Pregunta retórica para la reflexión*), por lo que el tiempo de ejecución sería O(2 log(n)), pues el tiempo de búsqueda en un árbol binario es O(log(n)).

2.- En este caso, primero tendrías que ordenar tu árbol binario según el  `string`, para luego buscar la referencia a tu objeto dentro del árbol. Asumiendo que el tiempo de ordenación es O(n log(n)), tu tiempo de ejecución sería de O(n logn + log(n)), pues primero tienes que ordenar, y luego buscar en el árbol.  Por otro lado, el uso de memoria sería de O(n).

3.- En esta, el tiempo de búsqueda sería O(n), pues en el peor caso el elemento buscado no estaba, y tuviste que recorrer todos los nodos del árbol y el uso de memoria es O(n).

En el análisis hay unos cuántos supuestos para no complicar la respuesta, y cosas que se pueden simplificar. Cuando hagas matemáticas discretas y/o estructuras de datos te va a tocar analizar en más profundidad este tipo de dilemas. Por ahora, queremos que logres llegar a una solución para el problema dado (y que ojalá lo pases bien programándola), y que hagas programas funcionales que puedan ser ejecutados y probados en un tiempo razonable (#264). Ya habrá tiempo para batallar con llegar a la máxima eficiencia posible :smile:

### Pregunta 2

Los tareos me confirman por interno que los nombres sí son únicos.

**Comment by naquiroz** [comment]
@jtagle2:
Gracias por la detallada respuesta!
Ahora, aclarando unas cosas.

2. - Pero, que pasa si yo, al agregar los nodos, los voy ordenando al tiro según el `string`?

3. O sea que la busqueda bfs sobre un arbol binario es más rápida que la búsqueda bfs?

**Comment by santilaguna** [comment]
Siguiendo con el hilo de la pregunta ¿ es más rapido aplicar un hash a un string y luego comparar por su hash(int) o comparar directamente por string?

**Comment by Panckx** [comment]
Hola! Viendo el archivo actualizado, puedo confirmar que los nombres NO son únicos.
