### ISSUE TITLE
Consulta sobre busqueda de afinidades no relacionadas directamente dentro de los 200 jugadores

### ISSUE THREAD

**Issue by AlexanderBarrera** [IIC2233/Syllabus#269]
Hola.
Mi duda consiste en que al momento de tener que calcular las afinidades indirectas entre dos jugadores que estan dentro de los 200 seleccionados, ¿se consideran las posibles relaciones que cada jugador tiene con los que estan fuera de esta seleccion?
Agradezco de antemano la respuesta.
Muchas gracias.
: )

**Comment by yoavnavon** [comment]
Si, se consideran todas las relaciones con la base de datos completa de jugadores.
