### ISSUE TITLE
Caracteres utilizados en los archivos .csv

### ISSUE THREAD

**Issue by cegalleta** [IIC2233/syllabus#269]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!

Para cargar los datos hice un archivo con funciones para entregar datos en cierto formato a las clases, sin embargo, varios built-ins de la librería collections se me caen por las tildes y las 'ñ' de la primera fila de los archivos .csv, incluso poniendo encoding='utf-8'.

El error que lanza con 'barcos.csv' es:

ValueError: Type names and field names must be valid identifiers: 'costo de mantención'

Pero el error pasa con todos los otros csv también, excepto 'canales.csv'.

Por ello, les pregunto si es que existe una manera de capturar el error y transformar todo a "ascii", que supongo que no causaría problemas, o si hay alguna otra manera de sortear esto. Leí que se pueden corregir los errores con archivos por bytes, pero no sé hacer eso.

Encontré a una persona que tuvo el mismo error pero no entiendo la solución que le dieron:

https://stackoverflow.com/questions/30503539/namedtuple-with-unicode-string-as-name

**Comment by cegalleta** [comment]
Actualización:

Intenté el siguiente código:

```
with open(path, 'r', encoding="utf-8") as data:
        data = data.readlines()
        parametros = data[0].strip().split(',')
        parametros_bytes = [parametro.encode(errors='ignore') 
                            for parametro in parametros]
        parametros = [parametro.decode(encoding='ascii', errors='ignore') for parametro in parametros_bytes]
```

pero sigue lanzando error :(

**Comment by Emiliax16** [comment]
¡Hola! por lo que entendí, el error viene dado por los namedtuple que creas, no por importar el archivo csv como tal. En el mismo link que adjuntaste, en la parte más baja hay una posible solución. El título es **Fix of the problem** y muestra una función llamada `def namedtuple_(typename, field_names, verbose=False, rename=False):def namedtuple_(typename, field_names, verbose=False, rename=False):` esta función básicamente permite agregar caracteres especiales. Prueba con eso. Otra solución es que utilices otro método y no namedtuple, como listas o diccionarios 😭 

Quedo atenta! cuéntame si te funciona o si necesitas algún otro apoyo!

**Comment by cegalleta** [comment]
Creo que no utilizaré namedtuples finalmente, me sorprende que tengan un bug tan raro en collections. Muchas gracias!

**Comment by Emiliax16** [comment]
También me sorprendió :c  suerte en tu tarea!
