### ISSUE TITLE
Duda sobre dimensiones del juego

### ISSUE THREAD

**Issue by drcid98** [IIC2233/Syllabus#269]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, se que en el issue #217 queda claro que podemos ocupar ventanas de las dimensiones que queramos, el problema es que mi pantalla en la cual trabajé durante todo este tiempo es un tanto grande y me di cuenta que (ahora que traté de avanzar desde mi notebook) la ventana queda muy grande para la pantalla de un notebook común y corriente. Es esto un problema? puedo asegurarme que la persona que vaya a revisar mi tarea tenga una pantalla suficientemente grande como para que se vea toda la ventana? Se que una opción es achicar todo, pero eso implica igual harta pega y quiero asegurarme antes de que no hay otra solución, para que esa sea mi última solución.

Pd: las dimensiones que ocupé para la ventana de juego (la más grande que contiene el juego) son de 1000x815

**Comment by mmunoz12** [comment]
Hola @drcid98!

No te preocupes si usaste dimensiones muy grandes, ya que a principio de semestre se preguntó por las resoluciones de sus pantallas por lo que como ayudantes ya sabemos de antemano en que dimensiones más o menos trabajarían. Si estas usando una resolución diferente a la que especificaste en ese form, podrías mencionar en tu Readme para que el ayudante sepa al momento de revisar.

 Mucho éxito con tu entrega! 😉

**Comment by drcid98** [comment]
Ya me di la lata de achicarlo todo u.u como nadie se asignaba el issue me entró la ansiedad. Gracias iguaaal por la respuestaaa
