### ISSUE TITLE
Dos enemigos en la misma casilla

### ISSUE THREAD

**Issue by jirarrazabal** [IIC2233/syllabus#269]
En el enunciado se indica que, si hay dos enemigos en la misma casilla, se deben mostrar los dos. No entiendo como podría mostrar a ambos enemigos al mismo tiempo.
¿Se puede mostrar solo una imagen, suponiendo que estan los dos superpuestas?
Muchas gracias

**Comment by Hernan4444** [comment]
Hola,
Deben estar ambas imágenes (es más fácil que mostrar solo una) y recuerda que pueden haber 2, pero uno mirando en una dirección (norte por ejemplo) y otro mirando en otra dirección (este por ejemplo) y se apreciará en el mapa que hay dos. Aunque se vea feo, no hay problema con eso. Si quieres hacer que se muestre solo una imagen, entonces puedes agregar un `bool` a `parametros.py` que:
* Si es `True` muestra solo una imagen como dices
* Si es `False` muestra todas las imágenes como pedimos.

De este modo, el ayudante puede verificar que hay 2 enemigos en una casilla y si luego quieres mostrarle el juego a alguien, habilitas ese bool para que se vea más bonito. Aunque te recomiendo dejar esta idea para después 😅 

Saludos :v:

**Comment by jirarrazabal** [comment]
Muchas Gracias!
