### ISSUE TITLE
Recorrección AC04

### ISSUE THREAD

**Issue by malopez16** [IIC2233/Syllabus#269]
Hola!
Hay hasta mañana para mandar a recorregir la AC04, pero aún no tengo la asignacion de puntajes de mi entrega en mi repo :( como podría verla?
Gracias :)

**Comment by LuisFros** [comment]
Yo tenia la misma duda, no me ha llegado a mi tampoco.

**Comment by bamavrakis** [comment]
Hola! Los feedbacks se subirán hoy! Se va a ampliar el plazo para recorregir hasta el Jueves a las 23:59

**Comment by sofiapacheco1** [comment]
Hola! Aún no he recibido el feedback de la AC04 ni tampoco el de mi T01, que puedo hacer? He mandado como 2 mails, mandé un form de recorrección pero no recibo ninguna respuesta y como las recorrecciones son hasta mañana no se que puedo hacer.
