### ISSUE TITLE
Duda contenidos midterm

### ISSUE THREAD

**Issue by bea-or** [IIC2233/Syllabus#269]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola, quería saber si los contenidos marcados como _bonus_ serán evaluados en el midterm. A esto me refiero, por ejemplo, a diagramas de clases o métodos estáticos, entre otros, que salen en los contenidos de algunas semanas.

Gracias!

**Comment by Dvckhv** [comment]
Hola! Tal como mencionas, son contenidos bonus, por lo que no son evaluados formalmente dentro de ninguna evaluación :)
