### ISSUE TITLE
Diccionarios almacenados en funciones en vez de en parametros

### ISSUE THREAD

**Issue by jac-34** [IIC2233/syllabus#269]
En algunas funciones y metodos de clases uso diccionarios para facilitar el flujo del codigo, pero estos diccionarios quedan escritos al inicio de la funcion. Estos diccionarios cuentan como variable hardcodeada? osea, es mala practica hacer eso y deberia dejar todos los diccionarios que cree en parametros?

**Comment by KnowYourselves** [comment]
La respuesta a esta pregunta es **depende**.  ¿De qué depende?, De la **importancia de la variable en en tu programa**. 

Me explico. Si tuvieras un diccionario que contiene valores máximos y mínimos de los atributos de una clase, **debería ser un parametro**. En cambio, si haces un diccionario que contenga cosas auxiliares, por ejemplo, funciones útiles o otras cosas **no tiene por que ir en parámetros**.

La diferencia es que el primero **controla como tu programa funciona** mientras que el segundo **ayuda a que tu programa sea legible**.

Como nota final, eso es lo que define si algo debe ir en parametros o no, que sea un diccionario no importa, podría tratarse de cualquier variable o estructura.

Espero que te haya quedado claro!
