### ISSUE TITLE
Uso parametros

### ISSUE THREAD

**Issue by drosselot** [IIC2233/syllabus#269]
Hola, como se si es necesario poner un parámetro en algún valor? ¿Hay algún criterio? Porque, por ejemplo, cuando elimino un alimento del inventario no creo que sea necesario poner un parámetro o si?

**Comment by mpsubiabre** [comment]
Hola @drosselot!

Esta issue #258 te podrá ser de ayuda. Pero de manera simple, el criterio para saber si definir o no algún valor como parámetro es que, sera parámetro todo valor que permanecerá constantes al momento de ejecutar tu código, o visto de otra manera, son datos que se establecen antes de correr el código, y no cambian durante toda la ejecución.

Espero haber contestado tu duda, de lo contrario comenta esta issue :)

**Comment by drosselot** [comment]
Si es que lo voy a usar una sola vez, es necesario guardarlo como parametro?

**Comment by drosselot** [comment]
Por ejemplo, cuando hay que asignarle atributos a los magos, solo voy a poner una vez el máximo y el mínimo de cada atributo, y el programa va a elegir uno al azar. No voy a usar ninguna de esas constantes nunca más en el programa, es necesario que los ponga como parámetros? No le encuentro la utilidad de hacerlo

**Comment by mpsubiabre** [comment]
Aunque sea usado una vez es necesario guradarlo como parametro, porque es independiente del numero de veces que lo uses. La idea de usar parametros es que tu codigo sea facil de modificar y sea escalable. Talvez en esta tarea no logres dimensionar tanto su importancia, pero son buenas practicas que es necesario adquirir. Por ejemplo, aunque no uses esas constantes nunca mas, puede que en el futuro quieras cambiarlas y sera mucho mas práctico hacerlo a travez de parámetros, que buscar en el código donde esta dicho numero, tambien puede que hayas escrito el codigo hace mucho tiempo y no recuerdes que hacia dicho numero o donde estaba. En esos casos los parametros son de mucha ayuda.

Espero que te haya quedado claro :)

**Comment by drosselot** [comment]
Si me quedo más claro, muchas gracias!!
