### ISSUE TITLE
Duda archivo "parametros.py"

### ISSUE THREAD

**Issue by SebaPassi** [IIC2233/Syllabus#269]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

En el apartado 6.3 del enunciado se especifica lo siguiente:

"Además, es fundamental incluir cualquier valor constante necesario en tu tarea, **así como cualquier tipo de path utilizado**."

¿A qué se refiere con lo del path?

Muchas gracias!

**Comment by wintermelyn** [comment]
Hola @SebaPassi!

Para la tarea deben leer tanto el archivo de difcultad entregado como argumento como el archivo de unidades.txt. La idea es que para la ruta de estos archivos las definan dentro de parametros.py, (usando patlib o os, como prefieran) por darte un ejemplo:

```python
RUTA_DE_EJEMPLO = os.path.join("data", "ejemplo.txt")
```

Y luego en el codigo de tu tarea puedes directamente usar la constante `RUTA_DE_EJEMPLO`.

**Comment by wintermelyn** [comment]
Hola @francorreaandrades!

Es obligatorio que los paths se ubiquen en parametros.py pues bajará el puntaje si no están. 😔

Te recomiendo revisar la issue #282.
