### ISSUE TITLE
temperatura en plantas básicas

### ISSUE THREAD

**Issue by Framnn** [IIC2233/Syllabus#269]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
holaa, consulta; ¿temperatura es heredado de jardín o es TEMP_INICIAL que ya habíamos definido anteriormente? 
<img width="1021" alt="Captura de pantalla 2024-09-06 a la(s) 5 26 50 p  m" src="https://github.com/user-attachments/assets/c6d0d097-238e-4ecb-8079-657b4a53c9f7">

**Comment by CatalinaBO** [comment]
Hola! La temperatura con la que se deben realizar los cálculos es la temperatura que hay en el momento. Recuerda que el jardín parte con una TEMP_INICIAL, pero al comienzo de cada día se debe actualizar la temperatura. Además, cuando ocurren heladas este valor igual cambia! 
Ojalá se haya respondido tu pregunta, quedo atenta.
