### ISSUE TITLE
import time

### ISSUE THREAD

**Issue by kraksiplus** [IIC2233/syllabus#269]
En el enunciado te dejan claro que no debs importar librerias a menos que te lo pidan, sucede que en mi caso he puesto unos añadidio bonitos al programa, y antes de reiniciar cada ciclo quiero que este espere unos segundos con time.sleep(), existe algun problema con eso?

**Comment by Lord-Kelsier** [comment]
En una issue dijeron que no lo hagamos porque los ayudantes para corregirlo deben ejecutar varias veces el código y eso ralentiza la corrección.

**Comment by bvasquezm** [comment]
Así es!! Ralentiza mucho el tiempo de corrección aunque quede más ordenado :( Gracias @Lord-Kelsier por tu respuesta!

**Comment by kraksiplus** [comment]
Perfecto, ante este escenario me las arregle para que quede bonito sin necesidad de usar time.sleep(), gracias por el aviso :3

**Comment by DCCollao** [comment]
@kraksiplus Este tipo de dudas va en la issue dedicada a preguntar sobre librerías, y ha sido resuelta anteriormente en esa misma issue. Te recomiendo revisarla antes de preguntar por una librería #87
