### ISSUE TITLE
Tipos de plantas en el plano

### ISSUE THREAD

**Issue by xperseosses** [IIC2233/Syllabus#27]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

**¿Cada plano debe tener solo una plantación de cada tipo? ¿No pueden haber dos plantaciones de 1 en diferentes coordenadas del plano?**

**Comment by SSParzival** [comment]
Hola buenas, en efecto, cada plano solo puede tener una plantación de cada tipo, y no pueden haber dos plantaciones del mismo tipo en coordenadas no conectadas.

El enunciado menciona explícitamente lo siguiente:
"Una restricción importante es que no se permite repetición del código de cultivo en el mismo predio."
