### ISSUE TITLE
Permission to IIC2233/syllabus.git denied to alvaritions.

### ISSUE THREAD

**Issue by alvaritions** [IIC2233/syllabus#27]
Había olvidado hacer el commit de la AC00, intenté hacer el git push pero la consola me retornó:

$ git push
remote: Permission to IIC2233/syllabus.git denied to alvaritions.
fatal: unable to access 'https://github.com/IIC2233/syllabus/': The requested URL returned error: 403

ni idea de qué hice/no hice para que me salga eso.

**Comment by Dnpoblete** [comment]
Hola @alvaritions , lo más probable es que estés tratando de subir la AC00 al repositorio del curso en lugar de tu repositorio personal. Revisa si lo estás subiendo a tu repo y en el caso contrario intenta descargar tu repo y subirlo en esa carpeta.

Avisame como te va y/o si tienes más dudas me dices para poder ayudarte :smile:

**Comment by alvaritions** [comment]
Ya lo subí, y sí era eso jjasjajsj gracias. Pero ahora el git status en mi AC00 me dice esto:
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    ../../Tareas/T01/README.md

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ../../Tareas/T00/T01/

no changes added to commit (use "git add" and/or "git commit -a")

supongo que es por el enredo anterior. Es muy grave quede así? O como se puede solucionar?

**Comment by Dnpoblete** [comment]
Te recomiendo hacer git pull para actualizar tu repo.

Avisame si con eso se soluciona 👍

**Comment by alvaritions** [comment]
El git pull no funcionó.
Se puede quedar así si no volveré a usar esa carpeta?

**Comment by entamburini** [comment]
Puedes borrar las carpetas que están de más, después has git status y revisa si se fueron :wink:

**Comment by alvaritions** [comment]
@entamburini no veo que haya carpetas de más, pero sí veo que en el syllabus en GitHub me aparece 

Revert "Add base Actividades folder"

No sé si es por los pull que mandé por error

**Comment by entamburini** [comment]
Aaaaah estás en el syllabus, creí que era tu repositorio. Para arreglar eso, te recomiendo seguir estos pasos:
- Guarda en otro lado (fuera del repositorio) los cambios que hayas hecho en el syllabus.
- En el repositorio syllabus corre el comando `git stash`
- Ahora puedes hacer `git pull` 
- Si vuelves a modificar el repositorio syllabus, repite estos pasos para que no tengas problemas. 

Recuerda que para subir tus cosas, debes estar en tu repositorio personal, en tu caso "alvaritions-iic2233-2020-1", si tratas de hacer `git push` en el syllabus no podrás porque es el repo del curso y sólo nosotros podemos echarnoslo >:) xd
