### ISSUE TITLE
Tasa de propagación continua o discreta?

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#27]
Hola!

En el punto 5.1 de la tarea se comienza a hablar de la tasa de propagación de los incendios. En un punto dice lo siguiente.

> La tasa de propagación base de todos los incendios son 500 metros de radio por hora.

Este aumento del radio es discreto o continuo? Es decir, en el instante que pasa una hora, aumentamos el radio en 500 metros? O aumentamos el radio constantemente a una rapidez de 500 metros por hora?

Gracias!

**Comment by stephichau** [comment]
Hola @akaminetzkyp ! 

El radio aumenta constantemente a una rapidez de 500 m/h.

Saludos! :)

**Comment by akaminetzkyp** [comment]
Súper! Gracias @stephichau! :D
