### ISSUE TITLE
Duda de como subir una carperta a GitHub

### ISSUE THREAD

**Issue by rgmorales1** [IIC2233/syllabus#27]
Una consulta, ¿como puedo subir una carpeta vacía?, lo necesito para el funcionamiento de mi programa, pero no le puedo hacer add en git para luego subirla, ¿qué debo hacer?

**Comment by DCCollao** [comment]
Hola!

En este [link](https://stackoverflow.com/questions/115983/how-can-i-add-an-empty-directory-to-a-git-repository) se habla de varias formas de lograr lo que buscas. Recomiendo utilizar el método que utiliza `.keep`.

Éxito!

**Comment by rgmorales1** [comment]
Muchas gracias !!
