### ISSUE TITLE
Ejecutar código con VS Code en MacOS

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2233/syllabus#27]
Hola! tengo ya todo bien instalado y todo, pero me da curiosidad algo que me pasa:

Al correr algo así como esto en VIsual studio me dice que hay problemas en la linea 5, puesto que "lineas" no está definido.

path_absoluto = "/Users/pablo/Desktop/hola.csv"
with open(path_absoluto, 'rt') as archivo:
    lineas = archivo.readlines()

lineas

Sin embargo, luego corro esto mismo en la consola de Python 3.7.4 y me funciona perfecto! 
A qué podría deberse? quizás me falta algo por instalar en Visual Studio?

**Comment by igbasly** [comment]
Hola @pabloalvarez67 :v:

Entiendo lo que intentas hacer con el código, pero no estoy seguro de como se está generando el error, ¿podrías por favor darme más detalles del contexto en que están ocurriendo y en lo posible una captura de pantalla de VSCode para entender donde podría estar fallando?

Además, ¿A qué te refieres cuando lo "corres en la consola de python", a escribir linea a linea o ejecutar un archivo?

Espero tus respuesta para dar una solución más acertada, aún no puedo decirte si es problema de VSCode o no 👍 .

**Comment by pabloalvarez67** [comment]
Linea a linea iba escribiendo en la consola de python, no ejecutando el archivo porque tengo más cosas debajo del ejercicio propuesto jajaja.
![Captura de Pantalla 2020-08-15 a la(s) 8 25 01 p  m](https://user-images.githubusercontent.com/62023649/90323893-a011c000-df35-11ea-9022-42450f5dc5f5.png)
Ese es el error que me tira visual studio con respecto a esa parte del código.

**Comment by igbasly** [comment]
Entiendo, al parecer podría tener que ver con como Visual Studio ejecuta el archivo, por lo mismo, te pediría esta vez una captura de pantalla de todo VSCode, para poder ver todo el espacio de trabajo.

**Comment by pabloalvarez67** [comment]
![Captura de Pantalla 2020-08-15 a la(s) 9 15 08 p  m](https://user-images.githubusercontent.com/62023649/90324397-6e502780-df3c-11ea-8328-36f026f94d90.png)

Aquí en este caso le dí a shift+enter para ejecutar el codigo en la linea 12, para ejecutar solo esa primera parte.

Eso que hice yo hasta la linea 12 me funciono también en la consola de python haciendo todo linea por linea regularmente.

**Comment by igbasly** [comment]
Yaa, perfecto, ahora entiendo lo que está pasando. 😅 

Te explico, con `shift + enter` se abre la consola interactiva de IPython, que funciona básicamente como cualquier consola donde puedes programar línea a línea. El problema que surge es que cuando tienes seleccionada una línea, esta consola solo correrá esa línea y luego dejará abierta la consola para que sigas programando "a mano".

La forma "correcta" de correr un archivo completo es mediante el botón que se encuentra en la barra superior donde están los nombres de los archivos, que tiene forma triangular ▶️ y es de color verde. Además de forma análoga, puede hacer click derecho dentro del archivo e ir a `"Run Python File in Terminal"`. Estos métodos te abrirán la terminal de VSCode y ejecutarán el archivo con Python.

Te recuerdo siempre guardar antes de ejecutar y te puedo recomendar el módulo [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) de VSCode para agregar comandos de teclados y otras configuraciones personalizadas al ejecutar código.

Coméntame cómo te va con esto y si queda alguna duda al respecto 🙌.

**Comment by pabloalvarez67** [comment]
Perfecto! muchas gracias por el módulo veré que tal se puede hacer con el.
Muchas Gracias!
