### ISSUE TITLE
TestCase tarea 1

### ISSUE THREAD

**Issue by IsidoraCarmona** [IIC2233/Syllabus#27]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, al momento de correr los testcase me aparece ModuleNotFoundError: No module named 'red ' , podrian guiarme un poco que significa eso? estoy editando sobre el archivo red.py de la carpeta de la tarea, no entiendo porque habria un error en la importacion de mi archivo en el testcase cuando no toque esa parte

**Comment by elneitans** [comment]
Yo lo estoy haciendo de esta forma: corro python red.py & python test_09_cambiar_planos.py en la terminal (ejemplo con el test_09). Pero al parecer tienes que tener red.py y test_09_cambiar_planos.py en el mismo folder (desde donde estás corriendo en la terminal), porque si quieres hacer por ejemplo: red.py & python tests_publicos/test_09_cambiar_planos.py, te sale ese error.

**Comment by MaxAl100** [comment]
Hola! Primero que todo, me explicas como estás haciendo correr los tests? Desde ahí te puedo ayudar. Por ejemplo, si entras a la carpeta donde están los tests y corres uno de los archivos.py desde ahí puede que sucedan errores, ya que el módulo red (red.py) no se ubica dentro de la carpeta, por lo que tu programa no lo puede encontrar.

Si estas testeando de otra manera, puede que el error se deba a otras razones, por lo que te pido que me expliques en detalle cómo estás testeando.

Asimismo, te recomiendo leer este issue: https://github.com/IIC2233/Syllabus/issues/24 donde explico cuales son las dos maneras con las que debieses testear. 😄

**Comment by MaxAl100** [comment]
> Yo lo estoy haciendo de esta forma: corro python red.py & python test_09_cambiar_planos.py en la terminal (ejemplo con el test_09). Pero al parecer tienes que tener red.py y test_09_cambiar_planos.py en el mismo folder (desde donde estás corriendo en la terminal), porque si quieres hacer por ejemplo: red.py & python tests_publicos/test_09_cambiar_planos.py, te sale ese error.

Hola! Esto no debieras realizarlo, ya que si mueves los archivos a la carpeta puede que a los ayudantes no les funcione bien tu código cuando corrijamos la tarea (y te saques mala nota 😱), por lo que debieses devolver los tests a la carpeta tests_publicos y asegurarte que funcione corrrectamente, siguiendo los pasos descritos en el issue https://github.com/IIC2233/Syllabus/issues/24

**Comment by elneitans** [comment]
Ya, muchas gracias.

Otra cosa, relacionada: parece que el test público 9 tiene un par de typos.  Indica que el archivo a abrir son ciudad_T.dcc y test_-1.txt cuando el folder de tests_publicos tiene ciudad_T.txt y test_1.txt. Si lo pudieran revisar, muchas gracias
