### ISSUE TITLE
Seccion Solucionar Tablero

### ISSUE THREAD

**Issue by GuilleStanke** [IIC2233/Syllabus#27]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Si en el menú de acciones se solicita Solucionar Tablero, y el archivo ingresado corresponde al de un tablero resuelto pero de manera incorrecta, ¿debo "deshacerlo" y hacerlo correctamente? (Esta pregunta la hago por separado para dos casos: 1) no se cumplen las reglas 2 y/o la regla 4./       2) se cumplen las reglas 2 y 4, pero no se cumplen las reglas 1 y/o 3)

**Comment by Hernan4444** [comment]
Hola @GuilleStanke 

El programa solo puede agregar nuevas tortugas, pero no puede modificar lo que ya existe. Por lo tanto, si cargas un tablero que ya tiene tortugas, esas se mantienen donde estan y desde dicho estado hay que intentar resolverlo o indicar que no tiene solución.

Saludos c:
