### ISSUE TITLE
Consulta contraseña y usuarios nuevos

### ISSUE THREAD

**Issue by K4rl4Munoz** [IIC2233/Syllabus#27]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Mi duda es:
1° Al crear la contraseña de un nuevo usuario, es necesario que sea alfanumérico o pueden ser solo letras o números?
2°Al agregar un nuevo usuario, debo agregarlo al archivo de "usuarios.csv" o será un registro momentáneo (al cerrar la sesión no se guarda el usuario?
3°cuando se modifique el estado del  paquete, debe actualizarse en el archivo o solo momentáneamente(al cerrar esa sesión no se guarda el cambio?

**Comment by magdalenanario** [comment]
Hola @K4rl4Munoz ! Respondiendo a tus preguntas, en primer lugar cuando se pide que la contraseña sea alfanumérica significa que puede estar formada solamente por letras, solamente por números, o por letras y números en conjunto. En cuanto a la segunda pregunta, cuando se crea un nuevo usuario este debe ser agregado a 'usuarios.csv', no es un registro momentáneo. Lo mismo pasa con la tercera pregunta, ya que al actualizar el estado del paquete esto se debe modificar en 'encomiendas.csv'. Saludos!
