### ISSUE TITLE
Respecto a los módulos entregados para formar el tablero

### ISSUE THREAD

**Issue by k-i-r-b-y** [IIC2233/Syllabus#27]
no entiendo exactamente como funcionan los módulos que nos entregaron, por lo que pregunto si se puede crear el módulo uno por su cuenta, y si es así, es necesario que tenga exactamente el mismo formato ? (me refiero a este o el otro con bordes)
                                                                                                                                   A B C
                                                                                                                              1   *  *  *
                                                                                                                              2   *  *  *
                                                                                                                              3   *  *  *

**Comment by vicentethomas** [comment]
Hola!
Según el enunciado, debes importar correctamente los módulos entregados. Por lo tanto, la importación de archivos es algo que se evalúa en esta tarea, así que **debes** utilizar el archivo `tablero.py` para el funcionamiento de tu programa. 
Te recomiendo revisar en los contenidos los apuntes de [modularización](https://github.com/IIC2233/contenidos/blob/master/semana-00/2-modularización.ipynb), en especial la parte de importación parcial donde se explica cómo importar funciones de otro archivo.

Feliz si me dices que parte del módulo no te queda muy claro para poder ayudarte! Pero en resumen, lo que hay que hacer es importar el método `print_tablero` en tu archivo principal de la tarea para cuando tengas que imprimir el tablero en consola. 
Recuerda también que a esta función `print_tablero` es necesario entregarle la lista `tablero` como atributo para que imprima la tabla (Las especificaciones de esta lista están en el enunciado).  :+1:

**Comment by Isiirribarra** [comment]
hola, cuando importo tablero me sale este error: SyntaxError: Non-ASCII character '\xe2' in file ...

**Comment by Isiirribarra** [comment]
> ¡Hola! ¿Podrías subir tus últimos cambios a tu repositorio personal para revisar cuál puede ser el error?



> ¡Hola! ¿Podrías subir tus últimos cambios a tu repositorio personal para revisar cuál puede ser el error?

esta subido

**Comment by vicentethomas** [comment]
Buenísimo, algunas cosas que comentarte. 
Primero, y solo para asegurarnos, estás usando python 3.10 verdad? Porque buscando en internet el error aparece principalmente en python 2. (Pregunto por que a mí no me aparece el error :cry:)
En VSCode abajo a la derecha debería salir tu versión.

Lo segundo y un poco extra pero para que no tengas problemas más adelante, intenta especificar las funciones que estás importando. Por ejemplo, si quieres importar `print_tablero` del archivo `tablero.py`, la mejor práctica sería `from tablero import print_tablero`.

**Comment by Isiirribarra** [comment]
estoy usando python 3.10.6

**Comment by vicentethomas** [comment]
Python 3 por defecto utiliza encoding utf-8, sin embargo el error que obtienes es porque está utilizando encoding ascii :fearful:. El problema probablemente sea del editor y no de python.
Lo que puedes hacer, es agregar la siguiente línea al comienzo de todos tus archivos .py:
`# -*- coding: utf-8 -*-`
Con eso va a cambiar la codificación. En todo caso, tener que poner esta línea en cada uno de tus archivos va a llegar a ser bastante tedioso, por lo que te recomiendo acercarte en la próxima clase o ayudantía a alguna persona del equipo docente para que te pueda ayudar en vivo y arreglarlo para todos los archivos!
Otra solución, es utilizar la consola/terminal de tu computador para correr los archivos. Para eso, abre la terminal desde la carpeta con tus archivos python, y en la terminal ingresas: `python archivo.py` para correr ese archivo.

Cualquier duda, no dudes en preguntar 👍

**Comment by valeureta** [comment]
Hola, tengo una duda. Estoy usando las funciones dadas en el modulo tablero.py. Y al imprimer el tablero me aparece de la forma
     A B C D
    ┌─────────┐
  0 │ ■ ■ ■ ■ │
  1 │ ■ N ■ ■ │
  2 │ ■ N ■ ■ │
  3 │ ■ ■ N ■ │
    └─────────┘
Esta bien que se vea donde estan las N? o para el jugador deberian estar ocultas?

**Comment by vicentethomas** [comment]
Hola!!  @valeureta Perdón la demora, la notificación se me perdió entre tantas issues (mala mía 😔). La respuesta a tu pregunta la respondieron en la issue #82. En resumen, la idea es que el usuario no pueda saber donde están las bestias gráficamente.
