### ISSUE TITLE
Jupyter Notebook para ver contenidos

### ISSUE THREAD

**Issue by fabarros** [IIC2233/Syllabus#27]
Hola, disculpen la ignorancia pero, existe alguna forma de leer los contenidos con Jupyter Notebook para ir ejecutando y/o modificando los códigos?
Muchas Gracias!

**Comment by mfanselmo1** [comment]
Hola!
La idea de los jupyter notebooks entregados es que los vayas ejecutando y cambiando el codigo para entenderlo mejor. Para instalarlo puedes ver la documentacion http://jupyter.readthedocs.io/en/latest/install.html
y para abrirlos tienes que ejecutar el comando `jupyter notebook` en consola

**Comment by fgbruna** [comment]
Si es que ya tienes instalado jupyter, es decir puedes ejecutar `jupyter notebook` en la terminal y se abre tu navegador predeterminado solo basta con seguir los sgtes pasos:
```
git clone `https://github.com/IIC2233/contenidos.git` #

**Comment by fabarros** [comment]
Listo! Muchas gracias m3n.
