### ISSUE TITLE
Actividades anteriores

### ISSUE THREAD

**Issue by fabarros** [IIC2233/Syllabus#27]
Hola, en ayudantía se comentó que sería bueno realizar actividades de semestres anteriores para preparar la actividad en clases, ¿dónde puedo encontrar dichas actividades? Gracias.

**Comment by sebacruzd** [comment]
Hola,
[Acá](https://github.com/IIC2233/Syllabus-2017-1) puedes encontrar el Syllabus del semestre anterior.

Saludos!

**Comment by Arcoirisky** [comment]
En Code, vas a ver un texto con todas las reglas del curso. Al final salen los repositorios de semestres anteriores. Ahí debería estar todo
