### ISSUE TITLE
¿Qué es la función de hash?

### ISSUE THREAD

**Issue by Piolawa** [IIC2233/syllabus#27]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

En la parte donde se enseña sobre "diccionarios", hay un apartado sobre la función de hash.
Pero aún no comprendo cómo funciona ni para que sirve, y cual es su relación con los diccionarios.
Lo único que entiendo es que entrega unos números, que asumo ,se utilizan para identificar un elemento, y luego sea más facil encontrarlo
Gracias de antemano :)

**Comment by aerotecnia99** [comment]
Hola!
Ese apartado es para explicar mas que nada cómo estan implementados los diccionarios, lo cual es mediante una tabla de hash. En esta estructura se aplica la función de hash, la cual recibe como entrada una llave del diccionario y entrega como resultado un entero, al que llamamos valor de hash o hash de un dato (como el rut de una persona). Entonces, cada llave que ingrese a la función se identificará con un solo valor de hash para que cuando lo busquemos en la tabla de hash sea más rápido y eficiente.

Es importante que las llaves a utilizar sean únicas y hasheables (built-ins inmutables), ya que si fuese posible usar una estructura mutable como una lista (la cual es posible cambiar su contenido) cuándo se quiera acceder a su valor de hash sería distinto cada vez que cambiemos algo en ella.

Aqui te dejo un link [https://pythondiario.com/2018/06/tabla-hash-en-python.html](url)
Espero haber aclarado tu duda ( ｡◕ ‿ ◕｡)

**Comment by Piolawa** [comment]
Gracias! Ahora si entendí uwu
