### ISSUE TITLE
Colisiones detectadas solo en bordes y Clase Froggy

### ISSUE THREAD

**Issue by benja20029** [IIC2233/Syllabus#270]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Implemente una colision a nivel basica entre un auto en movimiento permanente y el personaje principal (Froggy), sin embargo, esta colision solo es detectada a nivel de bordes, por lo que hay veces que Froggy llega a estar dentro del auto y la colision no es detectada. ¿Hay alguna manera de solucionar esto? ¿Se debio a mal codigo de mi parte o debido a que no utilice una funcion que implementa que haya colisiones al tocar cualquier parte del rectangulo de las entidades?

En segundo lugar, tengo la duda si es necesario implementar una clase Froggy o clase de autos, o solo los puedo modelar de la manera que guste mientras funcionen como deben funcionar?

**Comment by rodrigobj99** [comment]
Hola @benja20029! En cuanto a lo primero, la recomendación (dada en el enunciado) es implementar las intersecciones (colisiones) mediante el metodo intersects de la clase QRect de QtCore.

En cuanto a lo segundo queda a tu criterio mientras cumpla con lo que se establece en el enunciado y en la distribución de puntaje de la tarea.

Espero te sirva, saludos!
