### ISSUE TITLE
Parámetro DIAS_TORNEO y DIAS_TOTALES _TORNEO

### ISSUE THREAD

**Issue by MariaJoseSilva** [IIC2233/Syllabus#270]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola!
En las páginas 3 y 8 del enunciado se habla sobre el parámetro DIAS_TOTALES_TORNEO y en el página 5 sobre el DIAS_TORNEO, estos parámetros parecen hacer alusión a lo mismo ¿es necesario definir los 2 ?

Gracias

**Comment by emolaba** [comment]
Hola @MariaJoseSilva ! Tal como se dijo en las issues #249 y #131 ambos parámetros corresponden a lo mismo. Pueden usar cualquiera de los dos en su archivo parametros.py.
Saludos!
