### ISSUE TITLE
Uso de código tarea anterior

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#270]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!

Sobre el manejo de archivos `*.csv` en la Tarea 0 hice un módulo con funciones y muchas de ellas me sirven ahora también. ¿Puedo "reciclar" esas líneas o usar parte de ese módulo? Es que no sé si puedo referenciar mi propio trabajo anterior.

Desde ya, gracias 😄.

**Comment by Emiliax16** [comment]
¡Hola! por supuesto que puedes! simplemente escribe en el README que esas líneas de código fue elaboración propia aplicada en la T0.  c:

**Comment by Rerro-r** [comment]
Muchas graciaasss @Emiliax16 ❤️❤️❤️
