### ISSUE TITLE
Iteradores e iterables [Python]

### ISSUE THREAD

**Issue by BibarelUsedFly** [IIC2233/Syllabus#270]
Al comenzar a iterar sobre un iterable no iterador, se llama al método __iter__, que retorna un iterador.
¿Es correcto esto? De ser así, ¿Pasa lo mismo con los iteradores?

Esque tomé este ejemplo de iterador de los contenidos:
```
class Fib:
    def __init__(self):
        self.prev = 0
        self.actual = 1

    def __iter__(self):
        return self

    def __next__(self):
        valor = self.actual
        self.actual += self.prev
        self.prev = valor
        return valor 
```

y eliminé el método __iter__
pero al hacer:
```
f = Fib()
next(f)
```
funciona.
¿Por qué pasa esto?

Gracias de antemano.

**Comment by sebacruzd** [comment]
Esto es porque la función **tiene el método** next definido.

Si te fijas es como si le definieras un método cualquiera, con otro nombre y que lo uses. Es por esto que no estás llamando al método iter con lo que haces.

Lo que ahora no puedes hacer es usar ese objeto como un iterable (ya que al borrarle el __iter__ deja de ser un iterable).
Prueba usando esto con el método __iter__ definido y después borrándolo: (ejemplo burdo)

```python
f = Fib()

contador = 0
for i in f:
    print(next(f))
    contador += 1
    if contador == 10:
        break
```

Con el for si se está usando el método iter, haciéndolo un iterador. Cuando no tengas el método __iter__ vas a ver que ya no te deja usarlo, cosa que pretendías que sucediera antes con el __next__.

Revisa [este link](http://stackoverflow.com/questions/9884132/what-exactly-are-pythons-iterator-iterable-and-iteration-protocols) para salir de la duda.

**Comment by sebacruzd** [comment]
@BibarelUsedFly si tu duda está resuelta cierra el issue, lo haré yo esta vez, pero debes cerrarlos cuando te responden, o preguntar de nuevo si no entendiste.
