### ISSUE TITLE
Conceptos mínimos solicitados

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#270]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas. Consulta, si en el enunciado dice lo siguiente "Deberás utilizar conceptos claves como herencia, clases abstractas, polimorfismo, properties, etc." ¿debemos utilizar TODOS los conceptos vistos? o hay un mínimo de contenidos que debemos usar obligatoriamente??

**Comment by CatalinaBO** [comment]
Así es, debes usar todos los conceptos que se mencionan en el enunciado para cumplir con el formato de entrega. Igualmente puedes ver que uno de los objetivos de esta tarea es aplicar los conceptos de programación orientada a objetos (POO), por lo que deben utilizarlos todos para poder evaluar los contenidos enseñados.

**Comment by vitoco11** [comment]
Es necesario implementar @abstractmethod o con solo ocupar una clase abstracta como clase1(abc) ya es suficiente para el ámbito de clases abstractas.
