### ISSUE TITLE
Consultas y estadísticas sobre el grafo de afinidad

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#270]
Las consultas y estadísticas sobre el grafo de afinidad deben ser llamadas mediante una especie de menú? De ser así, sería fuera de la GUI, no?

**Comment by monicabelen** [comment]
Se hacen en consola.

**Comment by llloyola** [comment]
Y se tiene que desplegar un menú? O el ayudante que me corrija debe llamarlos él mismo en consola?

**Comment by yoavnavon** [comment]
La idea es que implementes una interfaz sencilla para mostrar los resultados, al igual que en la tarea pasada.

**Comment by llloyola** [comment]
Tengo un módulo llamado Grafo.py
Puedo especificar en el README que esta "interfaz sencilla" se desplegará sólo cuando se corra directamente mi módulo Grafo? O necesariamente tienes desplegarse en la consola al correr demo.py?
