### ISSUE TITLE
Duda modelaje colisión

### ISSUE THREAD

**Issue by Witomi** [IIC2233/syllabus#270]
Hola! 
Tengo la duda de como modelar bien la colisión, ya que tengo una variable con los obstaculos guardados y no se si se debe:
 -Revisar en el frontend si es que el movimiento del personaje se puede y evitar que se envíe la señal de que se mueva
 -Revisar en el backend con properties y setter si se puede, esta me tinca más, pero no sé como utilizar la variable de obstaculos si es que no es un atributo del personaje
Muchas Gracias desde ya!!

**Comment by lily416** [comment]
Hola 😄 

Lo más correcto es que la variable que guarda los obstáculos este en el _backend_, ya que ahí es donde se debe procesar si es que el movimiento es válido o no. 

Lo que puedes hacer es guardar es tener una clase `Juego` la que guarde la instancia del `Personaje`, `Enemigos` y los distintos elementos del mapa. Esta clase se podría encarga de relacionar todos los elementos entre sí y de la comunicación con el _frontend_.

Ánimo y éxito con la tarea 👋 🐈🐧
