### ISSUE TITLE
Mi QTimer no pesca el timeout

### ISSUE THREAD

**Issue by FlorenciaOnetto** [IIC2233/Syllabus#270]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Llevo mucho rato tratando de solucionar un problema con un QTimer. Resulta que independiente del tiempo que le ponga al intervalo, el timer no conecta con la función del timeout. Busqué en google y puede ser un problema de que dos threads se están sobrelapando, pero no sé como solucionarlo. 
Espero que puedan ayudarme.

**Comment by Hernan4444** [comment]
Hola @FlorenciaOnetto porfa actualiza tu repositorio de github e indicanos qué QTimer es para tener más contexto del problema c:

**Comment by FlorenciaOnetto** [comment]
Ya actualicé mi repositorio. Es el QTimer self.timer_aparicion_soles, en backend, en el archivo plantas, en la clase Girasol. El timer se inicia en el método iniciar_timer(), el cual es llamado con una señal cuando se presiona el botón botón_iniciar de la ventana juego.

**Comment by Hernan4444** [comment]
Hola @FlorenciaOnetto revisé el código y me percaté que dicha función conectada en el `timeout` está definida 2 veces en la clase. en la primera tiene el `print` que tu incluiste mientras que la segunda llamada no tiene `print`.  Puede ser eso lo que provoca que la función que tu quieres que se ejecute, no pase  nada, puesto que fue sobreescrita.

Luego, la segunda función hace la emisión de una señal, pero eso todavía no está conectada a nada, por eso tal vez no veías nada en pantalla.

Revisa esa parte del código y avisa si se soluciona el problema del QTimer. Quedamos atentos en el foro :D 
Saludosヾ(＾-＾)ノ
