### ISSUE TITLE
Archivos a subir para la tarea

### ISSUE THREAD

**Issue by Pdesolmi** [IIC2233/syllabus#270]
cuales son los archivos que hay que subir exactamente, se que sale que hay que ignorar los estáticos, que serían contrincantes y pistas. Pero también hay que ignorar el enunciado o no?. No estoy muy seguro que archivos subir exactamente

**Comment by cfalvarez2** [comment]
Hola @Pdesolmi :)
Como tú bien mencionas, el enunciado dice que debes ignorar los archivos estáticos `pistas.py` y `contrincantes.py`. Por lo tanto debes subir todos los archivos modificados por ti y que sirven para el correcto funcionamiento de tu programa, al final es lo que se evaluará.  
Te recomiendo que si el enunciado está dentro de tu carpeta T01 también lo ignores, al igual que las carpetas o archivos pycache, .idea, etc., pero para efectos de esta tarea solo se evaluará que hayan ignorado los dos archivos mencionados al principio.
Saludos.

**Comment by FelipeA7** [comment]
@cfalvarez2 hola! ayer sin querer subí esos 2 archivos. Qué tengo que hacer ahora para borrarlos?
Basta con agregarlos ahora al .gitignore y hacer un push?

**Comment by Jprampad** [comment]
@FelipeA7 
git rm --cached nombre.csv
git commit -m 'Algo'
git push

y después cuando quieras añadir algo, asegurate que los archivos que sacaste estén en el git ignore y así no hacer esto de nuevo
(el --cached es para que sólo se borre el archivo en tu github, si es que no lo pones, te va a eliminar el archivo en tu github y en la carpeta de tu computador que tienes linkeada con tu repositorio)
