### ISSUE TITLE
Validación de "unidades" en el flujo

### ISSUE THREAD

**Issue by ssepul21** [IIC2233/Syllabus#270]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!
 Espero se encuentren bien. Quería consultar si **hay un momento determinado en el que debamos avisar que el archivo `unidades.txt` es inválido o si queda a nuestro criterio** en qué momento se avisa, ya que, de lo que pensé, podría avisar al momento de intentar comprar un gato, al inicio del programa, al abrir la tienda, etc.

Gracias de antemano! 😁

**Comment by wintermelyn** [comment]
Hola @ssepul21!

El enunciado solo especifica:

"deberás asegurarte de que el archivo es correcto al momento de cargarlo, imprimiendo un mensaje de error y terminando el programa si no es el caso."_

Por lo que quedará a su criterio cuando **carguen** el archivo. Sin embargo te recomiendo igualmente que sea algo que valides al inicio de tu programa.

**Comment by ssepul21** [comment]
Entiendo! Muchas gracias
