### ISSUE TITLE
Determinar ocurrencia de acciones y eventos 

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#270]
Hola!
Cuando se refieren a las "probabilidades" de ocurrencia de una acción, para todas éstas debo evaluarlas de la misma manera en toda la tarea.¿?
Me refiero a que en el enunciado, página 9, indican cómo debemos evaluar estas "probabilidades":
"Para determinar si el evento ocurre, es recomendable que usen la función random.random para obtener un número aleatorio entre 0 y 1, el cual deberás comprobar si es mayor o menor que la probabilidad del evento."
Mi pregunta es que si esto se evalúa para todas las probabilidades de las distintas acciones que se ven en la tarea?

**Comment by moquezada** [comment]
Hola @Camila-sty,

Puedes utilizar esa técnica para determinar la ocurrencia de las acciones y eventos pertinentes sin ningún problema 👀 

Debes tener en cuenta que las distintas acciones y eventos poseen diferentes probabilidades de ocurrir, y por lo tanto, lo más adecuado es que evalúes de forma independiente si sucedieron no. Ahora, cada una de esas evaluaciones las puedes realizar usando la misma técnica.

Comenta en esta misma issue si sigues con dudas al respecto. Espero haberte ayudado ☺️

**Comment by Juampisaez** [comment]
Una duda, si ocurre que el random es mayor a la probabilidad, entonces el evento no ocurre? y en el otro caso, ocurre? No entiendo bien la explicacion del enunciado, podrian dar un ejemplo?

**Comment by Juampisaez** [comment]
Sigo teniendo la duda que hice mas arriba

**Comment by JosefaPaz** [comment]
Hola @Juampisaez , y la issue %325 no te la aclaró? Podrías explicarme nuevamente la duda, puede que yo no la esté entendiendo bien.

Quedo atenta

**Comment by Juampisaez** [comment]
Perdon, no la habia visto. Me queda claro, gracias!
