### ISSUE TITLE
 Imagen "GCCRPG.png" pareciera ser RCRGPG

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#270]
Hola! Tal como se comentó en #233 (pero sin respuesta), la imagen "GCCRPG.png" es muy confusa visualmente pues pareciera ser RCRGPG. La imagen tiene un río que parte por un lado y sale por otro, pero según su tipo el río solo entra por un lado y no sale por ninguno. Se que el programa debe correrse considerando el tipo tal como es y no a la imagen, pero al momento de jugar se hace confuso y uno piensa que es el código el que está malo. Sin ánimos de sonar "mandón", cuando corrijan la tarea por favor tengan en cuenta esta y otras fichas que visualmente parecieran ser de un tipo distinto al que son y es por eso que no pueden conectarse a otras y no porque nuestro código este malo.

**Comment by cilopez** [comment]
Efectivamente realizaremos esto al corregir ,~~excepto para el "mandón"~~ , no se preocupen tanto por esos casos que son un poco ambiguos dada la visualización de la pieza.

**Comment by Fhguinez** [comment]
¿Entonces consideramos la pieza como GCCRPG o como RCRGPG?

De ser el primer caso, ¿podrían proporcionarnos la visualización correcta de la pieza? Esto es necesario para saber si los lados de ciudad están conectados dentro de la misma pieza o no.

De ser el segundo caso, ¿podemos modificar el nombre del png, archivos.py y pieces.csv para que la pieza sea coherente con su visualización?

**Comment by cilopez** [comment]
@Fhguinez  Subiremos al *Syllabus* nuevas piezas, para que no contengan estos problemas :hammer: :factory:

**Comment by Arcoirisky** [comment]
Vean la issue #233 y comenten si existe algún percance.
