### ISSUE TITLE
Crear archivos extras

### ISSUE THREAD

**Issue by lorenzosilva** [IIC2233/syllabus#270]
Buena! 

Se pueden crear archivos extras a los que dan para poder guardar variables? 
Por ejemplo, quiero guardar las variables del número de filas y columnas que entrega el usuario para poder usarlas en difentes funciones.

**Comment by bvasquezm** [comment]
Hola @lorenzosilva!

Se responde a esta misma duda en la issue #93. Suerte con tu tarea!

**Comment by lorenzosilva** [comment]
Gracias!!
