### ISSUE TITLE
duda numero de filas 

### ISSUE THREAD

**Issue by jo00** [IIC2233/syllabus#271]
Hola.
Me surgio una duda respecto al numero de filas que se muestran en pantalla.
Porque el rango de filas posibles es de 3 a 15, sin embargo el tablero imprime desde el 0. Por lo tanto mi duda es si se considera el numero de filas apartir de este o no? Por ejemplo, si el usuario en un inicio selecciona 15 filas, el tablero debe imprimir hasta el 14 (ya que con la fila 0 serian 15) o hasta el 15?  desde ya graciaas

**Comment by jitorcas** [comment]
Hola! @jo00 

Independiente de que el tablero imprima desde el 0, debes respetar la cantidad de filas y columnas que el jugador quiera. 

Ejemplo: si el jugador quiere 3 filas, el tablero nombrará las filas como **0, 1 y 2**, pero en cantidad son 3, así que se cumple lo que el usuario desea. 

Espero me haya explicado bien, si quedas con dudas avísame! 

Éxito en la tarea! ⚓️
