### ISSUE TITLE
Movimiento de enemigos continuo

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2233/syllabus#271]
Hola, tenía una duda: Se puede modelar un movimiento continuo para los enemigos? Todo esto siguiendo los caminos hasta el final (como los TD normales)

**Comment by lily416** [comment]
Hola 😄 

Lo siento, no puedes implementar movimiento continuo para los enemigos 😞 
Con esta tarea buscamos evaluar que implementen los distintos tipos de movimiento, así que tómalo como una oportunidad para aprender más :sunglasses:

Ánimo y éxito con la tarea 👋 🐈🐧

**Comment by jitorcas** [comment]
Hola!
siguiendo la misma duda, ¿es posible determinar los posibles caminos que pueden seguir los enemigos desde un inicio y asignarle ese camino determinado al enemigo?  o lo que piden es que el enemigo en cada paso que da tenga la opción de elegir cuál es su siguiente paso de manera totalmente aleatoria?

 Entiendo la dinámica de pedir que el camino que sigan sea al azar, pero si desde el comienzo creo muchos caminos posibles a la base y a cada enemigo le asigno uno al azar también lo estaría haciendo aleatorio pero determinando desde antes que no se meta a caminos que no pueda salir.

**Comment by JJJGGGG** [comment]
Por otro lado, es posible animar el movimiento de los enemigos como continuo, pero modelarlo como discreto? Es decir, que siempre se detengan en una casilla, pero que puedan moverse entre las casillas?

**Comment by lily416** [comment]
@JJJGGGG Sí, si se puede 😄 

@jitorcas Depende mucho de cómo decidas los caminos que van a seguir los enemigos:
- Si son **caminos totalmente aleatorios**, entonces no es improbable que te quedes en un _loop_ al generar los caminos, por lo que deberías controlar esos casos haciendo que sea bastante complicado lo que quieres hacer. No te recomiendo mucho esta opción. 😖 
- Si son **caminos directos a la torre**, es decir no aleatorios,  tal vez sea una buena opción que te plantees hacer el bonus de la tarea y mandar a todos los enemigos por los caminos más cortos (también puede ser que solo sea uno). 🤔

En general el que el movimiento de los enemigos sea aleatorio busca simplificarles la tarea, no hacerla más difícil, así que tampoco es una mala opción que hagas el **movimiento aleatorio de casilla en casilla**. 😉✨  

Que les vaya muy bien en la tarea 🙌😸
