### ISSUE TITLE
Posicionar plantas

### ISSUE THREAD

**Issue by MaximilianWilke** [IIC2233/Syllabus#271]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo problemas para determinar si es más conveniente posicionar las plantas mediante clicks en el tablero o arrastrando las plantas (de cualquier modo estoy complicado con ambas, he buscado en internet pero no he encontrado algo que me sirva o entienda del todo)

**Comment by Lord-Kelsier** [comment]
Hola @MaximilianWilke, arrastrar las plantas es mas complejo, por este motivo es un bonus (Drag and Drop). 

En terminos generales lo que se debe hacer aqui es:
1) hacer click en una planta
2) por dentro revisar que planta fue 
3) click en donde se quiere plantar
4) por dentro revisar si este lugar es apto o no para plantar. Si lo es colocar la imagen

Esto se encuentra especificado en la seccion 5.4.2 del enunciado. Intenta traducir esto a codigo y se te hara mas sencillo

**Comment by MaximilianWilke** [comment]
Entiendo el orden en el que se quieren hacer las cosas, mi problema es que ya uso un mousepressevent(event) para revisar si se clickeo en una papa o otra cosa, entonces no se como obtener el segundo click para verificar si estamos en las casillas

**Comment by Lord-Kelsier** [comment]
no existe otro click, todo lo debe hacer esta funcion. Hay varias formas de abarcar el problema, la primera que se me ocurre es usar señales y que en backend se guarden "estados", como por ejemplo `hizo_click_en_planta = True` e ir revisando si estos estados para ejecutar o no una accion

**Comment by MaximilianWilke** [comment]
gracias logre hacerlo
