### ISSUE TITLE
Duda imagenes en qtdesigner

### ISSUE THREAD

**Issue by Crisax234** [IIC2233/Syllabus#271]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo problemas al intentar cambiar imagenes en un label donde ya tengo puesta otra imagen pero desde qt designer, ya que al momento de intentar cambiar la imagen desde el codigo desaparece el label, ya he utilizado el metodo raise_() pero no me funciona, hay alguna manera de poder solucionarlo?

**Comment by rodrigobj99** [comment]
Hola @Crisax234! Lo otra opción que puedes probar es usar el método lower() para enviar la otra ventana hacia el fondo.

Avisame si te funciona, saludos!

**Comment by Crisax234** [comment]
Ahora si me funciono, muchas gracias!

**Comment by llambias** [comment]
hola yo también tengo este problema, aun después de  usar lower()
