### ISSUE TITLE
Parametros cambiantes entre partidas

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus#271]
Estaba pensando en que supongo que los ayudantes podrian tener el parametro de mejora de chasis como 4 al iniciar la partida, pero despues la modifican y cargan esta misma partida, teniendo como valor 8 ahora. Entonces supongamos que el valo base del chasis era 5, luego con la mejora seria 4x5. Entonces luego deberia ser (4+8)x5? Ya que al inicio yo tenia los parametros estaticos por cada partida, digamos que si las mejoras eran 4, entonces iban de 4 en 4 para siempre.

**Comment by jmwielandt** [comment]
Hola, 😄 

Siento que te estás complicando sin necesidad 😥, el cambio en los valores de los parámetros no es algo de lo que deberías preocuparte en absoluto, nosotros los usaremos para facilitar la corrección (pero no por ello quita que sean una buena práctica y representen una buena modelación).

Contestando tu pregunta, sí, el valor sería `(4 + 8) * 5`. Solo debes preocuparte de usar correctamente los parámetros y no de sus valores.

Saludos y ánimo con la tarea, enfócate en completar funcionalidades y testear tu código 👍

**Comment by jmwielandt** [comment]
Hola de nuevo @MartinAracena 

Solo quería agregar que después nos dimos cuenta de que no es `(4 + 8) * 5`, sino `4 * 8 * 5`.

Saludos~
