### ISSUE TITLE
Duda en la fórmula de la probabilidad de encallar

### ISSUE THREAD

**Issue by a-ck** [IIC2233/syllabus#271]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Duda
![image](https://user-images.githubusercontent.com/69538524/115473480-c943c800-a209-11eb-88b4-c41240d9e646.png)

Hola, puede ser que la operación dentro del min() es mayor a 1 para todos los barcos de barcos.csv? (Esto significaría que la probabilidad de encallar siempre sea tend_encallar*dif_canal)

**Comment by sperezmasri** [comment]
Hola @a-ck! Puede pasar que para el archivo ```barcos.csv```  que se entregó se cumpla eso. Sin embargo, ten en cuenta que ese archivo podría cambiar, por lo tanto tu programa debe considerar la formula completa de todas formas, ya que podrían existir casos donde lo que está dentro del **min** no sea mayor a 1.

**Comment by a-ck** [comment]
Ok entiendo, muchas gracias!
