### ISSUE TITLE
Criaturas.csv: EstadoEsc y EstadoSal

### ISSUE THREAD

**Issue by Francisco5674** [IIC2233/syllabus#271]
En el enunciado dice que tanto la variable EstadoEsc y EstadoSal son variables para determinar si una criatura se escapo o esta enferma respectivamente, diciendo que si son del tipo bool igual a "True" entonces efectivamente están enfermas o fuera de cautiverio, lo que me llama la atención es que en la base de datos al parecer todas las criaturas están enfermas y sueltas al parecer, eso es intencional o que onda?

**Comment by Dnpoblete** [comment]
Hola @Francisco5674 acabo de revisar la base de datos y hay varias con False lo que significa que no están enfermas ni en cautiverio, adjunto imagen ¿A ti no te sale así la base de datos?
![image](https://user-images.githubusercontent.com/42362982/78590109-4c68ca80-780f-11ea-9db5-5c86d79393cb.png)

Quedo atenta a tu respuesta! 😄

**Comment by Francisco5674** [comment]
oh verdad, no se que paso, creo que debí haber modificado la fuente sin darme cuenta, sorry...

**Comment by Dnpoblete** [comment]
No te preocupes, que buena que se haya solucionado 😄 
Éxito con la tarea!
