### ISSUE TITLE
Atributos de Cilantrillo

### ISSUE THREAD

**Issue by gracie-14** [IIC2233/Syllabus#271]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Con el Cilantrillo, ¿tanto el aumento como el potencial _necesitan_ ser atributos de la clase? ¿O está permitido implementar, por ejemplo, el aumento de soles de otra manera para cumplir con lo pedido del enunciado (por ejemplo, modificando a un método de otra clase)?

**Comment by CatalinaBO** [comment]
Holaa, respondiendo a tu pregunta, eres libre de realizarlo de la forma que encuentres correcta, siempre cuando se realice lo solicitado y se utilicen los conceptos de POO. Precisamente eso es lo que se busca con esta tarea, que sean capaces de modelar su programa tomando sus propias decisiones. Igualmente recuerda dejar claro en el README las consideraciones que hiciste.
