### ISSUE TITLE
CURAR EJERCITO SI ESTE ESTA FULL VIDA

### ISSUE THREAD

**Issue by elshavi** [IIC2233/Syllabus#271]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Si se selecciona la opcion en tienda de curar ejercito, pero este ya esta full vida, igualmente se debe "curar" y descontar el dinero? En el enunciado no aclara que hacer con esta situacion por lo que supongo que queda a decision nuestra, de igual forma igual me gustaria confirmar si esto es asi.
Aclaracion: por lo que vi nadie aun pregunta esto, pido perdon si ya habia una issue, no la vi.
[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by wintermelyn** [comment]
Hola @elshavi!

Es un caso borde que no toca el enunciado así que queda a su criterio la manera de abordarlo. 🧙‍♂️ Aunque quizás lo más normal sea que no te descuente el dinero, pero es opcional.
