### ISSUE TITLE
¿Puedo editar el archivo piece.py?

### ISSUE THREAD

**Issue by nlvargas** [IIC2233/Syllabus#271]
En mi modelación del problema requiero que la clase Piece() tenga un par de atributos que no están implementados. ¿Puedo alterar ese archivo? 
Segun entiendo al estar en la carpeta .gui van a ser ignorados estos archivos por el .gitignore por lo que al subir la tarea estos cambios no se subirían a mi repositorio.

**Comment by iqacevedo** [comment]
Hola,

No puedes ocupar los archivos de la gui, esto incluye a Piece, por lo que no deberías requerir utilizarla. Cualquier modificación, tal como dices, no será considerada, lo que podría ocasionar que tú programa no funcione si utilizas modificaciones de los archivos que te entregamos.

Saludos !
