### ISSUE TITLE
Crear mis propios equipos

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#272]
En el enunciado dice que los equipos rivales deben crearse con jugadores aleatorios. Dado el tiempo que me estoy demorando en calcular la esperanza de un equipo (acabo de probar con un equipo aleatorio y me demoré 7 minutos), podría yo elegir a los jugadores que sé que harán que mi programa demore menos en esa tarea?

**Comment by monicabelen** [comment]
Hola! Los jugadores deben ser aleatorios. Sin embargo, te recomiendo dejarlos fijos por ahora y seguir avanzando en la tarea. Luego puedes arreglar esa parte :)
