### ISSUE TITLE
Error formula de DCCriatura - Probabilidad enfermarse

### ISSUE THREAD

**Issue by drosselot** [IIC2233/syllabus#272]
Hola, en el enunciado, en el calculo de la probabilidad de enfermarse, sale que prob_enfermarse es la probabilidad de escaparse.

**Comment by Dnpoblete** [comment]
Hola @drosselot , gracias por comentarnos el error, efectivamente prob_enfermarse es la probabilidad de enfermarse y no la probabilidad de escaparse.

Éxito en la tarea! 😄
