### ISSUE TITLE
No me deja hacer git push

### ISSUE THREAD

**Issue by rominaarancibia** [IIC2233/Syllabus#272]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Que puedo hacer si no me deja hacer git push de lo que he avanzado?
Tengo clonado dos veces el repositorio porque me pasó algo similar en la actividad. Sin embargo, me pone problemas al intentarlo de cualquiera de los dos. Gracias

**Comment by Hernan4444** [comment]
Hola @rominaarancibia 

Probablemente, el error se puede deber a que modificaste tu repositorio desde la página web y luego no hiciste `git pull` antes de hacer un cambio en tu repositorio del computador. Esto provoca que haya un "conflicto" porque tu PC pasó de un estado A a un estado B dado el commit, pero la nube de git pasó de un estado A a un estado C. Por lo cual, ahora hay conflictos porque desde el estado A, ¿a cual se debe pasar? ¿Al B que tiene tu PC o al C que tiene la nube?

La recomiendación del curso es siempre:
- Si haces cambio en el computador, hacer `git push` de inmediato para que la nube se actualice.
- Si haces cambios desde la página web (cosa que en verdad no recomendamos), ir al PC y hacer `git pull` antes de editar cualquier cosa, así tu pc está actualizado a la última version.

De este modo, siempre la nube de git y tu PC están trabajando en el mismo estado. En otro caso, si editas la página web y no haces `git pull` en tu pc, pasarás por muchos "conflictos" despues 😢.

Ahora, para resolver el problema que tienes, recomiendo clonar un tercer repositorio, ahí poner tus nuevos archivos y hacer `git push`. Los 2 repositorios viejos eliminarlos y solo trabajar con el tercero. Y desde este momento, asegurar siempre seguir las recomiendaciones indicadas antes sobre `push` y `pull`. Si bien hay formas de enfrentar estos problemas sin clonar nuevamente el repositorio, requiere de usar unos comandos un poco más complejos que requieren tener un poco más de experiencia previa con git para entenderlos bien :D 

Saludosヾ(＾-＾)ノ

ps: igual cuando tengas un error, mejor si siempre subes una foto del error para tener una mejor idea.
