### ISSUE TITLE
Problemas Gui con rotar pieza

### ISSUE THREAD

**Issue by Jiparavich** [IIC2233/Syllabus#272]
Hola! cuando ejecuto en la demo, rotar pieza , y luego agrego dicha pieza, los pentagonos se me borran como en la siguiente imagen :

![pentagono](https://user-images.githubusercontent.com/30678179/30245745-0958a29a-95ba-11e7-9d3b-b3cd13d1e5a0.JPG)

Si actualize mis documentos por la falla comunicada hace unos días, por tanto no creo que sea eso, ojala se entienda mi duda, Gracias!

**Comment by Jiparavich** [comment]
Otro ejemplo: 
![image](https://user-images.githubusercontent.com/30678179/30245854-04b5672a-95bd-11e7-9ce4-a19512bc3432.png)

**Comment by Jiparavich** [comment]
Ya lo resolvi

**Comment by tanavarrete** [comment]
¿Como lo resolviste? me pasa lo mismo

**Comment by tanavarrete** [comment]
@Jiparavich ¿Como lo resolviste? me pasa lo mismo

**Comment by Jiparavich** [comment]
@tanavarrete Me pasaba que en una parte de mi codigo, estaba llamando al gui.nueva_pieza despues del gui.add, entonces estaba agregando "nada" , ojala te haya servido!
