### ISSUE TITLE
Cronología de cálculo de ataque en enfrentamientos

### ISSUE THREAD

**Issue by ssepul21** [IIC2233/Syllabus#272]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!
 Espero estén bien. Al momento de hacer enfrentamientos entre 2 combatientes, **¿tenemos que considerar los cálculos en base a las estadísticas del inicio de la pelea?** _(considerando que un combate es un conjunto de peleas)_. 

 Lo que pasa es que si, por ejemplo, 2 caballeros combaten, pasaría algo así:
1.  El caballero A **calcula** su ataque
2.  Asumiendo que el Caballero A logra activar el poder, baja el poder del Caballero B.
3.  Caballero B calcula su ataque, pero, independiente de si activa el poder o no, va a ser menor que si él hubiese calculado su ataque primero porque el ataque depende del poder y este último bajo por el ataque especial del Caballero A.

Esto puede ser aplicado a cualquier enfrentamiento donde se afecte alguna de las variables que están dentro de ataque, pero el enunciado no contempla nada al respecto más allá que el que se ataquen al mismo tiempo.  **¿Hay alguna solución recomendada para este aspecto en concreto?** 

Quedo atento.

**Comment by wintermelyn** [comment]
Hola @ssepul21! 🧙‍♂️

> ¿Tenemos que considerar los cálculos en base a las estadísticas del inicio de la pelea?

Queda a su criterio cómo realizan los cálculos de buffs/debuffs, ya sea de forma aditiva o multiplicativa o si consideran que no tiene sentido, la aplican una sola vez con las estadísticas del inicio de la pelea por ejemplo. Aun así me gustaría comentarte que la idea de que los ataques ocurran **al mismo tiempo** es que no ocurran casos como el de los 2 caballeros que mencionas, en el cual uno tiene ventaja sobre el otro por activar su poder primero.

>  ¿Hay alguna solución recomendada para este aspecto en concreto?

No hay respuesta correcta 😔 cada modelación que elijan tendrán sus pros y contras, y la toma de decisiones de diseño es un factor que buscamos evaluar por lo que el enunciado es ambiguo en varias partes para que tengan la libertad de elegir y explicar su decision en el README.md. Aun así para evitar el caso que propones en particular un acercamiento podría ser que los poderes de ambos caballeros se activen antes del calculo de daño, considerando las estadísticas que tienen al inicio del "turno".

**Comment by ssepul21** [comment]
Gracias por la respuesta! @wintermelyn 
Con respecto a eso, revise de nuevo las issues y en la issue [243](https://github.com/IIC2233/Syllabus/issues/243) se menciona que podríamos decidir cómo lo hacemos, mientras se cumpla que si uno de los combatientes es derrotada, pueda hacer su ataque igual. 
Ante esto, **¿podemos tomar cualquiera de las dos posturas y va a ser igual de válido?** (Asumiendo que lo hagamos sin errores, solo apunto al tema de construcción)

**Comment by wintermelyn** [comment]
@ssepul21

Es exactamente como dices, ambas maneras de abordarlo son validas y al final mi comentario fue solo una recomendación., por lo que si te resulta mas sencillo de otra manera puedes implementarlo y explicar tus consideraciones en la sección del README.

Al final lo importante es que ambos combatientes tengan la oportunidad de activar su poder y atacar antes de recibir el ataque que baje su vida a 0.
