### ISSUE TITLE
Atributo de clase en un diagrama de clases.

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#272]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola!

Me preguntaba cómo se escribe en un diagrama de clases un atributo de clase, ya que en el curso sólo hemos visto cómo representar los atributos de instancia y los métodos.

Desde ya, gracias 🥰.

**Comment by pabloist** [comment]
Hola!

Te comento que en los diagramas no se hace diferencia entre atributos de clase y atributos de instancia, en tanto el objetivo del diagrama es dar una vista general de las relaciones existentes en el código sin entrar en una profundidad y complejidad muy alta.

Saludos!

**Comment by Rerro-r** [comment]
Muchas gracias @pabloist  😃😃😃
