### ISSUE TITLE
Ventana se cierra

### ISSUE THREAD

**Issue by LucianoDavico** [IIC2233/syllabus#272]
Hola, estoy teniendo el siguiente problema.

Hice una ventana con QtDesigner (la ventana de iniciar sesion) y al momento de hacer self.hide() hago una instancia de mi clase Juego (la cual hereda de QWidget). Luego cuando hago instancia_Juego.show() se abre y se cierra instantáneamente esta ventana. Pero si abro directamente la ventana de la clase Juego no ocurre lo mismo (sin abrir antes la ventana de inicio). Ayuda por favor :)

**Comment by KnowYourselves** [comment]
Hola @LucianoDavico!

Me imagino que tu código luce más o menos así:

```python3
... 
def alguna_funcion(self):
    ... 
    juego = Juego() 
    juego. show() 
... 
```
El problema con esto es que los `QWidget` son _threads_, de hecho podria pensarse que específicamente son _threads daemon_, es decir, si el programa termina las ventanas se cierran. 

El problema con el código que te muestro es que la variable `juego` **solo existe dentro de la función**, es una **variable local**. Esto implica que cuando la función llegue a su final, esta variable **será eliminada** junto a otras variables locales. Es por esto que la ventana se abre (`juego. show()`) y se cierra inmediatamente (termina la función). 

La forma de solucionar esto es hacer que `juego` sea más que solo una variable local, podemos hacer que sea una **variable de instancia** haciendo uso de `self`:

```python3
... 
def alguna_funcion(self):
    ... 
    self. juego = Juego() 
    self. juego. show() 
... 
```
Con este cambio la variable no será eliminada y la  ventana no se cerrará.

Espero haberte ayudado!

**Comment by LucianoDavico** [comment]
Ahí me funcionó!! Gracias!!
