### ISSUE TITLE
Error al usar listas como objeto no "subscriptable"

### ISSUE THREAD

**Issue by bpb02** [IIC2233/Syllabus#272]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Cuando intento correr el codigo de test dice que mi codigo en las funciones "riesgo_mortal" y "usar_item" dan error porque 'type' object is not subscriptable. ¿Que debería hacer? (una copia de la lista o usar otro tipo de objeto)

**Comment by gasparbenavente2** [comment]
El error que te aparece se debe a que estás tratando de usar index[] a un objeto que no tiene esa funcionalidad. Lo más probable es que el objeto que esté entrando a la función como argumento no sea del tipo lista.
