### ISSUE TITLE
Python vs StressTest

### ISSUE THREAD

**Issue by 3rdPix** [IIC2233/Syllabus#272]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

¿La tarea debe ser fuertemente robusta? En concreto, me interesa saber si debemos lidiar con el hecho de que *Python*, cómo bien dicen las lenguas en el mundo de la programación, solo funciona *bien* cuando se importan librerías que no son de python. (xD)

En particular ¿Qué ocurre si mi tarea cumple con todo lo solicitado en el enunciado, pero no es un programa a prueba stress-tests? Estoy hablando, por ejemplo, si pauso el juego, hay que pausar muchos `QTimer` y detener muchos elementos. Inicialmente logré lo solicitado, pero no me convencía la "resistencia" del programa, mejoré un poco el resultado aplicando `QMutex` en algunos sitios clave para evitar recursión, pero aún así, el programa no es indefinidamente robusto: seteé una aplicación para que apretara la `P` (pausando y despausando el juego) docenas de veces por segundo, ante esta situación el programa se cayó. A simple vista asumo que se trata de la conocida *lentitud* de python, o algún problema interno de optimización (en particular de threads). 

Sé que PyQt es de origen `c++`, por lo que debería funcionar relativamente bien contra estos test de estrés, pero quizás estoy pasando por alto algo. Luego surgen dos preguntas:

- ¿La tarea tiene que ser aprueba de este tipo de situaciones? Estoy hablando de pruebas de **alta exigencia**, el programa puede manejar sencillamente la velocidad de input de un usuario.
- ¿ Por qué puede estar produciendose esto? ¿Cómo mejorarlo/solucionarlo?

**Comment by Lord-Kelsier** [comment]
Si la tarea se ejecuta y cumple con el enunciado no hay problema, a menos que desde un inicio vaya tan lento que sea injugable. 

En general, por mas que un lenguaje sea rapido como C, lo importante va por el algoritmo que estes usando, en el curso de Estructuras de Datos y Algoritmos se ven estas cosas. Aqui te presentan un problema, que con una solucion/algoritmo naive (en C), puede tardar horas y con un buen algoritmo puede tardar menos de 1 segundo (si, asi de brutal). A pesar de esto, en efecto python es lento y existen ciertos built-in que estan escritos puramente en cpython que son bastante mas rapidos, algunos ejemplos de esto son `sum` o la libreria `numpy` que esta escrita completamente en C
