### ISSUE TITLE
Duda QThreads en la interfaz

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2233/Syllabus#272]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
hola tengo un problema en el comportamiento de los threads, en mi cado todos los autos en el back son Qthreads, los cuales guardo en una lista, luego cuando inicio el juego se recorre esa lista de autos, se inicia el thread del auto[i], y se esperan unos segundos para avanzar en la lista, EL Problema que tengo es que por alguna razón, no se mostrará el juego (la ventana se queda en blanco) hasta que se haya recorrido toda la lista de autos y todos los autos estén andando.
¿Como puedo arreglarlo? o ¿que necesito revisar?

PD, la señal que muestra el juego es la misma que inicia el recorrido de la lista de autos y posteriores instanciamientos de autos

**Comment by Maxi1805** [comment]
Hola @vice-rosas99, por lo que pude ver en tu código el problema puede estar relacionado a que cada vez que creas el auto estas poniendo un sleep de 3 segundos, por lo general el sleep a no ser que se hagan ciertos cambios no funciona muy bien en estos trabajos, si pruebas a sacarlo la pagina debería aparecer inmediatamente.
Espero te sirva.

**Comment by vice-rosas99** [comment]
lo que pasa es que ese sleep es esencial, ya que debe haber un tiempo entre autos para que no salgan todos al mismo tiempo
Lo otro es que parece que recorrer y startear todos los threads autos en la lista autos toma prioridad al procesamiento de la interfaz

**Comment by Maxi1805** [comment]
El problema con eso es que al poner un sleep vas a hacer que todo el funcionamiento del código pare, por ejemplo eso quiere decir que si activas el sleep tus autos dejaran de moverse, puedes hacer una prueba y activar un sleep al apretar un botón, va a ver que todos los elementos paran de moverse. En este caso recomendaría mas el uso de timers que no te van a generar este conflicto.
