### ISSUE TITLE
Puntaje al salir del programa

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#272]
Hola!
Cuando el jugador esta en partida, pero en el menú de juego selecciona "Salir del programa" ¿Se debe calcular el puntaje?

**Comment by danckoo1** [comment]
Hola :)
Dado que en el enunciado no lo mencionamos explícitamente, puede quedar a tu criterio. Por una parte podrías calcularlo de igual forma que al rendirse, o derechamente finalizar la partida sin ningún cálculo.

**Comment by Margarita-Paz** [comment]
muchas gracias! :)
