### ISSUE TITLE
Tipo de atributo en los diagramas de clases

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#273]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!

En los diagramas de clases se nos pide indicar qué tipo de dato es cada atributo o lo que retorne cada método (como, por ejemplo, +nom: str).
En el caso de los atributos que se definen por los parámetros de `parametros` no se sabe si serán `float` o `int` al momento de la revisión. ¿Qué se pone en ese caso? ¿o esto no se implementa en el diagrama de clases de la T1?

Desde ya graciaassss ❤️.

**Comment by Juampisaez** [comment]
Hola @Rerro-r 
Como tal vez ya sepas, el diagrama de clases corresponden a las entidades que exiten en tu programa y que van a estar relacionadas entre si. Ahora bien, si utilizas algun parametro de este archivo como atributo por ejemplo, lo que te recomendaria yo es ver como se define en el enunciado tal atributo para esa entidad en particular (todos los types de los atributos minimos de las entidades se encuentran en el enunciado).

Avisame si queda mas claro o si era otra tu duda :)

**Comment by Rerro-r** [comment]
@Juampisaez graciass. Lo que pasa es que dan los types de casi todos menos de las de `TENDENCIA_ENCALLAR_X`, ¿debería ser un `float`? Además, si uno define el valor de un atributo mediante un método (ya sea de un parámetro o no) ¿en los diagramas tiene que quedar el atributo como `None` aunque después sí tenga un type? ¿O se debería poner `atributo = int()` (por dar un ejemplo) sabiendo que luego el método le otorgará un `int`?

**Comment by Rerro-r** [comment]
Sí, me quedó clarísimooo. Muchas gracias @Juampisaez te pasaste!
