### ISSUE TITLE
DragAndDrop es excluyente?

### ISSUE THREAD

**Issue by 3rdPix** [IIC2233/Syllabus#273]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En la sección de Drag and Drop, el enunciado dice: *"Al seleccionar una planta de la tienda, en vez de plantar mediante el uso del click izquierdo, deberás usar drag and drop para arrastrar la planta a su posición deseada en el mapa de juego"*. Quiero destacar el **en vez de**. Es necesario que sea excluyente? No es posible implementar ambos métodos y que quede a gusto del usuario como plante sus plantas? 

Es decir, el usuario puede tanto arrastrar la planta al campo de juego, como hacer clics por separado, y ambos métodos funcionan perfectamente. Siento que es más completo si tiene ambas opciones.

**Comment by Hellonston** [comment]
Holaa **3rdPix**! Para el puntaje **es necesario** que sea drag and drop, lo escribimos de esa forma para que se entienda que lo debe tener si o si. Como todo lo del enunciado es lo mínimo para que puedan construir la tarea le puedes agregar otras funcionalidades mientras no solape a una que sea minimo. Feliz de que hagas ambos! Eso sí deja escrito en el readme que hiciste ambos 🙌
