### ISSUE TITLE
Que pasa con el inventario al usar la opción Cultivar?

### ISSUE THREAD

**Issue by agukolubakin** [IIC2233/Syllabus#273]
### Prerrequisitos

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Si cultivo una planta en una posición donde ya había una anteriormente, en mi inventario de plantas solo debo restar una del tipo que planté? O debo agregar una del tipo de la que estaba originalmente en la posición? Es decir, si por ejemplo voy a clavar un Defensauce donde había un Potencilantro, en mi inventario debo quitar un Defensauce y agregar un Potencilantro? O ese Potencilantro se pierde?

**Comment by augustayanez** [comment]
Si al cultivar una planta ya había otra planta antes en la posición ingresada, esta se borra definitivamente y es reemplazada por la nueva. En el caso del ejemplo que tu expones, sólo deberías quitar un Defensauce de tu inventario, y el Potencilantro que había anteriormente en la posición es eliminado.
