### ISSUE TITLE
Duda en cuanto a criaturas fuera de cautiverio

### ISSUE THREAD

**Issue by Francisco5674** [IIC2233/syllabus#273]
Otra pregunta más, en cuanto a si una criatura esta fuera de cautiverio o no, resulta que para alimentar, sanar o usar tu habilidad especial de magizoologo, supongo que sera necesario que la criatura este en cautiverio, sin embargo nunca mencionan eso en el enunciado, dándome a entender que puedo alimentar a una criatura mientras tenga alimento y energía suficiente, pero no importa si la tengo en su respectivo recinto, yo creo que por sentido común las criaturas deben estar en cautiverio para ser sanadas o alimentadas, en cuanto a la habilidad especial, supongo que es un tipo de hechizo ya que estamos dentro del mundo de Harry Potter y es independiente de si la criatura este presente o no en cautiverio, estoy en lo cierto?, o todo esto puedo explicitarlo en los supuestos ?

**Comment by Dnpoblete** [comment]
Hola @Francisco5674 ,efectivamente para alimentar a la criatura esta tiene que estar en cautiverio, osea que no puedes alimentar a una criatura que se haya escapado. Y en cuanto a la habilidad especial, siguiendo con la misma lógica, los magizoólogos docencios no podrán saciar el hambre de una criatura que se haya escapado y los híbridos no podrán sanar a una criatura que se haya escapado.

Éxito con la tarea! ✨

**Comment by rldelafuente** [comment]
Hola! 
Siguiendo la linea de esta pregunta, ¿qué pasa en caso contrario, del que el usuario intente alimentar una criatura que se escapó? ¿Debe volver a preguntar cuál criatura quiere alimentar? ¿No se le debe ofrecer alimentar a criaturas que se han escapado o queda libre elección esto?

Gracias!

**Comment by Dnpoblete** [comment]
Hola @rldelafuente, como ya mencione en esta misma issue, NO se puede alimentar a criaturas que se escaparon. Queda a tu elección si quieres volver a preguntar a cual criatura alimentar, pero explicándolo en el ReadMe.

Éxito en la tarea! :smile:

**Comment by Mendez69** [comment]
se deben mostrar las criaturas que han escapado en mostrar estado?

**Comment by Dnpoblete** [comment]
Hola @Mendez69 está pregunta no tiene relación con el tema de la issue, ya que sería más acorde preguntarla en issues como la #247, en donde se habla de mostrar estado, de todos modos la respuesta es que sí se tienen que mostrar las criaturas que se han escapado, ya que aún pueden ser recuperadas por el magizoólogo y pertenecer a él.

Éxito con la tarea! :smile:
