### ISSUE TITLE
Duda sobre descanso excavadores

### ISSUE THREAD

**Issue by sebastianval22** [IIC2233/Syllabus#273]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]
 Hola! Tengo una duda con respecto al descanso de los excavadores y los días que descansan. Si mi excavador está descansando, pero tengo un ítem que me da energía, podría darle el item y que el próximo día cavé con la energía entregada?? Esto no está tan especificado en el enunciado por lo cual no se si está prohibido o si depende de cada uno (mencionandolo en el Readme).

muchas Gracias

**Comment by Benjeeeh** [comment]
Hola!
Efectivamente, como no se específica mucho en el enunciado, tendría mucho sentido de que un excavador que esté descansando y que se use un ítem que le otorgue energía, este pueda trabajar al simular un día ya que la energía != 0 y el uso de ítems afecta a TODOS los excavadores.
Puedes leer los comentarios de las issues #247 y #267 que se habló de esto mismo.

Éxito con la tarea!!
