### ISSUE TITLE
Requerimiento propias implementaciones de EDD

### ISSUE THREAD

**Issue by pdesolminihac** [IIC2233/Syllabus#273]
Si implemento una estructura de datos parecida a un Diccionario de Python pero echa por mi, ¿es estrictamente necesario que cumpla todas las funciones de un Diccionario aunque yo no las necesite? (por ejemplo que sea iterable)

**Comment by cilopez** [comment]
Tal como se menciona en el ítem **Master** del enunciado,  tu estructuras deben cumplir con los mínimos de cada estructura que se emula , por ende si bien tu estructura no debe ser exactamente un diccionario, debe tener implementados por ejemplo los metodos `__iter__` y   `__next__` ya que un diccionario es iterable

**Comment by rihanuch** [comment]
@cilopez las estructuras tienen que tener por ejemplo `__delitem__` a pesar de que no la utilicemos? O `sort()` si tampoco la requerimos nunca porque hicimos un híbrido de diccionario con lista

**Comment by cilopez** [comment]
En ese caso tendrías que en tu *readme* señalar porque tu estructura de datos es un híbrido, que ventajas tiene y también porqué no le implementaste  ciertos métodos que tienen alguna de las estructuras que conforman tu híbrído. 
Si lo que señalas nos hace sentido ,no le vería problemas, por lo que debes estar seguro que tu estructura a lo largo de tu tarea nunca necesitará realizar esas funciones.
