### ISSUE TITLE
Duda sobre utiles.txt

### ISSUE THREAD

**Issue by TomasAndresPino** [IIC2233/Syllabus#273]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
El documento utiles.txt es mis gatos disponibles para la compra. Mi pregunta es: cada vez que compro, ¿ya no puedo comprar ese gato que compre? En ese caso se me podrian acabar los gatos para comprar y quizás no vencer a Gatochico. ¿Esa opción existe? Si no, quizás cada vez que pierdo puedo volver a cargar utiles.txt pero quiero saber si es que esto se puede o no. Muchas gracias :)

**Comment by wintermelyn** [comment]
Hola @TomasAndresPino! 🧙‍♂️

Eres libre de considerar que existe una cantidad infinita de combatientes a comprar en la tienda ~(pues tal es la determinación de los gatos chicos para derrotar a Gatochico)~. Sin embargo ambos acercamientos que propones son igual de validos, asi que elige el que estimes conveniente y mencionalo en tu README.md 😉
