### ISSUE TITLE
DEBONIFICACION_OSADO

### ISSUE THREAD

**Issue by pwillmer** [IIC2233/syllabus#273]
Hola! , en parametros.py se encuentra como BONIFICACION_OSADO. debemos cambiarlo a DESBONIFICACION_OSADO ?
Gracias de antemano.

**Comment by gatochico** [comment]
Hola! Si te acomoda más, puedes cambiar dicho parametro a `DESBONIFICACION_OSADO`, o dejarlo como está, pero efectivamente ese parámetro se refiere a la desbonificación que recibe el osado al ganar experiencia. Para más información, revisa la issue #192 
Saludos!

**Comment by pwillmer** [comment]
Gracias!
