### ISSUE TITLE
error 403 Git; intento realizar push y me aparece eso

### ISSUE THREAD

**Issue by NicholasRoch** [IIC2233/Syllabus#273]
$ git add .
$ git commit -m "respaldo sin readme solo 75% testcases"
$ git push
me retorna el error:

$ git push
remote: Permission to IIC2233/Syllabus.git denied to NicholasRoch.
fatal: unable to access 'https://github.com/IIC2233/Syllabus.git/': The requested URL returned error: 403

**Comment by Dvckhv** [comment]
hola! estas trabajando en la carpeta de Syllabus y no en tu repositorio privado, intenta mover tu trabajo a tu repo personal :)
