### ISSUE TITLE
Verificar menu inicial

### ISSUE THREAD

**Issue by mjgarrido1** [IIC2233/syllabus#273]
al crear el menu inicial debo verificar que está correcta/llenada la información que pregunto para poder comenzar el juego. Esta verificación puede ir en el front end? o es estrictamente necesario que esté en el back end? Las verificaciones son como del tipo que vimos hoy en la actividad para el usuario y que esté marcado el bando (pinguinos o gatos).

**Comment by gatochico** [comment]
Hola! La idea del backend es manejar **toda** lógica tras tu programa, por lo que si es necesario que cualquier tipo de verificación se haga en este. El manejar las verificaciones para comenzar el juego en el frontend implicaría una mala modelación. Saludos!
