### ISSUE TITLE
vscode ya no ejecuta mi programa

### ISSUE THREAD

**Issue by Julius9** [IIC2233/syllabus#273]
Hola! Tenia la tarea casi terminada y ya pusheada a mi repositorio privado, pero de un momento a otro vscode dejo de ejecutar mi programa y en vez de eso tira un extraño mensaje. Al principio pensé que sería un tipo fallo de vscode que ya habia tenido y se solucionaba reiniciandolo, pero no hay manera de que funcione, después cambie de interprete de python de 3.7 a 3.8 y nada tampoco. Lo raro es que vs code todavia me ejecuta las actividades que hemos echo en el curso AC00 y AF01, incluso pycharm y el mismo python idle no abren  ni ejecutan mi Tarea.

Esto es lo que me sale al intentar ejecutarlo
<img width="1440" alt="Captura de Pantalla 2020-08-29 a la(s) 02 36 53" src="https://user-images.githubusercontent.com/26386517/91630692-7a5ad100-e9a1-11ea-9adf-4563aa277776.png">

Y esto es lo que aparece si apreto /usr/bin/python3
<img width="1440" alt="Captura de Pantalla 2020-08-29 a la(s) 02 37 11" src="https://user-images.githubusercontent.com/26386517/91630718-bdb53f80-e9a1-11ea-9e28-c5d638f2712b.png">

Si lo abro de todas maneras me aparecen puros caracteres raros
<img width="1440" alt="Captura de Pantalla 2020-08-29 a la(s) 02 45 19" src="https://user-images.githubusercontent.com/26386517/91630727-d291d300-e9a1-11ea-9120-9ec390dae00a.png">

Y como ya mencione ni el python iddle me ejecuta el programa
<img width="1440" alt="Captura de Pantalla 2020-08-29 a la(s) 02 39 30" src="https://user-images.githubusercontent.com/26386517/91630748-fc4afa00-e9a1-11ea-892d-369a38333505.png">

Como también dije el problema no existe cuando abro la AC00 y la AF01, el problema solo aparece con los módulos dentro de la carpeta T00 y en realidad no me acuerdo de haber echo algo muy sensible para que suceda esto :'(

**Comment by yuwet15** [comment]
Hola, no soy ayudante, pero tu estas ejecutando los módulos? Y dentro de los módulos debiese ocurrir algo? Si ejecutas el main, hay problemas?

**Comment by Julius9** [comment]
Si dentro de cada módulo tengo pruebas para saber si voy bien con las cosas, pero ninguno dentro de T00 funciona tampoco main.py ni tanpoco el tablero.py que viene por defecto

**Comment by furcelay** [comment]
Hola!

Estuve revisando tu repositorio y ocurre un problema al ejecutar `partida.py`, el programa se queda en un loop infinito al intentar generar los barcos (método `agregar_barcos` en `jugador.py`) ya que el tablero está lleno de barcos y no tiene donde generar el próximo.  Ve la línea 166 en `partida.py`, y chequea el número de barcos que estás intentando generar.

Espero que eso resuelva tu problema,
Saludos!

**Comment by furcelay** [comment]
Otra cosa,
Está muy bien que crees pruebas al final de cada módulo, pero el problema es que al hacer un import se ejecutará todo el módulo incluyendo las pruebas, por eso debes estructurar el módulo de la siguiente manera:
```python
# Clases/funciones que quiero exportar
class Clase1:
    # ...

class Clase2:
    # ...

# ...

if __name__ = '__main__':
    # pruebas que quiero que se ejecuten solo al correr directamente este archivo
    objeto_1 = Clase1()
    objeto2 = Clase2()
    # ...
```
Lo que hace la línea `if __name__ = '__main__'` es chequear si el módulo actual corresponde al módulo en ejecución.

**Comment by Julius9** [comment]
Hola furcelay! gracias por los consejos y por percatarte de un error de loop infinito en mi codigo. Pero el problema aun persiste el computador simplemente nunca ejecuta ningun modulo de mi carpeta T00, es por esto que no me percate del problema del loop, pues si no se ejecuta el modulo el loop infinito nunca empieza. He intentado varias cosas incluso escribir errores a proposito como sumar una lista con un string o llamar funciones que no estén definidas, pero el error nunca se arroja por que como ya dije el programa nunca empieza :(

**Comment by furcelay** [comment]
@Julius9 
Prueba ejecutar Python en un terminal sin correr ningún archivo (solo el *Pyhton interpreter* ejecutando `python` a secas) y prueba si funcionan las operaciones que estabas realizando. Si no funcionan hay un problema con tu instalación de Python y lo mejor sería desinstalarlo y instalarlo nuevamente. 

Si el *Pyhton interpreter* funciona correctamente sería un problema particular de tu tarea. Al menos en las imágenes que adjuntaste no se ve que ocurra ningún error con Python ni VSCode, las dos líneas que aparecen en tu terminal en VSCode son las que se muestran siempre al ejecutar un archivo... Te recomiendo ver lo de los barcos porque si se queda en un loop el programa daría la apariencia de que está fallando.

Cuéntame como te va con eso.

**Comment by Julius9** [comment]
@furcelay probé copiando y pegando las lineas de código en archivos nuevos en una carpeta nueva y funciona ! el programa se empieza a ejecutar (incluido el loop infinito) con normalidad, lo cual me parece aun mas extraño es como si mi computador se hubiera ensañado con la carpeta T00. Continuare el trabajo en esta carpeta externa y cuando termine la reemplazare por T00 y haré el push. Cuando haya terminado seguire tu consejo y desintalare e instalare nuevamente python y vscode. Gracias por tu ayuda y por pillar una pifia en mi codigo 😄

**Comment by furcelay** [comment]
@Julius9 no sé que habrá ocurrido :sweat_smile:, pero que bueno que tu problema se haya solucionado 😄
