### ISSUE TITLE
Decoradores

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#273]
si hiciese una funcion que decora una clase y recibe los metodos de la clase
(signo hacia arriba) puedo poner un for para que decore cada metodo de la misma forma?
eje:
```
def funcion(*args):
    for argumento in args:
        def _funcion(cls):
            metodo = getattr(cls, argumento)
            def __funcion(self, *args, **kwargs):
```
es valido esto  o no funcionaria?  :expressionless:

**Comment by Diiru** [comment]
Si. Es posible hacer un decorador que aplique cierta función a todos los métodos de una clase. Por ejemplo, podríamos aplicarle una función que convierta todos los métodos públicos a privados, uno que pase de CamelCase a Snake Case al revisar la sintaxis o cualquier aplicación que quieras hacerle.

Te recomiendo revisar estas dos actividades de semestres pasados, intenta hacer por lo menos una antes de la AC de decoradores. ([2016-1](https://github.com/IIC2233-2016-1/syllabus/blob/master/Actividades/AC06/main.pdf) y [2016-2](https://github.com/IIC2233-2016-02/Syllabus/blob/master/Actividades/AC06/Enunciado.pdf))

**Comment by Dunkan1** [comment]
gracias, justamente estaba intentando hacer la AC del 2016-1, la parte de CamelCase a Snake Case y por eso me surgio la duda, ya que ese decorador lo estructure de la forma que mostre anteriormente
