### ISSUE TITLE
Duda sobre uso de un diccionario o lista de listas en parametros.py

### ISSUE THREAD

**Issue by EnzoMorata** [IIC2233/Syllabus#273]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda sobre si es posible incluir dentro de parametros.py alguna estructura de datos (como diccionario o lista de listas, o una combinación de ambas) que incluya parámetros ya declarados previamente en el archivo. A modo de poder llamar ciertos elementos de forma mas eficiente en otras partes del código sin recurrir a demasiadas condiciones y ocupar muchas lineas de código. O en cambio, debería crear otro archivo.py que contenga este manejo previo de los parámetros.

**Comment by Maxi1805** [comment]
Hola @EnzoMorata, puedes hacer uso de las estructuras de datos que mencionaste, pero es importante que consideres ciertas cosas, como que los elementos que agrupes tengan sentido, por ejemplo crear un diccionario como ```{path: "path", numero: numero}```, donde en lugar de importar directamente el path o el numero importas el diccionario, no tendría mucho sentido el uso de los parámetros, pero si en lugar de eso quieres hacer una lista con parámetros donde tomes uno o otro según un input no habría problema.
Espero te sirva.

**Comment by EnzoMorata** [comment]
Si, muchas gracias!
