### ISSUE TITLE
Actualización de  archivos .csv

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#274]
Hola! No entiendo en que momento hay que actualizar los archivos si la información de cada instancia esta en las clases. Por ejemplo, los puntos de salud actual de una criatura los tengo que actualizar en el archivo cada vez que cambie?

**Comment by Dnpoblete** [comment]
Hola @tedroppelmann, en el enunciado aparece lo siguiente:
![image](https://user-images.githubusercontent.com/42362982/78591603-aec2ca80-7811-11ea-847b-7b89b971da4a.png)
Por lo cual se espera que el programa actualice los archivos en cada cambio que se realice, asume que si yo cortó el programa, los archivos deben estar acorde con lo que se hizo y adicionalmente, si veo los archivos en medio de la ejecución del programa, también deben estar actualizados.

Éxito con la tarea! ✨

**Comment by anamanzana** [comment]
Se considera como caso equivalente el momento que se crea un nuevo usuario con su criatura? O se puede agregar al archivo después de haber seleccionado toda la información requerida? (haber seleccionado nombre, tipo de magizoologo, criatura y nombre de criatura)

**Comment by Dnpoblete** [comment]
Hola @anamanzana, puedes asumir que se puede modificar el archivo luego se haber seleccionado toda la información.

Éxito con la tarea! 😄

**Comment by dlmed** [comment]
Hola, qué pasa si guardo datos al momento de salir del programa?

**Comment by Dnpoblete** [comment]
Hola @dlmed, se volvió a conversar con el equipo docente y se considerará que lo más correcto es guardar por cada cambio, que es lo que recomendamos, y que guardar al salir no sería la forma más completa, ya que podría haber casos en que se cae el programa y por lo tanto no se guarden los cambios, pero por ahora si será considerado como una opción válida.

Éxito con la tarea! 🧙🏻‍♀️
