### ISSUE TITLE
Manejo de labels tipo Pixmap en Layouts

### ISSUE THREAD

**Issue by DonMarto** [IIC2233/Syllabus#274]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, a pesar de que en issues anteriores se destacó que no es necesario el uso de Layouts para esta tarea, hay partes en donde me gustaría implementar su uso. Sin embargo, he tenido varios problemas en la realización de esto, en particular con la implementación de las imágenes. Al momento de instanciar las imágenes, y definirlas usando, por ejemplo, setGeometry, no tengo problemas, pero si es que inserto el label asociado a un layout, esta imagen toma el tamaño original de la foto (y dado que tienen una cantidad de pixeles muy alta, utilizan toda la pantalla), y no he sido capaz de modificar su tamaño. Intenté opciones obvias como resize() o setGeometry nuevamente, pero al estar en un layout, estas resultan sin efecto. Luego, busqué dentro de la documentación de Qt, en pyqt5 ->  layout management, para encontrarme con los stretch factor, QSizePolicy y setSizePolicy, pero no me resultó en los intentos que hice, y no logro entender realmente que hacer, y como funcionan estos códigos.

TL;DR: Al insertar una imagen en un layout, este toma su tamaño original, que es muy grande para lo que busco, y no sé cambiarlo. Ayuda

**Comment by ivanvlam** [comment]
Hola @DonMarto ! Al utilizar layouts, los labels dentro de cada uno utilizarán todo el espacio, respetando los _stretchs_. Sin embargo, existe una manera de entregarle un tamaño exacto a elementos gráficos, es decir, que no se agranden, ni se achiquen al modificar el tamaño de la ventana. Lo anterior es utilizando los métodos setFixedSize(), setFixedWidth() y setFixedHeight(). En este [link](https://doc.qt.io/qt-5/qwidget.html#setFixedSize) puedes encontrar como funcionan, además, ahí mismo se señala que sobrescriben las restricciones de tamaño de un QLayout, lo que permite entender mejor su funcionamiento. Espero te sirva.

**Comment by DonMarto** [comment]
El problema con esa solución, al menos según mis pruebas, es que el layout define la posición y luego el tamaño del widget (el cual no puede cambiar). Esto resulta en un problema ya que la posición se define para el tamaño mayor, y no queda acorde a como yo busco (queda la imagen muy arriba a la izquierda). A través del uso de más layouts y stretchs, logré dejarlo en la posición deseada, pero este método induce a mucho desorden, así que no sé si habría algún simil tipo setFixedPosition() (lo busqué y no encontre)

**Comment by ivanvlam** [comment]
Una posible solución a ese problema es utilizar una función que escale el tamaño de tu widget, como los métodos scaledToHeight() y scaledToWidth(). Puedes leer más acerca de ellos en este [link](https://doc.qt.io/qt-5/qpixmap.html#scaledToHeight). Si lo anterior no funciona, te recomendaría resolverlo como mencionaste con más _layouts_ y _stretchs_.
