### ISSUE TITLE
Gitbash murio y necesito subir mi version final todavia

### ISSUE THREAD

**Issue by Cjparra97** [IIC2233/syllabus#274]
No me deja commit mi ultima version de unos archivos que tengo, me aparece el siguiente mensaje:

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

**Comment by furcelay** [comment]
Hola!

Ese problema puede ocurrir porque tu IDE está usando git al mismo tiempo, prueba realizar el siguiente procedimiento:
Cierra tu IDE, abre un terminal en la raíz de tu repositorio y ejecuta:
```
rm -f .git/index.lock
```
Si usas el cmd en Windows debes ejecutar `del -f .git/index.lock` en vez.
Luego vueve a intentar hacer el commit, ésta vez debería funcionar, y luego ve si tu IDE tiene la sincronización con git activada en tu repositorio y desactívala.

Si no se soluciona o el problema vuelve a ocurrir vuelve a comentar en ésta issue y seguiremos con la siguiente alternativa.

Saludos!

**Comment by Cjparra97** [comment]
Muchas gracias!!
