### ISSUE TITLE
Obtener posición del mouse relativa

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#274]
Hay alguna forma de obtener la posición relativa del mouse con respecto a una ventana? Ya que pude sacar la global y la relativa a donde se realizo el click, pero las posiciones de las cosas pueden variar ya que puedo mover la ventana.

**Comment by Polea012** [comment]
Hola! Los eventos que entregan una posición (como lo es *mousePressEvent*) son relativos a la ventana en la que estos eventos son definidos. 

Esto quiere decir que si tu defines una ventana de la siguiente forma: 

```python
class MiVentana(QWidget):
    def __init__(self)
        super().__init__()
    
    def mousePressEvent(self, mouse_event):
       relative_pos = mouse_event.pos()
       self.pos_x = relative_pos.x()
       self.pos_y = relative_pos.y()
```
Entonces cada vez que hagas el click en **MiVentana** se guardará la posición relativa a ella. Si mueves la ventana y vuelves a hacer click, la posición será congruente a la ventana (se obtiene la posición esperada sin que le afecte el cambio de la ventana). Esto es porque en cada QWidget tiene un *mousePressEvent*, de manera que la acción del evento dependerá de la definición que se declara en el QWidget. 

Saludos y ojalá te sea de ayuda!
