### ISSUE TITLE
Problema con el uso de .gitignore 🐧 

### ISSUE THREAD

**Issue by Bizonte28** [IIC2233/syllabus#274]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

**Duda**
Hola, mi problema va dirigida al uso de .gitignore. Tengo problemas al momento de intentar subir archivos como mi main.py a mi repositorio personal, ya que gitBash dice que está en el .gitignore, pero en el .gitignore solo tengo archivos del formato .csv. Sé que me identifica el archivo "main.py" en el .gitignore porque cuando ejecuto "git add main.py" el git bash me tira la línea 
"The following paths are ignored by one of your .gitignore files:
Tareas/T1/main.py"

**Comment by sperezmasri** [comment]
Hola @Bizonte28! Revisé tu repositorio y creo que lo que te puede estar generando problemas es el ```.gitignore``` que tienes al principio del repositorio (el que fue agregado/actualizado en el commit "Actividad Sumativa 🐯". En ese ```.gitignore``` está ```main.py``` y probablemente eso sea el problema en este caso. 

Avisame si se soluciona el problema modificando o eliminando ese ```.gitignore``` del principio. Quedo atento, saludos! :smile:

**Comment by Bizonte28** [comment]
Muchas gracias! ya me funcionó 🐧
