### ISSUE TITLE
[entrega final] 7.1.2. Conexión: Argumentos por consola

### ISSUE THREAD

**Issue by MystEdu** [IIC2233/Syllabus#274]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas, cuando nos entregan el puerto a conectar por consola, **¿podemos asegurar que ingresarán solo 1 argumento (puerto)?¿o podrían probar entregando más argumentos y nosotros usar el correcto?**

De antemano, muchas gracias

**Comment by gasparbenavente2** [comment]
Hola! El argumento de consola debe contener solamente un puerto, el que se debería encontrar en el archivo JSON de la carpeta del cliente

**Comment by dvillas28** [comment]
No me queda claro, en la revision de la tarea, se consultara ese archivo .json para saber cual es el port a usar como argumento por consola?

**Comment by MystEdu** [comment]
Tampoco me queda claro, ya que en el enunciado se indica que en el archivo .json se encuentra el host y no dice que el puerto se obtiene del archivo .json, sino que de consola.
![Screenshot_20231018_115140_Chrome](https://github.com/IIC2233/Syllabus/assets/130402592/f2e44414-f66c-4d52-8154-e50d5169e799)

**Comment by AntonioVenegas** [comment]
Hola!, el numero de puerto se debe rescatar del argumento entregado en la consola (un solo número), por lo que no debería estar en el archivo json de parametros.
Saludos :)
