### ISSUE TITLE
Duda sobre formato de entrega del input inicial

### ISSUE THREAD

**Issue by mVal919** [IIC2233/Syllabus#274]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, muy buenas noches.
Me entró una duda por la forma en la que está escrita una cosa sobre el input inicial. ¿Podemos asumir que siempre se recibirá el input inicial de manera correcta? Es decir, que despues del py o python3, y el main.py, irá el nombre del predio, y luego la dificultad?
Mi confusión surge porque en la página 4, dice que se entregará el input de la forma “python3.11 main.py nombre_jardin nombre_dificultad”, pero en el inciso 2 de la misma página, dice “python3.11 main.py dificil”. 
Eso, muchas gracias!

**Comment by CrisDonosoMaass** [comment]
Hola! Pueden asumir que el input por consola siempre estará en orden como main.py-nombre-dificultad. Sigue la forma “python3.11 main.py nombre_jardin nombre_dificultad”, la forma del inciso daría error por no especificar el jardín, gracias por mencionarlo!

**Comment by mVal919** [comment]
Hola
Gracias! Igual encontré una forma de que haga un print si pones algo incorrecto. Lo voy a dejar asi de todos modos por si acaso.

**Comment by CrisDonosoMaass** [comment]
Buenísimo! Menciónalo de todas formas en el README para que los correctores no malinterpreten tu solución como incorrecta.
