### ISSUE TITLE
[Diagrama de clases] Atributos con más de un tipo y atributos de clases

### ISSUE THREAD

**Issue by burgosibarra** [IIC2233/syllabus#274]
Mi consulta es como hay que escribir en el diagrama de clases un atributo de una clase que puede variar en el tiempo (partir en None y luego ser una tupla)

No se si el nombre atributos de clases esta bien pero quería saber como ilustrar esta situación
`class A():`
....`atributo_de_clase = tuple()`
....`def __init__(self):`
........`self.nombre = "algo"`
(los "." son identaciones no sabia como hacerlos):)

**Comment by RositaMunoz** [comment]
Hola!
Si el atributo solo cambia de None a tupla, entonces déjalo como tupla en tu diagrama. Ahora si tu atributo varía más que lo anterior mencionado, hay problemas en la modelación de tu clase. 
Espero haber respondido tu duda. 
Ánimo con lo que queda de la tarea!
