### ISSUE TITLE
Límite ciudades

### ISSUE THREAD

**Issue by Fhguinez** [IIC2233/Syllabus#274]
En caso de encontrarme con la siguiente combinación de piezas, estoy ante dos ciudades que se separan en el vértice? o debo considerarlo una sola ciudad?
![limiteciudades](https://user-images.githubusercontent.com/26127246/30250349-103ea03c-9623-11e7-94fd-fa3c18e8c317.png)

**Comment by sebacruzd** [comment]
Hola,
Como existe posibilidad de unir una pieza más para completar esta extraña ciudad, debe ser considerado como **una sola ciudad.**

_Tip_: El algoritmo que crees para detectar ciudades debería hacerlo sin que lo pienses realmente.

**Comment by Fhguinez** [comment]
¿Pero los bordes de arriba no conformarían una ciudad completa? Mi pregunta nace de lo explicado en la issue  #249, donde se muestran piezas con 2 lados Ciudad que no necesariamente están conectados entre si.
![limiteciudades](https://user-images.githubusercontent.com/26127246/30250815-5df7e808-962b-11e7-947a-a6963d8bd75d.png)

**Comment by sebacruzd** [comment]
No es completa, ya que aún hay una C que no está cerrada. Tiene una posible conexión con otra pieza C.
Guíate por las letras más que el dibujo (se podría asumir que esos dos bordes que chocan en una pieza en verdad es un borde continuo), sé que se ve feo y raro pero no por eso son ciudades distintas.
Mientras hayan piezas conectadas entre ellas y una de ellas tenga una C sin "cerrar", la ciudad no está completa y es solo una.

**Comment by MarceloSaldias** [comment]
Que pasaría si el único borde libre esta en el borde de la grilla? Como si en el ejemplo anterior el único borde "C" sin conectar estuviera en un borde.
Ahi la ciudad se cuenta como completada (porque no se pueden conectar más), o  queda como incompleta?

**Comment by MarceloSaldias** [comment]
up? ;-;

**Comment by fnquinteros** [comment]
@MarceloSaldias estaría completa en ese caso. Saludos!
