### ISSUE TITLE
Duda acerca de la clase Item Tarea 2

### ISSUE THREAD

**Issue by VicenteDubo** [IIC2233/Syllabus#274]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda acerca de un aspecto de la Clase Item que no me quedo claro con solo el enunciado, ¿Se supone que debería crear 3 clases distintas que herede de una clase madre para representar cada item? ¿O debería crear una clase que represente a uno de los 3 items según un parametro recibido? ¿O el enunciado me da libertad para hacerlo como estime conveniente?

**Comment by diegoftpxd** [comment]
Hola @VicenteDubo , En el enunciado dice que debes crear una clase item, no especifíca si esta debe tener clases hijas o no. Por esto es que el modelamiento pasa a estar a tu criterio. Pese a esto es recomendable hacer uso de herencia para modelar mejor los comportamientos.
