### ISSUE TITLE
Duda PEP8, largo de líneas 

### ISSUE THREAD

**Issue by pwillmer** [IIC2233/syllabus#275]
Hola! No exceder los 100 carácteres por fila hace referencia netamente a lo que codificamos independiente de los espacios de las primeras columnas? o hace referencia a que solo podemos escribir hasta la columna 100.

Gracias

**Comment by gatochico** [comment]
Hola! Los 100 carácteres se cuentan desde la columna 0. O sea, sin importar cuantas indentaciones tengas, **si alguna línea se excede de la columna 100**, habrá descuento :(
Saludos y éxito!!
