### ISSUE TITLE
Modelación circular

### ISSUE THREAD

**Issue by jearaneda** [IIC2233/syllabus#275]
Un concepto de la clase de hoy no me permite diferir lo que se considera modelación circular de lo que no. En las slides se aclara que la interacción entre el frontend y el backend debe ser en ambas vías, lo que -según entiendo- implica esto:

-Tengo en mi backend.py la clase Backend con la señal move_signal, que entrega la posición a la que se mueve un personaje. 

-Tengo en mi frontend.py la clase Juego que obviamente incluye keyPressEvent. **Este es el problema:**

Para la interacción yo importo en mi frontend.py el módulo backend y lo instancio. Así, puedo meterme en la clase Juego, y ponerle un backend.move_signal.connect(move). move(self,pos) es una función que recibe posición (pos) y mueve el sprite en la UI.

Ahora, cuando el backend me envíe una posición nueva, puedo recogerla con mi función move y moverla. El tema es: ya estoy enchufado a "Juego front-end recibiendo de back-end". **¿Cómo activo entonces a backend?** 

Lo que yo tenía hecho es llamar de forma directa el método del backend desde el keyPress event del front, digamos así (pseudocódigo para hacerlo corto):

```

(backend.py) - move_control:
if(condiciones se cumplen):
    move_signal.emit(nueva_posicion)


(frontend.py) keyPressEvent:
   backend.move_control()

```
 
Esto funciona porque yo llamo a la función _back_ move_control, esto desde el _front_. Luego, si move_control logra encontrar nueva posición, emite una señal que el front recibe y ya está.

Pero según entendí en la clase y actividad formativa de hoy, lo que hay que hacer es emitir señales en ambos lados. Pero le he dado varias vueltas durante la tarde-noche y no logro encontrar una forma de hacer esto sin que sea circular (y, de hecho, provocando varios errores en el camino).

Lo que entiendo es que tengo que importar el módulo frontend desde el back como un paralelo a lo anterior, y emitir una señal desde el frontend cada vez que keyPressEvent se ejecuta. 

El tema es que entiendo que esto es modelar de manera circular, pues para traer las funciones del front -como sus señales-, necesito instanciar las clases, y se produce el problema de "quien vino primero, el huevo o la gallina", pues estaríamos comenzando de nuevo el juego a cada rato.

Resumiendo: ¿cómo hago para emitir señales en ambos lados, como se pide en la distribución de puntajes, sin caer en una modelación circular?

**Comment by Polea012** [comment]
Hola! Tu duda va entonces enfocada a la lógica de conectar el *backend* con el *frontend*. Para ver el caso de conexión por señales, recordemos algunas cosas:

* En general, las señales solo se deberían conectar una vez al instanciar cada clase.
* Al conectar la señal, se le debe indicar cuál es la función que se debe ejecutar al hacer `emit`. Es importante recalcar que la función no tiene por qué ser un método de la clase de la señal.
* El tipo de parámetro que recibirá la función conectada se puede definir cuando uno instancia la señal. El tipo del parámetro puede ser `int`, `dict`, `list`, una clase creada por nosotros, etc.

Ahora, volviendo a tu duda: ¿Como conecto dos clases con señales? 

Efectivamente, podemos importar el *backend* e instanciarlo dentro del *frontend* para conectar la señal, pero tal como dices, eso es solo conexión "por un lado".

Con este ejemplo podrás ver la acción de una señal simple que se encarga de imprimir la posición donde se hizo click en una ventana. Aquí la señal está en el *frontend*),:

```python
class Controlador:
    def __init__(self):
        # Estamos creando una clase que conectaremos al frontend
        pass 

    def imprimir(self, mensaje_recibido):
         # Desempaquetamos el mensaje
         x = mensaje_recibido["pos_x"] 
         y = mensaje_recibido["pos_y"]
         # Imprimimos la información
         print("posicion x es {}".format(x))
         print("posicion y es {}".format(y))

class MiVentana(QWidget):
    signal_frontend = pyqtSignal(dict) # La señal enviará un diccionario en este caso
    def __init__(self):
        super().__init__()
        self.backend = Controlador() # Instanciamos el backend como parámetro
        self.signal_frontend.connect(self.backend.imprimir) # Conectamos la señal al metodo del backend
    
   # Captamos el evento del click
   def mousePressEvent(self, event):
        mensaje = {"pos_x" : event.pos().x(), "pos_y": event.pos().y()} # creamos el diccionario
        self.signal_frontend.emit(mensaje) # emitimos la señal 
```
Pero al instanciar a la clase del *backend* aquí, notemos que el objeto de `MiVentana` puede ahora utilizar el objeto  `Controlador` ya que es un parámetro instanciado con accesos a métodos y atributos. La señal es un atributo de clase y la podemos recuperar desde una instancia. De esta manera podemos hacer las conexiones del *backend* sin tener que crear otra ventana, evitando así los errores de loop en modelación circular

Aquí va una muestra de la conexión en un código simple:

```python

# Aquí muestro solo la parte de la conexión
# Indicamos que es QObject para que pueda usar señales
class Controlador(QObject):
    signal_backend = pyqtSignal() # defino una señal para la clase.
    def __init__(self):
        super().__init__()

class MiVentana(QWidget):
    def __init__(self):
        super().__init__()
        self.backend = Controlador() # Instanciamos el backend. Ahora podemos usar sus métodos y atributos.
        self.backend.signal_backend.connect(self.imprimir) # conectamos la señal del backend a alguna función del frontend
    
    def imprimir(self):
        print("Este mensaje se imprime después de emitir  la señal")
```
Esta es una forma de relacionar dos objetos sin errores de circulación puesto que no estamos creando de nuevo la ventana, sino que estamos utilizando el atributo (la señal) de un objeto ya instanciado (`Controlador`) para hacer la conexión. Además, al objeto `Controlador` no se le ha entregado la interfaz y en ninguna parte podemos llamar al `MiVentana` desde `Controlador` si no es por una señal.

Ahora veamos un ejemplo con eventos. Parecido a tu ejemplo, vemos como se procesa un movimiento a la posición donde uno hizo click con el mouse. El movimiento pasa por una verificación del *backend*:

```python
class Controlador(QObject): 
    signal_backend = pyqtSignal(dict) # La señal envía un diccionario
    def __init__(self):
        super().__init__()
        
    def comprobar_movimiento(self, mensaje_recibido):
        # Se entra a esta función si el frontend envió una señal
        # Hacemos las validaciones
        self.signal_backend.emit(mensaje_recibido) # Emitimos la señal. Aprovechamos de enviar el mismo diccionario con las posiciones.

class MiVentana(QWidget):
    signal_frontend = pyqtSignal(dict) 
    def __init__(self):
        super().__init__()
        self.backend = Controlador()
        self.signal_frontend.connect(self.backend.comprobar_movimiento) 
        self.backend.signal_backend.connect(self.mover_aqui)
    
   def mover_aqui(self, mensaje_pos):
        # Se entra a esta función si el backend envió una señal
        # Se procesa el movimiento...
    
   def mousePressEvent(self, event):
        mensaje = {"pos_x" : event.pos().x(), "pos_y": event.pos().y()} # creamos el diccionario
        self.signal_frontend.emit(mensaje) # emitimos la señal 
```

Para recapitular todo lo hablado:
* El uso de señales se basa en las funciones que uno conecta y si requiere parámetros.
* Basta con realizar todos los `connect` necesarios al inicializar la interfaz para hacer la relación *backend* - *frontend*.
* No necesitamos hacer una doble importación o doble instanciación para poder conectar señales porque caeríamos en errores de modelación circular.
* Esta forma mostrada no necesariamente es la única. Sólo es un caso en el que se muestra como las clases se pueden relacionar.

Mi recomendación es seguir averiguando sobre el manejo de señales porque son muy útiles para los propósitos de la tarea. 

Mucho éxito y saludos.

**Comment by emena97** [comment]
Si tengo una Clase1, que recibe como parametro a Clase2, y luego en algun metodo de Clase2 instancio Clase1, es considerado modelacion circular?
Por ej, si Clase1 es mi personaje y Clase2 mi juego, entonces el personaje recibe a juego en su init, ya que pertenece a el, y luego en algun metodo de mi juego yo instancio al personaje.

**Comment by Hernan4444** [comment]
Hola,

Si, es modelación circular, porque como dices `Clase 1` recibe una isntancia de `Clase 2` y `Clase 2` crea la instancia de `Clase 1`, por lo tanto desde `Clase 1` se puede acceder a `Clase 2` y desde la `Clase 2` se puede acceder a la `Clase 1`. 

Lo óptimo es que tu clase Juego cree a la Clase Personaje, pero le entregue las cosas que necesita nomás (atributos tal vez) o que la clase juego conecte las señales del personaje, pero que personaje no reciba a la instancia de su creador.

Saludos :v:

**Comment by furzuadr** [comment]
@Hernan4444 Estaría bien que mi padre guarde al hijo, y al crearlo mande la instancia del padre, pero a su vez en el init del hijo, no instanciar el padre sino hacer todas las señales que lo comuniquen? Gracias!

**Comment by Hernan4444** [comment]
No, eso no está bien porque de todos modos el hijo le llega la información completa de su padre.

Si quieres conectar las señales, el padre puede hacerlo tal como está en el código de ejemplo puesto por Pablo Olea. (`MiVentana` es el padre y `Controlador` es el hijo)
 
```python
# Aquí muestro solo la parte de la conexión
# Indicamos que es QObject para que pueda usar señales
class Controlador(QObject):
    signal_backend = pyqtSignal() # defino una señal para la clase.
    def __init__(self):
        super().__init__()

class MiVentana(QWidget):
    def __init__(self):
        super().__init__()
        self.backend = Controlador() # Instanciamos el backend. Ahora podemos usar sus métodos y atributos.
        self.backend.signal_backend.connect(self.imprimir) # conectamos la señal del backend a alguna función del frontend
    
    def imprimir(self):
        print("Este mensaje se imprime después de emitir  la señal")

```

Saludos :v:

**Comment by furzuadr** [comment]
Muchas gracias, me queda clarísimo! Entonces la ayudantía del semestre pasado de Mario es considerada modelación circular cierto? Gracias!

**Comment by Hernan4444** [comment]
Precisamente,

Para cumplir con el requisito de no hacer modelación circular, la conexión de las señales las debió haber hecho el Frontend de modo de no entregar el `self` al Backend. Gracias por notarlo, así podemos mejorar esa ayudantía para los siguientes semestres 👍

**Comment by mjgarrido1** [comment]
Hola! la solucion subida de la AC07 cumple con el requisito de no ser modelacion circular? como que realiza una equivalencia de senales

**Comment by furzuadr** [comment]
@Hernan4444 Considerando que la ayudantía en la que muchos se basaron para realizar la tarea trabajaba con modelación circular y muchos no lo teníamos claro hasta revisar esta issue, no es posible que para esta tarea no se penalice este tipo de mala práctica? Y para la actividad siguiente y tarea sea penalizado de forma estricta? Estuve mucho rato cambiando mi código para eliminar la modelación circular y es prácticamente inviable considerado el avance actual, además de que se extendería muchísimo en líneas si es que no se cambian las formas de relacionar. De antemano muchas gracias!

**Comment by pmolinaj** [comment]
Duda particular:
Tengo 3 clases, digamos que clase A, clase B y clase C. La clase A es instanciada dentro de la clase C, y la clase B también es instanciada dentro de la clase C. La clase A tiene una señal A, la clase B tiene una señal B, y la clase C, una señal C. La relacion entre las señales es la siguiente:
*Considerando que la clase C tiene instanciadas a las otras 2 clases en su interior
1- La señal A es emitida
2- El connect de la señal A y el slot de esta señal están en la clase C
3- Dentro del slot de la señal A (Que está en la clase C) se emite la señal C
4-El connect de la clase C y el slot de esta señal están el la clase B
5- Dentro del slot de la señal C (Que está en la clase B) se emite la señal B
6- El connect de la señal B  y el slot de esta señal están en la clase C
7- Dentro del slot de la señal B (Que está en la clase C) se realiza una funcion X

Perdon por el enredo, pero quiero saber si es que esto cuenta como modelación circular
De antemano gracias

**Comment by bimartinez** [comment]
Hola @pmolinaj

Podrías subir el código a tu repositorio e indicarnos cuáles son tus clases A, B y C para poder ver con mayor claridad lo que nos dices y darte una respuesta mas concreta :smile:

Saludos!

**Comment by Hernan4444** [comment]
Hola

@mjgarrido1 si cumple, porque no existe una clase padre que guarda referencia al hijo, en el main las 3 ventanas son creadas de forma independiente y luego se conectan sus señales, pero no sucede el hecho que la clase hija pueda acceder al padre porque no existe el padre.

@furzuadr lamento informar que no es posible aceptar esa solicitud. Si algo no está claro, se usan las issues. En descuento.md se indica que ante dudas de la modelación circular, que hagan una issue y por otro lado, si van a usar código externo que no fue entregado por nosotros este semestre, deben verificar que cumpla con las condiciones impuestas este semestre.

Saludos :v:
