### ISSUE TITLE
Duda velocidad lobo

### ISSUE THREAD

**Issue by mon-b** [IIC2233/Syllabus#275]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, mi duda es sobre la velocidad del lobo que aparece en el enunciado y en el archivo de parámetros.

Para la velocidad del conejo y la velocidad de las zanahorias de los cañones, se indica que tras aplicar una fórmula, la velocidad resultante está en “segundos por casilla” (los segundos que toma pasar a otra casilla). Para la velocidad del lobo igualmente se utiliza una fórmula (multiplicar por el ponderador del laberinto), pero no me quedó claro si el resultado de esta multiplicación también está en “segundos por casilla” ya que esto no se especifica en el enunciado.

Muchas gracias

**Comment by Curi2164** [comment]
Hola, siguiendo con la lógica que se comentó antes, entonces el lobo en el primer nivel se debe mover cada 4,5 segundos por casilla? siento que en pantalla se ve demasiado lento y no se alcanza a apreciar la "continuidad del movimiento", o eso da lo mismo y solo se deben mover cada 4,5 segundos por casilla?
