### ISSUE TITLE
Calculo de la afinidad de equipo 

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#275]
Hola no me queda claro cual es el criterio para elegir el calculo de afinidad  de cada jugador en un equipo, ya que segun lo que muestra en la Figura 4 el calculo se hace entre ciertos jugadores y no entre todos , pero se supone que yo podria calcularla entre cualquiera, dado que el grafo es conexo ( segun lo que se publico en otras issues).

**Comment by llloyola** [comment]
Por lo que yo tengo entendido, la afinidad de un jugador (en un equipo) es el promedio de su afinidad con los jugadores "vecinos". Por ejemplo, en la Figura 4, la afinidad del portero sería (0.93 + 0.12)/2.

Pd: Los jugadores vecinos son los que están conectados por la línea roja.

**Comment by ignaciohermosillacornejo** [comment]
Hola @sjkinast 
Ambas cosas que dices son correctas, sin embargo las estas confundiendo. Para calcular la afinidad de un equipo debes calcular el promedio de afinidad de un jugador con sus vecinos. 
En el ejemplo que @llloyola menciona, la afinidad del portero seria (0.93 + 0.12)/2, pero ¿De donde sale ese 0.93 y ese 0.12? Eso es lo que tienes que calcular "entre todos" para ponerlo en tus palabras. 
Resumiendo
1.- Calculas la afinidad de un jugador con sus vecinos y lo promedias
2.- La afinidad entre los jugadores y sus vecinos es el que se calcula con el grafo "de todos" que detallamos en la sección 4.1.1

**Comment by ignaciohermosillacornejo** [comment]
Hola @sjkinast
Ambas cosas que dices son correctas, sin embargo las estas confundiendo. Para calcular la afinidad de un equipo debes calcular el promedio de afinidad de un jugador con sus vecinos.
En el ejemplo que @llloyola menciona, la afinidad del portero seria (0.93 + 0.12)/2, pero ¿De donde sale ese 0.93 y ese 0.12? Eso es lo que tienes que calcular "entre todos" para ponerlo en tus palabras.
Resumiendo
1.- Calculas la afinidad de un jugador con sus vecinos y lo promedias
2.- La afinidad entre los jugadores y sus vecinos es el que se calcula con el grafo "de todos" que detallamos en la sección 4.1.1

**Comment by ignaciohermosillacornejo** [comment]
Hola @santilaguna, cuando @llloyola se referia a vecinos, yo pienso a que se refería a lo segundo que mencionas tum es decur los que se ven conectados en la pantalla. 
Sobre tu segunda pregunta, no existe un metodo directo de la GUI para obtener los jugadores pero sin embargo, es posible obtenerlo debido al orden en que se seleccionan los jugadores.

**Comment by 96jaime** [comment]
en la parte 4.3.1 se dice expresamente que la posiciones dentro del equipo son irrelevantes para calcular la ezperanza, por tanto a que vecinos se refiere???

**Comment by Hernan4444** [comment]
@96jaime esa frase hace referencia a que no hay posiciones como defensa, medio campo, etc. que afecten el calculo de esperanza, pero la posición en el grafo si importa para determinar los vecinos según la imagen.

Saludos ✌️
