### ISSUE TITLE
El juego se cierra al pasar unos 50 segundos, problema thread y timer

### ISSUE THREAD

**Issue by rutercrack** [IIC2233/Syllabus#275]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Ayer me enteré de que mi código tiene un problema importante, se cierra después de unos segundos. Para ver si me pueden ayudar a ubicar el problema, tengo que explicar que mis autos y troncos, son threads, y en el frontend, creé un timer para que creara y ejecutara estas threads cada cierto tiempo.
de la forma que (con un auto) el código de lo que repite el timer se vería así:

self.auto1 = Auto()
self.auto.actualizar.connect(self.actualizar_label)
self.auto.start()

El código hace esto perfectamente al principio, pero después de un tiempo ( noté que si hago que el timer sea mas corto dura menos aún) el juego se crashea. 
También pensé que podría tratarse de que no se borraban los labels, y por lo tanto el código acumulaba labels infinitos en los lados, pero dentro de los threads tengo definido que cuando se termine el mismo, haga clear a su label con self.label.clear(). 
Al final no se que esta pasando ni porqué se cae el código.

**Comment by Maxi1805** [comment]
Hola @rutercrack, por lo que dices se me ocurren un par de cosas, primero los autos y troncos son threads o Qthreads, ya que por el funcionamiento de PyQt se generan problemas con el uso de threads normales. En segundo lugar el método clear en realidad solo limpia el contenido de la label, más no la label en sí misma, para eso es necesario usar otros métodos, como deleteLater, sin embargo a no ser que estés creando una gran cantidad de labels no sé que tanto pueda ser ese el problema. Yo en tu caso, cambiaria el método para ver si ayuda en algo, luego si es que los threads resultan ser Qthreads, revisaría si estos se están terminando correctamente y no siguen corriendo con algun método como isRunning().

Espero que te sirva.
