### ISSUE TITLE
Puntajes de caminos, rios y ciudades incompletas

### ISSUE THREAD

**Issue by MrEarle** [IIC2233/Syllabus#275]
Un camino, ciudad o rio incompleto tiene piezas pertenecientes a ambos jugadores. Como es el calculo de puntaje en ese caso? Se da puntaje a cada uno según su pieza?

**Comment by cilopez** [comment]
En el de la ciudad se dan 10 puntos por pieza de cada jugador , el camino y el río no tienen puntaje asociado si están incompletos, por lo que no aplica tu duda.

**Comment by MrEarle** [comment]
![image](https://user-images.githubusercontent.com/30664457/30251951-42cf3d50-9640-11e7-8b59-8f6360a0b881.png)
Pero en este caso hay un rio que conecta una ciudad con el borde de la grilla, pero esta incompleto.
Segun el enunciado:
> 25 puntos si el rio conecta una ciudad con el borde de la grilla
No dice nada de que tiene que estar completo

**Comment by cilopez** [comment]
@MrEarle  Puedes considerar tres casos, que ese **río como no está completo** y no se le asignan puntos o que se le asignen 25 puntos al jugador que puso la **última ficha** que compone el río incompleto o al que tiene **más fichas** en el río incompleto,  si implementas una de estas déjalo en tu _readme_ y referencia esta _issue_ .
