### ISSUE TITLE
Problema con los items

### ISSUE THREAD

**Issue by JSalas277** [IIC2233/Syllabus#275]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo problemas con los items, pues aun no tengo claro si es que tienen que heredar de otra clase o si es que hay que hacer algo ademas de solo "evolucionar" la clase, o sea, tabien habrian que cambiar atributos del combatiente? Esto es lo que tengo:

**Comment by diegoftpxd** [comment]
Hola @JSalas277 , recuerda que no puedes publicar código en la issus. Pese a esto, los items se encargan de evolucionar a los combatientes. Ten en cuenta que en ese caso debes instanciar un combatiente de la clase evolucionada y por tanto debes agregar los atributo del nuevo combatiente. (Por ejemplo un Paladin tiene probabilidad paladín como atributo)

**Comment by constanzavicencio** [comment]
> Hola @JSalas277 , recuerda que no puedes publicar código en la issus. Pese a esto, los items se encargan de evolucionar a los combatientes. Ten en cuenta que en ese caso debes instanciar un combatiente de la clase evolucionada y por tanto debes agregar los atributo del nuevo combatiente. (Por ejemplo un Paladin tiene probabilidad paladín como atributo)

Una pregunta, cuando se evoluciona a un Combatiente, su vida se restaura (o disminuye) a la vida máxima propia de la clase evolucionada? Porque si no se hace eso puede que, si se mantiene la vida actual, la vida actual supere la vida máxima propia de la clase evolucionada. Pregunto porque como no está especificado en el enunciado me surgió la duda

**Comment by diegoftpxd** [comment]
Hola @constanzavicencio , esta duda ya fue respondida en la issu #238. Pero en resumen, ya que no queda especificado en el enunciado son libres de tomar la desición que quieran siempre que no transgreda el enunciado. Independiente de la desición que tomes, recuerda dejarlo explícito en le readme
