### ISSUE TITLE
Días transcurridos

### ISSUE THREAD

**Issue by drosselot** [IIC2233/syllabus#275]
Cuando quiero que transcurra un día, solo transcurre en el "mundo" del magizoologo que está cargado?

**Comment by JosefaPaz** [comment]
¡Hola @drosselot!

Sí, cuando transcurre un día este solo cambiará para el Magizoólogo que tiene iniciada la sesión, por lo que la información de los otros Magizoólogos no debería verse modificada. 🦄 

¡Éxito!
