### ISSUE TITLE
Coordenadas de columnas

### ISSUE THREAD

**Issue by mtaguero** [IIC2233/syllabus#275]
Hola! Llevo horas intentado corregir mi código, pero no entiendo lo que pasa.
(Contexto: Asignar barcos a coordenadas random)
Intento hacer lo siguiente:

`columna = random.randint(0, variable)`

y luego al cambiar un elemento de mi lista con la coordenada de columna:

`lista[columna][fila] = "B"`

no toma mi valor columna y hace que todas las columnas en la posición fila tengan una "B", cuando se supone que solo una columna debería cambiar. Es como si el valor columna valiera n valores diferentes, pero al imprimir la variable columna sale solo un número. 
Al copiar mi código en otra página y cambiar las variables, no hay problema. El problema es cuando lo ejecuto en mi otra pestaña, pero es el mismo código, entonces no entiendo.

Ejemplo de visualización:

En vez de imprimir esto:

[[' ', ' ', ' '], ['B', ' ', ' '], [' ', ' ', ' ']],

imprime esto:

[['B', ' ', ' '], ['B', ' ', ' '], ['B', ' ', ' ']]

¡AYUDA! xd

**Comment by Tsbalart** [comment]
Hola @mtaguero!
Creo que el error esta en la creación del mapa, de alguna forma el código esta asumiendo que todas tus filas son iguales, por lo que tal vez, al crear el mapa, **estas agregando la misma filas varias veces.** Revisa eso, y si sigues sin encontrar el error, puedes hacer git push de lo que llevas hasta ahora para revisarlo directamente desde tu repo.
Saludos! Exito con la tarea!

**Comment by Tsbalart** [comment]
otra cosa, el orden debería ser:
lista[fila][columna] = "B"

**Comment by mtaguero** [comment]
> Hola @mtaguero!
> Creo que el error esta en la creación del mapa, de alguna forma el código esta asumiendo que todas tus filas son iguales, por lo que tal vez, al crear el mapa, **estas agregando la misma filas varias veces.** Revisa eso, y si sigues sin encontrar el error, puedes hacer git push de lo que llevas hasta ahora para revisarlo directamente desde tu repo.
> Saludos! Exito con la tarea!

Era esto!! Gracias!

**Comment by mtaguero** [comment]
> otra cosa, el orden debería ser:
> lista[fila][columna] = "B"

Okay, pasa que donde tenía mi código raro, como que todo estaba patas arriba jajaja y de esa forma me funcionaba antes. ¡Gracias! 😁

**Comment by Tsbalart** [comment]
De nada!!!
