### ISSUE TITLE
Expresión "Para cada dia habra" sobre algunos parámetros

### ISSUE THREAD

**Issue by constanzarojasch** [IIC2233/Syllabus#275]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Mi duda es que para la probabilidad de iniciar evento y para la probabilidad de encontrar ítems se usa la expresión que para cada dia habrá una. Esto quiere decir que cada dia cambian estas probabilidades? Gracias!

**Comment by Benjeeeh** [comment]
Hola!

La expresión refiere a que cada día (cada simulación) se debe evaluar la probabilidad de que ocurra o no un evento en base a los parámetros mencionados, pero estos no deben cambiar ya que son constantes a lo largo del juego.

Éxito con la tarea!!
