### ISSUE TITLE
Problemas con librería Currency_Converter

### ISSUE THREAD

**Issue by Giolguin** [IIC2233/syllabus#275]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, hace poco instalé la librería Currency-Converter desde consola pero saque el comando de esta página: https://pypi.org/project/PyCurrency-Converter/,  al momento de utilizarla(tal como sale en la página) me arroja el siguiente error:

**urllib.error.HTTPError: HTTP Error 404: Not Found**. 

Intenté arreglarlo instalando otras librerías como "BeautifulSoup" y "requests" pero aún me da el mismo error.

**Comment by Juampisaez** [comment]
Hola @Giolguin 
Y si pruebas con el [link ](https://pypi.org/project/CurrencyConverter/) del enunciado, tampoco se instala correctamente?
Me tinca que estas instalando otra libreria.

Avisame si se soluciona :)

**Comment by Giolguin** [comment]
Ahora sí! Con esa me funcionó, no me había percatado que estaba en el enunciado.
Muchas gracias!
