### ISSUE TITLE
Commit entrega avance T1

### ISSUE THREAD

**Issue by mjsifri** [IIC2233/syllabus#276]
Hola, me pasó que después de hacer commit del avance de la tarea, borré un archivo desde git y me aparece que ese es el último commit (cuando borre algo que no quería entregar). Ese commit también tiene los últimos archivos actualizados que alcancé a subir antes de borrar lo otro? O debo pedir que me revisen el commit anterior?
Saludos

**Comment by Emiliax16** [comment]
Hola! efectivamente tu último commit contiene el `delete` del diagrama, aunque en tu repositorio está tu readme y diagrama actualizado. Avisa que se revise tu commit anterior y no habrá problema!

**Comment by Rerro-r** [comment]
Hola! Si tanto la explicación del diagrama como el diagrama fueron subidos en distintos commits ¿puedo asumir que se revisará el estado actual del repositorio en ese último commit y no necesariamente el último commit? Es que mi último commit fue de un archivo `*.py` dentro del plazo de entrega del avance. El avance lo tenía subido de antes y como dos commits distintos.

**Comment by Emiliax16** [comment]
Hola! tranquilo que se revisa todo lo de tu repositorio en tu último commit, no sólo lo que subiste en el mismo!!
