### ISSUE TITLE
Dudas Campeonato

### ISSUE THREAD

**Issue by sicorrecto** [IIC2233/Syllabus#276]
Para simular un campeonato en la GUI debo darle 200 jugadores y 16 equipos.

1.1 Estos equipos en realidad no tienen jugadores, cierto? (Solo le paso el nombre y la esperanza a  la GUI)
1.2 Entonces, estos equipos son inventados y la esperanza de estos equipos deberia ser random? (o debo usar equipos reales y calcular sus esperanzas)
1.3 Entonces, los 200 jugadores son para armar el equipo del usuario? 
1.4 Si mi equipo es el unico con jugadores, tambien es el unico que puede hacer faltas, cierto?

2. Las tarjetas amarillas y rojas no afectan en nada al partido ni al campeonato?
3. Cuando me hablan de guardar los eventos de cada partido y el campeonato en general (resultados, etc) se refieren a guardarlo en alguna base de datos, o a guardarlo en algun archivo (txt, csv....)

**Comment by yoavnavon** [comment]
1. El equipo tuyo y los rivales son iguales. Ambos tienen 11 jugadores, y sus esperanza de ganar se calculan de la misma manera. Es decir, para cada equipo rival, debes elegir 11 jugadores al azar, calcular las afinidades de la misma manera que para tu equipo, y jugar los partidos inculyendo las faltas. 
2. Las tarjetas no afectan en nada, son solo para fines estadísticos.
3. No es necesario que quede en un archivo, sino que por consola o con la gui, puedas desplegar todas las estadisticas. Cuando termine tu programa está información se perderá.
