### ISSUE TITLE
Robustez

### ISSUE THREAD

**Issue by rominaarancibia** [IIC2233/Syllabus#276]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Al momento de pregunta si esta implementada robustez exactamente a que se refieren? no lo encuentro en el enunciado. Gracias

**Comment by Benjeeeh** [comment]
Hola!
Robustez se refiere a que el programa esté diseñado para manejar diversos errores que puedan surgir durante la ejecución de esta y no se caiga, por ejemplo con manejo de inputs inesperados, o manejo correcto de la información (que se espere un int y el programa arroje un str y se caiga). En resumen, es controlar las diversas fuentes de errores que se puedan generar en la implementación de lo que se pide y tu programa lo aguante.

Éxito con la tarea!!
