### ISSUE TITLE
Duda ataque, resistencia / evento zombies

### ISSUE THREAD

**Issue by xperseosses** [IIC2233/Syllabus#276]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

¿Qué es ataque y resistencia?

<img width="850" alt="Captura de pantalla 2024-09-06 a la(s) 11 28 25 p  m" src="https://github.com/user-attachments/assets/67a62d39-f789-499a-bbfc-d533a5f53690">

**Comment by CrisDonosoMaass** [comment]
Hola! La resistencia es un atributo de las plantas que las protegen de los zombies: "Resistencia: Corresponde a un int entre 0 y 40 que representa la resistencia de la planta a los
 ataques de zombies." El ataque es un valor que deben crear ustedes, considerando que es la vida que le quitaría a una planta si esta no tuviera resistencia. Debido a esto es importante que este en un intervalo razonable para que, por ejemplo, no maten siempre a las plantas de un golpe.

**Comment by xperseosses** [comment]
ataque debe ser un parametro???

**Comment by CrisDonosoMaass** [comment]
> ataque debe ser un parametro???

Dado que es constante, sí deben considerarlo como uno.
