### ISSUE TITLE
Duda plantilla readme

### ISSUE THREAD

**Issue by CataLebe** [IIC2233/Syllabus#276]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, tengo dos dudas, primero en la plantilla del readme se menciona "El módulo principal de la tarea a ejecutar es  ```main.py```. Además se debe crear los siguientes archivos y directorios adicionales:"
**¿A qué se refiere con loa nuevos archivos que se deben crear?** Porque en teoría todos los otros archivos que se necesitan serán subidos al mi repositorio, como ventana_juego.py o logica_juego.py. 
Como segundo quisiera preguntar **¿Cuáles son específicamente los requisitos que debe cumplir un buen readme para obtener el des-descuento ?**

Gracias !

**Comment by tamyhan** [comment]
Hola @CataLebe ! Con respecto a tu primera duda, los archivos y directorios que debes mencionar son todos los que sean necesarios para una correcta ejecución de tu código, por ejemplo, los archivos .ui, los sprites, y en que directorio (carpeta) debe estar cada uno. Además, los archivos .py que subas a tu repositorio también debes mencionarlos pero en la sección de librerías propias. 
Respondiendo a tu segunda duda, los requisitos que debe cumplir un buen README, es básicamente que se especifique TODO lo que sea necesario para una correcta ejecución del código y para facilitar la corrección de la tarea. Primero que nada, debes mencionar qué partes de la tarea lograste implementar y qué partes no (explicando que fue lo que faltó). Además, debes incluir los archivos necesarios, los módulos creados, las carpetas en las que debe estar cada archivo para la correcta ejecución del código, y mencionar todo lo que hayas supuesto o considerado que no estaba mencionado en el enunciado, pero que sí tomaste en cuenta para la implementación de tu código. Por último, el README tiene que incluir todas las referencias de código externo que hayas usado para alguna parte del código. 
Es muy importante también que el README tenga solo información relevante para tu propio código y que no tenga partes del template que se les entrega sin haberlas adecuado a su código!!

**Comment by CataLebe** [comment]
Gracias !
