### ISSUE TITLE
Aumento de salud por Magizoólogo Híbrido

### ISSUE THREAD

**Issue by misantacruzc** [IIC2233/syllabus#276]
Hola! Cuando dice en el enunciado que los Magizoólogos Híbridos, al alimentar a una criatura aumentan los puntos de salud de la criatura en 10 puntos. Se refiere a los puntos de salud actuales o totales. Porque en los Docencio, sale que son los puntos de salud totales. Pero en este caso no sale específicado.

**Comment by moquezada** [comment]
Hola @misantacruzc,

En el enunciado se habla de que los Magizoólogos Híbridos logran que una DCCriatura __recupere__ 10 puntos de salud, por lo que realmente se hace referencia a los __puntos de salud actuales__.

Suerte en tu tarea :)
