### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by n4chin** [IIC2233/syllabus#276]
Holaa! En el README a que se refiere 'ubicación' en la parte 'Ejecución Computer'?? Siento que si pongo la ubicación en mi compu no lo podrán leer o creo que eso no es lo que están pidiendo.

**Comment by n4chin** [comment]
Tampoco entiendo que hay que decir en la parte de los supuestos y consideraciones adicionales.
De antemano gracias por la atención.

**Comment by furcelay** [comment]
Hola!
Respecto a tu primera duda, la ubicación es relativa a tu directorio `T00`, pensando en que puedes tener múltiples subdirectorios. Si llega a ser el caso de que tu programa requiera que exista algún archivo, por ejemplo `puntajes.txt` y no hay subdirectorios basta con que escribas en tu REAMDE

Además se debe crear los siguientes archivos y directorios adicionales:
1. `puntajes.txt` en `T00` 

Respecto a tu segunda pregunta, hay situaciones donde se da la libertad de interpretar cómo debe funcionar el programa, las consideraciones adicionales son para que el que corrija tu tarea pueda entender como interpretaste esa situación, o si tienes algún comentario que pueda ayudar a entender mejor por qué escogiste esa forma en particular de resolver el problema, etc.

Espero haber resuelto tus dudas,
Saludos! 😄

**Comment by n4chin** [comment]
Comprendo, muchas gracias!!!
