### ISSUE TITLE
Piezas con ciudades separadas

### ISSUE THREAD

**Issue by mesantamaria** [IIC2233/Syllabus#277]
![cgggcc](https://user-images.githubusercontent.com/17731596/30252500-f4c47756-9649-11e7-9187-0442d9b63aec.png)
Hola.
Para estas piezas se consideran 2 ciudades distintas o son parte de la misma?
Lo pregunto porque en #274 dicen que es la misma y en #216 se entiende como si fueran 2 distintas.
Me pregunto lo mismo para las piezas que tienen dos o más "C" en sus bordes. Visualmente parecen distintas, pero también hay algunas que se ven como si fueran de la misma, como la siguiente:
![cpgpcc](https://user-images.githubusercontent.com/17731596/30252559-1c16ac92-964b-11e7-89e6-2608b6f0fb88.png)

**Comment by Arcoirisky** [comment]
Todo depende de como se juegen las piezas, si comparas la de la isue #274, puedes usarla para complementar tu ciudad u otro jugador puede llegar y quitartela. Mientras que en la #216 se encuentran en extremos opuestos, así que, a menos que puedas unirlas con otras de tus piezas ciudad, puede considerarse como distintas, ya que en ese caso se cierra y se abre otra ciudad. ¿Se entiende?

**Comment by mesantamaria** [comment]
![cggcgg](https://user-images.githubusercontent.com/17731596/30252695-8bd97e9a-964d-11e7-91ea-72ee357cf86b.png)
![cgggcc](https://user-images.githubusercontent.com/17731596/30252696-8ef606b6-964d-11e7-85fa-b37535f0c8fa.png)

Eso se consideraría como una ciudad cerrada o no? (La pieza de abajo tiene un borde C sin completar, pero se ve como si fuera otra ciudad)

**Comment by cilopez** [comment]
@mesantamaria  Creo que la _issue_ #274 te puede ayudar, si no es así respondeme en esta _issue_

**Comment by mesantamaria** [comment]
@cilopez Lo que hice fue considerarla cerrada porque me guíe por como se veía la imagen. En mi programa hice casos especiales para estas piezas, pero en realidad lo lógico es que si la pieza tiene 2 'C' deberían ser ambas de la misma ciudad y no diferentes.

**Comment by cilopez** [comment]
@mesantamaria si tienes razón, debería estar cerrada, según lo que explicas  tu programa esta realizando lo correcto :+1:
