### ISSUE TITLE
Duda interacción entre 2 clases que se contienen en sus atributos

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#277]
Hola hay algún problema/descuento para la tarea si tengo a una instancia de la clase A que tiene como un atributo a una instancia de la clase B y la clase B tiene también un atributo que es la misma instancia de la clase A anteriormente mencionada
Un ejemplo de lo dicho:
![Captura](https://user-images.githubusercontent.com/48482216/64900627-85213680-d668-11e9-8270-62ce5f12b07e.PNG)

**Comment by aljara97** [comment]
Hola, el ejemplo que me muestras tiene errores de programación circular. En esta tarea, si bien no se evalúa, puede traer problemas en la modelación de tu programa. Te sugiero revisar las issues #221  y #248  en donde se toca el tema

Mucho éxito en tu tarea 🎉
