### ISSUE TITLE
Tutorial de como usar Py-QT5

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2233/syllabus#277]
No estoy entendiendo nada de como usar la libreria, he estado intentando ver que pasa si es que cambio alguno parametros de los codigos que ya nos entregaron e igual no entiendo mucho, alguien tiene un buen tutorial en youtube de como aprender a usar Py-QT5?

**Comment by jaromero6** [comment]
Este tutorial en español que encontré y a mi parecer explica bastante bien es el siguiente:
https://www.youtube.com/watch?v=DpSerOAZR9w
Incluye también el uso de QtDesigner, así que es bastante completo para aprender lo inicial. Si de momento no estás tan interesado en el uso del QtDesigner, este tutorial te podría servir ,aunque no es un video, es escrito y **está en inglés** :
https://www.mfitzp.com/article/create-first-window-pyqt5/
Es normal marearse con toda la documentación de PyQt5, lo que te recomendaría hacer es buscar tutoriales para la funcionalidad en específico que quieres implementar, ten en mente que es difícil encontrar un tutorial que tenga todo lo que necesites.

**Comment by lfuenzalida2** [comment]
Graciaas!
