### ISSUE TITLE
Evento especial Barco de Pasajeros

### ISSUE THREAD

**Issue by alvarocisternas** [IIC2233/syllabus#277]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
En el evento especial de los barcos de Pasajeros dice : "El evento especial de este tipo de barco corresponde a la intoxicación masiva de los pasajeros a bordo, lo que provoca que el barco pague una cantidad DINERO_INTOXICACION de dinero al canal a
cambio de medicamentos para sus pasajeros."
Como los barcos no tienen como atributo el dinero que poseen, entonces solo debería agregar la cantidad DINERO_INTOXICACION al dinero que posee el canal? 
Pensando en que en un flujo de dineros, una parte posee un descuento y la otra parte un ingreso, este no sería el caso?

**Comment by manearaya** [comment]
Hola @alvarocisternas!
No es necesario llevar la cuenta del dinero de los barcos, pero sí tienes que llevar cuenta del dinero del canal. Entonces, como tú dices, solo es necesario que el canal gane DINERO_INTOXICACION en el caso de que que ocurra el evento especial de intoxicación masiva.
Con respecto al flujo de dinero, una parte siempre posee un descuento y la otra un ingreso, pero solo nos interesa llevar la cuenta de este descuento o ingreso cuando corresponde al canal, ya que la simulación depende de que el canal no se quede sin dinero. Es decir, **tienes que calcular el flujo de dinero que entra y sale del canal.**
Puedes asumir que el barco siempre va a tener dinero para pagarle al canal, a menos que el enunciado diga lo contrario (issue #253). 
Saludos!

**Comment by alvarocisternas** [comment]
Muchas gracias @manearaya ! te pasaste !
