### ISSUE TITLE
Duda archivo como atributo de clase

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#277]
Hola! se puede agregar un archivo abierto a una clase como atributo y luego escribir en el en un método? es que no encuentro información sobre eso, gracias!

**Comment by jitorralba** [comment]
Hola @Natydlb!
Nunca he probado hacerlo pero debiese generar problemas si es que tienes más de una instancia de la misma clase, lo que te recomiendo hacer es escribir un método que te permita hacerlo directamente.
Avisame si te quedan dudas
Éxito con lo que queda de la tarea!

**Comment by Natydlb** [comment]
Pero debería importarlo dentro del método para que asi me funcione?

**Comment by jitorralba** [comment]
Claro, el método debería abrir, modificar y cerrar el archivo

**Comment by Natydlb** [comment]
no me funciono :(

**Comment by jitorralba** [comment]
Hazle push a tu repo personal e indicame donde está el problema

**Comment by Natydlb** [comment]
Es en la 124 :)

**Comment by jitorralba** [comment]
El import tiene que ir arriba donde van todos! Pensé que en tu comentario anterior con import te referias a abrirlo, entendí mal yo

**Comment by Natydlb** [comment]
me sale que la importo, pero que no la uso , por eso me sale con linea roja:(

**Comment by Natydlb** [comment]
File "/Users/user/Desktop/Repositorio/Natydlb-iic2233-2020-2/Tareas/T00/Tarea0.py", line 3, in <module>
    import puntajes
ModuleNotFoundError: No module named 'puntajes' 
Me sale eso, pero tengo abierto el archivo puntajes y ademas me encuentro en la carpeta donde esta puntajes

**Comment by jitorralba** [comment]
Borra el import, no es necesario importarlo porque es un archivo .txt, con eso te debería funcionar
