### ISSUE TITLE
Importar módulos

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#277]
Hola. En Python es posible importar un modulo para dos lados? Es decir, en el modulo A importo B y en el modulo B importo A. Es posible hacer eso?

**Comment by KnowYourselves** [comment]
Hola @tedroppelmann!

Si, se puede hacer importación círcular, pero si te encuentras con la necesidad de hacerlo es un síntoma de mal diseño. Esto se debe a que si tienes muchos archivos que dependen mutuamente unos de otros tu código se vuelve menos reutilizable.

En general, eso es solucionable re pensando la modelación o uniendo los módulos que dependen circularmente en uno.

Espero haberte ayudado!
