### ISSUE TITLE
Librerias permitidas

### ISSUE THREAD

**Issue by Chiseth** [IIC2233/Syllabus#278]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Mi duda es debido a que no entiendo que librerias son permitidas y cuales no. En el enunciado dice que si no esta especificado el uso de una libreria en el ennunciado, entonces, la libreria se encuentra totalmente prohibida. Sin embargo, en el enunciado no se menciona ninguna libreria a usar en todo el pdf, por lo cual se podría decir que no se puede importar nada. Sin embargo en la Issue #166 unn ayudante dice que la librería sys es permitida y luego más abajo dice que sys no esta permitida
Luego en la Issue #209 un ayudante menciona que para obtener la probabilidad aleatoria y ver si se activa o no el ataque del caballero se debe usar random. pero nuevamente eso no se especifica en el enunciado, por lo que estoy confundida y no se si al final estas se pueden o no usar. Y en el caso de que no se puedan no entiendo como obtendria un numero al azar o como verificaría la dificultad de la consola.

**Comment by Chiseth** [comment]
ya lo resolvi :)

**Comment by gasparbenavente2** [comment]
En el issue #166 hay una lista con las librerías que puedes y no puedes usar
