### ISSUE TITLE
Error "Qthread: Destroyed..." al jugar

### ISSUE THREAD

**Issue by Stomicicp** [IIC2233/Syllabus#278]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, no se si pueden ayudarme con u error extraño que me aparece cuando estoy probando el código. Todavia me faltan varias cosas por terminar pero cuando uno esta jugando de repente el juego se cae y sale el error: "QThread: Destroyed while thread is still running" y la ventana del juego se cierra. No entiendo muy bien lo que podría estar generando ese error para poder solucionarlo antes de entregar la versión final

**Comment by sebaguerrap** [comment]
Hola @Stomicicp ! Esto podría deberse a que se define el thread en el ```__init__``` de una clase de forma que al terminar de correr el ```__init__``` se pierde la referencia al thread por lo que es eliminado. (Puedes buscar más en esta issue que encontré del año 2015: https://github.com/IIC2233-2015-2/syllabus/issues/433).

**Comment by Stomicicp** [comment]
Pero al aplicar el self en la instancia del Thread no queda guardado para que se use después? Como que no entiendo como puedo guardarlo en el __init__ de mi ventana ya que se tiene que crear la instancia cada TIEMPO_AUTOS.

**Comment by sebaguerrap** [comment]
Lo importante es que el thread quede guardado en alguna parte donde sea accesible, por ejemplo, si creas un thread en el ```__init__``` de una clase, tienes que guardarlo como atributo de la clase (si tienes muchos puedes guardarlos en una lista). Ahora bien si tienes una instancia de una clase QThread, asegúrate de que puedas acceder siempre a ella. (Un ejemplo que se me viene a la mente de un caso donde no puedas acceder siempre a la instancia de la clase es el siguiente:)
```python
def funcion():
    instancia = Clase()
    ...
    return algo
```
En el ejemplo anterior solo se podrá acceder a la instancia de la clase mientras que la función se este corriendo, sin embargo, después de que retorne ```algo``` la instancia de la clase ya no será accesible.
