### ISSUE TITLE
No puedo encontrar Qt-desginer 

### ISSUE THREAD

**Issue by gustavobarrezueta** [IIC2233/syllabus#278]
Hola, acudo a ustedes luego de intentar por más de una hora abrir Qt-designer. No se si es una duda muy básica pero ya estoy desesperado. Tengo una Mac y logre instalar pyqt5 sin problemas al comienzo del curso pero no tengo idea de cómo abrir Qt-designer (por lo que entiendo debería tenerlo instalado). He intentado buscar por medio de mi terminal o en la carpeta de Python o descargarlo de internet desde qt.io (cosa que al final no pude instalar en el computador). Espero me puedan ayudar y lo siento si es una duda muy básica.

**Comment by iqacevedo** [comment]
Hola ! 

¿ Instalaste PyQt5-tools ?, en el [material del curso se subió un apoyo](https://github.com/IIC2233/contenidos/blob/master/semana-09/Extra/4-encontrar-qt-designer.ipynb) que dice que lo instalen, también hay una foto con un enlace a una issue de semestres anteriores con el mismo problema. Tal vez te sirva.

Quedamos atentos

**Comment by gustavobarrezueta** [comment]
Me aparece este mensaje cuando escribo el comando:
ERROR: Could not find a version that satisfies the requirement pyqt5-tools (from versions: none)
ERROR: No matching distribution found for pyqt5-tools
Es el mismo que aparece en la issue #516 del primer semestre del 2017... hago lo mismo que recomiendan en esas issue (descargar Qt5.x)? O hay otra forma de arreglarlo?
Gracias

**Comment by snarriagada** [comment]
me paso lo mismo en mac, lo descargue de https://build-system.fman.io/qt-designer-download

**Comment by iqacevedo** [comment]
@snarriagada muchas gracias por compartir cómo lo solucionaste. ¿@gustavobarrezueta con esa solución te funciona ?

**Comment by gustavobarrezueta** [comment]
Al final descargué Qt Creator desde la página oficial pero muchas gracias por la ayuda @iqacevedo , @snarriagada :)
