### ISSUE TITLE
Dias extra

### ISSUE THREAD

**Issue by chelo-carrasco** [IIC2233/Syllabus#278]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, como puedo solicitar días extra para la T1? 

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by CarolinaMezaCh** [comment]
Hola @chelo-carrasco!!

En el punto 10 del enunciado de la Tarea 1 se detalla la política de atraso en las tareas y descuentos asociados. Tienes que estar atento a que se abra un formulario de Google Form, después de la entrega oficial de la tarea, para indicar si deseas optar a entregar la tarea atrasada y si utilizarás los cupones. A continuación te dejo el punto 10 del enunciado para que lo leas con detalle:

**Entregas con atraso tendrán una penalización en la calificación máxima obtenida** acorde a la política de
atrasos. Sin embargo, tendrás a disposición cupones para eliminar días de atrasos.
Política de atraso:

- Hasta 1 día de atraso (00:01 a 24:00 hrs de atraso) tendrán calificación máxima 6,0.
- Hasta 2 días de atraso (24:01 a 48:00 hrs de atraso) tendrán calificación máxima 4,0.
- Después de las 48 hrs, no se aceptarán entregas atrasadas y se aplicará calificación mínima 1,0.

**Cupones**:

- Durante el semestre cada estudiante dispondrá de 2 cupones.
- Cada cupón permite eliminar 1 día de atraso en la tarea recién entregada.

**Posterior a la fecha de entrega de la tarea se abrirá un formulario de Google Form, en el cual deberán
indicar si desean optar por una entrega atrasada y si harán uso de 0, 1 o 2 cupones para la entrega**

**Comment by plourido** [comment]
Hola, que tal espero que se encuentren bien. Les quiero consultar si una vez ya respondido el formulario de google y haber obtenido una copia del formulario via mail, ustedes envían, una vez cerrado el proceso de entregas atrasadas, que commit se revisará?? 

Muchas gracias

**Comment by CarolinaMezaCh** [comment]
Hola @plourido!

El último commit que se revisará es el que hayas indicado en el formulario de google. 
Saludos!
