### ISSUE TITLE
Formulas y pistas

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus#278]
Tengo la duda de que por ejemplo las pistas de hielo no deberian afectarles el atributo rocas, aun si esta presente o no. Pero en los calculos de por ejemplo la velocidad recomendada, estan incluidas todos los atributos sea hielo, rocas y dificultad. Entonces lo que tengo entendido es que si estoy en una pista de hielo, automaticamente en los calculos deberia ser rocas = 0. Es asi? Porque por ejemplo la velocidad recomendada tendria la parte de defensa - rocas es defensa - 0 practicamente.

Lo segundo, es que si es como dije podria automaticamente hacer que las pistas de hielo su atributo sea 0 en el init? Digamos que si tipo = pista hielo, entonces si las rocas = 40, automaticamente en el init hace que las rocas sean = 0. Y cuando los guarde, se guardarian con rocas = 0. Esta permitido eso?

**Comment by RositaMunoz** [comment]
Hola!
Efectivamente, si tu pista no es de rocas, no debes considerarlas, por lo que en todos tus cálculos para ese tipo de pistas la cantidad de rocas es igual a cero. Lo mismo si tu pista es de tipo rocosa, no debes co siderar la cantidad de hielo. 
Con respecto a tu segunda pregunta, si puedes hacer que la cantidad sea cero, por lo mismo explicado arriba 
Espero haber respondido tu duda. 
Ánimo con lo que queda de tarea!
