### ISSUE TITLE
Utilización de parámetros.py

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#278]
Hola! No entiendo el uso de este archivo en el programa. Quieren que exportemos los valores desde ahí y utilizar los nombres que les pongamos en el programa? saludos y espero que se entienda :)

**Comment by JosefaPaz** [comment]
¡Hola @tedroppelmann !

Primero que todo, ten ojo que la extensión pedida para el archivo es .py ( parámetros.py). 

La finalidad de este archivo es que guardes los parámetros que en el enunciado se encuentran en **ESTE_FORMATO**, los paths, y cualquier otro valor que sea constante durante tu código, (siendo cada línea del archivo un parámetro) para que después, como tú dices, importes este archivo y así los utilices dentro de tus módulos principales con los nombres que pusiste en el archivo ```parámetros.py``` 😄

**Comment by maggiemunoz** [comment]
todas las formulas largas del enunciado como la probabilidad de atacar, la probabilidad de recuperar o sanar, etc también son consideradas parámetros?

**Comment by JosefaPaz** [comment]
@maggiemunoz  en este caso no, ya que un parámetro es un número que se mantiene constante durante todo tu código, y las fórmulas varían según la instancia que estés trabajando.

**Comment by maggiemunoz** [comment]
entiendo, gracias!

**Comment by amparostevens** [comment]
Hola! Si es que los parámetros son números constantes, los atributos de las clases que toman valores numéricos también hay que considerarlos parámetros?? Por ejemplo el efecto salud de los alimentos, aunque varíen por tipo de clase?

**Comment by JosefaPaz** [comment]
Hola @amparostevens !

En este caso no serían considerados parámetros, ya que como tú lo dijiste, son atributos de clases. Si bien se definen gracias a los parámetros cuando son creados por primera vez - como la destreza de un magizoólogo - estos después se guardan en el archivo csv, por lo que no deberían confundirse con los parámetros.

**Comment by JaviGuzman** [comment]
Hola!
No me queda claro por qué esos valores no deben ir en el archivo parametros.py, si de todas formas son números constantes. No puedo definir el efecto salud de la tarta, por ejemplo? Ya que este siempre será el mismo.

**Comment by tedroppelmann** [comment]
Tengo la misma duda con el efecto salud de los alimentos. Yo que había hecho era un archivo csv con los alimentos y después los exportaba como instancias de la clase alimentos, pero no se si se puede hacer eso. Saludos

**Comment by Dnpoblete** [comment]
Hola @JaviGuzman , hubo una pequeña confusión, pero como mencionas el efecto salud de la tarta sí tiene el formato de parámetro, por lo que si debería estar en parametros.py, como dato todos los que tengan el formato mencionado y tengan color celeste deberán ser considerados como parámetros.

**Comment by Dnpoblete** [comment]
Hola @tedroppelmann, lo que pasa es como recién mencioné todos aquellos números que estén en color celeste como el efecto de salud son parámetros que deben estar en el archivo parametros.py, por lo que no es necesario tener un archivo alimentos.csv, ya que de serlo se lo hubiésemos entregado. Ahora queda dentro de tu criterio si quieres mantener el archivo alimentos.csv, pero al momento de revisar la tarea no lo revisaremos, y aún así todos los parámetros deben encontrarse en parametros.py, porque ahí variaremos estos valores y deberían modificarse en todo el flujo del programa.

Espero haber aclarado tu duda y éxito con la tarea! ✨

**Comment by CataSudo** [comment]
Hola! Hay parametros tipo salud_min = 1, esos tambien hay que usarlos dentro del codigo?

**Comment by Dnpoblete** [comment]
Hola @CataSudo , como mencioné en el comentario anterior tienen que estar todos los valores que tengan el formato mencionado y estén en color celeste, eso si no encontré el que tu mencionas de salud_min en el enunciado, ¿En que parte esta? 

Quedo atenta a tu respuesta 😄

**Comment by CataSudo** [comment]
En DCC Criaturas, aparece en azul!

**Comment by Dnpoblete** [comment]
@CataSudo entonces como comente anteriormente, como aparece en azul si es un parámetro. 

Éxito con la tarea! 🧙🏻‍♀️
