### ISSUE TITLE
Atributos de plantas predeterminadas en jardines

### ISSUE THREAD

**Issue by Gaspartby** [IIC2233/Syllabus#278]
Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

[X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
[X] Revisé el compilado de dudas de la tarea y no encontré una issue similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/Syllabus/issues/11)).
[X] Mi duda no se trata sobre una librería o built-in, ya que eso se pregunta en la issue creada para ello ([click aquí para ir a esa issue](https://github.com/IIC2233/Syllabus/issues/10)).
 [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Duda
Cuando el usuario elige un jardín al comienzo del programa y este jardín contiene plantas desde un comienzo, de donde determinamos los atributos de esas plantas, como la vida máxima, la vida actual, etc. Debemos tomar como referencia el archivo plantas.txt y utilizar esos atributos para cada tipo de planta?

**Comment by R3Y3X** [comment]
hola espero que estés bien. Sí, las características iniciales debes tomarlas del archivo plantas.txt correspondientes a cada tipo de planta. Éxito en la tarea ⚡
