### ISSUE TITLE
sobre lo que retornan los metodos de demo.py

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#278]
Hola! Me bajó la duda de si es que es obligación que los métodos de demo.py retornen lo que dice en el enunciado. Por ejemplo, mi método colocar_pieza funciona bien, cumple con todas las reglas del juego, pero no retorna True si es que el jugador puede poner la ficha ni False si es que no puede (que es lo que dice el enunciado que deben hacer). No fue necesario hacer que retornara eso para que funcione bien el programa. Entonces, está bien lo que hice o tengo que cambiar mi código para que retorne lo que pide el enunciado?

**Comment by Arcoirisky** [comment]
Puedes comentarlo en el README si así lo consideras correcto pero, no olvides avisar por si llegara a suceder algo y no se pueda comprobar si de verdad está funcionando o no o:

**Comment by bedefrunner** [comment]
Ok, gracias!

**Comment by Arcoirisky** [comment]
Pd: Esas funciones no necesitan retornar nada o: si no las utilizas en ninguna otra parte, carece de sentido que lo hagan (Tal como dices tú) :D
