### ISSUE TITLE
Prints accidentales descuentan?

### ISSUE THREAD

**Issue by 3rdPix** [IIC2233/Syllabus#278]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Es una actividad común, crear lineas que impriman en consola mensajes clave para que uno pueda saber si el código llega (entra) a ciertos sectores de ejecución. En especial cuando necesita verificar el funcionamiento de una larga cadena de acciones.
`print('llega a plantar')`
`print('llega a línea 152')`
Dada la extensión de la tarea, y que a veces uno implementa esta técnica por muchos sitios, existe la posibilidad de que algún `print`, en algún módulo, se pase por alto y olvide borrarlo antes de enviar la tarea completa.
¿Si llegara a ocurrir, y la consola imprime un mensaje aparentemente aleatorio que diga `False`, o algun comentario que no tenga relación con el juego, descuentarían pts? ¿tengo que revisar detalladamente todos los módulos en busca de esos marcadores para borrar todos?

**Comment by PedroDP99** [comment]
Hola @3rdPix!
La evaluación de esta tarea se realiza a través de la interfaz, a menos de que en la distribución de puntaje se especifique que es por código o señales. Por lo que no habrían descuentos por los prints utilizados para debuggear tu código. Aún así, intenta quitarlos todos en la medida de lo posible, de esta manera queda más "limpio" todo. (Hint: control + F "print" y comentas o borras la línea 😎)
Saludos!
