### ISSUE TITLE
Duda archivos .csv

### ISSUE THREAD

**Issue by fsotomutoli** [IIC2233/syllabus#278]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! mi duda recae en si los archivos .csv deben ser reescritos (como en la tarea anterior, que había que reescribirlos y actualizarlos), ya que en el enunciado no sale nada sobre este aspecto

**Comment by Emiliax16** [comment]
Hola @fsotomutoli ! como mencionas, el enunciado no dice nada sobre editar los archivos csv, por lo que en esta tarea no debes hacerlo.
