### ISSUE TITLE
.gitignore no funciona

### ISSUE THREAD

**Issue by daniela-carreno** [IIC2233/syllabus#279]
Hola, ya subí todos mis archivos relacionados a la T00 y me puse a crear el .gitignore. Agregué los archivos mencionados en el Enunciado y di push, pero los archivos que quiero ignorar siguen en mi repo. Lei las issue 93, 119, y 219 relacionadas al tema y busqué en google. Entendí que dado que pushee esos archivos anteriormente quizás mi gitignore si funciona, pero no es retroactivo, es decir, no borra lo que yo subí anteriormente a mi repo y solo estaría ignorando sus cambios de ahora en adelante.

Mis dudas son:
1. Lo que entendí del gitignore es correcto?
2. Cómo quito archivos del repositorio sin eliminarlos de mi carpeta local?
3. A modo de recomendación para el futuro, debería crear el .gitignore antes de empezar a programar ?

Gracias!

**Comment by Tsbalart** [comment]
Hola @daniela-carreno!
Con respecto a tus dudas,
1. Efectivamente lo que entendiste es correcto!
2. Te recomiendo mover los archivos que quieres eliminar a otra carpeta, hacer nuevamente git push, y luego volver a poner los archivos en tu repo, y volver a hacer git push para verificar el funcionamiento del .gitignore.
3. En un futuro para que no vuelva a ocurrirte esto, si te recomendaria hacer el .gitignore antes del primer push.
Saludos! éxito con la tarea!

**Comment by daniela-carreno** [comment]
hice el paso 2 que me pusieron pero al hacer push en mi repo no aparece mi commit. Que hago?? :(

**Comment by Tsbalart** [comment]
El archivo deberia ser **.gitignore** le falta el . al nombre de tu archivo.
y me falto agregar los pasos anteriores del push en el paso 2: git add . , git commit -m "", git push
