### ISSUE TITLE
Duda extension maxima de lineas

### ISSUE THREAD

**Issue by vvialbarros** [IIC2233/Syllabus#279]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Queria saber que pasa en el caso de por ejemplo la produccion de soles, la formula de produccion me quedo de mas de 100 columnas (caracteres), en ese caso queria saber si uno se puede pasar un poco de las 100 columnas o el limite de extension son estrictamente 100 columnas y uno no puede pasarse nunca.

**Comment by R3Y3X** [comment]
hola espero que estés bien, el límite de extensión es estrictamente 100 caracteres, por lo que la formula de producción deberás dividirla para que no se superen estos caracteres por línea. Éxito en la tarea ⚡
