### ISSUE TITLE
Faltan fotos en photos 

### ISSUE THREAD

**Issue by sicorrecto** [IIC2233/Syllabus#279]
Hola, al correr Demo.py con mi propia lista de jugadores, me tira algunos errores `QPixmap::scaled: Pixmap is a null pixmap`, esto se traduce a que al elegir los jugadores para el equipo algunos aparecen sin foto, al buscar estos jugadores en la carpeta 'photo' me di cuenta de que no están.

Esto es un problema particular mío (se bajó mal photo)? Debería preocuparme por este error?

<img width="1280" alt="captura de pantalla 2018-04-18 a la s 21 25 53" src="https://user-images.githubusercontent.com/37185409/38965165-808bbac4-4351-11e8-8d8e-a29ab8cff274.png">

![Uploading Captura de pantalla 2018-04-18 a la(s) 21.24.59.png…]()

**Comment by cilopez** [comment]
Existen jugadores que no tienen fotos, puedes dejarlos sin fotos o agregarle una al azar.
