### ISSUE TITLE
Path Relativo

### ISSUE THREAD

**Issue by FelipeIGS** [IIC2233/Syllabus#279]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola de nuevo!

Una pregunta acerca de los path relativo. En la T0 me dijeron que debia ocupar os.path.join('Archivo', nombre_archivo) y me dijeron que estaba mal nombrarlo ../T0/nombre archivo al ser absoluto. Confirmo el tema de ocupar el os.path.join porque no se si todos abriran el archivo desde "Archivos"
Muchas gracias por todo!

**Comment by osillano** [comment]
Hola @FelipeIGS !

No sé si entendí bien tu pregunta. Efectivamente se recomienda el uso de la librería `os` para trabajar los paths. El path debe ser relativo al lugar en donde se encuentra el módulo principal de tu tarea.

**Comment by FelipeIGS** [comment]
Me referia a que como cada ayudante abre el archivo desde un lugar distinto ese modulo principal a veces depende del ayudante. Con modulo principal te refieres a que desde FelipeIGS (el modulo principal?) se abririan mis archivos, por ejemplo os.path.join("FelipeIGS", "main.py")? 

Y una pregunta con respecto a las variables globales, que creo que tengo unas para data_excavadores (y otras lineas lineas 459 - 462), pero al intentar poner esas variables dentro de Torneo me ocurren imports circulares o no me reconoce las clases(por ejemplo Torneo).

**Comment by osillano** [comment]
Con módulo principal me refiero al archivo `.py` que se debe ejecutar para correr la tarea. Por ejemplo, si se tiene una estructura:
```bash
Nombre
└── Tareas
    ├── TX
    │   ├── Archivos
    │   │   ├── archivo_1
    │   └── main.py
```
Como el módulo principal es `main.py`, el path relativo para acceder a `archivo_1` sería `os.path.join("Archivos", "archivo_1")`. 

Respecto a las variables globales, ¿Cual es exactamente el error que te aparece?

**Comment by FelipeIGS** [comment]
Al poner las funciones de redefining al inicio y poner data_excav and data_arenas, etc. en las partes que son utilizadas me indica el siguiente error:

File "c:\Users\felip\Desktop\FelipeIGS-iic2233-2023-1\Tareas\T1\entidades.py", line 58, in redefining_treasure
    tesoros.append(Tesoro(nombre = list_tesoro[i][0], tipo = "tesoro", \
NameError: name 'Tesoro' is not defined. Did you mean: 'tesoros'?

y tambien entra en un bucle al modificar algunas lineas. Alguna idea de cómo solucionar este tema? Que si creo otro modulo se auto-importan los modulos y vuelve a ocurrirme un circular_error

**Comment by osillano** [comment]
Viendo el código de tu repositorio, ese error parece ser causado porque estás tratando de instanciar un objeto de clase `Torneo` en la definición de la clase `Torneo`. No se puede instanciar un objeto antes de que esté definido.
