### ISSUE TITLE
¿Se actualizan los archivos .csv?

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#279]
Hola!

Me surgió una duda revisando la distribución de puntaje en la tarea 1, en particular, durante el ítem "Manejo de archivos". Aquí se pide _actualizar de forma correcta_ cada archivo .csv, pero este requerimiento no se declaraba en el enunciado de la tarea.

¿Es necesario que estos se actualicen? De ser así, ¿en qué momentos de la simulación?

edit: un compañero hizo esta pregunta 1min antes que la publicara, la elimino?

![imagen](https://user-images.githubusercontent.com/50121013/115623134-c955cd80-a2c6-11eb-98bc-da7bed83ccc2.png)

**Comment by Emiliax16** [comment]
Hola! @jamigone , fue error de tipeo. Se actualizó la distribución de puntajes. Como el enunciado no dice que deben modificar los archivos, entonces no se deben actualizar en ningún momento!
Quedo atenta por si tienes cualquier otra duda!
