### ISSUE TITLE
Ventana de Inicio

### ISSUE THREAD

**Issue by Nitsuga69** [IIC2233/syllabus#279]
<img width="1176" alt="Captura de Pantalla 2019-05-17 a la(s) 2 58 01 p  m" src="https://user-images.githubusercontent.com/48293112/57950076-33cc8a80-78b4-11e9-98c8-fa255fede721.png">
Hola, en esta parte, no entiendo si hay que crear dos ventanas distintas para el menú; una que me pida el nombre y otra donde se elija el bando con la opción de volver a la ventana del nombre. O, la ventana del menú es solamente una, donde se elige el nombre y el bando en esta (pero en este caso, no entiendo dónde debería estar la opción de cerrar sesión). Espero que se entienda y gracias de antemano.

**Comment by jaromero6** [comment]
Se te pide que a grandes rasgos el juego tenga dos ventanas y que cada una **debe cumplir su respectiva funcionalidad**

- Ventana de inicio
- Ventana de juego

Para la Ventana de inicio queda a tu criterio si lo haces todo en una sola ventana o creas varías para cumplir todas las funcionalidades que se te piden, en cambio para ventana de juego se te pide que tanto la preparación de la ronda y la ronda en sí misma **deben estar en una sola ventana**. . 
Por lo tanto, respondiendo directamente a tu pregunta, efectivamente puedes tener una ventana para iniciar sesión en una y elegir el bando en otra ventana aparte o bien hacer todo eso en una sola ventana.
Saludos y éxito con la tarea
