### ISSUE TITLE
problemas con utf-8

### ISSUE THREAD

**Issue by pdmino** [IIC2233/syllabus#279]
Hola, estoy teniendo problemas con la lectura de los archivos, la cual me arroja este mensaje: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 3417: invalid continuation byte
algún consejo sobre como solucionarlo?

**Comment by tgarcia4** [comment]
Me aparece el mismo error cuando guardo un segundo archivo

**Comment by jmwielandt** [comment]
Hola!

Explico lo que pasa y cómo arreglarlo (con python 😎) en la issue #267 .
En su caso, puedes probar con el mismo encoding que su compañero o con otro. Quizás `"latin-1"` les funcione.

Saludos y ánimo con lo que queda~ 👍
