### ISSUE TITLE
Estadisticas luego de ganar una ronda

### ISSUE THREAD

**Issue by elshavi** [IIC2233/Syllabus#279]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Holaaa, queria saber si luego de un combate en el cual combatientes del ejercito del jugador aumentaron/disminuyeron sus estadisticas, para la siguiente ronda estas deben ser reseteadas, se dejan como quedaron o queda a decision nuestra?
[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by diegoftpxd** [comment]
Hola @elshavi , en el enunciado no se especifíca nada acerca de este tema. Por lo que en gran medida pasa a estar a tu criterio siempre y cuando no transgreda el enunciado. Eso si ten en cuenta lo siguiente: 
La tienda cuenta con la opción de **Curar ejercito** luego se supone que la vida que tienen los gatos al llegar a la tienda puede ser diferente a la máxima así que da indicios de que deberían mantenerse.
Algunas estadísticas tienen valores máximos y mínimos. Luego ten cuidado de que núnca sean transgredidos (por ejemlpo la agilidad está entre 0 y 10).
Sobre si el resto de estadísticas se mantienen o no, está a criterio tuyo decidir. Lo importante es que esto lo dejes claro en el **readme**
