### ISSUE TITLE
¿Dónde poner el mutex?

### ISSUE THREAD

**Issue by 3rdPix** [IIC2233/Syllabus#279]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Estoy teniendo problemas con la visualización del movimiento. Algunos elementos se mueven mucho más lento de lo que deberían (mientras todo lo demás, alegremente, se mueve como debiera). Los widgets con problemas no tienen nada particularmente especial en común; algunos widgets creados antes de ellos, se mueven normal, y otros widgets creados después de ellos, también se mueven normal. Parecen tener un comportamiento aleatorio.

Dado que desconozco el origen de este error, asumo que se trata de un problema de concurrencia. Luego surge una serie de preguntas a partir de la forma en que está estructurado el código:

```
# en nivel inferior
def funcion_que_emite():
    alguna_señal.emit(objeto)

# en nivel superior
def funcion_que_es_llamada(objeto):
    objeto.mover(punto_especifico)
```
Surge de esta estructura la siguiente pregunta: ¿cuando el programa ejecuta la línea `alguna_señal.emit(objeto)`, considera la ejecución de ese método, algo único? ¿o considera que ahí existe toda la cadena de cosas que ocurren con la función a la que está conectada la señal? ¿El programa solo emite la señal, y luego considera que terminó la ejecución, o espera a que termine toda la cadena de cosas asociadas a la conexión de esa señal?

En base a esto, dónde debería poner una restricción de tipo QMutex?
**Opción A**
```
# en nivel inferior
def funcion_que_emite():
    EL_LOCK.lock()
    alguna_señal.emit(objeto)
    EL_LOCK.unlock()

# en nivel superior
def funcion_que_es_llamada(objeto):
    objeto.mover(punto_especifico)
```

**Opción B**
```
# en nivel inferior
def funcion_que_emite():
    alguna_señal.emit(objeto)

# en nivel superior
def funcion_que_es_llamada(objeto): # funcion mover
    EL_LOCK.lock()
    objeto.mover(punto_especifico)
    EL_LOCK.unlock()
```

Se debe considerar que muchos objetos distintos están llamando, tanto al método de la señal, como a la función `mover`, posiblemente en forma simultánea (y de ahi la concurrencia).

**Comment by Lord-Kelsier** [comment]
Hola @3rdPix , no creo que sea un problema de concurrencia ya que si este fuera el caso le podria pasar a cualquier widget en cualquier momento, es decir, el problema no se veria en un solo widget, sino que verias que todos van bien y en un momento uno falla en moverse 1 vez, luego otro falla 1 vez y asi. En todo caso, recuerda que las señales no ejecutan la funcion solo *triggerean* un evento que puede ser visto por el receptor
