### ISSUE TITLE
funcion verificar_tortugas: forma de contar tortugas

### ISSUE THREAD

**Issue by mmunozv** [IIC2233/Syllabus#28]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Si hay dos tortugas contiguas horizontalmente: ¿Se cuanta como si **ambas no cumplieran la regla, o solamente una?** 

Y como funciona con más de dos tortugas contiguas?

**Comment by Hernan4444** [comment]
Hola @mmunozv 

Ambas tortugas no cumplen (serían 2). Aquí tienes que ir tortuga por tortuga y si esta no cumple, el contador aumentará en 1. Si hay por ejemplo algo así
```
- T T - -
- T T - -
- - - - -
- T - - -
```
Serían 4 tortugas las que no cumplen esa regla.

Espero que este ejemplo te haya aclarado la duda,
Saludos!
