### ISSUE TITLE
Efectos de las nubes

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#28]
Hola!

En el penúltimo párrafo del punto 5.1 dice:

> En caso de nubes, no se modifican los puntos de poder ni tasa de propagación del incendio.

No entendí muy bien esto. Se refiere a que las nubes no afectan en nada la tasa de propagación calculada previamente? O que las nubes dejan en cero la tasa de propagación? No creo que sea la segunda opción, pero me gustaría estar seguro.

Gracias!

**Comment by Dunkan1** [comment]
no se modifican pero:
''Las nubes restringen la posibilidad de usar aviones o helic´opteros. Aviones no pueden operar si el techo
de nubes en el lugar del incendio es menor a 1500 metros. Helic´opteros no pueden operar si el techo de nubes
es menor a 1000 metros. Si no existe pron´ostico de nubes en el lugar del incendio, se asume que el techo de
nubes permite la operaci´on de cualquier aeronave.''
es decir con nuves luchin no sale

**Comment by akaminetzkyp** [comment]
Súper, entonces las nubes solo restringen las aeronaves y no afectan en nada la tasa de propagación?

**Comment by Dunkan1** [comment]
segun lo que yo entiendo no, pero no soy ayudante asi que te recomendaria que esperases a uno

**Comment by akaminetzkyp** [comment]
Oka, gracias!

**Comment by rpalmaotero** [comment]
@akaminetzkyp 

> Súper, entonces las nubes solo restringen las aeronaves y no afectan en nada la tasa de propagación?

Exacto.

**Comment by akaminetzkyp** [comment]
Gracias!
