### ISSUE TITLE
como crear una branch en la carpeta T0 desde la consola usando git?

### ISSUE THREAD

**Issue by ibgarrido** [IIC2233/Syllabus#28]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido

Hola! quería crear un branch para hacer versiones de prueba de la T0 pero no sé como hacerlo para una **carpeta en particular** (Considerando que hice git clone de mi repositorio personal completo que me entregó el bot del curso, y suponiendo que si trabajo en ese repositorio, el cual contiene todas las carpetas de actividades formativas y tareas, Si por ejemplo, cuando haga alguna tarea formativa, cuando actualice el repositorio no quiero que se haga completamente si no la carpeta correspondiente en la que voy a trabajar dependiendo de lo que esté haciendo)

Saludos!

**Comment by Juampisaez** [comment]
Holaa @ibgarrido 
Así como lo explicas, no se puede hacer. La forma de realizar lo que piensas es que crees una branch `T0` por ejemplo, y ocupes esa branch como desarrollo de tu tarea, en otras palabras, que trabajes en cada branch la actividad o tarea que corresponda (sin tocar las carpetas que no sean de esa evaluación).

Si encuentras otra forma, feliz que la comentes!
Quedo atento si sigues con dudas :)
