### ISSUE TITLE
AYUDAAA GitHub

### ISSUE THREAD

**Issue by fabarros** [IIC2233/Syllabus#28]
Hola, github y yo no nos hemos llevado muy bien y ya estoy hasta la reverenda con esto, creo que estoy a punto de commitear archivos del sistema. Hay algún ayudante que me pueda ayudar a dejar ok la cosa? Mañana estoy libre desde las 10 hasta las 14. Perdón por lo primitivo. Saludos.

**Comment by ifcarrera** [comment]
Hola! 
Yo te puedo ayudar :)
Estaré en el dcc desde las 11 de la mañana.
Saludos
