### ISSUE TITLE
Duda Properties

### ISSUE THREAD

**Issue by jasantamaria** [IIC2233/syllabus#28]
En la actividad nos pedían disminuir o aumentar la calidad de una pizza si contenía piña o pepperoni. 

Es correcto hacerlo como en el codigo adjunto o se debe llamar a la función calidad() que es una property para revisar su rango.  No sé si es correcto como lo hice en la función revisar_ingredientes()

```python3
class Pizza:

    def __init__(self, ingredientes=[]):
        self._calidad = random.randint(50, 200)
        # Rellenar Aquí
        self._lista_ingredientes = ["pepperoni", "piña", "cebolla", "tomate",
                                    "jamon", "pollo"]
        self.ingredientes = [random.choice(self._lista_ingredientes),
                             random.choice(self._lista_ingredientes),
                             random.choice(self._lista_ingredientes)]
        self._ingredientes_base = ["salsa de tomate", "queso"]
        self.ingredientes = self.ingredientes + self._ingredientes_base

    def revisar_tiempo(self):
        # Rellenar Aquí
        pass

    def revisar_ingredientes(self):
        # Rellenar Aquí
        if "piña" in self.ingredientes:
            self._calidad -= 50
        if "pepperoni" in self.ingredientes:
            self._calidad += 50

    @property
    def calidad(self):
        return self._calidad

    @calidad.setter  # Se controla que la calidad no sea negativa
    def calidad(self, valor):
        self._calidad = max(0, valor)
```

**Comment by KnowYourselves** [comment]
Hola @jasantamaria! (edité tu issue para que se viera bien el código)

Lamentablemente, no, no es correcto hacer `self._calidad -= 50`, para poder entender la razón de esto primero tenemos que entender el **fin** y el **funcionamiento** de la _property_ `calidad`.

Una _property_  añade **funcionalidades** a un atributo de una clase. En este caso, nosotros queremos que el atributo `calidad` nunca sea negativo. 

Veamos esta parte del código:

```python3
@property
def calidad(self):
    return self._calidad
```

Este código hace dos cosas:

1. Define a `calidad` como una _property_: 
&nbsp;
    Esto es lo que nos permite utilizar `self.calidad` como si fuera un atributo normal. 
&nbsp;
2. Define el `getter` de `calidad`: 
&nbsp;
    Esto define que valor vamos a obtener cuando escribamos `self.calidad` este valor se ve definido por el `return` de la función, que en este caso es `self._calidad`.

Sin embargo, esto por si solo no hace nada, podríamos simplemente hacer `self._calidad` y lograr lo mismo. La gracia de definir un `calidad` como _property_ es que podemos agregar el siguiente código:

```python3
@calidad.setter
def calidad(self, valor):
    self._calidad = max(0, valor)
```

Este código hace dos cosas:

1. Define el `setter` de `self.calidad`: 
&nbsp;
    Entraremos a este código cada vez que hagamos una asignación, por ejemplo, `self.calidad -= 50`
&nbsp;
2. Evita que `self.calidad` sea negativo: 
&nbsp;
    Como vimos antes, cuando usamos `self.calidad` en realidad estamos accediendo a `self._calidad`, entonces tiene sentido que cambiemos este valor. Especificamente hacemos que sea igual al máximo entre el valor que le queremos asignar y 0, es decir, siempre definiremos `self._calidad` como un número no negativo.

Finalmente, si hacemos `self._calidad -= 50` **no** entraríamos al `setter`, por lo cual el valor se podría pasar a los negativos. En cambio si hacemos `self.calidad -= 50` **si** accedemos al `setter` donde nos aseguramos que el valor no pase a ser negativo.

## Resumen:
1. `@property` nos define el `getter` de un atributo, al cual accedemos cuando hacemos `self.atributo`
2. `@atributo.setter` nos define el `setter` de un atributo, al cual accedemos cuando redefinimos `self.atributo`

Espero haberte ayudado!
