### ISSUE TITLE
Problema con Visual Studio Code al elegir interpreter

### ISSUE THREAD

**Issue by santiago3c** [IIC2233/Syllabus#28]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* X[ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

Hola, que en visual studio code quiero seleccionar mi interpreter que tengo gracias a haber descargado python desde Ubuntu, pero este no me sale y no se qué hacer. 

adjunto foto de lo que me aparece al elegir configuración y command palette
![Captura de pantalla (146)](https://github.com/IIC2233/Syllabus/assets/142272696/4346859a-7f65-42b3-a456-017f26aab6b5)

**Comment by santiago3c** [comment]
Esto es lo que me sale si pincho esa de buscar
![Captura de pantalla (147)](https://github.com/IIC2233/Syllabus/assets/142272696/94232ff5-4263-42f4-b897-949e1c535110)

**Comment by Hernan4444** [comment]
Hola @santiago3c 

Te recomiendo revisar la siguiente issue
* https://github.com/IIC2233/Syllabus/issues/15

En particular, desde [este comentario](https://github.com/IIC2233/Syllabus/issues/15#issuecomment-1681017920) donde explicamos el problema. 

En resumen: estás abriendo VSCode desde windows, pero debes abrirlo desde tu Ubuntu, dado que ahí si está tu Python. Por lo tanto, primero hay que abrir VScode de Ubuntu y ahí seguir con el siguiente paso, para eso, la issue indicada anteriormente tiene varias instrucciones al respecto.

Saludos

**Comment by santiago3c** [comment]
Cuando dices que hay que abrir VScode desde Ubuntu, ¿te refieres a que en Ubuntu ponga code . ? Porque eso ya lo estoy haciendo

**Comment by santiago3c** [comment]
Hola, ayer en la noche descargué un par de cosas, que no estoy muy seguro si eran las correctas... pero sí me está sirviendo ahora. Adjunto dos fotos del programa para ver si me puedes decir si se ve todo correcto o no.
![Captura de pantalla (156)](https://github.com/IIC2233/Syllabus/assets/142272696/a8ff7f5b-e95c-4978-b483-1bbc2613657c)
![Captura de pantalla (157)](https://github.com/IIC2233/Syllabus/assets/142272696/aa3f1605-11c7-4983-a834-22fb2e69cd19)

**Comment by Hernan4444** [comment]
Hola @santiago3c 

Está todo super 🎉 , con eso ya puedes ejecutar todo lo que quieras. Luego, usando `cd` deberás moverte por tus carpetas para llegar, por ejemplo, a la carepta "solution" de la experiencia 1 que está en el Syllabus, y ahí hacer "python3 main.py".

Saudos!

**Comment by santiago3c** [comment]
vale, muchas gracias
