### ISSUE TITLE
problemas imprimiendo el tablero

### ISSUE THREAD

**Issue by jpperez5** [IIC2233/syllabus#28]
Cuando trato de abrir un tablero de 3x4 , la función no lo imprime bien. El input que estoy usando para probar la función es [['','','',''],['','','',''],['','','','']], con utf8=True. ¿Estoy haciendo algo mal?

**Comment by DCCollao** [comment]
Hola!

Cuando lo pruebas con `''` (nada), se ve corrido el lado derecho del tablero. Esto no debería suponer un problema, pues el tablero no se llenará de esta forma. Si lo pruebas con algún caracter, debería funcionar bien. 
Recuerda que si quieres llenarlo con cuadrados blancos, la lista que debes entregarle a la función debe contener espacios.

Éxito!
