### ISSUE TITLE
Visibilidad de post propios en el Muro

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#28]
Hola,
tenia la siguiente duda:
¿En la funcionalidad de ver los Posts de los usuarios que sigues también se deben poder ver los propios?

Saludos!

**Comment by jeschuwirth** [comment]
Hola @Ignacioislae,

Cuando veas los Posts de los usuarios que sigas no debes ver los tuyos, para eso está la otra opción de ese menú.

Suerte!

**Comment by Ignacioislae** [comment]
Gracias!
