### ISSUE TITLE
Problema de Linting VS Code

### ISSUE THREAD

**Issue by MCorbella99** [IIC2233/syllabus#28]
Escribo errores a proposito y la ventana solamente me dice:
"No problems have been detected in the workspace"
Con un ayudante no pudimos solucionarlo.

**Comment by CarinaUG** [comment]
Me paso lo mismo y jugando, apreté play (aparece en la esquina superior derecha) y me aparecieron los errores en PROBLEMS

**Comment by aerotecnia99** [comment]
Hola!
Debes verificar que en las Preferencias (ctrl+shift+P) en Python: Select Linter esté seleccionado flake8 (debes instalarlo si te aparece una ventana con la opción install) y luego cuando abras una nueva terminal en la ventana PROBLEMS podrás visualizar todos los errores que contienen tus archivos. También puedes ver en Preferencias>Python: Enable Linting que esté seleccionada la opción Enable.
Espero haberte ayudado ◠‿◠

**Comment by MCorbella99** [comment]
Hola, ya había hecho todos esos pasos con el ayudante y no pusimos solucionarlo, pero ahora que abrí VS Code me apareció que no estaba instalado flake8, lo instale y esta todo perfecto. Muchas gracias :)
