### ISSUE TITLE
Duda con ejercicio propuesto 2.1

### ISSUE THREAD

**Issue by cnillanes** [IIC2233/syllabus#28]
Hola! Me queda una duda con la función atacar ya que los puntos de ataque y defensa están previamente definidos como atacante.ataque y defensa.defensa respectivamente pero no sé si ese atacante y defensa vienen de alguna clase que tengo que crear o de donde salen? A priori se me ocurre definirlas dentro de la función comenzar juego y una vez ahí llamar a la función atacar.
Y en el caso que puntos ataque y defensa sean iguales (i.e empaten) debo remover las cartas de cada jugador o seguir iterando hacia un nuevo turno?
Gracias desde ya :D

**Comment by tomasgv** [comment]
¡Hola @cnillanes!

En el enunciado del ejercicio se menciona que deberás cargar las cartas en una **estructura de datos adecuada** ([_hint_](https://github.com/IIC2233/contenidos/blob/master/semana-01/2-listas-tuplas.ipynb)). Existe una estructura de datos en particular que permite hacer lo que estás buscando :wink: .

Sobre el caso de empate, no se especifica qué debe pasar, por lo que queda a tu criterio y puede ser cualquiera de los comportamientos que mencionaste. Aprovecho de contarte que si te topas con algo que quede a tu criterio en alguna tarea tendrás que mencionar lo que hiciste en tu Readme 🤓  .

¡Espero haberte ayudado! 🎉
