### ISSUE TITLE
Clonación de repositorio 

### ISSUE THREAD

**Issue by mmangiamarchi** [IIC2233/Syllabus#28]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Al momento de intentar clonar mi repositorio mediante el terminal me sale un error, el cual dice que debo usar mi "personal access token". 

remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/IIC2233/mmangiamarchi-iic2233-2021-2.git/'

No encontré ninguna duda parecida y en internet me indica que debo generar un personal access token pero no se entienden bien las indicaciones.

**Comment by tqmbanados** [comment]
Hola @mmangiamarchi! Agradecería que me contarás si pudiste solucionar el problema para cerrar la issue.

**Comment by mmangiamarchi** [comment]
Hola si, gracias.
