### ISSUE TITLE
Duda sobre la función alcanzable de dcciudad

### ISSUE THREAD

**Issue by enzoacvi** [IIC2233/Syllabus#28]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! La función `alcanzable` de dcciudad evalúa si hay una ruta entre dos estaciones. Mi duda es si esta ruta es pasando por solamente un túnel o más de uno.

Tengo esta duda porque en el apartado relacionado al método `nivel_conexiones` sólo se especifica el uso de esta función de dcciudad (sin haber mencionado aún ninguna otra de aquel módulo), cuando en este método es importante saber lo directas que son las conexiones.

**Comment by Hernan4444** [comment]
Hola @enzoacvi 

La función `alcanble` verifica que exista una ruta, esta puede ser directa (A -> B) o pasando por muchos túneles (A-> C-> D -> B). 

En `nivel_conexiones` se evaluará que ocupen esta función, pero el desafío de ustedes es determinar en qué momento es apropiado ocuparlo dentro de la función. No es que debes ocupar únicamente esta función para resolver completamente `nivel_conexiones`, solo que debe ocuparse dentro... ¿donde exactamente? ahí está el desafío 😁... tal vez hay ciertas "validaciones" que puedes hacer sin necesitar de dicha función... pero en algún momento si o si la necesitarás ocupar 🙈.

Lamentablemente no puedo decir más porque estaría dando mucha pista de como resolver `nivel_conexiones`, pero espero que con las 2 explicaciones anteriores logres enfrentar el desafío de este método.

Saludosヾ(＾-＾)ノ

**Comment by enzoacvi** [comment]
Vale! De eso me quería cerciorar, muchas gracias 😊
