### ISSUE TITLE
Duda sobre tildes en Test Cases

### ISSUE THREAD

**Issue by MauroMigli** [IIC2233/Syllabus#28]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

**Tengo el problema de que las letras con tilde no se reconocen por VSCode. Tengo activado UTF-8 y aun así no las lee bien :(.**
![image](https://github.com/user-attachments/assets/70bcc14c-e2f6-4587-8e44-cb0aeb962cbb)

**Comment by Hernan4444** [comment]
Hola @MauroMigli 

Antes de responder tu duda, mucho ojo que VSCode **no es la herramienta para ejecutar los códigos**. Este es solo una herramienta para programar nuestros códigos mientras que es **la terminal** la encargada de ejecutar cada archivo `.py`. Por lo tanto, tener activado UTF-8 en VSCode no debería tener ninguna influencia en la ejecución, lo que debe ocurrir es que el `.py` tiene algún error que hace que el print no salga bien.


Ahora si, sobre el error que indicas, probablemente es porque falta utilizar correctamente el `encoding` al momento de abrir el archivo. Recomiendo revisar el contenido [2-I_O.ipynb](https://github.com/IIC2233/contenidos/blob/main/semana-01-introduccion/2-I_O.ipynb) de la semana 01 donde se habla más sobre el `encoding`.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ
