### ISSUE TITLE
consultas al revisar estado de encomiendas

### ISSUE THREAD

**Issue by K4rl4Munoz** [IIC2233/Syllabus#28]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

DUDA

![image](https://user-images.githubusercontent.com/101335687/159143261-eb4772b8-3c60-4561-bb98-a08a004e371a.png)

al querer revisar el estado de la encomienda el enunciado dice "muestra los atributos nombre y estado del articulo de las encomiendas del archivo encomiendas.csv que fueron realizadas por el usuario de la sesión"
como puedo saber que encomiendas fueron realizadas por el usuario?, o se refiere a las encomiendas dirigidas al usuario?

**Comment by jahernandez2** [comment]
Son las que el usuario ha enviado desde que inició sesión (opción [1] del menú de usuario: Ingresar encomienda). Antes de eso se asume que no ha enviado ninguna. Hay una Issue más abajo donde preguntan eso también. Saludos!

**Comment by jahernandez2** [comment]
Mira la Issue #19
