### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#28]
Hola, 
El diagrama de clases se hace con algún programa especial? Estoy haciéndolo con ArgoUML (http://www.descargarsoft.com/descargar-argouml-para-crear-diagramas-uml/). No recuerdo que hayan mencionado algún programa para hacerlos.

Gracias~

**Comment by yoavnavon** [comment]
Te recomiendo [www.draw.io](url), es una plataforma online que viene lista para hacer todo lo que necesites de diagramas de clase. En todo caso no es necesario un programa específico.

**Comment by jmwielandt** [comment]
Lo puedo hacer igual en ArgoUML? Es que ya lo tengo avanzado y solo deja guardar en formato .zargos o exportar a .UMI 
:/

**Comment by IchottMano** [comment]
La idea es que el ayudante pueda abrir facilmente el diagrama, por lo que sería mejor dejarlo en formato de imagen (.png, .jpg), por último puedes intentar sacar una captura de pantalla y enviar eso, si no el ayudante debería tener un programa específico para abrir tu diagrama y eso sería muy dificil.
