### ISSUE TITLE
Problemas con resizeEvent y sus propiedades oldSize() y size()

### ISSUE THREAD

**Issue by Liks96** [IIC2233/syllabus#280]
Hola! 
Estoy tratando de implementar una actualización automática del tamaño y posición de las entidades al achicar/agrandar la ventana, pero estaba viendo que al iniciar la ventana, me aparece que el cuociente entre size() y oldSize() me da un número negativo muy grande (el cuociente hecho entre los width() y height() correspondiente.

En los prints de la consola, me aparece algo así:
`-900.0
-700.0
0.9988888888888889
0.7777777777777778
0.9955506117908788
0.778642936596218
...`

Como se puede ver, el cuociente está funcionando como debería (al hacer un resizeEvent manualmente como usuario), pero no puedo entender como controlar el cuociente inicial (que pareciera coincide con las dimensiones de la ventana).

**Comment by Hernan4444** [comment]
Estimado, 

Esto no es necesario implementar, sobre esos datos, pueden ser los que aparecen cuando la pantalla está recién generándose, que de algo diminuto se va a algo gigante, pero esto es algo que no está en el enunciado, te recomiendo que de hacerlo, lo dejes al final c:

Saludos :v:
