### ISSUE TITLE
Como traer un label al frente para que no sea tapado por otros labels

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2233/Syllabus#280]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, tengo una  duda sobre si hay un método para traer al frente un label sin que cambie quien es su parent?? 
Lo que me pasa es que el sapo queda abajo de los troncos ya que estos se instancian después del label_sapo (ya que se generan a medida de que avance el juego)

**Comment by Maxi1805** [comment]
Hola @vice-rosas99, si entendí bien tu duda quieres usar los métodos raise() o lower() de la issue #248 que traen al frente y atrás del parent respectivamente. Aqui esta el link para que puedas leer un poco mas https://doc.qt.io/qt-5/qwidget.html#raise.

Espero que te sirva.

**Comment by vice-rosas99** [comment]
hola, si lo había revisado, el problema es que todos mis movimientos se basan en el sistema de coordenadas de un label.area_jugable, el cual está dentro de un label que es mi ventana de juego, si uso raise(), llevaría a mi labelsapo a estar en el label.ventanajuego, sacandolo de label.area_jugable

**Comment by vice-rosas99** [comment]
En todo caso ya encontré una solución: label_que_debería_estar_atraz.stackUnder(labe_que_debería_estar_adelante)

**Comment by vice-rosas99** [comment]
En todo caso ya encontré una solución: label_que_debería_estar_atras.stackUnder(labe_que_debería_estar_adelante)
