### ISSUE TITLE
malas practicas

### ISSUE THREAD

**Issue by javiermingo** [IIC2233/syllabus#280]
cuales son las malas practicas que descuentan nota?

**Comment by javiermingo** [comment]
que son las variables globales?

**Comment by kadroguett** [comment]
Hola @javiermingo, como dice en el enunciado en cada tarea se creará una issue que especifique cuáles son las malas prácticas que estarán prohibidas. En esta tarea es la #87. Sobre tu segunda pregunta te recomiendo hacer una nueva issue.
