### ISSUE TITLE
Uso de "\" es mala practica con print?

### ISSUE THREAD

**Issue by elshavi** [IIC2233/Syllabus#280]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Holaa, mi duda es si ocupar '\\' para no llegar a los 100 caracteres por linea esta permitido cuando se utiliza exclusivamente para prints, esto debido a que como de repente tengo que hacer prints en ciclos o condicionales, se me acortan los caracteres disponibles. Tambien se que es una opcion concatenar el print para asi no llegar a los 100 caracteres pero en mi juicio el codigo es menos legible de esa forma.

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by JJJGGGG** [comment]
Hola @elshavi ! Yo diría que la mejor práctica es hacer algo así:

```py
print(
    "Esta linea es muy larga por lo tanto vamos a "
    + "acortarla, parece que va a funcionar bien.. \n"
    + "Sigue la línea pero con un salto ahora"
)
```

También, siempre que estén **dentro de paréntesis**, se pueden omitir los `+`, de esta forma:

```py
print(
    "Esta linea es muy larga por lo tanto vamos a "
    "acortarla, parece que va a funcionar bien...\n"
    "Sigue la línea pero con un salto ahora"
)
```

o de esta forma:

```
texto_largo = (
    "este texto es muy largo y "
    "por eso vamos a tener que separarlo "
    "en múltiples líneas"
)
```

Cuidado con los espacios, que esta forma sólo concatena los strings, por lo tanto si no ponen espacio al final, entonces la última palabra del primer string se va a pegar con la primera del segundo.

Si ejecutamos el código, se ve así:

![image](https://github.com/IIC2233/Syllabus/assets/48324565/7d360f2c-2526-436e-a596-d91517f34c7d)

Espero haberte ayudado!

**Comment by elshavi** [comment]
Y para los return? como hago para separarlos ya que estos no tienen parentesis

**Comment by JJJGGGG** [comment]
Puedes hacer:

```py
return (
    "Hola "
    "Hola"
)
```

O

```py
return (
    "Hola "
    + "Hola"
)
```

Esto NO devuelve una tupla, sino que devuelve un valor (las tuplas con 1 elemento son así `("Hola",)`

Saludos!
