### ISSUE TITLE
Instalacion numpy

### ISSUE THREAD

**Issue by rfenzo** [IIC2233/Syllabus#280]
Hola, en el enunciado dice que hay que instalar únicamente numpy 1.12. , eso se refiere al 1.12.0 o tambien podemos usar el 1.12.1? Pregunto porque trate de instalar el 1.12.0 mediante "pip install numpy-1.12.1-cp36-none-win_amd64.whl" pero no hubo caso, solo pude instalar numpy mediante  "python -m pip install numpy", lo cual me instalo la versoin 1.12.1.

**Comment by Hernan4444** [comment]
@rfenzo si está bien!!! :smiley: 

Saludos!!

**Comment by rfenzo** [comment]
gracias!
