### ISSUE TITLE
Chasis Piloto al terminar la carrera

### ISSUE THREAD

**Issue by cristozille** [IIC2233/syllabus#280]
Hola, no me quedó muy claro en la sección 4 del enunciado cuando dice: 'Cada vez que se inicie una carrera, el vehículo se recuperará de todos sus daños obtenidos en las carreras anteriores'. 
Esto implica que si parto la carrera con chasis valor=30, una vez que termine la carrera debo volver mi chasis a valor=30? 
Y que sucede si mi chasis supera su valor inicial debido a muchas mejoras a  valor=45: al terminar la carrera debo volver a 30 o mantener el 40?
Gracias

**Comment by RositaMunoz** [comment]
Hola!
Tal como dice el enunciado, "Las mejoras compradas durante las carreras se mantienen en todo momento, ya sea que ganes, pierdas una carrera o cierres la partida." Por lo que si tu chasis inicial era de 30 y mejoraste tu vehículo durante la carrera a 45, el valor del chasis al iniciar otras carreras es 45.

Espero haber resuelto tu duda.

Éxito con lo que queda de tarea!
