### ISSUE TITLE
Duda sobre archivo de canales

### ISSUE THREAD

**Issue by arturoprietovic** [IIC2233/syllabus#280]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

El archivo que tiene los canales siempre va a tener 2 canales? Panamá y Suez? o al momento de la revision tiene que funcionar con mas canales?

**Comment by Emiliax16** [comment]
Hola, se usarán sólo esos dos canales para la revisión, sin embargo, siempre es una buena práctica almacenar los valores de los archivos como variables constantes y no trabajar sobre los mismos valores (ej. si un gato es _blanco_, no trabajar con _blanco_, sino que trabajar con una variable llamada _color_, al cual se asigna el color blanco o cualquiera otro). Esto se hace para que tu código sirva para cualquier valor que se le asigne. 
Saludos!

**Comment by arturoprietovic** [comment]
entiendo gracias!
