### ISSUE TITLE
__getitem__ y __len__ vs __iter__ y __next__

### ISSUE THREAD

**Issue by visalasc** [IIC2233/Syllabus#280]
Mientras trabajaba en mis estructuras de datos encontré en un blog  ( https://dbader.org/blog/python-dunder-methods ) que bastaba con getitem y len para poder iterar . No me queda claro en que casos es necesario utilizar iter y next sin que este demás al usar getitem y len.

**Comment by IchottMano** [comment]
@visalasc Hola!

Los métodos \_\_iter\_\_ y \_\_next\_\_ sirven para iterar tu Estructura de Datos y normalmente los usas entregando tu estructura a un *iterador*, siendo mucho mas rápido y usando menos memoria que \_\_getitem\_\_ y \_\_len\_\_. 

Sin embargo, si bien puedes iterar sólo con los dos primeros métodos mencionados, los métodos \_\_getitem\_\_ y \_\_len\_\_ son importantes individualmente, ya que te dejan indexar 
```python
>> a = mi_estructura(*(1,2,3))
>> a[1]
>> 2
```
Y tambien te dejan obtener la cantidad de objetos en tu estructura
```python
>> a = mi_estructura(*(1,2,3))
>> len(a)
>> 3
```
Por lo que tambien son importantes de implementar.

Saludos y disculpa la demora en la respuesta!

**Comment by visalasc** [comment]
Gracias! :)
