### ISSUE TITLE
Qtimers no funcionan

### ISSUE THREAD

**Issue by Bjnazar** [IIC2233/Syllabus#280]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!
Al intentar hacer los timers, intento poner un QTimer dentro de los atributos de una clase que hereda de QObject y no me funciona, el timer no parte de ninguna manera.
En cambio, cuando creo un timer en la ventana misma(clase Ventana) y ese qtimer realiza un método de esa misma clase ventana sí funciona.
Intenté buscar ejemplos de Qtimers y en la materia los hacían todos dentro de las ventanas, no se puede poner un Qtimer dentro de una clase que herede de Qobject? Es que no entiendo porqué no me funciona y tampoco he encontrado soluciones
Al partir el qtimer (timer.start) teniendo el timer definido en la clase que hereda de QObject desde la clase ventana tampoco funciona
De antemano muchas gracias!

El código que hice de ejemplo de este problema está en el archivo mov_fluido.py de mi repositorio de la tarea 2

**Comment by Hernan4444** [comment]
Hola @Bjnazar revisé tu código. El principal problema es que la instanciadora de tu clase que hereda de QObject no guarda dicha instancia en alguna parte y eso hace que cuando se termine de ejecutar el método que instancia dicha clase, se elimina el QTimer.

Para llevarlo al contexto de tu código, tienes un `z = Zombie(...)` lo cual es una variable local del método. Debes guardar ese  `z` en alguna parte que perdura (una estructura de datos o al menos hacer `self.z`).

Lo otro, solo por si acaso recuerda el uso de variables descriptivas :D
Revisa esa parte y quedamos atentos a cualquier duda que tengas,

Saludosヾ(＾-＾)ノ
