### ISSUE TITLE
Error extraño

### ISSUE THREAD

**Issue by depstein26** [IIC2233/Syllabus#280]
Hola, perdón lo poco específico del issue pero no entiendo por qué me arroja esto en consola al correr el demo, el programa me funciona bien y hace lo que he programado sin problema, solo que me sale esto al principio cuando corro el programa.
<img width="1280" alt="captura de pantalla 2017-09-10 a las 20 03 58" src="https://user-images.githubusercontent.com/30672947/30253842-7bbe054c-9663-11e7-96d0-91a4767d50cc.png">

**Comment by iqacevedo** [comment]
Hola, 

No te preocupes por eso, son advertencias de PyQt de que se está haciendo algo mal. Lo lamento por no haberlos notado, pero no afectan en nada a la tarea, por lo que no debes preocuparte.

Saludos !

**Comment by depstein26** [comment]
Gracias!
