### ISSUE TITLE
Movimiento vertical en tronco

### ISSUE THREAD

**Issue by jsilvalavin** [IIC2233/Syllabus#281]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! tenia una duda si es válido desactivar el movimiento vertical del sapito en el rio

básicamente, en mi código el sapito solo puede moverse horizontalmente en el río cuando esta sobre un tronco (sin salirse de éste) y no puede moverse en el eje y si no es con un salto - solo puede morir si salta al río-. En el enunciado se dice que el sapito debe poder moverse de forma libre en un tronco cuando está encima de uno ¿lo que estoy haciendo va en contra de eso o está bien? 
gracias :)

**Comment by Cristi512** [comment]
tengo la misma duda

**Comment by rodrigobj99** [comment]
Hola @jsilvalavin @Cristi512 ! Dado que el enunciado dice que debe moverse libremente en los troncos, entonces se debe considerar esto en la tarea.
