### ISSUE TITLE
aparición zombies

### ISSUE THREAD

**Issue by solebravo** [IIC2233/Syllabus#281]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! estoy confundida acerca de la función aparición zombies por algunas razones. Primero no entiendo el resultado que entrega, siendo este un float, y lo que yo hice fue transformarlo a int, pero no se si esto es correcto o se espera que utilicemos la función de otra manera, ya que no se me ocurre otra manera de utilizarlo como intervalo de en un QTimer. Segundo asumí que el numero entregado hacia referencia a segundos y por lo que los convertí en milisegundos al pasarlos como intervalo, pero de igual manera me parece como que fuera muy rápido.
Gracias de antemano.

**Comment by bernirosas** [comment]
Me uno preguntando si es que se podría multiplicar por 10.000 al pasarlo a entero para que el tiempo sea más razonable (cercano a 7 segundos entre zombies).

**Comment by catalinamirandah** [comment]
¡Hola!

Claro que puedes :D, pero todo eso lo debes dejar por escrito en el readme.
