### ISSUE TITLE
duda con "life steal" 

### ISSUE THREAD

**Issue by TomasAguirrebena** [IIC2233/Syllabus#281]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

lo que ocurre es que al momento de iniciar el combate en los 1 vs 1 el gato que saque la mayor ventaja en los primeros golpes quedara con una vida mayor a la del enemigo y por algún motivo como que por cada ronda que golpea al enemigo este literalmente se cura un poco quedando casi full, yo supuse que esto estaría debido a que cuando resto la vida - el ataque del oponente algo raro ocurre y se pone negativo por lo que use abs() para ver si se solucionaba y efectivamente se solucionaba, pero generaba otros problemas como bucles infinitos derrepente, por lo que lo deje fuera ya que es el único inconveniente que encontré, lo deje muy recalcado en el README pero como aun queda unas horas para la entrega quería saber si me podían iluminar.

**Comment by diegoftpxd** [comment]
Hola @TomasAguirrebena , con respecto a tu problema, creo que tiene relación en con un daño de valor negativo. Esto genera que por alguna razón se estén curando. Creo que esto puede ser indicio de que no estás implementando una restricción del enunciado en la sección 4.2.1.  Aquí se dice que los daños siempre deben ser **iguales o mayores a 1**. Osea que valores negativos quedarían prohibidos. Talvez implementando esto pueda solucionarse tu problema.
Creo que esta puede ser la solución pero no puedo revisar tu código.

**Comment by TomasAguirrebena** [comment]
Gracias !!! se me paso por completo esa condición, ahora si funciona bien la pelea y no se curan los gatos, hacia que mi juego tuviera un desbalance increible
