### ISSUE TITLE
Duda sobre dificultad del juego y los parámetros que altera

### ISSUE THREAD

**Issue by Thomassch32** [IIC2233/Syllabus#281]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, no me queda claro que parámetros cambian según la dificultad a la que esté el juego... ¿Cambian los soles robados, la armadura o la constante de soles? sería útil una lista más específica.
Saludos!

**Comment by Amath3o** [comment]
Por lo que entendí cambia la probabilidad de que ocurran los eventos del archivo "eventos.txt" y por otro lado los parámetros como ARMADURA por ejemplo son de libre definición, siempre y cuando tengan sentido, así que puedes decidir si quieres que interactúen con la dificultad o no

**Comment by augustayanez** [comment]
Los cambios que hay según la dificultad del juego son los siguientes:

- Para cada evento, su probabilidad de ocurrir cambia dependiendo de la dificultad de juego seleccionada (estas probabilidades ya vienen dadas en el archivo eventos.txt para cada evento y cada dificultad).

- Para el evento Oleada de Zombies, cada dificultad tiene un parámetro específico (ZOMBIES_FACIL, ZOMBIES_INTERMEDIO o ZOMBIES_DIFICIL) para definir cuantos zombies tendrá el grupo que atacará tu jardín.

**Comment by Thomassch32** [comment]
Gracias, me quedo super claro
