### ISSUE TITLE
QLabels fuera del init

### ISSUE THREAD

**Issue by Brocoleta** [IIC2233/syllabus#281]
Hola, estoy tratando de crear una funcion dentro de la ventana principal la cual esta encargada de crear qlabels para modelar a los enemigos en el frontend, pero al tratar de crear un qlabel fuera del init este no me aparece en la interfaz, hay alguna manera de crear un qlabel fuera del init?

**Comment by Polea012** [comment]
Hola! Para asignar la ventana padre a un QLabel puedes entregárselo al instanciarlo en el método. Como los métodos de una clase reciben a la instancia misma (`self') lo puedes entregar.

```python

class Ventana(QWidget):
        def __init__(self) :
           super().__init__()
           self.labels = [] 
        def crear_label(self) : 
           nuevo_label = QLabel(self) # Aquí indicamos que el label debe aparecer en esta ventana. 
           self.labels.append(nuevo_label) # Guardamos la instancia. 
           nuevo_label.show() # Para que aparezca en la ventana. 
```

Espero que te sea de ayuda, saludos.

**Comment by Brocoleta** [comment]
Gracias

**Comment by DCCollao** [comment]
Hola! No cierres las issues que te responden, pues alguien más podría tener la misma duda. #2
