### ISSUE TITLE
Correo coordinadora

### ISSUE THREAD

**Issue by valeria-adasme** [IIC2233/Syllabus#281]
Hola, sé que nos dijeron que no podíamos enviar correos, pero necesito comentar un asunto personal con la coordinadora del curso y no lo encontré en la página del curso ¿Me podrían decir cuál es?

Gracias

**Comment by egromero** [comment]
Hola, en la página del curso se encuentra esa información:

https://iic2233.github.io

Saludos

**Comment by FernandoPieressa** [comment]
El contacto es por medio de ayudantesiic2233@gmail.com

Saludos!
