### ISSUE TITLE
Duda sobre dinero que poseen los barcos

### ISSUE THREAD

**Issue by ignaciaurrutia** [IIC2233/syllabus#281]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, no entiendo como obtenemos el dinero que posee cada barco. Cuando ocurre el evento especial del barco pasajeros por ejemplo, este debe pagar un DINERO_INTOXICACION al canal, pero de donde se obtienen esos fondos para pagarle al canal? O el dinero para salir del canal también. Gracias!

**Comment by DomingoCarvajal** [comment]
No debes llevar la cuenta del dinero de cada barco. En la issue #253 se habla sobre este tema.
