### ISSUE TITLE
Problema con código para distribuir los barcos

### ISSUE THREAD

**Issue by sbvillalobosm** [IIC2233/syllabus#281]
Hola!

Mi problema es que mi código crea 2 barcos a veces. La mayoría de las ocasiones distribuye los 3 barcos que corresponden, y tanto el tablero del jugador como el de la computadora tiene 3 barcos, pero en ocasiones solo aparecen 2 y cuando eso pasa me falla todo el juego. Revisé mi código pero no logro ubicar dónde está fallando :(

**Comment by Tsbalart** [comment]
Hola @sbvillalobosm!
Lo mas probable es que ese problema se deba a que tus barcos se están "transponiendo" en algunos casos, que el random coincide, por lo que deberias verificar que al hacer el random no pueda poner una B donde ya había una puesta.
Espero que se haya entendido y se solucione tu problema.
Exito con la tarea!

**Comment by sbvillalobosm** [comment]
Muchas gracias! Con eso me di cuenta de que estaba controlando el que no se traspusieran casi al final de un ciclo, así que si se trasponían al comienzo, no se iba a chequear eso. Ahora lo pude arreglar :)

**Comment by Tsbalart** [comment]
Buenísimo!
