### ISSUE TITLE
La probabilidad de accidente se calcula antes o después del daño recibido por la vuelta?

### ISSUE THREAD

**Issue by DonJavi-538** [IIC2233/syllabus#281]
Precisamente como dice el título...
¿La probabilidad de accidente se calcula antes o después del daño recibido por la vuelta?

En el enunciado no se especifica, y me surgió la duda porque el daño del chasis afecta esta probabilidad.

**Comment by jmwielandt** [comment]
Hola! 😄 

Eso lo respondo en la issue #154 .

Saludos y ánimo con lo que queda~ 👍
