### ISSUE TITLE
Ejercicio propuesto 3.1, Semana 2

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#282]
Hola, intenté hacer el código del ejercicio pero al ejecutarlo me saltaba un error diciendo que el archivo "influencers.csv" no se encontraba. Intenté mover el archivo en donde estaba mi código a la carpeta en donde se encuentra el archivo  "influencers.csv" y ejecutarlo desde ahí. Lo ejecuté pero ahora me saltan un montón de errores y mi programa no termina nunca de ejecutarse

![image](https://user-images.githubusercontent.com/69520590/91643240-71005180-e9ff-11ea-8de4-4057889fafb7.png)

**Comment by tocococa** [comment]
Hola @En-clases ! 

Primero que nada, el _path_  de la terminal de VSCode está en el directorio correcto? Prueba corriendo tu programa desde una terminal externa (como CMD, WT o PowerShell) y me dices como te va. 

Lo otro es que si moviste el archivo `herencia.py` desde `~\Escritorio` a otra carpeta, es posible que VSC siga intentando ejecutar dicho archivo en `~\Escritorio` y no en la nueva carpeta, y por eso te salen todos esos errores.

Si sigues con problemas por favor avísame por acá mismo!
