### ISSUE TITLE
Unir ríos o caminos

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2233/Syllabus#282]
En el enunciado dice que el plot twist se aplica cuando se coloca la ultima pieza para unir un rio o un camino y mi duda es a que se refiere con unir, si es cuando se conecta con una ciudad o en que momento sería

**Comment by cilopez** [comment]
Un río o un camino se encuentra unido (completo) si : 
* Este se conecta con 2 o más ciudades (completas o incompletas) 
* Si se conecta con una ciudad(incompleta o completa) con una grilla

**Comment by Jiruiz2** [comment]
Disculpa la ignorancia, pero qué es una grilla?

**Comment by fnquinteros** [comment]
Es un anglicanismo de _grill_, que significa rejilla 😅 a lo que se refiere @cilopez es conectar una ciudad al borde de la grilla (que es una sola), es decir, el borde del tablero. Saludos!

**Comment by Sforrego** [comment]
@cilopez 
![image](https://user-images.githubusercontent.com/26422390/30385563-f4e8ec36-987d-11e7-90fd-6e4d14a0ce62.png)
![image](https://user-images.githubusercontent.com/26422390/30385578-fe5eb70a-987d-11e7-99bc-63e32c71679c.png)

un camino que tiene estos tipos de piezas en sus extremos no se encuentra terminado?

**Comment by iqacevedo** [comment]
@Sforrego Esos también se consideran terminados (claro solo por el lado que llega a esa pieza).

Saludos !

**Comment by Sforrego** [comment]
@iqacevedo En ese caso como podria conectar mas de dos ciudades?

como dice aca:
![image](https://user-images.githubusercontent.com/26422390/30388314-ba3e2e54-9885-11e7-9971-fa714d436c3a.png)

**Comment by jpmoraga1** [comment]
No entiendo bien las conexiones de ríos con ciudades, ya que ningún río llega directamente a una ciudad. ¿Se refiere con conexión a colocar piezas que tengan río y ciudad aunque no estén "conectados"? Por ejemplo: 
![crccrc](https://user-images.githubusercontent.com/24195066/30409524-ff0b3db4-98db-11e7-925e-9d4e1c92134b.png)
¿Acá habría conexión entre ciudades? (Para mí no, pero no sé de que otra forma podría conectar ciudades mediante ríos)

**Comment by cilopez** [comment]
@jpmoraga1 , esa si sería una conexión. @Sforrego  Te respondí en otra issue creo #241 ,
