### ISSUE TITLE
¿Cuales son los valores constantes que realmente debemos utilizar? Más algunos problemas de importación

### ISSUE THREAD

**Issue by vruizz22** [IIC2233/Syllabus#282]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!! Tengo una pequeña duda con las constantes, por ejemplo si el oro inicial es 5 según el enunciado, **como hago para poder jugar una ronda si los gatos valen minimo 10**. Luego, pregunto lo mismo para el resto de valores constantes, (ATQ_MAG, RED_MAG, etc...) que no se especifican, me imagino que van a nuestro criterio. Finalmente tengo la duda con los problemas de importancion dado que en la issue https://github.com/IIC2233/Syllabus/issues/269, dijieron que hay que dejar todas las rutas en el archivo parametros.py, sin embargo, la **RUTA_DIFICULTAD** me genera problemas de importación circular, ya que main.py recibe los argumentos, parametros.py importa el argumento desde main.py lo pasa a ruta y lo devuelve a main.py, donde esto es lo que genera el error. 😞

**Comment by wintermelyn** [comment]
Hola @vruizz22! 🤠

> Si el ~oro inicial es 5 según el enunciado~, como hago para poder jugar una ronda si los gatos valen minimo 10.

El enunciado no designa un valor de ORO_INICIAL por lo que es un parametro que pueden elegir ustedes y la idea es que le alcance para comprar 1 o mas gatos para su ejercito.

> El resto de valores constantes, (ATQ_MAG, RED_MAG, etc...) que no se especifican, me imagino que van a nuestro criterio.

Exactamente eso, tienen libertad para nivelar el poder de las clases ustedes mismos.

> RUTA_DIFICULTAD me genera problemas de importación circular, ya que main.py recibe los argumentos, parametros.py importa el argumento desde main.py lo pasa a ruta y lo devuelve a main.py

parametros.py no debe importar nada que provenga de main.py puesto que ocurrirá el problema de importacion circular. Para resolver esto te recomiendo revisar la documentación de [uso basico de pathlib](https://docs.python.org/es/3/library/pathlib.html#basic-use). Como pequeño tip recuerda que el enunciado te permite asumir que _"los 3 archivos de dificultad siempre estarán en la carpeta data/"_ por lo que cada path es **constante** (y por lo tanto va en parametros.py).

**Comment by vruizz22** [comment]
Super muchas gracias! Ahora además cree un diccionario con sus values como objetos de DCCombatientes que importa de parametros.py, por lo que tuve que crear una archivo extra para este caso.

**Comment by wintermelyn** [comment]
@vruizz22 Mientras tu archivo de parametros.py posea lo requerido por el enunciado no hay problema en que crees mas archivos auxiliares, sobretodo si ya explicas tu justificación en el readme. 👍
