### ISSUE TITLE
Duda al guardar y crear entidades

### ISSUE THREAD

**Issue by Afro27** [IIC2233/syllabus#282]
Tengo entendido que al crear un nuevo piloto, este no se debe agregar a pilotos.csv si esque el jugador no guarda su partida. Mi pregunta es al crear vehiculos nuevos, estos deben ser agregados inmediatamente a vehiculos.csv, o solo se deben agregar los vehiculos nuevos, siesque se guarda la partida. Si fuera como en el primer caso, y el piloto solo se guarda al guardar,  podria pasar que queden vehiculos con dueños inexistentes?

**Comment by gatochico** [comment]
Hola! 

En el enunciado se indica que cuando se crea un piloto nuevo, este debe guardarse inmediatamente en `pilotos.csv`, no esperar hasta que guarde la partida. Ahora, con respecto a los autos:

- Si el vehículo es el inicial (primero que adquiere el jugador), se guarda automaticamente en el .csv
-Si el vehículo no es primero que tendría el jugador, queda a tu criterio ver si se guarda automaticamente o sólo cuando le usuario elija guardar. (Ver la issue #263 para más detalles).

Éxito en la tarea!!!
