### ISSUE TITLE
Problema al leer csv

### ISSUE THREAD

**Issue by JorgeBdelaT** [IIC2233/Syllabus#282]
Hola, estoy tratando de leer el csv pero me arroja el siguiente error:
UnicodeEncodeError: 'charmap' codec can't encode character '\u0107'

Busque en internet y me sale que debe ser un problema de la consola de windows y que pusiese el comando chcp 65001, sin embargo el error persiste.  Que mas podría hacer?

**Comment by ignaciohermosillacornejo** [comment]
#234
