### ISSUE TITLE
QThread Error

### ISSUE THREAD

**Issue by maureenmaremaa** [IIC2233/syllabus#282]
Hola! Tengo un problema con el siguiente error: 
"QThread: Destroyed while thread is still running"
Se supone que mi thread si termina de correr mediante el método .quit() pero me sigue saliendo este error. Saben cómo puedo solucionarlo?

**Comment by Oisangui** [comment]
Me pasa lo mismo. Prueba haciendo return en el metodo run(). No me ha fallado

**Comment by maureenmaremaa** [comment]
Lo intenté pero no me solucionó el error :(

**Comment by roberto009** [comment]
Hola @Oisangui !
Esto ocurre normalmente cuando creas tu `Qthread`  en tu `Main Window` o en cualquier lugar que lo estás creando, pero no lo referencias en ningún lugar de la clase donde está corriendo. La forma más fácil de solucionar esto es guardándolo como un parámetro de la clase en la que se está ejecutando, de la forma `self.qthread_ejecutandose = QThread(...)`. 

Si no te quedo claro te recomiendo ver el siguiente [link](https://stackoverflow.com/questions/15702782/qthread-destroyed-while-thread-is-still-running)

Éxito con la tarea 😄
