### ISSUE TITLE
efectos potencilantro , cilantrillo y fensaulantro

### ISSUE THREAD

**Issue by Amath3o** [IIC2233/Syllabus#282]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
La  potenciación de estas planta es acumulable? o solo se elige la mayor potenciación cercana para las plantas que lo reciben?
y también sobre los efecto del fensaulantro y el aresauce se comportarían de la misma forma? es decir, en caso de haber 2 o mas seria el mismo efecto sobre el mapa que si hubiera solo 1 o se irian acumulando

**Comment by rodrigoaguilera15** [comment]
Hola, esto se respondió en la issue #241. Saludos.
