### ISSUE TITLE
Posicionamiento carpeta assets

### ISSUE THREAD

**Issue by tcapom** [IIC2233/Syllabus#282]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Considerando que el cliente y servidor tienen que funcionar completamente aparte, entiendo que en cada una de sus carpetas debería estar autocontenidos los archivos necesarios para la ejecución de cada uno. Me imaginaría entonces que al ser el cliente el único con interfaz gráfica, entonces sólo él debería tener acceso a la carpeta assets. Pero según el punto 10 del enunciado, como la carpeta assets tiene que ser parte del gitignore; ¿debo asumir que assets no se puede mover de posición y su ruta predefinida tiene que ser la misma para todas las entregas, o puedo en el readme indicar la posición en la que asumo que van los assets?

Muchas gracias

**Comment by cattpuccino** [comment]
Hola! Puedes mover la carpeta a tu gusto, pero debes dejar claro donde la dejaste en el README 🤗
