### ISSUE TITLE
Duda evento especial DCCocinero

### ISSUE THREAD

**Issue by matyjjn14** [IIC2233/syllabus#282]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, tengo una duda con el evento especial del tripulante DCCocinero, en especifico, no me queda claro del enunciado si es capaz de duplicar el tiempo de expiración una o más veces, o si hay un momento en el cual se activa, por ejemplo si la comida se agota? o al comienzo? 
Gracias, de antemano

**Comment by DomingoCarvajal** [comment]
Hola @matyjjn14.

Las habilidades de los tripulantes ocurren una vez y automáticamente. Es decir al comienzo del viaje de un barco con un tripulante DCCocinero, los alimentos de este ya tienen el doble de tiempo de expiración.

**Comment by matyjjn14** [comment]
gracias!
