### ISSUE TITLE
No puedo crear o mostrar nuevos label si la ventana es visible

### ISSUE THREAD

**Issue by llambias** [IIC2233/Syllabus#282]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, al añadir nuevos objetos y obstáculos en la ventana de juego, estos simplemente no aparecen a menos que los añada cuando la ventana no es visible, es decir, tengo que usar self.hide() si quiero añadir un objeto, ya intente usando raise_() y lower()

**Comment by Maxi1805** [comment]
Hola @llambias, para esto diría que hay 2 métodos que te podrían servir, el método repaint() para forzar a que se actualice o el método show() para hacer que se muestre la label.

Espero que te sirva.

**Comment by llambias** [comment]
gracias si sirvio
