### ISSUE TITLE
Errores de Enunciado

### ISSUE THREAD

**Issue by nivek0o0** [IIC2233/Syllabus#282]
Hola
1. Hay que corregir la fórmula de la distribución gamma, en el denominador debe ir la función gamma y no el factorial. Esto debido a que el parámetro **k** puede no ser entero, como ocurre en la 11-ava consulta de _consultas.json_. 
Luego, ¿podemos usar las integrales de numpy para calcular dicha función? o ¿asumimos que el parámetro **k** siempre será entero?

2. Hay que corregir la consulta n°10 de _consultas.json_, la variable se llama "funcion_normal" en vez de "normal"

Gracias

**Comment by Hernan4444** [comment]
@nivek0o0 hola!!

1. Puedes suponer que les entregaremos solo **k** enteros, en caso de consultas.json, el resultado de esa consulta fue considerando k = 1 (nuestro programa dejaba un 1 si le llegaba algo invalido)

2. Si había un error pero era que "normal" se debía llamar "normal2", si vez los resultados.txt entenderas porque :D

Saludos!!

**Comment by nivek0o0** [comment]
Hola nuevamente, 
la consulta n° 11 de _consultas.json_ debería arrojar un error, ya que RQL no permite usar como nombre de variable un nombre de alguna distribución de probabilidad. ¿Estoy en lo correcto?

**Comment by Hernan4444** [comment]
@nivek0o0 
Error nuestro, en la consulta n°11 y 12 `gamma `debería llamarse `funcion_gamma`.

Saludos!!
