### ISSUE TITLE
Detectar que se soltó un clic izquierdo 

### ISSUE THREAD

**Issue by Mardones567** [IIC2233/Syllabus#282]
Hola, tengo implementado todo el sistema para que al arrastra la planta esta se posicione donde quiero, ¿pero quiero saber como con mouseMoveEvent o de otra forma puedo detectar que el clic ya no esta presionado?

Ejemplo de lo implementado, la idea seria que cuando detecte que el clic no se presiona, deja plantada la planta.

https://user-images.githubusercontent.com/111083659/195494003-f4578dba-9295-4158-9a8f-6909990e1d02.mp4

**Comment by Hernan4444** [comment]
Hola @Mardones567 

Tal como existe el evento para detectar un click del mouse o el movimiento, tambien existe el evento para detectar cuando se libera un click. El desafío de este bonus es investigar cómo se llama dicho evento y utilizarlo, al menos te confirmo que hay un evento que justo hace lo que necesitas, pero no es con mouseMoveEvent.

Saludos :D
