### ISSUE TITLE
Usar while True: y luego break es conisderado una mala práctica?

### ISSUE THREAD

**Issue by Masterville** [IIC2233/syllabus#283]
Hola, algo así:
while True:
----variable = int(input())
----if variable > 5:
--------break

**Comment by danckoo1** [comment]
Hola! Para efectos de la tarea no se considera una mala práctica así que pueden usarlo. Sin embargo, no es muy aconsejable usar breaks, ya que en ocasiones pueden agregarle mucha complejidad al código y actuar como trampas 👀
