### ISSUE TITLE
Posición en pantalla de label en QGridLayout

### ISSUE THREAD

**Issue by fivaldivia** [IIC2233/syllabus#283]
Hola, quería saber si saben de alguna forma en que pueda obtener la posicion de un label dentro de una grilla. Esta grilla la cree en Qt Designer y poble con el mapa dandole posiciones de (20 x 15) del tamaño del mapa. Ahora cuando intento obtener la posicion real en la pantalla de la imagen, no se como hacerlo. He buscado y no me aparece nada :(. He tratado con pos() los cual me tira un QPoint y al sacarle el QPoint.x() por ejemplo me tira que todos son 0.

Gracias

**Comment by jaromero6** [comment]
Hola,  encontré un foro, aunque cuidado que es de **PyQt4** que te puede ayudar.  El comando que te puede ser útil es geometry.topLeft() para obtener la posición del label. (O puedes manipular el resultado para obtener lo que desees)
El link lo puedes ver [aqui](https://forum.qt.io/topic/29162/find-widget-coordinates-inside-a-layout/2)
Otra forma de hacerlo que se me ocurre (similar a la del link que te mandé), es tomar la posición del label y hacerle un desplazamiento acorde a su ubicación en la grilla, ten en mente que si conoces la posición de la grilla entonces para cada label dentro puedes sumar o restar a cada coordenada según correponda para obtener el valor que deseas.
Espero que te sirva

**Comment by fivaldivia** [comment]
La verdad que leyendo y tratando no logré hacerlo, ya que este es mi problema, lo encontré buscando demaciado : https://stackoverflow.com/questions/11594634/qt-widget-position. Aún así aquí sale que "The parent must not be 0 and must be a parent of the calling widget" y al imprimir la posicion de algun label me imprime cero. No se como arreglarlo.

**Comment by jaromero6** [comment]
Hola, buscando métodos en ese mismo link que mandaste encontré un método que te puede servir, este es **mapToGlobal**. Ten en mente que es un método de la clase Widget, por lo tanto no estoy seguro si otras clases tengan el mismo método.
El modo de usar este método es simple, sería dentro de la clase de tu ventana:
`posicion_label = label.pos() # Esta te retorna el (0,0) porque lo hace respecto a la grilla`
`posicion_final = self.mapToGlobal(posicion_label) # Te retorna la posición global respecto a la ventana`
Avísame si te sirve

**Comment by fivaldivia** [comment]
Pucha, la verdad que no me funciona, ya probé. Al principio me pone las posiciones del gridlayout, no global. Trate de cambiar el show() porque leí que podria afectar dependiendo de donde se encuentra este en el código, entonces lo puse despues de crear el mapa y me imprime coordenadas que no corresponden a nada, ni global ni del grid. Te mando esa parte de mi código para ver si puedes encontrar que está fallando. Muchas gracias.
[Duda_posicion_gridlayout.docx](https://github.com/IIC2233/syllabus/files/3195266/Duda_posicion_gridlayout.docx)

**Comment by jaromero6** [comment]
Mirando tu código me llama la atención ciertos aspectos:
- Porque no mejor en self.pos guardar el label en si mismo, piensa que si mueves el label de posicion mas adelante la posicion en tu lista se mantiene igual.
- Respecto a label y label2, no me queda clara la funcionalidad de cada uno, es decir, para las funcionalidades que quieres hacer solo con label te basta (aunque quizás querías implementar algo con ese label que no está en el código, esto es más una observación).
- Lo más importante, es que probando un código muy simple y agregando labels de la misma forma que lo haces en un for (pero en self.pos gurdando el label en vez de la posicion), llegué a la conclusión de que tu problema puede ser por estar printeando las posiciones en el init. Ten mando un ejemplo de lo que hice:

 ```
class Juego:
   def __init__( self):
          super().__init__()
          self.setupUi(self)
          # self.show_pos nos muestra la posicion de los labels
        self.pushButton.clicked.connect(self.show_pos) # Conectamos un botón que le puse a la grilla   con show_pos para que veas la diferencia
        self.labels = [] # Aqui guardaremos la posicion de la grilla
        self.cargar_mapa()  
        self.show_pos()  # Aquí me printea un objeto QPoint vacío


    
    def cargar_mapa(self):
       # Se agregan unos labels y se guarda su posición
        for i in range(10):
            for j in range(10):
                label = QLabel(self)
                label.setText(f'{i,j}')
                self.grid.addWidget(label, i,j)
                self.labels.append((label))
    
    def show_pos(self):
        # Este método al llamarlo con el click del botón printea las posiciones efectivas
        for i in self.labels:
            print(self.mapToGlobal(i.pos()))
    ```
El método show_pos a pesar de llamarlo después de cargar el mapa en el init, no printea las posiciones de los labels, pero si lo hace si se llama de otra forma, como apretando el botón.

**Comment by fivaldivia** [comment]
Muchas gracias, te pasaste.
