### ISSUE TITLE
daño vehículo

### ISSUE THREAD

**Issue by maormeno** [IIC2233/syllabus#283]
El daño al vehículo en cada vuelta dice max(0, defensa - rocas); eso esta bien?? Mi pregunta es porque si la defensa del vehículo es mayor a la cantidad de rocas (algo que supongo que es bueno), el valor va a dar positivo.... pero si las rocas son mas que la defensa (caso desfavorable), entonces la función va a entregar 0 daño al vehículo? Eso esta bien?

**Comment by RositaMunoz** [comment]
Hola!
Te recomiendo hacer pull del enunciado, porque se avisó que había un error y los valores del daño al vehículo estaban dados vuelta.
![imagen](https://user-images.githubusercontent.com/48262755/64908271-3ad59f00-d6d4-11e9-8a49-b3d8b47edf74.png)
Así es la ecuación ahora.

Ánimo con lo que queda de tarea!
