### ISSUE TITLE
Uso del sys.argv 

### ISSUE THREAD

**Issue by JosefaATP** [IIC2233/Syllabus#283]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Cómo están?
No me queda. muy claro el uso de sys.argv. Eso se usa solo para comenzar a correr el código? o se debe usar cada vez que se recibe un input? 

Gracias!
![image](https://github.com/user-attachments/assets/5b3be9f1-62d8-4cc6-afc3-2c8185bbbed4)

**Comment by augustayanez** [comment]
El uso de sys.argv se recomienda para trabajar con argumentos de línea de comando, que son aquellos que le entregas al programa por consola para iniciar su ejecución, que en este caso serían el nombre del jardín y la dificultad. Una vez inicializado el juego cada vez que se reciba un input no será un argumento de línea de comando, sino que será un input común y corriente, por lo que debes manejarlo como tal.

**Comment by JosefaATP** [comment]
Perfecto, gracias!
