### ISSUE TITLE
Zombie ralentizado, permanece así?

### ISSUE THREAD

**Issue by 3rdPix** [IIC2233/Syllabus#283]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado no especifica qué hacer con un zombie que fue ralentizado. Si uno fue ralentizado, permanece así para siempre? aunque dejen de llegarle guisantes de hielo? aunque muera la planta que lo ralentizó en un principio? o debemos darle un tiempo de recuperación, y si no le llega ningún guisante de hielo, puede volver a su velocidad normal...

**Comment by iespinazac** [comment]
Hola @3rdPix!
Basta que el zombie sea ralentizado una vez para mantenerse así durante toda la ronda, no importa si la planta que lo ralentizó desaparece 😄.
Quedo atenta si surge otra duda 👀
