### ISSUE TITLE
Duda con imágenes de piezas

### ISSUE THREAD

**Issue by depstein26** [IIC2233/Syllabus#283]
Hola, creo tener un problema con el archivo de las piezas, pues a veces al guardar o cuando me arroja una pieza nueva sale "invisible", cuando hago el trabajo con el historial me pasa lo de la foto a veces y si intento de poner una pieza contigua al lugar que sale como más feo en la grilla me lo permite con la misma secuencia de la pieza que debería estar ahí (está bien que la pieza haya quedado después de volver a otro estado).
Quería saber si es un problema con el archivo de la foto y la interfaz o hay un problema con mi programa. Lo que digo está en las casillas (4,4) y (5,4) (considerando del 0 al 7 el total).

Espero se haya entendido, gracias!
<img width="988" alt="captura de pantalla 2017-09-11 a las 00 13 59" src="https://user-images.githubusercontent.com/30672947/30257181-80220ca0-9686-11e7-81e2-e0f8f0483fa9.png">

**Comment by iqacevedo** [comment]
Hola,

Eso ocurre cuando por algún motivo no había una pieza en el lugar de la interfaz donde está la pieza a jugarse, y luego se utiliza add_piece para mover esa pieza al tablero. Entonces, revisa siempre cargar la pieza antes de agregarla al tablero.

Saludos !

**Comment by depstein26** [comment]
Gracias! Pero si por alguna razón quiero poner piezas en el tablero sin el método colocar_pieza no puedo hacerlo? Con cargarla te refieres a usar nueva_pieza? Gracias nuevamente

**Comment by depstein26** [comment]
Porque también a veces me pasa que en la parte de la interfaz donde está la pieza a jugarse me sale en blanco y cuando la intento jugar en el tablero la juega pero de forma "invisible"

**Comment by MariaJosefinaAlliende** [comment]
@depstein26 a mi me pasaba eso  al llamar a pop_piece en un lugar en donde no había ficha...revisa  que haya algo antes  de llamar a esa función :)

**Comment by depstein26** [comment]
Gracias!
Pero estoy bastante seguro que siempre hay algo, de hecho agrega una ficha invisible de las mismas características de la ficha que debería estar y en la consola cada vez que pasa eso me salen cosas del tipo de la imagen que adjunto. Perdón lo insistente, pero me fijé que cada vez que hace add_piece hay una ficha para jugar
<img width="1280" alt="captura de pantalla 2017-09-10 a las 20 03 58" src="https://user-images.githubusercontent.com/30672947/30258787-cdbf21a8-9692-11e7-9c14-00b5210a54b6.png">

**Comment by mesantamaria** [comment]
@depstein26 a mi me pasaba eso cuando hacía gui.nueva_pieza y le ponía los bordes rotados (no los originales que están en gui). Tienes que ponerle los originales y después rotarlos porque sino no encuentra la pieza.

**Comment by depstein26** [comment]
Gracias!
