### ISSUE TITLE
Dudas bonus tienda

### ISSUE THREAD

**Issue by narispe** [IIC2233/Syllabus#283]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola tengo dos dudas relacionadas al bonus de la tienda.
1. Tras realizar una compra en la ventana tienda y volver a la ventana de post nivel, ¿la cantidad de monedas que se muestra debe actualizarse?
2. ¿No es necesario mostrar en la ventana tienda la cantidad de monedas actuales?

**Comment by tamyhan** [comment]
Hola @narispe ! Tras realizar una compra, se ocupan monedas de las que el personaje lleva recolectando durante el juego, por lo que al volver a la ventana de post nivel, se debe actualizar tanto la cantidad de monedas restantes, como el elemento que se obtuvo. 
Con respecto a tu segunda duda, no es necesario mostrar la cantidad de monedas actuales en la ventana de tienda, pero lo puedes agregar si quieres :)
