### ISSUE TITLE
problema con path absoluto

### ISSUE THREAD

**Issue by tomasvasquezp** [IIC2233/Syllabus#283]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

hola! estoy teniendo problemas para obtener el path absoluto de los archivos, porque cuando uso os.path.abspath, me retorna el path del archivo pero con 2 / juntos y no 1 como debería ser, como por ejemplo: Users//usuario//archivo, y lo que quiero que me retorne es Users/usuario/archivo, como lo puedo hacer?

gracias!
[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by diegoftpxd** [comment]
Hola @tomasvasquezp , primero que nada. Ten en cuenta que el uso de path absolutos puede ser considerado mala práctica si es que los path absolutos no funcionan para **otros computadores**. Siempre es recomendable usar path relativos.
Con respecto al problema, en las actividades es común que esto suceda cuando estás en visual studio y para ejecutar haces uso de el boton de play que está arriba. Te recomiendo probar a ejecutarlo mediante un terminal. Para hacerlo debes hacer lo siguiente:

1. Abres un terminal
2. Te dirijes a la carpeta en la cual se encuentra tu archivo de python a ejecutar
3. pones en la termianal py NOMRE_DEL_ARCHIVO_DE_PYTHON
(Si no funciona con py, prueba con python y python3)
Prueba a hacer esto, si logras hacerlo y aún así persiste el error podemos probar otro método.

**Comment by tomasvasquezp** [comment]
al final usé path de pathlib (vi en una issue que se podía usar esa librería), poniendo Path('path_archivo').resolve() y después lo probé en otro pc por si lo podía abrir y me dejó
