### ISSUE TITLE
Error al usar librería Currency Converter

### ISSUE THREAD

**Issue by Joaquin3000** [IIC2233/syllabus#284]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Descargué Currency Converter y he intentado muchas formas para que corra, pero me dice que no existe el modulo currency_converter. Al descargarlo me apareció este Warning, que no sé si está relacionado
WARNING: The script currency_converter is installed in '/Users/joaquin/Library/Python/3.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

El sistema operativo es MacOs Catalina
 **¿Cómo podría arreglarlo?**

**Comment by matiasfernandez1** [comment]
Hola!
Se soluciona escribiendo esto en la terminal:
`code /.bashrc`
Esto abrirá el visual studio con el archivo .bashrc, que es un archivo que se ejecuta cada que utilizas la terminal que contiene variables que puede que necesites utilizan mientras ejecutas cosas en él. Es algo así como un parametros.py que utilizamos en las tareas pero para el programa de la terminal. 
Ya dentro de este archivo colocas en la última linea:
`export PATH=/Users/joaquin/Library/Python/3.7/bin:$PATH`
Con esto ya habrías importado el path que te faltaba y estaría solucionado el problema.
Si no te resulta prueba haciendo lo mismo sólo que con el archivo `zshrc`. Esto depende más de la terminal que uses. Los pasos serían los mismos.
Escribes en la terminal:
`code /.bashrc`
Y en la última linea del archivo colocas:
`export PATH=/Users/joaquin/Library/Python/3.7/bin:$PATH`
La solución la encontré acá [https://stackoverflow.com/questions/58051467/fixing-path-for-python-libraries-using-bash](url)
Saludos.

**Comment by Joaquin3000** [comment]
Hola Matías! Con eso me funcionó. Muchas gracias !

**Comment by matiasfernandez1** [comment]
De nada :D
