### ISSUE TITLE
Duda sobre imprimir cada combate en combatir

### ISSUE THREAD

**Issue by AlanGoldsmith25** [IIC2233/Syllabus#284]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo una pregunta, **se debe imprimir cada combate individual (como van bajando las vidas de cada combatientes) o solo tengo que retornar si se ha avanzado de ronda o he perdido?**

**Comment by mon-b** [comment]
Hola! En el enunciado no aparece nada sobre esto, por lo que es tu decisión si lo haces o no :).  Si lo haces, acuérdate de escribirlo en tu README para que la persona que te corrija tenga toda la información. Éxito en tu tarea :D
