### ISSUE TITLE
RETORNO DATOS CLASES

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2233/syllabus#284]
Hola!
Cuando llamo a una de mis clases desde el main para que me retorne datos, me aparecen como None todos, ¿hay alguna solucion?

**Comment by RositaMunoz** [comment]
Hola!
La verdad la solución que te puedo dar es que investigues por qué te retorna None. 
Puedes verificar que los datos se estén guardando correctamente en tu clase, o que si éstos vienen de un archivo, verificar que estás cargando correctamente los csv. 
Puedes poner `prints` para saber si está entrando a algún `if` importante, etc. 

No hay una solución concreta para esto, es solo veficar tu código e ir probando datos o poniendo `prints`.

Espero haberte ayudado con tu duda
Ánimo con lo que queda de tarea!!
