### ISSUE TITLE
Duda parámetro ZOMBIES_DIFICULTAD y probabilidades

### ISSUE THREAD

**Issue by JorgeUribeGo** [IIC2233/Syllabus#284]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda sobre la forma de guardar los valores de probabilidad de heladas y zombies según la dificultad. En el enunciado nos mencionan un parámetro ZOMBIES_DIFICULTAD (_"Siendo DIFICULTAD la dificultad actualmente elegida"_), y no entiendo si el parámetro se llama así y solamente guarda la dificultad elegida como un str o si hay que crear ZOMBIES_FACIL, ZOMBIES_INTERMEDIO y ZOMBIES_DIFICIL, donde cada una vale un float entre 0 y 1.

Mi idea era guardar en un diccionario los valores para las dificultades pero no estoy seguro de si tengo que guardarlos como valores por separado o cómo funciona eso.
_(Lo mismo aplica para las heladas en esta pregunta)_

**Comment by augustayanez** [comment]
Respecto a ZOMBIES_DIFICULTAD, tienes que crear ZOMBIES_FACIL, ZOMBIES_INTERMEDIO y ZOMBIES_DIFICIL y estos parámetros representan la cantidad de zombies en el grupo de zombies que atacará tu jardín.
Puedes guardar los valores de probabilidad de los eventos de la forma que quieras, siempre que tu programa funcione y cumpla con el enunciado.
