### ISSUE TITLE
[Entrega Intermedia] duda .gitignore

### ISSUE THREAD

**Issue by iacampillay** [IIC2233/Syllabus#284]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Para la Entrega intermedia, es necesario realizar un gitignore? O simplemente puedo subir todo el archivo de T2? También tengo una duda sobre si es necesario completar el Readme para esta primera entrega.

Saludos y gracias

**Comment by AntonioVenegas** [comment]
Hola!, el readme se debe completar para la entrega final. Y para el gitignore, debes obligatoriamente ignorar los archivos y carpetas indicados en el enunciado. Dado lo anterior, en la entrega inmediata no se especifica que se deban ignorar archivos, por lo que solo debes completar `funciones_cliente.py` y `funciones_servidor.py` con las funciones pedidas.

Saludos :)

**Comment by AntonioVenegas** [comment]
Corrección, para la entrega inmediata debes ignorar la carpeta de los tests (perdón por la equivocación)

**Comment by Joako5848** [comment]
> Corrección, para la entrega inmediata debes ignorar la carpeta de los tests (perdón por la equivocación)

La carpeta de los tests es la de test_publicos, pero me imagino que también hay que ignorar el run_public_tests.py que está en la carpeta de entrega intermedia, verdad?

**Comment by ignaciopena7** [comment]
Si subí dentro de la carpeta tarea 2, la carpeta entrega intermedia junto un archivo .gitignore y las funciones a entregar dentro de entrega intermedia, ¿esta correcto?

**Comment by AntonioVenegas** [comment]
Hola @Joako5848!, en el enunciado solo se les pide ignorar el enunciado, la carpeta de los assets y la de los tests. Pero dada la naturaleza del gitignore, deberías también ignorar `run_public_tests.py` (aunque no se les debería descontar si no lo hicieron). Saludos :)

**Comment by AntonioVenegas** [comment]
@ignaciopena7, el archivo gitignore debería encontrarse en la carpeta `Tareas/T2/`, y desde ahí ignorar todos los archivos y carpetas correspondientes.
Saludos :)

**Comment by isidoragutierrez** [comment]
En el anunciado de la tarea sale que debe ignorarse la carpeta assets/, ¿cuál es esta?

**Comment by AntonioVenegas** [comment]
Hola @isidoragutierrez, lo que pasa es que al añadir los archivos al gitignore después de haberlos subido a tu repositorio, no se eliminan automáticamente. Por lo que debes eliminarlos de tu repositorio antes de ponerlos en el gitignore. Hay varias formas de hacerlo pero creo que en está página se explica como hacerlo mejor. [](https://itnext.io/how-to-remove-files-already-added-to-git-after-you-update-gitignore-90f169a0a4e1 )

SI algo te falla me avisas, saludos :)

**Comment by isidoragutierrez** [comment]
ahí lo logré :) muchas gracias!
