### ISSUE TITLE
descheckear radio buttons

### ISSUE THREAD

**Issue by videvidts** [IIC2233/syllabus#284]
Quiero usar la funcion setChecked(False) para deschequear mis radio buttons pero no funciona así nada más metiéndola en la función, alguna idea de como hacerlo?

**Comment by jaromero6** [comment]
Hola, especificamente en que parte estás usando el setChecked(False)?  Lo digo porque si por ejemplo lo estás dejando en el init, entonces ese método no se ejecutará en ninguna otra parte no sea en el init, un esquema que debería estar en tú código:
`def __init__()`
`   Defines todo lo relativo a la ventana`

`def deschequear(self)`
`      self.mi_radio_button.setChecked(False)`

`def comprueba_si_ocurre_un_evento(self)`
`   if ocurre_el_evento:`
          `self.deschequear()`

En este _código_  el radio button se deschequea si ocurre el_evento, asumimos que self.compruba_si_ocurre_un_evento está **siempre observando** la ocurrencia de algun evento(como por ejemplo un keyPressEvent o un método que conectas a un botón con clicked.connect) .En caso de tener algo similar, te recomendaría revisar si efectivamente al ocurrir el evento estás llamando a la función que en el ejemplo sería self.deschequear, o bien si efectivamente estás captando de manera correcta la ocurrencia del evento.
Espero te sirva.

**Comment by quememo** [comment]
Para poder usar setChecked(False) para un radio button, primero debes quitarle la exclusividad mediante setExclusive(False).
Una solución a este problema sería algo de la forma:

`self.boton1=QRadioButton("1")`
`self.boton1.setExclusive(False)`
`self.boton1.setChecked(False)           #Ahora si funcionaría el setChecked y se desmarcaría`   

Luego si deseas tenga exclusividad (para que se desmarque al seleccionar otro boton), puedes setearlo como exclusivo luego de utilizar setChecked(False)

`self.boton1=QRadioButton("1")`
`self.boton1.setExclusive(False)`
`self.boton1.setChecked(False)`   
`self.boton1.setExclusive(True)`
