### ISSUE TITLE
Aleatoriedad direccion de autos y troncos por nivel o por partida

### ISSUE THREAD

**Issue by narispe** [IIC2233/Syllabus#284]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/216)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Cuando se pide que la dirrecion de los autos y troncos sea aleatoria, ¿se refiere a que se deben definir aleatoriamente en cada nivel, o el la direccion se define aleatoriamente solo al iniciar la partida y se mantiene constante en todos los niveles?

**Comment by tamyhan** [comment]
Hola @narispe ! Como no está especificado en el enunciado, queda a tu criterio y deberás mencionar tu decisión en tu README. Recuerda de todas maneras que la dirección en la que se mueven los autos/troncos en cada hilera debe ser aleatoria, pero que los autos/troncos de una misma hilera se deben mover en el mismo sentido.
