### ISSUE TITLE
puntaje rio que pasa por borde de la grilla, ciudad roja y ciudad azul

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#284]
Cómo sería la asignación de puntaje en el siguiente caso?
Un río pasa por el borde de la grilla, por una ciudad roja incompleta y por una ciudad azul incompleta, el último jugador en poner alguna ficha que aporte al largo del río fue el jugador rojo y el río tiene en total 5 piezas de largo.
Como el jugador rojo es el dueño de todo el río (por regla plot twist), la ciudad azul por la que pasa el río cuenta también para su puntaje? El puntaje del jugador rojo entonces sería:
+25 pts porque río une ciudad roja incompleta con borde de la grilla
+25 pts porque río une ciudad azul incompleta con borde de la grilla
+15*5 pts por largo del río
Puntaje jugador rojo = 125 pts
Puntaje jugador azul = 0
Está bien esto?

**Comment by cilopez** [comment]
Por la regla **plot-twist** todas las fichas que componen el río serían del jugador rojo, por ende los 15*5 puntos de largo del río son del jugador rojo, al igual que los puntos por ciudad del jugador rojo. Si bien el enunciado no deja en claro si se asigna puntaje base si es otro el dueño de la ciudad (como en este caso) , por lo que puedes dejar en tu *readme* expresado cual si le asignas esos puntos o no. Personalmente no le asignaría los 25 puntos de la ciudad azul.
