### ISSUE TITLE
commit final

### ISSUE THREAD

**Issue by nataliasuarez99** [IIC2233/syllabus#284]
hola!! durante la semana hice varios archivos que subi a gitbhub pero que finalmente no voy a usar (sin querer tambien subi el puntajes.txt y parametros.py etc..), que hago?? lo borro? (nose como borrarlo xd)
Gracias!:-)

**Comment by Tsbalart** [comment]
Hola @nataliasuarez99!
Mueve los archivos que no deseas subir a otra carpeta, (fuera de tu repo), y vuelve a hacer push, luego puedes volver a poner los archivos de vuelta a tu repo, pero ojo con que antes de volver subir archivos a github,  esten en el archivo .gitignore aquellos que no quieres subir.
Saludos! éxito con la tarea!
