### ISSUE TITLE
Uso de for en enunciado T03

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#285]
Hola!

En el punto 8.4 del enunciado de la tarea 3 se presenta el siguiente ejemplo.

<img width="374" alt="screen shot 2017-04-23 at 1 15 51 am" src="https://cloud.githubusercontent.com/assets/11022568/25310841/45841550-27c5-11e7-8167-da506d2523fb.png">

En este código se usa un `for` para iterar sobre `consultas`. ¿Un `for` así está permitido en nuestra tarea? Si es así, ¿por qué?

Muchas gracias!

**Comment by Hernan4444** [comment]
@akaminetzkyp el objetivo de esta tarea es que apliquen funcional y por ello nos interesa que no usen los ciclos for y while en lo que son las **funcionalidades lógicas del programa** pero iterar sobre las consultas para llevarlas a tu programa no es lo esencial de la tarea sino como procesar cada consulta, es por ello que se usó como ejemplo para hacer que se enfoquen en usar la materia en donde nosotros buscamos evaluar.

Espero haber respondido a tu duda.
Saludos!!

**Comment by akaminetzkyp** [comment]
Perfecto, usaré un for similar a ese para iterar sobre las consultas entonces. Los molestaré harto preguntando si algo esta permitido o no. :)

Gracias!

**Comment by akaminetzkyp** [comment]
@Hernan4444, a qué te refieres con **funcionalidades lógicas del programa**?

**Comment by Hernan4444** [comment]
@akaminetzkyp En este caso RQL se encarga de procesar consultas, por lo tanto con **funcionalidades lógicas** nos referimos a  todo lo necesario para que de una consulta salga el resultado (o un error). 

Usando el ejemplo, todo lo que se haga dentro de `procesar_consulta` debe ser sin usar for o while (a no ser que sean en generadores, listas por comprensión o generadores por comprensión)

**Comment by akaminetzkyp** [comment]
Muchas gracias! No la cerraré, entonces.

**Comment by akaminetzkyp** [comment]
Hola!

¿Puedo usar un for para iterar sobre los elementos de una consulta (lista de pocos elementos)? Sería para revisar si tiene consultas anidadas y calcular sus resultados recursivamente.

Saludos!

**Comment by iqacevedo** [comment]
Hola! 
Eso se considera como una funcionalidad lógica del programa, por lo tanto no puedes usar `for` ni `while`, a menos que los utilices como se indica en el punto 7.1.
Saludos !

**Comment by nvielva** [comment]
Se pueden usar fors que iteran sobre generadores? por ejemplo se podría utilizar un código como:
i = [3,23,4,1,54,231,2,4,33,4324,324,324,234]
warnings = (p for p in i)
for p in warnings:
    print(p)

**Comment by sebacruzd** [comment]
@nvielva No puedes hacer eso, sin embargo está la opción de hacer:
`[print(p) for p in warnings]`
O algo por el estilo.

Si quieres hacer cosas más complicadas te recomiendo revisar la materia de funcional, para ver cómo usar map, lambda, etc.

**Comment by nvielva** [comment]
ok ok.. y warnings siempre tiene que ser un generador? cual es la diferencia entre el codigo q me enviaste a el que te mande yo? @sebacruzd 
gracias por la respuesta

**Comment by Hernan4444** [comment]
@nvielva en tu codigo estas itelando de forma directa sobre tu generador, mientras que en el otro código estas usando un generador que realiza una acción sobre otro generador. Y sobre si siempre tiene que ser un generador...imagina que tienes 5.000.000 datos, una lista no podría para tanto mientras que un generador sí gracias a como está implementado.

Saludos!
