### ISSUE TITLE
Locks en QThreads

### ISSUE THREAD

**Issue by furzuadr** [IIC2233/syllabus#285]
Hola! He estado tratando de hacer un thread lock para los QThreads pero no me ha funcionado, probé con QMutex y tampoco. Alguna forma de hacerlo? Gracias!

**Comment by jaromero6** [comment]
Hola!
Respecto a los QMutex encontré esta página de documentación (Si bien está en C, comparte los mismos métodos con el QMutex de Python) en este [link](https://doc.qt.io/qt-5/qmutex.html). No solo explica la documentación sino que además tiene ejemplos de como usar cada método.
Lo otro, en caso de que te siga sin funcionar, exactamente ¿por qué es? ¿Te arroja un error o no se el QMutex no está haciendo lo que esperarías que haga? 
También a modo de sugerencia te recomiendo ver la parte que quieres que entre al Lock que tan ligada está a la interfaz, si es algo muy ajeno como leer un archivo o un ejecutar un cálculo podrías  en un módulo aparte modelar un thread normal con su Lock y simplemente pasar este valor a alguna instancia del backend una vez que el thread termine (**Ojo**, esto solo te servirá si lo que quieres hacer con ese thread es algo muy ajeno a la interfaz, si es algo que va de la mano con la interfaz es mejor que ocupes objetos de PyQt).
Espero que te sea de utilidad

**Comment by furzuadr** [comment]
Gracias! Ya lo pude solucionar, era un error en la forma en que estaba llamando el Mutex.
Gracias!
