### ISSUE TITLE
METODO JOIN

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2233/syllabus#285]
Hola!! Estoy utilizando el metodo join para convertir una lista de strings en un solo string, de la forma: ",".join(lista) , el problema es que reemplaza los espacios vacios de los string por comas tambien, por ejemplo si la lista es ["hola", "como estas","adios"] me retorna:
hola,como,estas,adios  Hay alguna forma de solucionar esto?

**Comment by lily416** [comment]
Hola :)

Si usas `', '` (coma con un espacio) en vez de `','` (la coma sola) debería quedarte `'hola, como estas, adiós'`.

Lo que hace `str.join(iterable)` es tomar la `string` que le pasas y usarla para unir los elementos del `iterable`. Por ejemplo, si hiciéramos:
```python3
lista_dieciocho = ['se viene el 18', 'las empanadas', 'los uyui!']
string_dieciocho = ', se vienen '.join(lista_dieciocho)
print(string_dieciocho)
>> se viene el 18, se vienen las empanadas, se vienen los uyui!
```

Espero te sirva :D
Saludos y éxito en la tarea 👋💪

**Comment by jfuentesg26** [comment]
Gracias!!!
