### ISSUE TITLE
Duda sobre avería de un buque 

### ISSUE THREAD

**Issue by vfibla** [IIC2233/syllabus#285]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

Hola. Mi duda es sobre ¿qué pasa si se avería un buque, solamente no puede avanzar o es como en el caso de encallar y el buque también bloquea el canal?

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by manearaya** [comment]
Hola @vfibla!

Como dice en el enunciado (página 5): "Este evento solo afectará al buque afectado, por lo que el resto de los barcos podrá seguir avanzando sin problemas". Por lo tanto, no es como el caso de encallar porque un buque averiado no bloquea el canal. Solo pasa que el mismo buque deja de avanzar.

Saludos!
