### ISSUE TITLE
Duda de Regar plantas y el archivo

### ISSUE THREAD

**Issue by SebaAgusto** [IIC2233/Syllabus#285]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Buenas, les comento.. El metodo "regar plantas" menciona que debemos aumentarle la vida segun unos parametros aleatorios a todas las plantas del tablero de manera simultanea. Sin embargo tengo una inquietud al momento de querer regarlas y calcular la vida, pues cada planta es diferente y tiene atributos distintos, por ende, una planta "S" es distinta a otra "S", entonces al ver el archivo **plantas.txt** se ve que debemos poner esas plantas en especifico, pero en el archivo de **jardines.txt** hay plantas ya puestas en el tablero, que no coinciden con la cantidad de plantas que hay en el archivo.
Por lo que mi duda es:
Como puedo sumarles la vida a una planta que existe 4 veces en el tablero, pero que en el archivo de plantas solo esta una vez?. adjunto algunas imagenes para mostrar a lo que me refiero.
![WhatsApp Image 2024-09-07 at 21 06 58_a022a84c](https://github.com/user-attachments/assets/341a5e64-a599-4827-bda2-abbbd08cdb1b)
Aqui se muestra un tablero lleno de "solarecillos", pero en el archivo solo existe 1 solarecillo. Entonces como podria regar cada uno para que sean diferentes? o como se que propiedades tiene cada uno si solo existe 1 en el archivo?
Espero que se entienda mi pregunta :)

**Comment by CrisDonosoMaass** [comment]
Hola! Las plantas que salen en plantas.txt son la referencia inicial para crear más plantas en el tablero con los contenidos de OOP, de esta forma cada una tiene sus propios atributos.
