### ISSUE TITLE
como puedo descargar los archivos que subí a mi repositorio privado?

### ISSUE THREAD

**Issue by isvz** [IIC2233/syllabus#285]
Hola, debido a que borres los archivos del pc y quisiera volver a tener los archivos que alguna vez subí al repositorio privado

**Comment by aaossa** [comment]
Hola @isvz , la forma más fácil (que también podría ser la más correcta, dependiendo de lo que quieras hacer) es clonando tu repositorio personal nuevamente (`git clone url_del_repo`). Si necesitas algo más específico que eso, pregunta acá mismo 👌
