### ISSUE TITLE
Comentarios Entregables

### ISSUE THREAD

**Issue by stephichau** [IIC2233/Syllabus#285]
- Deben tener en consideración las operaciones que harán con su estructura de datos para poder elegir la mejor representación. No olviden que para obtener el elemento `N` de una lista ligada, si partes desde el primer nodo, se debe ir nodo por nodo hasta llegar a la meta, es decir, haces `N` operaciones solo para obtener un nodo. Aunque el juego se vea como una matriz, analicen las ventajas y desventajas de usar esa al momento de:
 1. Buscar un nodo de los contornos.
 2. Seguir un camino.
 3. Verificar los alrededores de un nodo.

- No olviden que uno de los objetivos es **crear y usar algoritmos eficientes para recorrer las estructuras creadas**.

- Si quieren implementar una estructura de datos que se asemeje a un diccionario, recomendamos investigar sobre las `Tablas Hash` y cómo funcionan.

- Para hacer toda la tarea, deben implementar más de una estructura. Intenten darle una vuelta sobre qué estructuras podrían ser las más adecuadas para implementar en las distintas partes de la tarea.

- Existen más estructuras de datos que pueden implementar a parte de listas. 
- No olvidar los requisitos mínimos pedidos en el enunciado para sus estructuras de datos. Aunque no los vean necesarios, sí son requisitos.
- Pueden (y es la idea) que creen estructuras propias, distintas a las del material y no convencionales para poder adaptarlas mejor a su tarea. Piensen más allá de las estructuras built-in de python, sean creativos y busquen la mejor manera de representar el problema a través de su estructura.
- Hay algunas funciones del enunciado que se piden para que implementen una estructura de datos específica. Analicen mejor este último para ver en qué lugar deben usar qué estructura.
- Para guardar los estados pueden crear sus propias formas de guardar y cargar información. No se compliquen en esto y hagan una forma fácil y funcional.
- Cuando les pedimos entregar un esquema de su tarea, deben incluir todas las estructuras y clases que tengan en su programa. En este caso también debían poner las estructuras de datos creadas por ustedes.
- Una manera fácil de hacer diccionarios con la materia vista es aplicar utilizar árboles binarios para buscar la key a medida que bajaba por las ramas de este, usando el orden alfabético de la key y después trabajarlo como un arbol de busqueda.

- Uno de los beneficios de crear sus propias EDDs es que son totalmente customizables, es decir, se pueden comportar como ustedes quieran, usen esto a su favor pero siempre respetando las restricciones del enunciado.

- Las listas ligadas son muy útiles, pero recuerden que el tablero no es lineal, es decir, aparte de tener vecinos a ambos lados, tienen en otras 4 direcciones. Piensen en una estructura que les facilite la interacción con todos los vecinos de una pieza. 

- Para deshacer jugadas, es importante que vayan guardando la jugada que se va haciendo. Hay una estructura que debería ser muy intuitiva si lo que queremos es ir obteniendo siempre la última jugada que se hizo.
- Recuerden que sus EDD’s son simplemente clases, y por lo tanto se pueden heredar y crear nuevas estructuras más personalizadas.
- Creatividad ante todo. La gran idea de las estructuras en esta tarea es que te faciliten todo. Hacer solo una estructura, como ListaLigada y adaptarla para las diferentes tareas que suceden en tu programa no es una buena idea. Aprovechen las gracias de Python e intenten crear algo que realmente les sirva, no se guíen por lo más fácil. Si aún insisten en usar solo ListaLigada, recuerden que pueden heredar de ella para utilizarla para diferentes fines, esto es mucho más ordenado que en una sola clase agregar todos los métodos que se te ocurran.

- Las estructuras que ustedes creen deben pensarlas de tal manera de que faciliten su labor, es decir que sean específicas para este problema que están resolviendo ahora. No sirve mucho que intenten emular una estructura de python si ello va a significar que tienen que hacer miles de operaciones para realizar lo que se pide en la tarea, así que aprovechen la estructura que sea la óptima PARA ESTE PROBLEMA.
- Los métodos que pedimos que deben tener las estructuras (sección master) les va a facilitar trabajar con sus estructuras de una manera mucho más intuitiva y fácil, así que utilizarlos mientras están definiendo los mismos otros métodos de su estructura.
Aprovechen que ustedes hacen sus propias estructuras para hacerlas a la medida de lo que necesitan. No tienen por qué ser pauteadas de como se vieron en clases. Por la misma razón el uso de diferentes estructuras para cada parte es de gran utilidad! Recuerden modelar todo bien antes de lanzarse con algo a programar.

**Comment by rihanuch** [comment]
En ninguna parte del enunciado sale que se *debe* implementar mas de una estructura 🙄

**Comment by cilopez** [comment]
@rihanuch El objetivo de la tarea dice (*que es lo primero que sale en la tarea*): 
* Aplicar conceptos y nociones de estructuras de datos para el  _**correcto modelamiento del problema**_
* _**Crear y usar algoritmos eficientes**_ para recorrer las estructuras creadas

**Comment by matiaseche** [comment]
Hola, se agradece el feedback que nos hacen! 
Quizás es mucho pedir, pero sería ideal si para futuras tareas estos feedbacks se pudiesen dar antes, ya que a estas alturas, por lo menos yo (y supongo que la mayoría), ya tiene sus EDDs hechas (sean una o mas) y no tienen el tiempo para ponerse "creativos" y cambiar el modelamiento siendo que la **entrega es en 3 días**. A estas alturas no me queda mas que conformarme con lo que tengo y usar estos días para afinar detalles, avanzar en otras entregas y preparar pruebas para otros ramos.
De nuevo, gracias.

**Comment by rihanuch** [comment]
@cilopez lo entiendo perfectamente y lo aprecio, pero eso no cambia lo que esta hecho, al final como dije antes, es mejor ser claro del comienzo con margenes bien delimitados 🙃
"correcto" es bien vago... sumar 1+1=2 que es lo mismo que -1+3=2. Simpemente son formas distintas de ver el problema. Respecto a lo de los algoritmos eficientes tampoco me queda muy claro que es eficiente...
De verdad lo digo por todossss ❤️🤓💻

**Comment by cilopez** [comment]
@rihanuch ya se converso esto en la tarea anterior, te recomiendo leer la issue #131 donde el profesor aclara esta situación.  ¡Saludos!
