### ISSUE TITLE
Semana 11, ejercicio propuesto 1.1

### ISSUE THREAD

**Issue by Francisco-Aguilera-xd** [IIC2233/Syllabus#286]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola!
No entiendo muy bien como se realiza este ejercicio, porque se nos pide que a partir de un chunk de 8 bytes, se saque una lista de número. Revisando el jupyter de contenidos de la semana, no encuentro ningun comando que convierta los bytes a enteros como una lista. En la ayudantía de hoy una ayudante usó el comando ```int.from_bytes``` pero este entregaba solo un número, por lo que tampoco cacho como lograr obtener 8 números separados. ¿Alguna ayuda de como se hace este ejercicio?
Gracias de antemano

**Comment by carmebe** [comment]
Hola, no sé a qué te refieres con convertir los bytes a enteros como una lista, lo único que se te pide en ese ejercicio es obtener los *chunks* de 8 bytes, eliminar todos los valores  que sean máximos del *chunk* (puedes intentarlo con un *while*) y reconstruir el archivo agregándolos a un *bytearray*, tal como se había visto en los contenidos. Recuerda que puedes utilizar los métodos de listas o *strings* con los *bytearrays* también (ver su máximo, extenderlas, obtener su índice, etc.)

Espero que te haya servido, saludos!

**Comment by carmebe** [comment]
Hola, si te interesa ver esos valores como una lista de números, los cuales es opcional, prueba a usar print  en el *for* para obtener los *chunks* de esta manera:
```python
print([byte for byte in chunk])
```
Con opcional me refiero a que no necesitas trabajar con estos números, ya que puedes encontrar el máximo de un *bytearray* también.

**Comment by try-except** [comment]
Hola! Esos hexadecimales que te aparecen sí son números, solo que en su representación hexadecimal. Cuando lees un archivo en modo *read bytes* (con `rb` en el `open`), el método `read()` retorna un string de bytes, que puedes identificar por esa `b` al inicio del string. Una vez obtenido el string de bytes, puedes iterar sobre él en chunks.

Es fácil confundirse cuando aparecen los hexadecimales, pero recuerda que cada *byte* está compuesto por 8 *bits*, osea que imprimir 10 *bytes* resultaría en 80 caracteres, así que como un archivo está compuesto por muchos *bytes*, imprimir cada uno de los *bits* sería larguísimo y muy incómodo. Para evitar llenar tu terminal de 1 y 0, se usa la representación hexadecimal, que no es más que una forma un poco más compacta de representar lo mismo.

**Comment by carmebe** [comment]
Los \xba, \xfb, etc. son representaciones hexadecimales de números, puedes intentar lo siguiente para comprobarlo:
```python
num = b'\xba'
print(int.from_bytes(num, byteorder="little"))  # big también sirve
```

**Comment by try-except** [comment]
> Entonces en los bytes cada "caracter" es un haxadecimal?.

Un byte es un conjunto de 8 bits, por ejemplo:
```
10010110
```
Los bits son de base 2, es decir que cada dígito representa una potencia de 2, el `byte` anterior es equivalente al número 150 en base 10 ¿Te fijas que usé solo 3 dígitos en base 10 para representar exactamente lo mismo? Hay formas más compactas de representar el mismo número, como por ejemplo el hexadecimal, que usa base 16. El único objetivo de representar en base 16 es hacer más legibles los bytes del archivo. Para lograr tener 16 dígitos posibles, usamos los números de 0-9 y las letras de la "a" a la "f", por eso aparecen las letras. Python indica que el número que está mostrando es un hexadecimal con el prefijo `\x`, lo que sigue al prefijo es realmente el número.

A modo de ejemplo, el hexadecimal `\xfe` es igual a 254:
```
f = 15, e = 14
16^1 * 15 + 16^0 * 14 = 240 + 14 = 254
```
Te recomiendo no enredarte demasiado con los hexadecimales porque al final del día python se encarga de manejarlos por ti en la mayoría de los casos, piensalos como una representación más compacta solamente :)

**Comment by Francisco-Aguilera-xd** [comment]
Ahhhh ya, ahora me queda mucho más claro. Muchísimas gracias a ambos.
