### ISSUE TITLE
Cambio de funciones pre-entrega

### ISSUE THREAD

**Issue by CrisHD935** [IIC2233/Syllabus#286]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, queria saber si al usar las funciones de cliente y servidor que hicimos para la preentrega en la entrega final si al copiar estas funciones puedo modificarlas para acomodarlas al programa actual, dado que estas funciones no consideraban muchas cosas que deben hacerse para la entrega final.

**Comment by ignacio-sp** [comment]
Hola @CrisHD935! Pueden realizar cambios a las funciones para la entrega final, siempre y cuando cumplan su propósito inicial y no se modifique aquello indicado en el enunciado, saludos!

**Comment by sguridirt** [comment]
¿Qué implicar no modificar aquello indicado en el enunciado?¿No se pueden cambiar sus parámetros para adecuarlos a nuestro código?

**Comment by ignacio-sp** [comment]
Hola, me disculpo por lo anterior, no consideren lo que mencioné del enunciado, pueden cambiar las funciones ajustándolas a su programa como prefieran!
