### ISSUE TITLE
Problemas con un emit 

### ISSUE THREAD

**Issue by LunaGarces** [IIC2233/Syllabus#286]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Tengo un emir que no esta enviando correctamente al señal dentro de mis clase Soles_c, llega hasta el emit, pero este no se conecta con la función de mi front-end remote_sol 
si me pudieran ayudar lo agradecería.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Hernan4444** [comment]
Hola @LunaGarces 

Revisé el código y el tema es que la señal si se emite correctamente (si pones un `print` en la función objetivo, si se imprime). El tema es otro >.<

En tu código tiene 2 veces `self.juego.senal_aparecer_sol.connect(....)`. Esto hace que cuando la señal  `senal_aparecer_sol` se emita, se ejecute 2 veces la función objetivo. ¿Qué pasa con eso? es que para cada sol que aparece, se generan 2 `QLabel`. Una que guardas en tu dict y otro que no se guarda. Es ese otro sol (el que no se guarda) que luego no puedes eliminar. En tu `main.py` revisa donde tienes 2 veces `self.juego.senal_aparecer_sol.connect(...)` y elimina 1. Ahí podrás notar que la función objetivo para remover soles funcionará bien.

Ante cualquier duda, estaremos atentos al foro,
Saludosヾ(＾-＾)ノ
