### ISSUE TITLE
Porcentaje de los eventos

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#286]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas. Tengo una duda respecto a como usar los porcentajes que nos entregan en "eventos.txt". No sé si debemos elegir nosotros como utilizaremos estos números para que finalmente los eventos sucedan o no? o debemos seguir alguna instrucción para implementar un sistema que reciba estos porcentajes y nos diga si el evento sucederá?

**Comment by mmleivad** [comment]
Hola se puede asumir que los eventos con sus probabilidades que vendran en el archivo, siempre vendrán en el orden Z y luego H?

**Comment by CatalinaBO** [comment]
Hola! No se puede asumir.
