### ISSUE TITLE
Clase abstracta sin métodos

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#286]
Hola,
Tengo algunas clases que cumplen las características de una clase abstracta (es decir, que no deben ser instanciadas), pero no tienen métodos, por lo que para hacerla clase abstracta tendría que aplicar el @ abstractmethod en el __init__ de la clase.
Sería esto una buena idea o aplicar el @ abstractmethod sobre un __init__ no tiene sentido?

**Comment by jmwielandt** [comment]
Hola! 😄 

Recuerda que si tienes una clase sin métodos es muy posible que no deba ser una clase como tal, sino una estructura de datos.

En la tarea no debería darse el caso en que las hijas de una clase no tengan métodos comunes entre ellas, por lo que estos tendrían que estar en tu clase abstracta como _abstract methods_. Y si no los tienen, quizás no deberían estar heredando de la misma clase.

Para que una clase sea verdaderamente abstracta, entre otras cosas, no debe ser instanciable. Para esto debes poner el decorador `@abstractmethod` en el `__init__` de la clase.

A continuación te dejo un código para que pruebes 😉
```python3
from abc import ABCMeta, abstractmethod


class A(metaclass=ABCMeta):

    @abstractmethod
    def __init__(self, n):
        self.n = n


class B(A):

    def __init__(self, n, otro):
        super().__init__(n)
        self.otro = otro


if __name__ == '__main__':
    # a = A(3)
    # print(a.__dict__)
    b = B(2, 3)
    print(b.__dict__)
```

- Si instancias `B`, debería funcionar correctamente, pero si intentas instanciar `A` el programa se debería caer.
- En cambio si comentas el `@abstractmethod` deberias poder instanciar `A`, por lo que en ese caso `A` no sería una verdadera clase abstracta.


Saludos y ánimo con lo que queda~ 👍

**Comment by FelipeA7** [comment]
@jmwielandt gracias!
otra cosa, digamos que en el ejemplo que tú me diste existiera una tercera clase "C" que también heredara de A. Además, digamos que A tuviera un método llamado "dibujar" que sería el MISMO para B y para C. 
Entonces tendría lógica que solo usara el `@abstractmethod` para el __init__ de A y que el método dibujar() lo dejara como método normal, puesto que sería el mismo para B y C?
O quizás sería mejor dejar dibujar() como `@abstractmethod` y luego redefinirlo en las clases que lo heredan?

**Comment by jmwielandt** [comment]
Hola!

Los _abstract methods_ más allá del `__init__` tienen como objetivo declarar una interfaz que todas las clases hijas deben implementar, por eso tira error cuando una clase hija no lo implementa.

Si los métodos o atributos no difieren entre ellas, para evitar código duplicado tiene sentido que se implementen en la clase padre directamente y no como método abstracto.

Saludos 😄
