### ISSUE TITLE
Uso de split al leer archivo csv

### ISSUE THREAD

**Issue by mblejeune** [IIC2233/Syllabus#286]
Hola, tengo una duda muy grande! al momento de leer la base de datos, lo hago de la misma forma que la tarea 1:

- with open (...) as file:

- for line in file:

- atributos separados por coma = le hago strip y split(",") \

- en esta siguiente linea defino una instancia de una clase que tiene todos los atributos (atributos de la linea anterior)

- acá agrego la instancia que se creo en la linea anterior a mi estructura de datos, es decir, agrego un objeto a mi estructura de datos propia

Mi pregunta es si es legal hacer esto? porque al final no agrego ninguna estructura de datos prohibida a mi estructura de datos propia, solo agrego un objeto(instancia de la clase).

Y si es que sí se puede y es legal hacer lo anterior, al leer el archivo puedo comparar altiro afinidades usando la instancia.nacionalidad == other.nacionalidad, por ejemplo, o haciendo dos lecturas del archivo (de la forma en explicada anteriormente) para comparar y al final agregar un objeto a mi estructura de datos ?
Gracias!!

**Comment by IchottMano** [comment]
Respondido en #174
