### ISSUE TITLE
¿Se pueden crear entidades extra? Y duda sobre límite de líneas

### ISSUE THREAD

**Issue by constanzavicencio** [IIC2233/Syllabus#286]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, no había visto en el enunciado que los combates debían ser gestionados desde el método `combatir` en la entidad Ejército, por lo que hice distintas entidades para gestionarlo (Enfrentamiento, Ronda y Combate, siendo la última la que al llamarla produce el combate completo solicitado). Entiendo que por enunciado debo integrar Combate en el método `combatir` Ejército, pero estaría permitido mantener las entidades "auxiliares" Enfrentamiento y Ronda para hacerlo? En el enunciado se aclara que hay 3 entidades base mínima, pero no especifica si podemos crear otras :(

Por otra parte, si mi código tiene más de 400 líneas directamente no se corrige? O solo implica descuento? Lo tengo modularizado y todo pero no me es posible reducirlo más

Gracias!

**Comment by mon-b** [comment]
Hola Constanza! Puedes crear todas las clases que estimes convenientes :). 

Además la tarea se corrige aún con tu archivo de más de 400 líneas, pero **sí implica un descuento**.
