### ISSUE TITLE
Nueva ventana el preparar partida?

### ISSUE THREAD

**Issue by juanpacl111** [IIC2233/syllabus#286]
Está permitido crear una nueva ventana para preparar la partida o es necesario utilizar la misma durante todo el juego?

**Comment by roberto009** [comment]
Hola! 
En tu juego deben existir dos tipos de ventana:
1. *Ventana de inicio*
2. *Ventana de juego*

Para cumplir los requisitos de la *ventana de inicio* puedes crear varias. Por ejemplo una que pida la sesión, otra que elija el bando y tenga la opción jugar.

Es **importante** eso si, que la *Ventana de juego* sea **una** ventana en la que se haga tanto la preparación de la ronda, como el inicio de esta con el botón *"Empezar ronda". Esto no debería complicar mucho la modelación de esta ventana, ya que, puedes hacer que al apretar el botón *Empezar ronda*  comiencen todas las acciones del juego sin necesidad de cambiar de ventana. 

Cualquier duda me avisas!
Éxito con la tarea 😃
