### ISSUE TITLE
Duda movimiento de los barcos

### ISSUE THREAD

**Issue by vfibla** [IIC2233/syllabus#286]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
Hola, mi duda es que ¿si es posible que un barco adelante a otro o los barcos tienen que salir y entrar en el orden de llegada?
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by santiagovegaf** [comment]
Hola @vfibla!

Al avanzar los barcos con diferentes velocidades es posible que los más rápidos adelanten a otros que se mueven más lento.

Espero esto responda tu duda!
