### ISSUE TITLE
Parámetros de mi función exceden 100 líneas

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2233/syllabus#286]
Holaaa,
Quería consultar si el trozo de código de a continuación se considera mala práctica:
```Python
bomba_atacada = desicion_bomba(bomba_a_usar, bombas_especiales, atacadas, 
dimensiones, intento)
```
Cabe señalar que no me alcanzan los 100 caracteres porque esta dentro de un ciclo. En este caso quería saber si esta bien como lo puse o se considera mala práctica.

**Comment by matiasmasjuan** [comment]
Hola @Mamunoz42 !

**No**, **no** se considera una **mala práctica** ya que buscas impedir que se sobrepasen los 100 **caracteres** dentro de la misma línea. Por lo tanto, **sí** está permitido.

Por otra parte, puedes basarte en la siguiente **Issue** donde se dieron algunos **ejemplos**: #181 

Saludos! :smile:

**Comment by Mamunoz42** [comment]
Muchas graciaaaas 😄
