### ISSUE TITLE
Ordenar listaligada

### ISSUE THREAD

**Issue by benjadb** [IIC2233/Syllabus#287]
Es legal para ordenar mi listaligada, aplicar sorted (el que viene en python) sobre el iterador de mi listaligada y despues recorrer la lista (normal) que eso me retorne, e ir appendeando esos elementos a una listaligada.
Alfinal la duda es si es legal recorrer la lista que me retorna el sorted aunque nunca la use y le pase esos elementos a mi listaligada

**Comment by monicabelen** [comment]
Hola, no es legal manipular listas, por lo tanto, no puedes hacer lo que indicas. Lo que sí puedes hacer es  implementar tu propio método sort.
