### ISSUE TITLE
Obtener Pieza actual del GUI

### ISSUE THREAD

**Issue by ajahr95** [IIC2233/Syllabus#287]
Cuando se inicia el demo se obtiene directamente una nueva pieza y al agregar una pieza se esta llamando a colocar_pieza de MyInterface lo que al mismo tiempo llama a gui.add_piece(i,j) y gui.nueva_pieza(). Mi duda es como obtengo el string con el tipo de pieza que se esta jugando cuando abro el demo( y cuando se llama a gui.nueva_pieza() nuevamente al colocar una pieza) para asi poder trabajar en mi programa con este dato.

**Comment by iqacevedo** [comment]
Hola,

Basta con que cargues una pieza nueva que tu si conozcas y comiences con esa. No te puedo decir más, suerte en la tarea !

Saludos !

**Comment by ajahr95** [comment]
Pero especificamente respecto a la nueva pieza, esta se genera porque gui.init() llama a __game.initUi() y esta tiene como atributo un self.new_piece(), lo que de acuerdo a la funcion new_piece seleccionará un tipo de pieza aleatorio y un color aleatorio. Mi punto es que si no podemos alterar el gui, como puedo obtener esa información de la primera pieza siendo que se genera aletoriamente al llamar a la funcion gui.init().

**Comment by iqacevedo** [comment]
@ajahr95 si te fijas en mi respuesta anterior te di la respuesta de cómo hacerlo, no necesitas editar nada de la gui para conseguir lo que quieres.

Saludos !

**Comment by ajahr95** [comment]
Lo entendi, gracias
