### ISSUE TITLE
Cosas permitidas T00

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2233/syllabus#287]
Holaa, 
Quería consultar si la función `lamba` la puedo utilizar para ordenar el `.txt` del ranking?

**Comment by matiasmasjuan** [comment]
Hola @Mamunoz42 !
.
Recuerda que existe una sección para preguntar sobre **Librerías permitidas, no permitidas y malas prácticas** aquí #87. Veo que ya preguntaste, asi que porfavor no abras otra **Issue** con lo mismo.

Saludos! :smile:
