### ISSUE TITLE
if __name__ = "__main__"

### ISSUE THREAD

**Issue by jnbaltra** [IIC2233/syllabus#287]
Que significa if `__name__ = "__main__"` ? 
Lo he leído en muchisimos códigos, luego de eso llaman a la funciones que corren el  programa.

**Comment by KnowYourselves** [comment]
Hola @jnbaltra!

Un problema con _Python_ es que cuando importas un archivo **se ejecuta todo su contenido**. Esto quiere decir que si importas un archivo y este tiene _prints_, llamados a funciones u otras cosas, todo eso se va a ejecutar.

Para nuestra suerte _Python_ posee una variable llamada `__name__` que nos dice cual es el nombre del archivo ejecutado. La gracia de esto es que cuando se ejecuta un archivo desde la consola de comandos su nombre va a ser `__main__` mientras que todos los archivos que este importe **van a tener otro nombre**.

Esto quiere decir que para evitar que se ejecute código no deseado, después de definir las funciones y clases de un código, otro código misceláneo se pone dentro de ese _if_ que lo que hace es chequear si efectivamente el archivo que fue ejecutado en consola.

Una gracia de esto es que si por ejemplo tu tienes 3 archivos en tu carpeta y quieres hacer pruebas en uno de estos, puedes hacer todas estas después de este _if_, luego cuando ejecutes tu archivo principal estás no se van a ejecutar por lo mismo que te acabo de decir.

Esppero se haya entendido!

**Comment by aaossa** [comment]
Para complementar la súper respuesta de @KnowYourselves :sparkles: , puedes revisar el *notebook* de modularización, correspondiente a la semana 0 de los contenidos ([click aquí](https://github.com/IIC2233/contenidos/blob/master/semana-00/2-modularizaci%C3%B3n.ipynb)) 🤓
