### ISSUE TITLE
Flujo del programa

### ISSUE THREAD

**Issue by barbaracalderonr** [IIC2233/syllabus#287]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X]  Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X]  Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X]  Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X]  Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X]  De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holaa, tengo una duda respecto al flujo del programa, en el enunciado dice que se acaba una vez que no le queda dinero al canal. Esta acción de revisar el dinero, se debe hacer al término de simular una hora, o cada vez que se hagan transacciones?
Es decir, si el canal debe pagar al barco su costo de mantención, y se queda sin dinero, sigue el programa hasta que se acabe la hora, o debe finalizarse en ese mismo instante?

**Comment by DomingoCarvajal** [comment]
Hola @barbaracalderonr.

Como sale en el enunciado, el programa debe acabar automáticamente cuando los fondos lleguen a 0.
