### ISSUE TITLE
PyQt5

### ISSUE THREAD

**Issue by maxfreymo** [IIC2233/Syllabus#287]
Al correr el programa me aparece que el módulo PyQt5 No existe.

¿Debo descargar PyQt5 de internet para usarlo en mi pc? 
Si es así, una vez descargado ¿qué debo hacer para poder importarlo al programa y que corra? 

De lo contrario, ¿Qué hago?

**Comment by stephichau** [comment]
Hola! 
Debes descargar el módulo. [Aquí puedes descargar PyQt5](http://pyqt.sourceforge.net/Docs/PyQt5/installation.html)

**Comment by maxfreymo** [comment]
Ya lo descargue @stephichau pero aún así no me funciona. Coloque la carpeta del PyQt5 (después de descomprimir el zip) en la de T03 pero tampoco me funciona :(

**Comment by iqacevedo** [comment]
Hola !
Probaste siguiendo los pasos que aparecen en wiki?
https://github.com/IIC2233/Syllabus/wiki/Software-Obligatorio

**Comment by Dunkan1** [comment]
intenta con pip install PyQt5

**Comment by maxfreymo** [comment]
Gracias !! :D

**Comment by nvielva** [comment]
¿Como puedo instalar el PyQt5 en anaconda? En mi computador tengo instalado python 3.5 y anaconda por separado, ya agregue PyQt5 en python 3.5, pero me saldría mas comodo usar anaconda..

**Comment by flobarrios** [comment]
@nvielva probaste con 
[`conda install -c dsdale24 pyqt5=5.3.2`](https://anaconda.org/dsdale24/pyqt5)

**Comment by nvielva** [comment]
Si habia tratado.. me muestra este error:
PackageNotFoundError: Package missing in current osx-64 channels: 
  - pyqt5 5.3.2*

**Comment by nvielva** [comment]
tambien trate con este
conda install -c https://conda.anaconda.org/mmcauliffe pyqt5
pero me tira este error:
UnsatisfiableError: The following specifications were found to be in conflict:
  - pyqt5 -> python 2.7*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

**Comment by Minjor** [comment]
Tuve muchos problemas para lograr instalar PyQt5 así que buscando encontré un exe que me sirvió pero es de la version 5.6, esta bien? https://sourceforge.net/projects/pyqt/files/PyQt5/ ahí esta y se llama "PyQt5-5.6-gpl-Py3.5-Qt5.6.0-x32-2.exe". Sirve esa version/archivo? Hasta ahora no he tenido mas problemas.
