### ISSUE TITLE
Duda sobre variables globales

### ISSUE THREAD

**Issue by elshavi** [IIC2233/Syllabus#287]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

No entendí muy bien el tema de las variables globales y quería saber si el siguiente caso se considera como tal, y por lo tanto mala práctica.
El archivo a ejecutar en mi tarea es el main.py, en el cual al principio de este defino lo siguiente:
`ejercito = Ejercito(oro = oro_inicial)
ronda_actual = 1`

Esto para instanciar un objeto de la clase ejercito, y un contador con la ronda actual, el cual irá cambiando si el usuario gana una ronda.
Se considera mala práctica? muchas gracias

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mon-b** [comment]
Hola! El uso de variables globales es considerado una mala práctica. En el caso de tu código, ambas variables son globales, por lo que **sí serían consideradas malas prácticas.** En general, para evitar las variables globales es recomendable encapsular tu código haciendo uso de funciones y/o clases :)

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Tengo una duda similar, por ejemplo si para el ingreso de la dificultad tengo una lista del estilo dificultades_validas = ["facil", "intermedio", "dificil"] y para revisar que el input sea válido tengo algo como if input_usuario in dificultades_validas, la variable dificultades_validas sería también una variable global y por ende una mala práctica?

**Comment by elshavi** [comment]
@VicenteIgnacioSotoGonzalez según lo que yo entendí, es que si tu variable está fuera de una función o clase, se considera global.
