### ISSUE TITLE
Valor de personalidad para los pilotos Hibridos 

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#287]
Ya que debemos darle un valor a la personalidad de cada equipo en el diccionario de `parametros.py` pensé que lo mejor sería poner `choice(['osado', 'precavido'])`, el problema es que esto se define una vez se importa el módulo entonces todos los Hibridos tienen la misma personalidad. Lo otro que podría hacer es controlar el valor dentro de la clase `Piloto` pero quizás el manejo de los parametros se requiere que sea de otra forma. Como hay que hacer? Saludos

**Comment by RositaMunoz** [comment]
Hola!
No te puedo decir cómo hay que hacerlo, porque tú eres el que modela tu tarea :sweat_smile:  
Si tienes problemas con que al importar tus parámetros, los híbridos siempre quedan con la misma personalidad, entonces ahí al algo raro que no va de acuerdo al enunciado.
Si quieres controlar la elección de personalidad dentro de tu clase, puedes encontrar una forma en que se importen tus opciones de personalidad y luego las manejes a tu gusto. Así no tendrías el problema con el manejo de parámetros.

Espero haber ayudado.

Ánimo con lo que queda de tarea!
