### ISSUE TITLE
QtDesigner

### ISSUE THREAD

**Issue by plourido** [IIC2233/Syllabus#287]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido

Hola, espero que se encuentren bien y hayan tenido una buena semana de receso. Les escribo para consultarles si es necesario para la tarea 2 utilizar QTdesigner?
Muchas gracias

**Comment by Hernan4444** [comment]
Hola @plourido 

Esperando que tambien tuvieras una excelente semana de receso, históricamente no ha sido una exigencia utilizar QTdesigner en las tareas, y este semestre tampoco cambiaremos esa tradición 😅. La tarea se puede hacer totalmente sin necesitar de QTdesigner.

Saludosヾ(＾-＾)ノ

**Comment by plourido** [comment]
Perfecto, muchas gracias :)
