### ISSUE TITLE
Uso de * con parametros.py

### ISSUE THREAD

**Issue by MTGG123** [IIC2233/Syllabus#287]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

A la hora de importar los parámetros de parametros.py, estaría bien usar "from parámetros import *"? Se que el uso de * es una mala practica a la hora de importar módulos, pero en este caso, que sabemos la cantidad de cosas que se importarían, estaría permitido hacerlo?

**Comment by augustayanez** [comment]
El uso de * para importar es una mala práctica, por lo que a pesar de saber que es lo que importarías de parametros.py seguiría siendo una mala práctica usarlo.
