### ISSUE TITLE
La base siempre sera de 2x2?

### ISSUE THREAD

**Issue by tomascortes** [IIC2233/syllabus#287]
Hola, puedo asumir que la base siempre correspoderá a un espacio de 2x2 pixeles? ya que así está en los mapas dados.
Gracias

**Comment by hbkim94** [comment]
Hola @tomascortes ,

Suponiendo que te refieres a que la base toma 2 x 2 casillas, entonces sí, siempre será así.

Suerte con la tarea!

**Comment by tomascortes** [comment]
gracias!
