### ISSUE TITLE
Semana 12 - 2. Networking con python

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#287]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Estoy intentando entender la materia de Networking. Copié y pegué códigos de la materia, como estaba sugerido, para ver qué pasaba. 
Tengo en una carpeta 'servidor'
```python
import socket

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Así podemos obtener el hostname de la máquina actual
host = socket.gethostname()
port = 9000

sock.bind((host, port))
sock.listen()

counter = 0
while counter < 5:
    try:
        socket_cliente, address = sock.accept()
        print("Conexión aceptada desde", address)
        socket_cliente.sendall("Gracias por conectarte\n".encode("utf-8"))
        socket_cliente.close()
        counter += 1
    except ConnectionError:
        print("Ocurrió un error.")

sock.close()

Y en otra carpeta 'cliente'
import socket

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Obtenemos el nombre de la máquina a la que nos queremos conectar
# En este caso, nos queremos conectar a esta misma máquina
host = socket.gethostname()
port = 9000

try:
    sock.connect((host, port))
    data = sock.recv(4096)
    print(data.decode("utf-8"))
except ConnectionError as e:
    print("[Cliente] Ocurrió un error")
finally:
    sock.close() 
```
Desde la terminal corrí clientes.py, pero me sale el error 
```
Traceback (most recent call last):
  File "cliente.py", line 11, in <module>
    sock.connect((host, port))
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

Como no entiendo muy bien como funciona networking ni qué exactamente hace este código, además de conectar un host con port con otro,  me gustaría preguntar de qué se trata ese código y si hice algo mal para que tire error.

**Comment by carmebe** [comment]
Hola, por lo que yo he visto (en StackOverflow), los errores del tipo ``socket.gaierror`` ocurren cuando tu *host* y *port* no están bien definidos, y lo único que podría estar pasando es que al utilizar el método ``socket.gethostname()`` el *host* retornado no concuerda. Intenta usar ``print()`` para ver lo que te entrega y revisa si a lo mejor tienes algún problema con tu red (firewall, VPN, etc.).

Espero que te haya servido, saludos!

**Comment by Christian-Klempau** [comment]
Te recomiendo probar usando `host = "localhost"` directamente, para tratar de solucionarlo :)

**Comment by Fernanda1232123** [comment]
gracias, me funcionó!
