### ISSUE TITLE
Consulta de cuando crear los otros equipos

### ISSUE THREAD

**Issue by AlexanderBarrera** [IIC2233/Syllabus#288]
Hola.
En el enunciado, punto 4.2.1, se indica que los otros equipos del programa se deben crear luego de que se finalice de crear el equipo propio, pero no hay forma de que en demo se sepa que se terminó de setear el equipo del jugador. ¿Es posible que una solucion a esto sea crear los equipos antes que el jugador, con jugadores no dentro de los 200, o dentro de los 200, y no mostrandolos para que sean seleccionados?

**Comment by mora4** [comment]
Tengo la misma duda, ¿cuando sabemos que ya se terminó de crear el equipo del usuario?
Tampoco me queda claro si podemos modificar la lista de equipos que viene para cambiar las esperanzas en el demo.

**Comment by felipe8797** [comment]
Comento para saber

**Comment by akrebs2** [comment]
Por favor responder!

**Comment by FernandoPieressa** [comment]
Hola! Si se puede hacer lo que dices! Eso si, también podrías calcularlo cuando pones las estadísticas del campeonato, y haces que internamente ese botón te cree los equipos Y simule todos los partidos al mismo tiempo.

**Comment by ljrodriguez1** [comment]
Y puedo crear los quince equipos al presionar al azar?, yo lo tengo hecho asi, el unico problema es que en la ventana de equipos, los equipos que salen tienen una esperanza que no les corresponde

**Comment by joaquineichholz** [comment]
Tengo el mismo problema, no se como cambiar las afinidades de la gui, hasta ahora cambio el valor de la lista equipos que lee la gui pero aun asi no cambian los valores en la interfaz, creo que la gui los lee una vez y los guarda entonces al cambiarlos no pasa nada
