### ISSUE TITLE
Duda con respecto a extensión de archivo asociado a qtdesigner

### ISSUE THREAD

**Issue by gabo1243** [IIC2233/Syllabus#288]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, para que se cargaran las imágenes de forma correcta utilicé un archivo imagenes.qrc, pero para que funcionara tuve que pasarlo a python con un comando. El archivo quedó como ```imagenes_rc.py``` y me funcionan las imágenes dentro de las ventanas. El problema es que el archivo  ```imagenes_rc.py``` excede las 27000 líneas (XD). Lo uso porque era la única forma que podía de ocupar las imágenes sin poner paths absolutos (si ponía paths relativos en qtdesigner no me tomaba las imágenes si lo hacia como file, entonces las seleccione como resource) Mi pregunta es ¿puedo dejarlo así? Por que en el caso de no poder, no podría poner bien las imagenes sin ocupar paths absolutos.

En mi repositorio personal (T2) se puede ver como quedó. En caso de no poder dejarlo así. ¿Qué podria hacer para no usar paths absolutos y que las imagenes se importen bien? (usandolas como resource)

Gracias de antemano

**Comment by gabo1243** [comment]
Hola, lo que pasa es que para mostrarlo bien ocupé el archivo ```imagenes.qrc```, que de por sí no funcionaba bien, por lo que busqué en internet y encontré un comando (que ejecuté en la consola) que me creó el archivo ```imagenes_rc.py```, con el cual se muestran perfectamente todas la imagenes. El problema es que este último archivo excede por mucho las 400 lineas y no se si me van a descontar por eso. 

Gracias de antemano

**Comment by PedroDP99** [comment]
@gabo1243 
A lo que voy es que quizás no necesitas utilizar ```imagenes.qrc``` ni ```imagenes_rc.py``` . Ya que en otras partes del código si te funcionaron los paths relativos, por lo que es extraño que para ciertos sprites no te funcione. Por eso te pido que des más detalles de los problemas (que sprites fueron, en que situación, en que archivos, etc.). 
Saludos!

**Comment by gabo1243** [comment]
Lo que pasa es que los paths relativos no me funcionan en QtDesigner al seleccionar el pixmap como file. La idea era que pudiera poner las imagenes (iniciales) directamente desde QtDesigner para no ocupar espacio en el código. Entonces tuve que, en vez de file, ocupar resource en pixmap para ahi ocupar los paths relativos. Entonces no se como hacerlo para no ocupar las líneas de código y hacerlo directamente desde Qtdesigner (donde antes me tomaba solo paths absolutos)

**Comment by gabo1243** [comment]
UPDATE: Ya arreglé el problema, dejé los pixmap vacíos en QtDesigner y los rellené en el mismo código.

Gracias igualmente :)
