### ISSUE TITLE
Retomar Partida

### ISSUE THREAD

**Issue by cfalvarez2** [IIC2233/syllabus#288]
Tengo una duda sobre el enunciado. En la ventana de inicio debe darse la opción de comenzar una nueva partida o retomar la partida del jugador, entonces ¿deberíamos guardar en otro archivo toda la información de la partida? Porque en el archivo puntajes.txt se pide guardar el nombre del jugador y su puntaje total, pero si se quiere retomar una partida, se debe saber el número de ronda en la que va, las torres que sobrevivieron de la ronda anterior y la cantidad de monedas. ¿O solamente deberíamos trabajar con el puntaje total del jugador para retomar una partida?

**Comment by hbkim94** [comment]
Hola @cfalvarez2 

En la ventana de inicio debe darse solo la opción de comenzar una partida nueva; no pedimos que se pueda retomar una partida que ya fue terminada (lo único similar es el botón de pausa, pero eso es parar/retomar la partida mientras todavía se está jugando y se encuentra en la ventana de juego). 

El archivo `puntajes.txt` solo se utiliza para guardar los puntajes de partidas terminadas, cosa que al elegir el ranking de las 10 mejores partidas, aparezcan los puntajes correspondientes. 

Espero haber aclarado tu duda. ¡Mucha suerte!

**Comment by cfalvarez2** [comment]
Sí, muchas gracias!!
