### ISSUE TITLE
Criaturas en archivo magizoologos.csv

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2233/syllabus#288]
hola! En el archivo de los magizoologos ya existentes, nos dan el nombre de las criaturas que tienen pero nunca nos dicen de que tipo son, como para poder darles las condiciones y caracteristicas correctas al instanciarlas.

**Comment by aljara97** [comment]
Hola @maggiemunoz!

El nombre de una criatura es un identificador único, es decir, no hay ninguna criatura con el mismo nombre. Si te puedes fijar hay otro archivo llamado ```criaturas.csv```, el cual contiene el nombrw de las criaturas de los magizoólogos y su información correspondiente. Debes ser capaz de relacionar ambos archivos.

Cualquier otra duda, quedamos atentos 🧙‍♂️

**Comment by maggiemunoz** [comment]
ya, entiendo, pero y si ese archivo tiene todas las criaturas que ya tienen dueño, cuando uno quiere adoptar otra, el usuario debe elegir un tipo y un nombre, y se "genera" otra criatura?

**Comment by aljara97** [comment]
Exacto, al adoptar una nueva criatura debes ser capaz de asignarle nuevos datos como el nombre y su tipo, el primero debes verificar que no sea el de una criatura existente. También debes ser capaz de actualizar los archivos correspondientes, agregando los datos de tu nueva criatura a ```criaturas.csv``` y actualizar la lista de criaturas de tu magizoólogo en ```magizoólogos.csv```
