### ISSUE TITLE
Atraso

### ISSUE THREAD

**Issue by JSalas277** [IIC2233/Syllabus#288]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En caso de que quiera entregar por atraso había que hacer algo para optarlo pero no se que era, si es que alguno sabe le agradecería.

**Comment by Benjeeeh** [comment]
Hola!
Debes responder el [Formulario de Entregas Atrasadas](https://docs.google.com/forms/d/e/1FAIpQLSfQzkl0202OP7Z5O0dnAbZRR4kjfjGGivX3Dl8RhKOo8OdzMg/viewform). Te lo adjunto en el link anterior, y también puedes encontrar más detalles en el último anuncio de Canvas (Panorama Semana 22 de Abril).

Éxito!

**Comment by JSalas277** [comment]
Si en el caso de que haya hecho una entrega aun asi puedo dar una atrasada?

**Comment by Benjeeeh** [comment]
@JSalas277 Si, solo debes entregar el commit a revisar en el formulario, marcando los días de atraso y si quieres utilizar cupones.

**Comment by JSalas277** [comment]
O sea, debo subir un commit y luego mandar ese commit para el formulario. Ok muchas gracias
