### ISSUE TITLE
ReadMe, consideraciones generales

### ISSUE THREAD

**Issue by sofiaolmedos** [IIC2233/syllabus#288]
Hola! Para el README en la parte que tenemos que poner las cosas implementadas y no implementadas no me queda muy claro la estructura. ¿Deberíamos seguir el formato del Enunciado, como los índices? ¿O se debería seguir el formato del excel con la pauta?
Gracias!

**Comment by jitorcas** [comment]
Hola! @sofiaolmedos 

No les pedimos un orden predeterminado para enumerar las funcionalidades implementadas y no implementadas, queda a tu criterio utilizar como guía el enunciado, la distribución de puntajes o tu propia manera. 

Como recomendación, mientras más **detallado y explícito** es tu README, mayor probabilidad tienes de obtener las 5 décimas de de-descuento (a criterio del ayudante).

Éxito!! ⚓️
