### ISSUE TITLE
[Tarea 1][.gitignore] ¿Puedo usar solamente un .gitignore global?

### ISSUE THREAD

**Issue by Alexfhv** [IIC2233/syllabus#288]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

¡Hola! 👋  En la Tarea 1 🚢  el enunciado dice: "*```.gitignore``` ...deberá estar dentro de tu carpeta __Tareas/T1/__...*". También vi la *issue* https://github.com/IIC2233/syllabus/issues/113 donde se menciona que es "ideal crear un ```.gitignore``` para cada tarea".
Mi duda es, **¿es realmente obligatorio crear un ```.gitignore``` específico para cada tarea?**

Lo pregunto porque **VS Code** tiene una extensión de **git** que hace muy simple utilizar el ```.gitignore``` **global** del repositorio, pudiendo agregar archivos sin tener que editarlo directamente. En cambio, al crearlo en la carpeta **Tareas/T1**, no puedo realizar esta acción y se siguen agregando los archivos al global (traté de buscar alguna solución pero no la hallé). O sea, lo que haría sería únicamente copiar los *paths* del ```.gitignore``` global al local y modificarlos. Por esto creo que sería más eficiente dejar solo el ```.gitignore``` global 🌎 y no usar los locales 😄 .

**Comment by sperezmasri** [comment]
Hola @Alexfhv! Es **obligatorio** hacer un ```.gitignore``` para cada tarea. La idea de esto es que, en las tareas no siempre vas a querer ignorar las mismas cosas, y hacer un ```.gitignore```  global puede causarte problemas. Por ejemplo, digamos que en la tarea 1 y tarea 2 tienes un archivo llamado ```test.py```, pero solo quieres ignorar este archivo en la tarea 2. Si tuvieses un ```.gitignore``` global, ignorarías ese ```test.py``` en todo tu repositorio (se ignoraría en ambas tareas, cosa que no queríamos en este ejemplo).  Es claro que este ejemplo se puede solucionar cambiando el ```.gitignore``` global para cada tarea nueva, pero esto es muy desordenado ya que si alguien quisiera ver tu repositorio pensaría que todo lo que esta en ese ```.gitignore``` quiere ser ignorado en todo el repositorio, cosa que no es así según lo que tu mencionas, ya que el ```.gitignore``` global solo representaría lo que se esta ignorando en la tarea actual. Por último podría generar problemas en el repositorio (que en otros directorios ignores cosas que no quieres).

Hacer un ```.gitignore``` para cada tarea no es realmente tedioso, y es una forma ordenada de ver que es lo que quieres/quisiste ignorar en cada tarea. Avisame si respondi tu duda, o aún no te convence, saludos! :smile:

**Comment by Alexfhv** [comment]
Ok @sperezmasri! Entiendo, así lo haré entonces. 😊
Sin embargo, el ```.gitignore``` global si podría solucionar ese problema si escribimos los *paths* de los archivos a cada carpeta. Siguiendo con el ejemplo, el ```test.py``` podría estar en el ```.gitignore``` como ```Tareas\Tarea2\test.py```. Así no se ignoraría también en la Tarea 1 y la persona que lo vea sabrá bien a que carpeta nos estamos refiriendo. Pero como bien mencionas, si la idea es que creemos un ```.gitignore``` para cada tarea por supuesto también tiene sentido. Gracias por la respuesta 👨‍💻!!

**Comment by sperezmasri** [comment]
@Alexfhv, si como mencionas eso también estaría correcto y en la práctica podría servir :smile:. Otra cosa por la que se pide que tengas un ```.gitignore``` particular para cada tarea es que este se evalúa, entonces se necesita tener el ```.gitignore``` de cada tarea especifica. Saludos 💯
