### ISSUE TITLE
No me resulta borrar un elemento de la lista

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#288]
print(len(self.remaining))
                    if space.next:
                        space.next.prev = space.prev
                    if space.prev:
                        space.prev.next = space.next
                    print(len(self.remaining))

segun tengo entendido esto debería quitar el elemento space actual de la lista, ya que se lo deberían saltar, pero aun así, las dos veces donde imprimo el largo de la lista self.remaining me da el mismo largo. Que podría estar haciendo mal?

**Comment by iqacevedo** [comment]
Estás 100% seguro que len funciona adecuadamente?, si usas pycharm puedes usar el debug para detener tú programa en esa línea y revisar que efectivamente se eliminó. Cuando recorres tu estructura aún pasa por el elemento supuestamente no borrado ? 

Quedo atento,
Saludos !

**Comment by pnheinsohn** [comment]
Porfavor!!! Yo también tengo el mismo problema y mi len funciona perfecto! u.u

**Comment by Kitaps** [comment]
Al final cree una nueva lista que si funciona (nose porque, nunca lo sabre, no me interesa :6)
