### ISSUE TITLE
Modificación del código entregado

### ISSUE THREAD

**Issue by egbusch** [IIC2233/Syllabus#288]
En el enunciado se menciona que en el archivo main entregado se deben modificar dos métodos. Pero puedo modificar algo más aparte de esos 2 ? por ejemplo, puedo agregarle un diccionario al init de la clase ??

**Comment by Hernan4444** [comment]
@egbusch siiii!!! puedes usar el init para crear tus variables mientras no crees una que se llame igual a otra de la gui porque la terminarías sobrescribiendo

Saludos!!

**Comment by egbusch** [comment]
Gracias !

**Comment by cho19** [comment]
Hola!

Aparte de atributos, ¿puedo crear métodos dentro de la clase T03Window? Obviamente respetando los nombres de los métodos del gui.py.

Saludos y gracias

**Comment by iqacevedo** [comment]
Hola !

No esta permitido, puedes crear tus funciones en otros módulos e importar las que necesites para que interactuen con la interfaz. Además, siempre se busca que se separe el frontend del backend, que corresponde a separar lo que hace tu programa "por detrás "(en este caso todo el procesamiento de consultas) con lo que se ve (la interfaz gráfica).

Saludos !

**Comment by jorgeriesco** [comment]
Por que una variable que se llame igual que otra de la gui (lo que no se que es) se sobreescribira? Si es solamente un str de un diccionario. Algo no estoy entendiendo

**Comment by Hernan4444** [comment]
nos referimos a que en el init de la clase no puedes llamar dos variables igual. Por ejemplo si la gui tiene una `self.table = ...` y tu decides crear una variable en el init llamado table, vas a sobreescribir esa variable.
