### ISSUE TITLE
Importacion del módulo funciones.py

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#288]
Ya que se importan todas las funciones del modulo puedo importar así `import funciones as f` ?

**Comment by lily416** [comment]
Sí :)
Mejor dicho es una buena práctica que los importes de esa manera, ya que si importas dos módulos que tienen funciones, clases o variables con el mismo nombre, no se deberían sobreescribir :D

Por ejemplo:
```python3
import funciones1 as f1
import funcioens2 as f2

f1.funcion_repetida()
f2.funcion_repetida()

# Cada una funcionará como se definió y no se sobreescribiran :D
```


Saludos y éxito en la tarea 👋 💪
