### ISSUE TITLE
No me detecta las instancias de las clases en el menú

### ISSUE THREAD

**Issue by Gaspartby** [IIC2233/Syllabus#289]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

No entiendo por que los atributos de la clase Ejercito no pueden ser utilizados en mi archivo de menus, ya que al utilizar los mismos atributos dentro del archivo de donde los cree (clases.py) funciona perfectamente. Dejo las capturas prara que se entieda mejor.
Pd: utilicé import clases al comienzo del código menus.py y parece importarse correctamente. 
![Captura de pantalla 2024-04-23 220444](https://github.com/IIC2233/Syllabus/assets/141886529/9c7b139e-9889-449e-8377-24afa410a6ce)
![Captura de pantalla 2024-04-23 220505](https://github.com/IIC2233/Syllabus/assets/141886529/95377e47-24bd-4087-a0d3-89a612220f2e)

**Comment by tebi01** [comment]
Hola! @Gaspartby 

Intenta importar la clase directamente desde el archivo.

De esta manera: ```from clases import Ejercito``` en vez de sólo importar el archivo de clases. Tal vez pueda servirte de ayuda!

**Comment by Gaspartby** [comment]
perdón, no entendí bien cual es el error

**Comment by tebi01** [comment]
Imagina que tienes la definición de tu clase Ejercito (lo siguiente es pseudocódigo):

class Ejercito

**definicion de atributos de clase**

def init(self, atributos):
    **definición de atributos de instancia.**


resto del código



Para este caso, tienes que lo que esta dentro del init sólo es parte de un objeto de clase Ejercito (por ejemplo. si hola = Ejercito(args))

Entonces el ejercito hola contendrá los atributos de clase más los atributos del init (instancia).


Si quieres acceder a tu oro (lo que definiste dentro del init), entonces primero debes crear un ejercito, tal que:

ejercito_1 = Ejercito(args)

ahí sí puedes acceder al oro de ese ejército (mediante ejercito_1.oro), ya que definiste en el init que un ejercito tiene esos atributos.

De lo contrario, si quieres acceder al oro como parte de Ejercito como clase general y no como objeto, entonces define el oro fuera del init, tal que:

class Ejercito

oro = valor

def init(args)
resto del codigo.


Espero se entienda!
