### ISSUE TITLE
Duda intentar igualar señales

### ISSUE THREAD

**Issue by MaximilianWilke** [IIC2233/Syllabus#289]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

hola tengo un problema, para una clase planta defini una señal crear_planta como None, esto para luego igualarla con una señal de la logica del juego, dicha señal posee los atributos del tipo de planta, las posiciones, y el frame(para poner la imagen), de esta manera hacemos que la señal de cada planta sea especifica a cada una.

La cosa es que me tira un error TypeError: native Qt signal is not callable, no entiendo porque pasa esto, me base en los videos que mandaron junto con la T2, imito la creación de Mortys en la AI del archivo classes, el metodo run

**Comment by Hernan4444** [comment]
Hola @MaximilianWilke 

Te recomiendo revisar la clase de cierre de Interfaz Gráfica II (semana 7). En ella hablamos de errores comunes que hubieran en el desarrollo de la actividad y justo mencionamos ese error que indicas `TypeError: native Qt signal is not callable`.

Si lo de dicha clase no soluciona el problema, sube tu código con la señal crear_planta como None para ver cómo la utilizar y así intentemos encontrar la causa.

Saludosヾ(＾-＾)ノ

**Comment by MaximilianWilke** [comment]
Solucione el problema, no era eso pero lo logre
