### ISSUE TITLE
Semana 11

### ISSUE THREAD

**Issue by xDots1** [IIC2233/Syllabus#289]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Estuve realizando los ejercicios propuestos de la semana 11 y en el punto 1.3 piden encontrar el máximo de los 8 bytes 

**¿A qué se refiere esto?** o **¿Qué es lo que en realidad me están pidiendo en el ejercicio?**

**Comment by tqmbanados** [comment]
Hola  @xDots1! Recuerda que los bytes pueden ser representados como `int`: el `byte` `00000000` corresponde al `int` `0`, mientras que el `byte` `11111111` corresponde a `255`. En notación hexadecimal, son `\x00` y `\xff` respectivamente. En general puedes comparar el tamaño de bytes directamente, pero también puedes usar el método de `int` `from_bytes` para convertirlos a números sin problema!

Espero que esto aclare tu duda.
