### ISSUE TITLE
Borde amarillo de hint no desaparece

### ISSUE THREAD

**Issue by MrEarle** [IIC2233/Syllabus#289]
Cuando uno hace `gui.add_hint(i,j)`, aparece un borde amarillo en el espacio (i,j). Este borde solo desaparece cuando uno pone una ficha en ese espacio, hay alguna forma externa de hacerlo desaparecer?

**Comment by PIPEAPABLAZA** [comment]
tuve la misma duda y usé pop_piece(i,j), al igual que cuando borras una pieza y funciona 👍
