### ISSUE TITLE
Puntajes.txt

### ISSUE THREAD

**Issue by n4chin** [IIC2233/syllabus#289]
Que pasa si subí el archivo puntajes.txt a mi repositorio?? Lo saco o que puedo hacer??

**Comment by JadrinaDA** [comment]
Hola! Sí lo puedes sacar. Si quieres conservar el estado del archivo primero haz una copia del archivo en otra carpeta o si no puedes volver a copiarlo desde el syllabus. Ahora abres gitbash en la carpeta de tu tarea y usas el comando -rm ( git -rm puntajes.txt). Haces commit, push y listo! Ya no debería estar en tu repositorio y puedes volver a ponerlo en tu carpeta. Si tienes más dudas por favor avísame.

**Comment by n4chin** [comment]
Pero me bajarían mucho si lo dejo así?

**Comment by JadrinaDA** [comment]
En esta entrega no se evaluará el uso de gitignore, deberías poner el archivo en este para que no se subiera, así que no te va a afectar la nota. Sin embargo, es buena práctica para el futuro en que sí te podría sacar puntos.
