### ISSUE TITLE
Implementacion correcta  de clase abstracta

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#289]
Al crear una clase abstracta es necesario ponerle el decorador `@abstractmethod` o `@abstractproperty` para que cuente como buena implementación en la evaluación?

**Comment by jmwielandt** [comment]
Hola!

Sí, debes colocarlo para que sea una buena implementación. Para más detalles mira la issue #286 , allí se responde el caso particular del `__init__`.

Saludos.
