### ISSUE TITLE
Problema con main y DLL's

### ISSUE THREAD

**Issue by negutierrez** [IIC2233/Syllabus#289]
Ya instalé PyQt5, pero al correr el main tengo el siguiente error:
Traceback (most recent call last):
  File "C:/intento repo/negutierrez-iic2233-2017-1/Tareas/T03/main.py", line 1, in <module>
    from gui.Gui import MyWindow
  File "C:\intento repo\negutierrez-iic2233-2017-1\Tareas\T03\gui\Gui.py", line 1, in <module>
    from PyQt5 import QtWidgets, QtGui
ImportError: DLL load failed: %1 no es una aplicación Win32 válida.

Para las dos librerías me causa el mismo error, y creo que tiene que ver con los bits (32 y 64) de los paquetes pueden ser distintos a los de python.
¿Cómo puedo arreglar esto?

**Comment by GustavPrudencio** [comment]
+1

**Comment by sebacruzd** [comment]
De casualidad tenías instalado PyQt4 antes?
A mi me salía ese mismo error por instalar PyQt5 sin desinstalar el anterior. Eliminé ambos e instalé solo PyQt5 y se arregló.

**Comment by fmiranda22** [comment]
cps

**Comment by negutierrez** [comment]
Por si les sirve, lo arreglé re-instalando Anaconda(3-4.1.1), y de ahí instale pyqt5 usando "conda install pyqt5" en el Anaconda Promt. 
Hay que revisar que hacer el install de pyqt5 actualice también otros paquetes como Spyder, para que Spyder funcione bien.

**Comment by iqacevedo** [comment]
Hola!
Gracias por compartir tu solución, dejare esta Issue abierta por si le sirve a alguien más.

Saludos !

**Comment by Hernan4444** [comment]
Evitemos los "cps", suscribanse a las notificaciones de una issue si les interesa. Si les interesa el repo hagan watch (arriba a la derecha):

![image](https://cloud.githubusercontent.com/assets/10425834/14770701/2608a1c2-0a4e-11e6-8378-c58953883176.png)

Tanto en Facebook como aquí, en Github, existen sistemas para evitar las respuestas que no aportan a la discusión y que son solo para marcar seguimiento. Los invitamos a usar Github correctamente :grin:
