### ISSUE TITLE
¿Al mutar puedo usar mis plantas ya plantadas?

### ISSUE THREAD

**Issue by SpartyXD** [IIC2233/Syllabus#289]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holaa, 

A la hora de crear mutaciones, si esque no tengo las plantas necesarias en mi inventario **¿Puedo usar las que ya están plantadas?**l

El proceso seria como:
1. Elimino las del jardin
2. Agrego al inventario la mutacion nueva

Se puede hacer eso, o si deben ser plantas nuevitas para ser mutadas?

**Comment by rodrigoaguilera15** [comment]
Por enunciado solamente se pide que las plantas del inventario se puedan usar para las mutaciones, sin embargo no está explícitamente prohibido que se pueda hacer lo que tú sugieres. Solamente tendrías que dejar claro lo que hiciste en el enunciado.
