### ISSUE TITLE
Error cambiar jugador

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#289]
Esyo fue preguntado en ltra issue, pero todavia no contestan. Y no puedo seuir avanzando hasta solucionar este error, lo que pasa es que la demo me carga bien los 200 jugadores aleatorios y al armar el equipo los puedo meter a la cancha pero una vez dentro de la cancha si los selecciono no aparece el cuadrito con sus stats y para cambiarlo, porque podria estar ocurriebdo este error?

**Comment by behrmann97** [comment]
Hola, estas funciones se activan sólo cuando ya hay 11 jugadores dentro del equipo. ¿Te sucede aun teniendo el equipo completo?
Saludos!
