### ISSUE TITLE
QCoreApplication::exec: The event loop is already running

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2233/syllabus#289]
Tengo un problema con ese error, lo busque en internet y de lo que entendi es que pasa cuando uno hace `app = QApplication(sys.argv)` mas de una vez, lo que nos dice que el programa ya estaba en ejecucion, pero segun yo solo lo he puesto una vez. ¿Esta bien lo que entiendo del error?, si es asi ¿por que es que me esta dando igual?

**Comment by Hernan4444** [comment]
Hola,

Disculpa la tardanza, este error ocurre cuando haces más de una vez `. exec_()` de un widget cuando ya lo hiciste a una app, puede ser que en su momento tenías un `exec_` por ahí en alguna ventana lo cual generaba el error
