### ISSUE TITLE
Funcionamiento general git y github

### ISSUE THREAD

**Issue by margavicunas** [IIC2233/syllabus#29]
Hola! Todavía no tengo demasiado claro cómo funciona git y me cuesta entender un poco el ejercicio propuesto 4.1. ¿Qué hace add, commit o push para los archivos locales y remotos? y ¿Tienen algún tutorial disponible para familiarizarme más con git en general? Los que encuentro en internet no me han aclarado mucho.

Gracias de antemano :)

**Comment by tocococa** [comment]
Hola @margavicunas ! Git es un sistema de control de versión, esto es que permite hacer seguimiento a los cambios que haces en tu código (quién lo hizo, cuándo lo hizo, qué hizo, etc). También tiene herramientas más avanzadas que permiten que varias personas trabajen sobre el mismo _script_ o archivo sin generar conflictos durante la edición, además de permitir volver a alguna versión anterior y revisar el historial de modificaciones que se han realizado.

Los comandos que tienes que saber usar para el ramo son `git add`, `git commit`, `git push` y `git pull`. 

¿Ahora, cómo funcionan y que hace cada uno? Git tiene tres "árboles" mantenidos por `git.` . El primero sería tu directorio de trabajo, _working directory_, o dónde estás tú editando tus archivos en un computador. La segunda parte es el índice (_Index_ o _staging area_), donde se guardan los cambios enviados con `add`, en orden First In First Out. El tercero es el HEAD, que apunta al último `commit` que haz realizado.
- `git add <filename>` lo que hace es enviar los cambios que han ocurrido en tu directorio de trabajo a tu _staging area_.
- `git commit -m "mensaje del commit"` envía los cambios que se encuentran en el _staging area_ al HEAD junto con el comentario que describe los cambios, este lo escribes tu y es recomendable que sea descriptivo.
- `git push` finalmente sube los cambios indicados en los distintos _commits_ y registrados en el HEAD al repositorio remoto en el que estás trabajando, en el caso del ramo, tu repositorio privado en GitHub.

Lo más importante que hace Git, es que no sube _TODO_ el directorio (carpetas y archivos) con cada _commit_ y _push_, si no que se fija en que no hayan archivos repetidos, luego detecta que archivos sufrieron cambios, y sube solo dichos cambios, de esta forma se ahorra un montón de trabajo y ancho de banda.

Conversamente, `git pull` carga todos los cambios realizados al repositorio remoto (el syllabus o los contenidos en GitHub) en tu repositorio local (el que creaste usando `git clone`).

Si quieres aprender más sobre el funcionamiento de Git y GitHub, puedes revisar [esta guía](https://rogerdudler.github.io/git-guide/), el [_handbook_ de GitHub](https://guides.github.com/introduction/git-handbook/) y [esta otra guía](https://product.hubspot.com/blog/git-and-github-tutorial-for-beginners).

**Comment by margavicunas** [comment]
Mil gracias! Me quedó todo muuuy claro :)
