### ISSUE TITLE
Duda sobre estado final encomiendas

### ISSUE THREAD

**Issue by FranciscoPinto1138** [IIC2233/Syllabus#29]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda respecto al estado final de las encomiendas de la tarea. En el enunciado aparece como "En destino", pero en los ejemplos del archivo encomiendas.csv dice "Llegada al destino". ¿Cuál de estas opciones consideramos como correcta?

Gracias

**Comment by Emiliax16** [comment]
Hola @FranciscoPinto1138 ! ambas opciones son correctas! quedará a criterio de cada estudiante c: Saludos!

**Comment by FranciscoPinto1138** [comment]
Perfecto, muchas gracias!
