### ISSUE TITLE
Indentación y PEP8

### ISSUE THREAD

**Issue by knight-who-say-ni** [IIC2233/syllabus#29]
Holaa!! Tenia una duda... Segun la guía de estilo PEP8, cada linea de código debe tener cómo máximo 80 (o 100 en nuestro caso) carácteres... Dentro de esos 80 (100) se incluyen tambien??
Basicamente, en la linea despues de un while, mi maximo de caracteres despues de los 4 espacios seguira siendo 80 (100) o se verá reducido a 76 (96)??

Gracias!!

**Comment by MatiasDuhalde** [comment]
Hola!
Efectivamente, la indentación **sí se considera** para el máximo de caracteres por línea.
Por lo tanto, si te encuentras dentro de un bloque indentado, debes considerar los espacios que estén a la izquierda.

La mayoría de los editores de texto posee opciones que te permiten saber donde está el límite de los 100 caracteres. Visual Studio Code te permite poner una linea como se ve en este ejemplo:
![temp](https://user-images.githubusercontent.com/46191755/76806661-cc77b380-67c0-11ea-9386-bd51945ff691.png)
Ahí si te llegas a pasar de esa línea, estarías por sobre el límite de caracteres.
Además, en la parte de abajo a la derecha aparece en que columna (o caracter) se encuentra el cursor.

Te recomiendo también revisar la issue #20 para ver formas de como separar líneas muy largas.

**Comment by mikkelchile** [comment]
Hola, una pequeña duda como puedo colocar la linea vertical en el Visual Studio Code, para no pasarme de los caracteres máximos
Gracias.
