### ISSUE TITLE
Commit + Push post-actividades

### ISSUE THREAD

**Issue by fgbruna** [IIC2233/Syllabus#29]
Existe algún problema si yo,por motivos personales, quiero terminar lo que me faltó de la actividad del día y respaldarla en github,no se crearía ningún clonficto para la correción del commit que entregué en el horario adecuado?

**Comment by Hernan4444** [comment]
@fgbruna no hay ningún problema 👍 

Saludos!!

**Comment by flobarrios** [comment]
Hola!! 

Las actividades ya fueron recolectadas por lo que no hay ningún problema. Además, recolectamos el último commit antes de la hora de entrega por lo que si no se ha recolectado la actividad tampoco habría problema.

Saludos!!

**Comment by fgbruna** [comment]
Gracias!

**Comment by PIPEAPABLAZA** [comment]
y con respecto a los readme, con detalles y/o explicaciones del código, se puede subir aún?

**Comment by flobarrios** [comment]
@PIPEAPABLAZA si!
