### ISSUE TITLE
Duda sobre condición de victoria

### ISSUE THREAD

**Issue by camiloEscorza** [IIC2233/Syllabus#29]
* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Mi duda reside en cual es el objetivo del juego, porque siendo las reglas las siguientes:
1) Cada número del tablero representa la cantidad de celdas contigüas que se ven afectadas por la explosión de una bomba
2) El mínimo valor que puede tener una bomba en DCCeldas será 2 y el valor máximo 2n-1
3) Las celdas con números no pueden estar tapadas
4) Dos celdas tapadas no pueden estar juntas vertical u horizontalmente, solo en diagonal
5) (bonus) Sin islas por tortugas
Teniendo como victoria cumplir las reglas anteriormente mencionadas teóricamente yo podría hacer un tablero sin tortugas, con solo una bomba (y ni siquiera) cumpliendo la regla 2, y me cumpliría todas las reglas, ya que la regla 1 tendría que implementarla, la regla 2 la estoy cumpliendo, y como no tengo tortugas, la regla 3, 4 y 5 se cumplen automáticamente, ya que dependen de la existencia de tortugas. En las reglas explícitamente mencionadas no veo incentivos a poner tortugas, sino solo limitaciones a ellas. 
Entonces no entiendo qué tengo que implementar como estrategia de defensa, ya que si victoria se define como cumplir las 5 reglas, el uso de tortugas parece innecesario e incluso perjudicial

**Comment by Hernan4444** [comment]
Hola @camiloEscorza 

El tema es que los tableros tendrán bombas que no cumplen la regla 1 y nuestra única acción posible es poner tortugas para asegurar que las bombas si cumplan la regla 1. Pero no sirve poner tortugas en todas partes, hay que ponerlas de forma estratégica para que se cumplan las reglas 3 y 4, y si haces el bonus, la regla 5. Por ejemplo, un tablero que te podemos pasar es
```
- 2
- -
```
Y ahí ese 2 no cumple la regla 1, porque la bomba afecta a 3 celdas, pero el número es un 2. Hay que poner una tortuga para hacer que ese 2 afecte únicamente a 2 casillas (la que él está usando y una más).

Sobre la regla 2, es un seguro para saber desde un inicio si el tablero puede tener solución o no. Por ejemplo, si cargas un tablero que tiene número negativos, ya no se cumple la regla 2 y el tablero no tendrá solución (que es un caso a evaluar), así que ahí uno puede ahorrarse el intentar poner tortugas porque desde un inicio sabrá que no funcionará.

Espero que ahí quede más claro la estrategia de defensa 😄 

Saludos c:
