### ISSUE TITLE
¿Cómo se representan las baldosas para el jugador?

### ISSUE THREAD

**Issue by Rafoxxa** [IIC2233/syllabus#29]
Entiendo que si se elige una baldosa sin lego, esta tiene que mostrar la cantidad de legos aledaños. Lo que no me quedó muy claro es cómo se ve para el jugador una baldosa cubierta (con un espacio en blanco??). Gracias de antemano!

**Comment by jeschuwirth** [comment]
Saludos,

Lee la parte del enunciado donde hablan del archivo tablero.py y te debería quedar mas o menos claro como funciona, si te refieres a casillas sin legos adjacentes puedes utilizar un 0 una vez descubierta.

Si te quedan dudas sigue comentando en este hilo :)

Suerte en la tarea!

**Comment by Rafoxxa** [comment]
Gracias! estaba ahí !
