### ISSUE TITLE
Error con Python: Select Linter

### ISSUE THREAD

**Issue by miniatures0ul** [IIC2233/Syllabus#29]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

Estaba realizando la configuración de VSCode y al escribir el comando Python: Select Linter y seleccionar pycodestyle, me apareció la siguiente ventana de error.
<img width="417" alt="error_vsc" src="https://github.com/IIC2233/Syllabus/assets/141945478/c885dcf3-d628-4071-9438-d928058ff102">

¿Qué debo hacer?

**Comment by Hernan4444** [comment]
Hola @miniatures0ul 

Por lo que veo del error, es que VSCode está intentando crear una carpeta en windows y no tiene los permisos. Podrías intentar lo siguiente:

1. Abrir tu terminal de **WSL**
2. Escribir `sudo code .`  Esto es para abrir VSCode con permisos de administrador
3. Te pediré una contraseña, ahí pones la de ubuntu
4. Ahora si intentar el paso de "pycodestyle"

Avísanos cómo te va con eso,
Saludosヾ(＾-＾)ノ

**Comment by miniatures0ul** [comment]
Hola! Seguí hasta el paso 3 y apareció lo siguiente:
<img width="668" alt="wsl_a" src="https://github.com/IIC2233/Syllabus/assets/141945478/d8e1c89d-f7c7-4310-ba75-727e284912c5">

De ahí no hice nada porque no comprendo a qué se refiere exactamente :(

**Comment by Hernan4444** [comment]
Ya,

WSL no permite hacer `code .` . Lo que puedes intentar es
1. Desinstalar VSCode de tu windows.
2. En tu terminal de WSL, escribir `sudo apt-get purge code` para eliminar todo lo relacionado a `code`.
3.Seguir los pasos de [aquí](https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode#install-vs-code-and-the-wsl-extension)  que es insstalar VSCode pero asegurandose de agregar al PATH para que `code .` sea válido.

Luego, abrir tu terminal con WSL y escribir `sudo code .`

Avísanos cómo te va y si mandas foto, porfa que esta incluya todo tu terminal, es decir, que veamos todo el historial junto con el comando que utilizaste.

Quedamos atentos,

**Comment by miniatures0ul** [comment]
Al fin funcionó! Muchas gracias <3

**Comment by Hernan4444** [comment]
Que bueno que haya funcionado 🎉 🎉 

Saludos!
