### ISSUE TITLE
Repetición de estaciones en métodos de estaciones_intermedias.

### ISSUE THREAD

**Issue by Vicente1824** [IIC2233/Syllabus#29]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Si tengo una estación (por ejemplo, "Baquedano" del archivo `test_2.txt"`) que tiene un túnel hacia sí misma, **¿podría considerarse que hay una o dos estaciones intermedias entre la misma estación usando la misma estación como intermedia?** Por ejemplo, hacer
```py
metro.estaciones_intermedias_avanzado("Baquedano", "Baquedano")
```
retornaría la lista `['Baquedano', 'Baquedano']` como una forma posible de moverse entre ambas. ¿O las estaciones intermedias tienen que ser distintas a las de origen y final?
De igual forma, **¿podría una estación intermedia repetirse?** Es decir, poder retornar, de la estación "A" a la "B", la sublista `["C", "C"]` (en el caso de que haya un túnel de "C" a "C").

**Comment by MaxAl100** [comment]
Hola, buenos días! Lo que mencionas sí es válido, no es necesario ir a otra estación si es que existe un túnel de y hacia esta misma.

**Comment by Vicente1824** [comment]
¡Súper! Muchas gracias :)
