### ISSUE TITLE
Radio del Incendio

### ISSUE THREAD

**Issue by pita-horn** [IIC2233/Syllabus#29]
Hola!
Con tal de poder calcular el área del incendio necesito su radio, pero (al menos como sale en el enunciado) este valor no está en la base de datos. ¿Nos van a dar el radio en las bases más tarde o hay una manera de deducirlo dentro del enunciado?
Gracias :)

**Comment by Dunkan1** [comment]
segun yo debemos hacer el calculo.
tiempo de inicio del incendio + la tasa de propagacion base(500 metros por hora) + la hora de inicio del incendio, con estos tres se puede calcular el area, creo que por eso no nos dan el radio en la base de datos como un dato

**Comment by rpalmaotero** [comment]
@Dunkan1 eso mismo.

**Comment by benjamimo1** [comment]
@pita-horn hola 👀
