### ISSUE TITLE
Un QLabel no se puede mover si se le agregar un float

### ISSUE THREAD

**Issue by franco-anfossi** [IIC2233/Syllabus#290]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Holaa, mi duda es respecto a lo del titulo porque la velocidad de uno de los zombies es 1.5 la velocidad de zombies y esto de lo mismo que numero sea hará que uno de los dos zombies quede con velocidad float y un QLabel no deja que se mueva a una posición float, entonces no se que hacer aquí por que no puedo hacer que el zombie se mueva a la posición deseada. Habra alguna otra función de QLabel que lo permita o hacemos una aproximación o lo transformamos en int?

**Comment by Lord-Kelsier** [comment]
podrias usar `round()` de python
