### ISSUE TITLE
Nueva partida, guardado 

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#290]
En la sección 6.3.1 del enunciado dice que debemos guardar las entidades en los archivos correspondientes una vez creadas. No entiendo si el guardado debe ser estrictamente justo despues de crearlas, osea, creo un piloto y lo guardo, luego el vehiculo y se guarda, o si podría crear ambos y luego guardarlos.

**Comment by jaromero6** [comment]
Hola
Queda a tú criterio la manera de realizar el guardado, mientras no permitas que un piloto corra una carrera sin un auto está todo bien.
Ánimo con esa entrega
