### ISSUE TITLE
Duda sobre la AC05

### ISSUE THREAD

**Issue by dnalfaro** [IIC2233/Syllabus#290]
En la actividad del día de hoy salía en el enunciado:
> "**pokémon para entrenador(entrenador, pokémones)**
Recibe un entrenador y un iterable de pokémones.
Es un generador que retorna, como mucho, a los seis mejores pokémones para el equipo del entre-
nador, **ordenados según la estadística favorita del entrenador**."
>
Ya avanzada la actividad se dió la información de que el orden debía ser por el poder total de los pokemones. El problema es que el output esperado se obtenía efectivamente ordenando por la _estadística favorita del entrenador_ . Quería saber cuál sería la versión definitiva?

**Comment by jtagle2** [comment]
@dnalfaro, ambas versiones se considerarán correctas.
Saludos!

**Comment by dnalfaro** [comment]
Muchas gracias
