### ISSUE TITLE
Modulos en README

### ISSUE THREAD

**Issue by sofiaolmedos** [IIC2233/syllabus#290]
Hola! Para el Readme no entiendo bien si la explicación de los módulos que creé debería ir en Ejecución o Librerías
Gracias!

**Comment by josefinareyes** [comment]
Hola! La explicación de tus módulos tiene que ir en ```Librerías```, en el ejemplo de tu repo debería haber una sección de ```Librerías propias```, para explicar brevemente lo que hace cada módulo creado. En la parte de ```Ejecución``` deberías especificar más bien la ubicación de cada módulo o archivo para que funcione bien tu tarea! Éxito en la tarea!
