### ISSUE TITLE
QTimer timeout nunca se dispara

### ISSUE THREAD

**Issue by jearaneda** [IIC2233/syllabus#290]
**Logré hacer que corriera pero parece que está prohibido en la tarea, me pueden aclarar? Hice esto**
```
    def run(self):
        print('runin')
        loop = QtCore.QEventLoop()
        timer = QtCore.QTimer()
        timer.timeout.connect(self.mover_ai)
        timer.start(1000)
        print(timer.remainingTime())
        print(timer.isActive())
        loop.exec_()
    
```

No logro triggerear el timeout de ningún Qtimer, lo necesito para ir moviendo enemigos. Jamás se dispara.

Tengo la clase Enemigo(QThread), la que es instanciada por la clase Backend. Pongo mi QTimer en QThread así:
```
    def timer_func(self):
        print('prendida')
        QtCore.QTimer.singleShot(500, self.mover_ai)
```

Esta función está después del init obviamente (tiene self). El problema es que mover_ai jamás se ejecuta.

Tampoco funciona con la definición normal (definir el qtimer arriba del init.... etc). Leí que podía ser un problema con el cómo los QThreads manejan los QTimer, pero estoy tratando de usar threads por las indicaciones del enunciado. De todas formas, no encontré como solucionarlo.

Por otro lado, sé que el timer está corriendo porque haciendolo así me tira un True y una cantidad de ms restantes. Pero self.mover_ai no se ejecuta
```
        timer = QtCore.QTimer()
        timer.timeout.connect(self.mover_ai)
        timer.start(1000)
        print(timer.remainingTime())
        print(timer.isActive())

```

**Comment by roberto009** [comment]
Hola!
Tu pregunta está media dispersa pero intentaré responderla lo mejor que pueda.
Si tu clase hereda de *QThread`*el método que se ejecutará cuando hagas `objeto.start()` será el método `run()` de la clase, por lo que debes hacerle *overriding* con lo que tu quieras que pase cuando se corra ese *QThread*.

Luego, los *QTimer* son un *thread* que se repite cada un intervalo de tiempo que tu le das. Si es que usas `QTimer.sigleShot()` hace que tu *QTimer* se ejecute **una sola vez** después de ese tiempo. Si es que quieres hacer que los enemigos se muevan cada cierto tiempo no te recomiendo usar *singleShot()*.

Según lo que estuve leyendo, hay un par de problemas al usar *QTimer* dentro de un *QThread*. Trata primero modelando tu clase enemigo de una forma que no deba ser un *QThread*. Si es que no puedes hacer esto, porque es necesario para como estás modelando el programa, entonces prueba definiendo el *QTimer* en el `__init__` y luego de definirlo hacer `self.mi_qtimer.moveToThread(self). De esta forma estarás "uniendo" el *QThread* que es tu enemigo, con tu *QTimer* . Luego haz el `self.mi_qtimer.start()` dentro del método `run()` de enemigo. 

Espero que eso te funcione 😄 
Si no te funciona avísame!
Éxito 💪

**Comment by jearaneda** [comment]
Hola! No me resultó de la forma que sugeriste :(, al parecer tiene que ver con que son varios threads (enemigos). 

Pude hacerlo funcionar con lo que puse arriba en negrita, pero no sé si eso está en la lista de built-ins prohibidos. Sale que sí, pero también aclararon que si el método es de PyQt no había problema.

**Comment by Hernan4444** [comment]
Hola,

Antes de intentar con ese "_exec", podrías intentar con:
```python
    def run(self):
        print('runin')
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.mover_ai)
        self.timer.start(1000)
        print(self.timer.remainingTime())
        print(self.timer.isActive())
```

Y nos dices como te va, que una de las cosas de PyqT5 es que siempre debe quedar alguna referencia hacia los threads o timers, como tu lo tienes en una variable, luego de terminar el método run, esa variable desaparece (junto con su ejecución).

Saludos y quedo atento a tus comentarios. :v:

**Comment by jearaneda** [comment]
sigue sin resultarme si lo hago así, simplemente ignora la función del timeout pese a que crea el timer. No he logrado que funcione sin _exec :(

**Comment by Hernan4444** [comment]
Hola, revisé el último código que hiciste push y me encontré con esto:
```python
        for enemy in self.enemigos:
            enemy.spawn()
       
        self.enemigos = []
```

Aquí estamos justamente con algo que dije antes:

> una de las cosas de PyqT5 es que siempre debe quedar alguna referencia hacia los threads o timers

¿Qué está pasando aquí? 
Cuando haces que la lista sea vacía, se pierde toda referencia de tus enemigos y esto hace que ese timer también pierda su referencia. Acabo de eliminar esa línea (self.enemigos = []), hacer que `timer` sea `self.timer` y todo funcionó perfecto. En resumen, **jamas pierdas la referencia de un thread o timer** sino todo sale mal.

Aunque es cierto que con `loop = QtCore.QEventLoop()`, lo que estabas experimentado es un error que puede repertirse en otras partes de la tarea y no estamos seguros que `QEventLoop` lo vaya a solucionar. Con lo que puse antes de no perder la referencia, no deberás enfrentar este problema.

Saludos :v:
