### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#290]
## Veremos regex?

**Comment by lily416** [comment]
Hola @fernandosmither, 
 
Hasta el momento no hemos decidido si este semestre se verán Expresiones Regulares (regex) como parte de los contenidos del curso, ya que no forma parte de los contenidos mínimos a revisar. En caso de que se llegue a incorporar a los contenidos, les avisaremos con anticipación y les daremos más detalles al respecto.
 
Saludos y que tengas un buen fin de semana 👋🔠

**Comment by fernandosmither** [comment]
> Hola @fernandosmither,
> 
> Hasta el momento no hemos decidido si este semestre se verán Expresiones Regulares (regex) como parte de los contenidos del curso, ya que no forma parte de los contenidos mínimos a revisar. En caso de que se llegue a incorporar a los contenidos, les avisaremos con anticipación y les daremos más detalles al respecto.
> 
> Saludos y que tengas un buen fin de semana 👋🔠

Oka :(
