### ISSUE TITLE
Algunas piezas me salen "invisibles"

### ISSUE THREAD

**Issue by AndresGarciadelaHuerta** [IIC2233/Syllabus#290]
Hola! Estoy teniendo un problema con algunas piezas que me salen invisibles pero que las puedo rotar y hacer calzar en el tablero (si es que le achunto a los bordes correspondientes). 
¿A alguien más le pasa o le ha pasado? ¿O es un error de la gui y no mío? Que llevo un buen rato buscando a que se puede deber y simplemente no lo he podido encontrar ya que no me tira ningún error en consola, ya que después me siguen saliendo piezas bien y a veces se aparece alguna invisible. Si alguien sabe la solución me sería de mucha ayuda, gracias!!
![captura de pantalla 2017-09-11 a la s 17 59 18](https://user-images.githubusercontent.com/30664883/30296805-d892d654-971b-11e7-931d-fc3ea99ea04d.png)
En la foto se puede ver claramente dos piezas que pude poner y la número 3 es la última que me salió, las 3 invisibles.

**Comment by fnquinteros** [comment]
Hola! Probaste descargando la interfaz nuevamente?

**Comment by tanavarrete** [comment]
Me pasa lo mismo!

**Comment by MrEarle** [comment]
Puede ser porque estás pasando una pieza que gui.add_piece() no reconoce. A mi me paso lo mismo y ese fue el problema.

**Comment by cjmunoz4** [comment]
Me pasa lo mismo. La pieza "invisible", por lo menos a mí, me sale directamente de hacer gui.nueva_pieza()

**Comment by AndresGarciadelaHuerta** [comment]
@fnquinteros voy a probar a ver si me sirve! @MrEarle voy a revisar eso también, ya que estoy casi seguro que siempre entrego tipos de piezas definidos que ya existen y nunca uno rotado.

**Comment by iqacevedo** [comment]
@AndresGarciadelaHuerta también puede ser porque le estas pasando el color mal, solo puede ser 'red' o 'blue'. Ese tipo de errores, como bien dicen tus compañeros, ocurre cuando se intenta cargar una imagen que no existe, o bien cuando no se volvió a cargar la imagen con nueva_pieza, después de haberla usado con add_piece.

Cuéntanos si lograste solucionar tu problema.

Saludos !

**Comment by nmaturana97** [comment]
Hola, me paso, y me di cuenta que era porque el archivo pieces lo genere con las piezas antiguas, es decir, hay unas piezas que cambiaron de nombre, entonces no las pone. Hay que generar de nuevo el archivo de pieces.

**Comment by AndresGarciadelaHuerta** [comment]
@nmaturana97 después de revisar lo que me dijeron antes igual me seguía pasando, hasta que probé lo que dijiste y ese era el error!

**Comment by BeaGaete** [comment]
Hola! Ya logre que no me salieran invisibles, pero cuando trato de poner un estado que grabé la interfaz no me muestra la pieza rotada como la había rotado antes, aunque para efectos del juego sí se interpreta como si estuviera rotada, alguien con el mismo problema???

**Comment by iqacevedo** [comment]
@BeaGaete revistaste la issue #233 ? 
Ahí se agrega un método a los que ya tenían del enunciado que puede ayudarte a conseguir lo que quieres.

Saludos !

**Comment by Dyoma3** [comment]
A mi me salian piezas invisibles despues de rotar, pero era porque usaba agregar_pieza con el nombre de la pieza rotada, la que no existía en la lista de piezas

**Comment by Calomi** [comment]
Hola!
esto pasa porque dentro de gui, en variables.py en la linea 23 aun sigue los nombres viejos 🙄

**Comment by BeaGaete** [comment]
Gracias! Solucionado
