### ISSUE TITLE
Tarea 01: Precios de Alimentos y Criaturas para adoptar

### ISSUE THREAD

**Issue by rldelafuente** [IIC2233/syllabus#290]
Hola! 

**1.** Me queda una duda con los los **precios de adoptar criatura y comprar alimentos**, no los encuentro en el enunciado. ¿Cuánto cuesta comprar una Tarta de Melaza por ejemplo? ¿Cuánto cuesta adoptar un Niffler?

**2.** ¿La acción adoptar criatura significa crear una nueva criatura (nuevo nombre) o se puede adoptar criaturas que se han escapado (nombre ya existe)?

**3.** ¿Cuándo Augurey (ave) vuela para traer alimento, este es al azar? ¿Cualquiera de las 3 opciones?

Pido perdón de antemano si esta información está en el enunciado, pero no la encontré o no me quedó claro.

Gracias!

**Comment by Dnpoblete** [comment]
Hola @rldelafuente, por favor para la próxima vez que tengas dudas separalas en diferentes issues por tema, por que si alguien busca después es más fácil encontrar la respuesta y por otro lado, por favor revisar bien el enunciado y las issues anteriores antes de realizar nuevas preguntas.

Respondiendo tus dudas en orden:

1. En el enunciado sale lo siguiente:
![image](https://user-images.githubusercontent.com/42362982/78610602-353bd400-7833-11ea-834f-0a7568ca642e.png)
Por lo que los precios se dan en el enunciado, pero tienes que modelarlos como parámetros en el archivo parametros.py, cosa de que sean modificables.

2. La idea es que al adoptar criaturas el nombre no se repita por lo cual no puede ser igual a una criatura que se escapó, ya que estas se pueden recuperar, no adoptar.

3. Como no se explicita en el enunciado queda a tu criterio siempre y cuando lo expliques en el ReadMe, el ideal es que sea cualquiera de las tres.

Éxito con la tarea! ✨
