### ISSUE TITLE
Problema git ignore

### ISSUE THREAD

**Issue by tomasvasquezp** [IIC2233/Syllabus#290]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! estaba revisando mi repositorio y me di cuenta que, a pesar de crear el gitignore y poner dentro los archivos que debía ignorar, esos archivos se subieron igual, que puedo hacer?

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by gasparbenavente2** [comment]
Hola! Puedes haber tenido un error en que cuando creaste el gitignore los archivos ya estaban en github. El archivo gitignore solo hace que paren de ser "trackeados", si ya estaban subidos o modificados de antes no los afecta. Una solución puede ser:
Sacar los archivos de gitignore, borrarlos de la carpeta (o moverlos a otro lado), hacer push para que aparezcan como borrados, traerlos de nuevo a la carpeta, agregarlos a gitignore
