### ISSUE TITLE
Duda acerca de setter abstracto

### ISSUE THREAD

**Issue by matiasherrerar** [IIC2233/Syllabus#290]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola quería preguntar, si defino una propiedad abstracta y un setter abstracto, y luego en la clase hija quiero dejar el setter igual al de la clase madre, ¿cómo debo definir el setter en la clase hija para que lo herede exactamente igual?

Lo que se me ocurre es:

class Hija(ClaseMadre):

@ atributox.setter
def atributox(self, nuevo_valor):
       super().atributox(nuevo_valor)

**Comment by rodrigoaguilera15** [comment]
En el caso de properties y setters, si los vas a mantener iguales en las clases hijas, solo basta que las definas dentro de la clase abstracta, no es necesario volver a definirlos en las clases hijas.

**Comment by nachotagle** [comment]
En este caso, para que no sea necesario volver a definirlos en la Clase Hija, sería necesario hacer la propiedad y el setter abstracta?? O sin hacerlo abstracta igual funciona no volver a definirlo.

**Comment by rodrigoaguilera15** [comment]
Si a lo que te refieres es si es necesario ocupar el decorador @abstractmethod en este caso, la respuesta es que no. Quedo atento, saludos.
