### ISSUE TITLE
restaurar syllabus

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2233/Syllabus#290]
hola, tuve un problema con mi repositorio de syllabous local y para arreglarlo intenté borrando todos los archivos, pero ahora no puedo volver a descargar los archivos del syllabous de la nube

**Comment by 1862507J** [comment]
Hola! para clonar cualquier repo puedes ver [la siguiente guía](https://docs.github.com/es/repositories/creating-and-managing-repositories/cloning-a-repository). En el caso del syllabus es código sería `git clone https://github.com/IIC2233/Syllabus.git` y el de los contenidos `git clone https://github.com/IIC2233/contenidos.git`.
