### ISSUE TITLE
contrincantes pits

### ISSUE THREAD

**Issue by F-arellano** [IIC2233/syllabus#291]
¿puedo asumir que los contrincantes nunca ingresaran a los pits?¿puedo hacer que, si su chasis baja de cierto porcentaje, entonces ingresen inmediatamente a los pits en la proxima vuelta? la verdad la pregunta es solo por el balance del juego, no se siente bien que solo yo termine con tiempos adicionales gracias a los pits (o que terminen todos los contrincantes fuera de competencia debido a las pistas)

**Comment by jaromero6** [comment]
Hola
Queda a criterio tuyo si los vehículos ingresan a los pits, por lo que si podrías hacer que los contricantes entren a los pits. Pero **recuerda** que esto no es el enfoque principal de la tarea por lo que si queda mal implementado o dificulta de alguna manera la corrección de algún item, podría perjudicar tú nota.
FInalemente recuerda que si lo haces, debes especificarlo en tú Readme también para que el ayudante corrector esté al tanto.
Espero haber respondido a tú pregunta
