### ISSUE TITLE
Plantas desaparecen al ser tocadas por un zombie

### ISSUE THREAD

**Issue by ymotomy** [IIC2233/Syllabus#291]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Tengo un problema, al momento de que un zombie se coma a una planta, esta desaparece, no se detiene a comer. El error ocurre por que verifica constantemente si estan en la misma posicion, si es asi, le quita vida, y como ocurre en un pequeño lapso de tiempo donde será verdadero, le quita toda la vida. Intente solucionarlo con un QTimer, pero no me sirvió de mucho (seguramente lo aplique mal y no he podido percatarme de ello).

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Hernan4444** [comment]
Hola @ymotomy 

Tal como indicas, lo que pasa es que en ese pequeño lapso de tiempo, tu QTimer ejecutó la función verificadora de colisión varias veces y le quitó vida constantemente. Intenta ver el problema desde otro ángulo: si ya colisioné con la planta y le quité vida, ¿es razonable que en el siguiente tick le vuelva a quitar vida? ¿o tal vez debería esperar una "X" cantidad de ticks de estar chocando antes de volver a quitar vida? De ese modo relentizas las veces que le quitas vida a la planta y no desaparecerá de golpe. 

(Imagina que tienes un contador de colisiiones y cada vez que este contador llega un valor N, se le quita vida a la planta y el contador vuelve a ser 0, se deberá colusionar N veces de nuevo para voler a quitar vida)

Cuantanos como te va con este otro enfoque y cualquier cosa, estaremos atentos al foro,
Saludosヾ(＾-＾)ノ
