### ISSUE TITLE
Llamar a un objeto creado en otro archivo

### ISSUE THREAD

**Issue by ByronHidalgo1** [IIC2233/syllabus#291]
Hola, 
Tengo dos módulos, en el primero ("main"), se abre la ventana inicial y se crean los objetos para poder iniciar el juego el cual se programa en el segundo módulo llamado "personaje", el cual posee dos clases, "MiVentana" y "Personaje". Al iniciar a través de "main" me muestra la ventana inicial, luego de presionar aceptar, se abre la ventana de "personaje" y me permite presionar los botones que se crean en la clase "MiVentana". Luego al realizar un movimiento, (los movimientos están definidos en la clase Personaje), me dice esto:

NameError: name 'pantalla' is not defined

Pero en "main" tenía esto:

from personaje import MiVentana, Personaje
.
.
.
if __name__ == '__main__':
    app = QApplication(sys.argv)
    .
    .
    pantalla = MiVentana()
    .
    .
    sys.exit(app.exec_())

He intentado mover el lugar donde se crea el objeto "pantalla", sin embargo, sigue pasando lo mismo. ¿Me pueden ayudar?

**Comment by Witomi** [comment]
Pusiste en el frontend:
from backend import pantalla  ?

**Comment by ByronHidalgo1** [comment]
Al hacer eso, me dice:
ImportError: cannot import name 'pantalla' from 'personaje' (C:\Users\...\personaje.py)

**Comment by roberto009** [comment]
Hola @ByronHidalgo1 !
Por lo que entendí estas llamando a `pantalla` dentro de otra clase, pero está la tienes definida a fuera de está. Como estas clases en las que estas llamando a `pantalla` no están en el mismo archivo *main.py*, sino que están en el modulo *personaje.py*, no tienen referencia al objeto `pantalla` creado en el *main*.

Existen varias soluciones para este problema. Una es entregarle como argumento el objeto `pantalla` a la clase en la que lo estás llamando, para que así tenga como referencia este objeto. Es **importante** que tengas ojo con esta forma de solucionar el problema porque puedes caer un **modelamiento circular**.

En la issue #275 se habla más sobre la modelación ciruclar. 

En resumen, debes buscar la forma de que tu ventana de `personaje` tenga acceso a tu objeto `pantalla`, ya que, `pantalla` está definido en otro módulo.  

Otra forma de hacerlo es usando *metaclases* y creando un *singleton*, pero esta es una forma mucho más compleja y estos contenidos no se ven en el curso. Igual te dejo un [link](https://riptutorial.com/python/example/17869/singleton-class) por si te interesa averiguar más.

Éxito con la tarea 💪

**Comment by ByronHidalgo1** [comment]
Me funcionó con la primera forma, muchas gracias!
