### ISSUE TITLE
Error al cambiar jugador

### ISSUE THREAD

**Issue by Cschavez** [IIC2233/Syllabus#291]
Hola! Había mandado otra issue pero aún no me responden y me preocupa igual un poco:( Cuando aún no descargaba la carpeta "photos" funcionaba bien el programa, y al presionar sobre un jugador me aparecía su información. Sin embargo, desde que descargué la carpeta para las fotos, ahora al momento de presionar un jugador el programa se cierra. En la interfaz de python no sale ni un error.
[Issue #281 ](https://github.com/IIC2233/Syllabus/issues/281)
Gracias!

**Comment by Arcoirisky** [comment]
No tengo idea de lo que pasa pero intenta esto y dinos el error https://github.com/IIC2233/Syllabus-2017-2/issues/598

**Comment by Cschavez** [comment]
Esto es lo que dice:

![image](https://user-images.githubusercontent.com/37157327/39068124-93c603a4-44b1-11e8-8965-974fd67012ee.png)

**Comment by behrmann97** [comment]
Hola, ¿puede ser que estés pasando el overall de los jugadores como int? Recuerda que todos los valores que le pasas a la GUI al instanciarla deben ser strings.
Saludos!

**Comment by Cschavez** [comment]
Eso era! Mil gracias
