### ISSUE TITLE
Python desconoce las variables que nombro 

### ISSUE THREAD

**Issue by luzmagurzua** [IIC2233/syllabus#291]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Estoy trabajando en la clase "Barco", sin embargo para probar un nombre cualquiera del objeto, Python me dice que no existe la variable. por ejemplo, defini la clase "Barco" con sus atributos y luego instancié barco = Barco(bla,bla,bla...), printeé barco y me dice que no está definido.

Hoy estudiando threads también me pasó lo mismo cuando printeaba una variable ya definida... qué podrá ser? 

Desde ya gracias

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Juampisaez** [comment]
Hola @luzmagurzua 
Mm, puede ser que el archivo donde instanciaste Barco, no hayas importando tu clase Barco. Si puedes subir a tu repo tu tarea y decirme donde instancias la clase, asi te podria ayudar de mejor manera.

Quedo atento :)
