### ISSUE TITLE
¿Debe gitignore estar dentro de la carpeta T2? ¿Debo ignorar .keep?

### ISSUE THREAD

**Issue by VAMarques** [IIC2233/Syllabus#291]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el diagrama del enunciado podria parecer que .gitignore debe estar dentro de la carpeta T2, pero generalmente se encuentra en la carpeta base del repositorio.
![imagen](https://github.com/IIC2233/Syllabus/assets/141939409/ef691a67-0754-401d-aa0a-b88f3a261d43)

Por otra parte en la carpeta de entrega final, hay un archivo .keep, ¿Debo ignorarlo? ¿Porque esta ahi?
![imagen](https://github.com/IIC2233/Syllabus/assets/141939409/7fd30bdd-742d-48b0-a095-898405e51c00)

**Comment by cbuerger02** [comment]
Hola, en la Issue #57 se explica donde debe ir el .gitignore :) Si bien es una issue de la T1, aplicaría lo mismo para la T2
Por otra parte, en cuanto al .keep, una vez que agregues archivos te recomiendo que lo borres (no se penaliza si no lo haces, pero es buena práctica). Como contexto, el .keep sirve para que git "trackee" las carpetas que no tienen nada originalmente.
