### ISSUE TITLE
Duda sobre oleada zombie

### ISSUE THREAD

**Issue by vvialbarros** [IIC2233/Syllabus#291]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Pueden 2 zombies distintos atacar en la misma coordenada en una misma oleada zombie? En el caso de que no puedan, que debo hacer en el caso de que por ejemplo, en la oleada zombie en la dificultad dificil me invaden 10 zombies y mi jardin tiene menos de 10 casillas, por ejemplo en el jardin_pequeño que es un jardin 2x2 solo hay 4 casilleros, en ese caso tengo que hacer que los 6 zombies restantes simplemente no ataquen ninguna casilla?

**Comment by CatalinaBO** [comment]
Hola! Dos zombies si pueden atacar en una misma coordenada durante una misma oleada, siempre cuando se realice un ataque primero, se actualicen los atributos correspondientes, y luego se realice el siguiente ataque. En caso de que haya una mayor cantidad de zombies en comparación a la cantidad de casillas, puedes asignar los zombies que te quedan en casillas que ya fueron atacadas! 
Igualmente debes explicitarlo en el README, ya que de todas formas puedes elegir otro método que te parezca conveniente, siempre cuando no se contradiga con el enunciado.

**Comment by vvialbarros** [comment]
Si es que ya lo programe para que no se puedan atacar 2 veces la misma casilla lo puedo dejar asi y explicarlo en el readme? Es que en el enunciado decia que cada zombie debe atacar una casilla diferente o almenos eso es lo que yo entendi. "Cuando ocurre este evento, un grupo de ZOMBIES_DIFICULTAD zombies atacará tu jardín, cada uno eligiendo una casilla diferente"

**Comment by CatalinaBO** [comment]
Mil disculpas, no me percaté de esa parte del enunciado :( Es correcto lo que dices, cada zombie debe atacar a una casilla diferente, por lo que puedes avisarle al usuario que N cantidad de zombies no pudieron realizar los ataques debido a que no quedaban casillas disponibles, o como tu estimes conveniente, explicando la manera que escogiste en el README. 

Editaré el comentario anterior para que no surgan confusiones, muchas gracias!

**Comment by vvialbarros** [comment]
Ok muchas gracias!
