### ISSUE TITLE
git ignore

### ISSUE THREAD

**Issue by cnillanes** [IIC2233/syllabus#291]
Hola! llevo toda la tarde intentando borrar los achivos entregados de mi repo porque ya los habia subido antes de leer que habia que incluirlos en el gitignore y no me resulta  :( Busqué en internet y lei las otras issues pero tampoco me ha servido.
En este momento el git ignore lo tengo en la carpeta de mi repo y no en la tarea en si misma porque nose porque no me dejaba.. la cosa es que igual intenté crear un archivo .gitignore dentro de T00 para escribir ahi los entregados y no me los borró, de hecho me creó el gitignore, lo subió a la nube y pese a que yo lo borré despues de mi pc e hice git push no se ha borrado del repo, asi como tampoco los archivos entregados que si tengo escritos dentro del gitignore
Ayuda :( ya no se que mas hacer

**Comment by matiasmasjuan** [comment]
Hola @cnillanes !

Intenta revisar las **Issues**: #289 #284 #242 y #207 ya que se hablan de problemas similares. En caso de que el problema persista, no dudes en consultar.

Saludos! :smile:
