### ISSUE TITLE
Duda y solicitud Ayudantía Semana 12 (Networking)

### ISSUE THREAD

**Issue by v1toco** [IIC2233/Syllabus#291]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Holaa, primero que el video de esta ayudantía esta demasiado buena, la ayudante explico súper la materia y de verdad que los contenidos me quedaron muucho mas claros, y bueno mi preguntita iba en relación cuando instanciamos un thread porque hay veces que se ocupa el parámetro daemon=True?

Y mi solicitud era de que si existe la posibilidad de que puedan subir el archivo de esta ayudantía??

**Comment by camilagonzalezp** [comment]
¡Hola @v1toco!

Que bueno que te haya gustado la ayudantía! Me alegro mucho ☺️

Respecto a tu duda, se hace que ciertos threads sean `Daemon` dependiendo del comportamiento que se le quiera dar al programa. Por ejemplo, en el servidor, para aceptar a los clientes no se hizo que ese thread fuera `Daemon`, ya que queremos esperar a que este thread termine para que el programa termine de ejecutarse, porque sino apenas termine el thread principal, este thread también se terminaría y nunca se aceptarían clientes. Por otra parte, para escuchar a cada cliente (en el servidor) y para escuchar al servidor (en el cliente) sí se hizo que estos thread fueran `Daemon`, ya que se quiere que si el programa termina de ejecutarse se pare de escuchar y se termine el thread. Esto no va a ser igual en todos los casos, sino que depende de cómo tengas modelado tu programa.

Y con respecto a tu solicitud no hay ningún problema, se acaba de subir la presentación y se encuentra en la carpeta AY7.5.

Ojalá que te haya quedado más claro, sino cualquier cosa no dudes en volver a preguntar.

¡Éxito!✨

**Comment by v1toco** [comment]
Super, graciass
