### ISSUE TITLE
Ventana Juego

### ISSUE THREAD

**Issue by TriniAguilera** [IIC2233/Syllabus#292]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Podría separar el modo constructor con el modo juego en dos ventanas diferentes? Porque en el enunciado mencionan que como mínimo debo tener Ventana Inicio y Ventana Juego, pero puedo crear otras en caso de estimarlo necesario. En caso de separarlo, tendría una Ventana Constructor y una Ventana Juego ademas de la de inicio (por ejemplo).

**Comment by Hernan4444** [comment]
Hola @TriniAguilera 

No hay problema en crear más de una ventana, tal como dice el enunciado, como mínimo deben estar esas 2, pero si quieres dividir la del juego en 2 ventanas, está bien mientras funcione todo 😄.

**IMPORTANTE**: el enunciado indica que no se puede hacer la Ventana de Juego con QTdesigner, por lo tanto, si decides separar el modo constructor del modo juego, se puede, pero ninguno de las 2 ventanas se pueden hacer con QTdesigner (esto incluye transformar un `.ui` en un `.py`), porque ambos elementos (constructor y juego) pertenecen, originalmente, a la Ventana de Juego, la cual no permite QTdesigner. 

En resumen, **la única ventana que se puede hacer con QTdesigner en la Ventana de Inicio, ninguna más.**

Mientras respetes esa instrucción del enunciado, está todo bien 👍 

Saludosヾ(＾-＾)ノ

**Comment by Nestor1234m** [comment]
He one
