### ISSUE TITLE
No me corrigieron tarea 1

### ISSUE THREAD

**Issue by jgespinosa10** [IIC2233/Syllabus#292]
Me sale un 1 en la tarea y ningún comentario de que la hubieran corregido.
Como puedo mandarla a recorregir? Probablemente fué porque la mandé como Tarea01 en vez de T01

**Comment by FernandoPieressa** [comment]
Hola!

El formato de recorrección se encuentra en https://iic2233.github.io/recorreccion/

Saludos!

**Comment by sebacruzd** [comment]
Hola,

Era de suma importancia que la carpeta se llamara T01, porque como son más de 200 alumnos, se usa un script que descarga automáticamente todas las carpetas T01 de cada alumno. Por esto, deberás llamar T0X a cada carpeta de las siguientes tareas.

Deberás recorregir y habrá un descuento por esto.

Saludos!
