### ISSUE TITLE
Error al hacer Git push

### ISSUE THREAD

**Issue by allisonaguilar** [IIC2233/syllabus#292]
Hola! sin querer subi parametros.py le di delete al archivo para eliminarlo de mi repo, pero ahora al querer subir una nueva versión de la tarea me sale el siguiente error, si pudieran ayudarme lo agradeceria un montón!
![Captura de Pantalla 2020-08-29 a la(s) 17 54 00](https://user-images.githubusercontent.com/62110058/91646796-0102c300-ea21-11ea-9d88-150e50393cd1.png)

 :(

**Comment by danckoo1** [comment]
Hola! Parece que tienes cambios en tu repo de github que no has descargado a tu repo local. Trata de realiza un `git pull` primero y luego haces los `add`, `commit` `Push` Necesarios 
Saludos

**Comment by allisonaguilar** [comment]
![Captura de Pantalla 2020-08-29 a la(s) 18 20 46](https://user-images.githubusercontent.com/62110058/91647076-65735180-ea24-11ea-80a8-8f688d6587a0.png)

Lo hice y ahora me arroja ese error :(

**Comment by danckoo1** [comment]
Al parecer tu archivo de parámetros se hubiera modificado si se llevaba a cabo el pull por lo que se aborto. Lo que yo haría sería copiar el archivo de parámetros, luego hacer `git add parámetros.py`, `git commit` . Luego haces un `pull` Y si es que se modificó tu archivo de parametros, pegas La copia que le hiciste al anterior y por último un `add`, `commit` y `push` como siempre.
Puede que exista una forma más óptima, pero es lo que se me ocurre a primera vista, avísame si resulta!

**Comment by furcelay** [comment]
Hola!
Ya que queda poco tiempo intentaré ayudarte yo. Como dice el mensaje de git, puedes hacer git add y commit de ˋparametros.pyˋ, no podrás hacer push, después del commit haz pull y después sigues con el push.

Eso debería funcionar.
Saludos!

**Comment by allisonaguilar** [comment]
Lo logre! Muchísimas gracias!
