### ISSUE TITLE
Comunicación server-cliente

### ISSUE THREAD

**Issue by JavierMoralesD** [IIC2233/Syllabus#292]
* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En cuanto a la comunicación server-cliente, quería saber si los mensajes enviados deben ser en "paquetes" del largo obtenido luego de codificar el mensaje (4 bytes, 4 bytes, 36 bytes, 4, 36, ...) o pueden ser enviados, por ejemplo, como un solo paquete de bytes.

**Comment by AntonioVenegas** [comment]
Hola @JavierMoralesD, la idea es que cuando quieres enviar un mensaje codificado, lo mandes en un solo array de bytes (1 mensaje = 1 paquete de bytes), ya que así es más fácil y rápido reconstruir el mensaje, que en cambio esperar a que el cliente mande el mismo mensaje separado varias veces (además que si ocurre una desconexión repentina, puede que no sea posible reconstruir el mensaje o se mezcle con los de otro cliente).

Saludos :)

**Comment by AntonioVenegas** [comment]
Hola, una corrección, cuando se envia un mensaje entre cliente-servidor, efectivamente debes codificar el mensaje en bloques y enviar los bloques por separado (recomiendo mirar el ejemplo que sale en el enunciado 7.1.6), además, el receptor del mensaje debe asegurarse de también recibirlos de a un paquete. En general la forma en como se implemente es muy parecida a la experiencia 4 y los contenidos, asi que te recomiendo revisarlos :).

Saludos y perdón por la equivocación.
