### ISSUE TITLE
Etapa 2 [Workflow] 

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#292]
Estoy un poco (muy)  perdida con lo del codigo que ya viene... Mis dudas principales son las siguientes:
1. ¿Hay que estudiar el material de clases -GUI para entender el código de Gui.py y Main.py? ¿Es necesario?
2. No entiendo muy bien a qué se refieren con estudiar esta sección, ya que es la interfaz gráfica, podrían ser más específicos en cuanto a qué parte Gui y Main debemos entender para poder trabajar con ella.
3. Como no hay que hacer clases para esta tarea y el menú del programa no está hecho por nosotros, en que parte hay que  llamar a las funciones que hagamos para que se ejecuten las funcionalidades (no sé si se entiende esta pregunta)...

**Comment by iqacevedo** [comment]
Hola!
1-. No es necesario que estudies el material de clases, ya que no se busca que modifiques la interfaz, solo que interactues con ella (modificando los dos métodos que se mencionan en el enunciado). En estricto rigor solo necesitas trabajar con el código de main.py.
2-. Se refiere a que interactues con los dos métodos que se te indican de la interfaz para que entiendas bien como utilizarlos (ejemplo: ingresa una consulta en la interfaz e imprime `querry_array` del método `procces_consult`).
3-.Puedes importar alguna de tus funciones a main.py  y ejecutarlas en alguno de los dos métodos de T03Window. 

Espero haber respondido tus dudas.

Saludos !
