### ISSUE TITLE
AF3.Revisión de commits Actividades

### ISSUE THREAD

**Issue by juan-palma-1** [IIC2233/syllabus#292]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
Saludos, luego de revisar el commit que se va a revisar de la AF3 me surgió la siguiente duda: **¿Se revisan solo los archivos que se pushean en el último commit?**, me explico. El último push que realicé fue solo con el archivo `main.py` puesto que `emergencias.py` lo terminé antes, y no lo volví a incluir en el último push. Se revisan los ultimos commits de cada archivo o debí incluirlo en el último push también?. Gracias 👍 😢 .

**Comment by tqmbanados** [comment]
No te preocupes! Se revisa el estado de todo tu repositorio al momento de tu último commit 😸
