### ISSUE TITLE
Duda sobre la dificultad del juego

### ISSUE THREAD

**Issue by JosefaATP** [IIC2233/Syllabus#292]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Cómo están?

En el comienzo de las instrucciones dice que darán la dificultad del juego, pero lo que no me queda muy claro es donde hay que aplicar esto? o como se aplica? Que diferencias hay con las funciones descritas, por ejemplo que hacen de diferentes los métodos según la dificultad? porque no lo vuelven a mencionar en el enunciado.

Gracias!

**Comment by augustayanez** [comment]
Te sugiero ver la issue #281 donde clarifica que cambios implican las diferentes dificultades de juego.
