### ISSUE TITLE
QGraphicsView - Mapa

### ISSUE THREAD

**Issue by jitorcas** [IIC2233/syllabus#292]
Hola! estoy trabajando con `QGraphicsView` y puedo lograr que mi mapa se adapte a cualquier tipo de dimensiones, pero al momento de crear una interfaz en designer y mostrar el mapa del juego en la interfaz hay mapas que me aparecen con scrollbar ( se visualiza todo el mapa del juego pero como es de mayor cantidad de casillas no se puede ver todo al mismo tiempo, si no que hay que moverlo con los scrollbar para visualizar el juego completo)  esto es considerado como un error? o está bien? 
saludos!

**Comment by Hernan4444** [comment]
Hola,

Si eso ocurre cuando hay un N muy grande de pixeles o el mapa tiene muuuchos cuadros, no se preocupe, está bien que aparezca un scrollbar para poder desplazarse en el mapa y ver todos los pixeles, pero si el N es pequeño o hay pocas casillas, lo cual hace que "se debería ver en toda la pantalla" e igual aparece scroll, ahí está mal.

Saludos ✌️
