### ISSUE TITLE
que Qtimer comience enseguida y luego por intervalo 

### ISSUE THREAD

**Issue by solebravo** [IIC2233/Syllabus#292]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! estoy teniendo un pequeño problema con el Qtimer que utilizo para que aparezcan los zombies. La cosa es que este empieza un intervalo después de que se presiona inicio (si el intervalo es de 7 segundos, una vez se apreta el   botón hay que esperar estos 7 segundos para que aparezca el primer zombie) y no he encontrado como arreglarlo, por lo que quería saber si hay alguna función que lo arregla. Le hice push a mi repositorio por si necesitan mirarlo.
Gracias de antemano!

**Comment by Hernan4444** [comment]
Hola @solebravo 

Lo que pasa es que los QTimer ejecutan la función cada vez que se acaba el tiempo seteado en el `setInterval`. Por lo tanto, si lo tienes en 7 segundos, no tendrás de otra que esperar 7 segundos para la primera ejecución del QTimer.

Una opción que se me ocurre es que cuando inicializar el Qtimer que está conectada a tu función de crear zombies función, tambien crear y empzar un thread que ejecute tu función 1 vez y luego se muera. Como dicha función no está en un `while`, el thread solo hará una pasado lineal a ese código (creará un zombie) y luego se morirá. De esta forma te aseguras que con el start del thread tambien se ejecute al inicio y luego esperes 7 segundos para el segundo zombie producto de tu Qtimer.

Cuantanos como te vá con eso, cualquier cosa estaremos atentos al foro,
Saludosヾ(＾-＾)ノ

**Comment by solebravo** [comment]
Hola, lo solucioneeeeeeee!!!! por si a alguien le sirve, lo que hice fue primero settear un intervalo muy chico (de 1) que conectaba con la función crear zombies, y luego en esta funcion volver a settear el intervalo pero esta vez con el intervalo de aparición y funcione sin ningún problema, muchas graciasssssss.
