### ISSUE TITLE
Duda con atributos heredados

### ISSUE THREAD

**Issue by macagamerre** [IIC2233/syllabus#292]
Hola, mi duda es la siguiente:
Tengo una clase Padre que hereda a varias subclases. Quiero que las subclases hereden una función que usa parametros de un diccionario. El problema es que cada subclase tiene su propio diccionario y no sé como indicarle a la función de la clase Padre que ahora va a trabajar con otro diccionario. 
Creo que no estoy logrando renombrar la variable self.diccionario de la clase padre en las subclases. ¿Cómo puedo solucionarlo?
Es algo de este estilo:
`
class Padre:
    def __init(self, atributo, otro_atributo):
        self.atributo = atributo
        self.otro_atributo = otro_atributo
        self.diccionario = dict()
    
    def usar_parametros_diccionario(self):
        a = self.diccionario.get("llave común para todos los diccionarios")
        b = self.diccionario.get("otra llave común para los diccionarios")

class sublcase1(Padre):
    def __init__(self):
        super().__init__(*args)
        self.diccionario = diccionario_de_esta_clase
        #así espero que se ejecute la función usar_parametros_diccionario() con este diccionario

`

¿cómo puedo hacerlo para no tener que redifinir especialemente para cada subclase?

**Comment by jaromero6** [comment]
Hola!
Si entiendo bien, lo que quieres hacer es que todas las clases tengan un diccionario compartido, para lograr esto podrías crear un diccionario como atributo de clase, por ejemplo:
```
class A:
    diccionario_comun = dict()
    def __init__(self):
        self.a = None

class B(A):
    def __init__(self):
        super().__init__()

class C(A):
    def __init__(self):
        super().__init__()


b = B()
c = C()

b.diccionario_comun[1] = "hola"  # Creamos la llave 1 para diccionario_comun
print(c.diccionario_comun[1])  # El cambio se ve reflejado en otras instancias
```
En este ejemplo las clases B y C comparten un diccionario en común  que es diccionario_comun, lo que le hagas a ese diccionario se modificará automáticamente en todas las instnacias de A,B o C. 

Espero haberte ayudado

**Comment by macagamerre** [comment]
Gracias por la respuesta, pero creo que me expliqué mal jaja. 
Lo que quiero es una función comun que use los diccionarios de cada subclase (que tienen distinto contenido pero las mismas llaves)

**Comment by jaromero6** [comment]
Tú duda entonces es ¿cómo la clase padre identificaría que el diccionario que está usando es de la clase B que heredó de él o de C?

Una solución para esto sería algo similar a lo que ya tienes: 
```
class A:
    def __init__(self):
        self.a = None
        self.diccionario = {}
    
    def mostrar(self):
        print(self.diccionario)

class B(A):
    def __init__(self, key, value):
        super().__init__()
        self.diccionario[key] = value

class C(A):
    def __init__(self, key, value):
        super().__init__()
        self.diccionario[key] = value


b = B(1, 'Soy B' )
c = C(1, 'Soy C')

b.mostrar()
c.mostrar()
print(b.diccionario[1])
print(c.diccionario[1])
```
En el código que mandaste tú, no sería necesario redefinir el diccionario al heredar, este será único para cada instancia. Por ejemplo, fijate en el ouput de este código similar al que mandaste tú:
```
class Padre:
    def __init__(self, atributo, otro_atributo):
        self.atributo = atributo
        self.otro_atributo = otro_atributo
        self.diccionario = dict()

    def usar_parametros_diccionario(self):
        a = self.diccionario.get(1)
        b = self.diccionario.get(2)
        print(a,b)

class sublcase1(Padre):
    def __init__(self, *args):
        super().__init__(*args)
        self.diccionario = {1: args[0], 2:args[1]}

a = sublcase1("hola", "chao")
b = sublcase1("HOLA", "CHAO")
a.usar_parametros_diccionario()  # Solo usa los atributos de a
b.usar_parametros_diccionario()  # Solo usa los atributos de b
```
Espero aclarar tús dudas, quedo atento a si te sirvió

**Comment by macagamerre** [comment]
ahora entendí. Muchas gracias!!
