### ISSUE TITLE
Formato diagrama de clases

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#293]
Hola, en los diagramas de clase no se especifican las properties? y qué significan los + o - en el listado de atributos/métodos?

**Comment by dlmed** [comment]
Asociado a lo anterior, los atributos cuyas properties cambian, de acuerdo a la subclase, se deben especificar en la lista de atributos de esta subclase en el diagrama?

**Comment by dlmed** [comment]
Aparte, es necesario que todos los bloques estén conectados de alguna forma? qué pasa si no hay una clase como la de tipo `Juego` en el material?

**Comment by mpsubiabre** [comment]
Hola @dlmed!
Los signos + y - indican si un atributo/ método es publico(+) o privado(-) 
En el diagrama de clase si se especifican los tipos de properties que es\tiene el atributo mediante el uso de la notación <get/set/del> 
Si no existe una clase de tipo juego, efectivamente no estarán todos los bloques conectados. Tu diagrama de clase debe representar fielmente como modelaste el problema, pero ten en cuenta que es necesario que estos bloques en algún lugar se unan para que haya interacción (muy útil para esto una clase del tipo juego 👀 )

Si te quedan dudas sigue comentando esta issue:)

**Comment by lewebe** [comment]
Yo tengo otra duda: los abtract methods como se indican en el diagrama?

**Comment by mpsubiabre** [comment]
Hola @lewebe !

Investigue un poco, y en general se utiliza la letra tipo "italic" que es _este tipo de letra_ ara escribir el metodo :)
