### ISSUE TITLE
Cheatcode K+I+L sobre zombies aun no generados

### ISSUE THREAD

**Issue by kolk3y** [IIC2233/Syllabus#293]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Respecto al cheatcode K+I+L mi duda es ¿Qué sucede al momento de llamarlo mientras aún faltan zombies por generarse? ¿Se debe eliminar a los zombies actuales y luego ir eliminando uno a uno los que se van generando posteriormente, o eliminar a los actuales, detener la generación de los restantes y sumar la puntuación correspondiente?

Gracias de antemano por la respuesta! 🌱🌱🌱

**Comment by jlizamajara** [comment]
Hola @kolk3y!
Lo segundo que señalas es lo correcto. Al utilizar el cheatcode K+I+L en medio de una partida  se eliminan los zombies actuales y y los "por generarse", terminando inmediatamente la partida (es como si los hubieses matados a todos).
Saludos!

**Comment by armas01** [comment]
El puntaje añadido de K I L no queda a criterio de uno? ya que solamente explica que los zombies deben ser eliminados, pero no dice que se debe asignar puntaje a ello

**Comment by jlizamajara** [comment]
Hola @armas01!
 Al utilizar K+I+ L es como si acabaras la ronda matando/eliminando todos los zombies, por ello el puntaje asignado por ello sería  (según el apartado Puntaje del enunciado) puntaje_ronda + puntaje_extra.
Saludos!
