### ISSUE TITLE
Pistas y cantidad de contrincantes

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus#293]
Por que dice que hay que elegir los contrincantes de forma aleatoria dependiendo de la cantidad que te piden, Si en las pistas lo unico que dice son los contrincantes que participan, no la cantidad minima que tienen que haber de esos contrincantes.

**Comment by gatochico** [comment]
Hola! La respuesta a esto está en la issue #123 . Éxito con tu tarea!

**Comment by MartinAracena** [comment]
Y tengo la duda sobre el vehiculo que cada contrincante usa, como se elije esto? No vi que apareciera esto en ninguna parte del enunciado.

**Comment by gatochico** [comment]
En esa misma issue también se preguntó eso :0 Los últimos dos comentarios lo abordan. (Spoiler: Es a criterio tuyo)
