### ISSUE TITLE
Error QPixmap

### ISSUE THREAD

**Issue by benjastraub** [IIC2233/Syllabus#293]
Hola, me pasa que algunas veces al ejecutar la tarea, en la mitad del juego me aparece el siguiente error `QPixmap::scaled: Pixmap is a null pixmap` y no aparece la siguiente pieza. A veces incluso pasa a penas se ejecuta

¿Es un error producto del front-end o puedo hacer algo para solucionarlo?

**Comment by iqacevedo** [comment]
Hola, 

Leíste la issue #290 y #280, son de errores similares.

Saludos !
