### ISSUE TITLE
Cerrar servidor

### ISSUE THREAD

**Issue by MystEdu** [IIC2233/Syllabus#293]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, en el enunciado no vi sobre cuando cerrar el servidor, espero no haberme saltado donde lo dijera, por lo que dejo mis dudas:

- ¿El servidor se cierra solamente cuando se le fuerza a salir? 
- Cuando se indica que si el cliente presiona salir se debe cerrar el programa, ¿se debe cerrar también el servidor o solamente la ejecución del cliente?

De antemano, muchas gracias.

**Comment by Martinaurrutia** [comment]
Correcto, el servidor solo se cierra cuando se le fuerza a salir, y en el caso en que el cliente sale del programa, este se desconecta del servidor, pero el servidor no se cierra.

**Comment by MystEdu** [comment]
Vale muchas gracias 😄
