### ISSUE TITLE
Duda con VSC

### ISSUE THREAD

**Issue by pablofaundez** [IIC2233/syllabus#293]
Hola! Quería preguntar si en visual studio se puede configurar que no se considere algún tipo de error en particular.
En una parte de mi código tengo algo tipo (no sé como indentar acá :c ):
`for i in range(0, 2):`
    `    for j in range(0, 2):`
`        hacer_algo(i)`
La cosa es que me marca un warning de que la variable `j` no se está utilizando. Sería más satisfactorio que no me aparezca esto al terminar las tareas jajaja
Gracias!

**Comment by aaossa** [comment]
Hola @pablofaundez , la verdad no sé cómo se hace en VS Code, pero sí podría decirte lo que seguramente tu editor espera que hagas. En primer lugar, obviamente la idea es que no definas variables que no vas a usar, por distintas razones (ahorrar poder de procesamiento, ahorrar memoria, etc.), pero a veces es necesario hacerlo, como en tu caso. Normalmente, se utiliza el nombre de variable `_` para marcar que esa variable no te importa. Por lo tanto, una posible solución sería hacer esto:

```python
for i in range(0, 2):
    for _ in range(0, 2):
        hacer_algo(i)
```

Otro caso en que podría servirte este método, es cuando una función retorna más de un valor, pero solo te sirve uno. Imagina que existe una función `mayusculas_y_minusculas(texto)`, que te retorna dos cosas: el texto en mayúsculas y el texto en minúsculas. Si solo necesitas el primer resultado, podrías hacer algo como lo siguiente:

```python
texto_mayusculas, _ = mayusculas_y_minusculas(texto)
```

(Obviamente el último ejemplo era solo para mostrar el uso de `_`, ya que podrías usar `str.upper` y `str.lower` para lograr el mismo efecto)

Ojalá te sirva ✨

**Comment by pablofaundez** [comment]
Muchas gracias!
