### ISSUE TITLE
Duda sobre simular nueva hora

### ISSUE THREAD

**Issue by tamyhan** [IIC2233/syllabus#293]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, no entiendo bien como modelar el paso del tiempo durante el programa. Cómo relaciono el tiempo, con la velocidad de los barcos y el largo del canal?

**Comment by mistico0121** [comment]
Hola
Cada "unidad de tiempo" los barcos se mueven una determinada distancia. Hay barcos que son más rápidos y más lentos, por los que a algúnos les tomará mas tiempo cruzar el canal, pues se moverán menos espacios por unidad de tiempo, y otros se moverán más rápido. 

Saludos

**Comment by tamyhan** [comment]
Pero lo que no entiendo es cómo definir esa unidad de tiempo. Defino una variable que parta en cero y luego vaya aumentando cada vez que se termine una hora en la simulación? O tengo que usar time ?

**Comment by mistico0121** [comment]
Esa es una posibilidad. No es necesariamente una unidad temporal como segundo o minuto, si no que es del programa. Puedes verlo como si fuera un "turno", y cada turno ocurren cosas.

**Comment by tamyhan** [comment]
Ahh okaa gracias!
