### ISSUE TITLE
Como puedo usar "locks" y ".join()" en Qthreads

### ISSUE THREAD

**Issue by jfpena1** [IIC2233/syllabus#293]
Me pasa que segui la recomendacion de utilizar Qthreads y he tratado de ver la documentacion pero no logro encontrar como ocupar algo similar a los locks de threads y al metodo .join(). Alguna recomendacion? Sera mejor simplemente trabajar con threads entonces?

Gracias!

**Comment by jaromero6** [comment]
Hola, para los Locks te recomendaría ver lo dicho en esta issue #285. Por otra parte para implementar algo como el join con QThread, te recomiendo ver el método wait de esta clase [aqui](https://www.riverbankcomputing.com/static/Docs/PyQt4/qthread.html#wait) (ese es de **PyQt4**). También un poco más explicado aunque es en C lo puedes ver en este [link](https://doc.qt.io/qt-5/qthread.html) que es una documentación más reciente.
Éxito con la tarea

**Comment by jfpena1** [comment]
gracias!
