### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#293]
Cuando corro main.py no se ve en la interfaz la parte del menu donde se abre el archivo consultas.json... ¿qué está pasando? (Adjunto pantallazo para que se entienda lo que no aparece en la interfaz)
<img width="551" alt="captura de pantalla 2017-04-24 a las 11 50 50 a m" src="https://cloud.githubusercontent.com/assets/26121354/25343207/bf9f7bde-28e4-11e7-9b0f-b657b5e40d40.png">
Saludos!

**Comment by stephichau** [comment]
@acrojas2 fijate arriba a la izq en la barra, deberia salir algo asi:
<img width="167" alt="screen shot 2017-04-24 at 12 09 05 pm" src="https://cloud.githubusercontent.com/assets/16126322/25343949/f67d38d8-28e6-11e7-836f-7000537e46fd.png">

saludos :)!
