### ISSUE TITLE
Duda sobre enunciado de la función codificar_mensaje

### ISSUE THREAD

**Issue by angedvq** [IIC2233/Syllabus#294]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo dificultad al comprender la descripción de la función codificar_mensaje. No entiendo muy bien a que se refiere la parte que dice "(...) y los elementos que siguen son, de forma alternada, el bytearray que representa el
número de bloque y el bytearray que representa a un bloque con parte del mensaje original.". Tampoco me queda muy claro el ejemplo brindado xD 
Agradecería me lo pudieran explicar de una manera más clara para saber como modelar la función pedida

**Comment by bembem3** [comment]
Hola, yo tengo la misma duda, si se supone que los mensajes se deben separar de a 36 bytes, donde cada 36 bytes es un bloque por que la lista de la salida solo tiene 3 elementos, osea que ahí se asumió que siempre se tendrá UN SOLO bloque? o otra función debiese ir separando los elementos cada 36 bytes y luego aplicarle la función de codificar a cada bloque respectivamente? Si esto resulta ser así, en ese caso la función no debería también recibir el número de bloque que se esta codificando? esta medio confuso el enunciado. De antemano, muchas gracias

**Comment by gasparbenavente2** [comment]
Como se puede ver en la parte 7.1.3 del enunciado, el mensaje codificado tiene la siguiente forma.
1. Primeros 4 bytes: Largo del mensaje
2. Bloques de 4: Numero del bloque que viene justo después
3. Bloques de 36 bytes: el mensaje

El mensaje queda compuesto de la forma 1-2-3-2-3-2-3-2-3... hasta terminar el mensaje.

Para los bloques de 36 siempre tendrán que ser exactamente de 36, es decir, si un mensaje tiene un largo no divisible por 36 se tendrá que rellenar con ceros (complemento de ceros) para poder completar todos los bloques. Y cada uno va con un bloque de 4 bytes justo antes indicando el numero de bloque.
