### ISSUE TITLE
Duda sobre uso de probabilidad de encallar() en simulación

### ISSUE THREAD

**Issue by raibd** [IIC2233/syllabus#294]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda de como hacer que un barco encalle en base a su probabilidad. Si estoy simulando el canal, a medida que pasan las horas, como es que se determina si un barco encalla o no?. Lo único que se me ocurre es hacer un evento aleatorio usando random pero en ese caso para que servirian las probabilidades? Dicho de otra manera, que hago con una probabilidad de 0.7 por ejemplo?
Gracias

**Comment by manearaya** [comment]
Hola @raibd!

Debes considerar la probabilidad de que ocurran los eventos cuando determinas si van a ocurrir o no. 
Si tienes un evento que puede ocurrir con una probabilidad de 0.7, por ejemplo, podrías generar una variable con valor aleatorio entre 0 y 1: si esta variable es menor a 0.7, entonces el evento debería ocurrir. (Para generar esta variable, te puede ser útil la libreria random).

Saludos!

**Comment by raibd** [comment]
Gracias! me quedo mas claro.

**Comment by mjsifri** [comment]
Hola, estaría bien crear una simulación con una muestra de 100 elementos, y que por ejemplo, si la probabilidad es 0,4 se generen 40 "S" y 60 "N", y luego seleccionar una al azar? Siendo "S" por ejemplo que el evento ocurre y "N" que no.
Saludos!

**Comment by manearaya** [comment]
Hola @mjsifri!

En el caso que tú dices estaría bien, porque al final la probabilidad de sacar una S es la misma que la probabilidad del evento. De hecho, eso te sirve para cualquier probabilidad, porque está permitido redondear las probabilidades a 2 decimales, entonces usando una lista de 100 strings te debería alcanzar.

Éxito con la tarea!
