### ISSUE TITLE
parametros.py

### ISSUE THREAD

**Issue by YoGandalf** [IIC2233/syllabus#294]
Los parametros generacion_1 y generacion_2 para saber la cantidad de enemigos de la siguiente ronda no estan en parametros.py
Hay que determinarlos nosotros?

**Comment by gatochico** [comment]
Hola! El archivo parametros.py contiene sólo algunos de los parámetros que se indican dentro del enunciado, a modo de ejemplo. Debes completar dicho archivo con el resto de los parámetros del enunciado. Saludos!
