### ISSUE TITLE
Fecha entrega de diagrama

### ISSUE THREAD

**Issue by BelenMadariaga** [IIC2233/syllabus#294]
Solo para confirmar: el diagrama tiene fecha límite de entrega hoy hasta las 20 hrs, verdad? Si se entrega después cuenta como atraso?

**Comment by entamburini** [comment]
Hola Belén! :D 

Si, es parte de la entrega final, el readme es algo completamente a parte de la entrega. Si se entrega después de la fecha (hoy a las 20 horas) es considerado atraso :(

Saludos!

**Comment by Dafnemami** [comment]
den una hora más para entregar la tarea <3

**Comment by mpbascunan** [comment]
@entamburini

**Comment by entamburini** [comment]
🙄
