### ISSUE TITLE
SOS Python 3.6.5 NO SABE RESTAR

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#294]
¿Dónde se pueden reportar bugs?
![image](https://user-images.githubusercontent.com/37153467/39081150-93d6b530-4512-11e8-9343-82f700140251.png)

Voy a ver si la versión 3.6.4 está igual o no.
¿A alguien más le pasa? 😰😰😰

**Comment by IchottMano** [comment]
@jmwielandt Hola!

Eso no es un error de python, sino que es un problema que surge debido a como los computadores trabajan con los floats, produciendo errores con números que no pieden ser representados en forma binaria correctamente. Esto pasa si estas en python 2, 3 o cualquier lenguaje que trabaje con floats.
Lo que recomiendo en este caso es trabajar con una función que redondee el resultado.

Saludos!

**Comment by jmwielandt** [comment]
bueno, gracias uwu
