### ISSUE TITLE
Dudas gitignore

### ISSUE THREAD

**Issue by SebastianFerra** [IIC2233/syllabus#294]
Hola! no entiendo para que sirve ni como ocupar el git ignore, por consecuencia no sé cuándo es prudente y útil usarlo. Si alguien me aclarara esto lo agradecería mucho c:

**Comment by Tsbalart** [comment]
Hola @SebastianFerra!
Probablemente la mayoría de tus dudas con respecto al archivo .gitignore ya fueron resueltas en la issue #93, te invito a revisarla y si sigues con duda volver a comentar!
Saludos!

**Comment by SebastianFerra** [comment]
Creo haber leído que había un tutorial de como usar git ignore pero no recuerdo donde está, ¿dónde lo puedo econtrar?

**Comment by Tsbalart** [comment]
Hola @SebastianFerra 
Puedes encontrar un ejemplo y una explicación mas detallada de este archivo en la carpeta principal del syllabus https://github.com/IIC2233/syllabus/blob/master/.gitignore
Saludos!
