### ISSUE TITLE
Error en consola

### ISSUE THREAD

**Issue by monicabelen** [IIC2233/Syllabus#294]
Hola, estoy tratando de instalar PyQt5 pero cuando escribo "python3 configure.py" en el cmd, me retorna lo siguiente: **"python3 no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable."** Lo mismo si pongo "pip3 uninstall pyqt5" pero en vez de python3, sale "pip3".
De hecho no se si además tengo que instalar pip3(?)

Ayuda!! :(

**Comment by sebacruzd** [comment]
Has probado con python en vez de python3 y pip en vez de pip3?

**Comment by monicabelen** [comment]
Sí y nada..

**Comment by sebacruzd** [comment]
Creo que es un problema por las variables de entorno. Esto se debe a la instalación de python y la ruta en que quedó instalado, por eso no te reconoce pip.

Puedes probar lo que sale [aquí](https://github.com/BurntSushi/nfldb/wiki/Python-&-pip-Windows-installation) y setear las variables de entorno a la ruta correspondiente en tu pc.

Prueba con eso y avísame cómo te va 😁

**Comment by monicabelen** [comment]
No me sirvió.. :(

**Comment by iqacevedo** [comment]
Probaste también con py en vez de python?
También con **py -3.5 -m pip install pyqt5** o **python3.5 -m pip install pyqt5**?

**Comment by monicabelen** [comment]
Me funcionó!!!! :D 
Gracias!!

**Comment by norman123123** [comment]
que es pip?

**Comment by norman123123** [comment]
Hago esto:
python3.5 -m pip install pyqt5

y me dice:
Requirement already satisfied: pyqt5 in /Users/normanoliden/anaconda/lib/python3.5/site-packages
Requirement already satisfied: sip<4.20,>=4.19 in /Users/normanoliden/anaconda/lib/python3.5/site-packages (from pyqt5)

como hago q funcione en pycharm? pq me sale anaconda?

**Comment by monicabelen** [comment]
Es porque instalaste Anaconda (supongo). En pycharm puedes hacer lo siguiente:
1. Settings
2. Project Interpreter
3. Setuptools
4. Buscar pyqt5 e instalarlo.

Al menos eso me sirvió al mi :D

**Comment by norman123123** [comment]
Actualicé python, ese era mi problema! Ahora funciona todo ok
