### ISSUE TITLE
probabilidad de encallar y pérdida de mercancía

### ISSUE THREAD

**Issue by barbaracalderonr** [IIC2233/syllabus#295]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
*  [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X]Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
*  [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
*  [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola!, tengo una duda respecto a la probabilidad de encallar, cuando un barco es del tipo Carguero, y es atacado por piratas, pierde toda la mercancía a bordo. 
En la formula de encallar, se incluye como el peso de la mercancía, entonces si le roban la mercancía, (el peso de la mercancia ahora es  = 0) cambia la probabilidad de encallar?
Me pasa que lo había implementado así, pero dada la fórmula, pero me estaban dando algunos valores negativos

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]
![image](https://user-images.githubusercontent.com/70455981/115812585-9a6f5280-a3bf-11eb-9202-e25828497b8d.png)

**Comment by tqmbanados** [comment]
Acuérdate que la formula general dice que el valor mínimo que puede tener es 1; es decir, aunque la formula a la derecha te de un valor negativo, debes igualar el resultado a 1 (hay una función para eso).
Me parece bien que tomes la probabilidad considerando la mercancía actual del barco y no la mercancía con que partió. Igual agrega ese supuesto en tu README para que tu ayudante lo tenga en cuenta al momento de corregir.

**Comment by barbaracalderonr** [comment]
mm es que de la fórmula yo había entendido que se te toma el mínimo entre 1, y el numero de la derecha
entonces si es negativo tomaría ese...
o estoy muy perdida??

**Comment by tqmbanados** [comment]
oh, tienes toda la razón, jajaja no sé en qué estaba pensando. Además que la probabilidad debería ser siempre entre 0 y 1. 
De todas maneras, podrías también agregar esa condición de mínimo 0, y agregarlo en el supuesto. Creo que es más correcto que el programa responda al cambio en la mercancía. Voy a preguntar a les ayudantes encargades de la tarea y te respondo más en detalle!

**Comment by tqmbanados** [comment]
Efectivamente no hay problema con que de valores negativos! Además, para calcular la probabilidad igual un número negativo siempre es en el fondo probabilidad 0, pero igualarla manualmente es una buena opción. Siempre puedes incluir el supuesto en tu readme; con tal de que tengas claro lo que hiciste y corra tu programa estará bien.

**Comment by barbaracalderonr** [comment]
bacan muchas gracias!
