### ISSUE TITLE
Duda de los nombres de los tipos de plantas

### ISSUE THREAD

**Issue by DiegooDSC** [IIC2233/Syllabus#295]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holaa, me surgió la duda sobre el atributo tipo de las plantas. Por ejemplo, si nos referimos a la planta Solaretillo, el string sería "Solaretillo" o "S"?

**Comment by CatalinaBO** [comment]
Hola!, el atributo _tipo_ de las plantas sería "Solaretillo". Recuerda que el string "S" se utiliza para realizar la lectura de los archivos y para representar a la planta en el tablero, pero en el inventario se debe poner el string del tipo de planta que hay, por lo que debes considerar el nombre completo!
