### ISSUE TITLE
Tiempo vuelta

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#295]
Cual es la operacion a la que se refieren los corchetes del calculo del tiempo vuelta?

**Comment by jaromero6** [comment]
Hola 
Los corchetes se refieren a la función techo, si no tienes claro como funcionan puedes ver [aqui](https://es.wikipedia.org/wiki/Funciones_de_parte_entera) una explicación en detalle de como funciona.
Pero en términos simples es que en si un número es decimal, entonces te lo aproxima siempre a su entero mayor, si el número es entero, entonces lo deja como está.
Espero haberte ayudado
