### ISSUE TITLE
¿Podemos añadir paths a parametros.py usando os.path.join?

### ISSUE THREAD

**Issue by dvillas28** [IIC2233/Syllabus#295]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

añadirlos de forma correcta con la libreria os y no agregando el path relativo, suelto, como un *string*

Lo pregunto en el caso de que ejecuten la tarea en windows o en linux, el archivo parametros.py se adecue correctamente al sistema operativo y no haya que usar os.path.join en los archivos del cliente/servidor ya que son varias lineas las que hay agregar

saludos!

**Comment by cbuerger02** [comment]
Hola, te recomiendo agregar una lista de strings al archivo de parámetros, y cuando lo vayas a utilizar (en otro módulo) juntas los strings de la lista con os.path.join

**Comment by dvillas28** [comment]
si, al final los deje como strings en parametros.py y deje q un modulo se encargarse de hacerles todas las transformaciones q necesitaba 

gracias igualmente!
