### ISSUE TITLE
Duda sobre botón avanzar y zombies

### ISSUE THREAD

**Issue by bernirosas** [IIC2233/Syllabus#295]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! En el enunciado dice:
"Adicionalmente, dispones de un botón llamado avanzar
que solo funcionará si tienes COSTO_AVANZAR soles. En caso de disponer dicha cantidad de soles y oprimir
el botón, ganarás automáticamente la ronda sin eliminar a los zombies que faltaban, permitiendote
avanzar a la siguiente ronda." Cuando dice "sin eliminar a los zombies que faltaban"  se refiere a que no se cuente el puntaje de eliminar zombies o algo más?

**Comment by Hellonston** [comment]
Hola @bernirosas! Se refiere a que si cumples la condición y presionas el botón automáticamente avanzaras de ronda manteniendo el puntaje acumulado hasta antes de presionar el botón, es decir se "corta" lo que está pasando, capturas el puntaje hasta ese momento y lo pasas al acumulado.
Espero te sirva la aclaración y mucho éxito con la tarea 🙌

**Comment by bernirosas** [comment]
Ya perfecto!
