### ISSUE TITLE
Tareas (en general)

### ISSUE THREAD

**Issue by daniela-carreno** [IIC2233/syllabus#295]
Hola! me salieron un par de dudas para las próximas tareas o actividades en general.
1. Para la T00 habían muchas lineas comentadas a modo de instrucción en el main.py las puedo borrar para programar ? Lo que pasa es que leí en una issue que los comentarios sí se consideran en las 400 líneas, pero sus instrucciones eran muchas entonces me pase al tiro de las 400 líneas y tuve que hacer otro archivo.

2. Es obligación ocupar los contenidos de la semana para las tareas? Por ejemplo, si yo considero innecesario ocupar Clases en la T00, implica que tendría penalización?

3. Necesito ayuda con el .gitignore, el martes habrá alguien en discord que me pueda ayudar ? ya cree una issue, leí las otras relacionadas y aún así no me funciona 😭 

4. Hasta ahora, para debuggear, hago prints entremedio del código. Lo encuentro útil, pero poco práctico. Qué puedo hacer ?

5. Por último, de lo que he averiguado de git es que es súper usado por las ramificaciones que permite. Esto lo enseñan en algún momento del curso? Si quisiera aprender a usar más funcionalidades de git con quien tendría que hablar ?

Muchas gracias ☀️

**Comment by josefinareyes** [comment]
Hola! Respecto a tus dudas:

1. Las líneas comentadas en los módulos que se te entregan son más que nada para guiarte o explicar ciertos códigos, eres libre de borrar los comentarios si los entiendes y no los necesitas para programar!

2. Las tareas están diseñadas para que uses los contenidos de las semanas correspondientes y esto te facilite el proceso; es recomendable usarlos porque facilita tanto hacer la tarea como corregir errores a medida que avanzas en ella, y así tu código queda más legible y organizado 😄.

3. Hay un compilado de issues sobre ```.gitignore```en el compilado de la T00. Si aún leyendo las issues relacionadas sigue sin funcionarte, puedes dejar un comentario nuevo en la issue que creaste sobre tu problema (o aquí 👀 ), crear una nueva issue al respecto, o dejar tu duda por Discord y algún ayudante podría responder!

4. Hay ciertos editores de código que permiten hace debugging de tu código en el mismo editor, dependiendo del que uses puedes buscar cómo hacerlo, pero hacer prints de tus variables siempre es una buena opción!

5. Hay muchas guías sobre el uso de git en línea! Pero si tienes dudas puntuales sobre algo que necesites hacer, puedes hacer issues con ellas para ayudarte más puntualmente.

**Comment by daniela-carreno** [comment]
Gracias por tus respuestas

sobre el punto 4. Actualmente estoy usando sublime text 3 y hago correr los programas desde el IDLE de python o desde la terminal (contexto, mi computador es mac). No logré usar visual studio, lo encontré complicado y me reclamaba por querer extensión .py .  Qué editor me recomiendas? que tenga las opciones de debbugeo.

y de lo último, ha costado mucho seguir instrucciones sobre git. Las leo pero no entiendo o no me resultan (ejemplo con el gitignore 😢 ). Me gustaría saber muchas cosas:
5.1. Cuál es el alcance de github, por qué es tan popular ? 
5.2. Solo he escuchado sobre las ramas, pero no las sé usar. Cuándo se usan? para que? como las integro al main? puedo hacer una rama sobre otra?  
5.3. Qué pasa si avanzo en mi codigo y subí hartos avances, pero me doy cuenta que me conviene más retroceder y cambiar algunas cosas. Puedo retomar pushs anteriores? cómo hago esto ?

Muchas gracias 🙇‍♀️

**Comment by cothidalgo** [comment]
Hola Daniela, 

Si te interesa una forma rápida y buena de _debbugear_, que no dependa de tu editor, puedes utilizar la función `breakpoint()`. Esta la puedes poner en cualquier línea de código y al momento de ejecutar tu programa, se detendrá en esa línea. Podrás escribir las variables para ver sus valores, revisar los retornos de las funciones que tengas, y muchas cosas más! ⭐️ Si quieres  continuar con la ejecución, puedes escribir `continue` desde el terminal. Si quieres terminar la ejecución, puedes escribir `exit`.

Las ramas en git no se revisan en este curso. Pero, probablemente en ramos como Ingeniería de Software comenzarán a verlas. Son especialmente necesarias cuando trabajas en equipo. 

En términos simples, las ramas te permiten tener distintas versiones del código. Si por ejemplo, quieres trabajar en una nueva funcionalidad o _feature_, puedes crear una rama desde la principal. Esto te permitirá trabajar en esa rama sin hacer modificaciones en el código de la rama principal. Una vez que terminas la funcionalidad nueva, puedes hacer `merge` o juntar las dos ramas en solo una: el código inicial junto con tu nueva funcionalidad.

Generalmente, la rama principal se llama `master`, y si te fijas, cada repositorio del curso realiza sus commits en esa rama.
<img width="468" alt="image" src="https://user-images.githubusercontent.com/13752751/91728007-81840980-eb70-11ea-96f7-4bf0b8eb54f3.png">


Imagínate las ramas como las de un árbol, donde cada nodo representa un `commit` (como te muestra la imagen).

<img width="570" alt="image" src="https://user-images.githubusercontent.com/13752751/91727266-6ebd0500-eb6f-11ea-8668-877427d7788a.png">
(link de referencia: https://www.atlassian.com/git/tutorials/using-branches)

Sobre GitHub, es muy popular debido a la buena conexión que tiene tanto con git como con otros sistemas. GitHub es una de las plataformas que mejor conversa con git: puedes ver tus commits, la distintas ramas, revisar cambios, almacenar repositorios. Es como el google drive para los computines 😉

Espero haberte ayudado ✨ cualquier cosa me comentas.

**Comment by daniela-carreno** [comment]
Gracias profe 🥰

Otra duda más 🙈.. sobre mi última pregunta, la enumeré como 5.3 en el comentario anterior . Profis

**Comment by cothidalgo** [comment]
De nada 😊

Git te permite volver a commits anteriores (recuerda que los commits son las declaraciones de cambios en tu código). Esto también esta fuera de los contenidos del curso pero si lo manejas podrías utilizarlo a tu favor. 

Depende mucho de si tus commits están _pusheados_ o no. Si tienes en tu repositorio GitHub un historial de commits, y editas el historial desde tu local, vas a tener conflictos (diferencias) entre lo que tienes en la nube y lo que tienes en tu computador. Si los commits no están _pusheados_, es más fácil volver commits antiguos porque GitHub no sabe aún de esos commits nuevos.

1. Borrar commits en local
Puedes ver el hash del commit al que quieres regresar y escribir en el terminal `git reset --hard <commit_hash>` (el hash es un conjunto de letras y números que sirve como identificador del commit, y puedes revisarlos tanto en GitHub o con el comando `git log` )

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/13752751/91745534-1abf1a00-eb89-11ea-9edb-6c5dab1dc947.png">

Ojo que esto borrara tanto los commits siguientes como tus cambios locales que no les hayas hecho `git commit`. Hay que usarlo con conciencia y cuidado. Si quieres mantener tus cambios no _commiteados_, debes escribir `--soft` en vez de `--hard`.

2. Borrar commits que estén en GitHub

Puedes revertir _commits_ especifícos con el comando `git revert <commit_hash>`. Esto creará un nuevo _commit_ que revierte los cambios. De todas formas, te recomiendo que uses un poco más de git y GitHub antes de hacer esto, pues estarás modificando el historial de cambios y eso es más seguro cuando tenemos mejor conocimiento de la herramienta git.

Si quieres aprender más, hay mucha información online, incluso puedes revisar la documentación de git mismo. Si tienes dudas no dudes en mandarlas. ❤️
