### ISSUE TITLE
Arrastrar torre

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2233/syllabus#295]
Hola, llegué a la parte de la tarea donde dice, 
![image](https://user-images.githubusercontent.com/48324565/57974801-4cac6d00-7994-11e9-9ec4-c10d838bdb1e.png)
Ahora bien, no pasaron cómo arrastrar una torre junto con los contenidos. Existe una forma más o menos fácil de arrastrar una imagen?
Busqué un poco y hay cosas muy complejas, que requieren por ejemplo ```QMimeData``` y no entiendo qué es eso...
Por otro lado, la torre necesita verse mientras se arrastra, o puede simplemente puede arrastrarse "invisiblemente" y cuando se suelte el mouse se queda donde está el mouse?

**Comment by Hernan4444** [comment]
Hola, si se debe ver la torre cuando se arrastra. En el material extra se habla de los métodos `mouseMoveEvent`y `mousePressEvent` (y analógicamente, si está `keyPressEvent` y `ketRelaseEvent`, también debe existir `mouseReleaseEvent`) con esos métoods más el uso de QLabel, QPixmap y algún método para mover un label, se debe poder implementar el drag & drop y no recorrir a cosas complejas 👍 

Saludos ✌️

**Comment by jaromero6** [comment]
Complementando la respuesta de @Hernan4444 , te sugiero fuertemente jugar con `mouseMoveEvent`  y `mousePressEvent` para mover a un label. Otra recomendación es sacarle provecho a la herencia y tener una clase personalizada que herede de QLabel (te **recomiendo** ver que es lo que pasa si defines esos métodos en esa clase y no en la ventana)

**Comment by perezpefaur** [comment]
Haciendo esa clase personalizada, que hereda QLabel, puedo hacer overriding de metodos de QLabel (como setPixMap)? O sirve para conectar se forma directa al evento del mouse sostenido? La verdad no es que no logro captar bien la utilidad de redefinir la clase o que cosa cambiar en la clase personalizada de Qlabel. Gracias de antemano!
