### ISSUE TITLE
twistplot rios, caminos

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#295]
Dice el enunciado:"El jugador que ponga la última pieza para unir tanto un camino como un río, se convierte en su dueño" 

Mi duda es: En este caso, la pieza no tendría que cambiar de color porque en una pieza pueden haber dos ríos o caminos, por lo tanto **solo** se tendría que guardar esta información internamente o me equivoco?

**Comment by cilopez** [comment]
Te equivocas, la pieza si cambia de color en este caso,y ojo que la regla plot twitst puede tener reacciones en cadena. ¡Saludos!
