### ISSUE TITLE
Extensión archivos de entrada

### ISSUE THREAD

**Issue by cho19** [IIC2233/Syllabus#295]
Hola!

En los comandos para por ejemplo leer una columna (extraer_columna), se especifica el nombre del archivo pero sin extensión ("registros" en uno de los comandos de ejemplo).

Entiendo que podemos asumir que el formato del archivo por dentro siempre estará correcto pero, ¿podemos asumir lo mismo con la extensión? Es decir, ¿podemos asumir que nunca van a escribir "registros.csv" en el comando o qué no pediran que leamos archivos de cualquier otra extensión (.txt por ejemplo)?

Saludos y gracias

**Comment by Hernan4444** [comment]
@cho19 puedes asumir que siempre nos referiremos a archivos.csv ingresando solo su nombre

Saludos!!

**Comment by cho19** [comment]
@Hernan4444 Gracias !
