### ISSUE TITLE
Goles igual a 0

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#295]
Hola! Es idea mía o el cálculo de goles es siempre igual a 0?
Dado que la Esperanza está compuesta por el promedio simple de las afinidades promedio (valga la redundancia) de todos los jugadores, quiere decir que este valor siempre será <= 1, no?
La Calidad del equipo, al estar normalizada por el valor máximo que puede tomar la suma de los overall de los jugadores, también es un valor <= 1.
Luego, la esperanza, siendo el producto de estos dos cálculos, tomará valor <= 1.
Finalmente, el cálculo de goles de un equipo (asumiendo que no hizo faltas) corresponde el truncamiento de ((Esperanza Inicial/40)^2)... Claramente, ((Esperanza Inicial/40)^2) también es un valor < 1, por lo que truncarlo daría 0, haciendo que el número de goles hechos por un equipo siempre tome valor 0.
Corríjanme si estoy mal o ignoré algo, por favor. Me parece que extraño que todos los partidos tengan 0 goles.

**Comment by yoavnavon** [comment]
Hola! Si, al parecer hay un error en la formula, la calidad de equipo no debería estar normalizada, sino que debería ser la calidad promedio, es decir, la suma de calidades dividida en 11. Esto te generará partidos con goles. De todas maneras no es lo más importante una simulación verídica, si no que funcione el campeonato y lo demás. Saludos!

**Comment by llloyola** [comment]
Muchas gracias! :)
