### ISSUE TITLE
Encallar o no

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#296]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!
Según lo dicho en el enunciado el encallar o no es una probabilidad. Pero en el caso de simular y determinar si un barco encalló o no, ¿el programa va a elegir si ocurre o no?, tanto para hacer los cobros y que se ejecuten las consecuencias de un encallamiento. ¿Esto se haría con algún método de random? por dar un ejemplo.

Gracias!

**Comment by manearaya** [comment]
Hola @Rerro-r!

Si se dice que hay un evento que ocurre con cierta probabilidad, entonces el programa elige si esto ocurre o no en base a la probabilidad del evento, y para elegir puedes usar la librería random (te podría servir el issue #294).

Saludos!
