### ISSUE TITLE
Problema para aparecer un label

### ISSUE THREAD

**Issue by JoseUfre** [IIC2233/Syllabus#296]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola como están? Estoy poniendo un problema para que se muestre una imagen en pantalla que antes se estaba mostrando y quería saber si alguien podía ver el código en mi repositorio y ayudarme, porque no logro conseguir que sucede para que se haya dejado de imprimir :(((
El código a ver sería el método poner_zombie en el archivo ventana_juego.py.
De antemano, muchas gracias :)

**Comment by Hernan4444** [comment]
Hola @JoseUfre 

Revisé el código, está bien hecha esa parte, el problema es la ruta que le das. Si revisas cómo defines la ruta de `RUTA_WALKER_1` y donde efectivamente está, notarás que tu `os.path.join` no apunta a la ubicación exacta de la imagen.

Cuentanos cómo te va con eso, estaremos atentos al foro :D

Saludosヾ(＾-＾)ノ
