### ISSUE TITLE
Último commit a revisar

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#296]
Hola!!! Para mi tarea hice 4 módulos y uno de ellos contenía a main.py. Ayer hice commit del main.py y hoy me di cuenta que tenía un error en otro módulo diferente al main, lo arreglé y luego hice commit. Me aparece que el commit que me van a revisar es el de este módulo que cambié al final, pero no es el principal. Mi duda es ¿Debería llenar el formulario para que me corrijan el módulo main (a pesar de que perdería el trabajo que hice en el módulo que arreglé al final) o dejo que el commit a revisar sea el último que hice pero que no es del main? Ayuda :(

**Comment by furcelay** [comment]
Hola @denisseleiva !
Por favor no te preocupes, cuando haces un commit de un archivo estás actualizando ése archivo en el repositorio remoto, pero los archivos que se actualizaron en commits anteriores seguirán ahí, por lo que probablemente el módulo main esté en tu repositorio en su última versión. 

No hay problema con que el último commit sea de un archivo distinto de main, lo único que debes hacer es asegurarte de que en tu README esté indicado que el archivo a ejecutar es `main.py`.

Por último, si quieres asegurarte de que la versión que revisaremos es la correcta, les llegará un correo (si aún no les ha llegado) indicando el commit a revisar para la  tarea y tendrá un link con el que podrán ver su repositorio en la versión a revisar, siguiendo el link ve tu tarea 00 y chequea que esté todo Ok.

**Comment by denisseleiva** [comment]
Muchas graciaaass por la aclaración!! Ya me había asustado 😅😅
