### ISSUE TITLE
Consulta formato parametro "Congelación"

### ISSUE THREAD

**Issue by ByDati** [IIC2233/Syllabus#296]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tenía la duda respecto a la forma que se entrega el parametro de congelación en el archivo "plantas.txt", ya que en el ejemplo aparece como "0", mientras que la instrucción indica un booleano; debemos asumir los valores de "0" como "False" y los "1" como "True"? Gracias de antemano.

**Comment by augustayanez** [comment]
Te sugiero ver la issue #243 donde se explica como interpretar los valores de congelación de plantas.txt

**Comment by ByDati** [comment]
yaaa, gracias
