### ISSUE TITLE
Input Usuario

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#296]
Hola! No me queda claro de que forma o donde recibe el input del usuario el codigo. Una vez escrito el comando, adonde llega este valor en terminos de variables? Como "recibimos" dicho input?

**Comment by Hernan4444** [comment]
@benjamimo1 cuando uno escribe una consulta, si está bien formada se agregará a la tabla de consultas, luego haciendo click en ella y apretando en Realizar consulta(s) seleccionada(s), se llamará al método `process_consult` con la lista.

Saludos!

**Comment by JIGutierrez** [comment]
@Hernan4444 En relación al input, el usuario ingresa el nombre de una de las funciones, como
`comparar_(5, "<", 3)`
o debe ingresar
`[COMPARAR, [5, "<", 3]]`

Lo que entiendo es que se aplica lo segundo para las funciones que retornan números, pero no me queda claro para las otras.

**Comment by iqacevedo** [comment]
Hola!
@JIGutierrez debe ser `["comparar",  5,  "<",  3]`. Si pruebas la primera consulta en la interfaz, podrás ver que no te deja ingresarla. La segunda tiene unos "[ ]" de más. También puedes ver las consultas de ejemplo que vienen en consultas.json.

Saludos !
