### ISSUE TITLE
Imports cruzados

### ISSUE THREAD

**Issue by lothardp** [IIC2233/syllabus#296]
Es muy grave si tengo imports cruzados en mis archivos?? 
Me refiero a que por ejemplo en un archivo ```menus.py``` tengo ```import clases``` y en ```clases.py``` tengo ```import menus```.
Pregunto porque en los contenidos dice que no se puede, pero me corre el programa sin ningun error. Hay descuentos por esto por mala practica o es aceptable??
Gracias!

**Comment by jmwielandt** [comment]
Hola! 😄 

Tras hacer un par de pruebas y una búsqueda por el changelog de python 3.7, descubrimos que es una característica incorporada en esa versión, si te interesa, puedes ver [aquí](https://bugs.python.org/issue30024) la discusión al respecto y el desarrollo.

Lo hablamos en el grupo de ayudantes y es algo que puede ayudar a modularizar tu código y puedes usarlo, sin embargo si se usa mal puede crear muy fácilmente una modelación circular, con lo que debes tener cuidado ya que es una mala práctica y será penalizado a partir de la tarea 2.

Saludos y ánimo con lo que queda~ 👍
