### ISSUE TITLE
[entrega final] Duda enunciado: mensaje error por usuario inválido

### ISSUE THREAD

**Issue by mtldee** [IIC2233/Syllabus#296]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda en la parte del enunciado que dice que, en el caso de que sea un usuario inválido, se muestre un mensaje de error o pop up en la interfaz "mencionando el motivo del error". Con esto último se refiere a si es parte de los usuarios bloqueados o es inválido el nombre en general, o se espera que en este último caso se especifique el error puntual (no tiene una mayúscula, no tiene un número, etc)

**Comment by gasparbenavente2** [comment]
Hola. El motivo de error se espera que sea A) Usuario bloqueado o B) Nombre invalido. En el caso que sea inválido el nombre puedes poner específicamente cual fue el error (ej. no tiene mayúscula) para ayudar al usuario a elegir un buen nombre.
