### ISSUE TITLE
Comparacion Jugadores ayudantes

### ISSUE THREAD

**Issue by auirarrazaval** [IIC2233/Syllabus#296]
Hola!
Cuando comparo un jugador ayudante con el mismo o el valor de algun atributo de ellos, me dice que no son iguales. SOLO pasa con los jugadores que son ayudantes, con el resto no tengo problema

**Comment by IchottMano** [comment]
@auirarrazaval Hola!
Puedes explicar algo mas?
Mostrar un pantallazo o describir en mayor detalle el problema, a modo de poder entender mejor que es lo que esta pasando.

Saludos!
