### ISSUE TITLE
Error al importar PyQt5

### ISSUE THREAD

**Issue by fplois** [IIC2233/syllabus#296]
Al intentar ejecutar un código que utiliza PyQt5 me aparece este error en pycharm:
`ModuleNotFoundError: No module named 'PyQt5'`

y al intentar ejecutarlo en el IDLE me aparece este otro error:
```python
from PyQt5.QtWidgets import QWidget, QApplication
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/QtWidgets.so, 2): Symbol not found: __os_activity_create
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore
```

instale PyQt5 utilizando este código:
`pip3 install pyqt5`

al ejecutar el código nuevamente me aparece esto:
"Requirement already satisfied: PyQt5_sip<13,>=4.19.14 in ./anaconda3/lib/python3.7/site-packages (from pyqt5) (4.19.17)"

en todo caso descargue python 3.6.2 aparte y trabajo con ese en IDLE y en el interprete de pycharm.
¿Qu puedo hacer?

**Comment by KnowYourselves** [comment]
Hola @fplois!

Por lo que veo estás ocupando `anaconda`, el cual es conocido por dejar un poco la crema en cuanto viene a módulos y librerías. No me iré en detalles, pero la forma más segura que tienes de que `PyQt5` te funcione es la siguiente:

1. Desinstalar Anaconda.
2. Desinstalar Python.
3. Instalar Python desde la [página oficial](https://www.python.org/downloads/release/python-368/).
4. Instalar PyQt5.

Siguiendo estos pasos debería funcionar correctamente y sin ningún problema. En caso de que esto no funcione quedo atento a cualquier otra duda!

**Comment by fplois** [comment]
voy a ver si me funciona, pero después de seguir esos pasos que me diste ¿puedo instalar anaconda nuevamente ya que en el uso jupyter?.
Gracias

**Comment by KnowYourselves** [comment]
Podrías instalar Anaconda de nuevo, pero de verdad que no te lo recomiendo. Puedes instalar jupyter sin Anaconda con el siguiente comando:
```bash
pip3 install jupyter
```
Espero haberte ayudado!

**Comment by fplois** [comment]
Hola, sigo con los mismos errores después de haber seguido los pasos que me indicaste.

**Comment by KnowYourselves** [comment]
Estás seguro que estas usando el intérprete de Python adecuado en Pycharm? (puede que estes ejecutando el programa con otra versión)

**Comment by fplois** [comment]
como interprete tengo python 3.6 y me aparece este error ahora:
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-045166220bbb>", line 1, in <module>
    runfile('/Users/felipelois/Library/Preferences/PyCharmCE2018.3/scratches/scratch.py', wdir='/Users/felipelois/Library/Preferences/PyCharmCE2018.3/scratches')
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/felipelois/Library/Preferences/PyCharmCE2018.3/scratches/scratch.py", line 3, in <module>
    from PyQt5.QtWidgets import QWidget, QApplication
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/QtWidgets.so, 2): Symbol not found: __os_activity_create
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore
`
y al correrlo en el IDLE me aparece este:
`Traceback (most recent call last):
  File "/Users/felipelois/Desktop/pedro.py", line 2, in <module>
    from PyQt5.QtWidgets import QWidget, QApplication
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/QtWidgets.so, 2): Symbol not found: __os_activity_create
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore`

**Comment by Hernan4444** [comment]
Hola, 
Revisando esta issue: https://stackoverflow.com/questions/43531245/pyqt5-not-working-on-macos-sierra, parece que una forma es utilizar homebrew para cambiar una flag y que funcione realizar import.

Cuentanos como te va con eso.

**Comment by fplois** [comment]
Ya probe utilizando el código de esa issue y no se soluciona el problema. :(

**Comment by fplois** [comment]
Ya probe el código de la issue y sigo con el mismo error :(

**Comment by hbkim94** [comment]
Hola @fplois 

Asumiendo que ya tienes tanto Python 3.6 como PyQt5 instalados, ¿has intentado lo que dicen en esta [issue](https://stackoverflow.com/questions/40824497/mac-os-pyqt5-image-not-found)?

![image](https://user-images.githubusercontent.com/37163577/57977231-1685e200-79c2-11e9-93f2-cc14cb33bb20.png)

**Comment by Arcoirisky** [comment]
Cuando borraste anaconda, eliminaste todas las carpetas referentes a él ¿no? Y reiniciaste el pc 🤔 ¿si? (A veces lo cambios no se ejecutan sin reiniciar) 

Otra pregunta, el intérprete es Python 3.6 y no un environment ¿o no? O:

**Comment by Arcoirisky** [comment]
En cualquier caso, intenta instalar Pyqt5 según tu Python de este link: https://www.lfd.uci.edu/~gohlke/pythonlibs/

Se ven terribles feos pero a mi me sirvieron de harto cuando mi not metía problemas y según stackOverflow deberías poder instalarlo sin importar tu sistema operativo (https://stackoverflow.com/questions/48760797/how-can-i-pip-install-whl-file-according-to-current-operating-system)

**Comment by fplois** [comment]
@hbkim94 ya utilice el código que me mandaste con la ruta correcta y no me funciona.
@Arcoirisky después de eliminar anaconda, si reincie el mac y el interprete es Python 3.6, no un environment.

**Comment by jmwielandt** [comment]
Hola!
De casualidad, ¿qué versión de mac os tienes? 🤔

**Comment by fplois** [comment]
@jmwielandt  tengo os 10.11.6

**Comment by tamarabend** [comment]
Hola! Tuve el mismo error porque tenía la misma version de mac. Lo que me funcionó al final fue desinstalar pyqt5 y luego instalar la version 5.10.1 de pyqt con el siguiente código en la terminal:

```python
pip3 install PyQt5==5.10.1
```
Ojalá te funcione! @fplois

**Comment by fplois** [comment]
@tamarabend , en verdad muchas gracias!, lo que me dijiste funciono perfecto!.
