### ISSUE TITLE
Problema Ayudantía 6

### ISSUE THREAD

**Issue by savelozo** [IIC2233/Syllabus#297]
Estaba intentando repasar los contenidos para la actividad de mañana y no pude cargar el archivo de la ayudantía 6, de hecho, me arrojaba error. Consulté con otro amigo para saber si también tenía el mismo problema y, según él, tampoco le carga. Habrá alguna forma de solucionarlo? :)

Saludos!

**Comment by andresfdezc** [comment]
Subiré un pdf de la ayudantía por si acaso.

**Comment by andresfdezc** [comment]
Recuerden que pueden ver las ayudantías localmente en su computador con Jupyter Notebook.

**Comment by andresfdezc** [comment]
El problema fue solucionado. Si por algún motivo todavía no puedes verla en el navegador, dejé subida una versión en pdf.
