### ISSUE TITLE
Interfaz gráfica y demo.py

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#297]
Hola, ya escribí una issue sobre esto (#260), pero todavía no lo he podido solucionar y no puedo avanzar sin solucionarlo porfa si alguien tuvo el mismo problema y me puede orientar se lo agradeceria! 
PD: ya intenté lo que aparece en otras issues

**Comment by Arcoirisky** [comment]
https://github.com/IIC2233/Syllabus-2017-2/issues/598

Con eso ¿Qué error sale? :(

**Comment by santilaguna** [comment]
No sale ningún error si es que le quito el mi_juego.show(), pero si se lo dejo me aparece esto:

QImage::scaled: Image is a null image
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
Traceback (most recent call last):
  File "/Users/jaimealtamirano/SantiRepo/Tareas/T02/Demo.py", line 99, in <module>
    mi_juego.show()
AttributeError: 'Juego' object has no attribute 'show'

Que según entiendo es lo mismo, pero se cae antes pq no esta definido el .show()

**Comment by santilaguna** [comment]
Tal vez esta información puede ayudar,
Cuando ejecuto el demo.py desde adentro de la GUI  (cambiando los import) si me corre!!
