### ISSUE TITLE
Encoding 

### ISSUE THREAD

**Issue by VittoTassara** [IIC2233/Syllabus#297]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Holaa :) , tengo un problema a la hora de recibir los inputs iniciales por código con caracteres como la "ñ".
Si le entrego el código por terminal de git bash (ejemplo: python main.py jardin_pequeño facil ) la "ñ" se me identifica como carácter desconocido y por ende no me identifica el jardín en el archivo "jardines.txt" en cambio si entrego el código por terminal de CMD me considera la "ñ" como carácter desconocido pero del archivo de "jardines.text" :(((  
Estoy programando en Vscode y tengo encoding de UTF-8

**Comment by CatalinaBO** [comment]
Hola! Específicaste el encoding al momento de abrir los archivos?
En caso de que si lo hayas hecho, puedes responder con un pantallazo del print que obtienes al hacer print de los comandos  que utilizaste para ejecutar el archivo, o del error que se genera?
Quedo atenta!

**Comment by VittoTassara** [comment]
Holaa! Si era eso, lo había escrito mal jejejeje GRACIAS :)
