### ISSUE TITLE
Interprete

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#297]
¿La función del interprete es simplemente tomar cada valor de la lista, saber a que función se refiere y ejecutar la función usando dichos valores? ¿O es algo más complicado o distinto a eso?

Gracias!

**Comment by iqacevedo** [comment]
Hola!
Justamente, la idea es que se te haga más fácil y ordenado saber a que función llamar dada una consulta especifica.  De esa manera, si se ingresa una consulta del tipo asignar, tu interprete llamara a la función que tu hayas creado para esta consulta. 

Espero que quede claro !
Saludos !
