### ISSUE TITLE
Testeo con parametros.py 

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#297]
Hola, se me está haciendo difícil el testeo porque la proporcionalidad de algunos parametros me da valores raros. Es posible que suban un archivo parametros.py para no perder tiempo? uwu

**Comment by gatochico** [comment]
Hola! 
Lamentablemente no subiremos el `parametros.py` con datos ya llenados. La razón de esto se aborda en la issue #261 . En resumen, es porque es algo que buscamos evaluar en la tarea :(

Saludos y ánimo!

**Comment by FelipeA7** [comment]
Ustedes van a probar la tarea con nuestro parámetros.py o van a utilizar uno donde ustedes hayan llenado los datos? @gatochico

**Comment by gatochico** [comment]
Con los que suban ustedes! A lo más, cambiaremos un poco algunos valores para ver como funcionan pero la idea de que suban el suyo es que el programa corra tal como ustedes lo probaron.
