### ISSUE TITLE
Creo que commit a revisar erronea de la tarea

### ISSUE THREAD

**Issue by yuwet15** [IIC2233/syllabus#297]
Hola, estaba viendo en la issue supuestamente de la T00, pero al hacer click en commit a revisar, me doy cuenta, que está dirigido a la actividad formativa, y no a la T00, eso es normal?

**Comment by furcelay** [comment]
Hola @yuwet15!
El último commit a revisar es seleccionado automáticamente como el último que hayas hecho antes del cierre de la tarea. Por lo que veo el último que hiciste antes de esa hora fue efectivamente el de la AF01. No te preocupes porque no hay ningún problema con eso mientras al momento de hacer ese commit la tarea haya estado en su versión final. No revisaremos sólo los archivos que hayas actualizado en el commit sino que **veremos todos los archivos en `T00` al momendo de hacer dicho commit.**

Por último, si quieres asegurarte de que la versión que revisaremos es la correcta, les llegará un correo (si aún no les ha llegado) indicando el commit a revisar para la tarea y tendrá un link con el que podrás ver tu repositorio en la versión a revisar, siguiendo el link ve a `T00` y chequea que esté todo Ok.

Saludos!! 😄

**Comment by yuwet15** [comment]
entiendo, muchas gracias por aclararme esa duda
