### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by stgopau** [IIC2233/syllabus#298]
Hola, no entiendo muy bien el formato Markdow, ni de que forma quieren que utilice este formato para el diagrama de clases

**Comment by gatochico** [comment]
Hola! 

No queremos que hagas tu **diagrama en markdown**, sino que pedimos (de forma opcional, pero que al final solo te beneficiaría si lo haces :eyes:) una explicación de tu diagrama de forma escrita. La idea es que pongas cosas como: "La clase X hereda de la clase Y ya que _inserte justificación aquí_" o "La relación entre estas dos clases es de composición/agregación/herencia ya que _inserte justificación._"

Esta explicación escrita es la que debería ir en markdown, el cual es el mismo formato que posee el README, así que podrías tomar inspiración de este para el estilo (como poner cursiva, o negrita, o punteos, o lo que sea).

Éxito con la tarea!
