### ISSUE TITLE
.gitignore Entrega intermedia Tarea 2

### ISSUE THREAD

**Issue by anticarasosman** [IIC2233/Syllabus#298]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola disculpa, en el enunciado de la tarea dice que el gitignore debe ignorar el enunciado y las carpetas "assets/" y "tests/" pero no logro encontrar la carpeta "tests/" ¿se refiere a la carpeta "test_publicos/" que se encuentra en "entrega_intermedia/"?.

Adjunto imagenes de las carpetas en mi repositorio personal:
![imagen_2023-10-23_095749718](https://github.com/IIC2233/Syllabus/assets/94928628/b05c8d2c-14fc-48a2-a05a-6f13d5948e1b)
![imagen_2023-10-23_095808112](https://github.com/IIC2233/Syllabus/assets/94928628/9e89d5cb-d689-427d-ad79-83126ad47517)
![image](https://github.com/IIC2233/Syllabus/assets/94928628/84f59ba0-2a15-4b9b-b8c6-5e8ffb2fe704)

**Comment by AntonioVenegas** [comment]
Hola @anticarasosman!, si, cuando se refiere a la carpeta test, se refiere a la de test publicos. 
Saludos! :)
