### ISSUE TITLE
Donde pongo que le hice una correccion a mi codigo despues de la entrega?

### ISSUE THREAD

**Issue by tvallotton** [IIC2233/syllabus#298]
Hola, le tuve que hacer una corrección muy menor a mi código, como 10 caracteres en total. Esto lo aviso en el readme, o hago una issue en mi repositorio? Tengo que rellenar el formulario de entrega atrasada?

**Comment by josefinareyes** [comment]
Hola! Puedes especificar en tu ```README```el cambio de líneas correspondiente para que quien lo corrija lo tenga presente,  con esto no es necesario que llenes el formulario de entrega atrasada!
