### ISSUE TITLE
Título descriptivo (reemplazar con el título apropiado)

### ISSUE THREAD

**Issue by pgaguilera** [IIC2233/Syllabus#298]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

La cantidad de soles que no salen del girasol, sino que aparecen aleatoriamente en el jardin de la abuela ¿es la misma cantidad que está en el archivo parametros?

**Comment by drcid98** [comment]
Hola, INTERVALO_APARICION_SOLES es el parámetro al que te refieres, el cual debes incluir en el archivo parametros.py
