### ISSUE TITLE
Plot Twist rios, caminos

### ISSUE THREAD

**Issue by bawas** [IIC2233/Syllabus#298]
No me queda claro como debe realizarse el cambio en el color de las piezas al momento de colocar una pieza que continúe un rio o camino. por ejemplo, si en el tablero hay una pieza que solo sea un rio, y coloco continua a ella una pieza de otro color que tambien contenga un rio, de manera que continue el rio, ¿me adueño de la primera pieza? ¿o esto solo ocurre cuando existan ciudades involucradas en el inicio de los rios/caminos?

Saludos.

**Comment by cilopez** [comment]
Te recomiendo revisar más el foro, existen varias issues sobre esto
