### ISSUE TITLE
Ejecucion método Potencilantro

### ISSUE THREAD

**Issue by canija2000** [IIC2233/Syllabus#298]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Dado que no se explicita en el enunciado  debo asumir que  los **Potencilantros** ejecutaran su potenciación en cada día ? (lo mismo para sus hijos ? 
Gracias

**Comment by diegoftpxd** [comment]
Hola! Los potencilantros tienen que aumentar la producción de el resto de plantas todos los días. Esto quiere decir de que si hay Solaterillos cerca todos los días su producción debería ser mayor al caso con ausencia de potencilantros.

Por otro lado, si te refieres a que un solaterillo aumenta cada vez más su producción todo los días por tener un potencilantro cerca. El enunciado dice que la producción debe ser aumentada en AUMENTO_NUTRIENTES% por lo que debería aumentar siempre la misma cantidad la producción de soles, no debería  un solaterillo aumentar constantemente su producción. No sé si es claro.

**Comment by canija2000** [comment]
Vale! Si queda claro, gracias
