### ISSUE TITLE
Posibilidad de modificar Interfaz.py

### ISSUE THREAD

**Issue by akrebs2** [IIC2233/Syllabus#298]
Hola.

En mi código, cuando debo pasarle los jugadores a Demo.py, se cae porque se los paso en una lista ligada (ya que no está permitido ocupar listas). Cabe mencionar que mi tarea completa se ha estructurado de la siguiente manera:
Mis listas ligadas acceden a Nodos, los cuales tienen un atributo "valor", que puede ser un objeto de clase Jugador, tanto como un número, o cualquier otro tipo de objeto dependiendo el caso. Al ocupar esa lógica, en el módulo Interfaz.py, cuando yo le paso los jugadores, surge un problema en la siguiente sección:
`        for i in jugadores:
                 self.lista_jugadores.append(Jugador(self, *i, scaled=0.8))`
El cual me lanza el siguiente error:
> type object argument after * must be an iterable, not Nodo

En el fondo, no instancia bien la clase Jugador, ya que i toma el valor de un objeto de clase Nodo, y no el valor que contiene ese mismo nodo. Ante esto, es posible modificar solo esa sección del código, para que se instancien bien los jugadores? Mencionar también que mi código sí implementa el método __iter__. Tengo claro que el enunciado dice que sólo deberíamos modificar Demo, pero el código de Interfaz solo permite un tipo de configuración del problema (en donde, me imagino, la clase Jugador es un nodo en sí misma por tener el atributo "siguiente" o "next"). Si no, qué puedo hacer al respecto? Si no puedo hacer esto tendré que re-estrcturar mi tarea completa para que se adecue a esa linea, lo cual me llevará muchísimo tiempo.

**Comment by IchottMano** [comment]
@akrebs2 Hola!

Lamentablemente no puedes hacer eso, ya que los ayudantes corregirán tu tarea usando el Interfaz.py entregado, por lo que si tu fueras a cambiar código, esto no funcionará mas que en tu computador.
Además, está prohibido subir tu propio Interfaz.py, por lo que el subir uno modificado solo le restará a tu puntaje.

Saludos!

**Comment by IchottMano** [comment]
@akrebs2 PD:
Lo mejor que puedes hacer es implementar el método necesario para que esa línea de código funcione,
No debería ser muy complejo
Saludos!
