### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by raimundoloeser** [IIC2233/syllabus#299]
Al tener una clase abstracta, en el diagrama de las clases que heredan e esta, se incluyen los metodos que hereda desde la clase abstracta?

**Comment by jmwielandt** [comment]
Hola! 😄 

Como se comenta en la issue #286 y el material, no se puede instanciar una clase que hereda de una clase abstracta sin hacer override de los _abstract methods_ de esa clase, por lo que ambas clases implementan dicho método y ambas deben tenerlo en el diagrama.

Saludos y ánimo con lo que queda~ 👍
