### ISSUE TITLE
Cerrar sesion

### ISSUE THREAD

**Issue by masoto22** [IIC2233/syllabus#299]
He tratado de entender bien el enunciado pero aún no me queda claro lo de "cerrar sesión", esto tiene que estar en la misma ventana de inicio donde se inicia sesión? no me hace sentido 😢 yo lo pensé como algo que tenía que estar en el mapa pero según enunciado no es así, entonces no cacho y me voy a echar progra 😿

**Comment by Arcoirisky** [comment]
Antes de cualquier cosa ¡ánimo! y gatitos pata ti~ :cat: :cat2: :two_hearts: 

Ahora, sobre cerrar sesión. Siento que tu complicación va en entender la diferencia entre todos los botones y sus ubicaciones, te aconsejaría leer el enunciado más calma3, concentrandote más en la parte de la interfaz (aquí te va un resumen que puede responder tu pregunta)

Primero tenemos la **ventana de juego** (10.3) donde debe mostrar todo lo necesario para _preparar las rondas y jugar_. La **ventana que prepara las rondas** (10.3.1) posee dos botones:

- Empezar ronda
- Cerrar Sesión

El ultimo de estos termina el juego, cerrando nuestra **ventana de juego** y la sesión del ente que decidió abrirla desde la **ventana de inicio**. Notar que durante una ronda en progreso estos botones son reemplazados por uno de pausa :D  

Insisto en que te des un respiro si estás ansioso y lee el enunciado con un cuaderno o algo para poder escribir y reducir el tamaño del texto a re-leer. Así no te agobias por la cantidad de paguinas y puedes concentrarte en la información importante :D
