### ISSUE TITLE
problema con PATH al instalar CurrencyConverter

### ISSUE THREAD

**Issue by tamyhan** [IIC2233/syllabus#299]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, tengo un problema con el currency converter. Instalé la librería como decía en el link, con `pip install --user currencyconverter`, y me salió esto: 

**WARNING: The script currency_converter is installed in '/Users/tamarahan/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.**

Después, cuando traté de usarla poniendo `currency_converter 100 USD --to EUR` en el terminal, me salió: **command not found: currency_converter** 

Cómo lo puedo arreglar?

**Comment by Emiliax16** [comment]
Hola @tamyhan ! para arreglar ese WARNING, te recomiendo que sigas los pasos de [este_link](https://stackoverflow.com/questions/58051467/fixing-path-for-python-libraries-using-bash) que arregla el error de path de python. Debes hacerlo desde tu editor de texto y fijarte en poner bien tu usuario y tu versión de python. Ve con eso si te funciona y me cuentas. Quedo atenta!

**Comment by tamyhan** [comment]
Hola! Acabo de hacer lo que decía el link pero todavía no me funciona :(

**Comment by Emiliax16** [comment]
Prueba con `pip3 install --user currencyconverter` para la instalación. Si te sale un WARNING, igualmente debería funcionarte, ya que son sólo advertencias y no errores críticos. Cuéntame si te resulta.

**Comment by tamyhan** [comment]
Me sale esto:  
Requirement already satisfied: currencyconverter in ./.local/lib/python3.8/site-packages (0.16)

**Comment by tamyhan** [comment]
Ahí me funcionó!! No se bien que hice jajaja pero ahora me funciona!!

**Comment by Emiliax16** [comment]
Que bueno !! Suerte en el resto de la tarea c:

**Comment by Emiliax16** [comment]
Hola @fliperriga ! podrías adjuntar el error que te aparece?
