### ISSUE TITLE
Uso de clases. 

### ISSUE THREAD

**Issue by SaritaGP** [IIC2233/Syllabus#299]
Hola he leído issue #211 y #217 pero sigo sin tener claro si puedo usar clases, en mi código tengo la clase Jugador y un diccionario creado por mi que funciona así {nombre_jugador: Jugador(nombre_jugador)} y utilizo eso para calcular mi afinidad y crear el grafo, es válido? o lo que se espera es que use mi estructura tipo {nombre_jugador: {atributo1: valor, ...}}, puedo hacer eso, pero se pierde eficiencia (en término de tiempo) al crear mi grafo. ¿Qué tengo que hacer? :c

**Comment by IchottMano** [comment]
@SaritaGP Hola!

En primer lugar si está permitido usar clases, no te preocupes, en esas issues me refería a la representación de jugadores dentro de una Estructura de Datos.
Viendo tu repositorio (si, tenemos ese poder 👀 ) me di cuenta que hiciste un diccionario legal, si usar métodos prohibidos, por lo que no hay ningún problema con que uses esa estructura en tu tarea.
Lo que debes tener consideración, sin embargo, es de tener cuidado de no usar (por accidente o adrede) estructuras de datos de python.

Saludos!

**Comment by SaritaGP** [comment]
Genial, gracias!
