### ISSUE TITLE
Librerias

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#299]
¿Como desinstalo una libreria? o tambien ¿Como actualizo una libreria?
Ya que tengo numpy 1.11 y matplotlib 1.5.

**Comment by Hernan4444** [comment]
@jorgeriesco usando `pip install matplotlib` debería instalarse la ultima versión (junto con numpy).
intenta con eso y nos cuentas

Saludos!

**Comment by jorgeriesco** [comment]
no se actualiza :|

**Comment by stephichau** [comment]
@jorgeriesco intenta con ```pip install --upgrade [inserte nombre libreria]```

**Comment by jorgeriesco** [comment]
@stephichau Funciona! pero tengoun problema.
Tengo dos interpretes y se instala en el interprete que no quiero :(

**Comment by iqacevedo** [comment]
@jorgeriesco prueba con `py -[inserte versión de python] -m pip install --upgrade [inserte nombre libreria]`.
Eje: `py -3.5 -m pip install --upgrade matplotlib`

**Comment by jorgeriesco** [comment]
tengo dos 3.5 jaja

De hecho estaría buena que me dijeran como borrar la otra porfa

**Comment by sebacruzd** [comment]
Es con pip uninstall matplotlib

También se puede hacer a mano borrando la carpeta que se ubica en la carpeta site-packages, esto se ubica dentro de la carpeta de python.
