### ISSUE TITLE
Preguntas sobre asignación del valor congelamiento.

### ISSUE THREAD

**Issue by juanriveraf** [IIC2233/Syllabus#299]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tenia una preguntas sobre la asignación del atributo congelación. Cuando se lee el archivo de plantas, el valor de congelación podría ser 1 o siempre va a ser 0? Esto lo pregunto debido a que se supone que nosotros tenemos que definir el valor de congelación dependiendo de la resistencia y la temperatura, entonces no entiendo porque nos podría dar 1 también cuando lo extraemos del archivo si este depende de otro valor (temperatura). Ademas, quería preguntar como puedo hacer una pregunta más especifica de forma privada, para no compartir mi código por las issues. Muchas gracias!

**Comment by CatalinaBO** [comment]
Hola! Efectivamente el valor de congelación puede ser 1. Sin embargo, debes revisar que se cumpla la condición de congelamiento (resistencia térmica > temperatura del jardín). En caso de que esto no se cumpla, debes modificar el atributo para que sea válido.
Igualmente debes notar que esto no se considera como una línea errónea del archivo, ya que en teoría, el valor del atributo congelación se encuentra dentro de sus parámetros válidos {0, 1}.

**Comment by juanriveraf** [comment]
Muchas gracias
