### ISSUE TITLE
cheatcode con Qt.Key_S no funciona

### ISSUE THREAD

**Issue by Bjnazar** [IIC2233/Syllabus#299]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!
Al intentar hacer los cheatcodes encontré en la siguiente página los siguientes comandos para usar en pyqt5:
https://doc.qt.io/qtforpython-5/PySide2/QtGui/QKeySequence.html

No reconoce Qt.Key_** (letra) incluso importando Qt
o quizas solo funciona cuando se usa Ctrl dentro de las teclas?

de antemano muchas gracias!

**Comment by iespinazac** [comment]
Hola @Bjnazar!
Lo que tú quieres hacer está pensado para que sea resuelto con el método keyPressEvent visto en el curso 😄 
Si surge una nueva duda, puedes comentarla por este mismo medio!
