### ISSUE TITLE
Una funcion abstracta puede hacer referencia a si misma en el super?

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#299]
Hay una funcion que es relativa a la clase en la que esta, por lo que pense en hacer algo como "
```python
def nombre_funcion(self):
    if super().nombre_funcion() == True
    print("true")
```
pero tambien quiero que sea una funcion abstracta. Eso es posible? Si lo es, es pytonico?

EDIT: me equivoque con el codigo

**Comment by jeschuwirth** [comment]
Hola @sofiuni,

Por lo general es mala práctica utilizar una función de tu padre haciendo uso de super(), además las clases abstractas se utilizan como "esqueleto" para modelar las clases hijo que heredan de estas. Los métodos abstractos de las clases abstractas no deberían hacer nada ya que se ocupan solo para modelar tu programa, por lo que se suele colocar un `pass`, por este motivo llamar a estos métodos de tu padre abstracto no te va a ayudar en tu programa.

![image](https://user-images.githubusercontent.com/37160256/78719781-81018280-78f2-11ea-875f-11fc3f917277.png)

Espero que se entienda con el comentario y ejemplo, si te quedan dudas sigue comentando en la issue :)

**Comment by sofiuni** [comment]
La clase base es una clase abstracta, pero si los metodos no son abstractos, entonces se pueden heredar?

**Comment by jeschuwirth** [comment]
Sii, recuerda que los métodos de la clase padre siempre se heredan a la clase hija.

Te dejo un código de ejemplo que te puede ayudar:
![image](https://user-images.githubusercontent.com/37160256/78734270-cedbb200-7915-11ea-80bc-1bf532a4531a.png)

**Comment by sofiuni** [comment]
Genial, gracias!
