### ISSUE TITLE
Similitud Con EDD de python

### ISSUE THREAD

**Issue by simontoya** [IIC2233/Syllabus#299]
Hola!
Quería saber que tan parecida puede ser mi estructura de Datos a una que viene con Python, es decir si hago una EDD que se comporte exactamente como una lista es válido?

**Comment by ifcarrera** [comment]
Hola!
Es válido siempre y cuando no heredes de una EDD de Python y hagas todos los métodos de forma manual.
Saludos

**Comment by simontoya** [comment]
Perfecto! Gracias

**Comment by KnowYourselves** [comment]
Si tu EDD fue hecha desde 0 y no hace uso ni de list, set, dict, tuple, ect. Es válido.

Osea, tu puedes hacer una clase Lista que funcione, se vea, y se use exactamente igual que las list de python y estará bien siempre y cuando por debajo esté hecha por ti.

Saludos y éxito!
