### ISSUE TITLE
Cambio de lineas

### ISSUE THREAD

**Issue by BerroJessica** [IIC2233/syllabus#299]
Hola! 
Que tengo que hacer si quiero cambiar 3 lineas de mi código en vez de entregar tarde?

**Comment by jitorralba** [comment]
Hola @BerroJessica!
Puedes agregarlo en tu README indicando la línea, archivo y el contenido nuevo de esta, esto va sujeto a los descuentos que están en la [guía de descuentos](https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md)
