### ISSUE TITLE
Distribucion ventanas dentro del backend

### ISSUE THREAD

**Issue by bpb02** [IIC2233/Syllabus#299]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tenia la duda sobre como se espera que se estructure el frontend de la aplicacion. En teoria al haber una ventana de inicio y una ventana principal, entiendo que son dos clases distintas. Las hemos de definir dentro del mismo archivo .py dentro de frontend o debemos incluir dos archivos diferentes (uno para cada ventana).
Por otro lado pensaba si al iniciar el juego deberiamos cerrar la ventana de inicio y despues iniciar la ventana de juego dando lugar a un tiempo sin nada en pantalla. 

 Gracias

**Comment by AntonioVenegas** [comment]
Hola @bpb02, la decisión de incluir uno o dos archivos queda a tu criterio, si con solo uno notas que te estás pasando de las 400 líneas, puedes separarlo para tener un archivo por ventana.
Y segundo, cuando se cumplan las condiciones y se inicie el juego, la idea es que se cierre la ventana de inicio e inmediatamente se muestre la ventana de juego, por lo que no debería haber un tiempo "sin nada" en ese intertanto (excepto el tiempo que se demora en abrir la ventana de juego, que en general debería ser muy poco).

Saludos! :)

**Comment by nicolasaat** [comment]
Hola!, siguiendo un poco este hilo acerca de la distribución de ventanas. En el enunciado en **3.5 Fin del juego** dice "Se deberá reproducir el audio victoria.mp3 o el audio derrota.mp3 en caso de victoria o derrota, mostrando el resultado en la **Ventana de Juego** antes de que se cierre. Además, se mostrará un mensaje con (...)". ¿Es necesario que todo aquello se realice en la misma ventana de juego?, ¿o podemos crear más clases de ventanas (como por ejemplo "VentanaCreditos") cuando lo estimemos necesario?

**Comment by AntonioVenegas** [comment]
@nicolasaat, si puedes definir los pop ups como su propia clase y mostrarlos cuando sea necesario. Ahora voy a lockear esta issue, asi que si tienes más dudas te recomiendo abrir otra.

Saludos :)
