### ISSUE TITLE
Invitación del repositorio personal no recibido.

### ISSUE THREAD

**Issue by benjavicente** [IIC2233/syllabus#3]
Buenas,
Aunque me he inscrito en el formulario, no me ha llegado la invitación al repositorio personal. He intentado hacer varias cosas, pero aún no he podido acceder.

### Que he hecho:
- Revisar el correo desde la creación del usuario de GitHub y la inscripción en el formulario [Usuario GitHub](https://docs.google.com/forms/d/e/1FAIpQLSfhyU7m9Hm0By5lNdP4gpLWrGRexmL6J6Y-CrAWys3r-PKXdw/alreadyresponded) (busque en spam también)
- Entrar al repositorio con el enlace `github.com/IIC2233/{usuario}-iic2233-2020-1`
- Revisar las notificaciones de GitHub
- Editar las respuestas del formulario
- Avisar en clases a ayudantes
- Buscar un cuestionario en siding (mencionado [aquí](https://iic2233.github.io/registro/)), pero *no se han creado cuestionarios en este curso*

### Otra información:
- EL usuario de GitHub fue creado el 10 de marzo a las 10:47 ~ 10:48
- El formulario fue enviado a las 10:52 del mismo día
- La respuesta del form fue modificado el 12 de marzo a las 15:50

### Respuesta del formulario enviado:
*(las dos respuestas enviadas contienen los mismos datos)*
![image](https://user-images.githubusercontent.com/62021328/76656949-7d771780-654f-11ea-9755-ced99731cc6a.png)

**Comment by entamburini** [comment]
Estás respondiendo el formulario del semestre pasado :joy: Mala mía. Lo bueno es que la solución es sencilla: 

- Responde [este form.](https://forms.gle/PpUT1qY4ptMtrEng7) 
- Espera (aproximadamente) un minuto.
- Si todo sale bien, tendrás una invitación a participar en el repositorio :) 

Ya actualicé el link desde donde lo viste. Ahora está todo reparado :tada: 
Atento siempre a los anuncios de los profesores, ahí estaba el link correcto :o pero gracias a esto encontramos un error ^^

**Comment by benjavicente** [comment]
Perfecto, ahora me llego la invitación. Muchas gracias!
