### ISSUE TITLE
Falla con setup_test

### ISSUE THREAD

**Issue by vlyon07** [IIC2233/Syllabus#3]
- **Sistema Operativo:** Windows
- **Programa a instalar:** setup_test

- Foto del error:  
<img width="332" alt="error 1" src="https://user-images.githubusercontent.com/89176123/130081951-55e4692d-4c05-48d8-b4c1-c0df35910856.png">

<img width="188" alt="error 2" src="https://user-images.githubusercontent.com/89176123/130081999-a586c38e-cf3d-427b-a766-5db1ab5f7f66.png">

<img width="716" alt="error 3" src="https://user-images.githubusercontent.com/89176123/130082021-cabd1bf7-515c-470e-8d2b-e12d20259f45.png">

- Descripción del problema: sigo los pasos para correr el archivo setup_test, pero al buscar la carpeta iic2233 no la encuentra. Ya probé cambiándole el nombre y moviéndola de lugar. Adjunto las fotos que muestran que la carpeta está en el escritorio y que tiene solo el archivo adentro. Muchas gracias!

**Comment by Christian-Klempau** [comment]
Hola! Te grabé un pequeño video, sobre cómo podrías acceder a la terminal, dado que con `cd` no te funcionó.
https://www.loom.com/share/3a69606a4434400c9093a155738907e2

**Comment by vlyon07** [comment]
Ahí funcionó, muchas gracias!
