### ISSUE TITLE
Uso anaconca

### ISSUE THREAD

**Issue by eduecheverria** [IIC2233/syllabus#3]
que tan terrible es utilizar la ultima version de anaconda, que incluye la version 3.7 de python?

**Comment by hbkim94** [comment]
Se recomienda utilizar la versión 3.6 de python debido a que los ayudantes corregimos utilizando dicha versión, y se pueden generar inconsistencias en el momento de correr el código (por ejemplo, puede que un programa que funciona en 3.7 no corra correctamente en la versión 3.6).

Saludos!
