### ISSUE TITLE
Librerías permitidas/no permitidas en la T00

### ISSUE THREAD

**Issue by lily416** [IIC2233/syllabus#3]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:
 
> Puedo usar la librería nombre_librería para hacer explicación_de_lo_que_quiero_hacer
 
¡Recuerden especificar en su README qué librerías utilizan!
 
---
 
## ✅ **Librerías Permitidas** 
- random
- os
- math
- numpy
- string
- collections
- itertools
   * map
- copy
- sys.exit
- atexit
- dataclasses
 
## ❌ **Librerías Prohibidas**
- csv
- functools
- shutil
- pathlib
- pandas
 
## ☠️ **_Built-ins_ Prohibidos** 
El uso de alguna de las siguiente funciones es automáticamente un 1,0 sin discusión. 😭
- exec
- eval
- exception
 
 
 
¡Ánimo y éxito en sus tareas! 🌈🍀

**Comment by prochotito-rises** [comment]
hola! se pueden usar diccionarios?

**Comment by lily416** [comment]
Hola @prochotito-rises, ¿para qué quieres usar los diccionarios?

**Comment by prochotito-rises** [comment]
para hacer "menus anidados" (?)

**Comment by lily416** [comment]
@prochotito-rises Usalos con libertad 👍

**Comment by Alonsortega** [comment]
Puedo usar la librería time para darle cierta "fluidez" a mi programa?

**Comment by lily416** [comment]
Hola @Alonsortega, ¿a qué te refieres específicamente con darle "fluidez" al programa?

**Comment by Alonsortega** [comment]
En intro a la programación utilizaba la función time.sleep() para que los menús no aparecieran tan "bruscamente", y quisiera saber si puedo hacer lo mismo.

**Comment by lily416** [comment]
@Alonsortega No puedes ocuparlo, ya que es innecesario y puede llegar a complicar o molestar en la corrección de la tarea. 😅  
Mejor focalizate en realizar el menú simple y en completar otras funcionalidades de la tarea. 😉

**Comment by prochotito-rises** [comment]
hola, puedo usar 'combinations' de itertools para la creación del tablero?

**Comment by prochotito-rises** [comment]
hola, puedo usar `product` de `itertools` para ayudarme a crear el tablero?

**Comment by lily416** [comment]
Hola de nuevo 😄 @prochotito-rises, no puedes hacer uso de `product`, en esta tarea queremos evaluar conocimiento básico y por desgracia `product` no es un aporte en dicho objetivo. 😓

**Comment by MartinAracena** [comment]
Puedo usar diccionarios para ordenar las opciones de menu que son numericas y darles un valor segun el diccionario?

**Comment by lily416** [comment]
@MartinAracena sí, puedes usar diccionarios.

**Comment by cristozille** [comment]
Hola, se puede usar la librería pickle para guardar los tableros en un archivo?

**Comment by tavalenzuelag** [comment]
Hola! usar try and except tampoco estaría permitido?

**Comment by lily416** [comment]
@cristozille, no puedes hacer uso de `pickle`, ya que es materia que se verá a futuro en el curso y, como se dice en los objetivos, se espera que en esta tarea trabajen con archivos de texto leyendo, escribiendo y procesando datos.

@tavalenzuelag, no puedes usar `try/except` ya que es uno de los _built-ins_ prohibidos (`exception`).

**Comment by Paldana99** [comment]
Hola! Se puede utilizar el modulo ast para convertir strings a listas mas comodamente?

**Comment by lily416** [comment]
Hola @Paldana99, no puede utilizar `ast`, ya que en esta tarea queremos evaluar conocimiento básico, como el procesamiento de _strings_ y por desgracia `ast` no es un aporte en dicho objetivo. 😓

**Comment by MatiasDuhalde** [comment]
¿Se puede ocupar el módulo `re` para poder manejar el input del usuario sin tener que usar tantos `if`s? Principalmente es para distinguir un string que siga el formato pedido en las prompts de uno que no.
Salu2

**Comment by ranelson1** [comment]
Hola! ¿Puedo ocupar generadores para hacer el tablero?

**Comment by EstebanReyes1998** [comment]
Hola buenas, se puede utilizar la function list() ?

**Comment by mimadri** [comment]
Hola :) puedo usar sets para guardar coordenadas?

**Comment by vnespinosa** [comment]
Hola, puedo usar pickle para leer los strings que guardo en un .txt como listas?

**Comment by lily416** [comment]
@MatiasDuhalde no puedes usar `re` para procesar los inputs de los usuarios, se espera que utilicen control de flujo para manejarlos  (`if/elif/else`).

@ranelson1 no puedes ocupar generadores, ya que no es necesario en esta tarea (se puede lograr con la materia de introducción a la programación) y es materia que se verá más adelante en el curso.

@EstebanReyes1998 sí, puede utilizar `list()`.

@mimadri sí, puedes ocupar `sets`.

@vnespinosa como se dijo anteriormente no se puede ocupar `pickle`.

**Comment by szabala** [comment]
Hola! esta permitido utilizar la libreria JSON para manejar listas en archivos?

**Comment by lily416** [comment]
@szabala no puedes ocupar `json`, ya que en esta tarea queremos evaluar conocimiento básico, como el procesamiento de _strings_ y por desgracia `json` no es un aporte en dicho objetivo. :sweat:

**Comment by cristozille** [comment]
Hola, se puede utilizar la función lambda?

**Comment by Rafoxxa** [comment]
Se puede ocupar el built in copy? y la libreria copy?

**Comment by entamburini** [comment]
Estimade... mira al tope de esta issue 👀

**Comment by itplanella** [comment]
Hola, se puede utilizar la libreria "operator", especificamente el comando "itemgetter"? es para  ordenar una lista con respecto a cierto valor.
ej:
sorted(lista,key=itemgetter(0))

Gracias de antemano.

**Comment by lily416** [comment]
@itplanella sí, puedes utilizar `itemegtter`, también puedes ocupar la _lambda function_: `lambda x: x[0]` que sería su equivalente.

**Comment by adbakulic** [comment]
Hola! Quería saber si se puede usar la función filter para poder convertir strings a listas.

**Comment by lily416** [comment]
Hola @adbakulic, sí puedes usar `filter`.

**Comment by adbakulic** [comment]
Gracias!! @lily416

**Comment by HghSpc** [comment]
Hola, ¿se puede impotar la librería ast, para convertir una string que tiene forma de lista de lista en la lista de lista correspondiente?

**Comment by Felopo** [comment]
Hola, quería saber si estaba permitido usar la librería json.

**Comment by entamburini** [comment]
> @szabala no puedes ocupar `json`, ya que en esta tarea queremos evaluar conocimiento básico, como el procesamiento de _strings_ y por desgracia `json` no es un aporte en dicho objetivo. 😓

@Felopo está más arriba

**Comment by Felopo** [comment]
Perdón, no había leído, Gracias! @entamburini

**Comment by tlagosh** [comment]
hola! puedo usar .isdigit()?

**Comment by entamburini** [comment]
Hola @tlagosh, revisa el pie de página de la página 4 del enunciado 😉 (PD: si)
