### ISSUE TITLE
Problema al intentar clonar repositorios - los path ya existen

### ISSUE THREAD

**Issue by danvillablanca** [IIC2233/syllabus#3]
### Prerrequisitos
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Al realizar "git clone [repositorio del curso]", me aparece el siguiente mensaje: 

> fatal: destination path 'contenidos' already exists and is not an empty directory.

¿Cómo se resuelve esto?

¡Gracias!

**Comment by nicoguz** [comment]
Hola!
Esto probablemente ocurre porque ya existe un directorio con el nombre 'contenidos'.
Cuando clones un repositorio asegurate de que no tengas archivos o carpetas con el nombre de este para no generar este tipo de errores. 
Te recomiendo que crees una carpeta con un nombre como 'IIC2233 - Contenidos' o algo por el estilo y clones el repositorio dentro.

**Comment by lerivas707** [comment]
Similar problema, pero con el siguiente mensaje:
fatal: could not create work tree dir 'lerivas707-iic2233-2021-1': Permission denied

**Comment by nicoguz** [comment]
Hola!
El error anterior se refiere a un error de 'permiso'. Es posible que te encuentres en un directorio en el que no tienes permiso para 'escribir'. Como primer acercamiento podrías intentar clonar el repo en un lugar que sabes que puedes crear archivos o carpetas. Si te es más comodo puedes crear un directorio e intentar clonarlo dentro del nuevo directorio, esto te asegura que tengas permisos.
Avisame como te va!

**Comment by lerivas707** [comment]
Gracias. Efectivamente era un tema de permisos.

**Comment by nicoguz** [comment]
Perfecto, y se clona todo bien en la dirección que quieres? O sigues sin poder hacerlo?

**Comment by lerivas707** [comment]
Clonó perfecto. Gracias.
