### ISSUE TITLE
macOS error con "brew install git"

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2233/syllabus#3]
- Sistema Operativo: macOS 10.15
- Programa a instalar: Git

- Descripción del problema: Al abrir el link que esta en la pagina de los softwares obligatorios para instalar Git, me entrega varias opciones (en el ss salen, son 3: homebrew, Xcode y binary installer). Tengo que instalar las 3 o son distintas opciones y uno puede elegir la que quiera? Lo otro, segui el procedimiento para instalar Homebrew, pero cuando este finalizó al poner el codigo "$ brew install git" como dice en la pagina, me dice que el comando no se encuentra (como se ve en el screenshot).

![Screen Shot 2020-08-12 at 8 51 52 PM](https://user-images.githubusercontent.com/69609564/90082524-fab0df00-dcdd-11ea-88b2-18f9d7c05668.png)
![Screen Shot 2020-08-12 at 8 53 51 PM](https://user-images.githubusercontent.com/69609564/90082532-fedcfc80-dcdd-11ea-87f3-6854433ab47f.png)

**Comment by igbasly** [comment]
Hola @conyfernandezt ✌️

Comienzo preguntando si lo único que has hecho es `brew install git`??
De ser así, ingresa el comando `git --version` y cuéntame si aparece alguna versión de git instalada.
Esto ya que se supone que MacOS trae por defecto instalado git, en cuyo caso no es necesario pasar por la instalación con brew.

Quedo atento a lo que ocurre,
Saludos 😄

**Comment by igbasly** [comment]
@conyfernandezt no noté que cuando ingresaste el comando en tu terminal, ingresaste además el símbolo `$` (peso), este como puedes notar, ya viene incluido en la línea de comando, por lo que no es necesario incluirlo nuevamente.

Para cualquier comando solo debes ingresarlo directamente, en este caso `brew install git` o como te mencionaba `git --version`.

**Comment by conyfernandezt** [comment]
Hola, ingrese el comando "git --version" y me dijo "git version 2.21.0 (Apple Git-122)", asique supongo que eso significa que esta instalado jajaja. Si esque esto significa que tengo el git, podria desinstallar el Homebrew?

**Comment by igbasly** [comment]
Efectivamente, significa que ya está instalado 🙌. De todas formas no te recomendaría desinstalar Homebrew, ya que es un gestor de paquetes bastante utilizado en MacOS y que te puede ser útil más adelante.

También, como dato de utilidad :bulb:, si en el futuro te encuentras con algo del tipo `$algun_comando`, el `$` indica que es un comando de la terminal y no debe ser incluido al ejecutarlo.

Espero que hayamos resuelto todo y no dudes en preguntarnos :v:.
