### ISSUE TITLE
Detalles bonus "Funciones atómicas"

### ISSUE THREAD

**Issue by c4ebt** [IIC2233/Syllabus#30]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

El enunciado define el requisito para obtener el bonus por funciones atómicas de la siguiente manera: "cada función o método definido dentro del código contenga un máximo de 15 líneas de código". Cómo se cuentan exactamente estas líneas de código?

Me parece que la pregunta se respondería más fácilmente a través de un ejemplo:

```python
def imprimir_mensaje(mensaje):
    """
    Esta función imprime el mensaje recibido en
    el argumento mensaje
    """
    # Ahora imprimimiré el mensaje
    print("El"
          "mensaje" \
          + "es:\n",
          mensaje)
```
(El ejemplo es claramente exagerado, pero apunta a aclarar exactamente como se cuentan las líneas de código para el bonus.)

Para efectos del bonus de funciones atómicas, **cuantas líneas tiene la función del ejemplo anterior y qué líneas son estas?**

**Comment by Hernan4444** [comment]
Hola @c4ebt 

Serían 4 líneas, correspondiente a
```python
    print("El"
          "mensaje" \
          + "es:\n",
          mensaje)
```

En resumen, son 15 líneas de código las que cuentan. Si esa línea es tan larga que hay que hacer 2 líneas, se contarán las 2. Lo que se salva del contador son los comentarios.

Saludos c:

**Comment by c4ebt** [comment]
Muchas gracias!

**Comment by Mcroquevielle** [comment]
Hola! Con respecto a lo mismo, si defino sub-funciones para hacer una función como contaría?
Por ejemplo, con tablero.py (que se nos entrega) la función imprimir_tablero esta compuesta por 2 funciones. En este caso, se cuenta cada función por separado? Es decir, la función imprimir_tablero tendría 4 líneas? O se cuentan también las líneas de las funciones que la componen?

**Comment by Hernan4444** [comment]
Hola @Mcroquevielle 

Cada función se analiza de forma independiente. Por lo tanto, imprimir_tablero tendría 4 líneas.

Saludos c:

**Comment by jorgee02** [comment]
Hola!
Tengo una pregunta: se cuenta la línea de "return" en el caso que exista?

**Comment by Hernan4444** [comment]
Hola @jorgee02 

Si cuenta ☺️,

Saludos c:

**Comment by jorgee02** [comment]
Gracias por la pronta respuesta profe
