### ISSUE TITLE
Ejercicio 2.1 

### ISSUE THREAD

**Issue by lsschmitz** [IIC2233/syllabus#30]
No me queda claro que pasa si el ataque de un jugador es igual a la defensa del otro jugador. Esto es, si hay un empate que hago con las cartas?

**Comment by tomasgv** [comment]
¡Hola @lsschmitz!

Esta duda fue respondida en #28 👀 . En resumen queda a tu criterio.

Si te quedaron dudas, puedes comentar en esa _issue_.

¡Saludos!
