### ISSUE TITLE
Visual Studio Code, add port

### ISSUE THREAD

**Issue by santiago3c** [IIC2233/Syllabus#30]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

Hola, que en la parte de abajo del VS me sale una notificación, y al apretarla me sale una opción de "add port" y no se si tengo que apretarla o no, que realmente no se que significa
![Captura de pantalla (154)](https://github.com/IIC2233/Syllabus/assets/142272696/1ab3973e-f14e-4cec-8fef-ce4e60f2b51b)

**Comment by Hernan4444** [comment]
Hola @santiago3c 

No debes preocuparte por eso, no hay que hacer nada. Lo que ocurre es que WSL es detectado como "otra red" y para conectar por internet a otra red hay que usar un puerto, pero solo ignora esa parte, no debería ocasionar problemas.

Saludos!

**Comment by santiago3c** [comment]
gracias!
