### ISSUE TITLE
Diagrama de clases y properties

### ISSUE THREAD

**Issue by FJavierOss** [IIC2233/Syllabus#30]
Estaba leyendo los contenidos referente a diagramas de clases y no pude encontrar como referenciar en el diagrama de clases el uso de las properties. ¿Será necesario hacerlo dado que siento que de otra manera no queda explicito el funcionamiento del codigo? Y en el caso de que fuera así, ¿cómo se haría?

**Comment by fringlesinthestreet** [comment]
Hola @FJavierOss 

Los diagramas de clase son parte de las herramientas que provee _Unified Modelling Language_ (UML). Estas herramientas son independientes del lenguaje por lo que no existe una convención sobre cómo se deben poner las _properties_. 

Utilizaré un extracto de la [Ayudantía 1](https://github.com/IIC2233/Syllabus/blob/master/Ayudantias/Ayudantia01/Ayudantia01%20Solucion.ipynb) para mostrar una forma de visualizar las _properties_:

Se tiene la clase `Minion` la cual posee dos _properties_: `vida_actual` y `vivo`.
```
class Minion:
    _id = 0

    def __init__(self, vida_maxima):

        self._id = Minion._id 
        Minion._id += 1

        self.vida_maxima = vida_maxima
        self.__vida_actual = vida_maxima

    @property
    def vivo(self):
        return self.__vida_actual > 0
    
    @property
    def vida_actual(self):
        return self.__vida_actual

    @vida_actual.setter
    def vida_actual(self, value):
        if value < 0:
            self.__vida_actual = 0
        elif value > self.vida_maxima:
            self.__vida_actual = vida_maxima
        else:
            self.__vida_actual = value
```

Una forma de crear el diagrama de esta clase es el siguiente (el que se mostró en la primera clase):

![uml properties](https://user-images.githubusercontent.com/20802067/37687578-d66e67d6-2c7a-11e8-8628-27e9d677b34c.png)

Esto quiere decir que la clase `Minion` tiene:

* `_id`: es un atributo de tipo _integer_.
* `vida_maxima`: es un atributo de tipo _integer_.
* `vivo`: es una property con sólo el _getter_ implementado, retorna un _boolean_.
* `vida_actual`: es una property con el _getter_ y _setter_ implementado, retorna un _integer_.

Debo recalcar que esta es una forma para representar las _properties_ en un diagrama de clases, pero que ayuda a mostrarlas de manera explícita.
