### ISSUE TITLE
Duda acerca del tamaño máximo del tablero

### ISSUE THREAD

**Issue by aLotOfGluten** [IIC2233/Syllabus#30]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

¿Cuál es el tamaño máximo del tablero que hay que hacer? 2x2, 3x3, 1000 x 1000, n x n ?

**Comment by PedroDP99** [comment]
Hola!
En el inciso 5.1 del enunciado se especifica el posible tamaño del tablero, donde las dimensiones X e Y deben estar en el rango [3, 15]. Es decir, el tamaño máximo del tablero es de 15x15.
