### ISSUE TITLE
¿Cómo trabajar con los archivos .csv? 

### ISSUE THREAD

**Issue by ElTurkos** [IIC2233/syllabus#30]
Para la tarea 00 tenemos que traspasar los excel a mano o tenemos que poder hacer que el programa lea los excel y los modifique?

**Comment by KnowYourselves** [comment]
Hola @ElTurkos! 

Se espera que tu programa lea los contenidos del csv y los utilice como describe el enunciado.  En [esta sección de los contenidos](https://github.com/IIC2233/contenidos/blob/master/semana-00/3-paths.ipynb) puedes ver algunos ejemplos de como abrir y leer archivos haciendo uso de _Python_.

Éxito!
