### ISSUE TITLE
Duda con respecto al largo y ancho del tablero

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#30]
Hola
Hay alguna relación obligada entre largo/ancho con distancia horizontal/vertical  cuando creo el tablero o es completamente libre la forma en que lo haga (por ejemplo ancho si o si tiene que ser vertical o puedo poner ancho horizontal y largo vertical) porque por lo general se relaciona ancho con la menor distancia de un objeto plano 
gracias de antemano

**Comment by KnowYourselves** [comment]
Hola @JuaniAndres!

Para esta tarea no existirá la relación de la cual hablas. Puedes simplemente asignar el tamaño vertical y horizontal a la `N` y `M` o al revés, lo importante es que esto sea consistente con las coordenadas que se utilicen para descubrir las baldosas.

Éxito!

**Comment by JuaniAndres** [comment]
Gracias había asumido eso mismo pero mejor asegurarse

**Comment by sebacarrasco** [comment]
Hola, quería saber si es que es estrictamente necesario que las variables de largo y ancho se llamen M y N. Sé que así las ponen en el enunciado, pero yo las llame "ancho" y largo" con el fin de tener variables con nombres más descriptivos.

**Comment by KnowYourselves** [comment]
No es necesario que se llamen `N` y `M`, está bien lo que hiciste. 
Éxito!
