### ISSUE TITLE
Duda tarea

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#30]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holaa, en en enunciado de la Tarea 1, en "2. Predios de cultivo", se nos dice que la esquina inferior derecha tiene coordenadas (-1,-1). Mi pregunta es si es que esto es así efectivamente o yo estoy entendiendo mal el enunciado.

**Comment by xperseosses** [comment]
El enunciado dice: 
"En el lado opuesto, la esquina inferior derecha será la última celda ubicada en la coordenada (alto - 1, ancho - 1)"

Básicamente en una matriz de 5x5, la esquina inferior derecha tendrá coordenadas de [ 4 , 4 ], porque se empieza a contar desde el 0.

**Comment by vgalfaro** [comment]
Hola! tal como dijo tu compañero, la coordenada de la esquina inferior derecha corresponde a (alto - 1, ancho - 1), agregar que, en python puedes acceder al último elemento de un array con array[-1], entonces también puedes acceder con predio[-1][-1], ya que corresponde a la última fila y a la última columna. Saludos!
