### ISSUE TITLE
Ejecución de código en Visual Code

### ISSUE THREAD

**Issue by BenediktKd** [IIC2233/syllabus#30]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Al escribir print("Hola") en visual code y ejecutarlo con play, me aparecía la cmd de git, sin dar ninguna respuesta al código. Al consultarlo con el ayudante, logramos que apareciera la cmd de Windows en desde la de git y aparece el output del codigo escribiendo: python nombre_archivo.py // Pero más de eso no se alcanzó a hacer. Por ende, el Visual Code no me funciona correctamente, a pesar de haberlo instalado exactamente como aparece en el video. Y en la terminal de VS no sale nada tampoco.

Adjunto archivo donde se visualiza lo que pasa.
![Captura de pantalla 2021-03-23 153337](https://user-images.githubusercontent.com/80901100/112201052-a31d0f00-8bee-11eb-8534-0276e3ea3f94.jpg)

**Como se puede solucionar este problema?**

**Comment by dfloreaa** [comment]
Hola Benedikt :)

Para ejecutar mi código en Visual Studio normalmente utilizo la combinación de teclas **Ctrl + F5**, o bien puedes ejecutarlo desde aquí:

![image](https://user-images.githubusercontent.com/62019645/112230847-619f5a80-8c14-11eb-9fec-53aa1d609f77.png)

En caso de no funcionarte avísame, un saludo! ☺🦝

**Comment by BenediktKd** [comment]
Sigue ocurriendo lo mismo y no corre el código.
![Captura de pantalla 2021-03-24 102438](https://user-images.githubusercontent.com/80901100/112318113-7539d800-8c8b-11eb-9cac-fe0113c1529a.jpg)

**Comment by dfloreaa** [comment]
Finalmente lo resolvimos, solo costó una llamada de 30 minutos y muchas búsquedas en Google, para cualquiera que tenga este problema también, aquí dejo un pequeño resumen de como arreglarlo:

**[PROBLEMA]**
La consola no corre el código y se cierra con el error "exit code 3221225786", se ve algo así:
![image](https://user-images.githubusercontent.com/62019645/112544140-73f4d200-8d95-11eb-95ad-dd8ce5a33774.png)

**[SOLUCIÓN]**
1. Abrir VSCode y dirigirse al engranaje abajo a la derecha y entramos a Settings (Configuraciones)
![image](https://user-images.githubusercontent.com/62019645/112544332-a0105300-8d95-11eb-89a5-634f245a9fd0.png)

2.  Escribimos en el buscador ``conpty``
![image](https://user-images.githubusercontent.com/62019645/112544430-c0d8a880-8d95-11eb-80ff-fea1f4518c43.png)

3. Desactivamos la configuración e intentamos correr nuestro código
![image](https://user-images.githubusercontent.com/62019645/112544503-d8179600-8d95-11eb-8aa7-9b09c2202615.png)

![image](https://user-images.githubusercontent.com/62019645/112544632-02695380-8d96-11eb-9601-592f23dc312b.png)

Espero que si alguien más llega a tener este problema pueda resolverlo mediante este método, si no, por favor que comente en esta issue para intentar buscar otra solución.

Un saludo a quien este leyendo, ánimos con el semestre! ☺
