### ISSUE TITLE
git status: mensaje no deseado 

### ISSUE THREAD

**Issue by jahernandez2** [IIC2233/Syllabus#30]
Hola! Estoy haciendo la AP0 2.5 y luego de crear el archivo bienvenida.py y agregarlo a mi repositorio privado, una vez que coloco el git status, no me aparece mi como "modied" en "Changes not staged for commit", como debería, lo que no me deja seguir con lo que viene (git add y el commit). 
Gracias de antemano.

**Comment by tqmbanados** [comment]
Hola! Creo que no entiendo mucho tu problema 🤔 . Podrías mandar un pantallazo de tu terminal con los comandos? Eso me ayudaría a entender mejor lo que sucede.
En todo caso, si es que no sale el "changes not staged for commit", es posible que no hayan cambios! Revisa bien eso :)

**Comment by jahernandez2** [comment]
![issue 1](https://user-images.githubusercontent.com/62116520/131238906-4680b12d-eeee-40d3-9a81-6948ce663ea8.png)

**Comment by tqmbanados** [comment]
Yaa, ahí veo mejor. Al menos de esa imagen, pareciera estar todo funcionando bien, pero hay algunos problemas:
El archivo `desktop.ini` es un archivo invisible que se encuentra en el `Desktop` (u `Escritorio`) en los computadores Windows (desconozco si también es así en otros sistemas operativos). También se encuentra dentro de carpetas que tienen alguna configuración especial u otros casos específicos 🤔 . Por el momento ignóralo, pero una vez que sepas hacer bien el `.gitignore`, te recomiendo agregar `desktop.ini`. 

También hay algunos errores de concepto con git. En el tercer comando, `git add bienvenida.py`, estás tratando de agregar un archivo que no se puede encontrar desde la ubicación donde está abierta la terminal. Cuando usas `git add`, el archivo agregado debe ser uno de los que te aparece en rojo como "untracked files" al usar git status. En este caso, te falta "agregar" `Actividades\AP0`, por lo que se trata de la carpeta `AP0` completa!. Si quieres agregar archivos específicos de ahí, te recomiendo moverte hacia la carpeta (para esto usamos el comando `cd <carpeta>`. Es decir, tu tendrías que hacer `cd Actividades/AP0`. 

Ahora bien, también puedes hacer `git add Actividades/AP0`! Una vez que hayas agregado todo, al usar `git status`, te deberían salir los mismos archivos que agregaste pero en **verde**. Ahí los puedes commitear. Cuéntame cómo te va!

#### Sigue mini tutorial de git...
El comando `git status` nos muestra información acerca de el *estado* de la carpeta git. Nos dice alguna información que no vemos en el curso, pero algunos elementos importantes son los siguientes:
1.- **Untracked Files**: Archivos que se han cambiado, pero no han sido "agregados" a git. Es decir, estos archivos no son parte del control de versiones. Usualmente se muestran en rojo. Para agregarlos, usamos `git add <ruta_del_archivo>`. También podemos usar `git add -A` si queremos agregar **todos** los archivos. 
2.- **Changes staged for commit**: Estos son archivos que han cambiado, y han sido "agregados" a git. Sin embargo *aún no los hemos guardado como un commit permanente*. Estos usualmente aparecen en verde. Para guardar estos cambios como un nuevo commit (o una nueva *versión*), usamos `git commit -m <nombre_del_commit>`. El `nombre_del_commit` es un string que describe a grandes rasgos los cambios de esta versión. Un ejemplo: `git commit -m "main.py creado"`. 
3.- Si hay commits en nuestro computador que **no** están en el repositorio de github. En este caso, usamos el comando `git push` para enviar los commits nuevos.

**Comment by jahernandez2** [comment]
Muchas gracias @tqmbanados !

**Comment by tqmbanados** [comment]
Me alegro que te haya funcionado! :cat:
