### ISSUE TITLE
Problemas guardar modulo Atom

### ISSUE THREAD

**Issue by mpsubiabre** [IIC2233/syllabus#300]
Hola, tengo un problema al momento de guardar los cambios en un archivo, especificamente funciones.py, el cual no se guarda quedando todo el rato (al apretar control + s) en "beautification in progress" mientras que otros modulos se siguen guardando sin problema.
![image](https://user-images.githubusercontent.com/42593773/64913716-6b8cf700-d71b-11e9-9f76-ead2f5d02689.png)

**Comment by jmwielandt** [comment]
Hola!

Primero decirte que no uso atom, sino vscode y lidio con otro tipo de problemas, pero busqué un poco y en el pasado ha habido algunos problemas con atom-beautify de ese estilo ([1](https://github.com/Glavin001/atom-beautify/issues/1458), [2](https://github.com/Glavin001/atom-beautify/issues/2296)) . Si puedes, mi consejo de persona que no usa atom es que lo desactives, al menos temporalmente por la entrega de la tarea (si no la has entregado ya).

Si no puedes desactivarlo, abre el archivo con bloc de notas u otro editor de texto, copia el contenido de atom al otro y guárdalo en el otro y cierra el archivo en atom (sin guardar). Eso debería al menos ayudarte para la entrega 😟

Seguiremos buscando información, pero sería útil que guardes el código con problemas en otro archivo en tu repo (fuera de la carpeta de la entrega) y nos dices cuál es, para intentar verificar si efectivamente es un bug de atom-beautify y reportarlo o si es otro el problema.

Saludos, quedamos atentos 😉
Espero que tu entrega no se haya visto perjudicada por esto 😥

**Comment by mpsubiabre** [comment]
Muchas gracias, para la entrega hice lo del block de notas.
Subi el archivo en el repo junto con la carpeta tareas y actividades, se llama "funciones.py", por si lo puedes ver.
Saludos!
