### ISSUE TITLE
Mejora de torres

### ISSUE THREAD

**Issue by Oisangui** [IIC2233/syllabus#300]
Tengo una barra menú en la parte inferior de la ventana de juego. Puedo colocar los botones de mejora ahí para luego hacer click en la torre que quiero mejorar? O es necesario colocar botonoes encima de cada torre en fase de construcción?

**Comment by gatochico** [comment]
Hola! Con respecto a las mejoras, cada una puede ser comprada **una vez** y aplican a **todas** las torres al momento de la compra. Por lo tanto, no es necesario implementar un botón encima de cada torre, ya que una mejora afecta a todas simultaneamente. Saludos!
