### ISSUE TITLE
[4.2.3] Comandos que retornan un conjunto de datos

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#300]
Tengo un par de dudas respecto a este item:

1. Respecto a los retornos en gerenal, estos deben ser generadores o pueden ser listas, set, etc.
2. En la funcion operar: no entiendo bien que hace el simbolo ">=<" -> podrían darme un ejemplo (de la operación que hace el simbolo)
3. En la funcion evaluar no entiendo que funcion cumplen los parametros inicio y final -> podrían darme un ejemplo de qué hace esta funcion y de los valores que debería retornar en una Columna.

Disculpen tantas preguntas, pero prefiero preguntar antes que quedarme con las dudas y hacer todo mal ... 

Saludos :B

**Comment by iqacevedo** [comment]
Hola!
1-. En 4.2.1 se indica que columna (retorno de todos esas consultas) puede ser lista, set u otro iterable. Sin embargo, debes considerar el tamaño de los datos que estas guardando (No es muy óptimo guardar una lista de 1.000.000 de datos).
2-. Aproxima los datos que se encuentre en la columna (uno a uno).
Ejemplo: ['operar', [1.12, 1.3658, 1.15, 1.203], '>=<', 1] retorna [1.1, 1.4, 1.2, 1.2]
3-. En evaluar, generas datos a partir de una función. Debes aplicar esa función a un conjunto de datos para generar los que retorna la consulta. Ese conjunto de datos al que le aplicas la función comienza en el valor de inicio, el siguiente es inicio + intervalo, el que sigue inicio + 2*intervalo, y así sucesivamente hasta que llegues a final (que indica cuando parar de generar esos números).

Espero que aclare tus dudas!
Saludos!

**Comment by acrojas2** [comment]
Creo que aún no entiendo qué hace la funcion evaluar, si ppudieras poner un ejemplo con una funcion sencilla y numeros sencillos, tal y como está explicado el punto 2. 

Saludos :B

**Comment by Hernan4444** [comment]
digamos que tenemos la funcion `x**2`. quel llamaremos `f_x`
¿Que hará la consulta `["evaluar", f_x, 0, 10, 2]`?

1.- Generará una lista (o set de datos) con los números del 0 al 10 con un intervalo de 2, es decir: `[0, 2, 4, 6, 8, 10].`
2.- A cada numero le aplicará la funcion f_x, es decir, la lista quedará: `[0, 4, 16, 36, 64, 100]`.
3. Retornará esa nueva lista
pd: En este caso usé listas pero para demasiados datos (5.000.000 por ejemplo) es mejor usar generadores.

Espero que ahí se entienda mejor
Saludos!!

**Comment by acrojas2** [comment]
@Hernan4444 
última aclaración que necesito: 
si la consulta fuera ["evaluar", f_x, 1, 11, 3]
1.- Se generaría esta lista -> [1, 4, 7, 10] ó [1, 4, 7, 10, 11] ó ¿cual?
2.- ¿Puedo asumir que f requiere solo una variable?
3.- ¿Puedo asumir que 0 < inicio <  final e intervalo >= 0?

**Comment by Hernan4444** [comment]
1) generaría [1, 4, 7, 10], porque el siguiente es 13 y eso ya no está en la lista
2) Si puedes asumir eso porque F solo puede ser uno de los modelos de probabilidad (con los parámetros ya entregados)
3) No puedes asumir eso, se puede empezar de un numero negativo, podemos dar un intervalo decimal (revisar ejemplos) o podemos entregar un numero grande como inicio, otro mas pequeño como final y un intervalo negativo (entero o decimal).

Saludos!!

**Comment by acrojas2** [comment]
De las funciones:

extraer_columna: se espera que retorne un generador u otra cosa (?)
filtrar: Si por ejemplo se recibe una lista se espera que retorne una lista filtrada, si se recibe un generador se espera un generador filtrado, ..., si se recibe una tupla se pera un set filtrado.(?)
operar: misma duda que en 2. pero operando sobre los valores de la columna (?)
evaluar: se espera que retorne un generador u otra cosa(?)
Saludos :B

**Comment by Hernan4444** [comment]
sobre filtrar y operar, no es necesario que respetes el tipo de dato ingresado, puedes simplemente devolver siempre un generador aunque te llegue un set o una lista.

Sobre las demás funciones, está bien :+1: 

Saludos!!
