### ISSUE TITLE
SetPixmap no me funciona correctamente 

### ISSUE THREAD

**Issue by LunaGarces** [IIC2233/Syllabus#300]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

mi clase zombie emite todas la señales, que van dirigidas al frontend, pero la imagen de mi Zombie no se muestra, no se si me podrían ayudar

**Comment by Lord-Kelsier** [comment]
Hola @LunaGarces, mire tu tarea y veo que si estan solo  que fuera del mapa 
![image](https://user-images.githubusercontent.com/69614275/195961845-30c666d8-be06-467e-bb47-add6ce528fb8.png)
