### ISSUE TITLE
Sprite Celda Vacía

### ISSUE THREAD

**Issue by PauRovira1** [IIC2233/Syllabus#300]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, en la carpeta de sprites no existe ningun sprite para la celda vacia, esta imagen falta o nosotros tenemos que ver como hacerla.

**Comment by lucasvsj** [comment]
Hola @PauRovira1 
En efecto no les entregamos una imagen para las celdas vaciás, es algo que deben manejar ustedes.
Personalmente, no recomendaria agregar una imagen (*sprite*) en este caso. Lo que mas recomiendo es que busques el comando `setStyleSheet` (el cual es un metodo de un `widget`). Con este, puedes configurar el color de fondo de tu `widget` y asi elegir el que mas te acomode.

**Comment by diegoherrerag2000** [comment]
Hola, tengo una duda sobre esto. Como dices no hay imagen entonces tenemos que usar setStyleSheet, ¿importa el color que le pongamos?, es que, no se cómo encontrar el exacto que está en el ejemplo del enunciado.

**Comment by tremendapithon** [comment]
El color " #1f1f1f" podria servir

**Comment by tremendapithon** [comment]
Ya que se parece bastante al del enunciado
