### ISSUE TITLE
S3 - 1.1 duda con "agregación" - Diagrama de clases

### ISSUE THREAD

**Issue by alterdieg0** [IIC2233/syllabus#300]
Hola tengo una duda de contenido, en la parte de diagrama de clases no entiendo muy bien cómo y cuándo se explicita la _agregación_ (rombo blanco).

Estaba haciendo el diagrama de GoT del ejercicio propuesto 1.1 y pensé en incluir la clase `LoboGuargo` como agregación de la clase `Stark` ya que pueden poseer uno pero a la vez son independientes. 

Mis preguntas son: 

* ¿Cuándo y cómo determinar si una clase es agregación de otra, y en qué influye en el código?

* ¿La agregación se ocupa solo cuando una clase está hecha de muchas instancias de otra clase? como ocurre en el ejemplo de ejército de `Goombas` o está bien hecho en como lo hice en mi diagrama de GoT aunque los Stark solo tengan un LoboGuargo, y en ese caso, ¿está bien decir entonces que la clase `LoboGuargo` no es una _composición_ de `GoT`? o además de ser agregación de `Stark` es a su vez composición de `GoT`?

dejo una foto de mi diagrama para referencia
gracias de antemano 🐈 
![Untitled Diagram](https://user-images.githubusercontent.com/28828655/91665863-9dcb6c00-eac6-11ea-8ef3-06a3beeb5171.png)

**Comment by Juampisaez** [comment]
Hola @alterdieg0 

- Respondiendo a tu primera pregunta, tal como dice en los contenidos _"el tiempo de vida del objeto que agregamos es independiente del tiempo de vida del objeto que lo incluye."_, es decir por ejemplo, imagina que el objeto _alumno_ esta cursando varios ramos (cada ramo puedes considerarlos con un objeto distinto), si bota un ramo se deberá eliminar de los ramos cursados por el alumno (estos pueden ser almacenados en algun _built in_ por ejemplo), pero el ramo seguirá existiendo.

- Respondiendo a la segunda, la agregación se ocupa cuando una clase **incluye** una o varias instancias de otra clase (como el ejemplo anterior). Ahora segun tu diagrama, no tendria sentido que sea agregación ya que si Stark deja de existir, entonces LoboGuargo también lo haría, lo que contradice la definición de una agreagación. En este caso (según la imagen) en vez de agregación sería composición. Por otro lado, podría ser como tu dices que LoboGuargo sea una agregación de un Stark pero tendría que ser composición de GOT también.

ATENCIÓN SPOILER!:
Ahora si lo piensas como fue en realidad la serie, LoboGuargo debería ser composición de Stark, ya que por ejemplo cuando murió Robb Stark también murio Grey Wind (lobo de Robb)

Espero quede mas claro :)
