### ISSUE TITLE
funciones en parametros.py

### ISSUE THREAD

**Issue by DmBeta101** [IIC2233/syllabus#300]
Hola! Una duda,

En el archivo parametros.py puedo agregar una función o solo deben ser valores? Por ejemplo quiero hacer una función que me otorgue los valores aleatorios de la criatura.

Quedo atento a la respuesta, gracias!

**Comment by JosefaPaz** [comment]
¡Hola @DmBeta101 !

Tu duda se encuentra publicada en la issue  #278

Spoiler: solo deben ser valores constantes, no funciones, ya que varían según la instancia (criatura) :)
