### ISSUE TITLE
Duda Efecto anti_robo y red_atq

### ISSUE THREAD

**Issue by vvialbarros** [IIC2233/Syllabus#300]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Los efectos de ANTI_ROBO y RED_ATQ son acumulables o uno mismo elige si lo quiere hacer acumulable o no? es decir si tengo mas de 1 Fensaulantro y mas de 1 Aresauce estos efectos deberian ser mayores a que si solo tuviera 1 de cada uno?

**Comment by AndreaVict** [comment]
Holaa, como no se especifica en el enunciado queda a tu criterio si los efectos son acumulables o no. Recuerda mencionar en el README la decisión que tomaste. Mucho éxito en la tarea!!
