### ISSUE TITLE
Reutilizar código de tareas pasadas

### ISSUE THREAD

**Issue by dchahuan** [IIC2233/syllabus#301]
Para los menus podemos reutilizar codigo de nuestra tarea pasada?

**Comment by Dnpoblete** [comment]
Hola, esta pregunta ya fue respondida en la issue #242. Por favor revisar las issues ya respondidas antes de preguntar algo. De todos modos, la respuesta es que si se puede siempre y cuando citen.

Éxito en la tarea 😄
