### ISSUE TITLE
QtDesigner ventana inicial con QWidget o MainWindow

### ISSUE THREAD

**Issue by constanzarojasch** [IIC2233/Syllabus#301]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Queria saber si al crear la ventana inicial de la tarea con QtDesigner es relevante si religo que quiero crear un QWidget o un MainWindow. Gracias!

**Comment by jtlledo** [comment]
Hola @constanzarojasch! No es relevante elegir un tipo de ventana en específico, puedes escoger lo que más te acomode. Te recomiendo investigar un poco sobre las diferencias que tienen las dos, ya que existen algunas cosas que quizás te podrían ser útiles a la hora de construir la ventana. Te dejo el siguiente link donde se habla justamente de esto: [Diferencias entre QMainWindow y QWidget](https://stackoverflow.com/questions/3298792/whats-the-difference-between-qmainwindow-qwidget-and-qdialog)
