### ISSUE TITLE
duda con formas de definir listas

### ISSUE THREAD

**Issue by alterdieg0** [IIC2233/syllabus#301]
Hola, existe una forma en python tal que al momento de definir una lista se indique que solo puede contener elementos de un solo tipo de datos (ie. una lista de solo strings tal que si le intento _appendear_ un `int` entregue error o si al momento de _instanciarla_ si le entrego un `int` también entregue error) intenté buscar en google pero no encontré una respuesta satisfactoria.

🦖

**Comment by alterdieg0** [comment]
Se me ocurre hacer una clase que extienda de `list` pero mi pregunta es si es que se puede hacer solo con `list` o si hay alguna librería o buena práctica para hacerlo

**Comment by kadroguett** [comment]
Hola @alterdieg0, tengo entendido que `list` no tiene un método para hacer esto y revisando la documentación tampoco se encuentra algo como lo que describes (https://docs.python.org/3/tutorial/datastructures.html). 
Por lo que lo más recomendable sería hacer una clase que herede de `list` y crear un método para que solo acepte el tipo de datos que tu prefieras.

**Comment by alterdieg0** [comment]
[aquí](https://stackoverflow.com/a/49628157) encontré que si se puede definir eso de que las listas tengan un solo tipo de datos de una forma solo válida para el _linter_, ya que python lo permite de todas formas

**Comment by kadroguett** [comment]
Hola alterdieg0, no me había fijado en el edit que hiciste agregando los links (no se notifica al correo cuando se editan las issues).
Pero lo que encontraste (`def foo(a: 'str', b: 'str') -> 'str':`) no te permite limitar los inputs sino que solo te permite clarificar los inputs y outputs ideales.
Por otro lado te mostraré una solución que viene como anillo al dedo a la materia de la semana que viene: 
```
class StrList(list):
    def _init_(self, *args, **kwargs):
        super()._init_(self, *args, **kwargs)

    def append(self, value):
        if isinstance(value, str):
            return super().append(value)

        raise TypeError(
            f"El valor {value} es de tipo {type(value)} en vez de <class 'str'>."
            )


str_list = StrList()

str_list.append('a')
str_list.append('b')

print(str_list)

str_list.append(1)

print(str_list)
```
Este código es un ejemplo de como aplicar lo que necesitas, en el cual se crea una clase que hereda de `list` y se sobreescribe el método `append` para que solo acepte un tipo de dato, en caso contrario se levanta una excepción.

**Comment by alterdieg0** [comment]
@kadroguett si, por eso decía que era solo válido para el linter. Gracias por la respuesta 🙌

**Comment by kadroguett** [comment]
De nada, éxito!
