### ISSUE TITLE
parametrizar todos los numeros de mi código

### ISSUE THREAD

**Issue by jfernandez7** [IIC2233/syllabus#301]
Hola! Me gustaría aclarar que tan estricta es la instrucción "su tarea no debe
contener ningún valor numérico en su código, sino que todos ellos deben estar en parametros.py". Los parámetros que nos dicen en el enunciado que son modificables los entiendo, pero que pasa con todos los valores en los setGeometry() y funciones parecidas? También los incluye?
Gracias!

**Comment by Hernan4444** [comment]
Hola,

Esta issue #212 toca el mismo tema que tu. Si tienes dudas, realizar el comentario en esa para tener solo 1 issue que trate del mismo tema.

Saludos ✌️
