### ISSUE TITLE
Modularizar metodos de una clase

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2233/Syllabus#301]
Quería saber como se puede modularizar los métodos de una clase, si es que se puede, principalmente por temas de espacio, ya que llevo muchas lineas de codigo y no es muy agradable a la vista.

**Comment by akaminetzkyp** [comment]
Una clase no debería ser separada en más de un módulo. Si el propósito de esta es demasiado amplio podrías intentar separarla en dos o más clases distintas.

Saludos!
