### ISSUE TITLE
Cambiar frame

### ISSUE THREAD

**Issue by MaximilianWilke** [IIC2233/Syllabus#301]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo un problema para ir cambiando el frame de la planta (girasol), cuando creo una instancia de la planta (que hereda de la clase Planta que hereda de QThread) en su función run le digo que mientras este viva se vaya sumando el valor del frame (siendo esta un property) la cosa es al hacer el emit en el backend del juego (en logica abuela en la funcion crear planta) para decirle al frontend que cree la planta, este no actualiza su frame

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Lord-Kelsier** [comment]
Hola @MaximilianWilke , encontre que tu property la defines asi:
```python
@frame.setter
    def frame(self,value):
        if 2 < value:
            self.__frame
        else:
            self.__frame = value
```

y entiendo que tu idea es que se valla sumando 1 y cuando llegue a 3 vuelva a 1 para hacer el ciclo denuevo

**Comment by MaximilianWilke** [comment]
Si, pero cuando frame es igual a dos no hace nada

**Comment by Lord-Kelsier** [comment]
En los archivos subidos ahora esta el problema no?, porque no estoy viendo donde le haces start al girasol

**Comment by MaximilianWilke** [comment]
Si esta subido el codigo, pero crea que en efecto el start no esta iniciado, igualmente no se cuando se deberia hacer

**Comment by Lord-Kelsier** [comment]
Otra cosa, aun si hicieras start, lo unico que hace el run es cambiar el valor de frame, pero no se lo comunica al frontend, falta una señal ahi y como consejo, crear un label  nuevo no es buena idea, mejor cambia el pixmap de un label ya existente

**Comment by Lord-Kelsier** [comment]
> Si esta subido el codigo, pero crea que en efecto el start no esta iniciado, igualmente no se cuando se deberia hacer

Se debe hacer cuando inicie la ronda

**Comment by MaximilianWilke** [comment]
ok pero el emit que se hace en la funcion crear planta de logica no la conecta?? (en juego.py salen las conexiones)

**Comment by Lord-Kelsier** [comment]
Otra cosa, tienes algo como lo siguiente en crear_planta

```python
planta = Girasol()
self.senal_animar.emit()

```
pero cuando se termina de ejecutar, la funcion esta variablo local muere, por lo que aun si iniciaras el thread este moriria



> ok pero el emit que se hace en la funcion crear planta de logica no la conecta?? (en juego.py salen las conexiones)

Si, pero crear planta se llama al plantar una planta y nunca mas. Te digo que al cambiar de frame solo estas sumando una variable que nadie esta mirando

**Comment by MaximilianWilke** [comment]
Entonces dices que la misma función vaya revisando el frame?? meter un while no haría que no se muriera??

**Comment by Lord-Kelsier** [comment]
un while no evita que muera, puedes probar y ver que te sale lo siguiente: 
![image](https://user-images.githubusercontent.com/69614275/195966892-e3810d67-ed8d-4fea-887c-7ce2fde0816c.png)
y lo que digo es que al updatear el valor del frame se envie una señal que diga "hey cambia de pixmap"

**Comment by MaximilianWilke** [comment]
Se me habia ocurrido que para casos asi, dentro de la clase de Planta se emitiera la señal, pero por como esta hecho el codigo no sabia como conectarlo en el juego.py

**Comment by Lord-Kelsier** [comment]
no se puede, el backend esta generando nuevas plantas constantemente por lo que desde juego no se puede tener acceso a ellas (pues aun no se han creado), lo que deberias hacer ahi es mandar una señal logica_abuela y que esta mande una señal a ventana
