### ISSUE TITLE
Acerca de la sección 7.1.2. Conexión

### ISSUE THREAD

**Issue by martina-abello** [IIC2233/Syllabus#302]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

No me queda claro a qué se refiere esta sección del enunciado. ¿El archivo se crea desde fuera o con código, y para qué sirve? ¿El archivo debe contener algo aparte del host? Porque el "..." me confunde, ¿que más habría que poner? ¿Y el host lo tenemos que elegir nosotros al azar?

**Comment by iespinazac** [comment]
Hola @martina-abello, tú debes crear este archivo .json. En cuanto al contenido, debe tener como mínimo el host. El valor a asignar idealmente que sea "localhost" para evitar problemas en la corrección.
No se menciona qué más debería tener el archivo, pero recuerda que también tienes el parametros.py donde debes almacenar los parámetros pedidos y cualquier otro que veas pertinente agregar.

**Comment by martina-abello** [comment]
¿Y lo de que el cliente debe conectarse al socket abierto por el servidor con los datos en el archivo JSON de la carpeta cliente, es que hay que crear otro archivo JSON ahí, o de alguna manera acceder al del servidor desde el cliente, o...?

**Comment by iespinazac** [comment]
Son dos archivos .json, uno para el servidor y otro para el cliente. Espero que haya quedado claro 😊

**Comment by martina-abello** [comment]
Sí, muchas gracias ^-^
