### ISSUE TITLE
Actualización archivos en github en syllabus

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#302]
Hola
Actualizaron el enunuciado y los archivos csv en la tarea 1.
Entonces eliminé los archivos antiguos que yo tenía en T01 y ahora hago git pull para que se actualize y me sale que estoy "Already up to date" y no se descargan los archivos actualizados aunque esté vacía esa carpeta.

**Comment by JosefaPaz** [comment]
¡Hola @jirarrazaval !

Este error puede deberse a que te encuentras en tu repositorio de la T01 y no en el repositorio del syllabus, ya que los nuevos archivos fueron allí (syllabus) y no en tu repositorio personal.

Quedo atenta!

**Comment by jirarrazaval** [comment]
Noo si estoy en el repositorio del syllabus!

**Comment by jirarrazaval** [comment]
Noo si estoy en el repositorio del syllabus!

**Comment by JosefaPaz** [comment]
Oh que extraño 🤕 

Una solución rápida puede ser eliminar el **syllabus** de tu computador y volver a clonarlo con el comando ```git clone _link del repositorio_```.

Avísame si esto lo soluciona, para buscar más alternativas si no resulta.

**Comment by jirarrazaval** [comment]
Cuando trato de borrar toda la carpeta syllabus no me da permiso como mi computador! Y no la tengo abierta en otra parte, cerre todo y aun no me deja eliminarla

**Comment by JosefaPaz** [comment]
Puede ser que dentro del caché hayan archivos del syllabus aún abiertos, para solucionar esto puedes reiniciar el computador, o si necesitas muy urgente los archivos del syllabus puedes clonar la carpeta en otra parte de tu computadora

**Comment by jirarrazaval** [comment]
La logre borrar! Graciass me funcionó el  git clone :)

**Comment by aljara97** [comment]
Hola @jirarrazaval, por favor no cierres esta issue. Puede ser de utilidad para otro compañero, el equipo docente la cerrará cuando corresponda 🌟 

Éxito 🧙
