### ISSUE TITLE
Duda asignación de atributos tipo y congelamiento

### ISSUE THREAD

**Issue by juanriveraf** [IIC2233/Syllabus#302]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo una duda acerca de la forma de asignar los valores de tipo y congelamiento en la clase plantas. Es necesario pedirlos a la hora de crear la instancia (Planta(tipo, congelamiento, etc)) o puedo yo definirlos predeterminadamente adentro de la clase sin la necesidad de pedirlos? Muchas gracias!

**Comment by juanriveraf** [comment]
Hola, la pregunta al final solo es sobre la forma de asignar el valor de tipo, ya que ahora tengo entendido que si hay que asignar el congelamiento.

**Comment by CatalinaBO** [comment]
Hola! En ningún caso debes pedirle los atributos de una planta al usuario, si es eso a lo que te refieres. 
A cada planta debes asignarle sus atributos según corresponda. Con esto me refiero a que debes asignarle su atributo tipo según el string que se te indique en el archivo plantas.txt (recomiendo ver issue #295), y su atributo congelación según se cumpla o no la condición establecida.
Respondiendo a cómo le asignas los atributos a cada planta, si dentro o fuera de la clase, eso ya es parte de la evaluación!

Ojalá se haya respondido tu pregunta, quedo atenta cualquier cosa!
