### ISSUE TITLE
Calculo Ventaja caso especial

### ISSUE THREAD

**Issue by cristozille** [IIC2233/syllabus#302]
Hola, en cuanto a calcular la ventaja, como se calcularía si todos los competidores son eliminados excepto uno (el ganador). Gracias!

**Comment by jmwielandt** [comment]
Hola!

Como es algo que no está especificado en el enunciado, queda completamente a tu criterio y libertad creativa **siempre y cuando no contradiga otras partes del enunciado o lo dicho en otras issues**, pero **debes** especificarlo en tu readme.

Podrías hacer incluso que aparezca el dragón de la felicidad 🐉 y de un bonus de 1 millón de puntos de experiencia al jugador si te apetece, pero dado el tiempo que queda, te recomiendo pensar en algo que te resulte fácil y rápido de implementar.

Saludos y muchísimo ánimo con lo que queda~ :+1:
