### ISSUE TITLE
Problema con AF4 (para entender mejor la tarea)

### ISSUE THREAD

**Issue by FelipeDiazS** [IIC2233/Syllabus#302]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Estuve revisando y corrigiendo la AF4 para entender mejor los contenidos para la tarea, pero no me funciona. Ya revise el vídeo de la sesión de cierre y no veo ninguna diferencia con mi código. Hable de esto con una ayudante en la sesión de apoyo para la tarea y me dijo que dejara esta issue para que algún ayudante revisara mi código y me diga que está mal. Mi repositorio ya esta al día en esa actividad.

Gracias de antemano :)

**Comment by Christian-Klempau** [comment]
Hola @FelipeDiazS! Estuve revisando tu código y enconté lo siguiente:

En `enviar`, en el Servidor, estás haciendo esto: `self.socket_servidor.sendall(largo_mensaje + mensaje_codificado)`. Si te fijas, el servidor está mandando mensajes a si mismo (El socket servidor). Deberías reemplazarlo por `sock_cliente`. Ojo también que te está faltando reiniciar los eventos de print cuando corresponde.

**Comment by FelipeDiazS** [comment]
> Hola @FelipeDiazS! Estuve revisando tu código y enconté lo siguiente:
> 
> En `enviar`, en el Servidor, estás haciendo esto: `self.socket_servidor.sendall(largo_mensaje + mensaje_codificado)`. Si te fijas, el servidor está mandando mensajes a si mismo (El socket servidor). Deberías reemplazarlo por `sock_cliente`. Ojo también que te está faltando reiniciar los eventos de print cuando corresponde.
> 
> Ahí me cuentas si lo lograste solucionar. Saludos!

Gracias!
Un última cosa, que es eso de evento_prints? no lo encuentro en ninguna parte

**Comment by Christian-Klempau** [comment]
En la línea 19 de cliente.py, se define: `self.evento_prints = threading.Event()`. Es decir, es un evento de Threads, que comparten todos los que tengan acceso a la clase. Básicamente sirve para que dos threads / partes del código impriman cosas a la vez, a modo de desfigurarse la consola. Por lo mismo, cuando se realiza alguna operación I/O, se solicita el evento con `evento.wait()` (esto lo que hace es "pegar" la línea hasta que se desocupe el evento, en la práctica es similar a un `Lock()`), y cuando se desocupa se libera: `evento.clear()`.

Espero haya quedado claro :)

**Comment by FelipeDiazS** [comment]
> En la línea 19 de cliente.py, se define: `self.evento_prints = threading.Event()`. Es decir, es un evento de Threads, que comparten todos los que tengan acceso a la clase. Básicamente sirve para que dos threads / partes del código no impriman cosas a la vez, a modo de desfigurarse la consola. Por lo mismo, cuando se realiza alguna operación I/O, se solicita el evento con `evento.wait()` (esto lo que hace es "pegar" la línea hasta que se desocupe el evento, en la práctica es similar a un `Lock()`), y cuando se desocupa se libera: `evento.clear()`.
> 
> Espero haya quedado claro :)

Gracias! Me quedo claro, pero todavía me tira un error en la línea 79 del servidor

**Comment by Christian-Klempau** [comment]
Qué error te lanza?

**Comment by FelipeDiazS** [comment]
> Qué error te lanza?

Este:
Traceback (most recent call last):
  File "C:\Python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Felipe\Desktop\IIC2233\FelipeDiazS-iic2233-2021-2\Actividades\AF4\servidor\servidor.py", line 62, in thread_escuchar_cliente
    mensaje_recibido = self.recibir_mensaje(socket_cliente)
  File "c:\Users\Felipe\Desktop\IIC2233\FelipeDiazS-iic2233-2021-2\Actividades\AF4\servidor\servidor.py", line 79, in recibir_mensaje
    largo_mensaje_bytes = socket_cliente.recv(4)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto

**Comment by Christian-Klempau** [comment]
Si eliminas todos los `daemon=True` del programa, te funciona?
Al borrar los de cliente, me funcionó.

**Comment by FelipeDiazS** [comment]
> Si eliminas todos los `daemon=True` del programa, te funciona? Al borrar todos los de cliente.py, me funcionó.

Ahí me funcionó, gracias!
