### ISSUE TITLE
Formas de ingresar información

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#302]
Hola!

Quisiera confirmar que la única forma de ingresar datos al programa es leyendo un archivo `.csv` usando `extraer_columna`. En la mayoría de los ejemplos se ingresa información mediante este método, pero hay unos pocos donde se ingresa de la siguiente manera: `['VAR-COEF', [-2, -1, 0, 1, 2]]`.

Saludos!

**Comment by Hernan4444** [comment]
@akaminetzkyp te confirmo que ambas son formas validas de entregar información, solo que RQL está enfocado para trabajar con grandes volúmenes de datos (1.000.000 por ejemplo) pero es totalmente valido entregar una lista con datos mientras corresponda a un `set de datos`.

 En generar cuando ponemos esa lista es para mostrar un ejemplo de forma mas clara pero también puede estar como consulta al momento de evaluar.

Saludos!

**Comment by akaminetzkyp** [comment]
Perfecto, gracias!
