### ISSUE TITLE
Que hacer si tengo todo mal?

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#302]
Me acabo de dar cuenta que tengo todo mal.
Sirve de algo escribir todo en el Readme y tratar de ratonear puntos con cosas chicas (ej rotar las piezas)?

**Comment by cilopez** [comment]
Todo esfuerzo sirve , animo!

**Comment by nfbalbontin** [comment]
1ero que todo, tranquilidad. 
2o, te recomendaría que con lo que te queda de tiempo - que igual es suficiente para poder desarrollar "algo"- revises las issues contestadas y la retroalimentación que dimos con respecto a la Tarea, así te enfocas en lo que buscamos que hagan y puedes sacar tus ideas adelante! 
PD: Escucha Eye Of The Tiger y te apuesto a que la terminas en 5 horas ;)

**Comment by fgbruna** [comment]
Me pasó casi lo mismo,solo que creo que estoy peor :(, al principio tenia puras listas ligadas y estaba recién empezando a calcular  los puntajes(Lo que me complicaba un poco por usar listas),pero desde la entrega del feedback que estoy tratando de aplicar EDD's que me faciliten la pega y sinceramente no he avanzado casi nada y más que nada fue por culpa mía que no manejé bien el tiempo,por esto mismo e independiente de lo que alcance a hacer hoy me gustaría saber si hay algún ayudante que esté dispuest@ a conversar personalmente conmigo respecto a como afrontar especialmente la resolución de las tareas.
TL;DR : Necesito consejos para manejar el tiempo de las tareas :(

**Comment by cilopez** [comment]
@fgbruna Intenta leer el enunciado de una tarea apenas te lo entreguen, luego de esto debes pasar por un proceso de planificación y modelación del código, preguntarte que es lo que esperamos de ti, que cosas se están evaluando y de que forma abordarlas. En este punto sería ideal para ti consultar a los ayudantes acerca de tus ideas y como estas planteando el problema, para quizás recibir un _feed_ más especializado, finalmente con la idea en mente ,viene lo que demora mas tiempo, programar. Intenta enfocarte en realizar avances por pasos, programar por mucho tiempo a veces frustra y termina siendo contraproducente.

Si quieres puedes contactarme a mi mail y agendamos una reunión para conversar más acerca de esto

**Comment by jadiaz6** [comment]
Yaaaa cilopez
