### ISSUE TITLE
Ejericicio propuesto 2.1

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#302]
Hola!!! Estaba intentando hacer este ejercicio y no entiendo qué hay en el diccionario  **kwargs. En los contenidos cuando se instanciaba el objeto de la clase se le daban los parámetros que iban en el diccionario, pero en este ejercicio al instanciar no se da ningún argumento 🤔

**Comment by aaossa** [comment]
¡Hola @denisseleiva ! Si dentro de cada `__init__` imprimes lo que hay en la variable `kwargs`, verás que tiene un diccionario vacío, por lo que no afecta la ejecución del programa 😅 Esto lo puedes comprobar cambiando las invocaciones de `super().__init__(**kwargs)` por `super().__init__()`. Aprovecho de dejar, como recomendación general, que hay que tener ojo con el buen uso de `*args` y `**kwargs` en contexto de multiherencia, por las razones que justo se comentan en #304 . Esto hubiera sido relevante si alguno de los `__init__` (ya sea de `Dragona` o `Burro`) tuviera parámetros. ¡Ojalá te sirva ✨ !

**Comment by denisseleiva** [comment]
Graciass!! 😁
