### ISSUE TITLE
Mejora alcance torres

### ISSUE THREAD

**Issue by Nitsuga69** [IIC2233/syllabus#302]
Tengo entendido que la mejora del alcance de una torre no es radial, sino que solo se mejora el alcance hacia los lados (en MEJORA_ALCANCE casillas) de los caminos que ya están dentro del alcance. Así:
Sin mejora:
<img width="167" alt="Copia de Captura de Pantalla 2019-05-19 a la(s) 11 37 46 a  m" src="https://user-images.githubusercontent.com/48293112/57984646-e541fc00-7a2b-11e9-95c6-6ff52414285e.png">
Con MEJORA_ALCANCE = 2:
<img width="167" alt="Captura de Pantalla 2019-05-19 a la(s) 11 37 46 a  m" src="https://user-images.githubusercontent.com/48293112/57984649-f2f78180-7a2b-11e9-8be1-9d5502ea09ad.png">
Pero hay situaciones mas complejas donde no es muy claro como aplicar la mejora:
<img width="163" alt="Captura de Pantalla 2019-05-19 a la(s) 11 39 04 a  m" src="https://user-images.githubusercontent.com/48293112/57984666-17535e00-7a2c-11e9-9a72-38a1d74eafc4.png">
<img width="165" alt="Captura de Pantalla 2019-05-19 a la(s) 11 38 22 a  m" src="https://user-images.githubusercontent.com/48293112/57984668-1a4e4e80-7a2c-11e9-98bc-da7bd521a6ef.png">
Ambas situaciones sacadas del mapa_bonus. Quizás entendí mal el enunciado, pero no sé cómo aplicar la mejora de alcance en una de estas situaciones. Se puede asumir la mejora de forma radial??

**Comment by gatochico** [comment]
Hola! Tomemos como ejemplo una de tus figuras. Su rango inicial es de esta forma, siendo las partes que marcaste con negro las que realmente afectarán a los enemigos, ya que no pueden salir del camino :

<img width="167" alt="rangoinicial" src="https://user-images.githubusercontent.com/37161120/58032668-19cbbb80-7af1-11e9-9ebd-7be99e6a705a.png">

Ahora, digamos que se compra la mejora de rango, con un valor de MEJORA_ALCANCE = 2, haciendo que el lado del cuadrado que encierra a la torre sea de 5 casillas. El nuevo rango sería este:

<img width="167" alt="rangofinal" src="https://user-images.githubusercontent.com/37161120/58033033-c0b05780-7af1-11e9-9253-ff799875c490.png">

Así que sí, en cierto modo es "radial", pero preferí asegurarme y explicarlo con imágenes 😸 
Exito!

**Comment by Nitsuga69** [comment]
Gracias!!
