### ISSUE TITLE
Como se si tienen la ultima versión de la tarea 00?

### ISSUE THREAD

**Issue by HeraxD19** [IIC2233/syllabus#303]
Conteste la encuesta de tareas atrasadas, y la ultima versión que me aparece que hicieron pull fue la actividad 01 o hacen un ultimo pull para las atrasadas a las 20:15?

**Comment by josefinareyes** [comment]
Hola! Al contestar la encuesta de entregas atrasadas deberías haber especificado el _commit_ a revisar para tu T00 en la parte de "hash completo del commit", esa será la versión que se revisará!
