### ISSUE TITLE
Encoding UTF-8

### ISSUE THREAD

**Issue by CatalinaBO** [IIC2233/Syllabus#303]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, al momento de leer los archivos en la primera función me arroja todo el rato el siguiente error 

<img width="707" alt="Captura de pantalla 2024-05-14 a la(s) 2 17 00 p  m" src="https://github.com/IIC2233/Syllabus/assets/142747886/264af81c-f450-49bd-a000-33a548751f8b">

en los archivos que contienen tildes en sus líneas, por lo que asumí que utf-8 no está reconociendo los caracteres especiales. Para que si se puedan leer los archivos de forma correcta puedo usar el encoding iso-8859-1 ?

**Comment by TomasGMDC** [comment]
Se revisó el tema, y se decidió que deben usar encoding "latin-1".
