### ISSUE TITLE
Desaparecer moneda

### ISSUE THREAD

**Issue by crvargasu** [IIC2233/syllabus#303]
Para revisar si hay que desaparecer una moneda tengo un while que se ejecuta solo cuando el personaje se mueve, es decir, si el personaje se queda quieto no se desaparecen las monedas, dado a que si ejecutaba el while todo el tiempo, python se termina cayendo ( supongo que por sobrecarga de tener que revisar todo el tiempo ) Seria incorrecto hacerlo de esta manera? 

Al fin y al cabo termina siendo lo mismo, dado que si el personaje se mueve se desaparecen las monedas que habian excedido su tiempo de duracion, es solo para que python no se caiga

**Comment by roberto009** [comment]
Hola!
Lamentablemente si es incorrecto lo que estás haciendo, ya que las monedas deben desaparecer independientemente si el personaje se está moviendo o no. Te sugiero que no uses un `while` para revisar, debido a que esto sería una especie de *espera activa* lo cual no recomendable porque consume mucha memoria. 
Eso si, aunque usaras un `while` no debería ser razón para que se caiga tu programa, sino que a medida que aumente la cantidad de monedas tendría que estar mas lento. Trata de revisar bien el error que te arroja.
Te recomiendo que vea las issue #308 , quizá te puede ayudar 😄 
Éxito  con la tarea 💪
