### ISSUE TITLE
Duda sobre usar pyqt en otro archivo

### ISSUE THREAD

**Issue by vicenterodas** [IIC2233/Syllabus#303]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Mi duda es si es correcto y buena/mala practica usar la librería PyQt en otro archivo que no sea el frontend o backend. Por ejemplo crear un archivo que contenga funciones simples, y hacer que una de ellas genere botones por ejemplo. Esto con la idea de modularizar el código. Gracias

**Comment by martinjaraf** [comment]
Hola! 

Si deseas crear otro archivo para modularizar no hay problema, pero ojo que debe estar dentro del frontend (si es que vas a trabajar con botones o elementos de las ventanas) y de hecho es probable que necesites utilizar otro archivo para no excederte del total de líneas. 

Aunque igual ten cuidado porque los botones que se vieron en clases utilizan como referencia `self` de la ventana en el cual se encuentran por lo que podría traer algunos problemas en ese sentido.

**Comment by vicenterodas** [comment]
Gracias, eso si una cosa no me queda clara, a que te refieres cuando dices "ojo que debe estar dentro del frontend" ? 
Por ejemplo, puedo crear dos archivos diferentes para ventana_inicio y ventana_juego y llamarlos frontend_1 y frontend_2 , o como se hace. Gracias

**Comment by martinjaraf** [comment]
Me refiero a que esté dentro de la carpeta frontend. Sobre el nombre del archivo `.py` queda a tu criterio.
