### ISSUE TITLE
Duda aumento y AUMENTO_NUTRIENTE

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#303]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas. En la foto que adjunté del enunciado, el valor que está encerrado en azul es el mismo que el de AUMENTO_NUTRIENTE, es decir, será un número entre 0 y 100? Y si es así, el valor lo tenemos que designar nosotros??
<img width="1197" alt="Captura de pantalla 2024-09-09 a la(s) 1 01 22 p  m" src="https://github.com/user-attachments/assets/7584e2ca-4759-4d9f-9e4d-ade66fe66d22">

**Comment by rodrigoaguilera15** [comment]
Issue #240 lo explica
