### ISSUE TITLE
branches github

### ISSUE THREAD

**Issue by jgespinosa10** [IIC2233/Syllabus#303]
Tengo problema con github, y nose como arreglarlo.

**Comment by jgespinosa10** [comment]
![image](https://user-images.githubusercontent.com/30691527/30470123-db4692cc-99c9-11e7-9a83-180defb8fa2b.png)

**Comment by cilopez** [comment]
Cual sería el problema, ¿quieres borrar una carpeta? o ¿surgió un error en tu consola?

**Comment by jgespinosa10** [comment]
Quiero borrar la carpeta Tarea02

**Comment by cilopez** [comment]
@jgespinosa10 recuerda las reglas del foro, ¿buscaste información antes por tu cuenta en internet?, de ser así , ¿porque no te funciono?
