### ISSUE TITLE
Cambio de archivo Interfaz

### ISSUE THREAD

**Issue by mramirez7** [IIC2233/Syllabus#303]
Hola, hace unos días hice git pull y comencé a hacer la tarea sobre un archivo Interfaz.py de 433 lineas, el programa me habría bien y mostraba los jugadores que le entregaba con mi estructura de datos (iterable).
Recién me percaté que había un nuevo archivo Interfaz.py de 455 lineas, hice git pull pero ahora el programa no corre, me muestra solo los jugadores que no están en la cancha y al pincharlos se me abre una ventana diciendo que python dejó de funcionar y se cierra el programa.
Que puedo hacer?
 Supongo que la correción es sobre el último archivo por lo que se caería, o puedo seguir con el primer archivo de Interfaz? Que diferencia tienen los archivos??

**Comment by behrmann97** [comment]
Hola, los cambios que se hicieron fue que al iniciar, el jugador debe seleccionar de los jugadores que están fuera de cancha, a 11 jugadores. La razón por la que se te podría caer es que al clickear uno de afuera, la GUI llama a la función entra_jugador que debe estar en demo.py, pero que el antiguo demo.py no la tiene.
Revisa que esta función esté en tu demo.py y dime si el error sigue :)
Saludos!

**Comment by mramirez7** [comment]
Eso era, gracias!!!!!
