### ISSUE TITLE
Multiherencia

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#304]
En el ultimo codigo de los contenidos de multiherencia cuando se explica sobre el uso de **kwargs y herencia. No entiendo porque en cada clase independiente si es una sub clase o super clase, en todas se solo un super().__init__(kwargs) . Yo tenía entendido que los super eran solo cuando se pretendía crear una subclase, sin embargo en esta parte se colocan en todas las clases

**Comment by aaossa** [comment]
Hola @enriquemolinare !

En verdad encontré buena tu pregunta, así que espero que logre explicarlo bien para hacerle justicia 👌 Efectivamente, `super()` es para llamar a la implementación de un método de una superclase (recuerda además que todas las clases con las que trabajamos tienen superclase, ya que cualquier clase nueva heredará de `object`).

Ahora, volviendo al ejemplo. ¿Qué pasa si quitamos las llamadas a `super()` de los `__init__` de `Investigador` y `Docente`?

> AttributeError: 'Academico' object has no attribute 'area'

Es como si nunca se hubiera ejecutado `Investigador.__init__`, siendo que sí está `super().__init__` en `Academico`... Aquí es de ayuda el método `mro()`, para ver qué está pasando:

```python
>> Academico.mro()
[<class '__main__.Academico'>, <class '__main__.Docente'>, <class '__main__.Investigador'>, <class 'object'>]
``` 

Recuerda que MRO, *method resolution order*, nos dice en qué orden se resuelven los métodos en Python. Si te fijas, después de `Académico` viene `Docente` y luego `Investigador`. Por lo tanto, al tener `super()` en todas las clases, se ejecutarán en ese mismo orden:

1. `Academico.__init__`
2. `Docente.__init__`
3. `Investigador.__init__`
4. `object.__init__`

Pero al quitar `super()` de `Docente` e `Investigador`, "cortamos" la cadena de ejecución, por lo que no se ejecuta `Investigador.__init__` y no se inicializa el atributo `area`, provocando la excepción que está más arriba.

**¿Cómo se puede solucionar esto?** Agregando `super().__init__()` en `Docente`. Esto permite que se ejecute `Investigador.__init__` y se declare el atributo `area`, ya que Python seguirá el orden del MRO para llamar los métodos que correspondan.

---

**Ojo con una cosa**. Ahora cambiemos la herencia en la clase `Academico` para que el MRO siga otro orden:

```python
class Academico(Investigador, Docente):
```

Con este cambio volveremos a tener un error (con el atributo `departamento`), ya que ahora `Investigador` no tiene la llamada a `super().__init__()` y esta clase estará antes que `Docente` en el MRO. Como a priori no conocemos en qué orden se realizará la herencia, es mejor utilizar `super()` para invocar los métodos de las clases que estén más "arriba" en el MRO. (Sip, el orden en la multiherencia importa).

Por lo tanto, dado que sabemos que estas clases serán utilizadas en un contexto de herencia multiple, se utiliza `super()` en ambas clases para dejar que Python se encargue de llamar a los métodos según el MRO sin preocuparnos en esas clases del MRO. Desde un punto de vista de modelamiento, ese no es el lugar para decidir el orden de llamadas a superclases desde subclases. ¿Dónde sí nos debe importar el orden? Al declarar el orden de las superclases en la declaración de cada clase, como en el último bloque de código.

---

Sé que puede ser confuso, así que si tienes alguna duda (o alguien que esté leyendo 👀 ), pregunta por acá no más 👌 ¡Gracias por la pregunta! ✨

**Comment by sustancia** [comment]
Venía por una duda similar y esto está de pana, muchas gracias n.n
