### ISSUE TITLE
cantidad de lineas frontend

### ISSUE THREAD

**Issue by kmhaller** [IIC2233/syllabus#304]
Hola, me esta pasando que tengo más de 400 lineas en el frontend y no se como separarlas en otros archivos. Intenté de hacer mi clase VentanaInicio en otro archivo, pero no pude, porque tenía que llamar desde los dos archivos al otro, para mostrar la otra al cerrar una. Supongo que el programa no deja hacer eso por programación circular. Como se puede separar? Hay alguna otra forma de hacerlo? Se puede separar una clase en 2 archivos?

**Comment by jaromero6** [comment]
Hola
Si es para evitar programación circular te recomendaría hacer algo de la siguiente forma:
Suponiendo que tienes dos clases de ventana por ejemplo, crearía 2 archivos :  ventana1.py, ventana2.py  . Ahora para evitar la programación circular, o bien importar el módulo 1 en el 2 y vicerversa, haría lo siguiente
en ventana1.py
```
from ventana2 import Ventana2

class Ventana1:
................ Programas normalmente
     def metodo_que_llama_a_ventana2(self): 
                   self.v = Ventana2(self) # La clave está en este self
                   self.hide()
                   self.v.show()
```
Ahora en tu archivo ventana2.py deberías tener algo como:

```
class Ventana2:
     def __init__(self,padre):
             self.mostrar_padre = padre.show # OJO: sin parentesis y solo guardas el método
     
    def metodo_para_volver_a_ventana_1(self):
                self.hide()
               self.mostrar_padre()
```
Con esto te evitas problemas de  programación circular y de los imports, pues a ventana 2 solo le pasas la referencia del método para volver a mostrarlo y no es necesario importar ventana1 en ventana 2.
Espero que te sea de utilidad

**Comment by kmhaller** [comment]
Gracias! De lo anterior me queda el siguiente problema. Solo puedo importar ciertas imágenes para la Ventana1 luego de haber recorrido todas las funciones de la Ventana2. Por esto no puedo definir todos los atributos de la Ventana1 hasta que la Ventana2 termine. Como puedo solucionar esto?
me conviene hacer una señal cuando termina para "iniciar" el otro?

**Comment by jaromero6** [comment]
Efectivamente como dices una forma es con señales, o bien lo otro es hacer que las ventanas se muestren en un orden tal que una vez que consigas toda la información necesaria pases a la siguiente (Y no que la ventana actual necesite información de la que viene). ¿Cuál de las dos te conviene? Va a depender netamente de lo que  tengas y lo que pretendas hacer efectivamente con las ventanas.

**Comment by jaromero6** [comment]
Editado: Tuve un **error** en el código enviado más arriba, lo siento si esto causó problemas, el código que mostré más arriba efectivamente cae en modelación circular. En la issue #275 se habla mejor acerca de la modelación circular si es que el código les causó dudas.
Disculpen las molestias
