### ISSUE TITLE
[4.2.5] Comandos que retornan un Booleano

### ISSUE THREAD

**Issue by jnhasard** [IIC2233/Syllabus#304]
No queda claro si efectivamente retornan un booleano (True o False) como dice el titulo, o si retornan "any" como sale un poco más abajo. 

Gracias

**Comment by acrojas2** [comment]
Yo creo que retornan un booleano, por algo está en la sección de comandos que retornan un booleano.

**Comment by Hernan4444** [comment]
@jnhasard efectivamente retornan un booleano, fue un error de tipeo que terminamos poniendo "any"

Saludos
