### ISSUE TITLE
Verificar errores en la GUI

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#304]
Hola por lo que me eh dado cuenta si hay un error en la GUI el programa se cierra pero en el editor no me sale cual es el error entonces no se como identificarlo

**Comment by Arcoirisky** [comment]
https://github.com/IIC2233/Syllabus-2017-2/issues/598

Esto sirve O:!

**Comment by sjkinast** [comment]
No me quedo claro donde pongo en que parte de demo pongo ese codigo

**Comment by behrmann97** [comment]
Hola, pon ese código en la parte de if __name__ == "__main__" que está al final de demo.py

**Comment by sjkinast** [comment]
Hola no me sirve ese codigo me tira error que sys no esta definido. Podrian mandar asi como en ese issue , como se aplica textualmente para nuestra tarea.

**Comment by behrmann97** [comment]
Es exactamente lo que sale, tienes que hacer import sys al comienzo.

**Comment by sjkinast** [comment]
y que es qtwidgets que tampoco lo reconoce
