### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by stgopau** [IIC2233/syllabus#304]
Hola, ya tengo el archivo .gitignore con el nombre de los archivos que quiero subir, pero al momento de querer subir los archivos, utilizo el comando git status  pero aun asi aparecen en rojo los archivos que están dentro del .gitignore. (tengo un mac)

**Comment by gatochico** [comment]
Hola! Podrías mandar foto de lo que te sale, de como está distribuida la carpeta T01 de tu repositorio, y de tu .gitignore?

**Comment by jmwielandt** [comment]
Hola @stgopau  😄 

Eso se respondió en la issue #43 .

Saludos~
