### ISSUE TITLE
Plantas sigan lanzando proyectiles mientras los zombies se las están comiendo

### ISSUE THREAD

**Issue by isichavezc** [IIC2233/Syllabus#304]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Es que estoy intentando programar que las plantas sigan atacando mientras los zombies las están mordiendo. Intente hacerlo de muchas formas pero mi programa muere. 
Pensé en algo así:

def run(self):
   funcion 1
   funcion 2
Pero al hacer start() solo me corre la primera función y necesito que ambas funciones corran al mismo tiempo. 

También probé:
def run(self):
    funcion 1
def funcion 2(self):

Hacer start() para correr la funcion 1 y correr la funcion 2 cuando la necesite, pero de esta forma el programa se quedaba pegado y moría. 
Mi duda es si estoy haciendo algo mal o si es que hay alguna forma en que pueda correr las dos funciones al mismo tiempo sin que muera el programa. 
Gracias!!

**Comment by drcid98** [comment]
Hola, la mejor forma de hacer lo que dices es que los disparos sucedan de manera independiente a los demás eventos (usando timers por ej), así el hecho de que una planta esté siendo dañada no influye en los disparos de esta.
