### ISSUE TITLE
Que puedo hacer cuando se encalla un barco

### ISSUE THREAD

**Issue by Icarus328** [IIC2233/syllabus#304]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda de que si, a la hora de encallar un barco es necesario hacer que los demás sigan hasta llegar a la posición del barco encallado (Que asumo bloquea el camino) o si puedo congelar totalmente el movimiento de los barcos del canal que estén detrás del barco encallado mientras hayan barcos encallados

**Comment by Emiliax16** [comment]
Hola @Icarus328 ! cuando un barco encalla, todos los de atrás detienen su movimiento, no tienen que detenerse hasta alcanzar al barco encallado. Eso sí, sólo se detienen aquellos que se encuentran por detrás, no los de adelante.

**Comment by imuoz** [comment]
Hola, esto no se contradice con la issue #251 ?

**Comment by Emiliax16** [comment]
Hola, dado que se confirmaron las dos formas distintas de enfrentar esta acción, quedará a criterio del alumno la forma en que aborde la función de encallar. Es decir, si un barco encalla se puede:

1.  detener toda la flota detrás del barco encallado
2.  avanzar la flota detrás de barco encallado hasta la posición del mismo.

**Importante**: el supuesto que se escoja debe ser especificado en el **README**.

Estoy atenta a cualquier otra duda.
