### ISSUE TITLE
Duda de mi codigo AF4

### ISSUE THREAD

**Issue by jahernandez2** [IIC2233/Syllabus#304]
Hola, al momento de intentar ejecutar main.py del servidor en la AF4, me tira ese error, a lo cual voy a la linea que me marca el error y tengo lo mismo que está escrito en el power. No se si me pueden ayudar con eso, en mi repositorio está un poco distinto porque la entregue menos completa de lo que llevo (si prefieren que lo actualize para que me puedan ayudar, me dicen). 
Saludos.

![image](https://user-images.githubusercontent.com/62116520/144122620-e5cacfba-b235-4a9e-be13-1f63be90b22b.png)

**Comment by Christian-Klempau** [comment]
Hola @jahernandez2!
Puedes subir el código actualizado a tu repositorio, no hay problema :)

**Comment by jahernandez2** [comment]
Listo, perdón la demora

**Comment by Christian-Klempau** [comment]
Yap, leí tu código y algunos problemas que encontré y cambié, a modo de que tu actividad funcionara:

Primero, tenías un _typo_ y hacías referencia a `self.socket_client` en vez de `self.socket_cliente` (nota la **e** al final). Segundo, en el servidor, al escuchar el cliente, sólo debes mandar respuesta en caso que lo que retorne manejar comando sí sea válido. Por otro lado, en el cliente, si no tienes respuesta al escuchar, debes salir. También te faltó manejar el comando desde el cliente. Por último, el thread de escuchar en el cliente **no** debe ser daemon, sino el programa puede terminar antes de que se establezca la conexión correctamente.
Saludos, espero te sirva! :D

**Comment by jahernandez2** [comment]
Muchas gracias, pero me sigue sin correr. Perdón la insistencia y la demora, pero he seguido con algunas dudas de esta materia. Te mando foto en  particular de lo que ocurre cuando corro el main.py del cliente. 
![image](https://user-images.githubusercontent.com/62116520/145127566-b2b7e91e-0531-400b-9b4e-b6f6f0bffcc1.png)

Cuando corro el main.py d servidor, me corre al mencionarme que aprete Ctrl+C, se cae y no se que hacer. No se que es lo que me debería correr en esta parte la verdad. 
![image](https://user-images.githubusercontent.com/62116520/145127737-a65ed8a5-f8ff-43e7-86a0-4dd0792192ba.png)

**Comment by Christian-Klempau** [comment]
Yap, algunas cosas que puedo notar:
Primero, el error del cliente no es de sockets, sino porque python no está encontrando el archivo. Fíjate que estés manejando el path al mismo de manera correcta (veo que tiene dos `\\` y creo que no es correcto). Probablemente sea eso (en ese caso te recomiendo trabajar con `os.path.join(...)`). Si no es eso, entonces es un problema de **desde donde** estás ejecutando el código o del path mismo.

Respecto al error del servidor: lo que pasa es que estás haciendo accept a algo que no es una instancia socket. De hecho, por lo que veo es un método. Ojo ahí.

El flujo en general debiera ser el siguiente: iniciar servidor, hasta que veas que está aceptando conexiones. Luego, inicias el cliente, y este se conecta. Puedes probar con un servidor/cliente simple que se manden un mensaje, para que veas que está funcionando.

Saludos y ánimo! :D

**Comment by jahernandez2** [comment]
Muchas gracias. Pero lo primero significa que el código que venía en la actividad está mal? Ya que es el código que se supone no había que modificar...

**Comment by Christian-Klempau** [comment]
Pensé que esa parte la habías hecho tú 😅
No, no significa que el código de la actividad esté mal. Significa que o no tienes el archivo en tu computador y por eso no se encuentra, o la ejecución desde consola está incorrecta / desde un path incorrecto.
