### ISSUE TITLE
Duda temperatura jardin y helada

### ISSUE THREAD

**Issue by JoseMonterod** [IIC2233/Syllabus#304]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda ya que en el enunciado se menciona que la temperatura del jardin debe estar entre -5 y 25. Ahora bien, para el evento helada esta debe bajar más aun? o la temperatura del jardin siempre deberá estar en el rango mencionado sin importar el evento y el dia.

**Comment by AndreaVict** [comment]
Holaa, efectivamente la temperatura del jardín debe estar entre los valores de -5 y 25 °C sin importar el evento y el día. Mucho éxito en la tarea!!
