### ISSUE TITLE
.gitignore: no subir archivos de la carpeta gui o no subir la carpeta gui?

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#304]
Hola! En el enunciado se refieren a que no subamos la carpeta gui o que no subamos los archivos de la carpeta gui (y por ende, sí subir la carpeta gui pero dejandola vacía)? 
Si es el segundo caso, me pasa que al decirle a mi archivo .gitignore que no suba los contenidos de la carpeta gui, al hacer push tampoco me sube la carpeta gui. Debiera esperar a que suba una carpeta vacía o está bien lo que está pasando?

**Comment by cilopez** [comment]
Como lo realizaste en tu repositorio está bien, no es necesario agregar una carpeta vacía
