### ISSUE TITLE
Uso de for en carga de datos y consultas

### ISSUE THREAD

**Issue by faresdababneh** [IIC2233/Syllabus#304]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Tengo dos dudas:

1) Al momento de cargar los datos, leí en las issues de librerías permiidas que si se puede en esta parte de la tarea utilzar split( ), list(), strip(), y un ciclo for(). ¿Esto significa que el disclaimer del enunciado solo aplica para la sección de consultas? Entonces si podría crear listas, llenarlas, usar comando como los mencionados y usar ciclo for en la parte de cargar datos. 

2) En en el apartado de Consultas, cada vez que nos piden que creemos una función que retorne un generador, ¿Es válido utilizar un for() que recorra mi objeto de tipo map, filter o reduce y que vaya haciendo 'yield'? Lo pregunto porque no me queda claro si es válido por enunciado. 

Gracias!

**Comment by tcapom** [comment]
Hola @faresdababneh !

1. Efectivamente, el disclaimer que está al final de la parte 3 del enunciado, la programación funcional es exigida solamente en la sección de consultas. Para corroborar, están estos comentarios en la issue #298
![image](https://github.com/IIC2233/Syllabus/assets/141950883/5808ec12-f6aa-44ac-8948-d19c5820bdbd)


2. Si es que ocupas un ciclo (for o while) autocontenido dentro de una función generadora (que ocupe yield) no hay problema! Esta permisividad está indicada en el disclaimer.

**Comment by elneitans** [comment]
Una pregunta respecto a esto mismo. ¿Puede haber solo un "for" dentro de las funciones generadoras, siendo el que provee el elemento del yield (yield i)? O puede haber más de uno?

**Comment by tcapom** [comment]
Hola @elneitans !

Sí se puede usar más de un bucle dentro de una función generadora
