### ISSUE TITLE
Uso de .keys() & .values()

### ISSUE THREAD

**Issue by Bennjapa** [IIC2233/Syllabus#305]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!, tengo una duda y en parte querer confirmar, por miedo a realizar algo no permitido, si quiero crear una estructura de datos en una de las funciones y esta la hago con un diccionario por compresión, de forma que luego hago uso de metodos como .keys(), .values(). Eso estaria permitido o crear cualquier tipo de estructura de datos esta prohibida?

**Comment by tcapom** [comment]
Hola @Bennjapa !

Estoy esperando una confirmación, así que toma la información de ahora con un grano de sal. 
Las estructuras de datos que retornan `.keys()` y `.values()` son de tipo `dict_items`, las cuales no están explícitamente prohibidas en el enunciado, así que sí se debería poder usar.

Actualizaré la respuesta en caso de que me haya equivocado

**Comment by Bennjapa** [comment]
Hola, @tcapom!

Entonces, eso implica que esta permitido crear diccionarios por compresión a gusto?, que no lo terminé de entender del "Disclaimer"

**Comment by tcapom** [comment]
Hola @Bennjapa !

Puedes construir a gusto diccionarios y listas mientras estas estén hechas por compresión.

**Comment by Bennjapa** [comment]
Muchas gracias :)

**Comment by faresdababneh** [comment]
Hola, sumandome a la pregunta, ¿Se puede utilizar defaultdict() en las consultas? Lo uso como inicializador de un reduce(). Gracias!

**Comment by tcapom** [comment]
Hola @faresdababneh !

Para `defaultdict()` y para cualquier estructura de datos, no existe problema instanciarlo vacío siempre y cuando sea inicializador de `reduce()`

**Comment by VicenteIgnacioSotoGonzalez** [comment]
> Hola @faresdababneh !
> 
> Para `defaultdict()` y para cualquier estructura de datos, no existe problema instanciarlo vacío siempre y cuando sea inicializador de `reduce()`

Hola, respecto de este comentario, se pueden instanciar datos variables como var_1 = 0, var_2 = "" para que se vayan actualizando a medida que avanza el codigo? Esto en el contexto de las consultas.

**Comment by VicenteIgnacioSotoGonzalez** [comment]
> Hola @VicenteIgnacioSotoGonzalez !
> 
> Claro, toda variable que no sea estructuras de datos (str, int, bool, etc.) no tiene ningún tipo de restricción y puedes crear cuantas quieras.

Perfecto, muchas gracias por la respuesta!

**Comment by M4TI4D4CZ** [comment]
Hola, y se puede usar el metodo items()?
