### ISSUE TITLE
No me funciona el .gitignore

### ISSUE THREAD

**Issue by GitCross135** [IIC2233/Syllabus#305]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo mi gitignore pero no está ignorando todas las carpetas que quiero ni los archivos dentro de las carpetas, ya no se qué hacer. He probado ponendo la ruta relativa, dando vuelta los slashes y nada.

![image](https://github.com/IIC2233/Syllabus/assets/130419134/af7ac6a2-ce90-473e-b661-4150e8d393f6)

**Comment by gaspar-mr05** [comment]
tengo el mismo problema...

**Comment by Martinaurrutia** [comment]
Si es que realizaste un push de uno de los archivos, el gitignore no funcionará debido a que los archivos ya estarán dentro de git, por lo que si ese es el caso, debes eliminar los archivos de git, hacer el .gitignore y luego poner los archivo a ignorar en tu carpeta, de esa forma el gitignore los reconocerá y los ignorará al hacer nuevos push. Puedes revisar la Issue #205 dónde se explica esto también.
