### ISSUE TITLE
Instalar PyQt5 macOS Sierra

### ISSUE THREAD

**Issue by fernddevidts** [IIC2233/Syllabus#305]
Hola,

Traté de instalar pyqt5 con Homebrew y me sale que se instaló correctamente, sin embargo, cuando lo trato de importar en Python me dice que no existe ese archivo en el directorio. 
Me fijé de instalarlo con python 3.5
Después traté de instalarlo con pip3 pero me da un error de que no tengo permiso para realizar esas operaciones.
También traté de hacerlo descargando los archivos tar y ejecutando el configure.py pero me dice que tengo que usar el comando --qmake y no sé qué ponerle de argumentos a ésto.

Gracias por la ayuda!

**Comment by acrojas2** [comment]
Si usas pycharm, también lo instalé con pip, luego de eso,  al menos yo tuve que hacer lo siguiente:
ingresar a preferences -> Project interpreter y en el lado derecho de la ventana buscas un signo +, lo pinchas y te debería aparecer esto:
<img width="925" alt="captura de pantalla 2017-04-25 a las 6 53 10 p m" src="https://cloud.githubusercontent.com/assets/26121354/25409527/ab12f092-29e8-11e7-904a-5bb8f9b11281.png">
Acá buscas PyQt5 y apretas Install Package. 
Espero haberte ayudado.
Saludos!

**Comment by fernddevidts** [comment]
No funciona :( me tira el mismo error que cuando corro "pip3 install pyqt5" en el terminal:
PermissionError: [Errno 1] Operation not permitted

**Comment by iqacevedo** [comment]
Probaste con `python3.5 -m pip install pyqt5`?
