### ISSUE TITLE
Diagrama GOT (S3 1.1)

### ISSUE THREAD

**Issue by daniela-carreno** [IIC2233/syllabus#305]
Hola,
En el ejercicio propuesto 1.1 de la semana 3, no me quedan claras algunas relaciones. Voy a listar mi lógica y añadir la pregunta donde tengo dudas:
-  Got esta compuesto de humanos
- Los Stark son humanos (agregación)
- Los Guardias de la noche son humanos (agregación)
- Los stark pueden o no tener un lobo huargo  (agregación)
- John Snow es Stark (herencia)
- Ned Stark es Rey del Norte  (herencia)

![image](https://user-images.githubusercontent.com/69604571/91755327-ece1d180-eb98-11ea-8148-e4bdf4b2ee34.png)

1. ¿Por qué Stark no hereda de Humano en el Enunciado?
2. ¿Por qué Guardia de la noche no hereda de Humano en el Enunciado?
3.  ¿por qué Rey del Norte tiene de clase madre Humano y Stark? si Stark ya es Humano no sería redundante llamar a Humano?  Ya que esto es lo que pasa con Ned Stark que solo llama a Rey del Norte y no tiene que especificar que es Stark ni Humano.
4.  Similar con John Snow, por qué se debe especificar que es Humano, y Stark/Guardia? si tanto Stark como Guardia son tipos de Humano.

*nota* la issue #300 también hace referencia al diagrama de GoT, pero como hace otras preguntas hice una issue aparte

**Comment by Juampisaez** [comment]
Hola @daniela-carreno 
Respondiendo a tus dudas y a tu diagrama, podría ser como tu dices y estaría correcto. Sin embargo, te piden que **hagas un diagrama según el codigo** que parece justo abajo, por lo que tu diagrama no estaría correcto.
Mi consejo es que te fijes primero cuales son las clases que hereda cada subclase, luego cuales clases son instanciadas dentro de la clase (composición), luego ver cuales instancias pueden ser agregadas a otra clase.

Espero conteste a tus dudas, quedo atento.

**Comment by daniela-carreno** [comment]
Okis 😊 muchas gracias

**Comment by Juampisaez** [comment]
Claro, podrías hacerlo siempre y cuando hayas instanciado la clase NedStark y también hayas colocado el super().__init__() dentro de la clase NedStark

**Comment by daniela-carreno** [comment]
🤔 En ese caso al instanciar a NedStark se escribe: 
super().__init__ (atributosHumano, atributosStark, atributosReyNorte)
Self.atributoNed1 = atributo1

O debería instanciar por cada clase padre:
Humano. __init__ (atributosHumano)
Stark. __init__ (atributosStark)
ReyNorte. __init__ (atributosReyNorte)
Self.atributoNed1 = atributo1

**Comment by Juampisaez** [comment]
OJO que NedStark hereda solamente de Rey del Norte, por lo que bastaria hacer:
```
class NedStark(ReyDelNorte):

    def __init__(self):
        super().__init__(atributos de ReyDelNorte)
        self.familia = None # list[Humanos]
        self.honor = None # int
```

En el caso de Rey del Norte, sería como dices tu:
```
class ReyDelNorte(Humano, Stark):

    def __init__(self):
        Humano.__init__(self, atributos Humano)
        Stark.__init__(self, atributos Stark)
        self.poder = None # int
        self.espada_ice = None # bool
```

Desconozco si existe otra forma para ambas, te recomiendo igual investigar sobre multiherencia y revisar los contenidos de la semana 3.

Espero te sirva :)

**Comment by daniela-carreno** [comment]
Gracias 😊
