### ISSUE TITLE
¿Es relevante lo impreso en la terminal?

### ISSUE THREAD

**Issue by Fhguinez** [IIC2233/Syllabus#305]
Mi duda nace porque complemento varias cosas de la interfaz con mensajes explicativos en la terminal. Pero cuando uso gui.rotate_piece() (sin necesariamente estar presionando el botón rotar) no puedo evitar que la función me imprima "Derecha".

Adjunto una captura de los print generados por usar gui.rotate_piece() en mi método encargado de hacer plot twist.
![captura de pantalla 2017-09-15 a la s 13 17 07](https://user-images.githubusercontent.com/26127246/30492825-3dcc5186-9a18-11e7-8f3c-825ed5bf2909.png)

**Comment by cilopez** [comment]
La verdad es que no es tan importante, pero puedes tener descuentos en ese ítem si tu corrector lo considera prudente.

**Comment by Fhguinez** [comment]
Pero no es algo que pueda evitar, porque no puedo entrar a la carpeta gui y modificar rotate_piece()

**Comment by naazocar** [comment]
Pero que te imprima "Derecha" no es por el print(orientacion) en retroceder() en el demo?
