### ISSUE TITLE
Contradicción de PONDERADOR_DIFICULTAD

### ISSUE THREAD

**Issue by Raibruh** [IIC2233/syllabus#305]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Para las siguientes fórmulas me surge una duda con respecto a PONDERAROR_DIFICULTAD, ya que para la primera fórmula, que corresponde a la probabilidad de encallar, lo normal sería que PONDERADOR_AVANZADO sea más grande que PONDERADOR_PRINCIPIANTE, ya que si el canal es de dificultad avanzada debería ser más probable que sus barcos encallen.
![formula1](https://user-images.githubusercontent.com/80918062/115920867-c4208c00-a448-11eb-9b46-6d2a5dcea08d.png)
Sin embargo, para esta segunda fórmula que corresponde a la probabilidad de éxito de desencallar el barco no tendría sentido que un barco que se encuentra en el canal de tipo avanzado tenga mayor probabilidad de éxito que uno que se encuentre en un canal de tipo principiante
![formula2](https://user-images.githubusercontent.com/80918062/115920878-c84ca980-a448-11eb-846e-cae19767a5e6.png)

**Comment by Emiliax16** [comment]
Hola, como tend_encallar, dif_canal, PROB_BASE_DESENCALLAR y ponderador_dificultad son todos parámetros que cada alumno decide (en base a diferentes estimaciones y pruebas), lo que dices puede variar. 
En tu caso, con los valores que les otorgaste a los parámetros, te da una contradicción. No es necesario que lo veas como una contradicción, puedes pensar en ejemplos donde ciertas disciplinas tienen como _rango_1_ el más difícil de conseguir y _rango 5_, el más básico. 

Por lo que si defines eso en tu README, le puedes dar un valor menor al PONDERADOR_AVANZADO que el PONDERADOR_PRINCIPIANTE, lo importante es que seas consistente con tus supuestos y los especifiques.

Espero que haya quedado más claro, quedo atenta!

**Comment by Raibruh** [comment]
Mi duda surge con respecto a las dos ecuaciones que salen ahí, ya que según enunciado dif_canal tomará el valor de PONDERADOR_AVANZADO o PONDERADOR_PRINCIPIANTE, por lo tanto siento que son las fórmulas las que se contradicen, ya que lo lógico sería el que el ponderador haga una de las siguientes:
1. Para dificultad avanzada **aumente el valor de la probabilidad de encallar y disminuya el valor de la probabilidad de desencallar**, ya que debería ser más probable encallar y más difícil desencallar en un canal difícil de cruzar .
2. Para dificultad principiante **disminuya el valor de la probabilidad de encallar y aumente el valor de la probabilidad de desencallar**, ya que debería ser menos probable encallar y más fácil desencallar en un canal difícil de cruzar .
Puedo entonces modificar el valor del parámetro ponderador antes de utilizarlo en las fórmulas y especificarlo en el README?

**Comment by Emiliax16** [comment]
Entiendo tu lógica y es consistente con el contexto de la tarea. En este caso, podrías enfocarte en que la probabilidad de encallar en la dificultad avanzada sea mayor a la probabilidad de encallar en principiante, sin cuidar que la probabilidad de desencallar no se adecuen del todo al contexto. Eso si, yo lo diseñaría de tal forma sea más probable desencallar que encallar, pero eso va en los supuestos de cada alumno.
Respecto a lo de los parámetros, estos deben ser constantes para todo el flujo, no puedes cambiar el valor dependiendo de la fórmula que vas a usar ! Si sigues con dudas, coméntamelo!. Recuerda especificar todo esto en tu README.

**Comment by fernandosmither** [comment]
> Entiendo tu lógica y es consistente con el contexto de la tarea. En este caso, podrías enfocarte en que la probabilidad de encallar en la dificultad avanzada sea mayor a la probabilidad de encallar en principiante, sin cuidar que la probabilidad de desencallar no se adecuen del todo al contexto. Eso si, yo lo diseñaría de tal forma sea más probable desencallar que encallar, pero eso va en los supuestos de cada alumno.
> Respecto a lo de los parámetros, estos deben ser constantes para todo el flujo, no puedes cambiar el valor dependiendo de la fórmula que vas a usar ! Si sigues con dudas, coméntamelo!. Recuerda especificar todo esto en tu README.

Tenía exactamente la misma duda que mi compañero, finalmente un jugador que juegue en la dificultad difícil tendrá más fácil el desencallar un barco, que uno que lo juegue en fácil.

Ya que esto es por enunciado, y más que sea mil porciento lógico, lo importante es que nos adecuemos a lo que nos piden, asumo que no habrá algún tipo de descuento, por el hecho de que sea más fácil una accion en la dificultad difícil, verdad?

**Comment by Emiliax16** [comment]
@fernandosmither correcto, mientras sea consistente con los datos del enunciado y lo especifiquen en el README, no habrá ningún descuento asociado a esa acción !

Saludos.
