### ISSUE TITLE
Simular día

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#305]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas. Tengo una duda respecto a la imagen que adjunté del enunciado. ¿Debemos crear el menú tal que acepte simular varios días de una? ¿o podemos crear un menú tal que se simule solo un día apenas se elija el evento, es decir se elige un evento y se simula un día, luego se elige otro evento y se simula otro día?
<img width="1192" alt="Captura de pantalla 2024-09-09 a la(s) 3 45 48 p  m" src="https://github.com/user-attachments/assets/879f3dbd-4599-4e3a-924c-0cbe68d51d37">

**Comment by R3Y3X** [comment]
Hola espero que estés bien 😄. Como mencionas en la segunda pregunta, al seleccionar la opción de pasar día, se escoge un evento en base a la probabilidad de que ocurra (también puede pasar que no haya evento) y luego con ese evento activo se realiza la simulación y se vuelve al menú de inicio para decidir que opción tomar, como por ejemplo ir al Jardín y escoger la opción de regar para que la vida de tus plantas se recuperen y puedan combatir mejor para el próximo Pasar día. Éxito en la tarea ⚡
