### ISSUE TITLE
Librerías disponibles T01

### ISSUE THREAD

**Issue by AAVP** [IIC2233/syllabus#305]
Tengo permitido usar la librería sys en la tarea 2? Y qué otras librerías están disponibles? o no tengo permitido usar ninguna?

**Comment by Dnpoblete** [comment]
Hola @AAVP supongo que te refieres a la T01, que es en la que estamos ahora, para lo cual te recomiendo revisar en la issue #240 que fue creada para consultar por las librerías permitidas y no permitidas y en el caso de que no esté que preguntes ahí.

Éxito con la tarea! ✨
