### ISSUE TITLE
Problema git push

### ISSUE THREAD

**Issue by agustindesolminihac** [IIC2233/syllabus#305]
Hola al intentar hacer git push me aparece esto: git push
To https://github.com/IIC2233/agustindesolminihac-iic2233-2019-2.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/IIC2233/agustindesolminihac-iic2233-2019-2.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Y no me deja subirlo. No se por qué puede ser.

**Comment by gatochico** [comment]
Hola! Intenta lo siguiente:

- **GUARDA EN OTRA CARPETA DE TU COMPUTADOR UNA COPIA DE TU TAREA ACTUAL** (para evitar cualquier pérdida :warning:)
- En tu repo privado, haz `git pull` y `git status`. Si git status te dice que todo está _up to date_, haz `git push`. 
- Si funcionó, revisa bien tu repositorio remoto para que confirmes que todos tus archivos están ahí y tu tarea se subió correctamente.
- Si la version subida a tu repo remoto no es la versión que quieres entregar, reemplazala por la copia que hiciste en tu computadora y subela de nuevo.

Cuentanos como te va!

**Comment by jfuentesg26** [comment]
No me funciona

**Comment by jfuentesg26** [comment]
es que git status dice que no esta todo up date

**Comment by gatochico** [comment]
Clona tu repositorio de nuevo, y agregale tu copia de la t01, y pushea de nuevo!
