### ISSUE TITLE
reconocer distintas ciudades al calcular el puntaje

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#306]
![problema fichas](https://user-images.githubusercontent.com/30670535/30494772-d19d14e8-9a1f-11e7-9da8-01e159de8e4d.png)

Estoy haciendo la parte de calcular el puntaje de cada usuario y no sé qué hacer en casos como el de la foto, en qué no es posible saber si se trata de dos ciudades distintas como en el caso de la izquierda, o una misma ciudad como en el caso de la derecha. Las fichas de al medio no son posibles de diferenciar por sus bordes; sólo pueden diferenciarse por sus tipos. ¿Por lo tanto debería ver todos los casos en que tengo este problema y que mi programa tenga guardadas las combinaciones de tipos de fichas en que ocurre eso para que sepa qué puntaje asignar? ¿o se puede hacer un supuesto que simplifique el problema?

**Comment by cilopez** [comment]
Los nombres de las piezas son únicos, por lo que deberías poder reconocer estos casos, si el tiempo ya no está a tu favor, menciona en tu _readme_ si simplificaste estos casos

**Comment by mjgutierrez1** [comment]
ok gracias
