### ISSUE TITLE
Tiempo demora en extraer columna

### ISSUE THREAD

**Issue by JoseValencia125** [IIC2233/Syllabus#306]
¿cuanto tiempo se considera "quedarse pegado"? ¿menos de 10 segundos o debe ser inmediata la respuesta a esta consulta?

**Comment by Hernan4444** [comment]
@JoseValencia125 menos de 10 está dentro del tiempo considerable, si revisas los resultados.txt, la consulta 12 se demoro casi 10 segundos puesto que debía sacar la desviación estándar de ambos set de datos (500.000 por set). Si llegara a demorarse 1 minuto en algo que nosotros sabemos que se demora 5 segundos o 5 minutos en algo que máximo era 1 minuto, ahí estamos en problemas :c

Saludos!

**Comment by JoseValencia125** [comment]
Muchas gracias!

**Comment by fdominguezclaro** [comment]
Tengo un problema con respecto a esta función. 
Dentro de extraer_columna, abro el archivo con with open(....), y esta función me retorna un generador con la columna pedida. 

Pero al momento de usar dicho generador me dice que el archivo ya se uso... No puedo retornar una lista por compresión?

**Comment by Hernan4444** [comment]
@fdominguezclaro tienes permitido usar listas por compresión para lo que quieras pero recuerda que podemos pedirte que saques la columna de un archivo con 1.000.000, 5.000.000 o muchos mas datos y ahí tendrás problemas. Uno de los desafíos de la tarea es como solucionar de forma optima este problema del generador.

Saludos!!
