### ISSUE TITLE
QtDesigner: Dudas y más

### ISSUE THREAD

**Issue by ggmirandac** [IIC2233/Syllabus#306]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo un par de dudas con el funcionamiento de QtDesigner, y también un poco de como hacer buen uso de esta herramienta.

En primera instancia, estaba probando realizar la ventana de inicio con QtDesigner y agregar los fondos y logos de la misma ventana desde la misma aplicación. El problema con este es que python no lee los archivos .rc (según leí en este [issue](https://stackoverflow.com/questions/55972743/qt-designer-error-with-python-throwing-error-when-i-try-to-load-image) de StackOverflow) y hay que cambiar el archivo .rc a un archivo .py. Mi problema va a que hay que unas líneas del código del mismo archivo .ui generado por QtDesigner (como se menciona en el siguiente [issue](https://gis.stackexchange.com/questions/139625/qgis-plugin-problems-importing-resources-resources-rc-file-plugin-doesnt-l) de StackExchange). De esta forma, al cambiar el archivo .ui, se hace complicado poder actualizar el archivo que estamos usando en QtDesigner de nuevo, debido al cambio manual del archivo .ui. 

¿Hay alguna forma más sencilla de hacer esto, o se recomienda que se incluyan las imágenes a los labels correspondientes directamente desde el código del front-end correspondiente?

Sin otro particular, me despido.

Saludos,

**Comment by Hernan4444** [comment]
Hola @ggmirandac 

En base a la experiencia que tengo utilizando QtDesigner, no conozco otro método (busqué por un buen tiempo, y no encontré nada). Por lo tanto, solo quedaría hacer eso de transformar .rc a .py, o bien la opción que mejor recomiendo, hacer eso directamente desde el código de front-end correspondiente. Con los contenidos del curso + experiencia 3 y 4, esto último no debería ser muy complicado 😄 

Saludosヾ(＾-＾)ノ

ps:si alguien encontró una forma, le agradecería compartirla porque estuve un buen tiempo con algunos alumnos buscando otra opción, y no se logró encontrar nada 😞.
