### ISSUE TITLE
Duda produccion soles

### ISSUE THREAD

**Issue by mrebolledo03** [IIC2233/Syllabus#306]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En la tarea sale que la producción de soles nunca puede ser negativa, pero que pasa si la temperatura es negativa? le cambio el signo simplemente?

**Comment by CatalinaBO** [comment]
Hola! Efectivamente, la producción de soles no puede ser menor a cero. Como no se menciona en el enunciado, queda a tu elección cómo tratar la producción de soles para los casos en que la temperatura es negativa, pero debes explicitarlo en el README. 

Mucho éxito en la tarea!

**Comment by mrebolledo03** [comment]
Graciass
