### ISSUE TITLE
QTimer se activa pero la función conectada no se ejecuta

### ISSUE THREAD

**Issue by pablobustose** [IIC2233/Syllabus#306]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo un problema con un qtimer en mi código. En lógica_juego creo una instancia de Guisante, en donde esta crea y conecta su qtimer dentro de su init. Pero al momento de ejecución del timer, este aparece como creado (isActive retorna True) pero la función conectada no se ejecuta junto a este. Me podrían ayudar por favor? Ya que con este problema no puedo seguir avanzando con la tarea debido a que las funciones que me faltan son dependientes a esto. Gracias!

**Comment by iespinazac** [comment]
Hola @pablobustose!
¿Podrías hacer un push con los últimos avances de tu tarea para poder ayudarte?
Avísame por aquí mismo cuando esté listo 😉

**Comment by pablobustose** [comment]
Hola! Ya lo hice al momento de realizar el issue

**Comment by iespinazac** [comment]
Súper, ahora mismo lo reviso

**Comment by iespinazac** [comment]
Hola de nuevo @pablobustose!
Al instanciar el Guisante, conectas la señal pero no haces el emit!
Dime si encuentras el error y lo logras solucionar 😸 
Quedo atenta

**Comment by pablobustose** [comment]
Si, lo que pasa es que el qtimer de Guisante está conectado a la función que realiza el emit, pero como la función no es ejecutada, la señal tampoco es emitida. Eso es lo que no entiendo, que la función conectada del qtimer no se ejecute aun cuando el qtimer está funcionando

**Comment by iespinazac** [comment]
Ya pillé el problema. 
Al instanciar los guisantes, lo haces de manera local. Lo que ocurrirá es que luego de ejecutar se eliminará el QTimer. Debes guardar esas instancias locales en alguna parte, un self.guisantes, por ejemplo.
Ahora sí debería funcionar 😅
