### ISSUE TITLE
Implementación obligatoria del método __iter__

### ISSUE THREAD

**Issue by Regenschrim** [IIC2233/Syllabus#306]
El título es bastante explicativo, pero quería acotar que la iteración sobre mis lista funciona solo con los métodos `__getitem__,` `__setitem__` y `__len__;` por esta misma razón quería saber si es obligatorio la implementación del método `__iter__.`

Gracias!!!

**Comment by FernandoPieressa** [comment]
Hola!

El método `__iter__` se tiene que implementar de manera obligatoria al igual que todos los métodos solicitados en el enunciado.

Saldudos!
