### ISSUE TITLE
Ejercicio 2.2 - Duda con multiherencia y atributos "compartidos"

### ISSUE THREAD

**Issue by margavicunas** [IIC2233/syllabus#306]
Hola!
Hice el ejercicio 2.2 y ahora estoy intentando hacerlo de forma correcta (con el uso de **kwargs) pero me entró la duda de qué pasa cuando una clase hereda otras dos clases (HibridoDocencia por ejemplo) que tienen los mismos atributos (nombre y mensaje). Al momento de inicializar la clase HibridoDocencia(nombre="yo", mensaje="pucha la cuestion"), ¿Esos dos atributos se "duplican" para entrar a FullDocencia y FullTareas? o sea, ¿"Yo" entra como nombre tanto a FullDocencia como a FullTareas o entra a uno solo?

Pregunto porque no me está saliendo con **kwargs siendo que estoy imitando lo que sale en el cuaderno de multiherencia :c

**Comment by dchahuan** [comment]
Cuando pasas los kwargs, como argumento del super es como pasar un diccionario a todos los constructores de la superclase. Por lo tanto se pasan a las dos clases. Pero no se duplican, por lo menos a mi entender. Lo que pasa es que el constructor de la primera clase que super() pase le va a colocar un atributo nombre al objeto y luego el segundo va a reescribir el atributo nombre con el mismo valor que el anterior. Por lo tanto no se duplica aunque entre a los dos ya que cada uno de los constructores sobre escribe en la variable.

**Comment by margavicunas** [comment]
Gracias! :)

**Comment by dchahuan** [comment]
Ey me voy a tener tener que auto corregir en una parte. El si el constructor de una clase tiene como kwarg predeterminado por ejemplo nombre, este no va a seguir siendo traspado. Lo que te dije solo aplica si solo usas **kwargs como argumento.

**Comment by margavicunas** [comment]
Hola de nuevo! Me está complicando hacer el ejercicio propuesto de la ayudantía 3 y no logro pasarle los atributos a Cebra y Asno al instanciar Cebrasno :( 

![Screenshot (61)](https://user-images.githubusercontent.com/69604538/91992656-63e6a980-ed02-11ea-8ba8-388d8185c8b1.png)
![Screenshot (62)](https://user-images.githubusercontent.com/69604538/91992660-6517d680-ed02-11ea-97fd-9dc022fa6640.png)

¿Cómo hacer para pasar el mismo atributo a dos clases distintas? Estoy confundida en como hacerlo

Gracias de antemano!

**Comment by dchahuan** [comment]
Mira lo que esta pasando con tu codigo, es que cuando uno de los parametros del constructor tiene el mismo nombre que un kwarg, este "sale" de los kwargs. Entonces lo que esta pasando es cuando llegas a asno ya no le estas pasando ni un kwarg, a tu clase Animal. Por lo que los 

Entonces en tu codigo una posible solucion que podrias pensar, es que pasa si en el constructor de la clase super, le paso los argumentos que tengo que seguir pasando. Asi no repetirse como por ejemplo:


class Zebra(Animal):
    def ____init____(self, atributo1, atributo2):
        super().____init____(atributo1,atributo2)

Asi asegurar que estoy pasando el atributo a mi clase superior y no tener que preocuparse tanto con los args y kwargs.

**Comment by margavicunas** [comment]
No me quedó muy claro cómo resolverlo :( ¿podrías explicarme de nuevo?

**Comment by dchahuan** [comment]
Ya entonces en vez de usar kwargs y args uno le va pasando los argumentos que se necesitan a la clase super, asi asegurarse que estos sigan subiendo en la cadena de herencia y no tener que fijarse en listas variables.

**Comment by dchahuan** [comment]
Para ver como funcionan los kwargs en herencia hay un ejemplo muy bueno en el material del curso con la clase investigador, docente y academica que esta en el juptyer de multiherencia.
