### ISSUE TITLE
duda locales en cargar_datos, Set self.maxDiff

### ISSUE THREAD

**Issue by nicolettadegoye** [IIC2233/Syllabus#306]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
tengo una duda sobre un error que me aparece al correr los test, la cual es: AssertionError: Element counts were not equal:
Diff is 1073 characters long. Set self.maxDiff to None to see it.

**Comment by karlamunoz14** [comment]
tengo el mismo error :c

**Comment by Jeremiah-PHP6** [comment]
Hola! ¿Podrías enviar una captura del error que te arroja? Si es posible, que se vea el test que estás ejecutando.

**Comment by elneitans** [comment]
@nicolettadegoye  ve en cuál tipo de generador te está saliendo el error y luego ve el tipo de dato que tiene el archivo correspondiente

**Comment by karlamunoz14** [comment]
![error](https://github.com/IIC2233/Syllabus/assets/101335687/3364dbef-7b13-4584-97da-b3bea1b61ea5)
ese es el error que me aparece

**Comment by Jeremiah-PHP6** [comment]
@karlamunoz14 Entiendo. El error ocurre porque la cantidad de distritos que espera el test no coincide con los que entrega la función que estás creando. Revisa que estés accediendo a la carpeta correcta en  la función cargar_datos.

Me cuentas que tal 🙂

**Comment by nicolettadegoye** [comment]
si accede a la carpeta correcta :(. Intente hacer esto para ver cual era el error: 
```generador = list(cargar_datos("locales", "s"))
for elem in generador:
    print(elem)
print(len(generador))``` y me imprime:
(antes viene todo el generador) ... Locales(id_local='2362', nombre_local='Local 2362', id_comuna='343', id_votantes=[481, 1390, 1611, 1982, 2014, 2377, 3865, 3882, 4987, 5486, 5724, 6589, 7259, 9243, 9262, 9617])
2362
Entonces no entiendo porque no funciona si da lo esperado de los test case.

**Comment by Jeremiah-PHP6** [comment]
@nicolettadegoye Solo para confirmar, el error que te aparece es en la misma línea que a @karlamunoz14 ? Pareciera que lo que falla en tu caso es test_s_locales

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Hola! A mi también me pasa lo mismo :c

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Hola! A mi me aparece el mismo error pero en el contexto de los tests test_s_locales y test_l_locales.

**Comment by nicolettadegoye** [comment]
me aparece en todos estos:
FAIL: test_l_locales (__main__.TestCargarDatos.test_l_locales)

         Probando con el dataset L de locales

----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Nicoletta\Desktop\nicolettadegoye-iic2233-2024-1\Tareas\T3\tests_publicos\test_base_cargar_datos.py", line 232, in test_l_locales
    self.assertCountEqual(locales_cargados, locales_esperados)
AssertionError: Element counts were not equal:

Diff is 1783 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_s_locales (__main__.TestCargarDatos.test_s_locales)

         Probando con el dataset S de locales

----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Nicoletta\Desktop\nicolettadegoye-iic2233-2024-1\Tareas\T3\tests_publicos\test_base_cargar_datos.py", line 138, in test_s_locales
    self.assertCountEqual(locales_cargados, locales_esperados)
AssertionError: Element counts were not equal:

Diff is 1073 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------

**Comment by Jeremiah-PHP6** [comment]
@nicolettadegoye En tu caso, la cantidad de locales esperados es distinta a la cantidad entregada por tu función. Te recomiendo copiar las variables: generador, locales_cargados y locales_esperados, ubicadas en la función test_s_locales (test_base_cargar_datos.py). Luego, ejecútala en consultas.py y haz un print a las últimas dos y revisa en qué difieren.

Si aún no logras identificar el error, haz un push con el código que lleves para poder revisarlo y asistirte mejor. 😊

**Comment by karlamunoz14** [comment]
hola, yo ya se cual es mi error, pero no se si puedo subir ese trocito de codigo aqui, pero lo tratare de explicar, cuando abro el archivo y hago .strip().split(",") al recibir la lista en el momento de los locales, la diferencia se produce en que si la lista es [38, 46], como realice un split(",") se separa la lista y al acceder al dato me da como resultado "[38 " y no se como repararlo, de igual forma te dejo un pantallazo de la diferencia al hacer print, muchas gracias de antemano 
![errorrr](https://github.com/IIC2233/Syllabus/assets/101335687/b3dbe7f1-1cee-4470-ad8f-009ab32f40bd)
![errorrr](https://github.com/IIC2233/Syllabus/assets/101335687/a19e3202-bf35-4943-b690-10c4e096d04a)

**Comment by Jeremiah-PHP6** [comment]
@karlamunoz14 ¡Ojo que no está permitido subir código a las issues! Cualquier duda sobre lo que hiciste, puedes hacer un push y pedir que alguien del equipo te lo revise.

En cuanto a tu duda, podrías partir quitando los corchetes de entrada y salida en el primer y último elemento de la lista. Luego, manipula los índices para seleccionar los elementos de dicha lista en el split(",") y así los guardas en una lista aparte.
Espero te haya servido, cualquier cosa me comentas. 😃

**Comment by javirossi** [comment]
Hola, tengo un error con los tests de locales (ValueError: invalid literal for int() with base 10: ''), pero no logro entender a qué se debe si al hacer print de los datos cargados aparecen bien. ¿Será posible revisar mi código? Ya hice un push, muchas gracias de antemano.

**Comment by lietril** [comment]
Hola a mi también me da el error AssertionError: Element counts were not equal, al hacer print con la información del test case me da lo pedido así que no sé cual sería el problema. Voy a subir un ejemplo de lo que me da el print con la información del primer test de s animales

![image](https://github.com/IIC2233/Syllabus/assets/162619221/8f99f6dd-192d-4abb-9dd1-0bc5625fadd1)
