### ISSUE TITLE
Duda sobre importación de parametros

### ISSUE THREAD

**Issue by Artaudd** [IIC2233/syllabus#306]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, ¿**para importar los parámetros que creemos en parametros.py se puede hacer from parametros import * ?**  Porque recuerdo que hacerlo era considerado mala práctica, sin embargo al contar con tantos parámetros se me hace extraño importarlos todos de la forma import parametro0, parametro1, etc...
Soy consciente de que también podría importar el modulo completo y usar los parámetros escribiendo el nombre del módulo antes, pero creo que quedarían muy largos dentro del código al hacerlo. También se me ocurre que podría importar el módulo completo con un alias más corto, pero no sé si es la opción más optima visualmente (se me hace raro ver una variable escrita como p.PARAMETRO).

¿Qué debería hacer? :(

**Comment by manearaya** [comment]
Hola @Artaudd!

**Está prohibido importar cualquier módulo sin hacer referencia a él**, entonces no se puede hacer `from parametros import *`. Te recomiendo visitar el cuaderno 2-modularización de los contenidos de la semana 0 para recordar las maneras de importar y por qué se penaliza en el curso la importación sin hacer referencia al módulo.

Lamento que no te parezca óptimo visualmente usar `p.PARAMETRO` (quizás te parezca más `P.PARAMETRO`?), pero usar `from parametros import *` también tiene sus desventajas, como puedes ver en el cuaderno de contenidos.

Saludos!
