### ISSUE TITLE
NO PUEDO HACER PUSH!!

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2233/syllabus#306]
Hola mi ultimo push lo hice hace 4 horas, esto es lo que dice: 
 error: failed to push some refs to 'https://github.com/IIC2233/jfuentesg26-iic2233-2019-2.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

porfavor ayuda!! no se que hacer

**Comment by gatochico** [comment]
Hola, intenta seguir las instrucciones de la issue #305 . **(RECUERDA SIEMPRE HACER UNA COPIA EN TU COMPUTADOR DE TU TAREA PRIMERO)**

**Comment by jfuentesg26** [comment]
Ahora me funciono, pero ya estoy fuera de plazo, que puedo hacer? o que tengo que hacer si la entregue 12 min tarde?

**Comment by lily416** [comment]
@jfuentesg26 primero espera ver recibir la issue en la que se indica el commit a revisar, si sientes que ese commit no es adecuado para la corrección, entonces contesta el form de entrega atrasada indicando el commit a corregir.
