### ISSUE TITLE
¿Conejo debe empezar en E o en frende de E? ¿Hay diferencia cuando hace respawn?

### ISSUE THREAD

**Issue by VAMarques** [IIC2233/Syllabus#307]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hago esta pregunta debido a varias inconsistencias en el enunciado y en los archivos.
Por ejemplo, en esta imagen Conejochico parece empezar en la entrada y no frente a ella.
![imagen](https://github.com/IIC2233/Syllabus/assets/141939409/79c73764-b2ee-4ea8-b51a-d2b592f31fbd)

Pero por ejemplo en tablero_1.txt conejo y entrada estan separados.
![imagen](https://github.com/IIC2233/Syllabus/assets/141939409/09ed87a2-ffa1-48f4-ae6f-e0f02b4f2dd0)

Entonces cada vez que conejo pierde una vida haria respawn en Entrada, o frente a ella?

**Comment by cbuerger02** [comment]
Hola! Asúmelo como tú prefieras, pero te recomiendo que lo escribas en el apartado de consideraciones del README.
