### ISSUE TITLE
Error mutex

### ISSUE THREAD

**Issue by juanicortesl** [IIC2233/syllabus#307]
Hola, al utilizer mutex como lock, la ventana se cierra con el siguiente mensaje: exit code 139 (interrupted by signal 11: SIGSEGV) python. No logro identificar cual es el problema, si alguien tiene algo de información se lo agradecería. Saludos

**Comment by IchottMano** [comment]
Hola!
Me podrías dar algo más de información sobre que estas haciendo cuando obtienes este error?
Usualmente este error ocurre en PyQt5 cuando no guardas las referencias de un objeto, causando que python por detrás lo borre y cuando tu programa intenta acceder a este objeto, lanza este error de memoria.
Quedo atento.
Saludos!

**Comment by juanicortesl** [comment]
Quería que la torre chequee el hp de un enemigo con un mutex, para que no acceda a este mientras el enemigo esta recibiendo el ataque, sino que espere a que este se efectue. Esto funcionaba, pero cuando el hp del enemigo llegaba a 0, lo eliminaba, quizás en esa parte podía estar el error.

**Comment by IchottMano** [comment]
Como "eliminas" al enemigo?
Probablemente ahí sea donde radica tu error, debes tener cuidado de eliminar **completamente** al enemigo, es decir cualquier referencia que pueda tener en tu código, como en algún timer o thread que esté tratando de hacer algo con el enemigo despues que este haya sido eliminado, causando tu falla de memoria.
Dime si esto te hace sentido o te queda alguna duda con respecto a eso, y si efectivamente pudo arreglar tu error.
Saludos!

**Comment by juanicortesl** [comment]
Si, gracias, creo que ahora entiendo mejor a que se debe el problema y el error ya no ocurre, pero ahora muy de vez en cuando obtengo el siguiente error: Python(4175,0x70000c847000) malloc: *** error for object 0x11df2bad0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
No se si es por el mismo problema de antes o es un error diferente.
