### ISSUE TITLE
Mercancia.expirar() duda respecto a metodo Expirar

### ISSUE THREAD

**Issue by maurobsp** [IIC2233/syllabus#307]
### Prerrequisitos
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Al expirar la carga. se cobra al canal cierto monto dependiendo el tipo de mercancía, luego de esto, ¿ La mercancía es eliminada de la carga del barco o sigue siendo parte de sur carga y agregando peso a este?, en caso de que no se elimine, ¿cada caja solo puede expirar una vez? por lo que solo podría cobrar solo una vez que expire una caja?

**Comment by manearaya** [comment]
Hola @maurobsp!

Cuando una caja de mercancía expira, esta no se elimina del barco, por lo que sigue siendo parte de su carga. Además, no puede volver a expirar, entonces se cobra una sola vez la multa cuando una caja expira.

Éxito con la tarea!
