### ISSUE TITLE
Error en ejercicio propuesto 2.1 S03

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#307]
Hola! En el ejercicio propuesto 2.1 de la semana 3, que trata sobre pasar de diagrama de clases a código, hay un método repetido en el diagrama de clases. ¿Asumo que uno de los dos `cargar_competidores()` de la clase `GrandPrix` debería decir `cargar_vehiculos()`?
Gracias de antemano 😄

**Comment by Juampisaez** [comment]
Hola @sbcorrea 
Probablemente fue un error al escribirlo, yo consideraría cargar_vehiculos()
