### ISSUE TITLE
Duda con prohibiciones de comandos.

### ISSUE THREAD

**Issue by Martinluco** [IIC2233/Syllabus#307]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! A que se refiere esta parte del enunciaod?
 "Cómo se indica antes, la excepción al uso de estos comandos es es si deseas utilizar reduce y el inicializador es una lista, set o diccionario vacío."
Se puede crear listas y sets vacíos en cualquier parte de la tarea?
Gracias!

**Comment by TomasGMDC** [comment]
Lo que dice esa parte es que no, no se pueden crear listas, sets, tuplas, y/o diccionarios vacíos, entre otros, en cualquier parte de la tarea, solamente como inicializador de un reduce. En el fondo, si está dentro de un reduce, se puede usar (ojo con hacer algún tipo de trampa y usar un reduce para crear una lista, set, tupla y/o diccionario vacío adrede. La idea es que el reduce esté cumpliendo alguna función).

**Comment by Martinluco** [comment]
y como funciona el tema de las listas, sets, diccionarios por comprension? esas si se pueden crear sin problemas?

**Comment by TomasGMDC** [comment]
Eso dice el enunciado, así que sí.

**Comment by Martinluco** [comment]
Muchas gracias por la ayuda!

**Comment by elneitans** [comment]
Entonces, en una función que retorna un generador, yo podría crear una lista por compresión, recorrerla, encontrar un valor, y luego en otro ciclo retornar el yield del generador? Así como:
`def ...:`
   
`   lista = [ ... for i in ..]`
`    for i in lista:`
 `            ...`
`    for i in generador:`
`          yield i`

**Comment by IsidoraCarmona** [comment]
a que se refieren cuando dicen listas, sets, diccionarios por comprensión? no entiendo el concepto 'por compresión'

**Comment by TomasGMDC** [comment]
@IsidoraCarmona cuando se habla de listas, sets, diccionarios y/o tuplas por comprensión, se habla de una forma específica de generar iterables, en base a uno o más iteradores.
La sintaxis, por ejemplo, puede ser:

lista = [operacion(n) for n in iterador]

Donde se forma una lista a partir de una operación dependiente de los valores de un iterador (otra lista, por ejemplo). Entonces si la operación fuera n+1, quedaría:

lista = [n + 1 for n in lista_numeros]

Lo cual representa una lista por comprensión de todos los elementos de lista_numeros, sumados 1. En los contenidos, en la clase 1 de la semana 9, se muestran un par de ejemplos de iterables por comprensión.

**Comment by TomasGMDC** [comment]
@elneitans sí, se puede lo que mencionas.

**Comment by rodrigoaguilera15** [comment]
Se puede usar sum( ) ?

**Comment by njllanos** [comment]
En cuanto al mismo tema de las listas por compresión, uno podría usarlas en cualquier aplicación? Por ejemplo, en una función que recibe un generador llamado "cosas",  ¿Es válido definir una lista por compresión que fuera "[cosa for cosa in cosas]" para pasar el contenido del generador recibido a una lista?

**Comment by TomasGMDC** [comment]
@njllanos efectivamente, se puede.

**Comment by Benjaa7** [comment]
Entonces puedo transformar un generador a lista de la siguiente manera?
`lista = list(generador_x)`

**Comment by josefinaabbott** [comment]
puedo usar los comandos prohibidos junto con un map?     Por ejemplo hacer elementos = set(map(lambda ......))

**Comment by TomasGMDC** [comment]
@Benjaa7 no, no puedes de esa manera. En las consultas si quieres hacer una lista debe ser por comprensión. Según el enunciado, en las consultas solo puedes usar list si está dentro de un reduce.

**Comment by Yeps3nM** [comment]
Hola! Tengo una consulta, que pasa si creo una lista por comprensión donde dentro relleno otra que fue creada vacía inicialmente. (Esto en un archivo distinto con funciones auxiliares ). Es correcto rellenar esta de esa forma o en ningún caso incluso en modulos importables se pueden crear algún tipo de estructura vacía?

**Comment by SebastianArroyoSanchez** [comment]
Gracias por su tiempo, me queda un poco la duda que tipos de listas se pueden o no usar.

Este si se podría utilizar: a_3 = [int(valor.strip('[').strip(']')) for valor in a[3:]]

Y esto no (?)
return len(list(map(lambda votos: votos.id_voto, generador_votos)))

**Comment by TomasGMDC** [comment]
@josefinaabbott no se puede lo que mencionas, dado que set() está fuera de map(), e incluso si estuviera adentro, en base a lo dicho en el disclaimer y en " #339 ", solo se puede usar dentro de un reduce o en una función generadora.

**Comment by TomasGMDC** [comment]
@Yeps3nM en base a lo dicho en el enunciado y en " #339 ", solo se pueden crear este tipo de elementos vacíos dentro de un reduce o una función generadora, esto sin importar si es en el módulo principal o uno auxiliar.

**Comment by TomasGMDC** [comment]
@SebastianArroyoSanchez el primero se trata de una lista por comprensión, así que sí se puede usar.
En el segundo estás inicializando una lista en una función que retorna (no es una función generadora que funcione con yield), así que no se puede usar.

**Comment by antoechenique** [comment]
Hola! Puedo usar el comando max() en una función generadora?

**Comment by TomasGMDC** [comment]
@antoechenique según lo dicho en " #298 ", sí puedes. No te olvides de asegurarte de que no hayan problemas usando el script de revisión entregado.
