### ISSUE TITLE
Problema al hacer git add para subir el readme

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#307]
Estoy tratando de subir el readme pero me sale un error. Busqué en internet e intente usando el comando git rm -f .git/index.lock pero no sirvió y me sigue saliendo el mismo error
![error](https://user-images.githubusercontent.com/48482398/64927041-00572980-d7dc-11e9-8e86-2aea945a3199.png)

**Comment by jeschuwirth** [comment]
Hola!

A la rápida te diría que reinicies el pc y debería funcionar, como solución final que siempre funciona en git te recomiendo copiar todos los datos y pegarlos en una nueva carpeta, luego clonar nuevamente tu repo y pegarle los archivos que quieres subir.

Si no te funciona avísanos para seguir ayudándote :)

Suerte!
