### ISSUE TITLE
llamar a f  dentro g y luego desde g a f

### ISSUE THREAD

**Issue by rjdelrio** [IIC2233/Syllabus#307]
se puede hacer lo siguente teniendo esta consulta:
"comparar", ["PROM", "x"], ">", ["DESV", "y"]]
funcion analizadora consultas
..............una ves dentro revisar si es un numero o otra consulta
.........................si es otra consulta llamar a funcion analizadora consultas
......................                 
.........................si no ver quien es mayor

**Comment by Hernan4444** [comment]
@rjdelrio ten cuidado con eso, si es como el titulo dice que de F vas a G y desde G vas a F, no puedes porque es programación circular. En cambio si F llama de nuevo a F y así sucesivamente...y solo al final llama a G para pedir un dato pero solo haces returns para devolverte de todas las llamadas recursivas de F, todo bien. La idea es que una funcion X llama a otra funcion Y, entonces X no puede volver a ser llamada en esa recursion.

Es decir: 
1) F -> F -> F ->G   :white_check_mark: 
2) F -> D                  :white_check_mark: 
3) F -> F -> G -> E  :white_check_mark: 
4) F -> D -> F          :negative_squared_cross_mark:
5)  F -> D -> E -> F :negative_squared_cross_mark:
