### ISSUE TITLE
Mostrar Label generada

### ISSUE THREAD

**Issue by searzola** [IIC2233/Syllabus#307]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, estoy intentando generar las papas como una clase heredada de QLabel, pero no sé como hacer que aparezcan dentro de la ventana de juego, ya que al añadirlas no se ven y si en el init() ejecuto self.show() se crea una nueva ventana con la papa. El código lo subí al repositorio por si algún ayudante puede revisarlo.

**Comment by Bjnazar** [comment]
Hola!
A mi me pasó algo parecido y se soluciona poniendo el self al crear la Qlabel
como: label = QLabel(self) y ese self indicaría que se pone dentro de la ventana donde lo estan creando, sino se hace otra ventana con esa label
