### ISSUE TITLE
duda inputs inválidos de intercambiar (opciones de jardín)

### ISSUE THREAD

**Issue by hovyman** [IIC2233/Syllabus#307]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En Menú Jardín la opción intercambiar, ¿ Como se van a ser los errores del  el input() de las posiciones (Ej: 1,2;3,4) ?, tipo solo va a haber error como que tenga un carácter no numérico o números fuera de rango, tipo: (a,b;3,2) o también tengo que revisar que cumplan el formato de num,num;num,num (Ej: input = 12;13 , input = hola, etc)

**Comment by augustayanez** [comment]
Debido a que los menús tienen que ser a prueba de todo tipo de errores de usuario, tu programa tiene que ser capaz de manejar todos los errores por los que preguntas sin caerse e informarle al usuario que el input es inválido.
