### ISSUE TITLE
Cómo hacer que las monedas aparezcan cada cierto tiempo?

### ISSUE THREAD

**Issue by aljara97** [IIC2233/syllabus#308]
Hola, puedo crear una moneda que aparecerá un tiempo duración_moneda (actualmente lo hace solo en el inicio). Sin embargo, no puedo definir una función que las haga aparecer cada un tiempo_moneda, intenté hacer una función con un while True que durmiera el tiempo_moneda y ahí creara una, la cual desaparecía luego de su duración. Asumo que esto es muy complicado para el programa, ya que no mostró ninguna interfaz gráfica.

**Comment by JJJGGGG** [comment]
Usa un QTimer, y conecta su señal de timeout a la función

**Comment by roberto009** [comment]
Hola! 
No podemos decirte exactamente como modelar tu programa, pero no te recomiendo el `while` que estabas tratando de implementar. Puedo decirte que veas los consejos de ~~ @JJJGGGG  ~~ tus compañeros 😉 
Éxito con la tarea!
