### ISSUE TITLE
Duda sobre método desencallar_barco

### ISSUE THREAD

**Issue by ignaciaurrutia** [IIC2233/syllabus#308]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Cuando el canal intenta desencallar un barco, esto tiene un costo de COSTO_DESENCALLAR. Este valor se le cobra al canal a pesar de que el barco no desencalle? O solo cuando desencalla con éxito? Gracias!

**Comment by Emiliax16** [comment]
Hola! independiente de si el barco ejecuta esa acción con o sin éxito, el COSTO_DESENCALLAR se cobra.
Avísame si sigues teniendo dudas !

**Comment by Nicolemarin** [comment]
Ese costo lo debe pagar el barco al canal, o el canal al barco?  No queda claro
