### ISSUE TITLE
Error tipeo: Contenidos semana-03 -> clases abstractas

### ISSUE THREAD

**Issue by DasVaca** [IIC2233/syllabus#308]
>Luego, al instanciarse, podemos ver que funciona y utiliza el molde **deefinido** en Personaje, pero aterrizado a las implementaciones **de de** Jugador.

No es grave ni de cerca, pero está.

**Comment by aaossa** [comment]
Gracias por el aviso 🙌 Lo arreglaré en el repo interno, para no provocar cambios que afecten sus repositorios locales 😅
