### ISSUE TITLE
Encoding, Letras con Tildes

### ISSUE THREAD

**Issue by arturopachecoh** [IIC2233/Syllabus#308]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

La lectura de los archivos que contienen tildes o otros caracteres únicos del español, me están dando errores a la hora de leer el archivo. Intente cambiando el encoding de UTF-8 a otros donde las letras sí se ven de forma correcta en VScode pero al correr el código en la terminal me sigue apareciendo el error:

<img width="696" alt="Screenshot 2024-05-15 at 1 11 51 PM" src="https://github.com/IIC2233/Syllabus/assets/162739672/86bcee03-a797-4be1-aa68-2b60e7ca009b">

Donde la posición 69 del archivo es justo una "í".

**Comment by coniverav** [comment]
Es válido colocar `encoding = 'utf-8', errors = 'replace'`?

**Comment by ClemoAcevedo** [comment]
Hola @coniverav , es preferible que utilices el encoding latin-1 para evitar cualquier problema con los tildes y asegurar la consistencia con los datos de prueba y los test cases.
