### ISSUE TITLE
Referencia invalida y Error de tipo

### ISSUE THREAD

**Issue by rfenzo** [IIC2233/Syllabus#308]
Como puedo distingir estos dos tipos de errores dentro del programa? 
Pregunto porque por ejemplo, ['filtrar','x', '<', [PROM,'x']] es puesto como ejemplo de Referencia Inválida cuando x no está definido, pero tambien se puede entender como Error de Tipo, pues está ingresando un string en vez de una columna.

**Comment by Hernan4444** [comment]
@rfenzo queda tu criterio, depende de como modelaste las funciones, mientras entreges que hay un error y digas cual es la causa todo bien!! :D 

Saludos!!
