### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by raespinoza4** [IIC2233/Syllabus#308]
Hola, al intentar printear una representación de mi grafo (lo cual no habia probado, solo habia cargado los jugadores a este), me sale el siguiente error:

`Traceback (most recent call last):
  File "D:\Universidad\raespinoza4-iic2233-2018-1\Tareas\T02\main.py", line 274, in <module>
    print(map)
  File "C:\Users\Rodrigo\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0107' in position 240: character maps to <undefined>
[Finished in 0.355s]`

Intente con las soluciones nada en la issue #234 pero no me funcionó ninguna :(

**Comment by IchottMano** [comment]
@raespinoza4 Hola!

Que estas usando para correr tu código?

Saludos!

**Comment by raespinoza4** [comment]
Estoy usando el package script, en atom

**Comment by raespinoza4** [comment]
Btw, lo acabo de intentar ejecutar desde la consola de windows y funcionó altiro.
Abra alguna forma de poder ejecutarlo desde atom ?

**Comment by IchottMano** [comment]
Justo iba a decirte que intentaras correrlo por consola jajaja,
el problema es que el paquete que corre scritps de python en atom tiene los prints con un encoding distinto que no cubre muchas letras que se usan en nuestro csv, por lo que arroja el error.
Si en verdad no quieres que pase eso puedes descargar pycharm (tiene una opcion para cambiar encoding) pero si decides quedarte con atom, por lo menos en esta tarea deberás correr los scripts por consola.

Saludos!
