### ISSUE TITLE
Issue a revisar

### ISSUE THREAD

**Issue by lucastack** [IIC2233/syllabus#308]
Hola! no se por qué pero el push a revisar es anterior al último que hice. El correo automático dice que se revisará un push del día viernes a las 6 de la tarde aprox. mientras que el último que hice fue el día sábado como a las 19:00 hrs (así está registrado en el repositorio, no es que me haya equivocado y no lo haya subido correctamente ). Envié un correo al mail del curso y aprovecho de postear por acá también por si alguien le pasó :(

**Comment by ShescBlank** [comment]
Hola :D A mi también me pasó lo mismo :( solo que el commit a revisar es uno del sábado en la mañana e hice muchos después de ese :c (todos dentro del plazo adecuado)

**Comment by javieranavarrete** [comment]
Hola, si a mi también me pasó, subí mi tarea aprox a las 7 (por primera vez) y en el correo automático dice que no subí nada.

**Comment by Gaonuk** [comment]
Hola, a mi también me paso lo mismo!

**Comment by Pabloinz** [comment]
Tengo el mismo problema

**Comment by Pablok98** [comment]
Hola! Estoy en las mismas. El commit que me van a revisar es del viernes y pushee varias veces el sabado!

**Comment by entamburini** [comment]
¡Hola!

Me han llegado muchos mails al respecto. Fue un error en la revisión de la fecha de los commits. Se arreglará durante la mañana :) 

Les pido perdón por el susto y el mal rato que les pudo generar eso :c

**Comment by Pablok98** [comment]
Gracias!

**Comment by entamburini** [comment]
Ya está solucionado el problema :rocket: 
Pueden revisar sus repositorios, se cerró la issue anterior y se les creó una nueva para que no hayan confusiones :wink:
