### ISSUE TITLE
Cierre de ventana de juego

### ISSUE THREAD

**Issue by Witomi** [IIC2233/syllabus#309]
Hola!

Me pasa que cuando empieza a funcionar la ventana del juego después de un rato me aparece el siguiente error: Process finished with exit code -1073740791 (0xC0000409)
No sé si se deberá a una falta de memoria(dado que instancio cada cierto tiempo los coins) o a qué. Tengo también puesto el código que dieron para que muestre el tipo de error cuando se utilizan interfaces pero solo me sale eso.

Gracias desde ya!

**Comment by DCCollao** [comment]
Hola! ¿Tienes noción de qué parte de tu código genera este problema?

**Comment by Witomi** [comment]
Me sucede en la parte de los coins en que el coin(qthread) se toma un tiempo para desaparecer si es que no se ha llamado a la funcion agarrar_moneda, las monedas las instancio con qtimer

**Comment by Witomi** [comment]
Creo que ya lo arreglé, lo que hice fue que cualquiera de las finales del coin(tiempo maximo alcanzado o se agarra) le puse despues la funcion .quit(), no se muy bien el porque pero me funciona :)

Gracias de todas maneras!
