### ISSUE TITLE
Uso de kwargs en multiherenica

### ISSUE THREAD

**Issue by ignaciovilla** [IIC2233/syllabus#309]
Hola! En el último ejemplo de mutiherencia se hace uso de kwargs para llamar al init de las distintas subclases, y a medida que se va usando el kwarg, se va borrando de la lista de kwargs. Mi pregunta es la siguiente, que pasaría en el caso que los dos métodos init tengan un atributo con el mismo nombre clave? 
Muchas gracias de antemano

**Comment by dchahuan** [comment]
Si los dos tienen el mismo atributo clave, lo que importa es que llamas primero, si el init de tu super o los atributos de la clase. Mira este ejemplo:
class Investigador:

    def __init__(self, area='',nombre = "", **kwargs):
        print(f"init Investigador con area {area} y kwargs:{kwargs}")
        super().__init__(**kwargs)
        self.nombre = nombre
        self.area = area
        self.num_publicaciones = 0
        
class Docente:

    def __init__(self, departamento='', **kwargs):
        print(f"init Docente con depto {departamento} y kwargs:{kwargs}")
        super().__init__(**kwargs)
        self.departamento = departamento
        self.num_cursos = 3


class Academico(Docente, Investigador):

    def __init__(self, nombre, oficina, **kwargs):
        print(f"init Academico con nombre {nombre}, oficina {oficina}, kwargs:{kwargs}")
        super().__init__(**kwargs)
        self.nombre = nombre
        self.oficina = oficina

Aquí Investigador que es la ultima clase que se llama en el super no va a recibir nombre. Pero como super().__init__ lo llamo primero que cuando le atribuyo self.nombre a el Academico, lo que va a pasar es que se va a definir un atributo que sea self.nombre y este va a estar vacio. Pero luego lo voy a sobre escribir con el de la clase academico que si tiene el valor que yo quiero. Algo distinto ocurre si llamara al super despues. Donde mi clase academico tendria  un atributo self.nombre con el valor que yo quiero, y luego en la clase investigador lo sobreescribiria a un nombre vacio. Lo que me dejaria el nombre del atributo como vacio.

**Comment by ignaciovilla** [comment]
Muchas gracias! Me surge otra duda. Que pasa si dos subclases tiene el mismo atributo con el mismo nombre, por ejemplo, si ambos investigador y docente tienen el atributo área y suponiendo a que se refieren a lo mismo, a la hora de entregarle kwargs, alguno de los dos se quedaría sin el valor para el atributo, eso no arrojaría un error'?
Muchas gracias de nuevo

**Comment by dchahuan** [comment]
Siguiendo el mismo hilo, si no tuviera un valor predeterminado arrojaria un error. Pero en el caso como en el codigo de arriba en donde le puse nombre a dos de las clases y tengo el valor predeterminado vacio. El valor del atributo que se quede es el ultimo que se declaro, que en este caso seria el de academico ya que al constructor del super lo llamo antes que declarar el valor de nombre en la clase academico.
