### ISSUE TITLE
Problema cuando hago muchas veces el gui.pop_piece

### ISSUE THREAD

**Issue by santi95** [IIC2233/Syllabus#309]
Hola!

Estoy haciendo el historial y para poder retornar al por ejemplo "punto guardado 1" mi programa necesita que el tablero esté vacío.

Los for en mi lista funcionan impecables, pero al hacer
for i in range(8):
    for j in range(8):
        gui.pop_piece(i,j)

No me los borra todos. Alguna sugerencia?

**Comment by cotiravanal** [comment]
no te tira un error? a mi me tiraba un error cuando intente hacer eso porque habias veces que el tablero ya estaba vacio pero nose si era por eso en vedad jaja se me arreglo haciendo un if, y si es que el tablero en esa posicion no estaba vacio entonces le hacia el gui.pop_piece(i,j) para que me sacara la pieza

**Comment by santi95** [comment]
sisi eso hice yo! pero nada, nunca me los eliminó todos :/
