### ISSUE TITLE
"KUR", "ASI", "VAR-COEF", "KUR-COEF" or "ASI-COEF"

### ISSUE THREAD

**Issue by rfenzo** [IIC2233/Syllabus#309]
Que estadisticos son aquellos? Kur supongo que viene de kurtosis, pero los otros ni idea.

**Comment by Hernan4444** [comment]
@rfenzo Error mio!!! esos comandos se decidieron sacar pero se me olvido sacarlo de toda parte que se menciona. Mil disculpas

Saludos!!

**Comment by rfenzo** [comment]
Okas, mejor! jajaja

**Comment by Dunkan1** [comment]
sustos que dan gusto
