### ISSUE TITLE
Esta app.exec() permitido?

### ISSUE THREAD

**Issue by waknaudt** [IIC2233/Syllabus#309]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, en muchos ejemplos como la experiencia 3 y la ayudantia 6, se utiliza la siguiente linea:

'''sys.exit(app.exec())'''

Pero segun la Issue de librerias prohibidas, no se puede usar exec(). Es la funcion app.exec() la misma que exec()? Se puede o no usar en la tarea? Si no se puede usar, con que linea se podria reemplazar que cumpla la misma funcionalidad?

**Comment by cbuerger02** [comment]
No, no es lo mismo. Sí se puede usar app.exec()

**Comment by mariapazmunoz** [comment]
Hola! y si quiero que una alerta de tipo QMessageBox() puedo iniciarla con .exec() tambien? Gracias!

**Comment by cbuerger02** [comment]
Hola, también debería estar permitido.
