### ISSUE TITLE
"warning: LF will be replaced by CRLF" - Git

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#309]
![image](https://user-images.githubusercontent.com/37153467/39090485-1c387856-45b7-11e8-83d5-d4a4821a22f2.png)
¿Qué significa eso?

**Comment by IchottMano** [comment]
@jmwielandt Hola!
No te preocupes por eso, es algo que git hace a veces pero no afecta tu código.
Saludos!

**Comment by jmwielandt** [comment]
Oka, gracias!
