### ISSUE TITLE
Duda método encallar Clase Barcos y método desencallar clase Canales

### ISSUE THREAD

**Issue by alvarocisternas** [IIC2233/syllabus#309]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### La duda que tengo ya se preguntó en otra issue (#245) pero no me quedó clara la explicación.
En ambos métodos (desencallar y encallar) de las respectivas clases Barcos y Canales entregan una probabilidad de encallar y una probabilidad de éxito para desencallar.

Me queda clarísimo como obtener estas probabilidades, pero no me queda claro:
1. Cómo se encalla/desencalla un barco
2. Cómo utilizar los valores de probabilidades de los métodos en la simulación.

**Comment by sperezmasri** [comment]
Hola @alvarocisternas!

1. Cómo encallar y desencallar los barcos queda a decisión tuya. Lo importante es que tu programa sea capaz de verificar si un barco está encallado en el canal, y lógicamente si se desencalla, que el programa logre identificar que ya no está encallado .

2. Para utilizar los valores de probabilidades te recomiendo revisar la librería ```random```, que tiene métodos que pueden servirte para lo que se pide.

Avísame si eso responde tus dudas, saludos! :smile:

**Comment by alvarocisternas** [comment]
Muchas gracias, ya se me ocurrió una idea así que por el momento todo ok!!
saludos @sperezmasri  !!
