### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by agustindesolminihac** [IIC2233/syllabus#309]
Hola, además de hacer el readme, ¿se pueden agregar también comentarios al código para que sea más fácil leerlo?

**Comment by entamburini** [comment]
Hola Agustin,

La verdad es que nadie lo había preguntado. Pero no, por ahora no se puede, quizás en versiones futuras del curso :thinking:

**Comment by agustindesolminihac** [comment]
Ok, gracias.
