### ISSUE TITLE
Consulta sobre Archivos a usar para la tarea 0

### ISSUE THREAD

**Issue by TomasRiquelme** [IIC2233/Syllabus#31]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Buenas tardes. En el punto 5 del enunciado de la tarea 0 se encuentra la frase "Dentro de la carpeta Archivos podrás encontrar información de los posibles tableros del castillo". ¿Esto quiere decir que los archivos de esa carpeta son los únicos que serán usados en la evaluacion? De no ser el caso, alteraría la forma que estoy pensando para verificar que el archivo sea válido.
Muchas gracias

**Comment by Hernan4444** [comment]
Hola @TomasRiquelme

Efectivamente, cualquier nombre de archivo que te demos, debe estar dentro de la carpeta "Archivos" si no está ahí, entonces ese archivo no existe. Lo que si, para la corrección podemos llenar esa carpeta con muuuchos archivos más para poder probar todas las funcionalidades.

Saludos c:
