### ISSUE TITLE
Jefes/Pilotos

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2233/Syllabus#31]
Un Jefe o Piloto puede estar asignado a mas de 1 incendio al mismo tiempo?

Saludos

**Comment by rpalmaotero** [comment]
@Rudyjb24 hola, no, no pueden estar movilizados en más de un incendio al mismo tiempo.

**Comment by asdegoyeneche** [comment]
Puede un Piloto estar asociado a más de 1 avión/helicóptero? Por lo que mientras un avión "descansa" luego de volarlo el piloto, el mismo piloto vuela otro avión.
Gracias!

**Comment by stephichau** [comment]
@asdegoyeneche por como se hicieron las tablas, un piloto no puede estar asociado a más de 1 recurso :).

**Comment by asdegoyeneche** [comment]
@stephichau perfecto gracias!
