### ISSUE TITLE
Auto.evaluación

### ISSUE THREAD

**Issue by Dnpoblete** [IIC2233/syllabus#31]
Hola, recién me acabo de acordar de la autoevaluación de la actividad 2,el día que fue la actividad no pude ingresar al form porque no me dejaba y no me acuerdo si la respondí después y quería saber si me podrían decir si la respondí o donde lo puedo ver, porque no me acuerdo y ahora trate de meterme y no me dice si la respondí o no y no me acuerdo de las preguntas tampoco por si me pueden ayudar porfavor porque si no la respondí de verdad quería hacerlo y no se si lo hice o no :´(

**Comment by Hernan4444** [comment]
Hola!, 

Revisando las respuestas tal parece que no respondiste el form :c Si tienes un problema con el ingreso del form (no solo este, sino cualquiera), tienes que hacer una issue para notificarnos y revisar dicho problema.

Lo sentimos :c ¡será para la próxima actividad!
Saludos

**Comment by Dnpoblete** [comment]
Pucha y no hay nada que pueda hacer? porque de verdad trate de responderla y el form no me dejaba y no es que tenga problemas con google form porque respondí los dos de las ayudantías y el de carga académica y este se me fue, pero de verdad quería responderlo fui a la clase y termine la actividad y todo pero como nome dejaba después se me olvido hasta ahora, no hay alguna forma en que lo pueda responder o algo por ser la primera vez?  de verdad que no quiero perder las décimas por se pavay tenía muy presente responderlo :(

**Comment by Hernan4444** [comment]
Lo lamento, pero para esta actividad no hay nada que se pueda hacer. Los plazos fueron establecidos desde un inicio y con una curso ya masivo como este,  no podemos hacer excepciones. Todavía quedan 4 actividades más (8 décimas). Y cualquier cosa que pase con el formulario, contactanos de inmediato para solucionarlo y así no tengas que dejarlo para después.

Saludos

**Comment by DCCollao** [comment]
Hola!
Te recomiendo que no cierres la issues, pues alguien más puede haber tenido el mismo problema y le serviría tu pregunta

Saludos
