### ISSUE TITLE
Duda Tarea - test_02_regar

### ISSUE THREAD

**Issue by juanriveraf** [IIC2233/Syllabus#31]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. Tengo una duda en la tarea, especificamente en el test case que corrige la funcion regar(). Uno de los test cases dentro de esta correccion hace un plano de 6x8, y al correr mi codigo me dio erroneo, pero luego de verificar la funcion manualmente creo que el test case tiene un error. Esto se debe a que sale que hay una parte regada, la cual no puede ser alcanzada por ninguno de los circulos de riego planteados. Muchas gracias.

**Comment by ignacio-sp** [comment]
Hola @juanriveraf, puedes especificar a que parte del cultivo te refieres? Revisando el `test_02_varios_riegos_sucesivos` no logro detectar un problema con el resultado esperado. Recuerda que el riego es sobre un círculo inscrito en el cuadrado que se forma al extender dicho círculo por el área entregada, **ignorando las esquinas**.

Quedo atento a tu respuesta!

**Comment by juanriveraf** [comment]
Hola @ignacio-sp . Yo el test case que tengo se llama solo riegos. Será que ya cambiaron el test case?

**Comment by juanriveraf** [comment]
Hola @ignacio-sp. El resultado esperado tiene en la primera fila y las primeras tres columnas un número 1 (como si lo regaron). Pero ninguno de las 3 funciones que hay llegan hasta ese punto. Bajo lo que yo intente hacer manualmente me da que esos 3 valores son 0.

**Comment by ignacio-sp** [comment]
Ojo que el test está llamando a la función `regar` 4 veces, siendo la última en donde se guarda el resultado en la variable `resultado_estudiante_final`, en donde se riega en la coordenada (0, 0), lo que causa que esas casillas que dices aumenten su valor.

**Comment by juanriveraf** [comment]
Ahi lo leí. No me había dado cuenta que había 4 funciones, solo vi las primeras 3. Muchas gracias.
