### ISSUE TITLE
Pauta evaluación T00

### ISSUE THREAD

**Issue by crow-rojas** [IIC2233/syllabus#31]
¡Hola!

Quería preguntar cuando se va a publicar la pauta de evaluación de la T00 para realizar el README.md, o quizá ya lo subieron y no la he encontrado :s Que alguien me diga, please :(

¡Gracias!

**Comment by KnowYourselves** [comment]
Hola @crow-rojas!

Revisa tu mail, esta fue enviada hace 3 días 👀. Pero de todas formas, tal vez solo quizás [este sea el link a la distribuición](https://docs.google.com/spreadsheets/d/1ndqu5lnVhCo_WYMhRzDI6HYAIJLxUfpfm4pL4uORgVg/edit#gid=0).

Éxito!

**Comment by crow-rojas** [comment]
@KnowYourselves  ¡Gracias!
