### ISSUE TITLE
Problemas Visual Studio Code

### ISSUE THREAD

**Issue by aayale** [IIC2233/syllabus#31]
Hola, estoy viendo el video tutorial de Instalacion Visual Studio Code y este no ejecuta el codigo, aun cuando escribí lo mismo que sale en el video

**Comment by Juampisaez** [comment]
Hola, si pudieras especificar un poco mas el error que aparece, las extensiones que tienes instaladas o la forma en que estas ejecutando el codigo, seria mas facil poder ayudar.
Quedo atento

**Comment by aayale** [comment]
holaa, ya logré hacerlo.Yo me habia equivocado en algo.
Muchas gracias
