### ISSUE TITLE
Diferencia entre __str__ y __repr__

### ISSUE THREAD

**Issue by mmsaavedra1** [IIC2233/Syllabus#31]
Busqué la diferencia entre ambos métodos y llegué a la siguiente página: 

[https://stackoverflow.com/questions/1436703/difference-between-str-and-repr-in-python](url)

No entiendo a que se refiere con que: "__repr__ is for developers, __str__ is for customers."

Y ¿a cuál se le da prioridad de uso, cuál es ese criterio?

**Comment by akaminetzkyp** [comment]
[Esta página](http://brennerm.github.io/posts/python-str-vs-repr.html) tiene una buena explicación. :)

Si `__repr__` y `__str__` están definidos, un `print()` imprime lo retornado por el método `__str__`.

Saludos!
