### ISSUE TITLE
Definición de alfabético y alfanumérico

### ISSUE THREAD

**Issue by MrNachoX** [IIC2233/Syllabus#31]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Al registrar un nuevo usuario, se pide que el nombre de usuario tenga caracteres alfabéticos y que la contraseña tenga caracteres alfanuméricos, pero no me queda claro cuales caracteres se definen como alfabéticos/alfanuméricos.
En el enunciado de la tarea dice:

> Alfanumérico hace referencia a los caracteres formados por letras (ya sean minúsculas o mayúsculas) sin tildes y/o dígitos numéricos.

Lo que queda un poco ambiguo ya que no se define exactamente qué es una letra. Por ejemplo la `ñ` es parte del alfabeto español pero no del inglés.
Según la documentación de python (https://docs.python.org/3/library/stdtypes.html#str.isalpha): 
> Alphabetic characters are those characters defined in the Unicode character database as “Letter”, i.e., those with general category property being one of “Lm”, “Lt”, “Lu”, “Ll”, or “Lo”. Note that this is different from the “Alphabetic” property defined in the Unicode Standard.

De acuerdo a esta definición, algunos caracteres como `â ៗ å ð ˀ ÿ ñ` serian alfabéticos, ya que python (y las funciones built-in) los considera letras.
¿Cual definición debo usar para la tarea? ¿La `ñ` cuenta como alfabética?

**Comment by Emiliax16** [comment]
Hola @MrNachoX ! para la creación de usuarios, utiliza el alfabeto español, lo que incluye la ñ. Para que el programa modifique y lea los archivos con estos caracteres especiales, utiliza el encoding utf-8, de hecho es evaluado en la distribución de puntaje.

Por otro lado, la contraseña debe contener caracteres alfanuméricos (números 1,2,3,4.... y el alfabeto nombrado anteriormente, ya sea en mayúsculas o minúsculas). Notar que para la contraseña, no es necesario contener ambos tipos de caracteres, es correcto tener una contraseña sólo de letras, sólo de números o una combinación de ambas. Lo importante es respetar el largo mínimo y no utilizar comas, espacios, etc.

Espero que haya quedado claro. Saludos!

**Comment by Daniel-Guajardo** [comment]
A mí me asalta una duda sobre el nombre de usuario. Ciertamente la condición dice que el nombre de usuario debe tener caracteres alfabéticos, pero el archivo **usuarios.csv** que venía por defecto tiene registrados algunos nombres de usuario que terminan con caracteres numéricos e incluso algunos nombres de usuario aparecen como 2 palabras separadas por guión. 

![image](https://user-images.githubusercontent.com/101299560/159397138-c1c6bc7d-0c98-4bc0-bb50-6ab5b72187f4.png)

Me gustaría saber si esos datos de usuario de ejemplo son independientes a la condición pedida en el programa, o si puedo hacer que el nombre de usuario termine con una cadena numérica o tenga guión en su nombre.

Saludos!

**Comment by Emiliax16** [comment]
Toda la razón! entonces la regla de contener sólo caracteres alfabéticos en los nombres de usuarios se aplicará para cada usuario nuevo que se crea en el programa, pero se mantendrán los nombres del archivo tal cual están. Saludos!

**Comment by BenjaminSotoG** [comment]
Hola, tengo una duda parecida. El enunciado dice el nombre debe tener un mínimo de caracteres alfabéticos. Con esto entiendo que puede tener valores numéricos cumpliendo la condición mínima de los caracteres alfabéticos. Dicho esto y considerando la respuesta anterior, pueden o no tener números los nombres de los usuarios nuevos?. Gracias!

**Comment by Emiliax16** [comment]
Hola @BenjaminSotoG . Respecto a tu pregunta, no, los nombres de los usuarios nuevos registrados tendrán sólo caracteres alfabéticos, no numéricos. Con **mínimo de caracteres** se hace referencia al largo, no al tipo. Saludos.
