### ISSUE TITLE
Duda respecto a los paths

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#31]
Hola! Resulta que para abrir un archivo (el de 'usuarios.csv', por ejemplo), primero lo hago portable mediante el código:
 `usuarios= os.path.join("lewebe-iic2233-2020-1","Tareas","T00","usuarios.csv")`
Sin embargo, esto implica que al momento de subir la tarea a mi repositorio, entre los archivos que deberé subir tienen que estar también los archivos que se me entregaron ('usuarios.csv', etc.) para que mi path tenga sentido. Me gustaría saber si esto es válido o si se está buscando que ocupe los paths de manera distinta para abrir estos archivos

**Comment by bvasquezm** [comment]
Hola @lewebe!

Efectivamente a la hora de subir tus archivos a tu repositorio, los módulos como `usuarios.csv`estarán en la carpeta de tu ayudante corrector. Por lo tanto no debes preocuparte de subir nuevamente dichos archivos, únicamente los módulos con tu propio código. 

Hint: Siempre para estos casos utiliza paths relativos y no absolutos. Para más info, revisa la carpeta de contenidos, el documento sobre los path.

Espero haber resuelto tu duda!

**Comment by IgnacioPorte** [comment]
Hola ! Los ayudantes descargan el syllabus? pregunto esto como con la idea de elegir un path relativo desde el directorio del syllabus
