### ISSUE TITLE
Ayuda para la configuración "máximo de caracteres por linea" del linter `pycodestyle`

### ISSUE THREAD

**Issue by pedroriosg** [IIC2233/syllabus#31]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola! ✌️ 

Les traigo una ayuda para poder configurar de mejor manera el `linter` `pycodestyle` instalado en el `VSCode`.

El `linter` `pycodestyle` por defecto, les va a avisar cuando una línea de su código exceda los **79** caracteres. Sin embargo, para los efectos de este curso y de acuerdo a la guía de estilo que usaremos, es necesario que el `linter` nos avise cuando la línea exceda los **100** caracteres.

Para configurar `pycodestyle` de manera que nos avise cuando excedamos de **100** caracteres deben seguir los siguientes pasos.

**1.** Abrir `VSCode` y presionar `Ctrl + Shift + P` (`Cmd + Shift + P` en `MacOs`)
**2.** Escribe en el buscador `json` y selecciona la opción que dice `Preferences: Open Settings (JSON)`. Se les va a abrir un archivo con extensión `.json`, que contiene en él un diccionario.
**3.** Debajo de la línea que dice `"python.linting.pycodestyleEnabled": true,`, deben copiar lo siguiente: `"python.linting.pycodestyleArgs": ["--max-line-length=100"],`.
**4.** Deben guardar los cambios realizados en el archivo.

Se debería ver de la siguiente manera:

<img width="535" alt="Captura de Pantalla 2021-03-23 a la(s) 16 29 14" src="https://user-images.githubusercontent.com/69609154/112206642-eaa69980-8bf4-11eb-8d84-485a6c06ef82.png">

Con eso, tendrán el `linter` configurado con el máximo de caracteres por línea permitido.

Espero que les sirva!

**Comment by Rerro-r** [comment]
¿Cómo hago para configurarlo si no me aparece las líneas que mencionas? Esto es lo que me aparece en el archivo y sí tengo instalado el `pycodestyle` .

![duda linter](https://user-images.githubusercontent.com/80787908/112540949-8d941a80-8d91-11eb-800d-43a3450ec729.png)

Ayuda porfis 😭

**Comment by pedroriosg** [comment]
Hola @Rerro-r ✌️ 

Prueba copiando debajo de la línea que dice `workbench.....` lo siguiente:

`"python.linting.pycodestyleEnabled": true,`
`"python.linting.pycodestyleArgs": ["--max-line-length=100"],`

tal como mostré en la foto más arriba!
Avísame si te funciona

**Comment by Rerro-r** [comment]
Gracias @pedroriosg 😄, ahora sí pude configurarlo. Ahora me avisa en la parte de problemas si me excedo de las 100 lineas. Tengo una última duda, me habían contado que uno puede poner esa línea visible en la parte del código, ¿esa es una configuración aparte?

**Comment by tamyhan** [comment]
Hola! Qué hago si cuando abro el archivo .json está vacío?

**Comment by pedroriosg** [comment]
Hola @tamyhan ✌️ 

Copia las siguientes líneas en diccionario:

`"python.linting.pycodestyleEnabled": true,`
`"python.linting.pycodestyleArgs": ["--max-line-length=100"]`

Se debería ver de la siguiente forma:

`{
         "python.linting.pycodestyleEnabled": true,
         "python.linting.pycodestyleArgs": ["--max-line-length=100"]
}`

Avísame si te funciona. Saludos!

**Comment by tamyhan** [comment]
Creo que todavía no me funciona, ahora me aparecen más lineas, y lo agregue debajo de la que dice workbench… pero no me funciona.

**Comment by pedroriosg** [comment]
Puedes subir una foto con las lineas de tu archivo?

**Comment by tamyhan** [comment]
![image](https://user-images.githubusercontent.com/71773541/113007575-b67b2d80-914c-11eb-8c62-f25e4b22aab2.png)
