### ISSUE TITLE
Duda respecto a dcciudad en Menú

### ISSUE THREAD

**Issue by elneitans** [IIC2233/Syllabus#31]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda 

Al correr dcciudad.imprimir_red en main.py (creación del menú), luego de imprimir la red me aparece el siguiente error: File "dcciudad.py", line 26, in imprimir_red
TypeError: 'RedMetro' object is not iterable. 

No entiendo a qué se puede deber, por lo que cualquier ayuda lo agradezco mucho.

**Comment by pedrozavalat** [comment]
Hola @elneitans !

¿Podrías subir tu código a tu repositorio personal de la tarea para poder ver con mayor detalle el error?

Saludos! 😄

**Comment by elneitans** [comment]
Hola Pedro, primero que nada te agradezco mucho la pronta respuesta. Ahí lo subí a mi repositorio, red.py y main.py. Además, abusando un poco de tu amabilidad, te quería pedir si podías revisar también la opción 2 y 3 del menú, ya que estoy teniendo problemas que no tengo idea por qué ocurren (tengo la sospecha de que algo en red.py no está bien aunque corre todos.tests.py bien). 
Muchísimas gracias de antemano!!

**Comment by elneitans** [comment]
Además te quería avisar @pedrozavalat que aún no comienzo a escribir el README y no realizo la limpieza de estilo aún. Cualquier cosa estoy atento, y gracias de nuevo.

**Comment by pedrozavalat** [comment]
Hola @elneitans !

Respondiendo a la pregunta inicial, en tu código estas proporcionando a la fúncion `imprimir_red` como primer argumento el **objeto** de la Clase **RedMetro**, cuando debe ser una **lista de listas** (que seria el atributo **red** de esta clase) 😅 . 

Por otra parte, tanto en la opción 2 como 3 de tu menú, estas teniendo errores con respecto a la definición de tus atributos de la clase **RedMetro**. Probablemente, no estas actualizando los **atributos** con los datos entregados en el archivo .txt. 😌

Espero que haya aclarado tu duda, éxito en tu tarea! 😄

Cualquier duda responde esta issue 🧐

**Comment by elneitans** [comment]
@pedrozavalat, pude resolver los problemas. Muchas gracias por los tips!!
