### ISSUE TITLE
Duda sobre bool Congelamiento en plantas.txt

### ISSUE THREAD

**Issue by ByDati** [IIC2233/Syllabus#310]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, tenia la duda si es que los valores que se nos van a entregar dentro del archivo siempre van a ser "0" o "1" como se muestra en el ejemplo, porque como se indica  en el enunciado que se respeta el tipo, también nos podrian pasar un "True" o "False"?
![image](https://github.com/user-attachments/assets/b58fe3cc-fa96-4384-872b-62f27cbfdc6f)
![image](https://github.com/user-attachments/assets/b762d4c9-520f-4e2a-a7d4-65e945ca8869)

**Comment by AndreaVict** [comment]
Holaa, te recomiendo revisar la issue #243, ya que allí se menciona algo similar. Quedo atenta a cualquier duda.

**Comment by ByDati** [comment]
graciaas, si la había visto, pero me quedaba la duda de si aparte de este ejemplo, nos podrían pasar literalmente un "True" o un "False" dentro del archivo por la transformación de datos str a lo necesario, como para evitar que se me caiga el programa de la manera que lo estoy haciendo ahora
Saludos!

**Comment by AndreaVict** [comment]
Entiendo, en ese caso los únicos valores válidos para la congelación van a ser el "0" y el "1" los cuales se interpretan como se dice en la issue mencionada anteriormente. Saludos!!
