### ISSUE TITLE
Error: QPixmap::scaled: Pixmap is a null pixmap

### ISSUE THREAD

**Issue by mmsaavedra1** [IIC2233/Syllabus#310]
Estaba testeando el ingreso de las piezas cuando se rotan, y me surgió el error "QPixmap::scaled: Pixmap is a null pixmap"

A que se debe?😰
![captura de pantalla 2017-09-15 a la s 18 44 54](https://user-images.githubusercontent.com/23617087/30504613-3f2d9f48-9a46-11e7-9791-a54eedac6d62.png)

(https://user-images.githubusercontent.com/23617087/30504607-2ec63ade-9a46-11e7-9bb2-5579f3ec98d8.png)

**Comment by mmsaavedra1** [comment]
Sep 15 18:52:49  Python[2428] <Error>: CGContextSetFillColorWithColor: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 15 18:52:49  Python[2428] <Error>: CGContextSetStrokeColorWithColor: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 15 18:52:49  Python[2428] <Error>: CGContextGetCompositeOperation: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 15 18:52:49  Python[2428] <Error>: CGContextSetCompositeOperation: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 15 18:52:49  Python[2428] <Error>: CGContextFillRects: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 15 18:52:49  Python[2428] <Error>: CGContextSetCompositeOperation: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.


Se le sumó ese error

**Comment by iqacevedo** [comment]
Hola se ha mencionado en otras issues.

Lo más probable es que sea porque le entregas una pieza que no se encuentra en los tipos de pieza a nueva_pieza.

Saludos !
