### ISSUE TITLE
Deshacerme de "documentos en rojo" en git status

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2233/syllabus#310]
Hola. Que en el fondo cada vez que en mi terminal uso git status, además de los documentos que agregue con 'git add', me aparecen una serie de documentos que por alguna razón no he subido. El problema es que estos se van a acumulando y quisiera saber cual es la forma de deshacerme de ellos y que dejen de aparecer cada vez que hago git status. ¿Existe algún comando para que no me aparezcan estas cosas?

![Captura de Pantalla 2020-04-07 a la(s) 14 16 23](https://user-images.githubusercontent.com/48482564/78704931-aedacd00-78da-11ea-8320-354b4bcdfaa3.png)

**Comment by JosefaPaz** [comment]
¡ Hola @raimundomartinez !

Estos archivos eliminados son del repositorio syllabus? Si es así, intenta hacer un ```git pull``` a la carpeta, a ver si así se actualiza completamente y te dejan de aparecer :)

**Comment by raimundomartinez** [comment]
Hola @JosefaPaz. No son del syllabus. Creo que son documentos que alguna vez les hice git push, luego los elimine de esa carpeta, y de ahí hice git push en la misma carpeta (sin estos documentos). No puedo estar seguro, pero creo que de ahí vienen. De todos modos, hice recién lo que me recomendaste y sigo con el mismo problema :/

**Comment by JosefaPaz** [comment]
Entonces el problema es que no se removieron de tu repositorio en github. Tienes dos opciones:

- Usar el comando ```git  checkout _nombre_del_archivo``` para descartar los cambios en la carpeta donde eliminaste el archivo. (Es decir, no eliminarlos)
- Usar el comando ```git rm _nombre del archivo_``` para que también el archivo se elimine en tu repositorio de git.

Después de esto te recomiendo hacer git status y si todo te parece correcto, hacer git push
