### ISSUE TITLE
Re-corrección tarea y líneas a cambiar de código.

### ISSUE THREAD

**Issue by NicoMeyer** [IIC2233/syllabus#310]
Hola! 
Respecto al anuncio publicado sobre las recorrecciones de las tareas no me quedó claro si la fecha máxima del 19 de septiembre corresponde a la Tarea 0 o bien a la Tarea 1. 
La otra pregunta es como se tendría que hacer en el caso de la Tarea 1 si queremos optar a cambiar líneas de nuestro código respetando el máximo . ¿Se debe hacer una mención en el Readme o se llena un formulario aparte?

**Comment by entamburini** [comment]
Hola Nico,

La fecha corresponde para la Tarea 0. El form de recorrección para la Tarea 1 es **después** de la corrección de esta (si no, no se llamaría "recorrección" :roll_eyes:) 

Recuerda que el readme es para facilitar la corrección del ayudante en tu tarea. La instancia de cambiar líneas de código es para la recorrección y conlleva la penalización mencionada en el anuncio y el formulario. 

¡Saludos! :v:
