### ISSUE TITLE
Impacto de Kamikazes

### ISSUE THREAD

**Issue by quememo** [IIC2233/syllabus#310]
Tengo una duda acerca de la condición de que un enemigo Kamikaze explote, en particular en el enunciado se indica:

![image](https://user-images.githubusercontent.com/48305214/58005634-1960ff80-7ab4-11e9-8c25-2e4249949088.png)

Y más abajo aparece:

![image](https://user-images.githubusercontent.com/48305214/58005668-28e04880-7ab4-11e9-9140-e558872b2aee.png)

Por lo que según estas 2 indicaciones, **únicamente** cuando un Kamikaze **intentara moverse** hacia una ubicación donde existe una torre (fuera del camino) y no le fuera posible, explotaría destruyendo la torre (posibilidad dentro de un movimiento aleatorio en su recorrido), haciendo posible que un Kamikaze pase por al lado de una torre sin explotar y siguiendo su camino hasta la base (ignorándola, ya que es una posibilidad dentro del movimiento aleatorio), sin embargo unas líneas más abajo, aparece:

![image](https://user-images.githubusercontent.com/48305214/58005796-78267900-7ab4-11e9-9def-b65c05a76a0c.png)

Lo cual implicaría que inmediatamente al entrar a una casilla adyacente a una torre, este explotaría, evitando que sea posible ignorarla (siempre la explotará si queda en una casilla adyacente), lo cual es contradictorio.

Cual de las 2 situaciones hay que considerar como correcta?

**Comment by gatochico** [comment]
Hola! El segundo caso que mencionas es el correcto, donde la explosión se produce cuando entra en una casilla adyacente a la torre o base de forma automática. Lamentamos la confusión! 😿

**Comment by quememo** [comment]
Gracias!

**Comment by FelipeCampbell** [comment]
> Hola! El segundo caso que mencionas es el correcto, donde la explosión se produce cuando entra en una casilla adyacente a la torre o base de forma automática. Lamentamos la confusión! 😿

Hola :), no me queda claro como se aplica esto para el caso de los enemigos normales. Es decir los enemigos normales también le hacen daño a la base al entrar en una casilla adyacente o solamente cuando colisionan con esta (si fuera el caso de casilla adyacente podrían atacarla en diagonal que sería un poco raro)

**Comment by gatochico** [comment]
Los enemigos normales dañan a la base automáticamente cuando se encuentran adyacentes a esta! Para evitar dudas, las casillas diagonales a un objeto (las "esquinas") no deben ser consideradas como adyacentes y así no ocurre ese ataque en diagonal que mencionas. Toma como "adyacente" como que deben compartir un lado (: 
Saludos!
