### ISSUE TITLE
Subir/modificar README fuera de plazo

### ISSUE THREAD

**Issue by agustinmonti1** [IIC2233/syllabus#310]
Se puede hacer una modificacion al readme hoy?

**Comment by Drpinto1** [comment]
¡Hola!

Los `README` se recolectan en la fecha y hora indicada, sin embargo es posible que hacer cambios y, sobre todo, subir tu `README` si no lo hiciste, sea beneficioso para ti.

### Subir tarde el README

Si olvidaste subir tu `README`, el corrector de tu tarea notará que este no está en la carpeta recolectada y aplicará el descuento que corresponde, sin embargo antes de seguir corrigiendo, el ayudante revisará si este documento está en tu repositorio (subido fuera de plazo) y de ser así lo seguirá para entender mejor tu tarea.

Si bien esto no anulará el descuento y no te permitirá optar al "des-descuento" asociado al `README` lo más probable es que su existencia tenga un impacto positivo en tu nota, pues el ayudante entenderá mejor tu solución a la tarea.

Por lo anterior, si olvidaste subir tu `README` **es altamente recomendado que lo subas, aunque sea después de la entrega.**

### Hacer cambios al README

Sobre las modificaciones al `README`, esto funciona ligeramente distinto, ya que al momento de hacer la revisión el ayudante encontrará que este documento ya existe en la versión recolectada de tu repositorio, por lo que es **poco probable** que tus cambios sean vistos.

Dicho esto, si el ayudante corrector de tu tarea encuentra un error importante en tu código, es posible (aunque muy poco probable) que revise tu repositorio para verificar si hubo un cambio en el `README`.

Por lo anterior, **si quieres modificar tu `README`, puedes hacerlo** (y no pierdes nada), **pero es muy poco probable que esos cambios sean tomados en cuenta para la revisión.**

¡Saludos!

**Comment by sbcorrea** [comment]
Hola! Respecto a eso, yo en mi README reportaba un bug en los menús que afecta fuertemente el flujo de mi código. Como una hora después de la recolección del README, me di cuenta que todo el bug se arreglaba con un solo `return`. En ese caso, ¿yo no puedo modificar mi README para hacer un **cambio de línea atrasado**, o sí? En ese caso, ¿me harían un superhiper descuento potenciado entre cambio de línea y atraso, o qué onda?
Graciassss
