### ISSUE TITLE
Canal.ingresar_barco() duda al reingresar algun barco

### ISSUE THREAD

**Issue by maurobsp** [IIC2233/syllabus#311]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
En el enunciado dice que, podemos volver a ingresar un barco que ya salió del canal, tengo la duda si ese barco, vuelve a poder ejecutar su evento especial y que pasa con su carga. primero en el caso de que su carga fuera robada por piratas, al volver a ingresar el barco entra sin nada de carga, o vuelve a tener la carga del archivo barco.csv, y  segundo en caso de que este no fuera robado que pasa con las fechas de expiración de sus productos, estas vuelven a contar desde que entra , o toma en cuenta el tiempo que estuvo en el canal la primera vez y lo que lleva en el canal en su segunda entrada.

**Comment by DomingoCarvajal** [comment]
Hola @maurobsp.

Puedes considerar que todo lo relacionado al barco se reinicia una vez este ingresa al canal.
