### ISSUE TITLE
Funcion asignar

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#311]
Si uno asigna un comando a una función ¿Siempre será el resultado de la función? ¿Puede uno asignar un comando como función y convertir la variable en un comando?

**Comment by Hernan4444** [comment]
@jorgeriesco por como está en el enunciado puede ser el resultado de una consulta, por ejemplo de `crear_funcion` y por lo tanto ahora esa variable es una función que se puede evaluar en un rango, puede ser un valor fijo, una columna para poder operar, un string que coincide con el nombre de un comando, entre otros. pero siempre será algo fijo que no pueda cambiar, solo ser sobrescrito
Lo siguiente sería totalmente valido (en relación a los string)

["asignar", "x", "PROM"]
["x", [1,2,3]]
["asignar", "x", "VAR"]


Eso debería guardar en "x" el string "PROM", luego calcular el promedio de la lista [1,2,3] y finalmente dejá en "x" el string "VAR"

Saludos!!
