### ISSUE TITLE
 Verifica que se retorne los votantes cuando se manejan grandes datos.

### ISSUE THREAD

**Issue by nicolettadegoye** [IIC2233/Syllabus#311]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

al hacer el TestCiudadesDistritos.test_7 me aparece el error:

        Verifica que se retorne los votantes cuando se manejan grandes datos.

a que se refiere? porque la función del enunciado solo dice que retorne las provincias. 

Verifica que retorne los nombres de las provincias cuando existen dos distritos del mismo nombre en provincias distintas.
         ... ok
test_5 (__main__.TestCiudadesDistritos.test_5)

         Verifica que se retorne los votantes cuando se manejan pequeños datos.
         ... FAIL
test_6 (__main__.TestCiudadesDistritos.test_6)

        Verifica que se retorne los votantes cuando se manejan medianos datos.
         ... FAIL
test_7 (__main__.TestCiudadesDistritos.test_7)

        Verifica que se retorne los votantes cuando se manejan grandes datos.
         ... FAIL

**Comment by tcapom** [comment]
Hola @nicolettadegoye !

El texto al que haces referencia efectivamente está incorrecto, en el sentido que debería decir `nombres de provincias` en vez de `votantes`. 

De cualquier manera cuando tengas este tipo de dudas, siempre puedes revisar el contenido que tienen los tests. Tomando el ejemplo del `test_05`, el `expected_output` que tiene es de `CIUDADES_DISTRITOS_S`. buscando `CIUDADES_DISTRITOS_S` en el archivo `test_solution`, podrás encontrar lo siguiente:

`CIUDADES_DISTRITOS_S=[' Arica', ' Parinacota', ' Iquique', ' El Tamarugal', ' Tocopilla', ' Antofagasta', ' El Loa', ' Chañaral', ' Copiapó', ' Huasco', ' Choapa', ' Elqui', ' Limarí', ' Isla de Pascua', ' Los Andes', ' Petorca', ' Quillota', ' San Antonio', ' San Felipe de Aconcagua', ' Valparaiso', ' Chacabuco', ' Cordillera', ' Maipo', ' Melipilla', ' Santiago', ' Talagante', ' Cachapoal', ' Cardenal Caro', ' Curicó', ' Cauquenes', ' Linares', ' Talca', ' Arauco', ' Biobío', ' Concepción', ' Diguillín', ' Itata', ' Punilla', ' Cautín', ' Malleco', ' Valdivia', ' Ranco', ' Chiloé', ' Llanquihue', ' Osorno', ' Palena', ' Aysén', ' Capitán Prat', ' General Carrera', ' Antártica Chilena', ' Magallanes', ' Tierra del Fuego', ' Última Esperanza']`

Este resultado se trata justamente de nombres de provincias

**Comment by nicolettadegoye** [comment]
es raro porque si retorno el nombre de las provincias 

usando este codigo en consultas.py para comprobar:
```
generador = list(cargar_datos("distritos", "s"))
a = ciudades_distritos(generador)
for elem in a:
    print(elem)
```
y este es mi output:
```
C:/Users/Nicoletta/AppData/Local/Programs/Python/Python311/python.exe c:/Users/Nicoletta/Desktop/nicolettadegoye-iic2233-2024-1/Tareas/T3/consultas.py
 Arica
 Parinacota  
 Iquique     
 El Tamarugal
 Iquique     
 Tocopilla   
 Antofagasta 
 El Loa
 Tocopilla
 Chañaral 
...
```
y me aparece fail :(

**Comment by tcapom** [comment]
Hola @nicolettadegoye !

Si no hay problema con acceder al nombre de las provincias, entonces sí deberías ser capaz de poder hacer la consulta. Recuerda que el ejercicio pide que no haya repetición de nombres.
