### ISSUE TITLE
Implementación sort sobre lista

### ISSUE THREAD

**Issue by Regenschrim** [IIC2233/Syllabus#311]
Al implementar el método sort en nuestras listas, ¿bajo que argumento debe ordenar? Ya que dependiendo de si tenemos string, int u objetos (no estoy seguro si estos últimos son ordenables); el orden será distinto. Además, por lo que estuve viendo, una lista de python no permite mezclar tipos de variables al momento de ordernar.

Gracias!!

**Comment by cilopez** [comment]
Bajo el argumento que te parezca más necesario, como son tus propias estructuras, es ideal que resuelvan los problemas que surgen dentro de tu tarea. Si necesitas con urgencia ordenar strings por sobre números, ordenalos bajo ese criterio.
