### ISSUE TITLE
Monedas iniciales

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#311]
Hola, puedo hacer que el usuario empiece con una cantidad incial de monedas? De otra forma, el jugador no podría colocar torres en la ronda inicial y el juego se estancaría. Saludos

**Comment by gatochico** [comment]
Hola! Puedes hacer eso, pero recuerda siempre **incluirlo en tu README** y hacer que la cantidad de monedas que quieras entregar esté regida por un parámetro dentro de parametros.py . Éxito programando! 💻
