### ISSUE TITLE
NO se sube mi Readme

### ISSUE THREAD

**Issue by dpvillarroel** [IIC2233/syllabus#311]
Hola! 
Tengo mi Readme actualizado en el computador, pero cuando hago commit dice que no se han hecho cambios. Entonces al hacer push no se sube nada a git, como si el archivo aun estuviera vacío!

**Comment by jmwielandt** [comment]
Hola!

¿Qué te dice si haces `git status`?
Además, ¿qué tienes en tus .gitignore?

Saludos~
