### ISSUE TITLE
Asignación de argumentos a clases con herencia usando *args

### ISSUE THREAD

**Issue by tcouso** [IIC2233/syllabus#311]
Hola! Revisé el ejemplo final del notebook de multiherencia, donde se usan `**kwargs` para distribuir los argumentos a las respectivas clases, y me surgió la duda de si era posible implementar las mismas funciones con `*args`. Sin embargo, al intentar implementarlo, me percaté de la tupla `args` perdía argumentos en la medida en que la imprimía una clase de mayor jerarquía, de modo que finalmente quedaba vacía y arrojaba un `IndexError` al intentar asignar un atributo a la clase de mayor jerarquía.
¿Qué estaba pasando en este caso en que la tupla perdía argumentos? ¿Cómo sería una implementación correcta?

Gracias de antemano.

¡Saludos!

**Comment by tcouso** [comment]
Lo aclaré por mi cuenta al final, todo super!

**Comment by Baelfire18** [comment]
Genial! Cualquier cosa no dudes en preguntar

**Comment by camirojasguajardo** [comment]
Hola! yo tengo esa misma duda, pero aun no la he resuelto jiji me podrían decir cómo sería una implementación correcta con *args en ese caso?
saludos!

**Comment by tcouso** [comment]
@camirojasguajardo Hola! Yo lo hice asignando a los atributos de las clases diferentes elementos indexados de la tupla 'args'. Dejé *args como único argumento de las clases, y luego instancie entregando argumentos en un orden definido, de manera que luego podía igualar cada atributo a args["índice numérico que contiene el valor del atributo"]. Mañana te puedo compartir el codigo si se entendió muy poco.

Saludos!!
