### ISSUE TITLE
Colocar elementos en modo constructor

### ISSUE THREAD

**Issue by pulpaulaa** [IIC2233/Syllabus#311]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, estoy desarrollando el modo constructor y me entró la duda de cómo deben ser algunos aspectos de la interacción apretar un elemento y colocarlo en el mapa. En primer lugar, ¿qué pasa si apreto, por ejemplo, a Luigi y en vez de colocarlo en el mapa decido apretar el botón de pared? ¿Debería salir una alerta/mensaje diciendo que aún no pones a Luigi? ¿O por otro lado, debería 'devolverse' el Luigi a su botón (la cantidad vuelve a ser 1) y tomas una pared en su lugar?
Segundo, ¿Al apretar un elemento debe actualizarse de inmediato la cantidad? ¿o se debería actualizar la cantidad una vez que está puesto en el mapa?
Me imaginé que si no sale en el enunciado es libre pero preferí preguntar por acá por si acaso (perdón si se me pasó algo del enunciado).

**Comment by Hellonston** [comment]
Hola **pulpaulaa**!
En ambos casos, la decisión está en tus manos, siempre y cuando sea consistente con los demás puntos del enunciado. A mi parecer, sería más apropiado actualizar la cantidad una vez que el elemento haya sido ubicado en el mapa :)
