### ISSUE TITLE
Que es lo que me indica el tablero que se ocupará del archivo jardines.txt?

### ISSUE THREAD

**Issue by CJoost27** [IIC2233/Syllabus#312]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, no me queda claro cuál de todas las líneas será usada para crear el tablero, entiendo que existen diferentes tableros (5x5 vacío, 4x3 defensivo, entre otros) pero estoy confundido porque en la seccion 3 del enunciado se habla de nombre_jardin y nombre_dificultad. Ese nombre_jardin es el que me indica cual tablero será usado durante todo el juego?

**Comment by diegoftpxd** [comment]
Hola! efectivamente nombre_jardin debe ser un nombre válido para los tableros que se presentan en tableros.txt e indica que tablero debe cargarse al comienzo de la partida.
En el fondo, al iniciar el programa con una linea similar a "py main.py 4x3_defensivo fácil" tu código debe cargar el tablero indicado como tablero inicial y ocupar las variables correspondientes a la dificultad fácil. No sé si esto es claro.

**Comment by CJoost27** [comment]
Muchas gracias, me quedo claro.
