### ISSUE TITLE
Definir atributos en multiherencia

### ISSUE THREAD

**Issue by stephenwpugh** [IIC2233/syllabus#312]
Hola! al final del contenido 2 (multiherencia), para definir los atributos del `init` de cada objeto, usan por ejemplo: `def __init__(self, area='', **kwargs)`. Sería lo mismo definir area inicialmente como `area=None`? lo he visto en otros lados, pero no sé si es mala práctica o alguno está más correcto que otro. 
Muchas gracias!

**Comment by dchahuan** [comment]
Como python una variable puede tener varios tipos de datos, no creo que haga ni una diferencia. Pero la gracia de poner el "" o poner 0 a diferencia de None. Es que si no la cargas y la usas en un método no se te va a caer el código. Pero enverdad da lo mismo
