### ISSUE TITLE
Aclaración parámetros.py: parámetros hardcodeados

### ISSUE THREAD

**Issue by milosoria** [IIC2233/syllabus#312]
A qué se refiere con lo siguiente "Finalmente, cualquier parámetro que se encuentre `hardcodeado` dentro de tu código, también conllevaría a un descuento."?

**Comment by matiasmasjuan** [comment]
Hola @milosoria !

El término *hardcodeado* hace referencia a la **mala práctica** de escribir un mismo texto de código **sucesivamente** cuando podría  utilizarse un **parámetro** externo para referenciarlo.
Por ejemplo:

* Si en tu código necesitas abrir un archivo constantemente,```with open(carpeta/archivo.ext)```, y realizas varías veces esa misma línea. ¿Que pasa si en un momento tienes que cambiar la **ruta** de ese archivo? Eso implicaría que por cada línea, tendrias que cambiar manualmente cada una de las rutas, lo que puede ser tedioso y muy consumidor de tiempo. En cambio, si antes de ingresar la ruta, tu defines un **parámetro** llamado: ```RUTA = carpeta_2/archivo.ext``` y abres los archivos de la forma: ```with open(RUTA)``` si llega un momento en donde debes cambiar la **ruta**, basta con cambiar el parámetro **RUTA** y se acaba el problema.

Todos estos parámetros que se encuentren escritos **manualmente** en lugar de ser definidos externamente y ser llamados, es lo que se conoce como *hardcodeo*, y es justo lo que queremos evitar en esta tarea.

Finalmente, si quedaron dudas al respecto, puedes revisar [este link](https://es.wikipedia.org/wiki/Hard_code).

Mucho éxito con tu tarea!
