### ISSUE TITLE
Tamaño final base da datos?

### ISSUE THREAD

**Issue by akrebs2** [IIC2233/Syllabus#312]
Al momento de revisar, de qué tamaño será la base de datos? Si bien han dicho que por mientras trabajemos con la base pequeña de 200 jugadores, no sabemos con cuántos jugadores va a ser probado nuestro código. Esto lo pregunto porque, se dice que nuestro programa debería funcionar para un mínimo de 200 jugadores (o 16 equipos). Si yo asumo que la base de datos final es de, por ejemplo, 1600 jugadores, mi programa (hasta ahora) sólo le entregará 200 jugadores a Demo.py. Entonces ese número mínimo en mi programa está pasando a ser un número fijo (no sé si habrá un problema con eso). Por otro lado, al elegir 200 jugadores, de un total mayor.. cómo sabemos si este subconjunto será conexo? La base chica que nos entregaron es conexa, pero no se puede asegurar eso para subconjuntos aleatorios de una base más grande (me explico?). Por favor aclarar ese tema, porque no sé para qué tipo de "lógica" debe estar preparado mi programa. Y lo último, por favor responder la issue #288, nos tiene acomplejados a varios. Gracias!

**Comment by cilopez** [comment]
Nosotros probaremos con un grupo convexo que puede ir entre 200 a 1600 jugadores,  podrías preguntar un número de jugadores antes de que parta la GUI o dejar simplemente 200, no existirá problema alguno si señalas en tu `README` como lo tratas.
