### ISSUE TITLE
Extraer columna

### ISSUE THREAD

**Issue by fdominguezclaro** [IIC2233/Syllabus#312]
Podría asumir que en extraer_columna, el nombre de la columna va a ser el nombre completo? Por ejemplo, la primera columna de encuesta_uno es: 'familiares_muertos: int'

**Comment by Hernan4444** [comment]
@fdominguezclaro no puedes asumir eso, el `: int` es parte del formato csv para indicar el tipo de dato, no se considera como nombre de la columna.

Saludos!

**Comment by fdominguezclaro** [comment]
Y puedo asumir que va a ser el resto entero? es decir, 'familiares_muertos' y no 'familiares'

**Comment by Hernan4444** [comment]
@fdominguezclaro  te recomiendo leer de nuevo el enunciado en la parte de posibles errores, ahí está la respuesta c:

Saludos!

**Comment by fdominguezclaro** [comment]
Si lo leí, pero a lo que voy es que para considerar el nombre de la columna correcto, tiene que ser el nombre completo sin el :int ?

Puede ser un poco básica la pregunta pero es para salir de dudas nomás...

Gracias!

**Comment by Hernan4444** [comment]
si, tiene que ser exactamente igual, sino se genera error porque se está buscando una columna que no existe.

Saludos
