### ISSUE TITLE
Programación circular

### ISSUE THREAD

**Issue by bpeirano1** [IIC2233/syllabus#312]
Si es que en mi frontend instancio una clase Tablero que contendría el mapa de mi backend, puedo yo posteriormente instanciar una clase X en el frontend, que reciba a la instancia Tablero y que desde esta instancia X también pueda modificar a Tablero, estaría bien esto? no sería programación circular verdad?

**Comment by Hernan4444** [comment]
Hola, primero aclarar que esto es "modelación circular o referencia circular", no existe programación circular (ya corregimos descuentos.md para no usar ese termino que estaba mal).

Ahora con tu duda, no hay problema con eso. La referencia circular es cuando clase X tiene guardada una refrencia a la clase Z y la clase Z tiene una referencia a la clase X, pero dado lo que tu comentas, estás haciendo.
* Clase X_1 de FrontEnd tiene referencia a la clase Tablero
* Clase X de FrontEnd (Con X != X_1) tiene referencia a la clase Tablero.

Mientras Tablero no tenga ninguna referencia a la clase X_1 o X, todo está bien.

### Adicional

Cuidado con la transitividad. Si Clase X tiene referencia a Clase Y, Clase Y tiene referencia a Clase Z y Clase Z tiene referencia a X, entonces también se está realizando referencia circular, pero de largo 2, lo cual sigue estando mal modelado.

Saludos :v:
