### ISSUE TITLE
\ufeff

### ISSUE THREAD

**Issue by F-arellano** [IIC2233/syllabus#312]
estaba haciendo una funcion para que me retorne lineas de un archivo como namedtuples, y decidi testearlo con los archivos de la tarea. al probarlo con pistas.csv funcionaba perfectamente pero al intentarlo con pilotos.csv añadia "\ufeff" al principio del texto (leyendo el archivo con encoding = "utf-8"), y al parecer es un string restringido y no lo puedo asignar al campo de nombres de la namedtuple. ¿esto es comun que pase o algo esta mal con el archivo? o sea, ¿debo asumir que podria pasarme en otros archivos de tareas posteriores?

**Comment by benjastraub** [comment]
Eso es un [BOM](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8), que al fin y al cabo es un indicador del _encoding_ que tiene el archivo.  Podrías probar usando _encoding_ `utf-8-sig` para solucionarlo.

Por otro lado podrías intentarlo con el archivo original y ver si también pasa. Porque hay editores de texto en los que si editas el archivo con ellos agregarán el BOM. Tal vez por eso ocurrió en primer lugar.

**Comment by jmwielandt** [comment]
Hola @F-arellano !

Lo que dice tu compañero es correcto. Si buscas `utf-8-sig` en el buscador de las issues deberías poder ver las otras donde esto fue tratado. Dependiendo de cuándo veas esto, es posible que estén en la pestaña de cerradas, al ser de la tarea 1.

Saludos!
