### ISSUE TITLE
if y else en reduce().

### ISSUE THREAD

**Issue by VicenteIgnacioSotoGonzalez** [IIC2233/Syllabus#312]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, dentro de una función lambda en un reduce se pueden hacer operaciones condicionadas por un if o elif? Por ejemplo sumar dos elementos si se cumple x condición, etc.

Por otro lado, en una función lambda dentro de un reduce puedo convertir uno de los parámetros en alguna estructura, ya sea list(), etc? Por ejemplo lambda elemento: [elemento]

Gracias de antemano!

**Comment by TomasGMDC** [comment]
@VicenteIgnacioSotoGonzalez sobre el primer punto, sí se puede. Sobre el segundo, también se puede. El enunciado dice que se puede cambiar una estructura de datos aplicando comprensión o dentro de un reduce().

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Perfecto, muchas gracias! Última duda, es válido usar alguna estructura de datos como lista vacía para iniciar el reduce?

**Comment by Yeps3nM** [comment]
Hola! no me queda claro lo del cambio de la estructura de los datos, el problema con usar el list() sería si encapsula al reduce en vez del reduce a list() ?  
Gracias!

**Comment by TomasGMDC** [comment]
@VicenteIgnacioSotoGonzalez en el disclaimer del enunciado se menciona que sí se puede, así que sí.

**Comment by TomasGMDC** [comment]
@Yeps3nM sobre lo primero, sí, si list() está dentro de reduce(), se puede usar. Si no, no se puede usar, esto en la parte de consultas.
Sobre el segundo punto, el disclaimer es para la parte de consultas solamente, así que se podría usar para la parte de cargar datos.

**Comment by VicenteIgnacioSotoGonzalez** [comment]
> @VicenteIgnacioSotoGonzalez en el disclaimer del enunciado se menciona que sí se puede, así que sí.

Perfecto, gracias!
