### ISSUE TITLE
Como abrir ventana RQL 

### ISSUE THREAD

**Issue by andreslyon** [IIC2233/Syllabus#313]
Tengo instalado PyQt5, pero cuando ejecuto main.py no se abre la ventana (o se dice Gui?) de Rql.
No sale ningún error ni nada. Hay que modificar algo en el main? o se debería abrir siempre?.
Gracias

**Comment by iqacevedo** [comment]
Hola!
Al ejecutar main.py se debería abrir la interfaz de RQL en otra ventana.
Python te señala algún error ?.
Saludos !

**Comment by andreslyon** [comment]
Hola, nop ninguno. El programa se ejecuta y se cierra

**Comment by iqacevedo** [comment]
Has modificado algo en los archivos? o están tal cual los descargaste?. Podrías intentar descargar la carpeta T03 de nuevo y probar correr main.py para ver si se abre la ventana, el icono de la ventana en la barra de tareas es así : 
![image](https://cloud.githubusercontent.com/assets/13748732/25446637/8623b348-2a88-11e7-84c6-c118c134fca1.png)

**Comment by andreslyon** [comment]
Ok, voy a intwntar eso aunque no he modificado nada, solo copie todos los
archivos en mi repositorio. Gracias
