### ISSUE TITLE
Ejercicio propuesto 3.1 (Semana 3)

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#313]
Hola! 
En el ejercicio deben los 3 métodos con @abstractmethod?

**Comment by tocococa** [comment]
Hola @Margarita-Paz ! En el ejercicio 3.1, como sólo pueden existir hamburgueserías del tipo `HamburgueseriaVegana` y `HamburgueseriaCarnivora`, tu tienes que decidir que método son comunes para ambas, y en base a eso decidir cuáles de los métodos declarados en `Hamburgueseria` deben ir con el decorador `@abstractmethod`, para ser implementados por la clase hija, o ser implementados directamente en `Hamburgueseria`.

Si sigues con dudas o quieres saber más sobre que hace el decorador, por favor responde este mensaje!
