### ISSUE TITLE
Readme atrasado

### ISSUE THREAD

**Issue by Felopo** [IIC2233/syllabus#313]
Hola!
Lo que pasa es que se me olvidó subir el readme el lunes, y quería saber si es que lo subo ahora, como hago para que los ayudantes lo puedan ver?. Para que no se les haga tan difícil la revisión de mi tarea.

**Comment by entamburini** [comment]
¡Hola!

Subelo a tu repositorio en la carpeta correspondiente (en este caso, Tareas/T01) cosa de que a los ayudantes no les cueste corregir la tarea y así evitar que llegues a la recorrección :)

El hecho de no entregarlo a la hora implica un descuento, pero es mejor esto a no entregar nada (igual tendrías ese descuento) y que además dificulte la labor del ayudante ;)

**Comment by Felopo** [comment]
Oka, graciass! :)
