### ISSUE TITLE
Uso de imagenes y sonidos externos e imágenes Fantasma Follower Villain

### ISSUE THREAD

**Issue by Tamarindinho** [IIC2233/Syllabus#313]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! 

Tengo dos dudas:
- Me gustaría saber si está permitido el uso de recursos (imagenes y sonidos) externos a los proporcionados. En particular solo quiero saber si podemos colocar más sonidos e imagenes para enriquecer las interfaces gráficas (para que no sea tan soso). En caso de ser posible, tendríamos que crear una carpeta aparte donde depositemos los archivos para subirla al repositorio, verdad? (siempre y cuando el tamaño de los archivos no sea excesivo, claro está) Esto ya que se menciona en el enunciado, que los archivos de sprites y sounds deben ser ignorados.
- En cuanto al bonus, con el fantasma de follower villain, no hay archivos para su animación en concreto. Se me ocurre quizás, en pantalla si se mueve en horizontal usar los del fantasma horizontal, y si es en vertical, usar los del fantasma vertical, pero es un tanto confuso (no se notará en pantalla que efectivamente cuales son esos fantasmas particulares). ¿Qué hacemos en ese caso para ser consistentes con la animación y con lo visual para el usuario?

**Comment by Maratripa** [comment]
Hola! Sobre el primer punto, tal como fue mencionado en #294, **no** se pueden utilizar recursos externos a los entregados, ya que estos deben ignorarlos en el `.gitignore` y se utilizarán las mismas imágenes para los estudiantes en la corrección.

Sobre el Follower Villain, como no se especifica en el enunciado, pueden utilizar cualquiera de las imágenes entregadas de fantasmas. Si gustas puedes idear algún método para diferenciarlos del resto de los fantasmas, pero no es obligatorio :).
