### ISSUE TITLE
¿Se puede utilizar monkey patching para reescribir el método producir_soles??

### ISSUE THREAD

**Issue by OrianaCrescio** [IIC2233/Syllabus#313]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
En la tarea 2:
¿Se puede realizar esta potenciación usando monkey patching?
Graciias!!

**Comment by CrisDonosoMaass** [comment]
Hola! Sí pueden hacerlo, si hallaste una fuente con como hacerlo recuerda citarlo en tu readme.
