### ISSUE TITLE
Camino Corto

### ISSUE THREAD

**Issue by 96jaime** [IIC2233/Syllabus#313]
Como es falso el grafo del ejemplo en el enuciado, y en verdad solo tiene sentido moverse por las relaciones 0,9 ya que nos cambian de nacionalidad o liga. Puedo hacer la busqueda de afinidad no por un grafo total, sino más bien por las listas de ligas y nacinalidades, restando asi en cada paso 0,1?. Porque la mayor afinidad es el camino más corto , y este contempla unicamente relaciones de 0,9

**Comment by ignaciohermosillacornejo** [comment]
Hola @96jaime 
No te entiendo. A que grafo te refieres que es falso del enunciado? Todos los ejemplos del enunciado son con numeros inventados pero cumplen las mismas propiedades que los de la tarea.
Segundo, dices que "Porque la mayor afinidad es el camino más corto". Te invito a leer el parrafo 5 de la seccion 4.1.1 donde explicitamente mencionamos esto.

**Comment by 96jaime** [comment]
porque no respeta la lógica de las relaciones el gráfico del ejemplo. Si dos jugadores tienen afinidad 1 implica que poseen las misma relaciones con todo el resto del grafo. Si tienen afinidad 0,95, poseen las mismas relaciones de 0,9 con el resto de todo el grafo. Por tanto para unir dos personas que no comparten ni liga ni nacionalidad, hay que moverse por 0,9 que nos cambian de liga o nacionalidad, el resto de las relaciones no "avanzan" en el cambio de nacionalidad o liga

**Comment by Pipelao** [comment]
@96jaime Hola :)
No entiendo lo que dices de que : "Si dos jugadores tienen afinidad 1 implica que poseen las mismas relaciones con todo el resto del grafo", por lo que yo entendí sólo esos do jugadores tienen relación 1 entre ellos, pero el nodo A por darte un ejemplo puede tener afinidad 0.90 con el nodo B, 0,95 con el nodo C y 1 con el nodo D, pero eso es sólo entre ellos no con el resto del grafo.
Saludos.
PD: No soy ayudante

**Comment by 96jaime** [comment]
me refiro: Si A --1 --B    y    B--x--C
esto implica que  A--x--C   para x=1, 0.95, 0.9


Si   A--0.95--B    y    B--x--C
implica que A--x--C para x = 0.95, 0.9

**Comment by santilaguna** [comment]
@96jaime si entiendo bien, lo que mencionas, creo que tiene un solo error. Para el segundo caso, si es que B está conectado con C a través del club solamente, luego C es desconocido para A

**Comment by ignaciohermosillacornejo** [comment]
Hola @96jaime 
Creo que ya entiendo tu duda. 

> Si A --1 --B y B--x--C
esto implica que A--x--C para x=1, 0.95, 0.9

Eso es correcto

> Si A--0.95--B y B--x--C
implica que A--x--C para x = 0.95, 0.9

Eso es incorrecto por dos razones, y deja explicarte por que
1.- Perfectamente puede suceder que 

> Si A--0.95--B y B--x--C, A--x--C para x = 1, 0.95, 0.9

No existe ninguna relación entre la afinidad que tengan A y B con B y C. 

2.- Podría haber un nodo D tal que conecte A--1--D y D--1--C por lo que A--1--C.

Creo que estas pensando mucho la relación entre el grafo, afinidades y nacionalidades. El objetivo de esa parte del enunciado era que ustedes calcularan la afinidad de dos jugadores de una manera mas desafiante que simplemente haberles entregado directamente los valores de afinidad.
