### ISSUE TITLE
Contenido parametros.py

### ISSUE THREAD

**Issue by AgustinZalaquett** [IIC2233/syllabus#313]
En este archivo se que hay que guardar lso paramertros, pero no me queda claro ¿si los print de texto como el de los menus o de cuando se cobran multas tambien tienen que ir en parametros.py? o los podemos poner directamente en el codigo como print("texto")?

**Comment by AgustinZalaquett** [comment]
Tambien si los  textos para guiar el input de cuando de crean magizoologos y criaturas deben estar en parametros.py

**Comment by matiasmasjuan** [comment]
Hola @AgustinZalaquett !

En respuesta a tu pregunta, no. Todos los *prints("texto")* no deben ir en la sección de **parámetros.py**, ya que aquí deben ir aquellas **constantes** que están especificadas en el enunciado en el formato indicado. La idea es que usen este archivo para **importar** los parámetros que son **constantes**, pero que pueden ser modificados en cualquier momento. Un ejemplo de esto es el caso que se dio en el enunciado:

```python
SICKLES_INICIALES = 500
```
En este caso, si se desea cambiar la cantidad de **SICKLES_INICIALES** de un **Magizoólogo** se puede hacer cambiando **ese** parámetro en el archivo **parametros.py**. Pero cambiar los textos que **guían** al usuario a través de los menús no tendría mucho sentido, ya que ha diferencia de **SICKLES_INICIALES**, este último lo tendrás que llamar en **distintas** oportunidades, cosa que no ocurre en los textos de *print()*.

Espero haber respondido a tu pregunta, y mucho éxito con tu tarea!
