### ISSUE TITLE
Al rotar la ficha desaparece

### ISSUE THREAD

**Issue by jadiaz6** [IIC2233/Syllabus#313]
hola, llevo 2 dias intentando arreglar este problema. Al rotar mi pieza todo anda bien, cambia el tipo, solo se agrega al tablero si cumple los requisitos y hace las conexiones con los otros nodos. El problema es que la imagen solo aparece si es tal cual como esta en la carpeta \gui\assets\blue - o - red.

O sea, que al pedir la nueva ficha (la ficha rotada), esta llama a la imagen que está en la carpeta, pero no es capaz de rotarla.

¿Es esto un problema del gui?

**Comment by iqacevedo** [comment]
Hola,

No te sirvió utilizar la nueva función de la gui mencionada en #233?.

Saludos !

**Comment by jadiaz6** [comment]
Ahi si, muchas gracias!
