### ISSUE TITLE
Duda backend/frontend

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#314]
Hola, creo que me estoy complicando demás para modelar mi programa con backend/frontend.

Mi duda es si es que necesariamente cuando hago un click o una accion en el frontend, debe llamar a una clase/funcion en el backend? Que siento que para algunos casos es innecesario: por ejemplo si trato de abrir una ventana, podria directamente conectar dicho boton (que está en el frontend) con el metodo que abre dicha ventana (también en el frontend), en este caso siento que llamar al backend es innecesario. Espero se entienda.

Muchas gracias

**Comment by jaromero6** [comment]
Hola
Como efectivamente dices no siempre es necesario llamar a un método del backend en el frontend. Ten en mente que en el backend tu realizas la lógica del juego. Por lo tanto si tu quieres que por ejemplo al apretar un botón se muestre un mensaje, entonces no es necesario llamar al backend, pero por el contrario si al apretar el botón tu deseas comprobar ciertas condiciones y luego de acuerdo a esto desplegar un mensaje, entonces al apretar el botón deberías llamar al backend que compruebe  esas condiciones y el frontend acorde a la respuesta que reciba del backend muestra un determinado mensaje, ¿Se entiende cuando es necesario y cuando no?

**Comment by VicenteMerino** [comment]
Si, era justo como lo tenía más o menos pensado. Muchas gracias!
