### ISSUE TITLE
instancia locales

### ISSUE THREAD

**Issue by IsidoraCarmona** [IIC2233/Syllabus#314]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

En una instancia de Locales se puede asumir que el largo de la lista de id_votantes es equivalente a la cantidad de votantes que tiene ese local?

**Comment by ClemoAcevedo** [comment]
Hola @IsidoraCarmona !
En el enunciado el punto **3.1.4. Locales** describe **id_votantes** como: _Una list que corresponde a una lista con **todos** los identificadores de los votantes del local._ .  Lo que implica que el largo de esta lista representa la cantidad de votantes que tiene el local. Por lo tanto, es seguro asumir que el largo de la lista id_votantes es equivalente a la cantidad de votantes en ese local.

**Comment by IsidoraCarmona** [comment]
ahh oka, entonces puede estar la posibilidad que haya un error en los test case asociados a la función locales_mas_votos_comunas ? porque los resultados esperados no me hacen sentido y los he probado de varias maneras. Específicamente el test 5, 6 y 7.

**Comment by ClemoAcevedo** [comment]
@IsidoraCarmona puedes hacer push a tu repositorio de la implementación con la que estás trabajando? Para echarle un ojo

**Comment by ClemoAcevedo** [comment]
@IsidoraCarmona Te sugiero que revises el código de los test cases, especialmente los casos que están fallando. Y analiza el orden esperado de los identificadores de los locales en la variable `expected_output` de cada test case. Compara ese orden con el orden de los identificadores que estás obteniendo en tu función `locales_mas_votos_comuna`.
