### ISSUE TITLE
Ejercicio propuesto 3.1, Semana 3

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#314]
Hola,  en la clase  "Hamburgueseria" deje la función numero_clientes sin @abstractmethod ya que esta funcion es igual para todas las subclases. Luego en las subclases definí dicha función como:

def Foo(self):
      super().Foo()

Sin embargo, al momento de ejecutar la función, me retorna "None". Cómo lo puedo solucionar?

**Comment by tocococa** [comment]
Hola @En-clases ! Es probable que el _return_ extra se deba a que estás instanciado dos veces el método `numero_clientes` (en la hamburguesería y en sus hijas al hacer `super().numero_clientes`), recuerda que al heredar, no necesitas reinstanciar lo métodos que ya están definidos y listos para usar de la clase _parent_ .

Y ojo con subir código tuyo directo al foro en GitHub 😅

**Comment by En-clases** [comment]
Ahí me funcionó, gracias! Y perdón por el código 😢 .
