### ISSUE TITLE
Problema GUI

### ISSUE THREAD

**Issue by savelozo** [IIC2233/Syllabus#314]
Hola!

Cuando hago click sobre un jugador dentro de la cancha no me aparece la ventana que me permite cambiarlo y el programa sigue corriendo (no me arroja ningún tipo de error). Qué puede ser?

**Comment by cilopez** [comment]
¿Están todos los jugadores dentro de la cancha ?

**Comment by savelozo** [comment]
Oh! estuve como media hora cachando qué onda jaj muchas gracias!
