### ISSUE TITLE
Duda sobre la estructura de la tarea

### ISSUE THREAD

**Issue by AESMatias** [IIC2233/Syllabus#314]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

![image](https://github.com/IIC2233/Syllabus/assets/119653204/0a1f9a91-7a4c-4b7c-9d37-d770bcc440df)
#### Si lo anterior no fuera posible, me gustaría preguntar si es posible salirse un poco de la estructura de directorios patente en la imagen del enunciado, me pregunto si es posible hacerlo exactamente como se indica ahí, a excepción de tener dos archivos dentro de T2 que sirvan para inicializar el backend y el frontend importando todo lo requerido como módulos, para así manejar directamente el inicio del servidor y la interfaz sólo con dos archivos en T2, con el nombre que yo quisiera ponerles (lo que implica no poder nombrarlos main.py).

**Comment by AntonioVenegas** [comment]
Hola @AESMatias, si puedes copiar las funciones de la entrega intermedia en entrega final, además de crear cualquier función que estimes conveniente. Pero recuerda siempre respetar la separación funcional entre cliente y servidor.

Saludos :)

**Comment by AESMatias** [comment]
Entiendo, gracias!
