### ISSUE TITLE
Valores en tupla que retorna getItemPosition

### ISSUE THREAD

**Issue by benjastraub** [IIC2233/syllabus#314]
Hola, en el primer _script_ del tercer _notebook_ de la semana 6-7 se ocupa `self.grilla.getItemPosition(idx)` pero después sólo se ocupan los primeros dos elementos de la tupla. 

Al hacer _print_ de esta, noté que retorna (posición_y, posición_x, 1, 1) para todos los botones.

¿A qué hacen referencia los dos 1?

**Comment by StroveLight** [comment]
Hmm... (p_-)

Una búsqueda rápida nos lleva a [la documentación](https://doc.qt.io/qt-5/qgridlayout.html#getItemPosition):

![image](https://user-images.githubusercontent.com/48263952/65266788-20436180-daea-11e9-8e83-00a37247bde6.png)
Que nos dice, en términos de C++ (Otro lenguaje de programación en el que se hizo Qt, del que viene PyQt5):
* Que retorna ('variables passed down'), como tú dices posicion_y, posicion_x; pero además RowSpan y ColumnSpan

Ahora, uno se pregunta ¿Que son esas cosas?

_The plot Thickens_

Aquí es cuando nos dirijimos a la parte en la que ponemos el botón

![image](https://user-images.githubusercontent.com/48263952/65267110-c000ef80-daea-11e9-8e3d-cd58bfebdcec.png)

Como recordarás de la materia, esto equivale a hacer
```python
self.grilla.addWidget(boton, posicion_y, posicion_x)
```

Entonces buscamos que hace esta funcion en [la documentacion otra vez](https://doc.qt.io/qt-5/qgridlayout.html#addItem) (y si tiene algo que ver con esos Row y Column Span

![image](https://user-images.githubusercontent.com/48263952/65267501-7f55a600-daeb-11e9-8cdf-258033fdde07.png)

Como puedes observar, al agregar el botón se ponen esas variables, por lo que también se puede agregar el botón de esa forma

```python
self.grilla.addWidget(boton, posicion_y, posicion_x, 1, 1)
```

¿Que pasa si cambiamos las variables? Por ejemplo:
```python
self.grilla.addWidget(boton, posicion_y, posicion_x, 1, -1)
```
![image](https://user-images.githubusercontent.com/48263952/65268283-3999dd00-daed-11e9-9efb-17f38c789de8.png)
¿Y si alargamos esto manualmente?
![image](https://user-images.githubusercontent.com/48263952/65268345-56ceab80-daed-11e9-8d10-7518f6a48475.png)
Ahí se vé (al ser las letras centradas), que lo que altera es en donde termina el botón: ahora todos los botones llegan hasta el final de la ventana

¿Y si hacemos lo mismo, pero ahora con un 2?
```python
self.grilla.addWidget(boton, posicion_y, posicion_x, 1, 2)
```
![image](https://user-images.githubusercontent.com/48263952/65268528-b927ac00-daed-11e9-9d32-87a4db35a17a.png)
 Como puedes observar, ahora cada botón ocupa el espacio de 2 botones

¿Y si oprimimos el botón cambia algo?
Pues si:
![image](https://user-images.githubusercontent.com/48263952/65268816-4ec33b80-daee-11e9-9d06-c6d5ad973e2e.png)


Por lo tanto, el tercer y cuarto atributo indican cuantos espacios de botón usa cada botón, siendo 1 el default, por eso puedes ver esos dos 1


Intentemos ahora con:
```python
self.grilla.addWidget(boton, posicion_y, posicion_x, 2, 1)
```
![image](https://user-images.githubusercontent.com/48263952/65269421-82529580-daef-11e9-8cc2-0d6521534821.png)

Ya que los botones no poseen un alto que se adapte automáticamente (pero sí un largo como se mostró antes), el mismo efecto no se hace muy visible si alargas los botones

![image](https://user-images.githubusercontent.com/48263952/65269164-06f0e400-daef-11e9-8524-70f2b9d44571.png)

Pero sí cuando no lo están

Espero que esto te haya ayudado en tu duda
