### ISSUE TITLE
Error con herencia de una clase abstracta

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2233/syllabus#314]
Hola! estoy intentando que una clase herede de una clase abstracta pero me tira el error
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

voy a subir mi codigo por si lo necesitan revisar pero he hecho todo lo que internet me dice que haga y me sigue saliendo :(

**Comment by maggiemunoz** [comment]
perdon tuve un error subiendolo ahora si

**Comment by moquezada** [comment]
Hola @maggiemunoz,

Te dejé una issue en tu repositorio explicando el error 💃 

Saludos!
