### ISSUE TITLE
Duda sobre valor de temperatura dentro de parametros

### ISSUE THREAD

**Issue by jebensperger** [IIC2233/Syllabus#314]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, en las características de Solaretillo y de Potencilantro, nos piden usar un valor de temperatura para calcular la producción de soles. ¿De dónde sale ese valor?
Puedo definirlo yo misma en los parámetros? y en el caso de ser así... puedo definirlo usando random.randint (entre las temperaturas permitidas) dentro del archivo de parámetros? o debo darle un valor explícito

**Comment by CatalinaBO** [comment]
Hola! Te recomiendo mirar la issue #269. Ahí se habla sobre la temperatura que se usa para los cálculos de la producción de soles de las plantas que mencionas. 
Éxito en la tarea!
