### ISSUE TITLE
Ubicacion del "guardado" de variables durante la ejecucion

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#314]
A lo largo del enunciado se habla de "guardar" variables con ciertos valores. Mi duda es, donde las guardamos? En memoria, en una base de dato en particular o se deja a nuestro criterio.

**Comment by iqacevedo** [comment]
Hola! 
Eres libre de ver cómo las guardas, puede ser como dices o en tu mismo programa, lo importante es que puedas acceder a ellas una vez que son llamadas en una consulta.

Saludos!
