### ISSUE TITLE
Cambio de probabilidades por evento especial

### ISSUE THREAD

**Issue by sevillatheking** [IIC2233/syllabus#314]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

** Si los piratas atacan el barco se pierde toda la mercancía. Entonces barco.mercancia debería estar vacio, lo que cambiaría las probabilidades de encallar del barco y otras acciones. ¿Correcto?

**Comment by sevillatheking** [comment]
Añado a mi issue. Cuando algo se expira, ¿lo tengo que eliminar tambien?  Para que afecte a las probabilidades.

**Comment by manearaya** [comment]
Hola @sevillatheking!

Cuando los piratas atacan a un barco, estos se llevan toda la mercancía (incluyendo cajas y el dinero que tenga el barco, por lo que no puede pagar la tarifa de salida). Como dices, esto cambiaría las probabilidades de encallar el barco y otras acciones porque hay menos peso en el barco.

Sin embargo, cuando una caja expira esta no se elimina (y tampoco puede volver a expirar).

Éxito con la tarea!
