### ISSUE TITLE
Para el ayudante que corregirá mi Tarea 2

### ISSUE THREAD

**Issue by Srencoret** [IIC2233/Syllabus#314]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido

Al realizar la tarea, utilicé QtDesigner. Sin embargo, al poner las imágenes usé un path absoluto y no relativo. Supe de este problema luego de la hora de entrega por lo que no se verá ninguna imagen al correr el programa. Estoy consciente que no se puede hacer otra entrega y que no obtendré el puntaje completo pero si hice otro commit con el archivo bien hecho para que se pueda corregir el resto del programa.

**Comment by lily416** [comment]
Hola @Srencoret, 

Dado que esta _issue_ más que ser una pregunta es un mensaje a tu ayudante corrector cerraré la _issue_, pero le haré llegar el mensaje a la persona que corresponda. 

Para futuras evaluaciones, si necesitas dejarle un mensaje a tu ayudante corrector por favor escríbenos al correo del curso (iic2233@ing.puc.cl).

Saludos ✉️👋
