### ISSUE TITLE
Contenidos S3: Cardinalidad de relaciones

### ISSUE THREAD

**Issue by martin-iturralde** [IIC2233/syllabus#315]
No me queda muy claro como es la relacion de grados. Es decir, a que se refiere todo esto:
1 o muchos: 1..*
0 o muchos: 0..*
Número fijo: n
No entiendo bien cuando es 0 o n....

**Comment by Juan379** [comment]
Hola!
Te puede servir pensarlo de esta forma tomando el ejemplo del diagrama de clases de Mario de los contenidos. 

En dicho diagrama, el objeto del juego se relaciona Mario en una relación **1 a 1**, lo que quiere decir que el Juego tendrá un Mario y Mario solo puede pertenecer a un Juego, en este caso estamos hablando del caso de **Número fijo: n**, donde **n=1** para cada lado de la relación. 

Ahora, este diagrama también se ve que el Juego se relaciona con el objeto Goomba con una relación **1 a 1..***. Esto quiere decir que el Juego puede tener muchos Goomba, pero tiene que tener si o si 1 por lo menos y cada uno de estos Goomba pertenecerán solamente a un Juego.

Finalmente, el diagrama no incluye relaciones con la cardinalidad 0..*, pero esta es análoga a la del ejemplo anterior. Si es que el Juego se relacionara con el objeto Goomba con una relación **1 a 0..*** esto implicaría que el juego puede tener muchos Goomba **pero** también puede existir el caso donde no tenga ninguno (no obliga a tener por lo menos uno) y cada uno de estos Goomba (si es que existe alguno) solamente pertenecen a solamente un Juego.

Espero haya quedado claro!
