### ISSUE TITLE
for, while y comprensión en funciones auxiliares.

### ISSUE THREAD

**Issue by jisalasc** [IIC2233/Syllabus#315]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo un par de dudas con cuando se puede usar while y for. Si tengo una función auxiliar que cree yo en otro modulo, y esta usa for en listas, pero solo la uso con listas por compresión, puedo hacer eso?
muchas gracias.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by TomasGMDC** [comment]
Si es que entendí bien, estás preguntando si se puede usar for y while dentro de una lista por comprensión, dentro de una función auxiliar. Esto se puede. Recuerda también que puedes crear módulos nuevos, pero debes llamarlos correctamente en el archivo consultas.py.

**Comment by jisalasc** [comment]
eso era gracias.

**Comment by Yeps3nM** [comment]
Hola! Tengo la pregunta de si puedo en funciones auxiliares utilizar diccionarios por comprensión?

**Comment by TomasGMDC** [comment]
@Yeps3nM los diccionarios por comprensión están permitidos, así que sí.
