### ISSUE TITLE
Módulo con mas de 400 lineas

### ISSUE THREAD

**Issue by Ed0ss** [IIC2233/syllabus#315]
Hola, tengo una clase para la ventana de juego, y entre todos sus métodos, labels y otros widgets puede que me pase de las 400 lineas de código. ¿Qué se hace en este caso que no puedo modularizar una clase en diferentes archivos?

Saludos!

**Comment by lily416** [comment]
Hola 😊

Sube tu código e indicanos que módulo(s) tiene más de 400 líneas para que podamos ver si se puede modularizar y así nosotros te avisamos si es que hay algo que puedas hacer. 😄

Ánimo 💪

**Comment by JJJGGGG** [comment]
Hola, tengo el mismo problema. Qué se puede hacer en el caso de tener funciones de una clase que se extiendan mucho?

**Comment by Hernan4444** [comment]
Hola,

Te recomiendo verificar que no tienes código repetido o nada que debería estar haciendo el backend y que actualmente hace el frontend o viceversa. Casi siempre se encuentra que hay una funcionalidad que no corresponde o llamas constantemente una serie de líneas que podría ser reemplaza por una función que llame esas líneas y ahí se puede reducir la cantidad de líneas.

**Comment by matumartinez** [comment]
Hola,

Aunque modularicé algunos elementos de la interfaz de mi tarea, estoy a punto de alcanzar 400 líneas en mi frontend.py. Según la pauta se descuentan hasta 5 décimas máximo por pasar 400 líneas. ¿Cuántas décimas se descuentan exactamente si es que solo tengo un archivo sobre 400 lineas?

Saludos

**Comment by Hernan4444** [comment]
Hola

Esa información se define una vez tengamos todas las tareas revisadas y así, junto con los profesores, ver cuanto descontar dado los casos identificados. Por lo tanto, no puedo decir un número ahora

**Comment by Juaco97** [comment]
> Hola,
> 
> Te recomiendo verificar que no tienes código repetido o nada que debería estar haciendo el backend y que actualmente hace el frontend o viceversa. Casi siempre se encuentra que hay una funcionalidad que no corresponde o llamas constantemente una serie de líneas que podría ser reemplaza por una función que llame esas líneas y ahí se puede reducir la cantidad de líneas.

En esa misma linea, yo tengo mi back repartido entre como 3 archivos (uno para ventanas, otro para clases generales y otro para funciones independientes), ¿no hay problema verdad? Además, para acortar algunas lineas de codigo del front, incluí el main en otro archivo, ¿habría problemas al respecto tambien? Me cuesta ver la lógica detrás de separar el back y front, y cuesta más aún cuando hay un límite de lineas :c

**Comment by Ed0ss** [comment]
Hola, acabo de subir mi código con el modulo ventana_juego.py el cuál tiene más de 400 líneas y no tengo ni idea de cómo poder modularizarlo, ya que aún me falta bastante para terminarla. Una de las cosas que más me gasta lineas es que tuve que crear todos los labels, botones y otros de manera manual, lo que me toma cerca de 200 lineas. Si me pudieran ayudar con ello les agradecería.
