### ISSUE TITLE
Problema imagenes en pyqt5

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#315]
Hola estaba corriendo el código de los contenidos de esta semana específicamente la interfaz con una imagen (la de la pitón) no desde el jupyter como se debía pero no me esta funcionando porque aparece la ventana pero en blanco sin la imagen alguna idea de donde puede estar el problema?
Lo copie tal cual como estaba en el archivo
Gracias de antemano

**Comment by csantiagopaz** [comment]
Holii Juan, quizas te falto agregar la imagen en la carpeta que tu estaba executando tu .py

**Comment by JuaniAndres** [comment]
esta bien el path y la imagen esta donde tiene que estar
alguna otra idea?

**Comment by JuaniAndres** [comment]
Por si ayuda este es el codigo:
![codigo](https://user-images.githubusercontent.com/48482216/65269455-91d1de80-daef-11e9-9e09-caca5e15dce1.PNG)

**Comment by csantiagopaz** [comment]
humm, mira intenta poner  eso despues del `if __name__ == "__main__":

    def hook(type, value, traceback):
        print(type)
        print(traceback)
        print(value)
    sys.__execpthook__ = hook`
y antes del app = QApplication([])
y me avisas si tira algun error, porque no me ocurre nada si no la ruta( yo hice un archivo.py en mi carpeta contenidos/semana6-7/ y copie el codigo del jupyter, me funciono perfecto)

**Comment by JuaniAndres** [comment]
lamentablemente no entrega nada pensé que podría ser pycharm pero trate también en idle y solo me aparece la ventana vacía voy a seguir probando que puede ser 
![Captura](https://user-images.githubusercontent.com/48482216/65270200-0bb69780-daf1-11e9-96fd-788ae12e811c.PNG)

**Comment by csantiagopaz** [comment]
Hola Juan, mira intenta hacer lo seguinte, cambia la imagen a la misma carpeta del archivo python que tu esta executando, pero antes redefina ruta_imagen con solo el nombre del archivo (python.jpg).

**Comment by JuaniAndres** [comment]
ya encontre el error fue completamente mio la imagen esta donde tiene que estar pero el archivo no lo estoy corriendo en donde tiene que estar (la carpeta de contenidos)
muchas gracias igual por la ayuda y felices fiestas  @csantiagopaz
