### ISSUE TITLE
Duda sobre la función intercambiar en el Menú del Jardín

### ISSUE THREAD

**Issue by TarzanDeMaceta** [IIC2233/Syllabus#315]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado dice que el intercambio debe ser "planta-planta", "vacío-planta" o "vacío-vacío", **quería consultar si es válido o no admitir "planta-vacío"**. Pregunto por que lo último es equivalente a hacer "vacío-planta".

Gracias de antemano

**Comment by R3Y3X** [comment]
Hola espero que estés bien, Sí, es valido admitir  "planta-vacío", ya que como mencionaste es equivalente a hacer  "vacío-planta".Éxito en la tarea ⚡

**Comment by TarzanDeMaceta** [comment]
Muchas gracias
