### ISSUE TITLE
Uso y funcionamiento .json

### ISSUE THREAD

**Issue by Joako5848** [IIC2233/Syllabus#315]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Funcionamiento .json

En la parte 7.1.2 del enunciado habla de como el json debe contener el port y "...", asumo que esto es para que le fuesemos agregando cosas nosotros, pero como que? se me ocurre que sería lo necesario para el leaderboard y usuarios baneados pero eso no lo puedo hacer por un .txt en la carpeta server?

**Comment by AntonioVenegas** [comment]
Hola, según el enunciado el archivo json del servidor debe contener el host, en está issue https://github.com/IIC2233/Syllabus/issues/287 se habla sobre los usuarios baneados, pero básicamente queda a tu criterio si quieres añadirle más cosas al json o hacerlo de otra forma (siempre y cuando seas consistente y se respete lo especificado por el enunciado, como por ejemplo, que los usuarios baneados se encuentren en el servidor). Recuerda además que debes crear un json para el servidor y otro para el cliente.

Saludos :)
