### ISSUE TITLE
Efectos de Opción "Volver Atrás"

### ISSUE THREAD

**Issue by danvillablanca** [IIC2233/syllabus#315]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Se pide que el Menú de Acciones incluya la opción de Volver Atrás. Sin embargo, si el usuario decide Volver Atrás en plena simulación, tendría que iniciar una nueva simulación y la simulación que estuvo jugando se perdería. ¿Es así, o esta opción debe permitir continuar el juego donde quedó antes de Volver Atrás?

**Comment by Emiliax16** [comment]
Hola! como el menú de inicio tiene únicamente dos opciones (Comenzar una nueva simulación o Salir), en caso que se vuelva atrás en el _Menú Acciones_, los datos de la simulación se resetean.

**Comment by danvillablanca** [comment]
¡Muchas gracias por la clara respuesta!
