### ISSUE TITLE
Desde main.py no se encuentra gui

### ISSUE THREAD

**Issue by kadawn0** [IIC2233/Syllabus#315]
Hola,
En las primeras líneas de main.py sale:

from gui.Gui import MyWindow
from PyQt5 import QtWidgets
import sys

Quería abrir la ventana de la interfaz pero no tengo gui.Gui. Pensé que era de Tkinter pero ese package está instalado. ¿Qué pasa?

**Comment by Hernan4444** [comment]
@kadawn0 gui.Gui es la carpeta gui que les dimos junto con la tarea-

Saludos!

**Comment by jtagle2** [comment]
Para complementar: Lo que se está haciendo ahí, es desde el archivo main.py, abres la carpeta gui (que debe estar en la misma ubicación que el main), y luego se va al archivo Gui.py y desde ahí importas la clase MyWindow.
Esto se vió en la primera ayudantía, cualquier duda puedes revisar ahí también.
Si te dice que el modulo no existe, seguramente estas ejecutando tu main sin tener la carpeta gui en la misma ubicación.
Saludos!

**Comment by kadawn0** [comment]
Gracias, no había copiado esa carpeta.
