### ISSUE TITLE
Duda respecto a properties

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#315]
Cuál es la ventaja comparativa de usar property sobre un atributo? Entiendo que al hacerlo, puedo definir cómo lo muestro y cómo lo modifico (con el getter y el setter), pero ambas cosas las podría hacer de igual forma sin tener que definir el atributo como property...

**Comment by Dnpoblete** [comment]
Hola @lewebe, en primer lugar, utilizar properties en comparación a utilizar atributos normales, genera un código más limpio y comprensible, ya que con solo mirar la propertie sabes los rangos y/o condiciones tiene el atributo, mientras que con un atributo normal no lo sabes con solo mirarlo. Y en segundo lugar, usar properties te ahorra muchas líneas de código, ya que al momento de modificar el atributo en el resto del código solo lo haces, por ejemplo si tienes el atributo vida y le quieres restar 2, solo haces self.vida-=2, mientras que si fuera un atributo normal, tendrías que tener varios if y elif para comprobar que se pueda realizar la acción, y eso cada vez que tratas de modificar el atributo en el código, lo cual a fin de cuentas pueden llegar a ser muchas líneas de código.

Espero haber aclarado tu duda y éxito con la tarea! ✨

**Comment by lewebe** [comment]
Hola, gracias por contestar! No entendí a lo que te refieres con el ejemplo de restar 2 puntos de vida. Eso también lo puedo hacer sin properties o no?

**Comment by Dnpoblete** [comment]
Si se puede hacer, pero como dije sería más largo, ya que cada vez que quieras restar a self.vida tendrás que utilizar varios if para comprobar que por ejemplo la vida no sea un número negativo, y en el caso de que sea 0 notificar que no tiene vida, lo cual tendrías que hacer cada vez que en el código se reste vida, en cambio con una propertie solo lo escribes una vez en el setter y te ahorras muchas líneas de código.

Avisame si ahora se entendió y sino para explicarlo de otra forma 😄
