### ISSUE TITLE
Consulta subir tarea (se crea carpeta: .idea)

### ISSUE THREAD

**Issue by mblejeune** [IIC2233/Syllabus#316]
Hola! estoy haciendo un intento para subir mi tarea utilizando gitignore, y según entendí debo subir /Tareas/T02 ya que dentro de la carpeta T02 está el gitignore, y en este caso se me sube la carpeta GUI y dentro de GUI están los módulos que yo creé (grafo.py, hackerman.py, etc )y modifiqué (demo.py). Está bien que se suban dentro de la carpeta GUI? o subo directamente solo los módulos que ya mencioné? Y también al hacerlo se me crea una carpeta ".idea" pero nosé si está bien que esta se cree, porque al recolectar tareas podrían recolectar la carpeta .idea la cual no tiene los códigos que yo he escrito entonces me tiene complicada que se cree esa carpeta.

También tengo la duda de si debo ignorar los modulos extras? Que son los que yo cree como grafo o hackerman.py, entre otros( los cuales se importan a demo.py) En este caso solo se subiria la carpeta GUI con demo.py dentro.

Esto es lo que se me sube : (lo intente subiendo a la AC03 de mi repositorio en github ya que a esa actividad no pude asistir entonces no me complicaría la vida jaja)

![captura de pantalla 2018-04-22 a la s 14 17 28](https://user-images.githubusercontent.com/37160975/39097874-8a0fd42e-4638-11e8-9465-3e71097f2618.png)

**Comment by cilopez** [comment]
- En primer lugar deberías poder evitar subir la carpeta `.idea` con tu archivo `.gitignore`
- Esta bien si estas trabajando con esos módulos en esa carpeta, no podríamos evaluar tu tarea si no subes el grafo o el hackerman por lo que es vital que los subas a tu repositorio.

No estoy seguro si entendí bien tu duda, porfavor hazme saber si queda resuelta.

**Comment by mblejeune** [comment]
@cilopez Si! Ahi cache que poniendo en mi archivo .gitignore: *.idea se evita que se suba :) Sobre el gitignore en internet sale que para ignorar es necesario poner * delante, está bien esto cierto? Como para que me funcione haciendo *.idea (porque es una carpeta) con los demás archivos me funciona bien!

Me queda la duda de si al momento de subir la tarea está bien que suba la carpeta GUI y dentro de esta están estos módulos?  en ese caso se recolectaría la carpeta GUI para revisar? O es necesario que suba los módulos directamente uno a uno (no dentro de una carpeta)?

Muchas gracias!! :)
