### ISSUE TITLE
problema con instalacion de pyqt5

### ISSUE THREAD

**Issue by pascal1003** [IIC2233/syllabus#316]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema
Hola, 
Intente descargar pyqt5, lo deje como media hora cargando y no se me instalo.

**Comment by pascal1003** [comment]
logre instalar pyqt5 pero cuando installo pyqt5-tools me aparece este error
![Captura de pantalla 2021-04-24 a las 2 17 55 p m](https://user-images.githubusercontent.com/80788210/115968870-db727e80-a507-11eb-8cb4-b1ac4fdbe529.png)

**Comment by Emiliax16** [comment]
Hola @pascal1003 ! y si intentas con `pip install pyqt5-tools` o con `pip3 install pyqt5-tools` ?

**Comment by pascal1003** [comment]
como tengo varios python 3 descargados utilizo pip3.7 install pyqt5-tools

**Comment by Emiliax16** [comment]
Me acabo de percatar que tienes mac. Por lo que sé, pyqt5-tools está habilitado sólo para Windows. Prueba con las soluciones de [este link](https://stackoverflow.com/questions/52601877/install-pyqt5-tools-on-macos) y avísame como te va!

**Comment by pascal1003** [comment]
Logre instalar qt designer pero no me deja abrirlo
![Captura de pantalla 2021-04-25 a las 12 08 26 p m](https://user-images.githubusercontent.com/80788210/116000618-0370e900-a5bf-11eb-81d3-9e3770b4e195.png)

**Comment by Emiliax16** [comment]
@pascal1003 sigues con el mismo problema?

**Comment by pascal1003** [comment]
ya me lo descargue pero no lo puedo abrir

**Comment by Emiliax16** [comment]
El problema es que está deshabilitada la opción para abrir la app, aquí te dejo opciones:

1. En preferencias de sistema, anda a "Seguridad y privacidad". Anda a General y debería estar Qt por ahí. Deberías poder ver la opción de 'Cualquier sitio" dentro de permitir. Con eso, se habilita la app.
2. Anda a FInder y localiza la app Qt, hace click derecho y selecciona "Abrir desde el menú de función rápida". Luego presiona abrir.

Quedo atenta!

**Comment by pascal1003** [comment]
muchas gracias por la ayuda, ya me funciono
