### ISSUE TITLE
Uso de filter

### ISSUE THREAD

**Issue by felipecr00** [IIC2233/Syllabus#316]
No comprendo bien como hacer un filter de un filter (como el que se hace en la actividad).
city = ciudad_por_pais(nombre_pais, paises, ciudades) tengo este iterable,
Ahora quiero filtrar las personas que tienen esas ciudades pero sin usar el for (que es la unica forma en que si me funciona). No entendi muy bien esa materia asi que agradecería ayuda.

**Comment by akaminetzkyp** [comment]
La función `filter` recibe dos argumentos: una función y un iterable. Además, retorna un generador (que es un iterable). Por esta razón, tu puedes entregarle a un `filter` lo retornado por otro `filter`.

Por ejemplo, supongamos que queremos obtener las personas que son de Santiago y tienen un ingreso superior a 600. El código para lograr esto podría lucir de la siguiente manera:

```
# "personas" es una lista que contiene namedtuples de tipo "Persona"

personas_santiago = filter(lambda persona: persona.ciudad_residencia == 'Santiago', personas)
personas_santiago_e_ingreso_superior = filter(lambda persona: int(persona.sueldo) > 600, personas_santiago)
``` 

Ahora revisemos tu ejemplo. Supongo que quieres obtener las personas que pertenecen a un país específico. Tienes una función que retorna un generador con todas las ciudades de dicho país. Para que una persona pertenezca al país debe pertenecer a cualquiera de las ciudades de este país. Para lograr saber si una persona pertenece a alguna ciudad del país podríamos usar `in`, pero no es tan simple como aplicar `in` sobre el generador. Por esta razón, creamos una lista que contiene los nombres de todas las ciudades del país. El siguiente código muestra una forma de encontrar a las personas pertenecientes a Chile.

```
# "paises" es una lista que contiene namedtuples de tipo "Pais"
# "ciudades" es una lista que contiene namedtuples de tipo "Ciudad"
# "personas" es una lista que contiene namedtuples de tipo "Persona"

ciudades_de_chile = ciudad_por_pais('Chile', paises, ciudades)
nombres_de_ciudades = [ciudad.nombre for ciudad in ciudades_de_chile]
personas_de_chile = filter(lambda persona: persona.ciudad_residencia in nombres_de_ciudades, personas)
```

Espero que te haya ayudado! Si todavía tienes alguna duda por favor cuéntanos.

Saludos!

**Comment by felipecr00** [comment]
Muchas gracias por tu ayuda! me quedo super claro
