### ISSUE TITLE
Explosión Kamikazes

### ISSUE THREAD

**Issue by csmeneses** [IIC2233/syllabus#316]
Hola, en el enunciado no se dice en ninguna parte si cuando un kamikaze explota solo destruye una torre o todas las que estén dentro de su radio de explosión (una casilla en cada dirección).
En este caso, si tengo varias torres adyacentes y llega un kamikaze al que le correspondería destruirlas todas, debo restringirlo a solo una de esas? o simplemente es mala estrategia ponerlas juntas porque son muy fáciles de destruir...

**Comment by gatochico** [comment]
Hola! El kamikaze sólo destruye a la torre que "activó" su explosion (la que estaba adyacente al kamikaze).  Saludos!

**Comment by furzuadr** [comment]
Con respecto a esto, al llegar a una esquina con dos torres, como llega al mismo tiempo a ser adyacente a ambas, es correcto que exploten las dos? (poniéndolo en el readme) Gracias!

**Comment by gatochico** [comment]
Si, siempre y cuando esté en el Readme!! :cat:
