### ISSUE TITLE
Duda sobre parametro AUM_AUM_CIL

### ISSUE THREAD

**Issue by mrebolledo03** [IIC2233/Syllabus#316]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, en la tarea dice "Tanto su atributo de potencial como el de aumento deben ser mayores que el de sus clases padre, respectivamente en AUM_POT_CIL % y AUM_AUM_CIL %, siendo ambos un float entre 0 y 1." esto se refiere a que el parametro AUM_AUM_CIL remplaza al AUMENTO_NUTRIENTE en la formula de produccion de soles? o a que el total de produccion de soles aumenta en ese float?

**Comment by JVeloz19** [comment]
**Hola buenas!!** Para no crear una issue nueva respecto al mismo tema me adhiero a esta misma.

Realmente no entiendo a que se refiere cada AUM, también se me ocurría que alguno de los dos tiene que remplazar al aumento para potenciar normalmente la producción de soles, pero no me queda claro que hace el otro.  ¿Podría ser que uno es el porcentaje de aumento a otras plantas y el otro es el aumento que se realiza a sí mismo?

**Comment by rodrigoaguilera15** [comment]
La explicación es la siguiente: El cilantrillo tiene tanto el atributo de potencial como el de aumento de sus clases padre. Sin embargo se pide que ambos atributos sean mayores que los originales de sus clases padres ¿pero cuánto? eso es lo que representan AUM_POT_CIL y AUM_AUM_CIL respectivamente. Ejemplo: si el atributo potencial del solaretillo vale 10, yo necesito que el potencial del cilantrillo valga más, entonces asigno AUM_POT_CIL como 0.2, de tal forma que el potencial del cilantrillo me dé 10*(1 + 0.2) = 12. La misma relación sucede entre el atributo aumento del potencilantro, el aumento del cilantrillo y el parámetro AUM_AUM_CIL. Espero haber respondido satisfactoriamente, respondan con un pulgar arriba si es así, quedo atento, saludos.

**Comment by mrebolledo03** [comment]
o sea que AUM_AUM_CIL aumenta el potencial en AUM_AUM_CIL% de las plantas vecinas y AUM_POT_CIL en AUM_POT_CIL% el potencial del mismo cilantrillo?

**Comment by rodrigoaguilera15** [comment]
@mrebolledo03 No exactamente. El cilantrillo aumenta su propio atributo de aumento en AUM_AUM_CIL%, entonces aumenta el potencial de las plantas vecinas y el suyo propio en un factor de (1 + aumento/100) donde aumento = aumento_base * (1 + AUM_AUM_CIL%), donde aumento_base es el aumento del potencilantro. Lo que dices respecto a AUM_POT_CIL es correcto, aumenta en dicho porcentaje el potencial del mismo cilantrillo.
