### ISSUE TITLE
DUDA MODELAR OBJECTOS

### ISSUE THREAD

**Issue by tremendapithon** [IIC2233/Syllabus#316]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola buenas noches tengo una duda respecto, si es que tengo que modelar clases (similar a lo de la T1) para las entidades y los bloques, o no es necesario como tal.

**Comment by Hernan4444** [comment]
Hola @tremendapithon 

En estricto rigor, no, no es necesario modelar clases como en la T1. Cómo se puede observar en la [pauta](https://docs.google.com/spreadsheets/d/1um-WMGdzDC-xNCSoNokFIzh0aLR-iR8YVvbNfCQZNOc/edit), no hay ítem que evalúe dicho contenido. No obstante, se recomienda fuertemente utilizar OOP en algunas partes porque facilitaría el orden en el código y en caso de utilizar herencia, podrías reducir la cantidad de código que tengas que programar. Además, luego puede ser más fácil encontrar ciertas cosas cómo las señales asociadas a una entidad o funcionalidades que son propias de una entidad.

Saludosヾ(＾-＾)ノ
