### ISSUE TITLE
¿Las variables especiales como `__file__` está prohibido?

### ISSUE THREAD

**Issue by Utmite** [IIC2233/Syllabus#316]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

A vista de que no me tomaba el path de una imagen, hice este código para tomar la posición del mismo archivo e ir desde ahí en busca de la imagen. Mi pregunta es si hacer esto es una mala práctica o si el uso de las variables especiales como `__file__` está prohibido.

```python
image_path = path.join(
    path.dirname(path.abspath(__file__)), "../assets/sprites/logo.png"
)

**Comment by MathiasPrett** [comment]
tengo la misma pregunta, me están complicando demasiado los paths!!

**Comment by AntonioVenegas** [comment]
Hola!, por un lado no debería haber descuento ya que usaste paths relativos para construir uno absoluto con `abspath()`. Sin embargo te recomiendo darle una vuelta, los paths se construyen desde el directorio donde se ejecuta tu archivo. Si construyes correctamente los paths, no debería ser necesario usar "..".

Por ejemplo, si el directorio fuera:
'''
Cliente
    main.py
    assets
        sprites
            logo.png
    backend
    ...
'''
La ruta sería "assets/sprites/logo.png".

Pero si en cambio, el directorio fuera:

'''
Cliente
    main.py
    frontend
        assets
            sprites
                logo.png
    backend
    ...
'''
La ruta sería "frontend/assets/sprites/logo.png"

Espero eso haya aclarado la duda. Saludos :)

**Comment by Utmite** [comment]
muchas gracias :3
