### ISSUE TITLE
Do IF

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#316]
tengo la duda de como recibe los parametros
es asi? 
[do_if, [extraer_columna, columna_b], [comparar, 1, >, 2], [operar, columna_2, +, 2]]

**Comment by Hernan4444** [comment]
@Dunkan1 la forma en que do_if recibe los parametros está bien :+1: 
Saludos!!

**Comment by Dunkan1** [comment]
gracias
