### ISSUE TITLE
Duda con la interpretación de los tests

### ISSUE THREAD

**Issue by escontre** [IIC2233/Syllabus#316]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, no entiendo como interpretar este error que me sale en el test 04 de la tarea. 

![image](https://github.com/IIC2233/Syllabus/assets/142276448/40f62d87-62e1-46e0-95db-0f896f47f8af)

**Comment by tcapom** [comment]
Hola @escontre !

El propósito de `.assertCountEqual(a,b)` es que, siendo `a` y `b` dos estructuras de datos, verá si es que todos los elementos de `a` están en `b` y viceversa sin importar su orden. Cuando se imprimen líneas del tipo `First has 0, Second has 1: 'Medusa'`, es porque `Medusa` se encuentra una vez en `b` y ninguna en `a`

Recuerda que siempre puedes buscar en la documentación oficial de python para saber la funcionalidad de distinto métodos. En este caso `.assertCountEqual()` se puede encontrar en [https://docs.python.org/3/library/unittest.html](url)
