### ISSUE TITLE
Pregunta sobre output 'None'

### ISSUE THREAD

**Issue by aayale** [IIC2233/syllabus#316]
Hola, en la Tarea 00 cree unas funciones que en vez de tener un *return*, imprimían cosas. El problema, que no logré solucionar, es que al llamar a la función en el módulo principal si bien escribía lo que yo quería, al final me salían **None**, incluso a veces salían hasta 3 None seguidos. Quería saber por qué razón ocurre esto y si hay alguna manera de arreglarlo

**Comment by dchahuan** [comment]
Que si no pones return o si tienes una funcion de este estilo:

def func(a):
    hace algo con a ....
    return

Python ve que no retornas nada entonces lo que tu función devuelve es None. Como la funcion solo imprimia y no retornaba nada especifico python lo ve y dice esta funcion retorna None. Estas funciones si no quieres que salga None, no las pones dentro de un print(func()) ya que el print devuelve en la consola lo que devuelve la funcion.
