### ISSUE TITLE
setMouseTracking

### ISSUE THREAD

**Issue by LucianoDavico** [IIC2233/syllabus#317]
Hola!

Estaba haciendo la parte de arrastrar las torres al mapa e hice overriding de los métodos `mouseMoveEvent()` y `mouseReleaseEvent()`. El problema que tengo es que luego hago `setMouseTracking(False)` para 'bloquear' el mouse, es decir, que no pueda seguir arrastrando las torres que ya asigné, sin embargo igual puedo seguir moviendo las torres. Existe alguna forma de bloquear las señales que emito?

Gracias

**Comment by jmwielandt** [comment]
Hola!
Con esto te refieres  a que aunque sueltes el botón del mouse la torre sigue moviéndose con el cursor o a que una vez está puesta en el mapa, la puedes volver a agarrar y mover a otro lado?

**Comment by LucianoDavico** [comment]
A lo segundo, que la pueda volver a agarrar y mover.

**Comment by jmwielandt** [comment]
En ese caso, puedes incluir algún if y/o atributo que te permita identificar cuando una torre ya fue posicionada y  no aceptar moverla de nuevo, porque en teoría, eso ya es parte del backend darse cuenta que la torre no debe seguir moviéndose.

Ánimo con la tarea~
