### ISSUE TITLE
Problemas de instalación

### ISSUE THREAD

**Issue by Dafnemami** [IIC2233/syllabus#317]
Al momento de instalar  PyQt5 y Jupyter me lanza esos errores.  Busqué ayuda en línea para solucionar ambos errores, pero no logré avanzar. 

obs:  Me llama la atención que teniendo Python 3.7.2 no pueda ejecutar "python3 -m pip install jupyter", por eso ejecuté "python -m pip install jupyter", no sé si eso está bien o no.

Muchas gracias de antemano 👩‍🚀 🔥 ❤️ 

![error 1](https://user-images.githubusercontent.com/53848830/65297510-83f77a00-db3e-11e9-8c0b-5106d02fc86b.PNG)
![error 2](https://user-images.githubusercontent.com/53848830/65297512-8528a700-db3e-11e9-867d-ca12c396a9d3.PNG)

**Comment by jmwielandt** [comment]
Hola!

> obs: Me llama la atención que teniendo Python 3.7.2 no pueda ejecutar "python3 -m pip install jupyter"

Eso pasa cuando solo tienes instalado python 3 en tu computador (imagino que será el caso). Todos los comandos funcionan con pip y con python, no con pip3 ni python3.

En principio ejecutar

```powershell
pip install jupyter
pip install pyqt5
```

Debiera bastar, prueba antes con:

```powershell
pip uninstall jupyter
pip uninstall pyqt5
```

Si esto no funciona, realiza una desinstalación total de python, 

![image](https://user-images.githubusercontent.com/37153467/65380067-b70a4c80-dca9-11e9-9e80-b389e2cf1997.png)


Debes quitar los dos, primero el con versión y luego el launcher.

Borrar las carpetas:
- `C:\Users\dafne\AppData\Local\pip`
- `C:\Users\dafne\AppData\Local\Programs\Python`
- `C:\Users\dafne\AppData\Roaming\jupyter` si la tienes

Luego, reinstala python (te recomiendo descargar un instalador nuevo) e instala las distintas librerías con `pip install XXXX`.

Recuerda que al instalar python debes agregarlo al path.

Dime si te funciona, saludos~
