### ISSUE TITLE
Problema con push

### ISSUE THREAD

**Issue by Regenschrim** [IIC2233/Syllabus#317]
Tengo dos problemas.
1) Si subo desde la consola los archivos, no me corre el gitignore y me sube todo. No entiendo porque.

2) Como me pasaba lo anterior configure Pycharm para subir directamente los archivos lo cual funciona pero me crea la carpeta de mi repositorio como Tarea02/GUI. Asumo que es porque los archivos los esta cargando desde esa carpeta. ¿Influye esto al momento de revisar la tarea? 

No había tenido este problema antes, asi que no se que pasa :/ 

Gracias!!!!!

Edit: ¿No hay problema si dentro de T02 hay una carpeta GUI que contenga solo los archivo pedidos?

**Comment by cilopez** [comment]
- Probablemente tu gitignore no está bien definido.
- No deberían existir problemas en ese caso.
