### ISSUE TITLE
Parametros por dificultad

### ISSUE THREAD

**Issue by Agusrush21** [IIC2233/Syllabus#317]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, mi consulta es que si ¿Puedo establecer los parámetros en función de la dificultad del juego?, y si es así, ¿Puedo guardar los parámetros en un diccionario, lista, tupla o namedtuple?. Esto solo para darle mas dinamismo al juego y de ser así, poder acceder mejor y ordenadamente a los parámetros dichos.
Gracias de antemano

EDIT: Si estoy consciente de los cambios que afecta la dificultad del juego, peor mi duda va mas si se puede extender a mas parametros

**Comment by diegoftpxd** [comment]
Hola! si está permitido que ajustes más parametros según tu criterio. Lo importante es que estos parametros sean facilmente cambiables y se encuentren en parametros.py está bien.
