### ISSUE TITLE
Ayudantía "virtual": Decoradores

### ISSUE THREAD

**Issue by andresfdezc** [IIC2233/Syllabus#317]
¡Hola!

Los ayudantes de docencia preparamos un material de apoyo para su estudio de esta semana. Pueden encontrarlo [aquí](https://github.com/IIC2233/Syllabus/blob/master/Ayudantias/S07%20Programaci%C3%B3n%20Funcional%20Decoradores/S07%20-%20Decoradores.ipynb).

Cualquier duda que tengan al respecto pueden preguntarla en esta misma issue.

Además, si encuentran algún error, por favor avísennos.

¡Nos vemos el jueves en la actividad!

**Comment by MarceloSaldias** [comment]
En la ayudantia sale que el decorador "correct_price" deberia ser asi:
```python
def correct_price(iva_actual, iva_nuevo): 
    def decorador(metodo): 
        def nuevo_metodo(*args, **kwargs): 
            precio_original = metodo(*args, **kwargs) / iva_actual
            precio_nuevo = precio_original * iva_nuevo
        return metodo
    return decorador
```
Pero no realiza ningun cambio en el metodo, solo lo recibe y calcula el precio pero no lo retorna.
Esta bien este cambio?
```python
def correct_price(iva_actual, iva_nuevo): 
    def decorador(metodo): 
        def nuevo_metodo(*args, **kwargs): 
            precio_original = metodo(*args, **kwargs) / iva_actual
            precio_nuevo = precio_original * iva_nuevo
            return precio_nuevo
        return nuevo_metodo
    return decorador
```

**Comment by jnlarrain** [comment]
Estimado gracias por la observación, esta correcta la solución que propones.

**Comment by SarahEverke** [comment]
Hola! No me queda claro porqué se utiliza **kwargs en la siguiente función

`def correct_price(iva_actual, iva_nuevo): 
    def decorador(metodo): 
        def nuevo_metodo(*args, **kwargs): 
            precio_original = metodo(*args, **kwargs) / iva_actual
            precio_nuevo = precio_original * iva_nuevo
        return metodo
    return decorador`

**Comment by nachocontreras** [comment]
Hola! En la ayudantía sale que la siguiente función hace que los métodos sean privados.
```Python
def protect_methods(*metodos): 
    def decorador(cls):
        for metodo in metodos:
            funcionalidad = getattr(cls, metodo)
            nuevo_nombre = "__{}".format(metodo)
            setattr(cls, nuevo_nombre, funcionalidad) 
            delattr(cls, metodo) # borramos el anterior
        return cls
    return decorador
```


Sin embargo, cuando en el main se ejecuta `ej.__change_price()`, se imprime "Has accedido a un metodo que debiese ser privado" 🤔 

```Python
@protect_methods("change_price")
@snake_case("IncreasePrice", "FinalPrice", "ChangePrice")
class Product:

    def __init__(self, name, price, stock):
        self.name = name
        self._price = price
        self._stock = stock

    def ChangePrice(self, new_price):
        print("Has accedido a un metodo que debiese ser privado")
        self._price = new_price

ej = Product("Car", 100, 2)
print("LLamado de __change_price(1000):")
ej.__change_price(1000)
print("Nuevo precio:",ej._price)
```

Retornado:

```
LLamado de __change_price(1000):
Has accedido a un metodo que debiese ser privado
Nuevo precio: 1000
```
