### ISSUE TITLE
Tiempo acotado por test

### ISSUE THREAD

**Issue by njllanos** [IIC2233/Syllabus#317]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
Hola! En el enuciado aparece que hay que corroborar que cada test público para cada consulta corra en un tiempo acotado de 20
segundos por test, y que en caso contrario se asumirá un resultado incorrecto. **En caso de cumplir con el acotamiento, ¿Tengo asegurado de que no se demorará más del límite (o que no se contarán como malo) en los test privados o de corrección?**. Lo pregunto dado que en caso de tener una consulta que corra en 17-18 segundos, quiero estar seguro de que con eso basta y no tendré problemas con los tests en la etapa de correción.

**Comment by ClemoAcevedo** [comment]
Hola @njllanos, si es que son los más difíciles, está bien que tarden más aunque 17-18 segundos igual es elevado. Lo único que te podemos asegurar es que el volumen de datos de los tests públicos y privados será similar, pero no te podemos asegurar que sí o sí pase el test dado que podría haber un dataset cuyas respuestas tarden un poco más. Te recomendaría dejar para el final la optimización en tiempo de tus funciones que andan cerca de los 20 segundos.

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Hola, respecto a esta duda, cuando se refiere a que cada test público debe durar como max 20 segundos se refiera al test publico completo (con los sub tests que cada uno posee) o que cada sub test del test debe durar como máximo 20 segundos?
