### ISSUE TITLE
Jupyter instalación

### ISSUE THREAD

**Issue by Vfabres2** [IIC2233/syllabus#317]
- **Sistema Operativo:** MacOs Catalina version 10.15.6
- **Programa a instalar:** jupyter

- Foto del error: # ![Uploading Captura de Pantalla 2020-09-02 a la(s) 11.05.18.png…]()

- Descripción del problema: Hace unos cuantos dias me funcionaba perfecto, pero ahora no me abre archivos. Pongo jupyter --version y me tira esto: zsh: command not found: jupyter,  después pongo pip3 install jupyter y me sale lo de la foto. Tengo un video de todo el proceso, pero nose como mandarlo.

**Comment by aaossa** [comment]
Hola @Vfabres2 , por alguna razón no se ve la foto del error, ¿podrías ponerla de nuevo? Gracias 😅

**Comment by Vfabres2** [comment]
Tengo un video mucho mas demostrativo se lo puedo manar por gmail?

**Comment by aaossa** [comment]
@Vfabres2 la verdad es que prefiero que inicialmente subas la captura por acá, porque no tengo certeza de poder ayudarte. Además, de esa manera es posible que le sirva a otras personas que tengan un problema similar

**Comment by Vfabres2** [comment]
Bueno voy a ver como lo puedo hacer

**Comment by Vfabres2** [comment]
![Captura de Pantalla 2020-09-02 a la(s) 11 05 18](https://user-images.githubusercontent.com/69874942/92006750-23435c00-ed13-11ea-8077-6b14f567fa4a.png)

**Comment by aaossa** [comment]
Instalaste `zsh` después de instalar jupyter? Mi pregunta va hacia saber si esto partió cuando instalaste `zsh`

**Comment by Vfabres2** [comment]
![Captura de Pantalla 2020-09-02 a la(s) 11 58 34](https://user-images.githubusercontent.com/69874942/92007209-a369c180-ed13-11ea-98ac-aa9fea75664a.png)

**Comment by Vfabres2** [comment]
Creo que si lo hice

**Comment by aaossa** [comment]
Un par de posibles soluciones que encontré:

1. Después de una instalación, lo mejor es partir reiniciando la consola (cerrándola y volviendo a abrirla).
2. Revisa si te funciona `python3 -m notebook --version`, para imprimir la versión de Jupyter

Otras soluciones dependen de cómo instalaste Jupyter y pueden ser algo más complicadas. Si lo de arriba no te funciona, te recomendaría probar desinstalar Jupyter y volver a instalarlo

**Comment by Vfabres2** [comment]
Muchas gracias profesor! Me funciono ocupando lo que sale en este link https://github.com/jupyter/help/issues/89
