### ISSUE TITLE
Labels, PushButton, etc. no se actualiza

### ISSUE THREAD

**Issue by Tomasalvarez15** [IIC2233/syllabus#318]
No se porque cuando hago cambios en un Label o hago self.hide o self.show a un label, boton,etc. esto no se actualiza hasta que dejo de "mirar la ventana" y la abro nuevamente. También sirve agrandar la ventana. ¿Puede ser esto considerado un error? ¿O existe alguna forma para solucionarlo?

**Comment by jeschuwirth** [comment]
Hola!
Te diría que ocupes el siguiente método TU_LABEL.setText("Hello World"). 
Aunque asumo que es lo que haces.
Comenta en la issue escribiendo lo que tienes después de if __name__ == "__main__":

```
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    Form.show()
    sys.exit(app.exec_())
```

**Comment by Tomasalvarez15** [comment]
if __name__ == '__main__':
    app = QApplication(sys.argv)
    inicio= Inicio()
    inicio.show()
    sys.exit(app.exec_())

Estoy usando ese metodo, y funciona. Pero los cambios solo ocurren cuando veo la ventana nuevamente o modifico su tamaño. Es como que se activara la actualizacion de ella por estos métodos. Me gustaría saber si existe una penalización por ello.

**Comment by furzuadr** [comment]
Me pasa lo mismo en un mac, a veces funciona bien y a veces no, es un problema de PyQt5, estuve mucho rato buscándolo en Internet, se lo mostré a varios ayudantes en la actividad pasada y no encontraron ningún error y me dijeron que estaba bien. Probando en otro computador con Windows, funcionaba bien.
