### ISSUE TITLE
Decoradores fibo

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#318]
![image](https://user-images.githubusercontent.com/24725124/30645966-c9f11e8e-9ded-11e7-8a10-22b91470790f.png)

En ese parte no me queda claro de donde sale el argumento "x" que según veo es el return del "f"

**Comment by andresfdezc** [comment]
La función `func(x)` es una como cualquiera, pero que fue definida dentro del _scope_ de otra función. Así como cualquier función, uno puede declarar sus argumentos de entrada. En este caso `func` recibe un número `x` (que luego es entregado como argumento a la función `f`).

Luego, la función `efficient_fib(f)` (el decorador en este caso), recibe una función `f` que calcule los números de Fibonacci. No un número, tampoco la ejecución de una función, la función sin ejecutar. Como `func(x)` está definida dentro de `efficient_fib(f)`, puede ver y alterar cualquier variable de ahí. Es por eso que puede usar el diccionario `data` donde se guardan los valores de Fibonacci previamente calculados, y `f` que es la función recibida por `efficient_fib(f)` como argumento.

Finalmente, `efficient_fib(b)` retorna la función `func`. No un valor calculado por `func`, la función misma. Esta función retornada es luego guardada en la variable `fib`, por lo que simplemente se puede utilizar como si se llamara `fib`.

**Comment by andresfdezc** [comment]
Porque son la misma función. `func` fue entregado a la variable `fib` cuando se hizo
```python
fib = efficient_fib(fib)
```
pues, `efficient_fib` retorna a `func`. También tienes que considerar que `n` es un número cualquiera. Perfectamente pudo haber sido `print(fin(3))`, y ese argumento `3` es lo que recibe `func(x)` como argumento en `x`.

**Comment by movaldivia** [comment]
Muchas gracias, ya me quedó claro !

**Comment by fgbruna** [comment]
A mí no me queda claro por qué inmediatamente después de decorar `fib` la función se vuelve más eficiente.No debería ser luego de ejecutarla por segunda vez para el mismo número ya que previamente `data` no tiene ningún dato ?

**Comment by KnowYourselves** [comment]
@fgbruna 
Lo que sucede es lo siguiente, el `efficient_fib` lo único que hace es guardar cada valor de n y su representación en fibonacci en un dict. Si te detienes a analizar cuando ejecutes `fib(n)` recursivamente se va a ir metiendo en `fib(n-1)`, ya que en el return siempre va a ir de izquierda a derecha. Es decir que lo primero que hará tu programa sera calcular `fib(n)`, `fib(n-1)`, ... , `fib(2)`, `fib(1)`. Una vez terminando este proceso (que es muy rápido) seguira con todos los otros cálculos, pero como ya tiene guardado todos los valores de 1 a n en el dict no se demora nada.
