### ISSUE TITLE
Error de pull Ayudantía 3

### ISSUE THREAD

**Issue by sreitze** [IIC2233/syllabus#318]
Hola, estoy tratando de pullear la ayudantía 3 y me aparece esto. Saben que puedo hacer?
![Anotación 2020-09-02 154113](https://user-images.githubusercontent.com/69603335/92028964-dbccc800-ed32-11ea-85f8-19f03a5c2889.png)

**Comment by Baelfire18** [comment]
Intenta poniendo en git bash:
`git stash`
`git pull`
`git stash pop`

**Comment by sreitze** [comment]
Ahi funcionó gracias!
