### ISSUE TITLE
Consultas y estadísticas sobre el grafo de afinidad

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#318]
Hola, revisando mi tarea me di cuenta de que no existe ningún método de la GUI para consultar sobre las estadísticas del grafo de afinidad ¿es esto un problema y debemos implementar algún método para que el usuario consulte a través de la interfaz? ¿o simplemente debemos definir las funciones y evaluarán la lógica de estas?

**Comment by monicabelen** [comment]
Lo deben realizar en consola. Lo mismo que hicieron para la T01.

**Comment by santilaguna** [comment]
@monicabelen Entonces, ¿como hacemos para volver a la consola si al abrir demo.py se inicia la interfaz? Me refiero a cómo le pregunto al usuario si quiere consultar los gráficos. 
Si me puedes explicar como es la interacción con el usuario lo agradecería, porque como no hemos visto interfaces gráficas no entiendo muy bien como realizar estas acciones.
