### ISSUE TITLE
Duda sobre existencia de jardines.txt y otros documentos

### ISSUE THREAD

**Issue by PazArenas** [IIC2233/Syllabus#318]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Al tratar de abrir los archivos de jardines.txt me aparece error porque me dice que dicho file no existe. Me pasa lo mismo con los demás archivos y no entiendo porqué.

**Comment by CatalinaBO** [comment]
Hola! Tienes los archivos de texto ubicados en la misma carpeta que tienes tu código?

**Comment by PazArenas** [comment]
Sii. Capaz influye en algo que ya puse los archivos en el .gitignore?

**Comment by CatalinaBO** [comment]
No debería ser eso, ya que el .gitignore sirve para que Git ignore los archivos que les indicas. Por ende, esto no debería afectar a la capacidad de tu código para leer esos archivos. Debes fijarte que efectivamente lo archivos se encuentren en la misma carpeta de tu código (volver a agregarlos si los eliminaste de la carpeta) y que al momento de leer el archivo pongas la ruta correcta, incluyendo la extensión .txt en el nombre del archivo.

**Comment by PazArenas** [comment]
Revisé y si están en la misma carpeta que el código que estoy editando. Incluso borré los archivos y los volví a copiar en la carpeta para asegurarme pero me sigue saliendo que no existen

**Comment by CatalinaBO** [comment]
Revisando tu repositorio, veo que en tu archivo ayuda.py estas usando el comando os.path.exists, sin embargo no estás proporcionando el path correcto. En caso de que estes tratando de leer el archivo de esa forma, te recomiendo repasar el contenido de paths para poder abrir archivos!

**Comment by PazArenas** [comment]
Sisi, el archivo ayuda.py que tengo lo cree para tratar de ver si es que en otro archivo si me aparecía que existían los demás archivos utilizando un comando distinto (os.path.exists), pero este no es mi archivo principal en donde me sale el error. En el archivo mismo que voy a entregar (main.py) abrí cada archivo utilizando el comando open("jardines.txt","r"), y aún así me tira error. A esto te refieres con el path correcto para abrir archivos?

**Comment by bibarra9** [comment]
> Sisi, el archivo ayuda.py que tengo lo cree para tratar de ver si es que en otro archivo si me aparecía que existían los demás archivos utilizando un comando distinto (os.path.exists), pero este no es mi archivo principal en donde me sale el error. En el archivo mismo que voy a entregar (main.py) abrí cada archivo utilizando el comando open("jardines.txt","r"), y aún así me tira error. A esto te refieres con el path correcto para abrir archivos?

Te lanza error porque no estás especificando que el archivo `jardines.txt` se encuentra en la carpeta `data`. Para que la dirección del archivo sea la correcta debes utilizar la función `os.path.join()` para poder hacer esto adecuadamente sin preocuparse del sistema operativo en el que se trabaja.

**Comment by PazArenas** [comment]
Perfectoo, ahí me funcionó. Gracias!
