### ISSUE TITLE
Aumento de salud por Magizoólogo Tareo

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#318]
Hola, cuando se menciona "al alimentar a sus DCCriaturas poseen un 70% de probabilidad de recuperar toda la salud actual de la criatura"; no entiendo muy bien a qué se refiere. Porque si esto sucede, entonces la salud actual de la criatura ahora será igual a la salud total que tenía al principio del día? o qué?

**Comment by mpsubiabre** [comment]
Hola @Camila-sty !

Lo que hace referencia a que al alimentarla, con un 70% de probabilidad, recuperara todos los puntos de salud total, es decir quedara en el su máximo permitido.

**Comment by Camila-sty** [comment]
Hola.
Aún me queda la duda. Qué es lo que aumenta de la criatura, los puntos de salud total o actual?, porque en el enunciado dice *actual* y no  *total* como es lo que me respondieron.
Lo otro, a que valor se refiere cuando dice que "recupera toda la salud". Se refiere a los puntos de salud total? o a los puntos máximo total según el rango dado para los 3 tipos de criaturas distintos..¿?

**Comment by mpsubiabre** [comment]
Hola @Camila-sty!

Lo explicare de otra manera, recuerda que los puntos de **salud total** es el numero **máximo** al que pueden llegar los puntos de **salud actual** de la criatura. Por esto, cuando se indica que "recuperar la salud actual de la criatura que recibió el alimento" hace referencia a que los puntos de salud actual llegaran a su máximo. Por ejemplo, la salud total de la criatura es 100 (la salud Máxima a la cual puede llegar), y por diversas circunstancias (como por pasar hambre o enfermarse) la criatura en estos momentos tiene puntos de salud actual igual a 30. “Recuperar toda la salud actual” hace referencia a que, la **salud actual tome el valor de la salud total**, que vuelva a "sanarse a su máximo", es decir, los puntos de salud actual tomaran el valor de 100.

Recuerda que para cada **nueva** criatura, tiene como atributo esta cantidad de *salud total*, la cual se mantiene constante. Solo para definirla se realiza de forma aleatoria en ciertos rangos.

Cada criatura nueva comienza como punto de **salud actual** igual a los puntos de salud total, y son los puntos de salud actual los que irán variando.

Espero que te haya quedado más claro, de lo contrario comenta cualquier duda que te quede :)
