### ISSUE TITLE
Problema con configuración maximo caracteres por linea

### ISSUE THREAD

**Issue by MCorbella99** [IIC2233/syllabus#318]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola, estuve revisando todos los issue relacionados con este tema y luego de intentar todo no pude configurar correctamente VS Code para que dejara de marcarme como error las líneas mayores a 79 caracteres. (Quiero que sea de 100 para arriba)
Intente configurando pycodestyle en la carpeta python pero no cambio nada y adjunto una foto de como está mi JSON actualmente (lo deje igual a la issue que lo solucionaba así pero cuando lo cierro se vuelve a este formato).
![Captura](https://user-images.githubusercontent.com/80912799/115948820-733b8280-a49e-11eb-907d-07075e9beefd.PNG)

**Comment by Christian-Klempau** [comment]
Hola! Efectivamente es un poco extraño, ya que con esa línea debería efectivamente cambiarse al máximo de 100 caracteres. Podría ser que no tengas _pycodestyle_ activado y estés ocupando otro linter? (con Ctrl+Shift+P te sale la ventana para buscar _settings_ arriba en VSCode, y escribes "linter" y debería aparecer algo como "Python: select linter", haces enter y seleccionas pycodestyle).
En cualquier caso, te dejo mis settings.json que tengo en VSCode, con los cuales efectivamente se fija el máximo de caracteres como 100. 
![max_line_100_vscode](https://user-images.githubusercontent.com/62039719/115976705-ae8d8e00-a53e-11eb-93eb-782091291e5f.PNG)
