### ISSUE TITLE
me fallo pc para esta actividad

### ISSUE THREAD

**Issue by glbello** [IIC2233/Syllabus#319]
Saludos a todos, tuve problemas anoche con mi note y traje otro pero no tengo python y editor y por más que trato no logro bajarme python (intenet uc plz, 4g plz(q nunca me agarró)) así que quería saber si alguien me pudiese ayudar, prestarme el python 32 bits win10 3.6 y algun editor si fuera atom, pycharm, sublime... lo que sea :/

PD: soy muy cuidadoso con el keyboard (teclado)

**Comment by andresfdezc** [comment]
Por favor envíale un mail a jpg@uc.cl con copia a tu profesor. Él te puede prestar un computador del DCC. Hazlo ya!

**Comment by glbello** [comment]
Sé que lo cerraron pero quería agradecer la respuesta, y pude conseguir un notebook por este medio, se pasaron :)
