### ISSUE TITLE
Error Importación PyQt5

### ISSUE THREAD

**Issue by tcperez** [IIC2233/syllabus#319]
Hola!

Usando pip install instalé PyQt5 para python 3. Luego ejecuté < import PyQt5 > en Pycharm y no tuve problema, lo malo ocurrió cuando ejecuté:

< from PyQt5.QtWidgets import QWidget, QApplication >

El programa me arroja el siguiente error:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from PyQt5.QtWidgets import QWidget, QApplication
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyQt5/QtWidgets.so, 2): Symbol not found: __os_activity_create
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore

He buscado mucho pero no sé cómo solucionarlo :(  

Gracias de antemano.

**Comment by jmwielandt** [comment]
Hola!

Ese error es porque tienes una versión del sistema operativo anterior a Mac OS X 10.12, y la versión de pyqt5 que instalaste requiere que sea una mayor o igual a esa.

Tienes dos opciones:
1. Actualizar el sistema operativo.
2. Desinstalar PyQt5 e instalar la versión 5.10.1 de PyQt5 con el comando

```bash
pip3 install PyQt5==5.10.1
```

Es un error que ya vimos el semestre pasado y costó encontrar la solución 😅 

Saludos y espero que te sirva 👍

**Comment by tcperez** [comment]
Me funcionó! Muchas gracias!
👍👍
