### ISSUE TITLE
Duda con exec

### ISSUE THREAD

**Issue by enriqueb98** [IIC2233/Syllabus#319]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/293)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Una duda chica que se supone que no podemos usar exec pero siempre en los ejemplos que hemos visto cuando hacemos interfaz grafica al principio inicializamos la aplicación y al final ponemos sys.exit(app.exec_()), no se si esto sea aparte y no importe espero que no ya que también lo puse en la T2 pero no e encontrado ejemplos dentro de las clases en que no se ponga al final

**Comment by knight-who-says-ni** [comment]
Hola @enriqueb98!!

Tu duda ya fue respondida aqui: https://github.com/IIC2233/Syllabus/issues/215#issuecomment-957754090

Saludos!!
