### ISSUE TITLE
definicíon de error/robustez en el programa.

### ISSUE THREAD

**Issue by jervaal** [IIC2233/syllabus#319]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, duda es sobre donde pueden estar los errores.

Se que pueden haber errores de input (que se seleccione una opcion que no exista), pero me surgio la duda si pueden haber errores en los datos .csv (que una de los datos en vez de llamarse tamaño, se llame largo, que falte una coma, etc.). De ser así, ¿como se procederia a realizar esto?

De antemano, muchas gracias

**Comment by Emiliax16** [comment]
Hola @jervaal ! respecto al archivo canales.csv, tamaño se refiere al atributo _largo_ de la entidad canales, poseen el mismo valor. 
En ningún archivo debería haber errores de formato, ya que fueron creados de tal forma que el formato que está en la primera línea es repetido para todos los datos.

Saludos.

**Comment by jervaal** [comment]
¿Entonces los unicos errores que tenemos que contemplar serán de inputs? (ya que los posibles ValueErrors, TypeErrors estan contemplados que no pasarán, debido al correcto formato de los archivos .csv ?)

**Comment by Emiliax16** [comment]
Exactamente. Suerte en tu tarea c:

**Comment by jervaal** [comment]
Muchas graciaas, ahora entendi uwu

**Comment by Emiliax16** [comment]
de nada!
