### ISSUE TITLE
Duda sobre .split()

### ISSUE THREAD

**Issue by mpuntous** [IIC2233/Syllabus#319]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Se que la pregunta puede ser media tonta, pero al final del enunciado nos dicen que no se puede utilizar .split(), esto también aplica para cargar_datos()? y otra cosa, en todas las funciones es necesario ocupar programación funcional? porque hay una en que me sale mucho mas sencilla con un simple for. Muchas Gracias.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mpuntous** [comment]
en la del for no me piden que devuelva un generador, solo un int.

**Comment by ClemoAcevedo** [comment]
Hola @mpuntous , en #298 explican que .split() si se puede ocupar para cargar datos pero no para las consultas.
Y sobre tu segunda pregunta: Sí, es necesario utilizar programación funcional en todas las funciones tal como lo especifica el enunciado. La idea es que practiques y apliques técnicas de programación funcional, incluso si pareciera ser más sencillo usar un bucle for. De todas formas te recuerdo que el uso de for se permite en funciones generadoras, listas o diccionarios por compresión y dentro de reduce. Buena suerte!
