### ISSUE TITLE
tiempo_movimiento_fantasmas

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2233/Syllabus#319]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

El tiempo de movimiento fantasmas corresponde a cuanto debe esperar el fantasma para moverse a otra casilla luego de avanzar a una o corresponde a cuanto tiempo se debe demorar en avanzar una casilla. En caso de ser la primera, cuanto tiempo se debe demorar el fantasma en avanzar una casilla considerando que el movimiento debe ser continuo de los sprites

**Comment by Hernan4444** [comment]
Hola @SantiagoDLCB 

Dicho tiempo corresponde a cuanto debe pasar entre el movimiento de casilla A -> B, y de B-> C. Ahora bien, al momento de escribir el enunciado, lo pensamos como el segundo caso que describes: es el tiempo total que se demora en avanzar a una casilla. Y durante ese tiempo, la idea es ver como se mueve de a poquito y animadamente a dicha casilla. 

No obstante, no quedó totalmente claro, así que queda a tu criterio si prefieres hacer la opción (1). Si haces esa, el tiempo que se demora de una casilla a otra quedaría a criterio tuyo, mientras ese tiempo sea menor al calculado por la fórmnula. Por ejemplo, si la formula dice que el tiempo es 2 segundos. La esperado es que el proceso de moverse de A->B tome 2 segundos y luego de B->C sean otros 2 segundos. Usando esta forma, podrías decidir que la animación de movimiento tomará 1 segundo, y luego el fantastma esperará 1 segundo más en esa casilla antes de moverse. Con eso respetas el tiempo calculado por la formula, pero lo haces en función de 2 etapas: un movimiento y un tiempo de espera.

Espero que esto haya aclarado tu duda, sino nos puedes preguntar por aquí para seguir aclarando tu duda sobre el tiempo de movimiento del fantasma.

Saludosヾ(＾-＾)ノ

**Comment by SantiagoDLCB** [comment]
En ese caso no se puede hacer un movimiento absolutamente continuo? Osea si el tiempo es 2 segundos el fantasma no puede demorarse 2 segundos en cambiar de casilla y altiro moverse a la siguiente, demorandose 0 segundos en empezar otro cambio de casilla?

**Comment by Hernan4444** [comment]
Hola @SantiagoDLCB 

Si, si es posible, y sería justamente la opción 2 que diste en el mensaje original:

> corresponde a cuanto tiempo se debe demorar en avanzar una casilla. 

Es factible que si el tiempo es 2 segundos, se demore justamente 2 segundos en llegar a la siguiente casilla y de ahí comience inmediatamente el movimiento a la siguiente casilla que le volverá a tomar 2 segundos más.

Saludosヾ(＾-＾)ノ

**Comment by tomastrivino** [comment]
@Hernan4444 No me quedó muy claro... ¿Puedo hacer que ese tiempo corresponda a mi "timeout"? vale decir, que sea como el siguiente flujo:
Si el `tiempo` dado por la fórmula es 2, entonces:
Inicialmente, espera 2 segundos para moverse desde A->B.
Luego de que se mueve a B, espera otros 2 segundos para moverse desde B->C.

Todo esto conservando un "framerate" constante de las animaciones (es decir, que va con una misma velocidad de animación desde una casilla a otra, solo que con un intervalo de tiempo que está dado por la formula). ¿Se puede hacer así?

Gracias

**Comment by Hernan4444** [comment]
Hola @tomastrivino 

Revisamos tu caso con los ayudantes, y es una interpretación válida. Así que lo puedes hacer de dicha forma. Pero esa constante que define el framerate deberá estar entre los parámetros por si queremos editarla para ver una animación más rápida entre una casilla y otra.

Además, te recomendamos agregar esta interpretación en el Readme para que el ayudante sepa cómo enfrentaste el movimiento y que ahora usas 2 constantes (una de framerate y otra de timeout).


Saludosヾ(＾-＾)ノ

**Comment by tomastrivino** [comment]
Ok, perfecto, tengo un parámetro que establece el tiempo que dura cada sprite (en ms). Como son 3 sprites para cada animación, si el parámetro corresponde a 30ms, entonces la animación durará 90ms. ¿Está bien? Cabe destacar que ese tiempo será constante para todos los elementos que sean animados, independiente de su tipo (Luigi no se moverá más rápido que un fantasma, por ejemplo).

Muchas gracias y disculpa la hora

**Comment by Hernan4444** [comment]
Hola @tomastrivino 

Si, es válido.

Saludosヾ(＾-＾)ノ
