### ISSUE TITLE
Nivel de aprobación inicial

### ISSUE THREAD

**Issue by 18638333** [IIC2233/syllabus#319]
Hola, cuando se crea un nuevo magizóologo, cual debería ser su nivel de aprobación inicial?

**Comment by matiasmasjuan** [comment]
Hola @18638333 !

Si bien no se indica **explícitamente** en el enunciado, puedes crear un **parámetro** que indique el nivel de aprobación inicial de **Magizoólogo**. Te recomiendo un valor entre **60** y **100**, ya que la idea es que el nuevo **Magizoólogo** parta con su **licencia** (según lo que indica el enunciado).

Saludos!

**Comment by furcelay** [comment]
Hola!, 
No soy ayudante, pero creo que el valor de aprobación inicial puede definirse con la misma fórmula **calcular nivel de aprovación** que resultaría en 100 para un magizoólogo que acaba de inicializarse. Si fijas un valor como un parámetro este se sobreescribiría inmediatamente por lo que no tiene mucha utilidad...

**Comment by matiasmasjuan** [comment]
Hola @furcelay !

Efectivamente, el valor de **aprobación inicial** del **nuevo Magizoólogo** puede calcularse a través del método del **DCC**: **calcular nivel de aprobación**. Sin embargo, esto lo realiza cada vez que se *pasa al día siguiente*, por lo que no contaría al momento de **crear** al **nuevo Magizoólogo**. Como esto no se indica **explícitamente** en el enunciado, pueden hacerlo de **ambas** formas. (estableciendo un **parámetro**, o mediante **calcular nivel de aprobación**).

Muchas gracias @furcelay por la acotación!

**Comment by MINGOD24** [comment]
Hola,

Para los magizoologos ya existentes, el primer dia debo calcular su nivel de aprobación con la formula al principio del programa, o debo ingresarlo con un parametro?

**Comment by matiasmasjuan** [comment]
Hola @MINGOD24 !

Dado que al cargar un **Magizoólogo** ya **existente** cuenta con todas las **variables definidas** para utilizar la fórmula del **DCC**: ***Calcular nivel de aprobación***, lo mejor sería definir su **nivel de aprobación** mediante la **fórmula**.

Saludos!

**Comment by Camila-sty** [comment]
Hola!
No me queda claro la parte de calcular el nivel de aprobación, ya sea para un magizoólogo nuevo o ya existente. En el enunciado tampoco dice que al iniciar el día se debe calcular el nivel de aprobación. Lo que yo asumí, es que este valor solo existe cuando se elige la opción *pasar al día siguiente*, por lo tanto sólo aparece recién ahí.
Ahora la duda que tengo, es que si al iniciar el día, el magizoólogo opta por la opción *Mostrar estado de Magizoólogo y DCCriaturas*  pero aún no ha ido por *pasar al día siguiente*, el "nivel de aprobación" no va a existir, asumiendo su valor como cero. 
Esta bien esto? o me recomiendas usar la fórmula para calcular su nivel de aprobación?

**Comment by Camila-sty** [comment]
Tengo que mencionar que calcularlo con la fórmula, me lleva a editar el código y se me hace un poco complicado. Yo solo quería saber si asumir su valor como "cero" estaba bien.

**Comment by matiasmasjuan** [comment]
Hola @Camila-sty !

Tienes toda la razón. Dado que esto no se **explicita** en el enunciado, puedes optar por las dos formas, y eres libre de escoger cualquiera de las dos:

1) Realizar un **parámetro* sobre el nivel de aprobación inicial del Magizoologo.
2) Calcular el nivel de aprobación del día 0 con la fórmula de *calcular nivel de aprobacion*.

Si optas por la primera, vuelvo al primer comentario: 

*"Si bien no se indica **explícitamente** en el enunciado, puedes crear un parámetro que indique el nivel de aprobación inicial de **Magizoólogo**. Te recomiendo un valor entre 60 y 100, ya que la idea es que el nuevo **Magizoólogo** parta con su licencia (según lo que indica el enunciado)."*.

Y si optas por la segunda, debes calcularlo mediante este método.

Respondiendo a tu pregunta, no creo que sea **correcto** establecer el **nivel de aprobación** inicial igual a 0, ya que la idea es que el **Magizoologo** parta con la licencia, por lo que te recomendaría hacer un **parámetro** para esto.

Espero haber respondido a tu pregunta, y mucho éxito con tu tarea! 😄

**Comment by Camila-sty** [comment]
qué tiene que ver que el parámetro de nivel de aprobación con partir con su licencia ?

**Comment by matiasmasjuan** [comment]
Recuerda que el enunciado señala lo siguiente:

![nivel_aprobacion](https://user-images.githubusercontent.com/48495638/79398327-6e202b00-7f4e-11ea-998c-5495217cf66a.PNG)

Además, si te fijas en la sección de la definición de la licencia

![licencia](https://user-images.githubusercontent.com/48495638/79398363-8b54f980-7f4e-11ea-9d16-d6591df77763.PNG)

Como el **Magizoolgo** parte con la licencia, y sabes que si el **nivel de aprobación inicial** es menor a 60, habría una **contradicción**, ya que sabes que por la definición de licencia: *Si el Magizoólogo tiene un nivel de apobación inferior a 60, pierde la licencia*.
Para evitar esta contradicción, te sugiero para que no te moleste tanto cambiar tu código, simplemente establecer un **parámetro** con el nivel de **aprobación inicial** entre 60 y 100.

Saludos! 😄

**Comment by Camila-sty** [comment]
Toda la razón. Aún no veía esa parte entonces no estaba aún en mis conocimientos jaja.
Gracias! :smile:
