### ISSUE TITLE
Contenidos S3: Property en Abstract Class

### ISSUE THREAD

**Issue by camirojasguajardo** [IIC2233/syllabus#319]
Hola! Tengo una duda con respecto a un ejemplo que se plantea en el cuaderno de clases abstractas. Es el siguiente:

class Base(ABC):

    @property
    @abstractmethod
    def valor(self):
        return '¿Llegaremos aquí?'
En este código nunca se define el atributo oculto al que se le aplicará la property, sin embargo, igual funciona. Mi pregunta es ¿por qué? jaja.
Saludos!

**Comment by dchahuan** [comment]
La respuesta a esto es que un propery no necesariamente tiene que tener un atributo por detrás. Es como un metodo que le podemos dar dos versiones(get,set) pero como dije antes no es obligatorio tener un atributo.
