### ISSUE TITLE
Potencial solaretillo

### ISSUE THREAD

**Issue by mrebolledo03** [IIC2233/Syllabus#319]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

No entiendo en el enunciado si es que nos dan el valor del potencial del solaretillo, o lo invento yo? Y no todos los solaretillos tendran el mismo valor inicial de potencial o si?

**Comment by rodrigoaguilera15** [comment]
Hola. El enunciado dice que el atributo potencial de cada solaretillo debe ser un número aleatorio entre "POTENCIAL_SOLARETILLO_MIN y POTENCIAL_SOLARETILLO_MAX". Esto significa que cada planta tiene su número fijo, pero aleatoriamente generado, entre esos dos parámetros. Aclaración: todo lo que esté en **azul y mayúsculas** es un **parámetro**, y todos los parámetros deben ser definidos arbitrariamente por uds. a menos que se diga explícitamente su valor en el enunciado, el cual es el caso menos frecuente. Reacciona con pulgar arriba si eso responde tu pregunta, saludos.
