### ISSUE TITLE
Existe algun problema con no usar todas las funciones de la entrega intermedia?

### ISSUE THREAD

**Issue by dvillas28** [IIC2233/Syllabus#319]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Especificamente algunas funciones de `funciones_cliente.py`, viendo como estoy pensando la implementacion de la logica del juego, siento que no me van a a ser 100 % de utilidad.

No descarto que las vaya a usar despues (si es que mi implementacion fracasa), pero quiero saber si existe una penalizacion de puntaje por no usarlas *todas*

Saludos!

**Comment by AntonioVenegas** [comment]
Hola!, la idea es que usen las funciones que ya crearon donde correspondan en la entrega final, si necesitan, pueden modificarlas en caso de tener que adaptarlas al código.

Saludos :)

**Comment by dvillas28** [comment]
Hola, al final le logre encontrar un uso acorde a mi implementacion, con un poquito de adaptacion jaja, ¿Eso de deberia de especificar en el readme no?
Saludos!

**Comment by AntonioVenegas** [comment]
En general, si es que ayuda a entender tu tarea deberías ponerlo en el readme, dado lo anterior, puedes poner una breve descripción de como lo adaptaste a tu código ;)

**Comment by benjaminsalgado** [comment]
Hola, en el caso de no utilizar 2 de las funciones que hicimos en la entrega intermedia, el descuento será mucho? es que mi implementación inicial consideraba usar el tablero solo para aparecer las entidades al inicio y que estas interactuaran entre si mediante señales, por lo que las funciones riesgo_mortal y validar_direccion las estoy ignorando.

**Comment by AntonioVenegas** [comment]
Hola @benjaminsalgado, no te puedo responder específicamente cuales o cuantas son las funciones que si o sí deben integrar, ya que la idea es que ustedes mismos identifiquen cuales son las funciones que necesitan para esta tarea. Pero algunas esperamos que si se den cuenta que deben ser integradas, mientras que otras talvez no sean tan obvias (en cuyo caso, no habría descuento si no las integran). Igual lo puedes poner en tu readme si es que no estás seguro.

Saludos :)
