### ISSUE TITLE
Número de caracteres usuarios T00

### ISSUE THREAD

**Issue by sofiaemd** [IIC2233/syllabus#32]
Hola! En la tarea sale que los usuarios deben tener un  mínimo de 8 caracteres, pero hay algunos (Juan379, 1gbasly, szabal4 y lily416) que tienen 7 caracteres.

**Comment by DCCollao** [comment]
Hola!

Muchas gracias por avisar, acabamos de actualizar los archivos corrigiendo el largo de los nombres de usuario. Si encuentras algún otro error, por favor hazlo saber!

Éxito!

**Comment by sofiaemd** [comment]
Muchas gracias!!
