### ISSUE TITLE
Cargar partida

### ISSUE THREAD

**Issue by raimundoloeser** [IIC2233/syllabus#32]
Al cargar la partida, debemos eliminar este archivo? O si el jugador pierde puede volver a cargar la misma partida desde donde fue guardada?

**Comment by gatochico** [comment]
Hola!

No es necesario que borres el archivo .txt una vez cargado, por lo que se podria cargar dicho archivo más de una vez. Saludos!

**Comment by raimundoloeser** [comment]
Perfecto, gracias!
