### ISSUE TITLE
Dudas properties

### ISSUE THREAD

**Issue by nimorales97** [IIC2233/Syllabus#32]
Hola!
Aún no termino de entender todos los usos de los properties, estaba releyendo el apunte de eso [https://github.com/IIC2233/contenidos/blob/master/semana-1/03-Properties.ipynb](url), quise experimentar y ejecuté en mi pc el siguiente código que sale en "¿Cuándo usar properties?"
![captura1](https://user-images.githubusercontent.com/30670006/29253922-cdabd5d8-805f-11e7-9a9d-214381725ab6.PNG)
Primero ejecuté el código sin cambiar nada y obtuve los valores 1.23 y 0.0. Luego que hice fue comentar lo de @property y ejecuté sólo para ver qué pasaba, obtuve dos veces 0.0. Por último en la parte siguiente del código agregué paréntesis en los contenido_1 = page.content() y ejecuté de nuevo y obtuve 1.47 y 0.0. 
¿Por qué esos cambios? Me interesa saber qué es lo que cambia al usar @property y por qué en el segundo intento me dio 0.0 dos veces en lugar de tirarme un error.
De antemano gracias

**Comment by KnowYourselves** [comment]
Lo primero que hay que entender es el uso de los properties.

Los properties te permiten agregar funcionalidades a atributos. Una property tiene 3 funcionalidades differentes:

- Setter
- Getter
- Deleter

El setter es el que creas al poner @property.
La gracia de este setter es que es ejecutado cada vez que llamas al atributo.

```
Class Circulo:

    def __init__(self, radio):
        self.radio = radio
        self.area = radio * 3.14
```
 
Por ejemplo este código representa un círculo, supongamos que creamos un círuclo de radio 1. En este caso su radio sería 1 y su área 3.14 qué pasa ahora si cambiamos el radio de la froma `circulo.radio = 2`?
El area sigue siendo 1, ya que esta no se re define automaticamente. 

Aquí es donde entra la utilidad de property. Al definir un atributo con property **cada vez que llames al atributo** se ejecutará. Esto quiere decir que si cambiamos el código de la siguiente manera: 

```
class Circulo:
    def __init__(self, radio):
        self.radio = radio
        self._area = None

    @property
    def area(self):
        return self.radio * 3.14
```

Con este código cada vez que ejecutes `circulo.area` el programa irá directamente al property y retornara `radio *  3.14`, de esta manera puedes cambiar el radio sin tener que cambiar manualmente al área. 

Una forma fácil de verlo es la siguiente, Si un atributo depende de otro, entonces podría ser buena idea hacerlo property.

En el código que muestras el property content funciona de la siguiente manera:

1.  Revisa si content es Fasle (None == False)
2. Si content es None, lo redefine como los contenidos de la url.
3. Retorna content

Es decir que la primera vez que llamas a content lo redefine y lo retorna mientras que la segunda vez como content ya no es None lo retorna directamente. La segunda parte del código te imprime cuanto se demora en cada proceso.  Imprime 1.23 y 0 respectivamente al primer intento porque en el primer llamado ejecuta el if (ya que content es None) mientras que en la segunda pasa directamente al return.

En el segundo caso al comentar `@property` content deja de ser una property y pasa a ser un método, por lo cual al hacer `page.content` python simplemente te dice que content es un método de la clase WebPage, lo cual se demora practicamente nada, por eso te imprime 0.

Finamente en tu tercer caso al cambiar contenido_1 a `page.content()` a diferencia del caso enterior ejecutas el método content, por lo cual se demora más y te imprime 1.47, mientras que contenido_2 sigue demorandose nada por la misma razón que te explique antes.

**Comment by nimorales97** [comment]
Me quedó claro, gracias!

**Comment by benjastraub** [comment]
@KnowYourselves me quedan dos dudas respecto a lo que pusiste:

1. ¿En qué caso debería usar por ejemplo `@area.setter` y luego definir area de nuevo bajo ese decorador?

2. ¿Por qué defines `self._area` y por qué lleva un underscore?

**Comment by KnowYourselves** [comment]
En primer lugar en properties el setter es usado para interceptar la redefinición del atributo. Esto quiere decir que cada vez que hagas algo de la forma `self.area = 10` y tienes `@area.setter` definido, se llamará a este. El setter es bastante versatil por lo cual no hay una "regla general" de cuando aplicarlo. Usualmente si tienes atributos complejos que requieren de muchos pasos para ser redefinidos puedes usar setter.
Un ejemplo que se me ocurre es el siguiente, como bien se sabrá ahora es posible trabajar con múltiples personas a la vez en archivos word, excel, etc. Pero si una persona sin autorización intenta cambiar algo del archivo no se permite. 
```python
@area.setter
    def area(self, value):
        print("Acceso denegado.")
```
Agreando este extracto al código ya presentado evitara que `self.area` sea redefinido. Podría ser modificado para recibir certificación, etc. (cabe recalcar que si defines un property sin un setter tirara error al intentar redefinir el atributo)

En segundo lugar, hago esa definición por la siguiente propiedad de properties:

```python
@property
    def area(self):
        print(self.area)
        return self.radio ** 2 * 3.14
```
Este código generará un error de recursión, ya que al llegar a `print(self.area)` llamará de nuevo a la property y se generará un bucle infinito. Entonces si quisieras guardar la información de una property en otra variable (como en el ejemplo original de esta issue) por convención se hace de la forma `_variable`. El underscore se utiliza por convención. En PEP8 un underscore antes de un atributo o método significa que este es de uso interno. De hecho al importar módulos python ignorará las variables que empiezen con underscore por lo mismo. En este ejemplo específico del círculo si bien no utilizo `self._area` es buena práctica siempre definir ese tipo de variables al utilizar properties por si llegan a ser necesarias más adelante en el proceso de desarrollo.
