### ISSUE TITLE
visual studio Terminal Mac

### ISSUE THREAD

**Issue by bigtere** [IIC2233/syllabus#32]
![error 1](https://user-images.githubusercontent.com/69727438/90349883-572b3b80-e009-11ea-8384-63671f2d57c1.jpeg)
no me abre el terminal cuando quiero correr el código, intente cambiar el nombre de la carpeta porque tenia un acento y pensé que eso estaba ocasionando el problema, pero ahora ni si quiera se quiere abrir , que hago?

**Comment by tomasgv** [comment]
¡Hola @bigtere!

Por el momento veo dos casos posibles:
- Si cambiaste el nombre desde fuera de VS Code, posiblemente el programa no se haya actualizado correctamente y siga buscando el archivo dentro de un directorio con el nombre anterior al cambio, y por lo tanto no lo encontraría. En este caso reiniciar VS Code solucionará el problema.
- En ocasiones hay problemas al ejecutar archivos dentro de directorios con nombres separados por espacios (depende de cómo hayas escrito el comando para ejecutarlo). En macOS, se debe escribir un _backslash_ (`\`) antes de cada espacio en los nombres de archivos, o de lo contrario el terminal creerá que su nombre termina antes. No deberían haber problemas si tienes la extensión de Python instalada y usas _click_ derecho > _Run Python file in Terminal_.

Para abrir el terminal de VS Code puedes hacer `Ctrl` + ``` ` ```, o también puedes hacer _click_ en _View_ > _Terminal_.

¡Espero haberte ayudado! 😸

**Comment by bigtere** [comment]
gracias ahora si se me abre el terminal y encontro perfect la carpeta, aunque ahora no me corre el codigo, pense que era un error en el codigo y intente copiar los ejemplos de la materia para asegurarme de tener una respuesta y claramente le pasa algo al programa que no quiere leer el lenguaje python
![issue 1](https://user-images.githubusercontent.com/69727438/90557044-e3537500-e167-11ea-9420-2b80b7b4d261.jpeg)

**Comment by tomasgv** [comment]
Ojo con la versión de Python!

Los sistemas macOS vienen con Python 2.7 instalado por defecto, por lo que al usar el comando `python` utilizaste esa versión y no la que querías. Para solucionar esto puedes usar `python3` 🎉 .

Según la captura de pantalla adjunta, abriste Python 2.7 en la terminal misma de VS Code y luego pegaste una línea a la cual parecen faltarle las comillas al _string_, resultando en un `SyntaxError`:cry: . Para ejecutar el archivo que tienes abierto puedes escribir `python3 nico.py` en esa terminal o hacer _click_ derecho > _Run Python file in Terminal_, o posiblemente también sirva hacer _click_ en el ícono semejante a un botón _play_ en la esquina superior izquierda.

Quedo atento por si aún tienes dudas! :eyes:

**Comment by bigtere** [comment]
intente de las tres formas y me sigue lanzando error
![issue 2](https://user-images.githubusercontent.com/69727438/90637099-8c967b80-e1f9-11ea-9999-d20a4659e5ef.jpeg)

**Comment by tomasgv** [comment]
Hay avances! 🎉 

Si te fijas en la ubicación mostrada en la terminal, notarás que ahora sí estás usando Python 3.7 😄  . 

En la sección donde se ingresa el comando, notarás que la preceden los caracteres `>>>`. Esto indica que tienes abierta la **consola interactiva de Python**, la cual se abre cuando escribes en la terminal `python` o `python3` sin ningún nombre de archivo. Esta es la razón por la cual no te funcionó escribir `python3 nico.py`. Puedes salir de este modo escribiendo `exit()`.

Dado que han existido varios problemas, te recomiendo probar con un archivo simple, por ejemplo el clásico `print("Hola Mundo")`. De este modo podrás identificar si el error se origina en el archivo o en la ejecución misma.

Avísame cómo te va! 👀

**Comment by bigtere** [comment]
muchas gracias ahí me funcionó!!!! yeiiiiii
