### ISSUE TITLE
Duda tarea sobre riego de planta

### ISSUE THREAD

**Issue by Agusrush21** [IIC2233/Syllabus#32]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola espero que tengan un buen día. Mi duda es bien simple.
Cuando planto una planta esta tiene un numero (que varia del 0 al 9), al momento de regar en área, la planta que esta dentro de esta, se le suma 1 a la planta, por lo que me da entender que el numero representa el nivel de riego o que tan regada esta. Entonces si esta planta tiene como numero 9 y se riega ¿Qué pasa con la planta?, ¿vuelve a 0?, ¿no se riega?, ¿la planta se "muere"? o ¿continua la numeración?, pregunto dado que el enunciado no describe esa situación.

**Comment by vgalfaro** [comment]
Hola! en un mismo predio se tiene un plano (donde se cultivan las distintas plantas con sus respectivos códigos) y un plano riego, estos son independientes, por lo que cuando riegas se editan los valores del plano riego no los del plano de cultivos. Espero haber contestado tu duda!

**Comment by Agusrush21** [comment]
Vale gracias @vgalfaro , y perdon exprese mal mi pregunta no debi agregar la parte de plantar.
Mi duda va mas a que si en el plano de riego hay una planta con el numero 9 y esta se riega ¿Qué pasa con esa planta?

**Comment by vgalfaro** [comment]
Son dos planos distintos, por lo que al regar no afectas el plano de los cultivos, la planta con el número 9 queda como estaba, al igual que todo el plano de cultivos!

**Comment by Agusrush21** [comment]
Vale gracias @vgalfaro, solo para confirmar que entendi lo que me dice
Osea si yo riego el plano_riego y riego una celda que tiene 9 esta se mantiene en 9

**Comment by vgalfaro** [comment]
Así es, si riegas no afectas al plano de cultivos, son planos independientes. Saludos!

**Comment by Agusrush21** [comment]
Ya, ya muchas gracias y perdon por la demora, ahora me quedo claro
