### ISSUE TITLE
Duda sobre implementación de programación orientada a objetos

### ISSUE THREAD

**Issue by gabo1243** [IIC2233/Syllabus#32]
### Duda

Hola, vi que en las consideraciones generales se exige programación orientada a objetos. Aquí mi duda: ¿es realmente necesario utilizarla? o ¿puedo llevar a cabo la misma función pero sin utilizar programación orientada a objetos?.  Si es necesaria, ¿Qué tanto o en qué partes tiene que ocuparse si o si?

Gracias de antemano

**Comment by drcid98** [comment]
Hola! no es necesario usar programación orientada al objeto. Tal como dices, puedes hacerlo solo usando funciones. En todo caso, si te sientes capaz de hacerlo usando clases, te lo recomiendo, ya que en las siguientes tareas si será obligatorio y te puede servir para acostumbrarte/practicar. Saludos!
