### ISSUE TITLE
Duda sobre ejercicio 6.1

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#32]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda de enunciado ejercicio 6.1

Hola! tengo una duda puntual con el enunciado, tengo que dicen "agrega 100 veces UN número aleatorio entre 0 y 100", pero ya que se trabaja con un set no me hace mucho sentido, no debería ser agregar 100 numeros aleatorios entre 0 y 100?

Edit: justo al terminar de escribir tuve otra duda, en caso de que sea lo que dije,  eso no seria solo un set con un solo numero faltante entre 0 y 100?

**Comment by pabloist** [comment]
Hola! :)

No entiendo por qué no te hace sentido agregar un número 100 veces a un set, pero trataré de responder tu pregunta. El enunciado lo que explicita es realizar un loop que se realice 100 veces en el cual se añade un número random entre 0 y 100 al set, particularmente para este caso es de utilidad la función add perteneciente a la clase Set(). El resultado de esta operación es un set con 100 elementos, los cuales corresponden a 100 números random en el rango indicado.

Ojalá haya respondido tu pregunta, cualquier cosa puedes comentar en esta misma issue, saludos!

**Comment by Pabloski100** [comment]
Mi principal conflicto es que al ser aleatorios pueden repetirse números, y como un set no admite repetición el set no seria de largo 100. Incluso si hago que los números no se repitan, como el set y el intervalo calzan mas o menos, seria como agregar casi todos los números del intervalo

**Comment by pabloist** [comment]
Perdón corrijo, generarás un set de máximo 100 elementos (en el caso de que ninguno de ellos se repita), pero dado que no es una solicitud por parte del ejercicio agregar 100 elementos diferentes, no hay problema con que tu set final tenga menos elementos.
