### ISSUE TITLE
recursos y su ubicacion

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#32]
en la base de datos de recursos nos dan la latitud y longitud de la base es decir en un comienzo todos se encuentran en reposo, pero mi duda es:
comienzan a moverse al aplicar estrategias de extincion?
y entonces si antes de aplicar esta, el usuario escoge (recursos mas efectivos) entonces, 
solo se debe mostrar una lista segun los puntos de poder?

**Comment by rpalmaotero** [comment]
@Dunkan1 no se encuentra especificado en el enunciado, queda a tu criterio.

**Comment by Dunkan1** [comment]
gracias
