### ISSUE TITLE
Error en archivo ‘functions.py"

### ISSUE THREAD

**Issue by camiloEscorza** [IIC2233/Syllabus#32]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

`  tablero_resuelto = solucionar_tablero(tablero_2x2)
    print(tablero_resuelto)

    tablero_2x2_sol = [
        ['T', 2],
        ['-', '-']
    ]

    resultado = verificar_alcance_bomba(tablero_2x2, (0, 1))
    print(resultado)  # Debería ser 2

    resultado = verificar_tortugas(tablero_2x2_sol)
    print(resultado)  # Debería ser 0`
en  
`resultado = verificar_alcance_bomba(tablero_2x2, (0, 1))
 print(resultado)  # Debería ser 2` 
no debería ser tablero_2x2, sino q debería ser tablero_2x2_sol, pero estaba escrito sin el sol. Lo cambio yo en mi repositorio o luego corrigen o no es relevante para la corrección?

**Comment by Hernan4444** [comment]
Hola @camiloEscorza 

Es irrelevante eso para la corrección, solo era para que tengan un mini ejemplo de cómo llamar las funciones 😄 

Saludos c:
