### ISSUE TITLE
Duda funcion cambiar_planos de la clase RedMetro

### ISSUE THREAD

**Issue by IsidoraCarmona** [IIC2233/Syllabus#32]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, en la función cambiar_planos se pide verificar primero si el archivo existe o no, ¿En que ubicación debería existir el archivo? ¿La estructura de los archivos es igual a los de la carpeta data o no necesariamente?

**Comment by pedrozavalat** [comment]
Hola @IsidoraCarmona 😄 !

Respondiendo tu primera pregunta, tal como se menciona en la seccion 4.2 del enunciado, todos los archivos deben estar almacenados en la carpeta **data**. 

Por otra parte, los archivos que serán testeados por parte del equipo docente van a seguir la estructura mencionada en la misma seccion 4.2, teniendo el siguiente formato: 
```markdown
4
A
B
C
D
0,1,1,0,0,1,0,1,0,0,0,1,0,0,0,0
```

Recuerda que los archivos dentro de la carpeta **data** seran solamente de formato **.txt**, por lo que tienes que tener ojo cuando se te entreguen archivos con formatos distintos a este. 

Espero que haya aclarado tu duda, éxito en tu tarea! 😄 

Cualquier duda, responde esta issue 😃

**Comment by Couyoumdjian13** [comment]
Hola, tengo una duda. Como poder comprobar que estoy cargando bien el archivo, (data), si es que los test publicos no están en la misma carpeta? Me tira "No such file or directory": "nombre del archivo

**Comment by pedrozavalat** [comment]
Hola @Couyoumdjian13 😄 !

Probablemente el error se deba a como estas ejecutando el archivo en la terminal. Te recomendaría revisar la issue [#24](https://github.com/IIC2233/Syllabus/issues/24#issuecomment-2000599698) para ver como se ejecuta el archivo de los _tests_.

Recuerda que tanto los archivos `main.py` y `todos_tests.py` son ejecutados desde la carpeta `T1/`. 

Cualquier duda que tengas, o si aún persiste el error, por favor responde a esta issue 😄

Saludos!

**Comment by pedrozavalat** [comment]
@Couyoumdjian13 
Revisando tu código me di cuenta que tienes un pequeño error de sintaxis. `with open("data/nombre_archivo", "r") as file:`. En este caso no te va a cargar el archivo, ya que no estas considerando la variable `nombre_archivo`. 😅
