### ISSUE TITLE
"Abrir" en ventana interfaz main.py

### ISSUE THREAD

**Issue by malopez16** [IIC2233/Syllabus#320]
Hola!
Me pasa lo mismos que lo de la consulta #293 , pero estoy en ubuntu. No me sale el abrir :( 
Donde tengo que fijarme? Estoy usando pycharm.

Gracias!! 

![asd](https://cloud.githubusercontent.com/assets/26126519/25455823/757470e0-2aa7-11e7-9d17-9ae63bef0587.png)

**Comment by iqacevedo** [comment]
Hola!

No se si ya lo encontraste pero aparece arriba cerca de donde dice RQL, tiene que poner el mouse sobre esa zona para que se vea:

![captura de pantalla de 2017-04-27 20-08-29](https://cloud.githubusercontent.com/assets/13748732/25511739/1ba921b6-2b9f-11e7-8977-2bcd18223244.png)

Saludos !

**Comment by malopez16** [comment]
Buenísima, como la ventana se abre pequeña, no había acercado el mouse justo al borde de la pantalla.. Ya estaba trabajando en windows (pero ahora puedo volver a ubuntu jajaja)
Muchas gracias!
