### ISSUE TITLE
QMutex, QTimer y QThreads

### ISSUE THREAD

**Issue by thneckelmann** [IIC2233/syllabus#320]
Hola!
Tengo un problema al correr mi programa. Utilizo una instancia de QTimer para activar una función que crea enemigos. Sin embargo, al llegar a una cantidad de aprox. 4 enemigos creados, comienza a fallar si visualización en el frontend. Estoy utilizando QMutex.lock() y QMutex.unlock() para evitar que múltiples QThreads utilicen las funciones que mueven a los personajes en el frontend, pero esto sigue ocurriendo. ¿Alguna idea de que podría estar fallando?

**Comment by jmwielandt** [comment]
Hola!

Si quitas los locks, ¿siguen los problemas?

**Comment by thneckelmann** [comment]
Si quito los locks pasa exactamente lo mismo.
Uso señales desde la clase enemigo tanto para mover el label, como para cambiar la imagen para darle movimiento, no sabría como más utilizarlas. :(

**Comment by jmwielandt** [comment]
@thneckelmann puedes subir tu código a tu repo para ayudarte de mejor manera?
