### ISSUE TITLE
Argumentos type.__new__()

### ISSUE THREAD

**Issue by Pipelao** [IIC2233/Syllabus#320]
![duda](https://user-images.githubusercontent.com/26421921/30776972-e082ded0-a086-11e7-888c-0377ae607922.png)

Hola, espero que estén bien.

Tengo una duda con respecto a la cantidad de argumentos de esta función. Según lo que encontré en internet, la cantidad de argumentos pedidos son 3, que sería el nombre de la clase, las clases bases y el diccionario, pero en la imagen adjunta aparecen 4, y cuando le saco uno dice error: fueron entregados dos argumentos y 3 son requeridos cuando hay 3. ¿por qué es esto?

Tampoco entiendo que son las clases bases y el diccionario.

De ante mano, gracias.

**Comment by entamburini** [comment]
Hola! Ese error que te sale es el mismo que cuando estás declarando un método y se te olvida el `self`.
En el caso que muestras, es lo mismo, efectivamente se piden los tres argumentos que dices, más el argumento equivalente de `self`, que en el caso de las metaclases (y lo visto en clases) lo llamamos `meta`.
Las clases base son las que la clase hereda, es una tupla con las clases que heredarán las creadas a partir de esa metaclase.
El diccionario en el `__new__` tiene todos los atributos y métodos que tendrán las clases creadas a partir de la metaclase.

**Comment by Pipelao** [comment]
Ahhh, a eso se refiere, muchas gracias por la respuesta, me quedó claro.
