### ISSUE TITLE
Inclusión de .gitignore en commit

### ISSUE THREAD

**Issue by VichoAburto** [IIC2233/syllabus#320]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, una consulta, ¿Debo incluir o no el .gitignore en mi commit final de la T1?, en otras palabras, ¿Debo ignorar el archivo .gitignore con el mismo archivo .gitignore? O debo subirlo para que ustedes verifiquen que lo utilicé?

**Comment by sperezmasri** [comment]
Hola @VichoAburto! El archivo ```.gitignore``` **debe estar subido** en tu repositorio (en este caso en la carpeta T1). Por lo tanto **no debes** ignorarlo,  saludos! :smile:

**Comment by VichoAburto** [comment]
Yaa buenísima! Graciass
