### ISSUE TITLE
Problemas con cargar archivo y funcion hallar_region T3

### ISSUE THREAD

**Issue by cataruze** [IIC2233/Syllabus#320]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Holaaa. 
Al cargar los datos de los archivos distritos en cualquiera de los tamaños, se guarda unas nametuple con por ejemplo provincia ="  Iquique", con el espacio incluido debido a la forma en la que están guardados los nombres en los archivos (con espacio y después nombre). Teniendo esto en cuenta los test cases de cargar datos toman como correcto cuando uno los carga con estos espacios. Pero ahora al realizar hallar_region, desde el test case 5 en adelante, se realizan con la carga de datos, (los anteriores se realizaban con una lista de nametuples creadas), en donde el resultado esperado no contempla este espacio que se realiza al cargar los datos, lo cual no posee concordancia. 
Adjunto fotos para que se entienda mejor:
archivo distritos:
<img width="323" alt="archivo" src="https://github.com/IIC2233/Syllabus/assets/162622512/9c6a08e5-5042-485d-b311-3d3f5997c449">
respuesta obtenida vs esperada
<img width="143" alt="respuestaa" src="https://github.com/IIC2233/Syllabus/assets/162622512/3f369fd6-e6a5-4edf-9580-83febf9fa95f">

Con este problema quería consultar, si existe la posibilidad de que los tests cases tengan algún error, o si es un problema de mi codigo.

Muchas gracias de antemano.

**Comment by TomasGMDC** [comment]
@cataruze pregunté, y es un problema de tu código. Considera la forma de evitar ese espacio.

**Comment by vichorosen** [comment]
Hola! También tengo el mismo error con los últimos 3 test.
Entonces en el mismo código de dicha pregunta debo considerar una forma de quitar este espacio en el string retornado, para solucionar el problema? Esto asumiendo que en los archivos viene siempre este espacio.

**Comment by TomasGMDC** [comment]
@vichorosen efectivamente, deben considerar cómo quitar este espacio.

**Comment by pedro1ani** [comment]
Dentro de una lista por compresion o diccionario por compresion, se puede aplicar el metodo .strip()

**Comment by TomasGMDC** [comment]
@pedro1ani sí, se puede aplicar .strip() dentro de una estructura por comprensión.
