### ISSUE TITLE
Path Absoluto

### ISSUE THREAD

**Issue by Dafnemami** [IIC2233/syllabus#320]
Al abrir una imagen en ubicarle en un QLabel, decidí por dejarla en el escritorio y darle un path absoluto al os.path,join() para cuando quiera abrirla, pero no he conseguido abrirla. Puedo abrirla si la muevo a un lugar conveniente, pero me gustaría entender mi error y aprender.

Debe ser un error sutil que no me he percatado , desde ya agradezco sus comentarios 🚀 👩‍🚀 !

![error 1](https://user-images.githubusercontent.com/53848830/65379278-2416e580-dc9c-11e9-9a06-bdfee2752858.PNG)
Esta imagen la dejo como referencia de donde obtuve el path de la imagen en el escritorio .

![error 2](https://user-images.githubusercontent.com/53848830/65379279-25481280-dc9c-11e9-951b-12d78ae4bca8.PNG)
Este es mi código.

**Comment by jmwielandt** [comment]
Hola!

Podrías decirme qué error te tira?

Saludos~

**Comment by Dafnemami** [comment]
Ninguno en el editor de texto al menos. Tengo esto puesto:

    def hook(type, value, traceback):
        print(type)
        print(traceback)
    sys.__excepthook__ = hook

Pero no parece que haya "nada malo" con el código en si, solo que no supe entregarle el path correcto. Por lo que tenía entendido, no importa desde que directorio referencie el path si es absoluto, y debería abrir sin problemas. De todos modos, te comento que en la fotografía que pusé arriba:
![error 1](https://user-images.githubusercontent.com/53848830/65380355-4fa3cb00-dcb0-11e9-952b-7b46abbb225d.PNG)

"C:\Users\dafne\.PyCharmCE2018.3\config\scatches"  es el directorio desde donde llamo al path absoluto de la imagen que intento cargar.

**Comment by jmwielandt** [comment]
Hola!

Por lo que averigüé, parece ser que es One Drive el problema. El archivo no se guarda en tu disco, se guarda en algún servidor remoto y tu explorador de archivos te permite ver todo lo que tienes almacenado remotamente como si estuviera en tu pc, por eso python no encuentra las imágenes. Tienes dos opciones:

1. Seleccionar la carpeta donde se encuentren los archivos con los que estés trabajando > Click derecho > "Mantener siempre en este dispositivo".
2. Poner las imágenes en otro directorio fuera de One Drive.

Saludos~
