### ISSUE TITLE
Tamaño de los sprites

### ISSUE THREAD

**Issue by martina-abello** [IIC2233/Syllabus#320]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

¿De qué tamaño tienen que ser los sprites para los lobos, las paredes, los items, etc? Imagino que todos del mismo, pero los cañones y las explosiones por ejemplo son rectangulares y las paredes y los sprites del conejo cuadros. ¿Cuál debería ser el tamaño estándar para que los parámetros funcionen bien? (En particular las velocidades.)

**Comment by AntonioVenegas** [comment]
Hola!, la idea es que los tamaños de las ventanas y los sprites los manejes tú, puedes usar los ejemplos del enunciado como base para ir calibrando el tamaño de las entidades y las casillas. Y con respecto a la velocidad, te recomiendo primero definir el tamaño de las entidades y después calibrar que tan rápido se mueven, pero igual vas a tener que hacer prueba y error hasta que funcionen bien.

Saludos :)
