### ISSUE TITLE
Avanze

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#320]
Hola! ¿Tengo una duda a que se refiere con avancé? Debemos haber completado una cierta parte de la tarea, o es sólo para ver donde estamos actualmente.

**Comment by aljara97** [comment]
Hola @CataSudo!!

Esta duda ya fue respondida en la issue #295, recuerda que si tienes una duda, revisar en el compilado de issues (#239 ) si algún compañero preguntó por lo mismo.

Éxito :D
