### ISSUE TITLE
Diagrama de clases: herencia de properties

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#321]
Hola, quisiera saber si es que al hacer mi diagrama de clases, si yo tengo una clase madre con una property "a" y en una clase hija yo quiero implementar esa misma property "a" pero con leves modificaciones, tengo que escribirla tanto en el recuadro de la clase madre como la hija?

**Comment by mpsubiabre** [comment]
Hola @lewebe !

Depende del nivel de cambios, si esas modificaciones son tales que debes definir esta property nuevamente, es decir, no la hereda porque tienes que reescribirla (redefinirla), en este caso debe ir en tu clase hija también. En cambio si esas modificaciones son modificables sin tener que reescribir esta proprety, no debe ir en la clase hija :)

Espero que te haya quedado claro, de lo contrario sigue comentando esta issue 😉
