### ISSUE TITLE
Aplicacion de generadores en extraer_columna 

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#321]
Trate de hacer que mi función me retornara un generador con los datos de la columna pedida, pero después al tratar de operar sobre este fuera del with open tira un error por intentar operar en un archivo cerrado, hay forma de evitar este error?

**Comment by sebacruzd** [comment]
Yo creo que en tu pregunta está la respuesta. 
Estás **intentando operar en un archivo cerrado**, por lo que estás usando referencias al archivo al tratar de operar como dices, en vez de haber **escrito** sus datos en el generador, por lo que me imagino. 

Revisa bien lo que haces en tu generador, ya que ahí debería estar el problema.

**Comment by KnowYourselves** [comment]
Lo que intente hacer fue extraer la información con generador por comprensión, lo cual me tira error, pero al hacerlo con lista por comprensión funciona bien, pero se demora más y por lo que tengo entendido ocupa espacio de memoria, no entiendo como hacer un generador con la información y que pueda salir del with sin pasar por ser una lista/tupla

**Comment by Hernan4444** [comment]
@KnowYourselves te recomiendo intentar estudiar otras formas de abrir un archivo, no siempre es necesario with para lograr eso.

Saludos!

**Comment by acrojas2** [comment]
Hola:
En el contexto de esta pregunta, qué pasa si yo leo un archivo de esta forma:
file = open(name, "r", ...)
    ->guardo la info de la columna en una variable
    ->return columna
y no hago file.close()
¿Qué pasa con eso (quiero que me digan consecuencias)? ¿Puede el archivo quedar abierto para efectos de la función extraer columna?
Si hiciera file.close() antes de retornar ocurriria el error ValueError: I/O operation on closed file y si lo hiciera después, no se cerraría puesto que ya retorno la función... y con with open el archivo se cierra automáticamente, entonces... ¿Hay otra forma de abrir un archivo ->obtener la info -> retornar  y que el archivo no quede abierto?
Espero se entienda mi pregunta...
Saludos :B

**Comment by aeperalta** [comment]
Tengo exactamente la misma pregunta que @acrojas2. Hay forma de obtener la info para almacenarla en un generador, sin que el archivo quede abierto?

Saludos

**Comment by Hernan4444** [comment]
@acrojas2 @aeperalta. 
Primero ¿Que pasa si no cierras el archivo?. Hay algunos python que dejarán en memoria la referencia del archivo y solo si tu eliminas esa referencia python cerrará el archivo o si es que cierras el archivo. 
Por ejemplo:
```
file = open(path)
del file
```
Al momento de eliminarlo ya no hay referencias para acceder al objeto retornado por `open(path)` y por ello python lo cierra. ese es el caso ideal :ok_hand:  (aquí se encuentra al menos python 3.5.2) Pero es una mala practica depender de que tu interprete cierre el archivo y no hacer `.close`

### ¿Cual es el peligro si no cierras el archivo?
Cada usuario tiene un máximo de archivos para tener abierto (por ejemplo en mi python 3.5.2 es de 8189 archivos y en python 3.4.3 es de 2045), si llegas a esa cantidad no puedes hacer ningún `open` más hasta cerrar alguno o eliminar la referencia a algún archivo. Quiero enfatizar que no es una buena practica hacer lo segundo. **siempre** hay que ingeniárselas para lograr cerrar el archivo.

Una opción para enfrentar esto es no cerrar los archivos después de leer la información, pero almacenar todos los file.open(path) en alguna parte (lista por ejemplo) y al momento de terminar todas las consultas pedidas ahí cerrar todos los elementos almacenados. Si después quiero acceder a una variable que tenía referencia a uno de los archivos, entonces vuelvo a crear el generador del archivo y almacenándolo como lo hice antes. Como todo esto es `on the fly`, entre tener el generador abierto o no y tener que crearlo de nuevo, no se pierde eficiencia.

Espero haber resuelto sus dudas.
Saludos!
