### ISSUE TITLE
Notación de MEJORA_ATAQUE

### ISSUE THREAD

**Issue by furzuadr** [IIC2233/syllabus#321]
Hola, estaba incluyendo las mejoras y me surgió una duda con el parámetro MEJORA_ATAQUE.
En el enunciado este dice que es una porcentaje fijo, esto debo incluirlo como un valor por ejemplo:
Quiero que aumente un 20%, debería usar:

MEJORA_ATAQUE = 20, o
MEJORA_ATAQUE = 0.2, o
MEJORA_ATAQUE = 1.2.

Me quedaría con la primera, pero prefiero estar seguro, gracias!

**Comment by jmwielandt** [comment]
Hola!
Eso queda a tu criterio pero ponlo en tu readme.

Ánimo con la tarea!
