### ISSUE TITLE
Duda sobre el movimiento del conejo

### ISSUE THREAD

**Issue by juanivegam** [IIC2233/Syllabus#321]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Cuando el usuario aprete una tecla para mover al conejo, ¿El conejo cambiambierá su dirección inmediatamente, o bien, esperá a que choque con una piedra o cañon, y desde ahí seguir la nueva dirección que indico el usuario?

Por ejemplo si tengo el siguiente tablero:

    0. 1.  2. 3. 4. 5
0 [[P, P, P, P, P, P],
1 [ -, C, -, -,  -, P],
2 [P, - , - , - , -, P]

Si el conejo se está moviendo horizontalmente hacia la derecha, y en ese instante el usuario apreta S (abajo), el conejo bajará una vez que que haya llegado a la posicion (1,4) o bajará en el mismo instante, es decir bajaría a (2,1)

**Comment by ignacio-sp** [comment]
Hola @juanivegam, el conejo se mueve hasta colisionar con una pared, por lo que bajaría al llegar a la posición (1,4), saludos!

**Comment by ignaciopena7** [comment]
Hola. Luego de leer la lógica que deberia seguir el conejo quede confundido, ya que modifica bastante la estructura que tenia planteada. Entonces, según el ejemplo que dio mi compañero, ¿se podria decir que el conejo va a ir acumuluando instrucciones y con estas deberia ser capaz de completar el laberinto?

**Comment by Segismundios** [comment]
Me sumo a la duda de @ignaciopena7, según lo que señala @ignacio-sp, entiendo que entonces las instrucciones de movimiento podrían acumularse en una especie de queue?

**Comment by ignacio-sp** [comment]
Hola @ignaciopena7 y @Segismundios, como no se especifica en el enunciado, pueden realizar sus propios supuestos del manejo de inputs e indicarlo en el README, ya sea si deciden esperar para el siguiente movimiento o almacenarlo, espero les sirva!
