### ISSUE TITLE
Multiples teclas de movimiento apretadas

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2233/Syllabus#321]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Si mientras Luigi se mueve apretó otra tecla de movimiento. Tengo que anularla, permitiendo que Luigi se mueva solo si se encuentra quieto o tengo que esperar a que se ejecute la acción anterior y a penas termine ejecutar esta acción, generandose una cola de acciones? En cualquier de los dos casos ¿Aplica lo mismo para los cheatcodes? O por lo contrario los cheatcodes deben ejecutarse inmediatamente independientemente del estado de movimiento de Luigi

**Comment by MaxAl100** [comment]
Hola! En ambos casos tú eliges cómo quieres que funcionen, pero se recomienda que funcione como una cola de acciones. Recuerda escribir cual de los dos casos escojas en tu README!
