### ISSUE TITLE
Barcos en paralelo en el canal

### ISSUE THREAD

**Issue by B-Birb** [IIC2233/syllabus#321]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Tengo una consulta con respecto al flujo de más de un barco en un mismo canal. Ya que no tenemos el ancho del canal, ¿Podemos asumir que los barcos pueden viajar de manera paralela? Es decir, ¿Puede el barco A pasar por el lado del barco B? De similar manera, ¿Pueden dos barcos estar uno al lado del otro? Esto es asumiendo que ninguno ha encallado.

**Comment by santiagovegaf** [comment]
Hola @B-Birb!

Es correcto asumir que los barcos pueden viajar de manera paralela! 

Además aprovechó de recordar que nunca está de más anotar todos los supuestos realizados en tu ReadMe!

Exito en el desarrollo de tu tarea!
