### ISSUE TITLE
Remover Ubuntu 16.04 y volver a Instalar Windows 10

### ISSUE THREAD

**Issue by simontoya** [IIC2233/Syllabus#321]
Hola! 
Alguien que me pueda ayudar, hace un tiempo elimine windows 10 de mi computador y lo deje solo con ubuntu 16.04. Ahora me cambie a un Mac pero necesito dejar el otro computador con windows 10, ya tengo la licencia correspondiente que da la universidad para windows 10. Intente hacer el usb booteable con windows 10 e incluso me funciona el instalador pero luego de supuestamente terminar la instalación en el disco duro, saco el pendrive o cambio la preferencia del dispositivo en el bios y el computador no arranca windows 10. Alguien que sepa como hacerlo?

**Comment by fgbruna** [comment]
[Probablemente ya lo respondieron en AskUbuntu alguna vez](https://askubuntu.com/q/133533/648324)
