### ISSUE TITLE
en test cargar datos no encuentra "utilidades"

### ISSUE THREAD

**Issue by domingaelton** [IIC2233/Syllabus#321]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Para mi test de cargar datos me sale el siguiente error.

from utilidades import Animales, Locales, Candidatos, Distritos, Ponderador, Votos
ModuleNotFoundError: No module named 'utilidades'

Por que no encuentra utilidades?

Gracias!

**Comment by ClemoAcevedo** [comment]
Hola @domingaelton , te aseguraste que el módulo `utilidades.py` y el módulo donde estás intentando importarlo se encuentran en la misma carpeta? Si es así, has un push a tu repositorio para que pueda revisar que está ocurriendo.

**Comment by josefa00** [comment]
Hola! yo tengo ele mismo problema cuando ejecuto el test de cargar datos en el terminal de mi T3

**Comment by domingaelton** [comment]
@ClemoAcevedo si la tengo en la misma carpeta, ahi hice git push en mi repositorio gracias :)

**Comment by Chiseth** [comment]
A mi igual, al testear 'test_base_cargar_datos' me arroja

Traceback (most recent call last):
  File "c:\Programación\Chiseth-iic2233-2024-1\Tareas\T3\tests_publicos\test_base_cargar_datos.py", line 9, in <module>
    from utilidades import Animales, Locales, Candidatos, Distritos, Ponderador, Votos
ModuleNotFoundError: No module named 'utilidades'

**Comment by ClemoAcevedo** [comment]
@domingaelton Probé con tu repo correr el test `test_base_cargar_datos.py` (supongo que hablabas de ese al decir el test de cargar datos). Y los problemas que me tira son otros. Dos detalles: Es importante asegurarse de que la lista esté inicializada correctamente, independientemente del tipo de tamaño. Y pon atención a que el método `append` se esté utilizando en la lista adecuada. Si esto no lo arregla, cuentame como estás corriendo el test

**Comment by ClemoAcevedo** [comment]
@Chiseth @josefa00 como estan ejecutando el test?

**Comment by cgonzalezw** [comment]
Hola, me pasa lo mismo. Estoy ejecutado el tests desde visual, tengo que hacerlo desde el terminal si o si?

**Comment by Joomkin** [comment]
Hola algun update de esto jaja
