### ISSUE TITLE
Multiherencia parcial

### ISSUE THREAD

**Issue by clementethompson** [IIC2233/syllabus#321]
Hola, si tengo un diamante de este estilo:
![imagen](https://user-images.githubusercontent.com/53916605/92137929-c5c71200-eddb-11ea-82cb-2e3985ec848b.png)

Mi duda es como heredar atributos específicos de cada clase madre (en este caso quiero heredar atr3 de la clase izq y atr 4 de la derecha). Todas las clases reciben los mismos argumentos y algunas tienen atributos propios.

Ojalá se entienda mi pregunta. Saludos.

**Comment by tocococa** [comment]
Hola @clementethompson ! En Python no hay una manera "formal" de hacer lo que propones 😢, pero hay alternativas. 

Una sería partir la `ClaseA` en dos, y así tienes una clase con ciertos argumentos y otra clase con los demás y ahí puedes ver como heredar para que tu `ClaseB` sólo reciba los que tu quieres, y si aún necesitas una clase con todos los atributos de `ClaseA` (que partiste en 2), creas una nueva clase que hereda de ambas.

También podrías usar composición en vez de herencia, o hacer _override_ del atributo y que, en la clase hija, este levante un error si se trata de acceder (excepciones lo van a ver la próxima semana👀).

Se que probablemente no es la respuesta que andabas buscando, pero son limitaciones del lenguaje, y si de verdad llegas a una situación así, también sería buena idea revisar como estás haciendo tu modelación.
