### ISSUE TITLE
QObject: Cannot create children for a parent that is in a different thread.   (Parent is QApplication(0x1eeb146c0c0), parent's thread is QThread(0x1eeb14fd210), current thread is Juego(0x1eeb56363a0)

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2233/syllabus#322]
Estoy teniendo este error, estuve buscando en internet que significa y me sale que es un problema con que estoy tratando de crear threads desde un thread que no esta conectado al thread padre, lo raro es que hice todo lo posible por conectarlos (estuve pasando padre entre clases) y aun me sigue saliendo el error, aunque le de al thread padre.

Aqui dejo un par de links en donde busque esta informacion

- https://stackoverflow.com/questions/3268073/qobject-cannot-create-children-for-a-parent-that-is-in-a-different-thread

- https://www.qtcentre.org/threads/45638-QTcpSocket-Cannot-create-children-for-a-parent-that-is-in-a-different-thread

**Comment by jmwielandt** [comment]
Hola!
Para poder ayudarte mejor podrías poner una versión de ejemplo del código que te tira ese error. Si ese código es solución de _algo_, será mejor que lo subas a tu repositorio en alguna carpeta especial y avises por acá.

Quedamos atentos.

**Comment by lfuenzalida2** [comment]
No tengo una forma de poner el codigo como ejemplo porque igual es extenso, lo que podria hacer es explicar un poco por donde se mueve el error.

Subi a mi repositorio todo y coloque un archivo llamado "Texto_explicativo_error_issue322.txt" en donde explico que pasa, donde pasa y un poco del contexto del codigo.

**Comment by lfuenzalida2** [comment]
Muchas gracias por la ayuda, perdon por molestarte ;)

**Comment by ByronHidalgo1** [comment]
Hola, me aparece el mismo error. ¿Cuál era más o menos la solución?
