### ISSUE TITLE
Valor inicial Nivel de aprobación magizoologo

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#322]
Hola, lei el enunciado y entiendo que en un magizoologo, el nivel de aprobacion "Varía entre
0 y 100, y si es menor a 60 el Magizoólogo pierde su licencia". Pero no dice nada sobre el nivel en el que parte.

**Comment by matiasmasjuan** [comment]
Hola @Juampisaez !

Esta pregunta se respondió en la [Issue 319](https://github.com/IIC2233/syllabus/issues/319).

En caso de tener alguna duda, no dudes en preguntar!
Éxito con tu tarea!
