### ISSUE TITLE
Saltos de linea al final de los archivos de texto de laberintos

### ISSUE THREAD

**Issue by anticarasosman** [IIC2233/Syllabus#322]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [ X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Los 3 tableros que se encuentran en la carpeta de assets tienen todos un distinto numero de saltos de linea al final del texto, el tablero 1 tiene 4, el 2 tiene 1 y el 3 no tiene ninguna ¿se pueden cambiar/borrar estos saltos de linea? O se debe dejar como estan?
![imagen_2023-10-27_162004244](https://github.com/IIC2233/Syllabus/assets/94928628/f40e57b4-ec6d-4a05-aa64-d6bd40e6dedc)
![imagen_2023-10-27_162017816](https://github.com/IIC2233/Syllabus/assets/94928628/f96c40b9-eaad-4aca-9298-a0ea963ac794)
![imagen_2023-10-27_162035540](https://github.com/IIC2233/Syllabus/assets/94928628/32d48dbc-52a1-4a2e-a0d8-3c4fc6e30b5b)

**Comment by AntonioVenegas** [comment]
Hola @anticarasosman, aunque puedes borrarlos, tu programa debería saber manejar ese tipo de casos al leer un archivo de tablero. Hay muchas formas de resolverlo, pero talvez el método rstrip() te sea útil. Saludos :)
