### ISSUE TITLE
for en un generador por compresión y Counter de collections.

### ISSUE THREAD

**Issue by VicenteIgnacioSotoGonzalez** [IIC2233/Syllabus#322]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! junto con saludar quería preguntar dos cosas respecto de las funciones de consultas.

1. Se puede usar for por compresión en un contexto similar a este: return (instancia[0] for instancia in filtrado)

2. Tengo entendido que no se pueden crear estructuras de datos sin aplicar compresión, por ese motivo me genera la duda de si puedo ocupar la función Counter de collections para crear un iterable para usar filter, del estilo filter(funcion, Counter(map())) (hice push de mi tarea, ya que la duda es confusa sin el contexto apropiado). Gracias de antemano!

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Más que nada lo pregunto porque por lo que entiendo, Counter devuelve un dict, el cual si no me equivoco no se estaría creando por compresión.

**Comment by TomasGMDC** [comment]
@VicenteIgnacioSotoGonzalez sobre el primer punto, dado que estás creando una tupla por comprensión, sí se pueden usar líneas de código de ese tipo, incluso con un return.
Sobre el segundo punto, te comparto una issue pasada en la que se habla del uso de Counter:

![image](https://github.com/IIC2233/Syllabus/assets/71156496/5dd58a6e-ed8c-42cd-9c84-adce058a95d2)

Entonces, si utilizas un map dentro de Counter, es posible utilizarlo, siempre y cuando dentro del map no se utilice alguno de los comandos prohibidos.

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Perfecto, muchas gracias por la respuesta, todo claro.
