### ISSUE TITLE
Clases abstractas

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#322]
Hola! No entendí el objetivo de las clases abstractas. Si hay que volver a instanciar todos los métodos abstractos en la subclase, por qué haríamos el código 2 veces? No entiendo la utilidad que pueden tener estas clases, o es para usar los métodos no abstractos en varias subclases? Pero esto no es como hacer una herencia normal?

**Comment by Juampisaez** [comment]
Hola @kalarconvl 
Tal como dice en los contenidos, "Por abstracta, nos referimos a que son clases cuya intención no es ser instanciada (o crear un objeto de esa clase directamente), si no que **solo usarse como parte de modelamiento de otras clases.**". Como ejemplo, imaginate que quieres desarrollar un codigo que represente al cuerpo docente del curso, dentro de este (entre otras cosas) habrán ayudantes Docentes, Tareas e Hibridos, pero no todos tendrán las mismas funcionalidades, es decir, todos los ayudantes podrían tener métodos abstractos como por ejemplo deberes, correcciones, entre otras cosas. A pesar de que sean los mismos metodos, sus funcionalidades serán distintas. La idea de tener clases abstractas, es para tener un orden al programar, ademas de funcionar como clases padres con en la Herencia (te pueden ahorrar codigo de la misma forma).

Espero haber aclarado la duda que tenías, perdón lo tarde de esta respuesta :)
