### ISSUE TITLE
Error Importación PyQt5

### ISSUE THREAD

**Issue by agustindesolminihac** [IIC2233/syllabus#322]
Hola, tengo un problema al importar PyQt5 en pycharm, me dice que no existe el módulo PyQt5, pero en consola me dice que ya lo tengo descargado.
Gracias de antemano.
![progra](https://user-images.githubusercontent.com/49526698/65389390-2032a400-dd2c-11e9-9055-8d9cd7d77434.png)
![progra1](https://user-images.githubusercontent.com/49526698/65389391-2cb6fc80-dd2c-11e9-8ce6-f09d7e87777e.png)

**Comment by Jprampad** [comment]
Me pasa lo mismo, busque en internet y dice que hay que usar una VE, es así o no?

Adjunto link: https://www.metachris.com/2016/03/how-to-install-qt56-pyqt5-virtualenv-python3/

Gracias de antemano

**Comment by JoacoCoyu** [comment]
Hola! 
Respecto a tu issue, no te preocupes que está bien instalado PyQt5 en tu computador. Sucede PyCharm genera un venv (Virtual Environment) para correr archivos el que no contempla algunos _bindings_ de bibliotecas de Python, en particular PyQt5. Entonces el error ocurre porque estás usando este venv en vez del intérprete del computador que instalaste (Python 3.7.X) para correr tus programas.

Los que debes hacer es:
1. Ir a los Settings de PyCharm (en la pestaña Archivo/File > Settings ...). 
2. Presionar la opción: Project: "nombre de tu proyecto".
3. Seleccionar la opción: Project Interpreter.
4. Al lado superior derecho va a aparecer un buscador en el que debes elegir el tipo de "Project Interpreter" para tus programas. En particular, ahí debes elegir el Python 3.7.X que tienes instalado y que tiene su path correspondiente.
5. Seleccionalo, luego presiona "Apply" y después "Ok". En esta misma pestaña te van a aparecer todos los módulos y paquetes que tiene ese Python que seleccionaste y es el que tienes instalado, incluyendo PyQt5.

* Problemas que pueden surgir con el paso 4., es que no te aparezca el path del Python que quieres seleccionar. Esto sucede porque en el momento en que lo instalaste, lo más probable es que no hayas presionado la opción "Add To Path". 
Ahí te recomiendo (no se la verdad si hay otra manera, pero hice yo): desinstalar el Python que tienes, instalarlo nuevamente, y cuando aparezca, presionar la opción "Add To Path". No te tomará mucho tiempo.

Espero que te ayude,

Saludos!

**Comment by pazanelli** [comment]
Hola, me pasa algo similar. Uso VS Code y al correr el código me tira el error <No name 'QWidget' in module 'PyQt5.QtWidgets'> y lo mismo para 'QApplication'. ¿Cómo lo puedo solucionar?

**Comment by tago470** [comment]
tuve el mismo problema y pasé mucho tiempo arreglándolo lo que pasa es que no da la opción de elegir el path del programa directamente, por eso tienes que ir a la opción de configuración a la derecha y poner ShowAll luego a la derecha el botón "+". Luego seleccionar la opción "Existing Enviroment" luego apretar a la derecha los "..." y escribir manulamente (porque hay carpetas ocultas en mi caso "AppData" no existía) el path que sale arriba en "Base Interpreter" de "New Enviroment" una vez Hecho esto poner "Ok" y estará listo. Ojalá les sirva para no perder tiempo como yo solucionandolo.

**Comment by Gianluc139** [comment]
A mi me paso que al tener python 3.5 desde antes, el PyQt5 se me instalo en ese. Y al desinstalarlo ahi recien pude instalarlo en el 3.7.X que tengo y se soluciono el problema.
