### ISSUE TITLE
Distribucion Gamma

### ISSUE THREAD

**Issue by andreslyon** [IIC2233/Syllabus#322]
#277 
En la parte de distribuciones de probabilidad del enunciado,, la gamma esta definida con (k-1)! en vez de con Γ(k), luego k solamente podría ser natural. Lo dejamos así o se puede implementar la funcion gamma que viene en la libreria math?

**Comment by Hernan4444** [comment]
@andreslyon puedes asumir que solo con números naturales esperamos que funcione la distribución gamma, cualquier otro tipo (float, negativo, etc) deberá generar error.

Saludos!
