### ISSUE TITLE
Asunción adecuada?

### ISSUE THREAD

**Issue by Icarus328** [IIC2233/syllabus#322]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, esto es una duda no solo sobre esta tarea si no sobre las tareas en general, y es que si a la hora de solicitar un input del usuario, le digo a ese usuario el formato del input, es razonable esperar que el input sea en ese formato?

Por ejemplo, si al solicitar un input pongo:
   Porfavor seleccione una opción:
   [0] opción 1
   [1] opción 2
   [2] opción 3

Es razonable esperar y asumir que el usuario va a ingresar 0, 1 o 2, o en su defecto un número cualquiera, pero no por ejemplo "La primera" o algo así?

**Comment by Emiliax16** [comment]
Hola @Icarus328. El usuario en todos los inputs puede ingresar cualquier cosa, pero sólo puede funcionar con las opciones que tú muestras. Si en tu ejemplo el usuario pone: "La primera", "la del medio", "opción 1", "la última", el programa no debería dejarlo ingresar a esa opción (ya que existirían muchísimas formas de referirse a una de tus opciones y sería innecesario incluirlas), por lo que puedes asumir que sólo con los números que tu pusiste, se puede continuar.
