### ISSUE TITLE
Librerías permitidas/no permitidas en la T03

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233/Syllabus#323]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:

> ¿Puedo usar la librería nombre_librería para hacer explicación_de_lo_que_quiero_hacer?

¡Recuerden especificar en su README qué librerías utilizan!

---

## Librerías Permitidas
- `csv`
- `itertools`
- `os`
- `random`
- `unittest`
- `collections`
- `copy`
- `types`
- `functools`
- `sys`
- `inspect`
- `datetime`
- `typing`
- `re`

## Librerías Prohibidas
- `pandas`
- `pyparser`
- `scipy`
- `operator`
-  `sympy`
- `threading`

## __Built-ins__ prohibidos
- `eval (💀)`
- `exec (💀)`

## ESPECIALMENTE PROHIBIDO
- `for`
- `while`

(Sin embargo, sí se pueden usar en los casos especificados en el enunciado.)

**Comment by Hernan4444** [comment]
@jjaguillon no tienen que leer el archivo consultas.json, eso lo hace la misma interfaz. 
Saludos ✌️

**Comment by norman123123** [comment]
¿Por qué no se puede usar regex?

**Comment by simontoya** [comment]
Hola!
Puedo ocupar funciones recursivas?

**Comment by Hernan4444** [comment]
@norman123123 fue un error nuestro, lo prohibimos para que no parseen las consultas, pero al final decidimos entregarlas en un formato de lista así que no era necesario parsear. Ya está permitida.
@simontoya Si puedes.

Saludos ✌️

**Comment by emeiese** [comment]
Se puede utiliza el built-in "locals()"? lo quiero para extraer el nombre de los argumentos de una función.

**Comment by emeiese** [comment]
Y se puede usar la librería types? Me interesa sacar el tipo de un generador con types.GeneratorType

**Comment by Hernan4444** [comment]
@emeiese si puedes usar `locals()`. Para `types` si puedes utilizar esa, aunque  tambien tienes `typing` que hace lo mismo.

Saludos ✌️

**Comment by santilaguna** [comment]
¿Se puede importar el módulo types, para importar la clase GeneratorType?

**Comment by norman123123** [comment]
Tambien tengo la duda de si se puede usar operator.attrgetter 
Saludos

**Comment by felipe8797** [comment]
Se puede usar la librería recordtype?

**Comment by jjaguillon** [comment]
¿Puedo usar la librería string para eliminar la puntuación de un string?

**Comment by Hernan4444** [comment]
@felipe8797 recuerda seguir formato de consulta
@jjaguillon si puedes.
@norman123123 y @jpsiegel si es para lo que dicen, si se permite, pero no olviden especificarlo en el Readme,

Saludos ✌️

**Comment by jmopaso** [comment]
¿Puedo usar la librería heapq para obtener los n elementos maximos de una lista?

**Comment by Hernan4444** [comment]
@jmopaso no puedes, eso lo tienes que implementar con las herramientas vista en clases.

Saludos :v:

**Comment by savelozo** [comment]
Puedo utilizar la librería ast para la conversión de int y floats?

**Comment by Hernan4444** [comment]
@savelozo no puedes utlizar esa librería
@auirarrazaval si puedes utilizar `statistics.mean()`

Saludos ✌️

**Comment by mblejeune** [comment]
Hola! estoy intentando añadir con self.addanswer() las columnas de los generadores para las primeras consultas, por si me piden directo ["load_database"] por ejemplo, y queria saber si puedo hacer for para ingresar a cada pelicula dentro de mi generador, ya que sé que se puede usar for para entrar al query que se ingresa, pero dentro de este abro como result el generador de load_database y para añadirlo a la interfaz hago for el in result: self.addanswer(el.atributo) y poniendo separadores de lineas y todo y me funciona, pero quera saber si es legal usar este ultimo for para ingresar a cada elemento de mi generador y añadirlo con self.addanswer, gracias! :)

**Comment by mplazadelosreyes** [comment]
@Hernan4444 Se puede usar globals() para ejecutar funciones?

**Comment by llloyola** [comment]
Hola! Estoy usando inspect.getargspec para obtener los nombre de las variables de mis funciones, pero cuando aplico 2 decoradores a una función e intento obtener los nombre de las variables de la función original, me devuelve las del decorador. Puedo importar el módulo decorator para usar decorator.decorator y así conservar los argumentos de la función original?

**Comment by Arcoirisky** [comment]
@llloyola puedes :D
