### ISSUE TITLE
Duda sobre malas prácticas en manejo de excepciones 

### ISSUE THREAD

**Issue by diegocostares** [IIC2233/Syllabus#323]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Hola, quería saber si es mala práctica hacer lo siguiente:
```python
except OSError:
       pass
```

_PD: Es algo que estoy haciendo en la T3 para evitar  varios errores innecesarios, pero lo puse como duda sobre `contenidos` porque está más ligado a los contenidos según yo_

**Comment by knight-who-says-ni** [comment]
Hola @diegocostares!!

Si bien no descontamos por hacer eso, si es mala practica. Lo correcto sería 
```
python
except OSError as error:
    pass
```

Esto es porque si bien estás capturando correctamente, de esa forma no puedes tener información concreta de porque pasó esa excepción, lo que puede hacer que el debugueo sea más difícil, o que nunca te enteres de que tu programa tiene algún problema. Con el `as error`, puedes imprimir este error y obtener información más clara de este.

Saludos, y exito programando!!
