### ISSUE TITLE
Opción volver al menú anterior

### ISSUE THREAD

**Issue by Icarus328** [IIC2233/syllabus#323]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, tengo la duda si la opción de volver al menú anterior también debe de estar presente en la cadena de decisiones que resultan de elegir "Avanzar hora", o si, al ser decisiones tomadas como resultado de una acción y no parte de un menú como tal, se puede asumir que las decisiones tomadas en "avanzar hora" son irreversibles.

**Comment by matiasfernandez1** [comment]
Hola @Icarus328, en el enunciado sólo se pide que tengan la opción de regresar al menú anterior los menús. Y "Avanzar hora" es una acción así que no es necesario. Pero de todos modos como no hay nada que lo contradiga, puedes hacer el supuesto de que se puede cancelar la simulación y colocar la opción siempre y cuando lo expliques en tu readme. Saludos.
