### ISSUE TITLE
Uso de QThread.quit() y QThread.exit() (problema 9 semana 6-7)

### ISSUE THREAD

**Issue by benjastraub** [IIC2233/syllabus#323]
Hola, revisé la documentación de los _QThread_ pero no me queda claro cómo utilizar correctamente `quit()` y /o `exit()`.

En el problema 9 hice `connect` del botón detener con el siguiente método:

```
def detenerfunc(self):
        self.thread.exit()
```

donde self.thread es una instancia de una clase que hereda de `QThread` y hace que los cuadrados se agranden y se achiquen.

Esto no funcionó así ni usando `self.thread.quit()`. Sólo funcionó usando `self.thread.terminate()`, pero por lo que leí no es recomendado utilizarlo.

**Comment by fdoflorenzano** [comment]
Hola @benjastraub,

Es buena tu pregunta, gracias por hacerla. Iré por partes:

- Primero, ¿por qué no funcionan `exit` o `quit`, pero sí `terminate`? Leyendo en detalle esta [referencia](https://doc.qt.io/qtforpython/PySide2/QtCore/QThread.html) que encontré, `terminate` es el único que es para interrumpir y detener completamente el *thread* en cuestión. `exit` y `quit` por su parte son para sacar a un `QThread` del *event loop*. ¿Qué significa esto? Un `QThread` entra al *event loop* cuando ejecuta dentro de `run` al método `exec_`. ¿Suena conocido eso último? Es lo mismo que ejecutamos cuando comienza nuestra aplicación (`app.exec_`) para que se detenga para esperar eventos del usuario (en el *event loop*). Luego, como tu *thread* (asumo) nunca llama a `exec_`, ni `exit` ni `quit` tiene efecto sobre el. Ahora revisando el material de contenidos, noto que se menciona `quit` como un símil de `terminate`, pero esto es incorrecto y lo actualizaré pronto.

- Segundo, ¿por qué no se recomienda interrumpir y terminar un *thread*? Porque no es seguro y no sabemos que vamos a interrumpir. Es la misma razón de porque era necesario tener métodos de sincronización entre *threads*. Eventualmente un *thread* puede estar en la mitad de una operación importante cuando se interrumpe: escribiendo en un archivo, actualizando valores, etc... Es por esto que al usar *threads* no es recomendado que estos tengan "vida" indefinida, y que tengan una clara condición de término y lo hagan naturalmente terminando de ejecutar su método `run`.

- Último, ¿cómo hago el ejercicio? Si te fijas, el ejercicio mismo dice que uses `QTimer` para implementarlo. A diferencia de los *threads*, estos están creados para repetirse indefinidamente y para ser detenidos y reiniciados fácilmente usando los métodos `start` y `stop`. Investiga sobre `QTimer` e intenta usarlo.

Espero cada parte se entienda. ¡Me cuentas si te quedan dudas!
