### ISSUE TITLE
actualización de notas (?)

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#323]
La hoja de notas que se sube cuando se suben las notas de actividades/tareas/etc tiene que tener actualizadas las notas post-recolecciones, o eso se hace al final del curso? 🤔

**Comment by flobarrios** [comment]
Si! Se mantiene todo actualizado.

**Comment by naazocar** [comment]
Debo preocuparme entonces si ya me recorrigieron la T01 pero no se ha actualizado en la hoja con las notas?
