### ISSUE TITLE
Siguiente día - pérdida puntos de salud

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#323]
Hola, según el enunciado, por cada día que una criatura esté hambrienta o enferma, pierde cierta cantidad de puntos de vida. Mi duda va con que al pasar al siguiente día, primero se suma 1 a ´dias_sin_comer´ y después se hacen los descuentos respectivos o al revés? porque si una criatura fue alimentada, este contador es cero, pero al pasar al siguiente día es 1 y haciendo lo primero, perdería vida por algo que no tiene mucho sentido... lo mismo con el hecho de enfermarse. Aún así me resulta confuso, porque ha pasado un día, pero no se a partir de qué día se empieza a descontar salud.

**Comment by matiasmasjuan** [comment]
Hola @dlmed !
Tal como señalas, al momento de alimentar una **DCCriatura**, inmediatamente su información sobre **días sin comer** baja a 0. Al pasar al día siguiente, **inmediatamente** se **cambia** los **días sin comer** a 1, y a partir de allí se realizan las demás funciones por si alguna criatura se enferma, que el DCC te haya pagado, las multas, etc).
Ahora bien, según el enunciado, mas específicamente en la sección de **4.2 DCCriaturas**, se señala que una criatura perderá salud si su **nivel de hambre** es **"hambrienta"**, y esto sólo ocurre a partir de 2 días sin comer en el caso de un **Niffler** y **Erkling** y a partir de 3 días para el **Augurey**. Según esto, no pasa el caso en que se descontará **si o si** salud por temas de alimento, ya que al pasar al día siguiente, si bien es cierto que se suma 1 día, no implica que su **nivel de hambre** pasará a **hambrienta** y su salud debe ser descontada.
Sin embargo, para el tema de descontar salud cuando una **DCCriatura** se **enferma**, es distinto. En este caso, si transcurre un día y la criatura se **enferma**, **inmediatamente** se deberá **descontar** su salud. Un ejemplo de esto se muestra en la sección **3.5 Pasar al día siguiente**, en donde la **DCCriatura** apenas se **enferma**, se descuenta **salud**.

Espero haber respondido a tu pregunta, y mucho éxito con tu tarea!

**Comment by dlmed** [comment]
sii gracias!
