### ISSUE TITLE
abstract method nietas

### ISSUE THREAD

**Issue by caroizquierdo** [IIC2233/syllabus#323]
En clases abstractas cuando y le pongo a una funcion abstract method sus hijas tienen que tener si o si es a funcion pero las hijas de la hijas tambien? osea las nietas de la clase abstracta tambien tiene que ocupar esa funcion q se le puso abstract method?

**Comment by Juampisaez** [comment]
Hola @caroizquierdo 
Si haces la prueba te darás cuenta que no es necesario, ya que ya la definiste en la clase padre por lo que las clases hijas tendrán las mismas clases que la "abuela" en este caso (si quieres verlo de esa forma). OJO que también puedes redefinir los métodos como en cualquier Herencia.

Espero haber respondido tu duda, perdón lo tarde de la respuesta :)
