### ISSUE TITLE
consultas.json

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#323]
¿Estas consultas siempre serán creadas manualmente? ¿o en alguna parte del progrma voy a poder generar o guardar informacion en este aechivo?

**Comment by Hernan4444** [comment]
@jorgeriesco ese archivo siempre se te entregará con las consultas listas para leer. La idea es que si quieres probar nuevas consultas las escribas en ese archivo y así no las ingresas de forma manual cada vez que quieras probarla.

Saludos!
