### ISSUE TITLE
Duda respecto a Potencilantro

### ISSUE THREAD

**Issue by JJ-TARS** [IIC2233/Syllabus#323]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas, mi duda es la siguiente: ¿El poder de potenciar el área del Potencilantro y sus mutaciones es permanente o temporalmente mientras vive el Potencilantro?  Si el Potencilantro muere, ya no potencia a los Solaretillos en esa área? O potencia a los Solaretillos como un poder fijo que se mantiene incluso después de la muerte del Potencilantro? Lo mismo para las otras plantas con poderes especiales. 

Muchas Gracias.

**Comment by rodrigoaguilera15** [comment]
Hola qué tal, la respuesta es que el potencilantro debe potenciar solo mientras viva. Si es eliminado, su efecto debe desaparecer de las plantas alrededor.

**Comment by JJ-TARS** [comment]
Muchas gracias
