### ISSUE TITLE
Funciones que retornan una columna

### ISSUE THREAD

**Issue by cho19** [IIC2233/Syllabus#324]
Hola!

¿Se espera que las funciones que retornan una columna impriman dicha columna en el método self.add_answer? ¿Independiente sea una columna gigante o tome mucho tiempo? 

Por ejemplo si hago `filtrar("x", ">", 0)` con `x = extraer_columna("registros", "tiempo_sano")`, ¿en la consola y archivo debo guardar esa enorme lista? ¿O basta con un head/nombre del comando (o en su defecto el objeto que tengo por debajo)?

Gracias de antemano!

**Comment by Hernan4444** [comment]
@cho19 como no especificamos en el enunciado queda a tu criterio como lo muestras. Ojalá que tu decisión implique mostrar algunos datos (por ejemplo 50) para confirmar que el filtrado fue un éxito. 

Lo que si puedo confirmar que no haremos ningún comando que llegue a pedir que imprimas tantos datos. A lo mas filtraremos lo necesario hasta asegurarnos que la lista resultante tenga 50 o menos datos y recién ahí esperaremos verla.

Saludos!!

**Comment by cho19** [comment]
@Hernan4444 Lo tendré en cuenta! Muchas gracias :)
