### ISSUE TITLE
No puedo agregar widgets

### ISSUE THREAD

**Issue by dacampos1** [IIC2233/syllabus#324]
Hice un QWidget que crea varias labels para el tablero, cuando voy  poner una torre quiero crear una nueva label y no puedo. Tengo el mismo problema con el crear monedas y enemigos, solo puedo moverlos si ya los había creado en el init.
Vi un issue relacionado, pero cuando creo los nuevos elementos siempre  indico el parent y aún  así no funciona.

**Comment by jaromero6** [comment]
Hola
El problema que tienes se podría deber a las siguientes razones:
- Si lo estás creando fuera del init, deberías hacer show del label o widget.
- Deberías estar guardando una referencia del objeto, que estás creando, si dentro de un método haces `label = QLabel(self)` por ejemplo, al salir del metodo perderás la referencia de la variable label, deberías hacer algo como `self.label = QLabel(self)` o guardar esto en una lista por ejemplo, etc.(Hay varias formas de guardar la referencia).



Espero que esto aclare tu duda, de lo contrario podrías especificar exactamente cual es el problema que tiene, es decir, ¿te arroja error? ¿no se muestran los labels?, etc. 
Espero que te ayude y ánimo con la tarea

**Comment by dacampos1** [comment]
Hola, he intentado ambas cosas y ninguna resulta. Hice por ejemplo una función para crear enemigos  y los genera sin problema en el init. Pero cuando trato de usar señales para llamar la función no aparecen en la ventana, cuando uso show se abren ventanas independientes. 
![Captura de Pantalla 2019-05-21 a la(s) 15 08 02](https://user-images.githubusercontent.com/42916420/58123700-6808b980-7bda-11e9-915a-c142165f1a82.png)

**Comment by jaromero6** [comment]
El problema debería entonces estar en la clase Enemigo, comprueba que tengas algo como esto:
```
class Enemigo:
      def __init__(self,parent, ....<mas parametros>):
               self.label = QLabel(parent)  # Ojo: Aqui va parent, que sería el self que le pasas como parametro
               # Despues añadirle la imagen y lo que sigue de la clase es importante
```
Digo esto, porque si se te están abriendo ventanas a parte, lo más probable es que en alguna parte le estés pasando una referencia distinta a la de ventana a un label, y por esto se abre en una ventana aparte.

**Comment by dacampos1** [comment]
He probado de varias manera y todavía no puedo, cuando defino Enemigo si referencie  la ventana como parent. Pero al conectarla por ejemplo a un boton no aparecen.

**Comment by isidonoso** [comment]
En la función que esta arriba y se llama al parent no se considera modelación circular? había entendido en la issue #275 que eso si se consideraba ya que crea la clase enemigo y se ocupa a si mismo como parametro para poder crearla

**Comment by jaromero6** [comment]
Efectivamente se considera modelación circular, una solución a esto es si simplemente crear el label en el frontend y así evitar caer en modelación circular. Por lo que guíate por esa issue para evitar caer en este tipo de modelación, disculpa haberte dado un código incorrecto.
