### ISSUE TITLE
Duda decoradores T03

### ISSUE THREAD

**Issue by Javierdr** [IIC2233/Syllabus#324]
Tengo una duda. ¿En esta tarea se va a evaluar el uso de decoradores? Ya que lo vimos la última semana, pero el enunciado no dice nada de si se va a evaluar directamente esto.

**Comment by BeaGaete** [comment]
Tengo otra duda: en un decorador puedo usar un for?

**Comment by egromero** [comment]
Hola, no se evaluará decoradores en esta tarea.

Saludos!
