### ISSUE TITLE
Error al instalar Designer.exe

### ISSUE THREAD

**Issue by Jprampad** [IIC2233/syllabus#324]
Tengo un problema al instalar Designer usando pip3 o pip, me da el siguiente error:
![Captura de Pantalla 2019-09-23 a la(s) 19 46 26](https://user-images.githubusercontent.com/49689744/65468586-f2885080-de3a-11e9-9442-c41e87b00b28.png)

Busco Designer.exe por el Finder y no lo tengo. 
Gracias de antemano

**Comment by mjvarela** [comment]
Hola! por lo que sé QtDesigner no se puede descargar mediante la terminal en mac. Te recomiendo descargarlo desde el siguiente link [https://build-system.fman.io/qt-designer-download](https://build-system.fman.io/qt-designer-download). Ojalá te sirva 😄

**Comment by Jprampad** [comment]
Gracias!

**Comment by adbakulic** [comment]
Hola! 
Me descargué Qt Designer con el link para mac pero se abre por separado y no muestra todas las opciones. Adjunto una foto para que se entienda mejor:
<img width="1280" alt="Captura de pantalla 2019-09-26 a las 12 26 20 p m" src="https://user-images.githubusercontent.com/42577073/65701964-9bf85d80-e058-11e9-87dd-8bec696834e3.png">

**Comment by mjvarela** [comment]
Hola! Así es como es designer 😁 Al crear un archivo (Widget, Main Window, etc) te da la opción de meterte a view y agregar todas las opciones de diseño. Adjunto foto de como se vería con todas las opciones seleccionadas
![Captura de Pantalla 2019-09-26 a la(s) 12 31 23](https://user-images.githubusercontent.com/42159497/65702667-c7c81300-e059-11e9-9c49-e6fea0844575.png)

**Comment by adbakulic** [comment]
Gracias jajajajaja!!
