### ISSUE TITLE
Problema con paths e importacion de módulos de entrega intermedia (ImportError: attempted relative import beyond top-level package)

### ISSUE THREAD

**Issue by MathiasPrett** [IIC2233/Syllabus#324]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. Necesito ayuda para importar las funciones de la entrega intermedia al backend de mi entrega final. He leído bastante sobre los contenidos de importación de módulos y no logro importar correctamente los archivos.

asi mas o menos esta organizado mi directorio de la tarea 2

```
.
└── T2/
    ├── entrega_final/
    │   ├── cliente/
    │   │   ├── backend/
    │   │   │   ├── elementos.py
    │   │   │   └── **logica.py**
    │   │   ├── frontend/
    │   │   │   ├── ventana.py
    │   │   │   ├── elementos.py
    │   │   │   ├── parametros_frontend.py
    │   │   │   └── assets/
    │   │   │       └── ...
    │   │   └── main.py
    │   └── servidor/
    │       └── ...
    └── entrega_intermedia/
        ├── **funciones_cliente.py**
        └── ...

```

Resulta que en logica.py estoy intentando importar las funciones de cliente de la siguiente manera:
`from ....entrega_intermedia.funciones_cliente import validacion_formato`

y me esta tirando el error:
`ImportError: attempted relative import beyond top-level package`

Por lo general no tengo problemas importando, pero cuando se trata de importar hacia un archivo mas "profundo", ya sean modulos o sprites, suelo tener este tipo de problemas.

Gracias!

**Comment by AntonioVenegas** [comment]
Hola @MathiasPrett!, en ese caso te recomiendo copiar las funciones de entrega intermedia en donde tengas que usarlas en entrega final, así no te complicas con los imports.

**Comment by MathiasPrett** [comment]
> Hola @MathiasPrett!, en ese caso te recomiendo copiar las funciones de entrega intermedia en donde tengas que usarlas en entrega final, así no te complicas con los imports.

Hola @AntonioVenegas, gracias por tu respuesta. Sin duda te voy a hacer caso con esa solución y no me voy a complicar con lo demás, pero de todas formas me deja preocupado no saber como arreglar un problema asi a futuro con lo que me queda aún por hacer en la tarea, cuando "copiar y pegar" un archivo no sea lo correcto. Hay alguna parte de los contenidos donde se explique mejor como arreglar este caso específico?

Gracias

**Comment by AntonioVenegas** [comment]
En la parte de los contenidos de la semana 0 se ve modularización y en particular como importar archivos, ahora bien, el problema de importar archivos desde una carpeta superior es que python revisa solo la carpeta desde donde se está ejecutando tu archivo para buscar el modulo a importar. Una solución es usar sys.path.append(..), sin embargo no te la recomiendo, ya que es una mala práctica.  Por otro lado, es mejor tener todos los archivos/carpetas que necesitas para ejecutar main.py en una carpeta donde puedan ser accedidos (al mismo nivel por así decirlo) y así no tienes que hacer imports relativos ni nada por el estilo.

Espero eso haya resuelto tu duda :)
