### ISSUE TITLE
Reiniciar juego

### ISSUE THREAD

**Issue by TriniAguilera** [IIC2233/Syllabus#324]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Tengo una duda sobre la situación en que luigi choca con un fuego:
1. Cuando no hay cheatcode: Entiendo que las vidas no se reinician (se pierde una por tocar el fuego, si llega a 0 entonces pierde). Respecto al tiempo, este se debe reiniciar o se mantiene en donde estaba para seguir disminuyendo?
2. Cuando hay cheatcode KIL: actualmente cuando está este cheatcode, si luigi choca con el fuego yo hago que vuelvan a aparecer los villanos (todos los fantasmas desde el inicio). No se si estoy bien o tengo que hacer que estos no aparezcan si reinicia el juego.
3. Cuando hay cheatcode INF: actualmente si reinicia el juego, las vidas y el tiempo están estáticas (no disminuyen).  El resto de los elementos del tablero vuelven a sus posiciones iniciales.

Como último detalle, no se si está bien asumir que habrá uno de los dos cheatcode aplicados, no ambos al mismo tiempo (mi plan es especificarlo en el readme).

**Comment by ignaciovita** [comment]
Hola! Te respondo según los 3 casos que mencionas:

1. En el enunciado no se menciona qué debe ocurrir con la cuenta regresiva cuando se reinicia el nivel, por lo que queda a tu criterio. Te recomiendo que el tiempo también se resetee al reiniciar el nivel, pero eres libre de elegir lo que más te acomode. En cualquier caso, no olvides mencionar en tu README qué opción eliges.
2. En el enunciado tampoco se menciona si los villanos deben volver a aparecer en el mapa luego de reiniciarse un nivel, tras haber presionado previamente el cheatcode KIL. Esto también queda a tu criterio. Puedes hacer que los villanos desaparezcan para siempre, o bien que solo desaparezcan para el nivel actual (en este último caso, el cheatcode KIL debería poder volver a usarse en el nuevo nivel). También podrias incluir en tu README lo que acabes haciendo.
3. En este caso, debe ocurrir como dices.

Respecto al último detalle, está bien asumir eso, si lo especificas en el README. Lo importante es que ambos cheatcodes estén correctamente implementados y que se puedan probar de forma separada.
