### ISSUE TITLE
Hardcoding de paths

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#324]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Se hace mucho hincapié sobre el _hardcoding_, sin embargo, podemos hardcodear los paths de los .csv, asumiendo que están en el mismo directorio (no haría falta os) y siempre se llamarán "canales.csv, barcos.csv, etc" ?

**Comment by matiasfernandez1** [comment]
Hola @fernandosmither.
Utilizar el nombre de los archivos csv para el path no sería considerado harcoding. Si es que te refieres al usar algo como `open("canales.csv", "r")`.

**Comment by fernandosmither** [comment]
> Hola @fernandosmither.
> Utilizar el nombre de los archivos csv para el path no sería considerado harcoding. Si es que te refieres al usar algo como `open("canales.csv", "r")`.

### Sí, a eso me refería. De todas formas, cuando leo omito el "r" ya que python lo hace por defecto, asumo que no afecta en la evaluación no ponerlo?

**Comment by matiasfernandez1** [comment]
No está dentro de [_malas practias_](https://github.com/IIC2233/syllabus/issues/222) así que no.
