### ISSUE TITLE
Evitar copia actividades sumativas

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#324]
Hola!, cuando tiempo dps de hacer el push de las 17:00 podemos comentar entre nosotros las actividades sumativas.

**Comment by lily416** [comment]
Hola @sa-Appel,
 
Pueden hablar de las actividades cuando se cumpla alguna de las siguientes situaciones:
* Ya se encuentre subido el video de cierre de la actividad, o
* Cuando se termine el día de la actividad, es decir, desde el viernes en adelante.
 
Esto se debe a que algunos de sus compañeros y compañeras siguen rindiendo la actividad después de las 16:50, por lo que no sería correcto que hablaran de ella mientras ellos siguen rindiendo la actividad.
 
Saludos y que tengas una buena semana 👋🧙

**Comment by sa-Appel** [comment]
perfect gracias!
