### ISSUE TITLE
Producción de soles Solaterillo

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#325]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas. En la foto adjunta del enunciado, la temperatura que aparece en la fórmula de producción de soles, es variable?? o consideramos que vale TEMPERATURA_INICIAL?
<img width="941" alt="temperatura" src="https://github.com/user-attachments/assets/15e0d763-6b77-4f32-b947-f6cdd3f905f1">

**Comment by PkAlvaro** [comment]
Hola @martinpint! Espero que estés teniendo una buena noche 😄 te comento respecto a tu duda, en el caso del Solaretillo, la temperatura que indica la fórmula es variable respecto a cada día que va pasando según el funcionamiento del parametro de temperatura mencionado en el punto 5.1 del enunciado, TEMPERATURA_INICIAL es solamente el caso primero y no es el general.

Espero que te haya quedado mas claro 👍
