### ISSUE TITLE
Preprocesamiento

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2233/Syllabus#325]
Tengo 2 dudas acerca de los comentarios con bots:
1- Si una palabra dentro de vocabulary aparece en una review dentro de otra palabra, ¿se cuenta o no? (Por ejemplo: enjoy, enjoyable)
2- En algunas reviews hay oraciones mal escritas donde faltan espacios. Para contar el número de palabras, asumimos que serían sólo una palabra? Esto también afecta en mi primera duda, ya que, por ejemplo, si aparece en una review "Ienjoyrikanmortin" no sería lo mismo que buscar "I enjoy rikanmortin"

**Comment by santilaguna** [comment]
@jpmoraga1 
Para el preprocesamiento podemos crear nuestro propio archivo de reviews procesados o editar los originales ¿o la idea es preprocesarlos cada vez que queramos leer ese archivo?

**Comment by iqacevedo** [comment]
@santilaguna  si puedes, siempre y cuando la primera vez que se abra la interfaz se haga un preprocesamiento.

Saludos !

**Comment by santilaguna** [comment]
Gracias!

**Comment by naquiroz** [comment]
@iqacevedo Entonces para efectos del bot, debemos considar palabras que tengan como subpalabra palabras del volcabulario?

**Comment by iqacevedo** [comment]
@naquiroz si !

Saludos !

**Comment by naquiroz** [comment]
@iqacevedo Es obligatorio hacer eso? Porque ahora que he avanzado más , me dí cuenta que es más facil chequear que la palabra exacta esté en la frase, vs que la subpalabra esté en la frase.

**Comment by fpattillo** [comment]
Tengo la misma duda. Además, se me hace raro darle connotaciones positivas o negativas a palabras que pueden tener poco que ver con su "superpalabra", ejemplo: head, big-headed.

**Comment by Arcoirisky** [comment]
@naquiroz Si es obligatorio hacer eso O: De hecho, en la misma issue que presentas te dicen que es obligatorio. Lean esa issue que está bien explicado todo por Rihanuch uwu
