### ISSUE TITLE
Líneas vacías extra en laberintos

### ISSUE THREAD

**Issue by GitCross135** [IIC2233/Syllabus#325]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, en los archivos .txt que contienen los laberintos hay líneas extras vacías al fondo, en el tablero_1.txt hay 4 líneas vacías luego de los datos para el laberinto, en el tablero_2.txt hay 2 líneas vacías extras y en el tablero_3.txt no hay ninguna, podemos modificar estos archivos para borrar esas líneas o está pensado que sean así para algo?

tablero_1.txt:
![image](https://github.com/IIC2233/Syllabus/assets/130419134/bc8e5c3e-b319-44dd-937d-11719dffb490)

**Comment by AntonioVenegas** [comment]
Hola!, en la issue https://github.com/IIC2233/Syllabus/issues/322 se ya se respondió esta misma duda. (pero si, si puedes borrarlos)

Saludos :)
