### ISSUE TITLE
Probabilidades - parámetros

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#325]
Hola, hay algunos parámetros de las criaturas que son probabilidades, que en el enunciado dice que se mantienen entre 0 y 1, pero que también al momento de crear una criatura, estos parámetros toman un valor dentro de un rango. El tema es que, si es una probabilidad que se asigna al principio (creación de la criatura) y no cambia a lo largo del juego (como para usar una prop), cuál es la posible implementación de estos rangos (0, 1) y la necesidad de agregarlos como parámetros en `parametros.py`?

**Comment by jeschuwirth** [comment]
Hola @dlmed,

Digamos una criatura tiene una probabilidad de 0.3 de enfermarse, luego en tu código puedes generar un variable `K` de valor un número aleatorio entre 0 y 1 (la función del módulo random que hace eso te la dejo como tarea).

Entonces, si K obtiene un valor menor al de parámetros la criatura se enferma, en caso contrario no lo hace.

Éxito!

**Comment by anamanzana** [comment]
Hola! Me sigue quedando la duda, en el caso de **alimentar** a la criatura se genera una probabilidad por ejemplo del 40%, eso quiere decir que me atacaran? **A partir de que porcentaje** mi criatura atacara a mi magizoologo al **alimentarlo.**

**Comment by jeschuwirth** [comment]
@anamanzana, no entendí mucho tu duda, si te refieres a esta parte del enunciado:

![image](https://user-images.githubusercontent.com/37160256/78895457-e5305d80-7a3c-11ea-83c3-225a1d2b3212.png)

Entonces si el resultado de esa fórmula es 40, tienes un 40% de que tu criatura te ataque, por lo tanto debes hacer un random que sea` True` el 40% de las veces y `False` el otro 60%

Como le dije a @dlmed, te recomiendo convertir ese 40 en un 0.4 y obtener un valor random (float) entre 0 y 1, de ese modo, luego basta con hacer la comparación:

`valor(en este caso un random entre 0 y 1) < probabilidad(en este caso un 0.4)`

Esa comparación tiene un 40% de ser True y un 60% de ser False

Éxito!

**Comment by anamanzana** [comment]
Buenos dias,

Entonces, esto aplicar para alimentar, escaparse y enfermarse? O en el caso de enfermarse se compara la probabilidad de enfermarse dada con la probabilidad generada con la ecuación dada?
Es ahi donde surgio mi duda, se otorga tanto para escaparse o enfermarse un valor dado según el tipo de criatura y a su vez una ecuación que daba un float. Pero en el caso de alimentar no daban una probabilidad en el enunciado.

Saludos!

**Comment by lily416** [comment]
@anamanzana esta metodología explicada por @jeschuwirth se aplica para todas las fórmulas de probabilidad que se indican en el enunciado:
* Que la criatura ataque al Magizoólogo mientras se le alimenta. (pág. 10)
* Que la criatura escape al iniciar un nuevo día. (pág. 11)
* Que la DCCriatura se enferme al comienzo de cada día. (pág. 11)
* Recuperar un criatura que escapó. (pág. 8)
* Sanar una DCCriatura enferma. (pág. 8)
* Y cualquier otra fórmula de probabilidad que pueda haber pasado por alto.

Fíjate, que los atributos de las criaturas que tienen relación con la probabilidad de escapar y enfermarse, se utilizan como parte de las funciones de probabilidad, por lo que solo son un factor de la ecuación.

En el caso de alimentar, las probabilidad de ataque de la criatura se verá afectado por el hambre y la agresividad de la criatura.


Espero que te quede más claro, quedo atenta en caso de que tengas dudas 😉 
Saludos y éxito en la tarea 👋🧙‍♂️
