### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#325]
Hola: 
Hace dos dias corrí main.py y funcionaba, se abría la nueva ventana y todo bien. No he modificado el modulo, no he agregado ni quitado  algo, lo acabo de correr y me tira el siguiente error:
<img width="1192" alt="captura de pantalla 2017-04-26 a las 11 51 28 p m" src="https://cloud.githubusercontent.com/assets/26121354/25465949/f2bc39aa-2adb-11e7-93d0-e8127ce10453.png">
¿ Qué está pasando? ¿ Cómo arreglo esto? ------> Ayudaaaaaaaaaa!!!
Saludos :B

**Comment by rrhurtado** [comment]
Por lo que investigué, parece ser un error con la ejecución de librerías de 64 bits en un entorno de 32 bits, o viceversa.

La solución propuesta es correr el código con el siguiente prefijo.
`VERSIONER_PYTHON_PREFER_32_BIT=no /usr/bin/main.py`

Fuente: http://stackoverflow.com/a/32144521

**Comment by norman123123** [comment]
Como y donde hago eso? tengo el mismo problema. No funciona desde pycharm?
