### ISSUE TITLE
Duda enunciado ejercicios propuestos semana 6-7 QGrid

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#325]
Hola estaba haciendo los ejercicios propuestos y me encontré con esto en el paso 2 del ejercicio largo:
![image](https://user-images.githubusercontent.com/48482216/65469167-c7066580-de3c-11e9-99ef-fbff05d38f63.png)
Mi duda es si con QGrid se refiere a QGridLayout o existe una clase que sea solo QGrid?
No pude encontrarla asi que supongo que se refiere al Layout
gracias de antemano

**Comment by StroveLight** [comment]
Hola! Se trata de QGridLayout.
Saludos
