### ISSUE TITLE
Formula de probabilidad de encallar

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#325]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

#### Hay algo que no me calza sobre la probabilidad de encallar.
![image](https://user-images.githubusercontent.com/66154723/115975656-8d27a480-a534-11eb-87af-7d4723a151f4.png)
####  Haciendo un caso extremo (tirado a menor) podría ser el siguiente:

![image](https://user-images.githubusercontent.com/66154723/115975678-bd6f4300-a534-11eb-9666-ffa951648a25.png)

### En Wolfram, el cálculo de un caso horriblemente representativo tirado hacia abajo (es decir, la gran mayoría daría un valor mucho mayor a este) nos da:
![image](https://user-images.githubusercontent.com/66154723/115975754-99f8c800-a535-11eb-81ed-f87663cdbce1.png)
![image](https://user-images.githubusercontent.com/66154723/115975768-c1e82b80-a535-11eb-8585-73d64de4d39c.png)

### Con lo cual, a menos que haya un barco horriblemente nerfeado (que no sé cuantos hayan), siempre el min(1, formula) agarrará el 1, a lo que pregunto entonces, ¿Cuál es el punto de hacer la fórmula siquiera, si simplemente podríamos dejarlo como 1?

Espero se haya entendido. Gracias!

**Comment by Emiliax16** [comment]
Hola @fernandosmither ! lo que puede hacer es cambiar los valores del peso de `mercancia.csv` a la hora de importarlos en tu programa, mediante alguna división del peso real por alguna constante. Por ejemplo, si los pesos de las mercancías se encuentran en otro rango (ej. 20-25 👀), la probabilidad de que la fórmula sea menor a 1 aumenta muchísimo. Recuerda que tu manejo de csv debe estar preparado para que en la revisión, cambiemos algunos valores y no ocurran errores en el flujo !!
Quedo atenta si aún sigues teniendo dudas, ten en consideración mi ejemplo del rango!!

Saludos.

**Comment by fernandosmither** [comment]
> Hola @fernandosmither ! lo que puede hacer es cambiar los valores del peso de `mercancia.csv` a la hora de importarlos en tu programa, mediante alguna división del peso real por alguna constante. Por ejemplo, si los pesos de las mercancías se encuentran en otro rango (ej. 20-25 👀), la probabilidad de que la fórmula sea menor a 1 aumenta muchísimo. Recuerda que tu manejo de csv debe estar preparado para que en la revisión, cambiemos algunos valores y no ocurran errores en el flujo !!
> Quedo atenta si aún sigues teniendo dudas, ten en consideración mi ejemplo del rango!!
> 
> Saludos.

Gracias!, Me parece muy lógica tu respuesta!, pero me preocupa que de base algo así de fundamental no haya sido mencionado en el enunciado mismo. En base a esto, me seguirías recomendando dividirlo por alguna constante numérica, o puedo dejarlo como está? (ya que si divido estos grandes números en una cte, un rango hipotético de 20-25 disminuiría aún más 👀 , pero sin dividirlo, funcionaría impeke en ese rango)

**Comment by Emiliax16** [comment]
Actualmente, en `mercancia.csv`, el peso de cada lote está entre 80 y 100. La división de los valores actuales por alguna constante es para que veas bien con qué rango funciona mejor la fórmula, pero pensándolo mejor, una vez que hayas descubierto el rango más adecuado (como el ejemplo que hemos estado nombrando 🌞 ), modifica el archivo csv directo con los nuevos valores que sean pertinentes. Si haces click con ctr presionado (o en su defecto, cmd), puedes dejar el cursor en varias líneas al mismo tiempo, lo que te permitiría modificar varios valores a la vez. A la hora de la corrección, ten la seguridad que tendremos en archivo con el rango correcto para que funcione sin problemas esa fórmula.

Destaco que más que problema de enunciado, fue un pequeño problema nuestro al hacer ese csv, por lo que te agradezco mucho haberte percatado de esto. Espero que mi respuesta te pueda ayudar. Mucho ánimo con tu tarea y estaré atenta si sigues con dudas.

**Comment by fernandosmither** [comment]
> Actualmente, en `mercancia.csv`, el peso de cada lote está entre 80 y 100. La división de los valores actuales por alguna constante es para que veas bien con qué rango funciona mejor la fórmula, pero pensándolo mejor, una vez que hayas descubierto el rango más adecuado (como el ejemplo que hemos estado nombrando 🌞 ), modifica el archivo csv directo con los nuevos valores que sean pertinentes. Si haces click con ctr presionado (o en su defecto, cmd), puedes dejar el cursor en varias líneas al mismo tiempo, lo que te permitiría modificar varios valores a la vez. A la hora de la corrección, ten la seguridad que tendremos en archivo con el rango correcto para que funcione sin problemas esa fórmula.
> 
> Destaco que más que problema de enunciado, fue un pequeño problema nuestro al hacer ese csv, por lo que te agradezco mucho haberte percatado de esto. Espero que mi respuesta te pueda ayudar. Mucho ánimo con tu tarea y estaré atenta si sigues con dudas.

Perfecto! Escribí un programa en python que expulsa un mercancias.csv con todos los valores divididos en 4, ¿Lo puedo compartir para ayudar a mis compañeros?

**Comment by Emiliax16** [comment]
¡Que bueno que lo hayas entendido! respecto a lo de compartir, creemos que es mejor no compartir ningún script para evitar malos entendidos, es mejor prevenir cualquier problemita uwu muchas gracias por tu consideración, espero que te vaya muy bien en el resto de la tarea 💟

**Comment by aagodoy1** [comment]
Holaa 
Estaba leyendo esto y me queda la duda, entonces debemos dividir los valores de mercancía.csv divido por 4 u otra constante? o lo dejamos como está?

**Comment by fernandosmither** [comment]
> Holaa
> Estaba leyendo esto y me queda la duda, entonces debemos dividir los valores de mercancía.csv divido por 4 u otra constante? o lo dejamos como está?

Déjalos como están en tu programa. Si quieres (para probar tu código en condiciones ideales) divide manualmente los valores de tu .csv por alguna cte, pero si no lo quieres, solo no lo consideres. **Recuerda que el .csv no se sube, con lo cual no te afectará de todas formas.**

**Comment by Emiliax16** [comment]
Hola @aagodoy1 ! tal como dice @fernandosmither , puedes modificar el csv de mercancías y cambiar los pesos (los cuales se encuentran en un rango de 80-100) a un rango que puede adaptarse mejor a la fórmula (ej: 20-25). Con eso, puedes visualizar mucho mejor la probabilidad de encallar. Nosotres tendremos los rangos correctos a la hora de corregir. Como mencioné anteriormente, una forma de cambiar rápido varios valores a la vez es:

_Sublime_: click mientras se mantiene presionado ctrl, así puedes borrar muchas cosas al mismo tiempo.
_Vscode_: click mientras se mantiene presionado alt.

Cabe destacar que si en esta fórmula (o en cualquier otra) algo da negativo, deben considerarlo como 0 (la menor probabilidad). Para saber más de esto, recomiendo revisar la issue [#295](https://github.com/IIC2233/syllabus/issues/295).
