### ISSUE TITLE
Imagenes desaparecen

### ISSUE THREAD

**Issue by YoGandalf** [IIC2233/syllabus#325]
Cuando quiero empezar una oleada de mas de 2 enemigos (2 porque hay 2 tipos de enemigos)
las imagenes como que se corresponden entre si y solo puedo ver una de cada tipo, es decir, un kamikaze y un normal. LLevo mucho rato buscando el error y googleando y no encuentro nada.
Alguna recomendacion?

**Comment by jmwielandt** [comment]
Hola!

¿Cómo estás manejando las imágenes?
En un principio, no debería haber ningún problema con setear un mismo QPixmap a varias QLabels...

**Comment by YoGandalf** [comment]
Tengo una variable con todos los paths y despues con un for hago QLabel(self) setPixmap(QPixmap) y el resto de cosas para cada enemigo
Al momento de mostrarlos todos tambiern lo hago con un for

**Comment by jmwielandt** [comment]
¿Puedes actualizar tu repo?
Avísame cuando lo hayas hecho.

**Comment by YoGandalf** [comment]
Listo
Se corre mapatarea aunque tambien se puede ventanainicio
Las funciones son guardar_imagenes agregar_enemigos y mover_enemigos
Las variables con nombres raros y cortos como "cc" o "al" estan en funciones line 158
