### ISSUE TITLE
LEER ARCHIVOS

### ISSUE THREAD

**Issue by Chiseth** [IIC2233/Syllabus#325]
llevo como 2 horas intentando leer los archivos y no sé por que no los lee todos, hice algo tan simple como
with open('tests_publicos/data/s/animales.csv', "r") as file:
    for line in file:
        datos = line.strip().split(",")
        print(datos)
solo para visualizar que leyera todas las lineas pero solo me enseña las de 8984 a 10000, el problema está en que cuando hice algo más elaborado haciendo las tuplas, el test case me daba error, ya que decia que mi cantidad de tuplas era mucho menor a las 10mil que se esperabann, por lo que no sé como hacer que realmente guarde esa cantidad tan grande de datos ;/

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Chiseth** [comment]
Es de la T3 : c

**Comment by IsidoraCarmona** [comment]
Tengo el mismo problema

**Comment by tcapom** [comment]
Hola @Chiseth !

Para revisar si es un problema de que no se estén leyendo todas las líneas, para el mismo test de 10000 líneas con el que estabas probando, deberías debuggear (usando un `for`, contador, o lo que estimes conveniente) para visualizar un rango de datos específico (por ejemplo, las primeras 500 líneas de un archivo). Si es que sí se puden ver, debe ser un tema solamente de la consola de no poder ver todas las líneas, pero el archivo debería estar cargando sin problemas.

Lamentablemente cuando te refieres a:

> el problema está en que cuando hice algo más elaborado haciendo las tuplas

El comentario es muy vago para entender qué realmente ocurre. Aún así, la discrepancia que podría estar generando errores es que si dices:

> no sé como hacer que realmente guarde esa cantidad tan grande de datos ;/

Podría ser que estás obviando el hecho de que la función `cargar_datos` pide retornar un generador, por lo que realmente no deberías estar en ningún momento guardando una cantidad tan grande de datos.
