### ISSUE TITLE
Confusion al commit de AS01

### ISSUE THREAD

**Issue by MagnaThyrsus** [IIC2233/syllabus#325]
Mi último commit para la AS01 lo hice un buen rato, al menos 10 minutos antes de que terminara el tiempo. Estaba seguro de que estaba bien porque probe el codigo en un notebook de jupyter.

El problema es que hace poco lo probe con otros programas (Sublime y vsc) y tira error. Ya solucione el error pero no se si hacer un commit ahora sea válido. ¿Qué se hace en esta situación? Yo deje de preocuparme porque el código si me funcionó en jupyter.

**Comment by Juampisaez** [comment]
Holaa @MagnaThyrsus 
En primer lugar decirte que para las próximas actividades, tareas y la vida en general, trabajes siempre en un editor de codigo como Vscode, sublime, pycharm, etc (de preferencia Vscode) al crear códigos, ya que jupyter notebook a pesar de que se puedan escribir códigos, no es un editor de codigo como tal. (en el curso se ocupa por permitir ejemplos de códigos simples principalmente y ser editor de texto).
Lamentablemente, cuando termina el horario de las actividades no se permiten mas commits (que puedan ser revisados), por eso se recomienda realizar varios commits durante el horario de actividades.

Espero resolver tu duda, y ánimo, aun quedan mas actividades :)
