### ISSUE TITLE
Numpy?

### ISSUE THREAD

**Issue by andreslyon** [IIC2233/Syllabus#326]
en la funcion graficar sale que se debe usar unicamente numpy 1.12. Pero significa que solo podemos usar numpy y esa version? o en caso de usar numpy tiene que ser esa version?

**Comment by iqacevedo** [comment]
Hola!
Lo que sucede es que para graficar se utiliza la libreria matplotlib, la que a su vez requiere que utilices los arrays de la librería numpy. Entonces de numpy solo puedes usar numpy.array en esa parte de la tarea, y tiene que ser la version 1.12 porque es con la que se revisara.

Saludos!
