### ISSUE TITLE
Temperatura negativa

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#326]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas, en la foto adjunta, si es que la temperatura es bajo 0, o sea negativa, igual la añadimos en la fórmula?, ya que esto nos dará una producción negativa.
<img width="988" alt="Captura de pantalla 2024-09-10 a la(s) 10 41 28 p  m" src="https://github.com/user-attachments/assets/407419f8-51a0-4e8c-99cc-82bec84b5ebb">

**Comment by R3Y3X** [comment]
Hola espero que estés bien. Revisa esta issue #306, en resumen queda a tu criterio como implementar la producción de soles en ese caso, recuerda explicar en el README . Éxito en la tarea ⚡

**Comment by 3rdPix** [comment]
- [ ]
