### ISSUE TITLE
Días consecutivos de una criatura enferma

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#326]
Hola, según los .csv y el enunciado, está bien asumir que lo único que se mantiene un tracking a lo largo de los días (independiente si se deja de jugar) son los días sin comer? Porque al principio de cada nuevo día hay eventos que dependen de los días sin comer y los días estando enferma, pero de esto último, no hay datos en los .csv, por lo que al dejar de jugar da lo mismo qué una criatura esté enferma? podría cerrar el juego y así se vuelve a cero la cantidad de días enferma (?)

**Comment by dlmed** [comment]
Creo que ya no tengo esta duda

**Comment by aljara97** [comment]
Hola @dlmed!

Voy a responderte igual, para que estés seguro y porque puede servirle a otro compañero con la misma duda jajaja. Dado la naturaleza del archivo `criaturas.csv` no se indica la cantidad de días que lleva enferma una criatura, por tanto, al momento de cerrar el programa y cargar el magizoólogo nuevamente puedes asumir que es el primer día que esta se enferma (día 0). Recuerda que igual hay una columna de este archivo que te indica si la criatura está enferma y los días sin comer.

Éxito 🧙

**Comment by dlmed** [comment]
gracias!

**Comment by aljara97** [comment]
De nada 🧙‍♂️

**Comment by Camila-sty** [comment]
Hola!
Qué pasa si la criatura lleva más días sin comer de los que ponen como condición para pasar de *satisfecha* a *hambrienta*  según cada tipo de criatura?, igual sucede esto? 
Yo supongo que si, pero prefiero que me lo aclaren. Además tampoco sé si pueden llegar a tener más de 3 días sin comer.

**Comment by aljara97** [comment]
@Camila-sty, por favor concentra tu duda en la issue que hiciste recientemente, ya hay un ayudante asignado para esta. En caso de que corresponda, dirigirá tus dudas a otra issue.
