### ISSUE TITLE
uso de pyqt5

### ISSUE THREAD

**Issue by benjabarrios** [IIC2233/Syllabus#326]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema
![image](https://github.com/IIC2233/Syllabus/assets/112400703/857a1d9c-45f9-4ed2-b181-765c520de4a9)

[Al ejecutar un código de ejemplo que usa pyqt5 (un código de clases ejecutado en otra ventana) me arroja el error de la imagen, no tengo idea el motivo, ya que pyqt5 esta efectivamente instalado en mi pc]

**Comment by Hernan4444** [comment]
Hola @benjabarrios 

Lo que estoy viendo, es que  cuando ejecutas archivos, ocupas un python que está en `AppData/Local/Microsoft`, mientras que cuando instalas cosas, se está instalando en un python que está en `appData/local/programs`. Con eso, creo que en tu computador hay, al menos, 2 pythons instalados, y si bien pyqt5 ya está instalado en uno, se está usando otro para correr tus programas.

Lo que te recomiendo, es utilizar la consola par acceder a la carpeta T2 y ahí usar`python3 main.py`,  `python main.py` o `py main.py` para correr tus archivos. Luego, con el comando que te funcione, asumamos "python3", hacer `python3 -m pip install pyqt5`. De esta forma, te aseguras que el python ocupado para ejecutar cosas se encargue de instalar su versión de pyqt5, y no otro que no se está ocupando.

Si quieres mantener el uso de VSCode para ejecutar tus archivos, te recomiendo investigar cómo cambiar la versión de python que se está ocupando por defecto al momento de ejecutar archivos en VSCode. De este modo, hacer coincidir la versión que ocupa VSCode con la versión que efectivamente tiene instalado pyqt5.

Cuantanos cómo te va con eso :D
Saludosヾ(＾-＾)ノ

**Comment by benjabarrios** [comment]
Hola, muchas gracias si me ayudó a reconocer el problema, mi computador traía una app de python por defecto y además al inicio del curso descargue aparte python, entonces al seleccionar el kernel elegía el que no tenía instalado pyqt5.
