### ISSUE TITLE
Contenidos a evaluar AC sumativa

### ISSUE THREAD

**Issue by pwillmer** [IIC2233/syllabus#326]
Hola! para la actividad sumativa de este jueves entra hasta el tema 8 "conexiones entre ventanas"?

**Comment by Drpinto1** [comment]
¡Hola!
Para la actividad sumativa del jueves (y en general para todas las actividades) entra todo el material hasta la semana correspondiente.

Puedes revisar qué semana va con qué actividad en el README del repositorio de contenidos.

Saludos :D
