### ISSUE TITLE
largo de carga de datos

### ISSUE THREAD

**Issue by IsidoraCarmona** [IIC2233/Syllabus#326]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, una consulta, cuando abro un archivo y hago una lista con cada linea del archivo, luego trato de imprimir cada elemento de la lista pero no me imprime todos los elementos del archivo, me imprime aproximadamente los ultimos 500, ¿Eso es normal o significa que no se me esta cargando de forma correcta el archivo?

**Comment by tcapom** [comment]
Hola @IsidoraCarmona !

Sin saber mayor información, es muy probable que sea una limitación de la consola y que la cantidad de impresiones simplemente sea porque no caben. 

Se me ocurre que para cualquiera de los tests que tengan más filas que la cantidad de líneas que puedas ver imprimirse, plantea algún `for` o contador para visualizar un rango de datos específico (por ejemplo, las primeras 500 líneas de un archivo). Si es que sí se pueden ver, entonces sí sería una limitancia de la consola que no debería producirte problemas en la carga del archivo
