### ISSUE TITLE
duda sobre la potencia del cilantrillo y la potencia del solaretillo padre.

### ISSUE THREAD

**Issue by danielnavarroa** [IIC2233/Syllabus#327]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holaa, estuve revisando las issues y encontré algunas similares, pero ninguna exactamente igual.
Se menciona que la potencia del cilantrillo debe ser mayor que la potencia de su solaretillo padre en cierto porcentaje. Pero, ¿qué sucede cuando el cilantrillo viene directamente en el tablero del jardín que entrega el archivo jardines.txt? Ahí no conozco la potencia del solaretillo padre, ya que este valor es aleatorio entre ciertos márgenes. **¿Debo considerar que todos los solaretillos tendrán el mismo valor de potencia (definido de manera aleatoria previamente)?**

**Comment by CrisDonosoMaass** [comment]
Hola! Dado que no se especifica ese caso en el enunciado, puedes elegir la opción que consideres que es mejor. Sólo recuerda ponerlo en el readme para hacer explicitar tu solución.
