### ISSUE TITLE
Pies Grandes

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#327]
Hola, en el enunciado sale que para que alguien sea de ascendencia africana necesita tener pies grandes, pero no encuentro la definicion de pies grandes. 
Pies grandes es entonces que más de 50% de los pies sean GTA ? Es decir todas las tallas mayores a 41 ? 

Gracias

**Comment by TomasSalvadores** [comment]
En efecto no se especifica en el enunciado. En breve se subirá una nueva versión que corregirá este error y los demás. Pies grandes se considera como talla >= 44.
Saludos!

**Comment by fgbruna** [comment]
@TomasSalvadores  Van a alcanzar a subir la nueva versión hoy :sweat_smile: ?

**Comment by Kitaps** [comment]
gracias
