### ISSUE TITLE
Duda sobre parametros permitidos

### ISSUE THREAD

**Issue by FVivess** [IIC2233/syllabus#327]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola he leído otros issues acerca de parámetros pero no me queda claro si al momento de evaluar nuestro código, debemos estar preparados para que se ingrese y se trabaje con cualquier tipo de parámetros (por ejemplo, en probabilidades, ingresar un int), o si es suficiente que definamos que el código funcione de una forma (por ejemplo, solo admitiendo float), y que le indique al usuario que los parámetros son inadecuados (por ejemplo, levantando distintos tipos de errores si se ingresa un int).

En otras palabras, **si levantamos errores cuando los parámetros no funcionan con nuestro código, ¿se considera que el código está "mal hecho" al no trabajar con esos parametros?**

**Comment by Emiliax16** [comment]
Hola @FVivess ! al evaluar tu tarea, podemos cambiar los valores de los parámetros dentro de un margen que nosotros conozcamos que debería seguir funcionando, es decir, si un parámetro funciona bien entre 0.1 y 0.8, ten por seguro que no lo cambiaremos por un 50. Respecto al tipo de parámetro, no cambiaremos el formato en que vienen (ej. entregar algo como string si el enunciado especifica que es un int), aunque si tienes tiempo, siempre es una buena práctica estar preparada para cualquier tipo de cambio en los parámetros!!

Espero que haya quedado más claro!

**Comment by FVivess** [comment]
Perfecto. Muchas gracias!
