### ISSUE TITLE
Duda Threads Problema 5

### ISSUE THREAD

**Issue by Zapararte** [IIC2233/syllabus#327]
Hola! Tengo problemas para resolver el problema 5 de los ejercicios propuestos de Threads. Dado que solo se trabaja con una "señal" (evento_nivel_terminado), no puedo especificar un orden entre los niveles... ¿de qué forma se puede solucionar esto? Gracias de antemano :)

**Comment by StroveLight** [comment]
```python
def jugar_nivel(nivel, evento_nivel):
    ##### SOLO AGREGAR CÓDIGO EN ESTA FUNCIÓN
    
    print(f"¡Jugando nivel {nivel}!")
    time.sleep(1)
    print(f"Batallando en el nivel {nivel}")
    time.sleep(3)
    print(f"Terminando el nivel {nivel}")
    
    
evento_nivel_terminado = threading.Event()

n1 = threading.Thread(target=jugar_nivel, args=[1, evento_nivel_terminado])
n2 = threading.Thread(target=jugar_nivel, args=[2, evento_nivel_terminado])
n3 = threading.Thread(target=jugar_nivel, args=[3, evento_nivel_terminado])
n4 = threading.Thread(target=jugar_nivel, args=[4, evento_nivel_terminado])

# =========== SOLO AGREGAR CÓDIGO DESDE AQUÍ HACIA ABAJO =============

n1.start()

n2.start()

n3.start()

n4.start()
```

Me siento un poco culpable si te soplo lo que a mí me resultó, así que iré de a poco

<details><summary>pista 1</summary>
Puedes aprovechar de que puedes editar el código entre los inicios de cada thread
[Refiriéndome a la parte de n1.start(), n2.start(), ...]
</details>

<details><summary>pista 2</summary>
Puedes aprovechar de que cada programa de python ya es de por sí un thread (el thread principal)
</details>

<details><summary>pista 3</summary>
ya que es un thread, puedes hacer que espere en cierto lugar a que ocurra algo
</details>

<details><summary>pista 4</summary>
No necesitas ningún otro evento, y solo te basta con el set, clear y wait
</details>

<details><summary>Solución (Usar con precaución)</summary>
<p>

```python
def jugar_nivel(nivel, evento_nivel):
    ##### SOLO AGREGAR CÓDIGO EN ESTA FUNCIÓN
    print(f"¡Jugando nivel {nivel}!")
    time.sleep(1)
    print(f"Batallando en el nivel {nivel}")
    time.sleep(3)
    print(f"Terminando el nivel {nivel}")
    evento_nivel.set()


evento_nivel_terminado = threading.Event()

n1 = threading.Thread(target=jugar_nivel, args=[1, evento_nivel_terminado])
n2 = threading.Thread(target=jugar_nivel, args=[2, evento_nivel_terminado])
n3 = threading.Thread(target=jugar_nivel, args=[3, evento_nivel_terminado])
n4 = threading.Thread(target=jugar_nivel, args=[4, evento_nivel_terminado])

# =========== SOLO AGREGAR CÓDIGO DESDE AQUÍ HACIA ABAJO =============
evento_nivel_terminado.set()
n1.start()
evento_nivel_terminado.clear()

evento_nivel_terminado.wait()
n2.start()
evento_nivel_terminado.clear()

evento_nivel_terminado.wait()
n3.start()
evento_nivel_terminado.clear()

evento_nivel_terminado.wait()
n4.start()
```

</p>
</details>

**Comment by Zapararte** [comment]
Efectivamente, no se me ocurrió utilizar el programa principal como un thread y por eso terminé complicándome intentando definir dentro de la primera función las pausas y el orden... ¡Gracias por la respuesta y por presentarla gradualmente! Hizo que le diera otra vuelta al problema. Saludos!

PD: ¿Tengo que cerrar la issue ahora o la dejo abierta?

**Comment by StroveLight** [comment]
De nada ('◇')ゞ

PD: No es necesario cerrarla, el alto mando se encarga de ver cuando se cierran las issues
