### ISSUE TITLE
¿Cuando una criatura escapa deja de pertenecer al magizoólogo?

### ISSUE THREAD

**Issue by nachobascar** [IIC2233/syllabus#327]
Cuando una criatura se escapó, esta deja de pertenecer al magizoologo hasta que la recupere?
Habría que ponerla en el menu de mostrar estado del magizoologo?
Y perdería vida por hambre o enfermedad mientras está escapada?

**Comment by aljara97** [comment]
Hola @nachobascar! 

- Cuando una criatura escapa, esta sigue perteneciendo al magizoólogo. Debes preocuparte de interactuar con ella de forma adecuada según el flujo del programa. Por tanto, debes mostrarla en el estado del magizoólogo, ya que sigue siendo de su propiedad y las acciones que este haga influyen en ella.

- El enunciado especifica que debes tener en cuenta que las probabilidades de que una DCCriatura enferme o escape son independientes, por tanto, una criatura puede escapar y estar enferma a la vez, por tanto, una criatura aún no recuperada podrá estar enfermarse o viceversa. Incluso ambos eventos podrían ocurrir al mismo tiempo. Te recomiendo también ver la issue #273 en donde se menciona cómo se emplea la alimentación de una criatura cuando escapa.

Éxito 🧙

**Comment by nachobascar** [comment]
Entonces las habilidades de las criaturas al comenzar el día, como la que los Augurey buscar alimentos para el magizoologo, siguen activas?

**Comment by dlmed** [comment]
+1 a lo de arriba

**Comment by aljara97** [comment]
Exacto, es un supuesto válido que el Augurey al no estar en cautiverio podría traer un alimento de regalo al magizoologo si es que cumple con las condiciones necesarias: **no tener hambre, tener todos los puntos de salud y no estar enfermo**.

Recuerden agregar este supuesto a su `README` y citar esta issue 🧙‍♂️

**Comment by aljara97** [comment]
@nachobascar por favor no cierres esta issue, puede ser de utilidad para alguien más. Nosotros como equipo docente lo haremos cuando sea correspondiente. 

Saludos 👨🏻‍💻
