### ISSUE TITLE
Duda acerca de forma que correrán archivos de servidor y cliente

### ISSUE THREAD

**Issue by BenjaCarrill0** [IIC2233/Syllabus#327]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Una pregunta, se puede asumir que tanto el cliente como el servidor correrán en el mismo computador? Es que como tanto el servidor como el cliente deben poseer un archivo .json que contenga la dirección ip del servidor no se si la forma que estoy pensando para tener eso estará acorde con la forma que se evaluará finalmente.

**Comment by Hernan4444** [comment]
Hola @BenjaCarrill0 

No necesariamente se van a correr en el mismo computador, pero esa parte no te preocupes, en el json puedes dejar "localhost" que es la forma que hemos hecho el seteo de dirección ip en los contenidos o experiencia 4. Si es que el ayudante decide correr en 2 pc, él mismo editará el archivo JSON para indicar la IP de su computador. Lo importante es que ese archivo exista (tanto en el servidor como en el cliente) para que pueda ser editado cuando corresponda.

¡Mucho éxito en la tarea!
Saludos!

**Comment by BenjaCarrill0** [comment]
Muchas gracias!
