### ISSUE TITLE
Tuplas por comprensión

### ISSUE THREAD

**Issue by CatalinaBO** [IIC2233/Syllabus#327]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, se puede crear una lista de duplas por comprensión? Me entra la duda ya que al usar [ ( .., ..) for elemento in iterable] se puede interpretar como tuple()

**Comment by jisalasc** [comment]
y por ejemplo, hacer una lista tipo, lista =[elemento for elemento in generador] es valido?

**Comment by tcapom** [comment]
Hola @jisalasc !

Este caso sí es válido, pues solo usas compresión

**Comment by IsidoraCarmona** [comment]
y como se puede crea una tupla por compresion sin usar tuple()? que se me forma un generador si trato de hacer (x for x in y), pero si hago tuple (x for x in y) ahi si me funciona.

**Comment by tcapom** [comment]
Hola @IsidoraCarmona !

Si revisas la issue de librerías permitidas y prohibidas, hay muchas librerías que están permitidas para poder ocuparse. Revisar la documentación de estas puede darte una posible solución.

Con intención de ayudarte y sin intención de darte la respuesta, recomiendo revisar la documentación de `itertools`:
https://docs.python.org/3/library/itertools.html

**Comment by emivenezian** [comment]
se puede usar entonces combinations que sale en esa documentacion?
