### ISSUE TITLE
error al heredar de Qthread

### ISSUE THREAD

**Issue by snarriagada** [IIC2233/syllabus#327]
no se por que al hacer start() de una clase que hereda de Qthread y Qobject lanza el siguiente error:
TypeError: start(self, priority: QThread.Priority = QThread.InheritPriority): first argument of unbound method must have type 'QThread'

el metodo run no recibe argumentos, solo self
puede ser problema en init de la clase? he probado de varias maneras

**Comment by Hernan4444** [comment]
Hola

Esta issue #246 responde la duda, de forma sencilla, no heredar de Qthread y Qobject al mismo tiempo. Cualquier duda, realiza un comentario en dicha issue para mantener el mismo tema en solo 1 issue.

Saludos :v:
