### ISSUE TITLE
Duda sobre los Generadores pedidos.

### ISSUE THREAD

**Issue by mpuntous** [IIC2233/Syllabus#328]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
![generadores](https://github.com/IIC2233/Syllabus/assets/130417431/aeb17ee8-8cb6-4588-862f-625fec9726fd)
En ambas funciones nos piden que retornemos un generador, sin embargo en ciudades_distritos se permiten varios tipos de return 
![image](https://github.com/IIC2233/Syllabus/assets/130417431/9b43a676-14eb-424c-9385-ebcfa4ef2068)
pero en especies_postulantes solo tenemos tipo generador
![image](https://github.com/IIC2233/Syllabus/assets/130417431/e0622098-8e52-4a9a-8d52-35bab41eabef)
.
Quería saber a que se debe eso.
Muchas Gracias

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by cataruze** [comment]
holaa, yo también tengo una duda similar, ya que normalmente retorno map() (que igualmente retorna un generador), pero en algunas funciones me dice que esta mal, y con esto retorno un generador por compresión. Se recomienda siempre retornarlo de la ultima forma, o ir viendo que acepta cada test case?.
Muchas gracias de antemano.

**Comment by tcapom** [comment]
Hola @mpuntous!

Para cualquier consulta que pida en el enunciado retornar un generador, es porque es posible crear un generador con los datos disponibles. Para algunos casos, los ejercicios son más laxos y se te permite devolver otro tipo de dato (como una lista debidamente hecha por compresión), pero la idea es que se retorne un generador.

**Comment by tcapom** [comment]
Hola @cataruze !

Hablando estrictamente, aunque `map()` sea en la práctica un generador, para Python, se trata de un objeto de tipo `map` y no `Generator`. Si ves en los testcases de que exige que el resultado retornado sea `Generator`, entonces tendrás que hacer la conversión correspondiente.

**Comment by leonidasmontes** [comment]
Hola @tcapom !

Te quería preguntar sobre lo de retornar un Generador. ¿Hay alguna diferencia entre usar yield para retornar cada item del generador y retornar el generador entero? Voy a dar dos ejemplos básicos que según lo que entiendo de generadores son lo mismo. Osea usar yield hace que la funcion sea un generador y de la otra forma estamos retornando un generador. Me imagino que es igual de correcto pero queria confirmarlo.

Es decir, es igual de correcto un 
for i in generador:
  yield i

a

return (i for i in generador)

**Comment by tcapom** [comment]
Hola @leonidasmontes !

A un nivel técnico, el primer código que mencionaste es una función que retorna un generator expression, mientras la segunda es una función generadora

Igualmente para el alcance de la tarea, ambos resultados son simplemente de tipo generador y tendrían la misma información
