### ISSUE TITLE
Duda tildes en codigo

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#328]
Hola, tenía una duda general respecto a buenas/malas practicas que he tenido hace tiempo.

Por ejemplo en la taréa hay funciones como    índice_de_tamaño(persona)

Entiendo que sea una tarea y que por lo tanto esté bien, pero en la vida real se usan caracteres especiales como tildes ñes y ßes ?  
Y que se hace para evitar su uso?

Gracias

**Comment by Arcoirisky** [comment]
Hola! 
Se supone que lo correcto es programar en ingles, como un lenguaje universal. De todas formas, te invito a ver bien las reglas del PEP-8, que son como "las leyes supremas" http://recursospython.com/pep8es.pdf <--
Pero en principio, cómo se dice en la parte de **codificación**, se debería de usar __siempre__ la codificación ASCII o Latin-1 (aunque para python 3 en adelante se prefiera el UTF-8 al Latin-1). 

_todos los identificadores en la librería estándar de Python DEBEN usar caracteres correspondientes
a la coficiación ASCII, y DEBERÍAN usar palabras en Inglés siempre que sea posible_

Conclusión: ASCII y PEP8 son la ley :D

**Comment by nebil** [comment]
En la vida real, es muy probable que debas escribir tu código (a excepción de los _strings_, quizá) en inglés. Esto es independiente del lenguaje de programación que utilices, dado que el inglés —lo quieras o no— **es la [_lingua franca_](https://en.wikipedia.org/wiki/Lingua_franca) del desarrollo de software**. De todas formas, en el mundo surrealista de IIC2233, no hay problema con que escribas tus variables en español. :wink:

¿Y por qué ocurre esto? Esto sucede ya que escribir el código en inglés cuenta con múltiples ventajas. Veamos una de ellas, con un ejemplo.

Este _snippet_ de código…
```python
if student not in group:
    pass
```
suena mejor que…
```python
if estudiante not in grupo:
    pass
```
…ya que estamos aprovechando el hecho de que los _keywords_ de Python están en inglés, que es algo que ocurre en ([casi](https://qriollo.github.io)) todos los lenguajes de programación. Esto permite, entonces, que la lectura del código sea más natural. :relieved:

Otro beneficio directo es que aporta **simplicidad**, puesto que en la disciplina de la _ingeniería de software_ —y en muchísimas otras áreas más—, el inglés es finalmente un [estándar _de facto_](https://es.wikipedia.org/wiki/Estándar_de_facto). Luego, basta con aprender esta única lengua, y no [quince](https://imgs.xkcd.com/comics/standards.png) otras más. Además, esto se extiende también, por ejemplo, a los mensajes de los [_commits_](https://gist.github.com/nebil/f96a2f0bfe1e059d589d6a2190a2ac81). _&lt;/camouflaged self-promotion&gt;_

Como anécdota[\*](#note), cuando hice el curso de _Introducción a la programación_ en esta universidad (eso ocurrió hace algunos años atrás, y el curso se dictaba en [Java](https://es.wikipedia.org/wiki/Java_(lenguaje_de_programación))), tenía la misma pregunta que tú. Y para mí el curso era, efectivamente, una introducción a la programación, porque era la primera vez que incursionaba en aquellos temas. Ahora, como recién estaba empezando en eso, me negaba a escribir las variables en inglés, debido a que no quería claudicar ante las garras del [imperialismo anglosajón](https://www.youtube.com/watch?v=oED3w_1CZyQ). O algo similar a eso, pensaba en aquel entonces. El problema estaba en que aquella versión de Java no permitía —a diferencia de Python— escribir variables con caracteres que no estuviesen en el [ASCII](https://es.wikipedia.org/wiki/ASCII). Entonces, para no ceder en mi gesta heroica de mantener encendida la llama del castellano, estaba obligado a buscar sinónimos para cada palabra que contuviese o una tilde, o una eñe, o una [diéresis](https://es.wikipedia.org/wiki/Diéresis). Para mi suerte, en los enunciados nunca aparecieron :penguin::penguin:.

Finalmente, para cerrar esta breve novela, te dejo un [artículo](https://blog.codinghorror.com/the-ugly-american-programmer/) (en inglés, obviamente) que habla sobre varios puntos que me hacen sentido, relacionado a lo que he escrito en estos párrafos.

**tl;dr**
En la vida real, como mencionó @Arcoirisky, es altamente probable que tengas que escribir en inglés. En tu código, si es que no estás escribiendo un _string_, no debería aparecer ni una eñe, ni un _Eszett_.

---

<a name='note'>\*</a> Generalmente, las anécdotas deberían ser divertidas. Y esta, probablemente, no lo es.

**Comment by Kitaps** [comment]
Graicas, resolvieron mi duda que traía conmigo desde intro
