### ISSUE TITLE
Duda sobre metodo Presentarse

### ISSUE THREAD

**Issue by JosefaATP** [IIC2233/Syllabus#328]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola!
En las instrucciones del método presentarse de la clase jardín dice que se **debe** sobreescribir. Mi pregunta es se considera la sobreescritura si la clase jardín (no hereda de nadie), o sea que hereda de objeto?

Saludos!

**Comment by augustayanez** [comment]
Para el método Presentarse se señala en el enunciado que debes sobreescribir el método __str__ de la clase, que es el que se ejecuta al hacer print de un objeto (que por defecto va a imprimir algo como <__main__.Jardin object at 0x03E99C90>). Con sobreescribir el método lo que se quiere decir es que en tu código definas el método __str__ dentro de la clase con los requerimientos pedidos, y al hacer esto estarías redefiniendo su función.

**Comment by JosefaATP** [comment]
Ah, entiendo.
Muchas gracias!
