### ISSUE TITLE
Uso de backgrounds (index1, 2 o 3)

### ISSUE THREAD

**Issue by CrisDonosoMaass** [IIC2233/Syllabus#328]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, al momento de crear las ventanas hay algún background específico para cada una o es de libre elección? Muchas garcias!

**Comment by mtaguero** [comment]
¡Hola!

El enunciado no especifica que debas tener algún fondo en particular. De esta forma puedes escoger cualquiera de los fondos disponibles en los archivos subidos para las ventanas.

De todas maneras, cuando se pide el ingreso es deseable que el fondo sea desde fuera del dōjō, mientras que cuando se está en la ventana de juego debería ser dentro de este (pueden guiarse por el enunciado en la sección de interfaz gráfica).

En cuanto a las variaciones de estos escenarios, siéntanse libres de ocupar el que deseen.
