### ISSUE TITLE
avance T01

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#328]
Hola. Quería saber qué es lo que se espera a entregar en el avance de mañana?
Sé que debemos subir un archivo donde salga un diagrama de clases para la entidades, pero que tan completo debe estar éste?
Y además debemos también subir el código de avance donde salen los módulos que representaran al diagrama?
Yo por ejemplo, hice el código de los módulos, pero no sé si tenga bien claro y definido el tema de las herencia, composición o agregación que tengan éstos para mañana en la entrega..

**Comment by mpsubiabre** [comment]
Hola @Camila-sty !

Para el avance se espera que entregues tu diagrama de clases lo más completo posible. Como bien se indicó en la issue #295, el objetivo del avance de la tarea es poder entregarte un feedback de como piensas modelar tu programa. Solo se pide el diagrama, sin embargo, el que subas tu código puede permitir que entendamos mejor tu diagrama y detectar errores en caso de que hubiera.
