### ISSUE TITLE
¿Un diccionario de parametros es un parametro?

### ISSUE THREAD

**Issue by juanesjeep** [IIC2233/syllabus#328]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### ¿Un diccionario de parametros es un parametro VALIDO?
en el enunciado dan un ejemplo con una multiplicacion, me preguntava si se puede extender a los built_ins mientras estos esten conformados por otros parametro.

Ejemplo:
**LLAVE_JUANITO = 'Juanito'**
**LLAVE_PABLITO = 'Pablito'**

**ALTURA_JUANITO = 1.75**
**ALTURA_PABLITO = 1.7**

**DICT_ALTURAS = {LLAVE_JUANITO: ALTURA_JUANITO, LLAVE_PABLITO: ALTURA_PABLITO}**

**Comment by tqmbanados** [comment]
Hola! Es válido lo que colocas, sin embargo no dejaría la llave como parámetro. Es más, si los parámetros de arriba no los usarás individualmente, podrías definir el diccionario reemplazando los valores así tal cual. En tareas futuras, será práctica común definir los parámetros dentro de diccionarios. Por ejemplo, supongamos un programa que simula distintos autos. Tendría sentido, que cada "modelo" de auto esté en los parámetros como un diccionario separado:
```json
MODELO_AUTO_X = {"MARCA": "Subaru", "TAMAÑO": 10, "ACELERACION": 15}  
```
*(Es un ejemplo, no se nada de autos jajaja)*
Espero que se te aclare un poco!

**Comment by juanesjeep** [comment]
gracias
