### ISSUE TITLE
Errror de instalacion PyQt5

### ISSUE THREAD

**Issue by jac-34** [IIC2233/syllabus#328]
Hola, 
Al ejecutar el comando "pip install pyqt5" en python me arroja error. Dice "invalid syntax" seleccionando la palabra "install".
![image](https://user-images.githubusercontent.com/53883804/65521351-784ddf80-debf-11e9-875a-f018754b9245.png)
Muchas gracias

**Comment by mjvarela** [comment]
Hola! El comando lo debes correr desde la terminal de tu computador (símbolo del sistema en windows), no desde IDLE 😉
