### ISSUE TITLE
[T02] Mapa se ve "separado" entre imagenes :c

### ISSUE THREAD

**Issue by Juaco97** [IIC2233/syllabus#328]
Hola! Estoy creando el mapa en base al uso de HBox y VBox, y para simplificarlo probé con solo 4 imagenes para el borde, el camino, el espacio libre y la base. El problema es que entre una imagen y otra queda un espacio de separación que hace que el mapa no se vea como continuo. Lo estoy haciendo iterativamente. ¿Alguien sabe cómo solucionarlo? (probé también usando el método de grilla y ubicando las imagenes en posiciones de acuerdo a cómo iba leyendo el mapa que se daba, y me arrojaba el mismo error) 

Aquí va la imagen de cómo se ve el mapa:

![Captura de Pantalla 2019-05-21 a la(s) 02 57 56](https://user-images.githubusercontent.com/37164418/58075352-7ffa2200-7b75-11e9-915b-dd84ec810a22.png)

Gracias!

**Comment by MartinAracena** [comment]
Podria ser que con setSpacing(0) te funcione. Eso le quita los espacios entremedio a los layouts al parecer.

**Comment by jmwielandt** [comment]
@jaromero6 es lo que comenta tu compañero. Se trató un poco en la issue #204
