### ISSUE TITLE
Valor de energia Magizoólogos

### ISSUE THREAD

**Issue by amparostevens** [IIC2233/syllabus#329]
Hola! No me quedó muy claro cómo funcionan algunos atributos. Se supone que los rangos de valores que nos entregan son para que tome ese valor inicialmente y que luego, en los atributos que corresponda, se cambie ese valor? 
Por ejemplo con nivel de energía de **Docencio**, inicialmente toma valores entre 40-50 y eventualmente podría ser 0? En ese caso qué pasaría? Muere el mago o se acaba el juego?

**Comment by mpsubiabre** [comment]
Hola @amparostevens!

Muy bien como mencionas en tu ejemplo, inicialmente tomara algún valor aleatorio entre esos rangos y luego, a medida que se desarrolla tu programa. se cambiaran los valores de dicho atributos según corresponda (recordando los limites de dichos atributos 😉 ).
En particular, la energía  ayuda a limitar la cantidad de acciones que puede hacer el Magizoólogo en un día. Por esto, si llega a cero esta obligado a pasar de día para poder recuperarla y así poder hacer alguna acción.
