### ISSUE TITLE
Problema al buscar designer

### ISSUE THREAD

**Issue by mrrebolledo** [IIC2233/syllabus#329]
Hola! Pude instalar PyQt5 pero no encuentro Designer en mi computador cuando lo pongo en buscar y tampoco esta en la dirección que pusieron, aunque todo lo demas sí.
Esta es la dirección:
C:\Users\usuario\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\pyqt5_tools

![Captura](https://user-images.githubusercontent.com/53914076/65537203-2b780200-dedb-11e9-979c-8debb453f97a.PNG)

Si pongo designer.exe en el símbolo del sistema me sale que no se reconoce como comando interno o externo.

**Comment by StroveLight** [comment]
Hola! No hay nada raro de que no aparezca designer allí (lo acabo de probar yo mismo recién)

Ceroabo:
A punto de mandar esto, ví que usar el designer.exe es sólo para powershell, así que creo que con solo la primera parte te bastará (lo acabo de probar)

Primero: Probaste escribiendo en la cmd lo siguiente?:
```powershell
Designer
```

Segundo:
Si lo anterior no te funciona, podrías buscar el archivo en 
```C:\Users\usuario\AppData\Local\Programs\Python\Python37\Scripts\designer.exe```
(tal vez Python37 te aparezca como Python37-32)

Tercero:
Si lo anterior aún no te funciona, podrías intentar abrir la cmd o powershell (cualquiera sirve) como administrador e intentar denuevo la descarga

PD: Espero que esto te ayude

**Comment by mrrebolledo** [comment]
Lo encontré en Scripts! Muchas gracias!!

**Comment by StroveLight** [comment]
De nada (≧∇≦)b
