### ISSUE TITLE
TIEMPO_ATAQUE_TORRE

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#329]
Hola, no me queda muy claro la utilidad de este parámetro, me imagino que es solo para efectoss visuales, ya que las torres atacan cuando hay enemigos en el rango (y supongo que no paran hasta que ya no hayan).

**Comment by gatochico** [comment]
Hola! Efectivamente, es para fines visuales. Cuando una torre ataca, debe aparecer sobre ella una etiqueta que indique que está atacando. TIEMPO_ATAQUE_TORRE indica el tiempo que esta etiqueta debe permanecer sobre la torre.

**Comment by quememo** [comment]
esta etiqueta debe aparecer _**cada vez**_ que la torre ataque? En otras palabras si la torre atacó 5 veces, debe aparecer 5 veces la etiqueta que dice que atacó?

**Comment by gatochico** [comment]
Tecnicamente, sí. Si es que estás pensando en los casos límites con tu pregunta (por ejemplo, un caso donde la frecuencia de ataque es mayor al TIEMPO_ATAQUE_TORRE, y entonces, la torre efectuó otro ataque nuevo antes de que la primera label desapareciera), puedes manejarlos a tu discreción (como haciendo que las labels se vayan apilando una sobre otras, o editando la label para tener un contador de ataques ), siempre y cuando expliques tu decisión en el README!

**Comment by quememo** [comment]
muchas gracias! me agrada la idea de simplemente hacer que se vayan apilando uno encima de otro jajaja
