### ISSUE TITLE
DECODIFICACION LATIN1

### ISSUE THREAD

**Issue by Chiseth** [IIC2233/Syllabus#329]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Desde ayer que llevo intentando codificar el codigo por latin-1 y no logro hacerlo funcionar, he visto y leido muchas cosas por iternet y aún así no funciona, solo me salen cosas como ÃÂ¯ÃÂ¿ÃÂ½guila,TarÃÂ¯ÃÂ¿ÃÂ½ntula, HÃÂ¯ÃÂ¿ÃÂ½rcules. No sé como hacer que realmente remplace esa decodificacion, ya que si solo agrego errors='replace' sigue saliendo lo mismo

**Comment by ClemoAcevedo** [comment]
Hola @Chiseth , puedes hacer push a tu repositorio para probarlo?

**Comment by Chiseth** [comment]
ahí pushee ;c

**Comment by ClemoAcevedo** [comment]
@Chiseth probé tu código con el test case base de cargar datos y en un comienzo me tiraba problemas de que no encontraba los archivos `csv`, modifique un poco la ruta y en la forma en que la insertas y me imprimió todo bien, incluso quitándole `replace`. Por lo que te recomendaría dos cosas: 1. No utilices `replace` (solo `encoding='latin-1'`) ya que podría tener incongruencias con los test cases, es mejor que ocurra el problema y resolverlo en vez de "reemplazarlo". 2. Analiza y modifica la forma en la que estás manejando la ruta de los archivos.

Si después de probar con estas opciones sigue sin funcionarte, explícame como estás corriendo el test case para entender mejor.

**Comment by Chiseth** [comment]
Me sigue sin funcionar, incluso para evvitar errores de ruta lo hice con os.path.join() y sigue sin funcionar, ni en la consola ni en el test.
Para probar este test simplemete cree una copia en donde se encuentra el .py de consultas para poder correrlo de forma más sencilla por vscode

**Comment by ClemoAcevedo** [comment]
@Chiseth si lo corres por consola igual te imprime mal? Puede ser una configuración errónea de VS Code

**Comment by Chiseth** [comment]
si, me printea igual q en vscode :(
![image](https://github.com/IIC2233/Syllabus/assets/156480987/2a782990-188e-4bd2-abbb-e5e291c87cd2)

**Comment by ClemoAcevedo** [comment]
@Chiseth solo para comprobar una cosita, si corres el test base de cargar datos por consola, con la implementación que habías pusheado, también se te imprimen mal?

**Comment by Chiseth** [comment]
si, tambien me imprimia mal :c, lo que si es que a mi nunca me dio problema para encontrar el archivo

**Comment by ClemoAcevedo** [comment]
@Chiseth desde un comienzo probaste con latin-1 o también te ocurría con utf-8?

**Comment by Chiseth** [comment]
He probado con utf-8 pero tampoco nunca me codifico bien por mas q usara utf8 replace o algun otro tipo de remplazo de errores

**Comment by Chiseth** [comment]
Creo que halle la forma de que me decodificara, pero debo importar csv, puedo escribir from csv import reader?:c no sale en las librerias permitidas como tal :c

**Comment by Chiseth** [comment]
Creo que el error lo tiene el archivo que quiero leer, y es que en el enunciado dice que se debe leer la carpeta data que está dentro de test_publicos y esta es la que no logro decodificar, en cambio si la ruta es solo de la carpeta data, la que no esta dentro de los test si me deja decodificarla, será algun error del enunciado? ya que los contenidos de las carpetas son distintos tipo una tiene los simbolos que no logro decodificar (parte izquierda de la foto) y la otra son rombos que si puedo decodificar con latin-1 ( parte derecha de la foto)
![image](https://github.com/IIC2233/Syllabus/assets/156480987/7b0b7a9d-612e-407b-b3bd-68eba13c9ba2)

**Comment by ClemoAcevedo** [comment]
@Chiseth si eliminas la carpeta de `data` y de `tests_publicos` y las vuelves a descargar del Syllabus, te sigue ocurriendo?

**Comment by Chiseth** [comment]
Acabo de hacer eso y ahora si funciona ToT creo que en algun momento se cambiaron mis cosas de la cargpeta test_publicos, como la decodificacion, ahora me decodifica bien TuT gracias

**Comment by ClemoAcevedo** [comment]
Que bueno! Buena suerte
