### ISSUE TITLE
Archivo .gitignore

### ISSUE THREAD

**Issue by danvillablanca** [IIC2233/syllabus#329]
Hola, mi duda es si en el archivo .gitignore se pueden ignorar también los archivos Enunciado.pdf y parametros.py, además de los indicados en el enunciado.

**Comment by josefinareyes** [comment]
Hola! Deberías incluir cualquier archivo que se te entregue y que **no modifiques** en tu `.gitignore` ya que todos podemos acceder a estos archivos a través del Syllabus, eso incluye el enunciado, pero si tienes que crear o modificar el archivo `parametros.py`, debes subirlo a tu repositorio!

**Comment by danvillablanca** [comment]
Gracias!
