### ISSUE TITLE
Duda sobre simbolos en Filtrar

### ISSUE THREAD

**Issue by Minjor** [IIC2233/Syllabus#329]
Cómo puedo transformar un string de ["==","<",">",">=","<=","!="] en un operador?
Podría hacer un if para cada símbolo pero me gustaría lograrlo en una linea. Gracias!

**Comment by rpalmaotero** [comment]
Lograrlo en una línea es posible pero es muy probable que haga tu código menos leíble. Personalmente lo haría con un diccionario emulando un `switch` (http://stackoverflow.com/a/103081/389112).

**Comment by consuvalencia** [comment]
Pero hacerlo con un if no caería dentro de las 'cosas prohibidas'? o no se considera parte de las funcionalidades?
