### ISSUE TITLE
Duda efecto_especial de los tripulantes

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#329]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### El efecto de los tripulantes debe ser implementado con un metodo?
En el avance de la tarea me dijeron que se debia poseer un metodo del efecto_especial de los tripulantes, pero difiero, ya que en el enunciado solo dicen de que el efecto se aplica automaticamente al ya estar en el barco y nunca menciona que deban tener un metodo.

**Comment by Emiliax16** [comment]
Dado que **Tripulación** es una entidad y aunque el enunciado no lo diga explícitamente,  lo más correcto sería trabajar cada _efecto_especial_ como un método, ya que varía de acuerdo al tipo de tripulante.

**Comment by Ignacioislae** [comment]
Si, pero no tengo que hacerlo asi cierto? Porque igual podria identificar en el Barco si es que poseo el tipo X de tripulante en su tripulacion y actuar segun eso.

**Comment by vcrb18** [comment]
Confirmo lo que dice Ignacioislae

**Comment by Emiliax16** [comment]
Es una manera de hacerlo. Puedes ver cómo te acomoda más ejecutarlo mientras cumplan con lo pedido en el enunciado y no impliquen malas prácticas en el código de esa sección. Cumpliendo con eso, debería estar bueno.

**Comment by Ignacioislae** [comment]
Dalee Gracias!
