### ISSUE TITLE
Python  o reconoce archivo json

### ISSUE THREAD

**Issue by espeescobar** [IIC2233/Syllabus#329]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Problemas con archivo JSON

Cree el archivo json dentro de la carpeta del cliente para el host y el buffer, y me funcionó, pero de la nada apareció un error de que el archivo no se encuentra en el directorio pero lo tego en la misma carpeta que el archivo de python.

**Comment by AntonioVenegas** [comment]
Hola @espeescobar!, es dificil saber el error con solo la información que proporcionas, pero puede ser un error en el path del archivo json cuando intentas abrirlo con `open()`, si todavía tienes problemas con eso puedes mandar el print del error en consola, asi es más facil saber que es lo que te está fallando específicamente.

Saludos :)
