### ISSUE TITLE
Indice de tamaño

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#329]
En el enunciado dice que:

> primero deberás buscar el gen de tamaño
AGT en las caracterı́sticas donde se expresa: la altura y el tamaño de los pies

Pero los pies no usan AGT sino que GTA

A la vez en el ejemplo que da luego habla de la altura y de la guata. Guata efectivamente si usa AGT y ACT al igual que altura. 

Entonces asumo que hubo un error de tipeo y en vez de tamaño de pies se refería a tamaño de guata? 

Gracias

**Comment by TomasSalvadores** [comment]
Estás en lo cierto, es un error. El gen AGT se expresa el la altura y la guata, por lo que deben buscarlo ahi y no en los pies.
Lamentamos las molestias!
