### ISSUE TITLE
Hay que tener un volver atrás frente a cualquier input?

### ISSUE THREAD

**Issue by crow-rojas** [IIC2233/syllabus#33]
¡Hola!

Quería preguntar si es obligatorio tener la opción de volver atrás cada vez que al usuario se le pida tomar una decisión mediante un input (eligiendo baldosas, eligiendo su usuario, tamaño del tablero, etc.), ya que solo implementé la opción de volver atrás en los inputs más generales.

**Comment by KnowYourselves** [comment]
Hola @crow-rojas!

Esta duda ya fue resuelta en #16!, Recuerda buscar en las issues tu duda antes de crear una nueva. 

Éxito en lo que queda de tarea!
