### ISSUE TITLE
Problemas con instalación de PyQt5

### ISSUE THREAD

**Issue by SofiaP419** [IIC2233/syllabus#33]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema
Tengo Windows y seguí las instrucciones de la wiki para instalar PyQt5, pero cuando escribo el comando "pip install pyqt5" en git bash no pasa nada, lo intenté con pip3 y es lo mismo. Hablé con una ayudante y me dijo que lo intentara desde la terminal, pero me tira el siguiente error:  ***Fatal error in launcher: Unable to create process using*** "PATH". Al intentarlo importar desde un archivo python me dice que el módulo no existe. ¿Qué hago?

**Comment by nanglada** [comment]
Hola! Estuve buscando y encontré que el error que te sale puede suceder porque pip no está actualizado. 
Intenta correr el siguiente comando "python -m pip install -U pip" y después "pip install pyqt5" de nuevo. 
Me cuentas si te funciona.
Saludos :)

**Comment by SofiaP419** [comment]
Me sigue saliendo lo mismo :(

**Comment by nanglada** [comment]
Ya, lo otro que podría ser es que no tienes pip en el path. Anda a "ver configuraciones avanzadas de sistema", luego a "variables de entorno". Ahí seleccionas la variable "Path" para asegurarte que tengas tanto Python, como los Scripts de Python (entre ellos, pip), en el path. Debería verse así. 
![path](https://user-images.githubusercontent.com/62104901/112218855-01ec8380-8c03-11eb-914d-19b9cea6d130.PNG)
Si es que eso no te sale, es porque no tienes el path hecho y tienes que agregarlo de manera manual. 
Ojalá te sirva!

**Comment by SofiaP419** [comment]
Si tengo el pip en el path. Mi version de git es 2.26.0, de python 3.7.7 y vsc 1.54.3 ¿tendrá algo que ver con eso?

**Comment by nanglada** [comment]
No debería tener ningun problema con eso. 
¿Podrías revisar cuales son los paths de python y del script? Para comprobar eso, puede ir a los paths como lo hiciste antes o puedes escribir el comando "where python" y "where pip" en tu terminal.

Python debería estar en: \AppData\Local\Programs\Python\Python37\python.exe
pip debería estar en: \AppData\Local\Programs\Python\Python37\Scripts\pip.exe

Si esto estuviera bien, me estoy quedando un poco sin opciones sobre cual podria ser el problema ajaja
Como última opción te recomendaría que elimines tu versión y la instales nuevamente.

**Comment by SofiaP419** [comment]
Me aparecen 2 paths.
python: 
\AppData\Local\Programs\Python\Python37\python.exe
\AppData\Local\Microsoft\WindowsApps\python.exe

pip:
\AppData\Local\Programs\Python\Python37-32\Scripts\pip.exe
\AppData\Local\Programs\Python\Python37\Scripts\pip.exe

Si elimino e instalo de nuevo python ¿afecta a los otros programas que ya descargué?

**Comment by nanglada** [comment]
Veo que tus paths están bien así que parece que por ahí no está el problema. 

El siguiente paso ahora es borrar y reinstalar Python. No debería afectar a los demás programas. 
Sin embargo, si al reinstalar Python te siguiera fallando, te recomiendo que borres todo lo que ya descargaste con pip y empieces de cero con todas las instalaciones. (Ojalá esto sea un último recurso porque es súper latero).

Suerte!

**Comment by SofiaP419** [comment]
Reinstalé python y git pero me pasaba lo mismo. Luego de probar varias cosas me funcionó con el comando "python -m pip install pyqt5". Gracias por la ayuda!

**Comment by dfloreaa** [comment]
Como una pequeña acotación @SofiaP419, parece que tienes problemas al llamar a módulos de python (como lo es ``pip``, en mi pc me pasa lo mismo 😔), si quieres acceder a ellos directamente vas a tener que siempre anteponerles ``python -m`` para poder utilizarlos, ojalá te ahorre un dolor de cabeza a futuro ☺
