### ISSUE TITLE
Problema con la Importacion del Modulo Utils.pyc

### ISSUE THREAD

**Issue by JVeloz19** [IIC2233/Syllabus#33]
### Prerrequisitos
* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
No se muy bien como importar las funciones del modulo utils.pyc, lo estaba intentando importar dentro del archivo dccultivo.py para poder crear el método de detectar las plagas de la clase DCCultivo.
Para importar simplemente estaba intentando esto:  `from utils import plagas`
Sin embargo el VSCode me marca como un error esa linea y cuando intento ejecutar el archivo dccultivos.py me muestra el siguiente error: 
![imagen_2024-08-15_042406656-fotor-2024081542536](https://github.com/user-attachments/assets/cc310e2d-4dae-4b1d-a7d4-68e9df1f0a60)

**Comment by FernandoTFH** [comment]
Como dice tu terminal, cuando importas "utils" está ocurriendo una importación en círculo, dado que el archivo utils.pyc, lo más probable es que esté importando el archivo dccultivo.py. Es decir, A importa B y B importa A y se repite el ciclo. En resumen no lo hagas.

**Comment by JVeloz19** [comment]
Entonces creo que no estoy entendiendo como funciona el tema de las plagas, por lo menos yo estaba entendiendo que esa funcion me daba la información respecto a los cultivos con plagas.  Duda: ¿creo una issue nueva para preguntar eso o aqui mismo?

**Comment by FernandoTFH** [comment]
Si crea otra issue.
