### ISSUE TITLE
Problema al usar el comando git pull

### ISSUE THREAD

**Issue by oliviallanosj** [IIC2233/Syllabus#33]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

[Hola, al ejecutar el comando **git pull** para poder actualizar los contenidos o el syllabus, me tira el error: "fatal: Incapaz de leer el directorio de trabajo actual: Operation not permitted".]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by oliviallanosj** [comment]
<img width="566" alt="Captura de Pantalla 2023-08-18 a la(s) 17 45 52" src="https://github.com/IIC2233/Syllabus/assets/141787878/2fb5dacb-e503-46e3-a6e7-fbedcf8d3722">
Me sale esto al poner git pull en la carpeta "contenidos"

**Comment by Pablo-Gonzalez-Calderon** [comment]
Hola 🤧

Creo que este error está relacionado con algo que preguntaron en clase. Si no me equivoco, ocurre porque tienes cambios en tu repositorio local de "contenidos" y, a la vez, estás intentando cargar los cambios de GitHub (que difieren de tu repositorio local). Entonces Git no sabe qué hacer con los cambios locales. En el archivo [README.md](https://github.com/IIC2233/contenidos/blob/1bd8351dbbd530265e6725c15b1af24065e70e90/README.md) del repo de los contenidos sale que deberías usar
```bash
git stash
git pull
git stash pop
```
para poder conservar tus cambios a la vez que cargas los cambios del repo online.

Espero que eso solucione tu problema 😁

**Comment by oliviallanosj** [comment]
Hola, no es ese mi problema. Al ejecutar esos comandos me sale lo siguiente:
<img width="718" alt="Captura de Pantalla 2023-08-19 a la(s) 15 47 04" src="https://github.com/IIC2233/Syllabus/assets/141787878/ce7126e6-2317-4142-8164-10d660f6a069">

**Comment by Hernan4444** [comment]
Hola,

Creo que estás intentanto hacer pull de un repo pasado, porque en tu log sale algo como "semana-07" y "semana 15" y nosotros todavía no subimos eso. 

Te recomendamos mejor eliminar esa carpeta y clonar [este repo](https://github.com/IIC2233/contenidos) que es el de este semestre nuevamente.

Saludos!

**Comment by oliviallanosj** [comment]
Hice eso, eliminé la carpeta anterior y clone el repositorio actual de contenidos de este semestre y tampoco me funciona. Me sale lo siguiente: 
<img width="571" alt="Captura de Pantalla 2023-08-21 a la(s) 11 30 39" src="https://github.com/IIC2233/Syllabus/assets/141787878/08f2fb34-5895-4078-996a-aba7384c131a">

**Comment by Hernan4444** [comment]
Hola @oliviallanosj 

Parece que tu terminal no tiene los permisos para poder escribir archivos. Podrías intentar primero hacer lo indicado en [esta guía](https://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/) sobre darle permisos a tu terminal, reiniciar tu terminal y luego intentar hacer nuevamente git clone?

Quedamos atentos,
Saludos!

**Comment by oliviallanosj** [comment]
Ahí me funciono! Muchas gracias profe
