### ISSUE TITLE
Nivel de Ataque

### ISSUE THREAD

**Issue by Bipavez** [IIC2233/Syllabus#33]
En el enuciado de la tarea 1 dice que se aplica el ponderador a los soldados, ¿En este caso se refiere a las unidades del ejercito  (_soldados y magos_) o  solamente a las unidades _soldado_?

**Comment by ptflores1** [comment]
A ambos, mago y soldado. Saludos!

**Comment by DanielCarrascoFalcon** [comment]
Consulta,
Al aplicar el ponderador puedo superar el límite de ataque del soldado? 
Lo mismo al aplicar los ponderadores a las tasas de recolección...
En caso de no ser posible van a existir situaciones en que ser de nivel = 2 o nivel = 3 sería exactamente lo mismo.
Gracias!!

**Comment by Hernan4444** [comment]
Hola, el ponderador si puede permitir que el ataque o tasa supere el límite. Dicho límite solo esta al momento de generar dichos datos o cuando el usuario los modifica.
