### ISSUE TITLE
Ingresar encomienda indicar error 

### ISSUE THREAD

**Issue by jahernandez2** [IIC2233/Syllabus#33]
Hola, al ingresar los distintos input necesarios para la encomienda, primero se señala que se debe corroborar en usuarios.csv el nombre y luego que en caso de no cumplir con el formato en algún campo, arrojar el error. ¿El error puede indicarse en modo genérico luego de haber ingresado todos los datos o debe ir en específico en caso de no encontrarse el usuario inmediatamente luego de eso?

**Comment by Emiliax16** [comment]
Hola @jahernandez2, como se indica en el enunciado, cada vez que exista un error en los datos ingresados, el programa debe notificarte y preguntarse si deseas continuar (ingresar nuevamente ese valor) o cancelar la encomienda. Sin embargo, no se pide que detalles específicamente el error cometido, podríamos simplemente decir "Campo erroneo!" o "Dato ingresado incorrecto" si lo deseas. 

Lógicamente esto implica que dentro de tu código, hagas las verificaciones correspondientes en cada campo mientras se van ingresando los datos. Al ingresar el nombre de usuario, se debe verificar inmediatamente si pertenece a usuarios.csv para poder arrojar el error mencionado. Avísame cualquier otra duda! Saludos 😄

**Comment by jahernandez2** [comment]
Gracias! Saludos
