### ISSUE TITLE
Largo nombres de usuarios y parametros.py

### ISSUE THREAD

**Issue by Nicromanker** [IIC2233/Syllabus#33]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Estaba volviendo a cada uno de los individuos del csv de usuarios a una clase que cumpla con las restricciones para los nombres dadas en el enunciado cuando me di cuenta que hay 2 nombres en este archivo que no cumplen con estas condiciones. **¿Deberia contarlos como usuarios de todas formas o dejar que el programa los quite?**

**Comment by Juampisaez** [comment]
Hola @Nicromanker!
Efectivamente, existen dos usuarios en el csv que no cumplirían con los parametros de ejemplo que aparecen en el enunciado. De igual manera, los parametros se utilizan al momento de **registrar** un usuario en el programa, por lo que no debería afectar a los usuarios previamente existentes en el archivo (no te preocupes de estos). Por otro lado, al momento de ingresar al programa, basta con verificar que el usuario se encuentre en el archivo _usuarios.csv_.
Por último, cabe mencionar que los parametros puedes cambiarlos, no necesariamente deben ser los mismos del enunciado.

Espero haya quedado claro
Quedo atento de igual manera :)
