### ISSUE TITLE
Duda con opciones y opciones de menu

### ISSUE THREAD

**Issue by ggmirandac** [IIC2233/Syllabus#33]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Saludos,

Esperando que se encuentren bien, les escribo mi siguiente duda.

En el menú de inicio, los archivos que nos piden, ¿las opciones son las entregadas? No hay que generalizar para casos en los que los tableros sean, por ejemplo, 6x6.

Por otra parte, en el enunciado se nos dice que hay que cerrar el programa. ¿Esto significa que el menú se cierra y no sigue corriendo, o sea, no pedimos de nuevo que ingrese otra vez hasta que esté bueno?

Sin otro particular, me despido.

Saludos,

Gabriel

**Comment by terelopezc** [comment]
Hola! Esto se refiere a cualquier archivo que se encuentre en la carpeta.
