### ISSUE TITLE
Repo personal

### ISSUE THREAD

**Issue by Gjescalante** [IIC2233/syllabus#33]
Saludos, escribo porque no pude asistir a la primera clase ¿ya se crearon los repos personales o se hará esta semana? gracias.

**Comment by yuwet15** [comment]
En el primer anuncio hay que completar el formulario y ahi se te inscribe al repositorio, aunque nosé porque a mi aun no me llega la invitacion

**Comment by tocococa** [comment]
Hola @Gjescalante y @yuwet15 !

Como bien dijo @yuwet15 , tienes que completar el formulario en el primer anuncio, se debería crear su repositorio privado y llegar la invitación por correo. Si aún no les llega a su mail, por favor revisen si no tienen una notificación en GitHub con la invitación y si tampoco han recibido la invitación por GitHub, por favor escriban al correo del curso, <iic2233@ing.puc.cl>.
