### ISSUE TITLE
restricción de nombres de usuarios

### ISSUE THREAD

**Issue by agustin18638937** [IIC2233/syllabus#33]
piden que los usuarios registrados tengan por lo menos 8 caracteres de por lo menos una letra y un número, sin embargo en el archivo usuarios no siguen esa restricción, ¿eliminamos esas restricciones o las consideramos igual?

**Comment by DCCollao** [comment]
Hola @agustin18638937!

La issue #32 es sobre este mismo problema.
De todas formas, gracias por avisar! Si encuentras algún otro error, por favor hazlo saber!

Éxito!
