### ISSUE TITLE
¿Qué es el avance?

### ISSUE THREAD

**Issue by jearaneda** [IIC2233/syllabus#33]
La entrega de Avance de Tarea exige solamente que hagamos modelación en lucidchart? No es necesario hacer algún avance en código?

**Comment by Arcoirisky** [comment]
El avance a entregar es solo la modelación :D ¡Tómense su tiempo para hacerlo de la mejor forma posible! Les servirá para ordenar sus ideas y les será más fácil poder estructurar correctamente su código.
