### ISSUE TITLE
Duda respecto al uso de listas por comprensión y extend()

### ISSUE THREAD

**Issue by Cris871** [IIC2233/Syllabus#330]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, tengo la siguiente duda, como dice el titulo de la issue, es valido usar listas por comprensión y el método extend()? ya que en mi tarea he estado usando esto para reducir el uso de bucles for para crear/agregar elementos a listas.

**Comment by CrisDonosoMaass** [comment]
Hola! Mientras estés usando los mismos métodos de python sin agregar librerías externas no debería haber problema. Recuerda ponerlo en tu readme para que quede clara tu forma de hacerlo.

**Comment by Cris871** [comment]
ok, muchas gracias :)

> Hola! Mientras estés usando los mismos métodos de python sin agregar librerías externas no debería haber problema. Recuerda ponerlo en tu readme para que quede clara tu forma de hacerlo.
