### ISSUE TITLE
Duda notebook 3 de interfaces gráficas

### ISSUE THREAD

**Issue by crow-rojas** [IIC2233/syllabus#330]
¡Hola! Me encuentro leyendo el tercer notebook de la semana 6-7 y se me generó una duda donde se habla de señales. En esta sección del notebook, está el ejemplo:

<details><summary>Click para ver el código</summary>
<p>

```python
import sys
from PyQt5.QtCore import (QObject, pyqtSignal)
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel)


class MiSenal(QObject):
    """
    Esta clase contiene la señal que permite la comunicación entre
    elementos de la GUI.
    """
    senal = pyqtSignal()


class VentanaPresionable(QWidget):

    def __init__(self, senal_escribir):
        super().__init__()

        self.senal_escribir = senal_escribir

        self.inicializa_gui()

    def inicializa_gui(self):
        self.etiqueta = QLabel('Presiona esta ventana', self)
        self.etiqueta.move(20, 10)
        self.etiqueta.resize(self.etiqueta.sizeHint())

        self.setGeometry(300, 300, 290, 150)
        self.setWindowTitle('Emite señal')
        self.show()

    def mousePressEvent(self, event):
        # Al ejecutar la siguiente línea, se emite la señal,
        # y los métodos conectados se llamarán automáticamente.
        self.senal_escribir.emit()

class VentanaQueSeEdita(QWidget):

    def __init__(self, senal_editar):
        super().__init__()

        self.senal_editar = senal_editar
        # Conectamos el método encargado de ejecutar la tarea
        self.senal_editar.connect(self.edita_etiqueta)

        self.inicializa_gui()

    def inicializa_gui(self):

        self.etiqueta = QLabel('', self)
        self.etiqueta.move(20, 10)
        self.etiqueta.resize(self.etiqueta.sizeHint())

        self.setGeometry(700, 300, 290, 150)
        self.setWindowTitle('Recibe señal')
        self.show()

    def edita_etiqueta(self):
        self.etiqueta.setText('¡Oh! Alguien ha presionado el mouse')
        self.etiqueta.resize(self.etiqueta.sizeHint())


if __name__ == '__main__':
    app = QApplication([])
    senal = MiSenal()
    ventana_1 = VentanaPresionable(senal.senal)
    ventana_2 = VentanaQueSeEdita(senal.senal)
    sys.exit(app.exec_())
```
</p>
</details>

Luego, se dice esto (mi duda solo va al punto 2):

![Notebook 3](https://i.imgur.com/iNvz9nx.png "The Game")

Mi duda es, ¿por qué en el punto 2 se dice que se define como atributo de clase y no de instancia? ¿Si ``senal`` no tiene antes ``self`` y se guarda en una variable que contiene una instancia de ``pyqtSignal()``? Ya sé que quizá puede referirse como un *atributo de clase* porque está siendo definido dentro de una clase, pero escrito así *no* es un atributo de la clase como tal, no sé si me explico, entonces entra a confundir.

¿Está malo o no lo entendí bien? Ojalá me puedan ayudar, ¡gracias!

**Comment by javieraochoa** [comment]
Hola @crow-rojas !

Sé que puede sonar un poco confuso, pero un atributo de clase y un atributo de instancia no son lo mismo. Como bien sabes, los atributos de instancia tienen la sintaxis de `self.atributo` y se crean en el `__init__` (y entonces esos atributos van solo asociados a esa clase en específico). En cambio, los atributos de clase se crean fuera de los métodos y no necesitan tener antes el `self` cuando se crea (y queda asociado a la clase completa, no solo a la instancia).

Ojo  que luego cuando llamas ese atributo sí debes hacerlo con el `self ` antes
