### ISSUE TITLE
Manejo del DCC

### ISSUE THREAD

**Issue by AAVP** [IIC2233/syllabus#330]
En el apartado 4 del enunciado de la T01 se mencionan entidades que deben ser tratadas como objetos, pero no sé realmente si DCC también debe instanciarse o si se deben realizar tales acciones como meras funciones.

**Comment by mpsubiabre** [comment]
Hola @AAVP!

Si bien el DCC se podría realizar mediante funciones, manejarlo como entidad te sera mucho mas sencillo y ordenado. A la vez que en esta tarea queremos que aprendan y utilicen de buena manera programación orientada a objetos, por lo que debe instanciarse. Te recomiendo fijarte en la distribución de puntaje, ahi se indica que el DCC debe ser tratado como una clase :)
