### ISSUE TITLE
Duda poseer relaciones de composicion y agregacion

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#330]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Hay que poseer relaciones de composicion y agregacion en el programa
En el avance me dijeron que habia que poseer ambos tipos, pero en el enunciado, especificamente en la 3ra pagina, en la parte de entidades, primer parrafo dice: "Para modelarlas correctamente, deberás utilizar conceptos clave de programación orientada a objetos: herencia, clases abstractas, polimorfismo, propertiesy relaciones, ya sean de agregación o composición."
Lo del final me da a entender a que debe haber relaciones, pero no que tengan que existir las de ambos tipos, sino que puede ser la una, la otra o ambas juntas.

Saludos

**Comment by Emiliax16** [comment]
Hola @Ignacioislae .

Efectivamente el enunciado dice que se deben usar relaciones, sean de agregación o composición según corresponda. Esto es porque si o si debes usar las relaciones, pero saber dónde y qué tipo de relación usar es propio de tu modelación. Si en el avance dijeron que se deben poseer ambos, es porque la modelación de la propia tarea requiere que estén ambos, no porque sea obligatorio usar los dos a la vez. No sé si se entiende, quedo atenta !

**Comment by Ignacioislae** [comment]
¿Es que porque habria que habria agregacion en la Tarea? Si la mercancia y los tripulantes (para el programa) solo existiran dentro del Barco y jamas fuera. Y lo mismo con los barcos en los canales, solo existiran mientras esten en el canal y sino no existiran para el programa. 

(Agregacion seria como en el caso de los goombas que en ejemplo de los contenidos: donde estos podian existir fuera de los ejercito en el programa)

**Comment by Emiliax16** [comment]
Podrías intentar asociar la tarea a casos reales si eso te ayuda a visualizar mejor la modelación del programa. ¿Qué entidades son sólo asociaciones a clases y podría seguir existiendo en la vida cotidiana, aunque la relación con su clase agregada desapareciera? No pongo en duda que tu modelación está correcta, pero quizás se podrían hallar otro tipo de relaciones si le das otra vuelta!
Piensa que si esto se evalúa, es porque debe existir al menos una relación de agregación!!

Saludos y ánimos para el diagrama!
