### ISSUE TITLE
Diseño de modelación de menús

### ISSUE THREAD

**Issue by fran-gl** [IIC2233/syllabus#330]
Hola, quería saber si definir distintas funciones para cada menú del programa y luego dentro de la función de un menú llamar a la función de otro menú es una manera válida de modelar o si es considerado dependencia circular y por tanto una mala práctica. Muchas gracias de antemano.

**Comment by amparostevens** [comment]
Hola @fran-gl! 
Por experiencia te puedo decir que muy probablemente ese diseño de modelación te va a traer problemas en el correcto funcionamiento de tu tarea, especialmente si es que el menú que llamas dentro del otro menú va a seguir llamando más funciones. 

No necesariamente se va a crear una dependencia circular (lo cual sí es una mala práctica) pero puede que tu programa no termine haciendo lo que quieres y no sepas en qué estás fallando (me pasó :sweat:). 

Te recomiendo pensar en otras formas de modelar el problema y que pruebes muchas veces tu código para no tener errores inesperados. Mucho éxito con la tarea! ✨

**Comment by fran-gl** [comment]
> Hola @fran-gl!
> Por experiencia te puedo decir que muy probablemente ese diseño de modelación te va a traer problemas en el correcto funcionamiento de tu tarea, especialmente si es que el menú que llamas dentro del otro menú va a seguir llamando más funciones.
> 
> No necesariamente se va a crear una dependencia circular (lo cual sí es una mala práctica) pero puede que tu programa no termine haciendo lo que quieres y no sepas en qué estás fallando (me pasó 😓).
> 
> Te recomiendo pensar en otras formas de modelar el problema y que pruebes muchas veces tu código para no tener errores inesperados. Mucho éxito con la tarea! ✨

Ok, muchas gracias!
