### ISSUE TITLE
Agregar personaje al mapa

### ISSUE THREAD

**Issue by mjespinoza** [IIC2233/syllabus#330]
Holaa, cuando agrego el personaje al mapa me aparece una ventana aparte "escondida" y el personaje solo se mueve cuando le hago click a la ventana. No se que comando ocupar para quitarla y que las funciones del personaje sigan funcionando. Gracias de ante mano.

**Comment by YoGandalf** [comment]
Si te aparece la ventana en vez del personaje en el mapa y el personaje es un qlabel, probablemente te falta agregarle el parametro self al qlabel al final de los argumentos.

**Comment by mjespinoza** [comment]
Si le agregue el padre, pero me aparece asi, es una ventana sin nada que si la dejo atras del mapa no se mueve el personaje :(
![Captura](https://user-images.githubusercontent.com/42595117/58136610-ac0cb600-7bfc-11e9-979a-bfb29789ea5c.JPG)

**Comment by jmwielandt** [comment]
Hola!

¿De qué hereda tu personaje? ¿A qué objeto le pones la imagen?
Creo que para ayudarte es más fácil que subas tu código a tu repo, para ayudarte mejor.

De todos modos lo de que el personaje no se mueva a menos que le hagas click tiene que ver con algo llamado `focus`. Piensa en cuando intentas escribir en un formulario donde hay varios campos de texto, ¿qué hace que solo uno registre lo que ingresas en el teclado? Es el `focus` (relacionados: `focus policy` / `focus handling`). Esto es "quién" va a estar escuchando los distintos inputs de tu usuario. La función que recibe los inputs del teclado para el movimiento de tu personaje está en esa ventana y solo comenzará a escuchar tu teclado cuando el focus del programa esté en esa ventana. Eso te puede dar una pista sobre lo que puede estar pasando.

Quedo atento.

**Comment by jmwielandt** [comment]
@mjespinoza 
- Mueve tu función `keyPressEvent` a la clase `VentanaJuego`
- Haz que tu personaje herede de `QLabel` y no de `QWidget` (setéale el parent eso sí).
Por esto se te abre una segunda ventana.

Hice esos cambios en tu repo clonado y funciona bien :D

**Comment by mjespinoza** [comment]
muchas gracias!!!
