### ISSUE TITLE
Función comparar columna

### ISSUE THREAD

**Issue by JoseValencia125** [IIC2233/Syllabus#330]
En el enunciado dice que la función recibe como argumento:
un str que puede ser: ("LEN", "PROM", "DESV", "MEDIAN", "VAR", "KUR", "ASI", "VAR-COEF", "KUR-COEF" or "ASI-COEF"), sin embargo"KUR", "ASI", "VAR-COEF", "KUR-COEF" or "ASI-COEF" no existen aparecen en ninguna otra parte del enunciado
¿Que son?

**Comment by sebacruzd** [comment]
#309
