### ISSUE TITLE
cantidad de genes en común

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#331]
Hola, en la función gemelo_genético(persona) hay que encontrar la persona con la genetica más parecida a persona.

Esto para cada caracteristica

Mi duda es, como se decide quien es geneticamente más identico? 

1. Por una parte estan los genes no codificantes para cada caractersitica. Estos cuentan igual?

2. Que tiene precedencia, cantidad de genes comunes en total o cantidad de caracterisitcas geneticamente comunes? Ya que en el enunciado sale que hay que ver los genes en común que tengan para cada caracterı́stica.

Con esto me refiero a que tengo una persona A una B y una C
Si A y B se tienen en todas sus caracteristicas un 50% de genes comunes pero
A y C tienen las lineas geneticas de pelo y ojos iguales pero el resto todo distinto.
Entonces, quien sería el gemelo genetico de A? B o C?

**Comment by Arcoirisky** [comment]
Hola! 
Se acaba de subir una versión más detallada del enunciado. Prueba a leerla a ver si te queda más claro ahora :D

**Comment by Kitaps** [comment]
Ahí revise. 

Respecto a 1. Aun no me queda claro si es que los genes que no codifican habría o no que contarlos.

Respecto a 2. De lo que entendi con el nuevo enunciado, entonces lo que importa es la cantidad de genes en común total. Segun esto entonces el gemelo genético de A sería B (?)

**Comment by Arcoirisky** [comment]
a1. Los genes no codificadores no son relevantes.

a2. Se supone que por cada característica tienen una cantidad n_i de genes codificantes. La suma de estos n_i con i desde 0 hasta la última características son las que deben de coincidir. Entonces, si entendí bien tu ejemplo, B sería el gemelo genético de A  O:!

**Comment by glbello** [comment]
Yo sigo **sin entender** a cabalidad esta función, ¿podrían dar algún ejemplo u explicarlo de otra manera para que quede más claro por favor?

**Comment by Kitaps** [comment]
Gracias, 

Dejaré la issue abierta, ya que la marcaron como importante. 
Sientanse libres de cerrarla si quieren ;)

**Comment by Jiparavich** [comment]
Up?

**Comment by caespinoza5** [comment]
Aún me quedan dudas respecto a esta función. Lo que entiendo de esta issue es:
Supongamos que para dos personas A, B, se tiene la siguiente lista de genes:
A: ("AGT", "AGT", "ACT", TAG", "GTA")
B: ("AGT", "AGT", "TAG", "GTA").
De ellos, el id de la lista me dice que los **genes relevantes** para la altura son, respectivamente:
relevante_A = ("AGT", "AGT", "ACT", "TAG")
relevante_B = "(AGT", "AGT", "TAG")
Como es la altura, los **genes codificantes** serían:
codificante_A = ("AGT", "AGT", "ACT")
codificante_B = ("AGT", "AGT")
Entonces, la cantidad de **genes codificantes en común** para la característica altura sería 1 (sólo "AGT" se repite en codificante_A y en codificante_B). Esto se repite con las 8 características restantes y el gemelo genético sería aquel que tiene mayor suma de genes codificantes en común por característica.

Es esto correcto?

**Comment by Hernan4444** [comment]
@caespinoza5 estás casi correcto, si tenemos lo que tu dices:
```python
codificante_A = ("AGT", "AGT", "ACT")
codificante_B = ("AGT", "AGT")
```
La cantidad de **genes codificantes en común** para la característica altura sería **2** puesto que tenemos **2 AGT en común**. Luego se hace lo que dices tu, se repite en las demás características y luego se obtiene la suma de todos esos números. La persona que tenga el número más grande es el gemelo genetico.

Se entiende mejor? 
Saludos ✌️

**Comment by caespinoza5** [comment]
@Hernan4444 Muchas gracias! Ahora entiendo.

**Comment by Polea012** [comment]
@Hernan4444 Y en caso de que se tuviera estos genotipos para la altura de dos personas: 
A = ["AAT", "AAG, "AAT"]
B = ["AAG", "AAT", "TCT"]
¿A y B tambien tendrian dos genes en comun (dado que "AAT" y "AAG" están en ambos genotipos) o no tendrian ningun gen en comun porque no estan en las mismas posiciones?

**Comment by Hernan4444** [comment]
@Polea012 son 2 genes en común
Saludos ✌️

**Comment by Polea012** [comment]
Gracias!

**Comment by JPSF** [comment]
Hola! Me surgió una duda respecto al último caso mencionado. @Hernan4444 dice que son 2 genes en común, pero anteriormente habían dicho que los genes no codificantes no son relevantes para gemelo_genético, y en este caso los genes en común son AAT y AAG, los cuales no son codificantes para la altura, por lo que no se deberían considerar ¿Entonces se deberían considerar o no?

**Comment by Hernan4444** [comment]
@JPSF tienes razón, como en ese momento no estabamos analizando el tema de si eran genes codificantes para altura o no, sino que si importaba la posición, no me percaté de ese gran detalle.

Lo que si se dijoal final es que como no está especificado muy bien si filtrar o no los genes codificantes para algunas consulta. Al final queda en su criterio si filtran o no y por ello la respuesta anterior que dí (2 genes en común) si estaría buena si es que no filtran o serían 0 si es que filtran. La solución que hicimos permite ambos casos.

Saludos ✌️

**Comment by mjgutierrez1** [comment]
@Hernan4444 tengo una duda. Leyendo esta issue creo que entendí que para una característica, al tomar la lista de los genes que les corresponden, en esa lista pueden haber genes que no son codificantes para esa característica:

1. ¿En qué parte del enunciado quedaba claro eso?
2. ¿Hay un ejemplo de que pase eso en alguna de las personas del archivo chico de genomas.txt (el que no está en la carpeta test_1)?
3. Mi programa lo hice asumiendo que en cada lista de genes sólo habían genes codificantes para la característica correspondiente. De hecho, por ejemplo, para calcular el fenotipo en las características de forma continua veo cuántas veces aparece un gen "A" en la lista de genes para esa característica, y la proporción la calculo asumiendo que todos los otros genes son su gen complementario "B". Pero si  también hubieran genes no codificantes para la característica, entonces lo que asumí estaría mal. Es decir, muchos fenotipos podrían estar mal "calculados" y, por lo tanto, muchos de los resultados de todas las funciones de mi programa serían erroneos....

¿Efectivamente las listas traen genes no codificantes para sus respectivas características?¿Que hago en ese caso si es que ya no puedo hacer esa parte de mi programa denuevo, ya que en realidad tendría que cambiar muchas funciones del programa y no alcanzo a hacerlo?

**Comment by Hernan4444** [comment]
@mjgutierrez1 
1. En el enunciado nunca se dijo que pueden suponer que una lista de Genomas de una característica tendrá solo Tag de Valor y por ello tenían dos opciones: hacer su librería sin ese supuesto o preguntar a los ayudantes si podían realizar ese supuesto. Mucha gente hizo lo segundo (incluso en la programaton) y les dijimos que no pueden suponer eso.
2. No hay un ejemplo hasta ahora, pero eso fácilmente lo puedes agregar tu para testear eso.
3. Ese supuesto de que si no es A, entonces es B está mal.

Así que efectivamente las listas pueden traer genes no codificantes. Lo que dejamos a su criterio es si deciden filtrar la lista antes para que solo contenga Tag codificantes (situación que podrías hacer tú para que así tu supuesto sea válido) o no filtrar pero no usar el supuesto "si es A, entonces no es B".

Si no alcanzas a implementar nada, debes especificarlo en el readme para que usemos test adecuados pero eso tendrá posible repercusión en la nota.

Saludos ✌️
