### ISSUE TITLE
[Graficar: opcion normalizado]

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#331]
Si hay datos con valor negativo hay que considerarlos como positivos o se dejan negativos (?), es decir si el eje y es [-1, 0 , 1, 3], entonces el el eje x sería [0/(-1 + 0+ 1+ 3), 1/3, 2/3, 3/3] ó [0/(1 + 0+ 1+ 3), 1/4, 2/4, 3/4].
Saludos! :B

**Comment by Hernan4444** [comment]
@acrojas2 como no quedó especificado en el enunciado, queda a tu criterio mientras lo especifiques en tu Readme

Saludos!!
