### ISSUE TITLE
Proporción enemigos normales vs kamikazes 

### ISSUE THREAD

**Issue by kylevon** [IIC2233/syllabus#331]
En el enunciado dice: la proporción de enemigos normales versus kamikazes será 3 : 1.
¿Esta proporción se puede hacer con probabilidades?  Es decir: 75% de probabilidad de que un enemigo sea normal y 25% de probabilidad que un enemigo sea kamikaze.

**Comment by lily416** [comment]
Sí, puedes hacer la proporción con probabilidades. 

Ánimo y éxito con la tarea 👋 🐈🐧

**Comment by furzuadr** [comment]
En la misma línea, puedo hacer que los enemigos aparezcan en cada uno de los inicios distintos según probabilidades? Por ejemplo, si hay 4, que aparezcan con probabilidad 1/4 en cada una? Gracias!

**Comment by lily416** [comment]
@furzuadr, si te refieres a la probabilidad con la que los enemigos se reparten entre los distintos puntos de inicio, entonces queda a tu criterio como los distribuyes, mientras **no contradiga lo dicho en el enunciado**:

![image](https://user-images.githubusercontent.com/26393515/58131921-ee7ac680-7bed-11e9-9cc4-8727d48a367f.png)
![image](https://user-images.githubusercontent.com/26393515/58131939-fdfa0f80-7bed-11e9-9ea1-6c31a364dc6f.png)

Éxito con la tarea 😸

**Comment by kylevon** [comment]
En el caso de esa sección del enunciado dice que es un ejemplo eso de generar N/M enemigos en cada uno, es decir que ¿también es igual de válido hacer que se repartan equitativamente como dice furzuadr?

**Comment by lily416** [comment]
@kylevon sí, es valido lo que dice @furzuadr 😉

**Comment by kylevon** [comment]
¡Gracias!

**Comment by Juaco97** [comment]
> En el enunciado dice: la proporción de enemigos normales versus kamikazes será 3 : 1.
> ¿Esta proporción se puede hacer con probabilidades? Es decir: 75% de probabilidad de que un enemigo sea normal y 25% de probabilidad que un enemigo sea kamikaze.

Con respecto a esto mismo, ¿se puede asumir que en cada ronda la cantidad de enemigos será un número múltiplo de 4? Como no lo dice el enunciado, yo había propuesto una forma específica para resolver en caso de que no fuera así (¿puedo hacerlo y dejarlo en claro en el readme?).
Gracias!

**Comment by lily416** [comment]
@Juaco97 sí, puede asumir que el número de enemigos será múltiplo de 4, para esto debes hacer que los parámetros `GENERACION_1` y `GENERACION_2` sean múltiplos de 4 y especificarlo en tu README.

Saludos y éxito con la tarea 🐱
