### ISSUE TITLE
Syntax error en multiples archivos cuando no deberia haber

### ISSUE THREAD

**Issue by matiaschen** [IIC2233/syllabus#331]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

[En mi código me aparece syntax error cuando no existe uno, trate haciendo correr el programa  a traves de la terminal y cerrando visual studio, sin ningun resultado favorable]

**Comment by tqmbanados** [comment]
Hola! Estás 100% seguro que no hay un syntax error? A veces los linters no los identifican, y python a veces tira el error en la línea "incorrecta", es decir, a veces cuando ocurre un ```SyntaxError``` y una línea que se ve bien, es porque en alguna línea *anterior* está el error.

**Comment by matiaschen** [comment]
Hola! Voy a revisar lo que me dices, muchas gracias por la sugerencia. Te aviso como me va.

**Comment by matiaschen** [comment]
Era lo que decias. Gracias por la ayuda!

**Comment by tqmbanados** [comment]
Me alegro que se te haya arreglado!!
