### ISSUE TITLE
Error test 4 en votos_interespecie

### ISSUE THREAD

**Issue by sofiiit** [IIC2233/Syllabus#331]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo un error en el test_18_votos_interespecie.py en el test 4, que dice 

`tests_publicos\test_18_votos_interespecie.py", line 508, in test_4
    resultado_estudiante = votos_interespecie(generador_entregado1, generador_entregado2, generador_entregado3)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: votos_interespecie() missing 1 required positional argument: 'misma_especie'`

Mi duda es si está bien ese test, y de contrario podría corregirlo proporcionando un valor predeterminado en la definición de la función?

**Comment by ignacio-sp** [comment]
Hola @sofiiit, lo que mencionas es un error de como estaba definida la función, se realizaron los cambios pertinentes según indicada en esta [issue](https://github.com/IIC2233/Syllabus/issues/338#issue-2303846202) modificando el argumento `misma_especie`, para que sigas las intrucciones indicadas ahí. Mucha suerte!
