### ISSUE TITLE
Duda sobre la ejecución de la tarea.

### ISSUE THREAD

**Issue by mon-b** [IIC2233/Syllabus#331]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Según el enunciado, la tarea se ejecutará desde T2 (aunque no tendrá ese nombre). Mi pregunta es si al ejecutar, por ejemplo, el main.py del cliente se hará en la terminal: python entrega_final/servidor/main.py, o exactamente ¿cómo se manejará esto? 

No sé si es seguro asumir que así será y aclarar en el README que mi tarea está pensada para ejecutarse así. :(

**Comment by Hernan4444** [comment]
Hola @mon-b 

En primera instancia, el ayudante hará `cd` hasta llegar a la carpeta cliente y servidor (en 2 terminales distinta) y hará `python main.py` (asumiendo que en cada carpeta exista un `main.py`). Esto es igual a cómo lo hicimos en la experiencia 4.

Sin embargo, si quieres hacerlo de la forma que propones `python entrega_final/servidor/main.py`, tambien es aceptado mientras lo indiques en el _readme_ 👍 . Esa forma sigue respetando el hecho que la ejecución no depende del directorio "T2", todo está adentro de dicho directorio.

Personalmente recomiendo intentar hacerlo como en la experiencia 4, así tus _paths_ e _imports_ quedan mucho más fáciles, y es más intuitivo hacer `python3 main.py` desde la carpeta donde vas a ejecutar el programa.

¡Mucho éxito con la tarea!
Saludosヾ(＾-＾)ノ
