### ISSUE TITLE
Actividad Sumativa Qt Designer

### ISSUE THREAD

**Issue by Dafnemami** [IIC2233/syllabus#331]
Es necesario llevar instalado el programa?, o solo tendremos que escribir código?

**Comment by jmwielandt** [comment]
Hola!

La actividad de mañana se puede hacer únicamente escribiendo código, aunque también podrán hacerlo usando QtDesigner. Si quieres usarlo, es mejor que lo lleves instalado, para no perder tiempo durante la actividad.

Sobre su uso en la Tarea 2, lo informaremos más adelante.

Saludos!
