### ISSUE TITLE
AttributeError: Atributos privados en herencia con properties

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#331]
Cuando me refiero a una propiedad sin __ en el metodo str me da error de que no existe, pero esta bien definido como property. Por que pasa esto?

EDIT: investigando me di cuenta que el error era que falla el getter del property :thinking: dice `AttributeError: 'Niffler' object has no attribute '_Niffler__nivel_magico'
`

**Comment by igbasly** [comment]
Hola @sofiuni 😄 
Con la información que me entregas, solo puedo pensar en que definiste el *getter* usando un atributo privado, el cual no está definido. Me explico, consideremos que tienes una clase con una *property* definida como el siguiente ejemplo:
```python
class Clase:
    def __init__(self):
        # operaciones del constructor

    @property
    def some_property(self):
        # operaciones del getter
        return self.__atributo

    @some_property.setter
    def some_property(self, value):
        # operaciones del setter
        self.__atributo = value
```
Aquí tenemos una *property* `some_property` que depende del atributo privado `__atributo`.
Si intentamos llamar al *getter* de la *property* así como está definida, obtendremos el error que tu mencionas, esto debido a que el atributo `self.__atributo` no ha sido definido. Con esto quiero decir para poder utilizar el *getter* de una *property* primero **debes** darle un valor inicial, para lo cual tienes dos opciones:
* Definir el atributo privado en el constructor con un valor inicial.
```python
    def __init__(self):
        # operaciones del constructor
       self.__atributo = algun_valor_inicial
```
* O puedes llamar directamente al *setter* de la *property* y que este defina al atributo *(eso ocurre por defecto al tener `self.__atributo = valor`)*.
```python
    def __init__(self):
        # operaciones del constructor
       self.some_property = algun_valor_inicial
```
Así cuando vayas a llamar al *getter* de la *propety* por primera vez, esta podrá retornar el valor del atributo, ya que este fue definido previamente. Por esto es importante que con *properties* siempre pensemos en el caso base y dejemos un valor por defecto.

Espero haber aclarado tu pregunta y no dudes en comentar 👌

**Comment by sofiuni** [comment]
El problema es que yo si defino la variable. Incluso lo puedo imprimir en el super().__init__(), super siendo la clase DCCriatura. El valor se crea, lo puedo imprimir, pero apenas lo intento imprimir fuera del super, me da el AttributeError. La clase hereda de DCCriatura. Los prints en el init de DCCriatura si se imprimen.

**Comment by igbasly** [comment]
@sofiuni, te pido si puedes escribir un ejemplo de cómo está implementado lo que genera tu error *(no coloques código de tu tarea directamente)*, sino por otro lado si puedes explicarlo de forma más explícita en cuanto a los pasos que mencionas.

Quedó atento 😉

**Comment by sofiuni** [comment]
Oki, 
basicamente tengo

class Criatura:
    def __init__(self, valor):
        self.valor = None
        self.valor = valor
        print(type(self))
        print(self.valor)

    @property
    def valor(self):
        return self.value

    @valor.setter
    def valor(self, nuevo_valor):
        self.valor = nuevo_valor


class CriaturaA(Criatura):
    def __init__(self, valor):
        print("entrando a criatura A")
        super().__init__(valor)
        print(self.valor)


en el codigo de la tarea, eso me da error, de que no existe self.valor en CriaturaA. Pero corriendo ese codigo funciona bien.

**Comment by igbasly** [comment]
@sofiuni, te comento que el código que me muestras se ve bien, excepto por el detalle de que en el *setter* colocas `self.valor = nuevo_valor` lo cual llama recursivamente al *setter* de la *property* y genera el error de límite de recursión. El resto de la implementación está correcta, definiendo el valor en el constructor como te mencionaba, aunque no es necesario que lo definas dos veces 😅.

Si eso no soluciona tu problema, entonces probablemente ya no sea por la definición de la *property*, de todas formas coméntame cualquier inquietud que vaya quedando  😄.

**Comment by sofiuni** [comment]
Mi codigo de la tarea no lo tiene asi y igual da error, por lo que se puede asumir que el problema no es la property... Que mas podria ser?

**Comment by igbasly** [comment]
@sofiuni, honestamente no podría decirte qué más puede estar causando el error con la información que tengo hasta ahora. Ya que con todo lo que me has dicho y lo que te he comentado, la *property* debiera estar bien definida. 

Te invito a que comentes directamente con el error que arroja tu programa, para poder evaluar que podría estar causándolo.

**Comment by sofiuni** [comment]
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    criaturas_lista.append(cs.Niffler(s[0], s[2], s[3], s[4], s[5], s[6], s[7], s[8], s[9], s[10], s[11], s[12]))
  File "/home/usuario/UNI2020/PA/sofiuni-iic2233-2020-1/Tareas/T01/criaturas.py", line 225, in __init__
    print(self.__nivel_magico)
AttributeError: 'Niffler' object has no attribute '_Niffler__nivel_magico'

**Comment by igbasly** [comment]
@sofiuni según lo que me comentas, el error se debe a que `__nivel_magico` es un atributo privado de la clase padre de `Niffler`, y con los atributos privados hay que tener el cuidado de que no se heredan *(de hecho, eso es lo que python considera como privado, que no se herede)*. 

No estoy seguro de por qué intentas imprimir ese atributo (asumiendo que se utiliza en una *property*), pero de todas formas en la *property *, aunque esté definida en el padre, debe funcionar correctamente. Por lo tanto, te recomiendo que utilices directamente la *property*.

Ahora, si además quiere utilizar ese atributo, solo debes definirlo nuevamente como `self.__atributo` en la clase heredada y este no interferirá con el que tengas en la clase padre.

Espero que esto aclare el problema, si no, házmelo saber :+1:

**Comment by sofiuni** [comment]
Hmm entiendo perfecto eso, ahora trate de arreglarlo eliminando las menciones que tienen "__" en el nombre en ves de llamar al getter pero el getter en si da error... tengo que hacer las propiedades en cada clase que hereda de la clase abstracta? No entiendo esa parte

**Comment by sofiuni** [comment]
*Ahora agrege `self.__nivel_magico = 0` al metodo __init__ de la clase Niffler, antes del super().__init__, y al imprimir el valor, da 0... Sera que no se esta corriendo el init de la clase padre?

**Comment by igbasly** [comment]
@sofiuni, respecto a tu primera mención no es necesario que definas nuevamente cada *propety*, ya que como te mencionaba, estas funcionan perfectamente en la clase hija mediante la herencia, siempre y cuando las llames como corresponde `self.property` para obtener o asignar un valor.

Por otro lado para tu segundo comentario, tal como te mencionaba en mi comentario anterior, los atributos privados funcionan de forma independiente en cada clase, por lo tanto, si defines de esa forma el atributo es normal que se imprima ese valor, pero no significa que en la clase padre no se haya definido o tenga otro valor.

Te quiero invitar a que revises cuidadosamente tu código, las definiciones de las clases y de las *properties* basándote en la información de los [contenidos](https://github.com/IIC2233/contenidos/blob/master/semana-02/2-properties.ipynb) y lo que te he expuesto más arriba, ten cuidado con definir el atributo que la *property* utilizara para la permanencia de la información *(lo que menciono en el [primer comentario](https://github.com/IIC2233/syllabus/issues/331#issuecomment-611048498) de la issue)*, además de siempre utilizar la *property* para cualquier cambio y no acceder directamente al atributo mencionado.

Quedo atento a cualquier duda o comentario 🙌

**Comment by sofiuni** [comment]
Entonces como accedo a los valores definidos? Entiendo lo de los contenidos, pero no comprendo adonde se estan definiendo los valores. No el super().__init__ define los valores en el self?

**Comment by igbasly** [comment]
Si estamos hablando de las *properties*, como te he mencionado se debe hacer mediante sí mismas. Si por ejemplo, si usamos la *property* del [pimer ejemplo](https://github.com/IIC2233/syllabus/issues/331#issuecomment-611048498) que guarda información en `__atributo`, uno **no debe** acceder a `__atributo`, sino que a `some_property` para cualquier uso de la información en cualquier clase *(donde está definida o en alguna heredada)*.
Por otro lado, si hablamos de atributos normales, estos si pueden ser utilizados directamente en cualquier clase.

¿Es a esto a lo que te refería? 🤔

**Comment by sofiuni** [comment]
Si, accedo al getter del property, **pero me da el AttributeError**

**Comment by igbasly** [comment]
Entiendo, es por esto que te recomiendo revisar minuciosamente tu código en base a lo mencionado en el [comentario anterior](https://github.com/IIC2233/syllabus/issues/331#issuecomment-611837852). Así descartar o arreglar cualquier error de modelado que pueda estar interfiriendo.

Además te recomiendo ir probando de a poco en cada parte lo que vas implementando. Me explico, si heredas, primero en la clase padre, en el constructor, en el *setter* y *getter*, etc. Luego en la clase heredada lo mismo, en el constructor, asignando valores, etc. 👌

**Comment by sofiuni** [comment]
Pucha ya probe todo lo que hemos conversado y mas, y el error persiste, no se como resolverlo y no puedo avanzar

**Comment by igbasly** [comment]
@sofiuni 😄!
Para hacerme una mejor idea de cuál podía ser tu problema, revisé el código que llevas hasta ahora.
Pude notar cuál es el problema que causa el error que mencionas, pero considerando que esta *issue* es pública y puede ser de ayuda para un compañero, lo explicaré mediante un ejemplo.
Se define una clase `ClaseBase` con una *property* `some_property` y un atributo privado `__atributo`, junto una clase `SubClase` que hereda de `ClaseBase` en la cual se redefine la *property* `some_property` (Generalizando tu código): 
```python
class ClaseBase:
    def __init__(self, arg1):
        self.__atributo = arg1

    @property
    def some_property(self):
        return self.__atributo
    
    @some_property.setter
    def some_property(self, value):
        self.__atributo = value


class SubClase(ClaseBase):
    def __init__(self, arg1):
        super().__init__(arg1)

    @property
    def some_property(self):
        return self.__atributo
    
    @some_property.setter
    def some_property(self, value):
        self.__atributo = value
``` 
## Causas 😓 
En general, el modelo aquí planteado no está incorrecto, pero hay dos factores que influyen en que el error se genere. 
* Primero, el valor de la *property* es asignado directamente al atributo privado en el constructor del padre, es decir, se le entrega el argumento al padre mediante el `super().__init__` y luego es asignado a `__atributo` en el padre.
* Segundo, la property es redefinida en la clase `SubClase` donde se utiliza nuevamente el atributo privado `__atributo`.

## Contexto 📚 
Para entender cómo estos dos factores en conjunto contribuyen al error, primero hay que repasar ciertos conceptos. Como menciono en un [comentario](https://github.com/IIC2233/syllabus/issues/331#issuecomment-611805014) más arriba, los atributos privados en Python son "privados" porque no se pueden heredar directamente, es decir, si el padre tiene un atributo `__atributo`, este no es heredado al hijo, y por lo tanto, el hijo no tendrá un `__atributo` por herencia. Aún así, en el hijo se puede definir un `__atributo` propio, el cual no tendrá relación con el atributo homónimo del padre, o sea, ambos pueden tener valores diferentes. Esto se explica con más detalle en la [documentación de Python](https://docs.python.org/2/reference/expressions.html#atom-identifiers), donde se indica que Python lo que hace cuando se encuentra con un atributo del tipo `__nombre_atributo` (con dos guión bajo al comienzo) es agregar `_ClassName` al comienzo, es decir, por detrás lo convierte a `_ClasName__nombre_atributo` lo cuál genera un atributo único.

## Extraña combinación
Dicho esto, lo que ocurre aquí es que con el primer punto, cuando se pasa un valor `arg1` al constructor del padre para que este lo guarde en el atributo privado `__atributo`, esto queda guardado en el padre y la forma de acceder a ello normalmente en el hijo sería mediante la *property*, pero... :flushed:
Esto nos lleva al segundo punto, la *property* fue redefinida en base a un atributo privado con el mismo nombre en la clase hija (para Python un atributo distinto), entonces al intentar acceder a la información en la clase hija mediante la *property*... 
Ej:
```python
class SubClase(ClaseBase):
    def __init__(self, arg1):
        super().__init__(arg1)      # Aquí se guardó en el padre
        print(self.some_property)   # Aquí se quiere acceder a la property redefinida

    # Más abajo se redefine la property como en el código de arriba
```
...se genera el error producto de que en esta clase el atributo `self.__atributo` aún no ha sido definido *(que tenga un valor asignado)* ni por el *setter*, ni en el constructor, entonces para Python no existe.

## Soluciones 🙌 
En este momento solo pensé en tres soluciones para abordar el problema:
* **Primero**, puedes almacenar directamente la información en el constructor de la clase heredada:
```python
class SubClase(ClaseBase):
    def __init__(self, arg1):
        super().__init__(arg1)     # Aquí se guardó en el padre (no importa)
        self.some_property = arg1  # Aquí se guarda en el hijo

    # Más abajo se redefine la property como en el código de arriba
```
De esta forma, independiente de si se guardó en el padre o no, quedará guardada en el atributo `__atributo` del hijo por el *setter* de la *property*.
* **Segundo**, puedes cambiar el nombre de los atributos por `_atributo` *(solo **un** guión bajo)*, de esta forma Python lo considera un atributo normal y lo hereda sin problemas, no afectando la redefinición de la *property*. **OJO** que este cambio debe hacerse en todas las menciones de la variable, tanto en la clase padre, como en la clase heredada.
* **Tercero**, cuando se redefine la *property* `some_property` se puede utilizar el nombre que Python utiliza por detrás `_ClaseBase__atributo` en vez del atributo directamente.
```python
class SubClase(ClaseBase):
    def __init__(self, arg1):
        super().__init__(arg1)

    @property
    def some_property(self):
        return self._ClaseBase__atributo
    
    @some_property.setter
    def some_property(self, value):
        self._ClaseBase__atributo = value
```
Esto debe hacerse **solo en la clase heredada**, en la *property* que se redefine.

Espero que con esto haya quedado claro como arreglar el error que te aparece, recuerda que debes aplicarlo a todas las clases que estén presentando el error y puedes elegir una de las soluciones que planteo, según cual te parezca más conveniente.
Quedo atento por si surge alguna duda respecto a la explicación o por algún otro problema que persista 👍

**Comment by sofiuni** [comment]
Gracias!!! Ahora funciona todo perfecto
