### ISSUE TITLE
Duda movimiento

### ISSUE THREAD

**Issue by benjaminsalgado** [IIC2233/Syllabus#332]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda relacionada al movimiento de las entidades. Entiendo que en el enunciado (apartado 4.1 ConejoChico) se habla de que "Las animaciones de este personaje son continuas, de tal manera que se vean fluidas". ¿Esto significa que el conejo tiene que moverse de forma continua o que con los sprites que me dan "simulan" esta continuidad? Por ejemplo, si la velocidad del conejo fuera de 10, el tiempo que se tendría que demorar para ya estar en la otra casilla sería 1/10 segundos (según lo que entiendo de la formula del enunciado), lo que significa que cada 100 milisegundos se tendría que mostrar al conejo en una nueva casilla directamente (manera discreta) o que se muestre como va avanzando, en 100 milisegundos, a la siguiente casilla.

**Comment by iespinazac** [comment]
Hola @benjaminsalgado, el movimiento del conejo es discreto, pero debes utilizar los sprites para simular que hay continuidad en el movimiento. Para el ejemplo que planteas, lo correcto es el último caso 👍

**Comment by benjaminsalgado** [comment]
Lo correcto es esto entonces? "lo que significa que cada 100 milisegundos se tendría que mostrar al conejo en una nueva casilla directamente (manera discreta)" o esto "se muestre como va avanzando, en 100 milisegundos, a la siguiente casilla. (continuo)" ?

**Comment by iespinazac** [comment]
Lo correcto es que "se muestre como va avanzando, en 100 milisegundos, a la siguiente casilla. (continuo)", pero **ojo** que esto es algo visual. El conejo no puede estar entre dos casillas dentro del tablero, por eso se habla de "simular". Espero que se haya entendido 😊

**Comment by benjaminsalgado** [comment]
Que sucede en el caso de que haya hecho el juego solo considerando al tablero para aparecer las entidades y que después estas interactúen mediante señales de choque? pensando que el conejo podría (bajo esta forma de resolver la tarea) estar entre dos casillas, ¿tendría que cambiar mi implementación para usar el tablero?

**Comment by Segismundios** [comment]
@iespinazac entonces está mal si el conejo se mueve totalmente en continuo y sólo cae en una casilla al llegar a su posición final? Es que en el enunciado no veo que se diga eso y tendría que cambiar toda la lógica del movimiento y la construcción de las entidades para hacer que el movimiento se procese de forma discreta.

**Comment by iespinazac** [comment]
@benjaminsalgado en la interfaz se debe ver al conejo moviéndose de manera fluida, pero no es necesario que sea de a 1 pixel. Mientras se observe un movimiento continuo, estará correcto. Y claro, este movimiento se verá reflejado de forma interna como comentas, luego de cierto tiempo. Sólo recuerda de utilizar la fórmula (4) de tiempo del enunciado, en el ítem 4.1. En ese caso, tendrías VELOCIDAD_CONEJO con un valor de 10, pero puedes cambiarlo al ser un parámetro.
