### ISSUE TITLE
No tengo nota en el C02

### ISSUE THREAD

**Issue by SarahEverke** [IIC2233/Syllabus#332]
Hola,
en el drive con las notas no me aparece la nota del C02 y si lo di .
Estoy preocupada 🙁😣.

**Comment by flobarrios** [comment]
Hola! puede que estés entre las personas que entregaron el control sin nombre 😢. Deberás recorregir con Yessenia.

Saludos!

**Comment by SarahEverke** [comment]
Ok!
Mañana iré a recorregir,
gracias 😄

**Comment by jtagle2** [comment]
Tu control si tenía nombre. Fue un error de tipeo al subir tu nota, perdón por el mal rato! 
Saludos
