### ISSUE TITLE
Comportamientos especiales criaturas

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#332]
Hola, tengo 3 preguntas relacionadas entre sí:
1.- Cómo sé qué alimento le trae un Augurey al dueño? se hace aleatorio?
2.- Cuando Erkling roba un alimento, se beneficia con esto? me refiero aumenta su salud?
3.- En qué momento exactamente se ejecutan estos comportamientos? inmediatamente después de sumar 1 a los `dias_sin_com` de cada criatura y antes del resto de cosas pedidas en la sección de **Pasar al día siguiente**?

**Comment by mpsubiabre** [comment]
Hola @dlmed !

1. Como no se explicita en el enunciado queda a tu criterio siempre y cuando lo expliques en el ReadMe, el ideal es que sea cualquiera de las tres tipos de alimentos.

2. Cuando Erkling roba un alimento, recibirá todos los beneficios del alimento que comió.

3. Estos comportamientos dependen de como se encuentra la criatura al comienzo de un día y también pasan al comienzo del día, por lo que si, como bien lo indicas esto pasa después de sumar un 1 a los días sin comer, sin embargo, el enunciado no indica explícitamente si ocurre antes o después de realizar el resto de acciones pedidas en la sección pasar de día, por lo que queda a tu criterio, pero recuerda explicarlo en el README :)

**Comment by mpsubiabre** [comment]
Hola @dlmed!

Quisiera agregar un detalle, en el caso particular de que Erkling robase Buñuelo de Gusarajo, la probabilidad de rechazo queda anulada. Mas detalles de esto en esta issue #336

**Comment by rldelafuente** [comment]
Hola!
Siguiendo con la linea de la pregunta. ¿Augurey puede traer un alimento si está escapado?¿ No tiene hambre significa que días sin comer es 0 o está satisfecha?

Gracias!

**Comment by mpsubiabre** [comment]
Hola @rldelafuente,

Sobre tu duda de traer alimento de Augurey esta contestada en esta issue #327.
En cuanto al termino no tener hambre, hace referencia a que este satisfecha :)
