### ISSUE TITLE
Monedas enter rondas

### ISSUE THREAD

**Issue by furzuadr** [IIC2233/syllabus#332]
Hola, tengo definido que las monedas dejen de aparecer cuando se acaba una ronda, pero debo eliminar las existentes? Puedo dejarlas y comérmelas entre rondas? O dejarlas y comérmelas cuando parta una nueva ronda?
Gracias!

**Comment by lily416** [comment]
Hola 😄 

Queda a tu criterio si:
- Eliminas las monedas que quedaron en el mapa al terminar una ronda. 💸 
- Estas están presentes desde el principio en la próxima ronda. 💰 

Cualquiera de las dos opciones debes especificarla en tu README para que tu corrector sepa al respecto. 

Ánimo y éxito con la tarea 👋 🐈🐧 

PD: Con respecto a "Dejar las monedas y comerlas entre rondas", no sería correcto ya que en las etapas de preparación de ronda el personaje y su movimiento no debería estar disponible. 🤔

**Comment by furzuadr** [comment]
Toda la razón, muchas gracias!

**Comment by quememo** [comment]
> Hola 😄
> 
> Queda a tu criterio si:
> 
> * Eliminas las monedas que quedaron en el mapa al terminar una ronda. 💸
> * Estas están presentes desde el principio en la próxima ronda. 💰
> 
> Cualquiera de las dos opciones debes especificarla en tu README para que tu corrector sepa al respecto.
> 
> Ánimo y éxito con la tarea 👋 🐈🐧
> 
> PD: Con respecto a "Dejar las monedas y comerlas entre rondas", no sería correcto ya que en las etapas de preparación de ronda el personaje y su movimiento no debería estar disponible. 🤔

Y que ocurre si en la preparación de una ronda quiero poner una torre en la ubicación que "quedó parado" mi personaje? La estaría bloqueando y no debería permitirse pero esto no me hace sentido
Creo que en ningún lado del enunciado se indica que "el movimiento del jugador no está disponible en preparación de ronda"

**Comment by lily416** [comment]
@quememo tienes razón que en el enunciado no se indica que "el movimiento del jugador no está disponible en la preparación de ronda", por lo que queda a tu criterio qué hacer con el personaje en esas situaciones:
- Permitir que se mueva por el mapa para que no interfiera con la colocación de las torres. 🗺 
- Ocultarlo durante la preparación de ronda y cuando inicie una nueva ronda hacer que vuelva a aparecer. ✨ 
- Cualquier otra idea que se te ocurra y que no contradiga el enunciado. 🤔 

Siguiendo con la idea, @furzuadr: 
- Sería válido "Dejar las monedas y comerlas entre rondas" mientras desaparezcan después del tiempo que les corresponde. ⏳ 

Éxito con la tarea 💪😸

**Comment by lily416** [comment]
@furzuadr, si decides "Dejar las monedas y comerlas entre rondas" o hacer que las monedas "Estén disponibles en la próxima ronda", ten en cuenta que deberás **manejar los casos bordes** que se pueden presentar. Por lo que te recomendamos ~~debido a que es más sencillo~~ que "Elimines las monedas al final de cada ronda". 🙏
