### ISSUE TITLE
Duda sobre Testcase

### ISSUE THREAD

**Issue by Jugonzalo** [IIC2233/Syllabus#332]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/167)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/166)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el testcase 00, me cargan correctamente los primeros 5 test pero al cargar archivos el sexto falla  el séptimo ni siquiera carga. ¿Esto es un error al cargar o referente al código?

**Comment by ignacio-sp** [comment]
Hola @Jugonzalo, podrías detallar un poco el error que te aparecen en estos tests? De momento, viendo los tests, tanto el 6 como el 7 hacen uso de los archivos de `data` que son más grandes que los del test 5, por lo que el problema puede estar ahí. Te recomiendo también para debuggear copiar el código de un test y pegarlo en otro archivo para ir haciendo prints en distintas líneas e ir viendo donde puede estar el error. Suerte!

**Comment by Jugonzalo** [comment]
Cuando se evalua print(list(resultado)) python no carga. ¿eso se debe puramente a la funcion o puede ser el generador?
![image](https://github.com/IIC2233/Syllabus/assets/143092203/da07d6f4-d069-4e41-a402-6cc8b55eaef2)

**Comment by Jugonzalo** [comment]
> Hola @Jugonzalo, podrías detallar un poco el error que te aparecen en estos tests? De momento, viendo los tests, tanto el 6 como el 7 hacen uso de los archivos de `data` que son más grandes que los del test 5, por lo que el problema puede estar ahí. Te recomiendo también para debuggear copiar el código de un test y pegarlo en otro archivo para ir haciendo prints en distintas líneas e ir viendo donde puede estar el error. Suerte!
O la duda viene hacia el contenido en si, ¿ cuales son las formas mas eficientes de manejar datos, ademas del filter() y el map()?
