### ISSUE TITLE
Uso de for y while en generadores

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#332]
Hola!

@Hernan4444 dijo en la issue #285 lo siguiente:

> ...debe ser sin usar for o while (a no ser que sean en generadores, listas por comprensión o generadores por comprensión)

¿Significa esto que sí podemos usar un for o while dentro de un generador? Por ejemplo:

```
def generador():
    for i in range(10):
        yield i
```

Saludos! 😄

**Comment by stephichau** [comment]
@akaminetzkyp sí :).
Saludos!

**Comment by akaminetzkyp** [comment]
Gracias Stephi! 😄
