### ISSUE TITLE
Información faltante de bonuses

### ISSUE THREAD

**Issue by 3rdPix** [IIC2233/Syllabus#332]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En los sprites disponemos de contenidos en la carpeta `Bonus`, en la que es posible encontrar cartas de joker, imagenes de puffles y el boton (de pánico, asumo). Sin embargo en el enunciado no es posible encontrar información respecto a estos elementos. ¿De qué manera se deben implementar? Adicionalmente, ¿no es posible obtener todos los bonuses? Según se lee, el límite es 5 décimas, pero esto es no posible de obtener; solo con el chat, de modo que se deja de lado otro bonus?

En los cheatcodes también menciona que habrán dos posibles cheatcodes, pero solo uno se explica en el enunciado.

**Comment by mtaguero** [comment]
En un principio se habían evaluado distintas opciones de bonus para que pudiesen implementar, sin embargo, no todas las opciones fueron seleccionadas. Por esta razón es que hay más sprites de los que deberían ocupar, que como dices, no se encuentran en el enunciado. Sin embargo, estos sprites pueden usarlos como estimen conveniente, ya sea para decorar el chat u otra situación. Asimismo, no es necesario que ocupen todos los sprites si estos no son mencionados en el enunciado.


### **Aunque, las cartas de joker fueron implementadas pensando en que al apretar el botón de pánico una de ellas pudiese ser mostrada y seleccionada en vez de alguna de las cartas que se tienen en el mazo.**


En cuanto a los bonuses existe un límite de 5 décimas. Esto busca que ustedes no tengan que realizar todos ellos, sino que si eligen el chat, solo hagan eso y ya obtengan sus 5 décimas. Si esto les complica mucho, pueden hacer los otros bonuses que les permite obtener un total de 4 décimas.

Y con respecto a los DOS cheatcodes, probablemente sea un error de enunciado que se aclarará pronto. 
¡Gracias por mencionarlo!
