### ISSUE TITLE
Fin del Juego, Luigi muere por fantasma

### ISSUE THREAD

**Issue by franfonte** [IIC2233/Syllabus#332]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

El enunciado dice que luigui muere si es que un fantasma llega a su misma casilla, por lo tanto ¿si luigi se mete a la casilla donde hay un fantasma actualmente podria no morir?

**Comment by ignaciovita** [comment]
Hola! En realidad da lo mismo quien se topa con quien. Luigi pierde una vida si es que ambos se encuentran en una misma casilla. En la sección 5.2. del enunciado se menciona:

"El fantasma es el principal enemigo del juego. Si el fantasma llega a estar en la misma casilla que Luigi cuando a este no le quedan vidas, se terminará el juego y el usuario habrá perdido. En caso contrario, si alcanza a Luigi pero aún posee vidas restantes, entonces solo perderá una vida."

Acá queda un poco más claro lo que te menciono, el quien se topa con quien no es relevante.
