### ISSUE TITLE
Opción "Volver atrás" en Menú de Inicio

### ISSUE THREAD

**Issue by domingo2000** [IIC2233/syllabus#332]
Hola, respecto al menu de inicio de la tarea 1, se dice que todos los menus tienen que tener la opcion de volver y salir, pero el de inicio no "volveria" a ninguna parte, debe entonces tener una opcion volver, o solo la opcion de salir?

**Comment by retamalcito** [comment]
¡Hola @domingo2000!

Como correctamente dices, el menú de inicio no podría volver a ningún otro menú, ya que es el primero que se presenta al usuario. Por lo tanto, este es el **único** menú que no necesita tener la opción de **volver atrás**.

¡Saludos! 👋

**Comment by camirojasguajardo** [comment]
Una consulta, el orden de los 1)menús es inicio 2)principal y 3)entrenador, cierto? o sea que puedo volver de 3) a 2) y de 2) a 1) pero no de 3) a 1), o sí?
Saludos!

**Comment by retamalcito** [comment]
¡Hola @camirojasguajardo!

Lo que dices es correcto, es decir, la opción **volver atrás** debe llevarte al menú **inmediatamente anterior** al actual.

¡Saludos!
