### ISSUE TITLE
Problema de VScode con pyqt

### ISSUE THREAD

**Issue by bgonzlez** [IIC2233/syllabus#332]
Hola, me pasa que funciona pyqt cuando corro el código en idle pero no en Vscode, aparece que la librería no existe, busqué y pregunté pero no pude encontrar nada. Gracias!!

**Comment by benjastraub** [comment]
Tal vez tienes más de una versión de Python instalada y tienes seleccionado en VsCode el Path de la versión en la que no instalaste PyQt5

**Comment by bgonzlez** [comment]
buena gracias!

**Comment by pazanelli** [comment]
Hola! Me pasó lo mismo y segui las instrucciones en esta página:  https://medium.com/@haominnn/how-to-deal-with-python-not-finding-tensor-flow-module-under-anaconda-3aefa8ffae11

**Comment by jmwielandt** [comment]
**Disclaimer rápido: NO instalen anaconda.**

Hola @bgonzlez !

¿Tu problema se solucionó con lo que dijo @benjastraub ?

Saludos.

**Comment by NelsonIMA** [comment]
Hola! Yo tengo un problema, tengo VSCode pero no sé si atribuírselo.

Al ejecutar los códigos "Eventos y señales", los codigos 3 y 4 (eventos de mouse) me arroja una pantalla en blanco. Con los demás codigos no he tenido problema.

![image](https://user-images.githubusercontent.com/42616922/65653358-4b96e680-dfeb-11e9-8d40-eda5e02a5127.png)

Quedo atento,
Gracias de antemano c:

**Comment by NelsonIMA** [comment]
Agregar a lo anterior que me arroja esto en la terminal:

![image](https://user-images.githubusercontent.com/42616922/65653910-5ce0f280-dfed-11e9-95be-080bd6bbce9f.png)

**Comment by benjastraub** [comment]
@NelsonIMA fíjate que tengas descargadas las imágenes azul.png y verde.png

Luego revisa que el path sea el correcto según donde están guardadas

Y por último fíjate que estes ejecutando el script en el directorio correcto

**Comment by NelsonIMA** [comment]
Gracias Benja!
