### ISSUE TITLE
Uso de while

### ISSUE THREAD

**Issue by fantinee** [IIC2233/Syllabus#333]
Hola, escribo porque por enunciado entiendo que esta prohibido el uso de while sin embargo me gustaria saber si se permite dentro de generadores de la siguiente forma: 
pd. la imagen la saque de la manera que enunciaron como permitida en actividades pasadas
![image](https://cloud.githubusercontent.com/assets/26147098/25509931/d4f8aed2-2b92-11e7-8f4a-8320d90a925c.png)

**Comment by rpalmaotero** [comment]
#332
