### ISSUE TITLE
Comprar torres durante el juego

### ISSUE THREAD

**Issue by csmeneses** [IIC2233/syllabus#333]
Hola... Las torres se pueden comprar en el transcurso de una ronda o solo antes de que empiece?
Si no se pudiera, en la primera ronda si o si perdería vida la base, ya que no tengo dinero al comenzar y no podría poner torres.

**Comment by lily416** [comment]
Hola 😄 

Como se dice en el enunciado:

![image](https://user-images.githubusercontent.com/26393515/58132538-8b8a2f00-7bef-11e9-86dc-f625db3934ce.png)
por lo que no puedes agregar torres en el transcurso de una ronda. 😕 

En la issue #311 se habla de partir con una cantidad fija de monedas al inicio del juego, así podrás construir torres y no perderas en la primera ronda. 😉💰 

Ánimo y éxito con la tarea 👋 🐈🐧
