### ISSUE TITLE
Duda Reiniciar Nivel 

### ISSUE THREAD

**Issue by rosarioguerreror** [IIC2233/Syllabus#333]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!
Tengo una pregunta con respecto a la cuenta regresiva. En el enunciado dice que si llega a 0 segundos se debe reiniciar el nivel. Reiniciar el nivel quiere decir que los lobos deben volver a su posición inicial y vaciar el inventario? O se refiere a devolver al conejo a la entrada del nivel.

Gracias!

**Comment by Hernan4444** [comment]
Hola @rosarioguerreror 

Lo único detallado en el enunciado es que cuando se reinicia el nivel, todos los lobos vuelven a aparecer y que el conejo vuelvo a la entrada. Todo lo demás queda a tu criterio. En particular:

> ¿se vacía el inventario? 

Queda a tu criterio qué ocurre con él. Puede vaciarse, mantenerse como está o restaurarse a cómo estaba cuando empezaste el nivel.


> ¿los lobos vivos vuelven a su pocición inicial? 

Es una opción o la otra es que se queden donde están.

En ambos casos, recuerda dejar la decisión tomada en el Readme.

¡Mucho éxito en la tarea!
Saludos!

**Comment by vichoassadi** [comment]
¿Lo mismo sucede cuando el conejo choca con un enemigo? Vi una issue que hablaba de esto, pero el enunciado dice que cuando choca con un lobo o una zanahoria, se pierde una vida y se lleva al inicio; no habla nada de que se reinicia el tiempo o que vuelven a aparecer los lobos. Gracias
