### ISSUE TITLE
Cosas implementadas en el README

### ISSUE THREAD

**Issue by minsoos** [IIC2233/syllabus#333]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
[**Corto**] ¿Es necesario/recomendado escribir ítem por ítem incluyendo subítems en el readme? va a quedar un poco largo si coloco toda la pauta.

**Comment by mistico0121** [comment]
Queda a tu criterio. Si dices que lo implementaste y explicas un poco como queda demostrada esta implementación, facilita la corrección.

La idea del README es que al momento de corregir, entendamos mejor como funciona su programa y no se nos pase algún detalle o funcionalidad, ya que ustedes conocen su código mejor que nosotros.

Igual hacer READMEs es un arte. Mientras lo hagas con la intención de facilitar nuestra corrección, y no solo "porque hay que hacerlo", creo que es un README bueno.

**Comment by minsoos** [comment]
Gracias!
