### ISSUE TITLE
bloqueo de firewall al ejecutar servidor.py

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2233/Syllabus#333]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

[Describe tu duda de manera detallada, explicando los contenidos en cuestión y ojalá colocando código o un caso de uso de ejemplo]
Estaba practicando la materia de networking para la tarea, y al intentar ejecutar por primera vez un servidor, saltó la alerta del firewall de windows defender donde decía que había bloqueado algunas características de la aplicación Python, preguntandome si quería que python se comunicara en redes públicas o privadas, lamentablemente no permiti el acceso y apreté cancelar, por lo cual ahora cuando ejecuto el servidor ya no salta el firewall de windows defender para dar la opción permitir, el problema es que asumo que ahora python tiene bloqueada la comunicación por redes en mi computador (puesto que al ejecutar el servidor no aparece nada en la terminal)
¿Es necesario desbloquear esta característica de python para la tarea?
y ¿Como lo hago sin desactivar mi protección de firewall?

específicamente estaba tratando de ejecutar el servidor en el input 12 de los contenidos de networking (el ejemplo del servidor tcp)

**Comment by tocococa** [comment]
Hola @vice-rosas99 ! Para permitir que Python 3 atraviese el firewall de tu PC, tienes que ir a `Control Panel\System and Security\Windows Defender Firewall\Allowed apps` y buscar Python o agregar el ejecutable del PATH si no aparece en la lista.

**Comment by vice-rosas99** [comment]
Efectivamente no aparece en la lista, solo aparece python.exe
Puedes explicar lo de de agregar el ejecutable al PATH?

**Comment by tocococa** [comment]
Si aparece `python.exe` en la lista del firewall, y tiene tickeada la opción de dejar pasar está bien, debería dejar que python se conecte a la red de tu computador.

**Comment by vice-rosas99** [comment]
python.exe solo tiene la opción para redes públicas y no para redes privadas (que es en lo que estoy yo ahora), el problema es que no me deja editarlo

**Comment by vice-rosas99** [comment]
ok, al final por algún motivo a pesar de que el firewall bloquee la comunicación de python, igual mi programa de cliente pudo recibir la info del servidor, (supongo que el bloqueo que tengo yo solo es efectivo en caso de comunicaciónes no locales)

**Comment by vice-rosas99** [comment]
Yo se que no debería preguntar acá y hacer una nueva issue, pero **¿Es necesario que la Tarea esté lista para ejecutarse en 2 máquinas distintas? Osea si debería cambiar como lo tengo yo ahora donde el host es local

**Comment by Christian-Klempau** [comment]
Hola @vice-rosas99!
No es necesario que tu aplicación se pueda ejecutar entre dos máquinas (es decir, computadores) distintas. Al momento de corregir, corremos servidor y cliente en la misma máquina. Eso sí, debe existir comunicación entre ambas partes, dentro del mismo PC.
Saludos!
