### ISSUE TITLE
take_movie_while

### ISSUE THREAD

**Issue by jeschuwirth** [IIC2233/Syllabus#333]
En esta consulta nos dan que las únicas opciones en column son rt,imdb,metacritic, date o box_office, pero en los ejemplos de consultas preguntan por IMDb con mayúscula, mi duda es ¿debemos sólo aceptar el nombre alternativo de las fuente de rating como RT,MC,IMDb, o tambien se puede preguntar por el nombre completo, o ¿por el nombre en minúsculas como sale en las opciones de la consulta?

**Comment by IchottMano** [comment]
@jeschuwirth Hola!

En esos caso se puede preguntar por el nombre completo o por el nombre alternativo, sin embargo es **muy importante** que las mayúsculas e minúsculas sean exactamente iguales a las que salen en el enunciado.

Saludos!

**Comment by frduran** [comment]
@IchottMano Esas mayúsculas y minúsculas exactamente iguales a las que salen en el enunciado se refieren a las de la tabla en 2.3 o como salen en el enunciado de take_movie_while?

**Comment by jpjoublan** [comment]
Y `box_office` se recibe en minúscula o mayúscula?

**Comment by Hernan4444** [comment]
@jpjoublan eso no quedó especificado (y definir uno ahora no creo que sea lo mejor), sugiero dejarlo tal como viene en el dataset, pero de todos modos escogan una opción (mayuscula o minuscula) y la ponen en el Readme.

Saludos ✌️
