### ISSUE TITLE
largo de funciones

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#333]
la documentación de las funciones y/o comentarios cuenta en el largo de lineas de una función? 🙄

**Comment by KnowYourselves** [comment]
No. Salu2

**Comment by rihanuch** [comment]
gracias!

**Comment by MrEarle** [comment]
Y cuenta las lineas continuadas por seguir PEP8?
Ej:
`print("Blah blah.... \

"blah.)`
Cuenta como 1 o 2 lineas?

**Comment by KnowYourselves** [comment]
Cuenta como 1!

**Comment by MrEarle** [comment]
Y el uso de decoradores se suma al largo de la función?

**Comment by Hernan4444** [comment]
@MrEarle No se suma.
Saludos ✌️

**Comment by pnheinsohn** [comment]
Tengo una duda, no me queda claro bien si por ejemplo tengo una linea de código en 5 líneas de pep8... Eso cuenta como una linea o 5?

**Comment by Hernan4444** [comment]
@pnheinsohn eso cuenta como 1 linea, pero recuerda lo siguiente del enunciado:
![image](https://user-images.githubusercontent.com/15641721/31075308-413fd85c-a74b-11e7-9e74-5be00dfeb802.png)
Aunque PEP8 lo permita, ten cuidado en que se deje de entender lo que programas.

Saludos ✌️
