### ISSUE TITLE
No encuentro QtDesigner en Ubuntu

### ISSUE THREAD

**Issue by Beitey** [IIC2233/syllabus#333]
Hola, he probado diferentes comandos en mi terminal para abrir/instalar QtDesigner.
Si este se instala al momento de instalar PyQt5, ¿Donde lo podria encontrar y ejecutar?

**Comment by bimartinez** [comment]
Hola @Beitey!

Intenta instalarlo a través del siguiente comando:

`sudo apt-get install qttools5-dev-tools`


Fuente: [*StackOverflow*](https://es.stackoverflow.com/questions/122881/como-instalar-el-modulo-qt-designer-en-linuxubuntu)

Avísame como te va!
