### ISSUE TITLE
Rol de implementos deportivos y fórmula de entrenamiento

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2233/syllabus#333]
No queda claro cómo implementos deportivos influye en la eficiencia del entrenamiento. Respecto a entrenamiento deportivo sólo se indica que el atributo entrenado se aumenta por PUNTOS_ENTRENAMIENTO y la moral del deportista aumenta en 1, no se indica un ponderador por implementos. Además, en IEEEsparta sale que la fórmula de entrenamiento se pondera por 1.7 ¿cuál fórmula? 

Segundo, hay parámetros que no están definidos. Cuando los definimos le asignamos un valor arbitrario? e.g. PUNTOS_ENTRENAMIENTO = 4 (porque sí). 

Por último, el nivel de implementos de una delegación corresponde al atributo implementos deportivos ? (para validar una competencia)

**Comment by jitorcas** [comment]
Hola! @jorge-ovalle 

Responderé a tu pregunta por partes.

Primero, efectivamente implementos deportivos **no influye** en la eficiencia del entrenamiento, si no que influye en la **validez de competencia** (método de deporte). 

Segundo, la 'fórmula' que hace referencia el enunciado corresponde al parámetro `PUNTOS_ENTRENAMIENTO`.

Tercero, los parámetros que no están definidos deben asignarles valores ustedes, ya que de esa manera pueden ir variando el programa a su gusto.

Por último,  `NIVEL_IMPLEMENTOS` corresponde únicamente a implementos deportivos.

**Comment by ClauMS** [comment]
Hola!, me quedó una duda con respecto a esta issue. ¿Es totalmente necesario que los atributos de los deportistas sean de tipo int?. Por ejemplo, si se elige el parámetro PUNTOS_ENTRENAMIENTO = 4, para el caso de IEEEsparta el resultado final para un atributo sería un float ya que PUNTOS_ENTRENAMIENTO se ponderaría por 1.7.

**Comment by jitorcas** [comment]
Hola @Christian-Klempau 

Primero que todo, lo siento! no me había llegado notificación de esta issue :( 

Puedes cambiar el atributo a un` float` con tal que sea consistente con el flujo del programa!

**Comment by Christian-Klempau** [comment]
Creo que te confundiste con el "@" jajajaj

**Comment by jitorcas** [comment]
@Christian-Klempau Jajaj totalmente, lo siento 😞

**Comment by Christian-Klempau** [comment]
Tranqui :)
