### ISSUE TITLE
Nombre_jardin linea de comando

### ISSUE THREAD

**Issue by Franastel** [IIC2233/Syllabus#333]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el Menú de Inicio, cuando la línea de comando debe aceptar argumento en el formato “python3.11 main.py nombre_jardin nombre_dificultad”, el nombre del jardín debe ser si o si uno de los que está en jardines.txt?

**Comment by CrisDonosoMaass** [comment]
Hola! Se puede dar un nombre de jardín que no esté en el .txt, pero el programa debe estar preparado para responder esos casos
