### ISSUE TITLE
Solución Ayudantía 4

### ISSUE THREAD

**Issue by fnberrios** [IIC2233/syllabus#334]
Hola! Estoy tratando de correr el main.py de la solución de la ayudantía 4 y la línea 
```
window_name, base_class = uic.loadUiType("ay_04_mainwindow.ui")'
```
no reconoce el archivo "ay_04_mainwindow.ui" siendo que los dos archivos están en la misma carpeta (tal y como se descargó del syllabus). El error es el siguiente 
```
File "C:\Users\Local\Programs\Python\Python37\lib\xml\etree\ElementTree.py", line 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'ay_04_mainwindow.ui'
```
 Ocupo VS Code para ejecutar el programa. ¿Saben cuál podría ser el problema? Gracias de antemano.

**Comment by bimartinez** [comment]
Hola @fnberrios!

Desde dónde estás ejecutando el archivo, especificamente desde qué carpeta se está ejecutando *Python*? Me tinca que puede ser un problema de que *Python* se esté ejecutando desde otro *path* que no es donde se encuentra el archivo que dices. 

Intenta abrir una terminal directamente en la carpeta donde se encuentra el archivo y ejecutalo desde ahí. Avísame como te va y si te va mal adjunta pantallazos de tu terminal.

Saludos!

**Comment by fnberrios** [comment]
Desde el mismo documento en VS Code ejecuto el archivo. Lo pude solucionar! Lo que hice fue limpiar el WORKSPACE de VS Code dejando solo los archivos de interés y resultó. Tal vez donde tenía muchos archivos de diferentes carpetas abiertas colapsaba el terminal. Gracias!
