### ISSUE TITLE
Animación de balas

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2233/syllabus#334]
Hola. Si animo el ataque de las torres con balas, puedo omitir la parte del enunciado que dice lo siguiente?
![image](https://user-images.githubusercontent.com/48324565/58132683-57ffd280-7bf8-11e9-9790-c465f0a33c6e.png)
Gracias.

**Comment by gatochico** [comment]
Hola! Puedes añadir todas las funcionalidades extras que quieras a la tarea, sin embargo no puedes omitir **nada** de lo pedido en el enunciado. Por lo tanto, la etiqueta sobre la torre debe ir de todas formas. Éxito !!!
