### ISSUE TITLE
Asunciones de menús

### ISSUE THREAD

**Issue by minsoos** [IIC2233/syllabus#334]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

¿Puedo hacer las siguientes asunciones?
1. Si simulas una hora, ya no hay vuelta atrás, por lo que si no ingresas una opción correcta al elegir un barco, el programa asumirá que no quieres ingresar ningún barco
2. En mostrar estado se vuelve inmediatamente al menú de acciones (ya que a mi juicio no tiene mucho sentido poder mantenerse ahí y tener una opción de volver, ya que no se puede interactuar con nada). Esto lo pregunto porque está en la rúbrica, quizás esa parte iba asociada a "desencallar barco"

**Comment by Emiliax16** [comment]
@minsoos 

Respecto a la segunda, lo que dices es lo más lógico. Volver al menú de acciones te permitirá continuar tu simulación.
En cuanto a la primera, no estoy segura de haberla entendido bien, pero si escoges la opción de _simular nueva hora_ y no hay barcos encallados, debes seleccionar un barco. En caso de existir errores de input a la hora de escoger un barco (barco no existe por ejemplo), podrías ofrecer intentar de nuevo o volver al menú acciones. Esto podría ayudar si alguien se equivoca y elige la opción de simular cuando en realidad quería ver otra opción.

Todos los supuestos recuerda incluirlos en tu README.

Saludos!

**Comment by minsoos** [comment]
Entonces en mostrar estado no se evaluará una opción para volver al menú? con volver por si solo basta?
