### ISSUE TITLE
Diferencia crear magizoologo y cargar

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#334]
Hola, llevo mucho rato pensando la manera de crear y cargar magizoologo, mi problema es el siguiente:
Si creo un magizoologo, este tendra algunos atributos que seran aleatorios en un principio (hasta ahi voy bien). Pero cuando quiero cargar un magizoologo, este ya tiene esos atributos que fueron en un principio aleatorios y ahora no lo son.
Mi duda es, como definir los objetos de magizoologos, sin tener necesariamente que editar esos atributos en caso que ya los tenga.
Llevo pegado harto en esto

**Comment by mpsubiabre** [comment]
Hola @Juampisaez !

Si te entendí bien, preguntas como cargar a  los Magizoólogos ya existentes. Como bien indicas, cargar y crear son dos acciones diferentes, una buena opción seria entonces crear dos funciones diferentes, una para cada acción, de esta manera sabras cuando debe editar y cuando no.

Espero que esa sea tu duda, si no te referías a esto comenta esta issue :)

**Comment by Juampisaez** [comment]
entiendo ese punto, mi problema es al definir el objeto si se carga. En este caso podria crear un metodo en una clase de magizoologo que se cargar, y que en caso de que se ponga la opcion cargar en el menu de inicio, se definina el objeto como si fuese uno nuevo, y luego llamar al metodo cargar de la clase para redefinir los parametros que son aleatorios. Es valido?

**Comment by mpsubiabre** [comment]
Ahora entiendo tu duda, funcionara, pero no es lo ideal porque al final lo estas instanciando mal para luegoa rreglarlo. Te recomiendo fuertemente esto, que al crear un Magizoólogo tengas que entregarle todos los valores de los atributos (es decir que nada se cree internamente). Así, si estos deben ser creados aleatoriamente, se crean y luego se les entregan, y si ya están previamente establecidos (en el archivo magizoologos.csv) se los entregas directamente. De esta manera lo instanciaras de manera correcta inmediatamente :)

Si te quedan dudas comenta! :)
