### ISSUE TITLE
expresion fenotipo vision

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#334]
para la vision, si mal no entiendo siempre se va a tener un problema de visión, o no? (a menos que no se presente ninguno de los dos genes)

**Comment by TomasSalvadores** [comment]
Exacto, si en los genes que afectan a la visión no hay ningún gen TTC ni ATT, significa que la persona no padece de ninguna enfermedad.
Y basta con que tenga un solo gen asociado para que padezca la enfermedad, pudiendo padecer ambas, una o ninguna.

**Comment by rihanuch** [comment]
ok! muchas gracias!
