### ISSUE TITLE
StopIteration Exception

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#334]
Tras crear un generador y recorrerlo python me lanza el error "StopIteration Exception", alguna idea?
```
data = csv.reader(csvfile, delimiter='|')
data_generator = (i for i in data)
columna = [next(data_generator) for i in range(largo del generador)]`
```

**Comment by Hernan4444** [comment]
Porque data_generator es un generador y por lo tanto al hacer len(data_generador) el generador se olvida y de este modo al hacer next, no hay nada para poder hacer next.

Por otro lado recuerda que no está permitido csv para la Tarea 3.

Saludos!!

**Comment by benjamimo1** [comment]
No uso len(generator), uso el largo de la data con la cual se crea el generator. Por lo que el problema no va por ahi :/

**Comment by benjamimo1** [comment]
Ahora no usando CSV y guardando el largo como variable tira el mismo error:

`with open(x, 'r') as f:
		data = (line.split(",") for line in f)
		row_count = sum(1 for row in f)  # fileObject is your csv.reader
		columna = [next(data)[columna] for i in range(row_count)]

`

**Comment by Hernan4444** [comment]
@benjamimo1 haciendo `open(x)`, estas creando un generador y por ello cuando haces el `data`, creas un generador que está conectado a tu archivo `f`. Del mismo modo, con `sum` del archivo, haces que el generador `f` se itele para obtener la suma y por lo tanto se olvide. Esto lleva a que al hacer `next(data)`, `data` intenta acceder al generador del archivo que ya fue itelado. El problema aquí es que estás haciendo dos itelaciones sobre el mismo generador (uno desde el data y otro desde el sum) y eso no se puede.

Saludos!!
