### ISSUE TITLE
Consultas ('N/A')

### ISSUE THREAD

**Issue by clementeross** [IIC2233/Syllabus#334]
Hola, en la consulta sobre las peliculas "popular_movies()" si me piden calcular el promedio de los 3 rating (es decir, cuando r_type = "All") y resulta que alguno de ellos es ''N/A', ¿qué hago? El promedio es 0? None? Calculo el promedio entre los otros 2?

Gracias

**Comment by IchottMano** [comment]
@clementeross Hola!

Por favor revisa la sección de excepciones del enunciado.

Saludos!
