### ISSUE TITLE
2 archivos para consulta.

### ISSUE THREAD

**Issue by bozzimuc** [IIC2233/Syllabus#334]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Buenas tardes

En caso de que mi código en consultas.py supere las 400 líneas, ¿podría crear un segundo archivo digamos consultas2.py donde defina algunas de las consultas, y luego importarlas a consultas.py para que luego sean importadas a los tests?

Muchas gracias

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by ClemoAcevedo** [comment]
Hola @bozzimuc , eres libre de crear módulos de funciones auxiliares que te ayuden a implementar las funciones de `consultas.py`. Recuerda que los tests cases prueban solo `consultas.py`, por lo que en este deberías importar esas funciones auxiliares. Eso si, todo tiene que cumplir con lo descrito en el enunciado y las otras issues. Buena suerte.

**Comment by bozzimuc** [comment]
Hola @ClemoAcevedo , muchas gracias por la respuesta. No quise decir funciones auxiliares, sino mover algunas de las funciones que nos piden escribir en consultas.py a otro archivo

**Comment by ClemoAcevedo** [comment]
@bozzimuc El problema de mover algunas de las funciones pedidas a un `consultas2.py` es que no te funcionarán los test cases, porque están programados para ocupar solo las implementadas en `consultas.py`. Debido a esto, te recomendaría delegar algunas de las funcionalidades de tus funciones a módulos de funciones auxiliares, para reducir la cantidad de líneas. 

Ejemplo random: Si estoy implementado funciones para construir una casa en `casa.py` y tengo `instalar_puerta()`, `instalar_ventanas()`, etc y se que cada una de estas primero tiene que realizar mediciones, quizás puedo crear una función auxiliar en otro módulo `funciones_auxiliares.py` que se encargue de realizar las mediciones e importarlo para que los métodos de instalaciones lo ocupen. De esta forma, no moví los métodos de instalaciones a otro módulo, pero pude acortarlos. 

No se si quedó muy claro el ejemplo jajaja

**Comment by faresdababneh** [comment]
Entonces, ¿En nuestro repositorio debería estar consultas.py y el segundo archivo "x" x.py en donde consultas importa funciones de este? Gracias.

**Comment by ClemoAcevedo** [comment]
@faresdababneh claro, de la misma forma que se les ha pedido modularizar en la tarea pasada, en la misma carpeta de la tarea.
