### ISSUE TITLE
Crear un módulo adicional de constantes

### ISSUE THREAD

**Issue by martin-santiago** [IIC2233/syllabus#334]
Hola, quería saber si es legal hacer un módulo donde tenga constantes las cuales iré modificando en otros módulos, esto con el fin de no utilizar el comando "global", o seguiría siendo contabilizado como mala práctica?

**Comment by retamalcito** [comment]
¡Hola @martin-santiago!

Las únicas variables globales que necesitas para la implementación de la tarea son las que se encuentran especificadas en el enunciado y van en `parametros.py`. Además, todos los valores que van cambiando a lo largo de la ejecución no necesitan ser guardados en una variable global, por lo que **no** puedes crear un módulo adicional en el que los guardes.

Te recomendaría darle una vuelta de nuevo a tu modelamiento del problema, ya que no debería necesitar variables globales. :thinking:

¡Saludos! :wave:
