### ISSUE TITLE
Formato de diagrama de clases (abstract)

### ISSUE THREAD

**Issue by minsoos** [IIC2233/syllabus#335]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, quería saber cómo se podía denotar una clase abstracta y un método abstracto en el diagrama de clases, y si este último debe estar indicado en la súper clase, sub clase o ambos

**Comment by sperezmasri** [comment]
Hola @minsoos! Para denotar una clase abstracta en el nombre de ésta, podrías poner un paréntesis que diga ABC. Por ejemplo si yo tengo la clase "Vehiculo" que es abstracta, en el diagrama podría salir como **"Vehiculo (ABC)"**. De todos modos, hay otras formas de denotar que una clase es abstracta, pero con el que te mencioné basta.

Para denotar un método abstracto puedes hace algo similar, por ejemplo si tengo el método "saludar", en el diagrama podrías poner algo como: **(ABC) saludar(): None**. 

También podrías ponerle un asterisco (*) en los nombres, pero aquí deberías especificar en el diagrama mismo o en una explicación aparte lo que significa el asterisco.

Recomiendo que incluyas los métodos abstractos tanto en la súper clase como en la sub clase, ya que así queda más claro.

**Comment by minsoos** [comment]
Gracias!

**Comment by sperezmasri** [comment]
@minsoos te recuerdo que no debes cerrar las issues, ya que podrían servirle a tus compañeros. Basta con decir "gracias" o algo por el estilo para que nosotros pongamos el label "resuelto", saludos :smile:
