### ISSUE TITLE
Temperatura del Jardin

### ISSUE THREAD

**Issue by gracie-14** [IIC2233/Syllabus#335]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En la parte 4.1 del enunciado, dice que la temperatura del jardín debe estar entre -5 y 25 grados celsius:
<img width="588" alt="Screenshot 2024-09-11 at 12 29 50 PM" src="https://github.com/user-attachments/assets/80e16562-6bce-4406-b072-d6e2a8a6500a">

Sin embargo más tarde en la parte 5.1 dice que la temperatura puede estar entre los parámetros ```TEMP_MIN_JARDIN``` y ```TEMP_MAX_JARDIN```:
<img width="598" alt="Screenshot 2024-09-11 at 12 31 20 PM" src="https://github.com/user-attachments/assets/a0e19154-2218-4d24-807f-394e0a23aae0">

y en la parte 6 sobre los eventos, puede cambiar a algún valor entre ```TEMP_MIN_HELADA``` y ```TEMP_MAX_HELADA```: 
<img width="563" alt="Screenshot 2024-09-11 at 12 31 49 PM" src="https://github.com/user-attachments/assets/3c3c1569-964f-4676-9a33-8e0bfcfca9da">

¿La temperatura debe seguir lo indicado en la parte 4.1, y los parámetros definidos deben estar de acuerdo con esto? O, ¿la parte 4.1 solo indica el rango de la temperatura de inicio, y puede haber casos más extremos durante las heladas?

Es decir, ¿```TEMP_MIN_JARDIN``` y ```TEMP_MIN_HELADA``` deben ser no menos de -5, mientras ```TEMP_MIN_JARDIN``` y ```TEMP_MAX_HELADA``` deben ser no más de 25? ¿O pueden ser valores distintos?

**Comment by PkAlvaro** [comment]
Hola @gracie-14 😸 espero que te encuentres bien!
Te comento respecto a tu pregunta, primeramente y citando a lo que se indicó en la issue #304 en ningún caso la temperatura sale del rango de los -5° a 25° Independiente del evento.

Espero que te haya quedado mas claro 👍
