### ISSUE TITLE
Parámetros no definidos

### ISSUE THREAD

**Issue by cnillanes** [IIC2233/syllabus#335]
Hola! tengo dudas con los parámetros PUNTOS_ENTRENAMIENTO, NIVEL_IMPLEMENTOS y PUNTAJE_MINIMO ya que no se como escribirlos en el archivo porque el enunciado no me entrega valores especificos para esos.

Por otra parte, ya viene escrito uno de POPULARIDAD_MINIMA_DELEGACION y no encontré eso en el enunciado asi que tampoco entendí a que se refiere :( 

Ojalá puedan ayudarme,
Gracias desde ya <3

**Comment by jitorcas** [comment]
Hola! @cnillanes 

Dado que no se le asignan valores a dichos parámetros, es tu responsabilidad llenarlos con valores a tu gusto. Puedes definirlos como cualquier otro parámetro dentro de `parametros.py`.

Con respecto a `POPULARIDAD_MINIMA_DELEGACION` no influye en el programa, así que por el momento no te preocupes por ese parámetro.

Mucho éxito en tu tarea! espero poder haberte ayudado 🥇

**Comment by jarvasquez** [comment]
Los parámetros del pueden escribir como diccionarios? O es necesario que estén explícitos. Por ejemplo.

En vez de anotar:
COSTO_ENTRENAR = ...
COSTO_SANAR = ...
COSTO_MEJORAR_TECNOLOGIA = ...
COSTO_HABILIDAD_IEEE = ...
COSTO_HABILIDAD_DCC = ...

Se puede anotar:
COSTOS = {
    “entrenar” : ...,
    “sanar” : ...,
    “mejor tecnologia” : ...,
    “habilidad IEEE”: ...,
    “habilidad DCC” : ...
}

De esta se pueden ahorrar tiempo al importar los parámetros.

Muchas gracias!

**Comment by jitorcas** [comment]
Hola! @jarvasquez 

Si puedes! 

Éxito en la tarea! 💯🥇
