### ISSUE TITLE
Alimento inicial de Magizoólogo

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#335]
hola, queria saber si se le puede otorgar un alimento predeterminado a cada magizoologo que uno cree. En el enunciado no dice nada sobre eso.

**Comment by moquezada** [comment]
Hola @Juampisaez,

En el enunciado aparece explícitamente  el alimento inicial debe ser aleatorio 🤔

![Captura](https://user-images.githubusercontent.com/43896576/78804120-c3c46880-798d-11ea-8ef2-382df81389e7.PNG)

Saludos!
