### ISSUE TITLE
Problemas con PyQt5

### ISSUE THREAD

**Issue by joaquin-alvarez21** [IIC2233/syllabus#335]
Hola, tengo unos problemas con la instalación de PyQt5, lo que pasa es que instale la extensión por así decirlo, con Pip install PyQt5 en cmd, pero ocurrióun problema al "instalarlo", fui a pedir ayuda a un ayudante ayer, y me explico que no se pudo instalar una versión, pero si lo hizo una alternativa, mi problema es que ahora al momento de importar el modulo PyQt5 me dice que no existe, no sé por qué. 
Cabe recalcar que las carpetas de este módulo están en mi carpeta de anaconda, no se si ahí debe ir o debo moverlas a la carpeta de py.
Estoy atento a tus respuestas, saludos.

**Comment by DCCollao** [comment]
Hola! Todavía tienes problemas de instalación con PyQt5?

**Comment by joaquin-alvarez21** [comment]
No, ya lo resolví, muchas gracias
