### ISSUE TITLE
[materia] definir una señal

### ISSUE THREAD

**Issue by JupaOlivares** [IIC2233/syllabus#335]
Hola!
Tengo una duda de materia. Porque las señales se definen adentro de una clase y fuera del init?

**Comment by JJJGGGG** [comment]
Hola. Las señales se definen fuera del ```__init__```, ya que al definirse cambian la metaclase del QObject en el que se definen. Luego, al crear una nueva instancia del objeto, se crea una nueva instancia de la señal en el QObject instanciado (eso quiere decir que dos QObjects del mismo tipo tienen señales diferentes cuando se llama a ```self.señal```).
