### ISSUE TITLE
casos no especificados parentesco

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#335]
que pasa si no se cumple alguna de las condiciones para parentesco n?? (por ejemplo si la diferencia de altura es > 70 cm) 🤔

**Comment by Hernan4444** [comment]
@rihanuch entonces no tiene parentesco n. (Recuerda que las consultas si pueden dar vacías)
Saludos

**Comment by rihanuch** [comment]
gracias!
