### ISSUE TITLE
[4.2.3 Comandos que retornan un conjunto de datos]

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#335]
De las funciones:
1. extraer_columna: se espera que retorne un generador u otra cosa
2. filtrar: Si por ejemplo se recibe una lista se espera que retorne una lista filtrada, si se recibe un generador se espera un generador filtrado, ..., si se recibe una tupla se pera un set filtrado.
3. operar: misma duda que en 2. pero operando sobre los valores de la columna
4. evaluar: se espera que retorne un generador u otra cosa

Saludos :B

**Comment by Hernan4444** [comment]
@acrojas2 es una pregunta o una afirmación el objetivo de esta issue? :sweat_smile: 

Saludos
