### ISSUE TITLE
Duda sobre DINERO_INTOXICACION

### ISSUE THREAD

**Issue by RodrigoFritis** [IIC2233/syllabus#336]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, mi duda es sobre si el parámetro DINERO_INTOXICACION está establecido por el canal en USD, o irá variando respecto a la moneda del barco. Por ejemplo, un barco puede pagar 10 dolares al canal por medicamentos, como otro barco puede pagar 100 dolares al canal por medicamentos (al hacer la conversion de la moneda de origen). Entonces no sé si tomarlo como un valor constante que debe pagar cada barco o irá variando.
Gracias

**Comment by ivanvlam** [comment]
Hola! No soy ayudante pero en la issue #326 está respondido. Saludos!

**Comment by RodrigoFritis** [comment]
No me queda del todo claro, por eso hice otra issue un poco más detallada sobre mi duda.

**Comment by Emiliax16** [comment]
Hola @RodrigoFritis ! como es un parámetro, debes darle un valor constante. Acabo de corregir mi confusión en la issue [#326](https://github.com/IIC2233/syllabus/issues/326). Vela y dime si ahora te queda más claro.

**Comment by RodrigoFritis** [comment]
Muchas gracias!
