### ISSUE TITLE
Consulta enunciado

### ISSUE THREAD

**Issue by yuwet15** [IIC2233/syllabus#336]
hola, en el enunciado seccion 3.2.1, en la parte de fichar, donde dice _"se deben mostrar todos los deportistas disponibles, dar la opción de seleccionar alguno que no esté fichado por ninguna delegación"_ con todos los deportistas disponibles supongo que se refiere a los que no están fichado por ninguna delegación, está bien eso?

**Comment by amparostevens** [comment]
Hola @yuwet15!
Si, puedes asumir eso

**Comment by yuwet15** [comment]
ok, muchas gracias

**Comment by antoniaalcayaga** [comment]
Hola, tengo una duda respecto a esto mismo, cuando hablan de mostrar a los deportistas, se refieren a el nombre solamente o también sus atributos?

**Comment by amparostevens** [comment]
Hola @antoniaalcayaga!
Queda a criterio tuyo, la idea es que se puede identificar claramente al deportista. 

De todas formas nunca está de más saber algunos atributos (como precio o atributos físicos) para tomar una decisión informada y lograr tener los top deportistas en tu equipo :trophy:
