### ISSUE TITLE
Importar modulos de otros directorios

### ISSUE THREAD

**Issue by maxo2727** [IIC2233/Syllabus#336]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. Estoy teniendo problemas para importar modulos de otros directorios distintos al original. Por ejemplo, en un archivo dentro del backend, quiero importar el archivo de parametros que no está ni en backend ni frontend, solo está en la carpeta T2, pero no puedo importarla. Que se debería hacer en estos casos?

Investigando, encontre que una solución puede ser la siguiente:

```python
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.dirname(CURRENT_DIR))
import parametros
```

Será buena idea implementar esto, o habrá otra manera?

**Comment by Hernan4444** [comment]
Hola @maxo2727 

Podrías echarle un ojo a esta issue donde se consultó por el mismo caso que el tuyo :D

* https://github.com/IIC2233/Syllabus/issues/295

Saludosヾ(＾-＾)ノ
