### ISSUE TITLE
duda input intercambiar jardin

### ISSUE THREAD

**Issue by eldanilop** [IIC2233/Syllabus#336]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, es necesario aseverar que al realizar el input se use   , ; , de forma adecuada simplemente solo hay que chequear que los parametros sean numeros y que esten dentro del rango permitido.

**Comment by PkAlvaro** [comment]
Hola @eldanilop espero que estés teniendo un buen día 😸 

Te comento, el input debe ser en el formato solicitado de , ; , siempre, por lo que eso es parte de lo que debes cuidar que se entregue bien, sumado a esto considerar que las entradas sean enteros válidos con las restricciones dadas en el enunciado, recuerda como manejarlo en caso de que no se cumpla lo requerido.

Espero que te haya quedado más claro.
