### ISSUE TITLE
Suban los archivos porfavor

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#336]
Hola, no me queda muy claro con el enunciado el formato exacto que tendran los archivos, por eso, les pido que suban cuanto antes estos, ya que sin ellos es muy dificil trabajar en la tarea.
Gracias.

**Comment by Hernan4444** [comment]
@nmaturana97 acabo de subir la base de datos. En unas horas (ojalá antes de las 12) subiré algunas consultas con sus resultados ✌️

**Comment by rihanuch** [comment]
@Hernan4444 creo que hay un pequeño error en el archivo 🤔 , sale 

> 5Jesús10De 
Na...

(se corto el apellido con un `\n`)

**Comment by Hernan4444** [comment]
@rihanuch intenta leer el archivo desde python. Ese "salto de linea" es producto de un espacio pero python te dirá que no hay `\n`

**Comment by rihanuch** [comment]
Ok! 👌🏼 muchas gracias!

**Comment by rihanuch** [comment]
@Hernan4444 cero que "Luna Lovegood" tiene un espacio en "Luna ", por lo que su nombre seria "Luna  Lovegood", es un detalle, pero para que se tenga en cuenta 😬

**Comment by Hernan4444** [comment]
@rihanuch efectivamente tiene un espacio adicional (puesto a proposito) y por lo mismo el número de letras de ese gen es 5 🙈.

Saludos ✌️

**Comment by santi95** [comment]
entonces el nombre original de Luna (Con el que se va a hacer el testing) tiene 2 espacios? Solo para aclarar!

gracias!
