### ISSUE TITLE
Comportamiento de Erkling

### ISSUE THREAD

**Issue by benjaguiloff** [IIC2233/syllabus#336]
En el caso de que un Erkling esté hambriento, le robe un alimento a su dueño, ese alimento resulte ser un buñuelo de gusarajo y rechace el alimento, el Erkling va a seguir robando alimentos hasta que efectivamente se coma uno y pase a estar satisfecho? o solamente roba una vez, aunque rechace el buñuelo y siga estando hambriento?

**Comment by mpsubiabre** [comment]
Hola @benjaguiloff !

Muy buena pregunta, para este caso se debe cumplir siempre que robara solo un alimento(en caso de que existan), y cambiara siempre a estar satisfecho. Por esto, si robase Buñuelo de Gusarajo, la probabilidad de rechazo queda anulada. (Podia decirse que esto pasa porque se la come voluntariamente 👀 )

Gracias por la pregunta, no estaba del todo claro :)
