### ISSUE TITLE
Respecto a la encriptación de mensajes

### ISSUE THREAD

**Issue by martina-abello** [IIC2233/Syllabus#336]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Me enredé un poco con el enunciado, y no me queda claro si hay que encriptar/codificar los mensajes que van del cliente al servidor, o los que van del servidor al cliente, o ambos? Y el "mensaje" que se envía qué es, el puntaje o el nombre de usuario o un conjunto...? Considerando que las funciones para codificar y encriptar el mensaje son funciones del servidor.

Lo otro, el orden es primero serializar el mensaje, codificarlo, y luego encriptarlo? o se encripta antes de codificarlo?

Gracias de antemano.

**Comment by iespinazac** [comment]
Hola @martina-abello, debes encriptar y codificar los mensajes que van tanto del cliente al servidor como servidor al cliente. El mensaje que se envía depende de lo que se quiera informar. Por ejemplo, cuando el usuario presiona el botón para comenzar el juego, se debe enviar un mensaje al servidor con el nombre de usuario. Te recomiendo que pienses en una estructura para este mensaje, de forma que quién lo reciba entienda lo que tenga que verificar, actualizar, etc... En cuanto al orden, primero debes encriptar el mensaje y luego codificarlo. Cualquier otra duda, me la comentas 👍
