### ISSUE TITLE
Animales segun edad humana

### ISSUE THREAD

**Issue by IsidoraCarmona** [IIC2233/Syllabus#336]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, para esta función debo ocupar el archivo ponderadores, pero hay especies en este archivo que están mas de una vez con distintos ponderadores, que tengo que hacer en ese caso? probarlo con los 2? 
En el caso por ejemplo que para una misma especie hayan 2 ponderadores distintos y para ambos ponderadores cumpla la condicion, tengo que imprimir su nombre 2 veces? o en caso de que solo cumpla la condicion con un ponderador, lo considero?

**Comment by Jeremiah-PHP6** [comment]
¡Hola! No debería haber más de un único ponderador por especie. ¿Me podrías mostrar las líneas de código donde aparece la misma especie con distintos ponderadores?

**Comment by IsidoraCarmona** [comment]
En ponderadores tamaño s, linea 47 y linea 200 por ejemplo

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Hola! Ví que se subieron varios archivos solucionando problemas, pero me parece que este no fue abordado, no?

**Comment by italocalcutta** [comment]
Hola! No se ha resuelto aun, son varias las especies que tienen mas de un ponderador, lo que genera inconsistencias en los resultados

**Comment by VicenteIgnacioSotoGonzalez** [comment]
> Hola! No se ha resuelto aun, son varias las especies que tienen mas de un ponderador, lo que genera inconsistencias en los resultados

Okas, no hay problema, muchas gracias por la respuesta! :)

**Comment by nicolasoyarcegUC** [comment]
este problema ya se resolvio?

**Comment by Jeremiah-PHP6** [comment]
@nicolasoyarcegUC Efectivamente, en la issue #338 aparecen los cambios hechos a los testcase, donde se corrigieron los ponderadores duplicados. 😃
