### ISSUE TITLE
Ayudantía 4 - Duda decorador pyqtSlot

### ISSUE THREAD

**Issue by dianafuentesc** [IIC2233/syllabus#336]
Hola

Revisando la solucion de la ayudantía 4, me quedo una duda con el rol del decorador pyqtSlot y que hace este con el argumento que se le da. Tampoco entiendo por que puede recibir distintos tipos de almacenamiento de info

Gracias!

**Comment by Dafnemami** [comment]
En la ayudantia dijeron que podíamos omitir el decorador, era solo para hacer más eficiente el programa

**Comment by nabenitez** [comment]
Hola! 
Efectivamente, como dice tu compañera arriba es posible omitir el decorador, que su función es transformar el método a un QtSlot (el que tiene ciertas propiedades que mejoran el comportamiento del programa, puedes revisar más info [aquí](https://www.riverbankcomputing.com/static/Docs/PyQt5/signals_slots.html#the-pyqtslot-decorator)). Su utilización es opcional y raras veces estrictamente necesario, ya que *pyqtSignal*  se puede conectar con cualquier *callable* de python. 
En relación a tu segunda pregunta, ¿a qué te refieres?, agradecería si puedes ser un poco más específica.
Saludos!

**Comment by dianafuentesc** [comment]
Ya respondi la segunda pregunta con el link de la info que mandaste recien, gracias!
