### ISSUE TITLE
Crear una ventana a partir de otras ventanas

### ISSUE THREAD

**Issue by maureenmaremaa** [IIC2233/syllabus#336]
Hola! Estoy intentado crear una ventana que contenga dos subventanas adentro. 
Dentro de esta ventana en el init instancio cada subventana y formo un hbox agregando cada una de estas subventanas mediante .addWidget. La idea es que se vea más o menos así:
Ventana = [[subventana1]     [subventana2]]
Cada subventana funciona bien por separado pero cuando ejecuto para esta ventana que contiene ambas, solo me aparece una. Quería saber si alguien sabe por qué? ¿Podría tener algo que ver con los tamaños de cada uno?
Probé esta idea con ventanas más simples y me funcionó bien pero no sé cuál podría ser el problema acá. Gracias!

**Comment by jaromero6** [comment]
Hola, como bien dices una razón es que los tamaños que definiste para alguna de las dos ventanas hagan que una "quede fuera de la ventana principal", el hbox las alinea, pero no las ajusta automaticamente, solo mueve su posición. Es así como podrías estar mirando solo una ventana, puesto que la segunda que definiste queda fuera de la pantalla, ajusta los tamaños de cada una  con setGeometry prueba a ver si aparecen nuevamente.
En caso de que el problema persista, encontré un problema similar al tuyo [aquí](https://stackoverflow.com/questions/34143233/pyqt-mainwindow-not-showing-widgets)
Espero que te sirva, éxito con la tarea!!

**Comment by maureenmaremaa** [comment]
Muchas gracias por la respuesta, pero aún no logro solucionar mi problema. Fui probando distintos números en el setGeometry y logré hacer que ambas me aparecieran en la misma ventana pero una de ellas no sale completa, sale cortada. También me di cuenta que sin importar los valores que asigne al setGeometry de las dos subventanas éstas se distribuyen equitativamente viéndose así: 
Ventana = [[subventana1][subventana2]]
Me gustaría hacer que una de ellas fuera de mayor tamaño:
Ventana = [[        subventana1        ][subv.2]]
Sabes de alguna otra forma o un comando con el que se pueda realizar esto?

**Comment by jaromero6** [comment]
Primero trataría de ver cuales son las dimensiones de la ventana en que los estás tratando de mostrar ambos widgets, de este modo les podrías asignar a cada uno la medida y posición correcta más fácilmente.
En segundo lugar, para lo que quieres hacer recuerda que los HBox son útiles cuando quieres lograr simetría más fácilemente con los elementos que están en la ventana, dado que no deseas hacer eso, quizás una opción es no usar el HBox y te sería más fácil lograr tener una ventana más grande que la otra.
