### ISSUE TITLE
Duda validación nombre cliente-servidor

### ISSUE THREAD

**Issue by Joako5848** [IIC2233/Syllabus#337]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Recordaba haber subido esta issue ya pero no la encuentro asi que asumo que no

### Validación 
Debido a esta parte del enunciado, el verificar el largo, alfanumerismo y que tenga al menos 1 mayus y 1 num, se hace en el mismo cliente o servidor? pues la funcion que nos hicieron crear era para el cliente y esto refiere al servidor, entonces es medio confuso

![image](https://github.com/IIC2233/Syllabus/assets/130397939/13e0ae03-b0b2-454c-a55e-8a0299d97315)

**Comment by AntonioVenegas** [comment]
Hola @Joako5848!, si bien en esa parte se dice que debe validar y verificar todo, en la parte de ventana de inicio (6.2.1) se dice que el backend del cliente es el que debe verificar el formato del nombre ingresado, mientras que la tarea de revisar si el nombre se encuentra bloquedo la realiza el servidor. Espero eso haya aclarado tu duda :)
