### ISSUE TITLE
Testing funciones que arrojan decimales -T03

### ISSUE THREAD

**Issue by malopez16** [IIC2233/Syllabus#337]
Hola!
Hay alguna manera en la que se solucione el hecho de las aproximaciones decimales al hacer testing?
Por ejemplo, si quiero calcular alguna función y otro programa me tira como resultado 1.0009 de una función aplicada sobre un conjunto de numeros, y mi función en python retorna 1.00089 (obviamente la cantidad de decimales es mucho mayor), podemos hacer round? si es así, con cuántos digitos?

Gracias!

**Comment by Hernan4444** [comment]
@malopez16 puedes redondearlo a los decimales que tu estimes convenientes para que ese problema no te afecte, si el resultado dado es 1.000293 y tu esperabas solo 1.0003, entonces solo redondea al cuarto decimal.

Saludos!!

**Comment by malopez16** [comment]
Gracias!

**Comment by malopez16** [comment]
É

**Comment by malopez16** [comment]
Eso implica que sería en el testing el redondeo , no en la función?

**Comment by Hernan4444** [comment]
seria mejor que fuera en el testing porque al menos los resultados que nosotros esperamos ver es sin redondear nada, dejamos que python sume todo con decimales incluidos.

**Comment by malopez16** [comment]
gracias por la respuesta rápida! Ahora si la cierro :)
