### ISSUE TITLE
Varias dudas de enunciado

### ISSUE THREAD

**Issue by Nicolemarin** [IIC2233/syllabus#337]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Dudas. Disculpen lo larga pero es de enunciado mas que nada

1) En **simular_hora**, dice algo así como: ”En caso de que no haya ningún barco atascado, deberá mostrar lista de barcos para que el usuario seleccione uno, para que éste entre y avance en el canal”.  Mi duda es si en caso de que "no haya ningún barco atascado", **tampoco debería avanzar ningún barco**? o si? no se especifica, asi que se podría asumir que no?

2) Todos los barcos tienen **todas** las cajas de mercancía que vienen en el csv? porque en ningún lugar dicen  condiciones especiales para que una caja de mercancía ingrese a un tipo barco en particular. Lo mismo pasa con tripulantes, todos los barcos tienen **todos** los tripulantes del csv?

3) En **Mostrar_estado**: dice que hay que mostrar la cantidad de barcos que han pasado. Ese “**han pasado**” se refiere a “han entrado” al canal, o “han salido”?

4) No entiendo la diferencia de **Ejecutar_evento_especial(),** con **Evento_especial()** de cada barco, creo que se podría hacer 1 solo que incluya las funciones de los dos, o no?. De todas maneras, si usara ambos métodos, tal cual me indican, tendría que llamar a Evento_Especial() **dentro** del Ejecutar_evento_especial()?

5) tengo duda de materia para esta parte: Cuando llamo un método de una Sub clase, solo debo colocar objeto**Superclase**.metodo()? porque hago esto y no me resulta :( 

6) me enreda el atributo **probabilidad_de_encallar**:

-  ¿es lo mismo que tendencia de encallamiento mencionada en cada tipo de barco?

-  ¿el valor de probabilidad_de_encallar, es la probabilidad que nos retorna el metodo Encallar()?

Muchas gracias de antemano :D

**Comment by DomingoCarvajal** [comment]
Hola @Nicolemarin!

Aunque sean muchas issues igual es bueno que las hagas por separado, para asi poder asignarlas a una seccion en el compilado de issues.

1. Si no hay ningún barco encallado, los barcos deberían poder avanzar libremente.

2. Cada barco tiene una lista de mercancía propia, no va a tener todas las mercancías del archivo. Lo mismo pasa con los tripulantes. Estos vienen definidos en el archivo barcos.csv.

3.  Son los que han salido.

4. No se a que te refieres. En en enunciado sale que hay que definir un método para ejecutar el evento especial, si tu quieres hacer más de un método para esa funcionalidad puedes hacerlo, tienes libertad para implementarlo con tal de que funcione como se pide.
5. Para llamar el método de una subclase en una subclase, se llama como cualquier otro método. objeto.metodo().

6. El atributo probabilidad a encallar es la tendencia a encallar de cada barco, el cual deberás usar en la fórmula del método encallar.
