### ISSUE TITLE
Bonus Super Magizoólogo DocencioTareoHíbrido

### ISSUE THREAD

**Issue by nachobascar** [IIC2233/syllabus#337]
El Magizoólogo pasa a esta super clase cuando su nivel de aprobación es 100?
Porque al crear un nuevo magiziologo y pasar el día, este casi siempre va a terminar con una aprobación de 100, por lo que obtener la super clase sería demasiado fácil.

Además, en las habilidades del super magizoologo, ¿no faltaría la habilidad de Docencio que al alimentar una criatura esta aumenta su salud total en 5?

**Comment by matiasmasjuan** [comment]
Hola @nachobascar !

Aunque es verdad que pueda resultar un poco **"sencillo"** obtener esta ***SuperClase***, es la condición establecida en el enunciado para poder *transformarse*. Recuerda que esta "transformación" solo puede suceder al momento de *pasar al día siguiente*, por lo que al momento de **crear** un **Magizoólogo**, no iniciaría con esta **transformación**. Además, al momento de *pasar al día siguiente*, aún es posible que algunas de tus **DCCriaturas** se escapen, por lo que no **necesariamente** esta *transoformación* sería **inmediata** al pasar recién 1 día.

Con respecto a la segunda pregunta, si bien es cierto que un **Magizoólogo Docencio** tiene la facultad de **aumentar** la salud total de una **DCCriatura** en 5, esto **no** se puede realizar para el **Magizoólogo DocencioTareoHíbrido**, tal como se indíca el enunciado. Sin embargo, **si** pueden utilizar la **habilidad especial** del **Magizoólogo Docencio**.

Espero haber respondido a tu pregunta, y mucho éxito con la tarea!

**Comment by nachobascar** [comment]
Gracias!!

**Comment by matiasmasjuan** [comment]
De nada! Por favor no cierres las issues ya que podrían servir de ayuda para tus demás compañeras y compañeros.
Éxito con la tarea!
