### ISSUE TITLE
Carácteres especiales en genomas

### ISSUE THREAD

**Issue by cjmunoz4** [IIC2233/Syllabus#337]
Hola! Pude darme cuenta de que en el archivo "genomas.txt" hay carácteres especiales en los nombres (tildes), por lo que, al leer letra por letra, es como si los tildes utilizaran una posición extra.  

Por ejemplo, "Jesús" sale como si fuera JesÃºs, por lo que no tendría 5 letras y se estropea el propósito de que nos den la cantidad de letras del nombre de cada individuo. ¿O acaso debemos detectar cuando hay tildes y arreglar el problema manualmente? 

Muchas gracias.

**Comment by Hernan4444** [comment]
@cjmunoz4 tienes que usar el encoding adecuado para poder leer los archivos.
Saludos
