### ISSUE TITLE
Duda sobre sys

### ISSUE THREAD

**Issue by vvialbarros** [IIC2233/Syllabus#337]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Queria saber si la parte del sys (lo que se encarga de recibir el nombre del jardin y el nombre de la dificltad en la consola) tambien debe ser a prueba de errores o se puede asumir que siempre se escribiran bien los datos

**Comment by CrisDonosoMaass** [comment]
Hola! Pueden asumir que siempre vendrá en orden correcto, pero debe ser a prueba de errores en casos que falte un argumento o no exista el mapa dado por ejemplo.

**Comment by ShoshiC** [comment]
Respecto a esto, podemos asumir que los jardines posibles siempre tendrán los nombres escritos en el ejemplo?

**Comment by CrisDonosoMaass** [comment]
> Respecto a esto, podemos asumir que los jardines posibles siempre tendrán los nombres escritos en el ejemplo?

Creo que no entendí tu pregunta, voy a responder lo que creo que te refieres. Para evaluarlos se van a usar los mismos jardines que hay en el archivo .txt, pero en la correción, para validar que se leen bien los archivos, los correctores pueden crear nuevos jardines desde cero con un nombre que no se les da en la data. De esta manera evitamos que harcodeen cada mapa en su código.

**Comment by ShoshiC** [comment]
Ohhh ya me quedo claro. Muchas gracias <3
