### ISSUE TITLE
Atributo privado y clases abstractas

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#337]
¡Hola!

Si uno tiene atributos privados en una clase abstracta: ¿las clases que heredan de esta clase pueden acceder o modificar los atributos privados? ¿O en ese caso es mejor definirlas como protegidas?

Gracias :)

**Comment by Baelfire18** [comment]
Hola, efectivamente la clase hija puede acceder a los atributos ocultos de la madre.
Por ejemplo:
```
from abc import ABC, abstractmethod

class Abstracta(ABC):
  def __init__(self, nombre, zodiaco):
    self.nombre = nombre
    self.__zodiaco = zodiaco

class Humano(Abstracta):
  def __init__(self, nombre, zodiaco, ocupacion):
    super().__init__(nombre, zodiaco)
    self.ocupacion = ocupacion
    self.__zodiaco = "Piscis" #because why not? Todos somos piscis?
  
  @property
  def zodiaco(self):
    return self.__zodiaco

b = Humano("Baelfire", "Leo", "Ingeniero de Software")
print(b.zodiaco)
```
Tendra como output
```Piscis```

En esta caso se pudo acceder al atributo oculto de la madre y es más se pudo sobreescribir.
Dime si a esto iba tu pregunta y si se solucionó!

**Comment by amahns1** [comment]
Perfecto :)

Muchas gracias!!

**Comment by Baelfire18** [comment]
De nada!
