### ISSUE TITLE
Duda > y < en comentarios

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#337]
Hola! Dos consultas sobre los comentarios/reviews... 

1. Puedo asumir que para cada "<" habrá un ">" que lo "cierre"? Me refiero a que no me encontraré con casos como:
`"thismovie was truelygreat </p> <"`
`"</p> it was purrfect >>"`

2. Puedo asumir que no habrán pares de "<>" dentro de otro par "<>"? Por ejemplo:
`"I would love to see a second part for The Adventures Of The Amazing Professor Cristian Ruz<</p>>"`
`"<When's the release of The Ayudantes of Avanzada: Python Wars? </p>>"`

**Comment by iqacevedo** [comment]
Hola, 

1-. No puedes asumirlo, si falta "<" o ">" no tendrías un tag cerrado, por tanto nada que eliminar.
2-. No deberían existir en las bases de datos que les dimos. Si llegara a aparecer algo de ese estilo simplemente se eliminaría el tag de más afuera (con todo en su interior).

Saludos !

**Comment by IchottMano** [comment]
@auirarrazaval  Hola!

No, no pueden asumirlo.

Saludos!
