### ISSUE TITLE
Archivos - Selector de opciones

### ISSUE THREAD

**Issue by yisidoramolina** [IIC2233/Syllabus#337]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, me surgio la duda si cuando revisen la tarea, la carpera 'mapas' cambiará o si los archivos variaran en nombres, ya que por ejp mi selector es especifico con los nombres actuales de la carpeta

**Comment by Hernan4444** [comment]
Hola @yisidoramolina 

Te confirmo que los archivos si cambiarán. Lo esperado es que el selector se ajuste a los archivos que estén en dicha carpeta. Por este mismo motivo el enunciado incluye el siguiente texto

>  puedes hacer uso de la librería os para obtener esta información. 

Con dicha librería (+ investigar el comando específico) se puede obtener los nombres de forma automática.

Saludosヾ(＾-＾)ノ

**Comment by ooscarr** [comment]
mas información de os en https://github.com/IIC2233/contenidos/blob/main/semana-00/3-paths.ipynb
