### ISSUE TITLE
Movimiento en grillas

### ISSUE THREAD

**Issue by JupaOlivares** [IIC2233/syllabus#337]
Hola!
 Para mover un objeto en una grilla estoy ocupando un metodo de stackoverflow que basicamente remueve el objeto y lo agrega nuevamente en la nueva posicion, pero esto me conlleva a que no pueda implementar animaciones o que al ser muchos enemigos la grilla me tire error, existe algun otro metodo o estructura que pueda implementarse que soporte movimiento con animacion y/o no implique remover y volver a agregar el objeto para moverlo?

Gracias!

**Comment by jaromero6** [comment]
Hola, puedes simplemente colocar un label sobre la grilla e ir moviendo este label, de este modo vas dejando la grilla tal como está y con este label si es posible agregar animación al movimiento. Si es que este al entrar a la grilla queda por debajo de esta (y por ende no se ve), te recomiendo ver lo que se habla en la issue #225 o [aquí](https://stackoverflow.com/questions/21190340/how-to-display-a-qlabel-under-another-qlabel) acerca del método **raise**
Espero te sirva
