### ISSUE TITLE
variables de modulo?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#338]
Digamos tengo un modulo que tiene funciones que usan un archivo constantemente. Puedo guardar de manera global como `string`, ese archivo :page_with_curl:?
Pregunto, por la filosofía de _“Do one thing and do it well”_, dado que se busca hacer funciones de 
lineas <= 15, entonces se podría considerar como trampa ❌

**Comment by rihanuch** [comment]
¡Hola @naquiroz !

Cuando dices:

> guardar de manera global como ```string```, ese archivo 📃

¿A qué te refieres con eso? 🤔

**Comment by naquiroz** [comment]
Hola @rihanuch !

Con eso me refiero a lo siguiente:

```Python
with open('something.txt', encoding='utf-8') as file:
    the_file = file.read().splitlines()

def is_in_file(word: str) -> bool:
    for line in the_file:
        if word in line:
            return True
    return False

def edit_line(initial: str, final: str):
    for i, line in enumerate(the_file):
        if line == initial:
            the_file[i] = final
            break
```

Como se puede ver en el ejemplo, existe una variable que se usa a lo largo de varias funciones, y pero técnicamente no está en ninguna función. Esto está permitido?

**Comment by rihanuch** [comment]
@naquiroz , se puede hacer lo que dices, _**siempre y cuando**_ se siga lo siguiente ⚠️:

1. Hacerlo la **menor cantidad de veces posible**, porque no en general es muy mala práctica
2. **Declarar que son constantes** de manera adecuada, esto implica seguir PEP8, de la forma ```NOMBRE_CONSTANTE = data``` 👀
3. Mantener en mente que la idea de esas constantes es **no modificarlas**, ya que el propósito es que sean _constantes_ (tal como indica su nombre)

Supongo que no lo hiciste de adrede, pero también es importante mencionar que en tus ejemplos estas haciendo **uso indebido** 🚨 de los ```for```, ya que en ambos casos se pueden realizar las mismas funciones mediante un ```map```

¡Saludos y éxito! 🍀

**Comment by naquiroz** [comment]
@rihanuch Gracias! Respecto a 
2. Que pasa si la cosntante es una named tuple? Igual el nombre debe ser en mayusculas?

**Comment by rihanuch** [comment]
@naquiroz ,

Según la [guía de estilo de PEP8](https://www.python.org/dev/peps/pep-0008/#naming-conventions)
> Constants are usually defined on a module level and written in all capital letters with underscores separating words. Examples include MAX_OVERFLOW and TOTAL.

Por lo tanto sí, debe ser en mayúsculas 🔠

Ojo que tienes que tener en consideración que en la vida real __no debes__ ❌ guardar toda la información que está siendo utilizada en la memoria RAM, ya que de ser así tendrías que tener mucha más de la que se puede tener (por ejemplo si trabajas con una base de datos de índices económicos)

¡Suerte! 🍀

**Comment by rihanuch** [comment]
@naquiroz , no se si lo alcanzaste a leer antes del EDIT, pero me había equivocado 😬
