### ISSUE TITLE
Movimiento animado enemigos

### ISSUE THREAD

**Issue by bvallejo1** [IIC2233/syllabus#338]
Hola, puede pasar que desde el back end estén ejecutándose n threads y cada uno de estos threads esté mandando una señal al front end para actualizar su posición? La clase del front end soportaría las peticiones de todos estos threads simultáneos?
Además como podría identificar al enemigo (Thread) al cual quiero actualizar su posición en el front end?

Muchas gracias.

**Comment by jaromero6** [comment]
Hola
Efectivamente lo que dices es factible de hacer, obviamente si hay muchos enemigos esto genera más carga en el computador, pero con un número razonable de enemigos no debería causar problemas.
Respecto a como identificar a que thread corresponde un enemigo un forma es con el método [__eq__](https://devinpractice.com/2016/11/29/python-objects-comparison/). Otra forma también si es que eso te da problemas es la siguiente:
```
class Enemigo(QThread)
         enemigo_id = 0
         def __init__(....)
                 Haces todo lo que tengas que hacer en este init
                 self.mi_id = Enemigo.enemigo_id
                 Enemigo.enemigo_id += 1             
```
Con esto logras ya que cada thread tenga un id único, simplemente después mediante una señal por ejemplo cuando cada thread termine puedes mandar su id, luego ya depende de ti, sabiendo que este id será único como buscarlo. Si desconoces como funciona ese enemigo_id te recomiendo ver este [link](https://es.stackoverflow.com/questions/132561/diferencia-entre-atributos-de-instancia-y-atributos-de-clase).  Cabe resaltar que esta **no** es la única forma de obtener la referencia a un thread (por ejemplo también podrías guardarlos en una lista y [preguntarles sin terminaron](https://doc.qt.io/qt-5/qthread.html) ) existen muchas más y cual es la mejor, bueno dependerá de que es lo que busques hacer exactamente.
**Atención**: Asumí que te referías a los QThreads, ya que dado que están usando PyQt5, se recomienda fuertemente usar uno de estos para no generar conflictos entre threads de python y de PyQt. Si tienes dudas respecto a los Threads de python puedes ir a los contenidos.
Espero te sea de utilidad
