### ISSUE TITLE
Archivos csv: Magizoólogo con criatura inexistente

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#338]
Hola! Un mago tiene una criatura llamada "Felie" pero esta no se encuentra en el achivo criaturas.csv. ¿Qué hago?

**Comment by aljara97** [comment]
Hola @CataSudo!

Como te puedes fijar sí existe una criatura de nombre "Felie", esta se encuentra en la fila 6 del archivo `criaturas.csv`. Probablemente éstas trabajando con una versión antigua de estos archivos, los que hemos actualizado de acuerdo a los errores que han detectado.

Adjunto un pantallazo 
![Screenshot_20200408_133246_com android chrome](https://user-images.githubusercontent.com/42227563/78815342-21f94780-799e-11ea-8562-10b5f6fd0804.jpg)
