### ISSUE TITLE
Orden tags de características en genomas.txt

### ISSUE THREAD

**Issue by jerosalazar** [IIC2233/Syllabus#338]
¿Es posible asumir que para cada linea del archivo gemonas.txt el orden de los tags de características de cada persona siguen siempre el mismo orden (orden del cuadro 1 en el enunciado: AAG, GTC, GGA...)?

**Comment by indonoso** [comment]
Te refieres al orden en que aparecen en el header, cierto? No siempre vendrán en el mismo orden.
