### ISSUE TITLE
Equivocación actividad 5

### ISSUE THREAD

**Issue by Zapararte** [IIC2233/syllabus#338]
Al enviar el último commit de mi actividad 5, se produce un error porque escribí la _key_ del diccionario como "msj" en vez de "msg". Al cambiar esta letra el programa se puede ejecutar correctamente. ¿Cabe la posibilidad de que se pueda realizar este cambio, quizás con un descuento asociado? Subí un archivo al repo de mi actividad en donde indico la línea en la que se ubica el error.

**Comment by Drpinto1** [comment]
¡Hola!

Al momento de corregir las actividades, en caso de que esta no se ejecute correctamente, el ayudante intentará ver si existe algún error de sintaxis (pequeño y fácil de arreglar) e intentará corregirlo para poder hacer funcionar el código.

La "reparación" del código puede o no venir con un descuento asociado dependiendo del error, pero es lo más probable es que la situación que cuentas sea detectada y arreglada por tu corrector.
Dicho esto, si el ayudante que revisa tu actividad no se percata del error, luego de que se entreguen las notas podrás solicitar la recorrección de tu actividad y ahí podrás describir en detalle que (pequeños) cambios se pueden/deben hacer para arreglar el código.

Saludos :D

**Comment by Zapararte** [comment]
Perfecto! Gracias por la información! :)
