### ISSUE TITLE
Problema instalación PyQt6

### ISSUE THREAD

**Issue by rkongr** [IIC2233/Syllabus#338]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Tengo problemas a instalar PyQt6, me aparece lo siguiente:
![Captura de pantalla 2023-10-31 143039](https://github.com/IIC2233/Syllabus/assets/106290684/2a5c032d-9f16-4b10-bb95-12965c0b2116)

**Comment by vicente999** [comment]
Ese mensaje te dice que ya tienes instalado pyqt6 y esta en la ruta usr/local/lib/python3.10/dist-package, podrías intentar correr tu codigo en Visual teniendo como intérprete python 10, que es el que tiene instalado pyqt6

**Comment by vicente999** [comment]
Eso te puede pasar (me paso a mi jajaja) porque tienes por defecto otra libreria o version de python por encima de la version 10 o un pytq distinto al 6
