### ISSUE TITLE
funciones de probabilidad y comando evaluar

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#338]
En las funciones gamma, exponencial y normal, ¿los parametros pueden ser float? (A excepcion de k en la gamma ya que se nota que no puede porque se usa en un factorial)

**Comment by Hernan4444** [comment]
@jorgeriesco si pueden ser :+1: 
Saludos!

**Comment by jorgeriesco** [comment]
¿Estas funciones de probabilidad solo pueden ser usadas desde evaluar funcion? ¿o se pueden consultar directamente pr el usuario?

**Comment by Hernan4444** [comment]
exactamente!! con `crear_funcion` creamos una de las 3 funciones y con `evaluar` creamos una columna de datos con la evaluación de dicha funcion, no hay otra forma :+1: 

Saludos!

**Comment by jorgeriesco** [comment]
otra:
En evaluar, al ingresar funcion, ¿Se ingresa como str o como digitos que representan la funcion sin estar entre comillas?

**Comment by Hernan4444** [comment]
puedes dar un ejemplo, no entiendo muy bien tu pregunta.

**Comment by jorgeriesco** [comment]
["evaluar", "normal", 1, 10, 3] ¿esta bien? es decir, ¿normal debe estar entre comillas?

**Comment by Hernan4444** [comment]
aaa nonono, el segundo comando es una función. Por lo tanto tenemos dos formas:
```
[’evaluar’, [’crear funcion’, ’normal’, 0, 0.5], -3, 5, 0.1]
```

`crear función` creará una función Normal de parametros 0 y 0.5. --> RETORNA una función
`evaluar `tomará un objeto función y la evalúa desde -3 hasta 5 con un intervalo de 0.1 

la otra opcion es que hayas echo
```
["asignar",  "variable", [’crear funcion’, ’normal’, 0, 0.5]] -> Guardas como variable, la funcion normal
["evaluar", "variable", -3, 5, 0.1]
```

Ambas formas hacen exactamente lo mismo, en la primera el argumento fue otra consulta que retorna un objeto función mientras que en la segunda guardas ese objeto dentro de una variable y luego lo llamas en evaluar,

**Comment by jorgeriesco** [comment]
Perfecto

**Comment by jorgeriesco** [comment]
¿Tiene algún sentido crear una función sin asignarla a una variable o usarla directamente en evaluar?

**Comment by Hernan4444** [comment]
crear una funcion sin asignarla no tendrá ningun sentido (y tampoco haremos consultas que solos pidan crear una funcion sin guardarla), usarla directamente en evaluar como el ejemplo 1 es simplemente para no gastar memoria en almacenar una función que no queremos usar mas veces
