### ISSUE TITLE
rama master

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2233/syllabus#338]
A qué se refiere la rama master de nuestro repositorio personal. Está bien subir la tarea a la carpeta T01 de nuestro repositorio, es lo mismo que rama master?

**Comment by itmunoz** [comment]
Hola! Los repositorios de Github parten con una rama master y a menos de que crees otra rama, todos los commit que hagas irán a la rama master. (Y sí, subir la tarea a la carpeta T01 de tu repositorio está bien).
Para explicar un poco las ramas, imagina que cada rama es una copia independiente de tu repositorio de Github, y que modificar una rama no afecta al resto. El uso de ramas se usa mayoritariamente en trabajos de equipo, para que el trabajo de un integrante no interfiera con el trabajo de otro. Así que en Progra Avanzada no es necesario crear ramas alternas, y usar la rama master es suficiente.
Para comprobar que en tu repositorio estás en la rama master, esto se puede ver en la esquina superior izquierda, donde debería decir "master".
![image](https://user-images.githubusercontent.com/62030415/92314998-a1bb2a80-efad-11ea-82ba-588b0ccc5aae.png)
