### ISSUE TITLE
Duda sobre uso de ambos canales en una misma simulación

### ISSUE THREAD

**Issue by ignaciaurrutia** [IIC2233/syllabus#338]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, he hecho casi toda la tarea basándome en que cuando se inicia una simulación, solo se simula uno de los canales, pero ahora me surgió la duda de si en una misma simulación se puede cambiar de canal y hacer acciones en el segundo. Gracias

**Comment by DomingoCarvajal** [comment]
Hola @ignaciaurrutia!

Puedes asumir que solo se usará un canal para cada simulación.
