### ISSUE TITLE
duda RED_ATQ fensaulantro

### ISSUE THREAD

**Issue by SebaAgusto** [IIC2233/Syllabus#338]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola buenas, RED_ATQ es un parametro que reduce el nivel de ataque de los zombies.. pero a que se refiere con "nivel de ataque"? a la cantidad de zombies por oleada? reduce daño en un x%? o como? Gracias de antemano :)

**Comment by AndreaVict** [comment]
Holaa, RED_ATQ se refiere a la reducción del parámetro _ataque_ de los zombies el cual es utilizado para determinar el daño que generan estos a las plantas. Además, recuerda que RED_ATQ corresponde a un float que va desde el 0 al 1. Éxito en la tarea!!

**Comment by SebaAgusto** [comment]
graciasss
