### ISSUE TITLE
Salón de la fama - ¿Actualización constante en la ventana de inicio?

### ISSUE THREAD

**Issue by benjaminsalgado** [IIC2233/Syllabus#339]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, para el salón de la fama, la actualización del mismo, por cada cliente, es una vez (al inicio de su ejecución) o tiene que, cada cierto tiempo, chequear la lista de puntajes e ir enviandolos a cada uno de los clientes? Ej: Inicio sesión con un cliente (cliente 1) y, al momento de hacerlo, el Jugador1 esta primero con 2000 puntos. Si mientras estoy en esa ventana de inicio otro usuario (cliente 2) logra conseguir 3000 puntos, los cuales son enviados al servidor y este los guarda, ¿el cliente 1 debería actualizar el Qlabel que muestra esta información o esta actualización se vería reflejada ya para otro cliente (cliente 3) al momento de iniciar la ventana de inicio?

**Comment by AntonioVenegas** [comment]
Hola @benjaminsalgado, la idea es que la información del salón de la fama se vaya actualizando a medida que la lista de los mejores puntajes vaya cambiando. En tu ejemplo, cliente 1 debería actualizar su salón de la fama, mientras que cliente 3 debería verlo ya actualizado.

Saludos :)

**Comment by benjaminsalgado** [comment]
Hola, le consulte a una profesora hoy en la programatón, y entendí que esto no era así, y que el cambio solo se vería reflejado en el cliente 3, dentro del ejemplo. ¿Qué tengo que seguir?

**Comment by AntonioVenegas** [comment]
Hola, si la profe te dijo eso, entonces hubo una confusión por parte mía, mil disculpas.
