### ISSUE TITLE
Imagenes para casillas en blanco y de donde nace la cantidad de entidades

### ISSUE THREAD

**Issue by camiloEscorza** [IIC2233/Syllabus#339]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
2 Preguntas: Los espacios vacios quedan a mi criterio colorearlos o hay alguna imagen que hay que usar?
De donde nacen las cantidades que tenemos para poner las entidades?, por ejemplo 1 Luigi, 5 paredes, etc. Lo pongo en parametros.py?

**Comment by ignaciovita** [comment]
Hola! Como no hay un sprite o imagen para las celdas vacías, tu decides cómo las muestras en la interfaz (una opción es como dices, utilizando algún color). 

Por otro lado, las cantidades máximas que se pueden poner en el modo constructor para cada entidad las debes definir tu y establecerlas como parámetros. Esto sale explicado en la sección 3.1 del enunciado. La única restricción es que esta cantidad máxima debe ser 1 para el caso de Luigi y también para la Estrella.
