### ISSUE TITLE
Duda sobre distribucion puntajes

### ISSUE THREAD

**Issue by vvialbarros** [IIC2233/Syllabus#339]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Estaba leyendo el excel de distribucion de puntajes y note que hay un item que hablan sobre un "menu tienda" que es ese menu? porque nunca se menciona en el enunciado

**Comment by AndreaVict** [comment]
Holaa, se refiere al menú del jardín. Saludos!!
