### ISSUE TITLE
Duda función recursiva-circular

### ISSUE THREAD

**Issue by cho19** [IIC2233/Syllabus#339]
Hola, 

Tengo una duda, trataré de no dar mucho detalle con el ejemplo: supongamos tengo una función recursiva que recorre un elemento y llama a la función en alguno de sus argumentos, con el uso normal de `for` se vería así (quizás hay algo mal, mi código no hace exactamente esto):

<img width="242" alt="captura de pantalla 2017-04-28 a la s 21 39 42" src="https://cloud.githubusercontent.com/assets/14133074/25551430/3b039d68-2c5b-11e7-8cd6-b72c9f074b83.png">

Si quiero dejarla como listas por comprensión (spoiler), me veo obligado (**creo**) a crear otra `funcion()` que contenga esas instrucciones y ejecutarla en lo que va dentro de la lista por comprensión, por lo que al llamar a `recursion()`, llamaría a `funcion()` que retornaría `recursion()` y así. 

¿Esto es considerado una función circular? Parece bastante obvio que si, pero pregunto por qué al hacer una recursion (que una función se llame a si misma) me veo obligado a hacer algo circular y, usando `for` normales, nunca llamaría a la funcion(), sería una recursion normal. 

Saludos y gracias!

**Comment by Hernan4444** [comment]
@cho19 hacer una recursión donde una función se llame a si misma si está permitido, lo que se prohibió es que una función X llame a otra Z y esta llame a X nuevamente. En #307 se preguntó algo similar para que lo revises. Y en tu caso, si.. se considera función circular lo que nos explicas. Te sugiero que intentes darle otra vuelta al problema e intentar enfrentarlo desde otra perspectiva

Saludos!!

**Comment by cho19** [comment]
Uhh, ya, gracias!
