### ISSUE TITLE
Autoevaluación AC05

### ISSUE THREAD

**Issue by mpbascunan** [IIC2233/syllabus#339]
Donde está el link para realizar la autoevaluación?

**Comment by Drpinto1** [comment]
¡Hola!

La idea de la autoevaluación es que puedan tener un cálculo estimado de la nota que tendrían en la **actividad formativa** correspondiente, por lo que, en particular para esta actividad y también para todas las **actividades sumativas** no existe el form de auto evaluación, pues su actividad será corregida por un ayudante y tendrán su nota y feedback individual de la actividad.

Saludos :D
