### ISSUE TITLE
Funciones dentro de funciones

### ISSUE THREAD

**Issue by DquezadaO** [IIC2233/Syllabus#339]
Si defino una función adentro de otra como funciona el tema del límite de lineas de las funciones? porque quiero que mi función solo la pueda ver la función padre pero juntas tienen más de 15 lineas entre ambas

**Comment by sebacruzd** [comment]
Hola, 

Como la función hija es parte de la función grande, aún así cuenta dentro de las 15 líneas. 
Sino, habría un vacío legal y podrían haber funciones de mucho más de 15 líneas si se abusa esto.

Saludos.

**Comment by DquezadaO** [comment]
@sebacruzd Entonces tengo que crearla fuera? pero no sería exactamente lo mismo definirla afuera como otra función distinta y llamarla únicamente en esa función? Lo decía por un tema de orden. 🤔  O las funciones que creemos necesariamente tienen que ser llamadas más de una vez? Y si es así, si necesito una función episódica (que voy a usar una pura vez), Deberé usar una lambda de varios pasos? Porque yo encuentro que hacer una lambda de 13 lineas, que como dijeron en la issue #333 que cuenta como 1, no tiene mucho sentido, para eso mejor uso def.

**Comment by Hernan4444** [comment]
@DquezadaO lamento la demora, la primera vale como 1 porque en sentido estricto, es una linea de código que será cortada por PEP8 mientras que la otra no. 
¿Cual es el riesgo de la primera forma?

![image](https://user-images.githubusercontent.com/15641721/31075308-413fd85c-a74b-11e7-9e74-5be00dfeb802.png)

Te exponen a que el ayudante no entienda que estás haciendo y aplique descuento por código poco claro.
De la segunda forma se muuucho más entendible que estás intentando hacer.

Saludos ✌️
