### ISSUE TITLE
Formato de entrada de la consulta

### ISSUE THREAD

**Issue by Panckx** [IIC2233/Syllabus#339]
Hola! Cuando en la interfaz se decide procesar alguna consulta, por detrás recibiremos un string con forma de lista y todos los elementos? O recibiremos efectivamente una lista donde, por ejemplo, si uno de los parámetros entregados es un número, obtendré efectivamente un número y no un string con el número? No sé si se entiende la duda...

**Comment by IchottMano** [comment]
@Panckx Hola!

Puedes ver eso fácilmente printeando lo que te entrega la lista en el archivo que entregamos y si no te queda muy claro puedes usar type() para ver su tipo.

Saludos!
