### ISSUE TITLE
Duda formato Alimentos

### ISSUE THREAD

**Issue by mpenalozag** [IIC2233/syllabus#339]
Es necesario que los alimentos sean clases ? Que pasa si mi programa funciona sin tener los alimentos como clases ? 
Gracias de antemano

**Comment by Dnpoblete** [comment]
Hola @mpenalozag como esta tarea es sobre OOP (programación orientada a objetos), esperamos que sean capaces de modelar clases, e identificar cuales deberían ser modeladas como tal.  Por lo cual no podríamos decirte que si o no.

Éxito con la tarea! 😄
