### ISSUE TITLE
error de caracteres pero en git bash

### ISSUE THREAD

**Issue by cseverino99** [IIC2233/syllabus#339]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, en una de las actividades me dijeron que una buena manera de correr mi código era mediante git bash, ya que aveces vs code no corria bien, pero cuando imprimo ciertas palabas en gitbash los tildes no se imprimen bien algo asi como: 'petr▒leo' pero cuando lo imprimo en vs code este si sale de manera correcta 'petróleo', es motivo para preocuparme o debo considerar que mi codigo funciones en vs code?
Gracias

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Emiliax16** [comment]
Hola @cseverino99  ! no te preocupes por eso. Nosotres corregimos desde nuestros editores, por lo que deberíamos ver exactamente lo que te imprime a ti en la consola de vscode! 

Saludos c:
