### ISSUE TITLE
Creación de Personas.

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#34]
En la página 9, punto 5 opción 3 de acciones posibles, se señala 
**"Posteriormente la persona aparecerán al inicio del turno siguiente."**, Mi duda es, ¿se puede crear más de una persona? además en el ejemplo del archivo:  6.1.4. acciones pendientes.csv, se ejemplifica con **"27,2,ayudante,3"**, siendo que se supone que las personas aparecen el turno siguiente entonces el 3 de al final no debería ser un "1"?

**Comment by jmwielandt** [comment]
Sí, puedes crear tantas personas en un mismo turno como tus recursos te lo permitan, pero aparecerán el turno siguiente.

**Comment by iqacevedo** [comment]
Hola !

Respecto a la segunda pregunta, efectivamente era un error en el ejemplo. Acabamos de actualizar el enunciado arreglando este error. 

Una persona se demora un turno en crearse. Los edificios pueden demorarse más de un día, dependiendo de lo indicado en edificios.csv.

Saludos !

**Comment by perezpefaur** [comment]
Para no crear un nuevo issue, es del mismo tema, pero pregunta distinta. En la sección 5, punteo 3. Donde dice creación de personas, esta dice que tengo que considerar los edificios creados, cantidad de recursos actuales y cantidad máxima de personas de la civilización. No encuentro en ningún lugar cuantos recursos cuesta un trabajador por ejemplo o un ayudante o soldado. Si no cuestan recursos, no tendría sentido el juego.  Si esta perdon de antemano pero me lo lei tres veces el doc.

**Comment by Arcoirisky** [comment]
Hola! 
Esa información está en edificios.csv (sección 6.1.2)

**Comment by perezpefaur** [comment]
Muchas gracias! Donde dice "oro necesario para producir una persona" y despues "madera necesario para producir una persona"  y después con piedra. Hay que pagar de los tres materiales? O puedo elegir entre pagar con oro, madera o piedra?

**Comment by Arcoirisky** [comment]
Debes pagar de los tres materiales O:! Si te falta aunque sea una unidad de cualquiera de ellos según el precio, entonces no puedes comprar nada :(
