### ISSUE TITLE
No entiendo utilidad Clases Abstractas

### ISSUE THREAD

**Issue by glbello** [IIC2233/Syllabus#34]
Saludos, después de indagar en internet, sigo sin poder entender la utilidad que tienen las clases abstractas respecto a que tenga métodos abstractos, entiendo que por ejemplo tenga la clase Vehiculo que sería la clase abstracta y que de estas hereden por decir Auto, Moto, Camion, etc. pero que utilidad tendría yo con darle métodos abstractos a la clase Vehiculo si estas no serán usadas ya que para Auto, Moto u otro, a esas clases les daré métodos que pueda usar, pero de la clase Vehiculo no podré usar ningun método porque... son abstractos, esto también aplica mi duda con las property abstractas. 

Lo que sale en la materia: "La principal razón de las clases abstractas es ahorrarnos el repetir las variables y métodos que compartirían todas sus subclases"... de acuerdo pero si estos tienen métodos abstractos, de igual manera tendré que nuevamente definirlos en las subclases para poder usarlas según lo que entiendo.

**Comment by jorgeriesco** [comment]
Primero que todo es importante entenderlo como concepto, lo que me parece que si entiendes. Luego si impones en tu programa que sea abstracta o no, es prácticamente lo mismo. La única diferencia entre imponer que es abstracto y no hacerlo es que al imponer no puedes instanciar la clase abstracta, es decir, tira error. Te parecerá que esto no tiene sentido porque tu eres el único que ve tu programa y lo cambia y no necesitas imponer que una clase abstracta sea abstracta, pero como dijeron en clases, es bueno tener la buena costumbre para proyectos futuros en los que trabajes en equipo o incluso puedas entender mejor tu propio código después de no haberlo visto por un tiempo. Lo mismo con los métodos.

**Comment by glbello** [comment]
PD: ¿Puedo tener métodos y property que no sean abstracta en una clase abstracta? Tomando el ejemplo de la actividad 02, cuando decía que la clase Personality tuviera el método react(plate), yo establecí que la clase Personality fuera abstracta y que sus subclases fueran Cool y Hater... si react(plate) fuera abstracta no me habría sido posible usarla, por lo que no la hice abstracta el método react, ¿es indebido o poco formal hacer eso?

**Comment by jorgeriesco** [comment]
Las clases abstractas son necesarias no por su condicion de abstracta, sino por su condicion de potencial padre de otras clases, las cuales todas tienen en comun los atributos y metodos que heredan del padre y además es posible especializarlas agrgando metodos o atributos o cambiando los mismos. Esto es util porque de esta manera el codigo tiene una logica más entendible para cualquier lector y además el programador ahorra escritura, ya que no tiene que escribir los mismos atributos y metodos reiteradas veces para distintas clases. 
Como dije no es necesario que sean abstractas. El hecho de imponer en el programa que una clase sea abstracta solo hace que si se quiere instanicar dicha clase, el programa tirará error. Si no se impone que sea abstracta, no pasa nada, pero es buena costumbre hacerlo para proyectos futuros en los que se trabaje en equipo y además el codigo sea más entendible para cualquier lector.

**Comment by glbello** [comment]
Comprendo, gracias por responder, aunque aun me hace ruido lo que mencionas en el último párrafo, o tal vez entendí mal, por ejemplo:

```python
from abc import ABCMeta, abstractmethod

class Personality(metaclass=ABCMeta):
    @abstractmethod
    def react(self):
        print("react de Property")
class Client(Personality):
    pass

bob = Client()
bob.react()
```
Al ejecutarlo me dará error ya que me dirá que es un método abstracto, pero si defino el método react() en Client, ahí si resultaría pero desde ya tuve que definir nuevamente el método react en la subclase, por lo que no deja de ser abstracta el método react hasta que la redefina en Client, lo que en la actividad me habría sido imposible pasar a llevar la restricción que solo debía definir el método react en Personality

**Comment by jorgeriesco** [comment]
Ahí no estoy seguro (no soy ayudante), pero te recomiendo poner eso en python y probar que pasa.

**Comment by glbello** [comment]
si si lo probé, por eso preguntaba, de cualquier forma agradesco tu tiempo para aclarar mi duda

**Comment by MainScientist** [comment]
Una clase abstracta permite entregar un "molde" para las demás clases que hereden de esta, pero que por sí sola no tiene sentido (es decir, no sirve como instancia). Así mismo una clase abstracta puede entregar métodos abstractos, estos métodos se encuentran vacíos y las clases que heredan de esta clase abstracta **deben** implementar estos métodos. A la vez las clases abstractas pueden tener métodos que no son abstractos, estos métodos por lo general definen un comportamiento que es común a todas las clases que heredan de la clase abstracta.

Para explicarlo mejor pondré el siguiente ejemplo:

```python
class Auto:
    pass

class Avion:
    pass

class Fabrica(metaclass=ABCMeta):
    def fabricar(self, n):
        l = []
        for i in range(n):
            l.append(self.nuevo())
        return l

    @abstractmethod
    def nuevo(self):
        pass

class FabricaAuto(Fabrica):
    def nuevo(self):
        return Auto()

class FabricaAvion(Fabrica):
    def nuevo(self):
        return Avion()
```

En este ejemplo puedes ver como la clase `Fabrica` es abstracta, debido a que una fabrica por si sola no tiene sentido, para que tenga sentido necesita tener algo que fabricar (esto hace concreto el término abstracto de una Fabrica). Sin embargo, la clase `Fabrica` aun al ser abstracta, define un comportamiento común a todas las fábricas, que es fabricar n objetos con el metodo `fabricar`. El método `nuevo` es abstracto, ya que depende de cada fábrica cual va a ser su objeto a fabricar.

Como puedes ver, las clases `FabricaAuto` y `FabricaAvion` son concretizaciones de la clase `Fabrica`, y por esto **deben** implementar el metodo `nuevo` el cual debe retornar una instancia del objeto a fabricar.

Las clases abstractas sirven para entregar una *idea* o un comportmiento comun a una serie de objetos que, posteriormente van a ser distintos entre sí (una fabrica de autos y una fabrica de aviones son distintas, pero comparten el concepto abstracto y los comportamientos de una fabrica) y así no repetir código (en este caso el metodo `fabricar`).

No sé si me habré explicado con claridad, es un concepto difícil de digerir en un principio, pero que en el fondo es bastante simple.

**Comment by glbello** [comment]
@MainScientist Perfecto! ahora entiendo a cabalidad, y responde a mi duda si podia o no tener métodos abstracto una clase abstracta, mil gracias por la detallada explicación.
<p style="text-align:center;"><img src="http://generadordememesonline.com/media/created/70rwal.jpg" height="128px" /></p>
