### ISSUE TITLE
Notación 'variable_'

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#34]
Hola!

En el notebook `contenidos/semana-01/2-listas-tuplas.ipynb`, subtítulo `Slicing de listas`, celda `In [21]`, hay un atributo de clase etiquetado como `Pieza.id_`. Como nunca había visto la notación de poner el guión bajo al final de la variable, me preguntaba **si esa es una convención para atributos de clase, y si es general para Python o específicamente PEP8**.

Muchas gracias de antemanooo 🥰

**Comment by amparostevens** [comment]
Hola @sbcorrea!

El intérprete de Python tiene una serie de funciones y tipos incluidos en él que están siempre disponibles, los que se conocen como __built-in functions__. Entre ellos se encuentra la función ```id(object)```, por lo cual al momento de definir el atributo de clase se le agrega el guión bajo para distinguirlo de la función. 

[Aquí ](https://docs.python.org/3/library/functions.html#id)puedes aprender más sobre `id()` y otras built-in functions.

Espero haberte ayudado 😄

**Comment by sbcorrea** [comment]
Aah perfecto, ¡muchas gracias!
