### ISSUE TITLE
Volver a una opción anterior

### ISSUE THREAD

**Issue by jahernandez2** [IIC2233/Syllabus#34]
Hola! Tengo una duda más específica sobre el flujo de mi programa. Mi archivo main.py está ordenado según cada menú y dentro de cada menú las distintas opciones que se pueden realizar. Es fácil poder ir de un menú a otro con solo llamarlo, pero mi duda es si es que existe alguna manera más simple de volver a una opción en específico, por ejemplo si la contraseña es incorrecta, ¿como podría volver a esa opción en específico y no a algún menú? Agradecería mucho si me pudieran dar algún tip sobre como manejar estos casos. 
Saludos.

**Comment by Christian-Klempau** [comment]
Podrías hacer alguna función auxiliar que se encargue de verificar eso y retorne algo específico que tú quieras. Luego, basta con hacer un while que llame a esa función constantemente, hasta obtener el input esperado.
No sé si te refieres a eso exactamente pero esa es la idea general de cómo puedes solucionarlo

**Comment by jahernandez2** [comment]
Si, me refería justamente a eso. Muchas gracias.
