### ISSUE TITLE
Problemas con Github al hacer Push

### ISSUE THREAD

**Issue by ceosorio** [IIC2233/syllabus#34]
Hola!

Hoy quise hacer push para actualizar mis archivos de la tarea y me da un error fatal. Intenté por la GUI de Git y me dio este error:

> remote: Repository not found.
fatal: repository 'https://github.com/IIC2233/ceosorio-iic2233-2019-2.git/' not found
Pushing to https://github.com/IIC2233/ceosorio-iic2233-2019-2.git

Hace unos días hice push sin problemas al repo. Qué puede ser?

**Comment by KnowYourselves** [comment]
Hola @ceosorio!

Creo saber cual es tu problema!, Primero, cuál es tu sistema operativo?

Quedo atento!

**Comment by ceosorio** [comment]
Uso Windows 10

**Comment by KnowYourselves** [comment]
Yap, creo que es un problema de que Windows tiene guardados los certificados erróneos para tu cuenta de git, debes eliminarlos. Sigue los siguientes pasos:

1. Abre el Panel de Control. (Ponlo en ver por categoría)
2. Haz click en "Cuentas de Usuario", luego en "Cuentas de Usuario" de nuevo.
3. En el menu del costado izquierdo haz click en "Administrar credenciales".
4. Haz click en "Credenciales de Windows".
5. En "Credenciales genéricas" busca la credencial de git, ábrela y bórrala.
6. Haz git push y esta vez te deberá pedir tus credenciales.

Si tienes problemas con alguno de estos pasos o si no se soluciona tu problema, dime!

**Comment by ceosorio** [comment]
Efectivamente, al parecer al instalar Vivado (Para otro curso), Wandows cambió las credenciales. Ahí me funcionó, gracias!

**Comment by jjaguillon** [comment]
Hola.

Estamos con el equipo del IIC2343 buscando una solución permanente a este problema, dado que reescribe constantemente las credenciales de Github con el usuario **xilinx-xhub-users**.

Saludos
