### ISSUE TITLE
Duda sobre ingresar usuario no existente

### ISSUE THREAD

**Issue by Ikilly0** [IIC2233/Syllabus#34]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Muy breve, cuando el usuario elige la opcion, ingresar usuario, si ingresa un nombre que no esta registrado, se debe hacer algo en particular? o puedo simplemente loopear de vuelta a que ingrese otro usuario hasta que ingrese uno que si existe?

**Comment by Juampisaez** [comment]
Hola @Ikilly0!
El enunciado dice que si el usuario ingresado no existe, se deberá avisar en consola esto y se deberá volver al Menun de inicio. Queda a criterio tuyo como lo hagas, mientras se cumpla la condición que ya mencione.

Espero quede mas claro
Quedo atento igualmente :)
