### ISSUE TITLE
Duda descuentos por cambio de lineas

### ISSUE THREAD

**Issue by juanesjeep** [IIC2233/syllabus#34]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

No me quedo claro lo del decuento por cambio de lineas, 
**¿Se refiere a despues de la entrega cambiar lineas?**

**Comment by cristobalnic** [comment]
Hola @juanesjeep! El cambio de líneas es parte de la recorrección y te permite arreglar algo **después de la entrega** con un descuento proporcional a la cantidad de líneas que tuviste que cambiar.

Espero que esto haya solucionado tu duda!

**Comment by DCCollao** [comment]
Complementando un poco la excelente respuesta de @cristobalnic, te comento que también es posible solicitar este cambio de líneas dentro de tu archivo `readme.md`, y es lo ideal si te das cuenta de un pequeño error después de entregar tu tarea, ya que el `readme.md` tiene fecha de entrega posterior a la del código.
