### ISSUE TITLE
Duda sobre término de la partida

### ISSUE THREAD

**Issue by panchouc** [IIC2233/Syllabus#34]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo una duda respecto a que se considera como el término de la partida. Esto ya que en el enunciado nos dicen que cada vez que se termine la partida, debemos de mostrar el puntaje final, guardar el ranking en `puntajes.txt` y debemos volver al menú de inicio. Mi  inquietud es respecto a que casos se entienden como término de la partida. Por lo que leí, supongo que se refiere a:
- La persona pierde, ya que había una bestia en la coordenada que eligió.
- La persona gana, ya que descubrió todas las casillas vacías.
- La persona desea salir la partida, ya sea guardando su progreso o no.

Desconozco si hay más situaciones que se deban considerar como término de la partida, pero de momento eso es lo que entiendo del enunciado. De antemano muchas gracias y saludos.

**Comment by victoriaatria** [comment]
Hola! Exactamente como dijiste, existen esos tres casos donde termina el juego. En el último caso, recuerda que solo debes guardar el progreso si el usuario selecciona la opción de guardar la partida.

**Comment by gabo1243** [comment]
Hola, en ese tercer caso, ¿es necesario guardar el puntaje en el ranking?  Porque entiendo que esa partida se podría continuar en otro momento, entonces no sé si se debiese guardar ese puntaje parcial.

Gracias de antemano

**Comment by victoriaatria** [comment]
Hola! No, solo es necesario guardar el puntaje cuando se pierde o se gana una partida.
