### ISSUE TITLE
[Contenidos - Semana 01] ¿Cuando un atributo se debe considerar privado?

### ISSUE THREAD

**Issue by maromero-21** [IIC2233/Syllabus#34]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda
Hola! Entiendo la convención respecto a usar el _underscore_ para dar a entender que un atributo es privado.

Mi duda tiene más relación con cómo saber cuando específicamente un atributo debe ser privado o no.

Por ejemplo en el **Ejercicio 1: Autos deportivos** de la semana 1, la property **_depreciacion_acumulada_** no está definida como atributo, sin embargo utiliza los atributos _precio_ y _fecha_de_compra_,  ¿estos atributos participantes tienen que ser privados si es que están ligados a una property o no necesariamente?

**Comment by CarlangaUC** [comment]
Hola!

Todo depende del contexto, usualmente se emplea atributos privados cuando no hace sentido que puedas alterar un atributo en una clase de manera externa, esto permite un encapsulamiento te doy un ejemplo: 

class Alumno():
   def __init__(self, nombre, contraseña):
      self.nombre = nombre
      self.__contraseña = contraseña #Atributo oculto

En todo caso usualmente se especifica para asi mejor entendimiento, espero se haya entendido.

**Comment by mskdancers** [comment]
Hola :) Para añadir a lo que dijo mi compañero, los atributos privados se usan cuando, valga la redundancia, quieres que un atributo sea privado. Por ejemplo, si es que tienes una clase _Usuario_ no te convendría que cualquier persona pueda acceder a su atributo _contraseña_, y para limitar eso puedes hacer que _contraseña_ sea un atributo privado. 

En el caso de las properties, los atributos que estas manejen no necesariamente tienen que ser privados, como en el ejercicio que mandaste.

Dicho esto, también se usan mucho los atributos privados cuando queremos que estos sean manejados por una property. Por ejemplo, si es que tuviéramos una clase _Personaje_ y queremos que su vida sea un atributo con la salvedad de que esta nunca puede ser menor a cero, podríamos hacer el siguiente código:
```
class Personaje
    def __init__(self, vida_inicial):
        self.__vida = vida_inicial

    @property
    def vida(self):
        return self.__vida

    @vida.setter
    def vida(self, valor):
        if valor >= 0:
            self.__vida = valor
        else:
            self.__vida = 0
```
En este caso nos sirve tener el atributo privado ___vida_ ya que cuando alguien quiera modificar el valor de la vida, no accederá al atributo en sí sino que accederá a la property, la cual se encargará de que ___vida_ nunca tome valores negativos.

Espero haberte ayudado 😸

**Comment by maromero-21** [comment]
Muchas gracias por sus respuestas!
