### ISSUE TITLE
Uso de .gethostname o "localhost"

### ISSUE THREAD

**Issue by CrisDonosoMaass** [IIC2233/Syllabus#340]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/326).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/325).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, no estoy seguro de que forma manejar el host del servidor y no sé si debemos usar localhost o gethostname o si no existe una restricción. Muchas gracias!

**Comment by madiarenas** [comment]
Hola, con respecto a la función .gethostname() mi mac creo que me está causando problemas al intentar usarla ya que luego no se reconoce el nombre del host que entrega, y a veces cambia el nombre entregado ¿Hay alguna manera de solucionarlo?

**Comment by framos9** [comment]
Hola @CrisDonosoMaass.
No hay no existe una restricción. Elige lo que mas te acomode.

**Comment by framos9** [comment]
Hola @madiarenas.
Intenta manejar el host del servidor con "localhost" en vez de .gethostname(). Quizás eso sea mas fácil de implementar sin que tu Mac cause errores.
Si no se soluciona no dudes en escribir de nuevo.
