### ISSUE TITLE
Potenciador de Potencilantro y hardcoding

### ISSUE THREAD

**Issue by MTGG123** [IIC2233/Syllabus#340]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
En cuanto al potenciador del potencilantro, se considera hardcoding definir el potenciador en Solaretillo (Definida primero en parametros.py) y que solamente se active cuando éste este dentro del area del Potencilantro?

**Comment by rodrigoaguilera15** [comment]
Hola, solo sería hard-coding en caso que definieras el valor dentro de la misma clase y no dentro de parametros.py, por lo tanto lo que tú sugieres no corresponde a hard-coding. Revisando el enunciado, no dice explícitamente que el potencilantro deba tener como atributo propio al aumento que genera alrededor, así que lo que tú propones es válido. Si lo vas a hacer, recuerda especificarlo en tu README.
