### ISSUE TITLE
Librerías permitidas, no permitidas y malas prácticas

### ISSUE THREAD

**Issue by lily416** [IIC2233/syllabus#340]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:
 
> **Puedo usar la librería nombre_librería para hacer explicación_de_lo_que_quiero_hacer**
 
¡Recuerden especificar en su README qué librerías utilizan!
 
---
 
## ✔ **Librerías Permitidas** 
- PyQt5
- QtDesigner
- threading
- time
- random
- collections
- itertools
- functools
- operator
- dataclasses
- string
- copy
- os
- sys.exit
 
## ❌ **Librerías Prohibidas**
- pygame
- OpenCV
- Arcade
- Pyglet
- Tkinter
- matplotlib
- keyboard
- csv
- json
- pickle
- shutil
- pathlib
- glob
- pandas
- numpy
- ast
- curses
- io
- re
 
## ☠️ **_Built-ins_ Prohibidos** 
El uso de alguna de las siguiente funciones es automáticamente un 1,0 sin discusión: 😭
- exec
- eval
 
 
## Malas prácticas
El uso de las siguientes prácticas será considerado una mala práctica:
- Variables globales, a excepción de los elementos considerados en `parametros_generales.py`, `parametros_plantas.py`, `parametros_precios.py` y `parametros_acciones.py`. 
- `except Exception:` o únicamente `except:`
 
 
¡Ánimo y éxito en sus tareas! 🌽🍀

**Comment by ianfi96** [comment]
hola! en cuanto a la libreria exception, no me queda bien claro. Se puede o no usar la combiación ```try```, ```except```?

**Comment by veneguitas** [comment]
Hola! ¿De verdad no se puede usar exec? Lo pregunto porque es lo que han estado utilizando en todos ejemplos de los contenidos de Interfaces Gráficas.

**Comment by lily416** [comment]
Hola @ianfi96 pueden hacer uso de `try/except` para atrapar excepciones, pero su mal uso será penalizado. 
 
Está bien utilizado cuando se distinguen los distintos errores y se hacen excepciones específicas para cada uno de ellos. Por ejemplo:
```python3
try:
    # …
except ValueError:
    # Capturamos solo los ValueError y les damos su comportamiento
    # …
except (RuntimeError, TypeError, NameError):
    # Capturamos los RuntimeError, TypeError y NameError y les damos un comportamiento
    # ...
```
En cambio si hicieras que tú excepción no distinga entre los distintos errores y no tiene un comportamiento específico para cada uno, entonces sería una mala práctica. Ejemplos de lo anterior serían:
```python3
try:
    # …
except Exception:
    # …
```
```python3
try:
    # …
except:
    # …
```
 
Espero que te quede claro, cualquier consulta no dudes en preguntar 😊
Saludos y éxito con tu tareas 👋🍃

**Comment by lily416** [comment]
Hola @veneguitas , con respecto al uso de `exec`. Lo que ustedes utilizan para ejecutar los programas de PyQt5 es `exec_` el cual es distinto de `exec`. 
 
- `exec_` es una funcionalidad propia de PyQt que se utiliza para poder ejecutar la interfaz.
- `exec` es una funcionalidad propia de Python.
 
En esta tarea está permitido utilizar `exec_` para ejecutar la interfaz de su programa.
 
¡Ánimo y éxito con tu tarea! 👋🌾

**Comment by lily416** [comment]
@veneguitas actualicé el uso de `exec` por algo más completo, ojalá te sea de ayuda. 😬

**Comment by ignacio-urrutia** [comment]
Hola, quisiera saber si instanciar una ventana dentro de otra clase ventana se considera mala práctica (ejemplo: instanciar VentanaJuego dentro de la clase VentanaInicio).

**Comment by lily416** [comment]
@ignacio-urrutia instanciar ventanas dentro de otras no se considera una mala práctica, pero debes tener cuidado de que no se produzcan referenciar circulares entre ellas.

Saludos y perdón por la demora. 👋:bow:

**Comment by kisco99** [comment]
Hola! ¿Se puede instanciar un back-end en el front-end?  En mi VentanaInicio instancié el back-end de esta (para conectar las señales nada más) y me funciona, pero nosé si es mala práctica.

PD: En la ayudantía extra lo hicieron así y quedó bien

**Comment by lily416** [comment]
Hola @kisco99 , 
 
Existen tres formas de instanciar un programa con separación _back-end/front-end_:
1.- El _back-end_ en el _front-end_, como es el caso de la ayudantía extra.
2.- El _front-end_ en el _back-end_.
3.- El _back-end_ y el _front-end_ en un módulo que no corresponda a ninguna de las áreas y que se encargue de relacionarlos.
 
Cualquiera de las tres formas es correcta, mientras seas consistente con su modelación.

Ánimo y éxito con la tarea 👋🍁

**Comment by jfuentesg26** [comment]
Se puede usar la librería math??

**Comment by lily416** [comment]
Hola @jfuentesg26, ¿para qué quieres utilizarla? y si puedes especificar ¿qué funciones planeas usar?

**Comment by jfuentesg26** [comment]
@lily416  quiero usar las funciones floor y ceil para convertir la posicion del personaje en pantalla a indices en el mapa hecho de lista de listas

**Comment by lily416** [comment]
@jfuentesg26 puedes usar `floor` y `ceil`.

Saludos y éxito con tu tarea 👋🌱

**Comment by Iamchotiado** [comment]
Hola!! se puede usar la funcion "partial" de la libreria "functools"??, si se que es una libreria permitida, sin embargo quisiera asegurarme que se puede usar esa funcion

**Comment by lily416** [comment]
@Iamchotiado sí, puedes usar `partial` y todas las funciones de la librería `functools` 😄 

Saludos y éxito con tu tarea 👋👨‍🌾

**Comment by dpvillarroel** [comment]
Puedo ocupar --> from PyQt5.QtGui import QDrag, QPixmap, QPainter, QCursor, QImage para hacer el Drag and Drop??

**Comment by lily416** [comment]
@dpvillarroel sí puedes ocuparlos.

**Comment by diegopcalderon** [comment]
![duda_progra](https://user-images.githubusercontent.com/53881413/66575880-1e027f00-eb4d-11e9-9a54-87d78eea5c0d.png)

Encontre este codigo en internet y queria saber si el "exec_" que ocupa se puede usar?

**Comment by Dafnemami** [comment]
Puedo ocupar la libreria msvcrt ?

**Comment by Dafnemami** [comment]
Es para desactivar el teclado temporalmente

**Comment by francodonati** [comment]
Está permitida la libreria datetime? Es para hacer un reloj interno y poder usarla junto con Qtimer

**Comment by lily416** [comment]
@Dafnemami no puedes usar `msvcrt` ya que es sólo para Windows y tu programa debería ser capaz de funcionar en cualquier sistema operativo.

@francodonati Sí, puedes ocupar `datetime`.

Saludos y éxito en sus tareas 👋🌽

**Comment by mgbriones** [comment]
se puede usar datatime??

**Comment by lily416** [comment]
@mgbriones ¿para qué quieres usar la librería `datetime`?
