### ISSUE TITLE
Modelacion Circular

### ISSUE THREAD

**Issue by emena97** [IIC2233/syllabus#340]
Hola, no me queda claro que se considera como modelacion circular y que no.
Por ejemplo si yo tengo a mi clase Juego en el front-end y a la clase Character en el back-end, y Character recibe como parametro en su init a la clase juego, esto se puede?

**Comment by Hernan4444** [comment]
Hola, 

Estás diciendo que Character recibe a Juego, esto es válido mientras **Juego no tenga referencia a Character**. Para mayor información **comentar la issue #275** que ya está abierta y trata el mismo tema, así dejamos todo unificado en una sola issue y no tenemos issues duplicadas.
