### ISSUE TITLE
Iniciar el juego (botón y cuenta regresiva)

### ISSUE THREAD

**Issue by tremendapithon** [IIC2233/Syllabus#340]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola buenas tardes, puedo añadir un boton (inicar juego) en la ventana de juego para iniciar la cuenta regresiva?
Ademas, tengo una duda sobre TIEMPO_CUENTA_REGRESIVA == tiempo_restante.
Saludos

**Comment by Panconquesocl** [comment]
Holaa!!, si es que te refieres a que en la ventana de juego el juego comience al presionar ese botón no deberías, ya que, en el enunciado se indica que el juego debe comenzar automáticamente al mostrarse esta ventana, respecto a la duda sobre el tiempo restante podrías hacerla en una issue aparte por favor, suerte en la tarea😁!!

**Comment by gecoli** [comment]
¡Hola, @tremendapithon !
Si te fijas en el enunciado, en la figura 3 de `Ventana de Juego`, se puede apreciar en la parte de abajo un botón que dice 'Jugar'. Es este el botón que 'inicia el juego' si es que entraste en modo constructor y quieres comenzar a jugar, con todas las implicaciones (como comenzar la cuenta regresiva) 😊 
Si no se comienza con el modo constructor y se carga un mapa, en efecto debe iniciar automáticamente (como señala Panconquesocl).

Respecto a la segunda duda, ¿podrías desarrollarla? 🤔
