### ISSUE TITLE
Duda sobre archivos ya subidos

### ISSUE THREAD

**Issue by cseverino99** [IIC2233/syllabus#340]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia
Hola, cuando queria subir el diagrama para el avance de la tarea no puede subir solo el pdf (nunca supe pq no me dejaba luego de hacer add .pfd, commit y push) por lo que hice add . y luego push para subir todo, ahora paraa entregar la tarea tengo claro que no debo tener subidos todos los archivos y deben estar en mi git ignore, pero si ya estan subidos en mi repositorio de git hub que debo hacer??

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mistico0121** [comment]
Hola. Encontré esta solución a tu pregunta en stackoverflow. 

https://stackoverflow.com/questions/2047465/how-can-i-delete-a-file-from-a-git-repository/2047477

Yo en lo personal, cuando subo un archivo que no debí haber subido, lo saco de la carpeta del repositorio temporalmente, y hago "git add ." + commit + push, lo que remueve el archivo en el último commit del repo, que es lo que se corrige. 

Prueba a hacer eso. Igual siempre mantén un respaldo en tu PC de los archivos que puedan servirte localmente, y recuerda utilizar el gitingore para evitar que se suban.
