### ISSUE TITLE
Duda función votos_interespecie

### ISSUE THREAD

**Issue by SebaPassi** [IIC2233/Syllabus#340]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!

¿Puede ser que en la definición de la función "votos_interespecie" haya faltado colocar el valor que debe tomar el argumento "misma_especie" en caso de que este no se entregue en el llamado a la función?

En el código prehecho está de esta forma:

**def votos_interespecie(generador_animales: Generator,
    generador_votos: Generator, generador_candidatos: Generator,
    misma_especie: bool) -> Generator:**

¿Se puede modificar para que quede así? -> 

**def votos_interespecie(generador_animales: Generator,
    generador_votos: Generator, generador_candidatos: Generator,
    misma_especie: bool = False) -> Generator:**

Muchas gracias!

**Comment by ignacio-sp** [comment]
Hola @SebaPassi, en efecto lo que indicas corresponde a un error de la definición de la función, recomiendo hacer pull de la tarea para ver los cambios realizados indicados en esta [issue](https://github.com/IIC2233/Syllabus/issues/338#issue-2303846202), el cambio que mencionas es el correcto. Éxito!
