### ISSUE TITLE
Nivel Energía Total Docencio

### ISSUE THREAD

**Issue by CristobalUrzua** [IIC2233/syllabus#340]
No me queda muy claro cuando el enunciado dice, por ejemplo, que energía total estará entre 40 y 50. ¿Estos son rangos que se deben cumplir? o ¿Estos son los valores (dentro del rango (40,50) que pueden tomar aleatoriamente magizoologos nuevos?.
Es decir, ¿podría tener energía total de 30?

**Comment by matiasmasjuan** [comment]
Hola @CristobalUrzua !

Al momento de **crear** un **nuevo** **Magizoólogo**, su valor de **energía total** va a estar dado por un valor (por ejemplo, para el caso de los Docencios) **aleatorio** entre **40** y **50**. Por ejemplo, supongamos que su **energía total** fue de **42**. Luego de esto, **ese valor** de **energía total** **no cambia nunca más**. Vale decir, una vez que se **crea** el **Magizoólogo** se **establece** cuál va a ser su **energía total**. Su energía actual puede variar dependiendo de las acciones que haga durante el día, pero al momento de *pasar al día siguiente*, se debe **recuperar** su **energía actual** a su **energía total** (en este caso, 42).

Espero haber respondido a tu pregunta, y mucho éxito con tu tarea!

**Comment by Camila-sty** [comment]
Hola.
Pero durante el día puede llegar a ser cero la energía actual del magizoolo?

**Comment by matiasmasjuan** [comment]
Hola @Camila-sty !

**Sí**, puede llegar a ser 0 la **energía actual** durante el día. Pero **ojo** que no puede ser **inferior** a esta cifra. Vale decir, no puede existir **energía actual negativa**.

Saludos!
