### ISSUE TITLE
T01 Habilidad especial DCCrotona

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#340]
Hola! no me quedo claro en el enunciado si la habilidad aumenta en +1 el medallero insta , o si podemos escoger una competencia y hacer que nuestro deportista gane esta insta.
creo es lo primero pero para confirmar
Saludos.

**Comment by jitorcas** [comment]
Hola! @sa-Appel 

Así es, solo suma uno a la cantidad de medallas totales.

Éxito en la tarea! 🥇

**Comment by jarvasquez** [comment]
Se dice que se obtienen todos los beneficios que en condiciones normales. Pero en condiciones normales si un deportista gana su moral sube al doble, ¿a qué deportista se la damos?

**Comment by jitorcas** [comment]
Hola! @jarvasquez 

En la issue #374 se profundiza más en tu duda, pero básicamente puedes elegirlo al azar. 

Éxito🏃🏻
