### ISSUE TITLE
orden de sucesos al alimentar DCCriatura (Buñuelo)

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#341]
Mi problema surge con el "efecto especial" que poseen los buñuelos, ya que estos pueden hacer que la DCCriatura escape.

Pero ademas, la criatura puede atacar al Magizoologo cuando come los buñuelos, entonces mi duda es:

¿Que ocurre primero? 
¿La criatura ataca y después huye?
¿La criatura huye pero no ataca al usuario?

**Comment by mpsubiabre** [comment]
Hola @felipehen !

El efecto especial de los buñuelos es que pueden ser rechazados o no por la criatura, y el alimento en ambos casos se perderá. Creo que tienes una confusion porque los Buñuelos no tienen el efecto especial que mencionas (le di varias leídas, si lo dice y se me paso me lo indicas)

Si te quedan dudas coméntalas :)

**Comment by felipehen** [comment]
ohh acabo de leerlo de nuevo, y resulta que lo entendí mal, al decir "lo perderá", asumí que hablaba de la criatura, y que se refería a que "se escapa"

muchas gracias

**Comment by mpsubiabre** [comment]
No hay problema, éxito con la tarea :smile:

**Comment by kipasten** [comment]
me surgió la duda de qué pasa cuando un Erkling al pasaer el dia se roba un buñuelo y lo come? aun asi se activa el posible "rechazo"? o si lo roba se lo come sin rechazarlo?

**Comment by mpsubiabre** [comment]
Hola @kipasten !

Al no estar explicito en el enunciado quedara a tu criterio. Revisa la issue #336 

Exito! ✨
