### ISSUE TITLE
Monedas enemigos

### ISSUE THREAD

**Issue by emena97** [IIC2233/syllabus#341]
cuando un enemigo muere y deja monedas, estas tiene que dasaparecer luego de un tiempo tambien? o se puede asumir que se quedan ahi?

**Comment by jaromero6** [comment]
Hola
Desaparecen luego de un tiempo, al igual que las monedas que aparecen en el mapa aleatoriamente (Es decir, duran el mismo tiempo).
Éxito en la tarea!
