### ISSUE TITLE
Duda sobre hardcoding

### ISSUE THREAD

**Issue by 0DASAC** [IIC2233/syllabus#341]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

He buscado harto sobre el significado de hardcoding pero todavía no estoy muy seguro.
si creo una variable menu en el main y la ocupo para ver en que menú estoy seria mala practica?

**Comment by tqmbanados** [comment]
Hola! No se si cerraste la issue porque solucionaste el problema tú, pero en general trata de nunca cerrar las issues! Voy a dejar la respuesta igual por si a otra persona le sirve.

### Definicion General
El *hardcoding*, en general, es la inclusión de datos (pueden ser strings, ints, floats, o incluso estructuras como diccionarios) directamente en el código. No siempre es un problema, por ejemplo, si queremos calcular un promedio entre dos valores, tendremos que sumarlos y dividirlos por el int ```"2"```, en este caso, ese int podría considerarse hardcodeo, pero no sería problemático para tu programa. Sin embargo, si la cantidad de valores que se quieren promediar es variable, agregar un int fijo no resultará en promedio adecuado cuando la cantidad de valores es distinta al int. En ese caso, se debe calcular el valor en el mismo programa, o si la cantidad de valores puede ser definida antes de correrlo, agregarlo como un parámetro.

#### ¿Qué es el "softcoding"?
El softcoding es cuando tu programa toma los valores de otras fuentes, y no de valores escritos **directamente** en él. Cuando tomas input de un usuario, estas asignando un valor a una variable de tu programa, sin tener que escribirlo directamente; esto sería softcoding. Otras formas de softcoding serían:
* Tener un archivo de texto con los valores, y un protocolo de lectura de este archivo que los asigna al programa
* Tener un módulo usado especialmente para definir parámetros constantes en el programa
Hay otras maneras de softcodear más complicadas, pero esas son las que usaremos en el curso. En la Tarea 1, les pedimos que usen la segunda opción, salvo que se pida lo contrario. Es importante tener en cuenta que en el propio archivo ```parametros.py```, se definen como *variables* estos valores. Sin embargo, el módulo no hace procedimientos para cambiar estas variables, y sólo es ejecutado por otro módulo que no puede cambiar los valores que contiene. Por esto, dentro del programa se comportan como **constantes**. 


 ### Definición Específica

En este curso corre una definición más específica. El hardcoding corresponde a la inclusión en el código base de cualquier valor que pueda ser *variado* antes de la ejecución final del programa. Por ejemplo, la velocidad de los barcos, si bien la podrías escribir manualmente cada vez que tienes que hacer un cálculo con ese valor, tendrías problemas si eventualmente quieres cambiarlo; y tengas que recorrer tu código buscando donde lo usaste. En programas simples no es tanto problema hardcodear (como la tarea 0), pero ya cuando empiezan a tener muchas líneas es cada vez más problemático. 
Esto se soluciona **parametrizando** estos valores. Si tienes un módulo aparte (puede también ser un archivo de otro tipo que abres con el programa, algo que aprenderán a hacer en el futuro) con los valores unidos a un nombre fijo, y en tu programa sólo trabajas importando ese "nombre", que sería una constante, y asignándolo donde corresponde, luego si quieres hacer algún cambio sólo debes modificar el valor en el módulo ```parametros.py```. 
Entonces, consideraremos hardcoding cualquier definición de una constante que use tu programa para calcular valores determinados, por ejemplo las distintas probabilidades de los eventos. También, strings que sean usados para comparar, por ejemplo aquellos que revisan si el input de usuario corresponde a cierto valor (como el de \volver en la T0), son valores que  
deben ir parametrizados. El enunciado de la tarea en general explicita qué valores son aquellos que debes parametrizar, pero es posible que a tí se te ocurran soluciones a problemas ocupando valores que no pueden ir hardcodeados.

### Ejemplo

Imagina que quieres hacer un simulador de comportamiento de partículas complejo. Quieres definir distintos tipos de partículas, con propiedades como masa y carga eléctrica. Además, quieres someterlas a una fuerza de gravedad, además de los efectos de un campo magnético. La simulación debe calcular las fuerzas que ejercen todas estas partículas entre ellas, y también las fuerzas del ambiente, una cantidad de cálculos y fórmulas que puede ser gigantesca. Si todos esos cálculos los hicieramos con valores "hardcodeados" (es decir, cada vez que hay que calcular el efecto de la gravedad, escribimos un int ```10```), podríamos echar a andar nuestra simulación y descubrir que no funciona como esperamos; quizás por que nuestro valor para gravedad no es suficientemente exacto. Tendríamos que ir a cada una de esas fórmulas para cambiar el valor a ```9.8``` o algo más exacto. Esto nos tomaría mucho tiempo, y lo más probable es que se nos pase una, y el dolor de cabeza continúe.
    Si simplemente escribimos en un módulo aparte esta fuerza de gravedad, y todos los otros valores de nuestra simulación, podemos cambiarlos en 3 segundos, sin miedo a que deje de funcionar nuestro código, y sin que queme la cabeza.

*(Además, hay ciertos lenguajes que tienen que ser __compilados__ antes de ejecutarse, por ejemplo en un ```.exe```. A un programa ya compilado no le puedes cambiar el código fácilmente, pero si puedes agregarle un archivo parámetros externo para cambiar)*

**Comment by 0DASAC** [comment]
muchas gracias por la respuesta.
