### ISSUE TITLE
Avance de Tarea - Cargado visual

### ISSUE THREAD

**Issue by JosefaPaz** [IIC2233/syllabus#341]
Hola!!

Respecto al avance de tarea, al implementar el cargado visual del mapa a partir de los archivos entregados, se refiere a implementar el frontback, o simplemente una idea visual de cómo debería verse el mapa de manera gráfica?

gracias!

**Comment by aljara97** [comment]
Hola, para el cargado visual de la tarea se pide que tu programa sea capaz de abrir una ventana que represente gráficamente a través de los sprites entregados las distintas celdas del mapa. Si bien, se entregará un feedback general, es recomendable que el cargado visual del mapa se haga a partir de una separación backend y frontend, ya que es un item a evaluar en la tarea.

Mucho éxito con tu tarea, cualquier duda trataremos de respomderla rápidamente
