### ISSUE TITLE
Secuencia de sprites en la Animación

### ISSUE THREAD

**Issue by JoaquinBocaz** [IIC2233/Syllabus#341]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, esperando se encuentren bien.

Respecto a la animación de las entidades al moverse, si bien comprendo el uso de tres sprites en el proceso, me surge la interrogante acerca de la forma en que estas deben ir secuenciadas. Para ver si comprendo,  la secuencia de imágenes sería, la forma estacionaria de la entidad, luego un cambio de dos imágenes distintas en la casilla que estaba al inicio, seguido de un cambio a la casilla siguiente cambiando a una tercera imagen, o nada que ver? Desde ya muchas gracias por su tiempo

**Comment by gecoli** [comment]
¡Hola, @JoaquinBocaz !

Como dices, el movimiento parte de una casilla donde la entidad está en la `sprite_1`. De esta manera, la animación está pensada para que sea `-> sprite_2 -> sprite_3 -> sprite_1`, donde la entidad quedaría nuevamente en la primera sprite (y pasa por las 3). 

Éxito!

**Comment by Matoclip** [comment]
Hola! Si bien entiendo la secuencia de sprites que debe seguir la animación, a mi me queda la duda de si nos están pidiendo que estos sprites intermedios (sprite_2 y sprite_3) aparezcan entremedio de las casillas para emular movimiento continuo; esto es lo que yo pienso que nos están pidiendo y estoy bastante complicado. Si en realidad estos sprites se han de encontrar en la casilla original o en la casilla a la que nos dirigimos, sería bastante más sencillo. De antemano muchas gracias por la respuesta!

**Comment by EleaTriesToCode** [comment]
Hola :)

Me subo a este issue para pedir un poco de ayuda con las animaciones...

He hecho todo mi juego sin preocuparme de ellas, pensando agregarlas al final y estoy un poco perdida de como hacerlas. Se pueden manejar solo desde el front o el back debe enviar senales para cada sprite ? Se debe usar una liberia especial de PyQt o hay otras opciones para hacer que se vea continuamente el movimiento (he intentando con sleep en el front entre cada sprites para hacer un cambio mas suave pero no me funciono...) ?

He intentado varias cosas pero sin mucho exito y no quiero destruir mi arquitectura que a parte de eso funciona bien... Agradeceria cualquier tip sobre las animaciones que ustedes juzgan bueno darnos :)

**Comment by Hernan4444** [comment]
Hola!

Primero respondiendo la duda: la idea es que para lograr este moviento "fluido y animado" que solicitamos en la tarea, es que mientras el personaje (Luigo o fantasmas) se desplaza de una casilla a otra, se vaya cambiando el sprite.

Por ejemplo, **analizando solo el eje X**, digamos que la casilla 0 está en  X=0, y la casilla 1 está en X=150.

La idea sería:
1. El personaje está en X = 0 mostrando sprite 1. ... Comienza su movimiento a la casilla 1.
2. El personaje se mueve a en X = 50 mostrando sprite 2.
3. El personaje se mueve a en X = 100 mostrando sprite 3.
4. El personaje se mueve a en X = 150 mostrando sprite 1.

Con eso, el personaje se movio de a poquito a la casilla 1, y mientras hacía el movimiento se cambió el sprite. El cambio paulatino de posición permitió percibir este movimiento fluido, y el cambio de sprite permitió percibir la animación. Sobre la fluides, esto tambien se puede apreciar en la Experiencia 4 donde hacemos que los meteoritos se mueven una cantidad pequeña de pixeles, generando la percepción que está cayendo fluidamente.

Respecto a un tips, primero indicar que este contenido no rquiere de ninguna librería especial de pyqt, solo aplicando lo que hemos visto en los contenidos y experiencias (señales + QTimers o Qthreads + QPixmaps) es posible lograr este ítem.

Luego, si bien no es lo mismo, en la sala de ayuda de la semana pasada (cuyo código está en el Syllabus T2), vimos un pequeño ejemplo de _zapping_ donde presionar la tecla W activaba un QTimer que llamaba a una función constantemente para cambiar el canal, y cuando se soltaba la tecla W, ese QTimer se detenía. El movimiento animado es bien análogo a esa situacion, mientras ocurre algo (que no puedo decir), hay que activar a una función que haga algo adicional, y cuando todo este proceso termine, esa función se detiene.

La idea aquí es evlauar que logren conectar todos los contenidos para lograr este movimiento fluido, por eso tampoco puedo decir exactamente cómo hacerlo, pero la idea es que el _zapping_ visto en la sala de ayuda los apoyara justo a tener una idea de cómo enfrentar este ítem.

Saludosヾ(＾-＾)ノ

**Comment by josegarafulic** [comment]
@Hernan4444 quisiera saber si para la tarea es obligación ocupar threads?. O si en cambio de pueden solo ocupar Qtimers como en la experiencia 4.

**Comment by Hernan4444** [comment]
Hola, se puede utilizar cualquiera de dos, al final son 2 formas distintas de generar concurrencia.

Saludosヾ(＾-＾)ノ
