### ISSUE TITLE
Uso de len()

### ISSUE THREAD

**Issue by tomasvasquezp** [IIC2233/Syllabus#341]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! tengo una duda, esta permitido el uso de len()? pregunto porque me quedo la duda de si se puede usar o no. Además tengo una duda con la creacion de programacion funcional, queria ver si es posible que vean mi codigo en cantidad_votos_candidatos para ver si cumple con programacion funcional (hice push para que la puedan ver). 

Gracias!

**Comment by ClemoAcevedo** [comment]
Hola @tomasvasquezp , en la issue de `Librerías permitidas, no permitidas y malas prácticas T3` explican que len() se puede ocupar tanto para la carga de datos como para las consultas. Viendo tu código te diría que vas bien encaminado, buena suerte.
