### ISSUE TITLE
Asignar variable como comando o dato

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#341]
Hola!

Supongamos que corro estas líneas:
```
["asignar", "x", 3.14]
["asignar", "y", "x"]
```
Si luego llamo a `y`, esta me debería retornar el string `x`, ¿verdad?

Saludos!

**Comment by iqacevedo** [comment]
Hola

Debería retornar 3.14, puesto que con escribir "x" llamas a la variable guardada previamente y ese es el valor que guardas en y.

Saludos!

**Comment by akaminetzkyp** [comment]
Perfecto, gracias!

**Comment by adisrael** [comment]
y luego la variable x deberia borrarse o quedan las 2??

**Comment by adisrael** [comment]
@iqacevedo
