### ISSUE TITLE
Al correr main.py y abrir las consultas me tira error

### ISSUE THREAD

**Issue by AndresGarciadelaHuerta** [IIC2233/Syllabus#341]
Hola! Como dije en el enunciado, me está tirando este error dentro de la gui al abrir consultas.json desde la interfaz:
![captura de pantalla 2017-09-26 a la s 14 37 11](https://user-images.githubusercontent.com/30664883/30875091-b57f7542-a2c8-11e7-8800-76bfa2c3917b.png)

Estoy usando un computador Mac. ¿A alguien más le pasa o sabe cuál es la solución? Gracias!

**Comment by Arcoirisky** [comment]
Te sugiero buscar entre las Issues cerradas (Como la --> #337) y prestar atención al tipo de error que te está tirando. 

Pd: Google apaña bastante :D

**Comment by AndresGarciadelaHuerta** [comment]
Te entiendo perfecto lo del encoding y todo eso, el problema es que estoy corriendo el main.py y abriendo consultas.json con lo que uds subieron y no se está abriendo correctamente desde la gui, que no puedo editar, con lo que no puedo cambiar el encoding. Estoy haciendo esta parte del enunciado, apartado 7.1 consultas.json:

> Para poder leer este archivo, se debe copiar, sin cambiar su nombre, a la misma carpeta que main.py. A través de la interfaz, en la barra de opciones, debe seleccionar la opción “Abrir” para cargar el archivo.

 Y haciendo esto me tira el error. Se entiende? Gracias por responder!

**Comment by Arcoirisky** [comment]
Oh, eso es tema. ¿Puedes mandar el error? Como imagen, pantallazo, como sea. Para así verlo y cachar que se puede hacer.

**Comment by AndresGarciadelaHuerta** [comment]
![captura de pantalla 2017-09-26 a la s 23 32 10](https://user-images.githubusercontent.com/30664883/30893159-fa8d56f0-a312-11e7-90a6-263b9e471a8f.png)

@Arcoirisky Aquí va un pantallazo y el error en sí lo puse en mi primer comentario. Gracias!!

**Comment by Arcoirisky** [comment]
Ahora entiendo bien y después de modificar algo se ha solucionado. Gracias por insistir en el error!! Ahora mismo lo estoy viendo.

**Comment by AndresGarciadelaHuerta** [comment]
@Arcoirisky Dale perfecto! Gracias!

**Comment by Arcoirisky** [comment]
@AndresGarciadelaHuerta Soluciona3. Haz pull y dime si ahora te funciona O:!
