### ISSUE TITLE
Entrega Avance diagrama

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#341]
Hola! quería saber por donde y hasta cuando tenemos para subir el avance del diagrama.

**Comment by jitorcas** [comment]
Hola! @sa-Appel 

En la portada de la tarea se específica. 

<img width="647" alt="Captura de Pantalla 2020-09-05 a la(s) 19 12 18" src="https://user-images.githubusercontent.com/48298300/92314878-e47c0300-efab-11ea-9923-760c1e731aba.png">

Éxito en la tarea 🥇
