### ISSUE TITLE
Implementar Mapa T02

### ISSUE THREAD

**Issue by fnberrios** [IIC2233/syllabus#342]
Hola! Si bien los archivos '''mapa_1.txt''' y '''mapa_2.txt''' nos entregan la distribución espacial del campo ya existente, hay muchas más imágenes en la carpeta '''sprites\mapa''' que cantidad de objetos en el mapa ¿Cual es la correspondencia entre cada una de las imágenes y el mapa entregado? ¿Nos ayudaría usar alguna librería como pySlipQt o pygame?
Gracias de antemano.

**Comment by jeschuwirth** [comment]
Hola!

Les entregamos muchas más sprites de las necesarias para aquellos alumnos que quieren decorar más su mapa o tener elección de entre todas las sprites.

Para su ventana de juego pueden ocupar cualquier sprite de los entregados, siempre y cuando se entienda lo que representan (no usar sprites con rocas para representar pasto/tierra arada) ni usar la casa para representar rocas.

En cuanto a las librerias recuerda mirar la issue #340 con las librerías prohibidas (como pygame). Si tienes la duda si se puede usar alguna librería, siempre puedes preguntar en un comentario en esa misma issue.

Suerte en la tarea !
