### ISSUE TITLE
Duda efecto especial DCCapitán

### ISSUE THREAD

**Issue by Pakarati** [IIC2233/syllabus#342]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Estuve revisando las issues y creo que nadie preguntó por esto. Me surgió una duda al aplicar el efecto del capitán. ¿Se aplica *justo después de que el barco encalla por primera vez* o se aplica *luego de terminar la hora*? Por otro lado, si es que se aplica _inmediatamente_, luego de que el capitán "desencalla" el barco ¿este puede *seguir avanzando en la misma hora* en que encalló? ¿o debe si o si *esperar a otra hora* para avanzar, a pesar de ya estar desencallado por efecto del capitán?

**Comment by Emiliax16** [comment]
Hola @Pakarati  ! cuando un barco encalla por primera vez y  posee algún tripulante tipo DCCapitán, desencalla inmediatamente, por lo que puede seguir avanzando. Tómalo como que si se cumplen las condiciones nombradas, es como si nada hubiera pasado! 
Recuerda que sólo funciona la primera vez que el barco encalla.

Saludos!
