### ISSUE TITLE
Cálculo parámetros pixeles/ms para Qtimer.

### ISSUE THREAD

**Issue by benjaminsalgado** [IIC2233/Syllabus#342]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, revisando las indicaciones para la velocidad, me gustaría comprobar si esta formula es valida para conseguir los parámetros adecuados para un qtimer que mueva cierta cantidad de pixeles, de la manera que se solicita en el enunciado. Ej: Qlabels de tamaño 50 pixeles con una velocidad de 10.

pixeles / ms = tamaño / ((1 / velocidad) * 1000)
pixeles / ms = 50 / ((1 / 10) * 1000)
pixeles / ms = 1 / 2, es decir, se mueve 1 pixel cada 2 ms.

Favor de confirmar si esto es correcto.
En el caso de los lobos, el valor de la velocidad se dividiría en el ponderador correspondiente de cada nivel.

**Comment by vicente999** [comment]
Hola! Podrías explicarme que es lo que intentas conseguir con eso? En el fondo en el enunciado se explica como se manejan las velocidades y los tiempos, pero no entiendo lo que quieres lograr

**Comment by benjaminsalgado** [comment]
En el enunciado, por lo que entiendo, solo se especifica como manejar el tiempo, el cual se corresponde a el tiempo que se demoraría la entidad en moverse hacia otra casilla. Siguiendo con esto, lo que estoy intentando calcular es la cantidad de pixeles que se tiene que mover un Qlabel, por ms, para poder cumplir con la cantidad de tiempo establecido. En el ejemplo presentado, el resultado diría que se tiene que mover 1 pixel cada 2 ms, lo que si lo multiplicamos por el tamaño (tanto el denominador como el numerador) de los Qlabel (50) da como resultado un desplazamiento de 50 pixeles cada 100 ms, cunpliendo con la formula:

![image](https://github.com/IIC2233/Syllabus/assets/141959315/d2b71faa-b410-4a5b-b9e8-752010e3e19f)

Ya que la velocidad en mi ejemplo es 10.
Saludos

**Comment by vicente999** [comment]
Ya perfecto, ya te entendí! Lo que te importa aca es cuanto se demora el conejo en avanzar 1 baldosa, por ejemplo si te digo que la velocidad del conejo es 1, se demora 1 segundo en avanzar una baldosa, ahora tienes que adaptar esa velocidad a la cantidad de pixeles que contiene esa baldosa segun tu codigo. O sea si una baldosa es de 10x10 px, tu conejo avanza 10 px por segundo, se entiende?

**Comment by benjaminsalgado** [comment]
Entiendo!, entonces la formula estaría bien, no?

**Comment by vicente999** [comment]
Si!
