### ISSUE TITLE
Abstract Class/Method en Diagrama de Clase

### ISSUE THREAD

**Issue by camirojasguajardo** [IIC2233/syllabus#342]
Hola! Cómo se especifíca que una clase o método es abstracto en el diagrama de clases? Hay alguna forma especial de hacerlo o se debe representar como todas las demás?

**Comment by itmunoz** [comment]
Hola! Se representan como todas las demás. No es necesario hacerle algo especial.

**Comment by camirojasguajardo** [comment]
Muchas gracias por la respuesta, qué tengas un buen finde!

**Comment by enriquemolinare** [comment]
En la pauta de entrega con respecto al avance de la tarea  dice que debe "Contener todas las clases junto con sus atributos y métodos. También deberás identificar cuales clases serán abstractas y cuáles no" .  Cómo debo identificar a las clases abstractas en el avance de la tarea?

**Comment by aaossa** [comment]
Hola @enriquemolinare y @camirojasguajardo , tal como se dijo en #383 traicionalmente se utiliza *itálicas* (cursiva para les amigues), pero pueden usar la forma que más les acomode (no les pedimos una forma exacta). Mientras esté explícito en su diagrama, no hay ningún problema 👌  Por ejemplo, podrían poner bajo su diagrama un cuadradito que diga "las clases abstractas son las que están marcadas de ESTA MANERA" o "**esta manera**" o "`esta_manera`". Lo importante es que elijan una forma y aparezca explícitamente para que les ayudantes puedan corregir ✨ 🤓
