### ISSUE TITLE
Error git push 

### ISSUE THREAD

**Issue by mariaignaciag** [IIC2233/syllabus#342]
Hola, cuando intento realizar el git push del diagrama, junto con los otros archivos, me tira un error de la actividad formativa 2, específicamente el archivo jugadores.py, creo que esta la modifique en git cuando ya había hecho git push desde el computador,  adjunto error, gracias!
![Captura de pantalla 2020-04-08 a la(s) 14 22 44](https://user-images.githubusercontent.com/62075301/78819596-7bfd0b80-79a4-11ea-867c-9d6658a4fdf1.png)

**Comment by JosefaPaz** [comment]
Hola @mariaignaciag !

Como tú bien dices, este error se produjo porque modificaste el archivo en git y además hubo una modificación en tu computadora. Intenta añadir el archivo ```jugadores.py``` nuevamente a tu repositorio en git, y de ahí ver el status de tu repositorio.

Quedo atenta!

**Comment by mariaignaciag** [comment]
si!! muchas gracias!
