### ISSUE TITLE
Movimiento de QRect en front o back end?

### ISSUE THREAD

**Issue by bmurtagh01** [IIC2233/syllabus#342]
Tengo la duda sobre el movimiento de mis rectangulos de interseccion. Si bien cuando yo muevo un sprite, ej. un enemigo, lo mas eficiente (segun entendí yo en las clases) era que el backend se encargue de la logística de coordenadas y así envie una señal al front end para que haga el "move" del label segun los números calculados en el backend. 
Yo pretendía hacer el movimiento del rectangulo QRect que sigue al enemigo solamente en el backend pero por el hecho de ser un objeto de Qt nose si tambien debo hacerlo en el front-end por temas de eficiencia. (Ojalá que no.)

**Comment by jaromero6** [comment]
Hola, efectivamente como dices lo más lógico es que verifiques la colisión en el backend, en ese sentido no hay problema en instanciar un objeto Qt en el backend, la idea de la separación entre este y el frontend es netamente una separación entre lo visual y la lógica, obiviamente PyQt te ofrece clases y métodos que te serán de ayuda tanto en frontend como en backend, así que no hay problema en tener este u otras clases de Qt en el backend.
Espero haberte ayudado

**Comment by bmurtagh01** [comment]
Perfecto muchas gracias!
