### ISSUE TITLE
clases generador

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#342]
¿Como obtengo la clase de generador?

**Comment by iqacevedo** [comment]
Hola
La necesitas para usar algo del estilo `isinstance(my_variable, ClaseGenerador)` ?

**Comment by jorgeriesco** [comment]
si

**Comment by akaminetzkyp** [comment]
Puedes importar `type.GeneratorType` y después usar `type(foo) is type.GeneratorType`. :)
