### ISSUE TITLE
Modificar un string con for

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#342]
El siguiente codigo ejemplo:

```Python
def replace(string):
    for replace in replaces:
        string = string.replace(replace,  '')
    return string
```
Esta permitido? Dado que un string no es una esturcutra de datos, pero tampoco una funcion, sino que una variable.

**Comment by naquiroz** [comment]
Trate de hacer lo que quiero con bult-ins pero no pillo ninguno que me sirva, por eso pregunto si eso se puede hacer.

**Comment by Hernan4444** [comment]
@naquiroz si puedes, pero es recomendable trabajar sobre una copia del _input_ para no olvidar que las funciones buscan **minimizar los efectos colaterales**, entre esos, no modificar el _input_.

Saludos ✌️
