### ISSUE TITLE
Logo DCCampo

### ISSUE THREAD

**Issue by DiegoEmilio01** [IIC2233/syllabus#343]
Hola, quería pedir si pueden subir el logo del juego para poder utilizarlo en la ventana de inicio. De antemano muchas gracias.

**Comment by agustin-rios** [comment]
puedes cortarlo del enunciado

**Comment by JuaniAndres** [comment]
igual el original va a quedar siempre mejor que el recortado al menos en png

**Comment by javierzagal** [comment]
Los bordes del mapa estan en sprite>mapas (los que se llaman tiles)

**Comment by lily416** [comment]
Ya se encuentra subido el logo del _DCCampo_ al _syllabus_ del curso. 😊
Se encuentra en la carpeta `Tareas/T02/sprites/otros/`. 
Espero que le saquen un buen provecho.
 
Saludos y éxito con sus tareas 👋🍀🌽

**Comment by lily416** [comment]
@JuaniAndres Ya se encuentran subidas las bases que se usaron para crear el borde del mapa y del inventario.  Pueden reescalarlos y editarlos para que calcen con la imagen que tengas en mente.
 
También te invito a investigar distintas opciones en internet, puede que encuentres algo distinto y que le de un toque especial a tu tarea. 😄:sparkles:
 
En cualquiera de los dos casos: las imagen editadas o descargados por ti **debes subirlas en una carpeta distinta a `sprites`** para que así no sean ignorados por el `.gitignore`.
 
Saludos y éxito con tu tarea. 👋🌱

**Comment by JuaniAndres** [comment]
Gracias @lily416  es que esos bordes le dan su toque :grin:
