### ISSUE TITLE
QThread

### ISSUE THREAD

**Issue by cmarquez1** [IIC2233/syllabus#343]
Tengo una duda si implemente bien el thread en el movimiento del personaje y si las señales entre back y front estan bien. Tengo una clase "Jugador" que herede un Qthread en el back, tengo una función la cual hace sumar o restar tantos pixeles a variables x e y dependiendo de la tecla que presiono (que esta conectada  a una señal del front), y estas variables tiene propierty que verifican si hay colision o no y si hay, la variable cambia al valor. Y al final tengo mi metodo run que envia una señal al front con las variables cambiadas o no cambiadas ya que el start() esta en el front el cual se ejecuta cada vez que presiono una tecla WASD. Mi duda aca es que si es que tengo el thread "malo", que es lo que deberia ir en la funcion run de mi clase "Jugador", no se si me explique bien

**Comment by naquiroz** [comment]
Hola! :wave: 

Primero que todo, te felicito por tu motivación por la tarea ! :tada: :muscle: 

Sin embargo, no entiendo bien tu duda, ni tu implementación del problema. Quizás trata de concretar un poco mas tu pregunta para así darte una respuesta precisa :blush: 

Quedo atento a tu respuesta!
