### ISSUE TITLE
Uso de while y for con estructuras de datos

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#343]
Hola por lo que entendi estaria permitido el uso de ```for``` y ```while``` mientras no se modifique una estructura de datos ni se retorne. Pero no me queda claro si esta permitido el uso de ciclos al leer una estructura de datos pero solo cambiar una viarable que no es una estructura como en el siguiente ejemplo:
```python
contador = 0
lista = [1, "hola", 3, 4, 5]
for elemento in lista:
    if elemento == "hola":
         contador += 1
```

**Comment by rihanuch** [comment]
¡Hola @sjkinast !

En la issue #342 se trata algo sumamente similar, espero eso te deje las cosas más claras 😄

¡Saludos y éxito!🍀
