### ISSUE TITLE
Cuando se usa la reducción de ataque y el anti robo

### ISSUE THREAD

**Issue by dbarraza01** [IIC2233/Syllabus#343]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, espero estén bien. Tengo una duda respecto al evento oleada. Si un zombie aleatoriamente ataque una casilla donde se encuentra un Fensaulantro o un Aresauce ¡es ahí cuando se activa el parametro de reducción de ataque (Fensaulantro) y el parametro anti robo (Aresauce)? 
¿O esos parametros se activan automaticamente cuando hay un ataque de los zombies en cualquier casilla?

**Comment by rodrigoaguilera15** [comment]
Hola, estas plantas deben activar sus respectivas habilidades cada vez que haya un ataque, independientemente de las casillas que sean atacadas.
