### ISSUE TITLE
¿Esta permitido importar librerias en parametros.py?

### ISSUE THREAD

**Issue by kraksiplus** [IIC2233/syllabus#343]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Quiero setear la probabilidad de encallar de distintos barcos mediante el metodo random.random(), ¿es posible dejar seteados este parametro de la forma PROBABILIDAD_ENCALLAR = random() en parametros?  el objetivo de esto es que al instanciar un objeto a una clase barco en concreto deseo llamar a este parametro para setear su probabilidad de encallar

**Comment by manearaya** [comment]
Hola @kraksiplus!

Deberías asignar un valor concreto cada parámetro en parametros.py. Si quieres que cambien entre ejecuciones, los puedes modificar "a mano".

Se usa un valor aleatorio para determinar si se lleva a cabo una acción que tiene cierta probabilidad: si el valor aleatorio es menor a la probabilidad del evento, entonces el evento ocurre. Si el valor aleatorio que quieres asignar en parametros.py es para esto, te recuerdo que el valor no cambiaría a lo largo de la ejecución, por lo que siempre tendría el mismo resultado y esto no estaría bien.

Eso sí, ten ojo porque la probabilidad de encallar de un barco no es un parámetro: es una fórmula y no debería ser aleatoria, sino que depende de otros valores (es la formula (2) del enunciado). Los parámetros son las **tendencias** a encallar de cada barco.

Espero que haya quedado claro, quedo atenta cualquier duda.

**Comment by kraksiplus** [comment]
Perfecto, creo que inicialmente entendi a la formula de probabilidad encallar como un metodo aparte de la instancia self.prob_encallar, en este caso self.prob_encallar = (forlmula enunciado) cierto?

**Comment by manearaya** [comment]
Eso es un pequeño error de enunciado 😅 el atributo que dice "probabilidad de encallar" debería ser la "tendencia a encallar" del barco (el parámetro, que depende del tipo de barco). Cuando tengas que determinar si el barco encalla o no en el método encallar, debes calcular la fórmula del enunciado (issue #260).
