### ISSUE TITLE
Herencia en módulos distintos

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#343]
Hola. Tengo una duda con respecto a cómo puedo hacer que una clase herede de otra cuando se encuentran en distintos módulos. También me gustaría saber cómo usar los atributos de una clase hija si ésta se encuentra en un módulo distinto al de la clase padre. 
Por ejemplo en el módulo de la clase hija coloco:
```python
import "módulo_clasepadre"
class subclase("módulo_clasepadre".clasepadre):
    super.__init__(atributos)
```
Pero al parecer no me lee los atributos así. Tampoco sé si esto se puede hacer, y si se puede, no sé como hacerlo jaja.

**Comment by Camila-sty** [comment]
??????????????????

**Comment by Drpinto1** [comment]
¡Hola @Camila-sty!

Para que una clase herede de otra que se encuentra en un módulo diferente, no deberías hacer nada distinto a una herencia normal, por lo que probablemente tienes un error con el uso de `super()` o con el uso de `import`, por lo que te recomiendo mirar los contenidos asociados a estas dos materias (semana 02, cuaderno 3 y semana 00, cuaderno 2 respectivamente)

Dicho esto, lo más probable es que, si necesitas importar de módulos separados, **exista un error en tu modularización**. Recuerda que la idea de los módulos es que agrupar componentes lógicas y funcionalidades, mientras que la idea de herencia es especializar clases similares, por lo que es muy probable que quieras que ambas clases de una herencia se encuentren en el mismo módulo.

Si te quedan dudas luego de leer los contenidos, pregúntalas en esta misma issue, estaré atento :D

¡Saludos!

**Comment by Camila-sty** [comment]
Ya lo solucioné, gracias.
El tema es que el código estaba sobrepasando las 400 lineas permitidas y aún no terminaba siquiera de realizar todas las acciones que quería programar, entonces me ví obligada a dividir el código en la mitad.
Me queda una duda con lo que mencionaste sobre la idea de la herencia. Lo que pasa es que hice uso de la herencia sólo para hacer uso de los atributos de la clase padre y no de sus funciones, está mal?

**Comment by Drpinto1** [comment]
¡Hola!

Si te ves obligada a dividir una parte del programa en dos módulos, intenta que en cada uno las cosas estén agrupadas de la mejor manera posible (por funcionalidad o según lo que representan las partes del módulo)

Por otra parte, si en tu herencia solamente usas los atributos de la clase padre y no los métodos y/o no agregas comportamiento, probablemente hay algo que no estás considerando, pues la idea de la herencia es representar una especialización de una clase.

Espero que esto te aclare un poco más tu duda :smile:
