### ISSUE TITLE
Distribucion de caracteristicas #30

### ISSUE THREAD

**Issue by jerosalazar** [IIC2233/Syllabus#343]
La distribución de características número 30 es vacía. ¿Que características es posible que tengan esta distribución? Por ejemplo, es entendible que una persona pueda tener problemas de visión con esta distribución (lo que quiere decir que no tiene ningún problema), pero sería extraño que su piel siguiera esta distribución (querría decir que no tiene color de piel).

**Comment by TomasSalvadores** [comment]
Este tipo de distribución lo pueden tener las características de tipo complementarias, o sea, la visión y el pelo corporal.
Si llegara a haber otro tipo de característica con esa distribución, es un error. De ser así, te apreciaría que lo comentaras por acá para corregirlo 😅
