### ISSUE TITLE
Hard Coding

### ISSUE THREAD

**Issue by camirojasguajardo** [IIC2233/syllabus#343]
Hola! No me quedó muy claro qué es 'hard coding' (leí el link de wikipedia y aun así no entendí) ni su diferencia con las variables globales.
Ayuda, me da miedo hacerlo sin querer y tener descuentos jaja

Desde ya, gracias por sus respuestas, saludos!

**Comment by sa-Appel** [comment]
*NO soy ayudante * pero por lo que entendi se refieren a meterle valores a lo bruto , cuando estos debiesen estar en nuestro archivo de parametros.py
por ejemplo para el calculo de quien gana, en lugar de importar el Puntaje_MIN le asignas un valor , como 0.3

**Comment by itmunoz** [comment]
Hola! Como dijo sa-Appel, hard coding es meter valores directamente al código del programa, en vez de sacarlos de una fuente externa, como sería el archivo parametros.py. Meter los valores directamente es una mala idea porque si quieres cambiar un valor, tendrás que buscar por todo el código dónde se usó ese valor y cambiarlo uno por uno.

**Comment by camirojasguajardo** [comment]
ok, muchas gracias!
