### ISSUE TITLE
Funciones de Itertools

### ISSUE THREAD

**Issue by AlanGoldsmith25** [IIC2233/Syllabus#343]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo una pregunta sobre la libreria itertools, se pueden usar todas las funciones y clases dentro de esta?

**Comment by ClemoAcevedo** [comment]
Hola @AlanGoldsmith25 
En #298 se explica que puedes ocupar todos los métodos de una librería si es que está permitida (y si es que no está explícito que cierto método de la librería está prohibido):
![image](https://github.com/IIC2233/Syllabus/assets/101653213/3a2130e5-c5b7-4dce-b913-bf320996850d)
