### ISSUE TITLE
Duda construccion torres

### ISSUE THREAD

**Issue by mjgarrido1** [IIC2233/syllabus#344]
El enunciado dice "Las torres se pueden construir en un Espacio libre solo si hay, a lo menos, un elemento camino adyacente". 

Para esta verificacion tambien debo contar los caminos diagonales a mis espacios libres? o adyacentes significa que compartan "lado" con mi espacio libre? (arriba, abajo, izq, der)

**Comment by DCCollao** [comment]
Hola! Toma como adyacente que compartan un lado. Además, quizás te pueda servir algo de lo discutido en la issue #310, que trata de un tema parecido.
