### ISSUE TITLE
Ataque por alimentar

### ISSUE THREAD

**Issue by arturobugueno** [IIC2233/syllabus#344]
Al momento de alimentar a una criatura, existe una posibilidad de ser atacado (definida por una función). ¿Con relación a qué parámetro ocurre este ataque?

**Comment by mpsubiabre** [comment]
Hola @arturobugueno!

La probabilidad de ataque esta dado por la formula que utiliza el efecto_hambre y el efecto_agresivida, que dependen del estado actual de tu criatura.
Como bien indica el enunciado, el efecto_hambre  se relaciona con el nivel de hambre de la criatura, que es igual a 0 si la criatura esta "satisfecha" e igual a 15 si la criatura está "hambrienta". 
El efecto_agresividad se relaciona con  el nivel de agresividad de la criatura, puede tomar el valor 0 si la criatura es "inofensiva", 20 si es "arisca" y 40 si es "peligrosa".

Espero haber respondido tu duda, de lo contrario comenta esta issue :)

**Comment by arturobugueno** [comment]
Entiendo esto; lo que no se es cuando va a atacarlo. A lo que me refiero es la probabilidad de 'defenderse' del magizoologo. Es decir, con respecto a que parámetro del magizoologo se mide este método.

**Comment by mpsubiabre** [comment]
Creo que tu duda hace referencia a lo respondido en la issue #325. Ahi se explica como se utiliza la probabilidad que obtengas. No tiene relacion con otros parámetros. Revisala :)
