### ISSUE TITLE
Ataque oleadas de zombies

### ISSUE THREAD

**Issue by jtvvtj** [IIC2233/Syllabus#344]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

No entiendo muy bien, como son los ataques de las oleadas de zombies, en el sentido de que si bien, los zombies atacan ciertas casillas diferentes (esas casillas son de forma aleatoria para cada zombie??????????????), en el enunciado aparece en el definición de Defensauce: "Su función es recibir daño mientras protege a las demás plantas.". Entonces yo recuerdo el juego "plantas vs zombies", y me entra la duda, de cómo es eso de que "protege a las demás plantas. ". Porque al final, los ataques se supone que son aleatorios?, no en orden, por lo que se podría dar el caso que hubiera casillas que nunca fueran atacadas por ejemplo, y esas podrían ser plantas de tipo Defensauce, entonces como "protegerían"?

**Comment by rodrigoaguilera15** [comment]
Hola, buenas. Este juego es una versión simplificada del pvz, por lo tanto, la defensa es más o menos simbólica. Efectivamente está pensado para que las casillas atacadas se elijan aleatoriamente, y al final la idea del defensauce es ser capaz de resistir mucho daño. Pero si quisieras implementar un sistema para que la elección de casillas dé prioridad a los defensauce, para que tenga más sentido, esto no iría en contra del enunciado, lo importante es que lo especifiques en el README.

**Comment by jtvvtj** [comment]
comprendooo, muchas gracias :)
