### ISSUE TITLE
¿Puedo usar la librería tabulate para hacer la tabla de los Logs del servidor?

### ISSUE THREAD

**Issue by pvallotton** [IIC2233/Syllabus#344]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

**Comment by AntonioVenegas** [comment]
Hola!, no puedes usar tabulate ya que es una librería externa que requiere instalación, por lo que puede generar problemas al momento de corregir.

Saludos :)

**Comment by AntonioVenegas** [comment]
Corrección, si puedes usar la librería tabulate como se indica aquí: https://github.com/IIC2233/Syllabus/issues/241 (y especificar en el readme que la usaste para que se pueda corregir tu tarea), cuando haya dudas de librerías porfavor hacerlas por la issue de librerías permitidas.
