### ISSUE TITLE
Señales VentanaJuego

### ISSUE THREAD

**Issue by rominaarancibia** [IIC2233/Syllabus#344]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo dudas de que pueden transmitir las señales, en particular si pueden emitir listas de listas desde el backend de juego para actualizar las posiciones de los personajes en el frontend. O bien, en caso de no ser posible que forma me recomendarían para hacer esto. Gracias

**Comment by rominaarancibia** [comment]
Entonces no existe método para enviar listas de listas por medios de señales?. Me podría dar un ejemplo de como sería mantenerlo más simple?
Gracias!

**Comment by tomastrivino** [comment]
> Entonces no existe método para enviar listas de listas por medios de señales?. Me podría dar un ejemplo de como sería mantenerlo más simple? Gracias!

Si no me equivoco sí es posible. Yo tengo un par de señales de la forma `senal_enviar_lista(list)` o `senal_enviar_diccionario(dict)`.

**Comment by lsilvabw** [comment]
cuando creas tu señal puedes decirle a esta que el tipo de dato que recibirá, si lo defines como lista entonces puedes enviar listas de listas también.

`senal_thread = pyqtSignal(list)`

y luego cuando recibes la información de la señal debes manejarla como cualquier lista de lista.
