### ISSUE TITLE
enviar consulta

### ISSUE THREAD

**Issue by fjaraneda** [IIC2233/Syllabus#344]
Hola, este boton esta en el gui y no entiendo como funciona o si debo modificar su comportamiento.

**Comment by Hernan4444** [comment]
@fjaraneda al lado del botón hay una barra para poner texto, la idea es que ahí puedes poner alguna consulta (con el formato que les damos) y al apretar el botón, se agrega dicha consulta a la tabla de consultas. No hay que modificar ningún comportamiento.

Saludos ✌️
