### ISSUE TITLE
Reviews con ","

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#344]
Hola!
Quería preguntar que si al igual que el problema de las columnas, también se van a modificar aquellas reviews que tengan comas (",") en los comentarios. En caso contrario ¿debemos modificarlas en el pre-procesamiento o levantar excepción cuando se consulte por ellas?

**Comment by llloyola** [comment]
Hola! Disculpa, no ando al tanto. Cuál era el problema de las columnas?

**Comment by santilaguna** [comment]
Las columnas en las reviews a veces estaban en orden invertido, es decir, el id después del comentario

**Comment by llloyola** [comment]
Ah, gracias! 😄 

Pd: las "," en comentarios o títulos de película no presenta una problema, a mí parecer.

**Comment by santilaguna** [comment]
@llloyola si, hay otra forma de hacerlo, pero siento que la solución no es genérica (podrían escribir dentro del comentario los caracteres por los que quieres splittear igualmente por eso se , a menos que esté pasando algo por alto.

**Comment by santilaguna** [comment]
Cerré la issue por error
