### ISSUE TITLE
Atributos habilidades y fortalezas

### ISSUE THREAD

**Issue by chineseJack564** [IIC2233/syllabus#344]
Hola,
En el enunciado sale que las fortalezas es un float entre 0 y 1 , estas 2 son parametros, y nos da el rango de variacion de cada fortaleza para cada equipo.
Entonces es necesario en el programa verificar si el rango de cada fortaleza esta dentro del rango permitido?
Gracias!

**Comment by jitorcas** [comment]
Hola! @chineseJack564 

Debes implementar que al momento de instanciar una delegación, a los atributos `Excelencia y respeto`, `Implementos deportivos` e `Implementos médicos` se le asigne un valor aleatorio entre los valores predeterminados para cada delegación. 

Espero haya quedado más claro! Éxito 🥇

**Comment by cristobal-larach** [comment]
cuando se mejore los implementos médicos o implementos deportivos (a través de la acción "Comprar Tecnología"), se debe seguir teniendo en cuenta los límites iniciales del enunciado, y verificar que no se excedan? o estos sólo serán útiles al instanciar la delegación?

**Comment by jitorcas** [comment]
@cristobal-larach 

Los límites son solo cuando se instancia la Delegación, a lo largo del juego esos atributos pueden cambiar dependiendo de las acciones que se van tomando.
