### ISSUE TITLE
Duda sobre si es posible no elegir barco al simular una hora 

### ISSUE THREAD

**Issue by RodrigoFritis** [IIC2233/syllabus#344]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda respecto a simular hora. Asumo que en el primer intento si o si debo elegir un barco para comenzar, pero luego del primer intento, cada vez que simulo una hora debería entrar un barco nuevo? o puedo dar la opcion de no elegir ningun barco y solo jugar con el del primer intento hasta que se termine? 
Gracias

**Comment by mistico0121** [comment]
Tu tarea también debe manejar ese caso. Es posible que haya turnos en los que no entrará un barco, y sin embargo los barcos que hay dentro del canal deberán ser simulados.
