### ISSUE TITLE
Funcion circular

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#345]
¿Que es una función circular? Pregunto esto porque me parece que el ejemplo del enunciado esta malo, no veo en ninguna parte que si f llama a g, g llame a f de nuevo.

**Comment by AmbrosioV** [comment]
#307

**Comment by Hernan4444** [comment]
@jorgeriesco en el ejemplo del enunciado `analizar_consulta` llama a `promedio` y en la función `promedio` se llama a `analizar_consulta`, eso seria una función circular.
Saludos!
