### ISSUE TITLE
Repeticion Bot

### ISSUE THREAD

**Issue by Felipehanckes** [IIC2233/Syllabus#345]
En procesamiento de las reviews del bot, sale que un mensaje del bot tendrá las siguientes caracterisitcas:

1. Tiene 4 o más palabras de su vocabulario, sin contar repeticiones. Por lo tanto, si el vocabulario contiene las palabras hola y chao, y el comentario dice hola hola hola, sólo contamos una aparición.

2. Repite 3 veces al menos una de las palabras de su vocabulario.

3. Tiene entre 6 y 84 palabras totales.

En el punto 2, se toma solo cuando repite la palabra exactamente 3 veces? o cuando la repite a lo menos 3 veces?

**Comment by iqacevedo** [comment]
Hola,

#332
