### ISSUE TITLE
Guardar partida

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#345]
Hola, me surge la duda en que momento se debe guardar en los menus? o mejor dicho en que momento se sobrescribe el codigo luego de jugar un rato.

**Comment by Dnpoblete** [comment]
Hola @Juampisaez  con guardar te refieres a actualizar los datos de los .csv, esta duda ya fue respondida en la issue #274, para que lo revises.

Si esto responde tu duda responde esta issue para poder ayudarte 😄
