### ISSUE TITLE
[T02] Número de ventanas

### ISSUE THREAD

**Issue by Juaco97** [IIC2233/syllabus#345]
En el enunciado se menciona que deben haber dos ventanas: una de inicio y una de juego (puntos 10.1 y 10.2). En la ventana de juego se debe poder prepara la ronda y realizar la ronda; pero dentro de mi lógica había pensado en generar 3 ventanas: la del menú, la de preparación de la ronda y la del juego efectivo (así me evito tener que bloquear la barra de herramientas cuando se esté jugando una ronda), ¿se puede hacer o habría algún inconveniente?

Gracias! :D

**Comment by gatochico** [comment]
Hola! En la issue #279 se habla un poco del tema, pero a grandes rasgos: Para la Ventana de Inicio (Menú), puedes hacer todas las ventanas que quieras, pero debe haber solo **una** ventana de juego, por lo que estaría incorrecto que tengas tu preparación de ronda y ejecución de ronda en diferentes ventanas 😿 Esto es ya que, efectivamente, queremos evaluar que manejes el bloqueo temporal de elementos de una interfaz.

Éxito programando! 💻
