### ISSUE TITLE
movimiento aleatorio

### ISSUE THREAD

**Issue by Cristian1754** [IIC2233/Syllabus#345]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, mi duda surge con el tema del factor aleatorio del movimiento de los fantasmas,  no entiendo si es que este valor aleatorio cambia cada vez que el fantasma se mueve, o si debe ser distinto para cada fantasma o simplemente tiene que ser aleatorio cada vez que se inicie la partida

**Comment by lsilvabw** [comment]
El valor aleatorio es por partida. Respecto si debe ser distinto el valor para cada tipo de fantasma queda a criterio tuyo, ambas alternativas son validas.

Saludos!

**Comment by lsilvabw** [comment]
Al definir el tiempo de ejecución del Qtimer debes considerar que este se da en mili segundos por lo que puedes definirlo de la siguiente manera
`self.timer.setInterval(int(tiempo * 1000))`
Entendiendo que la variable tiempo sera un float, lo multiplicas por mil para pasarlo a segundos y luego lo conviertes en un int.
Espero te sirva de ayuda.
Saludos y éxito !

**Comment by ggmirandac** [comment]
Hola, me cuelgo porque justo una cosa que pregunto @plourido no me quedo muy clara con su respuesta @lsilvabw. ¿Los tiempos son constantes? Es decir, ¿estos no hay que cambiarlos cada vez que el fantasma se mueve?

Saludos,
