### ISSUE TITLE
problema con tildes

### ISSUE THREAD

**Issue by jgespinosa10** [IIC2233/Syllabus#345]
Cuando trato de tratar con los nombres, los tildes en la letras están escritos de una forma distinta. Lo que no me permite contar las letras. ¿Qué puedo hacer?
![image](https://user-images.githubusercontent.com/30691527/30884622-b8552514-a2e6-11e7-8565-720266c3ce3b.png)

**Comment by jgespinosa10** [comment]
Si miras los nombres con tilde en la lista, está escrito así JesÃºs, pero el largo dice que es 5.

**Comment by naazocar** [comment]
#337

**Comment by Arcoirisky** [comment]
Sino, prueba con #341
