### ISSUE TITLE
Puntaje acumulativo usuario

### ISSUE THREAD

**Issue by CrisHD935** [IIC2233/Syllabus#345]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola. Cuando uno ingresa con un usuario y este tiene de record haber completado el tercer nivel, al reiniciar los niveles debe acumularse el puntaje que tuvo al terminar el tercer nivel? O se reinicia a 0.

**Comment by CrisDonosoMaass** [comment]
Hola! El puntaje que obtuvo con el récord es inalterable, ósea si un jugador consigue 1000 puntos y después quiere volver a jugar, su medidor parte de 0 pero su puntaje máximo se debe seguir viendo en el salón de la fama.

**Comment by Segismundios** [comment]
Hola! Una duda respecto a esto mismo. En el enunciado dice : "Cada vez que se termine un nivel se deberá enviar el nombre de usuario, nivel completado y puntaje actual al servidor, y este se guardará un archivo llamado puntaje.txt. Cabe destacar que en este archivo debe existir una única línea por cada usuario que juegue, actualizando tanto el puntaje acumulado como el último nivel completado. Esto quiere decir, independiente de comenzar una nueva partida, los puntajes siempre se suman al valor ya guardado, por ejemplo, si Gewwy0325 jugó un día y logró 1000 puntos, su línea querdaría como Gewwy0325,1,1000. Si al siguiente día juega y hace 500 puntos al completar el nivel 2, su línea se actualizaría a Gewwy0325,2,1500."
¿Qué sucede en el caso en que un jugador ya pasó todos los niveles y luego vuelve a jugar? Se borra su puntaje máximo de la lista de puntajes (procurando tener que éste siga apareciendo en el salón de la fama si es que es de los 5 más altos) para seguir guardando a contar de ahora su nuevo puntaje acumulado (ya que debe haber una única línea por jugador).

**Comment by CrisDonosoMaass** [comment]
CORRECCION: En todos los casos el puntaje se debe sumar al puntaje actual del jugador, si ya termino los 3 niveles con 3000 puntos en total, al volver a jugar se empieza a contar desde esos 3000 puntos. De esta manera se puede respetar que sólo haya una línea por jugador en el archivo .txt. Disculpen por la confusión!

**Comment by CrisHD935** [comment]
Hola, no puedo dejarlo como lo explico la primera vez? Que estuve mucho tiempo cambiándolo a como lo explicó y me voy a demorar mucho mas denuevo para cambiarlo de vuelta, algo de lo cual yo simplemente seguí instrucciones.

**Comment by CrisDonosoMaass** [comment]
Sí, si tienes problemas en la corrección por eso refiere a este issue.

**Comment by dvillas28** [comment]
Respecto a como se gestionan los niveles, cuando un jugador termina los 3 niveles, y luego quiere volver a jugar ingresando su usuario, entonces se deberia mantener el puntaje y comenzar desde el nivel 1?
