### ISSUE TITLE
Regar

### ISSUE THREAD

**Issue by fgallard** [IIC2233/Syllabus#345]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Cuando regar_planta dice que se elige aleatoriamente uno de los dos valores al regar, se refiere a que en cada ronda de riego se elige uno y este aplica para todos, o que para cada planta se elige al azar de forma independiente?

**Comment by PkAlvaro** [comment]
Hola @fgallard 🐶 espero que te encuentres bien.

Te comento, la selección de que valor toma es al azar por cada planta, si te fijas en la figura 9 del enunciado hay un ejemplo donde tienes dos plantas del mismo tipo, que recuperan valores distintos.

Espero que te haya servido la respuesta :)
