### ISSUE TITLE
Calculo de moral de la Delegacion

### ISSUE THREAD

**Issue by domingo2000** [IIC2233/syllabus#345]
Hola, una pregunta, en el enunciado dice que la moral de la delegacion es un int y que se calcula como el promedio de las morales de todos los jugadores, en caso de que este promedio de un float, ¿que hacemos? ¿redondeamos truncamos? o ¿que se hace?

**Comment by amparostevens** [comment]
Hola @domingo2000!
Luego de discutirlo con el equipo, llegamos a la conclusión que lo debes tratar como un **float**
Éxito con la tarea! :sparkles:
