### ISSUE TITLE
Desencallar barcos ilimitadas veces por hora.

### ISSUE THREAD

**Issue by Nicolasramos411** [IIC2233/syllabus#345]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Si es que el canal tiene el dinero necesario para desencallar un barco, ¿Puede intentar desencallar el barco o los barcos encallados más de una vez por hora?, tomando en consideración el hecho de que si se le acaba el dinero entonces la simulación acaba,

Muchas Gracias.

**Comment by DomingoCarvajal** [comment]
Hola @Nicolasramos411!

En el enunciado no sale lo contrario, por lo que si podrías intentar desencallarlo muchas veces.
