### ISSUE TITLE
'VentanaInicio' object has no attribute 'input' T02

### ISSUE THREAD

**Issue by veneguitas** [IIC2233/syllabus#345]
Hola! el error que describe el título es lo que arrojo al probar mi Ventana de Inicio, separé el front-end y el back-end, la ventana se inicia, pero al escribir algo en la línea que se puede editar, me arroja ese error. Busque en google, pero no aparece nada, comparé mi código con ejemplos muy parecidos de los contenidos y sigo sin entender que falla.

**Comment by gatochico** [comment]
Hola! Puedes subir la versión de tu código con el error a tu repositorio privado? :0

**Comment by veneguitas** [comment]
> Hola! Puedes subir la versión de tu código con el error a tu repositorio privado? :0

Ya lo subí!

**Comment by gatochico** [comment]
Si te fijas, lo que ocurre es que no definiste ningún atributo en tu `init` que se llame 'input'. 
Por lo que veo, quieres recibir el valor que se entrega en el **line edit** y almacenarlo en una variable. En tu programa, almacenaste el elemento **line edit** bajo la variable `mensaje2`, entonces si quieres interactuar con este deberías usar `mensaje2` en vez de `input`.

En general, una vez que almacenas un elemento de pyqt5 bajo una variable y quieres luego interactuar con el, debes llamarlo por el nombre de la variable que usaste!

(PD: una vez arregles eso saldrá otro error :eyes: Sin embargo, la lógica tras este es la misma: estas llamando a un elemento que no existe (en este caso nuevo será `resultado`, que no está en el init y deberás cambiarlo por un elemento que si exista en este))

Cualquier duda comenta y éxito! :corn:

**Comment by veneguitas** [comment]
Muchas gracias!
