### ISSUE TITLE
Desplazamiento jugador

### ISSUE THREAD

**Issue by cchauriye** [IIC2233/syllabus#346]
Hola!

En cuanto al desplazamiento del jugador ¿se espera que uno deje la tecla apretada hasta llegar al lugar que quiere o que sean clicks sucesivos con un avance determinado?

Gracias!

**Comment by jeschuwirth** [comment]
Hola,

Como funciona del desplazamiento queda a criterio del alumno siempre y cuando se cumplan las condiciones del enunciado.

Ya que ocupamos PyQt, probablemente termines con un programa que acepte ambos casos. Si presionas varias veces el personaje se moverá de a poco y si se mantiene presionado el personaje se mueve un poco, luego se detiene y por última avanza muchas casillas seguidas.

Si te quedaron dudas comenta en la issue :)

Suerte!
