### ISSUE TITLE
Leer y escribir archivos T03

### ISSUE THREAD

**Issue by papasconketchup** [IIC2233/Syllabus#346]
En python una función pura es aquella que no tiene "efectos secundarios". Dentro de estos está incluido leer y escribir en archivos, ya que eso sería modificar una estructura. ¿Nuestro programa debe ser 100% funcional?, o puede tener algunas funciones no puras? También aplica a la  función print, etc.

Gracias!

**Comment by Hernan4444** [comment]
@papasconketchup la idea es minimizar esos efectos lo mayor posible, pero entendemos que al casos como los que indicas que no. Así que no te preocupes, pueden haber funciones no puras, mientras esté justificado su uso (escribir y print son buenas justificaciones.)

Saludos ✌️
