### ISSUE TITLE
Código funciona en terminal de VS Code, pero no al ejecutar el .py

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#346]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Mi codigo no corre al ejecutar el .py

(Esta duda es relacionada a la tarea, pero no de la tarea en si)

Tengo mi código de la tarea casi listo, y todo este tiempo lo he estado probando en la consola de VS Code, pero
ahora intente ejecutarlo desde el archivo .py y no pasa nada, se abre una consola y se cierra inmediatamente.

A que se puede deber eso? Incluso intente poner un sleep al inicio, pero no lo ejecuta, en vez de esperar la
consola se cierra.

**Comment by mistico0121** [comment]
Prueba a usar el comando python3 para correr tu archivo .py. Quizas es eso.

Cuando uso solo "python main.py" mi computador usa la version de python 2.8 para ejecutar el archivo, mientras que si corro "python3 main.py" lo ejecuta usando python 3.x
