### ISSUE TITLE
separacion front end

### ISSUE THREAD

**Issue by mjgarrido1** [IIC2233/syllabus#346]
para hacerlo de forma mas ordenada (para mi) tengo dos archivos: front_end.py y front_end_2.py. Para efectos de descuentos, esta mal? es necesario agrupar ambos en un solo modulo? o puedo seguir trabajando de esta forma

**Comment by DCCollao** [comment]
Hola! No hay problema con que tengas tu front-end separado. Lo ideal sería que su nombre indique lo que contiene cada uno, pero si ya está programado, con que expliques bien en tu readme qué hay dentro de cada archivo, es suficiente.
Éxito!
