### ISSUE TITLE
Puede haber mas de una funcion normal

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#346]
?crear funcion puede crear distintas funciones de distribuciones con parametros distintos? 
?o las sobreescribe?

**Comment by Hernan4444** [comment]
si es que las asignas a una misma variable, las sobreescribe, pero en otro caso puedes tener una diversa cantidad de modelos de probabilidad normal pero con diversos parametros

Saludos!

**Comment by Dunkan1** [comment]
ya veo, gracias
