### ISSUE TITLE
funcion potenciar

### ISSUE THREAD

**Issue by eldanilop** [IIC2233/Syllabus#346]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

hola, estoy confundido. que evento gatilla que sea necesario usar la funcion potenciar?

**Comment by PkAlvaro** [comment]
Hola @eldanilop espero que estés teniendo un buen día!

Te comento que lo relacionado a potenciar como tal viene dado solamente por el uso de plantas como el Potencilantro o el Cilantrillo, ya que al ser plantadas estas plantas se gatilla la potencia a las casillas directamente colindantes (siempre y cuando estas tengan la cualidad de ser potenciadas).

Espero que te haya quedado mas claro.
