### ISSUE TITLE
Alimentar a DCCriatura si esta se encuentra escapada

### ISSUE THREAD

**Issue by MINGOD24** [IIC2233/syllabus#346]
Queria saber, ya que creo que no sale en el enuciado, si es posible alimentar a una dccriatura si esta se encuentra escapada?

**Comment by JosefaPaz** [comment]
¡ Hola @MINGOD24 !

Como tu criatura se ha escapado, no se debería encontrar disponible para alimentarse. Tu pregunta se encuentra en la issue #273 :)
