### ISSUE TITLE
Duda con Premiar a Deportistas y sus Delegaciones

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2233/syllabus#346]
Hola! algo que no me queda claro es que al premiar a los deportistas y sus delegaciones, el deportista perdedor bajará su moral y su excelencia y respeto.
excelencia y respeto es un atributo tanto de las delegaciones como de los deportistas? o al perder bajaría la excelencia y respeto de su delegación en general?

También, los demás valores de fortalezas (implementos deportivos y medicos) son valores de las delegaciones? o son además de cada deportista de una delegacion? en este último caso, varian para cada deportista o son iguales para todos los deportistas de la delegacion?

gracias!

**Comment by amparostevens** [comment]
Hola @pabloalvarez67 !

El atributo __excelencia y respeto__ pertenece exclusivamente a una __delegación__, al igual que __implementos deportivos__ e __implementos médicos__.
Quizás quedó poco claro, pero cuando un __deportista__ pierde la competencia pasan dos cosas: 
- Su __moral__ baja en cierta cantidad (y dado que la moral de la delegación se calcula en base a la moral de sus deportistas, ésta también bajará). 
- Baja la __excelencia y respeto__ de la __delegación a la cual pertenece el deportista__

Espero se entienda
Éxito con la tarea! ✨

**Comment by pabloalvarez67** [comment]
> Hola @pabloalvarez67 !
> 
> El atributo **excelencia y respeto** pertenece exclusivamente a una **delegación**, al igual que **implementos deportivos** e **implementos médicos**.
> Quizás quedó poco claro, pero cuando un **deportista** pierde la competencia pasan dos cosas:
> 
> * Su **moral** baja en cierta cantidad (y dado que la moral de la delegación se calcula en base a la moral de sus deportistas, ésta también bajará).
> * Baja la **excelencia y respeto** de la **delegación a la cual pertenece el deportista**
> 
> Espero se entienda
> Éxito con la tarea! ✨

Buenisimo! entonces ese valor es al azar para la delegacion que se instancia. gracias!

**Comment by camirojasguajardo** [comment]
hola! una consulta, este atributo se debe mantener siempre entre 0.0 y 1.0?

**Comment by amparostevens** [comment]
Hola @camirojasguajardo!
Tal como dice el enunciado,  _"Estos valores son de tipo float que varían entre 0.0 y 1.0"_
