### ISSUE TITLE
Alerta de error de input durante modo constructor

### ISSUE THREAD

**Issue by mskdancers** [IIC2233/Syllabus#346]
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, tengo dos dudas, ambas sobre como alertar al usuario cuando se produce un error de input en el modo constructor (cuando no quedan elementos para poner o se pone un elemento por sobre de otro).

La manera en la que tengo mi código ahora hace que no sea posible presionar una casilla que ya tiene puesto un elemento en ella (el botón para esa casilla no existe prácticamente), ¿está correcto esto? ¿O tengo que notificarle al usuario explícitamente que no puede poner un elemento por sobre otro?
La segunda es si es que se le puede notificar al usuario de un error de input mediante una ventana pop-up, o si es que necesariamente tiene que notificársele en la misma ventana donde está el juego.

De antemano muchas gracias!!

**Comment by Panconquesocl** [comment]
Holaa😁😁!!, se debería poder presionar una casilla aunque este ocupada y en caso de estarlo se debería alertar al usuario que si es que está ocupada y por lo tanto no se puede agregar una entidad, respecto a tu segunda pregunta la manera de alertar al usuario queda totalmente a tu criterio siempre y cuando no sea por terminal, un pop-up es buena idea en este caso😉👍.
