### ISSUE TITLE
porque ocurre esto?

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#347]
![captursdfsdfsdsdfdddddddddddddddddde](https://cloud.githubusercontent.com/assets/26102365/25553447/a4b7e722-2c89-11e7-8172-71b2f6704286.PNG)

**Comment by Hernan4444** [comment]
@Dunkan1  acabo de copiar el código tal cual en mi consola y los resultados al final son `6, [6] y 120`. Pude ser que tengas metido un import del modulo que tiene ese codigo, como parece que no está dentro de un `if __name__ == "__main__":` cada vez que importas ese modulo se ejecuta todo eso y por ello te aparece dos veces. Pero con solo esa información no puedo suponer otras causas.

Saludos

**Comment by Dunkan1** [comment]
jajajaja cierto siempre se me olvida ponerlo, gracias con eso me funciono
