### ISSUE TITLE
Inicializar el código

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#347]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas. En la imagen que adjunté del enunciado, podemos asumir que el código que inicializa el menú tendrá el nombre de un jardin, la dificultad, y que estos parámetros serán válidos?
<img width="605" alt="Captura de pantalla 2024-09-11 a la(s) 8 36 14 p  m" src="https://github.com/user-attachments/assets/5520b86f-f045-46b9-9f27-3436582ffc1f">

**Comment by AndreaVict** [comment]
Holaa, te recomiendo revisar la _issue_ #337, ya que allí se menciona algo similar a lo que preguntas. Saludos!!
