### ISSUE TITLE
Problema con el tamaño de la ventana

### ISSUE THREAD

**Issue by rubenmalis** [IIC2233/Syllabus#347]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
En el init_gui de la ventana tengo seteado el setGeometry a (400, 400, 500, 500), pero sin importar que vaya cambiando los valores, la ventana que aparece es enorme.

**Comment by rubenmalis** [comment]
Hola, no ocupo ninguno de esos comandos ni similares en el código.

**Comment by AntonioVenegas** [comment]
Entonces te recomiendo que después de `ventana_particular.setGeometry(...)`, añadas en la siguiente línea setMaximumSize(x, y), con x e y las dimensiones máximas que quieres para tu pestaña. Cuentame como te va con eso :)
