### ISSUE TITLE
Movimientos Tarea 2

### ISSUE THREAD

**Issue by josegarafulic** [IIC2233/Syllabus#347]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

1) Se que tengo que usar los sprints para cuando se mueve un personaje del juego. Pero por ejemplo en los fantasmas, simplemente hay que hacer que cambien de forma 3 veces (distintas sprites) en la casilla original y luego poner el fantasma en la casilla siguente?. Porque ese movimiento no se vería fluido. O capaz hay que de alguna manera hacer que la imagen del personaje pase lentamente de una casilla a otra, habiendo un momento en que la imagen esta justo entre ambas casillas.

2) Los threads los voy a ocupar en el backend pero podría definir sin threads el cronómetro en la ventana principal con Qtimer?

**Comment by lsilvabw** [comment]
Respecto a la pregunta 1, debes iniciar la animación cuando el fantasma cambie de casilla, de esta forma su movimiento corresponde con la animación y este se ve fluido.
Respecto a la pregunta 2, te recomiendo mantener los Qtimers en el backend y comunicar los cambios al frontend. Para ver como se puede implementar de manera ordenada revisa la experiencia 4 (ahí esta muy claro el workflow).
Saludos

**Comment by josegarafulic** [comment]
gracias @lsilvabw, pero todavía me queda la duda de la animacion de las casillas. Hay algun momento en que la imagen esta sobre ambas casillas (justo al medio)? . O simplemente hace el salto de una casilla a la siguente (más allá del uso de sprites en cada casilla)

**Comment by MariaJoseSilva** [comment]
Hola!
Cuando una entidad  se encuentra en medio de dos casillas, para revisar las colisiones entre luigi y los fantasmas, ¿considero que la entidad está en ambas casillas o que no está en ninguna? 

Por ejemplo, luigi se está moviendo desde la casilla 1 hasta la casilla 2, y justo cuando está efectuando este movimiento y se  posiciona en medio de la casilla 1 y 2, llega un fantasma a la casilla 1 ¿considero esto como colisión?

**Comment by lsilvabw** [comment]
El criterio de colisión es en los términos absolutos. Si estoy en la casilla X y me muevo a la casilla X+1 donde hay un fantasma, entonces es colisión.
Saludos y exito
