### ISSUE TITLE
Generadores con for y strip

### ISSUE THREAD

**Issue by NicolasCourt** [IIC2233/Syllabus#347]
Estoy creando un generador el cual me recorre una lista de str, pero para compararlo uso el metodo strip. Es valido ya que no estoy modificando la lista original?
            for item in lista_de_str:
                  item2 = item.strip("h")
                  if item2 ...
                     ...
                     ...
                     yield algo

**Comment by Hernan4444** [comment]
@NicolasCourt si es válido porque los string son inmutables, por ello aplicarle un método que los altera te retorna un nuevo string, no modifica el original. Solo ten cuidado cuando trabajes con estructuras mutables, ahí puede pasar que aplicar un método comience a editar algo dentro de tu generador y eso buscamos evitar.

Saludos ✌️
