### ISSUE TITLE
Duda composición parametros.py

### ISSUE THREAD

**Issue by JavaBravo** [IIC2233/syllabus#347]
Hola, mi duda es la siguiente, entiendo que debemos crear un archivo que contenga parámetros constantes bajo el nombre parametros.py, los cuales se encuentran en ESTE_FORMATO (azul) en el enunciado, a pesar de no encontrar nombres de parámetros con ese formato, si encuentro números (en azul) que me dan a entender que son los parámetros que mencionaban. Por lo que mi pregunta es: ¿efectivamente los números en azul del enunciado son los parámetros correspondientes a parametros.py?

**Comment by matiasmasjuan** [comment]
Hola @JavaBravo !

Efectivamente, tal como indica el **enunciado**, todos los **números** en azul son **parámetros** que se deben agregar al archivo ```parametros.py```. El **nombre** de estos **parámetros** quedan a tu criterio, siempre y cuando sean lo más **descriptivos** posibles. Además de los **números en azul**, los *paths* o *rutas* también deben ir en este archivo. Recuerda que además puedes incluir **otros** parámetros si lo estimas conveniente.

Éxito con tu tarea!

**Comment by JavaBravo** [comment]
Gracias!
