### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by mjgarrido1** [IIC2233/syllabus#347]
Deberia definir todos mis atributos de instancia dentro del init? puedo hacerlo fuera?
por ejemplo para construir labels la mayoria de las ocasiones utilizo en el metodo `init_gui`
`self.label = QLabel(self)`
sin definir antes en `__init__` el `self.label `

**Comment by marioreinike** [comment]
Hola! No debería haber problemas con eso, lo único que podría pasar es que caigas en el error de llamar a `self.label` antes de instanciarlo, por eso se dice que hay que definir los atributos en el init. Una manera correcta de hacerlo sería llamar a `init_gui` dentro del `__init__` así evitas cualquier problema en el futuro.
