### ISSUE TITLE
Sanar Lesiones

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#348]
No entiendo muy bien cual es el numero aleatorio. Una vez que se calcula la probabilidad de sanar, se debe tirar un numero aleatorio entre 0 y 1. En el caso que el numero sea mayor a la probabilidad calculada se sana el jugador o es al revés?

**Comment by amparostevens** [comment]
Hola @enriquemolinare !
La fórmula especificada en  __sanar lesiones__ te va a entregar la probabilidad asociada a que el deportista logre recuperarse. 
Para saber si el evento se cumple o no, deberás generar un número aleatorio entre [0, 1] y compararlo con el resultado que te entregó la fórmula.
Si el número aleatorio es __menor o igual__ que la probabilidad calculada anteriormente, entonces el deportista es sanado.

**Comment by enriquemolinare** [comment]
perfecto, graciaas

**Comment by YehudaGurovich** [comment]
Alguna idea de que nombre colocarle a las variables asociadas a los numeros en la función de sanar lesiones?

**Comment by Natydlb** [comment]
muchas gracias!

**Comment by Mamunoz42** [comment]
En base a la primera pregunta, este rango [0, 1] no siempre sera asi verdad? Ya que depende del parametro que va dentro de la funcion o no?

**Comment by amparostevens** [comment]
Hola @Mamunoz42 !
Tienes razón, __0.0__ y __1.0__ son parámetros, por lo tanto pueden variar. Recuerda siempre respetar el rango, sin importar el valor.
