### ISSUE TITLE
Existencia de comentarios positivos

### ISSUE THREAD

**Issue by Felipehanckes** [IIC2233/Syllabus#348]
Es posible que las palabras que nos dieron para medir lo positivo o negativo de un comentario suelan no aparecer en los comentarios de la gente?

Pregunto solo para saber si lo estoy haciendo bien, dado que el maximo porcentaje de comentarios positivos que logro obtener incluso revisando las sub-palabras dentro de palabras mal escritas me da un 33%.

**Comment by rihanuch** [comment]
¡Hola @Felipehanckes !

Vamos a revisar la base de datos y veremos si pasa, pero independiente de si es así o no, el funcionamiento del programa no debería cambiar por ser así o no 😬

¡Confía en tu código ✅ o haz pruebas a mano!

¡Exito y ojalá sea un buen fin de semana largo! 🍀

**Comment by mramirez7** [comment]
Hola, a mi me pasa lo mismo, el 100% de los comentarios parecen ser neutrales. Creo que nadie, al hablar, usa el 40% de sus palabras en adjetivos (menos 60%). Podemos modificar los porcentajes para que la tarea tenga un poco más de sentido??

**Comment by Hernan4444** [comment]
@mramirez7 preferimos que edites el archivo word para que existan más palabras positivas y negativas. De este modo, nosotros solamente cambiamos el archivo al momento de corregir y no tenemos que ir tarea por tarea buscando la línea en donde estén los porcentajes.

Saludos ✌️
