### ISSUE TITLE
Duda sobre la frecuencia de disparo de las zanahorias

### ISSUE THREAD

**Issue by juanivegam** [IIC2233/Syllabus#348]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, ¿la frecuencia de disparo de los cañones la podemos determinar nosotros? Es que no lo encontre en el enunciado.

**Comment by CrisDonosoMaass** [comment]
Hola! Sí, la frecuencia de disparo la deben determinar ustedes añadiéndola al archivo de parámetros.

**Comment by juanivegam** [comment]
Perfecto, gracias. La frecuencia de disparo tiene que ser la misma por cañon o eso queda a nuestro criterio?

**Comment by CrisDonosoMaass** [comment]
Debe ser la misma para todos los cañones en el mismo nivel.

**Comment by benjaminsalgado** [comment]
Hola, estaba revisando las issues y acabo de ver esta, la cual choca con mi implementación de las zanahorias, podría dejar esto escrito en el Readme como un supuesto o consideración, ya que no se encuentra especificado en el enunciado y la única información disponible fue dada hace 3 días en este issue?

**Comment by CrisDonosoMaass** [comment]
> Hola, estaba revisando las issues y acabo de ver esta, la cual choca con mi implementación de las zanahorias, podría dejar esto escrito en el Readme como un supuesto o consideración, ya que no se encuentra especificado en el enunciado y la única información disponible fue dada hace 3 días en este issue?

Puedes dejarlo en consideraciones. Refiere a este issue si tienes problemas en la correccion.
