### ISSUE TITLE
Entregable T03- Como leer Genoma de una persona

### ISSUE THREAD

**Issue by pdesolminihac** [IIC2233/Syllabus#348]
En esta parte del entregable, A que se refieren con "Leer Genoma de una persona",  a como transformar el genoma de una persona a sus características fenotípicas  o a como leer el archivo genomas.txt ?

**Comment by Hernan4444** [comment]
@pdesolminihac se refiere a leer el archivo genoma y lograr obtener sus características (leer + transformar)

Saludos ✌️

**Comment by pdesolminihac** [comment]
Entonces para leer el archivo genomas.txt tambien debe ser a través de funciones atomizadas?

**Comment by Hernan4444** [comment]
@pdesolminihac precisamente 👍 . La idea es que encuentren las diversas operciones que tienen que hacer sobre el archivo para que puedan atomizarlo.

**Comment by fgbruna** [comment]
Pero en la lectura del archivo listas.txt se puede considerar una sola función que haga todas las operaciones ya que es relativamente simple su formato?

**Comment by Hernan4444** [comment]
Es posible, depende de como utilices funcional para obtener todo. Solo recuerda que debes especificar que builtins ocuparás y nosotros despues comentaremos sobre eso.

**Comment by PIPEAPABLAZA** [comment]
@Hernan4444 será mucho pedir que me des un ejemplo de una función en forma atomizada y no atomizada, aún no comprendo bien el concepto.

**Comment by Hernan4444** [comment]
@PIPEAPABLAZA supongamos que la tarea hubiera sido de geometria y una función fuera
>descripción(figura, atributos): dado un string con el nombre de la figura (puede ser "circunferencia" o "cubo") y un diccionario con los atributos de dicha figura, debes imprimir en pantalla una descripción sobre el área de superficie y volumen.

La forma no atomizada sería:

```python
def descripcion(figura, atributos):
    if figura == "circunferencia":
        radio = atributos["radio"]
        area = math.pi * radio**2
        volumen = 4/3 * math.pi * radio***3
        print("La atributos de radio {radio} tiene area {area} y volumen {volumen})
    elif figura == "cubo":
        lado = atributos["lado"]
        area = 6 * lado ** 2
        volumen = lado ** 3
        print("El cubo de lado {lado} tiene area {area} y volumen {volumen})
```
Como podemos notar, descripción se encarga de calcular todo para una circunferencia y para un cubo. Supongamos que tenemos más figura o más datos por cada figura y esta función crecerá mucho más.

Una forma atomizada sería

```python
def circ_descripcion(radio):
      area = math.pi * radio**2
      volumen = 4/3 * math.pi * radio***3
      return area, volumen

def cuadrado_descripcion(lado):
       area = 6 * lado ** 2
      volumen = lado ** 3
      return area, volumen

def descripcion(figura, atributos):
    if figura == "circunferencia":
        radio = atributos["radio"]
        area, volumen  = circ_descripcion(radio)
        print("El circulo de radio {radio} tiene area {area} y volumen {volumen})
    elif figura == "cubo":
        lado = atributos["lado"]
        area, volumen = cuadrado_descripcion(lado)
        print("El cubo de lado {lado} tiene area {area} y volumen {volumen})
```
Ahora puedes ver que la función se redujo un poco de espacio y dispones de dos nuevas funciónes que calcula el área y volumen. Imagina que por "abc" motivo la fórmula para calcular un volumen cambia 😱. Con la version sin atomizar hubieras tenido que buscar entre tus funciones donde usas esa fórmula, ahora solo tienes que ir a una función y editar la fórmula.

El fin de atomizar es que las funciones cumplan un propósito, en el primer caso `descripcion(figura, atributos)` debía filtrar entre la figura, calcular sus datos e imprimir en pantalla esos. Con estole quitamos la pega de calcular y ahora solo filtra entre las figuras, llama a otra función e imprime.

Reitero, imagina que te pido más figuras y más atributos y la primera opción se hubiera alargado mucho más.

Espero que se haya entendido el ejemplo.
Saludos ✌️

**Comment by PIPEAPABLAZA** [comment]
@Hernan4444  OK! , me queda más claro , muchas gracias 👍
