### ISSUE TITLE
ayuda con PyQt5 

### ISSUE THREAD

**Issue by norman123123** [IIC2233/Syllabus#348]
Traceback (most recent call last):
  File "/Users/normanoliden/progra/Syllabus/Tareas/T03/gui/Gui.py", line 1, in <module>
    from PyQt5 import QtWidgets, QtGui
ImportError: No module named 'PyQt5'

Tengo este problema, que significa? googlee y descargué PyQt5 desde la pagina de python pero no se que hacer ahora.

**Comment by iqacevedo** [comment]
Hola

Significa que no tienes PyQt5 instalado (por lo menos en python 3.5). Lee las issues #294 , #305 y #287 para ver si alguna de las soluciones que se comentan te sirve.

Saludos

**Comment by norman123123** [comment]
aun no lo logro, he probado todas las opciones de los issues

**Comment by norman123123** [comment]
Se agrandó el error:

Traceback (most recent call last):
  File "/Users/normanoliden/progra/progra_av/Tareas/T03/main.py", line 1, in <module>
    from gui.Gui import MyWindow
  File "/Users/normanoliden/progra/progra_av/Tareas/T03/gui/Gui.py", line 1, in <module>
    from PyQt5 import QtWidgets, QtGui
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyQt5/QtWidgets.so, 2): Library not loaded: /usr/local/opt/qt5/lib/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyQt5/QtWidgets.so
  Reason: image not found

**Comment by norman123123** [comment]
actualice python y funciono.
