### ISSUE TITLE
Duda con formato de los csv

### ISSUE THREAD

**Issue by aagodoy1** [IIC2233/syllabus#348]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, hay varios Issues con preguntas de los archivos csv pero no encontré nada que responda esto en particular, si hay uno y se me pasó sorry :3
Mi pregunta es que en el archivo de ejemplo que subieron de los canales, eso de dificultad "principiante" o "avanzado" cuando lo corrijan pueden venir escrito de otra manera? Como por ejemplo, puede ser "AvAnZado" o "Príncípíánté", cosas asi? O siempre va a traer única y correctamente escrito ambas palabras?

**Comment by mistico0121** [comment]
Puedes asumir que los nombres de los archivos van a ser los de los archivos de ejemplo. Si de verdad te preocupa, puedes especificar en el README, "se asume que los nombres de los archivos son xxxxxxx.csv e yyyyyyy.csv"
