### ISSUE TITLE
Duda sobre las cartas del juego

### ISSUE THREAD

**Issue by gabo1243** [IIC2233/Syllabus#348]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/326).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/325).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, cuando parte la partida, ¿cada jugador parte con las mismas 15 cartas? (Mostrando solo algunas en pantalla)
Y sobre las cartas en pantalla se dice que deben ser BARAJA_PANTALLA, pero igual no puede ser un valor muy grande porque no cabrian 15 en la mesa por ejemplo. En otra issue dijeron que debe ser un valor con sentido como 5, pero al corregir la tarea ¿cual seria el valor maximo que podrian ponerle a este parámetro? Es que necesito ese maximo para definir un tamaño y lugar de forma que quepan todas considerando un maximo de cartas en pantalla.

Gracias de antemano

**Comment by mtaguero** [comment]
Hola ✨

No necesariamente deben tener las mismas cartas. Como pueden haber distintas combinaciones, sería bueno que ustedes pudiesen armar estos mazos de 15 cartas al azar. Esta es la idea de que hayan +40 cartas posibles.

Con respecto a la cantidad de cartas en pantalla, pensando en que son 15 cartas por mazo, un valor máximo razonable podría ser 7. De todas formas no te preocupes mucho por la corrección, ya que más que evaluar cómo quede en la interfaz lo importante es la funcionalidad.

Espero que la respuesta te haya sido de ayuda. Si no, ¡no dudes en volver a preguntar! 🍃

**Comment by gabo1243** [comment]
Yaa graciass. Igual me di cuenta que la función get_penguins() te da altiro las 15 cartas random entonces no es algo que tenga que hacer yo (creo).

**Comment by mtaguero** [comment]
¡Buenísimo!

Presta atención a todos los detalles del enunciado para que no se te escape nada.
Y por simplicidad te recomiendo dejar el valor de BARAJA_PANTALLA en 5, probablemente no modifiquemos ese valor al revisar.

¡Éxito!
