### ISSUE TITLE
Imprimir plantas al finalizar el juego

### ISSUE THREAD

**Issue by jx4jordan** [IIC2233/Syllabus#348]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado en el punto 2 dice: "luego deberás imprimir cada planta presente en el jardín". Refiriéndose al final del juego.

¿A que se refiere con imprimir cada planta presente en el jardín? 
¿A imprimir cuantas de cada una de las plantas tenía el jardín al finalizar?

El enunciado no menciona nada sobre un método str de la clase Planta o algo del estilo. ¿Se refiere a eso?

**Comment by AndreaVict** [comment]
Holaa, se refiere a imprimir las plantas que quedan en el jardín al momento de finalizar el juego. El como implementar y realizar esto en la tarea queda a tu criterio. Recuerda especificar en el README la decisión que tomaste. Éxito en la tarea!!
