### ISSUE TITLE
Congelamiento de Fantasmas con el cheatcode

### ISSUE THREAD

**Issue by emilio-p** [IIC2233/Syllabus#348]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola buenas tardes, por enunciado se especifica que con la combinación de teclas I + N +F se congela el tiempo, pero no especifica nada de si se congelan los fantasmas también, ¿Hay que congelarlos?. Y en caso de que no haya que hacerlo ¿Qué pasa con el boton de pausa? ¿Puede ser que el cheatcode solo congele el tiempo y el boton de pausa siga funcionando solo para controlar el movimiento de los fantasmas?. 
Muchas gracias de antemano :)

**Comment by jtlledo** [comment]
Hola @emilio-p! El cheatcode 'I + N + F' congela el tiempo y le da vidas infinitas a Luigi, es decir, se da tiempo infinito y vidas infinitas para que se pueda completar el nivel. Por esto, el funcionamiento del nivel debe seguir normal, todos los movimientos de los fantasmas deben ser los mismos, y el botón de pausa debe detenerlos. En resumen, lo único que cambia del nivel la combinación de teclas 'I + N + F' es el contador y las vidas de Luigi, todo lo otro no se ve afectado.
