### ISSUE TITLE
Tiempo tests cases

### ISSUE THREAD

**Issue by VicenteIgnacioSotoGonzalez** [IIC2233/Syllabus#348]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Buenas tardes, junto con saludar quería realizar una duda respecto del tiempo máximo de los tests cases, cuando en el enunciado se refiere a que cada test público debe durar como max 20 segundos se refiera al test publico completo (con los sub tests que cada uno posee) o que cada sub test del test debe durar como máximo 20 segundos?

Por ejemplo test_10_animal_mas_viejo_edad_humana en mi caso dura 20 segundos aprox, por lo que no me queda claro si me estoy pasando del límite o estoy bien ya que tiene 7 tests internos en el que se reparten esos 20 segundos. Gracias de antemano.

**Comment by tcapom** [comment]
Hola @VicenteIgnacioSotoGonzalez !

El enunciado dice

> corroborando que cada test que les pasamos para cada consulta corra en un tiempo acotado de 20 segundos por test, en caso contrario se asumirá un resultado incorrecto.

Significa que cada consulta tiene asignado un archivo de test, el cual tiene un máximo de 20 segundos para retornar los resultados correspondientes.

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Okas, entonces en el ejemplo dado estaría en el límite, no?

**Comment by tcapom** [comment]
Hola @VicenteIgnacioSotoGonzalez !

Si es que te refieres a que tus 7 tests se demoran sobre 20 segundos, te estarías pasando del límite, pero recuerda que la tarea está planteada para que encuentres una solución por debajo de los 20 segundos.

**Comment by VicenteIgnacioSotoGonzalez** [comment]
> Hola @VicenteIgnacioSotoGonzalez !
> 
> Si es que te refieres a que tus 7 tests se demoran sobre 20 segundos, te estarías pasando del límite, pero recuerda que la tarea está planteada para que encuentres una solución por debajo de los 20 segundos.

Sip, en particular me refiero que estando en la carpeta data y en la terminal ejecutando py test_10_animal_mas_viejo_edad_humana.py en total pasando por todos los tests se demora 20 segundos aprox.

**Comment by VicenteIgnacioSotoGonzalez** [comment]
En particular aquí está lo que me sale en consola: 
![imagen](https://github.com/IIC2233/Syllabus/assets/162501853/30cb860b-b062-4ade-80f9-b34c73a438dc)

**Comment by tcapom** [comment]
Hola @VicenteIgnacioSotoGonzalez !

Entendí a lo que te referías. En este caso, te estás pasando de los 20 segundos, pues es la suma de los "subtests de cada test" los que tienen que demorar a lo más 20 segundos.

**Comment by VicenteIgnacioSotoGonzalez** [comment]
> Hola @VicenteIgnacioSotoGonzalez !
> 
> Entendí a lo que te referías. En este caso, te estás pasando de los 20 segundos, pues es la suma de los "subtests de cada test" los que tienen que demorar a lo más 20 segundos.

Okas, muchas gracias por la respuesta :)
