### ISSUE TITLE
Error QtDesigner

### ISSUE THREAD

**Issue by nicoguz** [IIC2233/syllabus#348]
Hola!!
Estoy tratando de crear una ventana con designer donde uso layouts verticales, horizontales y una grid, pero cuando quiero guardarla me tira el siguiente error: "This file contains top level spacers. They will not be saved. Perhaps you forgot to create a layout?".
No se por qué se produce, aiuda por favor!!! :(

**Comment by gatochico** [comment]
Hola! ¿Podrías mandar un pantallazo de tu escritorio de Designer con la configuración que lanza el error? algo así, pero con la interfaz que quieres hacer:
![image](https://user-images.githubusercontent.com/37161120/65931256-4cf75300-e3df-11e9-8e14-bf1ff851003e.png)

De forma preliminar, me encontre con [este link](https://forum.qt.io/topic/45115/top-level-layout-breaks-desired-form-layout/2), donde se menciona que el problema se arregló al agregar un qwidget que sea del tamaño de tu ventana y luego poner todos los layouts y grids que usarás dentro de este. Podrías probarlo :0

Espero tu respuesta!

**Comment by nicoguz** [comment]
Intenté hacer eso pero tampoco funcionó. Al final terminé creando la misma ventana de cero y se arreglo el problema :/. Puede que haya sido un glitch o algun widget suelto. Gracias de todas formas :D
