### ISSUE TITLE
QThread no ejecuta run

### ISSUE THREAD

**Issue by Witomi** [IIC2233/syllabus#348]
Hola!

Al llamar a la función run mediante self.start() en un metodo del thread se me cae el programa, sin embargo cuando lo corro con debug de pycharm no se cae y si se ejecuta run() y nose porque :(

**Comment by iqacevedo** [comment]
Hola! 
¿Tienes puesto el hook para poder ver qué error te tira antes de caer?

**Comment by Witomi** [comment]
Lo tengo puesto en el frontend que es donde corro el programa: 
![image](https://user-images.githubusercontent.com/48265428/58200095-f72bd500-7c9f-11e9-94f6-11d6d511ffc9.png)
 pero el Qthread está en el backend, puse un print antes del self.start() y si llega hasta ahi pero puse otro print en run() y nunca se imprime

**Comment by Witomi** [comment]
Ya lo resolví, al parecer como no guardaba el QThreads en una lista se creaba y  luego se eliminaba al terminar la funcion :)

**Comment by mistico0121** [comment]
> 
> 
> Ya lo resolví, al parecer como no guardaba el QThreads en una lista se creaba y luego se eliminaba al terminar la funcion :)

Me has salvado. Gracias!
