### ISSUE TITLE
funciona generadora con archivo?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#349]
Tengo una duda con el material de la semana anterior.

Probe con la siguiente funcion generadora:

```Python
def gen_lines():
    with open('file.csv', encoding='utf-8') as file:
        for line in file:
            yield line.strip()
```

Que es posible iterar sobre las mismas lineas del archivo, de manera simultanea, sin tener que cerrar el archivo:
```Python
for line1 in gen_lines():
    print(line1)
    for line2 in gen_lines():
        print(line2)
```
En el ejemplo anterior, me di cuenta que no hay problemas con el archivo. Mi dudas son:

1. Es posible realizar lo mismo con un `while True` ? o con un `while`? Dado que ahi, el archivo se mantendría abierto indefinidamente.

2.  De ser posible lo anterior, no ocurren problemas con que el archivo se este usando en una iteración del generador, al crear una segunda (o enésima) iteración?

**Comment by naquiroz** [comment]
No se ha respondido mi pregunta aun 😢

**Comment by DquezadaO** [comment]
1.- Entendiendo tu idea de while True como:

```python
def leer():
    with open("file.txt", "r") as file:
        while True:
            yield next(file).strip()
```

Efectivamente se puede realizar lo mismo con un while True, pero el archivo no se va a mantener abierto indefinidamente porque "file" de por sí es un generador ('_io.TextIOWrapper') y cuando se agoten las líneas del archivo este va a arrojar el error StopIteration que python internamente reconoce como una señal de término de generador (Esto viene de las versiones antiguas de python cuando las clases iterables se construían con \_\_getitem\_\_ en vez de con el método \_\_iter\_\_ raise StopIteration se colocó a modo de que python supiera cuando dejar de iterar). A modo de ejemplo este es un generador de una lista con los números del 0 al 7:

```python
for i in range(20):
    if i == 8:
        raise StopIteration
    yield i
```

Respondiendo a tu pregunta, si bien python es compatible todavía con la utilización de StopIteration para marcar el fin de los generadores ya no es considerado una buena practica y lo que haces con tu "while True" es indirectamente hacer este raise porque fuerzas al archivo a arrojar una vez que se le acaban las líneas a leer.

--------------------------------------------------------

2.- Respecto a lo que dices de que ocurran problemas con el archivo, este tipo de lectura es indiferente a si se usa un while o un for y no debería haber problemas mientras no intentes escribir sobre él mientras lo estas leyendo.

Espero haberte ayudado si quedas con dudas pregunta nomas
