### ISSUE TITLE
Agregación de un objeto entre dos opciones

### ISSUE THREAD

**Issue by tqmbanados** [IIC2233/syllabus#349]
Hola!

En el caso que una clase deba tener una relación de agregación con otra clase, pero esta puede ser cualquiera entre muchas opciones, como se representa en el diagrama de clases? Por ejemplo, la clase A debe tener dentro de sus atributos a la clase B o la clase C, pero no las dos. 

Gracias 😸

**Comment by retamalcito** [comment]
¡Hola @tqmbanados!

En la elaboración del diagrama de clases, no debería ocurrir que un atributo puede tener más de una clase posible 🤔. Quizás te refieres a que las que tú llamas `Clase A` y `Clase B` son ambas **subclases** de una clase llamada, por ejemplo, `Clase C`. En dicho caso, basta con indicar que el atributo es de clase `Clase C` (ya que tanto `Clase A` como `Clase B` son, a su vez, `Clase C`).

En resumen, si tienes un atributo que puede ser un objeto de distintas clases, todas hijas de una misma **superclase**, debes colocar que el atributo es del tipo de la **superclase**. Si este no es el caso, y tu atributo puede ser de dos clases que no tienen relación entre ellas, te recomiendo revisar la modelación de tu programa.

Espero haber contestado tu duda, ¡saludos! 👋

**Comment by tqmbanados** [comment]
Muchas gracias por tu respuesta! Me alcara muchas dudas. Entonces, la flecha de Agregación debería conectar la clase A con la superclase, y no las dos subclases?

**Comment by retamalcito** [comment]
¡Hola!

En efecto, la flecha deberá conectar a `Clase A` con la **superclase**, ya que todos los objetos con los que puede ocurrir la agregación pertenecerán a esta.

¡Saludos! 🥇
