### ISSUE TITLE
Uso de sprites numeros

### ISSUE THREAD

**Issue by CrisDonosoMaass** [IIC2233/Syllabus#349]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/326).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/325).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, estoy haciendo la parte del  despliegue de cartas y tengo una duda si tenemos que usar las cartas de la carpeta cartas o tenemos que crear las cartas con los sprites vacíos y manualmente poner su valor desde la carpeta números. Además, la carpeta números llega hasta 30, pero el enunciado dice que las cartas solo tienen un valor entre 1 y 5.

**Comment by mtaguero** [comment]
Hola ✨

La carpeta cartas se hizo con la intención de que finalmente fuera más fácil para ustedes poder usar estos sprites. Así que no se preocupen por los otros sprites y utilicen las cartas como están creadas.
