### ISSUE TITLE
Lugar donde almacenar datos de los archivos

### ISSUE THREAD

**Issue by Renato-Sierra** [IIC2233/Syllabus#349]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Respecto al contenido de los archivos que me entragan tengo 2 dudas en particular: 

1.- Al ser datos que no variaran a lo largo de la ejecucion del programa, los puedo guardar dentro del archivo parametros.py segun corresponda (asi como leerlos dentro de este)? 
2.- En caso de que lo primero no se pueda, es factible el crear un nuevo archivo .py que cumpla una funcion similar al de parametros.py pero con estos datos?

**Comment by PkAlvaro** [comment]
Hola @Renato-Sierra 🚀 

Efectivamente, debes generar un archivos de parametros.py para los parámetros constantes y luego importarlos donde los necesites.

Para mas información te recomiendo revisar el punto 7.4 del enunciado.

Saludos 👍
