### ISSUE TITLE
Error 'ascii' codec can't encode character '\xf1' in position 2: ordinal not in range(128)

### ISSUE THREAD

**Issue by itplanella** [IIC2233/syllabus#349]
Hola! Estoy creando una ventana que envié una señal al apretar cierto botón, la cual se muestra correctamente, pero cuando agrego la variable  "señal = pyqtSignal(str)" dentro de la clase pero fuera del init, me arroja el siguiente error:

'ascii' codec can't encode character '\xf1' in position 2: ordinal not in range(128)

quisiera saber si me pudieran ayudar a resolverlo ya que no encontré la respuesta en Internet. 
Gracias de antemano.

**Comment by ShescBlank** [comment]
Hola :D es por el nombre de la señal, a las señales no les gustan las "ñ", si lo cambias debería funcionar :)
No soy ayudante, pero me pasó lo mismo cuando estudiaba para la actividad :D

**Comment by itplanella** [comment]
Siii, funciono! Muchas gracias :D
