### ISSUE TITLE
Error con importaciones de archivos.py

### ISSUE THREAD

**Issue by ignaciopena7** [IIC2233/Syllabus#349]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo esta ruta de archivos:
├── carpeta_backend
 |   ├── funciones_cliente.py
 |   └── funciones_cliente_nuevas.py
 |
└── entidades.py
 |
└── main.py

Cuando realizo desde entidades.py la importación from carpeta_backend import funciones_cliente.py obtengo el error: ModuleNotFoundError: No module named 'funciones_cliente'. Desconozco porque sale este si se encuentra "todo en orden", varias veces he intentado cambiar la forma en la que importo y otras veces me arroja otro error el cual es: ImportError: attempted relative import with no known parent package. He intentado buscar información sobre el uso de sys y tipos de importaciones pero no llego a nada concreto para poder avanzar con mi codigo. ¿Cual debe ser la forma más óptima de poder importar y evitar estos tipos de errores?

**Comment by cattpuccino** [comment]
Hola! Para importar un modulo desde una carpeta no es necesario agregar el **.py**, en tu caso, quedaría:
`from carpeta_backend import funciones_cliente`
Si eso aún da problema, fíjate como estas abriendo el entorno de trabajo. Te recomiendo abrir en tu editor de texto la carpeta T2.

Me comentas si sigues teniendo el mismo problema.
