### ISSUE TITLE
movimiento enemigo con ruta mas corta

### ISSUE THREAD

**Issue by emena97** [IIC2233/syllabus#349]
Hola, si yo implemento un algoritmo para que mis enemigos recorran la ruta mas corta, cuando estos llegan a la base, deben seguir mostrando animación en su movimiento, a pesar de que no se estén moviendo?
o una vez que llegan se pueden quedar parados?

**Comment by gatochico** [comment]
Hola! Ya que el enemigo no avanzará más, no es necesario que animes el movimiento. Sin embargo, recuerda que debes animar el **ataque** de los enemigos, dicho en el enunciado:
![image](https://user-images.githubusercontent.com/37161120/58177149-ce8ce680-7c71-11e9-8c91-b109f064afd2.png)

Por lo tanto, no estaría bien que se quedaran "parados" sin ninguna animación, sino que deberían quedarse en su lugar al llegar a la base, pero teniendo una animación cada vez que ataquen a esta. Éxito!
