### ISSUE TITLE
Sobre archivos trolls

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#349]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

**Comment by fernandosmither** [comment]
O por ejemplo que la dificultad de un barco en vez de ser "Avanzada" o "Principiante" sea "Intermedio" Y eso cause error

**Comment by tqmbanados** [comment]
Hola! Me encantó tu pregunta jajaja. 
En general puedes asumir que cambiaremos los archivos, pero manteniendo siempre el formato descrito en el enunciado. Sin embargo, un programa verdaderamente robusto no se cae al "corromper" los archivos. En caso de que tu programa se encuentre con un *archivo troll*, sería un ideal que lo identifique, notifique al usuario, y se cierre correctamente, en vez de lanzar una Excepción. Eso no será evaluado en esta tarea, pero si es una buena práctica que te vayas acostumbrando a hacerlo!

**Comment by fernandosmither** [comment]
> Hola! Me encantó tu pregunta jajaja.
> En general puedes asumir que cambiaremos los archivos, pero manteniendo siempre el formato descrito en el enunciado. Sin embargo, un programa verdaderamente robusto no se cae al "corromper" los archivos. En caso de que tu programa se encuentre con un _archivo troll_, sería un ideal que lo identifique, notifique al usuario, y se cierre correctamente, en vez de lanzar una Excepción. Eso no será evaluado en esta tarea, pero si es una buena práctica que te vayas acostumbrando a hacerlo!

Vale... **A llenar de try/except jajaja**

**Comment by tqmbanados** [comment]
jajajaj pero noo si no es necesario, incluso puede complicar la corrección. Podrías sólamente preocuparte de que los archivos existan por ejemplo, y el resto asumir que no vamos a corromper los archivos apropósito.
