### ISSUE TITLE
Python no me reconoce un booleano correctamente

### ISSUE THREAD

**Issue by imuoz** [IIC2233/syllabus#35]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Es en el ejercicio 2.1, basicamente estoy entregando un valor de ataque y un valor de defensa y al hacer ataque>defensa me da el bool incorrecto. Para corroborarlo tengo un print(ataque,defensa,ataque>defensa) y uno de los casos me entrega "700 1200 True"

**Comment by aaossa** [comment]
Hola @imuoz , lo que describes podría ocurrir debido a que estás trabajando con los tipos incorrectos (`str` en lugar de `int`). El único caso en el que esa operación debería dar un resultado inesperado es al comparar dos *strings*:

```python
>>> 700 > 1200
False
>>> "700" > "1200"
True
```

¿Crees que sea eso lo que te produce el problema? Para revisarlo, te recomiend imprimir los tipos de las vaiables `ataque` y `defensa`, así: `print(type(ataque), type(defensa))`
