### ISSUE TITLE
¿Al eliminar una plaga, hay que reiniciar el bloque en el plano de riego?

### ISSUE THREAD

**Issue by SpartyXD** [IIC2233/Syllabus#35]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, respecto a la función detectar_plagas(), ¿Se debe igualmente reiniciar los planos de riego a 0 cuando se elimina un bloque?

**Comment by vgalfaro** [comment]
Hola! no, no debes reiniciar los planos de riego a 0, solo aquellas celdas con el mismo código del plano de cultivos. Saludos!

**Comment by Ignaciadiazgr** [comment]
Hola! Entonces, las celdas en los planos de riego que corresponden a las del plano de cultivo se deben reiniciar a 0, además de eliminar los cultivos? o solamente eliminar los cultivos sin modificar los planos de riego? Gracias.

**Comment by vgalfaro** [comment]
Hola! no, no debes reiniciar las celdas del plano de riego al eliminar una plaga, por ejemplo, si tu plano de cultivos y riego son respectivamente 
1, 1        0, 3
X, 2       1, 1   
y te piden eliminar una plaga en la coordenada (0,0), lo planos te quedarían
X, X       0, 3
X, 2        1, 1   
por lo tanto solo debes eliminar los cultivos, saludos!

**Comment by vgalfaro** [comment]
Se solaparon los planos, aquí se ven mejor.

Antes de eliminar una plaga en (0,0)
```
1, 1 | 0, 3
X, 2 | 1, 1
```
Después de eliminar la plaga en (0,0)
```
X, X | 0, 3
X, 2 | 1, 1
```

Plano cultivos | Plano riego, respectivamente para ambos.
