### ISSUE TITLE
Adicion de una funcion extra a red.py

### ISSUE THREAD

**Issue by elshavi** [IIC2233/Syllabus#35]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Mi duda es sobre si puedo implementar una funcion extra al archivo red.py fuera de la clase  redmetro, con el objetivo de disminuir la cantidad de lineas de codigo. En especifico esta se encargaria de obtener el indice de una estacion, de la lista de estaciones. Gracias.

**Comment by jprabyb** [comment]
Hola, si puedes, como se explicita en el enunciado puedes crear nuevos metodos,atributos,archivos y funciones que estimes conveniente.

Tambien es importante que toda modificacion que hagas(la funcion que quieres agregar por ejemplo) la debes explicar a detalle en el Readme.

Saludos
