### ISSUE TITLE
Duda acerca del Ejercicio 5.2: Categorizar por grupo

### ISSUE THREAD

**Issue by Kevinnevik** [IIC2233/syllabus#35]
Hola, quería preguntar que cuando define el namedTuple persona, las características, edad y nacionalidad no deberían ir en una lista

**Comment by Juampisaez** [comment]
Efectivamente, debe ser un error al momento de escribir el codigo
Debería ser de la forma
`Persona = namedtuple('Persona', ['edad', 'nacionalidad'])`
Gracias por avisar

**Comment by bimartinez** [comment]
Hola @Kevinnevik!

Efectivamente al momendo de definir una *named tuple* puedes hacerlo a través de una lista con los campos de la tupla (personalmente prefiero esto por temas de orden del código) o un solo *string* donde los campos están separados con comas (`'edad, nacionalidad'`) o espacios (`'edad nacionalidad'`), como nos dice la [documentación oficial](https://docs.python.org/es/3.7/library/collections.html#collections.namedtuple) de *Python*🐍:

> The field_names are a sequence of strings such as ['x', 'y']. Alternatively, field_names can be a single string with each fieldname separated by whitespace and/or commas, for example 'x y' or 'x, y'.

También puedes ver mas de *named tuples* en [este link](https://rico-schmidt.name/pymotw-3/collections/namedtuple.html) el cual contiene información detallada y en español (aún asi recomiendo la documentación oficial).

Si tienes mas preguntas no dudes en escribirlas! 😄 

Saludos!
