### ISSUE TITLE
Datos de los edificios

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#35]
Se puede asumir que todos los edificios van a tener como parámetros los datos entregados en el archivo edificios.csv?, es decir, puedo crear un Centro Urbano con esos datos directamente sin sacarlos del archivo dentro de mi programa? No se si se entiende mi pregunta.

**Comment by lily416** [comment]
Hola :)

No puedes asumir que los datos de `edificios.csv` se mantendrán constantes, ya que para corregir podría ser que cambiemos los archivos, así que debes leer los archivos entregados para cargar o crear una partida.

Saludos 👋

**Comment by jalliende** [comment]
Gracias
