### ISSUE TITLE
Cómo actualizar el tablero una vez ingresada una coordenada válida

### ISSUE THREAD

**Issue by moquezada** [IIC2233/syllabus#35]
Hola, tengo una duda respecto a cuando el usuario ingresa una baldosa válida. Al actualizar el tablero que se mostrará en consola para que el usuario siga jugando, aparte de mostrar el número de Legos que hay aledañas a dicha baldosa, ¿también debo mostrar explicitamente la ubicación de los Legos o estos deben seguir "escondidos"?

**Comment by KnowYourselves** [comment]
Hola @moquezada!

Funciona exactamente igual que en el buscaminas. Cuando se descubre una baldosa válida, **solo se revela esa baldosa** y se pasa a mostrar cuantos legos tiene a su alrededor, **no cambia el estado de ninguna otra baldosa** (A menos que quieras realizar el bonus).

Espero haberte ayudado!

**Comment by moquezada** [comment]
Muchas gracias!
