### ISSUE TITLE
Duda sobre los archivos a subir

### ISSUE THREAD

**Issue by sbarriag** [IIC2233/Syllabus#35]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, cuando entreguemos la tarea en la carpeta de nuestro repositorio que archivos deben estar presentes y cuales no pueden estar en la carpeta? (me imagino que el enunciado no, pero debe estar el README) pero que otros archivos se pueden/deben adjuntar? 
Gracias

**Comment by MaxAl100** [comment]
Hola!
No hay limitaciones de lo que "puedes" subir, pero es buena práctica no subir archivos que no sean necesarios cómo es el caso del enunciado, ya que ocupa espacio innecesario en la nube.
En esta primera tarea ese es el único archivo que puedes no subir, pero tampoco es un problema si lo subes.
Espero que ye haya ayudado y buena suerte en la tarea! 😎

**Comment by ooscarr** [comment]
¿el readme se sube con la tarea (20hrs) o hay más plazo (1 hora después, 21 hrs)?

**Comment by pedrozavalat** [comment]
Hola @ooscarr ,
Se tiene que subir hoy hasta las 20:00 con la tarea.
Saludos :)
