### ISSUE TITLE
Crear planetas

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2233/Syllabus#35]
hola, no me quedo muy claro cuando puedo crear un planeta,

Si estoy en el inicio del juego, antes de entrar en una galaxia, puedo crear un planeta dando un nombre, una raza y además especificando la galaxia a la que pertenece o solo luego de haber entrado a una galaxia.

**Comment by IchottMano** [comment]
Hola! 
Puedes crear un planeta cuando tu quieras, al momento de modificar una galaxia.
Saludos!

**Comment by llloyola** [comment]
Al momento de crear una galaxia debe crearse automáticamente junto con un planeta o se puede tener una galaxia "vacía"?

**Comment by IchottMano** [comment]
@llloyola Una galaxia para ser galaxia debe tener por lo menos un planeta.
Saludos!
