### ISSUE TITLE
Duda sobre metodo os.path.join()

### ISSUE THREAD

**Issue by Crisax234** [IIC2233/Syllabus#35]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, tengo una duda sobre el metodo os.path.join(), ya que al intentar generar una ubicación de algún archivo, lo genera con slash's dobles, como por ejemplo la ruta, 'hola\texto.txt' me la genera como 'hola\\\texto.txt', por lo tanto el programa no puede ubicar el archivo, como se puede solucionar esto? De antemano muchas gracias.

**Comment by Maxy15** [comment]
Hola Crisax234! Una opción para solucionar tu problema es escribir os.path.join('hola', 'texto.txt'), ya que la misma librería te generar los slash en las rutas al momento de imprimirlo o usarlo como string. Espero te sirva.

Quedo atento 👀

**Comment by Crisax234** [comment]
Eso mismo hago sin embargo la consola me tira error ya que la ruta se genera con 2 slash entremedio.
![image](https://user-images.githubusercontent.com/88630837/131229623-49af97b3-cba0-4c00-9aa2-d7f660ee07f5.png)
![image](https://user-images.githubusercontent.com/88630837/131229658-d83f09fa-d6c8-44b0-9ff0-881ea881f865.png)

**Comment by Maxy15** [comment]
Y si intentas con el método normpath? Funciona así:

path = '/home//user/Documents'
norm_path = os.path.normpath(path)
print(norm_path)
-> /home/user/Documnets

Avísame si te funciona!

**Comment by Crisax234** [comment]
El print de norm_path me funciona bien, sin embargo cuando lo intento colocar en la función me tira error denuevo.
![image](https://user-images.githubusercontent.com/88630837/131231106-c9d16919-d75f-47fa-b547-1b63b6e7e4af.png)
![image](https://user-images.githubusercontent.com/88630837/131231109-e3f99b72-da92-4305-867f-883919ab0f89.png)

**Comment by Maxy15** [comment]
Y si lo haces con el path escrito como string "AP0\Ayudantes.csv"?, no es obligatorio el uso de os. Puedes escribir los paths siempre y cuando sean relativos y no globales. 

Quedo atento

**Comment by Crisax234** [comment]
Me sale el mismo error si lo escribo de esa forma, por eso intente con os para ver si se arreglaba pero pasaba lo mismo

**Comment by tqmbanados** [comment]
Hola! Interrumpo para decir que si estas corriendo el archivo desde adentro de la carpeta `AP0`, el path tiene que ser sólo `"Ayudantes.csv"`. Es posible que por ese te diga "path not found" 😸. 
Si tienes windows, es normal que te transforme el path a usar dos ``\``. Esto es por que el carácter `\` es especial al ser usado para agregar caracteres especiales (como `\n`). Para poner un `"\"`, debes colocar **dos** `\`.
Es decir: el string `"\\"`, es leído por python como `"\"`.

Espero ser de ayuda!

**Comment by Maxy15** [comment]
Gracias! Como tengo Mac, desconocía el asunto de los dos "\". Nos avisas si era ese el problema!

**Comment by Crisax234** [comment]
Si lo estoy corriendo desde esa carpeta pero al colocar solo "Ayudantes.csv", me tira el error: FileNotFoundError: [Errno 2] No such file or directory: 'Ayudantes.csv', sin embargo cuando en vs code abro la capeta completa y no el archivo solo como estoy haciendo ahora si me funciona como dices, pero quería ver como hacerlo funcionar sin la necesidad de abrir especificamente la carpeta en vs code en la cual esta mi .py y el archivo, se puede hacer con paths o debo siempre abrir la carpeta completa?

Abrir la carpeta en vscode me refiero a esto:
![image](https://user-images.githubusercontent.com/88630837/131232112-1f46a073-0f64-4f64-93ad-787723006257.png)

**Comment by Maxy15** [comment]
Debería poder hacerse con paths, sin necesidad de abrir toda la carpeta. Puedes adjuntar un pantallazo del error por favor? 🤔

**Comment by Crisax234** [comment]
Aquí esta:

![image](https://user-images.githubusercontent.com/88630837/131232371-78692215-ed5f-43f7-b903-0735f2a5e202.png)

**Comment by Maxy15** [comment]
Deja el path sólo como "Ayudantes.csv", porque ya estás en la carpeta AP0 👀

**Comment by Crisax234** [comment]
Es que si hago eso sin abrir la carpeta completa completa me tira error :/
![image](https://user-images.githubusercontent.com/88630837/131232706-f97d0a71-99c7-4b5e-9db1-baffcd92a755.png)

**Comment by Maxy15** [comment]
Ya mira, me acaban de informar que en Windows es necesario abrir la carpeta para que te funcione en VS Code. Por ende, estabas bien, espero te sirva! 😬
