### ISSUE TITLE
Lógica de ingresar hora y fecha

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#35]
No me queda claro cual es el sentido de ingresar una hora y fecha en el menu. 
Si entiendo bien, es para definir el momento presente en que el usuario esta metido en el programa y cualquier acción que haga, ya sea destinar recursos o consultar información, será afectuada en ese momento, es decir, si consulta donde está un recurso, dirá donde esta el recurso en esa hora y fecha, y si delega un recurso, se registrará que en ese momento el recurso parte hacia la zona que le fue destinada. 
Lo que me hace ruido es que parece como un viaje en el tiempo cada vez que se ingresa al sistema. Ingresas y eliges el momento en el que quieres estar para delegar cosas o consultar que está pasando en ese momento.
Si estoy completamente equivocado agradecería una aclaración, si no, cualquier aporte para entenderlo mejor o complementar algo que omití también sería de gran ayuda.

**Comment by Dunkan1** [comment]
tambien sirve para calcular el area del incendio en ese momento, y si a mi tambien me parece un viaje en el tiempo ya que el usuario pondria la fecha que quisiera, pero como en la guia no dice nada al respecto entonces no creo que importe

**Comment by rpalmaotero** [comment]
Es un viaje en el tiempo 😀. Cada vez que se cambie la hora el programa deberá recalcular el estado de la situación basado en las estrategias que se han calculado.

**Comment by acrojas2** [comment]
Quizas es un poco tonta mi duda, pero gracias a esta pregunta lo que me hace ruido a mi es que como el usuario puede poner cualquier fecha, este podría ingresar con una fecha determinada y luego podría ingresar al sistema con una fecha anterior a la que ingreso en principio, esto puede pasar? y si pudiera pasar, los datos deberían estar actualizados de acuerdo a la fecha mas reciente (considerando una linea de tiempo, no la fecha con que ingreso el usuario en la ultima vez que ingreso la fecha)?????
