### ISSUE TITLE
birds?

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#35]
Hola, parece q el generador de csvs(csvgenerator.csv) tiene un error.
Cuando en ves de generar ordenes de tipo bid genera ordenes de tipo bird.

Si esto no es un error me disculpo

**Comment by Hernan4444** [comment]
@Kitaps efectivamente el csvgenerator.py tenía un ligero error. Muchas gracias por avisa, acabo de subir el código de nuevo sin dicho error 👍 

Saludos!!
