### ISSUE TITLE
Registro de usuario con espacios

### ISSUE THREAD

**Issue by CristobalUrzua** [IIC2233/syllabus#35]
Al momento de registrar a un usuario, este ¿podría contener espacios?
y si es así, ¿esto también se tomaría en cuenta para la extensión mínima?

Por ejemplo: Leo oss1 

Este ejemplo no cumpliría con el mínimo de caracteres alfanuméricos, pero su longitud si es 8.

Pero por ejemplo: Leo ossa1

Si cumpliría con el mínimo de caracteres alfanuméricos, pero su longitud es 9.

De antemano gracias.

**Comment by MatiasDuhalde** [comment]
Hola! 

Quizás el enunciado no sea lo suficiente explícito, pero **todos** los caracteres de los nombres de los usuarios deben ser **alfanuméricos**.
Si tomamos los nombres que pusiste de ejemplo, ninguno de ellos sería válido, puesto que contienen un espacio, el cual **no** es un carácter alfanumérico.

_**Tip:** Los carácteres alfanuméricos son **A-Z a-z 0-9**, pero existe un método de strings que te permite analizar si un string contiene sólo caracteres alfanuméricos ;)_

Éxito en tu tarea!
