### ISSUE TITLE
Validez de competencia

### ISSUE THREAD

**Issue by chineseJack564** [IIC2233/syllabus#350]
Hola, 
Cuando un equipo no cumple el implemento requerido po un deporte y el otro equipo si lo cumple gana automaticamente el otro equipo o no?
En el caso que ambos no cumplen debe haber un empate?
saludos!

**Comment by jitorcas** [comment]
Hola! @chineseJack564 

Si una Delegación **no cumple con alguno** de los requisitos necesarios, **pierde automáticamente la competencia**, independiente si la otra Delegación cumple con los requisitos. 

Si la delegación X **cumple** con todos los requisitos y la delegación Y **no cumple** entonces gana la delegación X. 

Si ambas Delegaciones pierden la competencia, entonces se declara un empate. 

Mucho éxito! 🥇

**Comment by cnillanes** [comment]
Hola! Me surgió una duda leyendo esto :(
No entiendo el punto 1 de la respuesta ya que si reviso Crotona primero y no cumple la dejo de perdedora sin haber revisado si Esparta los cumple? eso entre que no me hace sentido y me parece injusto jaja

Ojalá puedas re explicarme ese punto,
Gracias :D

**Comment by jitorcas** [comment]
Hola! @cnillanes 

Lo siento! Me faltó especificar que ambas Delegaciones deben ser validadas antes de determinar quién gana o pierde. Al referirme con **pierde automáticamente** no me refiero a que se deba dejar de inspeccionar a la otra Delegación, si no que no hay manera que gane la competencia, independiente de si la otra Delegación cumpla o no con los requisitos. 

Espero me haya expresado mejor.
Mucho éxito! 🥇
