### ISSUE TITLE
Duda con la excepcion Bad Request

### ISSUE THREAD

**Issue by andreslyon** [IIC2233/Syllabus#350]
Hola, no me queda muy claro lo que tiene que hacer esta excepcion. Dice:
_ . . . que no existe dentro de
las consultas solicitadas y no se puede procesar._ 
A que se refiere con esto?
Gracias :)

**Comment by Hernan4444** [comment]
@andreslyon se refiere a que te llegue una consulta que tu librería no es capaz de procesar. Por ejemplo: una nueva consulta (no implementada) o una consulta que si existe pero mal escrita y por lo tanto no es posible determinar que hacer.
Saludos ✌️
