### ISSUE TITLE
Duda Objetivos Tareas 

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#350]
La sección Objetivos de los enunciados de las tareas son para guiarnos en lo que debemos usar en la tarea? O da igual que para resolver mi problema no use alguna de las cosas especificadas en dicha sección?

**Comment by Hernan4444** [comment]
@llloyolan no da lo mismo que utilizar para resolver el problema. La sección objetivos indica lo que principalmente se va a evaluar en la tarea y recurrir a otra forma no cumple con lo esperado.

Saludos ✌️

**Comment by llloyola** [comment]
Mmm... Y me pueden bajar nota en una tarea por no usar algo que no está especificado en el enunciado?

**Comment by Hernan4444** [comment]
Si puede llegar a bajar:
1) Si es que se dijo algo en una issue (generalmente le ponemos label importante)
2) Si es que se dijo en clases
3) Si era algo que se debía aplicar en la tarea pero era trabajo de ustedes darse cuenta con los contenidos vistos en clases (no estaba explicito)

Pero si encuentra que el descuento no es justificado, manda a recorregir y ahí obtendrás una respuesta más justificada sobre tu solicitud.

Saludos ✌️
