### ISSUE TITLE
Cambiar color a barra de vida

### ISSUE THREAD

**Issue by furzuadr** [IIC2233/syllabus#350]
Hola! Estuve tratando de cambiarle el color a la barra de vida para que quedara como en el enunciado:
<img width="246" alt="Screen Shot 2019-05-22 at 9 59 30 AM" src="https://user-images.githubusercontent.com/48994882/58180628-6b528280-7c78-11e9-8312-0d3c60158214.png">
No encontré ninguna forma para hacerlo, así que creé una función que me cambia el _styleSheet_ al color que se le entregue, pero esto cambia la barra a tipo _chunk_ y queda de la siguiente forma:
<img width="157" alt="Screen Shot 2019-05-22 at 9 59 10 AM" src="https://user-images.githubusercontent.com/48994882/58180802-ab196a00-7c78-11e9-9297-427ac1c97686.png">
Hay alguna forma de que quede como el enunciado? Supongo que no importa que quede como lo hice, pero quiero arreglarlo por temas estéticos. Gracias!

**Comment by lily416** [comment]
Hola 😄 

No es necesario que la barra se vea como en la imagen del enunciado, es solo un ejemplo para que les sea más fácil hacerse una idea de lo que deben hacer.

Si aun asi quieres modificar como se ve, el siguiente [link](https://stackoverflow.com/questions/9368824/change-the-color-of-a-qprogressbar) puede que te sea de ayuda (especialmente el comentario de castors33). También te invito a investigar las opciones que entrega Qt para personalizar las QProgressBar.

Ánimo y éxito con la tarea 👋 🐈🐧
