### ISSUE TITLE
Python restarts Shell

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#350]
En el proceso de crear el interprete de consultas, hago algunos prints para chequear el avance. El problema es que no se termina dicha ejecucion debido a que el IDLE resetea el Shell y cierra la GUI. Algun motivo aparente para esto? 

 RESTART: Shell

**Comment by Hernan4444** [comment]
@benjamimo1 puedes reformular tu pregunta, no logro entender lo que quieres decir :c
Saludos!!

**Comment by benjamimo1** [comment]
Jajaja, voy con el segundo intento entonces.
Parte de la tarea es diseñar el "interprete" que lee los comandos y retorna el resultado. (process_consult). Segun yo, el codigo de mi interprete esta bien, pero a mitad de camino este "muere" y el programa se resetea.  
No levanta ningun tipo de error, simplemente Python resetea la consola (sin cerrarla) e imprime: -----------RESTART: Shell------
Terminando la ejecucion de mi interprete a mitad de camino.
Espero se entienda jaja
Saludos!

**Comment by negutierrez** [comment]
No se si es lo mismo, pero cada vez que yo corría python por segunda vez se me reiniciaba el nucelo del python. 
Lo arreglé cambiando ''app = QtWidgets.QApplication(sys.argv)'' del main por:
    app = QtWidgets.QApplication.instance()
    if app is None:
        app = QtWidgets.QApplication(sys.argv)

**Comment by benjamimo1** [comment]
@negutierrez  Lo intentare ahora y te aviso!

**Comment by indonoso** [comment]
Intentaste no usar idle? usar la consola directamente?
