### ISSUE TITLE
duda potencial cilantrillo

### ISSUE THREAD

**Issue by DiegoRODestudiante** [IIC2233/Syllabus#350]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, no estoy entendiendo bien como funciona el potencial y el aumento en cilantrillo, en el caso del potencial dice que debe ser un float entre 0 y 1 pero que debe ser mayor al de su clase padre, y no le encuentro el sentido ya que como sería mayor si tiene que ser entre 0 y 1, y el potencial de su padre es un numero aleatorio y en ese caso el máximo valor que podria tomar el potencial de su padre tendria que ser negativo, no sé en verdad no me hace sentido

**Comment by AndreaVict** [comment]
Holaa, el incremento en los valores del potencial y el aumento del cilantrillo se refiere a que las constantes de la clase padre aumentaran su valor en una proporción de un AUM_POT_CIL% y AUM_AUM_CIL% respectivamente. Saludos!!
