### ISSUE TITLE
Configurar tamaño de un QIcon en un QPushButton

### ISSUE THREAD

**Issue by burgosibarra** [IIC2233/syllabus#350]
Hola, por más que he leído en internet no logro que la imagen (icono) de un botón sean del mismo tamaño.
Este es un ejemplo de mi código 
`boton = QPushButton(self)
boton.resize(QSize(VALOR_1, VALOR_1))
imagen = QIcon(PATH)
boton.setIcon(imagen)
boton.setIconSize(QSize(VALOR_2, VALOR_2))`
Por más que aumento el valor a VALOR_2 el icono tiene una relación de proporcionalidad con el boton

**Comment by aundurraga** [comment]
Hola! Puedes hacer un Qpixmap, escalarlo, y luego agregarlo al botón:
imagen = QPixmap(PATH).scaled(VALOR_2,VALOR_2)
icono = QIcon(imagen)
boton.setIcon(icon)
boton.setIconSize(QSize(VALOR_2, VALOR_2))
 O también puedes probar borrando el borde del botón, usando boton.setStyleSheet('QPushButton{border: 0px solid;}').  Debes considerar que en este último caso simplemente estás haciendo que el borde sea transparente, por lo que al hacer click en el borde igual estás apretando el botón.
Espero que te sirva!

**Comment by burgosibarra** [comment]
Me ha funcionado sin quitar los bordes
muchas gracias!!!!
