### ISSUE TITLE
[Detalle] Salir en menús

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#350]
### El enunciado dice que todo menú debe llevar la opción de salir del programa completamente, sin embargo, menús son solamente los detallados en el enunciado, o si en un caso muy hipotético, crease un pseudo-menú para elegir canal, también debería tener la opción de salir?

**Comment by manearaya** [comment]
Hola @fernandosmither!

Si creas un menú, este debería tener la opción de volver atrás y salir al igual que el resto de los menús del programa. Sin embargo, elegir un canal puede ser considerado como una acción y no como un menú en sí, por lo que podrías omitir las opciones de volver y salir (issue #323, aunque quizás podría ser útil implementarlas).

Saludos!

**Comment by fernandosmither** [comment]
> Hola @fernandosmither!
> 
> Si creas un menú, este debería tener la opción de volver atrás y salir al igual que el resto de los menús del programa. Sin embargo, elegir un canal puede ser considerado como una acción y no como un menú en sí, por lo que podrías omitir las opciones de volver y salir (issue #323, aunque quizás podría ser útil implementarlas).
> 
> Saludos!

Vale! saludos
