### ISSUE TITLE
Rúbrica criterio "A medida que avanza de nivel, ConejoChico aumenta su velocidad."

### ISSUE THREAD

**Issue by tcapom** [IIC2233/Syllabus#350]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Dentro del puntaje designado para conejo chico aparece el siguiente apartado, donde tengo una duda en el tercer recuadro:

![image](https://github.com/IIC2233/Syllabus/assets/141950883/0f0693d6-02d9-4ce7-8c70-29119b2beecf)

En este se indica que el conejo debe aumentar de velocidad, pero esto nunca aparece en el enunciado, apareciendo el siguiente cálculo para la velocidad (Figura 4):

![image](https://github.com/IIC2233/Syllabus/assets/141950883/699c4657-2c71-4629-ac6a-c426fd90c4ff)

De hecho, para los lobos efectivamente hay que aumentar la velocidad de ellos a través de los niveles (Figura 2).

![image](https://github.com/IIC2233/Syllabus/assets/141950883/fb500139-fc2e-4e64-a89e-fc30b4137b4c)

Pero este cálculo no aparece reflejado en la rúbrica.

![image](https://github.com/IIC2233/Syllabus/assets/141950883/3e16fcaf-748a-4cee-88c1-8097d81165c7)

A qué hay que hacerle caso?
De antemano muchas gracias

**Comment by CrisDonosoMaass** [comment]
Hola! Hazle caso al enunciado, la velocidad del conejo debería ser constante mientras que la de los lobos aumenta con los niveles.
