### ISSUE TITLE
Problema al hacer git push

### ISSUE THREAD

**Issue by MariaJoseCovarrubias** [IIC2233/syllabus#350]
Hola, al momento de hacer git push me tira el siguiente error. Llevo mucho rato intentandolo y no se como resolverlo! Gracias!

![Captura de pantalla 2020-04-08 a la(s) 17 25 24](https://user-images.githubusercontent.com/54035477/78835335-01d98080-79be-11ea-85c4-f0f1f84e6d0e.png)

**Comment by MariaJoseCovarrubias** [comment]
Gracias pero ya pude hacerlo! No sé por qué pero se me subió un commit que había hecho hace 40 minutos y que no se había podido ejecutar. ¿Cuál es la razón?

**Comment by JosefaPaz** [comment]
¡ Hola @MariaJoseCovarrubias !

Disculpa la demora en contestar, a veces los ```git commit``` no logran ejecutarse porque se subieron mal los archivos, hay diferencias con el repositorio local, etcétera. Pueden ser bastantes fallas en verdad jajaja Si quieres ver porqué es el problema la próxima vez, busca el error que te tira git en internet, y eso te permitirá tener más nociones de porqué sucede ese error.

Éxito en la tarea! 😸
