### ISSUE TITLE
repetición de animales en ponderadores.csv - animales_segun_edad_humana()

### ISSUE THREAD

**Issue by vicntealonso** [IIC2233/Syllabus#350]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Buenas, una consulta, ¿Cuál sería la mejor forma de gestionar la repetición de especies de animales en el archivo ponderadores.csv dentro de la consulta animales_segun_edad_humana? Ya que esta repetición genera disparidades al ejecutar los tests asociados. Por ejemplo, en el ponderadores.csv de "m", la especie "Escarabajo rinoceronte" se repite en las líneas 104 y 182 con dos ponderadores distintos.

**Comment by ClemoAcevedo** [comment]
Hola @vicntealonso , debería haber 1 ponderador por especie, se va a corregir.

**Comment by njllanos** [comment]
Hola, con respecto a estas repeticiones, se dan en más de una ocación para distintas especies y en los 3 distintos tamaños de archivo. Especificamente la cantidad de repeticiones por especie en cada archivo es:
Estrella de mar': 5, 'Suricata': 3, 'Pez globo': 3, 'Erizo de mar': 3, 'Erizo de tierra': 3, 'Caballito de mar': 2, 'Escarabajo rinoceronte': 2, 'Petauro del azúcar': 2, 'Medusa': 2, 'Estrella frágil': 2, 'Estrella espinosa': 2.

**Comment by ClemoAcevedo** [comment]
Gracias @njllanos , mañana se revisarán las repeticiones
