### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2233/syllabus#351]
Perdon por hacer esto, pero tengo abri una issue con un error que no pude arreglar y en el que me dejaron el visto... (se que fue fin de semana largo pero obtuve un comentario que me dejo parado donde mismo y nada mas)  Llevo 2 dias intentando hacer algo y no puedo, ojala que puedan ayudarme en lo que se pueda.

La issue es la [#322](https://github.com/IIC2233/syllabus/issues/322)

**Comment by jmwielandt** [comment]
Hola!
No te he dejado el visto. Hace un rato cloné tu repo y lo estoy revisando.
Te responderé en un rato.

PD: si me mencionan es más probable que lo vea en un menor tiempo, ya que me sale la notificación en telegram.

**Comment by lfuenzalida2** [comment]
Perdona, fue mala mia, es que como no habias respondido pense que te habias olvidado y  tambien llevo 2 dias buscando informacion sin poder avanzar asique estoy bastante preocupado
