### ISSUE TITLE
Actualización GUI T03

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2233/Syllabus#351]
¡Hola!
Si es que han tenido problemas con las consultas, al seguir las instrucciones del enunciado, para poder leer el archivo _consultas.json_. Vuelvan a hacer PULL del repositorio. Ya debería de estar solucionado el error.

Gracias por avisar, saludos y ¡éxito! :D

**Comment by Jiruiz2** [comment]
Hola, hice pull hace poco, pero al hacer la consulta valor característica, el programa me manda el siguiente error [https://ibb.co/iBVyWG](url) y quería saber si este error ya lo arreglaron y yo no he sobrescrito bien los comandos.

**Comment by Jiruiz2** [comment]
Hola, hice pull hace poco, pero al hacer la consulta valor característica, el programa me manda el siguiente error  y quería saber si este error ya lo arreglaron y yo no he sobrescrito bien los comandos.
![problema interfaz](https://user-images.githubusercontent.com/26437497/31095016-97558e02-a78d-11e7-819b-14282b88acd1.PNG)
