### ISSUE TITLE
Visualización de Gráficos 

### ISSUE THREAD

**Issue by fantinee** [IIC2233/Syllabus#351]
Disculpen mi duda es si los gráficos se ven como pop-up window o hay que hacer que se vean directamente desde la ventana de la interfaz grafica, ósea desde aquí:

![image](https://cloud.githubusercontent.com/assets/26147098/25557182/996a8b0a-2ce2-11e7-9dee-87b711343679.png)

**Comment by Hernan4444** [comment]
@fantinee como pop up.

Saludos!!
