### ISSUE TITLE
Caracteristicas bot

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2233/Syllabus#351]
Hola!
Para identificar el comentario de un bot, debe cumplir con las tres características al mismo tiempo, o es al menos una.

**Comment by norman123123** [comment]
ya, perfecto y si un comentario es de bot, se descarta todo el comentario ?

**Comment by mfanselmo1** [comment]
![image](https://user-images.githubusercontent.com/26393563/39397802-6fa6486e-4adb-11e8-9403-0293845daa35.png)
> los cuales debes eliminar 

Por favor revisen el enunciado antes de hacer issues.
