### ISSUE TITLE
Tener dos sprites sobrepuestos en el mismo QLabel

### ISSUE THREAD

**Issue by szabala** [IIC2233/syllabus#351]
Hola! llevo mucho tiempo buscando el la documentacion de PyQt5 como poder hacer un "merge" entre dos sprites, para que se muestren al mismo tiempo en un solo QLabel. Por ejemplo, como muestra el enunciado, los sprites en rojo corresponden a dos sprites "sobrepuestos".

![ejemplo](https://user-images.githubusercontent.com/48331715/65926942-08af8700-e3ce-11e9-8054-b194e5b09204.png)

La mayor cantidad de ejmplos con QPainter estan en C++ :c

**Comment by jmwielandt** [comment]
Hola!

No necesitas usar QPainter para ello (aunque nada te lo impide). Lo que puedes hacer es aprovechar que el fondo de la casa es transparente y tener dos QLabels independientes, cada una con una imagen, en el mismo lugar.

Saludos!

PD: es cosa de tiempo que le agarres la maña a traspasar la docu de C++ a Python, el built-in de python "help" te puede ayudar para saber los tipos de los argumentos de los métodos y clases, principalmente 😉. También si le haces help a un módulo, te dice todo lo que trae, es muuuuy útil :3

**Comment by jmwielandt** [comment]
Hola @szabala !

No cierres las issues, ya que pueden servir a tus compañeros.
Nosotros las cerraremos cuando sea oportuno.

Ánimo con la tarea!

**Comment by Paldana99** [comment]
Pero por ejemplo si utilizo una grilla, y la casa la puse en el espacio 2, 2. Si situó un nuevo elemento en la grilla 2, 2 (el pasto por ejemplo) se borra la casa. Como se podria solucionar? o es mejor no utilizar una grilla

**Comment by davidpuntoarias** [comment]
@Paldana99 Si se pueden colocar dos QWidget en la misma coordenada de un QGridLayout, simplemente debes crear dos QLabel distintos y asignarles las mismas coordenadas. Por ejemplo:
grid = QGridLayout()
grid.addWidget(QLabel("1"), 0, 0)
grid.addWidget(QLabel("2"), 0, 0)

PD: Ten cuidado porque la que se coloca primero es la que se queda en el fondo.
