### ISSUE TITLE
Mapas

### ISSUE THREAD

**Issue by mjgarrido1** [IIC2233/syllabus#352]
Puedo asumir que siempre los mapas comenzaran sin espacios libres en los extremos? Al ver los mapas entregados todos cumplen que tienen  X en todos los extremos (a excepcion de cuando aparece S)

**Comment by jaromero6** [comment]
Hola:
No se puede asumir eso, el mapa podría tener espacios libres en las esquinas, la idea es que tu programa sea capaz de leer el mapa tanto si tiene o no tiene espacios libres en las esquinas.
Mucho ánimo con la tarea.
