### ISSUE TITLE
Archivos .qrc QtDesigner

### ISSUE THREAD

**Issue by dpvillarroel** [IIC2233/syllabus#352]
Hola!

Cuando trabajo con QtDesigner y guardo imágenes se crea un archivo .qrc, estos archivos los dejo en la misma carpeta de sprites o los tengo que guardar en una carpeta aparte para que se ejecute correctamente en otro computador?

**Comment by aljara97** [comment]
Hola, para ver si un archivo generado por QtDesigner es recomendable que hagas una copia de la carpeta que contiene tu tarea sin estos archivos y pruebes si son prescindibles o no. 
En caso de que sean necesarios para el funcionamiento de tu tarea debes subirlo al repositorio, en caso de subir archivos de imágenes extras a los contenidos en la carpeta ```sprites`` (esta carpeta debe ignorarse mediante el archivo ````.gitignore``` :eyes:), esto se hace en una carpeta extra y debe especificarse en tu readme.
Cuéntame cómo te va y mucho éxito en tu tarea 👍

**Comment by dpvillarroel** [comment]
Son necesarios para la ejecución! gracias

**Comment by aljara97** [comment]
Ok, no olvides especificarlo en tu readme. Para la próxima no cierres una issue, luego nosotros lo haremos, puede servirle a otro compañero :)

**Comment by kisco99** [comment]
Hola! Me pasa que tengo mi archivo .qrc y .ui en la misma carpeta que mi código, pero aún así me tira error.
<img width="660" alt="issue 1" src="https://user-images.githubusercontent.com/53839911/66141302-d7a3a200-e5d9-11e9-9ac3-adc098e89bad.PNG">
<img width="545" alt="issu2" src="https://user-images.githubusercontent.com/53839911/66141312-dbcfbf80-e5d9-11e9-9715-948e8f116dc4.PNG">

**Comment by aljara97** [comment]
Hola @kisco99 lograste solucionar el problema? De no ser así puedes comentar la forma en que importas el archivo qrc?
