### ISSUE TITLE
Envio de mensajes en formato diferente a string (no pickle)

### ISSUE THREAD

**Issue by endlessloop2** [IIC2233/Syllabus#352]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, quería saber si hay libertad en la forma de enviar los mensajes, mientras se respete la codificación y encriptación, o si estamos obligados a usar la funcion serializar_mensaje y solo enviar strings.

Es decir, me gustaría saber si por ejemplo, se permite encodear ints y enviarlos como parte del mensaje encriptado y luego codificado? O, enviar JSON como texto plano, encriptarlo, codificarlo y enviarlo?

**Comment by vicente999** [comment]
Con respecto a usar la funcion serializar_mensaje es parte del enunciado, por lo que tienes que usarlo

**Comment by vicente999** [comment]
Igual el contenido del mensaje es indiferente mientras cumpla con las funciones de la comunicación servidor-cliente, lo único que deben respetar es la serialización, encriptación y codificación
