### ISSUE TITLE
Caracteristicas sin los genes necesarios para obtener fenotipo

### ISSUE THREAD

**Issue by mnmardones** [IIC2233/Syllabus#352]
Tratando de probar una función para obtener el color de piel recorriendo todas las personas me encontré con un error de división por 0 al obtener el porcentaje de los genes  AAT y GCG, al revisar el tag TCT, que supuestamente corresponde al color de piel, me fije que varios no tienen ninguno de los dos genes, provocando que el total sea 0 y por lo tanto se produzca el error. Es posible que ocurra eso, es un error del archivo, o estaré haciendo algo mal, como tomar el tag incorrecto o asignar la lista incorrecta.

**Comment by rihanuch** [comment]
@nmardones me paso lo mismo 😱! Revise algunos a mano y efectivamente es asi! Ahora, si bien quizas no todos lo son y podriamos estar mal🤔

**Comment by nachocontreras** [comment]
en ese caso habría que levantar Genome Error? 🤔

**Comment by mnmardones** [comment]
Resolví el problema, resulta que estaba tomando slices incorrectos, seq[i : i + 3], siendo i la posición que indica la lista, pero el largo de la secuencia es el triple al del número de genes, así que i tiene que ser el triple, para que lo tomen en cuenta al obtener los slices o si les estaba ocurriendo lo mismo.

**Comment by rakarachon** [comment]
Hola! También tengo la duda de si es posible que para alguna característica ninguno de los genes asociados a esta (según listas.txt) corresponda a un tag de valor para dicha característica, y si estaría bien en ese caso considerarlo como Genome Error.
