### ISSUE TITLE
Posición Luigi a la hora de interactuar con estrella + fin de juego

### ISSUE THREAD

**Issue by juanespala** [IIC2233/Syllabus#352]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, mi duda nace respecto a que en el enunciado no se deja claro si luigi debe estar en **la misma celda** que la estrella, o puede ser una de las 8 celdas adyacentes a esta. Por otro lado, me gustaría saber si el fin de juego puede ser mostrado en una ventana nueva. 

Buen día!

**Comment by ignaciovita** [comment]
Hola! Respecto a tu primera pregunta, Luigi debe estar en la misma celda que la estrella para presionar "G" y tomar la estrella (y no debería poder hacerlo estando en las 8 celdas adyacentes a la estrella). El enunciado dice en la sección 3.5: "Luigi llega a la Estrella donde se encuentra encerrado Aaossa y presiona la tecla 'G' sobre el bloque para liberarlo". La palabra "sobre" indica que Luigi debe encontrarse necesariamente sobre la estrella.

Respecto a tu segunda pregunta, si puedes mostrar el fin de juego en una ventana nueva. No hay un máximo de ventanas que puedes crear, las que aparecen en el enunciado son solo las mínimas que deben existir. Solo preocúpate de cumplir con todo lo que pide el enunciado respecto del fin de juego: reproducir el audio correspondiente, mostrar un mensaje indicando el nombre de usuario, el resultado y puntaje final, y un botón para cerrar el programa (lo que sale en la sección 3.5 del enunciado).

Éxito con la tarea!
