### ISSUE TITLE
Duda con importacion de parametros

### ISSUE THREAD

**Issue by momse11** [IIC2233/Syllabus#352]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Buenas, quería saber si es que importo un archivo que importa parametros, puedo usar el mismo para llamarlos, o necesito sí o sí importar directamente de parametros.
Por ejemplo digamos que tengo un archivo_1.py que dice "from parametros import PARAMETRO". Luego si necesito PARAMETRO en el archivo_2.py puede simplemente poner "from archivo_1 import PARAMETRO" ?
Sé que funciona pero quería saber si se puede hacer para la tarea.

**Comment by PkAlvaro** [comment]
Hola @momse11 como estás?

Considerando la duda, si bien como dices ese método de importación funciona, uno de los focos del curso es el que lleves orden respecto a la modularización, por eso mismo, es preferible que importes directamente desde tu parametros.py en ambos archivos.

Saludos.
