### ISSUE TITLE
Confusión con comunas en votantes_validos_por_distrito y distrito_mas_votos_especie_bisiesto.

### ISSUE THREAD

**Issue by elneitans** [IIC2233/Syllabus#352]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Estoy un poco confundido con las comunas, y quería pedir una ayuda. En la última función (votantes_validos_por_distritos), se pide encontrar el distrito con la mayor cantidad de votos válidos y retornar los animales que pertenecen al distrito. Para encontrar el distrito con mayor emisión de votos se puede ver dónde votó cada animal, lo cual da un local, lo que a su vez da una comuna y ésta da finalmente el distrito. En este ejercicio según lo veo, las comunas de donde son los animales no tienen ninguna relevancia, y si se consideran uno lo tiene malo. Sin embargo en la función "distrito_mas_votos_especie_bisiesto", también se pide encontrar el distrito con la mayor cantidad de votos emitidos, sin embargo al no dar en esta oportunidad los locales, se debe considerar que los animales votan en su misma comuna, es decir, ahora sí que hay que usar el id_comunas de animales de esta forma, a diferencia del caso anterior. Haciéndolo de estas funciones como dije, obtengo todos los puntos en los tests, sin embargo me queda la duda de que en realidad no lo haya entendido, y luego en los tests privados tenga problemas. Agradezco mucho la ayuda.

**Comment by TomasGMDC** [comment]
@elneitans efectivamente, debes interpretar los archivos de forma distinta para esas consultas, tomando en cuenta los generadores que recibes.
