### ISSUE TITLE
Duda fin del programa por dinero igual a 0

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#352]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### ¿Cuando el dinero llega a 0, cierro el programa con todo? ¿O termino la simulacion?

En el enunciado dice "Finalmente el programa acabara automaticamente cuando tus fondos llegen a 0, significando la bancarrota del canal y el fracso de tu simulacion" Lo que me da a entender de que el programa se cierra, pero quiero estar seguro. :sweat_smile:

**Comment by Emiliax16** [comment]
Yo diría que lo más correcto sea que informes por consola sobre el fracaso de la simulación y entregues la opción de volver al menú de inicio para iniciar una simulación o salir del programa, pero dado que el enunciado dice explícitamente _Finalmente el programa acabara automáticamente cuando tus fondos lleguen a 0, significando la bancarrota del canal y el fracaso de tu simulación_, podría interpretarse como que el programa podría cerrarse inmediatamente después del fracaso de la simulación.

En cualquier caso, añade qué supuesto tomaste en tu README y no deberían haber problemas!
