### ISSUE TITLE
Dias de competencia y dia actual

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2233/syllabus#353]
Hola! se supone que el parametro DIAS_COMPETENCIA siempre será un número par, entonces porque el *dia actual *de Campeonato comienza en el 0? me parece extraño que al final se entrene en los días pares y se compita en los impares.
O el DIAS_COMPETENCIA al ser por ejemplo 6 días, estos los contamos desde el día 0 al día 5 nomas?

**Comment by vsantelicest** [comment]
Hola! Claro, la idea de los días pares es que comiences la DCCumbre Olímpica con un día de entrenamiento, y la termines con uno de Competencia, tal como lo señalas en el caso de tener 6 días, donde el día 0 correspondería al primer día de entrenamiento, y el día 5 al último de competencia.

**Comment by pabloalvarez67** [comment]
gracias!
