### ISSUE TITLE
Pantalla en blanco al cargar nivel

### ISSUE THREAD

**Issue by GitCross135** [IIC2233/Syllabus#353]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, cuando ejecuto la ventana del laberinto, esta se queda en blanco por alrededor de 15 segundos (con un mensaje de "la ventana no responde") y luego carga y comienza a mostrarme su contenido, y cuando paso del nivel 1 al nivel 2, es mucho peor. Habrá algún tipo de ayuda que me puedan ofrecer por aquí? Gracias de antemano :c

**Comment by vicente999** [comment]
Hola! Estuve revisando tu codigo y creo que puede darse por la forma de importar objetos y cargar los widgets , en el fondo estas pidiéndole mucho a la VentanInicio. Lo que podrías hacer es tener algunas cosas pre-cargadas de antes, cosa que no sea tan peludo para VentanaInicio. Y si te pasa que al cargar el siguiente nivel la cosa empeora, puedes reciclar algunos widgets ya cargados, asi optimizas mejor tu codigo.

**Comment by GitCross135** [comment]
Vale vale, gracias!
