### ISSUE TITLE
Sprites

### ISSUE THREAD

**Issue by veneguitas** [IIC2233/syllabus#353]
Hola! Quería saber si era obligatorio utilizar todos los sprites del mapa. Gracias!

**Comment by jirarrazabal** [comment]
Hola! No es obligatorio usar todos los sprites. Puedes elegir los que más te gusten para hacer el mapa como quieras.

**Comment by jeschuwirth** [comment]
Hola!

Esta issue fue respondida en la #342.
No es necesario utilizar todos los sprites de mapa, basta con usar los minimos que representen cada casilla.

Suerte !
