### ISSUE TITLE
decisión en elección de evento

### ISSUE THREAD

**Issue by cifernandez1** [IIC2233/Syllabus#353]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

¡Hola! Aun no entiendo bien la parte de 5. Simular Dia, específicamente en 5.2 Elección de Evento, respecto a "se deberá decidir si sucederá un evento o no durante el dia." ¿Como se toma esa decisión? Ya que existen unas probabilidades pero en el ejemplo no se decide respecto a eso.

**Comment by AndreaVict** [comment]
Holaa, como se menciona en el enunciado, al seleccionar la opción **Pasar día** en el menú de inicio, se comienza con la simulación. Al accionarse esto se debe intentar activar un evento en base a las probabilidades que estos tengan de ocurrir. 
**Por ejemplo :**
 - Se tiene el evento **Oleada de Zombies** con un **10%** de probabilidad de ocurrencia, el cual se intentara activar. 
 - Si esto no ocurre entonces la **Helada** con un **50%** de probabilidad se intentara activar.
Si es que se llegase a activar deberían ocurrir todos las situaciones mencionadas (con el evento activo) en el enunciado para finalmente volver al menú de inicio. 
Para cualquier opción que ocurra (Oleada de Zombies, Helada o ninguna) se debe accionar lo mencionado en la sección de **"Simular día"**. 
Es importante mencionar que la activación de los eventos se realiza netamente en base a sus probabilidades. Ahora bien, el como implementar esta decisión en base a los % es parte de la evaluación. Mucho éxito en la tarea!!
