### ISSUE TITLE
interfaz sin opcion abrir

### ISSUE THREAD

**Issue by BeaGaete** [IIC2233/Syllabus#353]
Hola, en mi interfaz no aparece la opcion “Abrir” en la barra de opciones, por lo que no puedo  cargar el archivo consultas.json. Lo copie sin cambiar el nombre en la misma carpeta tal como dice en el enunciado, pero no funciona. ¿Que puedo hacer? Esta es mi interfaz:
![interfaz tarea 3](https://cloud.githubusercontent.com/assets/26144496/25558408/0f96e8b2-2cf4-11e7-8e47-880519639862.png)

**Comment by Hernan4444** [comment]
puedes mandar imagen de como se vé la pantalla? por favor

**Comment by malopez16** [comment]
#293 
#320 
Me pasó lo mismo! pon el mouse en la parte más arriba de la pantalla a la izquierda, mientras tienes maximizada esa ventana. Ahí debería hacerse visible el "abrir" en la barra superior :)

**Comment by BeaGaete** [comment]
Gracias !!!!
