### ISSUE TITLE
Lectura de los genes:

### ISSUE THREAD

**Issue by inmadariaga** [IIC2233/Syllabus#353]
No entiendo bien como leer los genes, osea , tomare de ejemplo la primera linea de genomas:
-AAG3
-me voy a la lista 3
-26,81,108,140,148,171,172,175,223,237
-tendria que irme al 26 del adn (aquí, el primero se cuenta como 0 o como 1?)
tendría que tomar el 26-27-28 como manifestaciones del gen AAG?, es que en el enunciado dice
 " El segundo dato es un numero que representa el id de una lista con las posiciones de los posibles valores para dicha característica"

**Comment by Hernan4444** [comment]
@inmadariaga el enunciado fue actualizado con un ejemplo de eso, revisa eso y si no se entiende, vuelve a preguntar :v: (Adelanto: el primero cuenta como 0)

Saludos :D

**Comment by inmadariaga** [comment]
@Hernan4444 Creo que entendi mal eso, por ejemplo, si me tocaba el j, iba  al posicion j y tomaba el j, j+1 y j+2, pero haciendolo asi, en muchas fenotipos me retornaba None, por que no estaban las caracteristicas que buscaba, los estoy tomando mal? el ejemplo del enunciado no me clarifica nada

**Comment by inmadariaga** [comment]
ya lo arreglé, gracias
