### ISSUE TITLE
Feedback actividades

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2233/Syllabus#353]
Hola, hay algún tipo de feedback de las actividades y como puedo recorregir una?

Gracias

**Comment by DquezadaO** [comment]
En los repositorios personales se les sube feedback de sus actividades en la sección de issues

**Comment by Javierdr** [comment]
Y para recorregir una debes responder, dentro del plazo, el form que se encuentra en [la pagina del curso](https://iic2233.github.io/recorreccion/).
