### ISSUE TITLE
Duda uso de parámetros

### ISSUE THREAD

**Issue by tamyhan** [IIC2233/syllabus#353]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Está permitido definir un parámetro con un valor inicial y que luego se vaya modificando con el transcurso del programa?

**Comment by Emiliax16** [comment]
Hola @tamyhan ! el módulo `parametros.py` debe contener sólo valores constantes, por lo que sería considerado una mala práctica y mal uso del archivo de parámetros si los modificas. Lo que si puedes hacer es usar ese parámetro como valor inicial para definir una variable dentro de tu módulo, así es esa variable la que se va modificando con el transcurso del programa.

Avísame si te quedó más claro! c:
