### ISSUE TITLE
posición de rect()

### ISSUE THREAD

**Issue by nep0s** [IIC2233/syllabus#353]
Hola!

Cuando imprimo la posición de una imagen en la ventana con .pos() me aparece la posición correcta, pero cuando ocupo .rect() para obtener la posición del rectángulo los primeros dos argumentos (de posición) me aparecen siempre como 0, 0.
Alguna idea de porqué pasa esto o como puedo solucionarlo?
Gracias!

**Comment by jaromero6** [comment]
Hola
Acorde a lo que encontré [aquí](http://zetcode.com/gui/pyqt5/painting/) y en este otro [enlace](https://www.qtcentre.org/threads/44873-what-s-the-difference-betwwen-rect()-and-geometry()), el método rect retorna por default un rectángulo en la posición (0,0). Algo que te podría servir sería pasarle a ese método los atributos de posición, o usar el [QRect](https://doc.qt.io/qt-5/qrect.html)
Espero haberte ayudado

**Comment by nep0s** [comment]
Si! Gracias!
