### ISSUE TITLE
Condiciones de calculo de probabilidades de encallamiento

### ISSUE THREAD

**Issue by NiceGuyWorz** [IIC2233/syllabus#354]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el Enunciado dice: 

"_A continuación, el programa deberá calcular si el barco encalló o no en base a su probabilidad de encallar.
En caso de no encallar, deberá calcularse a continuación si el barco ejecutó su propio evento especial._"

¿Entonces se debe calcular dos veces la probabilidades para los barcos que van entrando en ese turno? 
Seria 1 vez por entrar y 2 vez por moverse dentro. 
¿O solo se calcula una vez la probabilidad por turno?

Y para el evento especial,
¿Puede ocurrir solo una vez por cada vez que atraviese el canal o solo puede ocurrir una vez por juego?

**Comment by Emiliax16** [comment]
Hola @NiceGuyWorz ! la issue [251](https://github.com/IIC2233/syllabus/issues/251) responde casi todas tus dudas.

Respecto a el evento especial, como dice el enunciado, sólo puede ocurrir una vez por barco durante toda su trayectoria por el canal.

Avísame si aún quedan dudas!
