### ISSUE TITLE
Duda Ayudantía 6

### ISSUE THREAD

**Issue by Cschavez** [IIC2233/Syllabus#354]
Hola! En el método verify_types(...), así como está en la solución, al imprimir la función "saludar" imprime None. Haciendo la ayudantía yo dentro de verify_types(..) puse : return funcion(*args, **kwargs)  dentro de "_verificar_tipos" y ahí si imprime el resultado de la función si hago
`print(saludar("hola"))`
y si está efectivamente tiene el input y output correcto.
 Mi pregunta es si, al menos para ese caso en particular, no es necesario hacer lo que dije recién y da igual que al printiar se imprima "None", o si existe alguna razón en particular por lo que de igual cualquiera de las dos formas de hacerlo. Espero se haya entendido:(
Muchas gracias !
![image](https://user-images.githubusercontent.com/37157327/39279270-55c1881e-48ce-11e8-8519-fb8f9bfd40cf.png)

**Comment by fgbruna** [comment]
Hola!, efectivamente en este caso, y debido a como construimos la función `_verificar_tipos` esta no retornara nada ya que no definimos su retorno usando la _keyword_ `return`.
**Si quieres obtener lo que retornaba `saludar` originalmente** deberias hacerlo así:
```python
def verify_types(input_type, output_type):
    """
    Verifica que el primer argumento de una función sea del tipo input type y que
    el valor de retorno sea del tipo output type. En caso contrario, lanzar una
    excepción de clase TypeError.
    """
    def verificar_tipos(f):
        def _verificar_tipos(*args, **kwargs):
            if args and not isinstance(args[0], input_type): # Verificamos que reciba al menos un argumento
                raise TypeError("El primer argumento no es de tipo {}".format(input_type))
            retorno = f(*args, **kwargs)
            if not isinstance(retorno, output_type):
                raise TypeError("El retorno de la función no es del tipo {}".format(output_type))
            return retorno
        return _verificar_tipos
    return verificar_tipos
```
Nota que usamos el retorno **al final**, asi obtendremos el funcionamiento esperado, es decir obtendremos el retorno si y solo si pasa ambas pruebas!

**Comment by Cschavez** [comment]
Gracias! Otra duda, vi el enunciado de la actividad y en una parte dice que hay que hacer una función que imprima el nombre de la función que se está ejecutando junto a otras cosas, sin embargo, no se me ocurre como obtener el nombre de la función. Estuve buscando y en varias partes encontré un código como esto:
```
import inspect
# functions
def whoami():
    return inspect.stack()[1][3]
def whosdaddy():
    return inspect.stack()[2][3]
def foo():
    print "hello, I'm %s, daddy is %s" % (whoami(), whosdaddy())
    bar()
def bar():
    print "hello, I'm %s, daddy is %s" % (whoami(), whosdaddy())
johny = bar
# call them!
foo()
bar()
johny()
```
http://stefaanlippens.net/python_inspect/[fuente](url)

Para efectos de la actividad estaría bien o serviría ocupar eso? Muchas gracias de nuevo!

**Comment by fgbruna** [comment]
Debería ser más simple que eso, [tal vez esto te pueda servir](https://stackoverflow.com/questions/308999/what-does-functools-wraps-do/309000#309000)
