### ISSUE TITLE
Relación herencia y asociación

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#354]
Hola!! Tengo una duda más que nada conceptual. Tengo la clase A y B con relación de herencia (A la superclase). Además, tengo entre B y C una relación de asociación. Mi duda es si puedo crear un método en A que reciba como argumento a C. 🤔

**Comment by mmunozmendez** [comment]
Hola, de poder crear el método, si puedes, pero en ese caso tendrías que pensar si realmente la asociación es entre C y B, y no entre A y C.

**Comment by denisseleiva** [comment]
dalee, gracias!!!
