### ISSUE TITLE
Duda comando "asignar"

### ISSUE THREAD

**Issue by cho19** [IIC2233/Syllabus#354]
Hola!

Si el usuario ejecuta `["asignar", "comando", ["PROM", 1]]`, ¿la GUI debe imprimir `Error: asignar("x", "PROM"*), Causa: Error de tipo`? ¿O sigue la ejecución y una vez llamo a la variable "comando" en algún otro comando levanta la excepción y el correspondiente mensaje?

Saludos y gracias!

**Comment by Hernan4444** [comment]
según enunciado, asignar guardar en "comando" lo que retornar la consulta, es decir, se debe ejecutar ["PROM", 1] y ahí fallará

Saludos!

**Comment by cho19** [comment]
Gracias!
Dado eso me surgió otra pregunta: ¿es necesario que ejecutemos y guardemos el valor de retorno del comando al asignarlo? Lo digo pues hasta ahora por conveniencia, había trabajado guardando las funciones listas para ser ejecutadas, tengo una solución en mente si no se puede pero prefiero preguntar.
Saludos!
