### ISSUE TITLE
Actualización de un diccionario por medio de reduce

### ISSUE THREAD

**Issue by VicenteIgnacioSotoGonzalez** [IIC2233/Syllabus#354]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Buenas tardes, junto con saludar quería consultar si es válido actualizar un dic por medio de un reduce mediante la siguiente linea.

reduce(lambda dic, elem: dic.update({elem: 0}) or dic, iterable, {})?

Gracias de antemano!

**Comment by jfpantoja** [comment]
Hola @VicenteIgnacioSotoGonzalez!!
En este caso si es válido, siempre y cuando el diccionario previo sea creado por métodos admitidos.

**Comment by VicenteIgnacioSotoGonzalez** [comment]
> Hola @VicenteIgnacioSotoGonzalez!! En este caso si es válido, siempre y cuando el diccionario previo sea creado por métodos admitidos.

Perfecto, muchas gracias!
