### ISSUE TITLE
Grid Layout, sobre poner sprites 

### ISSUE THREAD

**Issue by Paldana99** [IIC2233/syllabus#354]
En la issue #351 se respondió de crear labels independientes para sobreponer los sprites, pero mi pregunta es en caso de utilizar las grid layouts para organizar por ejemplo el mapa, como se pueden sobre poner las imágenes? O no es necesario utilizar las grid, pero en ese caso que pasaría si la ventana se agranda?

**Comment by jeschuwirth** [comment]
Hola!

Creo que el método que estas buscando es usar un Qlabel.raise(), para colocar un qlabel por sobre todo el resto.

Si no es ese avisa para intentar ayudarte :)

Suerte!

**Comment by Paldana99** [comment]
No mi idea, es poner dos grillas sobre puestas, o en una misma grilla poner dos labels en la misma casilla.
Por ejemplo si utilizo una grilla, y la casa la puse en el espacio 2, 2. Si situó un nuevo elemento en la grilla 2, 2 (el pasto por ejemplo) se borra la casa. Como se podria solucionar? o es mejor no utilizar una grilla

**Comment by Pablok98** [comment]
Hola! Nosé si es la unica solución, pero si creas un qpainter para dibujar las imagenes, en vez de insertarlas directamente a los labels, puedes dibujar una encima de la otra en el mismo objeto, usando la funcion drawpixmap() en el orden correspondiente. Es un objeto de qt de GUI, si encuentro un buen ejemplo, te actualizo, pero puedes buscar como usarlo en la documentacion de pyqt.

**Comment by Pablok98** [comment]
Creo que esto te podría servir: https://stackoverflow.com/questions/42769354/draw-on-top-of-image

**Comment by jeschuwirth** [comment]
@Paldana99,

Ya entendí tu problema. Lo que más te recomiendo ya que evita problemas es utilizas la grilla como el fondo de tu programa y luego colocar todos los objetos que se piden "encima".

En este caso, la casa, tienda, personaje y cultivos irían encima.

Me gusta tu idea de utilizas dos grillas, pero no estoy seguro si PyQt lo permite :/. podrías intentarlo y usar una de ellas como el fondo con las rocas/tierra/pasto y luego una segunda con los items mencionados anteriormente.

Lo siento por no tener una respuesta exacta a lo que necesitas, si intentas las grid y no te funciona y tampoco funciona con hacerlo al modo "naive" o a mano, entonces sigue comentando en la issue para buscar una solución.

**Comment by Paldana99** [comment]
Si lo intente pero me perdi asique arme todo sin grillas. Pero igual gracias por la respuesta.
Ahora mi duda es como determinar las distancias, porque por ejemplo puse un valor constante que los determine en parametros.py, pero para hacer espacios laterales por ejemplo le voy sumando arbitrariamente 100 pixeles por ejemplo. Mi duda es si estos valores se deben tambien mantener constantes o esta bien ir sumando?

**Comment by jeschuwirth** [comment]
Recuerda que puedes hacer todo en base al parámetro N. Por ejemplo, el largo del mapa podría ser 20*N.
