### ISSUE TITLE
Error c/ señales y error sin sentido

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2233/syllabus#354]
Hola, tengo una problema, para saber que bando el jugador vas a jugar envio una señal para una función que esta en un modulo destinto, la señal me llega y tiene el valor que deberia tener ( penguino, si printeo self.referencia despues de ese evento tambien me printea penguino. lo que pasa es que cuando ingresa en la funcion sprites(self, event) que espera la funcion fmapa emita una señal. y eso solo pasa despues de emitir la señal para saber la referencia de que es el player(penguino o gato),me printea que self.referencia = gato(en la clase la defini como default como gato, y lo más raro que encontro es que mismo self.referencia siendo igual a gato y el type ser el mismo de la condicion del if que tengo, NUNCA me ingresa al if, abajo tiene las imagenes 
![image](https://user-images.githubusercontent.com/42182095/58205715-209f2d80-7cad-11e9-9274-43ba56b63713.png)
![image](https://user-images.githubusercontent.com/42182095/58205742-344a9400-7cad-11e9-8fed-ac06dccbff3d.png)
![image](https://user-images.githubusercontent.com/42182095/58205910-96a39480-7cad-11e9-847e-d4fb697c8352.png)
![image](https://user-images.githubusercontent.com/42182095/58205947-ae7b1880-7cad-11e9-8246-b28e1e79a56e.png)
el primero print se referie a print(event) dentro de la funcion freferencia, el segundo print(self.referencia) el tercero de que tipo es self.referencia, el cuarto es si self.referencia==gato y me tira true, pero nunca ingresa al if que pregunta lo mismo( si printeo la referencia en otras partes de la funcion me tira que self.referencia continua sendo gato).

**Comment by Hernan4444** [comment]
Hola

Viendo tu código, puedo ver 2 atributos `self.referencia`  y `self.referecia`, ¿está bien que sean 2 atributos? o fue un error de tipeo?

estoy atento a tus comentarios

**Comment by csantiagopaz** [comment]
No creo que me equivoque en eso jajajaja, te amo Hernán, muchas gracias

Em qua, 22 de mai de 2019 16:40, Hernan Valdivieso <notifications@github.com>
escreveu:
