### ISSUE TITLE
Comando ** para diccionarios

### ISSUE THREAD

**Issue by AlanGoldsmith25** [IIC2233/Syllabus#355]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Se puede usar el comando ** para ir actualizando los valores de un diccionario?

**Comment by Julius9** [comment]
Hola! tengo algunas preguntas sobre esto, primero recuerda que en el caso de las consultas, esta prohibido utilizar diccionarios, listas o tuplas fuera de un `reduce()`. En segundo lugar los operadores `**` se utilizan para desempaquetar valores de un diccionario. Por ejemplo, la función `randint()`del modulo `random` recibe dos argumentos llamados "a" el limite inferior y "b" el limite superior, por lo que para usar un diccionario se utiliza `randint(**{"a": 2, "b": 20})`. Por lo que mi pregunta es:

¿como planeas utilizarlos para actualizar valores de un diccionario ?

**Comment by AlanGoldsmith25** [comment]
Puedo mandar un ejemplo de mi codigo por aca o se considera copia?

**Comment by Julius9** [comment]
No puedes mandar tu código, pero si un ejemplo no relacionado a la tarea de como usarías el operador `**`

**Comment by AlanGoldsmith25** [comment]
Lo haria dentro de un reduce de la siguiente manera como ejemplo:

diccionario = reduce(lambda diccionario, hola: {**diccionario, \
                       hola.hola: hola.chao, generador_hola, {})

**Comment by Julius9** [comment]
En ese caso si puedes utilizarlo, éxito en la tarea!
