### ISSUE TITLE
Conversión reviews + N/A

### ISSUE THREAD

**Issue by Panckx** [IIC2233/Syllabus#355]
Hola! Cuando se hace una consulta popular_movies en que se pide, por ejemplo, filtrar por el raiting de IMDb, se espera que conviertan todos los ratings al puntaje estándar? En ese caso, si se pide filtrar por los ratings de IMDb y hay una película que no tiene rating para Rotten Tomatoes (N/A), debo detener la consulta y anunciar que se cayó, incluso cuando la razón de esto no tiene nada que ver con la consulta?

**Comment by mfanselmo1** [comment]
Hola!
Tal como sale en 2.4
![image](https://user-images.githubusercontent.com/26393563/39279788-aaea33a6-48d1-11e8-8a43-80ae19c669dd.png)

> Se debe levantar esta excepcion si durante una consulta se **requiere analizar** un dato de las peliculas que no esta definido

Por lo tanto, si una consulta no tiene que revisar algun dato no definido, aunque este en una pelicula, no tendria porque dar el error.
