### ISSUE TITLE
duda distribución puntaje  los elementos no se superponen

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#355]
Hola estaba revisando la distribución de puntajes y me tope en la parte de ventana de juego que dice

> Información indicada en el enunciado se muestra en la pantalla.Los elementos no se superponen entre sí.

¿A que se refiere el final con no se superponen entre sí?
gracias de antemano

**Comment by aljara97** [comment]
Hola, básicamente esto se refiere a que al momento de cargar tu mapa los distintos elementos ocupen el espacio que corresponde (un ancho y largo N). Además debes preocuparte que estos elementos y otros de tu ventana, tales como botones, barra de vida, entre otros no estén "uno encima de otro", es decir, debe respetarse su espacio correspondiente. Esto debe ser para cualquier mapa que queramos probar y para cualquier parámetro N a definir.

Mucha suerte con tu tarea 👍
