### ISSUE TITLE
DUda sobre que fondo utilizar

### ISSUE THREAD

**Issue by Vjyhgv** [IIC2233/Syllabus#355]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/326).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/325).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Una consulta,  tal vez se me paso del enunciado, pero hay múltiples fotos para ocupar como fondo en una venta, esto es para elegir? hay que ocupar alguna en algún momento determinado?  Por ejemplo , el dojo 

Gracias

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mtaguero** [comment]
Hola ✨

Esta pregunta fue respondida en la issue [#328](https://github.com/IIC2233/Syllabus/issues/328) 👀👌🏼
Si te quedan dudas, puedes volver a preguntar sin problemas.

¡Éxito! 🎈
