### ISSUE TITLE
Incluir el frontend del mapa en la venta de juego

### ISSUE THREAD

**Issue by jfpena1** [IIC2233/syllabus#355]
Al tratar incluir el frontend del mapa en la venta de juego, me pasa que solo puedo ver como se desarrolla el movimiento de los enemigos pero no puedo mover mi personaje, como si puedo hacerlo al tenerlo al tenerlo como una ventana separada. Hasta ahora estoy incluyendo el mapa como un widget de uno de los dos vertical layouts de la ventana de juego (l otro VBox corresponde a las opciones de la barra de preparacion). Nose como solucionarlo, me podr[ian ayudar con alguna idea de modelacion? Muchas gracias.

**Comment by mjespinoza** [comment]
Holaa, yo tuve el mismo problema y me recomendaron dejar la funcion keypressevent() en la ventana de juego y setearle el parent al personaje.

**Comment by jfpena1** [comment]
vale gracias!
