### ISSUE TITLE
Error librería CurrencyConverter

### ISSUE THREAD

**Issue by fliperriga** [IIC2233/syllabus#355]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, instalé la librería CurrencyConverter y al correr el código no la reconoce. Cuando escribo (pip install --user currencyconverter) en el terminal, retorna lo siguiente: Requirement already satisfied: currencyconverter in c:\users\cbarr\appdata\roaming\python\python37\site-packages (0.16).

**Comment by mistico0121** [comment]
El error dice que ya está instalada. Asegurate que estés corriendo Python en la misma version en la que se instaló.

Tambien puedes probar revisar como se importa la librería y que estés siguiendo todos los pasos. Si no has visto la documentación, te recomiendo echarle un ojo:
https://pypi.org/project/CurrencyConverter/

También puedes probar instalando con pip3. Hay veces que he debido usar pip y con pip3 he logrado instalarlo.

Saludos.

**Comment by nnovoag** [comment]
holaa me pasa lo i¡mismo!! como lo arreglo?

**Comment by mistico0121** [comment]
@nnovoag 
Prueba revisando que se haya instalado en la versión correcta de python, si es que tienes más de una version en tu PC. Es posible que tengas 2 versiones y que la consola esté corriendo la que no tiene instalada la librería. Ej: Si pip se encuentra "apuntando" hacia otra versión, y están correindo una versión distinta de Python, es posible que les ocurra esto de que pip dice que está instalada y python dice que no y no pueda reconocerla. También asegurense de que estén corriendo correctamente la librería y no haya errores de tipeo o cosas así.

Para solucionarlo, creo que lo mejor que pueden hacer es asegurarse que pip esté apuntando a la version de python que están utilizando, para cambiarla e instalarla en la versión que corresponde.

Es lo más probable que se me ocurre que puede estar generando este problema.

Saludos

**Comment by nnovoag** [comment]
Mm no te cache como arreglarlo, podrías quizás tu o alguien mas ayudarme a arreglarlo porque es pa mañana la tarea jajaja y si no funciona seria una lata :(

**Comment by mistico0121** [comment]
@nnovoag 
Hola

Lamentablemente, me es dificil setear una hora para solucionarlo 1 a 1. Puedes ver si en el discord de Programación Avanzada hay algún ayudante que te pueda ayudar en esta modalidad. Sin embargo, varios de tus compañeros han tenido el mismo problema y se han sugerido varias alternativas de como solucionarlo 
-usar el comando python3.7 a la hora de instalar con pip "python3.7 -m pip install currencycoverter"
-revisar el PATH de pip
-Otras issues respecto al mismo problema #357 #380

Recuerda revisar google y stackoverflow, que son los mejores recursos a la hora de hacer troubleshooting. Simplemente copypastea el error en la búsqueda y te aparecerán varias posibles soluciones. Acá hay 1 de varias soluciones al mismo error de una persona que intentó instalar otra librería y se le instaló en la versión incorrecta de python. https://stackoverflow.com/questions/25607837/pip-install-not-installing-into-correct-directory

Espero que te sirva. Suerte
