### ISSUE TITLE
Mover rocas con fantasmas detras

### ISSUE THREAD

**Issue by emilio-p** [IIC2233/Syllabus#355]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola buenas tardes, tengo la duda de que es lo que tiene que pasar si muevo una roca y justo hay un fantasma en la direecion en la q la quiero mover. Y en caso de que si se pueda mover la roca, que pasa con el fantasma, ya que este no puede atravesar las rocas y le estariamos poniendo una roca en su misma casilla.
Saludos y gracias.

**Comment by Hernan4444** [comment]
Hola,

La roca se mueve solo a una casilla si está vacía. Por lo tanto, si ya hay un fantasma, la roca no podrá ser empujada hasta que este se vaya y la celda quede vacía. Ahora, si el fantasma se está moviendo justo a una celda (todavía no llega) y ahí decido empujar la roca a dicha celda, ahí queda a tu criterio qué hacer en ese caso. Pero no es un caso que vayamos a testear,.

Solo vamos a validar que la roca no pueda ser empujada si claramente hay un elemento al frente de ella.


Saludosヾ(＾-＾)ノ

**Comment by blampasona18** [comment]
Hola @Hernan4444 !
Aprovechando la pregunta sobre la roca, al mover esta, **la animacion debe ser fluida?** Al no tener más de un sprite, estaría correcto según pauta que la roca desaparezca y aparezca en el siguiente bloque.
Gracias de antemano!

**Comment by Hernan4444** [comment]
Hola @blampasona18 

No se exige un movimiento fluido, así que es válido lo que propones, como también es válido si alguien hizo que se moviera a la par de Luigi para simular la fluidez, aunque no animado.

Saludosヾ(＾-＾)ノ

**Comment by blampasona18** [comment]
> Hola @blampasona18 
> 
> No se exige un movimiento fluido, así que es válido lo que propones, como también es válido si alguien hizo que se moviera a la par de Luigi para simular la fluidez, aunque no animado.
> 
> Saludosヾ(＾-＾)ノ

Perfecto, gracias!
