### ISSUE TITLE
Duda con parametros.py

### ISSUE THREAD

**Issue by momse11** [IIC2233/Syllabus#355]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Buenas, queria saber si para condiciones se necesita definir en parametros.py con lo que se compara si es que es una constante. Por ejemplo si digo if X == "solaretillo", debería definir TIPO_1 = "solaretillo" en parametros.py?
Y si ese es el caso, también quería saber como trabajarlo si es que ese elemento está en una lista. Por ejemplo LISTA_NOMBRES = ["Francisco",  "Juan", "Pablo"]
Si quiero decir if X == "Francisco", debería decir if X == "LISTA_NOMBRES[0] ? o seria mejor definir cada elemento de la lista aparte en parametros?

**Comment by CatalinaBO** [comment]
Hola! El archivo de parámetros se utiliza únicamente para definir valores numéricos. Por lo tanto, puedes definir los tipos de plantas en el código, lo mismo para las listas que mencionas.

**Comment by momse11** [comment]
Hola! Gracias por la respuesta. Otra duda me surge cuando me dices que solo se usan valores numéricos en el archivo de parámetros. Leí en otra issue #351 que los paths si se definen en parámetros. Entonces, para confirmar, los únicos valores no numéricos a guardar en parametros.py son los paths?

**Comment by CatalinaBO** [comment]
Exacto, los paths también se definen en el archivo parametros.py. 
Para explicarte un poco más como funciona este archivo, se utiliza para no caer en el método de hard-coding, pero también por un tema de simplicidad e independencia en el código. Al trabajar con un archivo de parámetros constantes, en caso de que haya que modificar alguno de estos valores por el motivo que sea, se simplifica mucho más la búsqueda y la eficiencia para poder arreglar el programa, ya que no debes cambiar el valor en todas las líneas que usaste el parámetro que ahora quieres modificar, sino que solo basta con cambiar el valor en la variable que definiste en parametros.py, y automáticamente se modificará todo tu código. Esto es una buena práctica y ayuda a que se eviten muchos errores cuando se tiene códigos extensos!
Es por esto que se usa este archivo para valores númericos y para paths (porque pueden ser cambiados constantemente), y aunque se pueden definir otras variables que consideres necesarias, para lo que me planteaste en tu comentario de arriba no lo encuentro tan fundamental. 
Éxito en la tarea!
