### ISSUE TITLE
Bombas y su efecto

### ISSUE THREAD

**Issue by emiliamarti** [IIC2233/Syllabus#355]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo una duda acerca de las bombas. La bomba de manzana y su explosión debería borrar los cañones también o solo los lobos y las zanahorias? Y el conejo puede cruzar esa explosión como si fuera una celda vacia o pierde una vida? Y si el conejo cruza la bomba de congelación, también afecta en su movimiento?

**Comment by CrisDonosoMaass** [comment]
Hola! Respecto a las bombas manzana "Son capaces de detonar todo a su alcance" por lo que sí deberían eliminar cañones. El conejo no puede cruzar las casillas de explosión como si estuvieran vacías y si es que lo hace pierde una vida. El efecto de las bombas de hielo también afecta al conejo.

**Comment by Segismundios** [comment]
Hola! Se considera incorrecto que sólo afecta a los lobos? El enunciado dice lo siguiente:
"Uno de los items usables en DCConejoChico es la bomba de manzanas. Estas al ser colocadas por Cone-
jochico son capaces de detonar todo lo que esté a su alcance, en las 4 direcciones posibles hasta chocar
con una pared. Cuando la bomba de manzana explote, deberá dejar en llamas todas las casillas de su alcance durante
TIEMPO_BOMBA segundos, y cualquier lobo que cruce el fuego durante este intervalo de tiempo, deberá ser
eliminado del laberinto."
Además, la pauta dice lo siguiente:
Bomba manzana: "Elimina correctamente todo los lobos a su alcance."
Bomba congeladora: "Ralentiza únicamente a los lobos afectados por su alcance hasta el final del nivel o tras que ConejoChico pierda una vida."

De lo cual entiendo que ambas bombas sólo afectan a los lobos. Tampoco veo especificado en alguna parte que éstas deban actuar como muralla para el conejo.
Es posible especificar que se tomaron estas decisiones en el README o se consideraría derechamente incorrecto?
