### ISSUE TITLE
Excepción Genome Error y espacio

### ISSUE THREAD

**Issue by BeaGaete** [IIC2233/Syllabus#355]
Encontré un espacio en '5Luna 8LovegoodAAG1...' que no interrumpe la secuencia de genes. También lo debería manejar con Genome Error o bien solo debería arreglarlo en el proceso de la lectura del genoma para que me quede 'Luna Lovegood'  ?

**Comment by Hernan4444** [comment]
#336  (ultimos 2 comentarios)
Saludos
