### ISSUE TITLE
extraer columna

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#355]
Que en los titulos del archivo registro por ejemplo le ponen ":float" y en las consultas.json cuando se hace extraer columna, el nombre de la columna no agrega ese ":float", ¿Mi programa debe estar preparado para eso o deberia estar el ":float" y asi ser consecuente con la extraccion de la columna? 
¿En las consultas esos titulos de columnas deberian agregar el ":float" y ustedes "se equivocaron" o está bien?'

**Comment by Hernan4444** [comment]
#312
