### ISSUE TITLE
Atributos Deportista

### ISSUE THREAD

**Issue by yuwet15** [IIC2233/syllabus#355]
Hola, quisiera saber si la clase Deportista se le puede agregar la variable nombre, que no aparece en el enunciado, muchas gracias

**Comment by jitorcas** [comment]
Hola! @yuwet15 

Si, puedes agregar los atributos que consideres necesarios para el cumplir con los requisitos de la tarea, siempre y cuando no contradigan el enunciado. 

Mucho éxito! 🥇

**Comment by yuwet15** [comment]
Muchas gracias
