### ISSUE TITLE
Tamaño Sprites del Mapa

### ISSUE THREAD

**Issue by nicoguz** [IIC2233/syllabus#356]
Hola!
Tegno una duda sobre el tamaño de los 'tiles' que nos dan porque su tamaño no calza con el de una casilla (segun el tamaño de la casa que debería estar en un tamaño de 2*2). Por lo que quería saber si existe alguna forma de reescalar estos sprites para hacer que calzen.

**Comment by aljara97** [comment]
Hola, exactamente, debes escalar la casa para que sea un cuadrado de ancho ```2 * N```, en caso de que estés usando un QPixmap puedes usar la función .scaled de este objeto. 

Mucho éxito con tu tarea ;)

**Comment by nicoguz** [comment]
Oka Gracias!!!
