### ISSUE TITLE
Entregas atrasadas con cupones tareas

### ISSUE THREAD

**Issue by diegoherrerag2000** [IIC2233/Syllabus#356]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda sobre entregas atrasadas, tengo entendido que si entregamos un día atrasado tenemos nota maxima 6.0, y que tenemos dos cupones para usar, pero si aún no los he usado y los quiero usar ambos ahora ¿es posible entregar la tarea un día después de los dos días correspondientes a los cupones?, sería un día atrasado y nota maxima 6.0, pero ¿se puede?.

**Comment by Hernan4444** [comment]
Hola @diegoherrerag2000 

No, no se puede. El sistema es que son 2 días máximo de entrega atrasadas y los cupones **no extienden el plazo** solo reducen la penalización correspondiente por dicho atraso. Por lo tanto, el jueves de la otra semana a las 20:00 sería el plazo máximo de entrega, con nota máxima 4. 
* Si decides ocupar 1 cupon, tu nota máxima será 6.
* Si decides ocupar 2 cupones, tu nota máxima será el máximo posible (considerando bonus).

Pero post jueves 20:00 ya no se aceptará ninguna entrega, aunque el estudiante disponga de cupones.

Saludosヾ(＾-＾)ノ

**Comment by diegoherrerag2000** [comment]
perfecto!! muchas gracias!.

**Comment by fvm2** [comment]
Hola! Tengo una duda respecto a las penalizaciones por atraso, si decido entregar mi area un día tarde sin usar cupones, que la nota máxima sea un 6 significa que ahora la escala para evaluarme está construida como si el 100% de los puntos da un 6.0 en vez de un 7.0 o significa que si entrego la tarea con un nivel de completitud que da un 6.1, la nota final se trunca a un 6.0? Muchas gracias

**Comment by Hernan4444** [comment]
Hola @fvm2 

Cómo aparece en [el programa](https://github.com/IIC2233/Syllabus/blob/main/Archivos%20Importantes/Programa.pdf), la nota se acota, es decir, si tienes un 6.1 y entregas 1 día tarde, la nota final será un 6.0, o si te sacas un 5.9, esa nota se mantiene porque no supera el techo. En resumen, no se va a reajustar la escala 😄, solo a aplicar un techo.

Saludosヾ(＾-＾)ノ
