### ISSUE TITLE
Aumento y potencial de Cilantrillo

### ISSUE THREAD

**Issue by fgallard** [IIC2233/Syllabus#356]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holaaa, hay varias issues similares, pero no entiendo cuando en el enunciado habla de que el Cilantrillo debe tener aumento y potencial mayores en un % respecto a sus **clases padre**, eso es respecto a la clase padre o respecto a las 2 plantas individuales que estoy combinando? porque si se interpreta como respecto a la clase, lo que se tiene que aumentar en cierto % es el int aleatorio que genera, por ejemplo, Solaterillo (como clase), y luego lo aumento, lo que no tendría relación con la planta que estoy combinando. Por otro lado, si tengo que aumentar el solaterillo individual que uso para fusionar las plantas, es distinto, porque ahí ya no es aleatorio sino q es un aumento que ya está fijo previamente. El enunciado pareciera indicar la primera, pero es un poco contraintuitivo.

**Comment by CatalinaBO** [comment]
Hola! Debes aumentar en los porcentajes establecidos los atributos de las dos plantas que estás combinando. Efectivamente como mencionas, el aumento no es aleatorio, ya que el porcentaje está establecido en parámetros y se debe cumplir que el atributo de potencial y aumento debe ser mayor que el de sus clases padres.
Espero se haya respondido tu pregunta, quedo atenta!
