### ISSUE TITLE
Adoptar primera criatura

### ISSUE THREAD

**Issue by jturquiza** [IIC2233/syllabus#356]
Hola! Cuando creo un nuevo personaje y tengo que adoptar una criatura, tengo que considerar el costo? o la primera es sin costo?

Gracias!

**Comment by Dnpoblete** [comment]
Hola @jturquiza esta pregunta ya fue respondida en la issue #284, para que la revises y en caso de dudas preguntes en esa issue.

Éxito con la tarea 😄

**Comment by jturquiza** [comment]
Ya, muchas gracias!
