### ISSUE TITLE
Número constante de cartas en el mazo

### ISSUE THREAD

**Issue by AlonsoPizarr** [IIC2233/Syllabus#356]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/326).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/325).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, 
Mi duda es sobre si el numero de cartas del mazo(15) es constante durante el juego? En el enunciado sale que las cartas descartadas vuelven al final del mazo en el caso de que el jugador pierda o empate en la ronda, pero en el caso de que el jugador gane solo se menciona que la carta pasa al mazo de triunfos.  La carta ganadora no vuelve al mazo?
Gracias.

**Comment by mtaguero** [comment]
Hola ✨

Efectivamente el número de cartas del mazo es constante. En todo momento deben haber 15 cartas en el juego.
Cuando se habla del mazo de triunfos, se refiere específicamente a aquellas cartas que se van reuniendo para poder generar las condiciones necesarias para ganar.
Si quieres, puedes guiarte por la Figura 7 del enunciado. Las cartas que se encuentran en las esquinas superiores corresponden a las características de las cartas que están en los mazos de triunfos. Entonces, si la carta gana una ronda, esta se debería agregar al mazo ganador, pero también debería volver al mazo de juego. 

¡Si no quedó claro, no dudes en volver a preguntar 🤓!

**Comment by AlonsoPizarr** [comment]
Muchas gracias!
me quedo todo claro ahora
