### ISSUE TITLE
Problema con mensaje pop-up

### ISSUE THREAD

**Issue by Crisax234** [IIC2233/Syllabus#356]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
Hola, tengo un problema al usar QMessageBox ya que cuando quiero mostrar un mensaje para notificar de algo al usuario, el programa se me congela y me aparece esto:
![image](https://user-images.githubusercontent.com/88630837/145474396-a3f684ba-530d-4a96-89c4-e14962222169.png)
Estoy usando el mismo código que use en la tarea pasada para hacer mensajes pop-up, pero nunca me había pasado algo asi, hay alguna manera de solucionarlo?

**Comment by Emiliax16** [comment]
Hola @Crisax234 ! revisé la tarea desde tu repositorio para conocer un poco más sobre el error. En el módulo ventana_inicio, implementaste un timer, desconozco porqué, pero ese es el causante de tu problema. De hecho si lo hago sin ese timer o bajándole considerantemente el tiempo (25 seg por ejemplo), la ventana funciona y no se congela. El problema era que la ventana aparecía mientras la ventana_inicio aún tenía funcionando ese timer. Revisa bien esa parte. Suerte!

**Comment by Crisax234** [comment]
Muchas gracias! Te podría hacer otra pregunta respecto a mi codigo por discord? Que tengo un problema con una conexion entre el cliente y el servidor que no he podido solucionar hace mucho rato.

**Comment by Emiliax16** [comment]
Pucha no se puede por discord. Puedes crear una issue especificando tu problema y dejar en tu repo la versión más actualizada del código!
