### ISSUE TITLE
Pregunta noob if else en lista por comprension 

### ISSUE THREAD

**Issue by aSPCA** [IIC2233/Syllabus#356]
Puede ser muy noob mi pregunta pero esta permitido ocupar if y else dentro de las listas por comprension, o solo if ?

**Comment by Hernan4444** [comment]
@aSPCA si puedes!!
Saludos!

**Comment by afcarvallo** [comment]
y se pueden ocupar listas por compresion ([x for x in range(10)] o solo generadores por compresion lo mismo pero con parentesis()?

**Comment by Hernan4444** [comment]
#278 ultima linea
saludos!!

**Comment by afcarvallo** [comment]
cuando se refieren en el enunciado a que se pueden ocupar ciclos for para imprimir valores, quiere decir que se puede ocupar un for comunes para guardar datos en un archivo?
Enunciado: 'Nos interesa que no usen los ciclos for y while en lo que son las funcionalidades logicas del programa. Si pueden utilizarlos, por ejemplo, para imprimir valores'.

**Comment by Hernan4444** [comment]
@afcarvallo si, puedes usar un for para crear resultados.txt. Si deseas crear otro archivo para ayudar a tu programa, ese debe ser creado mediante generadores y funcional.

Saludos!!

**Comment by chuma9615** [comment]
Y se puede usar for para recorrer el array de la funcion process consult del main o no?, a mi parecer si ya que es solo para imprimir resultados en la interfaz pero no estoy seguro

**Comment by Hernan4444** [comment]
@chuma9615  #285 
Saludos!
