### ISSUE TITLE
DIAS_COMPETENCIA

### ISSUE THREAD

**Issue by cnillanes** [IIC2233/syllabus#356]
Hola!
El enunciado menciona que el campeonato tiene una duracion de DIAS_COMPETENCIA dias y que será siempre par porque los días van como en tuplas. Mi duda es, siempre será como día 1 entreno, día 2 compito, día 3 entreno y asi sucesivamente?

**Comment by vsantelicest** [comment]
Hola! Efectivamente la sucesión de días es como menciones, sin embargo, en la parte de Competencia está explícito que los días de competencia comienzan en el día cero, por lo que sería día 0 entreno, día 1 competencia, día 2 entreno y así.
