### ISSUE TITLE
Numero de barcos encallados

### ISSUE THREAD

**Issue by CGR0** [IIC2233/syllabus#356]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Cuando se selecciona ver el estado del canal en el enunciado dice que hay que poner el numero de barcos que han encallado, por lo que me surge la siguiente duda, ¿Si un barco se encalla 2 veces cuenta como una para ese dato o los barcos solo se pueden encallar una vez?

Muchas gracias de antemano!
![issue](https://user-images.githubusercontent.com/80780814/116159829-f20f0600-a6be-11eb-9699-d034afc25578.png)

**Comment by Emiliax16** [comment]
Hola @CGR0 ! se pide mostrar la cantidad de barcos que han encallado, por lo que no importa cuantas veces encalló un barco, sólo debes sumar todos aquellos que al menos una vez hayan encallado.

**Comment by FranciscoPintoo** [comment]
@Emiliax16 hola, yo tengo una duda con eso, que pasa si un barco sale del canal habiendo encallado en el. Luego vuelve a entrar y encalla otra vez en el segundo recorrido, cuenta solo 1 o los 2?

**Comment by Ignacioislae** [comment]
cps

**Comment by Emiliax16** [comment]
Hola @FranciscoPintoo ! en ese caso, podrías contar al mismo barco de nuevo sólo si encalla en la segunda vez que ingresa al canal, pero esto puede quedar a criterio de ustedes. Lo importante es que lo que sea que tomes como supuesto, lo especifiques en el README, así no habrá ningun problema c: 

@Ignacioislae Lo mismo que en el caso anterior. Eso es algo que el enunciado no especifica y bien podría contarse de nuevo o no. Particularme, creo que en el conteo de barco es mucho más lógico que si se cuenten las veces totales que pasó cada barco,  por el mismo canal. Incluye tu supuesto en el README !
