### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by furzuadr** [IIC2233/syllabus#356]
Hola! Mi programa está listo con todo lo del enunciado, funciona bien pero algunas veces pasa que me sale este error y se cae. Estuve leyendo y tiene que ver con que se acaba la memoria del computador. Mi duda va a si es que el programa se cae debido a esto cuando lo estén revisando, tengo todo malo? No tiene que ver con estar eliminando un thread que sigue corriendo, porque me ha pasado en instancias en las que no se elimina nada. Hay alguna forma de solucionarlo? Gracias!

**Comment by naquiroz** [comment]
Hola! :wave: 

De primeras, diría que no, si el programa se cae no deberías tener todo malo. Ahora bien, todo depende bastante del tipo de error que tu programa arroja, podrías indicar que error es? :smile: 

Saludos :man_dancing:

**Comment by furzuadr** [comment]
Hola! Al correr el problema por PyCharm, me sale el error: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
Al correrlo por terminal de Mac: segmentation fault: 11 python

Según estuve averiguando, el problema es debido a que se acaba la memoria del computador. También encontré que es por un problema de módulos de terceros (en este caso PyQt5), el cual a veces deja de funcionar por problemas de compatibilidad.

Alguna idea de qué podría ser? Gracias!

**Comment by IchottMano** [comment]
Hola! Disculpa la demora de la respuesta.
El error SIGSEGV es un error lanzado al intentar acceder a memoria que ha sido liberada previamente (es decir, por ejemplo, un objeto que ya no existe)
Como en python no existe uso de memoria como en otros lenguajes, existe algo llamado *garbage collector* que se encarga de liberar la memoria por tí.
Sin emabrgo, PyQt5 es algo especial, ya que es código que no está en python, por lo que a veces sucede que te tira errores que son de otro lenguaje (en este caso C++).
Para arreglar este error, usualmente lo que debes hacer es asegurarte que guardas referencias de **todos** tus objetos que aparecen en pantalla, es decir que en algun lado debes tener, por ejemplo, una lista de enemigos como atributo de alguna clase, a modo de que python sepa que tu lo necesitas y que no es correcto eliminarlo.
Epero esta explicación te haya ayudado 😄 
Saludos!

**Comment by furzuadr** [comment]
Hola! Gracias por tu respuesta. Luego de horas de revisar y de volver a versiones anteriores, me di cuenta de que mi error es al hacer un setValue en los progressBar de los enemigos. Probé instanciándolo incluso en el main game y igualmente se cae. Estuve investigando en foros y hay muchas personas que les pasa esto con PyQt5 al hacer lo mismo que yo traté de hacer. No me quedó nada más que dejar mi código comentado en esa parte. Igualmente lo incluiré en el Readme. Muchas gracias igualmente!
