### ISSUE TITLE
S4-Duda en archivo Excepciones personalizadas

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2233/syllabus#357]
Holaaaa:
Muy buenas tardes, en el archivo `Excepciones Perzonalizadas` al final aparece un ejemplo, sin embargo de este no logro entender el funcionamiento de la clase `ErrorRepeticionEstudiante`,  especificamente en que momento se define la key del diccionario `estudiantes_repetidos`. 
Espero se entienda mi duda y de antemano muchas gracias :smile:.

**Comment by retamalcito** [comment]
¡Hola @Mamunoz42!

En primer lugar, se puede ver que `estudiantes_repetidos` es un `defaultdict`, es decir, toda `key` tendrá como `value` una lista vacía por defecto. Luego, en el `__init__` de la excepción `ErrorRepeticionEstudiante`, se define la variable `numero`, la cual corresponde al atributo `numero` de la `namedtuple Estudiante` que recibe la excepción. Finalmente, luego de esto, en el mismo `__init__`, se encuentra la línea:

```python
self.estudiantes_repetidos[numero].append(estudiante)
```

En esta línea, se accede al diccionario `estudiantes_repetidos`, se crea la `key` igual a la variable `numero`, y se añade el elemento `estudiante` a la lista que corresponde al `value` de esta `key`. Esto se puede hacer justamente porque `estudiantes_repetidos` es un `defaultdict`, por lo que al hacer referencia a la `key` (sin haberla definido explícitamente), el programa automáticamente le asocia una lista vacía de `value`, a la cual se hace el `append`. Si quieres aprender más sobre el funcionamiento de los `defaultdict`, te recomiendo revisar la documentación [aquí](https://docs.python.org/3/library/collections.html#collections.defaultdict).

Espero haber respondido tu duda, ¡saludos! 👋

**Comment by Mamunoz42** [comment]
Muchísimas gracias, ahora me queda claro :smile:
