### ISSUE TITLE
Tamaño de sprites / tamaño de sprite de la casa

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#357]
Estoy tratando de generar el mapa pero tengo problemas con el tamaño de las sprites.
[https://imgur.com/a/JaQytU0](url)
Así me está quedando hasta ahora. Estoy tratando de poner cada "sprite" en una parte distinta de un QGridLayout. Como pueden ver con la foto de la tienda, el primer problema (que es obvio) es que, como la tienda es solo 1 sprite, no puedo llegar y ponerla 4 veces porque entonces se ven 4 tiendas en el mapa.
Lo que se me ocurrió para solucionar esto es cortar "manualmente" (con photoshop) el sprite en 4 piezas, y esto es lo que hice para la casa, pero esta queda con proporciones distintas a los sprites de pasto y rocas (queda de 56x56 en vez de 16x16) entonces se ve borrosa. 
Hay alguna mejor manera de resolver esto?

**Comment by dianafuentesc** [comment]
Tengo el mismo dilema
Se me ocurre que si existiera una forma de mostrar solo un cuarto de la imagen, y si se pudiera elegir qué cuarto mostrar, se podría solucionar, pero en la documentacion no encontré como :c

**Comment by aljara97** [comment]
Hola, no puedo darles directamente la solución de este tipo de problema. Sin embargo les sugiero cuestionarse si realmente es necesario hacer esto mediante un QGridLayout, o simplemente ir posicionando distintos labels según su ubicación en el mapa (i, j) y el largo N, definiendo su tamaño como se explicó en la issue #356 

Ánimo y mucha suerte con sus

**Comment by dianafuentesc** [comment]
Gracias por el tip!
