### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by FelipeIGS** [IIC2233/Syllabus#357]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo las siguientes dudas:
- cree la grilla con QGridLayout no con listas y nose si eso puede repercutir o difcicultar el proceso en general
- en el modo construcción recomiendan que lo haga en base a drag objects o mejor en base a clicks?
- no entiendo muy bien la lógica de cómo interactúan las entidades con la grilla o en insertar objetos al mapa. Que ando medio perdido en todo eso. asi que se agradecen un poco de ayuda. 

Gracias!

**Comment by Hernan4444** [comment]
Hola @FelipeIGS 

Como algunos tips:

1. Esto es 100% personal, hay alumnos que lograron hacer esto sin nunca usar QGridLayout, otros que si la usaron, y en ambos casos se ve super lo logrado. Así que depende mucho de ti y con qué elementos de pyqt te manejas mejor. Yo personalmente no soy de usar Layot y mejor jugar con posiciones fijas (como la experiencia 4, donde solo hacemos move de los elementos según lo indicado en el backend).

2. Ojo que los bonus solo se otorgan si la tarea logra tener sobre una cierta nota, y estos generalmente son más desafiantes que lo mínimo pedido. Por lo cual, se recomienda siempre partir con lo pedido como mínimo antes de ir a funcionalidades bonus.

3. Sobre esto, lo que queremos es que si hacemos click en Luigi y luego en la posición (100, 200) de la ventana de juego. Que se determine que dicha posición (100, 200) corresponde a la casilla (X, Y) de nuestra grilla, y se inserte una imagen de Luigi en dicha casilla. Ahora el cómo programar todo eso, ahí no podemos decir tanto, solo que con los contenidos del curso es posible. No podemos indicar cómo hacerlo porque en verdad existen muuuuuuchas formas de enfrentarlo, ya sea con QGridLayout, jugando únicamente con las posiciones, teniendo QLabels invisibles que detecten click, usando cosas avanzadas de pyqt5, etc, y cada una tiene sus pros y contra. Lo importante para nosotros es evaluar cómo toman todos los contenidos de pyqt que hemos vistos en clases, experiencias o que investigaron por su cuente, y los juntan para solucionar este caso aplicado, pero ahí dependerá de ti el cómo modelar esta situación.

Saludosヾ(＾-＾)ノ
