### ISSUE TITLE
Movimiento aleatorio enemigos

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#357]
Hola, a qué se refiere que el movimiento sea aleatorio del personaje? Debe ser aleatorio después de cada celda de movimiento? Lo que yo hice fue que los enemigos se movieran en una sola dirección, y cuando llega a un borde del camino, cambia su dirección, ya que si cada moviemiento es al azar, es muy poco probable que un enemigo llegue a la base. Es esto válido?

Saludos

**Comment by jaromero6** [comment]
Hola
Con respecto a que pedimos por movimiento aleatorio es como dices, el personaje avanza de manera aleatoria en cada paso. Respecto a lo segundo es válido siempre y cuando controles que no queden encerrados en una parte sin torres o que tome un camino que nunca mueren.
La idea de pedirles el movimiento aleatorio es netamente para evitar que se compliquen en como implementar esta funcionalidad **(A no ser que implementen el bonus, que sería el movimiento más correcto)**, pueden decidir implementar de otra forma el camino, pero deben **tener cuidado** en que estos queden atrapados en rutas que nunca mueren, algo que si lo hacen de forma aleatoria **no** se deben preocupar, pues la probabilidad de quedarse encerrado en un camino de este tipo es muy baja, teniendo en cuenta además que como es aleatorio siempre existirá la probabilidad de salir.
Ánimo con la tarea !!

**Comment by VicenteMerino** [comment]
Solo para aclarar, es válido mientras no queden encerrados en una parte sin torres o base también?

Ya que según lo indicado en el enunciado, esto también debería ser válido (y en mi caso, como lo implementé, los enemigos terminan llegando a la base).

![image](https://user-images.githubusercontent.com/47841749/58217992-42aba680-7cd3-11e9-8670-6ab68047276c.png)

**Comment by jaromero6** [comment]
Correcto, es válido mientras no queden atrapados, de la forma en que sea que lo implementen deben preocuparse de que no queden atrapados.
 **Aclaración**: Cuando me referí a que con movimiento aleatorio no se debe comprobar que quede encerrado, me refiero a que es imposible que al moverlo aleatoriamente **obligue** al enemigo a dar vueltas en circulos eternamente, si bien puede darlas, con mucha probabilidad en algún momento tomará otra ruta, no así con otra especie de algoritmo que efectivamente lo mande eternamente a dar vueltas en circulos. A eso me refería cuando dije que no se debe comprobar.
Resumiendo entonces con esta aclaración a tu pregunta, si tu forma de implementar el movimiento evita estos loops, entonces es válida.

**Comment by jmwielandt** [comment]
@VicenteMerino considera que podemos usar casos como estos para testear.

![image](https://user-images.githubusercontent.com/37153467/58219259-31b16400-7cd8-11e9-9c27-9569baab93c8.png)

![image](https://user-images.githubusercontent.com/37153467/58219270-383fdb80-7cd8-11e9-833b-457aaff87d4e.png)

Saludos!

PD: te recomiendo antes verificar que solución es más rápida de implementar si es que no deseas realizar el bonus, tal vez un botón o hacer click sobre un enemigo puede ser más rápido que jugar con el comportamiento del enemigo.

**Comment by VicenteMerino** [comment]
Muchas gracias, con estos casos no me serviria (ya que solo cambio de posicion al llegar a un borde). En este caso es válido que el cambio de posicion se haga con una probabilidad distinta al de continuar caminando en dicha direccion?

**Comment by nhorellana** [comment]
Hola! También tengo una duda con respecto a esta pregunta, yo modelé el movimiento de los enemigos de forma aleatoria con un movimiento de + (1, 10) pixeles en cada dirección. Mi problema es que se ve como si giraran muy rapaidamente, lo que hace que se vea como un "trompo" que no se desplaza mucho a lo largo del tiempo. Esto estaria bien igual? O se recomienda otra forma?

**Comment by jaromero6** [comment]
@VicenteMerino es válido, siempre y cuando garantizes que el enemigo no quede atrapado en un loop que hace que la ronda no termine. (Te recomiendo tener en cuenta la PD de @jmwielandt )
@nhorellana,verifica que estés referenciando bien las imágenes al momento de mover, pero de la forma que lo estás haciendo es correcto (lo de girar pasaría a ser un detalle).

**Comment by ByronHidalgo1** [comment]
Hola, ¿se considera aleatorio si le entrego ciertos patrones? Por ejemplo, me gustaría que el enemigo no girara en círculos. Tenía pensado que evitara avanzar de la forma S,D,W,A,S,D,W,A, por ejemplo, diciéndole que cada dos pasos haga un movimiento aleatorio, y obligarlo a hacer algo del tipo S,S,D,D,W,W,D,D para darle más chances a llegar a las torretas. ¿Es válido?
PD: Los enemigos se autodestruyen si se cumple un tiempo de juego (el cual está en parámetros)

**Comment by jaromero6** [comment]
@ByronHidalgo1 es vaĺido en tanto garantize lo que se ha dicho más arriba, que la ronda termine.
