### ISSUE TITLE
Duda sobre herencia de property 

### ISSUE THREAD

**Issue by BoPe3p** [IIC2233/Syllabus#357]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Tengo una duda sobre las clases "nietas" que heredan de otras dos, en el caso de la tarea serían las mutantes. 

Voy a cambiar el código para cumplir con el último requisito:
Yo definí un setter y un getter para el atributo vida para Delantero y Defensa, el último tomando en cuenta la contención del jugador, Si hago el objeto "Sergio_Ramos" que hereda de ambas clases, ¿Cómo se cual property va a heredar? Ya que debería heredar la de Defensa porque hereda la contención, ¿Se tiene que especificar esto en el código? algo así como: 

`@property`
`def Defensa.vida`
`return self._vida`

`@vida.setter....`

O se hace de otra forma?
Saludos

**Comment by CatalinaBO** [comment]
Hola! No logro entender muy bien tu pregunta, estas planteando que tienes una clase hija que hereda de dos clases padre, y quieres saber que property se va a heredar? O la duda es sobre getter y setter?

**Comment by BoPe3p** [comment]
@CatalinaBO la duda es sobre cual property va a heredar

**Comment by CatalinaBO** [comment]
Entiendo, cuando quieres heredar atributos para una clase hija aplicando multiherencia, los atributos de ambas clases padres son heredados. 
Refiriéndome a las propertys, llevándolo al contexto de la tarea, todas las plantas tienen las mismas restricciones en sus atributos, por lo que las propertys son las mismas para todas las clases de plantas. Igualmente si es que quieres heredar una property de una clase en específico pero que tiene el mismo nombre que la property de la otra clase padre, python hereda según el orden en que son declaradas las clases padres en la definición de la clase hija. Gráficamente me refiero a lo siguiente: def ClaseHija( Preferencia1, Preferencia2).
Espero se haya podido responder tu pregunta, quedo atenta!
