### ISSUE TITLE
Instalación Currency Converter

### ISSUE THREAD

**Issue by robertoorrego** [IIC2233/syllabus#357]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Estoy teniendo problemas instalando el modulo CurrencyConverter. Seguí la instrucciones de la página y aparentemente se instalo bien. Luego trate de importar el modulo en Sublime y no me funcionó. Leí el foro y intente hacer la instalación nuevamente con pip3. No me funciono. El error que da no aparece o no lo vi en otros issues.
Adjunto imagen de la Terminal
<img width="563" alt="Captura de Pantalla 2021-04-26 a la(s) 7 21 16 p  m" src="https://user-images.githubusercontent.com/70174581/116163048-00602080-a6c5-11eb-8e75-1effb85558e6.png">

**Comment by Emiliax16** [comment]
Hola @robertoorrego .

Dado que sólo tienes un WARNING, la instalación parece estar bien. ¿Estás importando correctamente la librería en sublime? porque por lo que veo, en la terminal no comprobaste bien el uso de currency_converter. Para probar cualquier librería de python por la terminal, debes:

1. escribir _python_,  **enter** (así puedes ingresar código)
2.   **>>>**  _from currency_converter import CurrencyConverter_ ,**enter**
3.   **>>>** _c = CurrencyConverter()_ ,**enter**
4.  **>>>**  _c.convert(100, 'EUR', 'USD')_ ,**enter**

Haciendo eso, no debería tener problemas de path con la librería. 

Prueba si te funciona por la terminal, si es así, debería funcionar bien desde sublime. Coméntame si te funciona!

Saludos c:

**Comment by alvaritions** [comment]
Hola, estaba probando esto y creo que se me instaló en otra versión de Python que tengo, ¿Cómo hago para tenerla en el la 3.7?

**Comment by Emiliax16** [comment]
Hola @alvaritions . Podrías eliminar las versiones anterior, desinstalándolas desde Configuración > Aplicaciones y características. Luego de desinstalar versiones anteriores, reinicia tu compu y verifica la versión que sigues teniendo. En la terminal, puedes verlo con python -version, si es 3.7.X, instala de nuevo la librería y ve si te funciona!

**Comment by alvaritions** [comment]
abrí una issue al respecto porque aqui se me olvidó decir que no puedo borrar esta otra versión porque la uso en otro curso :(
Gracias por la respuesta de todas maneras.
