### ISSUE TITLE
Atributos necesarios en clases hijas de una clase no-abstracta

### ISSUE THREAD

**Issue by amorande1** [IIC2233/syllabus#358]
Hola! En una superclase ¿Existe alguna forma de determinar que es esencial definir cierto atributo en su subclase? 
(Me lo imagino como el uso de @abstractmethod en los métodos de clases abstractas)

**Comment by retamalcito** [comment]
¡Hola @amorande1!

Cuando estamos en el contexto de una clase abstracta, definir un método como **abstracto** hace que toda clase que herede de ella **deba tenerlo**. Por lo tanto, si quieres que todas tus clases hijas tengan un método específico, puedes obligar esto haciendo que el método sea **abstracto**.

Sin embargo, cuando la superclase **no** es abstracta, **no** hay una forma de obtener el mismo comportamiento, es decir, obligar a las clases hijas a tener algún método en específico. Lo único que podrías hacer es definir tus clases hijas cuidadosamente, recordando redefinir el método para cada una. 🙁

¡Saludos y mucha suerte! 👋
