### ISSUE TITLE
importar archivos cruzadamente

### ISSUE THREAD

**Issue by anvaldes** [IIC2233/syllabus#358]
Si tengo archivo_1, archivo_2, Por qué siempre me tira error cuando hago que el archivo_2 importe el archivo_1 y el archivo_1 import el archivo_2? Que puedo hacer para solucionarlo?

**Comment by aljara97** [comment]
Hola, lo que estás haciendo es un tipo de referencia circular. Al importar un archivo_1 en un archivo_2 y a su vez haces que el archivo_2 importe al archivo_1, lo llamas infinitamente. Para solucionar este problema te sugiero hacerte las siguientes preguntas:

¿Es necesario importar el módulo completo? Probablemente solo necesitas unos elementos de cada archivo, por tanto podrías intentar hacer 
````
from archivo import elemento_1, elemento_2
````
Puede existir también el caso en que no sea necesario separar en módulos distintos, por tanto, en ese caso podrías intentar escribir todo en un mismo archivo (a menos que correspondan a elementos que deban estar en separación backend y frontend). Intenta probando estos casos y cuéntanos cómo te va
