### ISSUE TITLE
vocabulary.txt tiene dos veces la palabra like. T03

### ISSUE THREAD

**Issue by FJavierOss** [IIC2233/Syllabus#358]
Queria saber si vocabulary.txt tiene dos veces la palabra "like" a proposito o simplemente fue que esta repetida dos veces por error. PD: Para evitar programar dos veces sobre el mismo tópico

**Comment by iqacevedo** [comment]
Hola,

Fue un error, gracias por avisar. Debería estar solo una vez.

Saludos !
