### ISSUE TITLE
Actividad paranormal en Manejo de errores

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#358]
En mi programa al hacer **raise AlgunaException**, se abre una ventanita que me dice que **python dejo de funcionar** y está tratando de solucionar el problema y luego me dice que cierre el programa, lo cierro y termina la ejecución del programa(no se cierra python, solo se termina la ejecución de mi programa), lo cual no se si esta bien o mal, pero **nunca se imprime el tipo de error** con su descripción, que es lo que me importa. **¿Está mal que se abra esa ventana? Si está mal ¿Porque me pasa y que hago?**

**Comment by Hernan4444** [comment]
@jorgeriesco lo que pasa es que PyQt5 no le gustan los errores por eso cuando se genera un `raise error` si es que no se maneja ese error (con un try/except) pyqt5 se cae.

Saludos!!

**Comment by jorgeriesco** [comment]
Pero entonces que esperan que haga en el manejo de errores? Lo que quiero decir es ¿Debo hacer que el progrma se caiga cuando hay un error? Si no tengo que hacer eso ¿Que hago?

**Comment by Hernan4444** [comment]
la idea es que los manejes con los try y except necesarios para que no se genere el error pero se escriba en pantalla y/o archivo que hubo un error según como está indicado el enunciado.

Saludos!!

**Comment by jorgeriesco** [comment]
@Hernan4444  Pero debo detener el programa o no? esa es basicamente mi duda porque si tengo que pararlo, te preguntaría como hacerlo. 

Gracias!

**Comment by Hernan4444** [comment]
@jorgeriesco no tienes que pararlo, sino solo escribir como resultado de consulta que hubo un error y seguir con la siguiente consulta.
