### ISSUE TITLE
Llamar a clases dentro de parametros.py

### ISSUE THREAD

**Issue by fgallard** [IIC2233/Syllabus#358]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

No sé si está permitido, ni si funciona en Python, pero quiero ver si puedo importar y llamar a las clases de plantas en mi parametros.py para poder crear una variable de planta genérica, es decir, Solaterillo y Potensauce, etc que me sirva para crear las plantas mutadas cuando me las entregan desde un inicio, sin estar juntando dos plantas previamente conocidas. Digo que no sé si se puede en python porque estaria importando dos archivos mutuamente, pues parametros es llamado en main y en este caso main sería llamado en parámetros.

**Comment by CatalinaBO** [comment]
Hola! No se puede, ya que estarías cayendo en importación circular. Además, no es el objetivo de la tarea, ya que se busca que el archivo parámetros.py contenga solo valores númericos que serán utilizados a lo largo del programa. También se busca que sean capaces de generar instancias que heredan de clases padres, y no que sean genéricas, ya que los atributos que deben ser aumentados en cierto porcentaje dependen de los atributos de las plantas que están siendo combinadas! 
Espero se haya respondido tu pregunta, quedo atenta :)
