### ISSUE TITLE
gemelo genetico

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#358]
en el enunciado se dice

> Esto debe ser genéticamente y no fenotípicamente; es decir, puede que una persona de pelo negro sea más parecida a una persona rubio en vez de una persona de pelo negro, por la cantidad de genes de ese tipo que tenga. Una persona se declara parecida a otra según la cantidad de genes en común que tengan para cada característica

Si en la persona que se esta comparando se expresa este gen 1 vez, pero en la otra se expresa 2 veces, se cuenta como 1 vez o como dos?

**Comment by Hernan4444** [comment]
@rihanuch como uno puesto que tienen 1 gen en común.

Saludos ✌️

**Comment by rihanuch** [comment]
Ok! Gracias!
