### ISSUE TITLE
Error desconocido

### ISSUE THREAD

**Issue by egarnham1** [IIC2233/syllabus#358]
Cuando inicio la ronda y aparecen los enemigos, el programa se cae y aparece este error:
Process finished with exit code -1073740940 (0xC0000374)
Esto a pesar de implementar el código para que se vean los errores, del jupyter notebook 3 de la semana 9 de los contenidos. 
El error aparece antes cuando hay más de cuatro enemigos; con cuatro o tres se cae cuando muevo mucho el personaje, y con uno no hay problema. 
Estoy usando clases que heredan de QThreads, una en el backend y otra en el frontend. Esta ultima se instancia cada vez que quiero mover la QLabel, su método run( ) la mueve, y se guarda en una variable que después la reemplaza por otra instancia (para mover de nuevo la label). Creo que el problema está en esta clase pero no se que puede ser.

**Comment by IchottMano** [comment]
Hola!
Estas usando pycharm? Si es asi, tal vez [este link](https://cvisiondemy.com/solve-exit-code-1073741819-0xc0000005-error-in-pycharm/) te sea útil.
Esos errores no son muy específicos, por lo que pudo ser causado por varias razones distintas. Entre ellas posiblemente un error con windows.
Avísame por favor si esto resuelve tu problema.
Saludos!

**Comment by egarnham1** [comment]
Apliqué las soluciones 1 y 3, parece que la 2 no puedo porque no tengo Django. No me resultó :(

**Comment by IchottMano** [comment]
Puede que sea un problema al momento de tener muchos threads haciendo que se caigan los enemigos, o tambien un problema con la memoria.
Has intentado correr tu programa usando la consola en vez de pycharm?

**Comment by egarnham1** [comment]
Lo intenté con la consola y con el IDLE, y nada, se cae igual sin indicar ningun error

**Comment by IchottMano** [comment]
Cuando dices que guardas el QThread en una variable, lo guardas en algun otro lado? Como una lista de enemigos o algo asi? Puede que tengas un problemas porque te quedas sin referencia de los threads y estos son eliminados por python, intenta tener guardado en alguna parte las referencias de los objetos que estas declarando.

**Comment by lfuenzalida2** [comment]
Yo estoy teniendo el mismo problema con la diferencia de que el error que me lanza es exactamente el mismo que le aparece al que escribio la solucion del [link](https://cvisiondemy.com/solve-exit-code-1073741819-0xc0000005-error-in-pycharm/). También trate de hacer la solucion 1 y 3 del link y no me funciono ninguno

Lo raro es que el error no me aparece de manera constante, aparece al azar cuando corro un programa, es decir, puede aparecer al segundo 1 o aparecer luego de 10 min. 

Llevo este problema desde que comence a usar QTimer y QThread creo, antes de eso no tuve problemas.
