### ISSUE TITLE
parametros.py (Uso de todos los parametros)

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#358]
Hola! Tenemos que agregar todos los parámetros tipo, el mínimo de salud es 1, y tenemos que hacer uso de todos los parámetro escritos en parametros.py? O podemos ir selecionando los más relevantes a nuestro codigo?

**Comment by Dnpoblete** [comment]
Hola @CataSudo esta pregunta ya fue respondida en la issue #278, para que la revises y en caso de tener dudas preguntar en esa issue.

Éxito en la tarea! 😄
