### ISSUE TITLE
Sobre lanzar 2 QApplications...

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#358]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Se menciona que el tener dos QApplication lanzará error. ¿Por qué no me ocurrió a mi?
![image](https://user-images.githubusercontent.com/66154723/116167210-c3e4f280-a6cd-11eb-92f3-4ccc6038cc99.png)
![image](https://user-images.githubusercontent.com/66154723/116167223-cb0c0080-a6cd-11eb-9744-53f1a4b91d08.png)

**Comment by aaossa** [comment]
Hola @fernandosmither , técnicamente no hiciste lo que dice ahí 😅 Prueba duplicando la línea, lo que sí producirá un error:

```python
if __name__ == '__main__':
    app = QApplication([])
    app = QApplication([])
    form = MiVentana()
    sys.exit(app.exec_())
```

Ojo que este error no ocurre directamente en Python, sino que viene desde el *back-end* de PyQt (Qt). Sospecho (no tengo certeza) que esto ocurre porque Python "borra" su referencia a la primera `QApplication`, pero para Qt sigue existiendo. En el ejemplo que tu hiciste, ambas `QApplication` siguen existiendo tanto para Python como para Qt.  Ojo que el código que puse funciona si es que entre las dos declaraciones de `app` borras explícitamente la variable (`del app`).

---

Sé que la idea es que solo exista una instancia de `QApplication` a la vez tanto para Python como para Qt, pero estuve jugando un poco con esto. Al parecer, cuando creas dos variable, se crean dos objetos distintos (mira las direcciones de memoria):
```python
>>> app = QApplication([])
>>> print(app.instance())  # Creamos una QApplication
<PyQt5.QtWidgets.QApplication object at 0x00000167A399EDC8>
>>> app2 = QApplication([])
>>> print(app2.instance())  # Ahora tenemos una nueva instancia
<PyQt5.QtWidgets.QApplication object at 0x00000167A59C7AF8>
>>> print(app.instance())  # Pero esto reemplaza a la anterior
<PyQt5.QtWidgets.QApplication object at 0x00000167A59C7AF8>
```

Sin embargo, si usamos la misma variable, parece que hay una "descoordinación" (o al menos así lo explicaría) entre Python y Qt que impide que Qt pueda crear una nueva instancia:
```python
>>> app = QApplication([])
>>> print(app.instance()) 
<PyQt5.QtWidgets.QApplication object at 0x0000017716E9E438>
>>> app = QApplication([])
>>> print(app.instance())
None
```

No estoy 100% seguro de qué ocurre, y tampoco creo que sea un *bug*, solo que Python permite hacer cosas que originalmente no se podían hacer en Qt (programado en C++) y eso produce este tipo de comportamientos.

**Comment by fernandosmither** [comment]
> Hola @fernandosmither , técnicamente no hiciste lo que dice ahí 😅 Prueba duplicando la línea, lo que sí producirá un error:
> 
> ```python
> if __name__ == '__main__':
>     app = QApplication([])
>     app = QApplication([])
>     form = MiVentana()
>     sys.exit(app.exec_())
> ```
> 
> Ojo que este error no ocurre directamente en Python, sino que viene desde el _back-end_ de PyQt (Qt). Sospecho (no tengo certeza) que esto ocurre porque Python "borra" su referencia a la primera `QApplication`, pero para Qt sigue existiendo. En el ejemplo que tu hiciste, ambas `QApplication` siguen existiendo tanto para Python como para Qt. Ojo que el código que puse funciona si es que entre las dos declaraciones de `app` borras explícitamente la variable (`del app`).
> 
> Sé que la idea es que solo exista una instancia de `QApplication` a la vez tanto para Python como para Qt, pero estuve jugando un poco con esto. Al parecer, cuando creas dos variable, se crean dos objetos distintos (mira las direcciones de memoria):
> 
> ```python
> >>> app = QApplication([])
> >>> print(app.instance())  # Creamos una QApplication
> <PyQt5.QtWidgets.QApplication object at 0x00000167A399EDC8>
> >>> app2 = QApplication([])
> >>> print(app2.instance())  # Ahora tenemos una nueva instancia
> <PyQt5.QtWidgets.QApplication object at 0x00000167A59C7AF8>
> >>> print(app.instance())  # Pero esto reemplaza a la anterior
> <PyQt5.QtWidgets.QApplication object at 0x00000167A59C7AF8>
> ```
> 
> Sin embargo, si usamos la misma variable, parece que hay una "descoordinación" (o al menos así lo explicaría) entre Python y Qt que impide que Qt pueda crear una nueva instancia:
> 
> ```python
> >>> app = QApplication([])
> >>> print(app.instance()) 
> <PyQt5.QtWidgets.QApplication object at 0x0000017716E9E438>
> >>> app = QApplication([])
> >>> print(app.instance())
> None
> ```
> 
> No estoy 100% seguro de qué ocurre, y tampoco creo que sea un _bug_, solo que Python permite hacer cosas que originalmente no se podían hacer en Qt (programado en C++) y eso produce este tipo de comportamientos.

### Como siempre, profesor, completísima la respuesta. Muchas gracias! Extrañísimo como se comporta PyQt en estos casos.  Ojalá no tener que lidiar con esto en el futuro.
☺
