### ISSUE TITLE
Do one thing and do it well... ¿qué tan extremo?

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#359]
Hola, 
Quería saber qué tan extrema será la solicitud de que cada función realice un único trabajo, porque podría abrir un archivo, sacar su info, aplicarle un formato dado y hacer que me retorne un generador en una sola función pero eso se considera como "una tarea" (compuesta por micropartes).
No me imagino haciendo una función que abra un archivo o.o

Gracias
![image](https://user-images.githubusercontent.com/37153467/39281380-9c74e8d0-48da-11e8-97b6-3db1d448efa6.png)

**Comment by Arcoirisky** [comment]
Hola!
La idea es que una función pueda hacer todo lo que propones siempre y cuando no necesites una similar para hacer algo parecido. En el caso del ejemplo estaría mal hacer funciones separadas para obtener cada parte del archivo.

Ten en mente que la filosofía fomenta el reutilizar funciones más que reutilizar código (copy/paste o similar) :O
