### ISSUE TITLE
Cerrar Ventana y Abrir Otra inmediatamente

### ISSUE THREAD

**Issue by anvaldes** [IIC2233/syllabus#359]
Hola, tengo la siguiente situación:

1. Cuando ingreso un mapa que tiene la dirección correcta, entonces estoy okey, y se cierra mi ventana de inicio a través del envio de señales y todo bien. El problema es justamente como hacer para desde mi frontend mandar una señal a mi backend para que la ventana de Juego en ese instante también se muestre. Y quería saber que opciones podrían hacerse porque he intentado varias y no resultan

**Comment by gatochico** [comment]
Hola! 

Aunque no podemos dar la respuesta concreta :see_no_evil:, te puedo recomendar que revises de forma **muy detallada** la ayudantía extra que se subió al [syllabus](https://github.com/IIC2233/syllabus/tree/master/Ayudantias/AYEX-Interfaces_graficas). 

En específico, revisa bien el flujo del programa (tanto en backend como en frontend) cuando se pasa de una ventana a otra, que es justo lo que deseas hacer. Si aún así tienes dudas sobre partes en específico de dicho código (no pedir exactamente la respuesta), no dudes en preguntarlas en esta issue!

Exito y quedamos atentos!
