### ISSUE TITLE
Aproximación de valores aleatorios 

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2233/syllabus#359]
Hola, estos valores deben ser floats entre los valores respectivos de cada delegacion. Pero al ocupar la recomendacion del random que sale en el enunciado, salen decimales grandes. Lo dejamos asi o se puede redondear?

**Comment by jitorcas** [comment]
Hola! @conyfernandezt 

Dado que en el enunciado no se especifica que se deban redondear, puedes redondearlos, pero debes indicar en el README que los redondeaste y en qué líneas lo hiciste, para que el ayudante pueda deshacerlo en caso de ser necesario. 

Mucho éxito! 🥇
