### ISSUE TITLE
Ascendencia albina

### ISSUE THREAD

**Issue by Fhguinez** [IIC2233/Syllabus#359]
En el enunciado dice:
"La mayoría de las ascendencias se pueden identificar mediante los fenotipos, a excepción de la ascendencia albina la cual se podrá identificar mediante el genotipo"

¿Esto se refiere a que basta con que la persona tenga una vez el gen albino (AAT) para tener esta ascendencia? En ese caso, aquellos con la piel albina, blanca o morena tendrían siempre ascendencia albina.

**Comment by Hernan4444** [comment]
@Fhguinez precisamente 👍 

Saludos ✌️

**Comment by Hernan4444** [comment]
@Fhguinez Leyendo el enunciado determinadamente, este dice
> Para la ascendencia albina, solo deberás ver si el gen albino, AAT, está presente en **las características
donde se puede expresar el gen**. Entonces, una persona será albina si el gen AAT está presente en sus secuencias genéticas de los **ojos, el pelo y la piel**.

Lo que tu dices sirve para analizar el tema dela piel pero te falta ver el caso de los ojos y pelo. Una persona será ascendencia albina si se cumple la presencia de ATT en los ojos, pelo y piel.
Disculpa por no percatarme de ese **gran** detalle.

Saludos ✌️

**Comment by jerosalazar** [comment]
@Hernan4444 entonces para que una persona tenga ascendencia albina tiene que tener el gen AAT en las 3 características (si tiene el gen en ojos y pelo pero no piel entonces no tiene ascendencia albina)?

**Comment by Hernan4444** [comment]
@jerosalazar exactamente 👍
