### ISSUE TITLE
Hay algun problema con cargar los QPixmap desde el backend?

### ISSUE THREAD

**Issue by dvillas28** [IIC2233/Syllabus#359]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Lo que dice el titulo, en mi codigo, cargo los QPixmap con los paths desde el backend, para que luego este mismo vaya gestionando que enviarle al frontend, y este ultimo solo se encargue de setear a un label lo que sea que le haya llegado. ¿Es considerado una mala practica?

Saludos!

**Comment by CrisDonosoMaass** [comment]
Hola! Sí, es una mala práctica. Una buena modularización de front y backend debería funcionar en la que frontend se encargue de todo la parte UI, al setear los QPixmap desde el backend le estás dando una responsabilidad extra a este que originalmente no le corresponde.

**Comment by dvillas28** [comment]
vale, lo suponia
muchas gracias!
