### ISSUE TITLE
Fondos barco y COSTO_DESENCALLAR

### ISSUE THREAD

**Issue by Nicolemarin** [IIC2233/syllabus#359]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En la opción de desencallar barco, mencionan que cuando el barco queda "sin fondos" no puede desencallarse. Mi duda es cómo medimos los fondos del barco? Porque los barcos no traen "cantidad de dinero" en los archivos csv.
Mi duda es si se espera que creemos un atributo self.dinero de barcos, o los fondos se miden a través cantidad de mercancía que lleva?

Además se menciona que para intentar desencallar un barco, se hace un cobro de COSTO_DESENCALLAR, y no me queda claro si este costo lo paga el barco al canal, el canal al barco? En la issue #308 alguien menciona que es un cobro que le hace el barco al canal , pero no me hace sentido.

Gracias!

**Comment by manearaya** [comment]
Hola @Nicolemarin!

Como se ha dicho en las issues anteriores, no es necesario llevar la cuenta del dinero de los barcos.  En el enunciado es el canal que tiene el método que desencalla un barco, y es el canal que el debe pagar el costo para intentar desencallar un barco: no el barco.

En la parte 4.2.2, cuando se dice que hay que verificar si se tienen suficientes fondos se refiere a que se tiene que verificar que el canal tenga suficientes fondos para asumir el costo. A lo que se refiere la issue #308 es que este costo se paga cuando se intenta desencallar, independiente de si se logra desencallar o no.

Espero que haya quedado claro! Quedo atenta cualquier duda.
