### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#359]
lo que pasa es que al enviar una consulta a la interfas falla. Segun yo no es mi culpa porque cuando uno sube una consulta no la esta ejecutando(tambien intente descargando de nuevo el main.py), asi que intente de diversas formas por si era eso.
['extraer_columna', 'practica_lectura.csv', 'tiempo_infectado']
[['extraer_columna', 'practica_lectura.csv', 'tiempo_infectado']]
'['extraer_columna', 'practica_lectura.csv', 'tiempo_infectado']'
'[['extraer_columna', 'practica_lectura.csv', 'tiempo_infectado']]'
pero sigue fallando
![c1](https://cloud.githubusercontent.com/assets/26102365/25559776/ee296c9e-2d17-11e7-894c-770946462bf0.PNG)
![c2](https://cloud.githubusercontent.com/assets/26102365/25559777/f0550db6-2d17-11e7-9e8f-d4881e5fd0ef.PNG)

a menos que cuando se sube entonces ejecuta la consulta de inmediato en ese caso si seria mi culpa

**Comment by Hernan4444** [comment]
@Dunkan1 puedes intentar con las doble comillas ( " ) en vez de comillas simples?? y me cuentas
Saludos!

**Comment by Dunkan1** [comment]
:tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada:
con que era eso, gracias
