### ISSUE TITLE
QPainter error

### ISSUE THREAD

**Issue by dacampos1** [IIC2233/syllabus#359]
Me aparece el siguiente error, supongo que tiene que ver con que las imágenes se demoran en actualizarse y hace que se cierre a veces.
![Captura de Pantalla 2019-05-22 a la(s) 19 24 43](https://user-images.githubusercontent.com/42916420/58215385-ab8d2180-7cc7-11e9-8fa6-e45174b88f75.png)
No use en ninguna parte la clase QPainter

**Comment by jaromero6** [comment]
Hola
Te recomendaría revisar bien tú código, pues ese error se debe por usar la clase QPainter, encontré este [enlace](https://www.qtcentre.org/threads/22570-problem-in-QPainter-begin) que te puede ayudar ( si bien está en C, PyQt está hecho a partir de Qt de C, por lo que las clases y los métodos funcionan de la misma forma).
Espero que te sirva

**Comment by kmhaller** [comment]
Hola, a mi me pasa lo mismo y no se donde tengo la clase QPainter ocupada.
Que puede ser lo que causa el error? No entendí bien cómo hacer lo del enlace.
Subí mi código.
