### ISSUE TITLE
error colisiones

### ISSUE THREAD

**Issue by rominaarancibia** [IIC2233/Syllabus#359]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Al momento de evaluar posibles colisiones del personaje me sucede que ya definí que reconozca las paredes pero no respeta este requisito. No entiendo porque. Subí el archivo a mi repositorio como logica.py dentro de la carpeta backend por si lo pudieran ver. Es entre las lineas 107-138 donde radica el problema. Muchas gracias

**Comment by Hernan4444** [comment]
Hola @rominaarancibia 

Intenté ver tu código, pero solo con los archivos que subiste, no fuí capaz de encontrar el error 😭, a simple vista parece que está todo bien, pero claramente no debe ser así cómo tu indicas. Lo que te recomendaría es que, cuando veas esto, intentes subir tooodo el código que tienes, así el lunes cuando volvemos al horario laboral, revisar tu código y poder determinar qué está ocurriendo para dar alguna pista de cómo enfrentarlo. Tal vez hay algo en el frontend que gatilla este error.

Lo único que me levantó una mini alerta, es que en tu método `cargar_mapa` defines un diccionario como  `self.tablero`, y luego haces `self.diccionario_grilla = self.tablero`. Cuando hace esto, ambos atributos (`self.diccionario_grilla` y `self.tablero`) están apuntando al mismo diccionario. Por lo tanto, cuando uno se edita, el otro tambien se editará. 

Aquí dejo un ejemplo más visual donde creo `diccionario`, luego hago `otro = diccionario` y edito `otro`.... pero `diccionario` tambien terminó siendo editado.
 
<img width="226" alt="image" src="https://github.com/IIC2233/Syllabus/assets/15641721/679ca614-9101-444d-9518-fe29e0fb2398">

No sé si eso puede estar gatillando el problema, pero mejor lo menciono por si acaso. Si deseas duplicar un diccionario, recomiendo investigar como asegurar una verdadera copia de un diccionario.

Saludosヾ(＾-＾)ノ

**Comment by rominaarancibia** [comment]
Hola profe! Está bien subiré el código completo apenas pueda. Sin embargo, estoy segura que el error radica en el archivo que mencione y subí en vista a que desde ahí se envía las coordenadas al frontend para actualizar posiciones. Por lo que, si reconociera correctamente la pared no enviaría sus coordenadas si identifica que en esas esta alguna pared. Veré lo del diccionario pero igualmente ya probé otra forma sin intentar duplicarlos y me sigue ocurriendo lo mismo por lo que el error no radica ahí. Concretamente lo que me sucede es que reconoce la pared como saltando. Por ejemplo si tengo 4 paredes en las posiciones (5,4), (6,4), (7,4), (8,4) solamente evita que se mueva en (6,4) y (8,4). No se si me recomendaría usar mejor otra manera.

**Comment by rominaarancibia** [comment]
Hola profe ya pude encontrar el error. Igualmente graciass
