### ISSUE TITLE
Feedback T01

### ISSUE THREAD

**Issue by nhorellana** [IIC2233/syllabus#36]
Hola! Van a subir un feedback tipo excel con la asignación de puntaje esperada por item?
Saludos!

**Comment by iqacevedo** [comment]
Hola,

Entre hoy y mañana subiremos la asignación de puntajes.

Saludos !

**Comment by angelaparriana** [comment]
Hola! Dónde se encuentra este feedback? Muchas gracias!

**Comment by iqacevedo** [comment]
Hola,
El enlace se envió por un anuncio del curso. Lo puedes encontrar [aqui](https://docs.google.com/spreadsheets/d/1M8KsuF9yip-18tZqPmc-BU4VfPxCf-KZpJ_FSSCRzpA/edit?usp=sharing).

Saludos
