### ISSUE TITLE
Problema con el comando jupyter notebook

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#36]
Hola! estaba siguiendo los pasos del video pero me sale que no existe jupyter
![Captura de Pantalla 2020-08-17 a la(s) 15 17 47](https://user-images.githubusercontent.com/62019255/90435412-f51c1600-e09c-11ea-8f9b-c25fc2ec221c.png) y nose que hacer porqué todos los demás pasos me funcionaron bien, revise el setup de python y tambien se descargo bien jupyter, por favor si me podrian ayudar, gracias!

**Comment by igbasly** [comment]
Hola @Natydlb :v:

Puedes ver las issues #10 y #5 por temas similares. Coméntame si esto es de ayuda o si el problema aún persiste.

Quedó atento, saludos 😄

**Comment by Natydlb** [comment]
Muchas gracias!! Me funciono @igbasly
