### ISSUE TITLE
Error al correrlo en el terminal 

### ISSUE THREAD

**Issue by martinrtc** [IIC2233/syllabus#36]
hola, al correr mi codigo en IDLE no presenta ningun problema, pero al correrlo en el terminal del mac me arroja este error:
```bash
MacBook-Pro-de-Martin-3:T00 Martin$ python menu_inicio.py
Traceback (most recent call last):
  File "menu_inicio.py", line 1, in <module>
    from partida import crear_partida
  File "/Users/Martin/Desktop/martinrtc-iic2233-2019-2/Tareas/T00/partida.py", line 10, in <module>
    from tablero import print_tablero_con_utf8
  File "/Users/Martin/Desktop/martinrtc-iic2233-2019-2/Tareas/T00/tablero.py", line 5
SyntaxError: Non-ASCII character '\xe2' in file /Users/Martin/Desktop/martinrtc-iic2233-2019-2/Tareas/T00/tablero.py on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
El cual por o que leo parece ser un error del archivo de tablero.py que nos dan. 
A un amigo le pasaba lo mismo..
Si alguien podria ayudarnos seria bacan, ya que no sabemos como arreglarlo

**Comment by entamburini** [comment]
Hola Martín,

Viendo su problema, se me ocurren dos posibles causas:

MacOS trae python 2 por defecto, de hecho si usas el comando:
```bash
python --version
```
Quizás veas que no esté llamando a python 3.7 sino que a la versión de python que tiene tu sistema operativo :O La forma fácil de arreglar eso es especificando que quieres usar python 3:
```bash
python3 menu_inicio.py
```
La otra solución es poniendo en el principio del archivo .py el encoding (esta la saqué del primer [link de google](https://www.google.com/search?q=macos+python+non+ascii&oq=macos+python+non+ascii&aqs=chrome..69i57j33l5.10895j0j7&sourceid=chrome&ie=UTF-8) ): 
```python
#principio del archivo
#coding: utf8 
```
Espero tus respuestas! :D

**Comment by martinrtc** [comment]
muchas gracias! ese era el problema, habia que correrlo con python3, funciono perfecto muchas gracias

**Comment by JuanDlugo** [comment]
Muchachos me esta pasando lo mismo en mi Mac, y no entendí como lo resolvieron.
Por favor si me pueden explicar que hicieron para solucionarlo ;)

**Comment by martinrtc** [comment]
En el terminal en vez de escribir:

python menu_inicio.py

Escribe;

python3 menu_inicio.py

Asi el Mac lo corre en Python 3 y no en el 2 que está por defecto en los
macs.
Asi se me arreglo altiro

**Comment by lily416** [comment]
@JuanDlugo tu error se debe a que el programa no es capaz de imprimir los caracteres especiales del print, pasale al `print_tablero()` `False` como segundo argumento para que no imprima los caracteres especiales.

Ojalá que con esto se arregle 🙏

**Comment by JuanDlugo** [comment]
¡Muchas Gracias a ambos!
Efectivamente era lo de python, pero nose pq yo tenía que especificar python3.7 enunciado.py 
y ahí efectivamente funcionó
¡Gracias!
