### ISSUE TITLE
Consultas básicas/ Entidades

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#36]
En el enunciado se presentan 3 entidades (ANAF, Pilotos, Jefes) y se pide  realizar el programa "SuperLuchin" para gestionar eficientemente los recursos de la agencia. Lo que no me queda claro es si es porqué los jefes y los pilotos son entidades si se supone que ellos pueden realizar sus funciones gracias a los recursos que tiene la ANAF, y por ende, deberían ser parte de esta agencia. Si no son parte de la ANAF, entonces mi pregunta es si en el menú inicial debe estar la opción de ingresar como "Usuario ANAF",  "Piloto" o "Jefe" (?) y luego desplegar un menú según si son "Usuarios ANAF" o "Piloto"/"Jefe". 
Por favor aclararme la relación entre las entidades.
Saludos!

**Comment by rpalmaotero** [comment]
Cada usuario tiene un sólo rol, el cuál está definido por el atributo `recurso_id` de la tabla `usuarios.csv`. Sólo los usuarios de la ANAF pueden calcular estrategias, hacer consultas avanzadas, etc. Los jefes/pilotos sólo tienen acceso a la información del recurso al cuál pertenecen y de los incendios a los que han sido asignados.

**Comment by acrojas2** [comment]
entonces tanto los usuarios ANAF, los jefes y los pilotos deben poner su usuario e ingresar su contraseña

**Comment by rpalmaotero** [comment]
@acrojas2 claro.
