### ISSUE TITLE
[Ejercicio 3 - Semana 01 - DCCgram] Diferencia entre atributos públicos y privados de la clase Usuario.

### ISSUE THREAD

**Issue by maromero-21** [IIC2233/Syllabus#36]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Mi duda respecto a este ejercicio tiene que ver con la diferencia entre los atributos de formato **_"self.__atributo"_** y **_"self.atributo"_** de la clase **_Usuario_**.
Según lo que entendí es que las condiciones de edad, correo y rut se hacen en base a los atributos en formato **_"self.atributo"_** , y solo si es que estos cumplen las condiciones, entonces actualizariamos los valores de los formato _"self.__atributo"_. ¿Estoy en lo correcto o no?

Gracias por su tiempo!

**Comment by mskdancers** [comment]
Hola!
Exacto, los atributos privados (_"self.__atributo"_) son para almacenar los valores, y los otros (_"self.atributo"_) son en realidad las properties asociadas a cada atributo. Lo que está pasando en el _init_ es que inicializas los valores de los atributos privados como _None_ y luego llamas a los setters de cada property para actualizar el valor de cada atributo con los argumentos que se te entregaron, dependiendo si estos cumplen las condiciones o no. Esta última parte es la que tienes que programar tú 😉 
Mucha suerte!
