### ISSUE TITLE
AC1 Problema con test cases función animes_por_estreno

### ISSUE THREAD

**Issue by Igufu** [IIC2233/Syllabus#36]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Saludos, tengo un problema respecto a la función `animes_por_estreno(animes: list) -> dict:` en la actividad 1.
Cuando corro el test con el comando `python3 -m unittest -v -b tests_publicos.test_consultas_animes_por_estreno` o todos los test a la vez hay veces que la consola imprime `failures=2`,`failures=1` o `OK`. 

Específicamente el error viene del test `test_resultado_varios_repetidos`
```
AssertionError: {2016: ['Gintama', 'BnHA'], 2011: ['Chihiro', 'Amapolas'], 1998: ['Sakura']} != {1998: ['Sakura'], 2011: ['Chihiro', 'Amapolas'], 2016: ['BnHA', 'Gintama']}
- {1998: ['Sakura'], 2011: ['Chihiro', 'Amapolas'], 2016: ['Gintama', 'BnHA']}
?                                                                   --------

+ {1998: ['Sakura'], 2011: ['Chihiro', 'Amapolas'], 2016: ['BnHA', 'Gintama']}
?                                                          ++++++++. 
```

De manera de prueba corrí el código 100 veces y anoté los resultados en la siguente tabla:

| Output   | times |
| -------- | ------- |
| Failures=2  | 63  |
| Failures=1| 7  |
| OK  | 30 |

También me aseguré de correr el código en el path correcto (/Actividades/AC1) y de jamás editar los test cases.

Me parece un tanto extraño el error ya que en el enunciado dice que el orden de los animes dentro de las listas no importa:

![imagen](https://github.com/user-attachments/assets/0f8a1ba5-8046-4c51-8728-a2112cecbff6)
Estoy seguro de que es un error mío, una sospecha que tengo es que tal vez el error se genera de otra parte, tal vez con los types pero la verdad es que he estado varias horas tratando de arreglarlo y no puedo llegar a pasar los tests de forma consistente.

<hr>

Gracias y disculpen las molestias! :)

<img src="https://i.pinimg.com/originals/df/f5/d7/dff5d7e39e452ad7c5c48c0b1c1b03f1.gif" alt="ibuki thumbs up yipee" width="250" height="150"/>
(unrelated gif)

**Comment by Igufu** [comment]
Ok he solucionado el problema rehaciendo la función desde 0, el problema pareció surgir o desde el desempaquetamiento de la namedtuple o desde el operador `dict()`. Dejare este Issue abierto ya que aún no estoy seguro cuál fue el problema original, y especialmente el hecho de que los testcases a veces daban bueno y a veces malo.

**Comment by Igufu** [comment]
Hola!

He subido un archivo llamado `main_viejo.py` a mí repositorio en -  `AC1/Test_issue` una cosa a destacar es que no use la namedtuple de manera (cosa que estoy arreglando), tal vez el bug podría originarse por eso. Ahora mismo no estoy en mi casa por lo que no alcanze a poner anotaciones. Así que si el código es muy difícil de entender al llegar a mi casa le pongo anotaciones para que sea más comprensible.

Gracias! 🐧

**Comment by Hernan4444** [comment]
Hola @Igufu 

Revisé tu código y el tema es el uso de `set` y luego su transformación a una lista. En Python, los conjuntos (`set`) son colecciones desordenadas y no tienen un orden garantizado. Cuando transformas un `set` en una lista, el orden de los elementos en la lista puede no ser consistente porque los `set` no mantienen un orden fijo de los elementos.

El orden de los elementos en un `set` puede variar entre diferentes ejecuciones (como lo que te ocurrió a ti), o incluso entre diferentes ejecuciones de esa misma función dentro de una misma ejecución del programa. Por eso, en general si vas a transformar un `set` a una lista, nunca esperar que el orden se mantenga, ahí es recomendable explorar otras herramientas, por ejemplo, transformar a lista y luego aplicar un tipo de ordenamiento deterministico. 

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ

**Comment by Igufu** [comment]
Hola!

Gracias me quedo claro el error, la verdad tiene mucho más sentido de lo que pensaba.

Nuevamente agradezco la ayuda y espero que tenga un buen fin de semana!, ahora cerraré el issue.


<img src="https://media1.giphy.com/media/Sm9AfJRiZofjlrkAAl/giphy.gif?cid=6c09b952ykrrkrqxjzf7yzdcga1opuiahfm7fiwahr73o1q0&ep=v1_gifs_search&rid=giphy.gif&ct=g" alt="typingcat"/>

**Comment by Hernan4444** [comment]
Hola @Igufu 

Recuerda porfis que en las [Reglas del foro](https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)) (punto 8) es que no cierren la issue. Esto lo haremos nosotros 😁

🦖
Saludosヾ(＾-＾)ノ
