### ISSUE TITLE
Orden de columnas en archivos CSV

### ISSUE THREAD

**Issue by aecanales** [IIC2233/Syllabus#36]
En la sección 10 del enunciado de la T01 hay la siguiente ominosa frase: "Cabe destacar que, en el formato CSV, **el orden de las columnas pueden variar.**" :ghost:

En nuestra tarea, ¿debemos tomar en cuenta este hecho? ¿O podemos asumir que los archivos CSV de la tarea siempre tendrán el mismo orden de columnas que los archivos iniciales dados por `generar_archivos.py`? Es decir, que podamos asumir que en el archivo `galaxia.csv` la primera columna siempre contendrá el nombre de la galaxia, la segunda siempre el número de minerales, y la tercera siempre el número de deuterio.  

¡Gracias de antemano!

**Comment by iqacevedo** [comment]
Hola,

Es tal como dice el enunciado, no puedes asumir que estarán en ese orden. Lo único que si tendrán es que existirá cada una de las columnas que ya están en los archivos csv.

Saludos !
