### ISSUE TITLE
Prograpost y todo tipo de caracteres

### ISSUE THREAD

**Issue by anamanzana** [IIC2233/syllabus#36]
Me gustaría saber si los prograpost pueden tener una coma. Me fije que en ningún ejemplo de texto de prograpost existe una coma y me produce un cambio de columna dentro del .csv tener un input de texto con ",".

**Comment by MatiasDuhalde** [comment]
Hola!

Tal y como se dice en el enunciado, los _prograposts_ **si pueden tener comas** (`,`). No te guíes por las columnas del csv. Siempre las entradas del archivo `posts.csv` van a tener el formato `usuario_creador, fecha_de_emision, cuerpo`, y de estos la parte `cuerpo` puede tener comas.

Si te fijas en la séptima línea del archivo:
`Dnpoblet3,2019/07/06,billie eilish, carly rae jepsen, and miley cyrus should form a pop group called billie rae cyrus`
Esta tiene 4 comas:
- El que separa el usuario de la fecha
- El que separa la fecha del cuerpo
- Y los últimos dos son parte del cuerpo

Por lo tanto, en tu código vas a querer tomar en cuenta solo los dos primeros comas al momento de separar las líneas.

Ojalá eso responda tu pregunta :)
