### ISSUE TITLE
Duda Registro de Usuario ya registrado

### ISSUE THREAD

**Issue by aplaza2** [IIC2233/Syllabus#36]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

*Hola, en el enunciado dice que mientras se cumplan los requisitos del nombre de usuario a registrar, solo lo registremos, ¿pero qué hacemos en caso de que el nombre que se trate de registrar ya está ingresado?*

**Comment by Juampisaez** [comment]
Hola @aplaza2!
En el enunciado, en el Menu de inicio, dice _"...se pedirá el nuevo nombre de usuario verificando que este no se encuentre utilizado por otro usuario..."_ al momento de registrar un usuario. Por lo cual, si el usuario ya se encuentra registrado, se deberá notificar y volver al Menu de inicio.

Espero quede mas claro
Quedo atento de igual manera :)
