### ISSUE TITLE
Error o Línea Descartada en plantas.txt ??

### ISSUE THREAD

**Issue by JVeloz19** [IIC2233/Syllabus#360]
### Prerrequisitos
* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola buenas !!
En el archivo plantas.txt hay una línea que sale "CA;10;8;2;10;0;27", este "CA" debe referirse tipo de la planta, es un error de tipeo? o tenemos que tener alguna forma de detectarlo como línea descartada?

**Comment by AndreaVict** [comment]
Holaa, en el enunciado (sección 7) se mencionan las siglas de los diferentes tipos de plantas. Por tanto, a partir de estas siglas válidas debes decidir si descartar o no esa línea. Éxito en la tarea!!

**Comment by JVeloz19** [comment]
Okas, muchas gracias!!
:)
