### ISSUE TITLE
Movimiento de personaje

### ISSUE THREAD

**Issue by kadroguett** [IIC2233/syllabus#360]
En el enunciado dice que el movimiento debe ser pixel por pixel, si cada sprite tiene un tamaño de N*N el personaje debería moverse a lo largo de todo el N por cada pixel si la velocidad de movimiento fuera 1? o el movimiento es sprite por sprite (segunda foto de referencia) y al aumentar la velocidad se avanzarían entre sprites. 
Si fuera el primer caso, es posible asignarle varias coordenadas de un Grid a un mismo label?

![movimiento](https://user-images.githubusercontent.com/31357861/65998776-6695aa80-e472-11e9-8327-595e0bf354b4.png)

![mov](https://user-images.githubusercontent.com/31357861/65999174-42869900-e473-11e9-9e4f-8f445b903434.jpg)

**Comment by tomasalvarez13** [comment]
De que tamaño tiene que ser el personaje?

**Comment by jeschuwirth** [comment]
Hola,

El parámetro VEL_MOVIMIENTO define cuantos **pixeles** se mueve el personaje cada vez que se presiona la tecla. Por esta misma razón recomiendo no tener al personaje dentro de la grilla, sino que la grilla la ocupas para los contenidos del mapa junto con las semillas. El personaje se debería mover por sobre el GridLayout, no te recomiendo que se mueve **en** la Grid.

En cuanto a la preugnta de varias coordenadas de un grid a Qlabel, te recomiendo mirar la issue #357, aún no la responden pero ya fue asignada.

@tomasalvarez13, eso queda a criterio del alumno, te recomiendo que sea (N-5) o (N - K; con K entero), para así poder moverse pasar entre dos rocas que tengan una casilla de pasto entre ellas.

Ojalá hayan quedado claras las explicaciones, cualquier duda sigan comentando en la issue :)

Suerte!

**Comment by kadroguett** [comment]
Muchas gracias !!
