### ISSUE TITLE
genes a considerar en gemelo_genético

### ISSUE THREAD

**Issue by Fhguinez** [IIC2233/Syllabus#360]
El enunciado dice: "Una persona se declara parecida a otra según la cantidad de genes en común que tengan para cada característica"

¿La cantidad de genes en común se calcula incluyendo todos los genes relacionados a dicha característica? ¿o solo los que influyen en dicha característica?

Tomaré como ejemplo los genes de altura (AAG) de Jesús De Nazaret: estos llaman a la cuarta línea de _listas.txt_, donde hay 10 posiciones de genes presentes. ¿Debo revisar que cualquiera de esos 10 genes se repitan en el gemelo_genético? ¿o solo aquellos que sean AGT o ACT (genes que influyen en la altura)?

**Comment by Kitaps** [comment]
Tube una duda parecida en la issue [#331](https://github.com/IIC2233/Syllabus/issues/331)
Aprovecha de preguntar ahí para que sea todo lo respecto a gemelo genético sea respondido en una sola issue ;)

**Comment by Fhguinez** [comment]
Gracias! No había visto esa issue
