### ISSUE TITLE
Forma de ver errores

### ISSUE THREAD

**Issue by miortiz1** [IIC2233/syllabus#360]
Existe alguna forma de ver por que se cae una ventana?

**Comment by jaromero6** [comment]
Hola, en los contenidos de la [semana 9](https://github.com/IIC2233/contenidos/tree/master/semana-09)
se explica una forma que en la mayoría de los casos muestra el error de porque se cae una ventana. 
Espero que te sirva

**Comment by miortiz1** [comment]
Me sigue mostatrando solamente:
Process finished with exit code -1073740791 (0xC0000409) 
y no me imprime ningun error

**Comment by jaromero6** [comment]
Te recomiendo hacer las siguientes cosas:

-  Comprobar en que parte se cae tu ventana, de manera que puedas identificar que código genera este error (pudes colocar prints por ejemplo en disintos métodos, para ver donde es que no se alcanza a ejecutar).
-  Poner especial atención en como redactaste esta parte del código, en el llamado de variables, metodos etc.
- Por experiencia propia, te recomiendo poner especial atención en posibles loops (Si usaste while o recursión en particular) en los que tu programa podría quedar atrapado. También poner atención en el orden que llamas a ciertos métodos, a veces llamarlos antes o después de cierta función puede ocasionar errores 
También te recomiendo buscar en internet dicho error, si bien el código que arroja es distinto, te podrían ayudar.
Finalmente, si es que aún esto no te ayuda a solucionar el problema te recomiendo subir por esta issue parte del código que no está funcionando.

**Comment by LucianoDavico** [comment]
Hola!

Yo estoy ocupando Pycharm como editor de texto y tenía el mismo problema. Busqué en internet y salía que había que deshabilitar la opción `PyQt compatible`, hice eso y me funcionó bien!
