### ISSUE TITLE
Superar las 400 líneas con "líneas de testeo"

### ISSUE THREAD

**Issue by domingo2000** [IIC2233/syllabus#360]
Hola, tengo una duda, si mi archivo tiene mas de 400 lineas, pero las lineas "extras" (osea pasadas las 400 lineas) son solamente lineas de "testeo" osea if __name__ == "__main__" para probar mis clases, asi como se hacia en las actividades, esas lineas extras causan igual el descuento??, pues podría borrarlas simplemente al subir el archivo, pero preferiría dejarla para probrar cosas

**Comment by retamalcito** [comment]
¡Hola @domingo2000!

Usar _líneas de testeo_ es muy útil y es algo que todos hacemos. Sin embargo, si alguno de tus módulos supera las 
400 líneas a causa de ellas, **sí se te aplicará un descuento**. Te recomiendo tenerlas en el archivo a medida que vayas avanzando con tu tarea, y una vez de que estés seguro de que todo funciona correctamente, borrarlas del archivo. Lo importante es que en tu **entrega final** ningún módulo supere las 400 líneas.

¡Saludos! 👋
