### ISSUE TITLE
& antes de texto en GUIS

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#360]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Con "&":
![image](https://user-images.githubusercontent.com/66154723/116169611-1c6abe80-a6d3-11eb-9bd1-19f9e2788299.png)

### Sin "&":
![image](https://user-images.githubusercontent.com/66154723/116169666-3ad0ba00-a6d3-11eb-9bd8-26e583d14b7f.png)

![image](https://user-images.githubusercontent.com/66154723/116169813-8d11db00-a6d3-11eb-85d1-9d05db183b03.png)

#### PS: Estoy corriéndolo en VSCODE. Otra cosa rara que me sucede es que el QLineEdit me aparece pegadisimo al texto, de hecho debería ser "Texto:" pero no se logran ver los dos puntos. No sé si a alguien más le pasa. Claramente sé que debo cambiar la posición en el setGeometry, pero me parece raro que en mi computador se muestre algo distinto a las fotos de ejemplo ((edit: También le sumo el hecho de que no se vea el título de la ventana, a menos que manualmente la agrande))

**Comment by aaossa** [comment]
Hola @fernandosmither , tal como dice el contenido, el uso de `&` es visible solo en ciertas plataformas, aunque al menos en mi versión de Windows 10 no es visible sin antes apretar `ALT`. Sin embargo, sí hay diferentes comportamientos.

Al usar `&` al comienzo del texto de un botón, le estamos pidiendo a PyQt que le avise al sistema operativo que debe asignar una secuencia de teclado al *widget*. Esto permite, en el caso de Windows, que al usar `ALT+p` (en el ejemplo), el foco (*focus*) se traspase al botón (y también activa el evento `clicked`). Puedes comparar ambos comportamientos y probar si efectivamente el uso de esa combinación de teclas hace que el botón destaque de alguna manera. Cuéntame si te funciona y éxito con tu tarea 🙌

**Comment by fernandosmither** [comment]
> Hola @fernandosmither , tal como dice el contenido, el uso de `&` es visible solo en ciertas plataformas, aunque al menos en mi versión de Windows 10 no es visible sin antes apretar `ALT`. Sin embargo, sí hay diferentes comportamientos.
> 
> Al usar `&` al comienzo del texto de un botón, le estamos pidiendo a PyQt que le avise al sistema operativo que debe asignar una secuencia de teclado al _widget_. Esto permite, en el caso de Windows, que al usar `ALT+p` (en el ejemplo), el foco (_focus_) se traspase al botón (y también activa el evento `clicked`). Puedes comparar ambos comportamientos y probar si efectivamente el uso de esa combinación de teclas hace que el botón destaque de alguna manera. Cuéntame si te funciona y éxito con tu tarea 🙌

Wow! qué específico, pero sí, me pasa exactamente lo mismo. Gracias!
