### ISSUE TITLE
Duda respecto a argumentos de funciones.

### ISSUE THREAD

**Issue by Minjor** [IIC2233/Syllabus#360]
Mis funciones pueden recibir *args en vez de lo que sale en el enunciado?

**Comment by Hernan4444** [comment]
@Minjor si puedes mientras cumplas todo lo solicitado en la tarea (manejo de errores por input).

Saludos!!

**Comment by Minjor** [comment]
otra pregunta que me surgió ahora, en una consulta cuantas consultas anidadas pueden haber? por ejemplo en el enunciado sale "['filtrar','x', '>', ['PROM',['extraer columna', 'notas avanzada', 'Tarea 1'] ] ]" ahí veo 3 consultas (2 consultas dentro de 1), extraer columna y PROM anidadas en filtrar.

**Comment by FernandoPieressa** [comment]
@Minjor Puede haber cualquier cantidad de consultas anidadas, por lo tanto te recomiendo tener un código genérico que sirva para cualquier cantidad y no limitando

Saludos!
