### ISSUE TITLE
Duda con tests de votos_validos

### ISSUE THREAD

**Issue by AlanGoldsmith25** [IIC2233/Syllabus#360]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Mi duda es que me funcionan los tests del 0 al 4 pero no del 5-7 en la funcion de votos_validos, y segun yo el codigo esta correcto. No habra algun error en los tests o las edades de los animales en los archivos?

**Comment by ClemoAcevedo** [comment]
Hola @AlanGoldsmith25, hoy en la noche habrá una actualización a los archivos. Cuando estén, prueba con esos, si te sigue sin funcionar avisa por acá.

**Comment by SebaPassi** [comment]
A mi también me fallan los mismos test cases. Lo acabo de probar con los nuevos tests. ¿Puede que haya un error?

Muchas gracias!

**Comment by JaimeMatas** [comment]
A mi también me pasa exactamente lo mismo. Los 3 últimos tests case me fallan (5, 6 y 7). Actualicé todo con los cambios que hicieron ayer y sigue igual. ¿Podrían revisar estos test case para saber si hay algún tipo de error?

Muchas Gracias

**Comment by faresdababneh** [comment]
Hola, me pasa exactamente lo mismo

**Comment by AlanGoldsmith25** [comment]
Hola, lo acabo de volver a probar con los mismo archivos y siguen fallando los mismos tests, por si podrian revisar los archivos o el test solution de nuevo porfa!

**Comment by SebaPassi** [comment]
Holaaaa

¿Alguna novedad sobre los test cases de esta función?

El test 5, 6 y 7 siguen sin funcionarme.

Saludos y muchas gracias!

**Comment by mpiavf** [comment]
Hola, actualizamos los tests con lo detectado en esta issue y otras más. Pueden revisar la issue creada en #444 para más detalle. 
Saludos!

**Comment by navila1** [comment]
Hola! A mi me sigue pasando lo mismo, seguirá habiendo un error en los tests 5, 6 y 7?? o yo estoy mal?
