### ISSUE TITLE
Problema en cargar los sprites en la ventana de juego

### ISSUE THREAD

**Issue by ling2333333** [IIC2233/Syllabus#360]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

me surgió un problema en colocar los elemento en el tablero. Puse bien los cuadros de pared y fondo, pero luego usando el mismo formato de código en colocar los elemento como conejo, los cañones y las burbujas de poderes, se apareció esto en la ventana:
<img width="432" alt="image" src="https://github.com/IIC2233/Syllabus/assets/107127861/79e852ed-a1a9-412f-819d-1c446faca6c3">
<img width="194" alt="image" src="https://github.com/IIC2233/Syllabus/assets/107127861/0a5f1265-35a3-4bdf-b51d-3b228e341a7c">
y con el tablero se nota que los elemento está en una posición correcta, solo que la imagen no se aparece. Mi código está subido en mi repositorio, no sé si se pueda revisar un poco para saber por qué aparece esto.
Gracias!!

**Comment by vicente999** [comment]
Hola! Eso ocurre porque el sprite del conejo (u otro elemento) está detras del fondo rosado, lo que te recomendaría es rellenar el tablero con baldosas cafés todo el mapa del juego e ir superponendo las baldosas grises de los muros, de esta forma tienes el codigo listo para superponer el sprite del conejo, y así solo haces un manejo de coordenadas. Pero en caso de que tengas el codigo ya muy avanzado como para hacer eso, revisa bien que el conejo no quede detrás del fondo rosado.
