### ISSUE TITLE
Valores fortalezas y debilidades

### ISSUE THREAD

**Issue by domingo2000** [IIC2233/syllabus#361]
Hola una pregunta, cuando en las delegaciones especificas dice que las fortalezas y debilidades varian entre 2 parametros
![image](https://user-images.githubusercontent.com/40220174/92337778-427b1a00-f082-11ea-8da4-840a04641698.png)
esto significa solamente que empieza entre esos dos parametros?, o que cuando estos van cambiando deben estar tambien en esos rangos, en vez de [0, 1] como dice en la delegacion general?

**Comment by jitorcas** [comment]
Hola! @domingo2000 

Significa que cuando se instancia una Delegación, sus fortalezas y debilidades deben ser un valor aleatorio entre esos intervalos. A lo largo del juego pueden variar y no es necesario que sigan perteneciendo a ese rango. 

Mucho éxito! 🥇

**Comment by Mamunoz42** [comment]
Entonces eso significa que para instanciar el primer valor debe cumplir el rango de cada delegación y después este puede variar en el rango de [0, 1] (Este cambiaría por el parámetro que le ingresen)?

**Comment by jitorcas** [comment]
@Mamunoz42 

Así es!
