### ISSUE TITLE
Mapa + Layouts

### ISSUE THREAD

**Issue by cchauriye** [IIC2233/syllabus#361]
Hola!
Tengo una duda respecto al uso de layouts. Me gustaría usar layouts para "dividir" la ventana de juego correctamente. El tema es que el mapa lo hice con un layout y no sirve para mover el personaje, entonces tendré que hacerlo de alguna forma "absoluta". ¿Hay alguna forma de insertar el mapa "completo" dentro de un QHBoxlayout o algo así?

Gracias

**Comment by DCCollao** [comment]
Hola!

Uno de los principales objetivos de la tarea es que este tipo de dudas las puedas consultar por ti mismo viendo la documentación de PyQt5 (o Qt5), por lo que no te podemos responder directamente si existe o no una forma de hacerlo :(

Mucho éxito para la tarea!
