### ISSUE TITLE
no me funciona hide() en QLineEdit()

### ISSUE THREAD

**Issue by teverde** [IIC2233/syllabus#361]
Intento esconder tanto QLabel, QLineEdit() y un QPushButton al iniciar sesión para dejar solo el botón de cerrar sesión, pero sucede que no se van, sino que quedan como una sombra (solo la imagen, no es funcional) detrás del botón de cerrar sesión que hago aparecer.
Sin embargo cuando cambio el tamaño de la pantalla con el mouse, aparece como debiera.
![Captura de Pantalla 2019-05-22 a la(s) 20 42 09](https://user-images.githubusercontent.com/48270797/58217828-8c47c180-7cd2-11e9-97de-addb62608e0b.png)
![Captura de Pantalla 2019-05-22 a la(s) 20 42 36](https://user-images.githubusercontent.com/48270797/58217832-8f42b200-7cd2-11e9-9233-83d380030f8b.png)

**Comment by gatochico** [comment]
Hola! Puedes subir tu última versión del código a tu repositorio para darte una respuesta más concreta?
Por lo que explicas, podría ser que en vez de ocultar los botones, sólo los estás deshabilitando y es por eso que siguen presentes?
