### ISSUE TITLE
Método __str__ y presentarse de jardín.

### ISSUE THREAD

**Issue by Dielastros** [IIC2233/Syllabus#361]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo 2 dudas respecto al método __str__ del jardín y las ocasiones en las que debemos presentarnos.

La primera, ¿Es absolutamente necesario que el método __str__ del jardín contenga el inventario y sus contenidos? (Aparece como una instrucción directa en la sección 4.1). Hay numerosas ocasiones en el código que, según yo, queda mejor solo imprimir el jardín y sus contenidos actuales, por lo que imprimir el inventario quedaría mejor como una función a parte, implementada en casos específicos. 

Lo segundo, en la sección 5.5 de presentación, además de todos los datos del jardín, se pide que se muestre en pantalla el NUMERO de plantas congeladas. ¿Es esto realmente necesario? Se encuentra implícito en el propio mapa y ni siquiera el ejemplo propuesto lo aplica.

Muchas gracias por la atención.

**Comment by augustayanez** [comment]
Como los que comentas son instrucciones y requerimientos, es necesario implementarlos en tu código. Por otra parte, los ejemplos del enunciado son para darte una idea, pero puedes hacerlo como quieras mientras cumplas con lo pedido. Saludos!
