### ISSUE TITLE
Problemas de comunicación entre servidor y cliente

### ISSUE THREAD

**Issue by elisahonorato** [IIC2233/Syllabus#361]
* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/326).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/325).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, estoy teniendo problemas para recibir mensajes desde el servidor. Si bien, al inicio del juego, me los recibe perfectamente, cuando intento comunicarle desde el cliente, las cartas que seleccioné, no me recibe el comando. En otras palabras, sólo me recibe mensajes al principio, a pesar de que no parece desconectarse el socket. Por qué podrá estar pasando eso? Muchas gracias

**Comment by Hernan4444** [comment]
Hola @elisahonorato 

Revisando el último código que había en tu repo junto con la descripción del problema que indicas, el problema está en la función `escuchar_cliente` donde el código solo se ejecuta 1 vez, pero tu necesitas que esté constantemente escuchando los mensajes del cliente. Ahí falta agregar algo que permita que una vez escuchado un mensaje y procesado, vuelva a ponerse a escuchar el siguiente mensaje que llegue

Saludosヾ(＾-＾)ノ

**Comment by elisahonorato** [comment]
Muchísimas Gracias!
