### ISSUE TITLE
Problemas con el formulario de recorrección

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#361]
Hola! 
Estaba intentando usar el form de recorrección y me aparece el siguiente mensaje:

"El form de recorreccion requiere que te logees con tu correo UC. Tu correo será cruzado con tu nombre y tu usuario de GitHub. Si algo no coincide la recorrección será ignorada, por lo que te pedimos que tengas cuidado con esto"

Sin embargo, una vez me logie me seguía indicando lo mismo (lo intenté varias veces), si pudieran adjuntar el link por acá lo agradeceria

**Comment by tomasrivera** [comment]
Hola, el mensaje que indicas no es del formulario, por lo que es normal que se mantenga una vez que ingresaste con tu cuenta.

Preocúpate de que tu **mail UC** salga correctamente en el formulario (Tu dirección de correo electrónico (mail@uc.cl) se registrará cuando envíes este formulario.) y de ingresar tu **usuario de GitHub** de manera correcta. Saludos.

**Comment by tomasrivera** [comment]
Si no te sale el formulario es porque no estás conectado a una cuenta de Google (correo uc), te recomiendo ir a Google y conectarte desde ahí.

**Comment by santilaguna** [comment]
Si estoy conectado y sigue sin funcionar...

**Comment by Hernan4444** [comment]
@santilaguna a veces pasa que si tienes multiples cuentas en google, el form no te toma la UC sino que otra. Intenta cerrar todas las cuentas que tengas y solo hacer login con la UC
