### ISSUE TITLE
ASI COEF - ASI

### ISSUE THREAD

**Issue by monicabelen** [IIC2233/Syllabus#361]
¿A qué se refieren con las medidas ASI y ASI-COEF?

**Comment by Dunkan1** [comment]
te van a decir que ya lo preguntaron en otra issue, pero eso se les paso a los ayudantes asi que debes ignorarlo
lo que la funcion recive son estos
("LEN", "PROM", "DESV", "MEDIAN", "VAR")

**Comment by monicabelen** [comment]
o sea VAR-COEF y KUR-COEF tampoco van? :o

**Comment by akaminetzkyp** [comment]
Nop!

**Comment by monicabelen** [comment]
Perfecto, gracias!!

**Comment by Hernan4444** [comment]
#309 
Saludos!!
