### ISSUE TITLE
Uso de variables obtenidas a partir de una lista

### ISSUE THREAD

**Issue by tomasvasquezp** [IIC2233/Syllabus#361]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! tengo una duda, se pueden crear variables a partir de una lista en consultas? es decir, si tengo una listas de listas, puedo crear una variable que se llame variable1 = lista[0][0] para luego retornarla o usarla en otra cosa? Igualmente hice push de mi tarea por si la quieren revisar, porque hice algo asi en hallar_region y quiero ver si esta bien lo que hice.

Gracias!

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Julius9** [comment]
Hola! mientras la lista de lista se haya creado de forma licita (por compresión por ejemplo) no existe problema con que hagas slicing para obtener el valor de una variable :)
