### ISSUE TITLE
Error enunciado plantas.txt

### ISSUE THREAD

**Issue by herrerac1** [IIC2233/Syllabus#362]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! En la seccion 7.2 del enunciado de la tarea, en el cuadro 3 de plantas.txt dice que la resistencia deberia ser un int entre 0 y 40, sin embargo, despues dice que una resistencia erronea sera un int fuera del rango entre 0 y 10, lo cual supongo que es un error. Entonces, queria saber cual es el rango verdadero que tengo que utilizar?

**Comment by augustayanez** [comment]
Efectivamente, la parte del enunciado que dice que "Por ejemplo, una resistencia errónea será siempre un int pero fuera del rango entre 0 y 10." en el archivo plantas.txt tiene un error, ya que la resistencia siempre será un int entre 0 y 40 como se define en las características básicas de las plantas (sección 4.2). Gracias por notar el error para poder corregirlo en el enunciado!

![image](https://github.com/user-attachments/assets/7be8a3d8-6d9c-4296-ab26-cd912735744e)

**Comment by augustayanez** [comment]
Debido al error del enunciado, se aceptarán cualquiera estos dos rangos, puedes hacer que la resistencia sea un int entre 0 y 40 o un int entre 0 y 10. Saludos!
