### ISSUE TITLE
Excepciones y errores en la base de datos

### ISSUE THREAD

**Issue by emeiese** [IIC2233/Syllabus#362]
Hola! Estaba creando la función filter_by_date, y, por ejemplo, hay una lína en movies.csv que dice "3, "Forrest gum", 8.6/10, 41%, 84/100, $177.413.655, N/A". Claramente el ultimo atributo, que sería la fecha, no es entero, por lo que al leer el archivo y tratar de filtrar, me tira un error (porque hago int("N/A") < date).
Respecto a esto, en la sección 2.4 sale que hay que crear una excepcion llamada MovieErrors para el caso. 

0. No entiendo bien a que se refieren con lo siguiente: "Debes recordar que se está **_realizando_ una librería**; por ende, una librería levanta excepciones mientras que los usuarios que utilizan la librería son los que capturan errores" 

1.  En este caso, no podré filtrar bien la base de datos hasta que ese "N/A" ya no exista. La cosa es que en esta parte del enunciado no dice nada sobre "corregir" los errores, sino que sólo levantar la excepcion en el caso correspondiente. ¿Entendí bien? Porque me parece raro ajaja.  En el fondo, solo hay que "atrapar" la excepcion pero no hacer nada al respecto? Porque si ese es el caso, nunca podré filtrar bien la base de datos a menos (?) ajajaj atraparé para siempre la excepción 

2. En esta actividad no se evalúan decoradores? No vi nada al respecto luego de leer el enunciado (o se me pasó). De todas maneras, se pueden usar cierto?  

3. Aún no entiendo muy bien el sistema de consultas. Esos ejemplos que salen en la sección 2.3, por ejemplo: ["filter_by_date", ["load_database"], 2015, True] ...esa consulta se le entrega a quien? O quién me la retorna?

**Comment by Hernan4444** [comment]
Hola,
0) Ese recordatorio es para que **no hagas** `try/except` de cualquier error que ocurra en tu librería para asegurar el funcionamiento, si algo no corresponde a lo esperado, se debe levantar alguna de las excepciones especificadas.

1) Precisamente, toda consulta que implique filtrar por fecha no se podrá realizar, a no ser que filtre primero por otra cosa para que esa película ya no esté y luego filtre por fecha.

2) Si se puede utilizar.

3) Esas consultas a ti te llegaran desde la interfaz y tu tendrás que procesarlas para retornar los datos pedidos según cada consulta.

Saludos ✌️

**Comment by Hernan4444** [comment]
Lo que dije en 1 es un ejemplo de lo que un usuario podría intentar hacer con tu librería para evitar que se genere una excepción.

**Comment by Hernan4444** [comment]
Lo que dije en 1 es un ejemplo de lo que un usuario podría intentar hacer con tu librería para evitar que se genere una excepción.

**Comment by Hernan4444** [comment]
@emeiese la opción es A

saludos :v:

**Comment by mblejeune** [comment]
en este caso, se tendrian que hacer dos opciones para hacer filter by date, una en que el usuario elige filtrar los N/A y que estos no se consideren, y otra en que si se consideren y por ende tiraria un error(si es que utilizan una base de datos que contenga N/A para date, pero esta opcion de si el usuario desea filtrar el N/A donde esta? porque en la consulta como funcion no tiene parametro si desea filtrar los datos N/A o no, y a travez de la interfaz solo se entregan consultas definidas con parametros ya, entonces nunca se le daria al usuario la opcion de que no antes de realizar filter by date elimine los datos N/A, que se hace en este caso? gracias!

**Comment by Hernan4444** [comment]
Creo que hay un **GRAN** malentendido. La consulta **solo filtra por fecha y si hay un N/A tira error**, eso es todo.

Ahora ¿que puede hacer el usuario para filtrar por fecha con la base de datos actual? **él** tendrá que hacer una consulta para primero sacar ese dato malo y esa consulta anidarla a una de filter_by_date.


Ejemplo:  `["filter_by_date", ["popular_movies", ["load_database"], 1, 20], 2015, True]`

**Tal vez**, repito, **tal vez** con una consulta así, `["popular_movies", ["load_database"], 1, 20]` nos dará una base de datos que no tenga la película con N/A, de este modo ahora `filter_by_date` si logrará ser ejecutada sin lanzar Error.

Saludos ✌️

**Comment by Regenschrim** [comment]
Entiendo que si estamos iterando y encontramos un "N/A" debemos levantar un error, el problema es que levantar un error detiene la iteración. ¿Es posible que en el manejo de las excepciones se use un for? Me pasa que al intentar entregar una consulta y manejar el error, el programa deja de correr tras encontrar el primer error :(

**Comment by Hernan4444** [comment]
@Regenschrim recuerda que puedes utilizar un `for_each` para realizar lo que quieres.

**Comment by Hernan4444** [comment]
Complementando, revisen #371

Saludos ✌️
