### ISSUE TITLE
Pregunta sobre QThreads

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus#362]
Hola, tengo una duda sobre los QThreads. Pregunte hace unos dias en stackoverflow y me pidieron el contexto del problema, el experto en si vio que tenia una clase QThread de los enemigos y la pregunta no tenia que ver con eso, pero me dijo que era muy mala idea usar QThreads en la mayoria de los casos, ya que se usaban para procesos intensivos y que mi programa estaria trabajando el doble.  Entonces solo me entro la duda de si mas o menos estoy bien encaminado con la idea de ponerlos como enemigos, ya que aunque lo que el experto me dijo sea cierto, tambien se que se evalua en la tarea, por lo tanto voy a usarlo igual.

En mi caso, puedo lanzar 800+ enemigos y el programa no se me pega absolutamente en nada, ni tiene bugs, pero podria eso depender del procesador y no trabajar de la misma forma en los demas computadores, por lo mismo quisiera saber si existiria una mejor forma de hacer esto o estoy mas o menos bien encaminado.

Puede ser que la pregunta no corresponda, ya que estoy mas o menos preguntando una sugerencia que deberia verla yo. En tal caso, solo borrar o cerrar la issue jajajajaja.

**Comment by roberto009** [comment]
Hola!
Puedes modelar los enemigos de distintas formas y tu debes elegir la que mas te convenga.
Modelar con `QThreads` puede que no sea lo más eficiente, pero es viable 😉
En el contexto de está tarea lo importante no es el uso de memoria ni la eficiencia, sino que sean capaces de desarrollar el programa que les pedimos y aprendan a utilizar `PtQt5`.
Éxito con la tarea 💪

**Comment by YoGandalf** [comment]
O sea no es necesario usar QThreads en ninguna parte? O solo en esa parte no es necesario

**Comment by Hernan4444** [comment]
Hola, 

No se está diciendo eso, sino que no se preocuparan por tal situación de que si bien QThreads dicen que no es eficiente para este caso, no buscamos eso.

Saludos :v:
