### ISSUE TITLE
nombre inventario template

### ISSUE THREAD

**Issue by JosefaPaz** [IIC2233/syllabus#362]
Hola! 
es correcto que el nombre del sprite de inventario sea "invetary_template" en vez de "inventary_template" ? gracias!

**Comment by jeschuwirth** [comment]
Hola @JosefaPaz ,

Como no se sube la carpeta de sprites, te recomiendo no cambiar el nombre de los archivos que les entregamos, ya que el ayudante tendrá que cambiarlos también en su ordenardor.

Si ese template no vino en la carpeta sprites (creo que no), entonces lo tienes que subir a tu repo junto con la tarea y no hay problema con cambiarle el nombre :)

Suerte!
