### ISSUE TITLE
T01 Orden deportistas.cvs

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#362]
Hola! puedo asumir que el archivo deportistas.cvs va a estar en ese orden siempre?
o me pueden cambiar el orden de flexibilidad por dinero .. etc

**Comment by itmunoz** [comment]
Hola! El orden que aparecen los datos será completamente aleatorio, tanto en deportistas.csv como en delegaciones.csv.
Es por eso que estos archivos se ven especialmente desordenados.
