### ISSUE TITLE
QTimer: Movimiento en paralelo

### ISSUE THREAD

**Issue by ggmirandac** [IIC2233/Syllabus#362]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola,

No sé si lo que tengo es una duda o un error. Pero estoy siguiendo la estructura presentada en la experiencia número 4 para generar movimientos de varias entidades al mismo tiempo. Para esto creo para cada una de las entidades (modeladas como una subclase de QObject) un QTimer propio, el cual se conecta con la función de movimiento de la entidad, función la cual al moverse envia una señal al frontend para cambiar de posición del objeto, cosa que tambien activa unos QPropertyAnimation objects para animar el movimiento. 
Al iniciar el juego pongo inicio a los QTimer de cada uno de las entidades (.start()) en el backend. Al moverse, deberían enviar una señal al frontend para que se muevan los QLabels, pero cuando lo corro pareciera que en vez de correrse en Threads diferentes se corrieran en el main thread, debido a que cuando ocurre el movimiento de los objetos solamentente uno de ellos se mueve.

Lo que me parece extraño es que seguí al pie de la letra lo que se muestra en la experiencia 4, pero no logro hacer que ocurra el movimiento paralelo de las entidades.

Si me pudieran ayudar estaría muy agradecide :3 

Saludos

**Comment by Hernan4444** [comment]
Hola @ggmirandac 

Revisé tu código, antes de todo, ojo con las cosas que estás ignorando.... tu código ocupa "logo_rc" y "fondo_inicio_rc" los cuales no están subidos en tu repositorio porque están dentro de `sprite`. Recomiendo (1) moverlo a una carpeta que no esté siendo ignorada y (2) tener ojo que ese código tambien cumpla con las reglas de PEP8.

Respecto al problema, lo que pasa es que en frontend estás haciendo tanto para fantasma como luigi un código así: `self.animation = QPropertyAnimation(...)`. Esto hace que el último personaje en enviar una señal de movimiento sobreescriba ese atributo, y el personaje anterior que se estaba moviendo animadamente pierda su animación. Dado que QPropertyAnimation solo funciona mientras exista alguna referencia de ese objeto en python (ya sea guardandolo en un atributo, una lista, un diccionario, etc). Cuando se sobrescribe, es una forma de eliminar ese objeto y con ello, la animación que se estaba ejecutando. Lo que debes hacer, es asegurarte de que la animación no sea sobreescrita cuando otro personaje se vaya a mover.

**Comment by ggmirandac** [comment]
Hola,

Muchas gracias por las recomendaciones. Pero me queda una duda, pq para los casos en los que tengo varias entidades que se mueven al mismo tiempo, como los fantasmas que pueden moverse al mismo tiempo, debo crear una variable diferente para cada uno de las entidades. Sumado a esto, para que la animación funcione, esta debe ser una variable de clase, es decir, con self.{varible}. Intente utilizar un sistema de asignación de variables dinámico mediante el comando exec() pero buscando en stackoverflow me dice que no es la mejor forma [stack_linkl](https://stackoverflow.com/questions/73038909/file-string-line-1-in-lambda-nameerror-name-self-is-not-defined). Y me causa aquí duda, porque de hecho defini una variable para controlar la animación y luego el comando exec() no al reconoce, a pesar de ser definida antes, onda es lo siguiente:

controlador = Control()
exec(controlador.funcion1())

y me sale el error:
Traceback (most recent call last):
  File "<string>", line 1, in <lambda>
NameError: name 'controller' is not defined

Entonces no se como hacerlo, me podría dar algún tip de como hacer esto. Debido a que intente poner las variables self.animacion en una lista y ejecutarlas parecido a 
for animacion in animaciones
    animacion.start()

Y tampoco funcionaba.

Cualquier recomendacion es bienvenida

**Comment by tomastrivino** [comment]
@ggmirandac #290 si usas exec() <la función built in de python> tienes un 1.0 D;

**Comment by ggmirandac** [comment]
ª, no me acordaba de eso. Gracias por la advertencia

**Comment by Hernan4444** [comment]
Hola @ggmirandac 

> Sumado a esto, para que la animación funcione, esta debe ser una variable de clase, es decir, con self.{varible}

Eso no es totalmente correcto, para que funcione lo importante es que la animación esté guardada en alguna parte, ya sea una variable (self.{variable}) o en alguna estructura de datos que es un atributo.

Tal vez cuando hiciste lo de la lista, intentaste hacerle `start` a alguna animación que ya le habías hecho `start` antes y eso generaba error. o talvez la lista no era guardada despues, así que si bien pusiste todo en una lista, luego la lista no quedaba en algun atributo, asi que se perdía.

Si revisas la experiencia 4, ahí teníamos un diccionario con todos los QLabel de meteriotos creados, esto justamente es para guardar una referencia al objeto pyqt en el código, pero no como self.meteorio, sino como un diccoinario con toooodos ellos. Sería similar en este caso.

Saludosヾ(＾-＾)ノ

**Comment by ggmirandac** [comment]
Hola @Hernan4444 

Si, es que dije eso, porque intente ejecutar la animación solamente son la variable como sin el self. y no me corrió.
Pero ahora intento hacer lo mismo, onda guardando el objeto QPropertyAnimation en una lista y tratar de correr cada uno de los elementos de la lista y la animación no corre :(((
Saludos y gracias por la ayuda

**Comment by Hernan4444** [comment]
Hola @ggmirandac 

Lo que ocurre, es que si bien guardaste las cosas en una lista, esa lista es una variable local de ese método. Esto significa que una vez acaba el método, esa lista se pierde, junto con todo lo que tenga adentro. Esto provoca que la animación no se vea, puesto que el objeto "Animación" fue eliminado junto con la lista.

Si verificas la experiencia 4, creamos en el `__init__` un diccionario que guarda todos los QLabel, el cual es `self.labels_meteorito` y luego lo usamos dentro del método para crear meteoritos. Del mismo modo, en la sala de ayuda de la T2, hicimos otro diccionario para guardar todos los `QPixmaps` y luego este sea utilizado en otros métodos. En ambos casos, los pasos fueron (1) crear un atributo que es una estructura de datos y (2) utilizar ese atributo o llenarlo con información en los otros métodos. Esto hace que la información quede guardada para siempre en ese diccionario y no se pierda una vez finalice el método.

Revisé tu código, hice los cambios para ser consistente con lo mencionado anteriormente y pude ver cómo el fantasma se movía al mismo tiempo que movía, con el teclado, a Luigi. Por lo cual, solo es un tema de que no está siendo guardado como corresponde la animación en tu clase.

Saludosヾ(＾-＾)ノ

**Comment by ggmirandac** [comment]
Si

Ya se también que es, es que cuando muevo los fantasmas, se mueven independientemente. Lo que hace que se sobreescriba la función. Así que debo crear una función que se encargue de moverlos todos de una y así poder hacer que lo que recomendaba de la lista. 

Muchas gracias por su ayuda, me salvo :3 

Gracias
