### ISSUE TITLE
reviews.csv, palabras unidas y len(reviews)

### ISSUE THREAD

**Issue by Bipavez** [IIC2233/Syllabus#363]
Hola!
Resulta que en en archivo _reviews.csv_; en algunas líneas hay palabras unidas, por ejemplo:

- 7, "Keanu Reeves going rampantbecause why not?!"

¿En este caso tenemos que tomar en cuenta este rampantbecause cómo (rampant, because)?

Otra pregunta;
¿En el tercer requierimiento para identificar al bot, se nos piden la cantidad de caracteres entre [6,84] o la cantidad de palabras entre [6, 84]? 
¿Si es última opción, la mayoría de las películas se quedarían sin reviews?
Edit: pense que era _req1_ **or** _req2_ ... y no _req1_ **and** _req2_ ....

**Comment by rihanuch** [comment]
¡Hola @Bipavez !

1. No te preocupes por separarlas, el punto es ese mismo, los que crearon las palabras fueron humanos y no bots 🤖, por lo que tienes que dejar el comentario tal cual está
2. Te lo respondo cuanto antes posible (dentro del día voy a actualizar el comentario y te aviso 😬)

¡Saludos y éxito!🍀

**Comment by Bipavez** [comment]
**¡Gracias!**

**Comment by rihanuch** [comment]
@Bipavez ,

Vamos a revisar la base de datos y veremos si pasa, _pero_ independiente de si es así o no, el funcionamiento del programa **no debería cambiar** por ser así o no 😬

¡Confía en tu código ✅ o haz pruebas a mano!

¡'Saludos y éxito! 🍀

**Comment by Bipavez** [comment]
Me equivoqué en la interpretación del enuciado, en el edit de mi primer comentario señalo mi error. 
_El número de reviews sí es válido y cada pelicula tiene al menos una review_ (según lo que vi)
¡Muchas gracias!

**Comment by rihanuch** [comment]
¡Perfecto! 🆒

**Comment by jminostroza** [comment]
"Isabelle...Huppert...yaaaaasssss...queen..." se considera como una sola palabra?

**Comment by norman123123** [comment]
Estoy usando re.compile('<.*?>') para sacar las etiquetas html, lo malo es que despues de limpiar todo me cambia los apóstrofes de las palabras en inglés, por ejemplo:

Huppert's pasa a ser Huppert\'s 

Esto da lo mismo para la tarea? porque el archivo inicial sin limpiar queda con los " 's" correctos pero luego de limpiar (no se porque) queda con los "\'s". Alguien sabe arreglarlo? o filo no ma?

PD: estoy baneado de stackoverflow hasta junio.

**Comment by IchottMano** [comment]
@jminostroza Hola!

Al tener puntuación, se consideran como palabras separadas.

Saludos!

**Comment by Drpinto1** [comment]
Entonces cuáles caracteres deberíamos interpretar como separación de palabras?
, ; . y espacios, cualquier caracter alfanumérico o alguna otra combinación?
