### ISSUE TITLE
duda properties/polimorfismo/abstractmethod

### ISSUE THREAD

**Issue by jervaal** [IIC2233/syllabus#363]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! tengo una duda sobre el ítem de incluir properties, abstractmethods y polimorfismo

si no utilicé ninguna vez properties (@propertie ... ), pero si ocupe abstractmethod (@abstractmethod .... ), ¿se le considera a esto como uso de properties?.

Además, si defino un abstractmethod, al hacerle overwriting (definir nuevamente esta función según lo necesario) a este abstractmethod, ¿Se considera que se incluyó el uso de polimorfismo?

De antemano muchas gracias!

**Comment by tqmbanados** [comment]
Hola! 
1) @abstractmethod no es una property, es un decorador! El significado de eso lo verán más adelante. Lo importante es que **no** es válido para el uso de properties. El enunciado ofrece muchas buenas oportunidades para usar properties, no tienes que quemarte la cabeza buscándolas! 
2) En tu segunda pregunta no lo tengo 100% claro, pero me parece que sí, pues técnicamente eso **sí** es una forma de overriding. Voy a averiguar para tenerlo más claro y te comento!

**Comment by tqmbanados** [comment]
Hola de nuevo, te aviso que no existe en la distribución de puntajes el uso obligatorio de overriding! Entonces si usas clases y métodos abstractos correctamente no deberías tener ningún problema :)
