### ISSUE TITLE
Uso de código externo

### ISSUE THREAD

**Issue by eliasbruchfeld** [IIC2233/syllabus#363]
Hola! en la AS01 venia un código para cargar los datos de un archivo .csv. Puedo copiarlo para la tarea 1? obviamente indicandolo en el readme

**Comment by jitorcas** [comment]
Hola! @eliasbruchfeld 

Si! Puedes utilizar recursos externos, pero **debes** citarlos en tu README. En caso que se esté utilizando una librería externa recuerda revisar la issue #326 para confirmar si se puede utilizar. 

Mucho éxito! 🥇
