### ISSUE TITLE
Error en la pauta? 

### ISSUE THREAD

**Issue by benjavicente** [IIC2233/syllabus#363]
En la [pauta](https://docs.google.com/spreadsheets/d/15SDoSSz9VINHPLQwmdgAIT_0-A2eDpvHsk3cTLGfXG0), en la sección de _Pasar al día siguiente_ en _Acciones_ estan los siguientes items:

- Se aplican correctamente las habilidades especiales de cada DCCriatura.
- **Se actualiza correctamente el estado de salud de las DCCriaturas.**
- Se actualiza el estado de hambre de cada DCCriatura dependiendo del tiempo que lleva sin comer.
- **Se actualiza correctamente el estado de salud de las DCCriaturas.**
- Se actualiza correctamente la cantidad de DCCriaturas escapadas.
- Se actualiza correctamente el nivel de aprobación y el estado de la licencia del Magizoólogo.
- Se paga correctamente la cantidad de sickles al Magizoólogo y se actualiza la cantidad de sickles que tiene.
- La fiscalización se realiza correctamente: se calculan multas según los eventos de DCCriaturas.

Como se ve, los items 2 y 4 son los mismos. Será que uno de ellos se refiere a los _Puntos de salud actual_ y otro a el _Estado de salud_?

Aprovecho también de preguntar, es este el orden en el que tienen que ocurrir los eventos al pasar de día?

Gracias por adelantado!

**Comment by Dnpoblete** [comment]
Hola @benjavicente, gracias por notificarnos el error, lo arreglaremos lo antes posible 😄
