### ISSUE TITLE
resultados.txt

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#363]
los resultados entregados son correctos?

**Comment by Hernan4444** [comment]
@rihanuch sip 👍. Pero como existe la posibilidad de que la solución tenga algún error (tuvo que ser programada en menos de 24 horas 😞), te sugiero publicar en esta issue el resultado de alguna consulta que no te coincida con el puesto en `resultados.txt` y si a más personas le dá lo mismo que tu, verificaré cada paso de la solución para determinar el error, pero por el momento esos resultados son los correctos.

Saludos ✌️

**Comment by rihanuch** [comment]
Oh que duro! La vida de los programadores ☹️. Gracias!

**Comment by BeaGaete** [comment]
Hola! A mi también me da en algunas consultas otra cosa distinta a los que dice resultados.txt. En la 2 solo me da Sterling Archer y en la 3 además de Hakalamax Atalapastruka se agregan otros, pero en todo lo de más me da lo correcto. Sería bueno que verificaran la solución si es que tiene un error. Gracias!
![captura de pantalla 2017-09-28 a la s 10 08 13](https://user-images.githubusercontent.com/26144496/30968156-c05507e4-a434-11e7-870e-c4a6ee35bfb1.png)

**Comment by Hernan4444** [comment]
@BeaGaete es posible que mi digas todas las características de Staling Archer y de Marcelo Lagos, puesto que efectivamente la consulta me dá lo mismo que tu pero en la consulta 3 me sigue dando lo mismo que antes 👀.

**Comment by NoemiCC** [comment]
Hola, a mi la consulta 4 me sale incorrecta. Me da que los nombres que salen son de grado 2 (en vez de n).

**Comment by Hernan4444** [comment]
@NoemiCC si revisas las restricciones para grado de pariente, las restricciones van  disminuyendo a medida que aumenta el grado. Por lo que es demasiado probable que un pariente grado 1 tambien sea grado 2 o grado n. Por ejemplo: yo ("Hernan Valdivieso") soy pariente grado 0 con "Marcelo Lagos"  , esto implica que si buscamos mis parientes grado 1, tambien aparecerá "Marcelo Lagos" y eso no está incorrecto.

Resumen: Si con la busqueda de grado n aparecen esas 2 personas, estás bien 👍 
Saludos ✌️

**Comment by BeaGaete** [comment]
mis namedtuples de Marcelo Lagos y Hakalamax Atalapastruka son:

humano(nombre_apellido='Marcelo Lagos', altura=1.4, ojos='cafes', pelo='negro', piel='blanco', nariz='aguilen_a', pies=43.33333333333333, vello=['axila'], guata='atleta', vision=['miopia'])

humano(nombre_apellido='Hakalamax Atalapastruka', altura=2.1, ojos='cafes', pelo='negro', piel='blanco', nariz='aguilen_a', pies=45.666666666666664, vello=['axila', 'espalda'], guata='man_ana empiezo la dieta', vision=['daltonismo', 'miopia'])

**Comment by Hernan4444** [comment]
@BeaGaete recuerda la condicion de vision, ambos deben tener los mismos problemas de vision y en ese caso Marcelo lagos no tiene daltonismo.

**Comment by BeaGaete** [comment]
Okis, gracias! ya lo arreglé. Entonces finalmente en la consulta 2 solo tiene que dar 'Sterling Archer', cierto?

**Comment by Hernan4444** [comment]
@BeaGaete Precisamente, voy a subir en la noche uno con resultados buenos y pondré más. Ojalá los puesdas probar pronto para buscar cualquier irregularidad (lamento esto pero crear una solución en poco tiempo igual es dificil pero con la ayuda de todos podemos crear una solucion 100% buena y evitar errores al momento de corregir 😅 )

**Comment by llloyola** [comment]
@Hernan4444 Entonces para ser parientes de grado 1 o 2, deben tener los mismos problemas de visión? Con el enunciado, yo había entendido que bastaba con que tuvieran un sólo problema en común.

**Comment by Hernan4444** [comment]
@llloyola deben tener los mismos problemas. Si uno tiene miopio y el otro no, ya no tienen los mismos problemas.

**Comment by Hernan4444** [comment]
Acabo de subir más test (disculpen la tardanza). Si pueden probarlos sería ideal 👍 
Si quieren compartir más test y resultados, adelante c:
Saludos ✌️

**Comment by felipecr00** [comment]
Del archivo de test1, en mis resultados me entrega que Henry Boys es albino (consulta 7 del json)
@Hernan4444 podrias confirmar si eso es asi :3 ?? me da que presenta genes AAT en el color de pelo y tono de piel :/ aiuda pls
Saludos!

**Comment by Hernan4444** [comment]
@felipecr00 para que una persona de albino, tiene que ser en pelo, piel y ojos. Henry Boys tiene AAT en pelo y piel, pero los genes de ojos son `['CAG', 'CCT']` lo cual implica que no puede ser albino

Saludos ✌️

**Comment by felipecr00** [comment]
ooh ya veo jajaja ahora entiendo, muchas gracias!!
