### ISSUE TITLE
Importar os en parametros.py

### ISSUE THREAD

**Issue by KEKGU** [IIC2233/Syllabus#363]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, mi pregunta es si puedo importar el modulo os en parametros.py. La duda viene por la issue 223 (Tarea1), en donde una respuesta dice que no se pueden importar librerias en parametros.py. Pero me gustaría usar os.path.join() para las rutas que vaya creando

**Comment by Hernan4444** [comment]
Hola,

Tal como se dijo en esa issue, la respuesta es no. La idea de parámetros es que son constantes y no hacen `import` de nada. Ahora, si quieres guardar las rutas, hay otra forma. Cuanda la lista que le darías a `os.path.join`. Por ejemplo:

```python
LOGO_SPRITE = ["sprite", "logo.png"]
```


Y luego, en tu código haces

```python
import parametros
import os
path = os.path.join(*parametros.LOGO_SPRITE)
```
Ese `*` se va a encargar de desempaquetar la lista, y ejecutar lo siguiente `os.path.join("sprite", "logo.png")`


Saludosヾ(＾-＾)ノ
