### ISSUE TITLE
Ubicacion mapas tarea 02

### ISSUE THREAD

**Issue by dsilvc** [IIC2233/syllabus#363]
Para la tarea 2 ¿Podemos asumir que los mapas siempre van a estar en la carpeta mapas que nos dieron?. ¿Si ustedes añaden otro mapa para probar también estaría en esa carpeta?

**Comment by aljara97** [comment]
Hola, este supuesto es válido, si agregamos otro mapa estará en la carpeta mapas. Eso sí no necesariamente tendrán los nombres de los dos archivos entregados. Te sugiero incluir este supuesto en tu readme y citar esta issue.

**Comment by dsilvc** [comment]
Gracias !!

**Comment by aljara97** [comment]
De nada, por favor no cierres esta issue, nosotros lo haremos cuando corresponda. Puede ser de utilidad para otro compañero ;)
