### ISSUE TITLE
QObject::setParent: Cannot set parent, new parent is in a different thread

### ISSUE THREAD

**Issue by rubenmalis** [IIC2233/Syllabus#363]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, qué es este error, y como puedo solucionarlo?

**Comment by vicente999** [comment]
Hola! Le puedes hacer push a tu repo de lo que llevas para ver en detalle lo que está pasando?
En todo caso aca te dejo una referencia de cómo solucionar ese error https://stackoverflow.com/questions/35868750/qobjectsetparent-cannot-set-parent-new-parent-is-in-a-different-thread

https://forum.qt.io/topic/78994/error-qobject-setparent-cannot-set-parent-new-parent-is-in-a-different-thread

**Comment by rubenmalis** [comment]
Hola, ya está subido. Los archivos en los que podría estar el problema son clases_juego y ventana_juego en T2/entrega_final/juego.
Quedo atento a tu respuesta, muchas gracias.

**Comment by vicente999** [comment]
Ya mira estuve revisando tu codigo y te tengo varias recomendaciones:
1- Separa en Front y Back la parte del juego
2- Modulariza las clases del juego (Conejo, Lobo, Cañon, Baldosa, etc..) así te será más fácil debuggear este tipo de errores
3- El error del thread es porque quieres editar los subprocesos de Lobo desde un hilo del thread que no es el principal

Te recomendaría empezar con los puntos 1 y 2 que te marqué que creo que son más importantes en cuanto a puntaje, de momento sobre el thread del lobo puedes harcodearlo y hacerlo sin thread para tener un modelo mas simplificado, cuando tengas el punto 1 y 2 listo, ahi me tiraría con los threads.

**Comment by rubenmalis** [comment]
Dale muchas gracias.
Respecto a las rutas de los archivos, traté de ocupar el os.path y os.abspath, pero solo me funcionaron al colocar la ruta absoluta. Se puede hacer algo?

**Comment by vicente999** [comment]
Mmmm y probaste copiando las rutas relativas que te da Visual?
<img width="209" alt="image" src="https://github.com/IIC2233/Syllabus/assets/53841116/f31b95d3-b0c3-4cc8-9489-e77d4642292a">
De repente no te funciona porque la ruta esta mal escrita
