### ISSUE TITLE
Enviar una instancia de una clase con señales

### ISSUE THREAD

**Issue by mjespinoza** [IIC2233/syllabus#363]
Holaa, he estado intentando hacer que cuando se genere la ventana de juego desde mi ventana de inicio, se emita una una señal con la instancia del jugador que se genero el la ventana de inicio, sin embargo, esta instancia de jugador no se guarda como deberia, sino que solo la puedo ocupar en la funcion que la recibe. No se que hacer :c

**Comment by roberto009** [comment]
Hola!
Por lo que veo no estás guardando la instancia del jugador en ninguna parte luego de que es recibida por la función. Es por esto, que solo la puedes usar dentro de es función.
Prueba guardando la instancia como una atributo de clase para pode utilizarla después  de salir de la función. 

Recuerda que no es buena pirática definir atributos de clase fuera del `__init__`, por lo que te recomiendo que lo crees en el `__init__`y después simplemente lo reemplaces.

Avísame como te va!
Éxito 💪
