### ISSUE TITLE
Cantidad de dígitos del id

### ISSUE THREAD

**Issue by dvogaz** [IIC2233/Syllabus#364]
Ya que en el archivo listas.txt los ids llegan hasta el 30 solamente,
Puedo asumir que al leer el genoma los dígitos del id asociados al tag siempre serán 1 o 2 y no más?

**Comment by Kitaps** [comment]
Hola, 

suponiendo que son más yo te recomendaría que lo hagas con recursión. 
Vas usando isnumeric 
en caso de que sea numerico lo agregas y haces la funcion denuevo con lo que llevas más el resto de la linea
en caso de que encuentre un no numerico 
transformas lo que llevas en int y retornas eso

Con eso puedes obtener el int de cualquier largo

**Comment by Hernan4444** [comment]
@dvogaz  no puedes asumir eso. Lo que dice kitaps es una forma de hacerlo aunque tambien hay otras.

Saludos ✌️

**Comment by dvogaz** [comment]
Graaciaaas 😊  @kitaps @hernan4444
