### ISSUE TITLE
Duda con el main.py

### ISSUE THREAD

**Issue by ItsSancer** [IIC2233/Syllabus#364]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Que tan flexible puede ser el main? Me gustaria agregar unas funciones que gestionen los niveles, cerrando instancias y abriendo otras. Pero como nunca hemos visto ejemplos donde el main haga mas cosas que conectar o iniciar, no se si es legal hacer que haga mas cosas.

**Comment by CrisDonosoMaass** [comment]
Hola! Puedes añadir funciones al main pero asegúrate que se mantengan las responsabilidades de cada ente. Por ejemplo, no hagas cosas del cliente en el main del server y viceversa, etc.
