### ISSUE TITLE
Error tipo [Errno 2] QtDesigner

### ISSUE THREAD

**Issue by nfragav** [IIC2233/syllabus#364]
Hola! Estaba intentando usar el codigo de los contenidos de la semana 6 y 7 para crear ventanas usando Designer a traves del siguiente codigo compartido en los contenidos:
![Capture1](https://user-images.githubusercontent.com/53798945/66008774-3f4cd680-e48e-11e9-9f71-f444b827b8df.PNG)

Lo cual me presenta el siguiente error, respecto de encontrar el archivo que quiero mostrar:
![Capture2](https://user-images.githubusercontent.com/53798945/66008796-5be90e80-e48e-11e9-81bc-d4195195ac3f.PNG)

Analogamente, la libreria de pyqt5 presenta el mismo tipo de error respecto a imagenes cuando intento mostrar estas en mi ventana.

Quedo atento y muchas gracias por sus respuestas.

**Comment by nabenitez** [comment]
Hola @nfragav!

Debes asegurarte que ```ventana_inicio.ui```esté en la misma carpeta que ```ventana_inicio.py```. Tu error se debe a que el programa no encuentra el archivo creado en QtDesigner(```ventana_inicio.ui```) en la misma carpeta que ```ventana_inicio.py```.  

Respecto al segundo error, también debes tener las imágenes y/o rutas a las que haces referencia en el **.py** en las carpetas respectivas.

Si sigues teniendo problemas o pudiste resolverlo, comentalo acá!,
Saludos!
