### ISSUE TITLE
Alimentar: orden, mostrar comida y criatura.

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2233/syllabus#364]
Cuando alimento, Puedo mostrar primero los alimentos disponibles y primero y despúes las criatura a las que se lo puedo dar?

**Comment by aljara97** [comment]
Hola @Aloncarrasco!

Puedes hacerlo, mientras permitas que el usuario escoja el alimento y la criatura no hay problema.

Suerte con tu tarea 🧙‍♂️
