### ISSUE TITLE
Título descriptivo (reemplazar con el título apropiado)

### ISSUE THREAD

**Issue by aagodoy1** [IIC2233/syllabus#364]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola tengo una pequeña duda con el detalle que debe tener el resumen que se entrega al terminar cada hora simulada, en el enunciado dice "mostrar .... un reporte de los movimientos de dinero, que contenga el dinero recaudado y los gastos incurridos durante la hora simulada"

Eso significa que si tenia 16 barcos en la simulación, como mínimo tendré que poner 16 transacciones en el resumen y además poner cuanto se recaudó y gastó al final ?  No es posible solo poner dinero recaudado y gastado en esa hora ?

**Comment by mistico0121** [comment]
Hola

Es preferible que muestres todas las transacciones una por una, pues así se puede ver si todos los valores están en orden para cada uno de los barcos. No solo nos ayuda a corregir mejor, si no que también los ayuda a debugear para que puedan revisar si todo está en orden con cada tipo de barco, gasto de dinero, etc.
