### ISSUE TITLE
Pixmap

### ISSUE THREAD

**Issue by mjgarrido1** [IIC2233/syllabus#364]
Cuando intento actualizar la imagen de mi personaje en una funcion_actualizar_personaje la imagen me aparece cortada, no obstante cuando corro exactamente el mismo codigo en el init_gui la imagen cambia correctamente. 
Todo esto en la ventana de mi juego. 
He tratado de buscar respuestas pero la verdad no entiendo por qué exactamente las mismas lineas funcionan distinto si estan en el init_gui o en una funcion :(

**Comment by jmwielandt** [comment]
Hola, ¿puedes subir tu código actualizado y dejar en el inicio de tu readme las zonas de código (una comentada) donde se ve a esta diferencia?
