### ISSUE TITLE
librería csv

### ISSUE THREAD

**Issue by fpattillo** [IIC2233/Syllabus#364]
En la ayudantía del martes se informó que al hacer uso de la librería csv, no habría problema con las comas extra (de los reviews, por ejemplo). Sin embargo, usando csv.reader me aparecen igualmente dos reviews en donde se separa en dos el review porque este contiene una coma. ¿Esto es normal y debo ingeniarmelas para arreglarlo, o no debería estar pasando?
Gracias!

**Comment by ptflores1** [comment]
Hola !
Intenta agregando el parametro `skipinitialspace=True` en el reader de csv, por lo que entendi en lo que busque el problema es que el reader reconoce a `"` como un delimitador de una cita ( parametro quotechar) por defecto y el csv que les dimos tiene un espacio antes de las `"` por lo que `skipinitialspace=True` hara que no se tome en cuenta el espacio, todo lo que este dentro de las `"` se tomara en cuenta como texto puro asi que no deberia separar la linea en las `,`
Saludos !

**Comment by fpattillo** [comment]
Listo! Muchas gracias!
