### ISSUE TITLE
¿Dónde comenzar a escribir tras colocar un backslash?

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#364]
en los contenidos de la semana 0 explicaron que cuando una linea contenía sobre 100 caracteres se podía insertar un "\" y el código continuaba en la línea siguiente. Existe una regla en específico sobre en que posición de la siguiente línea se debe comenzar a escribir

**Comment by retamalcito** [comment]
¡Hola @enriquemolinare!

Asumo que te refieres al **backslash** (`\`). En dicho caso, no existe una regla que diga dónde se debe a comenzar a escribir en la siguiente línea, pero te recomiendo que siempre intentes que luzca ordenado y legible. Lo más importante es que mantengas la indentación de la línea original, para evitar confusiones.

De todas formas, la mayoría de editores de texto te colocan en una posición ideal al momento de hacer `Enter` después de haber colocado un `\`, por lo que te sugiero continuar escribiendo desde esa posición.

Espero haber aclarado tu duda, ¡saludos! 👋
