### ISSUE TITLE
Duda sobre que sucede después de mutar una planta en el laboratorio

### ISSUE THREAD

**Issue by ssya333** [IIC2233/Syllabus#364]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Holaa, en el laboratorio después de mutar una planta si la mutación no es exitosa hay que permanecer en el laboratorio, pero si es exitosa también hay que permanecer en el laboratorio o hay que volver al menu de acciones?

**Comment by UnFedaykin** [comment]
Hoola! Lo que pase luego de realizar una acción exitosa queda a tu criterio, puedes quedarte en el menú del laboratorio (estableciendo en este una forma/opción para volver al menú de inicio) o volver directamente al menú de inicio. Cualquiera que sea tu decisión, te invito a escribirla en el README para que quede especificada. Éxito!

**Comment by ssya333** [comment]
Graciaas!
