### ISSUE TITLE
Parámetros para magizoólogos ya creados

### ISSUE THREAD

**Issue by sofiaemd** [IIC2233/syllabus#365]
Estoy confundida sobre cómo funciona el archivo parámetros.py para magizoólogos ya creados. Es decir, cómo se crean los parámetros que se basan en características que ya tienen los magos (por ejemplo la probabilidad de sanar una criatura. ¿Hay que importar el archivo después de cargar el magizoólogo o esos parámetros se definen en el código?
Muchas gracias

**Comment by Dnpoblete** [comment]
Hola @sofiaemd, creo que hay una pequeña confusión con los parámetros. La idea de usar un archivo que contenga los parámetros es que tu creas el archivo y cada vez que requieras los parámetros en alguna parte de tu código los importas para utilizarlos. Es por esto por lo que no debería de haber una diferencia entre los magizoólogos antiguos y los nuevos, ya que ambos los tienes que cargar en alguna parte de tu código, entregándoles los parámetros correspondientes.

Espero haber aclarado tu duda y si no fue así avísame que parte no entendiste para poder ayudarte 😄

**Comment by sofiaemd** [comment]
Gracias, hay algo que no me quedó tan claro.. cuando dices que cada vez que quiera usar un parámetro hay que importar lo es que hay que llamarlo o hacer import parametros?

**Comment by sofiaemd** [comment]
Ah, nada, ya entendí, leí el issue #361 y me quedó claro! 🙈

**Comment by sofiaemd** [comment]
muchas gracias

**Comment by Dnpoblete** [comment]
Que bueno que pudiste resolver tu duda @sofiaemd, pero por favor no cierres la issue ya que podria ayudar a algún compañero/a con la misma duda 😄
