### ISSUE TITLE
Duda con archivos, carpeta assets y parametros

### ISSUE THREAD

**Issue by benjaminsalgado** [IIC2233/Syllabus#365]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda relacionada a como distribuir los archivos dentro de la carpeta de cliente. De la forma en la que estoy haciendo mi trabajo, el juego se iniciará en el backend, y tendrá su propio frontend y backend ubicado en su interior, algo así:

cliente:
    -> main.py
    -> frontend
        -> frontend.py
    -> backend
         -> backend.py
            ->j_backend.py
            ->Iniciador_juego.py
        -> Juego
            ->j_backend.py
            ->j_frontend.py

Mi duda es, la carpeta de assets y parametros, puedo solicitar en mi readme que sean copiados en varias partes distintas? Es correcto poner todo el juego dentro del backend?
Saludos

**Comment by benjaminsalgado** [comment]
Mi otra opción es ponerlo todo dentro de la carpeta cliente, pero no se si supondría un descuento de puntaje

**Comment by vicente999** [comment]
Hola! Te recomiendo seguir esta estructura:
Cliente:
       Backend:
               parametros
               Archivos que sirvan para la LOGICA DEL JUEGO, ej:
               Lobo.py (clase lobo)
               Conejo.py (clase conejo)
               LogicaJuego.py (archivo que verifica si ganaste/perdiste, etc)
        Fronted:
               Manejo de vistas, ej:
               MenuPrincipal.py
               VentanaInicio.py
               VentanaJuego.py

        main.py (archivo para correr el juego)

Sobre los assets y parámetros te recomiendo tenerlos una vez y llamarlo con path relativos segun tus necesidades, los assets podrían estar en el front (que es donde los llamas) y los parámetros en el back.

**Comment by vicente999** [comment]
Como recomendación util para debuggear más rápido, separa cada clase en un archivo, así es mucho más fácil detectar errores
