### ISSUE TITLE
Uso de método exec() de QWidget

### ISSUE THREAD

**Issue by plourido** [IIC2233/Syllabus#365]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, espero que se encuentren bien y que tengan un buen fin de semana. Les escribo ya que tengo una duda en como ejecutar un pop-up ya que revisando en internet encontré una solución pero utilizan exec() y tengo entendido que eso esta prohibido utilizar. Les dejo un link donde encontré información para realizar el pop-up y para ejecutarlo utilizan ```exec_()```

<https://www.techwithtim.net/tutorials/pyqt5-tutorial/messageboxes>
Me podrían ayudar con eso por favor 
Muchas gracias

**Comment by Panconquesocl** [comment]
Holaa espero que estes bien😁!!, si quieres si puedes utilizar el método exec() como aparece en el tutorial, ya que, es el método exec() de QWidget y el que no esta permitido es el método built-in de python exec() que permite ejecutar codigo a partir de un string, si te quedan dudas no dudes en resolverlas por aquí 😉👍.

**Comment by ignaverb** [comment]
@Panconquesocl 
Holaa, se pueden utilizar los pop ups para indicar por ejemplo que no se pueden colocar más objetos de cierto tipo en el modo constructor? o esto solo se debe indicar con labels?

**Comment by Panconquesocl** [comment]
> @Panconquesocl Holaa, se pueden utilizar los pop ups para indicar por ejemplo que no se pueden colocar más objetos de cierto tipo en el modo constructor? o esto solo se debe indicar con labels?

Holaaa si puedes 👍, como notificar esto al usuario queda a tu elección siempre y cuando no sea por terminal, suerte!!😁.

**Comment by ignaverb** [comment]
> > @Panconquesocl Holaa, se pueden utilizar los pop ups para indicar por ejemplo que no se pueden colocar más objetos de cierto tipo en el modo constructor? o esto solo se debe indicar con labels?
> 
> Holaaa si puedes 👍, como notificar esto al usuario queda a tu elección siempre y cuando no sea por terminal, suerte!!😁.

Buenisimo, gracias!!!

**Comment by ignaverb** [comment]
Holaa sobre el método exec se puede uitilizar para realizar sys.exit(app.exec()) al iniciar el programa?
