### ISSUE TITLE
Como comparar dos listas sin for ?

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#365]
hola, 

para ver si dos listas son iguales, se me ocurría primero tomar una, recorrerla y si algun valor no está en la otra retornar false
luego lo mismo pero recorrer la otra lista y ver si algun valor no está en la primera, en tal caso retornar false

si termina de revisar ambas, que retorne true

Pero esto no se me ocurre como hacerlo sin for, ayuda porfavor

**Comment by fgbruna** [comment]
*Disclaimer:* no se si pueda responderte siendo también alumno, pero creo que puedo aconsejarte algo de manera general
Yo recomendaría aprovechar el uso de `zip` y ` lambda` :point_left:

**Comment by MarceloSaldias** [comment]
Se me ocurre ordenar las 2 listas (con lo que sea que pueda ser ordenable, y si no haces una funcion lambda para la key del sort), y despues compararlas directamente (lista1 == lista2). Si es True son iguales

**Comment by pnheinsohn** [comment]
lista_1 = lista
other_list = lista que quieres ver si es igual a lista_1
new_list = list(filter(lambda elem: elem in other_list, lista_1))
iguales = len(new_list) == len(other_list)

donde iguales es un booleano de si son iguales o no

**Comment by Kitaps** [comment]
@MarceloSaldias gracias pero no me sirve, ya que son valores nominales (Problemas de visión, zonas de pelo)

@pnheinsohn Wenisimo gracias, no se me había ocurrido usar len
