### ISSUE TITLE
Grid Layout

### ISSUE THREAD

**Issue by fbarrosalcalde** [IIC2233/syllabus#365]
Hola! Quería saber si se puede hacer un grid layout sin espacios entre los componentes? Gracias de antemano.

**Comment by aundurraga** [comment]
Hola! Si! Con setSpacing():
grilla.setSpacing(0)
Espero que te sirva!

**Comment by fbarrosalcalde** [comment]
Perfecto, gracias!

**Comment by SugarFreeManatee** [comment]
Hola! A mi con setSpacing(0), setHorizontalSpacing(0) y setVerticalSpacing(0) todavia me aparecen los espacios :(
