### ISSUE TITLE
Consulta do_if

### ISSUE THREAD

**Issue by seba608** [IIC2233/Syllabus#365]
Hola!

En el do_if dice "Si consulta b es true, realiza el consulta a, en caso contrario, realiza el consulta c.".
¿Se asume que lo que retorna do_if es lo que retorna la consulta que se ejecuta finalmente?

Si es así, ¿mi programa puede ejecutar tanto consulta a como consulta c pero retornar solo el valor que corresponda según consulta b?

Saludos

**Comment by Dunkan1** [comment]
segun yo
a) si
b) si, solo que en el workflow dijeron como dato que no necesitamos hacer ambas por ejemplo en el caso del do_if

**Comment by Hernan4444** [comment]
a) si, puedes asumir eso
b) y si te damos una consulta "c" gigantesca de 10 minutos pero nosotros sabemos que debería salir "a" que se demora 1 segundo? como tu consulta se demora mucho mas de lo esperado se te podría considerar malo.

Saludos!

**Comment by seba608** [comment]
Y pueden ser consultas anidadas? @Hernan4444 

Saludos!

**Comment by Hernan4444** [comment]
@seba608 si pueden ser :+1: 
Saludos!!

**Comment by seba608** [comment]
Gracias ! @Hernan4444
