### ISSUE TITLE
Citar codigo

### ISSUE THREAD

**Issue by emena97** [IIC2233/syllabus#365]
Hola, para mi tarea ocupo codigo que he encontrado en internet para algunas funciones y clases, cual es la manera correcta de citar este codigo y donde se hace? ( tarea misma, readme, etc)

**Comment by DCCollao** [comment]
Hola!
En tu readme, al final, hay una sección de nombre
## Referencias de código externo :book:

Aquí debes indicar de dónde sacaste el código, para qué lo utilizaste, y en qué archivo y líneas se encuentra.
Saludos!

**Comment by VicenteMerino** [comment]
Hola, que pasa si algunas partes de una clase lo basé en códigos de ayudantias pasadas (la estructura), pero fue modificado en base a lo requerido (pero aun así podrian encontrarse algunos parametros con los mismos nombres) y no es una cantidad de líneas fija la que fue sacada externamente, sino que la "idea".

**Comment by gatochico** [comment]
Hola! En esos casos, puedes poner en la sección de "Referencias de código externo" del README algo como: "El modulo 'modulo.py' está basado en/tiene ideas sacadas de la ayudantía XX del semestre 20XX-0X" y se entenderá la idea :cat:

**Comment by isihirmas** [comment]
Si sacamos algo del material de clases ( código carpeta extra) también hay que referenciarlo o se asume que eso está dado?

**Comment by DCCollao** [comment]
Hola!
En ese caso, lo mejor sería seguir lo que comentó gatochico, mencionando el módulo que sigue las ideas de la carpeta extra.
