### ISSUE TITLE
Opción Volver Atrás en Menús

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#365]
Hola, en el punto **3. Menús** dice que cada uno debe tener la opción de volver atrás. Mi pregunta es si el Menú Principal también tiene que tener esta opción, ya que en este no se explicita en las opciones de este menú?

**Comment by vsantelicest** [comment]
Hola! Efectivamente todos los menús deben tener la opción de volver atrás, a excepción del menú de inicio. Esto se menciona también en la issue #332, por si quieres revisarla también.

**Comment by Gustav2000** [comment]
Gracias!!!

**Comment by Crkosche** [comment]
Hola, en este mismo caso si es que vuelvo atrás desde el menú principal al menú de inicio se reinicia el juego? Tengo que volver a preguntar el nombre de entrenadores y empezar el juego desde cero?

**Comment by vsantelicest** [comment]
Hola! En ese caso, efectivamente, se reiniciaría la simulación actual de la DCCumbre Olímpica, reestableciendo todos aquellos valores que hayan sido modificados.
