### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#366]
en cada test hay que hacer 6 cosas cierto?
se debe testear que en cada funcion minima ocurra el error esperado (los 5) y
que funcione bien?
o algo mas?

**Comment by Hernan4444** [comment]
@Dunkan1 no es necesario. 
Tienes que testear los comandos señalados en el enunciado y ademas 5 test mas que fallen. Como son 9 comandos a testear, tu programa debe tener como mínimo 14 test, donde 5 son los errores posibles señalados

Saludos!!

**Comment by Dunkan1** [comment]
o ya veo gracias
