### ISSUE TITLE
resultados.txt.txt

### ISSUE THREAD

**Issue by cfernandez9** [IIC2233/Syllabus#366]
Cómo se llama el archivo de resultados? resultados.txt.txt o resultados.txt? Porque en el enunciado sale lo segundo, pero cuando lo descargué me aparece como lo primero...

**Comment by jerosalazar** [comment]
Yo creo que el archivo resultados.txt.txt lo llamaron así para que no se sobreescriba cuando crees tu archivo de resultados, ya que resultados.txt.txt contiene los resultados de las consultas de ejemplo

**Comment by Hernan4444** [comment]
@cfernandez9 efectivamente le pusimos otro nombre (aunque fue mala idea ponerle *.txt*) pero la idea era que no sobreescribiran ese archivo por equivocación.

Saludos ✌️

**Comment by cfernandez9** [comment]
@jerosalazar @Hernan4444 muchas gracias!
