### ISSUE TITLE
Método abstracto en clase abstracta no retorna 

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#366]
Hola! He probado muchas veces y me he dado cuenta de que mi método en clase abstracta funciona perfecto excepto que no retorna nada. (En este caso quiero que me retorne True o False) Saben que tengo que hacer para que si me retorne un bool?

**Comment by jirarrazaval** [comment]
(Es un @abstractmethod)

**Comment by igbasly** [comment]
Hola @jirarrazabal 
Considerando el como funciona los métodos, con un `return True/False` debería ser suficiente, nunca está demás recordar que debes asociar el resultado a una variable o no se va a guardar `variable = super().metodo()`.
De todas formas te aconsejo que revises el contenido [asociado al tema](https://github.com/IIC2233/contenidos/blob/master/semana-03/3-clases-abstractas.ipynb) para que revises si hay algo que estes pasando en alto.

No dudes en escribirnos cualquier inquietud :v:

**Comment by jirarrazaval** [comment]
Muchas gracias! Me funciono guardar el super().metodo()
