### ISSUE TITLE
empate en ganadores_por_distrito

### ISSUE THREAD

**Issue by cataruze** [IIC2233/Syllabus#366]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Holaa, en la función ganadores_por distrito, que se deve devolver si hay un empate?
Muchas gracias de antemano.

**Comment by Julius9** [comment]
En caso de empates en las consultas se debe devolver el elemento (en este caso el distrito) de menor id.

**Comment by cataruze** [comment]
Hola, me puse a ver los test cases, y de estos se asume que se devuelven ambos si hay empate, y si realizo lo de devolver el de menor id habrían menos elementos que en la solución del test case.

**Comment by juliettegramatges** [comment]
> En caso de empates en las consultas se debe devolver el elemento (en este caso el Candidato) de menor id.

Hola, creo que esto no se dice en el enunciado. Y me sumo a la duda de la consulta.

**Comment by Julius9** [comment]
Hola, primeramente debo admitir que en un inicio cometí un error y respondí pensando que era otra consulta. Ahora en segundo lugar, el retorno en caso de empate es tal como menciona @cataruze, es decir se deben retornar los dos elementos empatados.

Saludos y lamento el error
