### ISSUE TITLE
Duda respecto al número de acciones de cada día

### ISSUE THREAD

**Issue by Igufu** [IIC2233/Syllabus#366]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Saludos!, tengo una duda respecto a el número de acciones por día. A lo que me refiero son las acciones dentro del menú principal, ¿tengo que limitar yo la cantidad de acciones que se pueden hacer? (por ejemplo para que no se puedan regar y cultivar las plantas infinitamente). Gracias!

**Comment by UnFedaykin** [comment]
Hoola! Siendo que algunas acciones no tienen costo, en efecto, puedes realizarlas infinitamente, y no es necesario que limites la cantidad de acciones a realizar. Éxito en tu tarea!

**Comment by EnzoBalboni321** [comment]
> Hoola! Siendo que algunas acciones no tienen costo, en efecto, puedes realizarlas infinitamente, y no es necesario que limites la cantidad de acciones a realizar. Éxito en tu tarea!

¿Cual seria un ejemplo de una acción que consuma soles? No he logrado encontrar alguna, pero en el enunciado se hace referencia a algunas acciones señalando que no consumen soles, indicando que existen acciones que necesitan gastar soles para ser ejecutadas, gracias.
