### ISSUE TITLE
Acciones que requieren dinero 

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#366]
Hola!!! ¿Puedo asumir que para todas las acciones que requieran el uso de DDCoins se debe cumplir que tenga el dinero suficiente para poder realizarla?

**Comment by jitorcas** [comment]
Hola! @denisseleiva 

Si! Puedes asumir que si la Delegación no tiene dinero suficiente no podrá realizar la acción. 

Mucho éxito! 🥇

**Comment by denisseleiva** [comment]
gracias!!
