### ISSUE TITLE
Movimiento lobo y choque con zanahoria

### ISSUE THREAD

**Issue by bea-or** [IIC2233/Syllabus#366]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda acerca del movimiento del lobo. En el enunciado dice que se mueve hasta que choca, cuenta si choca con una zanahoria?

**Comment by AESMatias** [comment]
Tengo la misma duda.

**Comment by vicho14** [comment]
Hola!, el lobo no puede sobreponerse en la zanahoria, se interpreta como pared. Por lo que en el caso que dices, choca con la zanahoria. En una issue anterior lo preguntaron de todas formas (#246).

**Comment by Segismundios** [comment]
Hola! Tiene que ser estrictamente así? Porque eso no sale especificado en el enunciado e implicaría cambiar la lógica de mi juego :'(

**Comment by Segismundios** [comment]
Tomando en cuenta que acá la pregunta es por la zanahoria y en el issue anterior que indicas se refiere al cañón

**Comment by vicho14** [comment]
Perdón la confusión, pensé directamente en el cañón. El caso que dices tú, no se especifica en el enunciado. En ese caso puedes hacerlo como tu quieras o creas mejor nada más. No se evalúan estas interacciones.
