### ISSUE TITLE
Reviews con muy pocas palabras de words.csv

### ISSUE THREAD

**Issue by AlexanderBarrera** [IIC2233/Syllabus#366]
Hola,  (tomando los .csv de Database)
Tengo una duda, ¿dejamos pasar nomás que en reviews hayan poquisimas palabras de words.csv en los comentarios?, la consecuencia de esto es que las reviews tengan porcentajes buenos o de malos bajísmos, lo que hace que todas (exepto 1 o 2) se clasifiquen como neutrales, lo q impide calcular siquiera los 5 mejores, ya que con suerte hay 1 pelicula que tienen 1 comentario considerado positivo, ¿selecciono al azar dentro de las restantes que nisiquiera tienen comentarios buenos?, o de ser posible, se puede actualizar words, para que incluya palabras efectivamentes precentes en los comentarios en mayor cantidad?
Agradezco de antemano, muchas gracias

**Comment by akrebs2** [comment]
Favor responder!

**Comment by Hernan4444** [comment]
Hola, puedes actualizar words.txt para que salgan más comentarios. Al momento de corregir, nosotros usaremos otro review.csv y words.txt que asegure tener mínimo las 5 mejores películas.

Saludos ✌️
