### ISSUE TITLE
Orden de revisado de encallamiento

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#366]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

#### Cuando ingresamos un nuevo barco, el enunciado dice:
![image](https://user-images.githubusercontent.com/66154723/116195870-c280ed80-a700-11eb-9043-73d8c67f844b.png)
Cuando dice "el barco", supongo que se refiere al barco que acaba de ingresar, (si el usuario ingresó uno), y luego revisar el flujo para el resto de los barcos. (Eso entiendo yo)

#### Sin embargo, me parecería un poco más lógico que al entrar el barco, en vez de revisar primero este, se revisen todos los barcos comenzando desde el más lejano.  ¿Puedo hacerlo de esta manera?
(TL;DR, interpreté del enunciado este flujo): Barco nuevo encalla -> Barco nuevo acc. especial -> Barco nuevo moverse ->  El resto de los barcos encalla -> resto de los barcos acc. especial -> resto de los barcos moverse

Pero yo quiero hacer
Revisar todos baros encalla -> acc. especial -> moverse

**Comment by Emiliax16** [comment]
Hola @fernandosmither ! la issue [#251](https://github.com/IIC2233/syllabus/issues/251) explica detalladamente cómo es el flujo de los barcos dentro del canal. En esta issue, se dice que el flujo es cómo dices tu, barco ingresa, se revisa si encalla, si se activa el evento especial y luego avanza, y esto es repetido por todos los barcos del canal cada hora. En la realidad, este proceso sucedería al mismo tiempo para todos, por lo que puedes hacerlo de esa manera.

**Comment by fernandosmither** [comment]
> Hola @fernandosmither ! la issue [#251](https://github.com/IIC2233/syllabus/issues/251) explica detalladamente cómo es el flujo de los barcos dentro del canal. En esta issue, se dice que el flujo es cómo dices tu, barco ingresa, se revisa si encalla, si se activa el evento especial y luego avanza, y esto es repetido por todos los barcos del canal cada hora. En la realidad, este proceso sucedería al mismo tiempo para todos, por lo que puedes hacerlo de esa manera.

### Hola!, había visto esa issue y justamente ahí se me generó la duda, porque
![image](https://user-images.githubusercontent.com/66154723/116321561-4336fc80-a788-11eb-8ee0-a465234e0c72.png)


### No me queda claro si, al ingresar un barco nuevo al canal, tengo que revisar primero las acciones de ese barco **y después el resto de barcos** o si puedo simplemente revisar este al final, dado que es el último que ingresé.

### Mi problema con revisar todos los barcos "a la vez" es que perdería la facultad de decirle a un barco que no avance si un barco anterior a él encalló, ya que como lo estoy haciendo yo, itero de manera ordenada sobre ellos y dejo de pedir que avancen cuando encuentro un barco encallado.  Ahora claro, a mi el enunciado originalmente me hizo entender que quieren que revisemos primero al **barco que acaba de ingresar** y luego los demás, pero yo preferiría revisarlos todos por orden desde el más lejano.

Ojalá me haya hecho entender, sé que es muy enredada mi pregunta jaja 😢

**Comment by Emiliax16** [comment]
Yo diría que puedes hacerlo como dices! porque al final, estas cumpliendo lo que se pide en el enunciado!! te recomiendo fuertemente explicar el cómo lo llevarás a cabo en tu README, ya que el flujo de los barcos y sus posibles eventos es lo más pesa de la tarea c:

**Comment by fernandosmither** [comment]
> Yo diría que puedes hacerlo como dices! porque al final, estas cumpliendo lo que se pide en el enunciado!! te recomiendo fuertemente explicar el cómo lo llevarás a cabo en tu README, ya que el flujo de los barcos y sus posibles eventos es lo más pesa de la tarea c:

Vale, perfecto. Lo dejaré bien explicado para el ayudante que me toque 😊
