### ISSUE TITLE
imagenes qt designer

### ISSUE THREAD

**Issue by F-arellano** [IIC2233/syllabus#366]
estaba tratando de colocar el logo en la ventana de inicio en qt designer, pero por alguna razon al hacerlo sale todo bien, y al ejecutar el codigo con la ventana se ve todo menos las imagenes. ¿alguna idea de que podria ser?

**Comment by gatochico** [comment]
Hola!
Revisa el archivo `.ui` de la ventana que tiene el problema (puedes abrirlo con tu mismo editor de texto!), y asegurate que el path de dicho archivo sea válido en relación a la ubicacion del `.ui` y la ubicación de la imagen (Que el path relativo que viene en ese archivo efectivamente pueda llegar a la imagen desde donde se encuentra el `.ui`). Si no es así, puedes editar dicho archivo a mano y debería solucionarse.

Cualquier cosa nos avisas!

**Comment by F-arellano** [comment]
revise y la linea que aparece es <pixmap>../sprites/otros/logo.png</pixmap> (el archivo se encuentra en una carpeta aparte dentro del directorio). probe llevandolo directamente al directorio y cambiando la linea por <pixmap>sprites/otros/logo.png</pixmap>, y ahi funciona perfectamente. probablemente lo deje asi, pero igual me seria bueno saber por que no funcionó el primer path :c

**Comment by gatochico** [comment]
Aunque no puedo decirte de forma directa sin ver la distribución de tus carpetas y archivos, se me ocurre que podría haber sido algo así:
```
 -Sprites
 |-otros
   |-logo.png
-carpeta
 |-ventana_inicio.ui
 main.py (donde se instancia la ventana de inicio)
```
O algún otro caso donde el main donde se ejecuta la ventana no esté en el mismo directorio que `ventana_inicio.ui`, ya que como se debe heredar de una clase que usa el archivo .ui, quizá también usa el path que venia dentro de este archivo, el cual ya no sería valido para cualquier otra ubicación que no sea el mismo directorio. No se si se entiende, cual duda pregunta!
Éxito!!
