### ISSUE TITLE
Apoyo en tareas de años anteriores

### ISSUE THREAD

**Issue by kai-yamamoto1** [IIC2233/Syllabus#367]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Quisiera saber hasta qué punto nos podemos apoyar en tareas de semestres anteriores.
Muchas gracias!

**Comment by cattpuccino** [comment]
¡Hola @kai-yamamoto1! Según se indica en el programa puedes utilizar código de internet, mientras esté bien referenciado. Es decir, si las tareas que quieres referenciar se encuentran en internet y estas se **publicaron antes de liberar el enunciado** puedes utilizarlas. Sin embargo, si esta no existe en internet o fue publicada después de liberar el enunciado se tomará en cuenta el siguiente punto del programa:

> No se permite el uso de código de evaluaciones pasadas o será considerado falta a la ética.

Esto es lo que indica el programa, si es que te queda alguna duda:
![photo_2023-11-04_14-50-19](https://github.com/IIC2233/Syllabus/assets/101208672/a0513d5b-d7e3-40b8-a434-4b0f0c08be6b)

**Comment by BenjaMedinaPUC** [comment]
hola, espero que se encuentren bien, añadiendome a la consulta del compañer@ quiero saber en dos casos más:

-Si por ejemplo llego a usar una ayudantía/actividad sumatoria del ramo dictado en el 2019-2 ¿Se considera falta de ética?
-En caso que haya usado/implementado código que aprendí en algún curso de plataformas de pago tipo udemy o coursera ¿se considera falta de ética o puedo citarlo? ya que se encuentra en la web pero a la vez no está disponible como libre acceso para todos
Estaré atento a tu respuesta, que tengas un buen fin de semana!
