### ISSUE TITLE
Distribución de puntajes, Simulaciones, crear una o más simulaciones

### ISSUE THREAD

**Issue by Martinrsts** [IIC2233/syllabus#367]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, donde dice "Se pueden crear una o más simulaciones del DCCanal.", a que se refiere? A que tiene que haber una opción de sobreescrbir el archivo para crear el canal o a que pueden haber desde el principio dos canales?

**Comment by Emiliax16** [comment]
Hola @Martinrsts .

Se refiere a que puedes iniciar una nueva simulación del programa, básicamente que el flujo del programa funcione. Dice "una o más simulaciones" porque el enunciado dice: _el programa acabará automáticamente cuando tus fondos
lleguen a 0, significando la bancarrota del canal y el fracaso de la simulación_, por lo que, en el final del programa, queda a criterio tuyo si el programa se cierra completamente o si das la opción del volver al menú de inicio para iniciar una nueva simulación.

No se debe manejar ninguna funcionalidad de autoguardado ni nada parecido. Avísame si se entiende!

Saludos!

**Comment by Martinrsts** [comment]
Si perfecto! Muchas gracias.
