### ISSUE TITLE
Popularidad de comentarios

### ISSUE THREAD

**Issue by pcseisdedos** [IIC2233/Syllabus#367]
En la sección 2.2.1 dice:

> Tienes que determinar la popularidad de las películas basándote en los comentarios de los usuarios de la base de datos. Como no puedes leer uno por uno cada comentario, debes transformar los comentarios en un número que te indique la popularidad (o impopularidad) de una película

Mi pregunta es como se calcula la popularidad, entiendo que los comentarios positivos y negativos son una sección aparte y no es lo mismo que la popularidad (o impopularidad) de una película pero siento que de alguna forma debieran afectar en esta.

**Comment by rihanuch** [comment]
¡Hola @pcseisdedos !

La popularidad se calcula de la siguiente manera 🔢:

Si el comentario es positivo, se le suma +1 a la popularidad, si es negativo se suma -1 (se resta 1) y si es neutro se suma 0 

¡Saludos y éxito! 🍀

**Comment by pcseisdedos** [comment]
ok muchas gracias.
Otra pregunta, en que momento debo llamar a la función que le asigna la popularidad a los comentarios? porque no he visto que ese dato se use en alguna otra parte de la tarea.

**Comment by IchottMano** [comment]
@pcseisdedos Hola!

Eso queda a tu criterio cuando hacerlo.

Saludos!
