### ISSUE TITLE
no cerrar archivos

### ISSUE THREAD

**Issue by R3Y3X** [IIC2233/Syllabus#367]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ]x Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
en el metodo cargar datos dejo abierto el archivo con open y nunca lo cierro, esto influye en el puntaje aunque tenga los test cases buenos ?, dejo abierto el archivo porque sino los generadores no funcionan.

**Comment by ClemoAcevedo** [comment]
Hola @R3Y3X , dejar un archivo abierto sin cerrarlo es una mala práctica, incluso si los tests pasan. Revisa otras formas de hacerlo si tu implementación causa problemas.

**Comment by abraxvs** [comment]
Hola, esperando que aquel que lea esto se encuentre bien,
quería consultar más profundamente este tema, ya que creo que la manera en que _creo_ se pretende que lo haga el estudiante desafía el propósito de la tarea de programación funcional, me explico:
si se utiliza por ejemplo un código similar a este:
with open(blablabla) as file:
    return (funcion(line) for line in file)
asumiendo que _funcion_ es una función mágica que retorna una _namedtuple_ con la información entregada en la línea de file, nos encontramos con un problema, ya que este código entrega el generador pedido, pero, como sabemos, el generador NO tiene memoria guardada, por lo que cuando se hace la revisión por tests, el generador intenta acceder a _file_ pero no puede hacerlo porque el test no tiene abierto el archivo, lo que entrega un error ValueError: I/O operation on closed file. Una forma de resolverlo es guardar las líneas de archivo en la función:
with open(blablabla) as file:
    data = file.readlines()
    return (funcion(line) for line in data)
pero creo que esto desafía el propósito de la tarea por lo que no encuentro una solución pertinente. Si existe una instancia aparte de estas issues para resolver esta duda lo agradecería. 
Muchas gracias de antemano

**Comment by ClemoAcevedo** [comment]
@abraxvs te recomiendo volver a revisar la materia que tiene que ver con el uso de `yield` :)
