### ISSUE TITLE
Video clase cierre

### ISSUE THREAD

**Issue by pepinofdz** [IIC2233/Syllabus#367]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Estaba buscando el video de la clase de cierre porque quiero organizar mi malla del próximo semestre y recuerdo que dieron algunos tips de cursos en la última clase, pero el módulo está bloqueado en canvas. De ser posible, ¿podrían desbloquearlo?

De antemano, muchas gracias.

**Comment by gatochico** [comment]
Hola @pepinofdz !

Ya está habilitado el módulo, disculpa las molestias 😅

**Comment by pepinofdz** [comment]
Bacán! Muchas gracias!
Una última duda: el video de el profesor Tagle no está disponible? Sólo me salen los de las secciones 1, 2 y 3 jajaj
