### ISSUE TITLE
Movimiento enemigo

### ISSUE THREAD

**Issue by cmarquez1** [IIC2233/syllabus#367]
hola, lo que pasa es que cuando abro la ventana de juego los enemigos aparecen ya en el final de su movimiento y no veo como se mueven, solo el sprite en el que quedaron al final y la posición final. Tengo en el back una clase enemigo que hereda de qtread y en el run() envío una señal con las coordenadas para que se muevan en el front, y cuando creo los enemigos en __init__ de la ventana del juego ocupo la función start() par que se empiezan a mover, estos se mueven porque cuando se abre la ventana de juego, estos aparecen en una determinada posición aleatoria pero no llego a ver como estos se mueven, al contrario del jugador que apretando las teclas si puedo ver como este se mueve. No se si me explique bien pero hice push para que si no entienden vean el código.

**Comment by jeschuwirth** [comment]
Hola!

Te dejo un par de opciones que pueden arreglar tu problema:
 - Puede que tus thread de enemigos no tengan un sleep, por lo tanto se mueven tan rapido que no alcanzas a verlos antes de que lleguen a la meta.
- puede que tengas un` while true:` el cual repite el movimiento del enemigo y que la función que ocupes para actualizar a posición se encuentre fuera de este, por lo que sólo se actuliza después de moverse.

Ojalá te sirva alguna de estas opciones :)
