### ISSUE TITLE
Funcion desviacion estandar

### ISSUE THREAD

**Issue by chuma9615** [IIC2233/Syllabus#367]
buenas!, por que el denominador de la desviacion estandar  en el punto 4.2.4. esta dividido en n-1? no debería ser dividido en n? al menos asi es como lo calcula a funcion numpy.std

Saludos!

**Comment by Hernan4444** [comment]
@chuma9615 está bien la fórmula porque estamos trabajando con muestras de datos :+1:. Si te da curiosidad el porqué de la formula, te sugiero que busques por "desviacion estandar en una muestra"

Saludos
