### ISSUE TITLE
Realizar una nueva simulación

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#367]
Hola, en el punto **3.2.2 Simular Competencias** dice que en caso de no quedar días para competir una de las opciones que se darán será la de **Realizar una nueva simulación**, pero lo que no entiendo, es que si ya no quedan días de competencia, me volvería a retornar exactamente lo mismo que me acaba de mostrar antes al volver a realizar una nueva simulación. Espero que se entienda a lo que me refiero.

**Comment by vsantelicest** [comment]
Hola! Al realizar una nueva simulación, se reiniciaría por completo la DCCumbre Olimpica, volviendo a lo que sería el día 0 de competencia, y así reestableciendo, por ejemplo, el número de medallas ganadas por cada delegación. Espero se entienda 🥇

**Comment by Gustav2000** [comment]
Muchas gracias!!!
