### ISSUE TITLE
Ataque enemigo

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#368]
Hola, es válido que mis enemigos ataquen las torres o bases solo si las están mirando de frente?

Saludos

**Comment by jeschuwirth** [comment]
Los enemigos deberían ser capaces de atacar tanto torres como la base si se encuentran en una casilla adyacente. Si los enemigos siempre llegan de frente, entonces no hay problema, sin embargo si un enemigo está al lado de la base y no la ataca (porque esta girado). Entonces esta mal y se debe corregir.

Por lo general debería ser más sencillo hacerlo por la posición, de todos modos puedes dejar todos los supuestos en el readme.

Suerte en la tarea :)
