### ISSUE TITLE
Funciones en parametros

### ISSUE THREAD

**Issue by barbarafcp** [IIC2233/syllabus#368]
Hola! me preguntaba si es que yo podia definir alguna variable en el archivo parámetros con una función, por ejemplo, leer el archivo de deportistas y guardarlo ahi o no se pueden poner funciones en ese archivo?

**Comment by amparostevens** [comment]
Hola! @barbarafcp 

En el módulo `parámetros.py` tienen que ir todos los valores que permanecerán __constantes__ al momento de ejecutar tu código. En este sentido, dado que para esta tarea no se les pide almacenar cambios en los archivos entregados, podrías guardarlo como un parámetro.

Sin embargo, dado que para poder utilizar el archivo lo tienes que trabajar (me refiero a  separar los valores, etc), esa parte no debería estar en `parámetros.py`,  ya que la idea es que sólo guarde información, no que se apliquen métodos en él. 

Lo más recomendado ( y que ayuda a ser ordenados), es ocupar `parámetros.py` para guardar los **paths** relativos al archivo y luego en otro módulo, donde necesites esa información, abrirlo y trabajar con él.

Espero que te sirva! ✨
