### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by JPBarrosG** [IIC2233/Syllabus#368]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

A la hora de ejecutar mi programa, para crear las animaciones de las entidades necesito mandar una señal desde una instancia Qthread la cual esta instanciada dentro de otra clase Qobject, el problema era que al tratar de mandar la señal no habia forma que el archivo main recibiera la señal del Qthread, por lo que añadi un codigo de transcicion de señales para pasar la señal de la instancia Qthread a una señal de la instancia Qobject, siendo la instancia de esta clase si capas de conectarse al archivo main, el problema es que una vez intentado esta transicion de señales me arroja el programa la siguiente linea "segmentation fault". la linea de codigo en cuestion que me genera este error es el siguiente:
![image](https://github.com/IIC2233/Syllabus/assets/142442997/3b38de04-969d-43dd-b224-c9be8d725571)
instancias_lobos es una lista que tiene todas las instancias creadas para los lobos y el resto que aparece antes de senal_movimiento no es mas que una busqueda de indices. luego la funcion a la que se conecta es la siguiente:
![image](https://github.com/IIC2233/Syllabus/assets/142442997/84d47206-c621-409e-85dd-75cfb76176fa)
la cual es simplemente una forma de pasar la señal de un lado a otro.
que es lo que estoy escribiendo o redactando mal que se me genera el error "segmentation fault"?
cabe aclarar que investigue todo mi codigo y es efectivamente en esta linea de codigo donde se me genera el error de "segmentation fault".

**Comment by cattpuccino** [comment]
¡Hola @JPBarrosG! Por lo que veo, estas usando la **ñ** en el código, prueba cambiándolo por una **n** y me comentas que tal.

**Comment by JPBarrosG** [comment]
ahí se resolvio muchas gracias!!!!
