### ISSUE TITLE
Error al llamar una clase abstracta

### ISSUE THREAD

**Issue by EmeraldMP** [IIC2233/syllabus#368]
Hola, 

Me aparece este error cuando llamo a mi clase abstracta

Exception has occurred: TypeError
Can't instantiate abstract class Niffler with abstract methods alimentarse, enfermarse, escaparse
  File "C:\Users\princ\Desktop\Programacion_Avanzada\EmeraldMP-iic2233-2020-1\Tareas\T01\cargar_datos.py", line 19, in cargar_criaturas
    criaturas_dic[fila[0]] = Niffler(fila[0], fila[1], int(fila[2]), float(fila[3]), float(fila[4]), estado_sal, estado_esc, int(fila[7]), int(fila[8]), fila[9], fila[10], int(fila[11]), int(fila[12]) )
  File "C:\Users\princ\Desktop\Programacion_Avanzada\EmeraldMP-iic2233-2020-1\Tareas\T01\cargar_datos.py", line 29, in <module>
    cargar_criaturas(cvs_criaturas)

cómo se puede solucionar?

**Comment by jeschuwirth** [comment]
Hola @EmeraldMP,

Tienes que Niffler es una clase abstracta, estas clases **no** se pueden instanciar nunca, por lo tanto cuando la instancias Niffler(fila[0], ...) python te levanta el error de que estas instanciando una clase abstracta.

Para arreglarlo debes hacer que Niffler deje de ser una clase abstracta (dejar de heredar de ABC)

Éxito!

**Comment by EduardoIllanes** [comment]
Hola yo tuve un problema similar y se soluciona haciendo un override de los metodos abstractos. En tu caso te falta hacer un override de la clase niffler alimentarse, enfermarse, escaparse

**Comment by lily416** [comment]
Hola @EmeraldMP, ¿te funcionó lo que comentaron @jeschuwirth y @EduardoIllanes?

**Comment by EmeraldMP** [comment]
Me funcionó dejando de heredar la clase abstarcta, gracias!
@EduardoIllanes a que te refieres con un override?

**Comment by lily416** [comment]
@EmeraldMP, **_overriding_** es cuando se sobrescribe un método que fue heredado de la clase padre.
En el material de [polimorfismo](https://github.com/IIC2233/contenidos/blob/master/semana-02/4-polimorfismo.ipynb) se explica con mayor profundidad.

**Comment by EmeraldMP** [comment]
Perfecto!
