### ISSUE TITLE
Descuentos por tiempo tests

### ISSUE THREAD

**Issue by VicenteIgnacioSotoGonzalez** [IIC2233/Syllabus#368]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Buenas tardes, junto con saludar quería preguntar respecto de los descuentos asociados si un test se pasa del tiempo límite. En el enunciado se menciona que se asumirá resultado incorrecto, pero al entrar en el apartado de distribución de puntaje por cada consulta está el criterio de entrega de puntaje si pasa todos los tests para evaluar el correcto funcionamiento de la consulta y si la consulta termina en un tiempo adecuado. En tal caso si tengo una función que pasa los tests pero se demora más del tiempo, se consideran 0 puntos para la función en general o 0 puntos solo en el apartado de tiempo. Gracias de antemano.

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Por dar un ejemplo, si mi función animales_segun_edad pasa todos los tests y dura 25 segundos. Tendría 0 puntos en total en esa función o tendría 2 (ya que hay 2 puntos asociados al funcionamiento y 1 al tiempo)?

**Comment by ClemoAcevedo** [comment]
Hola @VicenteIgnacioSotoGonzalez , guíate por el Excel de la distribución de puntaje, al final del día así se revisará tu tarea y se calculará tu nota :) . Seguramente el primer criterio, el de "funciona o no" igual tiene un límite de tiempo por si pareciera que nunca vaya a terminar (para seguir corrigiendo), pero si te encuentras dentro de limites razonables (pero superior al tiempo pedido) seguramente obtendrás el puntaje de funcionamiento pero no el de tiempo.

**Comment by ClemoAcevedo** [comment]
@VicenteIgnacioSotoGonzalez me equivoqué un poco en la explicación, ósea si te tienes q guiar por el Excel pero te dejo una explicación más detallada de los profes:

habrá 2 tipos de tests

- Conjunto de tests de correctitud: que son los que no usan .csv sino que tienen los datos en el mismo tests. Esos igual deben correr en 20 segundos, pero son tan pocos datos los que se usan en esos tests que es muy muy díficil que supere los 20 segundos..... pero si el código llega a demorarse más de 20 segundos con esos tests, se considera malo igual.

- Conjunto de tests de eficiencia: que son los que cargarán CSV de diferentes tamaños, y esos tambien tendrán 20 segundos por tests, solo que aquí se espera que a medida que suba la cantidad de datos, tome más tiepo, pero nunca que se supere los 20 segundos.

Y al momento de correr los tests privados, cada tests es indepediente. En el sentido que si 1 test se demora más de 20 pero todos los demás de dicho archivo se demoran menos de 20, solo el test que tomó más tiempo será considerado incorrecto, pero todos los demás estarán correctos. Da lo mismo si ese test incorrecto fue el primero que se revisó o el último.... Para que no se preocupen de que si 1 test está incorreto, los siguientes ya se dejan de revisar, eso no pasará. 

Ojalá haya quedado más claro asi

**Comment by VicenteIgnacioSotoGonzalez** [comment]
> @VicenteIgnacioSotoGonzalez me equivoqué un poco en la explicación, ósea si te tienes q guiar por el Excel pero te dejo una explicación más detallada de los profes:
> 
> habrá 2 tipos de tests
> 
> * Conjunto de tests de correctitud: que son los que no usan .csv sino que tienen los datos en el mismo tests. Esos igual deben correr en 20 segundos, pero son tan pocos datos los que se usan en esos tests que es muy muy díficil que supere los 20 segundos..... pero si el código llega a demorarse más de 20 segundos con esos tests, se considera malo igual.
> * Conjunto de tests de eficiencia: que son los que cargarán CSV de diferentes tamaños, y esos tambien tendrán 20 segundos por tests, solo que aquí se espera que a medida que suba la cantidad de datos, tome más tiepo, pero nunca que se supere los 20 segundos.
> 
> Y al momento de correr los tests privados, cada tests es indepediente. En el sentido que si 1 test se demora más de 20 pero todos los demás de dicho archivo se demoran menos de 20, solo el test que tomó más tiempo será considerado incorrecto, pero todos los demás estarán correctos. Da lo mismo si ese test incorrecto fue el primero que se revisó o el último.... Para que no se preocupen de que si 1 test está incorreto, los siguientes ya se dejan de revisar, eso no pasará.
> 
> Ojalá haya quedado más claro asi

Holaaa! Todo super claro ahora, gracias por la respuesta!!! ;)

**Comment by abarrientosj** [comment]
Hay alguna manera de saber en cuanto tiempo debe correr cada función para no recibir el descuento de: _Pasan todos los tests para validar el correcto funcionamiento de esta consulta._
De modo de ir chequeando para ver si cumplimos con el requisito.

**Comment by Arielmild** [comment]
> @VicenteIgnacioSotoGonzalez me equivoqué un poco en la explicación, ósea si te tienes q guiar por el Excel pero te dejo una explicación más detallada de los profes:
> 
> habrá 2 tipos de tests
> 
> * Conjunto de tests de correctitud: que son los que no usan .csv sino que tienen los datos en el mismo tests. Esos igual deben correr en 20 segundos, pero son tan pocos datos los que se usan en esos tests que es muy muy díficil que supere los 20 segundos..... pero si el código llega a demorarse más de 20 segundos con esos tests, se considera malo igual.
> * Conjunto de tests de eficiencia: que son los que cargarán CSV de diferentes tamaños, y esos tambien tendrán 20 segundos por tests, solo que aquí se espera que a medida que suba la cantidad de datos, tome más tiepo, pero nunca que se supere los 20 segundos.
> 
> Y al momento de correr los tests privados, cada tests es indepediente. En el sentido que si 1 test se demora más de 20 pero todos los demás de dicho archivo se demoran menos de 20, solo el test que tomó más tiempo será considerado incorrecto, pero todos los demás estarán correctos. Da lo mismo si ese test incorrecto fue el primero que se revisó o el último.... Para que no se preocupen de que si 1 test está incorreto, los siguientes ya se dejan de revisar, eso no pasará.
> 
> Ojalá haya quedado más claro asi

Hola,
Aquí no me queda clara la definición de test, por ejemplo, ¿un test es literalmente el test "TestVotosValidosLocal" o es cada uno de los test que va dentro de ese test?
