### ISSUE TITLE
Error al conectar señales entre clases dentro de otra clase que las ejecuta

### ISSUE THREAD

**Issue by gicrot** [IIC2233/syllabus#368]
Hola, me explico. Tengo dos clases creadas, la ventana de juego y el backend de esta, en un metodo de una clase creada en el main que es iniciado si es que se ingresa un mapa correcto. Con esto todo en orden. 

Mi problema, es que al momento de hacer un connect entre las señales de una clase (ventana de juego o su backend) y con la funcion que la recibe respectivamente, este no las conecta respectivamente. Por ejemplo, al poner prints en distintos lugares, donde se hace el emit lo muestra, pero en la funcion que lo recibe no muestra el print de ese lugar, dando a entender que nunca se accedió a esa función. 

Llevo mucho rato buscando el problema y según yo es que los tengo a ambas partes (frontend y backend) en un método de una clase y no directamente en el main, pero sin esto no se como abrirlo correctamente.

**Comment by nabenitez** [comment]
Hola!, 

Te recomiendo revisar la Actividad de Interfaces Gráficas, en ```main.py``` se muestra como se crean las instancias de Backend y Frontend, además de cómo se conectan las señales entre ambas clases. Asegúrate de que los ```emit``` envíen la información a métodos que existen en el Backend.
No es necesario que ambas instancias se creen en un ```main.py```, la misma lógica del archivo ```main.py``` puede ser agregada a una clase.

comenta si pudiste solucionarlo o si sigues teniendo problemas!,
Saludos!

**Comment by gicrot** [comment]
Mi problema es que estoy basandome en esa actividad e incluso revisé en las ayudantias 4 y la extra para mi tarea, y solo en esta situación no me funciona. Tengo otras señales fuera de esa clase en el mismo main que funcionan (conecta otra ventana con otro backend), pero este caso en la clase no me funciona.

Parto mi programa (ventana incial) dentro del main, y con una señal conecto a la clase que inicia el juego por medio de un metodo para que inicie el frontend y su backend, donde esto me funciona. Pero en el mismo metodo conecto las señales a las funciones que las reciben respectivamente, pero nunca llegan a actuar estas pese a hacer un emit.
No se si se entiende :(

**Comment by nabenitez** [comment]
Es difícil encontrar una solución sin ver directamente el código. Por lo que te pido que subas esta versión de la tarea a tu repo y así poder guiarte en la solución de este problema.

**Comment by gicrot** [comment]
ok, ahi lo subí, el problema de conexiones está en dccampo.py, y para ver el frontend y backend esta escrito cuales son las funciones que reciben las señales.

**Comment by nabenitez** [comment]
El problema es que **no estás llamando al método que emite la señal de forma adecuada**. Recuerda que primero se debe conectar la señal y luego puedes llamar la función que ejecuta el método **emit()**.
Por último, considera que el programa (ojo en ```dccampo.py```) se lee de arriba hacia abajo.
Con lo anterior deberías poder solucionar el problema.

**Comment by gicrot** [comment]
Muchas gracias, creo que ya entendí mi problema!
