### ISSUE TITLE
[UnicodeEncodeError] Actividad Bonus 

### ISSUE THREAD

**Issue by namadatzis** [IIC2233/Syllabus#368]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! En la parte II, en la función  obtener_habilidad_info me aparece error al obtener la respuesta.json()  (siendo respuesta el GET de la url)

![image](https://user-images.githubusercontent.com/26422815/146000471-3f6930a5-80d5-43ad-9225-431e60646a61.png)

Busqué en internet y logré obtener la info pero ahora me la entrega en bytes, no en dict como lo hace json. El problema es ahora para pasarlo a dict no sé como hacerlo ya que la única forma que se me ocurre y que he encontrado es con json (loads, encode, etc) pero vuelvo al problema original, por lo que pido ayuda para arreglar el error del UnicodeEncodeError de otra forma y así poder continuar.

Ya subí el código que realicé a mi repo, gracias!

**Comment by namadatzis** [comment]
Edit. Después de probar mil soluciones, lo estaba corriendo en VSC, lo corrí en consola usando .json() y funcionó. Por lo visto es error del VSC y ni idea cómo arreglarlo por lo que seguiré probando por consola

**Comment by tocococa** [comment]
Hola @namadatzis, puede ser que tengas una `ñ` o vocal con tilde en alguna parte? Probablemente el encoding que estás usando no incluye esos carácteres.
