### ISSUE TITLE
comentarios y vocabulario: Mayus-minus

### ISSUE THREAD

**Issue by aamedinaj** [IIC2233/Syllabus#368]
Hola,
al pre procesar comentarios ¿debemos considerar las palabras 'bot' de vocabulario talcual? ¿o la palabra puede venir alteradas mezclando mayúsculas y minúsculas?
en otros términos, ¿"My"=="my"=="mY"?

salu2

**Comment by marioreinike** [comment]
Hola, aparte de la duda de mi compañero, tengo la duda de si hay que revisar que una palabra de vocabulary.txt, para que esté dentro de un comentario, debe estar "sola" dentro de él (por ejemplo: la palabra "para" no pertenecería a "paraverbal"),  o se puede considerar, que la palabra de vocabulary.txt simplemente aparezca dentro del comentario, sin importar que esté dentro de otra?

**Comment by Pipelao** [comment]
Hola @marioreinike 
Tú pregunta se responde en #325 
Saludos
PD: No soy ayudante

**Comment by Clemente24** [comment]
No se responde en esa issue... La duda es si tenemos que considerar las mayúsculas y minúsculas de las palabras del vocabulary.txt.

Es decir, por ejemplo;
hated está dentro del vocabulario, ¿tenemos que buscar también (HaTeD, hateD, Hated, etc...) dentro de los reviews?

**Comment by AntoniaChristensen** [comment]
@IchottMano por favor contestar!! que hacemos con las mayusculas?? (Tanto para la parte del bot como para procesar los comentarios como positivos o negativos)

**Comment by IchottMano** [comment]
@aamedinaj @AntoniaChristensen Disculpen 😅 pensé que se habia respondido la issue

Sobre la pregunta, cuando uno procesa los comentarios de una persona, no importa si las letras son mayúsculas o minúsculas, ya que sabemos que las escribió alguien real. Sin embargo, el bot no es alguien real, por lo que sigue estrictamente con las mayúsculas entragadas.

Saludos!

**Comment by naquiroz** [comment]
@IchottMano Creo que hay una contradicción de esto, con la issue #383
