### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by vicenterodas** [IIC2233/Syllabus#368]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Estoy intentando poner el audio cuando se gana o pierde pero no funciona. No lanza ningún error, simplemente no se escucha nada. (no es un problema de volumen).
Este es el código.
ruta = os.path.join('sounds', 'stageClear.wav')  
player = QMediaPlayer()
url = QUrl.fromLocalFile(ruta)
content = QMediaContent(url)
player.setMedia(content)
player.play()
Estas las librerías importadas correctamente. Gracias

**Comment by tomastrivino** [comment]
Yo tuve que usar path absoluto para arreglarlo (con os.abspath())

**Comment by MaxAl100** [comment]
> Yo tuve que usar path absoluto para arreglarlo (con os.abspath())

Tomás, te cuento que ocupar paths absolutos cuenta como **descuento**, así que te recomiendo encontrar otra manera de resolverlo

**Comment by tomastrivino** [comment]
> > Yo tuve que usar path absoluto para arreglarlo (con os.abspath())
> 
> Tomás, te cuento que ocupar paths absolutos cuenta como **descuento**, así que te recomiendo encontrar otra manera de resolverlo

@MaxAl100 Hola, lo que me comentas se contradice con lo que me dijo el profe en [este link](https://github.com/IIC2233/Syllabus/issues/290#issuecomment-1555942196)

Gracias igual :D

**Comment by MaxAl100** [comment]
> > > Yo tuve que usar path absoluto para arreglarlo (con os.abspath())
> > 
> > 
> > Tomás, te cuento que ocupar paths absolutos cuenta como **descuento**, así que te recomiendo encontrar otra manera de resolverlo
> 
> @MaxAl100 Hola, lo que me comentas se contradice con lo que me dijo el profe en [este link](https://github.com/IIC2233/Syllabus/issues/290#issuecomment-1555942196)
> 
> Gracias igual :D

aa ya excepcionalmente en este caso sí se permitió, pero en general **no se recomienda**
Muchas gracias por la pronta respuesta 😃 (y por enviar el link 😉)

**Comment by vicenterodas** [comment]
> > > Yo tuve que usar path absoluto para arreglarlo (con os.abspath())
> > 
> > 
> > Tomás, te cuento que ocupar paths absolutos cuenta como **descuento**, así que te recomiendo encontrar otra manera de resolverlo
> 
> @MaxAl100 Hola, lo que me comentas se contradice con lo que me dijo el profe en [este link](https://github.com/IIC2233/Syllabus/issues/290#issuecomment-1555942196)
> 
> Gracias igual :D

Estoy haciendo lo siguiente y no me funciona, no arroja error, simplemente no suena . Alguna idea?

player = QMediaPlayer()
ruta = os.path.abspath(os.path.join(*parametros.PATH_AUDIO_VICTORIA))       
url = QUrl.fromLocalFile(ruta)
content = QMediaContent(url)
player.setMedia(content)
player.play()

He buscado en internet pero no encuentro otra forma. Gracias

**Comment by Hernan4444** [comment]
Hola @vicenterodas 

Si el código que muestras es el que utilizas en tu tarea, el problema es que pyqt5 **necesita siempre** que sus objetos queden guardados en memoria. Ya sea en un atributo (self.player) o en una estructura de datos que es un atributo (self.players = []).  En otro caso, una vez finaliza la función que crea a player, esta variable deja de existir y pyqt5 elimina todo rastro de ella. Intenta guardar una referencia de ella en memoria para ver si eso soluciona el problema.

Saludosヾ(＾-＾)ノ

**Comment by vicenterodas** [comment]
> Hola @vicenterodas
> 
> Si el código que muestras es el que utilizas en tu tarea, el problema es que pyqt5 **necesita siempre** que sus objetos queden guardados en memoria. Ya sea en un atributo (self.player) o en una estructura de datos que es un atributo (self.players = []). En otro caso, una vez finaliza la función que crea a player, esta variable deja de existir y pyqt5 elimina todo rastro de ella. Intenta guardar una referencia de ella en memoria para ver si eso soluciona el problema.
> 
> Saludosヾ(＾-＾)ノ

Solucionado. Gracias!
