### ISSUE TITLE
Generar Archivo

### ISSUE THREAD

**Issue by NoemiCC** [IIC2233/Syllabus#368]
Hola, tengo una duda sobre la parte de guardar en la tarea. Entiendo que cuando se hace click en el botón "Generar Archivo" se tienen que guardar los resultados de las consultas en el archivo resultados.txt, pero que pasa si una consulta se repite? Osea si en una ejecución anterior ya se izo la misma consulta se vuelve a guardar el resultado?

**Comment by Arcoirisky** [comment]
Lógicamente sí. Puedes hacer una consulta A una vez, luego la B, la C, etcétera. Y luego volver a hacer la A. Por lo que debería de guardarse nuevamente la consulta A
