### ISSUE TITLE
Más comandos para las funciones booleanas

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2233/Syllabus#368]
¡Hola!
Llegando a la parte de booleanos me di cuenta que los comandos tienen kurtosis, coeficiente de asimetria y otros que no son definidos en la tarea. ¿Debo implementarlos de todas formas identificando la distribución a la que pertenecen los datos? ¿para eso no debería primero asignarlos a una distribución? En caso de que no se hayan asignado a ninguna distribución ¿debería de lanzar un error?

**Comment by Dunkan1** [comment]
no, se les paso a los ayudantes

**Comment by Dunkan1** [comment]
solo hay que hacer que funcionen con estos ("LEN", "PROM", "DESV", "MEDIAN", "VAR")

**Comment by Hernan4444** [comment]
#309
Saludos!!
