### ISSUE TITLE
Movimiento continuo personaje

### ISSUE THREAD

**Issue by miortiz1** [IIC2233/syllabus#369]
Existe algun problema de que al apretar una tecla el personaje se mueva en esa direccion? pasando Entremedio de 2 casillas( cambiando el sprite y no moviendolo diractamente a la otra), pero que lo haga si o si terminar el movimiento dentro de una casilla?

**Comment by jmwielandt** [comment]
Hola!

El personaje no tiene ningún tipo de restricción en cuanto a las casillas. Como estamos evaluando la implementación de los dos tipos de movimiento (continuo y restringido por casillas), no puedes hacer que el personaje termine justo en una casilla si el jugador dejo de presionar una tecla antes o después.
