### ISSUE TITLE
Python 3.5 para evitar problemas de PyQt

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#369]
Hola, en esta tarea nuevamente hay problemas con PyQt (importar QWidgets) 

Para la tarea 2 nos permitieron usar Python 3.5. 
Para esta tambien podemos usar este?

**Comment by sebacruzd** [comment]
Hola,

Si puedes usar Python 3.5

Saludos!

**Comment by Kitaps** [comment]
Gracias
