### ISSUE TITLE
Duda votos_validos y votantes_validos_por_distritos

### ISSUE THREAD

**Issue by oliviallanosj** [IIC2233/Syllabus#369]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola tengo una duda sobre las dos funciones mencionadas (votos_validos y votantes_validos_por_distritos). Hice la función correctamente, pero se demora demasiado tiempo en correr, de hecho en ambas, el ultimo test no termina nunca. Hice git push del codigo en mi repositorio donde se puede ver el codigo en detalle. Si me pueden ayudar. Estuve investigando cual podría ser el motivo de la tardanza pero no lo logré. Muchas gracias :)

**Comment by jfpantoja** [comment]
Hola @oliviallanosj!
Estuve revisando tu caso para la función ```votos_validos``` y posiblemente se trate de un problema por uso de memoria, debido a que como se utilizan datos grandes, guardar estos datos en estructuras como listas o diccionarios te usarán mucha memoria de tu computador y se demorará mucho en correr. Te recomiendo que trates de abordar estos casos con generadores (creados por funciones como map, reduce, filter) para optimizar el funcionamiento y mejorar los tiempos.
