### ISSUE TITLE
Sintaxis de métodos en Diagrama de Clases

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#369]
al interior de los paréntesis de los métodos del diagrama de clase deben estar escritos los parámetros que recibe el método?. De ser así, los parametros se escriben por su nombre que se encuentra escrito en el programa o por el tipo de objeto que representa. Lo otro, en la parte de los atributos se debe escribir el tipo de atributo, por ejemplo 'energia: int'. Sin embargo no me queda muy claro como se debe escribir cuando es una lista de objeto. En la sección de contenidos sale escrito como 'equipo = Jugadores[]' , pero en los ejercicios propuestos sale escrito como 'equipo = list[Jugadores]

**Comment by retamalcito** [comment]
¡Hola @enriquemolinare!

En cuanto a tus primeras dos preguntas, sí, en los paréntesis de cada método deben estar especificados los **tipos** de los parámetros que recibe (por ejemplo, `int`, `bool`, etc.). Recuerda que también debes especificar el tipo de los parámetros que retorna el método (si no retorna nada, se coloca `None`).

En cuanto a la sintaxis de las listas en el diagrama, ambas opciones que mencionas son correctas, por lo que puedes elegir la que más te acomode o se te haga más clara. Personalmente te recomendaría la segunda (`equipo = list[Jugadores]`), ya que es más explícita en lo que quiere representar.

Espero haber solucionado tu duda, ¡saludos! 👋

**Comment by enriquemolinare** [comment]
buenismo, muchas gracias.
