### ISSUE TITLE
Problema con pelicula "we, the screenwriter"

### ISSUE THREAD

**Issue by akrebs2** [IIC2233/Syllabus#369]
Hola. Cuando se instancian las películas, ocurre un error con la película "we, the screenwriter" (linea 89 del database grande). El error ocurre porque el titulo está separado por comas, por ende, .split(",") lo separa en dos elementos distintos de la lista. Tendremos que modificar el código para que acepte este tipo de formato (no es tan trivial aceptar ese formato ocupando programación funcional)?
Podrán cambiarlo a ";"?
:)
Saludos!

**Comment by llloyola** [comment]
Hola! Según yo, los títulos de película que contienen "," no presentan ningún problema si investigas un poco como procesarlos. Saludos!

Pd: No soy ayudante
Hint: Recuerda que puedes importar el módulo csv

**Comment by IchottMano** [comment]
@akrebs2 Hola!

Efectivamente es como lo dice @llloyola 😄 

Saludos!
