### ISSUE TITLE
avance T02

### ISSUE THREAD

**Issue by mgbriones** [IIC2233/syllabus#369]
el avance para la tarea 2 es de carácter obligatorio?

**Comment by DCCollao** [comment]
Hola!
 No es obligatorio, pero como se menciona en el enunciado, te permite optar por hasta 2 décimas en tu nota **final** si lo haces, por lo que es muy recomendado que lo hagas! Además entregaremos un feedback general que podría serte de ayuda para hacer mejor el resto de tu tarea.

Éxito!
