### ISSUE TITLE
Duda limites de valores

### ISSUE THREAD

**Issue by ByDati** [IIC2233/Syllabus#369]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holaaa, una consulta... al realizar el filtro de valores para el archivo "plantas.txt" y obtener cuales son las lineas correctas, es necesario que pongamos un filtro nuevamente en la clase Plantas para que los valores se encuentren en los rangos? En teoria, siempre vendrán 6 lineas validas con todos los atributos dentro de los rangos, entonces lo veo medio innecesario (quitando el caso de algunos que se pueden modificar durante el programa y eso si debo aplicarles condiciones.
Gracias de antemano :D

**Comment by rodrigoaguilera15** [comment]
Hola, es parte de la tarea que ustedes decidan qué atributos de las plantas deben ser properties y cuáles no. Así que si tú crees que no es necesario para ciertos atributos, no lo hagas, con tal que el programa funcione como se pide. Mucho éxito, saludos.
