### ISSUE TITLE
Fiscalizacion de critaturas que se escaparon hoy.

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#369]
Hola,
tengo la siguiente duda: ¿Cuando se pasa al día siguiente y se fiscaliza, se consideran las criaturas que se escaparon/enfermaron ese mismo día o solo las que ya estaban?

Saludos!

**Comment by aljara97** [comment]
Hola @Ignacioislae!

La fiscalización corresponde a los eventos ocurridos en en el día actual, por tanto, no debes hacer fiscalizaciones por las criaturas que se escaparon o enfermaron en días anteriores. 

Suerte en tu tarea 🧙‍♂️

**Comment by Ignacioislae** [comment]
¿Pero si una criatura todavía no la recupero o sigue estando enferma, pasa la fiscalizan también o no?

**Comment by aljara97** [comment]
No necesariamente, ya que, las multas se aplican a eventos que **ocurren en el día correspondiente**, por tanto, puedes cobrar la multa el día en que la criatura se escapa, el día en que la criatura se enferma y cuando alcanza el nivel mínimo de salud.

**Comment by CamilaArgomedo** [comment]
hola! sobre este mismo tema tengo la duda si debo fiscalizar por cada criatura que se escapa/enferma/saludbaja o solo una vez máximo por cada una de esas razones aunque se escape/enferme/saludbaja mas de una criatura
