### ISSUE TITLE
Obtener la habilidad en inglés (Actividad Bonus)

### ISSUE THREAD

**Issue by Francisco-Aguilera-xd** [IIC2233/Syllabus#369]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Hola! en la actividad bonus se nos pide obtener la descripción de la habilidad en inglés y se nos da la pista de ("name": "en"). No entiendo muy bien que se tiene que hacer con el ("name": "en") ni tampoco como lograr obtener la descripción en ingles, porque cuando reviso qué descripción estoy obteniendo está como en alemán.
Gracias de antemano

**Comment by igbasly** [comment]
Hoola @Francisco-Aguilera-xd!

Te recomiendo imprimir la respuesta de la API o lo contenido en `"effect_entries"` y ahí analizar cómo te puede ayudar lo mencionado en el enunciado 😉

Saludos!

**Comment by Francisco-Aguilera-xd** [comment]
Vale, muchas gracias!
