### ISSUE TITLE
Duda columnas y variables

### ISSUE THREAD

**Issue by cho19** [IIC2233/Syllabus#369]
Hola!

¿Es un input valido poner una variable dentro de una columna? Dicho de otro modo con un ejemplo: asigno `x=10` y ejecutan `["PROM", [0, 5, "x"]]`, ¿retorno `argumento invalido` o `5`?

Gracias!

**Comment by Hernan4444** [comment]
@cho19 es totalmente valido. Por definición `Columna`  representa un conjunto  de datos numéricos (todos con el mismo tipo: int o float) y tener una variable dentro de la columna el cual representa un numero es completamente valido mientras sea del mismo tipo .. .columna de float solo puede tener variables asociadas a float, en caso contrario se genera un error.

Por lo tanto tu programa debe ser capaz de reemplazar las variables por sus datos correspondiente al momento de extraer una columna de un csv (solo si existe la variable) o al recibir una lista como en tu ejemplo. En caso de no existir la variable en ese momento, debes generar un error.

Saludos!

**Comment by cho19** [comment]
@Hernan4444 Muchas gracias!

**Comment by acrojas2** [comment]
Hola:
Entonces en un csv se puede dar el caso que en una columna los datos sean por ejemplo:
-> 1, 2 ,3,  "x", "y", 34, ...., 45, ...
y que en la lectura del archivo el programa tiene que remplazar "x", "y" por sus respectivos valores si es que en x e y están  asignados valores mismo tipo  que los  de la columna ... (?)
Saludos :B

**Comment by Hernan4444** [comment]
exactamente!! :+1: 
Lo que si pueden suponer que la variable siempre estará entre comillas dobles ("") tal como es en las consultas.

Saludos!!

**Comment by acrojas2** [comment]
hola: 
las funciones que reciben como argumento columnas: pueden ser generadores que vienen necesariamente  de extraer_columna(?), y listas o sets vienen necesariamente de las consultas que se ingresan por la interfaz (?). Puedo asumir todo lo que dije anteriormente (?)
Saludos :B

**Comment by acrojas2** [comment]
Hola: (agrego a la pregunta anterior):
Respecto al edit, se refieren a que no harán algo como "123" en el csv y que haya que pasarlo a 2 (?), o sea,  donde haya que reemplazar por el valor correspondiente siempre tendrá como nombre algo solo con letras ("x" = 10) (?)
Saludos :B

**Comment by maxfreymo** [comment]
¿Será conveniente generar un archivo que vaya guardando las variables o me estoy complicando de más y existe alguna manera menos engorrosa?

**Comment by stgoa** [comment]
y si la variable es una consulta o una columna o un None??

**Comment by acrojas2** [comment]
Hola (agrego a mis dos preguntas anteriores):
Si me ingresan una lista como esta: [1, 3, 5, 5.6, 6] debo generar un error(?)
Si me ingresan una lista como esta: [1, 3, 4, "x"] y x es un float debo generar un error (?)
Saludos :B

**Comment by Hernan4444** [comment]
@acrojas2 puedes asumir eso *pero* que esa lista tambien puede venir escrita en el archivo consultas.json aunque eso no debería ser ninguna diferencia para tu programa.
sobre el edit es exactamente lo que dices, no pondremos "123" como variable, estas tendrán letras que evidencien que son variables pero si pueden ser letras con numero, ej: "var_01", "var_02", "var_03"
@maxfreymo recomiendo revisar algunas issues anteriores donde se insinuan formas de guardar las variables (hint: init)
@stgoa si la variable es una consulta se guardará lo retornado, si es una columna se guarda la columna para ser usada en otras funciones y si es None, simplemente guardas un None y si esa variable se ocupa en otra parte generará error de tipo.

**Comment by Hernan4444** [comment]
@acrojas2 exactamente, en ambos casos no se cumple la condición de que una columna (o lista en este caso) tiene solo un tipo de dato.

Saludos!

**Comment by akaminetzkyp** [comment]
@Hernan4444, ¿por qué una columna no puede tener valores de distintos tipos?

**Comment by Hernan4444** [comment]
@akaminetzkyp porque definimos que una columna puede ser una columna de csv y que estos cumplen la condición de solo tener un tipo de dato. Para ser consecuentes con eso, optamos que una columna solo acepte un tipo de dato.

**Comment by cho19** [comment]
@Hernan4444 y eso en funciones donde se comparan/usan dos columnas o una columna y un numero (sea int o float) influye? A lo que voy: si tengo una columna de ints y le sumo un float con operar a cada una, ¿debiera lanzar error o la columna con floats? ¿Y si quiero graficar dos columnas de distinto tipo? ¿O compararlas? Gracias!

**Comment by Hernan4444** [comment]
Ahí no debería influir porque al operar todos los datos pasarán a ser del mismo tipo (float generalmente), al comparar estamos comparando el resultado de una operación (ejemplo: promedio de ambas y ahí comparar 3.4 con 3 no es un problema) y en graficar tampoco porque al hacer dos columnas estamos creando puntos en un gráfico.
Resumen: no influye, solo al momento de analizar variables dentro de columna

**Comment by cho19** [comment]
@Hernan4444 buenísimo, gracias!

**Comment by maxfreymo** [comment]
Entonces @Hernan4444 ¿es legal ocupar una clase para almacenar variables?

**Comment by Hernan4444** [comment]
@maxfreymo por como está hecha la tarea, no puedes crear clases para trabajar con RQL, lo que si se permite es usar el init de la interfaz para crear alguna variable (Ej: alguna EDD vista en el curso) que te sirva para lo que tu quieras.

**Comment by B-Dominguez** [comment]
Algo que no me queda 100% claro después de re-leer esto y me quiero asegurar: En las columnas del csv pueden venir los datos como numeros o como variables entre "", pero no como consultas, o sí?

**Comment by Hernan4444** [comment]
@B-Dominguez asi es!! puedes suponer que no vendran consultas solo numeros o variables entre comillas **que representan a un numero**.

Saludos!
