### ISSUE TITLE
parametros.py en .gitognore

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#37]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

¿El archivo parametro.py debe estar en .gitignore?

**Comment by Maxy15** [comment]
Hola Fernanda1232123! No es necesario que uses .gitignore en esta tarea, pero si lo deseas, puedes colocar el archivo de parámetros de todas maneras, ya que es el mismo para todes les estudiantes. Espero te sirva 😸
