### ISSUE TITLE
Class methods en la tarea

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2233/syllabus#37]
Hola, se pueden usar @classmethods en la tarea?

**Comment by iqacevedo** [comment]
Hola!

Esto no es necesario para realizar esta tarea. De todas maneras, ¿puedes explicarnos por qué necesitas ocupar esto?, en base a tu respuesta evaluaremos permitirlo o no.

Saludos !

**Comment by JJJGGGG** [comment]
Tenia una pequeña idea para utilizarlos, pero lo resolví de otra forma. Muchas gracias de todas formas
