### ISSUE TITLE
Numero de bestias - Enunciado

### ISSUE THREAD

**Issue by pedrozavalat** [IIC2233/Syllabus#37]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### **¿Cuál es la cantidad mínima y máxima de bestias que debe haber en el tablero?**

Hola, estaba viendo la parte de la cantidad de bestias que requiere el tablero, en donde se utiliza la formula
 N = [largo * ancho * Prob_bestia ( 10 / 66)], pero no entiendo si esta cantidad "N" indica la cantidad minima de bestias que debe haber según esa formula o el total de bestias. 

Ya que, en el ejemplo que se muestra en el enunciado, en la sección de puntajes, el tablero es de tamaño 6 x 6, y tiene una cantidad total de N = 11 bestias. Sin embargo, bajo la lógica de la formula, la cantidad exacta de bestias serian N = 6 * 6 * (10 / 66) = 6 (aproximado al entero maximo mas cercano). Por ello, no entiendo cual es finalemente el valor de la cantidad bestias necesarias que debe presentar el tablero :(

**Comment by drcid98** [comment]
Hola! La fórmula para N indica la cantidad **exacta** de bestias que debe tener el tablero, pero esto siempre depende de qué valor tenga el parámetro PROB_BESTIA. En el ejemplo que se muestra, no se especifica el valor de este parámetro, lo que se menciona más adelante es el valor que se entrega en el archivo `parametros.py`, pero para el ejemplo se debió haber usado otro valor. Saludos!
