### ISSUE TITLE
Dudas sobre supuestos (bombas)

### ISSUE THREAD

**Issue by Fopazov** [IIC2233/Syllabus#37]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. Son dos preguntas:
a) - - -
    t 2 2
    - - -
 En este caso, ¿el alcance de las dos bombas es 4? ¿o las celdas ocupadas por bombas también bloquean a las demás?

b) ¿Dos bombas pueden afectar a la misma celda?
- - -
- 2 -
- 2 -
¿Las dos bombas afectan a la celda (0,1) ? 

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Fopazov** [comment]
En la pregunta b el tablero es el siguiente:
b) - - - 
b) - 2 - 
b) - 2 -

**Comment by Hernan4444** [comment]
Hola @Fopazov 

Recomiendo revisar esta issue #24 donde tambien se tocó tu problema y se dió solución. Si quedas con más dudas, puedes hacerla en esa issue para mantener dudas del mismo tema en una única issue.

Saludos c:

**Comment by Fopazov** [comment]
vale, gracias!
