### ISSUE TITLE
Abrir un path

### ISSUE THREAD

**Issue by pahaeussler** [IIC2233/Syllabus#37]
Hola, estaba tratando de abrir un archivo de la forma
with open(base_path+path, "r") as infile:
Para no utilizar como base_path la ruta completa (C:\Users\User\Documents\....) si mal no recuerdo se utiliza "./".
Lo probé utilizando sublime y no tengo ningún problema, en cambio en Atom se me cae el programa:
FileNotFoundError: [Errno 2] No such file or directory: *

**Comment by jfbahamondes** [comment]
"./" debería funcionar siempre y cuando el archivo cuya dirección es base_path+path esté en la misma carpeta que el módulo que se ejecuta. Incluso debería funcionar sin el "./". Si es que no está en la misma carpeta se debe agregar la ruta completa.

**Comment by pahaeussler** [comment]
Gracias, si lo hacia probado sin el "./" pero tampoco me funcionó en Atom, pero si en Sublime.
Estoy confundido, ¿por que un mismo programa puede funcionar en Sublime pero no en Atom?
