### ISSUE TITLE
Problema con abrir archivos mediante visual studios

### ISSUE THREAD

**Issue by rifibla** [IIC2233/syllabus#37]
Hola, sucede que al abrir el archivo "usuarios" mediante visual estudios este no reconoce el archivo, pero si ejecuto el mismo comando con IDLE este si logra abrir el archivo.
El método que utilizo para abrir los archivos es de forma: 
`with open(path) as file_name:
    file = `file_name.readlines()``
cabe mencionar que el el archivo "usuarios" está en en la misma carpeta en donde utilizo esta el archivo python que ocupo para tratar de abrir este archivo.

**Comment by DCCollao** [comment]
Hola @rifibla!

¿Podrías subir pantallazos de lo que te sale al intentar ejecutarlo en vscode?
Quedo atento!

**Comment by rifibla** [comment]
Hola @DCCollao  acá
![pantallazo](https://user-images.githubusercontent.com/62026552/76823215-297f6380-67d9-11ea-835a-6243faee0d41.png)
![pantallazo](https://user-images.githubusercontent.com/62026552/76823219-2be1bd80-67d9-11ea-9e60-25abab715ba7.png)

 va el pantallazo

**Comment by Tito0906** [comment]
Holaa! Si el problema sólo se te presenta con Visual Studio es posible que sea el mismo problema que se presentó en esta issue: [https://github.com/IIC2233/syllabus/issues/22](url) .

**Comment by DCCollao** [comment]
Tal como dice @Tito0906, lo más probable es que tu problema se haya tratado en la issue #22.
De todas formas, para ver en dónde se está ejecutando la consola de vscode, puedes intentar utilizar el módulo `os` de python, junto a su método `getcwd()`. Si dicho método no retorna la carpeta donde se encuentran tus archivos `.csv`, tienes un problema de paths (que puedes arreglar también utilizando `os.getcwd()`)

Quedo atento!

**Comment by rifibla** [comment]
muchas gracias @Tito0906 y @DCCollao con el procedimiento del issue #22 logre abrir el archivo.
