### ISSUE TITLE
Duda Archivos CSV

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#37]
Hola!

Tengo una duda con respecto al segundo párrafo del punto 4.1. En el enunciado se dice lo siguiente:

> Cabe destacar que en el formato csv el orden de las columnas puede variar.

Esto se refiere que a nuestro programa va a tener que usar archivos CSV con las columnas sin un orden establecido? Por ejemplo, que el archivo pueda ser "nombre, tipo, comentarios" o "tipo, nombre, comentarios".

Saludos!

**Comment by FernandoPieressa** [comment]
Es tal como dices, no hay un orden establecido, por lo tanto su programa debe ser capaz de funcionar con cualquier orden de columnas.

Saludos!

**Comment by akaminetzkyp** [comment]
Gracias Fernando!
