### ISSUE TITLE
Duda sobre cantidad de lineas en archivos .py

### ISSUE THREAD

**Issue by JorgeGuzz** [IIC2233/Syllabus#37]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Respecto a esta parte del enunciado:
![imagen](https://user-images.githubusercontent.com/80768853/131230944-1d0b7a50-2238-4ed3-b118-a926899ab417.png)

**¿Se consideran #comentarios y líneas vacías dentro de las 400?**

**Comment by Maxi1805** [comment]
Hola @JorgeGuzz.
Si, tanto los comentarios como las líneas vacías se consideran dentro de las 400 líneas por archivo, sin embargo es recomendable que no se acerquen a este numero a no ser que sea totalmente necesario, porque por un lado es mas difícil para ustedes organizarse o encontrar error, y por el otro dificulta la correcta corrección a los ayudantes. Como recomendación antes de empezar a programar todo, crea una serie de archivos especializados en lo que crees que vas a necesitar :)
