### ISSUE TITLE
diagrama de clases

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#37]
importa si para hacer el diagrama de clases se usan flechas con puntas negras en vez de blancas para denotar la herencia?

Gracias!

**Comment by stephichau** [comment]
@rihanuch sí, importa! La punta negra significa dependencia y la blanca herencia
saludos :)

**Comment by rihanuch** [comment]
gracias! existe alguna programa para macOS que permita hacer os diagramas en vez de usar ppt?

**Comment by stephichau** [comment]
te recomiendo [esta pagina](https://www.draw.io/), pero si quieres un programa descargable puedes encontrar alguno [acá](https://www.google.cl/search?q=uml+diagram+mac+os&oq=uml+diagram+mac+os&aqs=chrome..69i57j0l2.5470j0j7&sourceid=chrome&ie=UTF-8).

**Comment by tcgarrido** [comment]
@rihanuch Te recomiendo "astah professional".

**Comment by Sforrego** [comment]
@stephichau algunos tips para usar draw.io (cosas que no estan a la vista y que podrian ser muy utiles)? :)

@tcgarrido "Astah professional" es pagado o no?

**Comment by cfernandez9** [comment]
se puede hacer a mano y escanearlo o sacarle foto??

**Comment by tcgarrido** [comment]
@Sforrego Para estudiantes es gratis! http://astah.net/student-license-request

**Comment by ifcarrera** [comment]
@cfernandez9 Te recomiendo usar alguno de las aplicaciones mencionadas anteriormente. Hacerlo a mano podría ser muy enredado al momento de la corrección y se podría bajar tu nota por error (por algo que no se haya entendido, por ejemplo).

**Comment by rakarachon** [comment]
El diagrama se debe subir en algún formato en específico?

**Comment by akaminetzkyp** [comment]
Puede ser cualquier formato que no necesite algún programa especial para abrirlo (pdf, jpg, etc.). :)

**Comment by rakarachon** [comment]
ok, gracias!!

**Comment by cfernandez9** [comment]
@ifcarrera muchas gracias!!
