### ISSUE TITLE
Invitación a Repositorio Nuevo

### ISSUE THREAD

**Issue by alvaritions** [IIC2233/syllabus#37]
estoy dando este curso por segunda vez y no sé como hacer lo del repositorio, ya que tengo el de la vez anterior y no sé si hacer lo del formulario como si nada. ¿Tengo que borrar mi repositorio anterior? y si es así ¿Cómo lo hago?.
Saluross.

**Comment by lily416** [comment]
Hola @alvaritions,

Aunque tengas el repositorio del semestre pasado, debes rellenar el [formulario que se mando](https://forms.gle/6zqtyppKy3p9YC6Y6), ya que para cada semestre se genera un nuevo repositorio por estudiante (si te fijas en el nombre de tu repositorio personal sale el año y semestre en que rendiste el curso).

Además, te recomiendo que no borres tu repositorio anterior, ya que tus tareas y actividades del otro semestre te pueden ser de utilidad en este semestre o a futuro.

Saludos y que tengas una buena semana 👋✨

**Comment by cronda1** [comment]
hola! si mi numero de alumno termina en J que numero ingreso al formulario? me dice que "No es un número de alumno válido"

**Comment by lily416** [comment]
Hola @cronda1,

¿Me podrías dar tu número de alumno? Es para comprobar la razón por la que falla y poder corregirlo.

**Comment by cronda1** [comment]
si, el numero es 1863964J

**Comment by lily416** [comment]
@cronda1, cuando pongo tu número de alumno no me sale ningún problema:
![image](https://user-images.githubusercontent.com/26393515/90455943-6c65a000-e0c5-11ea-9078-0abcb0a74f2f.png)

Fíjate que no estés poniendo espacios antes o después de tu número de alumno.

**Comment by cronda1** [comment]
faltaba la letra mayuscula 😄 gracias!
