### ISSUE TITLE
Utilización de contenidos y orden

### ISSUE THREAD

**Issue by juanesjeep** [IIC2233/syllabus#37]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

**¿Es recomendable usar todos los contenidos de la semana  para los ejercicio propuestos?**

Se tiene que usar solo el contenido visto para ese punto por ejemplo en esta semana (la 01) no usar args en el ejercicio de listas y tuplas, o es recomendeble usar toda la materia de la semana en todos los ejercicios de la misma si importar el orden de estos claro que piorizando los que se practican en el ejercicio para practicarlo todo en conjunto.

**Comment by aerotecnia99** [comment]
Hola!
La idea es que en los ejercicios propuestos uses el contenido que se está practicando, claro que avanzando en el curso tendrás que ir utilizando todo lo aprendido. Si crees que puedes optimizar tu aprendizaje incorporando otros puntos de la semana en un ejercicio también puedes hacerlo.
Espero haberte ayudado ヽ(•‿•)ノ
