### ISSUE TITLE
Duda acerca de la lista de los mejores atacantes (Actividad Bonus)

### ISSUE THREAD

**Issue by Francisco-Aguilera-xd** [IIC2233/Syllabus#370]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Hola!
En la actividad bonus, cuando se pide entregar una lista de los 5 mejores atacantes, pero esta lista de qué es? Es de los nombres de los pokemones, los diccionarios de cada pokemon o alguna otra cosa?
Quedo atento a su respuesta.

**Comment by igbasly** [comment]
Hola @Francisco-Aguilera-xd ✌️ 

Cuando se dice "los 5 mejores Pokémon" se refiere a los objetos de Pokémon que tienes inicialmente, es decir, del mismo tipo que los recibidos en la lista argumento `pokemones`.

Saludos!

**Comment by Francisco-Aguilera-xd** [comment]
Ok, muchas gracias!

**Comment by igbasly** [comment]
Efectivamente, ese ejemplo estaría incorrecto, puedes ignorarlo 👍
