### ISSUE TITLE
Problemas git 

### ISSUE THREAD

**Issue by fernandovegauc** [IIC2233/syllabus#370]
hola ! tengo dos problemas con git :(
1) No me funcionó el .gitignore  por lo que quiero borrar todo lo del repositorio para volver a subir mis archivos pero no encuentro como hacerlo.

2) al intentar agregar algo al respositorio me aparece este mensaje:
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

Ojalá me puedan ayudar, gracias !

**Comment by nabenitez** [comment]
Hola @fernandovegauc!,
1.- Intenta utilizando ```git rm name``` donde ```name```es el nombre del archivo que quieres eliminar, esto eliminará el archivo localmente y hará que git detecte que este archivo ya no se encuentra, debes hacerlo para cada archivo que quieras remover y además la **terminal** debe estar en el directorio donde están los archivos que deseas eliminar. 
Luego, una vez que haz quitado todos los archivos es necesario que hagas *commit* y *push*, así estos elementos serán quitados del repositorio remoto. 
Por último, ahora puedes subir tu ```.gitignore```haciendo referencia a las cosas que no quieres subir.
**NOTA**: al hacer ```rm```remueves de forma permanente tus archivos, por lo que te recomiendo copiarlos en alguna parte.

2.- Corre ```rm -f .git/index.lock``` en la terminal en el directorio de tu repositorio local. Si no funciona, vuelve a comentar acá.

Quedo atento!,
Saludos!

**Comment by fernandovegauc** [comment]
hola, intenté partir por el punto 2 pero me aparece esto :(
![Captura](https://user-images.githubusercontent.com/53880431/66059505-8381ba80-e512-11e9-8854-eefaf4ecf203.PNG)

**Comment by nabenitez** [comment]
Prueba con **del** en vez de **rm**, creo que ese es el comando en Windows. 
Dime cómo te va!
