### ISSUE TITLE
problema type()

### ISSUE THREAD

**Issue by maxfreymo** [IIC2233/Syllabus#370]
Hola mi problema es que type me esta retornando la clase del dato y no el tipo que es.
Ejemplo:
print(type(3)) 
En mi programa retorna esto:   <class 'int'>
Pero yo quiero que me retorne esto:  <type 'int'>
¿Qué ocurre?

edit: creo que encontré la respuesta aquí http://stackoverflow.com/questions/35958961/class-vs-type-in-python  Entonces, ¿ahora debería ocupar type(x).__name__?

**Comment by Hernan4444** [comment]
@maxfreymo la respuesta que encontraste está bien pero si intentas en python type(x).name te entregará un error. Te recomiendo leer lo de este [link](http://stackoverflow.com/questions/510972/getting-the-class-name-of-an-instance-in-python) para complementar tu respuesta 

Saludos!

**Comment by maxfreymo** [comment]
Jajaja eso fallé en la escritura es type(x).__name__  por si alguien más lee esto :D
