### ISSUE TITLE
Largo de una funcion

### ISSUE THREAD

**Issue by mora4** [IIC2233/Syllabus#370]
Hola,

En el enunciado dice que no se puede exceder un largo de 15 lineas por función, pero que pasa si tengo funciones chicas dentro de una funcion más grande? No puedo exceder las 15 lineas dentro de cada función chica o dentro de la función total?

Gracias!

**Comment by IchottMano** [comment]
@mora4 Hola!

Debes tener presente que **ninguna** función puede exeder las 15 líneas, por lo que si tu compones una función grande, esta no puede tener mas de 15 líneas, independiente de las funciones que la compongan, es decir, si hay funciones mas pequeñas llamadas dentro de tu función no agregan líneas extras.

Saludos!

**Comment by akrebs2** [comment]
@IchottMano creo que no quedó tan claro, este ejemplo estaría bien?:

Si una función tiene 16 lineas, contando las lineas que tienen sus funciones interiores, está bien o mal?

Lo otro, si necesita ocupar un salto de linea (por PEP8) debido a que una linea es muy larga, este salto de linea se considera como una segunda linea o es parte de la anterior?

**Comment by Hernan4444** [comment]
@akrebs2 está mal, son 15 líneas máximo. Lo único que no se considera son las líneas que no tienen código (están en blanco o con comentarios). Si tienes más de 15 debes justificar en tu README el porqué tienes es necesario ocupar más del permitido.

Sobre tu segunda pregunta, se cuenta como segunda línea. En caso contrario podrían hacer todo en prácticamente una línea y tampoco es la idea.

Saludos ✌️

**Comment by IchottMano** [comment]
@mblejeune Hola!

Eso estaría bien.

Saludos!
