### ISSUE TITLE
librería json

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#370]
![image](https://user-images.githubusercontent.com/53887845/92399680-12bf2700-f101-11ea-8e65-84d5e38b3d60.png)
Hola!, esta librería aparece como prohibida y su nombre me aparece en esta parte de vsco, existe problema con eso?

**Comment by retamalcito** [comment]
¡Hola @Margarita-Paz!

El archivo `json` que te aparece corresponde a las configuraciones del editor de texto, las que se guardan en un archivo de este tipo. No te preocupes, ya que esto no tendrá impacto en tu entrega 😅. Lo importante es que no importes ni utilices la **librería** `json` en tus módulos.

¡Saludos! 🥇

**Comment by Margarita-Paz** [comment]
aah comprendo, gracias !! 😄
