### ISSUE TITLE
Confusión entre simular_nueva_hora y avanzar_barcos

### ISSUE THREAD

**Issue by Piolawa** [IIC2233/syllabus#370]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

No entiendo que implementar en simulacion_nueva_hora(), si todo su programa es está en el método de la clase Canal, avanzar_barco()

**Comment by manearaya** [comment]
Hola @Piolawa!

En el método de avanzar barcos del canal se llevan a cabo todas las acciones descritas en el enunciado cuando se simula una nueva hora (sección 4.2.3). Por lo tanto, al simular una nueva hora ese es el método que debería encargarse de hacerlo.

En el enunciado no se menciona que tengas que crear un método con el nombre que mencionas (quizás me puedes indicar en qué parte del enunciado se entiende eso para entender mejor de donde viene tu duda). De todas formas podrías crear uno si te ayuda con el flujo de tu programa, pero no es necesario. Lo que debe estar es la opción de simular una nueva hora en el menú de acciones.

Espero que te haya ayudado, quedo atenta cualquier duda!

**Comment by Piolawa** [comment]
muchas gracias, me quedó claro c:
