### ISSUE TITLE
Acceder a atributos de clase

### ISSUE THREAD

**Issue by Ed0ss** [IIC2233/syllabus#370]
Hola, para implementar la pausa del juego creé un evento en la clase enemigo que es compartido por todas las instancias, así, al pausar hago set() del evento y todos los enemigos quedan en pausa, pero para hacer esto debo acceder a la clase directamente y no sé si eso es algo que se pueda.

Saludos!

**Comment by gatochico** [comment]
Hola! Revisando tu código, no hay problema alguno con lo que hiciste para pausar a los enemigos, ya que está bien hecha la conexion front/backend y es válido cambiar atributos de clase de esa forma 👌 Saludos y éxito!!
