### ISSUE TITLE
Duda lectura archivos con programación funcional

### ISSUE THREAD

**Issue by bimartinez** [IIC2233/Syllabus#370]
Hola!

Tengo una duda respecto a como es la manera correcta de leer archivos con programación funcional?, ya que hasta ahora la única manera que tenía entendido para leer archivos era con `readlines` o de la siguiente manera:
``` 
with open... as file:
    for line in file:
        do_something
```
Y en la actividad me recalcaron que estas maneras eran extremadamente lentas e ineficientes.

Saludos!

**Comment by santi95** [comment]
+1

**Comment by naazocar** [comment]
Revisa la ayudantía de funcional, creo que ahí salía

**Comment by bedefrunner** [comment]
No estoy seguro de que esto sea efectivamente mas eficiente, pero funciona!
```
    with open ... as file:
        #generador con todas las lineas del archivo
        lines = (line for line in file.readlines())  
```
Eso sí, se puede iterar solo una vez sobre los generadores, así que aprovecha bien lo que hagai con él

**Comment by indonoso** [comment]
Hola!

Cuando abres un archivo usando un context manager `with open(path) as file:` o de la forma tradicional `file = open(path)` lo que están haciendo es obtener un *generador* sobre las líneas del archivo. Hacer esto:
``` python
with open(path) as file:
        lines = (line for line in file.readlines())  
```
es super ineficiente porque `file` ya es un generador, no es necesario obtener otro generador con todas las líneas. Si el archivo que van a leer pesa 10 GB, es muy probable que el computador no aguante y la ejecución del programa se pare en esa sentencia. Una de las cosas que es buena del código de arriba es que si salimos del scope del *context manager*, declarado con la sentencia `with` podemos leer el archivo igual.  Por ejemplo, esto:
``` python
with open(path) as file:
    print('Abrimos el archivo') 
    lines = map(func, file)
print(list(lines))
```
Les entregará el error `ValueError: I/O operation on closed file.`. Esto ocurre porque cuando salen del scope de la sentencia `with` el archivo se cierra y por lo tanto ya no lo pueden leer. En el primer código ya se leyó el archivo (en la sentencia `file.readlines()`) por lo que no dependen del archivo.  El siguiente código **sí** funcionará ya que estamos usando el generador para obtener las líneas mientras sigue estando abierta la conexión con el archivo.

``` python
with open(path) as file:
    print('Abrimos el archivo') 
    lines = map(func, file)
    print(list(lines))
```
Una forma eficiente, sin tener que usar `readlines()` y poder leer desde el archivo igual, es abrir y cerrar los archivos una vez que hayan sido leídos. Por ejemplo:
``` python
with open(path) as file:
    # Hacemos todo lo relacionado con la lectura del archivo. 
    # Guardamos todo lo necesario en variables del programa.
# Usamos lo que haya generado la lectura del archivo
```
``` python
file = open(path)
# Hacemos todo lo relacionado con la lectura del archivo. 
# Guardamos todo lo necesario en variables del programa.
file.close()
# Usamos lo que haya generado la lectura del archivo
```

**Comment by bimartinez** [comment]
Me quedo super claro! gracias!!!
