### ISSUE TITLE
Duda nombres de jardines en archivo jardines.txt

### ISSUE THREAD

**Issue by moizefala1** [IIC2233/Syllabus#371]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! resulta que en el archivo "jardines.txt" hay uno llamado : "5x5_ponteciado", es un typo?, o se supone que así se llama el jardín? desde ya muchisimas gracias ! :3

**Comment by UnFedaykin** [comment]
Hoola! El jardín, en efecto, se llama así. A pesar de ser un posible typo, "5x5_ponteciado" sigue representando el nombre de un jardín. 

Por otro lado, recuerda que tu código se enfrentará a un archivo de jardines.txt que puede que no tenga los mismos nombres de jardines que el jardines.txt con el que estás desarrollando el código. Dado esto, tu código debe ser capaz de enfrentarse a cualquier nombre de jardín y archivo de jardines.txt. Éxito en la tarea!
