### ISSUE TITLE
¿Se puede agregar al init de la clase T03Window?

### ISSUE THREAD

**Issue by paula-ds** [IIC2233/Syllabus#371]
Por ejemplo para agregar un self.personas = [a,b,c] que me será útil para llamar a mis funciones?

**Comment by rihanuch** [comment]
me sumo a la pregunta ademas de preguntar si se puede agregar 1 función a la clase T03Window 😬

**Comment by stephichau** [comment]
No se puede. 
Saludos!

**Comment by rihanuch** [comment]
@stephichau cual cosa, las funciones o el init?

**Comment by rihanuch** [comment]
O ambos?☹️

**Comment by TomasSalvadores** [comment]
Ninguno se puede 👍🏻

**Comment by nmaturana97** [comment]
y se le pueden agregar atributos no necesariamente desfe el init? por ejemplo definir self.lista en el modulo de la consulta?

**Comment by Hernan4444** [comment]
@nmaturana97 tampoco puedes hacere eso. porque es lo mismo que agregar atributos pero desde otra funcion.
