### ISSUE TITLE
Funcion evaluar

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2233/Syllabus#371]
Quiero asegurarme de estar leyendo bien. Dice _"Dada una función creada por el comando crear funcion, se evalúa función desde inicio hasta final a intervalos de intervalo. Retorna los resultados."_ En la última parte, cuando dice resultado**s** ¿se refiere a una lista de evaluar la funcion o simplemente a la suma de esa integral?

**Comment by Hernan4444** [comment]
@Arcoirisky a una lista de evaluar la función.
Saludos!

**Comment by Arcoirisky** [comment]
¿Entonces no considero el desfase?
Me explico: En la funcion de probabilidad, si mi intervalo empieza en 3, ese f(x) con x = 3 es distinto si es que comienzo de 0. Porque las problabilidades se van sumando. ¿se entiende?

**Comment by Hernan4444** [comment]
Vamos por un segundo intento porque no entendí lo que quieres decir :c

**Comment by Arcoirisky** [comment]
#Casi
Una funcion de probabilidad se supone que va siempre en aumento, con el objetivo de llegar a 1 empezando de 0. Entonces, en la parte de evaluar se suman (aunque en realidad es una integral) de las f(x) con x entre el intervalo que te dan. 
Por ejemplo: si mi f(x) = x  y la evalúo de 0 a 5 entonces quedaría 
[0, 1, 3, 6, 10, 15]
[0, (1+0), (2+1+0), (3+2+1+0), (4+3+2+1), (5+4+3+2+1)]
porque la probabilidad de x = 3 no es sólo lo que la función da como resultado, sino que viene en conjunto a todo el resto de xs que pasaron.

Entonces, mi duda es si mi función llegara a empezar de 3 a 5 quedaría:
[3, 7, 12]
[3, (4+3), (5+4+3)] 

ó

**considero el desfase** (todo lo que corresponde a antes del tres) que en este caso es 3 (que es f(x) de 0 hasta 3) para que me quede [6, 10, 15] como corresponde al iniciar desde 0

¿Mejor o peor?

**Comment by Hernan4444** [comment]
1) Lo que tu dices que siempre va en aumento es la función acumulada pero las formulas que te damos son de la función densidad.
![image](https://cloud.githubusercontent.com/assets/15641721/25567659/3461e996-2dc9-11e7-93f7-19163cae3cad.png)
En la imagen, la función en  azul es la de densidad (y que creas con la formula que les damos) y la rosada es la acumulada.

Por lo tanto evaluar lo que hace al final es dar un rango de inputs y toma el output de la función sin asociar un desfase o la suma de los otros conjuntos.

**Comment by Arcoirisky** [comment]
oooooooh, entonces es literalmente el nombre de la función. evaluar los f(x) y tirar la lista [f(x=1), f(x=2), etc] Gracias!

**Comment by monicabelen** [comment]
Si el inicio y el final son iguales entonces el resultado debe ser la función evaluada una sola vez?

**Comment by Hernan4444** [comment]
@monicabelen asi es
Saludos!
