### ISSUE TITLE
Duda uso de for (caso particular)

### ISSUE THREAD

**Issue by ciquezada** [IIC2233/Syllabus#371]
Hola, me surgen algunas dudas con respecto al uso correcto de un for para efectos de la tarea, si quisiera recorrer un par de listas para comparar sus valores y si ocurre algo levantar un error y nada mas que eso (si no levanta error se termina el ciclo sin hacer nada mas), ¿Esta permitido?

**Comment by Arcoirisky** [comment]
Hola c: Busca entre las issues abiertas. Sé que hay una que responde a tu pregunta uwu)

**Comment by ciquezada** [comment]
#347 Esto es lo mas parecido que pillé y solo para estar seguro de que entendí bien, entonces podría hacer eso, y el raise sería como la function(x) que ahí se menciona?

**Comment by Arcoirisky** [comment]
Casi. Mira, las únicas excepciones que debe levantar tú programa son las del enunciado. Al hacer lo que postulas en la pregunta entras en el caso de la issue #329 
Y eso no está permitido. 

Lo que quieres hacer se puede con funcional O: ¡investiga un poco más sobre eso! Porque existe c:

**Comment by ciquezada** [comment]
Ah, pero lo que la persona quiere hacer es, que si no puede aplicar la funcion elevar la exepcion, capturarla y agregar el elemento a la lista.
Lo que yo queria hacer era algo como un decorador check_type() como en la actividad 06, que pueda verificar el tipo de input, pero en ningun momento agregar algo a nada, y la excepcion que levante seria el wronginput que sale en el enunciado.
Se puede verificar el tipo con un funcional para luego levantar una excepcion?

**Comment by Arcoirisky** [comment]
Vale, mira O:
Lo que quieres hacer sí se puede verificar con funcional 🙈como hint, eso es combinando: filter, type y any🙊

pero tambien es posible de tu forma si lo que quieres hacer es algo del estilo:

for element in algo:
    check_type(element, type)

Ahí check type verifica que el elemento sea de ese type o haces raise de `WrongInput`. Porque, tu función no está retornando algo para una lista y no estás interactuando con una estructura de datos O: por eso se puede c:

¿Mejor ahora?
