### ISSUE TITLE
respuesta de obtener habilidad (actividad bonus)

### ISSUE THREAD

**Issue by FGarciaVarela** [IIC2233/Syllabus#371]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Tengo una duda con la respuesta de la actividad bonus en el apartado de "obtener habilidad". Deberíamos retornar como respuesta un diccionario con todo lo descrito en el ejemplo ( ablity: {... etc} ), o retornar el diccionario con el código "200" está bien?

Saludos!

**Comment by igbasly** [comment]
Hoola @FGarciaVarela :v:

No estoy seguro si te refieres a la función `info_api_curos` o a la función `obtener_info_habilidad`.
En ambos casos en el enunciado se indica que se debe retornar un diccionario con la información respectiva.

Saludos!
