### ISSUE TITLE
Error QProgressBar

### ISSUE THREAD

**Issue by Brocoleta** [IIC2233/syllabus#371]
Hola, tengo una QProgressBar para la base, la cual se va actualizando cada vez que se le hace daño a la base, el problema es que cada vez que se le hace daño el programa se cae o me sale el error: **QObject::setParent: Cannot set parent, new parent is in a different thread**, llevo mucho rato tratando de solucionarlo, pero sigo sin saber por que ocurre.

**Comment by gatochico** [comment]
Hola! Podrías subir a tu repo la versión de tu código donde te aparece el error? Revisando tu código, la unica progress bar que veo es para la ronda.
Se me ocurre que es debido a que creaste un objeto (en este caso, la progress bar) fuera del thread que quieres ejecutar, y luego lo mueves a dicho thread, provocando el error. Quizá crear la progress bar directamente en la clase/thread en que quieres que esté desde un principio podría ayudar?
Sería genial si pudieras dar más detalles de tu problema. Saludos!!
