### ISSUE TITLE
Funcion ganadores por distrito

### ISSUE THREAD

**Issue by IsidoraCarmona** [IIC2233/Syllabus#371]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, al ejecutar los tests de la función ganadores_por_distrito me tira que ese es el output del test_3 , lo cual no me hace sentido ya que solo hay 3 distritos entre las opciones entregadas en el test por lo que deberian ser maximo 3 entregados o no? , no se si estoy entendiendo mal la idea de la función o esta malo el test

**Comment by cstappung** [comment]
Hola @IsidoraCarmona!
Primero que todo, perdona la demora. En la función `ganadores_por_distrito`, si bien el nombre hace alusión a retornar los ganadores, la función lo que busca es que retornes el ganador entre todas las combinaciones posibles entre los candidatos de un mismo distrito. Por ejemplo, si se postulan A, B, C, en el Distrito 1. Se espera que retorne el ganador entre (A, B), (A, C), (B, C). Espero que esto pueda aclarar tu duda.
