### ISSUE TITLE
Ingreso de barco al simular hora

### ISSUE THREAD

**Issue by juanesjeep** [IIC2233/syllabus#371]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### ¿Es obligatorio ingresar un barco al Ingresar al simular hora?

Tengo la duda de que al el enunciado decir que "a lo mas uno de los barcos" significa que de se puede no ingresar un barco.
¿esto no abriria la posibilidad de que se pueda solo pasar las horas sin gastar dinero? al no seleccionas ningun barco y por lo tanto no pagar la mantencion.

**Comment by santiagovegaf** [comment]
Hola!

Es correcto lo que dices, el usuario puede no ingresar barcos al canal!
