### ISSUE TITLE
Archivos Zone.Identifier

### ISSUE THREAD

**Issue by espeescobar** [IIC2233/Syllabus#372]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Debo poner en el gitignore los archivos Zone.Identifier?
Tueve que hacer la tarea en un computador que no es el mio ya que en el mio no funcionaba PyQt en Ubuntu ni Windows. Al mandar los archivos de ese computador al mio se descargaron todos con una versión *[nombre]: Zone.Identifier*, y aun que los borre se subieron a github a hacer el commit y push. Los debo ignorar en el git.ignore? Y si es asi, como lo hago?

**Comment by ignacio-sp** [comment]
Hola @espeescobar, se recomienda ignorar ese tipo de archivo, para esto, basta con agregar `*Zone.Identifier` a tu .gitignore. Luego, como los archivos ya se encuentran subidos al repositorio, los tienes que eliminar para que puedan ser ignorados, para esto puedes ver [esta issue](https://github.com/IIC2233/Syllabus/issues/137#issuecomment-1703080864), saludos!

**Comment by espeescobar** [comment]
Gracias, pero los archivos Zone.Identifier se subieron igual
