### ISSUE TITLE
Duda extra señales

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#372]
Hola en la siguiente parte del código

![image](https://user-images.githubusercontent.com/47841749/58301123-326af880-7db3-11e9-9658-6ed8c2237514.png)

Que es lo que hace exactamente el QTimer con los respectivos métodos timeout y start?

**Comment by Hernan4444** [comment]
Hola

El método `timeout ` es como una señal que ejecuta la función a la que está conectada cada vez que pasa el tiempo indicado en start
El método `start` le dice al `Qtimer` cuanto tiempo esperar antes de emitir la señal `timeout`.

Con eso, está pasando que el `Qtimer` espera 50 milisegundos y hace emit de la señal `timeout`, lo cual implica ejecutar `self.food_creator`.

Saludos :v:
