### ISSUE TITLE
Funciones con ñ y tildes

### ISSUE THREAD

**Issue by fjaraneda** [IIC2233/Syllabus#372]
Hola, resulta que si puedo leer sin problemas archivos que tengan ñ o tildes, pero para poder crear funciones para las consultas que tengan los mismos nombres que hay en las consultas.json no me deja crearlas con nombres con ñ o tildes.

**Comment by Hernan4444** [comment]
@fjaraneda recuerda que las consultas son leidas por el main.py mientras que tus funciones son creaciones tuyas de **tu** librería. Por lo tanto no es necesario que tengan precisamente el mismos nombre (o mismos argumentos).

Saludos ✌️

**Comment by rihanuch** [comment]
por ejemplo si utilizo hasattr() y no uso mis funciones con ñ o tildes lo pongo en el readme nomas?

**Comment by Hernan4444** [comment]
@rihanuch podrías explicar un poco más tu uso de `hasattr` que me suena a uso de clases pero talvez estoy estoy equivocado

**Comment by rihanuch** [comment]
@hernan4444 jajajaja no, no uso clases, pero llamo desde `main.py` a mi archivo `consultas` y obtengo la funcion del modulo de la forma 
`funcion = hasattr(func, nombre)`

**Comment by Hernan4444** [comment]
@rihanuch entonces si, está todo bien 👍 y por si acaso especifica esto mismo en el readme 😄 

Saludos ✌️
