### ISSUE TITLE
Funcion asignar

### ISSUE THREAD

**Issue by josemlira** [IIC2233/Syllabus#372]
Hola!, si en el programa se realiza la consulta: 
['asignar', 'x', 'a'] 
es lo equivalente a hacer: x = "a" (como un string)? o el programa debiese buscar la variable 'a' (antes definida) y asignarle a 'x' su valor? 
Y el caso de que 'a' no estuviese antes definida que pasaría? 
Saludos!

**Comment by Hernan4444** [comment]
@josemlira primero busca la variable "a", en caso de no existir, la considera como un string. 
Nota: si después creas una variable llamada "a", "x" no se verá afectado porque el tiene guardado un string.

Saludos!

**Comment by josemlira** [comment]
Muchas gracias!!
