### ISSUE TITLE
¿Es necesario definir un nuevo método para Presentarse?

### ISSUE THREAD

**Issue by ByDati** [IIC2233/Syllabus#372]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, vi issues similares, pero no iguales y tenia la duda si es que si o si debemos implementar Presentarse como un metodo o ya queda listo con modificar el __str__ de la clase jardin para cuando lo printeemos
Graciaaas

**Comment by rodrigoaguilera15** [comment]
Hola, la respuesta es que el método presentarse descrito en el enunciado **es** el método __str__ sobrescrito. No hay necesidad de definir un método nuevo.

**Comment by ByDati** [comment]
muchas graciaaas
