### ISSUE TITLE
¿Es legal usar recursión?

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#372]
Hola, 
Quería saber si era legal usar unciones recursivas para realizar acciones.
Y se puede usar sys.setrecursionlimit en caso de que 998 niveles no alcancen?

(Si en algunos casos se puede y en otros no, podrían especificar?)

Gracias :smile:

**Comment by IchottMano** [comment]
@jmwielandt Hola!

Si es legal usar funciones recursivas, sin embargo no puedes usar setrecursionlimit ya que eso fácilmente podría provocar problemas en el computador de la persona que correrá tu código.

Saludos!
