### ISSUE TITLE
Requisitos del reporte de movimientos

### ISSUE THREAD

**Issue by juanesjeep** [IIC2233/syllabus#372]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### ¿Que tan especifico tiene uno que es en el reporte de movimientos?

hay que solo decir el dinero ganado y racuadado en general en la hora o especificar por cada barco lo que se gasto o gano con ese barco

**Comment by mistico0121** [comment]
A pesar de que es más o menos libre, les sugerimos que sea un reporte detallado. Es mejor para nosotros a la hora de corregir, y para ustedes a la hora de debugear. Mientras más cosas nos damos cuenta que tienen buenas, mejor para su puntaje:

Ejemplo: Tienen 1 cálculo malo, no sabemos cual es el barco que causa el problema, el dinero es solo un total y nada mas, tienen 0 o pocos puntos por mal cálculo. Si sabemos que solo 1 barco está generando el problema, podemos darles puntos por todo lo que tienen bueno. 


Saludos
