### ISSUE TITLE
Feedback Tarea 0

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#372]
Hola! Sé que entregamos hace muy poco tiempo la tarea 0 pero quería preguntar si ya saben cuándo entregarán las notas o algún feedback? Para no tener los mismos errores en la tarea 1

**Comment by kalarconvl** [comment]
@gatochico ?

**Comment by gatochico** [comment]
Hola @kalarconvl !

Cuando una issue está asignada, esto significa que ya estamos trabajando en ella. Te pido un poco de paciencia y en cuanto tenga las fechas confirmadas contestaré a la brevedad 🤓 .

**Comment by kalarconvl** [comment]
@gatochico Gracias!

**Comment by gatochico** [comment]
Ahora sí @kalarconvl , lamento la demora:

Como curso, tenemos **15 días hábiles** para tener las evaluaciones corregidas. Lamentablemente para la Tarea 00 esto caerá durante el feriado de fiestas patrias/semana de descanso, que no cuentan como días hábiles así que se aplazaría hasta finalizada la semana de descanso 😞 Además, esta semana estaremos priorizando la corrección de los **avances** una vez ustedes los entreguen, por lo que tampoco podemos apurar la corrección de la T00. 

En resumen: Las notas de la T00 estarán de vuelva de la semana de descanso, pero esta semana nos esforzaremos por tener los avances corregidos lo más rápido posible para que tengan feedback de su tarea actual. De todos modos, si tienes dudas respecto a malas o buenas prácticas/descuentos/etc., que quedaron de la T00, puedes hacer una issue y trataremos de responder a la brevedad 🤓 

Espero entiendas y Éxito en tu semana!
