### ISSUE TITLE
Duda con Git

### ISSUE THREAD

**Issue by tocococa** [IIC2233/syllabus#372]
Tengo un problema con git y VSCode, y es que por lo menos un par de veces al día, cuando hago push, me pide mis credenciales de GitHub nuevamente, ¿esto es un comportamiento normal o no debiese estar ocurriendo?

**Comment by KnowYourselves** [comment]
Hola @tocococa!

En que sistema operativo estas programando?

Quedo atento!

**Comment by tocococa** [comment]
Hola! Windows 10.

(~ー~,)

**Comment by KnowYourselves** [comment]
Esto sucede porque git necesita saber tu usuario y contraseña para poder hacer push a un repositorio privado. Usualmente en windows debería salirte una pantalla de git preguntando por usuario y contraseña y de ahí no debería salir más.

Si es que este no es tu caso, prueba haciendo este comando `git config credential.helper store` lo que estaría haciendo esto es diciendole a git que guarde las credenciales que utilices y no las pregunte más.

**Comment by tocococa** [comment]
Sep, me ha aparecido la pantalla, pero lamentablemente me sale bastante seguido.
Puse el comando que mecionaste, así que ahí voy a ver que pasa, gracias!

**Comment by lily416** [comment]
Hola @tocococa, ¿funcionó lo que te recomendó @KnowYourselves?

**Comment by tocococa** [comment]
Hola @lily416 , parece que si, aunque no esoty seguro. Tengo la sospecha que pasaba cuando cambio de adaptador de red en el PC y no me ha vuelto a pasar desde que puse el comando. Es bien errático cuando aparece y cuando no, así que solo me queda seguir avanzando con la tarea y esperar a ver si vuelve a pasar.

**Comment by lily416** [comment]
Okis. Por mientras voy a dejar la _issue_ como resuelta, si vuelves a tener problemas, comentalo acá mismo 😉 

Saludos y éxito en la tarea 👋🧙
