### ISSUE TITLE
Problema con ultima actualizacion de ponderadores

### ISSUE THREAD

**Issue by piacereceda** [IIC2233/Syllabus#372]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Al hacer git pull con los últimos cambios, mi computador ya no reconoce los tildes o carácteres especiales solo del archivo ponderadores, ya que los demás los lee correctamente (si tengo en encoding de 'latin-1'). 
¿Saben por qué pudo haber pasado eso?, considerando que antes no tenía ningún problema al respecto. 

Muchas gracias de todas formas.

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Hola! Tengo el mismo problema :c

**Comment by mpiavf** [comment]
Hola !
Gracias por avisar, fueron actualizados nuevamente. 
Saludos!

**Comment by francorreaandrades** [comment]
Hola!! Es normal que me sigua fallando?? 
No paso el test_base_cargar_datos.py porque me falla al cargar los ponderados

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Hola! En el mismo contexto del cambio de los archivos de ponderadores, no se deberia cambiar este numero en el test de carga de datos? Ya que ese valor sigue contando a los que estaban repetidos.

![imagen](https://github.com/IIC2233/Syllabus/assets/162501853/bf503f6e-7290-4a7f-9109-8c9f0c72e4ab)

**Comment by francorreaandrades** [comment]
Además, al intentar correr el test test_20_votos_validos.py me arroja este error siendo que antes pasaba todos menos los últimos 3 por error en el encoding, ahora me dice:
<img width="941" alt="Captura de pantalla 2024-05-21 a la(s) 12 45 23 a  m" src="https://github.com/IIC2233/Syllabus/assets/134115560/29eb9886-d8a6-475d-8dac-c1ba16dc9a2d">

Como lo puedo arreglar??

**Comment by mpiavf** [comment]
Hola !
Actualizaremos los archivos y mencionaremos los cambios!
Disculpen los percances, avisaré cuando todo esté en orden.
Saludos!

**Comment by francorreaandrades** [comment]
Muchas gracias!!

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Muchas gracias!!

**Comment by mpiavf** [comment]
Todo los archivos corregidos!
Gracias y buenas noches!
