### ISSUE TITLE
Discrepancia con resultados de ejemplo

### ISSUE THREAD

**Issue by Bneya** [IIC2233/Syllabus#373]
Dentro de los archivos que nos pasaron, fui probando las consultas que aparecían en **contultas.json** para ver si e entregaban los mismos resultados que los obtenidos en **resultados.txt.txt**. (Asumiendo que las respuestas de **resultados.txt.txt** eran a las consultas de **consultas.json* en orden).

El problema, es que hay al menos un resultado que me entrega diferente:

Para la consuta
> ["pariente_de", 1, "Tomas Salvadores]

El resultados correspondiente en orden es 
>Alejandro Kaminetzky
>Sterling Archer
>Stephanie Chau

Pero mi programa no entrega que Alejando Kaminetzky sea pariente de grado 1

Según el enunciado, un **pariente de grado 1** debe tener, entre otras cosas, **La misma forma de a nariz**, pero mi programa reconoce que **Tomas Salvadores tiene nariz respingada** mientras que **Alejandro Kaminetzky tiene nariz aguileña**.

Revisé manualmente la cuenta de los genes y la determinación para ambos parece estar correcta.

Entonces, ¿mi programa está leyendo mal los genes o existe una discrepancia, en este caso al menos, entre el resultado de ejemplo esperado y el resultado real obtenido?
¿o simplemente **resultados.txt.txt** no son necesariamente las respuestas a **consultas.json**?

**Comment by Hernan4444** [comment]
#363
