### ISSUE TITLE
Estructura de datos en una función generadora

### ISSUE THREAD

**Issue by benjadaza** [IIC2233/Syllabus#373]
En el enunciado se dice que crear estructuras de datos sin aplicar compresión y fuera de un reduce esta prohibido. Por otro lado, en las issues se dice que se puede si es en una función generadora. Mi duda entonces es, se puede crear una estructura de datos en una función generadora pero sin aplicar compresión y fuera de un reduce?

**Comment by TomasGMDC** [comment]
@benjadaza tal y como aparece en el ejemplo 4 de estructuras de datos:

#339 

Se puede hacer lo que dices, es decir, crear una estructura de datos dentro de una función generadora, a pesar de que no se aplique comprensión o esté dentro de un reduce. Ojo eso sí, debe ser una función generadora. Revisa la parte de cosas prohibidas/estructura de datos de ese mismo comentario para notar algunos casos incorrectos.
