### ISSUE TITLE
MEDIAN

### ISSUE THREAD

**Issue by aeperalta** [IIC2233/Syllabus#373]
Hola!

Para la mediana, en el enunciado dice: "Puede suponer que al solicitar la mediana, la columna ya estará ordenada.".
La pregunta es si la tengo que ordenar yo antes de que se ingrese a la mediana (que sin pasar por una lista se hace bastante complicado) o solo probarán esa consulta con una lista/generador ordenado?

**Comment by Hernan4444** [comment]
@aeperalta con ese supuesto es que ustedes no tienen que ordenar la lista aunque esté desordenada,  simplemente nos retornan el dato de al medio.
Saludos!!

**Comment by aeperalta** [comment]
Gracias, saludos!
