### ISSUE TITLE
Entregable menor a 15 lineas?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#373]
Hola, en en el enunciado no dice nada de que el pseudo codigo debe ser de menos de 15 lineas, puede ser de mas?

**Comment by IchottMano** [comment]
@naquiroz Hola!

Si, la restricción sólo se aplica al código que entregues.

Saludos!

**Comment by naquiroz** [comment]
@IchottMano Gracias! Pero si entrego algo mayor a 15 lineas esta mal?

**Comment by IchottMano** [comment]
@naquiroz No.

Saludos!
