### ISSUE TITLE
¿Qué DEBE imprimir Presentarse()?

### ISSUE THREAD

**Issue by ByDati** [IIC2233/Syllabus#373]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tenia la duda respecto a que se DEBE imprimir con presentarse, debemos incluir todo lo del ejemplo o solo el tablero con el inventario de plantas (en este caso no tendriamos que printear temperatura, y las plantas que quedan).
![image](https://github.com/user-attachments/assets/f48501f0-ed5b-4253-bc22-8154c830785f)

**Comment by rodrigoaguilera15** [comment]
Hola, el enunciado solamente exige que Presentarse imprima el tablero y el inventario, así que lo demás es opcional.

**Comment by ByDati** [comment]
yaaa graciaaas
