### ISSUE TITLE
Diagrama de Clase: Metodos Subclases

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#373]
Los métodos de la subclase que se derivan de la superclase pero  que modifican su función  se deben escribir en la sección de métodos de la  subclase? Por ejemplo, el método correr de la superclase hace cierta función. Sin embargo, el metodo correr de la subclase hace algo diferente. Entonces la pregunta es si el método correr se debe escribir en el diagrama de clase de la subclase

**Comment by baosse** [comment]
Holaa Enrique! 
Si el método se deriva de la superclase no es necesario ponerlo en las funciones de la subclase, esto asumiendo que llamarás dentro de la función de tu subclase a la función de tu superclase.  Puedes agregarle lo que sea necesario en la función de tu subclase.
Mucho éxito✨

**Comment by enriquemolinare** [comment]
buenísimo, muchas gracias
