### ISSUE TITLE
ventana fin partida

### ISSUE THREAD

**Issue by martinpena03** [IIC2233/Syllabus#373]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

En el enunciado se indica que al acabar la partida :
"...la ventana se mostrará totalmente en negro, o bien se esconderán los
sprites y se indicará si ganaste o perdiste, junto al nombre de usuario y el sonido respectivo de victoria o
derrota..." ..."debe aparecer un mensaje con el nombre del usuario, el resultado del juego y el
puntaje final. Finalmente, deberá aparecer un botón de ‘salir’ para cerrar el programa."  

Se podria hacer esto en una ventana aparte, que reutilice el fondo del menu? o debe ser en la misma ventana una pantalla en negro?

**Comment by lsilvabw** [comment]
Buenas, tal como se sale en esta issue #292, puedes hacer mas ventanas si es que lo ves necesario.
Saludos!
