### ISSUE TITLE
Duda de si se bloquea totalmente la simulación cuando encalla un barco

### ISSUE THREAD

**Issue by magdalenanario** [IIC2233/syllabus#373]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!  Entiendo que si un barco encalla, en esa misma hora, los barcos que están adelante pueden seguir avanzando y los que están atrás pueden avanzar hasta la posición del barco encallado. Pero en el caso de que, antes de partir una nueva simulación, haya un barco encallado, ¿Los demás barcos que están dentro del canal pueden avanzar? ¿o se bloquearía la simulación completa y no podrían avanzar?

**Comment by santiagovegaf** [comment]
Hola!

En #304 se responde un poco tu duda, donde esta decisión queda a tu criterio (aclarando en tu ReadMe :eyes:).

Suerte!

**Comment by magdalenanario** [comment]
Sii lei esa issue pero entendí que en una misma hora si un barco encalla, los de adelante tienen que seguir avanzando y los de atras queda a nuestro criterio. Pero cuando inicia una nueva hora y hay un barco encallado previamente, también hay que hacer funcionar el avanzar para los que están adelante del barco encallado, o eso queda bloqueado porque desde antes de partir la nueva hora había un barco encallado? 
Mi pregunta al final es que si cuando hay un barco encallado previamente, se bloquea la simulacion completa(tanto ingresar_barco como avanzar)? o solo se bloquea el ingresar_barco?

**Comment by magdalenanario** [comment]
Muchas gracias!
