### ISSUE TITLE
Enunciado dice carpeta Actividades\AB (Actividad Bonus)

### ISSUE THREAD

**Issue by larryuc** [IIC2233/Syllabus#373]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

En el enunciado dice:
"Como mencionado al comienzo de este enunciado, se espera trabajes y entregues en tu repositorio personal,
y en una carpeta nueva llamada AB/ dentro de la carptea Actividades. Se espera que usen los módulos
base siguiendo la misma estructura que en el código entregado, al primer nivel de la carpeta AB/:

Actividades/AB/

Sin embargo en Syllabus esto viene como Actividades\AC Bonus
¿Cual ruta es la que debemos utilizar?

**Comment by igbasly** [comment]
Hola @larryuc :v:

Para entregar la actividad, debes crear una carpeta de nombre `AB` dentro de la carpeta `Actividades/` de tu repositorio personal. Esto es independiente del nombre de la carpeta en la cual se subió la actividad en el syllabus, la cual es un poco más descriptiva.

Espero se entienda, quedo atento a cualquier duda, saludos!

**Comment by Fernanda1232123** [comment]
Hola, 
Estoy buscando como crear una carpeta en mi repositorio privado, pero no me resulta.
Haciendo lo que encontré en StackOverflow para crear una carpeta, creo un file, no una folder.
¿Como lo puedo hacer?
