### ISSUE TITLE
Inventario

### ISSUE THREAD

**Issue by kisco99** [IIC2233/syllabus#373]
Hola! 
Mi problema es que no se me ocurre como crear el inventario de tal forma que al agregar recursos estos vayan a los cuadraditos. Tampoco se me ocurre como dividir el inventario en 3 y agregar los botones para recorrer el inventario. Desde ya, muchas gracias.

**Comment by gatochico** [comment]
Hola!
Las implementaciones del inventario que dimos en el enunciado son solo **ideas** a seguir, para que pudieran tener una imagen menos abstracta de qué cosas pedíamos en cada ventana. Si estás tardando mucho tiempo en esa parte te recomendaría hacer un inventario más sencillo  y que cumpla lo mínimo pedido, en vez de priorizar el aspecto visual.
Ahora, una pista con respecto a los inventarios de ejemplo, sería el trabajar con **muuchos** pixmaps y jugar con todas sus propiedades disponibles. Además, usar designer en estos casos será muy util, ya que hay una parte que muestra una lista de todas las propiedades que tiene un elemento seleccionado :0  
Si tienes alguna duda específica, no dudes en comentar!
Éxito :corn: :man_farmer:

**Comment by kisco99** [comment]
Ok! Y es buena idea hacer en QLabel en cada cuadrado?

**Comment by gatochico** [comment]
No puedo decirte explicitamente si es que es una buena idea o no, pero siempre y cuando **funcione** y **esté manejado correctamente con señales**, todo es válido!

**Comment by kisco99** [comment]
Vale muchas gracias!
