### ISSUE TITLE
Problemas al generar monedas con threads

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#373]
Hola, como dice el titulo, estoy teniendo problemas al hacer start del thread. El juego se crashea:

![image](https://user-images.githubusercontent.com/47841749/58302035-ffc2ff00-7db6-11e9-8d04-cf496658f1bb.png)
![image](https://user-images.githubusercontent.com/47841749/58302042-08b3d080-7db7-11e9-8859-e1e48c31fa7d.png)

Caso 1: Sin hacer start
![image](https://user-images.githubusercontent.com/47841749/58302099-4e709900-7db7-11e9-8b22-117ca35b0c64.png)
![image](https://user-images.githubusercontent.com/47841749/58302118-5cbeb500-7db7-11e9-9f03-53f55e9e768f.png)

Caso 2: Haciendo pass en el run y start en el init (si printe cualquier cosa o pongo cualquier cosa en el run, pasa lo mismo)
![image](https://user-images.githubusercontent.com/47841749/58302060-1c5f3700-7db7-11e9-8071-e1aa4bd9ffad.png)
![image](https://user-images.githubusercontent.com/47841749/58302133-795aed00-7db7-11e9-84c9-1996ab1be840.png)

Tal vez no se logre apreciar, pero en el caso 2 se crashea. Me parece raro, ya que los enemigos los generé muy parecido, ambos basados en el material extra de señales. Alguna idea de cual podria ser mi error?

**Comment by Hernan4444** [comment]
Hola

2 observaciones para que revises y me dices como te va:
1. `generar_modeda()` Crea un objeto que hereda de `QThread` pero este no se guarda en ninguna parte. Un `QThread` no le puede pasar eso, si un objeto de PyQt pierde su referencia (osea, alguna forma de acceder a él), pasan cosas malas
2. El `QThread` es igual que un `Thread` y por lo tanto, el thread finaliza cuando el run se acaba, si no tienes nada ahí, este se ejecuta y en menos de 1 segundo ya finalizó, ahí tiene que poner un `while` con lo que quieres que haga el thread cada cierto tiempo, no olvides el sleep para que el while se ejecute cada un periodo de tiempo que quieras.

Saludos :v:

**Comment by VicenteMerino** [comment]
Gracias, ahora me funciona!
