### ISSUE TITLE
Problema con herencia

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#373]
Hola, tengo el siguiente problema: Tengo una clase en donde defino varios atributos None. Luego creo una subclase que hereda a la clase anterior, y redefino esos valores que eran None en la otra clase como numeros. El tema es que cuando instancio la clase, me define los valores None de la clase que heredo y no los valores que redefinio. Lo raro es que hice lo mismo con otra clase y no tengo ese problema

**Comment by JosefaPaz** [comment]
¡ Hola @Juampisaez !

Te parece subir tu código a tu repositorio, indicarme en qué archivos y líneas está el problema, y ahí ver por qué pasa esta situación?

Quedo atenta, que estés bien!

**Comment by Juampisaez** [comment]
Ya lo pude solucionar, fue un problema de escritura
Gracias!!
