### ISSUE TITLE
Duda uso comando

### ISSUE THREAD

**Issue by JoaquinBocaz** [IIC2233/Syllabus#374]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Muy buenas noches, disculpar las molestias, no obstante me ha surgido una duda respecto a un comando que no pertenece a una librería prohibida pero que al ser no mostrado en los contenidos de clases me genera miedo el usarlo o no, este corresponde al comando "cellPressed()" para grillas, me avisan sino para re-estructurar mi código, desde ya muchas gracias.

**Comment by Hernan4444** [comment]
Hola @JoaquinBocaz 

No hay problema con utilizar ese comando mientras sea de alguna librería permitida. Por ejemplo, si es un método de algún objeto de pyQt5, entonces no hay ningún problema.

Saludosヾ(＾-＾)ノ
