### ISSUE TITLE
Duda Habilidad Especial DCCrotona

### ISSUE THREAD

**Issue by rosariodominguezm** [IIC2233/syllabus#374]
Hola! Es que la habilidad especial de DCCrotona es ganar una medalla y todo lo que implica esta. Pero cuando se gana una medalla se considera como si ganó o solo la medalla? 
Gracias!!

**Comment by jitorcas** [comment]
Hola! @rosariodominguezm 

¿A qué te refieres con 'como si ganó o solo la medalla'?

Cuando la delgación DCCrotona utiliza su habilidad especial se le suma una medalla adicional a su total de medallas y además recibe los beneficios por obtener una medalla.

**Comment by rosariodominguezm** [comment]
Es que ganar una medalla implica que un deportista sube su moral y gana 100 monedas. Eso pasa? O solo aumento el medallero? 
Y otra pregunta, todo los números azules deben ser parámetros o solo los que tienen nombre como PUNTAJE_MINIMO?? 

Por ejemplo los del la formula 


<img width="857" alt="Captura de Pantalla 2020-09-07 a la(s) 13 14 09" src="https://user-images.githubusercontent.com/69605743/92405633-65eaa700-f10c-11ea-8824-7853869d8ce8.png">

**Comment by jitorcas** [comment]
Dado que no se ha especificado en el enunciado, puedes hacerlo como una de las siguiente maneras:

1. Aumentar todos los valores de los atributos asociados a la obtención de una medalla. Podrías elegir un deportista al azar para sumarle/restarle moral.

2. Solo aumentar los atributos de la Delegación: **DCCoins** , **Medallas** y **Excelencia y respeto**

La manera en que lo implementes queda a tu criterio, pero debes mencionarlo en tu `README`.

Con respecto a tu segunda pregunta, dado que está relacionada a la primera te pido abrir una nueva issue para resolverla 🙏 

Mucho éxito! 🥇

**Comment by RafaelEdwards** [comment]
@jitorcas La medalla que agregamos al medallero tiene que ser de una disciplina aleatoria?

Pregunto esto porque en el método "mostrar_estado", se señalan las medallas que tiene cada delegación por deporte.

**Comment by jitorcas** [comment]
@RafaelEdwards 

Dado que no les pedimos que simulen que DCCrotona gane una competencia cuando utiliza su habilidad especial, sería inconsistente agregarla a un deporte al azar, por lo que pediremos que aparezca como categoría por si sola. Puedes poner **medalla habilidad especial** en tu `Mostar estado`.
