### ISSUE TITLE
Dudas Matplotplib

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#374]
Hola!

Tengo un par de dudas sobre Matplotlib.

Primero, cuando llamo `plot`y `show` usando la interfaz gráfica aparece una ventana extra que no se puede mover ni cerrar. Adjunto un pantallazo de la ventana.

<img width="1680" alt="screen shot 2017-04-30 at 4 30 07 pm" src="https://cloud.githubusercontent.com/assets/11022568/25567391/e2f71028-2dc2-11e7-84df-429e4150e4db.png">

Segundo, cuando se llama más de una función `graficar` al mismo tiempo, solo se muestra el primer gráfico. Sin embargo, al correr los comandos por separado (y cerrando las ventanas entre llamados) se abren los gráficos sin problemas. Según lo que he leído, Matplotlib solo puede abrir una ventana a la vez. En el caso que se llame más de un comando `graficar` a la vez, ¿podríamos abrir solo el primer gráfico llamado?

Saludos! 😄

**Comment by Hernan4444** [comment]
@akaminetzkyp no pueden abrir solo el primero porque nosotros queremos ver todos los gráficos que pidamos, pero tal como lo haces tu (de ir cerrando las ventanas del gráfico), eso mismo haremos nosotros si en un set de consultas hay mas de un gráfico. Así que no te preocupes :D vas bien encaminado!!

Saludos!

**Comment by akaminetzkyp** [comment]
Súper! ¿Entonces puedo poner en mi Readme que los gráficos tienen que llamarse uno por uno? :D 

Saludos!

**Comment by Hernan4444** [comment]
@akaminetzkyp mmm que igual nosotros podemos usar un archivo similar a consultas.json donde hay mas de un grafico y lo que se espera de tu programa es que muestre el primer grafico y al momento de cerrar vaya por el siguiente y así sucesivamente

**Comment by akaminetzkyp** [comment]
Oka, entiendo! Alguna idea de cómo hacer eso? 😢 He intentado muchas cosas pero no lo he podido lograr. Ahora estoy llamando `show(block=False)` y me muestra solo un gráfico. Si le saco el `block=False` el programa se pausa hasta que se cierre la ventana, pero al cerrarla no sigue donde estaba.

**Comment by Hernan4444** [comment]
@akaminetzkyp cuando le sacas `block = False` y cierras la ventana dices que no sigue donde estaba, puedes desarrollar un poco mas esa parte, se salta código, consultas, te tira error?

**Comment by akaminetzkyp** [comment]
Intentaré explicarlo lo mejor posible. En mi programa, después del `show()` tengo un return. Cuando le saco el `block=False` y cierro la ventana, ese return no se ejecuta. Además, si habían consultas después de `graficar`, ninguna se ejecuta. Es decir, cuando uso el `show()` se salta código. Según lo que he leído, el show (en casos normales) debe ser usado al final del programa. Sin embargo, no encontré nada con respecto al uso de Matplotlib junto a PyQt5.

¡Muchas gracias por tu ayuda @Hernan4444! 😄

**Comment by pizquierdo2** [comment]
Tengo un problema similar al de @akaminetzkyp. Cuando llamo plot.show() usando la interfaz gráfica aparece una ventana extra en blanco que no se puede mover ni cerrar. Además, las líneas de código que venían después del la ejecución del plot.show() (unos print en  este caso) no se ejecutan hasta que cierre la interfaz gráfica (al cerrar el programa). A pesar de que no se ejecuten esas líneas de código hasta el final, si puedo seguir interactuando con la interfaz (ejecutando otros comandos). Alguna sugerencia para normalizar la situación? Muchas gracias

**Comment by Hernan4444** [comment]
al final se decidió que al momento de evaluar lo haríamos de un gráfico a la vez tal como akaminetzkyp  había sugerido para que no se preocupen. Parece que la combinación matplotlib y PyQt5 no es muy favorable. :sweat_smile:

Saludos!!

**Comment by akaminetzkyp** [comment]
Gracias! :D
