### ISSUE TITLE
.gitignore subir archivo mapas

### ISSUE THREAD

**Issue by Zetaku1** [IIC2233/syllabus#374]
En el enunciado dice que no se deberán subir los archivos contenidos en la carpeta mapas, pero esto no nos dice si hay o no que subir la carpeta que contiene a los mapas (Claramente vacia).

**Comment by jcechavarri** [comment]
Hola @Zetaku1!

En el enunciado, en la sección gitignore dice, "la carpeta llamada sprites debe ser ignorada". Es decir, debes ignorar la carpeta completa 😄.

Espero haberte ayudado

**Comment by Zetaku1** [comment]
Gracias por responder!
Lo que pasa es que tenia una duda con la carpeta mapas, no con la de sprites.
Pero ante la duda, ignoraré tambien la carpeta mapas 😃
