### ISSUE TITLE
Test funciona para datos pequeños.

### ISSUE THREAD

**Issue by bozzimuc** [IIC2233/Syllabus#374]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Buenas tardes
En algunos tests, he logrado que mi código corra para datos pequeños, pero no para grandes. Mi pregunta es si puedo, en esos casos, poner algo como "if len(lista_animales) < 50000:" para poder recibir puntaje parcial por los datos que sí me funcionan.

Muchas gracias

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Jeremiah-PHP6** [comment]
¡Hola! El problema se puede deber a que tu función consume mucha memoria al crear los generadores. Prueba retocando tu código para que corra más rápido. Por ejemplo, muchos ciclos for anidados se traducen en un alto costo computacional, y hacen más lento al programa.

Te recomiendo que hagas esto, ya que si el testcase no para de correr, se dará por malo. ¿Qué función es la que te causa el inconveniente? Puedo echarle una mirada a tu repositorio si necesitas ayuda.

Quedo atento a tu respuesta, saludos.
