### ISSUE TITLE
Redistribuir metodos

### ISSUE THREAD

**Issue by Icarus328** [IIC2233/syllabus#374]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, mi duda es que en el enunciado sale el metodo "evento" bajo la clase "barco" mi duda es si, en caso de tener una clase "barco" y subclases "barco_tipo" puedo, en su lugar, poner el metodo "evento" en las clases "barco_tipo"

Gracias!

**Comment by Emiliax16** [comment]
Hola @Icarus328 .

En el apartado 3.1 **Barcos**, dice: _los barcos pueden realizar las siguientes acciones_ ,por lo que el enunciado no exige como requisito que estas acciones sean métodos exclusivo de la clase Barco, por lo cual podrías incluirla en las clases de los tipos de barcos (puesto se estaría cumpliendo con la acción "evento" de los barcos). Sin embargo, tienes que evaluar si a nivel de modelación, estaría correcto que un método que tienen en común los tipos de barcos (como "evento") no esté presente en tu clase **Barco**. (incluso sabiendo que dependiendo del tipo de barco, el funcionamiento podría cambiar). 

Cuéntame si quedó claro! Saludos c:
