### ISSUE TITLE
Duda AC Bonus / obtener_info_habilidad

### ISSUE THREAD

**Issue by J0SEF4** [IIC2233/Syllabus#374]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Mi duda es con respecto a la funcion obtener_info_habilidad que en el enunciado dice lo siguiente:
"def obtener_info_habilidad(url: str) -> dict: Recibe como parámetro el url de tu habilidad y
deberás hacer un request al sitio descrito en https://pokeapi.co/docs/v2#abilities para obtener la
información asociada a esa habilidad. Esto te entregará un mensaje en formato JSON que deberás parsear
para generar y retornar un dict con los siguientes datos"

Mi pregunta es que no entiendo que url tengo que usar, o como debo usar los 2 url que me son dados, en este caso el url dado y el otro que es https://pokeapi.co/docs/v2#abilities.

Gracias por adelantado, estaré esperando su respuesta.

**Comment by J0SEF4** [comment]
Además:
- Cual es el sitio descrito en ese url? Es este: https://pokeapi.co/api/v2/ability/{id or name}/?
- Que es parsear?
- Se debe usar .format en el request para que me de json o eso solo era a modo de ejemplo en los contenidos?

**Comment by J0SEF4** [comment]
En si no logro entender la documentación entregada en link todo es un diccionario o debo hacer url.format("name") para conseguir el nombre de la habilidad. Si es así como lo haría para conseguir el short_effect que esta dentro del effect_entries y mas en name: en? (no se como expresarlo)

**Comment by igbasly** [comment]
Hola @J0SEF4 :v:

* Te explico, cuando haces la primera consulta a la API del curso, se te entregará una habilidad Pokémon y la url correspondiente a la API de Pokémon de esa habilidad.
Esa url (la obtenida desde la API del curso) es la que debes utilizar para hacer la consulta de la función `obtener_info_habilidad`. En pos de que puedan entender que entrega esta consulta a la API de Pokémon, es que se les dio el link de la documentación de la API, el cual es: https://pokeapi.co/docs/v2#abilities . En ese sitio pueden encontrar información respecto a que entrega la consulta hecha al url obtenido desde la API del curso.
* "Parsear" es un término inglés españolizado que se refiere a tomar cierta información y procesarla con el fin de obtener solo ciertas partes de su contenido. En este caso se refiere a que desde la consulta a la API de Pokémon obtendrás mucha información respecto a tu habilidad específica, pero solo nos interesa obtener algunos atributos para generar la respuesta de la función.
* No entiendo bien tu pregunta respecto a `.format`. Este es un método de `String` y es para insertar información (interpolación) dentro de un `string`. Por ejemplo, estos dos códigos son equivalentes:
```python
"Hoy es: {}-{}-{}".format(15, 12, 2021)
f"Hoy es: {15}-{12}-{2021}"
```
* Respecto a lo preguntado en el último comentario no entiendo tu pregunta, si podrías explicarme de nuevo sería genial 😉 

Quedo atento 👌

**Comment by ArianaCisternas** [comment]
> Además:
> 
> * Cual es el sitio descrito en ese url? Es este: [https://pokeapi.co/api/v2/ability/{id](https://pokeapi.co/api/v2/ability/%7Bid) or name}/?
> * Que es parsear?
> * Se debe usar .format en el request para que me de json o eso solo era a modo de ejemplo en los contenidos?

Tengo las mismas dudas

**Comment by J0SEF4** [comment]
Entendido! Ya entendí mejor ahora los conceptos y el. format que antes no lo entendía del todo bien. 
Con respecto, a lo preguntado en el ultimo comentario ya lo entendí.
Gracias.
