### ISSUE TITLE
¿Cómo se escribe pseudocódigo?

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#374]
Hola, 
Ni idea si existe algún formato o sintaxis especial, si les pongo un texto grande que explique todo ¿cuenta como pseudocódigo?
¿Cómo se escribe pseudocódigo?

**Comment by IchottMano** [comment]
@jmwielandt Hola!

Aquí puedes ver una explicación de [pseudocódigo](https://es.wikipedia.org/wiki/Pseudoc%C3%B3digo)

Saludos!
