### ISSUE TITLE
guardando en lista toda info de personas

### ISSUE THREAD

**Issue by glbello** [IIC2233/Syllabus#374]
Saludos, estoy complicadísimo en obtener y separar la información de las personas en ```genomas.txt```, y quería asegurarme de lo que hago no es un mero desastre, deseo guardar en listas tanto el número de letras del nombre, el nombre propiamente tal, el número de apellido, el apellido, y así sucesivamente con los posteriores 9 características, más el genotipo, será factible o con eso haré que mi programa tarde un siglo. Todo lo anterior para luego poder distribuir las características de las personas en otra lista.

Quedo atento, gracias

**Comment by Arcoirisky** [comment]
La idea de funcional es no guardar casi nada :O Como estoy entendiendo tu idea, vas a hacer que más de un computador explote 😅 Te sugiero pensar bien en lo que haces y leer los comentarios de los entregable.
