### ISSUE TITLE
Implementacion de movimiento

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus#374]
Actualmente tengo a los enemigos moviendose de una forma muy fluida, pero el tema es que estoy tirando mas de una vez las imagenes y aplicando time sleep para hacer la ilusion de que son mas imagenes. El tema es que me molesta el time sleep, ya que me han comentado en stackoverflow que el sleep estaria pegando de alguna forma los eventos. La forma en que lo implemente es en el movimiento del enemigo y le manda una señal por cada vez que cambia una imagen y mini-movimiento, esto hasta completar el movimiento de una casilla, entremedio los sleep.
No habra otra forma de implementar lo mismo pero quitando los sleep? Estaba mirando QVariantAnimation y funciona bien como pruebas, pero dentro de mi programa no(por ahora).

**Comment by hbkim94** [comment]
Hola @MartinAracena ,

Efectivamente existe la probabilidad de que surjan conflictos particulares con` time.sleep()` cuando lo mezclas con `PyQt5`. Lo que puedes usar en reemplazo de `sleep()` es` QTimer.singleshot()`, que es como el equivalente a la primera función pero más "amigable" para `PyQt5` (en lugar de segundos usa milisegundos si, ojo!).

Prueba con eso. Mucha suerte con la tarea!
