### ISSUE TITLE
Magizoologos nuevos y criaturas

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#374]
Hola! En el enunciado dice "Todo magizoologo tiene al menos una criatura bajo su cuidado. Estas se detallan en la seccion DCCriaturas." Esto quiere decir que si el usuario crea a un Magizoologo se le tiene que pedir inmediatamente que cree a un criatura de su elección sin costo de sickles?

**Comment by matiasmasjuan** [comment]
Hola @lewebe !

Efectivamente, tal como dice el enunciado en el punto ***3.1 Menú de Inicio***, al momento de crear un nuevo **Magizoólogo** inmediatamente se le pide al usuario que adopte su primera **DCCriatura**. Para ello, se deben desplegar las opciones de *especies*, en donde se deberá elegir alguna, y posteriormente se debe hacer el procedimiento de elegir un *nombre*, con las especificaciones dadas en el enunciado. Esta **primera** **DCCriatura** **no** tiene **costo** de **Sickles**.

Espero haber respondido a tu pregunta, y mucho éxito con tu tarea!
