### ISSUE TITLE
Plazo hasta el martes?

### ISSUE THREAD

**Issue by isihirmas** [IIC2233/syllabus#375]
Hola! 
Es posible que el plazo se pueda extender hasta el martes? o incluso 2 pm del martes antes de la ayudantía?
Estamos en periodo de I3 y para los que tenemos prueba el lunes el plazo casi no nos afecta.
Porfavor lo podrían considerar? 
Es una extensión muy mínima y no afectaría al desarrollo ni estudio de la actividad del jueves <3

Gracias!

**Comment by Hernan4444** [comment]
Hola,

Lamento informar que no se va a extender más el plazo. El original era el domingo y se decidió dar un día más por si necesitan afinar detalles y asegurar que su tarea sea funcional para que sea corregida. Lamentablemente no podemos considerar todos los casos de pruebas para dar más tiempo. Además, los ayudantes necesitamos el tiempo para corregir la tarea y no afectar la planificación del resto de las tareas.

Saludos

**Comment by Dnpoblete** [comment]
Hola, tengo una duda con respecto a los plazos. Como ahora la tarea se entrega el lunes a las 8, el README se entrega un día después de entregada la tarea o se tienen que entregar las dos cosas juntas el lunes?

**Comment by Hernan4444** [comment]
El readme tienen hasta el martes 20:00 para entregarlo (junto con la entrega atrasada, en caso de querer optar a ella).
