### ISSUE TITLE
Método regar solo retorna Fensaulantro

### ISSUE THREAD

**Issue by mxmauoc0** [IIC2233/Syllabus#375]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### ¿Por qué cuando trato de regar todas las plantas, solo me retorna Fensaulantro?

He tratado de resolver este problema mediante prueba y error, modificando el método para cada planta, recibiendo y no recibiendo parametros (pues los parametros necesarios los definí en el metodo en mi clase "Planta", metodo que trate de hacer abstracto y no abstracto)

Pero claro, no entiendo como afecta la multiherencia y si es un problema en este caso, ya que tampoco encontre un ejemplo concreto de estas situaciones en los contenidos, lo que me genera muchas dudas...

**Dejo foto adjunta de mi menú para ilustrar el problema**

<img width="514" alt="Captura de pantalla 2024-09-12 210630" src="https://github.com/user-attachments/assets/a3a74e16-b985-4d06-be88-139f4ea6682e">

>Las coordenadas son correctas pero el atributo vida y tipo se mantienen con solo los de "Fensaulantro"

**Comment by rodrigoaguilera15** [comment]
Hola @mxmauoc0 , por favor no cierres las issues, solo los profes deben hacer eso. Dime ¿solucionaste tu problema? Puede servirle a alguien más con la misma duda.

**Comment by mxmauoc0** [comment]
Lo arregle! Por eso la cerre, lo siento :(.
Era un problema en mi generador de instancias, al leer los archivos, solo estaba generando instancias del último que era leído
