### ISSUE TITLE
Manejo de excepción GenomeError

### ISSUE THREAD

**Issue by jerosalazar** [IIC2233/Syllabus#375]
El enunciado, en la parte de las excepciones, dice:
> **Genome Error:**
Se debe levantar esta excepción si al leer un genoma, éste tiene errores ya sea porque tiene espacios, letras distintas a ACTG, números o caracteres especiales.

¿Que se debe hacer con esto? Por ejemplo: borrar el error, no leer la línea, indicar en la consola que el genoma no se puede leer...

**Comment by Hernan4444** [comment]
@jerosalazar Si hay un genome error, las consultas que requieran leer ese genoma deberán levantar la misma excepcion. Solo ten presente que el error de genoma puede estar por ejemplo, en los ojos y si nuestra consulta es sobre el pelo de todos, no debería detectarse ese error.

Saludos ✌️

**Comment by MariaJosefinaAlliende** [comment]
¿No se puede levantar GenomeError al leerlo pero luego arreglar el error sacando los caracteres especiales, espacios y letras del genoma? 
Mi programa lee genoma.txt una sola vez, arregla los errores en el genoma y ocupa para las consultas la información ya arreglada...¿Tengo que cambiarlo todo?

**Comment by Hernan4444** [comment]
@MariaJosefinaAlliende en la sección 7.3 "Consultas fallidas, ejecución y ejemplo" dice:
> Generar resultados.txt y no caerse al encontrar un error durante el procesamiento de alguna
consulta, sino indicar el error con el formato que se explicó previamente. La idea es que pueda seguir
con las otras.

Y hay un ejemplo de que los errores solo ocurren cuando se procesa una consulta:
```python
# Abre consultas.json
for i in consultas:
    try:
        resultado = procesar_consulta(i)
        # Escribe los resultados en resultados.txt
    except MyExcepcion:
        imprimir_fallo()
        # Escribe que la consulta fall´o en resultados.txt e indica el nombre del error
```

E incluso en esa sección dice: 
> **¡Esta sección es muy importante! No respetar el formato afectará considerablemente la nota de su tarea.**

Bajo todo eso debe decirte que no estás siguiente el formato. Aunque no creo que sea necesario cambiarlo todo si deberás hacer algunos cambios para poder respetar el formato solicitado.

**Comment by MariaJosefinaAlliende** [comment]
@Hernan4444  Muchas gracias por responder :) . Sí leí esa parte antes de escribir la issue, pero es que  sigo teniendo dudas :S ... Sé que en esa parte  habla de errores en general, pero  en la descripción de todos los otros errores (Bad Request, Not Found, NotAcceptable) se menciona que se levantan durante una consulta, mientras que GenomeError no. Entiendo que obviamente no se tiene caer al realizar consultas  por errores en el Genoma (mi programa tampoco se cae), pero no porqué el error GenomeError tiene que levantarse durante la consulta y no antes cuando leí el archivo genoma.txt... porque me parece más eficiente procesar el genoma una sola vez en vez de estar haciéndolo cada vez que se hace una consulta...

**Comment by Hernan4444** [comment]
@MariaJosefinaAlliende entiendo tu punto, pero en ese caso hubiera sido mejor preguntar antes 😞. Por otro lado, procesar el genoma una vez implica que estás cargando en memoria RAM todo de una y eso es algo que funcional intenta evitar (aquí estamos ante la pelea de eficiencia v/s memoria :s). Tu forma igual la considero bueno en terminos de eficiencia, pero no en terminos de memoria.

Como sugerencia, te recomiendo que de alguna forma marques las características donde hubo error de genoma para que al momento de hacer la consulta se visualice el error. Así no tienes que cambiar tanto tu código que analiza y corrige todo antes y logras cumplir con el formato 👍 

Saludos ✌️

**Comment by jerosalazar** [comment]
@Hernan4444 una última duda. En el caso de que me encuentre con un espacio en la secuencia de genomas durante la lectura de la línea, por ejemplo: "AAGATCGTA GTCTC...".
¿Debo tomar el espacio como una posición y leer los genes como AAG-ATC-GTA-_GT-CTC... y lidiar con el error, como dijiste, cuando llame esa posición dentro de una consulta o debo eliminar ese espacio y leer los genes como AAG-ATC-GTA-GTC-TC...?

**Comment by Hernan4444** [comment]
@jerosalazar debes lidiar con el error, es decir, saber que las características que usan ese gen están malas para cuando hagamos la consulta sobre esa característica, arrojar error. Esto mismo se dá para una letra o símbolo que no coincide con AGTC dentro del genoma.

**Comment by MariaJosefinaAlliende** [comment]
@Hernan4444  ok, muchas gracias!! Voy a hacer eso entonces :)  👍

**Comment by bedefrunner** [comment]
@Hernan4444 Estoy en la misma situación que @MariaJosefinaAlliende. Mi código primero lee todos los genomas, instancia con namedtuples a todas las personas con su nombre, apellido y genoma y eso queda guardado para hacer las consultas. La lectura de datos es super rápida, usé muchos generadores y guardé solo lo estrictamente necesario, de hecho el programa no demora nada en correr. 
Ahora entiendo que no hay que leer todo el genoma sino que leer solo lo necesario para cada consulta que se realice. Voy a recibir mucha penalización por no estar haciendo lo pretenden que haga? Me conviene más seguir así o cambiar todo?

**Comment by Hernan4444** [comment]
@bedefrunner es posible que cuando probemos con archivos de gran volumen, el computador del ayudante pueda colapsar si es que estás instanceando tooodo el genoma y eso será un error para quien instancea todo antes o lo instancea durante cada consulta, mientras no lo hagan de de forma eficiente.

**Hint**: Una cosa es cargar la información de forma eficiente pero tambien hay que analizar como almacenarla de forma eficiente, una buena forma es aquella que no dependa del número de genes por persona.

Te puedo recomentar lo mismo que MariaJosefina para el error de `GenomaError`. De alguna forma marca las características donde hubo error de genoma para que al momento de hacer la consulta se visualice el error. Así no tienes que cambiar tanto tu código que analiza y corrige todo antes y logras cumplir con el formato 👍.

Pero si instanceas todo antes y logras hacer bien el `GenomaError` tampoco estaría mal. Talvez exista uno o dos test que se demore mucho porque ocupa más de 1000000 de genes 😱, pero ese error te puede ocurrir a ti como a cualquier que instancia todo el genoma de forma no optima.

Saludos ✌️

**Comment by vixolo** [comment]
@Hernan4444 En el enunciado aparece cada consulta con su respectivo argumento, y en todas las que no son estadísticas se toma el argumento "persona". Por ejemplo, la consulta ascendencia(persona) toma solo ese argumento. Eso me ha hecho pensar que se deberían instanciar las personas al comienzo del programa, y de ahí trabajar con ellas, pero en esta issue me confundo y pienso que hay que leer el archivo cada vez que hacemos una consulta y analizarlo en el momento. Es esto lo que hay que hacer?

Por otro lado, después pones que "una buena (de almacenar la información), es aquella que no dependa del número de genes". Si uno sólo abre una vez el archivo, lo analiza sin guardar la información del genoma, y sólo guarda la información de cada persona ya interpretado el genoma, está mejor?

Muchas gracias

**Comment by Hernan4444** [comment]
@vixolo no te puedo decir: **"si, eso debes hacer o no, eso está mal"** para la decisión de como implementar la lectura de genoma, tu debes tomar una opción, analizar los pros y contra, y decidir si implementarla o no. Con la materia vista hasta ahora, es posible llegar a una solución eficiente.

> Por otro lado, después pones que "una buena (de almacenar la información), es aquella que no dependa del número de genes". Si uno sólo abre una vez el archivo, lo analiza sin guardar la información del genoma, y sólo guarda la información de cada persona ya interpretado el genoma, está mejor?

Puede ser, pero que pasa con las consultas sobre el genotipo?

Les recordamos que la idea de la tarea no es que nosotros les digamos cual es la forma en la que deben implementar las cosas, sino que enfrentarlos a un problema y que ustedes logren tomar la decisiónes adecuadas en base a las materias que han visto y que los lleven a resolver el problema de la mejor forma posible.

**Comment by Bneya** [comment]
Para el caso de la función "pariente_de", necesito comprobar para cada persona si es o no pariente de la persona que consulto, por lo que si una persona tiene error en su genoma, casi siempre esta consulta va a arrojar **GenomeError** cuando _pase comprobando_ por la persona con error.
¿Está eso bien?
