### ISSUE TITLE
Duda en funcion obtener_info_habilidad (AC Bonus)

### ISSUE THREAD

**Issue by J0SEF4** [IIC2233/Syllabus#375]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Cuando me dice "Recibe como parámetro el url de tu habilidad y
deberás hacer un request al sitio descrito en https://pokeapi.co/docs/v2#abilities para obtener la
información asociada a esa habilidad. Esto te entregará un mensaje en formato JSON que deberás parsear
para generar y retornar un dict con los siguientes datos"
Esto me quiere decir que cuando hago el request,get me da altiro en formato json? o a lo anterior le debo aplicar .json()?

**Comment by igbasly** [comment]
Esto es parte de la issue anterior, así que la cerraré y responderé allá 😉
