### ISSUE TITLE
Barcos en canal, su posicion y colision y otras dudas.

### ISSUE THREAD

**Issue by Ikilly0** [IIC2233/syllabus#375]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, tengo un par de dudas que veo que nadie ha preguntado, lo cual me preocupa un poco.

1.- El canal solo va en un sentido cierto?, se asume me imagino
2.- si en un mismo turno de simulacion (hora) un barco 1 avanza y un barco 2( adelante del 1) encalla, quien tiene prioridad? encallar o avanzar?
3.- Como recomiendan guardar la posicion del barco dentro del canal?
4.- Mercancias deberia ser una lista de clases mercancias no? /lo mismo para tripulacion y para la lista de barcos dentro de class canal.
5.- Si hay un evento especial, que cosas si y que cosas no pueden suceder? Ej: Piratas; puede avanzar el mismo turno que sucedio el ataque? Ej2: Encallado, puede encallar el mismo turno que ocurrio una averia?
6.- Los barcos se pueden adelantar, entonces, pueden estar en el mismo lugar dos barcos? (barco(1).distancia  = barco(2).distancia), ademas me imagino que los barcos no tienen largo ni ancho y son puntos.

Son dudas mas que nada para unir correctamente la simulacion, podria asumir cualquier cosa y la simulacion correria igual, pero me gustaria saber que tenian en mente ustedes. Muchas gracias.

7.- De pasada pregunto, cual es la manera de usar remove? para eliminar los csv de mi repo... jsjsj

**Comment by Emiliax16** [comment]
Hola @Ikilly0 !

1. Asume que sólo va en un sentido, inclúyelo en el README.
2.  Si un barco encalla, los de atrás pueden seguir avanzando hasta llegar a su posición o detenerse en el instante en que el barco delantero encalló. Queda a tu criterio y no te olvides de ponerlo en el README.
3.  _Hint:_ podrías guardar la posición del barco utilizando directamente uno de los contenidos mínimos a evaluar en esta tarea. Revisa los objetivos de la primera plana de la tarea.
4.  Son entidades, lo más correcto es que las modeles como clases.
5.  Los eventos especiales de barcos pasajeros y carguero no le impiden avanzar. En el caso del buque, este no podrá avanzar por una cantidad de tiempo que tú debes definir.
6.  Sí, pueden estar en la misma posición y adelantar. Asume que son punto particulares.
7.  git rm --cached nombre_archivo

Saludos!

**Comment by Ikilly0** [comment]
1.- Perfecto
2.- Entonces si un barco encalla, dices tu que, seria valido (detener todos los barcos detras)? pregunto porque eso es increiblemente mas sencillo de programar que (detener todos los barcos en el punto mas lejano [dado por el encallo] que puedan avanzar o que avanzen hasta detenerse de manera natural en una hora)
3.- 🤔 !
4.- Perfecto
5.- Y que hay de los encallados? un barco encallado puede ser atacado por piratas?
6.- Perfecto
7.- Perfecto
Muchas gracias

**Comment by Emiliax16** [comment]
2. Sip, en issues anteriores se definió que esto quedaría a criterio del alumno. Sin embargo, avanzar todos los barcos mientras el de adelante encalló es más lógico y ayuda mucho a la fluidez del programa!
3.  Hay varias maneras de guardar la variables modificables de un objeto!! atributos, listas,  properties ...  
5. No! un barco encallado no puede sufrir un evento especial ! Revisa la issue [#317](https://github.com/IIC2233/syllabus/issues/317)
