### ISSUE TITLE
Columnas

### ISSUE THREAD

**Issue by stgoa** [IIC2233/Syllabus#375]
<img width="706" alt="captura de pantalla 2017-04-30 a las 5 36 39 p m" src="https://cloud.githubusercontent.com/assets/26234498/25567775/ba822cf0-2dcb-11e7-885a-f5b553e791be.png">
Como las columnas son cualquier iterable que pueda contener datos validos (datos de Tipos de Datos de RQL) no queda un poco la embarrada?? 
por ejemplo el string "xyz" es iterable, y si "x", "y" y "z" ya fueron asignadas entonces el string "xyz" es una columna válida. Luego las columnas y string se confundirían

**Comment by Hernan4444** [comment]
@stgoa tal como se dijo #302, las dos formas de ingresar información es a traves de extraer columna o escribir de forma manual una lista con elementos adentro. Es por ello que nunca se te ingresará como columna una concatenación de caracteres (string) por lo mismo que tu dices. Lo que sí dentro de una columna pueden haber variables.

Espero haber respondido tu duda.
Saludos!

**Comment by berrazuriz1** [comment]
@Hernan4444 no me queda claro una cosa, ¿puede haber una consulta anidada en el comando "extraer columna"?, la verdad es que no me pude imaginar como.

**Comment by Hernan4444** [comment]
ya tampoco me lo imagino....esto es porque extraer_columna pide como argumentos datos tipo string y no tenemos ninguna función que retorne un string

Saludos

**Comment by acrojas2** [comment]
Hola: 
Tenía la duda si es que se podría dar el caso que por medio de un archivo como el consultas.json se ingrese algo distinto a una lista, como por ejemplo una tupla o un set. 
Saludos :B

**Comment by pizquierdo2** [comment]
@Hernan4444 nos dijiste "las dos formas de ingresar información es a traves de extraer columna o escribir de forma manual una lista con elementos adentro". Ahora, en el caso 'de forma manual una lista con elementos adentro', podemos considerar que los elementos adentro son sólo del tipo 'int', o 'float', o 'str'? En ese caso, podemos suponer que si el elemento es del tipo 'str' entonces sólo puede ser interpretado como variable, y no como un número? Con esta última pregunta me refiero a strings del tipo '4' o '5', que podrían interpretarse como números al hacer float(string).

Relacionado con ese tema tengo otra duda. La función asignar "no permite guardar información si el nombre ingresado es igual al nombre de algún comando propio de RQL o al nombre de alguna distribución de probabilidad". Luego, no me queda claro si es válida la ejecución de asignar(variable, '5'). Dicho de otro modo, puedo guardar variables bajo el nombre de un string al que le puedo aplicar float(string) sin que me devuelva un error?

Gracias!

**Comment by Hernan4444** [comment]
Tal como se dijo en #369 pueden suponer que las variables no se pueden llamar solo con números (EJ: "123"). Por lo tanto tampoco haremos `[asignar, '5', 10]` a no ser que tenga una letra como `[asignar, 'a5', 10]`. Es por ello que se dijo que las columnas solo tendrían int o float, porque los "str" que contengan son siempre nombres de variables que guardan un int o float (tambien pueden ser una variable que no está definida y en ese caso hay que arrojar un error).
Saludos!!

**Comment by pizquierdo2** [comment]
Pero si una columna contiene un string == '5', debería retornar error, o convertirlo en en float?

**Comment by Hernan4444** [comment]
retorna un error.
saludos!!

**Comment by FernandoPieressa** [comment]
@acrojas2 la idea de entregarles una interfaz y el archivo consultas.json es que ustedes prueben cualquier input que les dé duda y por ejemplo podrías intentar escribir una tupla o un set en el json o en la misma interfaz (funcionan exactamente igual), si el programa soporta eso entonces puedes suponer que podemos hacer consultas con eso, si el programa no lo permite (se cae y/o te tira error) puedes saber que no lo haremos.
