### ISSUE TITLE
Dueños de criaturas de criaturas.csv

### ISSUE THREAD

**Issue by arturobugueno** [IIC2233/syllabus#375]
Las criaturas que entrega el archivo, ¿tienen algún dueño asignado o es una especie de zoológico de donde el magizoologo puede elegir si adoptar estas o una nueva?

**Comment by matiasmasjuan** [comment]
Hola @arturobugueno !

**Todas** las **DCCriaturas** deben tener sólo **un** dueño. Por esta razón, **todas** las **DCCriaturas** almacenadas en el archivo ```criaturas.csv``` tienen un dueño. Los **Magizoólogos** pueden tener varias **DCCriaturas**, pero a una **DCCriatura** le corresponde un **único** dueño. Al momento de **adoptar** una **DCCriatura**, ya sea en el ***Menú de Inicio*** tras crear un **Magizoólogo**, o a través del ***DCC***, se le debe pedir al usuario crear una **nueva DCCriatura**, que no se encuentre almacenada en el archivo ```criaturas.csv```. En esta opción, se le debe pedir al **usuario** cuál especie quiere, y elegir un nombre para la **DCCriatura** (según las especificaciones del enunciado, es decir, caracteres alfanuméricos, usar indistinamente las mayúsculas de minúsculas, no puede repetirse el nombre, etc)  y cuando la **DCCriatura** ya se encuentre lista, debe guardarse en el archivo ```criaturas.csv```.

Espero haber respondido a tu pregunta, y mucho éxito con tu tarea!

**Comment by arturobugueno** [comment]
Me refiero a quien le pertenece que criatura en el archivo. Por ejemplo, si decido iniciar sesión, como se que criatura me pertenece de las que no. Estuve revisando y no he encontrado nada que me indique el dueño de las criaturas existentes.

**Comment by matiasmasjuan** [comment]
Si bien en el archivo ```criaturas.csv```, en cada una de las lineas de la **DCCriatura**, no hay un **valor** que me indique el nombre de su **Magizoólogo** dueño, recuerda que en el archivo ```magizoologos.csv``` **SI** hay un valor en donde están especificadas una **lista** con los nombres de sus **DCCriaturas** separadas por (**;**). Tal vez puedes hacer uso de ese archivo para saber a quién le pertenece alguna **DCCriatura** .

Suerte con la tarea!

**Comment by arturobugueno** [comment]
Perfecto! Gracias!
