### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by tcperez** [IIC2233/syllabus#375]
Hola!

¿Es posible realizar drag and drop entre ventanas distintas? (es decir, moviendo en algún segundo el cursos por sobre el escritorio) De ser así, ¿hay alguna librería con la que salga más fácil hacerlo? O me conviene reestructurar mi programa, lo que pasa es que hice el inventario en una ventana aparte, y estoy considerando traspasarlo a la ventana de juego.

Gracias !!

**Comment by gatochico** [comment]
Hola! 

Sí, es posible realizar drag and drop entre ventanas distintas con unicamente pyqt5! :computer: Te puedo decir como pista que no resulta significativamente más dificil que el drag and drop dentro de una misma ventana, por lo que una vez entiendas cómo funcionan los elementos básicos del drag and drop en general, no te costará mucho el implementarlo entre dos ventanas :) Recuerda que cualquier duda **específica** puedes preguntarla en el foro y te ayudaremos.

Finalmente, si no lo logras y te das cuenta que te está tomando mucho más tiempo de lo necesario, te recomendaría el rediseñar el programa con una sola ventana, ya que la idea es que un detalle de diseño como este no te atrase en implementar cosas que sí se evaluan en la tarea.

Ánimo y cualquier cosa comenta! :corn: :woman_farmer:
