### ISSUE TITLE
Moral entregada en delegaciones.csv

### ISSUE THREAD

**Issue by mmontecino** [IIC2233/syllabus#375]
En el enunciado dice que debemos calcular la moral del equipo como el promedio de la moral de sus deportistas, pero en delegaciones.csv nos entregan un valor de la moral. ¿Debemos omitir el valor inicial y calcular la moral desde el inicio o mantenerlo?

**Comment by amparostevens** [comment]
Hola @mmontecino!

Ese valor de moral fue calculado tomando en cuenta los deportistas pertenecientes a la delegación, pero eres libre de calcularla de nuevo si así lo prefieres.
Recuerda eso sí, que la moral de la delegación se actualiza cuando agregas un nuevo deportista al equipo y cuando la moral de algún deportista cambia.
