### ISSUE TITLE
PEP8 multiple statements on one line

### ISSUE THREAD

**Issue by atbusch** [IIC2233/Syllabus#375]
Tengo una funcion que cumple con tener menos de 15 lineas si hago
if a == 1: b ==2
Pero ahi sale que no cumple con PEP8  por "multiple statements on one line" y habria que hacer
if a == 1:
     b = 2

Hay que cumplir con PEP8 en este caso tambien aunque sume varias lineas mas que de la otra manera y no sea mucha la diferencia en el orden del codigo?

**Comment by IchottMano** [comment]
@atbusch Hola!

No puedes usar usar ; para cumplir con las 15 ni hacer lo que dices.
En el caso que tu tarea tenga estas faltas, se arreglarán a modo que cumplan con pep-8 aunque esto implique que tus funciones rompan con el límite de líneas de código, l ocual implicará un descuento de puntaje.
Por lo tanto, debes buscar una manera de acortar aún más la función en cuestión.

Saludos!
