### ISSUE TITLE
votos interespecie

### ISSUE THREAD

**Issue by emivenezian** [IIC2233/Syllabus#375]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

En el test 0, hay animales que no tiene voto, en particular el 3055, 3, 3056. que pasa? no puedo asumir que los generadores de votos qu em dan corresponden a los generadores de animales?

**Comment by Jeremiah-PHP6** [comment]
¡Hola! Pueden haber animales que no tengan votos asociados en el generador de votos (esto se podría considerar como que votó nulo). No debería generar ningún tipo de conflicto. ¿Te aparece algún error al correr los test? Quedo atento.
