### ISSUE TITLE
Opción volver atrás

### ISSUE THREAD

**Issue by ignaciovilla** [IIC2233/syllabus#376]
En el enunciado dice que cada menú debe tener una opción de volver atrás, pero me surgen las siguientes dudas:
- Dentro del menú del entrenador, en las acciones de fichar, entrenar, y sanar también debe existir una opción de volver? ya que en cierto modo también son un menú
- En la parte de simular el día de competencia debe existir una opción de volver atrás?
Muchas gracias

**Comment by baosse** [comment]
Holaa Ignacio!
Dentro de las acciones (como simular, sanar, fichar y entrenar) no es necesario que pongas la opción de volver atrás. 
Mucho éxito✨
