### ISSUE TITLE
Duda comentarios del código y PEP8

### ISSUE THREAD

**Issue by VicenteAlvarado** [IIC2233/syllabus#376]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola,  se incluyen en las condiciones de conteo de líneas  y de largo de las líneas los comentarios que hago en mi código??

**Comment by mistico0121** [comment]
Hola

Si. PEP8 también lo incluye. Imagina tener que leer comentarios de 500+caracteres que ocupan como 3 pantallas xD. Procura que los comentarios también cumplan con el límite del largo de lineas

Saludos
