### ISSUE TITLE
Uso de parámetros en el frontend

### ISSUE THREAD

**Issue by c4ebt** [IIC2233/Syllabus#376]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En [esta respuesta a otra issue](https://github.com/IIC2233/Syllabus/issues/347#issuecomment-1554656662) se menciona que los parámetros deberían manejarse únicamente desde el backend. Entiendo que en una aplicación ideal el frontend no debería acceder directamente, por ejemplo, a una base de datos, sino que esta interacción debería estar mediada por el backend de la aplicación.

Sin embargo, en el caso de esta tarea hay muchos elementos del módulo `parametros` que tienen relación únicamente con el frontend de la aplicación, principalmente los paths de las texturas de los distintos sprites. Esto tiene un paralelo en las aplicaciones reales, por ejemplo, una aplicación web, en donde el frontend trabaja directamente con todos los elementos de `assets/`.

La sección 4.1 del Enunciado dice: "Se evaluará, entre otros, los siguientes aspectos: Correcta modularización del programa, lo que incluye una adecuada separación entre back-end y front-end, con un diseño cohesivo y de bajo acoplamiento."

A raíz de todo esto, me surgió la pregunta: **¿Está permitido trabajar directamente con los parámetros en el frontend?**

**Comment by Hernan4444** [comment]
Hola @c4ebt 

No hay problema con lo que preguntas. El frontend puede hacer uso de parámetros.py

Saludosヾ(＾-＾)ノ
