### ISSUE TITLE
Obtener_info_pokemones (AC Bonus)

### ISSUE THREAD

**Issue by J0SEF4** [IIC2233/Syllabus#376]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

En la funcion de obtener_Info_pokemones, se pide poner en el diccionario: 
      "types" Es una lista que contiene los nombres (str) de los tipos de pokémon al cual el pokémon
       pertenece. Los tipos de cada pokémon se encuentran en el objeto "types" de la respuesta de la API.
En esta lista que debemos crear solo debe tener los nombres de los tipos de pokemon o es una lista done cada elemento es un diccionario conjunto a su nombre, url y slot como sale en la documentacion(https://pokeapi.co/docs/v2#pokemon)?

**Comment by igbasly** [comment]
Hola @J0SEF4 :v:

Tal como dice en el enunciado, debe ser una lista que contenga los nombres (`str`) de los tipos del Pokémon. Y como se indica en el paréntesis, debe ser un *string*, por lo cual no puede ser un diccionario.
En la documentación de la API de Pokémon te muestran como vendría el formato de la respuesta, pero eso debes transformarlo a la lista de nombres que te solicitamos.

Quedo atento a otras consultas 👌

**Comment by J0SEF4** [comment]
Ya, muchas gracias!
