### ISSUE TITLE
Menu volver atras al ingresar nombre magiozoologo

### ISSUE THREAD

**Issue by LeoMo-27** [IIC2233/syllabus#376]
Hola!

Tengo la duda si despues de seleccionar crear magizoologo, se debe abrir otro menu donde se deba seleccionar por ejemplo:
"[1] Ingresar nombre"
"[2] Volver atras"
"[3] Salir"
Mi duda surge del hecho de que no se si debe existir la opción de volver atrás al momento de ingresar el nombre del nuevo magizoologo.

**Comment by mpsubiabre** [comment]
Hola @LeoMo-27 !

En el enunciado se pide que al crear un Magizoologo se pida de manera inmediata ingresar un nombre. En el caso de que se ingrese un nombre repetido o no valido, se deben indicar las opciones que indicas :)

Éxito en la tarea!
