### ISSUE TITLE
Aprovecharse del for en listas por comprensión

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2233/Syllabus#376]
Quería saber si esta línea de código puede ser usada en la tarea:
g = list(diccionario.update({"vellos": vellos[i]}) for i in range(len(vellos)))
En si, nunca usaré la variable g, sino que usaré el diccionario que ahora tendrá la key vellos y sus genes, pero para esto me aproveché de el for en la lista por comprensión.

**Comment by TomasSalvadores** [comment]
Es legal la linea 😉
