### ISSUE TITLE
Consulta sobre parametro 'rango:a,b,c' en graficar

### ISSUE THREAD

**Issue by cho19** [IIC2233/Syllabus#376]
Hola! 

En los resultados se ejecutan `['graficar', 'normal2', 'rango: -3,5,0.1']` y `['graficar', 'x', 'rango: 0.00004, 40, 0.00004']` con `x` definida, en el primer caso levanta `Referencia invalida` pues `normal2`no esta definida, eso queda claro, pero en la segunda debiera levantar la excepción de `Imposible procesar`. ¿Esto se da porque el formato de la opción debe si o si ser `rango:a,b,c` sin espacios? ¿O bien `rango: a,b,c`? ¿O simplemente porque los largos de las columnas generadas es distinta?

Pregunto lo segundo porque, de ser afirmativa la primera respuesta, en el primer comando se escribe así y no se si debiera ser aceptado así si `x`estuviera definida.

Gracias y saludos!

**Comment by Hernan4444** [comment]
@cho19 es porque en 'rango: 0.00004, 40, 0.00004' hay 1.000.000 de datos mientras que en 'x' hay 500.000 datos

Saludos!!

**Comment by cho19** [comment]
@Hernan4444 Gracias!!

**Comment by negutierrez** [comment]
Pero en el enunciado dice que si la cantidad de numeros generados por el rango es mayor o igual al 'x', si se podria graficar o no? El error deberia ocurrir si el rango es menor que 'x', lo que no ocurre en `['graficar', 'x', 'rango: 0.00004, 40, 0.00004']`

**Comment by Hernan4444** [comment]
@negutierrez tienes toda la razon!!! no me percaté de que podía ser mayor u.u Entonces ese graficar no debería tirar error. De todos modos cuando corrigamos los haremos con test que cumplan con todo lo dicho en el enunciado e issues para no descontar puntaje por algo que el ayudante se equivoco. Mis disculpas

Saludos!
