### ISSUE TITLE
Método presentarse Jardin ¿str o repr?

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#376]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas, tengo 2 preguntas.
En la imagen adjunta del enunciado, para el método presentarse, si o si se debe usar `__str__` o también se puede usar `__repr__`??  

Y lo otro, este método puede recibir un parámetro, por ejemplo la temperatura?, o debe ser capaz de imprimirse sin necesidad de recibir parámetros?

<img width="999" alt="Captura de pantalla 2024-09-12 a la(s) 10 41 33 p  m" src="https://github.com/user-attachments/assets/42c0ee94-b896-4cb6-8818-d2fe57b34b4c">

**Comment by rodrigoaguilera15** [comment]
Tienes que utilizar `__str__`. Dicho simple, `__str__` es para mostrar el objeto de una forma amigable, y `__repr__` es para mostrarlo de forma detallada. Adjunto un ejemplo extraído de geeksforgeeks.org. Respecto a lo segundo: no, no puede recibir parámetros.
![Captura de pantalla 2024-09-12 232958](https://github.com/user-attachments/assets/28b28d38-f1c3-40b6-b299-3df86005fe65)

**Comment by martinpint** [comment]
Hola, lo que pasa es que `__repr__` me ayudaba al momento de querer interactuar con mi plano del jardin, ahora para cambiarlo a `__str__` tendría que modificar bastante el código, ¿Si lo dejo con `__repr__` me descontarán puntaje?

**Comment by rodrigoaguilera15** [comment]
Hola @martinpint , dado que el enunciado exige que uses `__str__`, sí tendrías al un descuento, específicamente bajo el criterio de Formato de entrega. Sin embargo, **probablemente** sea un descuento no muy alto. Si quieres más información, te recomiendo revisar las bases generales de las tareas que se encuentra en syllabus/tareas y también la distribución de puntajes, cuyo enlace está al principio de la sección 9 del enunciado. Mucho éxito.

**Comment by martinpint** [comment]
Hola, sobre eso. Que pasa si yo utilizo __repr__ en cada planta, netamente para representarla en el menú, pero utilizo __str__ en Jardin cuando quiera imprimir el estado de mi jardin, que es lo que piden en el enunciado. Estaría correcto?

**Comment by rodrigoaguilera15** [comment]
Tendrás que usar `__str__` en este caso también. El `__repr__` se usa para que tú, como **desarrollador** del código, tengas una representación legible de la instancia, para facilitar el debugueo y esas cosas. El `__str__` está pensado ser la forma en que la instancia se le muestra al **usuario**. Esta tarea y todas la demás se tienen que crear pensando en que la pueda ejecutar correctamente un **usuario**, así que siempre `__str__`.
