### ISSUE TITLE
colisiones

### ISSUE THREAD

**Issue by mjgarrido1** [IIC2233/syllabus#376]
puedo restringir que la variable SPEED_PLAYER siempre sera un divisor de la CONSTANTE_N?? Lo que pasa es que hice las colisiones con qrect, entonces, por ejemplo si mi constante n es 30, y el speed es de 4 y ademas tengo un solo camino que a su alrededor solo hay obstáculos como acá:

XXXXXXXXXX
CCCCCCCCCC
XXXXXXXXXX

El jugador avanzara de 4 en 4 pixeles lo que siempre generara una interseccion con los obstaculos (de 30x30 pixeles) y nunca podra entrar en este camino. En cambio si avanza de 5 en 5 pixeles (otro speed) calzara en algun momento y podra entrar sin problemas al camino.

**Comment by MartinAracena** [comment]
No se si esto ayude, pero podrias cambiar los QRect por QRectF que es lo mismo, pero QRectF considera floats.
