### ISSUE TITLE
Regar Defensauce

### ISSUE THREAD

**Issue by agukolubakin** [IIC2233/Syllabus#377]
* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Si un Defensauce recibe daño de tal manera que pierde armadura pero no toda, es decir, su vida se mantiene igual que antes. Y si además la vida que tenía era menor a su vida máxima, entonces puede regarse (aumentando la vida y manteniendo la armadura que le queda)? O para regarla es necesario que se le quite vida primero?

**Comment by R3Y3X** [comment]
hola espero que estés bien, eres libre de decidir, recuerda dejarlo explicado en el README. Éxito en la tarea ⚡
