### ISSUE TITLE
Duda Señales

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2233/syllabus#377]
Hola, 
Queria saber si hay como enviar un señal a una Clase en vez de una Instancia de esa Clase, por ejemplo : 
![image](https://user-images.githubusercontent.com/42182095/58345343-1f454080-7e26-11e9-9c78-edd7fdb2bc57.png)

**Comment by hbkim94** [comment]
Hola @csantiagopaz ,

No sé si entendí muy bien tu consulta (espero que sí). Lo que se me ocurre para lo que buscas hacer, es que conectes tu señal a algún método de la clase, cosa que al ejecutarse se setee el atributo que quieres en la clase misma.

Si es que eso no era a lo que iba tu pregunta, ¿podrías dar más contexto en qué es lo que buscar hacer?

Quedo atenta!

**Comment by csantiagopaz** [comment]
No era eso, pero logré solucionar de forma más simples, de cualquier forma muchas gracias @hbkim94
