### ISSUE TITLE
retorno de <class "generator"> para load_database()

### ISSUE THREAD

**Issue by mblejeune** [IIC2233/Syllabus#377]
Hola! al hacer load_database() me genera una <class "generator"> que es el generador para movies, ya que usé named tuples para definir los atributos de cada pelicula. Puede efectivamente esta función retornar una <class "generator"> ?

**Comment by IchottMano** [comment]
@mblejeune Hola!

Efectivamente, puede retornar un generador, el cual es un iterable.

Saludos!
