### ISSUE TITLE
Cómo utilizar funciones min y max

### ISSUE THREAD

**Issue by jorgemayol** [IIC2233/syllabus#377]
Hola!
En el enunciado no entiendo bien las formulas que tienen min( 1, max ( 0, ......).
No se como interpretarla y tampoco se si se debe usar una libreria que resuelve este tipo de formula.

**Comment by moquezada** [comment]
Hola @jorgemayol,

Python tiene implementadas las funciones `min` y `max` y puedes utilizarlas sin ningún problema. De hecho, está especificado en uno de los comentarios de la issue #240 😄 Puedes encontrar información de cómo utilizarlas en este [link](https://docs.python.org/3/library/functions.html).

Ahora, te explicaré una de las fórmulas del enunciado. Tomemos como ejemplo la siguiente:

![formula](https://user-images.githubusercontent.com/43896576/78955856-8a374e80-7aae-11ea-8a26-5d9138737b8f.PNG)

En primer lugar, tenemos que tener en cuenta que nos interesan valores entre 0 y 1, ambos inclusive. Esto es porque estamos hablando de probabilidades y otros valores no nos estarían dando información relevante sobre la posibilidad de ocurrencia de algo :)

Ahora, podemos notar que en la función `max` que está dentro de `min` tenemos dos valores. Lo qué hará la función `max` será escoger el máximo entre ellos dos. Esto lo hacemos porque puede suceder que el segundo término puede llegar a ser menor a cero en caso de que `resp_magizoologo` sea mayor a `efecto_hambre` 😱 Esta misma lógica se aplica para la función `min`.

Espero haberte ayudado, éxito en la tarea 🐳

**Comment by jorgemayol** [comment]
Muchas gracias!!!
