### ISSUE TITLE
Atributos en una nueva simulación

### ISSUE THREAD

**Issue by barbarafcp** [IIC2233/syllabus#377]
Cuando se acaban los días de la competencia, y si el usuario quiere realizar una nueva simulación, se debe restablecer la moral de los competidores, los atributos aumentados por los entrenamientos y todo eso? o solo las medallas de las delegaciones?

**Comment by hsazos** [comment]
¡Hola @barbarafcp !
 Se debe reestablecer todo dentro del programa. La simulación solo debe cambiar según las decisiones que tome el usuario como entrenador. Lo que hizo el entrenador anterior, o el mismo usuario en una simulación anterior, no debería afectar simulaciones futuras.

¡Animo con la tarea! 🦕
