### ISSUE TITLE
Crear más funciones aparte de las que dan/ AB

### ISSUE THREAD

**Issue by Bvv12** [IIC2233/Syllabus#377]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Se pueden crear más funciones aparte de las que ya dan? Específicamente para usarla en el sort

**Comment by igbasly** [comment]
Hoola @Bvv12 :v:

Sii, no hay problemas con que crees todas las funciones que estimes necesarias, así como otros módulos también. Eso si, siempre manteniendo el nombre de las funciones originales solicitadas, ya que esto afecta directamente la corrección.

Saludos y mucho éxito! 🎉
