### ISSUE TITLE
QGridLayout

### ISSUE THREAD

**Issue by SamWeinstein** [IIC2233/syllabus#377]
Hola! Cree el mapa usando GridLayout, el problema es que cuando agrego la casa o la tienda a una posición del grid, toda la columna y toda la fila respectiva se agrandan para que estos widgets quepan, dejando espacios libres a lo largo de toda esa columna/fila. Hay algo que se pueda hacer para que la casa y la tienda ocupen el espacio de dos columnas/filas consecutivas? Se me ocurre dividir la imagen en 4 y agregarlos por separado pero esto no me parece una buena solución. También se me ocurrió duplicar el tamaño de los tiles de las columnas/filas respectivas para que cubran el nuevo espacio agregado, pero el pasto no quedaría uniforme pues habrían algunos tiles de pasto amplificados.  Me podrían dar alguna sugerencia de como proceder? Sigo alguna de mis ideas o hay algo que no estoy viendo? Muchas gracias!!!

**Comment by aljara97** [comment]
Hola, esta duda ya fue respondida en la issje #357

**Comment by SamWeinstein** [comment]
No me di cuenta, gracias!
