### ISSUE TITLE
Variables con espacios

### ISSUE THREAD

**Issue by josemlira** [IIC2233/Syllabus#377]
["asignar", "x", 3]
["asignar", "  x ", 5]
Luego "x" debiese ser 5 o se debe tener que: "x" = 3 y "  x " = 5??

**Comment by Hernan4444** [comment]
"en teoria" esos dos strings son diferentes, pero al menos te puedo asegurar que por nuestra parte no pondremos espacios en las variables y por lo tanto ambas serían iguales para nosotros, es decir "x" queda como 5
Saludos!!

**Comment by josemlira** [comment]
Gracias!
