### ISSUE TITLE
Consultas min y max

### ISSUE THREAD

**Issue by mesantamaria** [IIC2233/Syllabus#377]
Hola,
quería saber si se le puede poner otro nombre a las funciones de consulta

- min(tag_caracteristica)
- max(tag_caracteristica)

porque sobrescriben a min y max que vienen predefinidas en python.

**Comment by Hernan4444** [comment]
@mesantamaria no es necesario que las funciones de tu librería tengan el mismo que nombre que las consultas.

Saludos ✌️

**Comment by fnquinteros** [comment]
De todas formas deja puesto en el readme cómo las llamaste 😉
