### ISSUE TITLE
Sobre las entidades afectadas por las bombas

### ISSUE THREAD

**Issue by dvillas28** [IIC2233/Syllabus#378]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En base lo que dijeron en la [issue 355](https://github.com/IIC2233/Syllabus/issues/355), el conejo, los lobos, y los cañones son afectados por la bomba manzana, mientras que para la bomba congeladora, solo con afectados el conejo y los lobos (reduciendo su velocidad)

Pero en la pauta se indica:
 - 1. Solos los lobos deberian ser eliminados por las Manzanas
 - 2. Solo los lobos deberian ser ralentizados por el Congelador, y esto deberia ser hasta que se acabe el nivel **o se pierda una vida**, mientras que en el enunciado se indica que el efecto debe mantenerse aun cuando se pierda una vida

![image](https://github.com/IIC2233/Syllabus/assets/128737225/26f9f75f-cf83-4bc9-ba98-cf23ee2fbfb0)

¿Estoy entendido mal la pauta? o ¿En base a cual nos deberiamos guiar? 🥶 
Saludos!

**Comment by cattpuccino** [comment]
¡Hola @dvillas28! Considerando el poco tiempo que queda para la entrega, te aconsejo elegir lo que más te acomode y esto especificarlo en el README, citando la issue. Así cuando se te corrija se considerarán las dos opciones.

**Comment by dvillas28** [comment]
Vale, muchas gracias!
