### ISSUE TITLE
Retorno de generador con "columnas"

### ISSUE THREAD

**Issue by akrebs2** [IIC2233/Syllabus#378]
Hola.
Cuando en las "consultas que retornan otra base de datos" se nos dice que debemos retornar, por ejemplo, "el generador con las películas de ese archivo y las demás columnas", a qué se refiere específicamente? Sé que puede parece media obvia la pregunta, pero no tengo claro si debemos entregarlo en un formato en específico, o basta con poder ir traspasando la información de generador en generador a través de una estructura de datos a elección, como listas, tuplas, diccionarios, etc?
Gracias de antemano

**Comment by Hernan4444** [comment]
@akrebs2 el formato queda a su criterio, tal como dices, pueden ir traspasando la información de generador en generador a través de una estructura de datos a elección, como listas, tuplas, diccionarios, etc. Con esa frase de:
> las películas de ese archivo y las demás columnas

Es para que no retornen solo el nombre de la película, sino que todo lo demás y así puedan ocuparlo en otra consulta.

Saludos ✌️

**Comment by akrebs2** [comment]
Gracias!

**Comment by pcseisdedos** [comment]
Cuando en la consulta popular_movies dice

> retorna todas las películas y sus demás columnas de movies que...

Es equivalente a retornar un generador con namedtuples (que sean las películas que cumplen la consulta y cuyos atributos sean las demás consultas) o bien, es requisito retornar todas las columnas y se busca evitar de cierta forma el uso de namedtuples.

**Comment by Hernan4444** [comment]
@pcseisdedos el formato de como retornas cada columna queda a tu criterio, que pidamos todo no evita que uses namedtuples. Lo que tienes que tener en cuenta que nosotros podemos hacer una consulta sobre el resultado de popular_movies y en ese caso, si justo no retornaste una columna y yo hago una consulta que use esa columna, deberás abrir nuevamente el archivo para buscar esos datos, lo cual lo hace más ineficiente.
