### ISSUE TITLE
Entrega de inputs()

### ISSUE THREAD

**Issue by ByDati** [IIC2233/Syllabus#378]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holaa, una consulta... se sabe que el menu debe ser a prueba de errores de usuario, pero se puede asumir que por lo menos van a respetar ciertos parametros? Por ejemplo, si se pide un numero dentro del menu y el input es "a", el programa se cae, ahi tenemos que encontrar una manera de evitar todo fallo posible?

Gracias de antemano :D

![image](https://github.com/user-attachments/assets/bc72dc1d-e4cb-40cb-a57f-d363ff3b584f)

**Comment by AndreaVict** [comment]
Holaa, tu programa debe ser capaz de manejar inputs inválidos sin que se caiga el programa. 
**Por ejemplo:** Si en una opción se pide el ingreso de un _int_, pero el usuario ingresa un _str_ (por ejemplo un "hola"), el programa debe ser capaz de avisar por consola que este es un input inválido sin caerse y volver a pedir otro input. 
Éxito en la tarea!!
