### ISSUE TITLE
Impresion del error

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#378]
Al imprimir el error dice que debo imprimir el comando con sus argumentos. ¿Son los argumentos que se ingresaron en ese momento especifico o son los argumentos generales que espera ese comando?

**Comment by Hernan4444** [comment]
@jorgeriesco los argumentos que se ingresaron en ese momento. Te sugiero leer la ultima respuesta de #328 que también se habla de los errores
Saludos!
