### ISSUE TITLE
Duda sobre uso de listas de compresión en generadores

### ISSUE THREAD

**Issue by Bonjour1X** [IIC2233/Syllabus#378]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Una pregunta, esta bien usar de esta manera la lista de compresión, en el caso en donde a 1 o más generadores las transformó por ejemplo en 
gen_1 = [valor for valor in generador_1]
gen_2 = [valor for valor in generador_2]
para que no se pierdan y que a la vez pueda hacer otra lista de compresión que iteré en ambas para sacar algo?
año_ = [valor_1.año for valor_2 in gen_2 for valor_1 in gen_1 .....] 
ya que en teoría sigue por compresión aunque sean 2 o más generadores
Como para saber si esta prohibido crear variables que tengan algún valor pero sacado por compresión como listas o diccionarios
valor_a = [x.algo for x in gen ...]
valor_b = [x.algo for x in gen ...]
y solo resolviendo así, como para agregar cosas o funciones como Counter(valor_algo) y así unir o separar casos ¿siguiendo esa lógica? 
y una duda extra, si usará condicionales if, elif o else para casos de comparar, igual debe estar comprimido o se puede omitir? para una función por ejemplo

**Comment by Bonjour1X** [comment]
Entonces no puedo seguir usando comprension de listas para definir cosas? Como con funciones importadas? Ya que lo he estado resolviendo algunas así y sacar las respuestas usando comprension de listas y/o diccionarios?

**Comment by Bonjour1X** [comment]
Entonces no puedo seguir usando comprension de listas para definir cosas? Como con funciones importadas? Ya que lo he estado resolviendo algunas así y sacar las respuestas usando comprension de listas y/o diccionarios?, pse me gustaria saber si lo que hice esta bn, en casi de aue puedan ver lo que llevo

**Comment by jfpantoja** [comment]
Si puedes usarlas de esa manera! En general las listas y estructuras generadas por programación funcional (comprensión, map, etc.) las puedes utilizar como las consideres necesarias.

**Comment by Bonjour1X** [comment]
Entonces no puedo seguir usando comprension de listas para definir cosas? Como con funciones importadas? Ya que lo he estado resolviendo algunas así y sacar las respuestas usando comprension de listas y/o diccionarios?, pse me gustaria saber si lo que hice esta bn, en casi de aue puedan ver lo que llevo
