### ISSUE TITLE
Parametros de borde

### ISSUE THREAD

**Issue by mnbenimeli** [IIC2233/syllabus#378]
Hola, en mi tarea para limitar el movimiento de las entidades cree un área que se ve delimitada por el borde del mapa. Con esto agregué uno valores numéricos que corresponden a un borde superior y lateral (por los bordes blancos que tiene la ventana fuera del mapa). Quería saber si estos valores los puedo dejar por defecto o también tienen que ser importados de parámetros.py

**Comment by hbkim94** [comment]
Hola @mnbenimeli,

La respuesta depende de cómo se adaptan esos valores a la configuración de tu ventana. Si estos valores no son dependientes del tamaño del mapa (es decir, que tenga más/menos elementos que los entregados) o de la ventana de juego (que nosotros decidamos agrandarla o achicarla por x motivos) y tus valores se adaptan al cambio "automáticamente",  entonces no es necesario que los pongas en `parametros.py`.

La verdad es que no debería darse el caso contrario, dado que tu programa debería manejar este tipo de situaciones. 

Espero haber aclarado tu duda! Suerte!
