### ISSUE TITLE
Adoptar primera criatura: orden del nombre y  su tipo

### ISSUE THREAD

**Issue by CatalinaGoldsack** [IIC2233/syllabus#378]
En el menú de inicio al crear el magizoólogo y adoptar la primera criatura: 
¿Es estrictamente necesario que primero se elija el tipo de criatura y luego se pregunte por cómo quiere que se llame esta?
¿No podría ser al revés?

**Comment by Dnpoblete** [comment]
Hola @CatalinaGoldsack, si lo puedes realizar al revés siempre y cuando no afecte a la creación de la criatura y funcione correctamente. Adicionalmente, sería bueno que lo dijeras en el ReadMe.

Éxito con la tarea! ✨

**Comment by CatalinaGoldsack** [comment]
Buenísimo! Muchas gracias :blush:
