### ISSUE TITLE
Duda menú de entrenador: imprimir estado actual de la competencia

### ISSUE THREAD

**Issue by FernandoLarrea** [IIC2233/syllabus#378]
hola, en el enunciado en la parte de flujo de programa dice que _"En los días de entrenamiento el usuario debe poder, desde el Menú Entrenador, imprimir el estado actual del torneo"_, pero en la parte de Menú entrenador no se encuentra esto como acción del entrenador, sin embargo, en el menú principal sí: _"el programa debe mostrar el Menú principal, desde el cual se puede simular el día de competencia correspondiente, **revisar el estado del campeonato**, acceder al Menú Entrenador y salir"_. 
No entiendo donde debe ir esa acción.

**Comment by mmunozmendez** [comment]
Hola!
Es un error en el flujo del programa, la acción debe estar en Menú Principal.

Éxito!
