### ISSUE TITLE
Cambiar tamaño de ventana

### ISSUE THREAD

**Issue by vnespinosa** [IIC2233/syllabus#378]
Hola, es necesario que el juego se adapte al tamaño de la ventana?
Es decir, si agrandan la ventana y no se mueve el mapa ni nada, daria descuentos eso?

**Comment by aljara97** [comment]
Hola, si te refieres a que agrandaremos la pantalla manualmente, puedes asumir que no haremos esto. Sin embargo, tu programa debe mostrar una ventana sin elementos superpuestos entre sí, para cualquier parámetro N a definir

**Comment by dgzmr** [comment]
@aljara97 el parámetro N se refiere al número de pixeles?

**Comment by aljara97** [comment]
Exacto, el número de pixeles de ancho y largo de cada espacio del mapa
