### ISSUE TITLE
[ACB] Resultado de obtener_mejores_atacantes

### ISSUE THREAD

**Issue by agucova** [IIC2233/Syllabus#378]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/293)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En la especificación de `obtener_mejores_atacantes`, solo se especifica que se debe 
> "(...) entregar una lista con los 5 mejores pokémon atacantes ordenados de forma descendente."

No queda claro cual es el formato de cada pokemon, especialmente en vista de que este ejemplo posterior:

![image](https://user-images.githubusercontent.com/4694408/146287749-756ec367-b839-4469-afa4-bd96e4c37307.png)

Da a entender que se debe crear un diccionario individual para cada pokémon con llaves `name`, `attack` y `defense`, distinto al formato en que se encuentran los pokémones en la lista recibida por la función.

**Comment by marcosfernandezr** [comment]
Hola! Tengo la misma duda e intenté el formato que se muestra en la sección de enviar tests, pero me dice que no cumple el formato solicitado. Cabe destacar que todos los demás test me dan correctos. Gracias de antemano.

**Comment by igbasly** [comment]
Hola! :v:

Tal como se mencionó en la issue #370, en el enunciado se dice que la función debe retornar una lista con los 5 primeros Pokémon, a lo cual se entiende que serán los mismos objetos recibidos en el argumento `pokemones`.
En el caso del ejemplo del test, pueden tomarlo como que fue un error del ejemplo o que simplemente es un ejemplo de un test que va a fallar.

Espero se entienda, quedo atento.

**Comment by RorroReyes** [comment]
hola! tengo una duda en lo que dice al final de esa función, "En caso de un pokemon no posea uno de los atributos ("attack"o"defense"), debe ser ignorado. Si la lista resultante posee menos de 5 pokemones, entonces debes retornar toda la lista manteniendo el orden descendente." Cuando hay menos de 5 pokemonse, ¿se devuelve la lista teniendo primero los pokemones seleccionados, y después los pokemones recibidos en el argumento en el orden que vienen?

**Comment by igbasly** [comment]
Hola @RorroReyes

Solo debes retornar una lista con los Pokémon "seleccionados" ordenados de forma descendiente por su potencial de ataque como se indica en el enunciado. Si durante la evaluación de los Pokémon, te encuentras con alguno que no posea esos atributos, entonces se ignora y ya se acorta la lista de "seleccionados".
Por último, debes seleccionar los 5 mejores, pero puede que en el proceso te hayas quedado con menos de 5 y por lo tanto ahí debes retornar los que hayan quedado, respetando lo del orden descendiente.

Se entiende ahí??
Quedo atento 😉
