### ISSUE TITLE
Sebreescribir resultados.txt

### ISSUE THREAD

**Issue by MrEarle** [IIC2233/Syllabus#378]
Cuando uno debe escribir los resultados del query_array en resultados.txt, hay que continuarlo o sobreescribirlo?

**Comment by Hernan4444** [comment]
@MrEarle No está especificado pero yo recomiendo continuarlo 👍.

Saludos

**Comment by fdominguezclaro** [comment]
Tienes que continuarlo. 
Saludos!!

**Comment by fedetaladriz** [comment]
@Hernan4444 No habrá descuento de puntaje si lo sobrescribo? Ya que continuarlo implica leer el archivo y llegar hasta la ultima linea para encontrar el numero de linea de la ultima consulta.

**Comment by Hernan4444** [comment]
@fedetaladriz no hay problema si es que lo especificas en el readme.
Saludos ✌️
