### ISSUE TITLE
[ACB] Uso de la librería estándar

### ISSUE THREAD

**Issue by agucova** [IIC2233/Syllabus#379]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Dado que no hay un issue de malas prácticas, no sé si se puede utilizar librerías en la actividad bonus.

En mi caso particular, quiero utilizar `typing` y `__future__.annotations` para agregarle [type hints](https://www.python.org/dev/peps/pep-0484/) a mi código, ambos parte de la librería estándar.

**Comment by igbasly** [comment]
Hoola! ✌️ 

Para esta actividad no es necesario utilizar otras librerías, ya que al corregirse de forma automática, no nos responsabilizamos si es que la librería a importar está instalada o no. En caso de que un test falle producto de esto, se considerara incorrecto.
Dicho eso, en este caso no debería haber problemas con utilizar los módulos que mencionas, pero cualquier error de ejecución es bajo tu responsabilidad.

Espero se entienda, quedo atento 😉
