### ISSUE TITLE
Duda con creación de listas de listas y yield de tuplas

### ISSUE THREAD

**Issue by tomasvasquezp** [IIC2233/Syllabus#379]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
 Hola! tengo una duda, cuando creo listas por comprensión, es posible ir creando listas dentro de estas pero juntando variables y así formar listas de listas? es decir, si yo hago esto: lista = [[x.cosa1, x.cosa2] for x in generador], es lícito?

Aparte de eso, puedo retornar una tupla de la forma: yield (x[1], x[2])?

Gracias!
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by tomasvasquezp** [comment]
lo revisé y en algunos casos me da True y en un solo caso me da False

**Comment by TomasGMDC** [comment]
@tomasvasquezp eso respecto al primer punto? Te da error con el uso de lo que indicaste en esta issue? Recuerda que el script indica dónde está el error y cuál es.

**Comment by tomasvasquezp** [comment]
si, fue con respecto al primer punto, en algunas funciones creo listas dentro de otras listas cómo mostré antes y ningún problema pero hay solo 1 una función donde me da False siendo que hice exactamente lo mismo en las otras funciones, y vi donde tenía el error y me indicaba que usaba List pero en los otros no me daba ningún problema

**Comment by TomasGMDC** [comment]
@tomasvasquezp puedes hacer un push de tu código he indicarme la consulta y la línea con el problema?

**Comment by tomasvasquezp** [comment]
ahí hice push, es en ganadores por distrito, línea 238. al final logré hacerla pero sin el método que te mencioné antes pero añadí muchas líneas de código y creo que ya encontré el problema, era porque mientras hacía las pruebas con el test_elementos_prohibidos todavía no hacía yield, entonces puede ser que todavía no la detectaba cómo una función generadora, porque si eliminó la línea de yield, ahí me tira el error

**Comment by TomasGMDC** [comment]
@tomasvasquezp efectivamente ese es un problema. Un compañero tuyo hizo algo parecido y empleó un list() dentro de una lista de comprensión, y le salió malo. En conclusión, no se pueden crear estructuras de datos excepto en una función generadora o dentro de un reduce(), tal y como se dice en " #339 ", así que tampoco se puede hacer dentro de una lista por comprensión, a menos que esta esté dentro de una función generadora.

Lo más importante es que te guíes por el script, dado que con ese se realizará la revisión.
