### ISSUE TITLE
ModuleNotFoundError: No module named 'gui.Gui'

### ISSUE THREAD

**Issue by odbravo** [IIC2233/Syllabus#379]
Al intentar correr main.py me tira el error "ModuleNotFoundError: No module named 'gui.Gui'". Intenté importarlo de diferentes formas y me sigue tirando error, ¿Qué puede estar pasando?

**Comment by fdominguezclaro** [comment]
Estás trabajando en el directorio de la T03? Sólo se me ocurre que la carpeta gui (correspondiente a la T03) no está en el mismo directorio en el que está tu tarea.

Avísame si no te resulta!!
Saludos

**Comment by fjaraneda** [comment]
A mi me pasa lo mismo!, pero si lo dejo solo como Gui y no gui.Gui si me funciona, pero como no se puede modificar eso no se que hacer

**Comment by Hernan4444** [comment]
@fjaraneda desde donde estás abriendo el programa? a veces tira ese error porque estás abriendo todo desde una carpeta más "lejana". Si aún persiste el error, te recomiendo comentar la linea que dice `gui.Gui` y poner la que te sirva. De este modo, si el ayudante no le funciona tu solución, puede volver a descomentar la linea original y ahí debería funcionarle.

**Comment by fjaraneda** [comment]
@Hernan4444  lo estoy abriendo desde la carpeta de la tarea que incluye la carpeta gui tambien

**Comment by fringlesinthestreet** [comment]
@fjaraneda Hola :)

Por casualidad estás usando Atom? Lo que pasa en algunos editores es que debes tener ojo qué directorio pones de raíz para el proyecto. Mira la siguiente imagen:

![captura de pantalla 2017-10-01 a la s 13 39 10](https://user-images.githubusercontent.com/20802067/31056764-a08f3486-a6ad-11e7-9847-8dedcf5e4e7a.png)

La raíz del proyecto es la carpeta Syllabus por lo que si estoy en el directorio T03 debo hacer _import_'s con _path_ relativo. Esto se harían de la siguiente manera:

```import .gui```

En cambio si uno define la raíz como la misma carpeta (como en la siguiente imagen)

![captura de pantalla 2017-10-01 a la s 13 42 30](https://user-images.githubusercontent.com/20802067/31056784-030c4888-a6ae-11e7-9a06-998ac99f260a.png)

Uno puede hacer los _import_'s normales :).
