### ISSUE TITLE
Duda Menú Jardin, Regar

### ISSUE THREAD

**Issue by MTGG123** [IIC2233/Syllabus#379]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado se dice que una vez que se riega una planta, se debe imprimir la salud antes y despues del riego, y muestra un ejemplo (Un Solaretillo en (3,2) ha subido su salud de 10 a 20) pero no menciona nada de imprimir las coordenadas o el nombre de la planta, es necesario hacerlo?

**Comment by AndreaVict** [comment]
Holaa, como no se especifica en el enunciado, queda a tu criterio si implementar las coordenadas y el nombre de la planta, lo que se pide obligatoriamente es imprimir la salud antes y después de aplicar el riego. Recuerda especificar la decisión que tomaste en el README. Éxito en la tarea!!

**Comment by MTGG123** [comment]
> Holaa, como no se especifica en el enunciado, queda a tu criterio si implementar las coordenadas y el nombre de la planta, lo que se pide obligatoriamente es imprimir la salud antes y después de aplicar el riego. Recuerda especificar la decisión que tomaste en el README. Éxito en la tarea!!

Okkk, muchas graciass
