### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#379]
¿Debe ir el testing relacionado con la interfaz o solo pruebo las funciones internas del programa? Ya que si va relacionado con la interfaz sería raro y creo que no se pueden hacer inputs dentro de un test.

**Comment by afcarvallo** [comment]
Otra pregunta del testing: 
En el enunciado dicen hay que **"verificar que si ocurre un error se arroje excepción correspondiente a ese error"**, eso es lo mismo que **"testear  los 5 tipos de errores distintos"** que mencionan más abajo, a que se refieren con testear el error?

**Comment by iqacevedo** [comment]
Hola !
@jorgeriesco para hacer el testing ingresa las consultas "a mano" para probar tus funciones (es decir pruebalas con el mismo formato que las recibes en la interfaz).
@afcarvallo a eso se refiere, ya que debes generar las excepciones cuando ocurran los errores mencionados.

Saludos !

**Comment by Hernan4444** [comment]
@afcarvallo complementando la respuesta, las excepciones se trabajan en dos partes: la primera es durante el programa donde las usas para avisar cada error que suceda (y así tu programa nunca se cae) y la segunda es durante el testing donde verificarás que las excepciones se ejecuten cuando tengas un error.

Saludos!
