### ISSUE TITLE
Conectar una señal a muchas clases

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#379]
Hola, es posible que una señal se conecte a el mismo de metodos de muchas clases?
Por ejemplo en mi caso quiero hacer una señal de posicion de moneda que se conecten al metodo ` recoger_monedas` de todas las clases `Moneda`.

**Comment by VicenteMerino** [comment]
Sobre esta misma linea, es posible que en una señal se emit a la misma clase (algo así como que si tengo una clase `Moneda`, con una señal `signal` conectada a una clase personaje, pueda hacer `signal.emit(self))`

**Comment by hbkim94** [comment]
Hola @VicenteMerino ,

En respuesta a tu primera pregunta, sí. Una señal puede conectarse a varios slots (al final, según tu caso es que están conectados al mismo método de múltiples instancias que son independientes de otras, así que no debería haber problema).

En cuanto a lo segundo, tengo entendido que se pueden mandar objectos a través de señales. Ahora, no lo he probado con `self` , pero no estoy muy segura de qué tan correcto sería hacerlo de esa forma. Pero si quieres explorar el tema, encontré una issue en [stackoverflow](https://stackoverflow.com/questions/4523006/pyqt-signal-with-arguments-of-arbitrary-type-pyqt-pyobject-equivalent-for-new) que trata del envío de un objecto cualquiera a través de una señal.
