### ISSUE TITLE
Costo de Mantención

### ISSUE THREAD

**Issue by mfernandaestrada** [IIC2233/syllabus#379]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado se menciona que el canal paga un costo de mantención a los barcos que se encuentran en el canal en cada simulación. Mi duda es si se consideran los barcos que encallaron dentro de los barcos a los que se debe pagar mantención, o solo se consideran los barcos que "no generan problemas" en el canal.

Saludos :)

**Comment by santiagovegaf** [comment]
Hola @mfernandaestrada!

Como no se especifica que tipos de barco el canal debe pagar mantención es correcto asumir que todos pagan, independientemente de si están encallados o no!

Suerte :rocket:
