### ISSUE TITLE
Error con PyQt en Sublime Text 3

### ISSUE THREAD

**Issue by aydenbraber500** [IIC2233/syllabus#379]
Hola!
Resulta que al prender mi computador hoy, sublime me reportó que python no existía en mi computador. Al reinstalarlo con todos las herramientas necesarias, me entrega el siguiente error a la hora de importar los módulos de pyqt
![eror1](https://user-images.githubusercontent.com/53804772/66078777-103f6f00-e539-11e9-9ea5-1508a4723a55.png)
ayuda
uwu

**Comment by aljara97** [comment]
Hola, tuve exactamente el mismo problema al reinstalar Pycharm hace unos días. Probablemente al reinstalar python se eliminaron varias de sus librería, entre ellas PyQt5. Te sugiero instalarlo nuevamente en la terminal con el comando ````pip install PyQt5````

Cuéntame como te va y mucho éxito con tu tarea 😉

**Comment by aydenbraber500** [comment]
Al instalar PyQt5 me sigue saliendo el mismo error al momento de correr un código donde se importa PyQt5

**Comment by aljara97** [comment]
Otro caso puede ser que al reinstalar tu editor de texto, la versión de Python configurada para ese editor es una distinta a la 3.7. Para verificar esto te recomiendo revisar en tools/Build System y verificar la versión en la que estás trabajando

**Comment by aydenbraber500** [comment]
Muchas gracias por la ayuda, pero revisé la versión de python usada y era la correcta, por lo que parece ser que el problema es de pyqt en si, ya que al momento de hacer correr un archivo que utiliza módulos de pyqt desde la terminal, arroja el mismo error :c

**Comment by aljara97** [comment]
Hola, al final pudiste solucionar tu problema?

**Comment by aydenbraber500** [comment]
Hola, pude solucionar el problema ayer la verdad, tuve que reinstalar completamente python eso sí
