### ISSUE TITLE
Diferencia entre puntos de salud actuales y puntos de salud totales

### ISSUE THREAD

**Issue by fmartint** [IIC2233/syllabus#379]
Hola! Tengo un confusion con los puntos de las criaturas.
Cuando hablan que una criatura pierde puntos de salud por estar enferma o con hambre, cuales puntos son? Cuando hablan de la multa por que los puntos llegan al mínimo de la salud cuales son? Ya que cuando explican los puntos de salud actuales dice que el mínimo es 1 y no puede superar los puntos totales máximo. "Su valor no puede superar los puntos de salud total, y tiene como valor mínimo 1."

**Comment by moquezada** [comment]
Hola @fmartint,

Cuando una criatura pierde puntos de salud nos referimos a los **puntos de salud actuales**. En el caso de la multa porque los puntos de salud llegan al mínimo también nos referimos a los puntos de salud actuales :)

Saludos!
