### ISSUE TITLE
for y yield

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2233/Syllabus#379]
Hola, es legal hacer lo siguiente para retornar un generador al leer los archivos csv

```
def leer_csv:
    ..... 
    ..... 
    for x in lista_de_Named_Tuples:
         yield x
```

**Comment by Hernan4444** [comment]
@joaquineichholz si está permitido, al fin y al cabo estás iterando dentro de una función generadora lo cual si se permite según enunciado.

Saludos ✌️

**Comment by norman123123** [comment]
O sea que puedo hacer lo que quiera con "for" mientras sea dentro de una funcion generadora en vez de una funcion normal??
Entonces puedo usar un for sobre un iterable dentro de una funcion generadora?
   
 for item in esto_es_una_lista:
        yield funcion(item)

???
