### ISSUE TITLE
Ejercicio 2.1: abrir archivo

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#38]
No sé como abrir el archivo . el path que utilice fue 'ejercicios_propuesto/cards.csv'. Pero no se me abre el archivo.

**Comment by Juampisaez** [comment]
Holaa @enriquemolinare 
Probablemente el error que te lanza es que no encontró la carpeta ejercicios_propuesto en el path en el que te encuentras
> FileNotFoundError: [Errno 2] No such file or directory: 'ejercicios_propuesto/cards.csv'

Me da la impresion de que trataste de abrir en jupyter el archivo cards.csv en ejercicios_propuesto.ipynb. En este caso como ambos archivos se encuentran en la carpeta 'ejercicios_propuesto', no es necesario referenciar esta carpeta ya que te encuentras en ella. **Trata de ocupar como path simplemente el nombre del archivo --> cards.csv**.

Avisame si se soluciona el problema.

**Comment by enriquemolinare** [comment]
Holaa, gracias por la ayuda. Sin embargo todavía no me funciona. (estoy corriendo el código en jupyter)
este es mi código 
> with open(cards.cvs, 'rt') as archivo:
              lineas=archivo.readlines()
print(lineas)

**Comment by Juampisaez** [comment]
Tal vez sea un problema de identacion, fijate en eso aca te mando un ejemplo.
```
with open("cards.csv", "rt") as file:
    lineas = file.readlines()
print(lineas)
```
Si eso no funciona, muestrame el error que retorna.
Avisame si se soluciona

**Comment by enriquemolinare** [comment]
siii, ahora me funcionó. 
Gracias!!

**Comment by sreitze** [comment]
Hola, a mi me corria el mismo error, pero resulta que al descargar el archivo cards, de descargo como archivo de texto entonces tuve que poner 'cards.txt' en vez de 'cards.csv'. Como puedo hacerlo para que este como csv y no como txt ??(si es el necesario).

**Comment by Juampisaez** [comment]
Hola @sreitze 
Podrías probar dos cosas:
- La primera (y mas facil) es que abras la carpeta (donde se encuentra el archivo "cards") en vscode, y le cambies el nombre de cards.txt por cards.csv. Te dejo una foto de como deberias hacerlo.
![image](https://user-images.githubusercontent.com/48323752/90704091-918d1680-e25d-11ea-8ba0-c517ee3f66a8.png)

- La segunda es que borres la carpeta de contenidos que clonaste en tu computador, y lo vuelvas a hacer de la misma forma que lo hiciste en un inicio.

Espero que te ayude, avisame cualquier cosa

**Comment by sreitze** [comment]
Con la primera me funcionó, muchas gracias!
