### ISSUE TITLE
Carpeta.gitignore

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#38]
¡Hola!
Quería saber si basta subir una carpeta.gitignore o también es necesario que los archivos dentro de ella tengan la misma extensión. Sé que no se evaluará el .gitignore, pero me gustaría saber :)

**Comment by DCCollao** [comment]
Hola @jamigone!

`.gitignore` no debe ser una carpeta, sino que debe ser un archivo. Dentro de él es donde se escribe(tal como si fuera un archivo .txt) lo que no quieres subir a github.

Éxito!

**Comment by jamigone** [comment]
ahh, pero en mi repositorio personal igual pude subir los archivos.gitignore jajaja. ¿Debería borrarlos?

**Comment by DCCollao** [comment]
Lo ideal sería que tuvieras solamente un archivo `.gitignore` con todos los archivos a ignorar mencionados dentro de él
