### ISSUE TITLE
Duda respecto al uso de código no creado por mi 

### ISSUE THREAD

**Issue by Sebastian-Assereto** [IIC2233/Syllabus#38]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
Me gustaria saber como funciona el uso de codigo no creado por mi, obviamente este codigo no haria uso de las librerias prohibidas, pero no tengo del todo claro que tipo de codigos puedo utilizar, o si deben provenir de alguna fuente en especifico, en mi caso es de Youtube
Además me gustaria sabe que si finalmente me decidiera por utilizarlo, donde deberia informar que lo utilice, comentarlo en mi propio codigo, o al momento de escribir el readme, Saludos  
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by vicentethomas** [comment]
Hola! No hay límites para referenciar código externo mientras sea debidamente citado en tu readme de la tarea, en la sección del final: 
![image](https://user-images.githubusercontent.com/80768650/185758387-3a1f0820-40b5-4237-a459-2458c2a12a3d.png)
En computación es muy común buscar en internet los problemas que puedan aparecer, u otras formas de resolver algo que se quiere lograr. Por lo tanto, no dudes en consultar en internet ya que es de gran utilidad y una herramienta válida para el aprendizaje 😄 Siempre cuidando de citarlo debidamente para no caer en plagio, y de no usar ninguna de las librerias o métodos prohibidos de la tarea.
Por otro lado, no es obligatorio pero también puedes marcar en tu código (con un comentario por ejemplo) las partes que se referencian como citas en el readme para facilitar correción.
Saludos!

**Comment by Sebastian-Assereto** [comment]
Por lo tanto no habría problema en copiar y pegar código existente en Internet, mientras haga referencia a de donde lo obtuve?

**Comment by vicentethomas** [comment]
Exactamente. Lo importante es que entiendas qué es lo que estás copiando y pegando, por eso se pide que expliques lo que hace esa parte del código en el readme.
