### ISSUE TITLE
Problema con el ejercicio 3.1 de la semana 2

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#38]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Estaba haciendo los ejercicios de la semana 2 y en el caso del ejercicio del título (3.1), el programa entregado por el ejercicio (que yo no he tocado) me lanza un error que no me hace sentido, ya que dice que se entregan 5 elementos cuando la clase recibe 4. Imagen incluida para explicitar el problema.
![image](https://user-images.githubusercontent.com/43099597/159564685-33daf15a-2f87-49e4-84d2-cc600fd013cf.png)
Y lo principal de la duda es que no entiendo como el programa piensa que hay 5 cosas entregadas cuando claramente son sólo 4...

**Comment by Mamunoz42** [comment]
Hola @MaxAl100! 😃 

Por lo que veo en la imagen subida, agregaste en el `__init__` de la clase `Muser` el super, sin embargo, le entregas como uno de los parámetros self, sin embargo al igual que cuando se instancia una clase, no se debe agregar el self. 

Ahora entrando a lo que dice el error, está diciendo que se le entregan 5 argumentos, ya que a simple vista se le están entregando 4, los que tú agregaste, sin embargo, python por detrás está entregándole el self, y por eso aparece que son 5.

Espero quede claro, y en caso que sigas con duda no dudes en comentar esta issue 😄

**Comment by MaxAl100** [comment]
Cierto, cierto, se me había ido que en la herencia no era necesario poner el self...

Muchas gracias! 😄 👌
