### ISSUE TITLE
Error: 'PermissionError: [Errno 13] Permission denied'

### ISSUE THREAD

**Issue by Cristi512** [IIC2233/Syllabus#38]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, estoy haciendo la tarea y al intentar escribir algo en el archivo 'usuarios.csv' me tira el error 'PermissionError: [Errno 13] Permission denied'. Busqué en google y encontré que una solución a esto es usar comandos para cambiar los permisos de los archivos pero no estoy seguro que sea buena idea hacer eso. ¿Cómo puedo arreglar esto?

Gracias.

**Comment by IgnacioEngelberger** [comment]
Hola, a mi me paso lo mismo unas veces y era por tener el archivo abierto en excel. Espero que te sirva 🙆‍♂️

**Comment by Cristi512** [comment]
> Hola, a mi me paso lo mismo unas veces y era por tener el archivo abierto en excel. Espero que te sirva 🙆‍♂️

Sii eso era jajaja gracias
