### ISSUE TITLE
Consulta: Recursos / Fecha y Hora / Base de datos

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#38]
En primer lugar, cuando se asignan recursos a un incendio, o cuando incendios empiezan a ser trabajados por recursos, esta información debe permanecer si se cierra y abre el programa?, osea que cuando el programa se abra debe saber que recursos van/estan en que incendio, que incendios tiene  que % de puntos de poder, etc? 

En segundo lugar, cuando se asignan recursos, la posición de estos solo cambia cuando se reasigne la hora/fecha?

En último lugar, la base de datos de usuarios tiene tíldes y eñes por lo que al tratar de pasarla a python explota por los carácteres, hay alguna forma de evitar esto? 

Gracias!

**Comment by rpalmaotero** [comment]
> En primer lugar, cuando se asignan recursos a un incendio, o cuando incendios empiezan a ser trabajados por recursos, esta información debe permanecer si se cierra y abre el programa?, osea que cuando el programa se abra debe saber que recursos van/estan en que incendio, que incendios tiene que % de puntos de poder, etc?

No es necesario que las estrategias persistan entre ejecuciones, pero sí deben ser guardadas en el sistema de archivos cuándo son calculadas. Revisa el último párrafo del punto 5) del enunciado.

> En segundo lugar, cuando se asignan recursos, la posición de estos solo cambia cuando se reasigne la hora/fecha?

Claro.

> En último lugar, la base de datos de usuarios tiene tíldes y eñes por lo que al tratar de pasarla a python explota por los carácteres, hay alguna forma de evitar esto?

Revisa #39.

**Comment by KnowYourselves** [comment]
gracias!
