### ISSUE TITLE
Cantidad de mercados tarea 1

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#38]
Hola queria saber la cantidad de mercados que debemos crear para nuestras tareas, ya que al haber 7 divisas distintas me hace pensar que hay que crear 42 mercados.

**Comment by cilopez** [comment]
Si, deberían haber 42 posibles mercados ya que los mercados del tipo NECNEC no tienen sentido

**Comment by nmaturana97** [comment]
gracias

**Comment by cilopez** [comment]
@nmaturana97 Me equivoqué anteriormente en tu pregunta, **solo hay 7 mercados**, todos los mercados son una criptomoneda vs DCCoins, disculpa por el error

**Comment by IchottMano** [comment]
Muchas gracias por la aclaración!

**Comment by movaldivia** [comment]
@cilopez Estás seguro porque abrí las orders y hay cosas como BANRIN, NECRUP que según entiendo no tienen DCCoins. De hecho a ojo no veo ninguna acción con DCCoins, al parecer SOLO sirven para mejorar de trader a Investor o no?

**Comment by FernandoPieressa** [comment]
lean la issue #54
