### ISSUE TITLE
Problema al abrir y utilizar dcciudad.pyc

### ISSUE THREAD

**Issue by asapsanchez** [IIC2233/Syllabus#38]
Hola, el archivo dcciudad.pyc no se me abre en visual studios y no puedo usar las funciones contenidas en el archivo, como se podría solucionar? Gracias

**Comment by pedrozavalat** [comment]
Hola @asapsanchez !

Te recomiendo ver la issue #22 , ya que se menciona específicamente que el archivo `dcciudad.pyc` es un archivo Python Compilado, por lo que no es legible ni para VSCode u otro IDLE 😅 .

Además, recuerda ir revisando las _issues_ anteriores para verificar que tu duda no ha sido realizada anteriormente por otro estudiante 👀 (como por ejemplo el [Compilado de Issues de la T1](https://github.com/IIC2233/Syllabus/issues/20))

Saludos! 😄

**Comment by asapsanchez** [comment]
> Hola @asapsanchez !
> 
> Te recomiendo ver la issue #22 , ya que se menciona específicamente que el archivo `dcciudad.pyc` es un archivo Python Compilado, por lo que no es legible ni para VSCode u otro IDLE 😅 .
> 
> Además, recuerda ir revisando las _issues_ anteriores para verificar que tu duda no ha sido realizada anteriormente por otro estudiante 👀 (como por ejemplo el [Compilado de Issues de la T1](https://github.com/IIC2233/Syllabus/issues/20))
> 
> Saludos! 😄

Si lo había visto, pero lo que pasa es que tampoco me deja importarlo con "import" por lo que no puedo usar las funcionas definidas en el archivo. Como se podría solucionar?

**Comment by pedrozavalat** [comment]
@asapsanchez 
Tal como se responde la issue #22, 

> "... Respecto a que en un módulo esté subrayado en amarillo, eso no implica que haya un error, solo es un warning de la IDLE (asumo que VSCode) porque no logra entender qué es dcciudad o algún warning similar, pero no olvidar que VSCode solo es para programar, pero quien ejecutará todo es python desde la terminal. Por lo tanto, lo importante es que desde la terminal puedan hacer python3 archivo.py y todo funcione bien. ..."

El subrayado en amarillo es propio de VSCode (si es que estas trabajando en este entorno), ya que no logra entender la variable ```dcciudad``` al ser un archivo Python Compilado. A pesar del _warning_, este no deberia afectar dentro de las funcionalidades implementadas en tu programa. 

Por otra parte, no entiendo muy bien a lo que te refieres con que no te deja utilizar las funciones, en este caso ¿Que error te entrega el programa?

Saludos 😄
