### ISSUE TITLE
"Import (ejemplo) could not be resolved" Problema de importacion de los archvios main.py y loader.py de la actividad 1.

### ISSUE THREAD

**Issue by anticarasosman** [IIC2233/Syllabus#38]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido

No se muy bien como continuar una ves tengo los archivos main.py y loader.py, use cd para llegar a mi repositorio personal, cree una carpeta que llame "Testeo". Ahi use git pull para guardar los archivos de utils/, cree 2 archivos .py (main.py y entities.py) y tambien los guarde en la carpeta Testeo/. Pero cuando intento correr el codigo en Visual Studio, me sale "Import "entities" could not be resolved" en el archivo loader.py. y "Import "utils.pretty_print" could not be resolved" en el archivo main.py

**Comment by DaniloCordova13** [comment]
Hola! Me ocurrió algo parecido. A mi también VScode me tiraba error cuando quería ocupar el import entities en el archivo loader.py, no entendía por qué siendo que loader.py estaba dentro de utilis, la cual estaba dentro del directorio EX1. Resulta que corrí el código "a la fuerza" desde la terminal y no me tiró ningún error. Mi teoría es que tenía algo que ver con VScode, pero no necesariamente hay algo malo en el código. De todas formas, esto es una teoría mía, puede que si haya algún error y a mi funcionó el código en la terminal por otra razón que desconozco. Intenta correr el código igual en la terminal a ver si es que te funciona. 
Saludoos! :smile:

**Comment by dvillas28** [comment]
>  y a mi funcionó el código en la terminal por otra razón que desconozco.


@DaniloCordova13 Debe ser porque en la terminal corriste el programa desde un path distinto al que corriste en la terminal del VScode. 
Saludos 😄

**Comment by anticarasosman** [comment]
> Hola! Me ocurrió algo parecido. A mi también VScode me tiraba error cuando quería ocupar el import entities en el archivo loader.py, no entendía por qué siendo que loader.py estaba dentro de utilis, la cual estaba dentro del directorio EX1. Resulta que corrí el código "a la fuerza" desde la terminal y no me tiró ningún error. Mi teoría es que tenía algo que ver con VScode, pero no necesariamente hay algo malo en el código. De todas formas, esto es una teoría mía, puede que si haya algún error y a mi funcionó el código en la terminal por otra razón que desconozco. Intenta correr el código igual en la terminal a ver si es que te funciona. Saludoos! 😄

Me sigue saliendo un error, pero en este caso "No module named "utils"", solo para confimar, para correr un archivo python es solamente python3.nombre_de_archivo.py ¿verdad?

**Comment by Hernan4444** [comment]
Hola, 

Para correr un archivo si, basta con hacer `python3 nombre_archivo.py` Ahora bien, ese error es porque no detecta una carpeta llamada `utils`. Tu directorio debería verse así

![image](https://github.com/IIC2233/Syllabus/assets/15641721/3aa25db5-68f8-4f15-9831-ce9c15b8454f)


Tal vez copiaste todos los archivos de utils fuera de dicha carpeta y por eso se queja el código,

Avísanos cómo te va con (1) asegurando que tu directorio se vea con el mismo formato de la foto, es decir, 2 archivos y una carpeta llamada utils, y (2) ejecutando desde tu terminal `python3 main.py`

Saludos!

**Comment by Dvckhv** [comment]
Para ejecutar el codigo desde la consola debes ubicarte en tu carpeta `Testeo` y ejecutar  `python3 nombre.py` (con espacio),  `nombre.py` es el nombre del archivo que quieres ejecutar. Cuentame si te funciona :)

**Comment by anticarasosman** [comment]
> Hola,
> 
> Para correr un archivo si, basta con hacer `python3 nombre_archivo.py` Ahora bien, ese error es porque no detecta una carpeta llamada `utils`. Tu directorio debería verse así
> 
> ![image](https://user-images.githubusercontent.com/15641721/262066280-3aa25db5-68f8-4f15-9831-ce9c15b8454f.png)
> 
> Tal vez copiaste todos los archivos de utils fuera de dicha carpeta y por eso se queja el código,
> 
> Avísanos cómo te va con (1) asegurando que tu directorio se vea con el mismo formato de la foto, es decir, 2 archivos y una carpeta llamada utils, y (2) ejecutando desde tu terminal `python3 main.py`
> 
> Saludos!

Era exactamente eso, muchas gracias por la ayuda.
