### ISSUE TITLE
Problema al correr el codigo en jupyter

### ISSUE THREAD

**Issue by nsancha** [IIC2233/syllabus#38]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

- [X ]  Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)

* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Cuando trato de hacer los ejercicios propuestos en jupyter, no me funciona, corro una vez el código y funciona con normalidad pero si quiero volver a correrlo deja de funcionar, probé cerrando y abriendo jupyter, reiniciando el computador pero me sigue pasando lo mismo, esto no me había pasado días anteriores pero no he hecho nada diferente

**Comment by pedroriosg** [comment]
Hola @nsancha ✌️ 

Según lo que me indicas, creo entender que es lo que te está pasando.

Cada vez que ejecutas código, las variables que están definidas en la celda se guardan en el `kernel`. Te recomiendo que cada vez que hagas cambios en alguna variable y quieras ejecutarla, reinicies el `kernel`, y corras las celdas de nuevo. De esta manera, las variables se actualizaran nuevamente y no tendrás problemas (`Restart` o `Restart & Clear Output` debiesen funcionar).

<img width="571" alt="Captura de Pantalla 2021-03-25 a la(s) 00 12 56" src="https://user-images.githubusercontent.com/69609154/112413382-dc44a480-8cfe-11eb-85e6-24b5474dc2fb.png">



Avísame si te funciona!
