### ISSUE TITLE
"Vida de un soldado", "vida de un mago"

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#38]
En el enunciado de la tarea 1 sale que tras la batalla, para calcular el número de soldados/magos sobrevivientes se usan unas fórmulas que usan "vida de un soldado" y "vida de un mago" como parámetros. Como estas variables toman valores que oscilan en un rango, ¿Qué vida pongo?

Además, suponiendo que inicié con 25 soldados y tras la batalla sobreviven 15, ¿cómo decido cuáles diez eliminar de mi ejército? (aleatorio, los con menor vida, los con mayor vida, ¿o queda a mí criterio?)

**Comment by Arcoirisky** [comment]
hola! :D 
Para casos como esos, que no se especifican en el enunciado, queda a tu criterio :D siempre y cuando no pase por sobre otro aspecto especificado.
