### ISSUE TITLE
Que pasa con los recursos que estaba recogiendo un trabajador muerto?

### ISSUE THREAD

**Issue by fpaez7** [IIC2233/syllabus#38]
![rush](https://user-images.githubusercontent.com/37160024/54933565-a300b080-4efb-11e9-9d41-b8952a9c7d7e.jpg)

_**Trabajador**. El trabajador es la unidad que se encarga de la recolección de recursos (...)    Dicha cantidad extraída sera añadida a los recursos de la civilización **al inicio del
siguiente turno**, y el trabajador quedara libre para ser asignado a otra actividad._ 

**Puedo asumir que si el trabajador muere en un ataque los recursos recogidos por el desaparecen?**

1) DCC envía a sus 2 trabajadores a extraer recursos / trabajador 1 (+30 madera) & trabajador 2 (+40 madera)
2) Cobreloa ataca a DCC/  El ataque no es lo suficientemente fuerte para ganar y solo trabajador 1 muere 
3) DCC obtiene +40 de madera (no los 70 que junto)

**Comment by Arcoirisky** [comment]
Puedes asumirlo! Al no estar especificado en el enunciado queda a tu criterio como lo manejas :D 

Saludos~
