### ISSUE TITLE
Cómo actualizar el tablero cuando se equivoca el jugador

### ISSUE THREAD

**Issue by Rafoxxa** [IIC2233/syllabus#38]
Cuando el jugador pierde, en el enunciado dice que se debe mostrar el tablero con los legos en sus posiciones, pero ¿qué pasa con en el resto de las baldosas (con las que no tienen lego)? estas son las opciones que se me ocurren pero no sé cual es: (si esta es la tabla: [['L' , ' ' ],[' ' , ' ']])
-que se vean blancas , ['L' , ' ' ],[' ' , ' ']]
-que se vean con números (de los legos aledaños), ['L' , ' 1 '],[' 1 ' , ' 1 ']]
-que se vean con números (de los legos aledaños) solo las que el jugador adivinó y las que no que se vean como blanco --> me parece que esta es, ya que en el buscaminas de mi compu hace eso pero de todas formas igual lo pregunto. (suponiendo que adivinó solo la de la primera fila: ['L' , '  1 ' ],[' ' , ' ']])

**Comment by DCCollao** [comment]
Hola! 
La forma en que lo decidas hacer queda a tu criterio, pero recuerda especificarla en tu `README.md`. Lo importante de esta parte es que se revelen las posiciones de los legos :tada:

**Comment by Rafoxxa** [comment]
Gracias!!
