### ISSUE TITLE
Supuesto archivo.txt

### ISSUE THREAD

**Issue by Fopazov** [IIC2233/Syllabus#38]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Mi duda es corta. ¿Asumimos que los archivos que recibe el programa están bien definidos? (la dimension del tablero es congruente con la cantidad de elementos)

**Comment by pedrozavalat** [comment]
Hola @Fopazov!,

Si!, Cuando cargas el archivo a tu programa en el menú de inicio, este se caracterizará por presentar la informacion de  un tablero **cuadrado de _n x n_**. Como podrás notar en el enunciado de la tarea, tal como se explica en la _sección de Archivos_, puedes ver que en el ejemplo
```
5,2,-,T,-,-,T,-,-,T,-,-,5,T,3,-,-,-,-,6,-,3,T,-,T,5
```
en un principio tienes el largo del tablero cuadrado (5), y luego los elementos que contiene (25 elementos, dado que el tablero es de 5 x 5). Por lo que, la cantidad de elementos es proporcional al largo del tablero. 

Cualquier duda responde este hilo,
Saludos :)

Pedro Z.

**Comment by antsalieri** [comment]
Hola @pedrozavalat

Tengo una duda sobre esa secuencia y sobre las otras que aparecen en la carpeta Archivos, si cuentas la cantidad de elementos de los archivos (nxn.txt) un dato demás.

5,2,-,T,-,-,T,-,-,T,-,-,5,T,3,-,-,-,-,6,-,3,T,-,T,5

En esa lista hay 26 elementos en ves de 25, esto tambien pasa para los otros archivos.

¿Tengo que omitir el ultimo dato?

Atento a su respuesta.

**Comment by pedrozavalat** [comment]
Hola @antsalieri !,

Cada archivo de un tablero se compone por un numero inicial (el cual representa el largo del tablero) y una secuencia
de elementos los cuales serian los elementos que contiene el tablero. 

Tal como mencione en el ejemplo anterior, se te entrega un archivo con los siguientes datos:
```
5,2,-,T,-,-,T,-,-,T,-,-,5,T,3,-,-,-,-,6,-,3,T,-,T,5
```
Puedes ver que el archivo tienes 26 elementos. Entonces, para entender mejor este ejemplo, lo puedes visualizar de la siguiente manera:
```
5,             --> "Largo del tablero (en este caso, tiene una dimension de 5x5)
2,-,T,-,-,
T,-,-,T,-,
-,5,T,3,-,     --> "Elementos que contiene el tablero "
-,-,-,6,-,           "T": representa una tortuga  
3,T,-,T,5            "-": representa una celda vacía
                     "Número": representa el valor que puede alcanzar una bomba
```           
Cada dato es importante, ya que el primero te sirve para reconocer la **dimensión del tablero,** y el resto de elementos 
te servirán para utilizar las operaciones del **Menu de Acciones**.

Estoy atento ante cualquier duda que tengas :)
Saludos !

Pedro Z.

**Comment by antsalieri** [comment]
Ahh vale, Muchas gracias
