### ISSUE TITLE
Parametros: posibilidad de poner strings "constantes"

### ISSUE THREAD

**Issue by CatalinaGoldsack** [IIC2233/syllabus#380]
Hola! Quería saber si es legal poner ciertos strings que se mantiene constantes a lo largo del programa en el archivo de parámetros.
Por ejemplo: el mensaje que se imprime cuando el usuario decide salir, los menús donde se le muestra al usuario sus opciones.
Me parece que entorpecen harto el código, se ve mucho más lindo y ordenado si los pongo en parámetros. :smiley:
Gracias! :simple_smile:

**Comment by CatalinaGoldsack** [comment]
¿Estos son los strings definidos? Si es así ya me respondí con la otra issue :blush:

**Comment by mpsubiabre** [comment]
Hola @CatalinaGoldsack!

Exactamente, no hay ningun problema :)

Éxito con la tarea!
