### ISSUE TITLE
Avance diagrama de clases

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2233/syllabus#380]
Holaa: 
Para el avance del diagrama de clases podemos dejar los métodos con `none` si aún no determino que retornara cada uno, o es necesario que todo este implementado para la entrega del diagrama en el avance.
Saludos :smile:

**Comment by baosse** [comment]
Holaa @Mamunoz42 !
Si puedes dejarlo con 'None' si no has determinado que retornará. 
Mucho éxito✨

**Comment by Mamunoz42** [comment]
Muchas gracias :)
