### ISSUE TITLE
Sprite Arbol 

### ISSUE THREAD

**Issue by muovalle** [IIC2233/syllabus#380]
Hola! no encuentro la imagen del árbol en ninguna carpeta.
gracias!

**Comment by gatochico** [comment]
Hola! Se encuentran en `sprites/otros/tree.png` .

**Comment by muovalle** [comment]
gracias!

**Comment by muovalle** [comment]
y cuando me dice que el árbol debe ir en una celda disponible se refiere a pasto o también puede estar en un espacio cultivado?

**Comment by gatochico** [comment]
Los árboles tienen probabilidad de aparecer solo en celdas del tipo espacio libre! (:
