### ISSUE TITLE
Consulta min y fenotipo inexistente

### ISSUE THREAD

**Issue by jerosalazar** [IIC2233/Syllabus#380]
En el caso de que para una característica haya un fenotipo que no se exprese en ninguna persona, por ejemplo en color de ojos si tengo 10 personas con ojos cafes, 2 con ojos azules y 0 con ojos verdes, ¿el valor del mínimo será el que no se presenta ninguna vez (verde) o es,
 el con menor frecuencia, necesariamente mayor a cero (azul)?

**Comment by Hernan4444** [comment]
@jerosalazar debes considerar el mínimo entre los que se expresan. En tu caso seríá azul.
Saludos ✌️
