### ISSUE TITLE
Tiempo de cada tecla

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#380]
Como puedo hacer para saber cuantas veces e va a contar que se presiono una tecla del teclado si es que la mantengo presionada por cierto tiempo? Por ejemplo si dejo presionada la tecla de por 1 segundo cuantas veces se cuenta que se apretó?  Gracias.

**Comment by gatochico** [comment]
Hola! 
Lo que podrías hacer es tener una variable en tu ventana que almacene las veces que se llama el keyPressEvent (por ejemplo, sea self.veces_teclado = 0 en el init), y hacer que esta aumente cada vez que se hace el llamado a keyPress (ya que, como te diste cuenta, mantener el boton presionado es interpretado como que el boton está siendo apretado muchas veces muy rápido). 

Ahora, probablemente quieres poder utilizar en algo el nº de veces que se captó la tecla y que luego esta variable veces_teclado también se reinicie cuando sueltes la tecla y hayas utilizado el valor recién obtenido, cierto? Aunque no te puedo dar la respuesta directa, te recomendaría el entonces hacer que tu _funcion/señal/lo que sea que quieres que utilize este valor_ esté asociada a un **KeyReleaseEvent**. Como su nombre lo dice, se activa al sentir que se suelta la tecla!

Como ultimo tip, te darás cuenta que el **KeyReleaseEvent** funciona al igual que un KeyPress cuando se sostiene la tecla, es decir, activandose múltiples veces seguidas. Si quieres que esto no ocurra, y que se active solo una vez cuando **realmente** se suelta la tecla, te recomendaría revisar el método [isAutoRepeat](https://www.riverbankcomputing.com/static/Docs/PyQt4/qkeyevent.html#isAutoRepeat) que tienen los QKeyEvent... 

Cualquier duda nos avisas!
