### ISSUE TITLE
currencyconverter en versión incorrecta

### ISSUE THREAD

**Issue by alvaritions** [IIC2233/syllabus#380]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Usé *python -m pip install currencyconverter* en cmd y la librería se me instaló en la versión de Python 3.8
que tengo instalada para otro curso. ¿Cómo hago para instalarla en 3.7?.
Gracias por su atención.

**Comment by tamyhan** [comment]
Holaa! A mi me pasó lo mismo y si usaste ese comando para instalarlo trata con:

python3.7 -m pip install currencycoverter

No se si funcionará porque yo usé otro comando pero hice un cambio parecido

**Comment by mistico0121** [comment]
Hola. Hay varios alumnos que han tenido este problema.

-Prueba cambiando el PATH de python de tu computador(es basicamente el que dice que version usar cuando escribes el comando "python" o "python3") para que utilice la version correcta. 
-Usa pip3 en vez de pip. A mi me ocurre que pip instala cosas en python 2.x, mientras que pip3 instala en python 3.x.

Tambien puedes especificarle a pip donde quieres que instale el package. Intenta con este comando.
```
pip install --user currencyconverter -t "C:\Program Files (x86)\Python 3.7\Lib\site-packages"
```
Encontré eso que creo que quizás debería funcionar. Cambia la ruta de python ahí por la tuya que quieres que se ejecute.

Hay otras issues al respecto que también te pueden ayudar #355  #357

Suerte
