### ISSUE TITLE
Uso de sum con estructura por comprensión

### ISSUE THREAD

**Issue by carlosmartellus** [IIC2233/Syllabus#380]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Se puede utilizar sum(1 for _ in generador) para saber la cantidad de ocurrencias dentro del generador?

**Comment by TomasGMDC** [comment]
@carlosmartellus sum es un método permitido, así que eso es correcto. Eso sí, ojo que el for solo se puede usar dentro de una estructura por comprensión, es decir, haría falta encerrar el for en un iterable para asegurarte (tipo []).

**Comment by carlosmartellus** [comment]
tendría que ser entonces por ejemplo [sum(f for _ in generador)]?

**Comment by TomasGMDC** [comment]
@carlosmartellus no no, tendrías que hacer sum( [ 1 for _ in generador ] ). Es decir, crear una lista por comprensión, y usarla dentro de sum.

**Comment by maidazuniga** [comment]
Hola, tengo una pregunta sobre lo mismo. Si uso sum() si o si debo crear una lista por comprensión, o puedo usarlo junto con otra función como filter o reduce? Mi duda va en si estoy usando correctamente sum() en la función cantidad_voto_candidatos, ya le hice push a mi tarea para que puedan verlo

**Comment by TomasGMDC** [comment]
@maidazuniga revisé lo que subiste, y no hay problema. Solo ten ojo de usar el for dentro de una estructura de datos generada por comprensión (ej. sum( [ 1 for x in filter( ... ) ] ) ), para evitar cualquier tipo de problema con la revisión.

**Comment by Bonjour1X** [comment]
Una duda respecto a la suma, si yo sumó con reduce en este caso reduce(lambda x, y: x + y, (cosa_comprimida1, cosa_comprimida2)), eso esta bien? en un caso pensaba hacerlo porque no sabia si usar sum o +

**Comment by TomasGMDC** [comment]
@Bonjour1X usar el símbolo de suma en vez de sum también se puede. Ahora, para estar 100% seguro, no te olvides de utilizar el script de revisión del disclaimer para que no hayan problemas en la corrección.

**Comment by Bonjour1X** [comment]
Segun el test sale todo bn, pero como habia separado un generador en 2 y luego las volvi a sumar por comprension de listas, no sabia si sirve, pienso que igual que sí

**Comment by TomasGMDC** [comment]
@Bonjour1X si el script indica que todo está bien, lo puedes hacer, dado que con ese script se llevará a cabo la revisión del cumplimiento del disclaimer.
