### ISSUE TITLE
Problemas de vision en parentesco

### ISSUE THREAD

**Issue by fedetaladriz** [IIC2233/Syllabus#381]
Hola!
La condición de algunos parentescos es que tengan "el mismo problema de visión". Esto se refiere a que compartan alguno de los dos problemas posibles o que tengan **exactamente** el(los) mismo(s) problema(s)?
Gracias!

**Comment by TomasSalvadores** [comment]
Es que tengan el(los) mismo(s), si es que tienen, o que ambos no tengan.
Salu2!
