### ISSUE TITLE
Mención de métodos abstractos heredados de la clase padre en el diagrama.

### ISSUE THREAD

**Issue by Nicolasramos411** [IIC2233/syllabus#381]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Según lo explicado en [semana-03/1-diagrama-de-clases.ipynb]  los métodos heredados desde la superclase no se repiten en la representación de las subclases ya que, al tratarse de una relación de herencia, esta repetición o traspaso de atributos está implícita, pero en el caso de un método abstracto, al realizar uno un *overriding* sobre el método cada vez que se herede no sé explicita si debiese ser mencionado en el diagrama.

Aprovechando la pregunta, quisiera saber si esto se generaliza para cualquier método (abstracto o no) que se sobreescribe en una clase hija. 

Gracias!

**Comment by aaossa** [comment]
Hola @Nicolasramos411 , perdón lo tarde, esta *issue* quedó medio perdida porque era semi relacionada con la tarea y se pasó 😅 (Gracias de todas formas al botcito ✨). Intentaré responder tu pregunta en dos casos separados:

1. **Métodos abstractos**: Cuando haces un método abstracto, automáticamente las subclases deben hacer *overriding*, por lo que no es necesario explicitar en las subclases que se implementa el método. En este caso, basta con que en tu diagrama hagas visible que un método es abstracto, por ejemplo con un `+` y/o con cursiva, algo como *`+metodo_abstracto`*. En el curso no les imponemos un estándar al respecto, por lo que podrías marcarlo como más te haga sentido (y ojalá explicar tu notación en el diagrama entregado)
2. **Al hacer *overriding***: Ahora, cuando haces *overriding* de un método no abstracto, sí es necesario explicitar en la subclase que esta implementa dicho método. Si en la subclase no colocas el nombre de un método de la superclase, se puede interpretar como que no lo sobreescribe. Si en la subclase colocas el nombre de un método de la superclase, es porque aplicaste *overriding*.

Los dos casos son distintos, pero relacionados, así que intenté explicarlos por separado 😅 Lamento la tardía respuesta, pero espero que sea de utilidad 🙌
