### ISSUE TITLE
¿Cuándo un nombre de usuario es alfanumérico?

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#381]
Hola. Cuando mencionan que el usuario debe ingresar un nombre de usuario que contenga caracteres alfanuméricos, esto se refiere a que el nombre debe tener al menos un número y al menos una letra? o simplemente puede ser un nombre que pueda tener solo números o solo letras? 

Tengo una duda también en el mismo menú de inicio, pero cuando se selecciona la parte de "salir", cuando se sale del programa, que se debe implementar ahí? . Se puede indicar simplemente que debe volver a ejecutar el programa para que se vuelva a mostrar el menú de inicio¿?

**Comment by moquezada** [comment]
Hola @Camila-sty,

Un string alfanumérico puede contener letras y/o números. No es necesario que estén presentes tanto dígitos como letras. Unos cuantos ejemplos: `pikachu2000` es alfanumérico y `hapapa` también lo es :)

Respecto a tu segunda pregunta, la opción de **salir** es precisamente para salir del programa, por ende debe dejar de ejecutarse. Esta acción es totalmente distinta e independiente de **volver atrás**, opción presente en el resto de menús 😃 

Por último, te pido por favor que si vas a realizar más de una pregunta lo hagas en distintas issues, sobre todo si ninguna de ellas tienen relación entre sí ☺️.

Espero haberte ayudado con tus dudas 🐳 Éxito en tu tarea!

**Comment by Camila-sty** [comment]
Ok, gracias :smile:

**Comment by tedroppelmann** [comment]
Una palabra con tilde es alfanumérica?

**Comment by fdoflorenzano** [comment]
> Una palabra con tilde es alfanumérica?

Sí. Saludos.
