### ISSUE TITLE
Dias competencia

### ISSUE THREAD

**Issue by barbarafcp** [IIC2233/syllabus#381]
En el enunciado dice que dia empieza en el dia 0 y en los parámetros son 6 días de competencia. Significa que el dia 0, 2, 4 y 6 son de entrenamiento y los días 1, 3 y 5 son de competencia? Lo del dia 0 me genera confusión porque en el enunciado dice que los días de entrenamiento y competencia van de duplas y que los días siempre serán pares, pero con el dia 0, quedan disparejos

**Comment by hsazos** [comment]
¡Hola @barbarafcp!

Como dices, parte en el día 0 y son 6 días, por lo que las tuplas serían (0,1),(2,3),(4,5). El día 6 no estaría incluido.

¡Animo con la tarea!🦕
