### ISSUE TITLE
Tiempo movimiento fantasma significado visual

### ISSUE THREAD

**Issue by GuilleStanke** [IIC2233/Syllabus#381]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

el enunciado dice: "Donde ponderador_velocidad_fantasmas es un número decimal aleatorio entre MIN_VELOCIDAD y MAX_VELOCIDAD, y tiempo_movimiento_fantasmas es la cantidad de segundos que deben transcurrir entre un movimiento y otro."

cuando dicen "segundos que deben transcurrir entre un movimiento y otro", se refieren a los segundos que pasan entre que un fantasma está en una casilla y pasa a estar en la siguiente? O que el fantasma se va a mover con una velocidad arbitraria hasta detenerse (por tiempo arbitrario) y volverá a moverse luego de TIEMPO_MOVIMIENTO_FANTASMAS??

**Comment by Panconquesocl** [comment]
Holaa!! 😁 , se refiere a cada cuantos segundos el fantasma se mueve de una casilla a otra.
