### ISSUE TITLE
Sobre casas y tiendas

### ISSUE THREAD

**Issue by EstebanReyes1998** [IIC2233/syllabus#381]
Buenas tardes,

¿Podemos asumir que siempre habrá exactamente una casa y una tienda por mapa?
Muchas gracias.

**Comment by jeschuwirth** [comment]
Hola @EstebanReyes1998,

Si pueden asumir que será exactamente una casa y una tienda :)

De todos modos te recomiendo colocarlo en los supuestos de tu readme junto con una cita a esta issue para evitarte problemas.

Suerte!
