### ISSUE TITLE
¿Cómo borrar/terminar un QThread?

### ISSUE THREAD

**Issue by IngisRedd** [IIC2233/syllabus#381]
Hola!

Ocurre que es necesario en mi programa ir eliminando los threads de monedas, enemigos, y torres a medida que estos desaparecen en el juego. En los ejemplos y documentación me recomiendan utilizar la función quit() para ello. Pero he hecho varias pruebas y esta función no pareciera hacer nada en absoluto:
![image](https://user-images.githubusercontent.com/39068534/58357390-9b508000-7e48-11e9-9126-9102d4a83d14.png)

La función terminate(), en cambio, funciona mejor:
![image](https://user-images.githubusercontent.com/39068534/58357498-0c903300-7e49-11e9-9d42-61e712be2cfd.png)
Pero al parecer el uso de esa función no es muy recomendado. 

Además, en ambas pruebas el programa no termina por alguna razón que desconozco, pues en teoría ya finalizó de correr el thread y no queda más código que procesar. Agredecería me comentaran la manera correcta de terminar un thread, pues de otra manera me veré obligado a que mi juego acumule cientos de threads "muertos", que no cumplen ninguna utilidad e incluso continuan enviando señales que generan errores e impiden el funcionaminento del programa

Gracias por adelantado!  \(^_^)/

**Comment by IngisRedd** [comment]
PD: Mis threads son todos daemons, por si tuviera algo que ver.

**Comment by VicenteMerino** [comment]
Hola, yo también quiero saber esto

**Comment by VicenteMerino** [comment]
No estoy seguro, pero creo que haciendo self.deleteLater() podría servir

**Comment by jeschuwirth** [comment]
Saludos!

La razón por la que exterminate no es muy recomendada es porque un thread debería tener clara su función y saber cuando terminar, una vez que se ejecuta por completo el método `run()` el thread se borra automaticamente. Por lo general `run()`  tiene un `while condición` el cual lo mantiene vivo hasta que deje de ocurrir la condición o hasta que se ejecute el método `.terminate()`.

En este caso se tienen claras las condiciones de término de los thread enemigo, personaje o torre. Enemigo cuando este muere, torre cuando esta muere o termina el juego y personaje cuando termina el juego. Por esta razón te recomiendo que en enemigos y torres tu `while True` sea `while self.hp > 0`, de este modo si su vida llega a 0 su método `run()` termina y el thread se borra sin problemas.

Espero que les sirva, si tienen más dudas o no les quedó muy claro comenten en la issue con sus preguntas :)

Suerte en la Tarea!

**Comment by IngisRedd** [comment]
Entiendo. Y para que rayos sirve entonces self.quit()? Debería usarlo en algún minuto?

**Comment by jeschuwirth** [comment]
En general te recomendaría no usar quit() que hacer que los thread terminen, sino qué se estos acaben solos su función.
 Te recomiendo revisar en los syllabus de semestres anteriores las ayudantias y actividades de thread y ahí ver cómo los finalizan
