### ISSUE TITLE
[ACB] duda obtener_pokemon()

### ISSUE THREAD

**Issue by SCarcG1** [IIC2233/Syllabus#381]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, tengo una duda con el formato de obtener_pokemones, porque estoy tratando de verificar que este bueno lo que se obtiene utilizando enviar_test, pero me manda error de que respuestas no coinciden.
Siguiendo lo que dice el enunciado, ¿debo enviar una lista de diccionarios de cada pokemon? y ¿"nombre_stat" de "stats" tengo que reemplazar "nombre_stat" con el nombre obtenido cierto?.

PD: Perdon, recien cache que subi la issue dos veces, ya cerre una

**Comment by igbasly** [comment]
Hola hola @SCarcG1  ✌️ 

En cuanto a la primera pregunta, sí, debes retornar una lista de diccionarios, donde cada uno corresponde a un Pokémon.
Respecto a las otras preguntas, no entiendo muy bien a que te refieres, puedes explicarme un poco más??

Quedo atento :v:

**Comment by jicartagena** [comment]
Tengo la misma segunda pregunta, cuando se pide que contenga los datos 'stats' de la api, el enunciado dice que se cree un nuevo diccionario con la llave 'nombre_stat' ¿con eso se refiere al nombre de la stat guardad en 'name' o la llave debe ser llamada asi guardar el resto de informacion?

**Comment by igbasly** [comment]
Hola @jicartagena ✌️ 
Efectivamente, se refiere a que la llave sea el nombre de la *stat* guardado en el atributo `"name"` de su diccionario.

Se entiende??

**Comment by jicartagena** [comment]
@igbasly si! muchas gracias
