### ISSUE TITLE
Levantamiento y captura de errores/excepciones

### ISSUE THREAD

**Issue by akrebs2** [IIC2233/Syllabus#381]
Hola.
A pesar de haber leído un par de issues, no tengo claro cómo es el manejo de excepciones para esta tarea. Debemos hacer raise de nuestras excepciones (BadQuery, WrongInput, MovieError) en la librería, y capturarlas en el main? En la issue #362 se dice que no debemos hacer try-except, pero si no lo hacemos se nos caería el program cada vez que, por ejemplo, se encuentre un N/A en la base de datos.

**Comment by Hernan4444** [comment]
@akrebs2 en esa issue se dice que no hagas `try/except` de cualquier **otro error** que ocurra en tu librería `(ValueError, IndexError, etc)`. Pero en el enunciado especificamos que **si puedes** hacer  `try/except`  dentro de tu librería para capturar **solo** las 3 excepciones que generas  (BadQuery, WrongInput, MovieError).

Espero que ahí si quedara más claro 👍 
Saludos ✌️

**Comment by norman123123** [comment]
En caso de que haya un dato N/A, se debe descartar y procesar la consulta con los siguientes? o solo se levanta la excepcion, se indica que cosa fue lo que falló y nada más?

**Comment by norman123123** [comment]
A lo que me refiero es:
quiero sacar el promedio entre 5 ratings, pero hay 2 en los que no hay datos (sale 'N/A').
en ese caso calculo el promedio entre los 3 que si tienen o tiro una excepción de que no se puede?
Si es asi, tiene que ser una excepcion por cada dato incompleto? o basta una con el primer dato incompleto encontrado?

**Comment by Clemente24** [comment]
@norman123123 Supiste cual es la respuesta a esto? Estoy con la misma duda!

**Comment by Hernan4444** [comment]
Evitemos los "Comento para saber", suscribanse a las notificaciones de una issue si les interesa. Si les interesa el repo hagan watch (arriba a la derecha):

![image](https://cloud.githubusercontent.com/assets/10425834/14770701/2608a1c2-0a4e-11e6-8378-c58953883176.png)

Tanto en Facebook como aquí, en Github, existen sistemas para evitar las respuestas que no aportan a la discusión y que son solo para marcar seguimiento. Los invitamos a usar Github correctamente :grin:  

Sobre la respuesta, tal como se explicó en la ayudantía ( y la repito aquí para quien no fue), si la consulta falla, por culpa de una subconsulta (consulta anidada), ustedes tienen que indicar la falla de la subconsulta, es decir, indicar el error que se generó en esa subconsulta, junto con los parametros solicitados según el error.

Si están analizando un generador y hay un dato malo, se acabó la consulta. No les vamos a pedir que intenten pasar de largo ese dato o solucionarlo para poder continuar. Si hay excepción, no se sigue. Se indica el error y se pasa a la siguiente consulta.

Saludos ✌️

**Comment by mblejeune** [comment]
@Hernan4444 en ese caso para poder ver que efectivamente funcione por ejemplo filter_by_date que parará al encontrar un dato con N/A, para poder revisarlo usaran una base de datos sin N/A?

**Comment by Hernan4444** [comment]
@mblejeune si probaremos con otra base de datos. Se debe capturar porque estabamos evaluando el uso de excepciones en caso de que salga un N/A, no buscamos que el programa se caiga, sino que avise según el formato indicado en el enunciado y luego siga respondiendo las demás consultas mandadas.
