### ISSUE TITLE
T01 , inteligencia del cpu

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#382]
hola! tengo entendido que como acción mínima el cpu solo tiene que enviar atletas a competir, puedo asignar esto a un valor random? aun que el atleta que envíe este lesionado, o tengo que cumplir otros requerimientos mínimos, como que sea el mas capaz o que genere mayor puntaje y no este lesionado.
saludos y feliz lunes

**Comment by vicentevegaulloa** [comment]
Hola @sa-Appel !

Espero que estés muy bien 😄. Basta con que hagas un `random.choice()` para elegir el jugador rival. El enunciado solo dice que debe elegirse uno random, eres libre de agregarle cualquier acción extra (recuerda mencionarlo en el README). EL enunciado no dice que tengas que preocuparte de si está lesionado o cualquier otro requerimiento del deportista, recuerda que el método `validez_de_competencia` maneja el caso en que una delegación no cumpla con los requerimientos mínimos.
