### ISSUE TITLE
Comprar Torres

### ISSUE THREAD

**Issue by bvallejo1** [IIC2233/syllabus#382]
Hola, estaba investigando sobre como poder arrastrar el label de la torre y posicionarla en algún lugar válido del mapa, para esto estaba pensando en hacer override de mousePressEvent, mouseReleasedEvent y mouseMoveEvent, pero no se si esto debo hacerlo en la clase QWidget donde mantengo mi juego y los otros widgets externos (como las imágenes de torres para ser compradas), o hacerlo en una clase por ejemplo Torre que herede de QLabel.
Cual de las dos sería la forma mas correcta?

**Comment by Arcoirisky** [comment]
Hola~ 
Me temo que eso es algo que deberías ver por ti mismo :( pero ten en cuenta lo que quieres hacer y si corresponde a interfaz o más al procesamiento. O si quieres que cada una de tus clases tenga esta funcionalidad integrada, quizás hasta repitiendo código.

Quizás, pensártelo un poco y seguir lo que te parezca mejor según los conocimientos que han adquirido del curso :D
