### ISSUE TITLE
defaultdict() de collections

### ISSUE THREAD

**Issue by Chiseth** [IIC2233/Syllabus#382]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
Estuve viendo en la issue de cosas permitidas que se podia importar collections por lo que hice from collections import defaultdict
y cree un diccionario así para contar especies conteo_especies = defaultdict(int), es legal? :<

**Comment by TomasGMDC** [comment]
@Chiseth hasta donde yo sé, defaultdict() funciona, al igual que {}, para crear un diccionario, por lo que debe seguir las reglas de estructuras de datos expuestas en " #339 ". Ahora bien, para que te asegures, te recomiendo usar el script de revisión que se subió recientemente.

**Comment by Chiseth** [comment]
Utilizando el script me sale que no estoy utilizando nada prohibido en mi función, y paso todos los test, pero aún as´´i me da miedo que me coloquen un 1 por lo que me acabas decir : c

![image](https://github.com/IIC2233/Syllabus/assets/156480987/7768daca-cbfa-478e-ba0d-a110799126af)

**Comment by TomasGMDC** [comment]
@Chiseth en esa línea estás creando una estructura de datos dentro de un reduce(), lo que está permitido, así que todo bien con eso.
