### ISSUE TITLE
Sobre barcos encallados y eventos

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#382]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

**Comment by Emiliax16** [comment]
@fernandosmither , me parece más correcto no asumir lo que dices. **El evento especial no se aplica mientras el banco esté encallado**. Te podrías preguntar cuál es la diferencia entre un barco encallado y los de atrás que se encuentran detenidos. Si bien ninguno se mueve, sólo necesitas desencallar el barco de adelante para que los demás puedan continuar avanzando. Por esto,  **barco detenido** si puede sufrir un evento especial.

Avísame si se entendió!

**Comment by fernandosmither** [comment]
> @fernandosmither , me parece más correcto no asumir lo que dices. **El evento especial no se aplica mientras el banco esté encallado**. Te podrías preguntar cuál es la diferencia entre un barco encallado y los de atrás que se encuentran detenidos. Si bien ninguno se mueve, sólo necesitas desencallar el barco de adelante para que los demás puedan continuar avanzando. Por esto, **barco detenido** si puede sufrir un evento especial.
> 
> Avísame si se entendió!

**A modificar el código se ha dicho!** Jajaja, como siempre, muchas gracias Emilia!

**Comment by Emiliax16** [comment]
Ánimooo!! ❤️
