### ISSUE TITLE
[AC Bonus] Duda en las funciones de generar estadisticas 

### ISSUE THREAD

**Issue by svilaza** [IIC2233/Syllabus#382]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, tengo una duda general respecto a todas las funciones de la parte 3. Que pasa si hay pokemones con valores repetidos en alguno de los casos? por ejemplo que dos tengan la misma altura o velocidad. Como manejamos esos casos? Lo mismo en el caso de los mejores atacantes si varios tiene el mismo valor de atk/def cuales deberíamos retornar y cuales no? (asumiendo que estos queden dentro del top 5)

**Comment by igbasly** [comment]
Hoola @svilaza :v:

Respecto a la primera pregunta, da lo mismo si dos Pokémon tiene atributos repetidos, no afectará en nada al programa, así que debes mantenerlos como cualquier otro Pokémon.
Respecto a lo segundo, en el caso de la función `obtener_mejores_atacantes`, si resulta en que dos Pokémon tienen el mismo potencial de ataque, entonces debes ordenarlos por orden de aparición.

¿Se entiende? Si no quedo atento a otras consultas 😉

**Comment by svilaza** [comment]
@igbasly mmm me queda mas claro pero me pasó en el caso de la velocidad tenia 3 pokemon con igual valor y mi funcion retornaba el primero con esa velocidad y al probar el test me tiraba error pero luego si consdieraba el ultimo encontrado con ahi si funcionaba, asumo que eso es valido para el resto de funciones?

**Comment by igbasly** [comment]
@svilaza Sii, eso aplica a las demás funciones y se explica por como funcionan las funciones de ordenado. Pero probablemente para los test que evaluarán la AC consideraremos esos casos como cualquier de ellos bueno 👌 (solo a las funciones "mas rápido" y "más alto")
