### ISSUE TITLE
Crear archivo .csv auxiliar

### ISSUE THREAD

**Issue by rldelafuente** [IIC2233/syllabus#382]
Hola! 

¿Se puede crear un archivo .csv auxiliar, para ir guardando las acciones diarias del usuario ingresado? Este sería reseteado cada vez que el usuario pasa de día.

Esto con fin de ir guardando las acciones diarias de forma externa.

Saludos,
Rocío

**Comment by jeschuwirth** [comment]
Hola @rldelafuente,

No debería ser necesario guardar las acciones diarias que ha hecho el usuario, me puedes dar un ejemplo de para que lo quieres usar?

**Comment by rldelafuente** [comment]
Para cuando se pase al siguiente día, se indiquen las acciones diarias de ese día.

**Comment by fdoflorenzano** [comment]
Hola @rldelafuente,
Como dice @jeschuwirth, no debería ser necesario usar un archivo externo, pero si deseas solucionarlo de esa forma, es válido. 
¡Éxito!
