### ISSUE TITLE
Duda sobre rubrica: "Se actualiza correctamente el archivo puntaje.txt"

### ISSUE THREAD

**Issue by juanivegam** [IIC2233/Syllabus#382]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda respecto al puntjo del enunciado que dice "Se actualiza correctamente el archivo puntaje.txt". Tengo entenido que no hay ningun archivo así dentro de lo estipulado. ¿A qué se refiere?

**Comment by ignacio-sp** [comment]
Hola @juanivegam, se refiere a lo mencionado en el apartado `3.3 Puntaje` del enunciado:

![image](https://github.com/IIC2233/Syllabus/assets/80914872/9bc6ea0e-ef99-40a2-9c14-29f037eb4d93)

Saludos!
