### ISSUE TITLE
Errores Not Found y Not Acceptable

### ISSUE THREAD

**Issue by ewaugh2** [IIC2233/Syllabus#382]
En el enunciado dice que el error "Not Found" es para cuando se ingresan parámetros incorrectos y que "Not Acceptable" es para cuando no hay resultado.

Tiene Mucho mas sentido que sean al revéz. Las puedo cambiar y lo especifíco en el README?

Saludos

**Comment by Hernan4444** [comment]
@ewaugh2 puedes hacerlo siempre y cuando no olvides especificarlo 👍 
Saludos ✌️
