### ISSUE TITLE
Limite de lineas

### ISSUE THREAD

**Issue by Baelfire18** [IIC2233/syllabus#383]
Una pregunta, esta tarea no tiene limite de lineas cierto? Porque en el enunciado no especifica

**Comment by jmwielandt** [comment]
Hola!

Tal como indica la [sección de descuentos](https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md#modularizaci%C3%B3n-5-d%C3%A9cimas-package), se descontarán 5 décimas si tienes uno o más archivos con más de 400 líneas. En la entrega anterior avisamos en el enunciado que el límite variaba por si había gente que no estaba tan atenta, eso es todo.

Saludos y ánimo con la tarea!
