### ISSUE TITLE
Duda retorno distritos_mas_votos_especie_bisiestos()

### ISSUE THREAD

**Issue by jisalasc** [IIC2233/Syllabus#383]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado, nos dicen que se debe retornar un f-string en especifico, donde nos piden {nombre_distrito}, pero cuando llegue a los test case me di cuenta que para que calze en vez de nombre debe ir la id del distrito ya que con nombre queda malo, hay que hacerle caso a lo que piden los test_case o enunciado?

**Comment by TomasGMDC** [comment]
@jisalasc hablé de lo que mencionaste con el resto del equipo docente, y se cambiará el enunciado para que calce con lo que se llevó a cabo en los test cases. Así que concéntrate en lograr cumplir los test cases.
