### ISSUE TITLE
menú aprueba de error

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#383]
Hola.
Cuando un usuario ingresa una opción invalida, tengo que avisarle de su error, pero además qué es lo que debería hacer el código en este caso?. Simplemente deja de ejecutarse o debo ofrecerle intentar de nuevo la acción?

**Comment by jeschuwirth** [comment]
Hola @Camila-sty,

La idea de esa excepción es que un buen código no debe cerrarse levantando un error, siempre se debe cerrar por un exit() o el usuario clickeando la x. 

Si el usuario ingresa una opción inválida el programa no puede dejar de ejecutarse, sino que debe "darse cuenta" del error y volver al menú anterior o pedirla al usuario un nuevo input

Éxito!
