### ISSUE TITLE
Duda con retorno del filter

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#383]
Hola:
En la función filtrado retorno directamente filter(f, iterable) y al pasarlo como argumento a una función como promedio me tira el siguiente error:
TypeError: reduce() of empty sequence with no initial value
Lo he googleado y he hecho hartos prints para ver que pasa (realmente le entrego como argumento el retorno de filtrar) y no he llegado a ninguna respuesta, por lo que yo entiendo el filter retorna un generador, entonces no entiendo porqué una función como prom.
Espero puedan resolver mi problema.
Saludos :B

**Comment by Dunkan1** [comment]
a lo mejor filtra demasiado bien
lista = [ -1,-1,-2,-9]
a = filter(lambda x: x> 0, lista) = [ ]
PROM(a) -> esta vacio asi que no saca el promedio
reduce(lambda x , y:  x + y,  a)
TypeError: reduce() of empty sequence with no initial value

**Comment by acrojas2** [comment]
@Dunkan1 gracias! creo que justamente era eso :)
