### ISSUE TITLE
Rol de los menús en el diagrama de clases.

### ISSUE THREAD

**Issue by Nicolasramos411** [IIC2233/syllabus#383]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Hola, si definimos una clase menú con sus respectivos métodos deberíamos incluirlo en el diagrama de clases o lo consideramos como una especie de "interfaz",

Gracias!

**Comment by tqmbanados** [comment]
Hola! Todas las clases de tu programa deberían ser parte del diagrama de clases. Ahora bien, de aquí en adelante no evaluaremos diagrama, por lo que si continúas trabajando con diagramas de clases, deberías focalizarte en que a ti te ayude lo más posible. Si crees que esta clase ```menu``` es separada del resto (especialmente si no tiene muchas relaciones de agregación o composición), eres libre de agregarla o no. Ahora si es que trabajas en un equipo más grande mejor que lo converses con las personas con quien trabajas!
