### ISSUE TITLE
Combinaciones de tecla

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#383]
Hola en las combinaciones de tecla E+ N + D se puede asumir que será en ese orden o debo  ver todos los caso ( i.e.  N &rarr; E &rarr; D).

**Comment by gatochico** [comment]
Hola! Puedes asumir que las combinaciones de los cheat codes siempre serán en el orden definido en el enunciado, y que deben introducirse ininterrumpidamente para ser válidos. Saludos!
