### ISSUE TITLE
T2: Pregunta sobre 5.1 menu de inicio

### ISSUE THREAD

**Issue by JiajunOuO** [IIC2233/Syllabus#383]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]
Hola, tengo duda sobre un descripcion de 5.1 menu de inicio, que dice: **"El Día actual indica el número de oleada que va a acontecer al seleccionar la opción Pasar Día, que es un int entre 0 y DURACION."**, mi pregunta es, **los dias actuales afecta a la oleada de zombies?, si es asi como lo afectaria?** y **como duracion esta en azul y mayuscula, tengo que definir DURACION en mi parametro?, si es asi para que sirve este parametro?**

**Comment by augustayanez** [comment]
No, los días actuales no afectan a las oleadas de zombies. Cuando se dice que "*el día actual indica el número de oleada que va a acontecer al seleccionar la opción Pasar Día*", se quiere hacer referencia a la cantidad de días pasados en tu juego, cantidad de veces que ya se ha seleccionado la opción *Pasar Día* o cantidad de días simulados (lo puedes ver de cualquiera de estas formas). Respecto a DURACION, efectivamente al estar en ese formato en el enunciado es un parámetro, y simboliza la cantidad de días que se simularán en el juego (recuerda que el objetivo del juego es producir la mayor cantidad de soles posibles durante los DURACION días).

**Comment by JiajunOuO** [comment]
Ya entendi!! Muchas gracias por explicar.
