### ISSUE TITLE
Importar desde otros directorios a main no funciona

### ISSUE THREAD

**Issue by golosinas** [IIC2233/Syllabus#383]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Estoy tratando de importar desde los módulos ```ventana_inicio.py``` y ```ventana_juego.py```, desde mi carpeta ```frontend```, y ```logica.py``` desde la carpeta ```backend```, todo hacia mi archivo ```main.py```. 

Sigo el mismo formato que se utilizó en las experiencia 3, pero no me resulta. Me sale que no existe el módulo. He intentado crear un archivo __init__.py dentro de las carpetas, pero tampoco funciona. Sé que podría agregar la carpeta al sys.path manualmente, pero no sé si se considera buena práctica. ¿Hay otra manera de resolver esto? ¿Tendré que agregarlo manualmente?

Muchas gracias.
Saludos. 🙂

**Comment by lsilvabw** [comment]
Buenas, te recomiendo leer esta issue donde se aborda un caso similar. Quedo atento si quedas con dudas.
#295
Saludos!
