### ISSUE TITLE
Palabras dentro de otras (bots y comentarios)

### ISSUE THREAD

**Issue by Pipelao** [IIC2233/Syllabus#383]
Hola, espero que se encuentren bien
Sé que se ha insistido harto en esto ya que se habló en la issue #325, pero me causa duda que pueden haber palabras compuestas con las palabras que nos dan en vocabulary.txt, y un ejemplo es el que mencionaban precisamente en #325 donde hay que contar "enjoyable" si tenemos "enjoy" en vocabulary.txt, pero qué pasa con "I"? porque por ejemplo se contaría "If" en caso de ver que se contenga y si es así no me hace sentido por eso pregunto. En caso que no fuera así y sólo hay que ver ciertas palabras que se contengan dentro de otras, cómo lo hago?
Gracias de ante mano

**Comment by auirarrazaval** [comment]
Hola!
Perdon pero no me quedo muy claro, al momento de clasificar las palabras entre bueno y malo, cuando tengo la palabra "meaning" que contiene "mean", es clasificada como negativa, eso deberia ocurrir?

**Comment by rihanuch** [comment]
¡Hola @auirarrazaval !

Sí, eso debería ocurrir 👍

¡Saludos y éxito! ☘️

**Comment by sjkinast** [comment]
De hecho agregando a lo anterior tengo la misma opinion en relacion a lo de los bots  ya que "archivo llamado vocabulary.txt donde cada línea es una palabra del vocabulario del bot" se entiende claro que si  yo tengo una palabra x y esa palabra x no es equivalente a ninguna del archivo entonces esta no esta en el archivo.

**Comment by rihanuch** [comment]
¡Hola @sjkinast ! 

Sí, es obligación

Respecto a lo segundo, te recuerdo que al comienzo del semestre se dijo en la issue #3 🔙

> Este es un medio oficial de comunicación 

Esto significa que lo que respondamos los ayudantes será la manera en que se corregirá la tarea (respecto a esa duda). Las issues están para _**aclarar**_ este tipo de dudas, por lo que ya se aclaró y se dijo como se debe procesar el archivo

¡Saludos y éxito! 🍀

**Comment by savelozo** [comment]
En el caso, por ejemplo, de do y dog, debería incluir dog como una posible palabra generada por un bot? Porque claro, enjoyable comparte la raíz de enjoy, pero no es el caso mencionado anteriormente. 

Quedo atento :)

**Comment by rihanuch** [comment]
¡Hola @savelozo ! 🖖🏼

Si, incluyelos 

¡Saludos y éxito! 🍀

**Comment by savelozo** [comment]
¿Qué pasa en el caso de las palabras que solo comparten cierta parte de la raíz? Por ejemplo, en words.csv aparece "loving" y en algunos de los comentarios aparece "love". Como love no es un substring de loving mi código no lo está tomando como positivo y simplemente lo suma a neutral; eso estaría bien?

**Comment by rihanuch** [comment]
Recuerden que es importante tener en mente que el propósito de esta tarea no es poder detectar el léxico ❌🔠, si no que la palabra de ```vocabulary.txt``` esté (o no esté) de alguna manera contenida en los comentarios, entonces no se cuenta, pero si está contenida de alguna manera si se toma en cuenta

Esto es decir, asumamos que en ```vocabulary.txt``` tenemos ( 🐶):

- ```"I"```
- ```"dog"```
- ```"me"```


Y los comentarios son:

- ```"MI perro me atacó"``` -> aquí se toma en cuenta ```"I"``` y ```"me"```, sin importar el sentido que tengan dentro de la oración
- ```"La Amelia es una dog lover"``` --> aquí se toma en cuenta ```"me"``` y ```"dog"```, y **NO** se toma en cuenta "I" porque ```"I" != "i" ```

Ojalá con esto haya quedado más claro para todos 🌈, ¡saludos y éxito a todos! 🍀

**Comment by rihanuch** [comment]
@PhilippePotin , no, no deben ser consideradas

Saludos ✌️

**Comment by naquiroz** [comment]
@rihanuch Entonces lo que dijiste [aqui](https://github.com/IIC2233/Syllabus/issues/383#issuecomment-385600439) tambien se aplica para calculo de comentarios positivos y negativos? Porque en el issue #368 un ayudante dice lo contrario.

**Comment by rihanuch** [comment]
@naquiroz , me refería a los bots, que para ellos si es diferente tal como se dice en la issue #368

**Comment by joaquineichholz** [comment]
ode se considera positivo dado que la palabra modest es positiva? o solo se considera cuando la palabra que estamos comparando es un substring que se encuentra al comienzo de la palabra como "i con impatient" o "war con warmhearted"
