### ISSUE TITLE
Clases Abstractas en Diagrama de Flujo

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2233/syllabus#383]
Hola!
Cual es la manera de indicar que una clase es abstracta en un diagrama de flujo? Cómo se indican cuales métodos son abstractos? Y al mostrar relaciones como agregación de clases que heredan de una abstracta, se debe conectar con las heredadas o con la clase madre abstracta?
Muchas gracias!

**Comment by vicentevegaulloa** [comment]
Hola @Sofia-Arratia !

Estuve investigando y una clase abstarcta y sus metodos abstractos se escriben de _esta forma_. En cuanto a las relaciones de agregación con las que interactúa, esto depende de si la interacción es con todas las subclases (en ese caso haz la conexión directamente con la clase abstracta) o solo con algunas subclases (en ese caso haz la conexión directo a las sublclases).

**Comment by Sofia-Arratia** [comment]
Muchas gracias! 
Donde sale _esta forma_ debería haber un link? o se refiere a un texto en italica?
Nuevamente muchas gracias!

**Comment by vicentevegaulloa** [comment]
Significa que está en italica 😄

**Comment by Sofia-Arratia** [comment]
Perfecto! Muchas gracias c:

**Comment by vicentevegaulloa** [comment]
De nada!
