### ISSUE TITLE
[ACB] problema obtener_mejores_atacantes()

### ISSUE THREAD

**Issue by SCarcG1** [IIC2233/Syllabus#383]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, tengo un problema con el formato para probar los test. Siguiendo lo mencionado en las issues #370 y #378, utilize el mismo formato que se utilizo para obtener una lista de diccionarios con los pokemones como se tenia previamente pero ordenados por el valor pedido, pero aun asi el testeo me dice que no coincide, aun cuando probe de todas formas, tanto como la del ejemplo como la de las issues. Viendo toda la lista en orden descendiente, note que mi quinto lugar, tiene un valor de atk/def que se repite en hartos pokemones, que son variaciones del mismo (tenia que ser justo pikachu). Debido a que todos estos comparten quinto lugar, ¿debo de agregarlos todas las variaciones, aun cuando la lista quede con mas de cinco, o solo cinco?.
Agrego que de la lista de 5 mejores solo deje el valor base para los test y aun asi no funciona.
Saludos

**Comment by SCarcG1** [comment]
Acabo de solucionarlo por mi mismo, y es como dije. Al agregar todos los pokemones en el quinto lugar que comparten la misma estadistica la funcion enviar_test() me respondio con True, por lo tanto me quedo una lista de 19 pokemones. 
Leyendo la issue esto no se entiende claramente, debido a que ponen los mejores 5 y en caso de que no hayan 5 los mejores que hayan en total, sin mención de repetición de estadísticas de los pokemones como en mi caso.
Porfavor marcar con label completado, ya que no puedo con mi parte y quiero dejar mención de lo sucedido.

**Comment by igbasly** [comment]
Hola @SCarcG1 ✌️ 

Gracias por comentarlo, efectivamente se trata de un error en el test que debería estar arreglado durante los próximos minutos. Como menciono en la issue #382, en caso de que se repita el potencial de algunos Pokémon, se debe dejar primero el último en aparecer.
Donde en caso de tener Pokémon como los siguientes, donde `"PA"` es el potencial de ataque calculado:
```python
[
  {"name: "pokemon 1", "PA": 3},
  {"name: "pokemon 2", "PA": 2},
  {"name: "pokemon 3", "PA": 6},
  {"name: "pokemon 4", "PA": 10},
  {"name: "pokemon 5", "PA": 6},
  {"name: "pokemon 6", "PA": 14},
  {"name: "pokemon 7", "PA": 1},
  {"name: "pokemon 8", "PA": 6}
]
```
La función debería retornar:
```python
[
  {"name: "pokemon 6", "PA": 14},
  {"name: "pokemon 4", "PA": 10},
  {"name: "pokemon 8", "PA": 6},
  {"name: "pokemon 5", "PA": 6},
  {"name: "pokemon 3", "PA": 6}
]
```

Espero que se entienda y lamentamos los inconvenientes, quedo atento a cualquier otra duda 😉

**Comment by SCarcG1** [comment]
Sorry, me quedo otra duda con el funcionamiento y con el ejemplo que diste. Si tengo 50 pokemones y 10 de ellos estarian en la lista en la posicion 5, por dar un ejemplo, ¿solo agrego el ultimo de la lista para enviar una lista de solo 5, o me equivoco? ¿Y porque no en orden de aparición en la lista y si desde el ultimo?

**Comment by igbasly** [comment]
Hola @SCarcG1 :v:

Es como tu mencionas, eso se explica debido a la forma en que funcionan las funciones de ordenamiento y es la razón por la que se toman el último al ordenarse de forma descendiente.
