### ISSUE TITLE
excec_

### ISSUE THREAD

**Issue by Baelfire18** [IIC2233/syllabus#384]
Una pregunta estoy usando el objeto QDrag con el metodo exec_(), ¿esto pertenece a la libreria de objetos prohibidos llamada exec? O es un metodo propio de QDrag y por lo tanto esta permitido?

**Comment by Dnpoblete** [comment]
Hola @Baelfire18 está pregunta fue respondida en la issue de librerías prohibidas espero te sea de ayuda, si tienes más dudas por favor hacerlas en la issue correspondiente exito con la tarea! Esta fue la respuesta 😄 : 
> 
> 
> Hola @veneguitas , con respecto al uso de `exec`:
> 
>     * En PyQt5 existen tanto `exec` como `exec_`, los cuales son métodos de `QApplication`. Estos son los que se utilizan para ejecutar la interfaz gráfica de su programa.
> 
>     * El `exec` que se encuentra prohibido es una función _built-in_ de Python. Para más información sobre este puedes revisar este [link](https://docs.python.org/3/library/functions.html#exec).
> 
> 
> Entonces pueden utilizar `exec` y `exec_` cuando lo llames como un método de `QApplication`.
> 
> ¡Ánimo y éxito con tu tarea! 👋🌾
