### ISSUE TITLE
Sobre pago en la expiración

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#384]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Cuando jack sparrow le roba la mercancía a un barco, este al salir del canal no pagará. Sin embargo, qué pasa si una o todas las mercancías expiran? Te paga menos/no paga/sí paga?

**Comment by Emiliax16** [comment]
@fernandosmither , lo primero que dices es correcto. Si el barco es atacado por piratas, no paga la tarifa al salir. Respecto a las cajas de mercancías, la issue [#314](https://github.com/IIC2233/syllabus/issues/314) detalla todo lo relaciones con los eventos de las mercancías.

Saludos!
