### ISSUE TITLE
Error Segmentation Fault

### ISSUE THREAD

**Issue by Ariimaw** [IIC2233/Syllabus#384]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo implementados el conejo, los lobos y las bombas, estas se pueden agarrar y colocar, y los lobos caminan en la dirección asignada periódicamente, sin embargo tengo un problema con los cañones, en específico con las zanahorias que estos disparan, estas me crashean el programa de forma aleatoria.

He re-hecho el código de las zanahorias por lo menos 3 veces (usando métodos distintos) intentando arreglar el problema pero nada parece solucionarlo y al googlear en internet al respecto no sale mucho relacionado con pyqt en python, entonces no me queda claro cómo arreglarlo por que el mensaje de error es solo lo siguiente: Segmentation fault. Y Segmentation fault es todo lo que sé de mi error :( Sé que es un problema con las zanahorias por que tengo funciones que crean mis tipos de entidades y probe con cada una, el problema solo se da cuando los cañones están lanzando zanahorias.  

Por lo que dice Google se supone que Segmentation fault es una clase de error que uno recibe cuando se intenta acceder a memoria a la cual no tenemos permiso de acceder, o cuando uno intenta poner el puntero de un array (por ejemplo, de tamano 7) en una posición que no tiene (ej, 8). Para la opción 1 intente hacer lo que decía san Google y que es también lo que me recomendó una ayudante en la última programaton, que es aumentarle el espacio a la memoria de python con "ulimit -s <new_value>", sin embargo esto no me resolvio el problema. En ese entonces mis zanahorias estaban en un while True: y decidí cambiarlo ya que quizás la mala práctica podría ser el problema, sin embargo después de hacerlo con QTimer el problema persiste y ya no se que hacer </3. Se que es un problema algo aleatorio porque no está ni ligado a que el conejo camine o no, a veces se demora muchos segundos en pasar, a veces apenas abro el juego, a veces simplemente no pasa en todo el nivel.

No se que tanto puedo explicar mi codigo pero a grandes rasgos, mis zanahorias son de una clase que hereda de Qlabel, tienen un identificador único y un Qtimer, el Qtimer cada cierto tiempo llama a una función que setteará una flag propia del Qlabel a True. Aparte de el QLabel tengo una clase que hereda de QThread que se llama MovimientoZanahoria que simplemente toma el Qlabel (ya que tengo entendido que estos no pueden modificar su propia ubicación) y lo mueve lo necesario para crear el movimiento de disparar la zanahoria todos los bloques que debe avanzar. Cuando este proceso termina, se manda una señal para avisarle al Qlabel que el movimiento terminó y se settea otra flag interna del Qlabel a True. Solo cuando ambas flags internas sean True se triggerea la función que dispara las zanahorias de nuevo, osea que tienen dos requisitos: que el Qtimer haya dado el visto bueno y que la animación haya terminado. Perdon si fui muy explicita pero el error ha sido tan persistente que poco menos no deja jugar el juego con los cañones andando, y no me gustaría tener que elegir entre entregar la tarea sin los cañones que si me funcionan y disparan bien o entregar con ellos y que me bajen incluso más nota pensando que el juego esta todo mal hecho cuando el conejo, las bombas y los lobos van todos bien </3

Verdaderamente en comparación con cómo hice el conejo y las bombas y los lobos, las zanahorias son de lejos lo más simple entonces no entiendo porque estas están dando tanto problema :( Quizás tenga algo que ver con que a mi computador no le guste que las tepee? (teletransporte?) pero todas las Qlabels de mi programa hacen eso constantemente y no dan problema.

Cualquier ayuda la apreciaría enormemente ya que juro que yo encantada me pondría a googlear como nerd sobre como solucionarlo pero el contenido no tiene que ver con pyqt en sí y siento que ya se escapa de mis manos y también de lo que evalúa el curso WBUUAAAGHH </3

**Comment by ignacio-sp** [comment]
Hola @Ariimaw, puedes subir el código (a tu repo sería mejor) de dónde sospechas puede estar el problema relacionado a las zanahorias? De antemano intenta revisar si el problema es parecido al de esta [issue](https://github.com/IIC2233/Syllabus/issues/368#issue-1977106172) y ver si no hay algún carácter raro, avísame que tal te va!

**Comment by Liper1** [comment]
lo arreglaste? me pasa lo mismo, estoy chato q se crashee ;-;
