### ISSUE TITLE
 Problemas con uso de generadores

### ISSUE THREAD

**Issue by andreslyon** [IIC2233/Syllabus#384]
Hola, Como puedo solucionar esta situación:
def f(iterador):
     r1 = map(lambda i: ""alguna funcionalidad"", iterador)
     r2 = map(lambda i: ""otra funcionalidad"", iterador)
resulta que si el iterador es un generador, en el segundo map, el iterador ya esta borrado y no lo puedo usar. Por lo que me veo obligado a pasar mis iteradores a lista, si es que los quiero usar 2 veces.  
Como puedo evitar que mis iterables se borren? gracias

**Comment by Arcoirisky** [comment]
¿Probaste con buscar la repuesta en Google o en alguna issue o en el mismo material? Dale un par de vueltas e intenta resolverlo. Sé que puedes 💪

**Comment by andreslyon** [comment]
Si, talvez hice mal la pregunta. A lo que voy es que, en terminos de funcionalidad, pasandolo a lista mi programa funciona, y niun problema. Pero no se si hacer esto haga que mi tarea tenga menos puntaje o algo asi. Es decir, dejarlo como lo tengo hasta ahora se considera mala práctica dentro de la programacion funcional, o da lo mismo?

**Comment by Arcoirisky** [comment]
Al final, todo depende de qué tanto estás guardando. Como ya te diste cuenta, el genoma es gigante. Y si guardas una lista demasiado grande, aunque corra bien en tu computador, puede que otro muera (Piensa en cualquiera con menos RAM que un celular). 

Podrías buscar métodos para copiar iteradores o algo parecido que se asemeje a tu problema. 

Salu3~
