### ISSUE TITLE
Error de consulta

### ISSUE THREAD

**Issue by josemlira** [IIC2233/Syllabus#384]
si hago:
["asignar", "x", -2]
["crear_funcion", "exponencial", "x"] 
me deberia arrojar: 
Error de consulta: crear_funcion("exponencial", -2) 
o 
Error de consulta: crear_funcion("exponencial", "x")
Saludos!

**Comment by Hernan4444** [comment]
@josemlira debería salir `crear_funcion("exponencial", -2)`
Saludos!

**Comment by josemlira** [comment]
Gracias!!
