### ISSUE TITLE
Problema tamaño ventanas con QApplication.setAttribute

### ISSUE THREAD

**Issue by Witomi** [IIC2233/syllabus#384]
Hola!

me pasó que para que se vieran bien las ventanas creadas desde qtdesigner tuve que poner "QApplication.setAttribute(Qt.AA_EnableHighDpiScaling, True)" despues de los imports en el archivo de python, me funcionó bien pero ahora que quiero abrir la ventana del juego con un metodo de la clase de la ventana mencionada al principio aparece de un tamaño muy grande y no sé como arreglarlo, puse antes de mostrar la ventana del juego dentro de la funcion que la inicia el codigo "QApplication.setAttribute(Qt.AA_DisableHighDpiScaling, True)", el cual no me funciona para desactivar esa forma de visualizacion si la pongo en el metodo, pero si me funciona si lo pongo al inicio del archivo justo despues de los imports

**Comment by hbkim94** [comment]
Hola @Witomi ,

Esta es una repsuesta tentativa porque no estoy 100% segura si funcionará, pero ¿has probado con tener la clase de la ventana de juego en otro módulo de python, sin tener `QApplication.setAttribute(Qt.AA_DisableHighDpiScaling, True)` después de los import? 

Espero que sí funcione!

**Comment by Witomi** [comment]
Pucha asi es como ya lo tenía de antes, pues sigue apareciendo bien el menú pero la ventana del juego gigante

**Comment by hbkim94** [comment]
@Witomi 

Si tu problema persiste, ¿podrías subir tú código actual en tu repo, cosa de que podamos darle una revisada al problema? Según consulté, hay posibilidad de todas formas de que podamos ser más flexibles con problemas relacionados a resolución de pantalla.

**Comment by Witomi** [comment]
Lo acabo de subir!

**Comment by hbkim94** [comment]
Hola @Witomi !

Revisé el caso con tu código, y creo que la mejor solución a estas alturas es que especifiques en tu `Readme.md` que tu ventana de inicio funciona bien teniendo `QApplication.setAttribute(Qt.AA_EnableHighDpiScaling, True)`  y que la ventana de juego funciona bien al eliminar o comentar esa línea (tienes que especificarlo sí o sí).

Como te dije anteriormente, vamos a ser más flexibles con problemas de este tipo, así que no te preocupes por eso. Haré aviso de tu caso a los encargados correspondientes de todas formas.

P.D. : Noté a la rápida que al achicar el tamaño de celdas, el frontend de tu ventana de juego no se ajusta de la manera correcta. Lo siguiente no lo verifiqué, pero cuidado con que carguemos un mapa que tenga distintos números de elementos para las filas/columnas y que tu programa no se ajuste bien!
