### ISSUE TITLE
Semana 4, Ejercicio 2.7

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#384]
Hola!!

En este ejercicio se pide que los errores sean "atrapados" en el `main`. Esto significa que en la definición del método `guardar_lineas()` solamente podemos levantar errores `(raise)`.
En una parte debemos levantar un error si el `input` del usuario no es un número. Logré hacer esto con la función `isnumeric()` y con el uso de `try, expect`. 
Mi duda es si existe una forma de levantar este error sin el uso de `isnumeric()` o `try, expect`, ya que este último en teoría no debería ser usado.

**Comment by MatiasDuhalde** [comment]
Hola @amahns1 !

Tal como dices, la idea es que no ocupes bloques `try, except` dentro de la función `guardar_lineas`, y sólo se haga en el `if __name__ == "__main__"`. Para levantar la excepción en caso de un input no numérico, existen varias formas de hacerlo.

Una opción sería usando condicionales + `isnumeric` o `isdigit`, como en el siguiente ejemplo:
```python
if not input_string.isnumeric():
    raise ValueError("oh no")
```

Otra opción, aún más simple, sería intentar convertir el string directamente, usando `int`:
```
n_input = int(string_input)
```
Si `string_input` tiene un valor que no se puede pasar a `int` (por ejemplo `"hola"`), la función `int` automáticamente levantará una excepción del tipo `ValueError`, que podrá ser atrapada en el `if __name__ == "__main__"`.

Ojalá esto aclare tu duda, y si no, pregunta! 😄

**Comment by amahns1** [comment]
Aaaa ya entiendo. Con levantar el error entendí que era obligación utilisar `raise`. 

Muchas gracias :)
