### ISSUE TITLE
primer alimento

### ISSUE THREAD

**Issue by rpbarrera** [IIC2233/syllabus#384]
Saludos, ¿no hay problema si es que al momento de adoptar la primera criatura obligo a que el usuario compre un alimento ?, es por un tema de que se me facilita que tenga alimentos desde el principio para el manejo de los archivos.

**Comment by mpsubiabre** [comment]
Hola @rpbarrera!

Recuerda que el primer alimento es aleatorio, revisa la  issue #335 :)

**Comment by rpbarrera** [comment]
Uuh muchas gracias !! <3
