### ISSUE TITLE
namedtuples como variable global?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#384]
Hola, para la tarea 3:
1. Está permitido el uso de namedtuples? Dado que no es un clase pero es una estructura de datos de collections, librería que está permitida..
2. Pueden escribirse de manera global (_i.e fuera de las funciones, al comienzo del archivo_)?

**Comment by IchottMano** [comment]
@naquiroz Hola!

Como dice **el enunciado**, si puedes usar namedtuples y también puedes escribirlas de manera global, aunque esto **no sea necesario**.

Saludos!
