### ISSUE TITLE
[ACB] STATS

### ISSUE THREAD

**Issue by agustinbc7** [IIC2233/Syllabus#384]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, quería imprimir el dato "stats" del diccionario que genero al hacer request a la url de cada pokemon en obtener_pokemones (imprimí solo el del primer pokemon), para así ver cómo obtener el base_stat, effort y el nombre de la stat, pero al imprimir me salen múltiples base_stat, effort y name, ¿con cuál me debo quedar o estoy haciendo algo mal?

**Comment by igbasly** [comment]
Hola @agustinbc7 :v:

Lo que mencionas está bien, ya que el atributo `stats` de cada Pokémon es una lista de diccionarios con la información de cada uno.
Ahora, debes tomar toda esa información y transformarla al formato solicitado, es decir, un diccionario donde cada llave es el nombre de la "stat" y el valor es otro diccionario solo con la información pedida.

Espero que se entienda, saludos 😉

**Comment by agustinbc7** [comment]
Se entendió perfecto! muchas gracias
