### ISSUE TITLE
Error al realizar todas las consultas

### ISSUE THREAD

**Issue by Dyoma3** [IIC2233/Syllabus#385]
Cuando selecciono Realizar todas las consultas y alguna de ellas tiene un booleano, me aparece un JSONDecodeError. Sin embargo, si lo hago con la opcion de Realizar consulta(s) seleccionada(s) no me aparece este error.

**Comment by Hernan4444** [comment]
@Dyoma3 hiciste pull de la nueva gui?

**Comment by Dyoma3** [comment]
@Hernan4444 si

**Comment by pcseisdedos** [comment]
Quizás sea lo mismo de #328

**Comment by Hernan4444** [comment]
Por favor indícame como llegaste a generar ese error, `JSONDecodeError` o si es el mismo que #328, porque no debería ocurrir, así que mejor si me indican el error para arreglarlo. 

Saludos ✌️

**Comment by Dyoma3** [comment]
@Hernan4444 es el mismo que #328 y ocurre solamente cuando ingreso Realizar todas las consultas y hay un booleano, si lo hago con realizar consultas seleccionadas me funciona bien.
![untitled](https://user-images.githubusercontent.com/17127676/39412305-8fe16ce2-4bf0-11e8-8ee1-78462649ffc0.png)

**Comment by naquiroz** [comment]
Me ocurre lo mismo, que sucede al final?

**Comment by jpsiegel** [comment]
up

**Comment by Hernan4444** [comment]
Hola, es un error de la interfaz con el manejo de Json, pero no se preocupen, al momento de corregir tendremos la interfaz sin ningún error.

**Comment by jmwielandt** [comment]
@Hernan4444 le puedes poner la label "Importante" pls?

**Comment by Hernan4444** [comment]
Hola,
 En la gui.py tienes que ir a la línea 102 que dice:
```python
array.append(json.loads(querry.text().replace("'", '"')))
```

y cambiarla por 
```python
text = querry.text().replace("True", 'true').replace("False", 'false')
array.append(json.loads(text.replace("'", '"')))
```

Con eso debería funcionar.

**Comment by auirarrazaval** [comment]
A mi me sigue saliendo el error
`json.decoder.JSONDecodeError: Expecting value: line 1 column 63 (char 62)`
