### ISSUE TITLE
[ACB] Error enviando test

### ISSUE THREAD

**Issue by namadatzis** [IIC2233/Syllabus#385]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Estaba probando el test de la primera función **obtener_info_habilidad** pero me arroja error. Ante esto me surgen varias dudas: 

Se supone que en la Parte I obtengo mi habilidad, que en mi caso es la **51**  https://pokeapi.co/api/v2/ability/51/
Esta url la uso de argumento para **obtener_info_habilidad** la cuál pide un dict de 3 elementos, lo que yo entiendo es:

1. "name": Debido a que me dieron la habilidad con id = 51 este tendrá un valor único
2. "effect_entries": Al ser una única habilidad también la descripción del efecto es una, sólo que debo filtrar por idioma y guardar sólo la que esté en inglés
3. "pokemon": lista de varios pokemones que poseen la habilidad, con cada pokemon como diccionario con las llaves 'name' y 'url' 

Está correcto? es lo que entiendo y lo que hice en la función **obtener_info_habilidad** sin embargo el test me lanza error:

{"result":"error","message":"Las respuestas no coinciden con lo solicitado"}

Gracias!!

**Comment by igbasly** [comment]
Hola @namadatzis :v:

Efectivamente como mencionas eso es lo que debe retornar tu función 👌 .
Ahora, estuve viendo tu código y te recomiendo que revises bien que es lo que se está retornando (puedes imprimir la respuesta de tu función), ya que no se está manejando de manera correcta.

Quedo atento, saludos 😄
