### ISSUE TITLE
Error al hacer setValue de un progressBar

### ISSUE THREAD

**Issue by furzuadr** [IIC2233/syllabus#385]
Al hacer setValue del progressBar de mis enemigos al atacarlos, mi programa se cae con el siguiente código: QPainter::begin: A paint device can only be painted by one painter at a time.
Alguna posible solución? Gracias!

**Comment by jeschuwirth** [comment]
Saludos.

QPainter no se puede utilizar en cualquier thread sólo en el thread principal. 
source: https://forum.qt.io/topic/43362/how-to-paint-on-a-different-thread/2

Podrías hacer que en cada iteración del thread principal se cuente el número de enemigos que murieron desde la iteración anterior y así ir avanzando la barra. 

Espero que te sirva y suerte en la tarea

**Comment by furzuadr** [comment]
Estoy mandando una señal al thread principal para que haga el setValue y igualmente tengo el error!
Seguí los pasos según eso y nada! Gracias igualmente!
