### ISSUE TITLE
Probabilidad Recuperar Criatura

### ISSUE THREAD

**Issue by JaviGuzman** [IIC2233/syllabus#385]
Hola, me queda una duda sobre cómo saber si el magizoólogo va a recuperar a una criatura o no. Si ya tengo el valor generado de la fórmula, con qué lo relaciono para saber si realmente la recuperó o no?

**Comment by mpsubiabre** [comment]
Hola  @JaviGuzman!

Tu pregunta esta resuelta en la issue #325 :)

**Comment by JaviGuzman** [comment]
Gracias! Busqué y no había encontrado nada parecido. Pero me sigue quedando la duda.
Ya que por ejemplo, nos entregan el valor de prob de que un Augurey se escape, y también la fórmula para el método escape. En ese caso si prob Augurey escaparse < prob generada de la formula, entonces se escapará?

Por otro lado, es distinto con la prob de que un magizoologo recupere a una criatura, ya que solo tenemos la fórmula para generar esta probabilidad. En este caso debo hacer un random para entregarle al magizoologo?
Ejemplificando:
si prob_recuperar_criatura(calculado con la formula) < prob_generada(prob entre 0 y 1 con random), entonces el magizoologo va a recuperar a esa criatura?

Y si fuese asi, esa prob_generada queda asociada al magizoologo, o se ocupa solo para ese caso, y en caso de querer recuperar a otra criatura se debe volver a generar una prob con random?

Espero que se entienda, y gracias!

**Comment by fdoflorenzano** [comment]
Hola @JaviGuzman,
Iré en orden por tus dudas:

1. Ten ojo, la probabilidad **final** para considerar en estos eventos es lo que resulte de la fórmula. Si te fijas, en la descripción de "probabilidad de escape" dice que es una probabilidad **base**, y en la fórmula de escape se incluye este valor como parte del cálculo. Luego, debes usar ese valor calculado como el punto de comparación para determinar si se escapa o no una criatura. Como es descrito en #325.

2. Ojo, la comparación debe ser al revés. Imagina la probabilidad de recuperar resulta dar `0.7`. Esto representa que tiene un 70% de probabilidad de recuperar con éxito. Si generas aleatoriamente un número entre 0 y 1, y comparas `prob_recuperar < valor_generado`, solo el 30% de las veces se cumplirá que es mayor. En cambio, al comparar  `valor_generado < prob_recuperar` el 70% de las veces `valor_generado` cumple con la comparación.

3. El valor generado aleatorio se debe generar para cada vez momento distinto y acción que lo requiera. De lo contrario, al almacenarse, la probabilidad de futuros eventos quedarán condicionados a este, y las probabilidades pedidas no se cumplirían.

¡Espero se entienda!
Saludos.

**Comment by JaviGuzman** [comment]
Me quedó mucho más claro, gracias!!
