### ISSUE TITLE
GitIgnore

### ISSUE THREAD

**Issue by criss199** [IIC2233/syllabus#385]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda con el gitignore, no me queda  claro como se usa, ni como crearlo... tampoco encontré alguna guia donde expliquen como se usa y que es lo que se espera.

**Comment by Emiliax16** [comment]
Hola @criss199 ! lo que yo te recomiendo es copiar y pegar el gitignore del Syllabus en tu carpeta de la tarea. Luego borras su contenido y comienzas a rellenarlo.

Lo primero es pensar que no se subirá al repositorio:

- Enunciado.pdf
- archivos.csv
- __pycache__/

En el gitignore debes agregar literal los archivos que no quieres que se suban, simplemente con el nombre y extensión.
Debes subir el gitignore a tu repositorio de la misma manera que se suben los archivos .py.

Avísame si sigues teniendo dudas!
