### ISSUE TITLE
Duda sobre la temperatura del jardín y pasar día

### ISSUE THREAD

**Issue by momse11** [IIC2233/Syllabus#385]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Buenas. Por lo que entiendo de "pasar día" es que primero se cambia la temperatura del jardín. Si ese es el caso, entonces la temperatura inicial del jardin no se utiliza en la simulación de un día?

**Comment by augustayanez** [comment]
Si con "temperatura inicial" del jardín te refieres a la temperatura antes del cambio especificado en la sección 5.1 (modificar la temperatura actual por un valor aleatorioentre TEMP_MIN_JARDIN °C y TEMP_MAX_JARDIN °C), entonces efectivamente al *Pasar Dia* la temperatura inicial (antes del cambio) no se utiliza porque en realidad correspondería a la temperatura del día anterior. Por lo tanto, lo primero que debes hacer es cambiar la temperatura según lo descrito en la sección 5.1.
