### ISSUE TITLE
Comprar tecnología

### ISSUE THREAD

**Issue by margavicunas** [IIC2233/syllabus#385]
Hola!
En el enunciado (sección 4.1.1) dice que cada tecnología tiene un costo de 20 DCCoins cada una, ¿Eso significa que el usuario puede elegir qué tipo de tecnología comprar? ¿O simplemente compra ambas automáticamente x 40 DCCoins?

Gracias de antemano :)

**Comment by jitorcas** [comment]
Hola! @margavicunas 

Dado que no sale explícitamente la manera en que debes implementar la compra de tecnología, podrías hacerlo de la forma que estimes conveniente, respetando que cada una tiene un valor individual y aumentan en cierto porcentaje la tecnología correspondiente.

**Comment by margavicunas** [comment]
Bacán :) Gracias por la rápida aclaración!

**Comment by jitorcas** [comment]
@margavicunas solo para que lo tengas en consideración, todas las palabras y números que estén en el formato mencionado en la sección `5.4. parametros.py` corresponde a **parametros** y debes tratarlos como tal, en el caso anterior deberías tener un parámetro asociado **a cada valor** de implementos y un parámetro asociado **a cada cantidad** de aumento de efectividad asociado. 
En caso que compres los implementos juntos, al variar cualquier parámetro anteriormente mencionado debería verse reflejado correctamente.

**Comment by margavicunas** [comment]
Ohh, me confundí xd ¿Por qué habría de cambiar el parámetro NIVEL_IMPLEMENTOS?  Pensé que sólo cambiaba el atributo de implementos médicos o implementos deportivos de la delegación

También, leí que NIVEL_IMPLEMENTOS sólo se refería a implementos deportivos, ¿eso cambia ahora?

**Comment by jitorcas** [comment]
@margavicunas 

El parámetro `NIVEL_IMPLEMENTOS` corresponde a un parámetro asociado al método `Validez de competencia` de `Deportes`. Ese parámetro no influye en el método `Comprar tecnología` de `Delegaciones`. 

Ahora hablando solamente de `Comprar tecnología`, acá tienes distintos valores en juego (20 DCCoins y 10%), dichos valores son parámetros dado que siguen el formato especificado en la sección `5.4 parametros.py`. Al ser parámetros, no debes tratarlos como números fijos en tu programa, si no que asignarles una variable y que se puedan variar desde el archivo `parametros.py` , por ejemplo, en el caso anterior en vez de poner que implementos deportivos tienen un valor de 20 DCCoins, deberías poner que tienen un valor de `VALOR_IMPLEMENTOS_DEPORTIVOS` y asignarle el valor en `parametros.py`. 

Espero me haya explicado de mejor forma, avísame si quedas con dudas!

**Comment by margavicunas** [comment]
Ahhhhhhh perfecto :D Sii ahora me quedó muuy claro. Muchas gracias!!!
