### ISSUE TITLE
Duda sobre caso borde de follower villain

### ISSUE THREAD

**Issue by tomastrivino** [IIC2233/Syllabus#386]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!!
Resulta que mi follower villain elige a donde moverse en función de la distancia con Luigi. Sin embargo, esta función es simple y tiene el caso borde que produce lo siguiente (foto a continuación).
![image](https://github.com/IIC2233/Syllabus/assets/98418205/bdeab796-eb35-4df0-ab43-afd7e437c9a7)

Apenas Luigi empieza a moverse, el fantasma saldrá de ese "loop". A pesar de este caso borde, se dará el bonus ?

PD: mi tarea está "lista". Si pudiesen darme feedback de si funciona en su computador, bacan :) 

Gracias :D

**Comment by lsilvabw** [comment]
Buenas. 
El enunciado pide explícitamente que "Este fantasma debe evitar chocar con obstáculos" por lo que el bonus no estaría bien implementado.
Respecto a el feedback que pides, no es posible dar este tipo comentarios ya que es parte de lo evaluado que el código se ejecute de manera correcta en otros computadores.
Saludos !!

**Comment by tomastrivino** [comment]
> Buenas. 
> 
> El enunciado pide explícitamente que "Este fantasma debe evitar chocar con obstáculos" por lo que el bonus no estaría bien implementado.
> 
> Respecto a el feedback que pides, no es posible dar este tipo comentarios ya que es parte de lo evaluado que el código se ejecute de manera correcta en otros computadores.
> 
> Saludos !!

Wena!! Lo modificaré entonces. Gracias :)

**Comment by lsilvabw** [comment]
> 

Tomas,
Hable con los profesores y quedamos en que si no se queda atorado entonces se consideraría como bien implementado. Puedes ignorar mi primera respuesta :)
Saludos!

**Comment by tomastrivino** [comment]
> 

![gracias](https://images3.memedroid.com/images/UPLOADED453/5eb64c064bcf7.jpeg)

**Comment by Hernan4444** [comment]
Hola @tomastrivino 

Recuerda que las issues no deben ser cerradas. Esto lo haremos nosotros una vez terminada la evaluación.

Saludosヾ(＾-＾)ノ

**Comment by tomastrivino** [comment]
> Hola @tomastrivino
> 
> Recuerda que las issues no deben ser cerradas. Esto lo haremos nosotros una vez terminada la evaluación.
> 
> Saludosヾ(＾-＾)ノ

upsi, gracias ^^
