### ISSUE TITLE
Método lesionarse

### ISSUE THREAD

**Issue by valerianazal** [IIC2233/syllabus#386]
Hola, para el método lesionarse sé que hay una probabilidad de que se lesione el deportista dependiendo del riesgo del deporte, pero ¿Cómo determino si eso ocurre? ¿Hay una forma específica de hacerlo?

**Comment by jitorcas** [comment]
Hola! @valerianazal 

Hay distintas maneras en que puedes implementarlo, te dejaré una como ejemplo:

Supongamos que el riesgo de lesionarse en X deporte es **0.35**, deberás generar una variable `K` que esté asociada a un número aleatorio entre 0 y 1 (hay un hint en el enunciado que te puede servir!). Dicha variable debes compararla con el riesgo de lesionarse y comprobar que si se cumple `True` entonces el Deportista se lesiona, si no cumple `False` entonces el deportista sigue compitiendo. 

Te dejo una [issue](https://github.com/IIC2233/syllabus-2020-1/issues/325) del semestre pasado donde explican lo mismo de otra manera! 

Mucho éxito!
