### ISSUE TITLE
Duda T3 test_07_locales_mas_votos_comuna.

### ISSUE THREAD

**Issue by vichovargas** [IIC2233/Syllabus#386]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola tengo una duda con respecto al  test_07_locales_mas_votos_comuna. cuando corro el test me tira el siguiente error : 
SyntaxError: '[' was never closed.
esto ocurre en los ultimos 3 test de este test, es decir: 
test_5 (__main__.TestLocalesMasVotosComuna.test_5)
  Verifica que se retorne los votantes cuando se manejan pequeños datos.
tambien en el 6 y 7 en datos medianos y grandes. El problema es que, al realizar una prueba manual fuera de los test, la funcion realiza su trabajo correctamente, tambien al cargar los datos en una prueba manual se ve como se instancia la named tuple de manera correcta. No se a que se pueda deber este error no sé si será un error del test, o un error al cargar el archivo. Gracias

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by jfpantoja** [comment]
Hola @vichovargas!
Según lo que comentas, puede ser que haya un error debido a que pudiste haber modificado sin querer algún archivo de los test. En ese caso te recomiendo que pruebes reemplazando los archivos de los test que tienes por los archivos que se encuentran en el syllabus del curso que no han sido modificados (esto incluye la carpeta ```test_publicos``` y los archivos ```test_solution.py```, ```todos_tests.py``` y ```test_elementos_prohibidos.pyc```).
Si no se arregla, te pido si puedes mandar una foto del error que te muestra y hacer un push para revisar más en detalle.

**Comment by vichovargas** [comment]
Hola, ya lo pude arreglar, era un error mío al momento de cargar los archivos, muchas gracias.
