### ISSUE TITLE
Evaluar con intervalo 

### ISSUE THREAD

**Issue by JoseValencia125** [IIC2233/Syllabus#386]
Al usar la función Evaluar y dar un intervalo que no sea un divisor exacto del conjunto ¿que hago? ¿Dejo el ultimo termino como fin, como el valor más cercano, o levanto un error?
ejemplo: si inicio = 1, fin = 4, intervalo = 0.4
¿(1.0, 1.4, 1.8, 2.2, 2.6, 3.0, 3.4, 3.8) o (1.0, 1.4, 1.8, 2.2, 2.6, 3.0, 3.4, 3.8,4.0) o error?

**Comment by Hernan4444** [comment]
según tu ejemplo debería ser (1.0, 1.4, 1.8, 2.2, 2.6, 3.0, 3.4, 3.8)
Saludos!
