### ISSUE TITLE
Agrupar mapa

### ISSUE THREAD

**Issue by SamWeinstein** [IIC2233/syllabus#386]
Hola! Cree el mapa de forma "manual", es decir, posicionando cada label según su posición en la ventana sin usar layouts. ¿Como se pueden agrupar todos los labels del mapa para poder manipular el mapa entero? Para poder moverlo, agregarlo a un layout, etc. 

Muchas gracias!!

**Comment by jeschuwirth** [comment]
Hola @SamWeinstein,

No hay una manera exacta, pero te propongo 2 opciones que te pueden ayudar.

cuando creas cada label su largo y ancho dependen del parámetro N, si lo hiciste a mano, probablemente la posición en un eje es algo del estilo `N*pos`, con pos un int entre 0 y el largo. Para moverlo puedes agregar un nuevo parámetro llamada pos_inicial_x, de modo que cada posición de un cuadro sea `pos_inicial_x+N*pos`.

El otro modo que es un poco más amplio es crear un set, una lista o una matriz en el front_end. En este array vas ingresando cada Qlabel a medida que lo creas, de ese modo si quieres cambiar algo basta con iterar sobre el arreglo.

Espero alguna de estas soluciones te ayude :)

Suerte!

**Comment by SamWeinstein** [comment]
Buenísimo! Muchas Gracias!!!

**Comment by mpbascunan** [comment]
@jeschuwirth si ya tengo creado el mapa usando la primera opción que pusiste, como hago para agregar todos esos labels a un layout para que así cuando agrande la ventana el mapa no quede desajustado respecto a los demás labels de la ventana. O tendría que crear otra ventana poner los demás labels de la ventana?

**Comment by jeschuwirth** [comment]
@mpbascunan, perdón por la demora 😅.

La primera opción no ocupa layouts en absoluto, basta con colocar los labels dentro de un set o lista. 

Por esa razón no cambiará el tamaño del mapa si uno cambia el tamaño de la ventana. No hay problema si tu tarea no se ajusta a ese cambio.
