### ISSUE TITLE
Comentarios Entregable

### ISSUE THREAD

**Issue by stephichau** [IIC2233/Syllabus#386]
1. Está bien que usen las estructuras por comprensión pero varias funciones que deberán crear para poder sacar la información genética están hechas para que usen harto la materia de funcional: `map`, `zip`, `filter`, `reduce`, etc.  Si no ven donde ocupar al menos alguna de estas, no está de más revisar la materia denuevo, ya que estas funciones les solucionarán y ahorrarán harto código.

2. No abusen del uso de `try/except,` y recuerden que (como sale en la materia) existe el `else `y `finally`. Tal vez con estos puedan reducir el uso y lograr lo que querían hacer.

3. Intenten trabajar con objetos generadores hasta el final. No es necesario que hagan `list(map(filter … ))`, sino que pueden trabajar directamente con `map`, `zip` y `filter`.

4. Complementando el comentario anterior, recuerden que funcional se encarga de instanciar los elementos a medida que se necesitan mientras que una lista no, estas instancias todos sus elementos. Tengan precaución de que un genoma con más de 1000000 de genes ocupa mucha memoria ram (si es que se instancia) y por lo tanto es mucho más lento en contraposición con funcional que no presenta ese problema.

5. Al igual que con las listas, los diccionarios ocupan memoria RAM, y si se tiene todo instanciado en ellos, el programa no funcionará de manera óptima y aparte se hará uso innecesario de memoria. Puede que haya casos que sea útil usarlos (incluyendo algunas partes de esta tarea), pero no siempre son la solución y hay una manera más simple de hacerlo.

6. Tengan en mente que hay consultas que usen los fenotipos y otros que usan el genotipo. Muchos están haciendo funciones que leen el archivo *genomas.txt* y retornan los fenotipos de esa persona. Si hacen eso, tendrán que buscar nuevamente en el archivo los genotipos y ahí no están atomizando. Lo ideal sería leer el archivo, retornar genotipos y luego tener otras funciones de interpretación para obtener el fenotipo dado un genotipo.

7. Como en generadores los valores son solamente instanciados a medida que se necesitan y luego se pierden, es importante hacer uso de los valores lo más posible cuando se instancian porque luego ese generador ya no sirve para ser recorrido una segunda vez, por lo tanto cuidado con tener varias funciones que se encargan de recorrer un mismo generador.

8. Sean super inteligentes en que momento usar generadores, como indican los comentarios anteriores, los generadores se recorren solo una vez y van entregando un valor a la vez, de esta manera preguntense ¿Cuando me conviene crear un generador que lea los datos solo una vez? ¿Qué datos debería tener guardados? ¿Serán muchos datos como para usar listas, diccionarios u otra estructura?.

9. Un muy buen indicador de si están haciendo las cosas bien, es el tiempo que se demora su programa, si se queda pegado a cada rato significa que no están haciendo buen uso de funcional y probablemente no esté tan bien modelada su tarea.

10. Si ven que una función está quedando demasiado compleja, piensen como sub-dividir las tareas que ejecuta su función en otras más simples, y esas utilícenlas para conformar su función final.

**Comment by inmadariaga** [comment]
respecto al punto 7:
es eficiente tener un iterador y pasarlo a generador cada vez que quiero buscar algo en el?

**Comment by bedefrunner** [comment]
Sobre el punto 1, es obligación usar cada uno de los built-ins `map`, `zip`,` filter`, `reduce`? Ya termine la parte de leer el genoma y ocupé `map`, `filter`, generadores y listas y diccionarios por comprensión, pero nunca `zip` ni `reduce`. Tendré menos puntaje por eso? Si tampoco usé funciones generadoras, me bajarán puntaje también?

**Comment by NotSimple** [comment]
Con respecto al uso eficiente de la memoria RAM. Hay consultas que requieren de la informacion de todas las personas (por ejemplo _pariente_de_), seria mejor (en terminos de calidad de codigo) tenerla toda instanciada previamente o instanciar toda la informacion de __todas__ las personas __cada__ vez que se quiere acceder a ella?

**Comment by Hernan4444** [comment]
@inmadariaga si el iterador ya está instanciado, pasarlo por un generador no ayuda a la eficiencia puesto que no estamos reduciendo la cantidad de memoria con eso.

@bedefrunner recuerda que también hay consultas, ahí puede existir forma de utilizar `zip` o `reduce`, no es necesario que solo en leer el genoma utilices todo.

@NotSimple  la idea es recurrir lo más posible a funciones minimizando la RAM, instanciar todo puede ser una pésima idea cuando no sabes el largo de los gen que pueden haber (por ejemplo ahora se subió un archivo cuyos genes son muchos más largos que antes). La idea es que logren crear una forma de instancia que permita realizar las consultas necesarias pero sin instanciar cosas extras

**Tips**: una buena forma de instanciar  a las personas para esta tarea sería aquella que no depende del número de genes para cada característica pero de todos modos permite hacer consultas a fenotipo y genotipo al mismo tiempo

Saludos ✌️

**Comment by behrmann97** [comment]
Respecto al punto 4, ¿sirve tener una función que al ser llamada retorne un generador con las personas?

**Comment by Hernan4444** [comment]
@behrmann97 si sirve 👍 
Saludos ✌️

**Comment by fedetaladriz** [comment]
@Hernan4444 @stephichau 
No me queda claro el tema de la memoria RAM. Hasta este momento, lo que había hecho fue crear un diccionario con el genoma ordenado, ya que se utilizaba en las consultas varias veces. Si utilizo un generador para ahorrar memoria voy a poder utilizarlo sola una vez, entonces, como debería guardar la info para poder utilizarla posteriormente? O me recomiendan leer TODAS las características necesarias para no volver a utilizar el genoma? 
Gracias!

**Comment by bedefrunner** [comment]
@fedetaladriz hola, no soy ayudante jajaja pero lo que estai preguntando lo hemos estado discutiendo bastante en la #375. Lo que están buscando con esta tarea es que no leamos absolutamente ningún archivo al inicio del programa, ni genomas.txt ni listas.txt. La idea es que para cada consulta el programa entre a los archivos, lea solo lo necesario, que idealmente no guarde nada en listas ni diccionarios sino que solo ocupe generadores (pues no gastan casi nada de memoria), mostrar los resultados, escribirlos en resultados.txt y, nuevamente, no dejar nada guardado. Después de cada consulta no debiera quedar instanciado ningún diccionario, lista o tupla. Aunque sea poco eficiente, lo importante es que no se ocupe memoria. La razón es que si el programa lee todos lo genomas al principio y los guarda en una lista o diccionario, en caso de que sea un archivo de 10 millones de líneas el computador no va a tener memoria para guardarlo todo y va a caerse el programa.
Al menos eso entendí yo.

**Comment by Hernan4444** [comment]
@fedetaladriz no podemos decirte como debes guardar la información. Una de las dificultades de la tarea es precisamente eso: Analizar el problema y encontrar la mejor modelación que permita consultar y almacenar el mínimo de información.

El único hint que hemos dado en otra issue es el mismo que puse antes:
> una buena forma de instanciar a las personas para esta tarea sería aquella que no depende del número de genes para cada característica pero de todos modos permite hacer consultas a fenotipo y genotipo al mismo tiempo

Sobre la ram es lo siguiente: ¿Que tan bueno es guardar 100000 genes en memoria? ¿Existe alguna forma más sencilla de tratar esa información?

**Comment by mjgutierrez1** [comment]
@Hernan4444  viendo el hint y leyendo las issues me quedo con dos ideas y no se cuál es correcta:

1) Cada vez que se hace una consulta la función de esa consulta se encarga de leer "genomas.txt", sacar sólo la información que necesita para la consulta, interpretarla y que después esa información no quede instanciada en el porgrama.
2) Instanciar al principio del programa a todas las personas o en otros momentos a una persona si me preguntan por ella, siempre que esa instanciación sea eficiente en el sentido de ocupar poca memoria, es decir, tal como señala el hint (que no lo entiendo bien)

Si me pudieras explicar a qué se refiere el hint también lo agradecería (en otra issue vi un hint distinto, que aunque creo que está mal escrito, pareció muy claro en lo que pretendía decir: "una buena (de almacenar la información), es aquella que no dependa del número de genes", pero el hint que pusiste en esta issue no lo entiendo)
