### ISSUE TITLE
Type hinting

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#386]
Hola!
Quería preguntar si el formato type hinting es sólo utilizado para explicar las funciones que debemos implementar en la librería o que si debemos utilizar el módulo typing para escribir nuestras funciones con ese formato específico.

**Comment by maguerrap** [comment]
Tengo la misma duda, necesito saber si me estoy complicando demás por utilizar type hinting o no.

**Comment by Hernan4444** [comment]
Hola, el type hiting solo lo usamos para explicar las funciones. No es totalmente necesario que implementen funciones así, 

Saludos ✌️
