### ISSUE TITLE
Ubicación del archivo .gitignore

### ISSUE THREAD

**Issue by vvialbarros** [IIC2233/Syllabus#386]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Hola buenas tardes. Mi archivo de gitignore actualmente se encuentra dentro de la carpeta de mi repositorio personal y no dentro de la carpeta de tarea, mi duda es que para la tarea 1 me hicieron un descuento que dice asi: "No sube .gitignore pero tampoco los archivos, no se puede evaluar correctamente" mi duda es que mi gitignore si esta subido en la carpeta de mi repositorio, de hecho, puedo acceder al gitignore desde el mismo github y ver su contenido, mi duda es si me dijieron eso porque el gitignore debiera estar dentro de la carpeta T1 o simplemente se equivocaron al corregirme? Esta duda no es para solicitar una recorreccion ni nada, simplemente no quiero tener el mismo error para la tarea 2. gracias de antemano

**Comment by ChupeteBecker** [comment]
Hola @vvialbarros, en cada tarea deberías tener un .gitignore dentro de la carpeta de dicha tarea, esto porque después se hace una recopilación de las tareas y no te revisan directamente desde tu github.

Saludos!!!
