### ISSUE TITLE
Movimiento del Personaje... Lento? [Tarea 02] [Descuentos]

### ISSUE THREAD

**Issue by manarea** [IIC2233/syllabus#386]
Holaaa, les cuento que tengo implementadas las funciones para que el personaje se mueva y choque de manera correcta. Pero resulta que si implemento los métodos necesarios para que choque, se demora un tiempo bastante considerable, y se nota que "no es fluido" al tratar de verificar que no hay un posible elemento con el cual vaya a chocar. Si bien itero solamente los elementos que necesito, y dejo de iterar una vez encuentro algún choque, el personaje se mueve lento de todas maneras. Mi pregunta es, ¿Esto afectará en mi nota? El juego corre super bien, pero ese es el único pero :(

Pd: En caso de que este tema influya, pls ayúdenme a solucionar el tema. Eso, un salu2 y gracias de antemano

**Comment by Hernan4444** [comment]
Hola,

Dada la experiencia de programar juegos donde se implementa la colisión con pyqt5, podemos afirmar que debe haber algo que no está correctamente implementado en tu tarea (por ejemplo, el uso de señales) y por lo tanto, si afectará la nota.

Saludos
