### ISSUE TITLE
[ACB] Problema obtener_mejores_atacantes

### ISSUE THREAD

**Issue by Aledgit** [IIC2233/Syllabus#386]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Buenas,

Tengo un problema similar al del issue #383, tengo dos pokemones que se repiten el potencial de ataque, y he intentado ordenarlos de todas las formas posibles, pero no me resulta.

Digamos que tengo:

{'Pokemon 1': 3.7,
'Pokemon 2': 3.3,
'Pokemon 3': 2.5,
'Pokemon 4': 2.13,
'Pokemon 5': 2.0,
'Pokemon 6': 2.0}

He intentado ordenarlo de las formas:

1: [Pokemon 1, Pokemon 2, Pokemon 3, Pokemon 4, Pokemon 5]
2: [Pokemon 1, Pokemon 2, Pokemon 3, Pokemon 4, Pokemon 6]
3: [Pokemon 1, Pokemon 2, Pokemon 3, Pokemon 4, Pokemon 5, Pokemon 6]
4: [Pokemon 1, Pokemon 2, Pokemon 3, Pokemon 4, Pokemon 6, Pokemon 5]

Y ninguna me resulta :( según yo tengo todo bien en cuanto a haber calculado el ponderador y he revisado la lista que me entrega, verificado en internet para hacer los cálculos por mi cuenta y todo coincide, pero no me resulta.

Ya subí mi código con la versión 2, que en el issue antes mencionado es la que debería funcionar si mal no entendí.

**Comment by agucova** [comment]
Llevo sobre 7 horas pegado en esta función de 6 líneas :(

**Comment by igbasly** [comment]
Hola @Aledgit :v:

No entiendo bien tu problema, pero viendo tu código, creo que haces algunas operaciones demás, lo cual creo que puede estar generando tu error. Te recomiendo ir viendo que formato tiene tu respuesta e ir probando con la API antes de hacer otros cambios.

Quedo atento, saludos 😉

**Comment by Aledgit** [comment]
> Hola @Aledgit ✌️
> 
> No entiendo bien tu problema, pero viendo tu código, creo que haces algunas operaciones demás, lo cual creo que puede estar generando tu error. Te recomiendo ir viendo que formato tiene tu respuesta e ir probando con la API antes de hacer otros cambios.
> 
> Quedo atento, saludos 😉

Hola! las operaciones que hago demás son para sacar al último repetido (aka Pokemon 6 en vez de Pokemon 5)

ya he reviso el formato de mi respuesta, está siento printeado y he probado todas las permutaciones posibles de los 5 pokemones pero ninguna funciona, y estoy seguro que es el formato correcto

**Comment by igbasly** [comment]
Y has enviado una consulta a los tests de la API para cada permutación que has hecho? me parece improbable que permutando no hayas obtenido un resultado correcto.
En cuanto a los `print` los haces justo antes de cambiar los atributos de la lista, entonces no sé que tan bueno sea eso si estás intentando buscar donde falla el código.
Le daría unas vueltas a eso antes 👌

**Comment by Aledgit** [comment]
> Y has enviado una consulta a los tests de la API para cada permutación que has hecho? me parece improbable que permutando no hayas obtenido un resultado correcto. En cuanto a los `print` los haces justo antes de cambiar los atributos de la lista, entonces no sé que tan bueno sea eso si estás intentando buscar donde falla el código. Le daría unas vueltas a eso antes 👌

Si lo hice, antes hacía los prints del diccionario que le llegaba a la API, con las distintas permutaciones y ninguna funcionó, si quieres saco screenshots o te comparto pantalla a través de algún medio

**Comment by Aledgit** [comment]
Aún necesito ayuda, hice de nuevo las consultas con todas las permutaciones y aún no funciona u.u ya calculé los potenciales de los pokemones manualmente también para confirmar que estén bien, y me entrega las listas correctas pero no me reconoce ninguno como correcto.

**Comment by larryuc** [comment]
Estoy en las mismas. Retorno como en el enunciado de la parte IV con el ejemplo (donde se incluye sus datos de ataque y defensa y también como el compañero acá y no hay caso. No reconoce como exitoso. Que será? (está subido mi código tb a github)

@igbasly Puedes mostrar un ejemplo del formsto de la lista que se espera obtener?
