### ISSUE TITLE
QThreads y QObjects, optimización

### ISSUE THREAD

**Issue by jearaneda** [IIC2233/syllabus#387]
Hace unos días pregunté sobre el uso de timers en Qthreads, y me ayudaron con varias cosas para hacerlo funcionar. Uno de los ayudantes mencionó correctamente que los timers andan medio mal con los QThreads por lo que es recomendable buscar alternativas, lo que me llevó a los QObjects

El problema es que es demasiado mejor, y ahora tengo muy pocos threads en mi programa (monedas, controlador de monedas, clase backend). El problema es que por más que cambie el código, los timers en qthreads son muchísimo más lentos llegando a congelar el GUI, mientras que cambiar SOLO la palabra "QThread" por "QObject" en la clase 
-Enemigo(QObject) - hace el juego mucho más fluido.

Cuando hay 20 o más enemigos, por ejemplo, y uso Enemigo(QThread), el programa se crashea, pero logra seguir andando con Object

**¿Hay descuentos asociados a modelar con QObject la mayoría de entidades?** Tengo entendido que se pide usar threads, pero las estoy usando para el tema de monedas

**Comment by jaromero6** [comment]
Hola
Te recomiendo checkear las siguientes cosas:
-  ¿Dentro de los QObject usas QTimer o algún Thread? Si la respuesta es sí, entonces puedes dejar tu programa como está, pues estás usando los threads como se pide.
- Si solo usas QObject, te recomendaría usar los QThreads, en general es raro que las cosas paralelizadas funcionen más lento que las lineales, **si las paralelizadas se están usando de forma correcta**. En este caso te recomiendo ver como estás usando los QThreads, por ejemplo ¿Los detienes cuando corresponde (un enemigo o torre muere, una moneda es recogida o desaparece, etc). El no hacer esto haría que el programa se empieze a ralentizar, dado que se está acumulando los enemigos, es por eso que te recomiendo mirar como los estás manejando en general. Si tienes dudas, puedes subir tú código a tu repo y especificar que archivos mirar para poder ayudarte **(debes tener en mente que si lo haces deberías hacerlo hoy, pues mañana recuerda que no se responden issues)**.
Si aún así esto no logra solucionar el problema, entonces hazlo de igual manera con QThreads, pero especifica en tu README que el programa se prueba con una baja cantidad de enemigos generados.
Quedo atento a tu respuesta, ánimo con la tarea .

**Comment by JJJGGGG** [comment]
Si usas ```QObject```s sin que estén en otros ```threads```, entonces todo va a correr en el mismo ```Thread```, por lo tanto cualquier ```sleep``` o ```while``` va a hacer que tu ```event loop``` principal se demore en actuar, por eso se recomienda hacer calculos en el ```back-end```. Por ejemplo, si hay un botón en tu ```front-end```, y no haces los calculos en el ```back-end``` (en ```thread```s distintos), entonces no vas a poder apretar el botón mientras se estén haciendo los cálculos. Hasta, van a haber muchos problemas para las animaciones si usas while y sleep para animarlos. Creo que con los QTimers no debería haber problema, pero aún así los eventos gatillados por ```QTimer.timeout``` se capturarían en el ```event loop``` principal, por lo tanto afectaría el rendimiento de tu interfaz.

Te recomiendo que revises si no tira un error en especial cuando se cae (hay muchos posibles, esperemos que no sea un [segmentation fault](https://en.wikipedia.org/wiki/Segmentation_fault)), porque es la forma más facil de implementarlo.
