### ISSUE TITLE
Consulta 11

### ISSUE THREAD

**Issue by JoseValencia125** [IIC2233/Syllabus#387]
La consulta 11 en resultados.txt muestra que
----------Consulta 11
['asignar', 'gamma', ['evaluar', ['crear_funcion', 'gamma', 2, 0.16666666666666666], 0, 40, 4e-05]]
Resultado:  asignar
Time: 0.0 second

Sin embargo en el enunciado dice que asignar:

> Guarda el valor de retorno de comando, o el valor de dato, bajo el nombre variable. asignar no permite guardar informacion si el nombre ingresado es igual al nombre de algun comando propio de RQL **o al nombre de alguna distribucion de probabilidad**. 

¿Es un error?

**Comment by Hernan4444** [comment]
#282 
Saludos!
