### ISSUE TITLE
Valores default de clases padre en parametros.py

### ISSUE THREAD

**Issue by vWing7** [IIC2233/syllabus#387]
Hola, cuando tengo un atributo que se implemente en todas las clases hijas, normalmente lo implemento en la clase padre con un valor default para indicar que se tiene que implementar el atributo en toda subclase y el valor default depende del tipo del atributo, ej 0 para int. Mi pregunta es si ese valor default se incluye en parametros.py, porque nunca va a modificar como funciona el programa. Y queria saber si es buena practica o es preferible implementar solo en las subclases.
Gracias

**Comment by fdoflorenzano** [comment]
Hola @vWing7,
Interesante duda, y yo creo que su respuesta puede variar dependiendo a quien le preguntes. La idea de `parametros.py` es mantener los valores constantes del programa que afectan su comportamiento y reunirlos todos en el mismo lugar. Como bien indicas, estos valores base no deberían afectar el funcionamiento de tu programa, por lo que podría perder el sentido almacenarlo ahí.

En este caso creo es aceptable cualquiera de las alternativas. Podrías dejarlo en `parametros.py` para mantener consistencia, como elegir no hacerlo si son valores nulos que no tienen efecto.

Saludos.
