### ISSUE TITLE
Capacidad inventario

### ISSUE THREAD

**Issue by FranciscoCabello** [IIC2233/syllabus#387]
El inventario debe tener alguna capacidad en particular?

**Comment by Dnpoblete** [comment]
Hola @FranciscoCabello en este caso hay tres opciones la primera es que dejes una cantidad fija y lo expliques en el ReadMe, la segunda es que puedas agregar sin un tope y lo expliques en el ReadMe y la última es que crees un parámetro y lo expliques en el ReadMe.

Al final lo importante es que lo expliques en el ReadMe, éxito con tu tarea! 😺
