### ISSUE TITLE
Fichaje de deportistas

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2233/syllabus#387]
Hola! 
Debido a que no debemos modificar el archivo _deportistas.csv_, ¿ una delegación podría fichar más de una vez al mismo deportista? ¿O tenemos que adecuar nuestro código para que los deportistas ya fichados no estén disponibles para otro fichaje?

Saludos y buen lunes :)

**Comment by vicentevegaulloa** [comment]
Hola @ignaciomansuy !

Lo lógico sería que se le notificara al usuario que no quedan más deportistas o que se deshabilitara la opción de fichar. Sin embargo, esto no está especificado en el enunciado, por lo que puedes dejarlo a tu criterio y explicarlo bien en el README 😄

**Comment by nicolasvillarroel** [comment]
La delegación rival puede fichar deportistas? De ser así, lo hace aleatoriamente

**Comment by vicentevegaulloa** [comment]
Hola @nicolasvillarroel !

Basta con que la delegación rival elija aleatoriamente un deportista para cada competencia. El hacer más acciones para el rival queda a tu criterio. Esto significa que no necesariamente el rival tiene que poder fichar deportistas. Espero haber aclarado tu duda 😄

**Comment by amahns1** [comment]
Hola!
Entonces, al menos siguiendo el criterio del enunciado, un deportista puede competir por ambas delegaciones?

Gracias 👍
