### ISSUE TITLE
GenomeError

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#387]
**SE** que hay un issue respecto a este tema, pero la creo para llamar la atención y así sea respondida 😬 #375 
en esencia no queda claro en que minuto hay que usarla.
¿Que se debe hacer con esto? Por ejemplo: borrar el error, no leer la línea, indicar en la consola que el genoma no se puede leer...

**Comment by FernandoPieressa** [comment]
Estimado, al igual que ustedes, los ayudantes también son alumnos y tienen otras cosas que hacer. La otra issue será contestada lo antes posible (pero cuando se llegue a un consenso de la respuesta). Tienes que ser paciente porque los ayudantes si estamos al tanto de las issues que faltan por responder y no necesitas hacer issues duplicadas para llamar la atención. Saludos!
