### ISSUE TITLE
Sobre instanciar varias veces

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#387]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### La pauta menciona
![image](https://user-images.githubusercontent.com/66154723/116347478-44811d00-a7ba-11eb-9651-82ec7310f2b5.png)
### Por último, la forma de instanciar que mencioné en los dos puntos anteriores, es composición?

**Comment by Emiliax16** [comment]
@fernandosmither si puedes hacer ambas cosas que estas nombrando, mientras el manejo del archivo esté correcto y cada vez que se necesite ingresar un barco este se instancie de la manera correcta, no debería haber problema!

No estoy muy segura si puedo contestar tu última pregunta, pero sí. 💯 

Saludos!
