### ISSUE TITLE
Doble decorador/Largo de funciones con decoradores

### ISSUE THREAD

**Issue by jpsiegel** [IIC2233/Syllabus#387]
Si tengo una funcion con dos decoradores, como puedo mantener la referencia al nombre de la funcion original al entrar en el segundo decorador?

**Comment by rihanuch** [comment]
¡Hola @jpsiegel !

```Python
def dec_1(funcion):
    def dec_2(*args, **kwargs):
        return funcion.__name__
    return dec_2

@dec_1
def nombre_de_la_funcion():
    pass

print(nombre_de_la_funcion())

>>"nombre_de_la_funcion"
```
¿Te refieres a lo anterior? 👨‍💻

¡Saludos y éxito! 🍀

**Comment by jpsiegel** [comment]
`def dec_1(funcion):
    def wrapper(*args, **kwargs):
        return funcion.__name__
    return wrapper

def dec_2(funcion):
    def wrapper(*args, **kwargs):
        return funcion.__name__
    return wrapper

@dec_1
@dec_2
def funcion_a_decorar():
     pass`

Mi pregunta iba que cuando se entra al segundo decorador, se pierde el nombre "funcion_a_decorar", queria saber si hay alguna forma de obtenerlo, o quizas hay que darselo al segundo decorador

**Comment by rihanuch** [comment]
No se ha hablado de si está permitido o no, asique tendrás que preguntar si puedes utilizarla en la issue #323 , pero con la función ```wraps``` de la libreria ```functools``` se puede como te muestro a continuación

```Python
from functools import wraps

def dec_1(funcion):
    def wrapper(*args, **kwargs):
        return funcion.__name__
    return wrapper

def dec_2(funcion):
    @wraps(funcion)
    def wrapper(*args, **kwargs):
        return funcion.__name__
    return wrapper

@dec_1
@dec_2
def funcion_a_decorar():
     pass

print(funcion_a_decorar())

>> "funcion_a_decorar"
```

¡Saludos y éxito! 🍀

**Comment by PhilippePotin** [comment]
Un decorador cuenta como una linea extra en una función?

**Comment by rihanuch** [comment]
¡Hola @PhilippePotin !

No, el uso de decoradores no cuenta como una línea extra de una función

¡Saludos y éxito! 🍀
