### ISSUE TITLE
Reglas de programación funcional en funciones auxiliares

### ISSUE THREAD

**Issue by maidazuniga** [IIC2233/Syllabus#387]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una pregunta sobre el uso de funciones auxiliares. Si yo creo una función, esta **debe** estar escrita con las reglas de programación funcional? O puedo crearla "normalmente" sin considerar las restricciones que vienen con el uso de programación funcional?

**Comment by TomasGMDC** [comment]
@maidazuniga si creas/utilizas funciones auxiliares, estas deben respetar el disclaimer para las consultas. Es decir, sí, deben respetar las reglas para la programación funcional. Te recomiendo revisar " #339 " para ver algunos ejemplos de cómo definir funciones generadoras o no generadoras correctamente.

**Comment by maidazuniga** [comment]
Perfecto, gracias
