### ISSUE TITLE
Orden de columnas csv

### ISSUE THREAD

**Issue by diegoheg** [IIC2233/Syllabus#388]
Para esta tarea (T03) ¿Podemos asumir que las columnas de los archivos csv siempre vendrán en el orden en el que nos los entregaron?

**Comment by jmwielandt** [comment]
@IchottMano como en el enunciado no especificaron eso lo tomé a mi criterio y sí lo asumí
Tu respuesta está rompiendo **mucho** de mi código, puedo decir eso en el readme y seguir con mi vida?

**Comment by IchottMano** [comment]
@jmwielandt Hola!

Lamentablemente no 😓 puedes intentar ponerlo en el readme y que el ayudante te tenga compasión, sin embargo ten encuenta que en esta tarea se puede usar el **módulo csv** que te quitaría ese problema de encima

Saludos!

**Comment by jmwielandt** [comment]
El problema es que no está relacionado con la lectura del csv sino con determinadas búsquedas. Tengo por ejemplo que en una fila, la posición -1 es el año de estreno de la película y uso esa información... bastante :'(
(esto es por lo de hacer funciones genéricas reciclables ♻️)

**Comment by IchottMano** [comment]
@jmwielandt Y no puedes hacer una función que ordene tus filas a modo de que la posición -1 sea lo que tu quieras?

**Comment by FJavierOss** [comment]
Se que cerraron esta issue, y se que el foro no es la forma para enviar reclamos. Pero encuentro que no deberian cambiar las reglas del juego como asumir que las columnas pueden estar en cualquier orden especialmente si no fue mencionado en el enunciado y después de al menos una semana después de publicado el enunciado. Varios han tenido que volver ha reescribir el código dada esta situación perdiendo el poco tiempo que tienen. Por favor que las reglas sean claras desde el inicio y esten publicadas en el enunciado, no tenemos tiempo como para andar reescribiendo cada vez el código por cosas que no fueron publicadas en el enunciado en su debido momento. A mi parecer lo considero irresponsable ya que no considera el tiempo perdido y el doble esfuerzo que les significa a los alumnos. Solo pido que si para las otras tareas es posible respetar lo que sale en el enunciado. PD: y lo publico especificamente en el foro porque se de varios que opinan lo mismo y por lo menos todos puedan opinar de asunto que nos involucra como estudiantes.
Se que la pega es mucha para crear las tareas y a veces se pasan  cosas, pero tambien considerennos
