### ISSUE TITLE
Rechazar Buñuelo de Gusarajo y Atacar

### ISSUE THREAD

**Issue by furcelay** [IIC2233/syllabus#388]
Hola,
Cuando una DCCriatura rechaza el Buñuelo de Gusarajo con que lo estoy alimentando ¿puede de todos modos atacar al Magizoólogo?

**Comment by furcelay** [comment]
PD: Perdón por enviarlo un feriado, si no pueden contestar hasta el lunes no hay problema

**Comment by lily416** [comment]
Hola @furcelay 

Como no está definido en el enunciado queda a tu criterio si la DCCriatura ataca al Magizoólogo si es que rechaza el Buñuelo de Gusarajo. Explica en tu README la decisión que tomes y cita esta _issue_.

Éxito en la tarea 👋🧙‍♂️  

PS: Gracias por la preocupación c:

**Comment by furcelay** [comment]
Muchas gracias!

**Comment by tedroppelmann** [comment]
Por lo que entendí una criatura siempre acepta la comida que le da su dueño. No entiendo como rechazaría el buñuelo. Solo existe una posibilidad que mientras come ataque al dueño.

**Comment by fdoflorenzano** [comment]
@tedroppelmann Si revisas la descripción del Buñuelo en el enunciado, se especifica que existe una probabilidad de rechazo.
