### ISSUE TITLE
Parametrización 

### ISSUE THREAD

**Issue by isihirmas** [IIC2233/syllabus#388]
Hola! Qué pasa si varios path de mis imágenes depende de variables que se definen en el juego?  Puedo dejar esas rutas combinadas ( "imagen/"+variable+".png") o necesariamente debo parametrizarla y cambiar todo por varios if?
Sé que las constantes deben ir en parametros.py, pero no me quedó claro si los paths también.

Gracias!

**Comment by JJJGGGG** [comment]
Ponlo en este formato:
```python
PATH = os.path.join("hola", "como", "{}", "?")
```
y después haces simplemente
```python
PATH.format("estas")
```
Supongo que es una buena forma de hacerlo ;)
Si no quieres usar ```os```, puedes hacerlo de esta forma:
```python
PATH = "/hola/como/{}/?"
```
El string formatting es muy bacán

**Comment by gatochico** [comment]
Hola!
Debido a que nunca les cambiaremos los sprites (usaremos los entregados junto al enunciado, o sprites tuyos propios si es que los subes), no es necesario que los nombres de los archivos vayan en parametros.py . Por lo tanto, si estaría bien lo de "dejar las rutas combinadas".

(PD: Recuerda que escribir los paths del modo de tu ejemplo ( `"imagen/"+variable+".png"`) es una mala practica y podrías tener un descuento si el ayudante tiene un SO distinto! Como indica correctamente @JJJGGGG , la idea es que uses `os.path.join`! El segundo tip, efectivamente es bacán 😎 o también puedes poner la variable directamente como `os.path.join("imagen", variable+".png")`, ambas estarán correctas! )

Saludos!
