### ISSUE TITLE
Carpetas frontend y backend

### ISSUE THREAD

**Issue by vmunozgarachena** [IIC2233/Syllabus#388]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, quería saber si era necesario crear carpetas frontend y backend que contengan cada uno de los archivos respectivos, o si simplemente podía poner algo en el nombre de cada archivo, o en el README, para que se distinga bien eso.

**Comment by Hernan4444** [comment]
Hola @vmunozgarachena 

No es obligatorio ocupar carpetas, pero es lo recomendado para así asegurarse de hacer una correcta separación y no caer en la tentación de hacer import desde el backend de algo del frontendo viceversa.

Saludosヾ(＾-＾)ノ
