### ISSUE TITLE
Progresion de tiempo y cultivos

### ISSUE THREAD

**Issue by szabala** [IIC2233/syllabus#388]
En el enunciado explica que los cultivos toman una cierta cantidad de 'tiempo de juego' en cambiar cada fase y ademas, se explica que al dormir, el tiempo de juego cambia al dia siguiente. 

Entonces cuando un jugador duerma, los cultivos deberian crecer el tiempo equivalente que el jugador durmio? o el tiempo de los cultivos es 'tiempo real'?

**Comment by gatochico** [comment]
Hola! 

Los cultivos deben regirse por el **tiempo de juego** en todo momento. Por lo tanto, si el jugador va a dormir, los cultivos deberían crecer el tiempo equivalente a lo que el jugador durmió. Por ejemplo: Si el jugador durmió 8 horas, una vez que se levante para el próximo día, los cultivos deben mostrar el avance correspondiente a las 8 horas que 'no se vieron'.

Espeor haberte ayudado :corn: :four_leaf_clover:
