### ISSUE TITLE
Cambio archivo genoma.txt

### ISSUE THREAD

**Issue by ajahr95** [IIC2233/Syllabus#388]
¿El archivo genoma.txt sera siempre el mismo?, es decir, ¿se probara con el que subieron o tiene que funcionar para otros nombres y apellidos tambien?

**Comment by Hernan4444** [comment]
@ajahr95 se probará con diferentes genoma.txt que sigan la misma estructura. 
En estos momentos estamos puliendo otro genoma que utiliza mucho más genes y hay varios nombres más, pero primero estamos generando un set de consultas a ese genoma para subir todo junto: genoma, listas, consultas y resultados. 

Saludos ✌️
