### ISSUE TITLE
Habilidad especial DCCrotona

### ISSUE THREAD

**Issue by barbarafcp** [IIC2233/syllabus#388]
Hola! En el enunciado sale que la habilidad especial de la delegación dccrotona es ganar una medalla de forma inmediata, mi pregunta era si esta medalla hay que asignarla a algún deporte o simplemente se suma a la cantidad de medallas de la delegación? Gracias con antipiacion :)

**Comment by jitorcas** [comment]
Hola! @barbarafcp 

En la issue #327 puedes encontrar un compilado de issues con las preguntas que ya han hecho anteriormente y sus respuestas. 

Para tu pregunta, puedes leer las issues #340 y #374 . Si quedas con dudas puedes volver a preguntar!

Mucho éxito! 🥇
