### ISSUE TITLE
Característica bonus de mutaciones

### ISSUE THREAD

**Issue by momse11** [IIC2233/Syllabus#388]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Buenas, quería saber si los bonus de las mutaciones deben ser necesariamente atributos/métodos de las mutaciones o si se puede aplicar el bonus de forma indirecta de acuerdo al tablero solamente (por ejemplo, si es que hay una mutacion en el tablero, entonces se aplica el bonus)

**Comment by CrisDonosoMaass** [comment]
Hola! A qué bonus te refieres? Los AUM_POT_CIL y los demás que están así son parámetros constantes que deben estar en parametros.py, no estoy seguro que haya entendido tu pregunta. Si es que no era eso por favor ayúdame a entenderte mejor.
