### ISSUE TITLE
Conexion con el servidor

### ISSUE THREAD

**Issue by rubenmalis** [IIC2233/Syllabus#388]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/243)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/241)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Como puedo hacer para probar bien que el servidor y el cliente estén bien conectados. (Con Vs no me logra correr ambos archivos al mismo tiempo)

**Comment by ignacio-sp** [comment]
Hola @rubenmalis, puedes abrir dos consolas y correr el servidor y cliente por separado, o bien puedes correr uno en vscode y otro en una consola. También puedes hacer esto en vscode abriendo una terminal nueva en la pestaña superior `Terminal -> New_Terminal` y correr el servidor o cliente desde ahí y debería funcionar, saludos!
