### ISSUE TITLE
lists.txt cantidad genes codificantes

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#389]
Holaa! En el archivo de ejemplo que subieron para lists.txt, la cantidad id's y la de genes codificantes para cada id son bajas. Puedo asumir que esto siempre será así? (bajas en el sentido de que no son demasiado espacio de memoria si las guardo) Para ver si es eficiente guardarlos o convendría abrir el archivo cada vez.
Graciaas!

**Comment by TomasSalvadores** [comment]
No puedes asumirlo, podríamos probar las tareas con archivos de cualquier largo, y no sabes la calidad del computador del ayudante que te corregirá. Por estos y mas factores (presentes dentro y fuera del ramo) se espera que con esta tarea demuestren que son capaces de aplicar las técnicas vistas en clases para trabajar eficientemente grandes cantidades de datos, independiente del desempeño de tu computador con los datos de prueba.
