### ISSUE TITLE
AYEX-interfaces gráficas/solución/main no corre

### ISSUE THREAD

**Issue by Luckbox314** [IIC2233/syllabus#389]
Hola, traté de correr el main de la ayudantía extra y funciona al principio pero tras presionar cinco veces el primer botón, se abre una ventana en blanco y no puedo jugar 💃

**Comment by Drpinto1** [comment]
Hola!

¿Estas ejecutando el código desde terminal o desde un editor de texto?

**Comment by Luckbox314** [comment]
desde VSC, pero por alguna razón ahora si funciona
