### ISSUE TITLE
Volver atras en Menú de acciones

### ISSUE THREAD

**Issue by LeoMo-27** [IIC2233/syllabus#389]
En el menú de acciones general, cuando se escoja el menú dcc o el menú cuidar criatura, esta la opción de volver atrás, esta opción, debe pedir el nombre de magizoologo para entrar de nuevo o me debe llevar al menú de inicio?

Muchas gracias!

**Comment by lily416** [comment]
Al seleccionar "volver atrás" en el Menú de acciones, debe volver al Menú de inicio y dar la opción de:
> [1] Crear Magizoólogo
[2] Cargar Magizoólogo
[3] Salir

Saludos y éxito en la tarea 👋🧙
