### ISSUE TITLE
Graficar con opcion 'rango: a,b,c'

### ISSUE THREAD

**Issue by josemlira** [IIC2233/Syllabus#389]
Hola!, al intentar graficar con esta opción, se puede arrojar el gráfico si es que la cantidad de números generados por el rango es mayor o igual a la cantidad de datos? O estas cantidades deben ser iguales? 
De poderse, como es que se tendría que hacer? Solo utilizar los primeros datos generados por el rango? o ajustar de alguna otra forma? 
Saludos!

**Comment by Hernan4444** [comment]
@josemlira tambien tira error, la cantidad debe ser igual
Saludos.

**Comment by nivek0o0** [comment]
Creo que la pregunta era si podemos cortar el rango para igualar la cantidad de datos, siempre y cuando el rango sea más largo.

**Comment by Hernan4444** [comment]
no está bien especificado eso así que quedaría a su criterio aunque yo les recomiendo que tiren error porque a priori esperamos error ante eso, si haces lo otro y lo especificas en el readme el ayudante te lo pondrá bueno de todos modos :)

Saludos!

**Comment by josemlira** [comment]
Gracias!!
