### ISSUE TITLE
Duda error 401 en info_api_curso(token)

### ISSUE THREAD

**Issue by Vabu77** [IIC2233/Syllabus#389]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, en la funcion info_api_curso(token) hago respuesta = get ..... y despues al imprimir respuesta me tira error 401. Lo busque y me sale lo siguiente " The request was a legal request, but the server is refusing to respond to it. For use when authentication is possible but has failed or not yet been provided " por lo que entiendo es que no le estoy pasando el token por lo que no me puede dar la autorización, pero no entiendo que estoy haciendo mal, ya que me guie por como lo ponen en los contenidos. Subí lo que puse a mi repositorio, muchas gracias!

**Comment by Vabu77** [comment]
Hola, ya lo pude solucionar.
Muchas gracias!

**Comment by PedroGiesen** [comment]
Hola!! yo tengo el mismo error y no se como solucionarlo
