### ISSUE TITLE
Consulta sobre el formato considerando el enunciado

### ISSUE THREAD

**Issue by ignaverb** [IIC2233/Syllabus#389]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Holaa,
tengo una duda media básica en relación a los ejemplos que se dan en el enunciado. Más concretamente, en los ejemplos de ventanas de juego no se observa ningún botón de salir pero en la distribución de puntaje aparece que es necesario tener uno, existe alguna restricción sobre donde colocar ese botón? En línea con eso, puedo no representar el vacío de cada mapa ("-") como esos cuadrados negros que se observan en el enunciado (es que no lo vi en los sprites)?

**Comment by tomastrivino** [comment]
Hint: setStylesheet

**Comment by lsilvabw** [comment]
Buenas, 
en general tiene libertad respecto a como distribuyen el layout del programa. Obviamente siempre y cuando funcione de la manera pedida y sea simple de entender. Respecto a lo segundo que preguntas, no es necesario usar sprites para los cuadrados negros, lo puedes ajustar con las opciones de estilo.
Saludos!

**Comment by ignaverb** [comment]
Gracias!!!
