### ISSUE TITLE
Duda sobre typing.Generator

### ISSUE THREAD

**Issue by nicolaslindl** [IIC2233/Syllabus#389]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Al momento de ejecutar los test de una consulta, me arroja FAIL en los primeros 5 test con el error de "map object at xxxx is not an instance of typing.Generator", sin embargo los test 5,6 y 7 me evalúa OK. Como se si el error es mío o de los test? Supongo que si funciona con los test reales con archivos estará bueno.

**Comment by Jeremiah-PHP6** [comment]
¡Hola! En efecto, debería aceptarte el tipo de dato map como generator. ¿Cuál test es exactamente? Te recomiendo checkear la issue #338, donde se corrigió un test con tu mismo error, tal vez sea el mismo.

Espero tu respuesta, saludos.
