### ISSUE TITLE
Pregunta sobre el robo de soles en la Oleada de Zombies

### ISSUE THREAD

**Issue by Mgseverin** [IIC2233/Syllabus#389]
![image](https://github.com/user-attachments/assets/a8387d0e-5647-4f80-938e-c8a87f3b5306)

Hola! Tengo una duda respecto a cómo se manejan los soles robados durante la Oleada de Zombies. Es importante de qué planta roban los soles los zombies? Mi pregunta surge porque, si los zombies roban soles de las plantas, esos soles deberían descontarse del total recolectado al final del día o el robo se debe aplicar directamente al balance global de soles? Sé que esto último está mencionado en el enunciado, pero en la sección 5.3 Calcular soles dice que, además de imprimir el tipo de planta y su ubicación, se debe mostrar la producción de soles que realizó la planta ese día.

Entonces, ¿la producción de soles de la planta es independiente de los soles robados? Por ejemplo, si se simula un día y el balance inicial es de 100 soles, ocurre una oleada de zombies y roban 5 soles de la Planta1 y 5 soles de la Planta2, el balance global baja a 90 soles.

Luego, al calcular la producción de soles, si la Planta1 produce 6 soles y la Planta2 produce 4 soles, ¿estos soles se suman normalmente (6 + 4) o se debería restar lo robado, es decir, produciría 1 sol la Planta1 y 0 la Planta2? ¿Los soles robados no se deberían considerar en la producción final del día?

**Comment by AndreaVict** [comment]
Holaaa, se realiza lo que mencionas al final, se debe considerar el robo en el cálculo de la producción de soles. Por lo que se debe restar lo robado en la producción de cada planta. Saludos!!
