### ISSUE TITLE
Personaje desplazado

### ISSUE THREAD

**Issue by tomcan127** [IIC2233/syllabus#389]
Al crear mi personaje como el ejemplo de mario en la ayudantia del 2-2018, me pasa que el origen del personaje esta desplazado con respecto al widget en el que esta. Hay algun metodo para ajustar la posicion del QObject?
No hice grandes cambios en el codigo.

**Comment by jeschuwirth** [comment]
Saludos!

En las líneas 75-78 del archivo frontend.py se crea el personaje, la última de estas `self.front_character.move(0, 485)` es la que coloca la esquina superior izquierda del personaje en el pixel. x = 0
y = 485
```
# Se crea el personaje en el frontend.
self.front_character = QLabel(self)
self.front_character.setPixmap(QPixmap('sprite/Super MarioR.png'))
self.front_character.move(0, 485)
```
Ojalá te sirva  :)
