### ISSUE TITLE
Acceso denegado al calendario de evaluaciones

### ISSUE THREAD

**Issue by claramerino** [IIC2233/Syllabus#39]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido
![error calendario](https://github.com/IIC2233/Syllabus/assets/142466295/2c6e6320-f0ae-4f1b-9f88-e9af9de6ad15)

Hola, en Canvas hay un link al calendario de evaluaciones del curso, el que lleva a Google Calendar.
Al entrar me aparece "No tienes acceso al calendario de 917a620677ae040a69d5edf2adb2d0618d2bd917260dbbea0908b688bf559e57@group.calendar.google.com.".
Intenté con mail personal y mail uc, ninguno funciona.
**¿Hay otra forma de ver las fechas de las evaluaciones?**
Muchas gracias

**Comment by cfuenzalidai** [comment]
cps

**Comment by Juampisaez** [comment]
Hola @claramerino @cfuenzalidai !
El día de ayer en la noche se actualizó el acceso al calendario, por favor avisen por acá si pudieron acceder.

Quedo atento :)

**Comment by cfuenzalidai** [comment]
ahora me funcionó gracias!

**Comment by BenjaMedinaPUC** [comment]
Hola! el link de de calendario de actividades del curso no lo enviaron por canvas (sección 4) ¿Alguien que me lo pueda enviar? De antemano gracias

**Comment by Hernan4444** [comment]
Hola @BenjaMedinaPUC 

Prueba con el siguiente enlace

https://calendar.google.com/calendar/u/0?cid=OTE3YTYyMDY3N2FlMDQwYTY5ZDVlZGYyYWRiMmQwNjE4ZDJiZDkxNzI2MGRiYmVhMDkwOGI2ODhiZjU1OWU1N0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t

Saludos
