### ISSUE TITLE
Información a desplegar en "consultas"

### ISSUE THREAD

**Issue by caespinoza5** [IIC2233/Syllabus#39]
En 5.1, en "Consultar información de una moneda", aparece: _Además, debe indicar: cantidad de mercados con órdenes activas, precio actual en cada uno de los mercados abiertos y fecha de la última orden en cada mercado_. ¿La parte "cantidad de mercados con órdenes activas" y la parte de "última orden en cada mercado" se refiere a mercados y órdenes que involucren la moneda consultada?

**Comment by cilopez** [comment]
Sí , se refiere a mercados y órdenes que involucren la moneda consultada

**Comment by MarceloSaldias** [comment]
Solo para corroborar, esto incluye tanto los mercados donde la moneda a consultar es la intercambiada, como los mercados donde se paga con esa moneda? o.o

**Comment by cilopez** [comment]
Sí, ya que la moneda , como dije antes , esta involucrada en ese mercado. :v:
