### ISSUE TITLE
Recomendaciones para VS Code

### ISSUE THREAD

**Issue by diegocostares** [IIC2233/Syllabus#39]
_¡hola! Esto es una lista de extensiones y otras cosas recomendadas para Visual Studio Code, los invito a entregar mas recomendaciones en las respuestas de esta issue._

### Lista de extensiones
- <img src="https://miro.medium.com/max/390/1*o_pHnUIygnRPpKUHNmoi6Q.jpeg"  width=30 height=30 />  **Project Manager:** Sirve para tener carpetas en favoritos y para no perder el tiempo buscando en las carpetas.
- <img src="https://ms-ceintl.gallerycdn.vsassets.io/extensions/ms-ceintl/vscode-language-pack-es/1.60.0/1629245445172/Microsoft.VisualStudio.Services.Icons.Default"  width=30 height=30 /> **Spanish Language Pack:** Te permite tener vscode en español.
- <img src="https://res.cloudinary.com/practicaldev/image/fetch/s--C-yR3FzX--/c_fill,f_auto,fl_progressive,h_320,q_auto,w_320/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/432403/383f0325-7a40-46fe-8469-096d9277f83b.png"  width=30 height=30 />  **Tabnice:** Es una IA que te ayuda a completar código, es super útil, pero no se compara con github copilot (aún no está disponible para el público).
- <img src="https://pbs.twimg.com/media/EKOm2j_WoAAWPaZ.png"  width=30 height=30 /> **Code Runer:** Te permite ejecutar el código de forma mucho más amigable sin escribir en la consola.
- <img src="https://raw.githubusercontent.com/jithurjacob/vscode-nbpreviewer/master/images/jupyter.png"  width=30 height=30 /> **Jupyter Extension:** Te permite integrar jupyter en el editor, es MUY cómodo y te permite desplazarte de forma muy amigable entre carpetas.
- <img src="https://material.io/archive/guidelines/assets/0Bx4BSt6jniD7QU54RENNaGdOR0E/style-logos-product-patterns-elevate-do.png"  width=30 height=30 /> **Python docstrings:** Lo agrego como un extra, ya que no es muy relevante, pero te permite crear descripciones en las funciones, búsquenlo para entender mejor.

### Lista de themes bonitos
- **One Dark Pro:** Es de los temas más instalados y el que personalmente utilizo.
- **Polykai:** Un tema oscuro con buen contraste.

### Otros
- **JetBrains Mono:** Una tipografía muy utilizada y que permite activar 'ligaduras' para formar símbolos y flechas (recomiendo buscar un tutorial para instalarlo)

**Comment by IgnacioEngelberger** [comment]
Creo que "Tabnice" esta mal escrito, me parece que se llama "Tabnine" :smile:
