### ISSUE TITLE
Modelado de clases

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#39]
Hola
Quería saber si somos realmente libres de modelar el problema como queramos o si hay restricciones no dichas como que los soldados asesinos, aprendices, maestros y magos maestros deban ser clases distintas.
Gracias.

**Comment by Arcoirisky** [comment]
Hola!
Eso debes decidir aquello por ti mismo. Pero, siempre ten presente que hay mejores formas para modelar que otras, y esperamos que, aprovechando que tienen tiempo para pensar en cómo modelar, logren llegar a alguna de esas :D ya que pueden haber más de una buena forma.

**Comment by jmwielandt** [comment]
Oka, gracias n.n
