### ISSUE TITLE
PEP8 Rules

### ISSUE THREAD

**Issue by Jprampad** [IIC2233/syllabus#39]
Hola!! En la página de python dice que uno no se puede exceder de los 80 caracteres para satisfacer la regla, pero en Descuentos.md señala que son 100, a cuál le hago caso?

Link: https://www.python.org/dev/peps/pep-0008/#maximum-line-length

**Comment by KnowYourselves** [comment]
Hola @Jprampad!

Debes seguir lo que dice la guía de descuentos. 

Éxito!

**Comment by Jprampad** [comment]
Gracias
