### ISSUE TITLE
Dudas con el operador ' ** ' en Act1

### ISSUE THREAD

**Issue by mVal919** [IIC2233/Syllabus#39]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Buenas tardes.
He estado un par de horas buscando sobre el operador de desempaquetado ' ** ', y creo que estoy entendiendo que es, pero no logro implementarlo al código de la Actividad 1. 

![image](https://github.com/user-attachments/assets/9c9f1c36-5571-43aa-8e6c-35d3ab381f7d)

Para probar, hice un código que me imprima el diccionario 'estudios' entero, y luego que me dijera que era cada elemento.

![image](https://github.com/user-attachments/assets/d743be0e-82ac-4127-8808-c9186860f995)

El resultado es ese. Imprime bien a 'estudios', y el '[]' del final es el que no edité. Pero me dice que ahora los elementos en el diccionario son strings. Entonces, si le agrego un [0] o lo intento llamar con alguna de las llaves del dict 'estudios', no me deja, porque no tiene ese atributo. Y si le agrego un [0] o un .nombre o algo así a cada elemento de 'estudio', tampoco me deja, pues son strings.

Al final, mi duda es si me esta faltando agregarle algo para poder usar cada elemento de 'estudios'?

Eso, muchas gracias.

**Comment by R3Y3X** [comment]
holaaa, efectivamente cuando realizas el for, las n corresponden por defecto a las keys() de el diccionario que son todas str, puedes hacer un for de las values o de ambos, acontinuación te dejo una manera de hacerlo, si tienes dudas de como funciona, no dudes en preguntar, espero te sirva esta información y te dejo unos links donde puedes encontrar esta info:
[https://python-intermedio.readthedocs.io/es/latest/args_and_kwargs.html](url)
imagen del codigo:
![Captura de pantalla 2024-08-15 225001](https://github.com/user-attachments/assets/78a0ced7-863e-43bb-8528-f4549107ec90)
imagen del output:
![Captura de pantalla 2024-08-15 224850](https://github.com/user-attachments/assets/9932a85e-0a94-49a5-b738-7c1d50416d28)
por ultimo esto te retorna un set, acá puedes encontrar información de como trabajar con ellos:
[https://ellibrodepython.com/sets-python](url) 
Éxito en tu actividad⚡
