### ISSUE TITLE
Problema git push

### ISSUE THREAD

**Issue by benjarsanchez** [IIC2233/syllabus#39]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

[Resolví ejercicios de problemas propuestos semana 01 en mi repositorio local, guardé los cambios en jupyter, luego realicé git add, commit y git push, pero al realizar push el programa me arroja:
  
$ git push
remote: Permission to IIC2233/contenidos.git denied to benjarsanchez.
fatal: unable to access 'https://github.com/IIC2233/contenidos.git/': The requested URL returned error: 403
]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by nanglada** [comment]
Hola Benja 😀

La idea de los ejercicios propuestos es que lo resuelvan para que puedan entender de la mejor manera posible los contenidos del curso. Sin embargo, estos son de carácter personal por lo que, una vez realizados, no debes intentar subirlo al repositorio contenidos sino que se debe quedar en tu repo local. 
En tu caso, el repositorio contenidos solo sirve para hacer git pull. Solo los profesores y ayudantes tienen permiso para hacer git push a esta repo, por lo que siempre que lo intentes te tirará un error. 
Ojalá te haya quedado todo claro! Mucha suerte 🤩

**Comment by benjarsanchez** [comment]
Buenísima, muchas gracias <3

**Comment by nanglada** [comment]
De nada! Recuerda no cerrar las isssues tu mismo, sino esperar a que algún ayudante las cierre porque al resto de tus compañeros les puede servir. 🙌
