### ISSUE TITLE
Error en importación dcciudad: ImportError: bad magic number in 'dcciudad': b'\xa7\r\r\n'

### ISSUE THREAD

**Issue by mauriciosalass** [IIC2233/Syllabus#39]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola estaba viendo otra issues que solucionaban un error relacionado a dcciudad y no pude solucionarlo, esto es lo que me muestra la consola al correr ejemplo.py
Vi en otra issues que avisaramos si seguia el error, adjunto foto del error.

![Captura de Pantalla 2024-03-18 a la(s) 14 24 58](https://github.com/IIC2233/Syllabus/assets/162505962/aff67367-cf78-4807-8cd9-97d7457b1ab7)

**Comment by pedrozavalat** [comment]
Hola @mauriciosalass 😄 !,

En los ultimos comentarios de la issue [22 - error al importar y abrir dcciudad.pyc](https://github.com/IIC2233/Syllabus/issues/22#issuecomment-2002041057)  se menciona sobre el caso de obtener el error `bad magic number`. 
>  el error "error in magic number" ocurre siempre que un archivo .pyc se ejecuta con una versión de python distinta a la cuál fue compilada. En este caso, como fue compilada con python 3.11, si alguien usa (por accidente) alguna versión distinta a 3.11, surgirá ese error.

Como menciona el profesor Hernán, el archivo `dcciudad.pyc` fue compilado con Python 3.11. Por lo tanto, si ejecutas tu programa con una version de Python distinta al archivo dcciudad, te indicará aquel error.  

Te recomiendo realizar los pasos que se mencionan en la issue anterior, y en el caso que tengas un nuevo problema, no dudes en preguntar 😉. 

¡Exito en tu tarea! 🚀

**Comment by BenjaminIbanez** [comment]
Hola, estaba leyendo los demas issues y me salio una duda. 

En mi caso estoy usando python 3.12.2 por lo que, si no entendi mal, no voy a poder abrir dcciudad porque solo funciona con python 3.11, pero al mismo tiempo eso significa que no voy a poder usar el import dcciudad? porque intente correr ejemplo.py y me sale el error menciona como titulo de la issue. Continuando con la duda tambien significaria que debo instalar python 3.11 para poder hacer la tarea o no habria problema con python 3.12?

**Comment by pedrozavalat** [comment]
Hola @BenjaminIbanez 😄 !,

Si tienes una version distinta de `3.11`, no podrás importar el archivo `dcciudad.pyc`. El archivo fue compilado con una version de Python 3.11. Por lo tanto, si tienes versiones distintas, como Python `3.12`, vas a tener errores tal como `bad magic number` 😅. 

Te recuerdo que en la [wiki del curso](https://github.com/IIC2233/Syllabus/wiki/4.-Software-Obligatorio#python) se menciona específicamente que la versión de Python que trabajaran en el curso es `3.11.7` . Así que lamentablemente, tendrás que actualizar tu versión de Python para poder trabajar sin errores en el tarea. 

Espero que haya resuelto tu duda. ¡Éxito en tu tarea! 🚀
