### ISSUE TITLE
Consulta sobre la cantidad máxima de carácteres (100) que uno no debe sobrepasar por linea de código.

### ISSUE THREAD

**Issue by TTrincado** [IIC2233/Syllabus#39]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda sobre especificidad de máximos carácteres posibles en una linea de código.
En las reglas se establece que se penalizara con descuento si una linea de código sobrepasa los 100 carácteres incluyendo espacios. ¿Esto incluye los usos de "#", con fines de explicación de flujo de código? Considero que es una buena práctica pero considerando los comentarios que dejo con "#", sobrepasaría los 100 carácteres en algunas lineas. ¿Será considerado como una excepción? Ninguna linea sobrepasaría los 100 carácteres sin tomar en cuenta lo escrito con "#".

**Comment by Maxy15** [comment]
Hola TTrincado! En general se cuentan todos los caracteres. Si quieres colocar comentarios más largos te recomiendo hacerlo con tres comillas (''' '''), de la siguiente manera:

![image](https://user-images.githubusercontent.com/80775916/159586841-c950b93b-efc7-437b-80d5-29530bb4f300.png)

Espero te sirva :eyes:

**Comment by Franbelen** [comment]
Una duda relacionada con esto, ¿como puedo cortar un print? ya que he intentado con:
 print("el mensaje\ 
       sigue el string") 
pero me sale un espacio grande donde corte
