### ISSUE TITLE
leer archivo de usuarios

### ISSUE THREAD

**Issue by lefischer** [IIC2233/Syllabus#39]
hola, cuando intento leer el archivo de los usuarios me aparece
```python
Traceback (most recent call last):
  File "C:\Users\lefis\Desktop\T01\Data\csv.py", line 57, in <module>
    h4, d4 = openCsv("usuarios")
  File "C:\Users\lefis\Desktop\T01\Data\csv.py", line 36, in openCsv
    line = data.readline()
  File "C:\Users\lefis\AppData\Local\Programs\Python\Python35\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 802: character maps to <undefined>
```
es el único archivo con el que tengo problemas

**Comment by akaminetzkyp** [comment]
Quizás es por las "ñ" y los tildes!

**Comment by lefischer** [comment]
@akaminetzkyp  

gracias, le puse encoding utf-8 y me funciona, 
supongo que todos los archivos estan en utf-8, o no?

**Comment by benjamimo1** [comment]
Usaste el comando open y como argumento utf-8? A mi me tira error

**Comment by Nicolasvegam** [comment]
Tengo la misma duda! 🙁

**Comment by KnowYourselves** [comment]
Cuando se utiliza el comando `open()` se puede usar el argumento `encode = "utf8"` para evitar que esta clase de problemas ocurra

**Comment by jorgeriesco** [comment]
No entiendo como abrir los archivos para poder leerlos. ¿Como uso los del utf8? ¿o que otra manera existe?

**Comment by KnowYourselves** [comment]
puedes utilizar el comando `open("nombre_archivo","r",encode = "utf8")`

**Comment by jorgeriesco** [comment]
me tira error, no es valido usar encode en esa funcion

**Comment by rpalmaotero** [comment]
@KnowYourselves @jorgeriesco una corrección chica: el parámetro se llama `encoding`, no `encode`. Entonces: `open(..., encoding="utf8")`.

**Comment by jorgeriesco** [comment]
ahi si gracias
