### ISSUE TITLE
Duda escritura print(f"1: {data}")

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#39]
- Foto del error:
![Captura de Pantalla 2020-08-17 a la(s) 21 29 23](https://user-images.githubusercontent.com/69765490/90459931-bf912000-e0d0-11ea-9ff3-cdced6dbbf45.png)

- Descripción del problema:
Estimado:
Quería saber porque se escribe así eso, con una f adelante y la variable data entre{}
Gracias

**Comment by igbasly** [comment]
Hola @diego-ayala-2000 :v:

Ese formato de *strings* más conocido como *f-string* es por así decirlo, una actualización del método `.format` de la clase *String*, el cual permite insertar variables dentro de una cadena de texto según se indique. Este tema se trata en la issue #19, donde además dejan un anexo para ver más información del tema.

Saludos :smile:

**Comment by dchahuan** [comment]
Lo que pasa es que desde python 3.6 existe que una forma escribir strings que se llama f string, estas consiste en ponerle f al principio de la string y cada vez que uno pone las bracketas toma el valor de la variable como parte de la string. Mas info en https://realpython.com/python-f-strings/
