### ISSUE TITLE
Uso de Pycharm

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#39]
Hola. Recomiendan el uso de Pycharm como entorno para trabajar en las tareas? saludos.

**Comment by KnowYourselves** [comment]
Hola @tedroppelmann!

En general **no recomendamos _Pycharm_** para este curso. Algunas razones son las siguientes:

1. Es una IDE bastante poderosa y por lo cual también muy compleja, en este curso no sería utilizada en todo su potencial y se podrían caer en errores innecesarios.
2. Es una IDE **especifica para _Python_**, por lo cual no sirve para otro lenguajes. El problema con esto es que en futuros ramos donde programes en otros lenguajes **no te será útil**.
3. Es una IDE **que consume muchos recursos**, por lo cual si tu computador es de pocos recursos, no es recomendable.
En resumen, para este curso y también para otros, es mejor que aprendas y utilices otras IDE, como las recomendadas en la wiki.

Quedo atento a cualquier duda!
