### ISSUE TITLE
Guardar

### ISSUE THREAD

**Issue by Josefinafp** [IIC2233/Syllabus#39]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Hola! No entiendo muy bien la forma de almacenar la información de cada partida. Es válido un archivo que contenga los estados actuales del tablero (un print de este mismo después de cada operación realizada) ? o debe haber explícitamente números con las coordenadas de la casilla descubierta?
Saludos!!] 

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by vicentethomas** [comment]
Hola! Según el enunciado, la forma de almacenar la información queda completamente a tu criterio mientras cumpla las condiciones: 
- Archivo ubicado dentro de carpeta partidas
- Nombre del archivo debe ser `usuario.txt`
- Queda registro de las posiciones de bestias y posiciones descubiertas con sus números.

Así que mientras cumpla esto, las formas que mencionas son válidas 👍 . Eso sí, la forma de guardar el archivo debe tener cohesión con la forma de cargar el archivo, para que al momento de cargar se sepa el formato en el que viene guardada la partida.
