### ISSUE TITLE
Ataque y Defensa 

### ISSUE THREAD

**Issue by angelaparriana** [IIC2233/syllabus#39]
En la fórmula de  poder de ataque de una civilización sale Ctec, esa corresponde a la de la civilización que está haciendo el ataque o a la que están atacando? 

                                                     PA =FS +Ctec

**Comment by hbkim94** [comment]
Hola,

El `Ctec` corresponde a la cantidad de puntos de tecnología de la civilización atacante (el DCC).

Saludos!
