### ISSUE TITLE
Uso de for para cargar archivos

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2233/Syllabus#390]
¿Es legal usar for para tomar los datos de los archivos, o debemos hacerlo de manera funcional?

**Comment by rihanuch** [comment]
¡Hola @jpmoraga1 !

Se puede usar siempre y cuando no vaya en contra de lo que se ha dicho en otras issues o salga en el enunciado

¡Saludos y éxito! 🍀

**Comment by jerrymendoza** [comment]
Misma duda, ejemplo:

for línea in texto:
    yield línea 

¿?
