### ISSUE TITLE
Tengo problemas para subir la actividad bonus al repositorio privado

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#390]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola,

Ya hice una carpeta AB en mi repositorio privado. Pero al hacerla, me pedía que hiciera un file, a este file le puse nombre 'main.py'.
Hice un git pull en mi computador. 
Copié lo que llevo de la actividad en esta carpeta. Pero como en la actividad hay un main.py, puse que se reemplazara.
Después intenté hacer un git push, pero me sale que no se puede porque origin/main divergen
Después edité el archivo main.py a algo.txt para ver si funcionaba y me sigue dando el mismo mensaje.

Esto es lo que me dice:
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

Por favor ayuda para alcanzar a subir la actividad!! Necesito estas décimas extras

**Comment by igbasly** [comment]
Hoola @Fernanda1232123 ✌️ 

Ocurre que hubieron conflictos al momento de intentar actualizar tu repositorio. Quizá porque en algún momento subiste cambios directamente desde internet o porque no actualizaste el repositorio antes de hacer push. Lo que tienes es un error de conflictos, los cuales se pueden arreglar pero es algo complicado de explicar de forma general.

Te recomendaría para temas de la actividad, copiar los archivos de la actividad en algún otro lado de tu computador y volver a clonar tu repositorio, luego cambiar los archivos por los copiados e intentar subirlo.

Saludos, quedo atento a como te va 😉
