### ISSUE TITLE
Varias ventanas en una pyqt5 

### ISSUE THREAD

**Issue by JoseIgnacioGajardoRojas** [IIC2233/syllabus#390]
¿Es posible poner varias ventanas en una sola?, si es asi ¿Bastaria solo con instanciar la clase y luego agregarlas a un Layout?

**Comment by jmwielandt** [comment]
Hola!

Asumo que cuando te refieres a "ventanas" hablas de QWidgets. En efecto, se pueden poner tantos como quieras dentro de un mismo QWidget. Para esto puedes utilizar algún QLayout como dices o posicionarlo dentro del QWidget "padre" seteando este como "padre" para los QWidgets hijos.

Recuerda que QLabels, QPushButtons, QLineEdit y muchos otros elementos que se posicionan dentro de una ventana son al final del día QWidgets ya que heredan de esta clase. (En la documentación de Qt5 en C++ está la información de quién hereda de quién y todo eso).

Saludos!

**Comment by JoseIgnacioGajardoRojas** [comment]
Hola!
Lo hice así y me tira este error QImage::scaled: Image is a null image
