### ISSUE TITLE
Error en test_1

### ISSUE THREAD

**Issue by IchottMano** [IIC2233/Syllabus#390]
En la carpeta test_1, en los resultados de la consulta numero 4 que es
["pariente_de", 2, "Jesús De Nazaret"]
Dentro de Resultados.txt se nos muestra que no es aceptable, lo que significa que no arroja resultados.
Sin embargo, la siguiente consulta es 
["pariente_de", 2, "Florencia Barrios"]
y el primer resultado de esa consulta es "Jesús De Nazaret", por lo que debe haber un error.
Muchas gracias.

**Comment by Hernan4444** [comment]
@IchottMano precisamente había un error 🙀 , en Genoma había un `6Jesús` y eso ocasionó un ligero error en leer el dato, acabo de corregirlo. Cualquier otra cosa por favor indicalo lo antes posible 👍  Estaré atento a esta issue.

Muchas gracias por darte cuenta 😄 
Saludos ✌️

**Comment by leolivares** [comment]
Con respecto a este tema. Revisando los resultados que se deberían obtener, me parece que hay un error en cuanto a la manera en que se calcularon los fenotipos con ese código. (Mas específicamente los fenotipos de la forma continua)
Por ejemplo, en la consulta 12, se pide el valor del color de piel. La relación obtenida entre clara y oscura es 1:1, es decir 50% (Al menos es lo que me da). Entonces, el color de piel debería ser Blanco (No Moreno). 
Creo que este detalle produjo ciertos errores en otros resultados.
Dejo esto para saber si alguien mas concuerda, y para corregir los resultados en caso de que sea necesario.

**Comment by IchottMano** [comment]
@leolivares Justo iba a postear que tengo el mismo problema, me dan los mismos resultados que a ti

**Comment by Hernan4444** [comment]
@leolivares @IchottMano justo iba a avisar sobre eso 😅 (okno :c) gracias por avisar, tal como dices, el código de continuas no consideraba el caso borde. Es posible que suban sus respuestas a sus repositorios para comprobar si es que tenemos otro error para corregirlo lo antes posible?

Saludos ✌️

**Comment by leolivares** [comment]
@Hernan4444 Subí a mi repositorio el archivo "mis_respuestas.txt" (En la carpeta de la Tarea 3). Esos son los resultados que estoy obteniendo.

**Comment by IchottMano** [comment]
@Hernan4444 Igualmente, acabo de subir "Mis_Resultados.txt" en mi carpeta de la tarea 3, cabe decir que aún no realizo la parte de gemelo genético.

**Comment by Hernan4444** [comment]
Acabo de subir los resultados, coincidio bien con uno de ustedes, con el otro faltaban personas y creo que es porque están aproximando. Solo como dato:
1. La solución no usa ningún `round` por ahora
1. Si algo debe ser el 20%, se compara con 0.2, no multiplicamos por 100 y comparamos por con 20.

De todos modos, gracias a este tendremos en cuenta tales errores al momento de comparar las consultas 👍. Si les faltan o sobran algunas personas, no se preocupen, lo tendremos en cuenta c:

**Comment by leolivares** [comment]
@Hernan4444 Muchas Gracias!

**Comment by IchottMano** [comment]
@Hernan4444 En el caso de la cuarta consulta pude ver que la razón por la cual no se consideraban los que faltan es debido a la altura, sin embargo no logro encontrar el error en el cálculo de esta.
Podrían por favor revisar estas alturas a modo de ver si se trata de un problema mío o del código con el que se generan las respuestas?
Muchas gracias. 👽

**Comment by leolivares** [comment]
@IchottMano A mi me pasa igual en la misma consulta.

**Comment by Hernan4444** [comment]
Acabo de subir un nuevo archivo en la carpeta *test_1* donde hay una descripción de cada persona. Con lo anterior debería ser una buena ayuda para que cualquier pueda verificar si llega a los mismos fenotipos. 

Si algún número no les calza, comentenlo aquí.

**Comment by IchottMano** [comment]
Mientras que Jesús de Nazareth tiene una altura de 1.4 m,
Gabriel Lyon tiene una altura de 1.925 y Germán Contreras de 2.0m, por lo que no califican como parientes en segundo grado de Jesús
Además a primera vista obtengo que Hernán Valdivieso tiene una altura de 2.1 m

**Comment by Hernan4444** [comment]
@IchottMano no tendrás al revez el tema de las alturas??? Revisa Si una persona con puros tag `ATC` tiene altura 1,4 o 2.1 (por enunciado debería ser 1.4m)
Pero justamente la comparación de altura se estaba haciendo mal >-< (actualice los archivos), de agradecimiento te mando esta imagen:
![123](https://user-images.githubusercontent.com/15641721/31050075-053a68e8-a617-11e7-86b0-a235b2573fbd.jpg)

**Comment by IchottMano** [comment]
@Hernan4444 el problema es que esta "Hernan Valdivieso" que mide 1.4 m y "Hernán Valdivieso" que mide 2.1m asi que eso fue mi culpa jajaja

**Comment by pnheinsohn** [comment]
entonces no se aproximan los datos? ajajajaja (round)

**Comment by Hernan4444** [comment]
@pnheinsohn nop 👍
Sino habría caos si es que algunos aproximan y otros no al momento de comparar consultas. Ejemplificación de caos:
![bob_esponja_cual_es_mi_nombre](https://user-images.githubusercontent.com/15641721/31056232-b90ed1e6-a6a4-11e7-8ec2-8584b5dd2c6f.gif)

**Comment by BeaGaete** [comment]
@Hernan4444 en test 1 tengo todo correcto excepto las consultas de gemelo_genetico. Supongo que para un mismo sujeto cambian los genomas por eso cambió el resultado de la consulta gemelo_genetico para Hernan Valdivieso. Sin embargo para los archivos originales tengo esta consulta correcta, es decir gemelo_genetico('Hernan Valdivieso') = Marcelo Lagos. Par el test_1 esta consulta me da Frodo Baggins y para gemelo_genetico de 'Nebil Kawas' me da Nicolás Balboltín. Mi duda es si una persona es mas gemela que otra porque hay mas características donde comparten genes o bien en total se comparten más genes. Por ejemplo si alguien en las 9 características comparte genes y tiene en total 100 genes compartidos es más gemelo que otra que solo tiene 5 caracteristicas donde comparte genes pero tiene 200 genes en común??

**Comment by Hernan4444** [comment]
El que tiene 200 genes en común es más gemelo. Aquí contamos en número de genes en común (sin importar la característica). Puede ser que lo implementaste de la otra forma y por eso da resultados distintos

**Comment by felipecr00** [comment]
En la descripción de Hernan Valdivieso no obtengo los mismos resultados que los del test :/, los demás los tengo iguales.
Nose si ya lo respondieron o había algo que considerar.
Mi resultado es:
fenotype(persona='Hernán Valdivieso', altura=2.1, ojos='Azules', pelo='Negro', piel='Albino', nariz='Aguileña', pies=34.0, vello=[None, 'Axila', 'Espalda'], guata='Atleta', vision=['Daltonismo', None])

Saludos

**Comment by behrmann97** [comment]
Hola, en el test_1 me sale todo bien menos la consulta 4 que me faltan 2 personsa (sterling archer y luis leiva), quienes me aparecen como parientes de grado 1 de Jesús y no de grado 2. Esto se debe a que los genes del ojo de Jesús me dieron ['AAT', 'CCT', 'CCT', 'AAT', 'CAG', 'CAG', 'CAG', 'AAT', 'CAG'], es decir, sus ojos son cafés, y no azules como pasa en los genomas del enunciado. ¿Es esto un error mío al leer los ojos  o realmente son cafés segun sus genes?

**Comment by Jiparavich** [comment]
@Hernan4444 Hola! , puede pasar que haya cierta incongruencia con lo que nos subieron al test1? 
Por ejemplo en la consulta 4 sucede lo siguiente, según lo que leo SterlingArcher no debería aparecer en Resultados.txt ya que en las mismas "Descripciones.txt" que están en test_1 se obtiene que son
 de grado 1.
![image](https://user-images.githubusercontent.com/30678179/31319151-9c1de64a-ac34-11e7-995f-7e12557915a4.png)
Muchas Gracias!

**Comment by Hernan4444** [comment]
@Jiparavich en el enunciado nunca se dice los grados son excluyentes, alguien grado 1 puede ser grado 2 mientras cumpla las características que definimos para cada grado

Saludos ✌️

**Comment by Jiparavich** [comment]
Perfect👌🏻👌🏻
Gracias!
