### ISSUE TITLE
Cargar Fuente 

### ISSUE THREAD

**Issue by jerrymendoza** [IIC2233/syllabus#390]
Hola, Estoy intentando cargar una nueva fuente
según documentación, debería utilizar 
`id = QFontDatabase.addApplicationFont(path)`

pero siempre el id me da -1 (significa que no cargo)

alguien sabra que pasa?(el path es igual a como cargo imágenes y todo lo demás)

**Comment by hbkim94** [comment]
Hola @jerrymendoza ,

Solo para estar segura de que no te has saltado algún paso, ¿has revisado esta issue en [stackoverflow](https://stackoverflow.com/questions/41282158/pyqt4-how-to-import-and-change-custom-font-for-painted-text)? Si bien es para PyQt4, me parece que su uso es continuado en la versión 5.

Quedo atenta a cómo te va!

**Comment by jerrymendoza** [comment]
Hola @hbkim94,
Gracias..
exactamente lo que estoy haciendo, en el caso que me envías tu, da -1 en la segunda linea (font_id)

Al parecer depende del sistema operativo si deja o no cargar la fuente.
Puede poner en el readme que se instale la fuente (que dejare en el git) para revisar?
Se que no es algo relevante.. pero se ve mejor  jaja

**Comment by hbkim94** [comment]
@jerrymendoza ,

Hemos discutido tu situación, y preferiríamos que simplemente no incluyas esa parte de código en tu programa dado que necesitaría que instalemos algo ageno a lo que se requiere para la revisión de la tarea, lo que no puede ser. Si bien podría verse mejor, y entiendo que quieras que sea así, es mejor no arriesgarse a que tu programa se vea afectado por la presencia/ausencia de ello.

Espero que esto no te desaliente porque es genial que busques formas de mejorar la calidad visual de tu programa, pero para esta ocasión es mejor que todo funcione bien y sin problemas para el ayudante corrector. Saludos y mucho ánimo!
