### ISSUE TITLE
Uso de properties

### ISSUE THREAD

**Issue by Icarus328** [IIC2233/syllabus#390]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, respecto al uso de properties en la tarea, el enunciado dice que es necesario, pero me gustaría saber si debo implementar tanto getters como setters o si puedo implementar solo getters. También me gustaría saber si se va a evaluar el uso de properties o solo su existencia, ya que me cuesta ver un punto en mi código donde usar properties ahorraría líneas o lo haría más legible.

También me dí cuenta de que las properties no están mencionadas en la distribución de puntaje, eso significa que no son necesarias?

**Comment by Emiliax16** [comment]
Hola @Icarus328 , tal como el enunciado dice, deben usar properties en algún momento de su tarea. No es necesario que las implementes en todos los métodos, pero si que demuetres un buen manejo de ese contenido cuando corresponda. 
Se me ocurren dos buenas oportunidades donde sería útil el manejo de properties en el programa, te recomiendo mirar los contenidos de properties (semana 3) para que veas dónde y cómo aplicarlas. 

En la distribución de puntaje no aparece textual, pero se evalúa dentro de la _Definición de clases, atributos y métodos_, donde componen la modelación de las entidades. Insisto, no es obligatorio que cada entidad o cada método contenga properties, ocúpalas sólo cuando estimes conveniente.

Quedo atenta por si te quedan más dudas!

**Comment by Icarus328** [comment]
Hola, gracias, me quedó una duda, el uso de las properties en si demuestra un buen manejo de ese contenido? por ejemplo, haciendo que para acceder al valor de una clase sea necesario usar un getter, aún si el hecho de hacer ese valor "privado" no le añade nada al programa?

**Comment by Emiliax16** [comment]
Si bien puede que definir valores privados no le añada nada al programa en sí, resulta una buena modelación tener valores privados que, en caso de ser un programa real, sería completamente necesario que no se pudiera acceder libremente desde afuera.
