### ISSUE TITLE
Duda columnas y algunos comandos

### ISSUE THREAD

**Issue by cho19** [IIC2233/Syllabus#390]
Hola!

¿RQL debe soportar comandos que operan o filtran para strings? 
Por ejemplo,`["operar", ["a", "b"] "+", "c"]`, ¿resulta en `["ac", "bc"]` o un error? 

¡Saludos y gracias!
EDIT: no parece muy lógico que lo soporte pues, por ejemplo, el "-" no esta definido para los strings y no se si tenga sentido que un comando no soporte todas las operaciones para una columna de un tipo no numérica.

**Comment by iqacevedo** [comment]
Hola !
Como las columnas están definidas como conjunto de datos numéricos, no habrán consultas que hagan lo que tú pediste.
Saludos !

**Comment by cho19** [comment]
@iqacevedo Vale! Gracias
