### ISSUE TITLE
Archivo resultados.txt

### ISSUE THREAD

**Issue by barbarafcp** [IIC2233/syllabus#390]
Hola! El archivo resultados.txt se debe subir al repositorio o tenemos que crearlo desde dentro de otro archivo necesariamente?

**Comment by vsantelicest** [comment]
Hola! No entiendo a que te refieres con "crearlo dentro de otro archvio", pero con respecto a lo primero, no es necesario subir un archivo de resultados.txt al repositorio porque tu programa debe ser capaz de crear un "resultados.txt" y actualizarlo a medida que avanzan las competencias. Espero haya quedado claro

**Comment by barbarafcp** [comment]
Sii! me resolviste la duda jajajaj, gracias!
