### ISSUE TITLE
Salud actual, nivel de hambre y días sin comer iniciales de crear criatura

### ISSUE THREAD

**Issue by FelipeSrojas96** [IIC2233/syllabus#391]
Hola, al crear una criatura debo asumir que su salud actual es la misma que la total, y que lleva 0 dias hambriento ?

**Comment by fdoflorenzano** [comment]
Hola @FelipeSrojas96,
Sí, en enunciado dice que la salud comienza como los puntos de salud total, y como es una nueva DCCriatura, no puede tener llevar días sin comer aún.
Saludos.

**Comment by FelipeSrojas96** [comment]
Gracias, ah y tambien otra cosa, la criatura comienza como hambrienta o satisfecha?

**Comment by fdoflorenzano** [comment]
> Gracias, ah y tambien otra cosa, la criatura comienza como hambrienta o satisfecha?

Si seguimos la misma lógica, puedes considerar que comienza satisfecha.

**Comment by Camila-sty** [comment]
Hola. Los días que una criatura llevan sin comer, es cuando se optar por *pasar al día siguiente*?

**Comment by Camila-sty** [comment]
me refiero a que en esa acción, aumentan los días sin comer?. Y esto aplica para la criatura que está satisfecha y hambrienta?

**Comment by Camila-sty** [comment]
Publiqué mal esta issue. 
Ya encontré la respuesta,gracias!
