### ISSUE TITLE
hacer que el personaje no pueda pasar por encima de las rocas

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#391]
He estado tratando de hacer que mi personaje no pueda pasar por encima de las rocas pero tras intentar con distintos códigos y buscando en internet no he podido.
Mi mapa consiste en un QGridLayout donde cada espacio del grid es una sprite del terreno del mapa y encima de esta grid puse un QLabel del mismo tamaño por la cual se mueve el personaje.
Mi idea era guardar en una tupla las coordenadas en donde se van poniendo las rocas en el Grid para así no permitir al personaje pasar por estas coordenadas, pero buscando en internet me encontré con que no se puede obtener las coordenadas antes de ejecutar el código (decía en stackoverflow, "The geometry is updated only when the widget is displayed").

Existe alguna manera de prevenir que el personaje pase por las rocas según como tengo mi código o, debido a la manera en que lo estoy haciendo, es muy complicado y por tanto debería cambiar la estructura de mi código?

**Comment by jmwielandt** [comment]
Hola!

Tal como dices, deberías cambiar la estructura de tu código, pero es porque las colisiones se deberían calcular en el backend sin utilizar información del frontend. Piensa en cómo disociar la "data" del mapa y los elementos que allí se ven con el "aspecto" de ese mapa y contenido (tu QGridLayout). 

Saludos!

PD: puedes seguir preguntando acerca de cómo modelar el programa (mientras que no sea respecto a la separación frontend-backend), ya que no es parte de lo que se busca evaluar y es cierto que una mala modelación les puede hacer la vida imposible. Ánimo!

**Comment by raimundoloeser** [comment]
Mi duda es que tan estricta tiene que ser la colisión?, ya que la persona son imagenes con un tamaño definido, que tienen una coordenada definida y si quieremos intersectar las posiciones de las rocas con las de la persona seria un punto demaciado especifico.

**Comment by jmwielandt** [comment]
Hola!

En realidad lo más fácil que puedes hacer es usar `QRect` en tu backend para determinar las colisiones. Se recomendaron para la T2 del semestre pasado, puedes revisar las issues al respecto si lo necesitas.

Sobre "que tan estricta tiene que ser la colisión", imagina que tu personaje está caminando hacia la derecha con una velocidad de 50 píxeles por cada actualización pero en un momento hay un obstáculo a menos de 50 píxeles, digamos, 40 píxeles. En ese caso tu personaje debería moverse 40 píxeles en lugar de 50.

Imagina que nuestro personaje verde se mueve 129 px. por cada actualización, entonces quedaría en la posición del personaje rojo después de moverse.


#### Sin colisiones

![image](https://user-images.githubusercontent.com/37153467/66243908-a069e980-e6dc-11e9-946f-1302967f5632.png)


Debes hacer que se mueva solo 100 px., quedando en la posición del personaje azul.

#### Con colisiones
![image](https://user-images.githubusercontent.com/37153467/66243936-b8da0400-e6dc-11e9-8ad2-43f336148b39.png)


De todas formas, recuerda que las colisiones son con las casillas del obstáculo, no con el obstáculo en sí (hay una forma de no hacer caso al fondo transparente de las imágenes pero no sabemos más del tema).

Saludos!

<hr/>

PD: también se pueden implementar las colisiones sin usar QRect peropuede ser un poco más complicado, te dejo un par de links de interés ([1](https://love2d.org/wiki/Tutorial:Gridlocked_Player), [2](https://love2d.org/wiki/Tutorial:Callback_Functions) (mira el `love.update`)).

**Comment by raimundoloeser** [comment]
Yaya gracias! mi duda iba mas a lo ultimo, que la colision es con las casillas, ya que ahora lo tengo implementado de manera que la colision es mas menos la parte baja de mi jugador (es decir, el puede pasar caminando por debajo de una roca y se va a ver como si la cabeza este un poco sobre la piedra, ya que los pies mandan) 
Lo tengo que cambiar a que la colision sea completa? o lo puedo dejar asi y ponerlo en el readme

**Comment by jmwielandt** [comment]
Hola!

Lo puedes dejar así, ponlo en tu readme y agrega un link a esta issue, para evitar problemas durante la corrección 😉.

Saludos.
