### ISSUE TITLE
Uso de min_soles y max_soles

### ISSUE THREAD

**Issue by dbarraza01** [IIC2233/Syllabus#391]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Los parametros min_soles y max_soles
no entiendo si son límites para la cantidad de soles que puede tener el usuario o soles que se le otorgan de manera aleatoria entre esos dos parámetros 
Gracias

**Comment by augustayanez** [comment]
Al final de la simulación de cada día debes calcular los soles generados por el jardín durante el día. Para esto debes tomar en cuenta los eventos, la producción de cada planta y los **soles que se obtienen del cielo**. Estos últimos serán un valor al azar, que debe estar en un rango entre MIN_SOLES y MAX_SOLES (ambos parámetros que debes crear tu).
