### ISSUE TITLE
Unittesting de generadores

### ISSUE THREAD

**Issue by malopez16** [IIC2233/Syllabus#391]
Algún requisito en especial?

**Comment by indonoso** [comment]
No se entiende tu pregunta. Explica más

**Comment by malopez16** [comment]
Se va a evaluar el testing de generadores, pero el testing de generadores no aparece en el material del curso. Aún así, asumo que hay estándares mínimos que debemos cumplir para poder obtener el puntaje. ¿Alguna fuente o guía para cumplir con dichos estándares? ¿Se puede usar for - while? ¿Cómo podemos ver que estén funcionando bien (además de haciendo copy paste a los datos directamente)? ¿Deberíamos hacerlo así (con copy paste)?

**Comment by andresfdezc** [comment]
![screen shot 2017-05-03 at 8 31 29 pm](https://cloud.githubusercontent.com/assets/11430184/25685671/858d308c-303f-11e7-9174-675b0b667b3f.png)

Se te pide testear funciones. Creo que estás confundiendo los generadores con funciones generadoras que pueden retornarlos. No son lo mismo.

La forma más simple de testear es, dado un input, sacar "a mano" el output que debería retornar y repetir con muchos casos (distintos en esencia entre ellos). Puedes hacer lo mismo con una función generadora.

Sobre si se puede usar for - while -> #400
