### ISSUE TITLE
Programatones?? Tareas

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#391]
Hola! quería saber si van a existir instancias, como en los semestres presenciales, en donde se hacían las "programatones" y vamos a poder hacerles consultas a los ayudantes para la tarea.
Saludos y linda tarde

**Comment by gatochico** [comment]
Hola @sa-Appel !

A pesar de estar en formato online, no queremos perder estas instancias así que **sí habrán programatones en el semestre** 🎉 .

Para esta tarea eso sí, no tenemos agendada una :( (en las siguientes tareas sí 👀 ). Algunas instancias de ayuda para esta tarea son las **_issues_ del foro,** y la **sala de ayuda** de mañana en horario de ayudantía. Por último, recordar que siempre puedes contactarte con Tomás en `bienestar.iic2233@ing.puc.cl`.

Saludos y nos vemos en las (eventuales) programatones!

**Comment by sa-Appel** [comment]
bacan!
nos vemos en la sala de ayuda. Saludos
