### ISSUE TITLE
Error:{"result":"error","message":"Formato de request incorrecto, recuerda seguir el formato indicado en el enunciado."}

### ISSUE THREAD

**Issue by josetomasacuna** [IIC2233/Syllabus#391]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Estoy recibiendo el error {"result":"error","message":"Formato de request incorrecto, recuerda seguir el formato indicado en el enunciado."}. La verdad es que no se que en el formato está mal, lo he revidaso muchas veces, sin embargo no quiere cambiar el error. Subí mi código al repositorio personal por si me quieren ayudar

**Comment by igbasly** [comment]
Hoola @josetomasacuna :v:

Creo que la issue #372 te puede ayudar.

Saludos 😉
