### ISSUE TITLE
Consulta Votos Válidos

### ISSUE THREAD

**Issue by faresdababneh** [IIC2233/Syllabus#391]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, con respecto a la issue #360, sigo sin poder darle solución, lo que me hace cuestionarme si hay algo que no estoy haciendo bien o si la data presenta errores. Gracias

**Comment by leonidasmontes** [comment]
Hola!

Me pasa lo mismo, me da para los últimos 3 un número levemente menor. 
Me imagino que es por un tema de aproximación con el float pero no he logrado achuntarle.

**Comment by lil-kuo** [comment]
Me pasa igual, inclusive usando round, no funcionan

**Comment by jfpantoja** [comment]
Hola @faresdababneh, @leonidasmontes, @lil-kuo!!
Se revisó este test y efectivamente habrá un error en el resultado esperado debido a que se encontraron animales donde su edad no calza con la fecha de nacimiento, lo que al llevar a cabo el ejercicio utilizando la fecha de nacimiento (método utilizado por el test) para calcular la edad, se tendrá un resultado distinto que al sacar la edad directamente desde animales.

Entonces, al hacer la consulta votos válidos ocupando el atributo edad directamente de la instancia de animal da un resultado distinto que hacer la consulta votos válidos calculando la edad según el atributo de fecha de nacimiento de la instancia de animal.

El test actualmente considera como correcta la respuesta donde se utiliza la fecha de nacimiento del animal para calcular la edad y por eso difieren los últimos 3 test, por lo que al hacer la consulta mediante la fecha de nacimiento con datetime les debería dar el resultado esperado por el test actual.

De igual manera, se habló con el equipo docente y se actualizará el test para aceptar ambos casos, el caso donde se toma la edad directamente y el caso donde se calcula la edad por la fecha de nacimiento.

**Comment by leonidasmontes** [comment]
Muchas gracias @jfpantoja ! 
Quedo atento.

**Comment by mpiavf** [comment]
Hola, actualizamos los tests con lo detectado en esta issue y otras más. Pueden revisar la issue creada en #444 para más detalle. 
Saludos!
