### ISSUE TITLE
Diseño backend

### ISSUE THREAD

**Issue by constanzarojasch** [IIC2233/Syllabus#391]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Ando media perdida con el diseño del backend, ya que por ejemplo la lógica de las colisiones y etc se que hay que ponerlas en el backend, pero no me queda claro si algunas lógicas que si tienen que ver con la interaccion del usuario van en el frontend o en el backend. Por ejemplo, cuando se debe ver si el click en modo constructor fue hecho en una pared o no (que tiene que ver con verificar el numero esta dentro de ciertos parámetros) y también las properties setters del movimiento de luigi. Estas ultimas dos funciones no se si es necesario ponerlas en el backend, ya que es mas cómodo y menos acoplado ponerlas en el frontend. Gracias!

**Comment by Hernan4444** [comment]
Hola Contanza,

En generar lo que queremos evitar es solo que el _frontend_ llame a código del _backend_ y viceversa, (que nunca el _frontend_ haga `import backend`). Pero no hay problema en hacer un poco más inteligente el _frontend_, por ejemplo:
1. Que cuando se haga click en la pantalla, una opción es enviar la posición del click y que el _backend_ determine qué elemento es.
2. O bien que el frontend haga esa pega y solo le diga al _backend_: "hicieron click en una pared", y el _backend_ guarda dicha información para utilizar despues.
3. Incluso, tampoco habría problema si el _frontend_ se encarga de guardar el elemento que hiciste click y la posición en la grllla, y luego solo manda la información de: "quieren poner una pared en la posición X, Y", y ahí el _backend_ decide si esa jugada es válida o no para ponerla en la grilla.

Lo que nos importa es que no se hagan `imports` de un lado a otro, pero "quien decide" qué hacer, no hay drama. En clases yo les comenté que una opción era hacer _"frontend for dummies"_, que es un _frontend_ que no piensa nada, que manda toda información al _backend_ y solo muestra lo que el _backend_ decide, pero no es la única opción. Si recordamos la experiencia 4, todo el movimiento del mouse lo veía el _frontend_, porque al _backend_ no le interesa eso, solo se involucraba (con señales) cuando hacías  click que ahí si era necesario determinar si se destruyó o no un meteorito.

Respecto al `setter` del movimiento del Luigi, pasará algo similar: una opción es que el _backend_ solo indica que Luigi se mueve de X,Y a X+1,Y. Y es el _frontend_ quien hace ese movimiento de forma paulatina y cambiando el _sprite_, o bien, tambien puede ser que el _backend_ haga tooodo eso, que mover desde X,Y a X+1,Y implica hacer toda la lógica de ir moviendo de a poco y mientras se mueve, indicarle al _frontend_ que cambie el sprite utilizado.

Como ves, para ambas funciones consultadas, es totalmente válido dejarlo en _frontend_ o en _backend_, lo único que queremos evitar es que frontend llame directamente a funciones del backend y viceversa, sino que se comunen con señales,pero  "¿qué comunicar?" queda ya  a su criterio de qué es lo más sencillo para ustedes.

Espero que esta respuesta ye oriente mejor, sino no dudes en preguntar por aquí, estaré atento.
Saludosヾ(＾-＾)ノ
