### ISSUE TITLE
Programa poco eficiente

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#391]
Hola,

Qué pasa si mi programa no corre muy bien en computadores de bajo rendimiento? En el computador que estoy programando, me corre sin mayores problemas, sin embargo al probarlo en un computador de bajo rendimiento, no funciona del todo bien (los enemigos no desaparecen instantáneamente al morir, o las monedas se empiezan a quedar pegadas en el mapa), a lo que asumo es por la gran cantidad de threads que se generan, ya que cuando empiezan a morir los threads, empieza a correr con normalidad.

Lo segundo, si para un correcto funcionamiento no deben mover la ventana o minimizarla, puedo indicar esto en el Readme?  

Espero me puedan ayudar

**Comment by gatochico** [comment]
Hola! 
Corrí la ultima versión de tu código y para tu tranquilidad no hubieron grandes problemas con que se quedara pegado durante la ronda, incluso con más de 3 torres y el personaje moviendose (Corre una sola ronda eso si, ¿es a propósito? :0 ). Si quieres ser precavido, podrías incluir en tu README una sugerencia por lo del computador y así se le asigna a un ayudante con un computador más potente! 

Respecto a lo de no mover ni minimizar, indicalo y no habrá problema 👍 

Éxito!

**Comment by VicenteMerino** [comment]
Que bueno escuchar esto, lo de una ronda, es porque aún no implemento la continuidad de rondas, aun así mi duda era porque de repente se caía la ventana en mi otro computador. De todas formas una vez termine probaré bien mi código y veré si es que hay problemas de compatibilidad según el equipo.

Saludos

**Comment by gatochico** [comment]
No te preocupes, sólo avisaba lo de la ronda en caso de que no fuera intencional y así pudieras verlo! Éxito y sigue así (:
