### ISSUE TITLE
problemas con currencyconverter

### ISSUE THREAD

**Issue by nnovoag** [IIC2233/syllabus#391]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /Users/noeminovoa/Library/Python/3.7/lib/python/site-packages
sysconfig: /Users/noeminovoa/Library/Python/3.7/lib/python3.7/site-packages
WARNING: Value for scheme.purelib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /Users/noeminovoa/Library/Python/3.7/lib/python/site-packages
sysconfig: /Users/noeminovoa/Library/Python/3.7/lib/python3.7/site-packages
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /Users/noeminovoa/Library/Python/3.7/include/python3.7m/UNKNOWN
sysconfig: /Users/noeminovoa/Library/Python/3.7/include/python3.7
WARNING: Additional context:
user = True
home = None
root = None
prefix = None

ayuda porfa!!!! llevo 3 dias tratando de arreglarlo

**Comment by aaossa** [comment]
Hola @nnovoag , ¿cuál es tu problema? 🤔 Por lo que veo es solo un *warning* (advertencia) y no un error. ¿Es algo que quieres solucionar de todas formas?

**Comment by nnovoag** [comment]
hola profe! pucha es que no me deja usar currencyconverter me sale  esto:
 from currencyconverter import CurrencyConverter
ModuleNotFoundError: No module named 'currencyconverter' y sabiendo que esta instalado, lo vuelvo a instalar y me tira la warning de arriba

**Comment by aaossa** [comment]
@nnovoag me parece que tienes que importar usando `from currency_converter import CurrencyConverter` (ojo con el `_`)
