### ISSUE TITLE
uso de for para un contador

### ISSUE THREAD

**Issue by clementeross** [IIC2233/Syllabus#391]
Hola! Puedo utilizar 'for' para ir agregando unidades a un contador dada una condición? Al fin y al cabo no estoy alterando ninguna estructura.
Ejemplo:
```python
i = 0
for iterable in iterador:
     if condicion:
           i += 1

```
Gracias!

**Comment by clementeross** [comment]
La misma pregunta si ocupo "for" que me retorna un bool dada una condición.

**Comment by Hernan4444** [comment]
@clementeross aunque ese for si cumple las restricciones, recuerda que nosotros vamos a evaluar funcional y lo que quieres hacer se puede hacer fácilmente con funcional (`filter, map, sum`), así que te recomiendo darle una vuelta antes de querer utilizar `for` en esa parte.

Saludos ✌️
