### ISSUE TITLE
Altura en el Parentesco grado 0

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#391]
Hola, tenía una duda respecto al parentesco grado 0 de una persona. 

Esto debido a que el tamaño, al ser continuo es muy dificil que una persona tenga exactamente la misma altura que otra. Entonces al menos que tengan el mismo codigo en la parte de altura lo veo muy dificil que tenga parentesco 0 almenos que sea onda un clon.

Esta bien eso o hay que aproximar de alguna forma?

**Comment by Hernan4444** [comment]
@Kitaps justamente alguien será grado 0 cuando sea un clon, en el primer ejemplo que subimos tenemos a Hernán Valdivieso como clon de Marcelo Lagos y con eso se verifica esa consulta. Por el momento no aproximes nada (revisa #390).
Saludos ✌️

**Comment by Kitaps** [comment]
Ohh vale, gracias
