### ISSUE TITLE
[AC BONUS] PARTE IV

### ISSUE THREAD

**Issue by agustinbc7** [IIC2233/Syllabus#392]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Hola, no entiendo bien qué se evalúa en esta parte, ya que el main no llama a la función y uno puede probar cualquier función. ¿Hay que llamar a la función enviar_test en el main y luego se evalúa la comprobación de cualquiera de las funciones?

**Comment by igbasly** [comment]
Hoola @agustinbc7 ✌️ 

El objetivo de esta función es evaluar el uso de una consulta del tipo POST. En este caso, tu función debe ser capaz de enviar un consulta a la ruta indicada en el enunciado, enviado la información del test correspondiente señalados en los argumentos `test_id` y `respuesta`.

Espero se entienda, quedo atento 😉
