### ISSUE TITLE
Formulario atraso y política de atraso

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#392]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas, tengo 2 preguntas sobre el atraso para la tarea 2. 
1. Se encuentra disponible el formulario para utilizar un cupón? y si es así, dónde puedo encontrarlo?
2. En el caso de que por ejemplo yo me atrase 3 días en entregar, pero tengo 2 cupones, y los utilizo, eso me dejaría optar a nota máxima 6?

**Comment by augustayanez** [comment]
Respecto a tu primera pregunta, este se publicó ayer. Te adjunto el link al [formulario de entregas atrasadas T2](https://docs.google.com/forms/d/e/1FAIpQLSeJ3zBHDsNpIXRcNvFBgBHSXxHf8uc72qw6hUpl0ANIPWefmA/viewform).
Respecto a tu segunda pregunta, efectivamente optarías a nota máxima 6.

**Comment by augustayanez** [comment]
Te sugiero leer la issue #387 si quieres saber más sobre los descuentos por atrasos.

**Comment by augustayanez** [comment]
@martinpint Una corrección, la tarea se puede entregar con máximo 2 días de atraso, es decir, máximo hasta el domingo. Los cupones sirven para eliminar el descuento asociado a los días de atraso, pero lamentablemente no extienden el plazo de entrega. Lamento la confusión!

**Comment by Angel-Ros** [comment]
Buenas noches,

Una duda @augustayanez, lamentablemente por temas personales no pude estar casi nunca centrado en la tarea, pensé que se entregaba a las 12 y traté de avanzar todo lo que pude pero, me confundí y me di cuenta a eso de las 21:20 del domingo (hoy) que el horario de entrega era hasta las 20:00, puesto que lo entregué tarde, se me pondrá la nota mínima?, si es así lo entiendo solo quiero saber para no quedarme con la duda ni tener falsas esperanzas, para ser honesto mi entrega tampoco da para mucho más :(, gracias igual desde ya.

**Comment by augustayanez** [comment]
Hola @Angel-Ros! Leyendo tu caso, la mejor recomendación que te puedo hacer es que hables con el ayudante de bienestar de tu sección (te adjunto una foto con su contacto) para que ellos evalúen la situación que me comentas. Saludos!
![image](https://github.com/user-attachments/assets/13b0033c-04ec-423e-bc53-059e8e0001be)
