### ISSUE TITLE
Equivalencia threading/PyQt5

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#392]
Hola, quisiera usar el siguiente código para la pausa de mi código: [https://stackoverflow.com/questions/33640283/thread-that-i-can-pause-and-resume](url)
Sin embargo, no se cual sería el equivalente de Condition en PyQt5, lo que más se acerca es el comando QWaitCondition [https://doc.qt.io/archives/qt-4.8/qwaitcondition.html](url)
 sin embargo no se si será correcto.

Saludos

**Comment by VicenteMerino** [comment]
Lo mismo para cual sería el equivalente de Lock()?

**Comment by furzuadr** [comment]
El equivalente de lock es `tu_lock = QMutex()`, y para llamar el lock haces: 
```
with QMutexLocker(tu_lock):
    funcion
```

**Comment by gatochico** [comment]
Hola!

Dentro de pyqt5 hay varias formas de hacer una cosa, por ejemplo los threads pueden ser tanto QThread como QTimers y eso depende totalmente de como tú decidas enfrentar el problema. Con el caso expuesto, es lo mismo, tienes que ver tu que cosas usar dentro de PyQt5 y ver si funcionan con lo que estás haciendo.

Dado lo anterior, lamentablemente no podemos decir si está correcto o no porque eso es algo que se evalúa y estaríamos soplando la respuesta si te decimos que si o que no 🤐 Saludos!
