### ISSUE TITLE
Duda try/except

### ISSUE THREAD

**Issue by tamyhan** [IIC2233/syllabus#392]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! tengo una duda con el manejo de los bloques try/except, pero para explicarla tengo que mostrar mi código, lo pongo acá?

**Comment by matiasfernandez1** [comment]
Hola @tamyhan, mientras sea código simple que pueda explicitar la duda sí puedes hacerlo. Pero si el código que vas a compartir es un extracto literal de tu programa es preferible que no ya que hacerlo puede ser considerado copia.

**Comment by tamyhan** [comment]
<img width="379" alt="Captura de Pantalla 2021-04-28 a la(s) 16 00 20" src="https://user-images.githubusercontent.com/71773541/116465212-ed6f5c80-a83a-11eb-8755-154e537cf3f5.png">

Ya, es que tengo algo de este estilo, y cuando pongo un input que me debería activar la excepción, el programa me tira el siguiente error: `ValueError: invalid literal for int() with base 10`, y por lo que entiendo es porque trató de correr la última linea pero como no era un dígito no lo puede pasar a int. 

Lo que no entiendo, es por qué corre la última línea cuando se activa la excepción?

**Comment by matiasfernandez1** [comment]
Por lo que veo estás haciendo una recursión. Lo que sucede en el código es que el programa si la primera opción no es válida va a ir a el except y se va a llamar a funcion1() de nuevo. Pero luego cuando se resuelva este segunda llamado de funcion1(), va a continuar bajando y se encontrará con la línea de:
`opcion_nueva = int(opcion)`
Entonces inevitablemente vas a correr dicha linea. 
Una solución podría ser mover esa línea hasta el try. Quedando algo así el try
`
try:
    funcion2(opcion)
    opcion_nueva = int(opcion)
`

**Comment by tamyhan** [comment]
Ahí me funcionó!! Pero me quedó un bloque enorme adentro del try. Eso podría ser considerado mala práctica?

**Comment by matiasfernandez1** [comment]
Se espera que el programa este bien modularizado por lo si crees que podría dificultar la corrección de tu tarea puedes hacer pasar alguna parte de este trozo que mencionas a una función por si sola.

**Comment by tamyhan** [comment]
ok!! gracias! :)
