### ISSUE TITLE
ruta sprites

### ISSUE THREAD

**Issue by maormeno** [IIC2233/syllabus#392]
En el enunciado dice que todos los paths deben ir en "parámetros_generales.py". Esto aplica incluso para los sprites de todos los tiles? O el path puede llegar solo hasta la carpeta donde se encuentra y ahí agregar en el código el nombre del tile que se quiere ocupar?
Gracias!

**Comment by jeschuwirth** [comment]
Hola @maormeno,

Por lo general debería estar el path de cada tile.

Lo que puedes hacer que va a ser más sencillos es tener el path_sprites en parametros.py.

`PATH_SPRITES = "data/carpetas/sprites"`

y luego un diccionario con cada tile por separado:

```
DICT_TILES = {
"pasto": PATH_SPRITES + "pasto.png"
.
.
}
```
así solo tienes que importar una cosa de parámetros :)

Suerte!

**Comment by maormeno** [comment]
gracias!
