### ISSUE TITLE
Adición de atributos para Campeonato

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2233/syllabus#392]
Hola!
Es posible agregar nuevos atributos en la clase Campeonato, para que tenga una estructura similar a la del ejemplo de Mario Bros respecto a las otras clases?  (Estoy tratando de no develar mucho mi idea, no se cómo hacer una pregunta privada, ojalá me entiendan jajaj)
Desde ya muchas gracias, que tengan una linda tarde.

**Comment by retamalcito** [comment]
¡Hola @Sofia-Arratia!

Sí puedes crear nuevos atributos para tu clase `Campeonato`, siempre y cuando no se contradiga lo que dice el enunciado :eyes:. Así que ten cuidado con que alguno de tus nuevos atributos haga que la implementación de otra parte de la tarea deba hacerse de una forma diferente a como se explicita en el enunciado. ❗

¡Saludos!

**Comment by Sofia-Arratia** [comment]
Ok! Muchas gracias!
