### ISSUE TITLE
Digitos lista y elementos de la lista

### ISSUE THREAD

**Issue by jadiaz6** [IIC2233/Syllabus#392]
Hola, en el ejemplo del enunciado salen ids de listas con 3 dígitos, también hay elementos de listas que poseen 6 dígitos.

El enunciado nunca especifica la cantidad de dígitos máxima

¿Es 3 y 6 respectivamente?

**Comment by Hernan4444** [comment]
@jadiaz6 no puedes asumir que son 3 y 6 respectivamente. La cantidad de digitos puede ser desde 1 hasta el número que se estime conveniente y por eso no se especifica en el enunciado.
