### ISSUE TITLE
Uso de while en string replacement 

### ISSUE THREAD

**Issue by Clemente24** [IIC2233/Syllabus#392]
Hola,

Quería preguntar si se puede usar un while al momento de hacer el preprocesamiento... Leyendo las demás issues no me quedé tranquilo porque creo que no es el mismo caso.

Mi función hace algo como esto:

```Python
def pre_process(comment):
    html_start = '<'
    html_end = '>'
    string = comment
    while html_start in string:
       # borrar etiquetas HTML y lo que contengan
        string = "string limpio"

    return string
```

Por temas obvios, el código está más bien como un pseudocódigo, pero la funcionalidad se entiende igual.

Mi duda surge por el hecho de retornar un string que ha sido afectado por ciertos slicings.

Gracias!

**Comment by Clemente24** [comment]
Pero por qué estaría siendo fuera de regla? Asumiendo que los string no son una estructura de datos. Tampoco me queda muy claro a qué se refiere con "no retornen algún dato", ¿a qué tipo de dato se hace referencia?

**Comment by rihanuch** [comment]
@Clemente24 , se abrió una issue ( #401 ) en especial para estos casos, ahí puedes preguntar más en específico 😬
