### ISSUE TITLE
error test cases funcion 24 votantes validos por distrito

### ISSUE THREAD

**Issue by emivenezian** [IIC2233/Syllabus#392]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

el resultado esperado es lista_esperada = [
            Animal(1, "Gay", "Perro", 190, 288.0, 45, "1979/11"),
            Animal(2, "Lexi", "Gato", 61, 0.071, 34, "1957/8"),
            Animal(3, "Toccara", "Gato", 248, 0.525, 67, "1957/12"),
            Animal(4, "Phil", "Perro", 248, 0.525, 67, "1957/12"),
        ]
lo cual es incorrecto ya que el ponderador de gato es 0.01, lo cual hace que las edades respectivas sean menores a 18 y por ende no son votos validos. Mi codigo retorna la lista correcta, la que solo contiene a los perros, pero los test case hace que me arroje error.

ademas en votos validos los ultimos 3 test cases arrojan error y el codigo esta bien, veo que le paso a mucha gente.

**Comment by jisalasc** [comment]
Me paso algo similar, revise en los test case y creo que cuando instancian locales, en algunas casos usan id_locales = [] y en otros simplemente locales = [], no se si eso afectará.

**Comment by mpiavf** [comment]
Hola, actualizamos los tests con lo detectado en esta issue y otras más. Pueden revisar la issue creada en #444 para más detalle. 
Saludos!
