### ISSUE TITLE
Reasignar variables

### ISSUE THREAD

**Issue by pizquierdo2** [IIC2233/Syllabus#392]
Y con respecto a la función asignar, si yo ejecuto asignar('x', columna1), y después ejecuto asignar('x', columna2), en esta segunda ejecución debería interpretar la variable 'x' como columna1 (y así devolver error de tipo) o debería reasignar la variable 'x' a columna2?
Gracias

**Comment by Hernan4444** [comment]
se reasigna
saludos!!
