### ISSUE TITLE
Maximo de lineas en mas de un archivo

### ISSUE THREAD

**Issue by Cristian1754** [IIC2233/Syllabus#392]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Buenas tardes, mi duda surge al tener mas de un archivo con mas de 400 lineas, el backen tiene 430 y lo podria arreglra quitandole ciertas explicaciones y comentarios que ordenan el archivo, pero tambien tengo un archivo en el frontend irreparablemente largo, y la pregunta es la siguiente. el descuento es el mismo si es que tengos ambos archivos a que si solo tengo uno pasado?, ya que si da lo mismo si tengo uno o 2, me conviene dejar los dos ordenados y pasados

**Comment by mjmillan9** [comment]
Holaa @Cristian1754 !

La pauta de corrección dice lo siguiente: _"Se descuenta 5 décimas si uno o más archivos excede las 400 líneas de código"_
Por lo que si ya tienes un archivo que supera las 400 líneas se hará el descuento, por lo que te conviene dejar los 2 ordenados y pasados 

Suertee en tu tarea!
