### ISSUE TITLE
if funcion y if not funcion

### ISSUE THREAD

**Issue by pascal1003** [IIC2233/syllabus#393]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] 
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, 
me surgió una duda, si tengo una con condición "if not función" eso es equivalente a 
"if función== false" o a 
"if función!=True" 
En otras palabras si tengo una función con de la forma

def funcion(x):
     .
     .
     .
     if a==x:
            return a
     else:
           return False

el not función seria verdadero siempre porque no retorno nunca true o seria verdadero cuando retorno false?

**Comment by riadeane** [comment]
Hola @pascal1003!

Efectivamente puedes hacer `if not funcion` como reemplazo de `if funcion == False` o `if funcion != True`. Diría que generalmente se recomienda dado que queda más legible tu código.

Respecto a tu otra duda, generalmente cuando defines una función deberías retornar el mismo tipo de variable (string, booleano, entero, tupla, etc.) siempre. En el ejemplo que das, retornas `a` y `False`. Supongamos que `a` es un booleano para mantener esta estructura (más abajo está qué pasa si `a` no es un booleano). En caso de que `a` sea `True`, `not funcion` sería `False`.  Por otro lado, si `a` es `False` o si entras al `else` y retornas `False`, `not funcion` sería verdadero.

Por otro lado, si `a` es otro tipo de variable, depende de qué contiene para ver si se considera falso o verdadero cuando lo evalúas como un booleano. Por ejemplo, si es una variable de tipo string, los strings vacíos (`""`) se consideran como falsos , mientras que cualquier string no-vacío se considera como verdadero. Lo mismo ocurre con las listas, tuplas, diccionarios, y sets vacíos (y muchas cosas más, [aquí te dejo más información](https://www.freecodecamp.org/news/truthy-and-falsy-values-in-python/)). Todos estos valores se conocen como valores _Truthy_ o _Falsy_, ya que en estricto rigor no tienen un valor `True` o `False` pero se evalúan como tal. En general te pueden servir si quieres ver si algo es vacío antes de hacer una acción, por ejemplo si quieres revisar que un string esté vacío antes de concatenar algo nuevo puedes hacer lo siguiente:

```
if not string_vacio:
    string_vacio += lo_que_quiero_agregar
```

Espero que con eso te haya quedado más claro. Éxito en tu estudio! ✨

**Comment by pascal1003** [comment]
Muchas Gracias
