### ISSUE TITLE
Funcionamiento drag and drop entre qwidgets

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#393]
Idealmente para separar el inventario del mapa habría que tener dos widgets en un layout, mi duda es sobre donde implementar el mecanismo de señales para hacer el drag and drop. Hasta ahora yo tengo el manejo de señales para el drag and drop (eventos del mouse) en el widget principal pero esto me parece un poco incomodo ya que si quiero encontrar el elemento en el inventario que se va a mover hacia el mapa tendría que desde el widget principal localizar las coordenadas de los labels en el inventario. Quizas hacerlo todo desde el widget principal es lo mas facil.
Lo otro sería que al activar el `mousePressEvent` en el inventario se mandara una señal a la ventana principal para que activara el `mouseMoveEvent` o algo así. Tampoco sé como funcionaria.

**Comment by gatochico** [comment]
Hola! 
Lamentablemente, este tipo de preguntas es uno de los objetivos de la tarea, por lo que no podemos darte la respuesta concreta :( . Algunas sugerencias que pueden ayudarte:

- Revisa la documentación de pyqt5 de los elementos que quieres utilizar (drag and drop, QWidgets, etc.). Si no logras encontrarla, también puede es util revisar la documentación de Qt, la cual es un poco más clara, y hacer la analogía con pyqt5.
- Busca ejemplos en internet de las cosas que deseas hacer: ¿Alguien hizo algo similar? ¿Cómo lo hizo? ¿Lo hizo correctamente?
- **Prueba tu código**. Si tienes dos ideas de cómo implementar algo, y no sabes cuál será la más sencilla, o la más ordenada... ¡Trata de implementar ambas, y ve cuál resultó mejor! 

En esta tarea, les damos mucha libertad con respecto a qué cosas de pyqt5 usar en su interfaz,  siempre y cuando se cumpla el requisito de que esté modelado correctamente (Buena separación front/backend, uso de señales, etc.). 
Éxito!

**Comment by dgzmr** [comment]
@gatochico unu, gracias por los consejos
