### ISSUE TITLE
Testacases año bisiesto

### ISSUE THREAD

**Issue by M4TI4D4CZ** [IIC2233/Syllabus#393]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Hola, estaba revisando los testcases de la funcion 22, año bisiesto y no veo en qué falla mi codigo, no se si es un problema de los testcases o mío. 

![image](https://github.com/IIC2233/Syllabus/assets/130701916/88e94142-3f72-4a00-baae-4e711f115ce0)

**Comment by Martinluco** [comment]
puede ser que te falta el punto final?

**Comment by Jeremiah-PHP6** [comment]
¡Hola! Como señala @Martinluco, puede que te falte añadir el punto final al string (una nimiedad). Prueba con eso a ver si te funciona.

Saludos.

**Comment by M4TI4D4CZ** [comment]
efectivamente era eso, MUCHAS GRACIAS!
