### ISSUE TITLE
Testing-MiniDatabase

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#393]
Hola!
Al momento de testear las consultas que generar otras bases de datos, demos testear que el resultado sea una generador, el contenido de este generador o ambas cosas??
¿Puedo utilizar la MiniDatabase para realizar los testing? En caso de poder, ¿la debo subir junto con mi tarea o solo lo debo especificar en el REAMDE?

**Comment by nachocontreras** [comment]
Holaa!

Para las consultas que generen otras bases de datos se debe verificar el contenido del generador.
Para el testing se puede usar la MiniDatabase, pero esta debe subirse y especificarse en el Readme.
Este archivo se debe subir con el nombre de testing_minidatabase, para que asi el ayudante sepa que está relacionado con el testing.

Saludos 😀

**Comment by naquiroz** [comment]
@nachocontreras Una duda con respecto a lo que dijiste, qué hacemos en el caso de `load_database`?  Pregunto, porque me da la sensación de que la única forma de testear eso en esa función es haciendo exactamente el mismo procedimiento 😕

**Comment by nachocontreras** [comment]
Exacto, para testear ```load_database``` se puede utilizar el archivo testing_minidatabase y luego revisar el contenido del generador. Sin embargo, se recomienda usar un archivo más pequeño debido a la cantidad de elementos a testear en esa función.

Saludos!

**Comment by naquiroz** [comment]
@nachocontreras creo que no me explique bien, me da la sensacion que para hacer el testing, hay que hacer lo mismo que hace la funcion, pero para formar el test_case, entonces no me hace mucho sentido.

**Comment by nachocontreras** [comment]
Efectivamente, se debe crear un test_case que sea el resultado esperado de la funcion ```load_database```, para asi poder verificar si el contenido del generador es igual al resultado esperado.
