### ISSUE TITLE
Duda ataque enemigos básicos

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#393]
Hola, para los enemigos básicos, es válido que ataquen una base o torre solo el tiempo que se mantengan frente a ella, pero esto no impida que dejen de atacarla en algún momento y sigan su camino normalmente? Además el ataque no necesariamente debe ser de frente (se que visualmente no es muy correcto, pero el enunciado pareciese no contradecir esto)?

**Comment by gatochico** [comment]
Hola! Respondiendo a tus dudas:
-Recuerda que los enemigos normales solo pueden atacar la base, y no atacan a las torres!
-Si, es posible que el enemigo esté atacando la base y por decisiones de movimiento, se alejen de ella y dejen de atacarla hasta que otro movimiento aleatorio los lleve a ser adyacentes nuevamente.
-No es necesario que cualquier enemigo (normal o kamikaze) esté mirando de frente a la base/torres para que las ataquen, solo basta que estén adyacentes.
Éxito!

**Comment by Liks96** [comment]
En la página 13 no queda claro lo que mencionas, dado que dice "em caso que sea un enemigo normal, éste solo dañará la torre o base si es que se encuentra en una casilla adyacente a ella".  
Los enemigos normales entonces atacan o no torres?

**Comment by gatochico** [comment]
Recuerda que hace aproximadamente 10 días se mandó una notificación via issue de github y aviso de siding indicando que habíamos corregido partes del enunciado, entre esas incluida la parte que citas de los enemigos normales. Para más detalles, descarga el enunciado corregido y revisa la issue #242 !
