### ISSUE TITLE
Tengo nuevos problemas subiendo la actividad bonus al repositorio privado

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#393]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola,
Después de la issue pasada donde no me dejaba subir la actividad bonus a mi repositorio privado, borré la carpeta de AB en mi repositorio y en mi computador. 
Volví a crear la carpeta AB en mi repositorio privado e hice git pull.
En la carpeta AB en mi computador, pegué los archivos de la actividad e hice git status, add, commit y push. Pero no me deja y creo que es porque la nueva carpeta AB tiene el mismo nombre que la anterior que tenía problemas.

Primero, en git status solo me salía el archivo pokemon.py (que no sé si es uno antiguo o el más avanzado). A ese hice git add, commit y push. Este es el mensaje de la terminal

To https://github.com/IIC2233/Fernanda1232123-iic2233-2021-2.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/IIC2233/Fernanda1232123-iic2233-2021-2.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

El resto de los archivos simplemente no salen

¿Por qué puede ser? ¿Qué puedo hacer?

**Comment by igbasly** [comment]
Hola @Fernanda1232123 ✌️ 

Te recomiendo hacer lo que te describí en la issue anterior, así que cerraré esta issue ya que el tema es el mismo.
