### ISSUE TITLE
Nueva simulación y archivo puntajes.txt

### ISSUE THREAD

**Issue by CarolinaYanez** [IIC2233/syllabus#394]
Hola! Tengo dos dudas

En la parte 3.2.2 del enunciado dice que terminados los días de competencia debe darse la opción de **realizar una nueva simulación**. Con esto se refiere a volver a iniciar el programa (por ejemplo volver a pedir nombre usuario, rival, etc)? o con los mismos datos entregados por el jugador previamente volver a realizar un nuevo campeonato?

Segundo, en el archivo **puntajes.txt** que de debe crear, se deben guardar los datos **sólo de un campeonato** o de **todos** los campeonatos realizados hasta el momento? En caso de que sea lo primero (sólo se guarda un campeonato), se debe **sobreescribir** el mismo archivo cada vez que se quieren guardar los datos de un campeonato o se espera que hagamos un archivo diferente para cada campeonato?

Muchas Gracias!

**Comment by vsantelicest** [comment]
Hola! 
Con respecto a tu primera pregunta, la opción que mencionas se refiere a volver a iniciar la DCCumbre Olímpica por completo, pidiendo nuevamente el nombre y reseteando la información que haya variado durante la ejecución de la anterior competencia.
Sobre la segunda pregunta, el enunciado no se refiere a cual de las dos opciones que mencionas sería la correcta, por lo que podrías hacerlo de la manera que tu estimes conveniente, siempre y cuando lo dejes claro en tu Readme. Éxito en la tarea! 🏊

**Comment by CarolinaYanez** [comment]
Okey, muchas gracias!! 😄
