### ISSUE TITLE
Excepción Genérica

### ISSUE THREAD

**Issue by maxfreymo** [IIC2233/Syllabus#394]
¿Qué se considera una excepción genérica? ¿**except Exception**?
¿Esta bien colocar:
_try:
     algo
except TypeError:
     print("Error: El dato no es del tipo requerido")_
o hay que especificar el tipo de error type que se generó ? (ejemplo: except TypeError: se produjo porque el valor x no es del tipo int)

**Comment by Hernan4444** [comment]
@maxfreymo con excepción genérica es exactamente lo que dices `except Exception`. Tu ejemplo está bien colocado :+1: 

Saludos
