### ISSUE TITLE
Atributos base diagrama de clases

### ISSUE THREAD

**Issue by Raibruh** [IIC2233/syllabus#394]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Si al crear una clase hago algo como:

![duda](https://user-images.githubusercontent.com/80918062/116443110-3f0aed80-a821-11eb-85c4-b0b4b52b6b77.png)

, con el objetivo de guardar el valor inicial de la clase para poder recuperarlo más tarde en el programa, ¿debo agregar ambos al diagrama de clases?

**Comment by manearaya** [comment]
Hola @Raibruh!

La modelación que representas en tu diagrama de clases tiene que ser fiel a las clases que defines en tu código, por lo que si tienes dos atributos distintos definidos en una clase, estos deben estar reflejados en el diagrama de clase.

Suerte con la tarea!
