### ISSUE TITLE
una de mis funciones no muestra un label, pero si lo crea 

### ISSUE THREAD

**Issue by LunaGarces** [IIC2233/Syllabus#394]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

en mi codigo, creo un diccionario para saber las ubicaciones de los personajes, y este lo envio a una función que me instancia lo requerido, para modo constructor constructor me funciona perfecto, pero cuando le envio la info de los archivos mapas, en forma de diccionario, me crea los labels pero no los muestra 

estas dos señales emiten un diccionario, de forma {'L': [], 'P': [], 'V': [], 'H': [], 'R': [], 'S': [], 'F': []},  senal_info_mapa esta es de modo constructor y esta senal_diccionario_creado de donde leo los archivos de mapa, las dos llegan donde mismo, pero solo una me muestra las imágenes, ya corrobore las key de senal_diccionario_creado y la info de esta, y es correcta, no se si me pueden ayudar para saber porque los labes se crean, pero no se muestra 
**self.ventana_principal.senal_info_mapa.connect(self.ventana_principal_2.elementos_en_grilla)
    self.logica_principal.senal_diccionario_creado.connect(self.ventana_principal_2.elementos_en_grilla)**]

**Comment by Hernan4444** [comment]
Hola @LunaGarces 

Revisé tu código, el problema está en el main línea 28

```python
self.ventana_inicial.senal_todo_ok.connect(self.ventana_principal.mostrar)
```
Esa línea indica que si la validación fue exitosa, si o si se muestre la ventana_principal con el modo constructor, pero dado que tu tienes otra ventana para el modo juego, entonces falta depurar esa parte, que si la validación fue existosa *Y* escogí un mapa ya existente, entonces debo abrir directamente la ventana del juego, no la del modo constructor.

Puedes verificar esto si la línea 28 la duplicas y pones

```python
self.ventana_inicial.senal_todo_ok.connect(self.ventana_principal_2.mostrar)
```
De este modo, abrirás ambas ventanas y te darás cuenta que la que observabas era la del modo constructor y la del modo juego ya estaba lista y se ve todo lo que quieres.

Saludosヾ(＾-＾)ノ

**Comment by LunaGarces** [comment]
Profeee!! Graciasss lo voy a revisarrr!!! ✨✨

Sent from my iPhone

On 23-05-2023, at 14:48, Hernan Valdivieso ***@***.***> wrote:

﻿

Hola @LunaGarces<https://github.com/LunaGarces>

Revisé tu código, el problema está en el main línea 28

self.ventana_inicial.senal_todo_ok.connect(self.ventana_principal.mostrar)

Esa línea indica que si la validación fue exitosa, si o si se muestre la ventana_principal con el modo constructor, pero dado que tu tienes otra ventana para el modo juego, entonces falta depurar esa parte, que si la validación fue existosa Y escogí un mapa ya existente, entonces debo abrir directamente la ventana del juego, no la del modo constructor.

Puedes verificar esto si la línea 28 la duplicas y pones

self.ventana_inicial.senal_todo_ok.connect(self.ventana_principal_2.mostrar)

De este modo, abrirás ambas ventanas y te darás cuenta que la que observabas era la del modo constructor y la del modo juego ya estaba lista y se ve todo lo que quieres.

Saludosヾ(＾-＾)ノ
