### ISSUE TITLE
parámetro N

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#394]
He leído en varias issues que se debe utilizar un parámetro N que define el largo de los pixeles del mapa. Yo no definí explicitamente este parámetro y mi mapa es de tamaño fijo (500 * 250 pixeles app), por lo que los pixeles se hacen más grandes o más chicos dependiendo del tamaño del archivo .txt del mapa.  He probado con varios tipos de mapas (creé unos nuevos) y mi programa funciona bien. Es estrictamente necesario crear el parámetro N o está bien la forma en que lo hice?

**Comment by jeschuwirth** [comment]
Hola @FelipeA7,

Recuerda que se pueden hacer supuestos para tu tarea **siempre y cuando**  no se contradiga el enunciado. Como en la sección 6.1 te piden usar ese parámetro:

![image](https://user-images.githubusercontent.com/37160256/66222008-8c0afa00-e6a6-11e9-8974-7220dcbbcfb1.png)

Entonces estarías contradiciendo el enunciado al no usar N.

Suerte en la tarea y ojalá no tengas que cambiar muchas líneas 😅

**Comment by tomasalvarez13** [comment]
Puedo suponer que el parametro N permanecerá constante, si lo especifico en mi readme?

**Comment by FelipeA7** [comment]
Esto significa que los mapas van siendo más grandes o más chicos dependiendo de la cantidad de “piezas” que contiene cierto? 
Es decir, si por ejemplo tengo uno de 10x10 y uno de 20x20, entonces mi ventana del mapa debería ser más grande para el de 20x20?

**Comment by jeschuwirth** [comment]
@tomasalvarez13, el parámetro N va a ser constante durante la ejecución de tu código, sin embargo si el ayudante tiene el juego muy grande o muy pequeño como para corregir debería tener la libertad de cambiar N y que siga funcionando.

@FelipeA7, así es. Si el tablero es de 20x20, entonces debería ser 4 veces más grande que el de 10x10.

**Comment by burgosibarra** [comment]
He contestado el form que enviaron sobre la resolución de la pantalla y el tamaño de la ventana más grande.
Si tengo un parámetro N que indique el tamaño de los píxeles
Cómo puedo evitar sobrepasar el tamaño de la ventana que ya he enviado suponiendo que el mapa que pueden usar ustedes es más grande? O puedo asumir que no serán más grandes que los que ya enviaron?
Desde ya, muchas gracias

**Comment by jeschuwirth** [comment]
Hola,

Pueden asumir que los mapas no serán más grandes de los ya enviados, si el ayudante quiere probar con más grandes no va a descontar si se sale del tamaño.

Suerte !
