### ISSUE TITLE
Run QThread

### ISSUE THREAD

**Issue by YoGandalf** [IIC2233/syllabus#394]
Cuando heredo una clase de qlabel y de qthread al llamar el metodo start no me corre el run sino que el start. Parece que no me lo reconoce como thread no se que se puede hacer.
PD: heredo primero de qlabel que de qthread no se si influye

**Comment by gatochico** [comment]
Hola! Tu error probablemente se debe a que PyQt no funciona muy bien al heredar de más de una clase Qt, exactamente por cosas como las que te están pasando. En la misma documentación se indica:
![image](https://user-images.githubusercontent.com/37161120/58372758-87605900-7ef0-11e9-8fd1-b89a424f7b95.png)
Te recomendaría encontrar una forma de realizar lo que quieres sin la herencia múltiple. Éxito!
(Protip: Querer heredar de tanto Qlabel como de Qthread al mismo tiempo me suena como a que no hay una buena separación entre frontend y backend :eyes: Quizás podrías comenzar por ahí? )
