### ISSUE TITLE
(Posible) error en los test cases de test_20_votos_validos

### ISSUE THREAD

**Issue by VicenteIgnacioSotoGonzalez** [IIC2233/Syllabus#395]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Buenas tardes, junto con saludar quería consultar si tiene sentido que todos los tests pequeños de votos_validos funcionen pero los que involucran el importe de datos .csv no. Esto es actualmente lo que me sucede al correr mi código en ese test (sucede el mismo problema de diferencia de largo en los tests 5, 6, 7). (Hice Git Push por cualquier cosa :D) Gracias de antemano!

![imagen](https://github.com/IIC2233/Syllabus/assets/162501853/740cb946-d03c-4633-b4cd-09035665a008)
![imagen](https://github.com/IIC2233/Syllabus/assets/162501853/3ced1d41-9e9c-4a83-96f0-d8a3e0e20bd1)

**Comment by jfpantoja** [comment]
Hola @VicenteIgnacioSotoGonzalez!
Hace poco respondí la issue #391 donde hablo sobre este problema.

**Comment by VicenteIgnacioSotoGonzalez** [comment]
> Hola @VicenteIgnacioSotoGonzalez! Hace poco respondí la issue #391 donde hablo sobre este problema.

Okas, muchas gracias por la respuesta! ;)

**Comment by mpiavf** [comment]
Hola, actualizamos los tests con lo detectado en esta issue y otras más. Pueden revisar la issue creada en #444 para más detalle. 
Saludos!
