### ISSUE TITLE
Instanciar clase T03Window

### ISSUE THREAD

**Issue by chuma9615** [IIC2233/Syllabus#395]
Hola!

Mi pregunta es si puedo instanciar esta clase en otro modulo aparte del main

saludos!

**Comment by Hernan4444** [comment]
@chuma9615 puedes hacerlo **pero queda bajo tu responsabilidad**, instanciar esa clase en el main funciona perfectamente, si decides instanciarla en otro modulo aparte y no llega a funcionar, no se tendrá consideración especial.

Saludos!
