### ISSUE TITLE
Stats y inventario fuera de ventana principal

### ISSUE THREAD

**Issue by tomasalvarez13** [IIC2233/syllabus#395]
Hola, queria preguntar si es valido dividir mi juego en 2 ventanas: una en la que este el mapa con el personaje, y otra en la que se encuentren los stats y el inventario. 
Gracias

**Comment by tomasgv** [comment]
Hola!

El diseño y número de las ventanas queda a tu criterio, por lo que es válido siempre y cuando esté lo pedido en el enunciado.

Saludos!  👨‍🌾  🌽
