### ISSUE TITLE
Liberado de memoria en Python

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#395]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Justamente haciendo la tarea, me vino la duda de cuándo python decide eliminar una instancia de la memoria? Ya que si estoy instanciando un canal cada vez que el usuario elige uno, a menos que python decidiera eliminar las instancias, podríamos llenar la memoria, no? _(ejemplo de la tarea, pero mi pregunta no tiene nada que ver con esta per se)_

**Comment by matiasfernandez1** [comment]
Hola @fernandosmither, si te refieres a llenar la memoria de tu disco local no. Ya que los programas en los sistemas operativos se ejecutan en la memoria ram. Que es una memoria destinada a ser rápida y por ende poder ejecutar los programas que solicite el usuario con mayor fácilidad que la memoria de un disco duro. 
Ahora bien, sobre si es posible hacer un programa que ocupe toda tu memoria RAM. Primero dependerías de tener en cuenta cuantaa memoria RAM dispongas en tu computador, es distinto estar con 16Gb de memoria RAM en vez de que con 126 Mb. Podrías en teoría hacer un programa que ocupe un montón de memoria RAM tanto que tu programa tenga que ser cerrado porque tu computador empieza a ponerse lento. Pero no es nada que luego de un reinicio no arregle. 
Si tienes curiosidad de ver cuánta memoria ocupa algún objeto que hayas instanciado en python puedes ocupar la librería `sys` con el método `getsizeof`. En el siguiente [link](https://www.analyticslane.com/2018/11/19/reducir-el-consumo-de-memoria-en-python/) puedes encontrar información de cómo ocuparlo. 
Saludos.

**Comment by fernandosmither** [comment]
> Hola @fernandosmither, si te refieres a llenar la memoria de tu disco local no. Ya que los programas en los sistemas operativos se ejecutan en la memoria ram. Que es una memoria destinada a ser rápida y por ende poder ejecutar los programas que solicite el usuario con mayor fácilidad que la memoria de un disco duro.
> Ahora bien, sobre si es posible hacer un programa que ocupe toda tu memoria RAM. Primero dependerías de tener en cuenta cuantaa memoria RAM dispongas en tu computador, es distinto estar con 16Gb de memoria RAM en vez de que con 126 Mb. Podrías en teoría hacer un programa que ocupe un montón de memoria RAM tanto que tu programa tenga que ser cerrado porque tu computador empieza a ponerse lento. Pero no es nada que luego de un reinicio no arregle.
> Si tienes curiosidad de ver cuánta memoria ocupa algún objeto que hayas instanciado en python puedes ocupar la librería `sys` con el método `getsizeof`. En el siguiente [link](https://www.analyticslane.com/2018/11/19/reducir-el-consumo-de-memoria-en-python/) puedes encontrar información de cómo ocuparlo.
> Saludos.

Hola!
Muchas gracias Matías por tu respuesta. Mi pregunta, en todo caso iba más enfocada a cómo python maneja su memoria, como por ejemplo la función ``malloc`` y ``free`` de C. A mi me hace más sentido que este manejo fuese dinámico, y que por ejemplo (estoy inventando), justo antes de eliminar todas las referencias a un bloque de memoria, este sea liberado.

(En el caso que, por ejemplo un objeto de la instancia Barco, que solamente vivía dentro de una lista, al sacarlo de esta lista, saber si Python reconoce que ya no tengo forma de llegar a él, y lo borra para liberar memoria, o esta instancia vive infinitamente hasta cerrar el programa)

Sé que en el ejemplo que di pudo haber sonado irrelevante la cantidad de memoria que se utiliza y me mencionas el ejemplo de distintos tamaños de RAM, sin embargo, me interesaría saber mucho qué sucede cuando estoy trabajando con archivos más grandes, ya que estoy en un mini-proyecto donde creamos una interfaz básica de búsqueda de 2 csv's de más de 4 GiB c/u y claro, a mi máquina le cuesta mucho correrlo y es divertido ver como la RAM spikea en el administrador de tareas 😂😂

Lo otro, pensándolo bien, este manejo no dependería también de la implementación de python? (por ejemplo, quizás ``CPython`` lo maneja distinto a ``Jython``, pero de nuevo, es un tema que desconozco completamente y por eso la pregunta)

**Comment by fernandosmither** [comment]
bump u,u
