### ISSUE TITLE
Cantidad positives , Negatives , Neutral

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2233/Syllabus#395]
Hola , me nace una duda en el procesamiento , ya que al ejecutar los porcentajes en todos lo comentarios me muestra que solo hay dos comentarios positivos , 0 negativos y el resto neutros. Cuando los correctores corrijan la tarea pondrán mas palabras en tipos o bajaran el nivel de porcentajes para aceptar la connotación del comentario , de antemano muchas gracias.

**Comment by pcseisdedos** [comment]
Lo respondieron en #348

**Comment by Dyoma3** [comment]
@nicoparraguez me dio la misma cantidad que a ti porsiacaso
