### ISSUE TITLE
Espacios en los nombres

### ISSUE THREAD

**Issue by jadiaz6** [IIC2233/Syllabus#395]
Hola, me he fijado que en algunos nombres hay espacios, en el enunciado dice que debemos controlar el error.
Por ejemplo, en el caso de Luna Lovegood, la línea es "5Luna 8Lovegood...".

Asumo que en este caso hay que hacer un exception que lo cambie a "4Luna8Lovegood...".

¿Es esto correcto?

**Comment by Hernan4444** [comment]
#355
