### ISSUE TITLE
Orden de ejecución competencias

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2233/syllabus#395]
Hola, 
tengo una duda con respecto a la entidad campeonato, especificamente en el metodo "realizar las competencias del día". 
En el enunciado dice que:  
"Luego de tener a los competidores definidos, las competencias serán simuladas en el mismo orden en el cual se escogieron sus protagonistas".
 Mi duda es, ¿el orden al que se refieren puedo definirlo yo, y pedir a los deportistas en un orden igual siempre?, ¿o le tengo que dar la posibilidad al que este jugando de ver en que orden los quiere elegir?

**Comment by hsazos** [comment]
¡Hola @antoniaalcayaga !

Lo puedes definir tu! Pero si lo dejas en un mismo orden siempre, asegúrate de explicitarlo en el programa para el usuario.

¡Suerte en la tarea!🦕

**Comment by antoniaalcayaga** [comment]
perfecto, gracias!
