### ISSUE TITLE
Caso enemigos alejados

### ISSUE THREAD

**Issue by Ed0ss** [IIC2233/syllabus#395]
Hola, en el enunciado de la tarea aparece que hay que hacerse cargo de la situación en que los enemigos se demoren mucho en llegar a la base, y entre algunas de las posibilidades para arreglar esto se mencionan temporizadores, botones, aging y un cheat code. Resulta que el cheat code END que se pide resolvería esto también, así que se puede decir que este cheat se encargará del caso en que los enemigos se demoren mucho en llegar? o se debe implementar algo distinto?

**Comment by jmwielandt** [comment]
Hola, 

Esto debe ser algo distinto, pues buscamos que la muerte del enemigo realmente cuente como muerte y el puntaje se asigne, etc. Eso lo pedimos porque la implementación del **END** no es compatible con el término normal de una ronda, entonces para testear el término de partida por derrotar a todos los enemigos no podemos utilizarlo.
