### ISSUE TITLE
Duda actividad 3 contenidos semana 8

### ISSUE THREAD

**Issue by vvialbarros** [IIC2233/Syllabus#395]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Hola buenas tardes.
Para la actividad 3 es necesario usar los contenidos de la semana 8?

**Comment by Igufu** [comment]
No soy ayudante, pero ya hice la actividad y si es necesario usar los contenidos de la semana 8, de hecho hasta te prohíben no usarlos. Espero haberte ayudado :)

**Comment by Hernan4444** [comment]
Hola,

Soy profesor y confirmo que si es necesario usar esos contenidos 😁.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ
