### ISSUE TITLE
Como cuenta el pep8 para funciones atomizadas.

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2233/Syllabus#396]
Si tenemos que escribir una línea de comando en 2 lineas por las reglas de pep8 esta nos cuenta como dos líneas para el atomizar funciones (max 15) o cuenta solo como 1

**Comment by Hernan4444** [comment]
@Jiruiz2 cuantan como 2
Saludos! ✌️

**Comment by josefinabengoa** [comment]
¿la siguiente expresión se puede considerar como una sola linea? 
def f(x): return x

**Comment by fringlesinthestreet** [comment]
@Jiruiz2 También se habló en #333 sobre esto!
