### ISSUE TITLE
Métodos abstractos

### ISSUE THREAD

**Issue by Zenos-Paradox** [IIC2233/syllabus#396]
No estoy seguro de entender bién cómo usar métodos abstractos. 
Si defino un método abstracto en una clase abstracta, puedo poner código dentro del método o debe ser solo pass? Como lo entiendo, cada clase que herede de esta debe definir los métodos abstractos... o basta con poner, dentro de esta definicion, super().metodo?

**Comment by baosse** [comment]
Holaa @Zenos-Paradox !
En la superclase puedes poner el código que sea necesario y que tus subclases heredarán. Este será como tu código común en la función. 
Cuando tu subclase herede la función, en esta puedes poner código que será específico para esa clase o simplemente llamar a la función sin agregarle nada. 
Espero que esto te ayude.
Mucho éxito!✨

**Comment by Zenos-Paradox** [comment]
Entiendo, gracias!
