### ISSUE TITLE
Velocidad movimiento

### ISSUE THREAD

**Issue by mrrebolledo** [IIC2233/syllabus#396]
Hola! Ya preguntaron algo parecido pero no se responde mi duda porque no usé grillas.
Yo en principio asumí que cada movimiento del personaje es avanzar un pixel del mapa. Por lo que si aprieto 4 veces una tecla en una dirección, avanza 4 en esa dirección (y por cada tecla apretada mueve una pierna, osea uso otra foto de movimiento de enzo)
Si sale que velocidad_movimiento es la cantidad de pixeles que avanza el personaje cada vez que se aprieta una tecla (asumí que por pixel se refieren a los del mapa), entonces mi velocidad sería 1? Y si se pone velocidad=4, por apretar una tecla tendría que avanzar 4 pixeles del mapa?

**Comment by aljara97** [comment]
Exacto, como se dijo en la issue #360 el parámetro VEL_PERSONAJE corresponde a la cantidad de pixeles que este se moverá al apretar una tecla. Como indicas actualmente tu velocidad es 1, y si defines este parámetro como 4, deberás desplazarte 4 pixeles al apretar una tecla.
Recuerda que este es un parámetro y que debes definir en ```parametros_generales.py```
