### ISSUE TITLE
Duda ejercicios propuestos, semana 5

### ISSUE THREAD

**Issue by TarzanDeMaceta** [IIC2233/Syllabus#396]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola, quería consultar sobre el tercer archivo de ejercicios propuestos de la semana 5, que según el mismo archivo trata sobre programación funcional, contenido que recién vemos la semana 8, además se nos pide usar funciones como map, filter y reduce, que no vimos durante esa semana, las busque en internet y si bien podría usarlas no entiendo como funcionan internamente y por que son útiles. Mi consulta es **¿esos ejercicios propuestos son un adelanto de la semana 8 o es un error?**

**Comment by Hernan4444** [comment]
Hola @TarzanDeMaceta 

Fue un error subirlos esa semana. Ese notebook corresponde a la semana 8 (Programación Funcional) y se nos traspapeló. De todas formas, para la semana 8 no hay ejercicios propuestos porque está la AC3 que cumple el mismo objetivo.

Finalmente, si quieres realizarlos como mecanismo de estudio, puedes pero necesitarás la materia de la semana 8. Pero antes recomiendo ir por la AC3 que esa es evaluada.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con el curso! 🦖
Saludosヾ(＾-＾)ノ
