### ISSUE TITLE
Error con los enemigos que debiesen seguir el camino

### ISSUE THREAD

**Issue by cabendek** [IIC2233/syllabus#396]
Hola, tengo un problema con mis enemigos que deben seguir el camino. Al instanciarlos y crearlos en mi mapa, se mueven durante unos 3 seg y después me lanza el siguiente error: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

No estoy seguro si será un error asociado al .intersection del QRect (ya que cuando elimine esto, duro como 2 min sin caerse) o será algo asociado a mi computador MacBook Pro 2012 (10.14)

Algo extraño es que algunas veces cuando se cae me lanza otros errores como:

libc++abi.dylib: Pure virtual function called!
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

Process finished with exit code 136 (interrupted by signal 8: SIGFPE)

De antemano, muchas gracias!

**Comment by IchottMano** [comment]
Hola! 
El error SIGSEGV se debe usualmente a que por detrás python está eliminando cosas que tu aún vas a ocupar, por lo que al intentar hacer algo con ellas ya no existen y se cae tu programa. Lo mejor para solucionar este problema es revisar que estés guardando en alguna parte la referencia (el objeto instanciado) en alguna parte concreta, como por ejemplo una lista de enemigos en alguna parte.
Con respecto a los otros errores, SIGABRT en PyQt5 se da usualmente cuando el sistema operativo por alguna razón elimina uno de tus threads, ya sea por algún error o que consume demasiados recursos.
Finalmente SIGFPE se refeiere a que por algún motivo PyQt5 está haciendo un error al hacer un cálculo (com por ejemplo dividir por cero), lo cual tambien bota el programa.
Para arreglar estos ultimos errores, intenta revisar en que thread exactamente se cae tu programa y ve si es que estas haciendo algo que pida muchos recursos, estás instanciando demasiados threads o por alguna razón le pides a pyqt que haga cosas raras con números.
Saludos!
