### ISSUE TITLE
Modelación de clases: Alimento y DCC

### ISSUE THREAD

**Issue by Mendez69** [IIC2233/syllabus#396]
Lo pregunto porque está en el excel y ya he avanzado mucho en el código sin hacerlos definido (no me pareció necesario)
Gracias!

**Comment by CataSudo** [comment]
Y otra duda, DCC debe heredar a Magizoologo? Lo los tratamos como clases distintas?

**Comment by lily416** [comment]
@Mendez69 y @CataSudo.

Como se dice en enunciado, uno de los objetivos de la tarea es: "Aplicar conceptos de programación orientada a objetos (POO) para modelar y resolver un problema", por lo cual ustedes tienen que ver qué elementos de la tarea son clases, cuales no son clases y qué elementos deben heredar de otros.

Saludos y éxito en la tarea 👋🐲

**Comment by Mendez69** [comment]
Pero habrá un descuento por no usar como clase cosas que ustedes consideran que lo son (a pesar de que funcione bien)? por ejemplo los alimentos. Gracias!

**Comment by lily416** [comment]
**Es difícil responder porque:**
**1. Depende por cada caso de entidad**
**2. Estaríamos deliberadamente indicando algo correcto de incorrecto previo a la entrega.**

Esta tarea se trata sobre modelamiento en base a objetos. Se corregirá en base a modelamiento de entidades, lo cual generalmente implica una clase por entidad. Si tu solución no tiene alguna clase esperada pero si está bien modelado, estará bien. Pero si no se está tomando provecho de modelamiento de objetos donde podría estarlo, entonces no corresponde a puntaje completo.

Espero entiendas 🙇
