### ISSUE TITLE
Caso borde: Barco sin mercancías

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#396]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

#### Lo pregunto, ya que mi chequeo actual es el de si un barco no tiene mercancías (único evento que se las quita es el de los piratas) no pagará a la salida, sin embargo, un barco sin mercancías de por sí bypassearía mi chequeo, y además se generaría otro problema, ya que tendría que revisar si los piratas pueden atacar a este barco sin mercancías. (No sonaría tan loco, ya que en otra issue se menciona que los piratas "roban la mercancía Y el dinero", con lo cual sí podrían robarle a un barco sin mercancía)

**Comment by matiasfernandez1** [comment]
Hola @fernandosmither. Se espera efectivamente que puedas manejar este caso al momento de cargar el archivo barcos.csv.
