### ISSUE TITLE
AC3: Uso de Ciclos If, elif, else.

### ISSUE THREAD

**Issue by mxmauoc0** [IIC2233/Syllabus#397]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### ¿Esta permitido usar if, elif, else en las funciones de la parte 2?
Encuentro complicado manejar ciertos inputs sin el uso de if, elif, else, siendo que ya utilizo map, filter y reduce...

**Pregunta extra:**  ¿¿Esta permitido usar join() para transformar una lista de comprensión que itera sobre un generador??
porque al hacer los testcases especificos no tuvo ningun problema, pero me cuestiono si el uso, aún que temporal y transitivo, de la lista por comprensión me genere problemas.

**Comment by Hernan4444** [comment]
Hola @mxmauoc0 

1. Si está permitido el uso de `if`, `elif` y `else`. Dado que eso es control de flujo, pero no implica el uso de loops o de estructuras que pueden ser reeemplazadas por un map, filter, redue.

2. Respuesta extra: Si está permitido. Igual como _hint_, la idea es pensar en usar `reduce` ahí, pero cuando hicimos la solución, tambien consideramos que alguien usara `join` y no tendrá ninguna penalización en la AC.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ

**Comment by mxmauoc0** [comment]
¡¡Gracias!! Que bueno que se puede usar if/else... En mi pregunta 2, encontre una forma alternativa de hacerlo usando map y reduce, así que estamos tiki taka. ᕕ( ᐛ )ᕗ
