### ISSUE TITLE
Crear funciones para un reduce

### ISSUE THREAD

**Issue by vaniaulloa** [IIC2233/Syllabus#397]
Hola, puedo crear un modulo con una funcion definida para usar en reduce en consultas? 

por ejemplo: 

en_otro_modulo.py.........
def funcion_x: 
.....return Y

y luego en consultas ocupar 

def aqui alguna funcion que tengo que completar(blabla):
.... resultado= reduce(funcion_x, generador, [])
.... for i in resultado:
........yield i

**Comment by TomasGMDC** [comment]
@vaniaulloa sí, sí puedes. Ojo eso sí, la función que crees debe cumplir con las reglas de programación funcional expuestas en el enunciado y discutidas en las issues. Te recomiendo revisar " #339 " para evitar tener algún problema.

**Comment by vaniaulloa** [comment]
> @vaniaulloa sí, sí puedes. Ojo eso sí, la función que crees debe cumplir con las reglas de programación funcional expuestas en el enunciado y discutidas en las issues. Te recomiendo revisar " #339 " para evitar tener algún problema.

lo revisé, pero no me había quedado claro este caso particular que pregunté. 

para re-confirmar XD, Entonces puedo hacer una funcion No-generadora, en otro modulo, para usarla como funcion en reduce, en una función generadora de consultas?

**Comment by vaniaulloa** [comment]
>  **_la función que crees debe cumplir con las reglas de programación funcional expuestas en el enunciado y discutidas en las issues._** 
Con lo anterior se refiere solamente a la que esté en consultas?

**Comment by TomasGMDC** [comment]
@vaniaulloa sobre lo primero, sí, puedes crear una función no generadora, en otro módulo, para usarla como función dentro de un reduce, dentro de una función generadora de consultas. Solo recuerda que si no es generadora, hay ciertos requisitos que debe cumplir que aparecen en la issue mencionada anteriormente, como por ejemplo, no usar for y/o while, entre otros.

Sobre lo segundo, no, toda función que se cree, ya sea auxiliar o no, debe cumplir con lo estipulado en el disclaimer para las consultas.
