### ISSUE TITLE
Errores en consulta anidadas

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#397]
Una pregunta, si tengo un error dentro de alguna consulta anidada, al momento de mostrar el error debo mostrar la consulta madre, o la sub consulta donde ocurrio el error?

**Comment by Hernan4444** [comment]
@la subconsulta
Saludos!

**Comment by pizquierdo2** [comment]
Y si ya tenemos la tarea programada para que al tener un error dentro de alguna consulta anidada, al momento de mostrar el error muestre la consulta madre, podemos explicitarlo en el readme y que se considere correcto?

**Comment by Hernan4444** [comment]
![image](https://cloud.githubusercontent.com/assets/15641721/25666805/f56594d2-2ff7-11e7-9a8d-7db624c64f9a.png)

En el enunciado se especifica que la consulta a mostrar es con el comando especifico que arrojo el error, no la consulta madre. Se te considera malo aunque lo expliques en el readme.

Saludos!!
