### ISSUE TITLE
load_database()

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2233/Syllabus#397]
Hola , no entiendo en la consulta load_database() , si solo esto lee el archivo movies.csv y lo transforma a un generador de listas, o  puedo transformar cada linea del archivo (movies.csv) en nametuple y que el generador en realidad sea nametuples de Películas.

**Comment by pcseisdedos** [comment]
Y la idea es que load_database() imprima en resultados todas las películas de la base de datos?

**Comment by valerojasm** [comment]
holaaa tb quiero saber esto

**Comment by Hernan4444** [comment]
Hola, load_database() se encarga de cargar la base de datos a su librería, el formato de como lo manejan por dentro es a su criterio, solo tienen que asegurarse que ese formato pueda se utilizado por las demás funciones que pueden hacer uso de esos datos y si yo hago una consulta `['load_database']`, esa consulta deberá imprimir en pantalla toda la base de datos de movies.csv. El formato está a su criterio.

Saludos ✌️

**Comment by Hernan4444** [comment]
@pcseisdedos debes imprimir todas. Por eso el enunciado dice que retorna el generador con las películas de ese archivo y **las demás columnas**. Si ipmrimes solamente las otras, se da a entender que no lees todo. Solo quiero destacar que la interfaz es extensible en tamaño, si lo pones más grande, se verá como corresponde.

Saludos ✌️

**Comment by pcseisdedos** [comment]
No es un problema de tamaño, es mas bien el orden
![image](https://user-images.githubusercontent.com/18387808/39605900-17f1a29e-4f09-11e8-8e59-3a5ff826fff5.png)

![image](https://user-images.githubusercontent.com/18387808/39605949-47d32b4a-4f09-11e8-9c26-b9c5c512c5b2.png)

Intenté jugar un poco agregando espacios según el largo (len) de cada línea pero no todos los caracteres ocupan el mismo espacio entonces igual no se ve como me gustaría
