### ISSUE TITLE
Duda habilidad DCC Tarea 1

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#397]
hola! cuando el DCC usa su habilidad y gana la medalla, le asigno los 20 de moral a un deportista aleatorio? , puedo no asignar y simplemente que ganen los 100 coins y tener 1 medalla extra.
saludos

**Comment by jitorcas** [comment]
Hola @sa-Appel 

En la issue #327 puedes encontrar un compilado de issues con las preguntas que ya han hecho anteriormente y sus respuestas.

Para tu pregunta, puedes leer las issues #340 y #374 . Si quedas con dudas puedes volver a preguntar!

Mucho éxito! 🥇

**Comment by sa-Appel** [comment]
@jitorcas  me quedo claro gracias! , sorry por el duplicado.
pd tienes algo de info acerca de la #391  o están discutiéndolo. Buena noche!

**Comment by jitorcas** [comment]
Ahí te respondieron! Harto éxito!! 💯
