### ISSUE TITLE
Colapso programa

### ISSUE THREAD

**Issue by fbarrosalcalde** [IIC2233/syllabus#397]
Hola! Me pasa que al vender elementos de la tienda, la ventana se cierra automáticamente como si colapsara, en cambio, cuando compro no tengo ningún problema. Será porque elegí una lista para agregar o quitar los elementos del inventario del jugador y no es la estructura de datos más adecuada? Gracias de antemano.

**Comment by gatochico** [comment]
Hola! De casualidad, ¿estás utilizando el código entregado en los contenidos para debuggear tu programa? Si no es así, lo adjunto a continuación:
```
if __name__ == '__main__':
    def hook(type, value, traceback):
        print(type)
        print(traceback)
    sys.__excepthook__ = hook

    app = QtWidgets.QApplication([])
    ventana = MiVentana(*args)
    ventana.show()
    app.exec()
```
Esto lo digo ya que es muy dificil saber la razón exacta de tu problema sin saber el tipo de error que lanza el programa. Sería conveniente que adjuntaras el error cuando quieras hacer una issue de este tipo.

Quedamos atentos!

**Comment by fbarrosalcalde** [comment]
Ahí me funcionó con lo de arriba! Gracias
