### ISSUE TITLE
Agregar widgets sobre un Qlayout

### ISSUE THREAD

**Issue by cncosta** [IIC2233/syllabus#397]
hice mi mapa con gridlayout pero para agregar otros objetos por sobre el mapa en formas de qlabels independientes al layout se abren en otra ventana aparte en ves de hacerlo sobre el mapa

**Comment by Hernan4444** [comment]
Hola, 

Creo que esto se debe a que tu qwidget debe tener el mismo parent que tu gridlayout y los widget que están dentro de la grilla. Verifica eso y nos cuentas

Saludos :v:

**Comment by cncosta** [comment]
el codigo que tengo funciona mas o menos asi:
![Captura de pantalla 2019-05-25 a la(s) 21 56 35](https://user-images.githubusercontent.com/42576884/58376378-0fb61c80-7f38-11e9-90df-4daccdfd2bea.png)

**Comment by Hernan4444** [comment]
Hola,

Los QLabel debes ponerle "self" para que sepan que ventana es su padre. Prueba poner `label = QLabel(self)`

Saludos :v:

**Comment by cncosta** [comment]
Gracias!
