### ISSUE TITLE
Argumentos para consultas solicitadas

### ISSUE THREAD

**Issue by Polea012** [IIC2233/Syllabus#397]
En el enunciado se entregan las consultas de la forma:
consulta(argumentos(s))
¿La funcion de esa consulta debe tener exactamente los mismos argumentos o puedo agregarle otros, como alguna estructura con datos previos que yo tenga preparado?

**Comment by Hernan4444** [comment]
@Polea012 recuerda que las consultas son leidas por el main.py mientras que tus funciones son creaciones tuyas de tu librería. Por lo tanto no es necesario que tengan precisamente el mismos nombre (o mismos argumentos).

**Comment by Polea012** [comment]
Ahh de acuerdo, Gracias!

**Comment by fjaraneda** [comment]
@Hernan4444 Entonces yo puedo cargar en el main.py mi estructura, y para no cargarla cada vez que hago una consulta solo la pongo como atributo?

**Comment by Hernan4444** [comment]
@fjaraneda a que te refieres con estructura? Recuerda que no se pueden usar clases. Por otro lado, no puedes modificar la gui, eso implica que **no puedes agregar atributos**. Cualquier dato precargado debe ser por parte de tu librería.
Saludos ✌️

**Comment by fjaraneda** [comment]
@Hernan4444 no me refiero a modificar los metodos de gui, sino que si por ejemplo para hacer la consulta del promedio a mi funcion le puedo agregar un atributo 'lista' por ejemplo, que reciba las personas.

**Comment by Hernan4444** [comment]
aaa si claro, puedes hacer que tus funciones reciban los argumentos que quieras mientras cumplan las restricciones del enunciado.

**Comment by fjaraneda** [comment]
@Hernan4444 bacan, gracias!

**Comment by felipecr00** [comment]
Tengo una duda que no pude encontrar en otras issues, los argumentos siempre respetan el mismo orden? 
Ej: ["pariente_de", 0, "Hernán Valdivieso"]
no es posible encontrarse con algo del estilo
["pariente_de", "Hernán Valdivieso", 0]

Saludos!

**Comment by Hernan4444** [comment]
@felipecr00 una consulta bien formada siempre respetará ese orden, en caso contrario (que estén invertidos) deberás arrojar un error de que los argumentos son invalidos.
Saludos ✌️
