### ISSUE TITLE
Animación muerte personaje

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#398]
Hola, puedo asumir que cuando un enemigo muere (sea tanto kamikaze, como normal y ya sea por muerte con torreta, explosion o muerte natural) tendrán siempre la misma animación de muerte explosiva?

**Comment by VicenteMerino** [comment]
De partida es necesario que tengan animación de explosión? Pues viendo el enunciado dice que ambos deben explotar, pero no dice nada respecto a que deban tener una animación de sprite de explosión, por lo que entiendo, con tal que desaparezcan del mapa debería estar bien o no?

**Comment by lily416** [comment]
Hola 😄 

No es necesario que animes la muerte de los enemigos, pero si quieres hacerlo queda a tu criterio cómo animarlo.

En cuanto a la animación de la explosión, esta es parte del ataque del enemigo kamikaze y como se dice en la issue #349 los ataques deben ser animados.

Ánimo y éxito con la tarea 💪 🐈🐧
