### ISSUE TITLE
Regeneración energía actual al volver o salir.

### ISSUE THREAD

**Issue by rldelafuente** [IIC2233/syllabus#398]
Hola!

Me queda una duda con la regeneración de la energía diaria. Si el usuario sale de Menú Acciones, por ejemplo vuelve a Menú inicio y después ingresa nuevamente con su usuario, ¿esto se toma como un día, se regenera energía actual al total? ¿Pasa un día para los animales (por temas de días sin alimento? O por otro lado, ¿es como ingresar hasta donde se quedó, con la energía que tenía antes?

Saludos!

**Comment by fdoflorenzano** [comment]
Hola @rldelafuente,
Es una buena pregunta, ya que no está explícito en enunciado. Sería problemático en términos de "justicia" que al volver e ingresando de nuevo se regenere la energía sin que un día pase. Así, el usuario podría ser ilimitado número de acciones sin que pase un día. Si lo pensamos, esto también aplica cuando el usuario sale del programa en cualquier punto de ejecución. Además, si te fijas, el archivo de Magizoólogos no contiene energía actual, ya que se supone que el usuario siempre ingresa con energías renovadas.

Como no está explícito, puedes resolverlo como veas apropiado, teniendo lo anterior en cuenta. Recuerda explicitar este tipo de decisiones en tu README.

Saludos.
