### ISSUE TITLE
Decimales de algunos atributos

### ISSUE THREAD

**Issue by barbarafcp** [IIC2233/syllabus#398]
Holii! Tengo una duda porque al usar random.uniform para calcular la excelencia y respeto por ejemplo, me queda un numero con muchos decimales, debería aproximarlo y dejarlo con un decimal o lo dejo tal cual? Gracias con anticipación :)

**Comment by vicentevegaulloa** [comment]
Hola @barbarafcp !

Como esto  no está explícito en el enunciado, se deja a tu criterio 😄

**Comment by cnillanes** [comment]
Hola! es necesario usar random.uniform? no se puede usar randit para calcular esos atributos?

**Comment by vicentevegaulloa** [comment]
Hola @cnillanes !

Se recomienda usar random.uniform ya que este retorna un float. randint retorna un int y no te sirve seg{un lo que se te pide en el enunciado.
