### ISSUE TITLE
Sprites Correcto

### ISSUE THREAD

**Issue by Alonsinho1** [IIC2233/syllabus#398]
Hola dudo muy corta y quizas irrelevante. Se nos evaluara que usemos el spirte correcto para los pastos? por ejemplo que en la esquina sea el pasta con forma de esquina y no un pasto generico? Que esto ahorra muchas lineas

Gracias

**Comment by lily416** [comment]
No, solo se evalúa que se distingan visualmente los distintos tipos de celdas. Las imágenes que se muestran en el enunciado sólo son un ejemplo de como se podría ver el enunciado, pero hay muchas formas en las que puedas implementar el mapa. Siéntete libre de hacerlo como más te guste :D
 
Saludos y ánimo con tu tarea 👋🍂
