### ISSUE TITLE
Graficar rango: a,b,c

### ISSUE THREAD

**Issue by josemlira** [IIC2233/Syllabus#398]
Hola!
Al momento de querer graficar por ejemplo:
["graficar",[1,2,3,4,5,6,7,8,9,10], "rango: 2.1, 3, 0.1"]
rango me genera, solo 9 elementos en vez de 10, debido a que el último elemento es 2.9000000000000004, entonces el siguiente quedaría mayor a 3 (lo que no es correcto) y por esa razón no se incluiría en mi rango, entonces para evitar que python me genere el número 2.9000000000000004 en vez de 2.9, puedo redondear al decimal 10 por ejemplo?

**Comment by Hernan4444** [comment]
@josemlira como no está bien especificado puedes redondear o dejarlo así pero recuerda especificarlo en el readme. Al menos la solución que nosotros disponemos no redondea así que tu error también deberá suceder en el nuestro. De todos modos tenemos este tema considerado al momento de corregir :+1: 

Saludos
