### ISSUE TITLE
Duda/Consejo en la aplicación del filtro en la ventana de creación.

### ISSUE THREAD

**Issue by Mikson16** [IIC2233/Syllabus#398]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, estoy teniendo problemas para la creación del filtro en el modo constructor, principalmente cuando se selecciona un filtro e intento actualizar los botones que aparecen en pantalla, se mantienen los mismos botones en la disposición inicial, algún consejo o ayuda para esto?

**Comment by Hernan4444** [comment]
Hola @Mikson16 

Como algún consejo, en la experiencia 4, usabamos 2 métodos para jugar con lo que se ve en pantalla al momento de crear y eliminar meteoritos. Exploraría por ese lado como integrar esos métodos al momento de aplicar el filtro en el modo constructor.

Saludosヾ(＾-＾)ノ
