### ISSUE TITLE
Problema ECA Semanal

### ISSUE THREAD

**Issue by ianmarcuson** [IIC2233/Syllabus#398]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Contenido

Hola, al tratar de completar la ECA semanal, no puedo acceder al website, me aparece el siguiente mensaje. Intenté también con el link directo (https://plataforma.eca.ing.uc.cl/) y recibí el mismo mensaje.
![ErrorAvanzada](https://github.com/user-attachments/assets/7c8d829d-0952-4e51-9f15-30b97e317340)

Gracias.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Hernan4444** [comment]
Hola @ianmarcuson 

Lamento la demora, lo que pasa es que dicha semana fue receso, por lo tanto no hay carga académica que reportar. Probablmente llegó el correo de "responder la ECA", pero la misma U bloqueó el acceso porque esta semana no está considerada dentro de las que la ECA espera que respondan.

Este domingo si se habilitará la ECA como es de costumbre para que puedan reportar las horas utilizadas durante esta semana.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con el curso! 🦖
Saludosヾ(＾-＾)ノ

**Comment by ianmarcuson** [comment]
Si, era eso. Ya pude responder, gracias!
