### ISSUE TITLE
Uso obligatorio de todos los generadores entregados para consultas

### ISSUE THREAD

**Issue by CKSGO** [IIC2233/Syllabus#398]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, logré realizar una consulta para la que nos daban 3 generadores, usando sólo 2. ¿Es esto legal?

**Comment by TomasGMDC** [comment]
@CKSGO o sea, de ser legal es legal. Ahora bien, debes asegurarte de que se cumplan todos los test cases. Si pudieras hacer un push de tu trabajo, o mencionar cuál fue la consulta para revisar, mejor, ya que las consultas se definieron pensando en el uso de cada generador expresado en los parámetros.

**Comment by CKSGO** [comment]
Sí, se cumplen todos los test cases. Lo logré en la consulta mismo_mes_candidato. Ya hice push de mi trabajo, muchas gracias!

**Comment by TomasGMDC** [comment]
@CKSGO efectivamente, con los datos actuales se puede lograr esa función con menos generadores. Eso sí, no te olvides que los test cases públicos no son representativos de todas las pruebas que se llevarán a cabo para revisar sus códigos, por lo que ojo con eso.

**Comment by CKSGO** [comment]
ok, muchas gracias!
