### ISSUE TITLE
Probabilidad de que ocurran los eventos especiales de los barcos

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#398]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!

¿Hay que definir un parámetro distinto para los eventos especiales de los barcos o los tres efectos especiales tienen la misma pobabilidad? Quiero decir, se debería definir un PROBABILIDAD_EVENTO_ESPECIAL o un PROBABILIDAD_EVENTO_ESPECIAL_BARCO para cada uno?

Gracias!

**Comment by matiasfernandez1** [comment]
Hola @Rerro-r, por el enunciado sólo se concidera PROBABILIDAD_EVENTO_ESPECIAL para todos los tipos de barco sin distinción. No es necesario que crees parametros para la probabilidad de cada uno de los tipos de barcos por separado. 
Saludos.
