### ISSUE TITLE
"😃" EXCEPTION - reviews.csv

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#398]
Hola, aprovecho de reabrir la issue #170 porque en la línea 113, columna 138 del archivo reviews.csv de la data grande aparece el caracter 😃, que me está arrojando la siguiente excepción:
![image](https://user-images.githubusercontent.com/37153467/39455467-def2deda-4cb6-11e8-9ef1-7db82d02ca9d.png)

Voy al archivo, busco la línea, encuentro el caracter sospechoso, lo copio, escribo ```ord('``` en el idle, ctrl + v y el idle se cierra solo.
Desde la pyshell se ve así:
![image](https://user-images.githubusercontent.com/37153467/39455501-17876040-4cb7-11e8-9794-44118ebb578b.png)
Al menos ya sé el número del caracter.
Vuelvo al idle, 
![image](https://user-images.githubusercontent.com/37153467/39455515-35d86b98-4cb7-11e8-95bb-b583ad0e23c6.png)
**¿Qué hago con eso?** (por mientras lo voy a borrar y trabajaré sin él)
**Estoy usando encoding='utf8' y el módulo csv**

El caracter visto en gedit:
![image](https://user-images.githubusercontent.com/37153467/39455598-bfc27786-4cb7-11e8-864f-a78349220879.png)

El caracter visto en bloc de notas:
![image](https://user-images.githubusercontent.com/37153467/39455663-11c4a8c4-4cb8-11e8-9896-ead6c80c52fd.png)

**Comment by IchottMano** [comment]
@jmwielandt Hola!

Intenta usando otro editor (que **no** sea IDLE) y dime si el problema persiste.

Saludos!

**Comment by pcseisdedos** [comment]
Yo estoy usando PyCharm y lo lee y lo escribe bien
![image](https://user-images.githubusercontent.com/18387808/39456255-929b332a-4cbb-11e8-84bb-9edb8693fcd4.png)

**Comment by jmwielandt** [comment]
@IchottMano 
Acabo de probar con sublime (instalación básica: sublime + package controll + python 3) y funciona bien, pero no lo uso porque me carga que me editen lo que escribo y sugieran cosas (pierdo tiempo, me desconcentra, etc) y no sé cómo quitarlo. Por eso me quedo con el IDLE.
¿Qué puedo hacer?

**Comment by IchottMano** [comment]
@jmwielandt 
No existe alguna opción para deshabilitar esas opciones?
Yo en lo personal uso pycharm el cual tambien tiene sugerencias y esas cosas, pero usualmente las ignoro y sólo al final reviso los errores que encuentra en general, lo cual me resulta muy útil y es algo que IDLE no tiene 😞 
En este caso como lo veo el problema es de IDLE, intenta ver si no funciona usando
```python
string.encode(encoding="utf-8", errors="ignore")
```

De no funcionar, recomiendo que uses Sublime o evites printear en esas situaciones.

Saludos!

**Comment by naquiroz** [comment]
@jmwielandt Yo no lo uso, pero puedes usar atom que si permite desactivar todas las opciones que tu no quieres.
