### ISSUE TITLE
Colisiones

### ISSUE THREAD

**Issue by real-Cinfante** [IIC2233/syllabus#399]
Hola,
para modelar las colisiones estoy creando QRects de espacios vacíos en donde se supone que hay una roca, casa o tienda (el mapa lo tengo dentro de una grilla y el personaje se mueve por "arriba" en su propio plano). Quería saber si hay alguna función que me permita verificar si en una coordenada especifica ya existe algún objeto (en este caso los QRects) para luego hacer que el personaje no se mueva por ahí.

Gracias de antemano

**Comment by robertov1** [comment]
Hola,

Existen métodos de Qrect que revisan si dos rectángulos se intersectan. Te podría servir para lo que quieres hacer.

En este link está la documentación de la clase Qrect, donde se explican los métodos que tiene: https://doc.qt.io/qt-5/qrect.html

Suerte!
