### ISSUE TITLE
Cantidad deportistas se pueden entrenar

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#399]
Hola!! Me surgió la duda con respecto a cuántos deportistas se pueden entrenar. En el enunciado, en la parte de menú entrenador dice que si se elige Entrenar, se debe seleccionar a un deportista para entrenar. Por otro lado, en la parte de delegaciones entiendo que el método permite entrenar más de un deportista, entonces estoy confundida :( O simplemente no tienen relación?

**Comment by amparostevens** [comment]
Hola @denisseleiva!
El método en delegaciones señala _"la delegación podrá enviar a entrenar a sus deportistas"_, pero la forma de hacerlo es eligiendo uno de ellos desde la opción __entrenar__ del __menú entrenador__.
Éxito con la tarea ✨

**Comment by denisseleiva** [comment]
buenisimoo, muchas gracias!

**Comment by denisseleiva** [comment]
Entonces Delegaciones no tiene que tener un método entrenar_deportistas?
