### ISSUE TITLE
Como hacer que un QThread sea daemon

### ISSUE THREAD

**Issue by MGilB** [IIC2233/syllabus#399]
Hola
Mi problema es que al eliminar las monedas al final de la ronda me sale un error `QThread: Destroyed while thread is still running`, y luego se me cae el programa. Puede que la solución es que los haga Daemon, pero no he encontrado el como se hace.

**Comment by JJJGGGG** [comment]
No se puede.
Tienes que parar el QThread y esperar a que se termine. Pararlo no es tan dificil: si tienes un while pones ```while continuar``` y cuando quieras pararlo seteas continuar a false.
Para esperar a que termine, haces ```thread.wait()```.
Ahora, suerte encontrando todos los threads activos en un momento jajaja
