### ISSUE TITLE
Problema duda README subido correctamente 

### ISSUE THREAD

**Issue by Bizonte28** [IIC2233/syllabus#399]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Hola, para la T0 en la corrección me dijeron que no había subido un README, sin embargo lo fui a revisar y estaba, dada esta confusión no se como verificar si un README se ha subido. Según mi repositorio el README está, con eso basta para que se haya subido correctamente?

**Comment by matiasfernandez1** [comment]
Hola @Bizonte28 revisando el push que se revisó me percaté que efectivamente en tu repositorio de la T0 hay un README pero este es igual al que se entrega como ejemplo. De seguro la persona que te reviso se refería a que tu README no estaba modificado con los datos especiales de tu tarea y por ello no se considera como válido para el ítem en que se evaluaba. Recuerda que en el README se espera que expliques los supuestos que hiciste en la tarea, el archivo que se debe correr para poder ejecutar el programa y las librerías necesarias para que esté funcione. Quizás en esta primero tarea esto último no era tan escencial pero para las siguientes saber qué librerías usaste es muy importante al momento de poder correr el programa que nos entregues. 
Saludos.

**Comment by Bizonte28** [comment]
En el readme se incluye dichos elementos. Entonces está mal la forma en que entregué las suposiciones, librerias, etc? Hay algun formato en especial que entregarlo?

**Comment by gatochico** [comment]
¡ Hola @Bizonte28 !

Lo que ocurrió es que tuvimos un problema en la T0 al momento de recolectar los README. En particular, a algunas personas que sí subieron su README a la hora no se les recolectó y por ende, pareciese que no lo hubieran subido. 

Al final la forma de asegurarte que tu README esté a la hora es que hayas hecho el _push_ antes de la hora pedida. Por lo tanto, si crees que esto pasó en tu T0 puedes solicitar recorrección para que veamos si tu README fue parte de los no-recolectador por error.

Saludos!
