### ISSUE TITLE
Función generadora id

### ISSUE THREAD

**Issue by Pipelao** [IIC2233/Syllabus#399]
Hola, espero que estén bien

Mi pregunta va con respecto a esta función que está en una ayudantía. ¿Es posible usarla para generar un id de algo que yo necesite? ya que se usa el while dentro.

De ante manos, gracias.

![tarea 3](https://user-images.githubusercontent.com/26421921/31057998-a84dd6c2-a6c2-11e7-9dba-259a42dbe0ff.png)

**Comment by Hernan4444** [comment]
@Pipelao si es soble usarla en la tarea, revisa el enunciado, sección 8.1 primer parrafo (página 13 por si acaso) Ahí está la respuesta.

**Comment by Pipelao** [comment]
@Hernan4444 sí, es sobre la tarea. Entonces si se puede usar, no había entendido que era una función generadora la de la ayudantía, gracias.
