### ISSUE TITLE
AC3: Duda sobre prohibiciones

### ISSUE THREAD

**Issue by fgarl** [IIC2233/Syllabus#399]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Las restricciones que se mencionan en el enunciado (`Ciclos for y while; estructuras de datos list, tuple,  #dict, set; cualquier tipo de
estructura creada por comprensión; y otras librerías diferentes a las dadas en los archivos base`) son solo para las funciones de la parte 2 o aplican para toda la actividad?

**Comment by Hernan4444** [comment]
Hola @fgarl 

* Respecto a las restricciones de ciclos y estructuras, estas son para la parte 2.

* Respecto a los `imports`, esto es para toda la actividad. En `notas` (página 4) esté el texto más global. Solo que en la parte 2 lo volvemos a recordar por si acaso.


Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ
