### ISSUE TITLE
instalación de Git

### ISSUE THREAD

**Issue by ebenstom** [IIC2233/Syllabus#4]
- **Windows**
- **GIT**
- Descripción del problema: no vi el video antes de instalarlo y después me di cuenta que no apreté el primer cuadrado cuando lo instalé... tengo que desinstalarlo e instalarlo de nuevo como python o basta con hacer un acceso directo de Git Bash en mi escritorio?

**Comment by Christian-Klempau** [comment]
Hola! ¿No te referirás a la instalación de Python, de la casilla "Add Python to PATH"? No me queda claro qué casilla sería necesaria para instalar Git.
