### ISSUE TITLE
Librerías permitidas/no permitidas en la T00

### ISSUE THREAD

**Issue by bimartinez** [IIC2233/syllabus#4]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:
 
> Puedo usar la librería nombre_librería para hacer explicación_de_lo_que_quiero_hacer
 
¡Recuerden especificar en su README qué librerías utilizan!
 
---

## ✔ **Librerías Permitidas**
- datetime
- os
- string
- copy
- sys.exit
- tabulate
- PyQt5
- operator
- *diccionarios*

## ❌ **Librerías Prohibidas**
- csv
- functools
- shutil
- pathlib
- pandas
- re
- numpy
- reload

## ☠️ **_Built-ins_ Prohibidos**
El uso de alguna de las siguiente funciones es automáticamente un 1,0 sin discusión. 😭
- exec
- eval
- exception (`try`/`except`)

¡Ánimo y éxito en sus tareas! 🌈🍀

**Comment by clcarrasco10** [comment]
Hola! 
Puedo utilizar numpy para trabajar los datos del archivo seguidores.csv (y probablemente post.csv también) como un array?

**Comment by benjavicente** [comment]
Puedo usar la librería `operator`, ya que [contiene attgetter()](https://docs.python.org/3/library/operator.html#operator.attrgetter), función que es [recomendada en la documentación](https://docs.python.org/3/howto/sorting.html#operator-module-functions) para sortear por atributos?

**Comment by lily416** [comment]
@benjavicente puedes usar la librería `operator`.

Saludos y éxito con la tarea 👋🐦

**Comment by cotefon** [comment]
Por que no se puede usar la librería CSV?

**Comment by lily416** [comment]
@cotefon como sale en el enunciado de la tarea, uno de los objetivos es “Trabajar con archivos de texto para leer, escribir y procesar datos”, por lo que si pudieran usar la librería `csv` no estarías logrando completamente este objetivo.

Espero entiendas, saludos :bow:

**Comment by benjavicente** [comment]
@cotefon Debe ser también porque los archivos que se entregan no son realmente `csv`. 

Los [*Comma-Separated Values*](https://es.wikipedia.org/wiki/Valores_separados_por_comas) son los archivos donde **se separan los diferentes _campos_ con comas**.

En el caso de [posts.csv](../blob/master/Tareas/T00/posts.csv), los campos deberían ser usuario, fecha y mensaje. Entonces cada línea debería tener el formato `{usuario}`, `{fecha}`, `{mensaje}`. Pero en el enunciado se menciona lo siguiente:

> Cabe notar que **el cuerpo de un prograpost puede poseer comas**, por lo que cualquier coma encontrada después de la que se utiliza para separar la fecha de emisión del cuerpo es parte de este último

Por ejemplo, la línea 26 del archivo:
`barbara1m,2018/10/07,Well, well, well, if it isn’t the feelings I’ve been trying to avoid` 
Si el archivo fuese `csv`, los campos serían `barbara1m`, `2018/10/07`, `Well`, `well`, `well` y `if it isn’t the feelings I’ve been trying to avoid` y no `{usuario}`, `{fecha}`, `{mensaje}`.

En el caso de [seguidores.csv](../blob/master/Tareas/T00/seguidores.csv), los campos son `usuario` y `seguidores`, pero los seguidores están separados por comas, por lo que cada seguidor de un usuario es un campo distinto.

En el caso de [usuarios.csv](../blob/master/Tareas/T00/usuarios.csv) simplemente no hay comas ¯\\\_(ツ)\_/¯

**Comment by lily416** [comment]
@cotefon además los que dice @benjavicente es correcto, los archivos que les entregamos no son completamente archivos csv.

**Comment by Daniel-SebastianGaete** [comment]
Se puede usar `from collections import namedtuple` ?

**Comment by anamarn** [comment]
puedo usar la librería collections para usar las queus en vez de listas para hacer un stack más bonito?

**Comment by lily416** [comment]
@Daniel-SebastianGaete y @anamarn sí, pueden utilizar la librería `collections`.

Saludos y éxito en la tarea 👋💻

**Comment by mapasche** [comment]
¿ Se pueden usar diccionarios ?

**Comment by mapasche** [comment]
El diccionario como estructura de dato, ¿ se puede usar en la tarea?

**Comment by mestuardo** [comment]
Puedo usar la librería PyQt5 para hacer una interfaz gráfica a mi gusto?

**Comment by vicenteaguero** [comment]
Buenas, ¿puedo utilizar la librería `time` para usar la función sleep()?

**Comment by lily416** [comment]
@mapasche sí, pueden usar diccionario en la tarea.

Saludos y disculpa la demora 👋🙇‍♀

**Comment by lily416** [comment]
@mestuardo puedes usar `PyQt5` para hacer un interfaz, pero no será evaluada y no puede interrumpir la corrección del ayudante, sino nos reservamos el derecho de descontar por criterio del corrector.

Saludos y éxito en la tarea 👋🎨

**Comment by lily416** [comment]
@vicenteaguero ¿para qué quieres usar la función `sleep()`?

**Comment by stgosuarez** [comment]
Hola
Puedo usar `re` para la función `search` para ver si un string contiene ciertos caracteres?

**Comment by lily416** [comment]
@stgosuarez no puedes usar la librería `re`, ya que la idea es que comprueben las _strings_ de forma manual.

Saludos y disculpa la demora 👋🙇‍♀

**Comment by tsmatus** [comment]
se puede usar numpy ?

**Comment by lily416** [comment]
@tsmatus ¿para qué quieres utilizar la librería `numpy`?

**Comment by tsmatus** [comment]
> @tsmatus ¿para qué quieres utilizar la librería `numpy`?

quiero usarla con la librería displaymenu

**Comment by lily416** [comment]
@tsmatus no puedes usar la librería `displaymenu`, ya que uno de los objetivos de la tarea es "Procesar _input_ del usuario de forma robusta, manejando potenciales errores de formato", por lo cual deben crear los menús por su cuenta.

Además de la librería `displaymenu`, ¿tienes alguna otra razón para utilizar la librería `numpy`?

De paso, estuve buscando información sobre `displaymenu` y no encontre nada, ¿podrías dejarme algún _link_ de referencia?

**Comment by amparostevens** [comment]
Puedo usar tabulate para que el imprimir los posts se vean ordenados como en una tabla?

**Comment by amparostevens** [comment]
Puedo usar `tabulate` para que al mostrar los posts se vean como en una tabla??

**Comment by bimartinez** [comment]
Hola @amparostevens!

Si puedes usar `tabulate`, pero te debo recordar que la manera en que muestras los *posts* no será evaluada, el objetivo es mostrar la información pedida de manera fácil y clara. 

Saludos y éxito!

**Comment by ficortes** [comment]
Hola queria saber si se puede utilizar la libreria reolad? la verdad no se me ocurre bien como hacer el tema de volver a tras, es decir,  si por ejemplo pongo 0 y cierro la sesion o vuelvo al inicio, que se ejecute el script de nuevo y no termine, nose si se entiende. Saludos

**Comment by bimartinez** [comment]
Hola @ficortes!

`reload` no está permitida, ya que uno de los objetivos de esta tarea es que sepan crear un menú básico y que sea navegable, le daría otra vuelta a la modelación del menú que estás haciendo.

Saludos!
