### ISSUE TITLE
¿Actualizarán material curso PyQt5?

### ISSUE THREAD

**Issue by glbello** [IIC2233/Syllabus#4]
Saludos, quería saber si actualizarán el material del curso acorde a PyQt5, ya que revisé y en los ejemplos que hay están con PyQt4 (ya intenté hacerlo funcionar con PyQt5 pero no funcionó).

De todas maneras quería aprovechar de compartir este tutorial que encontré:
http://zetcode.com/gui/pyqt5/

**Comment by indonoso** [comment]
El material del curso se irá actualizando semana a semana (ya borramos todo lo que había). En todo caso, el material de `pyqt` cambiará :)

**Comment by akaminetzkyp** [comment]
Hola! Los contenidos de este semestre se irán subiendo [aquí](https://github.com/IIC2233/contenidos). En el material de GUI se trabajará con PyQt5. Saludos!

**Comment by glbello** [comment]
Buena, muchísimas gracias :rabbit2:
