### ISSUE TITLE
descarga e impresión de contenidos

### ISSUE THREAD

**Issue by tolavarria** [IIC2233/syllabus#4]
Hola! 
Me gustaría poder descargar con el fin de imprimir los contenidos del curso ¿hay alguna forma fácil de hacerlo?

**Comment by tocococa** [comment]
Hola! Lo que tienes que hacer es usar `git` para clonar el _syllabus_ del ramo a tu computador, [puedes seguir estas instrucciones](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository) y así vas a poder ver e interactuar con los contenidos que te entregaremos. Imprimirla no te lo recomiendo porque (salvo los enunciados) no te entregaremos un archivo de texto, si no que un _Jupyter Notebook_, que incluyen código interactivo y no se aprovecha bien si está impreso (además que no son fáciles de imprimir).

**Comment by sbcorrea** [comment]
Hola @tolavarria ! porsiaca, aunque queda super mal formateado y se pierde mucho por no poder interactuar con el código, jupyter notebook admite ctrl+p
