### ISSUE TITLE
Problemas para instalar Python versión 3.7.x

### ISSUE THREAD

**Issue by luzmagurzua** [IIC2233/syllabus#4]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema
Hola, mi sistema operativo es MacOS y estoy tratando de actualizar mi versión de Python y la eliminé de mi computador (supuestamente) para instalar la versión que piden, pero al buscarla en la terminal (de ambas maneras que recomiendan) me aparece lo siguiente: 
![Captura de Pantalla 2021-03-16 a la(s) 22 14 38](https://user-images.githubusercontent.com/80796978/111400030-4200b300-86a5-11eb-914b-344663264273.png)

### Pregunta 1
Y tengo dos preguntas: 1) está desinstalado python? 2) qué versión es la que tengo? 

## Pregunta 2 
Luego, para descargar la versión que piden tampoco me quedó claro bien como hacerlo, ya que aparece "download" en la versión más reciente es una 3.9, y no sé como descargar la que piden. Perdón T_T y gracias desde ya.

**Comment by sawiiii** [comment]
Holaa!
Python lo tienes instalado y en los Macs normalmente viene por defecto las versiones 2.7.X que es la primera que te aparece, respondiendo lo siguiente, tu tienes la version 3.8.5 que es lo que te aparece al hacer "python3 -v" o tambien al usar el comando "python3" te aparecera la misma version (3.8.5). Seguramente te aparece esa porque la descargaste

Por lo que se, se usaran versiones 3.7.X, que puedes descargarla desde la pagina https://www.python.org/downloads/ , en esta pagina mas abajo te apareceran varias versiones y busca alguna 3.7.X, te va a redirigir a otra pagina donde te saldran distintas opciones de sistemas operativos, busca alguno que sea MacOs. Y al descargar una nueva version deberia cambiarse la version que tienes en el Mac, por eso despues de descargarla revisa nuevamente la version en la terminal, sino se cambió, avisanos!

Espero que te sirva, saludos

**Comment by luzmagurzua** [comment]
Muchas gracias. Lo logré hacer! Tengo una consulta más, la debo hacer por aquí o generar una nueva issue ? :)

**Comment by sawiiii** [comment]
Hola!
Si es de lo mismo puedes hacerla por acá, si es de otro tema te recomiendo otra issue de manera que cualquier otro ayudante que pueda saber la respuesta antes pueda contestartelá mas rápido y le pueda servir a alguien mas con la misma duda.

**Comment by joshelml** [comment]
hola! yo tenia la versión python 3.8, lo desinstale e instale la versión 3.7. Pero al verificar la versión me sigue saliendo python 3.8. ¿Qué puedo hacer?
Gracias!

**Comment by sawiiii** [comment]
Hola!
Prueba en el terminal del computador intenta con los comandos "python3 -V" o con "python3" , ambas te arrojaran una linea donde te diran la version. En caso de no funcionarte o tener problemas, avísanos!.
Ojala te sirva, saludos!

**Comment by joshelml** [comment]
Me sigue saliendo python 3.8.3 :(

**Comment by sawiiii** [comment]
Hola!
Posiblemente no se ha desinstalado la version 3.8.X de tu computador o puede ser que tengas mas de alguna version 3.8.x en tu computador. Elimina las versiones de Python que hayas descargado (no la 3.7) y altiro revisa en la terminal, sino se te cambia en la terminal el 3.8.x, se esta desinstalando mal.
Ojala te sirva, sino avisanos!

**Comment by robertoorrego** [comment]
Hola!
(Había hecho este issue en mi repositorio personal y no me había dado cuenta)

Llevo todo el día intentando cambiar mi versión de Python. Estoy trabajando en un Mac. He tratado todo y no lo he logrado.
Tengo la versión 3.8 y no puedo llevarla a una 3.7. Estoy intentando con Brew y Pyenv. ojalá me puedan ayudar

Gracias!
