### ISSUE TITLE
Problema al instalar PyQt4 en Mac

### ISSUE THREAD

**Issue by asdegoyeneche** [IIC2233/Syllabus#4]
Hola! 

Estaba intentando instalar el PyQt4 pero al hacerlo (a través de Terminal con Homebrew y el comando `brew install pyqt --with-python3`) me tira el error: `No available formula with the name "pyqt" `, y sugería instalar reemplazando `pyqt` por `pyqt5` (reemplazar por `pyqt4` no funcionó). Finalmente funcionó el `pyqt5` pero, ¿es lo mismo/equivalente/sirve?

Muchas gracias de antemano, saludos!

Alfredo

**Comment by andresfdezc** [comment]
Hola

No es exactamente lo mismo. ¿Puedes intentar esto?

```
brew install homebrew/boneyard/pyqt --with-python3
```

Si no funciona, ¿puedes mostrar que te muestra homebrew cuando usas `brew search pyqt`?

**Comment by andresfdezc** [comment]
Olvida lo anterior. Sí, PyQt5 sirve y es el que usaremos este semestre. Actualizaremos la wiki pronto.

**Comment by asdegoyeneche** [comment]
Perfecto muchas gracias!
