### ISSUE TITLE
Duda Readme.md T00/Ejecución

### ISSUE THREAD

**Issue by fnberrios** [IIC2233/syllabus#4]
Hola! En el archivo Readme.md de la Tarea 00 existe un apartado llamado Ejecución que dice lo siguiente:
····El módulo principal de la tarea a ejecutar es  ```archivo.py```. Además se debe crear los siguientes ····archivos y directorios adicionales:
····1. ```archivo.ext``` en ```ubicación```
····2. ```directorio``` en ```ubicación```
····3. ...
¿```archivo.py``` corresponde al archivo que nosotros desarrollaremos? y ¿Qué seria ```directorio```, ```ubicación``` y ```archivo.ext``` específicamente?

**Comment by gatochico** [comment]
Hola!

En tu `readme`, deberás cambiar `archivo.py` por el nombre del archivo que debe ser ejecutado para comenzar a correr tu tarea. A medida que tu programa aumenta en complejidad, a veces el límite de líneas permitido por archivo no es suficiente para realizar toda tu tarea y es necesario modularizar. En esos casos, tendrás múltiples archivos `.py` en tu repositorio, pero no todos iniciarán el juego al ser ejecutados e indicar cual lo hace facilitará la corrección al ayudante.

Con respecto a la segunda pregunta, todo depende de como programes tu tarea: Si, por ejemplo, para que tu programa funcione correctamente es necesario que ya exista una carpeta llamada `carpeta` en la misma ubicación que el archivo a ejecutar, debes escribirlo siguiendo el formato anterior. Deberás hacer lo mismo si es necesario crear un archivo cualquiera de antemano. Si tu tarea funciona perfectamente sin tener que crear ningún archivo/carpeta de forma previa, puedes saltarte esa parte y borrarla de tu `readme` final!

El formato del archivo `Readme.md` entregado es bastante genérico, con el fin de que puedas facilmente adaptarlo a cada tarea que hagas y puedas agregar/quitar cosas según apliquen a tu tarea o no. **No es una guía estricta de como estructurar las tareas**

Saludos y éxito programando :computer:!

**Comment by fnberrios** [comment]
Comprendo. Genial! Gracias.

**Comment by gatochico** [comment]
Pd: No cierres las issues resueltas, ya que podrían servirle a alguien más con la misma duda!

**Comment by Patodinosaurio** [comment]
Me surgió una duda sobre esto. En el caso de que yo necesite que haya una carpeta o archivo creado. Cómo indico la ubicación si quiero que esté donde mismo está el `archivo.py` principal?

1. `texto.txt` en `ubicación(?)`
