### ISSUE TITLE
Solucionar Tablero

### ISSUE THREAD

**Issue by vicenterodas** [IIC2233/Syllabus#40]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/syllabus/issues/21)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](https://github.com/IIC2233/syllabus/issues/20)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola , mi duda es la siguiente.
Cuando me piden solucionar un tablero, si este no tiene un error evidente (como los de las reglas 2, 3 o 4) siempre se le puede encontrar una solución a cómo debemos colocar las tortugas ? O puede haber algún caso en que esto por la distribución simplemente no se pueda y nosotros debemos darnos cuenta de eso.
Muchas gracias.

**Comment by jtagle2** [comment]
Hola!

Respecto a solucionar tablero, en el enunciado se pide que solucione el tablero, y si el tablero no tiene solución entonces la función retorna `None`
