### ISSUE TITLE
Tablero.py puede que printee None

### ISSUE THREAD

**Issue by Jprampad** [IIC2233/syllabus#40]
Cada vez que imprimo el tablero me aparece un None abajo de este, he revisado mi codigo multiples veces y no tengo nada con que salga ese None. Puede que sea algo del archivo, ya que no entiendo mucho lo que dice. 

Link: https://gyazo.com/998ca9d4a1de7ac9612f314a29f0a63b

**Comment by KnowYourselves** [comment]
Hola @Jprampad!

De casualidad estás haciendo `print(print_tablero(tablero))`?

Quedo atento!

**Comment by Jprampad** [comment]
Si,
Quedo atento

**Comment by KnowYourselves** [comment]
Bueno, lo que sucede es que la función `print_tablero` **imprime sola las cosas**, no es necesario que le hagas `print`.

Por ejemplo, considera la sig. función:

```python3
def test():
    print("Hola Mundo!")
```

Si ejecutaras `test()` se imprimiría `Hola Mundo`, en cambio si ejecutaras `print(test())` también se imprimiría `None`. Esto se debe a que en la segunda opción estarias imprimiendo lo que retorne la función `test`, pero esta no retorna nada, asi que el valor que te entrega es `None` y eso es lo que se muestra en pantalla. Lo mismo está pasando en tu caso.

Espero haberte ayudado!

**Comment by Jprampad** [comment]
Bueena, bacan! Gracias!!
Buena explicación
