### ISSUE TITLE
Duda Comision

### ISSUE THREAD

**Issue by Jiparavich** [IIC2233/Syllabus#40]
Hola! , tengo una duda respecto a la comisión que se le cobra al comprador ( e.g el que adquiere/compra 1.5NEC por 100.000 pesos) , esa comisión se le resta en "NEC" , o por esa cantidad de NEC gasta 100.000+100.000*comision ? 
Espero se haya entendido mi duda, gracias! #

**Comment by sebacruzd** [comment]
Hola,

La comisión se resta a la cantidad que se recibió (para el comprador y vendedor).
Por ejemplo yo vendí 1 NEC a $100.000 y la comisión era 1%, ahora en vez de recibir los $100.000 **recibo $99.000**.
A la vez, quien me compró ese NEC, en vez de recibir 1 NEC **recibirá 0.99 NEC**.

Espero que esa haya sido la duda.
