### ISSUE TITLE
Desintalar Anaconda de manera segura

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2233/syllabus#40]
Hola, para exploratorio de Computación me hicieron instalar Anaconda. ¿Cómo puedo desinstalarlo de manera segura? 
Desde ya muchas gracias!

**Comment by Pablok98** [comment]
Hola! Si con "desinstalarlo de manera segura" te refieres a que no haya problema con las dependencias depués (osea, que no tengas errores por paquetes que no funcionan) la respuesta es _depende_ . Si tienes una instalación de Python separada de Anaconda, donde instalaste todo según las instrucciones del curso, entonces no tendrás ningun problema al desinstalar Anaconda de tu computador. En el caso de que aun uses Anaconda para algo del curso, entonces tendrás que instalar cualquier paquete necesario que uses ahí en tu instalación de Python que usarás para el curso (y luego borrar Anaconda). Por último, si solo tienes Anaconda y nada más, basta con desinstalarlo y luego reinstalar Python desde la página oficial, no debería haber problemas
En resumen, no debería haber ningún problema al desinstalar Anaconda, y si tenías una instalación de Python podrás seguir usandola sin problemas.

_pd. los enviroments de Python "puro" y anaconda son independientes :)_
