### ISSUE TITLE
Duda función asegurar_ruta

### ISSUE THREAD

**Issue by juliettegramatges** [IIC2233/Syllabus#40]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda sobre la función asegurar_ruta que debemos modificar. Qué pasa si por ejemplo: quiero que las rutas desde D hasta A tengan como mínimo 2 estaciones intermedias. Y tengo algunas rutas como D -> A, y otra  D -> A -> B -> A, entre otras. Si saco el  túnel de D -> A estaría perdiendo la otra ruta …. ***¿Qué hago en ese caso, lo ignoro y saco el túnel no más?*** Saludos.

**Comment by CrisHD935** [comment]
Hola! En el caso que dices donde no existen más rutas para llegar desde D a A, dado que al sacar el túnel que tu dices resulta en que no exista una ruta mínima con 2 estaciones intermedias entonces no existe una solución y debe retornarse una lista vacía como dice en el enunciado.
