### ISSUE TITLE
Método de revisión

### ISSUE THREAD

**Issue by despipe** [IIC2233/Syllabus#40]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda respecto a la revisión de la tarea, específicamente si se revisa corriendo el programa desde el .py o si se abre en algo como visual studio y ahí se corre, porque en visual me corre todo bien, pero cuando pruebo en la consola, al momento de seleccionar visualizar el ranking, se cierra, siendo que no debería. Aun no logro entender porque sucede esto, pero mi duda es si se correrá el código en ambas o en cual de las dos. Gracias

**Comment by vicentethomas** [comment]
Hola! La forma de revisión puede depender del ayudante, pero en general se revisa a través de la consola, así que te recomiendo revisar cual es el error. 
Algo que es común en estos casos, es que la ruta hacia el archivo que quieres abrir no es relativa con respecto al `main.py`. Con esto, me refiero a que todas las rutas que utilices deben estar pensadas para que el directorio principal sea donde está ubicado el archivo con el que se corre la tarea. Por eso, revisa si en Visual Studio abriste la carpeta específica de la tarea (T0) o una carpeta superior (Por ejemplo tareas, o tu repositorio). Procura que tu workspace sea T0. 
![image](https://user-images.githubusercontent.com/80768650/185759628-d249d42e-df4b-4c10-9abb-373482f3c243.png)
(Imagen referencial de otro semestre)
Revisa si este es el error, si es así arregla las rutas para que el directorio principal sea T0. Si es otro, escríbeme y tratamos de arreglarlo! 👍

**Comment by despipe** [comment]
Holaa, si era eso, estaba tomando como ruta relativa el repositorio, muchas graciaas!!
