### ISSUE TITLE
Problema con propiedades abstractas

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2233/syllabus#40]
Hola, estaba haciendo la tarea y quise intentar utilizar propiedades abstractas. Para eso investigue y probé un par de cosas en la consola, en archivos .py y llegue a un resultado extraño. Al correr este código:
```python
from abc import ABC, abstractmethod, abstractproperty

class A:
    def __init__(self):
        self._propiedad = 0
    @property
    @abstractmethod
    def propiedad(self):
        return self._propiedad

obj1 = A()
print(obj1.propiedad)

class B(A):
    def __init__(self):
        super().__init__()
obj2 = B()
print(obj2.propiedad)
```
No ocurre ningún error, lo que debería suceder pedir la propiedad de la clase padre o al no definirla en la clase hija. Sin embargo, el output es 0 0 (las dos propiedades remiten a _propiedad de la clase padre, que tiene un valor 0. Por qué pasa esto? Mi computador tiene un error?

**Comment by KnowYourselves** [comment]
Hola @JJJGGG!

Para que `abstractmethod` funcione tu clase `A` debe heredar de `ABC`.

Espero haberte ayudado!
