### ISSUE TITLE
Dudas sobre como usar los archivos usuarios.csv, comentarios.csv, publicaciones.csv y parametros.py

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#40]
### Prerrequisitos

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, 
Según enunciado tenemos que usar archivos.csv, comentarios.csv, publicaciones.csv y parametros.py en nuestra tarea. 
Para 'bajarlos' de github, ¿se espera que se haga con git clone? ¿o se puede hacer un copy/paste y crear nosotros un archivos.csv y los demás?
Si fuera con git clone, ¿como se hace?

Gracias

**Comment by franciscares** [comment]
Hola! Puedes copiar los archivos del syllabus a tu repositorio personal y después añadirlos haciendo un git add, commit y push.

**Comment by Fernanda1232123** [comment]
Hola, 
¿como los copio a mi repositorio privado?

**Comment by franciscares** [comment]
Hola! 
seleccionas los archivos que quieres copiar del syllabus, si hiciste un clone del syllabus en tu pc debe estar ahí sino lo hiciste te recomiendo que lo hagas :). Los copias y pegas en tu repositorio personal en la carpeta que se llama T0 y luego haces git add, commit y push.
