### ISSUE TITLE
Duda archivos

### ISSUE THREAD

**Issue by fgallard** [IIC2233/Syllabus#40]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Para abrir un archivo, como por ejemplo el que tiene crear_predio(nombre_archivo) de imput, qué se hace con la Ruta? Porque si corro los testcase desde la carpeta tarea 1 (que, corríjanme si no, pero creo que es lo que hay que hacer en la tarea, correr todo desde ahí) dice que ese archivo no existe. Ahora bien, puedo ponerle /data+nombre_archivo y ahí si abre, pero no sé si se puede poner ese /data por dos razones 1. por lo de la incompatibilidad entre computadores y 2. porque lo estoy restringiendo a que el archivo debe estar en la carpeta data, lo que no sé si será necesariamente el caso en la corrección y no sé si es el objetivo de la tarea. Cómo debo tratar esta ruta? se debe expresar de una forma general o está bien restringirla a la carpeta en la que está  predios.txr? 
Gracias

**Comment by RGutierrez21** [comment]
> Hola! te recomiendo buscar sobre path.join de la librería os. Con esta función es posible crear rutas sin que haya un problema de incompatibilidad

Hola! cómo están? con respecto a esto mismo, debemos asumir que el archivo 'nombre_archivo.extension' estará sí o sí en data/?

**Comment by diegoolivares42005** [comment]
> Hola! te recomiendo buscar sobre path.join de la librería os. Con esta función es posible crear rutas sin que haya un problema de incompatibilidad
Se puede usar os.walk(os.getcwd()) para acceder a todas las rutas dentro de la ruta actual??????
