### ISSUE TITLE
"\n" en cada linea de los archivos

### ISSUE THREAD

**Issue by mc-cari** [IIC2233/syllabus#40]
Hola, es importante mantener el "\n" al final cada linea de los archivos? ya que no se especificaba su existencia en el enunciado y al comparar usuarios lo toma como un caracter adicional, por lo que falla

**Comment by Tito0906** [comment]
Holaa @mc-cari , el "\n" representa una salto de línea en el archivo, por lo que si no lo incluyes el archivo esperado será diferente a lo que se pide.  Por otro lado, para comparar el nombre de ambos usuarios existen funciones que fácilmente eliminan el "\n".

**Comment by mc-cari** [comment]
Ok, gracias 👍
