### ISSUE TITLE
Cálculo de daño

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#40]
En el enunciado sale: "Cuando una entidad ataca, la vida de la
otra entidad (ejército enemigo) se reduce según la cantidad de daño que tiene el atacante."

Donde dice "cantidad de daño" debe decir "cantidad de ataque"?
La fórmula de daño es daño = ataque o hay/puede ser otra? (lineal, polinomial, logarítmica, raíz, etc...)
Y la única variable involucrada es qué tanto ataque tenga? Se puede agregar un ponderador aleatorio y otros que dependan de, por ejemplo, la vida que le queda al atacante?

**Comment by Arcoirisky** [comment]
Hola c: 
Cuando se habla de daño se refiere a ataque O:!
Daño = Ataque

**Comment by jmwielandt** [comment]
Oka, gracias!
