### ISSUE TITLE
Problema de Git (no puedo utilizar git commit)

### ISSUE THREAD

**Issue by matiaschen** [IIC2233/syllabus#40]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

[Al momento de abrir el centro GitBash o el centro de comando, para poder enviar mis respuestas de la AF1 no me deja realizarlo,  git status me dice que los archivos estan list para el commit, pero luego me aparece un error fatal. Tratamos con :    
rm --force ./.git/index.lock
cd .git
touch index.lock
rm index.lock
rm -f .git/index.lock
git rm -f .git/index.lock
git commit -a
git commit -m '1'
mensajes que aparecieron fueron:
'fatal: Unable to create 'C:/Users/matic/OneDrive/Escritorio/Universidad Real/2021-1/Programacion Avanzada/matiaschen-iic2233-2021-1/.git/index.lock': File exists.'
'an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
Si reinicie el computador, cualquier ayuda se acepta felizmente para poder cumplir con el ramo. Gracias de antemano

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by dfloreaa** [comment]
Hola Matias,

Encontré una posible solución [aquí](https://es.stackoverflow.com/questions/26147/git-no-puede-crear-archivo)

Aparentemente debes eliminar el archivo ``index.lock`` contenido en el directorio ``.git/``, para hacerlo deberás correr el siguiente código en tu terminal:

``rm -f C:/Users/matic/OneDrive/Escritorio/Universidad Real/2021-1/Programacion Avanzada/matiaschen-iic2233-2021-1/.git/index.lock``

O bien, si tu terminal ya está en la carpeta desde donde quieres hacer el commit

``rm -f ./.git/index.lock``

Luego, deberías poder hacer el commit sin ningún problema

Espero que te sirva, un saludo! ☺🦝

**Comment by matiaschen** [comment]
Gracias!

**Comment by dfloreaa** [comment]
Recuerda no cerrar las issues que vayas teniendo, pueden serles útiles a tus compañerxs
