### ISSUE TITLE
Duda error tarea

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#40]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, 

Tengo la tarea casi lista, y la he ejecutado muchas veces sin ningún error. Hasta que la ejecuté y me sale un error de un código que me ha estado corriendo desde que partí la tarea. Cuando he llevado mucho tiempo trabajando en el mismo programa, a veces Python como que se satura (o vscode) y me tira error en algo que había estado corriendo hace rato. Me ha pasado que espero un rato y vuelve a funcionar.
Pero el error que estoy teniendo ahora me preocupa porque la entrega es el viernes, y no sé si es porque escribí algo en alguna parte en el programa que hace que me tire error en ese lugar.

Este es el error:

➜  T0 git:(main) ✗ python3 main.py
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    users = file_to_dictionary(PATH_USERS)
  File "/Users/fernandadelpinozegers/Documents/2022-1/IIC2233 PROGRA AVANZADA/repositorio privado/Fernanda1232123-iic2233-2022-1/Tareas/T0/files_handling.py", line 47, in file_to_dictionary
    usuario, contraseña = linea.strip().split(',')
ValueError: not enough values to unpack (expected 2, got 1)

Voy a subir lo que llevo de tarea a mi repositorio privado, ¿lo podrían revisar y ayudarme con lo que se pueda?

**Comment by Emiliax16** [comment]
Hola Fernanda1232123 ! El error hace referencia a la siguiente línea:

`usuario, contraseña = linea.strip().split(',')`

Puede ser que la lista linea.strip.split(',') tenga más (o menos) variables que las que estás asignando? te aconsejo hacer un print de linea.strip().split(','); si no es del estilo: `['Juan', Dasdk47']` entonces ahí debería estar el error, ya que estás asignando cada valor de la lista a sólo dos variables, usuario y contraseña. Avísame si este era error, sino para mirar tu código! Saludos 😸

**Comment by Fernanda1232123** [comment]
Ya lo arreglé. Era porque al correr el programa se me fueron agregando los usuarios que iba registrando, luego los borré pero el programa me reconocía espacios vacíos como parte de usuarios.csv que hacía que tirara error la función de abrir el archivo y convertirlo a diccionario.
