### ISSUE TITLE
Tildes en programa

### ISSUE THREAD

**Issue by notyourlasagna** [IIC2233/syllabus#400]
Hola, quería preguntar si se pueden usar los tildes correspondientes de las palabras en el código que programo para la tarea, o si usarlos puede traer algún problema a Python o algo. O si es mejor mantener todo sin tildes.

**Comment by baosse** [comment]
Holaa @notyourlasagna !
Puedes usar los tildes correspondientes sin que te tire problemas.
Éxito!✨
