### ISSUE TITLE
Personas sin ascendencia

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#400]
Hola! Pueden haber casos donde haya gente sin ascendencia? Agradecería si pudieran responderme, pues es algo que me da la sensación de que mi código no está bien.

**Comment by Arcoirisky** [comment]
Hola!
En el enunciado, el punto de excepciones dice que, en caso de que alguna consulta diera vacío, entonces esta debe levantar una excepción. Si llegara a suceder que tu programa leyera a alguna persona sin ascendencia, entonces debería de cumplirse __Not Acceptable__

**Comment by naazocar** [comment]
Si se puede, de hecho de test1 en consultas.json preguntan por la ascendencia de Henry Boys, a lo que el programa arroja Error: Not Acceptable (o sea que no tiene).

**Comment by llloyola** [comment]
Excelente! Me estaba urgiendo jajja Muchas gracias :)

**Comment by Sforrego** [comment]
@naazocar si Henry Boys no tuviera ascendencia entonces porque en resultados.txt en la consulta 5 dice Estadounidense? pregunto por curiosidad nomas :)

**Comment by naazocar** [comment]
Depende de qué archivos estés ocupando, en el primer paquete de archivos que nos dieron donde eran muchos menos genomas y sólo 8 consultas efectivamente Henry Boys tenía ascendencia. Cuando subieron la carpeta test_1, junto con los nuevos genomas y resultados, cambiaron algunos (entre ellos la ascendencia de Henry Boys, o el hecho de que ya nos sea guatón parrillero).
