### ISSUE TITLE
Limite de Archivos

### ISSUE THREAD

**Issue by LeoMo-27** [IIC2233/syllabus#400]
Hay un limite de archivos que pueda crear para la tarea o puedo hacer cuantos yo quiera?

**Comment by lily416** [comment]
Se habla sobre eso en la _issue_ #307.

Recuerden revisar las _issues_ antes de abrir una nueva, puede que tu duda ya haya sido respondida anteriormente.

Saludos y éxito en la tarea 👋🦄
