### ISSUE TITLE
captura de excepciones en main.py

### ISSUE THREAD

**Issue by mblejeune** [IIC2233/Syllabus#400]
En el enunciado al explicar la interfaz sale : "En este punto, deberas hacer uso de try/except para poder atrapar las diversas excepciones que genere la libreria.", pero en libreria se pide que "Solo se permitira que su libreria capture las excepciones definidas en este punto; capturar cualquier otra excepcion sera penalizado.", es decir, ¿aquellas que caigan dentro del tipo "Bad Query", "movie error" o "wronginput" deben ser capturadas (y levantadas obvio en la libreria) y aquellas excepciones que se levanten solas (no escribimos nosotros el raise) por el programa las debemos capturar en main.py ?? por ejemplo, un value error que no dependa de ninguna de las tres categorias anteriormente mencionadas se debe capturar en main.py, pero una vez capturada debo volver a seguir haciendo lo que se haya parado debido a este error en la libreria eliminando ese dato ? o haciendo otra cosa? 

Gracias!! :)

**Comment by sjkinast** [comment]
Tengo la misma duda y ademas quisiera agregar de que si esta permitido por ejemplo dentro de un filter  poner una funcion que con try y except ve si es posible aplicarle int() al valor y si no se puede hace except value error y en el except lanza el movie error ya que la pelicula tenia N/A.
ejemplo:
filter (lambda x: funcion(x)< 5 , movies)
def funcion(x).
try :
return int(x)
except ValueError:
raise MovieError
