### ISSUE TITLE
Duda deformar las sprites de cultivos

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#400]
Hola estaba programando el tema de que los cultivos crecieran y como las sprites de cultivos son rectangulares estaba implementando que ocuparan el espacio de más de una casilla cuando crecieran sin embargo y por accidente implemente que ocuparan el espacio de una casilla por lo que se comprimían verticalmente las imágenes el resultado es un poco feo en el estado 1 pero en el resto de estados se ve mucho más ordenado que como lo tenia pensado
Mi pregunta es si puedo hacer esto de deformar las imágenes de los cultivos o necesariamente tienen que mantener las proporciones verticales de como fueron entregadas?
Imagen del resultado:
![image](https://user-images.githubusercontent.com/48482216/66246663-16298180-e6ec-11e9-99fd-798d279c72c0.png)

**Comment by Dnpoblete** [comment]
Hola @JuaniAndres la respuesta es sí, si puedes cambiar la cantidad de celdas que utilizan las platas, siempre y cuando lo expliques en el Readme. En este caso te recomendaría aclarar que los cultivos serán de N de ancho (1 celda) y dos N de largo (2 celdas), lo importante es que quede bien explicado y utilices el parámetro N que se pide en el enunciado.

Éxito con la tarea! :corn:

**Comment by JuaniAndres** [comment]
ok muchas gracias
