### ISSUE TITLE
Advertencia sobre 'usa_metodo_prohibido' en Test Cases en Actividad 3

### ISSUE THREAD

**Issue by mVal919** [IIC2233/Syllabus#400]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Hola, muy buenas tardes.
Esta no es una duda per se, pero si una advertencia para los que estén haciendo el ejercicio y estén buscando si a alguien ya le contestaron sobre esto.
Si les sale el error de 'usa_metodo_prohibido' durante la parte 2 de la actividad y no saben porque, *fíjense que no tengan escrito el nombre de lo que podría gatillar el error*, como por ejemplo las letras 'list', 'dict', 'set', o 'tuple' en ese orden, y luego un abre y cierra paréntesis con algo dentro, aunque esté luego de un '#', porque lo va a marcar como malo.
Así que asegúrense de borrar sus comentarios en el código si no saben porque están teniendo el error, porque podría ser eso!
Eso. Ojalá les ayude, y que les vaiga bien!

**Comment by Hernan4444** [comment]
Hola @mVal919 

Muchas gracias por notar esto. Vamos a intentar mejorar (para el otro semestre) aún más el script de `metodos_prohibidos` para que no pesque comentarios.

¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ
