### ISSUE TITLE
Procedimiento tras perder todas las vidas

### ISSUE THREAD

**Issue by criism0** [IIC2233/Syllabus#400]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Holaa!, tengo una duda respecto a qué ocurre cuando se le acaban las vidas a Luigi, se debe mostrar el puntaje/cerrar el programa/dar la opcion de volver a comenzar el nivel, no me queda muy claro que hacer tras perder todas las vidas, gracias de antemano.

**Comment by MaxAl100** [comment]
Si no implementas el bonus de volver a jugar, simplemente debes reproducir el sonido correcto y luego hacer aparecer el mensaje con el nombre del jugador, el resultado del juego y el puntaje final, junto a un botón de salir. 
En caso de implementar el bonus de volver a jugar, entonces tienes que realizar lo descrito anteriormente y, junto al mensaje, en un botón aparte del de salir, debes dar la opción de volver a jugar.
