### ISSUE TITLE
Duda diagrama de clases

### ISSUE THREAD

**Issue by fsotomutoli** [IIC2233/syllabus#400]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, tengo una duda/pregunta respecto a la diagrama de clases, ¿Existe la chance de que podamos mandar el diagrama de clases junto al README en vez de mandarlo hoy antes de las 20 hrs? Siento que es mejor aprovechado el tiempo si podemos utilizarlo para programar, y dejar el diagrama de clases con plazo junto al README de la tarea.

**Comment by lily416** [comment]
Hola @fsotomutoli, espero que te encuentres bien :) 
 
Tal como se indica en el enunciado "junto a la entrega final, deberás entregar una versión final de tu diagrama que represente fielmente la modelación del problema usada en tu programa" debido a lo anterior deben entregar el diagrama de clases hoy, miércoles 28 de abril, a las 20:00. 
 
Te recuerdo que el diagrama de clases es algo que se realiza antes de empezar a programar, ya que definirá la estructura que tendrá tu programa. La idea es que utilicen este diagrama como una base al momento de programar, por lo mismo cualquier cambio que se le haga en esta etapa de la tarea debería ser menor y capaz de realizarse en el plazo de entrega que queda.
 
Espero que entiendas.
