### ISSUE TITLE
Duda uso de for

### ISSUE THREAD

**Issue by pizquierdo2** [IIC2233/Syllabus#400]
Se que hubo una issue para este tema, pero aún me queda la duda por estos tres precisos casos:

1) Puedo usar for para generar el string que retornan mis errores (habiendo procesado ya la consulta)?
2) Puedo usar for para generar el string que utilizo como argumento de la funcion add_answer?
3) Puedo usar for para escribir en resultados.txt?

Gracias!

**Comment by ofvera** [comment]
Me sumo a preguntar si puedo usar for en el testing, para demostrar que la funcion funciona con un conjunto de inputs.
Son pocos datos, pero es más cómodo escribirlo con for que escribir todos.

**Comment by andresfdezc** [comment]
![screen shot 2017-05-03 at 8 26 50 pm](https://cloud.githubusercontent.com/assets/11430184/25685598/fb652d9c-303e-11e7-9b31-77d45bd84cdc.png)

**Comment by pizquierdo2** [comment]
@andresfdezc 

Sin embargo, en la issue 285 @Hernan4444 nos dijo:

i) "el objetivo de esta tarea es que apliquen funcional y por ello nos interesa que no usen los ciclos for y while en lo que son las funcionalidades lógicas del programa pero iterar sobre las consultas para llevarlas a tu programa no es lo esencial de la tarea sino como procesar cada consulta, es por ello que se usó como ejemplo para hacer que se enfoquen en usar la materia en donde nosotros buscamos evaluar".

ii) "...con funcionalidades lógicas nos referimos a todo lo necesario para que de una consulta salga el resultado (o un error)."

Por ii) se deduce que  la escritura de los textos que conforman el retorno hacia el usuario del procesamiento lógico ya acabado (que contempla el retorno de su resultado o un error) de las consultas no es parte de las 'funcionalidades lógicas del programa'. Así, por i) tendríamos que no les interesa a aquellos que evaluan la tarea si usamos ciclos de for y while en la escritura de los textos que conforman el retorno hacia el usuario del procesamiento lógico ya acabado de las consultas. Luego estaría permitido tanto lo que pregunté en 1), 2) y 3).

Gracias

**Comment by andresfdezc** [comment]
![screen shot 2017-05-03 at 11 35 46 pm](https://cloud.githubusercontent.com/assets/11430184/25688899/43f419e6-3059-11e7-94e7-e2546773f662.png)

El objetivo de la tarea es aplicar programación funcional y todo lo que preguntaste se puede hacer eficientemente con eso. Te recomiendo intentarlo, más que arriesgarte a descuentos.

**Comment by Hernan4444** [comment]
@pizquierdo2 tal como dice andresfdeszc el objetivo de la tarea es aplicar funcional y como en el enunciado se especificó, **el uso de for y while es para la logica del programa** es por ello, siendo consecuente con lo dicho en #285, en el punto 3 es valido usar for o while porque ahí solo buscar escribir todo lo obtenido de procesar consulta en un .txt :+1: .

Sin embargo tanto lo pedido en 1 y 2 son acciones que tu `procesar consultas` debe hacer (el retorno de un resultado o de un error). El hecho que le pidamos un formato para desplegar el resultado o un error no implica que no sea parte de la lógica del programa, un detalle que debes considerar al momento de procesar una consulta es ¿como voy a mostrar el resultado o el error?  y por lo tanto la respuesta final sería:
1) No.
2) No.
3) Si.

Saludos!
