### ISSUE TITLE
Fuente del label

### ISSUE THREAD

**Issue by Balepe666** [IIC2233/syllabus#400]
Alguno sabe como puedo cambiar la fuente del texto de un label y su tamaño?? Pues cada vez que hago el setText viene el texto con la fuente por default.

**Comment by Balepe666** [comment]
Ahi me salió se hace así: 
self.label.setFont(QFont("Bahnschrift Condensed", 18))

**Comment by lily416** [comment]
Que bueno que encontraste la como cambiarlo. 😄 
Para más información puedes revisar la documentación de Qt sobre [QFont](https://doc.qt.io/qt-5/qfont.html).

Saludos y éxito con la tarea 👋 🐈🐧 
PD: Por favor no cierres las _issues_, a otra persona podría surgirle la misma duda. 😊
