### ISSUE TITLE
Supuesto generador_animales 

### ISSUE THREAD

**Issue by faresdababneh** [IIC2233/Syllabus#401]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, ¿Puedo suponer que cada vez que nos entregan generador_animales en este se encuentran todos los animales "existentes"? Por ejemplo, si junto a generador_animales nos entregan generador_votos y generador_candidatos, ¿Puedo suponer que todos los votos emitidos y recibidos son por animales que se encuentran en generador_animales, y que en este también se encuentran todos los animales candidatos?

Gracias!

**Comment by leonidasmontes** [comment]
Tengo la misma duda. ¿el id de un candidato siempre estara en generador_animales?

**Comment by Jeremiah-PHP6** [comment]
¡Hola! En el ejemplo que diste, los atributos "id_animal_votante" y "id_candidato" corresponden a los atributos id de las namedtuples Animales y Candidatos, respectivamente. Por lo tanto, cada voto debe hacer referencia a animales y candidatos preexistentes en cada generador. Así que sí, puedes asumir la existencia de estos.

Si te llega a aparecer cualquier tipo de inconsistencia en los tests referente a este tema, no dudes en hacérmelo saber por este medio. ¡Saludos!

**Comment by M4TI4D4CZ** [comment]
Hola! esto se puede asumir para todos los generadores?  por ejemplo, si agarro el id_local de un voto, podree encontrar si o si, una forma de llegar a su distrito?

**Comment by Jeremiah-PHP6** [comment]
@M4TI4D4CZ Correcto Matías, estos atributos hacen referencia a los id de otras tablas (por ej. Votos.id_local corresponde a Local.id_local). La única excepción sería Candidatos.id_candidato, el cual NO hace referencia a Animales.id.

Espero haber respondido tu duda, saludos.

**Comment by M4TI4D4CZ** [comment]
Como asi? o sea, el id de un candidato no corresponde a su id de animal? si no es asi, como se supone que accedamos por ejemplo a su fecha, ya que estos dos son los unicos identificadores unicos que poseen ambas tuplas, o sea, todos los otros datos del candidato no son suficientes para llegar al resto de la infomaci'on que existe en el generador de animales.

**Comment by Jeremiah-PHP6** [comment]
@M4TI4D4CZ ¿En qué función necesitas la fecha de nacimiento del candidato?

**Comment by M4TI4D4CZ** [comment]
en la funcion mismo_mes_candidato....

**Comment by Jeremiah-PHP6** [comment]
@M4TI4D4CZ Hubo una incosistencia al crear los atributos Animales.id y Candidatos.id_candidato. Donde NO se cumple la igualdad es en la función `porcentaje_apoyo_especie`; para el resto de funciones en la tarea, sí se asume que Animales.id = Candidatos.id_candidato.

Espero haber sido claro, saludos.
