### ISSUE TITLE
Formato "rango:a,b,c"

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#401]
Hola!

En el enunciado dice que el comando `graficar` puede ser llamado con la opción `rango:a,b,c`, siendo `a` y `b`  los extremos de un intervalo y `c` el step. Según el enunciado, el formato de este string es sin espacios. Sin embargo, en el archivo `resultados.txt` aparece escrito con un espacio después del `:` (`'rango: -3,5,0.1'`). ¿Cuál es el formato que deberíamos utilizar?

Saludos!

**Comment by Hernan4444** [comment]
Ambos formatos son validos, cuando se les entrega el formato es para indicar que la opción tendrá un `titulo` que será **rango** seguido de `:` que separa el titulo de argumentos y por ultimo 3 números separados por comas `,`. La idea no es que tengan un código especifico que ante un espacio se caiga sino que pueda soportar las distintas formas de anotarlos mientras cumpla el formato de `titulo: argumentos separados por comas`. De todos modos, eso debería ser un pequeño detalle a corregir para ignorar los espacios.

Saludos!!

**Comment by akaminetzkyp** [comment]
Perfecto. Muchas gracias!
