### ISSUE TITLE
time dentro de un Qthread

### ISSUE THREAD

**Issue by mjgarrido1** [IIC2233/syllabus#401]
puedo utilizar time.sleep dentro del run de los enemigos que heredad de un qthread??estoy intentando utilizar qtimer, pero no me funciona:(

**Comment by Hernan4444** [comment]
Hola,

Tal como he comentado en otras issues, "lo mejor en computación ante estos casos es probar". Te recomiendo tomar un código sencillo del material (carpeta extra) donde hay Qthread implementados y poner time.sleep para ver como resulta. Si mi memoria no falla, debería haber un código en la carpeta Extra que justamente es un QThread y usa sleep, podrías revisar ahí, pero insisto, en computación es mejor probar si algo se puede hacer o no.

Saludos ✌️
