### ISSUE TITLE
Typing y properties en diagrama de clases

### ISSUE THREAD

**Issue by juanesjeep** [IIC2233/syllabus#401]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### ¿Se puede hacer typing en ls metodos de las clases?

hay que evitar poner lo o no se tendra en cuenta?
ejemplo

**metado_(Pesona, int): None**

y las properties que tengan getter y/o sette ¿se tienen que escribir de alguna otra manera
en especial como esta en la AS1?
![image](https://user-images.githubusercontent.com/79773721/116460801-daaa5700-a83d-11eb-832e-276c65d8ec7b.png)

**Comment by Ignacioislae** [comment]
cps

**Comment by DomingoCarvajal** [comment]
Hola @juanesjeep!

Está bien definir los tipos de los parámetros en los métodos. Y si, puedes denotar las properties de la misma manera que muestras.
