### ISSUE TITLE
Python no encuentra el archivo magizoologos.csv

### ISSUE THREAD

**Issue by drosselot** [IIC2233/syllabus#401]
Hola, cuando trato de cargar el archivo de los magizoologos en python me tira el error de que no existe el archivo 'magizoolos.csv'. Están en la misma carpeta y copie y pegué el nombre en mis parametros para asegurarme que no lo escribí mal.  No entiendo porque me tira este error, trate de googlearlo pero todo lo que me sale es sobre paths, pero están en la misma carpeta por lo que no debería importar.

**Comment by lily416** [comment]
Hola @drosselot, ¿cómo estás ejecutando tu código? ¿puedes pegar el error completo que te sale cuando tratar de ejecutar tu código?

**Comment by drosselot** [comment]
Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: 'magizoologos.csv'
  File "C:\Users\dross\Desktop\Ingenería Civil\Programación Avanzada\Repositorio\drosselot-iic2233-2020-1\Tareas\T01\Cargar.py", line 45, in cargar_magos
    with open(Parametros.PATH_MAGIZOOLOGOS, "rt", encoding="utf-8") as archivo:
  File "C:\Users\dross\Desktop\Ingenería Civil\Programación Avanzada\Repositorio\drosselot-iic2233-2020-1\Tareas\T01\Cargar.py", line 94, in <module>
    cargar_magos()

En parametros lo tengo guardado como PATH_MAGIZOOLOGOS = 'magizoologos.csv'

**Comment by lily416** [comment]
¿Desde qué directorio estas ejecutando tu tarea? Normalmente este error sucede cuando ejecutan su tarea desde un directorio que no es `\T01`.

**Comment by drosselot** [comment]
Desde la carpeta de la tarea 1, abro con vsc y lo corro. No se si es es correr desde ese directorio.

**Comment by drosselot** [comment]
Era eso, no se porque se ejecutaba en la carpeta de Tareas y no en la carpeta T01. Pero ahora me funciono. Muchas gracias!!!
