### ISSUE TITLE
Deportistas iniciales de las delegaciones

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#401]
Holaa!
En el archivo `delegaciones.csv` hay información acerca de los deportistas "iniciales" que tendrá cada delegación. Esos deportistas iniciales siempre serán los mismos para ambas delegaciones? o puede ocurrir que inicien con otro plantel?

**Comment by jitorcas** [comment]
Hola! @Gsalinas1506 

No siempre serán los mismos deportistas para cada Delegación, estos pueden variar. 

Mucho éxito! 🥇

**Comment by tsunayoshi21** [comment]
Se puede asumir que siempre se partirá con al menos 1 deportista por delegación?

**Comment by jitorcas** [comment]
@tsunayoshi21 

Siempre serán 5 por delegación!
