### ISSUE TITLE
Programación Funcional - Uso de for o while

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233/Syllabus#401]
# Programación Funcional - Uso de `for` o `while`

### Función generadora

Una función generadora se caracteriza por tener `yield` en vez de `return`. Si tienen uno o más _loops_ con `for` o `while` dentro de estas funciones, todo bien :+1:. 

Ejemplos  de funciones generadoras:
```python

def identificador():
    n = 0
    while True:
        yield n
        n += 1
        
def eliminar_palabras(frase, letra):
    # Solo devuelve las palabras de la frase que no
    # tenga la letra indicada y finalmente devuelve
    # la lista con todas las palabras no consideradas
    eliminadas = []
    for palabra in frase.split(" "):
        if letra not in palabra:
            yield palabra
        else:
            eliminadas.append(palabra)
    yield palabra
    
frase = "hola que hace"
letra = "e"
lista = [x  for x in eliminar_palabras(frase, letra)]
print(lista)
> ['hola', ['que', 'hace']]
```

Pueden notar que dentro de una función generadora si está permitido interactuar con estructuras de datos o variables junto a un `for` o `while`

### Expresión generadora

Se construyen de la misma forma como una lista por compresión, pero retorna un generador. Una expresión generadora solo puede tener `for`. Si están usando esto, Todo bien :+1: .

Ejemplo  de funciones generadoras:
```python
números_cuadrados = (x**2 for x in range(100)) 
#generador, se itera una vez y luego se pierde
```

### Listas o `set` por compresión

Estas son estructuras creadas a partir a través de un loop interno. Se contruyen de igual forma que la expresión generadora, pero cambia el tipo de parentesis que ocupa y lo retornado.

Ejemplos
```python
números_cuadrados = [x**2 for x in range(100)]
# lista, se conserva en la memoria
 
números_cuadrados = {x**2 for x in range(100)}
# set, se conserva en la memoria
```

### :warning: ¿Qué estructura de programación no es funcional? 
Utilizar la lista o set por compresión para editar una variable o estructura.

Ejemplo
```python
pares = []
números_cuadrados = [pares.append(x) for x in range(100) if x%2==0]

# pares tendrá los x pares y números_cuadrados tendrá null
```
Solución funcional
```python
# Mejor hacer
pares = [x for x in range(100) if x%2==0]
```

### Simular `forEach` :eyes:

Uno de implemetaciones que no tiene Python es el `for_each(función, iterable)` el cual se encarga de ejecutar la función indicada una vez por cada elemento de la lista. 

Una forma de hacerlo era utilizando `list(map(...))`
```python
imprimir = list(map(print, [1,2,3]))
> 1
> 2
> 3
```
Lo anterior logra hacer `print` de forma inmediata, situación que no pasaría si solo haces `map(print, [1,2,3])`. Aunque se puede y es funcional, ¿Qué hacemos con una lista de 3 `null`? **El cuarto requerimiento puesto en la tarea apunta a que puedan hacer esto** de forma que no generas los `null`

:warning: si no estás respetando lo indicado a continuación, **está mal**.

Las restricciones de `forEach` en Python son:
1. No retorna nada.
1. No edita cosas que está fuera del `forEach` (no tiene efecto colateral de otras variables)
1. No edita la lista (sin efecto colateral del input)
1. Aplica de inmediato la función a los elemento, no es un generador.

Una forma de implementar esto es:
```python
def for_each(function, iterable):
    for elem in terable:
        function(elem)
```

Y ustedes llaman esta función cuando sea necesario, como:
```python
a = for_each(lambda x: print(x), [1,2,3,4,5]):
print(a)
> 1
> 2
> 3
> 4
> 5 
> null
```

Dado lo anterior, lo siguientes casos de uso de `for` o `while` están **totalmente prohibidos**

```python
contador = 0
for elem in iterable:
   if condicion(elem):
       contador += 1
        
# Editando un dato fuera del for. 
# forEach no sería capaz de hacer esto.

for index, elem in enumerate(iterable):
    if condicion(elem):
        iterable[index] = otro_valor
       
        
# Editando el iterable. 
# forEach no sería capaz de hacer esto.

```

**Comment by Unknomads** [comment]
Puedo usar un loop dentro de un diccionario por compresión?

**Comment by Hernan4444** [comment]
@Unknomads si te refieres a crear un diccionario por compresión, tal como se crean los `set`, pero definiendo la key y value, si puedes :+1: 
@Drpinto1 ante esa situación, si es posible. :+1: 

Saludos :v:

**Comment by joaquineichholz** [comment]
En load_database() quiero juntar la informacion de las diferentes bases de datos, puedo usar un for para agregar elemnentos a un orderdict antes de retornar un generador? Seria algo de la siguiente manera 

`for x in oderdict1: 

     x.update(({'key': 'list(map(lambda x: (x['key']), (filter(lambda x: x['id'] == k['id'], orderdict2))))})
     yield x`

**Comment by Hernan4444** [comment]
@joaquineichholz si es una función generadora, el `for` si está permitido, pero te recomiendo revisar las librerías permitidas. Hay una que hace justo lo que quieres 👀.

Saludos ✌️

**Comment by joaquineichholz** [comment]
@Hernan4444  lo que hice es considerado una función generadora? , no encontré  que librería me sirve 
gracias!

**Comment by mblejeune** [comment]
Hola! puedo hacer esto ?
lista = [linea.strip() for linea in lineas]
