### ISSUE TITLE
Comparaciones del Testing

### ISSUE THREAD

**Issue by leolivares** [IIC2233/Syllabus#401]
Para realizar los distintos tests, para las distintas consultas, ¿debemos usar como base las respuestas que esperamos utilizando los archivos .txt que nos entregaron (test_1)? O debemos tener un archivo de genomas propio para la parte de testing
Mi pregunta surge debido a que puede que la corrección del código principal se realice con otros genomas (es decir, otro archivo). Gracias

**Comment by Arcoirisky** [comment]
Los casos Testing puedes simularlos de la forma en que más estimes conveniente. Usando setup puedes hacer todos los archivos que quieras de la forma que quieras y con teardown los puedes eliminar. Y listo~ :D Puedes hacer los casos con los códigos que quieras. Mejor aún con test_1 ya que tienes las respuestas ahí mismo.

**Comment by leolivares** [comment]
@Arcoirisky Gracias! Dejare especificado en el readme los archivos que usaré.

**Comment by jerosalazar** [comment]
@Arcoirisky si yo importo los datos en cada consulta y no al principio, como dijeron en otra issue que era mejor, es necesario que sobreescriba el setUp igual? porque me pareciera que no es necesario

**Comment by Arcoirisky** [comment]
¿Te refieres a hacer uso del setUp y tearDown?  Porque si no me equivoco, es pedido en el enunciado. 
Si te refieres a que debas modificar el setUp para cada Test, eso pasa automáticamente. 
¿Le achunte a tu pregunta? O:

**Comment by Arcoirisky** [comment]
Sep. Punto 5 del enunciado. Lo que dice el enunciado es Ley y debe cumplirse O:
