### ISSUE TITLE
hora del juego

### ISSUE THREAD

**Issue by F-arellano** [IIC2233/syllabus#401]
el flujo del tiempo en el juego esta completamente separado del tiempo real? no se si al comenzar el juego deberia comenzar con la hora actual, tampocode  si debe seguir un paso de "1 segundo en la vida real, 1 en el juego", o si puedo cambiar esta proporcion.

**Comment by Dnpoblete** [comment]
Hola @F-arellano respondiendo tus dudas por parte, en cuanto a si el juego esta separado del tiempo real la respuesta es sí, y con respecto a si debe partir con la hora actual no es necesario, pero en el caso de que quieras hacerlo lo puedes hacer y explicar en el Readme. Lo importante es que debes tener en consideración que debes tener un contador de los días que han transcurrido y las horas. Y con respecto a la última duda el enunciado dice lo siguiente:

> "El juego debe poseer un reloj interno que controle el flujo del tiempo, es decir, las horas del día y así el progreso de ciertos eventos: crecimiento de las plantas, el pasar de los días, etc. La rapidez con la que pasa el tiempo (cuántos segundos dura un día, por ejemplo) queda a tu criterio y debes definirlo como un parámetro."

Debido a lo anterior la respuesta es que el tiempo lo debes definir como un parámetro que puedes utilizar como un segundo de la vida real como dices, pero el programa debe ser capaz de funcionar cuando se cambie el valor al parámetro.

Espero haber respondido tus dudas, si algo no queda claro puedes comentar esta issue para poder ayudarte. 

Éxito con la tarea! :clock1: :seedling:

**Comment by burgosibarra** [comment]
Hola!
En cuanto al parámetro de tiempo de germinación de las semillas, corresponde a un tiempo en la realidad o a un tiempo en el juego?
Desde ya, muchas gracias!

**Comment by Dnpoblete** [comment]
Hola @burgosibarra, con el respecto al parámetro de tiempo de germinación de las semillas, corresponde a un tiempo del juego. Como tip en el juego siempre vamos a hablar del reloj interno que ustedes crean, nunca va a ser necesario usar el reloj actual.

Éxito con la tarea! 🕐 😄
