### ISSUE TITLE
Compilado MIDTERMS anteriores

### ISSUE THREAD

**Issue by JosefaATP** [IIC2233/Syllabus#402]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Contenido

Hola! Cómo están?

Donde puedo encontrar algún compilado con midterms anteriores de las que pueda estudiar para el midterm de la próxima semana?

Gracias😁

**Comment by Hernan4444** [comment]
Hola @JosefaATP 

Lamento informar que no existe un compilado. Sino que en cada semestre donde hubo evaluación escrita, está el enunciado y la solución publicada. En este sentido, puedes acceder al [Readme del Syllabus](https://github.com/IIC2233/Syllabus?tab=readme-ov-file#semestres-anteriores) que contiene los links a cada Syllabus pasado, y ahí ver desde el 2023-2 al 2024-1  los enunciados.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con el curso! 🦖
Saludosヾ(＾-＾)ノ

**Comment by JosefaATP** [comment]
Perfecto, gracias!
