### ISSUE TITLE
# Diagrama de clases (propuesto)

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233/Syllabus#402]
# Diagrama de clases (propuesto)

![](https://i.imgur.com/WzA6Ute.png)

**Disclaimer**
La modelación de un programa de software, y en particular el de la tarea, tiene muchas versiones distintas y formas de entender la relación entre las entidades presentes. **En esta propuesta se explica una de esas formas.**

En la última sección de este post se explica cómo mandar a recorregir.

## Justificación de utilizar herencia en Raza
Para empezar, el enunciado especifica que todas las razas poseen atributos en común, un grito de guerra con un mensaje común de todos y una personalizado por cada raza. En base a lo anterior, para no repetir los atributos, se pensó que cada tipo de raza heredara de Raza y dentro de las subrazas sobrecargar el método de habilidad especial.

Utilizando el modelo anterior, el Archimago era una multiherencia de Asesino y Aprendiz para que su habilidad especial sea un llamado a las habilidades de las otras dos clases.

## ¿Porqué ejercito es una clase?
Como se indicó durante la elaboración de la tarea y en el enunciado, cada soldado se elabora con un ataque y vida al momento de generarlo (instancearlo) y este se mantiene durante todo el juego y solo cambia cuando:
1. Se gana una batalla 
2. Cierras el programa y lo vuelves a cargar.

Es por ello que se pensó al ejercito como una clase.

**¿Porqué no sirve tener solo la cantidad?**

Si solo permites que la raza guarda la cantidad de soldado o magos, no podrás saber el ataque de este, sino que tendrás que hacer un `random` cada vez que tengas una batalla, lo cual implica que un solado puede tener diferente vida y ataque durante el mismo juego.

## ¿Porqué edificio es una clase?
Esto es porque cada edificio cuanta con una vida, la cual se va reduciendo con el meteoro, un costo de recursos y en el caso de la torre, esta contaba con un daño que se utilizaba en la batalla. Aunque se podrían pensar como atributos del planeta, exigía tener mínimo 5 atributos más en el planeta `(costo_torre, costo_cuartel, vida_torre, vida_cuartel, daño_torre)`. Por orden del problema, lo mejor era representarlo como clase.

## Recorregir modelo
Si tu modelo **NO** es como el de  esta pauta propuesta, pero consideras que tu modelación del problema cumple con los estándares OOP, es correcta y explica las relaciones entre las entidades, puedes mandar a recorregir. Para eso tienes que responder explícitamente las preguntas:
1. ¿Por qué está bien modelado el problema en tu diagrama?
2. ¿Qué relación modela cada conexión en tú diagrama?

Recuerda que que un programa funcione es muy distinto a que esté bien modelado. No se aceptarán apelaciones solo porque funciona correctamente.

**Comment by jmwielandt** [comment]
Llené el form el otro día
¿Lo mando de nuevo?

**Comment by Hernan4444** [comment]
@jmwielandt si por favor.

**Comment by mblejeune** [comment]
la recorrección de esto también es hasta el viernes (que se envia el main.py de las funcionalidades no revisadas de la t01 por no estar en consola)? es decir, se envia en conjunto en el mismo formulario de recoleccion que aparece en la pagina oficial del curso verdad? muchas gracias!!

**Comment by Hernan4444** [comment]
@mblejeune efectivamente 👍 

Saludos ✌️
