### ISSUE TITLE
problema con commit

### ISSUE THREAD

**Issue by SugarFreeManatee** [IIC2233/syllabus#402]
Hola! 
por accidente hice un commit en vez de hacer add y ahora no puedo addear nada. me aparece el error:
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
ayuda porfavor :(

**Comment by Arcoirisky** [comment]
Hay varias opciones, la más fácil es guardar en otro lado los cambios que no tengas guardados ya en github, borrar tu repositorio local (suprimir la carpeta), volver a clonar y no equivocarse de nuevo.

Las otra opción es volver al pasado pero si temes perder tu avance o tener otro error, considerando la hora, optaría por la primera opción.

Avísame cómo te va

**Comment by SugarFreeManatee** [comment]
Me funcionoo muchas gracias <3
