### ISSUE TITLE
Heredar una ventana a otra

### ISSUE THREAD

**Issue by bpeirano1** [IIC2233/syllabus#402]
@Hernan4444 Mi ventana de juego es solo una clase y esta llego a las 400 lineas, puedo crear una nueva clase de ventana que herede a mi ventana de juego y seguir trabajando en esta, es legal ?

**Comment by Hernan4444** [comment]
Hola, 

Es legal, pero en términos de una buena modelación, no es correcta, aunque para esta tarea no estamos exigiendo eso. Aunque puede ser que para la T03 si.

Saludos :v:
