### ISSUE TITLE
tílde en "gemelo_genético"

### ISSUE THREAD

**Issue by caespinoza5** [IIC2233/Syllabus#402]
En el enunciado, aparece que la función es "gemelo_genético". Sin embargo, en consultas, aparece "gemelo_genetico". Pregunto cuál de los dos es el correcto y el que se utilizará al momento de evaluar, para así revisarlo en la excepción de Bad Request (ya que, por ej, valor_característica sí tiene tilde).

**Comment by Arcoirisky** [comment]
Hola~
Usaremos los nombres que aparecen en el enunciado :D

**Comment by caespinoza5** [comment]
¡Gracias! En ese caso creo que sería importante actualizar los archivos consultas.json de la tarea para que después no haya confusión al momento de corregir la tarea.

**Comment by Hernan4444** [comment]
@caespinoza5 acabo de agregar los tildes. Muchas gracias por avisar 👍

**Comment by rihanuch** [comment]
@caespinoza5 , segun lo que entendi, segun la issue #372 también se pueden usar sin tildes siempre que lo pongas en el readme 🤔

**Comment by Arcoirisky** [comment]
A lo que se debe de referir @rihanuch es que tus funciones pueden ser con nombres diferentes pero, cuando se pida una consulta con tilde (**Según el enunciado**) y es pedida sin tilde, entonces debe levantar error.

**Comment by rihanuch** [comment]
@arcorisky , no me referia a eso, me referia a usar las funiones de consulta sin tildes y sin ñ (por eso mismo pregunte en la otra issue lo mismo), pero si tienen que tener tilde al hacer la consulta entonces la issue #372 no es valida (?)

**Comment by Hernan4444** [comment]
@rihanuch lamento la confusión, pero nosotros entendíamos que querías programar tus funciones sin tildes ni ñ (EJ: `def gemelo_genetico:`) y que estabas utilizando `hasattr` para facilitar la pega. Lo anterior fue lo que permitmos, pidiendo que especificaras en el readme (el uso de `hasattr`), pero las consultas en `consultas.json` si iban a llegar con tildes  y ñ (por algo editamos la interfaz para poder leer tildes)

**Comment by rihanuch** [comment]
Ahhh perfecto! Ya entendi! Muchas gracias!😁😄
