### ISSUE TITLE
Feedback Tareas [Administrativa]

### ISSUE THREAD

**Issue by BibarelUsedFly** [IIC2233/Syllabus#402]
Hola, tendo un dilema respecto al feedback de mi tarea 01.
al momento de ser corregida, no se me entregó ninguna razón del por qué de mis puntajes.
la sección "Comentarios Generales" está en blanco y la casilla de comentarios de cada punto solo contiene un guión.
Mandé a recorregir la tarea por esto, pero a la entrega de las recorrecciones mi nota sigue igual y los comentarios (la ausencia de ellos) también.
Me gustaría saber qué ocurre.

Gracias de antemano.

**Comment by indonoso** [comment]
Esta consulta es particular. Envía un mensaje por el form de contacto.
