### ISSUE TITLE
Uso de (x, y) en diccionarios y map

### ISSUE THREAD

**Issue by cataruze** [IIC2233/Syllabus#402]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, quería saber si se podía realizar lo siguiente:
1. Para diccionario: {i: (i.x, i.y) for i in generador)
2. Para map: map(lambda x: (x[0].n, x[0].n), tupla)
Muchas gracias de antemano.

**Comment by TomasGMDC** [comment]
@cataruze te recomiendo revisarlo con el script que se subió recientemente, dado que será el utilizado para revisar que se cumpla con las reglas de programación funcional.
