### ISSUE TITLE
Definir bloques como entidades

### ISSUE THREAD

**Issue by Fopazov** [IIC2233/Syllabus#402]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. Mi duda es bien corta. ¿Supongo que se puede definir a los bloques (ej: pared, fuego) como entidades, o estoy mal? 
Me entro la duda porque comencé a hacer la ventana de constructor y se expone en el filtro las opciones entidades y bloques. Sin embargo, al inicio del enunciado se dice: 
"opción de construir diferentes mapas a partir de 6 tipos de Entidades". 
Pregunto simplemente para asegurarme de no tener problemas. 
Saludos

**Comment by jtlledo** [comment]
Hola @Fopazov ! Si, puedes definir los bloques como entidades, es decir, definir clases que modelen su funcionamiento. De hecho, es lo recomendado para que tu código sea más ordenado y legible.
