### ISSUE TITLE
UML: acceder a datos en de la clase "superior" en relación de composición

### ISSUE THREAD

**Issue by furcelay** [IIC2233/syllabus#402]
Hola,
Mi duda es respecto a cuando se tiene un diagrama como el siguiente:
![class-diagram](https://user-images.githubusercontent.com/61999313/79024842-223a4400-7b52-11ea-9f0c-82e0f1a68381.png)
Mi problema es cómo una instancia `Usuario` que corresponde a `usuario_actual` debe obtener información de `Main` de la forma correcta, por ejemplo obtener la lista de otros usuarios en `Main`. 

Poniendo un ejemplo en particular, si el `usuario_actual` quiere saludar a un `usuario_x` ingresando como `input` el nombre `usuario_x`, definiendo el método `saludar_otro_usuario` (en `User`) como:
```python
def saludar_otro_usuario(self):
    nombre = input("Ingrese el nombre del usuario a saludar: ")
    if nombre in nombres_usuarios:  # aquí el problema: User no tiene nombres_ususarios
        print(f"Hola {nombre}!")
``` 
Se me ocurren dos formas de resolverlo, pero no sé si están bien:

1. Que `Usuario` agregue a `Main`:
![class-diagram (1)](https://user-images.githubusercontent.com/61999313/79025095-d76cfc00-7b52-11ea-8e2e-0d5b6d19a21f.png)
Entonces `saludar_otro_usuario` sería:
```python
def saludar_otro_usuario(self):
    nombre = input("Ingrese el nombre del usuario a saludar: ")
    if nombre in self.main.nombres_usuarios:
        print(f"Hola {nombre}!")
``` 
2. Que `Main` también tenga un método `saludar_otro_usuario`:
![class-diagram (2)](https://user-images.githubusercontent.com/61999313/79025424-a7722880-7b53-11ea-806e-9e2c01680343.png)
Entonces en `Main`:
```python
def saludar_otro_usuario(self):
    nombre = input("Ingrese el nombre del usuario a saludar: ")
    if nombre in self.nombres_usuarios:
        self.usuario_actual.saludar_otro_usuario(nombre)
``` 
En `Usuario`:
```python
def saludar_otro_usuario(self, nombre):
    print(f"Hola {nombre}!")
``` 

3. ¿Alguna forma mejor?

Muchas gracias!!

**Comment by fdoflorenzano** [comment]
Hola @furcelay,

Muy buena pregunta, se nota que estás aplicando los contenidos en términos de modelación y cuestionándote distintas modelaciones. Primero quiero mencionar que los diagramas y códigos corresponden apropiadamente en ambos casos que mostraste.

Ahora, la pregunta a la que apuntas podemos verlo como una decisión de modelación que debes tomar como desarrolador(a). Específicamente, es una decisión de asignación de responsabilidades y jerarquía de entidades. 

Aquí, tu usuario puede saludar a otro mediante a un método, pero esa acción necesita información sobre la totalidad de los usuarios para realizarse. Describes bien las alternativas que tienes teniendo esas dos clases, y la decisión al final se reduce a si tiene sentido en términos de modelación.

Para el caso 1: ¿tiene sentido la entidad `Usuario` tenga acceso a una entidad `Main` y potencialmente acceso a todos sus métodos? Por su nombre, me imaginaría que `Main` maneja a `Usuario` y es mayor en la jerarquía de entidades del programa.
Para el caso 2: ¿tiene sentido que `Main` sea quien llame al método de parte de `Usuario`? Me imaginaría que es el `Usuario` quien saluda a otro, no `Main`.
No respondo con seguridad estas preguntas, porque puede variar por contexto, y no tengo mucha información sobre `Main` o el programa en general.

El caso 1, a mi gusto, sería el más raro. Siempre que hay "ciclos" de relaciones de composición o agregación, es señal de que no están bien asignadas las responsabilidades o separadas los comportamiento que realizan ambas clases. En este caso, hay agregación de vuelta a `Main` solo por el hecho de que le falta información a `Usuario`. Además, este tipo de relación en general es complejo en términos de desarrollo, ya que como ambas clases se referencian entre ellas, hacer cambios en una significa hacer cambios en la otra, y viceversa. Ese tipo de relación se dice que es *acoplada*. Puedes bajar el acoplamiento, si solo una entidad hace referencia y llama a métodos de la otra.

Ahora, también puede haber una tercera opción. Por ejemplo, algo como una entidad `DatosUsuarios` que contiene los datos de usuarios y su objetivo es manejar dichos datos para proveerselos a otras instancias. Una instancia de `DatosUsuarios` tal vez se crea en `Main` originalmente, y luego se pasa a `Usuario` como referencia. Así, se fija una relación de composición entre `Main` y `DatosUsuarios`, y una de agregación entre `Usuario` y `DatosUsuarios`. Esto puede ser más ordenado, ya que ahora hay una entidad especializada en proveer información sobre los usuarios a otras entidades. Pero esto depende del contexto, que no tengo tan claro.

Espero te haga sentido lo que dije, cualquier cosa pregunta nomás.
Saludos.

**Comment by furcelay** [comment]
Muchas gracias! 
Fue muy clara la respuesta, en el contexto de la tarea 1 creo la opción 2 va mejor con mi modelamiento, pero consideraré la tecera opción para futuros proyectos...

**Comment by furcelay** [comment]
Perdón por lo tarde,
Relacionado a la tercera opción, ¿sería válido hacer algo similar pero pasando una función de `Main` a `User` sin que exista relación de herencia?, algo como:
```python
class Main:
    def __init__(self):
        self.usuarios = {}
        self.__ususario_actual = None
    
    def crear_usuario(self, nombre):
        self.usuarios[nombre] = Usuario(nombre)
    
    def nombre_registrado(self, nombre):
        return nombre in self.usuarios
    
    @property
    def ususario_actual(self):
        return self.__ususario_actual
            
    @ususario_actual.setter
    def ususario_actual(self, nombre):
        self.__ususario_actual = self.usuarios[nombre]
        self.ususario_actual.nombre_registrado = self.nombre_registrado
        

class Usuario:
    def __init__(self, nombre):
        self.nombre = nombre
    
    def nombre_registrado(self):
        # este metodo se soobrescribe cuando este ususario es el actual
        pass
    
    def saludar_otro_usuario(self, nombre):
        if self.nombre_registrado(nombre):
            print(f"{self.nombre}: Hola {nombre}!")
        else:
            print(f"{nombre} no se encuentra registrad@")
        

    
main_1 = Main()
main_1.crear_usuario("Felipe")
main_1.crear_usuario("Diego")
main_1.ususario_actual = "Felipe"

main_1.ususario_actual.saludar_otro_usuario("Diego")
main_1.ususario_actual.saludar_otro_usuario("Sofía")
```
Que retorna:
```
Felipe: Hola Diego!
Sofía no se encuentra registrad@
```
De este modo `User` no accede a la información, solo al resultado de la función de `Main`...

**Comment by fdoflorenzano** [comment]
Hola @furcelay,

Entiendo la intención de tu solución, pero debo decir que parece una solución tramposa al problema de fondo.  Sobrescribir comportamiento (métodos) dinámicamente (durante ejecución) en general no es buena idea. 

Primero, va en contra de la idea de asignación de responsabilidades claras entre clases, y muestra que hay una interdependencia de comportamiento entre las dos clases en cuestión. 

Segundo, es difícil de mantener, en el sentido de desarrollo de código. Si un método que se espera una entidad posea vive en otra clase, seguirle el rastro es difícil. Más aún si la asignación de tal método se realiza en algún momento del programa, en ocasiones puedes encontrarse con que se te olvida hacer la asignación, o que esta no se comporta como esperas. Lo último es lo que genera más dudas, ya que leer el código se vuelve mucho más difícil. Al leer tu solución no estaba seguro que funcionaba hasta que lo probé. Particularmente porque el significado de `self` se pierde completamente al pasar de clase a clase.

Tu pregunta original era si es que era válida la solución. Es difícil determinar la validez de una solución, ya que al fin y al cabo puede que logres terminar con un programa que funcione. Pero si puedo decir que no es la mejor práctica y hay formas mejores de modelar tus entidades, donde no es necesario la redefinición de métodos de forma dinámica.

Saludos.

**Comment by furcelay** [comment]
Es cierto que el resultado es poco legible, yo tampoco sabía si funcionaría hasta que lo corrí, solo me emocioné porque en el momento me pareció una buena idea :sweat_smile:, pero entiendo el problema de resolverlo de esta manera.

Muchas gracias!
