### ISSUE TITLE
consulta min y max

### ISSUE THREAD

**Issue by DquezadaO** [IIC2233/Syllabus#403]
En min y max dice:
- Si las características son color de ojos, color de pelo, tono de piel o forma de nariz ...
- Si las características son altura o tamaño de los pies ...

Pero que pasa con las características que no entran en ninguna de las 2 acepciones como Donde hay vello corporal, Tamaño de la guata o Problemas de Visión? Tengo que hacer un raise y decir que la función no se define para ellas o las tiro con las primeras?

**Comment by Hernan4444** [comment]
@DquezadaO si no está en ninguna de las dos categorías significa que es un argumento invalido, lo cual implica un Raise.

Saludos ✌️
