### ISSUE TITLE
Modicar valor con property

### ISSUE THREAD

**Issue by amparostevens** [IIC2233/syllabus#403]
Hola! No  puedo  modificar un valor de un atributo de una subclase. Probé el código que sale de ejemplo en #317 pero cuando quiero imprimir el nuevo valor asignado, me sigue saliendo el valor con que está definido `self.__atributo`. Cómo hago para que cambie definitivamente? En la tarea tengo varias properties y no me estarían funcionando.

**Comment by lily416** [comment]
¿Puedes tus cambios al repositorio personal e indicarme alguna de las properties que están fallando?

**Comment by amparostevens** [comment]
Ya lo subí. Aún no pruebo en las clases de la tarea pero la función sería la misma de los métodos del archivo Untitled.py

**Comment by lily416** [comment]
Aparentemente tienes el mismo error del que se habla en esta _issue_ #331. Revísala y si sigues teniendo problemas no dudes en volver a preguntar acá o en esa _issue_.

Quedo atenta.
Saludos y éxito en la tarea 👋🦄

**Comment by amparostevens** [comment]
Ya entendí que no se pueden heredar atributos privados. Muchas gracias!!

**Comment by amparostevens** [comment]
Me sale el siguente error `Method 'prop' has no 'setter' member` pero igual me funciona el código. Qué puede ser?

**Comment by lily416** [comment]
¿Es un error que te sale cuando ejecutas el código o uno que te indica el _linter_?

**Comment by amparostevens** [comment]
Me lo indica el _linter_

**Comment by lily416** [comment]
Entonces puedes quedarte relativamente tranquila, ya que no es uno de los aspectos que se evalúa en PEP8. 🙌 
Igual te recomiendo investigar un poco más sobre el error para poder corregirlo, ya no podemos estar 100% seguros de si tiene un verdadero efecto en tu código o no.
 
Junto al error te debería salir la como esto: 
![image](https://user-images.githubusercontent.com/26393515/79058893-90116900-7c41-11ea-85e3-e454031d09e2.png)
Si buscas "PEP8 E501" (que sería el caso la imagen) vas a poder obtener más sobre el error y cómo corregirlo. 

Trata de hacer lo mismo con el error que te sale y si no logras resolverlo no dudes en preguntar. 😉 
Eso sí, pon lo que señala la imagen para que sea más fácil identificar tu error de PEP8.

**Comment by amparostevens** [comment]
Gracias!! Por lo que estuve averiguando es el error E1101 y se "arreglaría" con `# pylint: disable=E1101`
