### ISSUE TITLE
T03: Resultados.txt y errores

### ISSUE THREAD

**Issue by AmbrosioV** [IIC2233/Syllabus#403]
> Para ayudar a su testing, puede considerar que ante cualquier error, el comando retornará None.

Dado esto supuse para mi tarea que al momento de hacer el txt de resultados puse el None y no el error, este sale en consola. Es esto aceptable?

**Comment by Hernan4444** [comment]
![image](https://cloud.githubusercontent.com/assets/15641721/25725548/d92ed436-30f6-11e7-8cce-020edcb50ab1.png)

Si en tu archivo txt no estás siguiente el formato indiacdo en el enunciado, está malo.

Saludos!

**Comment by egbusch** [comment]
Para mostrar en consola y en el archivo .txt los resultados. Basta con poner la operación que se realizo o se debe poner el resultado completo ? Lo menciono ya que en el caso de operar un columna de 1.000.000 datos, se deben mostrar todos estos como resultado de la operación ? No me queda claro leyendo el enunciado. 
Saludos !

**Comment by Hernan4444** [comment]
#324 aquí está la respuesta
Saludos!

**Comment by egbusch** [comment]
Gracias !

**Comment by AmbrosioV** [comment]
@Hernan4444 digo con ese formato, pero por ejemplo cuando se asigna un valor en vez de escribir asignar solo, escribo la consulta asignar y un  su resultado que seria un None
