### ISSUE TITLE
Duda en "Caso en el que los enemigos queden lejos de las torres"

### ISSUE THREAD

**Issue by kylevon** [IIC2233/syllabus#403]
Si se hace el bono de camino más corto, ¿podemos asumir que se cumpliría este requisito de la rúbrica?

**Comment by Hernan4444** [comment]
Hola,
Así es, porque si el enemigo sigue el camino más corto, si o si llegará a la base lo más pronto posible. Así que si no hay torres, igual el jugador perderá pronto y no esperará infinito a que el juego termina.

Saludos :v:

**Comment by kylevon** [comment]
Perfecto, gracias
