### ISSUE TITLE
Resumen a final de turno

### ISSUE THREAD

**Issue by Icarus328** [IIC2233/syllabus#403]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, en el enunciado aparece que al final de cada turno hay que imprimir "un reporte de los movimientos de
dinero", quiero saber si ese reporte tiene que ser detallado (Incluir específicamente en que se gasto dinero y de que manera) o si es suficiente colocar el dinero que se tenía al iniciar el turno, el dinero al final del turno y un balance económico (Es decir, el dinero que se ganó o perdió)

**Comment by matiasfernandez1** [comment]
Hola @Icarus328, esta duda está respondida en la siguiente [issue](https://github.com/IIC2233/syllabus/issues/364). Pero en resumen sí tienes que colocar en qué se gastó específicamente.

**Comment by Icarus328** [comment]
Ok, gracias, y la parte de mostrar todas las transacciones una por una necesariamente debe ir en el resumen o puede ir según esas transacciones se llevan a cabo?

**Comment by matiasfernandez1** [comment]
Como tal se espera que vayan en el resumen.
