### ISSUE TITLE
Duda sobre generador en cargar_datos

### ISSUE THREAD

**Issue by BoPe3p** [IIC2233/Syllabus#404]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Hola! Tengo un problema ya que no me queda claro cuando en el enunciado dice: "El trabajo de esta función generador es abrir el archivo con encoding "UTF-8" e ir entregando instancias de Genero según el contenido del archivo."

La idea de la función (cargar_generos en este caso) es devolver un generador que itere sobre todos los datos del archivo, o devolver cada vez que se llame a la función cargar_generos una instancia de Genero?

**Comment by Hernan4444** [comment]
Hola @BoPe3p 

La idea es que transformes dicha función para que sea una función generadora y cada vez que se itere sobre ella, vaya devolviendo una línea del archivo. Ahí se espera aplicar un comando que están en los contenidos (y en la AY06) para lograr ese objetivo.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ
