### ISSUE TITLE
Duda en highest_paid_actors

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#404]
Para encontrar a los _k_ actores mejores pagados debo tomar en cuenta el dinero que ganaron en total por las películas en las que actuaron o tomo sólo lo que ganaron por la película que les dio más ganancia?

**Comment by santilaguna** [comment]
Me sumo a esta pregunta, pero también había pensado que podría ser el promedio

**Comment by papasconketchup** [comment]
Como se sabe cuanto se le paga a cada actor? No lo veo en ninguno de los archivos.

**Comment by Hernan4444** [comment]
![image](https://user-images.githubusercontent.com/15641721/39649412-1633c19a-4fbc-11e8-99a2-94f5d5498ddb.png)

Tal como se ve en la imagen, el dinero recaudado por película se reparte entre todos sus actores. Para obtener la paga total, es la suma de todo lo que ganó en las películas que actuó.
