### ISSUE TITLE
conexión entre inicios y base

### ISSUE THREAD

**Issue by kylevon** [IIC2233/syllabus#404]
¿Los "inicios" (S) siempre están conectados a la base? Ya que en el enunciado aparece: "Espacios en donde aparecen las unidades enemigas y comienzan su recorrido hacia la base." Tiene sentido que sea así.

**Comment by Hernan4444** [comment]
Hola, 

Siempre existirá al menos 1 camino desde el inicio S hasta la base. Lo que si puede pasar, es que el camino se divida en 2 y uno de ellos no llegue a la base, pero el otro si.

Saludos ✌️

**Comment by kylevon** [comment]
Perfecto, gracias!
