### ISSUE TITLE
Uso de decorador métodos estáticos (y otros)

### ISSUE THREAD

**Issue by ljgonzalez1** [IIC2233/syllabus#404]
Hola. Sé que vimos los decoradores _@property_ y _@abstractmethod_, pero quería saber si no había problemas con usar _@staticmethod_ o cualquier otro por si se me presenta el caso en la T01.

**Comment by retamalcito** [comment]
¡Hola @ljgonzalez1!

No hay problema en que utilices el decorador `@staticmethod` en tu tarea, siempre y cuando tengas claro su funcionamiento y no contradigas ninguna parte del enunciado ✨. Supongo que con "otros", te refieres al decorador `@classmethod`, el cual también puedes usar (aunque veo más difícil su utilidad en este contexto).

¡Saludos! 😄
