### ISSUE TITLE
Diagrama De Flujo

### ISSUE THREAD

**Issue by pascal1003** [IIC2233/syllabus#404]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, 
Si es que en el diagrama de flujo tuve máximo puntaje en el avance tengo que modificarlo igual para la entrega final?

**Comment by matiasfernandez1** [comment]
Hola @pascal1003, deberías modificarlo si es que en el feedback que se entrego te hicieron alguna anotación. Ya que el en el avance más se evaluaba que fueras por buen camino con ya todas las clases y las relaciones bien colocadas más que el tener todo el diagrama totalmente perfecto. 
De todos modos yo que tú igual le echaría un ojo por si acaso. Saludos.
