### ISSUE TITLE
Alimentar criaturas escapadas

### ISSUE THREAD

**Issue by knight-who-say-ni** [IIC2233/syllabus#404]
Hola!! Tenía una duda, al alimentar criaturas, puedo alimentar alguna criatura que se haya escapado??
Lo logico suena que no, pero no aparececen el enunciado esta restriccion...
Muchas gracias!!

**Comment by lily416** [comment]
Hola @knight-who-say-ni, tu duda ya fue respondida en la _issue_ #273.

Recuerden revisar las _issues_ antes de abrir una nueva, puede que tu duda ya haya sido respondida anteriormente.

Saludos y éxito en la tarea 👋🦄
