### ISSUE TITLE
Largo Métodos de Interfaz en main

### ISSUE THREAD

**Issue by pdesolminihac** [IIC2233/Syllabus#404]
Los metodos que debemos sobreescribir en el main (process_query, save_file) también deben tener un largo maximo de 15 lineas y estar atomizados?

**Comment by fnquinteros** [comment]
Hola! Idealmente deberían usar sus funciones atomizadas de la librería para interactuar con esos métodos que deben sobreescribir. 

Saludos!

**Comment by pdesolminihac** [comment]
Pero el metodo en si debe medir 15 lineas también?

**Comment by MarceloSaldias** [comment]
Agradecería si pueden responder esto para salir de la duda :c 
Yo creo que no pero no quiero sorpresas en la correcion :disappointed:

**Comment by Hernan4444** [comment]
si pueden sobrepasar las 15 lineas, pero no olviden que la lógica de su programa (todo el procesamiento) debe estar en su librería, el main es solo un medio para conectar interfaz con librería.
