### ISSUE TITLE
Duda metafísica de la columna

### ISSUE THREAD

**Issue by pizquierdo2** [IIC2233/Syllabus#404]
<img width="738" alt="captura de pantalla 2017-05-03 a la s 18 37 41" src="https://cloud.githubusercontent.com/assets/26145677/25682749/a28d439e-302f-11e7-89af-3e55c797c2bd.png">

Consideremos la lista = [1,2,3,4,[]].  Se considera esta lista una columna?

En particular, la pregunta la tengo porque no se que error si levantar o no un error en el siguiente caso: asignar('x', [1,2,3,4,[]]). Si [1,2,3,4,[]] no fuera una columna, entonces debería levantar un Error de Tipo. En el caso contrario no debería levantar ningún error.
 
Consideremos ahora este otro caso: graficar([1,2,3,4,[]], 'numerico').  Si [1,2,3,4,[]] no fuera una columna, entonces debería levantar un Error de Tipo. En el caso contrario debería levantar un error Imposible Procesar, puesto que no podría procesar todos los datos de la columna entregada.

En mi opinión, deberíamos considerarla una columna, pues de otro modo habría que repasar cada uno de sus elementos consititutivos para verificar si es o no columna; y en columnas como generadores eso es muy desfavorable, por su condición on the fly, lo que nos obligaría a proceder de algún modo que tuviera como consecuencia perder la eficiencia en memoria que nos otorga el on the fly.

Gracias!

**Comment by cho19** [comment]
¡Apoyo esto! (en la mejor de las ondas)

Pongo otro ejemplo: en caso de que tuviéramos que asignar a una variable una columna de archivo muy grande (5.000.000 de datos) y sabemos la columna a leer es de un tipo numérico (int/float). Se dijo en otro issue que la columna del archivo podía contener variables ("x" en lugar de 10, con x=10 en RQL), imaginemos que la "x" esta en el archivo, pero no asignada aún. Por otro lado también se nos pide que `asignar` no tome mas de 0 segundos pues se genera la columna, ¿cómo voy a lanzar error de referencia invalida si no puedo recorrer la columna al asignarla? Y si pudiera, creo que no tendría ningún sentido analizar una columna de 5.000.000 de datos al ser asignada si no va a ser operada.

Lo más lógico parece ser que dejemos que eso sea una columna y que el usuario, al intentar operarla, se encuentre con otro error pero en la operación misma.

Saludos y gracias

**Comment by Hernan4444** [comment]
Sobre el tema de errores en cuestión:
![image](https://cloud.githubusercontent.com/assets/15641721/25726167/47f2f27e-30f9-11e7-9a65-20a90da1e3f8.png)

Es decir, si no saben que error levantar, decidan ustedes y argumenten en su readme.

> Por otro lado también se nos pide que asignar no tome mas de 0 segundos pues la columna no se procesa, se crea un generador. 

En ninguna parte se les pidió que no tome mas de 0 segundos. 

![image](https://cloud.githubusercontent.com/assets/15641721/25726421/74da98a4-30fa-11e7-804a-29194b373118.png)

En el anuncio se indica que es un tiempo referencial y en esos ejemplos no había variable dentro de las columnas y por ello se demoró 0 segundos. Si llegáramos a poner variables dentro, vamos a ejecutar nuestra solución revisando esos casos y ver cuanto tiempo se demora para que sea esa nuestra referencia y no un caso donde no habían variables. 

> Lo más lógico parece ser que dejemos que eso sea una columna y que el usuario, al intentar operarla, se encuentre con otro error pero en la operación misma.

Sin embargo te concedemos esta parte, usando la lógica de funcional y beneficiarse de `on the fly` lo mas lógico es lo que dices. Considerando que queda casi 1 día para entregar la tarea, puedes usar esta forma (especificando en el readme) pero la anterior de revisar al momento de extraer también la tendremos en cuenta (en relación al tiempo y al error que salga al final) con el fin de que ningún de los alumnos salga perjudicado por tomar una de estas dos vías.

Saludos!!
