### ISSUE TITLE
Problema con QWidget.setContentMargins()

### ISSUE THREAD

**Issue by MGome** [IIC2233/syllabus#404]
Hola buenas! Al testear mi programa me di cuenta de que se me generan automáticamente estos margenes en la en la ventana principal (la cual hereda de QWidget). Buscando en la documentacion de PyQt5 (https://doc.qt.io/archives/qt-4.8/qwidget.html#setContentsMargins) encontré este método que, se supone, debería eliminar el margen de los contenidos. Al probarlo como self.setContentMargins(0, 0, 0, 0) me di cuenta de que no funcionó :(. Adjunto una foto de lo que quiero arreglar
![margen](https://user-images.githubusercontent.com/48321270/66249382-cc02c900-e708-11e9-9e78-808cee9c7ca5.jpg)

**Comment by lily416** [comment]
Primero, recuerda que el foco de esta tarea es que sea **funcional**, ya que la visualización de la tarea no es un punto a evaluar.

Con respecto a tu problema, tengo la sensación de que más que ser un margen, aparece por la ubicación que tienen los elementos dentro de tu ventana. Puede que esté relacionado que el elemento que guarda el mapa (`fondo`) es un `QVBoxLayout()` 🤔 

Saludos y ojalá te sea de ayuda 👋🌱
