### ISSUE TITLE
Botón "Archivo" en GUI (Mac)

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#405]
En la imagen que sale de la GUI en el enunciado, aparece un botón que dice "Archivo". ¿Es relevante para cargar las consultas? 
De ser o no ser así... Me podrían hacer una pequeña explicación de cómo cargar las consultas, por favor? Gracias de antemano.

**Comment by Hernan4444** [comment]
@llloyola fijate arriba a la izq en la barra, deberia salir algo asi:
<img width="167" alt="screen shot 2017-04-24 at 12 09 05 pm" src="https://cloud.githubusercontent.com/assets/16126322/25343949/f67d38d8-28e6-11e7-836f-7000537e46fd.png">

Con presionar en "Abrir" debería cargar las consultas
saludos :)!

**Comment by llloyola** [comment]
@Hernan4444 No me sale eso, mi botón no funciona :( Qué puedo hacer?

**Comment by jerosalazar** [comment]
@llloyola ocupas atom? porque a mi me pasa lo mismo cuando abro el programa con atom. En IDLE no hay problema 😄

**Comment by llloyola** [comment]
Ocupo Sublime. Tengo que bajar PyQt5 para ocuparlo con IDLE :(
