### ISSUE TITLE
Tiempo de crecimiento de las plantas

### ISSUE THREAD

**Issue by kadroguett** [IIC2233/syllabus#405]
Hola, con respecto al tiempo de crecimiento de las plantas me parece extraño que los segundos sean tan pocos, considerando que tenemos que ajustar el tiempo para que en el juego pasen días los 180 segundos por fase de los choclos tomaría menos de un segundo en el juego y no se lograría apreciar el cambio, y si se ajusta el tiempo para que pase más lento tomaría mucho pasar un día. Como no se tiene que subir el archivo parametros_plantas.py asumo que no se deben modificar, con esto en mente, los valores en el archivo están bien y los tiempos tienen que ser así de cortos? es más recomendable jugar con estos valores o con la velocidad del reloj?

**Comment by Arcoirisky** [comment]
Los parámetros están para que quien pruebe el programa pueda modificarlos a su gusto y, de paso, ver cómo afecta en el juego. Si crees que deberían cambiar, puedes modificar los valores de los parámetros pero ojo, no puedes cambiar la fórmula dada en el enunciado. 

Reitero, la fórmula del enunciado la debes mantener pero los valores de los parámetros puedes cambiarlos a tu gusto mientras programas. Mientras tu tarea funcione con el archivo sin modificación, estará bien. 

Recuerda que puedes hacer los cambios que quieras mientras lo estipules en el enunciado y no contradiga el enunciado.

**Comment by kadroguett** [comment]
Gracias!

**Comment by cchauriye** [comment]
Hola! A qué se refieren con la fórmula del enunciado?
