### ISSUE TITLE
Duda test_elementos_prohibidos [RecursionError]

### ISSUE THREAD

**Issue by IsidoraCarmona** [IIC2233/Syllabus#405]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, me podrian guiar un poco en lo que significa este error ?
![image](https://github.com/IIC2233/Syllabus/assets/162645031/de4e4a38-f42a-42bf-a35f-50a4f7cd0c55)

**Comment by leonidasmontes** [comment]
Me sale exactamente lo mismo. ¿Es normal?

**Comment by Hernan4444** [comment]
Hola,

No es normal eso. Estoy investigando qué cosa del código provoca este error (estoy usando el código de @IsidoraCarmona para validar). En un rato les indicaré por qué ocurre esto y en caso de ser un error en el script, se corregirá eso.

Saludos

**Comment by leonidasmontes** [comment]
Ok gracias quedo atento! @Hernan4444

**Comment by CatalinaBO** [comment]
me sale el mismo error :(

**Comment by Hernan4444** [comment]
Hola,

Acabo de subir una versión 2 del script `test_elementos_prohibidosV2.pyc`. Porfa intenten con este y avisenme si les corre todo. Que encontré una posible solución que funcionó con el código de @leonidasmontes e @IsidoraCarmona  quienes tenían un push bien reciente, pero tal vez el código que tienen justo justo ahora tiene algo que no estamos viendo.

Finalmente, esta issue va a ser solo para este RecursionError al momento de ejecutar el archivo. Si quieren entender por qué el script indica que una línea está mala, porfa crear otra issue.

Quedo atento a si les corre la V2.

Saludos!

**Comment by leonidasmontes** [comment]
Gracias @Hernan4444 !!

Ahora no me sale lo mismo de antes pero no me funciona :(. No sé si estoy haciendo algo mal yo.

<img width="643" alt="Captura" src="https://github.com/IIC2233/Syllabus/assets/162604887/55e03420-ea3a-494c-a858-3a3be063ec40">

**Comment by Hernan4444** [comment]
@leonidasmontes puedes pushear tu código actual porfa y me avisas.

Saludos!

**Comment by IsidoraCarmona** [comment]
Hola a mi me aparece lo mismo 
![image](https://github.com/IIC2233/Syllabus/assets/162645031/c1c2d912-5ee6-4ab9-a490-007dfa82d73b)

**Comment by leonidasmontes** [comment]
Ahí hice un push @Hernan4444

**Comment by CatalinaBO** [comment]
Muchas gracias @Hernan4444, ya me funcionó todo bien!

**Comment by leonidasmontes** [comment]
Si, funcionó. ¡Gracias! @Hernan4444

**Comment by IsidoraCarmona** [comment]
Ahí funcionó, ¡Muchas Gracias!

**Comment by Hernan4444** [comment]
Buenisima :tada:, entonces ahora si voy a reemplazar el archivo original con esta nueva versión 👍  (así dejamos solo 1 archivo).

-----


## Momento que nadie me pidió pero quiero hacer.

Para transparentar, el segundo error  (`FileNotFoundError`) fue que edité una línea que permitía que el script funcionara en windows, y como estoy en mac, a mi me funcionó y lo pushie de inmediato para no hacerlos esperar. De aquí se aprende a revisar bien qué cosas uno cambia antes de pushear 😅 🙈.

Respecto al primer error, lo que sucede el que el script busca cada llamado que hace una función. Por ejemplo
```python3

def f(x):
    return f2(x)
```

Aquí se da cuenta que `f` llama a `f2` así que antes de terminar su análisis por `f` debe analizar `f2`. Ahora bien, si `f2` llama a `f` o `f` llamara a `f` (recursión) el script se cae por un análisis recursivo.

Ahora, muy probablemente ustedes no tenían ese caso de recursión, pero si tengan algo como:
```python
def votos_interespecie(x):
    ...
    votos_interespecie = [..... ]

     return .... 
```

Es decir, dentro la una consulta (`votos_interespecie` en este ejemplo), se define una variable que se llama **exactamente igual** que alguna función y el script actualmente asocia a que `votos_interespecie` está ejecutando `votos_interespecie`, y ahí se generaba la recursión en el script. Eso último se corrigio para que si detecta que `f` ejecuta `f`, no entre en la recursión de analizar nuevamente `f` y por eso ahora funcionó. 

¡Muchas gracias por haber participado en este mini testeo de la nueva versión!, estoy muy agradecido que se pudo mejorar aún más este script 🧡

¡Éxito en su tarea! 🚀
Saludosヾ(＾-＾)ノ
