### ISSUE TITLE
Duda de enunciado

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#405]
Hola. En un parte de el enunciado dice que al pasar el día hay que Mostar las criaturas que han perdido salud por estar enfermas. Mi problema es que no encuentro en donde esta el valor de lo que baja por día la salud si la criatura esta enferma. :(

Además, no entiendo algo en la parte de la multas. Por ejemplo, si paso de día y hoy se enfermó una criatura pero sigue enferma varios días, solo multo el día en que apareció enferma? Lo mismo cuando se escapa.

**Comment by fdoflorenzano** [comment]
Hola @tedroppelmann, ambos detalles se explicitan en el enunciado.

Tu primera duda se responde en el detalle del atributo "Estado de salud" en DCCriaturas, y además ya fue respondida en #394.
Lo segundo se explica en "Fiscalizar a los Magizoólogos" en DCC se aplica sobre eventos **que ocurran en el día correspondiente**.

Saludos.
