### ISSUE TITLE
Décimas bonus

### ISSUE THREAD

**Issue by pulpaulaa** [IIC2233/Syllabus#405]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Me disculpo si esta información está disponible de forma específica en algún lado, pero las veces que lo he buscado no lo he encontrado o entendido y quiero estar segura. ¿El puntaje de los bonus de las tareas es parte del máximo o es extra? Es decir, si yo hiciera la tarea de forma perfecta pero no implemento ningún bonus, ¿sería un 7 o sería menos, porque no implementé los bonus?

**Comment by Hernan4444** [comment]
Hola @pulpaulaa 

Es puntaje extra, si haces todo perfectamente y sin bonus, optarás al 7.0

Saludosヾ(＾-＾)ノ
