### ISSUE TITLE
problema en las named_tuples

### ISSUE THREAD

**Issue by Andrssilva** [IIC2233/Syllabus#405]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

las named_tuples en utilidades tienen dos atributos cada una, en vez de seis y 3 que mencionan en el enunciado. 

Pelicula = namedtuple('Pelicula', 'id_pelicula, titulo, director, estreno, rating')
Genero = namedtuple('Genero', 'genero, id_pelicula')

Hay algún error?
![image](https://github.com/user-attachments/assets/8d863e42-06f9-4757-9dc1-80380177026e)

**Comment by bibarra9** [comment]
No es un error. Cuando se define una `namedtuple`, se debe especificar el nombre en el primer argumento y un `str` o una `list` que enlista los atributos como segundo argumento.

**Comment by Hernan4444** [comment]
Hola @Andrssilva 

Tal como dice bibarra9. No es un error. Si revisamos los [contenidos de la semana 3 (Estructuras de Datos)](semana-03-estructuras_de_datos/1-introducción-y-tuplas.ipynb), ahi se menciona:

> La inicialización básica de una namedtuple requiere un string con el nombre para el tipo de tupla y el nombre de los campos que tendrá, los que se pueden entregar en un string o una lista de strings como en el siguiente ejemplo:
```python
# Asignamos un nombre a la tupla (Register_type), y los nombres de los atributos que tendrá
ChileanRegister = namedtuple('ChileanRegister_type', ['RUT', 'name', 'age'])
# Vemos que podemos asignar los atributos como string
MyRegister = namedtuple('MyRegister_type', 'unique_id, nickname, age')
```

Por lo tanto, solo es que usamos la segunda forma en vez de la primera.


Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ
