### ISSUE TITLE
AttributeError - programa toma set() como list()

### ISSUE THREAD

**Issue by dmelberg** [IIC2233/syllabus#405]
Hola!
Tengo un metodo en mi init de mi ventana principal "`VentanaMapa`" que agrega objetos de tipo `Moneda` a un set que se encuentra en el init haciendo `set_monedas.add(moneda_nueva)`. Al ejecutar el codigo me sale este error:
`self.mis_monedas.add(nueva_moneda)
AttributeError: 'list' object has no attribute 'add'`
Pero probe incluso declarando un set aparte con un nombre que no he usado en toda la tarea (por si lo tuviera repetido y sobreescrito como list) y llamando a ese atributo y me tira el mismo error :( No se que puede estar fallando.

**Comment by ariel-m-s** [comment]
Hola @dmelberg!

Para ayudarte, voy a necesitar que subas un pantallazo del método ```__init__``` en el que instancias ese ```set``` y otro pantallazo de la función en la que lo usas para agregar las monedas.

Saludos.

**Comment by dmelberg** [comment]
Lo subo aquí publico nomas?

**Comment by ariel-m-s** [comment]
@dmelberg gracias por preguntar antes de subir código de la tarea. De hecho, sería mucho mejor que hicieras _push_ en tu repositorio y me indicaras el archivo y el número de líneas a revisar. Luego de eso, comentaré acá mismo cuál es el error.

**Comment by dmelberg** [comment]
Perfect. Hice push hace poco. Todo lo que mencioné está en el archivo `front_end_mapa.py`. El atributo en la **linea 63** y y se utiliza en la **linea 151**, en la función `crea_moneda`. Para correr el programa, se debe correr el archivo `front_end.py`.

**Comment by ariel-m-s** [comment]
Utilizas _properties_, lo cual está muy bien 😄. El problema es el siguiente: cuando defines el _setter_ de ```mis_monedas```, colocas el decorador ```@posiciones_monedas.setter```. Me parece que lo que en realidad querías escribir es ```@mis_monedas.setter```.

No sé como funcionan las _properties_ internamente, pero me imagino que de alguna manera esto está sobre escribiendo ```mis_monedas```, lo cual causa el error que mencionaste.

Espero haberte ayudado. Avísame si te funciona. Saludos!

**Comment by dmelberg** [comment]
gracias!!
