### ISSUE TITLE
Duda sobre metodos 

### ISSUE THREAD

**Issue by isidorabecker** [IIC2233/syllabus#405]
Holaaa, si creo un nuevo atributo en un métodos especifico de la clase, este atributo también debe estar en init o no es necesario ??

**Comment by ignacio-urrutia** [comment]
Hola @isidorabecker ! no es necesario que esté en el init de la clase, ya que ahí solo debes definir los atributos que se ingresan como parámetros. Sin embargo, para que este atributo pueda utilizarse en otros métodos, debes recordar guardarlo como _self.atributo_

**Comment by isidorabecker** [comment]
Ok, muchas gracias !!!
