### ISSUE TITLE
Error en juego

### ISSUE THREAD

**Issue by cmarquez1** [IIC2233/syllabus#406]
Hola, lo que pasa es que cuando hago funcionar el front, funciona todo bien hasta un par de momentos después, el cual la ventana se llega a cerrar, subi mi codigo pa que lo puedan ver y ver cual es el error que hace que la ventana de cierre despues de unos segundo de juego.

**Comment by Hernan4444** [comment]
Hola, 

Primero te recomiendo que vayas ejecutando tu tarea con pocas cosas, por ejemplo: solo tu persona, luego tu persona + monos, luego tu persona + torres, persona + monedas, de modo que puedas acotar el origen del problema, ¿qué clase es la que genera el error?.

Luego, el error típico que está pasando es que pyqt5 no acepta tener cosas cuya referencia no existe, por ejemplo, tener un QLabel en la pantalla, pero nadie guardó ese label en algún atributo y por lo tanto, sin referencia se genera error. 

Dada la descripción que das, que se cae luego de un rato, puedo suponer que al momento de eliminar algo, estás dejando algún residuo sin eliminar. Por ejemplo: muere el enemigo que es QThread y destruyes el thread, pero no su label, y por lo tanto el label pierde su referencia y se cae el juego. En ese caso hay que eliminar el label y luego destruir el thread.

Saludos

**Comment by cmarquez1** [comment]
Me pasa cuando agarro las monedas, tengo una función que crea monedas y guarda el back(clase moneda del back) y front (Qlabel) en un dicc con un id para cada moneda, y cuando las agarro envio una señal a una funcion del front que hace desparecer las monedas, donde toma el id de la moneda, hago dicc.pop(id, None) para que no tire error cuando no encuentre id, y hago primero deleteLater() para borrar el label y despues hago quit() para terminar el thread antes, porque el back es un qthread el cual en la funcion run() envio una señal para que se muestre la moneda en el front, un sleep, y despues envio una señal para eliminar la moneda (que esta conectada a la misma funcion que esta conectada cuando agarro una moneda).

**Comment by cmarquez1** [comment]
ocupe .terminate() para terminar el qthread y creo que se me soluciono

**Comment by Hernan4444** [comment]
Ok,

Necesito que hagas push para ver esa parte de tu código y ver está pasando.

Avisame

**Comment by cmarquez1** [comment]
acabo de hacer push

**Comment by Hernan4444** [comment]
Revisando el código,

El error es que cuando atrapas la moneda, esta la eliminas, pero el `run` del thread sigue en ejecución y por lo tanto, cuando termina de hacer sleep, emite una señal, pero el thread ya estaba muerto, por eso se genera un error. (Un thread "muerto" que intenta emitir una señal, ahí pasan cosas malas) 

Te recomiendo intentar con un atributo que diga si "ya tocaron la moneda o no" que parte como false. Cuando el personaje la toque y se emita la señal para eliminarla, solo elimina el label y cambias ese atributo a "si, fui tocada". Luego, en el run del thread, despues del sleep, verifica:
* Si fue tocada, entonces no hace nada porque ya no hay referencia al thread y el run terminó. Por lo tanto el thread termina exitosamente.
* Si no ha sido tocada, entonces emite la señal de desaparecer_moneda, su label será eliminado y como se pierde la referencia al thread y el run se terminó, el thread terminará exitosamente.

Hice eso con tu código y no se me ha caido nada cuando las toco. Como lo tenías antes, igual se me caía cuando atrapaba una moneda y luego esta "finalizaba su sleep".

Saludos

**Comment by lfuenzalida2** [comment]
A mi me ocurre el mismo error, pero con los enemigos y sucede que cuando pongo mas enemigos mas me falla, todavia no he implementado el matar a enemigo, asique no hay problema con que el thread termine y otra cosa que pude observar es que cuando coloco mas enemigos se cae mas rapido el programa, intente de aislar el problema para ver que era y efectivamente eran solo eso con los enemigos. No se que hacer, he buscado en muchos lugares, pero no se me ocurre que puede estar fallando
