### ISSUE TITLE
Generar Archivo

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2233/Syllabus#406]
Cuando generarmos el archivo, tenemos que guardar la informacion de las consultas realizadas. Respecto al formato del txt generado, debe ser lo mismo que habria aparecido en la pantalla de RQL?

**Comment by Hernan4444** [comment]
@Rudyjb24 sobre guarda la información de las consultas realizadas no quedo bien especificado así que queda a tu criterio mientras lo especifiques en el readme. sobre el formato, es prácticamente el mismo con una ligera diferencia con no mostrar los gráficos.

Saludos!
