### ISSUE TITLE
cheatcodes en teclados con antighosting

### ISSUE THREAD

**Issue by criism0** [IIC2233/Syllabus#406]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola buenas! tengo una duda respecto a los cheatcodes, ya que en la implementación de estas funcionalidades lo hice con un teclado que me permitia apretar varias teclas a la vez y funcionaba perfecto, pero ahora, intenté activarlos en otro computador con un diferente teclado y este no me permite activarlos ya que solo permite activar algunas teclas a la vez pero justo la combinación "KIL" no la permite en cambio "INF" sí, y en el otro teclado ambas estaban permitidas, en este caso qué debo hacer? cambiar la manera de activar los cheatcodes que tengo implementada? que no se me ocurre otra manera de hacerlo o solo colocarlo en el readme y especificar este problema que puede ocurrir dependiendo del teclado. Muchas gracias de antemano.

**Comment by Hernan4444** [comment]
Hola @criism0 

Si en tu notebook funciona, dejalo como está. Pero comenta eso en el readme. Además, si lo tienes como un parámetro `KIL = "KIL"`, tu corrector podría cambiar esa secuencia por otra que el taclado si lo permita y así validar su funcionamiento. Por ejemplo, validar `INF`, luego intercambiar `INF` por `KIL` y verificar que cuando oprima `INF` ocurra lo de `KIL` y con eso estamos. 

Así que no te preocupes, hay situaciones como estas que según como tengas configurado tu PC, se toman ciertas decisiones que otro PC puede que no funcione. De todas formas, si a ti te funciona y al ayudante no, esto totalmente se puede ver en el proceso de recorrección y conversar con tu profe para que lo vea en tu PC y dé el visto bueno.

Saludosヾ(＾-＾)ノ
