### ISSUE TITLE
Cantidad máxima de atributos

### ISSUE THREAD

**Issue by barbarafcp** [IIC2233/syllabus#406]
Hola! Por lo que tengo entendido los implementos medicos y deportivos aumentan en un 10% al comprar tecnología, esto se refiere a que se le suma su valor inicial*0.1 ? y mi otra duda es que si los parámetros que dan, por ejemplo, al inicio cuando asigno un valor random a implementos deportivos que este entre 0.3 y 0.7, después cuando aumente al comprar tecnología tampoco puede exceder el 0.7 o estos valores son solo para la asignación inicial? Gracias con anticipación^^

**Comment by baosse** [comment]
Holaa Barbara!
Sii, a eso se refiere, es su valor inicial más el 10% de este. 
Y con respecto a tu segunda pregunta, si, no puede exceder este número.
Espero que te haya quedado más claro.
Mucho éxito!✨
