### ISSUE TITLE
uso de funciones en parte 2 actividad 3

### ISSUE THREAD

**Issue by vhernnda** [IIC2233/Syllabus#406]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Cuando el enunciado dice  "se espera que apliquen correctamente diferentes funciones como map, filter y reduce, uso de funciones anónimas (lambda) e itertools.", se espera que aplicamos cada una de las funciones mencionadas por lo menos una vez?.

**Comment by Hernan4444** [comment]
Hola @vhernnda 

Es un "deseaso", pero no es un requisito exclusivo. Por ejemplo, se puede crear una función con `def` en vez de usar `lambda` y estará correcto, pero al menos las consultas se pensaron para poder aplicar de todo al menos 1 vez y así puedan practicar estos comandos.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ
