### ISSUE TITLE
Duda sobre cuando usar Signals

### ISSUE THREAD

**Issue by javierzagal** [IIC2233/syllabus#406]
Al momento de enviar información del front end a la entidad personaje instanciada en el mismo, es necesario utilizar señales? Por ejemplo si quiero enviarle un string a mi personaje instanciado en la ventana y uso algo como _self.personaje.recibir_string(string)_ es una mala practica, o recibir informacion en el otro sentido de manera similar con los _returns_ en las entidades? En algunos casos me parece mas simple y no estoy seguro si está permitido

**Comment by tomasgv** [comment]
Hola!

Recuerda que cualquier procesamiento de información debe pasar por el _backend_. Pregúntate si deberías realmente tener la instancia completa del personaje en el front cuando lo único que el front debe hacer es actualizar su imagen.

Espero haberte ayudado! 🌽
