### ISSUE TITLE
El sistema deja de agregar entidades en el tablero 

### ISSUE THREAD

**Issue by FelipeIGS** [IIC2233/Syllabus#407]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola,
Me esta pasando que despues de comenzar a agregar entidades al tablero el sistema deja de agregar a las entidades y la comunicacion con el grid deja de tener respuesta. Esto creo que podria ser debido al tema de setFocus, pero por lo que habia investigado, puede tener relacion con el QWidget que pego, ya que las entidades heredan de eso. Me pueden ayudar a detectar que ocurre o a que se debe? Muchas gracias!

**Comment by Hernan4444** [comment]
Hola @FelipeIGS 

Revisé tu caso, y no es problema del setFocus, es que tus widget que agregas son demasiado grande. Si en tu código (ventana_construccion.py línea 162) agrego un `print(entity.width(), entity.height())` te saldrá que es 640 y 480. Eso hace que tu widget tape la grilla y no se detectenlos demás clicks. Si por ejemplo partes poniendo una pared desde la derecha y te vas moviendo a la izquierda, si funcionaría 😅 porque esa zona todavía no estará tapada.

Lo que intentaría es cambiar tamaño de esos widget, por ejemplo, con `.setGeometry`.

Saludosヾ(＾-＾)ノ

**Comment by FelipeIGS** [comment]
Muchas gracias profe Hernan! Soluciono mi vida.
