### ISSUE TITLE
Rango torre

### ISSUE THREAD

**Issue by jerrymendoza** [IIC2233/syllabus#407]
Consulta no importante, es posible cambiar el rango de ataque a una circunferencia y no un cuadrado, se ve más real (según yo) ?

**Comment by Hernan4444** [comment]
Hola

No se puede cambiar porque nosotros vamos a evaluar que el rango sea cuadrado y funcione bajo ese supuesto. Por lo tanto, de querer implementar rango circular, te recomiendo dejar una variable en parametros que permita cambiar entre cuadrado y circulo , o un botón en el juego, pero no se permite el dejar de implementar el cuadrado por hacer el circular.

Saludos ✌️
