### ISSUE TITLE
Consultas en la gui

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#407]
Hola tengo la  duda de que si las cosultas siempre vendran en un formato de que  la consulta de mas afuera es la que retorna una lista la de al medio es la que retorna movies y la primera es load_database() o de tal forma que lo que se muestre en las respuestas de la gui sea siempre lo obtiene de la lista

**Comment by Hernan4444** [comment]
@sjkinast no puedes hacer ese supuesto. Pueden haber consultas que retornen solo la base de datos e incluso, pueden haber multiples consultas anidadas (más de las que aparecen en el enunciado).  

Saludos ✌️

**Comment by santilaguna** [comment]
@Hernan4444 para los casos en que una consulta anidada no retorne una base de datos, ¿levantamos BadQuery entonces?
Ejemplo: ["filter_by_date", ["successful_actors", ["load_database"]], 2015]

**Comment by Hernan4444** [comment]
@santilaguna precisamente, porque filter_by_date necesita una base de datos como primer argumento, pero recibió una lista de actores, así que el parámetro es inválido.

Saludos ✌️

**Comment by jpmoraga1** [comment]
@Hernan4444 ¿No sería WrongInput en ese caso?

**Comment by mora4** [comment]
No entiendo que se debe mostrar en la interfaz en el caso que hagan una consulta que retorna un generador. Imprimir los elementos del generador?

**Comment by Hernan4444** [comment]
@mora4 exactamente, imprime los elementos, el formato queda a tu criterio.
