### ISSUE TITLE
Citar en actividades

### ISSUE THREAD

**Issue by BoPe3p** [IIC2233/Syllabus#407]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Buen dia, tenía una duda ya que nunca se menciona, pero utilicé código externo para una actividad. ¿Esto se puede hacer? Si es que se puede, ¿cómo debería citar el código? ¿Debería hacer un README para la actividad? 

Gracias de antemano

**Comment by Hernan4444** [comment]
Hola @BoPe3p 

Si se puede utilizar código externo. Respecto a la cita, si bien en las actividades somos más flexible y no revisaremos que cites. Lo mejor es acostumbrarse a hacerlo. Para esto, puede ser un comentario en el mismo código con el link a donde sacaste el código, o crearte un Readme para poder citar.

Si bien no vamos a exigir eso en las actividades, lo que puede llegar a pasar es que luego copies algo de tu actividad a tu tarea, y ahí si exigimos que cites el origen de ese código. Por eso recomiendo que, al menos, en las AC dejes un comentario con el link de donde sacaste código externo, así si llegas a usar ese mismo código en la tarea, tengas la fuente original para citar.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ
