### ISSUE TITLE
¿Es necesario utilizar herencia para modelar los deportes?

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2233/syllabus#407]
Hola, queria saber si tenia que hacer una clase Deporte padre o si podia solamente hace clases independientes para cada deporte.

**Comment by retamalcito** [comment]
¡Hola @conyfernandezt!

**Sí es necesario** que crees una clase `Deporte` madre de las clases que representan a cada deporte individual, ya que herencia es parte de los contenidos de la tarea y nos interesa que la manejen.

Técnicamente podrías hacer clases independientes para cada deporte, pero no tendrías puntaje en la parte de modelación de estas entidades. 🙁

¡Saludos! 🥇
