### ISSUE TITLE
Nombre archivo al hacer save_file

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2233/Syllabus#407]
Quería saber como se tiene que llamar el archivo que se genere al hacer save_file en la gui y, suponiendo que se llama "consultas.json", debe sobrescribir al antiguo consultas.json o deben agregarse las consultas a este (append)

**Comment by andresfdezc** [comment]
![screen shot 2017-10-02 at 5 05 53 pm](https://user-images.githubusercontent.com/11430184/31096925-fbd066da-a793-11e7-8fbf-356307462834.png)

**Comment by andresfdezc** [comment]
#378
