### ISSUE TITLE
Problema con Currency Converter

### ISSUE THREAD

**Issue by antoniacaceres** [IIC2233/syllabus#407]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Holaa, instalé el currency converter y al usarlo me sale este error <currency_converter.currency_converter.CurrencyConverter object at 0x10be7f050> y no encontré por qué ocurría en internet, no lo puedo usar. Gracias de antemano!

**Comment by matiasfernandez1** [comment]
Hola @antoniacaceres, ¿podrías copiar un poco más de lo que te aparece como error?
Porque con lo que copiaste no más estás dando la información sobre en qué objetivo ocurrió el error.

**Comment by antoniacaceres** [comment]
Ups creo que encontré el error, estaba literal imprimiento CurrencyConverter() con el código del link:

from currency_converter import CurrencyConverter
c = CurrencyConverter()
c.convert(100, 'EUR', 'USD')
print(c)

Pero muchas gracias de todas formas!

**Comment by matiasfernandez1** [comment]
Ah, tiene sentido jaja. De nada, suerte.
