### ISSUE TITLE
Problema fundamental en la ejecucion del main

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#407]
Hola! Tengo un error que no me permite desarrollar mi tarea de forma optima.
Tengo mi interprete listo y funciona. Si lo corro en consola como sigue: `print(gettie(["asignar", "x", ["extraer_columna", "registros", "tiempo_sano"]]))` Todo va bien, pues se printea None en la consola. Ahora si lo llamo en el contexto de la GUI, la ejecucion de mi intreprete ocasiona un colapso en esta, y se cierra. La forma en que lo llamo es la sgte: 
```
def process_consult(self, querry_array):
        # Agrega en pantalla la solución. Muestra los graficos!!
        print(querry_array)
        x=str(gettie(querry_array))
        text = "Probando funcion\nConsulta 01\n"
        self.add_answer(x)`
```
Corriendo el main dado por ustedes. AYUDA por favor, no entiendo que error esta ocurriendo pues no desarrolle el GUI.

**Comment by Hernan4444** [comment]
![image](https://cloud.githubusercontent.com/assets/15641721/25688170/57a9c432-3053-11e7-87c9-828fcdd9c2a1.png)

Tal como se indica en la imagen, add_answer muestra un **texto** y en tu caso le estás mandando un None. Intento con poner `str(x)`

Saludos!
