### ISSUE TITLE
Duda cosechar plantas

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#407]
Hola como se cosechan las plantas ya que buscando en el enunciado no logro encontrarlo
Solo aparece que los cultivos ya cosechados de la planta se recogen caminando sobre ellos
Gracias de antemano

**Comment by gatochico** [comment]
Hola!
Tienes razón :0 no está explicitado el cómo cosechar los cultivos. Debido a esto, **queda a tu discreción** el cómo se realizará esto, **y debes explicar tu decisión en tu README**. Una sugerencia podría ser el mediante un _click_ en el sprite del cultivo listo para cosechar, aunque si deseas hacerlo de otra forma, estás en toda libertad de hacerlo.

Éxito con la tarea :man_farmer: :man_farmer:
