### ISSUE TITLE
[Cortito-detalle] Mostrar estado

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#408]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### En el enunciado, menús solamente aparecen el menú inicio y el menú de acciones.
![image](https://user-images.githubusercontent.com/66154723/116477517-bbfe8d00-a84a-11eb-99fd-8aeb5ee05fd2.png)
### Luego, en la descripción de la **acción** de mostrar estado, solo hace referencia al print que debe hacer
![image](https://user-images.githubusercontent.com/66154723/116477495-b6a14280-a84a-11eb-891b-923cec2b70c0.png)

## Pero, revisando la pauta, vi que tenía este punto que me confunde mucho;
![image](https://user-images.githubusercontent.com/66154723/116477615-dcc6e280-a84a-11eb-966c-abb74b3ea367.png)
## **En mi caso, yo implementé esta opción solamente como una función que printea lo pedido, y, naturalmente se vuelve automáticamente al menú de inicio, con lo cual el siguiente input del usuario es directamente sobre este menú de inicio. ¿Es esto lo que piden, o quieren que creemos un ciclo solamente para esta función que solamente tome un input para salir?**

**Comment by DomingoCarvajal** [comment]
Hola @fernandosmither!

En la issue #334 se responde tu pregunta.

**Comment by fernandosmither** [comment]
> Hola @fernandosmither!
> 
> En la issue #334 se responde tu pregunta.

Gracias, no había cachado porque hicieron dos preguntas a la vez. Entonces asumiré que no es necesario tomarlo como menú
