### ISSUE TITLE
Gasto de energía de plantar semilla

### ISSUE THREAD

**Issue by enzoyacometti** [IIC2233/syllabus#408]
Hola,

En el modulo de parametros_acciones.py no se especifica cuanto es la energía que toma plantar una semilla, ¿debo agregar esto yo al modulo? ¿o lo agrego a parametros_generales.py?

Gracias.

**Comment by gatochico** [comment]
Hola! Tienes razón, no está explicito el valor que gasta el plantar la semilla, por lo que el valor de dicha acción queda a tu criterio (que valga lo mismo que otra accion, o tenga su propio parámetro, por ejemplo). 

Si deseas agregarlo como parámetro, fijate que el enunciado indica:
![image](https://user-images.githubusercontent.com/37161120/66311483-f90bd300-e8e4-11e9-8bcd-6056a486c0db.png)
Por lo que cualquier parámetro que no esté y desees agregar deberás agregarlo a `parametros_generales.py` o no se subirá y no podremos correr tu tarea :(

Éxito!

**Comment by lucastack** [comment]
@gatochico Con respecto a que no tenemos que subir parametros_plantas.py ni ninguno que no sea parametros_generales.py : se asume que testearán nuestro código con otros archivos parametros_XXXX ? o que tenemos que incorporar TODOS los parametros dentro de parametros_generales.py?

**Comment by gatochico** [comment]
Puedes asumir que cualquier parámetro que este en `parametros_plantas`,`parametros_precios`,`parametros_acciones` no debe ser añadido a parametros generales, ya que al probar tu tarea nosotros agregaremos una copia de estos 3 archivos a tu carpeta.

`parametros_generales` es para agregar cualquier parametro que no este en esos tres archivos, y consideres/el enunciado indique sean cruciales para modelar tu tarea. Ese se sube, y usaremos el que subas a tu repo al momento de probar.

Saludos! :cat:
