### ISSUE TITLE
test_elementos_prohibidos y tupla

### ISSUE THREAD

**Issue by emivenezian** [IIC2233/Syllabus#408]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

en una funcion me sale false porque:  Utiliza 'tuple' (línea 288) [for distrito_id, comunas in distritos_comunas.items():]

pero tengo entendido que eso si se puede hacer, ademas lo uso en otras funciones y me sale true

**Comment by Hernan4444** [comment]
Hola @emivenezian 

Lo que ocurre es que ese esa línea estas **desempaquetando** una tupla cuando haces ` distrito_id, comunas in distritos_comunas.items()`. Esto implica que el script detecta que estás creando, por un pequeño momento, una tupla sin utilizar comprensión. Esto es similar al caso expuesto en #406, por lo cual recomiendo no desempaquetar el elemento y con eso ya no debería salir `false` por el uso de tuplas.

Sin ver el código, puedo asumir que en otras partes te sale `True` porque estás haciendo eso dentro de un reduce o función generadora, que son los 2 casos donde si permitimos crear estructuras sin necesidad de usar comprensión.

Dado que este script es el que se utilizará para verificar, si en otras consultas te aceptó hacer eso entonces puedes estar tranquila que en dicha consulta está todo bien, pero en las que te diga `false` es donde deberás actualizar el código para que dicha consulta esté 100% válida.

Espero que haya resuelto tu duda. ¡Éxito en tu tarea! 🚀
Saludosヾ(＾-＾)ノ

**Comment by emivenezian** [comment]
osea que si mi funcion es generadora si puedo desempaquetar tuplas? ahora me salen todas mis funciones como true, a pesar que si uso ese formato.

**Comment by Hernan4444** [comment]
Hola @emivenezian 

Si, si la función es generadora, puedes crear estructuras sin usar comprensión y desempaquetar tuplas cae dentro de dicha creación.

Saludos!

**Comment by josefinaabbott** [comment]
No me funciona desempaquetar las tuplas como mencionan, imposible que permitan el uso de tuplas para la tarea, llevo varias horas buscando otras formas y aún no lo logro.

**Comment by Hernan4444** [comment]
Hola @josefinaabbott 

Los casos que el script está detectando como `false` son lo casos que se alinean al _disclaimer_ de la tarea, es decir,  apunta a los casos que queremos que eviten porque facilmente puede ocasionar que se empiece a dejar de lado el paradigma funcional. 

Por lo tanto, si el script indica que no se cumple, entonces habrá que iterar esa sección de código, tal vez buscar otra via que no implique la creación de tuplas o de desempaquetar los elementos, ahí hay comandos que pueden crearte las tuplas por dentro y te la dan lista para que tu puedes usarla con [0], [1], [2], etc. Incluso, como mini validación, ejecutamos este script con la solución de la tarea y pasó el script. Esto es para indicar que hay formas de enfrentar estas consultas con las restricciones dadas en el _disclaimer_, en especial con la flexibilidad que dentro de un `reduce` o de una función generadora, se autoriza este tipo de estructuras de datos. Aquí recomiendo revisar [esta issue](https://github.com/IIC2233/Syllabus/issues/339) donde incluirmos algunos ejemplos de casos que pueden programar con estructuras y te pueden ayudar a buscar alternativas.

Por otro lado, mucho ojo que si haces algo como:
- `[ (x, y) for x,y in ... ]`
- `( (x, y) for x,y in ... )` 

Efectivamente estás creando una lista o generador por compresión, lo cual está permitido, pero adentro de dicha estructura estás creando una tupla sin compresión y eso es lo que se queja el script: que adentro se construya una estructura de una forma que no sigue el _disclaimer_,

Saludos!
