### ISSUE TITLE
Atributo excelencia y respeto deportistas

### ISSUE THREAD

**Issue by jorge-schenke** [IIC2233/syllabus#408]
Hola, creo que hay un error en el enunciado.

En 4.4: Campeonato, específicamente en premiar a deportistas y delegaciones se indica que se debe castigar al perdedor con una baja de 10 en su moral y de 0.02 en su excelencia y respeto, sin embargo los deportistas no tienen el atributo excelencia y respeto, como se indica en la explicación de la entidad.

¿No se debería referir a la excelencia y respeto de la delegación?.

Muchas gracias

**Comment by baosse** [comment]
Holaa Jorge! 
Como dice el enunciado se deberá "_Premiar a los Deportistas y sus Delegaciones_" y con esto va también la parte del perdedor. Efectivamente la parte de excelencia y respeto hace referencia a la clase Delegación, ya que esta también se verá perjudicada con la derrota de su deportista.
Espero que te haya quedado más claro.
Mucho éxito con tu tarea!✨
