### ISSUE TITLE
Duda sobre las bases de datos

### ISSUE THREAD

**Issue by Javierdr** [IIC2233/Syllabus#408]
¿Las bases de datos (genomas.txt y listas.txt) serán las mismas al momento de corregir la tarea o estas pueden cambiar ?

**Comment by Arcoirisky** [comment]
Estoy segura que esa pregunta fue respondida en otra issue. Intenta buscarla entre las que están cerradas si es que no la encuentras entre las abiertas :D

**Comment by Arcoirisky** [comment]
Sep. Fue respondida en otra issue y está abierta :)

**Comment by Javierdr** [comment]
busque pero no encontre jajajajaj lo intentare nuevamente.
