### ISSUE TITLE
Tipo de dato en MovieError?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#408]
En el enunciado dice:

> Puede asumir que un dato sin definir se denota con N/A en la base de datos. Cuando se levanta el error, se debe indicar el nombre de la excepción, de la consulta donde se generó el error, el nombre de la película que generó el error y **el tipo de dato que generó el error**. Ejemplo:
> - "`MovieError: successful_actors, Titanic, actors`"
> - "`MovieError: highest_paid_actors, Iron Man, box_office`"

A que se refieren con _tipo de dato_? porque los ejemplos del enunciado no me lo dejan muy claro, dado que en ninguno de los dos casos, los tipos de datos son parámetros de la funcion, y en el primero caso, el valor no corresponde a una columna del archivo (que fueron mis dos interpretaciones de "_tipo de dato_")

**Comment by jmwielandt** [comment]
Me sumo con otra duda:
Puede ser "Internet Movie Database" o debe ser "rating_imdb"?
![image](https://user-images.githubusercontent.com/37153467/39496084-72a47208-4d73-11e8-97e8-c8b0aedca8f7.png)

**Comment by santilaguna** [comment]
@Hernan4444 cuando evaluamos un tipo de dato como input ¿tenemos que restringir el rango también?
Ejemplo:
["take_movie_while", ["load_database"], "IMDb", "<", 101]
¿demos retornar un generador con todas las peliculas o debemos levantar WrongInput?

**Comment by Hernan4444** [comment]
@santilaguna no quedó especificado en el enunciado. Por simplicidad lo dejaría así (retornando todas las películas).
Saludos ✌️

**Comment by pcseisdedos** [comment]
@Hernan4444 de forma análoga para la consulta popular_movies si r_min es mayor que r_max no deberíamos retornar ninguna película?
aprovecho de preguntar si las películas con rating r_min y r_max no están incluidas, es decir, si son iguales tampoco deberíamos retornar ninguna película?

**Comment by Hernan4444** [comment]
@pcseisdedos lo mismo que santilaguna, no qudó bien especificado en el enunciado esos casos. Se deja a tu criterio pero no olvides especificar en el Readme.

Saludos ✌️
