### ISSUE TITLE
Uso for por compresión actividad 3

### ISSUE THREAD

**Issue by JosefaATP** [IIC2233/Syllabus#408]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Hola! Cómo están?

Se puede usar for por compresión en la actividad? o tampoco se puede?

Saludos!

**Comment by Hernan4444** [comment]
Hola @JosefaATP 

Depende del caso. Esto es porque tal como dice el enunciado para la parte 2:

> ...se encuentra estrictamente prohibido el uso de: ciclos for y while; estructuras de datos list, tuple, dict, set; **cualquier tipo de estructura creada por comprensión**; y otras librerías diferentes a las dadas en los archivos base.

Por lo tanto, si el `for` por compresión lo haces para crear, por ejemplo, una lista: ahí irías en contra del enunciado. Sin embargo, si lo ocupas para crear un generador por compresión, ahí no tendrás problema. De todas cormas, la AC está diseñada para que no necesites recurrir a ningún tipo de `for` en la parte 2. Todo se puede lograr hacer con los comandos nuevos aprendidos esta semana (map, filter, reduce, lambda e itertools).

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ

**Comment by JosefaATP** [comment]
gracias!
