### ISSUE TITLE
Agregar atributos extras 

### ISSUE THREAD

**Issue by tsmatus** [IIC2233/syllabus#409]
Hola, quiero saber si puedo agregar atributos a las clases que nos dieron para modelar, por ejemplo, puedo agregar el precio en la clase de los alimentos o esta restringido a lo que nos dieron

**Comment by Dnpoblete** [comment]
Hola @tsmatus, tu duda ya fue resuelta en la issue #261, para que la revises y en caso de tener dudas sobre esto preguntes en esa issue 😄
