### ISSUE TITLE
Error en cargar archivos(locales)

### ISSUE THREAD

**Issue by ArielV24** [IIC2233/Syllabus#409]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Al cargar archivos, si son tipo local me funciona correctamente si utilizó los elementos de la lista como str, pero al momento de intentar cambiar los str(por ejemplo ['385', '626']) a int me aparece que '' no es un int.

![image](https://github.com/IIC2233/Syllabus/assets/162527571/30e38388-b2fa-4432-bc49-cd34f60975b3)

Hice push de la tarea por si es necesario
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by ClemoAcevedo** [comment]
Hola @ArielV24 

El error `ValueError: invalid literal for int() with base 10: ''` ocurre cuando intentas convertir una cadena vacía a un entero. Revisa cómo limpias los datos en tu lista antes de convertirlos, especialmente en el caso de locales. Asegúrate de que no hay elementos vacíos en tu lista de enteros :)

**Comment by ArielV24** [comment]
Hola, entiendo que esa es la razón del error, pero mi duda esta en que si dejo los elementos de la lista como str esta se muestra correctamente, para verificar revise el tamaño de la lista, y en el caso ['385', '626'], esta tiene largo 2, por lo que no debería haber ninguna cadena vacía.

**Comment by ClemoAcevedo** [comment]
Claro, como lista lo ves bien. Por lo tanto tu problema se encuentra cuando vas a manejar y manipular la lista
