### ISSUE TITLE
Entrenamiento de deportistas

### ISSUE THREAD

**Issue by Zenos-Paradox** [IIC2233/syllabus#409]
Cómo se calcula cuánto aumenta el atributo entrenado? En el enunciado dice PUNTOS_ENTRENAMIENTO, pero no sugiere ningún valor.

**Comment by retamalcito** [comment]
¡Hola @Zenos-Paradox!

Como dice el enunciado, el método `entrenar` **suma** al valor actual del atributo el parámetro `PUNTOS_ENTRENAMIENTO`. Como se mencionó en la issue #335, puedes definir el valor de este parámetro con total libertad, dado que no se explicita un valor en el enunciado.

¡Saludos!

**Comment by Zenos-Paradox** [comment]
Gracias! no había encontrado esa issue

**Comment by domingo2000** [comment]
Otra pregunta del entrenamiento, en la delegacion IEEE dice que la formula de entrenamiento se pondera por 1.7, pero los parametros de los deportistas son ``Int`` y no ``float``, por lo que no entiendo como ponderar el entrenamiento para fijar dichos parametros como int tras entrenar en IEEE
