### ISSUE TITLE
Sprite inventario

### ISSUE THREAD

**Issue by mpbascunan** [IIC2233/syllabus#409]
Holaa, podrían subir la sprite del inventario cuadrado que sale en el enunciado por favor?

**Comment by dgzmr** [comment]
Es un objeto QFrame, busca en la documentacion :)

**Comment by gatochico** [comment]
Hola! Hay 2 opciones: 
- Tal como dice @dgzmr , usar el objeto QFrame de pyqt5 
- Editar los _templates_ de ventana e inventario que están en la carpeta tarea del syllabus en tu editor de imágenes favorito, y luego subir estos a tu repo junto con tu tarea.
Usa el que te sea más facil! Éxito!
