### ISSUE TITLE
Archivo main.py de la recorrección

### ISSUE THREAD

**Issue by agustincampeny** [IIC2233/Syllabus#409]
No me queda muy claro en que debe consistir este archivo.

¿Hay que hacer una interfaz completa para el programa o solo es necesario demostrar mediante ejemplos que las funcionalidades existen y funcionan?

Saludos.

**Comment by Hernan4444** [comment]
@agustincampeny hola, la segunda opción. La idea es que hagas ejemplos que demuestren el funcionamiento. 

Ten en consideración que el ayudante puede cambiar algunos datos de tu ejemplo para ver que no estás probando un único caso en donde funcionan tus funcionalidades. 

Saludos ✌️

**Comment by agustincampeny** [comment]
Muchas gracias!
