### ISSUE TITLE
Problemas al coordinar aparición de moneda y mapa

### ISSUE THREAD

**Issue by Juaco97** [IIC2233/syllabus#409]
Hola! Estoy tratando de hacer que aparezcan las monedas de manera aleatoria, pero cuando instancia el método que me permite generar monedas desde el inicio se me bloquea el juego, luego continua "generándose" las monedas (aunque no se muestran, porque está haciendo el loop de creacion) y cuando terminan de crearse las monedas me deja volver a jugar. Intenté poner la generación de monedas en distintas partes (después de empezar a jugar, cuando creo el mapa, etc) pero aun asi no mejora :s

Esto es mas o menos lo que me sucede:

![Captura de Pantalla 2019-05-25 a la(s) 21 34 06](https://user-images.githubusercontent.com/37164418/58376297-b351fd80-7f35-11e9-8482-94f128007004.png)

**Comment by Juaco97** [comment]
Se me olvidó mencionar que acabo de actualizar el código que subí a mi repo, por si alguien del staff me puede ayudar

**Comment by jaromero6** [comment]
Hola
Revisé tú código, te recomiendo verificar esto:
- Estás haciendo calculos que podrías realizar una vez en el init de tu clase (el cálculo de posiciones posibles al agregar las monedas), hacer esto una sola vez agiliza tu programa
- **OJO**: con los if y else, podría darse el caso que de la forma que estés llamando al método le estés mandando una señal que haga que nunca entre en el if que haría que se muestre el label que despliega tu moneda.
- Cuidado con estar sobreescribiendo atributos, si tienes un atributo que guarda un label y le añades una imagen es correcto. Pero si al mismo label le vuelves a agregar una imagen, entonces **no** tendrás 2 labels con dos imagenes distintas, tendrás uno con la última que agregaste, lo que eventualmente haría que solo tengas una moneda en el mapa, ve la opción de añadir a una lista los labels que muestren monedas por ejemplo.

Finalmente, ojo con la funcionalidad de un método, si yo tengo un método agregar_moneda, la intución de lo que debería hacer ese método es buscar posición por ejemplo, crear el label y mostrarlo, no tiene sentido que el método quite la moneda, porque su función es agregar, para quitar la moneda haría un método quitar_moneda donde haga el hide del label por ejemplo.
Espero que te sirva

**Comment by Juaco97** [comment]
> Hola
> Revisé tú código, te recomiendo verificar esto:
> 
> * Estás haciendo calculos que podrías realizar una vez en el init de tu clase (el cálculo de posiciones posibles al agregar las monedas), hacer esto una sola vez agiliza tu programa
> * **OJO**: con los if y else, podría darse el caso que de la forma que estés llamando al método le estés mandando una señal que haga que nunca entre en el if que haría que se muestre el label que despliega tu moneda.
> * Cuidado con estar sobreescribiendo atributos, si tienes un atributo que guarda un label y le añades una imagen es correcto. Pero si al mismo label le vuelves a agregar una imagen, entonces **no** tendrás 2 labels con dos imagenes distintas, tendrás uno con la última que agregaste, lo que eventualmente haría que solo tengas una moneda en el mapa, ve la opción de añadir a una lista los labels que muestren monedas por ejemplo.
> 
> Finalmente, ojo con la funcionalidad de un método, si yo tengo un método agregar_moneda, la intución de lo que debería hacer ese método es buscar posición por ejemplo, crear el label y mostrarlo, no tiene sentido que el método quite la moneda, porque su función es agregar, para quitar la moneda haría un método quitar_moneda donde haga el hide del label por ejemplo.
> Espero que te sirva

De todas formas, al cambiar algunas de las cosas que me dices, me sigue arrojando el problema de que cuando paso de la primera ventana (de inicio) a la segunda (de preparacion), primero crea las monedas, les da el tiempo y posiciones que deberían tener, las elimina y después me abre la ventana para poder jugar (hago print en todas partes y por eso pude saber la lógica que tenía). No sé me ocurre como sincronizar la aparición de ambas cosas a la vez (sin que una interfiera en la otra).

**Comment by jaromero6** [comment]
Hola de nuevo y disculpa la demora:
El problema que tienes es que estás creando las monedas solo en ese instante y en ninguna otra parte más. Para solucionar esto, deberías tener un thread o timer que vaya creando las monedas mientras esté la ventana de juego abierta.
Ánimo con la entrega
