### ISSUE TITLE
[Cortito-detalle] DCCapitan desencallador

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#409]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Mi duda es, Se debe contar o no ?, y ¿Es esto relevante realmente, o simplemente se puede dejar especificado en el readme como un supuesto?

**Comment by fernandosmither** [comment]
## Con contabilizar, me refiero sumar uno a los encallamientos históricos del mostrar_estado() del menú inicio

**Comment by Emiliax16** [comment]
Como dice el enunciado, el DCCapitán desencalla el barco! pero especifica lo que hiciste en el README no más, ya que es muy lógico tu supuesto.

**Comment by fernandosmither** [comment]
> Como dice el enunciado, el DCCapitán desencalla el barco! pero especifica lo que hiciste en el README no más, ya que es muy lógico tu supuesto.

De todas formas esto es muy fácil de cambiar, si lo tengo así y lo dejo como supuesto en el readme no se descuenta, o lo cambio?

**Comment by Emiliax16** [comment]
Para evitar descuentos, simplemente especifica bien tu supuesto y la justificación en el README, como dije anteriormente, es una lógica super válida!
