### ISSUE TITLE
For y While dentro de un generador.

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#409]
Se que esta permitido usar for y whiles dentro de un generador, pero mi pregunta es la siguiente, lo unico que requiere una funcion para ser generador es usar `yield`?

Segunda pregunta, solo se permite usar for para hacer `yield`?
Osea, no esta permitido usar un for loop para hacer calculos dentro de la funcion y luego hacer otro para utiizar yield?

Gracias!

**Comment by Hernan4444** [comment]
> Osea, no esta permitido usar un for loop para hacer calculos dentro de la funcion y luego hacer otro para utiizar yield?

Si ese for **no** está junto a un yield (lo que lo convierte en un generador)*, en una lista por compresión o en un generador por compresión y lo vas a usar para una logica del programa (como calcular cosas) no está permitido, para eso está funcional.

* for x in ...:

**Comment by KnowYourselves** [comment]
gracias!
