### ISSUE TITLE
duda Git quitar archivo

### ISSUE THREAD

**Issue by rominaarancibia** [IIC2233/Syllabus#409]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, accidentalmente subí un archivo dentro de frontend que quería eliminar a git. Existe una forma segura de sacarlo si quiero seguir subiendo respaldos a mi repositorio?. O bien solamente mencionar en el README.md que se ignore?
Gracias

**Comment by Hernan4444** [comment]
Hola,

Si ese archivo no es necesario para la corrección, lo ideal sería no entregarlo (para no aumentar más el peso de las tareas). Para esto, dado que ya lo subiste, se recomienda:
1. Sacar el archivo en cuestión de tu carpeta. Por ejemplo, moverlo a tu escritorio.
2. Hacer git add commit y push para subir el cambio que el archivo "fue eliminado". Así tu repo público ya no lo tendrá.
3. Añadir, en el `.gitignore`, el nombre de ese archivo que no quieres que se suba
4. Recuperar el archivo que sacaste de (1). 

De esta forma, el archivo quedará en tu PC, pero no en el repo que está en la nube.

Saludosヾ(＾-＾)ノ
