### ISSUE TITLE
JesÃºs pese a que puse encoding="latin-1"

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#409]
Hola, tengo esto en mi codigo:

with open("genomas.txt", "r", encoding="latin-1") as file:
    people = [Person(*(person_parser(line))) for line in file]

y me tira un error, por lo que debbugeando puse que imprimiera cada linea y lo que ása es que ,e imprime la linea como 

5JesÃºs10De NazaretAAG3GTC6GGA1TCT14GTA13CTC25....

Que hago D: ?

**Comment by Arcoirisky** [comment]
Intentaste con utf-8?

**Comment by Arcoirisky** [comment]
Pd: No muestres de esa forma tu código. Mejor di que intentas abrir un archivo con encoding 'latin-1'

**Comment by Kitaps** [comment]
oh wena, eso era :)
