### ISSUE TITLE
Actualización de archivos

### ISSUE THREAD

**Issue by EmeraldMP** [IIC2233/syllabus#41]
Hola!

Es necesario actualizar los archivos entregados? Si es así, hay que ir actualizándolos cada vez que agregue o elimine algo o se puede actualizar una vez que se salga de la aplicación  creada?

Saludos!

**Comment by KnowYourselves** [comment]
Hola @EmeraldMP!

Efectivamente, los cambios que se realicen deben verse reflejados en los archivos. El momento en que se realicen los cambios queda a tu criterio.

Éxito!

**Comment by frosatis** [comment]
Hola @KnowYourselves ! 

Mencionas que el momento en que se realicen los cambios queda a nuestro criterio, pero en el enunciado (sección 4.3) se indica que debemos actualizar el archivo "seguidores" cada vez que se cree o elimine una relación de seguimiento.

¿Podrías aclarar esto por favor?

Muchas gracias!

**Comment by KnowYourselves** [comment]
Hola @frosatis!

Esa parte del enunciado hace referencia a que todos los cambios en seguidores que se realicen se deben ver reflejados en el archivo `seguidores.csv`. Estos se pueden realizar a penas sucedan o antes de que finalice el programa. 

Éxito!

**Comment by frosatis** [comment]
Muchas gracias!
