### ISSUE TITLE
[OOP] Al llamar métodos definidos con super() (en una subclase) se retorna None ¿Por qué?

### ISSUE THREAD

**Issue by dvillas28** [IIC2233/Syllabus#41]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda
Tengo una clase `Base` con un metodo definido, luego una subclase `Subclase` que hereda de esta, donde re-defino el metodo accediendo a la definicion original de la superclase. Al instanciar a la subclase y llamar al metodo obtengo `None`. Adjunto codigo:

```python
class Base():
    def metodo_1(self):
        return 'soy el metodo 1'
    
class Subclase(Base):
    def metodo_1(self):
        super().metodo_1()

i = Subclase()
string1 = i.metodo_1()
print(f"Usando el metodo 1:  {string1}") # string1 retorna None ¿Porque?
```
Esto me surgio cuando estaba trasteando con clases abstractas (donde habia un ejemplo en el que hacian algo parecido, a diferencia de que ese metodo no retornaba nada), asi que pense que podia deberse por eso, pero luego lo probe con una clase normal y corriente como en el ejemplo y sigue sucediendo. Segun el juypter de Herencia, `super()` invoca directamente la ejecucion del metodo, asi que ***no me queda claro porque se retorna *None****. Cabe añadir que si no re-defino el metodo y simplemento dejo que la subclase lo herede, esto no sucede.

Agradezco cualquier aclaracion! 
Saludos!

**Comment by Dvckhv** [comment]
Hola @dvillas28!

Piensa que metodo_1 de Base y metodo_1 de Subclase son 2 metodos diferentes, por lo que estás haciendo lo siguiente:

```python

def funcion_1():
    return 1
def funcion_2():
    función_1(): // solo se llama, no se retorna ni almacena
    //termina retornando None
```
Por lo que retorna Base.metodo_1() se pierde en la ejecución del método de la subclase, sería totalmente diferente si defines su método de la siguiente forma:

```Python
    def metodo_1(self):
        return super().metodo_1()

```
Donde el valor que retorna el método de la superclase es retornado también por el método de la subclase, Esto no pasa cuando no se define, porque no sobreescribes el método de la clase padre (recordar que al heredar se traspasan todos los metodos de padre a hijo).

Espero te sirva :)

**Comment by dvillas28** [comment]
Entiendo lo que me estas explicando, al final estoy llamando a una funcion2 que llama a otra funcion1 que retorna algo pero que no esta siendo asignada a nada. Pero me surge otra duda entonces: ¿Porque para el `__init__` de una subclase igual se pone solamente `super().__init__()` y no se le antepone el `return`? ¿Podra ser para que la funcion, primero llame al `__init()__` de la superclase, este se ejecute normalmente, y luego nos deje (por si es que se necesita) definir algunos atributos en la subclase?

Saludos!

**Comment by Dvckhv** [comment]
El método `__init__` no retorna algo definido por nosotros, por lo que no es necesario añadir el `return`, pero si lo hiciera podrías guardarlo en una variable o retornarlo como mencioné, cuéntame si sigues con dudas :)

**Comment by dvillas28** [comment]
Ya, me queda claro

Muchas gracias por tu respuesta, saludos!

**Comment by dvillas28** [comment]
creo que borre sin querer mi comentario, no queria cerrar la issue xd
Me queda claro ahora, muchas gracias!
saludos!
