### ISSUE TITLE
Líder de la civilización

### ISSUE THREAD

**Issue by isihirmas** [IIC2233/syllabus#41]
Hola! 
El líder de la civilización puede morir? Es decir, es considerado como una persona más, con HP incluido? O es una característica de la civilización que se define al momento de escogerla y luego no cambia.

Gracias!

**Comment by hbkim94** [comment]
Hola!

Lo segundo es lo correcto. No te preocupes por los líderes, son simplemente representaciones que usamos para florear el enunciado :) 

Saludos!

**Comment by Juaco97** [comment]
> Hola!
> 
> Lo segundo es lo correcto. No te preocupes por los líderes, son simplemente representaciones que usamos para florear el enunciado :)
> 
> Saludos!

Entonces finalmente nos quedamos como que cada Lider es una persona solamente? No se especifica su HP, por eso lo pregunto.

**Comment by hbkim94** [comment]
@Juaco97 Considera que líderes no existen físicamente en el juego 😁 saludos!
