### ISSUE TITLE
S01 ejercicio 2.1: namedtuple y 'property' vs. int

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#41]
¡Hola! Estoy haciendo el ejercicio propuesto 2.1 usando namedtuple como estructura de datos para `Carta`. Tengo un problema con las namedtuples que no entiendo: cuando trato de comparar el puntaje de ataque y el de defensa, me tira el error
```
TypeError: '<' not supported between instances of 'property' and 'property'
```
Traté de arreglarlo usando `int()` sobre ambos valores, guardándolos como variables y comparando ésas, pero me arrojó este otro error:
```
TypeError: int() argument must be a string, a bytes-like object or a number, not 'property'
```
Me consta que los valores quedaron guardados como int en la namedtuple, o por lo menos eso traté con estas líneas:
![image](https://user-images.githubusercontent.com/61999464/90523802-4e3a8700-e13b-11ea-94e0-0dff0ce1ba61.png)
¿Alguien me explica cómo trabajo con ints dentro de una namedtuple, porfa? Graciasss

**Comment by furcelay** [comment]
Hola!
Las  `namedtuple` se instancian de la siguiente manera, primero creas un constructor de las `namedtuple` que deseas, en éste caso *cartas*:
```python
Carta = namedtuple("carta", ["atributo_1", "atributo_2", "atributo_3"])
``` 
El primer argumento corresponde al nombre de tus `namedtuple` y luego viene una lista con el nombre de los atributos, todos deben ser *strings*.

Usamos el constructor para crear cartas, debemos darle los valores para los atributos (pueden ser cualquier objeto):
```python
carta_1 = Carta(atributo_1="foo", atributo_2=4, atributo_3=[1, 2, 3])
carta_2 = Carta(atributo_1="bar", atributo_2=-3, atributo_3=[4, 5, 6])
```
(Puedes omitir el nombre `atributo_1=`)

Podemos acceder a los atributos igual que con objetos:
```python
carta_1.atributo_2   # retorna 4
```

Por lo que vero en tu código puede que estés instanciando mal las `namedtuple` te recomiendo crear el constructor `Carta` antes del loop y en cada iteración del loop usarlo para crear una carta con los datos  de la línea del csv (la segunda línea en tu código). Espero que eso solucione tu problema

**Comment by sbcorrea** [comment]
AAAAH ya entiendo jajaja muchas gracias!!
