### ISSUE TITLE
Error de indentacion en SublimeText3

### ISSUE THREAD

**Issue by miguelsaavedra27** [IIC2233/syllabus#41]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema
Al hacer enter en una función del archivo cargar.py (de la AF1) se me indentaba automáticamente pero después me salía este error: 

  , line 19
    dic_ingredientes[linea[0]]=linea[1]
                                      ^
TabError: inconsistent use of tabs and spaces in indentation

La única forma en que pude solucionar esto era haciendo enter, borrando hasta llegar a la izquierda de la pantalla y apretando espacio las "4x veces" que fuese necesario. Esto hacía muy tedioso el trabajar sobre una función ya escrita en la que yo tuviese que rellenar y/o editar.

Gracias!!!

**Comment by cristobalnic** [comment]
Hola @miguelsaavedra27!

El problema que tienes se puede solucionar rápidamente haciendo que al escribir un "tab", esta tecla genere automáticamente 4 espacios. Para ello debes ir al menú de Sublime **View -> Indentation** y marcar la opción **Indent Using Spaces**. A continuación te dejo un screenshot para que la encuentres más fácilmente!

![image](https://user-images.githubusercontent.com/48327806/112537662-b87c6f80-8d8d-11eb-8b9b-2125c3767c25.png)

Ojalá esto te solucione el problema!

**Comment by kunafuego** [comment]
Muchas gracias! No había preguntado yo pero tuve el mismo problema jajaja

**Comment by miguelsaavedra27** [comment]
Gracias!
