### ISSUE TITLE
Duda al nombrar variables en for

### ISSUE THREAD

**Issue by Patodinosaurio** [IIC2233/syllabus#41]
Se supone que el nombre de las variables debe ser descriptivo, eso lo entiendo. Pero mi duda es si cuando usamos **_for_** tipo:

>_for **i** in lista:_

o

>_for **i** in range(5):_
 
ese **i** debe tener también un nombre descriptivo o podemos dejarlo como **i**?

Saludos y de antemano gracias c:

**Comment by jmwielandt** [comment]
Hola! 

La idea es que, por sobre todo, el código sea facilmente entendible (que aunque lo parezca, no es tan subjetivo, por algo las empresas de desarrollo normalmente tienen guías de estilo que todos sus trabajadores deben seguir). En este caso, el consejo que te puedo dar es que si algo es una entidad (**no** confundir con "objeto") en sí misma, le des nombre de entidad.

Por ejemplo:

```python
for index in range(len(my_list)):
    do_sth_with(my_list[index])
```

En este caso, la variable del for es usada como índice para sacar cosas de la lista, por lo que "index" es un mejor nombre que "i".

Otro caso es el `for i in lista` que pones, en ese caso es mejor nombrar al objeto que está dentro de la lista por lo que es, cosas como:

```python
for duck in list_of_ducks:
    do_sth_with(duck)
```
En este caso, "duck" es mejor que "i", al tratarse de una lista de patos.


**¿Cuándo usar "i" y nombres por el estilo ("j", "k", ...)?**
En lo personal lo considero apropiado para contadores, principalmente. Por ejemplo:

```python
for i, duck in enumerate(list_of_ducks):
    print(f"{i}) {duck.name}.")
```

Otra opción es cuando necesitas hacer una acción una cantidad finita de veces pero el contador no es usado, se usa el `_` como nombre (también se usa para variables que están ahí pero no vas a usar).

Ejemplo:

```python
for _ in range(30):
    print("Hola! :D")
```

Espero haber resuelto tu duda, cualquier otra cosa no olvides preguntar.
En todo caso, recomiendo que leas el [artículo de pep8](https://legacy.python.org/dev/peps/pep-0008), que al final enseña un poco sobre el lenguaje y toca muchos más temas.

Saludos!

**Comment by Patodinosaurio** [comment]
Okip, me quedó claro. **Gracias!** 

![marcianitos toy story](https://is5-ssl.mzstatic.com/image/thumb/Purple125/v4/11/60/35/1160354c-4469-5d38-a702-716800ceb0c8/source/256x256bb.jpg)
