### ISSUE TITLE
Enunciado tarea 1

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#41]
"Todos los usuarios poseen un nombre de usuario unico, un nombre, un apellido, una fecha de nacimiento,
y un balance de sus distintas currencies."
Creo que en users.csv falta una columna que diga la cantidad de "pesos" para cada currencie.

**Comment by FernandoPieressa** [comment]
Hola!

Los csv entregados no tienen toda la información necesaria para cada Clase dentro del programa, tienen solamente la información básica y el resto de los atributos necesarios los tienen que conseguir ustedes. 

Por esto mismo, para los usuarios entregados por nosotros **pueden asumir que tienen todas sus currencies en forma de orders, y están registrados en esos markets respectivamente**.

Es importante recordar que pueden generar y utilizar nuevos archivos csv a través de su programa para guardar mas información!

Saludos! :smile:

**Comment by ptflores1** [comment]
Es buena idea usar los mismos archivos csv que se entregaron pero extendiendo las columnas según necesitemos o es mejor crear archivos nuevos ?

**Comment by stephichau** [comment]
@ptflores1 hazlo como más te acomode

**Comment by sebacruzd** [comment]
@ptflores1 en todo caso, recomiendo crear archivos nuevos, ya que al modificar los csv se podrían generar errores al abrir el programa nuevamente, a menos que se maneje perfectamente ese detalle y se tenga en cuenta, pero a mi parecer sería más tedioso programarlo para que sobreescriba los archivos originales.

**Comment by rakarachon** [comment]
Hola! Perdón pero aún no entiendo bien el uso que debemos darle a los archivos csv que nos dieron. En el fondo son como ejemplos de los archivos que nuestro programa podría/debería crear? Y tampoco entiendo muy bien para que nos sirve el archivo csvgenerator.py D: De antemano gracias!

**Comment by iqacevedo** [comment]
Hola!

La función del archivo csvgenerator.py es generar las bases de datos que deben usar tu programa, ¿Por qué no ocupar solo las bases de datos que se dan? Porque tú programa debe ser capaz de leer estos archivos sin importar el orden de sus columnas. 
Respectoa a los archivos csv en si que se entregan, existen para que los utilicen para poblar su sistema, no son ejemplos en si, son la historia de lo que ha pasado en el mercado hasta que inician su programa, por lo que deben utilizarlo para crear esos usuarios, orders y currencies en su programa. Lo que dice Fernando más arriba es que esto no evita que ustedes puedan crear sus propios archivos csv luego de cargar los datos por primera vez para guardar más información de los cambios que se producen en el mercado mientras lo utilizan (cuando se crean nuevos usuarios, orders, etc.)

Saludos !

**Comment by ptflores1** [comment]
@FernandoPieressa 
> Por esto mismo, para los usuarios entregados por nosotros pueden asumir que tienen todas sus currencies en forma de orders, y están registrados en esos markets respectivamente.

Entonces dependiendo de las ordenes que tengan obtenemos los mercados a los cuales deberian estar registrados y luego revisando las ordenes con match actualizamos sus saldos ?

**Comment by rakarachon** [comment]
@iqacevedo ok, creo que entiendo. Entonces en el fondo las bases de datos que nos dieron es solo la info que existía de antes, y son distintas de las bases de datos que debería crear nuestro programa para manejar la información. Y respecto al archivo csvgenerator.py: se supone que mi programa debería estar "construido" de tal manera que sea capaz de leer cualquier base de datos que se intente ingresar (o sea en cualquier "formato de columnas"), no solo las 3 que nos dieron, entonces lo que hace el archivo al final es desordenarlas para comprobar que esto se cumple? Sorry si estoy siendo repetitiva, pero esta parte es la que más complicada me tiene, he leido el enunciado ene veces e igual no me queda del todo claro (horrible mi comprensión lectora jajaja).

**Comment by iqacevedo** [comment]
@ptflores1 es como tu dices, ademas, mientras esas orders que tienen esos usuarios no tengan match, debes considerar que tienen en su saldo esas monedas (que aun no se tranzan puesto que la order aun no tiene match).
@rakarachon es como dices, pero el formato siempre es el mismo, lo que puede cambiar es el orden de las columnas y la información de estas. 

Saludos !

**Comment by rakarachon** [comment]
@iqacevedo perfect, ya me quedo todo mucho más claro. Muchas gracias!!!!

**Comment by rakarachon** [comment]
@iqacevedo otra duda respecto a las bases de datos: las que se ingresen de manera externa para poblar el sistema pueden venir en cualquier formato de columnas, ok; pero las columnas de las bases de datos que cree mi programa después (o sea, en base a las 'externas' y a la nueva info que se vaya ingresando) si pueden tener un orden fijo, cierto?

**Comment by sebacruzd** [comment]
@rakarachon es correcto lo que dices. 
Como tú programas la manera en que se crean las nuevas bases de datos, puedes estar seguro que siempre tendrán ese orden fijo, por lo que las únicas partes de las bases de datos que pueden variar son las iniciales.

**Comment by rakarachon** [comment]
@sebacruzd bacaan! graciaaaas!!!!

**Comment by Mariana-Ortega-del-Rio** [comment]
¿Solo puedo crear nuevos archivos .csv o puedo crear archivos .txt por ejemplo?
Gracias!

**Comment by stephichau** [comment]
@Mariana-Ortega-del-Rio queda a tu criterio
