### ISSUE TITLE
Eventos

### ISSUE THREAD

**Issue by NicolasCourt** [IIC2233/Syllabus#41]
Sobre los eventos, hay prioridad con la cual reciben daño las estructuras?, EJ: primero el cuartel y despues la torre, el daño se reparte o queda a mi criterio?. Segundo, en caso de que una estructura no alcance a ser destruida, esta queda con esa vida para siempre o puede ser regenerada (usando recursos o con el tiempo)?

**Comment by Arcoirisky** [comment]
Holaaa!!
Todo eso queda a tu criterio :D

**Comment by NicolasCourt** [comment]
Gracias!! 💯
