### ISSUE TITLE
Funciones extra en functions.py

### ISSUE THREAD

**Issue by vmunozgarachena** [IIC2233/Syllabus#41]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](https://github.com/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! se pueden agregar funciones extras al módulo" functions", o ese módulo solo debe tener las especificadas en el enunciado?

**Comment by matiasmasjuan** [comment]
@vmunozgarachena Porfavor al momento de crear una _issue_ agrega un título relacionado a tu duda. De esta forma si cualquier otra persona tiene la misma duda se le haga más fácil encontrarla.
Saludos!

**Comment by terelopezc** [comment]
Hola @vmunozgarachena! No hay problema en que agregues más funciones a aquel módulo, mientras este tenga si o si las que están especificadas en el enunciado. Puedes hacer lo que para ti te resulte más ordenado, ya sea hacerlas ahí mismo o en otro módulo de tu tarea. 
A continuación te dejo dos aclaraciones del enunciado sobre esto para que te quede bien claro:

![2023-03-22 16 53 27](https://user-images.githubusercontent.com/48325070/227021973-cfb3005c-e603-491d-81c6-1dc8249404a5.jpg)

![tg_image_2663081366](https://user-images.githubusercontent.com/48325070/227022113-51dfc620-1cc8-4ac9-ba50-4f681d22d8eb.jpeg)
