### ISSUE TITLE
README en la tarea

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#41]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

¿Es necesario hacer un README para esta tarea?

**Comment by matiasmasjuan** [comment]
Hola @Fernanda1232123 !

**Sí**, es **obligatorio** la entrega del **README.md** para las tareas. En caso de no realizarlo, tendrás una penalización de una décima por no indicar los archivos necesarios para ejecutar tu tarea. Esto lo puedes ver de forma detallada en [Descuentos](https://github.com/IIC2233/Syllabus/blob/main/Tareas/Descuentos.md). Además de esto, no podrás optar a las 5 décimas de des-descuento que se ofrece en la distribución de puntajes por realizar un buen **README.md**:
<div align="center">

![imagen](https://user-images.githubusercontent.com/48495638/159589344-2e15b94f-5357-4bd4-8341-a2e872b2c66b.png)
</div>

Esto significa que en caso de tener otro tipo de penalización, ya sea por criterio de ayudante, malas prácticas, cambio de líneas, entre otras, **no podrás recuperar** esas décimas perdidas ya que no realizaste el archivo.

Ahora bien, el **objetivo** de realizar un buen **README.md** es para que les sirva de ayuda a ustedes a tener un *chek list* de los aspectos que han implementado o no implementado, e ir monitoreando el avance de sus tareas y puedan ir planificando su tiempo. Además, es de **gran** ayuda para los ayudantes al momento de corregir sus tareas, ya que les permite tener una idea de lo que han implementado y no implementado, junto con los supuestos que se realizaron, librerías instaladas o cualquier información adicional que les facilite el proceso de corrección. Es por esta razón que buscamos premiar los **README.md** útiles, claros y explicativos mediante la opción del des-descuento de hasta 5 décimas.

Saludos!
