### ISSUE TITLE
Duda enunciado -entidades

### ISSUE THREAD

**Issue by Hellonston** [IIC2233/Syllabus#41]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola!
Cuando en el enunciado nos señala sobre entidades, es una pista para trabajar con ellos como clases? (donde hace mención a usuarios, publicaciones y comentarios)

**Comment by mmunoz12** [comment]
Hola @Hellonston! No es obligatorio utilizar clases pero si se recomienda porque facilitarán la moderación de tu código ☺️ Suerte en tu tarea!
