### ISSUE TITLE
If en funciones lambda y funciones comúnes

### ISSUE THREAD

**Issue by simontoya** [IIC2233/Syllabus#410]
Hola! Quería saber cual es la diferencia entre ocupar varios o un if dentro de una función lambda o función común, en términos de memoria o cual resulta ser más rápido?

**Comment by indonoso** [comment]
Puedes dar un ejemplo?

**Comment by simontoya** [comment]
Por ejemplo:

def función():
    if condición:
        return 10
    else:
        return None

funcion = lambda x: 10 if condición else None

**Comment by indonoso** [comment]
0. Recuerda usar markdown para escribir el código

Estas mezclando dos temas en tu pregunta. No hay [diferencias significativas](https://stackoverflow.com/questions/44840101/in-python-lambda-expression-is-fast-or-the-normal-function) en performance entre usar funciones *lambda* y las funciones normales. Si hay [diferencias](https://stackoverflow.com/questions/12264834/what-is-the-difference-for-python-between-lambda-and-regular-function) en la forma en que python las representa, pero las dos son del tipo `function`, así que son tratadas igual.

[Tampoco hay diferencias](https://stackoverflow.com/a/44599923
) en performance entre usar operadores ternarios `value_true if condition else value_false` y el control de flujo como el escribiste en `funcion`. 

Lo que logran estas distintas formas es hacer el código más legible. Por ejemplo, es mucho más claro que `funcion` fuese:
```python
def funcion(x):
    return 10 if condicion else None
```
Podríamos también escribir esta función usando *lambda*.
