### ISSUE TITLE
Duda de cuando usar parametros

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#410]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

**Comment by lily416** [comment]
Hola @Ignacioislae 
 
Tal como se indica en el enunciado “debes agregar [al archivo parametros.py] cualquier valor constante en tu tarea, junto con los _paths_ que utilices”, por lo que se espera que indiques las constantes en este archivo y las utilices en tu tarea.
 
Ojo que hay que tener criterio 👀, cosas que nunca cambiarán no es necesario incluirlos dentro de los parámetros (por ejemplo, cuando en alguna fórmula se define `min(1, ...)`, el 1 nunca cambiará), pero sí deben estar los ponderadores, precios, _paths_ o cualquier otro valor que sea de ese estilo (cosas que se puedan cambiar y que tengan un efecto en la ejecución de una tarea).
 
Finalmente, ten cuidado con el nombre que le entregues a los parámetros. Te recuerdo que en el enunciado dan el siguiente ejemplo:
```python
CINCUENTA = 50                         # mal parámetro
COBRO_USO_CANAL_PRINCIPIANTE = 100     # buen parámetro
COBRO_USO_CANAL_AVANZADO = 200         # buen parámetro 
```
 
Espero que esto aclare tus dudas. Saludos 👋

**Comment by Ignacioislae** [comment]
Quede clarens. Gracias!!
