### ISSUE TITLE
Atributos deportistas IEEE al entrenar

### ISSUE THREAD

**Issue by domingo2000** [IIC2233/syllabus#410]
Una pregunta, en la delegacion IEEE dice que la formula de entrenamiento se pondera por 1.7, pero los parametros de los deportistas son Int y no float, por lo que no entiendo como ponderar el entrenamiento para fijar dichos parametros como int tras entrenar en IEEE pues se tendria por ejemplo
``velocidad = 1``
``velocidad += PUNTOS_ENTRENAMIENTO * 1.7``
y ``velocidad`` ya no seria un int sino que seria un float

**Comment by mmunozmendez** [comment]
Hola, efectivamente deja de el int el valor, pero así es como debe funcionar el programa. 
Éxito!
