### ISSUE TITLE
Recorrección T1

### ISSUE THREAD

**Issue by nsvega** [IIC2233/Syllabus#410]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Contenido

Si corregí esto en mi código   
print ("¡Bienvenido a DCCultivo!")  # Incorrecto
print("¡Bienvenido a DCCultivo!")   # Correcto
¿Cuenta para política de cambio de líneas ?

Saludos

**Comment by Hernan4444** [comment]
Hola @nsvega 

Si, todo cambio de línea, aunque sea para cambiar 1 caracter ya es un cambio de línea y será considerado en la política.

¡Éxito con el curso! 🦖
Saludosヾ(＾-＾)ノ
