### ISSUE TITLE
La señal demora demasiado en actuar

### ISSUE THREAD

**Issue by IngisRedd** [IIC2233/syllabus#410]
Saludos!
     Mi juego está compuesto de una clase Game() que contiene tanto la ventana del juego, cómo todos los threads de enmeigos, torres, monedas...
     Me ocurre que en algunas partes del código necesito que un thread reciba una información de su parent (por ejemplo: actualizar la  posición de los enemigos en el rango de ataque de una torre), por lo que le envía una señal pidiéndosela. Pero he descubierto que Game() se demora un poco en enviar la información de vuelta, por lo que el thread todavía actúa un tiempo con información desactualizada, causando errores.
     Esto no ocurriría si en vez de utilizar señales, los threads contuvieran a Game(), pero entiendo que esto se considera programación circular y se considera mala práctica.
    Se me ocurre que una forma de solventar este problema es que el thread espere a que su información sea actualizada por su parent antes de continuar actuando. Pero no se cómo aplicar esto pues no conozco una forma de detectar que un atributo de un objeto ha sido cambiado. 
Me encuentro sin muchas opciones y tampoco quiero recurrir a programación circular. ¿Se les ocurre que puedo hacer?

Gracias por adelantado!

**Comment by hbkim94** [comment]
Hola @IngisRedd ,

En primer lugar, ¿estás utilizando `QThread` o `QTimer`? Asumiendo que estás utilizando `QThread`, lo que se me ocurre a la rápida, en base a lo que estás buscando, es que tu thread hijo espere un poco (un muy corto tiempo en lo posible) antes del siguiente "evento". Quizás podrías probar con `QTimer.singleShot()` (actúa de forma similar a ` time.sleep()`), que básicamente ralentiza la ejecución de una función en los milisegundos especificados, modificando la cantidad de milisegundos que espera hasta que tu thread reciba la respuesta efectivamente antes de actuar. 

Sin embargo, dependiendo de cómo funciona tu programa y cómo tienes modeladas las cosas, además de la cantidad de threads que están corriendo al mismo tiempo que requieren de eso, no estoy muy segura de cómo esto puede afectar el performance de tu juego.

Por otro lado, quizás la razón por la que `Game()` se demora en enviar la información de vuelta es porque tiene demasiadas cosas incluídas o el orden de ejecución de sus métodos es tal que prioritiza otros primero sobre el procesamiento de la info que le envías. Podrías tener alguna clase intermediaria que contenga lo necesario para calcular los cambios, y que le envíe la información necesaria tanto a `Game()` como a tu thread hija para actualizar los estados pertinentes, en lugar de que sea todo por parte de `Game()`.

Mucho ánimo en lo que queda!

**Comment by IngisRedd** [comment]
Gracias por las sugerencias! No se me habría ocurrido crear una clase intermediaria aparte...
Al final, lo que me pareció funcionar fue incluir las acciones problemáticas del hijo en la funcion del parent llamada con la señal, así solo las relizaría después de haber enviado la señal en cuestión. Por si alguien tiene un problema parecido.
