### ISSUE TITLE
ciudades_distritos y cargar_datos

### ISSUE THREAD

**Issue by IsidoraCarmona** [IIC2233/Syllabus#410]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola en el test_03_ciudades_distritos me tira el error porque le falta un espacio a los nombres de las provincias, pero al alterar cargar_datos para que este salga con ese espacio faltante me corre este tests, pero me deja de correr correctamente el test_base_cargar_datos.py. Esto es un error o no? por que no es posible entonces que tenga ambos correctos. 
A parte trate de añadir el espacio directamente en la función pero solo pide este espacio para los elementos que son cargados desde los archivos, entonces me arroja error a los otros test que no son con carga de datos.

**Comment by SebastianEscudero** [comment]
Me pasa lo mismo

**Comment by mpiavf** [comment]
Hola !
Los archivos distritos fueron actualizados para que ese espacio no genere problemas, les recomiendo ver esta issue #338 
Si aún con estos cambios no funciona nos avisan !
Saludos

**Comment by IsidoraCarmona** [comment]
Ah sí, era porque no había actualizado test_solution. Muchas Gracias!
