### ISSUE TITLE
Limite de filas y columnas de mapa

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus#410]
No deberia haber un limite de las columnas y las filas de un mapa, ya que como cada sprite es de NxN, se podrian ir al chancho y poner que N=100 y si resultan ser muchas filas y columnas. El AREA MINIMA de donde se juega se pasaria incluso del maximo de resolucion de la pantalla del computador. Mas encima, pensando en que tiene que haber lugar para el inventario y tambien los datos de juego, no se deberia establecer como un borde maximo de filas y columnas...

Edit_extra: El problema principalmente esta en que se debe hacer un alineado del inventario y de los datos de juego JUNTO donde se desarrolla el juego, por lo que si se mueven a cada rato los i,j lo demas tambien. Encuentro que es un problema extra innecesario, si ya de partida se pueden modificar los pixeles.

**Comment by aljara97** [comment]
Hola, no es necesario que exista un limite para las columnas y filas del mapa, esto estará determinado por el archivo correspondiente. Puedes asumir que estos no contendrán cantidades irrisorias de elementos, sin embargo, debes ser capaz de manejar la creación de la ventana para cualquier parámetro N a definir. No te preocupes por el tamaño de la pantalla, solo de que los elementos no se superpongan entre sí.

Mucha suerte con tu tarea
