### ISSUE TITLE
Lectura de archivos en extraer_columna

### ISSUE THREAD

**Issue by djcontador** [IIC2233/Syllabus#411]
En la issue #321 al usar generador = open(name, "r"), no habría problema en dejar el archivo abierto o si? dado que solo estamos haciendo una lectura con el generador, y no editando el archivo.
gracias de antemano!

**Comment by Hernan4444** [comment]
ya se respondió en #321. Por favor no hacer una issue adicional de un tema que se está conversando en otra lo mejor es preguntar en esa para concentrar las respuestas.
