### ISSUE TITLE
Aumento de salud por Magizoólogo Híbrido

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#411]
Hola.
Cuando mencionan "recuperar 10 puntos de salud", qué salud aumenta, la total o la actual¿?

**Comment by JosefaPaz** [comment]
¡ Hola @Camila-sty !

Tu pregunta se encuentra en la issue #276 y #359 :) Recuerda revisar primero el compilado de issues de la T01, éxito en la tarea! 😄
