### ISSUE TITLE
Problemas con .gitignore y git en general

### ISSUE THREAD

**Issue by BenediktKd** [IIC2233/syllabus#411]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
Hola. Estoy teniendo problemas con .gitignore y git en general. Lo que pasa es que hace tiempo ya no me deja subir archivos a través de la terminal, por lo que lo tuve que subir manual ( con el add file a traves de la pagina web ). Pero **no puedo aplicar** lo mismo para el archivo gitignore ya que como aparece en una **issue anterior**, para actualizar bien el gitignore y que ignore los archivos csv, tengo que aplicar un codigo en la terminal ( lo cual no puedo hacer ).

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mistico0121** [comment]
Hola

Dado que estás teniendo problemas con el gitignore, y estas subiendo todo manualmente, tecnicamente no tiene mucho sentido tener uno dadas tus condiciones, pues cuando haces "git add ." el gitignore es el que se encarga de que no se suban ciertos archivos y puedas seguir trabajando con estos localmente, y como tu simplemente estás subiendo tus archivos manualmente, entonces el .gitignore nunca entra en acción.

Ahora, si tienes problemas con actualizarlo, puedes hacerlo desde github mismo. Hay un botón en todos los archivos llamado "Edit file" con el que puedes editar 1 archivo y hacer el commit de una. Yo generalmente lo uso para actualizar el README. Funciona igual para cualquier archivo así que puedes hacer eso con tu archivo .gitignore en tu repo.

Eso sí, te recomiendo solucionar tus problemas lo antes posible. El uso de github para tareas más complejas tanto en este ramo como en el resto de la carrera es una necesidad, y no puedes seguir subiendo los archivos 1 por 1 y actualizandolos manualmente. Considera esto una solucion parche y preocupate de solucionarlo lo antes posible(antes de cualquier otra cosa, en serio). Es muuuuy importante para tu flujo de trabajo.
