### ISSUE TITLE
Error en los tests de test_24_votantes_validos_por_distrito (No relacionado a las edades)

### ISSUE THREAD

**Issue by VicenteIgnacioSotoGonzalez** [IIC2233/Syllabus#411]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Buenas tardes, junto con saludar quería comentar lo que creo que es un error en el test mencionado, lo que pasa es que en los test 0-3 se crea la namedtuple Locales con un atributo llamado votantes, pero la definición Locales en utilidades.py no tienen ese atributo, su homólogo es ids_votantes. Eso hace que me salte el siguiente error en los tests 0-4 pero cuando se manejan los datos .csv no sucede.

![imagen](https://github.com/IIC2233/Syllabus/assets/162501853/f73cdf9f-9fce-4bed-a4c7-91b6378a5542)
![imagen](https://github.com/IIC2233/Syllabus/assets/162501853/5e0a9e9a-c28f-4b46-96bd-e1a6f4a6b113)
![imagen](https://github.com/IIC2233/Syllabus/assets/162501853/7d335554-97db-425b-ad53-68a9b5af0adb)

**Comment by VicenteIgnacioSotoGonzalez** [comment]
De hecho ahora que me fijo, lo mismo sucede con nombre y nombre_local.

**Comment by porresjm** [comment]
Me pasa lo mismo, siento que hay una incongruencia entre el nombre de la funcion y la descripción de la misma, ya que si retorno los animales con la unica condicion de que pertenezcan al distrito me dan bien los test, pero como considero animales que son "menores de edad" sus votos no tendrian validez y por lo tanto el nombre "votantes_validos_por_distrito" no tendría sentido.

**Comment by jfpantoja** [comment]
Hola @VicenteIgnacioSotoGonzalez, @porresjm!
Efectivamente, se habló con el equipo docente y esto es un typo, los nombres de los atributos deben ser ```nombre_local``` en vez de ```nombre``` e ```id_votantes``` en vez de ```votantes```. En este caso, por mientras, pueden editar los nombres en los test o bien utilizar índices para acceder a los atributos (local[1], local[3]). 
De igual manera, los test serán corregidos para que los atributos utilizados sean consistentes con el enunciado.

**Comment by jfpantoja** [comment]
@porresjm,
Con respecto a lo que mencionas, según lo que dice el enunciado, lo que busca la función en primer lugar es encontrar el distrito ganador con respecto a los votos válidos, luego de eso se pide retornar un generador con **Todos** los animales que pertenecen a ese distrito. Si bien el nombre como dices puede generar confusiones con respecto a lo que busca la función, te recomiendo que te guíes por la descripción de esta función y lo que está buscando.

**Comment by VicenteIgnacioSotoGonzalez** [comment]
> Hola @VicenteIgnacioSotoGonzalez, @porresjm! Efectivamente, se habló con el equipo docente y esto es un typo, los nombres de los atributos deben ser `nombre_local` en vez de `nombre` e `id_votantes` en vez de `votantes`. En este caso, por mientras, pueden editar los nombres en los test o bien utilizar índices para acceder a los atributos (local[1], local[3]). De igual manera, los test serán corregidos para que los atributos utilizados sean consistentes con el enunciado.

Okas, muchas gracias por la respuesta! ;)

**Comment by mpiavf** [comment]
Hola, actualizamos los tests con lo detectado en esta issue y otras más. Pueden revisar la issue creada en #444 para más detalle. 
Saludos!

**Comment by VicenteIgnacioSotoGonzalez** [comment]
> Hola, actualizamos los tests con lo detectado en esta issue y otras más. Pueden revisar la issue creada en #444 para más detalle. Saludos!

Okas! Muchas gracias!

**Comment by Hernan4444** [comment]
> Cuando nos piden que sean todos los animales que pertenecen a dicho distrito, si utilizo la lista id_votantes de locales para encontrarlos ¿Hay que verificar que cada uno de estos animales en la lista pertenezcan tanto al generador de votos como de animales? Gracias.

Hola, si tendrías que verificar eso, porque se buscan los animales que votaron en el distrito ganador. Por lo tanto, si partes de id_votantes, luego hay que encontrar a dichos animales y verificar si es que efectivamente votaron o tal vez hay algún animal que se negó a votar. 

Igual recomiendo explorar otras alternativas, por ejemplo, "dado un distrito ganador, buscar **todos** los votos realizados a dicho distrito y de ahí los animales que votaron". Y pueden haber más formas aún, y todas te permitirán llegar al mismo resultado, solo que en un orden diferentes de animales.... Lo bueno es que el orden no afecta a la respuesta de la consulta, mientras logres identificar a los animales que esperamos.

Saludos!
