### ISSUE TITLE
Reutilizar código propio

### ISSUE THREAD

**Issue by rominaarancibia** [IIC2233/Syllabus#411]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Por confirmar quería preguntar si esta permitido utilizar algunas partes de código especificas que cree yo misma  para las tareas anteriores de este semestre. En particular para el manejo de datos.

**Comment by Hernan4444** [comment]
Hola @rominaarancibia 

No hay problema con eso, aunque porfa agrega en las referencias del readme qué parte estás reutilizando de tu tarea anterior de este semestre.

Saludosヾ(＾-＾)ノ
