### ISSUE TITLE
Clase Abstracta

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#411]
Hola, tengo una duda ya que por lo visto en los contenidos **3-clases-abstractas** no se podía instanciar una clase abstracta, es decir una clase que herede del módulo **_ABC_**. Sin embargo al intentar esto sí se puede instanciar. Lo que da error es al agregar métodos abstractas (@abstractmethod). Entonces mi pregunta es para que sirve crear una clase abstracta heredando de **_ABC_**?

**Comment by itmunoz** [comment]
Hola! Para que una clase sea abstracta debe cumplir dos condiciones: que herede de ABC **y** que tenga algún método abstracto. Si solamente se cumple una de esas dos condiciones la clase no se comporta como abstracta.

**Comment by Gustav2000** [comment]
Ahhh, muchas gracias!!!
