### ISSUE TITLE
MovieError

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2233/Syllabus#411]
Acá tengo una duda debido a que me parece un poco contradictorio lo que se pide respecto a intentar usar generadores lo más posible. Me explico:
Digamos que estoy iterando sobre un generador con películas, comparando parámetros donde eventualmente encuentro un 'N/A'. Luego, yo debería ser capaz de encontrar la película donde se generó el error, pero a esas alturas ya no podría recuperarla si utilizo el mismo generador, ya que si aplico next( ) tomará el siguiente elemento del generador. Por lo tanto, la forma de capturar estos errores sería copiando el generador con tee o haciendo list(generador) al principio de cada función, pero esto último me quita automáticamente una línea de la función y me hace el código más burdo. ¿Debería tratar el manejo de errores de esta última forma, o se me está pasando alguna forma menos bruta de hacerlo? :c

**Comment by Hernan4444** [comment]
@jpmoraga1 se te está pasando otras formas que no puedo decir.
