### ISSUE TITLE
Duda ejercicio 3.3 Semana 6: Uso de fill 

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#412]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### No me queda claro como usar fill

Estaba intentando el ejercicio y no logro hacer funcionar .fill(), actualmente mi código es algo así:

pixeles = QPixmap().fill(Qt.color)

Luego de eso uso setPixmap como en los cuadernillos, pero esto resulta en un error, específicamente,
en el setPixmap ocurre "argument 1 has unexpected type 'NoneType'". Busque en internet sobre el error
y la sintaxis de fill, pero no logre encontrar mucho.

¿Que es lo que esta mal en esa forma de escribir fill?

**Comment by aaossa** [comment]
Hola @Pabloski100 , creo que te faltan dos cosas. Primero, crear un `QPixmap` no vacío (lo que ocurre si no le das argumentos), y, segundo, (aunque sé que lo mencionaste) crear un `QLabel` para contener al `QPixmap` (tal como hacemos con las imágenes). Prueba con el código de este ejemplo:

```python
self.label = QLabel(self)
self.pixmap = QPixmap(100, 100)  # Tamaño del pixmap
self.pixmap.fill(Qt.white)  # Qt.blue, Qt.red, etc.
self.label.setPixmap(self.pixmap)
```

Puedes encontrar más información sobre la clase `QPixmap` y sus constructores en [esta documentación](https://doc.qt.io/qt-5/qpixmap.html). Ojalá te sirva 🙌
