### ISSUE TITLE
Dudas con la ascendencia albina

### ISSUE THREAD

**Issue by Polea012** [IIC2233/Syllabus#412]
Me parece que ya lo habían preguntado pero no encuentro la issue.
Para el caso de la ascendencia albina, nos piden buscar el gen AAT en los genes de ojos, pelo y piel.
Sin embargo, AAT es el gen para el pelo rubio y los ojos azules.

Si una persona tiene ascendencia albina, entonces solo tiene que estar presente el gen AAT en las 3 caracteristicas al mismo tiempo?, y si es así, una persona con ascendencia albina retornaria "ojos azules" en valor_característica"?

**Comment by TomasSalvadores** [comment]
Efectivamente solo hay que encontrar el gen en las 3 características, por lo que no es necesario que se exprese fenotipicamente, es decir, alguien de ascendencia albina podría tener ojos verdes y pelo negro.
La idea de esto es ver si provienes de antepasados albinos cercanos, sin necesariamente ser albino de apariencia.
Suerte!

**Comment by Polea012** [comment]
Muchas gracias, super claro ahora !
