### ISSUE TITLE
Señal en QTimer

### ISSUE THREAD

**Issue by cmarquez1** [IIC2233/syllabus#412]
Hola, en la distribucion del puntaje de la tarea 2 las casillas que estan en azules se tienen que hacer con correcto uso de señales, al conectar una funcion con el timeout, es considerado un correcto uso de señal. Por ejemplo conectar un timeout a una funcion que actualiza los datos y este qtimer se este todo el rato actualizando hasta que se termine la ronda o pausen el juego.

**Comment by Hernan4444** [comment]
Hola

`timeout` es un tipo de señal. Así que está todo bien 👍 

Saludos ✌️
