### ISSUE TITLE
Property en clase abstracta

### ISSUE THREAD

**Issue by BFry712** [IIC2233/syllabus#412]
Hola! queria saber si para definir una property en una clase abstracta se utiliza @abstractproperty o solo ocupamos @property?

**Comment by jitorcas** [comment]
Hola! @BFry712 

`@abstractpproperty` quedó descontinuado desde la _versión 3.3_. Puedes utilizar `@property` con `@abstractmethod` de ser necesario. Adjunto la [documentación](https://docs.python.org/3/library/abc.html#abc.abstractproperty)

Éxito!
