### ISSUE TITLE
Problemas con la función imprimir_generos por utilización de caracteres Unicode

### ISSUE THREAD

**Issue by undieguito** [IIC2233/Syllabus#412]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema
Hola, espero que estén bien:
Mi problema es que al ejecutar el código main de la actividad, me tira un error de encoding, ya que imprimir generos en utilidades utiliza unicode y mi terminal al no ser UTF-8 (sino cp1252) me tira a error. Cambié el encoding del terminal a UTF-8 y lo verifiqué, y aun así, me tira el error UnicodeEncodeError: 'charmap' codec can't encode character '\u22ee' in position 4: character maps to <undefined>

¿Que se puede hacer en este caso, ya que creo que no puedo modificar nada en la función utilidades? ¿Aparte, como puedo cambiar el encoding de mi computador a futuro para que no me vuelva afectar esto? Porque probablemente la próxima tarea de programación funcional tenga algunas líneas con Unicode.

Saludos.

**Comment by Hernan4444** [comment]
Hola @undieguito 

Esperando que estés bien, si quieres puedes editar esa línea de `utilidades.py` para que puedas probar el resto del `main.py`. Esas funciones las pusimos para que puedan imprimir el contenido de cada generador de forma más ordenada, pero no serán usadas al momento de corregir. Aquí únicamente ejecutaremos los tests privados que llamarán a cada función y revisarán resultado entregado (similar a los test públicos). Por lo tanto, no te preocupes que mientras los tests te corran, entonces tu código está bien. 

Respecto a cambiar el _encoding_ del computador, eso depende mucho del sistema operativo que uno tiene, lo mejor es que al momento de abrir la terminar, setear el _encoding_ y mantener la terminar abierta mientras se trabaja en la tarea. No obstante, no tienes que preocuparte que esto vuelva a pasar porque la tarea de programación funcional no entregaremos ningún archivo que haga `prints` con caracteres unicode, esto fue solo para la AC.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ

**Comment by undieguito** [comment]
Perfecto, muchisimas gracias :)
