### ISSUE TITLE
Impresion del error

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#412]
¿Es necesario que imprima específicamente los errores que ponen en el enunciado? Porque yo imprimo los errores con su explicación, pero no pongo específicamente "Error de tipo" o "Referencia invalida" por ejemplo.

**Comment by Hernan4444** [comment]
@jorgeriesco te recomiendo que en el readme indiques que explicación va con los errores pedidos para después saber que identificas los 5 errores que al menos nosotros requerimos para la tarea.
Saludos!
