### ISSUE TITLE
Hitbox personaje

### ISSUE THREAD

**Issue by MGome** [IIC2233/syllabus#412]
Hola buenas! Al estar probando el envío de señales entre el frontend y el backend me surgió la duda de cuál debía ser el hitbox del personaje, pues esto influye directamente en las colisiones y el inicio de algunos eventos. En esta imagen marqué el hitbox que le tengo puesto a mi personaje por ahora. La medida del hitbox debe ser de N o queda a nuestro criterios?
![image](https://user-images.githubusercontent.com/48321270/66261514-2f423900-e7a5-11e9-8bd9-7be8c9aa889f.png)

**Comment by jmwielandt** [comment]
Hola!

Puedes hacer las colisiones de cuerpo completo o solo con los pies del personaje, queda a tu criterio pero debes agregarlo en tu readme y poner una referencia a esta issue en él, para así evitar problemas durante las correcciones 😉.

Se habla con mayor profundidad sobre las colisiones en la siguiente issue #391.

Saludos~ 🕺
