### ISSUE TITLE
Tipo de dato "id"

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#412]
Para el archivo movies.csv se indica que el dato de la columna id es un int, mientras que para el resto de archivos es un str.
¿Puedo trabajar los id que aparecen en los otros archivos como int?

**Comment by Arcoirisky** [comment]
Disculpa, no logro entender el problema de la pregunta :( Revisé los archivos .csv y son del tipo int para todos ¿Quieres pasarlos de str a int en tu programa? Porque no hay problema con eso.

**Comment by pcseisdedos** [comment]
Creo que se refiere a esto:
![image](https://user-images.githubusercontent.com/18387808/39657275-ba6f0b78-4fdc-11e8-9ba9-1871422b4004.png)

**Comment by pcseisdedos** [comment]
Creo que se refiere a esto:
![image](https://user-images.githubusercontent.com/18387808/39657313-1cce2416-4fdd-11e8-8c57-5ef3c18b1995.png)
