### ISSUE TITLE
Función votantes_válidoss_por_distrito

### ISSUE THREAD

**Issue by ignanuyens** [IIC2233/Syllabus#413]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

En el enunciado la pregunta pide lo siguiente:

def votantes_validos_por_distritos(generador_animales: Generator, generador_distritos: Generator, generador_locales: Generator,
generador_votos: Generator, generador_ponderadores: Generator
Recibe cinco generadores, con instancias de animales, distritos, locales, votos y ponderadores. Primero se debe encontrar el distrito con la mayor cantidad de votos válidos. Luego, se debe retornar un generador con todos los animales que pertenecen a dicho distrito. En caso de haber empate entre dos distritos, se utiliza el distrito con el menor id. Recuerda revisar la consulta votos_validos donde se define cuando un voto es válido

Mi duda está en los test cases, una vez que tengo el id del distrito ganador, debo buscar qué comunas pertenecen a ese distrito, y luego buscar todos los animales que pertenecen a dichas comunas (debido a que lo único que tienen en común los Animales y Distritos es un id_comuna, y que un distrito está compuesto por varias comunas).

Sin embargo en los test de la función donde son para casos pequeños nos entregan lo siguiente:

```python
Animal = namedtuple(
            "Registro",
            [
                "id",
                "nombre",
                "especie",
                "id_comuna",
                "peso_kg",
                "edad",
                "fecha_nacimiento",
            ],
        )

        lista_entregada1 = [
            Animal(1, "Gay", "Perro", 190, 288.0, 45, "1979/11"),
            Animal(2, "Lexi", "Gato", 61, 0.071, 34, "1957/8"),
            Animal(3, "Toccara", "Gato", 248, 0.525, 67, "1957/12"),
            Animal(4, "Phil", "Perro", 248, 0.525, 67, "1957/12"),
            Animal(5, "Ernst", "Gato", 116, 81.0, 60, "1964/9"),]

        generador_entregado1 = (element for element in lista_entregada1)

        Distrito = namedtuple(
            "Distrito", ["id_distrito", "nombre", "id_comuna", "provincia", "region"]
        )

        lista_entregada2 = [
            Distrito(1, "Distrito 1", 1, "Arica", "Arica y Parinacota"),
            Distrito(1, "Distrito 1", 2, "Parinacota", "Arica y Parinacota"),
            Distrito(2, "Distrito 2", 3, "Iquique", "Tarapacá"),
        ]

        generador_entregado2 = (element for element in lista_entregada2)

        Locales = namedtuple("Locales", "id_local, nombre, id_comuna, votantes")

        lista_entregada3 = [
            Locales(id_local=0, nombre="Local 0", id_comuna=1, votantes=[1]),
            Locales(id_local=1, nombre="Local 1", id_comuna=1, votantes=[2]),
            Locales(id_local=2, nombre="Local 2", id_comuna=2, votantes=[3]),
            Locales(id_local=3, nombre="Local 3", id_comuna=2, votantes=[4]),
            Locales(id_local=4, nombre="Local 4", id_comuna=3, votantes=[5]),
        ]

        generador_entregado3 = (element for element in lista_entregada3)

        Voto = namedtuple(
            "Voto", ["id_voto", "id_animal_votante", "id_local", "id_candidato"]
        )

        lista_entregada4 = [
            Voto(1, 1, 0, 5),
            Voto(2, 2, 1, 3),
            Voto(3, 3, 2, 1),
            Voto(4, 4, 3, 1),
            Voto(5, 5, 4, 1),
        ]

        generador_entregado4 = (element for element in lista_entregada4)

        Ponderador = namedtuple("Ponderador", ["especie", "ponderador"])

        lista_entregada5 = [Ponderador("Perro", 5.5), Ponderador("Gato", 0.01)]

        generador_entregado5 = (element for element in lista_entregada5)

        resultado_estudiante = votantes_validos_por_distritos(
            generador_entregado1,
            generador_entregado2,
            generador_entregado3,
            generador_entregado4,
            generador_entregado5,
        )

        self.assertIsInstance(resultado_estudiante, Generator)

        lista_esperada = [
            Animal(1, "Gay", "Perro", 190, 288.0, 45, "1979/11"),
            Animal(2, "Lexi", "Gato", 61, 0.071, 34, "1957/8"),
            Animal(3, "Toccara", "Gato", 248, 0.525, 67, "1957/12"),
            Animal(4, "Phil", "Perro", 248, 0.525, 67, "1957/12"),
        ]

```

En la cuarta columna de listaentregada1 tenemos las comunas de los animales que serían (190, 61, 248, 248 y 116), por otro lado en la columna 3 de listaentregada2 tenemos a las comunas que pertenecen a los distritos que serían (1, 2 y 3), al igual en la lista de los locales las comunas existentes son 1, 2 y 3.

Por lo tanto mi duda está en que una vez que encuentro el valor del id del distrito ganador, y sus comunas (pongamos por ejemplo ganó el distrito con id 1 para ese testcase según yo), no existe ningún animal que pertenezca a las comunas 1, 2 o 3.
No sé si hay algo que no estoy entendiendo del problema o hay un error.

Muchas gracias de antemano :)

**Comment by leonidasmontes** [comment]
Me pasa lo mismo. ¿No deberían ser comunas existentes las de los animales votantes?

**Comment by faresdababneh** [comment]
Hola tengo el mismo problema. Encontrar a los animales que pertenecen a cierto distrito, es equivalente a encontrar a todos los animales que pertenecen a cada comuna que forma parte de dicho distrito. Por lo que no logro darle sentido, más aún cuando paso los test_case con datos grandes y no con los de prueba. Gracias

**Comment by jisalasc** [comment]
Creo que es por que en este caso para encontrar los votantes por distrito, no hay que fijarse de que comuna son sino a que local pertenecen y ver a que comuna pertence ese local, o no?

**Comment by jfpantoja** [comment]
Hola!! @ignanuyens, @leonidasmontes, @faresdababneh, @jisalasc
Como bien dice @jisalasc, no hay que fijarse en la comuna donde vive el animal, sino en la comuna donde a este le toca votar. Para contextualizar un poco, lo que busca esta función es entregar todos los animales que votan en el distrito ganador.

**Comment by jfpantoja** [comment]
@ignanuyens exactamente es como dices y lo tendremos en consideración con la corrección, hace poco igualmente respondí una issue hablando de ese tema, está en la issue #411

**Comment by mpiavf** [comment]
Hola, actualizamos los tests con lo detectado en esta issue y otras más. Pueden revisar la issue creada en #444 para más detalle. 
Saludos!
