### ISSUE TITLE
Maximo lineas

### ISSUE THREAD

**Issue by YoGandalf** [IIC2233/syllabus#413]
Hola
Hay alguna posibilidad de que suban las lineas maximas permitidas a 500?
Me estoy complicando demasiado y me estan quedando lineas bastante feas solo para reducir el maximo posible y aun me faltan algunos labels que ocupan muchas lineas cada uno.
Si sigo asi va a quedar el codigo mas ilegible del mundo y voy a hacer funciones y clases en el main que no tiene tantas lineas solo para zafar del descuento que no se si es la idea.
O sea de poder puedo reducir las lineas pero seria demasiado forzado.
Quiza se podria hacer bien en 400 lineas pero no se me ocurre otra forma de hacerlo sin que quede muy forzado y tampoco se si la idea es que se evalue la mejor manera sino que puede haber maneras distintas de hacerla.
Espero se entienda

**Comment by Hernan4444** [comment]
Hola,

Lamento informar que no se hará ningún cambio.
