### ISSUE TITLE
Duda forma de llamar a los atributos del super

### ISSUE THREAD

**Issue by mjadresic** [IIC2233/syllabus#413]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola, mi duda es que existen 2 formas de definir los atributos al momento de definir una clase hija.

Una es poner 
super().__init__(atributos...)

otra forma que funciona es poner 
NombreClasePadre.__init__(atributos...)

Mi pregunta es cual es la diferencia entre estas formas y si se considera necesariamente "incorrecta" la segunda forma o si es correcto hacerlo asi.

Saludos

**Comment by aaossa** [comment]
Hola @mjadresic , muy buena pregunta! 

Justo hace unos días hablé eso con @cothidalgo revisando un código. En general, diría que es preferible utilizar `super()`, porque deja de depender del nombre de la superclase y porque la herencia debe ser declarada explícitamente junto al nombre de la subclase. Sin embargo, hay casos en los que hace sentido utilizar la segunda opción (`Superclase.metodo(self, *args, ...)`), que sería solo si estás utilizando multiherencia y quieres "saltarte" alguna(s) clase(s) del MRO. A mi juicio esta forma no se justifica en otro caso (al menos no puedo pensar en otra situación). Espero haber respondido tu pregunta, pero si tienes más dudas pregunta por acá mismo 👌 ¡Éxito con tu estudio ✨!

**Comment by mjadresic** [comment]
Tengo otra duda con respecto a eso, cual podría ser la causa de que mi código no corra cuando ocupaba la primera opción  (super().__init__(self, *args, ...)) ? Solo al ponerle el nombre de la clase padre envés del super() es cuando el código me podía funcionar sin problemas.
En otras palabras, mi duda es cual es la diferencia de los 2 métodos no en torno a los beneficios de usar una o la otra sino que cual es la diferencia en torno a que hace exactamente cada una?

Saludos
