### ISSUE TITLE
DUDA PLANTAR SEMILLAS

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2233/syllabus#413]
Hola! Quería saber como podía descontar la cantidad de semillas del inventario cuando las planto, ya tengo creados los drag and drops con las restricciones necesarias. Mis dos opciones son: descontar apenas empiezo a moverlo, eso incluye que si el usuario se equivoca pierde una semilla, o descontar cuando hago el drop. Pero ambas necesitan señales que no puedo conectar en el main, ¿puedo conectar señales en el front? ¿o de que otra forma puedo hacerlo?

**Comment by jmwielandt** [comment]
Hola!

Espero no romper demasiado código con esto, pero en general cuando un programa se complejiza un poco, lo normal es que cada clase del frontend (QWidget, QLabel, etc) tenga su propio backend como atributo y se comuniquen mediante señales cuando es necesario que tengan un cierto comportamiento asociado. Las señales se pueden conectar en el `__init__` de la clase del frontend que nos interesa, luego de instanciar su backend. En el curso se comentaron además otras dos opciones; la primera es que sea el backend quien instancie a su frontend, con un funcionamiento similar al anteriormente descrito. Otra opción que se presentó es tener una clase o función intermediaria que se encargara de conectar las señales entre ambos, conteniendo tanto al frontend como al backend. Eres libre de usar cualquiera de estos tres modelos o algún otro siempre y cuando no haya referencias circulares.

Saludos!

<hr>

Por favor, no cierres las issues ya que pueden servir a tus compañeros. Nosotros las cerraremos cuando sea oportuno. También que no se responden issues desde el sábado en la noche hasta el lunes en la mañana.
PD: el colapso es real y me disculpo por no responderte ayer. Entiendo que es un tema sensible al tiempo el de esta issue :(
