### ISSUE TITLE
opción volver atras menu inicio

### ISSUE THREAD

**Issue by notyourlasagna** [IIC2233/syllabus#413]
Hola, para el menú de inicio también hay que hacer una opción de volver atrás? No creo que tenga mucho sentido ya que no existe un 'atrás', si el programa inicia con este menú.

**Comment by baosse** [comment]
Holaa @notyourlasagna !

No, no es necesario implementar la opción 'Volver atrás'. Solo se debe implementar 'Comenzar nueva partida' o 'Salir del programa' como dice el enunciado.

Mucho éxito con tu tarea!✨
