### ISSUE TITLE
Problemas para printear 70% de

### ISSUE THREAD

**Issue by drosselot** [IIC2233/syllabus#413]
Hola, cuando trato de printear el string "tiene un 70% de probabilidades" me toma el %d como funcion para formatear el string. ¿Hay alguna forma de que solo me lo tome como string?

**Comment by fdoflorenzano** [comment]
Hola @drosselot,
No puedo replicar lo que mencionas solo imprimiendo ese *string*, por lo que asumo estás intentando formatear dentro de este otra cosa. Si es el caso, intenta con otro método de *formatting*, como *f-strings*.

Si no es el caso, intenta ser un poco más claro y explícito con lo que sucede. ¿Cuál es la línea de código completa que ejecuta? ¿Qué es lo que produce?

Saludos.

**Comment by sbcorrea** [comment]
Hola, no soy ayudante ni nada, pero, ¿y si pruebas poniendo ```\``` antes del ```%```?
Ojalá te sirva :)

**Comment by drosselot** [comment]
Me equivoque, funciona perfecto. El problema que pensé que tenía era que no printeaba bien, pero no es así. En el codigo "% d" se me marcaba azul, pero cuando lo printeo, aparece normal, asique no tengo problemas.
