### ISSUE TITLE
Crear nuestros propios errores o con default errors?

### ISSUE THREAD

**Issue by chuma9615** [IIC2233/Syllabus#413]
Hola!

Mi pregunta es si para esta tarea es necesario que nosotros creemos nuestors propios errores o podemos manejar los errores solo con los errores built-ins?

saludos!

**Comment by iqacevedo** [comment]
Hola!

Se pide que manejes los errores específicos de las consultas, tu decides como te acomoda más lanzar los errores, pero debes estar seguro de que los manejas bien para poder distinguir el tipo de error y puedas mostrar el resultado esperado.

Saludos !
