### ISSUE TITLE
Método dentro de clase abstracta

### ISSUE THREAD

**Issue by gore26** [IIC2233/syllabus#414]
Hola c: tengo una duda sobre si un método dentro de una clase abstracta puede recibir un argumento externo, por ejemplo def fichar_deportistas(self, deportista)

**Comment by baosse** [comment]
Holaa @gore26 !
Si puede recibir un argumento externo, solo debes recordar ponerlo en el super de la función que tendrás en la subclase y que esta función igual deberá recibir el mismo argumento.
Espero te haya servido.
Mucho éxito!✨

**Comment by gore26** [comment]
Ahh yaya perfecto, gracias! :)
