### ISSUE TITLE
cuando hacer procesamiento y preprocesamiento

### ISSUE THREAD

**Issue by ciquezada** [IIC2233/Syllabus#414]
hola, en la issue #325 se menciona que el preprocesamiento se hace al abrir por primera vez la interfaz, pero no me queda muy claro si despues se puede volver a hacer otra vez. Mas importante solo para no quedar con dudas, ¿es posible que me explicaran el objetivo de hacer un preprocesamiento para luego hacer un procesamiento?, y ¿cuando y cuantas veces se supone que hay que hacer preprocesamiento y procesamiento? (por ejemplo una vez por cada consulta, o una vez para un grupo de consultas)

**Comment by jmwielandt** [comment]
En el archivo reviews.csv están los comentarios para las películas.
Originalmente, tienen dos problemas: están con código html y hay comentarios de bots.
Un comentario puede ser "hola <i> chao </i>", si lo dejas así tiene 4 palabras, lo que es incorrecto, por lo que el preprocesamiento parte 1 debe eliminar el html y dejar "hola chao", en lugar de "hola <i> chao </i>".
Luego de eso, tienes que eliminar los comentarios de los bots.

De la issue que pusiste, tienes dos opciones: 
1. cada vez que vayas a usar los comentarios (para best_comments, por ejemplo) haces el preproceso del archivo y luego lo procesas.
2. la primera vez que abres la interfaz haces el preproceso y sobreescribes el archivo "reviews.csv", para que luego no lo tengas que preprocesar todas las veces.

**Todo esto es para que en el procesamiento tengas únicamente los comentarios de personas reales y con el número correcto de palabras.**

PD: no soy ayudante.

**Comment by ciquezada** [comment]
¿Osea que para la tarea no se pide que haya un numero limitado de procesamientos y preprocesamientos sino solo que uno sea antes que el otro?

**Comment by pcseisdedos** [comment]
En caso de optar por la segunda opción se puede realizar el pre-procesamiento solo cuando se necesite revisar los comentarios? dado que no en todas las consultas se requiere por lo tanto pre-procesar sería innecesario
