### ISSUE TITLE
Botón pausar

### ISSUE THREAD

**Issue by vnespinosa** [IIC2233/syllabus#414]
Hola, al presionar el botón pausar, debo solo pausar el tiempo?, o debo prohibir tener cualquier interacción con el juego hasta que pongan continuar? Así como que no puedan cosechar o mover el personaje por ejemplo

**Comment by Dnpoblete** [comment]
Hola @vnespinosa la idea del botón de pausa es que funcione como en los juegos de computador o cualquier otro, en que al pausar no puedes mover tu personaje, no aparecen monedas ni nada por el estilo. Así que la respuesta es que debes pausar todo el juego, considerando que no se pueda mover el personaje, que no avance el tiempo, no se pueda cosechar, etc.

Éxito con la tarea! 😄
