### ISSUE TITLE
morenazo

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#414]
En el enunciado sale "te encuentras con una persona con proporción de genes AAT:GCG
de 1:2, estas en presencia de un morenazo" no debería ser blanco?

**Comment by TomasSalvadores** [comment]
Nop, el enunciado esta bien.

**Comment by movaldivia** [comment]
Pero dice 1:2 osea 50% AAT y en el cuadro 4 pone Gen1: 74,999% a 50% blanco

**Comment by naazocar** [comment]
Según entiendo proporción 1:2 significa que por cada 1 gen AAT tiene 2 GCG, ergo tiene 33.3333% AAT, por lo que entra en el intervalo (50, 25]%

**Comment by movaldivia** [comment]
Gracias! Tiene sentido
