### ISSUE TITLE
Uso de tuplas en map() y diccionario por compresión

### ISSUE THREAD

**Issue by SebaPassi** [IIC2233/Syllabus#414]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!

He visto ciertas issues donde se aclara que sí está permitido el uso de tuplas dentro de un map(). Por ejemplo: map(lambda x: (x.algo_1, x.algo_2), generador). A pesar de esto, me tira como si estuviese prohibido (al correr el archivo de elementos prohibidos).

Sumado a esto, ¿está permitido hacer un diccionario por compresión utilizando tuplas? Por ejemplo: "diccionario = {x.id: (x.caracteristica_1, x.caracteristica_2, x.caracteristica_3) for x in generador}" Para este caso también me tira error al correr el archivo de elementos prohibidos.

Muchas gracias!

**Comment by TomasGMDC** [comment]
@SebaPassi sobre lo primero, no se puede, ya que estás creando una estructura de datos por medio de comandos dentro de un map(), y no de un reduce() o una función generadora. Se están corrigiendo las issues y debes guiarte por lo que indica el script. Disculpas por las molestias.

Sobre lo segundo, tampoco se puede, en base a lo anterior: solo puedes crear estructuras de datos por medio de comandos dentro de un reduce() o una función generadora, tal y como se indica en " #339 ". Cuando digo comandos, me refiero a: list(), {}, (), [], etc.
