### ISSUE TITLE
[T02] Monedas de enemigos

### ISSUE THREAD

**Issue by Tito0906** [IIC2233/syllabus#414]
Holaa¡, las monedas que libera un enemigo muerto también deben respetar que no exista otra en ese lugar? Puedo asumir lo contrario? No me parece lógico que si mueren todos los enemigos en un sólo lugar, sólo se reciba una moneda.

**Comment by gatochico** [comment]
Hola! Como hay un solo tipo genérico de moneda en el juego, todas deberían comportarse de la misma manera, independiente de como se generaron (Aparición random o por muerte de enemigo). Por lo tanto, todas deben respetar las reglas del enunciado. Éxito 💻 🖱
