### ISSUE TITLE
DCCriaturas consideradas para nivel de aprobación

### ISSUE THREAD

**Issue by anamanzana** [IIC2233/syllabus#414]
Hola!

Me quedo la duda en el Nivel de aprobación si se calcula en base a las criaturas que se escaparon ese día o al total de las criaturas que escaparon (ese día y dias anteriores).

**Comment by fdoflorenzano** [comment]
Hola @anamanzana,
Se considera la totalidad de criaturas del Magizoólogo para hacer el cálculo.
Saludos.
