### ISSUE TITLE
Problema con instalacion de pyqt5

### ISSUE THREAD

**Issue by antoniacaceres** [IIC2233/syllabus#414]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Holaa, estuve intentando instalar PyQt5 y me tira este super error: 
![Captura de pantalla 2021-04-29 a las 12 02 44](https://user-images.githubusercontent.com/80801754/116581311-329a9980-a8e2-11eb-83d9-0eca369be78e.png)
(es un mac)
Gracias de antemano!

**Comment by aaossa** [comment]
Hola @antoniacaceres , ¿pudiste instalar PyQt5 finalmente? Si pudiste cuéntanos qué hiciste, pero si sigues con el problma responde por acá para que podamos revisar qué podría ser 🙌

**Comment by antoniacaceres** [comment]
holaa, no pude instalarlo

**Comment by aaossa** [comment]
¿Podrías probar si instalando esta versión anterior de PyQt5 no tienes el error?

```
pip3 install PyQt5==5.15.2
```

**Comment by antoniacaceres** [comment]
me tira el mismo error):
![Captura de pantalla 2021-05-01 a las 18 15 45](https://user-images.githubusercontent.com/80801754/116796185-a6869e80-aaa8-11eb-937b-e6bfb809f2a1.png)

**Comment by aaossa** [comment]
Mmm, ¿podrías decirme qué te aparece al actualizar pip y luego intentar instalar PyQt5?

```
pip3 install --upgrade pip
pip3 install pyqt5
```

**Comment by antoniacaceres** [comment]
al actualizarlo me dice esto:
Collecting pip
  Downloading pip-21.1.1-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 7.7 MB/s 
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1
Successfully installed pip-21.1.1

**Comment by antoniacaceres** [comment]
luego intento instalarlo y me tira el primer error que al principio

**Comment by antoniacaceres** [comment]
pero ahora me salió succesfully installed al final de los errores, debería funcionar?
![Captura de pantalla 2021-05-01 a las 18 39 37](https://user-images.githubusercontent.com/80801754/116796630-fa46b700-aaab-11eb-8a67-5a6e3a27e7ee.png)

**Comment by antoniacaceres** [comment]
he probado todo y no me funciona nada

**Comment by antoniacaceres** [comment]
desintalé python, lo instale de nuevo y ahí me funcionó altiro! gracias
