### ISSUE TITLE
¿Puedo crear un archivo de texto para el test?

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#415]
mi idea es crear un archivo con genomas con errores y otros sin para poder testar tanto errores como consultas

**Comment by Arcoirisky** [comment]
Si lo haces en la parte de Testing puedes hacerlo en el setUp y luego borrarlos en el tearDown O:

**Comment by nmaturana97** [comment]
y no puedo indicar que tal archivo tiene que estar en la carpeta para el testing? (la verdad ya lo cree :/), por ejemplo: genomas_para_testing.txt y listas_para_testing.txt?

**Comment by Arcoirisky** [comment]
Osea, no hay una restricción para eso pero si es sólo para el Testing, igual puedes hacerlo más simple y sería una buena forma de usar el setUp 👀👀
