### ISSUE TITLE
Duda sobre los datos entregados en Archivos

### ISSUE THREAD

**Issue by allisonaguilar** [IIC2233/syllabus#415]
Hola! en una parte del enunciado dice que el orden puede modificarse, pero puedo asumir que siempre me entregaran los mismos datos? o pueden no entregarme algunos de ellos? 
Es decir, en el caso de deportistas.csv puedo asumir que me darán nombre, velocidad, resistencia, flexibilidad, moral, lesionado y precio (en el orden que sea) ?

Gracias!

**Comment by itmunoz** [comment]
Correcto. Siempre se entregarán los mismo datos tanto en _deportistas.csv_ como en _delegaciones.csv_. Lo único que puede cambiar es el orden en que aparecen; por ello es fundamental guiarte por el _header_, el cual será la primera línea de los archivos.

**Comment by allisonaguilar** [comment]
Gracias!
