### ISSUE TITLE
Test_elementos_prohibidos y uso de list() en lista por comprensión.

### ISSUE THREAD

**Issue by diegofuentesy** [IIC2233/Syllabus#415]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, hice una pregunta en la issue de elementos prohibidos si es que se podía utilizar los comandos tuple() o lis() dentro de una lista por compresion. Di el ejemeplo de [list(x) for x in generador]. Me dijeron que si se podía usar pero en el test de elementos prohibidos me lo arroja malo. Que hago? lo ignoro o esta mal? igual que me arroja malo si hago [[x] for x in generador] pero trabajo todo dentro de listas por compresión, por lo que en teoría no debería estar mal. Gracias

**Comment by diegofuentesy** [comment]
Pregunta: https://github.com/IIC2233/Syllabus/issues/298#issuecomment-2120575981
Respuesta: https://github.com/IIC2233/Syllabus/issues/298#issuecomment-2121080358
Es la issue #298. Ideal si pueden revisarlo, que pregunte hace algunos dias ya y algunas partes de mi código lo hice con esto debido a que me dijeron que si se podía. gracias

**Comment by TomasGMDC** [comment]
@diegofuentesy la issue está siendo corregida. Guíate por el script, y disculpa las molestias.

**Comment by mpiavf** [comment]
Hola Diego! Sí, ese fue un error mío, disculpa las molestias que te pudo haber causado.
