### ISSUE TITLE
Resolución de pantalla recomendada para PyQt5

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#415]
Hola!

Al ejecutar códigos que crean interfaces gráficas noté que mi compu las abre más chicas de lo normal 😥. Me parece que es debido a la resolución de mi pc (3840 x 2160). De no solucionarlo creo que ocasionaría problemas en la siguiente tarea para el/la ayudante que corrija mi tarea.

¿Cuál es la resolución recomendada?
Gracias!

**Comment by Juampisaez** [comment]
Hola @jamigone 
Probablemente es lo que dices, normalmente un pc tiene una menor resolucion (notebook), el mio es de 1366 x 768 pixeles por ejemplo. Yo te recomendaría tener esta medida de referencia al momento de hacer tu tarea para hacer mas facil la corrección de las tareas que vienen despues. Una forma de arreglarlo es hacer tus interfaces mas pequeñas.

Quedo atento si tienes otra duda :)
