### ISSUE TITLE
Actualizar QgridLayout

### ISSUE THREAD

**Issue by mbcarcamo** [IIC2233/syllabus#415]
Hola, tengo una duda, hice mi inventario como una grilla donde cada elemento es un QLabel, en el cada imagen del inventario va acompañada con el número de unidades que posee. Luego cada vez que compro o vendo un elemento no se como hacer que se actualicen los cambios, intenté sobreescribir la grilla pero no resultó, ¿hay algún método que me retorne un elemento de la grilla según su posición y así simplemente hacer .setText("") al elemento para actualizar las unidades existentes?

**Comment by tomasgv** [comment]
Hola!

Existe un método para retornar objetos de la grilla especificando fila y columna, el cual puedes encontrar en https://www.riverbankcomputing.com/static/Docs/PyQt4/qgridlayout.html. También hay formas de encontrar items especificando posición en x e y.

Espero haberte ayudado! 🌱
