### ISSUE TITLE
Problema con Sprites

### ISSUE THREAD

**Issue by Naogaz** [IIC2233/syllabus#415]
Por alguna razon no puedo cargar ningun otro sprite distinto que los sprites "m".

![61188929_303160337227166_6830765439811846144_n](https://user-images.githubusercontent.com/48302271/58377367-7d6c4380-7f4c-11e9-8274-88f8b7710a19.png)
![61431839_424284101453680_4211310562958639104_n](https://user-images.githubusercontent.com/48302271/58377368-80ffca80-7f4c-11e9-875f-358061dcd01e.png)
![60952654_833602780346901_5841062648187191296_n](https://user-images.githubusercontent.com/48302271/58377369-82c98e00-7f4c-11e9-9ad2-bf75dd09f966.png)

probe moviendo los archivos a otras carpetas y solo carga "m" aunque no carga cuando lo agrego a carpetas como la de los pinguinos o a la carpeta f

**Comment by lily416** [comment]
Estas ingresando mal los _patha_ de los archivos, los _sprites_ del personaje femenino se encuentran en `sprites/personaje/f/` y sus nombres son de la forma `f_xx.png`.

Saludos y éxito con la tarea 👋 🐈🐧
