### ISSUE TITLE
Multiherencia con QObject y pyqtSignal

### ISSUE THREAD

**Issue by pazanelli** [IIC2233/syllabus#416]
Hola, para la tarea quisiera crear una clase que herede de `list` pero que a su vez pueda emitir señales. El problema es que cuando creo una clase que hereda de `list` y de `QObject`  me tira el error: **TypeError: multiple bases have instance lay-out conflict**, y creo que es porque no admite esta multiherencia. He buscado pero no encuentro la solucion asique quiero preguntar: 
1. ¿Para emitir señales `pyqtSignal` la clase necesariamente debe heredar de QObject?
2. ¿Hay alguna forma de hacer lo que quiero correctamente?

Quiero que mi clase herede de list porque quiero poder agregar y quitar fácilmente cosas de una instancia de ella.

**Comment by jmwielandt** [comment]
Hola!

El error que te tira es porque PyQt5 se implementa en C++, que tiene OOP pero no multiherencia (muchos lenguajes lo restringen para evitar el problema del doble diamante). Es por esto que no te lo permite :( Tampoco vas a poder heredar de varios objetos de PyQt5 a la vez.

Sí necesitas que herede de QObject para poder emitir señales.

<details>
<summary>(Lo probé).</summary>
<br>

![image](https://user-images.githubusercontent.com/37153467/66317311-a1bf3000-e8ef-11e9-9692-fa7321d02522.png)

</details>

Vas a tener que hacer una clase QObject que contenga la lista como atributo. Podrías definirle los _dunder methods_ `__getitem__` y `__setitem__` para poder usar la sintaxis self[index], que es lo que entiendo que quieres hacer.

Saludos!
