### ISSUE TITLE
Rangos de atributos

### ISSUE THREAD

**Issue by fddelabarra** [IIC2233/syllabus#416]
Tengo una duda con el enunciado donde dice:
"Su nivel magico varıa entre 20 y 25", "Su nivel magico varıa entre 10 y 20", etc
Con esto se refiere a que esta entre 20 - 21- 22 -23 -24 y 24?? o solo "20 o 25"?

**Comment by fdoflorenzano** [comment]
Hola @fddelabarra,
Es lo primero que indicas, un valor entero entre los límites del rango, incluyendo sus extremos.
Saludos.

**Comment by camolina2** [comment]
hola! cuando dice un valor del tipo int que toma un valor aleatorio uniforme entre 5 y 10, necesariamente tiene que ser distribución uniforme? es que esta solo retorna valores de tipo float. Puedo usar otra aunque no sepa realmente si es distribución uniforme que incluya solo esos valores? como random.randit(a,b)
gracias!

**Comment by fdoflorenzano** [comment]
hola @camolina2,

Si te refieres a la función `uniform`, que solo retorna `float`s, no es necesario usar esa función específica para tener una distribución uniforme. 

Si te fijas en la[ documentación de `random`](https://docs.python.org/3/library/random.html), se menciona que las funciones principales como `randint` son uniformes entre enteros. Puedes usarla con tranquilidad.

Saludos.
