### ISSUE TITLE
Gitignore

### ISSUE THREAD

**Issue by ian-fell** [IIC2233/syllabus#416]
Hola. Tengo un problema con el .gitignore, y es que a pesar que pongo los archivos que no se deben subir, como el enunciado y los .csv, se suben de todas maneras al repositorio. No se si es porque los tengo mal escritos o algo.
<img width="631" alt="Captura de pantalla 2020-09-08 a la(s) 16 30 56" src="https://user-images.githubusercontent.com/62180167/92519758-e71b6a00-f1f0-11ea-8194-c8101cb31f7f.png">

**Comment by itmunoz** [comment]
Hola! Por lo que veo, escribiste mal el nombre del archivo, pues pusiste ".gtignore".
