### ISSUE TITLE
Proporción forma continua.

### ISSUE THREAD

**Issue by fgbruna** [IIC2233/Syllabus#416]
Tal vez es muy básica la pregunta, pero quiero asegurarme.
En el cálculo de los fenotipos de la forma ~~complementaria~~  continua :grin: la proporción que debemos usar es:
`p = (#gen 1)/ (# complementario) o p = (#gen1 / (#complementario + #gen1) )` ?

**Comment by DquezadaO** [comment]
Según yo si tienes 100% del gen 1 y 0% del complementario deberías expresar el gen 1, cosa que no se cumple en la primera ecuación. Igual me gustaría la opinión de algún ayudante para corroborar

**Comment by TomasSalvadores** [comment]
Debido al titulo de la issue, asumo que donde pones “forma complementaria” te refieres a continua. 
Piensa en un ejemplo, si tienes 10 genes 1 y 90 genes 2, cual es el porcentaje de genes 1?
Con cual de esas formulas llegas a ese resultado?
#Animoquevaquedandomenos!

**Comment by fgbruna** [comment]
@TomasSalvadores  Gracias!

**Comment by xariveros** [comment]
Hola!, una duda similar. Para la forma determinista, por ejemplo, si hay 1 GTG (pelo negro) y 1.000 CCT (pelo pelirrojo), la persona tendría el pelo negro?? No me queda tan claro porque me da que todos tienen el pelo negro, que ninguno nariz recta y ninguno ojos verdes. No sé si lo entendí mal el enunciado o esta bien que ocurra esto. Muchas gracias!

**Comment by fgbruna** [comment]
Me pasa lo mismo que a @xariveros , pero según yo mi algoritmo esta bien implementado:sweat_smile:, así que supongo que esos deberían ser los resultados para la base de datos inicial

**Comment by Hernan4444** [comment]
@xariveros intentaste ver con la nueva base de datos que subimos? ahí hay gente con pelo de otro color. Y si, con que exista un gen dominante (como el pelo negro) es suficiente para que el fenotipo sea negro.

Saludos ✌️
