### ISSUE TITLE
Funcionamiento del des-descuento

### ISSUE THREAD

**Issue by lfb1206** [IIC2233/syllabus#416]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Revisando el feedback de la tarea 0 me entro esta duda ¿Como funciona el des-descuento? ¿Se agregan esas décimas en la nota final o en el caso de un descuento se des-descuenta a ese descuento?

**Comment by gatochico** [comment]
¡Hola @lfb1206!

Respecto al des-descuento, este funciona de la siguiente manera:

- Primero, el desdescuento no son décimas automáticas a la nota 🙅‍♀️. Como dice su nombre, la idea es **contrarrestar** algún posible descuento que hayas obtenido en la tarea (una mala práctica o descuento del ayudante, por ejemplo). Por lo tanto, este solo puede eliminar como máximo 5 décimas de descuento que se haya aplicado en tu tarea. Si no obtuviste ningún descuento, el des-descuento no afectará en nada a tu nota.
- Además, el des-descuento **no aplica** sobre los siguientes descuentos: Entrega atrasada y Librerías prohibidas. Por lo tanto, si tienes algún descuento en estos 2 ítems, esté no podrá ser eliminado por un buen README.

Todo esto sobre el des-descuento y los descuentos en general, lo puedes leer en detalle en la página [Tareas/Descuentos.md](https://github.com/IIC2233/syllabus/blob/main/Tareas/Descuentos.md) del Syllabus.

Saludos!
