### ISSUE TITLE
Error al crear una nueva consulta

### ISSUE THREAD

**Issue by berrazuriz1** [IIC2233/Syllabus#416]
Tengo un problema. Mi tarea corre todo bien, probé todas las consultas que venían en el archivo consultas.json y todo, pero cuando yo escribo una consulta, la mando con el botón de Enviar consulta y realizo la consulta el programa se me cae. No es un error de tipeo y no me eleva ninguno de los errores que le puse al programa. Incluso copie textual una de las consultas dadas y tampoco me funciona, pero si me funciona si la corro  desde Abrir y selecciono la consulta. A una amiga le pasa lo mismo. la pregunta es, ¿existe la posibilidad de que la interfaz este mala, o nadie mas le pasa?

**Comment by Hernan4444** [comment]
@berrazuriz1 una opción es que el programa es sensible a comillas simples `'`, tienes que escribir siempre una consulta con comillas dobles `"`. Si no es eso ¿puedes intentar meter el código del main dentro de un try gigante con `exception Exception as e: print(e)` para ver que error te indica?

saludos!

**Comment by berrazuriz1** [comment]
Ya lo resolvi, no eran las comillas, era que habia puesto la condicion de un error mal, por lo que tampoco funcionaba si elegía la consulta desde abrir. Pense que era el enviar consulta por que no le había cambiado nada, pero le había incluido el error mal, lo que hizo que se caiga todo.
