### ISSUE TITLE
Crear QWidgets (QLabels) dinamicamente

### ISSUE THREAD

**Issue by cambrinKD** [IIC2233/syllabus#416]
Es facil crear el caracter principal (su QLabel) usando un metodo del Window principal (algo como self.main_caracter = Character). Pero cuando quiero crear enemigos o otros cosas, donde va a haber mas de uno de ellos, necesitará algo como self.enemigo1, self.enemigo2, etc. Hay una manera de hacer esto dinamicamente? O hay una manera de evitar esto?

**Comment by lily416** [comment]
Puedes guardar todas las _labels_ en una lista o diccionarios que contenga todos los `QLabels` de los enemigos, de esta forma podrás crear n enemigos sin perder sus _widgets_. 

Saludos y éxito con la tarea. 👋 🐈🐧
