### ISSUE TITLE
Actualización de archivos

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#417]
EDIT: ¿Tengo que actualizar el archivo de magizoologos cada dia que pase? (Título anterior)

Lo de el titulo, puedo hacer que se guarde solo cuando el usuario sale o tiene que ser cada dia?

**Comment by fdoflorenzano** [comment]
Hola @sofiuni,
No hay una regla específica sobre como o cuándo deben actualizar los archivos, si lo reservan para ciertos momentos, es criterio suyo.

¡Saludos!

PD: Alteré el título y contenido de tu pregunta para que sea más fácil de buscar y revisar para el resto.

**Comment by sofiuni** [comment]
Oki! Gracias por la respuesta
