### ISSUE TITLE
INICIAR NUEVO DÍA

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2233/syllabus#417]
Hola! Cuando me paro sobre la casa, debo iniciar un nuevo día, esto incluye que la hora cambie??? por ejemplo si mi hora cada dia parte en cero, y me meto en la casa el día 4 a las 10, debo cambiar fecha y hora por día 5 a las 0 o dia 5 a las 10?

**Comment by gatochico** [comment]
Hola! 

El primer caso sería el más correcto: cuando el personaje se vaya a dormir :zzz:, el siguiente día siempre parta en una hora fija (por ejemplo, 8 am.). Sin importar si se acueste a las 17:00 o a las 21:00, siempre amanecerá en dicha hora. Sin embargo, como no está definido de forma explícita en el enunciado, puedes dejarlo a tu criterio, **siempre y cuando lo explicites en tu README**.

Saludos y éxito!

**Comment by jfuentesg26** [comment]
Eso también significa que al pararme en la casa y avanzar la hora mis cultivos deberían "ajustarse" a esta hora?? Es decir, deberían aparecer cosechados??

**Comment by gatochico** [comment]
Los cultivos deberían haber progresado el tiempo respectivo que se durmió. Si dormiste 8 horas, el cultivo al siguiente día debería aparecer como si hubieran pasado estas 8 horas de forma automática.

**Comment by jfuentesg26** [comment]
¿Y el paso de los días cuando entro de la casa? por ejemplo si mi parametro dice que un dia son 24 horas del juego (1440 segundos), una vez que pasen esas 24 horas agrego +1 a la cuenta de dias y hago aparecer oro y arbol o  tengo que simular la noche tambien y hacer que el personaje duerma durante ese tiempo y recupere energía

**Comment by gatochico** [comment]
El personaje no está obligado a dormir si el jugador no lo desea, así que tu primera opción sería la correcta, siempre y cuando siempre se muestren de forma correcta los días y horas de juego en la interfaz. 

Por otro lado, si implementas el bonus de la casa, el tiempo debe pasar normalmente dentro de esta a menos que se vaya a dormir (utilice la cama).

Si no respondí tu duda, por favor avisame!

**Comment by jfuentesg26** [comment]
Si! Entendi perfecto, gracias!!!
