### ISSUE TITLE
Módulos de pyqt5 no reconocidos en importación

### ISSUE THREAD

**Issue by ljgonzalez1** [IIC2233/syllabus#417]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Sé que esto tenía que estar listo hace como una semana, pero estaba metido en la tarea.

Instalé PyQt5 sin problemas con `python3.7 -m pip install pyqt5`. Si uso el comando sugerido en la wiki del ramo va por defecto a la versión de python del sistema.
A la hora de importarlo, lo reconoce. Pero al importar cualquiera de sus módulos (ej: `PyQt5.QtWidgets`) me tira error diciendo que no lo encuentra.

![image](https://user-images.githubusercontent.com/48295025/116717103-8969a700-a9a6-11eb-9902-23343b55f7ed.png)

Me aseguré de tener la librería instalada en la versión de python que uso para este ramo y confirma que ya se encuentra (con algunas advertencias que no entiendo de por medio).
![Screenshot_20210430_111350](https://user-images.githubusercontent.com/48295025/116716918-50313700-a9a6-11eb-9b29-e7e3814782a2.png)

Revisé en la carpeta y los módulos efectivamente se encuentran donde se supone que tienen que estar
![Screenshot_20210430_112619](https://user-images.githubusercontent.com/48295025/116717638-1e6ca000-a9a7-11eb-88f4-60f0c7ee6fdf.png)

¿Alguna idea/sugerencia de cómo puedo hacer para que reconozca los módulos?

_Información del sistema (puede ser de utilidad):
OS: KDE Neon 5.21.4
Kernel: Linux 5.4.0-72
DE: Plasma
WM: KWin_

**Comment by Juampisaez** [comment]
Hola @ljgonzalez1 
Perdon la demora. Tengo un par de preguntas antes:
- ¿Tienes linux o mac? (me da la impresion de linux, pregunto solo para estar seguro)
- probaste instalandolo con pip3?

Quedo atento :)

**Comment by ljgonzalez1** [comment]
Linux. Está en la información que puse al final.
Si uso pip3 se va por defecto a la versión de python del sistema (3.9) y no a la que uso para el ramo (3.7).
Como instalé python 3.7 aparte, si instalo librerías con pip3 no me las reconoce (ya he probado).

**Comment by ljgonzalez1** [comment]
:eyes:

**Comment by Pablok98** [comment]
¡Hola! Puedes usar el pip de python 3.7 puedes usarlas utilizando `pip3.7 install`. Prueba si te funciona!

**Comment by ljgonzalez1** [comment]
Me dice que no existe el comando y no hay un paquete con ese nombre que pueda instalar.

![image](https://user-images.githubusercontent.com/48295025/117212434-55d4b580-adc8-11eb-9c4e-9e3cb0ba4688.png)
