### ISSUE TITLE
Funcion asignar

### ISSUE THREAD

**Issue by NicolasCourt** [IIC2233/Syllabus#417]
Tengo una duda, si yo por ejemplo le asigno a la variable "x" la función "PROM"  y luego le asigno a la variable "y" la función "PROM", se espera que cuando llame a "x" o "y" me retorne como "PROM" o solo me debería retornar para el ultimo caso, para este ejemplo solo me retornaría "PROM" si llamo a "y"

**Comment by Hernan4444** [comment]
ambas variables harán referencia a "PROM" y por lo tanto si llamas a "x" o "y" debería funcionar.

Saludos!

**Comment by NicolasCourt** [comment]
Muchas gracias!!
