### ISSUE TITLE
Test elementos prohibidos - Archivos extras

### ISSUE THREAD

**Issue by SebaPassi** [IIC2233/Syllabus#417]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!

Tengo un archivo llamado "funciones_extras.py" en el que hago el desarrollo de algunas consultas y que luego importo al archivo "consultas.py".

¿El test entregado para ver si cumplimos con los elementos prohibidos también tiene en consideración estos otros archivos extras? ¿O debo hacer todo en consultas.py y ahí correr ese test para ver si cumple con lo pedido?

Muchas gracias!

**Comment by Hernan4444** [comment]
Hola @SebaPassi 

El archivo buscará los demás .py y verificará todo. Así que si el script dice que una consulta es `true`, entonces está todo bien.

Si quieres experimentar, puedes agregar a la mala un `list` en alguna función dentro de `funciones_extras.py` y podrás ver que el script te lo acepta siempre y cuando dicha función no sea generadora.

Saludos!
