### ISSUE TITLE
Linter VSCode

### ISSUE THREAD

**Issue by dvaldesg** [IIC2233/syllabus#417]
Holaaa
Pasa que, cuando configuré en un principio vscode, me funcionaba super bien en relación al tema problemas (cuando me faltaban lineas entre funciones, tenia una variable mal escrita o sin utilizar, cuando me pasaba de cierta cantidad de lineas, etc me avisaba que tenia errores con un número y subrayando el error) y después de subir la T0 dejó de funcionar xd
alguien sabe como puedo solucionarlo sin reinstalar todo de nuevo?

**Comment by tocococa** [comment]
Hola @dvaldesg ! ¿Revisaste que el _linter_ siga activado? ¿Y dejó de funcionar una vez que hiciste el último push de la T0 o pasó algo después?

Puedes ver si está activado o desactivado abriendo el _command palette_  de VSCode con `ctrl + shift + p`, escribes `linter` y al hacer click en `Python: Select linter` deberías poder elegir entre distintas opciones.
