### ISSUE TITLE
uso exec__

### ISSUE THREAD

**Issue by tomcan127** [IIC2233/syllabus#417]
Puedo usar el exec__ de la ultima linea?
Este mismo es usado en el main, para correr el programa.
Es diferente al exec prohibido?
![image](https://user-images.githubusercontent.com/44327650/58384409-572bbf80-7faf-11e9-869e-bdcd2959ba8f.png)
![image](https://user-images.githubusercontent.com/44327650/58384436-85110400-7faf-11e9-8be5-76d6fe705c65.png)

**Comment by DCCollao** [comment]
Hola! En #198 va este tipo de preguntas, y además ya fue preguntado. Recuerda revisar antes, para no tener varias issues hablando de lo mismo.
Éxito!
