### ISSUE TITLE
best_comments

### ISSUE THREAD

**Issue by gejohow** [IIC2233/Syllabus#417]
Hola queria saber si me pueden aclarar la parte de cuando n es negativo:
Se debe entregar las n peliculas, y sus demas columnas, con mas comentarios positivos, si n es un numero negativo, entonces entrega las -n peliculas con mas comentarios negativos.
1. Quiere decir que si n es negativo debo entregar las n peliculas con más comentarios negativos?
2. El archivo de los comentarios entonces es el mismo que se utiliza para el procesamiento?
3. Que pasa si el valor de n sobrepasa la cantidad de comentario positivos o negativos
Saludos

**Comment by Arcoirisky** [comment]
1) Si O:
2) Estoy segura que ya hay una issue sobre procesamiento. ¿Por qué no hechas un vistazo?
3) No está en el enunciado, así que queda a tu criterio c:
