### ISSUE TITLE
Errores y exceptions

### ISSUE THREAD

**Issue by behrmann97** [IIC2233/Syllabus#418]
¿La idea es crear errores personalizados (estilo class BadRequest(TypeError):pass) o simplemente hacer excepciones que impriman 'Error: Bad Request'? La pregunta va a que si hay que crear errores o solo usar los existentes.

**Comment by Arcoirisky** [comment]
Se espera que se cumpla el ítem 4 del enunciado. No entiendo a qué va tu pregunta ¿Podrías explayarte un poco más?

**Comment by behrmann97** [comment]
Dice el enunciado que hay que controlar las excepciones dadas. Mi pregunta es si hay que hacer los errores con los nombres, como en esta imagen
![image](https://user-images.githubusercontent.com/26407766/31146399-f66557cc-a85c-11e7-81ee-24f0c198fc13.png)
y luego controlar esos errores, o simplemente utilizar errores ya existentes (como TypeError) cuando ocurran las situciones dadas y al momento de controlarlas, poner que printee lo necesario. Creo que se entiende más con un ejemplo:
caso 1:
la consulta no da resultados: raise NotAcceptable
y en el main tener: except NotAcceptable: algo

caso 2:
la consutla no da resultados: raise TypeError
main: excecpt TypeError: print('Error: Not Acceptable')

**Comment by Arcoirisky** [comment]
Caso 1. Sí, absolutamente, definitivamente sí. 
Si te das cuenta, hay una gran diferencia entre el caso 1 y el caso 2. El primero atrapa distintos tipos de errores, el segundo los atrapa todos y ahí ve qué es lo que pasa. Lo mejor que puedes hacer es el caso 1 😱

**Comment by Sforrego** [comment]
@Arcoirisky en ese caso se podria heredar simplemente de exception?

**Comment by Arcoirisky** [comment]
La idea es que sepas atrapar un error identificable. No todos de una a pesar de que al final lo separas, ya que, eso es un mal uso de excepciones. Piensa bien en lo que vas a usar.

**Comment by felipecr00** [comment]
Respecto a los errores, puedo crear una clase que sea como formato errores y luego tener metodos que vayan diciendo que error es (como esto):
por ejemplo
``` python
class Formato:
       def not_aceptable(self, dato)
           if #alguna condicion que deberia cumplir el dato :
                raise ValueError("Error: Not Acceptable")
```
y usar la clase en otros modulos para que haga las cosas que necesito (como imprimir el "Error: Not Acceptable") ???

Saludos!!
