### ISSUE TITLE
Cheat codes

### ISSUE THREAD

**Issue by MGilB** [IIC2233/syllabus#418]
Una pregunta los cheat codes son solo con las letras mayúsculas o se deben activar si son minúsculas también??

**Comment by Hernan4444** [comment]
Hola

Como el enunciado no quedó claro en ese aspecto, queda a tu criterio pero recuerda especificarlo en el readme. De todos modos el `event.key() de `keyPressEvent` no diferencia entre mayuscula o minúscula y si usas _string_, los métodos `upper` o `lower` pueden ser de utilidad.

Saludos ✌️
