### ISSUE TITLE
Git ayuda

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#418]
hola, cuando subi mi ultimo commit de la tarea 3 ocurrio algo extraño, asi que queria perguntar si esto es un error y si puede provocar problemas cuando se corrija a y como arreglarlo pls. (esto no habia pasado antes :(  y no se que pudo provocarlo)

![capture](https://cloud.githubusercontent.com/assets/26102365/25754723/a8641aaa-3196-11e7-8b83-47ac083aa3d9.PNG)

**Comment by jtagle2** [comment]
Eso no es ningún error. Es simplemente que lo que subiste fue la fusión de dos branchs. Dudo que hayas usado el comando git branch o git checkout, por lo que si me pongo a adivinar, creo que esto es lo que pasó:
1.- Hiciste un cambio en tu repositorio desde la página (ej: Subir una ac directamente a git a través de la pagina, actualizar un readme porque te habias equivocado en algo chico, entre otras)
2.- Hiciste cambios en tu computador (repositorio local), e hiciste un(os) commit(s).
3.- Hiciste git push y no te dejó porque tenías trabajo en el repositorio remoto que no tenías local
4.- Hiciste git pull, y te actualizó el repositorio local (y es aquí donde se hace un merge: Se junta el commit que subiste directamente a través de un navegador, y el que tenías hecho de manera local)
5.- Hiciste git push, funcionó y subiste el merge.

Si no es eso lo que pasó, adiviné mal :( . De todas formas no te preocupes, no es un error, es una funcionalidad de git que en ramos de más adelante te va a servir más.
Saludos!

**Comment by Dunkan1** [comment]
:open_mouth: :open_mouth: :open_mouth: :open_mouth: :open_mouth: :open_mouth: :open_mouth:
gracias
1.- hice un cambio en el README desde la pagina
2.- hice unos commits
3.- no me dejo hacer el git push
4.- hice git pull me actualizo
5.- hice git push y me aparecio el mensaje
5/5 , estoy impactado....
