### ISSUE TITLE
Inconsistencia test_19_porcentaje_apoyo_especie.py

### ISSUE THREAD

**Issue by joseracioppi** [IIC2233/Syllabus#418]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo una duda con el test_19. Tengo malos los test desde el 1-5, pero tengo buenos los test 6-8, que son los que corresponden a la base de datos. Creo que se debe a una inconsistencia entre el formato de la información de los archivos y los test creados.
En los archivos, los candidatos se encuentran también en en el archivo de animales, y el id de candidato corresponde al id de animal. Por ejemplo, si el animal con id 5 vota por el candidato con id 7, al buscar el id 7 en el archivo de animales, me encontraré con la información del candidato votado. Esto no es así en los test cases del 1-5, donde hay candidatos que no se encuentran dentro de los animales.

**Comment by fmandiolafellay** [comment]
Me pasa lo mismo, se repiten id para dos animales distintos.

**Comment by Jeremiah-PHP6** [comment]
¡Hola! Ojo que Candidato.id_candidato no es lo mismo que Animal.id, ya que los candidatos no necesariamente van a estar dentro de animales (al menos en los testcase). Sin embargo, esto último puede llegar a pasar, si bien no es la regla general. Un claro ejemplo de esto son los test que mencionabas.
Espero haber respondido tu duda, saludos.
