### ISSUE TITLE
Materia Semana 7 , QThread y Señales

### ISSUE THREAD

**Issue by CarlosValleA** [IIC2233/syllabus#418]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola ! no logro ver la diferencia entre los ultimos dos bloques de codigo de archivo 1 de la semana 7.  En el bloque de mas arriba se dice que _"...luego de unas centenas de threads creados, el programa colapsa"_, lo cual no pasa en mi computador. Me puse a compararlo con el codigo siguente y no veo diferencias (quiza estoy piti), ya que ambos usan señales. Sera un error con el material ?

Gracias!

**Comment by imuoz** [comment]
Confirmo, ambos códigos son iguales jajaja

**Comment by aaossa** [comment]
Hola @CarlosValleA e @imuoz , efectivamente es una celda duplicada. Al parecer no podían ver la solución "incorrecta", entones siempre les funcionaba. Estoy corrigiendo el error en los repos de contenidos, así que cuando vean este comentario ya debería estar publicada la corrección y podrán ver la diferencia entre utilizar señales y no utilizarlas 👌 ¡Éxito con su estudio!
