### ISSUE TITLE
Cantidad de parámetros de consultas

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2233/Syllabus#418]
Para verificar los parámetros para levantar WrongInput, ¿podemos asumir que la cantidad de parámetros siempre será la correcta? Si no es el caso, ¿cómo mostramos el error? Ya que se pide mostrar la película, parámetro que genera el error y valor del parámetro, pero en ese caso no existiría el parámetro como para indicarlo. (Por ejemplo, si load_database( ) se entrega con un parámetro, no tendría como mostrar el nombre del parámetro)

**Comment by jpmoraga1** [comment]
Creo que no, por lo que entendí del enunciado una BadQuery es una consulta que no existe en el sistema, en este caso existiría pero se entregarían argumentos extra

**Comment by Arcoirisky** [comment]
En el enunciado dice "Mal escrita o no existe" O: Si le faltan parámetros sería mal escrita O:

**Comment by pcseisdedos** [comment]
mmm yo había interpretado que BadQuery iba dirigida al nombre de la consulta (dado que eso es lo que se debe indicar cuando se genera esta excepción) y no a los parámetros, pero tal como dice @jpmoraga1 si a una consulta le faltan o sobran parámetros no sabría indicar cual es el parámetro que causó el error :/ (se podría establecer un criterio para eso) o quizás me estoy enredando mucho y simplemente debería imprimir el nombre de la consulta (aunque esta esté bien escrita) y catalogarla como BadQuery
