### ISSUE TITLE
Error: Se cierra programa al enviar señal

### ISSUE THREAD

**Issue by vchadwick** [IIC2233/syllabus#418]
Hola, estoy utilizando Pycharm para crear la tarea. En la la tarea se mandan varias señales entre los respectivos frontend y backend y funcionan todas correctamente menos una (en mi programa llamada señal_procesar_jugador, que ocurre cuando se presiona una tecla) que hace que el programa se cierre. La señal es enviada entre mi frontend (VentanaJuego) y un backend(Jugador).
Cuando corro el programa normalmente los errores son:
     - Process finished with exit code 138 (interrupted by signal 10: SIGBUS)
Y cuando corro el programa con debug (no se para que sirve):
     - pydev debugger: process 1833 is connecting
     - Connected to pydev debugger (build 192.6817.19)
     - Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

He buscado en internet pero no he llegado a una solución. También descargue la nueva versión de Pycharm pero tampoco fue la solución.

Subi el avance de mi tarea a mi repositorio.

**Comment by itplanella** [comment]
Hola! no se si sea el problema, pero me paso que al usar la letra "ñ" en la variable de una señal, como en tu caso "seÑal_procesar_jugador", me arrojaba error, asi que cambie la "ñ" por una "n" y funciono. Quizás si haces eso te funcione. Suerte!

**Comment by vchadwick** [comment]
Ya me ayudaron a solucionar el problema! Era un problema con definición de variables, es decir, el backend tenia el mismo nombre que un label.

**Comment by aljara97** [comment]
Perfecto, muchas gracias por avisar. También gracias @itplanella por aportar con la solución cuando no podemos responder issues ;)
