### ISSUE TITLE
nonlocal variables

### ISSUE THREAD

**Issue by Baelfire18** [IIC2233/syllabus#419]
Penalizan por usar variables globales, ¿pero por usar variables nonlocal?

**Comment by jeschuwirth** [comment]
Hola @Baelfire18,

Personalmente no había escuchado de ese término, acabo de leer un par de páginas para aprender un poco como funciona.

Como la idea de no usar variables globales es enseñar el uso de funciones, **no** esta permitido usar nonlocals.

Si comentas en esta issue un ejemplo de como lo quieres implementar se puede discutir con los ayudantes, pero considéralo como no permitido hasta que se avise lo contrario.

Suerte!
