### ISSUE TITLE
Progressbar

### ISSUE THREAD

**Issue by miortiz1** [IIC2233/syllabus#419]
Hola, la vida de mi base esta siendo seteada de la siguinte forma cada vez que es atacada:
    def atacada(self):
        self.barra_vida.setValue(max(0,int(self.hp*100/self.hp_max)))
        print(f"{int(self.hp*100/self.hp_max)}%")

sin embargo en el juego la barra de vida solo me muestra un cambio cuando llega a 75, 50, 25 y 0 % de hp y sé que esta siendo seteada tambien en 60%, por ejemplo, pero no me muestra ningun cambio en la pantalla. A qué se puede deber esto? Por que con unos valores si funciona y otros no?

**Comment by Ed0ss** [comment]
Hola, creo que el siguiente link te puede ayudar: https://stackoverflow.com/questions/51509798/qtwidgets-qprogressbar-settextvisiblefalse-causes-lag, en el caso que hayas usado setTextVisible para quitar el porcentaje de la barra. Saludos!
