### ISSUE TITLE
Problema Git: "Another git process semms to be running..."

### ISSUE THREAD

**Issue by mpmunoz13** [IIC2233/syllabus#419]
Hola! 
Sin querer hice "git commit ." en vez de "git add ." al entrar en git Bash y ahora no me deja hacer add y me tira el siguiente error:

> Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.<

He tratado de usar varias cosas que encontré en internet y no he logrado solucionarlo. Git status aparece normal pero al tratar de hacer add en cualquier archivo me tira ese error.

**Comment by fdoflorenzano** [comment]
Hola @mpmunoz13,

Por lo que investigué, puede que se haya generado por error de funcionamiento interno de Git. Una forma es eliminando un archivo `index.lock` ubicado dentro de la carpeta oculta `.git` que se crea en la raíz de todo repositorio. Puedes manualmente buscar tal carpeta (en el repositorio donde te ocurre esto), buscar el archivo indicado, y eliminarlo. Para eso, debes tener habilitada la opción de ver archivos y carpetas ocultas en tu máquina.

Si no te funciona, mencionaste que probaste soluciones de internet. ¿Cuáles fueron? Así tenemos un poco más de información.

Saludos, quedamos atentos.

**Comment by mpmunoz13** [comment]
Muchas gracias! Solucionado!!
