### ISSUE TITLE
Duda acceso property y herencia

### ISSUE THREAD

**Issue by BFry712** [IIC2233/syllabus#419]
Hola! queria saber si yo defino una property por ejemplo dinero(con el setter tambien) y luego en la clase DCCrotona yo con funciones modifico el dinero.(Por ejemplo con la función de usar_habilidad_especial).
Por que me puede aparecer este error?: TypeError: dinero() takes 1 positional argument but 2 were given

**Comment by amparostevens** [comment]
Hola! 
Cómo estás definiendo la property? Si puedes sube tu código a tu repositorio para poder verlo.

**Comment by amparostevens** [comment]
Hola! 
Cómo estás definiendo la property? Si puedes sube tu código a tu repositorio para poder verlo.

**Comment by BFry712** [comment]
hola! si! lo subí a T01 delegaciones.py c:

**Comment by amparostevens** [comment]
Si se fijas el error dice que le pasaste 2 argumentos pero que en realidad toma 1. Esto es porque cuando definiste el método ` def dinero (self)` sólo le pasas __self__ como argumento. 

Luego cuando intentas modificar el atributo al hacer `self.dinero -= 30`  le estás pasando, aparte de self que viene implícito, el argumento 30 y por eso falla. 

Tal como aparece en los contenidos del curso, un ejemplo de cómo definir una property sería el siguiente:

``` @property
    def personas(self):
        return self.__personas

    @personas.setter
    def personas(self, nuevo_valor):
        if p > self.maximo:
            self.__personas = self.maximo
        elif p < 0:
            self.__personas = 0
```


 En tu caso faltaría darle el argumento correspondiente a `nuevo_valor`, que es el valor ya modificado de personas.

Espero que aclare tu duda! ✨

**Comment by BFry712** [comment]
Muchisimas gracias! c:
