### ISSUE TITLE
Contenidos del Midterm

### ISSUE THREAD

**Issue by mrebolledo03** [IIC2233/Syllabus#419]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Contenido

Hola, no encunetro donde estan los contenidos que seran evaluados en el midterm del jueves, donde estan? o cuales son?

**Comment by Hernan4444** [comment]
Hola @mrebolledo03 

La semana pasada (lunes o martes) cada profesor mandó en su sección el aviso semanal (o resumen de la semana 8), donde se incluyó información relevante del midterm como los contenidos y otras cosas más sobre el formato de la evaluación o qué implica la ausencia de la evaluación.

Saludos!

**Comment by mrebolledo03** [comment]
gracias
