### ISSUE TITLE
Podemos confiar de test_elementos_prohibidos.py ??

### ISSUE THREAD

**Issue by MathiasPrett** [IIC2233/Syllabus#419]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/396)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/395)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. Hice algunas pruebas con el test de elementos prohibidos, escribiendo en mi código a propósito comandos prohibidos como list() o for x in generador, para ver si el test los capta. Pero no me ha arrojado ningún error ni tampoco me lo arrojo cuando use el método sorted en una de mis funciones, siendo que de acuerdo a una issue, no debería estar permitido.

Puedo confiar en lo que me retorne ese test??  Podemos tener seguridad de que si ese mismo test no arroja ningun problema, no arriesgamos la nota 1??

Gracias

**Comment by MathiasPrett** [comment]
Solucionado. Estaba ejecutando el test directamente y no por run_public_tests.

De  todas formas cosas prohibidas como el uso de sorted() no las detecto. Como podemos checkear eso si se nos pasó??

**Comment by constanzarojasch** [comment]
Hola! Siempre leer las issues anteriores antes de preguntar! En la issue #405 se responde la duda. Aun así, en el enunciado se indica explicitamente el uso de cosas que están permitidas, se deben guiar por eso también. A la vez, si aun no les queda claro, siempre es mejor revisar las issues ya que se aclaran muchos de estos usos, y si no se encuentra la duda, realizar una y esperar la confirmación del equipo docente (las consultas se resuelven con lo que es señalado en el enunciado: map, filter, reduce, estructuras de compresión y librerías itertools y collection).

**Comment by MathiasPrett** [comment]
@constanzarojasch Toda la razón, mala mía no lo había visto. Gracias igualmente!
