### ISSUE TITLE
Me dejo de funcionar VS CODE/python

### ISSUE THREAD

**Issue by SamWeinstein** [IIC2233/syllabus#42]
Hola, me dejo de funcionar VS code, el problema empezó una vez que cometí un error y me salió el error correspondiente en el terminal, pero al arreglar el error, me seguía saliendo el mismo error, aunque borrara el código me seguía dando el mismo error en la misma linea (donde no había código), luego esto dejo de suceder pero me empezó a salir el mismo output (del cual adjunto una imagen (print("hola")) ) en todos mis archivos. Le pedí ayuda a un amigo que ya curso este ramo y probamos muchas cosas por mas de 2 horas y el problema persiste. No he podido avanzar nada en mi tarea desde ese entonces. Ya probé guardando los archivos en distintos lugares y también intente correr el código desde distintos lugares en la terminal. AYUDA POR FAVOOOOR 
![Screen Shot 2019-08-15 at 1 34 02 AM](https://user-images.githubusercontent.com/53912919/63075084-5b0c1580-befe-11e9-9930-00b1b57f08cf.png)

**Comment by SamWeinstein** [comment]
Ya probé desinstalando e instalando denuevo la extension de python y también intente correr el código en pycharm y el problema persiste, el output no es siempre exactamente el mismo, pero siempre similar y de la misma forma.

**Comment by jmwielandt** [comment]
Hola!

Te puedo pedir más detalles al respecto? Me parece extraño que el error persista al cambiar de editor, eso parece más un error en el código 🤔 

Saludos~

**Comment by SamWeinstein** [comment]
Ya lo solucione, era porque el archivo .py se estaba guardando en 2 lugares distintos y eso generaba problemas. Gracias!
