### ISSUE TITLE
Duda sobre formato Datetime

### ISSUE THREAD

**Issue by SVenegasA** [IIC2233/Syllabus#42]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Saludos, 
Quisiera saber cómo hacer para que esta línea de código (datetime.datetime.now()) Me retorne la fecha y la hora en el formato que está en reclamos.csv (Este: 2022/03/10 18:04:26)

Además, necesito saber si hay restricción para esta tarea con la cantidad de líneas de código (Más bien, si hay descuentos por programas con muchas líneas)
Gracias

**Comment by Emiliax16** [comment]
Hola @SVenegasA . Para tener el formato que buscas podrías hacerlo de varias maneras, desde modificarlo manualmente con los contenidos vistos en clases (sobretodo manejo de string y listas) o podrías aprovechar la misma librería datetime, ya que cuenta con funcionalidades para poder tener el formato deseado. Te recomiendo googlear `strftime` y no olvides citar en tu README en caso de extraer código de alguna página.

Respecto a los módulos, esta tarea no descuenta por tener módulos sobre las 400 líneas (a diferencia de las siguientes). Sin embargo, en la distribución de puntaje existe una sección sobre la modularización de tu programa, por lo que si superas esta cantidad de líneas, no tendrás el puntaje completo en este ítem. Saludos!

**Comment by RicciOff** [comment]
Respecto a lo mismo, al añadir una nueva encomienda y ocupar datetime.now() para registrar la hora, me hace return de Y-m-d H:M:S:f, con los microsegundos incluidos. Es necesario eliminar eso no?

**Comment by Emiliax16** [comment]
> Respecto a lo mismo, al añadir una nueva encomienda y ocupar datetime.now() para registrar la hora, me hace return de Y-m-d H:M:S:f, con los microsegundos incluidos. Es necesario eliminar eso no?

Sí. Debe seguir el mismo formato que aparece en los archivos. Al igual que la pregunta anterior, hay varias maneras de eliminar los microsegundos, ya sea manualmente con string/listas o indagando en la librería datetime 😄
