### ISSUE TITLE
Duda acerca de si el usuario debe ingresar coordenadas solo numéricas o alfanuméricas.

### ISSUE THREAD

**Issue by aLotOfGluten** [IIC2233/Syllabus#42]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Cuando el usuario ingresa las coordenadas para descubrir casilla, ¿estaría bien si ambas coordenadas son números? En el print_tablero del modulo tablero el tablero queda descrito como 1, 2, 3, ..., n y A, B, C, D..., pero me parece que sería más simple si el usuario solo ingresara el número de fila y el número de columna.

¿Está bien si las coordenadas son ingresadas número/ número?

**Comment by Lord-Kelsier** [comment]
Claro, las tareas son bastante libres y por lo mismo, cualquier cosa que consideres no intuitiva para el ayudante que corrija anótalo en el *README*. Como regla general, si en el enunciado no se especifica como debe hacerse (o que no debe hacerse) entonces eres libre de hacerlo como te parezca correcto. 

Si te fijas, estas son las instrucciones de los menus:
![image](https://user-images.githubusercontent.com/69614275/185769519-70637f1e-0598-4152-8756-f21b6f7a5ce5.png)
