### ISSUE TITLE
consola y tkinter

### ISSUE THREAD

**Issue by Bipavez** [IIC2233/Syllabus#42]
En referencia a la respuesta dada por @FernandoPieressa en el issue #21, me gustaría saber si se puede usar la ventana de tkinter para llamar a la consola (por ej, si tengo que recibir un input llamar a la consola; pero si quiero volver atrás puedo apretar un botón en la ventana(de tkinter)) o toda funcionalidad debe estar expresada en la consola.
Pregunto porque al pedirnos el uso de la consola, y el manejo de input robusto puede referirse solo al manejo de errores de input.
Gracias

**Comment by Hernan4444** [comment]
@Bipavez lamento la tardanza. Para esta tarea ** toda funcionalidad debe estar expresada en la consola.** Si quieres utilizar tkinter, primero necesitamos que tengas todo lo de consola implementado y luego, si quieres, implementar tkinter.
