### ISSUE TITLE
Duda sobre funcion cambiar_planos

### ISSUE THREAD

**Issue by AlanGoldsmith25** [IIC2233/Syllabus#42]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Mi duda es que al momento de ejecutar los tests de esta funcion, solo me funcion los que deberian dar false y los que deberian dar true me entregan false, sin embargo, si copio un test en mi archivo red.py me funciona bien y me sale true.

**¿A que se podria deber dicho error al momento de ejecturar los tests?**

**Comment by CrisHD935** [comment]
Hola! A que te refieres con copiar el test en red.py? A ingresarlo como un input? A parte de esto ejecutaste el test directo dentro de la carpeta de tests o desde todos_test.py? Dado que puede haber un error de modulación.

**Comment by AlanGoldsmith25** [comment]
que por ejemplo, agarro el test_2 dentro del archivo test_09 y lo copio en el red.py y al ejecturalo me entrega True, pero al ejecutar el archivo test_09 ese mismo test me entrega false. 

El test lo ejecute dentro de la carpeta de tests, no entiendo muy bien como ejecutar un test en especifico desde todos_test.py

**Comment by Hernan4444** [comment]
Hola @AlanGoldsmith25 

Hay un ligero problema con el archivo test_09 que estamos solucionando.

Lo que se refiere el ayudante, es que vayas al archivo `todos_tests.py` y comentes las líneas de los tests que no quieres probar. Algo como lo siguiente

```python
import unittest
# from tests_publicos.test_00_informacion_red import TestInformacionRed
# from tests_publicos.test_01_agregar_tunel import TestAgregarTunel
# from tests_publicos.test_02_tapar_tunel import TestTaparTunel
# from tests_publicos.test_03_invertir_tunel import TestInvertirTunel
# from tests_publicos.test_04_nivel_conexiones import TestNivelConexiones
# from tests_publicos.test_05_rutas_posibles import TestRutasPosibles
# from tests_publicos.test_06_ciclo_mas_corto import TestCicloMasCorto
# from tests_publicos.test_07_estaciones_intermedias import TestEstacionesIntermedias
# from tests_publicos.test_08_estaciones_intermedias_avanzado import TestEstacionesIntermediasAvanzado
from tests_publicos.test_09_cambiar_planos import TestCambiarPlanos
# from tests_publicos.test_10_asegurar_ruta import TestAsegurarRuta

if __name__ == "__main__":
	unittest.main(verbosity=2)

```

De este modo, el archivo `todos_tests.py` solo ejecutará los tests del archivo 9. Y si ahí te funciona, entonces está todo bien con tu código 👍 

Respecto al error que mencioné antes, lo que ocurre es un problema de _paths_ y desde donde estamos ejecutando. En el siguiente comentario explicaré el error y pondré como solucionar este problema.

**Comment by Hernan4444** [comment]
## Explicación problema  `test_09_cambiar_planos.py`

Actualmente, para ejecutar 1 archivo de _test_, lo que hacemos es:

1. Posicionar nuestra terminar dentro del directorio "tests_publicos"
2. Hacer `python3 test_09_cambiar_planos.py`. 

Cuando hacemos esto, el código del _test_ hace `from red import RedMetro` y con eso obtenemos la clase `RedMetro` que cada estudiante está completando. 

El problema surge que cuando el código, dentro de red.py, hace algo como `open(os.path.join("data", "holi.txt"))`. Ante ese código, lo esperado es acceder al directorio "data" que está en la T1 y buscar el archivo `"holi.txt"`... 

**No obstante** 😱 , como nuestra terminal **estaba posicionada dentro de "tests_publicos"**, el código de `red.py` se pondrá a buscar  el directorio "data" **dentro** del directorio "tests_publicos" y ahí surge un error.... porque no existe "data" dentro de "tests_publicos". 

Todo esto se traduce en un problema de profundidad porque nuestra terminal está dentro de "tests_publicos" y el directorio "data" está al mismo nivel de "tests_publicos".

## Solución a este problema 🎉 

Actualmente hay varias soluciones, aquí pondré 2 que son más fáciles:

1. Una forma es la comentada anteriormente: Ejecutar `todos_tests.py`.

Para ejecutar este archivo, nuestra terminal estará a la misma altura que `red.py` y `data`, y no dentro de "tests_publicos". Así que no habrá problemas con las rutas. Y si ese archivo indica que está todo bien, entones no hay nada que preocuparse 😄.

2. La otra opción es **copiar el directorio "data" dentro de "tests_publicos"** quedando así la organización de archivos:

![image](https://github.com/IIC2233/Syllabus/assets/15641721/b27ac6ba-8b4d-4cb4-983f-00f41a21e943)

Notar que el directorio "data" está 2 veces: en el directorio T1 junto a los archivos `red.py`, `ejemplo.py`, etc. Y tambien dentro de "tests_publicos". 

Con esto, podemos seguir haciendo `python3 test_09_cambiar_planos.py` dentro del directorio "data" sin problema.

---
Ambas opciones son válidas y no está demás indicar que nosotros nos aseguraremos de que, al momento de revisar, no ocurra este problema con las rutas 👍 .

Saludosヾ(＾-＾)ノ

**Comment by Hernan4444** [comment]
Hola, se actualizó al Syllabus para abordar el problema mencionado en esta issue, y en la issue #44. Que corresponden a las 2 issues marcadas como **Importante** hasta el momento.

En particular, se copió el directorio `data` dentro de `tests_publicos`.

Saludosヾ(＾-＾)ノ
