### ISSUE TITLE
Problema pyqt5

### ISSUE THREAD

**Issue by Fercho19** [IIC2233/syllabus#42]
Hola, al instalar el pyqt5 me sale lo siguiente: 
![pyqt5](https://user-images.githubusercontent.com/69866585/90545942-67513100-e157-11ea-9cef-6283ae5404fa.jpg)

**Comment by tocococa** [comment]
Hola @Fercho19 ! 

Lo que ves ahí significa que ya tienes instalado PyQt5, y la segunda parte en amarillo te avisa que hay una actualización disponible para pip. Si quieres puedes correr el comando que te sugiere ahí, pero no es crítico para el ramo.

**Comment by Fercho19** [comment]
> Hola @Fercho19 !
> 
> Lo que ves ahí significa que ya tienes instalado PyQt5, y la segunda parte en amarillo te avisa que hay una actualización disponible para pip. Si quieres puedes correr el comando que te sugiere ahí, pero no es crítico para el ramo.

Muchas gracias!
