### ISSUE TITLE
Kernel have died

### ISSUE THREAD

**Issue by kai-yamamoto1** [IIC2233/Syllabus#42]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

En el ejercicio propuesto 1 de properties intenté correr mi código y me apareció el siguiente mensaje en el notebook. Intenté reinicar el kernel, cerrar y volver a abrir jupyter notebook, y también reiniciar el PC. Otras celdas en el notebook corren bien, ¿será un problema del código? Adjunto imagen del mensaje.
Saludos!

![image](https://github.com/IIC2233/Syllabus/assets/128411642/4d2cb631-541f-41cd-9251-ca426c48c5f0)

**Comment by Dvckhv** [comment]
Hola @kai-yamamoto1 ! Viendo tu codigo, tienes un error en el setter y getter.

El getter deberia retornar un valor y el setter debe asignarlo, usualmente usas un atributo privado para eso o simplemente puedes calcularlo en el getter cada vez que se pregunta (en este caso asumiendo una fecha actual).

En tu caso, el getter se esta retornando a si mismo y el setter no esta haciendo nada en particular por que nunca se  llama ( para llamarlo deberias hacer algo como , `self.depreciacion_acumulada+=2023`.

En resumen, se soluciona moviendo lo que tienes asignado en el return del setter a el return del getter y asumir una fecha jeje.

Cuentame si se entendió el porque fallaba :)

**Comment by kai-yamamoto1** [comment]
Si muchas gracias
