### ISSUE TITLE
import csv

### ISSUE THREAD

**Issue by RicardoFDQ** [IIC2233/syllabus#42]
Hola, se puede usar la librería csv? o debo hacerlo solo como textos.

**Comment by KnowYourselves** [comment]
Hola @RicardoFDQ!

Para todas las tareas hay una issue especifica donde saldrán todas las librerías permitidas y prohibidas donde podrás hacer este tipo de preguntas. En este caso es la issue #4.

Éxito!

**Comment by RicardoFDQ** [comment]
Gracias
