### ISSUE TITLE
AF1. No apareció la Issue que dice qué commit revisaran. 

### ISSUE THREAD

**Issue by migonazo** [IIC2233/syllabus#42]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Como dice el título, no recibí la issue en mi repo personal que dice cuál commit me revisarán.

Hice mi último commit antes de las 4:30 como decía el enunciado.

Supongo que la embarré en algún lado 😞 , perdón.
Qué tengo que hacer?

**Comment by lily416** [comment]
Hola @migonazo,
 
Aparentemente hubo un problema al momento de crearse las _issues_ con el _commit_ a revisar. En este momento estoy trabajando para identificar a los alumnos con este problema y así hacerles llegar la información del _commit_ a corregir. Te pido que dentro de lo posible sea paciente c:
 
Saludos y que tengas una linda tarde 👋
