### ISSUE TITLE
Orden de asignación de daño a las personas

### ISSUE THREAD

**Issue by mnbenimeli** [IIC2233/syllabus#42]
Hola, 
en la sección 4.1 dice con los soldados "Esto se debe hacer **comenzando por los soldados que poseen menor HP hasta los que se encuentran en mejor estado.**", y luego reafirma con los aldeanos "donde se debe
utilizar la misma mec´anica de los soldados, **comenzando por los que est´an m´as debilitados**"

Mi pregunta es, el orden se dicta por [hp neto] o [porcentual y luego neto]?
Sean los trabajadores A, B, C y D, con hp 5/5, 2/11, 5/10 y 7/9 respectivamente. Cuál sería el orden?

**Comment by jeschuwirth** [comment]
Saludos!
Para el cálculo de daño a las personas se utiliza la vida que posee la unidad actualmente, **no** la percentual, por esta razón el orden de los trabajadores sería:

B con 2/11, A o C con 5/5, 5/10 (ya que ambos poseen 5) y por último D con 7/9

El orden de A o C queda a criterio del alumno.

Ojalá te haya contestado bien la pregunta y suerte en la tarea :D

**Comment by mnbenimeli** [comment]
Muchas gracias, con eso quedé perfecto
