### ISSUE TITLE
ReadMe tarea 0, se puede modificar en github y entregar ese para la tarea 0?

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#42]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola,
me gustaría saber si puedo copiar y pegar el readme de guía en mi repositorio privado, editarlo y entregar ese. De poderse, ¿como lo copio y lo pego?

**Comment by catalina-arcila** [comment]
Hola @Fernanda1232123 Es totalmente recomendable que uses el formato de README que se encuentra en la carpeta de la tarea del syllabus. Este lo puedes copiar y pegar en tu carpeta de la tarea en tu repo personal (su Ctrl+C Ctrl+V; también lo puedes mover a lo maldi en tu _Explorador de archivos_). Posteriormente para añadirlo debes hacer el git add, commit y push :).
Recuerda no incluirlo en el _.gitignore_!!
