### ISSUE TITLE
Uso de caracteres especiales

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#42]
La base de dato viene con caracteres codificados en utf-8; si bien empleo el argumento encoding en la funcion open, al printear la base de datos estos aparecen no codificados y no puedo trabajar con dichos Strings. Alguna forma rapida de solucionar este problema 😔

**Comment by rpalmaotero** [comment]
Sólo para confirmar: hiciste `open(..., encoding="utf8")`?

**Comment by akaminetzkyp** [comment]
Hola!

Estoy medio perdido con el tema de los caracteres especiales. He abierto los archivos de la manera común y python no me ha lanzado ningún error. Será que en mi computador está funcionando bien pero quizás en otro se va a caer? Debería poner el `open(..., encoding="utf8")`?

Gracias!

**Comment by benjamimo1** [comment]
Lo solucione ejecutandolo en otro editor de texto!`open(..., encoding="utf8")` me tiró error hasta que lo ejecuté directo en IDLE
