### ISSUE TITLE
Problema instalación Qt Designer

### ISSUE THREAD

**Issue by ctoro05** [IIC2233/syllabus#420]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Muy buenas tardes, tras intentar de instalar Qt Desinger no he conseguido encontrarlo en mi computador, incluso he seguido la ruta del archivo sin poder dar exitosamente con designer.exe.  Según la consola tengo todo correctamente instalado así que me pregunto si existe una alternativa para la instalación de este.

Muchas gracias.

**Comment by aaossa** [comment]
Hola @ctoro05 , después de haber instalado `pyqt5-tools`, al menos en mi computador `designer.exe` se encuentra en la carpeta de Python, en la siguiente ruta: `Python37/Lib/site-packages/qt5_applications/Qt/bin/designer.exe`. ¿Podrías confirmarme si te aparece ahí? Ojalá aparezca 🙌

**Comment by ctoro05** [comment]
Gracias profesor! Efectivamente ahora si pude encontrarlo.
