### ISSUE TITLE
Empate en resultados.txt

### ISSUE THREAD

**Issue by barbarafcp** [IIC2233/syllabus#420]
holiii, tengo la duda de que guardar en el caso de que en una competencia haya un empate, porque me piden la delegación ganadora y el deportista ganador, pero si las delegaciones empatan entonces no guardo en el archivo delegación ni deportista o que?

**Comment by vicentevegaulloa** [comment]
Hola @barbarafcp !

Esto no aparece explicito en el enunciado, por lo que quedaría a tu criterio. Personalmente pondría un guión en delegacion ganadora y deportista ganador, o quizas "empate".

**Comment by barbarafcp** [comment]
aaaah buena, muchas gracias!^^

**Comment by vicentevegaulloa** [comment]
De nada! 😄
