### ISSUE TITLE
README y Función que no termina de correr

### ISSUE THREAD

**Issue by antoriffoc** [IIC2233/Syllabus#420]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, tengo dos preguntas:

1. En el enunciado se especifica que el README no será revisado por el cuerpo docente, pero que debe incluir las referencias que usamos. Si no tengo referencias lo entrego vacío??

2. Tengo una función que pasa todos los tests case cuando son pocos datos (desde el test 0 al 5), pero cuando llega a las bases de datos grandes s, m o l (test 6 al 8) la terminal carga indefinidamente. Al momento de corregir mi tarea, si la terminal se queda pegada cargando va a perjudicar a aquellos test que vengan después? o se va a parar esta función y continuará con las siguientes?

Muchas gracias

**Comment by mpiavf** [comment]
Hola !
Aunque el readme no será revisado manualmente, su propósito es que al identificar posibles casos de copia, nos permite verificar de dónde se referenciaron los contenidos. Si no utilizaste referencias para la tarea, no es necesario completarlo.

Tal como dice el enunciado, si cada test no corre durante un tiempo acotado de 20 segundos se asumirá el resultado incorrecto, por lo que te recomiendo modificar el código para que corra mas rápido. Cosas que hacen que se demore el correr un test puede ser la existencia de varios bucles for en la tarea.

Agregando a lo anterior, hay dos tipos de test: los de correctitud y los de eficiencia.  Los de correctitud son los que no usan .csv y los de eficiencia son los que cargan .csv, ambos tipos de test no pueden superar los 20 segundos. Sin embargo, cada test es independiente, por ejemplo si un test se demora más de 20 segundos y los demás se demoran menos de este tiempo, solo el test que tomó más tiempo será considerado incorrecto. En este sentido, si un test está incorrecto, los demás igual se revisan, no perjudican a los test que vengan después como mencionas.

Espero haberme explicado bien
Saludos!
