### ISSUE TITLE
Formato "comando error"

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#420]
Hola!

Cuando levantamos un error en RQL debemos especificar qué tipo de error fue levantado y qué comando lo causó. Supongamos que ejecuto la siguiente consulta:
```
["graficar", ["do_if", ["extraer_columna", "archivo", "columna"], ["comparar", 1, ">", 2], ["PROM", [1, 2, 3]]], "numerico]
```
En este caso se levantaría un error de tipo, ya que `graficar` recibiría como primer argumento un número, cuando debería recibir una columna. El resultado sería el siguiente:
```
Error de consulta: graficar("do_if"*, numerico)
Causa: Error de tipo
```
Al leer un mensaje así no queda claro qué fue lo que causó el error. Sin embargo, siento que imprimiendo un mensaje de la forma mostrada a continuación quedaría clarísimo.
```
Error de consulta: graficar(2, numerico)
Causa: Error de tipo
```
De esta manera, se comprendería inmediatamente que el error en la consulta está siendo causado por el primer argumento, donde hay un número en vez de una columna.

Para que el usuario pueda saber la fuente del error, ¿podría imprimir el resultado con el segundo formato? Todo sería explicado en el Readme, junto a las razones correspondientes.

Muchas gracias!

**Comment by DiegoAndai** [comment]
Hola! Sí, pueden modificar el formato de los mensajes de error, pero es muy importante que se evidencie en este:

-La causa del error, o sea, que comando la provocó
-El tipo del error

Si se muestran esas dos cosas claras, estará bien. También puedes evaluar la consulta como propones, poniendo `2` en vez de `"do_if"*`. Recuerda que todo cambio tiene que ir especificado en el README.

Saludos.

**Comment by akaminetzkyp** [comment]
Muchas gracias! :)
