### ISSUE TITLE
Mostrar un QWidget como 'child' de otra Ventana

### ISSUE THREAD

**Issue by cristozille** [IIC2233/syllabus#420]
Hola, tengo el mapa  y el inventario de la forma:
class Mapa(Qwidget)
class Inventario(QWidget)
En donde se le agregan QLabels con sus respectivos elementos. Ahora quiero generar una ventana en donde me muestre el mapa y el inventario. Intente de la forma:
class Ventana(QWidget)
    hbox = QHBoxLayout()
    hbox.addWidget(mapa)
    hbox.addWidget(inventario) 
    self.setLayout(hbox)
    self.show()
Pero no me muestra ninguna de los QWidgets(). Existe otra forma de poder tarta el mapa y el inventario como un 'child' QWidget para poder abrirlos en una ventana secundaria de esta forma?
Gracias!

**Comment by dgzmr** [comment]
A lo mejor te faltó ponerle a los widgets ventana e inventario parent=Ventana

**Comment by cristozille** [comment]
Hola, se lo agregué pero ahora me muestra una ventana vacía. Como puedo hacer que incluya los respectivos QLabels?
(Estos QLabels los agregue inicialmente como tile = QLabel(self) al mapa)

**Comment by moquezada** [comment]
Yo tengo el mismo problema. Al agregar una instancia de Mapa que hereda de QWidget a un Layout de la ventana principal no me muestra los QLabels que pertenecen al mapa. Esto no ocurre si solamente lo coloco dentro de la ventana principal sin un Layout. Cómo se puede solucionar esto?

**Comment by Alonsortega** [comment]
Si entiendo bien la pregunta, eso se puede hacer definiendo el _parent_ del widget. Por ejemplo, si tienen un _widget_ que se llama "ventana" que es del tipo "QtWidget" y quieren poner otro dentro, por ejemplo un widget tipo "QLabel" que se llama "label", hay que poner

label.setParent(ventana)

Si hacen show( ) de ventana, el label aparece automáticamente. Ojo que también el sistema coordenado de "label" va a ser respecto a la posición de "ventana".

**Comment by Alonsortega** [comment]
En tu caso, a las instancias de Mapa y Inventario, debes hacerle setParent con la instancia de Ventana

**Comment by moquezada** [comment]
@Alonsortega Si había realizado previamente eso. Lo que solucionó mi problema fue utilizar el método `QWidget.setMinimumSize(ancho, largo)` en el caso de mi instancia de Mapa que hereda de QWidget. Una vez aplicado el método, al instanciar el mapa en la ventana principal se desplegaba sin problemas. 

Muchas gracias de todas formas!

**Comment by cristozille** [comment]
Muchas Gracias!!
