### ISSUE TITLE
Librerías permitidas y no permitidas T3

### ISSUE THREAD

**Issue by catalinaortegacalderon** [IIC2233/Syllabus#420]
Para consultar sobre una librería deben responder esta _issue_ con una pregunta de la siguiente forma:  
> ¿Puedo usar la librería `nombre_librería` para hacer `explicación_de_lo_que_quiero_hacer`?  
 
¡Recuerden especificar en su README qué librerías utilizan!  

---  

## ✅ **Librerías Permitidas**
- functools
- itertools 
- collections  
- typing 
- string 
- os.path
- math.ceil
 
## ❌ Librerías Prohibidas 
- csv 
- pandas 
- numpy 
- JSON 
- pickle 
- threading 
- re 
- glob 
- time 
- copy
- pathlib
- more-itertools
- sys.module

## ☠️ _Built-ins_ Prohibidos 
El uso de alguna de las siguiente funciones es automáticamente un 1,0 sin discusión: 😭
- exec ([explicación](https://github.com/IIC2233/syllabus-2020-1/issues/591#issuecomment-616773839))
- eval ([explicación](https://github.com/IIC2233/syllabus-2020-1/issues/591#issuecomment-616773839))

## ⚠️ Malas prácticas
El uso de las siguientes prácticas será considerado una mala práctica:
-  `except Exception:` o únicamente ` except:` (excepciones bien capturadas sí estarán permitidas).
- Variables globales de cualquier tipo.
- `Import *` o _imports_ que no se encuentren al inicio del programa.
- No añadir _encoding_ al momento de trabajar archivos.
  

 ¡Éxito en sus tareas!

**Comment by xperseosses** [comment]
Hola, se que está permitida la librería itertools, pero ¿ Están permitidas todas las funciones que trae, por ejemplo  la función cycle() ?

**Comment by FiuProgra** [comment]
Hola! Quería preguntar si es que se puede usar la librería ([`copy`](https://docs.python.org/3/library/copy.html). Muchas gracias!

**Comment by catalinaortegacalderon** [comment]
> Hola, se que está permitida la librería itertools, pero ¿ Están permitidas todas las funciones que trae, por ejemplo la función cycle() ?

Hola! Si, todas las de itertools

**Comment by catalinaortegacalderon** [comment]
``

> Hola! Quería preguntar si es que se puede usar la librería [`copy`](https://docs.python.org/3/library/copy.html). Muchas gracias!

hola! recuerda especificar para qué la utilizaras por favor :) para poder evaluarlo

**Comment by FiuProgra** [comment]
> ``
> 
> > Hola! Quería preguntar si es que se puede usar la librería [`copy`](https://docs.python.org/3/library/copy.html). Muchas gracias!
> 
> hola! recuerda especificar para qué la utilizaras por favor :) para poder evaluarlo

Para poder copiar el generador en la función `pedido_con_mayor_descuento_utilizado()`.

**Comment by catalinaortegacalderon** [comment]
> > > Hola! Quería preguntar si es que se puede usar la librería [`copy`](https://docs.python.org/3/library/copy.html). Muchas gracias!
> > 
> > 
> > hola! recuerda especificar para qué la utilizaras por favor :) para poder evaluarlo
> 
> @catalinaortegacalderon Para poder copiar el generador en la función `pedido_con_mayor_descuento_utilizado()`.

No está autorizado. Te invito a buscar maneras alternativas de copiar el generador. Mucho éxito en tu tarea :)

**Comment by GasparSalas** [comment]
Hola. Esta permitido importar utilidades en consultas?

**Comment by undieguito** [comment]
Hola. ¿Está permitido utilizar la librería os para hacer paths relativos?
Saludos.

**Comment by catalinaortegacalderon** [comment]
> Hola. Esta permitido importar utilidades en consultas?

si!

**Comment by catalinaortegacalderon** [comment]
> Hola. ¿Está permitido utilizar la librería os para hacer paths relativos? Saludos.

Hola! Si.

**Comment by NicolasPhilippi** [comment]
Hola, ¿Se puede usar .issubset()? Seria para filtrar si un set es subconjunto de otro.

**Comment by catalinaortegacalderon** [comment]
> Hola, ¿Se puede usar .issubset()? Seria para filtrar si un set es subconjunto de otro.

Hola! Sí se puede. Es un método "built in" de python. Todos los métodos "built in" estan autorizados a excepción de "exec" y "eval".

**Comment by Yeps3nM** [comment]
Hola! se puede usar cambio de estructuras directamente, sin que sean por comprensión? como list() o dict()?

**Comment by mxmauoc0** [comment]
Hola Buenas, se que esta permitida la libreria itertools, solo para quedarme con más seguridad , esta permitida la función itertools.tee() ?

**Comment by catalinaortegacalderon** [comment]
> Hola Buenas, se que esta permitida la libreria itertools, solo para quedarme con más seguridad , esta permitida la función itertools.tee() ?

Hola! sí, está permitida

**Comment by NikowskyUC** [comment]
Hola! Se puede usar la librería` pathlib`? Para usar la clase `Path` al abrir archivos. 

Ejemplo: `file = open(Path("data/archivo.txt"))`

**Comment by vicenciomf2** [comment]
Hola! Muy buenas noches, ¿es posible usar `math.ceil()`? Por ejemplo, si de alguna forma tengo 1, 2, 3, 4, 1, 2, Eso lo calculo redondeando, por ejemplo, 5.3 hacia un 6 (obtener los primeros 6) , y para eso, para redondear por exceso busqué que se puede usar `ceil` de la biblioteca `math`

Muchas gracias de antemano:)

**Comment by catalinaortegacalderon** [comment]
> Hola! Se puede usar la librería` pathlib`? Para usar la clase `Path` al abrir archivos.
> 
> Ejemplo: `file = open(Path("data/archivo.txt"))`

Hola! no esta autorizado, puedes asumir que las rutas entregadas serán entregadas de manera correcta. Sino, puedes usar os.path

**Comment by catalinaortegacalderon** [comment]
> Hola! Muy buenas noches, ¿es posible usar `math.ceil()`? Por ejemplo, si de alguna forma tengo 1, 2, 3, 4, 1, 2, Eso lo calculo redondeando, por ejemplo, 5.3 hacia un 6 (obtener los primeros 6) , y para eso, para redondear por exceso busqué que se puede usar `ceil` de la biblioteca `math`
> 
> Muchas gracias de antemano:)

hola! ok, autorizado. Solo ten cuidado al utilizarlo en los tests, procura que el tiempo que se demora en correr el test no sea tan alto.

**Comment by tnar01** [comment]
Hola, esta permitido usar la funcion peek() de more-itertools

**Comment by Trinihi** [comment]
Hola! se puede usar  "datetime". Gracias

**Comment by nsvega** [comment]
Hola! quería saber si esta permitido utilizar  issubset() y startswith()

**Comment by catalinaortegacalderon** [comment]
> Hola, esta permitido usar la funcion peek() de more-itertools?

hola! recuerda especificar para que quieres utilizarla por favor :)

**Comment by catalinaortegacalderon** [comment]
> Hola! quería saber si esta permitido utilizar issubset() y startswith()

hola! si, son métodos "built in" no prohibidos.

**Comment by catalinaortegacalderon** [comment]
> Hola! se puede usar "datetime". Gracias

hola! recuerda especificar para qué quieres utilizarla.

**Comment by aleret4** [comment]
Hola! quería saber si se puede utilizar la librería sys, específicamente la función modules de esa librería? Gracias

**Comment by tnar01** [comment]
Hola! es posible utilizar mean() de statistics para calcular el promedio de los descuentos por pais?
