### ISSUE TITLE
Base destruida

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#420]
Hola, cuando la vida de la base llega a 0, puedo decir que el juego termina, una vez termina también la ronda?

**Comment by lily416** [comment]
En el enunciado sale:
![image](https://user-images.githubusercontent.com/26393515/58420950-b1368e80-805c-11e9-9141-46f8aa83bc28.png)
Por lo que cuando se destruye la base se termina la partida, no la ronda.

Saludos y éxito con la tarea. 👋 🐈🐧
