### ISSUE TITLE
Metaclases: argumentos que recibe __new__

### ISSUE THREAD

**Issue by fabarros** [IIC2233/Syllabus#420]
Hola, alguien podría por favor explicar qué son estas cosas?:
`meta`, `name`, `bases`, `clsdic`
Entiendo que son los parámetros que recibe el método `__new__` pero, son siempre los mismos? son siempre en ese orden? qué es el diccionario? qué es `bases`? etc.

**Comment by fringlesinthestreet** [comment]
Hola @fabarros 

El método `__new__` de una metaclase **siempre** recibe esos cuatro argumentos. Debes recordar que en el momento en que se llama a `__new__` la clase todavía no se crea ("La instancia de la metaclase todavía no es creada"). Estos argumentos representan:

- `meta`: es la Metaclase.
- `name`: es el nombre de la clase a crear. Cuando ésta es creada, se puede obtener con la sentencia `Clase.__name__`.
- `bases`: es una tupla con los padres de la clase a crear, en el orden que se le pasaron. Cuando la clase ya es creada, uno puede acceder a las bases con la sentencia `Clase.__bases__`.
- `clsdic`: es un diccionario con los métodos y atributos de la clase. **Ojo**: que son atributos de clase. (Además, trae ciertos atributos internos de python como el `__module__` y el `__qualname__` pero no te preocupes por esos).  Cuando la clase ya es creada, uno puede acceder a las bases con la sentencia `Clase.__dict__`.

A continuación mostraré un ejemplo, en donde se tendremos una metaclase ``MetaEjemplo` con sólo el método `__new__` sobreescrito (es decir, el método `__init__` y `__call__` usados van a ser los de `type` o "normales") y vamos a tener una clase `ClaseEjemplo` que hereda de las clases `A` y `B` y que tiene por metaclase a `MetaEjemplo`. Además, la clase `ClaseEjemplo` se define con un método llamado `método` y un atributo de clase llamado `atributo_clase`.

```
class MetaEjemplo(type):
        def __new__(meta, name, bases, clsdic):

        print('Metaclase utilizada: {}'.format(meta))
        print('Nombre Clase a crear: {}'.format(name))
        print('Clases Padres: {}'.format(bases))
        print('Diccionario con los atributos y métodos: {}'.format(clsdic))

        clase_a_crear = super().__new__(meta, name, bases, clsdic)
        return clase_a_crear


class A: pass

class B: pass

class ClaseEjemplo(A, B, metaclass = MetaEjemplo):

    atributo_clase = 5

    def metodo(self):
        pass

```

Esto imprime:

```
Metaclase utilizada: <class '__main__.MetaEjemplo'>
Nombre Clase a crear: ClaseEjemplo
Clases Padres: (<class '__main__.A'>, <class '__main__.B'>)
Diccionario con los atributos y métodos: {'metodo': <function ClaseEjemplo.metodo at 0x10383bea0>, 'atributo_clase': 5, '__qualname__': 'ClaseEjemplo', '__module__': '__main__'}
```

Como puedes notar en el ejemplo: `meta` es la metaclase, `name` es el nombre de la clase que se está definiendo (y tiene a la metaclase `MetaEjemplo`), `bases` es una tupla con los padres (en el mismo orden) y `clsdic` contiene al método y al atributo de clase.

 Como en el método `__new__` todavía no está creada la clase podemos modificar el nombre, la herencia y los atributos y métodos de la clase a crear.
