### ISSUE TITLE
Modulación circular, al crear widgets 

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#421]
Si creo un creo una clase Clase que herede de QLabel y que tome como atributo un QGridLayout

    grid = QGridLayout()
    label = Clase(grid)

Y luego añado al layout la label:

    grid.addWidget(label)

Sería modelación circular?

**Comment by Hernan4444** [comment]
Hola,

No, porque eso es algo de como está condicionada la librería a ocupar. En ese aspecto no tienen control de como programar eso. Se evalúa que no ocupen modelación circular sobre las clases que ustedes tienen control de editar.

Saludos ✌️
