### ISSUE TITLE
Duda ejercicio propuesto 3.3 Semana 6 acerca de .setText() y event.text()

### ISSUE THREAD

**Issue by FVivess** [IIC2233/syllabus#421]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, 
para este ejercicio implemente un texto que cambia de acuerdo a la tecla que presiona el usuario. Sin embargo, el cambio de texto solo funciona la primera vez que se presiona una tecla, y después se queda en la tecla que apretó el usuario. No entiendo por qué pasa esto.

Código:
```
`import sys
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel, QVBoxLayout)
from PyQt5.QtGui import (QPixmap, QColor)
from PyQt5.QtCore import Qt
import os


class MiVentana(QWidget):
    def __init__(self):
        super().__init__()
        self.inicializa_gui()

    def inicializa_gui(self):
        self.setGeometry(100, 100, 300, 300)
        self.setMaximumHeight(300)
        self.setMaximumWidth(300)

        self.label = QLabel("Blanco", self)
        self.label.setGeometry(100, 100, 100, 100)
        self.imagen = QLabel("", self)
        self.imagen.setGeometry(150, 150, 50, 50)
        self.texto = QLabel("Input: Nada", self)
        self.texto.setGeometry(50, 50, 100, 100)

        path = os.path.join("img", "colors", "verde")
        self.color = QPixmap(path)
        self.color.fill(Qt.white)

        self.imagen.setPixmap(self.color)

        self.show()

    def keyPressEvent(self, event):
        self.texto.setText(f"Input: {event.text()}")
        if event.text() == "v":
            self.texto.setText(f"Input: {event.text()}")
            self.color.fill(Qt.green)
            self.imagen.setPixmap(self.color)
            self.label.setText("Verde")
            self.texto = QLabel(f"{event.key()}", self)
        elif event.text() == "a":
            self.texto.setText(f"Input: {event.text()}")
            self.color.fill(Qt.blue)
            self.imagen.setPixmap(self.color)
            self.label.setText("Azul")
            self.texto = QLabel(f"{event.key()}", self)
        elif event.text() == "r":
            self.texto.setText(f"Input: {event.text()}")
            self.color.fill(Qt.red)
            self.imagen.setPixmap(self.color)
            self.label.setText("Rojo")
            self.texto = QLabel(f"{event.key()}", self)
        elif event.text() == "b":
            self.texto.setText(f"Input: {event.text()}")
            self.color.fill(Qt.white)
            self.imagen.setPixmap(self.color)
            self.label.setText("Blanco")
            self.texto = QLabel(f"{event.key()}", self)


if __name__ == '__main__':
    app = QApplication([])
    ex = MiVentana()
    sys.exit(app.exec_())
`
```

Ventana original:
![imagen](https://user-images.githubusercontent.com/80867403/116796436-eca12980-aacb-11eb-883d-ed3b2e754581.png)

Cuando el usuario apreta a:
![dudaprogra](https://user-images.githubusercontent.com/80867403/116796280-cd55cc80-aaca-11eb-98cc-a37a6b68d1af.png)

Cuando el usuario apreta v, después de apretar a:
![imagen](https://user-images.githubusercontent.com/80867403/116796428-da26f000-aacb-11eb-9d91-c9d36dec2683.png)

**Comment by tqmbanados** [comment]
Hola! Si te fijas, al final de cada condicional en ```keyPressEvent```, vuelves a definir un nuevo QLabel a ```self.texto```. Esto sobrescribiría el QLabel que habías definido antes, con un QLabel nuevo que no tiene dimensiones ni posición, entonces no aparece en pantalla. Entonces, la primera vez que cambias el texto, lo hace al QLabel original en la primera línea del ```keyPressEvent```, y los siguientes cambios van a QLabels creados sucesivamente con cada tecla, que al no tener geometría "no existen". Entonces, lo único que tienes que hacer es borrar las líneas ```self.texto = QLabel(f"{event.key()}", self)``` al final de cada bloque condicional. 

Lo único que no entiendo es por qué no se destruye el primer QLabel una vez dejas de guardarlo en una variable; en general todos los widgets deberías tenerlos siempre guardados en variables.

Espero así solucione tu problema!
