### ISSUE TITLE
Enviar desde frontend a backend

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#421]
Entiendo que en el mayor de los casos lo mejor es utilizar señales pero que pasa si lo que quiero enviar solo se hace al inicio y una sola vez. Por ejemplo al procesar el archivo del mapa en el backend envío una lista con las posiciones de los label al frontend. Si lo hago con señales entonces en el frontend tendría que crear una funcion que solo se dedique a asignarle un nombre a esa lista, ademas ese atributo del frontend `self.lista` sería instanciada fuera del `self.__init__()` lo cual entiendo es una mala práctica. Se me hace mucho mas razonable instanciar el backend en el main y luego pasarle como atributo al frontend `backend.lista`. ¿Como debería hacerlo?

**Comment by StroveLight** [comment]
Hola!
Si bien instanciar la variable ```mi_lista```  fuera del ```__init__()``` es una mala práctica, si se le puede asignar un nuevo valor a la variable fuera del ```__init__()```, pero se deberá instanciar la variable en el ```__init__()```

De esta forma, se puede hacer en el ```__init__()``` un ```self.lista = None``` , y luego en alguna funcion que sí reciba la señal le asignas los valores.

**Comment by dgzmr** [comment]
Vale
