### ISSUE TITLE
Error AtributeError en test_elementos_prohibidos

### ISSUE THREAD

**Issue by Mariana-Julia** [IIC2233/Syllabus#421]
Hola, estoy tratando de ejecutar test_elementos_prohibidos.pyc tal como indicaba el anuncio publicado en canvas, pero me salen estos errores y no se como solucionarlo (estoy usando Python 3.11.6) 
![Captura de pantalla 2024-05-23 173719](https://github.com/IIC2233/Syllabus/assets/163010405/8117b73c-1ba5-4160-ba61-8370b2d2d5fe)

**Comment by Hernan4444** [comment]
Hola @Mariana-Julia 

Puedes pushear tu código porfa, para ver qué está provocando este error

Avisanos cuando esté subido.
Saludos!

**Comment by Mariana-Julia** [comment]
Listo

**Comment by Hernan4444** [comment]
Hola @Mariana-Julia ahora se subió una nueva versión que funcionó con tu código. Había un error que justo tu código logró detectarlo.

Haz pull del syllabus y prueba con el nuevo archivo. Además te recomiendo despues revisar [esta issue](https://github.com/IIC2233/Syllabus/issues/406).

Saludos!

**Comment by Mariana-Julia** [comment]
muchas gracias!
