### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by lefischer** [IIC2233/Syllabus#421]
hola

que se debe testear reapecto a la function evaluar?

**Comment by DiegoAndai** [comment]
@lefischer, Hola!, una forma de testear a la función evaluar es aprovechar un poco de la teoría de probabilidad. Esta dice que la función acumulada de cualquier modelo desde menos infinto a mas infinito debe dar 1. Como no podemos simular algo así en python podemos intentar discretizar esto. 

Supongamos que tenemos una función normal con parámetros 0 y 1. Si esta la evaluamos desde -30 a 30 con intervalo 1, la suma de todos los datos será aproximadamente 1. Si usas un intervalo mas grande como 0.01 = 1/100, la suma te dará 1000 (pero si divides por 100 que es justo el denominador del intervalo) te dará 1. Si hacemos lo mismo con una gamma 3,4 y usamos el rango 0, 50 con intervalo 0.001= 1/1000 el resultado será aproximadamente 1000... si divides por el denominador del intervalo, dará 1. En resumen intenta usar esta propiedad para asegurarte que la suma de todos los datos (en un rango que viven todos los datos del modelo) dé 1.

Saludos.

**Comment by lefischer** [comment]
gracias
