### ISSUE TITLE
Error al importar módulos 

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#421]
Hola.
Tengo un error al querer importar una función llamada ```menu_de_acciones(usuario)``` de un módulo en otro. No entiendo por qué es el error.
Les adjunto lo que importo en ambos módulos y el error.
![imagen1](https://user-images.githubusercontent.com/59337116/79057196-98ab7480-7c2c-11ea-87d9-a2a36518ec38.PNG)
![imagen 2](https://user-images.githubusercontent.com/59337116/79057197-9b0dce80-7c2c-11ea-8ff3-d3e45acbbc63.PNG)
![imagen 3](https://user-images.githubusercontent.com/59337116/79057199-9f39ec00-7c2c-11ea-907a-962fd651c717.PNG)

**Comment by fdoflorenzano** [comment]
Se cerrará esta *issue* ya que se trata del mismo problema tratado en #444.
