### ISSUE TITLE
Entrega Avance Texto de Acompañamiento Diagrama

### ISSUE THREAD

**Issue by diegobustosk** [IIC2233/syllabus#421]
Hola no entiendo bien que texto tengo que entregar. Según yo el diagrama es auto explicativo

**Comment by jitorcas** [comment]
Hola! 

El objetivo del documento que debes adjuntar es explicar de mejor manera la modelación de tu tarea. Esto ayudará a los ayudantes a comprender tu razonamiento y darte un feedback más enriquecedor.
