### ISSUE TITLE
Se perdió código

### ISSUE THREAD

**Issue by Pdesolmi** [IIC2233/syllabus#422]
No sé si es que alguien me podrá ayudar con este problema, pero estoy usando Atom, apagué mi computador con todos los archivos guardados, y mis 3 archivos más importantes aparecieron vacíos y no he podido recuperarlos
Así es como me aparece, he buscado en internet pero no encuentro una solución, voy a empezar denuevo pero si esque alguien sabe como resolverlo feliz de que me ayude, son muchas horas de trabajo perdidas.
![frontend fallo](https://user-images.githubusercontent.com/53836282/66276021-f79ac600-e864-11e9-8e5e-4e14abb9cc81.PNG)

**Comment by jeschuwirth** [comment]
Hola @Pdesolmi,
 
Busqué en google y encontré varios foros de atom de personas con el mismo problema, lamentablemente atom funciona como editor de texto y no guarda automáticamente los cambios ):

Lo comentan un poco en el siguiente [link](https://discuss.atom.io/t/lost-progress/55757)

Te recomiendo las siguientes cosas antes de continuar con tu trabajo:

1. Subir siempre a git! recuerda que puedes hacer cuantos commits tu quieras a tu tarea, es recomendable hacer un commit después de cada día de trabajo. En el caso hipotético de que cambies varias líneas de tu código y que ya no funcione nada, puedes revertir tu código a como estabas un día anterior. Este es uno de los principales usos de git.

2. Si vas a settings y luegos los paquetes que tienes en atom :

![image](https://user-images.githubusercontent.com/37160256/66323916-f4521980-e8fa-11e9-9525-03b45356e289.png)

Puedes encontrar el paquete autosave que viene **desactivado** por defecto en atom, este paquete guarda tu trabajo cada cierto tiempo y cada vez que lo cierras. Para activarlo debes apretar en settings del paquete y seleccionar la opción `Enabled`. 

De este modo puedes evitar pérdida de código al olvidar guardarlo.

Aprovecho esta instancia para recomendarte los paquetes `atom-python-run`y `python-autopep8` 😉

Lo siento si perdiste mucho trabajo, ojalá vuelvas rápido a donde estabas.

Muchas suerte en la tarea !
