### ISSUE TITLE
Problema al hacer git pull

### ISSUE THREAD

**Issue by martin-iturralde** [IIC2233/syllabus#422]
Hola, ahora que subieron de nuevo los archivos .csv para la T01, estaba tratando de hacer git stash, git pull y git stash pop. Sin embargo, sigue sin funcionar. 
Aquí un pantallazo de lo que me dice en consola:
![image](https://user-images.githubusercontent.com/69633813/92526635-34510900-f1fc-11ea-8a96-b432b5519eaa.png)

**Comment by aaossa** [comment]
Hola @martin-iturralde , al parecer lo que ocurre es que tienes cambios que no son consistentes con los realizados en Syllabus. ¿Podrías utilizar `git status` (y colocar el *output* acá) antes de hacer `git pull` para ver cuál podría ser el problema? Gracias ✨

**Comment by martin-iturralde** [comment]
Esto es lo que me dice:
![image](https://user-images.githubusercontent.com/69633813/92599874-314c2c00-f281-11ea-9428-2632c6846ccb.png)

**Comment by aaossa** [comment]
@martin-iturralde al parecer has estado haciendo *commits* dentro del repositorio del Syllabus 🤔 Quizás lo mejor es que lo clones nuevamente, ya que no sé cómo se resolvería el historial de *commits* desde Git en este caso. Otra opción es que lo intentes resolver usando `git merge --abort`, pero no creo que funcione en este caso. ¿Tienes cambios en tu repositorio local que no quieras perder? Lo pregunto para tratar de averiguar si son necesarios esos 7 *commits* que tienes 🤔

**Comment by martin-iturralde** [comment]
Sí, voy a tener que borrarlo el repositorio de syllabus. Lo raro es que nunca le hecho git add, commit y push al del Syllabus. 
Lo que si hago, es copiar los archivos de la tarea a mi repositorio.... No sé si eso afectará de alguna forma?

**Comment by aaossa** [comment]
Hola, eso no debería afectar 🤔 Así que ahora estoy menos seguro de qué podría haber sido, porque lo que indica Git es que tienes *commits* que no están en Syllabus. Tal vez en algún momento tuviste algo así, pero al clonar nuevamente el Syllabus no deberías tener problemas ✨
