### ISSUE TITLE
Error al agregar monedas (Process finished with exit code -1073740791 (0xC0000409))

### ISSUE THREAD

**Issue by mjespinoza** [IIC2233/syllabus#422]
Holaa, acabo de agregar mis monedas al mapa, estas son Qthreads, para crearlas uso Qtimer. El problema es que cuando se emite la señal del Qtimer para generar las monedas, mi ventana de juego se cierra y me aparece Process finished with exit code -1073740791 (0xC0000409), aunque tenga el codigo para ver errores entregados en los contenidos. Por favor si alguien sabe como solucionarlo seria de mucha ayuda. Graciass.

**Comment by Arcoirisky** [comment]
Hola! ¿Por que no miras la issue #309? Pareciera que es la misma situación o:

Saludos~

**Comment by mjespinoza** [comment]
no, me resulta con la solucion de esa issue, ya agregue el self.quit para cuando se saliera del while de la funcion run del qthread.
