### ISSUE TITLE
Duda sobre señales y diseño front-back

### ISSUE THREAD

**Issue by FVivess** [IIC2233/syllabus#422]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

No me queda muy claro las formas de crear una señal o el código que se debe utilizar para crearlo.
En los apuntes de eventos y señales de la semana 6, se define la señal en la clase MiSenal(), para que luego la clase VentanaPresionable() pueda recibirla, y definirla en esa clase como self.senal_escribir, como se ve en el siguiente código:
```python
class MiSenal(QObject):
    """
    Esta clase contiene la señal que permite la comunicación entre
    elementos de la GUI.
    """
    senal = pyqtSignal()


class VentanaPresionable(QWidget):

    def __init__(self, senal_escribir):
        super().__init__()

        self.senal_escribir = senal_escribir 
```

Sin embargo, en los apuntes de diseño front-back, se hace de una manera distinta: la señal se crea en la misma clase que se quiere usar, y además nunca se define como self.senal_actualizar, sino que directamente se conecta al método self.actualizar_resultado.

```python
class Ventana(QWidget):

    senal_actualizar = pyqtSignal(str)

    def __init__(self):
        super().__init__()
        self.inicializa_gui()
        self.senal_actualizar.connect(self.actualizar_resultado)
        self.senal_procesar = None
```

Esperaría que en este último código hubiera una linea `self.senal_actualizar = senal_actualizar` antes de conectarla al método, pero este no es el caso.

**No entiendo por qué la segunda forma de definir la señal funciona, o si una forma es mejor que la otra al momento de querer hacer un programa cohesivo y poco acoplado (como se indica en los diseños front-back).**

**Comment by aaossa** [comment]
Hola @FVivess , buena pregunta 👌 La verdad es que ambas formas son formas correctas de hacer cosas, solo que ambas apuntan a necesidades distintas. Me explico:

1. El primer código simplemente intenta mostrar una situación en la que una señal está en otra clase (que debe ser un `QObject`), tal como cuando separamos entre *front-end* y *back-end*. En este ejemplo está todo bien. La señal está en el *back-end* porque queremos que el *back-end* la pueda emitir y avisarle a quienes se suscriban (en este caso, la clase del *front-end*).
2. El segundo código es una señal que está en el *front-end*, o sea, es una señal que activaremos cuando queramos que este le avise algo a quienes se suscriban (en general, el *back-end*). Primero que todo, no es necesario hacer `self.senal = senal`, porque la señal es un atributo de clase, entonces ya el objeto señal ya es accesible y común para todas las instancias (a no ser que una instancia sobreescriba su propio atributo, pero eso no entra en esta *issue*). Si lo piensas, cuando yo conecto un método propio a una señal mía, es equivalente a que justo después de que se active la señal yo utilice `self.actualizar_resultado`, por lo que podría servirnos para ahorrar código. En todo caso, justo al final de ese material se comenta que podría hacerse otras maneras y que el ejemplo solo busca ilustrar distintas maneras de hacerlo, pero de todas formas...

En general, para mantener el orden, es correcto que la clase que emite una señal sea quien la contenga, y las clases que se suscriban reciban una referencia al inicializarse, tal como se hace en el primer ejemplo. Otro consejo que también es útil es conectar señales y hacer todo lo relacionado con estas en el `main.py`, para tener un solo lugar dónde revisar tu código. Como dice el material, estas son decisiones de diseño y lo más recomendable por sobre todo es tratar de mantener la consistencia (por tu propio beneficio al programar). Espero se entienda, pero si tienes alguna duda adicional, pregunta de nuevo por acá no más 👌 ¡Éxito con tu estudio 🙌 !
