### ISSUE TITLE
Uso de diccionarios en parametros.py

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#422]
Hola! En lugar de guardar parámetros de la manera "tradicional":
parámetro_1 = algo
Se podría usar diccionarios de la forma NOMBRE_DICCIONARIO = {"PARAMETRO_1" : algo,.....}
?

**Comment by furcelay** [comment]
Hola!
No soy ayudante pero hice una pregunta similar (https://github.com/IIC2233/syllabus/issues/349) y me respondieron que incluso era mejor así...

**Comment by mpsubiabre** [comment]
Hola @RonaldoSosa ! 

Efectivamente como menciona tu compañero si puedes utilizarlo y es muy recomendable para ser mas ordenado, mas aun si tienes diccionarios diferentes segun grupos de parametros que tienen un uso en comun :)

Exito en la tarea 😄

**Comment by sbcorrea** [comment]
> Hola @RonaldoSosa !
> 
> Efectivamente como menciona tu compañero si puedes utilizarlo y es muy recomendable para ser mas ordenado, mas aun si tienes diccionarios diferentes segun grupos de parametros que tienen un uso en comun :)
> 
> Exito en la tarea 😄

Hola! Yo hice una mezcla de ambos... ¿es válido el siguiente proceso?
1. Todo ```parametros.py``` está escrito como ```VARIABLE = int```
2. Al final de ```parametros.py``` uso una función built-in para convertir todas las variables en un dict de tipo ```{'VARIABLE': int, 'VARIABLE_2': int, ... 'VARIABLE_N': int}```
3. En lugar de importar todo ```parametros.py``` a los módulos que sea necesario, **importo solo el dict** desde ```parametros.py```
Lo hice solo por comodidad, pero sé que es técnicamente una vuelta más larga. ¿Hay algún problema con eso?

Gracias de antemano :)

**Comment by RonaldoSosa** [comment]
Entendido gracias :)

**Comment by mpsubiabre** [comment]
Hola @sbcorrea ,

No hay ningún problema! defines muy bien los parametros y tu función esta relacionada con el almacenamiento de parámetros 😄

**Comment by sbcorrea** [comment]
Bacan, gracias!
