### ISSUE TITLE
Test_elementos_prohibidos - tuplas dentro de una estructura por compresion por  .items()

### ISSUE THREAD

**Issue by AlanGoldsmith25** [IIC2233/Syllabus#423]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Dentro de la funcion max_locales_distritos estoy generando una tupla por comprension de la manera ((x, y) for x, y in ejemplo.items()), lo cual al probar el test de elementos prohibidos me entrega False, sin embargo en la funcion votos por especie tambien creo un generador de tuplas con esas caracteristicas y me entrega True, habra algun error en el test?

**Comment by Hernan4444** [comment]
Hola @AlanGoldsmith25 

No es un error, es que en "votos por especie" tuvimos que incluir una excepción en el script para permitir ese tipo de situación. Esto fue porque notamos que en el enunciado se solicitada crear dicha estructura dentro del retorno y en esa única consulta no era tan directo crear dicha tupla sin funcional como en las demás.

No obstante, en las demás consultas no es necesario recurrir a hacer (x,y) para lograr el objetivo, con los diferentes comandos de programación funcional se puede lograr el objetivo cumpliendo 100% el disclaimer del enunciado.

_hint_ : recomiendo probar con `(x for x in ejemplo.items())` en vez de `((x, y) for x, y in ejemplo.items()}` 

Saludos!

**Comment by AlanGoldsmith25** [comment]
Ahi si funciono, gracias!
