### ISSUE TITLE
Interpretación resultados tests

### ISSUE THREAD

**Issue by Amath3o** [IIC2233/Syllabus#423]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, estaba haciendo las funciones para cargar los archivos de los archivos csv y al ejecutar el codigo vi un error proveniente de la carpeta timeout function, el cual no era el de tiempo limite asi que no entiendo mucho que podria estar mal (no estoy seguro de que hace la funcion del archivo timeout), probe a usar por mi cuenta las funciones y retornan los datos esperados en los test case
![image](https://github.com/user-attachments/assets/a42d95ca-ec08-400f-b9ff-f006f8ab41c6)

**Comment by lily416** [comment]
Hola @Amath3o 

Espero que estés bien 😄. Solo para tener más contexto, ¿cómo estás ejecutando los archivos de tests?

Quedo atenta 🐢

**Comment by Amath3o** [comment]
Con python3 -m unittest -v -b tests_publicos.test_00_cargar_datos4

![image](https://github.com/user-attachments/assets/91d1c119-afeb-4e9d-80cf-dcfe7a536213)

**Comment by lily416** [comment]
Ok, de momento no estoy 100% segura de qué puede estar causando el error, así que te voy a pedir algunas cosas:
* ¿Podrías subir tu código a tu repositorio personal?
* ¿Podrías sacar un pantallazo completo de lo que te aparece al ejecutar el código? Ojalá que el pantallazo contenga desde la ejecución del comando en la consola hasta el final.

**Comment by Amath3o** [comment]
ya subi el archivo al repositorio
y subo 2 imagenes para abarcar una buena cantidad del codigo, si necesita el resto lo puedo subir 

![image](https://github.com/user-attachments/assets/4e8ee155-31b6-411f-a316-b5e9a1b2b14e)
![image](https://github.com/user-attachments/assets/8374bf2d-6d06-47cc-95a2-1cb502ab04ac)

**Comment by lily416** [comment]
Gracias por subir tu código y fotos de tu consola, fueron de mucha ayuda para entender lo que estaba pasando 😄.

Para explicar con detalle, me centraré en uno de los tests en específico (`TestCargarDatos.test_l_pizzas`), pero esto aplica para cada uno de los casos.

Al ejecutar el siguiente comando:
```bash
python3 -m unittest -v tests_publicos.test_00_cargar_datos.TestCargarDatos.test_l_pizzas
```
 
Se obtiene lo siguiente:
```
test_l_pizzas (tests_publicos.test_00_cargar_datos.TestCargarDatos)

        Verifica que los datos carguen bien con un dataset L de Pizzas.
         ... FAIL

======================================================================
FAIL: test_l_pizzas (tests_publicos.test_00_cargar_datos.TestCargarDatos)

        Verifica que los datos carguen bien con un dataset L de Pizzas.
        
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../T3/tests_publicos/timeout_function.py", line 74, in wrapper
    raise result[0]
  File ".../T3/tests_publicos/timeout_function.py", line 65, in target
    result[0] = func(*args, **kwargs)
  File ".../T3/tests_publicos/test_00_cargar_datos.py", line 71, in test_l_pizzas
    self.assertCountEqual(pizzas_cargadas, pizzas_esperadas)
AssertionError: Element counts were not equal:

Diff is 1399 characters long. Set self.maxDiff to None to see it.

 ----------------------------------------------------------------------
Ran 1 test in 0.027s

FAILED (failures=1)
```

¿Cómo podemos interpretar lo anterior? Revisemos lo que nos indica desde abajo hacia arriba:
* `Diff is 1399 characters long. Set self.maxDiff to None to see it.` nos indica que hay una diferencia entre lo entregado por tu función y lo esperado por el test. Dado que la diferencia es muy grande (más de 1000 caracteres), el código no nos muestra los elementos que se están comparando.  

* Ahora, ¿qué es lo que presenta diferencias? Eso se puede comprobar en las siguientes líneas:
   ```
  File ".../T3/tests_publicos/test_00_cargar_datos.py", line 71, in test_l_pizzas
      self.assertCountEqual(pizzas_cargadas, pizzas_esperadas)
  AssertionError: Element counts were not equal:
  ```
  Con esto surge una nueva duda, ¿qué es lo que comprueba `assertCountEqual`? Según la documentación de `unittest` verifica que dos iterables tienen los mismos elementos la misma cantidad de veces (_Asserts that two iterables have the same elements, the same number of times, without regard to order._).  

  Dado que el programa no nos está mostrando las diferencias que existen entre lo cargado y lo esperado, para comprobar lo que se está comparando, podemos agregar un _print_ en los tests antes de que se haga la comprobación (`self.assertCountEqual(pizzas_cargadas, pizzas_esperadas)`).

* Finalmente, pueden surgir dudas sobre qué tiene que ver `timeout_function` con todo esto 🤔. Internamente `unittest` levanta excepcione cuando un _assert_ no se cumple, por lo que dicha excepción produce una detención del código del tests y nos entrega un _traceback_. Dentro de estos _tracebacks_ aparece `timeout_function`, ya que es una función que se ejecuta sobre cada tests para limitar los tiempos de ejecución, por lo que al producirse una excepción (en este caso la que es generada por los _asserts_) nos mostrará todas las funciones que estaban en ejecución cuando se produjo el error. 

En resumen, los errores que te aparecen no están relacionados al `timeout_function`, sino que se deben a que los resultado entregados no coinciden con los esperados.

Espero que esto aclare tus dudas. Cualquier cosa que no quede clara, no dudes en volver a preguntar.

Saludos 🐢💕

**Comment by Amath3o** [comment]
Graciaas! pude ver que error había en los datos que retornaba mi función y ya lo corregí, ahora funciona bien, y gracias por la explicación tan clara
