### ISSUE TITLE
Duda sobre manejo de imágenes con PyQt5

### ISSUE THREAD

**Issue by cegalleta** [IIC2233/syllabus#423]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Estaba haciendo la actividad evaluada de interfaces gráficas (actividad 10) del semestre 2018-2 de interfaces gráficas y no entiendo muy bien cómo cargar los sprites tal que uno sea el fondo y el otro pueda moverse libremente por sobre la imagen del fondo.

Lo que estaba intentando hacer era hacer en el backend una clase Pacman_proc que hereda de QObject que procesara el input del teclado (overriding de KeyPressEvent) y que emitiera una señal (int int str) al frontend que señalara la posición en x, en y y el str del path del sprite a seleccionar a un método que cargase el QWidget de PacMan con el sprite adecuado en la posición x,y por sobre el fondo. Creo que eso hasta ahí funciona  súper, pero en el frontend, no entiendo como posicionar el sprite correspondiente de PacMan en la posición pedida **sobre** el fondo. Pensaba hacer una clase PacMan que heredara de QWidget que se pudiera agregar a una especie de grid con distintas posiciones, pero no se muy bien dónde incluir el fondo y como hacer que se cargue la imagen de pacman.

Ojalá me pudieran dar una pista de como hacer QWidget de imágenes y sobre cómo posicionarlos en conjunto, uno por sobre el otro :(

Muchas gracias de antemano.

**Comment by Pablok98** [comment]
¡Hola!
Lamentablemente, tendría que ver la implementación completa como para indicar exáctamente que está pasando, pero te puedo dar algunos *tips*:

 - Cualquier objeto también puede heredar de *QLabel*, en ese caso, puedes hacer una *label* que se mueva, que tenga una imagen como *pixmap* .
 - Si estás teniendo problemas con que una imagen está "debajo" de otra, puedes intentar utilizar el comando `.raise()`. 
 - Preocupate de que la *label* que represente tu Pacman (ie, la imagen) tenga como *parent* la ventana de juego, de lo contrario no se va a mostrar.
 - Por último, a veces pasa que cuando agregas imágenes después de que ya mostraste la ventana, estas no se dibujen. Puedes solucionar esto llamando al método `repaint()` **después** de haber agregado la nueva imágen.

Espero que esto responda tu duda, cualquier cosa me puedes responder por acá. Suerte! 🥕
