### ISSUE TITLE
Aparición Espontanea

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2233/syllabus#423]
Hola! En el enunciado dice que las entidades espontaneas pueden aparecer en "cualquier celda disponible del mapa", ¿esto incluye espacios cultivables sin semillas/plantas? o solo espacios libres (O)? 
Gracias :)

**Comment by aljara97** [comment]
Hola, al referirnos a que pueden aparecer en cualquier celda disponible en el mapa, nos referimos a que tiene que ser un espacio libre (indicados con una O en el mapa). Debes cuidar que no haya otro elemento en este espacio, ni que haya sido transformado a un espacio cultivable.

**Comment by jfuentesg26** [comment]
Gracias!!
