### ISSUE TITLE
Dudas .gitignore

### ISSUE THREAD

**Issue by Pablomaluk** [IIC2233/syllabus#423]
Hola hay un tema que no me queda claro con el .gitignore. Tengo que subir los archivos.csv y luego ponerlos en el .gitignore para que no registre cambios? O no subirlos y correr el main.py sin los deportistas.csv? Si no subo ningun .csv como correrian mi tarea?

**Comment by jitorcas** [comment]
Hola! @Pablomaluk 

Se recomienda que **antes** de hacer el primer push a tu repositorio crees el `.gitignore`  e incluyas  todos los archivos que quieres ignorar, ya que cuando hagas push no se subirán a tu repositorio. 

En caso que hayas hecho el primer push a tu repositorio y subiste archivos que quieres ignorar, podrías usar el siguiente comando para bajarlos de tu repositorio: `git rm --cached nombre_de_archivo.extension`

Nosotros tenemos los archivos que les pedimos que ignoren, por lo que no es necesario que los subas de nuevo. Recuerda que `parametros.py` no debe ir en el `.gitignore` dado que tu definirás los parametros del programa. 

Hoy en la sala de ayuda se habló mas concreto del tema, podrías ir a revisarla por si te quedan dudas. 

Mucho éxito! 🥇

**Comment by jitorcas** [comment]
@Pablomaluk recuerda no cerrar las issues por si le sirve a alguien más!

**Comment by javiermingo** [comment]
hola! hice commits parciales en la tarea antes de hacer el gitignore, pero al utilizar el comando señalado no me saca los archivos que señalo de mi repo, que puedo hacer?

**Comment by jitorcas** [comment]
@javiermingo Hola!

¿Escribiste bien el nombre del archivo y extensión?,¿Te lanza algún error o simplemente no se borra nada? 

Quedo atento!

**Comment by javiermingo** [comment]
hola! simplemente no se borra, quizás falte ingresar algún otro comando después o no?

**Comment by jitorcas** [comment]
@javiermingo 

Prueba lo [siguiente](https://www.google.cl/amp/s/www.arsys.es/blog/programacion/eliminar-archivos-repositorio-git/amp/) y avísame cómo te va!

**Comment by javiermingo** [comment]
perfecto! me sirvio, ya quedo bien muchas gracias
