### ISSUE TITLE
Posición de un widget

### ISSUE THREAD

**Issue by clementesepulveda** [IIC2233/syllabus#423]
Tengo una grilla dentro de un QHBoxLayout y le pongo un widgets en la posición i,j. Después, ocupo grilla.itemAtPosition(i, j).widget() para que me entregue el widget en ese lugar, pero al hacerle .x() me retorna 0 (al igual que .y()), pars todos los widgets dentro de la grilla.

**Comment by lily416** [comment]
Como sale en la documentación de [QGridLayout](https://doc.qt.io/archives/qt-5.6/qgridlayout.html#itemAtPosition), la función `QGridLayout::itemAtPosition(int fila, int columna)` retorna el item que se encuentra en la posición `(fila, columna)`. 
Además todos los elementos dentro de la grilla tiene posición `(0, 0)`, ya que se encuentran dentro de casillas independientes, por lo que siempre obtendras la posición `(0, 0)`.

Utiliza la fila y la columna que se entergan a `itemAtPosition()` para encontrar la posición del que debería tener el _widget_.

Saludos y éxito con la tarea. 👋 🐈🐧
