### ISSUE TITLE
Duda de enunciado: Funciones que pertenecen a distintas clases

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#423]
Hola! Viendo el enunciado me doy cuenta de que, por ejemplo, la "tienda" que vende alimentos se encuentra explicada en la sección DCC. No se si esto significa que se espera que implemente los mecanismos de la tienda de alimentos en la clase DCC, porque a mi me resulta más fácil implementar estos mecanismos en la misma clase Magizoólogo, pues involucra muchos atributos suyos (como los sickles o su inventario de alimentos). Me gustaría saber si implementar la venta de alimentos como una función dentro de la misma clase Magizoólogos me descontaría puntaje o no. Gracias!

**Comment by furcelay** [comment]
Hola!
No soy ayudante, pero echa un ojo a la issue https://github.com/IIC2233/syllabus/issues/263

**Comment by Dnpoblete** [comment]
Hola @lewebe , como bien dice @furcelay esta duda ya fue resuelta en la issue #263, por lo que voy a cerrar esta issue. En caso de leer la issue y seguir con dudas, pregunta en esa misma issue, para poder ayudarte. 😄
