### ISSUE TITLE
Error en librería matplotlib

### ISSUE THREAD

**Issue by Nicolasvegam** [IIC2233/Syllabus#423]
Hola,

 de hace rato que he estado tratando de saber que pasa con la librería de matplotlib que no la puedo instalar, ya busqué que hacer y aún no lo puedo solucionar.   Lo trate de instalar por Pycharm , por consola y tampoco, ayuda ! :( 

me arroja el siguiente error en Pycharm,

Command "python setup.py egg_info" failed with error code 1 in C:\Users\Nicolás\AppData\Local\Temp\pycharm-packaging\matplotlib

y en consola:

Command "python setup.py egg_info" failed with error code 1 in C:\Users\NICOLS~1
\AppData\Local\Temp\pip-build-nty3aroq\matplotlib

**Comment by TamaraCucumides** [comment]
No sé que onda tu error específico, pero a mi me fallaba la instalacion porque mi version de pip no era la más reciente (PyCharm me lo dijo). La actualicé y se me instalo al tiro.

**Comment by iqacevedo** [comment]
Hola!
Si aun tienes el error busca las Issues con el label Setup, en ellas se dijeron muchos comandos para intentar arreglar este tipo de problemas.
Saludos !
