### ISSUE TITLE
metodo process_query(query_array)

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#423]
Hola! No entiendo bien el parámetro `query_array` de este método. El enunciado dice:

> Recibe un parámetro llamado query array, que es una lista con todas las consultas seleccionadas en la interfaz (o todas, en caso de apretar el botón “Realizar todas las consultas”).

`query_array` es realmente de tipo lista o es de tipo string? Si es de tipo lista, entonces no entiendo en qué caso deberíamos leer el archivo consultas.json si es que el método `process_query(query_array)` lo hace automáticamente. Digo esto porque el enunciado también dice:

> Su programa debe: 
>1. Leer consultas.json

**Comment by Hernan4444** [comment]
@bedefrunner es del tipo list y con:
> 1. Leer consultas.json

Hacemos referencia a que la interfaz cuenta con una opción de cargar el archivo y ustedes deberían hacer uso de él para cargar todo el paquete de consultas y luego procesarlas. 

La idea de eso es poder almacenar una gran cantidad de consultas en un archivo en vez de ingresarlas una por una en la barra de texto que incluye la interfaz. Luego ustedes hacen click en las consultas que desean resolver y finalmente apretan el botón correspondiente para llamar a ese método el cual te dará una lista con todas las consultas.

Espero haber resuelto tu duda, sino no dudes en seguir preguntando c:
Saludos ✌️

**Comment by paula-ds** [comment]
en este método se puede agregar un parámetro? por ejemplo poner:
def process_query(query_array, algo):
     blablá

**Comment by Hernan4444** [comment]
@paula-ds no puedes.

Saludos :v:
