### ISSUE TITLE
modularización T03

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#423]
Hola, mi librería consiste en cuatro módulos: ```cineteca.py```, ```funciones_auxiliares.py```, ```constantes.py``` y ```lector_de_inputs.py```, separados según los roles de cada uno. En ```cineteca.py``` tengo las funciones que piden en el enunciado pero en el ```main.py``` que nos pasaron solo necesito importar ```lector_de_inputs.py```, una función de ```funciones_auxiliares.py``` y una constante de ```constantes.py```.
¿Eso está bien y lo dejo así o lo pongo todo (funciones del enunciado, funciones auxiliares, constantes y el lector de inputs) dentro del módulo ```cineteca.py```? ¿O intento hacer una librería empaquetada o algo similar? (pls elegir **dos opciones**, nunca he hecho una lib. empaquetada -creo que es lo más correcto para la situación- y no quiero gastar demasiado tiempo en eso :/ )

**Comment by Arcoirisky** [comment]
Me temo que no puedo decirte alguna forma de hacerlo. **Mientras te funcione** y no hagas nada prohibido por el enunciado, eres libre de explicarlo en el Readme :D 

Si solo necesitas importar una y no todos tus módulos en main, cool. Es tu forma de modelarlo :D 

Calma con esos detalles, las tareas (vistas de forma general) deben funcionar, no infringir nada prohibido por enunciado ni issues y seguir las instrucciones que se puedan dar como respuesta en algunas de las issues c: Si cumples con todo (o al menos las últimas dos xD) está bien :D Tienes el Readme para explicar bien tus ideas. 

Ánimo! Y suerte con los otros ramos /o/
