### ISSUE TITLE
Crear QLabel fuera del inicializador

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#424]
Para mostrar los objetos que se agregan en el inventario tengo un método dentro de una clase `Ventana` que crea un `QLabel`  pero al llamarlo no aparece ninguna label. Si copio y pego el mismo bloque de código en el `Ventana.__init__()` sí funciona. Ya me aseguré de que el programa está llegando a esa sección del código. ¿Qué podría estar pasando?

**Comment by StroveLight** [comment]
Hola!
Intentaste de hacerle al QLabel el .show() ?
algo como ```self.labels[mi_label].show()```

saludos (\*'ω'\*)

**Comment by dgzmr** [comment]
Había probado con `raise_()` pero con `show()` funcionó. Gracias
