### ISSUE TITLE
Animacion de ataques

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus#424]
Los ataques tienen que tener una animacion distinta al movimiento o puede ser la misma del movimiento? Lo que tengo ahora es que cuando un enemigo se mueve y choca contra la base entonces le dañan a la base, pero hacen la animacion del movimiento.

**Comment by lily416** [comment]
Sí, la animación del ataque debe ser distinta a la del movimiento, sino no se distinguirá entre ambos.

Saludos y éxito con la tarea. 👋 🐈🐧

**Comment by MartinAracena** [comment]
Mmm y tiene que tener 3 el ataque tambien? Porque creo que los sprites tienen 2 para ataque solamente. Yo tengo 2 sprites de ataques(distintos al movimiento) y cuando atacan se mueven hacia delante y hacia atras haciendo un efecto como de empuje.

**Comment by lily416** [comment]
@MartinAracena es válido que la animación este hecha de dos _sprites_ mientras se distinga del moviento.

Saludos y éxito con la tarea 👋 🐈🐧
