### ISSUE TITLE
Captura de errores

### ISSUE THREAD

**Issue by mora4** [IIC2233/Syllabus#424]
Hola,

En el enunciado de la T03 sale esto:
> (...) una librería levanta excepciones mientras que los usuarios que utilizan la librería son los que capturan los errores. Sólo se permitirá que su librería capture las excepciones deﬁnidas en este punto (...)

No entiendo si esta bien capturar y manejar errores dentro de la librería o estos deben ser capturados y manejados en el main?

Gracias!

**Comment by Hernan4444** [comment]
Revisar esta issue  #362 
Si te quedan dudas, continua en esa issue y no en otra por favor.
Saludos ✌️
