### ISSUE TITLE
Problema programa

### ISSUE THREAD

**Issue by barbarafcp** [IIC2233/syllabus#424]
Hola tengo un gran problema en el programa, lo que pasa es que en la función de validar competencia, al revisar si es que los participantes no están lesionados me tira False siempre, onda si pongo print(usuario.lesionado) me tira False y si pongo print(not usuario.lesionado) tambien me tira False, pero si el participante si esta lesionado, entonces ahi los imprime bien, y no se que onda

**Comment by vsantelicest** [comment]
Hola! 
Sería difícil detectar que es lo que pueda estar fallando sin ver el código, pero se me ocurre que tal vez el "False" que mencionas es un string y no un bool, por lo que al imprimir tanto usuario.lesionado como not usuario.lesionado, se te imprime el string "False". Verifica que esos valores efectivamente sean bool y no strings, y avisa si es que se resuelve. 🚲

**Comment by barbarafcp** [comment]
efectivamente era un string jajajaj muchas gracias!!!!
