### ISSUE TITLE
fenotipo: proporcion forma complementaria

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#424]
Holaa, en la forma complementaria dice 
_El fenotipo de un gen se expresar´a si y s´olo si, al menos un 20% de los genes de esa característica tiene ese valor_
Por el ejemplo que dan después y por como es en los demás casos, me imagino que el total para calcular ese porcentaje es la suma sólo de los que expresan, y no de los que no son codificables.
Es así?

**Comment by TomasSalvadores** [comment]
A diferencia los otros casos a los que hacer referencia, el enunciado no *abarca* explícitamente el deber de filtrar o no.
Debido a esto y al tiempo que queda de tarea, en este caso particular se considerarán ambas formas como correctas, pero **deben indicar en el readme cual usaron**.

**Comment by B-Dominguez** [comment]
Muchas graax!
