### ISSUE TITLE
Objeto retornado por "crear_funcion"

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#424]
Hola!

Según el punto 4.4.2 del enunciado, `crear_funcion` retorna una función. ¿Es obligatorio que esta función retornada sea un "callable"? ¿O podría ser otro objeto que nosotros denominemos función? En mi caso, `crear_funcion` retorna un `namedtuple` con toda la información de la función. Este objeto retornado es recibido por `evaluar` y retorna el mismo resultado final.

Saludos!

**Comment by Hernan4444** [comment]
@akaminetzkyp  la idea de que fuera `callable` es que asociaran ese requerimiento con el uso de decoradores, en tu caso no se está logrando ese objetivo por lo que no está completamente bueno.

Saludos!!

**Comment by akaminetzkyp** [comment]
No entendí lo de decoradores. ¿Qué tienen que ver aquí? 😨

Saludos!

**Comment by Hernan4444** [comment]
@akaminetzkyp te sugiero que le eches una mirada al material de clases. Ahí hay varios ejemplos que explican el uso de generadores y el potencial que tienen.

Saludos!

**Comment by akaminetzkyp** [comment]
Entiendo qué son los generadores y decoradores. Lo que no entiendo es qué tienen que ver los decoradores aquí.

Saludos!

**Comment by Hernan4444** [comment]
@akaminetzkyp lo siento pero no puedo explicitar sobre los decoradores ahora. Es parte de la tarea lograr relacionar los contenidos con lo solicitado.

Saludos!

**Comment by akaminetzkyp** [comment]
No hay problema. Gracias igual!

Saludos!
