### ISSUE TITLE
Problemas de instalacion de pyqt5-tools

### ISSUE THREAD

**Issue by ddenunzi** [IIC2233/syllabus#424]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

 **no puedo instalar pyqt5-tools en mi computador, ya instale pyqt5 y mi pip3 esta al dia. Esto es lo que me aparece, segui el link que me mandaron pero no supe como resolverlo sola**
<img width="1280" alt="Screen Shot 2021-05-03 at 11 20 27" src="https://user-images.githubusercontent.com/69667822/116896571-63d8d980-ac02-11eb-8bbb-a2a0d0464321.png">

**Comment by aaossa** [comment]
Hola @ddenunzi , ¿qué comando usaste exactamente para instalar `pyqt5-tools`? Además, ¿podrías mostrarme el *output* de este comando: `pip3 show pyqt5-plugins`?

**Comment by tamyhan** [comment]
A mi me aparece el mismo error! :( y con ese comando me sale esto:
WARNING: Package(s) not found: pyqt5-plugins

**Comment by aaossa** [comment]
Probemos algo:

1. `pip3 install pyqt5 --upgrade`
2. `pip3 install pyqt5-tools --upgrade`

Si aparece el mismo error avísen porfas 😅

**Comment by tamyhan** [comment]
Me volvió a aparecer el mismo error con el segundo comando

**Comment by aaossa** [comment]
A ver, veamos si esto resulta. Vamos a desinstalar pyqt5-tools y PyQt5, y luego vamos a instalarlo de nuevo. Para eso, tienen que usar estos comandos:

```bash
# Desinstalar pyqt5-tools (si es que lo pudieron instalar)
pip3 uninstall pyqt5-5tools
# Lo mismo pero con PyQt5
pip3 uninstall PyQt5
# Ahora instalar de nuevo PyQt5...
pip3 install PyQt5
# ... y pyqt5-tools
pip3 install pyqt5-tools
```

**Comment by tamyhan** [comment]
Lo acabo de intentar con pip3 y pip3.7 (porque tengo instalado python 3.9 también) y en los dos casos me tira un error distinto. 

**Con pip3 me tira error con los dos comandos:**
<img width="682" alt="Captura de Pantalla 2021-05-03 a la(s) 17 04 28" src="https://user-images.githubusercontent.com/71773541/116933647-d319f200-ac31-11eb-9b66-9a6ee2364fdd.png">

**Con pip3.7 me tira error solo con el segundo comando:**
<img width="682" alt="Captura de Pantalla 2021-05-03 a la(s) 17 05 28" src="https://user-images.githubusercontent.com/71773541/116933907-3441c580-ac32-11eb-886d-eca25a79af2d.png">

**Comment by aaossa** [comment]
@tamyhan y en 3.7 al desinstalar no te dió ningún error cierto? Solo al volver a instalar?

**Comment by tamyhan** [comment]
Al desinstalar PyQt5 no me salió ningún error, pero al desinstalar pyqt5-tools me salió esto:
WARNING: Skipping pyqt5-5tools as it is not installed.

**Comment by aaossa** [comment]
> 
> 
> Al desinstalar PyQt5 no me salió ningún error, pero al desinstalar pyqt5-tools me salió esto:
> WARNING: Skipping pyqt5-5tools as it is not installed.

Quedé con la duda, escribiste bien el nombre en el comando? `pyqt5-tools`

**Comment by tamyhan** [comment]
Ahhh parece que lo escribí mal antes, pero ahora lo intenté con el comando bien escrito y me vuelve a aparecer lo mismo:
WARNING: Skipping pyqt5-tools as it is not installed.

**Comment by aaossa** [comment]
Mmm yap, mejor vamos a probar otra cosa. Qt Designer es un programa independiente de Python, entonces puedes instalarlo por otros medios. ¿Puedes ver si te funciona la versión de esta página (la hemos recomendado en versiones anteriores del curso)? [https://build-system.fman.io/qt-designer-download](https://build-system.fman.io/qt-designer-download)

**Comment by tamyhan** [comment]
Ahí me funcionó!! Gracias!

**Comment by ddenunzi** [comment]
use pip3 install pyqt5-tools
<img width="545" alt="Screen Shot 2021-05-03 at 18 03 09" src="https://user-images.githubusercontent.com/69667822/116939179-e6c95680-ac39-11eb-90c8-2b8b483dda0b.png">

**Comment by ddenunzi** [comment]
> 2\. pip3 install pyqt5-tools --upgrade

tambien me aparecio el mismo error
<img width="567" alt="Screen Shot 2021-05-03 at 18 04 42" src="https://user-images.githubusercontent.com/69667822/116939265-137d6e00-ac3a-11eb-9305-0e29e89d9655.png">

**Comment by aaossa** [comment]
> 
> 
> Mmm yap, mejor vamos a probar otra cosa. Qt Designer es un programa independiente de Python, entonces puedes instalarlo por otros medios. ¿Puedes ver si te funciona la versión de esta página (la hemos recomendado en versiones anteriores del curso)? https://build-system.fman.io/qt-designer-download

@ddenunzi podrías probar si te funciona este instalador?

**Comment by ddenunzi** [comment]
al final use el link porque tenia exactamente los mismos problemas que mi compañer@ y  recien ahi me funciono

**Comment by aaossa** [comment]
Voy a dejar la *issue* abierta para que quienes tengan un problema similar la encuentren más fácilmente. Después de unos días se cierra 👌

**Comment by SofiaNome** [comment]
Holaa!! Tuve los mismos errores pero no me funcionó con el link que mandaste. Me aparece esto y no la puedo abrir.
![Captura de Pantalla 2021-05-06 a la(s) 13 39 46](https://user-images.githubusercontent.com/80910891/117342034-c46d4e00-ae70-11eb-8652-22d353e5cf34.png)

**Comment by antoniacaceres** [comment]
Holaa, me pasó lo mismo aún descargando QtDesigner desde el link, me abre y todo pero al instalar los tools me tira el error el mismo error que a los demás. No probé haciendo upgrade a pyqt5 porque mi computador no acepta la última versión, existe otra opción para instalar los tools o tendré que utilizar otra versión de QtDesigner? Gracias de antemano!

**Comment by pedroriosg** [comment]
Hola @SofiaNome y @antoniacaceres ✌️ 

Lo mejor que pueden hacer es descargar el `QtDesigner`, es confiable y seguro. Con `QtDesigner` instalado se pueden olvidar de los `tools`, de hecho yo no los tengo instalado y todo funciona perfecto.

Para abrir el `QtDesigner`, recomiendo ir al Finder, luego seleccionar las aplicaciones, pararse arriba de `QtDesigner`, hacer click derecho (o apretar el trackpad con ambos dedos) y seleccionar la opción de abrir. Luego dar permiso y ya está.

Avísenme si les funciona por favor,

Saludos!
