### ISSUE TITLE
Crear una clase sin __init__

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#425]
Hola, quiero crear una clase que no tenga atributos, sino solamente metodos. Debo omitir el __init__ al momento de crear la clase? O hay otra manera de hacerlo? No me quedó muy claro buscando en internet...

**Comment by Imenend** [comment]
Hola, yo hice eso poniendo _pass_ al init, desconozco si hay otra forma.

**Comment by fdoflorenzano** [comment]
Hola @lewebe,

Sí, puedes omitir la definición de `__init__` en una clase, y puedes instanciarla de todas formas. De hacerlo, no habrá código que se ejecuté para cada instancia, pero si tiene acceso a todos sus métodos que se le definan.

Por ejemplo, el siguiente código es válido. Intenta ejecutándolo para asegurarte:
```python
class A:
    pass

class B:
    def saludar(self):
        print("Hola")

a = A()
b = B()
b.saludar()
```

Saludos.
