### ISSUE TITLE
Duda comprar en tienda

### ISSUE THREAD

**Issue by itplanella** [IIC2233/syllabus#425]
Hola! Tengo una duda en la parte de distribución de puntajes que dice "Se puede comprar solo cuando el personaje se para sobre la tienda". Para que el programa se vea mejor estoy haciendo que el personaje no pueda ponerse sobre la tienda y que al momento de tratar de ponerse se abra la ventana de la tienda. Quería saber si esto se puede hacer o no se me dará el puntaje. Gracias de antemano.

**Comment by tomasgv** [comment]
Hola!
Te recomiendo mejor seguir el enunciado, pues hay un descuento asociado y eso podría considerarse como no seguirlo. 

Saludos! 🌱
