### ISSUE TITLE
Duda Consultas.jason

### ISSUE THREAD

**Issue by augustoas** [IIC2233/Syllabus#425]
Hola, en el archivo de testeo no hay consultas del tipo indice de tamaño ni de las consultas estadísticas.
Con qué nombre se van a ingresar ese tipo de consultas? 
ejemplo:
c = ["min", "AAT"]
c =  ["indice_de_tamano","nombre_persona"]

O solo las consultas de ascendencia, pariente de, gemelo genetico y valor caracteristica son las que se deben ingresar a gui en ese formato?

Saludos !

**Comment by Hernan4444** [comment]
@augustoas con el mismo nombre que tienen en el enunciado, eso incluye tildes y ñ.

Saludos ✌️
