### ISSUE TITLE
Inconsistencia con enunciado test_publico_05

### ISSUE THREAD

**Issue by m-cozzetti** [IIC2233/Syllabus#425]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/421)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Problema

**EDIT**: Me equivoque con la label del issue, esto **es sobre la tarea 3, no la actividad**

Para la función `clientes_despues_hora` el enunciado dice que la hora sera un string de la forma `"HH"`, pero en el test publico 05 se entregan strings de la forma `"HH:MM"`. ¿Esta mal el enunciado, el test, o hay que tomarlo en cuenta en nuestro código?

Ejemplo de como sale en el test:
![image](https://github.com/user-attachments/assets/dc774137-bbb4-4831-b35e-f189d6e9ea7d)

**Comment by Vicente1824** [comment]
¡Hola @m-cozzetti 🙂! Efectivamente es un error del enunciado, el formato correcto será un string de la forma "HH:MM". Pronto se actualizará el enunciado para reflejar esto.
