### ISSUE TITLE
Hard_coding

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#425]
hasta que punto tengo que agregar a parametos.py , tengo en general casi todo ahí
 pero encuentro que algunos es medio innecesarios.
esta screen se considera mala practica por hard_code o esta bien.
saludos!

**Comment by mmunozmendez** [comment]
Hola!
Eliminé tu foto, porque no debes compartir código de tu tarea por este medio.
Queda a tu criterio cuántos parametros crear, lo importante es entender por qué usamos este archivo. Cuando tienes un valor como constante en parametros, al modificarlo, modificas el valor en cada lugar donde lo usas, por lo que es importante usarlo cuando tendrás un valor que puede cambiar a lo largo del programa por ejemplo. Los mínimos son los que en el enunciado tienen ESTE_FORMATO y todos los path, el resto depende de tu implementación.
Se considera hard_code cuando tu fuerzas valores, sería por ejemplo no leer un archivo y escribir directamente en tu programa la información que almacena. Tu línea está correcta.

**Comment by sa-Appel** [comment]
Perdón por lo de la foto, tendré mas cuidado para la prox. me quedo claro con la explicación, gracias !
