### ISSUE TITLE
Error test 12 y 07 con id_votantes

### ISSUE THREAD

**Issue by ManuelMandujano** [IIC2233/Syllabus#425]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En los test_case particulares 07 y 12 para los que no son de carga de datos, cuando hago local.id_votantes no me tira error y paso todos los test case, sin embargo para los de carga de datos, me dice que Locales no tiene "id_votantes" y cuando cambio local.id_votantes por solo local.votantes tengo los test case de carga de datos buenos y los otros malos. Esto no me paso antes de que actualizaran los archivos y en su momento corrian todos los test case perfectos, despues para correr el archivo todos_tests me percate de esta situación, como en el enunciado sale que locales si tiene id_locales lo planeo dejar asi pero hay alguna explicación de porque me pudiera estar pasando?

**Comment by mpiavf** [comment]
Hola! Puedes verificar que estás trabajando con los últimos archivos? Tanto en los .csv como en los test 07 y 12 no encontramos que haya algo con votantes, todo dice id_votante. 
Me comentas.
Saludos!

**Comment by ManuelMandujano** [comment]
En teoria son los ultimos archivos, para asegurarme clone el repositorio denuevo hoy dia mismo y me sigue saliendo el mismo error, sin embargo probe mi codigo en otro computador y no arrojo error al usar .id_votantes... asi que dejare todo como .id_votantes nada mas, gracias!
