### ISSUE TITLE
Duda sobre diccionarios y EX01

### ISSUE THREAD

**Issue by gracie-14** [IIC2233/Syllabus#426]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola!

Tengo entendido que los diccionarios son muy eficientes para acceder a un valor a través de una llave, y que hay un tiempo constante para eso aunque existan miles de entradas en el diccionario.

Por eso estoy un poquito confundida con respecto al código de la EX01. Porque en el método de ```__getitem__``` del diccionario que definimos, llama a una función que hace esto con un for loop:
<img width="609" alt="Screenshot 2024-10-01 at 2 17 17 PM" src="https://github.com/user-attachments/assets/9394d3b4-4c8b-4a8b-8e23-00c22cc37185">
Puesto que itera sobre cada elemento en el diccionario, ¿la eficiencia no dependería en la cantidad de elementos?

Mi pregunta es, ¿hay algo que no hemos aprendido que explica como los diccionarios son tan eficientes? 

(y si lo hemos aprendido, es relevante para el midterm jaja?)

**Comment by 3rdPix** [comment]
Hola @gracie-14 !

Lo que pasa es que no es un diccionario.

Saludos :D

...


En la experiencia 01, para ser precisos, lo que crearon es un *simulador* de diccionario, una estructura de datos personalizada que llamaron `DCCustomDictionary`. No es un diccionario propiamente tal, porque se basa en nodos secuenciales. A pesar de que por fuera tenga el mismo comportamiento que un diccionario, en el fondo, lo que ustedes programaron, no lo es. De ahí que tengas la confusión.

Un diccionario real lo que utiliza son otras técnicas para identificar los datos (véase [Hashing](https://en.wikipedia.org/wiki/Hash_table)), no un `for` ni una iteración sobre los datos, esto le permite lograr la velocidad que tu, correctamente, asocias a los diccionarios.

Me cuentas si tienes otras dudas 🦎
