### ISSUE TITLE
¿Cuáles eventos se deben mostrar al pasar a un nuevo día? 

### ISSUE THREAD

**Issue by LeoMo-27** [IIC2233/syllabus#426]
Hola!

Perdón si ya lo preguntaron pero no lo encontré en el compilado, mi duda es con respecto a lo que se printea al pasar al siguiente día, por ejemplo en la parte que sale criaturas hambrientas, debo mostrar todas las criaturas hambrientas que tengo o debo mostrar las que se enfermaron ese mismo día?

Muchas gracias!!

**Comment by aljara97** [comment]
Hola @LeoMo-27!

Debes encargarte de mostrar los eventos que ocurren en el día correspondiente, por tanto, no es necesario que muestres todas las criaturas hambrientas. 

Suerte con tu tarea 🧙‍♂️
