### ISSUE TITLE
actores N/A - MovieError

### ISSUE THREAD

**Issue by auirarrazaval** [IIC2233/Syllabus#426]
Hola! Los actores que salen como N/A deberian levantar error MovieError al ser procesados>, ya que para procesar por ser el ingreso por actor de una pelicula para highest_paid_actors, si esque uno de los actores de dicha pelicula es N/A a pesar de no ser uno de los actores en cuestion, lanzaria error.

pd: porfa respondan las ultimas preguntas de librerias permitidas/no permitidas :)

**Comment by Arcoirisky** [comment]
Hola~ ¿Cuál es la pregunta? O:

**Comment by auirarrazaval** [comment]
Si puedo usar statistics.mean(), gracias!

**Comment by Hernan4444** [comment]
Hola, sobre los actores, ten precaución que talvez un Actor N/A era de la película Buscando a Nemo, pero justo esa fue filtrada antes y por ello, nunca llegaremos a ese actor N/A. Solo los actores que tengan que ser considerados en la consulta para poder responderla pueden generar un error en caso de ser N/A.

y sobre statistics, ya la respondí 👍 
Saludos ✌️
