### ISSUE TITLE
Como nombrar a los parámetros?

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#426]
Holaa!
Tengo una duda acerca de como llamar a los parámetros de `parametros.py`. Es necesario nombrarlos como `NOMBRE_PARAMETRO_EN_MAYUSCULAS` o puede ser tambien `lo_mismo_pero_en_minusculas`?

Pregunto porque al momento de importarlos al módulo donde los queremos ocupar, pensaba que quizás usarlos con los nombres en mayúsculas podría ir en contra de las reglas de pep8.

Pensaba también importarlos con `import as`, pero eso seguiría conservando los eventuales nombres en mayúscula

**Comment by retamalcito** [comment]
¡Hola @Gsalinas1506!

Cómo se indica en el enunciado, **sí es necesario** que los parámetros encontrados en `parametros.py` se escriban con `ESTE_FORMATO`. Sin embargo, no debes preocuparte, ya que esto no infringe ninguna norma de PEP8 que deban seguir.

Es normal que las líneas a veces queden muy largas debido a los nombres de los parámetros 😅, por lo que sí te recomiendo usar, por ejemplo, `import parametros as pm` para ahorrar algunos caracteres. De todas formas, para estas situaciones es que existe el backslash (`\`).

¡Saludos y mucha suerte! 🥇

**Comment by Gsalinas1506** [comment]
okk, entendido. Muchas Gracias!
