### ISSUE TITLE
Cargar mapa cuando en mapa_n.txt hay espacios C, O, C

### ISSUE THREAD

**Issue by gustavo-toro** [IIC2233/syllabus#426]
Hola, tengo duda en cómo cargar el mapa cuando hay una fila o columna `C O C`. 
Sin considerar los tiles borde se vería algo asi.

 ![tiles](https://user-images.githubusercontent.com/48481641/66285268-4c106680-e8a2-11e9-8c2b-59e50ff3c361.jpg)

Si en el tile del medio quiero incluir los bordes de la tierra y pasto, no puedo poner bordes a ambos lados porque no encontré un sprite para eso. Si dejara los tiles borde en los espacios `C`, funcionaría, pero tendría problemas al cargar algo como `O C O`. Nosé qué hacer para que se vea bien.
Muchas gracias.

**Comment by aljara97** [comment]
Hola, si no hay sprites para eso puedes representarlo de la forma en que está en la imagen que muestras. Recuerda que solo es necesario que se distinga un tipo de espacio de otro y funcionen de manera adecuada, no siendo el foco de la tarea que esta se vea "bonita". Sin embargo, si tienes tiempo y quieres implementarlo de esta forma, puedes crear el sprite en base a las imágenes entregasas y subirlo en una carpeta aparte, la cual debe estar especificada en tu readme

**Comment by gustavo-toro** [comment]
Gracias.
