### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by Dafnemami** [IIC2233/syllabus#427]
Debo subir la carpeta mapa, pero no así los archivos o debo simplemente no debo subir la carpeta mapa?

**Comment by gatochico** [comment]
Hola! No es necesario que subas la carpeta mapas, puedes asumir que nosotros la agregaremos (: De todos modos, para asegurarte podrías indicar en tu README que la carpeta debe existir para correr tu programa y que la debemos añadir. 
Saludos!
