### ISSUE TITLE
Dudas sobre simular competencias

### ISSUE THREAD

**Issue by enriquerussi** [IIC2233/syllabus#427]
Hola, tengo 2 dudas. La primera es si cuando me dicen que queda a mi criterio si el rival utiliza o no sus días de entrenamiento, ese criterio es refiriéndose a mi como programador (podría no programar la opción) o como usuario (tengo que programarlo igualmente y decido si el rival utiliza esos días o no). La segunda duda es cuando ya no quedan más días para competir, la opción de realizar una nueva simulación se refiere a partir el programa de nuevo o en el caso de realizar otra simulación de de competencia (ya no quedarían días de competencia para simular).

**Comment by vsantelicest** [comment]
Hola enrique! 
Con respecto a tu primera pregunta, se refiere a tu criterio como programador, donde decides si el entrenador oponente entrenará en los días destinados a ello o no lo hará. 
Sobre tu segunda duda, efectivamente, se refiere a reiniciar la DCCumbre Olímpica por completo, restaurando los valores que hayan sido alterados durante la última simulación hecha.
