### ISSUE TITLE
Error cuando ejecuto método por segunda vez

### ISSUE THREAD

**Issue by amparostevens** [IIC2233/syllabus#427]
Hola! Tengo un error muy raro y que no sé que podrá ser. Cuando ejecuto mi programa y quiero `cargar_magizoologo`, la primera vez que lo ejecuto sale todo bien y el método me devuelve efectivamente el magizoólogo. 
![Captura1](https://user-images.githubusercontent.com/53883653/79058747-d2d24180-7c3f-11ea-8e31-f61ff49b525a.PNG)
Pero cuando al ingresar la opción del nombre del magizoólogo me equivoco y vuelvo a llamar al método, el resultado es `None`. Hice print de todos los pasos y la única parte en que se "pierde" el magizoólogo es cuando el método lo retorna. 
![Captura2](https://user-images.githubusercontent.com/53883653/79058779-36f50580-7c40-11ea-8c8b-43163acb3e1e.PNG)

**Comment by sbcorrea** [comment]
hola! no soy ayudante pero en la T00 me pasó mucho esto, y era porque en el código principal no estaba usando suficientes loops—y sin loops, la variable no se sobreescribía. también se puede resolver con recursividad... ojalá te sirva!

**Comment by JosefaPaz** [comment]
¡ Hola @amparostevens !

Pudiste solucionarlo? Si no es así, sube tu código al repositorio y vemos qué podría estar fallando.

Quedo atenta 😸

**Comment by amparostevens** [comment]
Graciaaas @sbcorrea!! Ya lo pude solucionar. Era un mal manejo de los loops

**Comment by sbcorrea** [comment]
de nadaa :)
