### ISSUE TITLE
Librerías permitidas/no permitidas en la T04

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233/Syllabus#427]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:

> Puedo usar la librería nombre_libreria para hacer explicacion_de_lo_que_quiero_hacer

Recuerden especificar en su README qué librerías utilizan!

—-
## **Librerías Permitidas**
- random
- csv
- logging
- abc
- datetime
- collection
- math
- time
- statistics.mean
- Numpy
- copy
- itertools
- Tabulate
- Typing
- abc
- functools.reduce
- matplotlib

## **Librerías Prohibidas**
- threading 
## **Built-ins prohibidos**
- eval (:skull:)
- exec (:skull:)

**Comment by FarDust** [comment]
Puedo usar la librería abc para hacer una clase abstracta ?

**Comment by stephichau** [comment]
@FarDust sí puedes!

**Comment by maxfreymo** [comment]
Puedo ocupar la librería threading ? (Se que es casi obvio, pero el casi es la diferencia jaja)

**Comment by Hernan4444** [comment]
@maxfreymo no puedes usarla. En esta tarea queremos que apliquen el conocimiento de Simulación basado en eventos discretos. Mas adelante usarán theading.

Saludos!!

**Comment by malopez16** [comment]
Puedo usar datetime para administrar las fechas?

**Comment by Hernan4444** [comment]
@malopez16 si puedes c:
Saludos!

**Comment by josemlira** [comment]
Puedo usar la librería functools para usar reduce?

**Comment by stephichau** [comment]
@josemlira sí ! :)

**Comment by egbusch** [comment]
Puedo usar la librería matplotlib para hacer los gráficos ?

**Comment by iqacevedo** [comment]
@egbusch si puedes !

**Comment by fcgfaura** [comment]
Puedo usar `mean` de `statistics`?

**Comment by Hernan4444** [comment]
@fcgfaura  si puedes!!
Saludos

**Comment by dgonzalezg** [comment]
¿Puedo ocupar pandas para trabajar con los archivos csv?

**Comment by chuma9615** [comment]
Se puede usar pandas para manejar escenarios.csv?
