### ISSUE TITLE
Vocabulary por palabra

### ISSUE THREAD

**Issue by dnalfaro** [IIC2233/Syllabus#427]
1. Cuántas palabras diferentes de vocabulary se pueden encontrar por palabra? Debo asumir que muchas o solo una por palabra?
1. En caso de que se repita una palabra de vocabulary en una misma palabra, la debo considerar como 1?
Ejemplo: si hola está en vocabulary, holaholahola sería suficiente para cumplir el requisito de:

> Repite 3 veces al menos una de las palabras de su vocabulario.

**Comment by Arcoirisky** [comment]
1) Pueden haber muchas~ Como puede haber sólo una. 

2) Estoy segura que algo similar se respondió en otra issue. Hecha un vistazo c:
