### ISSUE TITLE
Error al correr elementos_prohibidos - Bad Magic number

### ISSUE THREAD

**Issue by jisalasc** [IIC2233/Syllabus#427]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Tengo una pequeña duda, ahora no puedo correr elementos_prohibidos por un error extraño, antes si podia creo que algo paso por que actualicé  nuevamente los test.
![Captu
![Captura de pantalla 2024-05-23 215707](https://github.com/IIC2233/Syllabus/assets/162588701/ebbaa1e9-ad5c-47fa-a8c0-bbad674a34f0)
![Captura de pantalla 2024-05-23 215707](https://github.com/IIC2233/Syllabus/assets/162588701/ebbaa1e9-ad5c-47fa-a8c0-bbad674a34f0)
![Captura de pantalla 2024-05-23 215707](https://github.com/IIC2233/Syllabus/assets/162588701/ebbaa1e9-ad5c-47fa-a8c0-bbad674a34f0)
ra de pantalla 2024-05-23 215707](https://github.com/IIC2233/Syllabus/assets/162588701/a1a0833b-9b91-4e70-8105-34332d79f918)

**Comment by vaniaulloa** [comment]
me pasa igual, pudiste solucionarlo?

**Comment by abraxvs** [comment]
Hola, me pasa lo mismo. Con la T1 me pasó y lo solucioné asegurándome que la versión de python con la que lo estaba corriendo fuera mayor a 3.11.7; sin embargo eso no funcionó esta vez):

**Comment by Hernan4444** [comment]
Hola, 

Fue un error por nuestro lado, que se había compilado con una versión vieja de python en vez de la 3.11.

Ahora está subida la versión correcta.
Avisen como les va con esto.

Saludos!

**Comment by abraxvs** [comment]
> Hola,
> 
> Fue un error por nuestro lado, que se había compilado con una versión vieja de python en vez de la 3.11.
> 
> Ahora está subida la versión correcta. Avisen como les va con esto.
> 
> Saludos!

Hola @Hernan4444 !
A mi me funciona perfecto ahora, muchas gracias:)
