### ISSUE TITLE
consulta: prom(tag_caracteristica)

### ISSUE THREAD

**Issue by cirey1** [IIC2233/Syllabus#427]
En la parte de promedio, se pide medir el promedio de todas las alturas o tamano pies de las personas existentes en el archivo, que pasa cuando una de esas personas tiene GenomaError en la caracteristica pedida; se deberia entregar un error de output? o se salta a esta persona y se corre la funcion con el resto de las personas del archivo que no tengan problemas de genoma en esa caracteristica?

**Comment by Hernan4444** [comment]
@cirey1 con una persona es suficiente para que se caiga el programa y por ello debes entregar un error de output.
Saludos ✌️

**Comment by fjaraneda** [comment]
@Hernan4444 Hola, entonces para el caso del genoma genetico, si hay una persona con un error en el genoma, significaria que no hay genoma genetico???
