### ISSUE TITLE
Tipos de los atributos en las namedtuples

### ISSUE THREAD

**Issue by MTGG123** [IIC2233/Syllabus#427]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/421)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado de la tarea 3, nos dicen que los atributos de las namedtuple tienen un tipo definido, pero ¿Es obligatorio usar ese tipo a la hora de definir una instancia, o podemos dejar algunos con otro tipo? (ej. ingredientes de las pizzas como una lista en vez de un string)

**Comment by NachoRinda** [comment]
Hola, sí. Si te fijas en los archivos <test_*.py> del directorio "tests_publicos/solution/" verás la solución con la que se compara tu output en cada test. En cada una de estas soluciones las namedtuple tienen sus atributos definidos tal y como dice el enunciado. Por ejemplo, en <test_04.py> los ingredientes de cada namedtuple son strings y no listas como sugieres:
AJUSTAR_PRECIO_SEGUN_INGREDIENTES_S_1 = [
    Pizzas(nombre='Tocino BBQ_S', ingredientes='tocino;salchicha;queso;salsa BBQ', precio=17957),
    Pizzas(nombre='Tocino BBQ_M', ingredientes='tocino;salchicha;queso;salsa BBQ', precio=20344),
    Pizzas(nombre='Tocino BBQ_L', ingredientes='tocino;salchicha;queso;salsa BBQ', precio=27731)]

**Comment by MTGG123** [comment]
> Hola, sí. Si te fijas en los archivos <test_*.py> del directorio "tests_publicos/solution/" verás la solución con la que se compara tu output en cada test. En cada una de estas soluciones las namedtuple tienen sus atributos definidos tal y como dice el enunciado. Por ejemplo, en <test_04.py> los ingredientes de cada namedtuple son strings y no listas como sugieres: AJUSTAR_PRECIO_SEGUN_INGREDIENTES_S_1 = [ Pizzas(nombre='Tocino BBQ_S', ingredientes='tocino;salchicha;queso;salsa BBQ', precio=17957), Pizzas(nombre='Tocino BBQ_M', ingredientes='tocino;salchicha;queso;salsa BBQ', precio=20344), Pizzas(nombre='Tocino BBQ_L', ingredientes='tocino;salchicha;queso;salsa BBQ', precio=27731)]

Ahh ok, muchas gracias
