### ISSUE TITLE
Duda QSound

### ISSUE THREAD

**Issue by Brocoleta** [IIC2233/syllabus#427]
Hola, estoy tratando de implementar sonidos en la tarea con QSound como sale en el enunciado, el problema es que no he logrado encontrar mucha informacion en internet, he visto que hay dos formas de reproducir un sonido:
1.
```
 s = QSound("archivo.wav")
 s.play()
```

Cuando ocupo esa forma no se me reproduce ningun sonido

2. 
`QSound.play(archivo.wav)`

Cuando ocupo esa forma me sale el error QSoundEffect(qaudio): Error decoding source

Tambien he visto que existe la libreria pyside donde tambien existe el metodo QSound pero nose si se puede ocupar

**Comment by bmurtagh01** [comment]
Me pasa lo mismo

**Comment by Oisangui** [comment]
tienes que asignar el sonido al qwidget como una variable y ponerle play. Así me funciona al menos

**Comment by lily416** [comment]
Prueba agregando la variable `s` como un atributo de la clase:
```python
 self.s = QSound("archivo.wav")
 self.s.play()
```

Saludos y éxito con la tarea. 👋 🐈🐧
