### ISSUE TITLE
Lineas de código: sugerencia

### ISSUE THREAD

**Issue by kylevon** [IIC2233/syllabus#428]
Debido a que los comentarios en nuestro código cuentan como lineas de código, el descuento por lineas de código penaliza esta buena práctica. Debido a esto yo y probablemente muchos más compañeros no ponen muchos comentarios en el código (De hecho, yo eliminé varios de mi código por esta razón) debido a esto y también por que si se ponen de manera horizontal infringen pep8... Por ende, recomiendo no contar las lineas con comentarios como lineas de código para la futura tarea. Esto es muy fácil de hacer en la práctica, simplemente pueden usar regular expressions en python para parsear todas las tareas antes de revisar las lineas de código. 
Estos comentarios a los que me refiero son de ambo tipo:
```
"""
Comentario
"""
```
y del tipo
``` #Comentario```
y hay que tener ojo en el parseo de estos comentarios porque puede que estén entre paréntesis, es decir:
```
function(
    bar,
    """.
#bar
   """
    )
```
no debería eliminarse ese string de multiples lineas.
o tampoco en el caso de:
```
string = """
no es comentario
"""
```
No creo que sea un tema muy difícil de implementar y ayudaría mucho a la enseñanza en este curso.

**Comment by iqacevedo** [comment]
Hola,

Tener muchos comentarios en código no es una buena práctica, esto es un code smell (indicio de que algo no está bien con la calidad del código, más info ver [acá](https://en.m.wikipedia.org/wiki/Code_smell) ). En general un buen código es auto-explicativo, con buenos nombres de funciones y constantes, sin la necesidad de agregar comentarios. El detalle de este code smell, lo puedes ver [acá](https://refactoring.guru/smells/comments).

Es por este motivo que no se restarán las lineas de comentarios.

Saludos.
