### ISSUE TITLE
Ifs en lambda

### ISSUE THREAD

**Issue by savelozo** [IIC2233/Syllabus#428]
Es legal tener, por ejemplo, 3 ifs en una misma función lambda?

**Comment by Arcoirisky** [comment]
Mira #410 a ver si resuelve tu duda

**Comment by savelozo** [comment]
@Arcoirisky sí lo había leído, pero es lo que estoy preguntando :(

**Comment by jtagle2** [comment]
@savelozo, puedes escribir un ejemplo de lo que estás pensando?

**Comment by indonoso** [comment]
Sí se puede. Pero debes entender cómo funciona cada uno. Por ejemplo:
``` python
>>> f = lambda x: (x*2 if x > 1 else x -1) if x < 4 else x + 1
>>> f(6)
7
>>> f(5)
6
>>> f(4)
5
>>> f(3)
6
>>> f(-1)
-2
```

Aquí, primero se evalúa `x<4` si esto es verdadero, se evalúa `x > 1`.

**Comment by savelozo** [comment]
@jtagle2 me refería a algo así:

lambda x: pariente_menos(persona) if x == -1 else
        (pariente_cero(persona) if x == 0
        else(pariente_uno(persona))
        if x == 1 else(pariente_dos(persona)
        if x == 2 else pariente_npersona))))

Al final esa es una sola línea, pero con 4 condiciones distintas.
