### ISSUE TITLE
[Nivel de confianza]

### ISSUE THREAD

**Issue by Okhan97** [IIC2233/Syllabus#428]
Dice que el nivel de confianza inicial distribuye uniformemente entre 2 y 12 , ¿ esto es de manera discreta o continua ?

**Comment by sebacruzd** [comment]
Distribuye de manera continua.

**Comment by acrojas2** [comment]
Hola:
Tengo dudas acerca de la formula de confianza_notas:
Nota(a, b, c), final: ¿Se refiere a la ultima nota publicada por el coordinador? De se ser así x, y, z solo en las primeras semanas podrían ser 0, porque el resto del tiempo serían 1. 
Si alguien me lo pudiera explicar por medio de un ejemplo porfavorr!!!
Saludos!

**Comment by iqacevedo** [comment]
Hola

Los valores de x, y, z dependen de cada vez que ocurre el evento en que el coordinador sube notas.
Por ejemplo:
- si en una misma subida de notas el coordinador sube una nota de tarea y una de actividad, entonces x=1, y=1, z=0
- si en otra subida de notas el coordinador sube solo una nota de control, entonces x = 0, y=0, z=1
- si en otra subida de notas el coordinador sube una nota de control junto con una nota de tarea, entonces x=0, y=1, z=1.
- si en otra subida de notas el coordinador solo sube una nota de actividad, entonces x=1, y=0, z=0.

Espero haber entendido tu duda y que esto la resuelva. 
Quedo atento, saludos  !
