### ISSUE TITLE
Ocupar for para hacer levantamiento de errores

### ISSUE THREAD

**Issue by akrebs2** [IIC2233/Syllabus#428]
Hola. Está permitido hacer for's anidados para hacer "raise" de errores? Creo que no lo especifican en la issue que se habla de los for's permitidos/prohibidos.

Sería algo como:
```python
for pelicula in movies:
    if "N/A" in atributos_pelicula:
        raise MovieError
```
Saludos

**Comment by contranton** [comment]
No se si efectivamente será legal o no usar ese for, pero investiga sobre los built-ins `any` y `all` que quizás te pueden ser de utilidad.

#NoSoyAyudante

**Comment by jmwielandt** [comment]
#TampocoSoyAyudante

Les recomiendo darle una vuelta más: si algo se puede hacer con for, se puede hacer con reduce 😉
