### ISSUE TITLE
Cómo expresar no alimentos en archivo magizoologos.csv

### ISSUE THREAD

**Issue by AAVP** [IIC2233/syllabus#428]
Al crear un nuevo magizoologo, debo escribirlo en el archivo, pero el problema que se me viene es que al ser nuevo empieza sin ningún alimento. Es un problema porque no sé cómo se debe expresar eso en el string que dejo en el archivo. Si dejo vacío, dejando dos comas juntas (...criaturas,,licencia...), hay un problema porque al instanciar al magizoologo, el atributo de la lista de alimentos me queda como una lista NO vacía (es una lista con un solo elemento llamado ''. No pido que me solucionen el problema de la lista, sino que solo saber cómo dejar expresado el string que escribiré en el archivo. Muchas gracias!

**Comment by jaimecoloma** [comment]
@AAVP Hola! No soy ayudante pero el enunciado especifica que cada magizoologo nuevo SI comienza con un alimento aleatorio. Te lo cito!  (Aparece en la parte 4.1 pag 7)
Alimentos: Son los productos esenciales para el cuidado de tus DCCriaturas. **Cada nuevo Magizoologo parte con 1 alimento aleatorio**. Los alimentos existentes se detallan en la sección Alimentos.  Saludos

**Comment by AAVP** [comment]
Muchas gracias amigo me salvate! Y no me fijé en eso jaja son tantas cosas que siempre se me va a pasar algo:( jaja saludos!

**Comment by furcelay** [comment]
Hola!
Tampoco soy ayudante, pero pese a que el magizoologo parta con un alimento, este pude llegar a no tener ninguno si le da este alimento a una criatura. Ya que el formato es fijo no deberías interpretarlo, creo que deberías dejarlo como dices (`...criaturas,,licencia...`) y ver como manejar la lista vacía...

**Comment by AAVP** [comment]
No todo podía ser de color de rosas :(

**Comment by matiasmasjuan** [comment]
Hola @AAVP !

Tal como dice @furcelay , en caso de que un **Magizoólogo** se quede sin **alimentos**, el archivo ```magizoologos.csv``` deberá verse escrito de la siguiente forma:

```...,SICKLES,CRIATURA1;CRIATURA2,,LICENCIA,NIVELMAGICO,...```.

En donde ustedes deberán trabajar posteriormente con la lista **vacia** de alimentos.

Éxito con la tarea! 😄

**Comment by Camila-sty** [comment]
Hola!
Se puede alimentar a una criatura que está satisfecha ? 
En vida real no, porque ya esta satisfecha, pero como no lo dice el enunciado, no quiero intuir nada.

**Comment by Camila-sty** [comment]
Cuando el archivo queda con un ",," porque se quedó sin alimentos, qué es lo que hay entre comillas? es un string vacío?

**Comment by matiasmasjuan** [comment]
Hola @Camila-sty !

* Si, puedes alimentar una **DCCriatura** que ya está satisfecha.
* Exactamente, si un **Magizoologo** se queda sin alimentos, entonces en el archivo ```magizoologos.csv``` se verá algo así:
```CRIATURA1;CRIATURA2,,LICENCIA,...```. En el espacio donde hay **dos** comas seguidas, se ubica un *string vacío*, ya que no hay alimentos presentes.

Saludos y mucho éxito con la tarea 😄
