### ISSUE TITLE
Arar e interaccion con casa y tienda

### ISSUE THREAD

**Issue by raimundoloeser** [IIC2233/syllabus#428]
Tengo 2 dudas, Cuando el personaje decide arar o talar un arbol, este pierde la herrmienta? o al tener una herramienta la puede usar para siempre en el juego mientras la tenga. 
Por otro lado, para la interaccion con la casa y la tienda, sale que el jugador debe 'pararse' sobre estos. se refiere a que tiene que estar sobre y sin moverse? o cuando este sobre se realiza la accion de cada uno

**Comment by jeschuwirth** [comment]
Hola @raimundoloeser,

Para la pregunta 1: **no** se pierden las herramientas al usarse, por lo tanto una vez compradas las tienes para siempre :)

En cuanto a la segunda queda a criterio, pero ten en cuenta que si el jugador sale de la tienda debe perder la opción de comprar. En otras palabras, si decides abrir una nueva ventana cuando el jugador se para en la tienda, entonces se debe cerrar si el jugador sale de ella.

Suerte!
