### ISSUE TITLE
Metodo correr_segunda_mitad AC 4 y participantes avanzando despues de los 100 m

### ISSUE THREAD

**Issue by vhernnda** [IIC2233/Syllabus#428]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

En el enunciado se pide que para el metodo correr_segunda_mitad despues de liberar el lock el participante avance, sin embargo esto lleva a que despues algunos threads impriman mas de una vez el mensaje "Avancé a 100.00" pese a esto al ejecutar los tests me sale todo bueno. Es por esto que tengo la duda de si esto podria llegar a causarme problemas al revisar mediante tests privados

**Comment by vhernnda** [comment]
Entonces mejor lo dejo como esta?

**Comment by Hernan4444** [comment]
Hola @vhernnda 

Si, lo que mencionaba en el segundo párrafo era solo como una idea para mejorar la simulación. Lo importante es que cada método haga lo indicado en el enunciado, si con eso pasas los tests públicos, y main.py corre sin problema. Es que estás muy bien encaminado.

Saludos! 🦖

**Comment by vhernnda** [comment]
duda resuelta

**Comment by MTGG123** [comment]
> Hola @vhernnda
> 
> Si, lo que mencionaba en el segundo párrafo era solo como una idea para mejorar la simulación. Lo importante es que cada método haga lo indicado en el enunciado, si con eso pasas los tests públicos, y main.py corre sin problema. Es que estás muy bien encaminado.
> 
> Saludos! 🦖

Holaa. A mi me pasa lo mismo pero además, aun cuando se roba la bandera y el jugador esta en los 100m, no finaliza el código. Tengo entendido que esto es porque, una vez que se logra robar la bandera, no se vuelve a verificar si ya llego a los 100m, por lo que puede empezar a ejecutarse otro thread que puede volver a robarla antes que se compruebe si la carrera finalizó ¿Esto también está bien, o hay que modificarlo para que se verifique si el jugador ganó después de robar la bandera? De igual manera me sale todo bueno en los tests. Gracias
![Captura de pantalla 2024-10-04 203038](https://github.com/user-attachments/assets/488406a7-fdaf-4286-a8a7-0292b0f5d2de)
