### ISSUE TITLE
WARNING: CPU random generator seem to be failing, disabling hardware random number generation

### ISSUE THREAD

**Issue by lucasilabaca** [IIC2233/syllabus#428]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola!  Cada vez que corro algún código que requiere la librería PyQt5, ya sea en VS Code o en la consola del computador, se me imprime el siguiente error:

WARNING: CPU random generator seem to be failing, disabling hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff

De igual manera se abre la ventana y todo funciona bien, pero me molesta el error y me preocupa que más adelante no funcione algún módulo de PyQt5 u otra cosa.  Estuve investigando un poco y parece que tengo que actualizar BIOS, pero al intentarlo me advierten que puede tener efectos negativos en el PC.  ¿Ha pasado antes?  Si es así, ¿Cómo podría arreglarlo? ¿Actualizo el BIOS?  Gracias!

**Comment by aaossa** [comment]
Hola @lucasilabaca , tal como dices parecer ser un *bug* que debería desaparecer al actualizar la BIOS 🤔 No es algo que haya visto antes en el curso la verdad. Mi consejo es: si ahora puedes ejecutar aplicaciones en PyQt, entonces actualiza la BIOS después de la actividad (para no perder tiempo de estudio), pero si ahora te aparece un error (no una advertencia o *warning*) que te impida probar tu código mejor actualizarla ahora 🤔
