### ISSUE TITLE
Error de Formato al entregar Diagrama de Clase

### ISSUE THREAD

**Issue by AlonsoZamorano** [IIC2233/syllabus#428]
Buenas tardes
Al subir mi pdf con el avance de diagrama de clases descubrí que al descargarlo de draw.io se exportó en un formato extraño, en el que se dividieron en varias planas la todo mi diagrama haciendo dificil su lectura si es que no se ve de manera completa. ¿Que ocurre si hago otro commit si es que quiero corregir el formato?, ¿o es mejor dejarlo tal cual envie?

**Comment by mmunozmendez** [comment]
Hola, la hora de entrega era a las 20:00, y los archivos que estaban en ese momento son los que se revisarán. Éxito!
