### ISSUE TITLE
Fecha de Entrega Diagrama de Eventos

### ISSUE THREAD

**Issue by jnhasard** [IIC2233/Syllabus#429]
Hola, quería pedir en el nombre de varios compañeros si es posible que se corra la fecha de entrega del diagrama de eventos para el fin de semana, ya que varios de nosotros tenemos prueba de Calculo III el jueves y de Termodinámica el viernes. Nos harían un gran favor.

Saludos

**Comment by Hernan4444** [comment]
Todos aquellos que tengan el mismo problema **con alguna de esas dos pruebas** por favor denle :+1:  al comentario de @jnhasard. Así podemos revisar el quorum de su solicitud y discutirla.

Saludos!!

**Comment by flobarrios** [comment]
Hola! Queda para el viernes a la 23:59. No podemos darles mas plazo ya que la idea es que antes de partir programando, ordenen bien los eventos y piensen como se debe realizar la
simulación. Además, la idea es que el feedback esté el domingo por lo que si les damos mas tiempo no podremos cumplir con esto.

Saludos!

**Comment by diegonavarrovergara** [comment]
Hola, se me olvidó por completo que había que entregar el diagrama. Hay algo que pueda hacer? Lo puedo subir a algún otro lado? Gracias.

**Comment by Hernan4444** [comment]
@diegonavarrovergara lamentablemente tu diagrama esta fuera de plazo y eso se verá reflejado en la nota de esta tarea.

Saludos!

**Comment by acrojas2** [comment]
Hola:
@flobarrios Te quería preguntar cuando subirán el feedback de los diagramas de eventos, ya que estoy un poco confundida con la tarea (sobre todo con lo de las actualizaciones en los eventos)  y quizás con el feedback podría (yo y todos los que estemos confundidos) resolver varias dudas. 
Saludos! :B

**Comment by flobarrios** [comment]
@acrojas2 aun falta que algunos ayudantes den su feedback pero voy a hacer una issue con los que tenemos hasta el momento !
