### ISSUE TITLE
Eliminar Lables y Rects.

### ISSUE THREAD

**Issue by Alonsinho1** [IIC2233/syllabus#429]
Hola tengo una pregunta, lo que pasa es que necesito borrar labels y rects para realizar el inventario. SIn embargo no he podido encontrar en internet como puedo borrar rects y lables. Podria ocupar hide() para los labels. Sin embargo, el rect seguiria ahi. 

Intente crear una lista de labels y de rects y luego vaciarla. Sin embargo estos siguen ahi.

Hay alguna forma?

**Comment by robertov1** [comment]
Hola!

Una manera de hacerlo es cambiar las dimensiones del Qrect por ejemplo a (1,1) y moverlo a (1,1). Y para los labels usar hide()

Esta forma debería servir para lo que quieres hacer. Ojalá te sirva. 

Saludos!
