### ISSUE TITLE
Error en realizar todas las consultas

### ISSUE THREAD

**Issue by mora4** [IIC2233/Syllabus#429]
Hola, 

No se por qué me esta levantando este error cuando pongo "Realizar toda las consultas" en la interfaz:

![image](https://user-images.githubusercontent.com/37154386/39630561-0ba5a968-4f86-11e8-8439-3c1041b0ecb6.png)

Cuando lo hago con las consultas seleccionadas sí funciona.

Gracias

**Comment by Hernan4444** [comment]
@mora4 ya hay una issue sobre eso, por favor no abrir otra con el mismo tema.
