### ISSUE TITLE
solucion error _pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by vhernnda** [IIC2233/Syllabus#429]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Este error me sale al intentar deserializar un bytearray segun lo pedido en la actividad 5 para deserializar_tortuga y no tengo ni la mas minima idea de como resolverlo

**Comment by Hernan4444** [comment]
Hola @vhernnda 

Ese error es porque estás intentando deserializar un _bytearray_ que no es posible entender para `pickle`. Por ejemplo, si serializamos algo y a alteramos el _bytearray_, puede que ya no se puede deserializar:

```python3
numero_serializado = pickle.dumps(4444)
print(numero_serializado) # b'\x80\x04\x95\x04\x00\x00\x00\x00\x00\x00\x00M\\\x11.'
fragmento = numero_serializado[:4]
pickle.loads(fragmento) # Aquí saldrá error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.UnpicklingError: pickle data was truncated
```

Otro error posible que puede surgir es el siguiente: 
```python3
numero_serializado = pickle.dumps(4444)
print(numero_serializado) # b'\x80\x04\x95\x04\x00\x00\x00\x00\x00\x00\x00M\\\x11.'
fragmento = numero_serializado[1:]
pickle.loads(fragmento) # Aquí saldrá error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.UnpicklingError: invalid load key, '\x04'.
```

En el primer caso, como eliminamos los últimos 4 bytes, `pickle` ya no sabía como entender todo el mensaje, mientras que en el segundo caso, como eliminamos el primer byte, `pickle` no sabe como procesar ese inicio de mensaje.

Ambos se resumen en que lo recibido ya no es posible procesar. En terminos de la AC, probablemente algún paso de la desencriptación no está 100% correcta y por lo mismo ya no es capaz de obtener a la `Tortuga`. 

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad (de la otra semana 🙈)! 🦖
Saludosヾ(＾-＾)ノ

**Comment by vhernnda** [comment]
duda resuelta
