### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type QLabel has been deleted

### ISSUE THREAD

**Issue by Iawinter** [IIC2233/syllabus#429]
Intento eliminar QLabels mediante deleteLater, pero al intenterlo me aparece el error "RuntimeError: wrapped C/C++ object of type QLabel has been deleted" y no he encontardo una respuesta en Internet al problema. A que se puede deber?

**Comment by jjzapatai** [comment]
Hola, tengo el mismo error, pero para mi escena con Qgraphics: al hacer self.scene.removeItem(self.moneda), me sale el siguiente error: RuntimeError: wrapped C/C++ object of type Moneda has been deleted. Tampoco pude solucionarlo con google. 
Mi  moneda aparece y desaparece con un QTimer y este error me sale cuando cierro sesion y saco todo lo que hay en la ventana para ir a la ventana de Menu.

**Comment by VicenteMerino** [comment]
Yo lo que hice es tratar esa sentencia con ty/ecept, espero les sirva, en general me funcionó bien.
