### ISSUE TITLE
Sobre cómo se realizan los cambios de líneas en tareas

### ISSUE THREAD

**Issue by antoniafuica** [IIC2233/syllabus#429]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Tengo una duda sobre el cambio de líneas en la recorrección. Quería saber si puedo agregar líneas a mi código en vez de sólo cambiar una. 
Además, no me queda claro cómo indicar qué línea tengo que cambiar. Tengo que subir un nuevo código? O en el form indicar que línea cambiar?

**Comment by Sofia-Arratia** [comment]
Hola @antoniafuica ! El cambio de líneas en una tarea se refiere tanto a modificar una línea como a borrar o agregar otras líneas, cualquiera de estas tres cuenta como *un* cambio de línea dentro del máximo de 20.
Por otro lado, hay dos formas en las que puedes indicar los cambios de línea que requieres que se le realicen a tu programa. La primera es indicarlo en tu README.md si aún estás dentro de su plazo de entrega. La segunda es, como dices, a través del form de recorrección, indicando el índice de las líneas que quieras cambiar (o las líneas entre las que quieras colocar líneas nuevas), especificando exactamente de qué manera se debe realizar el cambio, es decir, escribiendo las líneas.
Espero esto te haya aclarado tus dudas ☺️
