### ISSUE TITLE
Tiempo de ejecucion de tests en computador viejo

### ISSUE THREAD

**Issue by waknaudt** [IIC2233/Syllabus#429]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, cual es el estandar que se utilizara para el tiempo de los tests? porque en mi computador varios test dan mas de 20 segundos, pero probe en otro computador y todos dan menos de 20 en ese. No hay un estandar mas objetivo para saber si se tendra descuento o no?

**Comment by Jeremiah-PHP6** [comment]
¡Hola! No debería ocurrir que se tarde más de 20 segundos en correr los tests, incluso si tu computador es viejo. Puede ser que estés instanciando muchas cosas innecesarias y la memoria se consuma más rápido (esto no es mucho problema para un pc más rápido, pero igual te recomiendo corregirlo).

Trata de refactorizar el código y que se demore lo menos posible. Cualquier cosa me consulltas 😃
