### ISSUE TITLE
map ayudantía

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#429]
En la ayudantía hay muchos casos como este:
return sum(map(lambda x: x, self.tiempo_espera_cola))
No entiendo para que usamos el map y no directamente el sum

**Comment by nebil** [comment]
Efectivamente, en aquellos casos, yo pienso que es posible aplicar la función `sum` directamente, de forma equivalente. De hecho, ese `lambda` está actuando como [función identidad](https://en.wikipedia.org/wiki/Identity_function), que es capaz de transformar _equis_ en… _equis_. Lo que, ciertamente, es una no-tan-apasionante labor para `lambda`.

Buen hallazgo, Mauricio. :wink:

---

Aprovecho este _issue_ para comentar que, mientras leía el código, encontré _snippets_ como…

```python
return max(map(lambda x: x.tiempo, self.platos))
```

Sin embargo, siento que es más pitonesco escribir…

```python
return max(p.tiempo for p in self.platos)
```

Y esto es análogo para todos los `map` que son inmediatamente entregados a `min`, `max`, `sum`.

:snake: [#pythonic](https://www.python.org/dev/peps/pep-0020/) :snake:
