### ISSUE TITLE
Distribución de puntajes

### ISSUE THREAD

**Issue by nicogrecod18** [IIC2233/syllabus#429]
Hola, les escribo ya que en el enunciado sale: 
"Cuando se publique la distribución de puntajes, se señalará con color amarillo cada ítem que será evaluado a nivel de código, todo aquel que no esté pintado de amarillo significa que será evaluado si y sólo si se puede probar con la ejecución de su tarea. En tu README deberás señalar el archivo y la línea donde se encuentran definidas las funciones o clases relacionados a esos ítems"
Quería saber donde puedo encontrar (o si no lo han subido aún) el archivo o página donde salga la distribución de puntajes. Gracias de antemano.

**Comment by Dnpoblete** [comment]
Hola @nicogrecod18, la distribución de puntajes fue subida el 7 de abril a canvas, de todas formas acá te dejo el [link](https://docs.google.com/spreadsheets/d/15SDoSSz9VINHPLQwmdgAIT_0-A2eDpvHsk3cTLGfXG0/edit#gid=0).

Éxito con la tarea! ✨

**Comment by nicogrecod18** [comment]
mala mía, se me fue buscar en canvas. Gracias por la respuesta (y el link)
