### ISSUE TITLE
Configurar pycodestyle

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#43]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

## Pregunta

Programando luego de instalar pycodestyle como linter en vscode (como pedían en la configuración inicial del curso), me he dado cuenta que hay muchos errores que me distraen, y preferiría que se ignorase el error del máximo de 79 líneas, por ejemplo.
Buscando solo logré llegar a [esta página](https://pycodestyle.pycqa.org/en/latest/intro.html#configuration) y explican como configurar el archivo y parece fácil pero sigo sin entender dónde está ese archivo o cómo llegar a él.

Por favor, si alguien sabe cómo hacerlo, agradecería un monton.

**Comment by BenjaRubio** [comment]
que es eso del pycodestyle? donde lo pedian?

**Comment by ajuanchuto** [comment]
¡Hola! 

En la [wiki](https://iic2233.github.io/wiki/) del curso puedes encontrar todo lo que te piden, en el apartado _setup para el semestre_. (En respuesta a  @BenjaRubio)

En general el archivo `pycodestyle.py` se guarda por default en una carpeta relacionada a _site-packages_ de Python, Te recomiendo buscar en la carpeta donde tengas descargado Python. Te mando la ruta que yo tengo en mi pc para que te hagas una idea:  `C:\Users\pc\AppData\Roaming\Python\Python37\site-packages`.  
Una vez que encuentres el archivo, ábrelo con tu editor de código y va a haber una variable llamada `max-line-length` y es ahí donde tienes que cambiar el número al valor que tu quieras o puedes seguir las instrucciones de la página que enviaste.

PD: Recuerda que el largo máximo de una línea es parte de PEP8 y por ende te descuentan en tareas si no lo cumples (revisa la [guía de estilos](https://github.com/IIC2233/syllabus/blob/main/Tareas/Descuentos.md#pep8-hasta-4-d%C3%A9cimas-pencil2) para ver las reglas de manera más detallada. Yo te recomiendo que no lo desactives, pero lo configures según lo que te pide el curso.

Cuéntame si te sirve 😄
