### ISSUE TITLE
Duda con paths modulo cambair_planos

### ISSUE THREAD

**Issue by jisalasc** [IIC2233/Syllabus#43]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Tengo una duda sobre el uso de paths, en el modulo de cambiar_planos, estuve con un problema, ya que al correr los test publicos (en este caso el 9), siempre me detectaba que no existian los archivos, sin embargo al crear un archivo de prueba en el vscode, este si me detectaba la existencia de archivos. Para hacer los path use la libreria os, y eran exactamente las mismas rutas para la pestaña de pruebas como para la red.py (donde se modifica el modulo). Para que funcione, copie y pegue el test_09 de la carpeta de test publicos (subcarpeta de T1) , directamente en la carpeta T1 de mi repositorio, y al estar a la "misma altura" que la data (donde estan los archivos) si me funcionaron los test en el terminal, intuyo que el problema, era que los test antes estaban en una carpeta "mas profunda" que los archivos, por lo que me pregunto si es **correcta esa manipulación, o definitivamente debo arreglar algo en los path para que la tarea se corrija bien**

**Comment by CrisHD935** [comment]
Hola! El test lo corriste individualmente dentro de la carpeta de tests o ejecutaste todos_tests.py? Porque tienden a haber problemas al ejecutar los tests directamente, por lo que recomiendo correr desde todos_tests.py. Por ejemplo, si quisieras correr el test 9 puedes comentar todos los otros imports de test en todos_tests.py de tal forma que al correr el archivo solo corre el test 9 pero lo haces desde la carpeta T1. Si haces esto y te funciona, el error fue al correr dentro de una carpeta dentro de T1 y no te preocupes al respecto, no habrá problema con los paths a la hora de corregir la tarea. En el caso de que no te funcione lo que dije, entonces hay otro error con la modularización que debes revisar para que esté en buen estado la tarea a la hora de ser corregida. Saludos!

**Comment by jisalasc** [comment]
Excelente ahi me funciono sin ese error, muchas gracias.

**Comment by Hernan4444** [comment]
Hola @jisalasc 

Respecto a tu comentario

>  intuyo que el problema, era que los test antes estaban en una carpeta "mas profunda" que los archivos,

Justamente había un error en los tests por ese caso. Por si acaso revisar el comentario de la issue #42 que justo abordamos este problema e indico cómo solucionarlo (una solución es la mencionada en esta issue, pero agregué otra más).

Saludosヾ(＾-＾)ノ
