### ISSUE TITLE
Sobre el comportamiento de las casillas descubiertas.

### ISSUE THREAD

**Issue by ibgarrido** [IIC2233/Syllabus#43]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, mi duda es muy simple: al despejar una casilla que no contiene una bestia, se supone que se deben despejar todas las 8 casillas que rodean a la casilla seleccionada. Esto también incluye a las casillas que **contienen bestias de esas 8,** o esas deben permanecer ocultas como suele ocurrir en un buscaminas común y corriente?

**Comment by Lord-Kelsier** [comment]
Cuando despejas una casilla que no tiene bestia, se debe mostrar la **cantidad** de bestias que hay en las 8 casillas que la rodean y deben permanecer ocultas.
### Para el bonus (opcional)
Si hay 0 bestias alrededor, entonces debes descubrir las 8 casillas que la rodean
