### ISSUE TITLE
Eventos metereológicos sobre incendio

### ISSUE THREAD

**Issue by malopez16** [IIC2233/Syllabus#43]
Sobre los eventos que afectan en la proporción de propagación de los incendios:
Suponiendo que se puede "viajar en el tiempo" poniendo fecha y hora cualquiera en el inicio del programa y un incendio crece lo suficiente como para sobrelapar con distintos indicadores metereológicos del mismo tipo (ejemplo: Temperatura-Temperatura), ¿Cuál se respeta? o se asume que ésto no ocurrirá?

**Comment by Hernan4444** [comment]
@malopez16 

![image](https://cloud.githubusercontent.com/assets/15641721/23838334/59ef2344-0773-11e7-8094-8afbf9cea2d5.png)

saludos!! c:
