### ISSUE TITLE
Duda función "verificar_tortugas"

### ISSUE THREAD

**Issue by martinpena03** [IIC2233/Syllabus#43]
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](https://github.com/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

La función verificar_tortugas retorna la cantidad de tortugas que estén mal posicionadas.
En el siguiente caso, se considera 1 mal puesta (en posición [0,0] ), o las 3?

["T","T","-"]
["T","-","-"]
["-","-","-"]

**Comment by Hernan4444** [comment]
Hola,

Recuerda que la primera regla del foro es ver si alguien más preguntó esto 😄 . Si revisas la issue #28 verás que alguien ya preguntó sobre esto mismo con un caso similar al tuyo, y se le respondió su caso y se dió otro más.

Saludos c:
