### ISSUE TITLE
Subi el archivo sin usar gitignore. Como puedo revertir los errores que causo?

### ISSUE THREAD

**Issue by Alonsinho1** [IIC2233/syllabus#43]
Hola tal como dice el enunciado, subi el archivo sin usar gitngore. Como puedo revertir los errores que causo?. En la ayudantía dijeron que podíamos borrar lo que no sirve y subirlo nuevamente y luego subirlo nuevamente con el gitignore. Sin embargo, mencionaron que había otro metodo. Es esto posible o es mejor hacer lo que mencione anteriormente?

**Comment by jmwielandt** [comment]
Hola!

**El método más seguro** (con menos errores humanos y más fácilmente revertibles) es haciendo otra carpeta dentro de tu repo, pongámosle `trash` y poner todo lo que no quieras ahí. Luego, agregas esa carpeta a tu `.gitignore` y al hacer el siguiente commit en el log de git aparecerían los archivos como eliminados.

El método bonito usando git es ejecutar el comando `git rm --cached <nombres_archivos>`, sin embargo debes tener algunas consideraciones:
- Esto solo borra el trackeo de git sobre los archivos seleccionados, si no los agregas al gitignore, al hacer un nuevo commit se subirán de todas formas.
- Si no pones el `--cached`, en lugar de solo borrar el tracking del archivo, borrará el archivo (y no va a la papelera, se borra 4 evah~). ⚠️ ⚠️ 
- `<nombres_archivos>` son los paths absolutos o relativos a los archivos en cuestión, pero si son relativos es respecto al directorio en el que estás, esto es importante que lo tengas en cuenta, ya que puedes quitar archivos equivocados por accidente.

Un ejemplo sería, si estoy en la carpeta de mi entrega de la T00, 
```git
git rm --cached ./Enunciado.pdf ./archivo_malo.py ./archivo_malo_otro.py
```

Saludos!

**Comment by Alonsinho1** [comment]
Muchas gracias!
