### ISSUE TITLE
Duda sobre escritura en archivos (encomiendas.csv, reclamos.csv, ...)

### ISSUE THREAD

**Issue by SVenegasA** [IIC2233/Syllabus#43]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda 

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
Saludos
Quiero saber **¿Cómo lo hago para que cuando mi programa escriba texto en otro archivo (función write( ) ), lo haga en una línea siguiente (sin texto)?**
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by catalina-arcila** [comment]
Hola @SVenegasA, te recomiendo revisar los contenidos de Introducción a la Programación. Igual buscando por internet deberías poder encontrar formas de poder abrir/modificar archivos. Suerte!!
