### ISSUE TITLE
Orden de civilizaciones según PA o PD

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2233/syllabus#43]
Hola,
En la sección 4.3, el enunciado dice:
> Estas civilizaciones deben poder ordenarse de acuerdo a su PA o a su PD

Debo interpretar esto como que las civilizaciones se ordenan primero de acuerdo a su PA, y si hay un empate, de acuerdo a su PD?

**Comment by BFFV** [comment]
Hola!
Se debe dar la opción al usuario de elegir si quiere verlos ordenados por PA o PD, es decir, deben existir ambas opciones en el programa.
