### ISSUE TITLE
Diagrama de clases, atributos: subclases

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#43]
Tengo una clase madre con tres posibles clases hijas.
En otra clase, un atributo puede ser una de las tres clases hijas. En el diagrama de clases qué tipo de dato coloco en ese atributo que puede ser cualquiera de las tres clases hijas? ¿Pongo la clase madre?

**Comment by jecastro1** [comment]
Exacto.

Saludos.
