### ISSUE TITLE
Leer posts.csv

### ISSUE THREAD

**Issue by jtmeyer98** [IIC2233/syllabus#43]
Para leer los archivos "usuarios.csv" y "seguidores.csv" utilizo este código:

with open('nombredelarcivo.csv', 'r') as csv_file:
    csv_reader = csv.reader(csv_file)
    for row in csv_reader:
        print(row)

y funciona perfectamente, pero al leer "posts.csv" aparece el siguiente problema:

"C:\Users\Soledad\Desktop\Proyectos de Python\venv\Scripts\python.exe" "C:/Users/Soledad/Desktop/Proyectos de Python/TAREA0/posts.py"
Traceback (most recent call last):
  File "C:/Users/Soledad/Desktop/Proyectos de Python/TAREA0/posts.py", line 5, in <module>
    for row in csv_reader:
  File "C:\Users\Soledad\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1527: character maps to <undefined>

Process finished with exit code 1

Tengo los 3 archivos csv en la misma carpeta, junto con los archivos python. He buscado otros códigos para abrir csv, pero en todos me aparece el mismo problema.

¿Que puedo hacer?

**Comment by Tito0906** [comment]
Holaa @jtmeyer98, me parece que tu problema es el mismo que se trata y soluciona en la issue [https://github.com/IIC2233/syllabus/issues/16](url).

**Comment by benjavicente** [comment]
@jtmeyer98 ojo que los códigos y librerías externas pueden no servir bien para leer los "csv" porque los archivos que entregan [**no son realmente csv**](https://github.com/IIC2233/syllabus/issues/4#issuecomment-599834514).

También parece que estás usando el [módulo csv](https://docs.python.org/3/library/csv.html#csv.reader), que está [**prohibido para esta tarea**](https://github.com/IIC2233/syllabus/issues/4#issue-581237246).

**Comment by rpbarrera** [comment]
Escribe : with open('nombredelarcivo.csv', 'r', encoding="utf8") as csv_file:
Eso me funciono a mí.

**Comment by jtmeyer98** [comment]
Ok! Gracias!

Tengo otra pregunta, si tengo los archivos ".py" en la misma carpeta que los archivos ".csv" entonces ¿puedo leerlos de esta manera?

with open("usuarios.csv") as file:

¿o eso está mal?
Se que recomiendan utilizar la libreria "os" para hacer una ruta portable:
ruta_usuarios = os.path.join("jtmeyer98-iic2233-2020-1","Tareas","T00","usuarios.csv")

Pero si estoy en la misma carpeta no es necesario, de hecho aparece un error:
FileNotFoundError: [Errno 2] No such file or directory: 'jtmeyer98-iic2233-2020-1\\Tareas\\T00\\usuarios.csv'

Entonces, ¿Puedo leer los .csv de esta manera que me funciona? with open("usuarios.csv") as file:
¿O eso está mal y tengo que ocupar otra?

**Comment by Tito0906** [comment]
Holaa, si lo abres con  _with open("usuarios.csv") as file:_ no está mal pero es más recomendado acostumbrarse a hacerlo siempre con _os.path.join_ para ahorrarse cualquier duda o problema. 

Por otro lado, a tu código le faltan varios argumentos a la función _open_ (modo de lectura o encoding). Recomiendo que revises la bibliografía de esa función para no tener problemas. 

Por último, si ya estas en la carpeta con tus archivos la manera correcta seria _ruta_usuarios = os.path.join("usuarios.csv")_. Puesto que de otra forma estas usando un path incorrecto si lo ejecutas desde la carpeta T00.

Cualquier duda quedo atento.

**Comment by jtmeyer98** [comment]
Perfecto!! Muchas Gracias!! me quedo muy claro, y ya le agregue los argumentos faltantes.
