### ISSUE TITLE
Dudas Guía de Estilo

### ISSUE THREAD

**Issue by Dieguu21** [IIC2233/Syllabus#43]
### Prerrequisitos

* [x] Leí las reglas del foro
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido 
* [X] Mi duda no se trata de un tema administrativo o personal
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

me surgieron tres dudas con respecto a la guía de estilo.

#### Primera duda

mi primera duda es si este llamado a una función

```python
ejemplo(b='mundo', c=42, a='hola')
```

debería ser 

```python
ejemplo(b = 'mundo', c = 42, a = 'hola')
```

o está bien de la primera forma?

#### Segunda duda

mi segunda duda es si podemos nombrar a archivos como

`"Archivo de Python.txt"`

o debe ser

`"archivo-de-python.txt"`

o de alguna otra forma?

#### Tercera duda

mi tercera duda es si al usar números en `snake_case` debe ser `ejemplo_1` o `ejemplo1` ??

**gracias.**

**Comment by Maxy15** [comment]
Hola! En la primera duda, debería ser la segunda forma. En la segunda duda, se suelen nombrar del estilo snake case, es decir, archivo_de_python.txt. En la tercera duda, debe ser ejemplo_1. Espero te sirva 😸

**Comment by Dieguu21** [comment]
gracias.

😁
