### ISSUE TITLE
Plantar

### ISSUE THREAD

**Issue by fgallard** [IIC2233/Syllabus#43]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

No entiendo cómo funciona el plantar. Supuestamente se planta lo más arriba y a la izquierda que sea posible, no? Pero en los test case hay muchas plantaciones en las que el cultivo podría ponerse en otro lado, más arriba y más a la izquierda, y no está puesto en ese lugar. Me podrían explicar qué es lo que se necesita realmente?.

**Comment by pacalein** [comment]
Hola, para el método `Predio.plantar` solo estamos verificando que puedes plantar un código de cultivo en esas coordenadas específicas. Lo menciona en el enunciado respecto a qué parámetros recibe y cuál es el resultado esperado. Lo de plantar lo más a la izquierda superior es para el método `DCCultivo.buscar_y_plantar`, lo cual también está descrito en la explicación del método.

**Comment by fgallard** [comment]
> Hola, para el método `Predio.plantar` solo estamos verificando que puedes plantar un código de cultivo en esas coordenadas específicas. Lo menciona en el enunciado respecto a qué parámetros recibe y cuál es el resultado esperado. Lo de plantar lo más a la izquierda superior es para el método `DCCultivo.buscar_y_plantar`, lo cual también está descrito en la explicación del método.

Sí. A eso me refería. Al buscar y plantar, y el screenshot corresponde a los testcase de buscar y plantar.

**Comment by jtvvtj** [comment]
al final esto era un error o no?, ya que como decía el compañero, los testcase son de buscar y plantar. Y como aún siguen apareciendo lo mismo en el test, queria saber si en realidad era un error o no?
