### ISSUE TITLE
Escribir archivos solo cuando salgo del sistema?

### ISSUE THREAD

**Issue by ptflores1** [IIC2233/Syllabus#43]
> Salir del sistema: Cuando un usuario desee dejar de utilizar el sistema, el programa debe cerrarse y todos los cambios realizados deben actualizarse en los archivos de texto correspondientes. Esto quiere decir guardar las orders que haya realizado el usuario.

Entonces, **solo** cuando se sale del sistema se deben actualizar los datos? o puedo actualizar los datos en el mismo momento en que se ingrese una orden?

**Comment by stephichau** [comment]
Puedes actualizar los datos cuando quieras, pero ten en consideración que si dejas todo para cuando uno sale del sistema, si se cae el programa no se actualizarán los archivos :).

**Comment by ptflores1** [comment]
Ok Gracias !
