### ISSUE TITLE
nuevo formato CSV 

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#430]
hola, no entiendo cual fue el nuevo formato que implementaron. ¿Cuál es la diferencia?
Hasta el momento he usado el antiguo formato y todo me funciona bien. 

saludos

**Comment by amparostevens** [comment]
Hola @enriquemolinare !

El cambio fue que se eliminaron espacios en blanco que quedaron el archivo, lo que añade un paso extra a trabajar con los archivos (hacerle un strip). 

Podrías probar si es que tu tarea funciona tal como está con la versión nueva y en caso de no funcionar (si no quieres modificarla), puedes poner en tu README que utilizaste la versión antigua y se te corregirá con esa :tada:

**Comment by enriquemolinare** [comment]
perfecto, yo voy había hecho el strip. Lo voy a intentar de todas maneras con el nuevo. 

Gracias
