### ISSUE TITLE
problemas con tildes al leer archivos

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#430]
A pesar de que estoy usando with open('genomas.txt', 'r', encoding = 'utf-8') as gen, me lee cosas como SÃ¡nchez en vez de Sánchez.

**Comment by mjgutierrez1** [comment]
ahora funciona, no sé que había pasado

**Comment by Arcoirisky** [comment]
Quizás corrías una versión sin utf-8 😅
