### ISSUE TITLE
Combinacion de teclas en keypressEvent

### ISSUE THREAD

**Issue by nhorellana** [IIC2233/syllabus#430]
Hola! Estoy haciendo la parte de "cheat codes" para lo que tengo que mezclar una combinacion de teclas, esto lo hago con  keyPressEvent, donde el evento lo coomparo con una Qt.Key, pero no es posible hacerlo con mas de una tecla al mismo tiempo, busque soluciones usando QSequence o QKeysequence pero nada, alguna sugerencia?

**Comment by Hernan4444** [comment]
Hola

En esta issues #268 se habló de algo que te puede ser de utilidad. Cualquier duda hazla en esa para tener todo condensado en una issue.

Saludos ✌️
