### ISSUE TITLE
Columnas de 'movies.csv' 

### ISSUE THREAD

**Issue by papasconketchup** [IIC2233/Syllabus#430]
Hola,

Lo que pasa es que en el archivo "movies.csv", sale que la columna correspondiente al rating de "Rotten Tomatoes" es la 5ta columna. Ahora, en el enunciado sale que los rating de "Rotten Tomatoes" llevan el  #caracter "%", lo que según las columnas del archivo corresponde al rating de "Metacritic". Con cual nos quedamos??

gracias!

**Comment by diegoheg** [comment]
No soy ayudante :grin:, pero pregunte algo parecido en la issue #388, espero te sirva!!

**Comment by papasconketchup** [comment]
buena master, voy a guiarme por eso y por el enunciado
