### ISSUE TITLE
suposiciones ultima funcion

### ISSUE THREAD

**Issue by M4TI4D4CZ** [IIC2233/Syllabus#430]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda sobre la ultima funcion (que supongo que piede extrapolarse a otras). Que pasa si luego de buscar votos validos no encuentro ninguno? debo retornar un generador vacio o puedo asumir que siempre existir'a al menos un voto valido. Finalmente, tambien puedo asumir que lso generadores animales, distritos, locales y ponderadores tienen toda la informacion para cada voto, por ejemplo, todos los locales posibles de los votos, y a su vez para sus distritos o cada especie de animal con su ponderador correspondiente?
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Jeremiah-PHP6** [comment]
¡Hola! En general, debes retornar un generador vacío si es que no hay votos válidos. En el caso particular de la función `votantes_validos_por_distritos`, en el caso de que no hubieran votos válidos en ningún distrito, entonces por vacuidad todos los distritos empatan con el máximo de votos (que es cero), y debes elegir el de menor id de entre todos.

Sobre tu otra duda, sí, puedes asumir que los generadores entregados tienen toda la información necesaria al momento de buscar los id.

Espero haberte ayudado, saludos.

**Comment by M4TI4D4CZ** [comment]
gracias
