### ISSUE TITLE
Ejercicio 2.2 semana 6 (Cambiar tamaño de Widget al usar QVBoxLayout( )

### ISSUE THREAD

**Issue by claxon16** [IIC2233/syllabus#430]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Quise hacer el ejercicio 2.2 de la semana 6 con QVBoxLayout y QHBoxLayout para que los widgets cambiaran su posicion al abrir la ventana, pero cuando ponía una imagen con ese método, daba igual el valor que le agregaba en setGeometry al label de la imagen, siempre aparecía del mismo tamaño. No se cómo cambiar eso o si es que lo estoy implementando bien .

**Comment by Pablok98** [comment]
¡Hola!
Lo que está pasando es que, cuando agregas una _widget_ a un _layout_, el _layout_ pasa a "controlar" el tamaño de las _widgets_ que contiene. En otras palabras, la imagen ya no decide su tamaño :O sino que el `QVBoxLayout` (o `QHBoxLayout`). 

Por defecto, si no haces nada más que agregar _widgets_, el _layout_ intentará que cada elemento ocupe el mismo espacio, a través de todo el espacio disponible. Por ejemplo, si agregas 3 imágenes a una caja horizontal, cada imagen tendrá un tamaño de 1/3 de la ventana y juntas ocuparán toda la ventana.

Algunas formas de cambiar este comportamiento son:

 - Definir un tamaño máximo y/o mínimo de la imagen, utilizando `.setMinimumSize(ancho, alto)`
 - Definir un tamaño inmodificable para la imagen, utilizando `.setFixedSize(ancho, alto)`
 - Cambiar los parámetros del _Layout_. En este caso, te recomendaría revisar la documentación.

Espero que esto responda tu duda, cualquier cosa me puedes responder por acá. Suerte! 🥕

**Comment by claxon16** [comment]
Muchas gracias! Ahí pude cambiarlo
