### ISSUE TITLE
Abrir ventana de juego desde la de inicio.

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2233/syllabus#430]
Holaa, tengo un problema, lo que hago en la ventana de inicio es aplicar un condicional a si esta o no el mapa pedido, y en caso de que la respuesta sea si, instanciar la clase que posee la interfaz del mapa. 
Cuando corro el programa, se abre la ventana pero se cierra al instante de haberse abierto, alguna ayuda ? 🤕

**Comment by lucastack** [comment]
Hola!
A veces pasa porque no agregas el objeto (como tu interfaz, en este caso) como un atributo de la clase que lo instancia. Otra forma de hacerlo podría ser usar señales y trabajarlas independientemente
