### ISSUE TITLE
Testeo

### ISSUE THREAD

**Issue by behrmann97** [IIC2233/Syllabus#431]
No entiendo a qué se refiere con 'todas deben probarse con un caso y en dos de ellas probar dos casos de uso distintos'. :D

**Comment by Arcoirisky** [comment]
Intenta leer con calma esa parte del enunciado 😅 La frase completa es:
>Para testear las consultas, todas deben probarse con un caso y en dos de ellas probar dos casos de uso distintos.

**Comment by Bneya** [comment]
@Arcoirisky ¿con "dos casos de uso" significa simplemente probarlo dos veces con inputs distintos para esa consulta?

**Comment by Sforrego** [comment]
@Arcoirisky tengo la misma duda, a que se refiere especificamente con "de uso distintos".

gracias :)

**Comment by PIPEAPABLAZA** [comment]
@Arcoirisky  tengo la misma duda!

**Comment by Arcoirisky** [comment]
Perdón por la demora 😅 Se refiere a eso mismo. Ahí pueden probar con dos casos distintos,  sus excepciones 👀👀, eso prácticamente.

**Comment by Sforrego** [comment]
jajajaja ok!
gracias :D
