### ISSUE TITLE
Dos backend/frontend

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#431]
Hola, es posible hacer dos archivos de backend y frontend cada uno para respetar el largo de líneas?

**Comment by DCCollao** [comment]
Hola! 
El concepto de frontend y backend es solo eso: un **concepto**
El que tengamos dos archivos separados para programas pequeños no quiere, de ninguna forma, decir que **siempre** deban ser solamente dos archivos. Esto es sólo una consecuencia de que nuestro programa sea corto, y no requiera de mayor modularización.

En particular, respecto a tu pregunta, en [contenidos semana 9](https://github.com/IIC2233/contenidos/blob/master/semana-09/5-diseño-front-back.ipynb) hay más detalles.
