### ISSUE TITLE
movimiento fluido sprite

### ISSUE THREAD

**Issue by F-arellano** [IIC2233/syllabus#431]
al tratar de realizar un movimiento continuo el label se queda fijo hasta que se ejecuta todo el codigo, para luego al final ubicarse en las coordenadas de destino. con algunos prints pude comprobar que si estan ejecutandose las ordenes pixel por pixel, pero por alguna razon solo se visualiza la ultima, alguna idea de que podria ser?

**Comment by pwillmer** [comment]
Probaste añadiendo self.label_personaje.show() cada vez que se actualiza la posición del personaje?

**Comment by F-arellano** [comment]
Ya había probado y no resulta. Intenté creando un nuevo label o actualizando el que ya existía, pero en ambos casos solo me muestra el estado final del personaje sin los estados intermedios (he confirmado con prints que la información que luego seteo en el label se va actualizando de forma fluida así que no se por que no resulta)

**Comment by gatochico** [comment]
Hola! Podrías subir tu tarea con el error a tu repo privado para ver en detalle el error :eyes:? (E idealmente decirnos donde están las líneas problemáticas si tienes muchos archivos!)

**Comment by F-arellano** [comment]
Ya lo solucione (aunque no estoy seguro porque). ya que al mandar la información del back end al front end solo me mostraba el estado final, se solucionó tomando N = 1 como parámetro de movimiento

**Comment by sebacarrasco** [comment]
Hola, me pasa exactamente lo mismo y no sé cómo solucionarlo. Por ejemplo, si la velocidad de movimiento es 50 me aseguré con prints de que el label y sus parámetros como el pixmap y posición cambiaran 50 veces, sin embargo la imagen se actualizaba solo al final del ciclo.
