### ISSUE TITLE
Duda funcion pedido_con_mayor_descuento_utilizado_cargar_datos

### ISSUE THREAD

**Issue by juanriveraf** [IIC2233/Syllabus#431]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/421)).
* [ x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](420)).
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo una duda sobre la funcion pedido_con_mayor_descuento_utilizado. En el enunciado sale que esta funcion tiene que devolver un iterable. Esto significa que la funcion puede retornar una lista por ejemplo, o tiene que ser si o si un iterable generado por alguna de las funciones nuevas vistas en clases. Muchas gracias.

**Comment by NachoRinda** [comment]
Hola, detectamos un problema con los tests. En general, deberían poder pasar sin importar si retornas una lista o directamente desde las funciones que se vieron en clase (map/filter). Así que, respondiendo tu pregunta, si puedes retornar una lista pero igualmente te recomiendo esperar a la actualización de los tests para no trabajar sobre estos desactualizados.

**Comment by juanriveraf** [comment]
Realmente lo estaba haciendo una lista porque no era posible retornarlo de la otra forma (saltaba error en los test cases).  Asi que muchas gracias!
