### ISSUE TITLE
Caso empates en función ganadores_por_distritos()

### ISSUE THREAD

**Issue by nicolasvialy** [IIC2233/Syllabus#431]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Al correr los test en la función generadores_por_distrito no me corren en los que hay empates. En estos casos de empate, que candidato debo retornar? Supuse que era el con mayor id pero no estoy seguro.

**Comment by TomasGMDC** [comment]
@nicolasvialy en caso de empate, se devuelven ambos candidatos.

**Comment by ooscarr** [comment]
eso era, ahí funcionó. El enunciado decía "En caso de empate entre dos o más candidatos más votados, se considera como más votado al **candidato** con mayor id."
