### ISSUE TITLE
Avance tarea

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2233/syllabus#431]
Ya entregué el diagrama, pero aun me falta el markdown de la explicación. Sin embargo, me llego el mail del commit que se va a considerar. Ya no puedo subir el markdown?

**Comment by baosse** [comment]
Holaa Jorge! 
Aún puedes subir el markdown para facilitar la corrección de tu diagrama de clases, sin embargo este no contará como parte de la entrega del avance:(
Mucho éxito!✨

**Comment by jorge-ovalle** [comment]
Pucha, pero no se avisó a qué hora iba a cerrar. Solo aparecía el día. Asumí que era hasta las 23:59 hrs

**Comment by baosse** [comment]
Estaba al principio del enunciado que era hasta hoy a las 20'00 hrs:(
