### ISSUE TITLE
Agregar atributos a subclases de clases abstractas

### ISSUE THREAD

**Issue by jnbaltra** [IIC2233/syllabus#431]
Hola, si quiero agregar un atributo a una subclase de una clase abstracta, cual sería la forma mas simplificada? (no haciendo overriding)

Me imagino como con un 
def __init__(self, parametros, nuevo_atributo)
    super().__init__(parametros)
    self.nuevo_atributo = nuevo_atributo

pero no estoy seguro, quedo atento, saludos!

**Comment by jeschuwirth** [comment]
Hola @jnbaltr,

El ejemplo que colocaste es exactamente lo que tienes que hacer.

Te recuerdo que para agregar atributos no es necesario hacerlo en el init (pero si es muy recomendado), podrías hacer:

```
class Hijo(Padre):
    def init(self, parametros)
        super().init(parametros)

a = Hijo(parametros)
a.nuevo_atributo = nuevo_atributo
```

Éxito!

**Comment by jnbaltra** [comment]
muchas gracias!
