### ISSUE TITLE
Como deshago el upgrade de pyqt5-tools??

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#431]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Como deshago el upgrade de pyq5t-tools?
Durante la ayudantia nos pasaron un codigo para actualizar el pyqt5-tools desde la consola, este era: ```pip install pyqt5-tools --upgrade```,  y lo instale, pero antes de aplicar el comando podia abrirlo solo con escribir designer en el CMD o escribiendo designer en la parte de arriba de las carpetas y ya no puedo. Antes era mucho mas comodo, como puedo configuralo o volver a como era antes?

**Comment by Ignacioislae** [comment]
Sino por ultimo como puedo borrar el pyqt5 y su configuracion?

**Comment by Sofia-Arratia** [comment]
Hola @Ignacioislae ! Para instalar una versión específica de cualquier paquete utilizando pip (en este caso, la versión anterior que tenías de pyqt5-tools), se sigue el siguiente formato: `pip install NombrePaquete==(versión_paquete)` o bien, si ya tienes el programa instalado, `pip install --upgrade NombrePaquete==(versión_paquete)` (que upgrade no te confunda, puede ser usado para upgrade o downgrade). Lamentablemente para eso necesitarás saber cuál era la versión que estabas usando anteriormente, ya que hasta donde se y he podido buscar, no existe manera de volver a una versión anterior así nomás. Sin embargo, entiendo que antes podías encontrar el programa tipeando `designer` en la cmd, intenta ahora con `pyqt5-tools designer` a ver si te funciona, en ese caso la versión que tienes quedaría casi tán accesible como la anterior.
Cuéntame cómo te va ☺️
