### ISSUE TITLE
razón existencia Mini_database

### ISSUE THREAD

**Issue by Felipehanckes** [IIC2233/Syllabus#431]
Tengo todas mis funciones definidas con un parametro Folder, ya que no se si en algun momento deberan usar la Mini_database, y esto me enreda un poco el codigo en general, de aquí mi pregunta.

¿Para que nos pasaron el MiniDatabase? 
¿Es necesario que lo utilicemos o que lo instanciemos de alguna forma especial en una consulta?

No encontre una respuesta en el enunciado ni en otras issues. Solo en la que hablan de usarlo para el testing.
Gracias

**Comment by Hernan4444** [comment]
@Felipehanckes MiniDatabase es solo otra base de dato más pequeña donde puede verificar rapidamente si las consultas arrojan el resultado que quieres. Puedes usarlo o no en tu tarea.

Saludos ✌️
