### ISSUE TITLE
Contradiccion  enunciado Excepciones

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#432]
Hola en este enunciado
 " una librería levanta excepciones mientras que los usuarios que utilizan la librería son los que capturan los errores. Sólo se permitirá que su librería capture las excepciones definidas en
este punto; capturar cualquier otra excepción será penalizado."
se da a entender que las librerias solo pueden levantar excepciones y no capturarlas pero luego se contradice dicendo que  la libreria solo puede capturar tales excepciones. Entonces no me queda claro si la libreria solo puede levantar la excepcion o tambien puede manejarla.

**Comment by Hernan4444** [comment]
También se permite manejarla, pero esa frase es para que no abusen de manejar todas las excepciones que ocurran, solo las 3 descritas en el enunciado.

**Comment by sjkinast** [comment]
Entonces en una consulta si tengo un Movie error en un parametro yo debiese pararla y que el resultado de la consulta sea un error que se muestre en pantalla o debiese capturar el mismo error en la libreria seguir con los otros elementos de la consulta y ademas mostrar que hubo un error en pantalla.

**Comment by Hernan4444** [comment]
Debes parar **esa** consulta y  resultado es el error. Si yo ejecuto una lista de consultas, si la consulta 3 tiene error, esa consulta tendrá como resultado, el error, pero las siguientes consultas deberán ser analizadas. El programa no puede parar solo por error de una consulta

**Comment by sjkinast** [comment]
OK gracias , entonces si se cae por ejemplo filter_by _date en esta consulta anidada ["successful_actors", ["filter_by_date", ["load_database"], 2015, True]] succesful_actors no se ejecuta.
Lo otro que no me queda claro es que siguiendo la logica que planteas, cada vez que yo lea el archivo de actores por ejemplo dado que hay uno con N/A , la consulta nunca tendra un resultado si es que yo tengo que leer a todos los actores .

**Comment by sjkinast** [comment]
Pero si estoy en una consulta que tiene como objetivo retornar actores, y para obtener los actores que cumplen el criterio verificar si alguno de ellos es un error tengo que revisar todas las peliculas(y estan si tienen errores en sus argumentos en r_type o en date, etc ), en este caso los errores de las peliculas debiesen ser manejados con try y except con objetivo de seguir con la consulta y ver si los actores tienen errores o a penas encuentra un error en las peliculas debo de igual forma lanzar una excepcion y parar la consulta.

**Comment by Hernan4444** [comment]
¿Porque tienes que revisar todas las películas? Si yo por ejemplo logré filtrar exitosamente 5 películas y a esas te pido sus actores, tu librería debe ser capaz de solo procesar la información relacionada con esas 5 películas y los demás actores ignorarlos. Si dentro de esas 5 películas hay algún Actor que N/A, ahí si se genera el error. Tienes que ver bien que datos tu consulta en verdad va a utilizar y cuales son descartados inmediatamente.

Otro ejemplo, supongamos que filtro y obtengo todas las películas del 2000 (suponiendo que las fechas están bien). Si yo te pido los actores de esas películas, entonces tu librería solo va a procesar los actores de las películas del 2000, todos los demás actores serán ignorados.

**Comment by Hernan4444** [comment]
La idea es que quede ordenado sus archivos, con el módulo interfaz yo me refería al modulo de la demo.py que les dimos. Si crees que desde la demo.py se pueden llamar los métodos de un interfaz directamente y atrapar las excepciones, no hay problema. El fín de modularizar es que quede un código ordenado para quien lo lee (en este caso nosotros los ayudantes) y así poder encontrar y entender de forma rápida lo que hicieron para poder evaluar.

Saludos ✌️
