### ISSUE TITLE
ambigüedad sobre función max_locales_distrito

### ISSUE THREAD

**Issue by cholalat** [IIC2233/Syllabus#432]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Para la función max_locales_distrito cuál es el punto de comparación que tengo que usar para ver si un local pertenece a algún distrito? Lo único que se me ocurre es usar la comuna, pero no veo por qué no podría pasar que 2 distritos pertenezcan a la misma comuna. muchas gracias.

**Comment by Jeremiah-PHP6** [comment]
¡Hola! La relación de pertenencia es al revés: un distrito tiene a una (o más comunas), pero una comuna pertenece a un **único** distrito. Por lo tanto, al verificar que el local pertenezca a un distrito, simplemente comparas los id_comuna de cada uno, y puedes asumir que el local pertenece a un único distrito.

Si algo no te quedó claro, no dudes en preguntarme. Saludos
