### ISSUE TITLE
parametros.py

### ISSUE THREAD

**Issue by Mario-uc** [IIC2233/syllabus#432]
No entiendo la creación e implementación de este archivo

**Comment by furcelay** [comment]
Hola, 
No soy ayudante pero por lo que entiendo aquí guardas todos los valores que son fijos en el programa pensando en que en un futuro puedas cambiarlos fácilmente sin tener que empezar a buscarlos en el código (principalmente los números en azul en el enunciado).

Por ejemplo, en vez de poner `self.sickles_iniciales = 500` en el `__init__`, puedes usar `self.sickles_iniciales = SICKLES_INICIALES` y defines `SICKLES_INICIALES = 500` en `parametros.py`.

**Comment by Dnpoblete** [comment]
Hola @Mario-uc, @furcelay  tiene razón, pero cerraré esta issue, ya que esta duda ya fue resuelta en la issue #278, para que la revises y en caso de dudas preguntes ahí, para que te ayudemos. Por favor para la próxima antes de hacer una issue revisar si ya se preguntó lo mismo en otra.

Éxito con la tarea! 😄
