### ISSUE TITLE
setText

### ISSUE THREAD

**Issue by Nitsuga69** [IIC2233/syllabus#432]
Hola!!
En mi tarea tengo varios QLabel y QPushButton y estoy continuamente utilizando setText para cambiar lo que muestran en la ventana al ocurrir un evento. El problema que estoy teniendo, es que con el setText no se me están cambiando de forma automática los textos, se mantiene el texto anterior hasta que haga algo fuera de la ventana. Por ejemplo, un QPushButton tiene como texto inicial "Iniciar sesión", luego de apretar el botón se llama a una función con un setText que le cambia el texto a "Cerrar sesión", pero este cambio no ocurre hasta que yo haga algún evento fuera de mi ventana creada, por ejemplo, si hago un click fuera de mi ventana (escritorio puede ser) el texto es recién cambiado a "Cerrar sesión". No sé si estoy utilizando mal setText o tiene un efecto tardío. Espero se haya entendido.

**Comment by gatochico** [comment]
Hola! Puedes subir la ultima versión de tu codigo a tu repo para echarle un ojo?

**Comment by Nitsuga69** [comment]
Listo!! En el archivo menu.py realizo el ejemplo que puse anteriormente.

**Comment by lily416** [comment]
Hola 😄 

Descargue tu repositorio, corrí el archivo `menu.py` y el texto del botón cambia correctamente cuando le hago click:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26393515/58431497-1fd71480-807c-11e9-99b3-740a009fdba4.gif)

Ánimo y éxito con la tarea. 👋 🐈🐧 

PD: Sería bueno que cambies el tamaño de los textos para que se pueda ver bien su contenido, para más información mira la issue #400.

**Comment by Nitsuga69** [comment]
Gracias!!! En mi computador me sale bien el tamaño, que raro.

**Comment by Nitsuga69** [comment]
<img width="872" alt="Captura de Pantalla 2019-05-27 a la(s) 12 50 37 p  m" src="https://user-images.githubusercontent.com/48293112/58431945-0cc54400-807e-11e9-8702-1eb4788bc0d4.png">
Yo lo veo así.

**Comment by Arcoirisky** [comment]
Podrías agregar en tu readme imágenes del como se ve y tú sistema operativo. Para que puedas seguir trabajando con tranquilidad y tener constancia del cómo lo ves tu.

**Comment by Nitsuga69** [comment]
Ok, gracias!!
