### ISSUE TITLE
drag.exec_() y forma apropiada de citar código de internet

### ISSUE THREAD

**Issue by burgosibarra** [IIC2233/syllabus#432]
Hola, para hacer drag and drop pensaba seguir este ejemplo (único comentario)
https://stackoverflow.com/questions/50232639/drag-and-drop-qlabels-with-pyqt5
Sin embargo, al final del código hace 
`drag.exec_(...)`
Por lo que tengo entendido los built-ins eval y exec están prohibidos, pero no sé lo que son ni que hacen así que nunca me he precupado de eso hasta ahora, y quería saber si esa parte de código tiene relación a eso.
Además, cuál es la forma apropiada de citar?
Desde ya, muchas gracias

**Comment by aljara97** [comment]
Hola, esta duda fue respondida en detalle en la issue #340 
Mucho éxito 🌽👨🏻‍💻

**Comment by aljara97** [comment]
Con respecto a la forma de citar código externo, no hay una forma estánda (puedes usar APA, ISO, etc), pero te recomiendo hacer lo siguiente:

En la sección **Referencias de Código Externo** de tu readme dar un detalle más específico sobre las líneas y el archivo en el que se implementa la función con una breve descripción de lo que hace, señalando el nombre del autor y el link exacto de donde fue obtenida.
Mientras que en el código antes de definir el método o función escribes la fuente con su autor como un comentario.

Por ejemplo en el caso que quieras citar la función ```factorial``` del link https://stackoverflow.com/questions/5136447/function-for-factorial-in-python

En tu código escribes:
```
# Código sacado de: "https://stackoverflow.com/questions/5136447/function-for-factorial-in-python", del comentario del usuario: "Jared Burrows"
def factorial(n):
    num = 1
    while n >= 1:
        num = num * n
        n = n - 1
    return num
```
Mientras que en tu readme:
Para realizar mi tarea saqué código de:
1.-  https://stackoverflow.com/questions/5136447/function-for-factorial-in-python
y está implementado en el archivo ```funciones.py``` en las lineas 10 a la 16, esta función se encarga de retornar el factorial de un parámetro n. 

Espero sea de ayuda para tu tarea 🎉🌽 :seedling:
