### ISSUE TITLE
Clase sin __init__

### ISSUE THREAD

**Issue by jnbaltra** [IIC2233/syllabus#433]
Se puede crear una clase sin definir un __init__?

tipo:
```python
class Clase1:

    def metodo_1(self):
        pass

    def metodo_2(self):
        pass
```
quedo atengo, saludos!

**Comment by CataSudo** [comment]
Hola, no soy ayudante pero se puede hacer! 
`class Clase1:
   def __init__(self):
       pass

    def metodo_1(self):
        pass

    def metodo_2(self):
        pass`
eso si, recuerda que para funcionar necesita instanciar elementos de otra clase! Espero que sirva

**Comment by jnbaltra** [comment]
Hola, muchas gracias! Con instanciar elementos de otra clase te refieres a hacer heredar a la Clase1?

**Comment by rieg-ec** [comment]
Por te sirve de ayuda (tampoco soy ayudante), si. Puedes hacerlo, y si tienes metodos dentro de ella que quieras ocupar puedes ocuparlos llamando a NombreClase.metodo(). Eso si, si la clase no tiene el metodo __init__() creado, no podras instanciarla (crear objetos a partir de ella).

**Comment by Dnpoblete** [comment]
Hola @jnbaltra, por favor antes de hacer una issue revisar si se preguntó lo mismo en otra, voy a cerrar esta issue, porque se pregunta lo mismo en la issue #425. En caso de seguir con la duda, pregunta en esa issue y te ayudaremos.

Éxito con la tarea! 😄
