### ISSUE TITLE
Qué significa usar space en vez de tab?

### ISSUE THREAD

**Issue by jearaneda** [IIC2233/syllabus#433]
Sé que es un poco tarde pero acabo de darme cuenta de que para pep8 piden "indentar con spaces en vez de con tabs" y no entiendo a qué se refiere eso

Normalmente lo que hago es dejar cuatro espacios (osea un tab) para indentar, así:

```
def mi_funcion(self):
    pass
```

¿hay una diferencia apretando 4 veces espacio versus apretar tab? La debe haber, por eso es una exigencia de pep8 pero cuál es?

gracias

**Comment by lily416** [comment]
Hola 😄 

Algunos editores de código setean automáticamente el `tab` como 4 espacios, pero puede darse que esté seteado como otro valor (i.e. 2 espacios) o como un `tab` (1 gran espacio de 4 espacios de largo), por lo que en esos casos deben cambiar el `tab` por 4 espacios.

Ánimo y éxito con la tarea. 👋 🐈🐧

**Comment by aaossa** [comment]
Solo para profundizar un poco más en la respuesta...

> Normalmente lo que hago es dejar **cuatro espacios (osea un tab)** para indentar, así:

4 espacios no son un tab, solo se ven iguales (en general... no siempre ha sido así). 

> ¿Hay una diferencia apretando 4 veces espacio versus apretar tab? La debe haber, por eso es una exigencia de pep8 pero cuál es?

Hay una diferencia pero primero responderé otra pregunta: 

> "¿Puedo mezclar tabs y espacios? Si puedo hacerlo daría lo mismo esto y no tendría que elegir". 

Bueno, eso es cierto, pero no se recomienda mezclar tabs y espacios por la respuesta a la primera pregunta: 4 espacios y un tab solo se ven iguales (y eso es cuando un tab tiene ese largo, podría tener la mitad o el doble, como dijo @lily416 ). Mira el siguiente código, es solamente abrir un archivo e imprimir sus contenidos:

![imagen](https://user-images.githubusercontent.com/10425834/58637401-69b03c80-82c0-11e9-96f3-f506af69ae2d.png)

¿Funciona? No. A pesar de que todo se ve bien, nos encontramos con el siguiente error al correrlo:

![imagen](https://user-images.githubusercontent.com/10425834/58637370-5c934d80-82c0-11e9-8889-ce33583819f0.png)

Como ya sabrás, la indentación es muy importante en Python. El "nivel de profundidad" en que empieza una línea de código define cuándo o cuántas veces se va a ejecutar.

```python
# Esto va a ejecutar los print 10 veces cada uno
for i in range(10):
    print(i)
    print(i)

# Esto solo ejecutará el primero 10 veces. El segundo una vez
for i in range(10):
    print(i)
print(i)
```

Lo que **no se ve** en el ejemplo de abrir el archivo es lo siguiente:

![imagen](https://user-images.githubusercontent.com/10425834/58637667-ff4bcc00-82c0-11e9-9be0-5ac97f9df64d.png)

Esos 4 puntitos de la línea 3 representan un espacio cada uno, mientras que la larga línea horizontal en la línea 2 representan un tab. ¿Se ven iguales? Sí. ¿Son iguales? No. Y Python 3 se da cuena de eso al ejecutar el código.

Y bueno, por esto es que no hay que mezclar tabs y espacios, porque no es una diferencia visible para el programador, solo para la máquina. **Es por esto que si vas a elegir entre tabs y espacios, solo se pide que seas consistente**.

Ahora, volviendo a tu pregunta original..

> ¿Hay una diferencia apretando 4 veces espacio versus apretar tab? La debe haber, por eso es una exigencia de pep8 pero cuál es?

Sí, hay una diferencia. ¿Por qué PEP-8 exigiría utilizar espacios por sobre tabs? [Respuesta corta](https://stackoverflow.com/a/121671/3281097): cuando se escribió PEP-8, los espacios eran la forma más popular de indentar, así que convengamos en que todos intentaremos usar espacios 😊 

**PS:** Si en algún momento hay tiempo, darle una mirada al [documento oficial de PEP-8](https://www.python.org/dev/peps/pep-0008/) podría ser interesante, permite entender las razones detrás de cada recomendación de estilo.
