### ISSUE TITLE
DELEGACIONES.CSV

### ISSUE THREAD

**Issue by mleon17** [IIC2233/syllabus#433]
Hola, no entiendo para que sirve el archivo delegaciones.csv

**Comment by mmunozmendez** [comment]
Hola!
El archivo delegaciones.csv contiene la información que debes cargar para crear las delegaciones con sus respectivos atributos. No debes modificarlo, solo leerlo.

**Comment by mleon17** [comment]
Pero al ejecutar el juego creo delegaciones nuevas, para que necesito la información de las delegaciones de ese archivo?

**Comment by mmunozmendez** [comment]
Las delegaciones deben ser creadas con la información del archivo, no debes inventarla.

**Comment by mleon17** [comment]
Ah entonces cada vez que creo una partida solo cambio los integrantes del equipo pero sin modificar el archivo delegaciones.csv? Porque el jugador debe ser capaz de elegir sus propios atletas. Y los valores como moral y dinero al iniciar una partida siempre son los que están establecido en ese archivo verdad?

**Comment by mmunozmendez** [comment]
Al crear la partida creas las delegaciones con los integrantes del archivo delegaciones.csv, después se pueden fichar más deportistas, pero siempre deben partir con los que indica el archivo. El jugador elige los atletas para competir en las distintas pruebas, para entrenar y para sanar.
