### ISSUE TITLE
Ejercicio property

### ISSUE THREAD

**Issue by jtvvtj** [IIC2233/Syllabus#433]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola no entiendo este problema del Midterm del 2023-2, por si alguien me lo podría explicar :)
![image](https://github.com/user-attachments/assets/d0030e18-1506-4974-b16d-a7818dcee6d1)

Principalmente me confunde cuando se define 'self.valor' dentro de la funcion 'def valor(self):'. Cuando se ejecuta la linea 'self.valor' que sucede?

**Comment by 3rdPix** [comment]
Las *properties* de una clase son, en el fondo, métodos que se ejecutan cuando la situación lo requiere. ¿Cuándo la situación lo requiere? dependerá de lo que estés haciendo con esa *property*. Los tres métodos asociados ocurren en los siguientes casos:

1. Método de acceso (`get`): ocurre cuando intentas leer, acceder a la propiedad de la instancia de la clase.
2. Método de escritura (`set`): ocurre cuando intentas asignar un nuevo valor a la propiedad en la instancia de la clase.
3. Método de eliminación (`del`): ocurre cuando intentas eliminar la propiedad de una instancia.

Estos tres métodos se definen respectivamente (utilizando la notación con decoradores) con

```python

# Método de acceso (el getter)
@property
def nombre_propiedad(): ...

# Método de escritura (el setter)
@nombre_propiedad.setter
def nombre_propiedad(): ...

# Método de eliminación (el deletter)
@nombre_propiedad.deletter
def nombre_propiedad(): ...
```

Es importante que entiendas que el intérprete de Python, lo que hará, es ejecutar **siempre** el método respectivo cuando intentes hacer la acción asociada a cada uno de estos métodos.

En el caso del ejercicio que presentas, el flujo que ocurre es el siguiente:

| Paso                                                                                                      | Explicación                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | `self._valor_secreto` |
|-----------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------|
| **1** (línea 17)                                                                                          | Instanciación de la clase. Aquí simplemente se le asigna el valor al atributo.                                                                                                                                                                                                                                                                                                                                                                                                                                              | 5                     |
| **2** (línea 18)                                                                                          | al ejecutar `caja.valor` estás intentando **leer** la propiedad con el nombre `valor` de la instancia, por lo tanto, se ejecutará el método asociado a la lectura (*getter*)                                                                                                                                                                                                                                                                                                                                                | 5                     |
| **2.1** (inicio ejecución del *getter*, línea 8)                                                          | Aquí estás intentando **asignarle** un valor a la propiedad, por lo que se ejecutará el método asociado (*setter*) con el argumento que esté a la derecha del *token* `=`                                                                                                                                                                                                                                                                                                                                                   | 5                     |
| **2.1.1** (inicio ejecución del *setter*, línea 14)                                                       | Recordando que el argumento que recibe el *setter* es el valor que estás intentando asignarle, te darás cuenta que el argumento que recibe este método es `self._valor_secreto + 1`, es decir, 6. Por lo que esta línea **imprime** 6.                                                                                                                                                                                                                                                                                      | 5                     |
| **2.1.2** (continua ejecución del *setter*, línea 15)                                                     | En este caso se modifica el atributo directo, por lo que no hay nada raro por debajo que se ejecute. Nuevamente, recuerda que el argumento **"valor"** en este momento es `self._valor_secreto + 1` (es decir 6). Por lo que ahora tendrás `self._valor_secreto += 6`, es decir, 11.                                                                                                                                                                                                                                        | 11                    |
| **2.2** (termina ejecución del *setter*, continúa el *getter*, línea 9)                                   | Solo **imprime** el valor del atributo, que como vimos en el paso anterior, es 11.                                                                                                                                                                                                                                                                                                                                                                                                                                          | 11                    |
| **2.3** (continua ejecución del *getter*, línea 10)                                                       | Retorna el atributo de la clase sin hacer modificaciones.                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | 11                    |
| **2.?** (qué ocurre con el valor retornado)                                                               | Nada! Recuerda que estabas intentando leer la propiedad `valor`, por lo que el método de la *property* te devuelve el valor, sin embargo, no estás haciendo nada con él, por lo que este paso queda en nada.                                                                                                                                                                                                                                                                                                                | 11                    |
| **3** (línea 19)                                                                                          | Estás intentando asignarle un valor a la *property*, por lo que se ejecutará el método *setter*. Sin embargo, ese método necesita un argumento, y da la casualidad que en el ejercicio de determinar cuál es el argumento que le estás pasando para que se le asigne, estás **leyendo** la *property* (recuerda que `a += 1` es una abreviación para `a = a + 1` por lo que `caja.valor = caja.valor + 5` necesita leer el valor de `caja.valor` primero), por ende, primero se ejecutará el método asociado a la lectura.) | 11                    |
| **3.0.1** (Determinación del nuevo valor que quieres asignarle, inicia a ejecutarse el *getter*, línea 8) | Se repite lo que ocurrió la última vez que llamamos a este método: Aquí estás intentando **asignarle** un valor a la propiedad, por lo que se ejecutará el método asociado (*setter*) con el argumento que esté a la derecha del *token* `=`                                                                                                                                                                                                                                                                                | 11                    |
| **3.0.1.1** (inicio ejecución del *setter*, línea 14)                                                     | Recordando que el argumento que recibe el *setter* es el valor que estás intentando asignarle, te darás cuenta que el argumento que recibe este método es  `self._valor_secreto + 1` , es decir, 12. Por lo que esta línea  **imprime**  12.                                                                                                                                                                                                                                                                                | 11                    |
| **3.0.1.2** (continua ejecución del *setter*, línea 15)                                                   | En este caso se modifica el atributo directo, por lo que no hay nada raro por debajo que se ejecute. Nuevamente, recuerda que el argumento **"valor"** en este momento es `self._valor_secreto + 1` (es decir 12). Por lo que ahora tendrás `self._valor_secreto += 12`, es decir, 23.                                                                                                                                                                                                                                      | 23                    |
| **3.0.2** (termina ejecución del *setter*, continúa el *getter*, línea 9)                                 | Solo **imprime** el valor del atributo, que como vimos en el paso anterior, es 23.                                                                                                                                                                                                                                                                                                                                                                                                                                          | 23                    |
| **3.0.3** (continúa ejecución del *getter*, línea 10)                                                     | Retorna el atributo de la clase sin hacer modificaciones.                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | 23                    |
| **3.1** (inicia ejecución del *setter*, línea 14)                                                         | Ahora que el intérprete conoce el nuevo valor que le quieres asignar a la propiedad (23 + 5 según lo que vimos), puede iniciar el método asociado a la asignación. En este caso solo **imprime** el nuevo valor que quieres asignarle, es decir 28.                                                                                                                                                                                                                                                                         | 23                    |
| **3.2** (continua ejecución del *setter*, línea 15)                                                       | En este caso se modifica el atributo directo, por lo que no hay nada raro por debajo que se ejecute. Lo que se tiene, recuerda, es `self._valor_secreto = self._valor_secreto + 28`, de modo que el valor final es 51.                                                                                                                                                                                                                                                                                                      | 51                    |

Como puedes ver, el intérprete tiene asociada la lectura al método respectivo, independiente de la lógica que pueda existir dentro de ese método, intentará ejecutarlo. Si sigues la línea de las veces que el flujo anterior **imprime** algo, notarás que la secuencia correcta es 6 11 12 23 28.

Espero esto haya aclarado tu duda! ^u^

**Comment by jtvvtj** [comment]
Holiii sí, me sirvió demasiado gracias, ahora lo entendí súper :). Perdón por la demora
