### ISSUE TITLE
popular_actors -> r_type

### ISSUE THREAD

**Issue by diegoheg** [IIC2233/Syllabus#433]
En el enunciado se da como ejemplo una consulta que tiene el parametro r_type = "RT" ¿Se refiere a "Rotten Tomatoes"? Ya que en todas las demás consultas el r_type de "Rotten Tomatoes" era "Rotten Tomatoes", por lo que estoy confundido si esta consulta recibe r_type de manera diferente a las demás consultas :confused:

**Comment by Hernan4444** [comment]
Te recomiendo revisar el enunciado, se especifica eso antes de empezar a mencionar cada consulta.

**Comment by diegoheg** [comment]
Realmente no 😟 
![screenshot_1](https://user-images.githubusercontent.com/26411041/39646016-6ffdefe0-4fb0-11e8-99bd-b95f84082489.png)
![screenshot_2](https://user-images.githubusercontent.com/26411041/39646019-738a2548-4fb0-11e8-9310-10f5050ed975.png)

**Comment by mblejeune** [comment]
@diegoheg en la pagina 6 sale que se puede llamar por su nombre alternativo que es RT! :)

**Comment by diegoheg** [comment]
@mblejeune Gracias!!!! te pasaste
