### ISSUE TITLE
promedio

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#433]
el promedio del ramo es el mismo del nuestro cierto?
y se reprueba de la misma forma tambien cierto?

**Comment by sebacruzd** [comment]
**Si no aparece en el enunciado** puedes asumirlo o hacer supuestos, mencionándolos en el README.md
Saludos!

**Comment by Dunkan1** [comment]
ok, gracias

**Comment by sebacruzd** [comment]
P.D: Siempre y cuando estos supuestos sean razonables. Si falta un detalle con el que no entiendes para nada y asumes que debes hacer algo totalmente distinto al enunciado, en ese caso es mejor preguntar.
