### ISSUE TITLE
Problemas con códigos del notebook de contenidos semana 6

### ISSUE THREAD

**Issue by AlfonsoBadilla** [IIC2233/syllabus#433]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Al correr el código no se encuentran los módulos

Cuando intento correr el código de las ventanas me arroja el siguiente error, acabo de desinstalar y volver a instalar pyqt5 y pyqt5-tools como dato.

Gran nombre del .py jsjsj

![Screenshot (120)](https://user-images.githubusercontent.com/80863383/117073805-70dbf280-ad00-11eb-813a-a65dc1e57cc1.png)

**Comment by Pablok98** [comment]
¡Hola! Pensando que podrías tener el mismo error de la *issue* #434, te hago las mismas preguntas:

1. ¿Este error te sale cuando corres un el programa desde consola? ( me refiero fuera de VSCode)
2. ¿Tienes más de una instalación de Python? **¿En algún momento has instalado anaconda?**

Quedo atento a tu respuesta 😀

**Comment by AlfonsoBadilla** [comment]
BuEnAsssss

Me sale el mismo error al correrlo desde la consola yyyyy solo he tenido python, lo instalé al principio del curso.

**Comment by Pablok98** [comment]
Algo que podríamos ver son las variables de entorno. 

Puedes crear un archivo de Python, importar `sys` y luego escribir `print(sys.path)`. Luego por favor sube una foto de lo que te sale.

Alternativamente puedes hacer la siguiente serie de comandos en la consola:
`python`
`import sys`
`print(sys.path)`
 Y mandarme el resultado.

**Comment by AlfonsoBadilla** [comment]
Esto arrojó al hacer la serie de comandos en la consola

![Screenshot (121)](https://user-images.githubusercontent.com/80863383/117188087-a9d0a180-adaa-11eb-8753-0e0d3af258f2.png)

**Comment by Pablok98** [comment]
Se bien, por lo que tendremos que probar algunas cosas:

1. ¿Instalaste pyqt5-tools? Si es que no, utiliza el comando `pip install pyqt5-tools` y prueba nuevamente.
2. Puede que alguna actualización de Windows haya afectado. Una opción que en general podría funcionar es simplemente reinstalar python. Para esto, **desinstala primero el que tienes actualmente** (puedes ir a programas de Windows y desinstalarlo como cualquier otra aplicación). Luego, reinstala python 3.7 igual que antes, acuerdate de chequear la opcion de agregarlo al PATH. Instala los paquetes con pip y debería funcionar.

Si aun tienes problemas, porfavor escribeme.

**Comment by AlfonsoBadilla** [comment]
Hay una advertencia que me sale, lo subí en la issue #432 . No sé si tenga que ver, reinstalaré python ahora.

**Comment by Pablok98** [comment]
Viendo eso, es totalmente probable que tengas problemas con las dependencias. Ten harto cuidado al reinstalar Python, procura desintalar usando el desinstalador que trae. Procura agregar python al PATH también. Cualquier cosa estoy atento!

**Comment by AlfonsoBadilla** [comment]
Ya reinstalé python y sigue igual, arroja los mismos errores, el inicial de esta la issue y el de la issue que cité en el comentario anterior:(

**Comment by Pablok98** [comment]
Que raro. Que te sale en consola si pones el siguiente comando:

`py -0`

**Comment by AlfonsoBadilla** [comment]
Sale esto...

![Screenshot (122)](https://user-images.githubusercontent.com/80863383/117193219-97f1fd00-adb0-11eb-96be-a3c72a434bb7.png)

**Comment by Pablok98** [comment]
¿Y con `pip list`?

Sobre eso que comentas que antes podías abrir ventanas bien, es lo que me lleva a pensar que una actualización de Windows pueda haber hecho algo. Por eso me pareció raro que reinstalar python no haya funcionado.

**Comment by AlfonsoBadilla** [comment]
Con pip list sale una lista enorme, no sé que mandar je

![Screenshot (123)](https://user-images.githubusercontent.com/80863383/117193822-51e96900-adb1-11eb-964c-c36603dac2d6.png)

**Comment by Pablok98** [comment]
Esto me ayuda de hecho. Se supone que reinstalaste python, pero veo que tu instalacion que estas utilizando en consola tiene paqueres como *scipy* o *scikit*. A menos que hayas instalado esas librerias recien, significa que definitivamente tienes alguna instalación de python por ahí escondida. 

¿Qué proceso seguiste para desinstalar python? ¿Estas seguro que no has instalado anteriormente, para otro ramo, python o conda? Algunos ramos como optimización lo utilizan.

**Comment by Pablok98** [comment]
¿Qué te sale si usas el comando `pip3.7 list`?

**Comment by AlfonsoBadilla** [comment]
True, me pareció raro que siguieran si estaba recién instalado se supone pero igual asumí que así debía ser

Ahora, si instalé otra versión de python, al inicio del curso porque fallé con la versión, sin embargo, me preocupé de desinstalarla o eso creo. Para desinstalo, fui al panel de control, click izquierdo y desinstalar.

**Comment by Pablok98** [comment]
Cuando desinstalaste al inicio del curso, ¿desinstalaste con el desinstalador? Es posible que no se haya borrado bien, y hayas estado usando todo este tiempo otro python :O

**Comment by AlfonsoBadilla** [comment]
Eso no es lo mismo que desde el panel de control? Al hacerlo así lleva a un desinstalador aparte de python pero no sé si es lo mismo.

**Comment by Pablok98** [comment]
Claro. Por casualidad, ¿no te sale más de un desinstalador? Algo que podrías probar es volver a borrar el python que instalaste recien y luego hacer `pip list`. Si te sale algo, es porque tienes una instalación de python definitivamente.

E

**Comment by AlfonsoBadilla** [comment]
Y de ser así y ver que sigue habiendo "otro python", como lo encontraría para desinstalarlo? Porque solo me deja desinstalarlo una vez

**Comment by Pablok98** [comment]
Si es que el comando `pip list` sigue funcionando, podrías localizar tu instalación de python con el comando `where python.exe` en la consola

**Comment by AlfonsoBadilla** [comment]
Desinstalé el python que acabo de instalar y ahora me dice que no existe, que lo instale.

Sobre ```pip list``` dice " 'pip' is not recognized as an internal or external command,
operable program or batch file. " no hay, no existe paizon.

a

**Comment by Pablok98** [comment]
En el primer pantallaso que subiste (el de `sys.path`), está la siguiente ruta:
`C:\\Users\\badil\\AppData\\Roaming\\Python\\Python37\\site-packages`
¿Sigue existiendo esa carpeta? (Tienes que habilitar poder ver las carpetas escondidas para entrar a *appdata* desde el explorador de windows)

**Comment by AlfonsoBadilla** [comment]
Uhhhh si está, existe y tiene cosas dentro.

**Comment by Pablok98** [comment]
Yap. ¿Te parece que nos comuniquemos por discord para solucionarlo? Tu caso es bastante específico. Hablame, mi usuario es San Ahoria.

**Comment by AlfonsoBadilla** [comment]
Voy
