### ISSUE TITLE
Ventana tienda superpuesta

### ISSUE THREAD

**Issue by tomasalvarez13** [IIC2233/syllabus#434]
Hola, en varias partes de la planilla de distribución de puntaje para esta tarea dice 'Los elementos no se superponen entre si'. Esto se refiere a que por ejemplo la ventana de la tienda no puede superponerse a otra ventana? O en este caso específico si seria valido?

**Comment by aljara97** [comment]
Hola @tomasalvarez13 al mencionar en la pauta que los elementos no se superpongan entre sí, se refiere a que cada elemento de **una ventana en específico** debe ocupar su espacio correspondiente y no debe tener otros elementos encima, independiente de los parámetros a escoger.

A modo de ejemplo revisemos el item *Ventana de Juego*, en este se evalúa el siguiente punto:
- Información indicada en el enunciado se muestra en pantalla. Los elementos no se superponen entre sí.
Este punto se refiere a que debes mostrar todos los elementos necesarios para esta ventana, ocupando **cada uno un espacio correspondiente**. Es decir, no debes tener *stats* en el área del mapa,  tampoco sobre un botón u otro elemento, puedes guiarte por las figuras 6, 7 y 8 del enunciado, en donde se muestra a cada elemento en su espacio correspondiente dentro de *una ventana*, sin considerar la interacción con otras.

Espero haber aclarado tu duda, suerte con tu tarea 🌱 🌽
