### ISSUE TITLE
Consistencia de días

### ISSUE THREAD

**Issue by JoseTomasSoto** [IIC2233/syllabus#434]
hay un num par de dias...
y un dia es solo de Menu de entrenamiento o Simular competencia...
esto seria que los dias "Impares" fueran de entrenamiento y los "Pares" de competencia

y en los dias que son de entrenamiento...se puede fichar, sanar, etc las veces que uno quiera o solo una vez??

gracias

**Comment by jitorcas** [comment]
Hola! @JoseTomasSoto 

El número total de días (`DIAS_COMPETENCIA`) **siempre** será **par**. Si comienzas a contar del día 0, el flujo sigue la siguiente secuencia:

**DÍA 0: Entrenamiento** 
Puedes realizar todas las acciones que **no están ligadas** a la competencia en sí. Como por ejemplo: fichar nuevos deportistas, sanar deportistas lesionados, comprar tecnología, etc. Estas acciones las puedes realizar las veces que quieras, **siempre y cuanto** tengas los recursos suficientes para poder efectuarlas. 

El transcurso al día de competencia se ejecuta cuando el entrenador del equipo decide **Simular la competencia**.

**DÍA 1: Competencia**
Los días de competencia solo se compite, donde cada delegación escoge a los deportistas que participarán en cada deporte y se simulará la competencia. 

El transcurso al nuevo día de entrenamiento (si es que quedan `DIAS_COMPETENCIA`) se realiza una vez se determinan los ganadores de cada deporte. 

Espero haya quedado más claro, si tienes cualquier duda avísame!
Éxito en la tarea! 🥇

**Comment by kalarconvl** [comment]
Hola! Me queda una duda sobre esto. Después de mostrar los resultados de un día de competencia se vuelve al menú principal. Acá el usuario puede elegir mostrar estado, volver a inicio, salir, ir al menú de entrenador o simular competencia. Como en teoría está en un día de entrenamiento debería ir al menú de entrenador, pero esto no es necesario o si? Si decide al tiro simular competencia es como que no hizo nada en el día de entrenamiento y salta al tiro al siguiente día de competencia? O hay que restringirlo? Y lo mismo al revés. Si escoge ir al menú de entrenador puede fichar, sanar y todas esas acciones del menú de entrenamiento. Una vez que decide volver al menú principal es como si entrara al siguiente día de competencia? Y qué pasa si decide volver al menú de entrenador? No entiendo esa dinámica de días 
@jitorcas

**Comment by jitorcas** [comment]
Hola @kalarconvl 

Efectivamente, los días transcurren únicamente si ocurre el evento que permite que pase al día siguiente. 

En el caso que estés en día de entrenamiento, solo pasas al día de competencia si el entrenador decide `simular la competencia`. El entrenador puede moverse por todos los menú y realizar las acciones que quiera (siempre y cuando tenga los recursos para poder hacerlo) sin restricción alguna. 

Por otro lado, al momento de finalizar las competencias se deben dar los resultados finales y automáticamente pasa al día siguiente. 

Avísame si quedan dudas! Mucho éxito! 🏋️‍♀️🏃🏻

**Comment by kalarconvl** [comment]
@jitorcas Entonces es como: Si está en el **Día 0: Entrenamiento** puede moverse por el menú principal y de entrenador cuando quiera. Una vez que escoge simular competencia pasa al **Día 1: Campeonato**. Cuando termina la simulación y se muestran los resultados pasa automáticamente al **Día 2: Entrenamiento**. Y cuando es día de entrenamiento entonces puede no hacer nada con el menú de entrenador y simular competencia al tiro?

**Comment by jitorcas** [comment]
@kalarconvl 

Así es! No pudiste haberlo dicho mejor 👌🏻

**Comment by kalarconvl** [comment]
@jitorcas Muchaas gracias! 😄
