### ISSUE TITLE
Aumento salud total Docencio

### ISSUE THREAD

**Issue by rmaguilera** [IIC2233/syllabus#434]
Hola, cada vez que Docencio alimenta a una de sus criaturas su salud total aumenta en 5? o esto es una única vez?

**Comment by mpsubiabre** [comment]
Hola @rmaguilera !

Lo unico que sucede una unica vez es la habilidad especial. El aumentar la salud  en 5 al alimentar es cada vez :)


Exito con la tarea! 😄

**Comment by rmaguilera** [comment]
pero es salud total verdad? no salud actual?

**Comment by mpsubiabre** [comment]
Hola @rmaguilera !

Sii, puntos de salud totales :)

**Comment by iankreisberguc** [comment]
Hola, puede este nuevo Puntos_salid_total, superar el rango de salud total de una criatura, (Ej: Augurey (35,45)), o llegaría a un tope de 45 (en el ejemplo) ?

**Comment by mpsubiabre** [comment]
Hola @iankreisberguc,

Como se respondio en al issue #289 , si se puede superar, puede llegar al infinito :0
