### ISSUE TITLE
respuestas múltiples para la misma consulta

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2233/Syllabus#434]
Hola,

1)  cuando pregunto por popular_actors, si tengo muchas películas y pocos actores, y todos están 1 vez por película, ¿no importa cual o cuales retorne?  ya que todas las películas están en la misma categoría "top n populares" o se espera que retorne el o los actores de la película más popular primero 

2) lo mismo me pasa con best comments, si "n" es mayor que el numero de películas con comentarios (pos o neg), las películas restantes a retornar podría ser cualquiera ya que todas poseen 0 comentarios o no debo retornar películas sin comentarios. Por otro lado, si tengo m películas con x comentarios c/u con m>n, ¿No importa cuales películas retorne?

**Comment by Hernan4444** [comment]
@joaquineichholz ante esos casos donde hay como un empate en los resultados obtenidos, queda a tu criterio como lo enfrentas.
