### ISSUE TITLE
Duda sobre funciones externas a consultas

### ISSUE THREAD

**Issue by MTGG123** [IIC2233/Syllabus#434]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).x
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/421)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado dice que podemos crear funciones aparte en un modulo distinto al de consultas, pero dado que estamos trabajando con programación funcional ¿Estas funciones externas pueden contener for o while?

**Comment by FradexMF** [comment]
Hola @MTGG123!
Para esta tarea **no** está prohibido el uso de ciclos y demás.
En su defecto, se corregirá la tarea con test de carga, que medirán la eficiencia de su código en archivos de tamaños muy grandes, es por esto que te recomendaría intentar evitarlos lo más posible.

Espero que haya quedado claro, ¡suerte!
