### ISSUE TITLE
Problema con la importación de módulos de Pyqt5

### ISSUE THREAD

**Issue by josefinamoenne** [IIC2233/syllabus#434]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola.

Instale pyqt5 tal como lo indicaban las instrucciones para windows (pip3 install pyqt5 y luego pip3 install pyqt5-tools), se da a entender que se instaló correctamente, aunque me aparecieron unos avisos de 'WARNING' que no supe interpretar, no sé si esto puede ser la fuente de mi problema. 

La cosa es que me corre bien en VSCode poner  import PyQt5, pero cuando quiero importar un mó

dulo no los reconoce, por ejemplo: from PyQt5.QtWidgets import QWidget, QApplication, me muestra el siguiente error: ImportError: DLL load failed: No se puede encontrar el módulo especificado.

*este es el warning que me mostró en la instalación:
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: C:\Users\56998\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Include\UNKNOWN
sysconfig: C:\Users\56998\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Include
WARNING: Additional context:
user = True
home = None
root = None
prefix = None

**Comment by Pablok98** [comment]
¡Hola!
Tengo dos preguntas para partir identificando cuál podría ser el problema:

1. ¿Este error te sale cuando corres un el programa desde consola?
2. ¿Tienes más de una instalación de Python? ¿En algún momento has instalado anaconda?

Quedo atento a tu respuesta 😀

**Comment by josefinamoenne** [comment]
1. Si, también me sale desde la consola
2. Si, tengo instalado la versión 3.8 y anaconda.. pensé que esto no había afectado porque cuando me instale Pyqt5 desde la consola me salía un mensaje lleno de "python3.7" asique asumí que se me había instalado para esta versión.

**Comment by Pablok98** [comment]
Es altamente probable que anaconda esté causando el problema. Te recomiendo desinstalar anaconda y reinstalar python de cero, siguiendo el wiki del curso. **Ten mucho cuidado con desinstalar anaconda usando su desintalador, y no simplemente borrandolo**.
