### ISSUE TITLE
incoherencia tests 07 pizza con ingrediente cargar datos

### ISSUE THREAD

**Issue by xperseosses** [IIC2233/Syllabus#435]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/421)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, en este test debería buscarse solamente el ingrediente "champiñones", pero realmente tambien se incluye "salsa de champiñones"

<img width="597" alt="Captura de pantalla 2024-10-01 a la(s) 11 39 56 p  m" src="https://github.com/user-attachments/assets/50f29244-178d-405a-83d2-443948f568a8">
<img width="1202" alt="Captura de pantalla 2024-10-01 a la(s) 11 40 56 p  m" src="https://github.com/user-attachments/assets/42f2218e-c8e9-4b9e-91b9-dac2bc0f4799">

**Comment by NachoRinda** [comment]
Hola, efectivamente este test tiene un comportamiento no esperado. Gracias por hacerlo notar. El equipo está trabajando en actualizar el test para que no suceda.

**Comment by canija2000** [comment]
Hola , aún no arreglan esto? O la salsa de champiñon va a contar como champiñon ?

**Comment by NachoRinda** [comment]
Hola, "champinones" y "salsa de champiñones" son dos ingredientes distintos. Desconozco exactamente cuándo van a actualizar los tests pero no se guíen por este test en particular mientras siga así.
