### ISSUE TITLE
def keyPressEvent

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2233/syllabus#435]
hola, estoy intentando modelar el movimiento del personaje, y me ocurre lo siguiente, creo el metodo y en una señal emito el event.text() que me entrega presionar una tecla, le puse un print para ver si me leia el teclado y lo hace, pero cuando debiese irse al metodo del back-end se cierra el juego o se termina el programa, porque pasa esto ??

de antemanos, muchas gracias.

**Comment by gatochico** [comment]
Hola! ¿Estás utilizando el código entregado en los contenidos para debuggear tu programa? Si no es así, lo adjunto a continuación:
```
if __name__ == '__main__':
    def hook(type, value, traceback):
        print(type)
        print(traceback)
    sys.__excepthook__ = hook

    app = QtWidgets.QApplication([])
    ventana = MiVentana(*args)
    ventana.show()
    app.exec()
```
Este código en teoría debería darte el error que causa que el programa se caiga, y posiblemente darte una pista para empezar a solucionarlo. Si aún así no puedes solucionarlo, sería ideal que nos comentes que error te lanza para poder ayudarte!

Quedamos atentos :0

**Comment by DiegoPibe** [comment]
Siiiiii con eso me sirvioooo... gracias !!!.
