### ISSUE TITLE
No usar 2 generadores

### ISSUE THREAD

**Issue by Matias449** [IIC2233/Syllabus#435]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/396)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/395)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Mi duda es si en una función de la parte de 2 generadores, solo ocupo uno en la función, ¿es una respuesta válida?, o se deben utilizar si o si los dos generadores entregados como argumento?

**Comment by victoriaatria** [comment]
Hola @Matias449 ! Recuerda siempre leer las issues pasadas para evitar preguntas duplicadas. Como se mencionó en la issue #427  , sí es válido no usar todos los argumentos de las funciones. Quedo atenta si tienes más dudas :)
