### ISSUE TITLE
Se considera comentarios en límite de líneas de la función?

### ISSUE THREAD

**Issue by Calomi** [IIC2233/Syllabus#435]
eso, más que nada para dejar bien claro que hacen las cosas o como (por si llegan a revisarlo) y así no ponerse a explicar tantas cosas en el readme 
por ejemplo:

```python
def fuu(si: object,on: object):
    """
    esta función fusiona
    a si con on
    """
    if si+on
    (...)

*linea17:* return sion
```

o con "#" aunque no esto no lo he usado pero = por curiosidad:

```python
def buu(uu: classrandom):
     do algo con uu
     #explicacion entremedio

```

**Comment by IchottMano** [comment]
@Calomi Hola!

Los comentarios **no** cuentan dentro del límite de 15 líneas, por lo que la función que propones estaría correcta.

Saludos!
