### ISSUE TITLE
Separar acciones con comas en misma linea

### ISSUE THREAD

**Issue by pdesolminihac** [IIC2233/Syllabus#435]
Esta permitido
`if cond:
    hacer_esto, hacer_esto_tambien`
?

**Comment by FernandoPieressa** [comment]
Hola!

Lo que estas planteando no cumple con las reglas de PEP-8. Las declaraciones compuestas como la que consultas son una mala practica.

Si:
```
if foo == 'blah':
    do_blah_thing()
do_one()
do_two()
do_three()
```
No:
```
if foo == 'blah': do_blah_thing()
do_one(); do_two(); do_three()
```

Puedes leer mas de pep-8 en este [link](https://www.python.org/dev/peps/pep-0008//). En la sección "Compound statements" se encuentra lo que acabo de explicar.

Saludos!
