### ISSUE TITLE
Uso abreviaciones en parametros.py

### ISSUE THREAD

**Issue by rmaguilera** [IIC2233/syllabus#435]
Hola, los nombres de los parametros pueden estar como abreviaciones? por ejemplo COSTO_ENERGIA_ALIMENTAR abreviarlo como CT_EE_ALIMENTAR??

**Comment by furcelay** [comment]
Hola!
No soy ayudante, pero creo que esto no es una buena idea porque haría que únicamente tú puedas comprender el código, si un ayudante lo lee no va a saber a qué corresponde la variable (y no es la idea solucionar todo con comentarios...). Entiendo tu problema porque está muy complicado hacer que las líneas no pasen de 100 caracteres :sob:

**Comment by rmaguilera** [comment]
Gracias por la comprensión 😭, se agradece jajajaja 😄

**Comment by Dnpoblete** [comment]
Hola @rmaguilera, lo recomendable es que no realices abreviaciones, pero en el caso de querer hacerlo en casos como si en ves de probabilidad_enfermas pone p_enf se entiende lo que es y no hay problema.  De todos modos sería bueno que los expliques en el ReadMe, para que el ayudante lo entienda y en ese caso no hay problema con que lo hagas :smile:. Como dato adicional, puedes hacer uso de diccionarios en parametros.py, para que revises la issue #422   que te tal vez te pueda servir!

Espero haber ayudado y éxito con la tarea! ✨
