### ISSUE TITLE
Nombre entrenador rival

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2233/syllabus#435]
Hola!
¿El nombre del entrenador rival debe ser elegido por el usuario? ¿O queda a nuestro criterio el nombre que toma?
En caso de que quede a nuestro criterio, ¿podríamos hacer una función que eligiera de manera aleatoria entre los nombres de los profesores de las secciones 😁? 
Saludos :)

**Comment by vsantelicest** [comment]
Hola!
En el enunciado no se aborda en específico el origen del nombre del entrenador rival, por lo que queda a criterio tuyo como hacer esa parte de la tarea. Debido a esto, no habría problema con crear una función que eligiera el nombre de manera aleatoria, tal como lo señalas, siempre y cuando lo especifiques en tu Readme! 💯
