### ISSUE TITLE
Camino mas corto 

### ISSUE THREAD

**Issue by jitorcas** [IIC2233/syllabus#435]
Hola! corriendo el backtracking del camino más corto se demora mucho en darme las rutas. Para mejorar el rendimiento del programa ¿puedo dejar la ruta en parámetros dependiendo del mapa? (ademas de dejar explicado en el README como se debe conectar la función para que de una ruta en un mapa nuevo)
Otra pregunta, el enemigo Kamikaze en el camino más corto solo debe explotar cuando llegue a la base? o cuando pase al lado de una torre también explota? muchas gracias!

**Comment by Arcoirisky** [comment]
Hola!

Sobre la primera pregunta ¿por qué no le echas un ojo a la materia de grafos? Quizás ahí puedas encontrar una forma más eficiente de solucionar tu inquietud.

Hay muchas formas distintas para encontrar el camino más corto pero aplicando la materia podrás con eso :DD cualquier duda siempre estaremos para responder :D

**Comment by jitorcas** [comment]
Hola! si lo hice con grafos, pero para hacerlo mas real, vi todas las posibles soluciones, si tengo 4 casillas de "S" y 4 casillas de "B" calculo todos los posibles caminos desde cada "S", o sea 16 BK y luego selecciono el de menor largo, y eso demora aproximadamente 3 - 5 min.

**Comment by mjgarrido1** [comment]
Hola! tambien lo intente con la materia de grafos, y se demora demasiado :(, puedo dejar la funcion y comando de como calcularlo/aplicarlo pero no ejecutarlo?

**Comment by Arcoirisky** [comment]
Realmente, eso es mucho tiempo. hay ténicas enseñadas que son más eficientes. Podrían buscar entre las issues de google una llamada "camino más corto" que ahí se explica otro algoritmo enseñado en el material.

De todas formas, aunque se demore se aceptará pero existe la posibilidad de que no se de todo el puntaje asociado si hay mapas en los que se demore mucho más :(

**Comment by Arcoirisky** [comment]
![D660F6E6-7FE1-49F5-AC53-86979FE46DC9](https://user-images.githubusercontent.com/26121402/58433271-63ce1780-8084-11e9-8d8c-9d542f441a9b.jpeg)

Por ejemplo uno así (disculpad la calidad)

**Comment by jitorcas** [comment]
@Arcoirisky se demora mucho porque es un camino de dos casillas, cambié el mapa a un camino de una casilla y se demora considerablemente menos, y es porque los nodos son no dirigidos. La verdad no se si existe una manera de dirigir los nodos, sin alterar posibles caminos. 
En la foto que enviaste, es un posible camino que vaya por toda la orilla, ya que son caminos de dos casillas y el BK lo busca igual :/

**Comment by jmwielandt** [comment]
Hola!

Les recomiendo tener cuidado con no repetir estados (estado = un enemigo en una casilla)

Saludos.
