### ISSUE TITLE
Problema para encontrar designer 

### ISSUE THREAD

**Issue by criss-ah** [IIC2233/syllabus#435]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

[Describe tu problema de manera detallada, explicando qué estás intentando hacer y explicando los errores o problemas que has encontrado. Se recomienda agregar fotos cuando sea posible]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Después de instalar pyqt5-tools no encuentro designer, intente con la ruta que nos dan por cmd pero me dice no encuentra la ruta cuando ingreso pyqt5-tools.

**Comment by Pablok98** [comment]
¡Hola!

Me podrías mostrar un pantallaso de lo que te aparece en consola cuando ingresas el siguiente comando:

`pip show pyqt5-tools`

Así podemos partir viendo que está pasando😀

**Comment by criss-ah** [comment]
![Captura de pantalla (86)](https://user-images.githubusercontent.com/80779455/117078014-1b571400-ad07-11eb-9c56-d34e279b96de.png)

**Comment by Pablok98** [comment]
Dejame confirmar algo, ¿probaste utilizando en el cmd el comando 

`pyqt5-tools designer` ?

**Comment by criss-ah** [comment]
No había probado haciendo eso ya que no lo vi en ningún lado, pero ahora probé y funcionó 😅, muchas gracias!

**Comment by Pablok98** [comment]
Es un truco que descubrimos preparando la ayudantía.

¡Suerte con el estudio!

**Comment by ArielGoldzweig** [comment]
Hola, tengo el mismo problema pero cuando pruebo "pyqt5-tools designer" me aparece esto: 

![image](https://user-images.githubusercontent.com/80789622/117089743-64699100-ad24-11eb-933a-cb722dd07b86.png)

**Comment by jigarciaforteza** [comment]
Hola, me pasa lo mismo que a la persona del último comentario
