### ISSUE TITLE
Horas dedicadas

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#435]
![capturlklkjlkjlke](https://cloud.githubusercontent.com/assets/26102365/25777387/24baeb4e-32b2-11e7-9e75-d6c1178327b8.PNG)

algo que no me queda muy claro es, que pasa con el tiempo que transcurre de jueves a domingo?,
en el enunciado se da el ejemplo de lo que estudiaria si partiese el lunes, pero 

?se parte a estudiar la materia el jueves anterior, no? 

por lo que cuando se llega a la actividad siempre se tendra el 30% total de lo que se dedicara a la AC, segun yo.

![capture](https://cloud.githubusercontent.com/assets/26102365/25777436/da1a62c0-32b3-11e7-81fc-7f0c637dcacf.PNG)

pero en esta parte se vuelve a mencionar "lo estudiado hasta ese momento".
?entonces para la AC no necesariamente se ha estudiado todo el 30% o si?

**Comment by sebacruzd** [comment]
Espero haber entendido tu duda.

Como la actividad es un jueves y estudiará toda la semana, lo mismo en cada día, no estudia 3 horas antes de la actividad, sino que proporcional a los días que pasan esa semana antes de la actividad (puedes asumir que lo que estudia el jueves lo hace antes de la AC).
Por lo que ha estudiado 4/7 de las 3 horas para la actividad.
Esto es porque **para esa semana tenía una cantidad distinta** a las otras semanas de tiempo de estudio.

En ese punto tienes dos opciones (siendo una la correcta):
* Haces que estudie una materia nueva cuando se hizo una actividad, o sea empezó un viernes a estudiar la siguiente materia.
* Haces que estudie una materia desde el lunes, como creo que estás entendiendo tú.

Lo que dice en el enunciado no especifica ninguna de esas opciones, sino que, por ejemplo:
Para la semana 1 tenía 20 horas total de estudio, por lo que cada día pudo estudiar 50 minutos aprox. para la actividad.
Para la semana 2 tenía 10 horas total de estudio, por lo que cada día pudo estudiar 25 minutos aprox. para la actividad.

Analiza la situación y la última pregunta que haces. ¿Estudia realmente el 30% de las horas de solo una semana **para una actividad** o cierto porcentaje de las horas de estudio de una semana, y otro porcentaje en la siguiente semana?

**Comment by Dunkan1** [comment]
gracias, me sirvio mucho
