### ISSUE TITLE
Ejercicio 5.1 - semana 6

### ISSUE THREAD

**Issue by Piolawa** [IIC2233/syllabus#436]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola!,
Estoy confundida en como conectar las señales, lo ultimo que probé fue la ventana_inicial con la ventana_donut_2, y la ventana_donut_2, con la ventana_inicial.

Y una duda, debería aparecer una imagen? es que busqué el path que ponen en el ejercicio en el archivo y no tengo estas imágenes, queria saber si las pasé a borrar o nunca estuvieron ahi xd

**Comment by Sofia-Arratia** [comment]
Hola @Piolawa ! Creo que tu confusión respecto a las señales que debes conectar se debe justamente a que no te están apareciendo las imágenes correspondientes, las cuales contienen instrucciones sobre cómo resolver el ejercicio 😅. Las imágenes se encuentran [aquí](https://github.com/IIC2233/contenidos/tree/main/semana-06/ejercicios_propuestos/img/ejercicio_5). Si aún así sigues confundida respecto a la conexión de señales, no dudes en comentar  tu duda en esta issue, estaré atenta c:
