### ISSUE TITLE
lectura de archivo genomas.txt

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#436]
Supongo que los números antes del nombre y el apellido los daban para saber sus largos y así poder obtenerlos desde el archivo de alguna manera. Sin embargo, logré leer el archivo sin considerar esos números... ¿Hay algún problema con eso?

**Comment by Hernan4444** [comment]
@mjgutierrez1 es probable que algunos test te fallen, puesto que pueden haber nombres compuestos como `11Juan Felipe5Solar` o nombres de reyes `11Enrique 8th5Lopez` y puede que tu algoritmo no se percate de eso. Si es que implementaste una forma que si se percata de todo lo que pongamos, entonces no debería haber problema.

Saludos ✌️

**Comment by jadiaz6** [comment]
Tenemos que levantar Genome Error si hay caracteres extraños en el genoma, ¿esto cuenta para la parte de los nombres?

O sea en el caso de Luna Lovegood, el nombre es "Luna " ¿hay que cortar ese espacio? ¿en "De Nazaret" hay que dejarlo?

**Comment by Hernan4444** [comment]
El Genoma error solo puede ocurrir en el header si es que hay algún error que no permita procesar el header como que el número indicado antes del nombre o apellido no coincide con el número de letras. ejemplo `2Hernan`.
El caso de luna está a proposito, como es `5Luna ` significa que hay un espacio adicional que no deben eliminar y las consultas serán con "Luna " (un espacio al final) para que coincida. En el enunciado nunca restringimos el nombre a solo letras, por lo tanto puede haber otro caracter mientras respete el largo adecuado.

**Comment by jadiaz6** [comment]
Ok gracias
