### ISSUE TITLE
variable = lambda ... [TAREA 3]

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#436]
Hola, 
Lo probé y corre perfecto pero, puedo usar...
```python3
saludar = lambda x: f"Hola {}"
print(saludar('Ayudantes')
```
... ?

**Comment by Hernan4444** [comment]
@jmwielandt lo que quieres es crear una función anonima y guardarla en una variable??
En ese caso si puedes, pero asegura de que esa función lambda sea atomizada de todos modos.

Saludos ✌️

**Comment by jmwielandt** [comment]
A qué te refieres con que sea atomizada? :o
Pregunto eso por el pep8 :/

**Comment by Hernan4444** [comment]
@jmwielandt es una forma sencilla de decir que haga una cosa y la haga bien. En otra palabras, que tu función lambda siga la filosofía.

**Comment by jmwielandt** [comment]
ah, oka
Gracias!
