### ISSUE TITLE
Obtener coordenadas QPoint

### ISSUE THREAD

**Issue by MatiasBarraF** [IIC2233/syllabus#436]
Para las torres me base en un código que encontré de Drag and Drop, y no hay ningún problema al ponerlas, pero cuando quiero usar sus coordenadas (que son entregadas en forma de QPoint) con el método QPoint.x() o QPoint.y() de la clase QPoint estos me deberían retornar un int según la documentación, pero me retornan <built-in method x of QPoint object at 0x10ffae828> o con y en el caso de que este buscando esa coordenada. ¿Saben como podría extraer el int de la coordenada desde este método?

**Comment by lily416** [comment]
Hola :smile: 

**Creo** que para acceder al `x` e `y` del `QPoint` debes hacerlo como si fueran atributos y no métodos, es decir, sin los `( )`.

Más rato te confirmo si es así o no, pero por ahora prueba eso para ver si sirve y me cuentas. 🙏🍀

**Comment by MatiasBarraF** [comment]
Al final si era un método y pude sacar el valor con evento.pos().x(), donde evento era el Drop del Drag and Drop, gracias.

**Comment by lily416** [comment]
Que bueno que lograste obtenerlo. 😊

Por favor no cierres la _issue,_ puede que haya más gente con el mismo problema.
