### ISSUE TITLE
Archivos en Avanze de la tarea

### ISSUE THREAD

**Issue by tqmbanados** [IIC2233/syllabus#436]
Hola! Hace poco recibí el correo usual que informa el commit que se revisará para el avance. Sin embargo, no encuentro los archivos asociados a mi último commit en la issue, por lo que me entra la duda de si tuve un problema al subirlos a Git, o si no he sabido encontrarlos. ¿Qué puedo hacer?

**Comment by lily416** [comment]
Hola @tqmbanados,

Estuve revisando los archivos que salen el _commit_ indicado en la _issue_ y tu diagrama de clases sí aparece dentro de los archivos recolectados 🎉. 

Para revisar los archivos recolectados para el avance de la T01, debes poner tu usuario de github y el _hash_ de tu _commit_, en el siguiente _link_ e ingresar al mismo:
```
https://github.com/IIC2233/{tu usuario de github}-iic2233-2020-2/tree/{commit}/Tareas/T01
```

Espero que esto te ayude y te deje más tranquilo 🤓.


Si en el futuro tienes alguna duda o problema, no dudes en hacer otra _issue_ y/o escribirnos al correo oficial del curso (iic2233@ing.puc.cl).
Saludos y que tengas una buena semana 👋🍬

**Comment by tqmbanados** [comment]
Muchas gracias por la respuesta! Me funcionó 😸
