### ISSUE TITLE
PROBLEMA_TEST_MODULO_CRIPTO

### ISSUE THREAD

**Issue by tremendapithon** [IIC2233/Syllabus#436]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola buenas noches, tengo un problema con el test de desencriptacion, ya que el ```bytearray original``` es distinto al del ```msg_original```

![imagen](https://github.com/IIC2233/Syllabus/assets/119064623/ba7af4b8-e919-4359-a58e-149bf1961e7e)

**Comment by MelanyLillo** [comment]
Es probable que tu función de encriptar está modificando la variable original, por ejemplo:

A = [1,2,3]

def f(x):
    x.append(2)

F(A),
print(A)
>> [1,2,3,2]

Eso también pasa con los bytearrays. Si tu función no hace una copia, está editando la variable de afuera y por eso falla después cuando compara.

Avísame si se aclaró tu duda😊

**Comment by tremendapithon** [comment]
Hola buenas, al final revise y mi funcion no altera ninguna variable. Y aun me sigue dando error en el test de desencriptacion.

**Comment by tremendapithon** [comment]
Ya lo arregle, usando la funcion .copy()
