### ISSUE TITLE
Adoptar nuevas criaturas

### ISSUE THREAD

**Issue by jtmeyer98** [IIC2233/syllabus#436]
Todas la criaturas en el archivo "criaturas.csv" tienen dueño en el archivo "magizoologos.csv".

Entonces cuando quiero adoptar en el DCC una criatura nueva, no podría, ya que todas tienen dueño.
No debería haber ninguna criatura en el DCC disponible para adoptar.

La única manera de adoptar una nueva criatura para el magizoologo sería adoptar una criatura de otro magizoologo. ¿No es raro eso? 

Si es así, después habrían dos magizoólogos con la misma criatura.

**Comment by furcelay** [comment]
Hola!
No soy ayudante, pero entiendo que las criaturas que puedes adoptar del DCC no son las que poseen otros magizoólogos, la idea es que cuando adoptes una nueva criatura la crees de cero como una nueva (al igual que al crear un magizoólogo al comienzo del programa).

**Comment by Dnpoblete** [comment]
Hola @jtmeyer98, complementando la respuesta de @furcelay, como bien dice, la idea es crear una nueva criatura, no tienes que ver las que se encuentran en el el archivos criaturas.csv. 

Como dice en el enunciado:

![image](https://user-images.githubusercontent.com/42362982/79120053-dfe65200-7d5f-11ea-83c3-ddbd60734d25.png)

La idea es que despliegues todas las criaturas que se encuentran en la sección DCCriaturas y le des al usuario la opción de seleccionar una, para que luego elija su nombre y así después agregarla a los archivos .csv.

Éxito con la tarea! 😄

**Comment by jtmeyer98** [comment]
Muchas Gracias!
