### ISSUE TITLE
Cortar Arboles

### ISSUE THREAD

**Issue by bgfeuereisen** [IIC2233/syllabus#437]
Hola buenas. 
Estoy implementando el evento para cortar árboles.  Y quería saber si existe alguna forma de al clickear sobre un label, en este caso el árbol, pudiendo enviar el label_arbol al metodo al cual conecto una vez que se clickea?
Tengo la opción de clickear el label y conectarla a otro método, pero no logro enviar ese label al clickear el árbol.
gracias

**Comment by lily416** [comment]
Uno de los objetivos de esta tarea es que investiguen los métodos que trae PyQt5. 
Te invito a volver a revisar el material, investigar en internet y revisar la documentación de Qt5 para ver si encuentra una función que haga lo que esperas.
Si no logras encontrar lo que buscas, comenta nuevamente está _issue_.
 
Saludos y éxito con la tarea 👋👨‍🌾
