### ISSUE TITLE
No uso de properties 

### ISSUE THREAD

**Issue by MINGOD24** [IIC2233/syllabus#437]
Hola,

Si mi codigo funciona bien, y cumple con todo lo que debe hacer, pero no utilizo properties, getters, setters, me perjudica en la nota?

**Comment by Dnpoblete** [comment]
Hola @MINGOD24 como se dice en el enunciado:

![image](https://user-images.githubusercontent.com/42362982/79121670-d363f880-7d63-11ea-8e6e-d5e01a09ac43.png)

Parte de los objetivos de esta tarea es reconocer cuándo utilizar properties y hacerlo de forma correcta, por lo que si no hace uso de esto, no obtendrás todo el puntaje en los items correspondientes, para más detaller puedes revisar la [distribución de puntajes](https://docs.google.com/spreadsheets/d/15SDoSSz9VINHPLQwmdgAIT_0-A2eDpvHsk3cTLGfXG0/edit#gid=0).

Como aún queda bastante tiempo para entregar la tarea te recomiendo cambiar tu código para que utilice properties y así no pierdas puntaje. En caso de tener dudas sobre el uso de properties puedes revisar las issues en donde se habla de esto y preguntar si tienes dudas.

Éxito con la tarea! :smile:
