### ISSUE TITLE
Largo funciones (decoradores y funciones anidadas)

### ISSUE THREAD

**Issue by meretamal** [IIC2233/Syllabus#437]
Hola, quería saber si el uso de decoradores en una función contaba como líneas de esta. Además, quería preguntar si, al definir funciones dentro de otras, estoy haciendo uso del máximo de 15 líneas de la función más general.

Muchas gracias de antemano.

**Comment by IchottMano** [comment]
@meretamal Hola!

En primer lugar, efectivamente los decoradores cuentan como una línea de la función.
En segundo lugar, definir una función dentro de otra también cuenta dentro del límite.

Saludos!

**Comment by sjkinast** [comment]
Hola en el caso de la gui esto tambien corre?

**Comment by Hernan4444** [comment]
@sjkinast se espera que en al gui ustedes solo llamen a su librería y maneje alguna excepción para imprimir en la interfaz, se puede pasar de las 15 líneas, pero **tampoco** es la idea que en **la gui hagan calculos o procesamiento que debería realizar la librería**. Solo tomar cada consulta, solicitar que la librería la procese y poner en consola o en el archivo el resultado entregado por la librería

saludos ✌️
