### ISSUE TITLE
Entrenamiento de deportistas 

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#437]
Uno elige entrenar de a un deportista o pueden ser multiples a la vez? pueden ser varios atributos entrenados al mismo tiempo?

**Comment by jitorcas** [comment]
Hola! @YehudaGurovich 

En la issue #399 se especifica que es solo un deportista a la vez. Con respecto a tu segunda pregunta, en el enunciado se señala que se debe entrar un atributo físico por cada entrenamiento. 

Mucho éxito! 🥇

**Comment by YehudaGurovich** [comment]
Y cuando le doy la opcion de elegir jugador o cuando elige atributo también tiene que estar la opción de volver atras?

**Comment by jitorcas** [comment]
@YehudaGurovich 

Así es, todo menú debe dejarte volver atrás. La issue #334 habla sobre eso!
