### ISSUE TITLE
Not Found error

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#437]
Hola! No entiendo bien lo que implica la parte del enunciado que dice:
> Not Found:
> Se debe levantar esta excepción si se ingresan mal los parámetros de una consulta.

Este error debe abarcar situaciones como estas?:
1. Parámetros se ingresan en desorden
2. Se ingresan más (o menos) parámetros de lo que se necesitan
3. Se ingresan parámetros de distinto tipo al que se necesita (por ejemplo str en vez de int)

Alguna otra situación que califique?

**Comment by xariveros** [comment]
Hola!, yo también tengo esta duda. Por ejemplo a qué tipo de excepción corresponde ingresar una consulta con un nombre mal escrito o que no esta en la base de datos?
Es decir, un nombre que no existe califica como un parámetro mal ingresado o como una consulta mal escrita?? (NotFound o BadRequest)
Gracias!

**Comment by mjgutierrez1** [comment]
Tengo la misma duda aún, alguien sabe la respuesta?

**Comment by bedefrunner** [comment]
Buena k-bros, yo lo hice que para cada consulta el codigo revise:
1. el largo de la lista sea el que corresponda a esa consulta, si es mayor o menor, levanto error
2. cada elemento de la lista sea del tipo que corresponde, si es de otro tipo levanto error
3. Hasta este punto, hay consultas que podrian pasar estos dos "filtros" siendo que igual están malas. Por ejemplo la consulta ['pariente_de', 4, 'pepito'] pasa los filtros, pero aún así mi código debiera ser capaz de levantar error porque no hay parientes de ese grado. Por lo tanto, para esta consulta reviso que el argumento de la posicion 1 esté dentro de los siguientes: -1, 0, 1, 2, 'n'. Lo mismo hago para otras consultas en donde se tenga que verificar que el argumento está dentro de una lista de argumentos posibles.

Así me aseguro de que todo esté en orden. Salu3.
