### ISSUE TITLE
rangos en notas

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#437]
![capture](https://cloud.githubusercontent.com/assets/26102365/25785967/e16ba052-3362-11e7-87a0-091fa69b2905.PNG)

los destacados estan incorrectos cierto? o debemos considerar un rango mas amplio eje si es 2 de 1.1 a 5.9

**Comment by sebacruzd** [comment]
Tienes toda la razón, pronto **se actualizará el enunciado** y se pondrán los intervalos correctos (no son necesariamente los que dices, para que estés atento a cuando se actualice).

Se anunciará cuando se cambie el enunciado.

Saludos!

**Comment by FernandoPieressa** [comment]
El enunciado fue actualizado.

Saludos!

**Comment by Dunkan1** [comment]
gracias.

**Comment by benjamimo1** [comment]
oh baiaa

**Comment by flobarrios** [comment]
Arreglado!

**Comment by jorgeriesco** [comment]
¿Que pasa si estudio 2.5 horas en OOP? ¿Que nota espero? Ojo que si puede tener horas de estudio decimales.

**Comment by Hernan4444** [comment]
@jorgeriesco #459
Saludos!
