### ISSUE TITLE
todos_tests.py

### ISSUE THREAD

**Issue by IsidoraCarmona** [IIC2233/Syllabus#437]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, una consulta, los cambios realizados el los test han sido actualizados en todos_tests.py ? para ver si me puedo fiar de lo obtenido en ese archivo.

**Comment by Jeremiah-PHP6** [comment]
¡Hola! El archivo `todos_tests.py` se encarga de cargar todos los tests de la carpeta `tests_publicos/`, por lo que sí, al correr este archivo verás reflejados todos los cambios realizados.
