### ISSUE TITLE
Error en columnas de movies.csv

### ISSUE THREAD

**Issue by antoniacobo** [IIC2233/Syllabus#438]
Hola!
En las dos primeras líneas del archivo `movies.csv` está lo siguiente:

> id, title, rating_imdb, rating_metacritic, rating_rt, box_office, date
> 0, "Titanic", 8.7/10, 88%, 90/100, $452.012.371, 1997

Si nos fijamos en los rating; el rating de _imdb_ corresponde a 8.7/10, el de _metacritic_ a 88% y el de _rotten tomatoes_ a 90/100. 

Por otro lado, en el enunciado tenemos:

![image](https://user-images.githubusercontent.com/37152809/39659335-83f7bc5a-4ffc-11e8-8636-ad9531c91dc0.png)

Esto, si lo pueden notar, no es consistente. Ya que en el enunciado dice que el rating de _rotten tomatoes_ debe ser con % y el de _metacritic_ en K/100 y en el archivo dice todo lo contrario. ¿Cómo deberíamos considerarlo?

**Comment by IchottMano** [comment]
#331
