### ISSUE TITLE
Moral en delegaciones.csv

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2233/syllabus#438]
Hola!
En el enunciado dice que el atributo ```moral``` de delegaciones es un ```int```, pero en el archivo delegaciones.csv está como un ```float```. ¿Debemos pasarlo a ```int``` o hay un error en el enunciado y debemos dejarlo como un ```float```?
Saludos :)

**Comment by mmunozmendez** [comment]
Hola,
Debes tratar el atributo como float.
Recuerda revisar el compilado de preguntas, esta ya estaba contestada ;)
Éxito con la tarea 🎇
