### ISSUE TITLE
if not (Problema)

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#438]
Estoy intentando sacar el approval level de cada mago(wizard), pero mi if not statement no funciona y no entiendo por que

**Comment by Dnpoblete** [comment]
Hola @CataSudo, por favor no subir código de tu tarea a issues, si deseas puedes hacerlo utilizando el método de este [tutorial](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) para poder ayudarte.
