### ISSUE TITLE
Multiples señales para el mismo slot?

### ISSUE THREAD

**Issue by Juan379** [IIC2233/syllabus#438]
Hola!
Tengo la duda si es que puedo enviar distintas señales para que la información de las señales distintas, que en este caso es un diccionario, pueda ser recibido por al función que quiero que lo reciba. Usualmente la funcion _target_ recibiría la info como un argumento del tipo **función(self, data)** pero si tengo dos señales con dos pedazos distintos de información dirigiendose a esta misma funcion, como lo pongo?

**Comment by lily416** [comment]
Lo más correcto es que una misma función **siempre reciba el mismo tipo de información**, ya que ese es su _input_, pero en caso de que aún así quieras que reciba señales con distinto contenido, podrías distinguir las acciones a tomar dependiendo del contenido del diccionario, es decir, sus llaves.

Ojalá te sea de ayuda,
Saludos y éxito con tu tarea 👋🌱
