### ISSUE TITLE
Archivo parámetros.csv

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#438]
Hola!

En el punto 9 del enunciado de la tarea 4 dice lo siguiente:

> Además, recibirá el archivo parámetros.csv con la cantidad de profesores, la cantidad de ayudantes y una cantidad de alumnos.

Dicho archivo no está en la carpeta T04. ¿Será subido en algún momento? ¿O simplemente lo ignoramos?

Saludos!

**Comment by FernandoPieressa** [comment]
Fue un pequeño error del enunciado, ustedes tienen que crear ese csv con esos parametros!

El enunciado fue arreglado.
Saludos!

**Comment by akaminetzkyp** [comment]
Perfecto!
