### ISSUE TITLE
Duda comentar un bloque en Pycharm para Mac

### ISSUE THREAD

**Issue by felipecr00** [IIC2233/Syllabus#438]
Alguno que use pycharm en mac y sepa como comentar un bloque de codigo con algun comando de teclas? el que recomienda el programa es cmd + /, segun yo no se puede hacer con los teclados de shile.

Saludos!

**Comment by sebacruzd** [comment]
Hola,
Con poner triple comillas antes y despues del bloque es suficiente. No debería ser mucho esfuerzo más en comparación a un comando :)
```
"""
Codigo comentado.
Todo lo de acá está comentado.
Y acá también.
...
"""
```

**Comment by felipecr00** [comment]
jajaja sii, es que en windows 👎  haciendo ctrl + 7 comentan todo lo seleccionando altiro y queria hacer lo mismo :(

**Comment by nebil** [comment]
:warning: **Advertencia:** No uso ni macOS, ni PyCharm. Mi editor es Atom, que corre en Ubuntu GNU/Linux.

Asumiré que con “los teclados de shile” quisiste hacer referencia al _layout_ español de Latinoamérica. Bueno, hasta a fines del año pasado, tuve el mismo problema con Atom, ya que este editor no hacía un buen manejo de los _layouts_ internacionales. Sin embargo, en [este _release_](https://github.com/atom/atom/releases/tag/v1.12.0) lo terminaron por arreglar. :sparkles:

Afortunadamente, mi _laptop_ anterior venía con [_numpad_](https://en.wikipedia.org/wiki/Numeric_keypad), por lo que mi _workaround_ consistía en presionar `Ctrl + /`, pero con el `/` del teclado numérico. Y todo funcionaba bien.

Entonces, mis posibles soluciones para ti son…

1. Intentar con `Cmd + /`, donde `/` es la tecla de tu teclado numérico. Aunque, ahora que estoy escribiendo esto, ni siquiera estoy seguro si es que existen los Mac con _numpad_. :smile:
2. Configurar, de alguna forma, el [_keymap_ de PyCharm](https://www.jetbrains.com/help/pycharm/keymap.html), para modificar el _shortcut_ que permite comentar bloques de código.
3. Hacer clic aquí: [:atom:](https://atom.io/).

Estaré a la espera de tus _comentarios_, Felipe.
:clown_face:

**Comment by felipecr00** [comment]
```python
import unittest
class HumanoTestea(unittest.TestCase):
    def test_humano_intenta_cmdbarrita(self):
          # el humano presiona la combinacion
    def test_humano_intenta_configurar(self):
          # el intenta configurar de alguna forma el keymap
    def test_humano_intenta_click(self):
          # el humano hace click
```
>Los resultados del test nos entregan:
```
FFF
======================================================================
FAIL: test_humano_intenta_cmdbarrita (__main__.HumanoTestea)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-9-95c055dd7b86>", line 5, in test_humano_intenta_cmdbarrita
    El mac no tiene teclado numerico asi que no tengo la barrita / sola :c
MacError

----------------------------------------------------------------------
FAIL: test_humano_intenta_configurar (__main__.HumanoTestea)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-9-95c055dd7b86>", line 6, in test_humano_intenta_configurar
    No logre hacer eso por que me perdi dentro de todas las opciones y google no me ayudo lo 
    suficiente jajaja :c
TontoError

----------------------------------------------------------------------
FAIL: test_humano_intenta_click (__main__.HumanoTestea)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-9-95c055dd7b86>", line 7, in test_humano_intenta_click
    No me llevo muy bien con atom porque me acostumbre a usar Pycharm <3
FlojoError 

----------------------------------------------------------------------
```

@nebil Al final seleccione la opción que deja hacer lo mismo pero haciendo click en el menu code. 
Muchas gracias por la respuesta!!!
Saludos
