### ISSUE TITLE
Duda sobre variable (misma_especie) en la función 18(votos_interespecie)

### ISSUE THREAD

**Issue by mpuntous** [IIC2233/Syllabus#438]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En la función 18(votos_interespecie) a veces no se nos entrega misma_especie, en ese caso se supone que debería de tener False como valor. Podemos modificar la definición de la función para esto? por ejemplo asi:
![image](https://github.com/IIC2233/Syllabus/assets/130417431/8a3cd4f5-ae0e-4155-a413-4bcb6c6ea4f5)
porque se que en la tarea dice que no se puede, pero no se me ocurre como mas poder hacerlo.
Una ayudita por favor :(
Muchas Gracias.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mpiavf** [comment]
Hola, perdón por la demora en la respuesta. Ese archivo fue modificado, te recomiendo que le des una mirada a la issue #338 y te recomiendo que actualices los archivos mencionados. En este caso efectivamente consultas.py fue cambiado en la parte de esa consulta.
Saludos!
