### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#439]
Hola cuando se tienen que probar la consultas en el testing puede ser entregando datos  separados de movies k_actors o tengo que entregar directamente una consulta en el formato JSON , es decir yo puedo probar cada funcion qu me ejecuta una consulta por separado entregandole parametros o es necesario que ocurra de la misma forma que en el gui.

ej : test_filter_by_date(movies:generator, date:int, lower=True:bool) yo le entrego  por separado las variables movies date y lower  a traves del set up

**Comment by Hernan4444** [comment]
@sjkinast no es necesario que pruebes las consultas en el formato JSON, sino que las funciones implementadas en tu librería entregando diferentes parámetros

**Comment by sjkinast** [comment]
Hola  cuando en el enunciado dice que se pueden crear archivos se refiere a que en los test se pueden crear o tambien  yo puedo por ejemplo seleccionar algunos generos y ponerlos en un archivo de forma de usarlos al abrir el archivo. Tambien me surge la duda de que  si en el objetivo de probar la consulta es relevante  la cantidad de datos que analize, es decir si analizo solo 3 peliculas o 100 , ya que desde mi punto de vista es mas facil comprobarla con pocos datos ya que resultan mas conocidos  y mas facil de comprobar los errores de si la consulta logra el objetivo o no.

**Comment by Hernan4444** [comment]
>  yo puedo por ejemplo seleccionar algunos generos y ponerlos en un archivo de forma de usarlos al abrir el archivo

Si puedes 👍 

Sobre la cantidad, puedes analizar 1, 2, 100, 200, lo que quieras. Tal como dice tu punto de vista, es más fácil comprobarlo con pocos datos

Pero para que tengas esto presente en el futuro, también puede ser que quieras testear la eficiencia de tu código y con ellos hagas archivos de miles de datos verificar que se demora menos de X segundo. Esto último **es un ejemplo de otro tipo de testing, no lo estamos evaluando**, pero podría ser util en algún futuro para verificar que los cambios no hacen que tu código se demore más
