### ISSUE TITLE
nivel de energía actual al crear un nuevo magizoologo 

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#439]
Al crear un nuevo magizoologo su energía actual sera la misma que la energía total? o  también sera un valor aleatorio en 0 y su valor de energía total? .Además en el enunciado, de energía actual, mencionan " Su valor inicial diario y máximo dependerá de cada Magizoólogo." ,esto último se refiere a como variará la energía actual dicho día dependiendo de las acciones que tome, o tiene otra interpretación.

**Comment by mpsubiabre** [comment]
Hola @RonaldoSosa !

Exactamente! el valor inicial diario es igual a la energía total, que es a la vez la máxima que se puede tener. Es decir, cada día los Magizoologos se recuperan a su máximo de energía
Lo segundo que mencionas hace referencia a que la energía inicial depende de cada Magizoólogo, esto es porque la energía inicial es igual a la energía total, y la energía total tendrá diferentes rangos según el tipo de Magizoologo :)

Espero que te haya quedado claro 😄

**Comment by RonaldoSosa** [comment]
Me quedo claro! Gracias
