### ISSUE TITLE
Ejercicio Calculadora Ayudantía 6.5

### ISSUE THREAD

**Issue by fernandolalanne** [IIC2233/syllabus#439]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Tengo una duda con el ejemplo de la calculadora de la ayudantía realizada el día de ayer. Sucede que no entiendo bien como en la ventana del back-end, donde se definen las operaciones que realiza la calculadora, cómo sabe el programa qué es lo que se debe hacer, porque tal como mencioné en esa pestaña solo se definen las operaciones pero en ningún minuto se aplican. 

En segundo lugar tenía una duda con el front en la línea 68 donde escriben texto_boton = self.sender().text(). Mi pregunta es cómo sabe el programa qué es self.sender??

Desde ya gracias!!

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Pablok98** [comment]
¡Hola!

Con respecto a tu primera pregunta, este ejemplo es un ejemplo de cuando aun se pasaba el concepto de funciones de primera clase (se nos pasó al construir la ayudantía extra). Antes de explicar exactamente como funciona, me gustaría que entiendas la lógica detras de lo que hace el backend:
1. La ventana del front end emite la señal *button_clicked_signal*, que está conectada al metodo *refresh_operation* del backend.
2. El metodo *refresh_operation* recibe la operación que está en la pantalla de la calculadora y modifica el string para obtener la operación que se quiere.
3. Se llama al método necesario dependiendo de la operación.

Con respecto a tu pregunta de ¿Pero... donde llamas al método de la operación 😵? Bueno, usamos el concepto que te decía, que **no es necesario que sepas para este curso**. Lo que hacemos es guardar cada método en un diccionario (*diccionario_operaciones*), donde la llave de cada método es el nombre de la operación. Con eso, extraemos el método a partir del string de la operación. 
Lo anterior es posible porque las funciones se pueden guardar y llamar dentro de variables, un ejemplo es:
`def imprimir_epico(palabra)`
`    return palabra + 'es muy estudioso'`
`funcion_guardada = imprimir_epico`
`print(funcion_guardada("fernandolalanne"))`
Retorna `fernandolalanne es muy estudioso`.

Con respecto al `sender`, siempre que un evento (una señal) llama a un método, el que activó esa señal queda guardado como sender. Esto quiere decir que cuando conecto un método al `.clicked` de un bóton, puedo acceder a ese botón por medio de `sender()` como ves ahí (o cualquier objeto que emita la señal, se pasara como sender).

Espero que no esté muy confusa la respuesta, cualquier cosa me respondes 🥕

**Comment by fernandolalanne** [comment]
Hola!! Chuta la verdad es que me confundí un poco pero se me ocurrió una opción alternativa y quería saber si eventualmente podría funcionar.

Mi idea en principio es no crear ninguna función y solo establecer un código if-elif. En base a lo anterior estaba pensando que el storing emitido a través de la señal desde el front se guarde en una variable, pero aquí está mi primer problema porque no sabría como guardar este string de la señal en una variable y posteriormente no sabría como conectarla.
Luego de lo anterior se podría leer esta variable y realizar la operación según corresponda. Mi idea quedaría algo así como:

class CalculatorB(QObject):
    new_operation_signal = pyqtSignal(str)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.numb_1 = None
        self.numb_2 = None
        self.operator = None
        self.variable_auxiliar_que_recibe_el_string_de_la_señal = None

    if "+" in self.variable_auxiliar_que_recibe_el_string_de_la_señal:
        numeros = operacion.split(operador)
        self.numb_1 = float(numeros[0])
        self.numb_2 = float(numeros[1])
        resultado = self.numb_1 + self.numb_2
        self.new_operation_signal.emit(str(resultado))

Luego sería lo mismo con "-", "*", y "/".

Finalmete lo que quedaría hacer sería conectar las señales pero la verdad es que ahí me pierdo nuevamente como hacerlo por lo que si pudieras orientarme te lo agradecería.

Saludos!

**Comment by fernandolalanne** [comment]
Sorry me equivoqué en escribirlo. En la variable numero, quedaría algo como

numeros = self.variable_auxiliar_que_recibe_el_string_de_la_señal.split("+")

El error fue porque copié gran parte del código que ustedes hicieron y se me fue cambiar esa parte.

**Comment by Pablok98** [comment]
Si, mira, olvídate en verdad de esa explicación de cómo funciona el método del ejemplo. Un equivalente sería algo parecido a lo que planteas: 

1. Imagina que se manda “2+2”
2. Defines una lista con los operadores “+”, “-“, “/“ y “*”. Iteras por la lista, viendo si el operador está en la operación. En este caso, encontramos “+”, pues `”+” in “2+2”` retorna `True`
3. Como sabemos que la operación es “+”, podemos hacer un split con el símbolo y tenemos los números (`“2+2”.split(“+”)` retorna `[“2”, ”2”] `).
4. Puedes hacer un bloque ` if/else `, para decidir que hacer con los dos números (en este caso, sumar).
5. Retornas el resultado con la señal.

Con respecto a las señales, no entiendo bien tu duda, pero revisa el main.py, ahí es donde se conectan las señales en este ejemplo.

**Comment by fernandolalanne** [comment]
Ya bacan. Mi duda es justamente en el 1. porque se emite la señal con el string pero cómo se guarda esa señal? Porque actualmente ese string de la señal se trabaja directamente en una función que recibe un argumento llamado "operación". Es decir, como puedo representar correctamente la señal en una variable del tipo:

variable = string de la señal que se emite en el front.
No se si se entiende. En caso de que no se entienda busco otra forma de explicarlo.
Saludos!

**Comment by fernandolalanne** [comment]
Y lo último que quería preguntar, en el mismo ejercicio, en el front existe una función llamada     

def refresh_screen(self, operacion)

y mi duda es, cómo sabe el programa cuando aplicar esa función?

**Comment by Pablok98** [comment]
Esque, al menos en este caso, no es necesario guardar el valor de la señal. Justamente, el objetivo de las señales es que, al emitirlas, enviamos los valores que son relevantes para la acción que queremos ejecutar. Por ejemplo, ahora queremos calcular una operación, por lo que al emitir la señal enviamos la operación que queremos calculada. 

De todas maneras, los parámetros que se envían por medio de la señal, se entregan al método como cualquier otro parámetro. Con eso, podrías conectar una señal con un metodo que sea "guardar_info(datos)" que reciba un string, y ahi puedes hacer "self.info = datos", dentro del método. Aún no estoy seguro si esa es tu duda.

**Comment by Pablok98** [comment]
Con tu segunda pregunta, me parece que quizás estás confundido con el funcionamiento de señales. En el main.py, la señal del backend `new_operation_signal` está conectada con el método del frontend `refresh_screen`. Por lo anterior, cada vez que el backend emita la señal de una nueva operación, se llamará al metodo de `refresh_screen`.

**Comment by Pablok98** [comment]
Un resumen del funcionamiento de las señales: 
- Una señal se conecta con un método (`señal.connect(método)`)
 - Una señal llama al metodo que tiene conectado cada vez que se emite (con `señal.emit()`)

**Comment by fernandolalanne** [comment]
Buenísima ahi me aclaraste todo con tus últimos dos mensajes. Efectivamente estaba un poco (mucho) confundido jajajaj. Y lo último es solo para confirmar. 
Si en el backend creara un método que se llamara def procesar_informacion(datos_señal) y conecto la señal del front con ese método único, al emitir la señal se corre automáticamente ese método cierto??

**Comment by fernandolalanne** [comment]
Pensando que en el def procesar_informacion(datos_señal) se realizan todas las operaciones (+, -, *, /) necesarias para ejecutar la calculadora.

**Comment by Pablok98** [comment]
Sip, se corre auto-mágicamente✨
