### ISSUE TITLE
Datos en delegaciones.csv

### ISSUE THREAD

**Issue by FdoTorres1** [IIC2233/syllabus#439]
Hola!

La cantidad de delegaciones contenidas en `delegaciones.csv` van a ser siempre 2, o pueden variar? En el caso de que puedan variar, podemos asumir que siempre habrá información al menos una delegación?

Gracias

**Comment by itmunoz** [comment]
Hola! Siempre serán solo dos delegaciones: IEEEsparta y DCCrotona. Ten en cuenta que el orden de qué delegación aparece primero en _delegaciones.csv_ sí puede variar.

**Comment by FdoTorres1** [comment]
Gracias!
