### ISSUE TITLE
Genome Error consultas gemelo_genetico, pariente_de

### ISSUE THREAD

**Issue by pdesolminihac** [IIC2233/Syllabus#439]
Para estas dos consultas(gemelo_genetico , pariente_de) en que se necesita comparar a la persona consultada con todas las personas de la poblacion, si nos encontramos con una persona que tiene un error en su genoma, ¿me lo puedo saltar para que siga buscando el resultado de la consulta?, o es necesario levantar el Genome Error

**Comment by Hernan4444** [comment]
@pdesolminihac es necesario levantar error.

Saludos ✌️

**Comment by Polea012** [comment]
¿ Entonces se dejaría de buscar el gemelo genetico o al pariente?

**Comment by Hernan4444** [comment]
precisamente 👍. Cuando en una librería falla algo, se levanta la excepcion y se termina la ejecución. Solo que en este caso, ustedes imprimen el error en la interfaz y pasan a la siguiente consulta.

**Comment by Polea012** [comment]
Eso no causaria confusion de cuando se detiene una consulta?
por ejemplo en las consultas que mandaron, Rick Sanchez devuelve error not acceptable porque usa la id 60 (que no tiene numeros y por ende, no hay genes de tal característica). Sin embargo, en pariente_de(1, Tomas Salvadores) se devuelve a Emilio Gabriele, pero siguiendo la lógica de antes, la consulta debería levantar un error y dejar de ejecutarse porque se reviso a Rick Sanchez y la caracteristica(problemas de vision) que levantaba el error.

¿Para que casos entonces se tiene que levantar el error?

**Comment by Hernan4444** [comment]
@Polea012 la lista de id 60 es usada para una característica complementaria lo cual se dijo en otras issues que pueden tener listas vacias, lo cual implica que no tiene ningún problema de visión. Por lo tanto no se debería afectuar ningún error.

**Comment by Polea012** [comment]
@Hernan4444 Entendido, muchas gracias!

**Comment by bedefrunner** [comment]
@Hernan4444 entiendo que en el caso de la consulta `pariente_de(grado, persona)` debemos levantar el error GenomaError en caso de que cualquier persona de la población tenga un error en su genoma, pero por lo que me acuerdo de otra issue, los errores de genoma se levantan solo si es que hay un error en alguna de las características en las que se está trabajando.

Por ejemplo, si estamos haciendo la consulta con grado 2 y hay una persona de la población con un error de genoma en su característica "tamaño de la guata", como el grado 2 de parentesco no utiliza esa característica entonces no se debe levantar genoma error. Estoy bien?

**Comment by Hernan4444** [comment]
@bedefrunner está perfecto 👍

**Comment by felipecr00** [comment]
@Hernan4444 podrian compartir algun archivo con genomas defectuosos para probrar el GenomaError,
nose si estoy considerando correctamente las cosas que debería hacer esta excepción.
Saludos!!

**Comment by Hernan4444** [comment]
@felipecr00 lamentablemente no podemos hacer eso, en estos momentos estamos trabajando en crear un script que nos haga genomas con las características que queremos y agregar más cosas a la solución (como las excepciones), pero aun estám defectuosos 😞. Si es que subimos test para el `GenomaError` es demasiado probable (100%) que en estos momentos no identifiquemos todo el potencial que tiene `GenomaError` y terminemos dando resultados incorrectos, lo cual confundiría a ultima hora a todos ustedes

La opción más viable es que tomes el primer *genoma.txt* que te dimos, le cambies una letra al genoma de una persona y compartas en una issue nuevas consultas y sus resultado junto con el archivo nuevo, así entre ustedes, que tienen la solución muuucho más avanzada, puedes ayudarse.

Saludos ✌️

**Comment by felipecr00** [comment]
okas :) gracias por la respuesta :D

**Comment by felipecr00** [comment]
@Hernan4444 por lo visto, en todas las consultas que impliquen analizar todos los genomas, si tan solo una de esas personas tiene su genoma defectuoso se deberia levantar el error GenomeError y entregar como resultado de la consulta ese error?

**Comment by Hernan4444** [comment]
@felipecr00 así es
Saludos 👍

**Comment by felipecr00** [comment]
@Hernan4444 Solo para confirmar entonces (o si alguien tiene los mismos resultados) del archivo de test_1 cambie el genoma de jesus (puse una letra distinta de ACTG). El output que me entrega la consulta.json seria algo como esto? Esta bien o a alguien le da algo parecido? (perdón por lo insistente con el tema :c )

![captura de pantalla 2017-10-07 a las 23 29 41](https://user-images.githubusercontent.com/18125733/31313387-31240e4a-abb8-11e7-9bf1-438d80fb4c5d.png)

**Comment by Hernan4444** [comment]
@felipecr00 te recomiendo compartir el archivo *genoma.txt* o especificar bien que genoma editaste, porque pudiste haber editado (por ejemplo) una tripleta de las características de Color de ojos y en ese caso, las consultas de pariente grado 2 no deberían dar fallo puesto que ahí tu no analizas los ojos de las personas. Pero si edistas el color de piel, ese si es ocupado en todos los parentezco lo cual genera Genoma Error en todos.
ps: sería bueno eliminar el texto `Probando función`

**Comment by felipecr00** [comment]
@Hernan4444 por lo que tenia entendido el enunciado dice que "Se debe levantar esta excepcion si al leer un genoma,  este tiene errores ya sea porque tiene espacios, letras distintas a ACTG, numeros o caracteres especiales". Lo que hice fue tomar el genoma completo de la persona (todas las letras) y si alguna tiene un caracter defectuoso entonces ese genoma esta malo, puesto que nada asegura que algunas de esas tripletas no lleguen a ser usadas para definir alguna caracteristica. Bajo ese punto de vista, independiente de si la persona analiza la caracteristica que pudiera contener la triada defectuosa, no deberia entregar la consulta, puesto que no se sabe si ese caracter o espacio afectaba el genoma completo y hubiera cambiado el resultado de la caracteristica que no tiene tripletas defectuosas.

**Comment by Hernan4444** [comment]
@felipecr00 #375 hace días se explicó en una issue lo del Genoma error  y hace un día fue cerrada. Recordando lo dicho en la issue de Reglas del foro (#26):
> Este es un medio oficial de comunicación por lo que es tu deber revisarlo periódicamente, ojalá todos los días, para que no estés desinformado/a.

Por lo tanto no puedo decir nada, solo ánimo, todavía hay tiempo

**Comment by felipecr00** [comment]
@Hernan4444 no hay problema :), lo cambie igual en base al penultimo comentario que me diste, cambie una tripleta de color de ojos y ahora arroja los resultados para el otro grado de pariente.
Saludos y muchas gracias por las respuestas! 😄
