### ISSUE TITLE
Problema con los test

### ISSUE THREAD

**Issue by mpuntous** [IIC2233/Syllabus#439]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.
 
Desde mas o menos la función 18-19 al correr los últimos tests se demora muchísimo, tipo en los que requiere extraer de un archivo, y me querría saber si puede ser porque mi función cargar_datos retorna una instancia de map, y no una función generadora por yield. que podria estar pasando?
Muchas Gracias

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mpiavf** [comment]
Hola!  En general no debería demorarse más de 20 segundo correr un test, puedes ver si estas instanciando quizás cosas innecesarias que hagan que la memoria se consuma más rápido. En cualquier caso si pusheas tu código podriamos ver que está pasando! 
Me comentas

**Comment by mpuntous** [comment]
OK, voy a hacer push únicamente a mi consultas.py. de verdad no entiendo que podria estar, pasando.

**Comment by mpiavf** [comment]
Hola, por lo que se puede ver, la función verificar_type hace que consumas mucho tiempo. El formato de los archivos ya está dado, puedes tener una función por tipo de archivo donde se sabe, según la posición, qué tipo de dato corresponde. Nosotros no te daremos un archivo con un formato distinto.

Por otro lado, instanciar tantas cosas (en memoria) hace que las consultas se vuelvan más lentas. A veces no necesitas instanciar todo, solo pasando una vez por ella de forma correcta ya logras el resultado. 

Espero que esto te ayude
Saludos!

**Comment by mpuntous** [comment]
Pero la función verificar_type esta para cambiar de str a el tipo de variable que necesito, por ejemplo edad debe ser int, la única manera de hacerlo sino es la manera larga, supongo que lo hare asi . No entendi a que te referias con el ultimo parrafo. Muchas Gracias.

**Comment by mpuntous** [comment]
De hecho, esas funciones únicamente las ocupo en "Locales" y el problema ocurre también en otros, cuando tengo una simple instancia, ahí modifique el archivo. Por favor necesito luz en este asunto :(
Muchas Gracias

**Comment by mpiavf** [comment]
Hola, 
Lo que te puedo recomendar es que vayas analizando en tus funciones qué partes toman más tiempo que otras. Por ejemplo, en un archivo de prueba aparte puedes ir probando tus respuestas y midiendoles el tiempo. Además, te recomiendo ir viendo en la semana de funcional qué operaciones tienden a ser más costosas que otras. 
Lamentablemente, no puedo dar más aclaraciones además de lo que ya he dicho ya que el objetivo de la tarea es que puedan encontrar la forma de correr bajo el tiempo pedido :C
Saludos
