### ISSUE TITLE
Duda sobre agregar comentarios en publicaciones

### ISSUE THREAD

**Issue by JuanIke** [IIC2233/Syllabus#44]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola buenas, tengo una duda sobre el menú de publicaciones, cuando piden agregar un comentario. En el enunciado dice que si un usuario no está registrado, no podrá agregar un comentario, pero quisiera saber si debo dejar la opción puesta y enviar una notificación tipo "Solo para usuarios registrados" o simplemente la opción no debe aparecer en pantalla.

]

**Comment by Emiliax16** [comment]
Hola @JuanIke ! dado que el enunciado sólo pide que los menús tengan sus opciones mínimas, puedes agregar otras opciones mientras no vaya en contra de ninguna condición. Para los comentarios del usuario anónimo, no se especifica lo que mencionas, por lo que podrías hacerlo cómo prefieras, lo único importante es que este usuario no pueda dejar comentarios. Saludos!

**Comment by JuanIke** [comment]
Perfecto! Gracias ❤️
