### ISSUE TITLE
Match de Bids y Asks 

### ISSUE THREAD

**Issue by odbravo** [IIC2233/Syllabus#44]
En el enunciado de la tarea, en la figura 7 se observan los resultados de hacer un bid a un precio mayor a los asks disponibles, generando un match parcial. Quisiera saber qué pasa en el caso opuesto, es decir, si se realiza un ask a un precio menor a la de los bids disponibles ¿También se realiza un match? De realizarse, ¿Se respeta el menor precio (el del ask)?

**Comment by nebil** [comment]
En aquel escenario, sí habrá un _match_ parcial y se irán respetando, uno a uno, los precios de cada _bid_, ya que aquellas órdenes llegaron primero al mercado. En otras palabras, funcionará de **forma análoga**. Pero recordemos que esto ocurrirá sólo si es que la cantidad del _ask_ es suficientemente grande para engullir —así es, una metáfora digestiva— cada oferta de _bid_ que se le presente. ¿Queda más claro?

**Comment by odbravo** [comment]
Ok entonces, ejemplificando, si hay un bid para comprar 2 NEC por 100 mil CLP cada uno y otro usuario realiza un ask de 1 NEC por 90 mil CLP no se produce match, pero si el bid es de 3 NEC si?

**Comment by nebil** [comment]
En ese caso también se producirá un _match_, y será de `1 NEC` —que es la mayor cantidad común de ambas ofertas— a 100 mil pesos chilenos, ya que el _bid_ estaba primero. Además, como la oferta de compra era mayor (en cantidad) a la de venta, quedará un _nebcoin_ puesto como _bid_ a `100.000 CLP`. Ahora, con lo de “engullir”, simplemente me refería a que una oferta de _ask_ irá ejecutando a su paso todas las ofertas de _bid_ que tengan un precio mayor al _ask_. Pero esto se podría frenar por dos motivos: ya no existe un _bid_ con un mayor precio al _ask_, o bien, la cantidad del _ask_ se agotó completamente.
**ProTip™:** quizá hacer un dibujo a mano es una buena idea para visualizar qué está sucediendo. :grinning:

Como moraleja de la historia, **nunca debería haber una oferta activa de _ask_ que tenga un menor precio que una oferta activa de _bid_**. Esto es bastante intuitivo, ya que si ocurriera algo así, ambos _traders_ estarían, con altísima probabilidad, de acuerdos en realizar la transacción. :money_mouth_face:

**Comment by rihanuch** [comment]
cuando ocurre un match solamente se genera dinero? (asumo que no, porque es un intercambio, pero en el ejemplo del enunciado se dice "¡Tenemos el primer match! El usuario que hab ́ıa puesto el ask de 3 NEC a 95 mil pesos recaudar ́a 285 mil pesos (menos la comisi ́on del mercado), mientras que el usuario que (reci ́en) realiz ́o el bid recibir ́a los 3 NECas ́ı es, menos la comisi ́on). Ahora, supongamos, que un mismo usuario coloca dos bid: uno de 1.5 NEC a 98 mil pesos y otro de 1.2 NEC a 100 mil pesos." Pero nunca se plantea que el usuario 1 y/o 2 tenga un descuento de lo que ofreció 🤑

**Comment by nebil** [comment]
Efectivamente, el “descuento” que mencionas no se describe en ese párrafo, pero **sí ocurre** de forma implícita. En el enunciado ya se había definido que un _match_ involucra un traspaso de bienes (en este caso, _nebcoins_) usando otros bienes (en este caso, pesos chilenos) entre ambos _traders_. Por lo tanto, escribiendo esto de otra manera, el usuario que recibió los 285 mil pesos —monto al que todavía se le debe restar la comisión asociada al mercado— sí entregó los tres _nebcoins_ que vendió. Porque además, si no funcionara así, la propuesta de valor de DCCapital sería, al menos, cuestionable. Y probablemente, después de un par de horas de funcionamiento, tendrían que declararse en bancarrota. :money_with_wings::money_with_wings::money_with_wings:

**Comment by rihanuch** [comment]
gracias! pero aun así, como puede un usuario ya registrado ( que no tiene dinero en forma de otras monedas que no sea asks o bids) realizar intercambios, ya que no se puede quedar en un balance negativo 😢

**Comment by nebil** [comment]
Tu duda es el motivo de por qué un usuario recibe :moneybag::moneybag: al registrarse en un nuevo mercado. :relieved:
