### ISSUE TITLE
Al realizar cambios en mi repositorio clonado no se actualiza utilizando git

### ISSUE THREAD

**Issue by MartinSanfuentes** [IIC2233/Syllabus#44]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema
Al actualizar mi README en vscode no me deja subir los cambios a mi repositorio. Utilizando git add . luego git commit -m "comentario" y git push me sale que no se han hecho cambios en los archivos.  

Abajo en la foto debería salir el cambio en la línea 14 y no ocurre esto.

![image](https://github.com/IIC2233/Syllabus/assets/142350665/34df568f-71a0-449a-a0d8-63d813cc476c)

**Comment by pedrozavalat** [comment]
Hola @MartinSanfuentes !,

En el circulo blanco de arriba indica que existen cambios en el archivo que no han sido guardados, por lo tanto probablemente no se te esta actualizando tu archivo README en tu repositorio dada aquella  razón. 
 
![Captura de Pantalla 2023-08-21 a la(s) 12 26 25](https://github.com/IIC2233/Syllabus/assets/105678668/c39fd657-1668-46d4-8531-508342ef4d70)

Por ello, te recomiendo activar la opcion **_auto save_** que aparece en el menu desplegable al hacer click en **_file_.** Asi te aseguras que todo cambio realizado en el archivo se guarde constantemente. 

<img width="323" alt="Captura de Pantalla 2023-08-21 a la(s) 12 28 58" src="https://github.com/IIC2233/Syllabus/assets/105678668/c487dd4a-b52d-4c71-9a43-04f4229c3bb7">

Ahora para verificar que te esta funcionando, edita nuevamente tu archivo README. Luego, realiza lo siguiente:

- ```git add .```
- ```git status``` _(Para verificar el estado de tu directorio)_ 
- ```git commit -m "Mensaje"```
- ```git push```

Despues de haber ejecutado lo anterior, se deberia haber actualizado tu README en el repositorio. 
Cualquier duda me avisas, Saludos! 😄
