### ISSUE TITLE
confusión con path en T0 o Archivos

### ISSUE THREAD

**Issue by blampasona18** [IIC2233/Syllabus#44]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, en las dudas de TomasRiquelme y csanchez, Hernan4444 se contradice sobre donde estarán los archivos que usarán para corregir la tarea. **Los archivos estarán dentro de T0 o dentro de T0/Archivos?** Gracias

**Comment by Hernan4444** [comment]
Hola @blampasona18 

En las issues que indicas se refieren a temas distinto con "archivo".
 
* La de TomasRiquelme hago refencia a los archivos del tablero. Los ".txt" que deben cargar en su programa siempre estarán en la carpeta de T0/Archivos. Si hay un tablero en otra carpeta o fuera de T0/Archivos, ese no existe para DCCeldas.

* En la de czsanchez se habla de los archivos a considerar para la corrección de la tarea, es decir donde deben desarrollar su tarea con los scripts de python que necesiten. Y estos deben estar dentro de la T0, es decir, si haces tu `main.py` fuera de la carpeta T0, este no será considerado para la corrección. Y además, lo que harán los ayudantes es abrir la terminar desde la carpeta T0 y ahí correrán todos los script, por lo tanto las rutas relativas deben ser pensadas en función de una terminal que estará posicionada (pwd) en `T0/`

Espero que esta aclaración resuelva la confusión que tienes,
Saludos c:

PD: Vi que marcaste la casilla que dice "Utilizaré un título descriptivo y llenaré correctamente esta plantilla.", pero inicialmente no le pusiste un título descriptivo (nos llega un aviso al cuerpo de ayudantes con el título original) . Creo que marcaste las casillas sin leer lo que pedían 😞, ojo con las siguientes issues que hagas 🙏.

**Comment by blampasona18** [comment]
Perfecto Hernán, muchas gracias!
Mala mía, tendré más ojo para la otra
