### ISSUE TITLE
Error Instalacion Visual Studio Code

### ISSUE THREAD

**Issue by Fercho19** [IIC2233/syllabus#44]
Hola, estaba instalando VSC y me salto el siguiente error: 
![Error Visual Studio Code](https://user-images.githubusercontent.com/69866585/90548517-104d5b00-e15b-11ea-8e1e-3608294e5e39.jpg)

**Comment by lily416** [comment]
Hola @Fercho19,

Estuve investigando un poco y aparentemente el error tiene relación con una actualización que tuvo recientemente VSCode ([fuente](https://github.com/microsoft/vscode/issues/104545)). 

Por ahora, prueba instalando una [versión anterior a la 1.48](https://code.visualstudio.com/updates/v1_47) u otra interfaz de desarrollo, como Sublime Text 3.

Coméntame cómo te va. Saludos 👋💻

**Comment by ExRage2000** [comment]
A mi me salió lo mismo pero apreté aceptar e igual se instaló ¿debería estar preocupado? .-.

**Comment by lily416** [comment]
Hola @ExRage2000,

Sinceramente no sé si debas estar preocupado 😅
Si pudiste configurarlo correctamente y si al usar VSC no tienes problemas escribir y correr tu código, probablemente todo está bien.

Cualquier problema que puedas tener durante el semestre, no dudes en hacer una issue al respecto 😄 

Saludos y que te vaya bien en la actividad de hoy 👋🐛
