### ISSUE TITLE
Problema con la función print_tablero()

### ISSUE THREAD

**Issue by SamWeinstein** [IIC2233/syllabus#44]
Hola! Al usar la función print_tablero me printea un tablero pero mostrando las "L". Según yo tenía entendido, a la función se le podía entregar un tablero con legos, pero el juego no funciona si los legos se muestran. Habrá que mantener los legos como " " y hacer que el programa conozca sus posiciones mediante "otro" tablero analogo para que el usuario no los vea? o hay alguna forma de darle a la función un tablero con legos y que se vean como celdas cubiertas?

un ejemplo de argumento que le entrego a la función sería el siguiente: 

[[' ', ' ', ' ', 'L'], [' ', 'L', ' ', ' '], [' ', ' ', ' ', ' '], [' ', ' ', ' ', 'L']]

**Comment by jmwielandt** [comment]
Hola! 😄

Lamentablemente no te podemos responder eso 😢, ya que es parte de lo que esperamos que ustedes sean capaces de responder. Lo que sí te puedo decir es que la función `print_tablero` solamente se encarga de imprimir bonito lo que le pasan y tú debes manejar el estado a mostrar. Si le pasas una 'L' en la lista, la va a imprimir.

Mucho ánimo con la tarea!
Saludos~

**Comment by SamWeinstein** [comment]
muchas gracias! esa era mi duda
