### ISSUE TITLE
Uso de Clases

### ISSUE THREAD

**Issue by benjaalvarez** [IIC2233/syllabus#44]
¡Hola!

¿Es estrictamente necesario usar Programación Orientada a Objetos en la Tarea 00?
Hasta ahora no la he utilizado y me ha funcionado todo, pero en el primer objetivo en el enunciado de la tarea dice "Aplicar competencias asimiladas en Introducción a la Programación para el desarrollo de una solución a un problema". ¿Esto implica que debemos usar necesariamente OOP?

Desde ya, ¡muchas gracias!

**Comment by Tito0906** [comment]
Holaa @benjaalvarez , es uso de POO no es obligatorio en esta tarea pero es altamente recomendado debido a varias razones:

- Uno de los objetivos fundamentales de esta tarea es que se acostumbren y recuerden cómo usar objetos, ya que serán necesarios para el resto del curso.
- El uso de objetos en esta tarea facilita la redacción y organización del código.
- Más adelante se pasará más materia de objetos, por lo que si no practican sus usos básicos ahora, después podría ser mucho más difícil entender las materias nuevas.

**Comment by benjaalvarez** [comment]
Ok ¡Muchas Gracias!
