### ISSUE TITLE
Dudas sobre el menú de inicio

### ISSUE THREAD

**Issue by mvveram** [IIC2233/Syllabus#44]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola,
Tengo una duda acerca de que tan a prueba de errores de usuario debe ser este menú. Por ejemplo, si le pido un `int`, ¿el "usuario" me podría dar un `string` o un `float`?. En ese caso, ¿debo contemplar todos estos tipos de errores en mi código? Porque me imagino que no se puede caer el programa por alguna de estas equivocaciones.

Muchas gracias de antemano

**Comment by victoriaatria** [comment]
Hola! Todos los menús deben ser a prueba de cualquier error de usuario. Es decir, debes contemplar que el usuario podría ingresar strings, floats etc.. y tu programa debe ser capaz de capturar todos estos errores sin caerse. Espero haya quedado claro!
