### ISSUE TITLE
Tecnología: Medicina

### ISSUE THREAD

**Issue by StroveLight** [IIC2233/syllabus#44]
Al descubrir la medicina, el hp máximo sube a 1.5 veces del hp actual (ya que se dice que cuando hp_max!=hp_actual, se considera hp_actual);
la pregunta es, si el nuevo hp máximo sería menor que el actual hp máximo, se debe actualizar el hp maximo? o la consideración es para no subirle el hp al herido al máximo?

ejemplo:
hp actual = 2;
hp maximo = 10;
--se descubre la medicina--
hp maximo = 3?
hp actual = 7 y hp maximo = 15?
se mantienen los datos originales?

**Comment by BFFV** [comment]
Hola!
Para las personas ya creadas se debe utilizar su HP actual (la idea es que se sanan un poco gracias a la medicina), mientras que para las nuevas personas que se creen en el futuro se deberá aplicar sobre su HP máximo (la medicina permite una mayor esperanza de vida para las nuevas generaciones).

**Comment by StroveLight** [comment]
gracias~ ^^
