### ISSUE TITLE
Tasa minerales/deuterio por segundo

### ISSUE THREAD

**Issue by antoniacobo** [IIC2233/Syllabus#44]
Dice que es un número aleatorio entre 1 y 10. Este numero tiene que ser un int o puede ser un float?
Lo mismo con cualquier otro numero aleatorio?

**Comment by NicolasCourt** [comment]
Por lo que yo entendi del enunciado tienen que ser enteros, si lo especificas en el README no deberias tener problemas

**Comment by ptflores1** [comment]
Holaa ! Queda a su criterio.
Saludos
