### ISSUE TITLE
Manejo de dcciudad

### ISSUE THREAD

**Issue by abarrientosj** [IIC2233/Syllabus#44]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

**Hola tengo la duda de como hacer que los test_case entiendan que he ocupado las funciones que se entregan (alcanzable e.g)**
Ya que, en las funciones tengo todos los test case buenos salvo esos, entregándome este tipo de errores:
AssertionError: Expected 'elevar_matriz' to have been called.
AssertionError: Expected 'alcanzable' to have been called.
Siendo que claramente las he usado

**Comment by SSParzival** [comment]
Hola, muy buenas. 

¿En qué archivo se provocan dichos errores? Agradecería igualmente si pudieras contar información de tu sistema operativo y versión de Python que estás usando. 

Asimismo, si puedes, sería de mucha ayuda que puedas subir tu código a tu repositorio privado, para verificar qué está sucediendo exactamente.

Quedo a la espera.

**Comment by abarrientosj** [comment]
Hola de nuevo, 
Los errores se presentan en red.py (mi código), en las funciones nivel_conexiones y ciclo_mas_corto.
Mi sistema operativo es OS Sonoma 14.0 y estoy ocupando la versión 3.11.7 de python.
De todas maneras, ya subi mi codigo al repositorio personal.
Muchas gracias

**Comment by SSParzival** [comment]
Buenas, muchas gracias por subir tu código; se logró con ello entender el problema que está sucediendo.

Por la implementación actual de los tests, estos solamente funcionan correctamente cuando en red.py se realiza un import dcciudad, y luego para los métodos en red.py se hace un llamado a dcciudad.alcanzable o dcciudad.elevar_matriz. En tu caso, como escribes algo de la forma: from dcciudad import alcanzable..., entonces el test falla porque no contempla dicho caso. Puedes intentar cambiar eso en tu código ahora para que los tests públicos te salgan buenos; aunque para la corrección final de los tests se admitirán imports de las dos formas.

Se está trabajando en una manera de que los tests funcionen correctamente con ambas maneras de importación válidas, y será informada a la brevedad.

**Comment by Hernan4444** [comment]
Hola, se actualizó al Syllabus para abordar el problema mencionado en esta issue, y en la issue #42. Que corresponden a las 2 issues marcadas como **Importante** hasta el momento.

En este caso, se actualizaron los tests para aceptar tanto que hagan `import dcciudad` o `from dcciudad ....`. Así no es necesario actualizar su código para que los tests publicos salgan totalmente correcto.

Saludosヾ(＾-＾)ノ
