### ISSUE TITLE
Ejecución de la actividad 0 en la terminal

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#44]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Holaa. Cuando quiero ejecutar mi código ubicado en main.py, lo busco y lo ejecuto en la terminal. Sin embargo, retorna lo siguiente: cd: not a directory: main.py. Busqué en internet y supuestamente hay 2 posibles razones, la primera es que no estoy en la carpeta adecuada, y la otra posibilidad es que no existe un archivo llamado main.py. Pero ya revisé ambos casos y el problema sigue.

**Comment by R3Y3X** [comment]
Hola, puede ser porque estas desde main.py intentando correrlo, puedes intentar correrlo desde la carpeta donde tienes el archivo usando cd .. para volver al directorio anterior y luego ejecutar py main.py recuerda que puede ser (py, python, python3), avísame como te va.

**Comment by martinpint** [comment]
Ahora sí funciona, había olvidado esa parte. Graciass
