### ISSUE TITLE
Dudas enunciado

### ISSUE THREAD

**Issue by lefischer** [IIC2233/Syllabus#44]
Hola, 

tengo varias dudas
1. cuando en la seccion 4.2.3 dice que cualquier cambio  producido durante la ejecucion del programa debe verse reflejado en las bases de datos se refiere a agregar usuarios, pronosticos metereologicos, y agregar incendios o algo mas.

2.  no entiendo como al ingresar una fecha se supone que se sabe que recursos estan movilizados y cuales no.  Se deben conectar con las estrategias de extincion? que pasa si se hace una estrategia un día x y  despues se ingresa al programa el dia x-1. se debe considerar la existencia de esa estrategia?

3. cuando debo considerar que actuan los recursos sobre un incendio?
 
para solucionar lo anterior se me ocurre que se pueda guardar la fecha del ultimo ingreso y que solo se pueda ingresar a una fecha que esta en el futuro, entonces asi se puede ver el efecto de las estrategias de extincion y que esta comienza a funcionar desde que fue planeada hasta que se planee otra que para el mismo incendio. es valido?

**Comment by rpalmaotero** [comment]
> cuando en la seccion 4.2.3 dice que cualquier cambio producido durante la ejecucion del programa debe verse reflejado en las bases de datos se refiere a agregar usuarios, pronosticos metereologicos, y agregar incendios o algo mas.

En la misma sección se indican los permisos, de acuerdo a los roles de usuario, para mutar las tablas. Esos cambios son los que deben persistir entre ejecuciones del programa. 

> no entiendo como al ingresar una fecha se supone que se sabe que recursos estan movilizados y cuales no. Se deben conectar con las estrategias de extincion? que pasa si se hace una estrategia un día x y despues se ingresa al programa el dia x-1. se debe considerar la existencia de esa estrategia?

Exacto, que un recurso se movilice o no depende si alguna estrategia así lo dispone. Si se "viaja al pasado" se deben considerar estrategias que fueron calculadas en el "futuro" para no disponer de recursos que puedan estar ocupados. Por ej., si se dispone de un recurso `r` en una estrategia calculada el tiempo `t`, al momento de calcular una estrategia en `t - 1` se debe considerar que el recurso `r` puede estar ocupado en el futuro. 

> cuando debo considerar que actuan los recursos sobre un incendio?

Citando el enunciado: *La estrategia de extinción consiste en un detalle de todos los recursos que son necesarios movilizar para extinguir un incendio. Para cada movilización de un recurso se debe mostrar la hora de salida del recurso, hora de llegada al incendio, hora de retirada y hora de regreso a la base*. Una estrategia planifica las horas de movilización de los recursos, por lo tanto actúan apenas la estrategia así lo determina.

**Comment by lefischer** [comment]
@rpalmaotero gracias!

me surgió otra duda, si un plan va a usar un recurso n veces durante x dias, se puede asumir que esta reservado por ese tiempo y que no puede ser considerado para estrategias que actuan durante ese tiempo.

**Comment by NicolasCabello** [comment]
Hola, agregando a consultas, en el 4.1 (Base de datos) en la 4ta linea dice "Cabe destacar que en el formato csv el orden de las columnas puede variar", es decir, cuando ejecuten el programa las columnas no necesariamente estaran en el mismo orden como se nos fue entregado?

**Comment by Hernan4444** [comment]
@NicolasCabello  Exactamente!! el orden puede cambiar y todo eso se vera reflejado en el head del csv.

Saludos!!!

**Comment by rpalmaotero** [comment]
@lefischer ningún recurso puede usarse simultáneamente en distintas estrategias.

**Comment by lefischer** [comment]
hola,

cuando un usuario de la pide leer filas, se refiere a todas las filas, o a una especifica

**Comment by rpalmaotero** [comment]
Punto a punto:

2. Cuando entra a la zona afectada.
3. El enunciado dice: "Para que una condición meteorológica afecte un incendio, basta que los sectores circulares del incendio y el pronóstico se intersecten.". No puedes asumir lo que dices.
4. Eso es lo que hay que hacer.

La pregunta 1 no la entendí bien, si puedes reformularla sería genial.

**Comment by lefischer** [comment]
hola, respecta a la 1 me refiero a lo enunciado en la descripcion del usuario anaf que dice que puede leer las filas de las bases de datos

**Comment by rpalmaotero** [comment]
@lefischer una en específico.
