### ISSUE TITLE
Día en que suceden los eventos

### ISSUE THREAD

**Issue by nivek0o0** [IIC2233/Syllabus#440]
Con respecto al día de la semana en que suceden los eventos: ayudantía,  publicación/entrega de tarea, reunión oficina profesor

a) los modelamos como en la realidad (martes y viernes)
b) elegimos al comienzo de la simulación un día al azar de la semana
c) cualquier otra forma pero especificada en el ReadMe

**Comment by cilopez** [comment]
Me sumo para preguntar que día de la semana sería el día 0, es decir con el que parte la simulación

**Comment by rpalmaotero** [comment]
No está especificado, queda a tu criterio. De todas maneras, recomendamos hacerlo de la forma a).

**Comment by nivek0o0** [comment]
Gracias @rpalmaotero.
