### ISSUE TITLE
leer consultas.json

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#440]
No sé si estoy entendiendo mal el enunciado, pero ejecuto main.py, se abre la interfaz y no veo ninguna barra de opciones en la interfaz donde pueda seleccionar la opción "Abrir". Lo que veo es esto:

![image](https://user-images.githubusercontent.com/30670535/31296126-9b376446-aab7-11e7-9b58-b7c98fb54262.png)

**Comment by jfbahamondes** [comment]
Archivo -> Abrir
