### ISSUE TITLE
duda Descuento en función pedido_con_mayor_descuento_utilizado

### ISSUE THREAD

**Issue by bernarditaaliaga** [IIC2233/Syllabus#440]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/Syllabus/issues/420).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

esta funcion debe retornar un iterable con instancias de contenidoPedido que tengan el mayor descuento, pero *el mayor descuento con respecto a que?* ¿o acaso todos los pedidos que tengan descuento? no encuentro donde lo especifica, o

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Vicente1824** [comment]
¡Hola @bernarditaaliaga 😀! Todas los pedidos de `contenido_pedidos` tienen el atributo `descuento`. Este podría ser 0 (sin descuento) u otro valor (si hay descuento). Esta función pide que busques aquellas instancias que tengan el mayor descuento de toda la base de datos que estás trabajando (el archivo `contenido_pedidos.csv` correspondiente, en este caso) y retornar un iterable de estos pedidos.
Entonces, por ejemplo, si se tiene un pedido con descuento 0, otro con descuento 0.1 y otro con descuento 0.2, esta función **retornaría un iterable con el pedido que tiene descuento 0.2**.
Recuerda considerar que podrían haber casos de empate, y en estos, se tendrá que retornar todas las instancias que tengan el descuento mayor encontrado.

**Comment by bernarditaaliaga** [comment]
ahhh ya pero en casos de no empate solo tendría que retornar una sola instancia, perdón es que todavía no me queda claro que objetos son iterases o no, pero perfecto entonces en ese caso solo seria una lista con un solo elemento. 
gracias vicente!

**Comment by Vicente1824** [comment]
¡En casos de no empate (por lo que habrá solo una instancia con el descuento mayor) se debería retornar un **iterable** que solo tenga una instancia (la con más descuento)! ¡Espero que te sea de ayuda 👌!
