### ISSUE TITLE
Duda código problema DCCorreo ayudantía 6.5

### ISSUE THREAD

**Issue by aagodoy1** [IIC2233/syllabus#440]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola una consulta, lo que pasa es que estaba intentado hacer la ayudantía 6.5 y el código mostrado para abrir la ventana inicial solo con el logo fue este. 

def init_gui(self):

        self.setWindowTitle("DCCorreo")
        self.setGeometry(500, 100, 900, 500)

        logo = QLabel("", self)
        pixmap = QPixmap("Data/logo.png")
        logo.setPixmap(pixmap)

La cosa es que yo intenté con uno que me había servida para la actividad pasada:

    def init_gui(self):
        self.setWindowTitle("DCCorreo")
        self.logo = QLabel()
        self.logo.setGeometry(500, 100, 900, 500)

        pixmap = QPixmap("Data/logo.png")
        self.logo.setPixmap(pixmap)

Pero no funciona, me pueden ayudar ?? No cacho porqué antes funcionaba y con esta ayudantía no :c Solo me abre una ventana sin nada dentro.

**Comment by Pablok98** [comment]
Si aún no estas utilizando *layouts*, lo que está pasando acá es que el *label* del segundo código no tiene definido un *parent*, por lo que no pertenece a nadie y no se muestra. Fijate entre los dos código la definición de `QLabel()` vs `QLabel("", self)`, en el segundo caso se le está entregando el padre (además de un texto vacío). 

Tu propuesta debería funcionar si creas el *label* con `QLabel(self)`
