### ISSUE TITLE
15 lineas en funciones anidadas

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#440]
Hola tengo de como se aplica el criterio de las 15 lineas  en casos como definicion de funciones dentro de otras y en decoradores.
ej 1:
def funcion1():
----def funcion2():
--------#lineas
--------return algo
----otra_cosa = funcion2()
----#lineas
----return algo

ej 2:
def constructor():
----def decorador(funcion):
--------def decorada():
-------- ----#hacer algo
------------return funcion()
--------return decorada
----return decorador

**Comment by Hernan4444** [comment]
Por favor revisar issues anteriores que tratan ese tema, seguir la conversación ahí y no abrir una nueva
