### ISSUE TITLE
multa escape/pregunta identación

### ISSUE THREAD

**Issue by tolavarria** [IIC2233/syllabus#440]
tengo dos preguntas:
1) Si el magizoologo recupera una criatura el mismo día que se escapó ¿igualmente se le aplica la multa?
2) ¿como puedo agregarle los mismos espacios de identación a varias filas ya existentes? (por ejemplo, si se me olvidó poner un "while" antes que el resto del codigo en una función)

**Comment by furcelay** [comment]
Hola!
No soy ayudante pero creo que puedo responder tus preguntas (después verifica con un ayudante, pero al menos para que no te quedes pegado en eso):

1. Las multas se cobran **al comienzo del día**, antes de que puedas realizar cualquier acción, por lo que sí se cobraría la multa.

2. En tu IDE debes tener configurado el tipo de identación (espacios o tabs) para que sea de 4 espacios (suele ser la opción por defecto), si no lo tienes configurado googlea algo como "vs code change indentation size" o "vs code set tab size" (obviamente cambiando "vs code" por el IDE que utilizas). Cuando tienes la identación ajustada a 4 espacios estos se insertan cada vez que presionas la tecla `Tab`, y puedes identar múltiples filas seleccionandolas y presionando `Tab` (puedes eliminar una identación con `shift + Tab`)

**Comment by JosefaPaz** [comment]
¡Hola @tolavarria !

1. Tal como dice @furcelay, al pasar al día siguiente ocurren los siguientes eventos:

![imagen](https://user-images.githubusercontent.com/41802643/79136061-627e0a00-7d7e-11ea-9f30-3597675651d8.png)

Por lo que después de fiscalizar, ahí recién podrías acceder a las opciones como recuperar / alimentar / etcétera.

2. Si se te olvidó un while por ejemplo, lo más recomendable es lo que dice @furcelay. Seleccionas todas las líneas de código a identar y le das ```tab``` para correrlas 4 espacios más allá.

¡Éxito!
