### ISSUE TITLE
Diccionario

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#440]
Hola! Tengo un problema con el diccionario, intente crear variables mediante for y luego esas variables guardarlas como key en un diccionario pero me sale esto "local variable 'a' referenced before assignment", hay alguna forma de poder guardar variables y luego guardarlas en un diccionario?

**Comment by furcelay** [comment]
Hola @Natydlb,
El error que mencionas ocurre cuando intentas usar una variable que aún no ha sido definida en el programa y es probable que se deba a un error de sintaxis. En general la forma de crear un diccionario en un loop es por comprensión, suponiendo que tienes una lista con *keys* y otra con *values*:
```python
my_dict = {key: value for key, value in zip(key_list, value_list)}
```
En particular lo que mencionas sobre crear variables y luego usarlas como *key* en un diccionario, lo mejor es que te preguntes primero si esa variable tiene sentido fuera del diccionario. Si no tiene sentido su existencia fuera del diccionario lo mejor es crearla exclusivamente dentro de éste. Además no todas las variables pueden ser usadas como *key*, solo las que son inmutables (*strings, int, etc.*) en particular las que son *hasheables* (tienen el método `__hash__()` para encontrarlas), porque de otro modo si cambias la variable fuera del diccionario ya no podrías encontrarla dentro de él.

Espero haber aclarado tu duda! si no es así vuelve a comentar en la *issue* :smile:
