### ISSUE TITLE
parametros.py

### ISSUE THREAD

**Issue by isidonoso** [IIC2233/syllabus#440]
Es necesario que el tamaño de las barras de progreso y la ubicación de los elementos en la ventana de juego estén en el archivo de parametros.py? Porque hice el tamaño de la ventana acorde al tamaño del mapa, pero las opciones que tienen que estar en el lugar preciso para que se vea bien, sino se desordena todo y no aparecen bien en la pantalla

**Comment by gatochico** [comment]
Hola! No es necesario que esas cosas vayan en parametros.py , ya que no es algo que vayamos a cambiar.
