### ISSUE TITLE
Duda pregunta 4 midterm 2024-1

### ISSUE THREAD

**Issue by DiegooDSC** [IIC2233/Syllabus#441]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Contenido
Holaa, no entiendo la pregunta 4 del midterm del 2024-1 
![Captura de pantalla 2024-10-02 125007](https://github.com/user-attachments/assets/77409c7b-d2a0-432a-a898-7c474a5e3086)
Yo llegué a deque([6, 1, 3, 6, 8]), pero la alternativa correcta es la E) deque([8, 1, 3, 8, 10]). Bacán si me pueden explicar el paso a paso de como llegaron a eso

**Comment by 3rdPix** [comment]
Hola @DiegooDSC !

Puedes revisar la #433 donde hay un ejercicio semejante. Me cuentas si tienes mas dudas!

Saludos 🦎
