### ISSUE TITLE
Posible Error test_19_personas_no_asisten

### ISSUE THREAD

**Issue by joacopython** [IIC2233/Syllabus#441]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/396)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/395)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

En el test 0 encontre un posible error, ya que las personas que espera no son todas las que cumplen las condiciones del enunciado. Las personas que espera la funbción son  las siguientes:
            Personas(id=645321, nombre='Diego', genero='Masculino', edad=39),
            Personas(id=359827, nombre='Luis', genero='Masculino', edad=84),
            Personas(id=673894, nombre='Felipe', genero='No binario', edad=19),
            Personas(id=518367, nombre='Mateo', genero='Femenino', edad=77),
Sin embargo no contempla a otras tres personas las cuales hicieron su reserva fuera de la fehca de inicio y final:
            Personas(id=926242, nombre='Martina', genero='Femenino', edad=36)
            Personas(id=372615, nombre='Jimena', genero='Masculino', edad=72),
            Personas(id=596318, nombre='Martín', genero='Masculino', edad=81),
Y estas tres personas tienen en común que asistitran a la misma funcion:
            Funciones(id=7617, numero_sala=6, id_pelicula=11615401, horario=5, fecha='05-12-23'),
La cual esta fuera del rango de fechas:
            fecha_inicio = "02-12-2023"
            fecha_termino = "03-12-2023"

**Comment by gecoli** [comment]
¡Arreglado!

Gracias por el aviso ꒰ᐢ. .ᐢ꒱₊˚⊹
