### ISSUE TITLE
Problema cancion

### ISSUE THREAD

**Issue by gicrot** [IIC2233/syllabus#441]
Hola, en mi tarea puse música de fondo, el problema es que pesa 25MB y no se si subirla u omitirla por temas de que pesa harto más el juego con eso, o también no se si me descontarán por subir un archivo tan pesado

**Comment by entamburini** [comment]
Hola @gicrot! 

La verdad es que no me gustaría tener que bajar tu música de fondo, me llama la atención lo pesada que es, normalmente las canciones (a menos que sean de super buena calidad) no llegan a pesar eso, por lo que te recomendaría una canción más liviana (de unos 4 MB te la podría aceptar).

Una forma chora de hacerlo es con un try/except, que verifique si está la canción, en caso de que no esté, dar el link para bajarlo y decir qué nombre y dónde tiene que ir... eso en caso de que quieras usar la música de 25 MB de peso 😅.

Me gusta tu motivación y sé que llegarás a una solución a tu problema, por ahora, te pido que no la subas porque es muy pesada, pero si consigues una versión ligera, adelante :D 

Saludos! ✌️
