### ISSUE TITLE
elementos de un generador

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#441]
Después de recorrer un generador éste se pierde. Si dentro del generador había creado cosas como listas o diccionarios, ¿estos también son borrados de la memoria junto con el generador?¿o cuando tuvieron que ser instanciados se instanciaron como cualquier lista o diccionario sin que python identificara que estaban dentro de un generador y, por lo tanto, al borrarse el generador esas listas y diccionarios siguen existiendo en algún lugar de la memoria?

**Comment by mjgutierrez1** [comment]
Agrego otra duda:
¿las variables que creo dentro de una función y que sólo las uso ahí (es decir, que no las agrego o guardo en algún objeto [como por ejemplo una lista] que esté fuera de la función) se borran luego de que se ejecuta la función? Si la respuesta es sí, ¿entonces las variables dentro de las funciones son similares a un generador, en el sentido de que se instancian sólo cuando son necesarias (cuando se ejecuta la función) y luego se borran?

**Comment by indonoso** [comment]
Vamos por lo básico. Todo lo que se define dentro de una función y que no tiene variables que apunten a él será eliminado del programa por el [recolector de basura](https://www.quora.com/How-does-garbage-collection-in-Python-work-What-are-the-pros-and-cons). 

Ahora no entiendo tu pregunta del generador. Te refieres a una función generadora?
``` python
def funcion_generadora():
  i = 0
  while True:
    yield i
    i += 1
```
En este caso ocurre lo mismo que con una función: todo lo que se defina aquí será eliminado cuando termine de ejecutar. Además las variables definidas aquí son independientes de las variables definidas fuera. Por ejemplo:
``` python
a = funcion_generadora()
print(next(a))
print(i)
```
Esto lanzará el error`NameError: name 'i' is not defined`, porque no hemos definido la variable `i`.
