### ISSUE TITLE
Habilidad especial Erkling 

### ISSUE THREAD

**Issue by anamarn** [IIC2233/syllabus#441]
Hola !
En el enunciado dice que si el Erkling esta hambriento al pasar el dia, le robara alimento al dueño y pasara a estar satisfecho. De ahí se me vino la duda, vienen a aplicar los efectos de salud y especiales del buñuelo, de la tarta y del hígado? Eso significaría que si no le sale el efecto del buñuelo , volverá a robar, o pasar a estar satisfecho?

Saludos

**Comment by mpsubiabre** [comment]
Hola @anamarn ! 336

Si se aplicaran todos los efectos! Sin embargo como no se explicita en el enunciado, para el caso de el **Buñuelo**, el estado del hambre queda a criterio del alumno. Es decir si robase Buñuelo de Gusarajo, la probabilidad de rechazo queda anulada o funciona normalmente y puede quedar insatisfecho (revisa la #issue336).
Lo que si se debe cumplir es que robe solo una vez alimento.

Exito con la tarea 😄
