### ISSUE TITLE
Problema para encontrar Qt Designer

### ISSUE THREAD

**Issue by ArielGoldzweig** [IIC2233/syllabus#441]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

[Describe tu problema de manera detallada, explicando qué estás intentando hacer y explicando los errores o problemas que has encontrado. Se recomienda agregar fotos cuando sea posible]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola, en otra issue dijeron que con este comando "pyqt5-tools designer" podemos encontrar a QtDesigner pero al ocuparlo me aparece este error:
![image](https://user-images.githubusercontent.com/80789622/117209009-cd541600-adc3-11eb-968a-687ed00c06b4.png)

Esto me aparece con este comando "pip show pyqt5-tools"  :

![image](https://user-images.githubusercontent.com/80789622/117209326-33409d80-adc4-11eb-9f5c-100fef111198.png)

**Comment by aaossa** [comment]
Hola @ArielGoldzweig , ¿podrías revisar si está designer.exe en la ruta que aparece en mi comentario en #420 ? También, ¿te aparece designer si usas el buscador de Windows?

**Comment by ArielGoldzweig** [comment]
No me aparece en el buscador y tampoco me sirvió la ruta.

**Comment by Pablok98** [comment]
@ArielGoldzweig ¿Hasta que "parte" de la ruta puedes llegar? Es decir, ¿existe el directorio `../Qt/bin` por lo menos? 

Otras preguntas para intentar identificar el problema:

1. En la carpeta de `site-packages` donde buscaste el designer, ¿te sale la carpeta `pyqt5_tools`?
2. ¿Tienes o has alguna vez instalado anaconda?
3. ¿Existe la posibilidad de que tengas más de una instalación de python? Puedes verificar esto con el comando `py -0p`
4. ¿Probaste borrar `pyqt5-tools` y `pyqt5`, y luego reinstalarlo?

Lamentablemente, son muchos factores los que pueden afectar, pero estas preguntas podrían ayudar significativamente a identificar tu problema 😀

**Comment by ArielGoldzweig** [comment]
1. Si 
2. Lo tuve instalado
3. 
![image](https://user-images.githubusercontent.com/80789622/117234407-ed4efe00-adf2-11eb-9b17-5e68b5683aba.png)
4. Si y no funciono

**Comment by Pablok98** [comment]
Viendo el error que te sale, existe la posibilidad de que anaconda haya dejado algún problema con tu instalación de python (con las variables de entorno y/o paquetes). Siguiendo algunos de los procedimientos que hicimos en la issue #433, podríamos revisar las variables de entorno de python.

Puedes crear un archivo de Python, importar sys y luego escribir print(sys.path). Luego por favor sube una foto de lo que te sale.

Alternativamente puedes hacer la siguiente serie de comandos en la consola:
python
import sys
print(sys.path)
Y mandarme el resultado.

**Comment by ArielGoldzweig** [comment]
![image](https://user-images.githubusercontent.com/80789622/117235153-2dfb4700-adf4-11eb-8f25-d3b0a395aa08.png)

**Comment by Pablok98** [comment]
¿Qué te sale en la carpeta que debería contener el designer?

**Comment by ArielGoldzweig** [comment]
![image](https://user-images.githubusercontent.com/80789622/117235975-c1814780-adf5-11eb-9c7f-45b05b56855f.png)

**Comment by Pablok98** [comment]
La carpeta que contiene el desinger es

`site-packages/qt5_applications/Qt/bin`

Me podrías mostrar una foto de esa carpeta porfavor

**Comment by ArielGoldzweig** [comment]
![image](https://user-images.githubusercontent.com/80789622/117236318-7582d280-adf6-11eb-961f-f4c337c4b3ae.png)
![image](https://user-images.githubusercontent.com/80789622/117236375-8c292980-adf6-11eb-808c-409baae6535c.png)
![image](https://user-images.githubusercontent.com/80789622/117236396-9c410900-adf6-11eb-800c-93e1aa6d78fa.png)
![image](https://user-images.githubusercontent.com/80789622/117236430-a95df800-adf6-11eb-9336-e3ffcc565bce.png)

**Comment by Pablok98** [comment]
Que raro, pareciera que tienes todos los ejecutables excepto el designer. Es un poco fuerza bruta, pero podemos probar copiando y pegando un `designer.exe` en tu carpeta. Hablame por discord y te lo paso, mi usuario es San Ahoria

**Comment by Pablok98** [comment]
Si alguien ve este issue y está con el mismo problema, me escriben para pasarles el `designer.exe`
