### ISSUE TITLE
.gitignore Tarea

### ISSUE THREAD

**Issue by constanzacontreras** [IIC2233/syllabus#441]
Hola!
Acabo de subir mi tarea con el .gitignore, y creo que se subió bien, pero está subida la carpeta de sprites etc de la entrega avance (como ahí no era necesario subirlo con el gitignore).  ¿Que me recomiendan hacer? Igual ahí sale que lo subido actual es hace segundos, en cambio lo anterior es hace 12 días aprox.
Muchas gracias

**Comment by tomishishigang** [comment]
Hola, 
tienes que hacer git rm -r nombre_archivo asi borras las carpetas o archivos de tu repositorio

**Comment by gatochico** [comment]
Tal como dice tu compañero, hay [maneras ](https://stackoverflow.com/questions/9701238/git-how-delete-file-from-remote-repository)de eliminar los archivos de tu repositorio remoto. Por lo tanto, no deben estar en tu entrega final.  Éxito!

**Comment by ByronHidalgo1** [comment]
Hola, aún no entiendo bien lo del gitignore.
Simplemente subí dicho archivo que tenia escrito:
sprites/
mapas/
¿es suficiente?
Además no subí ninguna carpeta de Sprites o Mapas

**Comment by Hernan4444** [comment]
Hola,

Si el archivo solo tiene 
```
sprites/
mapas/
```

Lamento informar que no es suficiente. En el enunciado se especifica que no suban el enunciado y en la última línea de ese fragmento, dice:

![image](https://user-images.githubusercontent.com/15641721/58449376-4d9e7680-80d9-11e9-8c60-3d7ba4a74ea4.png)

Y por lo tanto, aunque no lo hayas subido, si no está el `Enunciado.pdf` en el `.gitignore`,  implica que no hubo un correcto uso.

Saludos

**Comment by ByronHidalgo1** [comment]
Y qué me descontaría menos puntaje? Hacer push de nuevo o dejarlo así? :c

**Comment by Hernan4444** [comment]
Hola,

No utilizar correctamente el `.gitignore` son 2 décimas, mientras que la entrega atrasada parte de las 5 décimas. Por lo tanto se recomienda dejarlo así para minimizar el descuento.


Saludos

**Comment by mimunoz11** [comment]
¿porque interpretan que no agregar enunciado.pdf en el .gitignore es un mal uso de este? por lo demás el enunciado no especifica que enunciado.pdf debía estar en mi carpeta local, habla de archivos en general

**Comment by Hernan4444** [comment]
Porque se especificó en el enunciado que no lo subieran. Fue un requerimiento para poder evaluar que sepan ignorar tanto un archivo específico y como carpetas.

**Comment by Hernan4444** [comment]
Hola
Como equipo se reconsideró esta situación y solo por esta tarea, como es la primera que se les pidió trabajar con `.gitignore`, se aceptará el que no esté totalmente como se indicaba en el enunciado. En particular: Se aceptará que el `.gitignore` ignore solo las 2 carpetas, mientras que en el repositorio no haya nada extra (como __pycache__ o enunciado.pdf). 

**Pero** para la T03, si se les pide no subir un archivo en particular, deben hacer eso mediante el uso de `.gitignore` para evaluar que no solo sepan ignorar carpetas, sino archivos específicos.

Saludos :v:
