### ISSUE TITLE
Dudas iniciales

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#441]
Algunas dudas:

1) Creo que lo leí pero ahora no lo encuentro en este extenso enunciado. ¿Cuantos alumnos , ayudantes, secciones son?

2) ¿La cantidad de horas mínimas diarias es de una hora para la tarea y 25 minutos para la materia? ¿La cantidad de horas mínimas semanales para la materia es de 1 hora y 45 minutos? ¿Como determino la cantidad real de horas diarias que dedicara al curso día a día? 

3) La probabilidad de tener una personalidad u otra es igual para las tres personalidades?

Disculpen si estas respuestas están en el enunciado. Lo leí, pero es extenso y complicado de entender todo al principio.

Gracias.

**Comment by cilopez** [comment]
1.- Eso sale en el archivo integrantes.csv
3.- Tome el mismo supuesto y no sale en el enunciado

**Comment by jorgeriesco** [comment]
¿Pa que hay una ocurrencia en la toma de créditos si eso esta en el archivo escenarios?

**Comment by cilopez** [comment]
Creo que para tener valores por defecto y para que se entienda mas el enunciado

**Comment by KnowYourselves** [comment]
Existen esos valores porque en caso de que en el escenario no este esa informacion se rellena con el default

**Comment by indonoso** [comment]
@jorgeriesco el archivo es un pdf. Puedes usar `Ctrl+f` y buscar por palabras claves.

**Comment by nivek0o0** [comment]
Se supone que en LET también se enseñaba redacción.
¿Por qué no se ponen el tag a ustedes?
Por algo será que cada Tarea tiene más de 100 issues....

**Comment by cpieringer** [comment]
Estimado @nivek0o0 ,

entiendo tu molestia, sin embargo, en las reglas del foro dice: "El foro no es un medio de reclamos." Estamos trabajando fuertemente para que en cada actividad o tarea reciban la información de la mejor manera para que la puedan resolver. Lamentablemente queremos evitar que abran issues por cosas que les de "lata" buscar en el enunciado. Tienen herramientas suficientes para hacer ese tipo de búsquedas. Indudablemente hay cosas que se nos pueden pasar, como también es difícil intuir todas las preguntas que ustedes puedan tener. Para eso existe este foro de consulta. Cualquier comentario también es bienvenido dento de un contexto de respeto. En este sentido, tu respuesta no me parece adecuada. Si necesitas hacer algún reclamo existe un formulario en el sitio del curso, y también te invitamos cordialmente a que nos visites personalmente, estaremos muy felices de recibir tus comentarios.

Saludos cordiales y éxito con tu tarea.

**Comment by nivek0o0** [comment]
Profesor @cpieringer 

mi molestia es por una issue en particular (#440). Eso no sale en el enunciado así que el argumento de "te dio lata buscar en el enunciado" no es válido en este caso. Si uno pregunta es para asegurarse de que no será mal evaluado y luego no tener que recorregir. Costaba absolutamente nada responder a), b) o c) a mi pegunta. Creo que es menos trabajo para ustedes responder una issue que responder una recorrección, cambiar la distribución de puntaje, la nota, etc. 

Por último, cerrar y taggear una issue sin motivo alguno no me parece un contexto de respeto.

Saludos.

**Comment by glbello** [comment]
Estoy de acuerdo con @nivek0o0 en cuanto creo que es inneceario el tag de LET0003, creo que es suficiente con responderle al que pregunta que eso está en el enunciado y esperar que el alumno se de cuenta, y cerrar el issue cuando el alumno confirme que lo encontró o esperar algunos dias para cerrarlo si este no responde.

**Comment by cpieringer** [comment]
Estimado @nivek0o0 ,

lamento el mal entendido, pero mi respuesta está en relación a esta issue ( #441). Cualquier comentario o reclamo que puedas tener sobre algún tema en particular, como las que mencionas, por favor envíala a través del formulario en el sitio del curso.
