### ISSUE TITLE
test elementos prohibidos

### ISSUE THREAD

**Issue by scovarrubiasm** [IIC2233/Syllabus#441]
Cuando paso el test de elementos prohibidos significa que la programacion de esa funcion es la correcta con respecto al uso de listas tuplas set etc ?

**Comment by TomasGMDC** [comment]
@scovarrubiasm efectivamente, el script entregado es para revisar que se cumplan las reglas asociadas al disclaimer de la tarea, lo cual incluye el uso de estructuras de datos.
