### ISSUE TITLE
duda mala practica clases hijas con método común

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2233/syllabus#441]
hola, 
Tengo una duda sobre algo que quiero hacer y se que funciona pero no se si es correcto.
Tengo una clase abstracta que tiene un método no abstracto ya que es común en todas sus clases hijas,  y hay una parte de mi código donde debo ocupar este método con cada una de las clases hijas. Lo que quiero hacer es un for para hacerlo con todas las clases hijas de una, mi pregunta es  ¿puedo ocupar solo una clase hija para hacer el método para todas?, ya que como es para todas iguales, en realidad no cambia
Lo ejempleficare por que creo que no se entiende muy bien

Opcion larga

hija1.metodocomun()
hija2.metodocomun()
hija3.metodocomun()

Lo que quiero hacer

for i in cantidad_de_hijas:
    hija1.metodocomun()

lo quiero hacer asi por que este método esta dentro de un código mas largo que es repetitivo para cada hija, y lo único que me impide hacer el for es esto.

**Comment by mmunozmendez** [comment]
Hola Antonia,
Lo que quieres hacer si debería funcionar bien porque todas las clases hijas pueden llamar al método. 
Te recomiendo, más en general, que vayas probando las cosas que te generan dudas con hartos ´´´´print´´´ para que te puedas ir dando cuenta como funciona y donde falla, si lo hace.

Éxito con la tarea 🦝

**Comment by antoniaalcayaga** [comment]
hola, 
ya lo probe y funciona, mi pregunta mas que nada es si era considerado una mala practica o algo malo dado que estoy ocupando el método de una sola clase hija para hacer como el trabajo de todas

**Comment by mmunozmendez** [comment]
Hola
Lo que no está bien es cuando tu tienes un método con el mismo nombre en clases que no tienen relación de herencia. En tu caso si existe la relación de herencia, por lo que es correcto 👏 

Saludos 🐰
