### ISSUE TITLE
problema con atributos y @property getter

### ISSUE THREAD

**Issue by sebaelsaca** [IIC2233/syllabus#442]
Hola!

Llevo muchas horas pegado al guardar todos los objetos de Magizoologo en una lista. Utilizé @property como un getter para atributos como sicklers que eran dinámicos pero al hacer un "for" que guardaba todas las instancias, me convertía el valor de todos los atributos dinámicos al valor de la última instancia. Por ejemplo si sickles en el primero era 15 y el siguiente era 1000, entonces el sickles de los 2 valdrá 1000 y no sé como corregirlo y porque pasa

**Comment by fdoflorenzano** [comment]
Hola @sebaelsaca,

La verdad es difícil analizar el problema sin mayor nivel de detalle. Revisé tu repositorio y no has subido estos avances. Hazlo y tal vez así se pueda encontrar el problema más rápidamente.

Saludos.
