### ISSUE TITLE
Duda sobre agregar imagenes a ventana de PyQt

### ISSUE THREAD

**Issue by criss-ah** [IIC2233/syllabus#442]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

[Describe tu duda de manera detallada, explicando los contenidos en cuestión y ojalá colocando código o un caso de uso de ejemplo]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola! Cuando creo una ventana y le agrego alguna imagen, al momento de correr el código la imagen no sale en la ventana, solo se ve un espacio vacío y no logro entender qué pasa.

**Comment by Pablok98** [comment]
¡Hola!
¿Revisaste bien el path de la imagen? Recuerda que las imágenes son archivos, igual que siempre, el path que entregues tiene que ser relativo a la raíz de tu proyecto.

**Comment by criss-ah** [comment]
Creo que justamente esa es la parte que no entiendo, cómo agregar el path y si este tiene que ser importado de igual manera que otro archivo.

**Comment by Pablok98** [comment]
El *path* de las imágenes se trata de la misma forma que has tratado los *path* de archivos hasta ahora. 

Por ejemplo:
```
main.py
- recursos
|- imagen_1.png
```
Si quieres hacer un *pixmap* en`main.py` sería `pixmap("recursos/imagen_1.png")`
