### ISSUE TITLE
Uso de memoria RAM

### ISSUE THREAD

**Issue by tanavarrete** [IIC2233/Syllabus#442]
Hice mi tarea utilizando listas y diccionarios, leí recién las issues que dicen que se debería trabajar con los generadores hasta el final.  Es necesario que cambie toda mi tarea?, afectara mucho en mi nota esto?

**Comment by Hernan4444** [comment]
@tanavarrete es probable que piedas puntaje por no hacerlo eficiente en terminos de memoria (puesto que fue algo que recalcamos desde hace tiempo), pero como no era algo prohibido en la tarea, como en la tarea 2, tampoco es que tendrás un 1.0. No podemos especificar que "tanto" afectará a tu nota. 

Por otro lado hay que destacar que muchas partes si es bien recomensable usar listas y diccionarios, pero hay otras (como la lectura e interpretación del genoma - data) donde guardar toda la información tal como viene será ineficiente. Por lo tanto, tampoco es necesario cambiar toda la tarea, sino las partes donde más afecta las listas en memoria

Saludos ✌️

**Comment by ajahr95** [comment]
¿Cuanto tiempo mas o menos debiera demorarse nuestro programa en leer el archivo genoma y guardar la info ordenada? @Hernan4444

**Comment by Hernan4444** [comment]
@ajahr95 para el caso de test_1 milisegundos desde que la interfaz se carga, pero nosotros dispondremos de casos con muuuuuucho más genes donde ahí se apreciará la diferencia entre alguien que guarda todo el genoma o alguien que procesa de forma optimizada
