### ISSUE TITLE
La GUI viene rota

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#442]
Intenté hacer esto:
![image](https://user-images.githubusercontent.com/37153467/39664964-9efba262-5062-11e8-9a25-4c761f9e17e6.png)

Y pasó esto:
![image](https://user-images.githubusercontent.com/37153467/39664962-94b8904e-5062-11e8-879c-e0a2dbdbfeef.png)

Lo que agregué a consultas.json:
![image](https://user-images.githubusercontent.com/37153467/39664979-b2cb58dc-5062-11e8-874a-3850b3fd97d4.png)

No quiero tener que escribirlo todas las veces uwu :(

**Comment by Hernan4444** [comment]
Hola,
 En la gui.py tienes que ir a la línea 102 que dice:
```python
array.append(json.loads(querry.text().replace("'", '"')))
```

y cambiarla por 
```python
text = querry.text().replace("True", 'true').replace("False", 'false')
array.append(json.loads(text.replace("'", '"')))
```

Con eso debería funcionar.

**Comment by mblejeune** [comment]
@Hernan444 este arreglo de la gui lo usarán para revisar la tarea o si hice eso debo especificarlo en el readme ? porque no subi el gui.py de nuevo suponiendo que lo arreglarian ustedes :(

**Comment by Hernan4444** [comment]
@mblejeune lo tendremos nosotros 👍
