### ISSUE TITLE
Repetición id_voto, test_20_votos_validos

### ISSUE THREAD

**Issue by Bennjapa** [IIC2233/Syllabus#442]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, estuve revisando los tests de votos_validos y resulta que a la hora de instanciar los votos, se repiten algunos id_voto, lo que hace que mi codigo no funcione en los test_0, test_3, test_4. Por lo que dice el enunciado de la tarea el id_voto entiendo que deberia ser único o en esta función, ¿hay que considerar que los id pueden repetirse?

**Comment by mpiavf** [comment]
Hola, actualizamos los tests con lo detectado en esta issue y otras más. Pueden revisar la issue creada en #444 para más detalle. 
Saludos!
