### ISSUE TITLE
Borro de archivo en repositorio, entrega atrasada

### ISSUE THREAD

**Issue by mnbenimeli** [IIC2233/syllabus#443]
Hola, acabo de notar que en mi repositorio hay un archivo .py que no debería estar ahora pues lo modularicé en más partes y olvidé borrarlo. Si lo borro ahora, después de la hora de entrega cuenta  como entrega atrasada?
O mejor aún, si no lo contemplo en el README va a ser omitido?

**Comment by roberto009** [comment]
Hola!
Lo que debes hacer es especificar claramente en tu readme que ese archivo debe ser omitido y/o borrado. Si es que lo borras ahora tendrás que llenar el form de entrega atrasada y eso te generaría un descuento.
Mientras este claro en tu readme todo bien  😄 
Saludos

**Comment by ByronHidalgo1** [comment]
Hola!
Entregué en archivo a la hora, sin embargo, luego intenté borrar un archivo (tipo 20:7) y no resultó. ¿Cómo puedo estar seguro de que el último push fue a antes de las 20:00 horas?

**Comment by roberto009** [comment]
Hola @ByronHidalgo1 
Los archivos se recolectan de forma automática a las 20 hrs. Si es que lo modificaste después de esto no deberías tener problemas con tu entrega. Más adelante les llegará a su repo personal una issue con el commit a revisar. Te recomiendo que lo veas para que verifiques que todo esta ok. 

Si es que no es el commit que quieres revisar debes llenar el form de entrega atrasada.
Saludos !
