### ISSUE TITLE
test_04 - correctitud (test_5)

### ISSUE THREAD

**Issue by canija2000** [IIC2233/Syllabus#443]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/Syllabus/issues/420).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En los test (04) de correctitud del código, especificamente en el quinto (5) test que **"Verifica funcionamiento correcto cuando la diferencia de precio deje el valor de la pizza en 7000 (pues es la cota inferior)."** 

Hay errores  en el argumento que se le entrega a la función o en la **lista esperada** . El filtro nos pide que el valor de la pizza no baje de **7000**, el argumento que se entrega es **-80,000** (coma para facilidad de lectura) , y luego, haciendo las matemáticas,  hay pizzas que no corresponden. Nombradas:
1.- Perfoni_S (80,004) - 80,000 != 7000 , sin embargo está dentro de lo esperado en los tests...
2.-Marga_S (9,424) - 80,000 != 7000, .....
3.- Naplitan 2E INFINITO PODER_S (70,543) - 80,000 != 7000 ..... 
4.- Hawaana_S (7000) - 80,000 != 7000 ... 

pd: 
[Valores a la izquierda son los pasados inicialemente, y que luego se espera que pasen el requisito del la función]
Quedo atento, gracias!

**Comment by NachoRinda** [comment]
Hola, este es un comportamiento esperado. Si leemos el enunciado para la función  <ajustar_precio_segun_ingredientes> dice que: 
_Este valor puede ser positivo (para aumentar el precio de la
 pizza) o negativo (para reducir su precio). El precio de una pizza nunca puede estar por debajo de $7000._
Entonces, lo que quiere decir esto es que el **nuevo precio** de las pizzas después de aplicar la **diferencia_precio** al precio original deberá ajustarse a 7000 **si es que el nuevo precio es menor a esta cota inferior**. Por otro lado, no se menciona ninguna cota superior por lo que por allí no está restringido.

Veamos los tests que mencionas: 
1.- Perfoni_S (80,004) - 80,000 != 7000
Luego de hacer la diferencia:  80,004 - 80,000 = 4, valor por debajo de la cota por lo que el precio se trunca a 7000. 

2.-Marga_S (9,424) - 80,000 != 7000
Luego de hacer la diferencia:  9,424 - 80,000 = -70576, valor por debajo de la cota por lo que el precio se trunca a 7000. 

3.- Naplitan 2E INFINITO PODER_S (70,543) - 80,000 != 7000
Luego de hacer la diferencia:  70,543 - 80,000 = -9457, valor por debajo de la cota por lo que el precio se trunca a 7000. 

4.- Hawaana_S (7000) - 80,000 != 7000
Luego de hacer la diferencia:  7000 - 80,000 = -73000, valor por debajo de la cota por lo que el precio se trunca a 7000.

Veamos ahora la solución:
lista_esperada = [
            Pizza(nombre="Perfoni_S", ingredientes="queso;pepperoni;kd", precio=7000),
            Pizza(
                nombre="Vegetariana_S",
                ingredientes="tomate;queso;champiñones;pimentón;aceitunas;kd",
                precio=90454532,
            ),
            Pizza(
                nombre="Marga_S", ingredientes="tomate;queso;albahaca;kd", precio=7000
            ),
            Pizza(
                nombre="Naplitan 2E INFINITO PODER_S",
                ingredientes="tomate;queso;jamón;kd",
                precio=7000,
            ),
            Pizza(nombre="Hawaana_S", ingredientes="tomate;jamón;piña;kd", precio=7000),
        ]
Si te fijas, todos los precios menores a la cota fueron truncados a 7000, exactamente lo que hicimos recién, mientras que el precio exorbitantemente grande después del descuento (90454532) se mantiene igual pues no hay restricción que se le imponga. Espero que esto resuelva tu duda, sino, házmelo saber por acá mismo :)

**Comment by canija2000** [comment]
ah! no habia entendido eso, pense que se eliminaban los precios si es que no correspondian al filtro de 7000 , gracias!

**Comment by JosefaATP** [comment]
Hola!
Recomiendo que lo aclaren en una issue o modifiquen en el enunciado, porque me paso lo mismo. Estaba eliminando aquellos que no cumplian con que su precio fuera >= 7.000, no los estaba truncando.

Eso 😁
