### ISSUE TITLE
Dia de catedra

### ISSUE THREAD

**Issue by JoseValencia125** [IIC2233/Syllabus#443]
¿El dia de la catedra es aleatorio?

**Comment by indonoso** [comment]
No, son los jueves

**Comment by acrojas2** [comment]
Hola:
Aclarada la duda del día de catedra. ¿Qué día son las reuniones de docencios y tareos o es aleatorio?

**Comment by Hernan4444** [comment]
@acrojas2 puedes dejar uno (ojalá antes de la catedra) y lo mantienes todas las semanas.
Saludos!
