### ISSUE TITLE
Pueden haber genes que no corresponden en las caracteristicas?

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#443]
Un ejemplo lo explica mejor: habiendo leído correctamente los genes de una persona, puede esta tener en su característica "altura" genes distintos a AGT y ACT? En caso de que pueda, asumo que no hay que considerarlos en ningún caso pues no le sirven de nada a la característica altura.

**Comment by Hernan4444** [comment]
@bedefrunner si puede tener y como dices, no se consideran. Lo que sí, cuando analizamos proporción entre un gen y los demás genes de alguna característica (ejemplo: 50% de los genes sea AGT) queda a tu criterio si haces el 50% de AGT en relación a todos los genes o 50% de AGT en relacion a AGT y ACT.

Saludos ✌️

**Comment by bedefrunner** [comment]
@Hernan4444 perfecto, gracias!
