### ISSUE TITLE
Acción alimentarse DCCriatura

### ISSUE THREAD

**Issue by CristobalUrzua** [IIC2233/syllabus#443]
Al momento de alimentarse, hay una posibilidad que la criatura ataque dada por la fórmula que está en el enunciado. Esta fórmula me va a dar un número, pero ¿cómo se cuando atacará? ¿de acuerdo a qué parámetro?.

Gracias

**Comment by jeschuwirth** [comment]
Hola @CristobalUrzua,

Tu duda está respondida en la issue #325, si crees que tu duda es distinta y esa issue no aplica sigue preguntando :)

Éxito!
