### ISSUE TITLE
Enviar consulta en interfaz

### ISSUE THREAD

**Issue by mblejeune** [IIC2233/Syllabus#443]
Hola ! al poner en el espacio para enviar consulta y probar si se me imprimen en resultados, yo ingreso en la barra lo siguiente: ["filter_by_date", ["load_database"], 2015, True], pero me sale q no es posible enviar la consulta, sin embargo, al enviar solo ["load_database"] si funciona, ¿como ingreso entonces consultas del primer tipo que especifico para filter_by_date ? :(

**Comment by Hernan4444** [comment]
@mblejeune revisa el enunciado sobre el tema de booleanos, ahí se explica

**Comment by mblejeune** [comment]
@Hernan4444 lo habia leido mil veces y no me acorde! disculpa, ahi me funciono :) muchas gracias!!! le cambie a true simplemente! te pasaste :)
