### ISSUE TITLE
Pregunta sobre nombres jugador-rival T01

### ISSUE THREAD

**Issue by Andres-Pizarro** [IIC2233/syllabus#443]
Hola! tengo una pregunta acerca de los nombres que se debe elegir para el jugador y para el rival. En el enunciado se especifica que los nombres tienen que ser  "sin distinción entre mayúsculas y minúsculas". ¿A qué se refiere eso?  ¿ Deben todas las letras ser minúsculas o mayúsculas o simplemente no importa como sean?

**Comment by baosse** [comment]
Holaa @Andres-Pizarro !  
Se refiere a que los nombres escritos con mayúsculas se consideran igual a los que poseen minúsculas. 
Por ejemplo:
 'Hola' == 'hola' == 'HOLA' == 'HoLa' 
y así.
Espero que te haya servido! Mucho éxito con tu tarea✨

**Comment by Andres-Pizarro** [comment]
Si es que entendí bien, en el enunciado cuando se escribe el nombre del entrenador, ¿estaría malo cuando se imprime el estado?
¿En qué afecta que no haya distinción entre Juanito y JUanitO?

**Comment by Andres-Pizarro** [comment]
Gracias por la respuesta tan rápida igual!!

**Comment by baosse** [comment]
Ohh no entendí muy bien a que te refieres con imprimir el estado:(
Por otro lado, sirve para diferenciar que jugador y rival no posean el mismo nombre ya que 'Juanito' != 'JUanitO'. No aparece en enunciado, pero genera una mejor experiencia al jugador que sus nombres sean distintos (para no confundirse en quien jugó si es que tuviesen un nombre muy similar).

**Comment by Andres-Pizarro** [comment]
Aaaaah, entonces al momento de elegir el nombre del rival, no puede tener exactamente las mismas letras en el mismo lugar que el nombre del jugador no? Si yo soy Andres16 el rival no puede ser AnDreS16, porque son considerados iguales??

**Comment by baosse** [comment]
Eso sería lo correcto! Pero para esta entrega no es necesario implementar que sean nombres distintos ya que no lo especifica el enunciado.✨ Pero es algo que puede servir para tus siguientes entregas.❤️

**Comment by Andres-Pizarro** [comment]
Listo!!! Muchas gracias!!!
