### ISSUE TITLE
Problema con pyqt5 / MacOs / ImportError: dlopen

### ISSUE THREAD

**Issue by antoniacaceres** [IIC2233/syllabus#443]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Holaa, intento ejecutar código con pyqt5 en el idle o en vscode y no me funciona, me tira este error

![Captura de pantalla 2021-05-06 a las 11 22 56](https://user-images.githubusercontent.com/80801754/117323229-b4e40a00-ae5c-11eb-8eb6-0322761dd6f3.png)
![Captura de pantalla 2021-05-06 a las 11 22 38](https://user-images.githubusercontent.com/80801754/117323241-b7defa80-ae5c-11eb-860e-2abe03ba2d3e.png)
 El código que estoy ejecutando es el siguiente:
```python
import sys
from PyQt5.QtWidgets import QWidget, QApplication

class MiVentana(QWidget):
    def __init__(self):
        super().__init__()

        # Definimos la geometría de la ventana.
        # Parámetros: (x_superior_izq, y_superior_izq, ancho, alto)
        self.setGeometry(200, 100, 300, 300)

        # Podemos dar nombre a la ventana (Opcional)
        self.setWindowTitle('Mi Primera Ventana')


if __name__ == '__main__':
    app = QApplication([])
    ventana = MiVentana()
    ventana.show()
    sys.exit(app.exec_())
```
Gracias de antemano!

**Comment by pedroriosg** [comment]
Hola Antonia! ✌️ 

Podrías indicarme que versión de sistema operativo tienes en tu Mac?

Saludos!

**Comment by pedroriosg** [comment]
Como instalaste `pyqt5`?

La manera de hacerlo es escribir en tu terminal `pip3 install PyQt5`
Mándame foto de lo que te sale si ejecutas eso!

Saludos

**Comment by antoniacaceres** [comment]
Sii eso hice pero me aparece instalado. Además instale Xcode y Qtcreator porque estaba resolviendo el problema con una ayudante pero nada funcionó.
![Captura de pantalla 2021-05-10 a las 21 03 19](https://user-images.githubusercontent.com/80801754/117742347-91112300-b1d2-11eb-82f9-57e5d98bb34c.png)

**Comment by pedroriosg** [comment]
Hola Antonia!

Una pregunta, instalaste `python` a través de Anaconda?

De no ser así, cncontré esto en Stackoverflow que quizá pueda servirte.
Ejecuta en tu terminal `LDFLAGS=-L/usr/local/opt/qt/lib CPPFLAGS=-I/usr/local/opt/qt/include pip3 install PyQt5`, todo en una línea. Acá te adjunto el link del Stackoverflow por si quieres mirarlo.

https://stackoverflow.com/questions/43531245/pyqt5-not-working-on-macos-sierra

**Comment by antoniacaceres** [comment]
Holaa, lo instalé como sale en el tutorial de canvas y al ejecutar lo anterior me sale esto y todo sigue igual, vscde me tra el mismo error
![Captura de pantalla 2021-05-12 a las 17 35 45](https://user-images.githubusercontent.com/80801754/118046812-d73bc300-b347-11eb-932f-943103705caf.png)

**Comment by pedroriosg** [comment]
Ok, intentaremos a ver si te funciona con una versión más antigua de `pyqt5`

Ejecuta estas acciones (en tu terminal) en el siguiente orden:

1.  `pip3 uninstall pyqt5`
2.  `pip3 install pyqt5==5.9`

Avísame que te sale

**Comment by antoniacaceres** [comment]
Funcionóoo! ahora al ejecutar el código se me abre la ventana correspondiente. Quería saber si puedo desintalar QtCreator y Xcode o si es necesario para el funcionamiento de pyqt en mi computador? Muchas graciass!

**Comment by pedroriosg** [comment]
Que bueno!!

Hasta donde sé `QtCreator` no es necesario para el curso y no es necesario para el funcionamiento de `pyqt5` (puedes desinstalarlo). Ahora bien `QtDesigner`  si te recomiendo descargarlo y usarlo porque te va a permitir realizar el diseño gráfico de tus ventanas de una manera más rápida y eficiente, ahorrando código y posibles `bugs`.

Con respecto a lo segundo, instalaste toda la aplicación `XCode`? O solamente algunos paquetes?
No debiese ser requisito tener instalado `XCode` en tu computador. Puedes desinstalarlo simplemente transfiriéndolo al basurero. Igual re recomiendo probar que todo funcione de manera correcta después de desinstalar. Me avísas si no funciona.

Te dejo el link para descargar `QtDesigner` si no lo tienes.

https://build-system.fman.io/qt-designer-download

**Comment by antoniacaceres** [comment]
si tengo qt designer y funciona bien. Xcode lo instalé porque una ayudante me dijo que quizás resolvería el problema porque mi computador no lo traía, pero finalmente no hizo nada. Graciasss

**Comment by pedroriosg** [comment]
Puedes desinstalarlo entonces si quieres. De todas formas revisa después de desinstalarlo que todo funcione bien.

Saludos! ✌️
