### ISSUE TITLE
La siguiente actividad va a estar más enfocada en archivos y bytes, o en serialización?

### ISSUE THREAD

**Issue by perezpefaur** [IIC2233/syllabus#444]
Es para saber a qué tema le tengo que dar más énfasis, al momento de hacer ejercicios.

**Comment by entamburini** [comment]
Hola! :D 

Para la actividad de esta semana entrará toda la materia de la semana, no habrá foco especial :eyes: Se trató de hacer una actividad que pueda englobar todos los contenidos de la semana :) 

Suerte!
