### ISSUE TITLE
Escenarios

### ISSUE THREAD

**Issue by josemlira** [IIC2233/Syllabus#444]
Hola!, no entiendo por qué se nos dan algunas probabilidades en el enunciado siendo que al final vamos a tener que utilizar las que nos dan en escenarios.csv. Para realizar la simulación, primero el usuario deberá seleccionar el escenario que quiera y luego utilizar estas probabilidades asociadas al escenario ingresado, es esto cierto? 
También se menciona que si aparece "-" entonces se utiliza el valor dado en el enunciado, pero en el ejemplo que se nos da en el Cuadro 5, las probabilidades de tomar cierta cantidad de creditos del escenario 2 no suman 1 (debido a que la probabilidad de tomar 55 creditos en ese escenario sería 0.15), entonces que se hace en esos casos?

**Comment by iqacevedo** [comment]
Hola ! 

La idea es que la simulación reciba por defecto todos los parámetros que se indican en el enunciado.
Como una opción aparte se debe permitir el análisis de resultados, que debe realizar la simulación para todos los escenarios y comparar los resultados que se obtienen en cada uno de ellos.

Si parece "-" es justamente como dices, se utiliza el valor por defecto indicado en el enunciado. Puedes asumir que los valores que aparecen en un escenario siempre serán consistentes, es decir las probabilidades sumarán 1 (por lo que no debes preocuparte de corroborar eso). Efectivamente como dices hay un error en el cuadro 5, se avisará cuando se arregle. 

Espero que quede claro, si te queda alguna duda pregunta no más 😄 
Saludos !

**Comment by josemlira** [comment]
Entonces debemos hacer algo así como un menú al principio, en donde se pueda escoger realizar la simulación con algún escenario y también realizarla con los valores por defecto?

**Comment by iqacevedo** [comment]
Basta con que se pueda escoger realizar una simulación con los valores por defecto, y que se pueda comparar todos los escenarios entregados en escenarios.csv (no es necesario que tengas una opción para correr por separado un escenario en específico). 
Saludos !

**Comment by josemlira** [comment]
Muchas gracias!!
