### ISSUE TITLE
Función atomizada con manejo de errores

### ISSUE THREAD

**Issue by jvlara** [IIC2233/Syllabus#444]
¿Las lineas extra debido al manejo de errores dentro de una función contaran para el largo de la función?

**Comment by Hernan4444** [comment]
@jvlara si cuenta. Recuerda que las 15 lineas son para evaluar que las funciones sean atomizadas, una funcion que verifica en input y luego procesa el input no es algo atomizado porque realizar 2 acciones.

saludos ✌️
