### ISSUE TITLE
el enunciado dice que el dinero siempre será positivo

### ISSUE THREAD

**Issue by notyourlasagna** [IIC2233/syllabus#444]
el enunciado dice que el dinero siempre será positivo, eso quiere decir que si a una delegación le quedan 60 DCCoins, y quiere hacer una operación que cuesta 60, esta no se podrá hacer? ya que quedaría en 0. O puede quedar con un valor positivo o 0 también?

**Comment by retamalcito** [comment]
¡Hola @notyourlasagna!

Al hablar de números positivos en el enunciado, esto también incluye el 0, por lo que si una delegación que tiene 60 `DCCoins` quisiera hacer una operación que cuesta 60, esta **sí** la podrá realizar, y quedará con 0 `DCCoins` restantes.

¡Saludos! 🥇

**Comment by notyourlasagna** [comment]
Muchas gracias @retamalcito y buenas noches :)
