### ISSUE TITLE
Actualizaciones tests  

### ISSUE THREAD

**Issue by mpiavf** [IIC2233/Syllabus#444]
Hola a tod@s

Frente a inconsistencias encontradas los últimos días se actualizaron los tests mencionados a continuación y el `test_solution.py`. 

**Importante:**  estos cambios no afectan el resultado de la solución actual si es que han seguido las instrucciones del enunciado

1. Se agregaron nuevos test en los archivos `test_01_animales_que_votaron_por.py`, `test_06_votos_alcalde_en_local.py` y `test_16_mismo_mes_candidato.py` que **no contradice el enunciado**, pero es para que tengan un caso más para probar por consulta.

2. Se actualizaron los test `test_10_animal_mas_viejo_edad_humana.py`, `test_20_votos_validos.py`, `test_23_votos_validos_local.py` y `test_24_votantes_validos_por_distrito.py` para que la edad calculada se permita tanto por animal.edad como por 2024-año_nacimiento.

3. Se actualizó `test_14_votaron_por_si_mismos.py` se arregló para que el tipo de dato que retorne la consulta no sea únicamente un Generador, sino tambien aceptar, map, filter, etc.

4. Se actualizó `test_10_animal_mas_viejo_edad_humana.py` se arregló para que el tipo de dato que retorne la consulta no sea únicamente un Generador, sino tambien aceptar, map, filter, etc. Se arreglaron los atributos incorrectos de Local().

5. Se actualizó el `test_20_votos_validos.py` para que no hayan id_voto repetidos. 

5. Se actualizó `test_solution.py` para poder tener los resultados actualizados de los tests.

**Comment by Daniel-M-P** [comment]
Hola, los tests siguen dando error, para algunos considera el ponderador y para otros la fecha de nacimiento
El test 1 tiene estos animales:

            Animal(1, "Gay", "Perro", 190, 288.0, 45, "1979/11"),
            Animal(2, "Lexi", "Perro", 61, 0.071, 34, "1990/8"),
            Animal(3, "Toccara", "Perro", 248, 0.525, 67, "1957/12"),
            Animal(4, "Phil", "Perro", 248, 0.525, 67, "1957/12"),
            Animal(5, "Ernst", "Gato", 116, 81.0, 60, "1964/9"),

Haciendo que por fecha de nacimiento todos sean mayor de edad
Todos votan, haciendo que el distrito uno sea el de mayor votos, pero 

El resultado está dado por 
Animal(5, "Ernst", "Gato", 116, 81.0, 60, "1964/9")

Porque los ponderadores son [Ponderador("Perro", 0.1), Ponderador("Gato", 4)] 

Lo mismo pasa con el resto de los tests, si usas los ponderadores te dan bien la mitad y la otra mitad no,  y al revés con usar la fecha de nacimiento (porque los ponderadores no hacen que los animales de la respuesta lleguen a los 18 años)

**Comment by Daniel-M-P** [comment]
Tomando todos los votos como válidos se pasan todos los tests menos el 1 y el 3, y filtrando añadiendo solo aquellos que sean mayor o igual a 18 años fallan todos los tests.

Pueden por favor revisar esto y corroborar que funcione bien el test 24 !!

**Comment by waknaudt** [comment]
Estoy seguro que el test 8 del test_16_mismo_mes_candidato esta malo, me dice que el animal con id=2633 deberia estar en el generador de quienes votaron por candidato con id=2633 y tienen misma fecha de nacimiento, pero el candidato con id=2633 no voto por si mismo por lo que no debiera estar en el generador.
