### ISSUE TITLE
Método run Jugador

### ISSUE THREAD

**Issue by Franastel** [IIC2233/Syllabus#444]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

No comprendo si el método debe iniciar el thread o es un método que funciona LUEGO de iniciarlo aparte

**Comment by Hernan4444** [comment]
Hola @Franastel 

El método `run` es aquel que tiene todo lo que deseas que realice el thread. Y uno le hace `start` para iniciar el thread.

Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ
