### ISSUE TITLE
Agregar métodos a T03Window

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#444]
Hola
Le puedo agregar métodos a la clase T03Window que viene en el archivo ```main.py```?
Gracias

Y el límite de líneas corre para los métodos de main.py?
Con el control de excepciones me estoy pasando :(

**Comment by Hernan4444** [comment]
@jmwielandt no, solo deben trabajar con los métodos que les damos y el init en caso de querer realizar el preprocesamiento solo una vez.

**Comment by castrillini** [comment]
Entonces los métodos de la clase T03Window, ¿también deben tener un máximo de 15 líneas?

**Comment by sjkinast** [comment]
Hola,  pero al no poder crear mas metodos no se estaria contradiciendo la idea de que cada funcion solo realice una cosa especifica ?

**Comment by Hernan4444** [comment]
@castrillini no seremos minuciosos con eso en la interfaz, ideal que no abusen de eso para poner código que hace la librería, pero en la interfaz. Pero lo esperado es que la interfaz solo llame a su librería para pedir el resultado, obtenga la respuesta o maneje la excepcion para tener el output y lo ponga en la interfaz o archivo. si eso supera las 15 líneas, no hay problema

@sjkinast las funciones son para la librería. Y si se pueden usar funciones auxiliares, Los métodos siguen siendo objetos en Python y por ello pueden ser argumentos que reciba otra función y ejecutar ese método en otra parte.
