### ISSUE TITLE
Problemas con importación ciclica de módulos

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#444]
Hola.
He tenido bastantes problemas con lo de importar módulos en otros. Probando por un buen rato, me dí cuenta que el error proviene de que; el programa no me deja importar el mismo módulo en ambos. Por ejemplo tengo un ```modulo1``` y un ```modulo2``` , lo que yo intento de hacer es que en el primer módulo importo al segundo, y en el segundo importo al primero. Ahora claramente no se puede hacer, ya que cada vez que lo hago me tira este error;
*AttributeError: module 'modulo1' has no attribute 'función de modulo1'*
Por qué no se puede hacer?.
Ahora, como consejo, considero que en la parte de la materia donde hablan de cómo importar los archivos (materia path) debieran mostrar que esto no se puede hacer, ya que así sabemos de antes.
Yo tengo mi código muy separado y no encuentro la forma de juntarlo más, cada módulo está casi en su extensión máxima de 400 lineas. Pueden ver mi código de avance si quieren, ahí se puede ver que tengo en todos los módulos ```import``` de todos los otros. Ojalá hubiera sabido de este error antes, porque hubiera buscado la manera de generar un código que no requiera importar de esta manera. 
Y estoy en no sé qué hacer. Porque tampoco puedo seguir avanzando, quiero probar mis funciones como código completo, pero por esto no he podido. 
Ojala puedan explicarme esto, y ayudarme de alguna manera :disappointed:

**Comment by Camila-sty** [comment]
Para ser más clara. El error me sale cuando ejecuto una función de ```modulo2```, y que requiere de ```modulo1```

**Comment by Camila-sty** [comment]
perdón, no es la materia de path. Me confundí.

**Comment by fdoflorenzano** [comment]
Hola @Camila-sty,

Como bien dices, el problema que te surge es uno de importación cíclica entre módulos. Y también como bien dices en tu último comentario, es materia de [modularización](https://github.com/IIC2233/contenidos/blob/master/semana-00/2-modularizaci%C3%B3n.ipynb), donde se indica como es que se ejecuta la importación de módulos.

Un arreglo rápido es simplemente sacar la interdependencia cíclica entre módulos. Una forma es dejar en el mismo módulo las secciones de tu código que dependan cíclicamente. Otra es separar aún más tu código y crear un tercer módulo que contenga código necesitado por tus llamados `modulo1` y `modulo2`, y que este tercer módulo no importe a nadie. Así las dependencias dejan de ser cíclicas.

El material no toca ese punto debido a que Python recientemente hizo cambios para manejar este problema, antes directamente no permitía este tipo de importación mediante un error específico. Ahora, el error persiste con otras formas, como en tu caso. 

Intuyo el problema se produce por lo siguiente (siguiendo el razonamiento puesto en los contenidos y probando un poco de código):
- Se comienza la ejecución de `modulo1`. Como en sus primeras sentencias importa a `modulo2`, se comienza ejecución de `modulo2`.
- Como en las primeras sentencias de  `modulo2` se importa a `modulo1`, se vuelve a ejecutar `modulo1`.
- En la nueva ejecución de `modulo1`, se ignora la importación de `modulo2`, porque ya se realizó, entonces continua hasta una línea que llama a una función de `modulo2`.
- Como la importación de `modulo2` llegó hasta un `import` y no las definiciones de funciones posteriores, no debe existir aún la función que se desea llamar. Indicando el error que te sale.

Intenta con las opciones que indiqué en el segundo párrafo, y en general evita importaciones cíclicas, así te ahorrarás problemas.

Saludos, y quedo atento a más dudas.

**Comment by jaimecoloma** [comment]
@fdoflorenzano Hola! Tengo una duda al respecto del mecanismo de funcionamiento en situaciones cíclicas. Resulta que yo también tengo un pequeño problema más simple de solucionar de dependencia cíclica y buscando información encontré que para evitar el error se podía poner la función/módulo llamada antes de la importación y así se evitaba el error. Quisiera saber si eso es válido y respeta el PEP8, ya que queda algo como : 
def función()
form archivo import clases
(En el archivo importo clases) 
,de otro modo estoy haciendo que aquellas funciones con la dependencia las copié y pegué en el módulo de clases que las necesitaba.
Agradezco de antemano!

**Comment by fdoflorenzano** [comment]
Hola @jaimecoloma,

Entiendo la solución, pero la verdad es que sería un arreglo fácil que rompe con PEP8, y que no recomiendo. Si bien no se explicita [en la guía de descuentos](https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md), si se habla de esto en [el contenido de guías de estilos](https://github.com/IIC2233/contenidos/blob/master/semana-00/1-gu%C3%ADa-de-estilo.ipynb).

El mantener los `import`s como lo primero en un módulo es una convención que intentamos impulsar en el curso, como en todos los códigos que les proveemos. Intentaría resolver el problema mediante re-estructuración de código o mediante los mecanismos mencionados más arriba.

Saludos.
