### ISSUE TITLE
do one thing and do it well

### ISSUE THREAD

**Issue by cjdelacuadra** [IIC2233/Syllabus#445]
todos sabemos que las funciones no deben tener más de 15 lineas, pero cuenta un linea que por el pep8 deba convertirla en más? osea cuanta por las que ocupa o por las que son??

**Comment by IchottMano** [comment]
@cjdelacuadra Hola!

Cuando contemos la cantidad de líneas, estas **deben** cumplir con pep-8.
De lo contrario, arreglaremos la función para que cumpla con pep-8 y **luego** contaremos la cantidad de líneas.

Saludos!

**Comment by ciquezada** [comment]
Hola, ¿el maximo de caracteres por linea es 75? (pregunto porque he visto que a veces en internet dice 72 o 79, no me queda claro)

**Comment by Arcoirisky** [comment]
Nosotros trabajamos con 80 caracteres por línea O: Si no me equivoco debería estar en el material inicial del curso c:

**Comment by mplazadelosreyes** [comment]
@Arcoirisky, hice mi tarea en Pycharm y para el PEP8 y largo de lineas me pone esto:
![captura de pantalla 2018-05-05 a la s 23 23 32](https://user-images.githubusercontent.com/37154771/39669181-6d7c087c-50bb-11e8-93f0-c65e7738149a.png)

Qué hago?? Porque tendría que cambiar casi toda mi tarea 😬😬 Van a considerar que pycharm pone el pep8 con 120 caracteres o lo tengo que arreglar si o si?

**Comment by Hernan4444** [comment]
@mplazadelosreyes tienes que arreglarlo. El enunciado especifica que es PEP8 (https://www.python.org/dev/peps/pep-0008/#maximum-line-length) , y no podemos cambiar las reglas de PEP8 porque pycharm decide ocupar otra configuración por defecto.

Saludos ✌️

**Comment by mplazadelosreyes** [comment]
@Hernan4444 y existe alguna manera de cambiar esa linea amarilla que me indica el largo de la línea en pycharm?? porque sino ni idea como saber cuanto son 80 caracteres sin tener que contarlos cada vez

**Comment by mplazadelosreyes** [comment]
@Hernan4444 ya lo arregle! gracias igual!
