### ISSUE TITLE
Duda Readme de-descuento

### ISSUE THREAD

**Issue by Deleon20** [IIC2233/syllabus#445]
Hola ! Tenia una duda acerca del readme, para el de-descuento dice " Especificar el archivo y línea donde se puede encontrar cada ítem de la distribución del puntaje que puede ser evaluado mediante la lectura de código.", esto se refiere a los items de la distribucion de puntaje unicamente en rojo?

**Comment by iqacevedo** [comment]
Hola!,

Si, bastará con que indiquen esos items.
Saludos.
