### ISSUE TITLE
¿Cuándo usar Properties?

### ISSUE THREAD

**Issue by iastruque** [IIC2233/syllabus#445]
Estoy un poco confundido con el uso de los property porque siento que debo ocuparlo en prácticamente todos los atributos de las superclases y subclases que hay, ya que todos los atributos de  los Magizoólogos u otra clases son privados e idealmente si van a ser alterados, por ejemple, por el DCC, estos deberán ser modificados dentro de la clase y por la propia clase con un setter.

Me podrían aclarar el uso que debo darle a ésta herramienta

**Comment by rieg-ec** [comment]
tambien tengo la duda, asi que cps

debo usar (o es buena practica) getters y setters (o solo getters si no se modifican las variables) en todos los atributos? lo veo un poco tedioso, por lo que solo lo hice con aquellos que tenian algun comportamiento especial (ej. no podian pasarse de cierto valor)

**Comment by Dnpoblete** [comment]
Hola @iastruque y @rieg-ec, les recomiendo revisar la issue #233, en donde se explica el uso de properties. De todas formas la idea de las properties es que se las usen cada vez que tengan un atributo que varía su valor constantemente, por lo que no todos los atributos de las clases serán properties, ya que algunos no se alteran durante todo el flujo del programa.

Por otro lado, si bien dicen puede ser tedioso a veces, el uso de correcto de properties te puede ahorrar muchas líneas de código y es una buena práctica. 

Es por esto que les recomiendo revisar bien cuales atributos deben ser properties y cuales deben tener getter y setter, ya que no siempre es necesario tener un setter, dado que este último solo es necesario si se desea cambiar el valor.

Espero haber respondido sus dudas, y en caso de no ser así por favor avísenme para poder ayudarlo.
Éxito con la tarea! 😄

**Comment by sbcorrea** [comment]
@Dnpoblete me quedó una duda con tu respuesta: en un momento dices que

> la idea de las properties es que se las usen cada vez que tengan un atributo que varía su valor constantemente


pero en otro, que

> les recomiendo revisar bien cuales atributos deben ser properties y cuales deben tener getter y setter, ya que no siempre es necesario tener un setter, dado que este último solo es necesario si se desea cambiar el valor


Por una parte, me imagino que ésa sería la manera de hacer que un atributo dependa de otro (por ejemplo, que la licencia sea ```True``` o ```False``` dependiendo del nivel de aprobación), pero en esta tarea todas esas dependencias no son automáticas sino que se hacen efectivas cuando cambia el día y fiscaliza el DCC.
Por lo tanto, no entiendo en qué caso convendría tener una property que solo ocupe getter. Entiendo en qué casos podría querer solo un getter y un deleter, pero no en cuáles me serviría solamente el getter. ¿Cómo se tiene un atributo que varía su valor constantemente sin cambiar el valor?

**Comment by Dnpoblete** [comment]
Hola @sbcorrea, con respecto a la primera parte, perdón lo dije un poco enredado, pero a lo que me refería es que la idea de las properties es identificar el uso de setters en momentos en donde varía el valor del atributo.

Siguiendo con lo que comentaste, entiendo a que te refieres con que son no automáticas, pero la verdad es que no se me ocurre algún caso en que la dependencia sea "automática", ya que siempre va a depender de como modeles tu código y no se va a producir el cambio solo, ya que siempre van a depender de que ocurra algún hecho para cambiar, como en este caso bien mencionas sería pasar al día siguiente.

Con respecto a lo último se puede tener solo un getter, pero no es necesario, con respecto a cuándo usar que cosa, no puedo decir más, ya parte de los objetivos es que identifiquen las properties y cómo modelarlas.

Espero haber respondido tu duda y éxito con la tarea! :smile:

**Comment by sbcorrea** [comment]
Creo que entendí, jajaja. Muchas graciassss
