### ISSUE TITLE
Análisis de resultados

### ISSUE THREAD

**Issue by josemlira** [IIC2233/Syllabus#445]
Hola!, en la sección 8 aparece que el parámetro fiesta_mes es la cantidad de veces que ocurre el evento fiesta en un mes, pero el evento fiesta distribuye exponencial, según enunciado, por lo que este parámetro no debiese ser en verdad el tiempo de ocurrencia de las fiestas? Lo mismo con el evento partido de fútbol.

**Comment by indonoso** [comment]
Un error del enunciado. 
En el archivo de escenarios te darán el valor de `lambda`, no la cantidad de veces que ocurre durante un semestre.

**Comment by josemlira** [comment]
Pero si fuesen los valores de lambda, no serían muy grandes? considerando que el lambda por defecto de fiesta es 1/30 ??? Además en el archivo de escenarios hay valores 0.0, por lo que expovariate arrojaría ZeroDivisionError?? Es por esto que creo que en realidad se refiere al tiempo de ocurrencia de las fiestas.

**Comment by Dunkan1** [comment]
yo creo que es 1/(en lo que esta en escenarios)

**Comment by josemlira** [comment]
No creo que sea eso ya que en escenarios dan valores 0.0

**Comment by iqacevedo** [comment]
Hola!
Nuevamente los problemas se ocasionaron por un error de enunciado, en primera instancia se indicaría el valor esperado, pero finalmente se decidió por dar el valor de `lambda`. Pronto subiremos tanto el enunciado como el archivo escenarios.csv corregido.
Saludos !

**Comment by josemlira** [comment]
En el archivo de escenarios siguen habiendo valores 0.0 luego del cambio realizado, por lo que expovariate arrojaría ZeroDivisionError??

**Comment by iqacevedo** [comment]
Hola!
Al final escenarios.csv no se había actualizado. Ahora si esta actualizado, podrás ver que fiesta_mes ahora corresponde al valor de lambda que recibe la distribución expovariate. 

Saludos !

**Comment by josemlira** [comment]
Ya! Muchas gracias!!

**Comment by asdegoyeneche** [comment]
Hola! 

Me gustaría corroborar una parte del enunciado respecto a "-" en `escenarios.csv`, entiendo lo que dice el enunciado, pero quería saber si efectivamente es lo que quieren que hagamos.

Dado que los valores del enunciado los guardaríamos y cargaríamos de `parametros.csv` (para poder modificar parámetros): ¿se quiere que carguemos el valor por defecto del enunciado (valor original sin posible modificación en `parametros.csv`) o por defecto presente en `parametros.csv`? Nuevamente, sé que el enunciado dice la primera opción, pero como esto reduce la dificultad del problema prefiero consultar previamente si es lo que quieren que hagamos vs a solo especificarlo en el README.md.

Muchas gracias de antemano!

Pd: revisé issues relacionados


> Si el valor de alguno de los parámetros es un “-“, significa que se debe utilizar el valor de ese parámetro del escenario por defecto (descrito en el enunciado) (...) Es importante destacar que cualquier parámetro de la simulación que no se encuentre en `escenarios.csv` debe ser ingresado con el valor que se indique en el enunciado, en caso de que no se especifique un valor queda a su criterio el valor a utilizar.

**Comment by iqacevedo** [comment]
Hola !

Como en el archivo parámetros.csv deben guardar los valores por defecto del enunciado, deberías cargarlos desde ahí. Si realizas alguna modificación a algún parámetro (cambiándolo en parámetros.csv) porque te pareció más lógico y lo especificaste en tu README, debería cargarse ese como valor por defecto (desde parámetros.csv).

Saludos !

**Comment by egbusch** [comment]
Hola !

Tengo una duda con los valores que se entregan en escenarios.csv, algunas probabilidades como prob_40_creditos van entre 0 y 1. Sin embargo, otras como prob_visitar_profesor van entre 0 y 100. Para la evaluación se mantendrán en el mismo formato que se entrego escenarios.csv (las que estan entre 0 y 1 y se mantienen y las de 0 a 100 también), serán todas entre 0 y 1, entre 0 y 100, o ninguna de as anteriores ??
