### ISSUE TITLE
Gasto energía al plantar

### ISSUE THREAD

**Issue by itplanella** [IIC2233/syllabus#445]
Hola! según tengo entendido, al plantar una semilla se debe perder energía, sin embargo, este valor no se encuentra dentro de los parámetros_acción ya que solo tengo perdidas de energía al usar herramientas, cosechar y recoger. Por lo que quería saber si debo usar alguno de esos o crearlo en parámetros generales. Gracias de antemano.

**Comment by gatochico** [comment]
Hola! En la issue #408 se comenta respecto a esto. Saludos!
