### ISSUE TITLE
Duda excepciones

### ISSUE THREAD

**Issue by bimartinez** [IIC2233/Syllabus#445]
Hola!

En el enunciado de la tarea dice que **una excepción genérica no se considerará correcta** refiriendose a `Exception`, mi duda es si se refiere a levantar una excepción genérica, a capturar las excepciones del programa a través de `except Exception` o si son ambas. Lo pregunto ya que por un tema de ahorrar líneas al escribir los resultados capturo los errores del programa a través de `except Exception` para luego escribirlos, por lo cual quiero saber si esto está permitido o en verdad debo cambiar la manera de hacerlo. 

Saludos!

**Comment by Hernan4444** [comment]
@bimartinez se refiere a ambas, se captura o levanta una excepción tipo `Exception` solo cuando no existe ninguna otra que sirva, pero este no es el caso.

Saludos ✌️
