### ISSUE TITLE
Iterables e iteradores

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#445]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola buenas, en la imagen que adjunté del midterm del 2023-2, en la pregunta 8, según la pauta la respuesta es la A, sin embargo yo tenía entendido que para crear un iterador necesitamos crear un `__iter__` además del `__next__`, por lo que yo había pensado que era la B, no sé si la pauta está bien.

<img width="909" alt="Captura de pantalla 2024-10-02 a la(s) 7 01 08 p m" src="https://github.com/user-attachments/assets/3f04e162-5a5f-421e-8401-3f310139ab84">

**Comment by gracie-14** [comment]
Hola! Yo tenía la misma duda porque también respondí B, pero revisé los contenidos y me parece que aunque es muy recomendable definir el método ```__iter__``` para los iteradores, técnicamente no es necesario:
<img width="984" alt="Screenshot 2024-10-02 at 11 24 47 PM" src="https://github.com/user-attachments/assets/529caa6d-3aa9-48f3-92ba-c7c4cf64bc4a"> 
(eso viene de los contenidos 3-iterables-generadores de la semana 5)
