### ISSUE TITLE
volver atras en menu principal

### ISSUE THREAD

**Issue by notyourlasagna** [IIC2233/syllabus#445]
hola, si uno vuelve atrás en el menú principal, a dónde debe volver? Porque atrás sería elegir los nombres y equipo, y eso sería volver a empezar todo o no? O no se debe implementar volver atrás en menú principal?

**Comment by retamalcito** [comment]
¡Hola @notyourlasagna!

Como se mencionó en la issue #365, esta opción **sí** debe estar presente en el menú principal, y al seleccionarla se debe comenzar todo de nuevo, reiniciando la simulación de la DCCumbre Olímpica.

¡Saludos! 👋
