### ISSUE TITLE
Duda Tarea 3 acerca de cuando se puede usar for

### ISSUE THREAD

**Issue by VicenteDubo** [IIC2233/Syllabus#445]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, me gustaría preguntar si funciones como por ejemplo la función "cantidad_votos_candidato" se puede utilizar for, tengo esta duda ya que se pide que esta función retorne un int y por lo tanto no se usaría un yield ni sería una función estrictamente generadora, pero en si recibe un generador que es lo que se esta iterando, por eso pregunto si usar for sería valido para este caso.

Muchas Gracias.

**Comment by TomasGMDC** [comment]
@VicenteDubo considerando lo dicho en " #339 ", no se puede. Tal y como indicas, dado que se trata de una función que no es generadora, no se puede utilizar for y/o while dentro de esta. Recuerda que el script de revisión entregado también sirve para poder estar 100% seguro de si algo se puede hacer o no.
