### ISSUE TITLE
Problema al intentar abrir Designer

### ISSUE THREAD

**Issue by matyjjn14** [IIC2233/syllabus#446]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Hola, tengo problema al intentar abrir Designer, me aparece el siguiente mensaje:
![image](https://user-images.githubusercontent.com/64443045/117338843-0dbb9e80-ae6d-11eb-909e-33a61f993095.png)

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by rlabb** [comment]
Me pasó algo parecido 
![Screenshot 2021-05-06 131826](https://user-images.githubusercontent.com/69586033/117340896-70ae3500-ae6f-11eb-911e-452baab2e465.png)

**Comment by matyjjn14** [comment]
Hola, lo siento la tardanza estuve desconectado en la semana de receso, pero al menos yo no use una versión de Anaconda

**Comment by aaossa** [comment]
Hola! @matyjjn14  @rlabb aún tienen este problema? Si lo solucionaron, ¿qué hicieron? 🤔

**Comment by matyjjn14** [comment]
hola, yo sigo con el problema

**Comment by Juampisaez** [comment]
Hola
A mi hace un tiempo me paso que no podia usar la app, habia instalado todo por consola. Lo que hice despues fue instalarlo directamente desde la pagina web, prueba con eso. En una de esas se soluciona.

**Comment by matyjjn14** [comment]
pucha yo lo descargue de la pagina web :c

**Comment by matyjjn14** [comment]
gracias @Juampisaez  me sirvió tu solución!
