### ISSUE TITLE
Tag con o sin comillas

### ISSUE THREAD

**Issue by caespinoza5** [IIC2233/Syllabus#446]
De acuerdo al enunciado, aparece que para las estadísticas y para valor_característica, se utilizarán como argumentos, por ejemplo, (TAG, "Nombre"). Sin embargo, de acuerdo a todas las consultas en los archivos de consultas, el formato aparece ("TAG", "Nombre"). Quería consultar si en este caso nos guiamos por enunciado o por el archivo de consultas. (Idealmente por el archivo de consultas, ya que tiene más lógica siendo que variables como TAG, GTC, etc no están definidas).

**Comment by Hernan4444** [comment]
@caespinoza5 tal como dices debe ser "TAG" para que la consulta puede ser leida. Fue un error del enunciado.

Saludos ✌️
