### ISSUE TITLE
Diagrama de eventos

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#446]
no me queda muy claro que debemos entregar en el diagrama de eventos...
es una lista con los eventos que pasan y como se gatillan o es otra cosa.

**Comment by indonoso** [comment]
El formato es como quieran, se les sugiere lo que está en el enunciado, como una seudo-tabla.
Lo único importante es que quede claro el nombre del evento, cuándo ocurre y qué pasa cuando ocurre el evento. En este último punto es importante que nombres **todas** las consecuencias del evento: qué se actualiza, qué se calcula, etc.

**Comment by Dunkan1** [comment]
aaaaaa, ya entendi gracias
