### ISSUE TITLE
Lectura de archivos con rb

### ISSUE THREAD

**Issue by perezpefaur** [IIC2233/syllabus#446]
Al leer los bytes de un archivo no entiendo porque tengo que leerlo como:

`for byte in archivo.read():`

y tampoco sabría decodificarlo en un caracters que no sean ACII. 
`for byte in archivo.read():`
` ....byte_decodificado = str(chr(byte))` # eso lo decodifica en caracteres ACII

Intento utilizar el `byte.decode("codificacion")` pero no me resulta.

**Comment by aaossa** [comment]
Hola, intentaré encadenar la respuesta a tu pregunta en el orden que me imagino que llegaste a ellas. Si lees un archivo en formato texto, lo recuperaremos como string:

```python
# Aqui implicitamente leemos en modo "rt" (read text)
with open("archivo.txt", "r") as archivo:
	contenidos = archivo.read()
	print(type(contenidos)) # <class 'str'> 
	print(contenidos[:7]) # "Ejemplo"
```

Pero si leemos un archivo en formato bytes, recuperaremos bytes (un "string de bytes"):

```python
# Aqui estamos ocupando el modo "rb" (read bytes)
with open("archivo.txt", "rb") as archivo:
	contenidos = archivo.read()
	print(type(contenidos)) # <class 'bytes'>
	print(contenidos[:7]) # b"Ejemplo"
```
Por lo tanto, al iterar sobre los contenidos leidos en formato bytes, *estamos leyendo cada byte*:

```python
with open("archivo.txt", "rb") as archivo:
	for byte in archivo.read():
		print(type(byte), byte) # <class 'bytes'> 17
```

Si te fijas, cada byte es interpretado por python como un `int` (y viceversa, por eso al crear un objeto de bytes tenemos que hacer `bytes([3, 4, 5])`).

Ahora, tenemos un `byte`/`int`, que queremos convertir en un caracter, el método `chr()` lo hace: retorna el string que representa al caracter identificado en Unicode por ese `int`. Este método aparece en la sección Notas del enunciado:

![imagen](https://user-images.githubusercontent.com/10425834/58587568-b8f85d80-822b-11e9-9381-14ec08ee5d31.png)
[Link a la actividad](https://github.com/IIC2233/Syllabus-2018-1/blob/master/Actividades/AC11/AC11.pdf)

Otra forma de hacerlo, sin utilizar `chr()` es hacer esto:

```python
bytes([byte]).decode("ascii")
# byte es un int
# bytes([byte]) es la representacion del byte como string
# bytes([byte]).decode("ascii") es la conversión a ASCII
```

A ti te da un error porque estás tratando de hacer `decode` de un `int`, y no de `bytes`, entonces lo que yo hice que convertir ese `int` en un objeto del tipo `bytes` (`bytes([byte])`) y eso decodificarlo.

Ojalá te haya quedado más claro ☺️ Lo que puedo sacar en limpio de tu pregunta y esta respuesta es que está súper bien cuestionarse por qué algo funciona o por qué no lo hace, así que agradezco que lo preguntaras. También espero que esto deje en claro, para cualquier persona que vea esta issue (que espero que sean varios), es que **es muy importante la sección *Notas* de un enunciado** 👀

**Comment by perezpefaur** [comment]
Clarisimo! Gracias!
