### ISSUE TITLE
precio alcachofas

### ISSUE THREAD

**Issue by pdmino** [IIC2233/syllabus#446]
Hola, me parece que hay un error de escritura en parametros_precios.py ya que aparece guardado el precio de las alcachofas como PRECIO_ALACACHOFAS y me parece que debería ser PRECIO_ALCACHOFAS. Saludos

**Comment by DonJavi-538** [comment]
+1

**Comment by DCCollao** [comment]
Hola!
 Efectivamente es un error. Puedes usar PRECIO_ALACACHOFAS, pero si te incomoda mucho, corrígelo e indica en tu `readme.md` que utilizaste PRECIO_ALCACHOFAS en lugar del original, nosotros nos aseguraremos de corregir con el que utilices.

Saludos y éxito!
