### ISSUE TITLE
duda test 10 carga de datos

### ISSUE THREAD

**Issue by xperseosses** [IIC2233/Syllabus#446]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/Syllabus/issues/420).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, en el test 10, tengo buenos los de correctitud, pero malos los de carga de datos y me fijé que todos mis precios solo varían por una unidad, ejemplo: 991 != 990. Nose si es porque estoy usando mal round() o porque los tests están mal. 
(todo esto en el test de tamaño S, para que se pueda visualizar)
<img width="1001" alt="Captura de pantalla 2024-10-02 a la(s) 8 46 49 p  m" src="https://github.com/user-attachments/assets/4e7f35d1-67c0-410f-a7ad-800233b941a1">

**Comment by NachoRinda** [comment]
Hola, el detalle que puedes tener es que el descuento con redondeo se aplica a **cada una** de las pizzas del pedido por separado. No es llegar y aplicar descuento + round() una vez sumado todo, sino que debes aplicar el descuento con round() para cada pizza de un pedido. Avísame como te va considerando esto.

**Comment by xperseosses** [comment]
Sigue arrojando error, aunque ahora en menor cantidad de los datos :( 
<img width="1124" alt="Captura de pantalla 2024-10-02 a la(s) 11 27 30 p  m" src="https://github.com/user-attachments/assets/e7e16293-bb03-45ba-9471-69d0b9481057">

**Comment by NachoRinda** [comment]
Hola, acabo de ver tu código. El error que tienes es uno bastante imperceptible. Presta atención en donde calculas la ganancia: **el orden en el que multiplicas si afecta al resultado**. En general, deberías evitar multiplicar por un _float_ siempre que puedas cuando necesitas exactitud, y si no puedes como este caso, realízalo al final pues este tipo de datos inducen problemas de precisión.

**Comment by xperseosses** [comment]
gracias hermano ahí funcionó,  te pasaste de verdad🙏🙏🙏

**Comment by canija2000** [comment]
Hola! No termino de comprender el procedimiento del descuento. 
Lo siguiente es lo creo entender de lo comentado más arriba: 
- Un pedido de id : **x** tiene un descuento **z** , y si este pedido tiene 4 pizzas **w**, entonces este descuento **z** se le aplica a cada precio de **w** ? Para luego sumar las 4 pizzas con descuento? 
-  O, teniendo el total de 4 pizzas **w** le aplico el descuento a ese valor. 

Luego lo de los round, bueno, el enunciado dice que este se le debe aplicar al total de las ganancias por pedido, sin embargo acá mencionas que el round se le hace al descuento. Entonces no entiendo muy bien a quién seguir y cómo proceder.
Gracias!

**Comment by NachoRinda** [comment]
Hola, vayamos por partes. Leamos lo que dice el enunciado:
_La ganancia de cada pedido estará determinada por: la cantidad pedida de una determinada pizza, el
 tipo y tamaño de dicha pizza y el eventual descuento utilizado. En caso de que alguna ganancia sea un
 número decimal (float) se debe aproximar por redondeo con la función built-in round a la cifra de la
 unidad para que se obtenga una ganancia entera (int)._
De acá queda claro que la ganancia de cada pizza por separado, usando los atributos de las namedtuples, es: **precio * cantidad * (1- descuento).**
Ahora bien, podrías suponer, de manera totalmente honesta, que como cada pedido tiene el mismo descuento, este se podría aplicar luego de sumar todos los **precio*cantidad**. Sin embargo, algo que tal vez faltó considerar en el enunciado es ser más estricto en la manera de calcular pues cuando multiplicas floats y aproximas con round(), el orden en el que hagas las operaciones puede suponer un desvío final minúsculo (como el error original en esta issue) pero error al fin y al cabo.
Por lo tanto, la forma de calcular el descuento para obtener el resultado exacto de los tests es:

1) A cada pizza individual calcularle su ganancia dada la fórmula, asegurándote de multiplicar por el float al final (int * int * float) y a esta ganancia aplicarle round().
2) Sumar todas las ganancias calculadas del pedido.

Haciendo esto deberías llegar a la solución esperada. Si te fijas bien, la aplicación de round() en este procedimiento no contradice el enunciado pues este explícitamente dice que siempre se debe usar cuando tengas una ganancia tipo float. Y esto efectivamente se cumple pues al multiplicar int por float este último tipo es el que adopta el resultado por defecto en python.
Espero que te haya quedado claro, y si no, házmelo saber.

**Comment by canija2000** [comment]
Vale gracias!

**Comment by MaxPrietoC** [comment]
Hola , siguiendo los pasos de dados para calcular el precio de cada pedido que diste me sigue dando dos errores por una unidad en dos casos, especificamente en los de archivos de porte s y no logro entender el por que de estos (mi codigo esta subido a mi repositorio).

**Comment by RumNCola** [comment]
Este Issue me acaba de salvar media hora de cabezasos contra el teclado, muchas gracias

**Comment by ManoCarva** [comment]
disculpen pero aun tengo problemas incluso haciendo round antes de sumar los (int * int * float) entre los con mismo ID como se dijo. Habría alguna otra razón por la que algunos elementos se diferenciarian solo por 1 unidad
