### ISSUE TITLE
Output consultas que no retornan bases de datos

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2233/Syllabus#446]
¿Es necesario que el output sea el especificado en el enunciado, o puedo retornar de otra forma y luego manejar el output para mostrarlo en la gui de la forma pedida en el enunciado?

**Comment by Arcoirisky** [comment]
Por enunciado, es necesario. Ya que se les dió la forma en que se espera que trabajen las funciones O:

**Comment by jpmoraga1** [comment]
Entonces, en la consulta popular_actors, ¿cómo debería separar a los distintos actores? Es que el ejemplo del enunciado lo muestra con un actor, y yo pensaba retornar una lista de listas, donde cada elemento de la lista fuera un actor y sus películas como está en el enunciado D:

**Comment by Hernan4444** [comment]
@jpmoraga1 Si en alguna consulta, no está el output especificado, lo puedes decidir tu. Como en popular_actors no pusimos un ejemplo de output para más de un actor, puedes decidir tu

Saludos ✌️
