### ISSUE TITLE
método abstracto

### ISSUE THREAD

**Issue by Melisa96** [IIC2233/syllabus#446]
Hola :D, si tengo una clase abstracta con el método abstracto tipo @abstractmethod metodo(self), pero en las clases hijas, que son dos,  tengo respectivamente metodo(self) y metodo(self, otra) se puede ? (porque me funciona, pero igual me acusa error) me pasa en el de habilidad_especial.. O hago esa clase no abstracta para que funcione?
Gracias desde ya!!
😄

**Comment by mmunozmendez** [comment]
Hola, si se puede hacer lo que dices, quizás tu error vienes de otra cosa.
Éxito con todo 🦆

**Comment by Melisa96** [comment]
![Captura de Pantalla 2020-09-11 a la(s) 04 08 58](https://user-images.githubusercontent.com/26425588/92880847-cae01e80-f3e4-11ea-8d30-b5f25e0905dd.png)

Entonces no importa que me salga eso?
Gracias :D!

**Comment by mmunozmendez** [comment]
Hola, lo que te aparece es una advertencia y no un error como tal. Para evitar que aparezca puedes utilizar *args o **kargs.
Ánimo 🦝
