### ISSUE TITLE
Uso de funciones en parametros.py

### ISSUE THREAD

**Issue by mestuardo** [IIC2233/syllabus#446]
Hola! ¿Puedo programar funciones que voy a utilizar para calcular algunas cosas y dejarlas en el archvio parametros.py . (Por ejemplo los cálculos de probabilidades)

**Comment by mpsubiabre** [comment]
Hola @mestuardo !

Recuerda que el archivo parametros.py es exclusivo para almacenar parámetros, y significara un descuento agregar algo que no sea almacenamiento de parámetros 😟 . En ese caso es mejor que crees un archivo especifico para realizar las funciones, te sera mucho mas ordenado :)

Éxito con la tarea! 😄

**Comment by sbcorrea** [comment]
> Hola @mestuardo !
> 
> Recuerda que el archivo parametros.py es exclusivo para almacenar parámetros, y significara un descuento agregar algo que no sea almacenamiento de parámetros 😟 . En ese caso es mejor que crees un archivo especifico para realizar las funciones, te sera mucho mas ordenado :)
> 
> Éxito con la tarea! 😄

Y en ese caso, se podrían usar funciones como parametros de otras funciones? Por ejemplo, muy simplificadamente:
```from archivo import calcular()

def funcion_1(numero):
    return numero + 3

lo_que_quiero = funcion_1(calcular())```

gracias de antemano 🤗

**Comment by mpsubiabre** [comment]
Hola @sbcorrea 

Si se puede! python permite entregar funciones como argumento dentro de otras funciones. Pero recuerda que un función no es un PARAMETRO, aunque sea usado como argumento, sigue siendo una funcion.

**Comment by sbcorrea** [comment]
eso, argumento, perdon! graciasss
