### ISSUE TITLE
Pregunta Tarea 3 Función ciudades_distritos() uso de set()

### ISSUE THREAD

**Issue by VicenteDubo** [IIC2233/Syllabus#446]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, me preguntaba si es posible que en funciones como en ciudades_distritos(), es valido crear al principio un set (utilizando "set()") para luego iterar el generador usando el metodo add para de alguna forma filtrar los datos o si esto no se puede debido a la utilización de set() al principio.

Muchas Gracias

**Comment by TomasGMDC** [comment]
@VicenteDubo la creación de estructuras de datos con set(), list(), [], {}, (), etc., se puede usar dependiendo del contexto. Tal y como se indica en " #339 ", se puede usar o dentro de una función generadora, o dentro de un reduce(). Entonces considerando lo que mencionas, se puede si es que ciudades_distritos() es una función generadora. Si no, no.

Ahora, para estar 100% seguro, no te olvides de utilizar el script de revisión, ya que ese se usará para revisar que los códigos implementados sigan las reglas estipuladas en el disclaimer.

**Comment by BenjaMedinaPUC** [comment]
hola! espero que se encuentren bien, tambien tengo la misma duda por que no queda claro en el ejemplo: entonces puedo crear estructuras de datos por comprensión a pesar que no tenga ningun dato?  porque por ejemplo en una linea de codigo escribi

datos = [x for x in range(0) if False]

y no me tiro advertencia en el testcases de elementos prohibidos, pero tampoco sé si esta permitido, ya que los ejemplos de la issue crean estructura de datos por comprensión y recorriendo un generador

lista_1 = [función(x) for x in generador]
set_1 = {x.algo for x in generador}
gen_1 = (1 for _ in generador)

Estaré atento tu respuesta!

**Comment by TomasGMDC** [comment]
@BenjaMedinaPUC honestamente, ahí estás entrando en una "zona gris" de las reglas, porque visto desde un punto de vista de redacción, claro, estás cumpliendo con las reglas, y el script te indicará eso ya que solo ve la redacción. Pero teóricamente estás creando una estructura de datos vacía, una especie de list() o [] solo que de una forma alternativa, lo cual no se puede.

Ahora bien, comuniqué tu duda y me dijeron que el script manda jajaja, así que legalmente hablando, lo puedes aplicar si es que el script indica que está correcto.
