### ISSUE TITLE
.gitignore del README_inicial

### ISSUE THREAD

**Issue by MTGG123** [IIC2233/Syllabus#447]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/Syllabus/issues/420).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holaa. En el enunciado, cuando hablan del gitignore no mencionan nada del README_inicial, a diferencia de las tareas anteriores ¿Deberíamos asumir que también se ignora?

**Comment by NachoRinda** [comment]
Hola, dado la naturaleza de la tarea la revisión es distinta, el Readme no es tan relevante como en las demás pues no explicarás tu código allí, solo mencionarás tus referencias. Con respecto a tu pregunta, pese a que encuentres estos "vacíos legales" dentro del enunciado la recomendación es **siempre** ignorar todos los archivos que:
1) Explícitamente te piden ignorar
2) No aportan en **nada** a tu tarea
Por lo tanto, claramente el README_inicial no aporta en nada y deberías descartarlo. Lo que si te sirve de este archivo es que dentro de él tiene un formato para referenciar código en tu Readme original. Fuera de eso no te va a dar mucha más utilidad.

**Comment by MTGG123** [comment]
> Hola, dado la naturaleza de la tarea la revisión es distinta. El Readme no será revisado detenidamente como en las demás pues no explicarás tu código allí, solo mencionarás tus referencias. Con respecto a tu pregunta, pese a que encuentres estos "vacíos legales" dentro del enunciado la recomendación es **siempre** ignorar todos los archivos que:
> 
> 1. Explícitamente te piden ignorar
> 2. No aportan en **nada** a tu tarea
> 
> Por lo tanto, claramente el README_inicial no aporta en nada y deberías descartarlo. Lo que si te sirve de este archivo es que dentro de él tiene un formato para referenciar código en tu Readme original. Fuera de eso no te va a dar mucha más utilidad.

Okk, muchas graciass
