### ISSUE TITLE
Usar archivos genoma.txt y listas.txt en Testing

### ISSUE THREAD

**Issue by pdesolminihac** [IIC2233/Syllabus#447]
Se puede asumir que tenemos estos archivos a la hora de hacer el testing?, Esto para poder abrirlos y utilizar su información para testear

**Comment by Hernan4444** [comment]
@pdesolminihac puedes especificar que usarás algunos archivo de genoma.txt y listas.txt para testing pero recuerda que en el enunciado se especifica que *ddeben** sobreescribir `tearDown` y `sepUp` y el enunciado el ley. Si asumir tales archivos implica que no usarás correctamente esos métodos sugeriría darle una vuelta más a como crear los test.

Saludos ✌️

**Comment by Bneya** [comment]
Si para hacer los tests en un archivo **testing.py**, necesito importar las funciones a testear desde el módulo que creé para la tarea, ¿puedo asumir que ese archivo y el de testing estarán siempre en la misma carpeta?

**Comment by Hernan4444** [comment]
@Bneya si puedes asumir eso, pero aún así es necesario especificarlo en el readme por si acaso.

Saludos ✌️
