### ISSUE TITLE
Clase con más de 400 líneas

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#447]
Hola, actualmente mi clase campeonato ya tiene 400 líneas de código y aún me falta implementar un método. Qué puedo hacer para que no me apliquen descuento por extensión?

**Comment by dchahuan** [comment]
Hola, suerte en tu tarea. Ni una clase esta diseñada para que sea tan larga, así que probablemente tu clase campeonatos tenga métodos que no pertenecen a ella o algunas partes de tu código te estas repitiendo mucho envés de usar funciones externas que te puedan ayudar. Así que esa es la recomendación ver primero que método o atributo le estoy otorgando que no le corresponde o ver donde me estoy repitiendo mucho en mi código y talvez crea una función externa.

**Comment by En-clases** [comment]
Ok, gracias!
