### ISSUE TITLE
profesor Tarea 4

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#447]
![capture](https://cloud.githubusercontent.com/assets/26102365/25828650/bcea09b0-3427-11e7-9c62-e8a618c5274d.PNG)

cual es la posibilidad de haber escuchado al profesor 50/50, ya que no aparece en el enunciado

**Comment by indonoso** [comment]
Como no está especificado puedes asumir que es 50%. Recuerda ponerlo en tu readme

**Comment by Dunkan1** [comment]
ok, gracias
