### ISSUE TITLE
Duda Peleas entre DCCriaturas

### ISSUE THREAD

**Issue by MINGOD24** [IIC2233/syllabus#447]
Hola tengo un par de dudas sobre el bonus.

1) ¿Las DCCriaturas que estan enfermas pueden ser escogidas para el combate?
2) ¿Las DCCriaturas que estan escapdas pueden ser escogidas para el combate?
3) ¿Las DCCriaturas con un punto de salud pueden ser escogidas para el combate?
4) Al comenzar el combate, ¿Las DCCriaturas en disputa  se deben tomar el maximo de puntos de salud de ella? Porque osino puedo poner a pelear a una DCCriatura que tenga muy pocos puntos de salud a combatir con una que tenga varios, lo cual seria una manera de obtener dinero facil.

**Comment by JosefaPaz** [comment]
Hola @MINGOD24 ,

Como estas dudas no sale explícitas en el enunciado, queda a criterio tuyo como desees implementarlas, pero recuerda explicar en el readme cómo implementaste estos puntos, para que al revisarlo se pueda comprender qué decidiste hacer.

¡Éxito! 😸
