### ISSUE TITLE
Duda con formato Rotting Tomatoes

### ISSUE THREAD

**Issue by ciquezada** [IIC2233/Syllabus#447]
Hola, el formato de rotting tomatoes se supone que es "6.7/10", mi duda es que ¿siempre será un decimal con punto(".")? ¿incluso con numeros enteros (por ejemplo: "4.0/10" "10.0/10")?

**Comment by Hernan4444** [comment]
@ciquezada si, siempre tendrá punto en rotting tomatoes

**Comment by ciquezada** [comment]
gracias, perdon por ser minucioso pero ¿seguido del punto siempre habra un digito?, (para descartar casos como 10./10)

**Comment by Hernan4444** [comment]
@ciquezada Te recomiendo revisar los archivos que les damos. Ahí está la respuesta y  puedes además ver cualquier otro caso con los raiting.
