### ISSUE TITLE
Estilo Inventario

### ISSUE THREAD

**Issue by pwillmer** [IIC2233/syllabus#447]
Hola!  debemos seguir el estilo de inventario propuesto en el enunciado ? . Es decir, que exista una imagen por cada objeto que se vaya agregando? o podría señalar cada objeto con su cantidad respectiva?

**Comment by gatochico** [comment]
Hola!
Cualquier decisión respecto al diseño de las ventanas queda a **tu criterio**, siempre y cuando se cumplan los requisitos que pida el enunciado. Para el inventario, serían por ejemplo:

- Se puedan sacar elementos de este mediante drag and drop.
- Tenga capacidad infinita.
- Se puedan acceder en todo momento a cualquier elemento de este (vs. solo a los primeros/ultimos 10, por ejemplo).
- Se vaya actualizando correctamente con las acciones del jugador (agregar y sacar cosas correctamente). 

Si tu inventario hace lo anterior, está bien!
Salu3 :nerd_face:

**Comment by pwillmer** [comment]
A que te refieres con este punto?
- Se puedan acceder en todo momento a cualquier elemento de este (vs. solo a los primeros/ultimos 10, por ejemplo).
Que pueda acceder a los distintos tipos de elementos (choclo - alcachofa, etc)? o que pueda acceder al 1er choclo recolectado, 2do choclo, por ejemplo.

**Comment by EstebanReyes1998** [comment]
Perdón, pero no me queda claro algo respecto a la capacidad del inventario.
Dices que el inventario debería tener capacidad infinita, sin embargo en la issue #387 (https://github.com/IIC2233/syllabus/issues/387) dice que puede ser limitado dado a un parámetro.
Además en el enunciado nunca son claros con la capacidad de este.
¿Con que información me quedo?
Gracias

**Comment by gatochico** [comment]
El primer caso que mencionas! Que si por ejemplo tienes en tu inventario choclo, semilla de choclo y alcachofa, puedas sacar cualquiera en cualquier momento sin restriccion.

**Comment by pwillmer** [comment]
Vale gracias!

**Comment by gatochico** [comment]
Y tienes razón con respecto a la capacidad del inventario, @EstebanReyes1998 , sigue lo que dice la issue que marcaste: el inventario puede tener capacidad infinita o finita, siempre que lo menciones en el README! Disculpa la confusión :(

**Comment by dgzmr** [comment]
@gatochico hola, si el inventario es finito y se llega a tener mas objetos que el limite de lugares en el inventario está mal?

**Comment by gatochico** [comment]
@dgzmr En general, tienes dos opciones: 
- Hacer el inventario infinito, y nunca preocuparte por un límite máximo de elementos que este posea, cuidando que no se te 'pierda' ningún item.
- Si haces inventario finito, debes seguir la restricción de tamaño de este: Si tiene capacidad máxima de por ejemplo, 5 items, y ya almacenaste estos 5 items, el programa debe detectar el caso en donde trates de ingresar un sexto y no dejarle recoger/comprar el item. (Sería ideal que haya asociado un mensaje o algun aviso asociado a esto, para que no pensemos que es un bug :bug:  Por lo menos que esté avisado en el readme)

Como la decision del tamaño del inventario queda a tu criterio, tienes que ser consistente con tu elección, y manejarla de forma acorde.
Espero haberme explicado bien! :man_farmer: :
