### ISSUE TITLE
Posibles consultas vacias

### ISSUE THREAD

**Issue by Polea012** [IIC2233/Syllabus#448]
¿En el manejo de errores, todas las consultas pueden no retornar un resultado?
Por ejemplo, pariente_de retorna vacio si no encontro ningun pariente del grado indicado.
¿Pero indice_tamaño podria retornar vacío?, y si es asi, ¿seria porque no habian genes AGT o ACT en los genotipos buscados?

**Comment by Hernan4444** [comment]
@Polea012 no necesariamente, hay otras consultas que podrían llegar a caerse antes de retornar vacío. Aunque ahí ya es decisión de ustedes cómo enfrentan estos casos (y deben especificarlo en el readme). Por ejemplo, si una persona no tiene genes AGT o ACT en tamaño de guata (ninguno de los 2 genes). cuando tu quieras calcular el porcentaje de ACT en presencia de AGT + ACT, eso te dará `0/0` y eso es más factible a un `Genoma Error`. Pero ya para casos un poco más rebuscado, puedes definirlos tu mientras especifiques en el readme.

Saludos ✌️

**Comment by Polea012** [comment]
@Hernan4444 Muchas Gracias !
