### ISSUE TITLE
Problema variables globales entre módulos

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#448]
Hola,
Estoy en el testing y creé una carpeta que se llama TestingDatabase.
En mi módulo ```constantes.py``` defino si voy a entrar a "MiniDatabase" o a "Database" a buscar los archivos.
En mi módulo ```funciones_auxiliares.py``` importo el módulo con las constantes y uso la variable que toma uno de esos dos valores.
En el módulo ```testing.py``` necesito declarar una variable global con el mismo nombre que la que está en ```constantes.py``` para que al usar os.chdir(...) entre a la carpeta "TestingDatabase" en lugar de a la carpeta que se definió en constantes.
¿Cómo lo hago?
Probé usar "global" y no funciona :/

La otra opción es que cuando el ayudante pruebe el testing, vaya a ```constantes.py``` y cambie el string de la carpeta que esté por "TestingDatabase".

UPDATE:
```python3
globals()['DATA_A_USAR'] = "TestingDatabase" 
```

Tampoco funciona.

**Comment by Hernan4444** [comment]
> La otra opción es que cuando el ayudante pruebe el testing, vaya a constantes.py y cambie el string de la carpeta que esté por "TestingDatabase".

Eso es algo que puedes especificar en el Readme, no hay problema con eso.
