### ISSUE TITLE
Energía cuando voy a dormir y no gasté energía

### ISSUE THREAD

**Issue by pwillmer** [IIC2233/syllabus#448]
Hola! si el jugador va a dormir y con la energía que gana al realizar esta acción supera el definido con ENERGIA_JUGADOR debe quedar la cantidad de energía superior o respetar el definido en parámetros?

**Comment by gatochico** [comment]
En ningún momento la energía del jugador debe sobrepasar el máximo dado en los parámetros. Saludos! :man_farmer:
