### ISSUE TITLE
Visualización Qt Designer en Mac

### ISSUE THREAD

**Issue by SofiaNome** [IIC2233/syllabus#448]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Holaa!! No pude instalar pyqt desde el terminal, y en una issue vi que un ayudante recomendó descargarlo desde internet y adjuntó un link. Hice eso pero se me abre en un formato muy raro. Nose que hacer o como arreglarlo

![Captura de Pantalla 2021-05-06 a la(s) 13 49 55](https://user-images.githubusercontent.com/80910891/117343611-76594a00-ae72-11eb-945f-78a2c0727e73.png)

**Comment by pedroriosg** [comment]
Hola @SofiaNome !

Tienes que arriba a la derecha en donde sale Settings.
Luego, selecciona Preferences y marcas la opción Docked Window

Avisame si te funciona!

Saludos ✌️

**Comment by SofiaNome** [comment]
sii ahi si graciass
