### ISSUE TITLE
Error FuncionDef has no attribute _id_iic2233 (ultima version)

### ISSUE THREAD

**Issue by Jugonzalo** [IIC2233/Syllabus#448]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Tengo el siguiente error con el test de elementos prohibidos, me fije que mucha gente lo tenia en versiones anteriores, pero tengo la ultima y sigue saliendo 
![image](https://github.com/IIC2233/Syllabus/assets/143092203/d5e4466d-a6c5-47e8-90c7-96a838db5096)

**Comment by Hernan4444** [comment]
Hola @Jugonzalo 

Puedes pushear tu código por favor, para ver cuál es el motivo de este error.


Quedamos atentos!
Saludos

**Comment by Jugonzalo** [comment]
@Hernan4444 listo

**Comment by Hernan4444** [comment]
Hola @Jugonzalo 

Acabo de actualizar el .pyc con una versión que si debería correr con tu código.

El error fue que no nos anticipamos al caso que definieras una función dentro de una función generadora 😅 y por eso el script se caía, pero ahora ya no se caerá por eso.

Avisanos cómo te va con esta versión.

Saludos!

**Comment by Jugonzalo** [comment]
@Hernan4444 Muchas gracias!
