### ISSUE TITLE
[T04] 4.3 - Profesor

### ISSUE THREAD

**Issue by malopez16** [IIC2233/Syllabus#448]
Hola!
En el enunciado se indica:
"Cada alumno tendrá una probabilidad de haber escuchado esta información o no" y luego no se define tal probabilidad. ¿Cuál es?

Gracias.

**Comment by arturodelreal** [comment]
Hola, queda a tu criterio, especificándolo en el README. Saludos

**Comment by malopez16** [comment]
Ok! Gracias  :)
