### ISSUE TITLE
Lesiones en una competencia

### ISSUE THREAD

**Issue by festelle** [IIC2233/syllabus#448]
Si un deportista está participando en una competencia y se lesiona, automáticamente pierde la competencia en la que está o la termina, pudiendo ganar, y después de esto no puede participar en otras?

**Comment by vsantelicest** [comment]
Hola!
En la página 8 del enunciado que subimos, sale explícitamente que "Si un jugador se lesiona durante una competencia, la pierde automáticamente.", imposibilitando la opción de que gane esa competencia. Efectivamente, después de lesionarse, no puede participar en el resto de las competencias del día.
