### ISSUE TITLE
Con quien comunicarse por inasistencia a las actividades?

### ISSUE THREAD

**Issue by Magus-gut** [IIC2233/syllabus#449]
Hola, por temas de salud no podré asistir a la actividad del jueves, y probablemente tenga algunos problemas con la T01.
‽Con quien deberíamos comunicarnos en estos casos para verlos detalladamente?  (Soy de la sección 4)
Gracias!

**Comment by tomasgv** [comment]
¡Hola @Magus-gut!

Para casos de este estilo puedes comunicarte conmigo, al correo de bienestar:  bienestar.iic2233@ing.puc.cl.
Allí te contaré en detalle los pasos a seguir y medidas a tomar 🙌 .

¡Espero tu correo! ✨
