### ISSUE TITLE
Acciones antes de salir del juego 

### ISSUE THREAD

**Issue by jrrosas** [IIC2233/syllabus#449]
Hola!

Antes de finalizar la ejecución del programa (opción salir), se tienen que realizar las acciones del día, es decir, las mismas que al pasar a un día siguiente? 

Saludos,
Javier

**Comment by JosefaPaz** [comment]
Hola @jrrosas,

Las acciones - eventos - que ocurren al seleccionar "pasar al día siguiente" solo ocurren cuando tú eliges esta acción, por lo que al finalizar el programa con la opción salir, todo debería quedar igual en el mundo del Magizoólogo justo antes de elegir salir.

Espero haber aclarado tu duda :smile:
