### ISSUE TITLE
Genes por característica

### ISSUE THREAD

**Issue by depstein26** [IIC2233/Syllabus#449]
Me surgió una duda que al menos a mi no me queda claro con el enunciado. Para todas las características, solamente se expresan genes que "valen", o sea, por ejemplo, para el color de ojos, solamente van a haber genes 'CCT', 'CAG' y 'AAT' o podrían haber genes 'GTG' por ejemplo. Gracias!

**Comment by TomasSalvadores** [comment]
Nop, si podrían haber genes no correspondientes.
La idea es para que el calculo numerico que ocurre para determinar un fenotipo, se ignoren estos. Sin embargo como tu dices, no queda 100% claro. Es por esto que pueden no ignorarlos en los calculos pero debe quedar especificado en el readme.

**Comment by Hernan4444** [comment]
complementando la respuesta, para el calculo de gemelo_genetico (que usa el genotipo) tambien pueden decidir si ignoran o no los genes que no "valen". La solución considera ambas formas
