### ISSUE TITLE
Duda con ventana de Tienda

### ISSUE THREAD

**Issue by rgmorales1** [IIC2233/syllabus#449]
Una consulta, al abrir la ventana de la tienda, ¿debo cerrar la ventana del mapa, y después para poder abrirla de nuevo cerrar la de la tienda, o deben estar en simultaneo las 2 ventanas mientras Enzo este sobre la tienda? Es que me quedo la duda donde el ejemplo de tienda del enunciado se ve que es grande la ventana y dice que no se pueden sobreponer entre ellas.

**Comment by DonJavi-538** [comment]
+1

**Comment by jirarrazabal** [comment]
Hola! Esto queda a tu criterio. Puedes dejar las dos abiertas o cerrar el juego. Lo que no se puede superponer son los elementos de una ventana. Suerte!
