### ISSUE TITLE
Problema con lectura de archivos csv en pycharm

### ISSUE THREAD

**Issue by AntoniaChristensen** [IIC2233/Syllabus#449]
Tengo un problema porque pycharm no me reconoce los archivos como csv sino como txt y no se como arreglar eso. Esto hace que algunas columnas de los reviews me salgan cambiadas (review primero y id después) y he buscado como cambiar esto pero todavía no puedo arreglarlo. Intente borrando todos los archivos y abriéndolos nuevamente pero tampoco me sirvió.
En la foto sale el icono que me aparece para los archivos el cual no es el de csv sino de txt.
![whatsapp image 2018-05-05 at 14 31 11](https://user-images.githubusercontent.com/37154410/39665880-46369e3e-5071-11e8-9bd8-af4618f2266c.jpeg)

**Comment by IchottMano** [comment]
@AntoniaChristensen Hola!

Aparte de esto, tienes algún problema al abrirlos dentro de tu código? 
De no ser así, no debería ser un problema mayor en el desarrollo de tu tarea.

Saludos!

**Comment by Arcoirisky** [comment]
Pd: Pycharm abre así los archivos csv O: y muchos otros también c:

**Comment by AntoniaChristensen** [comment]
@IchottMano no que yo sepa pero nose como podría saber tampoco 😬😬
@Arcoirisky pero al parecer soy la única que me pasa esto! A los que les pregunté les aparece un icono de csv no de txt y como que les reconoce las comas (se ponen de color) y a mi no me pasa

**Comment by pcseisdedos** [comment]
a mi me pasaba eso igual (se daba vuelta el id con las reviews) para los comentarios en árabe... super raro como funcionaba la lectura de archivos, acá dejo un print que no me explico, igual no he tenido problemas con eso... de cierta forma el id y la review si se guardan bien pero se imprimen mal
![image](https://user-images.githubusercontent.com/18387808/39667734-ebeaceb0-5092-11e8-957c-ff7ff43645ca.png)

**Comment by santilaguna** [comment]
@AntoniaChristensen a mi igual me pasa! pero ignoralo aparecen cambiados pero cuando los lees (con el módulo csv al menos)  funciona correctamente.
