### ISSUE TITLE
Rango de notas para calculo de confianza

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#449]
No me queda claro el uso de rangos para el calculo de confianzas. Pues dicha formula usa un valor especifico y no el rango dado por las horas estudiadas.
Por favor no taggearme con el tag de la verguenza (LET)

**Comment by Dunkan1** [comment]
si te refieres a los rangos que dan en Escenarios (si es asi estos se usan solo para definir el rango en el que esta la confianza inicial)
si te refieres a los rangos en la tabla de notas esperadas entonces, las horas estudiadas te dan un rango de notas que puedes esperar, escoges uno al azar entre estos y tienes la nota esperada.
eje:
si estudio 6 horas metaclase
puede esperar una nota entre 40 y 59
asi que escoges una al azar(tienen distribucion uniforme) por ejemplo 45
y esa es la nota que espera

**Comment by benjamimo1** [comment]
@Dunkan1 vale, no habia entendido que era distribucion uniforme.
Gracias

**Comment by Hernan4444** [comment]
@benjamimo1 tal como dice dunkan debería ser uniforme la distribución.
Saludos!
