### ISSUE TITLE
Duda Tarea archivos, re-impresión de tablero y ranking.

### ISSUE THREAD

**Issue by armas01** [IIC2233/Syllabus#45]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, quisiera saber 3 temas concretos de la tarea.

1.- Al momento de que un jugador pierde y tiene una partida guardada, yo asumo (y es lo que hice) que se debe eliminar la partida, sino causaría que se pueda volver a acceder al mismo tablero y ganar facilmente

2.- Al momento de re-imprimir el tablero, cosa que se debe hacer todo el tiempo, si yo tengo un input en donde le pregunto que hacer [1], [2] o [3], y cualquiera de esas preguntas llevan nuevamente a un follow-up input, debo re-imprimir el tablero? Siento que volviendolo a imprimir se vuelve complicado de seguir en la terminal.

3.- El ranking (puntajes.txt) debe ser un archivo que contenga TODAS las partidas guardadas? o, alternativamente, guardar el mejor puntaje relacionado a un nombre específico (como si fuera una Key de un diccionario)

Esas serían todas mis preguntas, muchas gracias de antemano.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by vicentethomas** [comment]
Hola! Antes que nada, porfa para la próxima separa tus dudas que tengan temas distintos en distintas issues. Es más que nada por un tema de orden, y que si alguien tiene la misma duda que tú la puede encontrar fácilmente :smile:
Ahora sí, respondiendo a tus dudas:

1. En el enunciado no sale especificado qué sucede con la partida guardada una vez perdida, así que queda a tu criterio y debes especificarlo en el readme para que el ayudante corrector entienda tu planteamiento. Puedes hacer lo que mencionas o tratar la partida guardada como una especie de "checkpoint".
2. El enunciado especifica que el tablero debe imprimirse cada vez que aparecen las opciones del menú de juego, pero no dice nada de si debe mostrarse tras un follow-up input como mencionas. Por lo tanto, sí puedes hacer lo que mencionas, pero cuidando de mostrar el tablero cada vez que se descubre una nueva casilla.
3. Según enunciado: "El formato del archivo queda a tu criterio, pero este deberá contener  los puntajes de **todas** las partidas finalizadas hasta el momento". Ojo que dice _partidas finalizadas_, no guardadas. Por lo tanto se refiere a todas aquellas partidas en que el usuario ganó o perdió. Además, como dice que son todas las partidas finalizadas, si un usuario tiene más de una partida finalizada, en el archivo puntajes.txt se deben guardar todos sus puntajes. 

Ojalá se entienda y avísame si quedaste con dudas! Saludos
