### ISSUE TITLE
Duda Recolección de datos para la creación de nuevas publicaciones

### ISSUE THREAD

**Issue by LaSamada** [IIC2233/Syllabus#45]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda Recolección de datos para la creación de nuevas publicaciones

Para la creación de publicaciones al usuario registrado se le pide el nombre de la publicación, precio y descripción. Para el caso del nombre de la publicación, **asumimos que el usuario no pondrá "," en él o restringimos el uso de "," para este input?**. Y en el caso del precio, **asumimos que el usuario solo ingresará valores enteros y no float o string?**

**Comment by Maxy15** [comment]
Hola! En el caso de las publicaciones, y a diferencia de los nombres de usuario, sí pueden tener "," en el contenido del mensaje, así que ojo con ese detalle 👀 Para los precios, queda a tu criterio si defines el input con float o int, o que todo sea string y luego lo pases al formato que más te acomode. Espero te sirva 😸

**Comment by LaSamada** [comment]
Hola! Me refería al nombre de la publicación, no a su mensaje de descripción. En ese caso, el nombre de la publicación puede contener ","?

**Comment by Maxy15** [comment]
Ah, okey. El enunciado dice que la descripción puede tener comas solamente, así que puedes asumir que el nombre no va a tenerlas. Recuerda colocar todas tus suposiciones en el README 🏷 Espero te haya quedado claro!
