### ISSUE TITLE
Citar codigos de 3ros.

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#45]
E encontrado ayuda en stackoverflow, para hacer mi código, y entiendo que hay que citarlo, pero no puedo encontrar el documento que explique como debo hacerlo.

**Comment by gatochico** [comment]
Hola! Para citar lo ideal es hacer dos cosas:

**1) Comentar la fuente dentro del código donde fue usado:**
![image](https://user-images.githubusercontent.com/37161120/76887617-4f504b00-6861-11ea-819b-ebab3b72c83a.png)

**2) Dentro del archivo README.md, en la sección "Referencias de código externo":**
![image](https://user-images.githubusercontent.com/37161120/76887839-a2c29900-6861-11ea-92d9-041b0e713f10.png)

Con eso deberías estar súper. Éxito! 🐦

**Comment by aaossa** [comment]
Adional a la buena explicación de @gatochico, hay un ejemplo similar en la [Clase 0](https://github.com/IIC2233/syllabus/blob/master/Clases/Semana%200%20-%20Bienvenida.pdf), subida al Syllabus 👌
