### ISSUE TITLE
Error en VS

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#45]
Hola, me podrían ayudar con este error que me aparece en visual studio, corro el codigo  en otro lado y me funciona perfecto pero en vs no. 

![Captura de Pantalla 2020-08-18 a la(s) 14 18 35](https://user-images.githubusercontent.com/69765490/90550371-ddf12d00-e15d-11ea-9be0-9430f3dea812.png)

Muchas gracias

**Comment by vsantelicest** [comment]
Hola! Prueba poniendo la clase Condominio con mayuscula y dime si funciona.

**Comment by diego-ayala-2000** [comment]
Sigue sin funcionar.

**Comment by xDanman** [comment]
Es porque solo estas ejecutando una linea, prueba apretando el boton de play de arriba a la derecha

**Comment by diego-ayala-2000** [comment]
Ahí me funciono, muchas gracias.
