### ISSUE TITLE
Error al instalar ubuntu

### ISSUE THREAD

**Issue by 222skully** [IIC2233/Syllabus#45]
Edición	Windows 11 Home
Versión	22H2
Instalado el	‎27-‎03-‎2023
Versión del sistema operativo	22621.2134
Experiencia	Windows Feature Experience Pack 1000.22659.1000.0

Ubuntu
![Captura de pantalla 2023-08-21 134740](https://github.com/IIC2233/Syllabus/assets/142363292/ebaa699c-0242-43ba-8ce1-7f49b8f2ad36)

No me deja descargar ubuntu, dice que haay un error y que le faltó descargar una caraacterística. Use wsl --install como apaarecía en el tutorial y se quedó pegado, después intenté de nuevo y pasó eso.

**Comment by gatochico** [comment]
Hola @222skully ,

Prueba con los siguientes pasos:

- Desactivar y volver a activar WSL en el panel de control:

- Panel de control > Programas > Activar o desactivar características de Windows > Subsistema de Windows para Linux

Si lo anterior no te funciona, puedes probar con algunos de los métodos vistos en esta issue: #13 

Saludos!
