### ISSUE TITLE
Error formato encomiendas.csv

### ISSUE THREAD

**Issue by cristhanos** [IIC2233/Syllabus#45]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by cristhanos** [comment]
Hola, escribo porque creo que hay un error de formato en el archivo encomiendas.cvs. He visto en las otras issues que más estudiantes han tratado de resolver esta misma duda y creo que no se entiende bien cuál es el problema que nosotros creemos que existe, es por eso que trataré de ser lo más detallado posible.
Cuando uno ingresa al menú de usuario tiene 5 opciones. La primera de ellas es hacer una encomienda: en ésta (en cuanto a emisor y receptor) sólo se pide ingresar el destinatario de la encomienda. Y debido al formato de "encomiendas.csv" sólo debemos agregar al archivo el destinatario de dicha encomienda.
En la opción 2 del menú de usuario pide revisar el estado de las encomiendas realizadas por el usuario de la sesión, es decir el emisor de la encomienda (quien no necesariamente es el destinatario de esta). Por lo que al momento de querer buscar qué encomiendas fueron realizadas por el usuario de la sesión, no voy a poder encontrarlas, ya que en el formato de las encomiendas no está el parámetro "Emisor".
Aunque si fuese el caso de que el formato de "encomiendas.csv" estuviese bien, (que lo único que se me ocurre es que DCCorreos fuese como un supermercado, en que el receptor es quien mismo realiza la encomienda), la opción 4 del menú de usuario sobraría, ya que dice "ver el estado de las encomiendas personales", es decir, las encomiendas en que el destinatario calza con el usuario que inició sesión, es decir, la opción 2 del menú de usuario y la 4, pedirían lo mismo.

Espero que lo lean detenidamente, gracias y espero resolver mi duda.

**Comment by tzehnder** [comment]
tengo la misma duda, comento para saber si responden algo.

**Comment by mvvaldes** [comment]
misma duda x2

**Comment by alvaritions** [comment]
misma duda, se me ocurrió hacer otro archivo guardando emisor y encomiendas respectivas pero no habría como recuperar las que ya están en la base de datos

**Comment by Emiliax16** [comment]
Hola! trataré de ser lo más clara posible:

Efectivamente el archivo de encomiendas no guarda emisor, por lo que la segunda opción del Menú de Usuario (Revisar el estado de encomiendas personales) mostrará sólo las encomiendas que hayas realizado en esa sesión en específico, ya que puedes guardar en tu programa la información de la encomienda asociada a la sesión del usuario. Es muy importante recalcar que toda encomienda ingresada **si o si** debe guardarse en el archivo `encomiendas.csv`, de tal manera que el admin pueda revisarlas. 

Recapitulando, toda encomienda creada debe guardarse en el archivo `encomiendas.csv`, pero tu programa debe guardar el emisor y toda la información de la encomienda ingresada mientras se esté en el Menú de usuario, de tal manera que la segunda opción de este menú pueda mostrar lo requerido.

Espero que haya quedado más claro, saludos!
