### ISSUE TITLE
Habilidad Aprendiz

### ISSUE THREAD

**Issue by antoniacobo** [IIC2233/Syllabus#45]
> Si esta habilidad es utilizada por soldados del jugador, no hay límite de minerales para robar. En caso de que sea la maquina quien aplica esta habilidad, el límite de minerales a robar es la cantidad de minerales que dispone el jugador en ese momento.

No entiendo a qué se refiere de cuando la habilidad es utilizada por soldados del jugador o la máquina

**Comment by leolivares** [comment]
Hola! Siempre que ocurra una invasión (de un planeta de raza Aprendiz) de parte del jugador,  se activarán las habilidades del aprendiz.
Por otro lado, cuando ocurra una invasión de Archimago, debes tomar en cuenta que también tiene las habilidades de un Aprendiz. En este caso, es una invasión de la computadora, y debes asegurar que el límite de minerales que podría robar, no exceda lo que dispone el jugador.
Espero que te ayude!

**Comment by Pipelao** [comment]
Hola :), una pregunta. Entonces, ¿el jugador puede robar más minerales que los que tenga el otro planeta invadido disponible?

Saludos

**Comment by leolivares** [comment]
@Pipelao Claro, como dice el enunciado, cuando el ejercito aprendiz del jugador ataca, no hay limite de minerales que para robar. Suerte!

**Comment by jminostroza** [comment]
Entonces no es necesario crear un método para utilizar la habilidad, ya que ésta se activa por defecto en un ataque??? 🤕

**Comment by leolivares** [comment]
@jminostroza 
Eso depende de la manera en que modelaste el problema. Debes pensar que sería mas conveniente e ideal.
Por lo general, es útil tener métodos que cumplan una sola función. De esta manera el código es mas claro y ordenado.

Lo que debes asegurar es que cada vez que el ejercito *Aprendiz* ataque, se active su habilidad, y se cumpla bajo las restricciones.
Suerte!

**Comment by Cschavez** [comment]
hola! con respecto a la misma habilidad: los minerales que roban son de los minerales que tiene la galaxia donde existe el planeta? si fuese así, significa que en la batalla los planetas que "pelean" tienen que ser de distintas galaxias? O cuando se hace la recolección de recursos, los minerales y deuterios recolectados se suman a una cantidad de minerales y deuterio específicamente del planeta? 
Muchas gracias !

**Comment by leolivares** [comment]
@Cschavez Hola!
Las batallas ocurren entre planetas de una misma galaxia.
Los minerales y deuterio del jugador son un fondo común de todos los planetas. Cuando se decide recolectar de un planeta, se agrega a ese "fondo común".

Entonces, si un archimago te ataca, solo debe poder robarte (como máximo), lo que tienes en tu fondo común de la galaxia.
Si tu ejercito *Aprendiz* ataca, simplemente no tiene limite para robar.

Suerte!

**Comment by frduran** [comment]
@leolivares Lo que no me queda claro es que si mi ejercito Aprendiz está invadiendo un planeta, éste al ser de la misma galaxia, si uso mi habilidad para robar, entonces estaría robando de mi propio pozo común (de la galaxia) no es así?
