### ISSUE TITLE
Tarea01: calendario

### ISSUE THREAD

**Issue by AmbrosioV** [IIC2233/Syllabus#45]
Una duda sobre la fecha/hora/calendario, suponemos un año de 12 meses y 30 días por mes?

**Comment by Hernan4444** [comment]
No pueden suponer nada, algunos meses tienen 30, otros 31. Los años bisiestos hay 29 de febrero y es por ello que uno de los desafíos es poder diferenciar tales meses y años bisiestos

Saludos!!

**Comment by AmbrosioV** [comment]
OK gracias por la aclaracion!
