### ISSUE TITLE
columnas invertidas de currencies.csv

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#45]
En la primera fila del archivo currencies.csv dice "name: string;symbol: string", pero creo el resto de los datos en las otras filas los ordenaron al revés.

**Comment by Hernan4444** [comment]
@mjgutierrez1 efectivamente los datos están al revés, acabo de arreglar el código y el archivo currencies.csv. Muchas gracias por avisar. 😄 

Saludos!!
