### ISSUE TITLE
path

### ISSUE THREAD

**Issue by lucasprato** [IIC2233/syllabus#45]
Hola! Desde que punto es necesario incluir el path cuando creee archivos?
"<mi_usuario>-iic2233-2019-2", "Tareas", "T00", "partidas", "<nombre>"
O simplemente
"partidas", "<nombre>"

Pregunto esto porque quizás cuando los correctores revisen la tarea van una carpeta "partidas" por cada alumno que corrigan, entonces python tiraría error porque no sabría donde guardar el nuevo archivo.

**Comment by gatochico** [comment]
Hola!
La segunda opción que indicas es la correcta. Esto es ya que tu programa buscará la carpeta dentro del directorio donde esta el .py a ejecutar y por ende, solo estará disponible el directorio `partidas` que corresponde a tu programa (no se confundirá con las carpetas de otros alumnos). 
Saludos y exito!

**Comment by lucasprato** [comment]
Gracias por la respuesta! Mi problema es que cuando lo hago con partidas/archivo me sale el siguiente error en la consola que no se cómo arreglar:

Traceback (most recent call last):
  File "/Users/prattowski/lucasprato-iic2233-2019-2/Tareas/T00/samples.py", line 20, in <module>
    archivo = open(ruta_juego, "w+")
FileNotFoundError: [Errno 2] No such file or directory: 'partidas/lucaja_prueba.txt'

Pero cuando lo hago desde "<mi_usuario>-iic2233-2019-2", "Tareas", "T00",... si se crea el archivo. Puedo dejar esta ruta relativa más larga o si o si debe ser partidas/achivo??

**Comment by jmwielandt** [comment]
Hola!

Te recomiendo revisar la issue #10 para solucionarlo.
Nosotros ejecutaremos tus tareas estando en T00, por si te lo preguntas.

Saludos~

**Comment by lucasprato** [comment]
Buena! Por lo que vi, sería un problema de Atom. Lo que voy a hacer es mantener el directorio más largo para que me funcione mientras programo y cuando envíe la tarea finalizada cambiaré al path mas corto "partidas"/"archivo". Debería funcionar esto, cierto?
Saludos

**Comment by gatochico** [comment]
Para asegurarte, podrías probar corriendo tu tarea desde la consola directamente tras haber cambiado los paths, o pidiendole a alguien más que la corra en su computador :0
