### ISSUE TITLE
Supuesto tupla (def verificar_alcance_bomba)

### ISSUE THREAD

**Issue by Fopazov** [IIC2233/Syllabus#45]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. ¿Podemos asumir que la posicion representada por la tupla va a pertenecer adentro del tablero?

**Comment by BenzoylMorexide** [comment]
Hola, creo yo que quizás podrías asumirlo. Si pides coordenadas a una lista de lista que no están dentro de la lista te va a tirar error el programa mismo.

**Comment by cegalleta** [comment]
Hola!!

Si bien es cierto que no tendría sentido ingresar una tupla correspondiente a una posición fuera del tablero, parte de la tarea consiste en manejar errores, por lo que si ingresas una tupla incorrecta tu programa debe ser capaz de identificarlo y seguir ejecutándose sin caerse.
