### ISSUE TITLE
Selección de Recursos

### ISSUE THREAD

**Issue by isihirmas** [IIC2233/syllabus#45]
Hola, puedo asumir que el tipo de recurso que se colecta es aleatorio? En el enunciado solo se especifica que la cantidad es aleatoria. Gracias!

**Comment by isihirmas** [comment]
o da lo mismo el tipo de recurso y solo importa la cantidad? Porque mas adelante en el enunciado no se especifica el uso de cada tipo.

**Comment by jeschuwirth** [comment]
![image](https://user-images.githubusercontent.com/37160256/54962287-f9451200-4f42-11e9-9a79-c8aa36e5cdbd.png)

En DCCivilization existen 3 tipos de recursos, piedra, madera y oro.

Como dice el extracto de enunciado, un trabajador se asigna a recolectar un recurso y luego recibe una cantidad de este, por lo que el usuario debe elegir un trabajador y asignarlo a trabajar en uno de los 3 recursos (de forma no aleatoria).

Para tu segunda pregunta, en el extractor 6.1.2
![image](https://user-images.githubusercontent.com/37160256/54962436-9607af80-4f43-11e9-885f-f32d3be8ffaa.png)

Tenemos que en los archivos dice la cantidad de cada recurso necesaria para construir cada tipo de edificio.

Espero haber contestado tus dudas, suerte en la tarea :)

**Comment by fpaez7** [comment]
> Hola, puedo asumir que el tipo de recurso que se colecta es aleatorio? En el enunciado solo se especifica que la cantidad es aleatoria. Gracias!

En el archivo acciones te das cuenta claramente que no es aleatorio

**Comment by fpaez7** [comment]
> Hola, puedo asumir que el tipo de recurso que se colecta es aleatorio? En el enunciado solo se especifica que la cantidad es aleatoria. Gracias!

En el archivo _acciones.csv_ hay pistas que indican que no es aleatorio
