### ISSUE TITLE
Metodo Ciclo_mas_corto

### ISSUE THREAD

**Issue by gmoran77** [IIC2233/Syllabus#45]
En este metodo nos dan el hint: "la diagonal de la matriz indica si existe una conexión desde una estación a ella misma, es decir, la existencia de ciclos." 

¿Se refiere a la matriz elevada o la matriz original? De igual forma no entiendo que quiere decir, si tengo una diagonal de solo 1's ¿En que estación estaría haciendo el ciclo o simplemente se refiere que puede existir un ciclo en cualquier estación de la matriz?

**Comment by CrisHD935** [comment]
Hola! Se refiere a ambas matrices, donde la matriz original indica conexión directa y luego el índice de elevación indica la cantidad de estaciones intermedias. Por ejemplo, una matriz elevada a 3 indica la cantidad de caminos con 3 estaciones intermedias entre 2 estaciones específicas. Con la diagonal, esta indica ciclos entre estaciones en el mismo orden. Por ejemplo, el primer elemento de la diagonal indica que la primera estación tiene un ciclo consigo misma, la cantidad de estaciones intermedias depende del elevador. Luego el segundo elemento de la diagonal indica ciclos de la segunda estación consigo misma y así. Entonces en el caso de una diagonal de sólo 1's, esta indica que todas las estaciones tiene un ciclo.

**Comment by emivenezian** [comment]
Hola, no seria que una matriz elevada a 3 indica la cantidad de caminos con 2 estaciones intermedias (tres tueneles)? Porque lo que yo entendi es eso. 
En el enunciado dice:
En la matriz elevada a 3, podemos ver que existe un 2 en la coordenada (0, 0). Esto quiere decir
que existen 2 caminos que pasan por 3 túneles para llegar a la estación "A" partiendo desde esa
misma estación. Si observamos la red original, justamente existe el camino "A -> B -> D -> A" y
"A -> C -> D -> A".

**Comment by CrisHD935** [comment]
Si! Me equivoqué, perdón, efectivamente el índice de elevación indica la cantidad de túneles, no la cantidad de estaciones intermedias
