### ISSUE TITLE
ayudantia serializacion

### ISSUE THREAD

**Issue by jfpena1** [IIC2233/syllabus#450]
Hola, estaba haciendo la ayudantia y en los ejercicios, en la parte 2, no me acuerdo bien como se podia hacer lo pedido. No entiendo si en la funcioon cargar_persona() primero tengo que hacer un read (con "br") y luego hacer load con el object_hook, o si se debe hacer otra cosa. Fui a la ayudantia pero no me acuerdo de esa parte. Muchas gracias

**Comment by jjaguillon** [comment]
Hola. En la parte 2 se les pedía cargar a las personas filtrando parámetros mediante un object_hook.

## ¿Qué hace un object_hook?
 
Lo que hace es transformar los diccionarios dentro del archivo y transformarlos a una instancia de Persona

## ¿Cómo?

El parámetro de object_hook puede recibir una **función** dentro de **json.load()** lo que permite que la lectura de estos diccionarios pasen a ser parámetros de la clase Persona, por lo tanto, dicha función debe recibir como parámetro un diccionario.

```python
def funcion_hook(dicto):
    pass
    # retorno una instancia de la Clase que requiera

def cargar(json_path):
    # json.load(json_path, object_hook=funcion_hook)
    pass
```
