### ISSUE TITLE
Prints de las competencias

### ISSUE THREAD

**Issue by pedroriosg** [IIC2233/syllabus#450]
Hola! Quería saber si luego de cada competencia (Atletismo, Natación, Gimnasia y Ciclismo) se deben imprimir mensajes en la consola indicando que fue lo que pasó (por ejemplo, quien gana, o si hay empate, etc) o basta con la información que se escribe en el `resultados.txt`

Gracias!!

**Comment by hsazos** [comment]
¡Hola @pedroriosg !

Dado que no esta explicito en el enunciado, queda a tu criterio si imprimirlo en consola o no.

¡Animo con la tarea!🦕
