### ISSUE TITLE
Documentacion Personal Midterm

### ISSUE THREAD

**Issue by nachotagle** [IIC2233/Syllabus#450]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Contenido

Hola!! Queria consultar algo respecto de la documentación personal midterm (Carnet de Identidad, TUC, etc...), ya que lamentablemente la semana pasada se me perdio la billetera, y estoy sin TUC ni carnet ni nada, por lo que ***quería ver si seria valido mostrar una foto de mi Portal UC o foto de mi carnet***.

Muchas Gracias!! Saludos.

**Comment by lucasvsj** [comment]
Hola @nachotagle 

Puedes presentar una foto de cualquier documento personal que tengas. Con esto, mientras sea valido el documento de la foto, lo aceptamos sin problemas.
Lamentablemente foto del Portal UC no seria valida en este caso
