### ISSUE TITLE
importacion ciclica

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2233/syllabus#450]
Hola! un modulo de mi codigo se pasa de las 400 líneas (tiene 500) y tiene 4 funciones que se llaman constantemente entre ellas. Quería separarlo en dos módulos pero tendría una importación cíclica. Si se que había una issue antes pero es imposible usar esas soluciones ya que en todas partes hago la recursion. Existe alguna forma para solucionarlo? gracias.

**Comment by JosefaPaz** [comment]
Hola @mariovaldesa ,

Te recomiendo leer nuevamente tu código y ver si encuentras partes de las funciones que se repitan constantemente, ya que si fuera así puedes volver estas secciones una nueva función y así reducir enormemente tu código. 
Además de esto, creo que en la issue #444 están todos los consejos para que puedas solucionar tu problema, si tienes más dudas comenta desde ahí para mantener las preguntas de módulos cíclicos aquí 😄
