### ISSUE TITLE
problema con los argumentos de las funciones

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#450]
edit: IMAGEN CENSURADA

En la imagen de arriba se puede observar un problema que me está pasando con distintas funciones, y que supongo que tiene ver con una característica de python que yo desconocía:

Si se ve la imagen, en el código a la izquierda yo defino "def obtener_header(linea, dicc = {}, str_actual = "", cont2 = 0, cont1 = 0):" con dicc = {}.

Abajo a la derecha, en la consola, quiero escribir "obtener_header(linea)", pero es posible darse cuenta que obtener_header tiene guardado como argumento a dicc distinto de {}.

Por eso es que cuando ejecuto el código por primera vez no tengo problemas, pero cuando lo ejecuto por segunda vez mis outputs son distintos, porque por una razón que desconozco, los argumentos por defecto de algunas funciones no están tomando el valor por defecto que yo les asigné en el código, sino que están tomando otro valor (seguramente el último valor que tomaron esos argumentos en las ejecuciones pasadas de las funciones o algo así).

¿Cómo soluciono esto?, no estoy pudiendo avanzar por culpa de esto...

**Comment by vijuarez** [comment]
Esto pasa porque el argumento default que le diste es mutable. Python instancia los argumentos default una vez y después todas las veces que llames la función se van a "compartir" el mismo argumento. Por eso, cuando vuelvas a llamarla, las cosas que metiste en el diccionario van a seguir ahí.

Si quieres una solución rápida, dale como argumento default un `None` y después deja que si el argumento es `None`, le asigne a la variable un diccionario nuevo.

Saludos y mucha suerte!!

**Comment by mjgutierrez1** [comment]
Ok muchas gracias! llevaba mucho rato con este problema.
