### ISSUE TITLE
PROBLEMA AL HACER GIT PUSH

### ISSUE THREAD

**Issue by MGome** [IIC2233/syllabus#450]
Al intentar hacer git push me arroja el siguiente error (imagen adjunta). Supongo que tiene que ver el hecho de que use tenga mi repositorio clonado en dos computadores distintos (mi notebook y mi PC), pero no entiendo a que se debe, ya que según lo que dice el error tengo trabajo en el repositorio que no tengo en mi unidad remota, siendo que no he hecho modificaciones en el notebook más allá de hacer git pull. Para corroborar que no he hecho modificaciones por error desde el notebook revisé el último push que hice en mi repositorio, y me di cuenta de que corresponde a un push hecho desde mi PC.

![image](https://user-images.githubusercontent.com/48321270/66451110-60cf3480-ea31-11e9-98fd-1a4c3f01fd3c.png)

**Comment by gatochico** [comment]
Hola! 

Lo que indica ese mensaje es lo **contrario** de lo que crees que pasó: tu repositorio **remoto** tiene cambios que tu repo local no posee. Sigue los siguientes pasos:

- Primero, :warning: **Haz una copia de tu tarea actual (la que quieres pushear y no puedes) en otra carpeta de tu computador, como un "respaldo"** :warning: Para evitar cualquier tragedia inesperada!
- Estando en tu repo privado, haz `git pull ` primero. Si te deja hacer pull, ahora revisa tu repo privado y ve si se sobreescribió algún cambio de tu tarea. Si es así, reemplazala por tu respaldo y listo! Ahora deberías poder hacer add/commit/push.
- Si no te deja hacer pull, clona tu repo privado de nuevo y luego simplemente le agregas tu tarea actual que tenías almacenada localmente.

Cuentanos cómo te va!
