### ISSUE TITLE
Reuniones para definir dificultad y nivel de progreso

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#450]
![capture](https://cloud.githubusercontent.com/assets/26102365/25832815/5e8a242e-3443-11e7-9352-08549106f276.PNG)

despues de leer el enunciado no encontre un punto en que se use la dificultad dada por el ayudante(solo la de la tabla) o como definen el nivel de progreso (que es un porcentaje)
?debemos definirlo como queramos...? y añadirlo en el README?

**Comment by flobarrios** [comment]
Hola! al final del enunciado dice:

_Cualquier detalle que no esté mencionado en el enunciado realice supuestos razonables._

Por lo tanto, queda a su criterio y expliquen como lo utilizaron en el README 😃

**Comment by Dunkan1** [comment]
ok, gracias
es que pense que como el nivel de progreso es algo que influye mucho en la simulacion, nos lo darian.
