### ISSUE TITLE
Visual Studio Code no abre ventanas de Pyqt5

### ISSUE THREAD

**Issue by EliMollo** [IIC2233/syllabus#450]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, durante la AS2 intenté correr el main.py y no se visualizaba la ventana, pero al correrlo desde IDLE se veía perfectamente. También al correr código en vcode la consola funciona bien (alertando de errores, etc). Se abre python launcher, pero después de unos segundos sale que 'la aplicación no responde'. Corrí la AF4 para ver si era un problema con pyqt y tampoco abre las ventanas creadas.
**Cómo puedo arreglar vscode para que abra las ventanas de pyqt5?** Es más cómodo trabajar ahí que en IDLE :(

![Captura de Pantalla 2021-05-06 a la(s) 21 09 59](https://user-images.githubusercontent.com/62027424/117384076-213c2900-aeb0-11eb-9b76-c180dc5cf042.png)
![Captura de Pantalla 2021-05-06 a la(s) 21 10 14](https://user-images.githubusercontent.com/62027424/117384083-2600dd00-aeb0-11eb-8202-f23d0c7557c0.png)
![Captura de Pantalla 2021-05-06 a la(s) 21 14 37](https://user-images.githubusercontent.com/62027424/117384087-28fbcd80-aeb0-11eb-9880-28c92a210b48.png)
![Captura de Pantalla 2021-05-06 a la(s) 21 14 49](https://user-images.githubusercontent.com/62027424/117384090-2a2cfa80-aeb0-11eb-8505-bd34bed082a1.png)

**Comment by aaossa** [comment]
Hola @EliMollo 👋 El que las ventanas se comporten distinto me hace pensar que podrías tener dos versiones de Python distintas, una que estás ocupando en tu consola y la otra en VS Code. ¿Podrías verificar que sean la misma? Desconozco cómo se hace exactamente en VS Code, pero lo más fácil que se me ocurre es importar `sys` e imprimir `sys.version_info` 🤔 También podría ser que algun plugin de VS Code está haciendo algo indebido, pero si el editor te ha funcionado bien el resto del semestre no debería ser el caso. Última pregunta, ¿esto te pasó solo en la actividad o con los ejemplos de los contenidos también?

**Comment by EliMollo** [comment]
Hola profe!, al correr los ejemplos de los contenidos pasó lo mismo, y esto fue lo que imprimió sys.version_info: 
![Captura de Pantalla 2021-05-10 a la(s) 21 52 43](https://user-images.githubusercontent.com/62027424/117748082-611b4d00-b1dd-11eb-8cf0-2a6b4fa74159.png)

**Comment by EliMollo** [comment]
Al correrlo desde la terminal pasó lo mismo que en vscode, y sobre las versiones de python, creo que la 2.7 viene por defecto en Mac.
![Captura de Pantalla 2021-05-11 a la(s) 11 48 29](https://user-images.githubusercontent.com/62027424/117847116-0ff87100-b250-11eb-8f42-fb1bef89cce6.png)
![Captura de Pantalla 2021-05-11 a la(s) 11 55 09](https://user-images.githubusercontent.com/62027424/117847129-11c23480-b250-11eb-9d75-5ef60780899c.png)
![Captura de Pantalla 2021-05-11 a la(s) 11 56 39](https://user-images.githubusercontent.com/62027424/117847133-125acb00-b250-11eb-869c-03299220d25b.png)

**Comment by aaossa** [comment]
hola @EliMollo , aún tienes este problema? 😅

**Comment by EliMollo** [comment]
Hola profe, sigo con el mismo problema. Por el momento estoy usando Pycharm o IDLE

**Comment by gatochico** [comment]
Hola @EliMollo! Por lo que mandas en tu pantallazo, pareciese que tienes tanto 3.6 y 3.7 en tu computador 🤔 (esto es porque en los Mac ya viene python 3.6 y 2 por defecto). Puedes correr lo siguiente para comprobar algo?

Desde tu terminal corre estas dos cosas:
`python3 --version`
`python3.7 --version ` (o `python37 --version`, si la anterior te lanza error)

Y mándanos el resultado.

De paso, por si las moscas, prueba correr desde tu terminal la AS2 pero así : `python3.7 main.py` (o `python37`, el que te funcione jaja).

Quedo atenta!

**Comment by EliMollo** [comment]
Hola! este fue el resultado
![Captura de Pantalla 2021-05-24 a la(s) 16 00 40](https://user-images.githubusercontent.com/62027424/119401536-9cbc1980-bca9-11eb-8aeb-3efba2c259f8.png)
![Captura de Pantalla 2021-05-24 a la(s) 16 02 20](https://user-images.githubusercontent.com/62027424/119401550-9e85dd00-bca9-11eb-96c8-32b79dfed0ee.png)

**Comment by gatochico** [comment]
Entonces tu terminal sí está redirigiendo correctamente a 3.7 también 🤔 

Lo siento por pedir tantas cosas jaja, pero puedes ejecutar el código:
```
import sys
print(sys.version_info)
```
desde IDLE? (que es donde te corren correctamente pyqt5)

**Comment by EliMollo** [comment]
No hay problema, con tal de solucionarlo jaja
![Captura de Pantalla 2021-05-24 a la(s) 16 15 04](https://user-images.githubusercontent.com/62027424/119402677-451ead80-bcab-11eb-8559-c49506d614d7.png)

**Comment by gatochico** [comment]
Hola!

Hemos estado viendo tu error, y tenemos una idea que podrían ayudar.

### **Desinstalar e instalar una versión específica de pyqt5**: 
Si actualmente tu versión de macOS es **Big Sur**, algunes ayudantes han reportado problemas con pyqt5 parecidos a los tuyos. Lo que hicieron en este caso fue instalar una versión en específico de pyqt5:

1. Desinstalar pyqt5 con `pip3 uninstall pyqt5`.
2. Instalar la versión 5.15.4 de pyqt5 con `pip3 install PyQt5==5.15.4`

Prueba corriendo la AS2 desde tu terminal ahora y nos cuentas como te va :0

**Comment by EliMollo** [comment]
Funcionoooo! 🎉💃🏽 Muchas gracias 


![Captura de Pantalla 2021-05-24 a la(s) 19 01 33](https://user-images.githubusercontent.com/62027424/119417021-efee9600-bcc2-11eb-98d5-bcb3f21704da.png)
![Captura de Pantalla 2021-05-24 a la(s) 19 02 44](https://user-images.githubusercontent.com/62027424/119417028-f4b34a00-bcc2-11eb-99eb-d3f77c8a0a03.png)
