### ISSUE TITLE
AssertionError por retornar un zip en votos_por_especie()

### ISSUE THREAD

**Issue by R3Y3X** [IIC2233/Syllabus#450]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

no permite retornar un zip y estos están permitidos. Tengo que buscar otra manera de retornar una tupla o se podra permitir retornar el zip?
AssertionError: <zip object at 0x000002077D3C3980> is not an instance of (<class 'list'>, <class 'tuple'>, <class 'set'>, <class 'filter'>, <class 'map'>, typing.Generator)

**Comment by Hernan4444** [comment]
Hola @R3Y3X 

Lo que pasa es que el tests no tenía estipulado el retorno de `zip`. Por el momento mi recomendación es hacer algo como `(x for x in zip(...))`, esto hará que lo retornado sea un generador del zip, esto no cambia tu respuesta y se asegura pasar el tests. De todas formas en el tests privados tendremos ojo con permitir el retorno de zip.

Saludos!
