### ISSUE TITLE
Medallero Competencia y calculo de puntaje T01 

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2233/syllabus#451]
¡Hola! Tengo un duda/idea, lo que ocurre es que en el formato de impresión de estado de campeonato se pide mostrar "los resultados que ha obtenido cada delegación en las diferentes competencias" que en el ejemplo se refleja en mostrar las medallas que cada delegación ha obtenido por competencia al final, pero el diccionario "medallero" de campeonato sólo almacena un int con las cantidades totales de medallas, por lo que quería preguntar si podría alterar el medallero para que fuera un dicc de dicc que me permitiera tener dos dicc dentro de "medallero" (uno por delegación) y que estos tuvieran las medallas totales y las medallas por deportes de cada delegación.
Otra duda que tengo, es cuándo debo calcular el puntaje de las delegaciones, pues en el enunciado solo aparece que se actualiza cada nuevo día, pero si en un día de entrenamiento ficho, entreno, sano o uso la habilidad especial, de cierta forma se altera la moral del equipo y creo que debería actualizarse en ese instante

**Comment by jitorcas** [comment]
Hola! @Jamesmoreno21 

Efectivamente, puedes crear los atributos que consideres necesarios para el flujo de la tarea, sin embargo dichos atributos **no pueden** alterar el flujo general. En tu caso, podrías tener ambos, un medallero que cumpla lo estipulado en el enunciado (cantidad total de medallas ganadas) y un medallero más específico. 

Con respecto a tu segunda pregunta, cuando una Delegación realiza una acción se deben efectuar en el momento las repercusiones de dicha acción (aumentar moral, disminuir dinero, etc), por lo que si debes calcularlas en el instante. 

Si tienes más dudas avísame! 
Éxito! 🥇

**Comment by Jamesmoreno21** [comment]
Ok! Me queda claro, muchas gracias!
