### ISSUE TITLE
Emular archivos con paraIO

### ISSUE THREAD

**Issue by mjgarrido1** [IIC2233/syllabus#451]
Hola, no entiendo muy bien como funcionan StringIO() y BytesIO(). No me queda claro con el ejemplo del contenido:(

**Comment by aaossa** [comment]
Tanto `StringIO` como `BytesIO` son objetos que simulan ser archivos, entonces podemos ocuparlo como si fueran archivos: podemos escribir y leer de ellos. ¿Por qué solo emulan ser archivos? Porque nunca estamos creando el archivo en sí, si salimos de Python no veremos nada en nuestro sistema (no hay `archivo.txt`, `StringIO.algo`, nada).

En el ejemplo emulamos que tenemos dos archivos, uno de entrada en la variable `file_in` y uno de salida en `file_out`. Cambiaré un poco el nombre de las variables y simplificaré algo el ejemplo.

```python
from io import BytesIO


archivo_inicio = BytesIO(b"Digamos que esto viene en un archivo")
archivo_final = BytesIO()
```

Supongamos que queremos copiar los contenidos de archivo_inicio, que están en texto plano, en archivo_final (un archivo binario), tal como si hicieramos `Ctrl+C Ctrl+V`. ¿Cómo lo haríamos con archivos reales?

```python
# Abrimos el archivo inicial en modo leer binario ("rb")
with open("inicio.jpg", "rb") as origen:
	# Abrimos el archivo final en modo escribir binario ("wb")
	with open("final.jpg", "wb") as destino:
		# Leemos todo lo del archivo inicial y lo escribimos en el final
		destino.write(origen.read())
```

Perfectamente podríamos querer probar esta funcionalidad antes de llegar y "meter la pata" con los archivos reales. Quizás no tenemos los archivos reales aún. Tal vez queremos buscar un método general en lugar de utilizar exactamente la estructura real del archivo. O quizás estamos buscando la forma más eficiente de hacerlo. Para todo esto, podemos usar `StringIO` y `BytesIO`, para no meternos con los archivos de nuestro computador.

```python
with archivo_inicio as origen:
	with archivo_final as destino:
		destino.write(origen.read())
		# Ahora veamos qué dice el archivo
		print(archivo_final.getvalue())
```

Finalmente, podemos explorar los contenidos de nuestros "archivos" sin salir de Python. (Si fuiste al último taller, esto podría sernos útil al crear un test por ejemplo 👀 )

En el material puede ser que esté demostrado de manera un poco rara, pero es porque no se utilizan context-managers (`with`) para leer el archivo. Simplemente se está usando `read(1)` (leer un caracter).

```python
# Estas declaraciones son como si hicieramos open(archivo) (no especificamos modo)
# (Mira como los usé más arriba, en el with)
file_in = StringIO("información como texto y más")
file_out = BytesIO()

# Leemos un caracter, si no quedan nos dará None
char = file_in.read(1)
# Usamos ese None para saber cuando detenernos
while char:
    # Convertimos el caracter a ascii y lo escribimos en el archivo
    file_out.write(char.encode("ascii", "ignore"))
    # Leemos el siguiente caracter
    char = file_in.read(1)

# Finalmente, revisamos que los contenidos sean los que esperamos
buffer_ = file_out.getvalue()
buffer_
```
