### ISSUE TITLE
Devolver item (drag and drop)

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#451]
En el enunciado dice que si se suelta un objeto del inventario en una posicion invalida se debe retornar a la posicion de inicio. ¿Esto significa que tiene que ser en la misma casilla del inventario o puede ser otra?

**Comment by jirarrazabal** [comment]
Hola! La idea es que el inventario quede como estaba antes, es decir, que si queda en una posición inválida no se modifique nada. Por esto debería ser en la misma casilla. Suerte!

**Comment by dgzmr** [comment]
vale
