### ISSUE TITLE
Duda sobre uso de tee()

### ISSUE THREAD

**Issue by maidazuniga** [IIC2233/Syllabus#451]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una pregunta sobre el uso de la función tee de itertools.
Tengo entendido que tenemos permitido usar toda la librería itertools, pero al momento de utilizar tee en una función, el archivo test_elementos_prohibidos me levanta una alerta. 

Adjunto imagen.
![Captura de pantalla 2024-05-25 155302](https://github.com/IIC2233/Syllabus/assets/162502366/09fb08a8-410d-4339-a6cf-b3415fecfe38)

Hay alguna forma en que me puedan orientar en cómo arreglar este "mal" uso, porque la función en sí me corre y pasa todos los tests entregados para ella, solo que estoy teniendo el problema que se puede observar en la imagen. La última versión de la tarea ya está en mi repositorio

**Comment by mpiavf** [comment]
Hola, te recomiendo ver la issue #406 en donde se explica el uso de tee para que no te lo tome como mal utilizado.
Me comentas!
