### ISSUE TITLE
Error al importar QtMultimedia

### ISSUE THREAD

**Issue by ljgonzalez1** [IIC2233/syllabus#451]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Aún con el problema de la [issue 417](https://github.com/IIC2233/syllabus/issues/417), ocupé como solución temporal una Raspberry Pi que tengo. En ésta puedo importar la mayoría de módulos de PyQt5 sin problemas.

![Screenshot_20210510_191109](https://user-images.githubusercontent.com/48295025/117737300-9452e180-b1c7-11eb-847b-fc9abb2472da.png)

Para esto me conecto por ssh a la tarjeta con X-Forwarding activado y monto mi computador como unidad remota en una carpeta usando sshfs. Esto me permite ejecutar los programas como si estuvieran en mi PC. Aunque supongo que está de más decir que el rendimiento es sub-óptimo.

![Screenshot_20210510_192952](https://user-images.githubusercontent.com/48295025/117737395-cd8b5180-b1c7-11eb-92ef-b4cbcdf5237c.png)

Durante la AS2 me topé con el siguiente error que impedía ejecutar el programa salvo que comente el `from PyQt5 import QtMultimedia`

![Screenshot_20210510_192939](https://user-images.githubusercontent.com/48295025/117737595-2b1f9e00-b1c8-11eb-95df-a6b0bce4b53f.png)

Para una solución temporal:
¿Qué puedo hacer para solucionar el problema al importar QtMultimedia?

Para una solución permanente ([issue 417](https://github.com/IIC2233/syllabus/issues/417)):
¿Qué puedo hacer para que no me levante error al importar módulos de PyQt5?

_Información de los sistemas (puede ser de utilidad):
Raspberry Pi:
    OS: Raspbian GNU/Linux 10 (buster) armv7l
    Kernel: Linux 5.10.17-v7l+
    DE: KDE5
    WM: KWin_
    
_PC:
    OS: KDE Neon 5.21.4
    Kernel: Linux 5.4.0-72
    DE: Plasma
    WM: KWin_

**Comment by aaossa** [comment]
Hola @ljgonzalez1 , estoy medio perdido con tu duda así que intentaré ordenarme. Tu problema es que no te funciona QtMultimedia en la Raspberry? Además, el problema en tu PC es que no puedes importar `QtWidgets`, cierto?

**Comment by ljgonzalez1** [comment]
Yap.
1- Gracias por la última respuesta. Ahora funciona QtMultimedia en la R-Pi. Con mi config funciona como casi cualquier otro PC con una distribución basada en debian, nada más que no es muy potente y tiene arquitectura ARMv7. Uso esta tarjeta como solución temporal para lo de abajo.

2- En mi PC no puedo importar módulos de PyQt5 a pesar de que la librería está instalada (QtWidgets, QtGui, QtCore, ...). Seguí lo que aparecía en la wiki.

![image](https://user-images.githubusercontent.com/48295025/117845569-af1c6900-b24e-11eb-8ae8-4bb71f2694c4.png)

El equipo tiene como versión principal python3.9, por lo que he de redirigir la instalación de librerías de `pip3 install <librería>` a `python3.7 -m pip install <librería>`. También he probado con pip3 por si acaso, pero el resultado es el mismo.

![image](https://user-images.githubusercontent.com/48295025/117844871-0a9a2700-b24e-11eb-818f-c58898c3976a.png)


Que era lo que había planteado en la [issue417](https://github.com/IIC2233/syllabus/issues/417) y todavía no puedo solucionar.

**Comment by ljgonzalez1** [comment]
Todo actualizado de todas las formas que se me ocurre, como usuario y administrador.
![image](https://user-images.githubusercontent.com/48295025/117861931-02e37e00-b260-11eb-8aab-02e7de50048b.png)

Y con python 3.9 es la misma historia. Puedo importar PyQt5, pero no cualquiera de sus módulos.
![image](https://user-images.githubusercontent.com/48295025/117862140-50f88180-b260-11eb-83ae-6650ec8d2674.png)

Respecto a mi OS, KDE Neon 5.21 es una distro basada en Ubuntu 20.04. La mayoría de comandos para este caso son similares. Las principales diferencias son que la integración con [Plasma](https://kde.org/plasma-desktop/) es mejor que la que se tiene con Kubuntu y hace una mejor administración de recursos.

**Comment by aaossa** [comment]
Hola @ljgonzalez1 , ¿pudiste solucionar esto? 🤔

**Comment by Wh4rp** [comment]
Hola, @ljgonzalez1. También tuve el mismo problema que con tú en KDE neon. Mi solución fue utilizar virtualenv e instalar el pyqt ahí. Probablemente a ti también te ayude.

**Comment by ljgonzalez1** [comment]
Gracias @Wh4rp . Veré cómo se hace lo de _virtualenv_ y probaré a ver si resulta.

Si de aquí a mañana (26/05/21) no publico nada, entiéndase como solucionado.
