### ISSUE TITLE
AC4: test no finaliza en el tiempo máximo asignado (pero solo a veces) (y en tests distintos)

### ISSUE THREAD

**Issue by m-cozzetti** [IIC2233/Syllabus#451]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema

Ejecutando los tests publicos, sale una exception que el test no termina en el tiempo máximo:

![image](https://github.com/user-attachments/assets/3c21c763-6276-423f-bf61-d0046a4dc809)

Tengo 2 problemas:

1. Este error solo ocurre algunas veces. Si se ejecutan los tests varias veces, algunas dira que se pasan todos, y otras saldra el error (approx 16% de las veces).
2. El error no siempre ocurre bajo el mismo test (a veces pasa con el test de que el thread no se inicia desde el jugar, a veces cuando se verifica que se inicien todos los theads, etc.), asi que no tengo forma de saber cual parte de mi codigo podría estar generando el problema.

que onda?????????????????? test no determinista?????????????????????????????????????????????????????????????????????????????????

**Comment by Hernan4444** [comment]
Hola @m-cozzetti 

Lo que puede pasar es que hay una función que tiene algo aleatorizado, pero para los tests se cambian los valores de porcenajes, por lo que no debería pasar. Recomiendo ir a la clase para que un ayudante pueda ver tu código para evaluar donde podría estar el error. En otro caso, te recomiendo pushear tu código para que el cuerpo docente pueda ver el código y determinar si hay un error con los tests o con la solución.

Saludos!

**Comment by danogajardo** [comment]
hola, tuve el mismo error. Los ayudantes en la clase me dijeron que lo comentara en las issue

**Comment by Hernan4444** [comment]
Hola,

Recomiendo echarle un ojo al tema de los `daemon` porque eso puede hacer que un thread se siga ejecutando aunque no corresponda.


Espero que haya resuelto tu duda, en otro caso no dudes en preguntar. ¡Éxito con la actividad! 🦖
Saludosヾ(＾-＾)ノ

**Comment by mrmoon01000010** [comment]
Hola, me ocurrió este mismo error. Sobre la recomendación del `daemon`, no creo que ese sea mi problema por lo menos. A veces los test se ejecutan sin problema, a veces fallan dos, los errores no parecen ser consistentes.
