### ISSUE TITLE
[T04] - Eventos  - ayudantes: subir notas

### ISSUE THREAD

**Issue by malopez16** [IIC2233/Syllabus#451]
Hola!
Con respecto al punto 4 del enunciado de la tarea, se indica:
Después de dos semanas desde alguna de estas evaluaciones (haciendo referencia a controles, actividades y tareas), los ayudantes entregarán las notas al coordinador para que él las suba.
Pero luego, en el punto 6, se indica:
Ayudantes: Subir notas (8 a 15 días después de rendir o entregar tarea)

Dos dudas:
1 - Con subir notas en el punto 6, se está refiriendo a entregarlas al Coordinador?
2 - A pesar de que se considere que el hecho de subir las notas pueda ser aplazado, dichos plazos no concordarían con lo que dice en el punto 6. (Serían 2 semanas para entregar las notas + lo aplazado = 14 dias + 3 a 5 días de aplazamiento) ). Cómo es entonces?

Muchas gracias!

**Comment by Dunkan1** [comment]
a pesar de lo que dice el enunciado
creo que seria ( 8-15 dias para ac y controles) y (14 dias para tareas) 
ademas ambos se pueden retrasar

**Comment by flobarrios** [comment]
Hola ! ha habido una actualización del enunciado, ahora es de la siguiente manera:

Los ayudantes entregan las notas al coordinador 2 semanas después de rendir o entregar evaluación (ac, controles, tareas y examen) y el coordinador **se puede o no** demorar entre 2 y 5 días en subirlas.

Saludos!!

**Comment by malopez16** [comment]
Gracias, aclarado!
