### ISSUE TITLE
Duda sobre módulo PyQt5 

### ISSUE THREAD

**Issue by papasconketchup** [IIC2233/Syllabus#451]
Hola,

No se porque pero cuando corro "main.py"  recibo una excepción del tipo ModuleNotFoundError diciendo que no existe un módulo llamado "PyQt5", siendo que si lo tengo instalado. No he podido arreglarlo.

**Comment by Arcoirisky** [comment]
Tienes por casualidad otro python instalado? Quizás lo instalaste pero para el otro Python uou intenta con Pip3 O:! 

O si usas anaconda, dicen que se come todas las librerías :(

**Comment by mblejeune** [comment]
@papasconketchup si estas usando pycharm a mi cada vez que abro como un nuevo proyecto me pide aplicarlo a ese proyecto especifico, aunque este instalado, intentando yendo a file -> default settings -> apreta el mas que aparece abajo como más a la izquierda y busca pyqt5 , apretalo cuando te aparezca y pon install package, ya hecho no olvides poner apply en default preferences! y luego ok y ahi te deberia funcionar si es que es eso :) 

edit : soy alumna! pero me pasó eso ya hartas veces jaja
