### ISSUE TITLE
¿A quienes afecta el nuevo día?

### ISSUE THREAD

**Issue by francisca0308** [IIC2233/syllabus#451]
Puede ser un poco absurda la pregunta, pero cuando paso al día siguiente, ¿todos los magizoologos se ven afectados y con ellos todas sus criaturas? ¿O solo se ve afectado el magizoologo "en línea" y sus criaturas?

**Comment by JosefaPaz** [comment]
Hola @francisca0308 ,

Esta issue ya fue respondida en la número #275

¡Saludos!
