### ISSUE TITLE
Duda cuando un Erkling roba un alimento

### ISSUE THREAD

**Issue by jturquiza** [IIC2233/syllabus#452]
Hola! perdón si ya lo preguntaron pero no lo encontré. En el enunciado sale que cuando un Erkling esta hambriento al comienzo del día va a robar un alimento al azar y pasará a estar satisfecho. Mi duda es si solo ocurre eso (cambiar estado de hambre), o se deben considerar también todas las cosas que pasan cuando se alimenta una criatura (el aumento en los puntos de salud, probabilidad de atacar al magizoólogo y probabilidad de rechazar un Buñuelo de Gusarajo)?
Gracias!

**Comment by moquezada** [comment]
Hola @jturquiza!

Tu duda se encuentra resuelta en las issues #336, #341 y #441. Si tienes dudas puedes revisar antes el compilado de issues #239 o utilizar el buscador con palabras claves respecto a lo que necesitas saber 😄 

Suerte en la tarea!
