### ISSUE TITLE
Diccionario de equipo

### ISSUE THREAD

**Issue by burizar** [IIC2233/syllabus#452]
Hola! En el enunciado nos dicen que el equipo de una delegación debe ser del tipo list. Si o si tiene que ser una lista o podría ser un diccionario?
Gracias!

**Comment by mmunozmendez** [comment]
Hola!
El equipo debe ser una lista, siguiendo el enunciado

Éxito 🦆

**Comment by IgnaciaJ** [comment]
Holaaa y el equipo podria ser una lista de listas que sean del tipo: [nombre del deportista, su instancia] ??

**Comment by mmunozmendez** [comment]
Hola
Eso sería una lista, así que si se puede 🦝
