### ISSUE TITLE
gemelo_genetico de Nebil Kawas

### ISSUE THREAD

**Issue by cirey1** [IIC2233/Syllabus#452]
Al usar mi funcion de gemelo genetico en el test1 me sale que el gemelo genetico de nebil kawas es sebastian cruz, con 34 genes en comun, en el resultados.txt sale que debiera ser el chuña  pero el solo tiene 25 genes en comun con nebil, por ende queria saber si mi funcion esta leyendo funcionando mal para este caso o es que el resultados.txt esta malo en esa parte.

**Comment by naazocar** [comment]
A mi me sale que es El Chuña con 68 genes en común :s
