### ISSUE TITLE
Movimiento fluido Sprite

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#452]
Según el enunciado el movimiento debe ser pixel por pixel, pero después dice que la cantidad de píxeles por cada movimiento es fija según el parámetro VEL_MOVIMIENTO.

No entendí muy bien esto, significa entonces  que si por ejemplo mi parámetro es igual a 10 entonces tengo que usar un loop que haga que el Sprite se vaya moviendo 1 pixel hasta que llegue a 10?

O se puede hacer que se mueva los 10 píxeles de una al apretar la tecla correspondiente?

**Comment by jeschuwirth** [comment]
Hola @FelipeA7,

El movimiento pixel a pixel se refiere a que te mueves por pixeles en vez de cuadros (por ejemplo de cuadro de pasto a cuadro de casa).

Por esta razón tu último razonamiento es el correcto, el personaje se movería 10 píxeles por apretar una tecla.

Suerte!

**Comment by JosefaPaz** [comment]
Hola! Y no habría problema si se mueve la misma cantidad de "N" que el largo de las celdas? Esto ya que quizás no se vaya a considerar fluido moverlo en "N" y quizá si en N/2

**Comment by jeschuwirth** [comment]
@JosefaPaz, efectivamente, si VEL_MOVIMIENTO es mayor que N, entonces el personaje se moverá más de una celda por movimiento. Este no es un problema, si un ayudante se encuentra con una tarea así le bajará el valor a VEL_MOVIMIENTO o se lo aumentará a N.

Recomiendo entregar la tarea con valores razonables para ambos parámetros :)

Suerte!
