### ISSUE TITLE
Error actividad del contenido 

### ISSUE THREAD

**Issue by mjgarrido1** [IIC2233/syllabus#452]
Hola, se me esta generando un error al correr la solucion de la actividad subida en el contenido, especificamente me aparece lo siguiente:
`caracter_base64 = base_to_num[byte_como_ascii]
KeyError: 'ÿ'`
cuando corro la funcion `algoritmo_base_64`
es un error de archivo o estoy haciendo algo mal?

**Comment by aaossa** [comment]
Hola! Como podrás notar, ese error se produce debido a que la key `"ÿ"` no se encuentra en el diccionario. ¿Qué quiere decir esto? Que el caracter `ÿ` no pertenece al alfabeto de base64:

```python
# Recuerda que para hacer el diccionario hacemos esto
string.ascii_uppercase +\ 
string.ascii_lowercase + \
string.digits + \
 "+" + "/" 
# Ese caracter no está en el diccionario!
```

Investigué un poquito más sobre qué podría estar provocando esto y se debe seguramente a la línea de código anterior a esa. En la solución, vamos transformando los `bytes`/`int`s a ASCII con `byte_como_ascii = str(chr(byte))`. En algún punto, un byte llevo a que Python decodificara una `'ÿ'`. Podemos saber exactamente cuál es el valor de byte que llevo a eso:

```python
# En lugar de hacer decode...
# (Opción 1)
str(chr(byte))
# (Opción 2)
bytearray([byte]).decode("ascii")
# (Opción 3)
bytes([byte]).decode("ascii")

# Queremos hacer el proceso opuesto, encode
bytearray("ÿ".encode("ascii"))[0]
# 1. Hacemos encode para convertirlo a bytes
# 2. Lo ponemos en un bytearray para acceder a cada byte del string
# 3. Como se representa con un byte, accedemos al primer elemento del bytearray
```

Si pruebas la línea de arriba, ese código lanzará una excepción:

```python
>>> bytearray("ÿ".encode("ascii"))[0]
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
        UnicodeEncodeError: 'ascii' codec can't encode character '\xff' in position 0: ordinal not in range(128)
```

Esto significa que ese caracter esta fuera del rango de "ascii", el utilizado en la actividad. Para ir un poco más allá, `chr` tiene un método opuesto que permite saber el byte que representa a un caracter: `ord`.

```python
>>> chr(64)
'@'
>>> ord("@")
64
```

Si usamos `ord` sobre el caracter que encontraste, obtenemos 255:

```python
>>> ord("ÿ")
255
```

Esto quiere decir que en algún momento de la iteración, la variable byte tomó el valor 255. Cuando pruebo el valor más alto de byte encontrado en el archivo, a mi me da 122. 

```python
with open("marciano64.png", "rb") as f:
        print(max(f.read()))
```

Cosas que se me ocurren: no estás leyendo el archivo correcto (se aplica sobre `marciano64.png`), estás leyendo el archivo de otra forma (lo que no debería causar problemas pero uno nunca sabe) o git descargó tu archivo de forma incorrecta (sería raro pero remotamente posible). Te pido que revises si estás leyendo el archivo correcto y si el valor del último código que escribí te da 122 o 255. Gracias!
