### ISSUE TITLE
Type del input en consultas.json

### ISSUE THREAD

**Issue by jtcaraball** [IIC2233/Syllabus#452]
Tengo una pregunta sobre el funcionamiento de consultas.json, cuando yo agrego una consulta
a través del GUI, ¿lo considera como un string? o si en los parámetros ingreso un boleando o un int,
lo guarda como tal? Pregunto para ver como implementar las excepciones. Muchas gracias!

**Comment by Arcoirisky** [comment]
Si haces type de lo que recibe la GUI debería de responder tu duda c: (Pero se consideraría un String)
