### ISSUE TITLE
Problemas con Visual Studio Code

### ISSUE THREAD

**Issue by alvarocisternas** [IIC2233/syllabus#453]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola!

Tengo un problema con VSC. Al parecer se me actualizó o cambió la configuración de éste (de manera automática) y cuando realizo la importación de un módulo en otro me aparece ** Import "módulo_importado" could not be resolvedPylance(reportMissingImports) ** 

Abrí actividades/tareas pasadas realizadas por mí para ver si me aparecía este error o era solo del actual módulo con el que estaba trabajando y el error me aparece en lo que he trabajado previamente y antes no existía ese problema.

Cuando intento ejecutar el módulo que posee importaciones me aparece ** The Python path in your debug configuration is invalid **.

De antemano muchas gracias, quedo atento!

**Comment by Pyngrei** [comment]
Yo también tengo el mismo mismo problema, estuve buscando soluciones pero realmente no supe como implementarlas o si siquiera sirve como una solución

Estos son los links de una solución que al parecer funciona, pero no entendí realmente como implementarla:
- [https://github.com/microsoft/pylance-release/issues/236](url)
- [https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#unresolved-import-warnings](url)

**Comment by gatochico** [comment]
Hola! Siguen con el error?

Si es así, quería saber cómo abren sus carpetas para trabajar en VSCODE (Open Folder o Open Workspace), y si este error ocurre solo con librerías de python o también con los módulos creados por ustedes mismos.

De momento, también les propongo ejecutar sus programas desde la **consola de comandos/terminal** en vez del botón de Run que provee VSC para que no les salga el error. Esto pueden hacerlo de dos formas:

- **Usando la terminal de su computador:** , abriendo la terminal de su computador en la carpeta con el archivo a ejecutar y corriendo `python nombre_archivo.py` o `python3 nombre_archivo.py`
- **Con la terminal integrada de VSC:**  Haciendo `Ctrl+Shift+Ñ` o, si no les funciona ese shortcut, Mediante la pestaña `Terminal -> New Terminal`. Esto les abre una terminal de su computador dentro de la misma ventana de vscode. Allí también van a la ubicación de su archivo y ejecutan el comando del paso de arriba.

En teoría, esas dos formas anteriores les deberían funcionar ya que no tienen que ver con VSC 🤔 Quedo atenta

**Comment by alvarocisternas** [comment]
Muchas gracias por la respuesta @gatochico . Efectivamente el problema tenía que ver con lo de Open Folder. Lo pude solucionar hace hartos días por suerte.

Saludos!

**Comment by gatochico** [comment]
Que bueno @alvarocisternas ! De todas formas recomiendo ejecutar programas por la terminal siempre por sobre los botones de Run de las IDES jaja, sobre todo si sigues en computación verás que todo se corre así!
