### ISSUE TITLE
Deportista puede jugar en ambas delegaciones?

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#453]
Holaa!
Un deportista puede ser fichado por ambas delegaciones? o solamente puede jugar por una?

**Comment by jitorcas** [comment]
Hola! @Gsalinas1506 

Un deportista puede pertenecer **solo** a una Delegación. 

Mucho éxito! 🥇

**Comment by Gsalinas1506** [comment]
Yaa, entiendo. Gracias!!
