### ISSUE TITLE
Ayudantía Serialización

### ISSUE THREAD

**Issue by LucianoDavico** [IIC2233/syllabus#453]
Hola!

Estaba tratando de resolver la ayudantía y al momento de escribir escribir la función `serializar_personas(personas)` tengo el siguiente error: `Can't pickle <class '__main__.Persona'>: it's not the same object as __main__.Persona`. Creo que en los contenidos publicados de pickle salía que cuando uno crea o carga un archivo mediante pickle.dump el tipo del objeto cambia, pero no entendí como se puede arreglar esto.

**Comment by jjaguillon** [comment]
Puede ser por dos cosas:

1.- Si estas utilizando Jupyter, puede que no te esté funcionando por eso.

2.- El __getstate__ no esté bien definido.

Me avisas si no es alguna de estas
