### ISSUE TITLE
Contención mutua entre clases

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#453]
¿Es mala práctica que una clase (objeto) contenga como atributo a otro objeto y viceversa?
Es decir, que se contengan mutuamente.
Ej:
```
class persona:
    def __init__(self, perro):
        self.perro = perro
        
class perro:
    def __init__(self, dueno):
        self.dueno = dueno


```
De manera de poder acceder al dueño desde el perro de forma directa y al perro desde el dueño de forma directa.

**Comment by Hernan4444** [comment]
@jorgeriesco es una mala practica. Esto se denomina referencia circular y no es correcto.
Imagina a un profesor y a un alumno, el profesor tiene como atributo a su alumno y el alumno tiene a su profesor como atributo ¿Que puede salir mal?

Digamos que el profesor tiene un método `poner_nota(alumno)` que dado un alumno, le pone una nota. Si el alumno tiene como atributo al profesor, el siguiente código es totalmente valido:

```
class Alumno
   ...
   def cambiar_nota(self):
       self.profesor.cambiar_nota(self)

```

¿No es un poco extraño que el alumno sea capaz de cambiar su nota cuando eso es una capacidad del profesor?

Lo ideal es que solo la clase profesor tenga un link a sus alumnos y si ellos necesitan algo de su profesor, hagas uso de decoradores (funciones como objeto) para darle algunas autorizaciones al alumno.

Para mas informacion  [visitar esta issue](https://github.com/IIC2233-2016-1/syllabus/issues/481)

Saludos!!
