### ISSUE TITLE
Duda en parentesco

### ISSUE THREAD

**Issue by savelozo** [IIC2233/Syllabus#453]
Una persona puede tener grado de parentesco 2 y n al mismo tiempo. Si cumplen con las características en común que ambos grados poseen podrían caber en ambas categorías (si es que cumplen con las características propias de cada grado, claramente). Si ese no es el caso, hay algún grado de prioridad?

**Comment by Hernan4444** [comment]
@savelozo si pueden tener ambos grado con una persona.
Saludos ✌️
