### ISSUE TITLE
Problema con función intentar_capturar_bandera 

### ISSUE THREAD

**Issue by isawilhelmy** [IIC2233/Syllabus#453]
Problema:
Tengo un FAIL al ejecutar los test cases publicos en la funcion intentar_capturar_bandera.

El error aparece cuando se ejecuta este test:
FAIL: test_intentar_capturar_bandera_blocking
Se verifica que los jugadores no se queden esperando a que se libere el lock
Traceback (most recent call last):
  ...
AssertionError: True is not false

El test está diseñado para verificar que el jugador no se quede esperando a que se libere el lock (lock_bandera). La bandera debe capturarse solo si el jugador puede obtener el lock inmediatamente (sin bloquear), utilizando acquire(blocking=False). Si no puede obtener el lock, debe continuar con su ejecución sin bloquearse.

Pero el problema es que el test aún indica que el jugador se queda esperando por el lock, lo que genera el fallo. El mensaje muestra que el jugador está capturando la bandera, pero el test espera que si no puede adquirir el lock inmediatamente, simplemente continúe.
Creo que esta bien implementada mi función pero aun así sigue apareciendo el error.
¿Alguien sabe que puedo hacer?

**Comment by Hernan4444** [comment]
Hola @isawilhelmy 

Podrías pushear tu código para que el cuerpo docente pueda verlo y poder dar más guia.

Quedamos atentos!
Saludos!
