### ISSUE TITLE
comentario no respondido en issue #270

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#453]
Hola pregunte hace dos dias por la issue #270 y aun no tengo respuesta, asi que lo hago por aqui.
Una duda, hay que comparar el valor del random con el valor de la probabilidad saliente de la funcion min, pero mi pregunta es: si el valor del random es mayor al resultado de min, entonces el evento no ocurre? y si es menor, entonces ocurre?

**Comment by JosefaPaz** [comment]
Hola @Juampisaez ,

Disculpa la demora 😞 Tu pregunta se encuentra respondida en la issue #325 ! (spoiler: si el random es un valor menor al de tu probabilidad, el evento ocurre)

Saludos! 😄
