### ISSUE TITLE
Duda sobre salir del juego

### ISSUE THREAD

**Issue by etoteiza** [IIC2233/syllabus#453]
Hola!
Tengo una pequeña duda sobre cómo salir. Basta con ocultar todas las ventanas (y python queda abierto) o se debe salir explícitamente de python

Saludos!

**Comment by aljara97** [comment]
Hola, como no se especifica en el enunciado esto queda totalmente a tu criterio. Te recomiendo especificar la forma que escogerás, ya sea volver a la ventana de inicio, esconder las ventanas o terminar el programa, en tu readme y citar esta issue.

Suerte 🌱
