### ISSUE TITLE
¿Es total la revision del test: "run_public_tests.py"?

### ISSUE THREAD

**Issue by mardrouilly** [IIC2233/Syllabus#453]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/396)).
* [ X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/395)).
* [ X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Buenas tardes, quería consultar con respecto a la revisión y exclusión completa de las funciones prohibidas con el test "run_public_tests.py", si este no detecta nada que está incorrecto, entonces ¿los tests que revisarán la tarea tampoco?, quiero asegurarme de que la revisión que hace es exhaustiva y no hay forma de que esté usando algo que no debería si paso correctamente todos los tests públicos. Gracias.

**Comment by victoriaatria** [comment]
Hola @mardrouilly ! Como se mencionó en las issues #405 , #419 y #430, el test de elementos prohibidos (que se corre al correr `run_public_tests.py`) es una versión preliminar de elementos prohibidos que son fácilmente detectables, pero hay otros métodos que también están prohibidos que no son detectados, por lo que se recomienda que preguntes antes de ocupar alguna función que no se diga explícitamente que está permitida. Quedo atenta por si tienes más dudas :)
