### ISSUE TITLE
abrir consultas json (hice issue en lugar respectivo ayer pero aun no respondida)

### ISSUE THREAD

**Issue by mblejeune** [IIC2233/Syllabus#453]
Hola! hice eso de "abrir" en file -> open y abri el archivo consultas.json que esta dentro de la misma carpeta del main, pero al hacerle run al main y realizar todas las consultas, no me funciona :( quizas estoy abriendolo mal porque al hacer open lo unico que hace es lo mismo que cuando yo abro cualquier archivo y me aparece al lado del main así. y al hacer print queries, ya que apreté realizar todas las consultas se imprime una lista vacía por lo que no se cargaron las consultas json :(

Además, se puede usar este for? uso for para ingresar a query especificay luego dentro de esta query ya en el generador hago: for el in result: self.addanswer(el.atributo) (esto es hacer for para cada elemento del generador ) y poniendo separadores de lineas y todo y me funciona, pero queria saber si es legal usar este ultimo for para ingresar a cada elemento de mi generador y añadirlo con self.addanswer, gracias! :)

y es necesario que estas funciones de process query y save sean tambien maximo 15 lineas?

![captura de pantalla 2018-05-04 a la s 23 29 12](https://user-images.githubusercontent.com/37160975/39667623-d687faae-5090-11e8-9b7d-1bc76b0a6caa.png)

edit: agregada pregunta for

**Comment by Hernan4444** [comment]
@mblejeune cuando haces open, te salen las consultas en la interfaz en la ventana izquierda?

Sobre tus dudas de for, recuerda que dispones del for_each que se explicó en la issue #401 con eso deberías ser capaz de hacer lo que quieres. Finalmente sobre el largo de línea no es necesario, aunque ten cuidado de no abusar de eso. En la interfaz solo debería haber llamados a tu librería y luego imprimir en la interfaz el resultado.

**Comment by mblejeune** [comment]
@Hernan4444  nop :( no me aparecen en la interfaz al hacerle open.

Y gracias! implementaré el for each :)
