### ISSUE TITLE
Largo de __init__

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#454]
Hola, tengo un init largo y me muestra una linea azul debajo porque tiene un largo de casi 200 caracteres, como se puede arreglar para que no me quiten puntaje?

````
def __init__(self, name, type, creatures, food, start_sickles, license, magic_level, skill, total_energy, responsibility, special_ability):

````
Este es el codigo!

**Comment by JosefaPaz** [comment]
Hola @CataSudo ,

Para solucionar esto te recomiendo usar args y kwargs, este contenido se encuentra en la semana 1 :) 

Otra solución es separar esto dando enter, de la forma:

```def __init__(self, name, type, creatures, food, start_sickles,``` 
---------------```license, magic_level, skill, total_energy, responsibility, special_ability):```

Avisame!
