### ISSUE TITLE
Duda contenidos semana 12

### ISSUE THREAD

**Issue by Dnpoblete** [IIC2233/syllabus#454]
Hola estaba corriendo los dos primeros códigos de ejemplo que utilizan json en dos computadores diferentes y me salió el siguiente error:

Traceback (most recent call last):
  File "C:/Users/dnpob/OneDrive/Escritorio/ejemplo.py", line 15, in <module>
    sock.connect((server_host, server_port))
OSError: [WinError 10049] La dirección solicitada no es válida en este contexto

Entonces no se si hice algo mal o si me faltó algo y como arreglarlo, porque solo los copie en dos computadores distintos y les puse correr.

**Comment by NevadaStreets** [comment]
¡Hola!

¿Te aseguraste de poner la dirección IP del servidor en esta línea?

![image](https://user-images.githubusercontent.com/5541246/58737228-ca2d9f80-83ce-11e9-94f3-31c483419978.png)

**Comment by Dnpoblete** [comment]
Ahora si me funcionó, no había cachado que al código del servidor también había que ponerle porque no decía escrito. 

Gracias :)
