### ISSUE TITLE
QProgressbar

### ISSUE THREAD

**Issue by cchauriye** [IIC2233/syllabus#454]
Hola!

Tengo un problema con la QProgressbar que aunque cambie su geometría, el ancho nunca cambia y me queda extradelgada (el largo si cambia). Tengo el código igual que compañeros que tienen Windows y en mi Mac no funciona. ¿Es normal?¿Algún tip?

Gracias!

**Comment by gatochico** [comment]
Hola! 

Uso ubuntu y ejecuté tu tarea. Tu barra de progreso se ve en mi pantalla de esta forma:
![image](https://user-images.githubusercontent.com/37161120/66539009-0c918680-eafd-11e9-8ad0-25f141ccfd65.png)
¿Se ve distinto en tu computador? Si se ve como en el pantallazo, no la consideraría 'extradelgada'. Si no se ve así, y consideras que podría dificultar la corrección de tu tarea, podrías indicarlo en tu README y así intentaremos que quien corrija tu tarea utilice windows o ubuntu (:

Quedamos atentos!

**Comment by cchauriye** [comment]
Hola! 

Muchas gracias! La mía se ve distinta (adjunto foto). Lo señalaré en el README. 

Gracias!
![Captura de Pantalla 2019-10-10 a la(s) 08 41 36](https://user-images.githubusercontent.com/31393605/66566139-94e24c80-eb3a-11e9-9812-2341fbb9af41.png)
