### ISSUE TITLE
Repetición de palabras del vocabulario

### ISSUE THREAD

**Issue by dnalfaro** [IIC2233/Syllabus#454]
> Repite 3 veces al menos una de las palabras de su vocabulario.
>
Con esto se refieren a que al menos una palabra de vocabulary.txt se repita exactamente 3 veces o que se repita 3 veces o más?

**Comment by Arcoirisky** [comment]
Esto ya se a preguntado en otra issue O: ¿Por qué no hechas un vistazo a las otras issues? :D

**Comment by dnalfaro** [comment]
Gracias, había olvidado ver las issues cerradas
