### ISSUE TITLE
Uso de excepciones levantadas por python para levantar mis excepciones

### ISSUE THREAD

**Issue by fedetaladriz** [IIC2233/Syllabus#454]
Hola! Puedo levantar alguna de mis excepciones mediante el uso de los levantamientos de las excepciones de python? 
Por ejemplo, si a una función le doy un numero incorrecto de argumentos, python va a levantar TypeError, por lo que podría hacer lo siguiente:
```python
try:
    miFuncion()
except TypeError:
    raise NotFound("Numero de parametros incorrecto")
```

**Comment by Hernan4444** [comment]
@fedetaladriz **esa forma de realizar no es correcta** (puedes hacerlo para evitar que el programa se caiga pero perderás puntaje en uso correcto de excepciones). Una librería levanta excepciones mientras que los usuarios que utilizan la librería son los que "capturan" los errores, recuerda la AC de excepciones.
Por ejemplo, este es un código de la librería `datetime`
```python
def _days_before_month(year, month):
    "year, month -> number of days in year preceeding first day of month."
    if not 1 <= month <= 12:
        raise ValueError('month must be in 1..12', month)
    return _DAYS_BEFORE_MONTH[month] + (month > 2 and _is_leap(year))
```
Como puedes ver, la librería no hace un try de `_DAYS_BEFORE_MONTH`, sino que analiza el input y levanta excepcion, es por eso que la tarae es: "Crear una librería".

Saludos ✌️
