### ISSUE TITLE
Fichaje de deportisas

### ISSUE THREAD

**Issue by ian-fell** [IIC2233/syllabus#454]
Hola! Como debe ser el proceso de fichaje de deportistas? Hay que imprimir todos los deportistas y dejar a elección del jugador cual elegir? O se le debe asignar un deportista aleatorio siempre y cuando exista el dinero para fichar? Lo pregunto porque si lo dejo a disposición del jugador cual elegir, habría que imprimir los 40 y tantos deportistas sin fichar para que elija, lo que puede ser muy feo estéticamente.

**Comment by mmunozmendez** [comment]
Hola! 
Al usar fichar se tienen que mostrar los deportistas disponibles y permitir al jugador seleccionar uno. 
Cómo se impriman depende de como lo definas, así que puedes lograr que no se vea feo 😉

Ánimo con la tarea 🦆
