### ISSUE TITLE
Descuento de Coordinador 

### ISSUE THREAD

**Issue by JoseValencia125** [IIC2233/Syllabus#454]
El enunciado dice:

>  Si decide aplicar el descuento, la nota verá reflejado dicho descuento hasta la siguiente publicacion de notas donde se le quitará el descuento.

¿Al quitar el descuento se traducirá en un cambio en el nivel de confianza? De ser así ¿se le aplicará a la confianza actual? o ¿se volverá al estado antes de la entrega con descuento y se aplicará allí?
Lo pregunto porque, por ejemplo (aplicandole el cambio a la confianza actual), si debido al descuento perdí 1 de confianza y luego con la correccion se me suma 0, quedo de igual manera con menos confianza.

**Comment by flobarrios** [comment]
Hola! se traduce en un cambio en el nivel de confianza actual y puede pasar que quedes con menos confianza que si se hubiese publicado la nota correcta en un primer momento. La idea es que la confianza se calcule en base a todas las notas que se encuentran hasta ese momento (no se hace diferencia si una fue actualizada o no). 
Saludos!
