### ISSUE TITLE
Problemas para descargar los contenidos semanales

### ISSUE THREAD

**Issue by criss-ah** [IIC2233/syllabus#454]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema
Holaa, al momento de intentar descargar el contenido de esta semana me aparece el problema de la imagen y no logro entender qué es para poder arreglarlo.
![Captura de pantalla (91)](https://user-images.githubusercontent.com/80779455/118569996-279c9180-b749-11eb-990c-77a5b325f4d6.png)

**Comment by Juampisaez** [comment]
Hola @criss-ah,
Me da la impresion que probablemente editaste algunos archivos de esta repo. Lo que te recomendaria yo, es guardar los archivos de esta repo en otra parte (suponiendo que has trabajado en ellos). Borres la repo y clonala nuevamente.

Quedo atento :)
