### ISSUE TITLE
test 13 popularidad_mezla_de_ingredientes_carga_datos

### ISSUE THREAD

**Issue by xperseosses** [IIC2233/Syllabus#454]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/Syllabus/issues/420).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, en el test 13 tengo buenos los de correctitud y los de carga de datos también, excepto el test 5 en el cual mi resultado varía mucho con el resultado esperado, no sé si la lógica de mi codigo este mal o el test. (mi código está en el repo)
<img width="1125" alt="Captura de pantalla 2024-10-04 a la(s) 12 49 18 p  m" src="https://github.com/user-attachments/assets/d972da9d-cb7b-409c-ad51-7693d67e375c">

**Comment by SSParzival** [comment]
Hola muy buenas; se revisó el test y efectivamente el resultado esperado es incorrecto, y tú tienes el resultado que es correcto.

A la brevedad se actualizarán los tests para reflejar ello; muchas gracias por hacernos notar el fallo de los tests :)

**Comment by dani-oviedo** [comment]
hola tengo una duda con esto porque a mi igual me tira todo bueno lo demás , pero yo si tengo que el valor que estaba antes, el cual ahora ese test case me tira error porque ahora se supone que el correcto es 111, y no 460. Comentaba para rectificar el resultado.

**Comment by SSParzival** [comment]
Hola muy buenas, el resultado correcto realmente es 111; para encontrar tu error en tu código te recomiendo revisar el último test agregado de correctitud para esta función.
