### ISSUE TITLE
Contenido .gitignore

### ISSUE THREAD

**Issue by bozzimuc** [IIC2233/Syllabus#455]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Buenas tardes

Si a lo largo de mi trabajo creé archivos que no son relevantes para mi entrega (por ejemplo un archivo jupyter donde hice experimentos), debería incluirlos en el .gitignore, o los saco de otra forma?

Muchas gracias

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by ClemoAcevedo** [comment]
Hola @bozzimuc , ese tipo de archivos extras no causan problema. A la hora de evaluar el uso de .gitignore se evaluan dos cosas:
1. que el .gitignore esté bien configurado ignorando los archivos y/o carpetas que se pide que se ignoren en el **enunciado**.
2. Que esos mismos archivos y/o carpetas no se encuentren en la carpeta de la tarea (es decir, que no se hayan subido).

Estrictamente, cualquier otro archivo da igual si es que no interfiere con la corrección de esta. Sin embargo, como buena práctica de uso de .gitignore te recomendaría añadir todo lo que no tenga que ver con la tarea como tu jupyter para que no se suba.

Buena suerte

**Comment by bozzimuc** [comment]
Vale, muchas gracias!

**Comment by josefa00** [comment]
Hola; como subieron nuevos archivos como el de test_elementos_prohibidos estos no estan considerados en el .gitignore del enunciado por lo tanto no lo debo agregar o si?

**Comment by ClemoAcevedo** [comment]
@josefa00 te recomendaría ignorarlo
