### ISSUE TITLE
Popular_genre

### ISSUE THREAD

**Issue by Pipelao** [IIC2233/Syllabus#455]
Hola buenas :)
Tengo una pregunta acerca de popular_genre, ¿qué pasa con las películas que dicen tener como género N/A? 
1. ¿Las debo considerar a la hora de esta consulta o me las salto y sólo considero los otros géneros? 
2. ¿Debo levantar algún error que esté relacionado con que el género sea N/A?
Gracias de ante mano

**Comment by Arcoirisky** [comment]
Hola~ Mira #334 o #355 c:

**Comment by FJavierOss** [comment]
¿No se puede considerar que las peliculas no tienen género?, por ejemplo considerarlas independientes. O sea pensandolo como la vida real hay peliculas que no clasifican en los géneros "comunes".
Y en consideración a esto la Issue 334 y 355 no se si respondan a la pregunta por Pipelao.
Gracias de anticipo

**Comment by ciquezada** [comment]
Hola, yo tengo la misma pregunta (que no es respondida en esas issues), si en popular_genre se piden los generos mas populares, ¿habrá que omitir las peliculas con genero N/A?, me hace sentido que estas peliculas no sean contempladas en esta consulta, pero en caso contrario si debe saltar una excepcion, ¿en caso habrá que hacerlo?, ¿por ejemplo si uno de los 4 generos populares fuese N/A?

**Comment by Hernan4444** [comment]
Hola, no hay la opción de sin género, sino tendríamos que haber explicado que el N/A en los géneros es para independientes. Por lo tanto, si entre las películas que están analizando, alguno de sus géneros es N/A y solicitamos popular_genre, se genera excepción. Si los géneros de todas las películas **que estamos analizando** no son N/A, entonces ahí si se puede entregar una respuesta

**Comment by ciquezada** [comment]
aun no entiendo, porque si popular_genre() busca los 4 mejores generos de entre todas las peliculas, entonces basta con que una no tenga genero para que toda la consulta falle, entonce popular_genre() siempre va a fallar a menos que se le haga un preprocesamiento a las peliculas segun su genero
