### ISSUE TITLE
Realizar más de los 6 tests obligatorios

### ISSUE THREAD

**Issue by caespinoza5** [IIC2233/Syllabus#455]
¿Se pueden realizar más de los 6 tests obligatorios por enunciado? Ya que si debo testear las 4 excepciones, sólo 2 testeos de consultas estarían retornando lo que deberían retornar. Con más consultas queda más claro el testing, a mi parecer.

**Comment by Hernan4444** [comment]
@caespinoza5 si puedes realizar más de 6 test.

Saludos ✌️

**Comment by Sforrego** [comment]
@caespinoza5 no se si entendi bien tu pregunta pero el enunciado dice 

![image](https://user-images.githubusercontent.com/26422390/31317417-31a1f8d2-ac17-11e7-9b38-8664bfe28930.png)

"Todas las excepciones y todas las consultas"
