### ISSUE TITLE
keyPressEvent & keyReleaseEvent

### ISSUE THREAD

**Issue by fernandovegauc** [IIC2233/syllabus#455]
Hola!
tengo un problema con keyPressEvent, estoy tratando de seguir el consejo del enunciado para cuando se aprietan tres teclas simultáneamente. El problema es que por ejemplo si solo hago prints de lo que estoy presionando y lo que estoy dejando de presionar en el keypressevent y en el keyreleaseevent las teclas se "sueltan" aún cuando las tengo presionadas.  ej : en el keyrelease pongo print("hola") y si mantengo presionada una tecla no debería imprimirse hasta que la suelte pero se imprime continuamente, entonces el set se va vaciando y nunca puedo tener el set con más de una tecla. Espero me entiendan mi duda ajajaja

**Comment by Dnpoblete** [comment]
Hola @fernandovegauc la idea de las combinaciones de teclas es que se presionen en ese orden, pero no simultáneamente, si no que una después de la otra sin que se presione una tecla diferente entre medio, porque sino ocurre el problema que tu comentas.

Espero haber respondido tu duda y éxito con la tarea! 😄

**Comment by fernandovegauc** [comment]
Respondiste mi pregunta, muchas gracias !!

**Comment by Dnpoblete** [comment]
De nada :smile:
