### ISSUE TITLE
Atributo > 100

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#455]
Hola!!

¿Al entrenar un deportista importa si el atributo es mayor a 100? ¿O eso no está permitido?

Graciaas :)

**Comment by amparostevens** [comment]
Hola @amahns1 !
En el enunciado se especifica que los atributos __deben__ estar entre __0__ y __100__, por lo tanto debes manejar que su valor no se pase de esos valores.
Éxito con la tarea! ✨

**Comment by amahns1** [comment]
Valee :)

Grande Ampi!
