### ISSUE TITLE
uso de Properties

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#455]
Es obligatorio el uso de properties para obtener el puntaje total en la Tarea?
Pregunto porque no salia su uso como obligatorio en la planilla de asignación de puntaje.

**Comment by Dnpoblete** [comment]
Hola @dsepulveda3 , esta duda fue resuelta en la issue #437, para que la revises y en caso de tener dudas preguntes ahí.

Éxito en la tarea! 😄
