### ISSUE TITLE
Problemas al correr los contenidos

### ISSUE THREAD

**Issue by mjespinoza** [IIC2233/syllabus#455]
Holaa, estoy teniendo problemas al correr los contenidos de la semana, me pasa que cuando hago run a la celda no termina de ejecutar y me aparece un [*] al lado de la celda( de que se sigue ejecutando). Espero sus respuestas, gracias de antemano :)

**Comment by gatochico** [comment]
Hola! Esto es debido a que los códigos relacionados a la materia de esta semana (Como los del _notebook_ de ejemplos) usualmente quedan corriendo de manera indefinida, ya que el servidor debe estar atento constantemente a la información que puede llegar desde el cliente en cualquier momento. 

Es por esto que recomendamos que en vez de ejecutar las celdas directamente en Jupyter, copies y pegues su contenido en dos archivos diferentes (cliente.py y server.py, segun corresponda) y ejecutes ambos desde tu editor favorito para probar su funcionamiento. Así podras aprovechar y entender la materia de esta semana al máximo. 

Saludos!
