### ISSUE TITLE
Semana 7 ejercicio 1.1

### ISSUE THREAD

**Issue by Gjescalante** [IIC2233/syllabus#455]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

**¿Cómo animar el movimiento de un QLabel?**

Hola! Necesito ayuda para saber como mover un label con animación, aún no entiendo como incorporar Qthread al ejercicio. Hasta ahora puedo hacer que el cuadrado aparezca en una posición aleatoria y que cambie al clickearlo. Gracias por su tiempo.

**Comment by tqmbanados** [comment]
Hola! Desde lo más básico, un movimiento animado se logra cuando el QLabel se mueve constantemente una cierta cantidad de pixeles en una cierta dirección. Es decir, si parte en (10,10), y queremos que se mueva a (110, 110), podríamos simplemente usar ```q_label_ejemplo.move(110,110)```. Sin embargo, esto lo movería instantáneamente y no causaría una animación. Para lograr la animación, tenemos que usar timers (busca el QObject QTimer). Lo que queremos, es que el QLabel se mueva una cierta cantidad de pixeles en un tiempo corto, muchas veces. Por ejemplo, que se mueva 3 pixeles cada 0,2 segundos. Si implementamos un timer cuyo fin marca que el QLabel se mueva 3 pixeles, y luego comienza otro QLabel, tendremos una animación simple. Idealmente, esto debería ocurrir dentro de un QThread, pero no es necesario!
Aquí va un ejemplo de posibles métodos de tu QLabel:
```python
def mover_arriba(self):
    x = self.x()
    y = self.y() + 3
    self.move(x, y)

def movimiento_continuo_arriba(self, velocidad):
    # Cada 200 milisegundos, 
    while True:
        QTimer.singleShot(200, self.mover_arriba)
        time.sleep(0,2)
```

Esa es una forma bastante básica pero poco eficiente y útil de hacer que se mueva el QLabel. Te reto a usar lo presentado aquí para formar tu propia manera de hacer que se mueva. Sin embargo, es una respuesta bastante general para una pregunta relativamente general, por lo que espero que encuentres la respuesta a tu duda aquí. Si tienes algo más específico que preguntar, dale nomás!

**nota final**: Insisto denuevo que QTimer es una excelente clase para poner en movimiento QLabels :) En este caso sólo uso el método de la clase ```singleShot```, pero la clase en sí tiene montones de cosas super útiles!
