### ISSUE TITLE
Dudas contenidos semana 12

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#456]
Hola, tengo dos dudas. La primera es que al correr un servidor en mi editor mas de una vez si que el socket se cerrara la segunda vez me decía que el port estaba ocupado, ya que efectivamente no se cerro el socket anterior, como puedo hacer para cerrarlo manualmente? Y lo segundo es que ejecutando este código: 
![Captura](https://user-images.githubusercontent.com/48294819/58756724-507bdb80-84cc-11e9-8b21-26496ed82b1c.PNG)
 me arroja el error: Connection reset by peer, que buscando en internet dice que es que el otro lado cerro la conexión. Entonces en el terminal no me aparecen los mensajes: "Archivo enviado" ni la respuesta del servidor, como soluciono eso?  Muchas gracias

**Comment by entamburini** [comment]
Hola @jalliende!,

El primer error sucede porque el proceso no se cierra del todo en tu computador y tiene el puerto "tomado". Siendo así, depende completamente de tu sistema operativo, prueba buscando "clear especific port [Sistema Operativo]" y quizás te aparezca algo. 

Para el segundo error, me suena harto a que no estás corriendo el servidor :sweat_smile: pero asumo que sí lo haces. En tal caso, puede ser que no estén ocupando el mismo puerto :o 

Espero que te sirva! :D
