### ISSUE TITLE
Modificar name == main

### ISSUE THREAD

**Issue by Sforrego** [IIC2233/Syllabus#456]
Existe algun problema con modificar el if __name__ == '__main__': de main.py,
con el fin de que el programa sea mas claro? 
por ejemplo:
imprimir personas
imprimir tag/caracteristica
imprimir las consultas que se pueden hacer
etc

**Comment by Hernan4444** [comment]
@Sforrego mientras no vayas en contra de las otras restricciones (como editar el main para agregar un método a la interfaz). Si puedes 👍 

Saludos ✌️

**Comment by Sforrego** [comment]
perfect! 

gracias :)
