### ISSUE TITLE
Barra Stats

### ISSUE THREAD

**Issue by fernandovegauc** [IIC2233/syllabus#456]
Hola, puedo hacer la barra de Stats en otra ventana?

**Comment by jeschuwirth** [comment]
Hola @fernandovegauc,

Aunque no hay problema con que la barra de stats esté en otra ventana recomiendo que se encuentre en la misma.

Si la barra está en otra ventana muy oculta o pequeña y le complica bastante al ayudante corregir se podría aplicar descuento de ayudante, pero si lo haces bien no hay problema con que esté en otra.

Suerte!

**Comment by fernandovegauc** [comment]
gracias !
