### ISSUE TITLE
Duda numero de palabras bot

### ISSUE THREAD

**Issue by Mariana-Ortega-del-Rio** [IIC2233/Syllabus#456]
Hola!
Quería saber en la parte del enunciado que dice que una de las características de los comentarios de los bots es que "Tienen entre 6 y 84 palabras". En este caso incluyo las reviews con 6 y 84 palabras? o solo las que están estrictamente "entre" 6 y 84, esto sería las que tienen 7 a 83. Pregunto esto porque cambia el número de reviews sin bots jaja.
Gracias de antemano!!

**Comment by Arcoirisky** [comment]
Queda a tu criterio, pero di cómo lo consideraste en el README :O
