### ISSUE TITLE
AF5 ingredientes infectados

### ISSUE THREAD

**Issue by maurobsp** [IIC2233/syllabus#456]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

hola tengo la duda en el decorador  __ingredientes_infectados()__ parte 1 de la AF5, nos pide revisar si los ingredientes están infectados o no y en caso de estarlos reducimos su cantidad. Mi duda es de enunciado , entiendo que con reducir la cantidad total en 1  me refiero a la (cantidad - 1) o que ej: tenia 10 y si están infectados pasa a 1. y mi otra duda es en el caso de que no me quede de un ingrediente (cantidad = 0), en ese caso no reduzco nada ??

**Comment by igbasly** [comment]
Hola @maurobsp ✌️

Respecto a la primera duda, nos referimos a lo primero que mencionas, `cantidad_actual - 1`.
Con la segunda duda, es un poco más libre, y es válido lo que mencionas, puedes verificar si es que es 0, dejarlo en 0.

Espero que quede claro, éxito en la actividad 🙌
