### ISSUE TITLE
Diagrama de clase: metodo sin return

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#456]
Hola!! Al ver el video de Diagrama de clases que se encuentra en Canvas, pude notar como no explica el caso en donde una funcion no retorne nada, y no sabia que hacer en este caso en mi propio diagrama de clase, pues, tengo muchas funciones que no retornan nada, imprimen cosas, o llaman a otras funciones

**Comment by vWing7** [comment]
Segun entiendo en ese caso es cuando se usa None. Tipo, function(): None

**Comment by Dnpoblete** [comment]
Hola @felipehen, como bien dice @vWing7 tienes que usar None.

Éxito con la tarea! 😄
