### ISSUE TITLE
Problemas en el test 03

### ISSUE THREAD

**Issue by JMCChen** [IIC2233/Syllabus#456]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/Syllabus/issues/420).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Al correr los test de la consulta 03 me aparece un error que no se que significa. Adjunto imagen del error
![image](https://github.com/user-attachments/assets/fe47e9aa-de2d-4bba-a8a4-1f4c16f608fd)

**Comment by NachoRinda** [comment]
Hola, la estructura del error te indica de abajo hacia arriba desde dónde partió el error hasta cuáles procesos se cortaron debido a este. Específicamente, este test te dice que hubo un AssertionError en el llamado a la función AssertionTrue() de la línea 75, y eso acabo con los procesos de arriba ("result[0]" es de una función timeout que evalúa que tu código corra en un tiempo acotado, como saltó error entonces este proceso que cronometra tu código también fue cortado).
Ahora bien, si quieres saber que está haciendo realmente AssertionTrue() puedes ver tu mismo el código de test en tests_publicos/ que es en dónde se encuentran todos.
Entrando en <test_03_pedido_con_mayor_descuento_utilizado_correctitud.py> puedes ver que su estructura es:

    def test_0(self):
        """
        Verifica que el test funcione si es que no hay pedidos con descuentos
        """

        ContenidoPedido = namedtuple(
            "ContenidoPedido", ["id_pedido", "nombre", "cantidad", "descuento"]
        )

        lista_entregada = [....
        ]

        generador_entregado = (pedido for pedido in lista_entregada)

        resultado_estudiante = pedido_con_mayor_descuento_utilizado(generador_entregado)

        **self.assertIsInstance(resultado_estudiante, (Iterable))**

        resultado_estudiante = list(resultado_estudiante)

        resultado_esperado = [...
        ]

        **self.assertTrue(
            all(elem in resultado_estudiante for elem in resultado_esperado)
        )**

Los assertion son las pruebas que se le hace a tu código para comprobar que funcione bien y verifican exactamente lo que dice su nombre. Por ejemplo, AssertIsInstance verifica que de los argumentos que le entregas uno sea instancia del otro (en este caso que tu retorno de la función sea **Iterable**).
Por otro lado, AssertTrue verifica que lo que le entregas sea lógicamente verdad (True). En particular, el test le entrega **all(elem in resultado_estudiante for elem in resultado_esperado**), esto lo que hace es verificar que **todo elemento que entregue de la solución esperada se encuentra también en el retorno que entrega tu función.**
Cómo es falso, significa que no todos los elementos de la solución están en tu iterable retornado.
Si tienes más dudas o no te quedo claro no dudes en volver a preguntar por acá mismo.

**Comment by DiegoRODestudiante** [comment]
Y qué pasa si estoy seguro de que si los está devolviendo pero me sigue saliendo false? Por lógica del código que hice es evidente que si considera todos pero sigue saliendo que false is not true

**Comment by NachoRinda** [comment]
Si estás seguro de que sigues la lógica que tienes en mente, tal vez tu problema sea que entendiste mal el enunciado. Tampoco has subido nada a tu repositorio por lo que no puedo ver lo que llevas hecho como para ayudarte.

**Comment by DiegoRODestudiante** [comment]
Pero se supone que tiene que ser un iterable con los que tengan el mayor descuento no? En caso de ser uno solo o en caso de ser más de uno se siguen retornando en el iterable, ya pushee por cierto

**Comment by NachoRinda** [comment]
Entendiste bien el enunciado, tu problema es que estás usando el generador **más de una vez**, por lo tanto, después de su primer uso se consume y terminas retornando un iterable vacío.

**Comment by DiegoRODestudiante** [comment]
No entiendo como sacar el máximo sin usar dos veces el generador, lo intente infinitas formas pero siempre terminaba usando 2 porque las otras no funcionan, porque no puedo comparar los descuentos sin tener el máximo, y para sacar el máximo tenia que sacar los descuentos sí o sí
