### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by barbarafcp** [IIC2233/syllabus#456]
Hola! yo no estoy incluida en el discord del ramo, y no encontraba los mails de los ayudantes, y ahora se me ocurrió preguntar por acá si me podían agregar o algo, mi usuario es barbarafcp#5280

**Comment by lily416** [comment]
Hola @barbarafcp, 

Acá te dejo el [enlace de invitación](https://discord.gg/wuArKXg) al canal de Discord siguiente enlace. Te recomiendo que revises el [Tutorial de Discord Actividad Remota](https://github.com/IIC2233/syllabus/blob/master/Archivos%20Importantes/Tutorial%20Discord%20AC%20Remota.pdf), ya que ahí se explica cómo funcionan los distintos canales del servidor.

Saludos y que tengas una buena semana 👋👾
