### ISSUE TITLE
Duda sobre el retorno de distrito_mas_votos_especie_bisiesto en caso de no haber animales

### ISSUE THREAD

**Issue by FelipeFuentesG** [IIC2233/Syllabus#456]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Tengo una duda sobre el enunciado en la parte de la consulta de distrito_mas_votos_especie_bisiesto. Al final dice que en caso de no haber algún animal que cumpla con lo indicado se debe retornar el distrito con menor id. ¿Qué significa eso? Es decir, si no hubiese animales que nacen en año bisiesto y son de la especie solicitada, ¿entonces solamente debo retornar el str de la menor id del total de distritos?

**Comment by SSParzival** [comment]
Hola buenas, en ese caso que mencionas, se debe retornar el str normal de la función, pero usando el id del distrito con menor id. En el caso que el menor id fuera 1 y la especie fuera Tortuga, debería retornarse lo siguiente:

`El distrito 1 fue el que tuvo más votos emitidos por animales de la especie Tortuga nacidos en año bisiesto.`

Ese caso borde lo evalúa precisamente el `test_5` del archivo `test_22_distrito_mas_votos_especie_bisiesto.py`.

**Comment by FelipeFuentesG** [comment]
Ah perfecto, muchas gracias!
