### ISSUE TITLE
Nuevo enunciado

### ISSUE THREAD

**Issue by negutierrez** [IIC2233/Syllabus#456]
Hola, llegó un mail diciendo que habían subido un enunciado, pero revisé el que subieron y creo que hay un error ya que es exactamente el mismo... de hecho tiene la misma fecha de entrega para el diagrama de eventos (11 de mayo), quizás se les pasó el otro archivo :) 
saludos!

**Comment by flobarrios** [comment]
Hola! se me pasó cambiar la fecha de entrega 🙈  pero no es el mismo archivo. Hay cambios pequeños y por eso en el mail detallamos que había cambiado para que no tengan que encontrar por  su cuenta los cambios.

Saludos!

**Comment by negutierrez** [comment]
Ok perfecto, gracias!
