### ISSUE TITLE
Duda sobre el decorador de desencriptar receta

### ISSUE THREAD

**Issue by 0DASAC** [IIC2233/syllabus#457]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola tengo una duda sobre el decorador de desencriptar receta ya que para implementarlo hay que llamar a la funcion desencriptar pero esta necesita una palabra clave y no se cual es la palabra que hay que usar.

**Comment by 0DASAC** [comment]
ya entendi que la palabra que me pide es la que se desencripta (pensé que era ya llave de encriptación o algo así)

**Comment by igbasly** [comment]
Eso mismo 🙌
