### ISSUE TITLE
popular_movie o popular_movies

### ISSUE THREAD

**Issue by beayancan** [IIC2233/Syllabus#457]
Una de las consultas que debemos implementar es **"popular_movies"**, la cual entrega **todas las peliculas** con ciertas caracteristicas. Sin embargo, en las consultas de ejemplo que se entregan en el enunciado son
* [**"popular_movie"**, ["load_database"], 1, 100, "Rotten Tomatoes"]
* [**"popular_movie"**, ["load_database"], 50, 100]

¿Debo entender que los ejemplos tienen errores de tipeo o de igual forma hay que aceptar la consulta con este nombre?

**Comment by Hernan4444** [comment]
@beayancan fue un error de tipeo, debe ser como se llama la consulta. popular_movies. 

Saludos ✌️

**Comment by beayancan** [comment]
Perfecto, gracias.
