### ISSUE TITLE
Duda sobre test_05_pares_de_candidatos

### ISSUE THREAD

**Issue by milaph** [IIC2233/Syllabus#457]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Estaba corriendo el test_05 y me lanza los siguientes errores:
test_5 (__main__.TestParesCandidatos.test_5)

         Verifica que se retorne los votantes cuando se manejan pequeños datos.
         ... FAIL
test_6 (__main__.TestParesCandidatos.test_6)

        Verifica que se retorne los votantes cuando se manejan medianos datos.
         ... FAIL
test_7 (__main__.TestParesCandidatos.test_7)

        Verifica que se retorne los votantes cuando se manejan grandes datos.
         ... FAIL

y no entiendo bien a que se refiere,  luego, al ver  los detalles me dice que los elementos contados no son iguales. Use combinaciones(). d ella biblioteca itertools  para programar esta función. ¿Alguien sabe que puede estar ocurriendo?

**Comment by ngulloa** [comment]
¿Lograste resolver tu problema? Tuve el mismo, me gustaría saber por qué fue
