### ISSUE TITLE
Correción avance tarea01

### ISSUE THREAD

**Issue by jg-tuna** [IIC2233/syllabus#457]
Hola 😺 !!
estaba revisando lo que fue la corrección del avance de la tarea me dicen que no hay una demostración de la relación entre el alimento y el magizoólogo. siendo que señalice esto en el diagrama (y en la explicación que se encuentra en el mismo pdf)

**Comment by entamburini** [comment]
Hola @jg-tuna!,

Te recuerdo que las issues son una instancia de dudas generales y relacionadas a código. Esta duda que tienes es de carácter personal, debido a que es de una corrección. Para recorrecciones del avance se habilitará un form al momento de que se publiquen las notas de la tarea para que ahí pongas tus comentarios al respecto :wink:.

Saludos! :v:

**Comment by jg-tuna** [comment]
Hola @entamburini!
Lo siento por haberlo mandado como issue, no volverá a ocurrir.
