### ISSUE TITLE
Cambiar tipo de atributo medallas de Delegación

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2233/syllabus#457]
Hola, 
quería saber si puedo cambiar el tipo de atributo medallas en delegaciones por un lista (en vez de un int) donde estén la medallas de cada competencia en vez del total de medallas, ya que me es mas útil en este formato. De no ser así puedo crear mas atributos en delegación cierto?

**Comment by amparostevens** [comment]
Hola @antoniaalcayaga !

Para ser consistentes con el enunciado, __debe ser un int__. Pero ya que deseas trabajar con listas, puedes crearla y utilizarla para lo que necesites y que el atributo medallas tome el valor del largo de tu lista :raised_hands: y así tienes lo mejor de dos mundos sin contradecir el enunciado! 

Y sí, siempre puedes crear más atributos y métodos siempre que no contradigan el enunciado.
