### ISSUE TITLE
Dudas context manager para sockets

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2233/syllabus#457]
En la ayudantía se habló de usar excepciones para garantizar que el socket se cierre adecuadamente. Hay una forma de crear un context manager para lo mismo? Es decir, se puede crear una clase que herede de socket y que tenga definido ```__enter__``` y ```__exit__```?

**Comment by entamburini** [comment]
Hola @JJJGGGG !

En verdad es una buena pregunta, luego de googlear un poco me dí cuenta que en efecto no existe algo de ese estilo para networking u.u

Peeeeero estamos en Python! :open_mouth: y eso significa que en efecto **sí** se puede  crear uno gracias a las facilidades del idioma jejeje

Para eso simplemente tienes que definir una clase que te sirva para el _context manager_, es decir, que tenga los métodos dichos por ti `__enter__` y `__exit__`. En el primero debes retornar lo que normalmente se pone como _as_ en los _context manager_ (como cuando estás leyendo un archivo y pones `as file` al final del `with`. En el método `__exit__` simplemente cierras lo que abres.

```python
class NetworkManager:
    def __init__(self, ip='v4', connection='tcp'):
        self.ip = socket.AF_INET
        if ip == 'v6':
            self.ip = socket.AF_INET6

        self.connection = socket.SOCK_STREAM
        if connection == 'udp':
            self.connection = socket.SOCK_DGRAM

    def __enter__(self):
        self.socket = socket.socket(self.ip, self.connection)
        return self.socket

    def __exit__(self, *args):
        self.socket.close()
```
En este ejemplo, hice un _context manager_ muy sencillo con valores por defecto que se pueden modificar (hay formas más limpias y seguras de hacerlo, pero encuentro que es suficientemente entendible c:). Aquí sólamente se crea un socket y es lo que devuelvo al usuario que quiere utilizar este _context manager_.

Entonces, con el ejemplo de cliente TCP que hay en el material, en vez de crear un `socket`, hacer las cosas y cerrarlo, puedo llamar a mi creación >:)

```python
with NetworkManager() as sockete:
    # Obtenemos el nombre de la máquina a la que nos queremos conectar.
    # En este caso, nos queremos conectar a esta misma máquina.
    host = socket.gethostname()
    port = 9000

    sockete.connect((host, port))
    data = sockete.recv(4096)
    print(data.decode("ascii"))
```

Esto es sólo un ejemplo, siéntete libre de usarlo si quieres :smile: para más información, yo me basé en lo que salía en este [link](https://stackabuse.com/python-context-managers/). Espero que te haya servido :D
