### ISSUE TITLE
[T04] - Eventos no programados 6.1

### ISSUE THREAD

**Issue by malopez16** [IIC2233/Syllabus#457]
Hola!
En el punto 6.1, que se hace referencia a los eventos no programados, en partido de futbol se señala que ese día no dedicarán tiempo al ramo. Esto significa que se reagendará el tiempo para desarrollar la tarea (por ejemplo) en el resto de la semana, o que simplemente esas horas simplemente se perdieron? 
En cuanto al corte de agua, cada profesor recibirá a máximo 6 personas por semana o los 3 profesores recibirán a 6 en total?

Gracias :)

**Comment by Dunkan1** [comment]
yo creo que se pierde(cualquier cosa al README)
y no son 10 personas por profesor?
![captureasdf](https://cloud.githubusercontent.com/assets/26102365/25873366/9ee7005e-34e4-11e7-8942-34f387e7b077.PNG)

**Comment by rmsolari** [comment]
Hola, se pierden las horas no dedicadas al ramo. En el corte de agua cada profesor recibe a 6 alumnos,  en semanas sin cortes de agua se reciben como máximo 10 alumnos por cada uno.

**Comment by malopez16** [comment]
Gracias!
