### ISSUE TITLE
GenomeError para genes no seleccionados

### ISSUE THREAD

**Issue by Fhguinez** [IIC2233/Syllabus#457]
Por issues pasadas, entiendo que GenomeError debe levantarse cuando al hacer la consulta nos topemos con un error en el genoma. Entonces, qué pasa si una parte del genoma es:
ATCGATAG-TCGACTAGACGCTAGACT (con un error en el guión)
Y al seleccionar los genes relevantes, según listas.txt, me quedan combinaciones como las siguientes para todas las características:
ATC [GAT] AG_TCG [ACT] AGA [CGC] TAGACT
[ATC] [GAT] AG_TCGACTAGACGC [TAG] ACT
Donde la tripleta con error nunca es seleccionada.

¿Corresponde levantar error en este caso? ¿O el error queda como 'ignorado'?
En caso de que corresponda, ¿en qué momento levanto el error? Porque si bien este está presente en el genoma, no tiene relación con ninguna característica.

**Comment by Hernan4444** [comment]
En ese caso no se levantaría nunca el error. Lo "ignoramos",
Saludos
