### ISSUE TITLE
entrenamiento lesionados y acciones rival

### ISSUE THREAD

**Issue by eliasbruchfeld** [IIC2233/syllabus#458]
Hola! Obviamente un lesionado no puede competir pero podría entrenarlo igual? En el enunciado no se especifica pero no se si hace sentido que si.

Y otra cosa, el rival puede fichar y entrenar a sus deportistas?

**Comment by itmunoz** [comment]
Hola! Como no aparece indicado en el enunciado, queda a tu criterio permitir si un deportista lesionado puede o no entrenar.
Por otro lado, en el ítem 3.2.2 del enunciado se dice que "queda a tu criterio decidir si la delegación rival usa o no sus días de entrenamiento fichando deportistas, sanándolos ó entrenándolos."
