### ISSUE TITLE
Problema al encontrar Designer

### ISSUE THREAD

**Issue by santandergc** [IIC2233/syllabus#458]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### 

No puedo encontrar designer, use la ruta que me entregan y tampoco. Esta es la ruta que tengo (C:\Users\Cristobal\AppData\Local\Programs\Python\Python37\Lib\site-packages\pyqt5_tools) pero aún así no aparece designer.exe. A diferencia de la ruta que me entregan, yo tengo pyqt5_tools con un guion bajo, no se si sea un problema.

![1](https://user-images.githubusercontent.com/80907322/119056439-b2bf9680-b998-11eb-856e-5356901ba7e3.PNG)

dentro de  pyqt5_tools

![2](https://user-images.githubusercontent.com/80907322/119056486-c4a13980-b998-11eb-8fe3-3df435ef5003.PNG)

**Comment by Juampisaez** [comment]
Hola @santandergc 
A mi hace un tiempo me paso lo mismo que a ti, habia instalado todo por consola y no me aparecio la aplicacion. Lo que hice despues fue instalarlo directamente desde la [pagina web](https://build-system.fman.io/qt-designer-download), prueba con eso.

Quedo atento por si tienes mas problemas :)

**Comment by dammr54** [comment]
busca una carpeta mas abajo llamada "qt5_applications" luego abre Qt y luego bin ahí debería aparecer la aplicación de designer
C:\Users\diego\AppData\Local\Programs\Python\Python37\Lib\site-packages\qt5_applications\Qt\bin
Esa es la dirección en mi pc
