### ISSUE TITLE
Parámetros.csv

### ISSUE THREAD

**Issue by JMOrellana** [IIC2233/Syllabus#458]
Hola a todos! 

Con respecto a este archivo no me queda claro el criterio para determinar la cantidad de profesores, ayudantes y alumnos. Es decir, ¿nosotros podemos generar un archivo parametros.csv con menor cantidad de profesores, ayudantes y alumnos que los dados en el archivo integrantes.csv?

De ser correcto lo anterior, ¿La cantidad de profesores, ayudantes y alumnos será distintas para cada escenario dado en el archivo escenarios.csv?

De antemano muchas gracias!

**Comment by flobarrios** [comment]
Hola! No debes definir la cantidad de profesores, ayudantes y alumnos en el archivo parametros.csv. Estos quedan definidos en el archivo integrantes.csv y el numero va a depender unicamente de lo que este en este archivo.

Saludos!!

**Comment by fcgfaura** [comment]
Entonces qué se define en parámetros.csv ??

**Comment by Hernan4444** [comment]
@fcgfaura en `parametros.csv` deben ingresar todo dato que está en el enunciado (como las tablas de notas esperadas, la dificultad por contenido, etc) de este modo podemos editar esos datos y ver que pasa en la simulación.

Saludos!

**Comment by akaminetzkyp** [comment]
Hola!

El enunciado dice esto con respecto a `parametros.csv`:

> Además, deberá crear un archivo parámetros.csv con la cantidad de profesores, la cantidad de ayudantes y una cantidad de alumnos.

Yo entendí que debemos crear el archivo `parametros.csv` con el siguiente formato:

| Rol:string  | Cantidad:int |
| --- | --- |
| Profesores  | 3  |
| Ayudantes  | 1  |
| Alumnos  | 4  |

Saludos!

**Comment by Hernan4444** [comment]
@akaminetzkyp eso se cambió (y prontamente lo cambiaremos en el enunciado). Estos quedan definidos en el archivo integrantes.csv y el numero va a depender únicamente de lo que este en este archivo. Tal como dije antes, parametros.csv será un archivo que almacenará todas las constantes que nosotros les dimos, es decir, tablas, probabilidades, nota esperada, etc.

Saludos!

**Comment by akaminetzkyp** [comment]
¿O sea `parametros.csv` será similar a `escenarios.csv`?

Saludos!

**Comment by Hernan4444** [comment]
@akaminetzkyp exactamente, solo que no hay diferentes escenarios y llevará todas las constantes definidas en todo el enunciado

**Comment by akaminetzkyp** [comment]
Perfecto, gracias!

**Comment by FernandoPieressa** [comment]
El enunciado fue modificado para reflejar estos cambios.

Saludos!

**Comment by JMOrellana** [comment]
Puedo crear más de un archivo de parámetros? Por ejemplo, crear la tabla de contenidos y nota esperada en un archivo csv y los demás parámetros en otro archivo csv.

Saludos!

**Comment by Hernan4444** [comment]
@JMOrellana si puedes c:
Saludos!!

**Comment by akaminetzkyp** [comment]
Quisiera confirmar que entendí bien como funciona el archivo `parametros.csv`. Este archivo debe ser creado por nosotros manualmente para poder ser leído por nuestro programa. ¿Así es?

Saludos!

**Comment by iqacevedo** [comment]
@akaminetzkyp así es ! 

Saludos !

**Comment by akaminetzkyp** [comment]
Perfecto, gracias!

**Comment by asdegoyeneche** [comment]
@Hernan4444 Me gustaría confirmar: En el archivo de parámetros deben estar _todas todas todas_ las constantes del enunciado?

¿Esto incluiría, por ejemplo, tanto el porcentaje de aumento de nivel de programación al visitar a un profesor, como la cantidad de alumnos que recibiría el profesor en caso normal y en caso de corte de agua, como también a partir de que nota y con que probabilidad decide visitar el alumno al profesor? ¿Incluiría también la cantidad de dudas que puede hacer un alumno (entre 1 y 10 por default) a ayudante en una actividad, y el máximo de preguntas a contestar por el ayudante (default 200)? También: intervalo de cantidad de días de retraso del malvado Dr. Mavrakis y probabilidad de esto, cantidad de descuento y cantidad máxima de veces por semestre. Etc. 

Al final mi pregunta se traduce a: cualquier valor numérico, ponderador, cantidad, número en formula del enunciado debe ser obtenido de `parametros.csv`? (Claramente que las tareas sean cada 14 días y ayudantías y actividades cada 7 no entraría en esto, pero quizás la cantidad de días después de la ultima nota para el día del examen sí podría hacerse variar). Creo que varía la dificultad/tiempo de la tarea, por lo prefiero preguntar.

Gracias de antemano!

**Comment by Hernan4444** [comment]
Tal como dices, van todas todas las constantes del enunciado (tablas, probabilidades).  Pero las constantes de las formulas puedes omitirlas.

**Comment by akaminetzkyp** [comment]
Hola!

¿Podemos no incluir en `parametros.csv` valores como cantidad máxima de controles, número de preguntas que tiene el examen, cantidad de contenidos que domina un ayudante, moda de la distribución triangular? Además, ¿podemos no incluir los intervalos de los `random` en las fórmulas?

Saludos!

**Comment by asdegoyeneche** [comment]
Ok, gracias!

**Comment by consuvalencia** [comment]
@Hernan4444 qué pasa si ya había considerado lo que decía en el 'antiguo' enunciado:
'Además, deberá crear un archivo parámetros.csv con la cantidad de profesores, la cantidad de ayudantes y una cantidad de alumnos.'
Es bastante diferente de lo que se pide ahora, pues al ingresar todos estos datos como input, cambiarían varias cosas en mi código (no aumenta la dificultad pero es harto el tiempo que tendría que invertir en hacer este cambio).
Considero que, dado que este cambio se hizo hace menos de un día, no debería considerarse como obligatorio. Quedo atenta al veredicto.

saludos!

**Comment by Hernan4444** [comment]
Al final se discutió y en el archivo parametros.csv deberá tener al menos 15 de las constantes que tiene el enunciado. Queda a su criterio cuales parámetros dejar mientras sean mínimo 15. Por otro lado, cada fila de una tabla se considera una constante, si una tabla tiene 5 filas...entonces ya tienen 5 constantes (no importa la cantidad de columnas). La idea de esto es poder ver como organizan la información.

Por otro lado, como sugerencia pueden crear un parser que lea su propio csv de parámetros (recordar que es **su** archivo así que tiene el formato que ustedes le dan) y genere un diccionario con las constantes. Luego las demás clases acceden a ese diccionario para buscar los parámetros que necesitan.

Saludos!

**Comment by consuvalencia** [comment]
Perfecto! Cuentan como parámetros los que se dan en escenarios verdad? (son 11)

**Comment by Hernan4444** [comment]
@consuvalencia si, cuentan como parámetros, mientras en ese archivo esté el valor por defecto, no el de algún escenario.

Saludos!

**Comment by AmbrosioV** [comment]
> Puedo crear más de un archivo de parámetros? Por ejemplo, crear la tabla de contenidos y nota esperada en un archivo csv y los demás parámetros en otro archivo csv.

Respecto a eso, le pongo el nombre que quiera al archivo, con tal de poder distinguirlos mejor y no ponerle parametroN a cada uno
sl3

**Comment by iqacevedo** [comment]
@AmbrosioV justamente, pero debería ser un nombre intuitivo para que pueda ser fácilmente reconocible, debes dejarlo bien especificado en tu README.

Saludos !
