### ISSUE TITLE
Duda tamaño de tests evaluados

### ISSUE THREAD

**Issue by Igufu** [IIC2233/Syllabus#458]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/Syllabus/issues/420).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

¡Saludos!, tengo una duda respecto al tamaño de los archivos que procesaremos en la evaluación real, ¿estos serán de tamaño similar a los que tenemos en `data/` o serán de un tamaño más grande (eg: >1gb)?, o es algo <em>**secreto**. :eyes:</em>

¡Gracias :)!

**Comment by SSParzival** [comment]
Hola muy buenas, aunque sea poco interesante que contar (ya desearía que fuera secreto), la realidad es que el tamaño de los datos de los tests privados serán virtualmente iguales que el tamaños de los datos de los tests públicos; por lo cual, si no tienes problemas de tiempo con los tests de carga públicos, para los privados no deberías tener problemas.
