### ISSUE TITLE
Problema con ejecución "Cachipun"

### ISSUE THREAD

**Issue by JoacoCoyu** [IIC2233/syllabus#458]
![prob 1](https://user-images.githubusercontent.com/48266376/58973241-7a175a00-878d-11e9-930e-0c93a1666bb6.PNG)
![prob 2](https://user-images.githubusercontent.com/48266376/58973252-7e437780-878d-11e9-9b54-6e7dded2f673.PNG)

Hola! Cuando intento correr el ejercicio de la ayudantía de "cachipun" me aparecen los siguientes errores. Revisé que el interprete no estuviera en modo "venv" pero aun si me sale esto. Es muy raro que al importar las clases de los otros módulos igual me salga en rojo.

Gracias!

**Comment by entamburini** [comment]
Hola! 

Te daré un set de preguntas, ojalá que encontremos la razón :)

- Esto te sucede cuando corres el programa en la consola?
- A pesar de que dices que no estás corriendo en venv veo en la primera foto que si lo estás haciendo :/ 
- Puede suceder esto cuando hay una instalación de 32 bits de python y correrlo en pycharm instalado en 64 bits, puedes revisarlo?
- Trata actualizando Windows si el resto de cosas no funciona :)
