### ISSUE TITLE
actualizar QLabel

### ISSUE THREAD

**Issue by mpsubiabre** [IIC2233/syllabus#458]
Hola, tengo el problema de que cada vez que le llega una señal a una funcion deberia actualzar un QLabel, mediante el uso de .setText, sin embargo ocurre que a pesar de que llega la señal y que python lea el codigo, solo cambia el QLabel a la primera lectura del setText, luego cuando le llega la segunda lectura del setText no lo actualiza, y asi sucesivamente. No logro entender porque pasa esto.
Gracias

**Comment by mpsubiabre** [comment]
lo resolví escondiendo el QLabel anterior y sobreponiendo uno nuevo, en vez de usar el setText

**Comment by jeschuwirth** [comment]
Felicidades por resolver el problema y publicar la solución en el foro, es un muy buen uso de Github.

De todos modos te recomiendo mirar el siguiente link para evitarte problemas con la tarea https://stackoverflow.com/questions/22715564/how-can-i-set-text-of-label-when-a-function-is-running

Suerte!
