### ISSUE TITLE
popular_actors output

### ISSUE THREAD

**Issue by diegoheg** [IIC2233/Syllabus#458]
Tengo la duda de si el string que va en la lista output de la función popular_actors contiene solo las películas del actor que están dentro del generador entregado en principio o si son todas las películas del actor

**Comment by Hernan4444** [comment]
@diegoheg son las películas que están dentro del generador. 

Porque imagina que partes con 5 películas y filtras para tener solo 2 y ahí pides el popular_actors de esas 2 películas, en estricto rigor no hay forma de saber cuales son las demás películas de esos actores sin tener que volver a abrir el archivo, pero eso es algo que ninguna consulta hace (reabrir la base de datos original), sino que funcionan a partir de la base de datos de películas que les llega.

**Comment by emeiese** [comment]
Yo tengo otra duda al respecto: Por ejemplo, si utilizo el mini database como generador inicial, 9 actores , de las 3 películas más populaes e IMDb, el output que me entrega mi función popular_actors es el siguiente:
`{'Diego Quezada': ['9'], 'Sebastián Guerra': ['6'], 'Sebastian Orrego': ['9'], 'Leonardo Olivares': ['6'], 'José Pablo Domínguez': ['9'], 'N/A': ['2'], 'Fernando Pieressa': ['6'], 'Tien Villalobos': ['9'], 'Enzo Tamburini': ['6']}`
(imaginaque no apaece N/A, que ya sabemos que debería tirar error jiji )
donde las películas más populaes son 6,2 y 9. Ese es el output correcto? O debería retornar todas las películas del generador inicial en el que aparecen los actores? Es decir:
`{'Diego Quezada': ['3', '5', '9', '11'], 'Sebastián Guerra': ['6', '14'], 'Sebastian Orrego': ['9', '15'], 'Leonardo Olivares': ['6', '13'], 'José Pablo Domínguez': ['9', '18'], 'N/A': ['2'], 'Fernando Pieressa': ['6', '8', '13'], 'Tien Villalobos': ['5', '9'], 'Enzo Tamburini': ['0', '6']}`

**Comment by Hernan4444** [comment]
Con lo primero está bien, porque esa consulta incluye un filtro para reducir el tamaño de la base de datos que te llega y por ello, es normal que primero saques las películas que no sirvan para luego encontrar los actores.  

Lo que estaría mal es Diego Quezada': ['9, 90], haciendo el supuesto que la película 90 era alguna con una fecha que filtraste en otra consulta anidada.
