### ISSUE TITLE
Habilidad especial DCCrotona

### ISSUE THREAD

**Issue by JoMarchant** [IIC2233/syllabus#459]
En el enunciado se especifica que al usarse se obtienen todos los beneficios de haber ganado una medalla pero, ¿qué ocurre con el bono de moral que se da al deportista ganador?.
¿Se le entrega a todo el equipo o a un deportista del equipo al azar?, ¿o no se entrega ese bono simplemente?

**Comment by baosse** [comment]
Holaa @JoMarchant !
Se le debe entregar a un deportista al azar. De todas maneras se profundiza más acerca de esto en la issue #374 .
Espero que esto te sirva! Mucho éxito con tu tarea✨
