### ISSUE TITLE
AF5 decorador capa_relleno()

### ISSUE THREAD

**Issue by maurobsp** [IIC2233/syllabus#459]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

hola tengo una duda en el decorador __capa_relleno()__ del archivo decoradores_cocinero.py.
Se menciona en el enunciado que en el caso de que no quede relleno se debe imprimir un mensaje y terminar la torta sin agregar otra capa de relleno. Mi duda es que si no nos queda relleno debemos cambiar el estado de la torta torta.finalizada = True ?  o solo no ponemos rellenos pero de todas formas se ponen capas de ingredientes en esta hasta que se pongan todos los ingredientes.

**Comment by igbasly** [comment]
Hola @maurobsp 

En este decorador nos referimos a "terminar la torta" precisamente a cambiar el atributo de la torta `finalizada` como `true`.
Ahora, para evitar errores recomiendo entender bien cómo funciona la función original `agregar_topping` 😉.

Saludos!

**Comment by IgnAMS** [comment]
Hola, respecto a este mismo tema en `agregar_topping` ya viene incluido el cambiar la `torta.finalizada` a `True` en caso de que no queden ingredientes disponibles. También en la función se verifica que queden ingredientes e incluye los prints pedidos. Me cuesta un poco ver el sentido de este decorador.

**Comment by igbasly** [comment]
Hola @IgnAMS, efectivamente `agregar_toppings` termina la torta cuando no quedan ingredientes, pero esto aplica únicamente al ingrediente que se está agregando que corresponde a un _topping_. En cambio, con el decorador estamos verificando que quede el relleno que se va a agregar entre los _toppings_, se entiende la diferencia??

Cualquier cosa quedo atento 😉

**Comment by IgnAMS** [comment]
Siiii, ¡Muchas gracias! 😃
