### ISSUE TITLE
Contenidos actividad recuperativa

### ISSUE THREAD

**Issue by jearaneda** [IIC2233/syllabus#459]
Hola, revisé los semestres anteriores y al parecer nunca se ha hecho actividades recuperativas, se tiene una idea de qué enfoque tendrá esta? Sé que tiene un "carácter integrador", pero no sé qué significa exactamente eso como para estudiarlo desde ahora

a) Integra todas las actividades **sumativas**
b) Integra **toda la materia** del curso 
c) tareas + sumativas 

u otras alternativas, gracias

**Comment by mnbenimeli** [comment]
Cuando le pregunté al profe me dijo que aún estaban viendo por esa misma razón

**Comment by fdoflorenzano** [comment]
Hola @jearaneda,

La AC recuperativa tendrá carácter integrador sobre varios de los contenidos del curso. En específico, se considerarán los tópicos cubiertos por actividad es sumativas y por algunas actividades formativas. 

Específicamente, se considerarán para esta actividad la siguiente lista de contenidos:
- Semana 01: Estructuras de datos built-in.
- Semana 02: Programación Orientada a Objetos
- Semana 06: Estructuras de datos nodales (parte 2): Grafos.
- Semana 07: Excepciones
- Semana 08: Threading
- Semana 09: Paths, I/O y serialización.

Enviaremos pronto detalles sobre la hora y duración de la actividad.

Saludos y éxito con el estudio.
