### ISSUE TITLE
Duda sobre interpretación error de un test votos_interespecie()

### ISSUE THREAD

**Issue by trinicamposl** [IIC2233/Syllabus#459]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* `"[X]"` Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* `"[X]"` Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* `"[X]"` Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* `"[X]"` Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* `"[X]"` Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* `"[X]"` Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* `"[X]"` De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

No entiendo bien cómo interpretar el error que se muestra a continuación ya que en esta función nunca alteré el peso ni lo utilicé como una variable entonces no entiendo en qué momento este valor fue alterado y cómo podría evitarlo. Muchas gracias :)

<img width="956" alt="image" src="https://github.com/IIC2233/Syllabus/assets/162622991/eb930aa1-68d7-4f7b-8cf9-8353ce738127">

**Comment by Hernan4444** [comment]
Hola @trinicamposl 

Lo que pasa es que hay pesos  que son decimales tan chicos que el computador los procesa en este formato: `7e-05`  y lo que ocurre con eso es que tu forma de cargar datos no se percata que eso es un float y lo deja como un "string", ese es el único error.

Mi recomendación es aprovechar que el formato de los archivos está informado en el enunciado y ese se mantendrá siempre. Por lo tanto, tu sabes de antemano cuales columnas son int, float o str. Y convertirlos según su posición. 
Esta recomendación no es solo por los float, sino que  puede pasar que un animal decida llamarse "007" o "3.141519" y con tu forma de cargar los datos, ese nombre se cargará como un `int` o `float` cuando debía ser un `string` en ambos casos ... ocasionando un posible error por transformar columnas a otro tipo de dato donde no corresponde. 

Además, esto igual optimizaría un poquitin más tu código, porque en vez de verificar la información, se transfoma de inmediato al tipo de dato que corresponda, y eso reduce un poquito el tiempo de ejecución.

Espero que haya resuelto tu duda. ¡Éxito en tu tarea! 🚀
Saludosヾ(＾-＾)ノ

**Comment by trinicamposl** [comment]
Muchas gracias! Ahí lo arreglé y todo bien :grin:
