### ISSUE TITLE
Orden de multas y fiscalización de Magizoologos

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#459]
Hola! En esta parte se cobra la multa por cada criatura que escapó, enferma, con salud mínima? es decir nro_de_criaturas_enfermas x  valor_de_multa o es solo por la existencia de al menos una criatura que cumpla estas condiciones .Además hay cierto "orden" en el cual pueden cobrar las multas por ejemplo primero las de escape , luego las de enfermedad y al final salud, además  en el caso de que  exista este orden, a los magizoologos que no puedan pagar por ejemplo la multa por escape y se le retire la licencia , la siguiente multa que le podria quitar al magizoologo, según el issue #408 queda a nuestro criterio hacer en el caso de que el magizoologo no tenga licencia y si una multa , así que se podría hacer que en el caso de que la persona que no tenga licencia y pero si multas no le pase nada o tendría una deuda o algo así??Por último el magizoologo no puede elegir que multas pagar por ejemplo en lugar de pagar la de salud minima decida pagar la de escape y enfermedad?

**Comment by moquezada** [comment]
Hola @RonaldoSosa,

En primer lugar, el enunciado indica que **múltiples eventos del mismo tipo se revisan de forma separada**.

![lol](https://user-images.githubusercontent.com/43896576/79168504-164fbb80-7db8-11ea-9f15-d357b0012c96.PNG)

Por lo que debes determinar la ocurrencia de los eventos por cada criatura, esto significa que no puedes realizar `nro_de_criaturas_enfermas x valor_de_multa` ya que asumirías que todas incurrieron en ese evento 😮

Por otra parte, el orden en que son aplicadas las multas no está especificado en el enunciado por lo que queda a tu criterio :) Y como se menciona en la issue #408, ese aspecto también queda a tu criterio por lo que puedes seguir lo recomendado ahí. Recuerda siempre mencionar estos aspectos en tu README para que al momento de corregir sean tomados en cuenta 😄

Para la próxima vez, recuerda hacer tus preguntas en issues separadas y no concentrarlas en una sola ☺️ 

Suerte en la tarea!

**Comment by RonaldoSosa** [comment]
Entendido!Perdón por lo largo de la issue y muchas gracias

**Comment by Juampisaez** [comment]
Me surge la duda
Al no haber un orden especifico de cobro de multas, puedo revisar cada criatura del usuario y aplicarle todas las multas de inmediato por esa criatura e ir asi con las demas criaturas?

**Comment by rldelafuente** [comment]
Hola! Me suma a la issue, lo de **cómo cobrar una multa.** En el caso que dos criaturas se enfermen (criatura1 y criatura 2) ese día y una de ellas también se escape (criatura1)... ¿Esto significa que existe un 50% de prob de multar por el escape de criatura1 + 50% de prob de multar por el escape de criatura 2 + 70% de prob de multar por la enfermedad de la criatura 1? ¿Es así como se calculan estos eventos separados?
