### ISSUE TITLE
Rangos Notas Esperadas

### ISSUE THREAD

**Issue by negutierrez** [IIC2233/Syllabus#459]
Debido a que la cantidad de horas disponibles para estudiar para las tareas es un float, me imagino que se podria dar el caso de que, por ejemplo, para una actividad de "programación orientada a objeto" el alumno estudie 2.5 horas en total, y la tabla indica:
![captura](https://cloud.githubusercontent.com/assets/11590773/25877105/d4d23504-34f7-11e7-8684-ee2d2b2da5e7.PNG)
En este caso la nota esperada estaría entre 1,1 y 3,9, no?

**Comment by rmsolari** [comment]
Hola, para el estudio de materias queda a tu criterio. Puedes aproximar las horas a un valor entero o considerar que los valores de la tabla incluyen todos los decimales del entero, por ejemplo 0 - 2 incluiría [0 - 2,9].
