### ISSUE TITLE
QThreads y QTimer

### ISSUE THREAD

**Issue by Alonsinho1** [IIC2233/syllabus#459]
Hola para esta tarea tengo pensado hacer los cultivos, arboles y oro, con QTimer ya que estos son un tipo especifico de threads.

Mi duda es la siguiente, si ocupo QTimer solamente y no Qthreads tendre descuento en la pauta? Pregunto esto, ya que Qtimer es en escencia un Thread. Sin embargo no heredare directamente "Qthreads" o "threads

muchas gracias

**Comment by jeschuwirth** [comment]
Hola @Alonsinho1,

Qtimer no es exactamente un thread, el usuario Jeremy Friesner en StackOverflow tiene una explación muy buena de la diferencia en el siguiente [link](https://stackoverflow.com/questions/42279360/does-a-qtimer-object-run-in-a-separate-thread-what-is-its-mechanism).

Sin embargo un cultivo no tiene problemas al ser usado como Qtimer en vez de Qthread, por lo que no hay problema con que ocupes el primero en vez del segundo. 

Como consejo te recuerdo que el cultivo no debe cambiar de fase una vez alcanza la etapa de cosecha.

Suerte!
