### ISSUE TITLE
duda sobre Guardar partida

### ISSUE THREAD

**Issue by etoteiza** [IIC2233/syllabus#46]
Hola!! tengo una pequeña duda, en el enunciado dice que para guardar partida hay que guardar las posiciones descubiertas, con su número respectivo y la posición de cada lego. 
sin embargo, puedo por ejemplo, guardar todo el tablero si quisiera o debe ser explicitamente las posiciones de las baldosas descubiertas y de cada lego.

**Comment by jeschuwirth** [comment]
Saludos,

El enunciado te avisa de eso para que te guíes un poco en como guardar la partida, sin embargo queda completamente a criterio tuyo como lo haces, por lo que si quieres guardar todo el tablero no hay problema. 

Es importante la última línea de ese párrafo:
![image](https://user-images.githubusercontent.com/37160256/63120502-61d37080-bf70-11e9-8d81-faf871b7253e.png)

Por lo que debes explicar como funciona tu método de guardado y cargado.

Suerte en la tarea!

**Comment by rgmorales1** [comment]
Muchas gracias

**Comment by etoteiza** [comment]
Gracias!

**Comment by jeschuwirth** [comment]
Hola!

Para ahorrarse problemas les recomiendo especificar en el readme cual alternativa eligieron 😊, recuerden que si el ayudante tiene problemas va a buscar ahí la solución.

**Comment by rgmorales1** [comment]
Bueno muchas gracias, especificare todo en el readme entonces 😊
