### ISSUE TITLE
Interactuar con código en Jupyter

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#46]
**OS:** Windows 10
**Browser:** Google Chrome
**Contexto:** Descargué todos los programas acorde a las instrucciones enviadas antes de la clase 0

## Problema
Abro los .ipynb en una pestaña del browser desde https://github.com/IIC2233/contenidos/tree/master/semana-00. **Haciendo doble clic** sobre los cuadros de código insertos en los archivos 1 a 4, **no puedo interactuar** con ellos como mostró el profesor en clase (editarlo y volverlo a correr ahí mismo).

## Duda
**¿Hay alguna manera de comprobar si Jupyter está corriendo bien en mi computador? ¿Había que abrir el archivo .ipynb de manera distinta para poder interactuar? O ¿no es doble clic lo que tengo que hacer?** Sé que no es de vida o muerte, porque puedo copiar el código manualmente y editar y correrlo en mi propia interfaz de desarrollo, pero sería más cómodo poder aprovechar Jupyter.

## Ya intenté...
* **Googleando:** me quiere enseñar a editar el código fuente en Python
* **El botón "fork file and edit:"** solo me dejaba editar desde el código fuente.
* **Tratando de abrir el .ipynb desde mi repo local de 'contenidos:'** cada programa que intento me muestra el código fuente. No me muestra algo parecido a Jupyter como opción.
* **Descargando GitHub Desktop:** es bastante inútil, no hace nada muy distinto, solo me vuelve a clonar el repo.

**Comment by KnowYourselves** [comment]
Hola @sbcorrea!

_Jupyter Notebook_ funciona levantando un servidor en tu computador al cual puedes ingresar para interactuar con _notebooks._ Los pasos para poder utilizar esta herramienta son los siguientes:

1. Installar _Jupyter_ siguiendo las [instrucciones](https://iic2233.github.io/wiki/software) de la wiki.
2. Clonar el [repositorio de contenidos](https://github.com/IIC2233/contenidos).
3. Abrir la consola de comandos en el repositorio clonado.
4. Ingresar el comando `jupyter notebook`. Esto iniciará el servidor y abrirá automáticamente una pestaña en el browser por default de tu computador.
5. En la pestaña que se acaba de abrir podrás ver los contenidos de la carpeta. Desde ahí puedes navegar y abrir los _notebooks_ que quieras y podrás interactuar con ellos.

Quedo atento a cualquier duda que tengas con alguno de los pasos.
Éxito!

**Comment by benjavicente** [comment]
@KnowYourselves  Yo tuve el mismo problema, pero ejecutar `jupyter notebook` en el repositorio no me funcionó. Al ejecutarlo en mi pc se abre una carpeta predeterminada. Por ahora, encontré [estas soluciones](https://github.com/IIC2233/syllabus/issues/10#issuecomment-599210513).

**Comment by sbcorrea** [comment]
¡Perfecto! Me funcionó, muchas gracias :hugs:
