### ISSUE TITLE
IEEE754 /Modulo decimal

### ISSUE THREAD

**Issue by Jiparavich** [IIC2233/Syllabus#46]
Hola! busque en varias partes como representar un numero (e.g 54 o 5.4)  usando la librería decimal siguiendo los entandares de IEEE754 y no entendí bien. Alguien sabe donde hay un buen tutorial o me puedo explicar de manera simple!
Muchas Gracias!

**Comment by nebil** [comment]
Te recomiendo estudiar esta breve [guía](http://puntoflotante.org/) para entender, de forma somera, por qué es apropiado usar una librería como `decimal` para resolver esta tarea. La idea es que no desaparezcan _nebcoins_ —o cualquier otra moneda, en realidad— mientras realices operaciones aritméticas. Además, la [documentación oficial](https://docs.python.org/3/library/decimal.html) de la librería también es, probablemente, un buen punto de partida. :book::snake:

**Comment by Jiparavich** [comment]
Esta muy buena a guía! 
Gracias!

**Comment by Jiparavich** [comment]
Entonces, en resumen a cada valor que el usuario ingrese, tendré que aplicarle Decimal(), y luego realizar todas las operaciones con esto? 
Por ejemplo:
El usuario ingresa 1.5 como ask , al momento de ingresarlo convierto ese numero a decimal.Decimal(1.5) y luego con otro bid de decimal.Decimal(1.7)    --->el balance final será = decimal.Decimal(1.7) - decimal.Decimal(1.5) ?

**Comment by nebil** [comment]
Claro, algo así. Aunque probablemente es una mejor idea entregarle a la clase `Decimal` cada argumento como un _string_ y no como un _float_, para obtener la precisión que tu sistema requiere. Te sugiero echarle un vistazo a este [_quick-start tutorial_](https://docs.python.org/3/library/decimal.html#quick-start-tutorial) para saber más.

**ProTip™:** si sientes que se te va la vida al escribir todo eso para restar dos simples números, siempre puedes pedirle ayuda a [:atom:](https://atom.io/) para autocompletar.

O también podrías utilizar la sintaxis de [:snake:](https://www.python.org/) a tu favor.

```python
>>> from decimal import Decimal
>>> one = Decimal('0.1')  # más corto que decimal.Decimal('0.1')
>>> two = Decimal('0.2')  # más corto que decimal.Decimal('0.2')
>>> print(one + two)
0.3
```

Y por último, para llevar esto al extremo de la flojera…

```python
>>> import decimal
>>> D = decimal.Decimal
>>> one = D('0.1')
>>> two = D('0.2')
>>> print(one + two)
0.3
```

:roll_eyes:
