### ISSUE TITLE
Orden archivos

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#46]
En un issue anterior dijeron que podían cambiar los archivos, pero podrían cambiar el orden de las filas (que la fila centro_urbano pase a estar en la que está en DCCowork), o solo cambiarían los atributos? Además podrían cambiar los valores de los nombres de edificio en el archivo (que muralla pase a llamarse Murallla por ejemplo). Gracias

**Comment by Arcoirisky** [comment]
El orden de las columnas pueden cambiar, es una de las gracias que tengan los .csv, vienen con un header que te ayuda a saber qué hay en cada columna. Además, existen estructuras de datos que te pueden ayudar a trabajar esa información de forma muy eficiente!! 

El orden de las filas y los nombres no deberían de cambiar como sugieres pero, tampoco debería ser impedimento para tu programa :D 

Saludos~
