### ISSUE TITLE
Problema para hacer pull de la Tarea 0

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#46]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Problema para hacer git pull de la tarea 0

Intente hacer git pull para descargar los archivos de la Tarea 0, pero la consola me da un error, al hacer git status me sale que debo hacer commit de los archivos que ocupe en la AF1, pero tengo entendido que no debemos hacer commit del syllabus (hasta ahora git me habia funcionado correctamente, no tengo idea de que causara esto)

El error es " You have not concluded your merge (MERGE_HEAD exists)"

**Comment by nicoguz** [comment]
Holaa!!
Esto puede ocurrir porque posiblemente editaste los archivos del syllabus al hacer la actividad. Cuando la realizaste, copiaste los archivos a tu repo local? Si trabajaste en tu repo local todo el rato entonces por alguna razón debe haber un archivo que cambiaste por accidente o por alguna otra razón se edito y quedó distinto al repo online.

Para solucionar esto primero asegurate que todos los archivos en los que trabajaste los tengas guardados en alguna parte que no sea el repo del syllabus o el de contenidos. Una vez que tienes todos tus archivos guardados deberás resetear el **repo local del syllabus** para eliminar los cambios y poder hacer pull. Esto se hace ejecutando los siguientes comandos en el git bash:

`git fetch origin`
`git reset --hard origin/master`

Lo que hacen estos comandos es resetear todos los cambios que puedes haber hecho al repo local en tu pc con respecto al online.
Avisame como te va!!
