### ISSUE TITLE
[OOP] duda con constructor de clases ejemplo 2 de polimorfismo

### ISSUE THREAD

**Issue by DaniloCordova13** [IIC2233/Syllabus#46]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

Hola! Estoy teniendo problemas con entender cómo funcionan los constructores de las subclases. Estaba haciendo el ejercicio dos y no cambié nada del código predeterminado, el cual hacía el constructor. Resulta que al definir mis métodos y al ver si es que mi código está bien me retorna el error "DCGotchi.__init__() takes 4 positional arguments but 5 were given", y no entiendo por qué me dice que le estoy dando 5 argumentos siendo que son 4.

![Captura de pantalla (15)](https://github.com/IIC2233/Syllabus/assets/141789725/536f9c8a-3b69-49cc-9ef5-bf136587501b)

Saludos! :wink:

**Comment by fvidalf** [comment]
Hola @DaniloCordova13!

No he explorado en profundidad lo que te pide el ejercicio, pero si puedo indicar un par de cosas.

Primero, cuando tu creas una instancia de una clase, de forma **implícita** siempre se entrega la referencia al mismo objeto (aka, el *self*) como uno de los argumentos para el constructor (por eso los métodos siempre deben llevar el *self*). Dicho eso, efectivamente le estás entregando 5 argumentos al constructor de DCGotchi (el *self*, un nombre, una edad, un peso, y un valor de hambre). 

Ahora que sabemos eso, puede que el verdadero problema esté en los parámetros que recibe tu constructor. Puede que le estés pasando un valor de hambre, pero que no lo estés recibiendo correctamente... :eyes:

Y segundo, recuerda los paréntesis al usar ```super()```!

Échale un ojo, y si aún tienes dudas, responde esta misma ichu :)

Saludos! ✌🏽
