### ISSUE TITLE
Subir Tarea a github

### ISSUE THREAD

**Issue by xperseosses** [IIC2233/Syllabus#46]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, he estado tratando de hacer un push de mi tarea en numerosas ocasiones, pero me arroja muchos errores en la terminal y cuando por fin pude hacer el push en conjunto con el .gitignore todo se subió a mi repositorio pero no dentro de la carpeta T1, sino  al main y eso que en mi terminal estaba en el path correcto según nos enseñaron en la AC0. Ayuda por favor

**Comment by vicho14** [comment]
Hola!
Mira si bien en la terminal estabas en el path de la carpeta, lo que importa es que los archivos en tu carpeta local del repositorio en tu computador estén en la carpeta T1 de tu repositorio para que cuando hagas push se suban en esa misma carpeta. Te recomiendo que revises que estén en los archivos en la carpeta de la tarea y ahí hagas push nuevamente en la terminal.

Si no es eso avísame!
