### ISSUE TITLE
Donde debo escribir los Menús?

### ISSUE THREAD

**Issue by DiegoAHA** [IIC2233/Syllabus#46]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola, tengo la duda de en cuál archivo debería escribir el código del Menú de Inicio y el Menú de Acciones. ¿Debería escribirlo en tablero.py o en funciones.py o debería crear un archivo Python nuevo para hacerlo? Estaré atento a la respuesta y de antemano gracias.

**Comment by pedrozavalat** [comment]
Hola @DiegoAHA !

Para escribir el codigo del Menu de Inicio y el Menu de acciones idealmente debes realizarlo en otro archivo distinto, es decir, crear uno nuevo que importe funciones o métodos definidos en los archivos ```tablero.py```o ```funciones.py```, para que puedas desarrollar un codigo mas ordenado.  

Recuerda revisar el compilado de preguntas de la tarea, dado que en la issue #42, otro estudiante preguntó lo mismo. Igualmente, cualquier duda que tengas, responde este hilo.

Saludos :)

Pedro Z.
