### ISSUE TITLE
Permiso para:

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#46]
Quería saber si yo puedo crear otro archivo de texto para guardar información necesaria que debe ser permanente. 
También quería saber si puedo modificar las tablas a nivel de agregar columnas.

**Comment by flobarrios** [comment]
Hola! Si puedes 😬

**Comment by jorgeriesco** [comment]
y la otra?

**Comment by flobarrios** [comment]
No, no puedes modificar los archivos que nosotros te entregamos (a no ser de que los modifiques en tu programa directamente) ya que la correción sera con otros archivos (con el mismo esquema de los entregados).

Saludos!

**Comment by jorgeriesco** [comment]
Pero me refiero a que cuando el anaf modifique información si yo puede agregar una columna para agregar datos que se relaciones con los incendios por ejemplo. Al final es lo mismo que la primera pregunta, pero en vez de hacer otro archivo uso uno que ya está hecho.

**Comment by flobarrios** [comment]
SI puedes, pero tu programa debe ser compatible con los archivos que nosotros les entregamos. Si quieres modificarlos durante la ejecución del programa no hay problema :)
