### ISSUE TITLE
Ejercicio 4.1 métodos git_commit/git_push

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#46]
Hola, no comprendo muy bien lo que me piden hacer en los métodos git_commit y git_push :(

**Comment by igbasly** [comment]
Hola @Margarita-Paz :v:

Como te indican en el enunciado del ejercicio, la idea acá es emular como funciona git de forma bastante básica con los métodos `add`, `commit` y `push`. Dentro del constructor de la clase `Repositorio` se te dice además que eres libre de crear atributos que estimes necesarios, los cuales probablemente tengas que usar.

Para entender un poco como funciona git, primero comenzamos con que el repositorio existe en dos formas, **remoto** es decir, lo que se encuentra en el servidor de GitHub o servicio equivalente (nube) y **local** que es tu computador. 
Al clonar o crear un repositorio diremos que ambos se encuentran en igual estado "sin cambios", que en este caso sería el equivalente a instancia la clase `Repositorio`. Una vez que se "modifique" un archivo (para el ejercicio esto es ficticio), este ya puede ser subido al repositorio remoto mediante los comandos `add`, `commit` y `push`.

Una forma de ver este proceso es pensado que los repositorios son bodegas de archivos "clonados" es decir puedes tener los mismos en el servidor y tu computador, pero cuando quieras subir algunos cambios al servidor, siempre debes hacerlo mediante "cajas" que llamaremos *commits*. 
* Dicho esto, siempre tienes una "caja" vacía (*commit*)  donde debes agregar los archivos que quieras enviar, esto mediante `add`, lo que hace es agregar el archivo que indiques a esta "caja".
* Una vez que tengas dentro de tu caja todos los archivos que quieras enviar, ya se puede sellar y "subir al camión", aquí el equivalente sería `commit`, este comando lo que hace es sellar esta caja, copiar estos archivos (para que no pierdas los de tu carpeta inicial), agregarle un mensaje para que sepas que hay en la caja y meterla al camión. **OJO** 👀 que los archivos aún no se han subido, solo se han clasificado y preparados para enviar.
* Por último, una vez que hayas armado todas las "cajas" que quieras enviar,  se puede "despachar el camión a la bodega", esto sería el `push`, donde finalmente se envían todos los cambios al servidor.

Siguiendo la analogía, git sería este servicio de almacenaje que te permite guardar cambios por grupos (*commits*) al los cuales puedes acceder cuando quieres y volver a ese estado. Entonces, dicho todo esto, creo que te puede dar suficiente información en cuanto a como modelar el problema propuesto en el ejercicio 4.1, entendiendo mejor que hace cada comando.
Lo destacable aquí es que nunca debes quitar los archivos del repositorio local siempre y solo serán enviados al repositorio remoto una vez hecho `push`, debes ver la forma de como llevar el control en el proceso intermedio, ahí puede ser necesario crear nuevos atributos.

Espero que esto haya sido de utilidad, lo siento por el [Mucho texto] pero considero que valía la pena, de todas formas no dudes en preguntar cualquier duda que haya quedado o si llegas a tener problemas, saludos :smile:

**Comment by Margarita-Paz** [comment]
Ahora me quedó clarísimo! Muchas gracias😁
