### ISSUE TITLE
6.3 Consulta galaxias - Mejor galaxia

### ISSUE THREAD

**Issue by NicolasCourt** [IIC2233/Syllabus#46]
Hola!, en este punto del enunciado sale que solo se consideraran las galaxias que tengan al menos 3 planetas. Los planetas tienen que estar conquistados para ser considerados o se calcula con todos los planetas de la galaxia sin importar si esta conquistado?

**Comment by leolivares** [comment]
Hola! No es necesario que los planetas estén conquistados. Solo debe cumplir con tener al menos 3 planetas. Suerte!

**Comment by NicolasCourt** [comment]
Yaa Gracias! 💯
