### ISSUE TITLE
Cómo restaurar archivos 

### ISSUE THREAD

**Issue by CataLebe** [IIC2233/Syllabus#46]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Holaa, resulta que hice modificaciones en el archivo usuarios.csv, y por error borré información que no debería haber borrado (perdí a todos los nombres de los usuarios) ¿Hay forma de recuperar el archivo original o algo así?

Gracias de antemano

**Comment by franciscares** [comment]
Hola! Puedes volver a copiar el archivo del syllabus a tu repositorio o al lugar en el que estás haciendo tu código :)

**Comment by CataLebe** [comment]
Para hacer eso tendría que hacer git pull del syllabus de nuevo? He estado trabajando en la carpeta de mi repositorio, y todos los cambios se están viendo también reflejados en la carpeta del Syllabus que tengo en mi compu. Entonces me preocupa que al hacer git pull del syllabus, mi carpeta del syllabus del compu se "resetee" y por ende mi repositorio también, perdiendo mi avance.

**Comment by franciscares** [comment]
Hola! Los archivos que estás usando, ¿los tienes en tu repositorio o en syllabus? Te recomiendo que copies tu avance en tu repositorio y hagas un push para subir tu avance y no perder los cambios, o que guardes tu avance en una carpeta aparte en tu pc. También puedes borrar syllabus, clonarlo de nuevo en tu pc y copiar los archivos que se te modificaron a tu repositorio personal para seguir avanzando.
