### ISSUE TITLE
Uso de Tee

### ISSUE THREAD

**Issue by fmandiolafellay** [IIC2233/Syllabus#460]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, al usar tee del estilo gen_c ,gen = tee(gen) no me tira error en las funciones generadores, tampoco False al revisar los elementos_prohibidos, cuando yo hice la pregunta me respondieron que si se podía usar asi, entonces no entiendo el issue #406, ya que en principio no imcumplo nada. Gracias.

**Comment by Hernan4444** [comment]
Hola @fmandiolafellay 

Lo que pasa es que si estás dentro de una función generadora, se permite crear estructuras sin compresión, por eso si haces `gen_c ,gen = tee(gen)` **dentro de una función generadora** está todo bien, pero si haces eso fuera de una función generadora, ahí hay problema porque estarías fallando en el disclaimer de la tarea, dado que esa línea pasa por la creación de una tupla sin aplicar compresión (por el tema de desempaquetar). Si es que quieres usarla fuera de una función generadora, ahí tienes que hacer lo que dice la issue #406


Espero que haya resuelto tu duda. ¡Éxito en tu tarea! 🚀
Saludosヾ(＾-＾)ノ
