### ISSUE TITLE
Uso de mis EDD para testing

### ISSUE THREAD

**Issue by fedetaladriz** [IIC2233/Syllabus#460]
Hola!
He visto algunas issues preguntando respecto a archivos que utilizarán en el testing. Puedo **no** utilizar archivos? Es decir, entregar mis propias estructuras de datos en el setUp para probar cada consulta y así evitarme trabajar con archivos?
Gracias!!

**Comment by Arcoirisky** [comment]
Puedes usar setUp para crear esas bases de datos pero, si aparte quieres testear si estás leyendo bien tus archivos, puedes crear tu propio archivo con tus propias bases de datos en el mismo setUp y luego eliminarlo en el tearDown. Puedes hacerlo cómo desees pero, no olvides usar bien setUp y tearDown que es algo requerido 😅 Y especificar en el Readme!

**Comment by fedetaladriz** [comment]
@Arcoirisky y es necesario probar que se están leyendo bien los archivos?😅

**Comment by Arcoirisky** [comment]
Skkdksjd Lo mínimo que necesitas testear está en el enunciado :D

**Comment by fedetaladriz** [comment]
Jajajajajjaja si se, pero como me dijiste "si quieres" me quedó la duda😅
Graciass!!
