### ISSUE TITLE
Se permite el uso de groupby y de chain de itertools?

### ISSUE THREAD

**Issue by jrodriguezluna** [IIC2233/Syllabus#460]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/396)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/395)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Se permite usar groupby de itertools para agrupar datos? además, se permite usar chain? Ambos devuelven una especie de generador por lo que no debería ser ilegal :thinking:

**Comment by jtlledo** [comment]
Hola @jrodriguezluna! Están permitidos los métodos que mencionas, al ser parte de la librería `itertools`. Nuevamente, te recuerdo que estas preguntas deben hacerse en la issue correspondiente (#395) para que todas las preguntas de este estilo queden en un solo lugar. Éxito en el desarrollo de tu tarea!
