### ISSUE TITLE
duda tuplas del iterable en "ganancias_producidas_en_los_pedidos"

### ISSUE THREAD

**Issue by vhernnda** [IIC2233/Syllabus#460]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/Syllabus/issues/420).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Teniendo en cuenta que generador_contenido_pedidos posee varios contenidos que comparten el mismo id_pedido, debe haber una tupla por cada instancia de contenidos_pedido que este en el generador o una tupla por cada id_pedido?

**Comment by FradexMF** [comment]
Hola @vhernnda !
Se espera que se retorne una tupla por cada id_pedido.
