### ISSUE TITLE
paths en la tarea

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#460]
Hola. 
De que forma se establece un path en la tarea de modo que funcione tanto para mi como el ayudante?

Gracias

**Comment by baosse** [comment]
Holaa Diego! 
Para las tareas debes usar los paths relativos tomando en cuenta de que estás dentro de la carpeta de tu tarea. Si quieres acceder a un archivo dentro de esta, ocupas solo el nombre del archivo, si quieres usar un archivo dentro de una carpeta deberás usar os.path.join('carpeta','archivo').
Espero que te haya servido! Mucho éxito con tu tarea✨

**Comment by diego-ayala-2000** [comment]
Gracia por la ayuda, lo que no entiendo es como hace para que visual studio se de cuenta que el directorio es la carpeta del curso y de ahi usar los paths relativos

**Comment by baosse** [comment]
mm si te refieres a cómo lo vamos a revisar nosotros, con lo que te dije debería estar bien, de esa forma podremos hacerlo correr❤️

**Comment by diego-ayala-2000** [comment]
Me refiero a como hago para establecer mi directorio en la carpeta del curso en visual studio, no he podido cachar eso. 
Gracias por la ayuda
