### ISSUE TITLE
Definicion de probabilidades

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#460]
Hola, tengo el siguiente problema:
Al definir las probabilidades de ocurrencia me queda una linea muy larga. Existe alguna forma para lograr separar esta linea? he tratado con el backslash que se ocupa en un if por ejemplo para separarla, pero me tira error de escritura.

**Comment by moquezada** [comment]
Hola @Juampisaez!

En este [link ](https://stackoverflow.com/questions/53162/how-can-i-do-a-line-break-line-continuation-in-python) puedes encontrar información respecto a realizar linebreaks. Por otra parte, está la [guía de estilo](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) que aporta mas información al respecto.

Además, una buena forma de acortar las ecuaciones es crear **variables auxiliares**, pero recuerda que estas también deben seguir las reglas de estilo. Supongamos que queremos formar la siguiente formula de probabilidad:

![asddsdsd](https://user-images.githubusercontent.com/43896576/79173239-f5419780-7dc4-11ea-89d7-aacb90b76b05.PNG)

Puedes crear variables auxiliares de esta forma:

```python
factor_salud = (salud_total-salud_actual)/salud_total
factor_resp = resp_magizoologo/100
```

Luego, tu fórmula quedaría así:

```python
probabilidad = min(1, prob_enfermarse + max(0, factor_salud - factor_resp))
```

Claramente tú puedes escoger nombres más cortos siempre y cuando estos sean claros y descriptivos con el fin de apegarse a las reglas de estilo.

Suerte en tu tarea! :)
