### ISSUE TITLE
AF5 decorador revisar_ingredientes()

### ISSUE THREAD

**Issue by maurobsp** [IIC2233/syllabus#460]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola tengo una duda respecto a el decorador __revisar_ingredientes()__ . En el enunciado nos dice que debemos verificar que antes de cocinar una torta debemos verificar que tiene que haber al menos el numero de ingredientes que tiene la receta. con esto se refiere a que debemos tener por lo menos las cantidades de cada ingrediente de la torta, o que utilizando ingredientes de la torta y otros que nos puedan servir como remplazo tener esa cantidad.  Ej una torta que requiere [mermelada, mermelada]
debemos tener mínimo dos e mermelada o si tenemos 4 manjar y 2 crema pastelera como tenemos mas de dos ingredientes la torta se puede realizar??

**Comment by igbasly** [comment]
Hola @maurobsp 

Como mencionas, vale cualquier ingrediente. En este caso se refiere a que entre todos los ingredientes disponibles haya cantidad suficiente para preparar la torta.

Espero que se entienda 😅.

**Comment by igbasly** [comment]
Por favor no cierres la issue para que esté disponible para todes 🙌

**Comment by Piolawa** [comment]
No entendí, puedes explicarlo de nuevo por favor :c

**Comment by igbasly** [comment]
No hay problema @Piolawa :smile:
En el enunciado se pide que "hayan suficientes ingredientes", eso significa que en total, considerando todos los ingredientes que existen, haya cantidad suficiente para satisfacer la receta.
Por ejemplo, si una torta requiere de 3 ingredientes, independiente de cuales sean, si entre todos los ingredientes que existen se pueden conseguir 3 unidades, entonces se puede preparar la torta.

Se entiende ahí?? Avísame si aún no queda claro. 😅
