### ISSUE TITLE
Duda ganancias_producidas_en_los_pedidos

### ISSUE THREAD

**Issue by dani-oviedo** [IIC2233/Syllabus#461]
* [ "X"] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ "X"] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ "X"] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/Syllabus/issues/420).
* ["X" ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola resulta que no se si los test tienen buena la aproximación, ya que tengo mi código pero hay ciertas diferencias con algunos valores por 1 entero, revise con calculadora que números daban, y creo que hay algunos test case que están aproximando mal , por eso consulto, a no ser que allá entendido mal como se calcula la ganancia por pedido.

**Comment by NachoRinda** [comment]
Hola, quizás tengas la misma duda que la issue #446 . Avísame si te sirve.

**Comment by dani-oviedo** [comment]
cierto gracias, perdon las molestias :)
