### ISSUE TITLE
Setter: Cómo hacer que funcione una vez

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#461]
Hola!

Tenía entendido que el setter funciona cuando se instancia un objeto. Por lo que veo el setter se "activa" cada vez que modifico el valor. ¿Cómo puedo hacer que se ejecute una vez o qué forma existe para lograr algo equivalente?

Gracias!!

**Comment by amahns1** [comment]
En el fondo, al parecer los atributos privados no son modificables. Esto perjudica gran parte del código. Qué forma sería una buena alternativa (equivalente a modificar los atributos privados).

**Comment by amparostevens** [comment]
Holaa! 
No se si entendí bien la pregunta jajaj pero voy a explicar esto por si te sirve. 

Si te fijas en este ejemplo (sacado de los contenidos el curso __semana-02/2-properties__), sí se esta modificando un atributo privado pero a través de un método (__setter__). 

```class Puente:
    
    def __init__(self, maximo):
        self.maximo = maximo
        self.__personas = 0
        
    @property
    def personas(self):
        return self.__personas

    @personas.setter
    def personas(self, p):
        if p > self.maximo:
            self.__personas = self.maximo
        elif p < 0:
            self.__personas = 0
        else:
            self.__personas = p
```
Ahora que existe una property, se puede llamar a `puente.personas` como un atributo normal, pero `puente.__personas` sigue estando encapsulado.

Avísame si responde tu duda!

**Comment by amahns1** [comment]
Graciaas!!

Lo que pasa es que estaba abriendo los archivos en el `setter` lo cual me hacía imposible modificar los atributos en otras partes del código. Ya lo pude solucionar :)

**Comment by amparostevens** [comment]
Bacan que se solucionó!!! :tada:
