### ISSUE TITLE
Formato archivo diagrama

### ISSUE THREAD

**Issue by Jaluco** [IIC2233/Syllabus#461]
¿El diagrama debe ser entregado en un tipo de archivo en especial? txt, md, etc?

**Comment by FernandoPieressa** [comment]
Hola!

El formato no es muy relevante mientras quede en un formato fácil de entender y no tengamos que instalar aplicaciones desconocidas para poder verlas. 

Saludos!

**Comment by ofvera** [comment]
Puedo considerar un evento algo que sucede dentro de otro evento, o los escribo todo en un evento.
EJ:
Catedra|Cada semana| Hay actividades y posiblemente un control...
Actividad|Cada catedra...
Control|Total:5 en cada catedra....
