### ISSUE TITLE
bytes not in PNG

### ISSUE THREAD

**Issue by StroveLight** [IIC2233/syllabus#461]
el metodo del envio de los bytes es libre cuando no es png? (es decir que puedo hacer que el primer byte mi diga si es png o no?[es decir si el primer byte es 137 o no])

**Comment by iqacevedo** [comment]
Hola !

El protocoló de envío de bytes lo defines tu. Puedes hacer lo que estas diciendo, pero te recomiendo crear tu propio protocolo, que diga que tipo de mensaje se va a recibir (una imagen, un mensaje, una acción). El problema que puede ocurrir si lo haces como dices, es que justo envíes algún mensaje que comience con 137 y se asuma que es una imagen en png, aunque no lo sea.

Saludos !
