### ISSUE TITLE
Mala practica: uso de if/else dentro de __init__()

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#461]
Hola,
Tenia la siguiente duda. ¿Es considerado una mala práctica el uso de if en __init__( )?

Saluds!

**Comment by JosefaPaz** [comment]
Hola @Ignacioislae ,

Sí, podría considerarse mala práctica el uso de condicionales dentro del constructor de una clase, ya que esta solo debe tener los atributos base.
 
Si necesitas elegir, por ejemplo, qué valores tendrá un atributo dependiendo de alguna acción, te recomiendo hacerlo con properties o con un método que defina posteriormente el atributo. (Estos contenidos se encuentran en la semana 2 😄 )

Éxito!

**Comment by Ignacioislae** [comment]
Ya Graciaas!

**Comment by benjavicente** [comment]
> ya que esta solo debe tener los atributos base.

¿Qué pasa en el caso que las atributos base dependan del contexto? Por ejemplo, al crear un Magizoólogo se pide crearlo con ciertos atributos aleatorios, y al cargarlo, con atributos fijos del archivo. Estos atributos no cambian cuando se realizan acciones, por lo que usar _properties_ tal vez no sea lo adecuado.

**Comment by JosefaPaz** [comment]
Hola @benjavicente , 

Para realizar esto, es mejor que, antes de crear la instancia del Magizoólogo, primero crees los valores de los atributos aleatorios, para así después entregarlos y crear la instancia, tal como se explica en la issue #334 . Así no tendrás diferencias al cargar y crear.

Quedo atenta 😄
