### ISSUE TITLE
Error con .emit

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2233/syllabus#461]
Hola, tengo un problema.

En una clase use una señal como en el ultimo ejemplo del material de front-end y back-end, creando un senal = None en el iniciador de una de las clases y un senal = pyqtSignal() en los atributos de clase de la otra, conecte la señal con el metodo correspondiente en el iniciador de esta otra clase y finalmente en el if __name__ == "__main__" cree la igualdad de señales clase1.senal = clase2.senal.

El punto es que despues en las mismas clases intente crear otra señal siguiendo los mismos pasos pero me arroja un error el programa, es el siguiente:

AttributeError: 'NoneType' object has no attribute 'emit'

Que puedo hacer ? :(

De antemano muchas gracias.

**Comment by pwillmer** [comment]
Me paso lo mismo, en mi caso fue porque en el backend se estaba ejecutando una función proveniente de la señal None antes de que la señal misma fuera definida. Lo solucioné poniendo if senal:

**Comment by DCCollao** [comment]
Hola! 
Tal como te dice @pwillmer, debes estar llamando el `emit` de la señal antes de definirla con 
```python
clase1.senal = clase2.senal
```

Por lo que en realidad estás haciendo 
`None.emit`
Hay varias formas de solucionarlo, siendo la mencionada por @pwillmer una de ellas. Otra forma sería identificar la parte de tu código que ejecuta la señal antes de lo que deseas, y modificarla para que no tenga este comportamiento indeseado.

Quedo atento!

**Comment by DiegoPibe** [comment]
Siii bacan me sirvio, pero ahora tengo otro problema con otro emit en otra parte de la tarea, hago algo parecido a lo que comente en la otra duda, pero ahora me tira este error:

AttributeError: 'PyQt5.QtCore.pyqtSignal' object has no attribute 'emit'

cual es la diferencia ? porque solo cambia el 'NoneType', que significa ?, algun consejo ?. :(

gracias de antemano.

**Comment by DCCollao** [comment]
Hola! 

Podré ayudarte mejor si incluyes la parte del código que te genera problemas.
Quedo atento!

**Comment by DiegoPibe** [comment]
Sii... siento, ahi va:

`class Pertenencias(QObject):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.senal_actualizar_dinero = None

        self.dinero = MONEDAS_INICIALES
        self.inventario = []

    def actualizar_dinero_estadisticas(self):

        if self.senal_actualizar_dinero:
            self.senal_actualizar_dinero.emit(self.dinero)

...`

y hacia abajo de este codigo solo hay metodos conectados a los botones de compra y venta de la tienda que funcionan perfceto.(esto en el back-end).

**Comment by DCCollao** [comment]
¿Conectaste la señal con el método que quieres que se ejecute al hacer señal.emit()?

**Comment by DiegoPibe** [comment]
Que rabia perder tiempo asi, ajaja ya me di cuenta escribiendo el codigo aqui del erroooor, instancie la Clase_1 como clase1 y despues iguale asi la señal:

clase2.senal = Clase1.senal (con mayuscula).

gracias de todos modos, y perdon por el tiempo. :(

**Comment by DCCollao** [comment]
No hay problema! Me alegra que hayas encontrado el error :) 
Mucho éxito!
