### ISSUE TITLE
AF5 consulta con el decorador capa_relleno

### ISSUE THREAD

**Issue by dammr54** [IIC2233/syllabus#461]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/223)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Dudas sobre enunciado y llamado de la función con sus argumentos
No entiendo muy bien como se debe acudir a los atributos o variables que hay que modificar dentro del decorador capa_relleno, al correr el código me aparece que el parámetro de decorador() es del tipo None.
Algo parecido me pasa al intentar comprender como funciona la definición de wrapper(*args) en el decorador encriptar_receta

**Comment by dammr54** [comment]
decorador capa_relleno *

**Comment by tqmbanados** [comment]
Hola! No entiendo del todo tu pregunta, me podrías aclarar algunas cosas?
1.- A cuál parámetro de decorador() te refieres?
2.- A qué te refieres con la definición de wrapper? Pregunto por que en general, esas definiciones están tal cual como sale en los contenidos.

Lo único que hay que tener en mente es que estos decoradores se aplican sobre **métodos**. El método funciona prácticamente igual que una función, con la sola excepción que el primer argumento siempre es la instancia de la clase que lo llama (```self```). En el decorador, debes tomar este argumento en cuenta, pues si quieres llamar el metodo en el wrapper, debes incluir manualmente esta instancia (que la recibes de los argumentos del wrapper). El beneficio acá, es que te permite acceder a la instancia que llama al método y sus atributos.

**Comment by dammr54** [comment]
Muchas gracias, mis preguntas fueron respondidas con la descripción que has hecho.
Otra duda que me surge es, si he agregado manualmente el argumento self, es posible hacer lo mismo con los demas y omitir en este caso *args y **kwargs como argumentos?

**Comment by tqmbanados** [comment]
Hola! Es posible hacer esto, pero recuerda que con decoradores, es buena práctica dejar *args y **kwargs aunque no se usen en esta actividad en específico. Esto porque los decoradores deberían ser "universales". Claramente estos decoradores en específico no se usarán para nada más, pero de todas maneras es recomendable acostumbrarse a esto 😸.
Me alegro que se hayan respondido tus preguntas!
