### ISSUE TITLE
duda sobre la evaluación de la hora en la función clientes_despues_hora

### ISSUE THREAD

**Issue by Yeps3nM** [IIC2233/Syllabus#462]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/Syllabus/issues/420).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Tengo una duda respecto a cómo considerar el intervalo de tiempo cuando veo los pedidos recibidos después de cierta hora. Tomo como tope las 00:00 ? o si la hora del pedido fue a las 23:00 considero pasado las 00:00 ? 

Muchas gracias!

**Comment by MaxAl100** [comment]
Hola! Sí, el tope son las 00:00 (sin contar este horario), ya que ahí comienza el siguiente día de trabajo.
