### ISSUE TITLE
AF5 - duda en escribir_receta

### ISSUE THREAD

**Issue by Piolawa** [IIC2233/syllabus#462]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola!, 
El decorador "encriptar_receta" funciona bien y me encripta los ingredientes que le pongo, pero al ponersela a escribir_receta me di cuenta que al abrir el archivo nuevas_recetas.csv solo guarda la mitad de los ingredientes sin considerar el primero, esto porque se escribió en esa función receta[1::2] como sale a continuación:

´´´archivo.write(f"{receta},{','.join(receta[1::2])}\n")´´´

Si esto lo reemplazo por receta[::] me logra guardar todos los ingredientes encriptados en nuevas_recetas.csv

Como esa parte no se debía modificar, no se si es un error de tipeo o a mi me falta agregar algo a mi código, saludos.

**Comment by imuoz** [comment]
Me pasa lo mismo

**Comment by alvarocisternas** [comment]
Tengo la misma duda.

**Comment by igbasly** [comment]
Hoola @Piolawa @imuoz @alvarocisternas ✌️

Efectivamente el método guarda la mitad de los ingredientes, pero esto se debe a que el método considera recibir una torta terminada y por ende, con capas de relleno. Por eso es que se recorre los ingredientes saltando saltando un ítem por medio.

Avísenme si no queda claro, éxito en la actividad 😉
