### ISSUE TITLE
Simular competencia

### ISSUE THREAD

**Issue by cnillanes** [IIC2233/syllabus#462]
Hola! 
El enunciado dice "En el caso que resten días de competencia, se mostrará una lista de deportistas disponibles para competir (...) si es que ya no quedan más días para competir (...) dar la opción de Salir del programa o realizar una nueva simulación"

Me queda la duda con lo de realizar una nueva simulación, porque dado que no quedan mas dias para competir, al reingresar a esta opcion como que entraría directamente al "else" y mostraría el estado y las opciones ya mencionadas, lo que no me hace mucho sentido. Puede que con realizar nueva simulacion hayan querido darle la opcion al usuario de comenzar nuevamente una partida? (Menu Inicio)

**Comment by amparostevens** [comment]
Hola @cnillanes !

Sí, efectivamente se refiere a realizar una nueva simulación del programa. Es decir, si se elige __salir__ el programa debería terminar, en cambio, al elegir __realizar nueva simulación__ tu programa debería volver al __menú de inicio__ y comenzar todo de nuevo desde cero.

Mucho éxito! 🌈
