### ISSUE TITLE
no usar forEach?

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#462]
Hola
Encontré una forma de iterar con lo que tenemos completamente legal y que me sirve para todo (no lo digo aquí por si lo consideran como "dar la respuesta")... ¿puedo prescindir totalmente del forEach que comentaron en una issue el otro día? Es que **no lo necesito** :/

**Comment by Hernan4444** [comment]
@jmwielandt si la forma que hiciste cumple con alguna de las formas que puse en la issue #401, no hay ningún problema de prescindir del for each, si no cumple con esas, es probable que es un for indebido. Pero si cumple, dale nomás 👍 
Saludos ✌️

**Comment by jmwielandt** [comment]
O sea... ni siquiera es un ciclo while o for y no tiene efectos colaterales
Gracias :D
