### ISSUE TITLE
Interfaz en Ubuntu

### ISSUE THREAD

**Issue by lootarola** [IIC2233/Syllabus#462]
Tengo Ubuntu y no me aparece la opción abrir en la interfaz :(

**Comment by naazocar** [comment]
Somos dos :(

**Comment by fgbruna** [comment]
Si usas Ubuntu Unity (El con detalles naranjos), los menús de opciones no aparecen en la ventana misma de los programas si no que en la esquina superior izquierda en tu pantalla.

**Comment by lootarola** [comment]
Aparece en pantalla completa :1st_place_medal:

**Comment by naazocar** [comment]
Bueena, en pantalla completa si

**Comment by matiaseche** [comment]
Yo uso Ubuntu y al principio lo ponia en pantalla completa para poder abrir el archivo de consultas. Después me di cuenta que igual me aparece la opción arriba a la derecha (en la esquina de la pantalla, no de la interfaz).
