### ISSUE TITLE
Nivel de Programación al visitar Profesor

### ISSUE THREAD

**Issue by nivek0o0** [IIC2233/Syllabus#462]
Hola, no queda claro cúando hay que modificar el Nivel de Programación del alumno. 

![one](https://cloud.githubusercontent.com/assets/20782451/25901337/e18a668e-356c-11e7-8a95-4e0f55df27e2.png)
Según esta parte, y según la fórmula, debería ser al cambiar de semana, por ejemplo el domingo.

![two](https://cloud.githubusercontent.com/assets/20782451/25901343/e5ed939a-356c-11e7-9879-04671dd1d476.png)
Pero en esta última parte se da a entender que aumenta 8% en medio de la semana, o sea inmediatamente después de visitar al profesor, lo que tendría consecuencias directas sobre los progresos de las evaluaciones que se realicen los días posteriores dentro de esa semana.

**Comment by sebacruzd** [comment]
Hola,

Esto queda a tu criterio. Puedes hacer que cambie instantáneamente al juntarse con el profesor o al final de la semana cuando se recalcule.
Recuerda especificar tu decisión en el README.md

Saludos!

**Comment by nivek0o0** [comment]
Gracias!
