### ISSUE TITLE
Limpiar QLabel de un QGridLayout

### ISSUE THREAD

**Issue by jperalta2202** [IIC2233/syllabus#462]
Tengo dos QLabel que agregue a mi QGridlayout con el comando addWidget en la misma posicion y me quedan uno encima de otro.  Pero cuando quiero limpiar la celda con el comando clear() para agragar otro QLabel, me elimina solo el QLabel de mas abajo y se mantiene el de mas arriba

**Comment by gatochico** [comment]
Hola! ¿Has probado con alguno de estos dos métodos?

![image](https://user-images.githubusercontent.com/37161120/66539643-216f1980-eaff-11e9-98fd-a77dfa6f5576.png)
[Sacado de aquí](https://www.riverbankcomputing.com/static/Docs/PyQt4/qlayout.html#removeItem)
Si es que añadiste los qlabel con addWidget, quizá el segundo te sea útil :0

Avísanos cómo te va!

**Comment by jperalta2202** [comment]
No funciona con esos comandos, ya que son metodos de QLayout y no de QGridLayout. Buscando la clase QGridLayout en esa misma pagina, el unico metodo que parece util es itemAtPosition, que me retornaría el ítem que este en una posicion dada, pero ese metodo solo me retorna el item de mas "abajo".

**Comment by JuanDlugo** [comment]
hola! pudiste resolverlo?

**Comment by gatochico** [comment]
Hola! Lamento la demora,

Aunque esas funciones son de QLayout, QGridLayout hereda de QLayout y por ende, debería heredar las funciones también... ¿Qué error te lanza al intentar usarlas?
