### ISSUE TITLE
Comando \chao

### ISSUE THREAD

**Issue by josejimenezp** [IIC2233/syllabus#462]
Hola, el usuario tiene que escribir "\chao <nombre>" o "chao <nombre>"? Es que si pongo "\chao" me sale un error de PEP8 en PyCharm :(

**Comment by Arcoirisky** [comment]
Hola~ 
¿Podrías mostrar el error? 🤔

**Comment by josejimenezp** [comment]
![Captura de pantalla](https://user-images.githubusercontent.com/48298035/59155249-2178e300-8a53-11e9-8935-776f772a6cba.png)

**Comment by Arcoirisky** [comment]
No te preocupes por eso. El enunciado lo pide, aunque al pep8 no le guste 😅

**Comment by StroveLight** [comment]
si quieres que no te moleste puedes escribir r'\chao' ese es algo que se le llama 'raw string', y hace que no te tomen esas 'escape secuence', ya que la gracia del raw string es que te lee las cosas tal como las escribiste


<img width="356" alt="chao" src="https://user-images.githubusercontent.com/48263952/59158749-fc08cb00-8a8c-11e9-9c9a-8de2c67de3c1.png">
