### ISSUE TITLE
Ayudantia Networking

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#463]
Hola, en el ejemplo de Cachipun, en que orden hay que ejecutar los archivos?

**Comment by Polea012** [comment]
Hola! El primer archivo que debes ejecutar es Ayudantia_Server.py, que se encarga de levantar el servidor y escuchar a clientes.

Luego, ejecutas Ayudantia_Cliente.py. Al ejecutarse el cliente se va a conectar con el servidor que levantaste previamente. 

Finalmente, debes ejecutar el archivo Ayudantia_Cliente.py de nuevo **sin detener las ejecuciones anteriores ** para poder empezar el juego del cachipun. 

Espero haberte ayudado, saludos!

**Comment by VicenteMerino** [comment]
Hola, al hacer eso me tiraba un error en el cliente que decía algo de self.window is None. No se si sabes a que se debe, en la tarde podria mandar una foto.

**Comment by Polea012** [comment]
Hola! Cometí un error en el nombre del archivo. En vez de Archivos_Cliente.py es Archivo_Interfaz.py.

Mil disculpas por el error. Ahora debería funcionar

**Comment by VicenteMerino** [comment]
Debo ejecutar dos veces el archivo inteefaz en ese caso?

**Comment by Polea012** [comment]
Si! Debes ejecutarlo dos veces para poder jugar.
