### ISSUE TITLE
Uso de []

### ISSUE THREAD

**Issue by VicenteDubo** [IIC2233/Syllabus#463]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, se que hice una pregunta similar a esta anteriormente pero quiero estar seguro de si lo siguiente es valido, si es que estoy dentro de una función generadora ¿Puedo crear un diccionario de la siguiente manera?

"diccionario = {i: [] for i in generador}"

Entiendo que esta permitido hacer la lista por compresión, pero mi duda esta con la lista vacía despues de los dos puntos, ¿Puedo usarla de esa manera si es que defino "diccionario" dentro de una función generadora?

Muchas Gracias.

**Comment by Hernan4444** [comment]
Hola @VicenteDubo 


Si estás dentro de una función generadora, no hay ningún problema en crear estructuras como tu quieras tal como se muestran en estos ejemplos

* https://github.com/IIC2233/Syllabus/issues/339

Si estás fuera de una función generadora, ahí el script y el _disclaimer_ del enunciado se quejarán porque estás creando una lista vacía sin usar compresión. Ojo que la compresión está bien en cualquier parte de la tarea, pero la lista vacía solo se puede crear dentro de una función generadora o un reduce.

Aquí recomendamos fuertemente usar el script que subimos hace algunos días (el archivo .pyc), dado que ese te confirmará si su uso está permitido o no. Si el script te dice "true" entonces está todo en orden porque ese mismo script usaremos para validar sus tareas. Si es que el script te dice "false" es que no estás cumpliendo algo, tal vez estás creando algo prohibido fuera de un reduce o de una función generadora, o bien no estás usando compresión para crear una estructura. Además, el mismo  script te indicará qué línea está mal.

Espero que haya resuelto tu duda. ¡Éxito en tu tarea! 🚀
Saludosヾ(＾-＾)ノ

**Comment by franquijada** [comment]
Hola, tengo una duda respecto a el uso de listas vacia, en una funcion estoy creando una lista vacia, la cual uso en una una funcion generadora (la creo afuera de la funcion generadora). Al usar el archivo.pyc dice "true", entonces mi pregunta es si esta bien implementado o no
