### ISSUE TITLE
Problema .gitignore no ignora aunque sale que si

### ISSUE THREAD

**Issue by rgevert** [IIC2233/Syllabus#463]
![captura](https://user-images.githubusercontent.com/30696955/31320895-8ceadf8e-ac52-11e7-903b-7b6e0b20772b.PNG)

Me sale eso, pero igual se me sube la carpeta gui. ¿Qué estoy haciendo mal?

**Comment by glbello** [comment]
¿podrías mostrar un screenshot de lo que tienes escrito en tu .gitignore?
para mí cuando son carpetas la que se quiere evitar que se suban se le debe agregar un ```/```.
Ejemplo: ```/gui/```

**Comment by rgevert** [comment]
intente con los backslash pero tampoco funciona, de hecho tengo 3 carpetas que genera automáticamente pycharm y si se ignoran, pero la gui no

![captura](https://user-images.githubusercontent.com/30696955/31321255-52bce080-ac59-11e7-8c1c-116a7f8f053a.PNG)

**Comment by Javierdr** [comment]
A mi me paso en la tarea 2 y era porque ya había subido los archivos a mi repositorio y luego creé el gitignore. Intenta borrando los archivos de tu repositorio (los que quieres ignorar).

**Comment by glbello** [comment]
Por si sirve de algo esta es la forma en que tengo escrito mi ```.gitignore``` y que me funciona:

![panta](https://user-images.githubusercontent.com/13740193/31321300-30886236-ac5a-11e7-8e93-9cfe20a519c6.png)

también puede ser lo que dice Javierdr

**Comment by rgevert** [comment]
@glbello @Javierdr no se cual de las dos sirvió, pero ahora si ignora jaja gracias
