### ISSUE TITLE
Duda sobre problemas al definir funciones lambda (Semana 10)

### ISSUE THREAD

**Issue by FVivess** [IIC2233/syllabus#463]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Lo que ocurre es que cuando quiero escribir una función lambda de la forma en que se define en los apuntes, ocurre que se cambia el formato. 
Por ejemplo, si quiero definir una función simple, como:
`funcion = lambda x: x+1`

al ejecutar el programa, el código se cambia automáticamente a:
`def funcion(x): return x+1`

No estoy seguro si este es el resultado esperado, pero me imagino que no, ya que en los apuntes dice que existen diferencias entre una función definida de manera normal, y una función lambda (y lo que ocurre aquí es que se redefine la función lambda como una normal).

**¿Como puedo hacer que deje de pasar esto?**
(utilizo VSCode para programar)

**Comment by tqmbanados** [comment]
Hola! En ese caso, ambas líneas son prácticamente iguales. La diferencia es algo de sintaxis, y es preferible usar la versión ```def funcion(x): return x+1```. Entonces, probablemente tu programa está haciendo el cambio automáticamente.
En esto me puede ayudar algún profesor, pero las funciones lambda no están hechas para definir funciones con nombre, si no más bien ofrecerse como funciones "temporales" en un contexto específico. Por ejemplo, para el key de funciones sort, max, min, y las funciones de manejo de iterables de los contenidos. 
No es un problema demasiado grave en todo caso, es sólo tu linter ayudándote a escribir mejor código. Igual encuentro raro que lo corrija sin preguntarte, probablemente haya alguna opción en preferencias para desactivarlo.

Espero haberte sido de ayuda!
