### ISSUE TITLE
Problema con keypress event y botones

### ISSUE THREAD

**Issue by Ignacio321** [IIC2233/syllabus#463]
Buenas
Mi problema es el siguiente:
Mi ventana mostraba el mapa y el personaje se movia cuando se apretaban las flechas. 
Luego a la ventana le añadi botones y ahora no se mueve, cuando apreto una flecha los botones aparecen como seleccionados, a que se debe esto?

**Comment by Dnpoblete** [comment]
Hola @Ignacio321, creo que no entendí muy bien tu problema, ¿te refieres a que agregaste QPushButton a la ventana del menú que esta en la misma que el mapa y ahora no te sirve usar los botones del teclado con flechas para mover al personaje?

**Comment by Ignacio321** [comment]
Si ese era mi problema, gracias 😄

**Comment by Dnpoblete** [comment]
De nada! 😄
