### ISSUE TITLE
[Tarea] - Contenidos de las tareas

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#463]
¿Que contenidos mide cada tarea? ¿Cómo defino eso? ¿Es más de uno por tarea? ¿Tomo mis propios supuestos?

**Comment by nivek0o0** [comment]
Tengo la misma duda. Si suponemos que las tareas comienzan el jueves o viernes de la semana 1, luego de la primera cátedra, tendrían que ser un total de 6 tareas para abarcar todos los contenidos.
![contenidos tareas](https://cloud.githubusercontent.com/assets/20782451/25913650/e045e1ac-3591-11e7-9fdb-dc709df00918.png)

Pero esto tiene el problema de que la última tarea se pasa de las 12 semanas. ¿Da igual eso?
![carta gantt](https://cloud.githubusercontent.com/assets/20782451/25913678/f672dc6e-3591-11e7-9848-cee3822b6aad.png)

**Comment by yoavnavon** [comment]
Me sumo a la pregunta y agrego otro problema que surge de esto. Si cada tarea abarca dos temas, como se calcula la nota esperada, ya que cada tema tiene sus propios parámetros. ¿Será el promedio entre ambas?

**Comment by benjamimo1** [comment]
Me sumo a la duda jaja

**Comment by Hernan4444** [comment]
En relación a las tareas,  la tabla de @nivek0o0 es la esperado que hagan, cada tarea abarca dos contenidos y  si una tarea se entrega después de la ultima actividad, no importa. Simplemente tendrán una semana donde los alumnos podrán reunirse con el profesor y después tendrán el examen. 

¿Como miden cada tarea según nota esperada y nota obtenida? Queda a su criterio aunque el supuesto de promediar no está nada mal.

Ojalá haya respondido sus dudas.
Saludos!

**Comment by jorgeriesco** [comment]
¿Tenemos que hacer que la primera tarea parta el viernes? ¿Puede ser el día que yo quiera?

**Comment by Hernan4444** [comment]
tiene que ser el día en que los ayudantes se reunen.

**Comment by jorgeriesco** [comment]
¿Los ayudantes se reúnen siempre los mismos días? ¿Puedo hacer que se reúnan en días de la semana que varían a conveniencia?

**Comment by Hernan4444** [comment]
@jorgeriesco no puedes, en el enunciado se especifica que las reuniones son cada 14 días en caso de los tareos. Por lo tanto si tu decides hacer la reunion un lunes, tiene que ser 14 días después, es decir, el subsiguiente lunes,

Saludos!

**Comment by AmbrosioV** [comment]
@Hernan4444  Sobre esto de promediar la nota de la tarea por contenido, ¿cada parte de la tarea (cada contenido) puede tener distinta dificultad? Y se podría subdividir la tarea en preguntas, al estilo del examen y que sean evaluaciones 'distintas' internamente (solo durante un breve periodo, cada una con su dificultad-contenido-nota) pero son solo una nota ya que se promediaran antes de pasarselas al coordinador y a los alumnos

**Comment by Hernan4444** [comment]
@AmbrosioV sorry pero no entendí bien tu pregunta/afirmación. Me da la sensación que preguntas si ¿es valido aplicar otro supuesto? Si esa era tu pregunta, entonces si puedes hacerlo de ese modo mientras lo especifiques en el readme, si no ea esa tu pregunta, por favor ¿puedes redactarla de otra forma?
Saludos!

**Comment by AmbrosioV** [comment]
Ya, era eso mismo de aplicar un supuesto, decidir hacer algo de una manera q no esta explicita como hacerla en el enunciado.
