### ISSUE TITLE
Cuándo volver al menú principal

### ISSUE THREAD

**Issue by cnillanes** [IIC2233/syllabus#463]
Hola!
Me queda una duda con la parte de "una vez resuelta la acción o menú se debe regresar a este menú (principal) a menos que la opcion sea salir"

Cuando estoy en Simular competencia, tengo 2 opciones que queden dias para simular o no. En el primer caso se me hace sencillo visualizar que una vez finalizada la simulación el usuario regresa al menú principal y vuelve a elegir que quiere hacer. Sin embargo, para cuando no me quedan dias de competencia, yo le doy la opcion de volver a simular o salir, tengo que ademas darle la opcion de volver al menu principal (pese a que ya se haya acabado el campeonato)?

**Comment by amparostevens** [comment]
Holaa @cnillanes ! 👋 

Luego de ejecutarse alguno de los siguientes: menú entrenador, simular competencia o mostrar estado, se debe volver a mostrar el menú principal si es que aún quedan días por competir (ya que si no quedan días restantes la competencia, en teoría, ya no puede existir). 

Espero que haya quedado claro!
