### ISSUE TITLE
Importa si es mayuscula/minuscula en los archivos csv al guardar?

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#463]
Lo que tengo ahora crea una clase DCC que convierte los nombres a minusculas y controla todas las operaciones, asi evitando que alguna comparacion de False por la capitalizacion de los caracteres. Mi pregunta es, importan las mayusculas al guardar un/a magizoologo/criatura en el archivo csv?

**Comment by matiasmasjuan** [comment]
Hola @sofiuni !

Me parece muy bien que **implementes** una **función** para poder comparar si dos nombres son iguales o no con el uso de minúsculas y mayúsculas. Sin embargo, debes tener **ojo** que **si** importan las **mayúsculas**  al momento de guardar un/a **Magizoólogo** o **DCCriatura** en sus respectivos archivos csv. Vale decir, una vez **establecido** el nombre de un **Magizoólogo** o una **DCCriatura**, ese nombre **debe** permanecer en el **mismo formato** en el archivo csv.

Espero haber respondido a tu pregunta y mucho éxito con la tarea!

**Comment by sofiuni** [comment]
Oki! Gracias, ya entendi.
