### ISSUE TITLE
Duda cálculo palabras + y - si palabras se repiten en reviews

### ISSUE THREAD

**Issue by Mariana-Ortega-del-Rio** [IIC2233/Syllabus#464]
Hola!
He leído muchas issues sobre palabras contenidas en otras, pero no me queda claro si al calcular el número de palabras positivas o negativas es con o sin repeticiones de la palabra en el review:
Ej: asumamos que "good" es una palabra positiva en mi words.txt
review = "goodgoodahhhhgood good" 
opción 1) 4 palabras positivas
opción 2) 1 palabra positiva

Gracias de antemano!
Saludos

**Comment by Mariana-Ortega-del-Rio** [comment]
La opción 1) parece más razonable, sin embargo te lleva al problema de tener más de un 100% de palabras positivas, ya que las palabras se consideran según si están separadas por un espacio o no.
Entonces, en el ejemplo opción 1) tendríamos un (4/2)*100 = 200% de palabras positivas lo que no es razonable. Como se dijo en la issue #383 no se está buscando que evaluemos léxico. Sería muy complicado en un caso general empezar a separar las palabras de una frase si no es por los espacios.

**Comment by Mariana-Ortega-del-Rio** [comment]
Corrección: Sé que en una issue aclaran que las palabras se consideran como palabras si están separadas por otros símbolos como puntos, signos de preguntas, etc. Pero eso no quita el problema de más del 100% jajaja

**Comment by rihanuch** [comment]
¡Hola @Mariana-Ortega-del-Rio !

Queda a criterio tuyo, solo asegúrate de ponerlo como comentario dentro del código y de tu ```readme.md``` (junto con los otros supuestos que hagas)😉

¡Saludos y éxito!🍀
