### ISSUE TITLE
Duda distribución puntajes threading

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#464]
Hola, me surgió una duda al revisar la distribución de puntajes en la parte:
> Los cultivos se actualizan según su fase de crecimiento. Lo hace con un correcto uso de señales y threading.

En relación a threading esto incluye QTimer o necesariamente se tienen que ocupar QThread para esa parte?

**Comment by Dnpoblete** [comment]
Hola @JuaniAndres esta duda ya fue respondida en la issue #459, para que la revises.

Éxito con la tarea! 🌱
