### ISSUE TITLE
Error al probar contenidos Semana 12

### ISSUE THREAD

**Issue by fplois** [IIC2233/syllabus#464]
hola!, al intentar cargar los contenidos de la semana 12 me arroja el siguiente error:
`[Errno 8] nodename nor servname provided, or not known` y al cambiar el host me arroja este otro error:
`[Errno 49] Can't assign requested address`.

> host = socket.gethostname()

ambos errores me los tira en esta linea del código 

> sock.bind((host, port))

¿Que puede provocarlo?, Gracias.

**Comment by entamburini** [comment]
Hola! :D

Se me haría más fácil probarlo en tu pc para reproducir el error :( pero se me ocurren dos probables causas:

- Estás corriendo las cosas en Jupyter :o si es así, prueba corriendo el código en un archivo .py. 
- Estás usando localhost justo en dicho puerto, en dicho caso tienes que terminar el proceso (busca en google "terminate process occupying port" y pones tu sistema operativo

De todas formas, si compartes el código que tratas de ejecutar, podríamos ver otras alternativas :) 

Avísame en caso de que soluciones tu problema c:

**Comment by fplois** [comment]
hola, disculpa por contestar tan tarde.
Mi error se producer al utilizar el comando "host = socket.gethostname()", lo cambie por "localhost" y funciono, no se si puedo dejarlo así o de que manera puedo asegurarme de que funcione en el caso de que el corrector coloque otro puerto y host.
Saludos y gracias.

**Comment by entamburini** [comment]
Claro que puedes c:
