### ISSUE TITLE
Inconsistencia con test de mismo_mes_candidato

### ISSUE THREAD

**Issue by nicolaslindl** [IIC2233/Syllabus#464]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En la funcion de mismo_mes_candidato, en el enunciado dice que hay que retornar un generador con los id de los animales que cumplan los requisitos, sin embargo en el test, el output esperado es con los nombres de los animales.
Y tambien encuentro que funcionan raro los test con carga de datos, ya que los 3 casos, s, m y l, me devuelven con que ningun animal cumple los requisitos y me sale que esta OK.

**Comment by R3Y3X** [comment]
yo también considero que hay una inconsistencia en el test y es que en el test 8 (Verifica que se retorne los votantes cuando se manejan pequeños datos) me dice que no integro el id  2633 pero este no se debe retornar porque es un candidato que boto por si mismo. en votos .csv el id_voto es : 9372 (linea 9373) en candidatos.csv el id_candidato es  2633 (linea 241) y en animales.csv id es: 2633 (linea 2634)
