### ISSUE TITLE
Progreso en tarea

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#464]
Las distintas áreas de progreso en la tarea dependen del nivel de programación. Como el nivel de programación cambia, me preguntaba si ese progreso se calcula con el nivel de programación al momento de la entrega, el promediado de las dos semanas o si el progreso está referido al progreso diario y no final y por tanto el final es la suma de todos los diarios (de esta forma no habría problema con la variación del nivel de programación). 
Si era una de esas opciones o la idea es que tome el supuesto que yo quiera, por favor decirlo.

Si estaba especificado o implícito en alguna parte, sorry, no lo vi XD.

Gracias.

**Comment by hanavarrete** [comment]
En el enunciado se da a entender que es al momento de entregar. De todas maneras, podrías hacerlo con uno de tus otros supuestos siempre que lo especifiques en el readme. 
Saludos! (inserte label de la vergüenza)

**Comment by acrojas2** [comment]
Hola:
Respecto al progreso de tarea, cuando hacen mención a que si el alumno al momento de entregar tiene un progreso menor al _progreso esperado_  manda un mail pidiendo mas plazo... ¿Cuál es la formula del progreso esperado y en qué momento se calcula?
Respecto a las formulas de progreso, no me queda claro bien que son Ht y Hs, ya que como las definen en la sección 4.1.1 son las hras en total que los alumnos dedican a hacer la tarea y estudiar respectivamente durante la semana, sin embargo en las formulas de progreso por ejemplo, corresponde a las horas dedicadas a hacer esa tarea (donde el plazo es 14 días y el Ht cambia semana a semana), lo que no entiendo es si en la formulas se refieren al Ht acumulado (para el caso de las tareas, es decir, Ht semana pasada + Ht actual (semana entrega)) . Lo mismo con el manejo de contenidos, ya que cada semana el tema de materia es distinto y el me imagino que el manejo de contenidos es del contenido que se trata en la tarea y el también cambia semana a semana.
Saludos! :B

**Comment by Hernan4444** [comment]
> Respecto al progreso de tarea, cuando hacen mención a que si el alumno al momento de entregar tiene un progreso menor al progreso esperado manda un mail pidiendo mas plazo... ¿Cuál es la formula del progreso esperado y en qué momento se calcula?

En la reunión de los ayudantes de tarea se define cual es el progreso mínimo para el 7,0. Ese es el progreso esperado.

Sobre lo otro, tal como dices Ht y Hs son las horas que esa semana el alumno le dedicó a la tarea y a estudiar respectivamente. En caso de las tareas, como son dos semanas el Ht sería el acumulado (cuanto tiempo trabajo la semana 1 mas cuanto tiempo trabajo la semana 2) y sobre el manejo de contenidos queda a tu criterio, Por ejemplo no sería mal supuesto usar un promedio  o crear una pequeña formula que relacione lo avanzado y aprendido en una semana con otra...obviamente mientras esa formula tenga sentido y justifiques cualquiera de los supuestos que decidiste.

Saludos!

**Comment by acrojas2** [comment]
Hola:
Y el Hs de la sección 4.1.3 es distinto del Hs de la sección 4.1.1, ya que el Hs de la sección 4.1.3 dice que son las horas de estudio hasta ese momento, por ende si estamos a jueves y las horas de estudio de la semana son 3, entonces Hs sería 40 (si se considera la definición de la sección 4.1.3) y por otra parte si consideramos la defición de la sección 4.1.1 serían 3 hrs. Mi pregunta es existen dos "Hs" (?) uno correspodiente al total de las horas de estudio de la semana y el otro al tiempo acumulado de estudio hasta el momento (?) ... Espero entiendan mi duda...
Saludos! :B

**Comment by Hernan4444** [comment]
@acrojas2 Hs se define como la cantidad de horas por semana para estudiar y se distribuye de forma uniforme en los 7 días. En la sección 4.1.3 se está haciendo referencia a que tomes una parte de ese Hs, que será los horas de estudio que cada día realizó el alumno hasta el evento. Puedes considera el Hs de la seccion 4.1.3 como un `Hs'` porque es solo una fracción de este.
Espero haber respondido a tu duda.
Saludos!!

**Comment by jorgeriesco** [comment]
@Hernan4444 Todavía no me queda claro si el Hs de la 4.1.3 es acumulado o es el estándar diario que dedica a estudiar. Digo estándar porque no varía en todo el semestre, a excepción de días específicos en que no hace nada por fiestas u otras cosas.

**Comment by Hernan4444** [comment]
En el 4.1.3 es acumulado hasta ese día. Tal vez con un ejemplo se explique mejor:

> Digamos que tienes 7 horas para dedicarle al estudio en una semana (HS de la seccion 4.1.1 = 7), esto implica que será 1 hora diaria de estudio. 

Hasta el momento puedo tener dos supuestos:
A) Las horas las estudio en la noche:

 Esto implica que para la actividad del jueves estudié el lunes, martes y miércoles. Entonces el el Hs de la 4.1.3 será de 3.

B) Las horas las estudio en la mañana:

 Esto implica que antes de la actividad pude estudiar el lunes, martes, miércoles y jueves. Por lo tanto el Hs de la 4.1.3 será 4.

¿Se entendió ahí la diferencia?
Saludos

**Comment by acrojas2** [comment]
@jorgeriesco El Hs según yo si cambia semana a semana ya que en una parte de la seccion 4.1.1 (al final del parrafo 1) dice que la cantidad de horas que le dedican al curso varía semana a semana. Entonces, según yo, cada semana hay que obtener la cantidad de horas que el alumno dedicará al curso según la cantidad de créditos que tenga. Lo que no cambia es la proporción (el 70% y el 30% ). 
Saludos :B !

**Comment by TomasSalvadores** [comment]
Pero tal y como lo expones aqui:
> En la reunión de los ayudantes de tarea se define cual es el progreso mínimo para el 7,0. Ese es el progreso esperado.

Los alumnos mandarían el mail siempre que no se vayan a sacar un 7.0, lo que es poco realista.
Además en el enunciado se da a entender que los alumnos no manejan información sobre su progreso, solo estiman su desempeño con la "Nota esperada".
Dado esto, podemos hacer que manden el mail en función de su nota esperada y si es que esperan un rojo (por ejemplo), especificando todo en el readme? Esto haría que la simulación sea algo mas realista.

**Comment by Hernan4444** [comment]
@TomasSalvadores recordemos que este curso es de una dimensión paralela y por lo tanto lo realista aquí puede ser distinto a lo realista en esa dimensión.
Sin embargo si con esa suposición haces la simulación mas realista según tu criterio, estás totalmente autorizado para hacerlo mientras especifiques en el Readme cual fue el cambio y la razón. 

Saludos!
