### ISSUE TITLE
Mostrar al usuario perdidas de energía y estado de sickles

### ISSUE THREAD

**Issue by rldelafuente** [IIC2233/syllabus#464]
Hola!
¿Es necesario mostrarle si fue atacado o no? En otras palabras, ¿hay que "printear" si ocurre un ataque por alimentar a una criatura? 

Lo mismo va para cuando se gasta sickles, ¿hay que ir indicando cuánto tiene?

Gracias!

**Comment by matiasmasjuan** [comment]
Hola @rldelafuente !

Si bien es cierto que en el enunciado **no** se **especifica** que haya que *printear* este tipo de **eventos**, ya sea el **ataque por alimentar a una DCCriatura**, o cuando uno **gasta** ***SICKLES***, **si** se **explicita** que deba **notificarse** cuando un **Magizoólogo** no tiene **energía** suficiente para realizar alguna acción o si no tiene suficientes ***SICKLES*** para comprar un alimento o una **DCCriatura**.

Si te fijas en la ***Distribución de Puntajes de la T01***, se evalúan los casos en donde se **descuenten los costos** correctamente tanto de **energía mágica** como de ***SICKLES***, **notificando** cuando no se puedan ejercer estas acciones. Por lo tanto, es **esperable** que tu **programa** **notifique**  y ***printee*** cuándo se está **realizando** algún evento. Lo mismo pasa en el caso si es que el **Magizoólogo** fue atacado cuando alimentaba a una **DCCriatura**. La idea **siempre** es poder **interactuar** con el **programa** y que te notifiquen (*printeen*) cuándo ocurren los eventos.

Trata de pensar que estos **mecanismos** de ***printeo*** **demuestran** que **efectivamente** están **funcionando** los eventos que defines. Por ejemplo el caso de gastar *SICKLES*; si compras algún **alimento** y se hace un correcto **descuento** en la cantidad de *SICKLES* que te quedan, esto indica que tu programa está funcionando bien. Lo mismo ocurre al momento de notificar si el **Magizoólogo** fue atacado; sería **correcto** indicar si es que **fue** atacado, cuánto fue el descuento en **energía** y cuánta **energía restante** posee.

Espero haber respondido a tu pregunta, y mucho éxito con tu tarea 😄
