### ISSUE TITLE
AF5 Duda sobre ingredientes_infectados

### ISSUE THREAD

**Issue by Piolawa** [IIC2233/syllabus#464]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
Hola!, 
Para saber si un ingrediente está infectado, cual condición debe cumplir? 
1) probabilidad_ingrediente < PROBABILIDAD_INFECCION
2) probabilidad_ingrediente = PROBABILIDAD_INFECCION
3) pobabilidad_ingrediente > PROBABILIDAD_INFECCION 

Es que al principio entendí que solo en el caso que sean iguales ambos valores el ingrediente estaba infectado, pero encontré que era muy baja la probabilidad.

**Comment by tqmbanados** [comment]
Hola! Esta respuesta va en general para siempre que se calculen probabilidades, así que agregaré el Label General.

Respuesta corta: debes calcular la probabilidad de que un número aleatorio sea *menor* a la probabilidad dada .

La probabilidad en decimales siempre representa un *porcentaje de acierto*, es decir, 0,2 es 20%, 0,76 es 76%, 1 es 100%, y así. Es decir, si un evento ocurre con una probabilidad de 0.2, ocurrirá (teóricamente) el 20% de las veces que se "pruebe" ese evento. Me imagino que esto ya es conocimiento general en este curso, pero por si alguien es de otra carrera o no entiende mucho de probabilidades es importante que sepan lo básico.

Entonces, si el parámetro PROBABILIDAD es ```0.2```, queremos hacer un condicional (```if expresión is True:```) que sea True el 20% de las veces. Para esto sirve mucho la librería ```random```, que tiene varias funciones como ```uniform()``` o ```random()``` que nos permiten generar números racionales (de tipo ```float```) aleatoriamente. Entonces, si generamos un número entre 0 y 1 al azar, es natural que el 20% de las veces sea **menor** a 0.2. Por lo que ahí tenemos nuestra respuesta, una expresión que es ```True``` el 20% de las veces sería: ```numero_aleatorio <= 0.2```, donde ```numero_aleatorio``` es un numero entre 0 y 1 que se genera al azar con cada prueba. 

Para futuro, siempre que veas una probabilidad en una tarea, actividad, u otra instancia, siempre representa el *valor máximo* que puede tener un número aleatorio entre 0 y 1 para que la condición sea ```True```. Dependiendo del caso, puede ser importante si es ```<``` o ```<=```, pero con números aleatorios de muchos decimales la diferencia es prácticamente cero. 

Sobre esto último, surge este "problema":  Si usamos siempre ```<=```, es imposible definir una probabilidad ```0```, pues un número aleatorio entre 0 y 1 *podría* ser 0. Por el otro lado, si usamos siempre ```<```, es imposible definir una probabilidad ```1```, pues este número aleatorio *podría* ser 1. Me imagino que las personas que estudian probabilidad tienen una respuesta más clara para esto, así que si alguien más se anima con darla sería un buen aporte! De todas maneras, son detalles prácticamente insignificantes :cat:

**Comment by Piolawa** [comment]
Gracias!
