### ISSUE TITLE
sprites cultivos choclo

### ISSUE THREAD

**Issue by vnespinosa** [IIC2233/syllabus#465]
Hola, puede ser que los sprites de nivel 6 y 7 del choclo están cambiados?
Por que el nivel 6 tiene choclos, pero el 7 no.
Si es así, es importante que arreglemos este error? o puedo usar de todas formas el sprite 7 para el nivel 7 y el 6 para el 6?

**Comment by Dnpoblete** [comment]
Hola @vnespinosa están en ese orden debido a que antes de que salgan choclos la planta no tiene la flor de arriba, la sprite 7 sería luego de que ya se cosecho choclo una vez de esa planta, recuerda que el choclo es una planta de crecimiento permanente. De todos modos en el enunciado se muestra la imagen con el proceso de crecimiento, la idea es luego de que se cosechen choclos puedan volver a crecer e intercales la imagen 6 y 7 según si tiene choclo o no. Talvez en el enunciado queda mal explicado pero luego de que coseches debes ir a la sprite 7 y cuando aparezcan choclos a la 6. No te recomiendo cambiar el orden de las sprites, ya que al revisar la tarea usaremos la que esta en github.

Éxito con la tarea! 🌽
