### ISSUE TITLE
Orden a mostrar eventos del día

### ISSUE THREAD

**Issue by milosoria** [IIC2233/syllabus#465]
Es posible mostrar los eventos en un orden distinto a: 

> Mostrar las criaturas que se enfermaron, las criaturas que se escaparon y las criaturas que pasaron a estar hambrientas.
 Además, se debe mencionar qué criaturas perdieron puntos de salud por estar enfermas o hambrientas. ?

Por ejemplo:
> Nifflenzini perdió salud por enfermedad :(
Augurinto perdió salud por hambre :(
Criaturas que enfermaron: Nifflenzini
Criaturas que escaparon:
Criaturas hambrientas: Augurinto

**Comment by aljara97** [comment]
Hola @milosoria!

El orden sugerido de cómo debes mostrar los eventos en la opción **pasar de día** es solo una sugerencia para que tengan claridad de cómo implementarlo. Cualquier orden que implementes es válido mientras muestres los eventos requeridos en el enunciado. Y sí, debes mencionar las criaturas que perdieron puntos de salud, ya sea por estar enfermas o por estar hambrientas.

Quedo atento si tienes más dudas 🧙

**Comment by milosoria** [comment]
Perfecto! Lo último, en criaturas que se escaparon o enfermas, debo solo incluir aquellas que lo hicieron ese día o todas las que están en ese estado?

**Comment by aljara97** [comment]
Solo debes mostrar las que se escaparon o enfermaron ese día, ya que esta función muestra un resumen de los eventos ocurridos al inicio del día
