### ISSUE TITLE
Imágenes Tablero

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#465]
hola, en caso de que quisiera utilizar imágenes para realizar el tablero esta pueden estar en la carpeta client o necesariamente tienen que estar en la carpeta server y ser mandadas a los clientes para poder utilizarlas?

**Comment by iqacevedo** [comment]
Hola!

Si son imágenes solo para poner fondos a la interfaz gráfica (o dejarla más bonita), deberían estar en el cliente.

**Comment by jalliende** [comment]
y en cuanto al tablero este tiene puntaje por ser "bonito"? es decir ser como los que aparecen como ejemplo en el enunciado o por ejemplo podría ser un tablero como este por ejemplo:

**Comment by iqacevedo** [comment]
@jalliende no tiene puntaje por ser bonito. Si implementas algo como lo que dices en una interfaz, es funcional y cumple con lo que pedimos, entonces estará bueno.
