### ISSUE TITLE
Parámetros

### ISSUE THREAD

**Issue by nicolascamhi** [IIC2233/syllabus#465]
Todos los números en celeste del enunciado deben ir parametrizados?? Por ejemplo el de las función sanar lesiones también??

**Comment by amparostevens** [comment]
Holaa! 
Sí, eso es correcto. Recuerda ponerles nombres descriptivos para saber a lo que se refieren. 

Éxito con la tarea🌟

**Comment by YehudaGurovich** [comment]
Alguna idea de que nombre colocarle a las variables asociadas a los numeros en la función de sanar lesiones? Pq son como numeros random...

**Comment by amparostevens** [comment]
Se me ocurre ponerle nombres como _denominador sanar lesiones_ para `200`, _probabilidad mínima sanar_ para `0`, etc..
La idea es que se sepa para lo que se estarían usando y que el código sea más facil de entender y modificar, tanto para ti como otra persona que lo vea luego.
