### ISSUE TITLE
best comments, popularidad

### ISSUE THREAD

**Issue by fpattillo** [IIC2233/Syllabus#465]
Hola!
"n películas con más comentarios positivos/negativos" se refiere a la cantidad neta de comentarios o la popularidad mencionada en 2.2.1? Ejemplo: si una película tiene 10 positivos y 20 negativos, es decir, popularidad negativa, y luego otra tiene 8 positivos y 0 negativos, la primera debería ir al comienzo?

**Comment by Arcoirisky** [comment]
Se refiere a que las primeras n-k películas deben ser consideradas con popularidad positiva (Desde la más positiva a la menos pos), mientras las ultimas k son las negativas (desde las menos neg hasta las más negativas). En tu ejemplo, la segunda debería ir primero porque la primera es más negativa que la segunda. ¿Se entiende? O:

**Comment by Pipelao** [comment]
Hola @Arcoirisky 
Lo que yo había entendido es que se retorna por la cantidad de positivos, entonces tengo que hacer una balance para la película de cuántos comentarios positivos/negativos/neutros tiene? Creo que en una issue leí que sería algo como si el comentario es positivo se suma uno, si es negativo se resta 1 y si es neutro se suma cero, ¿esto debo hacer?
