### ISSUE TITLE
[AF5] Duda de escribir_receta y capa_relleno

### ISSUE THREAD

**Issue by isinahum** [IIC2233/syllabus#465]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Tengo una duda de capa_relleno y escribir_receta. Se supone que al escribir una receta, no debo incluir los rellenos? Porque de la forma que está escrito el codigo de escribir_receta de la forma  archivo.write(f"{receta},{','.join(receta[1::2])}\n"), esta se salta la parte del relleno. Debemos modificar esto para que incluya el relleno?

**Comment by tqmbanados** [comment]
Hola! La receta final **no** incluye los rellenos. No te preocupes por eso en todo caso, es algo que está en el código dado para que las recetas mantengan el mismo formato. Pero por lo mismo, debes siempre usar la Torta con el relleno *incluido* en su lista de ingredientes! El método se encargará de escribir la receta correctamente :)
