### ISSUE TITLE
formato hora en clientes_despues_hora

### ISSUE THREAD

**Issue by bernarditaaliaga** [IIC2233/Syllabus#465]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/Syllabus/issues/420).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Mi duda es sobre el formato entregado de 'hora' en el argumento entregado, yo se que el enunciado especifica que este sera de la forma 'HH' sin embargo cuando lo convierto a int(), arroja un valueError y dice que estoy intentando convertir a int algo de la forma 'HH:MM' , acabó va un ejemplo de lo que arroja mi terminal 'ValueError: invalid literal for int() with base 10: '23:55'', esto lo corrijo fácilmente con slicing, sin embargo me es importante para la lógica de la funcion, pues si el formato incluye los minutos, debo tomar en cuenta que no tengo que considerar pedidos cuya hora sea la misma pero haya sido en minutos antes.

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by FradexMF** [comment]
Hola! Este problema ya fue contestado en la issue #425.
