### ISSUE TITLE
Problema con genomas.txt de la carpeta test_1

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#466]
Con el archivo genomas.txt chico todo lo que porgramé me funciona perfecto.
Con el archivo genoma.txt grande (el que está en la carpeta test_1) no puedo hacer nada, porque para la primera cosa que hacen todas mis funciones, que es reconocer el nombre de la persona que busco en el archivo genomas.txt, me levanta la excepción GenomeError que dice que hay un error en el genoma.

Me di cuenta de que esto ocurre en genomas.txt grande porque en "5Jesús10De NazaretAA..." cuando estoy recorriendo las letras, al llegar al "1", mi función levantadora de la excepción hace "if not '1'.isdigit()", y entra al if, es decir, ese "1" NO es un dígito. Por eso, al entrar al if se levanta la excepción. 

No sé por qué '1'.isdigit() retorna False, porque lo normal sería que retornara True. En el archivo genomas.txt chico sí me retorna True como debería ser, por lo que no tengo problemas. Pero en el archivo genomas.txt grande pasa esto que es muy raro y por eso no es posible hacer nada con ese archivo... Me di cuenta de que no puedo hacer nada útil con ese archivo porque como en main.py se manejan las excepciones, puedo ver en la interfaz que para todas mis consultas ocurre el mismo error (es decir, el error se repite para todas las personas).

¿Hay un problema en genomas.txt grande?

**Comment by naazocar** [comment]
Yo también lo hice con .isdigit() y no tengo problemas con ninguno de los dos archivos :/ Quizás hay algo mal en el algoritmo. También podría ser que estés usando el archivo 'listas.txt' del genoma viejo, o algo por el estilo

**Comment by mjgutierrez1** [comment]
@naazocar  mmm no creo que tenga que ver con 'listas.txt' porque como dije el error ocurre mientras el programa está leyendo los nombres de cada persona (es decir, antes de que empiece a leer la parte donde salen los tags de características con los ids de listas). Y quizás estaba usando el viejo, pero no creo porque si no me equivoco hice "git pull" el viernes, porque estaba teniendo problemas con los archivos de que tenía antes (que efectivamente eran los viejos).

**Comment by naazocar** [comment]
Aah... Sí, si lo decía en caso de que leyeras todo junto (mi caso), pero si no, de repente podría ser un error de posición o algo. ¿Lo pudiste solucionar al final?
