### ISSUE TITLE
Duda sobre errores en los test 

### ISSUE THREAD

**Issue by Yeps3nM** [IIC2233/Syllabus#466]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo una duda porque cuando corro desde los test individuales el cargar datos no me sale ningún error sin embargo cuando corro el archivo de todos los test si me da error en dos test cases. Ya tengo actualizado el repositorio en mi perfil por si pudieran mirarlo.  ¿Y lo otro de que tenía la duda, es de si incluso con los cambios constantes que han hecho a la tarea mantendrán la fecha de entrega?

Gracias de antemano

**Comment by Segismundios** [comment]
Hola @Yeps3nM, probé los tests en tu tarea y me aparecen correctos todos los tests de cargas de datos, incluso ejecutando todos los tests. Podrías revisar si tus archivos de tests y data están actualizados.  Si te siguen arrojando error podrías indicarme qué tests específicamente te están fallando, indicando qué errores en particular. 
En relación a tu consulta por el plazo de entrega, consulté con los profesores y me indican que las fechas se mantienen. De todas formas, recordarte que este tipo de preguntas administrativas se deben hacer vía email a Coordinacion.iic2233@gmail.com.

Quedo atento a tu respuesta, saludos!
