### ISSUE TITLE
Formato Tarea 3

### ISSUE THREAD

**Issue by sunrayito** [IIC2233/Syllabus#466]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hay que utilizar el formato PEP8 en la tarea? (considerando que se va a corregir de forma automatizada) Puedo pasarme de las 400 líneas en el archivo principal de la tarea o se espera que lo haga en diferentes módulos de todas maneras?

**Comment by AlonsoPlaza** [comment]
Hola, si hay que respetar PEP8 en la tarea y no puedes pasarte de las 400 líneas. Todos los descuentos que aplican para esta tarea están especificados en la hoja de distribución de puntaje mencionada en el enunciado.
