### ISSUE TITLE
Comentarios positivos-negativos

### ISSUE THREAD

**Issue by dnalfaro** [IIC2233/Syllabus#466]
Al contar las palabras positivas y negativas de los reviews, se puede dar el caso de una palabra como selfishappy que sería positiva y negativa a la vez?. Si se puede dar el caso, ¿cómo la considero?, ya que si la considero tanto neg como pos, podrían darse comentarios que tienen porcentaje sobre 100% al sumar pos% + neg% y eso no permitiría calificar el review.

**Comment by Arcoirisky** [comment]
Queda a tu criterio como la consideras. Positiva, Negativa, Neutra (en caso de que la cant de neg y pos sea igual) o como prefieras, pero especifíca tu elección en el README O:!!!
