### ISSUE TITLE
uso de '\chao' en la partida

### ISSUE THREAD

**Issue by Oisangui** [IIC2233/syllabus#466]
Se puede usar el comando \chao en el chat en medio de la partida o solo en la sala de espera?

**Comment by gatochico** [comment]
Hola! Como debe seguir existiendo un chat durante la partida, si debe ser posible utilizar **/chao** durante esta. Exito!

**Comment by Oisangui** [comment]
Ok, pero si se usa \chao el afectado es echado de la partida o solo se le deshabilita el chat? De ser expulsado de la partida, sus lineas quedan en juego? y sus cuadrados marcados?

**Comment by gatochico** [comment]
Al usar **\chao**, se debe expulsar al usuario de la partida. Ahora, con respecto a sus líneas y cuadrados, queda a tu criterio el mantenerlos en el tablero o quitarlos una vez sea expulsado (Aunque te recomendamos el dejarlos, ya que es más facil de programar). Sea la decisión que tomes, no olvides dejarla en tu README!
