### ISSUE TITLE
¿Cómo funcionan las properties?

### ISSUE THREAD

**Issue by clangoi** [IIC2233/syllabus#466]
No tengo muy claro como usar properties , ya lei el material subido y ya busque en google, pero sigo sin comprender, mas allá de seguir la estructura base y que funcione en algo (para la actividad por ejemplo), no entiendo como funciona en realidad y en tanto como usarlas para mi tarea. Por favor ayuda :cc

**Comment by retamalcito** [comment]
¡Hola @clangoi!

Imagina que estás jugando con tu Pokémon favorito, y la estás pasando tan bien, que decides modelarlo a través de POO. Entonces, comienzas a investigar qué atributos tendría que tener tu clase, y observas atentamente la interfaz del juego:

![image](https://user-images.githubusercontent.com/62028973/92659336-8f533080-f2ce-11ea-98aa-923fd08fb540.png)

De inmediato notas algunos de los atributos necesarios: `nombre`, `nivel` y `hp`. Por lo tanto, creas la siguiente clase:

```python
class Pokemon:
    def __init__(self, nombre, nivel, hp):
        self.nombre = nombre
        self.nivel = int(nivel)
        self.hp_actual = int(hp)
        self.hp_max = int(hp)
```

Pero luego de crear tu clase, notas que algo no está bien. Miras atentamente el juego hasta que te das cuenta. El atributo `self.hp` tiene **límites**. ¿Qué pasaría si tu Pokémon tiene 1 punto de salud, pero recibe un ataque que realiza 5 puntos de daño? Es lógico que no puede quedar con -4 puntos de salud; tiene que quedar con **0**.
Lo mismo ocurre en el otro sentido. ¿Qué pasaría si tu Pokémon tiene 25 puntos de salud (con un máximo de 26, como en la imagen) y le das un objeto curativo que hace que gane 20 puntos de salud adicionales? Tu Pokémon tampoco puede quedar con 45 puntos de salud, ya que se pasaría de la barra; debe quedar con **el máximo** (`self.hp_max`), en este caso, 26.

En estos casos es cuando usamos `properties`. Puedes imaginar una `property` como una especie de "filtro", que hace que cada vez que se cambie el valor de un atributo, se revise si este nuevo valor se encuentra dentro del un rango establecido. En caso de encontrarse dentro del rango, permite el cambio, pero si el nuevo valor se sale del rango, lo iguala al límite más cercano. Veamos esto con el ejemplo.

Decides reescribir tu clase para utilizar el poder de las `properties` a tu favor. Entonces, obtienes lo siguiente:

```python
class Pokemon:
    def __init__(self, nombre, nivel, hp):
        self.nombre = nombre
        self.nivel = int(nivel)
        self.__hp_actual = int(hp)
        self.hp_max = int(hp)
```

El único cambio que se realizó respecto de lo anterior es que se cambió el nombre del atributo `self.hp_actual` por `self.__hp_actual`. Hicimos esto porque queremos que nuestro atributo sea **privado**, es decir, no queremos que otras funciones externas tengan acceso directamente a él, ya que podrían modificarlo saltándose el "filtro" que implementaremos (**OJO**: En Python no existen realmente los atributos privatos, pero como convención, si se le coloca uno o dos **guiones bajos** a un atributo al inicio de su nombre, es porque queremos que sea tratado como un atributo privado).
Al definir nuestro atributo como privado, tenemos un nuevo problema, ¿cómo accederemos al éste? Para esto, utilizamos el `getter` de nuestra `property`, el cual implementamos de la siguiente forma:

```python
@property
def hp_actual(self):
    return self.__hp_actual
```

Como se puede ver, es una función que lo único que hace es retornar el valor de nuestro atributo. Hacemos esto para tener acceso a un atributo al que de otra forma no podríamos acceder.

Ahora viene la parte más importante: definir los **límites** que queremos que tenga nuestro atributo. Para hacer esto, utilizamos el `setter` de nuestra `property`, el cual se implementa de la siguiente forma:

```python
@hp_actual.setter
def hp_actual(self, nuevo_hp):
    if nuevo_hp < 0:
        self.hp_actual = 0
    elif nuevo_hp > self.hp_max:
        self.hp_actual = self.hp_max
    else:
        self.hp_actual = nuevo_hp
```

Veamos qué es lo que ocurre aquí. Se puede ver que el `setter` recibe un parámetro llamado `nuevo_hp`. Este parámetro corresponde al nuevo valor que se le quiere asignar a nuestro atributo. Sin embargo, como es claro, la asignación no ocurre inmediatamente, sino que **se revisa que se encuentre dentro del rango** antes de hacerla.
Primero, se verifica que la nueva salud no sea menor a 0; en caso que lo sea, se asigna el valor 0, ya que este es el mínimo valor que pueden tomar los puntos de salud.
Luego, se verifica que no sea mayor a los puntos de salud máximos (`self.hp_max`) que puede tener nuestro Pokémon, y en caso de serlo, se asigna el mismo valor que `self.hp_max`, ya que este el el valor más grande que puede tomar nuestro atributo.
Finalmente, si no se cumplieron ninguna de las condiciones anteriores (es decir, el valor de `nuevo_hp` se encuentra dentro del rango que queremos), permite realizar la asignación (`self.hp_actual = nuevo_hp`).

¡Lo logramos! Ahora, cada vez que se intente cambiar el valor de `self.hp_actual`, se pasará por nuestra `property` primero, lo que nos asegura que el valor de nuestro atributo **siempre** se encontrará dentro del rango que queríamos. Como un detalle, ahora siempre tendremos que referenciar nuestro atributo como `self.hp_actual` en lugar de `self.__hp_actual`, ya que de otra forma no pasará por el filtro y nos meteremos en problemas.

¡Ahora podrás continuar modelando a tu Pokémon sin problemas!

![image](https://user-images.githubusercontent.com/62028973/92663478-cc6ff080-f2d7-11ea-8ecd-65b12caf1a6e.png)

Ahora puedes extender el concepto de `properties` a otras cosas. ¿Qué atributos de mi clase tienen límites? 🤔 Por ejemplo, no pueden haber más de 120 personas en una sala de esa capacidad, no se puede tener una cantidad negativa de dinero, no se puede tener una temperatura menor al 0 absoluto, etc.

Ojalá te haya servido mi explicación, intenté no ser tan formal con los conceptos para facilitar la comprensión. Si tienes alguna pregunta, ¡no dudes en hacerla! ✨

**Comment by clangoi** [comment]
Estuvo muy claro, creo que ya entendí, muuuuuchas gracias 🙌🏻

**Comment by clangoi** [comment]
Holaaa de nuevo, en esta parte :
> 
> ```python
> @hp_actual.setter
> def hp_actual(self, nuevo_hp):
>     if nuevo_hp < 0:
>         self.hp_actual = 0
>     elif nuevo_hp > self.hp_max:
>         self.hp_actual = self.hp_max
>     else:
>         self.hp_actual = nuevo_hp
> ```

self.hp_actual no deberia estar con doble underscore inicial? si lo estoy aplicando bien, de lo contrario me tira recursion y creo que es porque vuelve a llamarse a si misma la funcion

**Comment by retamalcito** [comment]
¡Hola de nuevo!

Tienes toda la razón, cometí un error al implementar el `setter` 🙈. Como dices, las líneas en las que se realizan las asignaciones deberían hacerse con `self.__hp_actual`, no con `self.hp_actual`. Lo corregiré por si algún compañero tuyo necesitara esta issue.

En todo caso, te felicito por haber encontrado el error, ¡significa que estás aprendiendo!

¡Saludos! 👋
