### ISSUE TITLE
Pregunta Threads daemon

### ISSUE THREAD

**Issue by jnlarrain** [IIC2233/Syllabus#466]
Segun el contenido y lo visto en ayudantia, los Threads daemon deberian tener menor prioridad que un non-daemon y terminar cuando termina el programa, sin embargo cuando ejecuto el siguiente codigo en mi computador, tanto en pycharm como en la idle original, los threads daemon como los non-daemon dan el mismo output al levantar un error.

¿Esto depende de mi computador (numero de  nucleos)?¿Se puede controlar?¿O hay un error?¿O los Threads no terminan cuando hay error?

--------------------------------------------------
```python
import threading
import time


def a():
    print("hola")
    time.sleep(2)
    print("chao")

t1 = threading.Thread(name='non-daemon', target=a, daemon= True)

t1.start()
raise ValueError
```
--------------------------------------
```python
holaTraceback (most recent call last):
  File "C:/Users/ejemplo.py", line 14, in <module>
    raise ValueError
ValueError
 chao
```

**Comment by fvr1** [comment]
Hay algo extraño.. el `raise ValueError` (ese que va antes del Traceback) es parte de tu código?

**Comment by jnlarrain** [comment]
@fvr1 si lo puse para saber cual era el comportamiento al levantar errores, el output es lo que esta despues de la linea

**Comment by fvr1** [comment]
Ahh, creo que no entendí la pregunta.  ¿Te pasa que no se llega a imprimir el `chao`? ¿O que siendo el thread `daemon` o no igual se imprime?

**Comment by jnlarrain** [comment]
siendo que el thread es daemon se imprime igua

**Comment by andresfdezc** [comment]
Hemos probado en distintos sistemas operativos y nos ha funcionado como debiese. ¿Puedes darnos más información sobre dónde y cómo lo estás probando (sistema operativo, versión de python, etc)?

**Comment by jnlarrain** [comment]
Lo estoy probando en windows 10, en la idle de python 3.5 de 64 bits y en pycharm, obteniendo el mismo resultado en ambos

**Comment by iqacevedo** [comment]
Hola !
Has intentado probar abriendo el archivo desde la consola (una vez te encuentres en la ubicación del archivo) escribiendo `python ejemplo.py`?
Podrías ver si te ocurre el mismo error?

**Comment by andresfdezc** [comment]
Probaré. Puedes probar en consola por mientras lo siguiente para saber que versión estás usando:

```bash
python --version
```

**Comment by jnlarrain** [comment]
@iqacevedo tienes razon por cmd corre como corresponde, se que en las notas sale que depende de la idle si ejecuta igual el daemon, pero no considere que el cmd cambiara las cosas, muchas gracias
