### ISSUE TITLE
Cantidad de elementos inventario inicio

### ISSUE THREAD

**Issue by pwillmer** [IIC2233/syllabus#466]
Hola! 
Asumimos que en un comienzo la persona tiene 0 elementos de cada tipo en el inventario?

**Comment by Dnpoblete** [comment]
Hola @pwillmer si es totalmente válido, ya que no está explicitado en el enunciado queda a tu criterio, pero igual sería bueno que lo pongas en el item de supuestos en el ReadMe.

Éxito con la tarea! 🌱 😄

**Comment by pwillmer** [comment]
Gracias

**Comment by Dnpoblete** [comment]
De nada 😄
