### ISSUE TITLE
comunicacion cliente -> front-end en ayudantia 2018-2

### ISSUE THREAD

**Issue by fediaz3** [IIC2233/syllabus#467]
Hola!
Tengo una duda de la ayudantía recomendada para la T03
En el código, se llama directamente un método del front-end, ya que lo tenemos como atributo
lo que entiendo, pero conceptualmente tengo una duda.
mi pregunta es:
¿Esto va encontra de la comunicación front-end y back-end que debe ser solo mediante señales?
 ¿ Debería haber creado una señal, conectarla y emitirla, envés de simplemente llamar al método?

Abajo está el código resumido
Gracias :D

~~~
class Cliente:
    def __init__(self):
       ...
       ...
       ...
        self.frontend = VentanaPrincipal(self) 
        self.frontend.show()      #abajo, llama directamente al metodo del frontend
                                             # sin usar una señal, es correcto?
~~~

~~~
    def manejar_comando(self, diccionario):
        ...
        ...
        ...
        self.frontend.ventana_chat.actualizar_chat(f"{usuario}: {contenido}")  
        #se ejecuta un método directamente del front-end
        #pregunta: debería haber una conexión -> emitir una señal al front-end y con eso 
        #ejecutar el método?

**Comment by KnowYourselves** [comment]
Hola @fediaz3!

Siendo breve, la respuesta tus dos preguntas es: Si!, de hecho ese es el problema de esa ayudantía, que fue realizada sin señales (de hecho eso sale en el footnote donde se recomienda 👀). Lo correcto sería conectar señales y emitirlas para evitar modelación circular como se hizo en la tarea 2.

Espero haberte ayudado!

**Comment by fediaz3** [comment]
No me había dado cuenta de la nota 😅
Gracias!

**Comment by benjaurr** [comment]
Hola, me queda una duda con esto.
En este caso no se consideraría modelación circular, cierto? (Solamente que lo correcto sería conectar los metodos mediante señales)

**Comment by Hernan4444** [comment]
Hola, 

Si se considera, porque se esa ayudantía se está pasando el parent a otra clase hija para conectar las señales. Deben hacerlo de tal forma que no se tenga que pasar el parent y ahí dejará de ser modelación circular.

Saludos ✌️

**Comment by benjaurr** [comment]
Gracias! Pero la verdad no me queda muy claro. Si yo estoy instanciando en mi cliente el frontend, y le paso como atributo a el mismo en el init (self), si sería modelación circular. Pero si no le paso el atributo self, y desde la clase cliente conecto las señales, utilizando, por ejemplo:
`self.frontend.senal.connect(self.metodo)`
Sería considerado modelacion circular? Ahi en el frontend no habría ningun atributo ni instancia del cliente

**Comment by Hernan4444** [comment]
Hola

Ahí ya no es, solo que así no lo habíamos pasado el semestre pasado 😅. Pero si lo cambiaste a como señalas, está perfecto 👍  (no es modelación circular)

Saludos

**Comment by benjaurr** [comment]
Muchas gracias!

**Comment by benjaurr** [comment]
Muchas gracias!
Tengo una última duda. Es considerado incorrecto el self.frontend.show() hecho desde el cliente? (O sea, que se debería hacer mediante una señal, en vez de ocupar el método directamente)
