### ISSUE TITLE
test2 correctitud

### ISSUE THREAD

**Issue by vhernnda** [IIC2233/Syllabus#467]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Para el test 2 me sale todo bueno excepto test 3 de correctitud, he reescrito varias veces el codigo probando distintas maneras de calcular el valor, sin embargo todas me dan el mismo valor por lo que me gustaria saber si es que existe la posibilidad de que el test mencionado este malo

**Comment by Vicente1824** [comment]
¡Hola @vhernnda 🫡! Solo para verificar, ¿te refieres al test 3 del archivo `test_02_cantidad_vendida_de_pizza_por_tipo_correctitud.py`? Acabo de revisarlo y todo pareciera estar bien. En este test, hay 4 pedidos que en total suman 2413 pizzas del tipo `Pepperoni Falsa`. ¿Estás seguro/a de que todo se está calculando bien? ¡Recuerda revisar la lógica de tu código y revisar qué va ocurriendo! Me avisas si necesitas ayuda con alguna otra cosa.

**Comment by vhernnda** [comment]
todo claro
