### ISSUE TITLE
DCCriaturas: Escaparse y enfermarse

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2233/syllabus#467]
Hola! Estoy teniendo problemas entendiendo el enunciado 😅 No entiendo si se debería llamar al método 'enfermarse' o 'escaparse' de DCCriaturas en el inicio de un día o en otro momento. Gracias de antemano 😄

**Comment by Dnpoblete** [comment]
Hola @beatrizacuna, en la sección de pasar al día siguiente del enunciado dice lo siguiente:

![image](https://user-images.githubusercontent.com/42362982/79182997-414d0600-7dde-11ea-8ab4-62df197b0b37.png)

Por lo que deberás ver según la probabilidad correspondiente de ambos eventos sí alguna criatura se enferma y/o otra escapa, ya que podrían ocurrir ambas, ninguna o solo una, dependiendo de lo que diga la probabilidad de ese día.

Adicionalmente, deberás mostrar lo ocurrido como se dice en el enunciado:

![image](https://user-images.githubusercontent.com/42362982/79183165-b587a980-7dde-11ea-81e2-9e87fd25dfb3.png)

Espero haber respondido tu duda y éxito con la tarea ✨
