### ISSUE TITLE
Duda con la función cargar_datos

### ISSUE THREAD

**Issue by MrFoxley** [IIC2233/Syllabus#467]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
Hola, tengo una duda respecto a la función cargar_datos, no me quedó claro si está permitido o no que cree una lista para resolverla (o use también archivo.readlines() ), ya que cuando se explica que está prohibido crear una lista no especifica si es para todas las funciones que hay que modificar o si hay una excepción con las funciones generadoras. Por favor ayúdenme con esto , no quiero arriesgar tener un 1.0 de nota.
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by diegobas10** [comment]
Hola buenas @MrFoxley,
A la hora de cargar funciones si puedes hacer uso de los comandos que acabas de decir, ya que solo está prohibido para las consultas esto se menciona en los comentarios de la issue #298 y #304
Saludos y suerte con todo!
