### ISSUE TITLE
Ayudantias T04

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2233/Syllabus#467]
El enunciado dice que se toman a dos ayudantes y les obliga a hacer la ayudantia, pero ¿Son dos ayudantes por sección? o ¿La mitad de alumnos se van con uno y la otra con otro?

**Comment by akaminetzkyp** [comment]
Yo creo que es como es en la realidad. Dos ayudantes en total.

**Comment by Arcoirisky** [comment]
Entonces la gente se divide o:!

**Comment by sebacruzd** [comment]
Hola,
Queda a su criterio. Puede ser de ambas maneras, pero recuerden especificarlo en el README.md!
