### ISSUE TITLE
Botar  y recoger de otros items

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus#467]
Tengo duda si es necesario implementar drop de otros items aparte de las semillas. (O sea, si daran puntaje por esto) Y si es asi, entonces supongo que deberia implementar el recoger del mismo. Pero bueno la pregunta es lo que dije primero principalmente.

**Comment by aljara97** [comment]
Hola, solo es necesario que implementes drag and drog para cultivar semillas. Para otros items esto no se evalúa.
Suerte 🌱
