### ISSUE TITLE
AF5 duda sobre import de DCChef y Torta

### ISSUE THREAD

**Issue by m1guel-angel** [IIC2233/syllabus#467]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Mi duda es para qué sirve el import de DCChef y Torta en el archivo decoradores_cocinero.py, puesto que no lo utilicé en ese módulo y al momento de correr el código me tira un ImportError, sin embargo si comento esa la línea del import todo funciona bien.

**Comment by tqmbanados** [comment]
Hola! No encuentro el import en el archivo D: No hay alguna posibilidad de que los hayas agregado tú?
De todas maneras, es correcto que no es necesario hacer ningún import adicional en esos archivos. ¡Así que saca la línea nomás!

**Comment by m1guel-angel** [comment]
Gracias!! Se había importado solo, porque escribí DCChef y Torta en algún momento

**Comment by tqmbanados** [comment]
Me alegro que te haya funcionado! Exito! 😹
