### ISSUE TITLE
Visualización lenta

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2233/Syllabus#467]
Mi visualización(bonus) se demora mucho en ejecutarse, por lo que quería saber si es necesario que se ejecute siempre que una persona haga una consulta o puedo hacerla, por ejemplo, cuando se guarde el archivo.

**Comment by Hernan4444** [comment]
@Jiruiz2 tiene que ser cada vez que se ejecuta la consulta, pero puedes especificar que se demora para no realizar tantas consultas de visualización.

Saludos ✌️
