### ISSUE TITLE
Acciones de delegacion opuesta

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2233/syllabus#468]
Hola queria saber si la delegacion contrincante podia hacer algun tipo de accion o si durante todo el campeonato tiene los mismos atletas.

**Comment by vsantelicest** [comment]
Hola **@conyfernandezt**!
En el ítem 3.2.2 del enunciado que subimos, se explica que queda a criterio de ustedes si la delegación contraria hace uso de sus días de entrenamiento ejecutando acciones al igual que la delegación propia.
Éxito!! 🏋️
