### ISSUE TITLE
Librerías permitidas/no permitidas en la T04

### ISSUE THREAD

**Issue by iqacevedo** [IIC2233/Syllabus#468]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:

> ¿Puedo usar la librería nombre_librería para hacer explicación_de_lo_que_quiero_hacer?

Recuerden especificar en su README qué librerías utilizan!

-----------------
## **Librerías Permitidas**
- `random`
- `unittest`
- `logging`
- `abc`
- `datetime`
- `collection`
- `math`
- `time`
- `statistics.mean`
- `numpy`
- `copy`
- `itertools`
- `tabulate`
- `typing`
- `abc`
- `functools.reduce`
- `matplotlib`
- `csv`
- `calendar`
- `bisect`
- `heapq`
- `operator`
## **Librerías Prohibidas**
- `threading `
- `pandas`
- `recordclass`

## **Built-ins prohibidos**
- `eval`(:skull:)
- `exec` (:skull:)

**Comment by felipecr00** [comment]
puedo usar la librería pandas para procesar los datos csv?

**Comment by Hernan4444** [comment]
@felipecr00 para eso tienen la librería csv (que la acabmos de permitir). Así que no puedes usar pandas.
Saludos ✌️

**Comment by rihanuch** [comment]
se puede usar numpy?

**Comment by cilopez** [comment]
@rihanuch si se puede

**Comment by Kitaps** [comment]
se puede usar  sys.stdout, sys.__stdout__ y os.devnull para bloquear y desbloquear la funcion de printeo para la parte final ?

**Comment by iqacevedo** [comment]
@Kitaps si puedes, pero existe una forma **mucho** más fácil de hacerlo (aunque si ya sabes cómo hacerlo así está bien).

Saludos !

**Comment by pxparga** [comment]
se puede usar recordclass? Es como namedtuple pero mutable

**Comment by Bneya** [comment]
¿hay restricciones en el uso de functional? ¿puedo usar generadores, filters, map, etc?

**Comment by iqacevedo** [comment]
@pxparga no puedes.
@Bneya puedes usar funcional, no hay ninguna restricción respecto a su uso.

Saludos !

**Comment by fgbruna** [comment]
Se puede usar SimPy ?

**Comment by Hernan4444** [comment]
@fgbruna recuerda seguir el formato de consultas (explicar para que quieres usarlo).

**Comment by MrEarle** [comment]
Se puede usar bisect para mantener una lista ordenada desde el principio?

**Comment by Hernan4444** [comment]
@MrEarle si puedes c:

Saludos ✌️

**Comment by mmsaavedra1** [comment]
Puedo usar calendar para conocer el nombre del día que me entrega numéricamente date time?

**Comment by iqacevedo** [comment]
@mmsaavedra1 si puedes :)
Saludos !

**Comment by pdesolminihac** [comment]
Puedo usar libreria operator para obtener el objeto con un atributo mas alto de una lista de objetos?

**Comment by Bneya** [comment]
Puedo usar heapq para facilitar un merge sort?

**Comment by aleuribej** [comment]
Puedo usar functools.partial para poner default values en una namedtuple?
