### ISSUE TITLE
uso de exec_

### ISSUE THREAD

**Issue by diegopcalderon** [IIC2233/syllabus#468]
![duda_progra](https://user-images.githubusercontent.com/53881413/66585742-c6b8da80-eb5d-11e9-9461-d8f0e013b737.png)

Encontre este código en internet y quería saber si el "exec_" utilizado, se puede usar?

**Comment by aljara97** [comment]
Hola, en la issue #340 se explica en detalle la diferencia entre los métodos ```exec_()``` de PyQt5 y ```exec() ``` de python. 
Éxito con tu tarea 🌱
