### ISSUE TITLE
Chat y ventana

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#468]
Hola, cuando se inicia la partida, se puede mantener la ventana chat como una ventana adicional a la ventana de juego (la cual se abriria al iniciar la partida)

**Comment by gatochico** [comment]
Hola! Esta vez queda a tu criterio como mostrar el chat+juego (si ambas en la misma venta, o en ventanas distintas) , siempre y cuando ambas sean consistentes con el enunciado. Saludos! :cat:
