### ISSUE TITLE
',' en nombres de películas

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2233/Syllabus#468]
En el archivo Database existen películas que tienen comas en el nombre, lo que hace que se me caiga el programa por cargar mal los datos (ya que ocupo un split(', ') para cargarlos). ¿Debo preocuparme de intentar cargar las películas igual aunque estén las comas, o  puedo borrar las comas "a la mala" en las películas del archivo y ponerlo en el readme?

**Comment by pcseisdedos** [comment]
yo ocupé la librería csv para solucionar ese problema (pasa lo mismo con las reviews)
Saludos!
