### ISSUE TITLE
Duda de capa_relleno() e improvisar_toppings()

### ISSUE THREAD

**Issue by Jpobletel** [IIC2233/syllabus#468]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, tengo una duda a la hora de crear el decorador capa_relleno(). No entiendo como llamar a el atributo self.relleno_restante dentro del decorador, lo pongo en los argumentos del decorador? porque por lo que entedi solo debe llevar el tipo de relleno ahi.

Se dice que el decorador improvisar toppings va en agregar toppings, pero capa_relleno tambien es un decorador de esa definicion, se supone que debo poner ambas en la misma?

**Comment by tqmbanados** [comment]
Hola! Al trabajar con decoradores sobre métodos, la función (o método) recibida por el decorador incluye *todos* los argumentos. Entonces, los *args del wrapper tendrán como primer argumento la instancia que llama el método. Espero que con esta información puedas llegar a la respuesta a tu pregunta, si no avísame 😄 . Recuerda que en los métodos, el primer argumento es la instancia, usualmente llamada ```self```.

Para la segunda pregunta la respuesta es sí! Es posible superponer decoradores. Lo que ocurre ahí es que el decorador de más arriba, estará trabajando sobre la función retornada por el decorador de más abajo. En algunos casos el orden en que se colocan puede ser importante, te reto a descubrir si en este caso lo es!
