### ISSUE TITLE
[Threading] Clases o funciones target

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#469]
Que ventaja existe en crear un target como clase en vez de como un target hacia una funcion?
Puesto ambos son customizables, lo unico que se me ocurre es el poder ir guardando atributos en el objeto.

**Comment by DiegoAndai** [comment]
Hola! Son dos formas de modelar un problema, cada una tiene sus ventajas. Si quieres hacer threads más complicados o que manejen mucha información, sería más útil manejarlo como una clase así puedes acceder más fácil a los datos como atributos o a métodos auxiliares que estén en la misma clase, puedes ocupar properties, polimorfismo, al final tienes todas las ventajas que tienes con OOP. Un buen ejemplo de esto se puede ver en el material de sincronización cuando creas una clase MiDeque y se la asignas como cola a las clases Productor y Consumidor que son Threads.

Por otro lado, si tienes threads más simples, sería más directo ocupar la clase Thread  y simplemente asignarle el target. Esto te ahorra tener que escribir una clase que lo único que va a hacer es tener un run() distinto.

Al final, queda a tu criterio y tu manera de modelar el problema.
