### ISSUE TITLE
La fórmula de entrenamiento deportivo se pondera por 1.7.

### ISSUE THREAD

**Issue by nicolasvillarroel** [IIC2233/syllabus#469]
Cuando el enunciado dice que la formula de entrenamiento se pondera en 1.7, se refiere a que se pondera por 1.7 el parametro de PUNTOS_ENTRENAMIENTO? o se refiere a la formula de entrenar() completa?

**Comment by jitorcas** [comment]
Hola! @nicolasvillarroel 

La issue #333 responde a tu pregunta con mayor detalle.

Si quedas con dudas, puedes seguir preguntando! mucho éxito! 🥇
