### ISSUE TITLE
mesadas alumnos

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#469]
el enunciado dice que la mesada se recalcula cada 30 días, pero para efectos prácticos el mes tiene 20 dias. Se puede usar un mes de 20 días y simplemente cambiar la mesada al final de este mes modificado?

**Comment by cilopez** [comment]
@rihanuch no puedes asumir eso, ya que un evento no programado puede caer en un fin de semana, de ser así este no tiene repercusiones.

**Comment by rihanuch** [comment]
ok! pero es cada 30 días o una vez al mes? (es diferente, porque hay meses que tienen 31 días 👀)

**Comment by cilopez** [comment]
Lo esencial es que sean 4 meses, lo ideal sería que fuera desde la fecha que  inicio el semestre hasta 4 meses más, pero si quieres realizalo desde la fecha actual a 4 meses más.
