### ISSUE TITLE
Como testear eventos de teclas multiples como K + I + P sin teclado mecánico?

### ISSUE THREAD

**Issue by DonJavi-538** [IIC2233/syllabus#469]
Un elemento de la evaluación consiste en  poder realizar eventos al usar combinaciones de 3 teclas, pero la gran mayoría de los notebooks poseen teclados de membrana, por lo que no siempre pueden detectar de forma correcta una combinación con 3 o más teclas. Ante esto ¿qué recomiendan para testear que la funcionalidad sí esté implementada correctamente?

**Comment by Dnpoblete** [comment]
Hola @DonJavi-538 tu duda fue respondida en la issue #455, pero de todos modos te comento la respuesta: la idea de las combinaciones de teclas es que se presionen en ese orden, pero no simultáneamente, si no que una después de la otra sin que se presione una tecla diferente entre medio, porque sino ocurre el problema que tu comentas.

Espero haberte ayudado y si no respondí tu duda avisame para poder ayudarte.

Éxito con la tarea! 😄
