### ISSUE TITLE
Notas Actividades Fromativas y Sumativas

### ISSUE THREAD

**Issue by santiagoolivos** [IIC2233/syllabus#469]
Creo que hay un problema con mi repositorio ya que a pesar de que he hecho todas las actividades (formativas y sumativas) y las he subido correctamente, no me han calificado ninguna y me sale que no las he hecho o entregado. Además mande a re-corregir la AF01 y no me han notificado nada, por lo que creo que posiblemente  no están viendo mis entregas.
Es por esto que espero que me puedan ayudar con este problema y luego puedan re-corregir todas estas estas evaluaciones.
Gracias, saludos.

**Comment by entamburini** [comment]
Hola @santiagoolivos 

Este no es el medio para este tipo de consultas, puesto que es una duda personal, para futuras referencias ocupa el mail oficial del curso: iic2233@ing.puc.cl
