### ISSUE TITLE
Diferencia entre enunciado y "test_17_edad_promedio_humana_voto_comuna.py"

### ISSUE THREAD

**Issue by lauramelotrucco** [IIC2233/Syllabus#469]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, cuando corro el `test_17_edad_promedio_humana_voto_comuna.py ` , me indica que el resultado de esta función debería ser un float. Sin embargo, en el enunciado de esta función se indica que el resultado debe ser entregado como un int. ¿A cuál de las dos cosas debería hacerle caso? Gracias.
![image](https://github.com/IIC2233/Syllabus/assets/130701578/353bcc91-6929-464a-9611-28af182fac84)

**Comment by Hernan4444** [comment]
Hola @lauramelotrucco 

Efectivamente el enunciado dice `int` como edad promedio. Ahí hubo un pequeño _typo_ porque el promedio no necesariamente es un `int`, puede ser un decimal. No obstante, el enunciado es quien manda y los tests públicos son solo un segundo checkeo. Así que puedes mantener tu respuesta como `int` y al momento de evaluar los tests privados, se comprobará que tu respuesta sea el `int` correspondiente. 

De igual forma, si decidiste ajustar tu respuesta para que el resultado fuera un `float`, tambien se aceptará esa respuesta. En resumen, nos aseguraremos que los tests privados revisen que la respuesta sea tanto el int o float correspondiente. Así aceptamos la respuesta de quien siguió esa parte del enunciado o quien siguió los tests públicos. De este modo, ningún estudiante será afectado por la decisión tomada.

Mi recomendación es retornar el promedio **sin** transformar el dato a `int` en ningún momento. Así podrás validar que tu respuesta sea exactamente igual al tests, pero si optaste por dejarlo al `int` como en la foto que subiste, es 100% válido.

Espero que haya resuelto tu duda. ¡Éxito en tu tarea! 🚀
Saludosヾ(＾-＾)ノ
