### ISSUE TITLE
Duda parte 2 AF5 (decoradores del cocinero)

### ISSUE THREAD

**Issue by a-ck** [IIC2233/syllabus#469]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Tengo una duda, si en mi wraper pongo los parámetros como *args y **kwargs, cómo accedo a uno en específico después? lo llamo por su nombre no más o debo ponerlo manualmente dentro del wraper()? Si es esto último como que pierden todo el sentido los decoradores pq la idea es no tener que llamar parámetros en específico (cierto?)

**Comment by jadaam** [comment]
tengo la misma duda !

**Comment by aaossa** [comment]
Hola @a-ck y @jadaam 🙌 Recuerden que `args` y `kwargs` son una tupla (`tuple`) y un diccionario (`dict`) respectivamente. Por lo tanto, para acceder a un argumento posicional pueden usar su posición (`args[0]`) mientras que para acceder a un argumento nombrado pueden usar el nombre del argumento (`kwargs["argumento"]`). Si les queda alguna otra duda con esto, pregunten por acá mismo ✨ ¡Éxito con la actividad 💪!

**Comment by a-ck** [comment]
Ya perfecto, muchas gracias!!
