### ISSUE TITLE
Duda tamaños pizzas

### ISSUE THREAD

**Issue by vhernnda** [IIC2233/Syllabus#469]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Estaba viendo los tests y me di cuenta que en algunos casos consideran pizzas de tamaño xl, sin embargo en los archivos de data solo veo pizzas S, M o L. Deberia considerar existen pizzas xl, aun que sea por lo menos para los tests publicos?

**Comment by aline-schneider** [comment]
No soy ayudante, pero por lo que tengo entendido el tamaño de las carpetas s, m, l y xl, se refiere al tamaño del archivo, según cuántas líneas tiene. Los tamaños de las pizzas si deberían ser solo S, M y L.

**Comment by AlonsoPlaza** [comment]
Hola, en los tests si se consideran pizzas de tamaño XL mientras que en los datos dados no hay de ese tamaño. Ahora, en el enunciado nunca se especifica de que tamaños pueden ser las pizzas por lo que tu solución debería funcionar para cualquier tamaño, no solo para S, M o L.

**Comment by vhernnda** [comment]
Muchas gracias, saber eso me sirve caleta
