### ISSUE TITLE
Duda crear_predios

### ISSUE THREAD

**Issue by BoPe3p** [IIC2233/Syllabus#47]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola buenas, tengo una duda sobre un error en test públicos,. Ya hay una issue sobre eso pero no sabía si ponerla como comentario ahí o si hacer una issue nueva, igualmente como es específica del test 04, la pongo por separado.

Cuando corro el test 4, me sale el siguiente error:
<img width="845" alt="Captura de pantalla 2024-08-16 000551" src="https://github.com/user-attachments/assets/589451a5-8f8f-4d27-b8ec-325022d48ccb">

La cosa es que ese error hace referenia al archivo de los test públicos, el cual no se puede modificar... ¿Qué procede?
Gracias de antemano

**Comment by individuocomunycorriente** [comment]
Hola buenas, te aconsejo revisar de que forma estás creando los predios en el método crear_predios() de DCCultivo, debido a que el error que muestras en la imagen hace referencia a que la lista de predios de DCCultivo posee listas en vez de instancias de la clase Predio como menciona el enunciado. Quedo atento a tu respuesta :)

**Comment by pacalein** [comment]
¡Hola! El error no es de los archivos si no de qué datos estás creando. Recordemos que según el enunciado `DCCultivo.predios` es una lista de OBJETOS de la clase Predio. El test al intentar acceder al primer elemento de esa lista (`DCCultivo.predios[0])`, y luego acceder a su atributo, no puede hacerlo ya que dice que es una lista y por ende no tiene atributos. ¿Debe ser ese elemento en `DCCultivo.predios[0]` una lista? La verdad es que no, debe ser un objeto de la clase Predio. Es por eso que debes ir más atrás e intentar arreglar cómo estas generando y populando `DCCultivo.predios`.

Fran
