### ISSUE TITLE
Modificar galaxia

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#47]
En el item 6.2 de la tarea se pide que el jugador pueda modificar las tasas de recolección,¿Debemos limitar las tasas de recolección en los intervalos pedidos inicialmente ? ¿O debemos permitir que el jugador exceda estos valores iniciales de los planetas? (en el enunciado señala que debe ser mayor que cero, pero no se si las tasas de recolección tienen una capacidad máxima como tal)

**Comment by leolivares** [comment]
Hola! Esta en el enunciado. Sección 9 (Restricciones para modificar una galaxia).

**Comment by santilaguna** [comment]
Expliqué mal mi pregunta, la acabo de editar para que se comprenda mejor.

**Comment by NicolasCourt** [comment]
Si te fijas en el punto 5.2 se especifican las tazas de minerales y deuterios, en un principio se genera aleatoriamente entre unos valores, pero si quieres setearlo tu, debe estar entre los establecidos  (1-10 para minerales 5-15 para deuterio)  :)

**Comment by santilaguna** [comment]
Buena gracias!
