### ISSUE TITLE
Formato de fecha de los posts

### ISSUE THREAD

**Issue by Etienne99** [IIC2233/syllabus#47]
Hola! Solo quisiera saber si puedo trabajar con un formato de fecha distinto al que se especifica en el enunciado. En caso de que se pueda lo detallaré en el readme.md.

**Comment by Tito0906** [comment]
Holaa @Etienne99 , el formato bajo el cual se deben trabajar las fechas está explicito en el enunciado, por lo que deben usar exactamente ese formato.

**Comment by jonanortizvega** [comment]
Hola, en el enunciado sale que es yy/mm/dd, eso significa que debo usar 20/03/18 y no 2020/03/18?

**Comment by aaossa** [comment]
@jonanortizvega eso fue respondido en #14 (debería ser **yyyy/mm/dd**)
