### ISSUE TITLE
Bug al Cargar y Guardar 

### ISSUE THREAD

**Issue by fpaez7** [IIC2233/syllabus#47]
El evidente problema con el archivo  _civilizaciones.csv_ es que no se puede llevar cuenta de los hp actuales de los edificios generando el posible bug que eclipsa la Habilidad especial del mismísimo *Gran Polea* . 
### Si guardas y cargas todos los edificios vuelven a sus hp máximos 

La solucion podria ser muy simple en vez de almacenarlos como booleanos, podríamos almacenarlos con integers que nos permitan llevar la cuenta de los hp de los edificios mas importantes (centro urbano, cuartel ,dccowork)
( Nos aprovecharemos de que en python bool (0) = false , int(False)=0, bool (entero_no_nulo)=True)

![Correccion](https://user-images.githubusercontent.com/37160024/54968385-4338f280-4f59-11e9-9e4f-8626dcb0d235.png)

Esto no soluciona completamente el problema  que al cargar todas las unidades pueden cambiar y todavía puede usarse el bug para reparar las paredes , aunque se podrían implementar otras soluciones para esos problemas, esta solución mejora mucho la experiencia de juego. Y ademas lo hace un poco mas limpio de programar  (No puedo decir nada sin soltar respuestas)

**Comment by fpaez7** [comment]
Considerablemente mas limpio de programar

**Comment by iqacevedo** [comment]
Hola,
Si bien es una solución para guardar la vida de esos edificios, no es lo que estamos evaluando que guarden. No pedimos que se guardara Hp para simplificar el proceso de guardado.  Por este motivo, debes seguir el formato que les indicamos para guardar y cargar archivos.

Saludos
