### ISSUE TITLE
T0: Guardar partida > Cargar partida > Ganar ¿Qué pasa con el archivo guardado?

### ISSUE THREAD

**Issue by ReneSaavedraV** [IIC2233/Syllabus#47]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Supongamos se hace lo siguiente:
Crear Partida
Nombre: juego
Guardar partida
Salir al menu principal
Cargar partida: juego
Se gana la partida

Que pasa con el archivo juego.txt? Se debe borrar o simplemente no se altera una vez ha ganado el jugador?

**Comment by caramelnico** [comment]
Supongo que guardas el puntaje en el ranking y la eliminas de las partidas guardadas

**Comment by Emiliax16** [comment]
Hola! tal como dice @caramelnico , si terminas una partida y esta se encontraba en el archivo de partidas guardadas, se debe eliminar de ahí, ya que la idea principal de guardar y cargar partidas es **continuar jugando esa partida**, por lo que si está finalizada no tiene sentido que siga en el archivo. Eso sí, se debe guardar el puntaje obtenido al igual que con cualquier otra partida. Saludos 😸
