### ISSUE TITLE
Duda sobre el ejemplo de "Menú" en el enunciado

### ISSUE THREAD

**Issue by FVivess** [IIC2233/syllabus#47]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Quería saber si se puede utilizar los ejemplos de "Menú" entregados en el enunciado para la tarea, o si esto se considera plagio o algo parecido.
Por ejemplo, el menú de inicio entregado en el enunciado es el siguiente:
***** Menu de Inicio *****

Selecciona una opción:

[1] Crear usuario
[2] Iniciar sesión
[0] Salir

Indique su opción (0, 1 o 2): (input del usuario)
¿Sería correcto utilizar este mismo texto para el código?

**Comment by pabloist** [comment]
Hola :)

Te comento que los formatos de ejemplo entregados en la tarea tienen el objetivo de guiar el desarrollo de sus códigos, por lo que pueden utilizarlos tal como están (no se considera plagio) o utilizar otras formas de presentación de información más de su propio gusto, siempre y cuando muestren toda la información solicitada.

Saludos!

**Comment by FVivess** [comment]
Muchas gracias!
