### ISSUE TITLE
Como guardar correctamente mis archivos con VS Code

### ISSUE THREAD

**Issue by CataLebe** [IIC2233/Syllabus#47]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Sé que esta duda puede ser un poco básica, pero no sé por qué lo que hago en vs code no se guarda. La primera vez que redacté código se me borró todo, de forma que ahora lo he estado guardando en un drive a modo de respaldo. Me he preocupado de guardar cada archivo .py de forma individual con save as, pero aún así cuando lo vuelvo a abrir les falta parte código.
No se qué podrá ser.

Desde ya muchas gracias

**Comment by Juampisaez** [comment]
Holaa @CataLebe!
Cuando uno parte con vscode, los archivos no se guardan automaticamente al escribir o editar codigo. De esto te puedes dar cuenta en la barra donde aparecen los archivos abiertos, cuando lo editas aparece un circulo al lado del nombre del archivo, lo que indica que el archivo cambio y no ha sido guardado aún. Una forma de guardarlo de forma rapida es con el comando `ctrl + s`. Otra forma es activar el guardado automatico, lo que se puede hacer en la barra superior de vscode, en la opcion "archivo", ahi se desplegaran varias opciones, entre ellas el "autoguardado".

Espero te pueda ayudar con tu problema
Quedo atento si funciona :)

**Comment by CataLebe** [comment]
Lo intenté pero sigue sin servirme :(, no se cuál será el error. Fui por cada archivo .py de mi carpeta T0 poniendo save, y haciendo  ctrl + s pero sigue sin funcionarme creo.

Es este el punto que debería irse ?
![Captura de pantalla T0](https://user-images.githubusercontent.com/81182364/131522991-326054ab-ab7a-4557-a72f-812b73d655a4.png)

**Comment by Juampisaez** [comment]
A esto me refiero:
![image](https://user-images.githubusercontent.com/48323752/131523281-2d639fed-afc3-4c1c-9ad2-83202b1a235e.png)
Acá hice un cambio y aun no lo guardo, arriba en la barra de archivos me aparece el archivo con el circulo al lado y a la izquierda me aparece "1 sin guardar". Si apreto el archivo y le doy `ctrl + s` no te funciona?

**Comment by CataLebe** [comment]
Nopp, igual me aparece distinto, cuando hago un cambio en uno de los archivos dentro de la carpeta T0, no me aparece un circulo al lado de ese archivo como en la foto. Lo único que aparece un círculo al lado de la carpeta que contiene los archivos (T0), y el circulo no se va.
