### ISSUE TITLE
Duda sobre funciones helper

### ISSUE THREAD

**Issue by a-maccormack** [IIC2233/Syllabus#47]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Creación de helper functions para organizar mi codigo y "reducir" cantidad de lineas

Hola, estoy tratando de conseguir los puntos extra de funciones atomicas y me surgió la siguiente duda...

Puedo tener funciones "helper" que llame de otro archivo que no sea `functions.py` ?

Tengo pensado hacer algo como esto:
```python
# en helper.py (archivo creado por mi)
def calcular(a,b):
   out = 2*a - 3*b
   out *= 3
   out = out^3
   out += b

   return out

   # Observermos que la función "calcular" es de 5 lineas
```

```python
# En functions.py
from helper import calcular

def mi_funcion(p1,p2):
   """
   Imaginemosnos que hay varias lineas de codigo aquí
   """
   calculo_1 = calcular(p1,p2)
   calculo_2 = calcular(p2,p1)
   total = calculo_1 + calculo_2

   return total

   # Supongamos que la función "mi_funcion" terminó siendo de 13 lineas

```
Notemos que `mi_funcion` y `calcular` son ambas de menos de 15 lineas

Esta manera de organizar el codigo sirve para el requerimiento de funciones atómicas?

**Comment by pedrozavalat** [comment]
Hola @a-maccormack !

Si puedes importar otras funciones que sean de otro archivo distinto a ```functions.py```. Pero, recuerda que para **obtener el bonus de _funciones atómicas_**, para toda función que definas, debe contener como **máximo 15 lineas de código**. En este sentido, la condición del limite de 15 lineas de código como máximo se establece para todas las funciones que tu creas, sin importar en el archivo que se encuentre. 

Cualquier duda responde este hilo,
Saludos 😄 

Pedro Z.
