### ISSUE TITLE
multiherencia

### ISSUE THREAD

**Issue by santiago3c** [IIC2233/Syllabus#47]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

No entiendo qué hace ni cómo funciona al hacer ClaseB.llamar(self) dentro de la clase SubClaseIzquierda. Entiendo que hay un overiding, aparte de eso no entiendo mucho. También, ¿en la clase SubClaseIzquierda se crea la variable de clase num_llamadas_B  o no? Por favor si me pueden clarificar la situación

[De ser necesario, coloca tu pregunta de maner
![Captura de pantalla (160)](https://github.com/IIC2233/Syllabus/assets/142272696/b74f7908-d1c4-4bc7-b8ae-cb4afad6734b)
a explícita utilizando **este formato**]

**Comment by santiago3c** [comment]
ClaseB.llamar(self) es otro método dentro de la clase SubClaseIzquierda?

**Comment by santiago3c** [comment]
dónde se almacena self.num_llamadas_B, si no se crea una instancia de esa clase?

**Comment by santiago3c** [comment]
no se preocupen en contestar, ya entendí, gracias

**Comment by Dvckhv** [comment]
Aprovecho de añadir un comentario por si alguien mas tiene la duda je.

Al heredar, estas haciendo algo similar a un "copypaste" de todo el contenido de `ClaseB` en `SubClaseIzq`, por lo que puedes utilizae en la subclase todo lo que habia en su clase padre, ahora, al momento de hacer overwrite de un metodo, el de la clase padre puede ser llamado para recuperar ese contenido, a pesar de escribir uno con el mismo nombre ¿Como? Especificando que es del padre y no propio, por lo que haces `ClaseB.metodo()`.

Espero ayude a terminar de procesar Herencia y MultiHerencia :)

**Comment by santiago3c** [comment]
gracias!
