### ISSUE TITLE
Fork vs Clone en GitHub

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#47]
Holaa! Quería saber cuál es la diferencia entre Fork y Clone. Intentando acceder a los contenidos de la semana terminé haciendo fork desde IIC2233/contenidos. Viendo más videos cache que hay que clonarlo. Mi duda es, ¿Me va a causar problemas tenerlo en fork o puedo dejarlo tal como está?

**Comment by bvasquezm** [comment]
Hola @denisseleiva!!

Esperando que te encuentres bien, te comento que la herramienta **Fork** está pensada para compartir o copiar proyectos dentro de github, puedes obtener tu copia personal de un repositorio, pero este no existe dentro de tu computador a menos que lo **Clones**. 

No debiese haber ningún problema, pero para efectos de este curso sólo debes clonar los repositorios que desees importar a tu computador, como puede ser tu repositorio personal, el syllabus o contenidos del curso. Cualquier duda no dudes en preguntar :)

**Comment by denisseleiva** [comment]
@bvasquezm buenisimooo, muchas gracias!!!
