### ISSUE TITLE
Duda sobre cargar una partida en la tarea.

### ISSUE THREAD

**Issue by rgmorales1** [IIC2233/syllabus#47]
Una consulta, si al guardar una partida, el jugador pone como nombre "jugador", y luego al cargar la partida pone como nombre "Jugador", ¿puedo tomar esos 2 string como nombres distintos?, o necesariamente es el mismo nombre y tengo que cargar la partida de "jugador". En resumen, mi duda es sobre las mayúscula y minúsculas, si tomo en cuenta las mayúsculas como distintos string de las mayúsculas, aun que digan lo mismo.

**Comment by jeschuwirth** [comment]
Saludos,

Eso queda a criterio tuyo, por lo que no hay problema con que los consideres dos nombres distintos o el mismo.

Suerte en la tarea!
