### ISSUE TITLE
importar usuarios

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#47]
al importar los usuarios asumimos que son traders o investors?

**Comment by nmaturana97** [comment]
depende de la fecha de nacimiento mi querido compañero

**Comment by stephichau** [comment]
Puedes asumirlo como quieras, pero debes especificarlo en el **README** :)

**Comment by rakarachon** [comment]
@stephichau la suposiciones que haga respecto al diagrama de clases también basta con que las especifique en el README? (Por ejemplo si un mercado puede existir si no tiene usuarios registrados)

**Comment by stephichau** [comment]
@rakarachon sí, especifica todo en el README. Ojo con que tus suposiciones pasen a llevar cosas especificadas en el enunciado :)

**Comment by rakarachon** [comment]
@stephichau ok, muchas gracias!
