### ISSUE TITLE
Suponer Fecha Mínima

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#47]
Hola!

En mi programa quisiera convertir las fechas desde el formato día/mes/año a el formato "días pasados desde una fecha determinada" (ej: días pasados desde el 1 de Enero del 2000). Puedo suponer un limite inferior en las fechas que van a ser entregadas a nuestro programa?

Gracias!

EDIT: Podemos suponer una fecha máxima también? Cuando llegamos al 2100 los años bisiestos no son siempre cada cuatro años. Por ejemplo, el mismo año 2100 no es bisiesto.

**Comment by negutierrez** [comment]
Yo asumí que sí se podía, ya que datetime funciona de manera similar. Sobre los años bisiestos,  para que un año sea bisiesto tiene que ser divisible por 4 y además, no ser divisible por 100 o sí por 400, con lo que 2100 no es bisiesto pero 2400 sí lo es.

**Comment by arturodelreal** [comment]
Si puedes asumir una fecha mínima, pero debe ser antigua (por ejemplo 1 de enero del 2000). 
Lo de la fecha máxima lo puedes solucionar con lo que puso @negutierrez

**Comment by akaminetzkyp** [comment]
Súper! Usare el 1 de Enero del 2000 como fecha mínima.

Otra pregunta. No debemos tomar en cuenta los segundos extra de algunos años? El año pasado, por ejemplo, hubo un segundo extra a fin de año.

Saludos

**Comment by rpalmaotero** [comment]
Esos segundos extra pueden ser ignorados.
