### ISSUE TITLE
Duda respecto al largo del archivo red.py

### ISSUE THREAD

**Issue by BenjaminIbanez** [IIC2233/Syllabus#47]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Buenas tardes, mi pregunta consiste en que pasa si el archivo red.py se pasa de las 400 lineas de codigo, ya que  en las reglas del curso en la parte de modularizacion dice que no se puede superar las 400 lineas, , en caso de pasarnos tenemos que intentar reducir las lineas de codigo o por esta ocacion se dejara pasar ya que tenemos que definir todas las funciones en red.py?

**Comment by Pablo-Gonzalez-Calderon** [comment]
Holaaa ✨

Como se ha mencionado en clases, el **pasarse de las 400 líneas de código se considera una mala práctica, y tiene descuento en tu tarea** (puedes revisar el Excel de asignación de puntaje [aquí](https://docs.google.com/spreadsheets/d/1T8mptqbKGWay1crfTRisRhfUGSEssS-EWpUTdL4gmTE/edit#gid=383710472), donde, en "Aspectos generales" se indica que no cumplir este aspecto implica una disminución en tu puntaje).

Ahora, ¿qué pasa si tu archivo `red.py` se pasa de las 400 líneas? Deberás ✨modularizar✨ Un tip util es leer tu código y encontrar partes que se repiten y que puedas agrupar en archivos/funciones externas, **pero sin modificar las estructuras entregadas de forma inicial en la tarea,** pues modificar la estructura entregada tiene descuento, como indica la página 6 del enunciado:

> ![image](https://github.com/IIC2233/Syllabus/assets/30756770/33cdcd52-7674-44c9-b350-8b8faaa8d280)

Espero haber resuelto tu duda 😊🍀

P.D.: Recuerda agregar los nuevos módulos/funciones que crees en tu README, explicando qué hacen
