### ISSUE TITLE
duda testcase hallar region

### ISSUE THREAD

**Issue by nicolettadegoye** [IIC2233/Syllabus#470]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

al correr hallar_region, si pongo return me aparece todo OK, pero si pongo un yield, me aparece:
self.assertCountEqual(resultado, expected_output)
AssertionError: Element counts were not equal:
First has 1, Second has 0:  'Valparaíso'
First has 0, Second has 1:  'V'
First has 0, Second has 3:  'a'
First has 0, Second has 1:  'l'
First has 0, Second has 1:  'p'
First has 0, Second has 1:  'r'
First has 0, Second has 1:  'í'
First has 0, Second has 1:  's'
First has 0, Second has 1:  'o'
Sin embargo, el teste case de elementos prohibidos me aparece invalido al momento de poner return. A que se debe este error?

**Comment by ignacio-sp** [comment]
Hola @nicolettadegoye, puede que el script de elementos prohibidos te arroje inválida la función debido a que probablemente estés usando algún comando prohibido dentro de esta (algún for, tuple, list, etc) el cual está permitido dentro de una función que esté usando un `yield` al final, pero que no están permitidos dentro de una función que retorna con `return`, por lo que recomiendo que utilices una función auxiliar que haga uso del comando prohibido dentro de un `yield` para que el script no arroje algún error.
