### ISSUE TITLE
[Ayudantia 10]  self.alumnos vs alumnos

### ISSUE THREAD

**Issue by LuisFros** [IIC2233/Syllabus#470]
En la ayudantia del martes, cuando se creaaba el "spawner" de los alumnos, se hacia referencia al atributo self.alumnos. En la solucion propuesta, se utiliza el parametro local entregado al instanciar LLoraton "alumnos". Cuando se agregan alumnos en el "spawner", en ambos casos no parece haber una diferencia en la simulacion, deberia haber algun inconveniente al perder la referencia del "self."?
```sh
args=(self.alumnos,...
```
o
```sh
args=(alumnos,...
```
```sh
Class Lloraton(Thread):
...
def run(self):
    self.time=time.time()
    spawn_thread=Thread(target=spawner, args=(self.alumnos,.0.5, self.ayudantes), daemon=True)                                  
    while time.time() - self.time < self.max_time:
         ...
```

**Comment by jtagle2** [comment]
Hola! Que bueno que te diste cuenta de ese detalle. La verdad, se me pasó eso y está mal modelado, lo correcto es pasarle la referencia desde el `self.alumnos`.
Aprovecho para explicar un poco más de todas formas. Si le entregamos desde `alumnos`, estaríamos obligando al que use nuestro código a tener una variable alumnos para que el método funcione. Si lo entregamos desde el self, le damos libertad al programador para usar cualquier nombre de variables y que funcione de todas formas (nuestro spawner sería de uso general, no particular). Por otro lado, si quieres correr 2 lloratones en "paralelo" (Al ser un thread, no deberían haber problemas), lo correcto es que el spawner de cada lloratón, guarde los alumnos en la lista asociada a dicha lloratón, es decir, en `self.alumnos`.

Gracias por la observación, ya está arreglado
Saludos!
