### ISSUE TITLE
Problema con test_11

### ISSUE THREAD

**Issue by MTGG123** [IIC2233/Syllabus#470]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Revisando el test_11 me di cuenta de un problema. En la solución L_1 dice que la única pizza mas vendida en la fecha 2024-05-20 (según el test de cargar datos) es Esponjoso Fino Brillante con Magia, cuya cantidad máxima vendida es 5, pero también encontré otra pizza con la misma cantidad y la misma fecha que no esta en la solución. Un problema similar me pasa con el resto de test de tamaño L. No se si me falta considerar algo
![Captura de pantalla 2024-10-07 173936](https://github.com/user-attachments/assets/7a2c1a23-ebee-4df4-a54d-0522ca37a37c)
![Captura de pantalla 2024-10-07 175105](https://github.com/user-attachments/assets/6b7c5ed9-d434-4fc1-8bcc-a93daee5995a)
 
![Captura de pantalla 2024-10-07 173908](https://github.com/user-attachments/assets/2f087b89-17bd-4435-9f97-04ed6ce84e53)
![Captura de pantalla 2024-10-07 173852](https://github.com/user-attachments/assets/7049193c-6a94-4371-8015-01d4d25d3375)

**Comment by kbetelgeuse** [comment]
Hola @MTGG123!
Disculpa por la demora en responder. Estamos analizando como equipo docente el caso asociado con este test. ¿Podrías subir por favor a tu repositorio lo que llevas hasta este momento de tu tarea para poder analizar en detalle lo que comentas? 
Saludos!

**Comment by kbetelgeuse** [comment]
Hola @MTGG123 !
Ya se ha revisado el caso asociado a este test. Después de un analizar la base de datos no se ha podido detectar el problema que describes. Esto, dado que se pudo comprobar que la cantidad de pizzas vendidas de tipo `Esponjoso Fino Brillante con Magia` en el día `"2024-05-20"` es distinta de 5 (y en particular, es mayor que 5).

Por otra parte, estuve revisando el código que tienes subido hasta el momento en tu repositorio, y por lo que veo, no falta considerar nada: tu código está realizando todos los pasos de la consulta. También, se pasan todos los testscases con lo que tienes implementado. Junto con lo anterior, de acuerdo con el código que posees se obtiene que la cantidad vendida de la pizza `Esponjoso Fino Brillante con Magia` resulta ser distinta de 5.

Dado lo anterior, quisiera saber si es que sigues teniendo problemas de algún tipo acerca de esta consulta, ya que el desarrollo que posees de esta es correcto y está bien implementada. Si es el caso, coméntalo para que podamos resolverlo :)

Saludos, y éxito en el desarrollo de la tarea!
