### ISSUE TITLE
Duda comando \chao en chat [Tarea 3] 

### ISSUE THREAD

**Issue by Tito0906** [IIC2233/syllabus#470]
Holaa, tenía un par de preguntas respecto al comando \chao. Mi dudas son:
1) El comando debe ser necesariamente el último mensaje de un jugador? Es decir, si un jugador usa \chao y después manda otro mensaje, su voto se elimina?

2) Puedo votar por mí mismo para eliminarme de una sala?

3) Se puede tener más de un voto activo por usuario? osea, si usé el comando \chao para eliminar a un jugador X, puedo usarlo otra vez con un jugador Y  aunque no se haya eliminado a X? Esto daría la posibilidad de votar por todos los jugadores enemigos.

**Comment by gatochico** [comment]
Hola! Respondiendo en orden:

1. No es necesario que \chao deba ser el último comando del jugador para que este se permanezca activo. Los jugadores deben ser capaces de votar \chao a alguien y seguir hablando en el chat con normalidad, y el manejo de la votación debe seguir en curso en segundo plano.

2. Si, puedes votar para echarte a ti mismo 😹 

3. Queda a tu criterio elegir si puede haber una sola votación de \chao activa durante su respectiva ventana de tiempo, o si puede haber más de una para diferentes usuarios al mismo tiempo. Como siempre, escribe tu decisión en el README!

Éxito! 💻
