### ISSUE TITLE
Programación funcional para importar archivos

### ISSUE THREAD

**Issue by jerosalazar** [IIC2233/Syllabus#470]
¿Es importante que, como en la tarea 3, ocupemos generadores y programación funcional al importar los archivos csv o podemos importar datos a listas u objetos?

**Comment by iqacevedo** [comment]
Hola,

No es necesario para esta tarea, puedes importar datos a listas u otros objetos.

Saludos !

**Comment by mjgutierrez1** [comment]
Y aunque no sea necesario, ¿es recomendable hacerlo?, en el sentido de que quizás así el programa es más eficiente o corre más rápido.

**Comment by Hernan4444** [comment]
@mjgutierrez1, se recomienda utilizar funcional cuando sabes que el input de datos puede variar en grandes cantidades y quieres evitar sobrecargar la RAM con toda la información. En este caso los datos no son muchos y si o si hay que instanciar la mayoría de los datos para poder hacerlos interactuar en la simulación. Te recomiendo enfocar más en modelación y simulación que es la materia principalmente evaluada en esta tarea.

Saludos ✌️
