### ISSUE TITLE
duda test 19

### ISSUE THREAD

**Issue by santiago3c** [IIC2233/Syllabus#470]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/396)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/395)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, que en los tests 19, no entiendo porque hay múltiples Funciones diferentes con el mismo id, si me pueden explicar

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by pedrozavalat** [comment]
Hola @santiago3c !,
Se revisaron los _tests_ de `test_19_personas_no_asisten` y todas las funciones para cada test son únicas 😅. Presentan diferentes identificadores entre sí. 
Cualquier duda responde la issue, saludos 😄!

**Comment by santiago3c** [comment]
Gracias, que en el test 0 el id me sale 7617 tres veces, no se si estoy entendieno mal algo
![image](https://github.com/IIC2233/Syllabus/assets/142272696/d1cae27e-96e5-49cb-a319-7be8317dcda3)

**Comment by MystEdu** [comment]
@santiago3c ¿Tienes los tests actualizados?, han hecho varios cambios, así que imagino que puede ser eso. Revisé el test que tengo yo, y no están repetidos.
![test_0](https://github.com/IIC2233/Syllabus/assets/130402592/7bd0fff8-55fb-4164-afe6-ccc71dc0cbe2)

**Comment by pedrozavalat** [comment]
Si, el test tenía errores y ya fue arreglado. Actualiza el archivo `test_19_personas_no_asisten.py `para tener los nuevos cambios 😄
Saludos!

**Comment by santiago3c** [comment]
vale gracias
