### ISSUE TITLE
Uso adecuado de lower()

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#470]
Hola!
Qué significa este error; *<built-in method lower of str object at 0x000000B008D9CAF0>* ¿?
Me sale cada vez que se ejecuta el método de donde viene el error, pero el código funciona igual sin ningún problema, solo que me aparece esto y no sé por qué :disappointed_relieved:

**Comment by moquezada** [comment]
Hola @Camila-sty!

Tu error se puede deber a que quizás estas usando el método `lower()` sin paréntesis 😮 Si el error persiste avísame!

Saludos 😄
