### ISSUE TITLE
AF5 duda sobre función recibir_input

### ISSUE THREAD

**Issue by m1guel-angel** [IIC2233/syllabus#470]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

¿Es posible que la función input esté incompleta? Digo esto porque cuando elijo un número de torta que no está o ingreso una letra, el programa se cae debido a un KeyError.
Esto se podría solucionar agregando " respuesta = '' " en cada bloque except.

**Comment by igbasly** [comment]
Hola @m1guel-angel :v:
Efectivamente como bien mencionas, es posible que se nos haya pasado considerar ese caso borde para los inputs 😅 .
Como se trata de un caso específico y que no afecta directamente el contenido a evaluar, sino que la experiencia de usuario, puedes agregar como mencionas una línea con ese código para repetir la solicitud del input o puedes dejarlo como está e ingresar únicamente una de las opciones que ahí se muestran.

Espero que se entienda, haznos saber cualquier cosa :wink:
Éxito en la actividad! :tada:
