### ISSUE TITLE
Variación en los parametros

### ISSUE THREAD

**Issue by notyourlasagna** [IIC2233/syllabus#470]
Hola, si cambiamos los valores azules de la formula, el resultado de la probabilidad ya no sería entre [0,1], como dice textual el enunciado. Que debemos hacer?

**Comment by jitorcas** [comment]
Hola! @notyourlasagna 

No variaremos los parametros de tal forma que corrompan el flujo de tu programa, así que no te preocupes por eso!

**Comment by YehudaGurovich** [comment]
Entonces tenemos que ponerlos como variables o no?

**Comment by jitorcas** [comment]
@YehudaGurovich Tienen que ponerlos como parámetros dentro de tu archivo `parametros.py`

Puedes asignarle el nombre `denominador_sanar_lesión` para hacerla descriptiva.
