### ISSUE TITLE
La acción PLANTAR

### ISSUE THREAD

**Issue by DonJavi-538** [IIC2233/syllabus#470]
En el enunciado se muestra que plantar corresponde a una acción que gasta energía, pero no se especifica en ningún momento cuánta energía gasta dicha acción.

"El archivo parametros_acciones.py contiene los costos de energ´ıa de todas las acciones existentes en el juego. La informaci´on ser´a entregada de la siguiente manera:

ENERGIA HERRAMIENTA: cuanta energ´ıa pierde Enzo al ocupar una herramienta.
ENERGIA COSECHAR: cuanta energ´ıa pierde Enzo al cosechar un cultivo.
ENERGIA RECOGER: cuanta energ´ıa pierde Enzo al recoger un recurso del suelo."

**Comment by ariela1** [comment]
Hola! Esto ya fue preguntado en la issue #408. Espero que te ayude :)
