### ISSUE TITLE
Cantidad inicial de medallas de una delegación

### ISSUE THREAD

**Issue by sebastian-contreras-r** [IIC2233/syllabus#471]
¿Las delegaciones pueden tener una cantidad inicial de medallas distinta de cero en `delegaciones.csv`? Si es así, ¿se debe otorgar el bonus de excelencia y respeto por cada medalla inicial?

**Comment by jitorcas** [comment]
Hola! @sebastian-contreras-r 

Puedes asumir que nunca vendrán con un número mayor que 0. **Sin embago**, debes cargar la cantidad de medallas desde el archivo `delegaciones.csv` (independiente que siempre será 0).

Mucho éxito! 🥇
