### ISSUE TITLE
Duda AF5: problema con encriptar receta al crear la torta

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#471]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Tenia algo hecho para este decorador pero me di cuenta que esta mal, necesito corregir los argumentos que le doy al método original, ya que esta hecho para tortas y le estaba pasando una lista, sin embargo, al corregir esto llego a un error de import.

Para crear la torta que usare de parametro necesito tener cargada la clase Torta, pero si importo esta clase a decoradores_cocina se genera un error de import que no logro solucionar.

¿Cómo se arreglaría ese import error?

**Comment by igbasly** [comment]
Hola @Pabloski100 :v:

No estoy seguro cual es el *import error* que mencionas, pero de todas formas, no debería ser necesario que importes la clase `Torta` en el archivo de decoradores. Esto ya que toda la información que necesitas la recibe el decorador.
Te recomiendo revisar como funciona el método `escribir_receta` de `DCCocina` y el método `encriptar` para entender mejor como programar el decorador 😉 .

Quedo atento a cualquier otra duda, mucho éxito!! :tada:

**Comment by Pabloski100** [comment]
Es que según lo que entendí, el método escribir receta recibe como parámetro una instancia de Torta, y vi en otro issue que el método trabaja mal si no es así, por ejemplo, no tiene de donde sacar el nombre de la torta

**Comment by igbasly** [comment]
Efectivamente, el método `escribir_receta` recibe una instancia de `Torta`, por eso te decía que revisaras cómo funciona el método.
Y a esto mismo me refería cuando digo el el método recibe toda la información necesaria, en este caso, una instancia de torta que contiene la receta a encriptar.
