### ISSUE TITLE
utilidades.py

### ISSUE THREAD

**Issue by connandiaz** [IIC2233/Syllabus#471]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Si yo importé el archivo utilidades.py y lo usé en la función de carga de datos, pero luego el .gitignore me pide ignorarlo, significa que saldría error en mi tarea o van a corregir con otro archivo del tipo utilidades.py?

**Comment by Hernan4444** [comment]
Y complementando, nosotros mismos pondremos nuestro propio `utilidades.py` en tu entrega al momento de revisar. Este archivo tendrá la misma información que tiene el público. Esto es para evitar que hayan modificado, por ejemplo, las nametupled.

Así que no te preocupes por la ausencia de ese archivo, si es que le pusiste algún código dentro, como dice Julio, ahí si hay que sacarlo y ponerlo en otro módulo que no sea ignorado.

Saludos!

**Comment by viceandres** [comment]
creo que la pregunta se refería a si uno usa los datos dentro de utilidades.py al implementar la funcion cargar_datos, algo asi como utilidades.(...). si se ignora utilidades.py esos datos no se importaran?
