### ISSUE TITLE
stock vendedores

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#471]
se asume que los vendedores tienen igual cantidad de productos de ese tipo?
por ejemplo, si mi `stock_a = 5` y `stock_b = 10` y mi `stock=7` (el resultante del `randint()`) por decir, entonces **cada producto de la categoría correspondiente** a ese vendedor (digamos mexicana), va a tener `cantidad = 7` productos de cada tipo de producto mexicano para ese día?

**Comment by egromero** [comment]
Hola

**Del enunciado 5.1.2**
  
![captura de pantalla 2017-10-09 a la s 13 42 27](https://user-images.githubusercontent.com/26122117/31349097-26dd8f7e-acf8-11e7-9e58-2c8201fddc17.png)

Saludos

**Comment by rihanuch** [comment]
No lo había entendido muy bien en principio, por eso pregunte 😅 , asumo que eso es un sí, jajaj, gracias!
