### ISSUE TITLE
Duda sobre el tiempo en los test de carga de datos

### ISSUE THREAD

**Issue by Yeps3nM** [IIC2233/Syllabus#471]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Tengo algunas funciones en que corren los test de correctitud pero los de carga de datos cuando son desde el L, da fuera del tiempo límite. Hay alguna forma en que yo pueda saber que línea me está dando más tiempo o algún consejo para manejar estos problemas? Gracias!

**Comment by NachoRinda** [comment]
Hola, a la rápida puedes hacer que la función retorne un iterable vacío e ir línea por línea comentando hasta ver cuando los tests grandes comienzan a fallar por output erróneo en vez de por tiempo. Usualmente siempre el problema es algún product o ciclos anidados. Por otro lado, puede usar el módulo <time> para que te muestre el tiempo exacto que se demora cada parte que quieras, sin embargo, esto no es tan relevante pues solo necesitas saber cual parte de tu lógica es la que te hace demorar, no por cuanto.
