### ISSUE TITLE
servidor escuchando

### ISSUE THREAD

**Issue by niguzman** [IIC2233/syllabus#471]
Hola,
Cuando usamos socket.listen(), se puede dejar el paréntesis sin el número de conexiones máximas?
Es decir, dejar la opción de que se pueda conectar "n" clientes al servidor

**Comment by Polea012** [comment]
Hola! Efectivamente, puedes dejar la función ```socket.listen()``` sin un número como parámetro y te permitirá realizar conexiones sin un límite especificado previamente.  

Es importante mencionar eso sí que si uno no especifica una cantidad límite de conexiones en ```socket.listen()```, la función define un límite de manera interna (o sea, las conexiones no son infinitas estrictamente hablando). La cantidad definida internamente, sin embargo, es una lo suficientemente considerable para que no te afecte en el contexto de tu programa.

Espero haberte ayudado! Saludos!
