### ISSUE TITLE
QImage: out of memory, returning null image

### ISSUE THREAD

**Issue by jperalta2202** [IIC2233/syllabus#471]
Hola. Acabo de implementar mi reloj interno del juego, y al ejecutar el programa funciona bien durante un tiempo y luego se cierra el programa y aparece el error "QImage: out of memory, returning null image"

**Comment by jmwielandt** [comment]
Hola!

¿Puedes dar más detalles? ¿Siempre ocurre cuando tu contador llega al mismo valor? También sube tu código a tu repo para poder ayudarte de mejor manera.

Saludos!

**Comment by jperalta2202** [comment]
Hola, solucione el problema cambiando mi función que actualiza la pantalla, al parecer era mucha información actualizándose muy rápido y eso producia el error. Gracias
