### ISSUE TITLE
Método agregar_topping is not callable

### ISSUE THREAD

**Issue by AlfonsoBadilla** [IIC2233/syllabus#472]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Buenasss, en cierta parte de la ejecución del código cuando se debe llamar a este método, la consola me arroja el error mencionado en el título, además dice que este método es "NoneType" siendo que es un método definido desde el inicio. Se me ocurre que quizás se sobreescribió "agregar_topping" pero no tendría por qué dou.

**Comment by aaossa** [comment]
Hola @AlfonsoBadilla , considerando que la actividad es de decoradores y al error que mecnionas, sospecho que te faltó retornar el *wrapper* dentro del decorador 🤔 Recuerda que cuando defines un decorador debes retornar la nueva función 😱 Avísame si es eso 🙌

**Comment by AlfonsoBadilla** [comment]
Holaaa, ya encontré el error, tenía los return para todo pero tenía una indentación de más en la del wrapper.

Igual gracias por la respuesta, me hizo fijarme en eso juasjuas 👁
