### ISSUE TITLE
Límite de paciencia persona

### ISSUE THREAD

**Issue by matiaseche** [IIC2233/Syllabus#472]
> **Límite de paciencia:** En este caso, existe un factor que representa la cantidad de minutos
que un alumno puede esperar en una cola sin aburrirse. El lı́mite de paciencia parte siendo
cada dı́a un randint entre αpaciencia y βpaciencia minutos; y **por cada puesto que rechaza el
alumno, el factor se reduce en 5 minutos, hasta llegar a 0**. Cuando el alumno decide comprar
a un vendedor, debe estimar según la rapidez de atención del vendedor y la cantidad de
personas en la cola, cuánto tiempo esperará. Si su lı́mite de paciencia es igual o mayor al
tiempo que se demorará el vendedor, entonces decide ir a ese puesto y unirse a la cola. En
caso contrario, se decide ir al siguiente puesto.

Para la parte en negrita, ¿el factor se reduce en 5 minutos cada vez que rechace **por límite de paciencia**, o también se reduciría si no le alcanza la plata, o no hay stock?

**Comment by egromero** [comment]
Holaa, 

Tal como dices, la idea es que el factor se reduzca por cualquiera de los rechazos (paciencia, dinero o stock). Perdón si no queda bien claro.

Saludos!

**Comment by dmolina2** [comment]
Respecto a la paciencia de las personas UC hay algo que no me queda claro.
En el enunciado dice que :
![a1](https://user-images.githubusercontent.com/30671776/31458182-a8369ca2-ae95-11e7-8d63-98581c8bda1a.png)
Respecto a la parte que dice "en caso contrario, se decide ir al siguiente puesto", esto tiene que ver con lo que dice la estadística 13:
![a2](https://user-images.githubusercontent.com/30671776/31458273-f98fca74-ae95-11e7-8c5d-f63d67a8e608.png)
Es decir, si la persona estima que el tiempo que demorará en la cola es a mayor a su paciencia, entonces equivale a que "abandonó una cola de espera"?

**Comment by egromero** [comment]
@dmolina2 

Considera para la estadística solo los eventos de abandonar la cola, esto puede ocurrir solo una vez que la persona se agregó a una cola, es decir, el "decide ir al siguiente puesto" es para analizar si entra o no a la cola, por lo que no se consideraría como "dejar" la cola.

Espero esto aclare tu duda.
Saludos

**Comment by dmolina2** [comment]
@egromero 
Para ver si me queda claro, una persona primero antes de entrar a una cola de un puesto analiza los 3 casos (stock, dinero y paciencia), si cumple con estas 3 la persona entra la cola del puesto. Luego, una vez que esta haciendo la cola tiene que estar constantemente viendo si sigue cumpliendo con estas restricciones, ya que podría ocurrir que llegue un funcionario y justamente el puesto de comida quede sin stock y así la persona saldría de la cola del puesto. ¿Es esto correcto?

Gracias

**Comment by egromero** [comment]
Así es! Ya que de alguna forma se tiene que dar el evento: “Dejar la cola”

**Comment by dmolina2** [comment]
@egromero 
Me surgió una nueva duda con la paciencia, 
En el caso que una persona compra un snack cuando entra a la universidad y por algún motivo decide ir al siguiente puesto en su lista de oreferencias y luego compró en otro. Después, cuando va a comprar el almuerzo, el límite de paciencia parte con 5 minutos menos debido a que cuando compró un snack se movio un puesto en su lista de preferencias. ¿Es esto correcto?

**Comment by egromero** [comment]
@dmolina2  Puedes considerar que las comidas son independientes, esto quiere decir que no influiría el posible descuento de paciencia en el snack para el almuerzo. De todas formas especifícalo en tu README.

Saludos
