### ISSUE TITLE
Suposiciones Tarea4

### ISSUE THREAD

**Issue by sebacruzd** [IIC2233/Syllabus#472]
Estimados,

Dado que se han generado varias preguntas de la tarea sobre si se deben o no hacer ciertas suposiciones,  a modo de respuesta general, sí pueden hacerlas siempre y cuando no reduzcan la dificultad del problema y no violen otras partes del enunciado.

Por ejemplo, si en una parte se habla sobre reuniones de ayudantes y profesores, un supuesto adecuado sería que esto sea de lunes a viernes, ya que es más fácil juntarse en la universidad un día de semana. O si saben que los tareos se juntan todos los martes, que sus reuniones sean ese mismo día.

Si hay algo que creen que realmente no se puede suponer, en ese caso hagan un issue para preguntar. En caso contrario, especifiquen en su README.md los supuestos que hicieron.

Saludos!

**Comment by HenryBlairG** [comment]
Una dudilla loca: en el archivo de escenarios.csv hay escenarios en que algún valor es "-".¿Esto está abierto a hacer suposiciones nuestras? o tienen alguna preferencia de que ocurra algo? Sadulos 😃

**Comment by Hernan4444** [comment]
@HenryBlairG te recomiendo que vuelvas a leer el enunciado, la respuesta está ahí. (Pagina 11 párrafo 2)

Saludos!!
