### ISSUE TITLE
Actualización calendario

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#472]
Hola!
Dado el mail que enviaron sobre la actualización del calendario, descargue este nuevamente pero me aparecen todas las fechas iguales que antes. Entonces, quería cerciorarme de que el único cambio fuera la opción de segunda entrega de la tarea 3.

**Comment by fringlesinthestreet** [comment]
@santilaguna Hola

Ya fue actualizado! (de hecho hace unos días jeje).
