### ISSUE TITLE
Linea vertical cantidad de palabras vscode

### ISSUE THREAD

**Issue by jorgemouat** [IIC2233/syllabus#472]
Hola! Queria saber como puedo agregar una linea al vscode para ver la altura de las 100 palabras ?? Muchas gracias.

**Comment by retamalcito** [comment]
¡Hola @jorgemouat!

En VSCode, para añadir la línea vertical a la altura de 100 caracteres, debes entrar al archivo `settings.json` del editor y añadir la siguiente línea: `"[python]": {"editor.rulers": [100]},` en el diccionario. Si no sabes cómo acceder a este archivo, [aquí](https://supunkavinda.blog/vscode-editing-settings-json) hay un link que lo explica.

¡Saludos! :wave:
