### ISSUE TITLE
Duda sobre test_carga_datos

### ISSUE THREAD

**Issue by mVal919** [IIC2233/Syllabus#472]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, muy buenas tardes.
¿Qué se supone que está comparando en los test de carga de datos?
Por ejemplo, si veo algo así:
![image](https://github.com/user-attachments/assets/ace7516f-a515-4904-bffa-131b8abe82d8)
Que me comunica el AssertionError? El tiempo que se demoró el test? Porque no logre entender eso de que se "Evaluará el comportamiento de la solución implementada con respecto a la eficiencia del código y su capacidad de trabajar con archivos de diversos tamaños."
Eso, muchas gracias!

**Comment by AlonsoPlaza** [comment]
Hola, el error en este caso es que el int que retornó tu función (38) no es igual al esperado (101). Los test de carga revisan que tu solución funcione correctamente (resultado correcto en menos del tiempo límite) trabajando con archivos grandes mientras que los de correctitud revisan los casos bordes. Si tienes más dudas sobre como interpretar los errores te recomiendo revisar la issue #423

**Comment by mVal919** [comment]
Aaaaaaah ya
Ok, muchas gracias!
