### ISSUE TITLE
Clase server hereda de QWidget

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#472]
Hola, es posible que mi clase server herede de QWidget? Esto debido a que al hacer la comunicacion de señales entre cliente e interfaz, me aparecia un error: [especificado aquí](https://stackoverflow.com/questions/28202273/working-directory-error). Por lo que tuve que hacer que heredara desde QWidget para que funcionara correctamente (era solo hacer que se emitiera la señal desde el cliente al frontend que se abriera la ventana).

**Comment by Polea012** [comment]
Hola! Tengo una duda respecto a tu error y el link de StackOverflow que entregas. 

Comenzaré explicando el problema que me parece que tienes:

El problema que explicas de que tu clase Server ( y también Cliente) no permite usar señales con la interfaz se debe a que ```pyqtSygnal``` (y los objetos de ```PyQt5```, en general) exigen estar en un ambiente de objetos que sean de ```PyQt5```, específicamente, deben ser objetos del tipo ```QObject```. Debido a esto, si quieres usar señales en clases éstas deben heredar de ```QObject```.  En el caso de tu clase Server (o Cliente), si deseas utilizar señales te recomiendo hacer que la clase herede de ```QObject``` en vez de ```QWidget``` (quien a su vez hereda de ```QObject``` y por eso resuelve el problema también) por un tema de modelación. Tanto el servidor como el cliente en la lógica de tu tarea no tienen aspectos gráficos por sí mismos y no deberían ser un ```QWidget```.

Ahora, debido a que el link que entregas no habla sobre este punto, sino de problemas con PyCharm, me gustaría que me detallaras más cuál es el problema que estás teniendo. Aún así, ten el punto que expliqué antes en consideración.

Saludos.

**Comment by VicenteMerino** [comment]
Hola, efectivamente era lo que tu decias mi error. Me equivoqué de link al hacer la issue, por eso la confusión :(

**Comment by Polea012** [comment]
Hola! No hay problema por la confusión. Entonces para solucionar tu problema  te recomiendo realizar herencia de ```QObject``` en vez de ```QWidget``` por el punto que expliqué anteriormente.

Si tienes más consultas, no dudes en preguntar. Saludos y éxito en tu tarea.
