### ISSUE TITLE
Recargar energía

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#472]
Como se debe recargar la energia? Mientras el personaje se mueva dentro de la casa o una vez haya colision entre el personaje la energia aumenta solo una vez hasta que el personaje salga y entre otra vez. Tambien, que pasa si la interseccion entre el personaje y la casa es solo de un pixel? También vale? Saludos

**Comment by Dnpoblete** [comment]
Hola @dgzmr como dice el enunciado: "al caminar sobre ella, permite a Enzo recargar su energía e iniciar un nuevo día de forma automática", por lo que dependiendo de si realizarás el bonus de la casa o no cambia un poco el como hacerlo. Si no realizas el bonus, la idea es que al colisionar con la casa recargue su energía y comience un día nuevo automáticamente, si vuelve a chocar con la casa tendría que ocurrir lo mismo. En el caso de hacer el bonus como cambia un poco, y como no se explicita en el enunciado puedes escribir en el ReadMe si ocurre apenas entras a la nueva ventana o al salir de esta.
Con respecto a lo de si un pixel vale, la respuesta es sí ya que estaría tocando la casa.

Espero haber respondido tu duda y éxito con la tarea! 😄

**Comment by dgzmr** [comment]
Gracias
