### ISSUE TITLE
Duda interpretar resultado 'AssertionError: False is not true'

### ISSUE THREAD

**Issue by mVal919** [IIC2233/Syllabus#473]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola otra vez.
![image](https://github.com/user-attachments/assets/df093682-af85-41d8-bccd-0fb163b6ef99)
Que implica el mensaje de error 'False is not true'? O que otra informacion extra se puede sacar ademas de que tengo el resultado malo
Eso, muchas gracias!

**Comment by AlonsoPlaza** [comment]
Hola, el error implica que un elemento esperado no se encuentra en tu resultado. No se puede sacar mucha más información relevante.
