### ISSUE TITLE
Error en todos_test, pero no en el individual

### ISSUE THREAD

**Issue by fmandiolafellay** [IIC2233/Syllabus#473]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, en el todos_test todo me tira ok excepto un test de cargar_datos, pero en el individual no me tira error, que puede ser? Igualmente lo que me parece raro es que si mi archivo no cargara datos correctamente siento que lo demás no debería funcionar. 
![Captura de pantalla (90)](https://github.com/IIC2233/Syllabus/assets/91400597/1068a4f7-7dfc-4dce-8fb8-6a1b472afa05)
![Captura de pantalla (91)](https://github.com/IIC2233/Syllabus/assets/91400597/b6e4966f-8060-4b76-98ab-0573285f444b)

**Comment by Segismundios** [comment]
Hola @fmandiolafellay, acabo de probar tus tests y me arroja todos correctos usando todos_tests.py. Podrías revisar si tus archivos de tests y data están actualizados. 

Quedo atento a cómo te va, saludos!

**Comment by fmandiolafellay** [comment]
Debe ser mi todos_test entonces, si no entiendo mal te tiro ok el todos_test.py completo?

**Comment by Segismundios** [comment]
Síi, me pasó todos los tests usando todos_tests.py
