### ISSUE TITLE
Properties abstractas

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#473]
Hola. Quería saber como se puede hacer para construir un propertie en donde solo quiero que el setter sea abstracto. Se puede? Como se pone en las clases hijas? Saludos :)

**Comment by moquezada** [comment]
Hola @tedroppelmann!

Tuve que investigar un poco para saber como se hace lo que mencionas. La documentación de Python menciona que puedes indicar qué componentes de la property serán abstractos.

```python
class C(ABC):
    @property
    def x(self):
        ...

    @x.setter
    @abstractmethod
    def x(self, val):
        ...

class D(C):
    @C.x.setter
    def x(self, val):
        ...
```

Solo las componentes abtractas de la property deben ser actualizadas en las subclases. Este es el [link ](https://docs.python.org/3/library/abc.html#abc.abstractproperty)a la documentación que te permitirá ver más detalles al respecto 😄 

Saludos!
