### ISSUE TITLE
Gui

### ISSUE THREAD

**Issue by eitandv** [IIC2233/Syllabus#473]
Hola! 
Estoy teniendo problemas para leer las consultas, por lo que quería preguntar: ¿Es verdad que no van a corregir nada del código que no se muestre en la gui? Ademas, ¿hay algún built-in de python que ayude a procesar las consultas en este formato? 
Gracias de antemano!

**Comment by Hernan4444** [comment]
@eitandv ¿que error estás teniendo en relación a leer las consultas? Porque la interfaz se encarga directamente de abrir el archivo procesarlo y entregarle la lista con los argumentos en el formato que corresponde.

**Comment by Hernan4444** [comment]
@eitandv te recomiendo fuertemente intentar lograr hacer una función que al menos lea las consultas más sencillas, porque tal como dice en el enunciado: 

> Solo se corregirá los output que aparecen en la interfaz, no se evaluará nada por consola.

Y en caso de no tener dicha función, se tendría que corregir por consola y eso se avisó con tiempo que no se evaluará. Uno de los objetivos es utilizar la interfaz.

Recuerda que puedes utilizar recursión para hacer el interprete de lista a elementos que entienda mejor tu librería.

**Comment by eitandv** [comment]
ok, gracias!
