### ISSUE TITLE
stock QuickDevil

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#473]
en el enunciado se plantea que

> enfoque pescetariano a la empresa; es decir, solo venden comida vegetariana y productos de animales marinos

esto es en manera de "trivia" (para hacer el enunciado más ameno), o realmente es así, por lo que se tendrán **sólo** ese tipo de productos (en este último caso, cuáles serían?)

**Comment by cilopez** [comment]
Es en manera trivia :sweat_smile: , se nos escapó decir que _Quik Devil_  vende enrealidad todos los tipos productos.

**Comment by jotramon** [comment]
los precios de todos los productos seria los mismos para quik devil que para los locales? si la idea es que sea más caro para que la gente no quiera comprar alli. si no es así, que precios consideramos para quik devil?

**Comment by cilopez** [comment]
Los precios iniciales, ojo que nunca se declara que _Quick Devil_ cambia sus precios.
