### ISSUE TITLE
Medallas en mostrar estado 

### ISSUE THREAD

**Issue by fedezang** [IIC2233/syllabus#474]
Hola, en el ejemplo del enunciado al mostrar el estado de la competencia se imprime el medallero, pero este está mostrando la cantidad de medallas que ganó cada Delegación por cada Deporte. 
Sin embargo, en las entidades nos piden guardar el medallero solo como la cantidad de medallas que tiene cada Delegación (En total, no por deporte).
Es necesario mostrar el medallero por cada deporte?
![Captura de Pantalla 2020-09-09 a la(s) 21 20 58](https://user-images.githubusercontent.com/62078222/92667467-6046ba00-f2e2-11ea-89db-7b7e992fe5f0.png)
.

**Comment by jitorcas** [comment]
Hola! @fedezang 

En el método `Mostrar estado de la Delegación y sus Deportistas` de`Campeonato`, se especifica lo siguiente:

> _Por último, se deberá mostrar el estado actual de la competencia, que incluye el día actual en el cual está, y los resultados que ha obtenido cada delegación en las diferentes competencias._

Por lo tanto, debes mostrar los resultados de las delegaciones en las diferentes competencias, la forma en que lo hagas es libre! puedes seguir el formato que se ejemplificó o el que te acomode más, pero deben estar los resultados que ha obtenido cada delegación (además de la cantidad de medallas totales). 

Mucho éxito! 🥇

**Comment by denisseleiva** [comment]
Hola!!! me vengo a colgar de esta issue :P
¿Es necesario mostrar el resultado de las competencias en los días de entrenamiento? ¿El resultado que se muestra es como "histórico"? ¿O puedo mostrar el resultado de las competencias sólo en el día de las competencias?

**Comment by denisseleiva** [comment]
Hola!!! @jitorcas 
me vengo a colgar de esta issue :P
¿Es necesario mostrar el resultado de las competencias en los días de entrenamiento? ¿El resultado que se muestra es como "histórico"? ¿O puedo mostrar el resultado de las competencias sólo en el día de las competencias?

**Comment by jitorcas** [comment]
Hola! @denisseleiva 

Lo único que está explícito en el enunciado es que se muestren los resultados de la competencia del día, sin embargo tienes toda la información para mostrar el "histórico". Personalmente pondría ambos, pero el que se evalúa que esté correcto es el diario.

En cuanto a lo del día de entrenamiento, la idea es que llames al mismo método, así que podrías mostrar lo mismo ambos días.

**Comment by denisseleiva** [comment]
Buenisimoo, muchas gracias! @jitorcas
