### ISSUE TITLE
Timed out waiting for launcher to connect

### ISSUE THREAD

**Issue by emyskog** [IIC2233/syllabus#474]
Al tratar de correr el codigo en Visual Studio me aparece un error de "Timed out waiting for launcher to connect"
En mi launch.json aparece:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}
![57ed01a4-6c41-4ea4-9cbd-cac5b86d7f12](https://user-images.githubusercontent.com/61996414/79235749-04166180-7e3a-11ea-9805-9a961aa7b17e.jpg)
![6aca3fbb-79aa-4179-93a9-d0746b65f998](https://user-images.githubusercontent.com/61996414/79235756-0678bb80-7e3a-11ea-8e3d-688942dcbf5f.jpg)

**Comment by JosefaPaz** [comment]
Hola @emyskog !

Pudiste solucionar tu error?

**Comment by emyskog** [comment]
Sii

**Comment by JosefaPaz** [comment]
Excelente! @emyskog  podrías explicar cómo lo solucionaste por si alguien llega a tener el mismo error a futuro?

Gracias 😄

**Comment by emyskog** [comment]
Cerre y abri el programa de nuevo
