### ISSUE TITLE
dinero confiscado/ multas

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#474]
si un vendedor huye, el dinero que ha ganado durante el día se le confisca, o se le confisca el total del stock restante por los respectivos precios?

a que se refiere el enunciado con 

> Cantidad de multas que realizó cada tipo de Carabinero.

?

**Comment by cilopez** [comment]
Se les confisca sólo el total del stock y si lo cuantificas como dinero perdido sería multiplicar los productos confiscados por los precios actuales del producto. La cantidad de multas sería la cantidad de veces que se confiscó a algún vendedor.
