### ISSUE TITLE
Error Conexión servidor-cliente threads [Tarea 3]

### ISSUE THREAD

**Issue by mistico0121** [IIC2233/syllabus#474]
Hola

Al momento de intentar conectar un thread servidor a un thread cliente, al momento de ejecutar la función listen_client_thread como target del thread cliente (similar al funcionamiento de la actividad Cachipún de la Ayudantía 12), no se cae el servidor, pero se desconecta el cliente y se termina su hilo, y la ventana en la que corre el servidor tira el siguiente error:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Max\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Max\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/Max/Desktop/IIC2233 - Programación Avanzada 2019-1/mistico0121-iic2233-2019-1/Tareas/T03/server/servidor.py", line 88, in listen_client_thread
    response_bytes_length = client_socket.recv(4)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto

He buscado, y hay muchas causas por la cual puede producirse este error. Estoy usando un cliente similar al de la ayudantía también, así que no sé porque se está produciendo el error al intentar conectar.

Gracias, y saludos

**Comment by bimartinez** [comment]
Hola @mistico0121 

Podrías señalar lo que te muestra el cliente al intentar conectarse al servidor?

Saludos!

**Comment by mistico0121** [comment]
> 
> 
> Hola @mistico0121
> 
> Podrías señalar lo que te muestra el cliente al intentar conectarse al servidor?
> 
> Saludos!

Se cae, no dice nada mas, ni tampoco tira error.

**Comment by mistico0121** [comment]
Estaba excluyendo el error, por eso no aparecía 

Al momento de caerse, el cliente tira lo sgte
[WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión

**Comment by bimartinez** [comment]
Podrías subir el código a tu repo e indicar los archivos con problemas por favor!

**Comment by mistico0121** [comment]
> 
> 
> Podrías subir el código a tu repo e indicar los archivos con problemas por favor!

Está listo, los archivos con los que tengo problemas son "servidor.py" y "cliente.py", ubicadas respectivamente en las carpetas "server" y "client" de mi repositorio.

Por mientas, voy a intentar hacelas de nuevo.

**Comment by mistico0121** [comment]
No encontré la solucion y terminé haciendo las clases Cliente y Servidor de nuevo, y ahí si funciono. Ya fué, pero gracias!

:(
