### ISSUE TITLE
Error al correr test_elementos_prohibidos

### ISSUE THREAD

**Issue by consbb** [IIC2233/Syllabus#474]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, intento correr test_elementos_prohibidos.pyc y me sale un error, no se como arreglarlo.
![Captura de pantalla 2024-05-27 135350](https://github.com/IIC2233/Syllabus/assets/162772225/a33b8ac6-1da3-4318-8d6d-4d179e825c10)

**Comment by consbb** [comment]
ya funciono!!!

**Comment by Jerrazuriz** [comment]
A mi me aparece ese error. ¿Que hiciste para arreglarlo?

**Comment by consbb** [comment]
@Jerrazuriz nose que hice, simplemente lo volvi a correr y funciono :(
