### ISSUE TITLE
Instanciar QWidget con atributo

### ISSUE THREAD

**Issue by fcsanchez** [IIC2233/syllabus#474]
class Automovil (QWidget):
  ...

a = Automovil ('Ford')
b = Automovil ('Kia')

a.show()
b.show()

Se puede hacer esto de alguna forma? que todos los ejemplos que he visto las instancias no tienen atributos

Gracias

**Comment by pwillmer** [comment]
Creo que te refieres a esto:

class Automovil(QWidget):
        def __init__(self, marca):
                super().__init__()
                self.marca = marca

**Comment by lily416** [comment]
@fcsanchez es como dice @pwillmer, tanto las ventanas como los _widgets_ pueden recibir parámetros al momento de instanciarlas.
 
Saludos y éxito en sus tareas 👋🍂
