### ISSUE TITLE
metodo save_file

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#474]
Hola no me queda claro si la idea de save_file ,dado que recibe los mismos parametros que process queries y  dado que no se puede crear metodos y atributos, es entonces  volver a ejecutar las consultas ya que de lo contario la unica forma que veo permitida de implementar este metodo es que process queries sea una funcion generadora, pero el problema de esto seria que los resultados de la misma solo aparecirian en la interfaz si es que se llama a generar archivo.

**Comment by Hernan4444** [comment]
@sjkinast precisamente es volver a ejecutar las consultas, pero ahora el output va a un archivo mientras que en el otro método el output va a la consola

**Comment by sjkinast** [comment]
porque por ejemplo si  hay mas de un  error "N/A"   como los datos en los generadores no estan ordenados podria ser que se encuentre un error distinto que en la ejecucion anterior.
Tambien por ejemplo cuando se piden los 5 actores en popular actors y tengo 3 que tienen dos  peliculas y 6 que tienen una, la consulta entregaria los 3 que tienen mas dos que tienen menos.

**Comment by Hernan4444** [comment]
pero cuando uno hace una consulta vuelve a crear todos los generadores. Si sale esto en la interfaz
`["successful_actors", ["take_movie_while", ["load_database"], "IMDb", ">", 30]]` y pido process_consult
1) abres el archivo
2) tomas las películas mientras IMBb sean mayor a 30
3) Buscas actores
4) Escribes en pantalla.

Ahora si esa misma consulta está en la interfaz y pones save_file
1) abres el archivo
2) tomas las películas mientras IMBb sean mayor a 30
3) Buscas actores
4) Escribes en un archivo.

El procedimiento es exactamente el mismo.

**Comment by Hernan4444** [comment]
Talvez estás modelando esto como que la librería tiene memoria de las consultas anteriores y su respuesta depende de lo que se consultó antes (eso se me viene a la cabeza), pero aquí cada consulta es independiente, las únicas consultas que pueden afectar el resultado son las anidadas como en el ejemplo que te puse donde pido los actores de una consulta que filtró datos, pero si yo tengo:
```
[
  ["successful_actors", ["take_movie_while", ["load_database"], "IMDb", ">", 30]],
  ["take_movie_while", ["load_database"], "IMDb", ">", 30]
]
```
esas son 2 consultas diferentes y no se relacionan en nada.

En el enunciado se indica que debe ser:
![image](https://user-images.githubusercontent.com/15641721/39676105-10f6d69c-513b-11e8-96b9-eabef812ace8.png)

Y por lo tanto, cada consulta la procesas, tiras su output y pasamos a la siguiente consulta.

**Comment by santilaguna** [comment]
@Hernan4444 una duda que me queda es si debo cuando se procesan las querys realizar ambas acciones (si indican realizar todas las consultas) o sólo escribirlas en pantalla y sólo escribir en el archivo cuando se usa save file. No sé si me explico

**Comment by mplazadelosreyes** [comment]
@Hernan4444 a mi también me dan resultados diferentes. Por ejemplo en best comments si tengo "empate" porque digamos que tengo 6 películas con 1 comentario positivo, pero el usuario solo me pide las 3 mejores peliculas, yo puse que me eligiera al azar 3 de esas 6 (voy a poner eso en el readme), entonces si corro nuevamente esa consulta, quizás no me van a salir las  mismas 3 de antes, entonces ahí el resultado de la consulta seria distinto.

**Comment by Hernan4444** [comment]
@santilaguna solo se escribe en el archivo cuando haces save_file. En otro caso es siempe en la interfaz.
@mplazadelosreyes en ese caso no hay problema, porque tomaste una decisión en caso de empate, pero si hacemos consultas donde no hay empate, esperamos ver el mismo resultado en la interfaz o cuando hacemos save file

Saludos ✌️

**Comment by santilaguna** [comment]
Oka Gracias!
