### ISSUE TITLE
Progreso funcionalidad en Actividad

### ISSUE THREAD

**Issue by josemlira** [IIC2233/Syllabus#474]
se calcula como 0.3 * Si + 0.7 * P + 0.1 * C según enunciado, están malos los porcentajes, esto lo arreglamos con un supuesto o cómo debiesen ser?

**Comment by iqacevedo** [comment]
Hola,

Tal como dices habia un error, ya se actualizo el enunciado con la formula correcta. Ahora quedo asi:

![progreso funcional](https://cloud.githubusercontent.com/assets/13748732/26026796/bd128e12-37d8-11e7-846f-50998447f3ec.png)

Saludos !
