### ISSUE TITLE
Problema KeyPressEvent

### ISSUE THREAD

**Issue by jiurrutia** [IIC2233/syllabus#475]
Hola, estoy implementando la combinación de teclas que me recargan la energía o que me dan dinero. Pero al momento de apretar las teclas m+n+y al mismo tiempo solo me reconoce las letras m + n , algo similar ocurre si trato de hacer m+n+u o algunas otras combinaciones, sin embargo, con otras no sucede. El caso de k+i+p si funciona para recargar la energía. Quisiera saber si es por algo en particular y como podría arreglarlo. Estoy trabajando en un Mac, usando el key press y key release con sets. Gracias de antemano.

**Comment by tomasalvarez13** [comment]
Hola, tengo el mismo problema pero con k+p+i. Todas las combinaciones sin i me funcionan bien, puedo reemplazar k+p+i por k+p+o y especificarlo en el readme?
Gracias

**Comment by Dnpoblete** [comment]
Hola @jiurrutia  y @tomasalvarez13  esta duda ya fue respondida en la issue #455.

Éxito con la tarea! 😄

**Comment by maormeno** [comment]
Me pasa lo mismo con las teclas M + N + Y, presionándolas en ese orden y sin presionar ninguna tecla entre medio (que es la respuesta dada en al issue). Me funciona perfecto con K + I + P, pero con las primeras me funciona solo a veces cuando las presiono muy rápidamente y en cualquier orden (en casos muy random), pero nunca cuando las hago en el orden correcto (y en la forma correcta). También hago un print de cada tecla cada vez que la voy presionando, y resulta que también llega solo hasta M + N, pero la Y la registra después de presionar las 3 y soltarlas (siendo que el print lo tengo en el keyPressEvent, y en el keyReleaseEvent solo tengo que saque la tecla del set)
