### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by MINGOD24** [IIC2233/syllabus#475]
Hola,
con respecto a la entrega del diagrama de clases me quedo una duda. Como se debe escribir en el diagrama los properties, abstract method, setters, etc.¿ Existe algun ejemplo aparte del de los contenidos que no contiene estos metodos?.

**Comment by moquezada** [comment]
Hola @MINGOD24!

Tu duda está resuelta en la issue #293 :)

Saludos!
