### ISSUE TITLE
Usuarios no únicos

### ISSUE THREAD

**Issue by cjones27** [IIC2233/syllabus#475]
Hola, tengo una duda con respecto al punto 4.2.2 (rol del servidor, tercer punto) y 5.2 sobre el registro de los usuarios.
Según el 4.2.2 al crearse un usuario, se deben guardar sus datos para poder usarlos posteriormente. Sin embargo, en el 5.2 dice que se puede crear un usuario que ya exista en el caso de que no este conectado.
Dado esto debo no guardar la información de usuario en este caso? Se considera como si iniciara sesión? 

Gracias de antemano

**Comment by DCCollao** [comment]
Hola!
Al ingresar el nombre de un usuario ya registrado y que no esté conectado en ese momento, no se debe crear una nueva instancia de este en tu base de datos. Lo que corresponde es que se inicie sesión normalmente.
