### ISSUE TITLE
duda resultado esperado test pizza_del_mes

### ISSUE THREAD

**Issue by SebaAgusto** [IIC2233/Syllabus#475]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

wenas, mi duda es la siguiente. En esta funcion realice lo mismo que hice en la funcion `pizza_mas_vendida_del_dia` pero hay un test (especificamente el 1ro) que no me da el resultado esperado. Estaba revisando y al momento de sumar las pizzas mas vendidas del mes me sale que la que tiene mayor ventas es "Vegetariana" pero el test dice que la respuesta es "Pepperoni Clasica". Entonces no me queda claro si es error mio o no. Ademas todos los otros testcases me resultan, incluso los de correctitud. Les adjunto una imagen de lo que me resulta..
![image](https://github.com/user-attachments/assets/5e2d13ed-5a5b-4303-a3ea-8ab5cbe781f7)
Espero su respuesta, gracias de antemano :kissing_heart:

**Comment by kbetelgeuse** [comment]
Buenas @SebaAgusto.

Estuve revisando el código que tienes subido en tu repositorio. Más que un error, debido a la forma en la que estás procesando los datos para completar la consulta se está asumiendo algo que no ha sido explicitado en comentarios dentro del código (es como un supuesto que está implícito por cómo estás manejando los datos). Es posible que dentro de un mismo pedido se pida más de una vez un mismo tipo de pizza (mismo nombre y mismo tamaño). Por ejemplo, que en un pedido se pidan 7 pizzas `Vegetariana_M`, y que después en el mismo pedido se pidan otras 3 pizzas `Vegetariana_M`.

Tal como lo has hecho durante el desarrollo de la consulta (una forma bastante útil de hacer _debug_), te recomiendo seguir utilizando la función `print` para que puedas identificar qué es lo que está ocurriendo y puedas comprobar si los resultados que obtienes con lo que estás implementando coinciden con lo que aparece en la base de datos. Como pista, revisa la definición que tienes de la función `diccionario_id_pizzas` que creaste 😉.

**Comment by SebaAgusto** [comment]
Graciassss, ya me di cuenta del error, lo voy a corregir altiro :relieved:
