### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by monicabelen** [IIC2233/Syllabus#475]
Usando threads puedo simular el tiempo continuo solamente, o también puedo simular los eventos, haciendo correr el thread a medida que ocurren los eventos?

**Comment by sebacruzd** [comment]
Hola,

La materia de threads se evaluará en la siguiente tarea, para esta no está pensado usar threads.

Saludos!

**Comment by iqacevedo** [comment]
Hola,

A modo de complemento considera que en una simulación DES, tienes que ir avanzando toda la simulación hasta el tiempo de ocurrencia del siguiente evento, por tanto no requieres tener múltiples threads que trabajen en paralelo revisando que ocurre para poder ejecutar la simulación, ya que el comportamiento de la simulación solo está determinado por el siguiente evento que ocurra.

Saludos !
