### ISSUE TITLE
Retorno de consultas que no retornan otra base de datos

### ISSUE THREAD

**Issue by antoniacobo** [IIC2233/Syllabus#475]
Hola! En la sección 2.3.3. se pide que en las consultas se retornen 4 mejores, k más repetidos y así. Hay alguna manera en específico en que se tenga que retornar la información o queda a nuestro criterio?

**Comment by Hernan4444** [comment]
@antoniacobo no hay manera en específico, mientras cumpla con lo solicitado en el enunciado, el formato lo pueden dejar a su criterio, pero que sea entendible. Poner las respuestas en arabe por ejemplo cumple el formato, pero no es entendible 😅 

Saludos ✌️
