### ISSUE TITLE
Duda sobre el uso de 2 decoradores en una funcion

### ISSUE THREAD

**Issue by jniemann1** [IIC2233/syllabus#475]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Mi duda es respecto al **primer ejemplo** de la tercera parte de los contenidos de decoradores. 
En este problema se usan **dos decoradores** (@logger y @timer() ) para la función sleepysum(). ¿Porque en los wrapper de ambos decoradores se **repite** el codigo que toma el tiempo?
```python
start = time.time()
result = func(*args, **kwargs)
end = time.time()
```

**Comment by aaossa** [comment]
Hola @jniemann1 , es una buena pregunta pero no estoy seguro a si tu pregunta es (1) por qué es necesario repetir ese código (*spoiler*: no es necesario) o (2) por qué decidimos repetir ese código (*spoiler*: solo para mostrar que son independientes). Intentaré responder de tal manera que pueda responder ambas preguntas.

De partida, considera que el código que citaste es muy estándar para medir cuánto tiempo toma la ejecución de la llamada a una función (o de cualquier código que esté entre `start` y `end`). Ahora, decorador solo sabe que recibe una función, no sabe cuántos decoradores tiene o si quiera si está decorada. Esto hace sentido porque un decorador es una función que retorna otra función. El decorador `logger` ejecuta una función y te dice cuánto tiempo se ejecutó:

```python
import time

def logger(function):
    def wrapper(*args, **kwargs):
        start = time.time()
        print("Ejecutando la función...")
        result = function(*args, **kwargs)
        end = time.time()
        print(f"Finalizando la función. Demoró {end-start:.4f} segundos.")
        
        return result
    return wrapper
```

Por otra parte, el decorador `timer` te dice si es que la función decorada tardó más que `threshold` segundos en ejecutarse:

```python
import time 

def timer(threshold=2): # Podemos, incluso, entregarle un parámetro opcional.
    def check_time(func):
        def wrapper(*args, **kwargs):
            start = time.time()
            result = func(*args, **kwargs)
            end = time.time()
            
            if end - start > threshold:
                print("[Warning] La ejecución ha tomado mucho tiempo")
            
            return result
        return wrapper
    return check_time
```

Como dije al principio, ambas funciones son independientes, lo que se hace visible en el *output* de este ejemplo modificado que hice. En este ejemplo se hace visible que las duraciones reportadas por ambos decoradores pueden ser distintas, lo que es esperable ya que no están conectadas de ninguna forma, solo saben cuánto se demora la función que están "mirando" (decorando).

```python
import time

def logger(function):
    def wrapper(*args, **kwargs):
        start = time.time()
        print("(logger) Ejecutando la función...")
        result = function(*args, **kwargs)
        end = time.time()
        print(f"(logger) Finalizando la función. Demoró {end-start:.4f} segundos.")
        
        return result
    return wrapper

def timer(threshold=2): # Podemos, incluso, entregarle un parámetro opcional.
    def check_time(func):
        def wrapper(*args, **kwargs):
            start = time.time()
            print("(timer) Ejecutando la función...")
            result = func(*args, **kwargs)
            end = time.time()
            print(f"(timer) Finalizando la función. Demoró {end-start:.4f} segundos.")
            time.sleep(2)  # Dormimos 2 segundos más en timer
            
            if end - start > threshold:
                print("[Warning] La ejecución ha tomado mucho tiempo")
            
            return result
        return wrapper
    return check_time

@logger
@timer(0)  # 0 segundos de threshold
def sleepy_sum(a, b, c):
    time.sleep(3)
    return a + b + c

if __name__ == '__main__':
	sleepy_sum(1, 2, 3)
```

Este es el *output*:

```
(logger) Ejecutando la función...
(timer) Ejecutando la función...
(timer) Finalizando la función. Demoró 3.0036 segundos.
[Warning] La ejecución ha tomado mucho tiempo
(logger) Finalizando la función. Demoró 5.0054 segundos.
```

Como se puede ver, primero se empieza a ejecutar logger y luego timer, lo que coincide con el orden de la decoración, que es equivalente a `sleepy_sum = logger(timer(0)(sleepy_sum))`. Sé que esto puede ser confuso, pero te invito a jugar agregando los `print` que consideres necesarios para explorar el funcionamiento de los decoradores. Si tienes cualquier duda sobre este ejemplo en particular o cualquier otra cosa, pregunta por acá mismo y yo feliz respondo 👌

**Comment by jniemann1** [comment]
Hola, ¿entonces esto quiere decir que se ejecutan 2 threads, uno por cada decorador?

**Comment by aaossa** [comment]
En este contexto los *threads* no tienen relación, sino que todo ocurre en el *thread* principal, lo que significa que todo ocurre de manera secuencial (línea por línea). Lo que estamos haciendo es redefinir la función `sleepy_sum` y esta se llamará normalmente, sin diferencia para el resto del programa 🤓

**Comment by jniemann1** [comment]
Ya entendí, gracias!
