### ISSUE TITLE
calculo de mesada del mes de alumnos

### ISSUE THREAD

**Issue by NotSimple** [IIC2233/Syllabus#475]
En 6. Eventos Programados sale:
>  Mesada: Ya que casi ningun alumno trabaja, la fuente de ingresos se reduce a una mesada mensual variable. En otras palabras, cada 30 dias se recalcula la mesada utilizando la siguiente formula: 
mesada = base mesada∗(1 + random()random())∗20

Esta mesada se calcula para cada alumno individualmente o es la misma para todos?

**Comment by cilopez** [comment]
Se calcula para cada alumno individualmente, saludos!

**Comment by JuanGalilea** [comment]
aprovechando el issue, se calculan el primer mes o ese mes es la mesada base?

**Comment by cilopez** [comment]
No se si entendí muy bien tu pregunta, pero si te refieres a que inicialmente cuentan con una mesada, si cuentan con ella el día 0(se las entregas aquel día).
