### ISSUE TITLE
.gitignore Tarea 2

### ISSUE THREAD

**Issue by jvlara** [IIC2233/Syllabus#476]
Resulta que para esta tarea cree el .gitignore y efectivamente no subí los archivos de la gui pero ocupando el comando git add * no se subió el .gitignore y me descontaron 0.5. ¿Era estrictamente necesario subir el .gitignore? Según lo que entendí del enunciado el único fin de este era que no subiéramos los archivos del gui, por lo que me parece exagerado medio punto de descuento siendo que no subí archivos del gui.

**Comment by FernandoPieressa** [comment]
Las issues no son el medio para casos personales, para eso esta el mail de contacto (ayudantesiic2233@gmail.com) o el formulario de recorrección.

Saludos!
