### ISSUE TITLE
Herencia

### ISSUE THREAD

**Issue by RMMURUA** [IIC2233/syllabus#476]
Hola! Una consulta, ¿es necesario que en la tarea use herencia normal y clases abstractas? ¿O si uso solo clases abstractas ya estaria incluyendo herencia al aplicarla justamente en las clases hijas de las abstractas que cree? mil gracias de antemano

**Comment by baosse** [comment]
Holaa @RMMURUA !
Exacto, al usar clases abstractas estas ocupando herencia al usarlas en las clases hijas.
Espero te sirva! Mucho éxito✨
