### ISSUE TITLE
Ejecutar más de un cliente

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#476]
Hola, existe una forma rápida para ejecutar más de un cliente por ejemplo desde pycharm. Actualmente lo hago desde el cmd, abriendo varias ventanas, pero al tratar de parar el programa es muy tedioso, ya que implica cerrar las ventanas (puesto que se queda pegado en el while) y abrirlas de nuevo, cambiar el directorio y finalmente ejecutar el cliente (Esto 4 veces ya que estoy trabajando con 3 clientes y 1 server)

**Comment by bimartinez** [comment]
Hola @VicenteMerino 

En PyCharm no se como hacerlo, lo sé, pésimo servicio (⭐️➖➖➖➖) . Pero desde la `cmd` no es necesario cerrarlas para matar ☠️ un proceso. Solo debes presionar la combinación de teclas `CTRL + C` y el programa que actualmente esté ejecutandose terminará (con lo cual no tendras que volver a abrir una `cmd` y cambiarte al directorio en el que estás trabajando).

Saludos!

**Comment by VicenteMerino** [comment]
He tratado eso, pero o me funciona :( Pienso que es porque se queda pegado en el while del server/cliente.

**Comment by bimartinez** [comment]
Intenta con la combinación `CTRL+SHIFT+C`, eso debería funcionar! Avísame como te va 😄
