### ISSUE TITLE
README tarea 3

### ISSUE THREAD

**Issue by meretamal** [IIC2233/Syllabus#476]
Hola, si entrego la tarea 3 el miércoles 9, tengo plazo para entregar el readme hasta el 10?
Gracias de antemano

**Comment by rihanuch** [comment]
¡Hola @meretamal !

Sí, tienes plazo hasta el 10 para entregar el ```README.MD```

¡Saludos!🍀

**Comment by jfbahamondes** [comment]
Sin embargo, el readme siempre se puede modificar y completar. El readme no se recoge, sino que se corrige el que se encuentra en el repositorio el día de la corrección.
