### ISSUE TITLE
Duda tests test_24_votantes_validos_por_distrito.py

### ISSUE THREAD

**Issue by luisaparedesb** [IIC2233/Syllabus#476]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Tengo una duda respecto a qué evalúan los tests 6, 7 y 8 para esta función, ya que estos me dicen ok, pero los otros me dicen fail, y no logro descubrir dónde está mi error en el código. Hay un diccionario que definí, que al acceder al valor para ciertas llaves me retorna None para los primeros tests, pero no para los últimos.  Hice push de mi tarea por si es necesario.

**Comment by SSParzival** [comment]
Hola buenas, lo que describes parece semejante a lo que se explicó en la siguiente [_issue_](https://github.com/IIC2233/Syllabus/issues/413).

Quedo atento por si sigues teniendo dudas respecto al funcionamiento de la función.
