### ISSUE TITLE
Duda sobre promedio_ventas_con_descuento_de_un_pais

### ISSUE THREAD

**Issue by sunrayito** [IIC2233/Syllabus#476]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Con descuento se refiere al contenidopedido.descuento? o a la cantidad de dinero que se estaría ahorrando? En qué orden debería aplicarse round para que sea coherente con los test cases? Por cada pedido el descuento siempre es el mismo o hay que sacar el promedio de los descuentos por cada pedido? No me quedó muy clara la instrucción.

**Comment by mane6867** [comment]
Hola! esto se habla en la issue #446 si tienes otra duda o no te queda claro con la explicación no dudes en consultar una vez más!

**Comment by sunrayito** [comment]
hola, ya la había leído pero esta es una función diferente y no entiendo bien lo del descuento y cuándo debo aplicarle el round para este caso, le función anterior si me dio , pero esta no me da coherente con los test cases aún :( y también si el promedio es el mismo para cada pedido o si este varía

**Comment by sunrayito** [comment]
Update: no sé qué hice pero ahora si me dio coherente con los test cases, si alguien lee esto solo es necesario agregar el round al final cuando uno saca el promedio, y en respuesta a lo del descuento al menos para los test cases es el mismo para cada producto en el mismo pedido.

Aún me quedó la duda de si en los test cases con los que evaluarán la tarea el descuento por pedido será el mismo por todos los items dentro del pedido. Esto lo pregunto considerando en la vida real a veces hacen descuento por solo un producto y no siempre un descuento general por la compra, para saber si debo calcular el promedio entre todos los descuentos dentro del mismo pedido o solo considerarlo una vez está bien.

**Comment by mane6867** [comment]
El enunciado de la tarea menciona que la función promedio_valores_con_descuento_de_un_pais, corresponde al "promedio de los descuentos de todos los pedidos del país especificado", para esto tendrás que sumar todos los descuentos que se han aplicado en pedidos realizados en el país al que se hace referencia (se hace uso del atributo descuento de contenidopedidos) y a la vez calcular cuál es la cantidad total de pedidos que se han realizado en dicho país, finalmente deberás aplicar round en cuanto a la división de estos valores, es decir el promedio.

**Comment by sunrayito** [comment]
Me quedó la duda de si el descuento de contenido pedidos va a ser el mismo si es el mismo pedido (por ejemplo que el descuento de pedidos con id_pedido = 3 siempre será el mismo, o sea que si hay 3 contenidos dentro del mismo pedido, el descuento sea para todos 0.3 por ej y no sea 0.4, 0.3, 0.5) Entonces se puede afirmar que el descuento para contenidopedidos con el mismo id_pedido será siempre el mismo?

(Muchas gracias por la paciencia)

**Comment by mane6867** [comment]
Si, se puede afirmar que el descuento para contenidopedidos con el mismo id_pedido será siempre el mismo!

**Comment by JacintaOrtiz** [comment]
Hola respecto a esta misma función me queda la duda si cuando decimos el promedio de descuento de los **pedidos**,  a estos pedidos se refiere a cada instancia de Pedido o cada una de ContenidoPedidos??
