### ISSUE TITLE
Duda actividad y estudio

### ISSUE THREAD

**Issue by josemlira** [IIC2233/Syllabus#476]
El alumno, después de haber realizado la actividad del día Jueves, seguirá estudiando la materia de la semana (días Viernes, Sabado y Domingo) a modo de refuerzo y comenzará con la nueva materia el día Lunes? Y si no fuese necesariamente así, se puede suponer?

**Comment by iqacevedo** [comment]
Hola, 
Según el enunciado se considera que sigue estudiando esos días. En el ejemplo al final del punto 4.1.1 se indica que el alumno le dedicara 3 horas a estudiar materia, pero el día jueves solo lleva 1 hora y 40 minutos, por lo que la hora y veinte minutos que le faltan debería estudiarlos en los días viernes, sábado y domingo.
De todas maneras si consideras que es más lógico otro camino, como que estudie la materia nueva desde el jueves después de la AC hasta el siguiente jueves, puedes hacerlo siempre que lo especifiques en el README.

Saludos !

**Comment by josemlira** [comment]
Gracias !!!
