### ISSUE TITLE
Headers en archivos .csv

### ISSUE THREAD

**Issue by pedrobeckerj** [IIC2233/syllabus#477]
Hola! Entiendo que las columnas de los csv pueden cambiar el orden pero, los headers siempre serán los mismos?
Por ejemplo, para el archivo deportistas.csv, los headers siempre serán ['nombre                      ', 'flexibilidad ', 'moral ', 'precio ', 'velocidad ', 'lesionado ', 'resistencia']?

**Comment by baosse** [comment]
Holaa Pedro!
Los headers siempre serán los mismos pero se pueden encontrar en distinto orden.
Espero que te haya servido! Mucho éxito con tu tarea✨
