### ISSUE TITLE
Análogo de pyqtSignal

### ISSUE THREAD

**Issue by kylevon** [IIC2233/syllabus#477]
Hola,
Quiero usar algo similar a pyqtSignal para hacer un símil de 
```self.signal_name.emit(data)```
donde esa señal es conectada con una función de una clase instanciada:
```self.Boo.signal_name.connect(self.function_name)```
para objetos que **no** son QObjects.
No quiero usar events porque sería terrible tener millones de waits.
¿Cuál sería ese análogo?

**Comment by marioreinike** [comment]
Hola @kylevon!
según lo que entendí, ¿quieres emitir una señal desde un objeto que no es QObject, conectada a un método de una instancia de QWidget? en ese caso, deberías crear la señal en la ventana, conectarla en su `init_GUI` (o bien en su `__init__`) y pasársela al objeto como parámetro cuando lo instancies. En los contenidos del curso, en la [semana 09/2-eventos-y-señales](https://github.com/IIC2233/contenidos/blob/master/semana-09/2-eventos-y-se%C3%B1ales.ipynb), en la parte que se usan threads para actualizar un QLabel, se emiten señales pyqtSignal desde objetos que no son QObjects. Tal vez eso te pueda ayudar.
Respecto a no usar events, no entiendo por qué los usarías en vez de señales, pero espero que haya quedado claro con lo anterior. Cualquier duda avísame.
Saludos!
