### ISSUE TITLE
Discrepancia horas almuerzo

### ISSUE THREAD

**Issue by IchottMano** [IIC2233/Syllabus#477]
En el enunciado, dentro del ítem de Eventos Programados, dice que 
X% Almuerza entre 13:00 y 13:59, Y% Almuerza entre 14:00 y 15:00 y (100 - X - Y)% Entre 12:00 y 12:59
Sin embargo, mas adelante en la parte "Decidir ir a comer" dice que la distribución del horario para comer es normal con parámetro u = X:10, donde X puede ser 13, 14 o 15 que depende de si la persona almuerza de 13 a 14, 14 a 15 o 15 a 16.
Mi duda es, ¿que tiempo usamos?
Muchas gracias

**Comment by cilopez** [comment]
Utiliza 12:00-12:59 13:00-13:59 14:00-15:00 (_is this a Jojo reference?_)

**Comment by IchottMano** [comment]
En ese caso, el parámetro X debería tomar los valores 12, 13 o 14, o no? (*Everything is a Jojo reference*)

**Comment by iqacevedo** [comment]
Hola,
 
Si te refieres al parámetro X de "Decidir ir a comer" efectivamente puede ser 12, 13 ó 14.

Saludos !

**Comment by mjgutierrez1** [comment]
Además de basarse en las distribuciones para definir los distintos tiempos, ¿no se deberían agregar otras restricciones?

Por ejemplo, el tiempo de ir a comprar comida distribuye exponencial, pero en teoría ese tiempo me podría dar enorme lo cual podría ser equivalente a ir a comprar al día siguiente, siendo que el tiempo que estábamos calculando es el tiempo de ir a comprar comida en el día actual. Otro ejemplo podría ser con la distribución normal de la hora a la que se decide ir a comer: la distribución normal va de -infinito a +infinito, por lo que cómo interpretaría si me diera un valor positivo muy chico o negativo, ¿que decidió ir a comer antes de llegar a San Joaquín o el día anterior? Esos ejemplos no tendrían sentido en lo que queremos modelar.

En el caso de que efectivamente hubiera que poner restricciones a esos tiempos (es decir, que por ejemplo si me da que el tiempo en que quiere ir a comer es muy tarde, entonces defino el tiempo en que quiere ir a comer como un tiempo máximo conocido), ¿cuáles serían esas restricciones?

**Comment by cilopez** [comment]
@mjgutierrez1 complementaremos aquellas acotaciones cuando actualizemos el enunciado, gracias por señalarlo
