### ISSUE TITLE
Funcional al procesar query en libreria

### ISSUE THREAD

**Issue by dedarritchon** [IIC2233/Syllabus#477]
La funcion que recibe la query en la libreria tambien debe ser funcional?

**Comment by rihanuch** [comment]
¡Hola @dedarritchon !

Esta permitido usar ```for``` en la parte de las consultas, eso si lo ideal es todo lo que esté dentro sea de manera funcional (en lo posible)(tampoco abuses de esta condición 👀)

¡Saludos! 🍀
