### ISSUE TITLE
Azada

### ISSUE THREAD

**Issue by anvaldes** [IIC2233/syllabus#477]
¿Cual es la imagen asociada a una azada? Yo puse la que aparecia en el enunciado. Pero revisando la carpeta scritpts me aparece que su nombre el hoe, entonces me causo duda.

**Comment by ariela1** [comment]
Hola! Ese es la imagen designada para la azada, de hecho la palabra azada en inglés es hoe. Aun así, queda a tu criterio el diseño de los sprites, siempre teniendo en cuenta que se distinga cada elemento. Suerte con tu tarea!!
