### ISSUE TITLE
Formato datos

### ISSUE THREAD

**Issue by sunrayito** [IIC2233/Syllabus#477]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Se puede asumir que los datos que son entregados a la función siempre serán correctos? Por ejemplo si se espera un int que se asegure que se entregue un int, o se espera que sea a prueba de cualquier tipo de input? Lo mismo aplica para la carga de datos, los datos siempre estarán en el formato esperado?

**Comment by Gcamposbriceno** [comment]
Hola! Los datos cargados siempre estarán en un formato consistente con el enunciado. Esto no quita que, al venir en un archivo .csv, python va a leer todo como string inicialmente, por lo que si un campo es un int, debes transformarlo a int antes de guardarlo.
En esta tarea no se pide que las funciones sean a prueba de cualquier input, por lo que puedes asumir que siempre que se llame una función se le entregarán valores apropiados (asumiendo que implementaste las funciones de carga de datos correctamente).

**Comment by Mgseverin** [comment]
Hola! En este sentido, podemos asumir que los valores entregados en las funciones no serán vacíos? Por ejemplo, en `consulta_anidada(instrucciones: dict)` podemos asumir que no se entregará un diccionario vacío?

**Comment by kbetelgeuse** [comment]
Hola @Mgseverin!

1:
Si te refieres a que si en una consulta se van a entregar todos los parámetros necesarios: sí, todos los parámetros se entregarán; no habrá argumentos sin asignar al momento de llamar a las consultas dentro de los tests.

2:
Ahora, si en realidad tu duda era acerca de si siempre contendrán elementos los argumentos iterables que recibirán tus consultas:  los únicos objetos iterables que eventualmente podrían estar vacíos (sin elementos) serían algunos generadores. Lo anterior podría ocurrir, por ejemplo, en el caso de que llames a una consulta con un generador vacío dentro de otra consulta, ya sea porque realizaste un `filter` que entregó un generador sin elementos o porque quisiste entregarle intencionalmente un generador vacío. De todas maneras, en caso de que llegase, por algún motivo, a ocurrir lo anterior, tu programa debiese ser capaz de no fallar ante esta situación.

Dado lo anterior, el diccionario de instrucciones de la `consulta_anidada` en ningún caso debiera entregarse como un diccionario vacío (`{}`). En otras palabras, siempre este diccionario contendrá: una función correspondiente a las mencionadas en el enunciado; y los parámetros correspondientes necesarios para esa función, los cuales podrían ser eventualmente otro diccionario (el que, a su vez, tampoco estaría vacío).

**Comment by Fer5842** [comment]
Hola! Vi que en el test  4 de consulta anidada los argumentos no estaban en el mismo orden que como estaban definidos en la función. Podemos asumir entonces que las llaves del diccionario siempre tendrán el mismo nombre que como estan definidos los parametros de la funcion?

**Comment by kbetelgeuse** [comment]
Hola @Fer5842 !

Así es, pueden asumir que los nombres de las llaves en los diccionarios dentro de la consulta anidada tendrán el mismo nombre que los parámetros de las consultas que se están trabajando.

Por otra parte, puede ocurrir que en un diccionario el orden de los ítems no sea el mismo. Esto, dado que el diccionario es una estructura de datos no secuencial, lo que quiere decir que no posee relaciones de orden para los elementos que contiene. Por lo anterior es imposible hacer una indexación con diccionarios para acceder a elementos, no como ocurre en las listas en donde se pueden utilizar los índices de los elementos (los que están dados por su orden dentro  de la lista). Al igual que los sets, los diccionarios pueden almacenar la misma información independiente del orden de sus elementos. Por ejemplo, el diccionario

`{'nombre': 'nombre de ejemplo', 'correo secundario': 'ejemplo@ejemplo.com', 'correo': 'pepa@iic2233.aan'}`

puede "representar" la misma información que 

`{ 'correo': 'pepa@iic2233.aan', 'correo secundario': 'ejemplo@ejemplo.com', 'nombre': 'nombre de ejemplo'}`
