### ISSUE TITLE
Restricción alfanumerica para el nombre de jugador

### ISSUE THREAD

**Issue by lfb1206** [IIC2233/syllabus#477]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En la description de la ventana de inicio se menciona que hay que verificar la restricción alfanumérica del nombre del jugador. 
*¿Cuales son estas restricciones o dónde las puedo encontrar?*

**Comment by tomasrosenberg** [comment]
Hola @lfb1206!
La restricción alfanumérica se refiere a que el nombre del jugador debe contener sólo caracteres de ese estilo. Por definición, uno alfanumérico es aquel que está formado sólo por números y/o letras. Te recomiendo revisar la documentación de _python_ y buscar sobre esto ya que puede ser de gran utilidad.

Quedo atento cualquier otra duda :D
