### ISSUE TITLE
Horas de estudio 

### ISSUE THREAD

**Issue by TomasSalvadores** [IIC2233/Syllabus#477]
Hola!
Tengo una duda con el ejemplo de la siguiente imagen:

![captura de pantalla 2017-05-12 a la s 19 14 52](https://cloud.githubusercontent.com/assets/24449539/26018838/96d10bb6-3747-11e7-9927-8986cacec90a.png)

En el ejemplo creo que se asume que uno parte a estudiar para la actividad el lunes, pero como todos los días jueves hay actividad, y estudiamos todos los días, uno no comenzaría a estudiar para la siguiente a partir de el viernes?
Entonces al tiempo que ponen en el ejemplo no habría que sumarle los tiempos de estudio de  la semana pasada a partir del viernes?

**Comment by iqacevedo** [comment]
Hola !

Acabo de responder esto mismo en #476 (la cierro por lo mismo).

Saludos !
