### ISSUE TITLE
Uso de diccionario en parametros.py

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2233/syllabus#477]
Hola, puedo dejar un diccionario en las properties? (T 01)

**Comment by Dnpoblete** [comment]
Hola @Aloncarrasco, cual sería la razón por la que querías hacer eso? Te refieres a las properties o en el archivo parametros.py?

Quedo atenta a tu respuesta 😄

**Comment by Aloncarrasco** [comment]
ay si parametros

**Comment by Dnpoblete** [comment]
Esta duda ya fue respondida en la issue #422, para que la revises, voy a cerrar esta para que no este duplicada y en caso de dudas sobre el tema puedes pregunta en esa issue.

Éxito con la tarea! 😄
