### ISSUE TITLE
T3 Problemas con la ñ.

### ISSUE THREAD

**Issue by nicolasoyarcegUC** [IIC2233/Syllabus#478]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola, en los tests 21 y 22 donde hay que retornar strings, tengo que el problema que el string que retorno no reconoce ni a la ñ en "año" ni al tilde en "más" y por lo tanto cuando corro esos tests, me fallan pese a que mi resultado numerico es correcto   Como puedo hacer para retornar bien la ñ y los tildes?

**Comment by diegobas10** [comment]
Hola buenas @nicolasoyarcegUC,
Me podrías especificar a que te refieres con que el retorno no reconoce a estas strings para poder ayudarte.

**Comment by nicolasoyarcegUC** [comment]
@diegobas10  Hola, dejo una imagen. 

![errorenye](https://github.com/IIC2233/Syllabus/assets/86936213/295efcaf-7fe9-4a43-8dbc-2c35cb12ff14)

**Comment by nicolasoyarcegUC** [comment]
por otro lado, en visual studio, cuando escribo la ñ o tildes me los imprime sin problemas osea si escribo "ñau" imprime eso pero cuando ejecuto de cmd imprime "?au" no se como arreglar eso, no sé si será porque mi computador lo tengo en inglés o algo así.

**Comment by diegobas10** [comment]
@nicolasoyarcegUC es muy probable que esta sea la razón, ya que supongo que seguiste las instrucciones del encoding latin-1 o si no hubieras tenido problemas para cargar los datos, prueba cambiando el idioma de tu computador, si sigue sin funcionar sube tu commit a repositorio para ver cual podría ser el errores que ocurre.

**Comment by nicolasoyarcegUC** [comment]
@diegobas10 si segui las instruccioens de latin-1 y no tuve problema con eso. Ya cambie el idioma a español pero sigue igual, además me di cuenta de que cuando escribo en visual studio la ñ o á en un string y luego cierro el codigo y lo vuelvo abrir, estos se reemplazan a ?. Ya subí  mi commit al repositorio.

**Comment by JJJGGGG** [comment]
Como consejo, intenta usar powershell en vez de cmd, porque es un poco más poderosa.

**Comment by diegobas10** [comment]
@nicolasoyarcegUC probé tu código cambiando los caracteres trata de subirlos cambiando los valores con tildes de alguna manera tal vez no por visual y si lo haces por visual hazlo cambiando la versión de encoding abajo a la derecha. Lo siento por responder de esta manera con pocos detalles, tuve un corte de luz en la casa, apenas pueda responderte de mejor manera lo hago.

**Comment by enzoacvi** [comment]
Hola! Estoy con el mismo problema. He cambiado el encoding del archivo abajo a la derecha pero aún sucede esto. Qué se puede hacer para que no pase??

**Comment by nicolasoyarcegUC** [comment]
@diegobas10 hola, modifique el texto con el editor txt y me lo guardo bien y ahora si pasa el test gracias!

**Comment by nicolasoyarcegUC** [comment]
@enzoacvi  Hola, yo lo acabo de resolver. Lo que hice fue abrir el codigo usando editor txt y luego escribe la tilde y la ñ donde corresponda. Despues ve a guardar como y a la izquierda de "guardar" o "save"(si lo tienes en ingles) asegurate que el encoding sea UTF-8

**Comment by enzoacvi** [comment]
@nicolasoyarcegUC yaaa, muchas gracias

**Comment by diegobas10** [comment]
@nicolasoyarcegUC @enzoacvi Igualmente por si les llega a afectar el error de alguna manera, aunque lo hayan solucionado, no se preocupen, ya que este tal vez sea considerado en los tests privados si es que se llegan a cambiar y si no, igualmente en la recorreción podrán apelar, ya que una tilde no debería considerarse parte de la dificultad de la tarea y se le considerará correcto.
Saludos, quedo atento a cualquier duda.
