### ISSUE TITLE
Ubicación objetos en el inventario

### ISSUE THREAD

**Issue by maormeno** [IIC2233/syllabus#478]
Hola! La separación del mapa en tiles de n*n también debe aplicarse para el inventario?? Lo pregunto porque yo lo tengo puesto como que siempre se encuentre en la misma ubicación y sea del mismo tamaño, por lo que al ubicar los sprites de los objetos que se compran en la tienda, lo hice simplemente escribiendo las coordenadas de la ventana donde yo quiero que se ubique el primer objeto comprado, y luego sumarle "x" cantidad de pixeles cada vez que quiero agregar otro (para el lado y para abajo), eso esta bien? O debo cambiarlo y hacer todo en función del parámetro "n" también?

**Comment by aljara97** [comment]
Hola, si entiendo bien tu duda estás usando una misma ventana para el inventario y el mapa, pero asumes una ubicación fija para el inventario y que esta no depende del parámetro N? En ese caso no está bien la forma en que estás trabajando, ya que los elementos de tu ventana deben desplazarse en función de este parámetro (el cual podemos cambiar a propósito 👀 ) y así evitar la superposición entre los elementos de la ventana, ítem a evaluar en esta tarea. No es necesario que los elementos del inventario cambien su tamaño de acuerdo a este parámetro, sin embargo, es aconsejable para hacer más amigable la interfaz.

Espero haber aclarado tu duda, de no ser así coméntame 🌱 🌽

**Comment by maormeno** [comment]
Si era exactamente eso, muchas gracias
