### ISSUE TITLE
Mensajes en Chat

### ISSUE THREAD

**Issue by FaZorrilla** [IIC2233/syllabus#478]
Hola,
En el enunciado no menciona que se tiene que hacer un QAreaScroll para los mensajes. Tampoco se menciona que se deben poder ver todos los mensajes mandados previamente para todos los jugadores. Se puede hacer un supuesto, tal que solo se muestren los últimos 20-30 mensajes? En el caso del comando \chao, se puede guardar externamente en el servidor la cantidad de votos para la desición.

**Comment by jeschuwirth** [comment]
Saludos!

Tener un QAreaScroll no es obligatorio, pero si lo recomendamos para hacer más sencilla la lectura de mensajes. En el pie de página hay un link a un chat de una ayudantía pasada que puedes utilizar siempre y cuando cites para ahorrarte un poco de trabajo.

Para el caso del comando \chao, puedes guardar la cantidad de votos en cualquier parte, pero te recomiendo ir mostrando cuando votos lleva el usuario que se intenta echar y cuantos faltan, de modo de mostrar que cuentas correctamente el número de votos.

Suerte en la tarea !
