### ISSUE TITLE
Uso de emojis en código

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#478]
Hola, se pueden usar emojis en el código para que el output de la consola se vea mejor? (En los contenidos de la semana 4 usan)

![image](https://user-images.githubusercontent.com/62355739/92670623-ccc5b700-f2ea-11ea-9b45-f1c0dcf2a6c6.png)

**Comment by vsantelicest** [comment]
Hola **@Gustav2000**!
Mientras el uso de emojis no entorpezca la escritura de tu código o pueda ser causa de algún error, no habría problema en que los usaras. Se agradece este tipo de iniciativas para brindar mayor entretención a la escritura de código, sin caer eso si en usos excesivos! 
Éxito en la tarea! 🥇

**Comment by Gustav2000** [comment]
Buenísimo, muchas gracias!!!
