### ISSUE TITLE
Como importar archivos en ubicaciones paralelas

### ISSUE THREAD

**Issue by raibd** [IIC2233/syllabus#478]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Si tengo los siguientes archivos: 
_T2/parametros.py_
_T2/frontend/archivo.py_

Como puedo importar _parametros.py_ dentro de _archivo.py_?. En esta pregunta que encontré https://stackoverflow.com/questions/4383571/importing-files-from-different-folder dan una solución que es usar ```sys.path.append()```, pero no estoy seguro si esta permitido o si sería la mejor manera.

Gracias

**Comment by aaossa** [comment]
Hola @raibd , en general diría que no es bueno ni necesario utilizar `sys.path.append()`. Creo que la solución que está mejor modelada es aquella en la que se hacen llegar los parámetros a través de las instancias que utilices. Me refiero a que en `archivo.py` no importas los parámetros sino que, por ejemplo, si tienes una clase esta los reciba como atributos. De esta manera, solo es necesario importar los parametros en `main.py`. Te dejo un ejemplo:


```python
# parametros.py
VALOR = 1
```

```python
# main.py
from frontend.archivo import Ventana
from parametros import VALOR


if __name__ == "__main__":
    v = Ventana(VALOR)
```

```python
# frontend/archivo.py
class Ventana:

    def __init__(self, valor):
        self.valor = valor
```

Espero se entienda el ejemplo, pero si tienes alguna duda adicional, feliz de responder ✨ ¡Éxito con la tarea!

**Comment by raibd** [comment]
Ahora entiendo mejor, Gracias.

**Comment by imuoz** [comment]
Entiendo la respuesta que dieron, pero por ejemplo cuando usamos qt designer necesitamos heredar directamente a cada ventana (como en la AS2), entonces aquí si tenemos que importar parámetros. En la AS2 se importa de todas maneras y funciona pero no entiendo por qué

**Comment by imuoz** [comment]
Ya entendí, era que no lo estaba ejecutando desde el main jajaja

**Comment by raibd** [comment]
> Hola @raibd , en general diría que no es bueno ni necesario utilizar `sys.path.append()`. Creo que la solución que está mejor modelada es aquella en la que se hacen llegar los parámetros a través de las instancias que utilices. Me refiero a que en `archivo.py` no importas los parámetros sino que, por ejemplo, si tienes una clase esta los reciba como atributos. De esta manera, solo es necesario importar los parametros en `main.py`. Te dejo un ejemplo:
> 
> ```python
> # parametros.py
> VALOR = 1
> ```
> 
> ```python
> # main.py
> from frontend.archivo import Ventana
> from parametros import VALOR
> 
> 
> if __name__ == "__main__":
>     v = Ventana(VALOR)
> ```
> 
> ```python
> # frontend/archivo.py
> class Ventana:
> 
>     def __init__(self, valor):
>         self.valor = valor
> ```
> 
> Espero se entienda el ejemplo, pero si tienes alguna duda adicional, feliz de responder ✨ ¡Éxito con la tarea!

Hola, me surgió una duda con esto. Si en una clase debo importar varios (~20) parámetros, sería aceptable hacer algo del tipo:
```python
funcion(arg1,
             arg2,
             arg3,
             arg4,
             etc)
```
o algo como:

```python
funcion(arg1, arg2,
             arg3, arg4,
             etc)
```
en PEP8 sale algo parecido a lo segundo, pero encuentro que se hace dificil leer los nombres de las variables en especial cuando son muchas.
Gracias de antemano

**Comment by aaossa** [comment]
@raibd , claro, se puede. Aunque no sé si tu pregunta era sobre importar o sobre pasar argumentos en una función. Para ambas formas en las que se trabaja con varios valores, en lo personal yo prefiero usar esta forma:

```python
from parametros import (
    arg1, arg2, arg3,
    arg4, arg5, arg6,
)

funcion(
    arg1, arg2, arg3,
    arg4, arg5, arg6,
)
```

Personalmente, prefiero esta forma porque las líneas quedan iguales y no depende de la extensión de la primera línea. Ojo que igual puedes agregar saltos de línea adicionales para que los argumentos sean más fáciles de leer, nadie te pide que ocupes la línea entera antes de hacer un salto de línea, así que no te preocupes por eso. Lo importante es que ocupes la manera que te haga más sentido 👌
