### ISSUE TITLE
Ciclos for y while

### ISSUE THREAD

**Issue by benjadelgado** [IIC2233/Syllabus#478]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [x ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, escribo porque en el enunciado si bien se dice que se debe utilizar programación funcional, eso significa que no se pueden usar ciclos for y while? o una no excluye a la otra, es decir:
¿Se pueden usar for's y while's en la tarea?

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by DiegoGHR** [comment]
Hola Benja! El uso de ciclos for y while NO esta prohibido en esta tarea. Saludos
