### ISSUE TITLE
Distribución eventos no programados

### ISSUE THREAD

**Issue by vaguila95** [IIC2233/Syllabus#478]
El valor de la **expovariate** de los eventos no programados ¿nos retorna la cantidad de _horas_ desde el último evento? De ser así, eventos como el corte de agua (con el valor por defecto) sucederían demasiado seguido y por ende los profesores recibirían sólo 6 alumnos todas las semanas .

**Comment by iqacevedo** [comment]
Hola 

Corresponden a la cantidad de _días_ desde el último evento, si fueran  _horas_ ocurriría justamente lo que dices.

Saludos !
