### ISSUE TITLE
Posible error en columna box_office

### ISSUE THREAD

**Issue by Mariana-Ortega-del-Rio** [IIC2233/Syllabus#478]
Hola,
123, "A Wrecked Filmmaker", 5.6/10, 56%, 76/100, $0.918.700, 2007
Para esta movie me parece extraño que su box_office sea $0.918.700 debido a que en el resto si quieren poner que es menos de un millón entonces simplemente no colocan ese 0, por ejemplo,
149, "On the Road", 6.1/10, 44%, 56/100, $665.094, 2012
Esto me provoca errores en el codigo :'(
Para corregir la tarea arreglaran esta línea de movies.csv? 
Gracias de antemano!!

**Comment by rihanuch** [comment]
¡Hola @Mariana-Ortega-del-Rio !

Recuerda que tú también puedes verificar que no pase eso cambiando los 0's por 1's

¡Saludos! 🍀
