### ISSUE TITLE
Lineas de archivo personas.csv

### ISSUE THREAD

**Issue by nachocontreras** [IIC2233/Syllabus#478]
En el archivo personas.csv, hay lineas que contienen 2 o más individuos. Puede haber faltado un "\n" 🤔 ??

Ej:

```
Gabriel; Lyon; 40; - ; Vendedor; Snack ; - Isaac; Carrera; 30; - ; Vendedor; China ; - Leah; Blackwell; 24; - ; Carabinero; - ; Mr. Hyde 
```

**Comment by cilopez** [comment]
Efectivamente Rick, es un error del csv que arreglaremos dentro de poco, gracias por señalarlo!

**Comment by Hernan4444** [comment]
@nachocontreras se acaba de subir un *personas.csv* actualizado con el `\n` faltante.
Saludos ✌️

**Comment by nachocontreras** [comment]
Gracias!

**Comment by rakarachon** [comment]
Hola, creo que encontre otro error en personas.csv? las filas 238 y 109 se supone que son alumnos pero no tienen nombre ni apellido

**Comment by Hernan4444** [comment]
@rakarachon efectivamente era un error con personas que no tenían nombre, ya fueron eliminados.

Saludos ✌️

**Comment by SarahEverke** [comment]
Hola,
al leer el archivo, mi programa lee el nombre de Jesús como 

![captura de pantalla 2017-10-15 a la s 22 06 08](https://user-images.githubusercontent.com/30681133/31591184-4912ba56-b1f3-11e7-820e-9beafec7c489.png)

Para leer el archivo uso strip y split, ¿como puedo solucionar eso?

**Comment by SarahEverke** [comment]
Ya lo resolví, usé strip("\ufeff") !
