### ISSUE TITLE
Fotos de los usuarios

### ISSUE THREAD

**Issue by furzuadr** [IIC2233/syllabus#479]
Puedo asumir que las fotos de los usuarios serán cuadradas? (especificándolo en el readme). Si no lo hago, cada vez que hago un scaled me va a deformar la foto!
Gracias!

**Comment by jeschuwirth** [comment]
Saludos,
Da los mismo que las fotos se deformen, vamos a probar con fotos mas o menos cuadradas y mientras se note que es la misma no hay problema.

Suerte en la tarea !

**Comment by jeschuwirth** [comment]
Es importante agregar que el archivo .png que se envía al servidor no se puede modificar, sólo se puede alterar para facilitar como se muestra en la interfaz del programa.
