### ISSUE TITLE
Materia GUI

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#479]
Hola!

¿Al final se va a actualizar la materia de GUI a PyQt5?

Saludos!

**Comment by iqacevedo** [comment]
Hola,

Ya está actualizado intenta hacer `git pull` en contenidos para que puedas verlo.

Saludos !

**Comment by akaminetzkyp** [comment]
Toda la razón. Mil disculpas!

Saludos!
