### ISSUE TITLE
Uso de cupones para la tarea

### ISSUE THREAD

**Issue by MrFoxley** [IIC2233/Syllabus#479]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* X[ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
Buenas Tardes,

La tarea pasada subieron un anuncio a canvas donde había un formulario en el que se podía decir si que querían usar algunos de los cupones para las tareas. Me gustaría usar mis cupones para esta tarea ya que se me vino un poco muy encima. ¿Donde puedo aplicarlos para que no haya descuentos de atraso?

Muchas gracias de antemano
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by diegobas10** [comment]
Hola buenas @MrFoxley, 
Este formulario se abre después de las 20:00 de hoy, podría tardarse un poco, pero ahí recién lo vas poder rellenar, eso si ojo que tienes que llenarlo, cuando ya tengas el commit que quieres enviar, ya que hay que incluir este en el formulario.
Saludos, quedo atento a cualquier duda.

**Comment by BrucherBeta** [comment]
Hola! Con eso se refiere a que tenemos que adjuntar el link de la respuesta del formulario en el commit o como? Disculpe las molestias, primera vez que usare uno de los cupones

**Comment by diegobas10** [comment]
Hola @BrucherBeta,
No, a la hora de rellenar el formulario te va a pedir el último commit registrado, y el nuevo commit que quieres que se revise después de terminar la tarea. A la hora que se habilite el formulario las instrucciones estarán más claras.

**Comment by sulloam** [comment]
Hola tengo una duda sobre el uso de cupones, si es que uso mis dos cupones en esta tarea y entrego el jueves antes de las 20 horas tendre nota maxima 6 o no?

**Comment by diegobas10** [comment]
Hola buenas @sulloam
Disculpa la respuesta tan tardía. En las bases generales de las tareas se especifica que solo se puede entregar hasta 48 después de la fecha de entrega original, el uso del cupón solo elimina las penalizaciones que existirían por entregar más tarde la tarea.
Saludos
