### ISSUE TITLE
Duda resultado esperado test local_mas_pizzas_vendidas_por_tipo_de_pizza

### ISSUE THREAD

**Issue by dani-oviedo** [IIC2233/Syllabus#479]
* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

hola buenas tardes creo que en el test case las soluciones del número 16 esta erróneo el test 2 y 1, lo verifique a mano, ya que me corren todos los otros y además la correctitud igual excepto esos dos. según yo hay locales con mayor cantidad que los que aparecen ahí.

**Comment by kbetelgeuse** [comment]
Hola @dani-oviedo!
¿Podrías por favor subir a tu repositorio el desarrollo de tu tarea para que pueda analizar en detalle lo que me cuentas?
Saludos!

**Comment by dani-oviedo** [comment]
hola ahi subi mi tarea al repositorio, muchas gracias por revisar

**Comment by kbetelgeuse** [comment]
Revisé el código asociado a la consulta (y también en parte es de las otras jeje).

Debido a la forma en la que estás procesando los datos para completar la consulta se está asumiendo algo que no está explicito en comentarios dentro del código (usando `#`): es como un supuesto que está implícito por cómo estás manejando los datos. Algo que puede ocurrir dentro de un mismo pedido es que se pida de forma separada pizza del mismo nombre pero de distinto tamaño. Por ejemplo, que dentro de un pedido se pida 4 pizzas `Pepperoni Clásica_L` y posteriormente en otra parte del mismo pedido que se pida 6 pizzas `Pepperoni Clásica_S`. En caso de que se esté asumiendo esto se podría llegar eventualmente a diferencias entre lo que se obtiene luego de procesar los datos y lo que aparece en la base de datos. En específico, ¿qué sucedería dentro del desarrollo que implementaste para esta consulta si es que se tiene el caso del ejemplo que mencioné (me refiero al ejemplo de las pizzas de `Pepperoni Clásica`)? Como parte inicial de la respuesta a esta pregunta, habrá iterables que poseerán distinto largo, y en particular, los asociados a los generadores de pedidos y de contenido de pedidos. Te recomiendo cambiar algunas partes y considerar lo que estoy comentando, y también preguntarse qué implica que esos iterables posean distinto largo (es importante que te des cuenta de lo que eso implica, y si no lo consigues te puedo ayudar en el proceso 😉).

Ahora, quisiera hacer algunos comentarios adicionales de forma general de acuerdo con lo que has subido. Si es que no tienes contemplado cambiar algunas partes de lo que tienes para realizar la entrega final (porque claro, podrías preocuparte del formato al final), es importante que se respeten las reglas `PEP8`: en particular, hay varias partes en las que se posee más de 100 caracteres y en la que se carece de espacios después de las comas, lo que llevará a un descuento 🥺. A su vez, en reiteradas veces dentro del código se está utilizando lo que se denomina _bare except_: utilizar la sentencia `except` sin especificar el tipo de errores que quieres evitar. Esto es considerado una mala práctica y aparece mencionado en la issue #420 (Librerías permitidas y no permitidas), por lo que habrá descuento si es que lo utilizas para la entrega final 😢.

**Comment by dani-oviedo** [comment]
Hola muchas gracias voy a revisar lo que dices de la pregunta, y por otro lado como bien dices al final de implementar las cosas verifico el tema del PEP8 y lo de los except con más tranquilidad, ya que solo es mover cosas.
