### ISSUE TITLE
Pasar por la tienda

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#479]
Al pasar sobre la tienda y abrir otra ventana no puedo mover el personaje a menos que haga click en la ventana del juego. Está bien si dejo esto así o deberia abrirse sin interrumpir el movimiento del personaje? Saludos

**Comment by gatochico** [comment]
Hola! A que te refieres con 'hacer click en la ventana del juego'? Si es algo así:
- Se para sobre la tienda
- Se abre una ventana aparte con la tienda, y por ende la ventana inicial del juego se "des- selecciona"
- Se cierra la tienda o se quiere salir de esta moviendo al personaje fuera del ícono, por lo que se necesita "clickear" sobre la ventana original del juego para que vuelva a estar activa.

Entonces está bien! Si ese no es el caso, comentalo y veremos cual es el veredicto.
Quedamos atentos :3

**Comment by dgzmr** [comment]
@gatochico eso es lo que pasa. Sabes si hay alguna forma de abrir la nueva ventana pero sin des-seleccionar la principal? Se me ocurre hacer `show()` en la principal. Gracias

**Comment by gatochico** [comment]
Lo que ocurre es que no puedes tener dos ventanas activas al mismo tiempo, siempre una quedará activa, mientras que la otra en segundo plano. Si quieres hacer algo como que la ventana de la tienda quede automaticamente en segundo plano a menos que interactues con ella,  podrías probar con algo como [esto](https://stackoverflow.com/questions/12280815/pyqt-window-focus) o buscar algo relativo a mantener el foco en la ventana principal.

Si todavía te quedan cosas de la tarea por implementar, te recomendaría que terminaras eso primero y si te queda tiempo investigar con respecto a esto, ya que no conlleva puntaje.

Éxito!!!

**Comment by dgzmr** [comment]
Gracias
