### ISSUE TITLE
[Ayudantía Threads B18] Aclaración "join" final

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#479]
Hola a todos! 🙌

Quisiera aclarar una cosa que dije al final de la ayudantía en la B18 de hoy. 

Las últimas líneas de la solución eran las siguientes:
```
if __name__ == '__main__':
    laberinto = Laberinto('laberinto.txt')
    # Comenzamos el generador de personas.
    new_humans = threading.Thread(target=laberinto.human_generator, daemon=True)
    new_humans.start()
    # Comenzamos el thread que revisa si hay ganadores.
    watch = threading.Thread(target=laberinto.ver_ganadores)
    watch.start()

    watch.join()
```

Les comenté que el `watch.join()` del final estaba ahí para que el programa no terminara apenas comience. **Me equivoqué 🤥**. Estaba pensando que el *thread* `watch` era un *daemon*. En ese caso, el `join()` hubiera sido necesario, ya que el único *thread* no *daemon* hubiera sido el principal. Sin embargo, definimos el *thread* `watch` como no *daemon*. Por esa razón, no era necesario el `join()`, ya que a pesar que el *thread* principal hubiera terminado, el *thread* que revisaba los ganadores (que es el importante) hubiera seguido .

Otra cosa, les subí la solución al Syllabus. 😃

Si tienen cualquier duda o comentario de la ayudantía, porfa no duden en preguntar!

Saludos!
Ale Kaminetzky

**Comment by mjgutierrez1** [comment]
@akaminetzkyp  ¿Existe algún comando que termine la ejecución del programa, para que así cuando llegen tres personas a la meta ejecuto ese comando y todas las otras personas mueren (porque son Daemon)?, o también podría ser un comando que detenga a todos los threads, sean o no sean daemons.

Pregunto porque en el código de la ayudantía, el programa se ejecuta infinitamente (cuando llega la tercera persona a la meta siguen entrando personas al laberinto).

**Comment by akaminetzkyp** [comment]
Al usar `threading` en Python no es posible parar un thread desde afuera.

Acabo de correr la simulación y el programa termina cuando llegan todas las personas. Qué sistema operativo estás usando? Podrías subir una foto de lo que está pasando?

Saludos!

**Comment by mjgutierrez1** [comment]
Tengo Windows y uso Spyder para programar. En la imagen se puede ver que después de que se anuncian los tres primeros lugares siguen llegando personas al laberinto, que siguen llendo a la meta. Eso sigue así sin parar.

![problema](https://user-images.githubusercontent.com/30670535/31579477-9a44cf04-b10d-11e7-9992-b565e04aa892.png)

**Comment by akaminetzkyp** [comment]
Podrías agregar el parámetro `daemon=True` en la línea 92? Es posible que esos *threads* estén evitando que el programa termine, ya que por el momento no son *daemon*.
