### ISSUE TITLE
Duda Validar bombas y Tortugas

### ISSUE THREAD

**Issue by ggmirandac** [IIC2233/Syllabus#48]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Cuando estamos en el menú de acciones, la opción 2 es validar las bombas y tortugas. Al correr este programa (sea como sea implementado) si el tablero no presenta tortugas, ¿igual se debe correr? Porque, por ejemplo, si no contiene tortugas, se podría decir que todas son válidas porque no hay. ¿O hay que considerar en que si no hay tortugas, son inválidas?

Saludos

**Comment by jtagle2** [comment]
Hola! Se aplica el principio de presunción de inocencia, es decir, para que un tablero sea inválido, debes encontrar algo inválido, en caso contrario será válido.

Un tablero será inválido para la regla 2, si es que hay alguna celda que, teniendo una bomba, esta es inválida. Respecto a la regla 4, se aplica el mismo principio: Un tablero será inválido para la regla 4, si es que hay alguna celda con tortuga, y esta tortuga rompe la regla 4.

**Comment by ggmirandac** [comment]
¡Hola!

Okay, entonces si hay bomba, y no es válida, el tablero es inválido. Lo mismo con las tortugas. Entonces, ¿si no hay tortuga y las bombas son válidas (por x razón) entonces el tablero es válido?

**Comment by Hernan4444** [comment]
Hola @ggmirandac 

Si, puede darse ese caso. Por ejemplo, 

```
3 -
- -

```

Si te damos ese tablero, ese tablero es válido, e incluso ya está solucionado. Por lo tanto, la solución podría ser el mismo tablero, o bien, agregar una tortuga que "no influye en nada". Ambas soluciones serían válidas.

```
3 -
- T

```

Saludos c:
