### ISSUE TITLE
Duda con respecto al Bonus

### ISSUE THREAD

**Issue by despipe** [IIC2233/Syllabus#48]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holaa, tengo una duda con el bonus, la idea es automatizar los 0 o también los números que se encuentren alrededor de estos 0? solo eso, graciaas

**Comment by Emiliax16** [comment]
hola @despipe ! si descubres una casilla 0 (es decir, con 0 bestias a su alrededor), debes descubrir en ese mismo turno las 8 casillas que rodean a la casilla 0. SI alguna de esas 8 casillas es un 0 también, debes repetir el proceso sólo con esa casilla y descubrir sus 8 de al rededor. Esto se debe repetir las veces que sea necesaria mientras te salgan casillas con 0 bestias. Quedo atenta por si sigues teniendo dudas 😺 saludos!

**Comment by despipe** [comment]
Holaa, entonces no debo mostrar también los números que rodeen los 0 que bordean al conjunto de 0s unidos ya descubiertos? Ya que de todas maneras no abrá una bestia y luego el usuario deberá rodear cada 0 manualmente??

**Comment by Emiliax16** [comment]
no entendí bien la pregunta, pero mientras descubras casillas 0's, debes mostrar todas las casillas que lo rodean, ya que ninguna tendrá una bestia. En un puro turno puedes descubrir gran parte del mapa mientras te salgan casillas 0's.
