### ISSUE TITLE
Duda respecto al uso de funciones de dcciudad en nivel_conexiones

### ISSUE THREAD

**Issue by BenjaminIbanez** [IIC2233/Syllabus#48]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, mi duda es que si en la funcion de nivel_conexion se puede usar la funcion de elevar_matriz, ya que en la pregunta sale que se puede utilizar alcanzable pero no dice nada si se pueden usar las otras funciones.

**Comment by pedrozavalat** [comment]
Hola @BenjaminIbanez 😄 !

Si bien la función `nivel_conexion` tiene como **requisito** utilizar la función `alcanzable`, no hay problema que utilices el resto de las funciones del archivo `dcciudad.pyc`. 

Te recomiendo que para todo supuesto realizado en el desarrollo de las funciones de tu tarea debes referenciarlo en tu README. 

Espero que haya resuelto tu pregunta, ¡Éxito en tu tarea! 🚀
