### ISSUE TITLE
Duda respecto a los intentos en los controles formativos.

### ISSUE THREAD

**Issue by Dyotson** [IIC2233/syllabus#48]
Una duda rapida, los controles tienen intentos ilimitados, ¿Esto significa que ustedes se quedan con el mejor puntaje entre los intentos? Osea, ¿me quedo con el mejor intento?.

**Comment by lily416** [comment]
Hola @Dyotson, 

Se mantiene el puntaje más alto de entre todos los intentos que realices. 

Saludos y que tengas una buena semana 👋🌟
