### ISSUE TITLE
Probema al utilizar Jupyter

### ISSUE THREAD

**Issue by domingolira** [IIC2233/Syllabus#48]
- **Sistema Operativo: Windows 10 Home
- **Programa a instalar: Jupyter

- Foto del error:
![imagen_2023-08-21_192109102](https://github.com/IIC2233/Syllabus/assets/141957431/d4264425-577d-46d5-95fe-f92724fe7764)
![imagen_2023-08-21_192127232](https://github.com/IIC2233/Syllabus/assets/141957431/b6ccfa49-239f-4500-88ee-d9fd6efbc22c)
![imagen_2023-08-21_192204016](https://github.com/IIC2233/Syllabus/assets/141957431/1845bd02-a280-41ca-9093-d046356a3aa6)
![imagen_2023-08-21_192354122](https://github.com/IIC2233/Syllabus/assets/141957431/0bf1790a-1d8f-40e5-b44f-6e94fa6d9779)

- Descripción del problema: Al instalar el programa de Jupyter en mi computador, no tuve presuntamente ningún problema, sin embargo, no se afirmaba que se descargó correctamente. En cambio, aparecía el mensaje en amarillo "DEPRECATION". Al ejecutar el comando "jupyter notebook", el mensaje finalizaba con una serie de errores, y al abrir el enlace de Jupyter, no puedo crear ni abrir un archivo, pues me arroja "Error: Permission denied: Untitled.ipynb".

**Comment by Hernan4444** [comment]
Hola @domingolira 

Lo que ocurre es que tu WSL se está abriendo en una carpeeta protegida (`root`) donde no se tiene permisos para crear archivos y jupyter notebook necesita crear archivos, así que necesitamos salir de dicha carpeta. Lo que te recomendamos es:
1.  Abrir WSL 
2. Escribir `cd` (vacío, sin nada más). 
3. Luego escribir `jupyter notebook`

El paso (2) te mandará a tu carpeta raíz válida para WSL donde sí tendrás permiso de edición, y no a `root` que es la carpeta protegida.

En resumen. Primero abres WSL y luego en tu terminal debería verse los siguientes comandos:

<img width="502" alt="image" src="https://github.com/IIC2233/Syllabus/assets/15641721/55a17446-b460-4ac7-ae37-1c9ac1c10ce1">

Avísanos cómo te va con esto

Saludos!
