### ISSUE TITLE
Duda de flujo luego de crear un grupo o añadir un contacto

### ISSUE THREAD

**Issue by JOSELAGOSG** [IIC2233/syllabus#48]
### Prerrequisitos

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

###  Hacia qué menú debo dirigir al usuario luego de crear un grupo exitosamente?
...Y al añadir un contacto?
Al parecer no está especificado en el enunciado...
**Gracias!**

**Comment by Juampisaez** [comment]
Hola @JOSELAGOSG!
Tanto luego de crear un grupo o añadir un contacto, puedes asumir que volverá al menu previo a esa opción.
Un ejemplo, si estoy en el menu de grupos y quiero crear un grupo, luego de crearlo exitosamente te debería redirigir al menu de grupos. Lo mismo al añadir un contacto.

Espero haya quedado claro,
Cualquier cosa puedes volver a comentar esta issue :)

**Comment by JOSELAGOSG** [comment]
Estimado @Juampisaez 
Sinceramente no esperaba una respuesta tan rápida.
Me ha quedado clarísimo! 


**MUCHAS GRACIAS!**
