### ISSUE TITLE
Optimizacion

### ISSUE THREAD

**Issue by Veenty** [IIC2233/Syllabus#48]
Cuando tengo que determinar cuales son las mejores combinaciones para apagar cierto indendio, puedo suponer que el fuego deja de propagarse, o si es que pasa mas de una hora, tengo que considerar que aumento.

**Comment by FernandoPieressa** [comment]
Hola!

Si tienes que considerar la propagacion de fuego que pueda suceder en medio del proceso de apagar el fuego.

Saludos!
