### ISSUE TITLE
Flujo errores creación de prograpost y seguir usuario inválido

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#48]
*Durante la creación de un prograpost en caso de que este último no cumpla con los requisitos dice el enunciado que se debe detener la operación e informarle al usuario el problema pero una vez que le informo acerca del problema el programa vuelve al menú de inicio o al menú de prograposts.
*Respecto al menú de seguidores menciona que al elegir seguir a un usuario y que dicho usuario no exista se informa al error y vuelva al menú, en esta parte hace referencia al menú de inicio o al menú de seguidores

**Comment by aljara97** [comment]
Hola @RonaldoSosa,  con respecto a tu primera pregunta, esto puede quedar a tu criterio. Sin embargo, es importante que informes que no cumple con los requisitos mínimos de un prograpost y mantengas un flujo consistente del programa.

En el segundo caso, cuando quieras seguir a un usuario no válido, como no se especifica cuál de los dos menús debes volver, también puede quedar a tu criterio. Te recomiendo en este caso volver al menú de seguidores, para que la interfaz sea más amigable para el usuario. Lo más importante cuando manejes errores en esta tarea es avisarle al usuario y permitirle seguir interactuando en la interfaz sin problemas.

Éxito y espero haber aclarado tus dudas :D

**Comment by RonaldoSosa** [comment]
Me quedo claro!Muchas gracias
