### ISSUE TITLE
al conquistar un planeta

### ISSUE THREAD

**Issue by Pelaysen** [IIC2233/Syllabus#48]
al conquistar un planeta, el planeta conquistado queda poblado con la raza con la que parti el primer planeta, o con la raza que posee ya el planeta que conquiste?

si el planeta queda con la raza del primer planeta que tuve, en el evento del archimago, si desconquista mi planeta, con que raza queda ese planeta desconquistado? (ya que su poblacion y edificios quedan al maximo al desconquistarlo)

**Comment by leolivares** [comment]
Hola! La raza es una característica intrínseca del planeta. Por lo tanto, al ser conquistado el planeta, queda con la misma raza inicial.
