### ISSUE TITLE
Problema de enunciado con la revisión de estados de encomienda realizadas por el usuario

### ISSUE THREAD

**Issue by rodrigoogalde** [IIC2233/Syllabus#48]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!
Tengo una duda sobre enunciado, ya que dice 2 cosas distintas sobre qué desplegar al momento de consultar el estado de las encomiendas realizadas.
Debo mostrar toda la información del pedido o solo nombre y estado?
Gracias!
![image](https://user-images.githubusercontent.com/85193399/159749429-25e6e9ff-0fb6-4aa2-956b-78cf3acc65d6.jpeg)
![image](https://user-images.githubusercontent.com/85193399/159749465-7d78b956-ef24-4852-a490-e942d8ffe59f.jpeg)

**Comment by magdalenanario** [comment]
Hola @rodrigoogalde ! Para el método **Revisar estado encomiendas realizadas** se deben desplegar las encomiendas con todos sus atributos (nombre, receptor, peso, destino y estado), similar a como sale en el ejemplo de la figura 6. Saludos!

**Comment by rodrigoogalde** [comment]
Gracias!

**Comment by magdalenanario** [comment]
Al final como sale de las dos formas en el enunciado, se van a aceptar ambas. Lo importante es que mínimo tenga el nombre de articulo y el estado
