### ISSUE TITLE
Manejo de archivos.csv

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2233/Syllabus#48]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ]X De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda sobre el manejo de los archivos.csv para la tarea 0,
Específicamente a la hora de agregar un string en la siguiente fila.
Actualmente estoy intentando agregar esa linea con string, pero me encuentro con un error ya que en el primer print hacia el archivo, el string se agrega inmediatamente después del último nombre, y luego en los strings subsiguientes se agrega de la forma que yo quiero.
metodo usado: file = open( archivo.csv, 'a')

Yo se que puedo resolver esto si escribo todo el contenido de nuevo, junto con lo nievo que quiero agregar.
Pero quería saber si hay una forma de arreglar lo que detallé anteriormente sin tener que reprintear todo el contenido del archivo cada vez que quiera agregar algo (sería usando:  file = open( archivo.csv, 'w')

tambien me di cuenta que depende donde deje la barra que agrega caracteres en el archivo antes de printear, lo que tambien puede desordenar el archivo

**Comment by ivanvlam** [comment]
Hola @vice-rosas99 ! Si lo que te sucede es algo como esto:
```
usuario
Gatochico
matiasmasjuan
igbasly
Christian-Klempau
DCCollaoUsuarioNuevo1
UsuarioNuevo2
UsuarioNuevo3
```
Entonces, puedes agregar un salto de línea antes del primer print que deseas hacer, es decir, escribir `print('\n')`, seguido de los prints de UsuariosNuevos que correspondan.
Respecto a lo de la barra, no entendí muy bien, por lo que si no se soluciona con esto podrías tratar de explicarme mejor.
Espero te sea de ayuda!

**Comment by vice-rosas99** [comment]
si algo así pasaba

respecto a lo de la barra: por ejemplo si abro el archivo usuarios.csv y hago clic en la mitad de un nombre antes de ejecutar mi código, empezará a escribir desde ahí, o si hago clic en la linea que está después del último nombre, printeará los nombres cmo yo quiero

**Comment by vice-rosas99** [comment]
los veo desde el editor (Vscode) en paralelo con los archivos.py

**Comment by ivanvlam** [comment]
Que raro entonces. De igual manera, como te comenté, puedes asumir que durante la revision los elementos agregados al archivo serán después del último carácter, por lo que puedes considerar que la barra estará al final del documento.
Quedo atento. Saludos

**Comment by vice-rosas99** [comment]
ok, igual da lo mismo lo de la barra, pq simplemente la pongo al final del ultimo elemento antes de cerrar el archivo en el editor

**Comment by ivanvlam** [comment]
Hola @vice-rosas99 ! Perdón la demora. Si existe descuento por no mantener el formato en los archivos `.csv`, tanto en el caso de los saltos de línea como en el de tener dos usuarios en la misma línea.
