### ISSUE TITLE
problema al tratar de modularizar

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#48]
En base al ejemplo del documento "00 - Intro Curso.pdf" en la semana-00 de los contenidos tengo dos preguntas:

1. ¿Siempre que creo una nueva carpeta donde pongo archivos que llamaré en mi código principal es necesario crear un archivo vacío llamado "__init__.py"?¿por qué?

2. Pude acceder y utilizar el código de un archivo .py ubicado en la misma carpeta que mi código principal, pero cuando trato de acceder a otro archivo.py ubicado en otra carpeta me tira error:

Cuando uso `from carpeta_1 import archivo_3 as ar3` y en el código principal ejecuto `print(ar3.factorial(5))`, todo funciona bien. Pero cuando uso `import carpeta_1 as ca1` (tal como se hace en el documento "00 - Intro Curso.pdf") y en el código principal ejecuto `print(ca1.archivo_3.factorial(4))`, no se ejecuta todo el código del archivo_3 ni se printea el resultado de usar la función `factorial()` que definí en el archivo_3. Además al hacer esto último me tira el error `AttributeError: module 'carpeta_1' has no attribute 'archivo_3'`

**Comment by mjgutierrez1** [comment]
Otro problema es que usando la forma que sí funciona (from carpeta_1 import archivo_3) los archivos que están en la misma ubicación que el archivo principal sí se ejecutan cada vez que ejecuto el archivo principal, mientras que los archivos adentro de la carpeta_1 sólo se ejecutan la primera vez.

El problema de eso es que, por ejemplo, si después de haber ejecutado una vez el archivo principal elimino la función factorial() del archivo_3, si vuelvo a ejecutar el archivo principal la función factorial que es llamada en este archivo se vuelve a ejecutar, a pesar de haber sido borrada en el archivo_3 (luego de realizar cada cambio guardé los cambios).

**Comment by indonoso** [comment]
> 1. ¿Siempre que creo una nueva carpeta donde pongo archivos que llamaré en mi código principal es necesario crear un archivo vacío llamado "init.py"?¿por qué?

No es necesario a menos que estés creando un package. Solo los packages deben tener un archivo `__init__.py`. Puedes ver más detalles [aquí](https://docs.python.org/3/tutorial/modules.html#packages)


> 2. Pude acceder y utilizar el código de un archivo .py ubicado en la misma carpeta que mi código principal, pero cuando trato de acceder a otro archivo.py ubicado en otra carpeta me tira error:Cuando uso `from carpeta_1 import archivo_3 as ar3` y en el código principal ejecuto `print(ar3.factorial(5))`, todo funciona bien. Pero cuando uso import carpeta_1 as ca1 (tal como se hace en el documento "00 - Intro Curso.pdf") y en el código principal ejecuto `print(ca1.archivo_3.factorial(4))`, no se ejecuta todo el código del archivo_3 ni se printea el resultado de usar la función factorial() que definí en el archivo_3. Además al hacer esto último me tira el error `AttributeError: module 'carpeta_1' has no attribute 'archivo_3'`

Lo que ocurre (y que no explicamos ese día en la clase) es que para importar un package (la carpeta) y usar los módulos que están dentro sin importarlos directamente deben haberlos importado en el `__init__.py` de esta forma `from . import modulo`. Esto debería funcionar :)
