### ISSUE TITLE
Duda con subir carpeta "Puntajes"

### ISSUE THREAD

**Issue by oscars810** [IIC2233/syllabus#48]
Hola,
Para entregar la tarea quiero subir la carpeta puntajes, y en el gitignore puse todos los .txt para que no se suban los datos que he jugado en mi pc. El problema es que no se está subiendo la carpeta (que quiero subirla vacía) y creo que dará problemas cuando se intente correr mi código y se quieran leer los archivos.

**Comment by jeschuwirth** [comment]
Saludos!

Github no sube las carpetas vacías ya que no tienen archivos, un modo de arreglarlo es que subas la carpeta con el puntaje de un jugador, sin embargo como es un problema pequeño y fácil de arreglar basta con que coloques un anuncio en tu readme que avise al corrector debe crear la carpeta puntajes antes de correr el programa.

Suerte en la tarea!

**Comment by lily416** [comment]
Si te sientes más cómodo subiendo la carpeta a tu repositorio, en esta _issue_ #27  se indica como subir carpetas vacías a github.

Saludos y éxito con la tarea 👋 💪
