### ISSUE TITLE
distritos especie bisiesto

### ISSUE THREAD

**Issue by Martinluco** [IIC2233/Syllabus#480]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Podemos asumir que un año bisiesto es solamente divisible por 4? o hay que tener en cuenta el caso especifico de multiplo de 100 pero no de 400??
gracias!

**Comment by ignacio-sp** [comment]
Hola @Martinluco, el enunciado sólo menciona que el año debe ser bisiesto, y según la definición de este, se debe tener en cuenta los casos que mencionas para que se cumpla aquello, quedo atento a tu respuesta!

**Comment by Martinluco** [comment]
Listo muchas gracias!
