### ISSUE TITLE
Duda ayudantia Chat

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#480]
Hola, en mi código, que está basado en la ayudantia de chat recomendada, el titulo del Chat me aparece cortado, alguna idea de porqué podría ser este error, pues si es un problema con el código no logré identificarlo (al ejecutar la ayudantia tal cual, el título "DCChat" aparecía igual entrecortado).

![image](https://user-images.githubusercontent.com/47841749/59303984-65dbcd00-8c65-11e9-99ef-62cc588c2220.png)

**Comment by BernaValdivieso** [comment]
En el archivo FrontEnd.py, en el método `init_setUp` de la clase `VentanaChat`, tienes que cambiar los valores del alto y ancho en `self.label_titulo.setGeometry` .
