### ISSUE TITLE
Ejercicio 1.1 semana 10

### ISSUE THREAD

**Issue by Piolawa** [IIC2233/syllabus#480]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, 
No entiendo como hacer el ejercicio, creo que lo principal es donde colocar la funcion es_primo y donde se recorren los datos, aunque los datos no se crean fuera, sino dentro (eso también me confunde :c ayuda)

**Comment by MatiasDuhalde** [comment]
Hola @Piolawa !

Ten en cuenta que este ejercicio además de la clase `IterablePrimos`, te pide implementar una clase `Iterador`, la cual contendrá los métodos `__iter__` y `__next__`. Este último debe ser el encargado de retornar el siguiente número primo. 

¿Pero cómo se obtiene ese primo? Es parte del desafío que pedimos en el ejercicio, deben encontrar una manera de generar el siguiente número primo del iterador.

Como pista, puedes iterar sobre todos los número en un **rango**, y retornar el primero que sea primo (es decir, el primero en el cual la función `es_primo` retorne `True`). Eso sí, antes de retornar debes preocuparte de modificar este **rango**, para que la próxima vez que se use el iterable retorne el primo siguiente, y no el mismo todo el rato. Además, debes levantar la excepción `StopIteration` en algún lado (y dada cierta condición) para que el `for` sepa cuando dejar de iterar.

Te recomiendo tomar como base los ejemplos que se colocan en el notebook de [contenidos](https://github.com/IIC2233/contenidos/blob/main/semana-10/1-iterables-generadores.ipynb).

Ojalá eso haya aclarado un poco el ejercicio, y si sigues con dudas, pregunta! :sparkles:

**Comment by Piolawa** [comment]
Hola y gracias!,  me quedó mas claro, y logré que me entregara los primos, peeero, los que no son primos me entrega None, y no entiendo como hacer que eso no pase :c
