### ISSUE TITLE
implementos deportivos y entrenamiento

### ISSUE THREAD

**Issue by eliasbruchfeld** [IIC2233/syllabus#481]
Hola! en el enunciado dice que los implementos deportivos contribuyen a un entrenamiento más eficiente, pero tambien dice que si entreno un deportista, el atributo entrenado aumenta en PUNTOS_ENTRENAMIENTO, que es un parámetro que no considera el nivel de implementos deportivos.

Después, en ninguna otra parte hablan de como el nivel de implementos deportivos ayuda al entrenamiento por lo que no me queda claro a que se refiere con que contribuyen a un entrenamiento más eficiente.

**Comment by eliasbruchfeld** [comment]
alguen sabe porfa??? creo que me falta solo esto

**Comment by amparostevens** [comment]
Hola @eliasbruchfeld !

Primero me disculpo por la demora y los inconvenientes que te haya podido provocar. 

Con respecto a tu pregunta, los implementos deportivos no afectan la fórmula de entrenamiento de los deportistas, para ello sólo tienes que considerar los `PUNTOS_ENTRENAMIENTO`. 

El nivel de implementos deportivos se usa en los métodos `calcular_ganador` de cada deporte. 

Mucho éxito en la tarea! 🌈

**Comment by camilapavesi** [comment]
Hola @amparostevens :)
Me quedó una duda con respecto a tu respuesta anterior. Por lo que entiendo del enunciado, ```calcular_ganador``` solo usa las formulas del enunciado y éstas no consideran el nivel de implementos deportivos. Por otro lado, ```validez_de_competencia``` sí verifica que las delegaciones tengan un mínimo de implementos deportivos. Entonces, se debe incluir el nivel de implementos deportivos en ```calcular_ganador``` de alguna forma?
Gracias!!

**Comment by amparostevens** [comment]
Hola @camilapavesi !

La fórmula de `calcular_ganador` para cada deporte __no incluye__ el nivel de implementos. Este sólo se usa para saber si la competencia es válida, y sólo en caso que el deporte necesite de implementos. Si el deporte no necesita de éstos, entonces no importa si la delegación cumple con que su nivel de implementos sea mayor al parámetro.

**Comment by camilapavesi** [comment]
Perfecto muchas gracias!! :D
