### ISSUE TITLE
Creación de sala nueva

### ISSUE THREAD

**Issue by fivaldivia** [IIC2233/syllabus#481]
Hola, quería saber si cuando un usuario crea una sala nueva este ingresa automáticamente a esta? Por lógica, yo creo que sí pero prefiero estar segura, muchas gracias:)

**Comment by jeschuwirth** [comment]
Hola!

en el enunciado (s. 5.3.1) dice: "La persona que cree la nueva sala será asignada como jefe de esta, hasta que se desconecte o salga de la sala".

Está medio oculto y se entiende la confusión, pero tu lógica es correcta: si un usuario crea una sala nueva este ingresa automáticamente a esta.

Suerte en la tarea !
