### ISSUE TITLE
filter, map y demás cuentan como generador?

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#481]
Para los outputs de las funciones que retornan bases de datos, ¿un filter y las otras cosas similares cuentan como generadores?

Gracias

**Comment by Hernan4444** [comment]
@jmwielandt si cuentan 👍 

Saludos ✌️

**Comment by Arcoirisky** [comment]
Sip O: a menos que hagas un [(algo con filter u otra cosa parecida)], tanto como {} y cualquiera que te terminé guardando el generador en la memoria c:
