### ISSUE TITLE
Test malo: test_8 de test_16_mismo_mes_por_candidato espera un generador erroneo

### ISSUE THREAD

**Issue by waknaudt** [IIC2233/Syllabus#481]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Estoy casi seguro que el test 8 del test_16_mismo_mes_candidato esta malo, me dice que el animal con id=2633 deberia estar en el generador de quienes votaron por candidato con id=2633 y tienen misma fecha de nacimiento, pero el candidato con id=2633 no voto por si mismo por lo que no debiera estar en el generador. Ademas, no entiendo por que esta funcion recibe generador_candidatos, cuando no es necesario usarlo.

**Comment by Segismundios** [comment]
Hola @waknaudt. Revisando el archivo csv votos actualizado, encuentro que la línea 9372 es la siguiente: 9372,2633,2212,2633 Donde se indica id_voto, id_animal_votante, id_local, id_candidato respectivamente. Considerando esto, el animal con id 2633 sí debería estar en el resultado entregado.
En relación a tu segunda pregunta, sí pareciera ser redundante el generador_candidatos. Si llegas a pasar los tests sin usar ese generador, no debería haber problema.
