### ISSUE TITLE
Segundos fase planta

### ISSUE THREAD

**Issue by muovalle** [IIC2233/syllabus#481]
el parametro TIEMPO_XXXX se refiere a la cantidad de segundos reales que demora una fase o segundos en mi juego?

**Comment by aundurraga** [comment]
Hola! esto fue contestado en la issue #401! 
Efectivamente el parámetro del tiempo que demora una fase corresponde a un tiempo interno del juego, es decir segundos del juego.

**Comment by muovalle** [comment]
gracias! y duracion de la leña y oro tambien son segundos del juego?

**Comment by aundurraga** [comment]
Si! Todo es en base al tiempo de tu juego!
