### ISSUE TITLE
caracteres por línea

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2233/syllabus#481]
Hola! Uso vscode y pep8 esta configurado para un maximo de 80 caracteres por linea, como puedo cambiarlo a 100?

**Comment by benjavicente** [comment]
Yo lo cambié!
Tienes que abrir tu settings.json

**Comment by benjavicente** [comment]
Yo lo cambié! Tienes que abrir `settings.json` (lo puedes abrir buscando `settings (JSON)` con `ctrl` + `shift` + `p`) y añadir los argumentos
```json
    "python.linting.pycodestyleEnabled": true,
    "python.linting.pycodestyleArgs": ["--max-line-length=100"],
```
También añadí una regla para mostrar donde está ese límite con
```json
    "[python]": {"editor.rulers":
        [
            {
                "column": 100,
                "color": "#ff000060"
            },
        ]
    },
```

**Comment by mariovaldesa** [comment]
gracias!
