### ISSUE TITLE
Parámetros en escenarios.csv

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#481]
Hola!

En el enunciado se presentan once parámetros que estarán presentes en `escenarios.csv`. ¿Siempre estarán todos estos en el archivo? ¿En el mismo orden también? Entiendo que si hay un `-` debemos usar el valor por defecto.

Saludos!

**Comment by iqacevedo** [comment]
Hola! 

No necesariamente aparecerán todos, sin embargo solo pueden aparecer los que se indican en el enunciado, el orden puede variar. Cuando aparece un `-` es justo como dices, si ves el archivo escenario.csv que está subido podrás notar que alguno de los valores de algunos parámetros tienen `-`.

Saludos !

**Comment by akaminetzkyp** [comment]
Perfecto. Gracias!
