### ISSUE TITLE
Error sprites T2

### ISSUE THREAD

**Issue by ValeskaSantos** [IIC2233/syllabus#481]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holaa, estaba revisando los sprites de las tarea, y noté que en las sprites de lisa hay 2 left y 4 right, creo que hay un error en el left_3.

**Comment by tqmbanados** [comment]
Hola! Efectivamente hay un error. Conversaré del tema para ver si hay una solución que pueda ser aplicada generalmente (cambiar el archivo y hagan otro pull), pero el sprite que debería ser es el mismo pero reflejado. Con cualquier editor de imágenes deberías poder reflejar el sprite ```left_3.png``` de Lisa para que quede mirando y a la derecha y funcione. Gracias por avisarnos!

**Comment by tqmbanados** [comment]
Se realizará el cambio directamente en el syllabus! Así que puedes hacer pull de nuevo y se arreglará. No debería borrarse ningún avance que llevas.

**Comment by ValeskaSantos** [comment]
muchas graciasss!
