### ISSUE TITLE
TypeError: Cliente cannot be converted to PyQt5.QtCore.QObject in this context

### ISSUE THREAD

**Issue by isihirmas** [IIC2233/syllabus#482]
Hola! cuando trato de emitir la señal desde el cliente al frontend me tira este error y no entiendo por qué o cómo arreglarlo. En stackoverflow dicen esto:

QGraphicsItem does not inherit from QObject, therefore it is not possible to emit a signal from an instance of QGraphicsItem. You can solve this by subclassing QGraphicsObject instead of QGraphicsItem: http://doc.qt.io/qt-5/qgraphicsobject.html.
Pero tampoco lo entendí.

Gracias!

**Comment by jeschuwirth** [comment]
Saludos!

subclassing se refiere a herencia, si tienes dos clases, por ejemplo vehículo y autobús, donde autobús hereda de vehículo, entonces se dice que autobús es una subclase de vehículo.

Lo que te recomiendan en la solución es que tu Cliente herede de QGraphicsObject en vez de QGraphicsItem, inténtalo y avisa si te funciona.

Suerte!

**Comment by isihirmas** [comment]
Sí lo arregle recién gracias! 
Otra cosa, me pasa que la señal me va "sumando los mensajes" en el chat:
<img width="177" alt="Captura de pantalla 2019-06-11 a la(s) 18 02 40" src="https://user-images.githubusercontent.com/43628848/59310036-24eab500-8c73-11e9-9521-a5553abc3492.png">

También me estoy basando en el código de ayudantía que nos dijeron, pero la señal la emito una sola vez y el chat log si le borro el '+' solo queda en la pantalla el último mensaje.
Gracias!

**Comment by jeschuwirth** [comment]
No he visto la actividad con el chat como para ayudarte con esa duda. Te recomiendo escribir una nueva issue con esa consulta para evitar que se pierda entre todos los comentarios.

De todos modos lo voy a revisar hoy cuando regrese a mi casa, así que ahí te podré ayudar mejor.
