### ISSUE TITLE
Cambiar tamaño de fuente en qt designer

### ISSUE THREAD

**Issue by a-ck** [IIC2233/syllabus#482]
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Me gustaría saber cómo achicar la letra en qt designer (no me refiero a la letra de los widgets que estoy creando, me refiero a las letras del programa qt designer) porque encuentro que están muy grandes y se me hace muy incómodo trabajar así. Desde ya gracias.

**Comment by clementevalladares** [comment]
Hola @a-ck, para cambiar el tamaño de fuente en el programa tienes que presionar en la barra superior Settings -> Preferences. Dentro de esa ventana, ir a la pestaña "Appearance", y cambiar "Point Size" por el tamaño de fuente que prefieras, con OK visualizarás los cambios.

![image](https://user-images.githubusercontent.com/69611854/119243886-ed603500-bb38-11eb-8233-a11c5b33afb5.png)

**Comment by a-ck** [comment]
Muchas gracias!!
