### ISSUE TITLE
Bancarrota

### ISSUE THREAD

**Issue by MrEarle** [IIC2233/Syllabus#482]
La bancarrota ocurre si llevan 20 días seguidos sin vender o 20 días en total sin vender?

**Comment by fdominguezclaro** [comment]
Hola!
Son 20 días seguidos sin vender. 

Saludos!!

**Comment by JPSF** [comment]
¿Se consideran todos los días de la semana(incluyendo fines de semana?

**Comment by iqacevedo** [comment]
Hola,

No, ya que el vendedor no intenta vender un fin de semana.

Saludos !
