### ISSUE TITLE
Qtimer

### ISSUE THREAD

**Issue by Dafnemami** [IIC2233/syllabus#482]
Tengo un Qtimer para la hora y minutos por separado. 

Funciona bien, pero al momento de pausar ( Qtimer.stop() ), el QTimer de la hora se queda por un periodo adicional (entiéndase por periodo adicional al periodo de tiempo puesto en .setInterval) y no entiendo el por qué de esto, alguna idea??

🚀 🌵 🌖

**Comment by lily416** [comment]
Entiendo porque utilizas dos _timers_ para modelar el tiempo, pero lo correcto sería que la cantidad de horas que han pasado depende de la cantidad de minutos. 

Por lo que lo correcto sería modelar el tiempo sería usando un sólo _timer_, ya que de esta forma las horas depende de los minutos y no tendrás problemas al "pausar" el tiempo.

Saludos y éxito con tu tarea 👋👨‍🚀
