### ISSUE TITLE
Tipo de valor para moral de una delegación

### ISSUE THREAD

**Issue by MagnaThyrsus** [IIC2233/syllabus#482]
En el enunciado se especifica que la moral es un `int`, pero es también el promedio de las morales de los deportistas en el equipo, y eso probablemente da un `float`. El valor se debe truncar o redondear o qué se puede hacer?

**Comment by vsantelicest** [comment]
Hola **@MagnaThyrsus**!
El valor de la moral de la delegación debe ser tratado como un float, tal como se indica en la issue #345.
Suerte!! 🥇
