### ISSUE TITLE
Módulo extra para manejar excepciones

### ISSUE THREAD

**Issue by Panckx** [IIC2233/Syllabus#482]
Hola! Está bien si creo un módulo aparte encargado de manejar excepciones, 'formatear' las respuestas y entregarle las respuestas listas al main.py? O es requisito que las excepciones sean manejadas explícitamente en el main? Lo que pasa es que lo hice así para mantenerme ordenado pero he leído recien ahora en algunas issues que el main.py debe manejar las excepciones.

**Comment by Hernan4444** [comment]
@Panckx sorry lo muy tarde, pero estaba bien eso.
