### ISSUE TITLE
Error enunciado fromato hora namedtuple pedidos

### ISSUE THREAD

**Issue by Salvaknz** [IIC2233/Syllabus#482]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

En el enunciado sale que en la namedtuple pedidos el formato de hora es HH:MM:SS y yo estaba manejando el generador_pedidos de la funcion clientes_despues_hora pero al printear me di cuenta que el test entrega las horas en formato HH:MM al igual que la hora del segundo argumento de la función.

**Comment by Salvaknz** [comment]
Hola, también me estaba pasando que me funcionaba de una forma para uno de los test y de otra para el otro. En tests_publicos.test_05_clientes_despues_hora_correctitud el formato de hora del generador es HH:MM y en el de carga datos es HH:MM:SS donde HH siempre es 00

**Comment by FradexMF** [comment]
Hola!
Gracias por decirnos, fue una inconsistencia de nuestra parte. Los generadores de Pedidos deberían de tener la hora en el formato "HH:MM:SS" siempre. Pronto arreglaremos el test de correctitud 05 para que las instancias de Pedidos cumplan con el formato. Por otro lado, el segundo argumento de la función sí es entregado en el formato "HH:MM".

En cuando a que HH siempre sea 00, para los test de carga se utilizan los datos de la carpeta /data y no veo que pase esto que me dices en ellos, revisa bien que no sea un error de tu parte o de como están guardado los datos en tu copia local.

Suerte!

**Comment by Salvaknz** [comment]
Gracias!! Respecto de lo segundo, creo que si es error mío, voy a esperar la corrección entonces para ver si mi funcion sirve.
