### ISSUE TITLE
Descuentos por ¡variables globales!

### ISSUE THREAD

**Issue by Francisco5674** [IIC2233/syllabus#483]
Hola, tengo una duda con respecto a esta mala practica, ya que supongo que tener variables globales en módulos que no sean el principal esta permitido , o siempre esta prohibido?, ademas, te descuentan 5 décimas de la nota final por cada vez que detecten una variable global o que onda?
(Claro dejando de lado el hecho de parametros.py son solo variables globales ya que esta hecho para eso XD)

**Comment by KnowYourselves** [comment]
Hola @Francisco5674!

La únicas variables globales que permiten en tu programa son las que se encuentran en el archivo de parametros, en ningun otro módulo deberías tener variables globales. En cuanto al descuento, el máximo descuento por malas prácticas es 5 décimas y cuantas décimas se descuenten en especifico dependera de en que malas prácticas caigas.

Quedo atento a cualquier duda!

**Comment by Francisco5674** [comment]
F por mi
