### ISSUE TITLE
For en funciones que hacen return

### ISSUE THREAD

**Issue by TomasAndresPino** [IIC2233/Syllabus#483]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

[Describe tu duda de manera detallada, explicando los contenidos en cuestión y ojalá colocando código o un caso de uso de ejemplo]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola,  si es que uso for en cierta función pero es una función que es definida como 

def f(...) -> str: 

Mi duda es, si la funcion retorna un string ¿es generadora? y mi otra pregunta es, si no es generadora (creo que no es) ¿puedo ocupar un for para iterar en un iterable y luego hacer el return del string?

**Comment by diegobas10** [comment]
Hola @TomasAndresPino, 
Lo primero que dices como tu bien dices no es una función generadora, ya que estas ocupan la función yield, en vez de return, además puede formar generadores con (2 * i for i in range(n)) como aparece en los contenidos del curso. Con respecto a lo segundo si se puede usar un for mientras se use por comprensión, te dejó como ejemplo la issue #315
Saludos, quedo atento a cualquier duda
