### ISSUE TITLE
No se corregira lo que aparezca en consola

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#483]
quiere decir esto que si tengo todas las cosultas hechas con el las exceociones correspondientes, pero no alcanzo a hacer funcionar la gui tendre un 1. o se dara puntaje por que las consultas esten programadas.
pregunto esto ya que si no alcanzo a implementar la gui me gustaria hacer correr las consultas por la consola para que sea mas facil para los ayudantes corregir

**Comment by Hernan4444** [comment]
@ljrodriguez1 las reglas del enunciado especifican que solo se corrige lo que aparece en la interfaz (o archivo en caso de save_file).

Saludos!

**Comment by rihanuch** [comment]
¡Hola @ljrodriguez1 !

Tu duda y fue resuelta en otras issues

Saludos🍀
