### ISSUE TITLE
partido futbol mes 

### ISSUE THREAD

**Issue by afcarvallo** [IIC2233/Syllabus#483]
Hola, tengo una duda sobre cual lambda (λ) elegir para simular la cantidad de partidos de futbol ya que tenemos dos opciones: 

1. el valor de lambda que se obtiene de escenarios.csv
2. el que dice en el enunciado λ = 1/70
 
Lo mismo para los otros eventos no programados (fiestas y corte de agua).

Gracias!

**Comment by Hernan4444** [comment]
Sección 8.
![image](https://cloud.githubusercontent.com/assets/15641721/26029232/b6f0824a-3806-11e7-938c-728fb77f7f19.png)
