### ISSUE TITLE
VentanaCasa

### ISSUE THREAD

**Issue by Dafnemami** [IIC2233/syllabus#483]
Es necesario mostrar la barra de stats y el inventario cuando enzo entra a la casa?

**Comment by gatochico** [comment]
Hola! 

Si es que estás implementando el bonús de casa como mapa, ambos elementos (inventario y stats) deberían seguir mostrandose, ya que la "ventana" de la casa sigue contando como Ventana de juego, sólo que reemplazando el mapa del campo por el de la casa.

Salu3 :dove:
