### ISSUE TITLE
Matriz RGB

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#483]
Hola ocupe la función get_pixels a una imagen e imprimí la matriz que me arrojaba, no entiendo que significa cada valor dentro de la tupla correspondiente (son 4 valores)

**Comment by jeschuwirth** [comment]
Hola!

RGB es una matriz en la cual cada celda esta representada por una tupla de 3 valores, cada valor representa un color principal (R = rojo, G = green, B = Blue) y tienen asociado un entero entre 0 y 255, este número representa la "intensidad" de ese color, por ejemplo:

- la tupla (255,255,255) representa un pixel de color blanco
- (0,0,0) es un pixel negro 
- (238,130,238) es un pixel violeta

Además algunas imágenes .png vienes con un cuarto número que representa la opacidad de la imagen
0 significa 100% transparente y 255 es una transparencia de 0%. (esos son los 4 valores en tu matriz)

Para entender mejor que significa cada valor y como trabajarlos en la tarea tienes que leer el archivo 
 [T03 - PNG y Filtros.pdf](https://github.com/IIC2233/syllabus/blob/master/Tareas/T03/T03%20-%20PNG%20y%20Filtros.pdf) que viene en la misma carpeta que el enunciado.

Suerte en la tarea !

**Comment by jalliende** [comment]
Sisi lo lei, pero como solo había que trabajar con 3 valores no entendía que estaba pasando, el orden obvio que es rojo verde azul cierto? Muchas gracias

**Comment by marioreinike** [comment]
Sí, el orden es el mismo. Sólo cambia que se le agrega un nuevo valor correspondiente a la opacidad del pixel, pero el orden se mantiene igual.

**Comment by jalliende** [comment]
Muchas gracias. Otra duda como puedo pasar de una matriz de pixeles a formato png, eso no lo entiendo, ya que la función de "ida" es la get_pixels..... Muchas gracias

**Comment by jalliende** [comment]
En el enunciado apare como pasar de RGB a JPG pero la matriz inversa de la binaria que se obtiene al final del paso de el filtro dibujo de que tipo es?

**Comment by iqacevedo** [comment]
Hola,

@jalliende respecto a tu primera pregunta, para pasar de la matriz de pixeles a formato PNG, debes escribir a mano el archivo, con las instrucciones que salen al final de la sección **1. Manejo de bytes: Formato PNG**. Esto es justamente una de las cosas que estamos evaluando.

Respecto a la segunda, cuando se habla de imagen en el paso 5 del filtro dibujo, se refiere a la matriz que se obtiene luego de binarizar.

Sale como imagen porque todas las matrices resultantes de cada paso, son representaciones de una imagen, pues son matrices de pixeles (en la mayoría de los pasos del filtro dibujo, son matrices que representan una imagen en escala de grises, debido al paso 2).

Espero que haya quedado claro. 

Saludos y exito!

**Comment by jalliende** [comment]
pero la matriz que se obtiene es de un solo componente.... se escribe esa misma componente 3 veces?

**Comment by marioreinike** [comment]
Exacto. Como fue nombrado más arriba, (0,0,0) es blanco, y (255,255,255) es negro. Saludos

**Comment by niguzman** [comment]
Hola, tengo una pregunta relacionada a esto.
Con los RGB alpha, debo sumarle 255 a la fórmula que nos dan de x? o debo dejar una tupla del estilo (x, 22) para cada pixel?

**Comment by jeschuwirth** [comment]
@niguzman, revisa el final del Hint en la sección 2.1
![image](https://user-images.githubusercontent.com/37160256/59900587-bde1a480-93c6-11e9-9aa5-b736f34b66df.png)

Por lo tanto no es necesario que trabajes con el alpha mientras tengas sólo el canal x, cuando conviertas ese pixel en la tupla (x,x,x) le puedes agregar un 255. (x,x,x,255). 

Otra opción que te recomiendo más si estas teniendo problemas es ignorar el alpha, recuerda que debes ser capaz de leer la imagen de manera correcta tenga o no tenga un alpha, pero la puedes guardar en formato PNG con tuplas de RGB como si no hubiese tenido el alpha.

Exito en esta tarea!
