### ISSUE TITLE
¿Colocar opción de nueva partida en Ventana post-ronda?

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#483]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! El ítem **3.9 Fin del juego** señala que en la Ventana post-ronda "el jugador tendrá la opción de volver a la Ventana de inicio para comenzar una nueva partida". Sin embargo, el ítem **4.2.5 Ventana post-ronda** no muestra esta opción. De acuerdo a las imágenes, si el jugador pierde tiene habilitado solamente el botón _Salir_ (cuya función es salir del juego).

¿Debemos agregar esta funcionalidad en la tarea?
Saludos!

**Comment by tqmbanados** [comment]
Hola @jamigone! Es cierto que no queda tan claro desde el enunciado. En general, te recomiendo atenerte sólo a lo escrito y tomar las imágenes como sugerencias. Creo que lo mas sano es por el momento atenerte a la indicación del flujo del programa, pues en general es bueno poder volver a la ventana de inicio en cualquier aplicación. Sin embargo, conversaré con les otres encargades y te confirmo. Gracias por hacerlo notar!

**Comment by jamigone** [comment]
Gracias por la pronta respuesta @tqmbanados!
