### ISSUE TITLE
Bonus: daño de una DCCriatura

### ISSUE THREAD

**Issue by milosoria** [IIC2233/syllabus#484]
Hola! tengo una duda sobre el daño que puede hacer cada criatura, resulta que con las fórmulas dadas en el enunciado muchas criaturas ejercerían daño no entero (float), es esto intencionado o es un error?

**Comment by lily416** [comment]
Fíjate que al calcular el daño en todas las fórmulas se utiliza `[ ]`:
![image](https://user-images.githubusercontent.com/26393515/79286330-41a4da00-7e8e-11ea-9ab5-ba1f3a24c622.png)
Esta es una forma de representar la [función parte entera](https://es.wikipedia.org/wiki/Funciones_de_parte_entera#Función_truncamiento), por lo el daño sólo tomará valores positivos.

Saludos y éxito en la tarea 👋🏰
