### ISSUE TITLE
Puntaje Tareas

### ISSUE THREAD

**Issue by Valind4** [IIC2233/Syllabus#484]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Contenido

[Agrega aquí lo que quieras aportar o preguntar]

Holi, la calificación en canvas tiene el punto base sumado o no? porque salen las notas de forma x/6, pero no estoy segura si hay que sumarlo o no.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by jtvvtj** [comment]
holi no soy ayudante, pero la nota oficial la puedes ver en el feedback también. Pero sí, según yo lo de X/6, el X es la nota de obtenida, pero no estoy seguro. De todos modos, como decía. la nota oficial está en el feedback, sin lo del X/6 !! :)

**Comment by Dvckhv** [comment]
Hola! Tal como mencionan, la nota en canvas incluye el punto base, puedes revisar la nota en el excel publico.
Saludos!
