### ISSUE TITLE
Importar desde un path superior

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#484]
Hola trate de importar desde la carpeta cliente las funciones de get_pixels.py pero no logre hacerlo, como se hace correctamente?

**Comment by jeschuwirth** [comment]
Saludos!

Para este problema te recomiendo dos soluciones
- mover get_pixels.py a la carpeta de servidor e importarlo normalmente, ya que es este el que trabaja con la matriz

- si quieres tener el archivo get_pixels.py fuera de la carpeta cliente y fuera de servidor servidor, te recomiendo utilizar la librería sys, en el siguiente link dan un buen ejemplo que de seguro te sirve: https://stackoverflow.com/questions/24868733/how-to-access-a-module-from-outside-your-file-folder-in-python

Suerte en la tarea !

**Comment by quememo** [comment]
> * mover get_pixels.py a la carpeta de servidor e importarlo normalmente, ya que es este el que trabaja con la matriz

Si hiciera eso, el archivo pixel_collector.py _(get_pixels es una función de este)_ solicita la ruta del archivo, por lo que en verdad es algo que utilizaría dentro de la carpeta cliente no es así? Ya que es lógico que el servidor podría encontrarse en otro computador por lo que no tiene sentido que este lea una ruta de un cliente cualquiera

**Comment by jeschuwirth** [comment]
@quememo, creo que tu duda va más a lo que dice la issue #579 que esta, si te quedan dudas coméntalas en esa issue.

Suerte!
