### ISSUE TITLE
descuentos

### ISSUE THREAD

**Issue by eliasbruchfeld** [IIC2233/syllabus#484]
Hola! no habia leido en el enunciado que la competencia tenia que tener un metodo para calcular la moral de cada delegacion, pero tengo que la delegacion tiene un metodo para calcularse la moral a si misma. ¿Eso traería algun descuento?

**Comment by vsantelicest** [comment]
Hola **@eliasbruchfeld**!
Al tratarse de un método especificado tanto en el enunciado como en la distribución de puntajes, si sería necesario que el cálculo de moral estuviera principalmente a cargo de la competencia, aunque podría apoyarse en otros métodos creados por ti que se encontraran a cargo de cada delegación.
Suerte! 🏆
