### ISSUE TITLE
uso de split() en fecha de nacimiento

### ISSUE THREAD

**Issue by Jpdelaf** [IIC2233/Syllabus#484]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Quería saber si es legal que use Split para separar mi fecha de nacimiento en mes y año a partir de Split("/"), note al programar que no me tiraba como prohibido el hacerlo con el test pero me salto la duda de si estaría permitido usarlo en solo esto.

**Comment by Segismundios** [comment]
Hola @Jpdelaf, si lo estás usando dentro de una función generadora o reduce debería estar bien. De todas formas, considera que si al probarlo con el test no te arroja error, entonces deberías estar a salvo 😄

**Comment by Jpdelaf** [comment]
hay uno que tengo que es para guardar los datos del nacimiento donde primero cree un generador con next y sobre la fecha de este estoy haciendo el split, pero este ultimo lo hago no dentro del mismo generador sino que en una linea a continuación después de revisar que exista. no se si se entiende, es legal?

**Comment by Segismundios** [comment]
No te preocupes, puedes guiarte por los tests, si no te arroja ningún error de prohibición, entonces puedes confiar en que no tendrás problemas con la corrección.
