### ISSUE TITLE
Diferentes ventanas en QtDesigner y VS

### ISSUE THREAD

**Issue by martinletelier** [IIC2233/syllabus#484]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, tengo un problema al ejecutar un código en el VS ya que me muestra una MainWindow con diferente formato que en el Qt designer. 
**MainWindow en Qt Designer:**
![image](https://user-images.githubusercontent.com/80777883/119273228-e6d4ca80-bbd7-11eb-8707-26c3900f9d1e.png)
**MainWIndow en el VS:**
![image](https://user-images.githubusercontent.com/80777883/119273261-0d930100-bbd8-11eb-9c76-92adf1436b89.png)

Ya intente escalar la ventana y comparar las ventanas con otros ejercicios de los propuestos y no se porque me sale diferente.

**Comment by pabloist** [comment]
Hola buenas!

En primeras es difícil saber porque podrías tener problemas de escala con las ventanas de qtdesigner sin ver el código, dado que podría deberse a la utilización de layouts, a la definición de escalas incorrectas o incluso a interpretaciones propias del sistema operativo. Debido a lo anterior te voy a pedir que subas tu desarrollo a tu repo a modo de poder revisarlo :) (favor dejar link al repo en un comentario).

Saludos!

**Comment by jamigone** [comment]
Holaa! A mí me pasa lo mismo y es debido a la alta resolución de mi pantalla. Para que no fuese un problema busqué en google y encontré este código reescala la ventana al tamaño "normal". Planeo borrarlo antes de entregar la versión final de mi tarea eso si, es solo para comodidad por mientras :)

https://stackoverflow.com/questions/43904594/pyqt-adjusting-for-different-screen-resolution

![imagen](https://user-images.githubusercontent.com/50121013/119417710-735cb700-bcc4-11eb-93e4-a36b491f4469.png)
