### ISSUE TITLE
Sobre la cantidad de alumnos que no almuerzan

### ISSUE THREAD

**Issue by HenryBlairG** [IIC2233/Syllabus#484]
Una consulta de comprensión lectora mía: Cuando piden que calculemos 
> Cantidad de alumnos que no almorzaron por mes. 

Esto se refiere a la cantidad de ocasiones donde los alumnos no almuerzan o a la cantidad de alumnos que en alguna ocasión del mes no almorzaron? Mi pregunta viene de que de ser la primera alternativa, el mismo alumno puede ser contado más de una vez si no almuerza en más de una ocasión, mientras que en el segundo caso sólo se contaría una vez al alumno si deja de almorzar una o más veces. 
Desde ya gracias 😄 😃

**Comment by Arcoirisky** [comment]
Tu primera opción O: Ya que cada día es distinto y pueden pasar muchas cosas entre medio que mueva los números.
