### ISSUE TITLE
Imagenes Inventario

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2233/syllabus#484]
Hola tengo una duda..

`class Inventario(QWidget):

    senal_actualizar_inventario = pyqtSignal(list)

    def __init__(self,  ruta_mapa, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.senal_actualizar_inventario.connect(self.plasmar_inventario)
        self.ruta_mapa = ruta_mapa
        self.hoja_presente = 1
        self.hojas = []
        self.init_gui()

    def init_gui(self):

        # aqui ya esta definida la ventana y botones 

        if len(self.hojas) != 0:

            i = 1

            vbox_inv = QVBoxLayout()
            hbox_inv = QHBoxLayout()
            
            for articulo in self.hojas[self.hoja_presente - 1]:

                self.articulo = QLabel(self)
                pixeles = QPixmap(PATH_INICIO)
                self.articulo.setPixmap(pixeles)
                self.articulo.setScaledContents(True)

                hbox_inv.addWidget(self.articulo)

                if (i % 2) == 0:
                    vbox_inv.addLayout(hbox_inv)
                    hbox_inv = QHBoxLayout()

       """ vbox_bot = QVBoxLayout()
        vbox_bot.addStretch(1)
        vbox_bot.addWidget(self.anterior)
        vbox_bot.addWidget(self.siguiente)"""

        self.setLayout(vbox_inv)

        self.anterior.clicked.connect(self.anterior_hoja)
        self.siguiente.clicked.connect(self.siguiente_hoja)

        self.show()

    def plasmar_inventario(self, hojas):

        self.hojas = hojas
        self.init_gui()`

self.hojas : es una lista de listas de 8 path para imagenes o menos

el codigo me tira el siguiente error:

"UnboundLocalError: local variable 'vbox_inv' referenced before assignment"

llevo rato buscando el error y no lo encuentro, alguna idea de que esta mal ??.

de antemanos muchas gracias. :(

**Comment by DiegoPibe** [comment]
los vbox_bot que estan entre comillas, son de los botones pero no los inclui para vez si me muestra las imagenes, y no funciono.

la idea del codigo es recibir de la lista las imagenes de cierta pagina del inventario (self.pagina_presente) y mostrar las imagenes como una matriz de 2 x 4.

**Comment by gatochico** [comment]
Hola!

Leyendo tu código, pareciera que defines vbox_inv dentro de un condicional ( `if len(self.hojas) != 0`), pero luego haces el llamado `self.setLayout(vbox_inv)` fuera de dicho condicional. ¿Qué pasa con el caso donde no se entra al if, y por ende no se define la variable vbox_inv? Ya que despues llamarias una función que la tiene como parámetro, pero no estaría definida todavía. ¿Será eso la causa del error?

Cualquier duda nos avisas!

**Comment by DiegoPibe** [comment]
toda la razon, saque el `vbox_inv` del condicional y me dejo de arrojar ese error, pero sigue sin mostrarme las imagenes en la ventana :(

**Comment by gatochico** [comment]
Hola, ¿Podrías subir tu codigo a tu repositorio privado, e indicar en que parte de este está el codigo que mencionas? Así le echamos un ojo a ver si encontramos el error!

**Comment by DiegoPibe** [comment]
okaaa lo hago de inmediato y aviso
