### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#484]
Hola!
No aparece en el enunciado, pero me preguntaba si el archivo .json y los archivos vocabulary.txt y words.csv también es necesario agregarlos en el .gitignore (sólo se menciona la gui y los csv de la base de datos)

**Comment by Hernan4444** [comment]
@santilaguna si no se mencionan, queda a tu criterio.  Solo revisaremos que esté el .gitignore y no esté la gui y los csv.

Saludos ✌️

**Comment by santilaguna** [comment]
@Hernan4444 con los csv incluye a words o sólo los de database?
