### ISSUE TITLE
Nivel de programación en examen

### ISSUE THREAD

**Issue by josemlira** [IIC2233/Syllabus#485]
Hola!
El progreso por pregunta del examen dependerá del manejo del contenido de la pregunta, de la confianza del alumno y también del nivel de programación, mi pregunta es si este nivel de programación es el nivel de programación final del alumno o es el nivel que tuvo este en el contenido de la pregunta? 
Saludos!

**Comment by nivek0o0** [comment]
Me parece haber entendido del enunciado que el Nivel de Programación de algún alumno es solo un número que aumenta o disminuye a medida que pasan las semanas. Por lo tanto para calcular el progreso en las preguntas del examen habría que tomar el nivel de programación del alumno al momento de rendirlo, que sería el mismo en todas las preguntas.

**Comment by josemlira** [comment]
Yo también pensaba que era así, pero en la sección 7.2 de estadísticas personales dice que se debe mostrar el nivel de programación promedio por persona, entonces me saltó la duda.

**Comment by iqacevedo** [comment]
Hola ! 

@josemlira es tal como dice tu compañero @nivek0o0, debes considerar el nivel de programación que tiene el alumno al momento de rendir el examen y será igual para todas las preguntas. 

Saludos !

**Comment by josemlira** [comment]
Gracias!.
Entonces cuando nos piden el nivel de programación promedio por persona hay que mostrar el nivel de programación que tiene el alumno al final?

**Comment by iqacevedo** [comment]
No, tienen que mostrar el promedio, por ejemplo, puedes sumar  el nivel de programación que tiene cada día y después dividirlo en el total de días que tuvo la simulación ( o semanas tú decides) para obtener el promedio que se muestra en las estadísticas.

Saludos !

**Comment by josemlira** [comment]
Muchas gracias!
