### ISSUE TITLE
Duda mala practica: métodos que usan instancias como parámetros

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#485]
Hola, 
queria saber si lo siguiente era una mala practica:
teniendo dos clases , A y B:
Tener un metodo de la clase A que necesita una instancia de la clase B en los parametros.
y dentro de este metodo se ejecuta un metodo de la clase B que entre sus parametros 
necesite una instancia de la clase A.

ejemplo:
```python
    class A:
        :
        def metodo(self , instancia_de_clase_b):
            :
            instancia_de_clase_b.metodo2( self )
            :
        :
```
Pd: los dos puntos (  :  ) es para indicar que hay mas codigo entre medio.

**Comment by fdoflorenzano** [comment]
Hola @Ignacioislae,

A primera impresión, no, no es mala práctica, es bastante válido.

¡Éxito en la tarea! 
Saludos.

PD: te mencionó edité el código en tu pregunta para que se viera en formato apropiado. Puedes revisar como referencia [esto](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) para escribir en formato código aquí o en tus README.

**Comment by Ignacioislae** [comment]
Yaa Gracias!
