### ISSUE TITLE
Duda sobre retorno iterable

### ISSUE THREAD

**Issue by Valind4** [IIC2233/Syllabus#485]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Holi, en las funciones que dice que retornemos un iterable, nosotros elegimos que tipo de iterable? o sea como lista etc o cómo
[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mane6867** [comment]
¡Hola!

En las funciones que indican que deben retornar un iterable, efectivamente, puedes elegir el tipo de iterable que consideres más adecuado para el contexto.
