### ISSUE TITLE
Incluir imágenes directamente en QT designer

### ISSUE THREAD

**Issue by imuoz** [IIC2233/syllabus#485]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Al trabajar en QT designer podemos incluir directamente el archivo que se va a mostrar en el label, si los escogemos de esta manera no entiendo bien como funcionan los paths, es decir, **es un path relativo, absoluto? va a funcionar en otro computador?**

**Comment by JadrinaDA** [comment]
Hola! En este caso los paths son relativos, si miras en tus archivos .ui puedes ver una línea como esta "<pixmap>sprites/Logo_2.png</pixmap>". Va a funcionar en otro computador si este tiene la imagen con el mismo path relativo. Al corregir tu tarea vamos a siempre tener todos los assets en esa carpeta así que si el path es "assets/pic.png" va a estar bien. Si usas una imagen diferente a las entregadas debes subirla y decirnos donde ponerla. Espero haber respondido tu duda.
Saludos.

**Comment by imuoz** [comment]
mmmm ok, si cambio la distribución de las carpetas, tipo creo la carpeta frontend y meto todo ahí, incluida una imagen nueva, debo 1.- subir la imagen, 2.- especificar el orden de las carpetas en el readme junto a cual es la imagen nueva y con eso estoy cierto?

**Comment by JadrinaDA** [comment]
Sí! Con eso quien corrija tu tarea sabrá donde ponerlo y funcionará bien.

**Comment by raibd** [comment]
Hola, me surgió una duda relacionada con esto. Si tengo mi carpeta _sprites_ dentro de una carpeta _frontend_, es preferible sacarla de ahí y devolverla a la carpeta _T2_ donde estaba antes para evitar cualquier confusión?

**Comment by JadrinaDA** [comment]
Hola! Está bien que la carpeta _sprites_ esté dentro de _frontend_ ya que solo los códigos de esa carpeta deberían estar usando los sprites. Para tu seguridad lo incluiría en el README para garantizar que el o la ayudante ponga la carpeta en el lugar correcto. 
Saludos.
