### ISSUE TITLE
Combinaciones de teclas

### ISSUE THREAD

**Issue by kadroguett** [IIC2233/syllabus#485]
Hola, según lo respondido en la issue #455 en este item las teclas se deberían apretar en secuencia y no en simultaneo, pero como en el enunciado decía "todas al mismo tiempo" lo implementé de esa forma y en mi teclado funciona bien. Debería cambiarlo a como se dijo en la issue anterior o puedo dejarlo como lo tengo? 
![combinaciones](https://user-images.githubusercontent.com/31357861/66680720-86358b80-ec47-11e9-9408-8d6f64a2bcc9.jpg)

**Comment by lily416** [comment]
Gracias por avisar. Ya se mandó un aviso explicando la situación.
 
Saludos y éxito en tu tarea 😄👨‍🌾🌾

**Comment by kadroguett** [comment]
Muchas gracias 🤭
