### ISSUE TITLE
Consultas por Zoom

### ISSUE THREAD

**Issue by nimorales97** [IIC2233/syllabus#485]
Hola, necesito saber si hay algún ayudante que tenga disponibilidad para mañana viernes 11/09 para poder hacer un zoom. Resulta que necesito hacer varias consultas respecto a la materia, pero mi pc no aguanta discord por lo que me ha sido súper difícil ver problemas con ayudantes hasta ahora porque no puedo compartir pantalla.
Puedo en cualquier horario y en verdad si pudiera ser más de uno para no quitarle mucho tiempo a un puro ayudante sería bacán. De antemano muchas gracias.

**Comment by amahns1** [comment]
* No soy ayudante *
Hola!

Aprovecho de darte un consejo con respecto a discord. A mi también me corre súper lento, pero si lo abro en chrome funciona mucho mejor.

Ojalá te sirva :)

**Comment by nimorales97** [comment]
Lo probaré, algo es algo. Muchas gracias:)

**Comment by tomasgv** [comment]
¡Hola @nimorales97!

Lo que pides es un poco difícil pues requiere de uno o más ayudantes voluntarios a atenderte personalmente por zoom.

Por mi parte, puedes contactarme al correo de Bienestar (bienestar.iic2233@ing.puc.cl) y podemos ver la posibilidad de agendar Sesiones de Repaso junto a otres estudiantes 🙌  . Si es un problema muy urgente también podemos discutirlo particularmente.

Recuerda que si tienes dudas con materia puedes usar este mismo medio para preguntarlas! Incluso si tienes algún problema con tu código puedes hacer _push_ a tu repositorio y pedir asistencia.

Saludos!
