### ISSUE TITLE
duda descuentos pedido 

### ISSUE THREAD

**Issue by vhernnda** [IIC2233/Syllabus#486]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

respecto a los contenidos de un pedido, todas las tuplas con la misma id_pedido tambien comparten el mismo valor para el descuento?

**Comment by FradexMF** [comment]
Hola!
Asi es, el descuento es por pedido, por lo que todas las instancias de contenido_pedido que comparten el mismo ID, también comparten el valor de descuento.

**Comment by vhernnda** [comment]
duda resuelta
