### ISSUE TITLE
Cantidad de productos revisados por Carabineros

### ISSUE THREAD

**Issue by MarceloSaldias** [IIC2233/Syllabus#486]
Si un **Vendedor** tiene un stock de 44 productos, y el **Carabinero** (en alguna de sus personalidades) tiene como *tasa_de_productos_a_revisar* = 0.1 , entonces se deberian revisar 4.4 productos escogidos al azar.  Cierto?
En los casos en que da una cantidad decimal de productos, debemos aproximarlo al entero mas cercano?
(En el caso anterior quedaria en 4 productos, y si fueran 4.5 productos, quedaria en 5)

**Comment by fdominguezclaro** [comment]
Hola! 
Aproxima para abajo. De todas maneras déjalo especificado en tu readme.
Saludos!!
