### ISSUE TITLE
Mostrar estado DCC

### ISSUE THREAD

**Issue by Mario-uc** [IIC2233/syllabus#486]
En esta función , cuando se imprimen los alimentos, dice que se imprime tipo y efecto salud, ¿el tipo se refiere a su nombre o si es "barato", "medicinal" o "Tranquilizante"?

**Comment by JosefaPaz** [comment]
¡ Hola @Mario-uc !

Cuando habla de imprimir el tipo de alimento, se refiere a su nombre 😸
