### ISSUE TITLE
Detener/Destruir un Thread

### ISSUE THREAD

**Issue by josejimenezp** [IIC2233/syllabus#486]
Hola, quería saber cómo puedo hacer que un thread se detenga, o en su defecto destruirlo, de un momento a otro. Gracias!

**Comment by KnowYourselves** [comment]
Hola @josejimenezp!

Destruir un _thread_ de un momento a otro es **mala práctica** en los lenguajes de programación en general, por lo cual **no hay ninguna forma fácil de hacerlo**. Esto se debe a que un _thread_ en un momento dado puede tener acceso a un recurso valioso que debe ser cerrado bien (si no todo explota), o porque generó más _threads_ y habría que destruirlos también.

En vez de detenerlo o destruirlo abruptamente, uno usualmente hace el siguiente patrón (asumiendo que estés en el contexto de una clase):

```python3
...
def run(self):
     while self.sigo_funcionando:
         ...
```

De esta manera, cuando quieras detener el thread desde algún otro método de la clase, simplemente puedes cambiar el valor de `self.sigo_funcionando` a `False`, de esta manera te ahorras los problemas descritos previamente.

Espero haberte ayudado!

**Comment by josejimenezp** [comment]
Pero y cómo lo hago para que empiece? Porque si lo pongo en un while me dice que sólo puede hacer start una vez :(

**Comment by KnowYourselves** [comment]
Cuando empiezas tu _thread_ el valor del cual depende el _run_ lo inicializas en `True`, luego cuando hagas `start` el proceso se realizará constantemente hasta que el valor cambie a `False`.
