### ISSUE TITLE
Promedios del ramo

### ISSUE THREAD

**Issue by TomasSalvadores** [IIC2233/Syllabus#486]
Hola, tengo una duda sobre como calcular el promedio del ramo en distintas situaciones.

1. En el enunciado dice:
![captura de pantalla 2017-05-13 a la s 20 04 58](https://cloud.githubusercontent.com/assets/24449539/26029916/076db2f4-3818-11e7-9875-1103e05d4b27.png)
Pero esto significaría que en todos los meses la mitad de la suma ponderada es 1.0 menos en el mes del examen, lo que a priori causaría que siempre el mes con mas aprobación sea el mes del examen. Esto hace que se pierda un poco el sentido de esta estadística. Además, no toma en cuenta los controles, haciéndola aun menos representativa de la simulación.
Podemos modificar esta formula?

2. Creamos nuestras propias ponderaciones para calcular el promedio del ramo a lo largo del semestre (y determinar si los alumnos van a la oficina y/o botan el ramo), o usamos la formula anteriormente expuesta?

3. Para el calculo de la nota final usamos las ponderaciones del curso dictado en nuestra dimensión, o las de la formula del punto 1?

Saludos!

**Comment by FernandoPieressa** [comment]
Hola!

1) Pueden editarla si lo encuentran conveniente, mientras lo especifiquen en el readme

2) A criterio suyo

3) Nuevamente a criterio suyo

Saludos!
