### ISSUE TITLE
Inconsistencia en los sprites

### ISSUE THREAD

**Issue by v4rgas** [IIC2233/syllabus#486]
Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

[ X] Leí las reglas del foro (#1)
[ X] Busqué en las issues si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
[ X] Revisé el compilado de dudas de la tarea y no encontré una issue similar a la mía (#474)
[X ] Mi duda no se trata sobre una librería, built-in o mala práctica, ya que eso se pregunta en la issue creada para ello.
[ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
[ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
[ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia
Duda:

Estaba haciendo la tarea y encontre una inconsistencia en los sprites

Todos tienen los brazos cruzados (imagen para cuando estan quietos) en down_1 excepto homero que la tiene en down_3

Es un error?

**Comment by Tsbalart** [comment]
Hola @v4rgas! Efectivamente es un error, sin embargo no debiese afectar el flujo de tu movimiento, ya que solo se utilizan para la secuencia de movimientos.
Exito con la tarea!

**Comment by v4rgas** [comment]
yaaaa entiendo! entonces todos los personajes cruzan los brazos cuando estan caminando hacia abajo? pense que la caminata hacia abajo eran solos down_2 y down_3 por que el otro da la impresion de que se queda quieto. Muchas gracias por la ayuda

**Comment by Tsbalart** [comment]
Claro, es para aumentar el flujo de movimiento, de todas formas es algo que puedes especificar en tu readme, si decides usarlas de otra forma. Saludos!
