### ISSUE TITLE
Error de "inexistencia" de señal

### ISSUE THREAD

**Issue by bgonzlez** [IIC2233/syllabus#486]
Hola, hace unos días tengo este error, he buscado en varias partes pero no sé cómo arreglarlo:

![Captura de pantalla 2019-10-11 a la(s) 17 02 12](https://user-images.githubusercontent.com/53842152/66681975-3c9a7000-ec4a-11e9-9889-5c8cefa429d5.png)

**Comment by aljara97** [comment]
Hola @bgonzlez, podrías subir tu código a tu repositorio para ayudarte a detectar el problema de tu tarea?

**Comment by bgonzlez** [comment]
Hola!! oka, la acabo de subir, ahora cambié esa parte sin embargo sigue existiendo este problema con otra señal cuando cierro el programa. Gracias!!

**Comment by aljara97** [comment]
Estuve intentando correr el archivo ```main.py``` de tu código y me arroja el siguiente error: ```NameError: name 'caracter' is not defined```. Luego de revisar un poco en los archivos ```main.py```, ```caracter.py``` y ```caracter_2.py``` llegué a la conclusión de que quieres conectar las señales del personaje con la ventana de juego, sin embargo no importas el módulo correspondiente al personaje ni lo instancias en el main, es decir, no escribes ```caracter = Caracter()```.

Cuidado con los nombres de las señales que tienes en esta clase, ya que ninguno de estos es ```actualizar_caracter```. Espero haberte ayudado, de no ser así cuéntame más detalles y trataré de responderte a la brevedad, mucho éxito con lo que queda de tu tarea 🌱

**Comment by bgonzlez** [comment]
sii lo siento!! el que hay que correr es ventana inicio, error mío :( Gracias por todo!!

**Comment by aljara97** [comment]
No te preocupes, podrías contarme cuál es la señal con la que te arroja el error, o comentar el error textual que arroja tu programa?

**Comment by bgonzlez** [comment]
Este es el error, es igual al otro :( 
![Captura de pantalla 2019-10-12 a la(s) 14 30 00](https://user-images.githubusercontent.com/53842152/66705426-cdca1f00-ecfc-11e9-8dcb-4201447545b5.png)

**Comment by aljara97** [comment]
Estuve revisando el archivo ```caracter_2.py``` y en la línea 120 conectas la señal  ```senal_barra_energia``` a un método del parámetro ```madre```, por eso al querer emitirla en la función ```energía_barra``` tu programa tiene un error, ya que esa señal no está disponible para ser emitida. Te aconsejo usar dos señales distintas para estos propósitos, éxito con tu tarea 🌱

**Comment by bgonzlez** [comment]
ahhh entiendo, crear una en cada clase y luego igualarlas? Gracias :)

**Comment by aljara97** [comment]
De nada, ten cuidado que las señales tengan un nombre diferente 👀
