### ISSUE TITLE
Sprites y canciones personalizadas

### ISSUE THREAD

**Issue by Jpobletel** [IIC2233/syllabus#487]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! tenia la duda de si podemos usar sprites y canciones personalizadas en la tarea, ya que el enunciado dice que hay que usar un .gitignore con estas carpetas. Obviamente no es necesario pero encuentro que podria hacer mucho mas divertida la tarea con esto.
En caso de que se pueda, como las subo?
Muchas gracias de antemano

**Comment by clementevalladares** [comment]
Hola @Jpobletel, si pueden usar sprites y canciones personalizadas. Como bien dices, no puedes subir las carpetas que ya les entregamos. Por lo tanto, puedes crear una nueva carpeta que incluya todos los archivos adicionales que deseas agregar, y esta sí subirla a tu repositorio.
