### ISSUE TITLE
Problema GIT ADD

### ISSUE THREAD

**Issue by pwillmer** [IIC2233/syllabus#487]
Hola! por error realicé add a una carpeta que no quería subir. Aún no hago git push, como puedo sacarlo?

**Comment by gatochico** [comment]
Hola! 

En [este link](https://stackoverflow.com/questions/348170/how-do-i-undo-git-add-before-commit) se habla de tu problema. En resumen deberías correr en la consola:
`git reset <nombre_de_archivo>` si deseas sacar solo un archivo de la lista de archivos que se subirán.
`git reset` para reiniciar la lista de archivos que se subirán. 

Lamentamos la demora :crying_cat_face: . Éxito!

**Comment by pwillmer** [comment]
Gracias!
