### ISSUE TITLE
socket connect 

### ISSUE THREAD

**Issue by jerrymendoza** [IIC2233/syllabus#487]
Hola, 
Estoy intentando que no muera el cliente cuando el servidor no esta iniciado, me funciona todo bien si el servidor esta corriendo antes, pero si abro el servidor después de intentar una conexión, ya no deja 'ingresar'...

algo así:
#con servidor encendido, desde el cliente `self.sock.connect((server_host, server_port))`
Todo OK, y la comunicación continua

#con servidor apagado
Paso 1) intento conectarme desde el cliente, 
`self.sock.connect((server_host, server_port))`
error: 
`ConnectionRefusedError`

Paso 2) enciendo el servidor, intento desde el cliente 
`self.sock.connect((server_host, server_port))`
error:
`OSError: [Errno 22] Invalid argument`

alguna idea de que podría ser el problema? quizás como el socket ya rechazo la conexión espera otra cosa?
no se ni como buscar el error 

Gracias! y disculpen si es muy tonto esto..

**Comment by jeschuwirth** [comment]
Saludos!
Antes que nada, ningún error es muy tonto, te aseguro que van a llegar a otros alumnos a esta issue preguntándose lo mismo.

Si un cliente intenta ingresar al servidor y no hay servidor corriendo, entonces levanta el error ConnectionRefusedError como tu mencionas y no se puede conectar de nuevo, sino que se debe cerrar la consola y correr el programa de nuevo. En otras palabras, siempre se debe abrir el servidor antes que el cliente.

En esta tarea hay un bonus (s 10.5) Servidor y Cliente Robusto, para tener este bonus se deben considerar casos como el que tu mencionas. 

Por lo tanto si no haces el bonus puedes asumir que al momento de corregir nunca se va a abrir un cliente si no esta abierto antes el servidor.

Suerte en la tarea 😄
