### ISSUE TITLE
Crear una lista vacía dentro de una función generadora

### ISSUE THREAD

**Issue by FranVvi** [IIC2233/Syllabus#487]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Se puede hacer una función generadora en la que pueda comenzar con una lista vacía?  Se que la creación de listas, tuplas, sets es por medio de reduce pero no estoy segura si lo puedo hacer por medio de funciones generadoras, ya que en el ejemplo de "cosas permitidas" aparece la creación de un set por medio de datos entregados por la función. 

def funcion_generadora():
        lista = []
        ....
        
y si se puede hacer lo mismo con set, tuplas, diccionarios inclusive con float, str e int?

**Comment by ignacio-sp** [comment]
Hola @FranVvi lo que dices de crear una lista vacía si está permitido **dentro** de una función generadora como aparece en la [issue de cosas permitidas](https://github.com/IIC2233/Syllabus/issues/339#issue-2303846794), el mismo ejemplo con un set se puede hacer con una lista. Igualmente recomiendo hacer uso del script de elementos prohibidos (el archivo de extensión `.pyc` ) si este arroja true no hay problemas con tu función, si arroja false puede que no estés haciendo uso correcto de la lista. Espero haber ayudado!
