### ISSUE TITLE
Cuando llega un funcionario a la fila...

### ISSUE THREAD

**Issue by estebanmb** [IIC2233/Syllabus#487]
Si inicialmente hay X alumnos en la fila y el stock es X. Cuando llega un funcionario, ¿el último alumno se va automáticamente?. 
Lo mismo con la paciencia si al llegar funcionarios ¿ los alumnos en fila deben volver a estimar el tiempo de espera e irse si excede su límite?

**Comment by cilopez** [comment]
Estas en lo correcto en ambas situaciones! :+1:

**Comment by ptflores1** [comment]
@cilopez Hola! Que pasa si por ejemplo tenemos una cola asi: Vendedor - A1-F1-A2-A3 (el vendedor no esta en la cola pero es para indicar como avanza la cola) donde A son alumnos y F funcionarios , A1 esta siendo atendido y acaba de llegar F1, producto de su llegada A2 y A3 deciden irse porque se sobrepasa el limite de paciencia. La pregunta es: Se van ambos? porque podria pasar que se fuera A2 y como se reduce el tiempo estimado de espera, A3 decide no irse. Actualizo la cola desde izquierda a derecha (en este caso) o simplemente se van los dos?(No estoy seguro de que pueda pasar un caso asi :sweat_smile:)
Gracias !

**Comment by iqacevedo** [comment]
Hola,
@ptflores1 creo que te entendí tu duda, en ese caso es mejor que revises en ese momento cuales se van de la fila, y que efectivamente se vallan. Si consideraste que se vayan primero aquellos que tienen menor paciencia, y vas actualizando la espera para cada uno, también estaría bien (te recomiendo la primera porque es más sencilla).

De todas maneras no olvides especificar como decidiste resolver este tipo de situaciones en tu README.

saludos !

**Comment by B-Dominguez** [comment]
Cuando el tiempo de espera aumenta, los alumnos son inteligentes y consideran el tiempo ya esperado como costo hundido? O son muy temperamentales y consideran el tiempo total?

Es decir, para comparar con el limite de paciencia se evalúa el tiempo de espera que le queda o el total?

Graciaas!
