### ISSUE TITLE
Como usar .gitignore para ignorar carpetas externas

### ISSUE THREAD

**Issue by ExRage2000** [IIC2233/syllabus#488]
Hola, tengo un problema al hacer los commits: cada vez que hago un commit me aparecen archivos de otras carpetas a los que simplemente ignoré en su tiempo, intenté usar .gitignore pero solo se usarlo para ignorar archivos de la misma carpeta en la que está, no me resulta con archivos que estén fuera.

![Captura de pantalla (47)](https://user-images.githubusercontent.com/69613733/92805595-a1e16e80-f38f-11ea-8618-961bfdadfca1.png)

Actualmente estoy teniendo que añadir los archivos uno a uno al hacer los commits

**Comment by vicentevegaulloa** [comment]
Hola @ExRage2000 !

Las lineas en rojo son archivos o cambios a los que no se le está haciendo seguimiento. En otras palabras, son archivos o cambios que no se están considerando a la hora de hacer commit. Si deseas añadir de manera rápida e ignorando todos los `__pycache__` por ejemplo, debes incluir esta línea: `**/__pycache__`  en un .gitignore que esté en la carpeta inicial de tu repo. Si te equivocas y subes cosas por accidente, puedes usar el comando `git rm --cached nombre_de_archivo.extension` y luego añadirlo correctamente al gitignore. Si quieres revisar más sobre gitignore en la issue #219 se recomiendan varios links útiles para entender la sintaxis adecuada de un gitignore 😄

**Comment by ExRage2000** [comment]
Intenté añadir las carpetas con esa notación pero todavía las toma en cuenta el git 

![Captura de pantalla (48)](https://user-images.githubusercontent.com/69613733/92822524-a2373500-f3a2-11ea-8528-e053ac1140f3.png)
¿no hay alguna notación especial lo que esté fuera de la carpeta de origen?

**Comment by aaossa** [comment]
@ExRage2000 lo que ocurre es que el .gitignore utiliza la ruta desde donde está ubicado ese archivo. Por lo tanto, te recomendaría utilizar el comando `git status` desde donde tienes el archivo .gitignore, y colocar esas rutas. Por ejemplo, si tienes algo así:

```
Actividades/
Tareas/
- T01/
- - .gitignore
- - carpeta/
```

Para ignorar `carpeta` desde el .gitignore solo tienes que colocar `carpeta/` en el archivo, y así se ignorarán sus contenidos. En resumen, utiliza `git status` desde donde está el .gitignore y coloca esas rutas (no debería quedarte ninguna con `..`). Espero se entienda, pero si no queda claro pregunta por acá no más ✨

**Comment by ExRage2000** [comment]
Creo que no me estoy expresando bien. Se como usar "git status" y se que a los archivos en rojo no les hago seguimiento, el problema no es que quiera subir algo o borrar algo, lo que intento hacer es:
1. ignorar los archivos de carpetas fuera de la carpeta en que estoy trabajando
2. que git me deje de mostrar todos esos archivos que ya no estoy usando cada vez que pongo git status
3. que git los deje de contar cuando pongo git add * porque es bastante latero tener que añadirlos uno por uno cada vez que hago un commit

Por ejemplo, quiero ignorar la carpeta de la tarea 0 (porque me molesta y ahora estoy trabajando en la T01):
![Captura de pantalla (50)](https://user-images.githubusercontent.com/69613733/93290015-21b77080-f7b6-11ea-9221-e786b9333fc1.png)
He intentado todas las notaciones (en el .gitignore) que he visto para ignorar la carpeta T00 desde la T01, no puedo borrarla de github porque puede que aún la estén evaluando, y no puedo hacer un nuevo gitignore en la carpeta T00 porque git me va a pedir que la suba (que le haga un commit y un push) y ya no se pueden subir mas cosas a ese repositorio.

Espero que se me entienda mejor

PD: @aaossa creo que viste que probé anotando el " - /T00/ "  en el .gitignore pero no me resultó, gracias igualmente

**Comment by vicentevegaulloa** [comment]
@ExRage2000 mil disculpas por no responder, se me fué absolutamente la notificación 😢 Respecto a esto último que dices, la T00 no la puedes ignorar desde la T01 si esta ya está en tu repo. El .gitignore te ayuda a ignorar cosas que no quieres subir desde un principio.

Cuando git te muestra esas carpetas en rojo te está diciendo que no serán añadidas a tu próximo commit, por lo tanto te está haciendo exaxctamente lo que buscas. Que aparezcan esas carpetas en rojo no es un error, es solo una advertencia por si es que se te está olvidando esas carpetas, pero como tu estás dejandolas de lado a propósito, no deberías preocuparte. 

Por último, al hacer `git add *` se está añadiendo al commit todo lo que está dentro de la carpeta en a que estás ubicado, por lo que no es necesario preocuparte de archivos fuera de `T01` ya que estos no serán considerados, y puedes ver eso en el mensaje que te dice que las carpetas en rojo no serán consideradas. Ahora, si sabiendo esto quieres que git deje de mostrarte el mensaje de archivos y carpetas sin seguimiento debes usar el comando `git status -uno` o `git commit -uno`. Sin embargo, yo no utilizaría este comando ya que siempre es útil saber que se te está quedando fuera. 

Una vez más lamenta no haberte respondido, se me fué absolutamente la notificación de tu comentario en esta issue 😢  Espero haberte ayudado esta vez.

**Comment by ExRage2000** [comment]
No, está bien, la verdad es que me ayudó bastante, estaba preocupado de que se me subieran todos los archivos de otras carpetas y me quitaba tiempo añadir los módulos uno por uno. Como dijiste que no se iban a incluir los de otras carpetas hice el "git add * " y la misma aplicación git me dió una opción de que se ignoraran las demás carpetas. Aunque claro, como estaba en inglés y no era muy específico en lo que decía no fue muy intuitivo. 
Ahora solo se suben los archivos de mi carpeta y no me aparecen los demás en rojo. Así que gracias
