### ISSUE TITLE
Duda Bonus Emojis

### ISSUE THREAD

**Issue by bpeirano1** [IIC2233/syllabus#488]
Si mi programa manda emojis como un solo mensaje en el chat, es decir, "usuario: emoji", pero no es capaz de mandar emojis dentro de mensajes, es decir, "usuario: Hola emoji", igual se obtienen las décimas del bonus?

**Comment by KnowYourselves** [comment]
Hola @bpeirano1!

No, para obtener el bonus se debe poder ocupar emojis en cualquier lugar del mensaje. 

Saludos!

**Comment by bpeirano1** [comment]
Ok, gracias!
