### ISSUE TITLE
Duda sobre MNY y KIP (Velocidad del computador)

### ISSUE THREAD

**Issue by Alonsinho1** [IIC2233/syllabus#488]
Hola tengo una duda sobre respectos estos comando. Lo que pasa es que yo tengo implementado estas claves apretando las tres claves al mismo timepo. Para esto hice un key press event y un key release event. En el primero ponia las teclas en un set y luego las sacaba cuando se soltaban. Lo que me sucede es que el comando KIP funciona a la perfeccion sin embargo el comando MNY funciona aproximadamente 4/10 veces. No se si esto sucede debido a la velocidad de mi computador, o algo del teclado de mi computador. Hay una forma de agregar un "Tiempo" antes que se suelte la tecla.

PD: Puedo subir el codigo (si es que facilita la ayuda) de como estoy implementando esto, total no superan las 6 lineas.

Muchas gracias

**Comment by camaruri** [comment]
A mi me pasa lo mismo, me funciona perfecto el R+I+P pero el M+N+Y funciona solo a veces

**Comment by agustin-rios** [comment]
A mi me pasa que logro ingresar M+N+Y correctamente de la misma forma, pero a la hora de ingresar K+I+P solo me deja ingresar dos de estas y para que acepte la otra debo soltar una de las que ya apreto. Me preguntaba si puedo cambiar I por Y para que funcione?

**Comment by lily416** [comment]
@Alonsinho1 estuve probando tu código y me funcionan correctamente ambos comandos:
 
- `M+N+Y`: 
   ![image](https://j.gifs.com/JyW72g.gif)

- `K+I+P`: 
   ![image](https://j.gifs.com/Qng529.gif)

 
 
Cuando prueben las combinaciones de teclas traten de mantener apretadas dos de las tres teclas y apretar y soltar rápidamente la tercera que falta.
 
En caso de que les siga fallando, impriman el set en el que guardan las teclas, puede ser que se estén ingresando mal o que suceda algo que no estén esperando.
 
Saludos y éxito con sus tareas 👋👨‍🌾

**Comment by lily416** [comment]
@Alonsinho1 sobre agregar un tiempo para que se activa el efecto de las combinaciones de teclas, puedes hacerlo mientras **el tiempo de que se deben mantener apretadas las teclas sea un parámetro general**.

Si lo implementas debes especificarlo en tu readme y hacer referencia a esta issue.

**Comment by Alonsinho1** [comment]
Muchas Gracias! Eso si la version que esta subida, le agregue otra lista para que funcionara bien ese comando. Basicamente ahora tambien se pueden apretar las letras por separado, pero de manera seguida, eso ayuda que cuando se apreten las tres al mismo tiempo funcione
