### ISSUE TITLE
Cantidad de carabineros por llamado

### ISSUE THREAD

**Issue by dmolina2** [IIC2233/Syllabus#488]
Cuando Quik Devil realiza una llamada a carabineros, ¿cuantos carabineros llegan? Asumimos que llega solamente 1 o a alguna tasa?
No esta especificado en el enunciado.

Gracias!

**Comment by fdominguezclaro** [comment]
Hola!
Según el enunciado, en el segundo párrafo la sección de carabineros, dice que cada inspección está dada por un solo agente. Por lo que asume que llega solo un carabinero. 
Saludos!!

**Comment by rihanuch** [comment]
No me queda claro como es que van a revisar todos los locales posibles entre las 13:00 y las 13:40. Según entendí, revisan de forma instantánea, por lo que pueden revisar todos los locales en un instante al final 🤔

**Comment by iqacevedo** [comment]
@rihanuch lamentamos no haber respondido acá, lo respondimos en #490.
