### ISSUE TITLE
Duda objeto aumento de vida

### ISSUE THREAD

**Issue by VicenteAlvarado** [IIC2233/syllabus#488]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda con respecto al funcionamiento del objeto aumento de vida, este aumenta la vida actual del personaje? O la vida total? Y en caso de que se recoja teniendo la vida al máximo, qué ocurre?

**Comment by tomasrosenberg** [comment]
Hola @VicenteAlvarado!
Efectivamente el objeto aumenta la vida actual del personaje y no la vida total. Además, si es que se recoge teniendo vida máxima esta se mantiene en ese valor. En la sección 3.1 Personajes, se menciona que el atributo vida de cada personaje se comporta como un _float_ entre 0 y 1. Por lo tanto, su valor debería moverse **solo** dentro de ese intervalo. Espero que te haya quedado más claro.
Avísame si te queda cualquier otra duda :D
