### ISSUE TITLE
Duda multiherencia: constructores y args y kwargs

### ISSUE THREAD

**Issue by mariaignaciag** [IIC2233/syllabus#488]
Hola!, desde hace un tiempo tengo problema con mi código en la parte de multiherencia al hacerlo con super(), por esto decidí continuar y poner clase.__init__(self..), pero no quiero que se me genere el drama del diamante por lo que ahora estoy cambiando esa parte, sin embargo no puedo encontrar el error, acá un ejemplo:

```python
class Clase1:
    # arg2 (queesundiccionario)
    def __init__(self,arg1,arg2,**kwargs):
        super().__init__(**kwargs)

class subclase1(Clase1):
    # arg3(diccionario)
    def __init__(self, arg3, **kwargs)
        super().__init__(**kwargs)
```

el error son la diferencia de argumentos posicionales (le doy mas o menos) así que creo que tengo un error de concepto, les agradecería mucho si me pudieran ayudar!

**Comment by fdoflorenzano** [comment]
Hola @mariaignaciag,

Para estos casos debemos tener claro que es lo que recibe el constructor de cada una de tus clases, de manera que cuando los llames, ya sean instanciando o mediante `super`, pases argumentos como corresponden. 

Revisemos en cada clase lo que se espera recibir:
* `subclase1` recibe `self, arg3, **kwargs` en su constructor. `self` se entrega por predeterminado siempre al crear la instancia como primer argumento posicional.
    * `arg3` en cambio se puede entregar como argumento posicional, o como argumento por palabra clave.
    * `kwargs` recibe todos los argumentos por palabra clave que sobren, es decir que no correspondan a `self` o `arg3` en este caso. **Pero solo por palabra clave**.
* `Clase1` recibe `self, arg1, arg2, **kwargs` en su constructor. `self` se entrega por predeterminado siempre al crear la instancia como primer argumento posicional.
    * `arg1` y `arg2` en cambio se pueden entregar como argumentos posicionales, o como argumento por palabra clave.
    * `kwargs` recibe todos los argumentos por palabra clave que sobren, es decir que no correspondan a `self`, `arg1` o `arg2` en este caso. Pero solo por palabra clave.

Por como tienes estructurado el código, `Clase1` debe recibir `arg1` y `arg2` de alguna forma, pero desde `subclase1` llamas al constructor utilizando `super` y `**`, luego la única forma que le queda a `Clase1` de recibirlos es mediante palabra clave. Entonces, como `subclase1` recibe argumentos de palabra clave sobrantes (para ese constructor) mediante `kwargs`, hay que entregarle `arg1` y `arg2` como tales, no como posicionales. Solo `arg3` tiene la posibilidad de ser posicional, siendo el primero. 

Entonces, unas formas válidas de instanciar `subclase1` son:
```python
# 3 corresponde al valor de arg3 pasado como posicional
subclase1(3, arg1=1, arg2=2)

# en este caso se pasa todo por palabra clave, 
# y el orden es irrelevante
subclase1(arg3=3, arg1=1, arg2=2) 
```

Ahora, ojo que estas restricciones de valores por palabra clave surgen por como definiste las firmas de los constructores y por como llamas mediante `super` al constructor de `Clase1`. Si se estructuran de otra forma, cambia la forma en que se pueden llamar. Por ejemplo, si `subclase1` fuera:
```python
class subclase1(Clase1):
    # arg3(diccionario)
    def __init__(self, arg3, *args, **kwargs):
        super().__init__(*args, **kwargs)
```

Ahora se permite agregar argumentos posicionales sobrantes mediante `*args` y entregar como posiciones esos argumentos a `Clase1` (por la llamada de `super` en `subclase1`). Entonces ahora es posible algo como:
```python
# 3 corresponde al valor de arg3 pasado como posicional
# 1 corresponde al valor de arg1 pasado como posicional
# 2 corresponde al valor de arg2 pasado como posicional
subclase1(3, 1, 2)
```

Espero se entienda, cualquier cosa nos escribes. 
¡Saludos!

PD: te mencionó edité el código en tu pregunta para que se viera en formato apropiado. Puedes revisar como referencia [esto](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) para escribir en formato código aquí o en tus README.

**Comment by mariaignaciag** [comment]
Me quedó muchísimo más claro, muchas gracias!
