### ISSUE TITLE
Ponderacion de progresos

### ISSUE THREAD

**Issue by Okhan97** [IIC2233/Syllabus#488]
Hola, en la parte de Tareas dice que el progreso de la tarea se define como una ponderación de los progresos de todas las áreas ... ¿ una ponderación de que estilo ?

Supongamos que hay 2 areas:
Prog_total = prog1 * prog2
Prog_total = prog1 + prog2
Prog_total = .5 * prog1 + .5 * prog2 

Al principio me guié por la primera, pero me hace poco sentido en relación a como es el progreso real de una tarea

Si esta en otro lado no logré notarlo :/ (agradecería que me dijeran donde puedo encontrarlo de ser el caso)

**Comment by iqacevedo** [comment]
Hola

La ponderación se refiere a la tercera, aunque la segunda también podría ser dependiendo de cómo definas el máximo de progreso de cada área. Aunque personalmente te recomendaría la tercera. 

Saludos !

**Comment by Okhan97** [comment]
Perfect, muchas gracias.

Otra pregunta como cierro una issue ? y los labels solo lo pueden agregar ayudantes ?

**Comment by iqacevedo** [comment]
La cierras con el botón que está al lado de **Comment**:

![captura de pantalla de 2017-05-14 21-03-49](https://cloud.githubusercontent.com/assets/13748732/26039469/2482152a-38e9-11e7-8948-749f41380807.png)

Me parece que solo los ayudantes pueden poner labels.
Saludos !
