### ISSUE TITLE
Google Form T03

### ISSUE THREAD

**Issue by beayancan** [IIC2233/Syllabus#488]
Hola, nos enviaron un Google Form diciendo si quiero corregir la Tarea 3 hasta el miércoles, pero si quiero que me corrijan con lo que entregué hasta ayer domingo ¿de todas formas debo responder el Google Form?

**Comment by Arcoirisky** [comment]
Hasta dónde sé, No O: Deja que me informo más y te comento pero, en principio el Form es sólo para entregar el Miércoles c:

**Comment by FernandoPieressa** [comment]
El form solo se necesita contestar si quieres el plazo extra hasta el miércoles.

Saludos!

**Comment by beayancan** [comment]
Eso es lo que había entendido tambien, pero en el mismo form se pregunta "Quiero entregar la T03 el día miércoles 9 de mayo" y las opciones son "Si / No". Por lo mismo pensé que todos debían responderla y qué pasaría si no lo hago.

**Comment by santilaguna** [comment]
Yo respondí que no, asumo que es lo mismo que no responderla
