### ISSUE TITLE
Error en los test_24

### ISSUE THREAD

**Issue by DiegoMoe69** [IIC2233/Syllabus#488]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En los test, en los animales que se usan el 'atributo' id_comuna no tiene ningun sentido con las comunas de los distritos dados y por lo tanto no hay animales en los distritos mas votados nunca. Solo me funcionaron los test con archivos en este caso ya que ahi si tienen sentido.

**Comment by SSParzival** [comment]
Hola buenas, lo que describes se explicó en la siguiente issue[https://github.com/IIC2233/Syllabus/issues/453].

Quedo atento por si tienes más dudas.

**Comment by DiegoMoe69** [comment]
> Hola buenas, lo que describes se explicó en la siguiente [_issue_](https://github.com/IIC2233/Syllabus/issues/453).
> 
> Quedo atento por si tienes más dudas.
> 
> 

Hola, si vi las issues pero el tema es que en el enunciado especifican que el id_comuna de cada animal corresponde al id de la comuna donde vive, y después en la función que nos piden dice que devolvamos los animales que pertenecen al distrito.
Hice la issue porque a pesar de que muchas tratan el tema, la solucion propuesta en #444 arregla el tema de la edad, pero no la pertenencia de los animales a sus comunas.
En el caso de que se pida los animales que votan en el local (que es la otra solución que completa los primero 5test pero falla con los archivos), esa solución es incongruente con la descripción de la función ya que dicen devolver los animales que pertenecen (intuitivamente viven) al distrito ganador, no los que votan en el distrito ganador.

**Comment by SSParzival** [comment]
Hola, para esta función se tiene el supuesto implícito de que, si uno vota en una comuna determinada, uno “pertenece” a dicha comuna.

En un ejemplo: Si yo voto en la Renca, pertenezco a esa comuna, y, por lo tanto, si ganó el distrito que tiene Renca, entonces yo soy un animal a retornar. 

Sé que el enunciado no es muy claro respecto a este tema, pero descuida, ya que para los tests privados solo se van a testear casos donde un animal vota en la comuna donde vive, así va a dar lo mismo si se analiza el dónde vive un animal o dónde vota un animal.
