### ISSUE TITLE
acciones características de las criaturas al comienzo del día

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#489]
Hola! El enunciado menciona que cada criatura tendrá un determinado comportamiento dependiendo del tipo de criatura que sea al comienzo comienzo del día , por ejemplo de que el augurey entregara una ofrenda al magizoologo si se cumplen ciertas condiciones , mi duda es que si se presenta este comportamiento también, cuando recién se crea un magizoologo , obtiene su criatura y pasa al siguiente día, aquí también se tiene en cuenta esas acciones para el día 0 (cuando recién se corre el programa) o parte desde el día siguiente.

**Comment by matiasmasjuan** [comment]
Hola @RonaldoSosa !

Dado que en el enunciado se señala que estos eventos ocurren *al comienzo del día*, y no a través de la acción ***Pasar al día siguiente***. Queda a tu criterio si es que esto también es válido para cuando **recién** se **crea** el **Magizoólogo** (*día 0*), u ocurre al comienzo del **nuevo día** en la acción ***Pasar al día siguiente***. Te recomiendo que especifiques en el Readme qué supuesto realizas.

Saludos y mucho éxito con la tarea! 😄

**Comment by RonaldoSosa** [comment]
Entendido! Gracias

**Comment by Camila-sty** [comment]
Hola!
Esta bien si yo por ejemplo hago que estas acciones que ocurren al comienzo de un día. Para el caso en que yo creo un magizoóloo, no se aplica esto, pero si el usuario sale del programa, y vuelve a ingresar esto si se aplica?.
Tengo otra duda que se me creo al leer el comentario de más arriba. "pasar al día siguiente" solo vale cuando el usuario opta por esto? y no para cuando sale del programa y vuelve a ingresar?

**Comment by Camila-sty** [comment]
Para ser más clara, quiero generar estas acciones de "al comenzar un día" solo cuando ingresas como un usuario existente. Se puede?

**Comment by matiasmasjuan** [comment]
Hola @Camila-sty !

Con respecto a tu primera pregunta: **no**, al momento de salir del programa y vuelves a cargar un **Magizoologo**, la idea es que cargues todo lo almacenado en el archivo ```magizoologos.csv``` y ```criaturas.csv```. Como algunos de estos datos ya venían dado a la *última vez que se pasó al día siguiente*, **no** tienes que ejecutar esas funciones de *pasar al día siguiente* al iniciar el "usuario", ya que **sólo** se efectúan cuando tu ingresas la opción de *pasar al día siguiente*.

Con respecto a la segunda pregunta, si te refieres al caso del *Augurey* y que puedes implementar la acción de que te traiga comida al momento de pasar al día siguiente o al momento tras crear tu magizoologo, queda a tu criterio. Si te referieres a **todas** las funciones que se realizan al *pasar al día siguiente*, **no**, estas sólo se realizas cuando tu ingresas esa opción en el ***Menú de acciones***.

Espero haber respondido a tus preguntas, y mucho éxito con la tarea! 😄

**Comment by Camila-sty** [comment]
Sí, entendí lo de la opción *pasar al día siguiente*. Pero entonces yo puedo considerar las acciones de *al comienzo de un día* sólo cuando ingreso un usuario existente?
(ya que si creo un usuario, se considerará el día cero, por ende, no es el comienzo del día)

**Comment by matiasmasjuan** [comment]
Si quieres efectuar las acciones de **pasar al día siguiente** apenas ingresas con un usuario existente ya que es el *comienzo del día*, **no**, **no puedes**. Sólo se efectúan estas funcionalidades cuando ingresas la opción **explicitamente** de *pasar al día siguiente*.

Saludos! 😄

**Comment by Camila-sty** [comment]
jajaja, sí, entiendo.
Estoy hablando de la acción *al comienzo de un día*, eso fue lo que dije..

**Comment by matiasmasjuan** [comment]
Si te refieres a los casos de *comienzo del día* donde por ejemplo un **Augurey** le trae alimento al **Magizoólogo**, como no se especifica que sea al momento de *pasar al día siguiente* y sólo se señala *al comienzo de cada día*, queda a tu criterio si lo implementas cada vez que inicias sesión, o lo implementas apenas *pasas al día siguiente* (recuerda notificar en tu README esta decisión).

Saludos 😄

**Comment by Camila-sty** [comment]
Ok. Gracias!
