### ISSUE TITLE
Elección de deportistas para competencias

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#489]
Hola!!! Dado que no se especifica en el enunciado (creo), podría predeterminar el orden de las competencias al pedirle al usuario que me diga los deportistas en orden?
Onda
"Elige el deportista para competir en Natación: "
"Elige el deportista para competir en Ciclismo: 
.
.
.

**Comment by jitorcas** [comment]
Hola! @denisseleiva 

Así es! Puedes predeterminar el orden, respetando que luego de seleccionar a **todos** los deportistas que participarán, se simule las competencias en el **mismo** orden. 

Mucho éxito!! 🥇

**Comment by denisseleiva** [comment]
Gracias!!!!!
