### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by JosefaATP** [IIC2233/Syllabus#489]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Cómo están? 
En el enunciado de la tarea dice:
![image](https://github.com/user-attachments/assets/34cf306b-a52e-4ef8-a09a-13f9ecff8971)
Mis preguntas son:
1- Agregando los archivos a ignorar en este .gitignore está bien?
2- En el .gitignore subido ya esta lo de los archivos .csv y .zip pero al ponerlo así se ignorar automaticamente todos esos archivos? Lo pregunto porque como es la carpeta data la que contiene los archivos .zip y .csv. Hay q agregar algun tipo de path? o con lo que ya viene esta bien?

Saludos! ✌🏼

**Comment by JosefaATP** [comment]
Además comentar que la carpeta se llama testS_publicos, por si llega a generar drama por la copia y pega del nombre en el .gitignore 

Eso ejjeje

**Comment by mane6867** [comment]
Actualmente, en el archivo .gitignore se están eliminando los archivos con las siguientes extensiones:
  ```
*.csv
*.zip
```
Esto significa que todos los archivos con esas extensiones no se subirán al repositorio, inclusive si están dentro de alguna carpeta . Además, por defecto, si una carpeta no tiene archivos que subir, no se incluirá en el _push_ hacia el repositorio. 

Además de esto, asegúrate de ignorar los otros archivos mencionados en el enunciado y en el archivo de bases generales de las tareas, que puedes encontrar en el link proporcionado en el enunciado.

**Comment by JosefaATP** [comment]
Perfecto, gracias!
