### ISSUE TITLE
Tiempo comprar Snacks

### ISSUE THREAD

**Issue by JPSF** [IIC2233/Syllabus#489]
En el enunciado se entrega un tiempo en el cual un miembro de la universidad decide comprar un snack durante el día
1. ¿Este tiempo es distinto para cada miembro ?
2. ¿El tiempo se renueva cada día o es definido al empezar la simulación?
3. Si un miembro decide ir a comprar snack ¿por cual optará?
4. ¿Para ir a comprar un snack se considera el tiempo de _ir a comprar comida_?

**Comment by fedetaladriz** [comment]
Up

**Comment by JPSF** [comment]
@iqacevedo @Hernan4444

**Comment by Hernan4444** [comment]
Disculpen los atrasos 🙏
1. Si.
2. Eso puedes decidirlo tu :)
3. Dentro de la lista de vendededores de cada comprador, pueden haber puestos de snack, deben revisar ahí primero  y si no hay o son descartados, entonces van al quick.
4. Precisamente, el puesto de snack es un tipo de vendedor al igual que todos pero su comida es "snack", así que debe ser tratado como cualquier otro vendededor en la simulación

Saludos ✌️

**Comment by JPSF** [comment]
Gracias Hernán!
