### ISSUE TITLE
Problema con distintos mapas

### ISSUE THREAD

**Issue by tomasjelvez** [IIC2233/syllabus#489]
Hola, tengo un problema al cargar distintos mapas ya que ocupe Qgridlayout para crear el mapa, por lo que al abrir mapas distintos, las coordenadas que utilizo para el resto del programa no son las mismas y el juego no funciona como deberia.
Que me recomiendan hacer?Implementar lo que me queda tal como esta y asumir el descuento en la nota o intentar arreglar el problema, arriesgando no alcanzar a implementar lo que me falta?.

**Comment by aljara97** [comment]
Hola, según entiendo solo implementaste el cargado de mapa para uno de los archivos entregados, ya que ambos mapas tenían un largo y ancho distinto. En esta tarea se evalúa que tu programa debe ser capaz de leer cualquier mapa que queramos probar, sin embargo si no lo implementas de manera total, debes especificarlo en tu readme indicando el archivo para el cual funciona. No puedo decirte si priorizar este item u otro, sin embargo, te aconsejo revisar la distribución de puntaje y escoger según tu criterio.

Éxito con tu tarea :seedling:

**Comment by adbakulic** [comment]
Hola! 
A mi me pasa algo parecido. Logré cargar ambos mapas pero el GridLayout no se adapta al porte que tiene cada mapa. Por lo mismo, por ejemplo al aumentar el parámetro N, no se agranda la ventana, sino que se ajustan las imagenes del mapa a la grilla y quedan con un porte menor a N. 
Esto me afecta también para relacionar las coordenadas de la grilla con  las coordenadas de la ventana para que el personaje no pueda pisar piedras o saber cuándo está sobre la tienda.
¿No debería adaptarse la grilla al mapa en vez del mapa a la grilla?
Si no es así, como puedo hacer que la grilla se ajuste a lo que necesito.
Gracias de antemano.

**Comment by aljara97** [comment]
Hola @adbakulic, estuve viendo tu repositorio y existe el archivo ```ventana_juego.ui```. Es probable que al crear la ventana de inicio mediante Qt Designer no hayas instanciado el tamaño de la grilla ni de la ventana en función del parámetro N, lo que ajusta el tamaño de cada elemento de esta en función del espacio asignado. En caso de que quieras solucionar esto, te recomiendo crear la ventana y sus elementos a través de código y sin usar Qt Designer, los cuales deben estar en función de N.
