### ISSUE TITLE
Error Enunciado(?)

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#489]
Puede ser que en el documento T03 - PNG y Filtros.pdf en la sección 2.4.1 la convolucion tiene un valor errado? ME dio todos iguales menos el 184 que a mi medio 183.

**Comment by jeschuwirth** [comment]
Saludos,

Tienes razón, el valor correcto es 183, sin embargo no debería afectar en el enunciado.

felicidades por darte el trabajo de calcular la matriz 😅
