### ISSUE TITLE
Error linea

### ISSUE THREAD

**Issue by Chiseth** [IIC2233/Syllabus#489]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Acabo de entregar la tarea 1 día tarde como a las 7:30 y acabo de notar 8:05 que en una linea escribi mal un parametro edadd en vez de edad, por lo que no pasan esos test y quería saber si hay opcion de solo quitarle una d y que se siguiera considerando que solo entregue 1 día tarde : c

![image](https://github.com/IIC2233/Syllabus/assets/156480987/f0cc7433-2389-41d0-bdc7-2c60e47b0cd2)

**Comment by diegobas10** [comment]
Hola @Chiseth,
Lamentablemente, tendrías que usar el formulario para un día extra si es que esta función afecta gran parte de la entrega haciendo que te baje mucho el puntaje, y si solo afecta a un test, te recomendaría revisar si es que te conviene dejar así la entrega o pedir otro día. Los cambios de línea solo sirven para la parte que se revisará manualmente, pero esta parte se revisa por script.
Saludos, quedo atento a cualquier duda.
