### ISSUE TITLE
Entrega enunciado T04

### ISSUE THREAD

**Issue by alfa-labarca** [IIC2233/Syllabus#489]
Buenas, quería preguntar si pueden subir el enunciado de la tarea 4 esta semana, para poder empezar a trabajar lo antes posible, aunque aún no tengamos clases de la materia, al menos podemos leer el enunciado y empezar a pensarlo y programar las bases.
Así, en vez de tener una semana sin nada que hacer de la tarea, tendríamos una tarea en la que podemos trabajar por tres fin de semanas.

Saludos.

**Comment by FernandoPieressa** [comment]
Hola!

Todavía estamos haciendo los últimos ajustes al enunciado de la tarea para que quede lo mas entendible posible, por lo que no podremos subirla aún.

Saludos!

**Comment by alfa-labarca** [comment]
Y no podrían entregarla mañana después de la "entrega final" de la tarea 03?

saludos.

**Comment by Hernan4444** [comment]
Analizamos tu sugerencia, pero no será posible.
Saludos
