### ISSUE TITLE
Librería pathlib

### ISSUE THREAD

**Issue by nicolascamhi** [IIC2233/syllabus#489]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Podemos usar la librería pathlib para los paths? Es como usar os.path.join pero una versión mejorada y mas fácil de usar.

**Comment by tomasrosenberg** [comment]
Hola @nicolascamhi!
Por desgracia, no puedes utilizar esta librería ya que se encuentra en las Librerías Prohibidas de la Tarea 2. Te recomiendo seguir usando os para tus paths.
Quedo atento cualquier otra duda
