### ISSUE TITLE
[Suposición] Manejo de contenidos

### ISSUE THREAD

**Issue by aeperalta** [IIC2233/Syllabus#489]
Hola,
el manejo de contenidos depende de las horas estudiadas. Por otro lado, si el alumno va a la ayudantía y si el ayudante domina los contenidos, sube 10% su manejo de contenidos. La pregunta es: ¿puedo suponer que esa subida del 10% sea cuando va a cátedra y no en el momento que va a la ayudantía?
La pregunta va porque ese supuesto me facilita algunos cálculos, pero no sé si es razonable hacerlo.
De antemano, gracias.

**Comment by FernandoPieressa** [comment]
No es razonable, porque mezcla lo que debería ocurrir en distintos eventos, la idea es que en cada evento se pueda ver que va pasando en la simulacion y como afecta a los alumnos

Saludos!

**Comment by aeperalta** [comment]
Ahora que lo dices, tenía mal modelado el cálculo de manejo de contenidos.
Gracias!

**Comment by berrazuriz1** [comment]
Entonces la subida del 10% del manejo de contenidos en la ayudantia, es con respecto al manejo de contenidos que tengo con las horas estudiadas hasta ese minuto.

**Comment by berrazuriz1** [comment]
Es una pregunta.

**Comment by aeperalta** [comment]
por lo que respondió @FernandoPieressa, creo que así es (al menos yo lo hice así)
