### ISSUE TITLE
experiencia 1: al importar pretty_print y loader en main.py me sale que no hay modulos que se llamen asi. 

### ISSUE THREAD

**Issue by emivenezian** [IIC2233/Syllabus#49]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Mi repositorio se ve asi. Experiencias: experiencia 1: main.py, entities.py, y la carpeta utils como deberia ser. Pero no logro importar los modulos

**Comment by pacalein** [comment]
Hola! cuéntanos si aún tienes el problema, y de ser así trata de adjuntar alguna foto de la terminal, el directorio, o el código para poder ajustar la ayuda.
