### ISSUE TITLE
Funciones atómicas: criterio de contar lineas

### ISSUE THREAD

**Issue by ggmirandac** [IIC2233/Syllabus#49]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una pequeña duda sobre la bonificación para funciones atómicas.

Cuando ocurre el conteo de líneas, que se cuentan como líneas. Por ejemplo, en la siguiente función:

def suma_con_truco(x,y):
    for i in range(y):
       x+=1
    return x 

¿Se cuenta como si tuviera 3 líneas o 4 líneas?

De antemano muchas gracias.

**Comment by pedrozavalat** [comment]
Hola @ggmirandac !

En el enunciado de la tarea se dice que: _"se pide que cada función o método definido **dentro** del código contenga un máximo de 15 líneas de código"_. Por lo tanto, respondiendo a tu pregunta, se contaría como 3 líneas, ya que tienes que considerar el código dentro de la función.  

Cualquier duda responde este hilo,
Saludos 😄 

Pedro Z.

**Comment by Hernan4444** [comment]
Hola @ggmirandac 

Notamos que marcaste el tercer check de tu issue que dice: "Revisé el compilado de dudas de la tarea y no encontré una issue similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/syllabus/issues/21))."

No obstante, en el compilado se encuentraba una issue en la seccón de Bonus que se llama 
* #30 

La cual pregunta sobre este mismo tema y se le entrega una respuesta que hubiera respondido a tu duda. Por favor más ojo con las siguientes issues de revisar antes que exista una del mismo tema y si no ocurre eso, crear una nueva. Así unificamos las dudas de un tema en la misma issue. Además, el buscador de github permite buscar por palabras claves. Si pones "bonus" te buscará todas las issues donde se mencionó esa palabra y así buscar aquella que trate tu consulta.

![image](https://user-images.githubusercontent.com/15641721/227078693-980bec24-b584-4e8f-9bcd-d5690c9b7746.png)

Dejaremos esta issue cerrada para que cualquier duda con el número de líneas para el bonus se mantenga en la issue ya creada (#30 )

Saludos c:
