### ISSUE TITLE
Pareja de match

### ISSUE THREAD

**Issue by dialvarez1** [IIC2233/Syllabus#49]
¿Es necesario mantener información de cuál _order_ produjo _match_ con cuál o basta con saber que se produjo un _match_ no más?
Si es el primer caso, me parece rebuscado (aunque no imposible) emparejar las _orders_ al cargarlas del archivo _csv_.
Si es el segundo caso, en la lista de _orders_ (no necesariamente activas): ¿Qué pasa con los _match_ parciales? ¿Las _order_ se modifican para ajustarse al valor que efectivamente se transó o se debe recordar que fue un _match_ parcial?

**Comment by stephichau** [comment]
Es lo que dices en el primer caso.
Saludos!

**Comment by gabrielpinkman** [comment]
y qué sucedería con los matches parciales? también deben mostrarse por consola?

**Comment by sebacruzd** [comment]
@gabrielpinkman los match parciales son matches después de todo, así que sí. 
En todo caso, no es necesario que se especifique que fue un match parcial, esto depende de su modelación y está bien si se especifica tanto como si queda como un match normal.
