### ISSUE TITLE
Duda sobre el output que entrega vscode vs. el que aparece en jupyter notebook

### ISSUE THREAD

**Issue by luzmagurzua** [IIC2233/syllabus#49]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Estoy estudiando los contenidos más a fondo para realizar la tarea de forma óptima. Y revisando los códigos que aparecen en jupyter, los escribí tal cual en vscode y el output es ligeramente distinto, es decir: en jupyter aparecen paréntesis y comas, mientras que el resultado de la terminal de vscode va sin ellas. Puede ser un detalle pero quería aclarar por qué sucede. Adjunto foto y desde ya gracias. 

Foto en blanco, jupyter notebook
![Captura de Pantalla 2021-03-26 a la(s) 00 00 01](https://user-images.githubusercontent.com/80796978/112571165-43795c00-8dc6-11eb-8c24-c7b521dc6369.png)

Foto en negro, vscode
![Captura de Pantalla 2021-03-26 a la(s) 00 01 09](https://user-images.githubusercontent.com/80796978/112571239-6c015600-8dc6-11eb-906c-ac72795002ce.png)

**Comment by Juampisaez** [comment]
Hola @luzmagurzua 
La verdad es que es muy sutil la diferencia, en vscode lo que estas haciendo es imprimir en consola con un print(). Mientras que en jupyter te retorna la ultima linea con lo que esta, jupyter lo hace por default. La idea de haberlo hecho así, era para mostrar de forma mas rapida que las variables se crean en la clase video.
Por ultimo, te aconsejo escribir todo tu codigo en un editor de codigo (jupyter no lo es)

Espero haya quedado mas claro :)

**Comment by luzmagurzua** [comment]
Holaa, sii, es que pensé que lo que muestra Jupyter tenía que ser exactamente igual a la que uno ve en un editor de código normal. Pero no me quedó muy claro tu explicaión:( jajajaja. Me lo podrías explicar de nuevo porfa :(

**Comment by Juampisaez** [comment]
Tranqui, primero hay que entender que jupyter **no es** un editor de codigo, es un entorno de trabajo interactivo, por lo que no tendría porque necesariamente mostrarte lo mismo que si corrieras el codigo en un editor de codigo como vscode. 
Segundo, en jupyter al colocar `(vid.ext, vid.size)` por defecto te retorna `('avi', '1024')`, te lo muestra con comillas porque sería un string mas que nada (asi lo definiste). Ojo que jupyter en este caso te esta retornando algo, no quiere decir que te lo este imprimiendo (con print). Basicamente, son funcionalidades extras que tiene jupyter jeje nada mas.

Espero haya quedado un poco mas claro.

**Comment by luzmagurzua** [comment]
Ahhhh! Parece que sí. Porque ahora estaba viendo este código (que sale en jupyter): 

# Usando los valores asignados en a, podemos obtener los valores de una sección de la tupla.
data = (400, 20, 1, 4, 10, 11, 12, 500)

# Recuperamos los elementos que están entre los índices 1 y 3
a = data[1:3]
print('1: {0}'.format(a))

copié y pegué eso en vscode y me salé error en el formato del print :( será por la misma razón que tu me das? (estaba tratando de ver como funciona .format)

**Comment by Juampisaez** [comment]
Mm, debería imprimir en la consola esto:
`1: (20, 1)`

Que error en especifico te aparece?

**Comment by luzmagurzua** [comment]
Mmmm no te preocupes, ahora me resultó pero a veces no :S es raro jajajaja pero gracias igual :)
