### ISSUE TITLE
Líderes / Doctor Valdivieso

### ISSUE THREAD

**Issue by pmolinaj** [IIC2233/syllabus#49]
Hola!
Tengo una duda con la bonificación que entrega el Dr. Valdivieso:
Esa bonificación de 50 % de los puntos de progreso científico generados por estas unidades (ayudantes), ¿Ocurre cada turno sobre todos los ayudantes? ¿Ó es solo una vez en el juego?
![Captura](https://user-images.githubusercontent.com/37165246/54975479-f7487680-4f75-11e9-9f72-5423fb296752.PNG)

**Comment by lily416** [comment]
Hola :)

La bonificación se aplica en cada turno sobre todos los ayudantes del DCC.

Saludos y éxito en la tarea :wave:
