### ISSUE TITLE
Uso de POO

### ISSUE THREAD

**Issue by Juanfischermontero** [IIC2233/Syllabus#49]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Es obligatorio el uso de clases para esta tarea? De ser así no me queda claro en que partes es obligatorio y en cuales no. Gracias de antemano.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by vicentethomas** [comment]
Hola, esto ya fue respondido en la issue #32. (spoiler: no es obligatorio pero si recomendado)
