### ISSUE TITLE
Acerca del archivo entregado "parametros.py"

### ISSUE THREAD

**Issue by nolate26** [IIC2233/Syllabus#49]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, quedé con una duda, me pasó que implementé en mi código dos archivos .py y no usé el archivo 'parametros.py', pero aún así usé los parámetros que entregaba el archivo y efectivamente estoy importando otro archivo. Leyendo en la distribución de puntaje en  la sección General sale: "Parámetros: se utilizan los parámetros entregados dentro del programa, y se importa el módulo de forma correcta". ¿Si es que no use el archivo "parametros.py", no obtendré el puntaje? ¿o se considera como parámetros el archivo que tengo con otro nombre? 
Muchas Gracias

**Comment by catalina-arcila** [comment]
Hola @nolate26, se evaluará según la distribución de puntaje. Por lo que si no usaste el archivo llamado _parametros.py_, no obtendrás el puntaje indicado.

**Comment by nolate26** [comment]
Muchas gracias, cambiaré le nombre del archivo.
