### ISSUE TITLE
Agregar ID

### ISSUE THREAD

**Issue by mguerreromir** [IIC2233/Syllabus#49]
Cuando queramos agregar algo a una de las bases de datos el id debe corresponder al que sigue en la lista o se lo tenemos que pedir al usuario?

**Comment by FernandoPieressa** [comment]
Hola!

El usuario no elige su numero de id, el id se genera dentro de su programa.

La idea del id es poder tener un numero unico dentro de la tabla que actue como llave para referenciar el objeto de la tabla

Saludos!

**Comment by ignacioaraya1995** [comment]
¿Cuando agrego un usuario, como elige el recurso_id , si por ejemplo creo un piloto (avión), tengo que pedirle las coordenadas y el resto de los datos con un input?

**Comment by nivek0o0** [comment]
Hola!
¿puede un recurso estar asignado a más de un usuario o la asignación siempre es 1 a 1?

**Comment by rpalmaotero** [comment]
@ignacioaraya1995 no está especificado, queda a tu criterio.

@nivek0o0 no hay problema, lo único importante es que cada usuario sólo esté asociado a un recurso, debido a la estructura de las tablas.

**Comment by lefischer** [comment]
podemos asumir que los id van aumentando secuencialmente, es decir para generar un id solo revisamos el anterior y se le suma 1?

**Comment by rpalmaotero** [comment]
@lefischer mientras sean únicos no hay problema.
