### ISSUE TITLE
Modificar archivos entregados

### ISSUE THREAD

**Issue by EmeraldMP** [IIC2233/syllabus#49]
Hola!

Es necesario actualizar los archivos entregados? Si es así, hay que ir actualizándolos cada vez que agregue o elimine algo o se puede actualizar una vez que se salga de la aplicación  creada?

Saludos!

**Comment by KnowYourselves** [comment]
Hola @EmeraldMP!

Esta pregunta fue respondida en la issue #41. Recuerda revisar el compilado de issues antes de preguntar.

Éxito!
