### ISSUE TITLE
Duda sobre la construcción de la red en el menú

### ISSUE THREAD

**Issue by Yeps3nM** [IIC2233/Syllabus#49]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Leí la parte de la construcción del menú y me quedó la duda respecto si yo construyendo una función debo entregar la red aludida en la linea de argumentos de la consola? Porque revisé en los test case del flujo de programa general y esta es entregada de forma lista en una variable. Pero estoy confundida de si en efecto yo debo entregar a las funciones de dcciudad, la red extraída desde el archivo con una función que yo construí en el archivo main.  Muchas gracias :)

**Comment by Pablo-Gonzalez-Calderon** [comment]
Holaaa ✨

Como bien mencionas, hay que hacer un "paso intermedio" para poder pasar desde el nombre de la red (_string_ entregado a través de la consola) hacia la lista que contiene la red de metro mencionada en ese _string_. La decisión de cómo lo hagas queda a tu criterio, mientras cumplas con los elementos a evaluar (especificados en la pagina 11 del enunciado, y también en el Excel de asignación de puntaje [aquí](https://docs.google.com/spreadsheets/d/1T8mptqbKGWay1crfTRisRhfUGSEssS-EWpUTdL4gmTE/edit#gid=383710472)):
>![image](https://github.com/IIC2233/Syllabus/assets/30756770/4a752932-203d-4b00-a2ef-5eff615dc31d)

Espero haber podido responder tu duda, si no, avísame 😊🍀

**Comment by Yeps3nM** [comment]
Sii, todo claro! Muchas gracias :)
