### ISSUE TITLE
Problema con numpy

### ISSUE THREAD

**Issue by tgarcia4** [IIC2233/syllabus#49]
Cuando hago import numpy me tira un error que dice que no hay un modulo con el nombre numpy

**Comment by gatochico** [comment]
Hola! 
Numpy es una librería que no viene por defecto en python, y por ende debe ser instalada. Para instalarla, debes abrir la consola de tu computador y probar con alguno de estos comandos:
`pip install numpy`
`pip3 install numpy`
Alguno de los 2 debería instalar numpy en tu computadora y permitirte importarlo en tu programa.

Avisanos como te va y saludos! :computer:

**Comment by tgarcia4** [comment]
Eso era! Gracias @gatochico
