### ISSUE TITLE
Abrir jupyter desde cmd Windows

### ISSUE THREAD

**Issue by antonioerr** [IIC2233/syllabus#49]
Usar el comando jupyter notebook desde el cmd no me funciona, me sale el error: 
"jupyter" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable. 

En cambio si uso el comando python -m notebook si funciona.¿Por que pasa esto?

**Comment by tocococa** [comment]
Hola @antonioerr ! Si tienes MacOS, te recomiendo revisar [este thread](https://github.com/IIC2233/syllabus/issues/10), pero lo más probable es que haya ocurrido algún problema con el PATH de la instalación. De todas formas, si puedes abrir los _notebooks_ e interactuar con ellos correctamente no te preocupes.

**Comment by Yugen02** [comment]
tengo el mismo problema pero gracias a tu comentario logre abrirlo
