### ISSUE TITLE
Guardar resultados Campeonato

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2233/syllabus#490]
Hola! 
Una vez finalizado un campeonato, ¿los resultados de este deben quedar guardados en resultados.txt para siempre? ¿ No se debe borrar el contenido una vez que el usuario decide iniciar una nueva partida?

Gracias y saludos :)

**Comment by vsantelicest** [comment]
Hola **@ignaciomansuy**!
En el enunciado no se aborda este caso de manera específica, por lo que puedes llevarlo a cabo de la manera que tu creas es más conveniente, sobreescribiendo al archivo con cada partida o ir añadiendo la información de cada una de ellas. Solamente procura que la manera que decidas hacerlo esté explicada en tu readme.
Suerte!! 🚴
