### ISSUE TITLE
Cantidad de secciones

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#490]
Hola!

Como nuestra simulación es un universo paralelo al nuestro, ¿podemos suponer que siempre van a haber tres y solo tres secciones?

Saludos!

**Comment by Hernan4444** [comment]
@akaminetzkyp lamento decir que el Malvado doctor Mavrakis le gusta cambiar la composición del curso, despidiendo ayudantes, contratando mas profesores, creando mas o menos secciones, etc. La única regla que sigue (y esto si lo puedes suponer) es que todo eso lo especificará en `integrantes.csv` y este estará bien escrito, es decir, si un alumno es de la seccion "x", entonces hay un profesor de la seccion "x", al menos existen 2 ayudantes de docencia y 1 de tarea en el curso y hay un coordinador

**Comment by akaminetzkyp** [comment]
Uhhh, vale! Gracias!

Saludos!

**Comment by AmbrosioV** [comment]
¿No deberían ser mínimo tres ayudantes de docencia, ya que al menos tres van a cada clase? y otra pregunta, ¿no son por sección? puedo suponer que se desdoblan y ¿van a todas las secciones a la vez?
Y otra respecto a los ayudantes, ¿las tareas son coordinadas entre secciones? es decir, ¿es la misma tarea para todos?
De momento y segun let003 entiendo que los ayudantes son compartidos por todas las secciones.
sl3

**Comment by ranieto** [comment]
@Hernan4444 En `integrantes.csv`, ¿siempre irán primero los profesores, luego el coordinador, ayudantes y finalmente alumnos? ¿o ese orden también puede variar?

**Comment by Hernan4444** [comment]
@AmbrosioV tienes toda la razón!!! la cantidad de ayudantes de docencia siempre será como mínimo 3 veces la cantidad de secciones (para que vayan 3 por sección).
Respecto a las tareas, son todas coordinadas e igual para todas.... El malvado coordinador Mavrakis no les paga lo suficiente a los ayudantes para que hagan tareas diferentes por sección.

@ranieto Como en el csv se indica el rol por integrante, no es necesario suponer el orden, es decir, estos pueden ir en desorden.
Saludos!
