### ISSUE TITLE
Crecimiento de planta al pasar el dia

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus#490]
Tengo la duda de que pasa si duermes en cualquier momento del dia con respecto al crecimiento de plantas.

**Comment by gatochico** [comment]
Hola!

Los cultivos deberían haber progresado el tiempo respectivo que se durmió. Si dormiste 8 horas, el cultivo al siguiente día debería comportarse como si hubieran pasado estas 8 horas, a pesar de que estas no 'ocurrieron' (se paso automaticamente al siguiente día).

Cualquier duda comenta! :cat:
