### ISSUE TITLE
Codificar Tipo Bloque

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#490]
No entiedno que tenemos que ni como codificar, se tiene que pasar a bytes los distintos strings "IHDR", "IDTA" y "IEND"? 

![Captura](https://user-images.githubusercontent.com/48294819/59320913-2d0c1a00-8c9e-11e9-9715-00da9187a6b1.PNG)
 y de tener que hacerlo así esta bien hecho de esta forma, por ejemplo? y esto se agrega al principio de cada chunk despues del largo?
![Captura2](https://user-images.githubusercontent.com/48294819/59321034-88d6a300-8c9e-11e9-9739-012fd135676f.PNG)

**Comment by iqacevedo** [comment]
Hola !

Efectivamente a eso se refiere, y si, el tipo de bloque va al principio de cada _chunk_. Algo que hará que tu código sea más fácil de leer es definir el byte con `b` antes del string. Lo que escribiste es equivalente a `tipo_de_bloque = b"IHDR"`, que es una linea y se hace más fácil de leer y entender. A menos que quieras usar un encode especial y este no es el caso.

Finalmente, ten cuidado con subir fotos de código de algo tan directo a la tarea. En este caso era algo pequeño así que no hay problema :smiley: .

Saludos !
