### ISSUE TITLE
No funciona git bash

### ISSUE THREAD

**Issue by simoneaston** [IIC2233/syllabus#490]
Hola! cuando hago commit para subir cambios de la T01 me aparece esto y no se sube nada! no se qué hacer
$ git commit -m "tarea lista"
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
(use "git add ..." to update what will be committed)
(use "git restore ..." to discard changes in working directory)
modified: ../../Actividades/AF02/combate.py
modified: clases.py
modified: clases2.py
modified: menus.py
modified: parametros.py

el error surgió cuando eliminé un archivo de la carpeta directo en github

**Comment by simoneaston** [comment]
el error surgió cuando eliminé un archivo de la carpeta directo en github

**Comment by simoneaston** [comment]
ahora me pone esto:

$ git commit -m "tarea lista"
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ../../Actividades/AF02/combate.py
        modified:   clases.py
        modified:   clases2.py
        modified:   menus.py
        modified:   parametros.py

**Comment by jeschuwirth** [comment]
Hola @simoneaston,

Intenta hacer un git pull para actualizar los cambios hechos en la plataforma de github y luego hacer los commit y push.

Si eso no funciona te recomendaría clonar nuevamente el repo en otra carpeta y luego agregar los archivos nuevos, hacer git add, commit y push. 

La primera solución puede que no te solucione el problema para es rápida de intentar, la segunda solución es segura que te va a resolver el problema pero puede no ser tan cómoda

Me avisas que tal te va :)

**Comment by simoneaston** [comment]
Ya, muchas gracias!
Finalmente git pull no funcionó. Me funcionó fue hacer git add -A.
