### ISSUE TITLE
duda funciones que reciban  mas de un generador

### ISSUE THREAD

**Issue by vhernnda** [IIC2233/Syllabus#490]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Estaba haciendo la funcion de consultas y al ejecutar los tests me di cuenta que en un caso una de las funciones recibe un generador de contenidos el cual contiene pedidos para los cuales el nombre corresponde a una pizza que no se encuentra en el generador de pizzas.

En base a esto deberia tener en cuenta que es posible que un generador tenga datos que otro generador no?, EJ:
un generador de pedidos con una id que no se encuentra en un generador de contenidos

**Comment by FradexMF** [comment]
Hola!
¿Podrías contarme en que test ocurre esto? Así puedo revisar que es lo que puede estar pasando

**Comment by vhernnda** [comment]
corresponde a los tests 2 y 4 del test de consultas anidadas, ambos tienen como funcion principal a "total_ahorro_pedidos" y por lo menos uno de sus generadores corresponde a otra funcion distinta a las de cargar, mi codigo inicial me tiraba error en ambos porque el generador de contenidos tenia pizzas que no estaban presentes en el generador de pizzas, escribi mi codigo inicial asumiendo que cada pizza dentro de los contenidos iba a estar dentro del generador de pizzas, volvi a reescribir el codigo asumiendo que existe la posibilidad de que los contenidos contengan pizzas que no estan presentes en el generador de pizzas y ahora me funciona, pregunto mas que nada porque hice el codigo para todas las funciones con mi supuesto inicial y necesito saber si es necesario reescribirlo en base a lo previamente mencionado.

**Comment by FradexMF** [comment]
No deberia de ser posible. Los datos están hechos para que solo referencien datos existentes.

Lo que puede estar pasando es que como las consultas anidadas pasan por varias funciones, en alguna de estas se hayan filtrado datos de tal forma que se borre la instancia que se referenciaba. No debería ser algo que preocuparse en otras funciones.

**Comment by vhernnda** [comment]
O sea que lo mas probable es que sea un error en consultas_anidadas en lugar de un error en una de las funciones que utiliza?

**Comment by FradexMF** [comment]
Depende completamente de tu codigo. Considerando que se usan las funciones de la tarea en consultas_anidadas es posible que tengas que modificarlas para que no se caigan cuando consultas_anidadas las llame con generadores que le faltan datos.

**Comment by vhernnda** [comment]
Dale, ya me quedo claro
