### ISSUE TITLE
Error al importar pyqt5

### ISSUE THREAD

**Issue by TomasAuad** [IIC2233/syllabus#490]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola,

Cuando intento importar alguna librería de pyqt5, por ejemplo:

from PyQt5.QtCore import Qt, pyqtSignal

Salta el siguente error: ImportError: DLL load failed: No se encontró el proceso especificado.

Ya desinstale y volví a instalar pyqt5, pero aun así no cambio nada, no me había pasado antes, ni con las actividades ni con los contenidos.

Gracias.

**Comment by catalina-arcila** [comment]
Hola @TomasAuad 😃, lo estas corriendo en vs code o en la consola??
Intenta correrlo en la consola para ver que error te sale ahí.
Quedo atenta!

**Comment by TomasAuad** [comment]
Lo intenteee, pero pasa exactamente lo mismo.

**Comment by catalina-arcila** [comment]
https://github.com/IIC2233/Syllabus-2017-2/issues/203#issue-254723058 en años anteriores se tuvo el mismo problema, te recomiendo darle una mirada a este issue 🧐

**Comment by TomasAuad** [comment]
Funcionoo

Muchas gracias
