### ISSUE TITLE
Demora inspección carabineros

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#490]
Hola, 

en el enunciado sale que cuando el agente de carabineros inspecciona es de 13:00 hasta las 13:40.
Pero tambien sale que el revisar es inmediato y que la tasa es una tasa de productos.

Esto significa que: un carabinero siempre se demora 40 min en revisar todos los stands?
Como son todos inmediatos, los vendedores que no pasan el test, cuando se van? 
Random entre 0 y 40 nomas?

gracias

**Comment by valeria-adasme** [comment]
Me añado a esta pregunta :( Si todas las revisiones puedo asumirlas como inmediatas ¿no alcanzaría entonces a revisar todos los puestos incluso antes de que sean las 13:40? ¿O la gracia de esto es que siempre revisa todos los puestos entre esas horas?

**Comment by cilopez** [comment]
@Kitaps @valeria-adasme actualizé recién el enunciado, diganme si ahora es más claro como se realiza !

**Comment by valeria-adasme** [comment]
Gracias :) Leí el enunciado y aún me queda una pequeña duda...

Si se demora 40/N en revisar cada puesto, son N puestos en total y él se queda por 40 minutos en el lugar...
eso significa que revisa todos los puestos que habían?

Porque supongamos son 5 puestos de comida, se demoraría 8 minutos en cada uno, por lo que en 40 minutos alcanza a revisar los 5 puestos de la lista.
¿Qué sentido tendría que fuera de elección aleatoria así, si de todas formas los alcanza a revisar todos? ¿O pueden llegar puestos entre esas horas? (Como la instalación de puestos se asigna con distribución normal en 11:00 hrs con desviación 30 min, creería que es muy poco probable que lleguen a instalarse puestos entre esas horas).

Espero se entienda mi duda, quiero que me aclaren eso para ver si entendí bien @-@

**Comment by cilopez** [comment]
Si, el carabinero revisa **todos** los puestos, el sentido es que mientras el carabinero revisa el puesto no podrá vender, si es el primer puesto este no podría vender entre las 13:00 y 13:08 horas

**Comment by ptflores1** [comment]
@cilopez Que pasa si llegan mas vendedores entre las 12:00 y las 12:40 que es cuando ya se esta fiscalizando ?

**Comment by ptflores1** [comment]
@cilopez Necesito la respuesta de esto porfavor ! :cold_sweat:

**Comment by cilopez** [comment]
No esta explicito como se hace , desarrollalo como se te ocurra y mencionalo en tu readme!
