### ISSUE TITLE
Duda Enunciado

### ISSUE THREAD

**Issue by martin-santiago** [IIC2233/syllabus#491]
Hola buenas tardes

En el enunciado sale que debemos usar conceptos de herencia, clases ABC, polimorfismo y porperties *almenos una vez* ahora, si efectivamente solo lo hago una vez perderé puntaje?? ya que igual estaría cumpliendo el enunciado

**Comment by vicentevegaulloa** [comment]
Hola @martin-santiago !

Se te indica que deberías ocupar por lo menos una vez cada concepto, sin embargo, deberías esta más preocupado de como los usas que cuantas veces los usas. Si no los usas por lo menos una vez sabes que estás haciendo algo mal, pero eso no significa que si los utilizas más de una vez o una sola vez los estés usando bien. Al corregir los ayudantes nos guíamos por la distribución de puntaje, donde se corrige la modelación y la forma que implementas estos conceptos más que la cantidad de veces que los usas. Espero que se entienda 😄
