### ISSUE TITLE
Problemas con el test_05_clientes_despues_hora_carga_datos

### ISSUE THREAD

**Issue by MJelvez** [IIC2233/Syllabus#491]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [`X`] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ `X`] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ `X`] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ `X`] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, tengo un problema, ya que mi código para el test_05_clientes_despues_hora_ correctitud me aparece que esta todo correcto y pero al hacer el test_05_clientes_despues_hora_carga_datos me aparece que hay problemas de Diferencia de caracteres, no se como solucionarlo. ya que el test_00_cargar_datos tampoco me muestra problemas.

**Comment by FradexMF** [comment]
Hola! Esta duda ya se vio en el issue #482.
