### ISSUE TITLE
visualización de ventana en qtdesigner es diferente a cuando la ejecuto

### ISSUE THREAD

**Issue by a-ck** [IIC2233/syllabus#491]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Me pasa que diseño una ventana en qtdesigner que se ve bien, pero luego al ejecutar el codigo en vsc la ventana se muestra diferente (y mal). Por ejemplo letras más grandes y que no caben. no sé si me explico... adjunto imagen.
![image](https://user-images.githubusercontent.com/69538524/119285027-210d8e80-bc0f-11eb-996a-7dce6b3cd53d.png)

**Comment by Juampisaez** [comment]
Hola @a-ck 
Estaba viendo tu repo para ver el error, y no subiste los archivos .ui (en el gitignore le agregas la carpeta assets donde se supone estan los archivos .ui), si lo subes te puedo ayudar mejor.

Quedo atento :)

**Comment by a-ck** [comment]
ahí los subí :)))

**Comment by Juampisaez** [comment]
@a-ck 
Estaba viendo tu ventana, y la verdad es que se instancia bieen (los sprites no se muestran eso si, puede ser por como le das la ruta en designer). Que archivo estas corriendo para ejecutar tu ventana?

**Comment by a-ck** [comment]
los sprites los pongo en la parte de pixmap del designer, está mal hacerlo así? para ver las ventanas corro el main, pero a mí si me aparecen algunas cosas cortadas, será una cosa de cada computador entonces? :(

**Comment by Juampisaez** [comment]
Mm, si quieres podemos verlo por discord. Parece que el pixmap de cada label no se ha guardado (la ventana me aparece sin sprites).

**Comment by a-ck** [comment]
Arreglé mi primer problema (cambié la escala de windows de 150% a 100%). Mi duda es que igual se corre el riesgo de que en otro computador se vea mal o no? 
También arreglé lo de los sprites jeje

**Comment by Juampisaez** [comment]
Si lo subes a github, te puedo decir
