### ISSUE TITLE
Simulación -Contenidos

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#491]
Hola!
En los contenidos de esta semana no entendí muy bien porque si los métodos de `CreadorVehículos`, `programar_creación_vehículo` y `crear_vehículo`,  se llaman entre sí, estos no entran en un loop infinito (considerando que nunca evalúan el tiempo o algo así). Si me lo pudieran explicar sería de gran ayuda!

**Comment by jecastro1** [comment]
Veamos,

Lo primero que hace un `CreadorVehículos` es llamar a `programar_creación_vehículo`. Este método programará un evento futuro, en el que se creará el próximo vehículo. 

Dentro de la definición de `programar_creación_vehículo`, se calcula en cuánto tiempo se creará un vehículo a partir de ahora, y se calcula el tiempo contando desde cero. Después, se crea un `Evento`. Este evento tiene el `tiempo_evento`, que es cuándo se ejecutará, y una función, que en este caso es `crear_vehículo`. Notar que **el evento guarda la función como objeto**, por lo tanto, **la función no es evaluada cuando creamos el evento**. Finalmente, guardamos el evento en la lista y con eso terminamos.

Pasará un tiempo, quizás se ejecuten otros eventos entre medio, pero eventualmente el evento que creamos antes será el próximo a sacar de la lista. En el momento en que sacamos este evento de la lista, actualizamos el tiempo de la simulación y **recién ahí** llamamos a la función que habíamos guardado, que en este caso es `crear_vehículo`. Entonces se ejecuta la función, creando primero el vehículo y luego programando (para el futuro) otra vez el siguiente evento de para crear un vehículo.

Puedes seguir preguntando si quedaron dudas al respecto,

Saludos!

**Comment by santilaguna** [comment]
Buena ahora entendí, gracias!!
