### ISSUE TITLE
duda sobre lista

### ISSUE THREAD

**Issue by asapsanchez** [IIC2233/Syllabus#491]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola, si estoy dentro de una función generadora, puedo crear una lista vacía para ir agregando entradas?

**Comment by diegobas10** [comment]
Hola buenas @asapsanchez, 
Mientras este dentro una función generadora como tu dices y se este usando por comprensión no debería haber problema, si lo haces fuera de la función probablemente la detecte el script de elementos prohibidos, por lo que te recomiendo ir revisando constantemente,, en la issue #463 hay más detalles.
Saludos, quedo atento a cualquier duda

**Comment by asapsanchez** [comment]
> Hola buenas @asapsanchez, Mientras este dentro una función generadora como tu dices y se este usando por comprensión no debería haber problema, si lo haces fuera de la función probablemente la detecte el script de elementos prohibidos, por lo que te recomiendo ir revisando constantemente,, en la issue #463 hay más detalles. Saludos, quedo atento a cualquier duda

Esta dentro de una funcion generadora, pero no estoy haciendo la lista por comprensión, aun esta permitido? y lo otro, los test de elementos prohibidos arrojara siempre que haya algo prohibido? osea si tengo todos los test buenos, significa que no estoy infringiendo en nada prohibido?

**Comment by diegobas10** [comment]
@asapsanchez yo tendría cuidado ahí con su uso, ya que ahí debería detectar que estás creando una lista vacía, pero si lo estas haciendo bien el test siempre debería arrojarte true. Otra cosa es que este test es definitivo y es el que se usara para revisar, por lo tanto mientras tengas solo True, y ningún False estarías cumpliendo, así que anda usándolo constantemente cuando tengas dudas.

**Comment by asapsanchez** [comment]
Diego, perdón, no entiendo mucho. Efectivamente estoy creando una lista vacía, sin uso de comprensión ni nada, defino lista = [], me dices que esto no esta permitido, pero los test de cosas prohibidas me sigue arrojando todo como True, que debo hacer?

**Comment by diegobas10** [comment]
@asapsanchez Disculpa había leído mal, dentro de una función generadora si se puede hacer el uso de la lista [], solo preocúpate que el test te salga true, ya que así puedes saber que estás trabajando de la manera esperada.
