### ISSUE TITLE
qthread no acepta start() correctamente

### ISSUE THREAD

**Issue by christianluer** [IIC2233/syllabus#491]
Hola tengo un problema con mi clase tiempo que es un QThread cuando la llamo por el método start() el modulo run(self) no es llamado y cuando cambio de nombre y llamo directamente el modulo el programa se cae. 
por favor ayuda!!

**Comment by jeschuwirth** [comment]
Hola!

Esto es un problema muy específico, por lo que es dificil de resolver, te recomiendo revisar que la función asociada al thread se encuentra sin paréntesis al final:
`x = threading.Thread(target=thread_function, args=(1,))`

en vez de 

`x = threading.Thread(target=thread_function(), args=(1,))`

 Si lo anterior no lo arregla manda un pantallazo de la parte donde tienes ese error, pero intenta minimizar el contenido que muestras en la issue.

Suerte!
