### ISSUE TITLE
Almuerzo de MiembrosUC

### ISSUE THREAD

**Issue by jcampino1** [IIC2233/Syllabus#491]
En el enunciado salen los porcentajes de almuerzos según las horas, después la distribución de llegadas al campus y después la distribución del instante en que cada persona irá a almorzar dependiendo de la hora en la que almuerza. 

Esta un poco confuso, podrían explicar como se relacionan estas 3 variables para ver como determinar la hora en que almorzará cada persona. 

Gracias.

**Comment by iqacevedo** [comment]
Hola,

La secuencia es algo así:

1. El miembroUc  primero tiene que llegar a la universidad, por lo que se debería ver su distribución de llegada al campus para saber cuando llega.
2. Todos tiene horas distintas de almorzar, ahí es donde están los porcentajes de almuerzo.
3. Dentro de cada bloque de almuerzo, pueden decidir ir a almorzar en cualquier momento de su intervalo, es ahí en donde ocupan la distribución que se indica en decidir ir a comer.

Si no queda claro, no dudes en preguntar de nuevo.

Saludos !

**Comment by rakarachon** [comment]
Hola, no entiendo muy bien lo de los porcentajes de almuerzo. ¿Da lo mismo como defina el X% de MiembrosUC que decide ir entre las 13 y 14 horas y el Y% que decide ir a almorzar entre las 14 y 15 horas? ¿Y una persona almorzará siempre en el mismo intervalo de tiempo o este puede cambiar cada día?

**Comment by mesantamaria** [comment]
Y qué pasaría si una persona está asignada a almorzar entre las 12 y las 13, pero llega a la universidad después de las 13?

**Comment by BeaGaete** [comment]
misma duda que @mesantamaria, de hecho algunos miembrosUC me salen con este conflicto, como se debe arreglar o puedo considerar que ese día no almuerzan?

**Comment by fedetaladriz** [comment]
Me sumo a la pregunta de @mesantamaria !

**Comment by Jiparavich** [comment]
x3

**Comment by iqacevedo** [comment]
Hola a todos, 
Lamento mucho la demora 😅
@rakarachon da lo mismo como defines quienes entran en ese porcentaje, pero una vez que lo decides debería mantenerse en el tiempo. En general las personas mantienen horarios regulares de almuerzo, por lo que no tiene mucho sentido que lo cambiaran todos los días.
@mesantamaria Acá tienes dos opciones igualmente válidas, puedes decidir que esa persona que llegó después de su horario de almuerzo simplemente no almuerce ese día, o bien puedes asumir que almorzará enunciado intervalo de los que está posterior a su llegada. Decidas lo que decidas, debes especificarlo en el README para que podamos evaluarte considerando tu decisión.

Quedo atento a cualquier comentario que tengan (ahora sí que si 🙈),
Saludos !

**Comment by rakarachon** [comment]
@iqacevedo perfect, muchas gracias!!

**Comment by movaldivia** [comment]
@iqacevedo Sobre eso "En general las personas mantienen horarios regulares de almuerzo" no lo hice así debería cambiarlo o solo especificarlo en el readme?

**Comment by iqacevedo** [comment]
@movaldivia si tienes una buena justificación de porque decidiste hacerlo de otra manera puedes dejarlo así y especificarlo en tu README porque decidiste hacerlo de esa forma. Sin embargo, debes considerar que nosotros evaluamos que el problema esté bien modelado, y que por tanto las consideraciones que tomaste tengan sentido. Por lo anterior ai no tienes un motivo que este muy bien argumentando te recomendaría que lo cambies para que no consideremos que está mal modelado.

Saludos ! 

Saludos !
