### ISSUE TITLE
Problemas con property en clases abstractas

### ISSUE THREAD

**Issue by rldelafuente** [IIC2233/syllabus#491]
Hola!

Siguiendo el ejemplo (_class Puente_) de la clase de properties y viendo en la clase de Clases abstractas, intenté hacer una property con clases abstractas, pero me indica error. Dejo el código de la clase, solo que cambié que heredé de la clase Construccion. (Esto lo subo como ejemplo, para ver cómo hacerlo en el caso de la tarea)

##Código:
```
from abc import ABC, abstractmethod
class Construccion(ABC):
    def __init__(self, maximo):
        self.maximo = maximo
        self.__personas = 0

    @property
    @abstractmethod
    def personas(self):
        pass

    @personas.setter
    @abstractmethod
    def personas(self, p):
        pass 

class Puente(Construccion):
    @property
    def personas(self):
        return self.__personas

    @personas.setter
    def personas(self, p):
        if p > self.maximo:
            self.__personas = self.maximo
        elif p < 0:
            self.__personas = 0
        else:
            self.__personas = p
```
AttributeError: 'Puente' object has no attribute '_Puente__personas'

Como que no reconoce self.__personas de la clase abstracta... :(

**Comment by jeschuwirth** [comment]
hola @rldelafuente,

Encuentro genial que estes practicando con los código de distintas clases y mezclandolos :D

Si no me equivoco solo te falta el super().\_\_init\_\_ en el inicializador de Puente.

Éxito!

**Comment by rldelafuente** [comment]
Hola! 

Me sigue indicando error, incluso con el super()    :(
(No lo había puesto antes porque en las clase de Clases Abstractas no se utiliza, en la estructura parte al tiro con los métodos). Puse esto, pero sigue indicando error.
```
class Puente(Construccion):
    def __init__(self,maximo):
        super().__init__(maximo)
```


'Puente' object has no attribute '_Puente__personas'

**Comment by jeschuwirth** [comment]
Luego de ver tu issue y jugar un rato con el código tuve que buscar información acerca de este problema.

En la issue #331 tienen el mismo problema, el ayudante @igbasly da una solución muy extensa y completa acerca de por que ocurre y como solucionarlo.

Si te quedan dudas o no funciona exactamente lo que explican puedes comentar en este issue y te ayudaré a solucionarlo.

Éxito!

**Comment by rldelafuente** [comment]
Si!!!! Me quedo más claro! Me quedó una duda eso si, pero la escribiré en la otra issue para seguir con la linea de la pregunta. 
Muchas gracias!
