### ISSUE TITLE
Importaciones que se llaman mutuamente

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2233/syllabus#492]
hola, tengo un problema.
Al hacer la tarea, en especifico los menús, me di cuenta que era muy largo hacerlo en un archivo así que lo hice mas  modular. El problema es que yo plantee los menús  como "funciones" que se llaman mutuamente (entre comillas para no decir mucho de como lo estoy haciendo) los ``import`` que se llaman mutuamente no funcionan. Aquí planteo una simplificación del problema:

Archivo:  uno.py
```
from dos import fun_2
from tres import fun_3

def fun_1():
   print(1)

```
Archivo:  dos.py
```
from uno import fun_1
from tres import fun_3

def fun_2():
   print(2)

```
Archivo:  tres.py
```
from uno import fun_1
from dos import fun_2

def fun_3():
   print(3)

```

Los imports se llaman entre ellos y arroja ``ImportError``
¿Como se resuelve esto?

**Comment by itmunoz** [comment]
Hola! Lo que estás haciendo es una importación circular, que es cuando dos o más archivos se importan mutuamente. Al realizar esto en Python tira error, y recomiendan no realizar esta práctica.
Te recomiendo que las importaciones que hagas no sean circulares, sino que sean lineales (si hay dos archivos, que solo uno importe cosas del otro).
