### ISSUE TITLE
almuerzo funcionarios

### ISSUE THREAD

**Issue by cfernandez9** [IIC2233/Syllabus#492]
Hola, en el enunciado explican:
"Almorzar: Todos los usuarios, tanto estudiantes como funcionarios, almuerzan todos los días. El X % **de los alumnos** almuerza de 13:00 a 13:59, el Y % almuerza de 14:00 a 15:00, mientras que el (100 − X − Y ) % lo hace de 12:00 a 12:59. Con respecto a los vendedores, en este mundo no comen. Los datos de X e Y se entregar ́an al inicio de la simulación."
Solo se muestra el horario de los alumnos...en qué horario o cada cuánto rato almuerzan los funcionarios?

**Comment by ifcarrera** [comment]
Hola, puedes asumir que se comportan de la misma forma los funcionarios y por lo tanto almuerzan a las mismas horas (con la misma frecuencia)

Saludos

**Comment by cfernandez9** [comment]
Muchas gracias!!!

Enviado desde mi iPhone
