### ISSUE TITLE
Conexión de señales en el main

### ISSUE THREAD

**Issue by nicolascamhi** [IIC2233/syllabus#492]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Cual es la forma correcta de conectar las señales? He visto ejempolos donde se crea una clase en el main y luego en distintos metodos se van conectando las funciones pero en otros ejemplos las conectan todas de una vez en el main sin crear ni clases ni funciones.

**Comment by mmunoz12** [comment]
Hola @nicolascamhi! No es que exista sólo una forma de conectar las señales por lo que las dos formas que tu dices están bien, depende de como prefieras armar tu código. A veces puede ser más cómodo crear una clase que al instanciar sus métodos permita conectar cada señal de manera más ordenada. También es posible conectar todo en el main sin crear clases ni funciones ya que al momento de que se envíe la señal, esta llegará al main en donde el `connect()` se encargará de conectarla con su respectiva función, por lo que no importa si están en “desorden” dentro de este. Avisame si te quedan dudas!

**Comment by nicolascamhi** [comment]
Muchas gracias! Pero como sería recomendable hacerlo para esta tarea? Creando una clase en el main o haciendolo sin funciones ni nada?

**Comment by mmunoz12** [comment]
La verdad es como se te haga más cómodo a ti. En lo personal yo prefería que a lo largo de mi código se enviaran todas las señales y que en el main se conectaran con sus funciones, sin crear clases en este. Pero eso, puedes hacerlo como más te acomode a ti siempre y cuando haya una correcta separación entre back-end/front-end para esta tarea.
