### ISSUE TITLE
Evento Bota de Ramo

### ISSUE THREAD

**Issue by JoseValencia125** [IIC2233/Syllabus#492]
Del enunciado:
> Bota de ramo: Al momento de recibir la nota de la cuarta actividad, el alumno analizará sus notas y la confianza que tiene en ese momento del curso dada la siguiente formula.
> s = Confianza * 0,8 + Notas * 0,2
>  Si s es menor a 20, el alumno decidirá botar el curso.

¿Por Notas se refiere al promedio o la suma simple de sus notas?
El problema es que por ejemplo si un alumno, mantiene su confianza de 12 y tiene solo 7 en las actividades (considerando notas como la suma) y las 2 primeras tareas
 s = 12 * 0,8 + 42 * 0,2 = 9,6 + 8,4 = 18
Es decir, sigue botando el ramo aun cuando tiene la confianza maxima inicial y solo ha tenido 7.0

**Comment by iqacevedo** [comment]
Hola
Considera la suma simple de sus notas, también debes considerar que la confianza del alumno va cambiando, imagina que ese alumno esperaba un 5.0 en una AC, pero se saco un 7.0, con esto su confianza debería aumentar `3 * (7.0 - 5.0) = 6` solo en esa AC. Finalmente, en este ejemplo solo con eso `s` aumenta en 4.8

Saludos !

**Comment by rfenzo** [comment]
Hola, no me quedo muy claro lo anterior,  "Notas" es la suma de todas las notas que ya le han entregado hasta la actividad 4 incluyendo la Tarea 1 y los controles?

**Comment by Jaluco** [comment]
Les pasa que casi todos botan el ramo aunque tengan promedio sobre 4.5?

**Comment by aeperalta** [comment]
Me pasa algo parecido. Mucha gente bota el ramo. Me tinca que es por el calculo de las notas esperadas. Me pasa que en las actividades, por lo general, suben su confianza y en las tareas la bajan mucho

**Comment by akaminetzkyp** [comment]
En mi simulación, el "s" de casi todos los alumnos era menor a 20, por lo que casi todos botaban el ramo. Bajé el límite de "s" a 3 y ahora lo bota un número razonable de alumnos (~30).
