### ISSUE TITLE
Clientes_despues_hora - Sobre test_cases_carga_datos

### ISSUE THREAD

**Issue by el-Jay-C** [IIC2233/Syllabus#492]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Tengo una duda sobre cases de la carga de datos. Resulta que probando el código me di cuenta que existen casos que se consideran correctos para el test case pero que no corresponde a las condiciones explicitadas en el enunciado. Quizás yo estoy entendiendo mal la pregunta, pero lo que entiendo yo es que piden que retornemos los id de aquellos que piden después del horario ingresado a la función y antes de las 00:00.

Sin embargo, analizando el test_case 0 (que ve la carpeta s) entrega como verdadero valores que no cumplen esta condición. Adjunto imágenes

![image](https://github.com/user-attachments/assets/fe7f2025-8c1f-4c62-8f3f-91d24d504e91)
![image](https://github.com/user-attachments/assets/8c30aac1-c16b-4375-b5cd-265a20218360)
![image](https://github.com/user-attachments/assets/13520c33-8cc8-4bac-9dcc-71c6626693a5)
Por ejemplo 4, 6 y 7 no cumplen la condición y están dentro de los resultados esperados (no están después de las 18:00)

Espero que me puedan ayudar porque llevo mucho tiempo intentando debuggear :worried:

**Comment by FradexMF** [comment]
Hola!
Por lo que veo puede que estés confundiendo el id_cliente con el id_pedido. Recuerda que se pide un string con los id de los clientes que hayan hecho un pedido después de la hora dada.

**Comment by el-Jay-C** [comment]
> Hola! Por lo que veo puede que estés confundiendo el id_cliente con el id_pedido. Recuerda que se pide un string con los id de los clientes que hayan hecho un pedido después de la hora dada.

Efectivamente era eso :dotted_line_face:. Muchísimas gracias!!
