### ISSUE TITLE
Duda cantidad de oro y  arboles

### ISSUE THREAD

**Issue by mmrodriguez5** [IIC2233/syllabus#492]
No entendí si es que pueden haber mas de uno de estos elementos a la vez en el mapa.
Agredecería mucho que me pudieran responder esta  pequeña duda.

**Comment by gatochico** [comment]
En teoría, si podría pasar :0. Las reglas de estos dos elementos son:
- Con cada día nuevo, aparece uno de cada uno en el mapa.
- Aparecen sobre celdas en especifico (espacios libres)
- Tienen una duración especifica en el mapa, regida por un parámetro para cada una.

En el caso donde la duración de alguno de estos elementos en segundos sobrepase la cantidad de segundos que componen un día (Ej: el oro dura 120 segundos en el tablero, pero el dia esta definido como 100 segundos), estaría la posibilidad de que haya más de un elemento de aparicion espontanea al mismo timepo en el tablero.

Espero haber respondido tu duda! :man_farmer:
