### ISSUE TITLE
metodos GUI

### ISSUE THREAD

**Issue by fpattillo** [IIC2233/Syllabus#493]
En el punto 3, dice que no debemos modificar la interfaz, esto se refiere a que no podemos cambiar Gui.py? Leí en otro issue que no podemos agregar metodos a main.py, solo modificarlos. En ese caso, supongo que con add_answer se refieren al que está en Gui.py, o no? 
En resumen, tendría que modificar add_answer, process_query y save_file en Gui.py, y process_query y save_file en main.py? 
Gracias!

**Comment by nachocontreras** [comment]
Hola!
Solo debes modificar process_query y save_file en main.py

**Comment by fpattillo** [comment]
Entiendo, entonces se modifican además los 3 de Gui.py?

**Comment by nachocontreras** [comment]
No se modifican los métodos en gui.py
😁

**Comment by fpattillo** [comment]
Ok! Muchas gracias!
