### ISSUE TITLE
inicializador en un reduce()

### ISSUE THREAD

**Issue by JPBarrosG** [IIC2233/Syllabus#493]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Puedo inicializar un reduce() con una lista que contenga elementos como esta?

![image](https://github.com/IIC2233/Syllabus/assets/142442997/3c830009-caf6-4592-9556-78e2750e65d7)

con el test de elementos prohibidos me dice que es valido pero no se si el test contempla este caso.

**Comment by diegobas10** [comment]
Hola buenas @JPBarrosG,
Si el test elementos prohibidos, te marca true es que si se puede usar, ya que estarías utilizando la lista por comprensión, igualmente procura que el test de elementos prohibidos te de true, ya que este es definitivo para la revisión, para más detalles esta la issue #339
Saludos

**Comment by JPBarrosG** [comment]
Entonces el uso del .append() y del .update() estan permitidos dentro de funciones? 
![image](https://github.com/IIC2233/Syllabus/assets/142442997/0d0a5cd6-1c1f-48a4-9b57-922b40b0d6bd)
que tengo esta funcion de aqui y el test me dio igual True, en ese caso confio solamente en el test para saber si voy bien

**Comment by diegobas10** [comment]
@JPBarrosG Si, mientras sean listas hechas por compresión se podrán usar estos métodos, confía en el test elementos prohibidos, también puedes revisar #298 para ver si los métodos están prohibidos en este caso, no lo están.
Saludos
