### ISSUE TITLE
Error al importar ventana hecha en qt designer

### ISSUE THREAD

**Issue by dammr54** [IIC2233/syllabus#493]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda y error de importación de una ventana hecha en qt designer 
No logro solucionar este error, he agregado imágenes utilizando el navegador de recursos de qt designer el archivo de recurso creado tiene el nombre de logo.qrc, en lo que logro entender puede estar relacionado con esto. 

![image](https://user-images.githubusercontent.com/80791048/119291051-cc244500-bc1b-11eb-9199-b22e2b64d5f1.png)

**Comment by Juampisaez** [comment]
Hola @dammr54
Puede ser que el problema es que no tienes el archivo .ui de tu ventana. Si subes tu repo es mas facil ayudarte :)
Quedo atento :)

**Comment by dammr54** [comment]
no entendí muy bien a que te refieres con subir mi repo, pero actualice lo que tengo en GitHub y aquí están las carpetas donde estoy trabajando
![image](https://user-images.githubusercontent.com/80791048/119358174-61542780-bc76-11eb-87ee-bcf3fc91d984.png)
![image](https://user-images.githubusercontent.com/80791048/119358194-6618db80-bc76-11eb-9171-2e05473ec5d4.png)

**Comment by Juampisaez** [comment]
Ya, revise tu repo y lo que esta ocurriendo es que las imagenes en designer las estas instanciado como resources.
![image](https://user-images.githubusercontent.com/48323752/119371096-0de8d600-bc84-11eb-9427-6d3ead179f1f.png)

Te recomendaría colocar las fotos con la segunda opcion de la imagen de arriba "choose file".

Prueba con eso, me avisas si no resulta :)

**Comment by gonzaga2000** [comment]
Yo tengo el mismo problema, y aunque la instancie como resources me sigue dando el mismo error. Alguna sugerencia?

**Comment by dammr54** [comment]
Revise en que parte podrían aparecerme las opciones que has mostrado de las imágenes pero no lo encontré,  la forma que estaba utilizando para agregar las imágenes a la ventana era crear el archivo de recurso, añadir un prefijo/ruta y agregar la imagen y subirla de la forma border imagen utilizando stylesheet para obtener esta en un tamaño que se pudiera escalar fácilmente. En ninguna parte me aparecen las opciones mostradas.

gonzaga2000 podrías probar usando la segunda opción que aparece arriba en la imagen ya que según lo que entendí al instanciarse como resources ocurre el problema.

**Comment by Juampisaez** [comment]
@dammr54  Ahi tal vez se cacha mas
![image](https://user-images.githubusercontent.com/48323752/119381873-4fcb4980-bc8f-11eb-926a-168e17c77d81.png)

Quedo atento :)

**Comment by gonzaga2000** [comment]
@dammr54  ocupe las palabras cambiadas jajajaja. Pero ya cache mi error, como antes tenia imagenes instanciadas como resources, tenia que primero borrar todos esos resources y después instanciarlas como files.

**Comment by dammr54** [comment]
Buena muchas gracias ya pude abrir la ventana! :D, otra pregunta, al cargar los archivos de esta forma y subir mis archivos al repositorio a la hora de que lo revisen no ocurren problemas con los directorios ?

**Comment by Juampisaez** [comment]
@dammr54 
La verdad es que mientras tengas las carpetas que te entregamos en el mismo lugar, no deberian ocurrir problemas. Eso si, recuerda que debes subir los archivos .ui a la repo, todo lo que crees para tus ventanas debe estar.

Espero quede claro :)
