### ISSUE TITLE
Función Putrefacción

### ISSUE THREAD

**Issue by nachocontreras** [IIC2233/Syllabus#493]
La función `putrefaccion(t) = e ** (- t / tasa)` , puede que esté mal definida ya que en t=0, cuando recién se genera el producto, tiene putrefacción= 1, generando que su calidad, definida como `calidad(t) = (calorias * (1 - putrefacción(t)) ** 4) / (precio ** (4/5))`, entrega un valor de 0.

Por lo tanto, no sería mejor definir `putrefaccion(t) = 1 - e ** (- t / tasa)`, para que así los productos sean de calidad 😄  ??

**Comment by cilopez** [comment]
Estás en lo correcto :sweat_smile: , dentro de poco solucionaremos estos problemas en el enunciado, disculpas

**Comment by nachocontreras** [comment]
Gracias!!
