### ISSUE TITLE
orden delegaciones.csv

### ISSUE THREAD

**Issue by notyourlasagna** [IIC2233/syllabus#493]
Hola! En el enunciado dice que el header del archivo delegaciones puede cambiar, alterando el orden en que se presentan los datos de cada delegación por linea. Pero, puedo asumir que después del header siempre se presentará primero la información de IEEEsparta y luego en la siguiente linea la de DCCrotona?

**Comment by jitorcas** [comment]
Hola! @notyourlasagna 

No puedes asumir el orden en que se entregarán las Delegaciones. Puedes identificarlas por el nombre que aparece en cada línea. 

Mucho éxito! 🏅
