### ISSUE TITLE
test_02_cantidad_vendida_de_pizza_por_tipo_correctitud 

### ISSUE THREAD

**Issue by mxmauoc0** [IIC2233/Syllabus#493]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Test número 3

Primero, el test 02 de carga de datos esta perfecto, todo bien, luego, los 3 primeros test del de correctitud tambien todo bien, pero el último? SIEMPRE FALLA. Trate de usar listas por comprensión, la función reduce(), la función sum(), trate de iterar sobre los generadores y no hay chance. Por si se lo preguntan, si, para filtrar por tipo de pizza corrobore que fuera correcto, usando el mismo algoritmos que use en la primera función (slicing).

 :( **¿ Podrían orientarme un poco para saber donde podría estar mi error?**

Muchas gracias        ╯︿╰

![image](https://github.com/user-attachments/assets/984f393e-5413-487b-9527-a399fdd69800)

**Comment by mane6867** [comment]
Hola! revisando el test pareciera ser que no estás tomando en cuenta las pizzas "Pepperoni Falsa_XL", viste esta posibilidad?

**Comment by mxmauoc0** [comment]
> Hola! revisando el test pareciera ser que no estás tomando en cuenta las pizzas "Pepperoni Falsa_XL", viste esta posibilidad?UUU tienes toda la razón... por eso mi slicing falla, muchas gracias :)))
