### ISSUE TITLE
Base de Datos con json

### ISSUE THREAD

**Issue by ByronHidalgo1** [IIC2233/syllabus#493]
Hola, al hacer una base de datos en formato json, luego de utilizar dump en el Servidor, se me guarda algo así :
{
    "Type": [
        {
            "A": "hola",
            "B": 1,
            "C": "-"
        },
        {
            "A": "hola2",
            "B": 1,
            "C": "-"
        }
    ]
}
###################################################################
El problema es que al cerrar el servidor, no puedo volver a guardar de la misma forma utilizando append, puesto me queda algo como:

{
    "Type": [
        {
            "A": "hola",
            "B": 1,
            "C": "-"
        },
        {
            "A": "hola2",
            "B": 1,
            "C": "-"
        }
    ]
}{                  
    "Type": [
        {
            "A": "hola3",
            "B": 1,
            "C": "-"
        },
        {
            "A": "hola5",
            "B": 1,
            "C": "-"
        }
    ]
}
Lo que no podré abrir utilizando load. Tampoco quiero usar 'w' en vez del append, pues la idea no es sobreescribir la base de datos. ¿Alguien me puede guiar por favor?

**Comment by gatochico** [comment]
Hola! :cat:

Por lo que entiendo, estarías ocupando el modo "a" al momento de abrir tu archivo del servidor y actualizarlo. El problema con eso es que efectivamente, en ese modo comienzas a escribir justo después de la última línea del archivo, que en este caso es la que cierra el diccionario y genera el problema que mencionas. Por lo tanto, escribir en modo _append_ no te servirá si quieres lees luego tu base con _load_.

Tu mejor opción para escribir un archivo compatible con las funciones _load_ de json sería reescribir la base completamente de nuevo (con 'w') cada vez que necesites actualizarla, tomando en cuenta que debe haber permanencia de información, por lo que debes encontrar una forma de también incorporar siempre los datos ya existentes a tu nueva base. La otra opción sería simplemente elegir otro formato que no sea json para escribir tu base! (A menos que la parte que estés haciendo pida explicitamente un .json).
Saludos!
