### ISSUE TITLE
Abrir ventana de Tienda

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2233/syllabus#493]
Hola, tengo un problema...

`def abrir_tienda(self, salir):

        tienda = Tienda(self.ruta_mapa)
        pertenencias.senal_actualizar_dinero = tienda.senal_actualizar_dinero

        if salir == "Salir":
            tienda.hide()`

ese es un metodo conectado a una señal que me avisa cuando el personaje se situa sobre la tienda para abrir la ventana, cuando me paro en la tienda con el personaje, la ventana de la tienda parpadea, es otras palabras, se abre y se cierra al instante, porque pasa esto y que puedo hacer ???.

De antemanos muchas gracias.

**Comment by aljara97** [comment]
Hola, podrías subir tu código para ayudarte a detectar tu problema? :eyes:

**Comment by DiegoPibe** [comment]
ya lo logre, graxx de todos modos
