### ISSUE TITLE
Agregar datos al mostrar estado

### ISSUE THREAD

**Issue by drosselot** [IIC2233/syllabus#493]
Hola, cuando el DCC muestra los datos, puedo agregar algunos? Para no hacer tantas funciones parecidas, prefiero hacer una que muestre todos los datos de una criatura.

**Comment by matiasmasjuan** [comment]
Hola @drosselot !

Si, puedes **agregar** algunos datos en la acción del ***DCC: Mostrar estado de Magizoólogo y DCCriaturas*** **siempre y cuando** cumplas con **todas** las peticiones **mínimas solicitadas** en el enunciado. Además, no olvides notificar en tu **README** sobre esta modificación.

Saludos y mucho éxito con tu tarea! 😄

**Comment by drosselot** [comment]
Vale, gracias
