### ISSUE TITLE
Renombrar archivo y luego subirlo a GitHub

### ISSUE THREAD

**Issue by jaimecoloma** [IIC2233/syllabus#494]
Hola! Tengo un archivo que quiero cambiarle el nombre pero me entró la duda si al momento de subirlo a github, como ya habia subido preliminares de este, se va a subir un segundo archivo (el renombrado) o bien se va a actualizar el nombre en el repositorio. Quiero saber esto para evitar problemas torpes jaja espero el comentario :)

**Comment by jeschuwirth** [comment]
Hola @jaimecoloma,

No hay problema con renombrar un archivo usando github, tienes dos opciones: puedes hacer lo siguiente:
`git mv <nombre_antiguo> <nombre_nuevo>`

o simplemente borrar el archivo y luego agregarlo nuevamente como si fuera un archivo nuevo:
1. mover archivo a otra carpeta
1. `git rm <nombre_antiguo>`
1. mover archivo al repositorio
1. cambiar nombre al archivo
1. `git rm <nombre_nuevo>`

En cualquiera de los dos casos luego  debes hacer commit y push

Éxito!

**Comment by jaimecoloma** [comment]
@jeschuwirth muchas gracias!
