### ISSUE TITLE
se debe resetear a un archivo vacío resultados.txt cada vez que se inicia una DCCumbre Olímpica?

### ISSUE THREAD

**Issue by notyourlasagna** [IIC2233/syllabus#494]
Hola! quería preguntar si se debe resetear a un archivo vacío, es decir, sin información, resultados.txt cada vez que se inicia una DCCumbre Olímpica. Si inicio el programa y juego 3 simulaciones, solo guardo la informarción de la ultima? o guardo las 3 cumbres? o guardo todas las cumbres que se jueguen en el computador?

**Comment by itmunoz** [comment]
Hola! Como no aparece especificado en el enunciado, no es obligatorio resetear el archivo en una nueva simulación. Cualquier cosa  que decidas, te recomiendo que lo expliques en el README para que no haya confusión a la hora de corregir.
