### ISSUE TITLE
Confusión con test elementos prohibidos

### ISSUE THREAD

**Issue by Yeps3nM** [IIC2233/Syllabus#494]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!Estaba revisando si mi código pasaba los test de elementos prohibidos y me salió que en el test de 'animal_mas_viejo_edad_humana' yo hacía uso de list, sin embargo no usé en ningún minuto ese comando en la línea que establece. Entonces no sé que hacer, el código está en mi repositorio por si pudiesen mirarlo. Muchas gracias

**Comment by SSParzival** [comment]
Hola buenas, revisé tu código y el problema está en que en la línea 175 de `consultas.py` usas `[...]`, que el test de elementos prohibidos detecta como equivalente a usar `list(...)`.

Te recomiendo investigar otra manera de hacer algo similar a lo que estás haciendo, pero sin usar `[...]`.

**Comment by Yeps3nM** [comment]
Entiendo, pero no me queda claro porque estaría prohibido si dentro de los comandos prohibidos esta situación no se encontraba nombrada, y además está dentro de un diccionario por comprensión. 

Gracias por la pronta respuesta!

**Comment by SSParzival** [comment]
Si bien el diccionario por comprensión creado es permitido, lo que indica el enunciado es que no se puede crear una lista a menos que sea por comprensión, y al hacer `[...]` en tu caso dicha lista no es creada por comprensión, lo que conlleva el no pasar el test de elementos prohibidos.

**Comment by Yeps3nM** [comment]
Comprendo, muchísimas gracias :) !
