### ISSUE TITLE
Duda sobre reubicar los assest dados

### ISSUE THREAD

**Issue by FranciscoPintoo** [IIC2233/syllabus#494]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola. Para poder organizar mejor la modulación de frontend y backend guarde todos los assest dentro de una carpeta y esta carpeta dentro de la carpeta frontend. El gitignore va a hacer que no se suban todas esas carpetas y por ende los path que utilizare no servirán con el orden que daban de base. ¿Qué hago para arreglar esto, subo las carpetas o puedo agregar un readme que explique cómo quiero que reordenen las carpetas? (Esta duda es válida tanto para el avance como para la tarea final).

**Comment by MatiasDuhalde** [comment]
Hola @FranciscoPintoo ! 

Es válido el tipo de estructura/orden que propones de las carpetas, y de igual manera debes preocuparte de ignorarlas mediante tu `.gitignore`, y que no se suban a tu repositorio en GitHub. Si bien en general lxs ayudantes podemos inferir la ubicación de los archivos a partir de las rutas encontradas en el programa, siempre es mejor dejarlo bien claro en el README de tu tarea (tanto para el avance como para la entrega final), en la sección de `Ejecución`.
