### ISSUE TITLE
Enviar dos mensajes seguido a mi cliente

### ISSUE THREAD

**Issue by bpeirano1** [IIC2233/syllabus#494]
Hola!
Si para mi clase cliente tengo implementado un método "escuchar" el cual recibe los mensajes del servidor y el cual funciona en base a un thread. Entonces si yo le envió dos mensajes seguidos  a mi cliente desde el servidor, podría esto generar un problema al método escuchar?
Porque estoy teniendo un problema al enviar dos mensajes seguidos y es única explicación que se me ocurre. Y si es así como podría solucionarlo? (yo creo que con un lock pero no sabría bien como implementarlo)

Saludos!

**Comment by marioreinike** [comment]
Hola @bpeirano1 !
Si tu método escuchar del cliente está bien implementado (es decir, recibe la cantidad justa de datos según el largo del mensaje), entonces al recibir dos mensajes seguidos no debería haber problema, ya que recibe uno primero, ejecuta su comando respectivo y luego recibe el otro. Si estás trabajando con más de un thread en el cliente, entonces deberías usar locks si crees que hay conflictos en el acceso a alguna estructura de datos que puedan estar modificando al mismo tiempo. Saludos!
