### ISSUE TITLE
¿Que objetos se pueden vender?

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#494]
Es necesario poder vender el hacha o las semillas?

**Comment by gatochico** [comment]
Hola!

En teoría, deberías poder vender cualquier objeto que esté en tu inventario, así que sí :0 . Puedes tomar como valores de venta para los elementos que no lo poseen (como la azada, o semillas) su mismo precio. Ej: Semilla vale 20, se vende también por 20. 

Saludos y éxito!

**Comment by dgzmr** [comment]
Gracias
