### ISSUE TITLE
Duda sobre reciclar material entregado en el curso

### ISSUE THREAD

**Issue by benjaalfoncho** [IIC2233/syllabus#495]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda 

Hola! tengo una duda con respecto a reutilizar código que fue entregado o es elaboración propia en las actividades tanto formativas y/o sumativas del curso. ¿Está permitido? Pregunto para usar los códigos que generan ventanas y ese tipo de cosas que son más simples y menos variantes de programar.

**Comment by pabloist** [comment]
Hola buenas :)!

Es posible utilizar material tanto propio como el que les entregamos (actual o de otros semestres) **siempre y cuando** se indique de forma explícita en el README.

Espero te haya servido, saludos!

**Comment by benjaalfoncho** [comment]
Perfecto! muchas gracias!
