### ISSUE TITLE
Actividad 8 no fue recogida

### ISSUE THREAD

**Issue by ciquezada** [IIC2233/Syllabus#495]
Hola, quiero saber a quien puedo preguntar sobre este error, porque la actividad 8 la subí como 10 minutos antes que se acabara el tiempo, pero en la issue de la actividad aparece en blanco el commit a revisar

**Comment by jmwielandt** [comment]
La subiste tú y tu compañero?
Si es así, entonces a tu compañero le sale el commit
Cuenta como entregado que exista la carpeta AC08 en tu repo/Actuvidades/.
#NoSoyAyudante

**Comment by ciquezada** [comment]
yo la subí, por eso pregunto con quien puedo hablar para saber qué pasó

**Comment by ciquezada** [comment]
Gracias!!

**Comment by matthers3** [comment]
Hola, todavía tengo el mismo problema y quería preguntar si mi actividad fue recogida.  Muchas gracias!

**Comment by mblejeune** [comment]
Hola! Mi compañero también la subió, Santiago Laguna, y quería saber si ocurrio tambien este error o no, gracias!

**Comment by flobarrios** [comment]
Hola! tal como dijo @tomasrivera hubo un error en la publicación de las issues. @matthers3 si se recolectó tu actividad, @mblejeune te respondí en tu issue!. Entre hoy y mañana se les publicará el commit que fue recolectado. 

Saludos!!
