### ISSUE TITLE
Duda sobre colisiones al corregir

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#495]
Que tan estrictos van a ser en la corrección con respecto a las colisiones?
Por ejemplo, mi programa lo tengo hecho por ahora de forma que el "hitbox" de mi personaje está arriba a la izquierda del sprite, es decir, esta parte del sprite es la que puede colisionar con rocas. Esto significa que en algunos momentos se puede observar que el personaje está encima de una roca debido a que el personaje no tiene hitbox en los pies, pero las colisiones funciona bien con respecto al hitbox de la cabeza.
Está bien como lo tengo o es necesario que nunca se pueda ver alguna parte del personaje sobre una roca? adjunto 2 fotos, la primera es un ejemplo de colisión si se intentara avanzar a la derecha, la segunda muestra como a veces puede parecer que el personaje está sobre una roca.
https://imgur.com/a/sl2hd3s

**Comment by gatochico** [comment]
Hola! 

Si tu programa se comporta como en la segunda foto, el manejo de colisiones se consideraría como incorrecto :( La idea es que en ningún momento, ninguna parte del sprite del personaje "tape" al sprite de alguno de los elementos con los que se considera que hay colisión, como las piedras. La primera foto que mandaste sería un correcto manejo de colisiones.

Éxito con la tarea!! :cat:

**Comment by FelipeA7** [comment]
Intenté arreglarlo y llegué a esto: https://imgur.com/a/FTFpdYn
(Si intento avanzar hacia arriba no deja pues hay una colision)
Esto está bien cierto? O el espacio entre el personaje y la roca es mucho?

**Comment by gatochico** [comment]
Hola,

Revisando de manera más detallada las issues, para esta tarea se permitirá también que pongas tu punto de referencia en **los pies** del personaje y en ese caso se podrán permitir colisiones entre los sprites y el del personaje. Lamento la confusión, y he editado la respuesta anterior para reflejar el cambio.

Aún así, tu idea inicial tenía el error que tomabas el punto de colisión como la esquina superior izquierda, en vez de los pies del personaje, para que lo tengas en cuenta si decides revertir tu calculo de colisiones a la forma anterior que tenías!

Ahora, si deseas seguir implementando un manejo de colisiones donde los sprites **nunca** se sobrepongan, también es válido :tada:

En general, se habla de tanto tu pregunta inicial como el comentario que acabas de poner en la issue #391 de forma mucho más detallada e incluso con imágenes. Te recomendaría leerla con detalle y preguntar si algo no te queda claro en esta o esa issue.

Quedamos atentos! :eyes:
