### ISSUE TITLE
Realizar nueva simulacion

### ISSUE THREAD

**Issue by sebastianbreguel** [IIC2233/syllabus#495]
Hola, tenia la duda de si una vez terminados los dias de competencias, que es lo que debemos mostrarle al usuario y con una nueva simulacion se refiere a partir todo desde 0 tanto los atributos de los deportistas y delegacion o con los cambios de la simulacion anterior. 

Tambien si la nueva simulacion debe ser escrita en el resultados.txt siendo agregado como una dia mas o tiene que partir de 0 el archivo.

**Comment by hsazos** [comment]
¡Hola @sebastianbreguel !

Una simulación no debería modificar el comportamiento de la otra, por lo que los cambios no se guardan. Partes desde 0 la nueva simulación. Con respecto a lo de resultados.txt, lo dejamos a tu criterio, pero trata de explicarlo en el readme para entender mejor tu archivo de resultados. En la sección 3.2.2 de la tarea esta la respuesta a tu primera pregunta.

¡Animo con la tarea!🦕
