### ISSUE TITLE
Documentacion 

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#495]
Me preocupa que tan documentado debe estar todo, porque por ejemplo si yo tengo la clase auto y esta tiene el atributo patente como en el ejemplo del enunciado, ¿Es tan necesario especificar que es y que tipo de dato es? Ya que en algunos casos, como ese, me parece que es bastante obvio, tal vez no el tipo, ya que podría ser un objeto patente o simplemente un string, lo cual entiendo, pero si su significado como concepto.

Ademas no me queda claro si es obligación ocupar el formato de argumentación dado en el ejemplo, ya que perfectamente se podría hacer un poco menos formal y rígido y dejar igual de claro que es o que hace cierta cosa. Encuentro poco tedioso andar siguiendo un formato especifico como el del ejemplo, aparte porque la tarea es larga y no hay tanto tiempo de explicarlo todo con lujo de detalles.

Entiendo y comparto totalmente lo de **dejar claro de forma ordenada** que hace cada cosa, pero creo que es un poco pasado de la raya seguir lo del ejemplo al pie de la letra, no se si piensan lo mismo.

**Comment by iqacevedo** [comment]
Hola!

Se conversó y finalmente se decidió que deben seguir el formato especificado. Sin embargo pueden no documentar todo, basta con que tengan documentado al menos un 80% de sus métodos, clases y funciones.

Saludos !
