### ISSUE TITLE
paciencia funcionarios

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#495]
los funcionarios también tienen un límite de paciencia?

**Comment by rakarachon** [comment]
Me sumo a la duda y agrego otra: los funcionarios también deben verificar el stock del puesto _antes_ de ponerse a la cola? o da lo mismo?

**Comment by cilopez** [comment]
No, los funcionarios se van cambiando según el _stock_ únicamente, si en el caso hipotético un funcionario no alcanza a almorzar debido a que ha esperado mucho rato, este en el último instante que le queda para comer se va a _Quick Devil_ y almuerza inmediatamente.

**Comment by cilopez** [comment]
@rakarachon considera que si revisan el stock

**Comment by rakarachon** [comment]
@cilopez perfect, gracias!
