### ISSUE TITLE
T3 duda sobre creacion de elementos prohibidos

### ISSUE THREAD

**Issue by jagitbo** [IIC2233/Syllabus#495]
* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Por lo escrito en el enunciado entiendo que no se pueden crear listas o sets o diccionarios,
sin embargo no se menciona que no se puedan hacer contadores o bools, por lo tanto podria ocuparlos?

por ejemplo escribir

c= 0

if...:
c+=1

o escribir

c= False

if...:
c=True

por ultimo no entiendo si puedo sacar una lista de un generador con list(generador_a)

gracias de antemano

**Comment by Julius9** [comment]
Hola! respecto a tus dudas:

1. Si puedes utilizar contadores o booleanos, pero no puedes utilizarlos dentro de un ciclo `while`o `for` ( a menos que estés dentro de `map`, `filter`, `reduce` o una función generadora)
2. Si puedes obtener una lista a partir de un generador de la forma en que menciona o también en la forma `[x for x in generador]`
