### ISSUE TITLE
Cantidad salas iniciales

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#495]
Hola, puedo asumir que mi servidor parte con cierta cantidad de salas iniciales al iniciarse? Si es así, puedo asumir que el jefe de la sala será el primero en unirse?

**Comment by jeschuwirth** [comment]
Hola,

Al abrir un servidor no comienza con ninguna sala.

El primer cliente en conectarse debería ver que no existe ninguna sala y tiene dos opciones:

- Apretar el botón crear una nueva sala
- Esperar a que llegue otro cliente y éste cree la sala, por lo que el menú de salas del primer jugador se va a actualizar y debería ser capaz de unirse.

Ojalá haya aclarado tus dudas.

Suerte !
