### ISSUE TITLE
Descuento en las notas

### ISSUE THREAD

**Issue by josemlira** [IIC2233/Syllabus#496]
Hola! en el enunciado el coordinador puede descontar 5 décimas a las notas y esto lo puede hacer de 0 a 3 veces en el semestre, por ejemplo puede subir con descuento 3 tareas, 3 controles y 3 actividades o se refiere a que puede subir como máximo 3 evaluaciones entre tareas, controles y actividades con descuento? 
Otra duda que tengo es que dice que va a quitarle el descuento a la nota en la próxima subida de notas, pero esta próxima subida de notas tiene que ser del mismo tipo de evaluación? por ejemplo si el ultimo descuento fue realizado en una tarea y la próxima nota que se sube es la de una actividad, ahí debería arreglarse la nota o hasta la próxima subida de nota de tarea?

**Comment by nivek0o0** [comment]
Lo que yo entiendo del enunciado es que se refieren a evaluaciones en general, por lo que yo lo programé como 3 descuentos en total que se eliminan en la próxima subida de cualesquiera evaluación.

**Comment by Hernan4444** [comment]
Con evaluaciones es a modo general. Cuando el coordinador suba cualquier nota puede haber descuento y cuando sube la siguiente se arregla ese descuento. Lo esperado es tal como entendió @nivek0o0.

Saludos!!

**Comment by josemlira** [comment]
Muchas gracias!!!
