### ISSUE TITLE
Limite de lineas

### ISSUE THREAD

**Issue by Afro27** [IIC2233/syllabus#496]
Si la clase de mi ventana de juego por si sola tiene mas de 400 lineas, es posible crear las funciones en otro modulo y despues de alguna forma heredarselas a la clase de la ventana de juego para ahorrar lineas?

**Comment by lily416** [comment]
Es posible hacerlo, pero debes tener cuidado al dividir tu código.
 
Cuando dividas tu código trata de hacerlo de forma lógica (i.e. funcionalidades) y ve probando constantemente tu código, ya que si falla y por eso no se puede corregir no tendría sentido evitar el descuento de las 400 líneas.
 
Saludos y éxito en tu tarea 👋🌾
