### ISSUE TITLE
Cantidad de /chao simultáneo

### ISSUE THREAD

**Issue by cristobalwelch** [IIC2233/syllabus#496]
Hola!

Dado que en el enunciado no se especifica, puedo asumir que solamente va a existir una votación contra un jugador a la vez? Es decir, que no se pueda votar para expulsar a más de un jugador al mismo tiempo.

Gracias !

**Comment by jeschuwirth** [comment]
Saludos,

El enunciado no dice nada al respecto, pero al utilizar el comando \chao [nombre_jugador], tienes el nombre del jugador que se quiere "kickear" de la sala, por lo que podrían haber dos votos simultáneos a distintos jugadores.

Como no es tan complejo mejorar tu algoritmo a más de un jugador, te diría que **si** pueden haber votos simultáneos.

Suerte en la tarea!

**Comment by jeschuwirth** [comment]
[Corrección del comentario anterior]
Al final los votos simultáneos quedan a tu criterio, pero recuerda especificarlo en el readme. Para más información del comando lee la siguiente issue #470
