### ISSUE TITLE
Horarios almuerzo

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#496]
Hola, 

en el enunciado sale que:
Almorzar:
   X: almuerzan de 13 a 14 (13:59)
   Y: almuerzan de 14 a 15
   Resto: almuerzan de 12 a 13 (12:59)

Decidir ir a comer:
   parametros μ = X:10
   X puede ser 13, 14 o 15

Pero aqui falta el grupo que valla a comer de 12-13 o sobra el grupo que va a comer con parametro X=15 (porque este grupo iría a comer entre 15 y 16)

Cual es? O entendi mal el enunciado? 

Gracias

**Comment by NotSimple** [comment]
#477

**Comment by Kitaps** [comment]
Oh sry no la encontré,
gracias
