### ISSUE TITLE
tamaño ventana e imagenes QTdesigner

### ISSUE THREAD

**Issue by barbaracalderonr** [IIC2233/syllabus#496]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x]Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x]Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
*[x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola!; tengo un problema al añadir las imágenes en QTdesgigner, cuando agrego una imagen(label) a un Layout,  se agranda demasiado la ventana, y cuando la visualizo me queda una ventanas gigante, ni siquiera me deja ajustarla a la pantalla... estuve tratando de ajustar los tamaños de la ventana y de la imagen pero no me resulta bien, hay alguna forma de solucionar esto?

**Comment by JadrinaDA** [comment]
Hola! Para la imagen estás usando setScaledContents? Esto debería fijar el tamaño de la imagen al del label que la contiene. También podrías usar setFixedSize en la ventana para que esta siempre quede del mismo tamaño (también puedes intentarlo para el label).  Probablemente la imagen se está estirando para llenar el layout y para mantener las proporciones tiene que ser muy grande. Avísame si te sirve y si no me puedes decir cual ventana es para revisar tu código.
Saludos.

**Comment by barbaracalderonr** [comment]
Muchas gracias!, me resultó usar el setFixedSize!
