### ISSUE TITLE
Duda acerca de "tupla" en función sort

### ISSUE THREAD

**Issue by BenjaCarrill0** [IIC2233/Syllabus#496]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/396)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/395)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Me surgió una duda acerca de si es posible usar "tuplas" en las funciones sort, por ejemplo si tengo una lista definida como `a = [(1, 2), (2, 44), (3, 1), (1, 3)]` y quiero ordenarla de forma ascendente según el primer elemento, pero en caso de que sean el mismo, que sea de forma descendente según el segundo elemento. Ahí haría `a.sort(key = lambda x: (x[0], -x[1]))` para que quede `a = [(1,3), (1,2), (2, 44), (3, 1)]` ¿El `(-x[0], x[1])` cuenta como crear una tupla o si se puede usar?

**Comment by jrodriguezluna** [comment]
Creo que preguntarón algo similar en la issue #424

**Comment by sofialarrain** [comment]
Hola @BenjaCarrill0! Como bien dice @jrodriguezluna esta pregunta fue respondida en la issue #424. Mucha suerte!

**Comment by BenjaCarrill0** [comment]
Ya gracias, había pasado por alto esa issue
