### ISSUE TITLE
Definir una función en parametros, solo para que me entregue un parametro

### ISSUE THREAD

**Issue by drosselot** [IIC2233/syllabus#496]
Hola, por un tema de que en mis distintos módulos, a veces se llaman recursivamente, me sale un error. Una solución que encontré en Internet, es no importar los módulos que me causan problemas al principio del código, sino que solo cuando lo necesite. Los módulos que me están causando problemas son el de clases y parámetros. Por esto, ya que en clases necesito parámetros todo el rato (mientras que en parámetros solo uso el módulo clases una vez), quería saber si podía definir un parámetro como función, para así no tener este problema. Aún no se si esto me lo solucione, pero quería saber igual si podía hacerlo.

**Comment by jeschuwirth** [comment]
Holaa @drosselot,

Tienes varios temas que quiero comentar en tu issue:

1. Los `import` deben ir al **inicio** de tu código, esto es una buena práctica ya que te permite saber inmediatamente que librerías o modulos ocupa cada uno de tus archivos.

1. `parametros` no debería importar un modulo tuyo, a lo más debe importar alguna librería como `math` o `random`, si esta importando clases probablemente no estés ocupando parámetros correctamente.

1. No deberías definir un parámetro como función, si quieres importar una función de otro archivo puedes crear un nuevo módulo con esa función y luego importarlo.

Éxito!

**Comment by drosselot** [comment]
¿Y no puedo dejar como parámetro una lista de alimentos? Como los alimentos son iguales durante todo el código, pensé que era pertinente. Sería un problema si no puedo :(

**Comment by jeschuwirth** [comment]
@drosselot,

El problema de lo que comentas es que todos tus alimentos iguales van a ser la misma instancia del alimento, por lo tanto si tienes

```
alimento1 = TartaMelaza()
alimento2 = HıgadoDragon()
alimento3 = BunueloGusarajo()

alimentos = [alimento1, alimento2, alimento3]
```

Luego, si por ejemplo el efecto de salud de una tarta de melaza aumentar en 5 por alguna razón, todas las tartas de melaza en tu código van a aumentar su efecto de salud en 5. Lo que deberías hacer es instanciar (llamar a la clase) el alimento cada vez que lo crees, de ese modo puedes alterar sus valores sin cambiar los valores de todos los otros alimentos iguales.

Espero se entienda porqué no es recomendado usar clases en parámetros para este caso, sino puedes seguir comentando las dudas.
