### ISSUE TITLE
2 generadores, total ahorrado pedidos

### ISSUE THREAD

**Issue by danogajardo** [IIC2233/Syllabus#496]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

hola, al momento de ejecutar los testcases de carga de datos me fallan todos por muy poco (432251 != 432248 o 432251 != 432248 por ejemplo), no sé si esto se da por la perdida de precision al multiplicar por floats (como en una issue anterior), en ese caso queria saber si me pueden indicar el orden a realizar las multiplicaciones para que coincida con lo esperado, o si es simplemente que me equivoque en la forma de calcularlo.

**Comment by mane6867** [comment]
Hola!, estás teniendo un problema en el momento en el que haces el redondeo, este debe hacerse una vez en la función, específicamente al finalizar todos las multiplicaciones y sumas correspondientes ( _en el return por ejemplo_), quedo atenta por si te funciona!

**Comment by vicenciomf2** [comment]
También me había pasado, gracias por la ayuda

> Hola!, estás teniendo un problema en el momento en el que haces el redondeo, este debe hacerse una vez en la función, específicamente al finalizar todos las multiplicaciones y sumas correspondientes ( _en el return por ejemplo_), quedo atenta por si te funciona!

**Comment by mane6867** [comment]
Hola @benjadelgado!, revisé tu código y al retornar debes utilizar solo round, no int. Espero que te haya ayudado!

**Comment by carlosriffo** [comment]
Hola, yo tengo el mismo problema pero solo con los testcases de los tamaño S. Hago el redondeo al final pero el valor se redondea hacia abajo, quedando con una unidad menos.

**Comment by mane6867** [comment]
Hola @carlosriffo, revisé tu código y te recomiendo acumular el ahorro total en una sola variable en lugar de usar un diccionario para almacenar los ahorros por cada pizza. En cada iteración, calcula el ahorro y súmalo a esta variable. Ve si esto te funciona!

**Comment by carlosriffo** [comment]
@mane6867 me salió al tiro. Gracias!

**Comment by Yakao01** [comment]
Hola, me pasó lo mismo, solo que en todas las cargas, aunque sigue siendo por muy poco, es una diferencia de 5, 7 y 2 en los L, M, S respectivamente. Además, también me sucede en el 4 y el 2 de correctitud con una diferencia de 1.

**Comment by mane6867** [comment]
> Hola, me pasó lo mismo, solo que en todas las cargas, aunque sigue siendo por muy poco, es una diferencia de 5, 7 y 2 en los L, M, S respectivamente. Además, también me sucede en el 4 y el 2 de correctitud con una diferencia de 1.

Hola @Yakao01 revisando tu código veo que al final lo resolviste no?

**Comment by Yakao01** [comment]
@mane6867 sip, muchas gracias por revisarlo!
