### ISSUE TITLE
usar self para atributos de clase?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#497]
En la ayudantía herencia (si mal no recuerdo), vimos que se podrían crear atributos estáticos de una clase, y que acceder a esos mediante `self.atributo` **NO** era lo mismo que realizar  `Clase.atributo`. Lo consulté nuevamente con mi profesor @nebil y efectivamente no era lo mismo, por una razón que no entendí muy bien (pero algo tenía que ver con que la instancia se apropia de ese atributo de la clase y ya no es el mismo que el de clase; o sea, que lo duplica). Ahora bien, en el material de la semana 9 se realiza lo siguiente:

```python
import threading
import time
from random import random


class EscritorArchivo(threading.Thread):
    """
    Esta clase modela un thread. Dentro creamos un objeto para bloqueo dentro de la clase. 
    El Lock es una variable independiente de cada thread
    """
    
    lock = threading.Lock()
    
    def __init__(self, número, archivo):
        super().__init__()
        self.name = "EscritorArchivo número {}".format(número)
        self.número = número
        self.archivo = archivo
    
    def run(self):
        # Recordemos que la forma de buscar atributos es:
        # 1. Buscar en la instancia (en este caso, no existe).
        # 2. Si no existe, buscar en la clase (en este caso, lo encuentra).
        # 3. Si no existe, error.
        with self.lock:
            try:
                self.archivo.write('Línea escrita por thread # {}\n'.format(self.número))
            finally:
                # Hacemos que se demore una cantidad random uniforme [0, 1)
                time.sleep(random())
                

# Creamos un archivo para escribir una salida. 
# Luego creamos los threads que escribirán dentro del archivo
with open('files/salida.txt', 'w') as archivo:
    # Creamos los threads
    cantidad_threads = 7
    threads = [EscritorArchivo(i, archivo) for i in range(cantidad_threads)]
    
    # Hacemos partir los threads
    for thread in threads:
        thread.start()

    # Esperamos a todos los threads antes de cerrar el archivo
    for thread in threads:
        thread.join()
```
como se puede ver en esta linea:

```python 
with self.lock:
```

se está haciendo justamente lo que estoy hablando. Mi duda es, por qué en este caso hacer eso está bien? En qué casos se debe hacer y en cuales no?

**Comment by pcseisdedos** [comment]
Con tu pregunta me acordé que hace tiempo me surgió la misma duda pero nunca lo pregunté, ahora lo busqué y encontré el código que me causó la duda, es de la materia de [colas de la semana 02](https://github.com/IIC2233/contenidos/blob/master/semana-02/03-colas.ipynb) 
`
fromfrom  collectionscollect  import deque
from random import choice, randrange


class Auto:
    """Esta clase modela los autos que llegan a la revision."""
    
    # Un staticmethod es un método propio de la clase, que no se aplica a una instancia particular
    # Su primer argumento NO es una instancia de la clase (al que solemos llamar self)
    @staticmethod
    def tiempo_revision(tipo):
        if tipo == 'auto':
            return 10
        elif tipo == 'moto':
            return 25
        return 30
    
    def __init__(self):
        self.tipo_vehiculo = choice(['moto', 'camioneta', 'auto'])
        self.tiempo_revision = self.tiempo_revision(self.tipo_vehiculo)
        
    def __str__(self):
        return self.tipo_vehiculo`

Pasa lo mismo en esta linea:
`self.tiempo_revision = self.tiempo_revision(self.tipo_vehiculo)`
En donde se sobre escribe el método estático _tiempo_revision_ de la clase **Auto** por un atributo de la instancia, yo esperaría que en el lado derecho de la igualdad dijera Auto.tiempo_revision(self.tipo_vehiculo)

**Comment by naquiroz** [comment]
Ahhh, y no se duplica entonces?
Me explico, 
supongamos yo despues hago
```python
self.lock = 4
```
Eso cambiaria para todas las instancias? o sólo para esa instancia?

**Comment by jfbahamondes** [comment]
Si haces eso luego del with lock, estarías definiendo el atributo, dentro de la clase con el nombre lock. Es decir, que a partir de ese instante, self.lock ya no llamará más al atributo de la clase.

**Comment by jfbahamondes** [comment]
Como consejo te recomiendo no escribir el código de esta manera, a menos que seas claro y ordenado, ya que te puede causar confusiones. Y a nosotros también corrigiendo.

**Comment by naquiroz** [comment]
@jfbahamondes si, nunca lo hago jaja, pero era para exponer mi duda. Gracias!
