### ISSUE TITLE
Probar con otros .csv

### ISSUE THREAD

**Issue by pedroriosg** [IIC2233/syllabus#497]
Hola! Quería saber si existe la posibilidad de que suban otro archivo `.csv` (delegaciones y/o deportistas) para poder verificar que nuestro código efectivamente funciona ante un cambio de `header`.

Desde ya muchas gracias!

**Comment by itmunoz** [comment]
Hola! No tenemos pensado subir más archivos .csv aparte de los entregados. Sin embargo, puedes tú mismo editar el orden de los header en estos archivos para probar si efectivamente corre bien tu programa. Si haces esto, recuerda también cambiar el orden de los datos en las siguientes líneas.
