### ISSUE TITLE
Error NoneType

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#497]
Hola!
Resulta que queriendo ingresar a una acción determinada, a través de esta voy comprobando datos para guardarlos y poder utilizarlos, pero justo aquí, *python* me arroja un error que no sé por qué sucede. Les adjunto la imagen del error.
![error al elegir sanar criatura](https://user-images.githubusercontent.com/59337116/79301931-d45a6e80-7eb8-11ea-83d5-e7e214685051.PNG)

**Comment by mpsubiabre** [comment]
Hola @Camila-sty,

Es error significa que tu lista_datos_criaturas no tiene el método getitem que es al final poder acceder mediante los cachetes, verifica bien que esta lista sea efectivamente una lista, porque según el error no lo es, verifícalo mediante print(type(lista_datos_criaturas)))

Cuentame como te va :)
