### ISSUE TITLE
Definicón fin del día en función clientes_despues_hora

### ISSUE THREAD

**Issue by JosefaATP** [IIC2233/Syllabus#497]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Cómo están?
En la funcion clientes_despues_hora, dice: Retorna un str con el id de los clientes que hayan hecho un pedido entre el inicio de la hora dada y el fin del día.
Mi pregunta es que con que hora debemos tomar el fin del día? Realmente 00:00? o un horario en el que cerraria un local onda 23:00 o 23.30, etc?

Gracias!😁

**Comment by FradexMF** [comment]
Hola!
Se debe considerar desde la hora dada hasta las 23:59 incluyendo.
Ejemplo si te dan la hora "18:00" y los pedidos:
- Pedido(1,2,3, 2024-08-10, 00:00:00)
- Pedido(2,2,4, 2024-08-11, 23:59:00)

Se debe retornar el id_cliente del segundo pedido, es decir "4".

Espero te aclare la duda!

**Comment by JosefaATP** [comment]
Perfecto! 
Gracias 😁
