### ISSUE TITLE
Duda respecto a test_elementos_prohibidos

### ISSUE THREAD

**Issue by MrFoxley** [IIC2233/Syllabus#497]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
Hola, al correr el test elementos prohibidos me sale True al lado de cada test,¿esto significa que está bien? ¿O que estoy usando elementos prohibidos en cada test? Si se que es un poco intuitiva la pregunta pero de todas formas me quiero asegurar.
Gracias de antemano.
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by MrFoxley** [comment]
A esto me gustaría sumar la siguiente duda también, ¿este test revisa elementos prohibidos tales como el uso del comando list() ?
Por ejemplo, si en una función generadora hago "yield (id, porcentaje)" para que retorne una tupla, ¿estaría bien o sería considerada una mala practica?

**Comment by diegobas10** [comment]
Hola buenas @MrFoxley,
Mientras tengas todo true significa que estás cumpliendo con el test así que no te preocupes.
Saludos

**Comment by diegobas10** [comment]
@MrFoxley respecto a tu segunda duda, el test revisa todas las cosas así que no te preocupes, y si estaría bien ya que ocupas una función generadora para hacer estas tuplas, procura que siempre te salga True en el test.
Saludos

**Comment by MrFoxley** [comment]
Gracias!
