### ISSUE TITLE
Duda sobre keyPressEvent

### ISSUE THREAD

**Issue by imuoz** [IIC2233/syllabus#497]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Cree la ventana en Qt designer y la herede correctamente, esta se abre al ejecutarla, pero definí el metodo keyPressEvent y al apretar teclas no pasa nada, puse un print para ver si entraba al metodo y no lo hace, no estoy muy seguro por qué puede estar pasando esto

**Comment by clementevalladares** [comment]
Hola @imuoz, podría ser que tu ventana no esté enfocada, si no te funciona haciendo click en ella puedes intentar con "self.setFocusPolicy(QtCore.Qt.StrongFocus)" para cambiar el focus que permite tu widget.
De todas formas, podrías subir lo que llevas a tu repositorio de github, para poder ver si el problema se trata de algo más.

**Comment by imuoz** [comment]
No entiendo muy bien la utilización de self.setFocusPolicy. La ventana tiene Widgets que me permiten apretarlos, como radiobuttons, pero no entiendo qué pasa con las teclas, acabo de subir lo que llevo y el problema está en frontend/ventana_preparacion. Al apretar por ejemplo la I o la A me cambia la dificultad(widget que está arriba a la derecha), pero no reacciona keyPressEvent

**Comment by imuoz** [comment]
Presioné uno de los radiobuttons y comenzó a funcionar el movimiento, no entiendo qué esta pasando jajaja

**Comment by clementevalladares** [comment]
Lo que está pasando es que el focus de tu ventada de preparación está asignado por defecto a tu QComboBox, si presionas las teclas de arriba y abajo verás que cambia la dificultad seleccionada. 
Para arreglar esto, al final del __init__ de tu clase VentanaPreparacion debes escribir self.setFocus(True), de esta forma el focus volverá a tu ventana.

**Comment by imuoz** [comment]
Perfecto, muchas gracias!!!!
