### ISSUE TITLE
Binarización de una imagen

### ISSUE THREAD

**Issue by robertov1** [IIC2233/syllabus#497]
Hola! Tengo dos preguntas con la binarización de una imagen. 

1. Un pixel "encendido" es (255, 255, 255) y uno "apagado" (0, 0, 0) ?
2.  Para lo de las cotas, que significa "pixeles cuya intensidad es inferior a ese valor" ? 

Por ejemplo, para una cota de 30. Si tengo un pixel (150, 234, 29), binarizandolo tiene que quedar:
(1,1,0) o (0,0,0) ? No entiendo si lo que se binariza es el pixel completo (por tener un componente del pixel bajo la cota) o cada color que lo compone

Gracias!

**Comment by ariel-m-s** [comment]
Hola @roberto009!

¿A qué nos referimos con _encendido_ y _apagado_? A que una variable sólo puede tomar dos valores (es decir, que es **binaria**). En este caso estos valores pueden ser **255** y **0**. Sólo hablaremos en estos términos cuando nos refiramos a una imágen en **escala de grises**.

Si te fijas, una imágen RGB tiene un canal por cada color (rojo, verde y azul). En este caso, cada píxel es determinado por un **vector** de tres componentes: uno por cada canal. Esto implica que no está bien definido cuándo un píxel se encuentra _encendido_ o _apagado_.

Es por esto que siempre que hablemos de esta binarización, lo haremos con respecto a la imágen en **escala de grises**. En este caso, existe **un único canal** (el gris). Este canal, al estar binarizado, solo puede tomar dos valores: 255 (_encendido_) y 0 (_apagado_).

Siguiendo con esta idea, al momento de binarizar tu imagen, esta tiene que ya estar en escala de grises. De esta manera, podrás fácilmente determinar si la intensidad de su píxel es mayor o menor a cierta cota, dado que este será unidimensional.

Espero haber aclarado tu duda. Si no fue así puedes seguir comentando esta _issue_ sin ningún problema 😄.

Salu10.

**Comment by robertov1** [comment]
Muchas gracias Ariel!

**Comment by snarriagada** [comment]
Hola, aun tengo dudas para aplicar el filtro.
 Entonces en el paso 5 (Invertir esta imagen binaria) esta bien que me quede una matriz de valores unidimensionales (0 y 255)? y luego para el paso 6 (convertirla a png) debo primero triplicar cada valor unidimensional para obtener las tuplas (r,g,b) y poder pasar de rgb a png?

**Comment by ariel-m-s** [comment]
¡Hola @snarriagada!

Así es. Se recomienda trabajar con una sola matriz en escala de grises (unidimensional), que se puede obtener a través de la expresión mostrada en el enunciado a partir de las matrices RGB.

Ahora bien, para guardarlo como PNG **es necesario** que obtengas las matrices RGB correspondientes. Una manera de hacer esto es asignar a cada uno de los colores el mismo valor obtenido en escala de grises.

Saludos,
Ariel

**Comment by robertov1** [comment]
Hola @ariel-m-s,

Después de hacer todas las operaciones con las matrices, queda una matriz con un numero por pixel. Para guardarlo como PNG no la convierto a matriz RGB, pero en el chunk IHDR en color pongo 0 en vez de 2, que es para indicar que los pixeles están en escala de grises (un canal) y no en RGB (tres canales). Y funciona bien el filtro.

Se puede hacer así cierto? Son dos maneras válidas de hacerlo

**Comment by iqacevedo** [comment]
Hola @robertov1 

Es válido para la aplicación del filtro. Debes tener cuidado con que el resto del IHDR quede con el tipo de color 0. Mientras estés seguro de que no hay errores con el formato PNG está todo bien ahí.
Debes considerar que igual tienes que tener una función que dada una imagen normal, la guarde en PNG. Si te pasamos un jpg, se tiene que obtener la matriz RGB, y después guardar en PNG sin perder los colores de la imagen.

Saludos!
