### ISSUE TITLE
Distribución Temperaturas extremas

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#497]
Hola, 

no entiendo bien como funciona lo de las temperaturas extremas. 

Dice que dcada día hay una probabilidad de que haya temperatura. Y que las temperaturas tienen una distribución uniforme discreta entre 2 a 20 días. 

Esto que significa? Que todos los días hay un 18/30 de que haya temperatura extrema? 
Y luego un choice para ver si es calor o frío?

Gracias

**Comment by Kitaps** [comment]
O se refiere a hacer un randint entre 2 y 20 para que parta y luego un randint entre 2 y 20 para que termine y así?

**Comment by cilopez** [comment]
Lo que se refiere el enunciado es que al momento de implementar tu DES, el próximos _evento_ de temperatura extrema sera entre randint 2 y 20, y tu ya sabiendo ese día en que habrá temperatura extrema revisarás si es un día frío o uno caluroso y finalmente gatillaras lo señalado en tu simulación.

**Comment by MarceloSaldias** [comment]
Entonces en la simulacion solo habra un dia con temperatura extrema?

**Comment by cilopez** [comment]
Sucede lo que  dices en tu **edit**, ojo que es  día actual+2 y 20

**Comment by Kitaps** [comment]
Gracias

**Comment by iqacevedo** [comment]
Hola,

Porfavor no cierren las issues, nosotros las cerraremos más adelante 😸
