### ISSUE TITLE
Cambiar método de clase a función en otro archivo e importarla

### ISSUE THREAD

**Issue by MINGOD24** [IIC2233/syllabus#498]
Hola,
En mi tarea tengo un archivo que esta justo en 400 lineas, pero tengo una función dentro de este archivo (que es solo una clase) la cual supera en varias ocasiones los 100 caracteres por linea. ¿Podría yo crear un nuevo archivo y en este ultimo poner una función que replique la función que excede los caracteres, o es considerado una mala practica? Espero que se entienda :)

**Comment by jeschuwirth** [comment]
Hola @MINGOD24,

Para esta tareas si tienes una clase que se pase de las 400 líneas probablemente le estas agregando métodos extra que podrían ser funciones.

Es una buena práctica mover las funciones a otros archivos y luego importarlas, esto se le conoce como la modularización de tu programa. Ten en cuenta que este nuevo archivo con el método transformado a función debe tener un nombre declarativo de lo que contiene.

Si quedaron dudas sigue comentando en esta issue :)

Éxito!

**Comment by MINGOD24** [comment]
Perfect! muchas gracias!
