### ISSUE TITLE
Posicion inicial del personaje

### ISSUE THREAD

**Issue by Afro27** [IIC2233/syllabus#498]
Como puedo instanciar al personaje en el main para que su posicion inicial sea una determinada en el front(primera casilla de pasto), ya que no le puedo dar los atributos necesarios antes de saber que mapa se usará. La solución que encontre fue instanciar y conectar las señales del personaje en el front, pero de ser asi no podria conectar las señales del back(personaje) con otra clase que no sea la del front.

**Comment by lily416** [comment]
Tienes dos opciones:
1. Puedes instanciar tu personaje en una posición arbitraria (i.e. la casilla `0,0`) y una vez cargado el mapa reubicas el personaje en una posición válida.
2. Instanciar el personaje después de haber recibido el mapa como input y haber encontrado una posición válida.
 
Saludos y éxito en tu tarea 👋🚶

**Comment by Afro27** [comment]
Pero como puedo mover a la instancia del personaje despues de crear el personaje?, puedo conectar señales del front con el main para que el main haga algo?

**Comment by lily416** [comment]
Para lo primero, puedes mandar una señal que actualice la posición del personaje. Algo equivalente a cuando se presiona una tecla, solo que se activa cuando el mapa ya está cargado.

Con respecto a lo segundo, no comprendo a qué te refieres con "conectar señales del front con el main" trata de ser más específico.

**Comment by Afro27** [comment]
@lily416 Mi personaje si se mueve, lo que pasa es que al dar el primer paso se 'teletransporta' a la posicion donde se instancio en el main, entonces para cambiar esa posicion tengo que mandar una señal desde el front al main, pero no se si es correcto hacerlo.

**Comment by lily416** [comment]
@Afro27 ¿puedes subir tu código para revisarlo? 
Puede ser que cuando cambias el personaje de posición (a una posición en el mapa válida) no cambias la dirección en el backend

**Comment by Afro27** [comment]
Logre hacerlo, gracias
