### ISSUE TITLE
Archivo excede líneas máximas.

### ISSUE THREAD

**Issue by FranVvi** [IIC2233/Syllabus#498]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda, Mi archivo excede las líneas permitidas y quería saber si puedo crear un archivo nuevo para colocar todas las funciones pedidas en "Consultas que reciben tres o mas generadores" y en el archivo "consultas" (original) solo las "consultas que reciben un generador" y "Consultas que reciben dos generadores". Si esto no se puede hacer, de que otra forma lo podría resolver esto?

**Comment by diegobas10** [comment]
Hola buenas @FranVvi ,
La idea es que si sobrepasas la cantidad de lineas, es hacer un archivo con funciones auxiliares para que el archivo de consultas original no sobrepase las 400 lìneas, ya que a la hora de corregir con los tests, se va a llamar a las funciones de este archivo, por lo que si puedes tener un archivo extra, mientras se mantenga la estructura original y se siga usando las reglas de la tarea es decir que no se ocupen elementos prohibidos, igualmente este ultimo test va a seguir detectando si ocupas elementos no permitidos si es que ocupas estructuras prohibidas en el otro archivo.
Saludos, quedo atento a dudas.
