### ISSUE TITLE
Problema Contenido Interfaz Grafica

### ISSUE THREAD

**Issue by ofvera** [IIC2233/Syllabus#498]
Al usar PyQt4 y ejecutar el contenido de interfaz gráfica, después de bajarme PyQt5 para la tarea anterior, tengo problemas con el uso de de QtGui y QWidget. Vamos a usar PyQt5 o PyQt4 de ahora en adelante? 
Por que si el problema proviene del uso de módulos instalados en PyQt5, la materia de PyQt4 quedaría outdated, como aun no encuentro por que sucede este problema no soy tajante en eso (es más una intuición), espero que puedan ayudarme.

**Comment by Hernan4444** [comment]
@ofvera si revisas el material es de PyQt5. Parece que todavía tienes el material antiguo.

Saludos!

**Comment by ofvera** [comment]
Si gracias!

**Comment by benjamimo1** [comment]
Buenaa, tenia la misma duda
