### ISSUE TITLE
Inconsistencias retorno en algunas consultas que reciben dos generadores

### ISSUE THREAD

**Issue by Mgseverin** [IIC2233/Syllabus#498]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Tengo una pregunta respecto a unas inconsistencias entre lo que retornan algunas funciones de consultas que reciben dos generadores. Hay 4 funciones que en su definición en el archivo `consultas.py` retornan algo distinto a lo que dice que debería retornar el enunciado. Quería saber cual de las definiciones hay que respetar, ya que me hace sentido seguir la definición del enunciado, pero en  este se establece claramente: "Estas funciones ya están definidas en los archivos que te entregamos para esta evaluación. Solo debes completar estas funciones, es decir, **no debes cambiar su nombre, alterar los argumentos recibidos o cambiar lo que retornen**". No se si es relevante cambiar lo que retorna o si se puede hacer. Sería muy últil tener esta aclaración. Dejo las inconsistencias que encontré.
![image](https://github.com/user-attachments/assets/60df56b1-9967-4cad-a95a-de8db165231d)

**Comment by AlonsoPlaza** [comment]
Hola, es un pequeño error de consistencia pero siempre en estos casos hay que respetar lo que dice el enunciado.
