### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by constanzacontreras** [IIC2233/syllabus#498]
Hola!
¿Es necesario para el avance usar gitignore?
Gracias

**Comment by Hernan4444** [comment]
Hola

No es necesario, **pero se recomienda fuertemente** porque después se les olvida eliminar los archivos a ignorar (a varios les pasó) y por lo tanto terminan en el repositorio al momento de entregar, lo cual repercute en un descuento :c .

Saludos
