### ISSUE TITLE
Modularización en el Avance de la T2

### ISSUE THREAD

**Issue by AlfonsoBadilla** [IIC2233/syllabus#498]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Buenas, quería saber si para el avance es necesario que este esté modularizado, o si no es necesario pero es mejor hacerlo así, etc...

**Comment by Juampisaez** [comment]
Hola @AlfonsoBadilla 
Para el avance solamente se pide lo que aparece en el enunciado. Sin embargo, yo te recomendaría considerando que ya estas pensando en modularizar que lo hagas de igual manera, te ayudara en el modelamiento de tu programa (pero no se evalua en el avance).

Espero quede claro :)

**Comment by AlfonsoBadilla** [comment]
Wenísimo, gracias por la pronta respuesta, todo claro 🥏
