### ISSUE TITLE
Distribución normal de instalación de puestos

### ISSUE THREAD

**Issue by IchottMano** [IIC2233/Syllabus#498]
Debido a que la instalación de puestos de los vendedores se distribuye de manera normal, existe la posibilidad, aunque pequeña de que el valor entregado por la función muy grande o muy pequeño, lo que podría generar problemas, podemos establecer un horario mínimo y máximo para la instalación de puestos?
Muchas gracias

**Comment by cilopez** [comment]
Sí puedes, existe la posibilidad de que les definamos ese horario en una futura modificación del enunciado

**Comment by cilopez** [comment]
@IchottMano Revisa el nuevo enunciado :smile:
