### ISSUE TITLE
Librerías permitidas/no permitidas en la T04

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233/Syllabus#499]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:

> ¿Puedo usar la librería nombre_librería para hacer explicación_de_lo_que_quiero_hacer?

Recuerden especificar en su README qué librerías utilizan!

-----------------
## **Librerías Permitidas**
- `random`
- `unittest`
- `logging`
- `abc`
- `datetime`
- `collections`
- `math`
- `time`
- `statistics.mean`
- `copy`
- `itertools`
- `tabulate`
- `typing`
- `abc`
- `functools.reduce`
- `matplotlib`
- `bisect`
- `csv`
- `calendar`
- `operator`
## **Librerías Prohibidas**
- `threading `
- `pandas`
- `recordclass`

## **Built-ins prohibidos**
- `eval`(:skull:)
- `exec` (:skull:)

**Comment by llloyola** [comment]
Puedo importar ```numpy``` para usar ```numpy.random.choice```?
Quiero representar el **Cuadro 1** como una distribución de probabilidades discreta y así generar los horarios de colación para los empleados

**Comment by mfanselmo1** [comment]
Hola, para eso puedes usar `random`, ya que `numpy` puede generar muchos problemas entre versiones

**Comment by llloyola** [comment]
Pucha 😢 :cries_in_chilean:
Gracias!

**Comment by emeiese** [comment]
@mfanselmo1 También me interesa usar numpy.random.choice, ya que random.choices sólo funciona para python 3.6, y como tengo ubuntu 16.04 , esta versión de python no está disponible :( (o algo así encontré en internet), por lo que no puedo usar random.choices, pero si puedo usar numpy.random.choice

**Comment by FJavierOss** [comment]
@emeiese No se si haya diferencia entre ubuntu 16.04 y 16.04 lts, pero logre instalar python 3.6.2 en ubuntu 16.04 lts. Eso si uno se demorá un poco en hacerlo. Suerte

**Comment by emeiese** [comment]
@FJavierOss  Puedo usar ```numpy.random.choice``` en mi código y dejar comentado en el readme que utilicé eso? quizás poner otra versión de la misma línea que pueda ejecutarse con python 3.6 para cubrir el caso de que el ayudante tenga problemas con numpy al corregir debido a la versión que tiene. Prefiero no complicarme ni gastar tiempo en algo tan simple.

**Comment by FJavierOss** [comment]
@emeiese  No tengo idea jajaja, no soy ayudante, pero segun yo mejor no complicarse y usar random a la mala para hacer lo mismo que random.choice, serían pocas lineas en todo caso.

**Comment by rihanuch** [comment]
¡Hola @emeiese !

Tal como dijo @FJavierOss , puedes hacer ```random.choice```, no es necesario complicarse con ```numpy````

¡Saludos! 🍀

**Comment by mfanselmo1** [comment]
Hola @jachavarri!
Para eso deberas usar la libreria `faker`

**Comment by jmwielandt** [comment]
@emeiese 
```sudo apt-get python3.6``` si no me equivoco, te deja instalar python 3.6 en ubuntu 16.04
luego puedes abrir el idle con ```idle3.6``` y ejecutar tus archivos .py con ```python3.6 main.py``` (reemplaza "main.py" por el nombre del archivo que quieras correr).
Puedes crear un lanzador y asignarlo para que te abra el idle si quieres, y ese tipo de cosas ;)

Si no te funciona, haz esto:
```import random
def choice(lista):
    return lista[random.randint(0, len(lista))]
```
Y lo puedes poner en un módulo que se llame "funciones auxiliares.py" o algo así.

**Comment by jmwielandt** [comment]
Puedo usar colorama para poner el texto con colores y que sea más fácil leerlo?

**Comment by naquiroz** [comment]
hola! puedo usar la libreria `scipy.stats` para utilizar la funcion `truncnorm` para ponerle limite superior e inferior a los numeros calculados con distribuciones normales?. Busco esto por la parte del enunciado que dice que "la estatura no debe ser menor a 60cm ni mayor a 190cm"

**Comment by rihanuch** [comment]
@naquiroz , no, pero sí puedes usar un ```if``` en vez de la librería ```scipy.stats``` para hacer eso

**Comment by naquiroz** [comment]
@rihanuch y respecto a la otra librería?

**Comment by naquiroz** [comment]
Y lo otro, puedo usar la libreria `locale` para determinar el nombre en español de un dia en especifico con `calendar`?

**Comment by Hernan4444** [comment]
@naquiroz si puedes.

**Comment by naquiroz** [comment]
Puedo usar la libreria `locale` sacar los nombres de los dias en español?

**Comment by Hernan4444** [comment]
@naquiroz si puedes.

**Comment by jmwielandt** [comment]
Hola... más arriba pregunté si podía usar colorama pero creo que no lo vieron :(

**Comment by rihanuch** [comment]
@jmweilandt , no, no puedes. Lo que si te podría servir si quieres agregar colores es lo que aparece en [stackoverflow](https://stackoverflow.com/a/21786287)

**Comment by contranton** [comment]
¿Puedo usar `functools.partial` para operar con funciones con argumentos 'congelados' y tener asi mas flexibilidad con los callbacks de los eventos? Ejemplo de su uso:

``` python
from functools import partial
def foo(arg1, arg2):
    return arg1 + arg2

foo1 = partial(foo, arg2=5)
foo1(10)
>>> 15
```
Si no está permitido, ¿lo estará hacer una implementación casera y usar eso?
Gracias!

**Comment by Hernan4444** [comment]
@contranton si puedes.
Saludos ✌️

**Comment by naquiroz** [comment]
puedo usar `textwrap` para hacer _wrap_ automático de las descripciones muy largas?

**Comment by Hernan4444** [comment]
@naquiroz si puedes.
Saludos ✌️

**Comment by Clemente24** [comment]
Hola, se puede usar SimPy?

**Comment by Hernan4444** [comment]
@Clemente24 no puedes.

Saludos ✌️

**Comment by sjkinast** [comment]
Hola puedo usar exist de la libreria pathlib para agregar contenido al archivo log.txt

**Comment by Hernan4444** [comment]
@sjkinast lo que quieres hacer se puede con las herramientas del curso. No es necesario usar una librería, así que no puedes.

Saludos ✌️

**Comment by sjkinast** [comment]
Entonces puedo importar os.path.isfile que es usado  en la ayudantia 06 y por ende una herramienta del curso para el mismo fin?

**Comment by Hernan4444** [comment]
@sjkinast así es 👍 

Saludos ✌️
