### ISSUE TITLE
ajustar_precio_segun_ingrediente inicial

### ISSUE THREAD

**Issue by cucho2** [IIC2233/Syllabus#499]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, en el enunciado de la funcion ajustar_precio_segun_ingrediente, dice que ningún precio puede estar debajo de los 7000. Por esto mismo, antes de ajustar el precio indicado, ¿hay que modificar los precios existentes?
Es decir, ¿antes de ajustar el precio según ingrediente primero tenemos que verificar si existen precios debajo de los 7000 y cambiarlos? O asumimos que los precios iniciales no partirán bajo 7000.

Dicho esto, si la respuesta es sí, ajustamos el precio con el valor nuevo en caso de tener un precio inicial menor a 7000? ¿O deberíamos utilizar el valor antiguo?

Ejemplo: Pizza con precio 5000, se corrige a 7000. ¿Luego se restaría el ajuste de precio al 5000 inicial o al 7000 modificado?

**Comment by FradexMF** [comment]
Hola!
Te recomiendo revisar la issue #443, si aún tienes dudas avísame para aclararlo.
