### ISSUE TITLE
Duda acerca del tiempo de ejecución de los tests

### ISSUE THREAD

**Issue by MrFoxley** [IIC2233/Syllabus#499]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
Buenas Tardes, el test 18 me corren todos los tests ok salvo el ultimo que se demora demasiado en ejecutar y sigue por muchísimo tiempo. Cuando corro todos_tests se me queda pegado ahí un buen rato y nunca he esperado a que termine de correr. ¿Esto cuenta como que la tarea no se pueda ejecutar? ¿O puedo dejarlo así y que me descuenten puntos en ese test específico por exceder el tiempo pero me den algunos por tener los otros tests bien?
Gracias de antemano
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by MrFoxley** [comment]
Por favor ayudenme, me queda muy poco tiempo. 
Gracias de antemano

**Comment by mpiavf** [comment]
Hola, se explica esto en la issue #368 

Tal como sale en esa issue : 

Hay 2 tipos de tests

- Conjunto de tests de correctitud: que son los que no usan .csv sino que tienen los datos en el mismo tests. Esos igual deben correr en 20 segundos, pero son tan pocos datos los que se usan en esos tests que es muy muy díficil que supere los 20 segundos..... pero si el código llega a demorarse más de 20 segundos con esos tests, se considera malo igual.

- Conjunto de tests de eficiencia: que son los que cargarán CSV de diferentes tamaños, y esos tambien tendrán 20 segundos por tests, solo que aquí se espera que a medida que suba la cantidad de datos, tome más tiepo, pero nunca que se supere los 20 segundos.

Y al momento de correr los tests privados, cada tests es indepediente. En el sentido que si 1 test se demora más de 20 pero todos los demás de dicho archivo se demoran menos de 20, solo el test que tomó más tiempo será considerado incorrecto, pero todos los demás estarán correctos. Da lo mismo si ese test incorrecto fue el primero que se revisó o el último.... Para que no se preocupen de que si 1 test está incorreto, los siguientes ya se dejan de revisar, eso no pasará.

Saludos!
