### ISSUE TITLE
Tamaño de generadores

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#499]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Por qué los generadores tienen un tamaño fijo? Es una función almacenada que se llama al llamarlo más que los valores, o algo distinto? Lo otro, por qué lo arbitrario de su tamaño? en el note por defecto pesaba 128 bytes pero cuando lo corrí yo pesaba 120.

**Comment by aaossa** [comment]
Hola @fernandosmither , buena pregunta (para variar).

Los generadores solo son una expresión a la que Python le puede pedir valores continuamente (con `next`). No almacena una colección de valores ni nada parecido, sino que solo ciertos valores típicos de Python, un puntero a la expresión, un atributo para recordar si ya se está ejecutando el generador y otras cosas (el detalle puedes verlo en [esta respuesta de StackOverflow](https://stackoverflow.com/a/27794335/3281097), aunque puede que haya minúsculos cambios en la implementación debido a la evolución de Python).

Imagino que el tamaño específico en bytes de un generador puede variar trivialmente según la cantidad de código del generador y también imagino (no tengo certeza) que puede variar según la instalación de Python (a veces se comprimen de manera distintas las cosas, o se usan optimizaciones distintas según el *hardware*). De todas maneras, prácticamente siempre te convendrá usar un generador antes que otra alternativa. Por ejemplo, yo en general los uso cuando necesito una colección de elementos que solo quiero recorrer una vez, así me ahorro tener listas intermedias, ocupar memoria de más y tener que recorrer una colección más de una vez.

Avísame si tienes otra duda adicional ✌️ ¡Éxito con tu estudio ✨!
