### ISSUE TITLE
Pasar día siguiente enfermaron/escaparon

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#499]
Cuando paso de día y despliego criaturas que enfermaron y que escaparon es solo en ese día o es el total de todo los días. O sea, despliego los nombres de las criaturas que cambiaron de estado_salud, por ejemplo, solo ese día o muestro todas las criaturas enfermas actualmente.

**Comment by jeschuwirth** [comment]
Hola @dsepulveda3,

La duda esta resuelta en la issue #465
