### ISSUE TITLE
Llegada de Carabineros

### ISSUE THREAD

**Issue by MarceloSaldias** [IIC2233/Syllabus#499]
Cuando se refiere a los *Carabineros* como entes externos a la universidad, se dice que 
> *"El/Ella fiscalizara todos los puestos que alcance desde las 13:00 hasta las 13:40."*

Luego, cuando se habla de la *llegada de policias* como evento no programado, se dice que 
> *"Su dueño Devil llamara anonimamente a los policias locales para que fiscalicen. Las llamadas distribuyen Exp(lambda_t_llamada) y una vez que llama, los policias llegan de inmediato."*

En base a lo anterior, surgen muchos casos: 
Que pasa si *Devil* llama antes de las 13:00? Que pasa si llama despues de las 13:40? Que pasa si llama en algun tiempo intermedio entre las 13:00 y las 13:40?
Se nos dice que su llegada es aleatoria pero que solo actuan en un intervalo de tiempo definido, lo cual confunde un poco :disappointed:
Podrian explicar que pasa en cada uno de los casos anteriores?

**Comment by cilopez** [comment]
Las llamadas se realizan por día, es decir existe un día en el cual llama _Devil_ a los carabineros, tu variable aleatoria te proporcionará solo el valor del día en que sucede esto no en la hora, por lo que no te preocupes por los casos que estas diciendo. :police_car:

**Comment by jpmoraga1** [comment]
Sobre el tiempo de revisión, se dice que es inmediata, pero también se dice que
El/ella
scalizara todos los puestos que alcance desde las 13:00 hasta las 13:40.
Si no hay tiempo de revisión, entonces la simulación se quedaría pegada en esta parte, o se avanzaría en caso de que todos los puestos sean revisados. ¿Estoy en lo correcto?

**Comment by MarceloSaldias** [comment]
Entonces, si el expovariate entrega como resultado 3.5, significa que en (3 o 4?) dias mas vienen los carabineros?

**Comment by cilopez** [comment]
Aproxima como quieras, explicitalo en tu _readme_
