### ISSUE TITLE
Eventos no programados

### ISSUE THREAD

**Issue by berrazuriz1** [IIC2233/Syllabus#499]
En el enunciado, en la parte de eventos no programados, al final de la descripción del corte de agua dice que como máximo hay uno de estos eventos durante la semana, ¿esto se refiere a que cada uno de los eventos pasa una vez a la semana como máximo o que son excluyentes entre si, osea que si hay un partido en una semana no puede haber un corte ni una fiesta?. En el feedback de los diagramas de eventos mencionan que los eventos no programados son independientes entre sí, por lo que tiendo a pensar que es la primera opción, pero no estoy seguro.

**Comment by iqacevedo** [comment]
Hola ! 

Se refiere a que como máximo hay un corte de agua a la semana. Los otros eventos son independientes de este evento.

Saludos !
