### ISSUE TITLE
Duda porcentaje aumento comprar tecnología

### ISSUE THREAD

**Issue by AlfreMK** [IIC2233/syllabus#499]
Hola!, para los implementos el aumento en porcentaje como se haría? como si fuera interés compuesto o como interés simple?
de antemano muchas gracias por responder c:

**Comment by retamalcito** [comment]
¡Hola @AlfreMK!

Puedes implementar el aumento de porcentaje tanto como interés simple como interés compuesto, siempre y cuando lo **especifiques** en tu README. Personalmente, te recomendaría implementarlo como "interés compuesto", ya que así te será más fácil actualizar el valor.

¡Éxito! 🥇
