### ISSUE TITLE
Resultado Filtro Dibujo

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#499]
EL resultado que obtuve fue el siguiente:
![Capturam](https://user-images.githubusercontent.com/48294819/59393804-153e9f80-8d4b-11e9-993c-454512ca7c59.PNG)

esta bien? ya que no es exactamente igual a lo que se ejemplifica en el enunciado

**Comment by ariel-m-s** [comment]
Hola @jalliende!

No te preocupes que no sea exactamente igual al del enunciado. Tu resultado se ve bien 😃.

Ariel

**Comment by ariel-m-s** [comment]
Por favor no cerrar las _issues_. Pueden ser de utilidad para otro estudiante.
