### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by tgarcia4** [IIC2233/syllabus#499]
Me aparece fatal: not a git repository (or any of the parent directories): .git
cuando escribo algun comando en git sobre mi repositorio como "git status" como lo puedo solucionar? Ya que no puedo subir la tarea sin esto.

**Comment by gatochico** [comment]
Hola! 
Haz lo siguiente:
- Haz una copia de tu tarea funcional en otra carpeta en tu computador.
- Clona tu repositorio privado de nuevo.
- Agregale tu tarea al nuevo repo privado que clonaste.
- Sube tu tarea desde este repo y elimina el repo anterior que te estaba lanzando error.

Cuentanos como te va y recuerda **siempre ten una copia de respaldo de tu tarea en caso de cualquier problema**.  :eyes:

**Comment by tgarcia4** [comment]
Me funcionó!  Muchas gracias @gatochico
