### ISSUE TITLE
MacOS: Error en la ejecución de Jupyter

### ISSUE THREAD

**Issue by pedroriosg** [IIC2233/syllabus#5]
Hola!! Por algún motivo mi consola no ejecuta el jupyter notebook (en macOS Catalina v 10.15.6). Está instalado, pero no se por qué no reconoce. Qué puede estar pasando?

<img width="565" alt="Captura de Pantalla 2020-08-13 a la(s) 00 48 43" src="https://user-images.githubusercontent.com/69609154/90096020-3eb4db80-dd00-11ea-84e4-6e4e95bebce2.png">

**Comment by igbasly** [comment]
Hola @pedroriosg  :v:

Primero, coméntame si instalaste Jupyter utilizando `pip install jupyter`. En caso contrario, ¿cuál fue el método que utilizaste?
Por otro lado, veo que estás utilizando la terminal `zsh` ¿eso lo cambiaste luego de la instalación o lo tenías así de antes?
Y por último, coméntame si el comando `python` o `python3` funcionan. Esos debería abrir la terminal de python y se cierran ingresando `exit()`

Espero tus respuestas para tener un mayor contexto del problema, saludos :smile:.

**Comment by pedroriosg** [comment]
Para instarlo usé `pip3 install jupyter`, y lo instalé usando la terminal `bash`. Cambié la terminal luego de la instalación.
Tratando de abrir Python me arroja error, ninguna de las dos funciona.

**Comment by igbasly** [comment]
Entiendo, te comento que ambas ejecuciones están correctas :+1:, solo que `python` ejecuta la versión `2.7` y `python3` la versión `3.7` que es la que utilizamos, para que lo consideres cuando pruebes tus códigos.
Ahora, esto y que hayas migrado la terminal luego de la instalación de jupyter, nos permiten reparar lo que está sucediendo. Vamos a seguir los siguientes pasos:

1. Ingresa en la terminal `open ~/.bash_profile`
2. Copia todo su contenido.
3. Ingresa en la terminal `open ~/.zshrc`
4. Pega lo anterior antes de lo que tenga escrito el archivo `.zshrc`.
5. Guarda y reinicia la terminal.

Ahora debería funcionar `jupyter notebook`, hazme saber cualquiera de los casos o error que pueda surgir :raised_hands:.

**Comment by pedroriosg** [comment]
Hasta el paso 2 todo bien. Sin embargo al ingresar `open ~/.zshrc` me dice que el archivo no existe.

<img width="566" alt="Captura de Pantalla 2020-08-13 a la(s) 10 38 53" src="https://user-images.githubusercontent.com/69609154/90148311-33d66700-dd51-11ea-9cac-0b8ebeeb59b7.png">

**Comment by igbasly** [comment]
Perfecto, no hay problema, eso solo significa que no ha sido creado aún (por defecto no lo está).
Entonces agregaremos un paso, debes ingresar `touch ~/.zshrc` y luego continuar desde el paso 3 con el `open...`. Bajo este nuevo contexto, solo pega el contenido del otro archivo, ya no se considera que haya algo escrito porque creamos el archivo en blanco.

**Comment by pedroriosg** [comment]
Solucionado!! Muchas gracias!!

**Comment by diegobustosk** [comment]
Muchísimas gracias @igbasly  me estaba dando el mismo problema.
