### ISSUE TITLE
¿Solo se pushea el main.py?

### ISSUE THREAD

**Issue by canija2000** [IIC2233/Syllabus#5]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### ¿Solo se pushea el main.py?

Bueno, eso, según entendí en ambos instructivos de las actividades, lo único que se sube al repositorio es el <code>main.py</code>, pero quería estar seguro de que así era.

Gracias!

Joaquin

**Comment by Hernan4444** [comment]
Hola @canija2000 

Así es, para la AC0 de la otra semana y la AC1 de la subsiguiente, solo basta con subir dicho archivo, todo lo demás no es necesario. Esto es porque son archivos que ustedes no modifican, así que nosotros mismos vamos a poner esos archivos si deseamos ejecutar sus main.py

Espero que haya resuelto tu duda. ¡Éxito con las actividades! 🦖
Saludosヾ(＾-＾)ノ
