### ISSUE TITLE
Tiempo de espera / Tiempo promedio de atención

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#5]
En el material de la semana 01 en el documento 3-colas se nombra a una lista como tiempo_espera y finalmente esta se ocupa para saber el tiempo promedio de atención, lo que es distinto. Mi duda es, consideramos la que en la lista tiempo_espera se agregan los tiempos de atención o el de atención + espera del auto que esta siendo atendido anteriormente (si es que corresponde).

**Comment by KnowYourselves** [comment]
Hola!

En el ejemplo cuando se habla de "Tiempo promedio de atención" se hace referencia a cuanto se demoró la revisión del auto, sin considerar el tiempo que estuvo esperando a ser atendido.

En el ejemplo se atendió a una moto (tiempo de revisión 25) y dos camionetas (tiempo de revisión 30) lo cual nos deja con un tiempo de atención de 85 minutos que al ser dividido por 3 nos da el resultado de 28.33 minutos.

Espero haber resuelto tu duda!

**Comment by jalliende** [comment]
Si, gracias. Era eso de si considerar o no el tiempo que estuvo esperado para ser atendido.

**Comment by KnowYourselves** [comment]
Perfecto!

Eso si recuerda no cerrar las Issues inmediatamente para que otros la puedan ver!
