### ISSUE TITLE
Problema con instalación python y pyqt5

### ISSUE THREAD

**Issue by lfb1206** [IIC2233/syllabus#5]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Luego de instalar python como es mostrado en el video verifique en el terminal y me apareció que tengo instalada la version 3.8.2, siendo que descargue la 3.7. Luego al escribir el comando python3.7 --version me apareció que tengo la 3.7.9
**¿Esto significa que estoy listo con la configuración de python?**

Despues al seguir las instrucciones para instalar pyqt5 me salió error y no se como solucionar este problema, adjunto imagen.
 
![Screen Shot 2021-03-17 at 10 11 11 AM](https://user-images.githubusercontent.com/80774014/111472810-1c0cfa00-8709-11eb-9fbe-c30957aaf08b.png)

**Comment by ivannateresa** [comment]
Hola!
Con respecto a la instalación de Python, si ya tienes intalado la version 3.7x estas listo!. Pero puedes desintalar la version 3.8x para que no ocurran futuras confusiones, ya que los ayudantes solo van a revisar tareas con python version 3.7.

En lo segundo puede que tu error venga en que debes actualizar el pip. Se soluciona con : python -m pip install --upgrade pip o  python -m pip install -U pip. En el caso de que no tengas instalado el pip te recomiendo que utilices pip3 install o pip install.

Espero que te sirva!
