### ISSUE TITLE
Inasistencia a actividades

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#5]
si la actividad es en parejas y uno de ellos no puede ir, ¿esto se sanciona con un 10 al que falta o a la pareja? 
y ¿se necesita un porcentaje de asistencia para aprobar el curso o no?

**Comment by andresfdezc** [comment]
Si uno de ellos no va, la pareja se disuelve automáticamente y se trabaja solo. Las inasistencias se sancionan con un 1.0 solo a la persona que falta. No hay un porcentaje de asistencia mínimo, sin embargo tienes que tener al menos un promedio 4.000 en las actividades para aprobar.
