### ISSUE TITLE
¿Puedo seguir usando Python 3.5.1?

### ISSUE THREAD

**Issue by glbello** [IIC2233/Syllabus#5]
Saludos, según leí en la wiki en la sección software obligatorio, que debemos tener versión de Python 3.6.x
pero quería saber si puedo mantenerme en 3.5.1 (que es la versión que tengo actualmente)

**Comment by fringlesinthestreet** [comment]
Si bien la versión oficial del curso es 3.6.X, no se usa nada que no se pueda realizar con la versión 3.5.X. 
La recomendación sería que uses la versión 3.6.X para poder replicar posibles errores pero puedes mantener tu versión actual bajo tu responsabilidad.

**Comment by glbello** [comment]
oki muchísimas gracias :)

**Comment by andresfdezc** [comment]
Hay más información sobre esto en #9
