### ISSUE TITLE
Atom no logra correr archivos en python

### ISSUE THREAD

**Issue by eitandv** [IIC2233/Syllabus#5]
Hola!
Estoy tratando de dejar lista la ultima versión de Atom en windows 10 para usarlo como editor de código principal y al intentar correr cualquier archivo .py me dice que "python" no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable. ¿Que puedo hacer para solucionarlo?

![image](https://user-images.githubusercontent.com/30673518/37222443-da85398a-23ab-11e8-9ae1-e0375f832589.png)

**Comment by contranton** [comment]
Asegúrate de que tu instalación de Python esté en el PATH del sistema; esto hace que se pueda correr desde cualquier línea de comando tan solo escribiendo 'python' (onda sin el C:\Users\ blah blah). [Aquí](https://superuser.com/questions/143119/how-do-i-add-python-to-the-windows-path) sale como hacer esto. Suerte!

**Comment by eitandv** [comment]
muchas gracias!
