### ISSUE TITLE
¿Cómo correr código en terminal usando Rosseta?

### ISSUE THREAD

**Issue by ggmirandac** [IIC2233/Syllabus#5]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

Mi problema principal viene a ser como correr código utilizando la terminal usando Rosetta creada para poder instalar el programa pyqt5. Es decir, **cómo correr código a través de la terminal con rosetta**. 
Porque, por ejemplo, en vscode se genera una terminal automática, pero como corremos el código en la terminal que deseamos.

**Comment by Hernan4444** [comment]
Hola,

Recomiendo fuertemente no depender de la terminal de VSCode para correr los programas de python. Mejor abrir la terminar con rosetta y luego aplicar `cd` para moverse a la carpeta que uno desea (en los contenidos que subiremos mañana hablaremos de dicho comando). Finalmente aplicar `python3 file.py` para ejecutar el archivo deseado. Poder manejarse en la terminal es una habilidad muy necesaria en los siguientes cursos del DCC para correr programas, administrar servidores, etc.

De todas formas, en caso de igual desear incluir una terminal con rosetta a VSCode, en google encontré el [siguiente tutorial](https://dev.to/markwitt_me/creating-a-custom-vscode-terminal-profile-for-using-rosetta-on-an-m1-mac-apple-silicon-2gb2) donde se modifica un archivo de VSCode para incluir dicha terminal 😄.

En caso de usar ese tutorial, cuéntanos como te fue para saber si recomandarlo en otras issues o buscar otro,
Saludos c:

**Comment by ggmirandac** [comment]
Hola, 

Estuve probando ese consejo y no me resulto tan fácil de hacer, debido a que la carpeta que te dice que hay que modificar no se puede modificar debido a que se abre en read-only mode.

Pero encontré el siguiente tutorial que te ayuda a integrar la terminal de rosetta a vscode, de modo que se puede correr esta terminal en la misma aplicación [tutorial](https://dev.to/csjcode/howto-rosetta-terminal-macos-in-visual-studio-code-3pck).
