### ISSUE TITLE
VScode configuración pycodestyle

### ISSUE THREAD

**Issue by diegocostares** [IIC2233/Syllabus#5]
### Problema
Hola, al instalar pycodestyle en visual studio (como lo menciona la wiki) y me arroja muchos errores/alertas con las palabras que están en español, con comentarios # que están en una sola línea y con las que tienen una extensión de más de 79 caracteres, ¿existe alguna forma de configurarlo un poco?

**Comment by pedroriosg** [comment]
Hola @diegocostares ! ✌️ 

Te dejo acá una opción para regular el máximo de caracteres (100 para efectos del curso):

1. Abre `VSCode `y presiona `Ctrl + Shift + P` (`Cmd + Shift + P` en MacOs)
2. Escribe en el buscador `json `y selecciona la opción que dice `Preferences: Open Settings (JSON)`. Se te va a abrir un archivo con extensión `.json`, que contiene en él un diccionario.
3. Debajo de la línea que dice `"python.linting.pycodestyleEnabled": true,` debes copiar lo siguiente: `"python.linting.pycodestyleArgs": ["--max-line-length=100"],`. Si esta última línea es el último término del diccionario, va sin la coma al final, quedaría así: `"python.linting.pycodestyleArgs": ["--max-line-length=100"]`.
4. Deben guardar los cambios realizados en el archivo.

Se debería ver de la siguiente manera:

<img width="320" alt="Captura de pantalla 2021-08-19 175516" src="https://user-images.githubusercontent.com/69609154/130149558-089432cc-376f-494a-b4c0-c7eb5377c340.png">


Con eso, tendrás el linter configurado con el máximo de caracteres por línea permitido.

Con el tema del idioma, creo que puede deberse a la configuración del idioma que tienes en el VSCode. Prueba siguiendo los pasos de este [enlace](https://geeks.ms/jorge/2017/07/23/cambiar-el-idioma-en-visual-studio-code/). Si te funciona o no, avísame para que los demás que tengan el mismo error puedan solucionarlo.

Espero que te sirva!
