### ISSUE TITLE
Wiki: La informacion sobre linting no esta actualizada

### ISSUE THREAD

**Issue by endlessloop2** [IIC2233/Syllabus#5]
En la seccion sobre interfaces de desarrollo, estos pasos no se pueden seguir:

> Presiona Ctrl + Shift + P para abrir la paleta de comandos.
> Escribe o pega el comando Python: Select Linter y selecciona pycodestyle
> Luego del paso anterior, aparecerá una notificación indicando que pycodestyle no se encuentra instalado, por lo que debes seleccionar instalar.

En la seccion sobre consejos utiles, todo lo de 2. Ajuste de estilo automatico esta desactualizado, apunta a un link roto y ademas pide hacer cosas relacionadas con pycodestyle

Con respecto a la configuracion, creo que es posible hacerla, pero dice que esta deprecada.
![image](https://github.com/IIC2233/Syllabus/assets/30296511/1d5414ae-b48f-4745-b672-34fbc7e0ee9e)

Seria util proporcionar instrucciones para usar un linter actualizado y compatible con la ultima version de VSCode.

**Comment by Hernan4444** [comment]
Hola @endlessloop2 

Respecto a la parte de interfaces de desarrollo, lo que ocurre es que ese la parte de 

> Presiona Ctrl + Shift + P para abrir la paleta de comandos.
> Escribe o pega el comando Python: Select Linter y selecciona pycodestyle

Debe ser con un archivo python abierto. Si no tienes un archivo abierto, no te aparece, pero si abres cualquier archivo `.py` ahí si te aparecerá:

<img width="981" alt="image" src="https://github.com/IIC2233/Syllabus/assets/15641721/78178cc1-159f-48da-a03b-86ac717c67ca">

Respecto al punto 2, de ajuste de estilo automático, eso ya no aplicaba porque justamente se va a deprecar, y se nos olvidó eliminarlo de la wiki. Ahora si ya eliminamos esa parte de la wiki porque ya no está la forma automática que nosotros podamos recomendar, sino que ustedes, los estudiantes, se deben asegurar de ir cumpliendo las reglas a medida que programan el código. No obstante, si es que alguno/a encuentra una forma de verificar el PEP8 del curso de forma automática, no hay problema en compartir esa información 😄 

Saludosヾ(＾-＾)ノ
