### ISSUE TITLE
Duda sobre ortografía y redacción en las tareas

### ISSUE THREAD

**Issue by burgosibarra** [IIC2233/syllabus#5]
Hola! Quería saber si dentro de la pauta de evaluación de cada tarea está considerado la ortografía y redacción de los textos que imprima nuestro programa

**Comment by DCCollao** [comment]
Hola!

 El ítem que mencionas no está considerado directamente en la evaluación de la tarea, pero de todas maneras lo ideal es que quede lo más claro posible, ya que en caso de que llegase a significar un problema para corregir correctamente tu tarea, se te podría aplicar un descuento por criterio de ayudante. Puedes encontrar más detalles sobre esto en [Descuentos.md](https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md) (específicamente en la sección "Adicionales").

**Comment by burgosibarra** [comment]
Gracias!!
