### ISSUE TITLE
Duda sobre crear archivo con nombre: "Archivo.txt", "archivo.txt"

### ISSUE THREAD

**Issue by burgosibarra** [IIC2233/syllabus#50]
[Windows 10]
Hola! Tengo creado un código (no relacionado con la tarea) que pide un nombre, y crea un archivo .txt con ese nombre, y le imprime "hola". Al testear el código, si al comenzar en una carpeta vacía ejecuto el código e ingreso el nombre "archivo" todo funciona bien, o si al comenzar en una carpeta vacía ejecuto el código e ingreso el nombre "Archivo" también. Sin embargo, si ya existe uno de los dos archivos, ya sea "archivo" o "Archivo", al ejecutar e intentar ingresar la otra opción no crea el último archivo.
Ej: 
* Caso 1
1. Carpeta vacía
2. Ingreso "archivo"
3. Se crea "archivo.txt"
* Caso 2 
1. Carpeta vacía
2. Ingreso "Archivo"
3. Se crea "Archivo.txt"
* Caso 3
1. Carpeta con "archivo.txt"
2. Ingreso "Archivo"
3. No se crea "Archivo.txt"

He guardado este código por si necesitan que lo suba (desconozco si está prohibido subir ejemplos de códigos), si bien es cierto pareciera que no tiene relación con la tarea, me afecta en como funciona mi código en esta.
Pd: sí, he cerrado el archivo

**Comment by gatochico** [comment]
Hola! 

Este "problema" podría deberse a tu sistema operativo. Por ejemplo, Windows es _case insensitive_ con respecto a los nombres de archivos y directorios: `Archivo.txt `y `archivo.txt` corresponderían al mismo archivo, mientras que para sistemas operativos basados en Unix (como Ubuntu) serían 2 archivos distintos e independientes entre sí. 

Si es que usas Windows, lo que ocurre en el tercer caso es que cuando ingresas "Archivo", los contenidos iniciales de `archivo.txt` se sobreescriben con la información nueva (Si quieres comprobarlo, puedes ver que la información del `archivo.txt` original tendrá ahora la información nueva dentro de sí )

Quizás te preguntes: ¿Pero entonces, que ocurrirá si ingreso dos nombres de usuario que difieren en una mayúscula? En ese caso, puedes suponer que los nombres de usuario son _case insensitive_ (Usuario = usuario para tu programa) y queda a tu criterio el como manejar dichos casos: Avisar al jugador que el usuario ya existe y pedirle que ingrese otro nombre, o simplemente dejar que se ingrese un usuario 2 veces y en caso de que guarde la partida, esta sobreescriba cualquier partida anteriormente guardada. Recuerda poner tu decisión en el README!

Éxito y nos avisas cualquier cosa :) !

**Comment by burgosibarra** [comment]
Gracias!
