### ISSUE TITLE
Visualizar Prograpost

### ISSUE THREAD

**Issue by EmeraldMP** [IIC2233/syllabus#50]
Hola!

En el enunciado no están muy bien descrito si es que para ver los posts de los que uno sigue se tienen que ver todos los posts de todos los usuarios a los que uno sigue o uno elige el usuario (que sigue) y ve sólamente sus post. Por favor aclarar la duda o si ambas son válidas.

Saludos!

**Comment by gatochico** [comment]
Hola! La primera opción es la correcta: deberás mostrar de forma conjunta todos los posts de todos los usuarios a los que se sigue, como ocurriría en el muro de cualquier red social. (Idealmente, mostrando también quien es el autor de cada post junto con el post 🤓 ). 

Cualquier duda, quedamos atentos!

**Comment by rmaguilera** [comment]
es obligatorio presentarle al usuario la opción de ver los prograposts de manera ascendente (de más antiguo a más nuevo) o descendente (de más nuevo a más antiguo)?

**Comment by gatochico** [comment]
Al ser algo pedido de forma explícita en el enunciado, sí es obligatorio 🤓 (además, puedes ver que tiene puntaje asociado en la distribución de puntajes).
