### ISSUE TITLE
Formato CSV

### ISSUE THREAD

**Issue by jasantamaria** [IIC2233/syllabus#50]
Hola hay veces que excel trae los valores separados por "," (coma) y otras veces por ; (punto y coma) por defecto

Para efectos de la tarea cual de las 2 consideramos??

Gracias

**Comment by Arcoirisky** [comment]
Más que un Excel cualquiera, debes guiarte por el formato de los .csv que te entregamos :D 

Ese será tu guía ouo

**Comment by jasantamaria** [comment]
Lo que pasa es que los pc traen separadores de listas por defectos. Algunos vienen en  ";" y otros en ","

Esto puede ser defectuoso si escribo por ejemplo un .split(";") o un .split(",")

Se entiende???

**Comment by fdoflorenzano** [comment]
Hola @jasantamaria,

Creo entender lo que sucede. A veces ocurre que si abres estos CSV con algún programa, como Excel, este te cambia los separadores por como estaba configurado. La idea es que si eso pasa con algún programa que uses, **NO** lo abras con el para evitar que lo modifique.

Para efectos de la tarea, debes usar `.split(",")` inicialmente, ya que los archivos originales que fueron entregados tienen ese formato. Eso puedes revisarlo:

- [acciones.csv](https://raw.githubusercontent.com/IIC2233/syllabus/master/Tareas/T01/data/acciones.csv)
- [acciones_pendientes.csv](https://raw.githubusercontent.com/IIC2233/syllabus/master/Tareas/T01/data/acciones_pendientes.csv)
- [civilizaciones.csv](https://raw.githubusercontent.com/IIC2233/syllabus/master/Tareas/T01/data/civilizaciones.csv)
- [edificios.csv](https://raw.githubusercontent.com/IIC2233/syllabus/master/Tareas/T01/data/edificios.csv)

Espero eso resuelva tu duda.

**Comment by jasantamaria** [comment]
Gracias
