### ISSUE TITLE
Al invadir un planeta...

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#50]
Hola, 
Al invadir un planeta, los edificios de la raza invasora siguen dando el boost en la vida y ataque del ejército?

**Comment by ptflores1** [comment]
Hola!
En el enunciado dice:

> Si el planeta **invadido** dispone de una torre...

piensalo bien, si sigues con dudas nos dices :)

**Comment by jmwielandt** [comment]
Planeta A invade Planeta B
Planeta A cuenta con una torre
¿Ataque de A se ve incrementado en 1000 gracias a la torre?
Y lo mismo con el cuartel.

**Comment by ptflores1** [comment]
No se incrementa porque el planeta que esta siendo **invadido** en este caso es B y A esta invadiendo, esto es lo mas logico porque si estoy en mi propio planeta entonces la torre me ayuda a atacar pero si voy a invadir no me puedo llevar la torre. Espero se haya entendido.
Saludos !

**Comment by jmwielandt** [comment]
Ok, gracias
Y otra cosa, a la hora de calcular las unidades supervivientes no entra la vida de la torre y cuartel, en caso de haber, cierto?
