### ISSUE TITLE
¿Los 100 caracteres cuentan los espacios?

### ISSUE THREAD

**Issue by kunafuego** [IIC2233/syllabus#50]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

¡Hola! Si mi código tiene muchas indentaciones en una parte específica, **¿los 100 caracteres por línea cuentan las indentaciones o solo cuentan los caracteres desde donde termina la indentación?**] 
Desde ya muchas gracias

**Comment by cristobalnic** [comment]
Hola @kunafuego!

En la limitación de 100 caracteres por línea **si cuentan** las indentaciones, ya que también son caracteres (como cualquier otro). 
Esto tiene un trasfondo: cumplir esta regla de PEP8 permite que se mantenga más ordenado el código y sea más fácil de leer. Por esto, no tendría sentido permitir que las líneas tengan muchos espacios previos al "código a leer" aunque sean 100 caracteres.

Para ayudarte con esto los editores de texto suelen tener una regla (línea vertical) para que puedas visualizar el límite máximo en todo momento. A continuación te dejo la forma de activarla en Sublime y en VSCode.

**Sublime:** [ Menú de Sublime -> View -> Ruler -> 100 ]
![image](https://user-images.githubusercontent.com/48327806/112575954-16ca4200-8dd0-11eb-993c-addcb4dabb54.png)

**VSCode:** [Menú de VSCode -> File -> Settings -> editor:rulers] Aquí debes editar el archivo *settings.json* y escribir el máximo *100* en "editor.rulers" como se ve en el primer pantallazo.

![image](https://user-images.githubusercontent.com/48327806/112576305-c7384600-8dd0-11eb-8280-1b357f608ddd.png)

![image](https://user-images.githubusercontent.com/48327806/112576614-60fff300-8dd1-11eb-842d-bbe4e145f3d6.png)

Ojalá que esto te haya servido!

**Comment by kunafuego** [comment]
Ok gracias!

**Comment by fcbahamondes** [comment]
Holaa, ocupo vs code y me tira un error cuando la linea tiene mas de 79 caracteres, intente hacer lo que se propone en la issue pero no soluciona mi problema
