### ISSUE TITLE
Formateo de strings

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#50]
Hola! ¿Por qué en los contenidos de tuplas en el ejemplo de slicing imprimen: **print( "1: {0} ".format(a) )** y no simplemente: **print( "1:", a )**?
Y por qué ponen ese cero entre las llaves? Si funciona bien sin el cero.. es por alguna formalidad o regla que no conozco?

**Comment by furcelay** [comment]
Hola!
La idea de usar el método `.format()` de los *strings* es que así da mucha más flexibilidad que `print("texto", variable)`, además no siempre querremos printear el string. Por ejemplo con el sistema de formateo podemos controlar la alineación del texto con `<`, `>` y `^`:
```python
"{0:<10s}".format("Hola")
'Hola      '
```
```python
"{0:>10s}".format("Hola")
'      Hola'
```
```python
"{0:^10s}".format("Hola")
'   Hola   '
```
También puedes controlar el tipo de output, por ejemplo para redondear numeros con muchos decimales:
```python
"{0:1.3f}".format(1.231931213123)
'1.232'
```
Como ves después de los `:` va la alineación, luego el largo del output y luego el tipo (`s`->string, `f`->float, `i`->int).
El número que va antes del `:` tiene la función de indicar la posición del argumento al que corresponde:
```python
s = "Hola {2}!, mi nombre es {0} y tengo {1} años"
s.format("Felipe", 20, "Diego")
'Hola Diego!, mi nombre es Felipe y tengo 20 años'
```
Dado que podemos crear un string formateable como el anterior puedes reutilizarlo cambiando los valores que van en los `{}`, lo que es muy útil por ejemplo para imprimir tablas.

**Comment by furcelay** [comment]
Cambio el nombre de la issue para ser más descriptivo, si bien lo usan en la parte de tuplas ésto lo vimos anteriormente en los contenidos de la semana-00.
Saludos!

**Comment by kalarconvl** [comment]
Sii eso lo entendí en la parte de strings, pero no entiendo por qué en la parte de tuplas lo ponen así en vez que la otra forma más corta, porque en ese ejemplo no es necesario un format creo yo

**Comment by furcelay** [comment]
Tal como dices no es necesario, pero ponemos esas cosas para que no se olviden de los contenidos anteriores. Puedes usar la forma `print("1:", a)` cuando creas conveniente u omitir los corchetes si por ejemplo hay solo una variable, no hay problema con eso.

Saludos!

**Comment by kalarconvl** [comment]
Muchaas gracias!! Y con tu explicación me quedó mucho más claro el format!

**Comment by furcelay** [comment]
Que bien! 😄
