### ISSUE TITLE
Salir del programa

### ISSUE THREAD

**Issue by fgallard** [IIC2233/Syllabus#50]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Para que el menú salga del programa no hay que indicar nada? como que simplemente si escogen esa opción el programa ya no hace nada?

**Comment by individuocomunycorriente** [comment]
Hola!
Cuando seleccionas la opción salir del programa se debe termina la ejecución de main.py, si quieres puedes agregar un mensaje como "Saliendo de DCCultivo...", pero estrictamente por enunciado solo se exige que esa opción termine la ejecución del programa.
Saludos.
