### ISSUE TITLE
Ingresar encomiendas

### ISSUE THREAD

**Issue by jahernandez2** [IIC2233/Syllabus#50]
Al seleccionar la opción "Ingresar encomiendas", se ingresa un valor erróneo y luego se selecciona Continuar, se debe rellenar solo el valor erróneo o todos los valores de nuevo? No se entiende bien en el enunciado: _debe solicitar rellenar nuevamente el valor erróneo, de tal manera que se pueda llenar el resto de la información.

**Comment by Emiliax16** [comment]
Hola! se debe ingresar sólo el campo erróneo, el ejemplo de esa opción del menú muestra que si ingresas un valor incorrecto en el peso, inmediatamente se notifica y te pregunta si deseas continuar o cancelar. Ese continuar seguiría del mismo peso, no desde los inputs anteriores. Saludos!
