### ISSUE TITLE
Selección de casillas en el menú de juego #BUG  #MENÚ_DE_INICIO

### ISSUE THREAD

**Issue by k-i-r-b-y** [IIC2233/Syllabus#50]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
**Al momento de ingresar una casilla en el menú del juego mi tablero debería imprimir nuevamente este menú con la casilla desbloqueada y con el número correspondiente de bestias adyacentes, pero en vez de eso reemplaza toda la columna con dicho valor, independientemente del valor de la coordenada que indica la columna**

# Ejemplo de funcionamiento correcto --> [ [[■], [■], [■]], [[■], [■], [■]] ] = [ [[■], [N], [■]], [[■], [■], [■]] ]
# Ejemplo de funcionamiento mío --> [ [[■], [■], [■]], [[■], [■], [■]] ] = [ [[■], [N], [■]], [[■], [N], [■]] ]

**Comment by victoriaatria** [comment]
Hola! Recuerda que no debes subir líneas de tu código a una issue. Los ayudantes tenemos acceso a tu repo, así que tienes que hacer un push de tu repo y avisar por aquí cuando lo hagas para poder ayudarte con tu código!! Saludos
