### ISSUE TITLE
vsco max de carácteres por línea

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#500]
Hola, uso vsco y cada vez que excedo los 80 caracteres me advierte, hay alguna forma de cambiarlo para que me avise en los 100?

**Comment by furcelay** [comment]
Hola @Margarita-Paz !
Para configurar eso debes modificar tus *settings*.
1.  En la barra superior ve a *File* -> *Preferences* -> *Settings*.
2.  En el buscador introduce *python pylint args* y busca la opción que diga *Python › Linting: Pylint Args*
3.  Selecciona *Add Item* e introduce `--max-line-length=100`
4. En el buscador introduce *python formatting args* y busca la opción que diga *Python › Formatting: Autopep8 Args*
5.  Selecciona *Add Item* e introduce `--max-line-length=100`

Eso debería funcionar si usas *Linting* y *Autopep8* (alternativamente puedes modificar directamente el archivo `setup.json` pero es algo difícil de encontrar). Adjunto una imagen de ejemplo:

![image](https://user-images.githubusercontent.com/61999313/92949839-1d93f780-f432-11ea-9a08-5da91561aeff.png)

**Comment by YehudaGurovich** [comment]
Hay una issue al principio del semestre que explica lo que hay que agregar en el .json para que no te tire el error por si quieres hacerlo de esa forma.
