### ISSUE TITLE
Calcular características de los alumnos al inicio

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#500]
Hola!

Existen ciertas características de los alumnos que no dependen del tiempo ni del estado de la simulación. Por ejemplo, las horas que dedican los alumnos al ramo solo dependen de la cantidad de créditos que hayan tomado. Como generar estas características no depende del estado de la simulación, ¿podríamos generarlas al inicio de esta? De esta manera, no se necesitaría parar la simulación en un "evento" no existente al comienzo de cada semana para generar estos datos.

Saludos!

EDIT: Además, conocemos el máximo de semanas que pueden haber en la simulación. Si las notas de la T06 y del examen se llegan a atrasar, las notas finales del ramo se entregarían en la semana 19 de la simulación.

**Comment by iqacevedo** [comment]
Hola

Respecto a las horas que dedican los alumnos al ramo, en el enunciado se indica que estas varían semana a semana, en el cuadro 1 se entrega un rango de horas, por lo cual las horas que dedica un alumno estarán dentro de ese rango pero no necesariamente tiene que ser la misma cantidad de horas todas las semanas. Además, algunos de los eventos no programados influyen directamente en las horas que le dedican los alumnos al curso, ya que los alumnos no trabajan por algunos días cuando estos ocurren.

No entendiendo que buscas preguntar con el EDIT, podrías replantearlo?

Saludos !

**Comment by akaminetzkyp** [comment]
Hola! Muchas gracias por tu respuesta!

Las horas que se generan al comienzo de la simulación son todas distintas. Se me olvidó agregar que las horas por semanas serían modificadas si ocurre algún evento que amerite esto. Por ejemplo, partimos con una lista con 19 elementos, donde cada elemento representa la cantidad de horas disponibles para una semana dada (`horas_por_semana = [10, 9, 15, 13, 11, 13, ...]`). Los valores de esta lista son asignados utilizando `random.randint`. En caso que ocurra algún evento que deba modificar las horas, se cambia directamente en `horas_por_semana`.

El edit no era una pregunta. Era un comentario extra que afirmaba que siempre vamos a saber el tiempo máximo de simulación y, en consecuencia, el largo de `horas_por_semana`.

Perdón si no me expliqué bien! 😄
Saludos!

**Comment by iqacevedo** [comment]
Ahora entiendo a lo que te referías, es totalmente válido lo que dices. Sin embargo, no es muy óptimo hay mejores maneras de hacer esa parte que no requieren que guardes una lista con las horas por semana de cada alumno (hint: properties 😄 ).

Saludos !

**Comment by akaminetzkyp** [comment]
Perfecto. Muchas gracias! 😄

**Comment by acrojas2** [comment]
Hola:
@iqacevedo si bien dices que las horas van cambiando semana a semana, Ht y Hs cambian semana a semana según la materia, sin embargo para calcular el progreso de una tarea por ejemplo necesariamente se requiere los Ht de las materias que son de la tarea (2 materias) y no veo la utilidad de la property ya que siempre me estaría entregando el valor actualizado...  Por otra parte escuchar al profesor aumenta el manejo de contenidos en un 10% de lo que lleva hasta ese día y para la evaluación que tendrá en ese momento.  Entonces, lo que no entiendo (y quizás esto sea una pregunta de materia), porqué la property es conveniente si para el primer caso siempre que yo quiera al atributo Ht me dará el correspondiente al de la semana actual y para el segundo caso,  hay mas de una forma de settear el atributo. 
Espero se entienda mi duda :/
Saludos!

**Comment by iqacevedo** [comment]
Hola,
@acrojas2, lo bueno de las properties es que puedes controlar lo que te retornan y cuando actualizarlas. La idea de usar properties es que no guardan información innecesaria (en este caso si estoy en el semana 3 ya no necesito cuantas horas estudie la semana 1 y tampoco cuantas estudiaré en la semana 6). Además, como al fin y al cabo se esta llamando una función cuando una property es llamada, puedes hacer más cosas que simplemente retornar el valor, como realizar pasos intermedios para guardar información o lo que se te ocurra, pero esto ya depende de como estés modelando el problema y como busques resolverlo.

Espero haber entendido tu duda (y haberla respondido) :sweat_smile:.
Saludos !
