### ISSUE TITLE
¿Puedo tener False en elementos prohibidos, si la función no se ejecuta?

### ISSUE THREAD

**Issue by edupavez** [IIC2233/Syllabus#500]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/299)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/298)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Sobre el test de elementos prohibidos, si aparece algo False significa que se está ocupando un elemento prohibido y es un 1, incluso si dicho elemento en verdad no se utiliza? Por que me aparece False en un par de funciones donde usé slice para sacar el año en la fecha de nacimiento y en vez de borrar lo que hice en la función escribí un return al inicio de esta, de modo que el elemento que estaría prohibido nunca será ejecutado por el código,  pensando que esto haría que no se considere esa parte del código, pero aún así me aparece False en los test. Por lo tanto no sé si esto afecta la tarea, ya que la corrección es automática. Pregunto por que tengo dos commits, y el commit donde al final borré el código False está con atraso ya que no me percaté inmediatamente del problema. Debería usar ese commit atrasado?

**Comment by diegobas10** [comment]
Hola buenas @edupavez, 
A la hora de corregir las tareas si se detectaría el uso de elementos prohibidos, pero no es una nota automática 1, si no que solo se anularían los items en donde se detecta el uso de elementos prohibidos, entonces respecto a tu situación te recomiendo revisar que te conviene más el commit con atraso o solo tener malo los tests en que te aparece False.
Saludos, quedo atento a cualquier duda.

**Comment by edupavez** [comment]
Gracias por la aclaración.
