### ISSUE TITLE
Test 05 solucion duda con su solucion

### ISSUE THREAD

**Issue by EhytanC** [IIC2233/Syllabus#500]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Estuve revisando el test 05 carga de datos y no he podido resolverlo, tratando de descubrir cual es mi error me puse a ver la solución del test_0 de todos estos test, el primero test tiene como solución CLIENTES_DESPUES_HORA_S_1 = "4 49 6 10 39 50 7 33 40 21 8 29 25 18 48 20" y me puse a revisar los id de el archivo con la siguiente ruta desde la carpeta de la tarea data\s\pedidos.csv, el test_0 de estos test tiene como parámetro de hora '18:00' y el pedido con el id 8 tiene es el siguiente (8, 11, 39, 2024-01-03, 08:10:15) por lo que no entiendo porque debe ser parte del resultado esperado.

**Comment by Vicente1824** [comment]
¡Hola @EhytanC 😊! Ojo, porque el enunciado dice "Retorna un str con el id **de los clientes**", y según lo que dices, estás revisando el id de los pedidos. Por ejemplo en el test_0, el pedido del id **de cliente** `4` fue realizado a las `21:36:08`. En el caso del pedido con id de cliente `8`, hay 2 pedidos que tienen este id, y uno de ellos fue hecho a las `23:06:31`, por lo que aplica en ese caso. ¡Espero que te haya sido de ayuda y puedes comentar si tienes otra duda con el mismo tema!
