### ISSUE TITLE
.qt_for_python (Carpeta creada automaticamente)

### ISSUE THREAD

**Issue by lpalacios1** [IIC2233/syllabus#500]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! De manera automática se me generó la carpeta .qt_for_python y quisiera saber si esta carpeta se puede borrar o agregar al gitignore. Contiene el codigo de las ventanas creadas en el Qt Designer por eso nose si se puede borrar o poner en el git ignore. 

Gracias!

**Comment by catalina-arcila** [comment]
Hola @lpalacios1, si es que la carpeta contiende los archivos *.ui* que genera el *Qt Designer* no debes colocarlo en el *.gitignore*. Lo importante es que especifiques que contiene esa carpeta en el README. Éxito en la tarea! 😄

**Comment by lpalacios1** [comment]
Hola! Noo, la carpeta contiene archivos de python

**Comment by catalina-arcila** [comment]
Si es necesario para correr tu código de la tarea y que cumpla su funcionamiento, no lo coloques en *.gitignore*.
Sorry la demora :(
