### ISSUE TITLE
socket

### ISSUE THREAD

**Issue by juakoke** [IIC2233/syllabus#500]
Hola, para el servidor, intento hacer "self.host=self.socket.gethostname()" donde self.socket=socket() definido anteriormente. Lo que ocurre es que el programa me dice que self.socket no tiene ese atributo (gethostname), y este esta en los contenidos, ¿como puedo solucionar eso?

**Comment by ariel-m-s** [comment]
Hola @juakoke!

`gethostname` no es un atributo ni método de la clase `socket` del módulo `socket`, sino que es una función perteneciente a dicho módulo, que retorna un _string_ con el _hostname_ local. A continuación te muestro un ejemplo.

```python
import socket

socket.gethostname()  # la manera correcta
socket.socket().gethostname()  # la manera incorrecta
```

Para más información siempre puedes recurrir a la [documentación oficial](https://docs.python.org/2/library/socket.html#socket.getaddrinfo).

Saludos.
