### ISSUE TITLE
Tiempo desplazamiento entre colas

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2233/Syllabus#500]
Si un alumno decide dejar una cola, ¿asumimos que se cambia de cola de manera inmediata, o consideramos el tiempo de ir a comprar comida? (Lo mismo para el desplazamiento de una cola al quickdevil)

**Comment by cilopez** [comment]
Considera que se cambia de cola de manera inmediata en ese caso, al igual que si va a _Quick Devil_
