### ISSUE TITLE
No me aparece un QRadioButton

### ISSUE THREAD

**Issue by crvargasu** [IIC2233/syllabus#501]
Para lograr hacer aparecer una sala para los jugadores en linea estoy intentando hacer aparecer un QRadioButton mandando una señal desde el cliente a el front, sin embargo no sé por qué no me aparece el QRadioButton, a pesar de que con la señal se entra a la funcion y se ejecuta todo, solo no me aparece en la pantalla.
Al intentar poner .show() el interfaz se queda pegado

**Comment by bimartinez** [comment]
Hola @crvargasu 

Perdón por la demora :cry: Podrías contarme mas acerca de tu problema? A primera vista no se me ocurre cual podría ser el conflicto, tal vez algún problema con el parent del QRadioButton. Puedes subir el código y en el commit indicar las lineas y archivos donde haces uso de esto. Avísame apenas subas los archivos :floppy_disk: 

Saludos y nuevamente disculpas :frowning_face:

**Comment by crvargasu** [comment]
Cuando intento crear un boton, este no se me muestra en el front, la señal se mete en la función y crea el boton, pero no lo muestra en el front. Y si le pongo .show() el programa se queda pegado

**Comment by crvargasu** [comment]
Ya subí el codigo, la funcion de crear el Boton son desde la 108 hasta la 124 del front

**Comment by bimartinez** [comment]
Ya buena! Dame un rato para revisar que puede estar pasando :smile:

**Comment by crvargasu** [comment]
Si le pones # a todo y solo intentas crear el boton, se puede ver mejor el problema.
tipo:
    def crear_botones(self, n):
        boton = QRadioButton(self)
        boton.show()
Así el programa se pega

def crear_botones(self, n):
        boton = QRadioButton(self)
Así el programa no se pega, pero no muestra nada

**Comment by bimartinez** [comment]
Ya revisé tu código y lo único que hice fue descomentar la linea 120 y 153 del archivo `front.py` (respecto a tu commit `2dc86a2`) y me funcionó sin problemas, en el caso que a ti no te funcione (me parecería muy raro) avísame y sube la última versión que tengas. 

Saludos!

**Comment by crvargasu** [comment]
Lo que pasa es que esa linea llama a la funcion directamente desde el front, en lo cual no hay problema

El problema es cuando intentas crear un boton por medio de una señal

**Comment by crvargasu** [comment]
No sé si se entiende, la idea es que el servidor mande la señal para que se pueda crear el boton, la linea que estas descomentando esta llamando a la funcion directamente sin salir del front, lo cual funciona, pero ese no era el problema!!

**Comment by bimartinez** [comment]
Yayaya entiendo, disculpa. Puedes dejar todo armado con las señales y subirlo porfavor (limpia un poco el código para que sea mas claro poder identificar donde están las conexiones)

Avísame :smile:

**Comment by crvargasu** [comment]
ok

**Comment by crvargasu** [comment]
Ya lo resubí, todo armado y limpie el codigo de los comentarios

**Comment by bimartinez** [comment]
Ya, ahora si!

Al correr tu programa e intentar agregar el `QRadioButton`, me aparece el error `QObject::setParent: Cannot set parent, new parent is in a different thread`. Esto es debido a que estás intentando modificar la ventana directamente del *backend*, por lo cual estás haciendo mal uso de señales. Asi como estas comunicando frontend con backend a través de señales, la comunicación backend - frontend debe ser de la misma manera. Dale una vuelta a la manera en que lo estas haciendo. Si deseas ver mas información te dejo [esta entrada](https://stackoverflow.com/questions/13420931/pyqt-modify-gui-from-another-thread) de *StackOverFlow*.

Saludos!

**Comment by crvargasu** [comment]
Buena! Ahora me doy cuenta, me dejé guiar mucho por la ayudantía y se me olvidó esa parte

Muchas Gracias!!
