### ISSUE TITLE
Entregable formato zip, aceptable?

### ISSUE THREAD

**Issue by valeria-adasme** [IIC2233/Syllabus#501]
Hola :) Saben, me gusta añadir imágenes (algunas hechas por mí, otras no) en mis entregables, pero para que se vean en el archivo .md debo tenerlas en la misma carpeta, y por eso antes lo subía en formato zip (no decía nada la instrucción, decía que cualquier formato era aceptable). 

Pero ahora el cuestionario dice sólo formato pdf o md :( y yo les había hecho una imagen bien buena que quería subir xD ¿Cómo le hago? El cuestionario me lo acepta para subir, pero no sé si eso hará que no me cuente como entregado o no.

Gracias

**Comment by DquezadaO** [comment]
y si intentas convertirlo a pdf? Solo una idea no soy ayudante, de cualquier forma:

try:
http://www.markdowntopdf.com 🙄
except:
pass

**Comment by valeria-adasme** [comment]
Eso me han recomendado, pero no encuentro cómo convertirlo en pdf cuando la imagen es externa (no está por un enlace, sino que porque llamo al archivo en la misma carpeta)
