### ISSUE TITLE
Variable en for

### ISSUE THREAD

**Issue by mc-cari** [IIC2233/syllabus#501]
Hola,

Si uso 
`For criatura in criaturas:
    #Modificación criatura`
criatura es solo una variable local cuando la modifico o tambien cambia en el arreglo criaturas?

**Comment by jeschuwirth** [comment]
hola @mc-cari,

Aunque no lo creas tu pregunta no es tan sencilla de responder:

Recuerdas en intro cuando reasignabas variables con otra variable, en varios casos (int, float, string, etc) se comporta de la siguiente manera:
```
a = 5
b = a
b += 3
print(a)   #5
print(b)   #8
```

Sin embargo al trabajar con otros tipos de variables (listas, diccionario, clases) estas se comportan como una misma entidad:

```
a = [1,2,3,4,5]
b = a
b.append(6)
print(a)   #[1,2,3,4,5,6]
print(b)   #[1,2,3,4,5,6]
```

```
class Letra:
    def __init__(self, valor):
        self.valor = valor

a = Letra("A")
b = a
b.valor = "B"
print(a.valor)    #B
print(b.valor)    #B
```

Al hacer un `for criatura in criaturas:`, estas "haciendo" criatura = criaturas[0], luego criatura = criaturas[1] y así.

Por lo tanto dependiendo del tipo de variables que contiene tu lista criaturas los cambios van a ser también en el arreglo o no.

Espero haya quedado claro, cualquier duda sigue comentando :)

Éxito!

**Comment by mc-cari** [comment]
Si esta claro, gracias
