### ISSUE TITLE
Duda sobre como reemplazar un layout

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#501]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Mi duda es de pyqt5, estaba puliendo la ventana de rankings y me di cuenta que si vuelvo a abrir la ventana
los labels no se reemplazan, como que se escriben uno sobre otro, en consola sale aviso de que estoy
intentando colocar un layout en una ventana que ya tiene un layout, así que supongo que ese es el problema.

Hay alguna forma de cambiar/resetear el layout de una ventana? (esta ventana la cree como subclase de QWidget)

**Comment by JadrinaDA** [comment]
Hola! Una vez que pones un layout no deberías tener que reemplazarlo. Lo que si puedes hacer es rehacer los labels, o hacer un número determinado y simplemente actualizar el valor (por ejemplo siempre mostrar los mejores diez). Para que no se escriban los textos unos sobre otros asegurate de borrarlos al cerrar la ventana o crear una nueva instancia de la ventana cada vez. Avisame si te sirven estos consejos.
Saludos.
