### ISSUE TITLE
Atraso subida notas coordinador

### ISSUE THREAD

**Issue by fcgfaura** [IIC2233/Syllabus#501]
El coordinador puede atrasar la subida de una nota ya atrasada?

**Comment by nivek0o0** [comment]
Lo que yo entiendo del enunciado es que solo se puede atrasar 1 vez una evaluación, es decir, publicarla en 14 + 2 a 5 días desde el momento en que se rinde dicha evaluación.

**Comment by FernandoPieressa** [comment]
Hola! Lo que dijo @nivek0o0 esta en lo correcto, solo puede ser atrasada 1 vez.

Saludos!

**Comment by fcgfaura** [comment]
Fantástico!, gracias a ambos!
