### ISSUE TITLE
Nombre de un diccionario en parametros.py

### ISSUE THREAD

**Issue by nicolecll** [IIC2233/syllabus#502]
Hola, si deseo crear un diccionario en parametros.py para almacenar de mejor manera algunos valores, ¿el diccionario también debe tener ESTE_FORMATO? o no es necesario, ya que los parámetros dentro de el si lo tienen?

**Comment by retamalcito** [comment]
¡Hola @nicolecll!

Si creas un diccionario dentro de `parametros.py`, su nombre **sí** debe seguir `ESTE_FORMATO`, ya que todos los parámetros encontrados en este módulo deben seguirlo.

¡Éxito! 🥇

**Comment by nicolecll** [comment]
Perfecto! Muchas gracias
