### ISSUE TITLE
[Duda pequeña] Nombre parámetros

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#502]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo la duda si podemos cambiar un poco el nombre de los parámetros que dice el enunciado. Esto para que todos sigan el formato más similar posible. Por ejemplo, existen los parámetros DURACION_INTRO y otro que es APARICION_{INTRO} (con las llaves incluidas).

Saludos!

**Comment by Juampisaez** [comment]
Hola @jamigone 
Si te entendi bien, lo que quieres es especificarlo un poco. En el enunciado, en el footnote de la pagina 5 se explica un poco. La idea es que despues del guion pongas la dificultad (sin las llaves).

Espero quede mas claro :)

**Comment by jamigone** [comment]
Genial! Sí había visto esa footnote, había entendido que debía ir con la llaves jajaja. Gracias!
