### ISSUE TITLE
Efecto hambre varía en método de las DCCriaturas

### ISSUE THREAD

**Issue by CatalinaGoldsack** [IIC2233/syllabus#502]
Hola! Me llamó la atención la lógica del "efecto hambre"
En "alimentarse" este es 0 si está satisfecho y 15 si está hambriento, mientras que 
en "escaparse" este es 0 si está satisfecho y 20 si está hambriento.
Los consideraré como diferentes parámetros nomás, pero me pareció curioso que variara jajaja :smile:

**Comment by JosefaPaz** [comment]
¡ Hola @CatalinaGoldsack ! 

Exacto, está súper que lo consideres como parámetros diferentes 🐱.  Esto ocurre porque el efecto hambre en situaciones diferentes no tiene porqué obtener los mismos valores, y como son aplicadas en funciones diferentes, tiene sentido que difieran.

Gracias por la acotación, éxito en la tarea 😸
