### ISSUE TITLE
Edad de los clientes

### ISSUE THREAD

**Issue by akrebs2** [IIC2233/Syllabus#502]
Hola. Acabo de leer el enunciado y me he dado cuenta que no se habla de dónde se obtienen las edades de los clientes. Se dice que debemos generar sus nombres y apellidos pero no se habla de su edad. Esta información tampoco está contenida en las bases de datos entregadas.
Pregunto esto porque:

> un niño que no vomitó llorará con una probabilidad inversamente proporcional a su edad

¿Qué se hace al respecto?

Gracias!

**Comment by agustincampeny** [comment]
Reabro este issue ya que tengo la misma duda, bastará con usar distribución uniforme para los niños?
