### ISSUE TITLE
Cambio en el enunciado

### ISSUE THREAD

**Issue by cilopez** [IIC2233/Syllabus#502]
He actualizado el enunciado de la Tarea 4, principalmente corregimos ciertos errores e hicimos más explícitas ciertas cosas que ustedes nos señalaron en las _issues_, saludos

**Comment by valeria-adasme** [comment]
el único cambio es el de la función putrefacción? xD para no tener que reimprimirlo

**Comment by iqacevedo** [comment]
@valeria-adasme hay otros cambios más, son los que se han indicado en las issues. Por ejemplo está el cambio en las horas de dicidir ir a comer (pasó de 13, 14, 15 a 12, 13, 14). Si lees todas las issues y tienes claro que cambio, no tendrías que reimprimirlo.

Saludos !
