### ISSUE TITLE
nombres de salas

### ISSUE THREAD

**Issue by maureenmaremaa** [IIC2233/syllabus#502]
Hola! En caso de que se cierre una sala, es necesario que la próxima sala que se crea tome este nombre? 
Por ejemplo, si tengo estas salas:
 Sala1
 Sala2
 Sala3
Si la Sala2 cierra, es necesario que la próxima sala que se crea tenga el nombre "Sala2" o podría llamarse "Sala4"?
Gracias

**Comment by DCCollao** [comment]
Hola!
Mientras te asegures de que no existan dos salas con el mismo nombre, queda a tu criterio cómo lo hagas, por lo tanto no es necesario que la nueva sala tome el nombre de la que se cerró. 
Éxito!
