### ISSUE TITLE
Uso de .__replace()

### ISSUE THREAD

**Issue by sheinkzx** [IIC2233/Syllabus#502]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Quisiera saber si es posible de usar la funcion ._replace() para modificar elementos de una tupla?, esto ya que los test case publicos  dan bien, pero los privados no se tendria certeza de lo mismo

**Comment by kbetelgeuse** [comment]
Hola @sheinkzx!
¿Podrías mostrar un ejemplo de código en el que utilices esta función para implementar lo que dices?

**Comment by sheinkzx** [comment]
![imagen](https://github.com/user-attachments/assets/cb59cd28-2d79-440b-8bfd-ad36e16e590b)
de esta manera

**Comment by kbetelgeuse** [comment]
No debería haber problemas si utilizas la función `_replace` para realizar lo que comentas en relación con los tests, ya sea privados o públicos, ya que esta permite obtener una nueva `namedtuple` del mismo "tipo" que la original (con eventuales cambios en los valores de los campos asignados inicialmente, que en el caso del ejemplo que muestras sería `x.precio`). Lo anterior sería una forma de las varias que hay de obtener una nueva `namedtuple` a partir de los valores que tenía otra.

**Comment by sheinkzx** [comment]
Muchas gracias se lo agradezco!!!
