### ISSUE TITLE
Al instanciar un boton, KeyPressEvent deja de funcionar

### ISSUE THREAD

**Issue by jac-34** [IIC2233/syllabus#502]
Hola,

En mi ventana juego, estoy programando la parte del boton pausa y boton salir y me surgio un problema, al instanciar el QPushButton en el Widget, este deja de "leer" el KeyPressEvent, lo que significa que mi jugador ya no se mueve. Si me podrian exlicar que solucion puede haber por favor.

Lo otro es, dado este mismo tema, que metodo tiene QTimer para dejarlo en pausa?

Muchas Gracias

**Comment by jac-34** [comment]
Ya lo arregle, gracias.

**Comment by jedulcic** [comment]
Hola, que error tenias? Me paso algo similar
