### ISSUE TITLE
Bonus contraseña

### ISSUE THREAD

**Issue by fivaldivia** [IIC2233/syllabus#503]
Hola, quería saber si implemento el bonus de las contraseñas, cuando un cliente se registra, si el nombre de usuario ya existe no permito que se registre, por lo que nunca van a haber 2 usuarios con el mismo nombre. Esto reemplazaría lo de 5.2 del enunciado: 2. "El nombre de usuario ingresado si se encuentra registrado y actualmente esta desconectado. Esto implica que algun cliente ya ha ingresado al juego haciendo uso de ese nombre de usuario. ..." y lo del punto 3. también. Estaría correcto? Muchas gracias.

**Comment by gatochico** [comment]
Hola! Si implementas contraseñas, igual deberás tomar en cuenta e implementar esos dos puntos, pero en vez de en la sección de **Registro**, deberá estar en la sección de **Inicio** (Recuerda que si haces bonus de contraseñas, el usuario tiene la opcion de registrarse o iniciar sesión con un par usuario/contraseña). Piensa que un usuario puede estar jugando, y por otro lado otra persona podría querer entrar a su cuenta y saber su contraseña, por lo que no deberías dejarlo entrar al haber ya una persona conectada con esas credenciales.

Saludos y exito!
