### ISSUE TITLE
Detalle Eventos

### ISSUE THREAD

**Issue by maxfreymo** [IIC2233/Syllabus#503]
¿Cuál es el nivel de detalle que debe tener la descripción de los eventos cuándo ocurre?
(Específicamente en la parte de cambios/actualizaciones)

Ejemplo:
Reunión Ayudantes Docencia | Lunes, Día 1, Semana 1 |   Se determina
nivel de exigencia de la actividad de la semana. Se eligen 2 ayudantes
al azar para la ayudantía de la semana

¿Debería colocar cuál es el nivel de exigencia? ¿Debería decir el nombre de los ayudantes seleccionados?

**Comment by sebacruzd** [comment]
Hola,

Mientras más completo sea el detalle mejor, pero no debe ser excesivo. Anota en el README.md tu decisión respecto a esto, queda a tu criterio.

Saludos!
