### ISSUE TITLE
Problemas Qt designer

### ISSUE THREAD

**Issue by gonzaga2000** [IIC2233/syllabus#503]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! tengo un error cuando corro un archivo de Qt designer. en la aplicación me salen los labels normales, pero cuando corro el código, los labels me salen cortados. Alguna idea de que puede ser?

Esto es lo que tengo en Qt designer:
<img width="278" alt="designer" src="https://user-images.githubusercontent.com/80769344/119428042-2d125280-bcda-11eb-99d4-3c497a01d018.png">

y esto me sale cuando lo corro en vscode:
<img width="146" alt="pyth" src="https://user-images.githubusercontent.com/80769344/119428100-474c3080-bcda-11eb-8069-2b76c6306d0a.png">

**Comment by tqmbanados** [comment]
Hola! Lo más probable es que en Qt designer la ventana se asuma con ciertas dimensiones, que no son las mismas que estás ocupando en la Ventana que escribes en tu código. Si es que estás usando QLayouts (lo cual es muy recomendable), también es probable que ocurran ese tipo de cosas. 

Te recomiendo revisar las dimensiones de la Ventana, y los atributos del Layout si es que usas uno. Si revisas la documentación de los Layout, hay varios métodos y atributos que tienen que ver con el "espacio" asignado entre cada widget. El nombre del atributo es ```spacing``` y se cambia con ```setSpacing```. 

Lo más probable es que sólo sea un problema de agrandar la Ventana. Si esos botones están en un Widget dentro de una ventana, tienes que ver como hacer que ese Widget ocupe más espacio dentro de la ventana. 

Espero haberte sido de ayuda! Si lo anterior no te funciona cuéntame para que podamos probar otras opciones 😸

**Comment by gonzaga2000** [comment]
No entiendo muy bien la parte de que las dimensiones de la ventana que ocupo en mi código son distintas a las que asume Qt designer.  En mi código no defino las dimensiones de la ventana, las dimensiones las defini en Qt designer.

**Comment by tqmbanados** [comment]
Oka, si es ese el caso, lo más probable es que el problema sea el otro. Esta Ventana es independiente, o está contenida dentro de otra?

Para ejemplificar, en una app, tienes la ventana principal, que contiene varias "subventanas". Si es una "subventana", es posible que sus dimensiones cambien para poder caber dentro de la ventana principal.

Revisa también lo de los layouts! Por las imágenes que mandaste, lo más probable es que les falte un poco de espacio a esos layouts. Te recomiendo revisar la propiedad de ```QLabel``` ```minimumSize```. Esta se refiere al tamaño mínimo que puede tener el QLabel, y se cambia con ```setMinimumSize```. En la documentación salen más detalles al respecto, pero por el momento podrías setear un ```minimumSize``` a esos labels lo suficientemente grande para que quepa todo el texto (*hint: se puede editar este atributo directamente desde designer).

**Comment by tqmbanados** [comment]
Hola! Recordé otra cosa, que quizás haya sido el problema desde el inicio 😟. Prueba setear el atributo ```scaledContents``` de los ```QLabel``` a ```True```. Como es usual en Qt, esto se hace con un método setter ```setScaledContents```. Si es que esos ``QLabel```cargan imágenes, explicaría por que se te cortan al haber un cambio en el tamaño!

**Comment by gonzaga2000** [comment]
Hola! intente todo lo que me dijiste y aun me siguen saliendo distintos los labels, alguna otra idea de cual puede ser el error?

**Comment by tqmbanados** [comment]
Así a primeras no se me ocurre. ¿Podrías hacer push para revisar tu código? Cuéntame cual es el archivo de designer y en qué archivo esta la clase que estas implementando.

**Comment by tqmbanados** [comment]
Hola! Pregunté a otrxs ayudantes y me dijeron que puede hacer algo de la configuración de Windows jajaja. Así que si tienes windows, prueba cambiar el tamaño de la fuente por defecto. Esto se hace en configuración ---> accesibilidad (Ease of Access en inglés). Ahí hay un setting para hacer más grande el texto que debería estar en 100%, pero windows a veces lo cambia por defecto. Prueba ver si es ese el problema!
Si no tienes windows entonces veré si encuentro algo en tu código 😸.

**Comment by pedroriosg** [comment]
Hola @gonzaga2000 ,

Prueba escribiendo estas líneas al inicio de tu código. Debería solucionar el problema.

`os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "0"`
`os.environ["QT_SCALE_FACTOR"] = "1"`
`os.environ["QT_SCREEN_SCALE_FACTORS"] = "2"`


Saludos y avísame si te funciona por favor ✌️

**Comment by gonzaga2000** [comment]
@pedroriosg alfinal pude hacerlo ajustando la escala al 100%. Cuendo pongo las lineas que me mandaste la ventana que se abre es gigante, ocupa mas que toda la pantalla jajajajaj.

**Comment by pedroriosg** [comment]
Buena! Puedes poner en este mismo hilo que solución usaste por si le sirve a alguien más?

**Comment by gonzaga2000** [comment]
@pedroriosg  obvio! Para poder solucionar el problema tuve que ir a:  configuracion ---> Pantalla ---> Escala y distribucion.  Tuve que ponerla en 100% , en mi caso por default esta en 150% asique no se aplica para todos cambiarla a 100%. Al hacer este cambio toda la pantalla se hace mas chica, asique idealmente hay que usarla solo al trabajar en la tarea, y cuando se deje de hacer, volver a cambiar la escala al valor establecido por default. Para que mi codigo no se viera tan chico tambien le puse zoom a vscode.

**Comment by gonzaga2000** [comment]
otra cosa que hice para verificar que las ventanas fuesen del mismo porte fue asegurarme de que la escala de "Preview" de Qt designer estuviese en 100%. Se hace de esta forma, en desginer se va a: settings --> preferences --> Forms --> hacer tick en preview zoom --> ajustar en 100%. De esta forma estando en Qt desginer, uno puede apretar ctrl +R y te va a aparecer una previsualizacion de la ventana, esta previsualizacion es como se deberia ver una vez corrido el codigo.
