### ISSUE TITLE
Error test 11

### ISSUE THREAD

**Issue by JohanM-cyber** [IIC2233/Syllabus#503]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Creo que hay un error en el test de la función `pizza_mas_vendida_del_dia()` de la tarea, ya que al realizar el `test_2` de esta función, el resultado esperado es: `['Tradicional Tierno Dorado con Cautela', 'Maravilloso Delicioso Fresco con Tradición']`. Sin embargo, al ejecutar mi código, el resultado obtenido es: `['Jugoso Sublime Magnífico con Pureza']`.

Al hacer el debugging de la funcion, encontré que en el archivo, las pizzas `['Tradicional Tierno Dorado con Cautela', 'Maravilloso Delicioso Fresco con Tradición']` tienen una cantidad de 10 y 8 pizzas respectivamente, mientras que `['Jugoso Sublime Magnífico con Pureza']` tiene 15 pizzas. 

Comenté esta duda con el profesor Hernán en la clase de ayer, y tras revisar mi código, le pareció extraño que fallara, ya que todo parecía estar en orden y no había nada que indicara que estuviera ocurriendo un fallo. Por ello, me pidió que subiera un issue para que se revisara:

1. Que el test esté efectivamente correcto.
2. Se revisara mi código para ver si es que había un fallo mío.

Adicionalmente al implementar la función `pizza_del_mes()`, que pide exactamente lo mismo que `pizza_mas_vendida_del_dia()` (salvo que en lugar del día solicita el mes), usé **EXACTAMENTE** el mismo código, solo cambiando los nombres de las variables. Y oh sorpresa este se ejecutó sin problemas, lo cual puede indicar efectivamente un error en el test de `pizza_mas_vendida_del_dia()`.

#### Consideraciones adicionales
Mi repositorio personal no está en esta cuenta, sino en la cuenta **Johan-10** (esto debido a un error con mi cuenta principal). Por favor, revisen el código desde allí.

Y coloque varios comentarios en mi código para facilitar su entendimiento y mejorar el debugging.

**Comment by FradexMF** [comment]
Hola @JohanM-cyber!
Gracias por los comentarios en tu código, fueron muy útiles!

Por lo que puedo ver en tu código estas filtrando los pedidos únicamente por el número del día cuando debería ser por toda la fecha. 

En cuanto a que funcione para la funcion `pizza_del_mes()`, esto puede ser debido a que los datos dados solo son del año 2024 y por lo tanto solo hay un mes que coincide.

 Avísame si esto resuelve tu problema!

**Comment by JohanM-cyber** [comment]
Si! lo acabo de mirar, es justamente el error que tu mencionas, ahora si se ejecutan bien los test. 
Puedo sugerir que se cambie el enunciado para que se entienda bien que se solicita comparar toda la fecha y no solo el día (*^▽^*) porque hasta el profe y el ayudante cayeron en ese error al leer el enunciado más de una vez.
