### ISSUE TITLE
flujo de código Menu DCCriaturas 

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#503]
Hola! En el menú de criaturas el enunciado dice "En caso de tener suficiente energía para la acción, una vez seleccionada se debe efectuar y descontar el costo energético, en este punto no es necesario un menú para volver atrás o salir. ". Esto quiere decir que mi código debe finalizar una vez realizada la acción ya sea de sanar, alimento, etc ; o a que se refiere?

**Comment by matiasmasjuan** [comment]
Hola @RonaldoSosa !

Lo que el enunciado quiere decir, es que si tu efectúas alguna acción en donde **si** tienes **energía suficiente** para **ejercerla** , simplemente se realiza y no es necesario **implementar** nuevamente las opciones de **volver atrás o salir**, ya que la idea es simplemente **notificar** que se hizo la acción, y **volver al menú anterior** (En este caso el ***Menú cuidar DCCriaturas***). Por **ningún** motivo tu código debe finalizar, a menos que sea mediante la opción **salir**.

Espero haber respondido a tu pregunta y mucho éxito con tu tarea! 😄

**Comment by RonaldoSosa** [comment]
Yaaa vale me quedo claro !!!Gracias

**Comment by anamanzana** [comment]
Hola @matiasmasjuan 

No debería volver al menu Acciones después de realizar la opción en vez del Menu DCCriaturas?

**Comment by matiasmasjuan** [comment]
Hola @anamanzana !

Tienes toda la razón. Me confundí con lo estipulado en el enunciado. Después de realizar una acción, se debería conducir al ***Menú de Acciones***. Lo importante es que el programa no se cierre al momento de realizar una **acción**.
Muchas gracias por la acotación! 😄 
Saludos!
