### ISSUE TITLE
Modularizacion de main

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus#503]
Tengo una duda con las 400 lineas de codigo maximo. No es esto muy poco, digamos que la logica del juego esta en mi backend donde manejo muchos self. por lo que son atributos que estan dentro de la clase y cuando realizo cualquier funcion necesito varias lineas para completar la funcion. Y con toda la logica que ya llevo, probablemente termine en mas de 400 lineas. Lo que dice el descuento es que SI SE  PUEDE modularizar deberiamos hacerlo sino hay un descuento, pero probablemente cualquier cosa se puede, sin embargo dado el tiempo no creo que pueda hacerlo y encuentro logico que toda la logica del juego se encuentre en un mismo lugar.

**Comment by jeschuwirth** [comment]
Hola,

por lo general casi siempre es posible resumir más el código. Pero recuerda que el readme tiene mucho peso a la hora de corregir, si tienes una buena explicación para el largo de tu código y el ayudante está de acuerdo entonces se puede evitar el descuento.

Ten en cuenta que si el ayudante encuentra un método que puede ser una función sin problema, entonces puede que tengas el descuento de todos modos.

Si tu archivo backend pasa las 500 líneas es probable que tengas el descuento de todos modos.

Te recomiendo resumir lo más posible y evitar pasarte de las 400, si no puedes, entonces explica en el readme de manera extensa que no pudiste resumir mejor el código.

Suerte !
