### ISSUE TITLE
Duda con buenas prácticas de excepciones.

### ISSUE THREAD

**Issue by gustavo-toro** [IIC2233/syllabus#504]
Hola, quería preguntar si es mala práctica algo como:
```python
try:
    ...
except Error as err:
    pass
```
¿Es mala práctica utilizar pass y no hacer nada más al capturar las excepciones? Muchas Gracias.

**Comment by aljara97** [comment]
Hola, el uso de excepciones se explica en mayor detalle en la issue #340 
Suerte con tu tarea 🌽👨🏻‍💻

**Comment by entamburini** [comment]
Complementando un poco lo que dijo @aljara97, el sólo poner `pass` si es señal de una mala práctica:

- Por un lado, si tu código falla y no hace nada (porque tiene un `pass`) eso quiere decir que la parte del `try` no era realmente necesaria de ejecutar. 
- En caso contrario, podrías decir "pero si más adelante en el código lo verifico". Ese caso no tiene sentido porque justamente para eso es que se tiene el `except`, para hacer algo al respecto.

Espero que te quede un poco más claro! :D

**Comment by gustavo-toro** [comment]
Gracias
