### ISSUE TITLE
Duda actualización de vida y datos por ronda

### ISSUE THREAD

**Issue by franc1899** [IIC2233/syllabus#504]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, tengo unas dudas con los datos al momento de comenzar una nueva ronda. ¿La vida del jugador vuelve a 100% al comienzo de una nueva ronda o se mantiene la vida de la ronda anterior? ¿Los contadores de items buenos y malos son por ronda, o sea vuelven a 0 cada vez que inicia una ronda nueva? Lo mismo para el puntaje.

Saludos!

**Comment by valerianazal** [comment]
Hola @franc1899 ! La vida del jugador se mantiene al final de la ronda, es decir, si el personaje termina con 50% de vida, comenzará con dicho porcentaje en la ronda siguiente. La forma de recuperar vida sería con el _cheatcode_ correspondiente o atrapando el objeto _aumento de vida_ en el juego. Respecto a los contadores de items, estos vuelven a 0 al finalizar el nivel y la cuenta comienza nuevamente al comenzar la ronda siguiente. Por último, el puntaje se calcula por cada nivel, sin embargo, se debe sumar aquel al **puntaje acumulado**, el que es una suma de todos los puntajes obtenidos en los niveles jugados mientras se juega la misma partida. Al iniciar una **nueva partida** el **puntaje acumulado** vuelve a 0. 
Espero haber resuelto tus dudas! Quedo atenta a cualquier comentario 😄

**Comment by mjsifri** [comment]
Hola! No me quedó claro lo de los puntajes, para cada ronda, en la ventana de juego el puntaje debe ser cero? pero al volver a la ventana de preparación se muestra el acumulado (que sería la suma de los puntajes de cada ronda), que es el mismo que se guarda en el ranking al terminar el juego?
saludos

**Comment by mmunoz12** [comment]
Hola @mjsifri! Aproveché de contestar esta duda junto con otra relacionada que hiciste en la issue #535 para que las veas. Saludos!
