### ISSUE TITLE
Registro de parámetros

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2233/Syllabus#504]
En la tarea se dice que no puede haber ningún valor numérico en el código, ¿esto es en absolutamente todos los casos? Por ejemplo, en el caso de las náuseas y vómitos, tendríamos que definir parámetros distintos para:
náusea inicial
náusea máxima
náusea mínima para que exista la posibilidad de vomitar
probabilidad de vomitar superando la náusea mínima
náusea post_vómito
aumento de náuseas para niños por atracción
aumento de náuseas para adultos por atracción
aumento de náuseas post_restaurantes

Si este es el caso, ¿podemos usar números en casos puntuales, como la generación de probabilidades dentro del mismo código? Como si utilizara alguna distribución para verificar si alguien vomita o no, algo del estilo:

`if uniform(0,1) < prob_vomitar:
    persona.vomita()`

**Comment by leolivares** [comment]
Hola!
@jpmoraga1 La idea es que definan sólo las variables que se mantendrán constantes durante toda la simulación. No hay problema con que utilicen números al generar probabilidades, debido a que estos irán cambiando a medida que progrese.

@akrebs2 No debe ser redefinido en parametros.py. Si el enunciado no dice que cambian entonces quedará fijo.

**Comment by sicorrecto** [comment]
No me quedo claro que debe ir en parameters.py... el enunciado dice que el código no debe tener ningún valor numérico, es así o no? 
Por ejemplo nos dicen que la estatura de un adulto distribuye normal(170, 8).... entonces en mi código debería poner algo así como normalvariate(promedio_adulto, sigma_adulto) o bien, puedo poner  normalvariate(170, 8)?
