### ISSUE TITLE
Duda pizza favorita del cliente

### ISSUE THREAD

**Issue by Mgseverin** [IIC2233/Syllabus#504]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo una duda con respecto a lo que se refieren con "En caso de que no haya una pizza favorita, se retorna un iterable vacío". En este sentido, no se permite el empate? O que no haya pizza favorita se refiere a que ese cliente no hizo pedidos? Es un poco confuso, ya que en el enunciado se pide un Iterable con tuplas, lo que da a entender que si se permite el empate, pero la definición de la función en el archivo dice que debe retornar una tupla, no un iterable. Por lo tanto, a qué se refiere exactamente con que no haya una pizza favorita? Es porque el cliente id_cliente no hizo pedidos y, por lo tanto, no hay pizza favorita, o se refiere a que existe un empate y, en consecuencia, no hay una pizza favorita única? Espero que se entienda mi duda.

**Comment by FradexMF** [comment]
Hola!

Se refiere a cuando el cliente no haya hecho ningún pedido y por ende no hay pizza favorita.

En caso de empate se sigue tal y como dice el enunciado retornando todas las tuplas que cumplan el empate dentro de un iterable.
