### ISSUE TITLE
Módulos de inicio

### ISSUE THREAD

**Issue by ByronHidalgo1** [IIC2233/syllabus#504]
Hola!
Es necesario tener como inicio los módulos clientes y servidor? Puedo iniciar un frontend, que luego inicie el cliente y se conecte al servidor? En este caso para revisar la prueba tendrían que abrir un servidor y un frontend para el cliente y no este último de forma directa. Es posible?

**Comment by KnowYourselves** [comment]
Hola @ByronHidalgo1!

El único requerimiento tanto para el cliente como para el servidor es que ambos se ejecuten con un `main.py` y nada más. Es decir, tu programa debe funcionar ejecutando el main del servidor y luego el main del cliente. 

Espero haberte ayudado!
