### ISSUE TITLE
Días de susto consideran sábado y domingo?

### ISSUE THREAD

**Issue by valeria-adasme** [IIC2233/Syllabus#504]
Hola, quería saber si un vendedor por ejemplo tuviera 4 días de susto y lo asustaron un viernes, tendría que contar los días del fin de semana? o los ignoro y en este mundo sólo hay días de lunes a viernes?

Gracias :)

**Comment by iqacevedo** [comment]
Hola,

Como no está explícito en el enunciado, puedes hacerlo de la manera que te parezca mejor. No olvides mencionar en tu README cuál fue tu decisión.

Lo que si es bueno mencionar, es que en este mundo si hay fin de semana aunque no ocurran eventos en ellos, estos cuentan para eventos como recibir la mesada (en que se esperan 30 días).

Saludos !
