### ISSUE TITLE
Manejo de archivos .csv

### ISSUE THREAD

**Issue by vblopez** [IIC2233/syllabus#504]
Cuando en la pauta se menciona "**Trabaja correctamente con todos los archivos CSV entregados."** , 
que sería un buen trabajo o un mal trabajo? 

Lo correcto es trabajar con el archivo en todo momento y no cargarlo, es decir consultarlo al verificar nombres de usuario unicos y cada vez que se me pida info de algo? O puedo cargar el archivo, almacenar la info y trabajar con esa info temporalmente almacenada?

**Comment by matiasmasjuan** [comment]
Hola @vblopez !

Un **buen trabajo y manejo con los archivos CSV entregados** tiene relación con la capacidad de tu código de poder **actualizar**, **leer** y **escribir** sobre estos archivos **constantemente** sin **errores**. Uno de estos conceptos es el correcto uso de la **codificación** al momento de **escribir** en los **archivos**. Por ejemplo, si tienes que escribir la letra *ñ*, o letras con tíldes, y sabes que este caracter no se guarda correctamente en el archivo **csv**, entonces debes cambiar el ***encoding*** al momento de escribir el archivo (por lo mismo recomendamos el **UTF-8** y leer y escribir los archivos bajo la misma **codificación**). Otro de los factores que pedimos es que sean capaces de **actualizar constantemente los archivos**. Vale decir, si un **Magizoólogo** compra un **alimento**, la idea es que **inmediatamente** se actualice al momento de **efectuar** la acción.

Con respecto a tu pregunta, puedes **abir** y **cargar** los archivos cuando desees y cada vez que necesites de su información. Por lo tanto, la forma en que los trabajes, ya sea cargar desde un principio y almacenar los datos, o abrirlos constantemente queda a tu criterio y comodidad. Sin embargo, debes **considerar** las **indicaciones** señaladas **previamente**. Es decir, **sin errores** en la **lectura** o **escritura**, y que se deben **actualizar** **constantemente** los archivos ante cualquier **cambio**.

Espero haber respondido a tu pregunta, y mucho éxito con tu tarea 😄
