### ISSUE TITLE
Cálculo de mesada

### ISSUE THREAD

**Issue by valeria-adasme** [IIC2233/Syllabus#505]
En el Enunciado se entrega la fórmula:

mesada = base mesada ∗ (1 + random()random()) ∗ 20

pero no estoy segura entre qué parámetros son estos random :s o si hacen referencia a otra cosa

**Comment by iqacevedo** [comment]
Hola,

Los randoms de ahí hacen referencia a la función `random` del módulo random, que no recibe parámetros y devuelve un número aleatorio entre 0 y 1. Por lo que sería equivalente a tener una distribución uniforme entre 0 y 1.

Saludos !

**Comment by felipecr00** [comment]
en el enunciado dice que es random()^random(), pero creo que eso no se puede hacer?
