### ISSUE TITLE
Entrega de notas

### ISSUE THREAD

**Issue by jnhasard** [IIC2233/Syllabus#505]
Hola, 

Cuando el Malvado Dr. Mavrakis entrega con descuento las notas aparece en el enunciado que para la semana siguiente el descuento no seguirá ahí. ¿Esto significa que hay que publicar todas las notas semana  a semana o simplemente que el cambio no quede guardado para siempre? 

Gracias

**Comment by hanavarrete** [comment]
Que el cambio no quede guardado. Saludos!
