### ISSUE TITLE
No module named 'Logo_rc'

### ISSUE THREAD

**Issue by panchotarud** [IIC2233/syllabus#505]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Hice las ventanas en QtDesigner y agregué las imagenes por ahí. Al intentar importar las ventanas al codigo y correrlas me tira este error: **No module named 'Logo_rc'**, he buscado por todos lados y no se que hacer.

**Comment by MatiasDuhalde** [comment]
Hola @panchotarud !

Si incluíste imágenes directamente en QtDesigner, este debe haberlas empaquetado en un archivo con extensión `qrc`, además de los archivos `ui`. Por lo tanto, se te debe haber creado un archivo llamado `Logo.qrc` en tu directorio. Estos archivos debes compilarlos a archivos `.py`, lo cual se puede hacer usando el comando

```bash
pyrcc5 Logo.qrc -o Logo_rc.py
```
El cual debería dar como output un archivo que python pueda importar.

Si sigues teniendo problemas o no te funciona ejecutar el comando anterior, haz push de tu código a tu repositorio, para poder revisarlo con más detalle! :sparkles:

**Comment by panchotarud** [comment]
cree el archivo pero me sigue apareciendo el mismo error:( jajaj será porque lo esta buscando en una carpeta que no es? El archivo Logo_rc.py está en frontend/assets/sprites, y cree el _rc en la misma locación.

**Comment by MatiasDuhalde** [comment]
Hola @panchotarud !

Si, probablemente el error se debe a lo que mencionas. Para que al hacer el `import` se detecte el archivo `Logo_rc.py`, generalmente debe estar en el mismo directorio que los archivos `.py` de las ventanas, por lo que debes mover el archivo `Logo_rc.py` para que esté en el directorio correcto!

Intenta cambiar la ubicación del archivo y probar si funciona! Si no se soluciona con eso, puedes hacer push a tu repositorio para que podamos revisar tu estructura de archivos e intentar darte una solución más precisa! :cowboy_hat_face:

**Comment by panchotarud** [comment]
Me sigue saliendo lo mismo jajaja Acabo de hacer el push para que puedan ayudarme:)

**Comment by MatiasDuhalde** [comment]
Hola de nuevo @panchotarud !

Primero un poco de contexto, Python es un poco "mañoso" cuando se trata de importar cosas que no están en el root del proyecto, debes ocupar la notación del punto para importar a cualquier módulo en un subdirectorio, por ejemplo, tal como lo hiciste en tu main, en la línea `from frontend.ventana_inicio import VentanaInicio`. Los imports se vuelven un poco menos intuitivos cuando intentas importar otra cosa desde un submódulo hacia arriba, porque, por ejemplo, si importas a `ventana_inicial` desde `main`, y luego intentas importar otro archivo desde `ventana_inicial`, va a intentar sacar los imports tomando como base el path de `main`. Es por esto que en ciertos casos se prefiere optar por cambiar el diseño del programa, como se explica en la issue #478 .

Ya con este contexto, tienes dos opciones/soluciones (~~please lee ambas pero intenta usar la segunda~~ :):
- La opción "simple" (y fea), sería colocar el archivo `Logo_rc.py` en la base del repositorio (al mismo nivel de `main.py`), así, cuando al llamar `uic.loadUiType`, se pueda encontrar el archivo correctamente. Notar que `loadUiType`, por defecto, usa la regla explicada anteriormente de tomar los imports desde el main, por lo que a priori asume que los archivos `_rc.py` estarán ahí.
- La otra opción que es más bonita, pero que requiere un poco de investigación (~~don't worry, ya la hice~~), es configurar el método `uic.loadUiType` para que haga los imports de los archivos de recursos, es decir, los que terminan `_rc.py` (aunque esto igual se puede configurar con un argumento), desde un path distinto al base. Para hacer esto, debes agregar los argumentos `from_imports`, que permite imports relativos, y `import_from`, que indica el path de estos imports, a la llamada de la función. De esta manera, te quedaría la línea así:

```python
window_name_main, base_class_main = uic.loadUiType(p.VENTANA_INICIO, from_imports=True, import_from='frontend')
```

Básicamente esta línea, además de lo base, permite que `loadUiType` use imports relativos, y además, use el path `frontend` para buscar los archivos `_rc.py` (asumiendo que tu archivo `Logo_rc.py` se encuentra en ese directorio).

Si quieres saber de que otra manera puedes configurar a `uic.loadUiType`, esta es la documentación:
https://doc.bccnsoft.com/docs/PyQt5/designer.html

Cuéntanos si lo anterior te funciona, y si no, coméntanos cualquier problema que siga presente! :sparkles:

**Comment by panchotarud** [comment]
Funcionó perfecto! Muchas graciaas!!

**Comment by ConstanzaBaeza** [comment]
Hola.  Me sucede lo mismo al intentar usar el archivo de Designer en mi código de Python. Leí varias issues y aun no se como resolverlo aun. 
El terminal me arroja lo siguiente:

FileNotFoundError: [Errno 2] No such file or directory: 'ventana_de_inicio.ui'

Mi archivo de Designer se llama ventana_de_inicio.ui y se encuentra en la misma carpeta de donde esta el archivo de Python.

**Comment by MatiasDuhalde** [comment]
Hola @ConstanzaBaeza !

Cuando llamas al método `loadUiType`, debes pasarle el path del archivo `ui`, pero el path debe ser relativo según el archivo `main.py`.

Por ejemplo, si tienes la siguiente estructura de archivos:
```
T2
│   README.md
│   main.py
│   parametros.py
│
└───frontend
│   │   ventana_de_inicio.py
│   │   ventana_de_inicio.ui
│
└───backend
    │   ...
```
Deberás llamar a `loadUiType` en `ventana_de_inicio.py` con el path: `"frontend/ventana.ui"`.

Revisa si ese era tu error, y si es algo más, vuelve a comentar en esta issue para poder ayudarte!

**Comment by ConstanzaBaeza** [comment]
Ya lo pude solucionar, Muchas gracias!. Había guardado el nombre de la carpeta con un espacio de mas.

**Comment by Piolawa** [comment]
Hola, tengo el mismo error 
ModuleNotFoundError: No module named 'Logo_rc', pero Qt Designer no creaba el Logo.qrc, tuve que hacerlo con https://stackoverflow.com/questions/26508171/creating-a-resource-file-to-use-it-in-qt-designer#:~:text=Click%20the%20Edit%20Resources%20button,qrc)%20and%20click%20Save (la segunda solución que sale ahí)
Y probando las cosas que fueron diciendo en este hilo, cuando llegué a la compilación de los datos, me salía que no existía Logo.qrc :c

**Comment by MatiasDuhalde** [comment]
Hola @Piolawa !

No entiendí 100% el problema, pero si aún no logras crear el archivo Logo.qrc, [aquí](https://stackoverflow.com/questions/28536306/inserting-an-image-in-gui-using-qt-designer) hay una guía muy visual que explica como agregar recursos en Designer (específicamente una imagen, que supongo es tu caso de uso).

Una vez tengas el archivo Logo.qrc, que debería crearse en el directorio que elegiste en la etapa anterior, debes compilarlo a Python con el comando de arriba:

```bash
pyrcc5 Logo.qrc -o Logo_rc.py
```

Ten en cuenta que para correr este comando, tu consola debe estar en el mismo directorio que el archivo `.qrc`, o no lo encontrará.

Con eso debería crearse el archivo `Logo_rc.py`, y si sigues con el problema de `ModuleNotFoundError`, debería funcionarte lo de [esta](https://github.com/IIC2233/syllabus/issues/505#issuecomment-848328659) respuesta anterior.

Ojalá te sirva lo de arriba, pero si sigues con problemas o entendí mal el problema no dudes en preguntar! :sparkles:

**Comment by Piolawa** [comment]
Se me había olvidado colocar la consola en el mismo directorio jeje, gracias! @MatiasDuhalde
