### ISSUE TITLE
Resumen diario

### ISSUE THREAD

**Issue by inarrgd** [IIC2233/syllabus#505]
Hola! entiendo que en la parte de criaturas que se enfermaron, escaparon y hambrientas hay que considerar solo los que cambiaron su estado según corresponda al pasar de día, pero en la parte donde se imprime "criatura perdió salud por enfermedad/hambre", hay que considerar los que perdieron salud  porque cambiaron su estado ese día, o bien, puede haber por ejemplo una criatura enferma de antes, que no fue recuperada y debe imprimirse también dicho texto.
De antemano gracias!

**Comment by aljara97** [comment]
Hola @inarrgd!

Es necesario que informes de cualquier cambio en la salud de la criatura relacionado a pasar el día. Recuerda que estos no solo varían si la criatura enferma o pasa a estar hambrienta el mismo día, por ejemplo, por **cada día que esté hambrienta** pierde 3 puntos de salud y que por cada **día que esté enferma** pierde 7 puntos de salud.

Éxito y espero haber aclarado tu duda 🧙
