### ISSUE TITLE
Lluvia de hamburguesas (y Carabineros)

### ISSUE THREAD

**Issue by valeria-adasme** [IIC2233/Syllabus#506]
El día donde hay lluvia de hamburguesas ¿Los puestos pueden recibir la llegada de carabineros para su inspección? ¿O se asume que se retiran?

**Comment by cilopez** [comment]
Si hipotéticamente ocurren los dos eventos, asúmelo como quieras ya que es un caso bastante poco probable, menciónalo en tu _readme_

**Comment by Bneya** [comment]
Cuando el enunciado dice

>La probabilidad de que en un día haya una lluvia de hamburguesas distribuye exponencial de parámetro **lambda_t = ( 1 / ( 21 - n ) )** donde n son los días transcurridos desde la última temperatura extrema

No entiendo realmente qué cosa me entrega el **expovariate (lambda_t ) **,  ¿me entrega el prox día cuando ocurre, la prob de que ocurra ese día o qué cosa?

Probé qué me entregaría si hago 

`
for dia in range(10):
    print(expovariate(1 / (21 - dia)))
`

y me arrojó

>60.15367610904753
>154.67806133337743
>48.33784865377854
>4.719547164845789
>9.363881201441766
>6.398174584381277
>3.1208447620933324
>10.28344064276311
>13.548854442496959
>8.169495392392859

¿Que signifcan estos números?

**Comment by cilopez** [comment]
Si esto es en el primer día de simulación , significa que en tu cola de eventos, el día 60 habría una lluvia de hamburguesas.

**Comment by Bneya** [comment]
¿Entonces si ocurre una lluvia de hamburguesas cuando la última vez que hubo una temperatura extrema fue hace 3 días, la próxima lluvia de hamburguesas será el día entregado por expovariate ( 1 / (21 - 3 ) ) ?

**Comment by cilopez** [comment]
será el día entregado **más** expovariate ( 1 / (21 - 3 ) )

**Comment by ptflores1** [comment]
@cilopez En teoria uno no podría determinar cuando sera la próxima lluvia el mismo dia que ocurre una no? porque si hay un dia con temperaturas extremas antes del dia calculado para la lluvia este dia de lluvia debería cambiar, es así o me equivoco?

**Comment by MrEarle** [comment]
Asumimos que, una vez que se determina el proximo dia con lluvia de hamburguesas, este no puede cambiar? Porque si hay una temperatura extrema entremedio, la probabilidad cambiaria...
Ej:
Dia 1:
Temperatura extrema
Se determina que el dia 10 va a haber lluvia de hamburguesa
Dia 2: nada
Dia3: nada
.
.
.
Dia 8:
Temperatura extrema
Se vuelve a calcular el dia en que hay lluvia de hamburguesa?

Ademas, el Enunciado dice
> La probabilidad de que en un dia haya una lluvia de hamburguesas distribuye exponencial de parámetro (lambda)t

Habla de la distribucion de la probabilidad de que haya lluvia en un dia, no de los dias entre lluvias de hamburguesas. En ese caso la distribucion exponencial no entrega una probabilidad (número entre 0 y 1).

**Comment by cilopez** [comment]
@MrEarle  @ptflores1  Hay dos formas de hacerlo: 1 es considerar únicamente el cálculo inicial, 2 para los exquisitos en probabilidades: Calcular una exponencial trasladada  según los días que han pasado hasta la lluvia, se entiende?

**Comment by ptflores1** [comment]
@cilopez Creo entender, entonces al partir la simulacion hacemos `expovariate(1/(21 - 0))` luego si no ocurren temperaturas extremas entremedio cuando ocurre esta lluvia volvemos a calcular de la misma manera. Si ocurriese alguna temperatura extrema entremedio volvemos a calcular la proxima lluvia el mismo dia de la temperatura extrema con `n = 0` ya que acaba de haber una temperatura extrema. Ahora supongamos que estamos en el dia 30 y que en este dia hubo una lluvia, ademas la ultima temperatura extrema fue el dia 15 ( asi que al calcular la lluvia en el dia 15 nos deberia haber dado 15 => `tiempo_actual + 15 = 30`), como acaba de haber una lluvia calculamos el nuevo tiempo con `n = tiempo_actual - ultima lluvia` => `n = 30 - 15` entonces hariamos `expovariate(1/(21 - 15)`??, espero se entienda ! Gracias

**Comment by ptflores1** [comment]
@cilopez Necesito la respuesta de esto porfavor ! :cold_sweat:

**Comment by cilopez** [comment]
Si ,al parecer está bien como lo entiendes!

**Comment by ptflores1** [comment]
@cilopez Gracias por ambas respuestas!
