### ISSUE TITLE
citar link en el archivo

### ISSUE THREAD

**Issue by pdmino** [IIC2233/syllabus#506]
Hola, queria hacer una referencia a un link de internet dentro de mis archivos, pero el link supera los 100 caracteres, se considera mala practica si lo pongo todo junto o debo colocar el link entre dos lineas distintas para evitar superar los caracteres?

**Comment by aljara97** [comment]
Hola, los comentarios no deben superar los 100 caracteres, sin embargo no es necesario que coloques el link directamente en el código, también existe la posibilidad de que en el readme hagas una cita e indiques con claridad las líneas y archivo en el que utilizas código externo. En caso de que consideres necesario incluir el link en el archivo puedes usar un acortador de link como tinyurl. 

Suerte con tu tarea :seedling:
