### ISSUE TITLE
Instanciar Deportistas

### ISSUE THREAD

**Issue by isidorabecker** [IIC2233/syllabus#506]
Holaa, tengo que instanciar a los deportistas, osea tengo que crear a todos los deportistas que me entregue deportistas.csv como objetos ???

**Comment by amparostevens** [comment]
Hola @isidorabecker !

Perdón por la demora. Puedes hacerlo como estimes conveniente. Es decir, instanciar sólo los que sabes que vas a ocupar o todos los deportistas que aparecen en el archivo. Personalmente considero que es más sencillo instanciarlos todos de inmediato, pero queda a tu criterio.

Mucho éxito! ✨
