### ISSUE TITLE
Comunicación Cliente - Frontend

### ISSUE THREAD

**Issue by emena97** [IIC2233/syllabus#506]
Es valido instanciar una ventana(frontend) dentro de la clase cliente para luego acceder a ella? 
o es obligatorio hacerlo a través de señales?

**Comment by KnowYourselves** [comment]
Hola @emena97!

Es válido instanciar el _frontend_ en el cliente, siempre y cuando el cliente no esté también instanciado en el _frontend_ (es decir, modelación circular). Lo que no es válido, es que la comunicación entre estos no haga uso de señales. 

Espero haberte ayudado!

**Comment by emena97** [comment]
con instanciar te refieres a crear una instancia cliente en el frontend o no?
Porque lo que hago yo es instanciar el frontend en el cliente, pero otorgandole como atributo el mismo cliente, que despues ocupo para poder conectar mis señales del frontend a funciones del cliente.
Eso se puede?

**Comment by naquiroz** [comment]
Hola @emena97!
Cualquier combinación de pasar la instancia o instanciar dentro de, tanto el cliente en el frontend y frontend en el cliente, es modelación/implementación circular. Cuando situaciones como estás ocurren, vale la pena cuestionarse si es necesario que ambos tengan la instancia del otro.

Saludos? :wave:

**Comment by cjones27** [comment]
Hola!
Con respecto a lo anterior no entiendo cómo se modela de forma correcta (sin modelación circular) puesto que necesito mandar el input del usuario desde el frontend al backend con señales, pero desde el backend tengo que mandar los cambios que me lleguen del servidor también con señales hasta el frontend. 

Gracias 😄

**Comment by naquiroz** [comment]
@cjones27 puedes pasarle señal al instanciar una dentro de ella otra, y hacer el connect en el init. 😊
