### ISSUE TITLE
Gráficos

### ISSUE THREAD

**Issue by nivek0o0** [IIC2233/Syllabus#506]
Hola, 
¿las notas promedio deben ser las publicadas acumuladas desde el inicio de la simulación hasta dicha semana, o solo las publicadas dentro de esa misma semana?
Pregunto porque de ninguna de las 2 formas me queda algo similar al gráfico ejemplo del enunciado.
![graficos](https://cloud.githubusercontent.com/assets/20782451/26257831/1a612e6e-3c90-11e7-820e-f330eb82b752.png)
Este es mi gráfico donde una nota 0 representa que no hubo publicación de esa evaluación en la semana.  De este modo la curva de tareas tendrá altos y bajos cada 2 semanas aproximadamente.

Se me ocurre que el gráfico lo hicieron actualizando una variable a medida que avanzan las semanas, solo si hay publicación. De ese modo la curva se mantiene "constante" al pasar una semana sin publicación.

¿Cual es la forma de proceder?

Gracias!

**Comment by FernandoPieressa** [comment]
Hola!

La idea del gráfico es que sea acumulada de todas las notas que fueron publicadas hasta esa semana!

El gráfico del enunciado fue sacado aleatoriamente y no necesariamente representa uno con datos correctos de la simulación, era solo para que vieran la forma del gráfico de lineas y mostrar los 3 promedios en el mismo, asique no te preocupes si es muy diferente!

Saludos!

**Comment by asdegoyeneche** [comment]
Hola! 
Me entró la duda, para confirmar: 
Sería 1 solo gráfico por simulación si? Y por ejemplo, a la semana 5, en la curva de actividades: se muestra el promedio de los promedios por actividad obtenido por los alumnos que dieron la actividad (quienes estaban en el ramo en el momento).
Ejemplo: Promedio Ac1 = 5.0, Ac2 = 5.5, Ac3 = 4.5, Ac4 = 5.0, Ac5 = 6.0. En el gráfico se tendría para la primera semana de publicación de actividad un 5.0, luego para la segunda semana de publicación de actividad un 5.25, luego 5.0, luego 5.0 y finalmente a la 5ta semana de publicación de nota 5.2
A esto habría que incluir si se actualizó alguna nota (+0.5 dado el Dr. Mavrakis) entre semanas. 
Estoy en lo correcto?
Muchas gracias!
