### ISSUE TITLE
¿Cómo verificar intersecciones en PyQt5?

### ISSUE THREAD

**Issue by igbasly** [IIC2233/syllabus#506]
Hola a todes :sparkles:!!

Tal vez se están preguntando cómo se pueden verificar intersecciones entre elementos con PyQt5 para su Tarea 2. Si nos enfocamos un poco más específicamente en imágenes que están contenidas en `QLabels` podemos utilizar algunos métodos que aplican a cualquier tipo de `QWidget`. Además, recuerden que pueden revisar la documentación de [Qt5](https://doc.qt.io/qt-5/qtmodules.html) (que es en lo que se basa PyQt5) para encontrar más información sobre clases y métodos específicos.

Por temas pedagógicos nos guiaremos con el ejemplo de dos objetos de `QLabel` llamados `obj1` y `obj2`, los cuales tienen dimensiones  de `75px X 75px`.

> **Importante :eyes:**
>
> Las alternativas aquí mostradas, son solo ejemplo y no son las únicas formas de verificar intersecciones o colisiones entre dos objetos de `QWidget`. Siempre pueden buscar sus propias alternativas e ir probando según sus necesidades :wink:.
>
> Además, aquí no se indicó exactamente cómo evaluar una **colisión**, ya que se entiende por colisión cuando dos objetos se intersectan en alguno de sus bordes. Evaluar colisiones dependerá de en qué momento ustedes verifiquen las intersecciones y qué tanto están moviendo los objetos, ya que muchas veces no se cumple una colisión exacta.

## Utilizando [`QRect`](https://doc.qt.io/qt-5/qrect.html)

Una forma sencilla de evaluar intersecciones es utilizando una clase de `QtCore` llamada [`QRect`](https://doc.qt.io/qt-5/qrect.html).  Estos objetos poseen un método para evaluar si una instancia se está intersectando con otro objeto de la misma clase, el método `.intersects`, el cual recibe un objeto de `QRect` y retorna un `bool` indicando si se están intersectando los objetos.

Podemos crear un objeto de `QRect` de la siguiente forma `QRect(pos_x, pos_y, ancho, alto)`. Pero nos aprovecharemos de que los `QWidget` tienen un método `.geometry` que retorna un objeto de `QRect` con las dimensiones y posiciones del widget en cuestión. 

Ahora, con nuestro ejemplo, si quisiéramos evaluar si estos objetos se están intersectando, podemos hacer lo siguiente:

```python
rect_obj1 = obj1.geometry()  # Pedimos el QRect del obj1
rect_obj2 = obj2.geometry()  # Pedimos el QRect del obj2

intersectan = rect_obj1.intersects(rect_obj2)  # Retorna True si se intersectan
```

## Utilizando la posición

Otra forma completamente equivalente a la anterior, es utilizando las posiciones de los vértices del objeto. Ya que los `QWidget` son rectángulos, podemos calcular sus vértices y evaluar si es que están intersectando a otro objeto.

Recordamos que podemos obtener la posición del vértice principal (superior izquierdo) del `QWidget` con los métodos `.x()` y `.y()`. Como dijimos al comienzo, nuestros objetos poseen `75px` de ancho y `75px` de largo, por lo tanto, podemos calcular los vértices del `obj1` de la siguiente forma:

```python
pos_x = obj1.x()  # Obtenemos la posición x
pos_y = obj1.y()  # Obtenemos la posición y

vertice_1 = (pos_x, pos_y)
vertice_2 = (pos_x, pos_y + 75)
vertice_3 = (pos_x + 75, pos_y + 75)
vertice_4 = (pos_x + 75, pos_y)
```

*Los vértices son calculados en sentido horario comenzando por el vértice superior izquierdo*

Ahora, para evaluar si se cumple una intersección, necesitamos la posición `x` e `y` del otro objeto y verificar si **algún vértice** del primer objeto posee sus coordenadas dentro del rango `[x, x + ancho]` **y** `[y, y + alto]` del otro objeto. Siguiendo con el ejemplo de los objetos `obj1` y `obj2`, podemos ver la intersección del vértice Z así:

```python
pos_x_obj2 = obj2.x()  # Obtenemos posición x de obj2
pos_y_obj2 = obj2.y()  # Obtenemos posición y de obj2

# Recordar que obj2 tiene dimensiones 75px X 75px
intersecta_x = pos_x_obj2 <= vertice_Z[0] <= pos_x_obj2 + 75
intersecta_y = pos_y_obj2 <= vertice_Z[1] <= pos_y_obj2 + 75

# Se deben cumplit ambas condiciones para decir que el vértice intersecta
intersecta_vertice = intersecta_x and intersecta_y
```

---
Lo anterior son solo algunas forma de realizar la colisión entre 2 objetos con la librería PyQt5, pero los invitamos a investigar nuevas formas de realizar esta acción :nerd_face:. 

Esperamos que esto sea de ayuda para resolver su Tarea y les deseamos el mayor éxito posible :hearts:.

**Comment by jervaal** [comment]
Hola! tengo una duda con respecto al método de "intersects", ya que, al utilizarlo con 2 QLabels, que se generan aleatoriamente en un lugar del mapa, con dimensiones distintas, siempre me indica que es True, a pesar de que no se intercepten, o sobre solapen. llevo mas de 3 hrs intentado ver el error, pero no lo encuentro u.u

de antemano muchas gracias!

**Comment by lily416** [comment]
Hola @jerval :)
 
Cuando obtienes la geometría del `QLabel`, ¿te fijas en si estas llamando al _label_ correcto? 
Una forma fácil de notar si estamos llamando el _label_ correcto es imprimir lo que nos retorna `geometry()`, así podemos verificar la posición, porte del objeto y con ello comprobar que estamos llamando el objeto correcto:
```python
# Si ejecutamos esto: 
geom = self.mi_label.geometry()
print(geom)
 
# Te debería imprimir algo como esto: 
PyQt5.QtCore.QRect(300, 240, 50, 50)
# donde cada valor es respectivamente: 
#    posición en el eje X (desde la esquina superior izquierda)
#    posición en el eje Y (desde la esquina superior izquierda)
#    ancho del label
#    alto del label
```
 
Espero que esto te ayude a darte cuenta de tu error y comprender porque siempre te da `True` cuando revisas la colisión entre 2 _labels_.

Saludos y éxito en la tarea 👋🎷

**Comment by mariizamb** [comment]
Hola! Ayer estaba intentando usar QRect pero por alguna razón la geometry que me da siempre está en el (0,0) -> (x,y) siendo que el objeto en el archivo ui dice en la parte de geometry claramente otra cosa. ¿Cómo podría ver cual es el error en este caso?

**Comment by igbasly** [comment]
Hola @mariizamb ✌️

Lamentablemente no te puedo dar una solución directa para encontrar el error, porque no la hay. Todo dependerá de cómo lo estás implementando.
Eso si, te puedo aconsejar al igual que con el menaje de arriba, tener cuidad de que objetos estás usando para calcular su geometría. Como mencionamos, todas estas funcionalidades para verificar intersecciones aplican a todos los `QWidget` y por ende, aplican a las ventanas mismas, los botones, los campos de texto, etc.
Como bien dijo la Dani, imprimir es una herramienta útil, intenta imprimir el objeto que estás utilizando, la geometría que obtienes y toda la información que consideres necesarias para ir aportando a tu búsqueda del error.

Espero que esto sea de ayuda, cualquier cosa no dudes en escribirnos 🙌
Mucho éxito con la tarea! 🎉

**Comment by ctoro05** [comment]
Hola!! Intentando identificar la posición de mi objeto que supuestamente es un label, me encuentro con un error que dice 'QPixmap' object has no attribute 'geometry'. Tengo la impresión de que eso pasa porque en algún momento apliqué un `setPixmap` para hacer encajar el objeto en el cuadrado. Como puedo volver a tener la capacidad de saber su ubicación?
