### ISSUE TITLE
Inconsistencia test 2 y 4 consultas anidadas

### ISSUE THREAD

**Issue by juanriveraf** [IIC2233/Syllabus#506]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tenia una observación en los test de consultas_anidadas(). Especificamente en los test 2 y 4 hay que correr la función total_ahorrado_pedidos, pero hay nombres de pizzas dentro de generador_contenido_pedidos que no están dentro de generador_pizza. Por ejemplo, en el test 4 salta error porque generador_contenido_pedido tiene la pizza vegetariana_M, pero esta pizza fue filtrada de generador_pizzas, ya que se filtraron las pizzas que tenían el ingrediente tomate.  Esto no sale que se tiene que tratar en la funcion total ahorrado pedidos (tengo todos los test cases buenos en esa). Entonces, esto es un error del test case de consultas_anidadas(), o hay que agregarlo a total_ahorrado_pedidos? Muchas gracias!

**Comment by JVeloz19** [comment]
Hola buenas !!
No soy ayudante, y no se si lo habrás solucionado ya, pero tal cual como comentas el error es porque se filtraron anteriormente. 
La respuesta a tu pregunta supongo que depende como implementaste consultas anidadas. Pero yo creo que es mucho mas fácil implementar ese caso borde en total_ahorrado, ya que si lo agregas esta función abarcara mas casos y será mas robusta, pero no afectara los que tenias antes, así que seguirás teniendo los test buenos de este, y además te ahorras el problema en consultas anidadas.

**Comment by juanriveraf** [comment]
Hola, sisi yo al final lo corregí desde total ahorrado pero no sabía si estaba bien hacerlo así. Gracias por la ayuda!

**Comment by Vicente1824** [comment]
¡Hola @juanriveraf 🙌! Perdón la demora al responder. Lo que dijo @JVeloz19 es correcto, depende de la implementación de tu código (puedes manejar el caso borde en las consultas, o en la consulta anidada). Esta issue es un duplicado de la issue #490, donde se explica esto.
