### ISSUE TITLE
Error en los Limites de movimiento

### ISSUE THREAD

**Issue by DonJavi-538** [IIC2233/syllabus#507]
Hola! programando los límites en los que se puede mover el personaje me topé con un inconveniente: 
Al setear el límite de pixeles dentro de los cuales podía caminar el personaje en las coordenadas Y descubrí que debía multiplicar todo por 1.5 o sino el limite era muy inferior a lo esperado (el personaje se movía hasta la mitad del mapa aproximadamente)
¿conocen el origen de este problema?

**Comment by Dnpoblete** [comment]
Hola @DonJavi-538 esto podría deberse a que tienes que tener en consideración el tamaño del personaje v/s el tamaño de cada cuadrado del mapa y los espacios que avanza el personaje al caminar. ¿Esto te ocurre solo en el eje y? y ¿Tienes en consideración el tamaño del personaje v/s el tamaño de los cuadrados del mapa?
