### ISSUE TITLE
Stack Layouts

### ISSUE THREAD

**Issue by VichoAburto** [IIC2233/syllabus#507]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Una consulta, en clases vimos los layouts de tipo vertical y horizontal, pero existe algún tipo de layout que sea como para apilar QLabels o QWidgets, y que aparezcan al mismo tiempo? He buscado, pero no he podido encontrar.

Algo como de este estilo, pero que todas las imágenes (QLabels) estén dentro del mismo layout, cosa de que si quiero mover el layout, se mueva todo al mismo tiempo.

<img width="151" alt="Screen Shot 2021-05-25 at 12 52 53" src="https://user-images.githubusercontent.com/69520488/119537554-23c7cb00-bd58-11eb-8d7c-c4be2f797aa9.png">

**Comment by tqmbanados** [comment]
Hola! En [este link](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QStackedLayout.html#qstackedlayout) hay documentación para un objeto llamado ```QStackedLayout```. Ese permite colocar objetos uno encima del otro. Espero que sea lo que estás buscando!

Puedes revisar [aqui](https://doc.qt.io/qtforpython-5/overviews/layout.html#layout-management) para investigar más sobre Layouts. Al final de la página hay una sección para *custom layouts*, yo nunca las he usado, pero quizás también te sirvan para resolver tu problema.
Espero haberte sido de ayuda! Suerte con la tarea!

**Comment by VichoAburto** [comment]
Buenísima! Gracias!

Y sabes si hay alguna forma de utilizarlos en Qt Designer?

**Comment by tqmbanados** [comment]
Hola! Por lo que pude encontrar no hay una forma fácil de hacerlo, habría que crear un plugin para designer. Es posible que exista uno disponible pero no pude encontrar uno 😞. De todas maneras, para la tarea no debería ser necesario, que es lo que buscas lograr? Quizás podemos encontrar otra solución.

**Comment by VichoAburto** [comment]
Pucha, que lata. Gracias igual.

Quería lograr poner qlabels de colores para hacer los fondos uno encima de otro todos dentro de un layout, y después poner como el layout que contiene todos los textos y botones.

**Comment by tqmbanados** [comment]
mmmh creo que sería mejor simplemente crear el fondo manualmente en algún editor de imágenes, y luego usar esa imagen como QPixmap. 

Recuerda también que lo creado en designer es 100% editable, entonces puedes crear tu Ventana hay, incluyendo todo salvo el Stack Layout, y luego configurar el Stack manualmente el python. Quizás no te permita ver como quedará la "ventana final" en designer, pero sí te ayudará con cosas como los estilos de los Labels y conectar señales!

**Comment by VichoAburto** [comment]
Yaa dalee, muchas gracias por tus respuesta.
