### ISSUE TITLE
Entrega de notas

### ISSUE THREAD

**Issue by Nicolasvegam** [IIC2233/Syllabus#507]
En el enunciado dice que cada dos semanas los ayudantes le pasan las notas al coordinador, mi pregunta es, si simulo por ejemplo 12 semanas, solo se logran corregir 5 actividades ( por ejemplo) ¿ Hay que simular el tiempo necesario para entregar todas las notas ?

**Comment by nivek0o0** [comment]
Hay que simular el tiempo necesario para entregar todas las notas, creo yo.

**Comment by jnhasard** [comment]
Yo entiendo que pasan pueden corregir dos actividades en paralelo por lo que solo necesitarían dos semanas tras la final para terminar de corregirlas todas

**Comment by rrhurtado** [comment]
Hola, respecto al tiempo de simulación se espera que se entreguen todas las notas al término de ésta. 
Saludos !
