### ISSUE TITLE
Incremento moral en el entrenamiento de IEEEsparta

### ISSUE THREAD

**Issue by Kevinnevik** [IIC2233/syllabus#507]
Cuando incremento la moral en el entrenamiento de un deportista de IEEEsparta, también se ve afectada por el bonus de entrenamiento de la delegación?

**Comment by mmunozmendez** [comment]
Hola, cuándo dice que se pondera la fórmula de entrenamiento se refiere solo al atributo que se entrena y no a la moral. 
Éxito 🦝

**Comment by tsunayoshi21** [comment]
Por esto mismo, los atributos de los deportistas de IEEEsparta despues de entrenar se volverían floats. Podemos dejarlos como floats? O los truncamos y los volvemos ints?

**Comment by mmunozmendez** [comment]
Se discutió y los tienen que dejar como floats 👏
