### ISSUE TITLE
No puedo avanzar, test 10 ```ganancias_producidas_en_los_pedidos```

### ISSUE THREAD

**Issue by gracie-14** [IIC2233/Syllabus#507]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!

He pasado toda esta semana trabajando en solo esta función y todavía no puedo cargar todos los datos "L" y "XL" en el tiempo máximo, a pesar de que no estoy usando ningún loop de ```for``` ni ```while``` y tampoco estoy usando ```combinations``` o ```product```. Mi código solo contiene generadores. 

La única cosa en que puedo pensar que podría estar tomando tanto tiempo es ```cycle```, porque usé esto para poder recorrer el generador de pizza varias veces. Es que no puedo pensar en otra manera para encontrar los precios de las pizzas de los pedidos, porque los distintos pedidos podrían tener la misma pizza, así que sería necesario encontrarla otra vez, y obviamente tomaría demasiado memoria para guardarlo como una lista o diccionario.

**Comment by kbetelgeuse** [comment]
Hola @gracie-14 !
¿Podrías por favor subir a tu repositorio tu desarrollo de la tarea para poder ayudarte?
Saludos!

**Comment by gracie-14** [comment]
Acabo de actualizar el repositorio! Muchas gracias por la ayuda!!

**Comment by kbetelgeuse** [comment]
Hola, estuve viendo el desarrollo que enviaste. Sí, al parecer es la forma en la que se está utilizando `cycle` lo que está causando que algunos tests (los últimos en particular) tengan un elevado tiempo de ejecución. Es posible utilizar `cycle` en esta consulta. Si quieres usarla te recomiendo cambiar la forma en la que la implementas o utilizas dentro del código.

Sin embargo, en realidad, la sentencia `cycle` no es estrictamente necesaria para completar esta consulta. Se podrían tener varias alternativas:

1) Te recomiendo seguir investigando la librería `itertools` (la misma librería que contiene la función `cycle` que estás utilizando). Como pista, podrías ver la definición de `tee`.
2) No es imposible utilizar las estructuras de datos que se han visto en clases (las que incluyen las que tú mencionas). Se ha recomendado que se utilice programación funcional, pero no es que en todos los casos el programa sea eterno de ejecutarse.

Espero haber resuelto la inquietud que tenías.

**Comment by gracie-14** [comment]
Gracias por la ayuda! Lo intenté con estos consejos y me funcionó!
