### ISSUE TITLE
Mesada alumnos, días del mes

### ISSUE THREAD

**Issue by mesantamaria** [IIC2233/Syllabus#507]
Hola,

> Disponen una cantidad de pesos diarios (no acumulables) para gastar en comida dadas por una
mesada. En otras palabras, disponen de [mesada del mes / 20] pesos diarios no acumulables.

Qué hacemos con los meses que no tienen 20 días hábiles o asumimos que todos los meses son iguales?

**Comment by egromero** [comment]
Hola,

Puedes considerar que todos los meses son iguales, pero de 30 días, ya que no puedes asumir que no existe el fin de semana. O la otra opción como se comentó en una issue es usar `date time` especifica en tu readme lo que usaste.

Saludos

**Comment by mesantamaria** [comment]
Pero puedo considerar por ejemplo que todos los meses parten un día sabado? Porque así siempre serían 30 días y 20 hábiles y el cálculo de la plata diaria sería correcto para todos los meses.

**Comment by fdominguezclaro** [comment]
Hola!
Si, recuerda especificarlo en tu readme. Saludos!!

**Comment by fedetaladriz** [comment]
@fdominguezclaro Hola! puedo tener meses de mas de 20 dias hábiles? Pregunto esto porque estoy ocupando datetime para manejar el tiempo, y este módulo considera los meses de 31 dias. O a caso, hay alguna manera de quitarle en el módulo ese día a los meses que lo tienen? Lo busqué en google y no encontré nada :(
Gracias!

**Comment by fdominguezclaro** [comment]
@fedetaladriz tal como dijo @egromero si puedes usar la librería datetime con sus respectivos meses (30 y 31 días). 
Saludos!!

**Comment by mmsaavedra1** [comment]
@egromero No le veo lo malo a considerar un supuesto de que los meses sean simplemente de 20 días, ya que en ninguna parte del enunciado se menciona que el fin de semana hay acciones. Como es una simulación, el omitir estos días no afecta en nada ya que no hay consecuencias sobre nuestras clases. Y como mencionaron en las últimas issues #524 estos no deberían considerarse, ya que son un "estorbo" en nuestro análisis.

Saludos😊

**Comment by felipecr00** [comment]
pero puede suceder que en los fines de semana tenga una "recarga" de la mesada? de ser asi necesito los fines de semana también.

**Comment by MariaJosefinaAlliende** [comment]
Si ocupo datetime, pueden haber más de 20 días hábiles en un mes, por lo que me surgió la duda:   ¿el cálculo de la mesada se mantiene igual o tengo que cambiar el 20 por la cantidad de día hábiles que tenga el mes?  ¿Lo mismo con el saldo diario de la mesada?  ¿O lo dejo a mi criterio y lo explico en el readme?

**Comment by egromero** [comment]
@MariaJosefinaAlliende la idea de los 20 días era para simplificar la simulación. Hazlo como más se acomode a tu código y especifícalo en el README.

Saludos!
