### ISSUE TITLE
Método lesionarse: cuando ocuparlo

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2233/syllabus#508]
Hola! 
tengo una duda sobre el momento en que se debe ocupar este método lesionarse. Entiendo que un deportista se puede lesionar durante la competencia y perder por ello, entonces el método lesionarse debería ocuparse después de la validación (ya que el principio el deportista no estaba lesionado) y antes de calcular el puntaje? o antes de la validación de cada competencia?

**Comment by furcelay** [comment]
Hola @antoniaalcayaga!
Dado que el deportista solo se lesiona durante el deporte lo correcto sería usar el método después de la validación, es decir, si no está lesionado pasa la validación, participa en la competencia y se puede lesionar durante ella y finalmente se calcula el resultado de la competencia.

Saludos!

**Comment by CrisBerriosL** [comment]
Hola! Si un deportista se lesiona durante la competencia, la pierde automáticamente? O la puede ganar de todas formas?

**Comment by furcelay** [comment]
Hola @CrisBerriosL !
Como se indica en el enunciado, cuando un deportista se lesiona pierde automáticamente la competencia. (Aparece en la definición de lesionarse)
