### ISSUE TITLE
duda PEP8 máximo 100 caracteres

### ISSUE THREAD

**Issue by Christian-Klempau** [IIC2233/syllabus#508]
Hola!
Mi duda es simple, cuando se menciona que la línea no debe exceder los 100 caracteres, esto considera la columna? Por ejemplo, en VsCode puede que la línea termine en la columna 120, pero la línea en sí contiene solo 90 caracteres. En ese caso se descuentan décimas por PEP8? Ya que a simple vista la línea al estar en la columna 120, tendría más de 100 caracteres, aunque no sea el caso.
Gracias!

**Comment by aljara97** [comment]
Hola, el límite de 100 caracteres por línea sí considera los espacios utilizados para las identaciones. Por tanto, ninguna línea de tu código puede sobrepasar la columna 100. Te sugiero revisar la guía de estilo que usamos en el curso, para que obtengas más detalles y puedas configurar tu editor de texto para respetar este límite.

Saludos 🧙

**Comment by Christian-Klempau** [comment]
Perfecto, gracias!
