### ISSUE TITLE
No me funciona Faker

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#508]
Hola! Estaba intentando entender cómo usar la librería _faker_ y probé esto:
```
from faker import Faker


fake = Faker()
print(fake.name())
```
Lamentablemente, me arroja el siguiente error:
```
ModuleNotFoundError: No module named 'text_unidecode'
```
El error se genera en una línea que dice:
```
from text_unidecode import unidecode
```
¿Qué puedo hacer al respecto? 😢

**Comment by fringlesinthestreet** [comment]
Hola @llloyola 

Prueba instalando el módulo `text_unidecode` a través de `pip`.

Intenta con la sentencia (al menos para MacOs es así):

`pip3 install text_unidecode` 

Avisa cómo te va!

**Comment by llloyola** [comment]
No me funcionó 😭 
Una vez que uso ```pip3 install text_unicode```, el código debería funcionar donde quiera? Me explico... Hará que funcione si estoy usando Sublime?

**Comment by llloyola** [comment]
Nevermind, logré hacerlo funcionar 😄
