### ISSUE TITLE
Duda enunciado en función cliente_indeciso 

### ISSUE THREAD

**Issue by JosefaATP** [IIC2233/Syllabus#508]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Cómo están?

En la función cliente_indeciso dice: Debe elegir las pizzas una a una según el orden de generador_pizzas. si no se llegó a cantidad_pizzas y se llegó al final del generador, **debe continuar desde el principio del mismo.**  Con esto a que se refiere? que habría que volver a recorrerlo? De ser así lo tendria que "llamar" denuevo porque se acaban los generadores, entonces no me queda claro.
Y lo otro dice: Retorna un iterable con cantidad_pizzas instancias de Pizza que no tengan ingrediente_no_deseado.
Se debe incluir las instancias repetidas y **en caso de que no hayan pizzas con tal ingrediente**, retorna un
iterable vacío. Se refiere a que no hayan pizzas que no tengan el ingrediente vdd? porque el cliente quiere pizzas sin el ingrediente que no le gusta, vdd?

Gracias!

**Comment by kbetelgeuse** [comment]
Hola @JosefaATP. Bien, ¿y tú?

1) Exactamente, tal como dices si es que se recorre un generador más de una vez ya no se podrá volver a acceder a los elementos que contenía originalmente ya que este se "agota". Entonces, habría que encontrar una manera de que esto se pueda lograr, o en otras palabras, una manera de que puedas continuar desde el principio de algún generador.

2) Así es, se quiso decir **en caso de que no haya pizzas que no contengan tal ingrediente**, ya que, como bien tú dices, el cliente quiere pizzas sin el ingrediente que no le gusta.

**Comment by JosefaATP** [comment]
Que bueno, bien tmb 😁

Perfecto! 
Gracias!!
