### ISSUE TITLE
Eliminar carpeta de mi repositorio 

### ISSUE THREAD

**Issue by Dafnemami** [IIC2233/syllabus#508]
Uso "git rm nombrearchivo.extension" para eliminar archivos, pero no funciona para carpetas, al reemplazar  nombrearchivo.extension por "mapas/" .

Itenté con git branch, pero tampoco

Alguna idea??

**Comment by jmwielandt** [comment]
Hola!

Te recomiendo mirar las issues #19 y #43 , ya que `git rm ...` elimina cosas también de tu computador.

La flag para que funcione con directorios es `git rm carpeta -r`. El `-r` indica que debe hacerlo "recursivamente" por un árbol de directorios, o sea "borra esto y todo lo que contenga".

Saludos!

PD: recuerda que aunque no subas los archivos, si no los colocas en tu gitignore hay un descuento asociado.
