### ISSUE TITLE
Múltiples sockets en el servidor

### ISSUE THREAD

**Issue by kylevon** [IIC2233/syllabus#508]
¿Se puede crear multiples sockets en el servidor?, es decir por ejemplo, un socket para el chat y otro socket para el juego. Esto se observa en algunos casos en juegos donde sigue funcionando pese a que el chat se desconecte. Lo pregunto porque en el enunciado dice: 
> Nótese que dice el servidor (en singular), pues debe existir exactamente uno (ni más ni menos).

Y no estoy seguro de qué significa solo tener **un** servidor.

**Comment by iqacevedo** [comment]
Hola! 

Puedes hacerlo siempre y cuando asegures que: no se tenga que iniciar otro programa aparte del servidor y del cliente; cada vez que se abra una sala, se abra el chat de esa sala, si abro otra sala debería ser el chat de esa otra sala (respetar que el chat es de la sala). Sin embargo, no te recomiendo crear múltiples socket en el servidor, ya que es una complejidad que no estamos pidiendo. Solo deberías preocuparte de que se puedan conectar n clientes con el servidor.

Con tener solo un servidor nos referimos a que sea uno el programa que se ejecute. Que sea uno el servidor que maneje las conexiones de los clientes, que maneje los mensajes que recibe de los clientes y también los que le envía. 

Espero que se entienda. 
Quedo atento y ¡mucho éxito en la tarea!
