### ISSUE TITLE
Problema importando módulos

### ISSUE THREAD

**Issue by VicenteAlvarado** [IIC2233/syllabus#508]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, estoy con problemas para importar el módulo parametros.py a las subcarpetas en donde trabajo con el backend y el frontend ya que me aparece el error: "ModuleNotFoundError: No module named 'parametros'" 
El modulo parametros lo tengo en la carpeta principal "T2" en donde tengo igualmente el main.py pero no entiendo por qué no lo puedo importar a mis subcarpetas :(

**Comment by JadrinaDA** [comment]
Hola! Recuerda que al importar un módulo debes usar el path relativo a donde estas corriendo el archivo. Si estas dentro de las subcarpetas entonces puedes usar ".." para subir un nivel a la carpeta T2. Avísame si eso te funciona. 
Saludos.

**Comment by VicenteAlvarado** [comment]
No se si lo estaré haciendo bien, pero lo importo haciendo "from .. import parametros" y me arroja el error "ImportError: attempted relative import with no known parent package"

**Comment by luzmagurzua** [comment]
me pasa lo mismo :(

**Comment by JadrinaDA** [comment]
Hola! En este caso no le estas dando al programa el módulo de donde debe sacar los parametros. Te recomiendo usar 
"from ..parametros import PARAMETRO" ahí debería funcionar porque el programa va a subir un nivel a la carpeta T2 y buscar el módulo _parametros_. Les dejo una excelente [issue](https://github.com/IIC2233/syllabus-2020-1/issues/737) pasada sobre el tema por si quieren entender un poco más de como funciona.

**Comment by FVivess** [comment]
Hola he leído todas las issues del tema pero aún no logro que me funcione con este método. Mis carpetas son las siguientes:
```
T2/
├── codigo
│   ├── auxiliar
│   │   └── parametros.py
│   └── frontend
│   │   └── ventana_de_juego.py
│   └── backend
│       └── ventana_de_juego_backend.py
│
└── main.py
```
Intento hacer `from ..auxiliar import parametros as p` desde ventana_de_juego.py, pero me dice "ImportError: attempted relative import with no known parent package"

**Comment by JadrinaDA** [comment]
Hola FVivess! En ese caso la línea de código está correcta, pero esta solo funcionará cuando corras tu programa desde main.py ya que cuando corres ventana_de_juego.py python no reconoce nada de lo que está fuera de tu ventana. En la tarea se supone que vas a correr todo desde main.py así que debería estar bien.
Saludos.
