### ISSUE TITLE
Metodo validez de competencia

### ISSUE THREAD

**Issue by BFry712** [IIC2233/syllabus#509]
Hola! tengo una duda sobre que deberia retornar este metodo, o si simplemente me condiciona para pasar al metodo de calcular ganador.

**Comment by furcelay** [comment]
Hola @BFry712 !
No hay una restricción a cerca de qué debe retornar el método `validez_de_competencia`, pero dado que se trata de un método que chequea una condición lo más acertado sería que retorne un *bool* que indique si las condiciones se cumplen :eyes:, luego puedes usar el resultado para decidir cómo sigue el flujo del programa.

Espero haber resuelto tu duda :smile:!

**Comment by BFry712** [comment]
Muchisimas gracias!
