### ISSUE TITLE
Dudas sobre widgets en qtdesigner

### ISSUE THREAD

**Issue by tamyhan** [IIC2233/syllabus#509]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Tengo dos dudas con respecto al uso de los QWidgets en Qtdesigner:
1. Hay alguna manera de hacer que los valores de un QSpinBox sean palabras en vez de números?
2. Cuando pongo un QProgressBar en la ventana en el Qtdesigner no me aparecen después cuando la abro desde el terminal. Qué tengo que hacer para que me aparezcan?
<img width="194" alt="Captura de Pantalla 2021-05-25 a la(s) 16 50 05" src="https://user-images.githubusercontent.com/71773541/119566640-5f26c180-bd79-11eb-98a0-6f96df5468a3.png">
<img width="197" alt="Captura de Pantalla 2021-05-25 a la(s) 16 50 19" src="https://user-images.githubusercontent.com/71773541/119566642-6057ee80-bd79-11eb-91d0-a21c7389463d.png">

**Comment by clementevalladares** [comment]
Hola @tamyhan, con respecto a tu primera duda, te recomendaría utilizar QComboBox en lugar de un QSpinBox, debido a que este último no está realmente diseñado para ingresar texto. Hay alguna razón en particular por la que prefieras usar QSpinBox?
Con respecto a tu segunda duda, puedes intentar utilizando los métodos setVisible(True) o raise_() para tu QProgressBar. 

`self.barra_progreso.setVisible(True)`  
`self.barra_progreso.raise_()` 

El primer método (setVisible) te sirve en caso de que por alguna razón haya quedado invisible por defecto. El segundo (raise_) en caso de que haya quedado debajo de otro objeto, con eso lo llevas al frente. Si ninguna de esas soluciones funciona puedes subir tu código a tu repositorio para ver lo que está pasando con más detalle.

**Comment by tamyhan** [comment]
Gracias!! Ahí cambié el QSpinBox por un QComboBox, no había visto que existía ese widget.
Pero con lo otro, probé con los dos métodos y todavía no me aparece :( Acabo de subir todo mi código actualizado al repositorio

**Comment by clementevalladares** [comment]
Estuve revisando tu código y si me aparecían los QProgressBar, podría ser que estén por defecto en tamaño 0 cuando corres el programa, Podrías verificar esto con:
`print(self.progressBar.size())`
En caso de ser así puedes utilizar el método `setFixedSize()` para establecer el ancho y el alto.
Avísame si funciona.

**Comment by tamyhan** [comment]
Según el print su tamaño no es 0. 
Me aparece esto: PyQt5.QtCore.QSize(107, 20)

**Comment by clementevalladares** [comment]
Y si haces setFixedSize() tampoco aparece?

**Comment by tamyhan** [comment]
Nop :(

**Comment by clementevalladares** [comment]
Que versión de pyqt5 estás utilizando?
Podrías intentar instalando la versión que yo tengo instalada para ver si así te funciona.
`pip uninstall PyQt5`
`pip install PyQt5==5.15.1`
En caso de que siga sin funcionar, y solo pase con los QProgressBar, puedes reemplazarlos solamente por QLabels que indiquen el porcentaje. Porque la utilización de  QProgressBar no es un requisito de la tarea.

**Comment by tamyhan** [comment]
Ahora me aparece!! Pero no altiro cuando abro la ventana, como que se demora un rato pero después me aparece
Gracias!
