### ISSUE TITLE
Descuento PEP8 en tareas sobre comentarios

### ISSUE THREAD

**Issue by Mariana-Julia** [IIC2233/Syllabus#509]
### Duda

En el caso de que en mi tarea tenga una linea que tiene un comentario pero este comentario supera los 100 caracteres de linea permitidos por PEP8 ¿igualmente se realiza descuento por no respectar PEP8 o para comentarios no aplica este descuento?

**Comment by kbetelgeuse** [comment]
Hola @Mariana-Julia !
Si es que una línea posee más de 100 caracteres, sin importar qué es lo que contenga, habrá un descuento asociado por no seguir las reglas PEP8. Esto incluye las líneas que contengan comentarios, ya sea si la línea solo posee comentarios, o si esta posee código y un comentario adicional el cual hace que esa línea en cuestión exceda los 100 caracteres.
Si es que posees problemas con la cantidad de caracteres debido a comentarios, se podría estar en las siguientes situaciones. Si es que una línea posee más de 100 caracteres debido a un solo comentario, es posible separarlo en varias líneas: se utilizaría `#` en el inicio de cada una para seguir escribiendo el comentario. Si es que se tiene junto al código un comentario que hace que la línea tenga más de 100 caracteres se pueden hacer diversas cosas: hacer el comentario más corto, separarlo en varias líneas, o bien, escribir el comentario en la línea anterior (lo necesario para cumplir con el límite de 100 caracteres en una línea).
Espero haber resuelto tu duda!
