### ISSUE TITLE
Forma de unir puntos en el juego

### ISSUE THREAD

**Issue by furzuadr** [IIC2233/syllabus#509]
Hola! Estaba implementando al forma de unir los puntos en mi juego. Hice lo siguiente: primero se crean las líneas de forma opaca y si hago click sobre ellas se pintan más oscuras. Se puede hacer de esta forma? Obviamente lo pondré en el readme. Así es como queda:

<img width="242" alt="Screen Shot 2019-06-13 at 2 56 50 PM" src="https://user-images.githubusercontent.com/48994882/59459904-e298b380-8deb-11e9-914f-39df8527a744.png">
<img width="236" alt="Screen Shot 2019-06-13 at 2 57 01 PM" src="https://user-images.githubusercontent.com/48994882/59459906-e298b380-8deb-11e9-92ab-adc9801e9729.png">
Gracias!

**Comment by KnowYourselves** [comment]
Hola @furzuadr!

Esta perfect!, el único requerimientos es que sea claro, y tu forma de representarlo esta clarisima. (Recuerda que cuando cierren los cuadradados debe haber un indicador poe cada jugador)

Saludos y éxito!
