### ISSUE TITLE
Error al clonar el repositorio

### ISSUE THREAD

**Issue by bgonzp** [IIC2233/Syllabus#51]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema
Si bien en issues ya estaba resuelto no estaba la explicación de como se resolvió, acabo de cambiar el computador y al clonar el repositorio me sale que hubo una falla en la autenticación.
<img width="569" alt="Captura de pantalla 2023-08-22 a la(s) 14 48 40" src="https://github.com/IIC2233/Syllabus/assets/141947842/1e95c0aa-ac9e-438b-b899-4fb34e0bc924">
la autenticación 
[Describe tu problema de manera detallada, explicando qué estás intentando hacer y explicando los errores o problemas que has encontrado. Se recomienda agregar fotos cuando sea posible]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Juampisaez** [comment]
Holaa @bgonzp👋🏼
Al momento que te pide la clave, no debes colocar tu clave de github, sino que debes colocar el token de acceso.
Este lo puedes encontrar en el siguiente [link](https://github.com/settings/tokens), o bien, ir a:
Settings > Developer settings > Personal access token > Tokens (classic)

Una vez aquí, debes crear un token y darle los permisos que consideres necesarios, te recomiendo user, _notifications, write/read discussions, delete_repo, admin_ y los de _repo_ (aunque si prefieres puedes seleccionar todos, esto te permitirá hacer muchas mas cosas si lo deseas aunque no es necesario).

Una vez creado el token, te retornará un hash, el cual deberás ingresar en el campo de la clave que te pide la terminal.

Quedo atento cualquier cosa,
Saludos,

**Comment by bgonzp** [comment]
Perfecto ahi me funzioni muchas gracias

**Comment by bgonzp** [comment]
Perfecto ahí me funciono muchas gracias
