### ISSUE TITLE
menú crear predios

### ISSUE THREAD

**Issue by fgallard** [IIC2233/Syllabus#51]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Crear_predios nos pide como argumento el nombre del archivo. En el menú no habla de escribir un nombre de archivo, sino solamente de que se debe usar el método crear_predios. 
Debemos asumir que el menú abre directamente un archivo con nombre predios.txt ???? es decir, estamos llamando a crear_predios(predios.txt) ?? porque de otra manera se requeriría que el usuario que use el menú escriba un nombre de archivo, pero no sale en el enunciado.

**Comment by individuocomunycorriente** [comment]
Hola!!
Así es, de hecho en T1/data se encuentra el archivo predios.txt, el cual como tu mencionas, debes cargar directamente al momento de ingresar la opción 1 del menú de acciones. Por ende, no existe una interacción donde el usuario escriba en consola el nombre del archivo donde se encuentran los predios, sino que todo se maneja mediante código.
En la sección 4.2 del enunciado hay un ejemplo sobre el manejo de predios.txt.
Saludos.

**Comment by diegoolivares42005** [comment]
Hola, sobre esto me surgió la duda ¿hay que subir la carpeta data que contiene a "predios.txt" al repositorio personal de github? Mi duda surge puesto que en enunciado dice que hay que ignorarla con .gitignore. Y en caso de que no se suba ¿Cómo va correr nuestro código?

**Comment by diegoolivares42005** [comment]
> Hola!! Así es, de hecho en T1/data se encuentra el archivo predios.txt, el cual como tu mencionas, debes cargar directamente al momento de ingresar la opción 1 del menú de acciones. Por ende, no existe una interacción donde el usuario escriba en consola el nombre del archivo donde se encuentran los predios, sino que todo se maneja mediante código. En la sección 4.2 del enunciado hay un ejemplo sobre el manejo de predios.txt. Saludos.

Hola, sobre esto me surgió la duda ¿hay que subir la carpeta data que contiene a "predios.txt" al repositorio personal de github? Mi duda surge puesto que en enunciado dice que hay que ignorarla con .gitignore. Y en caso de que no se suba ¿Cómo va correr nuestro código?

**Comment by individuocomunycorriente** [comment]
Efectivamente hay que ignorarla con .gitignore, su código va a correr de igual forma al momento de corregir las tareas dado que los ayudantes correctores dispondrán de su propia carpeta T1/data/predios.txt, debes tomar en cuenta que el archivo "predios.txt" que tendrán los ayudantes no es exactamente igual al que tienen los estudiantes, sin embargo tiene la misma estructura de manera que pueda correr el código.
