### ISSUE TITLE
Reciclaje y citación de código propio de Tareas de Semestres anteriores

### ISSUE THREAD

**Issue by olherreragz** [IIC2233/Syllabus#51]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola. Este ramo lo tomé en un semestre anterior a este y después lo boté pero alcancé a hacer una tarea que es bastante similar a esta por lo que podría reciclar mucho código, tanto así, que me podría ahorrar muchísima pega ¿**Puedo reciclar código de la Tarea 0 que hice en semestres anteriores**? De ser así, ¿Cuál sería la forma correcta de citarlo? ¿Con el link de mi repositorio antiguo bastaría?

Además necesito saber ¿**Hasta qué punto me podría auto-citar, reciclar código y no considerarse copia**? Esta última duda es muy importante porque de ser posible podría reusar Menús y funciones enteras a las cuáles sólo podría cambiar ciertos parámetros, y de no ser posible, de todas formas llegaría a soluciones bastante similares y lo encontraría un poco redundante.

Saludos y muchas gracias.

**Comment by olherreragz** [comment]
Hola, luego de volver a revisar Issues de semestres anteriores encontré que en 2021-01 se ocupó este criterio ¿Se vuelve a aplicar el mismo criterio?

https://github.com/IIC2233/syllabus-2021-1/issues/57

**Comment by matiasmasjuan** [comment]
Hola @olherreragz !

Efectivamente, **no hay problema** con que utilices código realizado en tareas de semestres anteriores **siempre y cuando** cites correctamente en tu **README.md** que el código utilizado lo sacaste de ahí. En ese sentido, no hay límite de cuánto puedes citar, pero debes tener mucho cuidado en el nombre de variables que utilices, ya que la temática de esta tarea es diferente a la del semestre anterior, por lo que si decides reciclar código debes considerar cambiar el nombre de las variables para que se adecuen al contexto de esta tarea y para no dificultar la corrección al ayudante.

Saludos!
