### ISSUE TITLE
fecha de un post creado

### ISSUE THREAD

**Issue by Pelaysen** [IIC2233/syllabus#51]
hola, cuando el usuario crea un post, este debe ingresar la fecha o el programa debe usar la fecha del computador?, prefiero la primera opción, gracias de antemano.

**Comment by aljara97** [comment]
Hola, tu duda ya fue respondida en la issue #12. Recuerda revisar el compilado de issues de la tarea (#7), para asegurarte de que duda no haya sido resuelta anteriormente.

Éxito con tu tarea :)
