### ISSUE TITLE
Duda sobre el estado de sesión del usuario al volver al menú inicial

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#51]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Al iniciar sesión en el menú de inicio se pasa al menú de chats con el usuario registrado o con el que se haya ingresado. Mi duda es sobre qué asumir al pasar del menú de chats al menú de inicio, **¿la opción "volver" sería equivalente a cerrar sesión?** Es decir, si volvemos de chats a inicio y luego queremos volver a ir al menú de chats, ¿siempre habrá que volver a iniciar sesión o registrarse?

Espero se haya entendido mi consulta 😊 y desde ya graciaaass ❤️.

**Comment by Juampisaez** [comment]
Hola @Rerro-r 
En la parte de Menus, 4.2 se menciona que el menu de chats tendra la opcion de volver al menu de inicio, y tal como mencionas tu, este sería equivalente a cerrar sesión. Si quieres volver al menu de chats, deberas iniciar sesion nuevamente.

Espero que haya quedado mas claro
Quedo atento de igual forma :)
