### ISSUE TITLE
Al ordenar una lista que forma parte los atributos de un objeto , cambia el type  al usar un property para hacerlo

### ISSUE THREAD

**Issue by cncosta** [IIC2233/syllabus#51]
hola tengo una clase "A" que uno de sus atributos es una lista de objetos "B" , lo que quiero lograr es que esa lista de objetos "B" quede siempre ordenada de acuerdo a uno de los atributo de "B". para esto ocupo un property y la función sort().
Dejo mi código abajo 
![Captura de pantalla 2019-03-26 a la(s) 18 57 36](https://user-images.githubusercontent.com/42576884/55036337-14725900-4ff9-11e9-8317-d1776c2caafe.png)

lo que sucede es que en el property cambia el tipo de objeto, pasando de una lista a un NoneType

![Captura de pantalla 2019-03-26 a la(s) 18 55 56](https://user-images.githubusercontent.com/42576884/55036258-d70dcb80-4ff8-11e9-892a-880bbab513e7.png)

**Comment by IchottMano** [comment]
Hola!

En este caso particular, el problema es que cuando llamas a la property lista, estás retornando lo que retorna la función [sort()](https://www.programiz.com/python-programming/methods/list/sort) de tu lista, lo cual es un None.

Lo que puedes hacer es retornar tu lista **luego** de ordenarla.

Saludos!
