### ISSUE TITLE
Duda respecto a la definicion de stack

### ISSUE THREAD

**Issue by dfloreaa** [IIC2233/syllabus#51]
Se da a entender que el _stack_ como estructura de datos es distinta a la lista, pero revisando el código es básicamente una lista llamada "stack" que se opera solamente con algunas operaciones disponibles para listas.

![image](https://user-images.githubusercontent.com/62019645/90587846-57ae0880-e1a8-11ea-9841-08b2e4300926.png)

En ese sentido, básicamente cualquier lista puede ser tratada como stack y viceversa y no tiene nada de diferente con una lista normal verdad?

**Comment by josefinareyes** [comment]
Para usar el concepto de _stacks_ en Python, se pueden implementar como listas, con las funciones que mencionas, o creando una clase ```Stack()```, asignándole a distintos métodos los nombres correspondientes (_push, pop, peek, etc._) y sus funciones asociadas (_.append(), .pop(), [-1], etc._)

Si bien en Python no existe un _stack_ como tal, en general se utiliza esta estructura por su simplicidad para almacenar y recuperar datos.

**Comment by dfloreaa** [comment]
Muchas gracias! ☺
