### ISSUE TITLE
Flujo menu de acciones

### ISSUE THREAD

**Issue by plourido** [IIC2233/Syllabus#51]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, que tal  :), les escribo para consultarles si al ingresar a una de las opciones del menú de acciones después se debe volver al menú de acciones. Es medio raro lo que pregunto, pero por ejemplo: Ya estando en el menú de acciones, el usuario indica opción [1] MOSTRAR TABLERO, el juego le muestra el tablero y posteriormente regresa al menú de acciones o el juego se termina y debo hacer todo el flujo completo nuevamente para entrar a otra opción?
muchas gracias

**Comment by pedrozavalat** [comment]
Hola @plourido !,

Cuando ingresas una de las opciones del Menú de Acciones, se notifica la respuesta de la acción ingresada en la consola, y después debes volver al mismo menú. Por ejemplo, si en el Menu de Acciones ingresas la opción ```[1] Mostrar tablero```, se debería imprimir el tablero en la consola, y luego regresarías al Menú de acciones. El juego en el Menu de Acciones no se debería terminar,  **a menos que** le ingreses opción ```Salir del programa```.

Cualquier duda responde este hilo,
Saludos 😄

Pedro Z.

**Comment by vmunozgarachena** [comment]
Hola, y en cual de las otras opciones también se debe volver al menú? porque me haría sentido que con la 1 y la 2 se deba volver, pero no creo que con la 3 y la 4 sea necesario. Gracias

**Comment by pedrozavalat** [comment]
Hola @plourido,

En el caso que tu tablero tenga solución, debes mostrar el tablero resuelto en la consola. En tu caso, si ya solucionaste el blero del archivo ```2x2.txt```, entonces cuando imprimas el tablero, deberias mostrar el tablero solucionado del archivo ```2x2_sol.txt```. 

Saludos

Pedro Z.

**Comment by pedrozavalat** [comment]
@pedrozavalat test

**Comment by MariaJoseSilva** [comment]
Hola!
Me queda una duda, me voy a basa en la pregunta del compañero
_"Respecto a la misma pregunta. Una vez que se ingresa a [4]Solucionar tablero, vuelvo al menú de acciones y selecciono [1]Mostrar tablero, ahí que tablero debo mostrar el tablero cargado o el tablero ya solucionado?
Ej: inicio juego con 2x2.txt ingreso a opción [4]Solucionar tablero, esta opción me va a generar 2x2_sol.txt y me regresa al menú de acciones, ahora selecciono [1]Mostrar tablero, aquí que tablero imprimo? 2x2.txt o 2x2_sol.txt
Muchas gracias"_

A lo que la respuesta fue "Sí", mi pregunta es sobre las acciones [2] y [3] ,  si estas deben ser respecto al tablero ya solucionado guardado en 2x2_sol.txt o respecto al tablero inicial 2x2.txt

El ejemplo ahora sería:
inicio juego con 2x2.txt ingreso a opción [4]Solucionar tablero, esta opción me va a generar 2x2_sol.txt y me regresa al menú de acciones, ahora selecciono  [3] ¿debería decir que el tablero está resuelto o que no?

Muchas gracias!

**Comment by pedrozavalat** [comment]
Hola @MariaJoseSilva !,

Cuando seleccionas un archivo en el Menú de Inicio, este **se mantendrá en toda ejecución dentro del programa**, por lo que si seleccionas la opción 3, y el tablero no cumple las reglas, te retornará que el tablero no es válido. Por ejemplo, si tu elegiste desde un principio el archivo ```2x2.txt```, y lo solucionas generando un nuevo archivo ```2x2_sol.txt```, luego al utilizar la opcion 3, aun te dirá que el tablero no es válido, por que ```2x2.txt``` fue el archivo que elegiste en el Menu de Inicio.

Estoy atento ante cualquier duda,

Saludos 😄

**Comment by Hernan4444** [comment]
Hola @MariaJoseSilva 

Para tu ejemplo, si soluciono y luego pido ver [3]. Dirá que no está resuelto. Porque desde que dice que quiero trabajar con "2x2.txt", todo el flujo será con ese tablero siempre. Solo si yo cierro el programa, abro uno nuevo y digo "2x2_sol.txt", ahí si estaré viendo el tablero solucionado.

Avisame si tienes otra duda 😄 
Saludos c:
