### ISSUE TITLE
Problema con tablero

### ISSUE THREAD

**Issue by tgarcia4** [IIC2233/syllabus#51]
Hola, tengo un problema con la funcion para imprimir el tablero, ya que, de input le doy una lista de listas y me imprime todo en una sola columna, ¿Qué puedo hacer?

**Comment by DCCollao** [comment]
Hola!
¿Podrías subir una foto del input que le entregas a la lista?
También serviría que subas una de lo que te imprime la función! 
Quedo atento.

**Comment by tgarcia4** [comment]
@DCCollao tenia como input un array, por eso no me resultaba, gracias!
