### ISSUE TITLE
Duda enunciado

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#51]
>Todos los usuarios nuevos que cumplan con la mayoría de edad reciben
una cantidad inicial de 100.000 DCC, y también 50.000 de las monedas respectivas (i.e. las dos
divisas que componen un mercado) cuando se ingresa a un mercado especifico.

No entiendo que son los 100.000 que deben abonarse.
Por ejemplo si un usuario ingresa al mercado "NECRUP", ¿qué es lo que recibe al ingresar?

**Comment by FernandoPieressa** [comment]
Hola!

Cuando un usuario se registra en el sistema recibe 100.00 DCC, luego por cada mercado al que uno ingresa recibe 50.000 de la moneda que vende en el mercado.

Por ej, digamos me registro al sistema (y en ningún mercado), entonces recibo 100.000 DCC (la moneda comun de todos los mercados). Luego, me registro en el mercado de NECDCC, entonces recibiria 50.000 NEC adicionalmente.

Saludos!

**Comment by Bneya** [comment]
¿Si me reigistro en el mercado RUPBAN, recibo 50.000 RUP y 50.000 BAN o solo de uno de los dos?

**Comment by fgbruna** [comment]
@FernandoPieressa Según lo que entiendo del enunciado, al ingresar por primera vez a un mercado específico en donde se utilizan dos monedas se recibe 50000 de cada una,no solo de la que se transa e independiente de la cantidad de DCC que se posean antes.

**Comment by naazocar** [comment]
Por lo que entendí del comentario del ayudante en #38, el mercado RUPBAN no existiría, por lo que si entras a un mercado con alguna de esas dos monedas (sea RUPDCC o BANDCC), se recibirían 50000 RUP o 50000 BAN respectivamente.

**Comment by FernandoPieressa** [comment]
Estimados, hubo una confusión entre ayudantes y se va a aclarar todo en breve en una Issue nueva.

Saludos!

**Comment by fgbruna** [comment]
Gracias!

**Comment by nachocontreras** [comment]
Si en #38 se dice que todos los mercados son una criptomoneda vs DCCoins, entonces por qué en orders.csv están los mercados KAMWUB o SIMRUP?

**Comment by stephichau** [comment]
lean la issue #54 !
