### ISSUE TITLE
No incluí archivos apropiados en el gitignore, como los elimino de mi repositorio?

### ISSUE THREAD

**Issue by keac1** [IIC2233/Syllabus#51]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Subí sin querer los archivos .csv y parametros.py al repositorio. Ahora que me di cuenta, los puse en el .gitignore pero siguen apareciendo en el repositorio **¿Como los puedo eliminar?**

**Comment by Emiliax16** [comment]
Hola @keac1 ! puedes eliminar esos archivos mediante la consola de git, con el comando: 

git rm -r --cached nombre_csv
git commit -m "mensaje"
git push

De todas maneras, te dejo un link que podría ser de utilidad: 
https://www.arsys.es/blog/programacion/eliminar-archivos-repositorio-git/#:~:text=un%20paso%20adicional.-,Eliminar%20los%20archivos%20del%20repositorio,de%20nuestro%20directorio%20de%20trabajo.&text=Con%20%E2%80%93cached%20mantenemos%20los%20ficheros%20en%20nuestro%20directorio%20de%20trabajo.

Avísame cualquier cosa. Saludos c:

**Comment by keac1** [comment]
muchas gracias! solo para confirmar: parametros.py tampoco se tiene que subir al repositorio ?

**Comment by Emiliax16** [comment]
parametros.py **si debe ser subido en todas las tareas**, ya que es un archivo que siempre debe ser rellenado con los parámetros que se indican en el enunciado u otros que necesites utilizar c:

**Comment by fmeza7** [comment]
Hola @Emiliax16 !
Me queda una duda respecto a esto del uso de .gitignore ya que en el enunciado sale que se deben agregar los archivos utilizados en la tarea al .gitignore pero se supone que uno los ocupa en la ejecución del programa, te agradeceria me puedas aclarar esto :).

![Captura de Pantalla 2021-09-02 a la(s) 20 12 15](https://user-images.githubusercontent.com/89094570/131931577-9d1c85df-b26a-4d72-ae65-1cee203f5650.png)

**Comment by Emiliax16** [comment]
Hola @fmeza7 😸 los archivos que se suben al gitignore son los que entregan el equipo de ayudantes **al subir el enunciado de la tarea** (csv, enunciado, etc). Tenemos acceso a estos archivos, por lo que al momento de corregir tu tarea, incluimos todos esos archivos para que funcione bien. Siempre se ejecuta la tarea con los archivos utilizados! No sé si se entiende, cualquier cosa quedo atenta.

Saludos!

**Comment by fmeza7** [comment]
Perfecto, gracias @Emiliax16 ! Ahí si me quedo claro :)
