### ISSUE TITLE
Recursos de una galaxia

### ISSUE THREAD

**Issue by Clemente24** [IIC2233/Syllabus#51]
Hola, no me queda muy claro para qué sirven los recursos que tiene una galaxia (i.e. Los recursos que vienen en el archivo galaxias.csv).

Entiendo que cuando uno empieza a jugar en una galaxia, parte con 1000 minerales y 1000 deuterios. O sea que finalmente sólo serviría para mostrar cuantos recursos tiene una galaxia en las consultas, y ni siquiera para el Ranking de Galaxias (puesto que aquí influyen los recursos del planeta).

Sería bacan si me lo puede aclarar alguien, por favor!
Gracias

**Comment by ptflores1** [comment]
Hola!
Al crear una nueva galaxia se parte con 1000 de cada recurso, pero las galaxias que vienen en glaxias.csv ya fueron creadas por lo que ya se gastaron y/o generaron recursos (en la tabla dice: "Cantidad de minerales en **posesion**"). Queda claro con eso ? 😄 
Saludos!

**Comment by joaquineichholz** [comment]
Hola, tengo la misma duda ya que el archivo de las galaxias dice el nivel de deuterio y mineral de ellas pero el archivo de los planetas no tiene esta información. ¿Debo repartirlos entre los planetas de manera random, equitativo o a mi criterio?

**Comment by Hernan4444** [comment]
Hola, en la #73 se explicó más sobre los recursos.
Saludos
