### ISSUE TITLE
Foto de Perfil

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#510]
Hola, puedo asumir que al momento de seleccionar una foto de perfil el usuario seleccionara un archivo en formato .PNG y no por ejemplo .pdf, etc?

**Comment by niguzman** [comment]
Tengo la misma duda, sobre todo porque en la distribución de puntos dice que se probará con imágenes de 3 y 4 canales y no entiendo a qué se refiere con eso

**Comment by DCCollao** [comment]
Hola!

La función que les entregamos también retorna la matriz de píxeles de una imagen en otro formato, y en ese caso la puedes pasar a png de todas formas(en otras palabras, esto no debería generar que se caiga tu programa).

Sin embargo, revisaremos que funciones con imágenes png, así que si quieres puedes asumir que **se seleccionará un archivo PNG.**

En cuanto a @niguzman , revisa la issue #483 , te podría ser de utilidad.


Saludos y éxito!
