### ISSUE TITLE
Herencia en metaclases

### ISSUE THREAD

**Issue by Regenschrim** [IIC2233/Syllabus#510]
Si creo una metaclase para crear el resto de mis clases, ¿cómo puedo hacer que mi metaclase también herede de thread?, ¿o se puede simplemente crear una clase por entidad y hacer que cada una herede de thread? 

Edit: 
lo que hice para el primer caso fue poner un super(threading.Thread).__init__() en el new de la metaclase y cuando llamaba a la subclase lo hacia a través de la forma:
variable = threading.Thread(target=subclase1(*args).run())
Luego, colocaba variable.start() y corría el thread, pero no se si es la forma correcta de hacerlo :(

**Comment by iqacevedo** [comment]
Hola,

¿Quieres que la metaclase heredé de Thread? O ¿Quieres que las clases creadas por las metaclase a hereden de Thread?. Si el caso es el segundo efectivamente deberías modificar el \_\_init\_\_ de las clases en el init para que hereden de súper que es la clase de la que heredan, pero deberías modificar las bases que recibe el new agregándolo Thread. Entonces no necesitas escribir `super(threading.Thread).\_\_init\_\_` si no que bastaría con que llamaras a `super().\_\_init\_\_()`. 

Quedo atento si soluciona tu duda, 
Saludos !

**Comment by Regenschrim** [comment]
Ya, creo que ahora lo arregle. Suponiendo que mi clase A es la meta, y B y C mis instancias de A. Lo que hice fue cuando definía B y C, además de poner que tenían por meta clase A les colocaba el threading.Thread en el parentesis: class B (threading.Thread, metaclass=A)`. ¿Es eso a lo que te referias?

**Comment by iqacevedo** [comment]
@Regenschrim creo que estoy un poco confundido con lo que quieres hacer,
¿Quieres que tu metaclase herede de Thread?
¿Que las clases que son creadas por tu metaclase hereden de Thread?
Si es el caso anterior, ¿Por qué no haces que hereden de manera normal, sin el uso de metaclases?.

Finalmente, si tu idea de usar metaclases es para algo más que para que hereden de Thread, entonces está bien lo que dices en tu último comentario. En caso de que solo sea para que hereden, no necesitas usar metaclases en ese caso.

Saludos !

**Comment by Regenschrim** [comment]
Dale, lo preguntaba porque no sabia si era necesario el uso de meta clases en la tarea, ya que hablaba de herencia creí que era necesario usar una meta clase, pero ya vi en otra issue que no era necesario :P Gracias de todas maneras!

**Comment by iqacevedo** [comment]
@Regenschrim si esto era para esta tarea, te recuerdo que la librería `threading` está prohibida para esta tarea.

Saludos !

**Comment by iqacevedo** [comment]
@Regenschrim lamentablemente no te puedo decir en que parte debes usar herencia por el mismo motivo que en #544. Te recuerdo que para heredar no es necesario hacerlo de una clase que provenga de una librería externa, puedes hacerlo de una clase que tu mismo hayas creado.
Mucho animo y suerte en la tarea !
Saludos !
