### ISSUE TITLE
Commit sin contenido T02

### ISSUE THREAD

**Issue by mjcadile** [IIC2233/syllabus#510]
Hola! me pasó que subí un commit (a tiempo) el cual le faltaba una carpeta con sprites, por lo que encontré en internet que con commit --amend se podía "arreglar" esto... me funcionó, pero además se me subió un commit que dice "Merge branch 'master' of https://github.com/IIC2233/..." y que no tiene nada de información. El tema es que se eligió este último para la corrección :( qué puedo hacer? 
Saludos

**Comment by entamburini** [comment]
Hola @mjcadile! :smile: 

La verdad es que no pasa nada, dada la naturaleza de git, los commits son acumulativos, es decir que aunque el último commit que hayas hecho "no tenga nada", en realidad están todos los cambios anteriormente hechos. 

Te recomiendo que veas [aquí](https://github.com/IIC2233/mjcadile-iic2233-2019-2/tree/d23cebc49fbddb660a4e8eb9273998c29becd6a9/Tareas/T02) los archivos y corrobores que está todo bien (ese link es el estado de tu carpeta T02 en el momento del commit que hemos recopilado).

Que estés bien! :D
