### ISSUE TITLE
Consulta sobre eventos

### ISSUE THREAD

**Issue by chuma9615** [IIC2233/Syllabus#510]
Hola!
Mi pregunta es si los eventos marcados como imprescindibles en el enunciado (punto 6) deben ser independientes entre ellos. es decir por ejemplo. los ayudantes se deben reunir para calcular la dificultad, pero podria esta dificultad ser calculada antes de calcular la nota de la evaluacion (siendo esta la misma para todos) y "matar dos pajaros de un tiro"? a mi criterio esto debería ser correcto ya que el evento en si si sucede pero no quiero meter la pata.

Gracias!

**Comment by rmsolari** [comment]
Hola, la dificultad y progreso esperado se calculan en un solo evento

**Comment by chuma9615** [comment]
Pero podemos ajustar nosotros el momento de ocurrencia al que encontremos optimo mientras este ocurra antes de la tarea?

**Comment by indonoso** [comment]
El momento en que ocurre el evento es el que dice el enunciado. Los ayudantes deciden la dificultad durante la reunión, no antes de evaluar las tareas. 
Si decides la dificultad en el momento de evaluar no estás siguiendo las restricciones del enunciado.
