### ISSUE TITLE
Duda con KeypressEvent

### ISSUE THREAD

**Issue by dnazal** [IIC2233/syllabus#510]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola 
Cuando intento ocupar KeypressEvent me funciona solo para algunas teclas, funciona solo con las teclas que no son ni numeros ni letras. Hago print para ver si esta funcionando pero solo imprime para algunas teclas.

**Comment by Juampisaez** [comment]
Hola @dnazal 
Es muy raro lo que me dices, en especial que no te funcione con las letras. Me da la impresion de que el metodo lo implementas de forma distinta a lo correcto, puedes subir tu repo a github y asi te puedo ayudar de mejor manera.

Quedo atento :)

**Comment by antoniafuica** [comment]
Me pasó lo mismo! Cómo se soluciona?

**Comment by Juampisaez** [comment]
@antoniafuica No te funcionan los botones?
