### ISSUE TITLE
Duda sobre uso de globals() en consultas_aninadas

### ISSUE THREAD

**Issue by monejo1** [IIC2233/Syllabus#510]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

Hola, voy a compartir una línea de código que uso en la función de consultas_aninadas:

funcion = globals()[nombre_funcion]

con esto, consigo la función asociada al str del nombre, la que despues puedo llamar.
La duda es, que sale en malas prácticas que variables globales es una mala práctica, pero esto no es una variable global si no que una función en el mismoa rchivo .py. ¿Es una mala práctica? ¿puedo hacerlo así?

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by wintermelyn** [comment]
Hola @monejo1!

Si bien el uso de globals() en este contexto solo está siendo utilizado para obtener una referencia a la función sigue siendo menos recomendable que soluciones más directas.

Una opción mejor es usar un diccionario con referencia a funciones, por ejemplo:

**Comment by wintermelyn** [comment]
Hola @monejo1!

Si bien para el codigo solo estás accediendo a las variables globales para obtener las funciones por nombre sigue siendo una mala practica y menos recomendable que soluciones más directas. 

Para estos casos una mejor opción es utilizar un diccionario con referencias a las funciones.

```python
funciones = {
    "nombre_funcion": mi_funcion,
    "otra_funcion": otra_funcion,
}

funcion = funciones.get(nombre_funcion)
if funcion:
    funcion()
```

**Comment by gracie-14** [comment]
Hola! Yo tengo una consulta parecida-- ¿utilizar un diccionario para esto con todos los nombres especificados cuenta como _hardcoding_? A veces no estoy segura qué está incluido dentro de _hardcoding_

**Comment by TarzanDeMaceta** [comment]
> ie

Hola, no hay problema con usar la idea que propones? Es necesario referenciarlo en el README? Pregunto por que es código citado después de la publicación de la tarea.

**Comment by wintermelyn** [comment]
> Hola, no hay problema con usar la idea que propones?

No hay problema 🧙‍♂️

> Es necesario referenciarlo en el README?

En principio la idea es bastante general así que diría que no es necesario. Puedes referenciarlo de igual manera si así lo prefieres.
