### ISSUE TITLE
Excepciones en Menus

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#510]
Duda, en los menus tenemos opciones del 0 al 6, si ponen 7, lo trabajamos como excepción o esperamos que el usuario sigua las instrucciones puestas en el codigo?

**Comment by aljara97** [comment]
Hola @CataSudo!

En la [distribución de puntaje](https://docs.google.com/spreadsheets/d/15SDoSSz9VINHPLQwmdgAIT_0-A2eDpvHsk3cTLGfXG0/edit#gid=0) hay un ítem asociado a la robustez del programa, por tanto, no puedes asumir que el usuario seguirá las instrucciones de los menús.

Éxito en tu tarea 🧙
