### ISSUE TITLE
Convolución de matrices

### ISSUE THREAD

**Issue by robertov1** [IIC2233/syllabus#511]
Hola! Usando el método convolve de numpy, me tira este error cuando convoluciono la matriz de la imagen con un núcleo

`    return multiarray.correlate(a, v[::-1], mode) `
` ValueError: object too deep for desired array`

Por qué me tira ese error?

Gracias!

**Comment by DCCollao** [comment]
Hola!
Buscando encontré [esto](https://stackoverflow.com/questions/15923081/valueerror-object-too-deep-for-desired-array-while-using-convolution)
Que, en resumen, dice que no estás entregando los tamaños correctos.
Quedo atento!
