### ISSUE TITLE
Compra de DCCriatura y el estado de la criatura

### ISSUE THREAD

**Issue by anamarn** [IIC2233/syllabus#511]
Hola!
Se me vino una duda al hacer la venta de DCCriaturas. Mientras que establezco al azar las estadísticas de la criatura, también establezco al azar el estado en el cual compre la criatura (es decir puedo comprar un Niffler enfermo y con baja salud por el mismo precio que uno sano y con alta salud). O puedo asumir que como el DCC es una institución respetable te los entregaran en buen estado (max salud, sanos) ?
Gracias!

**Comment by aljara97** [comment]
Hola @anamarn!

Puedes asumir que el DCC te venderá siempre criaturas en buen estado, recuerda que debes fijarte que sus parámetros respeten el rango establecido. Te sugiero indicar este supuesto en  tu README y citar esta issue.

Suerte con tu tarea 🧙
