### ISSUE TITLE
Aparición de objetos en el mapa

### ISSUE THREAD

**Issue by colobos** [IIC2233/syllabus#511]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Los objetos deben aparecer dentro de una única baldosa o pueden encontrarse hasta en cuatro baldosas al mismo tiempo?
Saludos, y muchas gracias!!

**Comment by tqmbanados** [comment]
Hola! La verdad no entiendo muy bien tu pregunta, ¿te refieres a que los objetos puedan aparecer sobre un vértice entre cada baldosa, así ocupando espacio de cuatro, o que los objetos pueden aparecer del tamaño de 4 baldosas?

Si tu pregunta es lo primero, es opcional, pues el enunciado no especifica nada al respecto. Únicamente que aparezcan sobre el tablero y no encima de un obstáculo (esto último sale especificado en la sección 3.4 del enunciado, *Obstáculos*).

Si tu pregunta es lo segundo, también es opcional! El tamaño de los sprites de objetos en los assets es aproximadamente el doble que el de cada baldosa, sin embargo, eres libre de cambiar el tamaño de los sprites si crees que aporta una mejor experiencia. Ojo que si haces eso, debes hacerlo con el método ```resize``` del ```QLabel``` que tiene el sprite, pues si cambias el sprite directamente no se verá reflejado en tu entrega, dado que usaremos los assets como son presentados originalmente. Recuerda también que el tamaño de widgets debería ser un parámetro, por ejemplo, ```TAMANO_OBJETOS```. Lo más probable es que tengas que jugar un poco con el tamaño de las cosas, así que no tengas miedo de hacerlo!

**Comment by colobos** [comment]
Muchas gracias por ambas respuestas!!

**Comment by vcrb18** [comment]
Una pregunta respecto a lo que dijeron de resize. Si yo hago aparecer un label en la ventana de juego manualmente, es decir, a través de código no de Qt Designer, y a este le hago el comando de setGeometry y hago que el tamaño del label sea el mismo tamaño del label de homero y lisa, hay que aplicar igual resize? Con SetGeometry no bastaría?

**Comment by tqmbanados** [comment]
Hola @vcrb18! Con setGeometry bastaría :).

**Comment by piacabrera** [comment]
Hola! con respecto a "Únicamente que aparezcan sobre el tablero y no encima de un obstáculo", pueden aparecer dos objetos en la misma posición? o también debemos restringirlo?
