### ISSUE TITLE
duda test_0 carga datos pizzas_vendidas_mes_pais

### ISSUE THREAD

**Issue by danogajardo** [IIC2233/Syllabus#512]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Me falla este test y me puse a revisar "manualmente" la data para encontrar mi error, resulta que en ghana solo hay un local que vende 4 pizzas pero el testcase dice que deberian ser 13. No sé si el testcase está malo o yo entendi mal el enunciado, aún asi es el único testcase que me falla entre los de carga de datos y correctitud

**Comment by FradexMF** [comment]
Hola @danogajardo !
Revise los datos y estos están bien. También revise tu código y por lo que veo no estas guardando **todos** los pedidos asociados a un local, si no que lo sobrescribes (linea 502):
![image](https://github.com/user-attachments/assets/6bdb48dd-87bb-4a10-a2e2-2bcc5487cd12)
Aquí se ve como tenias guardado el id_pedido 49 para el id_local 15 (el que esta en Ghana), pero luego se sobrescribe para id_pedido 57, por lo que cuando sumas la cantidad de pizzas te están faltando las pizzas del pedido 49.

Ojala esto te ayude para resolver el error, suerte!
