### ISSUE TITLE
Problema para subir el Readme.MD

### ISSUE THREAD

**Issue by cristozille** [IIC2233/syllabus#512]
Hola, edité el archivo Readme.MD y lo traté de subir con git add Readme.MD pero al hacer el commit no lo considera como un archivo modificado y no lo sube a GitHub. Que puedo hacer para arreglar esto?

**Comment by lily416** [comment]
Hola 😃 

1. Haz una copia de tu _readme_ en otra parte (o si prefieres de toda la tarea).
1. Vuelve a clonar tu repositorio.
1. Agrega los archivos que quieres subir.
1. Y trata de hacer _pull_.

Cuentame como te va 🤓:octocat:

**Comment by cristozille** [comment]
Hola, no me funcionó. Traté también de eliminarlo con git rm -r y me dice que no existe el archivo Readme.MD, sin embargo este esta en el repositorio.

**Comment by lily416** [comment]
@cristozille ¿puedes mandar una captura de pantalla del error y el comando que estas ingresando?

**Comment by cristozille** [comment]
<img width="569" alt="Screen Shot 2019-10-14 at 11 04 17 AM" src="https://user-images.githubusercontent.com/42190189/66757386-78b01980-ee72-11e9-9038-80b421982b54.png">
<img width="564" alt="Screen Shot 2019-10-14 at 11 04 35 AM" src="https://user-images.githubusercontent.com/42190189/66757401-81085480-ee72-11e9-8cc7-b9280d3e6c57.png">

**Comment by lily416** [comment]
Trata escribiendo `Readme.md` en vez de `Readme.MD`.

**Comment by cristozille** [comment]
Ahi sí! Muchas Gracias :)

**Comment by lily416** [comment]
Yay 🙌
Si mal no recuerdo los Mac son _case sensitive_, es decir que para los archivos y directorios distingue entre mayúsculas y minúsculas, para que lo tengas en consideración al momento de acceder a archivos.
