### ISSUE TITLE
Error en terminal, PowerShell

### ISSUE THREAD

**Issue by santandergc** [IIC2233/syllabus#512]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Tengo un problema al ejecutar el código, la mayoría de las veces que ejecuto mi código me aparece este error

![image](https://user-images.githubusercontent.com/80907322/119587719-40d2bd00-bd9d-11eb-9ee2-26e5d0d2a053.png)

Luego de aparecer este error me obligado a reiniciar el Host, o sino no me deja correr ningún código. Otras veces que me aparece este error lo ejecuto nuevamente y ahí me corre bien, pero aun así en la terminal aparecen datos sobre PowerShell y "El valor debe ser mayor que o igual a cero y menor que el tamaño de búfer de consola en dicha dimensión. Nombre del parámetro: left"

Es muy raro y molestoso, porque la mayoría de las veces no me deja correr mi código, busque soluciones en foros y aun así no me funciona, no se que hacer.

**Comment by MatiasDuhalde** [comment]
Hola @santandergc !

El semestre pasado recuerdo haber respondido una issue con exactamente el mismo error al tuyo, y a la estudiante al parecer le funcionó la solución dada.

Esta es la issue en cuestión: https://github.com/IIC2233/syllabus-2020-2/issues/108

Al parecer el error tiene que ver con un problema en la versión del paquete PSReadLine de PowerShell (que tiene problemas al leer el input cuando es integrada en aplicaciones como VSCode), y lo que debería arreglar el problema sería simplemente actualizar el paquete (lo cual se explica en la issue linkeada).

Intenta replicar la solución, y si sigues con problemas, vuelve a comentar en esta issue! :sparkles:
