### ISSUE TITLE
Llegada de funcionarios a campus

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2233/Syllabus#512]
Se dice que los miembros de la PUC llegan a la u según la distribución triangular, pero sólo se especifica que los alumnos llegan en metro. ¿Asumimos que para alumnos y funcionarios es posible comprar un snack cuando llegan al campus, o sólo para los alumnos?

**Comment by egromero** [comment]
@jpmoraga1 Hola, por lo general cuando diga miembros de la PUC o personas (entiendase a los externos como una entidad distinta) se refiere a los alumnos y a los funcionarios.
