### ISSUE TITLE
Foto de perfil jugador

### ISSUE THREAD

**Issue by niguzman** [IIC2233/syllabus#512]
Hola,
me queda la duda si la selección de la foto de perfil del jugador debe estar implementado siempre o una vez que ya la escoge esta no se puede cambiar, es decir, queda esa foto guardada en el servidor asociada a ese jugador.

**Comment by gatochico** [comment]
Hola! Queda a tu criterio si el jugador puede cambiar su foto de perfil una sola vez, o las veces que quiera. Explicitalo en tu README, eso sí.
Éxito! 💻 :cat:

**Comment by niguzman** [comment]
Gracias,
me surgió otra duda respecto a esto mismo
Se supone que cada vez que uno inicia sesión el servidor almacena esa información. Si es que decidí que el usuario sólo pueda elegir la imagen una vez, cuando vuelva a iniciar esa misma foto se vuelve a cargar o se le debe preguntar de nuevo si, en ese caso, quiere mantener la foto o actualizarla?

**Comment by gatochico** [comment]
Debido a que estamos evaluando permanencia de datos, efectivamente debería mostrarse la ultima foto cargada por el usuario anterior cuando se inicie una sesión con el mismo nombre de usuario. Saludos!

**Comment by iqacevedo** [comment]
Hola !

En la distribución de puntaje salia que se evaluaría cambiar la foto de perfil. Lo sacamos y ahora solo evaluamos que se cargue una foto cuando no existe (pueden verlo [acá](https://docs.google.com/spreadsheets/d/1Xk7vlKgcRdXWRUjpf0zXCzL0IcNlR2PK2fqmIXWD-5M/edit?usp=sharing), en la sección de ventana de salas). Asi que es tal como dijo @gatochico.

Éxito en la tarea !

**Comment by pmolinaj** [comment]
No me queda muy claro un aspecto de la foto de perfil;  En el caso de un jugador que inicie con un nombre determinado, y sea la primera vez que alguien use es nombre, el podrá elegir su foto. Pero si un jugador distinto inicia sesión después usando el mismo nombre que el jugador anterior(Y el primero que usó el nombre está desconectado)¿Tendrá la misma foto que seleccionó el primer jugador?

**Comment by iqacevedo** [comment]
Si, justamente es como dices. El servidor tiene que guardar la foto de perfil de un jugador, cuando ese usuario se conecta debe mostrar La foto de perfil que guardo el servidor. Para que quede más claro, si yo subo una foto de perfil al servidor, me desconecto, borro La foto de perfil original que le envíe al servidor (suponiendo que estaba en la carpeta cliente), cuando me vuelvo a conectar el servidor debería enviarme La foto de perfil que guardo, para que pueda mostrar esa en la interfaz.

Se entiende ? Quedo atento !

**Comment by pmolinaj** [comment]
Entonces, ¿Todos los clientes con igual nombre tienen la misma foto?, si es así, ¿Esa foto la determina el primer jugador en utilizar ese nombre?

**Comment by jeschuwirth** [comment]
Si dos cliente tienen el mismo nombre, entonces son el mismo usuario para tu programa, piénsalo como si facebook no tuviera contraseña y te pudieras conectar al perfil de alguien con sólo de correo.

Como dice el enunciado:
![image](https://user-images.githubusercontent.com/37160256/59646051-0db03980-9143-11e9-9a91-c2f0a02ad475.png)
 
Por lo tanto la foto de perfil la elige el primer usuario en apretar el botón selector de archivos y seleccionar una foto de perfil.

Suerte!
