### ISSUE TITLE
Distribución de Puntaje - Consola / Opciones mínimas

### ISSUE THREAD

**Issue by Tvergara** [IIC2233/syllabus#512]
Hola, en el apartado de Consola, hay un item que es "Opciones mínimas" en donde dice: "Visualiza los resúmenes de todos los eventos del día que se mencionan en el enunciado." Pero en el enunciado no leí en ningún lado que se deba hacer un resumen en la consola de los eventos del día. ¿A qué se refiere este item?

**Comment by jitorcas** [comment]
Hola! @Tvergara 

Hace referencia a la sección `3.2.3 Mostrar estado`.

Mucho éxito! 🥇
