### ISSUE TITLE
Almacenamiento de tamaños y posiciones de labels en Backend 

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#513]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Calcular y almacenar los tamaños y posiciones a travez del Backend esta bien o se considera mala practica?

Que controlar el tamaño y posicion de los labels es algo que hace el frontend, pero es mas comodo que lo controle el frontend para determinar las colisiones. ¿Si no se puede, puede el backend almacenar la parte del label que colisiona, algo asi como area_colision?

saludos

**Comment by mmunoz12** [comment]
Hola @Ignacioislae! si! Como dices, el frontend se encarga de controlar todo lo que tiene que ver con la interfaz del programa, como mover labels y determinar sus colisiones. Si bien, un correcto backend no puede controlar elementos de la interfaz de forma directa, sí puede almacenar información sobre esta como ubicaciones de sus elementos, su área, y cualquier data que necesites para manipular después el frontend. Avísame si te quedan dudas!☺️

**Comment by Ignacioislae** [comment]
Dalee, entonces si tuviera una clase que almacenara la posiciones de labels en el backend, y cuando estas cambiaran mandara señal a una clase del frontend que se encarga de la parte visual estaria bien o no?

**Comment by mmunoz12** [comment]
Claro, estaría bien. Mientras no manipules directamente nada visual desde el backend, estaría bien hecho.
