### ISSUE TITLE
Mensajes del chat

### ISSUE THREAD

**Issue by emena97** [IIC2233/syllabus#513]
Qué pasa cuando paso de la sala de espera a la ventana de juego con los mensajes que se habían escrito en el chat, es necesario pasarlos? o se puede implementar otro chat nuevo?

**Comment by KnowYourselves** [comment]
Hola @emena97!

Cuando empieza el juego se debe mantener el chat de la sala de espera, lo único que esto implica es que **se deben mantener los mensajes**. Es válido crear una ventana nueva y mantener los mensajes, también es válido mantener exactamente la misma ventana. Si es que el juego empieza y hay solo **un chat** y este **tiene los mensajes escritos antes de empezar** todo bien.

Espero haberte ayudado!

**Comment by emena97** [comment]
Perfecto!
Gracias!
