### ISSUE TITLE
Descuento pep8

### ISSUE THREAD

**Issue by danogajardo** [IIC2233/Syllabus#513]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En esta tarea igualmente corre el descuento por pasarse de las 400 lineas de codigo?

**Comment by kbetelgeuse** [comment]
Hola @danogajardo.
Para resolver tu duda te recomiento ver la issue #466.
En ella se habla acerca de este mismo tema 😉.
Saludos!
