### ISSUE TITLE
Compra influenciada por la tarea

### ISSUE THREAD

**Issue by moquezada** [IIC2233/syllabus#513]
Hola, después de tanto tiempo dedicado a la tarea, acompañada de la frustración por no poder tener la granja de mis sueños con mi juego, terminé comprando Stardew Valley 🤔🐔

¿A alguien más le pasó? También vale si lo descargaron 4free ☠️

**Comment by jeschuwirth** [comment]
Luego de mucho tiempo dedicado a Stardew Valley en las vacaciones propuse ese tema para la T02, no es lo mismo pero estoy seguro que cuenta jajaja

**Comment by DonJavi-538** [comment]
Yo volví a jugar Harvest Moon para inspirarme durante la tarea sjkkajs, le puse hasta el soundtrack
