### ISSUE TITLE
Extender plazo entrega tarea 1

### ISSUE THREAD

**Issue by CarlosOlivos** [IIC2233/syllabus#513]
Estimados quería preguntar si existe la posibilidad de dar un par de días más para la entrega de la tarea, puesto que en la ayudantía de ayer varios compañeros y compañeras manifestaron que estaban atrasad@s porque estamos en temporada de I'es y bueno por la contingencia ha sido difícil sobrellevar esto.

**Comment by entamburini** [comment]
Hola @CarlosOlivos,

Sólo para comentar, que otros cursos tengan I'es no es razón suficiente como para correr una evaluación... sino nunca podríamos tener evaluaciones nosotros :sweat_smile:. 

El otro motivo que esgrimes es mucho más válido, todos nos hemos visto afectados con este contexto en mayor o menor medida y por lo mismo tratamos de ajustar cada evaluación que hemos hecho con eso en mente :o 

De todas formas habrá un anuncio al respecto :wink: 
Enzini

**Comment by CarlosOlivos** [comment]
Hola Enzo, estoy de acuerdo contigo, muchas gracias por tu respuesta.
