### ISSUE TITLE
[ Duda super().__init__() ]

### ISSUE THREAD

**Issue by Okhan97** [IIC2233/Syllabus#513]
Hola buenas, googleando me he dado cuenta de que el comando super().__init__() para heredar lo usan de maneras distintas y no logro entender la diferencia.

¿ Los parámetros que van en "super()" que función tienen ?, tampoco entiendo que función tienen los parámetros del init, en un principio pensé que era como iniciar a la clase padre, pero en internet he visto varios ejemplos donde omiten esto D: 

PD: También he visto ejemplos en donde ponen parámetros tanto en super como en init, pido por favor explicar esto

**Comment by indonoso** [comment]
puedes mostrar ejemplos? Hay unos ejemplos que son de python2, no de python3, por eso puede haber diferencias.

**Comment by Okhan97** [comment]
https://stackoverflow.com/questions/576169/understanding-python-super-with-init-methods

El segundo comentario contiene el ejemplo que no entiendo

**Comment by akaminetzkyp** [comment]
Hola! Esto es lo que yo se. En Python 3, no es necesario entregarle parámetros al ˋsuper()ˋ. Sin embargo, el ˋ__init__()ˋ recibe los parámetros que recibe el ˋinitˋ de la clase padre.

**Comment by indonoso** [comment]
> ¿ Los parámetros que van en "super()" que función tienen ?

En python2 se ponían para indicar que debías llamar al `init` de la clases base de `ParamSuper`. En python3 (el que usamos en el curso) no es necesario hacer esto. Solo debes hacer `super().__init__(*args, **kwargs)` y python se encargará de llamar a los `init` de las clases bases de acuerdo al `__mro__`. [Esta respuesta](https://stackoverflow.com/questions/222877/what-does-super-do-in-python/33469090#33469090) explica por qué eso es necesario.

> , tampoco entiendo que función tienen los parámetros del init, en un principio pensé que era como iniciar a la clase padre, pero en internet he visto varios ejemplos donde omiten esto D:

Exactamente, los parámetros del `init` son los parámetros del `init` de la clase padre. Si el padre no recibe parámetros en el `init`, es normal que no le pasen argumentos.

> PD: También he visto ejemplos en donde ponen parámetros tanto en super como en init, pido por favor explicar esto

Son cosas totalmente independientes. Arriba están explicadas las funciones de cada uno

PD: usa bien markdown. Recuerda marcar lo que es código para que sea más fácil entender tu pregunta
