### ISSUE TITLE
AC08 y simulación

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2233/Syllabus#513]
Me quedó una duda de la forma correcta en la que habría que modelar los eventos en la actividad, plz help.
Para inicializar los eventos en la simulación, lo que hicimos fue agregar un evento de lluvia, un evento de accidente, y eventos de atajos para todos los atletas. La duda que me quedó de esto es que, en el caso de que hubiese lluvia antes de que un competidor llegase a la mitad de la meta, o que algún competidor se lesionara, entonces el evento de atajo para ese atleta quedaría obsoleto (porque el tiempo de llegada a la mitad cambiaría o porque el atleta ya no está en carrera).  En ese caso, pensaba que podría ser una solución sacar los eventos anteriores y reemplazarlos, pero como la simulación se trabaja con una cola me parece poco correcto estar recorriéndola todo el tiempo para sacar elementos distintos.
En el fondo la pregunta es, si hay eventos creados que pueden verse afectados por eventos que ocurrirán antes de que se llegue a ellos, ¿hay una forma "elegante" de no tomar en cuenta ese evento y reemplazarlo por el correcto?

**Comment by santilaguna** [comment]
Sumándome a esta pregunta  ¿sería correcto modificar el tiempo de ocurrencia del evento atajo?
