### ISSUE TITLE
Readme (líneas del código)

### ISSUE THREAD

**Issue by mrrebolledo** [IIC2233/syllabus#514]
Hola! En la pauta sale que tengo que poner en el readme las líneas donde use señales. Pero en la parte de Ventana Juego que sale "información de la ventana se actualiza correctamente a lo largo del juego" no entiendo que tantas líneas tengo que poner, porque son muchas y no creo que tenga que poner todas, o si? 
En la parte General sale que tengo que decir en que líneas puse que no hay dependencias circulares pero tampoco entiendo como mostrar eso.
Gracias!!

**Comment by lily416** [comment]
Indica en qué líneas creas las señales y donde las conectas, si quieres complementar un poco más tu respuesta puedes decir **brevemente** para qué las usas (que información comunican).

Saludos y éxito en tu readme 👋🤓

**Comment by lily416** [comment]
En cuanto a las dependencia circulares, puedes indicar las líneas donde instancias las entidades del _back-end_ y el _front-end_, para que así al corrector le sea más fácil encontrarlas y pueda comprobar que no tengan dependencias circulares.

**Comment by jac-34** [comment]
Hola, en que parte sale que hay que escribir donde se crean las señales? Busque en la distribucion de puntajes y en el enunciado y no lo encontre.

Gracias

**Comment by jac-34** [comment]
ya lo encontre, gracias

**Comment by FelipeA7** [comment]
@lily416 Es necesario decir donde está CADA señal que ocupé? En mi código hay más de 20 señales por lo que mi readme quedaría complicado
