### ISSUE TITLE
Comienzo de ronda nueva

### ISSUE THREAD

**Issue by gonzaga2000** [IIC2233/syllabus#514]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo una duda de cuando empieza una nueva ronda. En el caso de que elegí a 'x' personaje para comenzar el juego, cuando termina la ronda se debe volver al menú de preparación, el usuario pude elegir otro personaje? o tiene que ser el mismo que eligió al principio.

**Comment by valerianazal** [comment]
Hola @gonzaga2000 !! Efectivamente es como dices, al terminar la ronda, si el personaje sigue con vida y el jugador quiere continuar con la partida, se debe mostrar nuevamente la **ventana de preparación**, donde se puede cambiar el personaje y/o la dificultad si así lo quiere el jugador. 
Espero te haya quedado claro! 😊

**Comment by gonzaga2000** [comment]
@valerianazal buenisimo! muchas gracias!
