### ISSUE TITLE
Variables globales, strings largos

### ISSUE THREAD

**Issue by kipasten** [IIC2233/syllabus#514]
Estaba revisando las issues y leí que **no** se puede dejar un string (en mi caso describiendo un menu) en parametros.py. 
Tengo todos los menus modelados así para poder llamar input(menu_correspondiente) y tener todas las descripciones ahi.
si hago un diccionario y junto todos los menus en él pasa a ser un parámetro?? 
porque ahora dentro de parametros .py tengo: 
menu_n = ''' toda la descripción del menu '''
.
.
. mas menus  y diccionarios.....
¿Cómo lo hago para que sí sean parametros?
¿Qué es lo incorrecto?

**Comment by matiasmasjuan** [comment]
Hola @kipasten !

La idea del archivo ***parametros.py*** es almacenar toda la información que puede ser *variable* y *cambiar* en algún momento antes de ejecutar tu programa, de tal forma que no tengas que cambiar **manualmente** ciertas acciones en tu código para que el programa funcione.

En ese sentido, **si** se pueden **almacenar** ***strings*** en el archivo *parametros.py*. (Asi como también *diccionarios, namedtuples, booleans o integers)*, **siempre y cuando** sus nombres sean **descriptibles** y **fáciles de reconocer a simple vista**. Por ejemplo un ***path*** para abrir un **archivo** es un ***string*** y si es necesario que se encuentren en *parametros.py*.

Con respecto a tu pregunta, dado que la "descripción de menús" no es prácticamente un **parámetro**, ya que siempre irá en tu archivo y **nunca** sufrirá **modificaciones** antes de correr tu programa, no creo que sea necesario incluirlos **dentro** del archivo *parametros.py*. Lo que si puedes hacer, es crear otro *archivo.py* que contengan todos los *prints()* o descripciones de los menús, y esos **si** puedes importarlos a tu **código**. En él podrás incluir **datos de todo tipo**, (*strings, booleans, diccionarios, namedtuples, listas, etc*) ya que no es el ***parametros.py*** oficial.

Espero haber respondido a tu pregunta y mucho éxito con tu tarea! 😄

**Comment by sbcorrea** [comment]
hola! yo también terminé metiendo toda la info de los menus en parametros, despues de una laaaarga conversacion la issue #424 hasta entender lo que eran las variables globales y cómo evitarlas. definitivamente entiendo por qué tendría que mover el contenido de los menús a un archivo nuevo, pero me queda una duda, porque **hay cosas dadas en el enunciado que yo sí consideré parámetros aunque no sean números. **

**por ejemplo**, el nivel de agresividad por defecto para cada tipo de criatura es constante, pero es 'inofensiva', 'arisca' o 'peligrosa'... aun considerando que perfectamente estos podrian haber sido nivel 1, 2 y 3 en el enunciado. Así como se podría variar mi código al decidir que el rango de nivel de magia de una criatura va a ser distinto, yo también podría decidir antes de correr el código que voy a cambiar el nivel de agresividad que una criatura nueva tiene por defecto, y me imagino que esto tendría implicancias parecidas que variar otros parámetros por defecto numéricos.
también, por defecto, se entregan las criaturas sanas y capturadas, donde mis valores por defecto de 'enferma' y 'escapada' (estado salud y estado escape en el Enunciado) son False. sin embargo, podría perfectamente querer modificar este hecho simplemente para agregarle dificultad al juego, no? volver esto un parámetro podría facilitar la modificación del código para sacar una nueva versión del juego que fuera DCCriaturas Fantásticas Salvajes y Cómo Domarlas 🌈 

suena rebuscado, pero **mi punto es que el Enunciado nos da muchos valores constantes que no son numéricos, y que siguen la misma logica, de hacer que el código sea modificable,** que los parametros. entonces mi pregunta es: por no ser números, ¿me funan si mancho el buen nombre de los parámetros con strings y bools? ¿los tengo que separar porque sí en otro archivo aunque se usen para instanciar lo mismo, creando complicaciones de diseño en mi código? ¿tengo que hacer un manifiesto como este en mi readme y prenderle velitas a le ayudante que me corrija para que esté de acuerdo conmigo? ¿qué hago para evitar el descuento ahora que ya me pasé tantas horas reestructurando para no tener una sola variable global? 😢 😢 😢 😢 

gracias por acompañarme a ver esta triste historia, y ```'gracias' * parametros.MUCHO``` si me ayudan a darle un final feliz

**Comment by matiasmasjuan** [comment]
Hola @sbcorrea !

En primer lugar, me alegra que hayas podido entender de **raíz** lo que representan los **parámetros** y la **lógica** detrás de estos 😄 
Con respecto a tu primera pregunta, **nadie** te va a "funar" por utilizar *strings* y *bools* en el archivo ***parametros.py*** 😅 y debes tener en cuenta que **todos los ayudantes** **SIEMPRE** leemos los *Readme* y los supuestos antes de comenzar con la corrección.
En relación a los **parámetros**, estos pueden ser **cualquier valor** que tu consideres que podría ser considerado como una variable **modificable**, y que a pesar de este cambio, tu programa funcionaría igual. En el enunciado, nosotros dimos todos los **parámetros** númericos y de *strings* sobre los **nombres** de ciertas características de las entidades. Por ejemplo el caso en que tu mencionaste, en donde una **DCCriatura** puede ser *inofensiva, arisca o peligrosa*. Este tipo de valores **no** son **numéricos** pero sí podrían ser considerados un **parámetro**, ya que permiten que tu programa pueda ser modificable.

 Además, recuerda que es posible almacenar todo tipo de valores en el formato que te sea más conveniente. Por ejemplo puedes usar *diccionarios* para almacenar ciertos valores relacionados, *namedtuples*, *bools*, etc, siempre que respetes la condición de los nombres de ellos sean **descriptibles**.

Ahora bien, lamentablemente la idea del archivo ***parámetros.py*** es almacenar todos estos valores correspondientes a **características** de las *entidades*, o *paths hacía rutas*. Por lo tanto, si tienes que almacenar otro tipo de **parámetros** en este archivo que **no tengan** relación con esto, y se deban principalmente al control de flujo, o secuencia de tu programa, **no recomiendo** que se encuentren en el archivo ***parametros.py***, ya que no lo estarías utilizando con el objetivo que queremos que ustedes cumplan. 😭 En este sentido, tendrías que crear otro archivo e ingresar estos valores allí. 

Intenta recordar el **por qué** estas realizando esa metodología. La razón de ello es porque intentas **evitar** utilizar **variables globales**. Recuerda que en la *Issue* #424 se definió que cualquier *variable* creada **dentro** de una función es considerada **local** y correcta, por lo que allí, puedes crear todas las variables auxiliares que necesites (ya sea *listas*, *bools*, *integers*, *strings*, etc) que permite que la lógica o secuencia de tu programa funcione correctamente.

Espero haberte ayudado con tu problema, y en caso de tener cualquier otra consulta no dudes en preguntar! 😄

**Comment by sbcorrea** [comment]
Perfecto, muchas gracias!!
