### ISSUE TITLE
Imagenes T05

### ISSUE THREAD

**Issue by JoseValencia125** [IIC2233/Syllabus#514]
¿Se pueden usar fondos, imagenes y sprites sacados de internet o cada uno debe hacer los suyos?

**Comment by stephichau** [comment]
Hola! Sí puedes :)

**Comment by IriSalazar** [comment]
Hola! Recomiendan alguna pagina de donde sacar los sprites? Pueden ser de cualquier tipo? Con esto me refiero a 2D o 3D, pixelados o de buena resolucion, asi como un mario bros de super nintendo respecto a calidad. O da lo mismo?

**Comment by hanavarrete** [comment]
Da lo mismo. Tal vez te sea más fácil que sean top view. Saludos!
