### ISSUE TITLE
Duda sobre toma de decisiones 

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#515]
En la sección 3.1.1 Adultos dice:
> "Los adultos toman todas las decisiones de qué hacer y cuándo hacer algo ... "

Cuando hay un _Día colegio_, ¿los adultos siguen tomando las decisiones a pesar de que no se suban a las atracciones con los niños?
Gracias de antemano!

**Comment by leolivares** [comment]
Hola!
Revisa la issue #516.

**Comment by llloyola** [comment]
Sí la revisé. Entiendo que los adultos no hacen fila con los niños, pero mi duda es si el adulto sigue siendo el encargado de todas las decisiones de todos los niños o si estos podrían mandarse solos e ir a distintas partes cada uno por separado. 
En otras palabras, que el adulto no haga fila ni se suba a los juegos con los niños implica que estos pueden mandarse cada uno por su cuenta (separando el grupo de niños) o si el adulto sigue mandando a todo el grupo de niños?

**Comment by leolivares** [comment]
Modelalo a tu criterio, mientras cumpla con lo pedido!
Saludos!
