### ISSUE TITLE
PyQt4 o 5?

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#515]
¿Da lo mismo si uso pqt4 o pqt5? ¿o aunque no importe mucho es recomendable usar pqt5?

**Comment by iqacevedo** [comment]
Hola!

Debes usar PyQt5, ese es el que estamos usando en el curso.

Saludos !

**Comment by jorgeriesco** [comment]
Ya pero hay designer en pqt5?

**Comment by hanavarrete** [comment]
si hay. Saludos!

**Comment by jorgeriesco** [comment]
Es que en mi compume aparece el designer (.exe) solo en pqt4 y no en el 5.

**Comment by hanavarrete** [comment]
@jorgeriesco  prueba haciendo [esto](https://stackoverflow.com/questions/37987290/pyqt5-designer-and-python-3-5) y me avisas si te funcionó. Saludos!

**Comment by jorgeriesco** [comment]
Ahi si! Gracias

**Comment by acrojas2** [comment]
Hola! Desde la T03 que me aparece este problema con PyQt5 si uso Python 3.5x.
<img width="1148" alt="captura de pantalla 2017-05-24 a las 12 17 36 a m" src="https://cloud.githubusercontent.com/assets/26121354/26386750/9e881fac-4016-11e7-8aea-f89321b8e132.png">
Si lo cambio a 3.6 no hay problemas ¿hay alguna posibilidad de hacer la tarea en Python 3.6x ? 
Saludos!

**Comment by acrojas2** [comment]
Edit: Ya no me funciona con ninguno de los dos! AYUDAAA!!

**Comment by hanavarrete** [comment]
Probaste reiniciando el router? (hint: no lo hagas)
Tienes windows? puedes decirme de cuantos bits es? Y también que versión de python tienes instalada (si es que tienes la correspondiente a tu sistema operativo o no)

**Comment by DiegoAndai** [comment]
@acrojas2 cómo instalaste pyqt? probaste instalarlo de nuevo desde cero?

**Comment by acrojas2** [comment]
@DiegoAndai lo instalé con pip! :( 
@hanavarrete tengo mac. :(

**Comment by sebacruzd** [comment]
@acrojas2 probaste lo que dijo @stephichau en #516?

**Comment by akaminetzkyp** [comment]
@acrojas2 Qt también está para Mac. Búscalo [aquí](https://www.qt.io/download/)!

**Comment by acrojas2** [comment]
@sebacruzd Si, probé todo lo que han dicho por las issues respecto a este tema :( .

**Comment by sebacruzd** [comment]
Una sugerencia, mientras se soluciona este problema intenta avanzar en el las partes de la tarea que no necesiten la interfaz directamente. (No tengo mac, no puedo probar desde mi pc)

Tienes PyQt4 instalado también? Esto podría generar el error que te sale. A mi me pasó y lo tuve que desinstalar.
Otra cosa, intenta con:
```
pip uninstall pyqt5
pip install --upgrade sip
pip install pyqt5```

**Comment by acrojas2** [comment]
Hola!
@andresfdezc solucionó mis problemas hoy! Muchas gracias a todos :)
