### ISSUE TITLE
Re-corrección T01

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2233/syllabus#515]
Hola tengo una duda, la verdad es que es algo raro, en la corrección de mi tarea, dice que el código se cae en cierto momento y que por eso no se pueden corregir algunas partes de la tarea, pero acabo de probarlo en esa parte muchas veces y no se me cae, y por el error que se me muestra en la corrección es raro porque según lo que leo y escribí no debiese dar ese error, entonces, que hago, si en la re-corrección no quiero modificar ninguna linea ?.

De antemano muchas gracias.

**Comment by lily416** [comment]
Puedes mandar a recorregir sin cambiar líneas e indicando que a ti no se te cae en en las situaciones dichas.
 
Igual es bueno que antes de mandar a recorregir: clones tu repositorio en otra carpeta y le agregues los archivos que debían ignorar, ya que así es como corrigen los ayudantes y puede ser que se repitan los errores que te indican.
 
Saludos 👋🤓

**Comment by DiegoPibe** [comment]
Oka, muchas gracias.
