### ISSUE TITLE
Combinar DES con simulacion sincrona

### ISSUE THREAD

**Issue by MrEarle** [IIC2233/Syllabus#515]
Está permitido simular el semestre de manera síncrona (donde un tick seria un dia), y los días con DES?

Me explico, sería simular TODOS los días del semestre (ya que en todos los días puede ocurrir algo, incluso en los fines de semana), pero cada dia simularlo (independientemente) con DES.

**Comment by Hernan4444** [comment]
@MrEarle no está permitido, esta tarea busca evaluar completamente DES en cada aspecto. Incluso en los días que no pasará nada.

Saludos ✌️
