### ISSUE TITLE
Sobre Autoevaluaciones Formativas

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#515]
Hola, quería saber como ponderan las autoevaluaciones formativas en la nota final del curso. Y si uno responde una después del plazo de Canvas ya no cuenta? (porque sigue habilitada la opción de responder).

**Comment by aaossa** [comment]
Hola @Gustav2000 ✨ , tu pregunta tiene dos partes así que responderé cada una por separado:

#### Ponderación de los controles de auto-evaluación

Cada control se considera como logrado (0.1) o no logrado (0) dependiendo de si se obtiene un 80% o más del puntaje del control. El puntaje de los controles se suma y se junta con el puntaje obtenido de las Actividades Formativas según la siguiente fórmula tomada del programa (A son las Actividades Formativas y B los controles):

![imagen](https://user-images.githubusercontent.com/10425834/93006862-ea3b9080-f537-11ea-94a1-2486034f3bc5.png)

Esta fórmula aparece en el programa y lo que manda es lo que dice ahí (por si algo que expliqué se entiende mal). Para calcular la nota de actividades, la nota AF se coloca junto a cada una de las notas de actividades sumativas (AS1, AS2, AS3 y AS4), y se elimina la peor. Esto significa que **la nota AF puede reemplazar tu peor actividad sumativa** (solo si te conviene).

#### Responder el control fuera del plazo

Dado que la idea de los controles es ser un apoyo para su estudio de los contenidos, deberían mantenerse abiertos para responderlos en cualquier momento. Por otra parte, la idea de asignarles un puntaje que vaya hacia la nota AF es incentivar el estudio semanal (para que lleguen con los contenidos ya estudiados a la actividad en clase), por lo que este incentivo no se debería aplicar si no se realiza el control antes de la clase. Así que si respondes el control fuera del plazo no tiene puntaje, pero sí es una buena manera de complementar tu estudio 🤓 

---

Si algo no queda claro pregunta acá mismo no más 👌. Sé que es complicado entender cómo se agrega todo, pero es mejor salir de la duda al tiro, así que muy bien por preguntar ✨

**Comment by Gustav2000** [comment]
Yaa, gracias!!!
