### ISSUE TITLE
Duda imagenes de cuatro canales

### ISSUE THREAD

**Issue by Ed0ss** [IIC2233/syllabus#515]
Hola, en la distribución de puntaje aparece que se debe poder manejar con imagenes de tres y cuatro canales, pero en el pdf de png solamente aparece cómo formar imágenes con tres canales. Mi duda es si es que independiente de que me llegue una imagen de tres o cuatro canales debo generar un png de tres canales, o debo generar un png según corresponda, ya que traté de generar una imagen de cuatro seteando el color en 6 y no me funciona.

Saludos!

**Comment by marioreinike** [comment]
Hola @Ed0ss !
Efectivamente, lo que importa es que tu programa sea capaz de trabajar con matrices RGB de 3 o 4 canales, pero no se pide que generes png de ambos tipos. Por lo que queda a tu critero si escribes pngs de los dos tipos o sólo de uno. Lo importante es que puedas guardar las imágenes con el filtro aplicado y se puedan visualizar. Espero que te sirva.
Saludos!

**Comment by benjaurr** [comment]
Eso significa que para imagenes con 4 canales, se podría omitir el canal de opacidad y tratarlo como una matriz de 3 canales?

**Comment by marioreinike** [comment]
Hola! Si, puedes hacer eso.
