### ISSUE TITLE
duda test cargar_datos pizza_mas_vendida_del_dia

### ISSUE THREAD

**Issue by eldanilop** [IIC2233/Syllabus#515]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Al correr el codigo de esta definicion en correctitud me da bien, no obstante en carga de datos me dice 'Pedido' object has no attribute 'id_pedido' lo que no comprendo ya que me ha funcionado Pedido en otras definiciones y no comprendo que esta mal, como podria corregir esto?

**Comment by AlonsoPlaza** [comment]
Hola, puedes subir el código a tu repositorio para poder revisarlo?

**Comment by eldanilop** [comment]
Ya logre resolver mi error, gracias igual!

**Comment by eldanilop** [comment]
Hola, perdon no entendí el correo.
Es por lo que mencione de la recorreccion de ayer?
Saludos

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Ale M. D. ***@***.***>
Enviado: Wednesday, November 6, 2024 10:24:01 AM
Para: IIC2233/Syllabus ***@***.***>
Cc: Daniel Alejandro López Lerner ***@***.***>; Author ***@***.***>
Asunto: Re: [IIC2233/Syllabus] duda test cargar_datos pizza_mas_vendida_del_dia (Issue #515)


Closed #515<https://github.com/IIC2233/Syllabus/issues/515> as completed.
