### ISSUE TITLE
Uso de multiples Threads

### ISSUE THREAD

**Issue by Martinrsts** [IIC2233/syllabus#515]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Si quiero usar concurrencia, puedo usar threading.lock() o no funciona bien con PyQt? intenté con QMutex pero no me sirven las funciones para ver si esta bloqueado o no.

**Comment by Juampisaez** [comment]
Hola @Martinrsts 
Si lo que quieres es implementarlo dentro de un QThread, la verdad es que nunca he visto un ejemplo en que se utilice un threading.lock() con PyQt. Si lo utilizas en una clase distinta a un QThread, puede ser mas probable que te funcione (no estoy seguro, podrias ir probando en ambos casos). Sin embargo, de igual modo como tip, tal vez lo que quieres hacer (me da la sensacion) se puede hacer teniendo un controlador de Threads (no se si me explico bien). Algo que controle la ejecucion de varios Threads.

Si tienes dudas sobre esto ultimo, quedo atento

**Comment by vcrb18** [comment]
Yo tengo dudas sobre esto último. Como controlo varios thread? Es decir, varios QTimer?

**Comment by Juampisaez** [comment]
Hola @vcrb18 
Puede ser un Thread por ejemplo que controle la partida, y dentro de este Thread crees otros Sub-Threads.
Tal como dices, tambien podrias agregarle un QTimer para regular el tiempo de la partida. A lo que quiero llegar es que hay varias formas de implementar esto.

Quedo atento si no se entendio algo.
