### ISSUE TITLE
Nivel de aprobación actual inicial 

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#516]
Hola!
Cuando un usuario elige la opción de mostrar estado de Magizoólgo y DDCriatura, pero éste aun no pasa al día siguiente, por lo tanto no tendría nivel de aprobación. El nivel de aprobación que se debería mostrar es "cero" ?

**Comment by aljara97** [comment]
Hola @Camila-sty!

Esta duda ya fue respondida en la issue #319, recuerda revisar el compilado para asegurarte que tu duda no haya sido resuelta con anterioridad.

Saludos 🧙‍♂️

**Comment by Camila-sty** [comment]
Ok. Si revisé el compilado, y no la encontré. Busqué con el mismo nombre de esta issue.
Gracias :smile:
