### ISSUE TITLE
¿tiempo que demoran los carabineros influyen en tiempo maximo de espera?

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#516]
hola mi duda es que si por ejemplo un carabinero demora 10 min en revisar un puesto de comida, las personas en la fila de igual forma "se aburren" de esperar y se van?

**Comment by iqacevedo** [comment]
Hola,
El enunciado no indica nada explícito respecto a esto, por tanto puedes hacerlo de la manera que más razonable te parezca.

Recuerda dejarlo especificado en tu README.

Saludos
