### ISSUE TITLE
Qtdesigner

### ISSUE THREAD

**Issue by hanavarrete** [IIC2233/Syllabus#516]
#Para esta tarea probablemente quieran usar [Qtdesigner](http://pyqt.sourceforge.net/Docs/PyQt5/designer.html), si no lo encuentran en la carpeta correspondiente a la librería es porque deben instalarlo aparte con PyQt5tools de la siguiente manera:
```
pip install PyQt5-tools
```

Saludos!

**Comment by maxfreymo** [comment]
**No lo encuentro y no me funciona el comando, aparece esto:**
wificlient-10-201-47-205:~ MaxFrey$ pip install PyQt5-tools
-bash: pip: command not found

**Intenté con pip3 y tampoco:**
wificlient-10-201-47-205:~ MaxFrey$ pip3 install PyQt5-tools
Collecting PyQt5-tools
 _Could not find a version that satisfies the requirement PyQt5-tools (from versions: )
No matching distribution found for PyQt5-tools_

Pd: Tengo **Mac**

**Comment by stephichau** [comment]
@maxfreymo puedes buscar "designer" en el buscador y te debería aparecer algo así:
<img width="295" alt="screen shot 2017-05-23 at 12 07 05 pm" src="https://cloud.githubusercontent.com/assets/16126322/26363862/5ca7d80e-3fb0-11e7-82ba-45636dfaa03f.png">

Avísame si no te aparece :)

**Comment by GabrielLyonB** [comment]
Tengo el mismo problema que Max. Aún no lo logro solucionar. Me imprime exactamente lo mismo, y en el buscador no me aparece.

**Comment by egbusch** [comment]
Me sumo al problema de Max y Gabriel, también tengo mac y no me funciona la solución propuesta.

**Comment by stephichau** [comment]
Como bajaron PyQt5 ?

**Comment by GabrielLyonB** [comment]
pip3 install PyQt5

**Comment by egbusch** [comment]
Creo que fue utilizando el comando: pip3 install pyqt5

**Comment by stephichau** [comment]
Bajen [Qt5.x](https://www.qt.io/download-open-source/?hsCtaTracking=f977210e-de67-475f-a32b-65cec207fd03%7Cd62710cd-e1db-46aa-8d4d-2f1c1ffdacea) y ahi debería venir Designer

**Comment by GabrielLyonB** [comment]
wificlient-10-200-6-22:/ Gabriel$ pip3 install Qt5.x
Collecting Qt5.x
  Could not find a version that satisfies the requirement Qt5.x (from versions: )
No matching distribution found for Qt5.x
wificlient-10-200-6-22:/ Gabriel$ 
--- 
Me aparece lo mismo

**Comment by jiaranda** [comment]
Me pasa lo mismo:
> Collecting PyQt5-tools
  Could not find a version that satisfies the requirement PyQt5-tools (from versions: )
No matching distribution found for PyQt5-tools

**Comment by hanavarrete** [comment]
@GabrielLyonB  Se referían a que se bajen Qt5 desde ese link, no con pip. La descarga es un exe. Intenta eso y nos dices como te fue. Saludos

**Comment by jnhasard** [comment]
Me funciona qt designer y puedo abrirlo y usarlo pero no tengo el comando pt

**Comment by sebacruzd** [comment]
pyuic5 no es la única manera de usar archivos .ui.
Si bien con esto lo transformas a código de python, con uic puedes importarlo y usarlo directamente desde tu programa.
Prueba lo que sale [acá](http://nullege.com/codes/search/PyQt5.uic.loadUi)

**Comment by jnhasard** [comment]
Ahí me funcionó gracias!

**Comment by GabrielLyonB** [comment]
Creo que lo logré. Me bajo el Qt Creator, nuevo problema, pero me abre los archivos qt-designer.

**Comment by egbusch** [comment]
Alguien sabe como hacer para que se me abran todas las ventanas del designer juntas en una ? 
Cuando ejecuto el programa se me abre así  y no me aparece la barra derecha (solo me apareció la primera vez que ejecute el programa):
<img width="1280" alt="captura de pantalla 2017-05-25 a la s 10 08 19" src="https://cloud.githubusercontent.com/assets/26125265/26453608/569294c6-4132-11e7-966c-13bb04965668.png">

**Comment by sebacruzd** [comment]
@egbusch no se me carga tu imagen, pero supongo que [esto](https://stackoverflow.com/questions/43322333/pyqt-how-to-load-multiple-ui-files-from-qt-designer) te puede ayudar. Sino también puedes buscar en google algo parecido a "how to load multiple .ui files in the same window pyqt".

Saludos!

**Comment by akaminetzkyp** [comment]
@egbusch, para abrir Designer en una única ventana tienes que ir a "Preferences", y en el menú "Appearance" cambiar "User Interface Mode" a "Docked Window".

<img width="477" alt="screen shot 2017-05-25 at 10 54 33 am" src="https://cloud.githubusercontent.com/assets/11022568/26455650/d689f006-4138-11e7-8f30-803dc69b3709.png">

**Comment by egbusch** [comment]
Gracias !
