### ISSUE TITLE
Funcionamiento del movimiento fluido/animado del personaje en el mapa

### ISSUE THREAD

**Issue by vcrb18** [IIC2233/syllabus#516]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Tengo una duda de como se van a mover los personajes en el mapa. El movimiento de estos es como una "teletransportación" pasando del sprite 1 al 2 y al 3 en cada sentido? Es decir, que por ejemplo se mueva de la posición (0,0) -> (2,0) -> (4,0) -> (4,2) y así, como si fuera una matriz y que el parámetro velocidad fuera en este caso ese 2 que podrían ser los pixeles que se mueve. O debería ser un movimiento fluido y continuo en donde el personaje realmente camina, como "continuo" sin "teletransportarse"?

**Comment by clementevalladares** [comment]
Hola @vcrb18, el movimiento del personaje en cuanto a su posición es correcto como lo planteas. Es decir, si la velocidad de tu personaje es 2, posición deberá cambiar de 2 en 2 pixeles. Efectivamente se estará "teletransportando" , pero mientras el salto no sea demasiado grande el movimiento parecerá fluido.
Con respecto a los sprites, no es necesario que en cada ciclo de movimiento (cada vez que se mueva 2 pixeles) cambie la imagen. Puedes hacer que sea, por ejemplo, cada 2 o 3, para así lograr el movimiento que parezca más fluido para ti.

**Comment by FVivess** [comment]
Hola leyendo la respuesta me surgieron varias dudas acerca del movimiento del personaje. Lo que yo entendí de acuerdo a lo que decía el enunciado, y de las fotos que se mostraban, es que el personaje se mueve dentro de las casillas del mapa. Por ejemplo, si se mueve dos veces hacia arriba (es decir, se presiona dos veces "w"), se movería dos casillas (y no dos pixeles, como aparece aquí). Debido a esto también entiendo que los objetos aparecen exclusivamente en estas casillas, y que la velocidad del personaje era el tiempo en que se demora en recorrer cierta cantidad de casillas, y no cuantos pixeles recorre con un movimiento. 

Si ya hice el código considerando esto, ¿tendría problemas en la parte de "movimiento fluido" del puntaje?

**Comment by clementevalladares** [comment]
Hola @FVivess, si ves en la sección 5.1 del enunciado (página 12) se explica que la velocidad de movimiento indica la cantidad de pixeles que se mueve el personaje al presionar una tecla.

**Comment by FVivess** [comment]
Y con respecto a los objetos, ¿estos no solo aparecen en las casillas?

**Comment by clementevalladares** [comment]
Los objetos pueden aparecer en cualquier parte del tablero. Debes considerar que no colisionen entre ellos y que dejen suficiente espacio para que pueda transitar el jugador.

**Comment by clementevalladares** [comment]
@FVivess aprovecho de agregar que puedes seguir ubicando los objetos en las casillas si así lo deseas, siempre y cuando lo hagan de manera aleatoria y sigan las restricciones. Pero no es necesario que lo hagas así.

**Comment by vcrb18** [comment]
Muchas gracias por la velocidad de respuesta! Leyendo lo que puso el compañero, me surgió otra duda. Si es que el tema fuera movimiento por casillas, el parámetro velocidad personaje tendría que ir de la mano con el tamaño de las casillas del mapa o no? Ya que si la velocidad es 2 por ejemplo y vemos el mapa como una matriz, la velocidad tendría que ser la distancia de pixeles desde el centro de una casilla al centro de la otra casilla, lo que significa que tanto el parámetro velocidad no podría cambiar. Entonces, el movimiento es completamente "libre" por el mapa? Es decir, no va moviéndose como dentro de una matriz?

**Comment by clementevalladares** [comment]
@vcrb18 Efectivamente tu personaje no se mueve dentro de una matriz definida (más que los pixeles en la pantalla). Cuando el parámetro de velocidad es 2, significará que te estás moviendo 2 pixeles en la dirección presionada, por lo que es "libre" por el mapa.
Si el movimiento estuviera planteado como casillas, sería exactamente como dices, el parámetro de velocidad tendría que necesariamente ser igual a la distancia entre una casilla y otra. Sin embargo, en esta tarea no está planteado de esa manera.

**Comment by vcrb18** [comment]
Queda más que claro, muchísimas gracias!

**Comment by vcrb18** [comment]
Creo que esta va a ser mi última duda... perdón, entonces en el mapa de homero, los objetos no tienen que necesariamente aparecer arriba de las baldosas o no? Y homero no tiene que caminar de baldosa en baldosa si no que podría caminar entremedio. Estas dudas me quedaron debido a como se ve el mapa de homero en la ventana de juego presentado en el enunciado.
