### ISSUE TITLE
duda programación funcional

### ISSUE THREAD

**Issue by fgallard** [IIC2233/Syllabus#516]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Pasar un generador a lista rompe con la programación funcional, cierto? pero no entiendo como puedo generar una comparacion en la que quiero ver si un elemento x de un generador está en otro generador y, ya que si hago algo del estilo filter(lambda x: x in generador2, generador1) no me va a funcionar porque el x in generador2 consume ese generador. Por ejemplo en la función pizza_mas_vendida_del_dia, conozco los códigos de pizzas vendidas en esa fecha luego de filtrar uno de los generadores, pero luego para hacer esa comparacion de solo usar los generadores de la otra que tienen esos id se puede hacer de alguna manera que no sea transformandolo en una lista?

**Comment by Gcamposbriceno** [comment]
Hola! Puedes utilizar `product` de **itertools** para juntar la informacion de una pizza con la informacion del pedido en el que se compra dicha pizza. Esto genera muchas combinaciones (hace todas las combinaciones posibles), asi que intenta filtrar tus iteradores antes de combinarlos.
