### ISSUE TITLE
Entrega Readme atrasada

### ISSUE THREAD

**Issue by nfragav** [IIC2233/syllabus#516]
Hola! Quisiera preguntar si existe por la posibilidad de entragr un readme atrasado. En caso contrario, me gustaria saber si existe esta posibilidad solo para ayudar al corrector y no optar por el desdescuento.

**Comment by entamburini** [comment]
Hola @nfragav, 

Puedes subirlo, el ayudante lo verá si es que no encuentra nada que fuera recolectado :). Pero no tendrás desdescuentos y la penalización por no entregar README seguirá existiendo :c 

Sólo servirá para ayudar a tu corrector a hacer un mejor trabajo con tu tarea 😄
