### ISSUE TITLE
Mostrar deportistas

### ISSUE THREAD

**Issue by margavicunas** [IIC2233/syllabus#516]
Hola!
En el enunciado se habla de "mostrar deportistas" ya sea para que el usuario elija cuál fichar, entrenar, sanar, mandar a la competencia, etc. ¿Basta con mostrar el nombre del deportista o hay que incluir los atributos relevantes a su elección? (ej. para mandar a competencia mostrar su nombre, habilidades y si está lesionado o no)
Me imagino que debe quedar a criterio pero ¿mientras más info en la consola mejor o realmente da lo mismo? 

Gracias :)

**Comment by jitorcas** [comment]
Hola! @margavicunas 

Efectivamente queda a tu criterio agregar más información de la solicitada. Como ayudante te agradecería si agregas datos **relevantes** dependiendo de la acción que se esté seleccionando. 
Solo para recordar, no tienes que mostrar todos los deportistas para cada acción. Por ejemplo, al elegir `Sanar` solo debería mostrar los deportistas lesionados. 

Mucho éxito! 🥇

**Comment by margavicunas** [comment]
Sisi obvio, mostrar los deportistas según el caso :) Yaa bacán, mil gracias!
