### ISSUE TITLE
Error de instalación PyQt con múltiples versiones de Python

### ISSUE THREAD

**Issue by pzuritas** [IIC2233/syllabus#516]
¡Hola!

Por razones de la vida tengo que trabajar esta tarea en Ubuntu 19, que viene con Python 3.7, que he estado usando hasta ahora. Instalé Python 3.6 como `python3.6` pero al ejectuar

`sudo apt-get install python3.6-pyqt5`

se arrojan los errores

`E: Unable to locate package python3.6-pyqt5`
`E: Couldn't find any package by glob 'python3.6-pyqt5'`
`E: Couldn't find any package by regex 'python3.6-pyqt5'`.

`pip3.6 install pyqt5` tampoco funciona. ¿Hay alguna otra forma de instalar PyQt en esa versión específica de Python?

**Comment by bimartinez** [comment]
Hola @pzuritas 

1.- No le temas a Ubuntu :heart: 
2.- Intentaste utilizando `pip3 install pyqt5`

**Comment by pzuritas** [comment]
`pip3 install pyqt5` arroja el error

`Could not install packages due to an EnvironmentError: [Errno 13] Permission denied:`
`'/usr/local/lib/python3.6/site-packages/PyQt5_sip-4.19.17.dist-info'`
`Consider using the ``--user`` option or check the permissions.`

PD1: ¡Gracias por la respuesta rápida!
PD2: Ubuntu es bacán.

**Comment by bimartinez** [comment]
Ya, intenta entonces con lo siguiente `pip3 install --user pyqt5`. Avísame como te va con eso :smile:

**Comment by pzuritas** [comment]
¡Era así de fácil! Muchas muchas gracias :heart: 
De curiosidad, ¿qué hace `--user`?

**Comment by bimartinez** [comment]
De nada! :smile:

Lo que hace el *flag* `--user` es decirle a `pip` que instale la librería solo para tu usuario (otros usuarios en tu computador no tendrán acceso a esta), para lo cual no necesitas permisos de administrador. Por defecto `pip` instala las librerías en el directorio raíz de tu SO, lo cual requiere acceso de administrador (si deseas instalar una librería de manera global, puedes intentarlo a través de `sudo pip3 install ...`). Si quieres mas información podrías consultar la [siguiente entrada](https://stackoverflow.com/questions/42988977/what-is-the-purpose-pip-install-user) de *StackOverFlow*

Saludos! :smile:

**Comment by pzuritas** [comment]
Bacán, gracias de nuevo!
