### ISSUE TITLE
Actualizar Readme

### ISSUE THREAD

**Issue by Zapararte** [IIC2233/syllabus#517]
Hola! Si es que ya envié mi Readme (a la hora) y ahora me di cuenta que podía agregarle un dato útil para la corrección, subir el mismo Readme con 3 líneas más (aprox)  qué significa en términos de:
-Dscto por entrega atrasada.
-Tener la posibilidad de optar al des-decuento.

Gracias de antemano :)

**Comment by DCCollao** [comment]
Hola! Puedes actualizar el ``readme.md`` de tu repositorio, y es **posible** que el ayudante que te corrija lo vea desde allí, y se le haga más fácil la corrección.
Sin embargo, para efectos del des-descuento, el ``readme.md`` válido es el que entregaste en el commit correspondiente a la deadline de entrega de ``readme.md``

Saludos

**Comment by Zapararte** [comment]
Gracias!
