### ISSUE TITLE
Menú acciones

### ISSUE THREAD

**Issue by fmartint** [IIC2233/syllabus#517]
Hola! Tengo una duda sobre que hacer después de que el usuario haga una acción, ej comprar comida, debo volver al menú DCC (Que es donde compro comida) o al menu de acciones?
En el enunciado dice:
"Una vez resuelta la acción o menu ́, se vuelve a mostrar este menu ́ (de acciones)."
Esto es solo para las acciones de este menu o es para todos los menus?
Saludos

**Comment by JosefaPaz** [comment]
Hola @fmartint !

Por ejemplo, si ya compraste alimento en el menú del DCC, deberás volver al menú de acciones, ya que como tú bien dices "ya estaría resuelto el menú", es decir, ya cumplió su propósito el que hayas entrado a dicho menú (comprar alimento). Lo mismo para las otras acciones que tiene el menú DCC

Éxito 😸
