### ISSUE TITLE
Tiempo de duracion del día en la simulacion

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#517]
no me queda claro si hay que simular solo desde las 11:00 hasta las 15:00 (en el enunciado sale "decides simular el horario de almuerzo durante un semestre academico") o bien todo el dia (00:00-23:59) (en el enunciado sale por ejemplo "Todos los miembros de la universidad pueden comprar snacks durante el dia")

**Comment by estebanmb** [comment]
@iqacevedo Entonces quienes  a las 15:00 quedaron en una cola,  ¿se consideran que no almorzaron ese día ?
