### ISSUE TITLE
Uso de @abstractmethod en el setter de una property 

### ISSUE THREAD

**Issue by nicolecll** [IIC2233/syllabus#517]
Hola !  Deseo crear una clase abstracta, pero esta tienes varias properties que van a variar en sus clases hijas,  si cada property va a tener su propio getter y setter,¿ en la clase abstracta debo definir tanto el getter como el setter como metodos abstractos?, no me queda muy claro como trabajar con ambas cosas juntas.

**Comment by jitorcas** [comment]
Hola @nicolecll 

Efectivamente debes definirlos como métodos abstractos, donde dichos componentes son los que deben actualizarse en la subclase. Un ejemplo que extraje de la [documentación ](https://docs.python.org/3/library/abc.html#abc.abstractproperty)es el siguiente:

```python
class A(ABC):

    @property
    def x(self):
        ...
    
    @x.setter
    @abstractmethod
    def x(self, val):
        ...

class D(C):
    @C.x.setter
    def x(self, val):
        ...
```

Éxito en la tarea! 🥇

**Comment by nicolecll** [comment]
Ok! Muchas gracias!
