### ISSUE TITLE
Posición absoluta/global de objeto

### ISSUE THREAD

**Issue by VichoAburto** [IIC2233/syllabus#517]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Una consulta, existe la forma de saber la posición absoluta/global en la ventana de algún objeto que esté dentro de un layout, y también dentro de otro layout?

En el fondo, en una ventana, tengo un layout vertical que adentro tiene contenido 2 layouts horizontales, y me gustaría saber cuál es la posición global de algún QLabel que tenga dentro del segundo layout horizontal. Existe alguna función? Porque geometry() y x() ó y() solo me dan las coordinadas del objeto respecto al layout de más adentro.

**Comment by catalina-arcila** [comment]
Hola @VichoAburto, buscando en la documentación *Qt* no encontré lo que preguntas, pero lo que se me ocurre es que podrías crear una función que mediante el tamaño del *layout* y la coordenada del *Qlabel* encontrar la coordenada absoluta del *Qlabel*

**Comment by VichoAburto** [comment]
Yaa! Graciass
