### ISSUE TITLE
Constantes

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2233/Syllabus#517]
En la tarea 5, se mencionan ciertos parámetros que se consideran constantes y que deben ser guardados en un archivo externo como, vida máxima de los campeones, vida de los súbditos, cantidad de daño por habilidad y velocidades de ataque.  
¿Qué se busca con esto?  Ya que estaba pensando en la posibilidad de que ciertos argumentos estén fijos dentro de las clases. Como por ejemplo: 
```python
class Renekton:
   def __init__(self):
        self.resistencia_magica = 20 
```
en vez de 
```python
class Renekton:
   def __init__(self, resistencia_magica):
        self.resistencia_magica =   resistencia_magica
```
y que yo le de el valor al momento de instanciarlo.

**Comment by stephichau** [comment]
La idea es poder cambiar los valores fácilmente y no tener que buscarlo dentro del código. Esto ayuda tanto para debuggear tu código como para los correctores. 

Saludos!
