### ISSUE TITLE
Problema pyqtSignal desde backend a frontend

### ISSUE THREAD

**Issue by Matoclip** [IIC2233/Syllabus#517]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/291)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/290)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, estoy teniendo problemas con el envío de señales desde el backend al frontend. Cuando un cliente se conecta al servidor, este le asigna un nombre y se lo manda al backend. El backend guarda este nombre como variable, y hasta ahí todo bien, pero cuando trato de emitir una señal conteniendo el nombre al frontend para actualizar la interfaz, nada se envía; sin embargo no tengo errores ni nada. Por otro lado las señales que comienzan desde el frontend (al presionar bot
\ones) funcionan perfecto. Me imagino que la señal se esta emitiendo antes de conectarse a un slot, porque cuando emito la señal utilizando un QTimer.singleshot() sí funciona, sin embargo no puedo utilizar esto dentro de un Thread por lo que no me es muy útil. Que puedo hacer? Muchísimas gracias de antemano

**Comment by MIrarrazaval** [comment]
Hola! Clone tu repo y no encuentro el error que describes, ¿ya esta arreglado?

**Comment by Matoclip** [comment]
Hola! Si, cambie de threading a QThread y se arreglo jaja, muchas gracias!
________________________________
De: Manuel Irarrázaval ***@***.***>
Enviado: jueves, 22 de junio de 2023 18:02
Para: IIC2233/Syllabus ***@***.***>
Cc: Matthias Aldrik Gerlach Krause ***@***.***>; Author ***@***.***>
Asunto: Re: [IIC2233/Syllabus] Problema pyqtSignal desde backend a frontend (Issue #517)


Hola! Clone tu repo y no encuentro el error que describes, ¿ya esta arreglado?
