### ISSUE TITLE
Calculo moral inicial

### ISSUE THREAD

**Issue by cperez20** [IIC2233/syllabus#518]
Hola, una consulta en el enunciado nos dice que la moral debe ser calculada como el promedio de los deportistas de la delegacion pero en el archivo .csv nos viene ya con una moral definida para cada delegacion, entonces a que le hacemos caso?

**Comment by jitorcas** [comment]
Hola! @cperez20 

En la issue #375 se responde a tu pregunta. 
Éxito en la tarea!
