### ISSUE TITLE
Documentacion PyQt5

### ISSUE THREAD

**Issue by andreslyon** [IIC2233/Syllabus#518]
Hola, buscando en internet sobre PyQt5, me he topado solamente con una documentacion que parece ser la oficial [http://pyqt.sourceforge.net/Docs/PyQt5/](url) , pero al seleccionar cualquier item, sale c++ documentation, y nada de python. donde puedo encontrar info sobre PyQt5, para python? gracias

**Comment by iqacevedo** [comment]
Hola!

Me parece que es la única documentación oficial que hay. Sin embargo, te puede servir leerlo de todas formas, ya que puedes aprender que hacen los métodos y clases, luego en python solo deberías cambiar la sintaxis de como usar lo que hayas aprendido. Por lo menos así lo hice yo cuando necesitaba encontrar algo en especifico de PyQt.

Saludos !

**Comment by hanavarrete** [comment]
Como dice ignacio lo mejor es usar esa documentación, el uso de las funciones es muy parecido. De todas maneras tal vez te pueda servir a modo de introducción [esto](http://zetcode.com/gui/pyqt5/). Saludos!

**Comment by andreslyon** [comment]
Graciasss

**Comment by eiherrera** [comment]
Aca va un [link](http://pyqt.sourceforge.net/Docs/PyQt4/classes.html]) con la documentación de PyQt4, que no tiene muchas diferencias con PyQt5, explicando que hace cada clase y que métodos poseen. Suerte!

**Comment by DiegoAndai** [comment]
Como recurso aparte, está la documentación original de Qt:

http://doc.qt.io/qt-5/reference-overview.html

PyQt5 es una librería de python que se construye sobre Qt5, por lo tanto la mayoría de las clases, funciones y atributos son análogos entre estos (no puedo asegurar que todos pero en general los que tendrán que ocupar para las tareas si). Ojalá les sea útil.

**Comment by Dunkan1** [comment]
quizas les sirva.
https://github.com/Programmica/pyqt5-tutorial
tiene explicaciones de algunas funciones
