### ISSUE TITLE
Penalización por uso de sets y diccionarios

### ISSUE THREAD

**Issue by vitoco11** [IIC2233/Syllabus#518]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Para ciertas funciones encontré que era necesario ocupar estructuras de datos como sets (para buscar si un elemento como un nombre de pizza esta dentro de el dentro de la función filter) o diccionarios (para asignar precios o ganancias y tener acceso rápido a ellas). Esto claro con trabajo previo, filtrando los generadores para disminuir su información y después aplicarles sets o dicts, esto resultó ser mucho más eficiente que el uso único de generadores (o a veces solo se me hizo posible de esta manera). **Existen penalizaciones por el simple uso de estas estructuras de datos o solo es requisito que la función pase por el test de carga de datos.**

**Comment by AlonsoPlaza** [comment]
Hola, te recomiendo revisar la issue #468 👀
