### ISSUE TITLE
AttributeError: module 'nombre' has no attribute 'clase'

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#518]
Tengo un archivo que contiene una gran clase, y tres que heredan de ella. La clase es abstracta y hereda de abc.ABC. Tengo otro archivo que importa el archivo como modulo, y utiliza las tres clases. Al intentar usarlas, me da el error del titulo.

**Comment by entamburini** [comment]
Hola @sofiuni,

Viendo tu código, tienes un typo, `TartaDeMeleza` != `TartaDeMelaza` :wink:

**Comment by sofiuni** [comment]
entiendo, ahora me da otro error, "UnboundLocalError: local variable 'alimento' referenced before assignment", pero la variable la defino en un if al cual deberia estar entrando bien? lo he revisado, y no comprendo donde esta el error. me puede guiar?

**Comment by entamburini** [comment]
En general, esos errores se pueden rastrear imprimiendo en las condicionales que no se están dando, para así encontrar qué es lo que provoca el error :).

La ventaja es que ya sabes cuál es el if al que no está entrando así que puedes partir desde ahi, imprimiendo las condiciones arriba para ver cuál es la que no se está cumpliendo y así encontrar e error :D
