### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by matyjjn14** [IIC2233/syllabus#518]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, tengo un problema con la creación de una clase puesto que en la linea donde la nombro ( es decir class NombreClase():) me arroja el error UnicodeEncodeError: 'ascii' codec can't encode character '\xf1' in position 2: ordinal not in range(128), la verdad no sé porque está pasando y cuando borro esta clase este error vuelve a aparecer en otra clase que antes si funcionaba. Espero me puedan ayudar, de antemano gracias

**Comment by valerianazal** [comment]
Hola @matyjjn14 ! Ese error significa que hay una "ñ" en el nombre de tu clase, la que no existe en el código ASCII. Si la cambias a una "n" se debería solucionar. Además, si quieres saber más sobre el código ASCII puedes visitar [este link](https://www.google.cl/amp/s/techterms.com/amp/definition/ascii). 
Si no se soluciona puedes poner poner un comentario en esta misma issue 😄

**Comment by matyjjn14** [comment]
perfecto, ahora sí! gracias!
