### ISSUE TITLE
ayuda error chat

### ISSUE THREAD

**Issue by jfpena1** [IIC2233/syllabus#518]
Hola tengo un problema con actualizar el Qlabel del chat. Al recibir un mensaje, el contenido de este (en formato string) se guarda bien en el texto del Qlabel al hacer .setText(contenido) (esto se que es asi porque al hacer label.text() veo que guardo lo requerido), sin embargo este nuevo contenido no se muestra en pantalla. 

Es decir, el mensaje llega de manera correcta al metodo de la interfaz del chat para que lo actualize pero el setText() no me esta funcionando.

Subi mi codigo actualizado para esta issue a github por si me pueden ayudar.  El chat se encuentra en el modulo  Ventana_perfil.py , dentro de la carpeta cliente, en particular el metodo actualizar esta en la linea 237 de este modulo. Muchisimas gracias!!!!!

**Comment by KnowYourselves** [comment]
Creo saber que te pasa, Dame unos minutos y lo reviso!

**Comment by jfpena1** [comment]
muchisimas gracias!!! te pasaste
