### ISSUE TITLE
Problema al usar Guy/PyQt

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#518]
En las dos tareas que han sido con interfaces en que usamos gui y PyQt, he tenido el problema de que en algunas ejecuciones del programa no se abre la interfaz y me empieza a tirar la frase "El núcleo dejó de funcionar, reiniciándolo". Esto no me impide programar ni usar interfaces ya que como dije es sólo en algunas ejecuciones del programa, sin embargo, generalmente es ejecución por medio por lo que pierdo mucho tiempo.
En la foto que adjunto sólo apareció dos veces la frase, luego  se reinicia y se vuelve al input 1, pero la mayoría de las veces esa frase aparece varias veces y para no esperar más simplemente cierro la terminal para que se abra otra nueva. Con una terminal recién abierta no ocurre el problema, la mayoría de las veces ocurre en la segunda ejecución.
No tengo idea si el problema tendrá que ver con Gui o PyQt.

![problema](https://user-images.githubusercontent.com/30670535/31579571-6b98c974-b10f-11e7-917f-a070f7f5dde5.png)

**Comment by mjgutierrez1** [comment]
El problema es con PyQt y al usar Idle no se produce este problema

**Comment by vijuarez** [comment]
Hola! Hasta donde tengo entendido, ese es un bug de Spyder. Te recomiendo o cambiar de IDE o correr los códigos en una consola aparte, con la tecla F6.

Saludos, nos cuentas si te ayuda.

**Comment by mjgutierrez1** [comment]
No entendí eso de la tecla F6

**Comment by vijuarez** [comment]
Hola! Me refiero a que literalmente presiones la tecla `F6` cuando estes usando Spyder, de esta forma el programa se ejecutara en una nueva consola y no en la de Spyder, que es donde ocurre el problema. No tengo Spyder para probarlo yo mismo, pero tengo entendido que esta es la única solución fuera de cambiar de IDE.

Saludos, nos cuentas si funcionó.

**Comment by mjgutierrez1** [comment]
No funciona, ese comando ejecuta el código de nuevo de la misma manera que con F6 (creo que la diferencia es que ejecuta el último programa que se corrió). Voy a tener que cambiar de IDE yo creo.

**Comment by iqacevedo** [comment]
@mjgutierrez1 lo que puedes hacer también es probar los códigos que involucren PyQt directamente en la consola, basta con que escribas en la consola del SO que estés usando `py ruta/del/archivo/archivo.py` O  `python ruta/del/archivo/archivo.py`.

Saludos !
