### ISSUE TITLE
No se ven imágenes en los contenidos semana 11

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#519]
Tanto en 1-Interfaces-Graficas.ipynb como en 2-QT-Designer.ipynb no se ven las imágenes.

**Comment by mjgutierrez1** [comment]
También en el material extra, en la parte del mouse no están  'images/colors/azul.png' ni 'images/colors/verde.png', por lo que no es posible probar el código.

**Comment by andresfdezc** [comment]
Acabo de arreglarlos. Gracias por avisarnos!
