### ISSUE TITLE
Duda sobre QThreads 

### ISSUE THREAD

**Issue by TomasFouyet** [IIC2233/syllabus#519]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, en la tarea tenemos que crear un personaje que persiga a nuestro personaje (el policia). Mi duda es la siguiente, mi policia puede ser un Qthread, pero todo el resto de mi codigo no serlo, es decir, el codigo principal funcionaria como un Thread al tener otro QThread?

**Comment by clementevalladares** [comment]
Hola @TomasFouyet, efectivamente el enemigo lo puedes manejar desde un QThread distinto al de tu código principal. Siempre y cuando siga cumpliendo las restricciones de TIEMPO_DELAY_{DIFICULTAD}.  Te recomendaría la utilización de señales para lograr esto.

**Comment by TomasFouyet** [comment]
perfecto, no me quedo muy claro, mi ventana principal de juego, la tengo que definir tambien como un thread? o solamente el policia lo tengo que definir como un thread

**Comment by clementevalladares** [comment]
Recuerda que el backend de tu programa debe estar separado del frontend. No es necesario que el código que maneja todos los eventos del backend sea un QThread, pero te recomiendo que lo plantees de esa manera para poder controlar todos los eventos que ocurren en una partida de la mejor manera posible. Te facilitará mucho más la implementación de la función de pausar el juego también.
