### ISSUE TITLE
Referencias circulares Tarea 4

### ISSUE THREAD

**Issue by gtquiroga** [IIC2233/Syllabus#519]
No me queda muy claro el punto 11 de enunciado cuando cuando se dice modelar la realidad. Si yo tengo una clase Simulacion y otra Persona, en mi clase Simulacion puede tener instancias de Persona y modificarlas pero en la clase Persona no puedo tener una instancia de Simulacion?

**Comment by cilopez** [comment]
¿Crees que sea real que una persona tenga la informacion de todo el universo ?

**Comment by mora4** [comment]
¿Cuando hablan de tener a una instancia se refiere en sus atributos? Por ejemplo, si la clase A contiene instancias de la clase B en sus atributos y la clase B recibe instancias de la clase A sólo para un método, ¿es esto circular?
