### ISSUE TITLE
¿Son obligatorias las clases que heredan de "Deporte"?

### ISSUE THREAD

**Issue by ExRage2000** [IIC2233/syllabus#519]
Hola, quería saber si es obligatorio que haga clases hijas para la clase Deporte, pues el puntaje de cada deporte se calcula de manera similar y las variables que no se ocupan se pueden dejar con ponderador 0. Además, el riesgo y necesidad de implementos también se puede definir en los parámetros, así que no veo muchas ventajas en crear las clases hijas

Estaba planeando en que los 4 deportes sean instancias de la clase deporte en vez de clases que hereden

(Ya ví la issue #407 porsiacaso, pero esa menciona la necesidad de la clase madre, no hijas)

**Comment by mmunozmendez** [comment]
Hola, 
Realizar herencias es parte de lo que se busca evaluar es esta tarea, por lo que debes hacer las clases hijas de Deportes. 
Existen muchas formas de lograr los mismo objetivos en programación, por eso es lógico que hayas encontrado otra solución, pero en la evaluación esta no tendrá el puntaje por modelación. 
En cuanto a la issue anterior, que deporte sea clase madre, implica que tenga hijas 😉.

Éxito!

**Comment by ExRage2000** [comment]
¿Incluso si ya estoy utilizando herencias en otra parte de la tarea?

**Comment by mmunozmendez** [comment]
Hola, finalmente puedes modelar como tu quieras las clases, pero tiene que tener sentido.

Éxito!
