### ISSUE TITLE
¿Puede un método abstracto retornar valores?

### ISSUE THREAD

**Issue by smoralesw** [IIC2233/syllabus#519]
Puedo hacer que una clase abstracta retorne un valor, de manera de poner en la clase hija algo del tipo:
if super().metodo() == valor: 
    (...)

Saludos

**Comment by fdoflorenzano** [comment]
Hola @smoralesw,

Esto pudiste haberlo probado por tu cuenta en vez de esperar una respuesta aquí 😅, pero todas formas te respondo, sí, es posible.

Saludos.
