### ISSUE TITLE
Tarea 3 duda sobre test cases 

### ISSUE THREAD

**Issue by mrtti** [IIC2233/Syllabus#519]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [x ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Estoy un poco perdida respecto a los test que debemos usar para la tarea, ya que como hay dos de cada uno no entiendo si es porque uno está malo y otro bueno, o porque es necesario que pase ambos test cases de cada uno. Me podrían explicar por favor, perdón por las molestias, es que ya busqué en las otras issues y en las actualizaciones de las tareas, pero no me quedó del todo claro.

Desde ya, muchas gracias!

**Comment by AlonsoPlaza** [comment]
Hola, si te refieres a los test de carga y de correctitud, debes correr ambos ya que prueban distintos aspectos de la función. Si queres saber especificamente que hace cada uno puedes encontrar una descripción en el enunciado item 4. Tests.
