### ISSUE TITLE
como saber que botón fue apretado

### ISSUE THREAD

**Issue by kmhaller** [IIC2233/syllabus#519]
Hola, quería saber cómo puedo identificar el botón que fue apretado si es que creo los botones con un for. Esto sería para las salas creadas. Intenté hacer una lista con los botones y hacer  que para cada botón en la lista se cree un boton.connect() pero esto no funciona. ¿Cómo se puede hacer? Además, ¿Existe un máximo de salas que se puedan crear?

**Comment by bimartinez** [comment]
Hola @kmhaller!

Lo que se me ocurre que podrías hacer es obtener el texto de cada botón para identificarlos. Y en vez de asignarlos a una variable armar alguna estructura donde guardes la instancia completa. Te dejo [esta entrada] en *StackOverFlow* para que le des una mirada. Respecto a lo segundo dame un rato y lo averiguo. 

Saludos! :smile:

**Comment by marioreinike** [comment]
Hola! hay un método de `QWidget` que se llama `sender()`. Este método te entrega la instancia del botón que fue apretado. Es decir:
```
class MiVentana(QWidget):
...
    def funcion(self):
        boton = self.sender()
...
```
Si conectas el boton a esa función, cuando lo clickees recibirás la instancia del botón con ese método. Espero que te haya servido.
