### ISSUE TITLE
Edición de archivos .csv en la Tarea0

### ISSUE THREAD

**Issue by cristobalba** [IIC2233/Syllabus#52]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, quería saber si al momento de entregar la tarea los archivos .csv deben estar intactos, es decir, con la misma información que venían cuando se entrego el enunciado. **O si es posible entregarlos modificados**, por ejemplo, si el archivo de usuarios venía con 10 usuarios y yo agregue un nuevo usuario para probar mi codigo

Gracias, salu2

**Comment by Emiliax16** [comment]
Hola @cristobalba ! en cada tarea no se deberían subir los archivos entregados (como lo son los csv). En esta tarea, no se hará descuento por si los subes, pero te recomiendo utilizar gitignore e incluir los csv ahí, así lo manejas bien para las siguientes tareas donde sí será evaluado!  😄

**Comment by cristobalba** [comment]
Valee gracias!

**Comment by J0SEF4** [comment]
No es completamente necesario usar maxsplit, cierto? Solo lo dicen como opción a resolver las comas que hay en la descripción en el caso de publicaciones, cierto?

**Comment by J0SEF4** [comment]
El id del archivo csv de publicaciones. Cuando elimino una publicación, el id debe volver a ordenarse o lo puedo dejar que ese id desapareció?
