### ISSUE TITLE
duda conteo puntajes

### ISSUE THREAD

**Issue by aydenbraber500** [IIC2233/syllabus#52]
Hola 
mi duda es que si al momento de un jugador caer en un lego, esta casilla que contiene el lego es tomada en cuenta como casilla descubierta a la hora del calculo del puntaje final

**Comment by etoteiza** [comment]
El enunciado dice puntaje = legos_tablero*celdas_descubiertas*POND_PUNT. donde legos_tablero es el la cantidad de legos que tiene el tablero, celdas_descubiertas es la cantidad de celdas ingresadas por el jugador que no tiene legos. asi que supongo que no

**Comment by DCCollao** [comment]
Hola!

Tal como menciona @etoteiza , el factor que considera las celdas descubiertas por el usuario solamente toma en cuenta aquellas que **no** contienen legos.

Éxito con la tarea!

**Comment by aydenbraber500** [comment]
aaah yaya
Muchas gracias @etoteiza @DCCollao
