### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by egarnham1** [IIC2233/syllabus#52]
en qué tipo de archivo debe ser la explicación de la modelación? entiendo que markdown es un lenguaje, no un tipo de archivo.

**Comment by gatochico** [comment]
Hola! 

Cuando te pedimos que entregues tu explicación de la modelación en archivo Markdown (que tienes razón, es un **lenguaje de marcado**), estamos pidiendo un archivo con extensión **.md** o **.markdown** (da lo mismo cual uses, ambos son equivalentes) que siga la sintaxis de dicho lenguaje. Puedes utilizar la [guía de referencia](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) y/o copiar alguno de los README.md que vienen en tu repositorio privado, y utilizarlo como base para tu archivo.

Ahora, puedes escribirlo o usando tu propia IDE (la mayoría soporta markdown y puede mostrarte una preview de tu archivo), o desde un editor [online](https://stackedit.io/). También puedes desde tu repositorio remoto en la página web de github, aunque no lo recomiendo, ya que podrías accidentalmente desincronizar tu repositorio remoto vs. tu repositorio local y tener problemas a futuro.

Espero haber respondido tu duda! :cat:
