### ISSUE TITLE
Guardar avances 

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2233/Syllabus#52]
Hola, cuando el usuario quiere guardar el juego se deben guardar "el nuevo estado de la galaxia" (sec 6.4.2). No dice nada de las galaxias en si,  entonces al crear una galaxia, ¿se deben guardar automáticamente?  ¿hay forma de eliminar y/o no guardar una galaxia creada? 

gracias!

**Comment by ptflores1** [comment]
Hola!
Al momento de crear una galaxia no hay forma de eliminarla después, entonces si, debiese guardarse automaticamente para que en la opción descrita en 6.4.3 no se elimine.
Saludos !

**Comment by joaquineichholz** [comment]
Gracias!!

**Comment by emeiese** [comment]
Hola! Respecto a esto mismo, por lo que entiendo, entonces, los cambios deben guardarse automáticamente tanto cuando la galaxia se crea, como cuando la galaxia se **modifica** cierto? (en otras palabras, el único cambio que se "cuestiona" al usuario, es cuando decide jugar en la galaxia)

**Comment by ptflores1** [comment]
Hola !
Estas en lo correcto los unicos cambios que no se guardan automaticamente son los hechos en el modo "jugar en la galaxia".
Saludos !

**Comment by pcseisdedos** [comment]
No entiendo bien como funcionan los recursos, al jugar en galaxia se sobre-escriben los valores de los minerales y deuterio de esta? es que en el enunciado en la parte 6.4 dice que el usuario parte con 1000 de cada uno, pero según tenía entendido los recursos pertenecen a las galaxias... o es como que el "usuario" tiene recursos y puede decidir en que galaxia dejarlos?

**Comment by ptflores1** [comment]
Holaa !
No se si te sirve ver esta #73  issue, si quedas con dudas avisame !
Saludos

**Comment by pcseisdedos** [comment]
Me queda mas claro que los recursos pertenecen a las galaxias y no al jugador. Pero sigo sin entender en que momento debemos asignar el valor de 1000 a los recursos estipulado en la parte de jugar en la galaxia, dado que cada una ya posee cierta cantidad de recursos, por qué deberia sobre escribirlos, y en que momentos debería llamar a esa función... siempre que se quiera jugar en una galaxia? De ser así para que hay que guardar los recursos si se sobre escriben constantemente. Gracias

**Comment by Hernan4444** [comment]
@pcseisdedos esto (de asignar 1000) pasa cuando juegas con una galaxia **recién creada mediante la interfaz**, puesto que **nunca se ha jugado con ellas** así que **no** ha tenido la opción de **"partir" en dicha galaxia**. 

Las galaxias del archivo se pueden considerar como galaxias ya creadas y donde el jugador ya partió en algún momento con 1000 de recursos, pero gastó/recolectó en algún tiempo pasado.

Espero haber respondido tu duda.
Saludos ✌️

**Comment by pcseisdedos** [comment]
Si, muchas gracias
