### ISSUE TITLE
Dudas varias

### ISSUE THREAD

**Issue by benjazuloaga** [IIC2233/Syllabus#52]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Tenia un par de consultas con respecto a la tarea.
1) Es necesario la utilización de objetos o es exclusivamente una tarea sobre flujos. Esto me surgió dado que en el README subido aparece que tendrá puntaje esto pero en el enunciado no se señala nada con respecto a esto. 

2) Tengo una complicación al mostrar el numero de bestias que hay alrededor de una coordenada. Según entiendo la función print_tablero entrega los cuadrados solo con espacios vacíos(si le entrego " "), entonces al momento de que la coordenada subida no sea bestia como se puede realizar el conteo de bestias alrededor de esa coordenada en especifico, porque todos alrededor serán espacios vacíos.

3) Para guardar las partidas, según leo en enunciado sera un archivo txt por nombre de usuario, y estas tendrán que ser guardadas en una carpeta de nombre partidas. Entonces entiendo que la cantidad de archivos serán tal como nombres de usuario de crearon. Mi duda va mas específicamente a como puedo guardar estos archivos en una carpeta distinta si estoy trabajando sobre mi carpeta de T0.

**Comment by drcid98** [comment]
Hola! 
1. No es necesario utilizar clases, tal como se respondió en la issue #32 
2. No entiendo muy bien la pregunta, si pudieras explicar un poquito más tu problema para ver en que puedo ayudarte sería ideal
3. Sobre esto, para poder guardar estos .txt en otra carpeta basta con utilizar **paths relativos** al trabajar con estos archivos. Puedes crear una carpeta y ahí guardar los archivos y luego especificar en tu README que es necesario crear una carpeta con un nombre y ubicación en específico para que tu tarea funcione.

**Comment by benjazuloaga** [comment]
2. Me refiero que al descubrir una celda que no es una bestia hay que poner un numero tal que este represente la cantidad de bestias alrededor de la coordenada descubierta. No entiendo como puedo hacer ese conteo, dado que las celdas que son cuadrados están vacías.
3. ¿A que te refieres con paths relativos? Perdón pero no estoy familiarizado con eso.

**Comment by drcid98** [comment]
Hola deneuvo,
2. Lamentablemente la forma en que hagas el conteo es parte de la tarea, no puedo responderte mucho en ese punto :(
3. Path relativos son los que se indican desde la carpeta en donde "estás" hasta otra. Por ejemplo, si estás en la carpeta T0 y dentro de esta tienes tu programa y otra carpeta llamada "partidas", para hacer referencia a un archivo dentro de "partidas" en tu programa deberías hacerlo usando un path del estilo `./partidas/archivo.txt`. Espero quede claroo.
Saludos!
