### ISSUE TITLE
Contraseña usuarios en distribución de puntaje

### ISSUE THREAD

**Issue by drosselot** [IIC2233/syllabus#52]
En la distribución de puntaje donde dice "Se puede registrar un nuevo usuario, nombre debe ser válido", sale también que la contraseña debe tener un mínimo de 8 caracteres. En ningún otro lado sale algo de una contraseña. ¿Se refiere al nombre de usuario cierto?

**Comment by bimartinez** [comment]
Hola @drosselot!

Efectivamente se refiere al nombre de usuario, disculpa por nuestra confusión. Ya se encuentra corregido! Muchas gracias :smile: 

Saludos y éxito :star2:
