### ISSUE TITLE
Añadirse a si mismo de contacto en contactos.csv

### ISSUE THREAD

**Issue by FVivess** [IIC2233/syllabus#52]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Me surgió la duda si uno puede añadirse a si mismo de contacto, y de ser el caso, si es importante que en la lista de contactos no esté repetido dos veces el mismo nombre (por ejemplo, si usuario1 se añade a si mismo, ¿importa si aparece dos veces "usuario1,usuario1" en "contactos.csv"?)

**Comment by Juampisaez** [comment]
Hola @FVivess 
Dado que no esta especificado en el enunciado, queda a tu criterio ese punto. En lo personal, creo que si es que te agregas a ti mismo bastaría con agregar solo una fila en "contactos.csv", ya que no tendría mucho sentido tener dos filas iguales en este archivo. De igual manera queda a tu criterio y deberías especificarlo al momento de escribir el Readme :)

Espero haya quedado mas claro, cualquier duda sigo atento.

**Comment by FVivess** [comment]
Super claro. Gracias!
