### ISSUE TITLE
Rango de años ingresables

### ISSUE THREAD

**Issue by Jaluco** [IIC2233/Syllabus#52]
Hola, mi duda es  que rango de años serán ingresados a la tarea, para saber que rango de años bisiestos debo considerar para validar las fechas :)

**Comment by rpalmaotero** [comment]
Puede ser cualquier año > 0. Si te sirve, hay un algoritmo muy simple que te dice si un año es bisiesto o no: https://en.wikipedia.org/wiki/Leap_year#Algorithm.

**Comment by akaminetzkyp** [comment]
Hola @rpalmaotero! En la issue #47 @arturodelreal dijo que podíamos asumir una fecha mínima antigua, como del 2000. Todavía podemos hacer eso?

Saludos!

**Comment by rpalmaotero** [comment]
@akaminetzkyp toda la razón, edité mi respuesta acá.
