### ISSUE TITLE
duda sobre nombre archivos 

### ISSUE THREAD

**Issue by karlamunoz14** [IIC2233/Syllabus#52]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola!, mi duda es:
Cuando el cliente ingrese un nombre de archivo para abrir la red, en que formato sera?
1) nombre_archivo
2) nombre_archivo.txt
MUCHAS GRACIAS!

**Comment by CrisHD935** [comment]
Hola! Debe ser sin el .txt

**Comment by FernandoMartinez1** [comment]
> Hola! Debe ser sin el .txt

Hola!

Disculpa, no me quedó claro si el input se recibirá sin .txt (lo que implicaría que nosotros debemos agregar el .txt al abrir el archivo), o que nosotros no debemos agregarle el .txt al cargar el archivo dentro del código (lo que implicaría que en el input se recibirá con el .txt incluido)

sorry si es muy obvio, quiero estar seguro.

**Comment by CrisHD935** [comment]
El input se recibe sin el .txt, este debe ser incluido dentro del código.
