### ISSUE TITLE
Duda en el orden para los ejercicios resueltos

### ISSUE THREAD

**Issue by jchamorrou** [IIC2233/syllabus#52]
Hola! Estaba estudiando el contenido y queria saber si recomiendan estudiar todos los capitulos y despues hacer los ejercicios propuestos o cada vez que lo mencionan tratar de hacerlo altiro. Me entro esta duda porque estaba haciendo el ejercicio 2.1 y despues leyendo me di cuenta que cosas de los siguientes capitulos me pudieron haber ayudado un poco en el ejercicio tambien. Gracias de antes :)

**Comment by retamalcito** [comment]
¡Hola @jchamorrou! :wave:

No es necesario que resuelvas los ejercicios propuestos en ningún orden en particular. En cada cuaderno se invita a resolver el ejercicio relacionado con ese contenido enseguida, pero si lo prefieres puedes leer todo el contenido primero y luego hacer todos los ejercicios.

Recuerda que el objetivo de los ejercicios propuestos es que pongan en práctica la materia de la semana y se familiaricen con su sintaxis, por lo que te recomiendo resolverlos como te parezca más cómodo, ¡lo importante es que aprendas! :tada:

¡Saludos y mucha suerte! :heart:
