### ISSUE TITLE
Semana 2: Progragotchis, sobreescribir __gt__

### ISSUE THREAD

**Issue by aangel-sama** [IIC2233/Syllabus#52]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Estuve haciendo el ejercicio hasta que llegue a la parte de sobreescribir __gt__ y primero no entiendo de que manera sobreescribir __gt__, lo hice de multiples maneras pero nunca me daba la lista ordenada de mayor a menor, no sé cual es el metodo para poder sobreescribirlo de forma correcta.

**Comment by Dvckhv** [comment]
Hola @aangel-sama !
En el ejercicio se te pide ordenar una lista de mayor a menor utilizando la **vida** de los progragotchis,   el método `__gt__()` debe retornar un `bool`, que es el utilizado por la función `sort()` al momento de ordenar una lista. Debes recordar que por defecto al usar `sort()` la lista se ordenará de menor a mayor, por lo que tu método `__gt__()`  deberá implementar el comportamiento inverso al esperado. Por último, el método se encuentra definido por defecto en la clase `int` y `float` , por lo que puedes utilizar esta información y el hecho de que la vida de tus progragotchis está definida como  `int` o `float` para hacer el polimorfismo.

Cuentame si sigues con dudas :)
