### ISSUE TITLE
Duda formato clases

### ISSUE THREAD

**Issue by SrGuspin** [IIC2233/Syllabus#52]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola!
Tengo una duda sobre el formato que deben de tener las variables. En mi tarea estoy siguiendo el formato snake case para todas las variables, pero me pregunte si las **clases tambien deben de seguir el mismo formato**, es decir, tengo variables y funciones tipo `lineas_archivo `y la clase deberia de ser `Archivos `o `archivos`.

Muchas gracias de antemano!

**Comment by Emiliax16** [comment]
Hola @SrGuspin ! para las clases siempre las escribimos con mayúscula :) y si necesitas escribir más de una palabra (del estilo `auto_rojo`), se escribiría `class AutoRojo:` . Saludos!
