### ISSUE TITLE
Duda sobre como acceder a las instancias de QLabel

### ISSUE THREAD

**Issue by mariizamb** [IIC2233/syllabus#520]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! encontré un comando findChildren(QLabel, "nombre label"), segun lo que entiendo de este comando, me ayuda a buscar el label que yo quiero por su nombre pero al momento de poner el geometry creeo que me esta lanzando la de QGridLayout en donde estan esos Qlabel. ¿Cómo puedo hacer esta diferenciación? :( 
O de no poder hacerse, hay alguna otra forma de poder acceder a los QLabel por su nombre?

**Comment by JadrinaDA** [comment]
Hola! Primero quiero felicitarte por buscar nuevos comandos para usar. Viendo lo que has subida al repo estas usando el findChildren de forma correcta. Tal vez tu error viene de que cambias la variable donde estas guardando el label accidentalmente? Tendría que ver esa parte de tu código para estar segura, si quieres puedes subirlo y le doy una mirada. Otra cosa que puedes hacer es guardar los labels en una lista o diccionario que sea atributo de la ventana para que puedas accederlo donde sea. Avísame si tienes alguna duda. Saludos!

**Comment by mariizamb** [comment]
Ya genial, intenté crear una lista con los labels pero no me resultó por lo que mencionas, osea que en mi lista no estaba la parte de "que sea atributo de la ventana", como podría hacer esto? (existe alguna función o algo de ese estilo?) y por otro lado, como te subo el código jaja. 
Finalmente mi código lo que hace en terminos generales sería: lista.append(self.findChildren(...).x(), self.findChildren(...).y())
pero ahí, los .x(), .y() me arrojan posicion (0,0) :(

**Comment by JadrinaDA** [comment]
Con que sea me refiero a hacer algo tipo self.lista_labels, así lo puedes llamar en cualquier función sin pasarlo como argumento. Para subir el código solo haz push de lo último que tienes porque estaba viendo tu repo y no vi donde se estaba usando geometry. Y sobre lo de retornar el (0,0) puede ser posible que los labels no se estén moviendo? Setteaste directamente los atributos x e y o usaste una función?

**Comment by mariizamb** [comment]
Ya super, ahora hago push yy finalmente estoy utilizando .x() , .y() y las posiciones de los labels que busco son labels estáticos pero asignados randomente.

**Comment by JadrinaDA** [comment]
Corrí tu código y parece que cuando la ventana está escondida da (0,0) pero al abrirla ahí sí dan los valores correctos. Intenta poner ventana_juego.show() en main para ver si te pasa lo mismo. Debe ser porque cuando la ventana está cerrada el programa no reconoce los labels.

**Comment by mariizamb** [comment]
Ya ahí si! Super!! de verdad te pasaste gracias!! Ahora si puedo ver las posiciones y trabajar con ellas :)

**Comment by valerianazal** [comment]
Hola @mariizamb !! No cierres las issues que haces si ya fueron resueltas, ya que le pueden servir a otro estudiante con la misma duda 😁 
Mucha suerte con la tarea!
