### ISSUE TITLE
Manejo de excepciones (ejercicios)

### ISSUE THREAD

**Issue by Zapararte** [IIC2233/syllabus#520]
Hola! en el ejercicio propuesto número 4 (Netflix), el primer error que hay es un FileNotFoundError, intenté manejarlo de dos formas y no entiendo por qué no funciona mi _try-except_ . Esta es la primera forma:
![image](https://user-images.githubusercontent.com/31223470/66973209-a319f680-f06d-11e9-9d71-93c8b2728209.png)
segunda forma:
![image](https://user-images.githubusercontent.com/31223470/66973267-d78db280-f06d-11e9-9a55-3ab2b0de652f.png)

A lo que la salida fue, respectivamente:
primera forma:
![image](https://user-images.githubusercontent.com/31223470/66973380-3ce1a380-f06e-11e9-84f1-ef2da2531e38.png)

segunda forma:
![image](https://user-images.githubusercontent.com/31223470/66973451-6b5f7e80-f06e-11e9-89d9-5a7fce696899.png)

**Comment by fdoflorenzano** [comment]
Hola @Zapararte,

Disculpa la demora en responder. Responderé cada error por separado:

1. El problema con la primera forma que entregaste, es que el error `FileErrorNotFound` se lanza cuando intenta abrir el archivo y no lo encuentra. Como lo armaste, haces un `try` dentro del contexto de `with open`, entonces primero abre el archivo y luego ejecuta el `try`. Como el `open` no está dentro de `try` (si no que al revés), no es capturado el error.
2. En esta forma si lo tienes en el orden correcto: `open` dentro del `try`. Incluso funciona la captura del error, ya que si te fijas, el error que te lanza aparece en la línea 14, que es dentro de la clausula `except`. Esto último indica que entró a la clausula pero un error apareció al intentar ejecutar algo. Como ves, te lanza un `AttributeError` ya que intentas acceder a `self.serie` (como un atributo de la instancia de la clase) en vez de `serie`. Veo que intentaste capturar el error `AttributeError` en la sentencia `except`, pero esto no se captura ya que esa línea (la 14) no se ejecuta dentro de un `try`. Uno al capturar errores, solo puede hacerlo si lo ejecutado está dentro de un `try`.

Espero se entienda. Si tienes más dudas, puedes responder.
