### ISSUE TITLE
Bonus juego diagonal

### ISSUE THREAD

**Issue by furzuadr** [IIC2233/syllabus#520]
Si implemento el bonus de Timbiriche diagonal, esto reemplaza a mi juego normal? Es decir, puedo hacer que solo se pueda jugar de esta forma y no tener que implementar la otra forma?

**Comment by KnowYourselves** [comment]
Hola @furzuadr!

Exacto!, Si haces ese bonus no hay necesidad de dar la opción de jugar el juego original, pero cuidado, que a pesar de ser un bonus, debe cumplir todos los requerimientos explicitados para el original.

Éxito!
