### ISSUE TITLE
Usar funciones de un generador en el resto de las funciones.

### ISSUE THREAD

**Issue by JohanM-cyber** [IIC2233/Syllabus#520]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Quería preguntar que si para la parte en que tenemos que usar dos o tres generadores, podemos llamar a las funciones anteriores que usan un generador. 

Ósea poder usar `cantidad_vendida_de_pizza_por_tipo()`, `pedidos_con_al_menos_esta_pizza()` o `cliente_indeciso()` en otra funciones como: `ganancia_total_de_un_local()` o `pizzas_vendidas_mes_pais()`.

Edit:
Adicionalmente quisiera confirmar el hecho de que podemos crear otros archivos e importarlos a `main.py` tal y como dice en el enunciado.
![image](https://github.com/user-attachments/assets/4ac6ebfa-fc5c-4ac3-a9c1-14965b09d230)

**Comment by AlonsoPlaza** [comment]
Hola. si puedes llamar funciones anteriormente y tambien puedes crear más archivos e importarlos.
