### ISSUE TITLE
Que datos son parametros

### ISSUE THREAD

**Issue by cperez20** [IIC2233/syllabus#520]
En el enunciado dice que si una palabra esta escrita de una determinada manera se debe definir como parametro en el archivo parametros.py pero mi duda es que algunas numeros tambien estan escritos en ese formato, estos también deben considerarse como parametros?

**Comment by jitorcas** [comment]
Hola @cperez20 

La issue #465 responde a tu pregunta.

Éxito en la tarea!! 🥇
