### ISSUE TITLE
Direcciones del sprite

### ISSUE THREAD

**Issue by rgriver** [IIC2233/Syllabus#521]
¿Puede el sprite de un personaje mirar solo en cuatro direcciones (arriba, abajo, derecha e izquierda)?

**Comment by hanavarrete** [comment]
mientras puedas hacerlo girar y que este tenga el movimiento en los 360° no hay problema

**Comment by sebacruzd** [comment]
Como complemento a @hanavarrete, está la opción del Top-View. Esto te podría facilitar ese tema en términos de rotarlo en los 360°.

**Comment by rgriver** [comment]
Buena.
