### ISSUE TITLE
Proporciones del almuerzo

### ISSUE THREAD

**Issue by MrEarle** [IIC2233/Syllabus#521]
En el enunciado dice:
> Almorzar: Todos los usuarios, tanto estudiantes como funcionarios, almuerzan todos los días. El
X % de los alumnos y funcionarios almuerza de 13:00 a 13:59, el Y % almuerza de 14:00 a 15:00,
mientras que el (100 -X - Y )% lo hace de 12:00 a 12:59. Con respecto a los vendedores, en este
mundo no comen. Los datos de X e Y se entregarán al inicio de la simulación.

Pero los alumnos llegan entre las 11 y las 15 hrs, entonces existe la posibilidad de que no esté el (100 - X -
 Y)% de los miembros en la uc entre las 12 y las 13.

Que se haría en ese caso? Hacia donde se distribuye el porcentaje que falta?

**Comment by iqacevedo** [comment]
Hola, lo acabo de responder en la issue #491.

Saludos !
