### ISSUE TITLE
Duda con QFrame y botones

### ISSUE THREAD

**Issue by panchotarud** [IIC2233/syllabus#521]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Tengo una duda con los botones de las ventanas ya que no me funcionan. Puse 3 botones en la ventana de inicio y todos ellos están contenidos dentro de un QFrame. En el código dentro de la clase 'VentanaInicio' llamé a los botones como 'self.boton_salir' (por ejemplo) y lo usé de la misma manera que en la AS2, conectándolo con el método 'salir' que contiene un 'self.close()', dentro de la misma clase. Aún así, el botón no funciona. Entonces, los botones al estar contenidos dentro del QFrame tienen que ser llamados de otra manera en el código?

**Comment by Juampisaez** [comment]
Hola @panchotarud 
Una duda, estas instanciado tu ventana directamente en codigo? o lo estas haciendo desde QtDesigner?. Si puedes subir tu repo actualizada a github mejor

Quedo atento :)

**Comment by panchotarud** [comment]
Lo acabo de subir. 
Y cree las ventanas en QtDesigner y luego las instancié en el codigo y agregué las imagenes, como en la AS2:)

**Comment by Juampisaez** [comment]
Mm entiendo, tal vez seria mejor que instanciaras todos los elementos directamente desde QtDesigner, es decir, asociar cada boton por ejemplo a su metodo respectivo, y dentro del codigo definir lo que realiza cada metodo. 

Se entiende?

**Comment by panchotarud** [comment]
Lo acabo de probar y sigo con el mismo problema:/ (si es que lo hice bien) jajaja

**Comment by Juampisaez** [comment]
Yaa, mira en semestres pasados se explico como trabajar con Designer y codigo a la vez. A continuacion te dejo dos videos que te podrian ayudar para resolver tu problema y mas cosas ademas (tu duda me parece muy tecnica jejeje).
[Ayudantía Interfaces Gráficas II - Parte 1 (front-end) ](https://www.youtube.com/watch?v=EAa7FozKY1w)
[Ayudantía Interfaces Gráficas II - Parte 2 (back-end)](https://www.youtube.com/watch?v=KyyFNnOllZw)


>**Importante**
 Ojo que estos videos son de semestres pasados (especificamente [2020-1](https://github.com/IIC2233/syllabus-2020-1)), por lo que puede que hablen de temas que no se hayan visto este semestre y viceversa. Sin embargo, enfócate en la parte donde se explica lo que preguntas.

> 
Espero que te sirva de ayuda :)

**Comment by panchotarud** [comment]
Gracias jajaj pero lo intenté exactamente como en el video (usando un Widget como ventana en vez de un MainWindow) y me ocurre el mismo problema:/ ya no se que hacer

**Comment by Juampisaez** [comment]
Mm, comentandolo salio que podia ser la version de pyqt5 que tienes en tu mac. Revisa que tengas la versión 5.15.4 de pyqt instalada.

Quedo atento :)
