### ISSUE TITLE
Dudas sobre "ganancias_producidas_en_los_pedidos", manejo de generadores

### ISSUE THREAD

**Issue by mVal919** [IIC2233/Syllabus#521]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, muy buenas tardes.
Tengo una duda sobre la implementación de la función ganancias_producidas_en_los_pedidos.
![image](https://github.com/user-attachments/assets/c7d84016-29b4-400a-872f-b38d459cd678)
Al ver mi resultado, se nota al tiro que nunca pudo sumar mas de la primera vez, pero si pasa al siguiente (el 9999 lo puse para ver si siquiera veia el siguiente elemento).
Efectivamente, poniendo que me diga cual es el elemento con el que está trabajando, me lo imprime, osea que si pasa a elemento siguiente
![image](https://github.com/user-attachments/assets/21c91e32-0685-4af0-9751-8e24d2c44a98)
Sin embargo, si reemplazo la ganancia en la tupla para que me diga a que valores de Pizzas es igual el nombre de la pizza del pedido, me imprime esto
![image](https://github.com/user-attachments/assets/5ed37b0c-4134-4efd-aaa3-5ad4b4142849)
Que pasó ahí? Me funcionó bien la primera vuelta, y despues no. Quizás se acabaron los elementos del generador, y despues no retorna nada? Pero no se puede usar copy para que pueda seguir usando el generador para todos los elementos
Eso, no se si podrán ayudarme

**Comment by mVal919** [comment]
Y relacionado a esto, ¿como le puedo sacar el valor maximo a un valor? (en pedido_con_mayor_descuento_utilizado, o pizza_favorita_cliente)
Porque si hago max(generador, key=lambda x: x.descuento), gasto el generador, y luego al hacer filter o cosas asi, siempre me retornará vacio.

**Comment by mVal919** [comment]
Hola
No me pesquen!
Descubrí sobre tee(), asi que la pregunta ya no tiene mucho sentido.
Eso, gracias!

**Comment by kbetelgeuse** [comment]
Hola @mVal919 ! En efecto, esa función del módulo `itertools` te puede ayudar con respecto a lo que me mencionas.
Por otra parte, ¿me podrías indicar si ahora ya no tienes problemas con la consulta "`ganancias_producidas_en_los_pedidos`"?
Saludos, y si tienes otra duda acerca de este mismo tema (de esta issue), coméntala 😉.

**Comment by mVal919** [comment]
Hola
No, ese era como mi único tema con esa función. 
Muchas gracias igual!
