### ISSUE TITLE
Diferencia de enunciado v/s Bonus Servidor y Cliente Robusto.

### ISSUE THREAD

**Issue by fediaz3** [IIC2233/syllabus#521]
Hola!
Tengo una confusión, entre el enunciado con el bonus de Servidor y Cliente Robusto.

En el enunciado y en excel , dice que tiene puntaje obligatorio:
 1)  'Si el jefe abandona la sala de espera se asigna un nuevo jefe'
 2) 'Una sala o partida es eliminada de manera automática en caso de que esta se quede sin jugadores. Se debe revisar que esta desaparezca de ventana de salas'

Lo que yo entiendo, esque:
Cuando abandona un jefe o un jugador cualquiera, entiendo que es cuando se preta 'X'(se cierra su interfaz)
entonces...
Al implementar (1) y (2),
siento que debemos implementar si o si el bonus de servidor y cliente robusto, 
donde nos dice que debemos manejar los casos donde se cierra la interfaz de un cliente
siendo ¿'obligatorio' hacer este bonus?

Espero que se haya entendido 

Gracias

**Comment by marioreinike** [comment]
Hola @fediaz3! 
No necesariamente es así, ya que (1) y (2) se refieren a cuando un cliente cierra la ventana de sala en la que está jugando. En ese momento debe ser devuelto a la _ventana de salas_, sin desconectarse del servidor. Esto se diferencia del Bonus _Servidor y Cliente Robusto_, que pide que en caso de que algún cliente o el servidor se desconecte (es decir, que cierre su ventana de salas o termine su ejecución), el programa no se caiga y arroje un mensaje de desconexión. Espero haber sido claro.
Saludos!

**Comment by fediaz3** [comment]
Entonces en la interfaz de la sala debe haber por ejemplo un botón u otra forma  para salir de la sala y devolverme ala ventana de salas? 
Y así poder diferenciar de salir de la sala con el 'x' de la interfaz

**Comment by marioreinike** [comment]
Claro, esa sería una forma de hacerlo, pero no tan correcta ya que si cierras la ventana te desconectas. Una forma más adecuada sería que controles el evento de cerrado de la ventana de la sala. En este caso, debes sobreescribir el método `closeEvent` de QWidget, el cual se ejecuta cuando cierras la ventana (presionas el botón`X`). Para mas info revisa este link de [StackOverflow](https://stackoverflow.com/questions/40622095/pyqt5-closeevent-method). Espero que te sirva de ayuda.
Saludos!

**Comment by fediaz3** [comment]
me ha servido  :smile:
Gracias
