### ISSUE TITLE
Error importando parametros.py

### ISSUE THREAD

**Issue by aipostigo** [IIC2233/syllabus#521]
En mi archivo principal quiero importar parametros.py y me aparece el siguiente error:

ModuleNotFoundError: No module named 'parametros.py'; 'parametros' is not a package

pero en el resto de los modulos que lo importo no hay ningun problema, porque puede ser?

**Comment by matiasmasjuan** [comment]
Hola @aipostigo !

¿Estas importando correctamente el archivo? Por ejemplo, es distinto importar:

1)
```python
import parametros.py
```
que

2)
```python
import parametros
```
Recuerda que si estás importando otro módulo de *python*, debes hacerlo de la segunda forma, sino, te va a arrojar el mismo error que mencionaste.

Suerte y comentame cómo te va 😄

**Comment by aipostigo** [comment]
Lo estoy importando asi:
import parametros as pm

Lo que me parece raro es que para todos los otros modulos tengo escrito lo mismo y me tira el error solo en el main.

**Comment by aipostigo** [comment]
Ya me di cuenta del problema! sin darme cuenta escribí parametros.py en otro modulo,

Gracias!
