### ISSUE TITLE
Duda con regex

### ISSUE THREAD

**Issue by Alonsinho1** [IIC2233/syllabus#521]
Hola espero se encuentren bien en estos dificiles dias.

Tengo una duda en el contenido en la parte de regex. En la parte de verificador de mail se señala que si queremos buscar un un ¨.¨ debemos utilizar \. para que no cuenta como el meta- caracter. Sin embargo para el .cl esto no se hace y funciona bien, por que ocurre esto?

Tambien mi otra duda es en que parte se evita que en no se pueda encontrar un mail de que contenga tanto mail "como" "mimail" por ejemplo komommdocs@mailmimail.cl o jocmdoasmcdso@mail.mimail.cl.?

Muchas gracias

**Comment by fdoflorenzano** [comment]
Hola @Alonsinho1, 

Buenas preguntas. Las responderé en orden:

1. Muy buena observación. Efectivamente, como se espera que haya un punto antes del `'cl'`, debería escaparse el punto, de la forma: `'[a-zA-Z0-9_.]+@((seccion1|seccion2)\.)?(mimail|mail)\.cl'`. Ahora, como dices pareciera funcionar sin escaparlo, pero en realidad solo funcionaba para los ejemplos mostrados: todos tenían un punto en esa posición. Al no escapar el punto, cualquier cosa hubiera calzado con esa parte, entonces si intentabas hacer *match* de `'[a-zA-Z0-9_.]+@((seccion1|seccion2)\.)?(mimail|mail).cl'` (sin escape del punto) con el *string*: `'nombre.apellido@mailAcl'` (con una `'A'` en vez de `'.'`), también hubiera hecho *match*. Esto era un error en los ejemplos, pero ya fue corregido en el repositorio. Gracias por hacerlo notar 😊 .

2. Para responder esta pregunta hay que analizar el patrón creado para la situación: `'[a-zA-Z0-9_.]+@((seccion1|seccion2)\.)?(mimail|mail)\.cl'`. Si te fijas, el patrón de alguna forma **obliga** cierta forma del *string*, donde solo le deja como opción algunos dominios. Analizando más en detalle, podemos separar el patrón por secciones:
- `'[a-zA-Z0-9_.]+'`: la primera parte pide que haya al menos un caracter (`'+'`) que sea una letra, número, `'_'` o `'.'`. Notar, que solo permite esos caracteres calzar en esa parte: una letra, número, `'_'` o `'.'`.
- `'@'`: al escribir un arroba directamente, se obliga a que haya un arroba en el *string* para que haga *match*. Si te fijas, en ninguna otra parte del patrón se admite el caracter `'@'`. Luego, de haber uno, debe calzar con esta sección.
- `'((seccion1|seccion2)\.)?'`: esto permite que haya (o no) una dirección `'secccion1.'` o `'secccion2.'`, pero ojo que solo permite esas dos direcciones ya que se escriben literalmente. No permitiría ``'secccion3.'``, ya que no calza con ninguna de las opciones.
- `'(mimail|mail)'`: esto permite el dominio `'mail'` o `'mimail'`, y **solo esos dos dominios**, ya que están escritos literalmente.
- `'\.cl''`: obliga a que aparezca al final del *match* un `'.cl'`, como comentado en la pregunta anterior.

Antes de responder tu duda, haré otra más simple. ¿Dónde se evita en el patrón que hayan dos `'@'`? De alguna forma es similar a lo que preguntas, y uno esperaría algo que dijera "solo un arroba" o "no arrobas". Pero si analizas la totalidad del patrón, está implícita esa propiedad. Hay una aparición literal del arroba, lo cual obliga que haya al menos uno. Lo que nos asegura que no hayan más, es que el resto del patrón no dan como posibilidad que exista un arroba. La primera parte solo admite letras, números, `'_'` o `'.'`; y la siguiente solo admite palabras específicas que no incluyen el arroba.

Entonces, ¿dónde se evita que hayan más dominios de correos? Por como está creado el patrón, después del arroba solo pueden hacer *match* *subtrings* que calcen con `'((seccion1|seccion2)\.)?(mimail|mail).cl'`. Y esos al usar los meta-caracteres `|` y `?`, admite **solamente** las siguientes opciones de dominio de correo: `'seccion1.mimail.cl'`, `'seccion1.mail.cl'`, `'seccion2.mimail.cl'`, `'seccion2.mail.cl'`, `'mimail.cl'` o `'mail.cl'`.

Tengo otra observación importante, el ejemplo del material utilizaba el método `match` de `re` para ver si los *strings* calzaban con el patrón. El problema con esto, es que como revisado, este solo busca si hay un *match* desde el comienzo del *string*, pero no se preocupa de que la totalidad del *string* calce con el patrón y por lo tanto puede traer falsos positivos. Por ejemplo, un *string* que comienza con un correo válido, pero continua con cualquier cosa hubiera calzado con el patrón: `'nombre@mimail.clCUALQUIERCOSA'`. El análisis hecho antes, y la idea detrás del patrón, toman por suposición que es el *string* completo el que debe calzar con el patrón, de no hacerlo, incluso podrían tener múltiples arrobas mientras estos estén después del `'.cl'`. 

Hay dos alternativas para remediar esto: se agregan los meta-caracteres de inicio y fin del *string* al patrón para que no acepten los casos mencionados: `'^[a-zA-Z0-9_.]+@((seccion1|seccion2)\.)?(mimail|mail).cl$'`; o se ocupa el método `fullmatch` de `re` que tiene el mismo resultado, verifica que la palabra complete calce con el patrón.

Espero se entiendan las explicaciones, si tienes más dudas o algún detalle no se entendió, no dudes en responder. 

Saludos.
