### ISSUE TITLE
Duda en función "pedido_con_mayor_descuento_utilizado"

### ISSUE THREAD

**Issue by mVal919** [IIC2233/Syllabus#522]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola otra vez.
Tengo una funcion aca que compara el descuento de cada elemento con el maximo ya calculado.
![image](https://github.com/user-attachments/assets/516a7211-1f58-466f-a40f-2b742a9c1948)
Pero cuando intento hacer correr el programa, sale esto:
![image](https://github.com/user-attachments/assets/504145b8-39d7-44ac-a74d-63486d1fcaaa)
Lo que no es verdad porque x es una instancia de ContenidoPedidos. No se que paso, porque para ninguno de los otros ejercicios se ha quejado por eso, y ahora ninguno de los ejercicios corre a menos que comente esas lineas.
Eso, muchas gracias, y disculpa si estoy preguntando mucho jjj

**Comment by wintermelyn** [comment]
Hola @mVal919!

Primero te recomiendo que añadas alguna linea para debuggear si el tipo de x que estás recibiendo al llamar la función es correcto o no:
```python
if not isinstance(x, ContenidoPedidos):
      raise TypeError(f"Se esperaba una instancia de ContenidoPedidos, pero se recibió {type(x)}") # o un print


```
Es probable que para el calculo del maximo hayas iterado sobre el generador. Recuerda que los generadores en Python son iteradores que se consumen una vez, es decir que después de iterar sobre ellos una vez, ya no puedes volver a acceder a sus elementos. También revisa que maximo esté definido (pues en la foto parece estar siendo utilizado como una variable global). 🧙‍♂️

**Comment by mVal919** [comment]
Yaa
Si, si ahí vi que puedo arreglar eso con tee, pero me queda otra duda igual. ¿Que tomarán como variable global? ¿Una variable definida para todas las funciones a la vez, o una variable definida para la funcion en especifico (x ej, si tengo que 'maximo' sea max(descuentos) y que solo sea relevante para la función)?
Osea no lo he probado todavia porque no estoy con el computador, pero me imagino que si tuviera que hacer un filter con maximo, y usara tee, tendría que hacer que tee, y el calculo de max(descuento) se repita muchisimas veces veces?
Muchas gracias igual!

**Comment by wintermelyn** [comment]
> ¿Que tomarán como variable global? 

Hola @mVal919! Por variables globales me refiero a cualquier variable que está definida fuera de cualquier función o método y puede ser accedida y modificada desde adentro. Es decir, para la imagen que mandas defines maximo fuera de la función y eso la convierte en una variable global (no local).

> Si tuviera que hacer un filter con maximo y usara tee como se haria?
La función tee crea copias d eun generador, es decir se puede utilizar si necesitas usar el generador para varias operaciones (en este caso calcular maximo y luego aplicar un filtro).
```python
gen1, gen2 = tee(generador)
# Usamos gen1 para obtener el maximo.
# Filtramos el gen2 para obtener solo los que tienen descuento igual al maximo
```
