### ISSUE TITLE
Probabilidad de comprar snack al llegar al campus

### ISSUE THREAD

**Issue by MrEarle** [IIC2233/Syllabus#522]
> Al momento de llegar a la universidad todas las personas deciden si comprarse un snack en forma
aleatoria, segun una probabilidad de random(0,1).

Que probabilidad es esa?
random.random() no toma parámetros, se refiere a uniform?

**Comment by jotramon** [comment]
x2 :)

**Comment by MrEarle** [comment]
Gracias!

**Comment by MrEarle** [comment]
Y cual es la probabilidad de comprar snack?
