### ISSUE TITLE
Suscribirse a una label en Github

### ISSUE THREAD

**Issue by emeiese** [IIC2233/Syllabus#522]
Hola! Dado que las Issues con la etiqueta **importante** son **IMPORTANTES** (lol)  y hay que estarlas revisando a cada rato, me gustaría poder suscribirme a la etiqueta, y que me llegue un correo cada vez que se suba o se comente una issue con esta label.

Traté de buscar en google una forma de hacer esto, pero no la encontré :(. Me ayudan pls? <3

Gracias! :)

**Comment by jfbahamondes** [comment]
Si mal no equivoco, en la barra de items de al lado puedes darle a la opción de suscribirte para las notificaciones. 
![cap1](https://user-images.githubusercontent.com/17971547/40154793-30d60eee-595e-11e8-9c6a-ae2560e1bcb1.JPG)
Avísame si es que no te sirve para averiguar más acerca de esto.

**Comment by emeiese** [comment]
@jfbahamondes Si me había fijado. Esa no me sirve ya que me suscribe a todas las issues, o a ninguna ajajaj. (En mi caso, la tengo configurada para que me suscriba en aquellas en las que he sido mencionada.
Lo que me interesa especificamente es suscribirme a cualquier issue que posea la etiqueta "importante"

**Comment by jfbahamondes** [comment]
@emeiese Que extraño. A mi me deja suscribirme individualmente a todas a issues. Entonces, supongo que podrías hacer esto en las issues importartes y te llegarían las notificaciones. 🤔

**Comment by emeiese** [comment]
Si! Pero estoy buscando una manera de que se haga automático ajajaj. Todo el tiempo se están creando issues **importantes**, y la idea sería no tener que revisar para poder suscribirme cada vez que se haga una ajajaj sino que se haga solo con cualquier issue que tenga la etiqueta importante :)

**Comment by nebil** [comment]
Según entiendo, @emeiese, GitHub no ofrece una manera sencilla de hacer eso. De hecho, si miras [este repositorio](https://github.com/isaacs/github), que tiene _feature requests_ —sugerencia de funcionalidades deseables— propuestos por personas hacia GitHub, podrás notar que alguien [pide lo mismo que tú](https://github.com/isaacs/github/issues/1172). :neutral_face:

Sin embargo, no todo está perdido: podrías resolver tu problema con Python y algo de tiempo. GitHub ofrece una [API](https://developer.github.com/v3/issues/#list-issues-for-a-repository), en donde puedes obtener información acerca de los _issues_ de un repositorio en particular. Lamentablemente, en la última clase, veremos este tema. Bueno, al menos supongo que esto servirá como motivación para aprender esta materia. :sweat_smile:

**Comment by pahaeussler** [comment]
Hola, yo hice algo similar a lo que pides. Puse suscribirme a todos los mensajes, no obstante en las configuraciones de gmail puse que me filtre los mail de GitHub en una carpeta aparte. Luego de todos los mail gmail filtra automáticamente los mails importantes en otra carpeta. Espero que te sirva.
