### ISSUE TITLE
Mostrar estado de Magizoólogo: Aprovación y Licencia

### ISSUE THREAD

**Issue by furcelay** [IIC2233/syllabus#522]
Hola!
Al mostrar el estado del Magizoólogo a través del menú DCC ¿se debe actualizar la aprovación y el estado de licencia considerando que esta pudo cambiar según las acciónes del usuario (sanar o recuperar criaturas)?¿O esta información solo se actualiza al pasar de día?

Gracias!

**Comment by matiasmasjuan** [comment]
Hola @furcelay !

Esta pregunta es muy similar a las que se realizaron en las issues #417 y en la #274 .

Ojalá que en ellos puedas encontrar una respuesta a tu pregunta.

Suerte! 😄

**Comment by furcelay** [comment]
¡Gracias por la respuesta! 
Pero mi pregunta va hacia el cálculo de la aprobación del Magizoólogo mas que a actualizar los archivos...
Mi duda surge porque en el enunciado aparece: "Calcular nivel de aprobación: El DCC **revisa todos los días el nivel de desempeño** del Magizoólogo"
Pero en el método Mostrar estado de Magizoólogo y DDCriaturas dice que se debe mostrar el **nivel de aprovación actual**.
Reformulando mi pregunta sería si este nivel de aprovación actual corresponde al que se calculó en el último paso de día o este se calcula al instante de elegir la opción de Mostrar estado de Magizoólogo.
Y si fuese el último caso entonces un Magizoólogo podría recuperar su licencia sin necesidad de pasar al día siguiente, ¿esto estaría bien?

Gracias!

**Comment by matiasmasjuan** [comment]
Dado que si **tiene licencia o no** sólo se efectúa al momento de *pasar al día siguiente*, puedes asumir que en la opción del **DCC: *Mostrar estado del Magizoólogo***, deberá tomar el valor de la **licencia** desde el último momento en que se realizó la función para realizarlo (en este caso, la última vez que *pasó al día siguiente*). Con respecto al **nivel de aprobación** actual, dado que es un poco *ambiguo* la expresión y puede causar confusión, queda a tu criterio si deseas calcular el **nivel de aprobación** nuevamente, o utilizar el que se realizó la última vez en el método *pasar al día siguiente* (recuerda agregarlo a supuestos en tu README). Sin embargo, si decides calcular nuevamente el nivel de aprobación, el valor de aprobación del Magizoologo no debe ser reemplazado, ya que debe conservar el que tuvo la última vez cuando se *pasó al día siguiente*.

Espero haber respondido a tu pregunta, y mucho éxito con la tarea! 😄

**Comment by furcelay** [comment]
Muchas gracias, eso resuelve mis dudas
