### ISSUE TITLE
Como manipular archivos csv?

### ISSUE THREAD

**Issue by enriquerussi** [IIC2233/syllabus#522]
Hola, donde puedo ver como abrir y manipular archivos csv.

**Comment by baosse** [comment]
Holaa Enrique! 
En los contenidos de la semana 0 aparece como puedes abrir los archivos y manipularlos. Aparece en el archivo de 'Paths y rutas dentro del sistema'.
Espero que esto te sirva! 
Mucho éxito con tu tarea✨
