### ISSUE TITLE
QTimers, QThreads y ejemplo

### ISSUE THREAD

**Issue by hanavarrete** [IIC2233/Syllabus#522]
Hola! Para guiarlos un poco en el manejo de distintos eventos de manera asíncrona les dejo esta issue creada un semestre anterior que aclara el uso y diferencias de los QThreads y QTimers (que ya saben que son porque ya empezaron la tarea(?)) y que en particular, me ayudó bastante aclarando los conceptos en la creación de mi T05:
BONUS: Además, en la carpeta de la T05 agregamos un código que muestra un manejo de señales para mover una imagen y un ejemplo de thread. Espero que les sirva! 👍 

### QThreads:
Los Qthreads siguen el mismo comportamiento que los Threads que fueron enseñados en el ramo, por lo que no debería presentarles mayor complicación aplicarlos en su tarea. Pero que pasa si queremos utilizarlos para una acción que sabemos que se va a repetir constantemente ? Podríamos implementar algo así en el Qthread
```python
def run(self):
       while True:
              # Lo que quiero que el QThread haga en cada iteración
              time.sleep(0.1) # Muy importante para que su interfaz no se quede pegada, el valor es ajustable
```
* ¿Con esto que tenemos ?: Un QThread que repite una acción una y otra vez.
* ¿Problemas?: Si.
* ¿Cuáles? Como detenemos este Qthread.
En general detener (matar) un thread es una [mala practica](https://stackoverflow.com/questions/323972/is-there-any-way-to-kill-a-thread-in-python), la idea es que un Thread se inicie, cumpla su objetivo y muera al terminarlo, no que lo tengamos que detener por nuestra cuenta (mas detalles en el link, es interesante y útil)
Entonces siguiendo esta misma lógica estamos abusando del run del Qthread con un vacío legal.
* ¿Puedo detenerlo con break ? Si, hay casos donde alumnos usan Qthreads en toda su tarea y no tienen problemas, como experiencia propia, empezar a matar Qthreads a diestra y siniestra con este método no escalo bien.

### Qtimers
Otra forma de realizar lo que hacíamos con Qthreads es con Qtimers.
* ¿Cuál es la ventaja que tienen estos sobre Qthreads?:
Qtimers esta pensado para que se repita una y otra vez lo que contiene su run sin necesidad de utilizar un while, recibe como parámetro al inicializarlo el tiempo cada cuanto se debe ejecutar y además posee un método stop para poder detenerlo "legalmente". Si, se ve más limpio en general que usar Qthreads, pero no asegura que su programa vaya a ser perfecto ni vaya a sufrir problemas de lag o caídas de interfaz, eso ya va en la programación de cada uno.

## Recomendación final
Son libres de usar ambos en sus tareas, los 2 son útiles y pueden tener una tarea 100% funcional ya sea con uno, el otro o ambos. Por ejemplo para objetos que existan en muchas cantidades y sea difícil controlar cuando interrumpirlos puede ser mas útil utilizar un Qtimer con ellos, pero para objetos que permanecen constantes en el escenario o que son más fáciles de controlar un Qthread es una buena opción.
Experimenten ! Vean con cual les anda mejor, con cual es mas eficiente su tarea y averigüen mas por su cuenta, siempre es útil leer un poco antes de lanzarse a usarlo algo, y no olviden siempre comentar en el README este tipo de decisiones y porque escogieron lo que escogieron.

**Comment by yoavnavon** [comment]
Algun ejemplo de como usar los QTimers? Tengo el mismo problema que se menciona en #541, y estaba pensando en implementar QTimers para ver si se arreglaba, pero viendo las documentaciones, entiendo que se usa de maneras distintas, y no es solo sobrescribir el run().  He visto bastante lineas como esta:
`self.timer = QtCore.QTimer()
 self.timer.connect(self.timer, QtCore.SIGNAL("timeout()")
 self.timer.start(1000)`

No entiendo como remplazar un QThread por el QTimer, ojala puedan ayudarme, saludos!

**Comment by Hernan4444** [comment]
@yoavnavon las lineas que has visto es una de las principales diferencias. A continuacion te pongo un ejemplo de un un objeto funcionando como QTimer
```
class Ejemplo(QTimer)
    def __init__(self):
        super().__init__()
        self.timeout.connect(self.metodo)
        self.start(1000) --> El run se ejecutará cada 1000 milisegundos

    def metodo(self):
        print("Ejecutando un QTimer)
```

Como puedes ver, la diferencia radica en que el método del QTimer no posee un while porque cada vez que pasa los 1000 milisegundos se ejecuta este mientras que en un QThread se utiliza un time.sleep dentro de un while para ejecutar un loop del run cada cierto tiempo.

Saludos

**Comment by yoavnavon** [comment]
Gracias por la rapida respuesta!!

**Comment by Veenty** [comment]
@Hernan4444 cuando intento correr tu codigo me sale el siguiente error D:

QObject::startTimer: Timers can only be used with threads started with QThread

**Comment by Hernan4444** [comment]
@Veenty estás el QTimer de la siguiente forma?:

```
app = QApplication(sys.argv)
a = Ejemplo()
sys.exit(app.exec_())
```

o estás haciendo `a = Ejemplo()` sin crear el QApplication?

**Comment by Hernan4444** [comment]
@Veenty objetos de PyQt deben trabajar en un entorno propio de PyQt, con instanciar el QApplication se prepara la librería para todos los siguientes objetos que vas a utilizar (no solamente QTimers) de PyQt5, si quieres profundizar en mas te sugiero investigar sobre la librería de QApplication

Saludos!!
