### ISSUE TITLE
Problema pip

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#522]
Hola, estaba tratando de instalar pyqt4 para probar un ejemplo de internet, sin embargo me sale que ni python ni pip se reconocen:

![image](https://user-images.githubusercontent.com/47841749/59530935-cc095f80-8eb2-11e9-818c-f4cf3fe002dd.png)

No se bien a que se debe, ya que antes si me funcionaron cuando instalé pyqt5 para la T02

**Comment by csantiagopaz** [comment]
No soy ayudante, pero intenté descargar pyqt4 con el pip también, y leyendo
en internet (stackoverflow) vi que no se puede más, hay que descargar
manualmente( yo puedo estar equivocado)

Em sex, 14 de jun de 2019 14:44, VicenteMerino <notifications@github.com>
escreveu:

**Comment by VicenteMerino** [comment]
Gracias, pero de todas formas mi problema va más que nada a que no se reconocen los comando pip y python3 een la consola.

**Comment by Arcoirisky** [comment]
Cuando instalaste Python lo agregaste al path? O: Generalmente ese es siempre el problema :c

**Comment by VicenteMerino** [comment]
Hola, si lo agregué al path. Me acabo de dar cuenta que usando python en vez de python3 si funciona, sin embargo el comando pip y pip3 no.

**Comment by Arcoirisky** [comment]
Podrías intentar lo que dice este [Link](https://tecnonucleous.com/2018/01/28/como-instalar-pip-para-python-en-windows-mac-y-linux/).

Sino un whl te puede sacar del apuro https://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by VicenteMerino** [comment]
Gracias, me funcionó con lo primero.
