### ISSUE TITLE
Consulta sobre uso de librería

### ISSUE THREAD

**Issue by AlonsoZamorano** [IIC2233/syllabus#522]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Buenas tardes, quería consultar sobre el **uso de la librería ```imageio```** que sirve para pasar imagenes a formato gif y viceversa. Mi duda salió de que al buscar sobre como hacer este proceso la mayoría de usuarios utilizaban la librería ```glob``` que aparece como prohibida, por lo que pensé en consultar primero. Muchas gracias.

**Comment by JadrinaDA** [comment]
Hola! Pregunta por favor en la issue "Librerías permitidas, no permitidas y malas prácticas T2 #473" para tener todas estas dudas en un mismo lugar. Ahí te responderán con la información pertinente.

**Comment by AlonsoZamorano** [comment]
Perfecto! Eso haré
