### ISSUE TITLE
operador and

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#523]
Imaginemos que tenemos dos funciones que devuelven True o False de la siguiente forma: 
if funct() and funct2() .
¿Qué hace Python, si ambas retornan False?. Es decir, llama a la primera y dice "como la primera es falsa no necesito llamar a la segunda" o "de todas formas, por protocolo, llamo a la segunda"?

**Comment by vijuarez** [comment]
Hola!

El operador `and` hace "cortocircuito", es decir, si ya sabe que el primer argumento es falso no se molestara en evaluar el segundo. Esto es útil si una de las funciones tarda notablemente más que la otra, pues puedes poner la más rápida primero y dejas la posibilidad de no tener que evaluar la segunda.

Puedes probarlo tu mismo con `print(False and 1/0)`. Esta línea de código no levanta ninguna excepción, ya que nunca evalúa el 1/0.

Saludos!

**Comment by movaldivia** [comment]
@vijuarez  gran idea el  **print(False and 1/0)**. Gracias !

**Comment by nebil** [comment]
¡Muy buen ejemplo, @vijuarez! :grinning:

Quiero extender el aporte de Vicente, para mencionar que esta evaluación de cortocircuito (en inglés, [_short-circuit evaluation_](https://en.wikipedia.org/wiki/Short-circuit_evaluation)) es un _idiom_ que aparece no sólo en Python, sino en muchísimos lenguajes de programación. Por otra parte, es importante notar que funciona de forma análoga con el operador `or`. Más concretamente, si tenemos dos expresiones booleanas, y la primera se evalúa como `True`, entonces el intérprete no analizará el resultado de la segunda expresión, puesto que el resultado devolverá `True` de todas formas.

Además, es interesante observar que esta lógica podemos extenderla a más de dos expresiones booleanas. Si tenemos una serie de condiciones yuxtapuestas con operadores `and`, entonces la evaluación se detendrá cuando encuentre el primer `False`. De forma análoga, ocurre lo mismo con `or`: la evaluación seguirá hasta evaluar el primer `True`. Y esto es lo que ocurre cuando usamos el siguiente par de _built-ins_ ofrecidos por Python: [`all`](https://docs.python.org/3/library/functions.html#all) y [`any`](https://docs.python.org/3/library/functions.html#any) respectivamente —que son funciones bastante útiles, por cierto. :snake:

Y ahora, _terminaré_ esta respuesta con un típico caso de uso de un _short-circuit evaluation_. Supongamos que tenemos una función que, leyendo desde un archivo, intenta obtener cuál es el navegador preferido de un usuario en particular. Y se vería algo así,

```python
def get_favorite_browser(username):
    # Por favor, amigue lector: imagine que esta función sí existe,
    # y no son sólo cinco líneas de comentarios altamente verbosos.

    # Dado un nombre de usuario, devuelve su navegador preferido.
    # Además, si algo llega a fallar (e.g. aquel dato no existe),
    # entonces esta función retornará None.
    pass
```

Ahora, supongamos que queremos asignar el resultado de esta función a una variable; sin embargo, en vez de asignar `None`, nos gustaría tener un valor por defecto. En este caso, creo que estaremos de acuerdo que un valor por defecto razonable es [Firefox](https://www.mozilla.org/en-US/firefox/new/): es el navegador favorito de todo el mundo[\*](#note). 

Una forma de lograr esto con Python, podría ser…

```python
browser = get_favorite_browser("stephichau")  # probablemente, "Internet Explorer 6".
if not browser:
    browser = "Firefox"
```

Sin embargo, podemos aplicar la evaluación de cortocircuito a nuestro favor. :electric_plug:

```python
browser = get_favorite_browser("stephichau") or "Firefox"
```

Mmm… pitonesco. :drooling_face:

---

<a name='note'>\*</a> El problema es que mucha gente todavía no lo sabe. :fox_face:
