### ISSUE TITLE
Duda Front_end y Back_end

### ISSUE THREAD

**Issue by JoseValencia125** [IIC2233/Syllabus#523]
Estoy un poco confundido en que cosa debe ir en cada uno. ¿Se supone que en el front debe ir todo lo de QMainWindow y en el back todo lo funcional y los QThreads? De ser así, si recibo en el Front con un "eventQKeyEvent" que el usuario apretó "w", este lo manda al back ¿Es el back el que mueve al objeto? ¿O solo le retorna por ejemplo cuanto moverse, pero es el front el que tiene el .move del objeto?

**Comment by Hernan4444** [comment]
@JoseValencia125 tal como dices, el Frontend tiene el QMainWindows y todo objeto gráfico mientras que el Backend tiene lo funcional y los QThreads. Y de nuevo tal como dices, el Backend se encarga de mover el objeto (actualiza su posición) y le manda una señal al Frontend indicando su nueva posición o el delta_x y delta_y, eso depende de tu código.

Saludos!!!

**Comment by JoseValencia125** [comment]
Perfecto! muchas gracias! ¿Entonces no hay problema por ejemplo, que en el back_end la clase personaje tenga un atributo self.imagen que sea un Qlabel?

**Comment by Hernan4444** [comment]
Lo que quieres hacer no es 100% adecuado (lo de dejarlo en el Frontend es una opción mejor) pero para efectos de esta tarea puedes hacerlo  sin tener descuento.

Saludos

**Comment by JoseValencia125** [comment]
comprendo, gracias!
