### ISSUE TITLE
Duda boton salir

### ISSUE THREAD

**Issue by mjadresic** [IIC2233/syllabus#523]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Que deberia hacer el boton salir de la ventana de juego? Cerrar todo, llevarme al menu de inicio, ventana post ronda...?

**Comment by valerianazal** [comment]
Hola @mjadresic ! La función de ese botón es **salir del juego**, es decir, **cerrar el programa**.

**Comment by Piolawa** [comment]
@valerianazal Hola!, me surgió una duda: al usar el botón salir en la ventana de juego, se guarda lo que llevaba para en un futuro mostrarlo en la ventana de ranking o se pierde lo que llevaba?

**Comment by valerianazal** [comment]
Hola @Piolawa ! No se guardan los datos de la partida.
Mucho éxito!

**Comment by valerianazal** [comment]
Hola @Piolawa ! No se guardan los datos de la partida.
Mucho éxito!✨✨
