### ISSUE TITLE
Objetos que se contienen mutuamente

### ISSUE THREAD

**Issue by tqmbanados** [IIC2233/syllabus#523]
Hola :)

¿Es posible/recomendable/buena practica que dos instancias se tengan entre sus atributos mutuamente? Por ejemplo, un objeto de clase A tiene un atributo que contiene una instancia de la clase B, y esa misma instancia clase B tiene un atributo que contiene la mencionada clase A. (Algo así como agregación/composición en doble sentido).

Gracias!

**Comment by itmunoz** [comment]
Hola! Esto no es algo que se haría normalmente (hasta me arriesgaría decir que podría haber algún error). Lo correcto sería que solamente un objeto sea una instancia de otro, y ojalá evitar este tipo de técnicas cíclicas.
