### ISSUE TITLE
Bonus Peleas: valor de la apuesta

### ISSUE THREAD

**Issue by furcelay** [IIC2233/syllabus#523]
Hola!
¿El valor de la apuesta es un número fijo o el usuario puede dar un input de cuanto desea apostar?

Gracias!

**Comment by matiasmasjuan** [comment]
Hola @furcelay !

Tal como dice el enunciado:

![bonus apuesta](https://user-images.githubusercontent.com/48495638/79404332-67e67a80-7f5f-11ea-9f60-ab423d440579.PNG)

Por lo tanto, el valor de la apuesta es un **parámetro** contenido en el archivo *parametros.py* y corresponde a un valor fijo de 30 *SICKLES*.

Saludos y mucho éxito con la tarea! 😄

**Comment by furcelay** [comment]
Muchas gracias!
Pensé que este valor podría ser la apuesta mínima.
