### ISSUE TITLE
Duda load y dump

### ISSUE THREAD

**Issue by mfocqueteau** [IIC2233/syllabus#523]
En json, ¿los archivos se leen/guardan siempre como archivos de texto ('r' y 'w') o pueden ser binarios?

Lo mismo para pickle pero al revés: ¿se usa siempre 'rb' y 'wb'?

**Comment by jmwielandt** [comment]
Hola!

Tu duda apunta a la materia de manejo de bytes, que se verá en unas semanas más, sin embargo, te explico.

Todo string se codifica como una secuencia de bytes, que son la unidad básica de almacenamiento de la información en los computadores, un byte se compone de 8 bits, por lo que puede tomar valores numéricos desde 0 (`0b00000000`) hasta 255 (`0b11111111`) (el prefijo `0b` es para indicar que está en binario).

Para representar más de 255 caracteres distintos surgen los `encodings`, que es el cómo codificamos los caracteres que usamos en una cierta secuencia de bytes. Esto permite que utf-8, por ejemplo, pueda usar la secuencia de bytes con valores `239`, `189` y `140` para representar el caracter `ｌ`, que se obtiene usando `chr(65356)`.

Ahora bien, cuando abres un archivo, los modos de texto son un atajo para procesar el contenido del archivo como si fuera texto, pudiendo en python darle un cierto encoding (en otros lenguajes no se puede).

JSON es un formato de serialización en forma de texto, por lo que sí, siempre debes usar los modos de texto para los archivos, mientras que pickle lo que hace es transformar tus objetos en algo **similar** al bytecode al que transforma python sus objetos en ejecución o al importar un módulo (para eso está `marshal`). De hecho, puedes serializar incluso una función con pickle. Te dejo un ejemplo:

![image](https://user-images.githubusercontent.com/37153467/67590343-310e7500-f731-11e9-9842-fc7c412fd80e.png)

Como puedes ver en la imagen, al serializar algo con pickle te devuelve un "string" pero con una b adelante, eso significa que es en realidad una cadena de bytes, por lo que sí, para pickle debes usar los modos binarios para manejar los archivos.


Espero que con esta explicación entiendas más el por qué de un modo u otro y sus diferencias ^^
Saludos!

**Comment by mfocqueteau** [comment]
Gracias por la respuesta tan rápida!
