### ISSUE TITLE
Problema clientes paralelos

### ISSUE THREAD

**Issue by aigarrido** [IIC2233/syllabus#523]
Hola!
Al tratar de iniciar varios clientes en pycharm sale una ventana que dice "'Cliente' is not allowed to run in parallel." y me da solamente una opción para cerrar y reabrir, que puedo hacer?

**Comment by IchottMano** [comment]
Hola!

Una opción (que es lo que recomiendo hacer) es la de intentar correr los multiples clientes y el servidor en mútiples consolas de comandos, en vez de intentar hacerlo vía PyCharm.
Para esto puedes usar, entre otras cosas, el cmd de windows, powershell o una ventana de bash en caso de que no estés usando windows.

[Como abrir una terminal en Windows](https://www.howtogeek.com/235101/10-ways-to-open-the-command-prompt-in-windows-10/)
[Como abrir una terminal en Ubuntu](https://www.wikihow.com/Open-a-Terminal-Window-in-Ubuntu)
[Como abrir una terminal en Mac](https://macpaw.com/how-to/use-terminal-on-mac)

Saludos!

**Comment by aigarrido** [comment]
Finalmente solucioné el problema cambiando la configuración de pycharm (una opción llamada allow running en parallel por si a a alguien le sirve), pero muchas gracias por responder tan rápido :)
