### ISSUE TITLE
Decisiones si el parque está cerrado

### ISSUE THREAD

**Issue by beayancan** [IIC2233/Syllabus#524]
Nebilandia solo opera desde las 10:00 hasta las 19:00, con lo cual en el caso de que un adulto y los niños se encuentren en la fila de alguna atracción digamos a las 18:58 y no alcanzan a subir a la atracción ¿deben esperar (muy pacientemente) en la fila hasta el próximo día? o ¿debo suponer que todas las filas se vacían y que todos los adultos tomen una nueva decisión al día siguiente?

**Comment by Hernan4444** [comment]
Hola, recuerda uno de los objetivos del curso:
![image](https://user-images.githubusercontent.com/15641721/40152842-f17c1512-5954-11e8-91c3-4846cd09d59b.png)

Creo que con eso queda claro que no puedo decirte cual es la opción que esperamos porque ya es algo que queda a tu criterio.

Saludos ✌️
