### ISSUE TITLE
Duda sobre uso de Qthreads en relación a backend-frontend

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#524]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### No identifico bien si un Qthread que controla el movimiento de un label debe ir en frontend o backend

Por un lado, el Qthread manipularía un label, y pienso que no seria incorrecto usarlo en el frontend, pero como el Qthread en si no es algo grafico, no se si es adecuado.

**Comment by clementevalladares** [comment]
Hola @Pabloski100, para separar correctamente backend de frontend debes hacer que solo lo visual de tu programa sea manipulado en el frontend, es decir, actualizar labels, ventanas, puntajes, vida, etc... según la información que el backend le transmita a través de señales. 
En relación a tu pregunta, si tienes un label que se mueve a través del mapa, la información de la posición de este y el resto de objetos en el mapa debería estar almacenada y ser procesada en el backend. Una vez hecho esto, el backend deberá emitir una señal y ser el frontend el encargado de mover al QLabel a la nueva posición que el backend le entregó.
Por lo tanto, el QThread que **procesa** el movimiento debe ir en el **backend**, pero el Widget que **actualiza la posición del QLabel en pantalla** debe encontrarse en el **frontend**.
Espero que haya quedado claro.
