### ISSUE TITLE
contenidos

### ISSUE THREAD

**Issue by camaruri** [IIC2233/syllabus#524]
Hola. Los contenidos que nos saltamos estas semanas es necesario estudiárselos igual para entender más la materia que viene en la próxima AC sumativa y luego la tarea?
O podemos dejar esa materia para estudiarla después de la T03.
Gracias

**Comment by entamburini** [comment]
Hola @camaruri!

Dada la naturaleza del curso, cada contenido es aditivo para la materia que le sigue. En este caso en particular, *es necesario* que tengan conocimiento de la materia previa de bytes y serialización porque son parte importante para networking y en la T03 se verán esos contenidos :eyes: 

Que estés bien! :D
