### ISSUE TITLE
Como mover un objeto hacia otro. (pyqt5)

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#524]
Hola!, una consulta (se que es googleable pero no he encontrado respuesta), si tengo la posición de dos objetos dentro de un window en pyqt, que forma tengo de hacer que uno se mueva en la dirección del otro? (por ejemplo, moverse en dirección al mouse, o en dirección a un enemigo) 

Estaba pensando usar el comando `move(x, y)` para ir actualizando la posición de a poco pero eso presenta el problema de como cambiar los valores cuando los dos objetos estan en diagonal uno al otro.

De ante mano, muchas gracias!

**Comment by DiegoAndai** [comment]
Hola!, podrías desarrollar un poco mas tu pregunta? `move()` es el método a utilizar. PyQt tiene implementado mouseTracking para obtener la posición del cursor, y si es un enemigo también podrías conseguir su posición desde la entidad que lo maneje, no entiendo qué problema se presenta al estar en diagonal.

**Comment by KnowYourselves** [comment]
Gracias por la respuesta rápida! Si, lo de las posiciones ya lo tengo claro, mi problema es que si las dos posiciones estan en diagonal al usar `move()` el movimiento tiene que descomponerse en un movimiento en x e y, para ver esto intente utilizar trigonometría, pero no me resulto de ninguna forma o manera, a eso me refiero, `move()` no es óptimo para mover en linea recta dos objetos cuando estos estan en diagonal

**Comment by sebacruzd** [comment]
Hola,

Te recomiendo utilizar ambas posiciones, la de tu campeón y la del enemigo a atacar/ posición del mouse.
Con esto puedes crear un vector desde el campeón al objetivo y luego normalizarlo, para que eso sea tu vector desplazamiento. Ojo con cuando está a distancia 0. No debería ser tan difícil lo de trigonometría que mencionas.

Saludos!

**Comment by DiegoAndai** [comment]
@KnowYourselves Puedes ocupar todos los recursos de cálculo en dos dimensiones. La forma de obtener un vector entre dos puntos es restarle al punto de llegada el punto de partida, por ejemplo, para llegar AL punto (3, 1) DESDE el punto (1, 1) el vector necesario es (3 - 1, 1 - 1) = (2, 0), esto es, una linea recta hacia la derecha. (2, 0) entonces sería lo que debes sumarle al origen para llegar al destino.

![image](https://cloud.githubusercontent.com/assets/16889233/26480491/175ff19c-41a8-11e7-9494-8ee36d7c1459.png)

La forma de trabajar vectores en python exactamente es ocupar tuplas, tal como lo harías en cálculo. Así, todas las propiedades que conoces se aplican.

**Comment by sebacruzd** [comment]
@KnowYourselves no es una class Vector, ni nada por el estilo, sino que solamente una tupla/lista (como te acomode), para que puedas hacer los cálculos pertinentes a cuánto se debería desplazar en cada dirección.

Recuerdo también que cuando hice eso en mi Tarea 5 tuve un par de complicaciones, pero cuando lo logré me di cuenta que no era tan complicado, con paciencia debería salir, ánimo!

**Comment by KnowYourselves** [comment]
Muchísimas gracias!, entre la idea de los vectores y el ejemplo me salió perfect!, que tengan una linda noche!
