### ISSUE TITLE
Pasar de satisfecha a hambrienta según cantidad de días

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#524]
Hola!
Primero quiero decir que no encontré esta misma issue.
Tengo la duda de los siguiente:
En el enunciado se indica que para cada distinto tipo de criatura, se evalua la cantidad de días que llevan sin comer y sucede que cambia su nivel de hambre, pero por ejemplo para el Augurey esto sucede si llevan 3 días sin comer, pero qué pasa si lleva más de 3 días? igual cambia su nivel de hambre?
Gracias!

**Comment by moquezada** [comment]
Hola @Camila-sty!

No entiendo muy bien tu pregunta :cry: ¿Te refieres a que si un Augurey lleva 4 días sin comer, este dejaría de estar hambriento porque en el enunciado se indica que **pasará de satisfecho a hambriento si no come en 3 días seguidos**? De ser ese el caso, el Augurey seguirá hambriento a menos de que lo alimentes 😄 Avísame si sigues con la duda. 

Suerte!

**Comment by Camila-sty** [comment]
Es que para el Augurey, si lleva 3 días sin comer cambia su nivel de hambre, pero si llevas más días igual cambia?

**Comment by moquezada** [comment]
@Camila-sty , si una criatura lleva más días sin comer de los indicados para que pase de satisfecha a hambrienta, esta debe estar hambrienta. Esto es porque al menos llevaría la cantidad mínima que se especifica, cumpliendo así con la condición de hambrienta :)
