### ISSUE TITLE
Cantidad de dias semestre academico

### ISSUE THREAD

**Issue by ajahr95** [IIC2233/Syllabus#524]
¿Cuánto se considera, en cantidad de días, que dura el semestre académico?

**Comment by ifcarrera** [comment]
Hola, el semestre académico dura 4 meses, es decir, 120 días; pero debes tener en cuenta que eso incluye los fines de semana, que para efectos de la simulación no deberían considerarse.
Saludos

**Comment by fedetaladriz** [comment]
@ifcarrera Tiene que durar **exactamente** 120 dias? Pregunto porque estoy utilizando la librería datetime para manejar el tiempo, la que considera meses de 30 y 31 dias.

**Comment by ifcarrera** [comment]
Hola! 
No hay problema con que los consideres de 30 y 31 días mientras ocupes librerías permitidas.
Saludos

**Comment by Jiparavich** [comment]
@ifcarrera  considerar 120 días- dias de findesemana, i.e , 106 días. (asumiendo meses de 30 días y que se parte un día lunes) ?
