### ISSUE TITLE
Ocupar QLabel como clase heredada

### ISSUE THREAD

**Issue by VichoAburto** [IIC2233/syllabus#525]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! 

Una consulta, he estado tratando de crear un clase que herede de una clase que hereda de clases abstractas y QLabel, y me gustaría poder usar la primera clase como un objeto QLabel dentro de mi ventana, pero no me deja utilizar los método de QLabel.

Explicado en forma de código:

`Class A(QLabel, ABC)`
.........`def __init__(self, position):`
..................`super().__init__()`
..................`self.x() = position[0]`.............# Estos métodos no me deja usar
..................`self.y() = position[1]`

`Class B(A):`
.........`def __init__(self):`
..................`position = [60, 50]`
..................`super().__init__(position)`

Y tengo instanciada la clase B en el `__init__` de mi clase Ventana

Se puede hacer esto o no? Porque lo más parecido que encontré, fue lo que hicieron para la AF4, sin embargo no caché bien porqué la ventana combate sería un QLabel, y no una ventana como tal (QMainWindow).

**Comment by MatiasDuhalde** [comment]
Hola @VichoAburto !

En primer lugar, según tu código, estás intentando hacer una asignación a un llamado de una función (es decir, hacer `mi_funcion() = algo`), lo cual no es correcto ni soportado por python. Si quieres manipular la posición de cualquier widget, simplemente basta con usar el método `move` o `setGeometry`, que debería quedar disponible al hacer la herencia. Te quedaría algo como `self.move(*position)` en el `__init__` de A.

También, puedo notar que tu herencia está un poco complicada, debido a que la clase A hereda al mismo tiempo de `ABC` y `QLabel`, lo cual puede causar conflictos en las superclases. Te recomiendo intentar probar el posicionamiento haciendo que A herede solamente de QLabel, para descartar conflictos que pueda tener QLabel con ABC.

Éxito, y comenta en esta issue si sigues con problemas! :sparkles:

**Comment by VichoAburto** [comment]
Yaa buenísima @MatiasDuhalde, gracias.

Voy a cachar y cualquier cosa comento de nuevo.

**Comment by VichoAburto** [comment]
Hola @MatiasDuhalde !

Sabes que hice lo que me dijiste, y me corrió el código. Sin embargo, mi problema ahora es que el personaje se crea como una ventana aparte, y no dentro de la misma ventana.

Hay alguna forma de que al momento de crear una clase que herede de QLabel, cualquier instancia de esa clase sea incluida dentro de la alguna ventana específica?

**Comment by MatiasDuhalde** [comment]
Hola @VichoAburto !

Cuando instancias un elemento como QWidgets o QLabels, generalmente se le proporciona el "parent" como argumento. Toma como ejemplo lo que sale en los contenidos, específicamente en [este notebook](https://github.com/IIC2233/contenidos/blob/main/semana-06/2-elementos-gr%C3%A1ficos-b%C3%A1sicos.ipynb). Cuando se crea un elemento como un QLabel en el `__init__` o en `init_gui` (que en realidad es correrlo indirectamente en `__init__`), se le proporcionan dos argumentos: 

```python
self.label1 = QLabel('Texto:', self)
```

Como podrás notar, se le entrega un texto (que para un QLabel corresponde al texto que contendrá), y también se le pasa `self`. Este argumento es el "parent" que se le asignará al QLabel. Dado que le pasamos `self`, dejamos como a la instancia de la clase en sí (que en el ejemplo de los contenidos sería un QWidget), como el parent del QLabel recién creado. De esta manera, el QLabel estará de alguna manera "contenido" dentro de su elemento padre, o en otras palabras, estará dentro de la ventana. 

En tu caso, como estás trabajando con una clase custom, deberías encargarte en el init de esta nueva clase de pasarle a la clase superior (con super) el argumento "parent", para que se asigne correctamente cuando la crees. Asimismo, también debes asegurarte de pasarle un argumento parent cada vez que instancies un elemento de tu clase custom. Entoces, al instanciarla, te debería quedar algo así:

```python
# init de clase custom
class MiClaseCustom:
    def __init__(self, param1, param2, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.param1 = param1
        self.param2 = param2


# otro lado del programa cuando instanciemos a la clase custom
# por ejemplo, dentro del `init_gui` de una ventana (QWidget/QMainWindow)
self.mi_instancia_custom = MiClaseCustom(param1, param2, self)
```





Ojalá esto te de alguna idea de como continuar!

**Comment by VichoAburto** [comment]
Buenísima @MatiasDuhalde !

Ahí me funcionó. Muchas graciasss.

Si en vez de QLabel, decidira usar QObject, sería lo mismo? o ahí cambia?

**Comment by MatiasDuhalde** [comment]
Hola de nuevo @VichoAburto !

Sí, QObject funciona de manera similar en ese sentido, también tiene un argumento en su constructor (`__init__`) que puede recibir a un objeto parent. 

Sin embargo ten en cuenta que para elementos visuales, idealmente debes ocupar una clase más especializada que QObject, como QWidget o QLabel, debido a que estas traen métodos que permiten manejar más casos de uso, como acceder a keyPressEvents, closeEvents, show, hide, etc.

QObject generamente se reserva para hacer clases que no son parte directa de la interfaz gráfica (no representan elementos visuales), pero si funcionan como canal para interactuar con estas. Por ejemplo, se puede definir una clase que herede de QObject, que sirva como una conexión entre el Backend y el Frontend, o incluso se puede definir como el backend mismo, ya que cosas como las señales o slots no pueden manejarse desde una clase básica, necesita los métodos que tiene QObject, y se pueden obtener con herencia.

Salu2 :cowboy_hat_face:

**Comment by VichoAburto** [comment]
Yaa buenísima!

Te pasaste. Gracias por toda la ayuda 😉
