### ISSUE TITLE
Error QPixmap::scaled: Pixmap is a null pixmap

### ISSUE THREAD

**Issue by niguzman** [IIC2233/syllabus#525]
Hola, 
Estoy recibiendo el sgte error y no entiendo por qué :C 
![Captura](https://user-images.githubusercontent.com/48304981/59541450-552e8f80-8ecf-11e9-97fe-d2ed09490cf2.PNG)

Traté dándole un path en la línea 80 del frontend porque había leído que a veces sale cuando se le entrega al QPixmap un path vacío pero sigue apareciendo

PD: lo raro es que imprime el error pero todo se ejecuta sin problema

**Comment by KnowYourselves** [comment]
Hola @niguzman!

El error `QPixmap::scaled: Pixmap is a null pixmap` ocurre cuando inicias un QPixmap con un path que no existe. En tu caso lo que sucede es que cuando inicializas tu Cliente inicializas tu Ventana de Inicia, luego inicializas la Ventana de Salas, luego en la Ventana de Salas llamas automaticamente a tu proceso de cargar una foto, especificamente, la linea 203. Cuando llegas aquí, `self.path` sigue siendo un string vacío, ergo el error.

Una forma de solucionar el error no incializando todo inmediatamente.  Solo cuando sea estrictamente necesario, ahora, lo "bueno" de este error, es que no hará que tu programa se detenga, simplemente te avisa que el Pixmap que acabas de crear no tendrá una imagen, ya que no se ingreso un path válido (es decir, el Pixmap será un espacio en blanco).

Espero haberte ayudado!
