### ISSUE TITLE
Tiempo para la función putrefacción

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2233/Syllabus#525]
En la función putrefacción dice que la variable t es el tiempo que ha transcurrido desde las 8:00 AM de ese día, pero no se especifica si ese tiempo son minutos, segundos, horas, etc. Nosotros decidimos en que medimos ese tiempo o debe ser de una manera especifica?

**Comment by egromero** [comment]
Hola, en el enunciado sale:

![captura de pantalla 2017-10-17 a la s 00 20 49](https://user-images.githubusercontent.com/26122117/31645188-12c5c91e-b2d1-11e7-8c1a-2d895c37c245.png)

Saludos
