### ISSUE TITLE
Encontrar sprites

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#525]
Hola!

No he podido encontrar sprites buenos para la tarea 😞. ¿Alguien tiene alguna página con top-down sprites que nos sirvan? Ayudantes, ¿existe alguna posibilidad que podamos acceder a las imagenes de los edificios que aparecen en el enunciado?

<img width="675" alt="screen shot 2017-05-26 at 1 37 36 am" src="https://cloud.githubusercontent.com/assets/11022568/26482444/6e678240-41b5-11e7-9f24-94dedb93f93c.png">

Saludos!

**Comment by hanavarrete** [comment]
En esta tarea google será tu mejor amigo. Sobre las estructuras puedes encontrarlas buscando cosas de [este](https://www.google.cl/search?q=league+of+legends+structures+sprite&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj2ruGH8IzUAhXPPpAKHUuXBGUQ_AUIBigB&biw=1366&bih=613#tbm=isch&q=league+of+legends+turret&imgrc=Evr_GfkpgyCW6M:) estilo, pero más que eso no puedo ayudarte. Siempre puedes hacer tus propios sprites 😃

**Comment by akaminetzkyp** [comment]
Gracias!

**Comment by Hernan4444** [comment]
Complementando la respuesta, en [esta pagina](http://www.taringa.net/posts/hazlo-tu-mismo/13144009/Quitar-fondo-a-una-imagen-Online-Sin-descargar-nada.html) se explica como quitar el fondo a las imágenes, así no te limitas a estar buscando imágenes sin fondo todo el rato, tu se los puedes sacar :+1: 

Saludos!
