### ISSUE TITLE
Duda compartir programa con librerias externas

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#525]
Hola me acuerdo haber visto a alguien preguntar esto antes pero no logre encontrar la issue
Algo nada que ver con los contenidos quería saber si existe una manera de compartir un programa (que se pueda correr ) con las librerías externas que el programa ocupa como por ejemplo pyqt5 sin que el que recibe tenga que instalar manualmente las librerías en cuestión o al menos poder automatizar el proceso de instalación 
Algo encontré en Internet sobre compilarlo pero cualquier dato es recibido 
Gracias de antemano

pd: Todo esto en python

**Comment by aaossa** [comment]
Hola @JuaniAndres

Disculpa lo tarde de la respuesta. Lo que preguntaste es algo que yo también busqué en su momento y se trata de crear aplicaciones independientes (podría serte útil googlear con el termino "*standalone*" y "*freeze*"). Hay distintas alternativas y van cambiando en el tiempo, algunas de las respuestas de Google son de 2011 (👴 👵 ) y ya no son confiables. El problema parte porque no son muchas librerías las que hacen esto y varias quedan abandonadas en el tiempo. [Este artículo](https://docs.python-guide.org/shipping/freezing/) tiene referencias a las que están más activas en este momento. 

Te sugeriría probar un par de las que estén relativamente activas y ver si te siven. [`cx_Freeze`](https://anthony-tuininga.github.io/cx_Freeze/) se ve como una buena opción. De hecho, me animé a tomar un "Hello world" de PyQt5 y armé un script para hacer un *.exe que debería funcionar sin requerir Python instalado (eso sí, necesita otros archivos, que también te genera `cx_Freeze`). Al final, es necesario correr un comando en consola para que `cx_Freeze` genere la carpeta con los archivos y el ejecutable.

```python
# hello_world.py
# Tomado de contenidos: semana-06-07/1-interfaces-gráficas.ipynb
# https://github.com/IIC2233/contenidos/blob/master/semana-06-07/1-interfaces-gr%C3%A1ficas.ipynb
import sys
from PyQt5.QtWidgets import QWidget, QApplication


class MiVentana(QWidget):
    def __init__(self):
        super().__init__()

        # Definimos la geometría de la ventana.
        # Parámetros: (x_superior_izq, y_superior_izq, ancho, alto)
        self.setGeometry(200, 100, 300, 300)

        # Podemos dar nombre a la ventana (Opcional)
        self.setWindowTitle('Mi Primera Ventana')


if __name__ == '__main__':
    app = QApplication([])
    ventana = MiVentana()
    ventana.show()
    sys.exit(app.exec_())

```
```python
# setup.py
# Tomado y modificado de documentación de cx_Freeze
# https://cx-freeze.readthedocs.io/en/latest/distutils.html
import sys
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need fine tuning.
build_exe_options = {
    "includes": ["PyQt5"],
}

# GUI applications require a different base on Windows (the default is for a
# console application).
base = None
if sys.platform == "win32":
    base = "Win32GUI"

setup(name="hello",
      version="0.1",
      description="Hello world!",
      options={"build_exe": build_exe_options},
      executables=[Executable("hello_world.py", base=base)])

```

Finalmente, el comando a ejecutar:

```bash
python setup.py build
```

**Ojo 👀 :** En general es complicado generar los archivos para que funcionen en un sistema operativo A desde uno B, pero probablemente esta librería se encarga de eso. Si no, puedes conseguir un computador con el otro sistema operativo y hacer el mismo procedimiento según la documentación (cambia el comando, hay más opciones que `build`). 

Si algo no te funciona o tienes un error raro, te recomiendo googlear bien un par de veces, tratando de priorizar los resultados más recientes (2017 yo diría que está bien en esto) y probar cosas. Si tienes dudas o problemas más avanzados de esto, puedes preguntar por esta misma *issue* o mandarme un mail. Éxito 💪 

Referencias:

* [Artículo con librerías para hacer esto en Python](https://docs.python-guide.org/shipping/freezing/)
* [Documentación de `cx_Freeze`](https://anthony-tuininga.github.io/cx_Freeze/)

**Comment by JuaniAndres** [comment]
@aaossa muchas gracias por la info cuando tenga tiempo voy a probar
