### ISSUE TITLE
Descuentos por exceso lineas codigo

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#526]
A partir de cuantas lineas de codigo en un archivo me empiezan a descontar decimas?
Si tengo 500 esta bien ?

**Comment by Dnpoblete** [comment]
Hola @dsepulveda3 , esta duda ya fue respondida en la issue #468, para que revises bien antes de abrir una issue, voy a cerrar esta y en caso de seguir teniendo dudas con respecto al tema, puedes preguntar en esa issue.

Éxito con la tarea! :smile:
