### ISSUE TITLE
Duda contenido de networking

### ISSUE THREAD

**Issue by Gaonuk** [IIC2233/syllabus#526]
He estado estudiando la materia del contenido de networking y probando los códigos que nos dan pero cuando me dicen que pruebe los códigos en dos computadores distintos, he estado intentándolo de distintas maneras pero aun no lo logro hacer que se establezca una conexión, como debo hacerlo para que se pueda establecer una conexión entre los dos computadores?

**Comment by cruz** [comment]
Hola @Gaonuk 
Para que dos computadores puedan "verse" de manera fácil, es necesario que estén conectados a la misma subred. ¿Qué significa esto? Una forma sencilla de verlo, es que las direcciones IP de cada uno empiecen de la misma manera. Si ambos están conectados a la misma red WiFi, es muy probable que ya se encuentren en la misma subred (incluso podrías hacerlo entre un celular y un computador en la misma WiFi). El cómo saber la IP varía un poco de acuerdo al sistema operativo, pero puedes seguir este [link](https://www.avast.com/c-how-to-find-ip-address) e ir a la sección "Find your local IP address".

Ahora, si quieres que se conecten dos computadores que están en subredes distintas; por ejemplo tu computador con el de otra persona que está en otra casa, vamos a encontrar más dificultades. Una es que los proveedores de Internet (Movistar, VTR, GTD, etc) restringen algunos puertos en que se permite comunicación, principalmente por temas de seguridad, y es posible que el _router_ del destinatario no permita que la conexión desde "afuera" ingrese directamente a la subred en que está el computador de la otra persona. Ahora bien, si los puertos no están restringidos, la segunda dificultad es que en las redes domiciliarias los computadores suelen tener direcciones IP privadas (seguramente empiezan con `10.*.*.*`, o con `192.168.x.x`), y cuando te conectas a internet no lo haces con tu dirección IP privada, sino con la dirección IP del router que te entregó tu proveedor. Para saber cuál es esa dirección puedes ir a google y consultar por "`what is my ip`"; ahora bien, no basta saber la IP pública del destinatario, sino que hay que configurar algo en el _router_ para que la comunicación desde afuera "pase" hacia el computador correcto en el domicilio de destino. Esa configuración se conoce como _Port Mapping_, o _Port forwarding_ y es parte de una configuración ampliamente usada que se conoce NAT (_Network Address Translation_). Explicarlo aquí sería bastante largo y los detalles específicos van a depender del _router_ del domicilio de destino. Sin embargo puedes buscar más información [aquí](https://afteracademy.com/blog/how-to-convert-your-laptop-desktop-into-a-server-and-host-internet-accessible-website-on-it-part-2-cdb4b3633fa9).

Un detalle. Si quieres probar la conexión desde un celular que está conectado a la red 4G (y no a la WiFi en que está el computador), es lo mismo que si estuvieras en otra casa, pues también se trata de subredes de internet distintas.

Finalmente, para poder ayudarte mejor, tendría que saber en cuál de los casos estamos.
