### ISSUE TITLE
habilidad especial dccrotona

### ISSUE THREAD

**Issue by eliasbruchfeld** [IIC2233/syllabus#526]
Hola! cuando la gente de dccrotona usa su habilidad especial, se supone que gana una medalla obteniendo TODOS los beneficios que eso implica.  O sea...basicamente se gastan 30 dccoins en la habilidad para que despues les regalen 100 por "haber ganado una medalla"??

**Comment by amparostevens** [comment]
Hola! 

Así es, deben ocurrir todos los cambios que ocurrirían al ganar una competencia, como es que aumenten las DCCoins. 

Éxito! 🌟

**Comment by alterdieg0** [comment]
@eliasbruchfeld usar la habilidad especial cuesta 20 DCCoins, no 30 :eyes:

**Comment by amparostevens** [comment]
Recuerden que los número escritos en azul son __parámetros__!! Para que tengan cuidado ya que se puede alterar su valor.

**Comment by spplaza** [comment]
Si es que ocupa la habilidad, a qué deportista se le aumenta la moral? Es aleatorio o no aumenta ninguno?

**Comment by alejita97** [comment]
comento para saber
