### ISSUE TITLE
Problemas con el uso de Qthread: Solo funciona una vez

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#526]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Un Qthread solo funciona una vez

Hola, para una parte de mi código uso un Qthread pero solo me funciona una vez, tal vez podría ser porque intente hacerlo de forma distinta a los ejemplos que vimos en cuadernillos, lo que quería hacer no era muy elaborado así que no quería crear una clase que hereda de QThread, busque y vi que se podía escribir lo que sigue:

thread = QThread()
thread.started,connect(metodo)

** El que solo funcione una vez es por como lo intente hacer, o deberia ser otro el problema? **

**Comment by clementevalladares** [comment]
Hola @Pabloski100.  De la manera en que están pensados los Qthreads (y threads en general) es para que se ejecuten hasta que hayan salido del flujo del método al que los asignaste. Si quieres que el ciclo se repita una y otra vez sin tener que comenzar el thread de nuevo, debes incluir un while dentro del método al que se llama al iniciar el thread.
Viendo la forma en que lo implementaste, aprovecho de agregar que cuando haces thread.start(), se llamará automáticamente al método llamado "run" que hayas creado dentro de tu clase. La manera en que lo hiciste produce exactamente el mismo resultado, pero quizás te sirve saber que existe esa forma de hacerlo.
Espero que se haya entendido.

**Comment by Pabloski100** [comment]
Perdón, me falto detallar lo que activa el qthread, lo que tenia pensado es que se ejecute el qthread cada vez que se presione una tecla, me pasa que funciona solo la primera vez que presiono la tecla, pero me imagino que si el problema no es como lo implemente debe ser algo en mi código

**Comment by clementevalladares** [comment]
Si subes lo que llevas a tu repositorio lo puedo revisar para ayudarte!

**Comment by Pabloski100** [comment]
Lo hago de inmediato, gracias!

**Comment by clementevalladares** [comment]
@Pabloski100 Revisé tu código. El problema está en que cuando llamas al método start() de un QThread, lo que hace es comenzar automáticamente al método run() que hayas definido dentro de esa clase. Por defecto, si no sobrescribiste este método, el QThread  estará corriendo hasta que llames al método exit(). Puedes encontrar más información [aquí](https://doc.qt.io/qt-5/qthread.html#run). Por lo que en tu programa self.thread.isRunning() siempre será True una vez que hayas hecho start().
De la manera en la que estás planteando por el momento tu programa. Podrías cambiar ese Qthread por una variable que tome valores de True y False y obtendrías el mismo resultado que esperas de ese thread. Probablemente más adelante dentro del desarrollo de la tarea sí te encuentres con la necesidad de implementar una clase que herede de QThread, te recomiendo mucho que lo hagas de la manera en que está explicado en los contenidos del curso porque le vas a encontrar mucha mayor utilidad.
