### ISSUE TITLE
Se gasta la mesada?

### ISSUE THREAD

**Issue by santi95** [IIC2233/Syllabus#526]
Si la mesada es de 20000 eso significa que puedo usar máximo 1000 al día?
Que pasa si un día almorcé por 500, al día siguiente podría almorzar por 1500?
O la mesada no se gasta y solo se tiene un máximo de gasto diario?
Además, se considera la compra de un snack como un gasto de la mesada? por ejemplo, si me compro un snack de 1000 y tenía 1500 de mesada diaria ahora solo puedo almorzar por 500?

Gracias!

**Comment by iqacevedo** [comment]
Hola, 

En el enunciado dice explicitamente que el dinero de un día es no acumulable. El gasto del snack si deberías considerarlo como un gasto de la mesada (el ejemplo que indicas estaría bien).

Saludos !
