### ISSUE TITLE
Llegadas fuera de horario

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#526]
Hola! En el enunciado (sección 8.1) en la explicación de _time_ dice: 
> Tiempo de llegada. Este valor siempre estará entre las 10.00 y las 19.00

Sin embargo, en _arrivals.csv_ nos encontramos con estos casos:
> Lunes,20:38,39737,3
> Martes,20:54,25439,2
> Viernes,20:00,53256,4
> Sábado,19:12,30130,2
> Domingo,30:25,127415,12

¿Consideramos esas llegadas como un error en la base de datos y las borramos directamente o las manejamos en nuestro código?

**Comment by Hernan4444** [comment]
@llloyola puedes ignorarlas. Voy a encargarme de filtrar esas llegadas para mañana.

Saludos ✌️

**Comment by llloyola** [comment]
Ok ok
Gracias! 😃

**Comment by pcseisdedos** [comment]
Donde se encuentra esa versión? quizás hubo un problema con el push, porque en Syllabus/Tareas/T04 sigue la misma:
![image](https://user-images.githubusercontent.com/18387808/40245977-205d4f68-5a95-11e8-972a-3d78f97741a3.png)
 :/ 
![image](https://user-images.githubusercontent.com/18387808/40246024-48ec4542-5a95-11e8-9e1c-c67ce9713cc3.png)

**Comment by Hernan4444** [comment]
ahí si jejeje
saludos ✌️
