### ISSUE TITLE
Mouse Sobre Label [pyqt5]

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#526]
Una consulta!, Hay alguna forma en pyqt de detectar cuando el mouse (mediante mouse event)  entra al espacio de un label dentro de un MainWindow?

**Comment by sebacruzd** [comment]
Hola,

Una opción es revisar si la posición del mouse está en una de las áreas de los objetos.
También existen los [tooltips](https://stackoverflow.com/questions/28510193/detect-being-hovering-over-specific-widgets-in-pyqt4)
Y en [este link](https://stackoverflow.com/questions/3562447/pyqt-how-to-catch-mouse-over-event-of-qtablewidget-headers) hay una respuesta interesante que creo podría servirte.
No olvides googlear antes de hacer algunas preguntas.

Saludos!

**Comment by KnowYourselves** [comment]
Gracias por la respuesta!, Lo siento si mi pregunta es googleable, pero en mi caso encuentro respuestas, pero simplemente no logro entenderlas, y la documentacion no es de mucha ayuda tampoco, en el caso de tus recomendaciones, si bien las entiendo algo, no entiendo ni como aplicarlas ni como funcionan, ese es mi problema principal

**Comment by DiegoAndai** [comment]
Hola! Quizás estás buscando un evento llamado 'enterEvent()' propio de QWidget (QLabel hereda de QWidget), este se activa cuando el mouse entra al label.

http://pyqt.sourceforge.net/Docs/PyQt4/qwidget.html

Esa es la documentación de QWidget de pyqt4 y ahí aparece el método que te menciono, no creo que sea muy distinto de pyqt5, en todo caso en la documentación oficial de qt 5 también aparece:

https://doc.qt.io/qt-5/qwidget.html

Avísame si no te funciona o no sabes cómo ocuparlo 😃 Debería funcionar como los otros eventos.

**Comment by KnowYourselves** [comment]
@DiegoAndai Creo que eso es exactamente lo que necesito!, Una consulta, hay algun "exit event"? o algo parecido?, en otro caso hay alguna forma de crear mis propios eventos para aplicar esto?

**Comment by KnowYourselves** [comment]
Pd: Ya me funcionió!, Muchas gracias!, le pondre tu nombre a mis hijos

**Comment by DiegoAndai** [comment]
Existe el método `leaveEvent()` que se activa al salir, en general puedes ocupar esa documentación de pyqt4 que puse ahí, es bien completa, y la mayoría de las cosas debería funcionar igual en pyqt5.

Saludos.
