### ISSUE TITLE
Crear otro archivo

### ISSUE THREAD

**Issue by sheinkzx** [IIC2233/Syllabus#526]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Siento que esta duda pueda ser media obvia, pero puedo crear otro archivo con el codigo a usar en `consultas.py`? Y subir ambos al termino de la tarea?

**Comment by DiegoGHR** [comment]
Hola! De poder, se puede, y no tendras descuento por esto. Por ejemplo, podrias importar parametros o funciones desde un archivo en la misma carpeta. Procura importarlo de manera correcta. Saludos
