### ISSUE TITLE
bonus contraseña

### ISSUE THREAD

**Issue by videvidts** [IIC2233/syllabus#526]
al intentar comparar la clave codificada en mi archivo y la clave ingresada por el usuario me dice: invalid salt.
¿Alguna idea de por que podría ser esto?
Mi clave está almacenada en un archivo.txt por lo que es un string cuando leo el archivo para poder comparar las claves.

**Comment by KnowYourselves** [comment]
Hola @videvidts!

Antes de poder responder, estás utilizando [bcrypt](https://pypi.org/project/bcrypt/)?, En caso de que así sea, el error te sucede **siempre**, o en ciertos casos? (por ej, cuando la contraseña tenga la letra ñ, o una tilde, etc).

Quedo atento!

**Comment by videvidts** [comment]
Ya lo solucioné! Es porque ya que leía mi clave desde un archivo era un string, tenía q convertirla a bytes

**Comment by KnowYourselves** [comment]
Congrats!
