### ISSUE TITLE
Duda mouse sobre Qlabel

### ISSUE THREAD

**Issue by JoseValencia125** [IIC2233/Syllabus#527]
¿Como puedo saber cuando el mouse está sobre un QLabel? Estoy usando un MouseMoveEvent y obteniendo para obtener las coordenadas del mouse, pero cuando paso por sobre el QLabel no las retorna.

**Comment by hanavarrete** [comment]
#526 porfavor revisar issues cerradas!. Si esto no te sirve aún, cuéntame por acá. Saludos

**Comment by JoseValencia125** [comment]
Ya lo resolví solo tenia que setear el tracking del mouse en el Qlabel como true
