### ISSUE TITLE
Desarrollo de ayudantía semana 5

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#527]
Hola!
Cuándo podrán publicar el desarrollo de la ayudantía que se hizo este martes?

**Comment by Dnpoblete** [comment]
Hola @Camila-sty, la solución de la ayudantía 4, correspondiente a la semana 5, fue subida hace 2 días, para que lo revises bien antes de abrir una issue.

En caso de que no la encuentres avisame! 😄
