### ISSUE TITLE
Problema con el test de correctitud 11

### ISSUE THREAD

**Issue by Delfin13120** [IIC2233/Syllabus#527]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Problema con el test de correctitud 11

Hola! Me pasa que a la hora de probar los test de carga de la función pizza_mas_vendida_del_dia me salen todos bien, sin embargo, me aparecen fallos en el test de correctitud, cosa que me parece rara ya que probé manualmente el código con casos particulares y todo parece estar en orden.

**Comment by Delfin13120** [comment]
En la función popularidad_mezcla_de_ingredientes me pasa lo mismo :(

**Comment by Delfin13120** [comment]
Otra cosa que me parece rara con respecto al test de correctitud 11, es que el test 12 de correctitud, de la función pizza_del_mes me salen todos OK, siendo que ambas funciones son casi iguales, solo cambia la indexación de la fecha.

**Comment by wintermelyn** [comment]
Hola @Delfin13120!

Es posible que estes dejando algunos casos borde como las pizzas de tamaño XL fuera de tu función y por esto estén fallando solo los tests de correctitud. El enunciado dice:

> Nombre de la pizza junto al tamaño de esta. Estos dos aspectos estarán separados por un guión bajo (_) y será el único guión bajo del nombre.

Esto incluye nombres como:
- Pepperoni Clásica_S
- Pepperoni Clásica_M
- Pepperoni Clásica_L
- **Pepperoni Clásica_XL**

**Comment by Delfin13120** [comment]
Hola! No pude resolver el problema :( 
Busqué en todos los datos de pizzas y el tamaño XL no existe en ninguna.

**Comment by wintermelyn** [comment]
@Delfin13120 Hola! por ejemplo en el test_0 de correctitud del archivo test_11_pizza_mas_vendida_del_dia_correctitud.py se te entrega el siguiente generador.

```python
lista_entregada = [
            ContenidoPedido(
                id_pedido=1, nombre="Pepperoni Clásica_M", cantidad=4, descuento=0.0
            ),
            ContenidoPedido(
                id_pedido=2, nombre="Pepperoni Clásica_XL", cantidad=10, descuento=0.0
            ),
            ContenidoPedido(
                id_pedido=3, nombre="Vegetariana Normal_M", cantidad=6, descuento=0.0
            ),
            ContenidoPedido(
                id_pedido=4, nombre="El Pepe Hawaiiana_M", cantidad=2, descuento=0.0
            ),
            ContenidoPedido(
                id_pedido=5, nombre="Camarones bajo ajo_S", cantidad=30, descuento=0.0
            ),
        ]

        generador_entregado_pedidos = (pedido for pedido in lista_entregada)
  ```
