### ISSUE TITLE
No me funcona KeyPressEvent 

### ISSUE THREAD

**Issue by arturoprietovic** [IIC2233/syllabus#527]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola!
Al usar el KeyPressEvent en mi ventana creada en qtDesigner no pasa nada. Intenté lo que dice en la issue #497 pero sigue sin funcionar :/

pd: mi repositorio ya esta subido cualquier cosa

**Comment by MatiasDuhalde** [comment]
Hola @arturoprietovic !

Revisé tu código, y el problema parece ser bien simple: al método lo llamas `KeyPressEvent` en lugar de `keyPressEvent` (notar la primera letra mayúscula). Para que el método se invoque correctamente cada vez que se presiona una tecla, el nombre debe ser exacto, debido a que por detrás la librería PyQt5 funciona con method overriding, y si hay una diferencia en el nombre del método (aunque sea tan pequeña como una mayúscula), lo va a considerar como un método totalmente distinto.

Como nota aparte, recuerda que para tu entrega final debes manejar el movimiento por medio de señales!

Ojalá eso haya resuelto tu problema! :cowboy_hat_face:

**Comment by arturoprietovic** [comment]
:man_facepalming: gracias :))
