### ISSUE TITLE
Duda de Networking

### ISSUE THREAD

**Issue by anvaldes** [IIC2233/syllabus#527]
Hola, tengo una duda, lo que pasa es que corro el siguiente codigo de la materia:

![image](https://user-images.githubusercontent.com/53879188/68989027-cf1cc900-081f-11ea-83f8-4a00e3f4834b.png)

Y se queda pegado en "estoy aca 1" me imagino que es porque no tengo el socket cliente definido. Ahora como lo defino?

**Comment by igbasly** [comment]
Hola @anvaldes!
Como bien indicas, el código que muestras corresponde a un servidor, el cual queda esperando en `socket_cliente, address = sock.accept()` a que algún cliente se conecte.
Ahora, para definir un cliente puedes ocupar el código que te indican en el material, justo debajo de eso, que corresponde a lo que aquí adjunto.
```python
import socket

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Obtenemos el nombre de la máquina a la que nos queremos conectar.
# En este caso, nos queremos conectar a esta misma máquina.
host = socket.gethostname()
port = 9000

sock.connect((host, port))
data = sock.recv(4096)
print(data.decode("ascii"))
sock.close()
```
Como la arquitectura cliente-servidor hace referencia a dos programas conectados mediante una red, los cuales pueden o no estar en maquinas diferentes, te lleva a crear programas independientes. Esto quiere decir que para probar la conexión entre el cliente y servidor, lo más sencillo sería hacer dos archivos (uno para el cliente y otro para el servidor) y correrlos independientemente, primero el servidor y luego el cliente.
Así deberías poder conectar tus programas :+1:

**Comment by anvaldes** [comment]
Hola, acabo de hacer lo que comentaste. Es decir, crear un archivo para el servidor y otro para el cliente. Primero corri el archivo para el servidor y luego para el cliente y aún así me tira el siguiente error:

![image](https://user-images.githubusercontent.com/53879188/68999101-76d6dd00-089a-11ea-9f9f-e7b8d75a00e6.png)

**Comment by JoacoCoyu** [comment]
Hola @anvaldes !

Estuve investigando tu error según el código que publicaste más arriba, y cosas que podrías revisar son:

> Que el comando bind (para servidor) y connect (para cliente) sean de la forma: `serverSocket.bind((serverPort ,serverPort))` y no `serverSocket.bind(serverPort ,serverPort)`. Este comando recibe una tupla con la dirección y el puerto, puede que sea un problema de sintaxis.

> Chequear que el socket en el servidor esté en modo `listen( )` para recibir conexiones de los clientes.

Según el error que muestras, parece haber un problema en el archivo cliente, pero de todas maneras revisa lo que señalé el archivo servidor. Te recomiendo también ver esta _issue_ [https://stackoverflow.com/questions/49628925/python-socket-programming-connectionrefusederror-winerror-10061] y probar ese código, tal vez identifiques el error comparándolo con tu código.

Espero que sea de ayuda!

**Comment by JosefaPaz** [comment]
Hola!

Sabes qué puedo hacer si al probar el código de ejemplo nunca se me conecta el cliente al servidor? Lo copié textualmente al editor de código y lo corrí en dos CMD diferentes, pero aún así tengo errores.

Gracias!
