### ISSUE TITLE
Enfermarse por producto en Quik Devil

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#527]
Si un alumno o funcionario se enferma por un producto que compró en el Quik Devil, como este no está en su lista de preferencias, igual puede volver a comprar en él?

**Comment by Julius9** [comment]
Del enunciado yo entendí que los pesos diarios  no son acumulables, por lo tanto aunque no gaste dinero un día no podré usar ese monto al día siguiente, como si se perdiera al no haberlo usado. Aunque no se si esta suposición este en lo correcto :(

**Comment by ifcarrera** [comment]
Hola! 
A pesar de que se enferme, siempre es posible volver a comprar en ese malvado local :(.
Saludos
