### ISSUE TITLE
Problema con arrivals.csv

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#527]
Hola
Sublime me arroja esto:
![image](https://user-images.githubusercontent.com/37153467/40213404-4b679bea-5a23-11e8-9158-2a285fb0fc38.png)

Y el dichoso caracter es...
![image](https://user-images.githubusercontent.com/37153467/40213383-313caefe-5a23-11e8-922b-a0e111d9064e.png)

Por si preguntan, estoy haciendo esto:
![image](https://user-images.githubusercontent.com/37153467/40213441-72043f2e-5a23-11e8-90b1-7f575646fa76.png)

Reciclé la función de la T03 y ahí funcionaba bien.

**Comment by yoavnavon** [comment]
Hola! Trataste de hacer pull al repo? En la issue #518 les paso lo mismo
