### ISSUE TITLE
Problema con keyPressEvent

### ISSUE THREAD

**Issue by victoriatsimoyannis** [IIC2233/syllabus#528]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo un problema con el keyPressEvent, cuando apreto muchas veces o mantengo presionada la tecla como que se da inicio a la ventana de juego muchas veces y aparecen muchos personajes y sets de objetos. Como puedo arreglar esto? yo creo que es porque se manda muchas veces la señal de iniciar juego, en realidad no estoy segura pero no supe cómo arreglarlo.

Graciass!!

**Comment by Juampisaez** [comment]
Hola @victoriatsimoyannis 
Si puedes actualizar tu repo para ver mejor el problema pls

Quedo atento :)

**Comment by victoriatsimoyannis** [comment]
Sii! Listo!

**Comment by Juampisaez** [comment]
Ya, el problema es que cada vez que apretas la tecla "D" en la pagina de preparacion, y la posicion del personaje es >= x, se envia la `self.senal_colision_edificio` lo que hace que se muetre el personaje en la ventana del juego. El error puede estar el sleep que haces antes de enviar la señal, ya que en ese tiempo puedes apretar la tecla nuevamente y se volvera a ejecutar nuevamente la señal.

Espero se entienda, sino me dices :)

**Comment by victoriatsimoyannis** [comment]
Sii graciass logré arreglar eso! Aunque ahora tengo otro problema tambien con el keyPressEvent, en la ventana de juego cuando lo mantengo apretado el personaje avanza pero luego retrocede, como si hubiese apretado solo una vez.

**Comment by Juampisaez** [comment]
Ocurre por lo mismo anteriormente, el problema esta en los `self.sleep`.
Si me preguntas, creo que podrias modelar de mejor forma los metodos para mover los personajes, en esta [issue #521](https://github.com/IIC2233/syllabus/issues/521), recomende un par de videos donde se modela el movimiento.

Espero que quede mas claro, sino me avisas :)
