### ISSUE TITLE
Spritesheets

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#528]
Hola hola, 

mi duda es respecto a como integrar spritesheets en PyQt. 

Onda se que en PyGame se hace fácil con convert nomas, pero quería ver si había una forma rápida de hacerlo con PyQt. No logro encontrar info al respecto, seguramente porque no es comun hacer juegos en PyQt. 

O sino, que recomiendan para convertir un spritesheet en imagenes chicas, ya que hacerlo manual es demasiado tedioso.

gracias y buen fine

**Comment by sebacruzd** [comment]
No se puede hacer lo que quieres con PyQt. Mira lo que dicen en #525, el comentario de @Hernan4444 debería ser una solución a tu problema.

Saludos!

**Comment by Kitaps** [comment]
Tnx

**Comment by Hernan4444** [comment]
@Kitaps lo que quieres hacer no tiene una forma "directa" tal como dice @sebacruzd, pero QPixmap tiene métodos para 'recorrer' una imagen tomando partes de ellas (desde un x,y hasta un x+dx, y+dy) y con ello puedes crear un conjunto de QPixmap que tienen cada imagen del spritesheets, así te ahorras el trabajo de tener un conjunto de imágenes por separado en una carpeta y solo tener un spritesheets  pero para eso implica investigar dentro de la documentación de Qpixmap con que métodos logras eso. ([Aqui está el link](http://doc.qt.io/qt-5/qpixmap.html) de la documentacion por si acaso.)

Saludos!
