### ISSUE TITLE
Hora en que se instalan los puestos de vendedores

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#528]
Hola en el enunciado sale: "Instalar puestos Todos los puestos abren alrededor de las 11 am, según un proceso de distribución normal de parámetros mu = 11:00, sigma = 30 minutos.", sin embargo nuestra simulación (por el mismo enunciado) debe partir a las 11:00.
¿Que hacemos si la hora de instalación de un vendedor sale por ejemplo a las 10:59 o antes?

**Comment by ifcarrera** [comment]
Hola, si las probabilidades te indican que un vendedor se instala antes de las 11:00, significa que cuando inicie el día de tu simulación ya estarán instalados (y vendiendo). Mientras que en el otro caso, se instalarán durante tu simulación (evento aparte).

Saludos

**Comment by ptflores1** [comment]
@ifcarrera Hola! es strictamente necesario hacer esto ? no puedo dejarlo como que se instalen antes? Personalmente me gusta mas asi :grin:. Ojala se pueda. Gracias !

**Comment by Hernan4444** [comment]
@ptflores1 **es estrictamente necesario que sigan el enunciado**. Si se dice que siguen una distribución normal con `mu = 11:00` y `sigma = 30 minutos`, es que se espera que implementen este evento bajo esa distribución y ver los efectos que tiene en las estadística. Bajo tu supuesto, no estás aplicando lo esperado. Si lo dejas así, es 99.9% seguro que tendrá repercursión en el puntaje.

Saludos ✌️

**Comment by JPSF** [comment]
@ptflores1 @ifcarrera 
Hola! Por lo que entendí se contradicen ambos en lo que dijeron.No me queda claro si es que efectivamente debemos modelar la instalación de los puestos como un evento (en cuyo caso la modelación empezaría desde antes de las 11), o si se debe realizar la modelación desde las 11 y que se consideren los eventos que ocurren antes de las 11 como eventos que ocurren efectivamente a las 11.

**Comment by mjgutierrez1** [comment]
A la duda anterior agrego otra: ¿podemos poner una cota superior de hora de instalación de puestos, al igual que como se hace con la hora de decidir ir a comer? Sé que es poco probable que den horas muy tardías, pero es teóricamente posible (de hecho, por esa misma razón se agregaron al enunciado cotas a las horas de ir a comer).

**Comment by cilopez** [comment]
@mjgutierrez1 Si puedes , agrega cotas razonables y mencionalas en tu readme como una medida para que la simulación sea más realista.
