### ISSUE TITLE
Sala de espera y chat

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#528]
Hola, puedo considerar que la sala de espera y el chat están en la misma ventana?

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

Mientras el chat siga los requerimientos del enunciado (aparecer solo cuando entres a una sala, mantenerse cuando empiece el juego, desaparecer cuando salgas de la sala, etc), es válido que lo hagas así.

Saludos!
