### ISSUE TITLE
error :'str' object is not callable

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#528]
Hola! intente hacer una instancia deportista con los datos que me daban en un diccionario, es decir
a["nombre"] era el atributo nombre y así, pero me salió ese error y busque en internet pero no entendi a lo que se refería

**Comment by amparostevens** [comment]
Hola! 
Podrías subir tu código a tu repositorio e indicarme dónde ejecutas ese método?

**Comment by Natydlb** [comment]
Listo! lo ejecuto en la linea 353

**Comment by amparostevens** [comment]
Noté varias cosas en tu código que creo podrían estar causando el problema.
- Las clases las estás definiendo con todas las letras minúsculas. Por pep8 deberían ser con la primera letra de cada palabra en mayus. 
- Luego llamas a variables que se llaman igual que tu clase deportista. Python busca en orden las referencias, por lo tanto si en la línea anterior definiste una variable tipo `str` como deportista, va a buscar en ahí primero y el programa va a fallar al intentar ejecutar métodos de clase sobre ella. 
- Cuida que los atributos sean del tipo correcto. Por ejemplo, dinero en algunas partes no estaba transformado a `int` por lo que no funciona cuando quieres modificar la cantidad. 

Espero que te sirva para arreglar tu código! Cualquier duda comenta esta issue 😉

**Comment by Natydlb** [comment]
Si muchas gracias! pero ahora tengo un problema con llamar a un atributo de otra clase en una clase, (ese atributo es obtenido de una clase padre y creo que por eso no me funciona, creo que no estoy implementando bien lo de clase abstracta pero no encuentro el error, esto esta en la linea 305, lo actualice

**Comment by amparostevens** [comment]
Si, estás implementando mal la herencia. 
Supongo que quieres que tus clases `DCCroton` e `IEEEsparta` hereden de `Delegaciones`, pero actualmente estás haciendo que hereden de `Delegaciones, Deportista y Deportes` pero no estás ejecutando bien el `__init__` ya que nunca llamas a `super()` para que verdaderamente se hereden todos los atributos y métodos, como aparece en los contenidos de [multiherencia](https://github.com/IIC2233/contenidos/blob/master/semana-03/2-multiherencia.ipynb)
Me parece que esa multiherencia no sería la modelación más adecuada en todo caso. Aquí puedes ver los contenidos de [herencia](https://github.com/IIC2233/contenidos/blob/master/semana-02/3-herencia.ipynb) 

Te recomiendo revisar los contenidos del curso (los dejé como hipervínculo 😉) y si aún no te funciona me avisas!
Mucho éxito con la tarea! ✨

**Comment by Natydlb** [comment]
Muchas gracias me sirvió de mucho!!! pero aun sigo con un problema porque en la clase que hereda porque trate de hacerlo como el ejemplo de la multiherencia y como contenido del super().init solo se pone solo el kwargs, pero python me dice que le faltan 5 argumentos al init de la clase que hereda, pero en los ejemplos no sale así D: nose que hacer, intente arreglarlo pero no funciono, esto paso en la 322

**Comment by amparostevens** [comment]
Por lo que acabo de ver, sigues con el mismo problema que mencioné antes. Creo que deberías considerar cómo estás modelando la relación entre clases. Tiene sentido que `Delegación` herede de `Deportista`? o acaso es una relación de agregación? o quizás composición? 
Revisa el feedback de tu diagrama de clases. Si no lo entregaste, te recomiendo que lo realices antes que sigas programando, para poder aclarar mejor tus ideas.

**Comment by Natydlb** [comment]
Gracias por la ayuda!, hice el diagrama pero ayer me di cuenta que no lo subí :( me cuesta harto ver lo de agregacion o composicion, me pongo en el caso de los deportista, si los deportes no existieran, los deportistas seguirían existiendo? me cuesta verlo, tal vez tendría sentido que un deportista herede una delegación, el campeonato herede un deportista y el deporte herede un campeonato, pero me confunde mucho, habra alguna parte donde hayan mas ejemplos a fondo de eso?

**Comment by amparostevens** [comment]
Hay mucho material en internet. Encontré este [video](https://www.youtube.com/watch?v=xLoFXfg4uY0&t=267s) que me parece explica bien y de manera simple la diferencia entre herencia, agregación y composición.

En resumen, cuando se habla de herencia se refiere a que algo __es__ otra cosa, en cambio, al hablar de agregación y composición no se es algo, sino que __usa__ o __tiene__ otra cosa. Para seguir con el ejemplo disponible en los [contenidos](https://github.com/IIC2233/contenidos/blob/master/semana-03/1-diagrama-de-clases.ipynb) del curso, un LadrilloMoneda __es__ un ladrillo (herencia), el Ejército __usa__ Goombas (agregación) y el Juego __tiene__ Ladrillo y Goomba (composición). 

En el caso de la tarea, una Delegación tiene Deportistas, pero no es un Deportista, del mismo modo que un Deporte tampoco es un Deportista. En caso de serlo, estaría diciendo que una Delegación tiene los mismos métodos y atributos de un Deportista, lo mismo con Deporte. 

Ojalá te quede más claro con el video! 
Éxito ✨

**Comment by Natydlb** [comment]
Muchas gracias!! me quedo mucho más claro con los ejemplos y pude ver el GRAN error que estaba cometiendo!!

**Comment by amparostevens** [comment]
Me alegro!! Mucho éxito con la tarea 🏅
