### ISSUE TITLE
Consulta Paciencia

### ISSUE THREAD

**Issue by simontoya** [IIC2233/Syllabus#528]
Hola! Tengo la siguiente duda en el enunciado sale que el ```mu``` paciencia se define como:
    ```mu  = (10 + energia * 30) min```
Mi pregunta es si cada vez que cambie la energía debo recalcular la paciencia con el nuevo valor de la energía?

**Comment by rihanuch** [comment]
¡Hola @simontoya !

Si, pero a paciencia va a variar en función de la energía. Eso si, ten en mente que poco óptimo hacer este cálculo *cada vez* que cambia la energía 🔋

¡Saludos y éxito! 🍀
