### ISSUE TITLE
Mala practica: atributos publicos

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#528]
Hola, 
tenia la siguiente duda:
¿Es considerado mala practica tener atributos públicos y ademas llamarlos fuera de la clase?

Saludos!

**Comment by mpsubiabre** [comment]
Hola @Ignacioislae,

Python a diferencia de otros lenguajes de programación no le da mucha importancia a los atributos públicos, sin embargo puede ser peligrosos. En un principio se pueden definir atributos públicos, lo cual te permite de forma mas simple acceder a ellos y cambiarlos. Sin embargo, cuando se necesite una funcionalidad en torno a su configuración, obtención y eliminación es correcto agregar estos con el decorador de properties, y setear el atributo privado.
También quiero destacar que en la programación es muy importante el termino de encapsulamiento de datos, lo cual es de manera simple, tener datos y los métodos en una sola unidad, evitando su acceso directamente, y evitar modificaciones accidentales. Para esto se utilizan las variables privadas.
Con esto espero que entiendas que la definición del atributo depende netamente de tus necesidades, y el contexto definirá su mala práctica o no.

Espero que te haya quedado claro 😄

**Comment by Ignacioislae** [comment]
Yaa gracias!
Una duda mas:
¿En que caso en el que quiera obtener el valor de una variable la debería dejar como privada, y usar properties? ¿Porque al querer obtener el valor de una variable no se modificaría y no se me ocurre como se podría generar un error? (si es que solo la llamo para recibir su valor)

**Comment by mpsubiabre** [comment]
Si solo deseas obtener el valor de dicha variable es mas simple que sea publica.
Un error hipotetico podria ser el caso de que esta variable sea muy importante y por ningun motivo pueda ser modificada. En este ccaso es mas "precavido" dejarla privada, para solo obtener su valor y no cambiarla accidentalmente, lo cual podria generar un error.

**Comment by Ignacioislae** [comment]
Buenisima, gracias!!
