### ISSUE TITLE
Error de conexión

### ISSUE THREAD

**Issue by anvaldes** [IIC2233/syllabus#528]
Hola! Corro el siguiente codigo:

![image](https://user-images.githubusercontent.com/53879188/68989112-18214d00-0821-11ea-8ce6-2f7772efcbbf.png)

Pero me lanza el siguiente error:

![image](https://user-images.githubusercontent.com/53879188/68989120-2b341d00-0821-11ea-8d48-6ac3bc65b77a.png)

A que se debe y como solucionarlo?

**Comment by igbasly** [comment]
Hola @anvaldes 😅 
Este error por lo general se genera cuando intentas conectar un cliente a una dirección cuyo servidor aún no está recibiendo conexiones, es por esto que primero deber abrir el servidor, es decir, ejecutar ese programa y luego abrir el cliente.
Con eso no deberías tener ningún problema, saludos ✌️
