### ISSUE TITLE
Uso de comandos de estructuras de datos

### ISSUE THREAD

**Issue by FranVvi** [IIC2233/Syllabus#528]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, quisiera saber si se permiten los comandos list(), tuple(), dict(), set(), entre otros, para poder cambiar una estructura de datos.
Por ejemplo: list(generador)
Gracias.

**Comment by DiegoGHR** [comment]
Hola! Si, se permiten utilizar las estructuras de datos que estimes convenientes. Recuerda tener ojo con el tiempo de ejecucion de tu tarea para no sobrepasar el limite. Estas estructuras pueden aumentar considerablemente el tiempo de ejecucion. Saludos
