### ISSUE TITLE
Precio entrada

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#529]
En el enunciado (sección 3.1.1 > Adultos) dice: 
> "... Cuando un adulto llega al parque, debe tener dinero suficiente para pagar su entrada, la de los niños de los que es responsable, ..."

¿En qué parte se especifica el precio de entrada al parque? No lo encuentro en el enunciado 😭

**Comment by BcruzUC** [comment]
En el archivo de attractions.csv estan los precios por atraccion.

Sumandome a tus dudas, el adulto paga por atraccion, por lo que no habria precio de incorporacion al parque? habrian 3 operadores por atraccion entonces? o al principio nomas donde tienen que ir a comprar los boletos para cierta atraccion? (eso significaria un tiempo para ir a comprarlos)

**Comment by llloyola** [comment]
Sí, en _attractions.csv_ están los costos de cada atracción, pero en el enunciado, en mas de una ocasión, se habla de precio de entrada a _nebiland_ y no sé de dónde sacar ese valor.

Pd: Espero no esté en el enunciado y quedar como gil jajaja 😅

**Comment by clementeross** [comment]
Me pasa lo mismo que no encuentro el precio de entrada al parque!

**Comment by BcruzUC** [comment]
@llloyola ya seriamos 3 los giles, entonces jaja Tampoco lo pille en ninguna parte. E igual me dan dudas de porque hay precios por atraccion, si se supone que hay un precio por entrar al parque..

**Comment by JorgeBdelaT** [comment]
+1

**Comment by nachocontreras** [comment]
Hola!

La entrada al parque es totalmente GRATIS!!

Éxito en la tarea! 😄

**Comment by nebil** [comment]
Porque desde el día 1, ese ha sido el compromiso de Nebiland: diversión gratuita y de calidad.

(Bueno, o al menos gratuita nomás. Y me refiero únicamente a la entrada.)
