### ISSUE TITLE
Consulta sobre tipo de dato a retornar

### ISSUE THREAD

**Issue by mVal919** [IIC2233/Syllabus#529]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, buenas tardes.
¿A que retorno le creemos?
A este:
![image](https://github.com/user-attachments/assets/31dccf3d-4a43-4960-ae03-08f975f3b104)
O a este:
![image](https://github.com/user-attachments/assets/13e5eb4c-0ed2-4d23-b923-2625af6a2cbe)
Porque uno pide que se retorne un str, y el otro un iterable.
Eso, muchas gracias otra vez.

**Comment by sheinkzx** [comment]
No se si puedo comentar, pero creele siempre al enunciado, mas adelante igual hay varias contradicciones

**Comment by mVal919** [comment]
Si, así vi mas adelante.
Gracias igual!

**Comment by wintermelyn** [comment]
Hola @mVal919!

Lamento la tardanza pero efectivamente confirmo que el enunciado manda. 🧙‍♂️
