### ISSUE TITLE
Duda sobre clases abstractas

### ISSUE THREAD

**Issue by tolavarria** [IIC2233/syllabus#529]
Hola, aún no entiendo la utilidad de una clase abstracta. En el caso de que nunca voy a instanciar una clase madre, solo sus clases hijas ¿de que me sirve definir metodos abstractos en la clase madre en vez de métodos normales? 
y otra duda: ¿es absolutamente necesario hacer levantamiento de errores mediante raise? porque de todas maneras, si sale un error, será capturado por los except, no?

**Comment by fdoflorenzano** [comment]
Hola @tolavarria,

Como expuesto en las [reglas de foro](https://github.com/IIC2233/syllabus/issues/1) (punto 7), por favor intenta no mezclar dudas y temas en una sola *issue*. Me centraré en esta *issue* en el primer tema, puedes abrir otra con tu segunda duda.

Saludos.

**Comment by tolavarria** [comment]
ok, mala mía

**Comment by fdoflorenzano** [comment]
Sobre las clases abstractas, tienen varias ventajas y aristas que considerar, pero su utilidad principal es una de **modelamiento de entidades**.

Básicamente permiten crear un esqueleto o base de otras entidades, y permiten definir comportamiento mínimo que deben presentar, y también comportamiento común. El comportamiento mínimo que exige es aquel definido por los métodos abstractos, que toda subclase debe implementar. El comportamiento común lo provee mediante herencia regular, donde es posible utilizar definiciones generales, e incluso la implementación dentro de un método abstracto.

Si bien todo lo anterior se puede lograr sin "hacer abstracta"  la clase y métodos, en términos de modelación sería menos correcto, ya que tu código permite la instanciación de una clase "esqueleto" que no necesariamente implementa todo su comportamiento, y que no tiene sentido existiendo por si sola.

Espero se entienda, si tienes dudas más específicas, escribe nomás.
Saludos.
