### ISSUE TITLE
Problemas con el path de imagenes

### ISSUE THREAD

**Issue by elpelaoloco** [IIC2233/syllabus#529]
* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* x[ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, hice mi ventana en qt designer y quiero modificar una imagen on keypress event, la señal funciona bien pero la foto se cambia a nada, supongo que es por  que esta malo el path que le pongo al pixmap, para esto ocupe funciones como path.exist, path.dir y path.isfile, todas me tiraron false. Intente poner el path de muchas formas distintas y aun no me funciona.

**Comment by valerianazal** [comment]
Hola @elpelaoloco !! Si puedes subir los cambios a tu repo para poder ver bien qué pasa :)
Quedo atenta!

**Comment by elpelaoloco** [comment]
los acabo de subir. lo que menciono  es en la ventada de preparacion

**Comment by valerianazal** [comment]
Lo revisé y el problema es que no utilizas `os.path.join` de manera correcta. De la manera en que lo estás haciendo tu ruta te quedaría: `"png\sprites\Personajes\Homero\right_2.png"` La forma adecuada de hacerlo sería la siguiente: `os.path.join("sprites", "Personajes", "Homero", "right_2.png")` .
La gracia de utilizar `path.join` de la librería `os`, es que la ruta se armará de acuerdo al sistema operativo en el que se corra el programa. Si la escribes de la forma que te mostré,  cada coma se reemplazará por "/" o "\", dependiendo del sistema operativo.
Avísame si se resuelve tu problema 😄

**Comment by elpelaoloco** [comment]
siiiii funciono, me arreglaste la vida. Muchas gracias
