### ISSUE TITLE
Preferencias de puesto al comprar snack o almuerzo

### ISSUE THREAD

**Issue by MrEarle** [IIC2233/Syllabus#529]
Existen casos donde un MiembroUC va a comprar un snack, pero no tiene a ningun vendedor de snacks en sus preferencias.
En un caso como este, eligen un puesto de snacks al azar? O van al quick devil?

**Comment by valeria-adasme** [comment]
Me sumo a la duda :s

**Comment by cilopez** [comment]
Se van a _Quick Devil_
