### ISSUE TITLE
Ambos deportistas se lesionan en la competencia

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#529]
Hola!! ¿Qué pasa en el caso que ambos deportistas se lesionen en una competencia? ¿Es un empate?

**Comment by hsazos** [comment]
¡Hola @denisseleiva !

Como no esta en el enunciado, queda a tu criterio. Pero me imagino que lo que tu dices es correcto, sería un empate.

¡Animo en la tarea!🦕

**Comment by denisseleiva** [comment]
Bacan, gracias!!
