### ISSUE TITLE
Rotacion de imagenes

### ISSUE THREAD

**Issue by rfenzo** [IIC2233/Syllabus#529]
He estado buscando por arto tiempo como rotar una imagen, para que vaya siguiendo el mouse, mi problema es que al rotar la imagen (QPixmap dentro de Qlabel) se rota de acuerdo a la esquina superior izquierda del QLabel en vez del centro de mi imagen, podrían darme un tip de como cambiar el origen de un QLabel, o como hacer la rotacion de manera alternativa?.

PD: estoy ocupando QTransform para hacer la rotacion.

Gracias

**Comment by Hernan4444** [comment]
@rfenzo PyQt está programado por debajo por c++, te recomiendo buscar por [qtransform rotate around center](https://www.google.com/search?q=qtransform+rotate+around+center&oq=QTransform&aqs=chrome.1.69i57j69i59j0l4.1341j0j4&sourceid=chrome&ie=UTF-8) y revisar código en c++ que solucionan ese problema.

hint: Tal vez podrías intentar rotar y luego trasladar.

Saludos

**Comment by hanavarrete** [comment]
Otro hint: podrías rotar segun em
Cuadrante en el que estás. Saludos!!

Hugo Navarrete

**Comment by KnowYourselves** [comment]
Hola!, Intentando ver el tema de la rotación intente centrar las imagenes del label mediante el uso de `setAlignment(Qt.AlignCenter)` pero inlcuso utilizando este método la posicion de mi label sigue siendo en la esquina superior derecha, alguna razón para esto? Gracias!

**Comment by hanavarrete** [comment]
Ocupa conocimientos de geometría para rotar el pixmap según la posición que se encuentre tu objetivo (mouse en este caso) y tu personaje. Esa es una manera más bruta pero simple de hacerlo.

**Comment by acrojas2** [comment]
Con respecto a esto, mi mono rota cuando el mouse esta dentro de su label pero cuando esta fuera, ya no lo hace, que pasa con esto? está bien que ocurra? sino, como podría solucionarlo, ya que lo que hice fue poner setMouseTracking(True) en el label del campeon y en el widget. No veo como el label del campeon pueda captar el mouse fuera de su área.
Espero se entienda mi duda...

**Comment by KnowYourselves** [comment]
@acrojas2 Una forma de solucionar esto sería usando señales (haciendo una señal que envie la posicion del mouse a tu campeón) o hacer esta rotación a nivel de MainWindow (donde puedes acceder tanto a la posicion de tu campeón como del mouse)

**Comment by hanavarrete** [comment]
tal como dice @KnowYourselves  esas son dos maneras de solucionar tu problema. Creo que la más fácil es hacer la rotación a nivel de mainwindow. De todas formas, a que te refieres con que esté "fuera de su label?" porque mientras este rote en la pantalla de juego todo bien. No debería haber problema que no rote si no estás ahí.

**Comment by acrojas2** [comment]
Supongamos que la posición de mi mono es (5,5) en la convención del widget (esquina superior izq), el área es de 5x5 por lo que si el mouse esta en la coordenada _(45, 60)_ el mono no rota (mouse fuera del label del mono) pero si el mouse está la posición _(7, 8)_ (mouse dentro del label del mono) si rota y lo hace bien. La rotación se hace en la gamewindow (widget de juego) que vendría siendo mi _frontend_ y se conecta por medio de señales con métodos del campeón. Probé sacando el setMouseTracking en el init  del campeón y dejó de funcionar. :(
