### ISSUE TITLE
Duda código base cliente_tcp

### ISSUE THREAD

**Issue by pazanelli** [IIC2233/syllabus#529]
Tengo dudas respecto a qué hace esta linea del código base del cliente de tcp:
`sock.sendall('GET / HTTP/1.1\n\n\n'.encode('ascii')) `
¿Es simplemente un` str` que  puedo recibir e imprimir de la misma forma que para el mensaje que envía el servidor? ¿O tiene alguna función particular?

**Comment by fdoflorenzano** [comment]
Hola @pazanelli, buena pregunta. 

#### Respuesta corta:
Para efectos generales, es solo un *string*, que se codifica a como *bytes* con `encode`, que se está enviando a través de un *socket*, desde un cliente hacia un servidor.

Ahora, hay una razón para su contenido y estructura. La respuesta se escapa de lo que tocamos en el material de *networking*, así que puedes optar a no entenderlo completamente, o ni leer lo siguiente, pero creo es interesante de saber.

#### Respuesta larga:
¿Por qué tiene ese contenido y forma? Es por el servidor, que corresponde al servidor de una página web (python.org). En la web, también se ocupa TCP para mantener la conexión y enviar mensajes, pero esto es solo al nivel de **transporte** (una de las capas de conexión que se mencionan en el material). En la web además se utiliza HTTP que es un protocolo de **aplicación**, es decir, es la forma en que se estructuran los mensajes entre clientes y servidor para que se entiendan entre ellos. 

A modo de ejemplo: digamos tu montas un servidor, y yo creo un cliente para conectarme. Podemos usar TCP para realizar efectivamente la conexión, pero si no establecemos reglas o un molde de como nos mandaremos mensajes, nuestros programas tendrían que abarcar muchos escenarios. Entonces nos podemos poner de acuerdo a que si yo te mando el *string* `"hora"`, eso significa que quiero saber que hora es, pero si te mando `"tiempo"` quiero saber el clima. Así tu servidor sabrá que responder en cada caso, y el resto no los soportas simplemente. HTTP sigue esa misma idea, son reglas de como enviarse mensajes entre cliente y servidor para entenderse entre ellos. Definen palabras para distintas acciones, y un formato para enviar datos de contenido.

Específicamente, el contenido `GET / HTTP/1.1` tiene dos partes: 
- `GET` es un verbo que especifica que acción quiere realizar el cliente. Quiere **obtener** algo (*get*)
- `HTTP/1.1` establece el tipo y versión del protocolo a utilizar en la comunicación. Será HTTP en su versión 1.1
El resto del mensaje se manda vació.

Como se manda un mensaje "con sentido", el servidor responde inmediatamente un mensaje de contenido prohibido, ya que no pedimos nada específico y probablemente la página tiene restringido el tipo de contenido que cualquiera puede acceder.

Si llegamos a mandar cualquier otra cosa al conectarnos con el servidor de python.org, por ejemplo un "hola": `sock.sendall('hola'.encode('ascii'))`, notarás que la respuesta del servidor demora en llegar. Eventualmente se recibe un mensaje:
```
HTTP/1.0 408 Request Time-out
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html><body><h1>408 Request Time-out</h1>
Your browser didn't send a complete request in time.
</body></html>
```

Que en resumen dice que no se mandó una solicitud al servidor **completa**. Es decir, se quedó esperando el resto del mensaje por algo con sentido al protocolo HTTP. 

Para efectos prácticos de lo que les pediremos en el curso no es tan relevante, ya que por lo general haremos conexiones entre servidores y clientes propios, no servidores web. Pero, sigue siendo interesante para entender como se comunican estas cosas en la web, y que debe existir un protocolo de mensajes para que se entiendan. 

Espero se entienda. Si estás interesade en aprender más del tema o te quedó alguna duda, puedes escribirnos 😄 .

Saludos.
