### ISSUE TITLE
Problema para leer archivos en VSCode

### ISSUE THREAD

**Issue by FelipeUC2020** [IIC2233/Syllabus#53]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tratando de trabajar con los archivos entregados en la tarea, VSCode no reconoce el path que le estoy entregando.

<img width="781" alt="Screen Shot 2021-08-31 at 17 08 33" src="https://user-images.githubusercontent.com/89170076/131577472-31e7eaee-27e4-4b52-ab99-3f3422d44378.png">

<img width="634" alt="Screen Shot 2021-08-31 at 17 19 38" src="https://user-images.githubusercontent.com/89170076/131577328-6667f2bb-054b-4d7d-99cd-f837d8de19e9.png">

¿Alguien sabe a qué se debe?

**Comment by pabloist** [comment]
Hola!

Al momento de abrir archivos es importante verificar en que "parte" se encuentra ubicado nuestro proyecto y script para lo cual es súper útil utilizar  el siguiente código:

**import os 
dir_path = os.path.dirname(os.path.realpath(__file__))**

Como puedes ver en la consola, tu archivo main.py desde donde se ejecuta (y probablemente donde tu proyecto se encuentra) está en la misma carpeta que el archivo ("T0"), por lo que al intentar buscar la carpeta "__syllabus__" obviamente no la encuentra; por lo que bastaría con solo llamar el nombre particular del archivo en este caso y no las carpeta madre.

Saludos!

**Comment by FelipeUC2020** [comment]
Hola, el proyecto lo estoy ejecutando en la carpeta de mi repositorio personal: FelipeUC2020-iic233-2021-2/Tareas/T0/main.py , al llamar el nombre particular del archivo con los datos me arroja el mismo error.
¿Tendrá que ver con los nombres que asigné a mis carpetas?

Saludos.

**Comment by pabloist** [comment]
Verifica que en tu repositorio personal tienes dichos archivos, porque están en el syllabus por lo que veo (que son rutas distintas).

**Comment by sachondo7** [comment]
hola! yo tengo el mismo error, intento abrir el archivo usuarios.csv, que lo tengo en la misma carpeta que la tarea y me arroja un error.
me pueden ayudar porfavor?
<img width="955" alt="Screenshot 2021-08-31 at 21 55 22" src="https://user-images.githubusercontent.com/80768647/131599103-8ea6212f-ae04-46c8-9121-5d1b98f787b3.png">
<img width="244" alt="Screenshot 2021-08-31 at 21 55 32" src="https://user-images.githubusercontent.com/80768647/131599108-378c12bd-22cd-4344-b81e-7f2e46eded75.png">

**Comment by kunafuego** [comment]
Hola @sachondo7 . Probablemente te aparece ese error porque tu terminal está en otra carpeta a la hora de correr tu código. Intenta corriendo tu código manualmente desde tu terminal. Esto te va a obligar a moverte hasta el directorio de la tarea antes de correr el código. Debes ocupar el comando `cd` para moverte entre directorios, y una vez dentro de T0, debes correr la script escribiendo `python main.py`.
