### ISSUE TITLE
Consulta contenidos a evaluar A1

### ISSUE THREAD

**Issue by juanivegam** [IIC2233/Syllabus#53]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido

[Hola quería consultar si la actividad del jueves estará más enfocada en los contenidos de esta semana o de la semana 0 y 1 también. Muchas gracias de antemano por la respuesta]

**Comment by Juampisaez** [comment]
Holaa @juanivegam 👋🏼
Las actividades, tal como se mencionó en la clase de bienvenida, estarán enfocadas en los contenidos de la semana que se realice la actividad (a menos que se diga lo contrario).

Quedo atento cualquier cosa
Saludos,

**Comment by juanivegam** [comment]
Muchas gracias!
