### ISSUE TITLE
Duda sobre los caracteres en el Excel de mensajes.csv

### ISSUE THREAD

**Issue by Gazteka** [IIC2233/syllabus#53]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
Duda sobre los caracteres en el Excel de mensajes.csv
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]
Pasa que descargue el csv y en los mensajes, especificamente en las palabreas que tienen tilde aparecen simbolos extraños en vez de la letra, asi :
regular,Christian-Klempau,roberto009,2020/06/24 04:44:44,Konnichiwa! Me robÃ© su corazÃ³n. Bai.

los mensajes son asi ? tenemos que descifrar como cambiarlos? o si estan asi los puedo dejar como estan sin problema, pense que quizas podia ser un problema al descargar o del encoding pero ya revise y el csv viene asi :(

**Comment by Juampisaez** [comment]
Hola @Gazteka 
Probablemente abriste el csv en excel, ahí te aparecen los mensajes como tu dices. Te recomendaría abrir el archivo en un editor de codigo (vscode por ejemplo) y notaras que no ocurre eso. De igual manera, para leer los archivos en python puedes probar utilizando el `encoding="utf-8"` al abrir el archivo e imprimir si contenido (si no resulta, no coloques el encoding e imprime igual el contenido).

Avisame si se soluciona el problema :)

**Comment by Gazteka** [comment]
sii ahi funciono, cuando lo revise me decia que tenia encoding cp1252, me parecio extraño pero con el utf-8 funciona bien, gracias!

**Comment by mateogs** [comment]
hola, resulta que tengo un problema parecido.
Al imprimir los mensajes en consola me salen con caracteres extraños y según VSCode estoy usando utf-8 :/

**Comment by Juampisaez** [comment]
Hola @mateogs 
No se si probaste tambien cargando el archivo sin el `utf-8`

Avisame :)

**Comment by mateogs** [comment]
Lo solucioné agregando  encoding="utf-8" en el open. 
Muchas gracias.

**Comment by Juampisaez** [comment]
@mateogs oka! no se que pudo haber sido entonces jejeje

**Comment by cseverino99** [comment]
Holaa, yo revisé el encoding y es uft-8.. pero al imprimir los mensajes me siguen saliendo caracteres extraños

**Comment by Juampisaez** [comment]
Hola @cseverino99  
Mm, lo que podrias hacer es usar los archivos de la repo donde esta la tarea. Y tratar de abrir los archivos utilizando el encoding "utf-8", imprimir y ver si se imprime bien en consola.

Avisame si funciona

**Comment by cseverino99** [comment]
@Juampisaez ya me funcionó con otro issue que lei... usando encoding = "utf-8" dentro del open!! gracias
