### ISSUE TITLE
Duda sobre la carpeta "partidas"

### ISSUE THREAD

**Issue by pazanelli** [IIC2233/syllabus#53]
Al momento de guardar un archivo en la carpeta "partidas", ¿puedo asumir que esa carpeta va a existir? ¿O tengo que verificar si existe y en el caso de que no, crearla y luego guardar el archivo?
Además, si es que puedo asumir que existe, puedo asumir también que está en el mismo directorio que el archivo.py del código? O tengo que buscarla

**Comment by gatochico** [comment]
Hola!

Todo lo que preguntas queda a tu criterio: Si deseas asumir que la carpeta ya existirá, puedes hacerlo (ya sea agregando una carpeta vacía a tu repositorio siguiendo los pasos de la issue #27, o simplemente pidiendole al ayudante en tu README que la cree antes de ejecutar tu tarea), y si quieres verificar por tu cuenta si existe y crearla si no, también puedes hacerlo (aunque no tendrá puntaje adicional). 

Con respecto a la ubicación de dicha carpeta, puede estar también donde tu quieras, poniendola tú si decides subir una carpeta vacía a tu repositorio, o nuevamente avisándole al ayudante en el README donde poner la carpeta para que tu programa funcione.

Saludos y éxito con la tarea!
