### ISSUE TITLE
pycharm indentación y if __name__ == "__main__":

### ISSUE THREAD

**Issue by RicardoFDQ** [IIC2233/syllabus#53]
Hola el tema de la indentación cuando una apreta enter ¿ se considera como tab?.
¿es necesario usar el if __name__ == "__main__":?, aunque no lohe visto en profundidad.

**Comment by Dnpoblete** [comment]
Hola @RicardoFDQ , con respecto a tu pregunta de indentación en pycharm hay una forma de configurar cuantos espacios equivalen a cada enter, por lo que puede ser que venga predeterminado con una cantidad diferente de espacios. Te recomiendo que lo verifiques y veas que efectivamente equivale a cuatros espacios para que no tengas problemas.  Y con respecto al uso de if __name__ == "__main__":, no es necesario pero es recomendable ya que es una buena practica, por lo que podrías tratar de implementarlo de a poco, si tienes dudas siempre puedes pedirnos ayuda.

Si tienes alguna duda avisame para poder ayudarte :smile:
