### ISSUE TITLE
Contenido semana 02 (Properties)

### ISSUE THREAD

**Issue by SVenegasA** [IIC2233/Syllabus#53]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
En la celda de código 5, **¿Por qué en el método setter se está recibiendo un parámetro "p"?¿Qué es el "p"?**

**Comment by Mamunoz42** [comment]
Hola @SVenegasA!

Espero estés teniendo una muy buena semana. Lo que hace `setter` es manejar el como puede ir cambiando el valor del atributo con el que se está trabajando, en este caso, `self.__personas`. El `setter` al corresponder a un método, primero recibe al self, y luego recibe otro parámetro, el cual corresponde al valor con el que quedaría nuestro atributo una vez se le haya hecho la operación que hizo que se ejecutara el setter.

Como se vio en el siguiente diagrama presentado en la Ayudantía del día martes:
![imagen22](https://user-images.githubusercontent.com/62019329/159935199-311a9d88-3d45-4e6b-bc5c-3c77a51e1c21.jpg)
El valor `p` del que hablas corresponde en el caso de la imagen a todo lo que está al lado derecho del signo igual, correspondiente al valor con el que quedaría nuestro atributo tras hacerle un cambio.
