### ISSUE TITLE
Archivos .csv

### ISSUE THREAD

**Issue by fdominguezclaro** [IIC2233/Syllabus#53]
Hola, 
En el punto 4.1 del enunciado, mencionan que los archivos .csv pueden variar el orden de sus columnas. Esto se refiere a que los archivos .csv que ustedes van a usar, puede que tengan un orden distinto a los que tenemos nosotros para realizar la tarea?

Gracias!!

**Comment by Hernan4444** [comment]
@fdominguezclaro es exactamente como dices. Usaremos archivos con otro orden!!!
Saludos!!

Pd: Tanto en #44 y #37 se hicieron preguntas sobre archivos csv, por favor revisar antiguas issues antes de abrir una nueva c:
