### ISSUE TITLE
Programación Circular

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2233/Syllabus#53]
¿¿Se puede utilizar programación circular para la tarea??

**Comment by rihanuch** [comment]
Hola @joaquineichholz !!

De poder _se puede_ y no habrá descuentos por ello, _pero_ es **altamente recomendado no hacerlo** ⚠️ , por varios motivos, entre ellos los siguientes:

1. Es mala práctica ☹️
2. Se genera código **altamente [acoplado](https://en.wikipedia.org/wiki/Coupling_(computer_programming))** (poco práctico en muchos sentidos)
3. A pesar de que ```Python``` 🐍  te deje hacerlo eso **no significa** que esto no pueda repercutir en tu código 👀 

Quizás te pueda servir leer una [issue](https://github.com/IIC2233/Syllabus-2017-2/issues/88) similar que surgió el semestre pasado 🔙 ~(en la cual yo también estaba haciendo esta mala práctica 😬)~

A pesar de que aún no tengan toda la materia para entenderlo (lo verán más adelante 🔜), por lo que te dejo la explicación a continuación

----
En general, lo más típico es que cuando una clase es _"dueña"_ de otra, y estos objetos necesitan conocer la información 🔍 de la _dueña_ para poder funcionar correctamente, por ejemplo:

```Python 
class Jefe:

    def __init__(self):
        self.observando = False
        self.trabajador = Trabajador(self)
        self.billetera = 1000000000000


class Trabajador:

    def __init__(self, jefe):
        self.jefe = jefe
        self.billetera = 1

    def dejar_de_trabajar(self):
        if self.jefe.observando:
            print("Debo trabajar")
        else:
            print("Puedo perder el tiempo :D")
```

Como puedes ver, el ```Trabajador``` puede acceder a ***todas*** los atributos de su ```Jefe``` (incluyendo su billetera 💸), lo cual en la vida real no tiene sentido (a menos que robes... 🙄), entonces, ¿por qué aquí lo tendría?

En```Python``` las funciones son objetos, por lo que se puede pasar el estado actual de algún atributo del ```Jefe``` sin tener que darle toda la información al ```Trabajador``` ℹ️ (por ejemplo cuanto 💵 tiene en su billetera) mediante el uso de decoradores (materia que verán más adelante). 

El código corregido 👨‍💻✅ quedaría de la siguiente manera:

```Python
class Jefe:

    def __init__(self):
        self.observando = False
        self.trabajador = Trabajador(estoy_observando())
        self.billetera = 1000000000000

    def estoy_observando(self):
        def _estoy_observando():
            return self.observando
        return _estoy_observando


class Trabajador:

    def __init__(self, me_estan_mirando):
        self.me_estan_mirando = me_estan_mirando
        self.billetera = 0.00000000001

    def dejar_de_trabajar(self):
        if self.me_estan_mirando():
            print("Debo trabajar")
        else:
            print("Puedo perder el tiempo :D")
```

La función ```estoy_observando``` está decorando ✨ (insisto, lo verán más adelante) y retorna una función, y esta segunda función ```_estoy_observando``` es la que realmente me retorna el valor de ```observando```, por lo que el único atributo que el ```Trabajador``` puede "ver" de su ```Jefe``` es si lo están observando o no, para así poder ver si puede dejar de trabajar 😴. Además, de esta manera, ¡la billetera está a salvo 🤑!

**Comment by joaquineichholz** [comment]
Gracias!! tratare de no caer en programación circular.. jajaja tengo que mdificar un par de cosas

**Comment by naquiroz** [comment]
Tengo una duda respecto a al ejercicio anterior.

```Python
class Auto:
    def __init__(self):
        self.conductor: Conductor = Conductor()
    
    def encender(self):
        print('Encendiendo...')


class Conductor:
    def __init__(self):
        pass
    
    
    def encender(self, auto: Auto):
        auto.encender()
```

El siguiente caso seria considerado como programacion circular?

**Comment by rihanuch** [comment]
Hola @naquiroz !!

Según lo que entendí de tu código sí 😬 
Imaginemos que defines ```Auto``` y ```Conductor``` de la siguiente manera:

```Python
class Auto:
    def __init__(self):
        self.conductor: Conductor = Conductor()
      
    def encender(self):
        print('Encendiendo...')

    def explotar(self):
        print('No me  detones por favor :(')

class Conductor:
    def __init__(self):
        pass
    
    
    def encender(self, auto: Auto):
        auto.encender()

   def morir(self):
      print("voy a morir!!")
```


Tu podrías hacer detonar el auto 🚗💥,  si lo quisieras desde el método ```encender``` lo que significaría que, al fin y al cabo, igual puedes acceder a *todo* lo que la clase ```Auto``` posee. Además de esto, ```Auto``` podría llamar a ```morir```, por lo que se estaría "cumpliendo" así con lo que sería una moderación circular 🌀

PD: corrígeme si me equivoco en esto, ahí estarías utilizando el módulo ```typing```, ¿o no? 🤔 (Lo digo para que lo tengas en mente si lo utilizas en tu tarea, ya que no se ha dicho que se pueda utilizar en la issue #21 

Saludos! 🍀

**Comment by naquiroz** [comment]
@rihanuch Técnicamente no es el modulo typing dado que la clase Auto es creada por mi, no importada, pero si, en la tarea estoy usando typing, supuse que se podria usar, asi que ahora emití una _issue_.

**Comment by rihanuch** [comment]
@naquiroz , ¡perfecto! 👍

¡Recuerda no asumir este tipo de cosas, ya que en un futuro te podría pasar que se te haga un descuento por utilizar un módulo no permitido o sin permiso! 👀

¡Éxito!🍀👨‍💻
