### ISSUE TITLE
Definición de funciones en functions.py vs. módulo auxiliar

### ISSUE THREAD

**Issue by c4ebt** [IIC2233/Syllabus#53]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Del enunciado:
![image](https://user-images.githubusercontent.com/50504998/227079843-9b6eca84-56c0-4f50-bb65-f30793d88ecc.png)

El enunciado dice que solo se asignará puntaje si las funciones pedidas están definidas en `functions.py`.
**Es válido definir "interfaces" para las funciones en `functions.py` pero definir las funciones reales en un módulo auxiliar?**

Ejemplo:
```python
# Archivo: functions.py
import modulo_auxiliar

def funcion_requerida(argumento: tipo) -> tipo_retorno:
    return modulo_auxiliar.funcion_requerida(argumento)
```
```python
# Archivo: modulo_auxiliar.py

def funcion_requerida(argumento: tipo) -> tipo_retorno:
    [código que debe realizar la funcion requerida en el enunciado]
```
En estricto rigor las funciones _están definidas en `functions.py`_, pero quería sacarme la duda de todos modos.

**Comment by jtagle2** [comment]
Si, no hay problema con que hagas otras funciones en otro módulo. Lo importante, es que las funciones que se piden en el enunciado estén en el archivo functions.py, y que estas hagan lo pedido.
