### ISSUE TITLE
Problema con designer

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#53]
- **Sistema Operativo:**
Windows 10
- **Programa a instalar:**
designer
- Foto del error:

- Descripción del problema:
Ya instale con pip pyqt5 y pyqt5-tools pero cuando uso designer en la consola me tira: 
bash: designer: command not found
y cuando lo busco en el buscador del pc tampoco me sale que existe

**Comment by gatochico** [comment]
Hola! 

Prueba corriendo en la consola o buscando en el buscador de windows `pyqt5designer`. Si no encontraste designer con ninguna de esas dos opciones, te recomiendo descargarlo directamente desde [aquí](https://build-system.fman.io/qt-designer-download).

Avísanos cómo te va!

**Comment by YehudaGurovich** [comment]
Funcionó al instante! Gracias.
