### ISSUE TITLE
Problema con error de Python

### ISSUE THREAD

**Issue by solebravo** [IIC2233/Syllabus#53]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, la verdad no estaba segura si esto pertenece a este foro, pero como me está sucediendo en la tarea lo mando por aquí. Lo que pasa es que estaba creando una función y me aparecía un error de syntax (SyntaxError: invalid syntax), no encontré ningún error, pero de igual manera la reescribí. El problema fue que después de esto, todas las veces que corro mi código me aparece el mismo error, aun cuando antes corría bien, o el archivo de Python son solo prints y la verdad es que no se muy bien que hacer con esto. 
Gracias de antemano.

**Comment by Lord-Kelsier** [comment]
Hola, este foro es para todas las dudas no relacionadas con temas administrativos o personales como se menciona en los prerrequisitos (Por lo que sí, este es el foro indicado🦉).

### Con respecto a tu problema...
Como veremos mas adelante en el curso, existen distintos tipos de errores en python y en este caso el tipo es: `SyntaxError`, lo que indica que no escribiste de manera correcta la sintaxis de python. Los siguientes son errores de sintaxis:

```python 
def funcion() #-> faltan los dos puntos ":"
  return

print("hola" #-> falta cerrar parentesis

for in range(10): #-> falta colocar una variable entre el "for" y el "in"
```
Puede suceder tambien lo siguiente: 
Tenemos dos archivos:
1) `error_de_sintaxis.py`:
```python 
def funcion()
 return
```
2) `funciona_perfecto.py`:
```python
print("hola")
```
El archivo 1 tiene un error de sintaxis y el 2 funciona perfecto, pero si ahora importo el archivo 1 en el 2:
2) `funciona_perfecto.py`:
```python
import error_de_sintaxis
print("hola")
```
ahora al ejecutar el archivo 2 nos arroja error de sintaxis
