### ISSUE TITLE
Sobre el absolute path

### ISSUE THREAD

**Issue by jearaneda** [IIC2233/syllabus#53]
Hace poco actualizaron los Descuentos , incluyendo el uso de absolute en vez de relative paths. Lo que no entiendo es cómo aplico esto en el programa, pues después de todo estamos usando un repo y no tenemos forma de saber en qué carpeta descargarán nuestros archivos.

O quizá leí mal y el descuento es por usar absolute paths cuando tenemos que usar relative paths?

**Comment by BFFV** [comment]
El descuento es por usar absolute paths en vez de relative paths.
Suerte en la tarea!
