### ISSUE TITLE
[Tarea 3] Foto perfil: Roles cliente-servidor

### ISSUE THREAD

**Issue by Tito0906** [IIC2233/syllabus#530]
Holaa ! Respecto a los roles de Servidor - Cliente - Frontend, tenía varias dudas de las "responsabilidades" de cada uno cuando se carga la foto de perfil o se usa el filtro dibujo. 

1) Entiendo que Servidor debe tener una base de datos, pero la base de datos debe guardar el path de la imagen, el nombre o toda la imagen?

2) Quién queda como "responsable" del filtro dibujo? Lo que debe suceder es que cliente cargue la foto y se la envía a Servidor y éste realiza el filtro, guarda y vuelve a enviar la foto filtrada a cliente o si cliente debe realizar el filtro y después sólo manda la foto filtrada o los datos que se deban guardar a Servidor.

**Comment by ariel-m-s** [comment]
¡Hola, @Tito0906!

1. ¿Puedes elaborar un poco más este punto? ¿Cómo podría el servidor tener el _path_ de la imagen pero no el archivo en sí?

2. La primera opción que mencionas es la correcta. Tal como explica el enunciado, todo lo que es lógica y procesamiento de datos lo ve el servidor. Esto incluye la aplicación del filtro.

Quedo atento.

**Comment by Tito0906** [comment]
Holaa, muchas gracias por contestar. Sobre la primera pregunta, me refiero a si Servidor sólo guarda el path de la imagen que entrega el cliente, por lo que al cargar se lo manda a cliente y cliente carga la foto a partir del path. Si no es así, debe ser que Servidor almacena el archivo completo y envía los datos a cliente?

**Comment by ariel-m-s** [comment]
El servidor se debe encargar del almacenamiento de todos los datos, incluyendo la imagen en sí. Este le deberá enviar la imágen al cliente cuando se necesite utilizar (para mostrarla en pantalla).

¡Éxito con la tarea!

**Comment by furzuadr** [comment]
Hola! @ariel-m-s , a qué te refieres con que el servidor debe enviar la imagen en sí? Puede enviar el path de la imagen alojada dentro del server? Debe enviar la matriz y el frontend transformarla a png o cómo sería? 

Actualmente mi secuencia es:
1) Jugador elige el path de la imagen desde el frontend
2) Se envía el path del frontend al client mediante una señal
3) Se envía al server el path de la imagen
4) El server agarra el path, crea la matriz leyendo ese path original, y luego la convierte en un png que lo guarda dentro de la carpeta server.
5) El server envía al client el path nuevo de la imagen alojada en el server. y este al frontend.

Está bien? O sería más correcto que el frontend lea el path, lo envíe al cliente, el cliente transforme a matriz y mande la matriz al server? Me imagino que esto es correcto, debido a que si el server está en otro computador, mi paso 4 no funcionaría.

Gracias!

**Comment by ariel-m-s** [comment]
¡Hola, @furzuadr!

No te puedo decir detalladamente cuál es el flujo, cómo debe ser la comunicación entre el servidor y el cliente ni qué tipo de datos se deben transmitir. Sin embargo, ten en cuenta lo siguiente.

* El servidor es el encargado de almacenar toda la información (esto incluye la imágen). La manera en la que se almacena la información queda a tu criterio, siempre y cuando no viole ninguna de las restricciones del enunciado.

* El cliente y el servidor deben poder funcionar en computadores diferentes, por lo que intentar abrir un archivo que le pertenece a la contraparte estaría contradiciento este punto y podría causar que tu programa se caiga.

* El formato en el que transmites la información entre el cliente y el servidor queda a tu criterio. Sólo te debes asegurar que se haga a través del los protocolos TCP/IP.

Saludos.
