### ISSUE TITLE
Problema con keyPressEvent

### ISSUE THREAD

**Issue by antoniafuica** [IIC2233/syllabus#530]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
No me funciona el método keyPressEvent con las letras, sólo se me activa cuando apretó botones como el enter, mayúsculas, espacio. Por qué podría ser esto? 

***Mi repertorio esta subido por cualquier cosa ***

**Comment by clementevalladares** [comment]
Hola @antoniafuica, podrías intentar utilizando el método self.setFocusPolicy(QtCore.Qt.StrongFocus) en la ventana que está ocurriendo el problema.
De todas formas revisaré tu código para ver si se trata de algo distinto.

**Comment by antoniafuica** [comment]
Me funcionó con ese método! Muchas gracias!
