### ISSUE TITLE
"volver atras" y "salir" al adoptar una DCCriatura y comprar alimento

### ISSUE THREAD

**Issue by vobrador** [IIC2233/syllabus#530]
Tengo duda de hasta donde debo dar estas opciones, según entiendo del enunciado es solo en los menues, pero que pasa si por ejemplo voy a comprar una criatura y al momento de nombrarla lo hago mal; ahí debería dar la de intentar de nuevo hasta que lo haga bien o dar las opciones intenta de nuevo, volver y salir?

**Comment by JosefaPaz** [comment]
Hola @vobrador , 

Como adoptar una DCCriatura o comprar alimentos es una acción y no un menú de por si, no es estrictamente necesario que tengan la opción volver atrás o salir, así que queda a tu criterio como desees implementarlo.

Éxito! 😸

**Comment by vobrador** [comment]
buenisimaa! gracias

**Comment by JosefaPaz** [comment]
@vobrador, conversando con otros ayudantes, es mejor que se siga el mismo criterio que cuando eliges tu DCCriatura al crear un Magizoólogo, tal como se explica en la issue #297. Es decir, si hay un error deberá volver a desplegar todas las opciones -de alimento o las DCCriaturas -para luego volver a elegir una.

Disculpa la confusión!

**Comment by JosefaPaz** [comment]
@vobrador, conversando con otros ayudantes, es mejor que se siga el mismo criterio que cuando eliges tu DCCriatura al crear un Magizoólogo, tal como se explica en la issue #297. Es decir, si hay un error deberá volver a desplegar todas las opciones -de alimento o las DCCriaturas -para luego volver a elegir una.

Disculpa la confusión!
