### ISSUE TITLE
No me funciona el metodo fichar deportistas #help

### ISSUE THREAD

**Issue by BFry712** [IIC2233/syllabus#530]
Hola! el metodo de fichar deportistas desde el menú del entrenador no me actualiza el dinero de la delegación ni la lista del equipo, estuve viendo la materia y arreglando más cosas pero no veo el error :c

**Comment by amparostevens** [comment]
Hola! 👋🏻

Te sale algún tipo de error o simplemente no funciona?

**Comment by BFry712** [comment]
hola! Me sale que siempre no tiene plata .a delegación del usuario y termina sin ficharlo :c

**Comment by amparostevens** [comment]
Primero, noté varias cosas con tu código que necesitas arreglar antes de entregar la tarea para no sufrir descuentos indeseados 😉 

- Tus __paths no son relativos__. Debes considerar que la tarea se corre desde tu carpeta llamada "T01", por lo tanto sólo debes llamar los archivos, a menos que los tengas en una capeta. Por ejemplo si en `datos` está `deportistas.csv`, para abrir el archivo basta con poner `os.path.join(datos, deportistas.csv)`.
- Estás usando `try/except`, el cual está __prohibido__
- Tienes varios números que deberían ir __parametrizados__
- No se si todas tus properties, pero al menos la que definiste para la moral está mal definida. El nombre que ocupas en el getter debe ser igual al del setter, como se muestra aquí:
``` 
@property
    def moral_(self):
      .....
@moral_.setter
    def moral_(self,nuevo_valor):
         ......
```

Ahora, con respecto a por qué no funciona tu método fichar, es porque nunca estaba retornando `True` ya que no se cumplían las condiciones definidas.
Siempre hay que fijarse en el __tipo de los atributos__ para poder hacer comparaciones. En tu caso, dinero estaba definido como un `str`, al igual que el precio del deportista y la moral, por lo tanto al intentar compararlos con un `int` nunca se iba a cumplir la condición del `if`. 

Hice los cambios pertinentes y al correr el código pude efectivamente fichar un deportista! :raised_hands:
Espero que te sirva y mucho éxito con la tarea! 🥇

**Comment by BFry712** [comment]
Muchisimas gracias! Te pasaste!!! 🥇 💯
