### ISSUE TITLE
Calculo nota

### ISSUE THREAD

**Issue by tgarcia4** [IIC2233/syllabus#530]
Hola tengo una duda en cómo se calculan las notas de las tareas, porque para las 2 primeras si hago:
(ptje obtenido/ptje máximo) * 6 +1 me da la nota que tengo pero no para la T02

**Comment by entamburini** [comment]
La tarea 02 tiene 106 puntos, no 90 como sale en el resumen de su feedback, sus notas fueron calculadas de manera correcta (con los 106 puntos).
