### ISSUE TITLE
Duda ganancias_producidas_en_los_pedidos

### ISSUE THREAD

**Issue by elisaorchard** [IIC2233/Syllabus#530]
Hola!! Estoy teniendo problemas con esta función. No sé qué hacer.

Puedo asumir que el generador_contenido_pedidos entregará los elementos por orden de id_pedido?

Gracias.

**Comment by wintermelyn** [comment]
Hola @elisaorchard!

No puedes ausmir que el generador_contenido_pedidos se entregará por orden de id_pedido. Esto lo puedes comprobar en los tests publicos de correctitud, por ejemplo el test1 de ganancias_producidas_en_los_pedidos entrega el siguiente generador_contenido_pedidos

```python
lista_entregada = [
            ContenidoPedido(
                id_pedido=1, nombre="Pepperoni Clásica_M", cantidad=1, descuento=0.0
            ),
            ContenidoPedido(
                id_pedido=4, nombre="Hawaiiana_M", cantidad=4, descuento=0.3
            ),
            ContenidoPedido(
                id_pedido=2, nombre="Pepperoni Clásica_M", cantidad=2, descuento=0.23
            ),
            ContenidoPedido(
                id_pedido=5, nombre="Camarones sobre ajo_S", cantidad=5, descuento=0.0
            ),
            ContenidoPedido(
                id_pedido=3, nombre="Vegetariana_M", cantidad=3, descuento=0.0
            ),
        ]

        generador_entregado_contenido_pedidos = (
            asociacion for asociacion in lista_entregada
        )
  ```

**Comment by elisaorchard** [comment]
Hola, gracias por tu respuesta. 
Más que por el orden en sí, lo preguntaba para poder usar itertools.groupby() por id_pedido, que sólo funcionaría si los contenido_pedidos del mismo id estám juntos. Pensé en usar sorted para asegurarme pero esto convierte el generador en una lista lo que le quita un poco la eficiencia. No sé si me puedes ayudar con esto?
