### ISSUE TITLE
Duda tiempo entre fallas

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#530]
Hola! 
¿El tiempo que hay entre cada falla para una atracción es fijo (uso ```expovariate(f)``` sólo una vez) o se vuelva a calcular cada vez que ocurra una falla?

**Comment by yoavnavon** [comment]
Hola! Como es una distribución exponencial, será el tiempo que transcurrirá hasta el proximo fallo. Es decir, una vez que falla, se vuelve a calcular. Saludos!
