### ISSUE TITLE
Comida en mal estado para la revision de los carabineros

### ISSUE THREAD

**Issue by MrEarle** [IIC2233/Syllabus#530]
Que se considera como comida en mal estado para el carabinero? Calidad < 0.2?

Edit: Misma pregunta, pero para las estadísticas, cuando consideramos que un producto esta descompuesto?

**Comment by Bneya** [comment]
up!

**Comment by iqacevedo** [comment]
Hola!

Considérenlo de igual forma que como se considera para las estadísticas, se acaba de responder esto en #550 (disculpa por la demora :sweat_smile: ).

Saludos !
