### ISSUE TITLE
AC09 Solución

### ISSUE THREAD

**Issue by camaruri** [IIC2233/syllabus#531]
Hola, queria saber si van a subir la solucion de la actividad 09.
Gracias

**Comment by entamburini** [comment]
Hola @camaruri!,

A tu pregunta, no, como de costumbre, nunca se subirá la solución completa de una actividad. Si te referías al cierre de clase que los profesores hacen, se está pensando, pero hasta ahora no está pronosticado. En caso de que finalmente si se suba, se les notificará a través de un anuncio 👍 

De todas maneras, cualquier duda que podrías tener acerca de cómo realizar la actividad, puedes hacerla a través de este mismo medio y felices te respondemos 😄 

¡Espero que estés bien! :D 
Enzo
