### ISSUE TITLE
tests case 05 correctitud

### ISSUE THREAD

**Issue by Cristobal-Hevia** [IIC2233/Syllabus#531]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

en este test case, el test uno de los test no ocupa ningun archivo dado si no una lista creada en el momento donde la hora esta en el formato HH:MM y no HH:MM:SS como en los archivos, tenemos que tener en cuenta los dos formatos a la hora de trabajar la informacion disponible?

**Comment by wintermelyn** [comment]
Hola @Cristobal-Hevia!

Puedes asumir que el formato con el que se te entregará el parametro hora siempre será `HH:MM`. 

Sin embargo el atributo hora de generador_pedidos tendrá el formato `HH:MM:SS`.
