### ISSUE TITLE
Ayuda con animacion sprite

### ISSUE THREAD

**Issue by Jesusdelgad** [IIC2233/syllabus#531]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Necesito ayuda , no logro hacer la animacion de los personaje con los sprites , lo que intente fue ocultar y mostar los labels de cada sprite cuando se presionaran las teclas pero no logre hacer todas las animaciones y además creo que no es la forma optima de hacerlo , busco en internet pero solo encuentro  tutoriales con pygame , ¿Qué método recomiendan ustedes utilizar para realizar las animaciones?

**Comment by tqmbanados** [comment]
Hola! efectivamente no es una forma muy eficiente de hacerlo 🐱. Lo que deberías implementar es un *timer* que se resetea al llegar al final, y que cambia la imagen actual a la siguiente cada vez que llega al final. Además, queremos lograr que este *timer* funcione **sólo** cuando se esta presionando una tecla de movimiento. 
Para esto existen muchas opciones, un ``while`` que integra funciones ``sleep``(por supuesto dentro de un Thread) es una opción. Pero Qt ofrece una alternativa más "bonita" que es el ``QTimer``. Esta clase envía una señal ``timeout`` cada cierta cantidad de tiempo, repetidamente. Es decir, podemos configurar una señal que se enviará cada segundo. La documentación la puedes encontrar [aquí](https://doc.qt.io/qtforpython-5/PySide2/QtCore/QTimer.html). 
Entonces, es necesario realizar varios pasos:
1. Crear el ``QTimer``, con un intervalo de tiempo relativamente corto.
2. Conectar la señal ``timeout`` al método que cambia el sprite del Label
3. Darle partida al ``QTimer``.
3. Detener el ``QTimer``.

Si te fijas, estos pasos van en el *backend*. En el *frontend* tiene que ir el método que cambia el sprite de la imagen, como también las funciones que detectan el input de teclas que deberían comenzar el movimiento. Es importante que el método que cambia los sprites, siempre lo haga al sprite correspondiente para que se vea un movimiento fluido. Es parte del desafío ver como lograr esto! (*HINT: puedes ocupar atributos de clase, pero la materia reciente de iteradores puede ser muy útil también!*)

Espero haberte sido de ayuda! Cuéntame si te resulta esta explicación o si te queda alguna duda. Éxito!

**Comment by Jesusdelgad** [comment]
Hola! Ahi lo logre hacer muchas gracias!

**Comment by tqmbanados** [comment]
Me Alegro! Suerte en el resto de la tarea! 😸
