### ISSUE TITLE
Paciencia en parameters.py

### ISSUE THREAD

**Issue by antoniacobo** [IIC2233/Syllabus#531]
Uno de los requisitos de la tarea es poner en un archivo `parameters.py` todos los parámetros y que no podían haber valores numéricos. De eso me salen dos dudas: ¿los rangos de edad hay que incluirlos en el archivo? y lo otro es para la paciencia, la fórmula es

> u = (10+energía * 30) min

, ¿esta fórmula hay que agregarla al archivo o será siempre fija?

**Comment by Hernan4444** [comment]
@antoniacobo los rangos de edad si deben ir porque pueden variar. Podemos pensar que un adulto empieza a ser adulto a los 16 y no a los 18 como está en el enunciado. 

La fórmula no hay que ponerla. pero los parametros dentro de ella (10 y 30) si deben ir. 

Al fin de cuentas, esperamos no ver números dentro de su código, que todos sean parametros que al editarlos produzcan un cambio en la simulación.

Saludos ✌️

**Comment by mblejeune** [comment]
Hola @Hernan4444 ! con definir parametros se refieren a como definir:

x = 30
y = 10 

y luego al hacerle import parameters.py puedo usar estas variables en la formula de paciencia ?
Pregunto porque no entiendo bien la idea de lo que se debe hacer en parameters.py :) 

Gracias!

**Comment by Hernan4444** [comment]
@mblejeune es exactamente como dices. hacer x = 30, y = 10 y luego importarlas.

Saludos ✌️
