### ISSUE TITLE
Distribución de puntaje: diagrama

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#531]
Hola!!

En el enunciado se pide el diagrama para el avance. No hay nada más en el enunciado respecto al diagrama de clases.
Sin embrago, en la distribución de puntajes aparece el diagrama de clases.
¿Debemos realizar el diagrama aunque no esté entregado el avance?

Gracias :)

**Comment by vsantelicest** [comment]
Hola **@amahns1**!
El diagrama de clases si debe entregarse junto con el programa final, procurando que explique fielmente la modelación que fue llevada a cabo en tu código.
Éxito!! 🏃

**Comment by amahns1** [comment]
Vale!!

Lo que pasa es que en el enunciado solamente aparece en la parte del avance.

Gracias!!
