### ISSUE TITLE
Problemas de Lag al disparar

### ISSUE THREAD

**Issue by fantinee** [IIC2233/Syllabus#531]
Estaba intentando configurar el movimiento del disparo de las torres, pero cuando se ejecuta el disparo, se lagea el movimiento tanto de la municion como de la unidad objetivo.
Mi bala es un QTimer y mi objetivo es un QThread, queria saber cuales podrian ser posibles causas del lageo.

**Comment by DiegoAndai** [comment]
Hola! Generalmente ese tipo de problemas se da porque hay muchas cosas pasando al mismo tiempo y el computador tiene que procesarlas todas, causando el lag. Trata de revisar tu código y minimizar la cantidad de cálculos e instrucciones que realiza cada thread o timer, a ver si eso funciona. Probablemente tu entidad bala esté realizando muchas operaciones y el computador se ve saturado, dale una vuelta a la implementación y vé qué cosas puedes optimizar para minimizar los cálculos hechos.

Si no te funciona o no era eso vuelve a preguntar por aquí.
Saludos.

**Comment by hanavarrete** [comment]
Como manejas el movimiento? Haces un move directo o haces un manejo como el del ejemplo que subimos en ma carpeta de la tarea? En mi t05 me pasaba lo mismo y lo solucioné realizando lo del ejemplo.

**Comment by fantinee** [comment]
... ambas, mi bala se mueve con un move directo y mi campeon (al que le estoy disparando) se mueve como el del ejemplo

**Comment by hanavarrete** [comment]
Puedes hacer que tu bala se mueva como la del ejemplo? Mi problema era
exactamente igual y así lo solucioné.

2017-05-27 16:31 GMT-04:00 fantinee <notifications@github.com>:

**Comment by fantinee** [comment]
me funciono :D gracias
