### ISSUE TITLE
Presencia del chat en la lista de salas

### ISSUE THREAD

**Issue by Jairuru** [IIC2233/syllabus#531]
Hola, puedo tener el chat en la ventana mientras el jugador recién inició sesión (está en la lista de salas) como un chat global?
En caso de que la respuesta sea no, puede estar de forma inactiva? Por ejemplo, desactivando el boton enviar y el QLineEdit.

Saludos, de antemano gracias.

**Comment by gatochico** [comment]
Hola!

La forma de implementar el chat queda a tu discreción, pero debe cumplir con que: 
1. No debe tener ningún mensaje si el usuario está en la sala de espera. 
2. Cuando se ingresa a una sala, se deben mostrar los mensajes sólo de esa sala.

Si entendí bien como quieres implementar tu chat, debes ponerle particular atención a estas restricciones :eyes: y preocuparte de que si el usuario cambia a otra sala, o sale de una sala a la ventana de elección de salas, se elimine todo rastro de las conversaciones de la sala previa. 

Saludos y cualquier cosa comenta!
