### ISSUE TITLE
Un fail en test 05 carga datos tamano l

### ISSUE THREAD

**Issue by CJoost27** [IIC2233/Syllabus#532]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

1) Todos los archivos se leen correctamente menos el l. ¿Es por un caso borde o por algún dato del archivo?
 
![image](https://github.com/user-attachments/assets/b9893b5a-a66d-4b40-a4bc-93cf6b1b4cb4)

2) Además, como puedo ver el resultado esperado cuando esta en este formato?, esto con la finalidad de ver el valor que no es el esperado.

![image](https://github.com/user-attachments/assets/81d7159c-cd72-4fd6-be8b-2f7785bc2cae)
Muchas gracias.

**Comment by lfcpardo** [comment]
tengo el mismo problema

**Comment by josegdotcom** [comment]
pues si, recuerda que si te encuentras desde la hora dada, te va importar los minutos y que estos sean del minuto dado asta el 59, si la hora esta por encima de la hora dada te debe dar igual y solo preocuparte de que los minutos no sean menores a 0 y mayores a 59.

**Comment by Gcamposbriceno** [comment]
Hola!

1. Te aparece algo más arriba o abajo de esos resultados? Es posible que tengas un timeout, o sea, que tu código se esté demorando más del tiempo límite permitido.
2. Los resultados esperados puedes verlos en `test_publicos/solution/test_{x}.py`
