### ISSUE TITLE
Snacks

### ISSUE THREAD

**Issue by mfanselmo1** [IIC2233/Syllabus#532]
Hola,
Podrian explicar mejor el tema de los snack en la tarea? 
![image](https://user-images.githubusercontent.com/26393563/31630690-bb38af74-b28d-11e7-9dc8-8c923782d66d.png)
Ese tiempo que da el expovariate desde donde es? Solo una vez al dia? o sino cual es la probabilidad de ir a comprar un snack?
![image](https://user-images.githubusercontent.com/26393563/31630756-fd93fd7e-b28d-11e7-8f32-ac2be424f676.png)
Que nos dice esa probabilidad?
Gracias!

**Comment by cilopez** [comment]
Voy aclarar esto dentro de poco, la verdad es que hay una incongruencia en el enunciado, voy a simplificar esa parte, disculpas.

**Comment by cilopez** [comment]
#543 Avisenme si no queda claro
