### ISSUE TITLE
Error al hacer json.loads

### ISSUE THREAD

**Issue by jfpena1** [IIC2233/syllabus#532]
Hola, me pasa que algunas veces, cuando un cliente se sale o entra al juego, y se envia el mensaje mediante el servidor a los demas clientes, cuando cada cliente recibe el mensaje y lo deserializa viene con un caracter demas. En mi caso siempre es en el caracter 45, en el que se cola una letra j o alguna otra justo antes de un diccionario. Es muy raro, y solo ocurre de repente.

Un ejemplo de mensaje que llega mal es (el caracter demas en Bold):
{"status": "jugador_agregado", "num_sala": 1}   **j**{"status": "mensaje", "data": {"usuario": "servidor", "contenido": "El jugador julio2 se unio a la sala"}}

El error que tira es el siguiente.
![image](https://user-images.githubusercontent.com/39381457/59553793-5eb80600-8f68-11e9-88e3-7b5d004f242c.png)

La verdad nose como solucionarlo, alguien tiene alguna idea de porque puede pasar esto?
Subi actualizado mi codigo a github por si acaso.Muchisimas gracias

**Comment by jfpena1** [comment]
pienso que se estan superponiendo mensajes que se reciben al mismo tiempo, porque a veces para una misma accion mando dos mensajes distintos para llevar a cabo distintas cosas en el lado del cliente.

**Comment by crvargasu** [comment]
Hola, creo que yo tenia el mismo error, entre medio de los mensajes que envias agregale un time.sleep(0.001), cosa de que no se manden los mensajes al mismo tiempo

**Comment by jeschuwirth** [comment]
Hola!

El problema se te solucionó para dejar la issue como resuelta?

**Comment by jfpena1** [comment]
si gracias!

**Comment by jfpena1** [comment]
si gracias!

**Comment by YoGandalf** [comment]
Hola donde pusieron el sleep?
Porque a mi con 1 segundo igual me pasa con algunos mensajes

**Comment by VicenteMerino** [comment]
> Hola, creo que yo tenia el mismo error, entre medio de los mensajes que envias agregale un time.sleep(0.001), cosa de que no se manden los mensajes al mismo tiempo

Hola, cuanto es lo recomendable para poner en el sleep, con el 0.001 no me funcionaba, pero con un segundo si. O es mejor indicar en el readme que el ayudante juegue con esto?
