### ISSUE TITLE
duda ejemplo doggo networking

### ISSUE THREAD

**Issue by mgbriones** [IIC2233/syllabus#532]
Tengo unas cuantas dudas con respecto al ejemplo doggo si me pudieran aclarar:

1) No me queda claro que protocolo de comunicación se esta utilizando (TCP o UDP) ya que en `servidor.py` , en el init socket() no tiene entradas...

2) ademas en que parte se acepta la conexión por parte del servidor??

3) self.cliente de vendría siendo un segundo socket?

En la solución del ejercicio propuesto:
4) los comando `from_bytes( )` y `to_bytes` ( de los métodos Función `Servidor.receive()` y Función `Server.send()` respectivamente ) son métodos exclusivos de alguna clase? No me queda claro. 

5) Cuando se utiliza el comando `mensaje = bytearray()`, `mensaje` no debería estar vació? en que momento se pasa información a mensaje??? (se utiliza al completar el metodo `receive(self)`)

**Comment by StroveLight** [comment]
Hola!

Con respecto a la primera pregunta, socket posee argumentos por default que justo son los que se usan para la mayoría de los ejercicios de los contenidos (es decir, AF_INET y SOCK_STREAM)
([Imagen tomada de la documentacion](https://docs.python.org/3/library/stdtypes.html#additional-methods-on-integer-types))
![image](https://user-images.githubusercontent.com/48263952/69384467-25b05a00-0c9b-11ea-8d80-44a0db7a275f.png)


2.- En el run() del servidor se usa la funcion self.socket.accept() para aceptar la conexion
![image](https://user-images.githubusercontent.com/48263952/69386829-7c6d6200-0ca2-11ea-8546-a76c47797082.png)

3.- Si, como se puede ver en la [documentacion](https://docs.python.org/3/library/socket.html#socket.socket.accept)
![image](https://user-images.githubusercontent.com/48263952/69386997-1f25e080-0ca3-11ea-8a46-cbbeed95e91d.png)

4.- Sí, son de la clase int, de allí siempre se llama de la forma int.from_bytes e int.to_bytes, [mas informacion en la documentación](https://docs.python.org/3/library/stdtypes.html#additional-methods-on-integer-types)

5a.- Un bytearray lo puedes ver como una lista, pero que guarda solo bytes. Al declarar ```mensaje = bytearray()```, se declara la estructura vacía, al igual que usar ```mensaje = list()````, pero con una estructura que guardará los datos como bytes

5b.- El bytearray al igual que las listas se le puede agregar mas contenido al original usando ```contenido_original += nuevo_contenido``` además de ```contenido_original.extend(nuevo_contenido)```. En el programa se usó .extend()
![image](https://user-images.githubusercontent.com/48263952/69387648-3cf44500-0ca5-11ea-94f4-3bb51f53d2c8.png)

Espero que esto te haya ayudado. Si algo no te quedó claro, solo pregunta de nuevo

**Comment by mgbriones** [comment]
Muchas gracias!!! me fue super útil!

**Comment by StroveLight** [comment]
De nada! ('◇')ゞ
