### ISSUE TITLE
ComboBox desactiva KeyPressEvent

### ISSUE THREAD

**Issue by lpalacios1** [IIC2233/syllabus#532]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! En la ventana de preparación utilice un ComboBox para elegir la dificultad del nivel. Sin embargo, cuando accedo a esta ComboBox cuando esta corriendo el programa, KeyPressEvent deja de funcionar y creo que los movimientos se me registran solo dentro de la ComboBox. Mi duda es si esto es un problema que se puede arreglar o es algo de PYQT que no se puede cambiar. Cuando vuelvo a seleccionar un personaje, este problema se arregla, pero lo ideal seria que se pueda seleccionar la dificultad con el personaje ya escogido. 

Gracias!

**Comment by catalina-arcila** [comment]
Hola @lpalacios1 que raro que haya ese tipo de error, puedes subir tu código a tu repo para revisarlo?
Quedo atenta!

**Comment by imuoz** [comment]
Si no me equivoco eso se puede arreglar con self.setFocus(True) cada vez que se interactúa con el ComboBox, así no cambia el focus de la ventana, quizás hay otra forma de arreglarlo pero eso me dijeron en la issue #497

**Comment by lpalacios1** [comment]
> Hola @lpalacios1 que raro que haya ese tipo de error, puedes subir tu código a tu repo para revisarlo?
> Quedo atenta!

lo acabo de subir!

**Comment by lpalacios1** [comment]
> Si no me equivoco eso se puede arreglar con self.setFocus(True) cada vez que se interactúa con el ComboBox, así no cambia el focus de la ventana, quizás hay otra forma de arreglarlo pero eso me dijeron en la issue #497

Trate con eso y no me funciono :(

**Comment by lpalacios1** [comment]
> > Si no me equivoco eso se puede arreglar con self.setFocus(True) cada vez que se interactúa con el ComboBox, así no cambia el focus de la ventana, quizás hay otra forma de arreglarlo pero eso me dijeron en la issue #497
> 
> @lpalacios1 era con eso!!!, lo agregué arriba del `print("se cambia")` y funcionó

Buenisimo!! Lo habia puesto en otra parte!! 
Muchisimas gracias!
