### ISSUE TITLE
Disponibilidad restaurantes

### ISSUE THREAD

**Issue by akrebs2** [IIC2233/Syllabus#532]
Hola, bien cortito.

Qué significa que, al tomar la decisión de qué hacer, se elija dentro de los restaurantes "disponibles". Los que no están llenos?

Gracias!

**Comment by ptflores1** [comment]
Hola !
Lo que dice @ljrodriguez1  esta correcto, recuerden que tienen que tomar en cuenta el tamaño del grupo.
Saludos!
