### ISSUE TITLE
Duda general de la estructura del programa

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#532]
Hola!

En algunos métodos de las subclases (tomaré como ejemplo el método fichar) DCCrotona e IEEesparta, llamo a una función que imprime el menú con los deportistas disponibles para fichar. Esta función se encarga de agregar la instancia del deportista al equipo además de realizar las otras acciones especificadas en el enunciado. 
El rival, como indica el enunciado, solamente debe mandar a competir a los deportistas (si lo determinamos de esa forma).
Estoy a tiempo de cambiar un poco la estructura.
Mi duda: ¿es válido si el método fichar solamente funciona para el jugador y no el rival? ¿Es válido si las acciones que realizan ambas delegaciones, como mandar a competir, sí estén implementadas para que el método funciones para el jugador y el rival?

Muchas gracias!

**Comment by vsantelicest** [comment]
Hola **@amahns1**
Efectivamente, si determinas que el rival no efectúa otras acciones que no sea participar de las competencias, estaría bien que el método que mencionas no se le aplicara. Procura explicar esto en tu Readme, para no entrar en confusiones y que quede claro que ese tipo de acciones no son llevadas a cabo por el oponente.
Suerte!
🏊
