### ISSUE TITLE
Arrepentimientos camino a crear Magizoologo

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#532]
Hola, al momento de crear un Magizoólogo, se asume que el usuario no se va a arrepentir en el camino de crearlo, por lo que no sería necesario dar a cada momento una opción de volver atrás y salir?

**Comment by mpsubiabre** [comment]
Hola @dlmed!

Exactamente, al no salir explicito en el enunciado se puede asumir, a la vez que es totalmente valido asumir lo contrario, queda a tu criterio :)
Recuerda escribir todos los supuestos que sean pertinentes en la sección de supuestos en el README 😉
