### ISSUE TITLE
Hacer Cola Atracciones

### ISSUE THREAD

**Issue by clementeross** [IIC2233/Syllabus#533]
Hola! Tengo 2 dudas:
1. Para hacer la cola de una atracción, ¿se debe verificar con anterioridad que el adulto tiene presupuesto suficiente para pagar las entradas?

2. Por otro lado, si el adulto tuviese la plata necesaria, que pasa si uno (o más de uno) de los niños no cumple con la altura mínima? el niño no se sube a la atracción y el resto sí? O también es una condición que se debe verificar antes de hacer la cola de que todos los niños cumplan con la altura mínima para subirse a la atracción?

Gracias!

**Comment by ptflores1** [comment]
Hola !
Ambos casos quedan a tu criterio.
Saludos!

**Comment by sjkinast** [comment]
Hola para entrar a la cola hay que verificar si esta llena la atracción? o si esta llena se queda esperando a la proxima.
