### ISSUE TITLE
Librerías permitidas, no permitidas y malas prácticas

### ISSUE THREAD

**Issue by lily416** [IIC2233/syllabus#533]
Para consultar sobre una librería deben responder esta _issue_ con una pregunta de la siguiente forma:
 
> **Puedo usar la librería nombre_librería para hacer explicación_de_lo_que_quiero_hacer**
 
¡Recuerden especificar en su README qué librerías utilizan!
 
---
 
## ✔ **Librerías Permitidas** 
- socket
- PyQt5
- QtDesigner
- threading
- time
- random
- collections
- itertools
- functools
- operator
- dataclasses
- string
- copy
- json
- pickle
- re
- os
- sys.exit
 
## ❌ **Librerías Prohibidas**
- pygame
- OpenCV
- Arcade
- Pyglet
- Tkinter
- matplotlib
- keyboard
- shutil
- pathlib
- glob
- pandas
- numpy
- ast
- curses
- io
 
## ☠️ **_Built-ins_ Prohibidos** 
El uso de alguna de las siguiente funciones es automáticamente un 1,0 sin discusión: 😭
- exec
- eval
 
 
## Malas prácticas
El uso de las siguientes será considerado una mala práctica:
- Variables globales a excepción de los elementos considerados en `parametros.json`. 
- `except Exception:` o únicamente `except:`
 
Si tienes dudas sobre estas malas prácticas, puedes revisar esta _issue_ #340.
 
¡Ánimo y éxito en sus tareas! 👋💻

**Comment by JuanDlugo** [comment]
Hola! 
Puedo usar la librería select para diferenciar los mensajes a mandar con respecto a los recibidos y a los errores?

**Comment by lily416** [comment]
Hola @JuanDlugo, no puedes utilizar `select` ya que uno de los objetivos de la tarea es que manejes de forma manual los mensajes entrantes, salientes y los errores.

Saludos y éxito en la tarea :wave:🐧

**Comment by emilianomm** [comment]
Hola

Esta permitida la librería _loggin_  ?? Pensaba hacer un .log de forma manual pero pensé que podría complicar demasiado el código para su recorección.

Saludos

**Comment by lily416** [comment]
Hola @emilianomm, no pueden usar la librería `loggin` ya que uno de los objetivos de este ítem es que mediante el formateo de _strings_ logren implementar los `prints` de los _logs_.

Saludos y éxito en la tarea 👋🗃

**Comment by sebaav12** [comment]
Hola, esta permitido el uso de asyncore?

**Comment by sebaav12** [comment]
Hola, se puede utilizar asyncore para manejar la conexión "clientes"-servidor?

**Comment by lily416** [comment]
Hola @sebaav12, la librería `asyncore` no se encuentra disponible en la versión de python que se utiliza en el curso (3.7). Igualmente, no es necesario que utilicen funciones asíncronas para manejar la conexión cliente-servidor, con la materia vista hasta el momento les debería ser posible realizarlo.

Saludos y lamento la demora 👋🙇‍♀

**Comment by mgbriones** [comment]
se puede usar la librería `Queue`?

**Comment by lily416** [comment]
@mgbriones puedes usar la librería `Queue` o su equivalente `collections.deque`, recuerda que al momento de preguntar debes indicar para qué quieres usar la librería.

Saludos y éxito con la tarea 👋 🚶 🚶‍♀ 🚶
