### ISSUE TITLE
Sensibilidad mayúsculas/minúsculas

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#533]
Hola, como en el enunciado dice que no hay distinción entre minúsculas o mayúsculas, al momento de ingresar con el nombre de magizoologo, este se puede hacer en su versión minúscula/mayúscula, o debe ingresarse tal cual? lo digo porque si es así sería más complicado ingresar sesión. Personalmente ocuparía esto sólo para verificar si existe ya o no el nombre.

**Comment by JosefaPaz** [comment]
¡ Hola @dlmed !

Al no haber distinción entre minúsculas o mayúsculas, el Magizoólogo puede entrar escribiendo con la combinación de minúsculas/mayúsculas que desee su usuario, por lo que este puede ser igual o diferente en combinación de minúsculas/mayúsculas a como se encuentra en el archivo csv.

Un ejemplo sería lily416potter, Lily416Potter, lilY416poTTer, donde todos son el mismo usuario 😸 

¡Éxito en la tarea!

**Comment by dlmed** [comment]
Gracias! se me ocurrió una forma no tan complicada :)
