### ISSUE TITLE
Es necesario el uso de Metaclases?

### ISSUE THREAD

**Issue by depstein26** [IIC2233/Syllabus#533]
Creo que el nombre de la issue es bastante autodescriptiva, pero dado que se pide heredar en la tarea 4, puedo heredar simplemente como en la tarea 1 o se deben hacer meta clases y usar esa materia del curso?

**Comment by egromero** [comment]
Hola,

No está dentro de los objetivos de esta tarea la evaluación de metaclases.

Saludos
