### ISSUE TITLE
Movimiento de traslacion y cambio de imagenes

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#533]
Es sabido que para generar la ilusion de movimiento se itera sobre una secuencia de imagenes.
Tengo definido un label a quien le voy variando su pixmap (setPixmap) para cumplir lo anterior.
Ahora bien cuando le aplico el comando` move(x,y)` funciona todo bien (desplaza la imagen) pero al iterar a siguiente imagen, el label retrocede hasta la posicion original. Es como si cambiar el pixmap anulará la nueva posicion post move (lo comprobe usando `qWait` y efectivamente setPixmap resetea la posicion).
Algun workaround?

**Comment by hanavarrete** [comment]
No estoy seguro si estoy entendiendo bien tu problema, pero probaste
moviendo el label también? si solo mueves el pixmap, el "nuevo" se pondrá
encima del label, por lo que debes mover el qlabel.

**Comment by hanavarrete** [comment]
Debes estar haciendo algo mal, dado que acabo de probar actualizar el pixmap y esto no me devuelve a la posición inicial. Revisa si tu función de movimiento está bien y mira el ejemplo que subimos a la carpeta de t05.

**Comment by benjamimo1** [comment]
Estoy moviendo el label
`self.foto.move(self.foto.pos().x()+v,self.foto.pos().y())` donde self.foto es label

**Comment by iqacevedo** [comment]
Hola!
Como dice @hanavarrete revisa si estas usando señales para mover a tu QLabel, tal vez por ahi va el problema !
Saludos

**Comment by benjamimo1** [comment]
El ejemplo esta bueno? Esto es todo lo que veo http://imgur.com/a/WlSVK

**Comment by iqacevedo** [comment]
Si esta bueno, deberías ver la siguiente imagen moverse desde el inicio de la ventana hacia abajo una y otra vez. Los números son las posiciones que tiene.

![captura de pantalla de 2017-05-27 17-34-08](https://cloud.githubusercontent.com/assets/13748732/26524511/ac762afc-4302-11e7-980d-bbf4769d5ff3.png)

**Comment by hanavarrete** [comment]
Asumiendo que tienes en la misma carpeta la imagen "green_boss.png"
