### ISSUE TITLE
Duda sobre tiempo de ejecucion testcases

### ISSUE THREAD

**Issue by ByDati** [IIC2233/Syllabus#533]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Respecto al tiempo de ejecución de cuando se nos evalue la tarea, ¿las bases de datos que usarán serán de tamaños similares a las que se entregan con los testcases? Para hacerme mas o menos la idea si mi codigo es lo suficientemente eficiente o debo optimizarlo de alguna manera para que no sobrepase los 30 segundos. Por ejemplo, hay algun rango de tiempo que es recomendable tener en la mayoria de los casos?

Gracias de antemano

**Comment by DiegoGHR** [comment]
Hola, recuerda que si no se cumple con el tiempo limite, no habra puntaje. Por esto, debes asegurarte que corran en menos de los 30 segundos. Las bases de datos seran bastante similares, pero podrian ser levemente mas extensas (un 1%). Saludos

**Comment by ByDati** [comment]
Yaaa, muchas gracias!

**Comment by Benjamin-Valdesa** [comment]
Cuando se dice "no se cumple en el tiempo límite" tipo se demoró más de 30 segundo, se refiere al correr todos los test case?
