### ISSUE TITLE
Mostrar moral de cada delegación

### ISSUE THREAD

**Issue by CarolinaYanez** [IIC2233/syllabus#533]
Hola! Se pide que la moral de cada delegación se muestre al inicio del día de entrenamiento y día de competencia pero, estaría mal si se imprime además de esas, otras veces?
Gracias!

**Comment by jitorcas** [comment]
Hola! @CarolinaYanez 

¿En qué otras situaciones estás imprimiendo la moral?

**Comment by CarolinaYanez** [comment]
Cada vez que se dirige al menú principal del jugador

**Comment by jitorcas** [comment]
@CarolinaYanez 

No le veo el problema, siempre y cuando sea algo intensional.

**Comment by CarolinaYanez** [comment]
Okey gracias!
