### ISSUE TITLE
Visual studio

### ISSUE THREAD

**Issue by nsancha** [IIC2233/syllabus#533]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema
En visual studio quiero activar los lintern para ver todo con los colores, segui el video explicativo pero aun asi no me funciona el lintern
[Describe tu problema de manera detallada, explicando qué estás intentando hacer y explicando los errores o problemas que has encontrado. Se recomienda agregar fotos cuando sea posible]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Juampisaez** [comment]
Hola @nsancha 
No sé si ya lo pudiste solucionar, yo por lo menos al momento de activar el linter use este [link](https://code.visualstudio.com/docs/python/linting). Tal vez te pueda servir mas en vscode.

Quedo atento igual :)

**Comment by nsancha** [comment]
No me funciono tampoco, no se por que
