### ISSUE TITLE
Entregable T04

### ISSUE THREAD

**Issue by papasconketchup** [IIC2233/Syllabus#534]
Hola,

¿Como se debe entregar la lista de eventos? No entiendo el formato o la manera en que se tienen que plantear los eventos en la lista.

Gracias

**Comment by mfanselmo1** [comment]
Hola,

Basta con una lista de eventos en el form, por ejemplo:
1. Alumno llega a la universidad
2. Alumno decide ir a clases
3. Alumno decide ir a almorzar
...

Pero en tu caso debes entregar esta lista con todo lo que sale en el enunciado (Quienes participan, que eventos suceden, etc)

**Comment by mblejeune** [comment]
@mfanselmo1 en el enunciado piden esto "debes entregar esta lista con todo lo que sale en el enunciado (Quienes participan, que eventos suceden, etc)" solo para el evento dia colegio, no para la lista de eventos. Cuando se cambió esta condición del entregable ? :(

**Comment by mfanselmo1** [comment]
Hola! Me equivoque yo al explicar. Deben entregar una lista de eventos y explicar como piensan hacer el evento dia de colegio, tal como sale en el enunciado.

**Comment by pcseisdedos** [comment]
Debemos nombrar todos los eventos de la simulación... y además explicar la forma en que pensamos modelar el evento del colegio, y solo para ese evento decir las entidades y eventos involucrados?

**Comment by Hernan4444** [comment]
Hola, son dos cosas separadas
1) Entregar una lista de **todos los eventos**
2) Como modelar el evento del colegio.

**Comment by mfanselmo1** [comment]
Vean el form y se van a dar cuenta de que se pide

**Comment by Hernan4444** [comment]
Se describe de todas maneras el día de colegio.

**Comment by Pipelao** [comment]
Ok, gracias.
