### ISSUE TITLE
Llegada al campus

### ISSUE THREAD

**Issue by valeria-adasme** [IIC2233/Syllabus#534]
¿Qué ocurre con el tiempo de traslado cuando el MiembroUC decide comprar un Snack al llegar al campus? ¿Lo considero igual o considero que la compra es sólo el tiempo que se demore en comprar?

**Comment by iqacevedo** [comment]
Consideralo como algo inmediato no mas, ya que cuando llegan pasan por donde están los puestos y no hay tiempo de traslado ahí.

Saludos
