### ISSUE TITLE
Niffler cambia de arisca a inofensiva

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#534]
Hola! 
No se si respondieron esto, busca issues y no encontre respuesta
Tengo una duda, si el niffler come una tarta, existe la posibilidad de que cambie a su agresividad a inofensiva, si esto ocurre considero que el efecto_agresividad cambia a 0? o lo dejo tal cual?

**Comment by matiasmasjuan** [comment]
Hola @Juampisaez !

Dado que en la acción de ***Alimentarse*** se define el **valor** del *efecto_agresividad* conforme a la condición de la **DCCriatura** (*efecto_agresividad* = **0** si la **DCCriatura** es *"inofensiva"*, **20** si es *"arisca"* y **40** si es *"peligrosa"*), la idea es que el **Niffler** cambie su *nivel de agresividad* tras comer la ***Tarta de Melaza***, y por ende, el valor de ***efecto_agresividad*** (según la probabilidad que esto ocurra) **también** deberá **cambiar**.

Saludos y mucho éxito con la tarea! 😄
