### ISSUE TITLE
foto de perfil

### ISSUE THREAD

**Issue by mjespinoza** [IIC2233/syllabus#534]
Holaa, tengo una duda con respecto a esta parte del enunciado
"En caso de que no implementes la foto de perﬁl, puedes crear la funci´on guardar png(path original, path destino), donde el argumento path original es la ruta de la imagen original, y el argumento path destino es la ruta donde la funci´on debe guardar una nueva imagen en formato PNG" ¿Cual es la diferencia con lo que tenemos que hacer?

**Comment by KnowYourselves** [comment]
Hola @mjespinoza!

Para poder ver que es correcto el manejo de PNG (y también el filtro) es necesario que implementes foto de perfil (y boton de filtro), en caso contrario no tenemos forma de ver que tu programa está funcionando. 

Sin embargo, en caso de que no implementes foto de perfil dentro de la interfaz, puedes simplemente hacer la función que describe el enunciado para evaluar el manejo de PNG de todas formas. Si este es el caso recuerda poner en tu README donde está la función!

Espero haberte ayudado!

**Comment by mjespinoza** [comment]
muchass gracias @KnowYourselves , tengo otra duda, el servidor si o si debe guardar la imagen en su carpeta? haciendo esto seria correcto guardar solo el path del archivo en la base de datos?

**Comment by KnowYourselves** [comment]
De nada!

El servidor debe guardar **la imagen** no el path. Si yo ejecuto el cliente desde otro computador y me conecto con un usuario que tiene una foto de perfil definida, el cliente debe descaegarla del servidor y mostrarla adecuadamente.

Éxito!

**Comment by mjespinoza** [comment]
si, pero me referia a la base de datos, segun lo que me dices en la base de datos hay que guardar el contenido (bytes) de la imagen o no? es que yo tenia la idea de tener la imagen guardada en el servidor pero para saber que imagen le pertenece a cada jugador guardar el path o nombre de la imagen ya guardada en la base de datos. No se si se entiende, estoy confundida con esta parte, dado que no se que es lo mas correcto.

**Comment by KnowYourselves** [comment]
Ah, lo siento, no entendí tu pregunta!

Si, puedes guardar la imagen como path en la base de datos del servidor mientras funcione como te dije. (También se puede guardar en un JSON con algo conocido como Base64 encoding, pero ese es otro tema)

Saludos!
