### ISSUE TITLE
Duda hardcoding

### ISSUE THREAD

**Issue by sofiaolmedos** [IIC2233/syllabus#534]
Hola! Me quedó una duda con que se considera o no hardcoding. Porque entiendo que es cuando se ponen valores directamente en el código porque con los parametros después se pueden alterar esos valores.
Pero mi duda es si TODOS los valores deben ir así, por ejemplo cuando se hace todo lo de calcular la probabilidad para sanar a un deportista, entiendo que en la fórmula pueden cambiar, pero yo igual usé otros números para calcular la probabilidad real y aproximar (por ej aproximar si es >= 5, no se si ese 5 sería hardcoding).
Gracias!! 😃

**Comment by mmunozmendez** [comment]
Hola!
No todos los valores que use tu programa se deben usar como parámetros, queda a tu criterio decidir cuales si se usarán de esta manera. Los valores que se usan como parámetros son valores que se pueden cambiar fácilmente y se cambian en todo el programa, por lo que es bueno tener aquellos que podrían cambiar o aquellos que se usan en muchas partes del código (modificarlos uno por uno podría generar un error).
El hardcoding es cuándo incrustas valores directamente en el código en lugar de sacarlos de su fuente, entonces, si tu defines que un valor debe ser un parámetro, cada vez que lo uses debe ser mediante el valor en el archivo parametros.py (que sería su fuente porque lo definiste así). 

Espero que te quede más claro
Éxito 🦝

**Comment by SebastianFerra** [comment]
Hola yo sigo teniendo preguntas, en el enunciado por ejemplo nos dicen "estos valores varían entre tanto y tanto" entonces yo no hice parámetros para eos y simplemente dije "ah bueno eso no debería cambiar" y lo puse directo en el código, cuenta como hardcoding?  porque si no es hardcoding, mi parametros.py queda solo con los parametros que se entregan en el enunciado

**Comment by mmunozmendez** [comment]
Hola, los que deben estar si o si en parametros.py son aquellos señalados en el enunciado. Para los otros valores que se usan queda a tu criterio, así que si consideras que está bien, es correcto, eso no es hardcoding.
Éxito 🦝 !
