### ISSUE TITLE
Duda Cálculo de nota final 

### ISSUE THREAD

**Issue by burgosibarra** [IIC2233/syllabus#534]
Cómo se incluyen las décimas en la nota final del curso?
Por lo que recuerdo del principio de semestre las décimas se suman a la mejor nota, pero con el cambio no me queda claro, ya que no se si la nota auxiliar (la que es el máximo entre el promedio y la recuperativa) considerará como promedio las notas con las décimas, o estas solo se consideran en el cálculo de la nota final.
Desde ya, muchas gracias

**Comment by entamburini** [comment]
Hola @burgosibarra!,

Tienes razón, no está del todo aclarado y es algo de lo que nos haremos cargo prontamente. Para responderte pronto, te puedo decir que las décimas obtenidas en las actividades formativas se aplicarán una vez ya calculada la nota auxiliar. 

Que estés bien! :v:
