### ISSUE TITLE
Tiempo delay Enemigo 

### ISSUE THREAD

**Issue by matildeotte** [IIC2233/syllabus#534]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Tengo una duda, para el delay del enemigo debe partir TIEMPO_DELAY_{DIFICULTAD} segundos después y demorarse lo mismo que el personaje (avanzar a la misma velocidad)? O por cada movimiento que haga el personaje el enemigo debe hacer el mismo movimiento TIEMPO_DELAY_{DIFICULTAD} segundos después?

Ahora lo tengo hecho de la segunda manera, pero avanza muy lento el enemigo (se ve muy cortado el movimiento). Además, al partir debo mantener las teclas de movimiento apretadas para que el enemigo no me alcance altiro.

En caso de que se tenga que hacer de la primera forma le puedo agregar un sleep además del TIEMPO_DELAY_{DIFICULTAD} ? Ya que si lo hago con un while o con un for el enemigo se teletransporta a la última posición del personaje.

Gracias!

**Comment by JadrinaDA** [comment]
Hola! Es la primera opción, el enemigo espera el tiempo del delay y luego empieza a moverse con la misma velocidad que el jugador. Y sí puedes agregar otro sleep, lo que necesites para que funcione bien. Cualquier otra duda avisame. c:

**Comment by matildeotte** [comment]
Yaa gracias!

**Comment by tamyhan** [comment]
Hola! Tengo una duda relacionada con esto. El enemigo tiene que aparecer al principio y luego del tiempo de delay empezar a moverse, o el enemigo aparece después de tiempo delay y empieza a moverse en ese momento?
En ambos casos, el enemigo aparece en una posición aleatoria o aparece en la misma posición en la que partió el personaje?

**Comment by JadrinaDA** [comment]
Hola! El enemigo debe aparecer TIEMP_DELAY_{DIFICULTAD} segundos después del personaje y empezar a moverse al tiro. Tal como dice en el enunciado en enemigo debe aparecer en el mismo lugar que es personaje y replicar su misma trayectoria. Avísame si tienes más dudas, éxito!

**Comment by tamyhan** [comment]
okaa gracias!!

**Comment by pascal1003** [comment]
Una duda con el movimiento el enemigo, si es que mi personaje se detiene y luego comienza a avanzar de nuevo, el enemigo tiene que detenerse la misma cantidad de tiempo antes de volver  avanzar o sigue como si nuestro personaje nunca hubiera parado? lo mismo cuando nuestro personaje se queda bloqueado con un objeto,

**Comment by JadrinaDA** [comment]
Hola! El enemigo debe seguir moviéndose en ambos casos, si no fuera así entonces este nunca podría alcanzar a nuestro personaje. Avísame si tienes más dudas, éxito!

**Comment by VichoAburto** [comment]
Hola! 

Una consulta, todavía no me queda muy claro. Hasta ahora lo que tengo y entendí del enunciado, es que el enemigo aparece TIEMPO_DELAY_{DIFICULTAD} segundos después que el personaje comienza a moverse, y además se demora TIEMPO_DELAY_{DIFICULTAD} segundos en moverse a la siguiente posición, pero como decian arriba, se ve un movimiento muy cortado. Está bien?

Porque lo otro que acabo de probar, es que al igual que dije antes, el enemigo aparece TIEMPO_DELAY_{DIFICULTAD} segundos después que el personaje comienza a moverse, sin embargo, al comenzar a moverse, le puse un intervalo de 350 ms entre cada movimiento a una nueva posición. Haciendo esto se ve mucho más fluido el movimiento del enemigo. Se puede hacer esto último o es lo primero?

**Comment by JadrinaDA** [comment]
Hola! Sobre lo primero no debes esperar el tiempo del delay para mover el enemigo a la siguiente posición, este tiene la misma velocidad que el personaje. El delay solo se usa al principio. Con eso se debería ver más fluido. Por lo que veo en la distribución no debería haber problemas por usar tu método. Saludos.
