### ISSUE TITLE
Dia de colegio 

### ISSUE THREAD

**Issue by AntoniaChristensen** [IIC2233/Syllabus#535]
Hay algo que no entiendo acerca del día de colegio. Dice que los niños andan solos, pero se sigue manteniendo la estructura del grupo? Es decir, siguen haciendo todo juntos? O como cada niño ahora tiene un presupuesto individual toma las decisiones solo? En ese caso que pasa si decide ir a un restaurante pero el adulto ya esta en otro restaurante con otro niño?? Además si a uno de los niños del grupo se le acaba la energía, sigue aplicando que todo el grupo se va?

**Comment by rihanuch** [comment]
¡Hola @AntoniaChristensen !

Tal como se dijo en la issue #515 🔙, queda a tu criterio, solo asegúrate de explicitarlo

¡Saludos! 🍀
