### ISSUE TITLE
Parametros

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#535]
Hola!

¿En las fórmulas es necesario agregar parámetros?

[foto]

Por ejemplo esos ponderadores que multiplican cada atributo.

Gracias!!

**Comment by mmunozmendez** [comment]
Hola!

Eliminé tu foto porque no debes compartir tu código por este medio. 
Te invito a ver la issue #534 , que responde a tu pregunta también.

Éxito 🦝
