### ISSUE TITLE
Duda sobre puntaje en cada ronda

### ISSUE THREAD

**Issue by gonzaga2000** [IIC2233/syllabus#535]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo una duda sobre cómo calcular el puntaje. Por enunciado sale que el puntaje de cada ronda se calcula como (puntos_buenos + puntos _X2)*vida. Eso me hace sentido al calcular el puntaje Alfinal de la ronda, pero como calculo el puntaje durante la ronda?

 Siento que el puntaje de la ronda debería aumentar cada vez que se agarre un nuevo objeto, pero no entiendo cómo sería posible ir actualizando el puntaje si este depende de la vida del personaje.

**Comment by mmunoz12** [comment]
Hola @gonzaga2000! El puntaje durante la ronda se actualiza con esta misma función _puntaje_ronda_ y como se menciona en la sección de ventana de juego, las **estadísticas se deben mantener actualizadas a medida que avanza el juego**. Entonces, cada vez que varía la vida del personaje o aumentan las cantidades de objetos atrapados (normales y x2) durante el juego, el puntaje mostrado en pantalla debe cambiar también según esta fórmula. Avísame si te quedan dudas!

**Comment by mjsifri** [comment]
Hola! A mi me queda una duda, si por ejemplo tengo tres objetos normales y calculo el puntaje, y luego tengo cinco objetos normales y calculo el puntaje, debería sumar ambos puntajes? o primero calculo el puntaje con los tres objetos y luego al tener cinco debo calcular el puntaje con dos objetos (ya que tengo cinco pero ya calcule con los primeros tres) y luego sumarlos? No se si se entendió jajaj

**Comment by mmunoz12** [comment]
Hola @mjsifri!! Es tal como lo dices al principio, tomando en cuenta que en una ronda tomas 3 objetos y en la siguiente 5, el puntaje acumulado (mostrado en la ventana post-ronda después de la 2da ronda) será la suma de ambos. 

El **puntaje acumulado** es el que se muestra en la ventana post-ronda y corresponde a las sumas de los puntajes correspondientes a todas las rondas realizadas hasta el momento (en la misma partida). Mientras que el **puntaje mostrado en la ventana de juego** corresponde al puntaje en sólo esta ronda, por lo tanto, se deberán tener en cuenta los ítems buenos y malos atrapados **sólo** en esta ronda actual. Por lo tanto, como al principio de cada ronda se tienen 0 ítems atrapados, el puntaje mostrado en la ventana de juego será 0. 

Y para la otra pregunta que tenías que aprovecho de contestar, en la ventana de preparación no se pide explícitamente por enunciado mostrar el puntaje, por lo tanto queda a tu criterio cual puntaje mostrar (tiene más sentido mostrar el acumulado ya que no se está jugando una ronda todavía). Por otro lado, es el puntaje acumulado el que se debe ingresar al ranking de mejores puntajes.

Espero que esto haya aclarado tus dudas, sino pregunta nomas!☺️

**Comment by Nicolasramos411** [comment]
Hola! En este sentido, ¿si uno pierde durante la ronda (muere o es atrapado) entonces su puntaje en dicha ronda debiese ser igual a 0?,

Gracias.

**Comment by mmunoz12** [comment]
Si! ya que por la fórmula _puntaje_ronda_ (ojo que no es el puntaje acumulado) la vida sería 0 entonces este tendría como resultado 0 para esa ronda. Saludos!
