### ISSUE TITLE
test_04_ajustar_precio_segun_ingredientes_carga_datos

### ISSUE THREAD

**Issue by lfcpardo** [IIC2233/Syllabus#535]
* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Hola, este test me falla para datos de la carpeta de tamaño l. No sé por qué podría fallar para una carpeta específica. 
<img width="1440" alt="Screenshot 2024-10-14 at 12 23 18" src="https://github.com/user-attachments/assets/2940f099-0410-40e9-b6bd-9d564826f406">

**Comment by AlonsoPlaza** [comment]
Hola, podrías subir tu código a tu repositorio personal para tener más contexto?

**Comment by lfcpardo** [comment]
Hola, lo acabo de subir

**Comment by martinrubilar** [comment]
hola, tengo el mismo problema, porque podria ser?

**Comment by lfcpardo** [comment]
me pasa lo mismo con el test en pizzas_con_ingredientes

**Comment by AlonsoPlaza** [comment]
El problema puede estar en como comprueban si la pizza tiene ese ingrediente, acuerdense que no es lo mismo "salsa de champiñones" a "champiñones"
