### ISSUE TITLE
Consistencia en el formato de los nombres en archivos .csv

### ISSUE THREAD

**Issue by tocococa** [IIC2233/syllabus#535]
Como el programa tiene que ser _case insensitive_, mi pregunta vendría a ser, es posible que el nombre de una criatura en criaturas.csv sea, por ejemplo, arthurdent. Pero que en magizoologos.csv, para el magizoologo que la posee, su nombre esté escrito como ArthurDent?

**Comment by moquezada** [comment]
Hola @tocococa,

En la issue #463 se habla sobre la relevancia de mantener el formato de los nombres respecto a como fueron asignados.

Saludos :smile:

**Comment by tocococa** [comment]
Gracias! Mi pregunta era más o menos eso, pero también me gustaría saber si previo a que el programa manipule los csvs nos podrían entregar archivos en que los nombres están guardados de esa manera.

**Comment by moquezada** [comment]
@tocococa, puedes asumir que usaremos archivos donde el formato de los nombres se mantiene, por lo que estarán escritos de la misma forma 😄 De todas formas, recuerda mencionarlo como un supuesto en tu README!

Saludos! ☺️

**Comment by tocococa** [comment]
Oka, gracias!
