### ISSUE TITLE
Manejo de imagenes

### ISSUE THREAD

**Issue by Ed0ss** [IIC2233/syllabus#535]
Hola tengo una duda con el manejo de imagenes, en particular con el hecho de pasar imagenes de un formato cualquiera a png. Tengo entendido que el cliente envía la imagen que él quiera a través de bytes, y luego el servidor se encarga de agarrar esta información y transformarla a png, para luego pasarla a su base de datos y devolver esta imagen para que se muestre en la interfaz. El problema con esto es que el servidor debe guardar esta imagen de formato cualquiera en alguna parte para poder obtener la matriz rgb con pixel_collector, por lo que al final debe borrar esta imagen temporal, y siento que esto se podría ahorrar si es que el cliente sea el que agarre su imagen y él transforme la información a png, enviando así la imagen en formato png y no en un formato cualquiera.

Saludos!

**Comment by jeschuwirth** [comment]
Hola!

Antes que nada para corregir la tarea sólo se van a utilizar archivos .png para facilitar el trabajo.

El enunciado dice:

> Es importante destacar que el servidor deberá guardar las fotos de perfil de los usuarios en formato PNG. Por lo que al recibir una nueva foto, debe obtener la matriz RGB, y posteriormente guardarla en formato PNG.

sin embargo la función get_pixels(image_path) que les pasamos necesita el path de una imagen, por lo que efectivamente necesitarías guardar la imagen en formato no png para luego transformarla a .png

Una forma de hacerlo es crear el archivo IMAGEN.JPG en la carpeta de servidor, luego utilizar get_pixels para crear el archivo .png y borrar el .JPG, pero para evitar crear imágenes temporales y aprovechando que sólo se va a corregir con archivos .png no hay problemas con que el cliente transforme la imagen a .png y luego envíe los bytes al servidor.

Recuerda especificar en el readme como lo hiciste y aprovecha de citar esta issue para evitar problemas en la corrección.

Suerte en la tarea !

**Comment by bvallejo1** [comment]
Hola, @jeschuwirth como dices hice una carpeta "fotos" en la carpeta de mi servidor, además de tener mi base de datos "data.json" con el usuario y el respectivo path de su foto , el tema es que cuando ingresa un usuario el cliente notifica sobre esto al servidor y este le dice si es válida su conexión o no, de ser válida le envía el nombre y su respectiva foto, pero esta foto tiene un path del tipo "./fotos/path.png". Dado esto el front no puede leer el path de la foto de ese usuario, debería hacer que el cliente busque en la carpeta de fotos del servidor o eso sería incorrecto?  De ser así como podría acceder a esa imagen.

Muchas Gracias.

**Comment by jeschuwirth** [comment]
Gracias por el recordatorio :sweat_smile:

El cliente nunca debe buscar cosas en la carpeta del servidor, eso se explica mucho en la sección de separación funcional (s 4.2.1).

Lo correcto en este caso es que el servidor mande el archivo.png de vuelta en forma de bytes en vez del path, ya que el cliente no tiene porque tener la foto en su computador.

Exito en la tarea!
