### ISSUE TITLE
Diagramación de clases

### ISSUE THREAD

**Issue by francisca0308** [IIC2233/syllabus#536]
Hola!!
Tengo una duda respecto a las relaciones de clases en una diagramación. No estoy segura si al dar una relación de composición de A con B y luego una de agregación de B con C implica que A tiene una relación de composición con C. 

No estoy segura si se entiende la pregunta

**Comment by moquezada** [comment]
Hola @francisca0308,

Tal como tú dices, existiría una relación de composición de A con C 😱 Ten en cuenta que al momento de realizar el diagrama de clases solo bastaría con mencionar la relación de composición entre A y B y la relación de agregación de B y C, dado que la composición entre A y C queda implícita y se puede desprender de ellas.

Saludos!

**Comment by francisca0308** [comment]
Muchas Graciaaas!!
