### ISSUE TITLE
Duda sobre abrir una ventana si cierro otra

### ISSUE THREAD

**Issue by Piolawa** [IIC2233/syllabus#536]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Al presionar el botón volver en la ventana ranking logro volver a la ventana de inicio, pero no entiendo como lograr abrir la ventana de inicio solo si cierro la ventana de ranking, es que los ejemplos de los contenidos solo abren una ventana cuando cierran otra a través de un botón que crean en la ventana. Algún hint? :c

**Comment by JadrinaDA** [comment]
Hola! Voy a darte un pequeño hint. Tal vez puedes hacer un override de cierto evento que ocurre al cerrar la ventana ;). Buena suerte!

**Comment by Piolawa** [comment]
Gracias!, ahí me resultó c:
