### ISSUE TITLE
Manera correcta para linkear Front- y Backend

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#536]
Hola, 

Cual sería la forma correcta para conectar estos dos. 
Todo lo que encuentro es para desarollo web. 

Lo que estoy haciendo hasta ahora es:
1.En el Frontend crear Objetos.
2. Si el objeto va a interactuar con el backend le creo una self.shadow = ObjetoEnElBackend() que sería su sombra en el backend, con funciones que retornan lo que necesite el frontend como tambien guardando información cuando sea necesario.

De esta manera cuando tengo que hacer algo no Frontend lo hace la sombra del objeto y luego lo retorna para que el Frontend pueda usar esa información (moverse, girar, etc..)

Mi duda es, está correcto eso de meter Objetos del Backend en el Frontend? Como se podría hacer mejor o más simple? En la ayudantía del Martes hablaron de algo de Trigges, pero no he podido encontrar nada al respecto. 

De antemano muchas gracais.

**Comment by iqacevedo** [comment]
Hola !

Por como lo explicas tiene sentido lo que estas haciendo, pero para ver si realmente estas haciendo bien la distinción entre el fronted y el backend debes entender que el fronted es quien mueve los labels y las ventanas, todos los cálculos y ese tipo de cosas que actualizan a los labels se hacen por detrás.
 
Mediante el uso de señales (ahí se ocupa lo que escuchaste de trigger) se comunica el backend con el fronted para indicarle cuando y como modificar las cosas. En el ejemplo que se entrego junto al enunciado de esta tarea puedes observar que en la clase `Character` se tiene ` trigger = pyqtSignal(MoveMyImageEvent)`, esto crea una señal, la cual conectas a la ventana `Bastian` (Fronted) con `self.trigger.connect(parent.actualizar_imagen)`, luego cuando activas la señal desde el Backend se llama al método `actualizar_imagen` entregándole un objeto de la clase `MoveMyImageEvent`, porque se indico que seria este objeto cuando se creo la señal. Finalmente, en setter de posición se enviá la señal al Fronted con `self.trigger.emit(MoveMyImageEvent(self.image, self.position[0], self.position[1]))` y el Fronted es quien actualiza la posición del label mediante el método `actualizar_imagen`.

No soy el mejor redactando :sweat_smile:, así que cualquier duda pregunta no más y si entendías todo esto y no respondí tu duda también jajajaja.

Saludos !

**Comment by acrojas2** [comment]
@Kitaps lo de los trigger aparece acá: http://pyqt.sourceforge.net/Docs/PyQt5/signals_slots.html.
En vdd no sé mucho, pero creo que los triggers es un nombre por convención, según yo, cuando hablan de los triggers hablan de la función pyqtSygnal. 
Espero haberte ayudado.

**Comment by hanavarrete** [comment]
Exacto, con los triggers nos referimos a la señal, por el hecho de que se "gatilla". Saludos

**Comment by Kitaps** [comment]
Yaa buena gracias
:o en que momento agregaron ejemplo!

Ya cerrare la issue por ahora, si sigo con más dudas la abro denuevo. Gracais !!

**Comment by hanavarrete** [comment]
Lo agregamos el jueves pasado pero fuimos ignorados :'(

2017-05-29 20:29 GMT-04:00 Kitaps <notifications@github.com>:

**Comment by AmbrosioV** [comment]
Tengo una duda de linkear frontend con backend. Si en el frontend pretendo tener el juego el que corre todas las operaciones que no tienen que ver con pyqt, pero que son importantes para el frontend -por ejemplo en el juego recalculo las posiciones de los minions, sus vidas etc- puedo pasar estos valores directo  tiene que ser por medio de señales?

**Comment by Hernan4444** [comment]
@AmbrosioV te recomiendo que se hagan mediante señales. 

Imagina que el frontend necesita recalcular la posición de un minion y lo hace de forma directa, eso implica que el frontend ejecutará algún método del backend y esperará al return de este para continuar con el siguiente método y por lo tanto no podrá estar pendiente de otras señales como otro click.

En cambio si se manda una señal, el otro método se ejecutará como un thread y por lo tanto el frontend podrá realizar otras acciones y cuando ese thread terminé de calcular lo necesario mandará una señal al frontend ejecutando un método con ese resultado.

Saludos!!!

**Comment by AmbrosioV** [comment]
Pero si esa ejecución del calculo es un Qthread no tendría que esperar nada, sino que seria paralelo en mi frontend. Mi pregunta es si es un error de modelacion tener el juego en el frontend.

**Comment by Hernan4444** [comment]
Aunque sea un Qthread, si tu tienes algo así en el frontend: `self.backend.calcular_algo(*args)`, el frotend se quedará esperando un return, mientras que si haces una señal, ahí se utilizará la propiedad que es un Qthread y la frontend no esperará nada.

Sobre tu duda de modelación, no está mal, el frotnend puede contener de atributo al backend o al reves el backend instancia al frotnend pero la idea de tenerlo es solo para realizar todas las conexiones necesarias y tener una referencia entre ellos pero no para activar métodos del otro de forma directa

Saludos!

**Comment by AmbrosioV** [comment]
Ok, entonces mientras llame por medio de una conexión los métodos del juego no hay problema.
Pero nose si me explique, si en mi frontend dentro de mi mainwindow tengo objetos qthreads que ejecutan ellos el calculo (llamando al backend por medio de una señal) y esos qthreads se encargan de modificar el frontend -con lo recibido del backend un qlabel por ejemplo-. Habria problema de que se va a quedar esperando?

**Comment by Hernan4444** [comment]
no se quedaá esperando pero ahí estarás haciendo que el backend modifique de forma directa al frontend (modificando el label) y llegarás a que en un momento tendrás lag en tu juego. Si la cantidad de objetos que hacen eso son pocos tal vez no te percates de ese problema pero cuando aumente la cantidad verás que los objetos dejaran de responder a la velocidad que quieras, la idea sería que luego de que el frontend le mande una señal al backend, este le responda con otra señal al frontend para que la interfaz edite los labels, así el frontend edita todo lo que sea interfaz y el backend hace todo lo que sea calculo pero ninguno toma el rol de otro.

**Comment by AmbrosioV** [comment]
Tengo una duda aparte, como el backend podría mandar una señal al frontend. Si no importa cosas de pyqt.
Y siguiendo con lo anterior, el backend no modifica el frontend -sino que es llamado por este a ratos en un thread por medio de señales- y con lo que recibe del backend se modifica a si mismo.
Gracias por las respuestas,!

**Comment by Hernan4444** [comment]
> el backend no modifica el frontend -sino que es llamado por este a ratos en un thread por medio de señales- y con lo que recibe del backend se modifica a si mismo.

En teoria es un QThread o QTimer y por lo tanto puede poseer un `QtCore.pyqtsignal` para comunicarse con el frontend

**Comment by AmbrosioV** [comment]
Me surgió otra duda, no seria circular que ambos se manden señales?

**Comment by Hernan4444** [comment]
circular es cuando uno desde un objeto puedes acceder a los atributos y métodos del otro y ese otro objeto puede acceder a los atributos y métodos de quien lo contiene. En este caso no se puede acceder a los atributos y solo es a métodos específicos que conectas.

Saludos
