### ISSUE TITLE
diagrama de clases

### ISSUE THREAD

**Issue by mleon17** [IIC2233/syllabus#536]
Hola, tengo muchas dudas respecto al diagrama de clases respecto a las herencias y clases abstractas. Hay alguna posibilidad de que algún ayudante me contacte para ayudarme porfa? Gracias

**Comment by gatochico** [comment]
¡Hola, @mleon17! 

Citando la respuesta de @tomasgv en #485 :
El pedir ayuda personalizada por canales no-oficiales (ej: _mail_ o _zoom_) es un poco más difícil, ya que dependerá de la disponibilidad de lxs ayudantxs.

Si deseas una respuesta más rápida, te recomiendo hacer una (o más, dependiendo de qué tan separadas estén las dudas) issue con tu duda de forma directa, así quien sepa la respuesta podrá contestarte cuanto antes y será una forma más rápida de atención.

Si lo sientes necesario, puedes contactarte con Tomás en el correo de Bienestar (bienestar.iic2233@ing.puc.cl) para agendar sesiones de repaso con otrxs estudiantes que necesiten también la ayuda. 

Saludos y espero se entienda! 🏃

**Comment by mleon17** [comment]
Muchas gracias! me contactare con el
