### ISSUE TITLE
Eventos iniciales

### ISSUE THREAD

**Issue by mblejeune** [IIC2233/Syllabus#536]
Hola! Estoy haciendo correr mi simulacion y nose si es necesario que tenga eventos iniciales, si la respuesta es si, estos serán los primeros que salen en cada dia ? por ejemplo, para el Lunes el evento que es a las 10:00 y si hay mas de uno a las 10:00 se toman ambos, para el martes el de las 10:06 y asi sucesivamente, y despues la idea es que al ir agregando nuevos grupos a mi parque de diversiones agregue los que vienen luego de estos eventos iniciales (dependiendo del dia que este viendo)?

Muchas gracias! :)

**Comment by yoavnavon** [comment]
Hola! No estoy seguro si te entiendo. Los eventos iniciales serán simplemente lo primero que pase en el parque. Si entre 10:00 y 10:06 no pasa nada, el evento inicial será este grupo de personas que llegó. En ese sentido, los eventos se ponen todos en una cola, y lo primero que ocurrió será el evento inicial del día. Nose si te respondí, saludos!
