### ISSUE TITLE
Material extra de simulación por eventos discretos

### ISSUE THREAD

**Issue by GabrielLyonB** [IIC2233/Syllabus#536]
Hola a todos,

Después de la actividad del jueves hubo un par de alumnos que me preguntaron cómo detectar eventos en una simulación por eventos discretos, por lo que les preparé un pequeño material para esto. Espero que les puede ser de utilidad. Ya esta subido en el Syllabus en la carpeta `Ayudantías/Extras`.

Suerte con la tarea!
Saludos!

**Comment by rgevert** [comment]
gracias!
