### ISSUE TITLE
Abrir archivo con extensión json

### ISSUE THREAD

**Issue by JosefaPaz** [IIC2233/syllabus#536]
Hola!

Estoy intentando abrir el archivo 'usuarios.json' para la T03, y me sale este error al ejecutar esta parte del código:

![imagen](https://user-images.githubusercontent.com/41802643/69496859-7bf8e500-0eb5-11ea-8f3e-106eaec73bf9.png)

![imagen](https://user-images.githubusercontent.com/41802643/69496868-9c28a400-0eb5-11ea-911c-4982634572ef.png)

Ojalá puedan ayudarme ya que no veo que estoy haciendo mal, estoy usando el mismo procedimiento para la AC09 y en ese momento sí me funcionó.

Gracias!!

**Comment by JosefaPaz** [comment]
Lo solucioné copiando todo el contenido de 'usuarios.json' en otra hoja y sobre-escribiendo la que entregaban, pero me gustaría saber por qué sucede este error.

Gracias :smile:

**Comment by lily416** [comment]
Primero, gracias por avisar y lamento el error. 🙇‍♀  

Cuando se creó el archivo `usuarios.json` hubo un problema con el _encoding_, ya que se utilizó `utf-8-sig` en vez de `utf-8`.

Se subió una nueva versión del archivo al repositorio, este se puede leer correctamente utilizando _encoding_ `utf-8` o el _encoding_ por defecto.


Saludos y éxito en tu tarea 👋🐧
