### ISSUE TITLE
ERROR NSWindow drag regions should only be invalidated on the Main Thread 

### ISSUE THREAD

**Issue by vicentesh** [IIC2233/syllabus#536]
Hola, estoy tratando de hacer .show() a una ventana y me lanza este error, no se que puede significar

WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
	0   AppKit                              0x0000000105ed1ccc -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 386
	1   AppKit                              0x0000000105ecf07c -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1488
	2   AppKit                              0x0000000105f8f95b -[NSPanel _initContent:styleMask:backing:defer:contentView:] + 50
	3   AppKit                              0x0000000105eceaa6 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
	4   AppKit                              0x0000000105f8f910 -[NSPanel initWithContentRect:styleMask:backing:defer:] + 64
	5   AppKit                              0x00000001061a1ad4 -[NSWindow initWithContentRect:styleMask:backing:defer:screen:] + 52
	6   libqcocoa.dylib                     0x0000000115013dd5 qt_plugin_instance + 163845
	7   libqcocoa.dylib                     0x0000000115000ff0 qt_plugin_instance + 86560
	8   libqcocoa.dylib                     0x0000000114ffac02 qt_plugin_instance + 60978
	9   libqcocoa.dylib                     0x0000000114ffa68b qt_plugin_instance + 59579
	10  QtGui                               0x0000000105344b0c _ZN14QWindowPrivate6createEby + 140
	11  QtWidgets                           0x0000000104d9dd71 _ZN14QWidgetPrivate10create_sysEybb + 1201
	12  QtWidgets                           0x0000000104d9ca26 _ZN7QWidget6createEybb + 326
	13  QtWidgets                           0x0000000104dafe73 _ZN14QWidgetPrivate10setVisibleEb + 195
	14  QtWidgets                           0x0000000104f71f1d _ZN7QDialog10setVisibleEb + 125
	15  QtWidgets.so                        0x00000001049322ee _ZN10sipQDialog10setVisibleEb + 110
	16  QtWidgets.so                        0x0000000104a507cb _ZL17meth_QWidget_showP7_objectS0_ + 75
	17  Python                              0x00000001007627c8 _PyCFunction_FastCallDict + 552
	18  Python                              0x00000001007eb5e4 call_function + 612
	19  Python                              0x00000001007ecfe4 _PyEval_EvalFrameDefault + 5604
	20  Python                              0x00000001007eb32e fast_function + 606
	21  Python                              0x00000001007eb5cb call_function + 587
	22  Python                              0x00000001007ecfe4 _PyEval_EvalFrameDefault + 5604
	23  Python                              0x00000001007eb9cc _PyFunction_FastCallDict + 828
	24  Python                              0x0000000100706724 _PyObject_FastCallDict + 356
	25  Python                              0x0000000100706840 _PyObject_Call_Prepend + 208
	26  Python                              0x0000000100706353 PyObject_Call + 99
	27  Python                              0x00000001007eda66 _PyEval_EvalFrameDefault + 8294
	28  Python                              0x00000001007eb32e fast_function + 606
	29  Python                              0x00000001007eb5cb call_function + 587
	30  Python                              0x00000001007ecfe4 _PyEval_EvalFrameDefault + 5604
	31  Python                              0x00000001007eb32e fast_function + 606
	32  Python                              0x00000001007eb5cb call_function + 587
	33  Python                              0x00000001007ecfe4 _PyEval_EvalFrameDefault + 5604
	34  Python                              0x00000001007eb9cc _PyFunction_FastCallDict + 828
	35  Python                              0x0000000100706724 _PyObject_FastCallDict + 356
	36  Python                              0x0000000100706840 _PyObject_Call_Prepend + 208
	37  Python                              0x0000000100706353 PyObject_Call + 99
	38  Python                              0x0000000100843ac7 t_bootstrap + 71
	39  libsystem_pthread.dylib             0x0000000101c59305 _pthread_body + 126
	40  libsystem_pthread.dylib             0x0000000101c5c26f _pthread_start + 70
	41  libsystem_pthread.dylib             0x0000000101c58415 thread_start + 13

**Comment by jeschuwirth** [comment]
Hola!

El problema que tienes es que intentas abrir una nueva ventana desde un thread que no es el principal. Los Qt widgets no se consideran seguros para el uso de thread y por esa razón sólo puedes utilizarlos desde el principal.

Para solucionarlo debes agregar señales que los thread extra envíen al principal para que éste abra la ventana.

El siguiente link de Stackoverflow comenta sobre el mismo problema, por si sigues teniendo dudas.
https://stackoverflow.com/questions/9957195/updating-gui-elements-in-multithreaded-pyqt

Suerte en la tarea!

**Comment by vicentesh** [comment]
funcionooo gracias Juan 😄

**Comment by jeschuwirth** [comment]
😄
