### ISSUE TITLE
Host tarea

### ISSUE THREAD

**Issue by cchauriye** [IIC2233/syllabus#537]
Hola!

Se supone que en el archivo parametros.json debemos ingresar una dirección IP del host. ¿Asumimos que cuando lo corrijan cambiarán ese valor a mano o debemos desarrollar un código que lo detecte solo? Aún no tengo muy claro cómo funciona eso.

Gracias!

**Comment by jeschuwirth** [comment]
Hola,

El ayudante va a cambiar la ip a mano :)

Recomiendo dejar "localhost" como la ip en parámetros, de ese modo no va a ser necesario cambiarla.

Suerte!

**Comment by jeschuwirth** [comment]
Hola,

El ayudante va a cambiar ese valor a mano :)

Recomiendo utilizar "localhost" como IP en el parámetro del servidor para no tener que cambiarlo.

Saludos!

**Comment by cchauriye** [comment]
Gracias!
