### ISSUE TITLE
Sprites

### ISSUE THREAD

**Issue by fcgfaura** [IIC2233/Syllabus#537]
Hola!, de qué páginas están sacando los sprites ? 🤔. Alguien me podría soplar alguna ?

**Comment by Kitaps** [comment]
https://www.spriters-resource.com/

**Comment by iqacevedo** [comment]
No tengo una pagina buena para recomendarte, pero si puede ayudarte buscar en Google usando palabras claves como _topdown sprite_ (que son sprites con una vista desde arriba), _sprites lol_,  _sprites warcraft_ o _sprites age of empires_ (que son otros juegos que ocupan estructuras similares).

Saludos!

**Comment by acrojas2** [comment]
@iqacevedo yo he buscado sprites de la onda de LoL, pero lo que necesito es que sean _topview_ o _topdown_ como lo mencionas en tu comentario y la verdad es que me ha ido super mal porque solo hay zoombies y warriors tipo militar, y no sé que tan exigentes sean con esto. Me gustaría saber si les importa que tenga lógica el fondo con los monitos, y que la rotacion del monito tenga lógica en cuanto a imagen (por ejemplo si el mousse indica a la izquierda que los ojos del mono estén mirando en esa dirección independientes si sus pies están en el "suelo" o no). No sé si se entiende mi preocupación. Yo tengo mi fondo estilo lol y todo en la onda de LoL menos los sprites que aún no los encuentro. 
Duda extra: los equipos deben tener diferenciación en pantalla o da igual que todo lo que tenga un equipo sea igual al otro ?
Saludos!

**Comment by hanavarrete** [comment]
La verdad es que no evaluamos que son tus personajes. Como dijo ignacio
antes, podrían ser gatitos y da igual jajaja. Mientras que se note que la
imagen está "enfocada" o mirando hacia el puntero está bien. Ojalá que los
equipos sean diferentes, aunque sea el color (eso lo puedes hacer con paint
incluso). Saludos!

**Comment by hanavarrete** [comment]
Igual, tal vez no encuentres a los personajes del lol, pero si buscas cosas estilo "warrior top view sprite" etc. Deberías encontrar cosas que podrían ser útiles en el contexto del lol.
