### ISSUE TITLE
Error al updatear QTableWidget

### ISSUE THREAD

**Issue by diaztunjano** [IIC2233/syllabus#537]
Hola! 

Estoy implementando un QTableWidget (la cual creo desde el Qt Designer y en mi código solo hago el self.setupUi(self) y self.init_setUp() para mostrar todo lo de la ventana) para mostrar las salas, enviando el server la información de las salas creadas para que se actualice en cada vez que alguien crea alguna sala. 

Después las actualizo con función posterior que les agrega celdas a esta tabla con self.tabla_salas.setItem(i, 0, QTableWidgetItem(sala)), pero no se ven las celdas que acabó de crear. 

He leido la documentación y no encuentro algún método estilo .refresh(), cómo puedo implementarlo? 

Gracias!

**Comment by jeschuwirth** [comment]
Hola!

Perdón por la demora, si sigues teniendo el mismo problema podrías intentar QWidget.update(). 

Si eso no te resulta puedes intentar QWidget.hide(), QWidget.show(), y si eso tampoco resulta entonces puede que tengas un problema al agregar el objeto.

Ojalá te ayude y éxito en la tarea !
