### ISSUE TITLE
Separación entre frontend y backend

### ISSUE THREAD

**Issue by minsoos** [IIC2233/syllabus#537]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, tenía la duda de si podía tener separado mi programa sólo respecto a las ventanas, sucede que se me hace más cómodo (y lo siento más fácil de ver también) que el código del backend y el frontend de una ventana estén en el mismo archivo. Obviamente, igual están separados, cada uno tiene una clase, Ventana y LogicaVentana respectivamente.
Esto en contraposición de lo que ha sido común en el curso, hacer un backend y frontend en archivos separados para cada ventana.
Saludos!
Min Soo

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Juampisaez** [comment]
Hola @minsoos 
La forma en que pongas las clases de tu programa dependera de como lo hayas modelado. Lo que tu dices podrias hacerlo, pero debes tener en cuenta que habran dos items de la revision en que no tendrias puntaje, ya que se considera no muy buena modelacion ni modularización.
De igual manera, te recomiendo intentar modelarlo por lo menos en archivos separados, de esta forma estaria todo separado. (no es vital que esten en carpetas distintas, aunque también se recomienda fuertemente por temas de modelacion como ya dije).

Espero sea de ayuda, cualquier cosa me dices :)

**Comment by minsoos** [comment]
Gracias!
