### ISSUE TITLE
duda protocolo respuestas issues

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#537]
Hola, imaginemos que alguien pregunta una issue y se le responde, luego yo pasé por la misma duda pero lo dejé "a mi criterio" y no vi la issue y lo resolví de forma distinta, haya especificado o no en el readme.
Me van a descontar por eso?
**(aplica desde la tarea 1 en adelante pls)**
Pasa que no creo tener la capacidad de leer y mantener presentes las al rededor de 100 issues que se generan en cada tarea.

**Comment by rihanuch** [comment]
¡Hola @jmwielandt !

La tarea se corrige según lo que se especifica en el enunciado más las aclaraciones de dudas que vayan surgiendo, tal como se dijo a principio de semestre en la issue #3 🔙

> Este foro está para que compartan sus dudas. También será usado para publicar información relevante en algunos casos.
Este es un medio oficial de comunicación por lo que es tu deber revisarlo periódicamente, ojalá todos los días, para que no estés desinformado/a.

Es decir, si hay algo que cambie el funcionamiento del programa, es tu responsabilidad estar atento a estos cambios 😬

Personalmente, lo que hacía para mantenerme al tanto es activar las notificaciones de las issues y sus comentarios. Para hacerlo simplemente tienes que ir a issues y poner "Watch 👁", con lo cual estarás informado de cada comentario e issue nueva que se haga.

¡Saludos y suerte! 🍀

**Comment by 96jaime** [comment]
tengo una duda respect a esto, pues en las reglas sale que los marcados "IMPORTANTE" son los que se concideran obligatorios y no se puede recorregir si no salía en enuciado pero si en estos. Para que se haría la distinción  si todas las  issues sería no apelatorias en caso de no leerlas?? No será acaso, y es lo que se infiere de la #3 , que lo único que modificaría u obligaría con respecto a una tarea serían las "IMPORTANTE"

**Comment by jmwielandt** [comment]
@96jaime en las reglas también sale que luego de que nos respondan una issue debemos dar las gracias y cerrarla pero a principio de semestre decían que no las cerráramos :/
