### ISSUE TITLE
Dudas sobre conexiones cliente-servidor

### ISSUE THREAD

**Issue by isidoragutierrez** [IIC2233/Syllabus#537]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola! Mis dudas son sobre los contenidos de la semana 9: networking.

Primero, 
Repasando para el examen noté que en varias ocasiones se cerraba el socket del cliente desde el código del servidor luego de que éste último aceptara una conexión. Por ejemplo, tenemos este código para el servidor:

```python
import socket

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.bind((socket.gethostname(), 9000))
sock.listen()

while True:
    socket_cliente, address = sock.accept()
    socket_cliente.sendall("Gracias por conectarte\n".encode("utf-8"))
    socket_cliente.close() # Aquí se cierra el socket del cliente que aceptamos

sock.close() # Aquí cerramos nuestro socket de conexión (servidor)
```
Pero en ninguno de los ejercicios/ejemplos proporcionados a través de ayudantías, experiencias, actividades, etc., se cierra el socket del cliente en el código del servidor sino que simplemente se cierra el socket del servidor cuando se quiere terminar el programa. 

¿Es realmente necesario hacer ```socket_cliente.close()``` en el código del servidor? ¿En qué casos se debe hacer y cuál es la diferencia con no hacerlo?

Segundo,
No tengo muy clara la relación entre el puerto especificado en el ```.connect()``` del cliente versus el ```.bind()``` del servidor. Es correcto decir que: en el caso de que ambos códigos se corran en el mismo computador el puerto debe ser el mismo, pero en el caso de que los códigos se corran en computadores distintos, no es necesario que los puertos sean iguales?
El puerto especificado en ```.connect()``` es el puerto que se usará en el computador donde se está ejecutando el cliente, en cambio, el puerto especificado en ```.bind()``` es el puerto que se usará en el computador donde se está ejecutando el servidor?

Muchas gracias de antemano.

**Comment by esperanzaacevedo** [comment]
Hola! yo tengo la misma duda

**Comment by esperanzaacevedo** [comment]
Hola, entonces porque la afirmación I, estaría incorrecta?
 
![IMG_7814](https://github.com/IIC2233/Syllabus/assets/141953897/47452711-5782-4266-8e24-a45492608a99)

**Comment by mskdancers** [comment]
Es una diferencia conceptual. Lo que pasa es que los números de puertos con los que trabajamos en el `.connect` y el `.bind` son **ambos** el puerto del destinatario, es decir, el puerto por el cual el servidor está escuchando. El puerto de origen es el puerto por el cual se comunica el cliente, y generalmente no se lo especificamos al programa. Es por esto que no necesariamente tienen que ser el mismo puerto; puedo tener un cliente comunicándose mediante el puerto 80 y un servidor escuchando en el puerto 100, sin embargo el argumento del `.bind` y `.connect` para ambos será `(hostname, 100)`.

Al usar un socket sin usar previamente el `.bind` (como hacemos por el lado del cliente) python te entrega un puerto que esté disponible ([dynamic memory allocation](https://www.geeksforgeeks.org/what-is-dynamic-memory-allocation/)) por el cual se pueda establecer la comunicación. Si estuvieras corriendo todo desde un solo computador y quisieras que el puerto de origen fuera el mismo al de destino, tu código se caería ya que no puedes usar un puerto simultáneamente para dos sockets; un error que te puedes haber encontrado si alguna vez se te olvidó cerrar el servidor y lo quisiste correr de nuevo (`OSError: [WinError 10048] Solo se permite un uso de cada dirección de socket`).

**Comment by isidoragutierrez** [comment]
Perfecto!! Muchas gracias!!!

**Comment by isidoragutierrez** [comment]
Perfecto!! Me queda todo clarísimo! Muchas gracias!!
