### ISSUE TITLE
¿Cómo modelar bien la simulación?

### ISSUE THREAD

**Issue by AndresGarciadelaHuerta** [IIC2233/Syllabus#537]
¿Es correcto modelar el run de mi clase Simulacion usando un for para los días y un while para cada uno de los eventos de ese día?
Así:
```python
def run(self):
     "Parametros a definir"
     for i in range(120):
           "Codigo a definir por cada dia"
           while True:
                 "Codigo que se ejecuta por cada evento del dia i"
```

Ya que tengo dudas de si es discreto o no. Gracias!!

**Comment by Hernan4444** [comment]
@AndresGarciadelaHuerta esa modealación es continua y no es lo evaluado en la tarea (no es correcta). Tiene que ser discreta.

Saludos ✌️

**Comment by AndresGarciadelaHuerta** [comment]
@Hernan4444 Gracias por responder! Me tincaba que no era discreta. Ahora mi duda es cómo lograr modelar lo que pasa sólo en un día y además que vaya cambiando de día de forma discreta con sólo un while para los eventos y sin poder usar un while o un for para los cambios de días? Cualquier pista se agradece jajaja

**Comment by fgbruna** [comment]
Podrías modelar el paso de un día como un evento, ya que hay variables que toman valores distintos cada día.
