### ISSUE TITLE
La opción salir en cualquier menú termina el programa?

### ISSUE THREAD

**Issue by Jairuru** [IIC2233/syllabus#537]
Hola! La pregunta cabía en el título jeje la opción salir termina el programa o sólo envía al menú principal? La opción salir del menú principal sí termina el programa?

**Comment by mpsubiabre** [comment]
Hola @Jairuru,

La opción salir hace referencia a terminar el programa, es decir toda opción que sea **salir**, independiente en que menu se encuentre, termina el programa.
Para volver a algún menu esta la opción volver atrás :)

Éxito en la tarea ✨
