### ISSUE TITLE
Tests carga datos

### ISSUE THREAD

**Issue by agukolubakin** [IIC2233/Syllabus#537]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Me di cuenta que en algunos tests de carga de datos (como en el 18 por ejemplo), solo se verifica con instancias de tamaño S y M, es necesario que comprobemos por nuestra cuenta que cumplan también para instancias de tamaño L y XL? O con tal de tener esos tests buenos es suficientes?

**Comment by AlonsoPlaza** [comment]
Hola, para las funciones de 3 generadores sólo se harán tests con archivos de tamaño S y M por lo que no es necesario que pruebes con archivos más grandes.
