### ISSUE TITLE
Error ventana pyqt5 'not responding'

### ISSUE THREAD

**Issue by clementesepulveda** [IIC2233/syllabus#538]
Hola! Por alguna razon trato de abrir una neuva ventana de pyqt5 y este no funciona y en el Title dice "Not Responding". En mi codigo ya he creado dos ventanas (una para conectarse al servidor y otro para ingresar el usuario) y entonces no entiendo porque esta tirando un error ahora.

**Comment by KnowYourselves** [comment]
Hola @clementesepulveda!

Dos preguntas:

1. El archivo que ejecutas tiene el exception hook definido?
2. Podrías hacer commit de tu programa para ver exactamente que podría ser?

Quedo atento!

**Comment by clementesepulveda** [comment]
Ya le hice commit y el exception hook donde va (o como se hace)?

**Comment by IngisRedd** [comment]
Creo tener el mismo problema. Pero por alguna razón, cuando trato de abrir la ventana nueva desde el frontend no ocurre. Sólo cuando lo hago desde el backend (clase Cliente). Esto me complica porque necesito corroborar los  requisitos para que se pueda abrir esa ventana, y estos cálculos nos piedieron expresamenete que se hicieran en el backend y no en el forntend.
No se muy bien que es eso del exception hook...:sweat_smile:

**Comment by KnowYourselves** [comment]
Okay!, Antes de meterme a probar tu código, agarra el siguiente código y ponlo exactamente después del `if __name__ == "__main__":` de tu `main_cliente.py`:

```python3
def hook(type, value, traceback):
        print(type)
        print(traceback)
sys.__excepthook__ = hook
```

Lo que pasa es que cuando ocurre una excepción en pyqt, el programa se queda pegado y no informa de ningún error. Lo que hace el código es interceptar toda excepción que ocurra en tu programa e imprimiendola, lo cual nos permite ver que error sucede, en vez de que se quede pegado el programa.

**Comment by videvidts** [comment]
Me pasa lo mismo, intento abrir una ventana desde el frontend (llamando desde cliente la funcion frontend.cerrar() y al abrir la ventana de juego se queda pegada (not responding). Hice commit recientemente, por si necesitan revisar algo.

Mi función cerrar es asi:
    def cerrar(self):
        self.ventana_salas.nombre_usuario = self.nombre_usuario
        self.close()
        self.ventana_salas.show()

**Comment by KnowYourselves** [comment]
@videvidts @IngisRedd , prueben ustedes agregando el except hook y diganme que error es!

**Comment by videvidts** [comment]
Solo me dice: Process finished with exit code 0

**Comment by videvidts** [comment]
Lo raro es que si entra a la función 'cerrar' de mi frontend

**Comment by videvidts** [comment]
Según lo que he estado viendo (haciendo muchos prints), mi error está aquí, esta es la exception que lo bota (está textual de la ayudantía por eso no me ubico tanto)

    def escuchar_cliente_thread(self, client_socket):

        while True:
            try:
                print("entra al try")
                # Primero recibimos los 4 bytes del largo
                response_bytes_length = client_socket.recv(4)
                print('no se cae aqui')
                # Los decodificamos
                response_length = int.from_bytes(response_bytes_length,
                                                 byteorder="big")
                print('aqui tpco')
                response = bytearray()
                print(response)
                print(response_length)
                while len(response) < response_length:
                    print("esta en el while")
                    print(len(response))
                    response += client_socket.recv(256)
                response = response.decode()

                if len(response) != 0:
                    decoded = json.loads(response)
                    self.manejar_comando(decoded, client_socket)
            except ConnectionResetError:
                decoded_message = {"status": "cerrar_sesion"}
                print("este es el error")
                self.manejar_comando(decoded_message, client_socket)
                break

**Comment by IngisRedd** [comment]
Creo haber aplicado bien el hook:
```python3
if __name__ == "__main__":
    def hook(type, value, traceback):
        print(type)
        print(traceback)
    sys.__excepthook__ = hook
    app = QApplication([])
    client = Client()
    sys.exit(app.exec_())
```
Pero no hay ningún cambio, no se imprime nada nuevo...

**Comment by clementesepulveda** [comment]
A mi me dice: Process finished with exit code -805306369 (0xCFFFFFFF)

**Comment by KnowYourselves** [comment]
@videvidts tu error es el siguiente:

PyQt esta pensado para que todo el manejo de ventanas (tanto mostrarlas como ocultarlas) suceda **siempre en el thread principal**, ahora, Cuál es el thread principal?, Pues **el archivo que fue ejecutado**. En tu caso sería `cliente.py`, por lo cual al hacer `self.ventana_salas.show()` en `frontend.py` tu programa muere debido a que intentas abrir una ventana fuera del thread principal.

Para solucionar este problema deberías implementar una señal que se conecte a una función del cliente para que en este archivo se haga `show()`. Cabe recalcar que para esto funcione, la ventana que quieras mostrar debe estar asociada al cliente con `self.`

Finalmente, en vez de ocupar `close` ocupa `hide`.

@IngisRedd, @clementesepulveda, podrían corroborar si su problema es el mismo?

**Comment by clementesepulveda** [comment]
Mi thread principal es main_cliente.py, y desde ahi abro y cierro todas mis ventanas (no desde el front_end), y ya ocupo el .hide() entonces no se si es el mismo problema.

**Comment by KnowYourselves** [comment]
@clementesepulveda, caes en exactamente el mismo error.

En tu caso, tu problema es que tu thread principal es el cliente, pero cuando te conectas al servidor empiezas un thread que escucha al servidor, luego, cuando haces show, lo haces en ese thread, no en el principal.

Para solucionar esto, debes utilizar señales. Especificamente, debes hacer lo siguiente:

1. Definir una señal en la ventana que vas a querer mostrar.
2. Conectar en el cliente esa señal al show de la ventana.
3. Emitir la señal cuando te llega la respuesta del servidor.

Ahora, Por qué funcionaría esto siquiera?, Funcionará debido al hecho de que cuando haces emit, el thread que ejecuta la función es **el thread donde se hizo connect**, es decir, si conectas el show de tu ventana a la señal, en tu thread principal, entonces cuando hagas emit, se hará en este mismo, resolviendo el error.

Espero haberte ayudado!

**Comment by IngisRedd** [comment]
Ese era mi problema también, lo pude solucionar. Gracias!

**Comment by videvidts** [comment]
Muchas gracias!

**Comment by videvidts** [comment]
Todavía me pasa lo mismo :(

**Comment by KnowYourselves** [comment]
@videvidts haz commit!

**Comment by videvidts** [comment]
listo!

**Comment by KnowYourselves** [comment]
@videvidts, el problema es específicamente la línea 97 de tu cliente, en vez de hacer show, debiste haber seguido los tres pasos que describí antes y utilizar una señal. Eso arreglará tu problema!

**Comment by videvidts** [comment]
Muchas gracias, no leí lo de más abajo.

**Comment by videvidts** [comment]
No entiendo a que te refieres con "emitir la señal cdo llegue la respuesta del servidor". 
Hice una señal_mostrar = pyqtSignal() en mi frontend y lo conecté con una función iniciar_sesion de mi main_cliente (que consiste de frontend.hide() y ventana_salas.show()). Ahora no entiendo donde tengo que poner emit.

**Comment by KnowYourselves** [comment]
En la linea 97, en vez de hacer ventana.show, tienes que hacer alguna_señal.emit(), con esa señal habiendo sido conectada a ventana.show en el init de cliente.

Avísame como te va!

**Comment by videvidts** [comment]
me funcionoooooooooooooooooooooo gracias tkm eres el mejor

**Comment by KnowYourselves** [comment]
Me alegro!, Éxito en el resto!

**Comment by clementesepulveda** [comment]
A mi no me funciona eso, o tal vez lo estoy implementando mal. Hice una senal en la ventana que quiero hacer y lo conecte al cliente (a una funcion que hace self.front_end.show()) y entonces solo creo la ventana y hago emit, pero no funciona.

**Comment by clementesepulveda** [comment]
Ahora lo solucione instanciando la ventana en el __init__ del cliente y despues haciendole emit(). gracias!

**Comment by lfuenzalida2** [comment]
Yo estoy teniendo el mismo problema y he intentado de hacer show() en mi MainThread (el cual es mi archivo client.py) y derrepente me funciona, ahora estoy haciendo la ventana de sala de espera y solo me deja conectar al primer cliente, no al segundo o mas, cada vez que trato de entrar a la sala se me queda pegado, aplique el hook y no sale nada, estoy haciendo todo con señales (y segun yo estan bien, porque hasta ahora no he tenido problemas), algun consejo??

**Comment by JupaOlivares** [comment]
Hola tengo el mismo error y me dice TypeError: Cliente cannot be converted to PyQt5.QtCore.QObject in this context, no se en verdad como implementar correctamente la señal, estoy instanciando mi ventana en el init de mi clase cliente y le paso la señal al thread del cliente para que la emita.

**Comment by KnowYourselves** [comment]
@lfuenzalida2 estás seguro que estas haciendo show en el MainThread y no en el Thread que escucha al servidor? Lo segundo suena más problema del servidor que el cliente.

@JupaOlivares haz commit de tu código y veo que es!

**Comment by lfuenzalida2** [comment]
@KnowYourselves Tienes razon, no esta en el MainThread el show, como puedo ejecutar el .show() desde el MainThread sin tener que destruir el Thread actual?

**Comment by KnowYourselves** [comment]
@lfuenzalida Revisa mi quinto comentario en esta misma issue (el que tiene 3 pasos) y dime como te va!

**Comment by lfuenzalida2** [comment]
@KnowYourselves Ahí me funcionó, como que leí el comentario a la rapida y ahora que me lo recalcaz me di cuenta de que no lo estaba haciendo bien, le di 8mil vueltas y ahora recien me funciona.
Muchisimas Gracias! 🙌🙌🙌🙌

**Comment by JupaOlivares** [comment]
> @lfuenzalida2 estás seguro que estas haciendo show en el MainThread y no en el Thread que escucha al servidor? Lo segundo suena más problema del servidor que el cliente.
> 
> @JupaOlivares haz commit de tu código y veo que es!

Ya lo pude resolver gracias
