### ISSUE TITLE
Mensaje cuando el personaje colisiona con un lugar incorrecto

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#538]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! En la distribución de puntaje dice que se debe "mostrar un mensaje cuando colisiona con un lugar incorrecto" (parte derecha de la imagen adjunta). No entiendo bien a cuál ventana se refiere ni cómo debiese aparecer (mostrar un QLabel, abrir ventana con ese mensaje, imprimir en consola, etc.)

Busqué en el enunciado, pero no encontré que se deba implementar este mensaje. De todas formas me imagino que se refiere a la colisión entre el personaje y los lugares de la Ventana de Preparación.

De ser así, ¿es necesario que se imprima un mensaje si se equivoca de lugar o puede bastar que "no pase nada", es decir, que no pase a la ventana de juego?

Saludos!

![imagen](https://user-images.githubusercontent.com/50121013/120083151-ad4b0600-c094-11eb-8599-22322dfd72be.png)

**Comment by valerianazal** [comment]
Hola @jamigone ! Efectivamente se refiere a las colisiones que ocurren dentro de la **Ventana de Preparación** y sí, es necesario que se imprima un mensaje. Para esto último, te puede servir implementar un `QMessageBox`.
Quedo atenta a cualquier duda ☺️

**Comment by jamigone** [comment]
Gracias!

**Comment by franciscareti** [comment]
Hola! Tengo una duda respecto a esto mismo. Como está mostrada la ventana de preparación en el enunciado, la primaria está después de la planta y el personaje se movería de forma horizontal. Mi duda es que, en ese caso, Lisa siempre chocaría con la planta para poder llegar a su ubicación, entonces siempre se imprimiría ese mensaje de error? Y así también, Homero nunca chocaría con la primaria porque se encuentra con la planta antes... No sé si me estoy enredando, pero feliz si me lo pueden aclarar! Mil gracias

**Comment by valerianazal** [comment]
Hola @franciscareti ! 
El personaje no necesariamente se va a mover de manera horizontal en la Ventana de Preparación, por lo que no chocaría en todos los casos con un lugar incorrecto. Ahora bien, si pones límites de movimiento de tal forma que el personaje solo puede moverse por la calle y no por el pasto, podrías poner los sprites de los lugares más pequeños, para que se puedan evitar colisiones no deseadas. De todas formas, en en caso que pusiste de Lisa, sí debería mostrarse el mensaje cada vez que pase por ahí en la Ventana de Preparación.
Espero haberte ayudado! Cualquier cosa no dudes en comentar nuevamente esta issue ☺️

**Comment by mjsifri** [comment]
Hola, para imprimir el mensaje puedo hacerlo con QLabels? o si o si hay que usar QMessageBox?
saludos

**Comment by valerianazal** [comment]
Hola @mjsifri ! Puedes hacerlo como tú quieras, asegúrate que se note bien al momento de mostrarlo. 
Aún así te recomiendo buscar el QMessageBox, ya que es una muy buena forma de implementarlo.
Mucho éxito! ✨
