### ISSUE TITLE
imagenes de heroes

### ISSUE THREAD

**Issue by rjdelrio** [IIC2233/Syllabus#538]
es estrictamente nesesario que Chau la hechicera y Hern´an el destructor sean unna maga y un barbaro, no pueden ser otra cosa?

**Comment by iqacevedo** [comment]
Hola !

Puede ser cualquier cosa, lo importante es que se comporten como indica el enunciado.

Saludos !

**Comment by rjdelrio** [comment]
muchas gracias :D

**Comment by hanavarrete** [comment]
No cierren las issues tan rápido para que la gente las vea amigo 😄

**Comment by rjdelrio** [comment]
sorry pense que habia que cerrarla altiro perdon  T_T

**Comment by hanavarrete** [comment]
@rjdelrio lo conversamos con los ayudantes y llegamos a la decisión de que estás perdonado, saludos!

**Comment by rjdelrio** [comment]
aajajajajaja ok gracias
