### ISSUE TITLE
Little Endian and Big Endian

### ISSUE THREAD

**Issue by anvaldes** [IIC2233/syllabus#538]
Hola! No entendí muy bien lo de big endian y little endian, pero lo que encontré en internet fue que para pasar un numero a big endian es:

numero.to_bytes(4, byteorder='big')

Y para pasar a little endian es:

numeroto_bytes(4, byteorder='little')

Y resulta que según el ejemplo que dan en el pdf se cumple perfect con big endian. Es decir, me dan que valor da con 1 y 2 y coincide, pero no pasa así con little endian que me dan el numero 300 y uds me ponen un valor y no me da ese valor según esa codificación. En que estoy equivocado?

**Comment by fdoflorenzano** [comment]
Hola Alberto,

Sobre lo que es el *endianness*, es simplemente el orden en que se agrupan *bytes* cuando se codifica algún valor. Por ejemplo, al ejecutar `(1).to_bytes(4, 'big')` lo que haces es codificar el valor del entero `1` utilizando 4 *bytes* en el orden *big endian*, lo cual resulta en `b'\x00\x00\x00\x01'`. Pero si ejecutas lo mismo cambiando el orden: `(1).to_bytes(4, 'little')`, obtienes los mismos bytes, pero en orden inverso: `b'\x01\x00\x00\x00'`.

Ahora, sobre el valor de 300 en *little endian*. ¿Estás seguro que no corresponde? 

El valor que sale  en enunciado es `b'\x2c\x01\x00\x00'`, pero si ejecutas `print((300).to_bytes(4, 'little'))` probablemente **veas** `b',\x01\x00\x00'`. ¿Son distintos valores?

Recuerda que hay *bytes* que tienen una correspondencia a un caracter siguiendo ASCII, y al ejecutar `print` Python prefiere imprimir un *byte* en su equivalente ASCII en vez de su equivalente hexadecimal. Y, el correspondiente valor es ASCII para `\x2c` es la coma (`,`).

Puedes verificar lo anterior de varias formas:
- `b'\x2c\x01\x00\x00' == b',\x01\x00\x00' ` retorna `True`.
- `ord(',')` y `ord('\x2c')` ambos retornan `44` que es el valor entero correspondiente al *byte*.
- `hex(44)` retorna `'0x2c'`, mostrando que es el mismo valor hexadecimal de 44.

Espero se entienda, cualquier cosa me dices.

Saludos.

**Comment by anvaldes** [comment]
Muchas gracias!!
