### ISSUE TITLE
Simulación de distintas unidades de tiempo (minuto, día, mes)

### ISSUE THREAD

**Issue by vixolo** [IIC2233/Syllabus#538]
Esta issue está relacionada con la #515 .

Leyendo el enunciado queda claro que para varias de las cosas a hacer, es necesario saber en qué día o mes se está, o al menos llevar un contador de días y meses. Hasta el momento estoy usando como unidad de tiempo de simulación el minuto, pero uso dos whiles anteriores para ir ubicando en qué día o mes estoy, más o menos de la siguiente forma:

```
    def run(self):
        while self.tiempo_simulacion_meses < self.tiempo_maximo_meses:
            self.tiempo_simulacion_dias = 0
            while self.tiempo_simulacion_dias < self.tiempo_maximo_dias:
                self.tiempo_simulacion_minutos = 0
                while self.tiempo_simulacion_minutos < self.tiempo_maximo_minutos:
                    self.SIMULACION_DES_PROPIAMENTE TAL
                self.tiempo_simulacion_dias += 1
            self.tiempo_simulacion_meses += 1
```

Los minutos (que son el tiempo que comanda todo) solamente son avanzados usando el método DES, obteniendo el mínimo entre los tiempos de los siguientes eventos. ¿Se puede hacer esto o es ilegal?

Muchas gracias

**Comment by TomasSalvadores** [comment]
Tal y como tu das a entender al decir que solo una parte es DES propiamente tal, tu simulación como un todo no lo es. Con tu código operas de una forma periódica, revisando obligatoriamente cada día de cada mes, siendo que pueda que en ese día no ocurra nada. Esto es propio de simulación síncrona, por lo que esta mal.
Pero sí sabemos que todos los meses pasa algo, ¿o sea que puedes quitar un nivel de profundidad a tus whiles y revisar cada mes? Esto sigue sin estar del todo bien, pues el concepto de DES que que tu estes constantemente saltando los tiempos muertos sin detenerte entremedio, es una búsqueda constante del siguiente suceso, pero al detenerte periodicamente entre meses estas actuando de forma independiente a los sucesos, de forma Síncrona.
Claro que tu approach podría ser efectivo e interesante, pero lamentablemente no es lo que se busca en esta tarea.
Tendrás que idear una forma de lograr hacer saltos temporales en tu unidad básica sin perder la ubicación temporal macroscópica de tu tarea.

Espero que te sea útil!
Salu2

**Comment by vixolo** [comment]
Muchas gracias! Me quedó claro lo que no puedo hacer y buscaré una mejor forma. Saludos

**Comment by JPSF** [comment]
@TomasSalvadores  ¿Pero podría considerarse el comienzo o término de un día como un evento o no?

**Comment by TomasSalvadores** [comment]
1. Como di a entender arriba, no. Pues estarias actuando de forma sincrona.

2. Claro que si a ambas preguntas. Un evento no programado es un evento. Y toda la gracia de DES es que si no pasa algo en un período de tiempo, te lo saltes completamente. Esta es la razón de porque el termino del dia no puede ser un evento, no hay nada que ocurra todos los dias a las 24 hrs.
