### ISSUE TITLE
Tiempo Simulación

### ISSUE THREAD

**Issue by Pipelao** [IIC2233/Syllabus#538]
Hola!
Tengo una pregunta acerca del tiempo de simulación. Según la introducción se quiere que se simule el parque durante una semana pero los eventos externos dicen por ejemplo lunes por medio (en el caso de ruziland) o día colegio en el que se menciona que cada día sábado hay 50% de probabilidad de que ocurra.
De ante mano, gracias.

**Comment by pcseisdedos** [comment]
En la sala de ayuda aclararon que podíamos interpretar lo del lunes por medio como un 50% de los lunes, es decir, como Ruziland invade con un 25% de probabilidad lunes por medio se calcula como que la probabilidad que ocurra un lunes de la simulación es de 12.5% y como solo se simula una semana no hay problema con que dos lunes seguidos ocurra el evento

**Comment by Pipelao** [comment]
Ahh perfecto, entonces para día colegio también sería un 12.5% de probabilidad que ocurra un día sábado?

**Comment by pcseisdedos** [comment]
Mmm según yo para el sábado sería 50%, el tema del lunes es que no pasa todos los lunes, sino lunes por medio, por eso se divide la probabilidad en dos, porque es como que fuera 50% del 25%, en cambio el sábado dice que son todos los sábados, no sábado por medio

**Comment by Pipelao** [comment]
Ya entendí, muchas gracias @pcseisdedos y @Hernan4444 :)
