### ISSUE TITLE
Pep 8 y f-strings

### ISSUE THREAD

**Issue by tsunayoshi21** [IIC2233/syllabus#538]
Hola!
Durante mi código, en varías parte ocupo las f-strings por que me son muy útiles, sin embargo, debido a usarlas muchas lineas superan los 100 caracteres y no se como se hace con las f - strings para cortarlas y ocupar menos caracteres por linea, ya que el operador \ no sirve en este caso como en los prints normales.

**Comment by vicentevegaulloa** [comment]
Hola @tsunayoshi21 !

Podrías usar parentesis de esta forma:

`msg = (
         f'Hola este f string es demasiado largo. '
         f'por lo que lo acortaré de esta forma {variable_cualquiera}'
)`

Espero que te sirva! De todas formas [aquí](https://stackoverflow.com/questions/48881196/how-to-split-up-a-long-f-string-in-python) hay más formas de hacerlo según stackoverflow. Espero que te sirva 😄

**Comment by YehudaGurovich** [comment]
Si se puede utilizar \ en los f-strings en todo caso.

**Comment by vicentevegaulloa** [comment]
Sii eso aparece igual en el link que adjunté
