### ISSUE TITLE
Duda sobre manipulación de estructuras de datos

### ISSUE THREAD

**Issue by mVal919** [IIC2233/Syllabus#538]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, muy buenas tardes.
Esta pregunta no es específicamente sobre alguna función de la tarea, pero consideré es lo suficientemente atingente como para haberla puesto con el label de 'Tarea'.
Digamos que tenemos un generador X que se ve como (("a", 1) , ("a" , 5) , ("c" , 2) , ("b" , 3) , ("b" , 8)) , y yo quiero, de alguna forma, sumar los valores del segundo elemento de la estructura con respecto al primero, tal que, o X se actualice o se cree un segundo generador,  y quede algo como (("a" , 6) , ("c" , 2) , ("b" , 11)). Estuve mirando en las funciones que están en los módulos/librerías permitidas, y no se me ocurre como usar las que están disponibles para este fin.
Mi primera idea había sido utilizar un for y tee(X, n) para cada elemento primario distinto, pero tampoco se me ocurre como implementar eso sin que sea una cosa que itere muchas veces por el generador.
Eso, no se me ocurre mucho como implementar esto, y dado el uso de product() durante la tarea, creo que de las 8 funciones que me quedan por terminar, algo como 6 o 5 se podrían terminar de resolver con eso.

**Comment by mVal919** [comment]
Okay
Lo probé con tee, y efectivamente se demora mucho. Para los archivos de tamaño S y M van bien, pero los otros no corren en los 30 segundos.

**Comment by MaxAl100** [comment]
Hola! Esto se puede solucionar mediante un código con reduce, donde reduces a una lista mínima del primer aspecto de las tuplas. Se puede ver como el siguiente ejemplo:
``reduce(
    lambda acc, x: acc.update({x[0]: acc.get(x[0], 0) + x[1]}) or acc, X, {}``
Este código revisa si existe el primer parámetro de la tupla a buscar en el diccionario que va creando y si existe, suma el valor al actual (``acc, x: acc.update({x[0]: acc.get(x[0], 0) + x[1]})``) y en caso contrario crea un nuevo valor al diccionario (``acc, X, {}``). 
Esta función te retornará un diccionario y no un generador (o tupla o lista), por lo que si lo quieres manejar como alguna de estas opciones debes manejar este output  o cambiar el código que te he entregado.

Recuerda que las variables en tu tarea deben ser descriptivas! Por favor avísame si te queda claro escríbeme y si no, te lo puedo seguir explicando :)

**Comment by mVal919** [comment]
En este caso, el codigo retornaría un diccionario como {"a":6, "c":2, "b":11}? (Usando el ejemplo anterior)
Después no debería ser tan complicado (creo) convertir eso a una tupla o una lista con los pares (key, value)

Lo que si, viendo el código no veo donde poner la lista/generador, ni el valor inicial. Me imagino que se pondrían después del lambda del primer código (igual que con un reduce regular?)
Muchísimas gracias igual.

**Comment by mVal919** [comment]
Okay.
Implementé el código y funciona de maravilla, así que muchísimas gracias, porque no creo que se me habría ocurrido algo así en mil años.
Sin embargo, se me sigue pasando el tiempo, así que no es esa parte de la implementación la que estaba dando problemas. Pero igual me sirve, considerando que puedo reusar el código para los otros ejercicios.
