### ISSUE TITLE
Duda sobre Grafos

### ISSUE THREAD

**Issue by isidoragutierrez** [IIC2233/Syllabus#538]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola! Tengo una duda respecto a la materia de grafos. 
¿Podría pasar que un nodo se auto-relacione consigo mismo? Es decir, que tenga una flecha (arista) que salga de sí y vuelva entrar a él mismo? 
En el caso de que no pueda pasar lo anterior, entonces en la representación como matriz de adyacencia, la diagonal siempre estará compuesta de ceros?

Gracias de antemano!

**Comment by mskdancers** [comment]
Hola! Si podría pasar, y se llama [loop](https://es.wikipedia.org/wiki/Bucle_(teoría_de_grafos)). Si es que te especificaran que el grafo no contiene _loops_, entonces, como dices tú, la diagonal de la matriz de adyacencia estaría compuesta por ceros. 

Saludos!

**Comment by isidoragutierrez** [comment]
Perfecto! Muchas gracias!!
