### ISSUE TITLE
Formato al escribir Alimentos

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#538]
Hola! Los alimentos deben ser escritos como sea, tipo mayúscula o minúscula? O deben seguir el formato presentado?

**Comment by JosefaPaz** [comment]
Hola @CataSudo !

Dado que solo existen los alimentos que se muestran en el enunciado y no se pueden "crear" nuevos alimentos, no es significativo si siguen el formato presentado o están escritos con combinaciones de mayúscula / minúscula, por lo que si tu programa los lee adecuadamente no habría problema. **Aún así, por un tema de consistencia** con los archivos que te entregamos, te recomiendo seguir el formato presentado.

Éxito en la tarea! 😸
