### ISSUE TITLE
Duda staticmethod en ejemplo Japonizador servidor

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#539]
Hola porque se ocupo staticmethod en esta parte del ejemplo?
![image](https://user-images.githubusercontent.com/48482216/69574059-0caeee00-0fa6-11ea-8b3f-bde926c42e00.png)

Gracias de antemano

**Comment by StroveLight** [comment]
Hola!

El staticmethod se en las clases cuando no se necesita pasarle el ```self``` como argumento implicito. Equivale a una funcion, pero que solo se puede llamar desde la clase (usando ```self.funcion()```). Un equivalente sin el decorador dentro de la clase sería:
```python
# Se comenta el @staticmethod
def send(self, mensaje, socket):
    # El resto de la funcion
```
El staticmethod sirve para dejar una funcion que no necesita la clase, pero que lógicamente si la necesita (En este caso se le pasa el socket, y lo usan algunos threads que parten desde la funcion de la clase, no lo necesitan otros elementos del servidor al no tener sockets). 

Realmente puedes usar el equivalente si deseas, no te perderás nada. Este decorador es principalmente para organizar un poco mas las funciones de la clase al indicar que no se usa el self adentro

[Mas informacion en stackoverflow](https://stackoverflow.com/questions/136097/what-is-the-difference-between-staticmethod-and-classmethod)

Espero que esto te haya servido (・∀・)

**Comment by JuaniAndres** [comment]
gracias
