### ISSUE TITLE
Superar límite de líneas archivos empaquetados

### ISSUE THREAD

**Issue by ljgonzalez1** [IIC2233/syllabus#539]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
[~] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía. *Encontré una relacionada pero no similar.*
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Había puesto imágenes en QtDesigner y me generó un archivo llamado assets.qrc. Corrí un comando para empaquetar las imágenes pero resulta tener del orden de 365 000 líneas. Dado que es un archivo comprimido, **¿se puede hacer una excepción con el límite de líneas para este archivo?** No quiero gastar tiempo y espacio en asignar todos los QPixmaps y QLabels siendo que el programa ya me permite hacerlo con facilidad.

**Comment by Juampisaez** [comment]
Hola @ljgonzalez1 
Probablemente es porque las imagenes en Qt las estas instanciando en pixmap como resources. La solucion es darle la direccion de la imagen. En esta issue se dio una posible solución para esto [#493](https://github.com/IIC2233/syllabus/issues/493). Asi no es necesario ocupar esos archivos .qrc que te creo Qt.

Espero te sirva de ayuda, cualquier cosa quedo atento :)

**Comment by ljgonzalez1** [comment]
Me habría acomodado más usar resources, sobre todo porque ya estaba hecho. Pero bueno usaré paths relativos.
Mucha gracias
