### ISSUE TITLE
Criaturas escapadas y uso de habilidad especial al pasar dia

### ISSUE THREAD

**Issue by drosselot** [IIC2233/syllabus#539]
Hola, si una criatura ha escapado y el magizoologo pasa al dia siguiente, siguen haciendo sus cosas normalmente? Me refiero a los de que el Augurey traiga alimento, el niffler robe sickles y el erkling se coma la comida.

**Comment by aljara97** [comment]
Hola @drosselot 

El uso de habilidades especiales de las criaturas no dependen del hecho si está en cautiverio o no. Por ejemplo, el Augurey traerá alimento si **no tiene hambre, no está enfermo y tiene todos sus puntos de salud**. Por tanto, en el caso de que una criatura escapó y cumpliera estas condiciones simultáneamente, ocurrirá el evento correspondiente.

Espero haber aclarado tu duda 🧙

**Comment by drosselot** [comment]
Vale, gracias
