### ISSUE TITLE
Cardinalidad diagrama

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#539]
Hola!! Acabo de ver el feedback del avance y me dijeron que tenía que poner la cardinalidad, pero del enunciado yo entendí que no había que poner ni cardinalidad ni visibilidad de métodos y atributos 🤔 Así que ahora estoy confundida jajajaaj
¿Hay que poner cardinalidad y visibilidad o no?

**Comment by furcelay** [comment]
Hola @denisseleiva !
Como dice el enunciado no es necesario indicar la cardinalidad ni la privacidad de los métodos/atributos. Es probable que quien revisó tu avance lo dijo como comentario. En todo caso si los incluyes nunca están de más...
Saludos!

**Comment by denisseleiva** [comment]
Bacan, gracias!! @furcelay
