### ISSUE TITLE
keyPressEvent

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#539]
Hola!
He intentado mover mi campeon con las teclas, para eso ocupo la funcion _keyPressEvent(self, event)_ y resulta que no reconoce el teclado. Probé poniendo algo como:
 _if event.key() == _Qt.Key_Q:
         print("Apreté una Q)_
Para que se imprima en consola y nada, ya que no imprime nada en consola.  ¿Alguien me puede explicar que está pasando?  ¿Qué puedo hacer para arreglar mi problema (mi pregunta va a qué hacer para que me pesque el teclado, no qué hacer para que el campeón camine, es decir, dado mi ejemplo, como podría imprimir "Apreté una Q")?
p.d = Ya googlié el tema y no sé que está mal. 
Saludos! :B

**Comment by arturodelreal** [comment]
Hola
De que hereda la clase en la que estas definiendo tu keyPressEvent?

**Comment by sebacruzd** [comment]
Hola,

Has intentado con el event.text()? Recuerdo haber usado eso. Aparte, si haces print(event.key()) que te aparece?

Saludos!

**Comment by acrojas2** [comment]
@sebacruzd Hice print(event.key()) y no imprime nada en consola y no he probado con event.text().
@arturodelreal por lo que he entendido y sale en las documentaciones keyPressEvent es un método de la clase QEventClass.
AYUDA!
Saludos!

**Comment by sebacruzd** [comment]
Pruébalo entonces :)
Arturo se refería a la clase en la que estás usando el método. Esa clase de qué hereda? Por ejemplo QMainWindow

**Comment by iqacevedo** [comment]
@acrojas2 estas sacando `Qt` del modulo `QtCore` verdad?, ya que ahi estan las `Qt.Key`, por ejemplo, `QtCore.Qt.Key_Q`.

Saludos!

**Comment by acrojas2** [comment]
@sebacruzd ya lo probé y nada :(
@iqacevedo si, saco el Qt del modulo QtCore ... Hago prints y no me imprime nada entonces no sé qué estará fallando. Incluso llegué a hacer lo siguiente:
_def keyPressEvent(self, event):
--->print(event.key())_
Para probar si reconoce el teclado (según yo, lo anterior me debería imprimir el numero que representa la tecla presionada).
No sé con qué mas probar.
Saludos!

**Comment by acrojas2** [comment]
@arturodelreal Creo que de QWidget
<img width="777" alt="captura de pantalla 2017-05-29 a las 11 40 33 a m" src="https://cloud.githubusercontent.com/assets/26121354/26555584/b05cf1c0-4463-11e7-8f72-1091dab9f9d7.png">
Nosé como ver eso en la documentación :( 
Saludos!

**Comment by acrojas2** [comment]
@arturodelreal de QWidget :)

**Comment by sebacruzd** [comment]
Y dónde estás definiendo el método?
Debería ser definido en la ventana principal, no en el campeón o en otra parte.

**Comment by acrojas2** [comment]
@sebacruzd Estaba definido en el Widget del del juego,revisando más la documentación me di cuenta que me faltaba poner el setFocusPolicy...
Gracias a todos! :)
