### ISSUE TITLE
Todos los miembros uc llegan al campus todos los días?

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#539]
Estoy teniendo algunos problemas con esta parte de la tarea. Como el máximo de esta distribucion es 240 minutos y la simulación corre entre 11:00 y 15:00 todos los días, es decir, durante 240 minutos, entonces TODOS los miembros uc llegan al campus todos los días? Si es así, me pasa que se vuelve muy lenta la simulación. Debido a que  la distribución triangular nos entrega el minuto exacto en que llegará un miembro uc al campus, entonces al generar el primer tiempo de llegada, el siguiente no puede ser menor a este, por lo que para generar el tiempo de la sgte llegada hay que hacer un while hasta obtener un valor mayor o igual al tiempo actual. Al principio es rapido, pero cuando ya son las 14:59 y aún faltan 100 miembros uc que lleguen, el while demora mucho en generar un valor mayor o igual a 14:59, y esto repetirlo 100 veces.
Se entiende a lo que me refiero?

**Comment by cilopez** [comment]
¿Es decir estas forzando en tu simulación que lleguen en 1 minuto 100 alumnos, ya que no te calzan las probabilidades?(_te entendí?_)

**Comment by bedefrunner** [comment]
Exacto! Como la distribución me obliga a mantener una moda de 30, es dificil que genere valores mayores o iguales a 14:59, lo cual ocurre en caso de que el tiempo actual sea 14:59 debido a que algun miembro llego a esa hora.

**Comment by bedefrunner** [comment]
Otra alternativa sería cambiar mi código de esta manera: 
Lo que tengo ahora es:
`while True:
            proximo_en_llegar = numpy.random.triangular(left=0, mode=self.moda_llegada_campus, right=240)
            if proximo_en_llegar >= self.tiempo_actual:
                self.proximo_miembro_llega = proximo_en_llegar
                break`

La opción sería cambiar el kwarg `left` de la distribucion por `left=self.tiempo_actual`, de tal forma de evitar que genere valores menores al tiempo actual, pero siento que estoy cambiando la distribución y eso no sería correcto.
(no se por que no se indenta bien el codigo en el comentario, pero creo q se entiende igual)

**Comment by bedefrunner** [comment]
No, mala idea. En el momento en que left se haga mayor a mode, tirará error. Ahora si que no se que hacer.

**Comment by bedefrunner** [comment]
Lo único que se me ocurre sería generar, a priori, los tiempos de llegada de cada miembro al empezar cada día. Luego, ordenarlos de menor a mayor e ir escogiendo el proximo evento que corresponda, pero según yo no es la idea de esta parte del programa.

**Comment by cilopez** [comment]
Mira @bedefrunner existe dos opciones: 
- Una que cuando te queden 20 minutos, fuerzes los integrantes nomás que entren de  alguna forma aleatoria que no te gaste tantas iteraciones

- Ajustar un poquito los parametros para que te calze (_los ayudantes aveces no somos muy precisos en los datos entregados_)

Cualquiera de las soluciones que realices señalala en tu _readme_ y mencionas esta _issue_ , saludos!

**Comment by bedefrunner** [comment]
OK! Pero no entendí bien la parte de ajustar los parámetros. Qué parámetros? Para que calce qué?

**Comment by bedefrunner** [comment]
Perfecto, gracias!

**Comment by simontoya** [comment]
Me quedó una duda respecto a esto,es mejor práctica que cada Miembro Uc tenga su propia hora de llegada y lo recalcule todos los dias(como atributo) ?

**Comment by iqacevedo** [comment]
Hola,
Tiene que ver con la moderación, piensa que la llegada del miembroUc es un evento, como es una DES efectivamente tendrías que calcular cuándo es el próximo tiempo de ocurrencia del evento, ¿Cuando lo calculas ? Cuando el evento se produce :)

Saludos !

**Comment by simontoya** [comment]
Osea que estaría bien si cada miembro uc tuviera un horario asignado y a partir de ese parámetro ordenar la llegada y así saber cual es la siguiente persona que llegará?
