### ISSUE TITLE
Duda sobre los archivos que se incluyen en el gitignore y su implicancia en la ejecución del código. (Considerando que no es evaluado)

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#54]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo una duda sobre `.gitignore`, que aunque sé que no es necesario en esta tarea quiero usarlo para agarrar práctica. ¿El `.gitignore` debe incluir enunciado, `usuarios.csv`, `contactos.csv`, `grupos.csv` y `mensajes.csv`? (no lo entendí bien en el enunciado).

Tomando en cuenta lo anterior, ¿debemos asumir que una vez que los ayudantes hagan `git pull` a nuestro repositorio los archivos `*.py` deberán correr con los archivos `*.csv` que ellos tengan en sus computadores?

Espero que me haya dado a entender bien 😢.

**Comment by matiasmasjuan** [comment]
Hola @Rerro-r!

En primer lugar, me parece muy bien que intentes agregar el archivo ```.gitignore``` en esta tarea debido a que se evaluará en las futuras entregas.
Tal como mencionas, el ```.gitignore``` debe incluir **todos** los archivos de la sección **Archivos** del enunciado, es decir: ```usuarios.csv```, ```contactos.csv```, ```grupos.csv```, ```mensajes.csv``` y ```parametros.py```. Al momento de corregir sus tareas, utilizaremos los mismos archivos que se encuentran en la carpeta de la **T0** en el repositorio del **Syllabus**. Por lo tanto, es de esperar que su programa funcione con los mismo archivos entregados.

Espero haber respondido a tu pregunta y mucho éxito con la tarea! :smile:
