### ISSUE TITLE
Duda sobre uso de pep8 en namedtuples

### ISSUE THREAD

**Issue by dfloreaa** [IIC2233/syllabus#54]
Una consulta, en general, según pep8 hay que usar CamelCase para nombrar clases, me preguntaba si aplica lo mismo para nombrar namedtuples, dado que se comportan tan similar. Gracias ☺

**Comment by Christian-Klempau** [comment]
¡Hola @dfloreaa!
Al ser un caso particular, donde uno se refiere a las Namedtuples de manera similar a las *Classes*, en rigor siguiendo el espíritu de [PEP-8](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles) deberían ser definidas usando **CamelCase**. Aunque en el curso **no** descontaremos puntaje si no lo ocupas en Namedtuples, te recomiendo fuertemente que **sí** lo ocupes, ya que se considera una buena práctica en general, porque mantiene el código más legible para ti y para el corrector. Por lo general puedes guiarte por la [guía de estilo](https://github.com/IIC2233/contenidos/blob/master/semana-00/1-gu%C3%ADa-de-estilo.ipynb) en cualquier caso.
Suerte!

**Comment by dfloreaa** [comment]
Lo tendre en cuenta para trabajar con casos parecidos entonces, muchas gracias 😊
