### ISSUE TITLE
**kwargs

### ISSUE THREAD

**Issue by santiago3c** [IIC2233/Syllabus#54]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

Agradecería si me pueden explicar cómo funciona los **kwargs en el primer código, porque en el segundo que adjunto no está haciendo algo parecido (lo de extraer como parámetro si tiene el mismo nombre en el diccionario y además de eliminarlo de este)
![Captura de pantalla (164)](https://github.com/IIC2233/Syllabus/assets/142272696/34725c3c-f36e-41ac-b1f6-ae3fcfb103ee)
![Captura de pantalla (165)](https://github.com/IIC2233/Syllabus/assets/142272696/b9b0eddd-5fb1-44f0-b317-3bc4c346a14b)

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Juampisaez** [comment]
Holaa @santiago3c 👋🏼

Por lo que estoy entendiendo del error que te retorna la consola, la función persona no tiene el atributo/variable _apellido_ definida en el input de esta, y estas definiendo `persona(**dic)`. En resumen, al llamar la funcion como lo haces, se queda buscando el atributo _apellido_ y no lo encuentra.

Distinto seria si la función estuviera definida como `def persona(**datos):`. De esa forma, basta con llamar a la funcion como `persona(dic)`.

Tal vez el siguiente [link](https://www.geeksforgeeks.org/args-kwargs-python/) te puede ayudar a entender mejor lo que está pasando.

Quedo atento cualquier cosa
Saludos,

**Comment by santiago3c** [comment]
muy claro, muchas gracias
