### ISSUE TITLE
Aclaración dudas enunciado

### ISSUE THREAD

**Issue by stephichau** [IIC2233/Syllabus#54]
1. Combinaciones posibles de mercados: Cada mercado puede tener dos divisas siempre y cuando no sean iguales (no necesariamente XXXDCC o DCCXXX).

2. Entrega de dinero: Al momento de registrarse como _Trader_ , el usuario recibe 100.000 DCC. Luego, por cada mercado, recibe 50.000 de **ambas** monedas.

3. Las divisas que les entregamos en el archivo _currencies.csv_ son sólo de ejemplo; Su programa debe soportar cualquier nombre y cualquier cantidad.

4. La comisión cobrada por el mercado/DCC Capital pueden asumir que "desaparece".

**Comment by Bneya** [comment]
¿Entonces el programa necesita aguantar n divisas diferentes y todas sus combinaciones posibles?

¿Entrar al mercado RUPBAN y BANRUP me da en total 100.000 monedas de cada una o solo 50.000 contando solo la primera entrada (ya que técnicamente son mercados diferentes)?

**Comment by FernandoPieressa** [comment]
Si, su programa debe poder aguantar una cantidad n de divisas diferentes y sus combinaciones para los mercados. No olvidar que no puede suceder un mercado de una divisa repetida DCCDCC por ejemplo.

Solo 100.000 de DCC cuando se registran por primera vez, luego 50.000 de cada una de las 2 del mercado al que se une.

Saludos!

**Comment by nmaturana97** [comment]
No entiendo muy bien como van a probar nuestros programas. ¿Pondran distintas divisas con las mismas columnas que currencies.csv para ver si se generan los mercados correspontiendes?

**Comment by FernandoPieressa** [comment]
Su programa debe ser capaz de leer los csv con el formato entregado y a partir de ese archivo generar las currencies y mercados correspondientes sin importar la cantidad o nombres entregados. (No pueden hacer que funcione solamente para las divisas del ejemplo porque en la corrección estas pueden cambiar)

**Comment by movaldivia** [comment]
Perdón pero no me quedó claro AAABBB es el mismo mercado que BBBAAA?

**Comment by naazocar** [comment]
@movaldivia Según entiendo en el mercado AAABBB se venden monedas AAA a precio en BBB, mientras en el BBBAAA se venden monedas BBB a precio en AAA

**Comment by Bneya** [comment]
Si me registro en el mercado AAABBB, me dan 50.000 AAA y 50.000 BBB, luego si me registro en el mercado AAACCC, me darían otros 50.000 AAA y los primeros 50.000 CCC. Entonces significa que quedaría con 100.000 AAA, 50.000 BBB y 50.000 CCC, ¿esto está bien?

**Comment by jpgonzalez4** [comment]
Para la corrección se va a usar un archivo con el mismo nombre "Currencies.csv" con los nombres y símbolos?

**Comment by andreslyon** [comment]
la comision cobrada al mandar "plata" a algun usuario tambien desaparece?

**Comment by fabarros** [comment]
Entonces DCC es otra simple divisa común y silvestre al igual que las otras "n" divisas del programa. Mercantílmente funciona igual que las demás sólo que estas en particular sirven para pasar de Clase Trader a Investor. Un ayudante en el patio me comentó que DCC son una moneda de cambio similar a lo que se conoce como "Bit Coins", pero en verdad eso no es correcto. Sería bueno que se aclare eso.

**Comment by tavalenzuelag** [comment]
Pero si es que cada usuario se registra en un mercado en específico, asumiendo por ejemplo que el mercado es AAABBB,  que me regalen 100000 DCC no me serviría de nada en ese mercado en específico? asumiendo eso, a la hora de consultar el saldo, debería retornar el saldo de las dos monedas del mercado en el que estoy o el de todas las monedas de los mercados en los que estoy registrado?.

**Comment by iqacevedo** [comment]
Hola!

1-. @movaldivia es tal como dice @naazocar, es decir el mercado AAABBB si es distinto a BBBAAA porque en cada mercado se transa una moneda al precio de la otra.
2-. @Bneya así es ! 
3-. @jpgonzalez4 si el archivo tendrá el mismo nombre, pero debes considerar que la información del archivo si puede cambiar (siempre manteniendo el mismo formato).
4-. @andreslyon si, desaparece también ! 
5-. @tavalenzuelag a la hora de consultar el saldo debes retornar la cantidad de monedas que tiene de cada divisa, además deberás transformar cada moneda a DCC y retornar el total del usuario en esta moneda, por lo que respondiendo a  @fabarros, DCC si es una divisa común salvo lo que dices tú, y que a la hora de calcular el saldo debes pasar todas tus monedas a DDC y mostrar el total.

Saludos !

**Comment by rihanuch** [comment]
Como se calcula el total en DCC?

**Comment by nachocontreras** [comment]
Por ejemplo:
50000 RUP
60000 BAN
150000 DCC
Entonces, si quiero vender BAN, debo ver que la cantidad no supere los 60000?
Y al mostrar el saldo, debo mostrar 260000 DCC?

**Comment by rihanuch** [comment]
@nachocontreras segun yo nica el cambio es 1-1, sino no tendria sentido tener el mercado 🤷🏽‍♂️

**Comment by nachocontreras** [comment]
@rihanuch cuanto podria ser?

**Comment by depstein26** [comment]
Como defino el valor de una currency? Debería haber un precio al que pueda llevar todas las monedas o no? O saber el cambio a DCC para poder tener un saldo por cada usuario, no sé si queda clara la duda. Gracias

**Comment by iqacevedo** [comment]
Hola a todos!
En el enunciado sale lo siguiente:
![image](https://user-images.githubusercontent.com/13748732/29497983-27a69924-85c9-11e7-8a32-5ec862618139.png)

Entonces, para saber el precio de la moneda AAA en DCC deben ver el valor al cual se transo el último match en el mercado AAADCC.

Saludos!

**Comment by mebruna** [comment]
@iqacevedo Y si aun no ha ocurrido un match en el mercado AAADCC? Se hace el cambio 1:1?

**Comment by iqacevedo** [comment]
@mebruna eso no esta especificado así que pueden escoger entre estas 3 opciones:

1-.Esa moneda en particular no la incluyan en el total de DCC, pero si indican que no hay información en los mercados para pasarla a DCC.
2-. Usar 1:1 como dices 
3-. Otra forma de abordar esto especificandolo en el README.

Saludos !
