### ISSUE TITLE
cargar partida

### ISSUE THREAD

**Issue by cotefon** [IIC2233/syllabus#54]
Hola! en la carpeta partidas, ¿tiene que existir la posibilidad de guardar más de una partida y tener la opción de cargar cualquiera de ellas o solo basta con poder guardar y cargar 1?

**Comment by KnowYourselves** [comment]
Hola @cotefon!

Se debe poder guardar una cantidad arbitraria de partidas en la carpeta `partidas` y se debe poder cargar cualquiera de estas.

Éxito!

**Comment by cotefon** [comment]
gracias!
