### ISSUE TITLE
Nombres de usuarios con números

### ISSUE THREAD

**Issue by NatC18** [IIC2233/Syllabus#54]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el punto 4.1 del enunciado se indica que la opción "Registrarse" solicita un nombre de usuario que debe tener un mínimo de caracteres alfabéticos, sin embargo en el archivo hay usuarios con números en el nombre. ¿Con el mínimo de caracteres alfabéticos se refiere a que el nombre debe tener al menos esa cantidad específica y además puede tener números o que no puede tener números y hay que filtrar el archivo de usuarios?

Muchas gracias!

**Comment by benjaaguila** [comment]
Hola @NatC18 ! Efectivamente en el archivo `usuarios.csv` hay un usuario con números que en teoría no debería estar ahí. Lo que se acordó es que los usuarios en el archivo deben ser considerados(**no filtrarlos**). Sin embargo, para la creación de los **nuevos usuarios** se debe verificar que tengan ese mínimo de caracteres alfabéticos (**solo letras**).

Espero que haya respondido tu pregunta, saludos!

**Comment by NatC18** [comment]
Perfecto! Muchas graciaas
