### ISSUE TITLE
duda editores de texto

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2233/syllabus#54]
Hola, tengo una duda respecto a las instrucciones, tanto de la tarea como los de la clase 0.
Hay muchas instrucciones respecto a los editores de texto. Mi duda es si se refiere al IDLE de python o a los programas que usamos para editar los archivos de texto como el block de notas en mi caso

**Comment by Dnpoblete** [comment]
Hola @vice-rosas99, se refieren a los programas para editar código, que en el caso del ramo serían VSC y Sublime. Para más info te recomiendo revisar la wiki y/o videos tutoriales del curso.

https://iic2233.github.io/wiki/

Éxito con la tarea 😄

**Comment by vice-rosas99** [comment]
ok muchas gracias

**Comment by Dnpoblete** [comment]
De nada 😸
