### ISSUE TITLE
Duda sobre la carpeta partidas y el archivo puntajes.txt

### ISSUE THREAD

**Issue by gabo1243** [IIC2233/Syllabus#54]
Hola, con respecto a la carpeta partidas y el archivo puntajes.txt, a medida que voy probando mi código estos se van llenando. Sobre esto, cuando lo subo a github:  ¿debo subirlos con todos los registros? o ¿debo subir la carpeta y archivo vacíos?
Gracias de antemano

**Comment by drcid98** [comment]
Hola! no deberías subir ningún archivo generado mientras pruebas tu código. Te recomiendo, tal como aparece en el enunciado, utilizar el archivo .gitignore (no que será evaluado en esta tarea) para poder practicar su uso para las tareas siguientes. Este archivo es abstante útil para no subir archivos generados como los que mencionas.
Saludos!
