### ISSUE TITLE
Duda con regla 3

### ISSUE THREAD

**Issue by ggmirandac** [IIC2233/Syllabus#54]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, tengo una duda con la regla 3.

La regla 3 dice lo siguiente:
Las celdas con números no pueden estar tapadas, es decir, no puede haber una tortuga y una
bomba en la misma celda.

Pero no me queda claro como sería el caso en el que ocurriera esto, es decir, que haya una tortuga y una bomba en la misma casilla.

Saludos,

**Comment by jtagle2** [comment]
Hola! Esta regla es relevante al momento de intentar solucionar el tablero. Como deberás probar distintas posiciones de poner tortugas, tienes que considerar que no puedes poner una tortuga en una celda con bomba para solucionarlo.

**Comment by Martoxp** [comment]
Hola buenas, la respuesta a la pregunta de mi compañero no me queda clara
Ya que, si bien, es entendible que no podemos poner una tortuga en una celda con bomba, la opción 3 del menu de acciones nos pide verificar si se cumple la regla 3, y no queda claro como lo verifico
Si hay una Tortuga encima de una bomba habrá una lista o tupla con una T y un numero, o habrá un str que contenga la T y el numero
Pq se entiende que yo no puedo solucionar un tablero poniendo la tortuga en el numero, pero si me toca verificar un tablero, como me entregarían un tablero con fallo?

**Comment by Hernan4444** [comment]
Hola, 

Esa regla no es necesita verificar en la opción 3 (error de enunciado). Solo verificas las reglas 1, 2 y 4. Y la 5 si es que haces el bonus. No les pasaremos nunca un archivo con 2 elementos en la misma celda c:

Saludos c:
