### ISSUE TITLE
Error al correr detectar plagas

### ISSUE THREAD

**Issue by fgallard** [IIC2233/Syllabus#54]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Ya había corrido los test case antes y todo había funcionado. Ahora avancé sin tocar esa parte del código y simplemente dejó de funcionar bajo este código de error. Eliminé todo lo referente al os del código, y aún así tira un error de os. Intenté cambiando la ruta, y nada, pero lo más raro es que no he cambiado absolutamente nada.
<img width="1054" alt="Captura de pantalla 2024-08-16 a la(s) 20 17 54" src="https://github.com/user-attachments/assets/ad4ceac1-0425-4147-a09c-326179dbdd99">

**Comment by ignacio-sp** [comment]
Hola @fgallard, si el error aún persiste, podrías subir el código que has realizado hasta ahora a tu repositorio personal para poder evaluar que está ocasionando el problema? Con la imagen que proporcionas, está complicado identificar qué lo está causando :(

Estoy atento a cualquier respuesta!
