### ISSUE TITLE
Duda - Uso de Clases

### ISSUE THREAD

**Issue by anais-mv** [IIC2233/Syllabus#54]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! mi duda es cortita. Si no usamos clases en ningún momento de la tarea eso no debiese ser problema verdad? en el discord vi que preguntaron y el profesor dijo que en esta tarea no se está evaluando el uso de clases por lo que entiendo que si no las uso no hay descuento ni nada por el estilo, pero preferí preguntar por aquí para hacerlo más oficial.

**Comment by Emiliax16** [comment]
Hola @anais-mv ! es justamente lo que dijiste. En esta tarea el uso de clases es totalmente opcional, ya que no será evaluado. Saludos!

**Comment by anais-mv** [comment]
ok, gracias!
