### ISSUE TITLE
Duda cambio realizado durante la ejecución del programa

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#54]
En el punto 4.2.3 dice que los datos se deben ir actualizando por ejemplo si se agrega un nuevo incendio. ¿Estos datos se tienen que guardar en el archivo "incendios.csv" o puede ser , por ejemplo, en una lista de nuestro programa?

**Comment by stephichau** [comment]
Hola @movaldivia ! 
Por un tema de modelación, lo correcto es guardarlo en el mismo archivo .csv :)
