### ISSUE TITLE
¿Qué sucede con los datos de las Personas una vez que guardo?

### ISSUE THREAD

**Issue by bmurtagh01** [IIC2233/syllabus#54]
Cuando estoy jugando creo distintas Personas las cuales tienen un HP. ¿Éste HP es fijo desde que hago una instacia de la clase o se calcula cada vez que es atacado/dañado?

Pregunto ya que cada vez que guardo un juego, se guardan los int de cuantas personas habian de cada clase, por lo que esos atributos se verían perdidos...

**Comment by hbkim94** [comment]
Hola!

Puedes pensar que el HP se "resetea" cada vez que se carga una partida guardada (es decir, se asigna aleatoriamente de nuevo a cada unidad existente).

Espero haber resuelto tu duda! Saludos!

**Comment by DCCollao** [comment]
Hola! No cierres las issues una vez sea respondida tu duda, pues a alguien más podría servirle tu pregunta!
