### ISSUE TITLE
Metodo compress y "ÏDAT"

### ISSUE THREAD

**Issue by Deleon20** [IIC2233/syllabus#540]
Hola! Estaba haciendo el filtro dibujo y me surgieron dos dudas con el enunciado de PNG Y FILTROS. Mi primera duda es si para el chunk IDAT el tipo es "ÏDAT" o es un error de tipeo del enunciado. 
![image](https://user-images.githubusercontent.com/48283979/59557321-fe938500-8fa4-11e9-9db0-cacd7f16aba4.png)
Y mi segunda duda es sobre el método compress de zlib, al leer su documentación en Internet vi que habían varios tipos de compresión que se determinaban por el segundo argumento de la función. Todos estos tipos de compresión funcionan para comprimir información del IDAT y que después sea leída en formato PNG?

Gracias!

**Comment by StroveLight** [comment]
Hola! para el IDAT se trata de un error de tipeo, por ello no posee las comillas cerradas

Con respecto al segundo argumento del compress, [tal como dice la documentacion](https://docs.python.org/3/library/zlib.html#zlib.compress), es para determinar cuanto memoria ocupará el resultado, a costa del tiempo de ejecución.

Como prueba, utilicé [una imágen](https://github.com/IIC2233/Syllabus-2017-2/blob/master/Tareas/T06/Imagenes/Squirtle.png), y la comprimí con el segundo argumento como 0 y como 9. Como resultado, una imágen me quedó usando aproximadamente 80 veces menos memoria que la otra.

Aparentemente los ayudantes no responden los domingos, pero espero que esta información te sirva para avanzar hoy

**Comment by Deleon20** [comment]
Si ya lo pude hacer! Gracias por la ayuda!  Al final el método compress puede no llevar ningún numero y de igual manera funciona!
