### ISSUE TITLE
Nombres sprites personajes

### ISSUE THREAD

**Issue by mpbascunan** [IIC2233/syllabus#540]
En el archivo usuarios.json los personajes 'adventurer' no tienen la última 'r', aparecen como 'adventure', sin embargo, en los nombres de los sprites si aparecen con la 'r', por lo tanto, ¿podemos en este caso modificar el archivo usuarios.json para que calce con los nombres de los sprites?

**Comment by jeschuwirth** [comment]
Hola,

Las alcachofas atacan nuevamente #344, por ahora recomiendo cambiar el nombre de la carpeta de sprites, ya que cambias sólo 2 nombres de archivos en vez de muchas lineas del json. 

Es **muy** importante que avises en el readme como vas a solucionar el problema para que el ayudante pueda corregir la tarea sin problemas, probablemente se suba un archivo reparado al igual que la anterior, voy a recomentar la issue en ese caso :)

Suerte!

**Comment by mpbascunan** [comment]
Graciaas!

**Comment by jeschuwirth** [comment]
Se actualizó el archivo usuarios.json del syllabus :)

recomiendo usar la versión nueva del archivo, sea cual sea la decisión nunca esta de más ponerla en el readme.
