### ISSUE TITLE
No se me corre el __init__ de una ventana

### ISSUE THREAD

**Issue by ijmeza** [IIC2233/syllabus#540]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Cree una ventana con QtDesigner pero no se me muestra. Revisé si tenía el self.show() y sí lo tiene. Después de mucho caché que no se me estaba corriendo el __init__ de la clase y no sé por qué pasa esto y cómo puedo solucionarlo.

**Comment by mmunoz12** [comment]
Hola @ijmeza! Podrías hacer push a tu repositorio para ver en más detalle que esta pasando? 🤔

**Comment by ijmeza** [comment]
Listo

**Comment by ijmeza** [comment]
Ya subí el codigo al repositorio

**Comment by ijmeza** [comment]
Sé que no me corre el __init__ de la clase VentanaInicio porque puse un print ahí y no se está imprimiendo en consola

**Comment by mmunoz12** [comment]
Resulta que estabas llamando a la aplicación utilizando `if __name__ == "main"` en vez de `if __name__ == "__main__"` por lo tanto tu archivo main.py no ejecutaba las líneas dentro de este if. Parece un cambio muy chico pero Python no lo leerá de otra forma 😵. Además el nombre del archivo .ui debe ser exactamente el mismo que tienes en el path (fíjate que en parámetros lo tienes escrito de otra forma), de otra forma el código no encuentra el archivo y no lo abre. Espero que eso solucione tu problema, quedo atenta!

**Comment by ijmeza** [comment]
Lo solucioné
Era un error en el main Gracias de todas formas
