### ISSUE TITLE
Problemas de redondeo en función 

### ISSUE THREAD

**Issue by vitoco11** [IIC2233/Syllabus#540]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Para la función gasto_cliente_por_mes() me da solo un test malo de carga de datos (los de correctitud me dan buenos todos). El error sucede por la diferencia de un numero: 
![image](https://github.com/user-attachments/assets/f2bd3265-72c1-4159-9a70-e3118d07f611)
Asumo que es un error de redondeo, como ya ha pasado antes con otras funciones, pero el problema es que para esta función ocupo una función creada anteriormente, la de ganancias_producidas_en_los_pedidos(), para esta función también tuve errores con el redondeo pero los logre solucionar gracias a una issue y ahora todos los tests de carga_datos y correctitud dan buenos. Ahora, si para la función gasto_cliente_por_mes() tira un error por redondeo, significa que la función ganancias_producidas_en_los_pedidos() tiene un error de redondeo, ya que fuera de esta no se hacen cálculos matemáticos, pero esto no puede ser, ya que se pasaron todos los tests. Por eso mismo no se que hacer, el redondeo debería estar bien (multiplicando 1 - descuento al final por cada contenido_pedido), a menos que para la función actual se requiera otra forma de redondear que no se especifique.

**Comment by mane6867** [comment]
Hola! podrías hacer push a tu repo para saber mejor lo que está pasando?

**Comment by vitoco11** [comment]
Holaa, acabo de hacer push

**Comment by vitoco11** [comment]
Ya resolví mi problema, el problema estaba que en la primera función de 2 generadores(ganancias_producidas_en_los_pedidos) solo da correcto si por cada contenido de pedido se le aplica el descuento sobre el precio de la pizza y su cantidad correspondiente(cada contenido, no cada pedido) y después se redondea. Mientras que en la función gasto_cliente_por_mes, al momento de querer las ganancias generadas para cada pedido que hizo el cliente, es necesario aplicarle el descuento recién cuando tengas la ganancia total del pedido y después redondear(no por cada contenido). No se si me explico.

**Comment by FinzoYFunzo** [comment]
🐐
