### ISSUE TITLE
Instancias de clase y asignación de variables

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#540]
Hola, tengo una duda. Si por ejemplo tengo un diccionario de instancias de una clase, donde la key es el nombre y el value es la instancia, y luego asigno  a una variable `var1 = diccionario['nombre_obj1']`, esto carga la instancia a mi variable y, si luego cambio los parámetros de esta instancia, estos también se cambian en la instancia que está dentro del diccionario? Me refiero, esto se comporta como una copia o como una referencia?

**Comment by matiasmasjuan** [comment]
Hola @dlmed !

Te sugiero que en estos casos en donde **no sabes** si cuando **igualas** una **variable** a un **objeto** de un *diccionario*, no sabes si hace una **copia** o una **referencia**, lo **pruebes tu mismo** y veas que ocurre. 

En respuesta a tu pregunta, cuando igualas una **variable** a un **objeto** dentro de un **diccionario**, lo que harás será que esa **variable** será **igual** al **objeto** y además será el **mismo** objeto instanciado, vale decir, **no será una mera copia**. Por lo tanto, si tu modificas un **atributo** de la variable, estarás cambiando el **atributo** del **objeto instanciado**, por lo que el **objeto dentro del diccionario** **también** **sufrirá** **modificaciones**, ya que son el **mismo**.

Saludos! 😄

**Comment by dlmed** [comment]
buenaa muchas gracias!

**Comment by dlmed** [comment]
Lo mismo pasa si el diccionario es atributo de un objeto? Es decir, si modifico este atributo, cambian los objetos del diccionario?

**Comment by matiasmasjuan** [comment]
Vuelvo a insistir que este tipo de **dudas** los puedes **probar tu mismo** y analizar lo que **sucede**.

En respuesta a tu pregunta, **si**, pasa lo **mismo**. si defines una variable igual al **atributo** de una **instancia** de **una** **clase**, si modificas la **variable** **también** modificarás el **atributo** de la **instancia** (al menos si este atributo es un *diccionario*).

Saludos!
