### ISSUE TITLE
Compra de snack

### ISSUE THREAD

**Issue by mmsaavedra1** [IIC2233/Syllabus#540]
Si tengo un Alumno que desea comprar un snack y dentro de sus preferencias llega a existir el caso que no tenga un vendedor de snack asociado, asumo que este alumno no puede comprar uno?

**Comment by cilopez** [comment]
Acuerdate que existe _Quick Devil_ y vende de todo !

**Comment by mmsaavedra1** [comment]
Me surgió otra duda,

La tasa de compra de snack es 0.3 y distribuye exponencial, hice un for para ver un rango de tiempo y son aproximadamente 3 minutos en promedio la continuidad de compra de un snack. 

![captura de pantalla 2017-10-17 a la s 09 58 19](https://user-images.githubusercontent.com/23617087/31666285-09e9dd84-b322-11e7-944b-a684bec17d67.png)

Si mi personaje está haciendo la fila para almorzar este saldría de la fila cada 3 minutos para comer un snack y eso hay que multiplicarlo por cada alumno. Entonces no tiene sentido que la compra de snack sea durante el día, si no que restringirlo a los instantes en que no está comprando almuerzo.

ej: Alumna Sasha Grey compra almuerzo entre 12:00 y 12:59, por lo tanto se le debiese prohibir comprar snack en ese horario, no?, ya que el enunciado menciona que es en cualquier momento del día.

**Comment by cilopez** [comment]
Lo modifique #543 , señalame si se comprende y esta todo bien, saludos
