### ISSUE TITLE
Modelación circular

### ISSUE THREAD

**Issue by Pipelao** [IIC2233/Syllabus#540]
Hola :)
Mencionando un poco lo que se pregunta en la iisue #519 , la idea es que en las clases ¿no reciba instancias de otras clases de manera que la clase mayor no pueda acceder a los atributos de esta?, ¿o puedo hacer que  si reciba la instancia y hacer ciertos atributos/métodos privados colocándole un _ al atributo/método?
Gracias de ante mano

**Comment by rihanuch** [comment]
¡Hola @Pipelao !

La idea evitar la modelación circular es que se pueda tener una separación lógica de las cosas y así poder asimilarlo lo mejor posible a la vida real. Te dejo el link al la issue #53 🔙 que habla más en detalle de esto y de cómo evitarlo

¡Saludos! 🍀

**Comment by Pipelao** [comment]
Perfecto, espero haberlo entendido, gracias.

**Comment by jjcamus** [comment]
Hola, tenia una duda sobre si un caso es programación circular o no.
Dado el caso de una **clase A** que **posee instancias de** una **clase B** en sus atributos. ¿Es programacion circular si un metodo de la clase B recibe una instancia de la clase A, y en este mismo metodo se alteran atributos de la clase A **mediante metodos de la clase A**? (osea sin escribir directamente ClaseA.atributo == algo)
Ej:
`
class A():

    def __init__(self):
        self.atributo = True
        self.instancias = [B()]


    def cambiar_atributo(self, nuevo_valor):
        self.atributo = nuevo_valor


class B():

    def __init__(self):
        self.no_importa = None


    def metodo(self, instancia_de_A):
        instancia_de_A.cambiar_atributo( False )
`

**Comment by rihanuch** [comment]
¡Hola @jjcamus !

Sí, eso sí sería programación circular 🔁

¡Saludos! 🍀

**Comment by ljrodriguez1** [comment]
No me queda del todo caso si este ejemplo seria una referencia circulares:
tener una función por ejemplo de un Cliente a la que se le pasa como argumento una clase Restaurante, y dentro de la función del cliente se ocupan valores de la clase, como podrían ser los precios. Para mi esto no seria una referencia circular ya que el cliente nunca guarda en uno de sus atributos a el restaurante, sino que solo hace consultas para una función en especifico.
Para solucionar esto podría pasarle una lista a la función del Cliente que contenga la solo la información necesaria del Restaurante. pero lo encuentro poco practico.
Muchas Gracias

**Comment by rihanuch** [comment]
¡Hola @ljrodriguez1 !

Sí, sería circular 🔄. Es importante distinguir entre que se haga a que se pueda hacer. El simple hecho de que se pueda hacer ya muestra una modelación débil. Quizás para efectos prácticos de este curso de lo mismo, pero en la vida real si importa.

Imagina, por ejemplo, que tenemos una arquitectura cliente servidor en la cual uno le pasa el servidor al cliente para obtener unos pocos datos. El simple hecho de pasar más información de la necesaria pone en riesgo la seguridad de nuestra aplicación, ya que el cliente puede interceptar el código y hacer inyecciones de código (lo cual no es para nada deseable)

No se si con el ejemplo anterior te queda más claro por qué es importante 😬. ¡Si aún tienes dudas pregunta con confianza!

¡Saludos! 🍀

**Comment by mplazadelosreyes** [comment]
Hola! 
Tengo una duda con la programación circular también.
Por ejemplo supongamos que tengo la clase Adulto, y que esta clase tiene un atributo que es una lista con los juegos visitados:

class Adulto:
    
    def __init__(self):
        self.juegos_visitados = []

Si en el atributo juegos_visitados guardo el id de la atracción y no la instancia de la clase de la atracción, eso no sería programación circular cierto? o me estoy equivocando? porque solo quiero llevar un registro de los juegos que visitó ese adulto pero el no podría acceder a ningún otro atributo de la atracción, ni tampoco a modificar alguno de estos. 
Eso está permitido entonces o no?

Gracias!!

**Comment by rihanuch** [comment]
¡Hola @mplazadelosreyes !

No, eso no sería circular, ya que el adulto no puede acceder ni modificar nada de los juegos 🎉

¡Saludos! 🍀

**Comment by Hernan4444** [comment]
@mplazadelosreyes eso estaría bien, solo estás guardando una información de la atracción, tal como lo haríamos nosotros que guardamos en nuestra cabeza el nombre de la atracción que visitamos. Guardar el id y no la instancia está permitido.

Saludos ✌️
