### ISSUE TITLE
Cálculo nota tareas

### ISSUE THREAD

**Issue by dgzmr** [IIC2233/syllabus#541]
Hola, considerando que la peor nota de las tareas se elimina como quedaría el cálculo para la nota de las tareas? Gracias.

**Comment by lily416** [comment]
En el [readme del syllabus](https://github.com/IIC2233/syllabus/blob/master/README.md) se explica como funciona el nuevo calculo de nota de las tareas.

![image](https://user-images.githubusercontent.com/26393515/69593856-45b48600-0fd9-11ea-98f9-6d5f016c904a.png)

Puedes correr ese mismo código de python e ir probando con tus notas, para ver cuál sería tu promedio final de tareas dependiendo de las notas que quedan pendientes.


Saludos y éxito con lo que queda del semestre 👋💪
