### ISSUE TITLE
problemas con imagen de fondo QtDesigner al abrirlas con python

### ISSUE THREAD

**Issue by luzmagurzua** [IIC2233/syllabus#541]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Me pasa que en el diseño de alguna ventana, pongo una imagen de fondo en el QtDesigner y todo bien, luego cuando ejecuto el código en Python y abro la ventana aparece sin el fondo. No logro entender por qué ocurre esto.

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mmunoz12** [comment]
Hola @luzmagurzua! Quizás es un problema con los patos, pero habría que verlo con más detalle🤔. Podrías hacer push en tu repo para verlo? Quedo atenta (:

**Comment by luzmagurzua** [comment]
gracias, lo acabo de subir :)

**Comment by mmunoz12** [comment]
No sé si ya habrás solucionado este problema, pero me di cuenta que los fondos no los designaste como **pixmap** en QtDesigner. Creo que los pusiste como Stylesheet entonces esto podría hacer que después no aparezcan. Prueba con agregar las imágenes a los labels a través de Pixmap y me avisas como te va! (yo lo probé así y no hubo problemas para mostrarlo)

**Comment by luzmagurzua** [comment]
Muchas gracias por tu respuesta, voy a intentarlo como em dices y te cuento.

**Comment by luzmagurzua** [comment]
Acabo de hacer push, no me funciono:( borré el stylesheet y puse pixmap, me sigue apareciendo lo mismo T.T

**Comment by mmunoz12** [comment]
Ya creo que ya sé lo que pasa. Estas añadiendo la imagen como un recurso, que es otra forma de añadir archivos a QtDesigner y que terminan creado esos archivos .qrc que tienes en tus carpetas. Una forma más sencilla de añadir imágenes es que al momento de seleccionar el pixmap, elijas la opción de **añadir archivo** en vez de añadir recurso.  El pixmap quedará guardado con un path con respecto a la foto y no necesitará de nada más que la foto (a diferencia del recurso). Avisáme si eso funciona :)

**Comment by luzmagurzua** [comment]
No lo puedo creeeerrrrrrr, al fin me resultó!!!!! muchas gracias, me liberaste de una gran preocupación T.T jajajajaja

**Comment by mmunoz12** [comment]
wujuuu me alegro!! Suerte!
