### ISSUE TITLE
Volver atrás desde menú de acciones

### ISSUE THREAD

**Issue by carolinamaggi** [IIC2233/syllabus#541]
Si yo cargo un magizoólogo y me manda al menú de acciones, pero yo decido volver atrás al menú de inicio, es como si nunca hubiera entrado como ese magizoólogo? porque en teoría no cerré sesión antes de poder entrar como otro magizoólogo,  porque a diferencia de la tarea anterior una vez iniciado sesión te daba sólo la opción de salir para 'cerrar sesión'. La opción volver desde menú de acciones no me hace mucho sentido.

**Comment by matiasmasjuan** [comment]
Hola @carolinamaggi !

Efectivamente, tal como señalas, y en semejanza con la **T00**, la opción de ***volver atrás*** en el ***Menú de Acciones*** es para desplazarte hacía el ***Menú de Inicio***. Allí, tienes nuevamente la opción de ***cargar Magizóologo*** (que puede ser el mismo o uno distinto al que antes habías iniciado), ***crear Magizoólogo***, o ***salir***. Tal cual como indicas, es un método para **cerrar la sesión** del **Magizoólogo**, pero que el programa siga corriendo, ya que sólo te desplazarás al ***Menú de Inicio***.

Saludos y mucho éxito con la tarea! 😄
