### ISSUE TITLE
Problemas con los Qthreads

### ISSUE THREAD

**Issue by gbordoni** [IIC2233/Syllabus#541]
Hola! Estoy teniendo algunos problemas con los Qthreads. Tengo una clase Minion(Qthread) y otra clase MinionCreator(Qthread). Esta ultima va creando las oleadas de minions cada 10 segundos en su run(). El problema es que no me deja crear objetos de la clase Minion dentro de MinionCreator y me aparece el mensaje: "cannot set parent new parent is in a different thread". El parent de ambos sería la ventana principal, y no me deja setear a esta como parent de los minions, por estar dentro de otro thread (el MinionCreator). He buscado y no logro encontrar como resolverlo, lo poco que encontre es [https://stackoverflow.com/questions/20324804/how-to-use-qthread-correctly-in-pyqt-with-movetothread](url) esto pero no logro entender nada. Cualquier tipo de ayuda sera bien recibida. Entiendo por qué se genera el problema, pero no se cual sería la alternativa a implementar.

**Comment by iqacevedo** [comment]
Hola, este tipo de problemas pueden solucionarse usando QTimers en vez de QThreads, lee #522, si usas QTimers se considera como que estas usando Threads y puedes usarlos en toda tu tarea si lo quieres :smile: 

Saludos !
