### ISSUE TITLE
Error que no hace nada

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2233/syllabus#541]
Hola, me esta apareciendo un error en mi tarea y este no afecta de ninguna manera el desempeño del programa, me permite seguir con todo el programa, lo unico es que sale en la consola el error, mi pregunta es si hay descuento por eso o tengo que arreglarlo?
![image](https://user-images.githubusercontent.com/42476356/59557534-1faaa480-8faa-11e9-8505-cda030a32427.png)

**Comment by valerojasm** [comment]
Hola!

Como puedes leer en [este link](https://stackoverflow.com/questions/21058935/python-json-loads-shows-valueerror-extra-data), lo más probable es que el objeto `response` que estás decodificando sean múltiples `json` sin estar envueltos en una lista. Revísalo, y si el error persiste cuéntame por acá para ver qué más podría ser.

Saludos!

**Comment by lfuenzalida2** [comment]
Ahí dejo de aparecer el error, muchas graciaas!
