### ISSUE TITLE
Comprar snack al llegar al campus

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#541]
Se que esta pregunta es un duplicate de #522, pero no ha sido resuelta, quizás con publicarla de nuevo se resuelve 😀. Cuál es la probabilidad de comprar un snack al llegar al campus? El enunciado dice:

> Al momento de llegar a la universidad todas las personas deciden si comprarse un snack en forma aleatoria, segu ́n una probabilidad de random(0,1).

la función `random` no recibe parámetros. Se refieren a random.randint(0,1) y si es 1 compra, si es 0 no compra? Es decir, tiene 50% de probabilidades de comprar un snack al llegar al campus?

**Comment by cilopez** [comment]
@bedefrunner  voy aclarar esto dentro de poco, que no está explicíto en el enunciado.

**Comment by cilopez** [comment]
#543
