### ISSUE TITLE
Modificar los saltos de linea de las funciones

### ISSUE THREAD

**Issue by JohanM-cyber** [IIC2233/Syllabus#542]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Quería saber si podía modificar los saltos de línea que tienen los parámetros de la función, ya que originalmente están de esta forma:
![image](https://github.com/user-attachments/assets/588fd3d2-4fdb-49a2-aa14-86f71f029c68)
 
Y quiero colocarlos de esta forma para ahorrar líneas:
![image](https://github.com/user-attachments/assets/34bcc83d-d576-48a4-bebc-2a61d07249ad)

Cumpliendo obviamente que no sobrepase los 100 caracteres. La razón de preguntar esto es porque la forma en que colocaron estas funciones roban muchas líneas y como tenemos un limite de 400 líneas, quería ver si podía hacer estos recortes.

Literal esto 👇 se lleva 7 líneas de código en parámetros, cuando podrían ser fácilmente 3 o 2 😅
![image](https://github.com/user-attachments/assets/e1d56f3b-e33f-412c-884e-018fe4946126)

**Comment by AlonsoPlaza** [comment]
Hola, no hay problema con que modifiques los saltos de línea mientras siga funcionando todo con normalidad.
