### ISSUE TITLE
Duda con carga de archivos creados con Qt

### ISSUE THREAD

**Issue by LucianaMedel** [IIC2233/syllabus#542]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!, llevo dias tratando de cargar cosas creadas con Qt a mi codigo en python, me dice no encontrar los archivos, tal que cree un codigo muy simplificado que solo me abriera una ventana simple y tampoco logra encontrarlo aunque esté en la misma carpeta, mi pc no tiene problemas para abrir la AS2 pero cualquier otra cosa no me corre, creo que el problema es mi pc pues le mande este pequeño codigo simple a una amiga (no del ramo) y le corre perfectamente
nose que podría estar pasando, porfi ayuda

**Comment by valerianazal** [comment]
Hola! Sigues con este problema?
