### ISSUE TITLE
Decidir ir a comer

### ISSUE THREAD

**Issue by AndresGarciadelaHuerta** [IIC2233/Syllabus#542]
Me he cabeceado harto rato tratando de entender bien como funciona y la verdad es que no me queda claro. El enunciado dice:

![captura de pantalla 2017-10-17 a la s 10 05 25](https://user-images.githubusercontent.com/30664883/31666466-b8444a36-b322-11e7-90f9-aab179a89b08.png)

De esto entiendo que los "mu" son 1,2, 1,3 y 1,4. Haciendo normalvariate me dan casi siempre tiempos mayores a 60 minutos (lo que está bien ya que el "mu" más chico es 72 mins). Con lo que no entiendo como asignar a que hora va un miembroUC a almorzar. ¿Cuál es el tiempo inicial al que le debo sumar el resultado de normalvariate? ¿La hora de llegada de cada miembro a la universidad ó a 12, 13 y 14 según corresponda?

Y otra duda que tengo es si esto debo calcularlo cada día o una sola vez al principio de la simulación (como dijeron en otra issue que los rangos de almuerzo de cada miembro eran constantes).

Gracias!!

**Comment by iqacevedo** [comment]
Hola,

Los "mu" pueden ser 12:10 hrs, 13:10 hrs ó 15:10 hrs dependiendo de a que hora almuerza el miembroUC regularmente (la hora a la que almuerza regularmente puede ser constante). Esto significa que en promedio debería almorzar cercano a esa hora cada uno. Para armar la normavariate debes traspasar estas horas a números, una opción es pasarla a minutos, y ahí depende de cual es tu minuto 0 de cuantos minutos vas a considerar cada "mu". Por ejemplo, si consideras el minuto 0 como las 11:00, los "mu" deberían ser 70, 130 y 190. 

Debes calcular la hora a la que deciden ir a comer cada día. Si tienes dudas en como se relacionan las personas que deciden ir a comer antes de haber llegado a la universidad, te recomiendo leer la issue #491.

Saludos !

**Comment by AndresGarciadelaHuerta** [comment]
@iqacevedo Gracias por la aclaración, estaba dividiendo en vez de contarlo como si fueran 10 minutos jajaja. Entendí perfecto, gracias!

**Comment by bedefrunner** [comment]
@iqacevedo quizás estoy equivocado, pero la distribución normal podría arrojar, por ejemplo, que una persona que almuerza entre 13 y 14 decida ir a almorzar a las 12:40. Debemos permitir esto? Quizás esta situación se "arreglaría" si es que el tiempo de traslado a ir a almorzar sea mayor a 20 minutos, con lo cual llega a una cola a las 13:00 y se cumple su horario. Pero si el tiempo de traslado es menor, llegará antes de las 13:00. 
Lo mismo aplica para el caso de que un alumno que almuerza entre 13:00 y 14:00 decida ir a almorzar a las 13:40 y demore más de 20 minutos en llegar a un puesto.

**Comment by iqacevedo** [comment]
@bedefrunner si puede darse ese caso, no tienes que evitarlo (es válido que una persona que **regularmente** almuerza a una hora, almuerce antes un día). La única consideración especial que debes tener son la que se discutió en la issue #491, sobre que pasa si un miembroUC decide ir a almorzar antes de llegar a la universidad.

Saludos !

**Comment by iqacevedo** [comment]
@bedefrunner acabo de actualizar la respuesta de más arriba.

Saludos !

**Comment by bedefrunner** [comment]
Ok! gracias
