### ISSUE TITLE
pillow no aparece con el pip

### ISSUE THREAD

**Issue by StroveLight** [IIC2233/syllabus#542]
No me aparece pillow con el pip; además la advertencia me da mal agüero, ya que ya se usa el PIL en una parte de la tarea

<img width="535" alt="pillow" src="https://user-images.githubusercontent.com/48263952/59564983-684e7600-901b-11e9-9e7e-ccabbf2721e9.png">

por ultimo, ¿porqué pillow no está en las librerías permitidas?

**Comment by iqacevedo** [comment]
Hola !

`pillow` es un fork de la librería `PIL`, entonces se ocupa `PIL`, pero el que se instala con `pillow` (por eso no pueden vivir juntos). Para lo único que se permite usar `pillow` es para utilizar el método get_pixels del archivo entregado junto al enunciado. ¿Podrías subir una foto de lo que te sale con pip3 o pip al intentar instalar `pillow`?, asi podemos ayudarte a ver por que no se instala.

Quedo atento.
Saludos !

**Comment by StroveLight** [comment]
creo que ya entendí, gracias
