### ISSUE TITLE
DUDA ENUNCIADO

### ISSUE THREAD

**Issue by betolguin** [IIC2233/syllabus#542]
holaa! no me queda clara la diferencia entre entrenar (deportista) vs entrenar_deportista (menu entrenador), 
quedo atento!
gracias de antemano

**Comment by vicentevegaulloa** [comment]
Hola @betolguin !

Las delegaciones deben revisar si tienen suficiente dinero para entrenar a un deportista antes de enviarlo a entrenar. El deportista debe modificar sus propios atributos cuando entrena. 

Espero haber aclarado tu duda 😄
