### ISSUE TITLE
Error: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by egbusch** [IIC2233/Syllabus#542]
Hola ! pido ayuda con error:

Cuando corro el juego, a veces se cae por el error: `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`. Sin embargo no parece tener una causa determianda. He buscado, pero no logro entender las respuestas o bien solo mencionan que es un problema de segmentación de memoria del hardware.

PD: Estoy usando mac 10.12.5.

**Comment by iqacevedo** [comment]
Hola !
Estoy buscando datos sobre tu error, podrías decirnos más información. Ocupas PyCharm?, si es así ocurre cuando usas el debugg + run?, ocupas Anaconda?. En el programa en el que se te cae, utilizas algo muy rebuscado? utilizas alguna librería externa?.

Saludos!

**Comment by hanavarrete** [comment]
Sube tu código al repo para poder ver si es algo ajeno a mac!. Saludos

**Comment by egbusch** [comment]
Subido !

**Comment by JoseValencia125** [comment]
Uso pycharm en mac y tengo exactamente el mismo error :(

**Comment by iqacevedo** [comment]
Alguno podría subir su tarea a su repo para que podamos ver si tiene que ver con el sistema operativo. Además, podrían indicarnos cuando exactamente se produce el error? @egbusch aun no has subido nada a tu repo .

**Comment by JoseValencia125** [comment]
Voy a subirla al tiro

**Comment by JoseValencia125** [comment]
Ya subí la mia al repo, es la linea 116 del back_end la que genera el error (deje comentado "esta linea crea el error" en el codigo)

**Comment by hanavarrete** [comment]
con @iqacevedo creemos que tu error está en que estás pasando un thread por la señal. Prueba como en el ejemplo que subimos, que entregamos una clase con los parametros necesarios, pero nunca un Qthread entero. Prueba eso y dinos como te va!

**Comment by egbusch** [comment]
Disculpa la demora, pero no cada vez que lo intento subir me arroja un error al hacer `git push` ! Alguna vez hice commit cuando tenia el archivo gif de la actividad 12. Utilice el comando `git reset HEAD~1` e intentando volver a subirlo pero me sigue arrojando el mismo error.

error:
`remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 451aa847ecf470071c5bb8dacbc861f4
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Actividades/AC12/mono.gif is 213.28 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/IIC2233/egbusch-iic2233-2017-1.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/IIC2233/egbusch-iic2233-2017-1.git'`

Lo raro es que ya borre el archivo .gif de la carpeta AC12. Por lo que no entiendo porque me sigue apareciendo como un archivo que quiero subir.

**Comment by iqacevedo** [comment]
@egbusch no se como arreglar tu problema usando `git`, pero puedes respaldar todos tus cambios desde tu ultimo `git push` para que no los pierdas en una carpeta afuera de tu repo, luego borrar tu repo y volver a descargarlo, agregar a ese tus cambios y hacer `git push`. Es la solución más rápida que se nos ocurre.

**Comment by rrhurtado** [comment]
Hola ! Sacado de https://stackoverflow.com/a/39394869 como fuente, donde tienen el mismo problema:

Intenta estos pasos

`git rm --cached giant_file`
Donde giant_file es el nombre del archivo, en este caso 'mono.gif'

`git commit --amend -CHEAD`
Parchamos el commit anterior con este nuevo commit, en que deseamos borrar el archivo

,`git push`

**Comment by egbusch** [comment]
Gracias, acabo de implementar lo que dijo @iqacevedo y funciono bien. Código esta subido al repo y aún me persiste el problema originalmente mencionado. No ocurre de inmediato pero si se cae por esa razón.

**Comment by iqacevedo** [comment]
@egbusch has podido solucionar tu problema ? Si no es así, recuerda que es muy importante el uso de señales para que los Qthreads puedan comunicarse con la Ventana Principal (no tenias eso puede ser que el error vaya por ahí). Recuerda revisar bien el ejemplo que se subió junto al enunciado de esta tarea para que veas cómo usar bien señales.

Saludos !

**Comment by egbusch** [comment]
Aún no puedo solucionar el problema que revisamos en la programaton: minion sin atributo de su centro, siendo que este esta definido como una property. Lo más raro es que suele partir bien y derrepente arroja este error y los minions se vuelven invisibles para las torres ya que no tienen centro y nadie los puede atacar.
PD: ahora si estoy trabajando con señales

**Comment by hanavarrete** [comment]
Hola! Puedes explicar mejor tu problema actual? No me queda muy claro que está pasando ya que no vi tu problema en la programaton :(.

**Comment by egbusch** [comment]
Aún no logro solucionarlo por lo que lo explicaré. Actualmente las la forma de ver si algo esta dentro del rango es comparar e centro de cada una d las cosas en el mapa. Para esto, en el caso de los objetos que se mueven, tengo definida una property con el centro para que se mantenga actualizado más fácil. El problema se ejecuta cuando otro objeto (ej: torre) le pregunta a las cosas del mapa donde esta su centro y por alguna razón me dice que el objeto minion no tiene el atributo centro, siendo que este se define como una property. Lo más raro es que funciona en un comienzo y de forma totalmente random salta este error y los minions se vuelven invisibles a todo porque no tienen centro (siendo que esta definido como una property). 
Gracias por el apoyo con esta tarea, esta particularmente larga.

**Comment by hanavarrete** [comment]
En que lugar están instanciados tus objetos?

**Comment by egbusch** [comment]
Logre solucionar los problemas que he tenido con errores del código. Sin embargo, ahora que el juego esta cada vez más completo se cae todo el tiempo por el error con el que inicie esta issue:
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`.
Nose si será por mac o no, pero no entiendo porque pasa (se da de forma aleatoria).
Cualquier ayuda será muy bien recibida !

**Comment by sebacruzd** [comment]
Busqué el error en google y me sale [esto](https://stackoverflow.com/questions/40203572/pycharm-debug-segmentation-fault-signal-11), puede que te ayude.

**Comment by egbusch** [comment]
Gracias ! La solución en este caso sería desinstalar e instalar pycharm y python denuevo ?? O no entendí bien la solución que propuso ??

**Comment by iqacevedo** [comment]
Respecto a la solución no estoy seguro si funcionará. Además, te sugiero fuertemente revisar que comuniques las acciones con señales y no hagas cosas como eliminar un Thread desde otro, o eliminar directamente algo de un Thread desde otro.
