### ISSUE TITLE
Formato y nombres de parámetros

### ISSUE THREAD

**Issue by vobrador** [IIC2233/syllabus#542]
No tengo mucha claridad respecto a los valores que son o no parámetros. Agradecería mucho si me pueden explicar un poco y si está bien que este escribiendo el formato de este forma: COSTO_E_ALIM = 5 (por ejemplo para el costo energético de alimentar). Seguí el ejemplo del enunciado pero no se si en realidad hay que escribir con mayúscula o no. Por otro lado, las funciones como alimentarse:
min (1, ((efec_ham + efec_agres)/100) los valores 1 y 100 son parámetros? ¿Cómo se llamaría dado que no son nada en particular?

**Comment by fdoflorenzano** [comment]
Hola @vobrador,

Se ha preguntado múltiples veces sobre este tema. Recuerda revisar *issues* anteriores o [el compilado de *issues* de la tarea](https://github.com/IIC2233/syllabus/issues/239) antes de preguntar.

Específicamente, las *issues*: #254, #258, #269, #278, #312 y #313 hablan del tema que preguntas.

Si tienes una duda sobre algo hablado en alguna de esas *issues*, puedes preguntar ahí, o en su defecto abrir una nueva *issue* con tu duda más específica. 

Saludos.

**Comment by vobrador** [comment]
Gracias y perdón, enserio busqué alguna issue pero al parecer no muy bien, perdon. De todas maneras si me quedaron dudas, debe escribirse en mayuscula obligatoriamente? y que nombre me sugieren para los que estan dentro de funciones min() max()? y el 100, onda DIVISOR_ALIM estaria bien?

**Comment by fdoflorenzano** [comment]
Hola @vobrador,

Sí, la idea es que estén en `ESTE_FORMATO`, así se pueden diferenciar de otras variables en el código. 

El nombre de cada parámetro es decisión tuya, pero como toda variable, recomendamos que tenga un nombre **descriptivo**. 

Saludos.
