### ISSUE TITLE
Ubicación parametros.json

### ISSUE THREAD

**Issue by benito-tondreaux** [IIC2233/syllabus#542]
En el enunciado de la tarea indica que la ubicación de el archivo "parametros.json" debe ser en "client/parametros.json" y ademas en la carpeta "server/parametros.json", sin embargo estoy trabajando con todos los archivos .py dentro de la carpeta "client" y "server" respectivamente por comodidad, ¿Afecta en la revisión de la tarea que yo continúe así o debo cambiarlo y trabajar los archivos python fuera de la carpeta "client" y "server"?.

Saludos!!

**Comment by DCCollao** [comment]
Hola! 

Tal como se indica en la sección 3.1.1 del enunciado, los archivos `.py` que correspondan al servidor deben encontrarse dentro de la carpeta server, mientras que todo archivo `.py` que corresponda al cliente debe encontrarse dentro de la carpeta client. 

![image](https://user-images.githubusercontent.com/37167447/69586855-9ff61c80-0fc2-11ea-9ac3-80a6604f7b1d.png)
En el ejemplo se utiliza `main.py` dentro de client y server, pero tú puedes crear más módulos e importarlos dentro de cada `main.py`

Espero haber aclarado tu duda, éxito!

**Comment by benito-tondreaux** [comment]
Gracias!!

**Comment by SamWeinstein** [comment]
Hola! Siguiendo la linea de la pregunta anterior,  me gustaría poder tener la carpeta sprites dentro del directorio cliente, para poder así acceder mas fácilmente, considerando ademas que los sprites solo los necesita el cliente, no el servidor. Esta permitido esto? Y de no estar permitido, como debería escribir el path para un directorio "anterior" al cwd actual, de modo que funcione en todos los computadores? Se me ocurrió cambiando el cwd temporalmente, pero si se puede poner la carpeta sprites dentro de cliente esto no es necesario.

**Comment by BelenMadariaga** [comment]
Hola! Se puede hacer lo mismo, pero con los archivos "amigos.json" y "usuarios.json" de manera que esten en la carpeta del servidor?

**Comment by jmwielandt** [comment]
@SamWeinstein te recomiendo revisar la issue #544, ahí lo respondí.

@BelenMadariaga los archivos `amigos.json` y `usuarios.json` deberían estar en la carpeta servidor y ser solo este quien acceda a ellos. De todas formas, debes especificar en tu readme dónde deben ir colocados estos archivos para la ejecución de tu tarea (ya que no los deben subir).

Saludos~
