### ISSUE TITLE
Probabilidad compra Snack

### ISSUE THREAD

**Issue by cilopez** [IIC2233/Syllabus#543]
En el enunciado no queda claro cuando y con que probabilidad compra un miembro uc un _snack_, por ende explicaré por este medio como funciona(_se simplificó_):

- Un miembro comprará un snack en un día si la probabilidad obtenida por una distribución uniforme discreta(0,1) es mayor a 0,5, es decir tiene un 50% de probabilidad de comprar un _snack_ en un día, si la probabilidad es menor no comprará _snacks_ ese día. 

- Si un  miembro va a comprar el _snack_,entonces el momento en que lo comprará  distribuirá uniformemente entre su hora de llegada y la hora de salida. 

Si ya programaron esta probabilidad según lo que entendieron inicialmente en su enunciado, dejenla nomás en su programa y señalen en su _readme_ que lo realizaron antes que se subiera esta aclaración.(_más tarde editaré el enunciado_)

**Comment by mapendola** [comment]
Si el momento en que va a comprar snack es su horario de almuerzo, se le debe prohibir ir en ese momento o que hacemos para ese caso?  esto porque podría estar en una fila para comprar almuerzo y al mismo tiempo producirse la compra de snack.

**Comment by rihanuch** [comment]
@cilopez al decir alumno te refieres a los miembros uc o a los alumnos?

**Comment by cilopez** [comment]
@rihanuch miembro, siempre me confundo jajaja perdon

**Comment by cilopez** [comment]
@mapendola puedes prohibirlo o puedes hacer que apenas termine de comprar su almuerzo, compre un snack(considera que no hay tiempo de traslado en ese caso)

**Comment by ptflores1** [comment]
@cilopez Entonces ya no existe la posibilidad de que al llegar compre snack? solo comprara como maximo una vez al dia? Gracias !

**Comment by cilopez** [comment]
@ptflores1  teoricamente es nula, si sólo una vez, no importa pregunta nomás

**Comment by estebanmb** [comment]
@cilopez Entonces ya no se debe considerar esto:
![image](https://user-images.githubusercontent.com/26117973/31689021-8193c61e-b364-11e7-88f6-a6f5c2eae0a5.png)

**Comment by llloyola** [comment]
@cilopez Ya actualizaron el enunciado?

**Comment by Kitaps** [comment]
@estebanmb parece que si lo haces así, aunq tu t sea de una hora, terminarías con:
![image](https://user-images.githubusercontent.com/10112117/31692534-83fe474c-b370-11e7-8e42-a95d4a7b23b5.png)
muchas personas comprando muchos snacks
por lo que la solución de @cilopez es para que no pase esto.

**Comment by cilopez** [comment]
@estebanmb si ya no se considera 
@llloyola  no, lo hago ahora

**Comment by Bneya** [comment]
¿Cuando una persona decide comprar un **snack** en un moemento x del día, tenemos que considerar que se **demora** en caminar a la entrada el **expovariate(lambda_traslado)** como en el almuerzo normal o es **instantánea** la compra?

**Comment by Kitaps** [comment]
#551 Pregunto aca igual, que igual está relacionado

**Comment by cilopez** [comment]
@Bneya ya que no se menciona en el enunciado y a modo de simplificación, considera que no

**Comment by cilopez** [comment]
@Kitaps  actualiza el enunciado !

**Comment by Jiruiz2** [comment]
¿ Las colas rigen de igual manera o es todo instantáneo?

**Comment by Hernan4444** [comment]
@Jiruiz2 si rigen (#489)
Saludos ✌️

**Comment by ptflores1** [comment]
@cilopez @Hernan4444 Mas arriba preguntaron sobre que pasa si la persona esta en la fila (de almuerzo) a la hora en que decide ir a comprar snack. Ahora la pregunta es en el caso contrario, que pasa si esta en la fila de snack y decide ir a comprar almuerzo? se olvida del snack y va por el almuerzo nomas?  en ese caso consideramos tiempo de traslado?

**Comment by Hernan4444** [comment]
@ptflores1 no está especificado en el enunciado, lo dejamos a tu criterio

Saludos ✌️
