### ISSUE TITLE
Problemas de interfaz

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#543]
He escrito el codigo de la ventana de inicio con un boton que se conecta a una funcion que lanza una nueva pantalla. El boton funciona y llama a la funcion, esto lo se por que utilize un print para comprobar, pero al presionar el boton, no se lanza la segunda pantalla. Por que puede ser?

**Comment by lily416** [comment]
Hola, ¿antes o después del `print` haces `show()` de la ventana que quieres mostrar?

**Comment by sofiuni** [comment]
Despues de el print

**Comment by lily416** [comment]
¿Podrías subir tu código a tu repositorio de github para revisarlo?

**Comment by sofiuni** [comment]
Se esta subiendo!

**Comment by lily416** [comment]
Para hacer que se cambie de ventana correctamente tienes que:
1. Hacer que la función `boton_principal()` sea un método de tu clase `VentanaInicio`.
1. Después tienes que guardar la instancia de `VentanaPrincipal` como un atributo de la clase `VentanaInicio`, basta con agregarle un `self` a lo que ya tienes.
1. Y ya debería funcionar correctamente. 🎉 

Igual te recomiendo hacer `hide()` de la ventana de inicio después de que hayas mostrado la ventana principal.

Ojalá te funcione correctamente, cualquier problema no dudes en avisar 😄 
Saludos y éxito con tu tarea 👋🐧

**Comment by sofiuni** [comment]
Me dio in error!! 

TypeError: boton_principal() takes 0 positional arguments but 1 was given
Aborted (core dumped)

Tambien me daba sin el hide()

**Comment by lily416** [comment]
El error se debe a que la función `boton_principal()` está recibiendo un argumento que no esperaba, que en este caso sería el argumento implícito `self`.

Como se explica en la #539, los métodos de una clase que no utilizan el `self` se conocen como `@staticmethod`.

En este caso `boton_principal()` si debe recibir el `self` ya que se debe utilizar para guardar la instancia de `VentanaPrincipal`, por lo que para solucionar el error debes hacer que se reciba el `self` como argumento de la función.


Ojalá que con eso te quede más claro la razón del error y logres solucionarlo.

**Comment by sofiuni** [comment]
Gracias! Ahora esta funcionando, voy a seguir con el punto 4!
