### ISSUE TITLE
fijar variable aleatoria

### ISSUE THREAD

**Issue by sebaelsaca** [IIC2233/syllabus#543]
Hola!

Cuando pongo una variable con el módulo "random" cambia cada vez que la llamo y necesito que se quede estática una vez creado. Cómo se hace???

**Comment by matiasmasjuan** [comment]
Hola @sebaelsaca !

No entiendo muy bien cómo estas **definiendo** la variable. Si la haces de la siguiente forma:
```python
variable_1 = random.random()
```
Cada vez que llames a la ```variable_1``` **siempre** va a conservar el **mismo valor**.

Por otro lado, si lo estas **haciendo** desde una clase, hay **dos** formas posibles. La primera es como un **método**:

```python
class Algo:
    def __init__(self, ... ):
    
    def metodo_random(self):
        return random.random()
```
En este caso, cada vez que ejecutes el **método**: *metodo_random()* se te generará un valor nuevo cada vez que lo llamas. 
Sin embargo, si lo haces como un **atributo**: 

```python
class Algo:
    def __init__(self, ... ):
        self.valor_aleatorio = random.random()
```

El **atributo** *valor_aleatorio* como ya se definió en el método ***__init__***, por lo que **siempre** se conservará el valor de ```instancia.valor_aleatorio``` cada vez que la llames (a menos que cambies el valor de la instancia).

Saludos! 😄

**Comment by sebaelsaca** [comment]
Yaaaa entiendo . Otra cosa que me aproblemaba era tener todas las variables aleatorias en "parametros" y eso hacia que fueran estáticas al llamarlas. Puedo guardar mis variables aleatorias fuera de parametros? O me descontarán por hacerlo?

**Comment by matiasmasjuan** [comment]
Si, puedes hacerlo. De esta forma, podrás lograr que no sean **estáticas** siempre.

Saludos! 😄
