### ISSUE TITLE
Importación de parámetros

### ISSUE THREAD

**Issue by Artaudd** [IIC2233/syllabus#543]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!, tengo una duda respecto a algo que se menciona en el enunciado de la tarea (adjunto foto).

![image](https://user-images.githubusercontent.com/65875467/120090397-2fa4eb80-c0d0-11eb-9551-f62a9bf80afa.png)

Mi duda es la siguiente, **¿Al decir que el archivo de parámetros debe ser importado como módulo se refieren a que no podemos importar parámetros específicos?** Por ejemplo, yo he estado importando mis parámetros con "from parametros import PARAMETRO", ¿debería cambiarlo por "import parametros as p"?

Gracias de antemano por responder!

**Comment by tomasrosenberg** [comment]
Hola @Artaudd!
Cuando se menciona que se deben importar como **módulo** se refiere a que estos deben estar en un archivo aparte. El cómo importes parámetros queda a tu criterio, pero recordando que no se puede importar con: "import *", porque es mala práctica. Entonces, sí puedes usar "from parametros import PARAMETRO".
Espero que te haya aclarado la duda :D
