### ISSUE TITLE
Duda sobre tests

### ISSUE THREAD

**Issue by catalinarozasf** [IIC2233/Syllabus#543]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ si] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ si] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ si] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ si] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tdengo una duda ya que en Consultas_anidadas mi codigo genera un Key error en total ahorrado, aunque corran bien los test de total ahorrado. Muchas gracias.

**Comment by Vicente1824** [comment]
¡Hola @catalinarozasf 😁! Con la información que me das no puedo saber muy bien qué es lo que ocurre. ¿Me podrías adjuntar una captura de pantalla o el texto del error para saber lo que pasa? ¿Cuándo ocurre tu error, al ejecutar los tests? ¿En cuál test? También sería ideal si puedes hacer *push* de tu código actual para poder revisarlo bien. ¡Espero tu respuesta!

**Comment by mrmoon01000010** [comment]
Me ocurre este mismo error a mí. En los tests `tests_publicos.test_consulta_anidada.TestConsultaAnidada.test_2` (`test_2`) y `tests_publicos.test_consulta_anidada.TestConsultaAnidada.test_4` (`test_4`) pareciera que se filtran las opciones de pizzas, pero esto no afecta a los pedidos que puede contenerlas.
En mi caso, me aparece que en el `test_2` se pide calcular el descuento de `Tocino BBQ_S` pero el generador de pizzas que llega a este punto solo contiene `Camarones sobre ajo_S`. En el `test_4` el error que ocurre es similar pero los valores cambian.

**Comment by RumNCola** [comment]
> Me ocurre este mismo error a mí. En los tests `tests_publicos.test_consulta_anidada.TestConsultaAnidada.test_2` (`test_2`) y `tests_publicos.test_consulta_anidada.TestConsultaAnidada.test_4` (`test_4`) pareciera que se filtran las opciones de pizzas, pero esto no afecta a los pedidos que puede contenerlas. En mi caso, me aparece que en el `test_2` se pide calcular el descuento de `Tocino BBQ_S` pero el generador de pizzas que llega a este punto solo contiene `Camarones sobre ajo_S`. En el `test_4` el error que ocurre es similar pero los valores cambian.

+1, tengo exactamente el mismo problema

**Comment by Vicente1824** [comment]
@mrmoon01000010, @RumNCola, recuerden que en el caso de consultas anidadas hay una posibilidad de que haya un generador que tiene datos que otro generador no tiene. Eso se ve en la issue #490. ¿@catalinarozasf puede que ese sea el error al que te refieres?
