### ISSUE TITLE
Empate ¿Para abajo o neutro?

### ISSUE THREAD

**Issue by MagnaThyrsus** [IIC2233/syllabus#543]
Me surgió la duda de qué pasa con las delegaciones en caso de empate. ¿Se considera que ambas pierden y ambas tienen los descuentos correspondientes o no pasa nada? Y cuando es empate por `validez de competencia` (O invalidez) ¿Se debiera considerar distinto a cuando es empate dentro de competencia o un empate es un empate?

**Comment by vicentevegaulloa** [comment]
Hola @MagnaThyrsus !

El empate en caso de invalidez o de que empataron en puntos es el mismo, y en ambos casos no pasa nada, es decir, nadie se ver perjudicado ni beneficiado. Espero haber aclarado tu duda 😄

**Comment by MagnaThyrsus** [comment]
Ah okok gracias

**Comment by vicentevegaulloa** [comment]
De nada!
