### ISSUE TITLE
Sprite 6Ways o rotacion continua

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#543]
mis dudas son:
- se puede usar un sprite 6ways en vez de rotacion continua?
- si es asi, cual seria mas recomendable

**Comment by sebacruzd** [comment]
Hola,

Si con 6 ways te refieres a las imágenes que miran hacia arriba, abajo, izquierda, derecha y las diagonales, puedes usarlo. 
En este caso se debería cambiar a la imagen correcta para que el campeón esté mirando en la dirección del mouse, con la que más se asemeje de todas las que usarías (dado que no rotarías pero si cambiarías la imagen)

No hay alguno más recomendable, queda a tu criterio pero tiene que estar bien implementado de la manera que elijas.

Saludos!

**Comment by Dunkan1** [comment]
gracias, por responder tan rapido

**Comment by hanavarrete** [comment]
@Dunkan1  como complemento a lo que dice el seba, recuerda que de todas maneras debe apuntar hacia el mouse. Si es que hay un angulo que esté entre dos de tus imagenes, tendrás que acomodar para que quede mirando a él.

**Comment by akaminetzkyp** [comment]
Hola!

@hanavarrete, en muchos juegos existe una cantidad finita de orientaciones para el jugador. Por ejemplo, en [mi tarea](https://media.giphy.com/media/JW7zOOcClyTaU/giphy.gif) el campeón siempre sigue al mouse, pero apunta en una de cuatro direcciones. Si el juego es top-down, encuentro que no hay problema en rotar las imágenes. Sin embargo, opino que si el juego tiene una vista isométrica (mi caso), rotar las imágenes entre los ángulos arruinaría completamente la animación del campeón.

Si nuestra tarea usa una vista isométrica y sprites de este estilo, ¿podemos utilizar una cantidad finita de orientaciones?

Saludos!

**Comment by iqacevedo** [comment]
@akaminetzkyp si pueden, la idea es que se note una diferencia clara cuando el mouse cambie su ubicación. Tu animación esta muy buena :smiley: !!

Saludos!

**Comment by akaminetzkyp** [comment]
Perfecto! Muchas gracias! :happy:

**Comment by hanavarrete** [comment]
@akaminetzkyp  si es isométrica como tu caso no hay ningún problema, pero para los topview tendrán que tener cuidado en eso
