### ISSUE TITLE
Documentación

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2233/Syllabus#543]
¿Es necesario documentar las properties?

**Comment by monicabelen** [comment]
Hola, sí es necesario.

**Comment by kenzoak** [comment]
A pesar de que se expliquen por si solas? Ej: tiempo_minimo_limpieza, min_hambre, edad_max_adulto?

**Comment by Hernan4444** [comment]
@kenzoak tambien, porque que se expliquen por si sola puede ser algo un poco ambiguo para algunos y preferimos evitar una ambiguedad con esto. Si es algo sencillo, la documentación no te tomará más de 1 segundo es explicar 
```python
def tiempo_minimo_limpieza(self):
"""
indica el tiempo mínimo en limpiar la atracción
"""
```
