### ISSUE TITLE
Uso de properties para proximo evento

### ISSUE THREAD

**Issue by pdesolminihac** [IIC2233/Syllabus#544]
¿Es necesario usar properties para calcular el próximo evento como hicieron en la ayudantia?, ya que en el enunciado se explicita el necesario uso de properties pero yo las uso en otras ocasiones para obtener diferentes características y atributos en mis clases definidas.

**Comment by iqacevedo** [comment]
Hola, 

No te podemos decir en donde tienes o no que usar las properties. Como dijo @luvalenz en la issue #131: 

"El objetivo de las tareas, en cambio, es que ustedes puedan resolver un problema complejo usando de la mejor manera posible los conceptos vistos. Por lo tanto, no sólo deben entender las herramientas de programación, sino que deben pensar cómo usarlas de la mejor forma posible. En una tarea nunca les vamos a decir qué herramientas usar ni cómo usarlas, ya una de las cosas que se está evaluando es que ustedes puedan tomar estas decisiones."

Saludos !
