### ISSUE TITLE
los disparos de los esbirros

### ISSUE THREAD

**Issue by rjdelrio** [IIC2233/Syllabus#544]
los disparos de los esbirros tienen que perseguir a su objetivo o seguir derecho nomas

**Comment by rjdelrio** [comment]
ademas es posible que los esbirros tengan friendly fire?

**Comment by iqacevedo** [comment]
Hola !
Los ataques de los súbditos pueden ser como tu quieras ya que no está especificado, recuerda eso si que los súbditos normales atacan a corta distancia (por tanto en vez de un disparo haria más sentido que dieran un golpe). Respecto al friendly fire, queda a tu criterio nuevamente ya que no está especificado, si decides permitirlo y tu campeón mata a un súbdito propio no le des puntaje por esa traición.

Saludos !
