### ISSUE TITLE
numero total de salas

### ISSUE THREAD

**Issue by juakoke** [IIC2233/syllabus#544]
Hola, cuando hago la ventana que me muestra las salas, estas son un QPushButton, por lo tanto después de creadas cierto numero de salas, no me caben en pantalla. Mi duda es, ¿Puedo definir un máximo de salas que pueden estar creadas simultáneamente?

**Comment by siescobedo** [comment]
up

**Comment by MatiAedo** [comment]
cps

**Comment by jalliende** [comment]
No creo, ya que sale esto
![Captura](https://user-images.githubusercontent.com/48294819/59570838-226dce00-906c-11e9-8781-2384a20438da.PNG)

**Comment by MatiAedo** [comment]
Pero de todos modos me hace sentido que podamos poner un límite de 15-20 salas, para que haya algún orden y que no se creen 1000 salas (O eso espero) </3
