### ISSUE TITLE
Lluvia 

### ISSUE THREAD

**Issue by antoniacobo** [IIC2233/Syllabus#544]
Hola! En el enunciado dice que la probabilidad de lluvia es exponencial con  lambda 1/20 (lluvia/días). Si eso lo convertimos a tiempo de en la simulación podría ser que nos de por ejemplo el martes a las 14:20, eso quiere decir que a partir de ese momento empieza a llover o que es todo el martes que llueve?

**Comment by ptflores1** [comment]
Hola !
Queda a tu criterio, puedes hacer que se considere que todo el dia llueve o que la lluvia parte desde las 14:20.
Saludos!
