### ISSUE TITLE
Path en parametros

### ISSUE THREAD

**Issue by francisca0308** [IIC2233/syllabus#544]
Hola! Según tengo entendido, los path deben ir en parámetros, pero, no debo usar funciones en ese archivo, por lo que no podría unirlas en os.join()
Entonces, creo una lista con la ubicación del archivo como [ 'Archivos' , 'criaturas.csv' ] para usarla en el main.py o bien no incluyo los path en parametros.py

**Comment by matiasmasjuan** [comment]
Hola @francisca0308 !

Puedes usar lo que **estimes** mas **conveniente** en el archivo ***parametros.py*** para guardar la **ruta** (*listas, diccionarios, etc*) y luego usarlas en el *main.py* u otro archivo. Pero **si o si** los *paths* **deben** ir en ***parametros.py***.

Saludos! 😄
