### ISSUE TITLE
Ubicación de los sprites

### ISSUE THREAD

**Issue by kisco99** [IIC2233/syllabus#544]
¡Hola! ¿Puedo tener la carpeta sprites dentro de la carpeta client? Es con el fin de poder encontrar los sprites usando paths relativos y no absolutos.

**Comment by jmwielandt** [comment]
Hola!

Uno de los esquemas usados en la vida real es que el servidor guarde las imágenes y todos los recursos y se los envíe al cliente vía sockets **si este no las tiene**. El cliente las almacenaría en su espacio local y así funcionaría.

Sin embargo en esta tarea no necesitan implementar algo de este estilo, pueden guardar las imágenes en el cliente (si no hacen los bonus que pidan lo contrario) si quieres.

Ahora, no necesitas usar paths absolutos, ya que los sistemas operativos nos ofrecen dos "nombres" especiales: el punto "`.`" sirve para hacer referencia al directorio en el que estás, mientras que dos puntos "`..`" sirven para hacer referencia al directorio superior al que te encuentras.

De todas formas, ten presente que **no puedes usar paths para compartir recursos entre el cliente y el servidor**, todo lo que compartan debe ser enviado vía sockets o, en el caso de funciones, clases y código, deberás poner una copia en el cliente y otra en el servidor.

Saludos!

**Comment by kisco99** [comment]
Perfecto.

¿Me podrías explicar en más detalle el uso del "." y de ".." para acceder a un archivo?

**Comment by jmwielandt** [comment]
Hola,

Sí, te mando capturas de la línea de comandos, funciona exactamente igual con python.


<details>
<summary>Consola</summary>

```powershell

PS ~\Avanzada - IIC2233\Syllabus> ls


    Directory: ~\Avanzada - IIC2233\Syllabus

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        15-11-2019    13:05                Actividades
d-----        22-08-2019    16:01                ArchivosImportantes
d-----        24-11-2019    16:34                Ayudantias
d-----        24-11-2019    16:34                Clases
d-----        22-08-2019    16:01                Salas
d-----        24-11-2019    16:34                Tareas
-a----        14-08-2019    13:01            196 .gitignore
-a----        15-11-2019    13:05           6246 README.md

PS ~\Avanzada - IIC2233\Syllabus> ls .


    Directory: ~\Avanzada - IIC2233\Syllabus

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        15-11-2019    13:05                Actividades
d-----        22-08-2019    16:01                ArchivosImportantes
d-----        24-11-2019    16:34                Ayudantias
d-----        24-11-2019    16:34                Clases
d-----        22-08-2019    16:01                Salas
d-----        24-11-2019    16:34                Tareas
-a----        14-08-2019    13:01            196 .gitignore
-a----        15-11-2019    13:05           6246 README.md

PS ~\Avanzada - IIC2233\Syllabus> cd tareas
PS ~\Avanzada - IIC2233\Syllabus\tareas> cd ..
PS ~\Avanzada - IIC2233\Syllabus> cd ./tareas
PS ~\Avanzada - IIC2233\Syllabus\tareas> ls


    Directory: ~\Avanzada - IIC2233\Syllabus\tareas

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        22-08-2019    16:01                Ejemplos Readmes
d-----        14-08-2019    13:01                T00
d-----        24-09-2019    17:13                T01
d-----        30-09-2019    22:13                T02
d-----        25-11-2019    15:47                T03
-a----        02-09-2019    10:24           6085 Descuentos.md
-a----        14-08-2019    13:01           4479 Readme.MD

PS ~\Avanzada - IIC2233\Syllabus\tareas> cd ../salas
PS ~\Avanzada - IIC2233\Syllabus\salas> ls


    Directory: ~\Avanzada - IIC2233\Syllabus\salas

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        22-08-2019    16:01          70740 S1-K200.png
-a----        22-08-2019    16:01          70802 S2-K202.png
-a----        22-08-2019    16:01          70990 S3-K203.png
-a----        22-08-2019    16:01          49889 S4-CS201.png

PS ~\Avanzada - IIC2233\Syllabus\salas>
```
</details>

Si estás en `~/T3/cliente/` y quieres ir a la carpeta `~/T3/sprites`, por ejemplo, tienes que usar `../sprites`; con `..` sales a ~/T3/ y después entras a `sprites`.

`~` es el path de la carpeta de tu usuario, funciona en windows y linux, no sé si en mac. También cuenta como path absoluto pero lo pongo en el ejemplo para que haya algún contexto.

Dime si todavía tienes dudas :D

**Comment by NelsonIMA** [comment]
Hola! Perdón por la pregunta, pero en esta misma línea, podría dejar los archivos amigos.json y usuarios.json en una misma carpeta, por ejemplo en la del servidor? 

Gracias de antemano ^^

![image](https://user-images.githubusercontent.com/42616922/70164458-f557bb00-169f-11ea-992f-236abd3148e6.png)

**Comment by jmwielandt** [comment]
@NelsonIMA 

Te recomiendo mirar mi respuesta a la issue #582, ahí lo respondo.

Saludos.

**Comment by NelsonIMA** [comment]
Gracias! :)
