### ISSUE TITLE
Duda maximo lineas archivos .ui

### ISSUE THREAD

**Issue by jervaal** [IIC2233/syllabus#544]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia
 pregunta de manera explícita utilizando **este formato**]

Hola, tengo una duda sobre el maximo de lineas que puede tener un archivo .ui (hechos con qt designer), ya que muchas ventanas exceden el limite de 400 lineas permitidas, y queria saber si hay un problema con esto, de antemano muchas gracias!

**Comment by tomasrosenberg** [comment]
Hola @jervaal!
No importa si los archivos creados para las interfaces en qt designer, es decir, los ui excedan las 400 líneas. Solamente los archivos que tu creas deben ser menores a ese valor.
Además, te pido que no cierres las _issues_ porque quizás esta duda le pueden servir a otro estudiante :D
Cualquier otra duda quedo atento :)
