### ISSUE TITLE
Lluvia de hamburguesas y temperaturas extremas en fines de semana

### ISSUE THREAD

**Issue by cjmunoz4** [IIC2233/Syllabus#545]
Hola, he leído varias issues en las que se menciona que no hay que considerar los fines de semana ya que no ocurre ningún evento, sin embargo, es posible que ocurra una lluvia de hamburguesas y/o que haya una temperatura extrema algún fin de semana, o me equivoco? Esta es mi duda, ya que, si es que ocurren estos eventos, tendrían repercusión en la simulación y deberían ser considerados. De antemano, gracias por resolver mi duda.

**Comment by cilopez** [comment]
No tendrían repercusión ya que no afectarían a los miembros uc

**Comment by nmaturana97** [comment]
si tendrian, ya que para calcular la proxima lluvia de hamburguesas que ocupa el numero de dias transcurridos desde la ultima temperatura extrema

**Comment by cilopez** [comment]
@nmaturana97 estas en lo cierto, pero me refería a que no les afectaría a las personas , solo a la simulación.

**Comment by nmaturana97** [comment]
ahh okay, entonces tomamos en cuenta que una temperatura extrema puede ocurrir un fin de semana, para el calculo de la lluvia de hamburguesas?

**Comment by cjmunoz4** [comment]
Y si es que hay una lluvia de hamburguesas un día domingo, al otro día tendrán más posibilidades de enfermarse también o no?

**Comment by Jiparavich** [comment]
x3

**Comment by cilopez** [comment]
@nmaturana97  nunca se dice lo contrario, por ende si lo consideras.
@cjmunoz4 considera que no, ya que quizás solo llovieron hamburguesas en el campus :sweat_smile:
