### ISSUE TITLE
Duda sobre .gitignore, archivo utilidades.py

### ISSUE THREAD

**Issue by Nobody-UC** [IIC2233/Syllabus#545]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Al momento de realizar el commit, se solicita agregar el archivo utilidades.py al archivo .gitignore. Este archivo lo utilicé en consultas.py para importar los Namedtuples. ¿Las personas encargadas de revisar tendrán en cuenta esta situación o es responsabilidad nuestra resolverlo de otra manera?

**Comment by AlonsoPlaza** [comment]
Hola, si lo tenemos en cuenta, no te preocupes y solo agregalo al gitignore. Al ser un archivo que no debería ser modificado sería redundante que todos lo subieran.

**Comment by Nobody-UC** [comment]
Genial, muchas gracias por aclararme la duda.
