### ISSUE TITLE
filtro

### ISSUE THREAD

**Issue by mjespinoza** [IIC2233/syllabus#545]
Holaa, estoy tratando de aplicar el filtro, la cosa es que la imagen me queda asi 
![image](https://user-images.githubusercontent.com/42595117/59570943-4978cf80-906d-11e9-9820-ef55f1277ccf.png)

alguien sabe que es lo que puede estar mal? Gracias de antemano.

**Comment by rinorambuena** [comment]
Cómo lo arreglaste? Porque me pasa lo mismo

**Comment by mjespinoza** [comment]
Tenía un error en las medidas de la imagen, las que se agregan en el IHDR

**Comment by ariel-m-s** [comment]
@rinorambuena #627.
