### ISSUE TITLE
Problema haciendo pull

### ISSUE THREAD

**Issue by jarvasquez** [IIC2233/syllabus#545]
Hola!! 

Hoy me cambié de computador y tuve un problema al hacer pull en el repositorio de contenidos.

En mi computador antiguo tenía descargado Drive File Stream para acceder mucho más fácil a mis archivos desde el drive. Al cambiarme de computador me descargué y anclé a la misma cuenta de Drive File Stream donde también tengo mis repositorios del ramo. 

Al intentar hacer git pull para descargar localmente los archivos de la semana 5 me aparece lo siguiente:

![image](https://user-images.githubusercontent.com/68974390/93009039-414e5f00-f552-11ea-8837-9554966f3327.png)

Al parecer funciona bien. Pero los archivos no se descargaron y no aparecen en la carpeta.

![image](https://user-images.githubusercontent.com/68974390/93009052-680c9580-f552-11ea-8a5f-a4faaaab3c3c.png)

Al hacer un git status (no se por qué lo hice, fue más reacción o para saber si habían archivos en la nube) Me aparece esto:

![image](https://user-images.githubusercontent.com/68974390/93009069-98543400-f552-11ea-80d1-341194867f49.png)

Como si tuviera que subir cosas al repositorio que yo nunca les hice un add. Intenté nuevamente hacer pull pero no me deja.

![image](https://user-images.githubusercontent.com/68974390/93009083-c33e8800-f552-11ea-889a-4d91b22076be.png)

Intenté eliminar los archivos del staging area pero no me dejó.

![image](https://user-images.githubusercontent.com/68974390/93009089-e10bed00-f552-11ea-80a5-4fc513f1f30e.png)

¿Qué puedo hacer?

Muchas gracias por su tiempo y disposición, quedo atento. 😊

**Comment by furcelay** [comment]
Hola @jarvasquez !
Yo también uso Drive File Stream para sincronizar todos los documentos de la universidad, y anteriormente tenía repositorios Git incluidos ahí, pero con el tiempo puede generar múltiples problemas, en especial si trabajas en más de un computador/OS, porque Drive sincroniza los datos por su cuenta y comienza a tener conflictos con git 😓, además a veces Drive reescribe los archivos y git considera como que el archivo tuvo un cambio.
En base a mi experiencia te recomiendo no tener tu repositorio local dentro de Drive, lo mejor es tenerlo por separado para que se sincronice únicamente con comandos git, y si quieres puedes hacer un backup dentro de Drive. 
Lo mejor es que clones nuevamente tu repositorio en un nuevo directorio y transfieras manualmente los archivos que no hayas podido actualizar.

Espero que eso responda tus dudas :smile:

**Comment by jarvasquez** [comment]
Perfectoo!! Muchas gracias!!

**Comment by jarvasquez** [comment]
Mmmm...

Traté de clonar mi repositorio en el computador y se ha demorado bastante. ¿Qué puedo hacer?

Sale esto,

![image](https://user-images.githubusercontent.com/68974390/93101404-9e483300-f680-11ea-8e3b-859b66c35e5d.png)

**Comment by jarvasquez** [comment]
Falsa alarma, era porque GitHub me estaba pidiendo mis datos de usuario y cambiando de pestañas no me había aparecido en pantalla.

Gracias y perdón por las molestias!!

**Comment by furcelay** [comment]
No hay problema, que bueno que lograste solucionarlo 😄
