### ISSUE TITLE
Décimas AC09

### ISSUE THREAD

**Issue by emilianomm** [IIC2233/syllabus#545]
Hola

No me queda claro si en la última actualización vía hoja de cálculo que enviaron de las notas están consideradas las décimas de la AC09, ya que tengo menos décimas de las que debería en caso de considerarla. Espero sirva para aclarar la duda si alguien mas la tiene.

Saludos

**Comment by entamburini** [comment]
Hola @emilianomm!

Para ver las décimas que han sido consideradas hasta ahora, puedes ver la hoja que está al lado en la [misma hoja de notas](https://docs.google.com/spreadsheets/d/1uCscFkTf8iTBrdsFHrWAS4I5Gu1B_IZNKQ7OBk1ukqM/edit#gid=28307970). 

Para contestar a tu pregunta, aún no están consideradas las décimas de la AC09 :wink: 

Que estés bien! :v:

**Comment by emilianomm** [comment]
Muchas gracias, quedo atento!
