### ISSUE TITLE
Hay que añadir en parametros las rutas de imagenes que añadi con designer?

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#545]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Hay que añadir en parametros las rutas de imagenes o las dimensiones de los labels que cree con designer? 

Por ejemplo: los mapas de la escuela o krustyland no creo que sea necesario porque no los voy a modificar, pero aun estoy con la duda.

saludos

**Comment by catalina-arcila** [comment]
Hola @Ignacioislae, te recomiendo que los archivos *.ui*  los dejes como los genera Designer 😄. Suerte en la tarea!
