### ISSUE TITLE
mousePressEvent y keyPressEvent

### ISSUE THREAD

**Issue by monicabelen** [IIC2233/Syllabus#545]
Cuando ejecuto event.pos() me lanza una posición incorrecta.. Cómo puedo solucionar eso?
Además, uso la función keyPressEvent pero cuando apreto una tecla no funciona.. :(

**Comment by hanavarrete** [comment]
debes activar en el label o widget la lectura de posición. El comando es
algo como setMouseTracking(True)
No recuerdo el nombre exacto para pyqt5, pero busca eso en google. Espero
que te sirva! saludos :)

**Comment by akaminetzkyp** [comment]
Hay veces que la posición retornada es con respecto a tu pantalla. Para convertirla a las coordenadas relativas a un `QWidget` puedes usar `mapFromGlobal`. Con respecto al problema del `keyPressEvent`, fíjate que sea un método de tu `MainWindow`.

Saludos!

**Comment by monicabelen** [comment]
Uso mapFromGlobal como un método dentro de mi QWidget?

**Comment by hanavarrete** [comment]
[Acá](http://nullege.com/codes/search/PyQt5.QtWidgets.QWidget.setMouseTracking) encontré a lo que me refería yo. Si no es esa la solución prueba lo que dice @akaminetzkyp y nos cuentas como te va 👀

**Comment by monicabelen** [comment]
Me resultó perfect! Muchas gracias! :D
