### ISSUE TITLE
Es necesario agregar en parametros una constante creada para una función especial propia

### ISSUE THREAD

**Issue by francisca0308** [IIC2233/syllabus#545]
Creo que es muy específica mi pregunta, pero tengo una función que valida la respuesta dada por el usuario ante cualquier menu. Esta recibe la opcion dada por el usuario y un int _"n"_ que representa la cantidad de opciones que acepta como válidas (en el caso del menú de inicio son 5: [1] menu de cuidar criaturas, [2] menu dcc, [3] pasar de día, [4] volver o [5] salir). En este caso debo crear el parámetro: CANTIDAD_OPCIONES_MENU_INICIO?

Entiendo que la función de este file es poder cambiar el parámetro sin necesidad de buscarlo en el código cada vez que aparece. Esto tiene mucha lógica para parámetros como SICKLES_INICIALES, pero en el caso de mi int _"n"_ depende del menú que se pide la opción y si ese menú cambia, entonces hay que cambiar el código de todas formas, por lo que no creo que sea necesario crear un parámetro para esta constante, pero no estoy segura de ello.

**Comment by matiasmasjuan** [comment]
Hola @francisca0308 !

Uno de los **objetivos** de esta **tarea** es que ustedes puedan ser capaces de **reconocer** lo que es necesario considerar como **parámetros** y lo que **no**. Por lo tanto, si consideras que la **existencia** de un **parámetro** que podrías **modificar** **implicaría** consigo una **modificación extra** en tu código, podrás intuir si es pertinente seguir considerandolo como **parámetro** o no.

Espero haberte ayudado y mucho éxito con la tarea! 😄
