### ISSUE TITLE
Darle forma a un boton

### ISSUE THREAD

**Issue by maxjosecr** [IIC2233/Syllabus#546]
Hola, estoy intentado darle forma a mi botón y hago boton.setStyleSheet("border-image: url(path imagen)").
Resulta que me queda el "botón" con la forma dada, pero no le puedo hacer click, queda como si fuera un label. Que se puede hacer?

**Comment by iqacevedo** [comment]
Hola,
Donde tienes definido tu botón? en la ventana principal? en un widget?, porque acabo de probar cambiándole la forma a un botón en una `QMainWindow` y me funciono perfecto. Por cambiarle la forma te refieres a ponerle una imagen de fondo verdad?, o a que el botón pase de ser cuadrado a circular?.

Saludos !

**Comment by maxjosecr** [comment]
El boton esta en la QMainWindow, me refiero a lo segundo, a que pase a ser circular (o la forma de la imagen que le pongo), no es agregarle un icono al boton sino que asignarle eso boton.setStyleSheet("border-image: url(path imagen)").

**Comment by iqacevedo** [comment]
Puedes revisar si hay otro label que este sobre tu botón (que no tenga imagen) que provoque tu problema. Si ves el [siguiente código](http://pythonprogramminglanguage.com/pyqt5-button/) y le agregas una linea cambiándole la forma como indicas que lo estas haciendo `(boton.setStyleSheet("border-image: url(path imagen)")),` verás que se puede seguir presionando sin problemas, por lo que te aconsejo revisar bien que otras cosas has implementado en tu tarea que podrían hacer que el botón se deje de presionar.
