### ISSUE TITLE
Duda con KeyPressEvent

### ISSUE THREAD

**Issue by sebamoralesm147** [IIC2233/syllabus#546]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo un problema con el método KeyPressEvent, cree la ventana desde designer y se ejecuta de buena manera, pero al apretar las teclas no las reconoce (no pasa nada), revise las otras issues que hay de este tema, implementando las recomendaciones que daban, pero sigue sin funcionar y no se que es lo que podría causar esto.
(Actualice el repositorio y el problema se da en ventana_preparacion)
 De antemano muchas gracias :)

**Comment by clementevalladares** [comment]
Hola @sebamoralesm147, te contesto hoy ya que es una duda corta, el problema es que lo tienes definido como KeyPressEvent en lugar de keyPressEvent, la primera letra debe ser minúscula!

**Comment by sebamoralesm147** [comment]
Buuu que pavo jajajajja muchas gracias, ahora si funciona :)
