### ISSUE TITLE
Duda sobre envío de mensajes T03 

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#546]
Luego de llevar el mensaje al formato que pide el enunciado, este se debe enviar todo de una al servidor, o podemos ir enviándolo por partes? Es decir, primero enviar el largo total del mensaje, luego el primer chunk, segundo, tercero, etc...
O esto simplemente queda a nuestro criterio?

Con respecto a este tema, también me surge la duda de por qué se debe anteponer el número del bloque a cada chunk que enviamos (lo de big endian). Consdirando que estamos usando TCP, y que todos los datos deberían llegar en orden al receptor, cual es el fin de agregar el número del bloque a cada parte del mensaje?

**Comment by DCCollao** [comment]
Hola! La idea de separar el mensaje en pedazos más pequeños es enviarlos por parte, al igual que ponerles números según su orden.

Tal como indicas, dado que utilizarán protocolo TCP los mensajes llegarán ordenados siempre, por lo que desde un punto de vista práctico, no sería necesario agregar el orden de envío para luego reordenarlos al ser recibidos. Sin embargo, esta parte la pedimos para que aprendan una forma de estructurar mensajes, además de pasar enteros a bytes teniendo en cuenta las variantes little/big endian.

Éxito!

**Comment by FelipeA7** [comment]
Gracias!
Otra duda, el enunciado dice que si el último chunk tiene menos de 124 bytes, entonces hay que rellenar con ceros. No le encuentro mucho la lógica a esto, puesto que intenté leer los datos sin rellenar con ceros y todo funciona sin problemas. Lo de agregar ceros como que lo veo como trabajo extra. Por qué se debe hacer esto?

**Comment by JuaniAndres** [comment]
Hola en el caso de codificar el mensaje según lo pedido y enviarlo todo junto para luego leerlo por partes al recibirlo esto traería  un descuento o es valido también ?

**Comment by DCCollao** [comment]
@FelipeA7 El objetivo de llenar con ceros el último chunk del mensaje, es evitar un error de lectura del mensaje que puede suceder al no llenar con ceros.
Por ejemplo, si desde dos clientes envías mensajes de 10 bytes, y los tratas de leer de a 15 bytes, el programa leerá los 10 bytes del primer cliente y además los 5 primeros bytes del segundo cliente, por lo que al imprimir primer mensaje recibido, contendrá parte del segundo mensaje enviado, mientras que al imprimir el segundo mensaje recibido, estará truncado.

@JuaniAndres tendría descuento en la parte de manejo de bytes en la distribución de puntajes, pues en el enunciado se indica que debe ser dividido en partes para enviarse :(

Quedo atento a cualquier duda!

**Comment by JuaniAndres** [comment]
@DCCollao entonces para clarificar la forma correcta envió 4 bytes del largo después 4 bytes del orden luego el bloque de 124 o es todo lo anterior en bloques de 124?

**Comment by jmwielandt** [comment]
@JuaniAndres Hola,

Debes mandar 4 bytes indicando el largo de tu mensaje y luego bloques de **128 bytes** que se dividen en: 

- 4 bytes con el número de bloque
- 124 bytes con el trozo del mensaje correspondiente

Saludos.

**Comment by JuaniAndres** [comment]
ya muchas gracias @DCCollao  y @jmwielandt  me quedo todo claro ahora

**Comment by JuaniAndres** [comment]
@DCCollao @jmwielandt  una duda corta se pueden enviar bytearray en el mensaje?

**Comment by jmwielandt** [comment]
@JuaniAndres el mensaje puede ser lo que tú quieras, lo único que te definimos es que lo que desees enviar debe ser **particionado** y ponerle un cierto **formato** (en _bytes_):

![image](https://user-images.githubusercontent.com/37153467/69918631-5b9bce00-1453-11ea-999f-170b46e25f09.png)


Saludos!

**Comment by JuaniAndres** [comment]
Ok gracias
