### ISSUE TITLE
Duda en crear sala y juego

### ISSUE THREAD

**Issue by fplois** [IIC2233/syllabus#546]
Hola, queria saber como seria un proceso correcto en la creación de la sala y el juego.
Mi clase Sala y juego (la parte de lógica de estas) debería ser creada en el archivo donde tengo la clase servidor o puede estar eso aparte?.
Tengo aparte de eso, las clases ventana_juego y ventana_sala que se encarga de la interfaz de estas y que se encuentran en la carpeta cliente.
Saludos !.

**Comment by jeschuwirth** [comment]
Hola!

El cliente debe poseer un frontend que le permita al usuario conectarse, ver las salas y el juego, también debe poseer un backend que maneje toda la conexión con el servidor, es decir, recibir los cambios realizados por otros usuarios (mensajes del chat o jugadas en el tablero) y mandarle esa información al front-end, y además recibir la información del frontend (como jugadas del jugador o la información de la cuenta al conectarse) y enviársela de manera correcta al servidor. 

El servidor por otro lado no posee frontend por lo que toda la información que posee es un gran back-end con los usuarios, las salas y los juegos.

Si tu pregunta va más a la modularización del programa, entonces te recomiendo separar tus clases según su utilidad. Que tu archivo frontend.py tenga sólo lo que es completamente necesario y dejar la definición de clases como Chat o VentanaJuego en un archivo aparte e importar de ahí estas clases.

Recuerda que modularizar es una muy buena practica, separar tus archivos por clases te permite debuggear de mejor manera (ya que python te avisa cual fue el archivo donde se cayó el programa) y nos permite a los ayudantes corregir más eficientemente tu tarea por la misma razón.

Ojalá haya respondido tu duda

Suerte en la tarea !

**Comment by fplois** [comment]
buena, esa era mi duda muchas gracias :)
