### ISSUE TITLE
Repeticion issue #506

### ISSUE THREAD

**Issue by juanriveraf** [IIC2233/Syllabus#546]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Escribi una issue (#506) el viernes pasado y fue en parte resuelta por un compañero, pero nunca tuve una respuesta de un ayudante o profesor. Queria saber si es posible que se vuelva a revisar. Muchas gracias!

**Comment by Vicente1824** [comment]
¡Hola @juanriveraf 😀! ¡Lamento la demora, estoy respondiendo ahora tu issue!
