### ISSUE TITLE
visualizar criaturas cargadas ya escapadas

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#546]
Hola, cómo sabe el magizoologo que alguna de sus criaturas anda de fugitiva? Lo digo porque en la sección de Menú DCC > Mostrar estado, no se pide imprimir el `estado_esc` de las criaturas. Entonces como experiencia de usuario, si recien inicia sesión y quiere ponerse al día con sus criaturas, cómo puede saber esto? Sería mejor que si imprimiera esto o no?

**Comment by mpsubiabre** [comment]
Hola @dlmed!

Para saber las criaturas escapadas debe ingresar al menu Cuidar DCCriaturas en la opción Recuperar DCCriatura, recuerda que aquí es donde se deben mostrar las DCriaturas que se han escapado :)

**Comment by dlmed** [comment]
ah pos si, gracias!
