### ISSUE TITLE
Sickles y nivel de aprobación de tipo int

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#547]
Hola, siempre los sickles y nivel de aprobación van a ser números enteros? Lo dijo, para saber si tengo que pasar a entero o no el pago del DCC antes de pasárselo al Mago. Lo mismo con el nivel de aprobación. Hasta el momento estoy asumiendo que lo son, ya que en la base de datos aparece que sickles es `int`.

**Comment by moquezada** [comment]
Hola @dlmed :D 

Tal como dices, tanto el nivel de aprobación como la cantidad de sickles son del tipo `int`. No tan solo se menciona en la base de datos entregada, sino que también se menciona explícitamente en las secciones donde se describe cada elemento:

![aprobacion](https://user-images.githubusercontent.com/43896576/79627008-d6177280-8102-11ea-8050-f01faa7d923c.PNG)
![sickles](https://user-images.githubusercontent.com/43896576/79627009-d6b00900-8102-11ea-8648-4d9dc72cf2e5.PNG)

Por lo tanto, debes trabajar con ellos como valores de tipo `int` :)

Suerte con la tarea! 😄
