### ISSUE TITLE
Editar el logo

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#547]
Hola puedo editar el logo de la tarea es que soy un poco detallista y esa linea negra abajo del pingüino me mata jaja

**Comment by entamburini** [comment]
Hola @JuaniAndres,

Por supuesto 😊!! (A mí también me mata)

**Comment by JuaniAndres** [comment]
ok gracias otra pregunta lo subo en una carpeta distinta?

**Comment by gatochico** [comment]
Recuerda que la carpeta `sprites` debe ser ignorada al momento de subir tu tarea, por lo que sí, cualquier sprite o recurso adicional que quieres se suba con tu tarea debe ir fuera de cualquier carpeta  a ignorar. :tada:

**Comment by JuaniAndres** [comment]
ok gracias
