### ISSUE TITLE
Test 10 Ganancias Producidadas

### ISSUE THREAD

**Issue by lfcpardo** [IIC2233/Syllabus#547]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

**Comment by wintermelyn** [comment]
Holala @lfcpardo!

El problema es que aun estas manejando los datos en estructuras de tipo listas con `list()`. Te recomiendo trabajar directamente con los generadores y utilizar un diccionario para acceder directamente a los precios en lugar de usar filter o hacer multiples pasadas sobre los datos.

**Comment by lfcpardo** [comment]
Muchas gracias !! ahí funcionó :)
