### ISSUE TITLE
tasa putrefaccion

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#547]
hola! me puse a pensar y si `putrefacción(t)=1-e**(-t/tasa)`, entonces entre mas adelante se esté en el día, menor putrefacción se tendrá 🤔 
por ejemplo:
<img width="153" alt="captura de pantalla 2017-10-17 a la s 16 15 50" src="https://user-images.githubusercontent.com/26392931/31684532-78b272ba-b356-11e7-8e5e-a1c3eaafe10f.png">

donde 10 y 100 son el tiempo t en minutos

**Comment by fgbruna** [comment]
:point_up: debería `ser 1 - e**(t/tasa)`

**Comment by fgbruna** [comment]
Ahí mismo en la imagen que pusiste se puede ver que la putrefacción subió entre 10 unidades de tiempo y 100 unidades de tiempo

**Comment by dmolina2** [comment]
Hola,
Ocurre que como el tiempo se toma en minutos y además hay que contabilizar desde las 8:00 am dan valores exageradamente altos desde el primer instante.
Me explico con un ejemplo:
Una persona compra a las 11:00 un snack,  la putrefacción del porducto, por ejemplo, de tasa 45 sería entonces   1  - exp^(-180/45), esto daría 0.98.... De ahí en adelante lo que hara la putrefacción sera subir en el tiempo y ,por ende, la calidad es extremadamente baja.
¿Esta esto correcto? , ya que las personas se enferman con mucha frecuencia.

Muchas Gracias

**Comment by Jiparavich** [comment]
Up?

**Comment by Arcoirisky** [comment]
Hola~
Tu forma está bien ya que así se definió el parámetro. Cuando se corrija, se espera variar los parámetros definidos es "variables.py" para saber cómo se comporta la simulación con otros parámetros :D :D
