### ISSUE TITLE
Interaccion atracciones y colas.

### ISSUE THREAD

**Issue by mlvinay** [IIC2233/Syllabus#547]
Digamos que una atracción tiene una capacidad de 8 personas. El primer grupo en cola es de 7 personas (1 adulto y 6 niños). El segundo grupo de es 3 personas. Y digamos que mas tarde en la cola, bieeen mas tarde hay un forever alone de adulto solo en la cola.

La pregunta es: Cuando la atraccion corra, debe ser persona a persona, o grupo a grupo?  En el caso anterior, debe correr con solo las 7 personas del primer grupo ya que separaria al segundo grupo? O simplemente separa a los grupos indiscriminadamente? O mas aun, intenta buscar algun grupo que calze perfectamente?

**Comment by monicabelen** [comment]
Hola! En el enunciado no se menciona de forma explícita que los grupo no se puedan separar, sin embargo, en general hacen todo juntos. Por lo tanto, podrías asumir que no se separan y dejar el cupo sin llenar. Otra opción es buscar a alguien o a un grupo que calce..

**Comment by michimalonko** [comment]
Yo preferi separar los grupos, ya que hay grupos de incluso 21 integrantes y esto genera problema con elegir atracciones  de menor capacidad al tamaño del grupo, y se dan algunas situaciones poco ajenas a la realidad como tener un juego para 15 personas andando con 1 y un grupo de 16 esperando, pero supongo que todo esto es una eleccion personal, si lo modelas sin cortar los grupos recuerda entonces filtrar las atracciones por capacidad sino tendras grupos atascado en las atracciones por superar su capacidad
