### ISSUE TITLE
Informacion de jugadores

### ISSUE THREAD

**Issue by MatiAedo** [IIC2233/syllabus#547]
Hola, 
Al crear usuarios y contraseñas, esta información la guarda solo el server, puedo crear un .txt para guardar esta información? O debe ir en el archivo parametros.json?

**Comment by jeschuwirth** [comment]
Saludos !

Como las cuentas de los usuarios no son parámetros del programa, **no** van en el archivo parametros.json, sino que se debe crear un archivo aparte que guarde la información. El tipo de archivo queda a tu criterio, por lo que puedes utilizar lo que más te acomode.

Recuerda que si quieres hacer el bonus **Contraseñas (10.4)**, la contraseña la tienes que guardar codificada en el archivo.

Suerte en la tarea!
