### ISSUE TITLE
crear Qlabels fuera del __init__

### ISSUE THREAD

**Issue by rfenzo** [IIC2233/Syllabus#547]
Quiero crear los qlables correspondientes a los subditos una vez que el init del Qwidget del juego ya se inicializó, puesto que debo ir agregandolos constantemente, pero no logro hacer que se muestren. Debo crear de forma anticipada los qlabels en el init para luego solo seetearles una imagen a medida que aparecen los subditos?

En caso de que no me haya explicado bien, aqui dejo un ejemplo del problema.

```
import sys
from PyQt5.QtWidgets import QApplication, QWidget, QLabel


class test(QWidget):

    def __init__(self):
        super().__init__()

        x = QLabel('esto si se muestra', self)
        self.setGeometry(20, 20, 200, 200)

    def addqlabel(self, text):
        self.y = QLabel(text,self)
        self.y.move(40, 40)


if __name__ == '__main__':
    app = QApplication([])
    form = test()
    form.show()
    form.addqlabel('esto no se muestra')     #AQUI LLAMO A LA FUNCION
    sys.exit(app.exec_())
```

Lo que busco hacer es llamar a la funcion addqlabel desde el backend cuado se crea un subdito, pero la imagen del nuevo subdito no se muestra.

**Comment by hanavarrete** [comment]
Si no me equivoco es porque no estás instanciando el Qlabel en ningún lado. Puedes probar con eso? saludos!

**Comment by rfenzo** [comment]
No entiendo a lo que te refieres con instanciarlo :/

**Comment by hanavarrete** [comment]
Antes de que editaras estabas haciendo Qlabel(text) solamente, pero ahora lo pusiste correctamente jajaj,

**Comment by rfenzo** [comment]
aah, sisi, pero igual no me funciona.

**Comment by hanavarrete** [comment]
debería funcionar si agregas un self.y.show()

**Comment by hanavarrete** [comment]
además, entregale solo el self, eso recibe como primer argumento. Avísame si te funcionó! Saludos

**Comment by rfenzo** [comment]
ahí funcionó, gracias!
