### ISSUE TITLE
Resultados.txt

### ISSUE THREAD

**Issue by cnillanes** [IIC2233/syllabus#547]
Holaa! No me queda claro si los resultados que se van guardando en el archivo.txt debo imprimirlos en consola en algún momento/ darle la opcion al usuario que pida acceder a ellos o no y solo me preocupo de imprimir el estado cuando corresponda?

**Comment by vicentevegaulloa** [comment]
Hola @cnillanes !

El estado es distinto de resultados.txt. El primero sí debes mostrarlo en pantalla, mientras que el otro es un registro de los ganadores por día en cada competencia, que debe escribirse en un archivo txt pero no es necesario mostrarlo.

Espero haber resuleto tu duda 😄
