### ISSUE TITLE
Stock y cambio de precios

### ISSUE THREAD

**Issue by jerosalazar** [IIC2233/Syllabus#548]
Hola, en el enunciado se dice:
>Como simplificación, en la simulación no se maneja un stock independiente por cada producto, sino un stock general para cada vendedor. En otras palabras, o bien el vendedor tiene todos sus productos disponibles, o bien no tiene ninguno.

Se dice también que los precios de un producto cambian mes a mes si se acaba el stock de ese producto  o si no se vende ese producto N veces en el mes.
Con respecto al punto de si se acaba el stock, ya que el stock es general para el vendedor, si se acaba el stock de un producto, se acaba el de todos. Con lo anterior entiendo que eso generaría un cambio en el precio para todos los productos que ofrece el vendedor en cuestión. En otras palabras, si se le acaba el stock 10 veces en el mes, cada producto aumentaría su precio en la proporción equivalente a los 10. ¿Es esto correcto o hay algo que no estoy viendo?, lo digo porque encuentro extraño que el precio aumente para todos los productos de igual forma

**Comment by fgbruna** [comment]
Me sumo a esta duda

**Comment by fdominguezclaro** [comment]
Buena!! 
Como no sale especificado en el enunciado pueden decidirlo ustedes. No olvides especificarlo en tu Readme.

Saludos!

**Comment by cjmunoz4** [comment]
Y para que baje el precio de un producto, tiene que cumplirse que ese producto en específico no se venda en algún día del mes? O, como el stock es en general, para que el precio de un producto baje no tiene que venderse ningún producto en un día del mes y, por ende, bajarían el precio de todos los productos?
Mejor dicho:
Hay que fijarse en específico si se vende un producto o en general si se vendió algún producto del puesto en el día?

**Comment by fdominguezclaro** [comment]
Hola, 
En ese caso debes revisar si se vendió algún producto en específico y disminuir el precio de dicho producto en caso de ser necesario. 
Saludos!

**Comment by Jiparavich** [comment]
Hola!, sigo sin entender, la parte de "En otras palabras, o bien el vendedor tiene todos sus productos disponibles, o bien no tiene ninguno." , esto quiere decir, que si el resultado del randint(alpha_stock, beta_stock) es menor a la cantidad de productos que tiene el vendedor, entonces simplemente no venderá ese día ?  o estoy entiendo mal?

**Comment by Jiparavich** [comment]
O tengo que seleccionar, "randint(alpha_stock, beta_stock)"  productos del total de productos que el vendedor esta vendiendo. No entiendo bien lo del stock general, ya que estamos generalizando a los productos, siendo que sus precios varían y por tanto eso incidirá en las estadísticas.

**Comment by jerosalazar** [comment]
@Jiparavich lo que entendí yo es lo siguiente:
Cada día obtienes el "stock diario" de cada vendedor como randint(alpha, beta).
El resultado del punto 1 (que llamaré SD) será una cuenta general. Entonces, si SD = 10 y el vendedor tiene para ofrecer los productos A y B, el stock funciona de la siguiente manera. A comienzo del día el stock tanto de A como de B es 10, luego, si una persona compra un producto A, por ejemplo, el stock tanto de A como de B baja a 9. Al final cantidad_de_A + cantidad_de_B = stock_actual (1). Esto obviamente no pasa en la vida real pero es para simplificar y no tener stocks individuales de cada producto.
Finalmente, a lo que aludía yo con mi pregunta original es que si el stock actual es 1, llega una persona y compra una unidad del producto A, el stock actual pasa a ser 0 y, por (1), el stock de A y de B es 0. Esto genera que si a un vendedor se acaba el stock de un producto, se le acaba el stock de todos. Por lo anterior, cada vez que se reajusten los precios a final de mes, el precio de cada producto bajará un porcentaje X (diferente para cada producto, por como se explica en enunciado) y subirá un porcentaje Y (en esta caso, este porcentaje será el mismo para todos los productos del vendedor, ya que la cantidad de veces que se acaba el stock en un mes es la misma para cada producto).
Espero que hayas entendido 😊

**Comment by Jiparavich** [comment]
@jerosalazar Mmmm es bastante ilógico, pero entiendo a la perfección tu explicación, Muchas Gracias!!!!
