### ISSUE TITLE
Propuesto Networking

### ISSUE THREAD

**Issue by oscars810** [IIC2233/syllabus#548]
Hola,

Solo quería saber si van a subir la solución del ejercicio propuesto para esta semana antes de la actividad de mañana. 

Gracias.

**Comment by entamburini** [comment]
Hola @oscars810,

La gracia de los ejercicios propuestos es justamente que no tienen respuesta :sweat_smile:. Por suerte, la naturaleza de este ramo es que para saber si algo está bueno, basta con programarlo y probarlo :smile: 

Suerte! :v:
