### ISSUE TITLE
Problemas al modularizar

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2233/syllabus#548]
Hola! tengo una clase MenuDeInicio y MenuPrincipal, que hereda de la primera.
mi tema es que MenuPricipal es muy larga, entonces al separar estos en 2 archivos, no me deja importarlos los unos a los otros ya que estos en algunos momentos se llaman.

Mi problema es que necesito separarlos, porque sino me pasaré de las 400 líneas en un archivo, lo cual vi que descuenta de una 5 décimas :(

Gracias!

**Comment by vicentevegaulloa** [comment]
Hola @pabloalvarez67 !

Lo que tienes es una dependencia circular. Mi recomendación es que si puedes, dividas tu código en funciones más pequeñas, de manera que puedas modularizar estas y empezar a acortar tu código. Te dejo [esta](#208 ) issue donde se toca más en detalle lo que son las dependencias circulares. 

Espero haberte ayudado 😄

**Comment by pabloalvarez67** [comment]
Perfecto! veré bien que puedo hacer. Una duda, ese descuento de 5 décimas es por cada archivo sobre 400 líneas? o con tener ya uno de 400 líneas ya se deja fijado en las -5 décimas?

**Comment by vicentevegaulloa** [comment]
Lo segundo 👍
