### ISSUE TITLE
Tiempo máximo de espera en una atracción

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#548]
Hola según entiendo, lo que va pasando es que se van gerando eventos en los que clientes llegan a la cola de una atracción , la atraccion parte en un tiempo determinado y a ella se suben todos los clientes que quepan por orden de llegada .
Pero en el caso que queden puestos sin llenarse como entra aqui el tiempo máximo que la atracción espera para partir cuando no está copada , si en teoría ya entraron todos los que podían y los próximos clientes que entrarán a la  próxima atracción son eventos que se crearan después.

**Comment by leolivares** [comment]
@sjkinast Hola!
No se si entiendo bien tu pregunta.
Creo que quieres saber si la atracción debería partir cuando no hay nadie más en la cola pero existen puestos libres. Si esa es tu pregunta, entonces si, si no hay nadie más en la cola, y ya existen personas esperando para partir, entonces puede iniciar la atracción. (Esta podría ser una opción para modelarlo).
También podrías agregar un tiempo extra, en donde se espere por otras personas.
Queda a tu criterio, pero agrégalo como un supuesto
Saludos!

**Comment by sjkinast** [comment]
Hola!
Mi pregunta era en verdad si yo puedo asumir que una vez que estoy en el evento de que la atracción empieze y ella no esta llena ,dado que no pueden ocurrir eventos simultaneos puedo asumir que como que no alcanso a llegar nadie mas simplemente asumir como que se espero y nadie llego por ende solo retraso el tiempo en que la atraccion partio en el máximo tiempo de espera.

**Comment by leolivares** [comment]
Esto sale en el enunciado, creo que es a lo que te refieres.

![image](https://user-images.githubusercontent.com/26394273/40442754-85acf124-5e92-11e8-8877-ae87471eae09.png)

**Comment by sjkinast** [comment]
Justo eso es lo que no entendía, pero creo que ahora entendi la lógica. El tiempo máximo entre clientes sería para ver  que luego de que una vuelta de la atracción termina, ver el máximo tiempo que la atracción esperará para partir, pero si la atracción cumple su capacidad antes de este tiempo, partira  con toda su capacidad.
Esta bien eso?

**Comment by leolivares** [comment]
@sjkinast Sería como el tiempo máximo que espera la atracción para partir desde que llega el primer cliente. Si es que se llena antes, entonces parte antes.
Espero haber aclarado tu duda.
