### ISSUE TITLE
Pasar al dia siguiente - criaturas escapadas y enfermas

### ISSUE THREAD

**Issue by FelipeSrojas96** [IIC2233/syllabus#548]
Hola, cuando tengo que imprimir las criaturas enfermas y escapadas, tienen que ser las que se escaparon y enfermaron en ese dia solamente o tienen que ser todas? 

Y respecto a las criaturas hambrientas lo mismo, tienen que ser todas las criaturas hambrientas o las que pasaron a tener hambre ese dia?

**Comment by moquezada** [comment]
Hola @FelipeSrojas96,

Tu duda ya fue respondida en las issues #465 y #467. Recuerda utilizar el buscador para poder encontrar respuestas a tus dudas antes de hacer una nueva issue.

Saludos!
