### ISSUE TITLE
Ingreso sala partida iniciada

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#548]
Que pasa si la partida ya esta iniciada? Se puede o no se puede ingresar?

**Comment by jeschuwirth** [comment]
Hola!

No se especifica en el enunciado, pero se entiende que si una partida ya esta iniciada, entonces no se puede ingresar a ella, sólo pueden jugar aquellos jugadores que se encontraban en la sala durante la **preparación de la partida(s 5.3.2)**, luego de que el contador llegue a 0 no se permite e ingreso a ningún otro jugador.

Como no está explícito en el enunciado, si lo haces de otro modo recuerda comentarlo en tu archivo Readme.

Suerte en la tarea!
