### ISSUE TITLE
Ayuda Eficiencia Test 10

### ISSUE THREAD

**Issue by duranjulio2004** [IIC2233/Syllabus#549]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Estoy atascado en la funcion 10 ganancia_producidas_en_los_pedidos. He intentado hacerlo usando "solo generadores" y tambien he intentado usando whiles y otras variables. El problema es que intentando usar solo generadores, el solo hecho de usar .product me crashea el pc en el test con archivos L. Y luego usando whiles tampoco logro pasar de los tamanos L para delante. Si es posible me gustaria alguna guia sobre que deberia intentar porfavor. 

Los archivos M y S me funcionan bien

**Comment by kbetelgeuse** [comment]
Hola @duranjulio2004 !
En efecto, utilizar `product` con bases de datos muy grandes como las de tamaño L y XL puede hacer que el computador tenga que procesar demasiado dada la cantidad de combinaciones que se pueden generar.

Las recomendaciones o sugerencias para desarrollar la consulta (porque esta consulta se puede completar de muchas maneras) podrían ser las mismas que se describieron en la issue #507. Te recomiendo tomar en cuenta esas sugerencias como primer paso. Si es que sigues teniendo problemas con la consulta luego de intentar lo anterior, te pediría que subas a tu repositorio el desarrollo de tu tarea para poder guiarte y ayudarte con más detalle 😉

Saludos!

**Comment by dani-oviedo** [comment]
hola tengo una duda respecto a esto porque por ejemplo en código no ocupo cycle , solo generadores, y aún asi no entran los case de L , entonces no se que podría ser, llevo mucho rato ya que solo me falta este, tengo subido a mi repositorio mi ultima actualización , muchas gracias por la respuesta de antemano.

**Comment by kbetelgeuse** [comment]
Hola @dani-oviedo !

Estuve revisando tu código y noté que hay dos secciones en este que hacen que el programa tenga un elevado tiempo de ejecución. La primera parte sería el procesamiento que se hace de los datos para definir la variable `contenido_y_pizza` y la segunda parte en el procesamiento de los datos para definir la variable `ganancia`.

Mis recomendaciones para evitar estos altos tiempos de demora serían que; como primer paso, encuentres una manera alternativa de obtener las ganancias asociadas a cada pizza pedida del generador `contenido_pedidos`, ya que ni siquiera alcanza a definirse la variable `contenido_y_pizza` cuando el tiempo del testcase se acaba; y que, como segundo paso, encuentres otra forma de sumar todas las ganancias asociadas a las pizzas pedidas en un mismo pedido (tampoco alcanza a definirse esta variable cuando termina el tiempo del testcase, considerando que ya está solucionado lo de la variable `contenido_y_pizza`). Luego de arreglar estos dos puntos todos los testcases se pasan sin problemas. Si quieres hacer más rápidas las secciones del código que mencioné podrías ver las sugerencias que dejé en la issue #507: estas te pueden ayudar con ello :)
