### ISSUE TITLE
¿Cuándo se debe calcular el puntaje y vida jugador == vida personaje?

### ISSUE THREAD

**Issue by Isi677** [IIC2233/syllabus#549]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, me surgió una duda respecto al cuando debemos calcular y presentar nuestro puntaje en la interfaz. De acuerdo al este issue: [https://github.com/IIC2233/syllabus/issues/504](url), el puntaje se calcula al finalizar una ronda, mostrándose este en la interfaz de la ventana post-ronda y, de seguir jugando, en las ventanas de preparación y juego. 
Ahora bien, según este otro issue: [https://github.com/IIC2233/syllabus/issues/535](url), el puntaje debe ser actualizado y calculado constatemente durante una ronda de acuerdo a los objetos que se atrapen durante esta y la vida del personaje. 
Respecto a lo anterior, no se por cual de las dos instrucciones guiarme: si actualizar durante la ronda el puntaje, calculando cada vez que se atrape un objeto, o calculando solo al final de la ronda.

Sobre vida, mi duda está en que en el enunciado se habla de "vida del jugador" y "vida del personaje". 
No se si se refiere a que la vida del jugador en una ronda es igual a la vida del personaje, es decir, si la vida del personaje seleccionado, por ejemplo, Homero, cae a 0 en la partida, el jugador pierde automáticamente aún cuando Lisa podría tener su vida completa para otra ronda. 
Si la vida de jugador y vida de personaje son diferentes ¿entonces la vida del jugador es básicamente la "suma" de las vida disponible que tiene a partir de todos los personajes posible?

**Comment by mmunoz12** [comment]
Hola @Isi677! Sobre los puntajes: el puntaje de cada ronda debe ser actualizado en la ventana de juego, partiendo con los ítems atrapados desde el inicio de esta ronda (comenzando con 0) y la vida del jugador (comenzando con %100 si es la primera ronda o menor dependiendo de la vida que le quedo en la ronda anterior). Cada vez que se atrape un ítem de cualquier tipo o varíe la vida, el puntaje **durante la ronda** se debe actualizar. Finalmente al terminar la ronda, este puntaje **se acumulará** con los puntajes de las ronda anteriores en esta misma partida, generando este puntaje que se podrá ver en la ventana de post-ronda/resumen.

Sobre la vida: siempre que se hable de vida del jugador o vida del personaje, es lo mismo. Esta debe partir al %100 para cualquier personaje elegido en la primera ronda y varía a medida que avanza el juego gracias a los ítems atrapados (buenos y malos) o al _cheatcode_ de vida. Por lo tanto el juego termina cuando la vida del personaje/jugador es 0.

Avísame si te quedan dudas ☺️ suerte en tu tarea!
