### ISSUE TITLE
[Tarea 3] libpng error: Read Error

### ISSUE THREAD

**Issue by Tito0906** [IIC2233/syllabus#549]
Holaa!, tengo un problema con la foto de perfil. Cuando trato de cargar la foto a una QPixmap(pathFoto) me sale el error "libpng error: Read Error". 
Para dar contexto, mi Servidor envía la foto en forma de bytes una vez procesada (RGB -> PNG) y Cliente lo guarda en su carpeta. La imagen se puede ver si desde afuera, desde un editor de imágenes, pero cuando trato de cargarla con QPixmap me sale el error que ya mencioné. Por otro lado, el path esta correctamente cargado, de eso estoy seguro.

**Comment by matiuc** [comment]
Me paso lo mismo, por que puede ser?

**Comment by Balepe666** [comment]
Si a alguien le sale bien que avise a mi me pasa lo mismo :(

**Comment by mjespinoza** [comment]
Yo tengo el mismo problema, lo busque y aparece que la imagen esta corrupta :/ no se como se puede arreglar

**Comment by iqacevedo** [comment]
Hola !
De momento intenten revisar si están escribiendo bien los bytes de PNG, sobretodo que no les falte ningún _chunk_. No he podido recrear el error, escribí una imagen en PNG, la probé con pixmap y me funcionaba bien.

**Comment by Tito0906** [comment]
Holaa, muchas gracias por responder. 
Por mi parte, revisé que estuvieran los chunk (IHDR, IDAT, IEND) y los bytes que indican que el archivo es PNG (Firma al inicio). Además, probé con 3 y 4 canales y cambiando algunas otras cosas y me sigue sucediendo lo mismo. Como dije, el archivo se puede ver desde un editor pero sigue dando el error de libpng cuando trato de cargar la imagen en QPixmap. 
A que te refieres cuando preguntas si indicamos si son 3 o 4 canales en IDAT? La información de la cantidad de canales no debería estar en IHDR?

**Comment by matiuc** [comment]
Hola, igual que a mi compañero la imagen en bytes que genero la puedo escribir como imagen en mi computador y puedo ver la imagen con el filtro aplicado correctamente, pero una vez que quiero sesearla con QPixmap me tira erro "libpng error: Read Error"

**Comment by crvargasu** [comment]
Hola!, tengo el mismo problema al intentar hace Qpixmap, sin embargo la imagen se ve perfecto en el computador.
'libpng error: Read Error'
No se que puede ser

**Comment by iqacevedo** [comment]
Hola ! Me refería al IHDR, gracias por aclararlo. Voy a estar revisando el error y les avisaré apenas pueda encontrar el error y alguna solución.

**Comment by iqacevedo** [comment]
Para poder encontrar el error me gustaría saber:

1-. ¿Que Sistema operativo tienen?
2-. ¿Ocupan anaconda :eyes:?
3-. ¿Podrían indicar la versión de libpng que tienen? [en ubuntu](https://stackoverflow.com/questions/33634402/how-to-check-libpng-version)
4-. Para tener más información, tambien indiquen su versión de PyQt.

Mi sospecha es que pueden solucionarlo actualizando `libpng`. Pero no prueben actualizando aun (ya que podría romper algo).

**Comment by Tito0906** [comment]
Holaa! , respondiendo en orden:
1 - ocupo Windows 10
2 - no ocupo anaconda
3 - no uso ubuntu
4 - PyQt5:
   -PyQt5                 5.11.3
   -PyQt5-sip             4.19.17
   -pyqt5-tools           5.11.3.1.4

Tengo la duda de si pudiste replicar el error?

**Comment by iqacevedo** [comment]
@Tito0906 muchas gracias, aún no logro replicar el error. Me funcionan bien los pixmap y no se me caen. Todas mis preguntas son en base a lo que he investigado. Sobre el punto 3 me expresé mal, me refería a que no sabía cómo buscarlo en otro SO que no fuera ubuntu, pero si es importante que busquen la versión de libpng que tienen, todo parece apuntar a que esa es la causa.

**Comment by absoto4** [comment]
Hola, tengo el mismo error. Alguien ha podido solucionarlo?

**Comment by Tito0906** [comment]
@iqacevedo holaa!, por el momento todavía no encuentro como ver la versión de libpng en Windows (no me han funcionado las que he encontrado). Sobre replicar el error, no se si ayude pero en el repositorio de mi tarea hay un archivo .py con las funciones que dan error llamado "libpng_error" que subí para preguntar mañana en clases (en una de esas te sale error tambien usandolas).

**Comment by mjgarrido1** [comment]
tengo el mismo error :( pero puedo abrir bien todas las fotos cargadas desde la carpeta

**Comment by iqacevedo** [comment]
Hola !
@Tito0906 gracias a tu código logré reproducir el error. No he logrado detectar porque falla, pero ya se que no depende de las versiones de libpng como sospechaba. Les estaré informando sobre las posibles fallas.

Saludos !

**Comment by perezpefaur** [comment]
Hola aca con el mismo error!

**Comment by crvargasu** [comment]
hola! alguien pudo resolver el problema?

**Comment by Hernan4444** [comment]
Hola @Tito0906 utilicé tu código que reproducía el error y el error era que el **tipo de chunk** que guardabas al final le pusiste "IDAT" cuando era "IEND" y por eso, el formato del PNG estaba mal.

Dado esto, la única hipótesis que tengo hasta ahora es suponer que el error es que no siguen el formato de un PNG. 

Primero les recomiendo que usen la función `get_pixels` para abrir la imagen y la guardan tal cual viene en otro archivo (sin aplicar el filtro de dibujo), si la imagen tiene error ahí, entonces el proceso de crear el IEND o IHDR está mal y recomiendo revisar eso, ejemplos de errores son: tamaño no está bien definido o no están poniendo bien el tipo de chunk. 

Saludos :v:

**Comment by Hernan4444** [comment]
@absoto4 revisé tu código y 
1. El tamaño de la matríz no está bien calculado, revisa el pdf donde se explica
2. El IEND no sigue el formato (Largo lo pusiste de 1 byte y es de 4, además es tamaño 0, no tamaño 1)
3. El largo de IDAT lo haces de la versión no comprimida y se debe hacer del comprimido
4. Para el CRC de IDAT se ocupa el tupo + información comprimida
5. **extra** llamas más de 1 vez a una función que toma mucho de forma injustificada (`filtro_dibujo`), recomiendo revisar como solo ejecutarla una vez.

En resumen, los errores se están dando porque 
1. CRC mal calculado o formato de los chunk no es el indicado en el enunciado

Saludos ✌️

**Comment by Hernan4444** [comment]
@crvargasu revisé tu código y los errores son similares a los mencionado antes

1. El IEND no sigue el formato (Largo lo pusiste de 0 byte y es de 4)
2. El largo de IDAT lo haces de la versión no comprimida y se debe hacer del comprimido
3. El 0 de cada fila se pone al inicio de esta, tu estás agregando uno más.

Con los cambios necesarios para resolver esos 3 problemas se ven las imágenes sin dicho error.

Saludos ✌️

**Comment by absoto4** [comment]
@Hernan4444  Muchas gracias! Ahora si me funciona! 😄

**Comment by crvargasu** [comment]
Muchisimas gracias!! ya me funciona!

**Comment by Tito0906** [comment]
@Hernan4444  Holaa!, muchas gracias! Funciona perfecto.

**Comment by juanpacl111** [comment]
@Hernan4444 Hola Hernan! ¿Será posible que revises mi código también por favor? Logro crear la imágen pero no logro leerla, ya intenté con todos los cambios propuestos.
