### ISSUE TITLE
__gatestate__

### ISSUE THREAD

**Issue by asuribe** [IIC2233/syllabus#549]
No logro entender bien la función de ese método. ¿Describe las acciones que se tienen que hacer al deserealisar un mensaje?

**Comment by fdoflorenzano** [comment]
Hola @asuribe,

Primero, asumo te refieres a `__getstate__`, y... más o menos. En realidad, no. 

`__getstate__` se acciona al serializar un objeto mediante `pickle`, no al deserilizar, para eso es `__setstate__`. 

Al serializar un objeto mediante `pickle`, este por defecto lo que hará es tomar el diccionario interno de la instancia y será eso lo que transforme a *bytes*. Pero, si se define para la clase el método `__getstate__`, se define una alternativa para la clase donde se describen las acciones a hacer cuando se serialice el objeto y debe retornar el objeto que luego se transforme a *bytes* en vez del defecto. Esto eventualmente significa alterar la instancia debido a que se está serializando, o llamar algún comportamiento necesario en ese contexto.

Saludos.
