### ISSUE TITLE
iterar sobre las instancias de una clase

### ISSUE THREAD

**Issue by tolavarria** [IIC2233/syllabus#549]
Hola, mi pregunta es si, teniendo varias instancias de una clase ¿hay alguna manera de usar un ciclo ``for`` para recorrer las distintas instancias de una en específico?

**Comment by Dnpoblete** [comment]
Hola @tolavarria, no se si estoy comprendiendo bien tu duda, pero en el caso de tener instancias de una clase y querer recorrerlas, en la [semana 1](https://github.com/IIC2233/contenidos/tree/master/semana-01)  de contenidos se vió lo que son las estructuras de datos, y sus distintos tipos. En base a esto, puedes seleccionar la mejor estructura de datos según lo que quieres hacer. En este caso en particular, si deseas recorrerlas con ciclo for, puedes utilizar una lista y recorrerlas haciendo:

`for instancia in lista:`

Espero haber resuelto tu duda y en caso de no haberlo hecho avísame para poder ayudarte! 😄

**Comment by tolavarria** [comment]
Ahh, sii entiendo que se pueden usar otras estructuras de datos, pero quería ver si, para ahorrar quizás algunas líneas o usar la menor cantidad de herramientas, podía simplemente hacer un ``for`` que vaya recorriendo todas las instancias.
Gracias!

**Comment by Dnpoblete** [comment]
Ah ahora entiendo, en el caso de querer hacerlo sin estructuras de datos, existen otros métodos que requieren más líneas de código, por ejemplo utilizar iter y next, que forman parte de los contenidos de iterables de la semana 6.  La otra opción que es como lo más cercano a lo que buscas es que podrías hacer una variable de clase que guarde todas las instancias mientras se crean.

Éxito con la tarea!
