### ISSUE TITLE
Problema Actividad 2

### ISSUE THREAD

**Issue by valerojasm** [IIC2233/Syllabus#55]
Hola! Lo que pide imprimir la actividad 2 me da lo siguiente:

```
----- Passenger list -----
------ Flight 009 ------
('1', (<__main__.Client object at 0x101baa7f0>, '10620242-2'), 0)
('2', '----', '----')
('3', '----', '----')
('4', (<__main__.Client object at 0x101baa668>, '22315433-5'), 0)
('5', (<__main__.Client object at 0x101baa518>, '24502023-2'), 0)

----- Destination -----
------ Concepción ------
Traceback (most recent call last):
  File "actividad2.py", line 162, in <module>
    print(*query21, sep="\n")
TypeError: print() argument after * must be an iterable, not NoneType
```

y antes de eso me da todos los nombres de los pasajeros de la forma: `'Margarita Flores del Campo': <__main__.Client object at 0x101baab70>, 'Elton Tito': <__main__.Client object at 0x101baaba8>, 'Eddy Ficio': <__main__.Client object at 0x101baabe0>}).`

la función passenger_list la deje igual, solo cambie las variables que estaban por los nombres que yo tenía, y mi passengers to destination esta asi:

```
    def passengers_to_destination(self, destination):
        flights_for_destination={}
        for flight in self.flights.values():
            if flight.destination==destination:
                for seatnumber in flight.seats_registration:
                    flights_for_destination[destination]=str(flight.seats_registration[seatnumber][1])
            else:
                continue
```

siendo el `self.flights` el diccionario que cree en el recovery para los vuelos del archivo, cuyo key es el numero de vuelo y su value es una instancia de Flights con los atributos fid, origin y destination. Lo que intento hacer es recorrer los valores y comparar el atributo destination al ingresado y para cada uno de esos, iterar en las keys del dict "seats_registration" que tiene Flights, que son los numeros de asiento con value nombre y pasaporte de la persona. Así, quería sacar el value "[1]" que sería el pasaporte y guardarlo en mi nuevo dict con key destination y value pasaporte que en el fondo es lo que pide retornar la función. Y no funciona. Ayudaaaaaaa

**Comment by valerojasm** [comment]
Probé esto y tampoco me funciona, me tira el mismo error:

```
    def passengers_to_destination(self, destination):

        set_rut = set()
        for vuelo in self.flights.values():
            if destination == vuelo.destination:
                for key in vuelo.seats_registration.keys():
                    set_rut.add(vuelo.seats_registration[key][1])
            else:
                continue
                
        list_asked = []
        for value in set_rut:
            list_asked.append(value)
```

**Comment by jecastro1** [comment]
Si miras en el [`main.py`](https://github.com/IIC2233/Syllabus/blob/master/Actividades/AC02/main.py#L121) y en el enunciado, se esperaba que el método `passengers_to_destination` retornara una lista de tuplas.

Debes agregar un valor de retorno a tu solución para que puedas imprimir los valores. Cuéntanos cómo te fue.

Saludos.
