### ISSUE TITLE
Acciones pendientes

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#55]
Hola, en el archivo de acciones pendientes se puede guardar el tipo de accion de la forma: "acción;cantidad" tal como lo hacen en "acciones"

Gracias

**Comment by VicenteMerino** [comment]
En esta misma línea, que pasa con las acciones pendientes de recolección de recursos, según el enunciado no se deberían guardar

**Comment by gatochico** [comment]
Hola! 

Estás en lo correcto, puedes seguir el formato **acción;cantidad** en _acciones_pendientes.csv_ para los casos donde se crean múltiples personas de un mismo tipo en un turno.

Con respecto a tu segunda pregunta, en teoría nunca guardarás acciones de recolección de recursos en _acciones_pendientes.csv_ ya que estas tienen una duración de 1 turno, y sólo puedes guardar una partida al inicio de cada turno. Por ende, si una civilización recolectó recursos en el turno _x_, estos ya están agregados cuando debe elegir acciones (entre ellas, guardar) al inicio del turno _x+1_. Y si se sale del programa sin guardar en este punto, al momento de reanudar la partida esta comenzará nuevamente al inicio del turno _x+1_. En resumen, en ningún caso una acción de recolección quedará pendiente a la hora de guardar una partida.

Saludos ! :cat:

**Comment by VicenteMerino** [comment]
Mi pregunta en verdad por qué pasa con las CPUs, puesto que si recolectan, y llega mi turno no alcanzarán a tener los recursos, ya que no ha pasado un turno completo, no se si se entiende.
Lo que se me ocurre es considerar que al inicio de mi turno los reciban, de esta forma:

Turno 1 (mío): Hago algo
Turno 1 (CPU): Recolecto recursos
Turno 2 (mío): CPU también recibe sus recursos, guardo partida y salgo

No se si es válido algo así?

**Comment by gatochico** [comment]
Si, es válido ejecutar todas las acciones de recolección de todas las civilizaciones al inicio del turno siguiente, antes de que el usuario pueda elegir sus acciones para el turno nuevo.

**⚠️ EDIT IMPORTANTE ⚠️:** 
Con respecto al archivo _acciones_pendientes.csv_, se llegó a la decisión de que si lo deseas, puedes almacenar dentro de este la construcción de varios elementos en una sola línea siguiendo el formato de _acciones.csv_, es decir:
```
turno, civ, tipo, turnos_pendientes
27, 2, muralla;3, 4
```

Sin embargo, tu programa también debe soportar el formato mostrado en el enunciado, donde la construccion de múltiples elementos de un tipo se escribe como una línea por elemento. Por ejemplo, tu programa también debería funcionar si se le entrega un _acciones_pendientes.csv_ con el siguiente formato:

```
turno, civ, tipo, turnos_pendientes
27, 2, muralla, 4
27, 2, muralla, 4
27, 2, muralla, 4
```
Queda a tu criterio si deseas solo quedarte con el formato del segundo ejemplo, o si deseas permitir que ambos sean válidos para tu programa.

Finalmente, lo que NO se permite, es crear una columna nueva para la cantidad de unidades de un elemento. El siguiente código estaría INCORRECTO, ya que la columna cantidad no está en la estructura dada por el enunciado para ese archivo:
```
turno, civ, tipo, cantidad, turnos_pendientes
27, 2, muralla, 3, 4
```

Disculpa por las molestias, y éxito programando!

**Comment by VicenteMerino** [comment]
Hola sobre mi pregunta qué pasa con las construcciones y creación de personas pendientes de las civilizaciones de la CPUs? Puedo hacer que finalicen en mi turno? Sino llegaria al mismo problema de la recolección de recursos anteriormente preguntada

**Comment by gatochico** [comment]
La idea es que si, la construcción y creación de personas de las CPU finalicen (si es que pasaron los turnos necesarios) antes de que le toque al usuario elegir sus acciones para el siguiente turno. Quizá se te haga más fácil ver como funciona un turno de esta manera:

![photo4960988295953754161](https://user-images.githubusercontent.com/37161120/55081350-732de600-507e-11e9-9f35-531a2be1b769.jpg)

Donde la línea gris es el momento donde se le permite al usuario elegir sus acciones (entre ellas, guardar la partida).

**Comment by quememo** [comment]
### Ocurre lo mismo con los puntos de tecnología? Explico a continuación mi punto en 2 casos:

1. Al inicio del turno 40, el jugador quiere atacar a la CPU2 y tiene **Pa>=Pd** por lo que la eliminaría por completo si lleva su ataque a cabo, sin embargo en ese mismo turno la CPU2 acumuló suficientes puntos de tecnología para obtener la victoria científica al desbloquear la computación, por lo que antes de ser atacada por el jugador, el juego terminó y ganó gracias a esto.

2. Mismo caso que el descrito anteriormente, pero los puntos de tecnología los recibe solo al comienzo del su turno la CPU2, por lo que antes de obtener la victoria científica, recibe el ataque del jugador y queda eliminada.

**Comment by Arcoirisky** [comment]
Hola @quememo

Hazte la siguiente pregunta ¿La recolección de puntos tecnológicos se hace en un turno? Y complementa con la respuesta de más arriba. 

Descansa un poco, ánimo y recuerda que cualquier suposición que no se haya explicado de alguna forma en el enunciado o en las Issues las puedes dejar explicar en tu README.md

**Comment by quememo** [comment]
> Hola @quememo
> 
> Hazte la siguiente pregunta ¿La recolección de puntos tecnológicos se hace en un turno? Y complementa con la respuesta de más arriba.
> 
> Descansa un poco, ánimo y recuerda que cualquier suposición que no se haya explicado de alguna forma en el enunciado o en las Issues las puedes dejar explicar en tu README.md

Osea, es que por ejemplo para los recursos tiene sentido que todas las civilizaciones reciban sus recursos en el inicio de MI TURNO, ya que no se guarda en el archivo de acciones pendientes.

Sin embargo, siento que podrían todas las civilizaciones recibir sus puntos de tecnología en el comienzo de MI TURNO o también que los reciban en orden, justo antes de llevar a cabo su acción (las CPU), pero dependiendo de que cosa considero, se alteran ciertos resultados de interacciones. No me queda del todo claro tu respuesta

**Comment by jmwielandt** [comment]
@quememo
Es al principio de **tú** turno.
Como no está en los pendientes, no puede ser recibido antes de que se concrete su acción ya que mientras tomas tu decisión puedes guardar y cerrar, y nunca recibirían sus recursos.
Ponlo en tu readme.
