### ISSUE TITLE
Input en Sublime text 3

### ISSUE THREAD

**Issue by Emiliax16** [IIC2233/syllabus#55]
Hola! como en sublime no se pueden ingresar inputs en la consola, puedo instalar sublimerepl o más adelante se verá otra manera de poder realizar esta acción? averigué que con eso se abre una pestaña para poder colocar un input :)

**Comment by Drpinto1** [comment]
¡Hola!

REPL es una muy buena alternativa para cuando quieras ejecutar programas que necesitan `input`, aunque tiene una pequeña desventaja y es que se ligeramente feo (en mi opinión y la de varios otros jajaja).

Una forma de evadir lo anterior es usar REPL solamente cuando necesites un `inputs`, pero si no te molesta (o te gusta) la apariencia de REPL, puedes usarlo para ejecutar todos tus programas :smile: 

¡Saludos!
