### ISSUE TITLE
Cantidad de publicación de post al día

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#55]
Tengo una duda, debemos asumir que se pueden publicar un post al día? , porque igual no se está trabajando con la hora a la que se publica, solo la fecha (según el archivo post.csv). O consideramos también la posibilidad de publicar más de un post al día  a pesar de que se guarde la misma fecha?

**Comment by Dnpoblete** [comment]
Hola @Camila-sty, considerando que en la vida real uno puede publicar más de un post al día, puedes asumir que un usuario puede publicar más un prograpost al día. Adicionalmente, te dejo esta issue donde se habló del tema #17 .

Éxito con la tarea! 😄
