### ISSUE TITLE
Duda sobre paths relativos T0

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#55]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En cuanto al uso de paths relativos, ¿debemos asumir que los archivos `*.py` estarán en la misma carpeta que los `*.csv`?
¿O los archivos `*.csv` estarán en otra carpeta que nos notificarán más adelante en el desarrollo de la tarea?

Desde ya, graciaasss ❤️.

**Comment by matiasmasjuan** [comment]
Hola @Rerro-r !

**Sí**, puedes asumir que los archivos ```*.py``` estarán en la misma carpeta que los ```*.csv```. Sin embargo, no hay ningún problema con cambiar el *path* de los archivos y agregarlos en otra carpeta **siempre y cuando** lo indiques en el **README.md**.

Saludos! y mucho éxito con la tarea :smile:
