### ISSUE TITLE
Duda sobre moverme entre paths

### ISSUE THREAD

**Issue by etoteiza** [IIC2233/syllabus#55]
Hola, tengo una pequeña duda, para moverme mediante paths usare el comando 'os.path.join()' de acuerdo a la carpeta contenidos. tengo la duda, importa las mayusculas o minusculas? por ejemplo, hay diferencia entre usar 't00' o 'T00'? 
pregunto porque no sé si eso podria generar problemas frente a los sistemas operativos al momento de corregir la tarea (tengo entendido que la idea de usar 'os.path.join()' es para moverse independiente de los sistemas operativos)

Gracias de antemano!!

**Comment by KnowYourselves** [comment]
Hola @etoteiza!

En algunos sistemas operativos los archivos son _case insensitive_ (como Windows) es decir, no importan las mayúsculas, mientras que en otros son _case sensitive_ (como Ubuntu) donde si importan las mayúsculas.

Por esto te recomiendo mantener las mayusculas en los paths en caso de que las hayan (como en `T00`). 

Espero haberte ayudado!

**Comment by etoteiza** [comment]
Muchas gracias!

**Comment by etoteiza** [comment]
Hola de nuevo,

Tengo un problema para moverme entre paths relativos. estoy usando `os.path.isfile()` para ver si el path existe. por ello estoy usando paths relativos. en mi caso uso ´os.path.join('T00', 'main.py)´ donde main.py es donde hago la tarea. sin embargo al utilizar `os.path.file()` sobre ese path relativo me sale que False. Sin embargo, para lo mismo, me sale True cuando uso el path relativo. No sé porque me funciona usando path relativo.

**Comment by KnowYourselves** [comment]
Una pequeña corrección, no es "que te muevas" entre _paths_ relativos. Tu programa tiene un _working directory_ que es desde donde se calculan todos los _paths_ relativos, este por default es el directorio desde donde se ejecutó el programa. 

Respecto a tu pregunta, ten en cuenta que el path que estás buscando es "T00/main.py", pero tu _working directory_ es dentro de "T00", por lo cual si bien el archivo "main.py" existe, no existe una carpeta "T00" que dentro tenga un archivo "main.py".

Espero que se haya entendido!
