### ISSUE TITLE
Archivos T0

### ISSUE THREAD

**Issue by Crisax234** [IIC2233/Syllabus#55]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola buenas, una pregunta, debemos hacer el programa para que funcione solo con los archivos entregados o será probado con archivos diferentes? De antemano muchas gracias

**Comment by tqmbanados** [comment]
Hola! Es posible que cambiemos el *contenido* de cada archivo, pero no cambiaremos su formato. Es decir, seguirá siendo un formato `.csv`, y cada columna se mantendrá representando lo mismo. 
Por ejemplo: 
```csv
nombre,apellido,cargo
fulanito,detal,presidente
``` 
Ahí quizás agreguemos o cambiemos **filas**, pero el archivo nuncá pasará a verse así:
```csv
nombre,cargo,apellido
fulanito,presidente,detal
``` 

Espero haberte sido de ayuda!
