### ISSUE TITLE
Uso de librería PrettyTable

### ISSUE THREAD

**Issue by paulmacguire** [IIC2233/Syllabus#55]
Hola!
Encontré en internet una librería llamada PrettyTable la cual te permite crear tablas de manera muy práctica. Con respecto a esto, ¿hay algún problema con que la ocupe? Vi que dejaron ocupar tabulate() y creo que es como lo mismo, pero pregunto para salir de la duda.

Gracias de antemano! :)

**Comment by benjaaguila** [comment]
Hola @paulmacguire ! Deja esta duda como comentario en la issue #13 ya que esa es especifica para preguntar por librerías.

Saludos!
