### ISSUE TITLE
Duda sobre guardar la partida

### ISSUE THREAD

**Issue by ojedarcelo** [IIC2233/Syllabus#55]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, tengo dos dudas con respecto a guardar las partidas.
1. Puesto que los archivos de las partidas guardadas deben tener el formato {nombre de usuario}.txt, ¿Un usuario puede tener sólo una partida guardada a la vez?
2. Si tengo una partida guardada, y creo una nueva partida con el mismo nombre de usuario, ¿La partida guardada se elimina? ¿O puedo seguir jugando una partida nueva mientras que la otra queda guardada?

**Comment by drcid98** [comment]
Hola!
1. Si, ya que el nombre del archivo es solo el nombre de usuario, cada usuario solo podrá tener una partida guardada como máximo.
2. Si un usuario tiene una partida guardada, empieza otra partida y **guarda** esa partida, el nuevo archivo debería sobrescribir el anterior. Si una nueva partida del usuario no se guarda, no hay razón para eliminar la partida que si fue guardada con anterioridad.
Saludos!

**Comment by ojedarcelo** [comment]
Y una última duda, si abro una partida guardada y la pierdo, ¿La partida guardada se elimina? ¿O puedo volver a jugar desde el punto en que la guardé (como un checkpoint)?

**Comment by drcid98** [comment]
Como mencioné, si no guardas explícitamente una partida no debería haber razón para modificar el archivo de la partida guardada. Pero de todos modos, ya que no sale en el enunciado, puedes tomar la decisión tú y especificarlo en el README.md.

Saludos!
