### ISSUE TITLE
Orders con id no asignadas

### ISSUE THREAD

**Issue by mesantamaria** [IIC2233/Syllabus#55]
Hola,

revisando los csv vi que hay orders que no están asignadas a ningún usuario (ejemplo id 95 y 39).

Las tenemos que asignar nosotros aleatoriamente a los usuarios que ya existen o hay alguna otra razón?

**Comment by hanavarrete** [comment]
Eso fue un error de nuestro script 🎉  . Omítanlas por el momento, el archivo que usemos para la corrección estará correcto.

**Comment by sebabitar** [comment]
Disculpa ,subirán un archivo correcto antes de la correción? porque es dificil probar el correcto funcionamiento del programa.

**Comment by Hernan4444** [comment]
@sebabitar acabo de subir el archivo arreglado 👍 

Saludos!!
