### ISSUE TITLE
Duda sobre ventanas creadas en Qt designer c

### ISSUE THREAD

**Issue by jervaal** [IIC2233/syllabus#550]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! tengo una duda sobre la carga de las ventanas de Qt designer, y es que cree una ventana en qt designer, pero no me deja cargarla y mostrarla en python, ¿Que podria hacer u.u?, he leido lo de los posts distintos y no llego a nada en concreto u.u

De antemano muchas gracias!

**Comment by tqmbanados** [comment]
Hola! Antes de empezar me gustaría que descartáramos algunas cosas:
1.- ¿Tienes correcta la ruta al archivo .ui?
2. ¿Utilizas bien la función ```uic.loadUiType()```? (```(clase_ventana, clase_base = uic.loadUiType("ventana.ui")```)
3. ¿Heredas correctamente de estas clases?
4. La clase que defines que hereda de estas clases, ¿no tiene algún otro error que impida que se abra?
5. Finalmente: los assets que usas en la ventana de designer, ¿están importados? si es que no lo están, ¿están guardados con path absoluto o relativo?
Cuéntame como te va revisando esas cosas. Puedo mirar tu código también, así que haz un push y avísame!

**Comment by jervaal** [comment]
> Hola! Antes de empezar me gustaría que descartáramos algunas cosas:
> 1.- ¿Tienes correcta la ruta al archivo .ui?
> 2. ¿Utilizas bien la función `uic.loadUiType()`? (`clase_ventana, clase_base = uic.loadUiType("ventana.ui")`)
> 3. ¿Heredas correctamente de estas clases?
> 4. La clase que defines que hereda de estas clases, ¿no tiene algún otro error que impida que se abra?
> 5. Finalmente: los assets que usas en la ventana de designer, ¿están importados? si es que no lo están, ¿están guardados con path absoluto o relativo?
> Cuéntame como te va revisando esas cosas. Puedo mirar tu código también, así que haz un push y avísame!

Holaa! al final no era nada de eso ksdlfkljdsf, era que no estaba el archivo de recursos .qrc en la misma carpeta que los otros archivos, muchas graciaas!

**Comment by tqmbanados** [comment]
fhgshda ya! igual te recomiendo no trabajar con recursos, hace las cosas un poco mas dificil uwu
