### ISSUE TITLE
Examen

### ISSUE THREAD

**Issue by IriSalazar** [IIC2233/Syllabus#550]
Hola! Por casualidad alguien sabe cuando es el examen de progra? No lo veo en el calendario.

Gracias!

**Comment by akaminetzkyp** [comment]
Es el 4 de Julio. 😄

**Comment by indonoso** [comment]
Ya agregamos la fecha al calendario, es la misma fecha que aparece en el siding. El examen será durante la mañana, pero todavía no hemos definido la hora de inicio.
