### ISSUE TITLE
Guardar resultados al terminar la simulacion

### ISSUE THREAD

**Issue by cefierro** [IIC2233/syllabus#550]
Hola, nos piden que se guarden los ganadores medallas y resultados, mis dudas son las siguientes:
en donde se guarda lo que se piden? se refiere solo a la parte de los resultados.txt?
con resultados se refieren a todo lo del archivo resultados.txt?
los resultados finales son solo los de las medallas?
comienzo a hacer la gran 'suponiendo que...' y lo pongo en el README simplemente?

**Comment by jitorcas** [comment]
Hola! @cefierro 

Efectivamente, se les pide que escriban en un archivo `puntajes.txt` todos los resultados obtenidos en las competencias. La forma en que lo hagas queda a tu criterio, pero debe estar la información que se explicita en la sección de archivos en el enunciado (día, competencia, delegación ganadora y deportista ganador). También podrás encontrar un ejemplo de cómo podría ser el formato del archivo. 

Mucho éxito! 🏋️‍♀️
