### ISSUE TITLE
Diferencia entre encode y to_bytes

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#550]
Hola,
Con respecto a la tarea, el enunciado dice que se debe rellenar con bytes ceros (b'\x00') los chunks de largo menor a 124. No me queda claro la diferencia entre esto y el output de '0'.encode()
Al hacer '0000'.encode('utf-8') se obtiene b'000'
mientras que si hago '0'.to_bytes(4, byteorder='little') se obtiene b'\x00\x00\x00\x00'
Cual es la diferencia entre estos outputs?

**Comment by fdoflorenzano** [comment]
Hola @FelipeA7,

Entiendo tu duda, y esta se remonta a tener ojo cuando imprime un objeto `bytes` y entender bien lo que representan y porque se imprimen como lo hacen en Python.

Los objetos que estás transformando a `bytes` mediante `encode` y `to_bytes` son de distinto **tipo**. [`encode`](https://docs.python.org/3/library/stdtypes.html#str.encode) es un método de `str` y [`to_bytes`](https://docs.python.org/3/library/stdtypes.html#int.to_bytes) es un método de `int`. Luego, en un caso estás transformando el *string* `"0"`, y en el otro el entero `0`, que **son objetos distintos** y por lo tanto se traducen de forma distinta.

Ambos *outputs* que señalas serían cadenas de 4 *bytes*, pero uno corresponde el traducir los caracteres `"0"` al *byte* correspondiente mediante UTF-8, mientras que el otro es calcular la cadena de *bytes* cuyo valor es equivalente al número 0, pero usando 4 *bytes* en total. 

Si imprimes el resultado del primero y ves `b'0000'`, ojo que se **ven** ceros, pero el que se ve es el caracter *string* correspondiente al *byte* que hay detrás, no corresponde al cero numérico que se pide en el enunciado. Puedes hacer la prueba para asegurarte con el siguiente código:
 
```python
lista_de_valores_numericos_1 = [int(byte) for byte in b'0000']
print(lista_de_valores_numericos_1)
lista_de_valores_numericos_2 = [int(byte) for byte in b'\x00\x00\x00\x00']
print(lista_de_valores_numericos_1)
```

El primero retorna `[48, 48, 48, 48]`, mientras que el segundo retorna `[0, 0, 0, 0]`. Nuevamente, ya que `'0000'.encode('utf-8')` traduce caracteres, y el correspondiente *byte* para el caracter `"0"` es el *byte* de valor 48, o de hexa `\x30`. De hecho, si imprimes `b'\x30\x30\x30\x30'`, verás de nuevo `b'0000'`, notando inmediatamente que muestra algo distinto a `b'\x00\x00\x00\x00'`.

Lo que siempre hay que tener en cuenta, es que al imprimir una secuencia de *bytes* en Python, este lo intentará hacer lo más legible posible para el usuario por lo que verá el valor numérico detrás de cada *byte* y verá si tiene una correspondencia por un caracter de *string* y lo reemplazará en la impresión. Si no encuentra una correspondencia, entonces muestra la codificación en hexadecimal.

Luego, al ver `b'0000'`, si bien leemos (con nuestros ojos) cuatro ceros seguidos, en realidad vemos cuatro caracteres `'0'` que son la correspondencia en *string* a *bytes* cuyo valor no es necesariamente el valor 0, y de hecho, es 48. Mientras que vemos para `b'\x00\x00\x00\x00'` cuatro números en hexadecimal, que no tienen un caracter de *string* correspondiente, y cuyo valor numérico es efectivamente 0.

Espero se entienda la idea. 

Saludos.
