### ISSUE TITLE
Estadisticas

### ISSUE THREAD

**Issue by MrEarle** [IIC2233/Syllabus#550]
Tengo una duda con 3 de las estadísticas que tenemos que calcular:

> 1) Cantidad mínima, máxima y promedio por productos vendidos durante un día.
> 2) Calidad promedio de productos de todos los vendedores por escenario
> 3) Cantidad de Productos que se descompone.

1) Esto es que, para cada producto, tengo que calcular cuál fue su mínimo/máximo de ventas pro dia y su promedio en todo el semestre?

2) Cómo calculo la calidad? Porque es una función que depende del tiempo en el dia, entonces qué momento elijo para ver la calidad promedio de los productos?

3) Cuando un producto esta descompuesto? En el enunciado sale que 

> Putrefacción: Corresponde a un valor entre 0 y 1 que representa el porcentaje de putrefacción y descomposición de los alimentos.

Pero nunca dice algo sobre cuando se considera descompuesto.

Edit: Hay otra estadística con la que tengo duda:

Cantidad promedio de dinero conscado a los vendedores debido a llegada de carabineros.

Un vendedor tiene distintos productos a distintos precios, pero todos están representados por el mismo stock. Cual uso para calcular el dinero confiscado? El promedio?

**Comment by iqacevedo** [comment]
Hola!

1-. Para simplificar que sea la cantidad total de productos para realizar el calculo, sin importar de que tipo sean. Tienes que calcularlo para todo el semestre, considerando el min/max como la cantidad mínima/ máxima que se vendió en un día.

2-. Como no está explicito, define en que momento vas a medirla. Te recomiendo medirla al momento en que se venden los productos o que se acaba el día, pero queda a tu criterio. Recuerda especificar en que momento la medirás en tu Readme. 

3. Queda a tu criterio que métrica usar para definir que está descompuesto. Solo recuerda que **debes** usar la putrefacción dentro de tu decisión y especificarlo en el Readme.

4-. Nuevamente como tampoco está explicito define que métrica deseas utilizar para decidir el precio. El promedio parece ser una muy buena alternativa. También especificalo en tu Readme.

Saludos !

**Comment by rihanuch** [comment]
@iqacevedo , se **debe** usar la putrefacción para ver si está descompuesto o no o se puede usar la **calidad** ?

**Comment by iqacevedo** [comment]
@rihanuch como la calidad depende directamente de la putrefacción es igualmente valido utilizarla.

Saludos !

**Comment by Bneya** [comment]
Para el caso de los alumnos, 
1- ¿el producto que escogen comprar cuando le compran a cierto vendedor en específico es al azar?
2- Si un vendedor tiene producto1 a $1000 y pruducto2 a $800 y un alumno escoge (conscientemente o al azar) compar producto1 teniendo solo $900, ¿se va no más del lugar por no tener dinero o escoge comprar producto2 en cambio?

**Comment by Hernan4444** [comment]
@Bneya 
1. Queda a tu criterio como escoger mientras que sea posible.
2. Para empezar, el alumno decidió quedarse en la cola porque el vendedor tenía algún producto que se podía comprar con el dinero del alumno. No suena lógico que intente comprar algo que no pueda :s. (Debería ir por el producto2)

Saludos ✌️
