### ISSUE TITLE
duda eliminar filas en QFormLayout

### ISSUE THREAD

**Issue by juakoke** [IIC2233/syllabus#550]
Hola!,  mi ventana donde muestro las salas la cree con un QFormLayout donde voy haciendo QFormLayout().addRow(sala, numero de personas) donde sala es un QPushButton y numero de personas en un Qlabel. Mi duda es ¿como puedo eliminar una fila cualquiera?, vi que existe el metodo .removeRow() pero no he encontrado la forma en que este funciona,¿ como le indico cual es la fila que quiero eliminar?

**Comment by jeschuwirth** [comment]
Hola!

El método removeRow(int) pide como argumento un int que índica el número de la fila que quieres eliminar. Por lo tanto FormLayout.removeRow(2) elimina la segunda fila.

Si te complica saber cual columna es la correspondiente a la sala que quieres eliminar, podrías utilizar un id en cada sala que represente la columna en la que está (el método rowCount() de FormLayout te puede ayudar para esto). Pero recuerdo que si tienes 5 salas y eliminar la sala 3, entonces la sala 4 se convierte en la nueva 3 y la 5 en la nueva 4.

Suerte en la tarea !

**Comment by juakoke** [comment]
Me funciono muy bien el removeRow ahora gracias pero tengo una duda con ek otro metodo. El metodo rowCount se utiliza despues de agregar la fila? Y me podrias contar mas de que atributos pide este metodo?

**Comment by jeschuwirth** [comment]
FormLayout.rowCount() no pide argumentos, y te retorna un int con el número de filas en tu FormLayout, te lo recomendaba para saber cuantas filas hay actualmente y así guardar un id para la sala de forma rápida. 

De todos modos es algo específico y si encuentras otra manera que te acomode más no hay problema con que la ocupes.
