### ISSUE TITLE
¿Hay que citar itertools? (y otros)

### ISSUE THREAD

**Issue by leonardosuarez777** [IIC2233/Syllabus#550]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### ¿Hay que citar itertools? (y otros)

En el transcurso de la tarea he implementado distintas funciones de itertools que no se vieron en la semana de contenidos, mi duda es, ¿es necesario que cite la página de documentación de este? Y en general para las tareas tengo la duda si es necesario citar solo cuando copio un código de alguna parte más o si tengo que citar cosas como estas que son funciones de librerías ya implementadas. Por ejemplo, imaginemos que no se enseñó el uso de randint, ¿es necesario poner en el README que usé randint que es un comando que encontré en un foro de reddit y lo usé en las lineas 56, 100 y 191? 
Gracias de antemano, 
Leonardo

**Comment by DiegoGHR** [comment]
Hola Leonardo! Para evitar problemas, te recomiendo citar todo lo que no se haya visto en los contenidos. Sino, puede parecer sospechoso y podrian creer que el codigo fue hecho con IA. En el caso de que sea una funcion ampliamente conocida o basica, puedes solo comentar que hace o como funciona (como randint). Saludos

**Comment by Cristobal-Hevia** [comment]
Entonces si no tenemos que citar ninguna funcion el readme se devuelve vacio?

**Comment by DiegoGHR** [comment]
Hola! El readme incluye hartas mas cosas que las citas. Pero si no hay nada que citar se devuelve esta seccion vacia. Saludos
