### ISSUE TITLE
Multas

### ISSUE THREAD

**Issue by vobrador** [IIC2233/syllabus#550]
Al aplicar la multa en fiscalizar magizoologo dice:
"* el escape de una criatura: se le pueden cobrar 50 sickles con una probabilidad de 50%"
Me queda la duda de si se aplica multa por criatura escapada o por al menos una, y, en cuanto a la probabilidad, es a  la multa total o por criatura?
Por ejemplo, si tengo 3 criaturas escapadas, serían 150 sickles o 50? Y, en cuanto a la probabilidad, podria eventualmente cobrarse solo 150 o 0 o se evalua por criatura (o sea si 2 de 3 pasan la probabilidad cobraria 100 por ejemplo).
Lei los issues relacionado a las multas pero en ninguna de las que vi se especificaba esto :(

Perdonen la redaccion, tengo sueño. Espero se entienda.

**Comment by moquezada** [comment]
Hola @vobrador 😄 

Tus dudas se respondieron en las issues #265 y #459. En resumen, siempre tienes que considerar los eventos del mismo tipo como sucesos independientes entre sí.

Ánimo con la tarea e intenta descansar en lo posible! ☺️

**Comment by vobrador** [comment]
Gracias!! :)))
