### ISSUE TITLE
error con setLayout

### ISSUE THREAD

**Issue by niguzman** [IIC2233/syllabus#551]
Hola,
cuando trato de cambiar de usuario hago que se vuelva a activar la ventana donde se le pide el nombre que quiere usar, pero pasa que al abrirme la ventana de las salas con ese nuevo nombre de usuario me tira error porque ya se ha seteado un layout (el programa no se cae pero no me actualiza el nombre en VentanaSalas)

**Comment by jeschuwirth** [comment]
Saludos!

Existen varias maneras de solucionar este problema, lo que más te recomiendo es crear los métodos iniciar_sesion y cerrar_sesion en tu QWindow de salas, las cuales hagan los siguiente:

- iniciar_sesion(user): guarda self.nombre usuario como el usuario actual y envía esa información al cliente para que le regrese su foto de perfil y luego muestra la ventana con toda la información.

- cerrar_sesion(): define self.nombre = "", deja de mostrar la foto de perfil y ejecuta QWindow.hide(), así tu programa queda en "hold" a que se haga QWindow.show() de nuevo.

Cada vez que quieras hacer QWindow.show() corres el comando iniciar_sesion(user) y si vuelves al menú anterior ejecutas cerrar_sesion() en vez de QWindow.hide().

recuerda que se debe implementar todo a través de señales.

Si buscabas algo más corto de implementar puede que te baste con colocar un if (QWindow): (el cual va a entrar al if si existe una QWindow, es decir ya se había iniciado sesión antes), entonces sólo tienes que cambiar el Qlabel con el nombre de usuario y la foto de pérfil, pero si no existe (no entra al if), entonces la creas y generas la Qlabel con el nombre de usuario.

Suerte en la tarea!

**Comment by niguzman** [comment]
mmm pucha la verdad no entendí mucho, traté de actualizarlo con settext() (ahí no me da el error pero sigue sin actualizarme lo que veo)

**Comment by jeschuwirth** [comment]
Hola!

Intenta utilizar un QWindow.update() a tu ventana donde se encuentra el Qlabel
