### ISSUE TITLE
Movimiento del personaje

### ISSUE THREAD

**Issue by rgriver** [IIC2233/Syllabus#551]
Entiendo que el personaje debe mirar al cursor en todo momento. Tambien entiendo que el mouse define el eje de referencia que el personaje usa para moverse. En el enunciado se muestra que el personaje cuando quiera moverse a la derecha o izquierda, el movimiento debe realizarse por el eje perpendicular al de referencia definido por el cursor. La duda está en que al moverse a la derecha/izquierda el eje de referencia cambiaría, pues el personaje debe mirar siempre el cursor. Considerando esto, creo que el personaje debería moverse en una curva y no como se muestra en el enunciado. Ojo que no hay problemas al moverse hacia arriba/abajo. Espero que se entienda.

**Comment by hanavarrete** [comment]
No entiendo bien tu problema. Si el personaje siempre debe mirar al cursos, no debería haber problema alguno en que se mueva a algún lado (derecha/izq) mientras mira a ese punto. Es como dar un paso al costado 😕 .

**Comment by rgriver** [comment]
La duda es si al moverse a la derecha/izquierda debe hacerlo en una recta o una curva (creo que es una curva).

**Comment by rgriver** [comment]
![Uploading IMG_0801.JPG…]()

**Comment by hanavarrete** [comment]
La verdad es que como no lo especificamos en el enunciado queda a tu criterio. Comprendo que esto debería hacer una curva, pero dijimos que sería solo a la derecha o izquierda, así que considera hacerlo en línea recta o como te parezca más adecuado

**Comment by rgriver** [comment]
Perfecto!

**Comment by monicabelen** [comment]
Con respecto al movimiento, me pasa que si sucede el evento "keyPressEvent", y al mismo tiempo trato de mover el mouse, este no se puede mover porque "keyPressEvent" está sucediendo ¿Existe una forma de solucionar esto?

**Comment by anavarro01** [comment]
Yo tenía el mismo problema de que no podía mover el mouse al presionar una tecla, pero descubrí que solo me pasa con el trackpad del notebook. Conectando un mouse lo pude solucionar

**Comment by sebacruzd** [comment]
@anavarro01 Esto es porque está configurado así tu notebook, se puede desactivar esa opción (depende de la marca del notebook en dónde se encuentra la opción).
Por ejemplo, en Dell es así. 

![touch](https://cloud.githubusercontent.com/assets/14894992/26651777/cdafc248-461b-11e7-9da1-587be81200b8.png)
El Touch Guard tiene que estar desactivado para que se puedan usar teclas y el trackpad a la vez.
