### ISSUE TITLE
Moral de cada delegación

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#551]
Hola, en el enunciado dice que el atributo moral de cada delegación es de tipo *int*, mi pregunta es si al pasar el valor del promedio de moral de la delegación (*float*) a *int* cómo es que ésta se tiene que redondear? Hasta ahora redondeo por defecto, es decir: 
54.5 ----redondear----> 54

**Comment by retamalcito** [comment]
¡Hola @Gustav2000!

Como se mencionó en la issue #345, debes tratar el valor de la moral como un `float`, por lo que no es necesario que trunques o redondees. :smile:

¡Éxito! 🏅
