### ISSUE TITLE
A que hora se van los miembros?

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#551]
En el enunciado sale que la hora de almuerzo es hasta las 3, pero igual si es que se quedan durante más tiempo podría ser que se queden hasta las 8. 
Esto ya que los snacks podrían ocurrir en ese intervalo de tiempo todavía no?

Hay que distribuirlo de alguna forma? O para simplificar la simulación podemos decir que a las 3, como ya almorzaron y les da lata ir a clase, todos se van a la casa ?

**Comment by iqacevedo** [comment]
Hola, 

Como el objetivo de esta simulación principalmente es modelar el almuerzo, puedes considerar que a las 15:00 de cada día terminan los eventos que involucran a miembrosUc y externosUC (que se van a su casa).

Saludos !

**Comment by Jiruiz2** [comment]
Ese horario es igual para todos o depende de cada persona según su horario de almuerzo?

**Comment by Kitaps** [comment]
@Jiruiz2 es igual para todos, hice una duda al respecto en otra issue
