### ISSUE TITLE
Duda modularización de consultas.py

### ISSUE THREAD

**Issue by FireGopherr5925** [IIC2233/Syllabus#551]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).

### Duda

Respecto al descuento de modularización, quería saber **que puedo hacer si mi archivo _consultas.py_ supera las 400 líneas de código.** Lo divido en dos archivos distintos mitad y mitad, o puedo dejarlo así? Cabe recalcar que **no tengo ninguna función extra en _consultas.py_ que no fueran las especificadas en el encunciado.**

**Comment by mane6867** [comment]
Hola!, puedes revisar la issue #481
