### ISSUE TITLE
Issue de dudas AC10: Networking

### ISSUE THREAD

**Issue by fdoflorenzano** [IIC2233/syllabus#551]
Esta *issue* irá acumulando las dudas junto con sus respuestas correspondientes que vayan surgiendo durante la elaboración de la AC10. De tener una duda, debes comentarla en esta *issue* y una vez respondida se actualizará este contenido.

## Dudas realizadas:

- > ¿Se pueden utilizar valores para *host* y *port* arbitrarios? ¿Se puede utilizar cualquier protocolo de comunicación?

Sí, los valores de *host* y *port* pueden ser arbitrarios. Prefieran utilizar TCP como protocolo, ya que con ese fue ideado el programa original.

- > ¿Dónde debería ejecutar el método `listen` del servidor?

Este método habilita a que el *socket* del servidor sea capaz de escuchar conexiones. Se específica en enunciado cual método de `Servidor` debe lograr eso.

- > ¿Los mensajes enviados entre servidor y cliente **deben** codificarse con UTF-8?

Pueden, pero **no necesariamente deben**. Queda a tu criterio dependiendo de como planeas enviar información entre ellos.

- > ¿Se puede modificar el código dentro de una sección marcada por "Completar"? 

Sí, no están obligados a usar lo que se deje ahí. Algunas líneas se dejan como pista de lo que hay que generar, y otras se dejan como indicios de lo que debe hacer el método, pero no necesariamente deben utilizarse tal cual (como las líneas de `mensaje.encode()` y `recv(100)`).

- > ¿**Tengo** que usar `encode` y `decode` en mi solución?

No deben, pero pueden usarlos. Si su solución serializa los mensajes de otra forma, entonces no es necesario que se utilicen esos métodos para codificar/decodificar *strings*. 

- > ¿Cómo se inicializa el código?

Ejecutándolo. Primero es necesario ejecutar el programa del servidor, y por separado de forma independiente ejecutar el programa del cliente mientras el programa del servidor sigue en ejecución.

- > ¿Cómo se ingresa la columna donde el jugador quiere jugar? 

El comando `\jugada columna` incluye la especificación de la columna donde desea jugar. Ejemplos de este serían: `\jugada 1` o `\jugada 8`. Este tipo de comandos y los otros dos se reciben en el `input` que ejecuta el método `procesar_comando_input` en `Cliente`.

- > ¿Se puede reutilizar el código encontrado en los ejemplos del material? Por ejemplo, ¿la parte para enviar mensajes de cualquier largo?

Sí, se puede. Siempre tienen ese código de referencia para su uso durante las AC y Tareas.

- > ¿Qué se entrega en el *commit* con mi progreso? ¿Todo?

No, solo es necesario entregar los archivos de extensión `.py` que se pide modificar.

- > ¿Cómo reviso que un *string* corresponda a un número entero fácilmente?

El método `.isnumeric()` de `str` retorna un *boolean* que indica si es un entero. `"23".isnumeric() is True`, pero `"hola".isnumeric() is False`

- > ¿Se puede importar `re` para verificar el *input* del usuario?

Sí, se puede.

- > En la corrección, ¿se ejecutarán ambos archivos en el mismo computador?

Sí, pueden asumir eso.

**Comment by fnberrios** [comment]
Hola! Espero estén bien. Me gustaría saber si el host y port que debo asignar al servidor a al cliente pueden ser arbitrarios. Me pregunto si al momento de revisar la actividad usaran el mismo computador,  lo digo para configurar la misma dirección IP en servidor y cliente. Además, ¿el protocolo de conexión queda a libre elección? Ya sea, TCP o UDP.

**Comment by fdoflorenzano** [comment]
Hola @fnberrios, buenas preguntas. Parece que se obviaron esos detalles en el enunciado.

Sí, el *host* y *port* utilizados pueden ser arbitrarios, y se pensó la AC para realizarse utilizando TCP. 

Para efectos de corrección, si puedes asumir que se corregirán en el mismo computador.

**Comment by eavivanco** [comment]
Hola! 
Haciendo la actividad 10, literalmente de la nada empezo a tirarme el error "OSError: [Errno 49] Can't assign requested address" y no me deja seguir corriendo el programa :(

**Comment by JuaniAndres** [comment]
Hola podemos importar re para revisar los inputs del cliente?

**Comment by fdoflorenzano** [comment]
@JuaniAndres sí, pueden.

**Comment by fdoflorenzano** [comment]
@eavivanco Hola. Falta un poco de contexto. Intenta indicar un poco donde arroja el error (línea), ¿antes no lo arrojaba?, pero recuerda no compartir tu solución. Sube a tu repositorio tus avances para que el equipo pueda verlo.

**Comment by tomasalvarez13** [comment]
Hola,no entiendo como pedir la columna al jugador. Debo crear un nuevo input?

**Comment by fdoflorenzano** [comment]
Hola @tomasalvarez13. El método `procesar_comando_input` pide un `input` donde se espera introduzcan los comandos. Específicamente, para la jugada se espera el usuario ingrese comandos de la forma: `\jugada 3`, o `\jugada 8`. En la segunda parte se indica la columna que desea jugar.

**Comment by jadawabe** [comment]
Hola, no entiendo como definimos la variable continuar en el método recibir_estado de cliente. ¿Cómo saber si el usuario quiere seguir jugando o no?

**Comment by fnberrios** [comment]
@fdoflorenzano Gracias!

**Comment by Drpinto1** [comment]
Hola @jadawabe :D

El cliente decide que no quiere continuar cuando selecciona la opción `\salir`.

**Comment by fdoflorenzano** [comment]
@jadawabe

Complementando la respuesta de Dante, tal vez tu pregunta era como identificar que valor debe tomar `continuar` en `recibir_estado`. Nota, que el método `enviar_estado` (**quien le manda información**) recibe de argumento un *boolean* que indica si debe seguir funcionado. Como dice Dante, ese valor será `False` si se recibe antes el comando de `\salir`.

**Comment by moquezada** [comment]
Hola!

Cuando se menciona que los métodos donde se envían datos mediante sockets deben servir para cualquier tamaño, ¿es válido utilizar una implementación similiar a la mostrada en los ejemplos de networking para enviar archivos? Específicamente en los que en primer lugar se envía el largo del mensaje mediante 4 _bytes_ y luego se lee la información recibida según dicho valor. Mi pregunta surge debido a que  a pesar de contar con un tamaño más que suficiente para efectos de la tarea este sigue siendo limitado.

Saludos!

**Comment by mpbascunan** [comment]
Hola, ¿los mensajes que se envían entre cliente y servidor deben estar codificados con UTF-8?

**Comment by JoacoCoyu** [comment]
Hola @moquezada 

Si! Es válido y está perfecto utilizar esa forma para enviar los datos. Al final es buena práctica realizarlo de esa manera para enviar precisamente y de manera ordenada el mensaje.

Saludos!

**Comment by ranelson1** [comment]
Hola! ¿Puedo modificar el tamaño del buffer que nos dieron (100)?

**Comment by itplanella** [comment]
Hola! En esta parte del codigo de Cliente, se puede cambiar la parte que dice "accion.encode("utf-8") o se debe dejar asi?

def enviar_accion(self, accion):
        '''Envia accion asociada a comando ya procesado al servidor.'''
        # ----------------------------------------------------------
        # Completar y usar un metodo para cualquier largo de mensaje

        mensaje_codificado = accion.encode('utf-8')

**Comment by FelipeA7** [comment]
Hola, en el código del servidor se asigna el valor de self.juego = None en la línea 27, pero en la línea 22 se utiliza la función self.esperar_conexion(), que luego ingresa a otro método donde sale escrito "if self.juego is not None"
En otras palabras, me está tirando error porque la variable self.juego se define después de ser utilizada. Puedo definir la variable antes? O puede ser que haya un error en mi código y por eso me salga este error?

**Comment by fdoflorenzano** [comment]
Hola @moquezada, claro que se puede utilizar el métodos mostrados en los ejemplos del material. Como siempre, estos están a su disposición de uso durante las ACs. Ojo que mencionas tarea, y lo que digo corre para la AC10. La tarea 3 por su parte define otro protocolo a implementar.

**Comment by fdoflorenzano** [comment]
Hola @mpbascunan. No deben necesariamente, queda a si criterio y como vean necesario generar los *bytes*. Pero si es así como deseas hacerlo, también se puede.

**Comment by jonettoh** [comment]
Hola, creo haber terminado de escribir mi codigo, pero no entiendo como inicializarlo, o sea hacer correr el servidor y el cliente, para poder partir el juego

**Comment by fdoflorenzano** [comment]
Hola @ranelson1. Por su puesto que pueden, para lograr lo pedido es necesario. Esa parte de código se encuentra en una parte que deben completar/rellenar, por lo que es completamente modificable.

**Comment by itplanella** [comment]
Hola! cuando en una jugada pongo un indice mayor al maximo, por ejemplo 15, el programa se cae. En el enunciado dice que en ninguna parte tenemos que preocuparnos por esto, por lo que queria saber si es que mientras nuestro codigo funcione para los indices correctos todo esta bien. 
Gracias de antemano!

**Comment by fdoflorenzano** [comment]
Hola @FelipeA7. Lo que me indicas no me hace sentido ya que el archivo que originalmente les damos no está como dices. No sé si me estás indicando las líneas de tu programa alterado, en cuyo caso yo no tengo como saber que línea corresponde a qué, o te estás confundiendo de archivo. 

Como les dimos inicialmente estructurado el módulo de `Servidor`, en el constructor se inicializa el valor del atributo `self.juego` y después de ejecutado ese completo se llama a `self.esperar_conexion`. Ojo, que el código que llama a este último ya se los damos escrito, fíjate al final del archivo.

**Comment by fdoflorenzano** [comment]
> Hola, creo haber terminado de escribir mi codigo, pero no entiendo como inicializarlo, o sea hacer correr el servidor y el cliente, para poder partir el juego

Hola @jonettoh. Cómo el resto de los ejemplos indicados en el material, debes ejecutar primero el programa del servidor e independientemente ejecutar el programa del cliente.

**Comment by etoteiza** [comment]
Hola! tengo una duda,

En el contenidos de ejemplos, se puede enviar datos de acuerdo al protocolo de 4 bytes indicando el largo, pero combinando con pickles y json? vale decir, en vez de enviar la información utilizando `.encode` y `.decode`. ya que con el protocolo hay que crear bytearray para ir recibiendo el mensaje, se puede perfectamente utilizar eso con pickles y json?

**Comment by fdoflorenzano** [comment]
> Hola! tengo una duda,
> 
> En el contenidos de ejemplos, se puede enviar datos de acuerdo al protocolo de 4 bytes indicando el largo, pero combinando con pickles y json? vale decir, en vez de enviar la información utilizando `.encode` y `.decode`. ya que con el protocolo hay que crear bytearray para ir recibiendo el mensaje, se puede perfectamente utilizar eso con pickles y json?

Hola @etoteiza , sí, se puede perfectamente. Queda a su criterio como generan los *bytes* transmitidos. Las porciones de `encode` y `decode` se dejan como pista de que hay que enviar *bytes*, pero no es necesario que lo usen.

**Comment by jonettoh** [comment]
gracias @fdoflorenzano

**Comment by FelipeA7** [comment]
En la línea 63 del main.py del cliente, se debe poner el booleano para continuar. No entiendo muy bien de donde sale este valor, se supone que lo debería mandar desde el servidor? Y cuando sería True o False?

**Comment by fdoflorenzano** [comment]
Hola @FelipeA7. Nuevamente, lo que me indicas no me hace sentido ya que me estás indicando las líneas de tu programa alterado, en cuyo caso yo no tengo como saber que línea corresponde a qué. 

Pero sí, el cliente cuando recibe el estado desde el servidor debe ser capaz de saber si debe continuar funcionan o no, mediante la variable `atributo`. Coincidentemente, el servidor al llamar `enviar_estado` también tiene acceso a un argumento que le indica si debe seguir funcionando el cliente o no. En el servidor ese método se llama en `interactuar_con_cliente` una vez, y varias otras en `manejar_accion`. Te recomiendo revises el código de `Servidor` y su flujo para entender cuando toma ciertos valores y cuando no.

**Comment by mpbascunan** [comment]
Para el bonus de la actividad se puede enviar primero los 4 bytes del largo pero no haberlos serializado con pickle o json?, porque si no ¿cómo se puede saber la cantidad de bytes en que esta codificado el largo del mensaje?

**Comment by fdoflorenzano** [comment]
Hola @mpbascunan, sí, por la misma observación que indicas. Cuando se dice que se debe "serializar la información a enviar" se refiere al contenido específicamente, no que absolutamente todos los *bytes* deben ser una serialización.

**Comment by Jprampad** [comment]
Hola! 
Cuando llamo a `juego.tablero_string()` para crear el tablero, éste va a ese método, de la Clase Juego, y viendo ese método no me reconoce `self.tablero()` ya que no existe ese método dentro de la Clase Juego, pero sí la variable.
Estuve harto rato probando y no pude cachar que hacer, 
gracias de antemano

**Comment by fdoflorenzano** [comment]
> Hola!
> Cuando llamo a `juego.tablero_string()` para crear el tablero, éste va a ese método, de la Clase Juego, y viendo ese método no me reconoce `self.tablero()` ya que no existe ese método dentro de la Clase Juego, pero sí la variable.
> Estuve probando y cambiando el nombre de la función de `crear_tablero()` a `__init__()` me funcionó, creo

Hola @Jprampad. En la clase `Juego` subida, nunca se hace un llamado de un método `tablero`. ¿Dónde dices que ese se ejecuta?

**Comment by Jprampad** [comment]
![Captura de Pantalla 2019-11-27 a la(s) 21 06 40](https://user-images.githubusercontent.com/49689744/69767194-e7fb7780-1159-11ea-8964-15035c43f6ba.png)
En el servidor, en el método `enviar_estado()`, el mensaje dentro llama a `self.juego.tablero_string()` y ahí me sucede ese error, por lo que no se puede imprimir el tablero

**Comment by fdoflorenzano** [comment]
> ![Captura de Pantalla 2019-11-27 a la(s) 21 06 40](https://user-images.githubusercontent.com/49689744/69767194-e7fb7780-1159-11ea-8964-15035c43f6ba.png)
> En el servidor, en el método `enviar_estado()`, el mensaje dentro llama a `self.juego.tablero_string()` y ahí me sucede ese error, por lo que no se puede imprimir el tablero

@Jprampad entonces significa que creaste en alguna parte una instancia del juego (`Juego()`) sin crear el tablero (`crear_tablero`). Si te fijas en lo entregado, en`Servidor`, en `manejar_comando` es la única vez que se instancia el juego y que luego se crea el tablero inmediatamente, luego debiste agregar por tu cuenta una instancia sin necesidad.

Recuerda que los detalles de lógica del juego en el servidor se entregan resueltos. Ten cuidado con agregar o alterar como está estructurada porque eventualmente puede traer más errores como este.

**Comment by Jprampad** [comment]
Verdad jaja, no ejecute bien el código ya que desconocía cómo iba a ser estructurado, gracias y sorry por la confusión!!

**Comment by martingallegos11** [comment]
Hola!
Al momento de enviar un mensaje desde el cliente hacia el servidor me aparece ese error y no he logrado arreglarlo :( ¿Cómo se soluciona?
OSError: [WinError 10038] Se intentó realizar una operación en un elemento que no es un socket

**Comment by pwillmer** [comment]
Hola! 
Me sale este error. No sé que puede ser.
![image](https://user-images.githubusercontent.com/53840038/69768766-87fbd580-1147-11ea-88e9-572d34db354e.png)

**Comment by lucastack** [comment]
Hola! Me ocurre el siguiente error:
Cuando el cliente se conecta al servidor se intenta ejecutar enviar_estado y al entrar en `if self.juego is not None:` me  aparece AttributeError: 'Servidor' object has no attribute 'juego', sin embargo en el init se inicia como None y por lo tanto no debería causar problemas. Espero puedan ayudarme :(

**Comment by nicoguz** [comment]
Holaa! Me aparece el siguiente error al ingresar una opción como cliente:
![Screenshot (51)](https://user-images.githubusercontent.com/53801690/69769535-f189dd00-1163-11ea-8cd1-0e3a9910a2a3.png)

**Comment by StroveLight** [comment]
> Hola!
> Al momento de enviar un mensaje desde el cliente hacia el servidor me aparece ese error y no he logrado arreglarlo :( ¿Cómo se soluciona?
> OSError: [WinError 10038] Se intentó realizar una operación en un elemento que no es un socket
@martingallegos11 
Hola!
Debido a que no diste mucha informacion de qué estabas intentando hacer, no puedo decir con certeza que fue. Pese a eso, es posible que sea debido a que cierras un socket y luego haces uso de una funcion que envia o recibe usando el socket ya cerrado.

En caso de que esta no sea la causa, me podrías dar un poco mas de detalles?, intenta de usar la funcion type() en la estructura que intentas de enviar y recibir los datos, ademas de decir que funciones estabas ocupando, ademas de subir los cambios a tu repositorio para ver si es algo mas rebuscado

Espero que esto te ayude

**Comment by DiegoPibe** [comment]
Hola, tengo 2 dudas :(

- primero, cuando intento enviar el primer mensaje del servidor al cliente sobre las opciones que este puede escoger, no me lee los últimos 2 bytes, me es muy difícil de explicar jaja pero lo subí a mi repositorio y marque con un comentario lo que hice para poder resolverlo, quería saber porque pasa eso y que puedo hacer porque como lo resolví funciona pero se que no esta bien. (es en el método recibir_estado de la clase Cliente).

- cuando ingreso el comando \juego_nuevo, el programa no hace nada y no entiendo porque, revise que hace el ultimo método manejar_acción de la clase Servidor y lo que hace es inicializar la clase Juego y luego crea un tablero mediante el método crear_tablero, finalmente usa 
" self.enviar_estado('', True) ", que dentro de ella no se actualiza la variable self.juego = None en el 
__init__ de la clase, si no es eso no se que es.

de antemano, muchas gracias.

**Comment by lucastack** [comment]
Una duda, en el init del servidor puedo hacer esperar_conexion despues de definir self.juego = None y self.socket_cliente= None ? Hacerlo en el sentidor inverso me genera error porque me deja self.juego sin definir...

**Comment by fdoflorenzano** [comment]
> Hola!
> Me sale este error. No sé que puede ser, ayuda por favor.
> ![image](https://user-images.githubusercontent.com/53840038/69768766-87fbd580-1147-11ea-88e9-572d34db354e.png)

@pwillmer, es difícil saber con poco contexto. En general ese error se lanza cuando `json` está intentando deserializar y se encuentra con algo que no sabe interpretar. ¿Estás seguro que le estás cargando un *string* que pueda deserializar? 

También, sube tus cambios a tu repo para ver el resto de tu código y tener una mejor idea.

**Comment by fdoflorenzano** [comment]
> Una duda, en el init del servidor puedo hacer esperar_conexion despues de definir self.juego = None y self.socket_cliente= None ? Hacerlo en el sentidor inverso me genera error porque me deja self.juego sin definir...

@lucastack Por esto y tu otro comentario deduzco que estás llamando al método `esperar_conexion` en el `__init__` del servidor. Nota que esto no es necesario, el programa (en la parte de más abajo) ya se te entrega armado para instanciarse y luego aceptar un cliente. El enunciado no dice que `__init__` deba aceptar a un cliente nuevo, solo dice que debe dejarlo hábil para escuchar conexiones.

**Comment by StroveLight** [comment]
> Holaa! Me aparece el siguiente error al ingresar una opción como cliente:
> ![image](https://user-images.githubusercontent.com/53801690/69769612-50e7ed00-1164-11ea-996f-ce25f76572d1.png)
> 
> Creo que tiene que ver con el "\" pero no se como arreglarlo.
> Aiuda por favor : _(

Hola!

Esto se debe a que el '\\' es un caracter usado para acciones especiales en un string, probablemente conozcas solo el '\\n', pero existen otros más. Debido a lo anterior si usas '\\juego', el programa lea el '\\j' en el programa y se de cuenta que no hay ningun caracter especial con esas caracteristicas.

Para evitar eso, puedes 'escapar' el '\\', que consiste en escribir '\\\\' en vez del '\\'. De esta forma le indicas al programa que quieres que solo se vea un '\\' en vez de que haga alguna operacion especial.

Espero que esto te ayude

**Comment by nicoguz** [comment]
> > Holaa! Me aparece el siguiente error al ingresar una opción como cliente:
> > ![image](https://user-images.githubusercontent.com/53801690/69769612-50e7ed00-1164-11ea-996f-ce25f76572d1.png)
> > Creo que tiene que ver con el "" pero no se como arreglarlo.
> > Aiuda por favor : _(
> 
> Hola @nicoguz !
> 
> Esto se debe a que el '\' es un caracter usado para acciones especiales en un string, probablemente conozcas solo el '\n', pero existen otros más. Debido a lo anterior si usas '\juego', el programa lea el '\j' en el programa y se de cuenta que no hay ningun caracter especial con esas caracteristicas.
> 
> Para evitar eso, puedes 'escapar' el '\', que consiste en escribir '\\' en vez del '\'. De esta forma le indicas al programa que quieres que solo se vea un '\' en vez de que haga alguna operacion especial.
> 
> Espero que esto te ayude

Intente hacerlo con el doble 'backslage' pero me sigue tirando el mismo error :(

**Comment by fdoflorenzano** [comment]
> Hola, tengo 2 dudas :(
> 
>     * primero, cuando intento enviar el primer mensaje del servidor al cliente sobre las opciones que este puede escoger, no me lee los últimos 2 bytes, me es muy difícil de explicar jaja pero lo subí a mi repositorio y marque con un comentario lo que hice para poder resolverlo, quería saber porque pasa eso y que puedo hacer porque como lo resolví funciona pero se que no esta bien. (es en el método recibir_estado de la clase Cliente).
> 
>     * cuando ingreso el comando \juego_nuevo, el programa no hace nada y no entiendo porque, revise que hace el ultimo método manejar_acción de la clase Servidor y lo que hace es inicializar la clase Juego y luego crea un tablero mediante el método crear_tablero, finalmente usa
>       " self.enviar_estado('', True) ", que dentro de ella no se actualiza la variable self.juego = None en el
>       **init** de la clase, si no es eso no se que es.
> 
> 
> de antemano, muchas gracias.

Sobre lo primero, el error es que al anteponer el largo del mensaje que envías para ser recibido por el cliente, antepones el margo del mensaje original, no el mensaje codificado. Mucho ojo, ya que no necesariamente son del mismo largo. Entonces, pasa que el cliente espera leer menos bytes de los que en realidad debe.

Sobre lo segundo. ¿A qué te refieres con que no hace nada? No entendí lo último que dijiste.

**Comment by FelipeA7** [comment]
Hola, tengo la actividad terminada pero de vez en cuando me pasa algo muy raro, como que la consola se queda pegada (en el servidor y en el cliente) y la única manera de volver a jugar es cerrando terminal y ejecutando el código de nuevo. Estuve probando harto y me di cuenta que probablemente es un error del computador o de python, y no un error por loop infinito o algo así, pues muchas veces se me queda pegado al repetir etapas del juego que ya he revisado que funcionan.
Qué podría estar causando esto?

**Comment by StroveLight** [comment]
> > > Holaa! Me aparece el siguiente error al ingresar una opción como cliente:
> > > ![image](https://user-images.githubusercontent.com/53801690/69769612-50e7ed00-1164-11ea-996f-ce25f76572d1.png)
> > > Creo que tiene que ver con el "" pero no se como arreglarlo.
> > > Aiuda por favor : _(
> > 
> > 
> > Hola @nicoguz !
> > Esto se debe a que el '' es un caracter usado para acciones especiales en un string, probablemente conozcas solo el '\n', pero existen otros más. Debido a lo anterior si usas '\juego', el programa lea el '\j' en el programa y se de cuenta que no hay ningun caracter especial con esas caracteristicas.
> > Para evitar eso, puedes 'escapar' el '', que consiste en escribir '\' en vez del ''. De esta forma le indicas al programa que quieres que solo se vea un '' en vez de que haga alguna operacion especial.
> > Espero que esto te ayude
> 
> Intente hacerlo con el doble 'backslage' pero me sigue tirando el mismo error :(

@nicoguz parece que regex hace la misma operacion que python, por lo tanto deberás de escapar doble, es decir, cada '\\', reemplazarlo por '\\\\\\\\\'. En python existe el raw_string, que te ayudará a cortar  la cantidad a la mitad, este se antepone agregando una 'r' al inicio de forma que:  r'\\j' = '\\\\j', tambien existe el raw_format_string, que es rf'{variable}'  (funciona como una fusion del raw y el format). Te recomiendo eso sí revisar el '\\' sin regex, y luego revisar con regex el resto para no complicarte tanto

**Comment by pwillmer** [comment]
@fdoflorenzano ya subí al repositorio los códigos

**Comment by valemaldonado** [comment]
Holaa
En la parte de manejar acción en el Servidor, no entiendo cuál es la diferencia entre la acción y el tipo de acción. Intenté printeando el argumento accion que le llega a la función manejar_accion, y me imprime el mismo comando que ingresó el cliente, por lo que acción y tipo serían iguales?

**Comment by fdoflorenzano** [comment]
> @fdoflorenzano ya subí al repositorio los códigos

Estimado, si ejecutas un *print* del mensaje que intentas hacer `loads` de, notarás que es porque está vacío: el mensaje nunca se mandó desde el cliente. Dale una vuelta al flujo del programa, tu cliente termina de funcionar antes de que se le pueda ingresar un comando, y el servidor se cae porque se quedó esperando un mensaje que nunca llegó.

**Comment by valemaldonado** [comment]
Holaa
En la parte de manejar acción en el Servidor, no entiendo cuál es la diferencia entre la acción y el tipo de acción. Intenté printeando el argumento accion que le llega a la función manejar_accion, y me imprime el mismo comando que ingresó el cliente, por lo que acción y tipo serían iguales?

**Comment by fdoflorenzano** [comment]
> Holaa
> En la parte de manejar acción en el Servidor, no entiendo cuál es la diferencia entre la acción y el tipo de acción. Intenté printeando el argumento accion que le llega a la función manejar_accion, y me imprime el mismo comando que ingresó el cliente, por lo que acción y tipo serían iguales?

@valemaldonado 

Se nombran distinto por un tema de modelación. Queda a criterio tuyo que tipo de objeto es la acción que envías de cliente a servidor, por eso el código se abstrae el tipo de objeto es, pero si pide algo mínimo que es reconocer que tipo de comando fue el que mandó el usuario. Puede ser que lo hayas modelado para que sean literalmente lo mismo, o tal vez no, tal vez `accion` retornada por `procesar_comando_input` es un objeto más complicado.

**Comment by fdoflorenzano** [comment]
> Hola, tengo la actividad terminada pero de vez en cuando me pasa algo muy raro, como que la consola se queda pegada (en el servidor y en el cliente) y la única manera de volver a jugar es cerrando terminal y ejecutando el código de nuevo. Estuve probando harto y me di cuenta que probablemente es un error del computador o de python, y no un error por loop infinito o algo así, pues muchas veces se me queda pegado al repetir etapas del juego que ya he revisado que funcionan.
> Qué podría estar causando esto?
> 
> EDIT: Seguí probando y me pasa algo muy raro, por ejemplo acabo de ejecutar el código 5 veces y en 3 de ellas pude jugar normal y en las otras 2 se me quedó pegado justo después de escribir \juego_nuevo

@FelipeA7. Es difícil saber si no tenemos acceso a tu código. Si aún tienes problemas con eso, recuerda subirlo para que el equipo pueda verlo. Me suena a que tal vez haya un problema del orden en que se envían las cosas. Intenta debuggear agregando prints de como se están enviando los mensajes. Tal vez hay algo que pasó por alto que no estás viendo.

**Comment by FelipeA7** [comment]
@fdoflorenzano Subí mi código a mi repositorio

**Comment by fdoflorenzano** [comment]
@FelipeA7 
Efectivamente me ocurre lo que indicas a veces, y el problema es un envío en bloques junto con concurrencia de programas: alguno de tus programas se queda esperando ya que espera terminar de leer bytes que le pides que lea, cuando ya los leyó todos.

Primero, al codificar no estás asegurando que los bloques sean efectivamente de 124 bytes, si queda una porción con menos que eso, queda de ese largo. Mientras que el receptor del mensaje solo lee bloques de a 124 bytes, lo cual puede generar que se pase en algunas ocasiones.

El flujo que tu esperas es alternado de alguna forma, uno envía y el otro recibe:
- Servidor envía 4 *bytes*
- Cliente lee 4 *bytes*
- Servidor envía 124 *bytes*
- Cliente lee 124 *bytes*
- Servidor envía 120 *bytes* (*)
- Cliente lee 124 *bytes*
- Servidor envía 4 *bytes*
- Cliente lee 4 *bytes*

Y en ese flujo funciona, ya que a pesar de que en (*) se envíen 120 bytes y se reciban 124, solo se leeran los 120 que fueron enviados.

Lo que pasa, es que como son programas diferentes, se ejecutan por separado y nos abes si esas instrucciones se alternan. Eventualmente puede pasar que:
- Servidor envía 4 *bytes*
- Cliente lee 4 *bytes*
- Servidor envía 124 *bytes*
- Cliente lee 124 *bytes*
- Servidor envía 120 *bytes* (*)
- Servidor envía 4 *bytes* (*)
- Cliente lee 124 *bytes*
- Cliente lee 4 *bytes* (****)

Que dos acciones de envío del servidor sean seguidas. Luego, el cliente intenta leer 124, y hay efectivamente 124 *bytes* esperando para ser leídos, entonces los lee completos, pero luego viene la última acción de lectura (****), que se queda esperando indefinidamente a que le envíen algo ya que fue leído.

**Comment by SamWeinstein** [comment]
Hola!! Tengo 2 dudas: 

1. Existe alguna manera de ejecutar el servidor y el cliente en 2 terminales distintos dentro de VSCODE? Lo que he hecho hasta ahora ha sido ejecutar el cliente en la aplicación Terminal de mac, y el servidor en el terminal de VSCODE. También intente ejecutar el servidor en la app Terminal pero sucede que me da un loop infinito en el que imprime:

Servidor iniciado. 
Esperando cliente... 
Servidor iniciado.
etc.

2. Ejecutando los archivos de la forma descrita, el main.py del cliente imprime "Cliente conectado exitosamente al servidor." , pero el servidor nunca imprime "¡Servidor conectado a cliente!", sino que se queda esperando ("Esperando cliente...").  (De todos modos cuando no ejecuto el servidor antes que el cliente, imprime "Conexión terminada." lo cual está bien, por eso no entiendo por que el servidor no se conecta al cliente) 

GRACIAS!!!

**Comment by fdoflorenzano** [comment]
@SamWeinstein 

Puedes abrir dos ventanas de VSCode, una para el cliente y otra para el servidor, y usar dos terminales separadas, una por ventana.

El comportamiento que indicas suena a que no se has completado bien aún las conexiones entre servidor y cliente, que son parte de lo que deben hacer en la AC. Revisa los métodos relacionados a la conexión en el enunciado y verifica que estes haciendo lo que se pide.

**Comment by SamWeinstein** [comment]
@fdoflorenzano Muchas gracias! Al abrir 2 ventanas de VSCode se solucionaron ambos problemas!

**Comment by calopez19** [comment]
hola!
 tengo un problema con el comando \salir, cuando selecciono esa opción el cliente se desconecta bien, pero en server surge el siguiente error:
![imagen](https://user-images.githubusercontent.com/53837383/69824614-1d03da80-11eb-11ea-9199-c3e7192c2ecc.png)
que podría hacer para arreglarlo?

gracias!

**Comment by aamartinez3** [comment]
Hola tengo una de porque me esta entregando el juego así
<img width="561" alt="Captura de Pantalla 2019-11-28 a la(s) 14 42 47" src="https://user-images.githubusercontent.com/53804101/69825452-2b9fc100-11ee-11ea-8e54-aa86de5f88f6.png">

**Comment by fdoflorenzano** [comment]
> hola!
> tengo un problema con el comando \salir, cuando selecciono esa opción el cliente se desconecta bien, pero en server surge el siguiente error:
> ![imagen](https://user-images.githubusercontent.com/53837383/69824614-1d03da80-11eb-11ea-9199-c3e7192c2ecc.png)
> que podría hacer para arreglarlo?
> 
> gracias!

@calopez19 Debe ser que por como estructuraste tu programa, se está ejecutando nuevamente el método `bind`. Este no puede ejecutarse dos veces sobre el mismo *socket*, solo una vez generalmente cuando se crea. Revisa bien lo pedido en el enunciado en las secciones de `__init__` y `esperar_conexion`.

**Comment by StroveLight** [comment]
> Hola tengo una de porque me esta entregando el juego así
> <img alt="Captura de Pantalla 2019-11-28 a la(s) 14 42 47" width="561" src="https://user-images.githubusercontent.com/53804101/69825452-2b9fc100-11ee-11ea-8e54-aa86de5f88f6.png">

@aamartinez3 Hola! Eso se debe a que se encuentra en forma de bytes. En python , algunos bytes se muestran con su caracter y otros permanecen en formato de byte al printearlos, en el ejemplo de la imagen puedes ver como los caracteres que son bytes se ven de una forma distinta al printearlos

![image](https://user-images.githubusercontent.com/48263952/69826358-871f7e00-11f1-11ea-8fa9-b4872338b653.png)

Te recomiendo echarle un vistazo al material (bytes y networking principalmente) para tener mas informacion
