### ISSUE TITLE
Fiscalización magizóologos

### ISSUE THREAD

**Issue by mestuardo** [IIC2233/syllabus#551]
¡Hola! 
Cuando utilizo la acción de fiscalizar magizóologos al pasar de día, debo fiscalizar al usuario o tambien fiscalizar y actualizar todo el resto de la base de datos? La misma pregunta para el pago

**Comment by aljara97** [comment]
Hola @mestuardo!

Esta duda ya fue respondida en la issue #309. Saludos y éxito y con tu tarea 🧙‍♂️
