### ISSUE TITLE
uso del archivo variables.py

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#552]
No entiendo bien qué cosas deben ir dentro de este archivo.  Por ejemplo, los valores que arroja la distriucion triangular para generar tiempos de llegada al campus debería estar en ese archivo e importarlo a los modulos que necesitemos usarlo? O sea debería ser algo así?

variables.py
`HORA_LLEGADA = numpy.random.triangular(left=0, mode=moda_llegada_campus, right=240)`

entidades.py
`from variables.py import HORA_LLEGADA`
`class MiembroUC(Persona):`
`...`
`self.hora_llegada = HORA_LLEGADA`

**Comment by stephichau** [comment]
sí, tal como lo pusiste :)

**Comment by bedefrunner** [comment]
Pero el enunciado dice que deben estar todas variables y probabilidades que NO estén en los archivos .csv, y moda_llegada_campus si está en los archivos, entonces HORA_DE_LLEGADA debe ir en variables.py igual o no?

**Comment by bedefrunner** [comment]
@stephichau estoy cada vez más enredado con esto jajajaj. Tengo 2 problemas:
1. Me dijiste que estaba correcto lo que escribí inicialmente, pero como te comenté arriba, la moda de llegada si está en los archivos. Entonces para poder crear la variable HORA_DE_LLEGADA en variables.py debería leer el archivo parámetros iniciales, obtener la moda de llegada y luego generar HORA_DE_LLEGADA.
2. Sumado al punto 1, por más que yo logre generar la variable HORA_DE_LLEGADA, al importar esta variable a simulacion.py para asignarsela a una persona, estaré asignándole la misma hora de llegada a todas las personas. Entonces, ¿debería hacer una funcion en variables.py que genere las horas de llegada y devuelva una HORA_DE_LLEGADA distinta cada vez que llame a esta funcion? Me parece que eso es propio de la simulación, por lo que no debería ir en variables.py
3. El punto 2 también aplica para variables que no están en parmetros_iniciales.py. Por ejemplo, el horario de llegada de un vendedor distribuye normal(mu=11:00, sigma=30), por lo que deberia ir en variables.py, pero al generar la variable TIEMPO_LLEGADA_VENDEDOR = normal(mu=11:00, sigma=30) e importarla al modulo necesario para asignarla a un vendedor, le voy a estar asignando el mismo tiempo de llagada a todos los vendedores.

Que hago?

**Comment by stephichau** [comment]
me confundí :( tienes razón, las variables **constantes** deberían ir en ```variables.py```

**Comment by bedefrunner** [comment]
Perfecto, gracias!!
