### ISSUE TITLE
QThread

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#552]
Tengo un problema existencial. Mirar los siguientes dos cogidos:

`class hola(QThread):

    def __init__(self):
        super().__init__()

    def run(self):
        t0 = time.time()
        while time.time() - t0 < 15:
            print(111)
            time.sleep(1)

d = hola()
d.start()`

`class hola(Thread):

    def __init__(self):
        super().__init__()

    def run(self):
        t0 = time.time()
        while time.time() - t0 < 15:
            print(111)
            time.sleep(1)

d = hola()
d.start()`

El primero no imprime nada y de hecho dura muy poco y el segundo imprime 111 durante 15 segundos.

Luego descubri esto:
`class hola(QThread):

    def __init__(self):
        super().__init__()
        self.g = 111

    def run(self):
        t0 = time.time()
        while time.time() - t0 < 15:
            print(self.g)
            time.sleep(1)

d = hola()
d.start()
time.sleep(15)`

Aca si se imprimen los 111 durante 15 segundos. ¿Acaso el QThread es un daemon por defecto?

**Comment by arturodelreal** [comment]
Hola 
La diferencia es porque el QThread es un "daemon thread" por defecto, a diferencia de tu instancia de hola(Thread) que por defecto parte sin ser daemon.
Saludos!
