### ISSUE TITLE
Duda orden generadores

### ISSUE THREAD

**Issue by SebaAgusto** [IIC2233/Syllabus#552]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola buenas, en la funcion de consultas anidadas tengo un error donde el orden en el que se le entregan los generadores a la funcion no es el esperado.. me explico.
 En el test4, la funcion **total_ahorrado_pedidos** debe recibir como parametros 2 generadores (generador de pedidos y generador de pizzas respectivamente), sin embargo en las consultas anidadas estos parametros se entregan al revez, lo que me genera un error. Es normal que se entreguen de cualquier forma los generadores o debo parchar ese "caso borde" para que siempre funcione independiente del orden en el que se entregan los generadores? Espero haberme explicado bien :)

**Comment by Vicente1824** [comment]
¡Hola @SebaAgusto 🫡! Dado que este caso está en los tests, deberías ser capaz de solucionar este caso borde de forma que el orden de los generadores no afecte al resultado ni haga fallar las consultas. ¡Me avisas si tienes alguna otra duda con este tema!
