### ISSUE TITLE
Modificar archivos

### ISSUE THREAD

**Issue by EmeraldMP** [IIC2233/syllabus#552]
Hola, 
escribo porque no me queda claro cuando tengo que modificar los archivos, si hay que hacerlo antes de que se cierre el programa o cada vez que se agrega un magizoologo, criatura o alimento, etc.
Saludos!

**Comment by Dnpoblete** [comment]
Hola @EmeraldMP, esta duda fue resuelta en la issue #274, para que la revises, y en caso de seguir teniendo dudas, preguntes en esa issue.

Éxito con la tarea! :smile:

**Comment by EmeraldMP** [comment]
Gracias! me quedó claro
