### ISSUE TITLE
Planilla puntajes de corrección

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#552]
Hola, no encuentro la planilla de corrección para la T01. ¿Dónde está publicada?

Saludos

**Comment by itmunoz** [comment]
Hola! El link de la distribución de puntajes es el siguiente: 
https://docs.google.com/spreadsheets/d/14YkdSyV4yCSA15LsCc29xmS9LKlXFYZ7-kFv_F6g_e4/edit#gid=489822381
