### ISSUE TITLE
Detalle sobre importación

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#552]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### En otras issues ya se ha hablado del tema...
![image](https://user-images.githubusercontent.com/66154723/120129516-21b79f00-c192-11eb-8566-343b4a1f5584.png)

### Pero, quiero saber, para acceder a un módulo que está en una carpeta anterior, se puede literalmente utilizar lo de la foto, o se debería utilizar el join de os? y en ese caso, utilizo ".." como un parámetro del join?

**Comment by tqmbanados** [comment]
Dependiendo del caso, está bien si usas from .. import x. Sin embargo, los imports relativos son *bastante complicados* y pueden generar montones de errores no previstos. En primer lugar, el ```from ..``` sólo funcionara si el módulo que esta llamando al import esta **dentro de un paquete**, con condiciones bastante específicas que no funcionan en cualquier caso. 
Un ejemplo rápido: Si corremos un archivo ```A.py```, y queremos importar un módulo ```miau.py``` de la carpeta superior, esto no funcionará bien. Para que esto funcione, ```A.py``` tiene que ser corrido como un módulo **dentro** de una carpeta superior. El motivo de esto es bastante complicado, y no sé si tiene mucho sentido entrar en explicaciones: [aquí](https://stackoverflow.com/questions/14132789/relative-imports-for-the-billionth-time) hay una muy buena respuesta por si te da curiosidad!

Tenemos la suerte que python calcula el PATH desde el archivo que se esta corriendo (incluyendo también los paquetes y librerías agregadas al path the python). Entonces, si corres un archivo ```main.py```, que tiene en la misma carpeta un módulo ```help.py```, e importas un módulo de una carpeta que tiene la línea ```import help```, te funcinonará! Por su puesto, si corres el módulo dentro de la carpeta, lanzará un error. En ese caso **si** es necesario usar funcionalidades de ```os``` y ```sys```, si revisas **la tercera respuesta destacada** en [este link](https://stackoverflow.com/questions/714063/importing-modules-from-parent-folder) encontrarás como hacerlo. En todo caso, no debiese ser necesario, por lo que si tienes algún problema con tus imports me lo puedes contar y buscamos una solución más simple.

**Comment by fernandosmither** [comment]
> Dependiendo del caso, está bien si usas from .. import x. Sin embargo, los imports relativos son _bastante complicados_ y pueden generar montones de errores no previstos. En primer lugar, el `from ..` sólo funcionara si el módulo que esta llamando al import esta **dentro de un paquete**, con condiciones bastante específicas que no funcionan en cualquier caso.
> Un ejemplo rápido: Si corremos un archivo `A.py`, y queremos importar un módulo `miau.py` de la carpeta superior, esto no funcionará bien. Para que esto funcione, `A.py` tiene que ser corrido como un módulo **dentro** de una carpeta superior. El motivo de esto es bastante complicado, y no sé si tiene mucho sentido entrar en explicaciones: [aquí](https://stackoverflow.com/questions/14132789/relative-imports-for-the-billionth-time) hay una muy buena respuesta por si te da curiosidad!
> 
> Tenemos la suerte que python calcula el PATH desde el archivo que se esta corriendo (incluyendo también los paquetes y librerías agregadas al path the python). Entonces, si corres un archivo `main.py`, que tiene en la misma carpeta un módulo `help.py`, e importas un módulo de una carpeta que tiene la línea `import help`, te funcinonará! Por su puesto, si corres el módulo dentro de la carpeta, lanzará un error. En ese caso **si** es necesario usar funcionalidades de `os` y `sys`, si revisas **la tercera respuesta destacada** en [este link](https://stackoverflow.com/questions/714063/importing-modules-from-parent-folder) encontrarás como hacerlo. En todo caso, no debiese ser necesario, por lo que si tienes algún problema con tus imports me lo puedes contar y buscamos una solución más simple.

@tqmbanados 

## Me queda una duda, al final cómo puedo hacer para que funcione el import, al correr el módulo como main, y al correrlo importado desde main a la vez?

**Comment by tqmbanados** [comment]
Para aclarar un poco tu duda: no deberías correr el archivo como main y como módulo al mismo tiempo. Al correrlo como módulo importado en un main, puedes usar los imports normalmente como si estuvieras en el mismo directorio que el módulo ```main```. 
Esto claramente es un problema si deseas correr el módulo como ```main```, por que tus imports lanzarían una excepción. En ese caso, tendrías que usar un ```if __name__ == "__main__"``` en la importación para importar con el método de ```os```, pero eso ya se volvería innecesariamente complicado. Entonces hay dos soluciones posibles: usar ese archivo **solo** como módulo (lo cual no es problema), o usar la solución propuesta en la issue #478. Esta solución es muy buena, pues así te ahorras errores en cualquier caso! En ese caso, si deseas probar ese módulo por separado, en el ```if __name__ == "__main__"``` instancias las clases con los valores que desees.
