### ISSUE TITLE
Altura según edad

### ISSUE THREAD

**Issue by Bipavez** [IIC2233/Syllabus#552]
¡Hola!
Quería saber si es que puedo hacer una función que me relate la edad con la altura. Hoy tenemos para un infante:
```python
self.altura = normalvariate(MEDIA_ALTURA_INFANTE, SIGMA_ALTURA_INFANTE)
```
Lo que para algún infante de edad entre 1-17 puede causar casos extraños como:
Alguien de 1 año mida en promedio 1.2m
Ó que alguien de 17 años mida en promedio 1.2m
Lo que propongo es algo como: 
```python
self.altura = normalvariate(MEDIA_ALTURA_INFANTE*funcion_altura_edad(self.edad), SIGMA_ALTURA_INFANTE)
```
Donde _funcion_altura_edad()_ me distribuye de alguna forma un multiplicador de altura para que así cuando la persona tenga 17 su media de altura sea ~ 170 y en el caso de las edades tempranas sea al revés.
De esta forma no molesto al archivo _parameters.py_ pero tengo un acercamiento mas 'real' a la simulación.
Cabe notar que, si _nebiland_ quiere volver a ser un lugar exitoso, no puede caer en irresponsabilidades como dejar a una persona de 2 años se meta a una montaña rusa. También, la población tendría severos problemas con bebés de _un metro_.

**Comment by leolivares** [comment]
@Bipavez 
Hola!
No es necesario que lo hagas debido a que no se especifica nada en el enunciado.
Sin embargo, si te encuentras con tiempo y deseas hacerlo, adelante. Indícalo en tu README.
Saludos!

**Comment by Bipavez** [comment]
¡Muuchas Gracias!
