### ISSUE TITLE
Duda AC10: Donde se escucha

### ISSUE THREAD

**Issue by cristozille** [IIC2233/syllabus#553]
Hola, tengo una duda. El sock.listen() del servidor se coloca en el __init__ o en esperar_conexion?
Gracias!

**Comment by fdoflorenzano** [comment]
Las dudas de la AC10 van aquí: #551. 

El método `listen` habilita a que un *socket* pueda aceptar conexiones, dónde va eso se explicita en la descripción de esos métodos en el enunciado.
