### ISSUE TITLE
Attribute error 

### ISSUE THREAD

**Issue by videvidts** [IIC2233/syllabus#553]
Tengo definido en mi cliente (en el innit) self.ventana_preparacion = VentanaPreparacion(), sin embargo cuando corro el programa me dice: 
AttributeError: 'Cliente' object has no attribute 'ventana_preparacion'.

He revisado y está bien escrito y está en mi init, que puede estar pasando?

**Comment by KnowYourselves** [comment]
Hola @videvidts!

Usualmente estos errores son por problema de flujo de tu programa, cabe recalcar que el error no miente, efectivamente cuando llegas a esa linea el atributo no está definido. Algunas de las posibles causas son las siguientes:

1. El atributo efectivamente no está deifnido. (Que al parecer no es el caso)
2. En el mismo init, antes de definir el atributo, ejecutas algún otro proceso que requiere que este esté definido (ergo, el error).

Mi recomendación con este error, es ver en qué linea llamaste a `ventana_preparacion` (la línea donde ocurre el error) y ver exactamente cual es el flujo que tu programa toma para llegar ahí. Eso podría aclarar el origen del error. 

Cuéntame como te va!
