### ISSUE TITLE
Uso función Type()

### ISSUE THREAD

**Issue by iastruque** [IIC2233/syllabus#553]
Tengo un problema, necesito imprimir que tipo de magizoólogo es ----> instancia_magizoólogo , pero al cargar los archivos no guardo eso, por ejemplo:  self.tipo_magizoólogo = 'Tareo', porque pensé que con la función type() lo podría obtener en caso de ser necesario.

Estoy intentando hacer algo así:

if type( instancia_magizoólogo) == 'Tareo':
    print('Tareo')

pero no me funciona.

Ayuda por favor

**Comment by Dnpoblete** [comment]
Hola @iastruque, creo que hay una pequeña confusión con el uso de `type()`. Lo que hace este método es retornar el tipo de argumento que se le entrega, por ejemplo, si le paso un número retornará que es un `int`, en el caso de entregarle una palabra retornará `str`, si le pasas una lista retornará `list`, etc.

Es por esto por lo que si tu haces lo que comentas, ese type te retornará que es una clase, pero nunca será igual al string "Tareo", adicionalmente abajo printeas el string "Tareo", no instancia_magizoólogo, para que tengas cuidado, ya que son diferentes.

Luego de haber aclarado esto, te recomiendo que si quieres ver que tipo de magizoólogo es, agregues el atributo que comentabas y utilices:

`if self.tipo_magizoólogo == "Tareo":`

Ya que así sí estarás comparando que el tipo sea efectivamente el string "Tareo"

Espero haber aclarado tu duda y en caso de que no se entienda me avises para poder ayudarte.
Éxito con la tarea! :smile:
