### ISSUE TITLE
Habilidad especial DCCrotona

### ISSUE THREAD

**Issue by n4chin** [IIC2233/syllabus#553]
Hola!! Cuando uso la habilidad especial de DCCrotona, ¿tengo que escoger un deportista al azar para aumentar la moral y todo? o se refiere a que solo se ganan los beneficios con respecto a delegaciones (aumenta la excelencia y respeto y ganar 100DCCoins) ?

**Comment by retamalcito** [comment]
¡Hola @n4chin!

Tu duda ya fue contestada en la issue #374, por lo que te recomiendo ir a leerla.

¡Saludos! :wave:
