### ISSUE TITLE
Proporción grupos de almuerzo random

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#553]
Hola, 

mi duda es, dado que X% son del grupo de las 13, Y% del grupo de las 14 y el resto del grupo de las 12. 
Basta con dejar a los X% primeros en ese grupo, los siguiente Y% en el grupo respectivo y el resto a las 12? O tiene que ser asignado el grupo randommente cada día?

Gracias

**Comment by iqacevedo** [comment]
Hola,

En una issue pasada se dijo que al comienzo de la simulación definan los horarios de comida para cada alumno (por lo que sería sólo al comienzo de la simulación). Ya que no se especifica quién ni cómo, puedes asignar quien almuerza en cada módulo de la manera en que quieras (siempre que respetes los porcentajes, tú forma estaría bien).

Lo que si debes tener presente es que debes calcular todos los días a que hora deciden ir a comer.

Saludos !

**Comment by Kitaps** [comment]
Ya genial
gracais
