### ISSUE TITLE
Tiempo que duran los objetos en el mapa y luego desaparecen

### ISSUE THREAD

**Issue by vcrb18** [IIC2233/syllabus#553]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Ando muy complicado viendo como hacer que los objetos duren solo cierto tiempo en mi ventana. Había pensado que se haga un QTimer cada vez que aparece un objeto, para que cuando termine se desaparezca. Sin embargo no funciona porque ocurre que cuando aparece el siguiente objeto, el timer del objeto anterior para que desaparezca aun no termina y deja la embarrada. Tampoco puedo hacer un timer que cada ciertos segundos elimine un objeto, porque este tiempo no es lineal. Es decir, si cada 3segundos aparece un objeto y estos duran 5s en el mapa, entonces los primeros dos aparecen en el segundo 3 y 6. Luego tendrían que desaparecer en el 8 y 11, y si hago un timer que empiece en el 3, los haria desaparecer en el 8 y en el 14, lo cual tampoco funciona. Estoy muy perdido ayuda

**Comment by catalina-arcila** [comment]
Hola @vcrb18, no te puede dar mucha respuesta, ya que es parte del funcionamiento de tu tarea 😣. Te recomiendo probarlo aparte de tu código y probar con otros opciones, porque las hay!!
mucho animo!!
te dejo el link de la documentación de Qtimer https://doc.qt.io/qtforpython-5/PySide2/QtCore/QTimer.html
