### ISSUE TITLE
Selección de atracción

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#553]
Hola ! 
Cuando se dice que la elección de una atracción se basa en una probabilidad que es inversamente proporcional al largo de la cola de esta , que es lo que se espera? que se haga un modelo que represente estas proporciones o quisas se referia a que fuera la fila más corta.

**Comment by IchottMano** [comment]
@sjkinast Hola!

Simplemente se busca que modeles las probabilidades de ir a una atracción dependiendo de la cantidad de personas en la fila.
Si una fila tiene menos gente, es mas probable que yo quiera ir a esa atracción a diferencia de una con una fila gigante.

Saludos!

**Comment by fpattillo** [comment]
Hola! 
Las especificidades de esto queda a nuestro criterio?
O sea, da mas o menos lo mismo cómo lo implemente con que las atracciones con menor fila tengan mayor probabilidad de atraer clientes?
