### ISSUE TITLE
Tamaño archivos testcases 

### ISSUE THREAD

**Issue by martinpint** [IIC2233/Syllabus#553]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas, estaba revisando los testcases de la tarea, y dentro del código de los testcases, desde la función 14 aprox (no me acuerdo bien) solo ponen los casos de archivos S, M y en algunas ocasiones L, pero no se prueban los XL. Entonces no sé si debería asumir que si los testcases se pasan en un tiempo reducido, aproximadamente 1 segundo, significa que están bien? o puede ser que al revisar la tarea los prueben con archivos más grandes de lo que hay en los tescases?

**Comment by Vicente1824** [comment]
¡Hola @martinpint 🙌! Efectivamente para los casos de 2 generadores solo se testeará con archivos hasta tamaño `L`, y para una consulta de 3 generadores solo con archivos hasta tamaño `M`. Esta issue es un duplicado de la #537, por lo que la voy a cerrar.
