### ISSUE TITLE
QTransform

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#553]
Hola, estoy tratando hace tiempo hacer rotar un mi label y quiero usar QTransform, ya que parece que es lo mejor para eso. 
Pero no entiendo como se hace, los ejemplos que encuentro no son de lo que busco y de la documentacion sale esto: 

A QTransform object can be built using the setMatrix(), scale(), rotate(), translate() and shear() functions. Alternatively, it can be built by applying basic matrix operations. The matrix can also be defined when constructed, and it can be reset to the identity matrix (the default) using the reset() function.

Traté de instanciar QTransform como attributo y sino usarlo directamente. 

Como se hace para usarlo? O donde puedo ver eso?

**Comment by Hernan4444** [comment]
@Kitaps te recomiendo expandir tu busqueda a rotar pixmap en pyqt4, puede que no sea lo mismo pero los ejemplos abundan (lo sé porque yo usé pyqt4 casi 1 año completo) y para este caso Qtransform entre PyQt4 y 5 no presenta casi ninguna diferencia así que te servirán mucho para resolver tu duda.

Saludos!!

**Comment by Kitaps** [comment]
Ahhh ya caxe, yo estaba tratando de girar el QLabel con el transform (y buscaba como hacer eso) gracias
