### ISSUE TITLE
Codificación envío de mensajes 

### ISSUE THREAD

**Issue by mpbascunan** [IIC2233/syllabus#554]
En el enunciado de la tarea dice que 'Para transformar strings a bytes deberías usar UTF-8' pero si yo utilizo pickle para codificar los mensajes entre servidor y cliente, ¿estaría bien para efectos de esta tarea? ya que al hacerlo de esta forma en ningún momento indico que se decodifiquen strings con utf-8. Aún así, he probado enviando mensajes con tíldes y varios caracteres, y se envían bien.

**Comment by jmwielandt** [comment]
Hola

Uno usa pickle para serializar objetos más complejos que strings, ya que estos pueden ser transformados a bytes directamente utilizando un encoding. El método `pickle.dumps` retorna una cadena de bytes, no una cadena de caracteres, así que si serializas algo con pickle, esto se envía tal cual.

Respecto al envío de strings con pickle, el enunciado exige que estos se transformen a bytes utilizando un encoding específico (UTF-8). Busca otra forma de codificar los strings ya que hacerlo con pickle no es lo que buscamos que hagan en ese punto. Si codifican un string con utf-8, deben decodificarlo con utf-8.

Saludos.
