### ISSUE TITLE
Cola de largo 0, y multiples tomas de decisiones a la vez.

### ISSUE THREAD

**Issue by mlvinay** [IIC2233/Syllabus#554]
Hola!
Ambos temas puestos en el titulo del issue los pregunto a la vez ya que:
Cuando se tiene una cola de largo 0, el inverso es naturalmente infinito, por lo que se 'DEBERIA' tomar esta atraccion sobre las otras. A la vez, si mucha gente sale de una atraccion a la vez, y todas ven esta fila de largo 0, se generaria que todas estas personas vayan a dicha atraccion.

Las preguntas entonces son:
- Si las filas son de largo 0, es posible darle simplemente un valor altisimo a su reciproco? Por ejemplo, peso 50.
- Si mucha gente va a tomar decisiones al mismo tiempo, digase que el grupo A decide ir a la atraccion B que posee cola 0. Pero ya que el toma 10 minutos tomar tal accion, la cola de B de no crece hasta que pasen estos diez minutos.  Es decir, todo el resto de los grupos ademas de A, veran que B no tendra una cola. Y todos convergeran en esta atraccion, a pesar de que posiblemente, la cola crezca MUCHO cuando todos lleguen. Es posible hacer que la cola crezca de forma inmediata al ser tomada tal decision?

**Comment by santilaguna** [comment]
Sumándome a esta pregunta, podría establecer que la probabilidad de escoger una cola de largo 1 es la misma a que si estuviera vacía (sólo en este caso para evitar la división por cero)?

**Comment by IchottMano** [comment]
@mlvinay Hola!

Tu primera pregunta queda a tu criterio mientras que tenga sentido.
Para el segundo caso la respuesta es no. Piensa que si la persona se demora en llegar a la fila 10 minutos, en ese tiempo si una persona viera la misma fila debería no ver a nadie, puesto a que aún no ha llegado nadie. Además, debes pensar en que llenar la cola de forma inmediata tendría varias repercuciones en el estado de tu simulación.

@santilaguna Nuevamente, queda a tu criterio mientras tenga sentido.

Saludos!
