### ISSUE TITLE
Duda test case por separado o todos juntos

### ISSUE THREAD

**Issue by dani-oviedo** [IIC2233/Syllabus#554]
* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola tengo una duda resulta que si corro los test case por separado me corren muy bien, pero a la hora de probar todos los test públicos, algunos me tiran error de tiempo, por ende no se que hacer al respecto, o si sera mi pc.

**Comment by NachoRinda** [comment]
Hola, ¿Estás seguro de que los tests muestran resultados distintos? A la rápida ejecute tus consultas y, por ejemplo, en el test_10 y test_12 me fallaron los mismos tests por tiempo, tanto al ejecutarlo por separado como todo junto. Revisa eso y avísame si estoy equivocado. Con respecto al tiempo de ejecución, sería raro que tu PC sea el causante de esto.

**Comment by dani-oviedo** [comment]
el test 10 y 14 son los que tienen problemas que yo se , pero por ejemplo el test 13 que esta bien por si solo cuando lo corro todo junto me tira error

**Comment by NachoRinda** [comment]
Ok, he estado probando mucho tiempo con tu código y llegué a la conclusión de que usar verbose (-v) está alenteciendoló. Pregunté y desde el equipo docente me responden que deben pasar los dos tipos de tests (por separado y todo junto), y no me contestaron si aplica o no puntajes parciales. Como mejoras rápidas que puedes hacer el try quita harto tiempo, lo comprobé con el mismo test_11 y bajó considerablemente el tiempo de ejecución. Eso si, haciendo esto no pasas los tests_S, te recomiendo implementar otra lógica en vez del try para solventar esto. Pregunté si la ejecución de los tests es con o sin las flags (-v y -b) pero aún no me responden, te informo inmediatamente cuando me digan.

**Comment by dani-oviedo** [comment]
Intenté una cosa, que fue borrar los test 10 y 14 de la carpeta de test públicos , y corriendo ahí todos los test de una con el comando incluyendo el -v y -b y me corre todo dentro del tiempo, por eso no entiendo que cuando se agrega luego estos de nuevo a la carpeta sucede ese error.

**Comment by NachoRinda** [comment]
Hola, me informa el cuerpo docente que en primera instancia se revisaría con las flags (-v y -b) pero puede ser válida una recorrección si tu código corre bien sin usar estas.
