### ISSUE TITLE
Dudas con varias estadísticas

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#554]
Perdón por la cantidad de preguntas, pero siento que está poco clara la sección _Estadísticas_ del enunciado. Voy uno por uno con las estadísticas que tengo duda:

**1. Cantidad promedio de dinero confiscado a los vendedores debido a llegada de carabineros.**
Asumo que esta es semestral. Es decir, cada vez que confisquen el stock a un vendedor, obtengo el promedio en plata confiscado (siguiendo lo que se dijo en #550) y lo voy sumando, sin importar qué día ni qué mes, y al final divido por la cantidad de veces que fiscalizó carabineros?
**2. Cantidad mínima, máxima y promedio por productos vendidos durante un día.**
Esta es diaria, según entiendo. Entonces, y como se dijo en #550, para cada día tengo que registrar la cantidad mínima, máxima y promedio vendida y al final de la simulación mostrar estos 3 datos para cada uno de los 80 días que dura la simulación?
**8. Cantidad promedio de personas que almorzó entre las 12:00-12:59, 13:00-13:59 y 14:00-15:00.**
Para esta hay que considerar la hora en que efectivamente el miembro uc se comió su comida verdad? Porque usar los horarios definidos según los valores X e Y entregados como parámetros iniciales no tendría mucho sentido.
**9. Cantidad de alumnos que no almorzaron por mes.**
Consideramos solo a los que no almorzaron por falta de plata, stock y paciencia? O también consideramos a los alumnos que llegaron después de su horario asignado para almorzar y no almuerzan por esa razón (en alguna issue salía que podíamos hacer eso)?
**10. Calidad promedio de productos de todos los vendedores por escenario.**
Acá hay que calcular por vendedor? Es decir, cada día obtenemos el promedio de calidad de los productos de cada vendedor, vamos acumulando en un contador unico para cada vendedor durante el semestre y al final de la simulación dividimos el contador de cada vendedor por la cantidad de días del semestre, entregando así tantos datos como vendedores haya? Eso es o se suma la calidad promedio diaria de todos los vendedores como un solo conjunto? Y no me queda claro lo que se dice en #550, la calidad varía con el tiempo, entonces si decido medirla para cada alimento cuando se vende, qué hago con los que no se venden? Mido su calidad al final del día?
**12. Cantidad de Productos que se descompone.**
Esta es diaria, mensual, semestral, por vendedor? O simplemente es que cada vez que se descomponga un producto, independiente a qué vendedor, se suma +1 a un contador semestral y a final de la simulación se entrega ese total?
**13. Cantidad promedio de miembros de la PUC que abandonaron una cola de espera por día.**
Asumo que esta es semestral, no diaria. Cada día sumo la cantidad de miembros que abandonaron la cola y al final de la simulación entrego ese contador dividido por 80 (la cantidad de dias)
**14. Cantidad promedio de vendedores por día que se quedaron sin stock.**
Mismo que antes

(hay premio a la issue más larga?)

**Comment by iqacevedo** [comment]
Hola,

1. Si, es tal cual dices.
2. Tienes que calcular el promedio, mínimo, maximo durante todo el semestre. Es decir tienes que mostrar solo 3 estadísticas, el promedio de productos vendidos por día, el mínimo y el máximo.
8. Es justamente cómo dices, no tendría mucho sentido usar X e Y acá.
9. Efectivamente son todos aquellos que por cualquier motivo no almorzaron.
10. Se calcula la calidad promedio de los todos los vendedores como un conjunto (es un solo dato el que debes mostrar). Cómo se dijo en #550, tienes que decidir cómo medirla, porque tienes muchas opciones válidas, lo que indicas es una opción perfectamente válida.
12. Se entrega el total no más, un contador bastaría tal como dices.
13. En esencia si. 
14. Como dices es igual que la anterior :).

(Podríamos pensarlo 🤔 jajajajajajaja) 
Quedo atento a las dudas, 
Mucho éxito en la tarea !!! 💪🏻💪🏻🎉🎉

**Comment by bedefrunner** [comment]
Muchas gracias caballero!

**Comment by bedefrunner** [comment]
@iqacevedo en la estadística 9, tengo que entregar el promedio de alumnos que no almorzaron por mes (es decir, solo 1 dato) o para cada mes la cantidad de alumnos que no almorzaron (es decir, 4 datos)?

**Comment by rihanuch** [comment]
@iqacevedo no entiendo como se sacaría el mínimo y el máximo de los productos vendidos, esto sería POR producto, o en general?

**Comment by iqacevedo** [comment]
@bedefrunner en (9) puedes tomar el promedio, aunque si despliegas los 4 datos también está correcto. En (11) para esta parte de estadísticas, si debes mostrar para cada vendedor cómo se dice ahí, aunque en otra issue mencione que para la parte de escenarios pueden tomar esa estadística como el total nomas (pero es solo para esa parte, acá se despliega para cada uno).

@rihanuch en general no más, no es necesario que sea por producto.
