### ISSUE TITLE
Problema al cargar imágenes

### ISSUE THREAD

**Issue by aeperalta** [IIC2233/Syllabus#554]
Hola, hice un par de cosas en el designer, pero tengo un problema: no sé como cargar las imágenes desde la carpeta IMGS. 
Busqué en la documentación de pyqt5 y un tutorial de QtDesigner y dice algo de poner un archivo .qrc en ese path (puse un archivo llamado xzz.qrc). Lo intenté y funcionó en el Designer, pero al cargarlo en python me tira un error (ImportError: No module named 'xzz_rc'). 
Luego tranformé el .ui a .py mediante la terminal y en los QPixmap sale simplemente en su argumento ":/nombre_de_imagen". Intenté cambiando a ":/IMGS/nombre_de_imagen" y tampoco funcionó.
En conclusión tengo dos problemas: como hacer que el designer trabaje correctamente con las imágenes de IMGS y (si no puedo hacer eso) como hacer que QPixmap tome correctamente las imágenes desde IMGS.
Estoy trabajando en macOS Sierra 10.12.5.
De antemano, gracias.

**Comment by iqacevedo** [comment]
Hola
Prueba sacandole el ":" al inicio de la ruta, si tu imagen se llama "heroe.png" prueba con `QPixmap("IMGS/heroe")` y con `QPixmap("IMGS/heroe.png")`. En este caso la carpeta IMGS deberia estar en la misma carpeta en la que se encuentra el archivo que necesita usar las imagenes.

Nos cuentas si te resulta, Saludos !

**Comment by aeperalta** [comment]
si funciona! me atrapé con algo bien simple, mala mía... saludos y gracias!
