### ISSUE TITLE
Clase Deportes

### ISSUE THREAD

**Issue by mleon17** [IIC2233/syllabus#554]
No entiendo porque esta clase tiene una probabilidad de lesionarse si cada deporte (hijas) tienen sus respectivas probabilidades de lesión, como debo relacionar las probabilidades? Gracias

**Comment by retamalcito** [comment]
¡Hola @mleon17!

La descripción que se hace en el enunciado del atributo **Riesgo** de la entidad **Deporte** es solo general; es una norma que, si te fijas, todas los deportes individuales siguen. Esto significa que no debes asignar un valor específico para este atributo dentro de la clase madre, sino que el valor se asigna en la clase hija, según lo especificado en el enunciado.

¡Saludos! 🏅
