### ISSUE TITLE
Importación en padres

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#554]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Hola!, en la AS2 en un módulo de una carpeta backend se llamó a un módulo directamente del directorio padre,
![image](https://user-images.githubusercontent.com/66154723/120131242-fdf65800-c195-11eb-9221-a92f707d0a20.png)

**Comment by tomasrosenberg** [comment]
Hola @fernandosmither!

Sí siempre funciona así porque estas abriendo desde dónde se encuentra el main y el archivo parametros, por lo tanto, mientras abras tu editor de texto en esa carpeta debería **siempre** funcionar. Respecto a la segunda duda, sí puedes utilizar esta forma en esta y próxima tareas, de hecho es recomendado para tener un archivo parametros que puedas usar en el resto de los archivos. Recuerda que las importaciones que uno realice dependen de dónde uno se encuentre en la ruta, por este motivo funciona dicha importación.

Quedo atento a cualquier otra duda y éxito en la Tarea :D

**Comment by fernandosmither** [comment]
> Hola @fernandosmither!
> 
> Sí siempre funciona así porque estas abriendo desde dónde se encuentra el main y el archivo parametros, por lo tanto, mientras abras tu editor de texto en esa carpeta debería **siempre** funcionar. Respecto a la segunda duda, sí puedes utilizar esta forma en esta y próxima tareas, de hecho es recomendado para tener un archivo parametros que puedas usar en el resto de los archivos. Recuerda que las importaciones que uno realice dependen de dónde uno se encuentre en la ruta, por este motivo funciona dicha importación.
> 
> Quedo atento a cualquier otra duda y éxito en la Tarea :D

### Para ver si lo entendí bien, al importar un módulo desde mi main, se considera el directorio actual en el que actualmente está el main?

> T2
├── app
│ .........└── folder
│ ....................      └── modulo.py
│ ....................      └── modulo2.py
└── parametros.py
└── main.py

### En la estructura anterior, si ejecuto desde main importando modulo.py, debería importar de esta forma parametros.py dentro de **modulo.py?**

#### parametros.py
```python
import parametros
```

### De ser así, cómo puedo arreglar para que también pueda correr el if name == "__main__", para hacer bugfixing más rápido? porque asumo que si pongo lo siguiente, sí debería funcionar en modulo.py, pero no si importo modulo desde main.py?


#### parametros.py
```python
import ../../parametros
```
