### ISSUE TITLE
Cerrar ventana

### ISSUE THREAD

**Issue by furzuadr** [IIC2233/syllabus#554]
Puedo asumir que no se cerrará forzadamente un cliente o el servidor?

LA forma en que tengo definida el salir de las salas, para eliminarlas o definir el nuevo jefe, no acepta que se cierre la pestaña, pero sí puse un botón de salir, para volver al lobby y de ahí otro botón para salir completamente, puedo si es que lo especifico en el readme?

Gracias!

**Comment by furzuadr** [comment]
Sé que el bonus de robustez me arregla esto, pero puedo asumirlo si es que no lo implemento?

**Comment by KnowYourselves** [comment]
Hola @furzuadr!

Como bien dices, eso está contemplado dentro de un bonus, por lo cual no hay ningún problema si no lo  haces. Con que tus ventanas tengan un botón visible y claro para devolverse está bien.

Éxito!
