### ISSUE TITLE
Uso de clases abstractas en T01

### ISSUE THREAD

**Issue by DmBeta101** [IIC2233/syllabus#554]
Hola una duda,

Es obligatorio usar clases abstractas? Ya que al inicio estaba usando ABC, pero me tiraba muchos errores y eso solucionó todo.

**Comment by moquezada** [comment]
Hola @DmBeta101,

Tu duda está resuelta en la issue #262, te recomiendo leerla completamente. Además, considera echarle un vistazo a la distribución de puntajes donde hay un ítem a evaluar sobre el uso de clases abstractas cuando corresponde.

Saludos!
