### ISSUE TITLE
Duda modelamiento de la simulación

### ISSUE THREAD

**Issue by vamussuto** [IIC2233/Syllabus#555]
Hola, tengo una duda con el modelamiento de la simulación. Tenía la idea de hacer una iteración de los días de la semana y dentro de esta realizar otra iteración que simule un día de funcionamiento del parque.
La simulación del día de funcionamiento del parque es basada en eventos discretos.
Mi duda es si al hacer la primera iteración (que itere los días de la semana) se considera una simulación síncrona.

**Comment by IchottMano** [comment]
@vamussuto Hola!

Me parece que lo que tu preguntas se responde en la issue #551 .
Si luego de leer igualmente no te queda muy claro, por favor hazmelo saber.

Saludos!
