### ISSUE TITLE
Duda de construcción del diagrama de clases

### ISSUE THREAD

**Issue by DmBeta101** [IIC2233/syllabus#555]
Hola!

Tengo unas cuantas dudas al respecto.
En el diagrama de clases como escribo si mi atributo es un diccionario que contiene clases o si mi método usa un diccionario? Por ejemplo mi diccionario que contiene DCCriaturas, eso como los escribo en el diagrama?
La otra duda que tengo, es que pasa si dentro de mi método utilizo otro método de la clase? Debo especificarlo de alguna forma?
Y la ultima duda, que pasa si mi método retorna distintas tipos de cosas, por ejemplo en cierto caso retorna un string y en otra un bool, puedo escribir metodo(): string, bool?

Gracias por la respuesta

**Comment by jeschuwirth** [comment]
Respondo tus dudas en orden:

a) No tenemos una guía exacta de diagramas de clases en el curso, mientras el ayudante entienda lo que quieres decir no hay problema, por lo tanto puedes tener por ejemplo:
`atributo: dict de 'clase'`

b) no es necesario que especifiques si un método ocupa otro método o función

c) un método o función no debería retornar 2 tipos distintos de variables, hay casos donde esto es útil pero por lo general no es recomendado, te dejo un [post](https://softwareengineering.stackexchange.com/questions/225682/is-it-a-bad-idea-to-return-different-data-types-from-a-single-function-in-a-dyna) de stackexchange donde se comenta el tema, si no tienes tiempo para cambiarlo o crees que si está bien modelado basta con que lo expliques de un modo claro.

Como respuesta general de la a y c, junto con el diagrama subes una explicación de este, por lo que cualquier punto que consideres que no queda lo suficientemente claro lo puedes explicar en el markdown.
![image](https://user-images.githubusercontent.com/37160256/79645084-1c101d00-817b-11ea-9b7a-ee8f549a851b.png)

Éxito!

**Comment by DmBeta101** [comment]
Gracias por la respuesta!

Tengo otra duda, si mi clase magizoologo tiene el atributo de sus criaturas, pero yo la cree como una lista de strings y no como una lista de clases, aun así hay una relación entre las clases? Como para unirlo en el diagrama de clases.

**Comment by jeschuwirth** [comment]
Hola @DmBeta101,

El diagrama de clases no es necesariamente igual a como implementaste la tarea, te recomiendo fuertemente que tanto en el diagrama como en tu tarea ocupes instancia de clases en lugar de una lista de strings.

En caso de solo ser una lista de strings entonces queda confusa tu modelación mago <-> criatura, pero de todos modos agregaría la relación al diagrama de clases para evitar problemas en la corrección.

Éxito!
