### ISSUE TITLE
Cambio de nombre a delegación

### ISSUE THREAD

**Issue by jocttan** [IIC2233/syllabus#555]
Hola, sé que no es relevante, pero puedo cambiar el nombre de IEEEsparta a IEEsparta? Me da cosa que tenga una E demás, y preferiría quede como con DCCrotona :(

**Comment by itmunoz** [comment]
Hola! No sé si te recomendaría hacer esto, puesto que el nombre que aparecerá en `delegaciones.csv` será siempre IEEEsparta. Puedes intentarlo, pero debes asegurarte de que no hayan problemas a la hora de leer y trabajar con los archivos `.csv`.

**Comment by jocttan** [comment]
Ok gracias!!

**Comment by gatochico** [comment]
@jocttan Dato curioso: si te deja más tranquilo, no es que IEEEsparta tenga una E de sobra, sino que es una referencia a la [IEEE](https://en.wikipedia.org/wiki/Institute_of_Electrical_and_Electronics_Engineers) 🙈  (**I**nstitute of **E**lectrical and **E**lectronics **E**ngineers)
