### ISSUE TITLE
Test 13 popularidad_mezcla_de_ingredientes

### ISSUE THREAD

**Issue by RicciCR** [IIC2233/Syllabus#555]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Mi consulta va relacionada al generador de pizzas que se entrega en los casos de correctitud, ya que hay ciertas pizzas que aparecen en los pedidos de estos test pero que no aparecen dentro de las pizzas. Esto es algo intencional?. Me parece raro ya que aunque se puede llegar a intuir que aquellas no entregadas no poseen los ingredientes no hay como saberlo. O debo de asumir que es posible que se vendan pizzas que no existen dentro de la base de datos de los zombies?. Muchas gracias de antemano.

**Comment by Vicente1824** [comment]
¡Hola @RicciCR 🙌! Efectivamente, hay casos donde hay pedidos que piden pizzas que no están en el generador de pizzas, en ese caso no podrías saber los ingredientes de la pizza. Asume que podrían haber pedidos con pizzas que no estén en la base de datos y trabaja sobre eso. ¡Espero te sea de ayuda!
