### ISSUE TITLE
Serialización con json

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#555]
Una vez que serializo algo con json, es necesario pasarlo a bytes a través de encode?
Yo tenía pensado que una vez serializado con json ya estaba listo para ser enviado a traves del socket, pero estoy tratando de mandar el string "12" (que fue serializado con json a través de json.dumps("12)) pero la consola me dice que no se pueden enviar strings.

**Comment by DCCollao** [comment]
Hola! 

Los sockets solamente pueden enviar bytes, por lo que sí es necesario que pases a bytes lo que quieras enviar. 
Te recomiendo que repases los contenidos de las semanas 12-13, específicamente lo contenido [en este archivo](https://github.com/IIC2233/contenidos/blob/master/semana-12-13/2-networking-con-python.ipynb), pues se detalla y ejemplifica la forma de enviar datos mediante sockets.

Quedo atento!
