### ISSUE TITLE
Limites distribución normal en horarios

### ISSUE THREAD

**Issue by Polea012** [IIC2233/Syllabus#555]
Del enunciado: 
"Considere que la distribución Normal no va tomar valores menores a X -1 hora y mayores a X+2 horas, es decir si almuerza entre 13 a 14, solo tomaría valores entre la 12:00 y 15:00 horas"
Sin embargo en el caso de las personas que almuerzan entre las 14 - 15 horas, la distribución podría entregar valores después de las 15 horas y nos piden que la simulación termine a las 15 horas.

¿No se podría dejar como limites para la distribución valores entre el mismo horario de almuerzo de la persona? (Por ejemplo, si almuerza entre las 14 - 15 horas, la distribución no toma valores fuera de ese rango.)

**Comment by GustavPrudencio** [comment]
eso queda a tu criterio, si la persona almuerza a las 15 horas o simplemente no almuerza, dado el caso que el tiempo de la distribución sea mayor a 15, puedes asumirlo y dejarlo expresado en el readme.
saludos.

**Comment by Polea012** [comment]
Muchas Gracias!
¿Y se podría realizar el mismo criterio en los otros rangos de horarios? (Ejemplo:Si una persona almuerza entre las  12 - 13, la distribución normal no entrega valores fuera de ese rango) ¿O solamente se puede ver en el caso de las 15 horas?

**Comment by GustavPrudencio** [comment]
si se puede, lo importante es que el criterio que utilices quede expresado.

**Comment by Polea012** [comment]
De acuerdo, Muchas Gracias !
