### ISSUE TITLE
Sobre tamaños en general

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#556]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Por último, podemos asumir una resolución de pantalla general? me imagino que si programo una ventana de 100x100 y se intenta revisar en una pantalla 4k por ejemplo, se verá mal, pero si hago una ventana de 1920x1080 y se revisa en menor resolución, va a ser mucho peor (sé que se debe usar criterio, pero solo para estar seguro)

**Comment by JadrinaDA** [comment]
Hola! No tenemos un tamaño de ventana fijo, te recomiendo usar el  necesario para que se vean todos los elementos claramente y que este todo ordenado. Sí puedes bloquear el tamaño de una ventana, prueba usando setFixedSize. Vamos a descontar si se hardcodea la posición de los obtaculos y los objetos coleccionables pero puedes harcodear la posición de los edificios en la ventana de preparación. Puedes bloquear el tamaño de objetos e imágenes, nosotros recomendamos escalar los contenidos de los labels para que se vean bonitos y no estirados. Nosotros vamos a tener tu resolución de pantalla al momento de corregir así que el o la ayudante va a cambiar su resolución para que sea igual a la tuya. Quedo atenta por si tienes más dudas.

**Comment by fernandosmither** [comment]
> Hola! No tenemos un tamaño de ventana fijo, te recomiendo usar el necesario para que se vean todos los elementos claramente y que este todo ordenado. Sí puedes bloquear el tamaño de una ventana, prueba usando setFixedSize. Vamos a descontar si se hardcodea la posición de los obtaculos y los objetos coleccionables pero puedes harcodear la posición de los edificios en la ventana de preparación. Puedes bloquear el tamaño de objetos e imágenes, nosotros recomendamos escalar los contenidos de los labels para que se vean bonitos y no estirados. Nosotros vamos a tener tu resolución de pantalla al momento de corregir así que el o la ayudante va a cambiar su resolución para que sea igual a la tuya. Quedo atenta por si tienes más dudas.
@JadrinaDA 
Perfecto!, debo avisar mi resolución en el readme, o ustedes la cambiarán a la que estimen conveniente?
Lo que principalmente me preocupa es por ejemplo en el designer diseñar los objetos un poco "al ojo" (y claro, quizás setear los valores a mano para que calcen) y eso sería muy fácil de hacer, pero a la larga no es escalable ni redimensionable, por eso me preguntaba si se consideraría mala práctica.

**Comment by JadrinaDA** [comment]
Nosotros ya tenemos tu resolución de pantalla ( creo que se preguntó en el formulario inicial) así que no tienes que ponerlo en el README. Además no te preocupes de que las cosas sean escalables porque no vamos a tocar la ventana, todo se debería ver como en tu computador. Saludos!
