### ISSUE TITLE
Putrefacciones muy altas

### ISSUE THREAD

**Issue by leolivares** [IIC2233/Syllabus#556]
Hola! Tengo una duda con respecto a la manera en que se calcula el valor de la putrefacción.
Tomando en cuenta los minutos entre las 8:00 AM y el momento en que se compran los productos (A partir de las 11:00 AM), los valores que toma la putrefacción son demasiado altos. Por ejemplo, si un miembro compra a las 11:00 AM un producto de tasa 46, los minutos serian 180, y la putrefacción resultante seria 0.98.
Esto ocurre igual para los otros productos, y las calidades siempre resultan extremadamente pequeñas.
Quería saber si esto debe ser así, o si estoy equivocado, o debe ser de otra forma.
Muchas gracias.

**Comment by AndresGarciadelaHuerta** [comment]
@leolivares Encontraste la solución? Que me pasa lo mismo con ambos valores!

**Comment by leolivares** [comment]
@AndresGarciadelaHuerta No.. pero cerré la issue porque otra persona menciono el caso en la #547. 
Aun no han respondido.
