### ISSUE TITLE
Restablecer el nivel de salud de la criatura

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#556]
Hola! 
Se qué hay muchas dudas referente a la salud total y actual de la criatura. Pero no se si en algún momento lo dijeron, pero me queda la duda aun. Al pasar al día siguiente, la salud actual de la criatura es igual a la salud total de esta? O esto solo pasa cuando recién se tiene una criatura? Me refiero a que la salud total sea igual a la actual ...

**Comment by moquezada** [comment]
Hola @Camila-sty,

Tal como indicas, eso sucede al tener una nueva criatura. Para lograr tener una salud actual igual a la salud total en un criatura existen los otros mecanismos detallados en el enunciado, pero esto no se realiza simplemente por pasar al día siguiente.

Saludos!
