### ISSUE TITLE
Eventos cercanos al termino del día

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#556]
Hola! 
En el enunciado dice que el parque cierra a las 19:00 , por lo tanto no se si hay que aplicar una restricción a los eventos que empiezan antes de las 7 y terminan después. Desde mi punto de vista y considerando el punto señalado en la Tarea  de que hay que modelar la realidad, lo lógico sería que estos eventos se realizaran hasta que terminen ya que en realidad los tiempos de cierre nunca son tan exactos y no se le negaría a una persona subirse a un juego si aun no cierra el parque.

**Comment by Hernan4444** [comment]
@sjkinast que cierre a las 19:00 es solo para asegurar que después de esa hora no llegará nadie. Como dices, puedes modelar que no le niegues a una persona subirse, pero también podemos aceptar que se les niegue porque a las 19:00 los operadores se van y la atracción queda sin vigilancia. Queda a tu criterio.

**Comment by sjkinast** [comment]
Podría hacer una restricción de que apesar de que los operadores se van a las 7 si sigue una atracció funcionado este no se puede ir?

**Comment by Hernan4444** [comment]
@sjkinast si puedes, pero al menos tienes que respetar la regla que a las 19:00 cierra el parque y eso implica que esperamos no ver que una atracción empiece a andar después de esa hora. Solo estarán funcionando aquellas que empezaron antes de las 19:00.

Saludos ✌️
