### ISSUE TITLE
Problemas con la carga de datos

### ISSUE THREAD

**Issue by gato-late** [IIC2233/Syllabus#556]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, buenas tardes!!! Tengo un problema con las funciones de la parte de carga de datos. Mi problema es que, a pesar de que estoy siguiendo lo que vimos tanto en ayudantías como en actividades (y que está también en los contenidos del curso (semana 8)), y mi código no logra cargar bien los datos. Haga lo que haga, en los tests mi generador difiere en uno o en miles de elementos en comparación con el generador esperado. Mi pregunta es, ¿qué es lo que podría estar pasando?

**Comment by Vicente1824** [comment]
¡Hola @gato-late 😀! ¿Específicamente qué tests te dan error? Como recomendación, puedes crear tu propio `main.py` (evitando subirlo a tu repositorio) e intentar ejecutar la función desde ahí, imprimiendo los resultados, y luego compara esto con los resultados esperados ¿qué tienen en común los casos que no se cargan correctamente? Revisa qué parte de la lógica de tu código podría tener un error. Sin tener acceso a tu código (no has hecho *push*) tampoco puedo saber muy bien cuál es el error. ¡Me comentas por aquí si necesitas más ayuda!

**Comment by gato-late** [comment]
el test 00 es el que me da error, el de las funciones que cargan la información de un archivo en namedtuples y retorna un generador de estas

Haré push de mi código por si es que puedes ayudarme por que también intenté haciendo prints en un archivo aparte pero no llegué a nada :(

**Comment by BoPe3p** [comment]
Hola, a mi también me pasa algo parecido, yo tengo literal código "de libro" y me tira error ya que le estoy asignando un int a '', la cosa es que cuando abro el archivo y hago un:
for linea in archivo_lineas:
print(linea)

--->Stdout:

---
No entiendo porque no me imprime nada, aparte que solo me ocurre en la carga de datos XL, el resto los pasa bien.

**Comment by BoPe3p** [comment]
Sumado a lo anterior, solo me da error en la cárga de XL de cargar_contenido_pedidos, las otras 3 funciones de cargar datos funcionan sin problema y el código es el mismo

**Comment by BoPe3p** [comment]
@gato-late Hola, ya arreglé todo, descarga denuevo la carpeta data, al menos eso me sirvió a mi, debo de haber manipulado los datos sin querer

**Comment by gato-late** [comment]
Hola @BoPe3p!!! Que bien que hayas logrado solucionar tu problema :D yo al menos sigo con el mismo problema jajajaaj y también intenté lo que me dijiste pero tampoco me resultó :( 

Aún así gracias por tus respuestas y mucho éxito con la tarea!!!

**Comment by gato-late** [comment]
Hola nuevamente @Vicente1824. Arreglé el coódigo e hice lo de los prints en un archivo aparte y todo resulta perfecto, inclusive hice manualmente las pruebas que hacen los tests internamente y resultaron bien para archivos .csv de todos los tamaños. Sin embargo, exactamente el mismo código me sigue arrojando el AssertionError con el mensaje "Diff is 1491 characters long. Set self.maxDiff to None to see it." cuando ejecuto los tests desde el archivo consultas.py. ¿A qué se podría deber esto?
