### ISSUE TITLE
Imprimir y Guardar Puntajes de Competencia

### ISSUE THREAD

**Issue by tqmbanados** [IIC2233/syllabus#556]
Hola!

¿Es necesario imprimir los puntajes obtenidos por los deportistas en cada competencia?
También, ¿Se deben guardar en resultados.txt estos puntajes, o sólamente quien ganó y perdió en cada competencia?

Gracias!

**Comment by jitorcas** [comment]
Hola! @tqmbanados 

Con respecto a imprimir los puntajes después de cada competencia, si bien no está explícito en el enunciado, lo podrías hacer para tener un respaldo de los resultados que se van obteniendo. 
No es necesario guardar los puntajes en `resultados.txt`, pero queda a tu criterio, siempre respetando la información mínima que se pide.
