### ISSUE TITLE
> Hola, tengo 2 dudas :(

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2233/syllabus#556]
> Hola, tengo 2 dudas :(
> 
>     * primero, cuando intento enviar el primer mensaje del servidor al cliente sobre las opciones que este puede escoger, no me lee los últimos 2 bytes, me es muy difícil de explicar jaja pero lo subí a mi repositorio y marque con un comentario lo que hice para poder resolverlo, quería saber porque pasa eso y que puedo hacer porque como lo resolví funciona pero se que no esta bien. (es en el método recibir_estado de la clase Cliente).
> 
>     * cuando ingreso el comando \juego_nuevo, el programa no hace nada y no entiendo porque, revise que hace el ultimo método manejar_acción de la clase Servidor y lo que hace es inicializar la clase Juego y luego crea un tablero mediante el método crear_tablero, finalmente usa
>       " self.enviar_estado('', True) ", que dentro de ella no se actualiza la variable self.juego = None en el
>       **init** de la clase, si no es eso no se que es.
> 
> 
> de antemano, muchas gracias.
@DiegoPibe 

Sobre lo primero, el error es que al anteponer el largo del mensaje que envías para ser recibido por el cliente, antepones el largo del mensaje original, no el mensaje codificado. Mucho ojo, ya que no necesariamente son del mismo largo. Entonces, pasa que el cliente espera leer menos bytes de los que en realidad debe.

Sobre lo segundo. ¿A qué te refieres con que no hace nada? No entendí lo último que dijiste.

_Originally posted by @fdoflorenzano in https://github.com/IIC2233/syllabus/issues/551#issuecomment-559306992_

**Comment by DiegoPibe** [comment]
me refiero a que, me acepta el input que le entrego y no me arroja error, no me imprime nada, no me termina el programa... la siguiente linea esta en blanco como si estubiese esperando algo.

**Comment by fdoflorenzano** [comment]
Es por como extrajiste el tipo de acción en `Servidor`, el tipo que llega no calza con ningún caso del `if` y resulta en que no hace nada.
