### ISSUE TITLE
Clase Jugador

### ISSUE THREAD

**Issue by vcrb18** [IIC2233/syllabus#557]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, estuve buscando en las otras issues y no encontré una duda tan específica como la mía y es la siguiente. Tengo dudas como con la modularización podría decirse de mi clase jugador. Tengo planeado trabajar con una clase que tenga atributos por ejemplo como nombre, puntaje, vida etc. El tema es que necesito básicamente acceder a esta clase a través de todas las ventanas y poder editar los atributos de esta y poder cambiar labels de la ventana según los atributos de esta clase. No sé cómo hacer esto, no sé si ando confundido por la cantidad de horas de programación que llevo encima, o porque no sé como aplicar este conocimiento con interfaces ya que nunca lo he hecho antes. 
En resúmen necesito poder acceder a atributos de una clase desde cualquier ventana, editarlos, y que estos editen labels de la ventana.
Espero que se entienda la duda y quedo atento!

**Comment by JadrinaDA** [comment]
Hola! Lo que puedes hacer es usar señales, de esta forma lograrás activar ciertas funciones de esta clase sin tener que importarla a cada ventana. Además conectas todas las señales a una misma instancia de una clase jugador así te aseguras que es el mismo objeto. Avísame si te quedan dudas. Saludos!

**Comment by vcrb18** [comment]
Te entiendo, pero no tengo claro como instanciar la clase. No sé bien como explicarme, por ejemplo si tengo la clase creada en un archivo py parte del backend, donde cada vez que se introduce un nombre, instancio la clase jugador. Ahora si quiero conectar una señal desde la ventana juego a esa instancia, no sé como acceder a ella, no sé donde debería guardarla. Quizás sería mejor instanciarla en el main pero tampoco sabría como hacer eso ya que ahí solo se instancian.

**Comment by JadrinaDA** [comment]
Hola! Perdón por la tardanza. Podrías crear la instancias y luego solo cambiar sus atributos en base a lo que conteste el jugador. También puedes pasarles a la ventanas la instancia del jugador al abrirlas o instanciarlas y guardar esta como un atributo. Hay muchas formas de hacerlo. Te recomiendo que pruebes y veas lo que te sirve mejor. Éxito!
