### ISSUE TITLE
Aparicion de subditos

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#557]
en el enunciado dice que
""" Cada 10 segundos se agregaran 5 subditos:
 cuatro normales y uno grande """
podriamos modificarlo a que cada vez que mueren reaparecen cada 10 seg. 
porque siento que si en el juego me dedico a arrancar se llenaria de subditos,
o no?

**Comment by hanavarrete** [comment]
La idea es que se llene de súbditos!, cosa de poder acumularlos y avanzar con más tropas 😄

**Comment by Hernan4444** [comment]
@Dunkan1 tal como dice hanavarrete la idea es que se llene de subditos lo que si puedes editar es la cantidad de segundos, puesto que es una constante (que estará en tu archivo de constantes) y darles mas tiempo si es que no quieres que reaparezcan cada tan poco segundos.

**Comment by Dunkan1** [comment]
jajajaja ok.
