### ISSUE TITLE
cliente  bool continuar

### ISSUE THREAD

**Issue by mpsubiabre** [IIC2233/syllabus#557]
hola!
En la funcion recibir_estado del cliente, no entiendo de donde sale la variable continuar, porque solo el  mensaje llega desde el servidor. Entonces deberia enviar ademas del mensaje, el booleano de continuar o no ?
gracias.

**Comment by fdoflorenzano** [comment]
Hola @mpsubiabre , esto ya se preguntó en la issue de la AC10: #551
