### ISSUE TITLE
Consultas ayudantía 11: Interfaces Gráficas BackEnds - FrontEnds

### ISSUE THREAD

**Issue by glbello** [IIC2233/Syllabus#557]
[Pueden cambiar el título si desean] Saludos, quedé con varias dudas respecto a la ayudantía pasada y aunque tal vez me digan que debo buscar los conceptos en internet, quería aludir de todas formas a los ayudantes de buen corazón, respecto a:

* BackEnd y FronEnd se les dio atributos de clase como: 

BackEnd:
``` python
class Character(QObject):
    trigger_move = pyqtSignal(MoveEvent)
    trigger_respuesta_ingreso = pyqtSignal(IngresoEvent)
```
FrontEnd:
``` python
class Ventana(QWidget):
    trigger_ingreso = pyqtSignal(IngresoEvent)
    trigger_mover = pyqtSignal(MoveEvent)
```
Sé que está explicado en la referencia en el código pero sigo sin entenderlo, además de no entender los pyqSignals que aparecen específicamente aquí.

* En el FrontEnd no entiendo el fin de ```self.trigger_ingreso.emit(IngresoEvent(self.ingreso_usuario.text()))```
En el código:
``` python
    def ingresar(self):
        self.ingreso_usuario.hide()
        self.boton_ingreso.hide()
        self.trigger_ingreso.emit(IngresoEvent(self.ingreso_usuario.text()))
```
* En el BackEnd no entiendo la utilidad del ```parent``` en esta parte del código:
``` python
class Character(QObject):
    trigger_move = pyqtSignal(MoveEvent)
    trigger_respuesta_ingreso = pyqtSignal(IngresoEvent)

    def __init__(self, parent, x, y):
        super().__init__()
        self.nombre = ""
        self.position = (x, y)
        self.trigger_respuesta_ingreso.connect(parent.comenzar)
        self.trigger_move.connect(parent.actualizarImagen)
```

**Comment by mjgutierrez1** [comment]
Hola, yo también tengo las siguientes dudas:

1) ¿Por qué en el método ingreso del BackEnd se hace self.trigger_respuesta_ingreso.emit(IngresoEvent(self.nombre)) en vez de simplemente devolver el mismo evento que recibió ese método como argumento?, es decir, haber hecho self.trigger_respuesta_ingreso.emit(event).

2) ¿Por qué se hace ese proceso extra de llamar al método ingreso del BackEnd para que este devuelva el mismo evento que recibió, en vez de en el método __setUp del FrontEnd hacer directamente self.trigger_ingreso.connect(self.comenzar)? Eso hubiera cumplido exactamente la misma funcionalidad del código actual, pero sin tener todo el código extra del BackEnd.

**Comment by fringlesinthestreet** [comment]
@glbello @mjgutierrez1 Hola :)

La idea del `parent` en el BackEnd es poder conectar las señales con métodos del FrontEnd, sin la necesidad de guardar `parent` como un atributo (para evitar referencia circular).

La idea de hacer ```self.trigger_ingreso.emit(IngresoEvent(self.ingreso_usuario.text()))``` es gatillar la respuesta en el Backend. Así se llama al método `ingreso` del BackEnd, pasándole el evento `IngresoEvent` con la información necesaria para que realice lo suyo (en este caso sólo guarda un atributo).

En la ayudantía, el BackEnd es súper simple (Así que tienen razón en que no tiene mucho sentido realizar ese "proceso extra"), pero imaginen que se deban instanciar objetos o guardar información. En ese caso es útil conectar el BackEnd con el FrontEnd a través de señales. Estas señales pueden contener eventos distintos a los que el FrontEnd les envió en un principio, para transportar distinta información (En este caso la información que debía enviarse era la misma).
