### ISSUE TITLE
Problema con boton en Qformlayout

### ISSUE THREAD

**Issue by mjespinoza** [IIC2233/syllabus#557]
Holaa, estoy haciendo la ventana en que se muestran las salas disponibles, para esto hice un Qformlayout, la cosa es que cuando hago Qformlayout.addrow(numero_jugadores,boton), en la interfaz solo se muestra el texto del boton, pero no el boton en si.

**Comment by jeschuwirth** [comment]
Hola!

Eso puede ser un error de como haces el Qformlayout.addrow(), intenta:

- FormLayout.addRow(QLabel("sala X"),  QPushButton)

Si no te sirve avisa para intentar ayudarte.

**Comment by mjespinoza** [comment]
no me funciono :c

**Comment by jeschuwirth** [comment]
![image](https://user-images.githubusercontent.com/37160256/59645576-9da0b400-9140-11e9-968c-2e0b4c312f93.png)
Aquí hice un pequeño código que agrega un botón con su label a un Formlayout, espero que te sirva para solucionar tu problema

**Comment by mjespinoza** [comment]
eso me funciono, creo que el problema es cuando hago scroll_area.setwidget(widget_que_contiene_al_form)
