### ISSUE TITLE
Duda atributos abstract class

### ISSUE THREAD

**Issue by Mariana-Ortega-del-Rio** [IIC2233/Syllabus#557]
Quiero crear una clase abstracta que tenga atributos que todas las clases que heredan de esta deben tener. 
Esto es lo que he estado haciendo:

```python
from abc import ABCMeta, abstractmethod

class Ovni(metaclass=ABCMeta):

    def __init__(self, nombre, apellido):
        self.nombre = nombre
        self.apellido= apellido

Mari = Ovni("mari", "ortega")
```
El problema es que al correr esto SÍ me deja instanciar a Mari sin ningún problema y siendo que es una clase abstracta esto no se debería poder hacer. He leído harto sobre @abstractproperty o ocupar @property y en la siguiente linea @abstractmethod y nada me funciona. No se si es un error conceptual y no se puede hacer o no.

Gracias de antemano!!
Saludos,
Mari

**Comment by rihanuch** [comment]
¡Hola @Mariana-Ortega-del-Rio !

No tienes ningún error conceptual 🤷‍♂️ (según lo que tengo entendido), voy a revisar y te doy la respuesta lo antes posible

¡Saludos! 🍀

**Comment by rihanuch** [comment]
@Mariana-Ortega-del-Rio , 

Probé con como tu lo planteas, y me ocurre lo mismo, pero si lo haces de la siguiente manera va a funcionar:

```python 
from abc import ABCMeta, abstractmethod

class Ovni(metaclass=ABCMeta):

    def __init__(self, nombre, apellido):
        self.nombre = nombre
        self.apellido= apellido

    @abstractmethod
    def mari_hace_algo(self):
        '''abc mari hace algo'''
        pass

Mari = Ovni("mari", "ortega")
```

Al parecer la el ```ABCMeta``` funciona correctamente cuando se explicita al menos un ```abstractmethod```

¡Éxito programando!

**Comment by Mariana-Ortega-del-Rio** [comment]
woooow muchas gracias!!!
Saludos!

**Comment by Pipelao** [comment]
Hola :)
Tengo una pregunta con definir un @abstractmethod, ¿de qué me sirve si de todas formas tengo que hacer overriding en la subclase?, por lo que tengo entendido, lo que haga en la función que se decora con @abstracmethod no se hará una vez que ocupe esa función en una instancia o no? 
Gracias de ante mano

**Comment by jfbahamondes** [comment]
Hola @Pipelao !
Un método abstracto sirve para tres cosas principalmente:
1. Para definir una clase como abstracta, ya que basta con que la clase tenga un método abstracto. (Tiene que heredar también de ABCMeta ya directamente o de una clase que herede de esta).
2. Para obligar a una clase que ocupe la clase abstracta a sobreescribir el método abstracto. Esto es importante si deseas llevar a cabo una buena modelación (así no se te pasan esos métodos en la creación de clases).
3. Al trabajar en conjunto con otros programadores te puedes asegurar de que si de alguna forma ocupan tu clase abstracta, entonces se aseguren de tener los métodos abstractos que definiste. (Muy relacionado con el punto 2).

Saludos, cualquier cosa que no haya quedado claro me avisas.
