### ISSUE TITLE
Prueba de código

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#557]
Probando que todo funcione bien, me di cuenta que si se registra un nuevo usuario y pasa al siguiente día de inmediato, tiene un nivel de aprobación de 100 y por ende se convierte en Super de una xd. Esto debería ser así?

**Comment by matiasmasjuan** [comment]
Hola @dlmed 

Recuerda que al momento de ***pasar al día siguiente***, existe la **probabilidad** de que tu/s ***DCCriaturas*** se **escapen**, lo que afectaría en el **nivel de aprobación** y por ende no sería igual a **100** en todos los casos. Si esto te pasó, **fue mera coincidencia** 😅 , ya que no debería **suceder** en el 100% de los casos.

Saludos! 😄

**Comment by dlmed** [comment]
Ahhh
