### ISSUE TITLE
Tarea extra.

### ISSUE THREAD

**Issue by nhorellana** [IIC2233/syllabus#558]
Hola! Hace un tiempo mandaron un mail sobre una tarea extra que publicaran con plazo de una semana, esta tarea que porcentaja de la nota final tendra o como afectara la ponderacion del curso? 

Saludos!

**Comment by iqacevedo** [comment]
Hola !

Como salia en el anuncio, podrán obtener hasta 3 décimas para el promedio de tareas.

Saludos !
