### ISSUE TITLE
Paciencia

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2233/Syllabus#558]
Me nace la duda si es importante que todos los clientes tengan este parametro , ya que si un niño pierde su paciencia no hace salir al grupo completo de la fila  y tampoco se puede quedar abajo por que es peligroso , por lo que puedo hacer el supuesto que como el adulto manda solo el debe tener este atributo y saber si quiere subirse a la atraccion?

**Comment by pcseisdedos** [comment]
Yo entendí que la paciencia era un atributo de los clientes (los niños también son clientes) entonces para un grupo calculo el mínimo de paciencia, y en base a eso determino cuando se saldría de la cola el grupo, también se puede hacer de esa forma?
