### ISSUE TITLE
Es por como extrajiste el tipo de acción en `Servidor`, el tipo que llega no calza con ningún caso del `if` y resulta en que no hace nada.

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2233/syllabus#558]
Es por como extrajiste el tipo de acción en `Servidor`, el tipo que llega no calza con ningún caso del `if` y resulta en que no hace nada.

_Originally posted by @fdoflorenzano in https://github.com/IIC2233/syllabus/issues/556#issuecomment-559309975_

**Comment by DiegoPibe** [comment]
muchas gracias, resolví los 2 problemas con lo que me dijiste, una ultima pregunta... 

- cuando ingreso el comando " \salir " el programa no termina sino que continua con otro input que imprime el " -> " correspondiente, al ingresar un nuevo comando, me arroja un error que dice que se anulo la conexión establecida, eso esta bien así o hay algo que tengo mal ?.

de antemano, muchas gracias.

**Comment by fdoflorenzano** [comment]
Estimado, es la segunda issue completa que abres solo para responder sobre la misma duda. No entiendo como estás respondiendo, pero ten cuidado y por favor cierra ambas cuando resuelvas esto para evitar exceso de información en la plataforma.

Sobre lo último que mencionas, parece ser un error de tu código al manejar los comandos del usuario. Te recomiendo revises esa parte y veas que se está ejecutando.
