### ISSUE TITLE
¿Qué almuerzan los miembrosUC?

### ISSUE THREAD

**Issue by AndresGarciadelaHuerta** [IIC2233/Syllabus#558]
No he podido encontrar en el enunciado algo que especifique bajo qué criterios eligen qué almorzar los miembrosUC. Se llevan el más barato? o simplemente se llevan todo lo que pueden según el saldo que tengan? o da lo mismo con tal de que sólo pueden disminuir el stock del vendedor en 1 unidad? La verdad es que no lo tengo para nada claro y si alguien me lo puede explicar/aclarar me sería de mucha ayuda! Gracias!

**Comment by Arcoirisky** [comment]
Hola!
Los funcionarios compran lo que sea que les alcance con su dinero. Queda a tu libertad :D Recuerda especificarlo en el README y cuida que no incumpla lo que dice el enunciado :D

**Comment by AndresGarciadelaHuerta** [comment]
@Arcoirisky Perfecto, gracias por responder !!
