### ISSUE TITLE
duda sobre tests carga de datos

### ISSUE THREAD

**Issue by bernarditaaliaga** [IIC2233/Syllabus#558]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Acabo de leer un issue parecido a este porque me esta pasando lo mismo de que unas pocas funciones fallan en la carga de datos, sin embargo igual quería preguntar, las fallas por carga de datos ocurren por que algo esta mal implementado en mis funciones generadoras? o es la misma funcion no generadora la que falla en algo?

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Gcamposbriceno** [comment]
Hola!

No entiendo muy bien tu pregunta, los test de carga de datos principalmente se fijan en que, una vez que tu función pasa los tests de correctitud con los datos que estos le pasan, también sea capaz de funcionar correctamente con los datos que tú cargas al programa. Cuando estos tests fallan, si al mismo tiempo pasas los tests de correctitud, es posible que los datos no estén siendo cargados de manera correcta al leer los archivos .csv. Si no pasas los tests de correctitud, difícilmente vas a pasar los de carga de datos ya que la función no está haciendo lo que se le pide.

Espero haber contestado tu pregunta, si tienes más dudas puedes comentar aquí.

**Comment by bernarditaaliaga** [comment]
pero esto ' es posible que los datos no estén siendo cargados de manera correcta al leer los archivos .csv' se debe a un error en una de mis funciones generadoras o a la funcion especifica de consulta con la que estoy trabajando? porque el test 00 de cargar datos me funciona perfectamente, entonces no entiendo porque al estas ser las encargadas de cargar los datos no se están cargando bien en mis otras funciones

**Comment by Gcamposbriceno** [comment]
Si el test de carga de datos funciona, lo más probable es que haya un problema en las funciones específicas que fallan. Intenta ir imprimiendo las instancias que uitilizas en tu función para ver si coinciden con lo que el test espera o si quizás hay que cambiar algunas cosas.
