### ISSUE TITLE
Éxito al sanar con puntos de salud actuales mayores a nivel mágico

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#558]
Hola, es posible que los puntos de salud actuales de una criatura sean mayores al nivel mágico de un mago? de ser así, al intentar sanar, siempre daría una probabilidad de éxito = 0.

**Comment by moquezada** [comment]
Hola @dlmed,

Sí, es posible. Por ejemplo, el nivel mágico de los Magizoólogos Híbridos varía entre 35 y 45, mientras que los puntos de salud total de un Augurey pueden estar en el mismo rango de 35 y 45 🤔

Saludos!
