### ISSUE TITLE
Duda sobre borrar imagen de un QLabel

### ISSUE THREAD

**Issue by Piolawa** [IIC2233/syllabus#558]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, en el label donde tengo al personaje que selecciona el usuario intento borrar una imagen de movimiento antes de colocar la otra, pero solo se superponen y no se que me está fallando.
Intenté borrar el label con `clear()` y `setText("")` 😢

**Comment by clementevalladares** [comment]
Hola @Piolawa, si lo que quieres es cambiar el sprite actual de un personaje, debería bastar con solo hacer `.setPixmap()` al QLabel del personaje con el nuevo `QPixmap()` que le quieres poner. Esto hará el cambio solo.
`personaje.setPixmap(QPixmap("path_nuevo_sprite"))`
De todas formas, recuerda subir lo que llevas a tu repositorio en github para que pueda ver si el problema se trata de algo diferente.
Espero que con eso se solucione tu problema.

**Comment by Piolawa** [comment]
Hola @clementevalladares, justo eso hago y me superpone las imágenes :c, acabo de subir lo que llevo al repositorio

**Comment by clementevalladares** [comment]
Disculpa la demora @Piolawa. Estuve revisando todo, el problema es que no se actualiza porque definiste la imagen de los personajes dentro del styleSheet en Qt Designer. Puedes arreglar esto eliminando el styleSheet que habías puesto y agregando el pixmap directamente desde la opción pixmap que está en Qt Designer:
![image](https://user-images.githubusercontent.com/69611854/120232545-c2a16b00-c221-11eb-957e-a52a1b6f4e40.png)
Luego.
![image](https://user-images.githubusercontent.com/69611854/120232696-14e28c00-c222-11eb-8513-8d2a8df24cda.png)

La otra opción, es que crees el QLabel de los personajes directamente desde tu programa y no en Qt Designer. Te recomiendo esto último para que puedas parametrizar y cambiar fácilmente tamaños y posiciones de inicio de tus personajes sin tener que estar cambiando los archivos .ui cada vez. Pero si te acomoda más la primera opción también es válido.
Avísame en caso de que estas soluciones no te funcionen.

**Comment by Piolawa** [comment]
Muchas gracias @clementevalladares , tomé la segunda opción, y quedó mucho mejor el código :smile:
