### ISSUE TITLE
Duda con probabilidad Sanar lesion

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#558]
Hola! tengo un par de dudas respecto a la formula de probabilidad de lesion, el numero que me de esta formula tiene que ser igual a otro aleatorio que tendré que sacar? o si me toca la probabilidad = 1 significa que puedo sanar ?

**Comment by Njcampos1** [comment]
por ejemplo si el riesgo del deporte es de 0.3, puedes hacer un random.uniform(0, 1), si el numero generado es menor a 3, el deportista se lesiona. :D

**Comment by amparostevens** [comment]
Hola @Natydlb! 

Es tal como dice @Njcampos1 y como sale en la issue #348
