### ISSUE TITLE
Duda test_13 función popularidad_mezcla_de_ingredientes

### ISSUE THREAD

**Issue by TarzanDeMaceta** [IIC2233/Syllabus#559]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, la función popularidad_mezcla_de_ingredientes es la última que me falta de las funciones que reciben generadores y hay un test que me falla y aun no se porque, el test 5. He revisado a mano algunos datos en la base de datos, pero sigo sin ver el error.  Lo raro es que los otros test_cases están bien (adjunto foto), lo que tampoco me da una pista del error. Pregunto si seria posible que algún ayudante revise mi código y me de un hint del error.

![image](https://github.com/user-attachments/assets/e119e3fb-533a-4070-b497-14806590c1e3)

![image](https://github.com/user-attachments/assets/d9b4976c-a1ee-4448-8796-51a72b945ecd)

Quedo atento sus respuestas y gracias de antemano
Saludos

**Comment by xperseosses** [comment]
#454

**Comment by Vicente1824** [comment]
¡Hola @TarzanDeMaceta 😁! Exactamente lo que dijo @xperseosses, revisa el último comentario de la issue #454 (se agregó un nuevo test de correctitud, ¡para más información revisa el cambio 2 realizado el 5 de octubre en el *README* de la tarea y recuerda realizar *pull*! Cerraré la issue ya que es un duplicado.
