### ISSUE TITLE
Pintar sobre qlabel

### ISSUE THREAD

**Issue by cmarquez1** [IIC2233/syllabus#559]
Lo que pasa es que trto de pintar sobre un qlabel, y al hacer drawpoints para que me haga los puntos del juego, hago dos for para hacer los puntos en las posiciones horizontales y verticales, sin embargo solo me me aparecen los ultimos puntos del ultimo for (me pintan los puntos de abajo solamente). Lei que tiene que pintar sobre algún widget que herede de QPaintDevice. Al igual que intente darle un Qpixmap vacio (ya que no tengo ninguna imagen para darle) al label. Sin embargo no cambia en nada.

**Comment by jeschuwirth** [comment]
Hola!

Perdón si nos atrasamos en responder la issue, pero es algo dificil de entender el error. 

Al parecer tu problema no es con Qpixmap o QPaintDevice, sino que tu forma de iterar sobre las filas y columnas no es la correcta. Si sigues teniendo el problema, podrías subir tu código al repositorio para mirarlo más facilmente?
