### ISSUE TITLE
Una función no se comporta como quiero

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#559]
Hola, tengo una función que lo que hace es que, en caso de un error de input, llama de nuevo a la función que le pasen como argumento. El tema es que, cuando hago este procedimiento:
- llamar a función 1 (que debe retornar un valor)
- error de input
- llamar_denuevo(funcion 1)
- ahora si el input es correcto

No pasa nada, lo cual estoy pensando es porque tengo algo así (de forma simplificada):
```python
def funcion_a():
    valor = funcion_1()

def funcion_1():
    input1 = input(' ')
    if input1 == 'algo':
        return 1
    else:
        llamar_denuevo(funcion_1)

def llamar_denuevo(func):
    func()
```

Entonces lo que creo es que en `llamar_denuevo()` debería poner `return func()`, pero no se, ya que ocupo esta función (`llamar_denuevo()`) para otras funciones que no retornan nada, entonces no se si al hacer esto me va a dar error en esas funciones.

**Comment by KnowYourselves** [comment]
Hola @dlmed!

El problema con tu función, es que al caer en el `else` y llamar a la función `llamar_denuevo`, no estás haciendo `return`. Esto quiere decir que llamaras de nuevo a la función, si, y recbiras un valor, pero ese valor no llegará a ningun lado. Podrías ser más directo y hacer que `funcion_1` simplemente sea recursiva y se llame a si misma: 

```python3
def funcion_1():
    input1 = input(' ')
    if input1 == 'algo':
        return 1
    else:
        return funcion_1()
```
Esto  si logra lo que quieres, que es que cada vez que el usuario no ingrese _input_ valido, se llame a la función de nuevo **retornando su resultado**.

El único problema con este _approach_ a validación de _input_ es que en ningun lenguaje de programación puedes llamar a infinitas funciones, si llamas a demasiadas funciones ocurrirá un error llamado `StackOverflow`. Es por esto que se recomienda mejor hacer un ciclo que le pregunte _input_ al usuario hasta que ingrese algo válido.

Espero haberte ayudado!

**Comment by dlmed** [comment]
Si, el tema es que en llamar_denuevo() hago otras cosas, que aquí no puse, pero pregunta si es que se quiere intentar denuevo, volver o salir, y en el caso de que se elija volver a intentar, llama a la función.

Entonces lo mejor sería hacer un llamar_denuevo para las que retornan y otra para las que no retornan?

**Comment by KnowYourselves** [comment]
En tal caso puedes hacer que llamar de nuevo **siempre retorne lo que su funcion entregada retorne**. Si esta no retorna nada, bueno, simplemente estarás pasando un `None` como resultado, pero eso no debería ser un problema, ya que en el contexto donde habras usado la función original no deberías estar haciendo nada con ese retorno de todas formas.

Ávisame si te sirve!

**Comment by dlmed** [comment]
Sí! ahí funcionó! También tuve que poner `return` al momento de llamar a `llamar_denuevo()`
