### ISSUE TITLE
Error al leer ayudantía 11

### ISSUE THREAD

**Issue by SarahEverke** [IIC2233/Syllabus#559]
Hola!

Ya tengo PyQT5 instalado, pero al correr el primer script de QT-Designer de la ayudantía 11 me sale el siguiente error
![captura de pantalla 2017-10-19 a la s 11 20 58](https://user-images.githubusercontent.com/30681133/31775114-112a0a0e-b4be-11e7-8a6c-affac39ec4f5.png)

¿Cómo puedo solucionarlo?
Gracias!!

**Comment by iqacevedo** [comment]
Hola,

Te falta tener el archivo qt-designer-label.ui en la misma carpeta en que estás corriendo el script.

Saludos !

**Comment by SarahEverke** [comment]
¿Cómo hago eso?

**Comment by andresfdezc** [comment]
¿Qué código estás corriendo?

**Comment by SarahEverke** [comment]
El primero de 2-QT-Designer.ipynb en la semana-11

**Comment by SarahEverke** [comment]
En verdad como se darán cuenta no cacho bien como usa QT designer :(
