### ISSUE TITLE
QThreads start() crash

### ISSUE THREAD

**Issue by kadawn0** [IIC2233/Syllabus#559]
Hola, tengo el siguiente problema:

Todas mis clases no GUI se heredan de QThread. La única que no se cae con su llamado a start() es la del juego, pero los threads de los personajes fallan en iniciar. Cuando se llama al método run() de cada personaje sí se obtiene el comportamiento esperado.

También he probado:

- Python Threads con un atributo que contiene una pyqtSignal y que se emite en el loop normal del thread. No funcionó debido a que el emit() no se hacía desde un QObject.

- QObject + QThreads: Usaba QObject.movetothread(QThread) luego de crear un thread e iniciarlo para poner el loop del QObject en un QThread. Funciona bien con cada thread usando QTimers para hacer un delay, pero al poner dos o más threads juntos la GUI se congelaba y finalmente mostraba el fondo sin personajes o un solo personaje. Tampoco corrían los loops de los threads.

- QThreadPool y QRunnable. Funcionaban pero en fila. Como uso loops infinitos para los personajes, nunca se pasaba al siguiente thread en la fila.

- Lo de ahora, heredar QThread. Funcionaba antes sin poder enviar pyqtSignals, ahora las envía pero no pasan hacia el thread de la clase juego y además al usar una pyqtSignal distinta para cada tipo de personaje los métodos start() hacen un crash de la ventana.

Ayuda por favor :( no puedo probar interacciones entre personajes.

**Comment by iqacevedo** [comment]
Hola,
Podrías explicarnos más que tipo de errores te indican cuando se cae el programa. Que hace la clase juego que tienes modelada cómoda QThread?.

Saludos !

**Comment by Dunkan1** [comment]
les diste dentro del while un pequenho delay.
time.sleep(0.05)
a mi me fallaba por eso

**Comment by hanavarrete** [comment]
Hola! Podrías subir tu código en caso de que la solución del time.sleep no funcione? Así podemos evaluar mejor o tener una idea más clara del error. (Estos casos son excepciones, por eso miraremos el código 👀)

**Comment by kadawn0** [comment]
Le di time.sleep(), QThread.sleep() y QTimers pero eso no parecía hacer una diferencia en cómo se procesaban los threads en cada una de las opciones.

La mayoría de las veces el programa se cae sin imprimir excepción con un traceback, pero cuando lo ha hecho han sido excepciones de PyQt relativas a la inicialización de clases al momento de heredar y a la imposibilidad de emitir una señal debido al tipo de objeto del que se origina.

También usé QMutex para controlar el acceso de los threads a ciertos trozos de código de la clase del juego, pero los threads se ordenaron de igual forma que antes para acceder a ellos.

Lo único que hay para interactuar con la GUI en el backend son señales, algunos pyqtSlots y tuplas con un QPixmap dentro en las señales. Subí el código a mi Github para que quien tenga acceso lo pueda ver.

**Comment by kadawn0** [comment]
La clase juego agrega objetos de cada personaje a sus diccionarios y luego les rellena atributos como posición absoluta inicial , IA e ID. 
Luego le da start a los threads y su método run sigue corriendo para manejar interacciones entre personajes como colisiones y manejo de rutas.

**Comment by rrhurtado** [comment]
Hola, sería ideal para poder ayudarte que mostraras textualmente el error que sale las veces que sí imprime la excepción.

Saludos

**Comment by kadawn0** [comment]
Errores comunes en la mayoría de las iteraciones de multithreading:
- Python: RuntimeError: super-class __init__() of %S was never called (http://bit.ly/2ry0LFS)

- TypeError: (InserteClase) cannot be converted to PyQt5.QtCore.QObject in this context (http://bit.ly/2qHtNj6)

El resto fueron solo TypeError's por pasar QEvent en vez de pyqtSignal y similares.
Olvidé mencionar que también usé QMetaObject.invokeMethod() y no funciona para alguno de los métodos que dije que había probado.

**Comment by iqacevedo** [comment]
Revise y me parece que puede ser porque cuando estás enviando cosas envías los Pixmap, vi también como esperabas recibir las cosas en el Fronted, la idea no es que crees un QLabel cada vez que te envíen algo si no que muevas y actualices el QLabel que pertenezca a lo que quieras representar.

Algunas veces usabas señales para conectar los funciones de la misma clase, esto no es necesario ya que las señales son principalmente para interactuar con otra clase enviándole los datos para que está otra clase efectúe algún método (el objetivo de las señales es que un Thread le envié instrucciones a otro sin modificarlo directamente para que no ocurran errores).

Ademas, replantéate si es necesario o no tener un Thread que les inidque a los otros Threads las cosas (Encontré medio raro que tablero fuera un Thread), en fin no puedo profundizar más en esto porque la idea es que tú veas cómo haces la tarea.

En cuanto a tus errores tiene que ver con problemas de herencia y con que PyQt en general necesita que trabajes con QObjetcts para que interactuar con sus clases directamente, entonces cuando trabajas con Threads comunes y corrientes debes tener mucho cuidado en cómo interactuar con las clases de PyQt para no tener estos errores (por eso es más sencillo trabajas con QThreads y/o QTimers).

Espero que te sirva,
Saludos !

**Comment by hanavarrete** [comment]
@kadawn0 pudiste solucionar tu problema con lo propuesto por @iqacevedo ?

**Comment by kadawn0** [comment]
Hola, perdón por la demora en contestar.
El problema continúa.
Estuve yendo paso a paso sobre lo que podría haber ido mal y actualicé mi github con el resultado.

- Vi que tal vez sería conveniente eliminar el QThread "operativo" y dejarlo todo más cerca del frontend. Aún cuando eliminé eso y los threads funcionan, poner dos o más threads causa que la GUI se pegue antes de que aparezcan los personajes y que los loops sigan corriendo. Le puse un time.sleep() de 1 segundo a cada loop, pero sigue pasando.

- Ya no uso señales para comunicar funciones de la misma clase, solo lo hice en algún momento temprano.

- Había memory leak por actualizar los QPixmaps (y accidentalmente los QLabels, gracias por notar eso), ahora no pasa y el movimiento es el mismo.

- Eliminé todo envío de cualquier QObject a través de señales.

**Comment by malopez16** [comment]
Tuve que hacer algo parecido para que funcione bien, aunque eliminando envíos a través de señales se me hizo mucho más difusa la relación entre front end y back end :/.
Has intentado con Qtimers? Antes tenía muchos threads y al pasar algunos a Qtimers se me ha ido solucionando (aunque con 3 ó 4 creepwaves activas igual se pega).

**Comment by kadawn0** [comment]
Acabo de cambiarlos todos a QTimers porque acaba de funcionar 🥇 
Muchas gracias!
