### ISSUE TITLE
Tiempo de preparación

### ISSUE THREAD

**Issue by pcseisdedos** [IIC2233/Syllabus#559]
En la sección 3.2.2 dice:

> Tiempo de preparación: distribuye exponencial con media de 6 minutos para platos de adultos y media 4 minutos para plato de niños.

Ante esto encontré dos posibles interpretaciones:
1.Como los restaurantes son autoservicio puedo asumir que todos los integrantes de un grupo comienzan a preparar su plato al mismo tiempo y se sientan a comer cuando el último en preparar termine de hacerlo, de modo que el tiempo de permanencia en el restaurante sería 10 mins + el maximo de los tiempos de preparación.
2. Existe una limitación de espacio en los restaurantes por lo que solo una persona puede preparar su plato por lo que el tiempo de permanencia sería la suma de los tiempos de preparación + 10 mins (esta opción es mucho menos atractiva ya que los restaurantes estarían casi siempre ocupados y además no tendría mucho sentido el establecer una capacidad para cada restaurante si en realidad solo 1 persona puede preparar su plato)

En este caso queda a mi criterio?

**Comment by jfbahamondes** [comment]
Si, queda a tu criterio cual escoger!

Saludos.

**Comment by jfbahamondes** [comment]
Ese `+10 mins` no es el tiempo que se demoran en comer, sino el `Tiempo máximo para comer`. Además recuerda que todo lo que quedó a tu criterio debe estar especificado en el README.
