### ISSUE TITLE
Atributos aleatorios

### ISSUE THREAD

**Issue by lorenzosilva** [IIC2233/syllabus#559]
Buenas! Estaba creando las clases pero no veo la necesidad de  crear los atributos aleatorios en la clase Delegaciones, si igual en la clase Esparta o en la clase Crotona  al implementarlos me darán nuevos números aleatorios.
Mi pregunta es , si es que no incluyo esos atributos en la clase Delegación, no tendré todo el puntaje de esa clase?

**Comment by retamalcito** [comment]
¡Hola @lorenzosilva!

En primer lugar, es **fundamental** que los atributos **Excelencia y respeto**, **Implementos deportivos** e **Implementos médicos** se encuentren en tu clase `Delegación`, por lo que se te descontará puntaje si no están presentes.

En segundo lugar, el enunciado dice que:

![image](https://user-images.githubusercontent.com/62028973/93074648-0c79ff00-f65b-11ea-975a-b41531e53b5a.png)

Esto significa que no debes asignarles ningún valor dentro de la clase madre, sino que el valor se asigna en la clase hija, dentro del rango especificado para cada una.

Espero haber aclarado tu duda, ¡éxito! 🏅
