### ISSUE TITLE
Variables descriptivas en Designer

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#559]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Puedo dejar el nombre de (por ejemplo una qLabel) un objeto que no editaré posteriormente en el código, como el por defecto de designer?

**Comment by valerianazal** [comment]
Hola @fernandosmither ! No hay problema con eso. Lo importante es que lo que sí modificas tenga un nombre **descriptivo** y **aclarativo**, ya que facilita la corrección.
Mucho éxito! 😁
