### ISSUE TITLE
Problema para hacer git pull

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2233/syllabus#56]
Hola, al intentar hacer git pull (y cualquier otro comando como commit, add, etc...) en el repositorio me aparece el siguiente mensaje en git:
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
Updating e68c586..01b74cc
como puedo solucionarlo?

**Comment by gatochico** [comment]
Hola! Intenta clonar el repositorio nuevamente. Si tienes progreso sin guardar, haz una copia en otra parte de tu computador, clona el repositorio de nuevo, y transfiere los archivos cambiados a esa copia recien clonada.

Avísanos como te va :eyes:

**Comment by mariovaldesa** [comment]
fatal: destination path 'syllabus' already exists and is not an empty directory.

me da ese mensaje y tampoco me deja eliminar el repositorio

**Comment by gatochico** [comment]
¿Qué sistema operativo usas, y como estas tratando de borrar la carpeta (i.e. click derecho y eliminar, o por terminal)?

**Comment by mariovaldesa** [comment]
windows. Estoy tratando con click derecho, deberia hacerlo por terminal? como se hace?

**Comment by mariovaldesa** [comment]
me funcionó! no se que cambio pero me funciono eliminarla y ya la clone, muchas gracias.

**Comment by gatochico** [comment]
super! :relieved:
