### ISSUE TITLE
Problemas al importar modulos en VSCode 

### ISSUE THREAD

**Issue by FelipeUC2020** [IIC2233/Syllabus#56]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Al tratar de utilizar módulos en vscode arroja un error diciendo que no se encuentra el modulo.
En stackoverflow vemos issues que reportan este problema en macos catalina para python 2.7; sin embargo la version de python instalada en este computador es la recomendada por el curso: 3.8.10 y el sistema operativo es macos big sur.

<img width="402" alt="Screen Shot 2021-08-31 at 19 43 22" src="https://user-images.githubusercontent.com/89170076/131590317-526d6726-6648-4516-b1a9-3c56e35f72cc.png">
<img width="466" alt="Screen Shot 2021-08-31 at 19 43 38" src="https://user-images.githubusercontent.com/89170076/131590335-357200b1-84ca-4bbb-af7f-3743d307efae.png">
<img width="522" alt="Screen Shot 2021-08-31 at 19 43 56" src="https://user-images.githubusercontent.com/89170076/131590345-b48bb8f1-ea99-4140-8f86-d57c6d85c6cd.png">
<img width="566" alt="Screen Shot 2021-08-31 at 19 44 44" src="https://user-images.githubusercontent.com/89170076/131590356-b1d9e2c1-82f3-4850-8852-d6333de12af6.png">

Por último, se corrió el setuptest.py y arroja un resultado positivo.

¿Hay alguna forma de arreglar este problema?

**Comment by Juampisaez** [comment]
Hola @FelipeUC2020!
el problema puede ser que estas corriendo tu programa en el interprete de python (puedes revisarlo mas detalladamente en #25). Una forma de solucionarlo, es agregando la extension "code runner" en vscode, para no tener problemas al ejecutar la flecha de vscode. Otra manera, es ejecutar directamente tu programa en consola, como por ejemplo, "python3 T0.py".

Avisame si se soluciona, quedo atento :)

**Comment by FelipeUC2020** [comment]
Muchas gracias, mantendré al tanto los resultados.
