### ISSUE TITLE
Balance de currencies

### ISSUE THREAD

**Issue by Pipelao** [IIC2233/Syllabus#56]
Hola Buenas,

Mi pregunta es con respecto al Usuario. En el enunciado de la tarea dice que tiene un nombre de usuario único, un nombre, un apellido, una fecha de nacimiento y un balance de sus distintas currencies, y es este el que no entiendo, ¿se refiere a la columna orders que está en el csv users o hay que crear una nueva? Si fuese el último caso no entiendo qué habría que hacer.

De ante mano, gracias.

**Comment by FernandoPieressa** [comment]
Hola! Creo que https://github.com/IIC2233/Syllabus/issues/41 resuleve tu duda.

Saludos!

**Comment by HenryBlairG** [comment]
Disculpen, pero leí el issue #41 y aún no me queda claro qué debe quedar guardado en el balance de las currencies. ¿Es como un historial de cómo ha afectado sus operaciones su total de cada divisa o es sólo cuánto tiene de cada una? Mi compresión lectora es casi nula.
aiuda 😭 😭 😭 !!

**Comment by Jiruiz2** [comment]
Aún no me queda muy claro, pero el balance es lo mismo que el saldo?

**Comment by sebacruzd** [comment]
Sí, es lo mismo.
