### ISSUE TITLE
Duda sobre añadir contacto ya existente

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#56]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holiiii 😄. Estuve revisando el enunciado en la parte 4.2.1 y sobre la funcionalidad de "Añadir contacto" lo que se pide es verificar si el usuario existe para agregarlo a la agenda, pero no se solicita el verificar si el contacto ya existe dentro de los contactos del usuario. ¿Se puede tener un contacto duplicado o se debe hacer la revisión para evitarlo?

En caso de que se evite, ¿se debería notificar al usuario de que no puede agregar un contacto ya existente? 

¡Gracias!

**Comment by matiasmasjuan** [comment]
Hola @Rerro-r !

Dado que no aparece explícitamente en el enunciado, **queda a tu criterio** cómo lo desees implementar siempre y cuando lo indiques en tu **README.md**. En lo personal, lo ideal sería que **no se pudiese** añadir un contacto que el usuario **ya** tenga, ya que sería redundante tener al menos dos contactos iguales. En ese caso, se debería notificar al usuario que **no puede** agregar un contacto ya existente.

Saludos! y mucho éxito con la tarea! :smile:
