### ISSUE TITLE
Duda del archivo readme respecto a la seccion de "Programacion orientada a objetos"

### ISSUE THREAD

**Issue by Sebastian-Assereto** [IIC2233/Syllabus#56]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Respecto a los menús, solo el menú de inicio debe ir como tal en una clase, o el menú de juego igualmente 
y por otro lado, respecto a lo de "funcionalidades" y "puntaje" a que hace referencia estos puntos, es decir mis "funciones" deben ir dentro de una clase? y cual es la razón de esto  

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by drcid98** [comment]
Hola, para esta tarea no es necesario usar clases, tal como se respondió en la issue #32.
Saludos!
