### ISSUE TITLE
Diagrama Avance

### ISSUE THREAD

**Issue by isihirmas** [IIC2233/syllabus#56]
Hola! Puedo entregar una foto del diagrama de clases hecho a mano, o tiene que ser  necesariamente en un programa?

**Comment by lily416** [comment]
Hola 😄

Los Diagrama de Clases los pueden hacer por el medio que más les acomode (mano, paint, power point, draw.io, lucidchart, etc. 🎨🖌), pero deben considerar que si el diagra no se entiende o distingue su contenido (i.e. la foto está borrosa, está muy desordando, etc.) no se les dará el puntaje correspondiente en la corrección de la tarea.

Saludos y éxito en la tarea 👋🏰
