### ISSUE TITLE
Odio al IDLE, Python x32 o x64

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#56]
Hola, me gustaría saber por qué odian 🗡 tanto al IDLE y desaconsejan tanto usarlo 🌚
Y si afecta en algo instalar python 3.6.X x32 o x64
Gracias 😄

**Comment by IchottMano** [comment]
Hola! En lo personal conozco a gente que ha hecho programación avanzada usando el IDLE de python, sin embargo es poco recomendable ya que IDEs como pycharm te pueden hacer la vida mucho mas fácil advirtiendote de posibles errores o arreglos que podria tener tu código, ademas de ayudar con los modulos y los colores que siempre simplifican la visualización del código.
Sobre la diferencia entre x32 y x64, depende de tu sistema operativo, si este es x32 e instalas python x64 no funcionará igual que el x32, al igual que en el cadi contrario.
Saludos!

**Comment by iqacevedo** [comment]
@jmwielandt particularmente recomiendo pycharm porque te permite debuggear, en simples palabras puedes detener la ejecución de tu programa en cualquier línea y ver el valor de las variables en ese momento, permitiéndote detectar errores de manera más efectiva.

Si usas atom o sublime son mucho más personalizables, por lo que puedes configurarlas fácilmente para usarlas con otros idiomas de programación, así que si te acostumbras a uno de estos los puedes usar en muchos cursos más.

Saludos !

**Comment by naquiroz** [comment]
@iqacevedo Sabes de algun source para aprender a usar bien el _debbuggin tool_ ?

**Comment by iqacevedo** [comment]
@naquiroz no es muy complicado, [acá](https://www.jetbrains.com/help/pycharm/part-1-debugging-python-code.html) tienes la documentación oficial de PyCharm que deja bastante claro como usar esta herramienta.

Si no te queda claro algo de ahi no dudes en preguntar.

Saludos !
