### ISSUE TITLE
Input int 

### ISSUE THREAD

**Issue by jahernandez2** [IIC2233/Syllabus#56]
Hola, en algunos casos solicito un input del tipo int (ya que las únicas opciones disponibles son números). Esto significa que al arrojar un valor alfabético o no númerico arroja un error. ¿Es necesario ponerse en ese caso o se puede asumir que el usuario escogerá algún número? Cabe mencionar que el programa, si se pone otro número, no se "cae", si no que notifica el error. 
Saludos y gracias de antemano.

**Comment by catalina-arcila** [comment]
Hola @jahernandez2, Al ingresas algo en la consola que no corresponde (un _int_ incorrecto o un valor alfanumérico) deberá ser notificado en la consola, es decir, tu deberás crear la condiciones en el código para determinar cuando es un valor correcto o no. De ser incorrecto deberías hacer un _print_ con el estilo `print("Valor incorrecto")`. No sé bien si respondí bien tu pregunta, quedo atenta!

**Comment by jahernandez2** [comment]
Si, muchas gracias!
