### ISSUE TITLE
Suposicion 

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#56]
Puedo suponer que todo ocurre en marzo? Porque así parece ser según los archivos entregados.

**Comment by eiherrera** [comment]
No, debes tener en cuenta que las bases de datos pueden abarcar cualquier mes.

**Comment by Nicolasvegam** [comment]
Se supone que debe ser todo posterior a marzo , que debería hacer el programa si se ingresa una fecha anterior a cierto incendio?

**Comment by rpalmaotero** [comment]
@Nicolasvegam no entendí muy bien la pregunta. Te recomiendo revisar #52 y #72.
