### ISSUE TITLE
Dos caracteres en un mismo lugar

### ISSUE THREAD

**Issue by SantiagoOsorio3** [IIC2233/Syllabus#56]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, tenia una pregunta sobre el menu de accion. En el numero 2, al tener que verificar si se cumple la regla 2 en un ejemplo de este estilo. [[ "2T", "-"], ["-", "-"]], en donde hay dos caracteres en un mismo espacio, estas reglas si se cumplerian o no ? Ya que dos cumple la segunda regla y no hay dos T juntos. 

Pero en un ejejmplo de este estilo [[ "2T", "T"], ["-", "-"]], ahí no cumpliria la regla 4 ? 

Cabe recalcar que este ejemplo NO seria valido para el numero 3 del menu de accion por nu cumplir la regla 3.

En resumen queria preguntar si es que al tener un tablero de ese estilo uno tiene que responder como lo propuse o de otra manera.

Saludos y gracias.

**Comment by Hernan4444** [comment]
Hola,

No existirán tableros con 2 elementos en la misma celda. Todos los tableros entregados serán con 1 elemento por celda y para cuando busquen la solución, se deben encargar de encontrar una que justamente tampoco tenga 2 elementos en la misma celda. La celda es bomba, blanca y tortuga, no híbrida ejejeje.

Saludos c:
