### ISSUE TITLE
Problema al moverme entre path

### ISSUE THREAD

**Issue by etoteiza** [IIC2233/syllabus#56]
Hola!!

Tengo un problema para moverme entre paths relativos. estoy usando os.path.isfile() para ver si el path existe. por ello estoy usando paths relativos. en mi caso uso ´os.path.join('T00', 'main.py')´ donde main.py es donde hago la tarea. sin embargo al utilizar os.path.file() sobre ese path relativo me sale que False. Sin embargo, para lo mismo, me sale True cuando uso el path relativo. No sé porque me funciona usando path relativo.

**Comment by KnowYourselves** [comment]
Una pequeña corrección, no es "que te muevas" entre paths relativos. Tu programa tiene un working directory que es desde donde se calculan todos los paths relativos, este por default es el directorio desde donde se ejecutó el programa.

Respecto a tu pregunta, ten en cuenta que el path que estás buscando es "T00/main.py", pero tu working directory es dentro de "T00", por lo cual si bien el archivo "main.py" existe, no existe una carpeta "T00" que dentro tenga un archivo "main.py".

Espero que se haya entendido!

**Comment by etoteiza** [comment]
Muchas gracias! ese era el problema. para aclarar, os.path.isfile() solo funciona sobre archivos pero no sobre carpetas. Como puedo averiguar si existe una carpeta dentro de mi working directory?

Gracias de antemano!

**Comment by KnowYourselves** [comment]
Usualmente este tipo de cosas se pueden encontrar fácilmente si se sabe como buscarlas. Mi recomendación es escribir lo que se busca de forma breve en inglés seguido del lenguaje. En tu caso por ejemplo, yo buscaría en google "dir exists python". 

Cuéntame como te va!

**Comment by etoteiza** [comment]
Gracias, lo encontré.
