### ISSUE TITLE
Error crear_predios

### ISSUE THREAD

**Issue by SebaAgusto** [IIC2233/Syllabus#56]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

buenas, mi duda es la siguiente: tengo el metodo "crear_predios" casi terminado pero me tira un error de impresion, y es que al momento de agregar las instancias predio (con su respectivo plano) a la lista "self.predios" de la clase "DCCultivos", cuando el "tipo" de plano es normal me imprime perfectamente lo que necesito.. sin embargo cuando el tipo es "riego", me retorna las listas vacias, siendo que el metodo "crear_plano" me funciona correctamente, pues pasa todos los testcases.  No se si sea un bug del Vs code, pues anteriormente todos los testcases me daban buenos, pero lo volvi a revisar y me daba uno malo. estoy atento :)

**Comment by catalinarozasf** [comment]
hola, yo tambien estoy teniendo problemas con crear_predios, he hecho el codigo de todas las formas posibles y no me esta reconociendo el archivo:C como se si se trata de un bug? estoy atenta, muchas gracias
