### ISSUE TITLE
Port usado cuando re-corro servidor

### ISSUE THREAD

**Issue by bmurtagh01** [IIC2233/syllabus#560]
Hola, comenzé la tarea viendo a la ayudantía del semestre pasado y sin alterar nada me di cuenta del siguiente error:

Cuando corro el servidor y abro los clienetes todo funciona perfecto, pero intenté correr el servidor nuevamente y me sale que el port seleccionado ya esta ocupado. Si cambio el port del servidor este funciona, pero si trato de correrlo con el port modificado o el antiguo nuevamente me sale que estan ocupados, es decir, una vez que corro el servidor este se comporta como si nunca deja de funcionar, por lo que no puedo hacer modificaciones sin antes tener que cambiar el port, y pregunte a amigos y soy el único con este error por lo que temo que es algo de mi PC.

(Debido a que el problema es de mi computador y involucra ports sospecho que pueden ser programas como Hamachi o Tunngle.)

Reiniciar el computador tampoco funcionó.

Muchas gracias.

**Comment by bmurtagh01** [comment]
Traceback (most recent call last):
  File "C:\...\syllabus-2018-2-master\Ayudantias\S13 - Networking\server.py", line 134, in <module>
    server = Servidor()
  File "C:\...\syllabus-2018-2-master\Ayudantias\S13 - Networking\server.py", line 18, in __init__
    self.socket_servidor.bind((self.host, self.port))
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

**Comment by jalliende** [comment]
Me paso lo mismo, lo que hago yo es correr los archivo en el terminal y el servido lo "mato" apretando control+c, y ahí se desocupa el port. Lo que pasa es que si no "matas" al servidor este queda con el port tomado.

**Comment by gatochico** [comment]
Hola! 
Efectivamente si no cierras tu programa de forma correcta ocurre lo que indica @jalliende , donde el puerto elegido para correr el server queda tomado. 

Como aparentemente estás usando windows, otra forma para cerrar los puertos que te hayan quedado abiertos podría ser la segunda respuesta de [esta](https://stackoverflow.com/questions/41836209/only-one-usage-of-each-socket-address-protocol-network-address-port-is-normall) pregunta de stackoverflow. En concreto:

1. Abre la CMD y ejecuta el comando "netstat -a"
2. En la columna "Dirección local", busca el número del puerto que quieres liberar. Una vez encontrado, busca el "PID" asociado a esa fila.
3. Abre el administrador de tareas y busca el proceso con el PID correspondiente al puerto que encontraste en el paso anterior.
4. Click derecho y finalizar tarea.

Saludos!
