### ISSUE TITLE
Baculo u objeto magico

### ISSUE THREAD

**Issue by JoseValencia125** [IIC2233/Syllabus#560]
del enunciado

>  Potencia la habilidad de tu campeon. El precio base es de 7 puntos y potencia
en 2 unidades la habilidad del campeon.

Como cada habilidad es distinta ¿puedo hacer que reduzca el colddown de la habilidad en vez de cambiar la potencia?

**Comment by hanavarrete** [comment]
Si! explicalo en el readme de todas formas. Saludos!
