### ISSUE TITLE
dudas sobre sanar

### ISSUE THREAD

**Issue by enriquerussi** [IIC2233/syllabus#560]
al momento de sanar si la probabilidad es mayor que el numero random el deportista se sana o no?

**Comment by retamalcito** [comment]
¡Hola @enriquerussi!

Supongo que te refieres al caso en que tienes un `float` que representa una probabilidad y realizas un `random.uniform()` para obtener un `float` al que llamas "número random". En dicho caso, sí, el caso favorable se dará cuando tu número aleatorio sea menor que la probabilidad de que ocurra. Por ejemplo, si tu probablidad es `0.7`, si `random.uniform()` te entrega `0.52`, entonces el deportista sí se sanará.

¡Éxito! 🏅
