### ISSUE TITLE
Issue desligada del ramo (sean amables)

### ISSUE THREAD

**Issue by jadiaz6** [IIC2233/Syllabus#560]
Tengo un problema, ya probé todas las soluciones de internet, incluso publiqué en un 2 foros y aún no he encontrado una solución, espero que alguno de ustedes me pueda ayudar.

Hace un par de días VTR cambió mi modem por un Connect-Box (que es como un modem, pero se llama así). Lo configuré y todo bien. 

El problema es que ningún notebook se puede conectar, aparece el signo de "conectado sin internet" y el solucionador de problemas dice que no hay conexión con el DNS principal.

Todos los otros dispositivos (televisores, celulares, ipads, etc.) se conectan sin problemas, esto ocurre solo con los notebook. Y ocurre con TODOS, tengo 3 en mi casa, porl o que sería muy raro que sea problema de los notebook.

Ya probé abriendo los puertos DNS (dirección ip abierta). También intente con Flush DNS. Obviamente lo primero que hice fue reiniciar el modem, así que eso no es solución. Si conecto mi notebook por ethernet la conexión funciona, el problema es con las conexiones Wi-Fi.

Por favor es muy importante que lo arregle, me cuesta mucho más trabajar en la tarea, ya que tengo que ir buscando información en mi celular, lo que hace todo más lento e incómodo.

¿Alguien sabe como solucionarlo?

Se agradece cualquier respuesta.

**Comment by sebacruzd** [comment]
Primero que nada, sino lo has hecho, llama a vtr, podrían solucionar tu problema.

Cuál es el nombre específico del modelo de ese Connect-Box? Creo que tengo lo mismo y es una caja blanca. ¿[es esta](http://www.libertyglobal.com/Annual-Report-2015/story/_img/story-12a-lo.jpg)?

Se me ocurre es el tipo de señal que está mandando. Tal vez está emitiendo solo 5G y no 2.4G.

Para poder hacer lo siguiente, **conéctate a internet mediante cable** desde algún computador.

Busca en google cómo poder editar eso, ya que varía dependiendo del equipo que tengas instalado. Tengo vtr y la dirección que debo visitar en un explorador es `192.168.0.1`, pero podría ser otra. No soy un experto en el tema, por lo que no te puedo explicar detalladamente qué es cada cosa.
Para entrar a modificar la configuración de la red, en ese sitio te pedirá una clave.

![imagen](https://user-images.githubusercontent.com/14894992/31795522-75ab76f0-b4fc-11e7-9a12-5c994b7cf90a.png)


Aparte, cada modelo tiene una clave distinta, a veces hay claves del día o en otro caso, como es el mío, viene en la parte de abajo del módem, en un sticker. En [esta foto](https://4.bp.blogspot.com/-Nq3X_GkOAyg/V9DLMKqo4PI/AAAAAAAAFJk/8wgyqC6bbC8fM0vCe0LA_6uALhEslwYHwCLcB/s1600/PASSWORD.JPG), es el número de más abajo.

Ahí deberás explorar las opciones y ver qué está pasando y si es así con las señales como mencioné.

**Comment by jadiaz6** [comment]
Me funcionó! Muchas gracias

**Comment by sebacruzd** [comment]
🎉

**Comment by jadiaz6** [comment]
Me funcionó! Muchas gracias
