### ISSUE TITLE
Sobre movimiento del personaje y teclado

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#560]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

**Comment by fernandosmither** [comment]
En ánimos a la misma duda, veo que esto podría generar problemas con determinar la velocidad del enemigo. ¿Cómo podría resolver esto? Quizás acordar un repeat rate por defecto, porque lo otro que se me ocurre sería cambiar el repeat rate de la persona que ejecuta el código, pero sería cambiar algo del funcionamiento interno del computador del ayudante que me corrija, y creo que es algo invasivo 😅

**Comment by clementevalladares** [comment]
Hola @fernandosmither, no te preocupes por eso. Lo importante es que cuando tu personaje se mueva, lo haga de VELOCIDAD_PERSONAJE en VELOCIDAD_PERSONAJE pixeles cada vez. Es decir, si la velocidad del personaje es 2, debe moverse de 2 en 2, No vamos a intentar "hackear" el juego cambiándolo, pero dentro de esta lógica no debería tener mucha incidencia en esto.
Para el enemigo tienes que considerar que se mueva a la misma velocidad que el personaje.

**Comment by fernandosmither** [comment]
> Hola @fernandosmither, no te preocupes por eso. Lo importante es que cuando tu personaje se mueva, lo haga de VELOCIDAD_PERSONAJE en VELOCIDAD_PERSONAJE pixeles cada vez. Es decir, si la velocidad del personaje es 2, debe moverse de 2 en 2, No vamos a intentar "hackear" el juego cambiándolo, pero dentro de esta lógica no debería tener mucha incidencia en esto.
> Para el enemigo tienes que considerar que se mueva a la misma velocidad que el personaje.

Esque me refiero a que cuando mantenemos una tecla pulsada, hace poco descubrí que realmente no lo toma como tal, sino que en realidad es la misma tecla repitiéndose muchas veces rápidamente, entonces ese valor puede variar de computador a computador, haciendo que en uno el pje se mueva más rápido o lento.

¿Existe algún evento que realmente sea "mantener" la tecla pulsda?

**Comment by StroveLight** [comment]
No existe un evento que haga eso, pero puedes usar el keyPressEvent en conjunto con el keyReleaseEvent para poder detectar si la tecla se mantiene pulsada

**Comment by clementevalladares** [comment]
@fernandosmither Una forma que tienes de identificar que una tecla se mantiene presionada es utilizando `keyPressEvent` y `keyReleaseEvent` en conjunto. De esta manera, puedes hacer que tu backend considere que la tecla esta presionada hasta que el `keyReleaseEvent` envíe una señal.

**Comment by clementevalladares** [comment]
@fernandosmither además, en tu método `keyPressEvent`, puedes utilizar el método `.isAutoRepeat()` dentro del evento que activa esta señal para identificar si el evento se volvió a activar por el repeat rate del teclado. Solo en caso de que te sirva para algo.
```
def keyPressEvent(self, event):
    if event.isAutoRepeat():
        pass
```
