### ISSUE TITLE
Integrante que no cumple con estatura mínima

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#560]
Una consulta... ¿Qué pasa si uno de los integrantes de un grupo no cumple con la estatura mínima para subirse a una juego? Bajo mi modelación, imagino que el adulto responsable no podría dejar al niño en cuestión solo, pero tampoco podría dejar a los demás niños subirse solos a la atracción, por lo que el adulto decide no subir a nadie a esa atracción y volver a tomar otra decisión.

El problema con el que me encuentro es que en el enunciado (__3.1.1__ > __Adultos__) dice:
> ... el adulto elige cualquiera de las atracciones que aún no ha visitado ... 

Mi duda es si considero a la atracción a la que nunca podrán subir (por la estatura de uno o más integrantes) como una atracción visitada o no. ¿Puedo agregar dicha atracción a una lista de atracciones visitadas a pesar de que no se suban? ¿Mi modelación contradice algún punto de la tarea?

**Comment by llloyola** [comment]
Acabo de darme cuenta de algo... Si el integrante más bajo de un grupo, no puede subirse a ningún juego, el grupo tampoco podría subirse a ningún juego. ¿Está mal modelarlo de esta forma?

**Comment by jfbahamondes** [comment]
En la sección 3.2.1 dice:

> Altura mínima permitida: sólo se pueden poner en su ﬁla de espera los grupos de clientes donde todos sus integrantes superen esa altura.

Así que no podrían ingresar a la fila y por lo tanto no podrían subirse.  Al ir a la atracción y finalmente darse cuenta que no la subirán queda a criterio si cuenta como que la visitaron o no.

Si no se cuenta, ocurriría lo que mencionas, pero es un caso borde. Y si lo quieres modelar mejor aún (asumiendo que se cuenta como visita al ir y no poder subirse), una vez visitado todas las atracciones no tendría por qué volver  a una atracción que ya visitó y a la cual no se pudo subir ( en los casos de las atracciones en los que un miembro es más bajo que la estatura mínima).

Respecto a tu segundo punto también es un caso borde y queda a criterio. Podrían irse ya que no tienen nada que hacer en el parque. 

Recuerda que cualquier cosa que hagas a criterio debes especificarlo en el README,
Saludos.

**Comment by llloyola** [comment]
Thaaaanks 🥑

**Comment by jfbahamondes** [comment]
@llloyola  ese caso quedó a criterio. Ya que es un caso muy borde.  De todas maneras creo que está bien modelado así, me imagino que en la vida real si alguien no puede subirse a nada simplemente el grupo se tendría que ir después de recorrer el parque (y darse cuenta que no se pueden subir a nada).
