### ISSUE TITLE
Agregar atributos a clases que no son especificados en el enunciado

### ISSUE THREAD

**Issue by CatalinaGoldsack** [IIC2233/syllabus#560]
Hola! Es legal agregar atributos a alguna clase, con el objetivo de hacer el programa más eficiente, a pesar de que no salga explícito en el enunciado? :smile:

**Comment by Dnpoblete** [comment]
Hola @CatalinaGoldsack, esta duda ya fue resuelta en la issue #261, para que la revises y en caso de dudas preguntes en esa issue.

Éxito con la tarea! :smile:

**Comment by CatalinaGoldsack** [comment]
Oh!! qué pava!! no lo ví, muchas gracias! :)

**Comment by Dnpoblete** [comment]
De nada! ☺️
