### ISSUE TITLE
Duda comentario avance Tarea 2

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#561]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! El/la ayudante que revisó mi avance me señaló que **tuviese cuidado** cómo estaba definiendo las variables en _main.py_, porque podría sufrir un descuento si las defino como variable global.

Revisé este comentario y no tengo claro a qué variable en particular se estaba refiriendo. ¿Me parece que no tengo ninguna variable definida globalmente?
Actualicé mi repo por si pueden darme detalles específicos sobre la variable que estoy definiendo mal, lo agradecería mucho :)

**Comment by Juampisaez** [comment]
Hola @jamigone 
Revisando tu avance, y consultandolo con los demas ayudantes, las variables que definiste en el main.py no deberian ser consideradas como globales (el corrector se pudo traspapelar probablemente). De igual manera, recuerda que las variables globales son aquellas que pueden ser accesadas en todo el entorno global, es decir que al final el valor de esta puede ser cambiado en cualquier parte del programa (no hay restriccion). Puedes averiguar por tu cuenta si lo deseas, pero eso es basicamente!!

Animo con la tarea! vas super!

**Comment by jamigone** [comment]
Gracias :D
