### ISSUE TITLE
Shortcuts y dudas frontend-backend.

### ISSUE THREAD

**Issue by rfenzo** [IIC2233/Syllabus#561]
Al tratar de hacer el cheat code LIF, se ejecuta automaticamente el shortcut para salir del juego (I), cambiarmos los shortcuts mejor?.

Lo otro, el shortcut para ir a la tienda tiene que hacer que el heroe se acerque al rango de compra de la tienda y luego abrirla, o tan solo abrirla a pesar de que el heroe se encuentre fuera de rango?.

Finalmente, queria confirmar que estoy haciendo las cosas bien. Tengo Qthreads en el backend  (probé ocupando threads normales y me tiraba error), queria saber si no hay problema con eso. Adicionalmente, mi frontend contiene a un objeto Game del backend, y a si vez Game contiene al QWidget del juego del frontend, por lo que se genera una referencia circular (en el backend solo importé pyqtSignal y QThread, nada más.). 

Gracias

**Comment by sebacruzd** [comment]
Hola,

Tu programa debe ser capaz de idenfificar si se está poniendo un cheat code o si se quiere salir.

El campeón debe estar cerca de la tienda para que el shortcut funcione.

Con manejo correcto de señales no debería haber referencia circular. De hecho, si tuvieras la referencia circular las señales están de sobra.

Saludos!

**Comment by rfenzo** [comment]
okas, gracias!
