### ISSUE TITLE
Local mas pizzas vendidas por tipo de pizza

### ISSUE THREAD

**Issue by jtvvtj** [IIC2233/Syllabus#561]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola buenas, no entiendo que es lo que hay que retornar en la funcion local_mas_pizzas_vendidas_por_tipo_de_pizza(). Son los locales que venden diversos tipos de pizzas, pero el tipo de pizza que mas venden es el str que nos otorgan? O es el local que vende mas pizzas de ese tipo en comparacion a todos los demas locales?
Gracias :)

**Comment by kbetelgeuse** [comment]
Hola @jtvvtj !
Es lo segundo que mencionas: se busca encontrar el local (o locales) que ha vendido más pizzas del tipo de pizza correspondiente al del `str` que se entrega (o sea, el que se otorga en el parámetro `tipo_de_pizza`).
Espero haber resuelto tu duda 🙂.
Saludos!
