### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by n4chin** [IIC2233/syllabus#561]
Hola! Cuando subí el diagrama sin querer subí deportistas.csv y delegaciones.csv a mi repositorio, si bien ya los puse en el gitignore, pero no sé como sacarlo de mi repositorio :c.

**Comment by itmunoz** [comment]
Hola! Para remover un archivo de tu repositorio de Github sin borrarlo del repositorio local (el de tu computador) haces lo siguiente:
`git rm --cached delegaciones.csv`
`git commit -m "Quitar delegaciones"`
`git push`
Y haces lo mismo con deportistas.csv.
