### ISSUE TITLE
Paso de dia y habilidad

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#561]
Hola, revise las issues y no encontre una respuesta:
Cuando pasa un dia, no dicen nada sobre las habilidades de las dccriaturas, mi pregunta es entonces, las habilidades surgen luego del resumen del paso de dia que parece en el enunciado? o antes?. Tambien si al surgir las habilidades hay que mostrar un mensaje

**Comment by JosefaPaz** [comment]
Hola @Juampisaez !

Respecto a las habilidades de las DCCriaturas al pasar al día siguiente, al no estar explicitado en el enunciado si van antes o después del resumen del día, queda a tu criterio. Pero sí deben ir antes de la fiscalización del DCC.
Además, sí debes mostrar un mensaje cuando una habilidad ocurre, ya que así podremos saber si se está ejecutando correctamente o no en el programa.

¡Éxito!

**Comment by Juampisaez** [comment]
Gracias!
