### ISSUE TITLE
Conexión ejemplo Networking

### ISSUE THREAD

**Issue by JosefaPaz** [IIC2233/syllabus#561]
Hola! Estaba probando el último ejemplo de Networking (https://github.com/IIC2233/contenidos/blob/master/semana-12-13/3-ejemplos.ipynb) y no logro hacer que cliente y servidor se conecten.

Me pasa que al ejecutar primero servidor y luego cliente, el servidor se queda esperando un cliente, y el cliente nunca detecta el servidor.

Copié y pegué textualmente el código y lo corrí en 2 cmd diferentes pero no me funciona.

gracias!

**Comment by Drpinto1** [comment]
Hola!

Disculpa la demora en la respuesta :(

¿El error aún persiste o lograste solucionarlo?
Si es que aún no lo logras, podrías ¿comentar el output que te entregan las consolas?

Saludos!

**Comment by JosefaPaz** [comment]
Hola dante!

Lo pude solucionar preguntando por discord, el problema era que el puerto no me lo detectaba Windows, así que había que cambiarlo jajaja

Gracias!
