### ISSUE TITLE
manejo bytes/png

### ISSUE THREAD

**Issue by RositaMunoz** [IIC2233/syllabus#561]
hola! 
estoy intentando el manejo de bytes, pero me pasa que me funciona solo para algunas imágenes en formato .png, si saco imágenes de google en formato .png no me funciona el manejo de bytes, hasta ahora me ha funcionado con imágenes sacadas de www.flaticon.com. Según la matriz RGB que me arroja el modulo pixel_collector.py todas las imágenes que he probado son de 4 canales. Entonces no sé por qué me funciona para unas imágenes y para otras no.

**Comment by RositaMunoz** [comment]
ayuda porfas :((

**Comment by iqacevedo** [comment]
Hola ! 
Podrías indicarnos con cuáles fotos has probado. Subir el link de alguna foto que si te funciono y otra que no.
Quedo atento!

**Comment by RositaMunoz** [comment]
por ejemplo, al descargar esta imagen en formato .png [https://www.flaticon.com/free-icon/beach_119596#term=beach&page=1&position=7](url) me funciona perfecto el filtro y que el server guarde la foto en una carpeta propia desde un path. Pero imágenes como esta [https://clipart.info/squirtle-pokemon-png-by-megbeth-8373](url) (si pongo en google imagen png) al aplicar el filtro o intentar escribir la misma foto, pero en la carpeta del servidor, el resultado es como interferencia de televisión, dejo imagenes de como me queda cada una
![imagen_filtro_dibujo](https://user-images.githubusercontent.com/48262755/59728577-ac529e00-9208-11e9-8cb2-1fdaf118356e.png)
![imagen_filtro_dibujo_malulo](https://user-images.githubusercontent.com/48262755/59728603-c7251280-9208-11e9-991c-a811245c4ded.png)

**Comment by RositaMunoz** [comment]
creo que la otra imagen no se ve porque esta como 'dañada'

**Comment by iqacevedo** [comment]
Hola !

Probé transformar ambas imágenes a PNG y luego les aplique el filtro, logré tener a ambas bien. Logre recrear tu error :tada:, cuando logre tener el mismo error era cuando ocurría una de estas situaciones:
* En el chunk IHDR, tenia color_type = 2, pero estaba intentado guardar 4 canales. Revisa que no estés intentando guardar 4 canales con esta configuración el IHDR. 
* Cuando no se insertaba el byte con valor 0 al inicio de cada fila en el IDAT.

**Comment by RositaMunoz** [comment]
gracias por responder!! según yo agrego el byte con valor 0 al inicio de cada fila en el IDAT, pero tengo una duda sobre los pixeles. Cada pixel debe estar en un byte, o cada canal de un pixel debe estar en un byte? porque no sabría como setear en un byte un bytearray. No se si se entiende la pregunta

**Comment by lily416** [comment]
@RositaMunoz Cada canal de un píxel debe estar en un byte. 😉 

Saludos y éxito con la tarea 👋💪

**Comment by RositaMunoz** [comment]
Para los que le sucede esto, mi problema era que puse al revés los tamaños de la imagen, por eso me salía error en imagenes no cuadradas :)
