### ISSUE TITLE
Duda sobre medidas de desempeño de los escenarios

### ISSUE THREAD

**Issue by MrEarle** [IIC2233/Syllabus#562]
Para muchos escenarios, la medida de desempeño consiste en mas de un valor.
Por ejemplo:

> Cantidad mínima, máxima y promedio por productos vendidos durante un día.

> Cantidad promedio de personas que almorzó entre las 12:00-12:59, 13:00-13:59 y 14:00-15:00

En estos casos, para realizar la suma y comparación de escenarios, como lo hacemos?

**Comment by iqacevedo** [comment]
Hola,

En esos casos simplemente despliégalas como alternativas separadas. En el primer caso que pones, que estén las opciones separadas de la cantidad mínima, máxima y promedio por productos vendidos durante el día. 

Saludos !

**Comment by BeaGaete** [comment]
Tengo la misma pregunta, pero para el caso de miembrosUC intoxicados por vendedor, tenemos que desplegar los 30 vendedores?????????

**Comment by iqacevedo** [comment]
Hola,

Despliégala como una sola opción no más y considera la cantidad total del intoxicados (como medida de desempeño considera el total de intoxicados).

Saludos !

**Comment by BeaGaete** [comment]
Oh!! Muchas gracias!!!
