### ISSUE TITLE
Constantes

### ISSUE THREAD

**Issue by gbordoni** [IIC2233/Syllabus#562]
Hola!
El Params.csv, en donde guardaría las constantes para iniciar el juego, lo tenemos que hacer "a mano" y el programa simplemente lo lee y lo carga? O el programa tambien tiene que crear dicho archivo? A mi me hace mas sentido la primera opción, pero no me queda claro leyendo el enunciado.

Saludos

**Comment by Dunkan1** [comment]
puede ser tambien un json cierto

**Comment by Hernan4444** [comment]
Enunciado: 

> El formato de estos archivos puede ser un csv, pickle, txt o cualquier otro formato que no requiera el uso de una librería que no ha sido permitido

Saludos :+1:

**Comment by Dunkan1** [comment]
excelente gracias
