### ISSUE TITLE
Animación de sprites

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#562]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

**Comment by MatiasDuhalde** [comment]
Hola @fernandosmither !

De este item en específico, esperamos que el movimiento sea fluído, y la animación ocurra durante el desplazamiento. Por lo tanto, si al dejar de presionar la tecla el personaje continúa moviéndose por un tiempo muy reducido, no afectaría realmente la fluídez. En cambio, si este punto se implementa de tal forma que la animación nunca para de alternarse (aún cuando el personaje está detenido), probablemente se descontará puntaje.

Para asegurarte que estés tomando un enfoque correcto en esta parte, te recomiendo revisar los métodos de implementación que se discuten en la issue #531

En resumen, los puntos principales sobre los que debes preocuparte al hacer este item son los siguientes: 
- Hacer que el movimiento (tanto el desplazamiento del personaje, como la animación) sean fluídos
- Implementar el movimiento y la animación con señales (**muy importante**)

Ojalá esto te haya aclarado un poco las cosas! :sparkles:
