### ISSUE TITLE
Duda Notas Actividades

### ISSUE THREAD

**Issue by Gianluc139** [IIC2233/syllabus#562]
Hola, con un amigo aun no nos queda claro que sucede con las notas de las actividades sumativas y la recuperativa.
Tengo entendido que:
La 4ta nota de las actividades es el maximo entre el promedio de las primeras 3, y la recuperativa.
Luego se calcula el promedio con las mejores 3.
Esta bien asi?
Saludos!

**Comment by Drpinto1** [comment]
¡Hola!

En el [README de Syllabus](https://github.com/IIC2233/syllabus/blob/master/README.md) se encuentra una explicación más formal del cálculo de la nota de actividades, además de un código python donde que calcula tu promedio a partir de las notas y décimas de cada actividad (también hay un código para la nota de tareas), por lo que si quieres saber tu nota de actividades o probar con distintos valores dependiendo de las instancias de evaluación que quedan puedes hacerlo ahí :D 

Respondiendo a tu pregunta, el cálculo funciona como dices, originalmente teníamos 4 actividades sumativas, pero una de ellas fue cancelada, por lo que la nota que antes correspondía a esta actividad fue reemplazada por la mejor entre dos opciones:
* El promedio de las 3 actividades sumativas (Las dos que ya tuvimos y la actividad remota que está en proceso)
* La actividad recuperativa que se hará en periodo de exámenes (los detalles de esta actividad se avisarán pronto)

Luego, la nota de actividades se calculará promediando las 3 mejores notas entre estas 4.

Espero que esta explicación haya aclarado un poco el sistema, pero de no ser el caso, no dudes en contestar esta issue con las dudas que te surjan de este tema.

¡Saludos :full_moon_with_face:!

**Comment by Gianluc139** [comment]
Perfecto! Graciaas

**Comment by Felopo** [comment]
Entonces, si reemplazo mis 3 notas de actividades sumativas en el código que está en syllabus, y me pongo un 1 en la recuperativa. El resultado de eso sería mi promedio de actividades? O me falta hacer algo?

**Comment by Drpinto1** [comment]
@Felopo Efectivamente, si decides no dar la Actividad recuperativa, es equivalente a tener un 1 en esta actividad (que se borrará al promediar), por lo que si incluyes tus décimas correspondientes a las actividades formativas, tendrás tu promedio de actividades.

**PS:** Había un pequeño error en el cálculo de la nota de actividades (cortaba los decimales), pero ya fue actualizado.

**Comment by Felopo** [comment]
Oka, gracias!!
