### ISSUE TITLE
Printear sucesos al pasar dia

### ISSUE THREAD

**Issue by knight-who-say-ni** [IIC2233/syllabus#562]
Hola!! Tenía la duda de que al pasar al al siguiente dia, al dar los sucesos que pasaron, en el ejemplo del enunciado se especifican las razones por las que se le aplicaron multas al magizoologo. 
Es necesario hacer esto en mi programa?? El enunciado dice que "se debe mostrar en
pantalla el pago del DCC, y luego las multas recibidas", pero nada de las razones de estas ultimas.

Lo mismo pasa con las criaturas que perdieron salud por enfermedad o por hambre, en el enunciado no dice que hay que mencionarlas pero en el ejemplo estas si se mencionan.

Muchas gracias!!

**Comment by JosefaPaz** [comment]
Hola @knight-who-say-ni !

Si bien no sale explícitamente en el enunciado, es importante que sí se muestren las razones de las multas y lo mismo para las DCCriaturas, ya que de esta forma podemos saber si se están implementando de manera correcta o no.

Éxito 😸
