### ISSUE TITLE
Referencias circulares

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#562]
No me queda del todo caso si este ejemplo seria una referencia circulares:
tener una función por ejemplo de un Cliente a la que se le pasa como argumento una clase Restaurante, y dentro de la función del cliente se ocupan valores de la clase, como podrían ser los precios. Para mi esto no seria una referencia circular ya que el cliente nunca guarda en uno de sus atributos a el restaurante, sino que solo hace consultas para una función en especifico.
Para solucionar esto podría pasarle una lista a la función del Cliente que contenga la solo la información necesaria del Restaurante. pero lo encuentro poco practico.
Muchas Gracias

**Comment by rihanuch** [comment]
¡Hola @ljrodriguez1 !

La issue #540 habla de eso, pregunta ahí

¡Saludos! 🍀
