### ISSUE TITLE
Recomendaciones para expresiones más cortas

### ISSUE THREAD

**Issue by sabquit** [IIC2233/syllabus#562]
Hola! Es una mala práctica usar variables auxiliares para renombrar parámetros en contextos de función o métodos?

```
def __init__(self):
    inicio = p.NOMBRE_DESCRIPTIVO_1
    final = p.NOMBRE_DESCRIPTIVO_2
    self.atributo_clase = final - inicio
```

Pregunto esto porque en ocaciones al usar los parámetros con nombres descriptivos, las expresiones resultantes superan el largo de linea recomendado en PEP8 (incluyendo indentación).

Recomiendan alguna otra forma de escribirlos?

**Comment by itmunoz** [comment]
Hola! Yo diría que hacer eso no es una mala práctica, así que no deberías tener ningún problema haciéndolo 👌
