### ISSUE TITLE
Error en test carga datos pero bien en correctitud

### ISSUE THREAD

**Issue by Isipirisi23** [IIC2233/Syllabus#562]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Viendo el test 10 (ganancias_producidas_en_los_pedidos). Haciendo el test de correctitud tengo todos ok, pero al ejecutar el test de carga de datos en todos me sale Fail y el mensaje de error es de 2 tipo:
![image](https://github.com/user-attachments/assets/39c32aae-8d8c-4837-992a-6d6180ddb694)
![image](https://github.com/user-attachments/assets/1297596c-16b8-4351-b7b2-ed102b009c18)

Entonces no entiendo cómo si mi correctitud está bien, en la carga de datos obtengo estos errores, según yo no tendría sentido :/ Quedo atenta! Gracias!

**Comment by Gcamposbriceno** [comment]
Hola!
Lo que te dice el primer error es que el resultado que retorna tu función está equivocado en los pedidos 7, 15, 23, 48 y 53 (las líneas que dicen "First has 1, Second has 0" son lo que tú retornas, y las que dicen "First has 0, Second has 1" son lo que pide el test). Los otros errores son más de lo mismo, pero como son más datos y sería muy largo imprimir todas las diferencias, no lo hacen.

Lo que te recomiendo es analizar los pedidos que te fallan en el primer caso y ver qué puedes hacer para que tu código pase ese test en específico. Si te fijas, los resultados que das no son tan distintos de lo que se pide, así que puede ser que los errores sean muy pequeños, o en casos muy específicos, y por eso no los obtuvo el test de correctitud.
Éxito!
