### ISSUE TITLE
.show de frontend

### ISSUE THREAD

**Issue by mistico0121** [IIC2233/syllabus#562]
Hola

Tenía la duda si ejecutar la función self.frontend.show() en el cliente es considerado programación circular tambien, y si debería hacerlo con señales como el resto de la comunicacion cliente-frontend

Saludos

**Comment by KnowYourselves** [comment]
Hola @mistico0121!

Los show y hide, por requerimiento de PyQt, deben ser ejecutados en el MainThread, es decir, el archivo que ejecutas inicialmente. En la issue #538  puedes encontrar una mejor explicación. 

Éxito!
