### ISSUE TITLE
error al intentar pushear

### ISSUE THREAD

**Issue by prochotito-rises** [IIC2233/syllabus#563]
Hola! Me apareció el siguiente error al intentar hacer push:
![image](https://user-images.githubusercontent.com/39094323/69834658-80593100-121a-11ea-85bd-eee849747857.png)
Me podrían ayudar a solucionarlo?
Saludos

**Comment by fdoflorenzano** [comment]
Estimado, estás intentando pushear a syllabus. Debías pushear a tu repositorio.
