### ISSUE TITLE
largo maximo de un archivo

### ISSUE THREAD

**Issue by kipasten** [IIC2233/syllabus#563]
Hola, se que queda poco tiempo pero, tengo archivos que están sobrepasando las 400 lineas de código y me falta aun definir ciertos comportamientos, la duda es ¿Habrá descuento por el largo de un archivo? para ver si lo separo mas aún, o sigo trabajando como está todo

**Comment by matiasmasjuan** [comment]
Hola @kipasten !

Puedes consultar la ***Distribución de Puntajes T01*** disponible en **canvas** para informarte de los **descuentos** de esta tarea.

Saludos! 😄
