### ISSUE TITLE
posiciones

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#563]
es necesario que las posiciones sean iguales a las de la imagen
![duda](https://cloud.githubusercontent.com/assets/26102365/26750210/156db448-47eb-11e7-88dc-150474868823.PNG)

**Comment by hanavarrete** [comment]
La idea es que mantengas el mismo formato, pero puedes tener otra escala ( distancias mas grandes o pequeñas). De cualquier modo, explica en el readme tus dimensiones. Saludos!

**Comment by Dunkan1** [comment]
gracias
