### ISSUE TITLE
Cliente se queda fuera

### ISSUE THREAD

**Issue by beayancan** [IIC2233/Syllabus#563]
Todos los clientes tienen un día y hora de llegada, ej: "Lunes 11:00", si ocurre que en la simulación ya vamos en un momento más adelante ej: "Lunes 12:00" ¿el cliente nunca entrará al parque?

**Comment by leolivares** [comment]
Hola! @beayancan 
Se supone que si la simulación va en un tiempo adelante, ya el evento que mencionas debió haber ocurrido.
Saludos.

**Comment by beayancan** [comment]
Entonces ¿efectivamente el cliente nunca entraría al parque?

**Comment by leolivares** [comment]
@beayancan 
No, el cliente **debe** estar dentro del parque.
Si la llegada del cliente era a las 11:00, y ya son las 12:00, el evento de su llegada ya debió haber ocurrido.
