### ISSUE TITLE
Duda sobre relacion entre QRadioButton y QComboBox

### ISSUE THREAD

**Issue by raimundosilvac** [IIC2233/syllabus#563]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Tengo definido un KeyPressEvent que cuando un RadioButton esté seleccionado, al apretar teclas (específicamente WASD) me hace un print de algo. Cuando ya tengo un RadioButton seleccionado los prints me funcionan bien. Pero después, si elijo una selección de ComboBox, al apretar las teclas no me reconoce el KeyPressEvent (o por lo menos yo asumo eso) ya que los prints no ocurren. Si después de hacer click en el ComboBox hago click nuevamente en los RadioButton, y solamente haciendo click en los RadioButton, ahí vuelven a funcionar los prints. La verdad no sé por qué ocurre eso siendo en que ninguna parte del código he editado alguna funcionalidad del ComboBox. (Hice el widget en QTDesigner)

**Comment by clementevalladares** [comment]
Hola @raimundosilvac, lo más probable es que el focus de tu ventana se esté cambiando hacia el QComboBox cuando lo presionas. Puedes verificar esto presionando las teclas de arriba y abajo y viendo si se cambia la opción del ComboBox. Para devolver el focus a tu ventana, y que vuelva a funcionar el keyPressEvent, debes hacer `self.setFocus(True)`.
Si quieres que esto pase cada vez que se selecciona un ítem diferente, los QComboBox emiten la señal `currentIndexChanged` cuando ocurre este evento.
Espero que te haya sido de ayuda, avísame si sigues con el problema.
