### ISSUE TITLE
Otra ronda

### ISSUE THREAD

**Issue by maureenmaremaa** [IIC2233/syllabus#563]
Hola! Quería saber si cuando termina el juego y el jefe elige jugar otra ronda, los usuarios deben esperar a que el jefe haga click en "Iniciar partida" o si el juego comienza al tiro. En caso de tener que esperar a que el jefe inicie la partida, ¿pueden ingresar nuevos jugadores al juego?

**Comment by KnowYourselves** [comment]
Hola @maureenmaremaa!

Queda a tu criterio. Tienes dos opciones:

1. La siguiente partida inicia inmediatamente.
2. Se vuelve a la sala, por lo cual hay que esperar que el jefe apreté el botón de iniciar partida, por lo cual nuevos jugadores pueden ingresar antes que lo haga.

Ambas son válidas, éxito!
