### ISSUE TITLE
Alumnos en cola a las 15:00 hrs

### ISSUE THREAD

**Issue by estebanmb** [IIC2233/Syllabus#563]
Solo para confirmar:
Al igual que con los funcionarios,  ¿si a las 15:00 los alumnos están en una cola de almuerzo, se van instantáneamente al *Quick Devil* ?

**Comment by Hernan4444** [comment]
@estebanmb como la simualción termina a las 15:00, queda a tu criterio que decision tomas
Saludos ✌️
