### ISSUE TITLE
Recorrecciones

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#564]
Hola! Una duda, como se sabe cuando una recorreccion esta hecha? Cual es el mail de ayudantes para dudas personales respecto a estos temas?

Saludos!

**Comment by FernandoPieressa** [comment]
Hola!

Cuando las recorrecciones estén listas, lo anunciaremos en siding!

El mail de contacto para cualquier tema personal es ayudantesiic2233@gmail.com

Saludos!

**Comment by rihanuch** [comment]
Si, es de una actividad, pero la respuesta me parece insatisfactoria por un tema lógico, eso cae como segunda recorreccion?

**Comment by rihanuch** [comment]
Gracias!!

**Comment by jtagle2** [comment]
Todas las recorrecciones que no te dejen satisfecho, se pueden ver al final del semestre en la recorrección final donde se recorrigen las últimas dos actividades, el examen y todas las actividades (siempre y cuando, hayan sido enviadas a recorregir en su momento).
Saludos
