### ISSUE TITLE
Bonus emojis

### ISSUE THREAD

**Issue by furzuadr** [IIC2233/syllabus#564]
Para el bonus de emoji cuántos debo hacer? Estoy haciendo un diccionario con los unicodes, pero no sé cuáles ni cuántos me pedirán. Gracias!

**Comment by KnowYourselves** [comment]
Hola @furzuadr!

Estrictamente hablando, solo es necesario que sea uno, lo importante es que si yo reemplazo tu diccionario con otro que siga el mismo formato y con más emojis, funcione correctamente.

Éxito!
