### ISSUE TITLE
Progreso tarea 5

### ISSUE THREAD

**Issue by diegonavarrovergara** [IIC2233/Syllabus#564]
Hola, no sé si un problema mío o es un problema generalizado, pero esta tarea se me ha hecho mucho más difícil y más larga que lo normal. Me leí toda la materia, pero es necesario saber muchas cosas que no están en ella. Además he investigado harto y aún así me cuesta avanzar.

Como decía el enunciado de la Tarea 4, mi progreso de esta tarea es menor que el 50%, por lo tanto le pregunto a los ayudantes si existe alguna posibilidad de extender el plazo de entrega , aunque sea unas horas más.  😃

Gracias.

**Comment by Dunkan1** [comment]
:smile:

**Comment by tburotto** [comment]
+1

**Comment by mjaguirre** [comment]
+1

**Comment by aSPCA** [comment]
+1

**Comment by flobarrios** [comment]
Estimados, 
No podemos dar mas plazo dado que estamos a fines de semestre y aun quedan dos tareas más a realizarse.
Saludos!

**Comment by acrojas2** [comment]
:( a la fecha mi monito solo sigue al mouse y lo mueve con las teclas y aparecen minions por todos lados (pero no siguen a nadie). No sé si sirva una hora mas la verdad :/ .

**Comment by akaminetzkyp** [comment]
¿No existe la posibilidad de extender el plazo en un día sin cambiar la fecha de publicación y entrega de la siguiente tarea?

Saludos!

**Comment by acrojas2** [comment]
@flobarrios 👍 
Igual a modo de sugerencia, para otro semestre podrían hacer la programatón en la semana 1 de esta tarea, porque a 4 días antes de la entrega no sirve tanto como en la primera semana, así sería posible tener más afianzados y reforzados los conceptos de PyQt y de cómo enfrentar esta tarea.
Saludines!

**Comment by hanavarrete** [comment]
@acrojas2  La programatón no está  a cargo de nosotros, sino que del ACM PUC (capitulo).  Es una instancia en que todo el dcc participa. De todos modos, siempre pueden ir a darse alguna vuelta por el dcc, siempre hay ayudantes y gente que sabe mucho dando vueltas por ahí. 
Saludos?

**Comment by acrojas2** [comment]
@hanavarrete yo lo decía a modo de sugerencia, también quizás podrían hacer una instancia similar a esta para esta tarea. Es super en la buena onda :) .
Saludos!

**Comment by Hernan4444** [comment]
@acrojas2 muchas gracias por la sugerencia, ya para el próximo semestre tendremos en consideración tu propuesta e intentaremos hacer que la ACM PUC (capitulo) fije la programatón para la primera semana de esta (o cualquier otra tarea) y así ayudarlos a empezar mejor pero no olvides agregarlo en la encuesta docente para tener un mejor registro de este feedback +1: 

Saludos!!

**Comment by gbordoni** [comment]
+1
Y quizas hacer un poco mas completa o explicar mejor la actividad sobre GUI...yo por lo menos no entendi nada ahí. Y los diagramas de secuencia sirvieron para perder tiempo nomás. 

saludos

**Comment by Hernan4444** [comment]
@gbordoni tus comentarios son valiosos para mejorar en la forma de hacer el curso pero ruego que estos comentarios no se queden solo en esta issue y los pongas en la encuesta docente para tener un registro de tal opinión :+1: 

Saludos!!
