### ISSUE TITLE
Tiempo en segundos, Tarea 4

### ISSUE THREAD

**Issue by meretamal** [IIC2233/Syllabus#564]
Tengo que el tiempo de preparación de los restaurantes se dan por un expovariate, por lo tanto, lo más probable es que obtenga un valor decimal. Debo dejarlo así y analizar los decimales como segundos o debo truncarlo en el minuto?

Muchas gracias de antemano

**Comment by leolivares** [comment]
Hola! 
Queda a tu criterio, puedes truncarlo por simplicidad.
Saludos!
