### ISSUE TITLE
Error en hacer push, hora al limite, envio 5 min tarde

### ISSUE THREAD

**Issue by javier-ICO** [IIC2233/syllabus#564]
Quise hacer push y me salió un error porque no estaba al día mi branch, me tardó 5 min arreglarlo y termine subiendo los archivos tarde, se puede hacer algo?

**Comment by Drpinto1** [comment]
¡Hola!

En general la recolección de actividades se realiza unos (pocos) minutos después de la hora oficial de entrega, con el objetivo de compensar la posible diferencia entre los relojes de cada uno y el tiempo que demora el *script* que registra sus *push* en hacer su trabajo, por lo que es posible que tu *push* esté dentro del plazo y sea revisado correctamente (Obtendrás confirmación oficial de esto cuando se abra la issue en tu repositorio con el *commit* a revisar)

En caso de que el commit no haya sido aceptado, lamentablemente, no podemos extender el plazo. La hora de entrega es la misma para todos y además, para efectos del curso, *Git* y *Github* no son solamente plataformas de entrega de evaluaciones, si no también herramientas que esperamos que aprendan a utilizar. Por lo anterior, intentamos recordarles lo más seguido posible que hagan *commit* y *push* regularmente con el objetivo de: respaldar regularmente tu trabajo; hacer entregas parciales en caso de inconvenientes inesperados; y llevar registro de las versiones y cambios en tu código, entre otras cosas.

Espero que tu *commit* quedara dentro del plazo y ánimo con lo que queda del curso.

Saludos.
