### ISSUE TITLE
archivo __init__.py

### ISSUE THREAD

**Issue by rmaguilera** [IIC2233/syllabus#564]
Hola en esta tarea puedo a una carpeta de modulos agregar el archivo vacio __init__.py para que lo reconozca como package y asi importar los modulos de esa carpeta? o me recomiendan que no cree esa carpeta y simplemente los importe de manera normal?

**Comment by aljara97** [comment]
Hola @rmaguilera!

Puedes crear tu propio package para importar tus módulos. Sin embargo, debes asegurarte de que este funcione de manera adecuada, ya que un ayudante **no se encargará de arreglarlo** en el caso de que no funcionen las importaciones correspondientes.

Éxito 🧙‍♂️
