### ISSUE TITLE
Poner imagenes sobre otras en un layout (QTdesigner

### ISSUE THREAD

**Issue by kraksiplus** [IIC2233/syllabus#564]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!!, espero que esten teniendo una buena semana :D, mi pregunta es sencilla.

Basicamente no se me ocurre como poner un sprite sobre otro mientras el sprite mas 'grande' se encuentra en un layout, dado que el layout me limita a poner las imagenes al lado o sobre la 'grande', pero nunca encima. Por lo que pregunto si conocen alguna opcion del programa para hacer esto. 

Por que por ahora, lo unico que se me ocurre (lo que seria mas engorroso) es poner los sprites mediante el  .py de la ventana, pero con el riesgo de que al cambiar su tamaño, los sprites no se moverian del lugar.

**Comment by Juampisaez** [comment]
Hola @kraksiplus 
Se me ocurren 2 cosas, si te entiendo bien estas queriendo colocar tu sprite de personaje sobre el mapa o algo por el estilo. Lo que podrias hacer en primer lugar es suponiendo que tienes un layout en Qt creado, podrias crear un label con el sprite que deseas y moverlo con las flechas del teclado (si lo haces con el mouse se inserta en el layout). La segunda que es la mas engorrosa para ti es hacerlo directamente en el archivo .py, lo cual igual es recomendable considerando que hay varios personajes. La ultima opcion, es que combines ambas cosas que te acabo de decir, creas el label en tu ventana y al momento de iniciar esa ventana, seteas el label en lugar que tu quieres.

Te dije varias cosas jeje, avisame si no se entendio algo.
Quedo atento.

**Comment by kraksiplus** [comment]
Gracias por contesar, si no me equivoco tu recomendacion seria dejar en un costado del mapa un label cualquiera (el cual se definiria su sprite segun que personaje se elija en los radio buttons) y fijar su ubicacion medianter codigo no?

(En la foto verás que al lado del mapa hay un TextLabel, ese seria el label que moveriamos a travez del codigo con self.label.move(x, y)??)

![image](https://user-images.githubusercontent.com/68204942/120255862-e9c85e80-c25a-11eb-8e4f-02583bda0d17.png)

**Comment by Juampisaez** [comment]
@kraksiplus 
Claro eso podria ser una opcion, o la otra podria ser que muevas ese label con las flechas del teclado encima del mapa.

**Comment by mjsifri** [comment]
Hola! yo tengo una duda parecida. Como puedo hacer que se vea un QLabel que está atrás de una grilla? Además, cuando agrego imágenes a los labels dentro de la grilla, se alteran los tamaños. Que puedo hacer? o esa no es la forma de hacer la grilla?
Saludos

**Comment by Juampisaez** [comment]
Hola @mjsifri.
Respondiendo a tus dudas:
1. Respecto a tu primera duda se me ocurre que puedes traerlo al frente (Qlabel tiene metodos para hacer eso en codigo).
2. Podrias cambiarles el tamaño dentro del mismo codigo segun lo que estes buscando.
3. Por ultimo, si tu duda es mas practica y menos conceptual, podrias revisar esta [issue](https://github.com/IIC2233/syllabus/issues/521), ahi comente unos videos que se hicieron semestres pasados que podrian servirte. 
 
Espero te sirve de ayuda :)

**Comment by kraksiplus** [comment]
Al final lo puder solucionar jeje, muchas gracias!!

**Comment by Juampisaez** [comment]
@mjsifri 
Lo busque y tampoco lo encontre, pero anda probando tal vez no sea necesario traerlo alfrente y solo sea necesario actualizar el label.
