### ISSUE TITLE
Duda Enunciado

### ISSUE THREAD

**Issue by gianfrancoantonucci** [IIC2233/syllabus#564]
Hola, tengo una duda sobre Simular competencias. Que en la sección 3.2.2 del enunciado dice que hay que elegir a los deportistas que competirán, y que luego se simulan las competencias según lo establecido en la sección de Campeonato. Pero en el método de Campeonato de Realizar competencias menciona nuevamente que hay que definir a los deportistas. Entonces, ¿puedo hacerlo en Realizar competencias, o hay que realizarlo antes de llamar al método?
También en simular competencias dice que hay que imprimir una lista cada vez que se elige un participante, pero me parece más lógico imprimirla una vez, si es que se puede, ya que lo dice explicitamente en el enunciado (además no se si se refiere a una lista de Python o simplemente a que hay que mostrarlos a todos).
Gracias

**Comment by hsazos** [comment]
¡Hola @gianfrancoantonucci !

Puedes hacerlo en realizar competencias, mientras explicites en el readme como modelaste el flujo de elegir competidores. Y la lista corresponde a mostrarlos a todos, no necesariamente a una lista de python.

¡Animo con la tarea!🦕

**Comment by gianfrancoantonucci** [comment]
Muchas gracias
