### ISSUE TITLE
Decidir ir a restaurante

### ISSUE THREAD

**Issue by pcseisdedos** [IIC2233/Syllabus#565]
En la sección 3.1.1 dice:

>  Restaurante: (...) En caso de que no haya un restaurante disponible, elige la opción “descansar” y luego vuelve a tomar una decisión.

"No hay un restaurante disponible" incluye que el grupo no pueda ingresar porque no ha visitado ninguna de las atracciones asociadas al restaurante? o se refiere solamente a la capacidad del restaurante en ese momento y la otra restricción debe verificarse al momento de ingresar?

**Comment by monicabelen** [comment]
Hola, esto no se especifica en el enunciado, por lo tanto, queda a tu criterio (podrías realizar cualquiera de las dos opciones que mencionas).
