### ISSUE TITLE
Sección Amistades

### ISSUE THREAD

**Issue by bahidalgo** [IIC2233/syllabus#565]
Hola, tengo algunas dudas referente a esta parte:

a) Si el usuario A desea agregar al usuario B, ¿Es necesario que tanto A como B estén en la misma sala? Ya que mi programa permite que A agregue a B incluso si B **NO** está conectado.

b) Si A quiere calcular la distancia a B, ¿puedo colocar un límite? Por ejemplo, si dicha distancia es mayor a 15, dejar de buscar, dado que mi función es recursiva (agregando dicho 15 al archivo _parametros.json_) ¿O es preferible que actúe hasta su límite de recursiones?

Gracias!

**Comment by jmwielandt** [comment]
Hola!

a) Se debe poder amistar a un par de usuarios incluso si **ninguno de estos** está conectado. No sé si es exactamente como lo tienes. Yo como usuario C puedo querer ejecutar el comando` /friend 'A' 'B'` y es válido.

b) ¿En qué caso quieres calcular la distancia entre dos usuarios?

Saludos

**Comment by bahidalgo** [comment]
Hola!

a) Perfecto!

b) Me acabo de dar cuenta que leí mal. En la función: 
          **/get affinity** <_nombre usuario 1_> <_nombre usuario 2_> 
    Pensé que me pedían el valor de la distancia d entre ambos, pero ahora lo cambié a la ecuación.

Muchas gracias por la pronta respuesta
