### ISSUE TITLE
Salir del programa desde un modulo

### ISSUE THREAD

**Issue by diegobustosk** [IIC2233/syllabus#565]
Hola cuando utilizo la función exit(), sys.exit() o quit() desde un modulo me arroja error. Hay alguna forma de salir del programa desde un modulo?

**Comment by amparostevens** [comment]
Hola @diegobustosk!

Estás corriendo el programa desde vscode o desde la consola de tu computador?

**Comment by diegobustosk** [comment]
Oooo era por eso estaba corriéndolo con el debugger. Muchas gracias !!!

**Comment by amparostevens** [comment]
Que bueno que te funciona! Igual, por si prefieres hacerlo con el debugger sólo tienes que entregarle un argumento como  `sys.exit(0)` y debería funcionar bien en ambos.
