### ISSUE TITLE
variables en variables.py

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#565]
No me queda muy claro cuales son las variables que quieren que guardemos en variables.py, no se si podrían explicar más específicamente cuales hay que agregar a este archivo.
Gracias

**Comment by felipecr00** [comment]
misma pregunta, ademas si genero una distribucion que quiero que cambie y la guardo en variables.py
por ej:
variacion_mesada = (1 + random.random()**random.random())*20
Ese valor no va a cambiar nunca porque la variacion queda fija, (y seria un caso donde es una "cte" a usar para el calculo del base mesada, que no usa parametros entregados para esa variacion).

Saludos!
