### ISSUE TITLE
Filtro Imagen

### ISSUE THREAD

**Issue by MGilB** [IIC2233/syllabus#565]
Hola, no entiendo muy bien el como transformar la matriz a pixeles RGB, ya que la matriz original, que se obtiene por la función get_pixels, cada pixel es una tupla de cuatro numeros. Pero en la parte de transformación a escala de grises, se nos aconseja que al obtener el "x", en vez de ponerlo 3 veces, por el RGB, trabajemos con sólo uno. 
¿ Después de obtener la matriz gradiente se, cada elemento hay que triplicarlo, para hacer cada canal?
 ¿Si quiero usar el Alpha de transparencia, en que posición va en la tupla?

**Comment by jeschuwirth** [comment]
Hola!

La primera pregunta esta muy bien explicada por @ariel-m-s en la siguiente issue: #497 

Para la segunda el valor alpha va en la cuarta posición en la tupla, ten en cuenta la issue #515 al momento de guardar tu imagen.

Ojalá te haya quede claro con eso, suerte en la tarea !
