### ISSUE TITLE
Comentario Avance T2

### ISSUE THREAD

**Issue by panchotarud** [IIC2233/syllabus#565]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Leyendo el comentario sobre mi avance, me dijeron que tuviese cuidado con la locación de los sprites. Actualmente yo los organicé en carpetas ( T2/frontend/assets/sprites ) para mantener un orden y poder hacer el espacio de trabajo mas limpio. Pero en el comentario me dicen que debiesen estar todos en la carpeta T2. Por qué es esto?

**Comment by Juampisaez** [comment]
Hola @panchotarud
Probablemente el comentario de que estuvieran en la carpeta T2 es para hacer mas facil la correción. Sin embargo, consultandolo con los demas ayudantes podrias colocarlo en la dirección que tu comentas, **pero debes comentarlo en el readme**.

Espero que quede claro :)

**Comment by panchotarud** [comment]
Ya bacaan! graciass.
