### ISSUE TITLE
duda ganancia total de un local

### ISSUE THREAD

**Issue by benjadelgado** [IIC2233/Syllabus#565]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!, escribo porque cuando ejecuto los test case de carga_datos en la función ganancia total de un local, cuatro de los testcase están buenos y uno falla por solo una unidad. Por el lado de los test de correctitud, también me pasa que los valores fallan por solo una unidad. El round lo tengo al final (en el return) como ha sido la tendencia de las otras funciones con cálculos, y esto ha funiconado. Sin embargo en este caso, no sé que es lo que hace que mis resultados difieran en una sola unidad. De antemano gracias!

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by AlonsoPlaza** [comment]
Hola, el problema es que estás haciendo round a la ganancia total del local cuando deberías usarlo para cada ganancia de cada pedido por separado y luego sumarlo.
