### ISSUE TITLE
QThread duda

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#565]
Hice una clase Qobject y dentro de su init instancié y empecé un QThreat. Lo que ocurre, según los prints que puse, es que entra al run del Qthread y no sale de ahí, es decir, el programa no continua con el resto del init del Qobject. Eso contradice lo que entiendo por Thread. 

Como dato adicional puedo decir que el QThread se comunica constantemente con el Qobject a traves de señales, no se si tenga que ver, además es la unica forma que veo de hacer lo que quiero hacer.

Ayuda!

**Comment by Hernan4444** [comment]
@jorgeriesco a tu Qthread hiciste thread.start() o thead.run()

**Comment by jorgeriesco** [comment]
run jajaj si acabo de cachar. siempre me pasa que pregunto y me doy cuenta del error un minuto despues

**Comment by Hernan4444** [comment]
Que bueno que alegraste el error :+1:
