### ISSUE TITLE
Quedarse sin alimentos

### ISSUE THREAD

**Issue by FelipeLara00** [IIC2233/syllabus#566]
Hola! Mi duda es si en algun momento un magizoologo puede quedarse sin alimento o se asume que simpre tiene mas de uno. Tengo este problema al actualizar el archivo ya que si no tiene alimentos, en el archivo aparecen dos comas seguidas.

**Comment by matiasmasjuan** [comment]
Hola @FelipeLara00 !

Esta pregunta fue respondida en la ***Issue*** #428 .

Saludos! 😄
