### ISSUE TITLE
duda modelacion circular y señales

### ISSUE THREAD

**Issue by snarriagada** [IIC2233/syllabus#566]
Hola, aun tengo dudas sobre como implementar correctamente la comunicacion por señales entre mi cliente.py  y el frontend.py

Si tengo instanciada una clase  del frontend (ventana principal) en mi cliente, puedo usar una señal hacia instancias de esa clase del frontend?, de esta manera:

en cliente.py:
self.nueva_sala_signal.connect(self.ventana_principal.ventana_salas.mostrar_nueva_sala)

gracias!

**Comment by KnowYourselves** [comment]
Hola @snarriagada!

Especificamente lo que esta prohibido es **instanciar el front end en el backend y viceversa a la vez**, solo uno puede estar instanciado en el otro. Si tu código luce así:

```python3
...
self.front_end = Frontend()
self.señal_backend.connect(self.front_end.funcion_front)
...
```

Está bien!, Si es que tus clases de frontend están anidadas (es decir, hay clases dentro de otras) también está bien.

Éxito!

**Comment by Juaco97** [comment]
> Hola @snarriagada!
> 
> Especificamente lo que esta prohibido es **instanciar el front end en el backend y viceversa a la vez**, solo uno puede estar instanciado en el otro. Si tu código luce así:
> 
> ```python
> ...
> self.front_end = Frontend()
> self.señal_backend.connect(self.front_end.funcion_front)
> ...
> ```
> 
> Está bien!, Si es que tus clases de frontend están anidadas (es decir, hay clases dentro de otras) también está bien.
> 
> Éxito!

¿En ese contexto, el código estaría escrito como parte del cliente? No entendí un poco la específicación que haces. ¿Se puede instanciar la interfaz en el cliente y mantener una relacion solo de señales entre cliente/interfaz? (lo pregunto ya que mi idea de instanciar la interfaz en el cliente es solo para hacer las conexiones de las señales que mando a la interfaz, y que la interfaz tenga un "parent" con el que comunicarse.

**Comment by KnowYourselves** [comment]
Hola @Juaco97!

Supongamos que tienes un `backend` y un `frontend` genérico. Tienes tres opciones que son válidas:

1. Instanciar el `backend` en el `frontend`:

```python3
...
self.backend = Backend()
self.senal_front.connect(self.backend.funcion_back)
...
```
2. Instanciar el `frontend` en el `backend`:

```python3
...
self.frontend = Frontend()
self.senal_backend.connect(self.frontend.funcion_frontend)
...
```
3. No instanciar ninguno dentro del otro y conectar las señales desde fuera (`main.py`):

```python3
...
backend = Backend()
frontend = Frontend()
conectar_señales(backend, frontend)
...
```

Ahora qué **no debes hacer?** Lo siguiente:

```python3
# Esto en el backend.py
self.frontend = Frontend(self)
...

# Esto en el frontend.py
self.parent = parent
```

Las primeras tres opciones evitan la modelación circular, mientras que la última es exactamente modelación circular. Si quieres que tu frontend se comunique con su padre (en tu caso, el cliente), debe ser mediante señales, y no mediante llamados directos a su padre.

Espero haberte ayudado!

**Comment by snarriagada** [comment]
Sobre lo ultimo, revisando efectivamente en backend hago:
self.frontend = Frontend(self)
pero en la clase Frontend no hago self.parent = parent en el __init__(self, parent, *args, **kwargs), sino que solo lo ocupo directo para conectar la señal:
self.terminar_conexion_signal.connect(parent.terminar_conexion)

Es modelacion circular en este caso?, sin instanciar el parent, pero usandolo?
si lo es como envio la señal desde el frontend al backend?
espero se entienda, gracias!!

**Comment by KnowYourselves** [comment]
Hola @snarriagada!

En ese caso también es modelación circular. Lo que puedes hacer es:

```python3
...
self.frontend = Frontend()
self.frontend.terminar_conexion_signal.connect(self.terminar_conexion)
...
```
Espero haberte ayudado!

**Comment by jfpena1** [comment]
Hola, tengo una consulta sobre este tema, entiendo que no se pueda instanciar al frontend dentro del backend y vice versa. 
Sin embargo, en el caso del servidor que no tiene frontend, es posible instanciar la clase de la logica del juego en el servidor y en la logica del juego instanciar al sevidor? Me refiero a algo del estilo:

en servidor.py:
self.juego = Juego(self, otro params)   # modulo que verifica aristas, cuadrados completos, tiempos etc..

en juego.py
self.servidor = servidor


Muchas Gracias

**Comment by KnowYourselves** [comment]
Hola @jfpena1!

Eso también se considera como modelación circular.

Éxito!
