### ISSUE TITLE
Duda con parametros: cuan literal es lo de ningún valor numérico en el código?

### ISSUE THREAD

**Issue by icampusano** [IIC2233/Syllabus#566]
Hola, mi consulta es muy nada, pero es para ver si debo modificar o no ciertos criterios dentro de mi código.

Entiendo que los parámetros se deben incluir en un módulo aparte, pero al leer el enunciado me queda la duda de si en los códigos ciertos elementos típicos serían o no aceptados. Por ejemplo indexación de una lista. 

En otras palabras, ¿se acepta (por dar un ejemplo concreto) poner lista_cualquiera[0]? ¿O se debe poner algo del estilo: lista_cualquiera[cero]? (teniendo definido cero = 0 en el módulo de parameters.py)

**Comment by leolivares** [comment]
Hola! @icampusano 
Para acceder a un elemento de una lista no es necesario.
Con parámetros se refiere a todos los datos relevantes a la simulación, y que se mantienen constantes.
Saludos!

**Comment by sjkinast** [comment]
Hola y en casos como por ejemplo si quiero calcular el largo de un grupo y hago por ejemplo 
(largo de niños +1) por el adulto, ahi el uno se tiene que poner en parameters también ? 
Osea en verdad la pregunta mas general es si los numeros que no referencias parametros que se mantienen constantes en la simulación y que son implementados por la propia modelación no se puede poner ?

**Comment by Hernan4444** [comment]
@sjkinast si son números implementados por tu propia modelación, no es obligatorio ponerlo. Mientras estén los que nosotros indicamos en el enunciado, todo está bien.

Saludos ✌️

**Comment by FJavierOss** [comment]
¿Y en el caso de un if donde el parametro se compara con una probabilidad?
Por ejemplo: vuela = 0.7

> if vuela > uniform(0,1):
>> do something

El uniform como esta puesto no deberia traer problemas o no?

**Comment by Hernan4444** [comment]
Tampoco hay problema
