### ISSUE TITLE
distribucion almuerzo MiembrosUc

### ISSUE THREAD

**Issue by inmadariaga** [IIC2233/Syllabus#566]
Sinceramente no logro entender esta parte, al leer las issues me mareo aun mas. Del enunciado:
"El X % de los alumnos y funcionarios almuerza de 13:00 a 13:59, el Y % almuerza de 14:00 a 15:00, mientras que el (100−X−Y )% lo hace de 12:00 a 12:59"
*el X% y el Y% de miembrosuc que come en ese horario lo designo yo de manera arbitraria/aleatoria?
*se determina cada día? o se determina una vez para toda la simulación?

**Comment by iqacevedo** [comment]
Hola,

Se determina solo una vez al comienzo de la simulación, quienes almuerzan en qué horario, mantiendo esos porcentajes (son los hábitos de las personas, la hora a la que almuerzan regularmente). Tiene que ser un cálculo aleatorio, pero no sigue ninguna regla en particular mas que mantener esos porcentajes.

Espero que te haya quedado más claro, si no es el caso me avisas.

Saludos !

**Comment by mjgutierrez1** [comment]
Hola @inmadariaga , no soy ayudante, pero si no me equivoco el X% y el Y% no los designas tú de manera arbitraria, sino que vienen como parámetros en el archivo parametros_iniciales.csv en la columna distribucion_almuerzo (sale explicado en la primera línea de la página 10 del enunciado). Creo que esa era tu primera pregunta.
