### ISSUE TITLE
No aparecen los QLabels

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#566]
Hola, no se que paso, pero luego de mover hartas cosas, no me aparece ningún QLabel, excepto el fondo.

¿A que se podría deber esto?

**Comment by jorgeriesco** [comment]
ya cache

**Comment by iqacevedo** [comment]
@jorgeriesco por favor antes de abrir una issue asegúrate de que no la puedas resolver por tu propia cuenta, si ese es el caso recuerda dar más detalles para que podamos entender el error, ya que en este caso era algo muy general y no podríamos haber sabido que error era a menos que conociéramos tu código.

Saludos

**Comment by jorgeriesco** [comment]
No la pude resolver po jaja

**Comment by Hernan4444** [comment]
@jorgeriesco a eso vamos, si es que no lograste resolverla, especifica mejor tu error para que podamos ayudarte. En caso de que lo lograste resolver después de preguntar, te recomiendo detallar en como lo solucionaste para que si alguien tiene ese mismo error, intente seguir lo que tu hiciste.

Saludos!!!
