### ISSUE TITLE
dudas sobre los parametros

### ISSUE THREAD

**Issue by enriquerussi** [IIC2233/syllabus#566]
hola, en los parametros hay uno que se llama PROBABILIDAD_ACCIDENTARSE_GIMNASIA, esto quiere decir que el riesgo que trae cada deporte especifico puede cambiar o es fijo y propio del deporte? de ser el caso de la segunda opción, no le encuentro el propósito a el parametro ya que ya es fijo dependiendo del deporte en cuestión.

**Comment by vicentevegaulloa** [comment]
Hola @enriquerussi !

El riesgo es distinto para cada deporte y no cambia durante el transcurso del programa. La razón por la que es un buen parámetro es porque evita meterse en el código para modificarlo, y por ende, lo hace más fácil a la hora de programar o corregir. Si quieres probar cosas como properties o si tus calculos de probabilidad están buenos, puede modificar el valor del riesgo desde los parámetros de manera sencilla. En resumen, la probabilidad de accidentarse por deporte es un buen parametro ya que es un valor constante en el programa.

Espero haber aclarado tu duda 😄

**Comment by camilapavesi** [comment]
Hola @vicentevegaulloa !
Puedo cambiarle el nombre al parámetro ```PROBABILIDAD_ACCIDENTARSE_GIMNASIA``` por simplemente ```RIESGO_GIMNASIA```? Sorry lo especifico de la pregunta :) 
Gracias!

**Comment by vicentevegaulloa** [comment]
Hola @camilapavesi !

No hay problema con que pongas tus propios nombres a los parámetros pero recuerda escribirlo en tu README 😄
