### ISSUE TITLE
Corrección de tarea en base a distribución de puntaje entregado

### ISSUE THREAD

**Issue by lfb1206** [IIC2233/syllabus#566]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Buenas noches, luego de la reciente entrega de las notas de la tarea 1 y su respectiva distribución de puntaje me di cuenta, al revisarla, que en la distribución de puntaje se generaliza demasiado sobre la dicha distribución. Por ejemplo, en "la tripulación esta modela correctamente" al parecer se exigía que cada tripulante tuviese su propia clase que hereda de una clase abstracta, algo muy simple de arreglar de haberlo sabido, pero no hay ningún lugar donde se especificara o incluso mencionara esto, entonces claramente no fue realizado por la simpleza de la tripulación. También en el caso de la creación de los canales, donde al parecer era necesario utilizar properties, cosa que tampoco se mencionaba en algún lugar y lo que finalmente se traduce en otro descuento. Por ultimo, la moderación de barcos, donde al parecer utilizar una función externa para calcular la probabilidad no se puede o por lo menos no se debería realizar. Todos estos descuentos eran simples de evitar pero no se mencionaba ni en el PDF, ni en la distribución de puntajes, entonces como uno puede decidir si su código esta bien modelado o no.

Muchas gracias y espero que esta situación pueda ser corregida para la próxima tarea.

**Comment by lily416** [comment]
Hola @lfb1206,

Primero que todo, queremos tomar este espacio para explicar los objetivos de las dos principales evaluaciones del curso: actividades y tareas.

> _[...] Las actividades están pensadas para que ustedes se enfrenten a los conceptos que estudiaron en el material del curso, puedan aplicarlos y resolver dudas. Como deben ser resueltas en un periodo muy corto de tiempo, nosotros les decimos exactamente lo que deben hacer. Estas tienen un enfoque técnico, ya que ustedes no tienen que pensar qué herramientas usar, sólo aplicar los conceptos._
>
> _El objetivo de las tareas, en cambio, es que ustedes puedan resolver un problema complejo usando de la mejor manera posible los conceptos vistos. Por lo tanto, **no sólo deben entender las herramientas de programación, sino que deben pensar cómo usarlas de la mejor forma posible.** En una tarea nunca les vamos a decir qué herramientas usar ni cómo usarlas, ya que una de las cosas que se está evaluando es que ustedes puedan tomar estas decisiones._
>
> Fuente: [issue 2017-2](https://github.com/IIC2233/Syllabus-2017-2/issues/131#issuecomment-323901288)

Sabemos que la explicación anterior es de hace varios años, sin embargo, el objetivo de dichas evaluaciones sigue siendo el mismo hasta esta fecha. En base a lo anterior, queremos aclarar que es una **decisión del cuerpo docente hacer que ni el enunciado ni la pauta entregada en la Tarea 1 a les estudiantes indique de forma explícita dónde hacer uso de clases abstractas, polimorfismos, properties, entre otros**. 

Incluso, dentro de los objetivos de la tarea (los cuales se incluyen al inicio del enunciado) se encuentra:
> * _Aplicar conceptos de programación orientada a objetos (POO) para modelar y resolver un problema._
> * _Utilizar properties, clases abstractas y polimorfismo como herramientas de modelación._

Y, dentro de uno de los párrafos del cuerpo del enunciado, se menciona que:
> _Para modelarlas correctamente, deberás utilizar conceptos clave de programación orientada a objetos: herencia, clases abstractas, polimorfismo, properties y relaciones, ya sean de agregación o composición. Cada uno de estos elementos debe ser incluido en el programa al menos una vez, y **deberás descubrir** dónde implementarlos según lo propuesto por el enunciado._

Por lo que si se dijera de forma explícita en el enunciado o pauta entregada dónde usar estos conceptos, entonces no se cumplirían los objetivos de la evaluación. Buscamos que, en base a lo aprendido en el curso, puedan analizar un problema real y aplicar una modelación que utilice todos los conceptos vistos y permita resolver dicho problema de forma adecuada. Luego, al momento de corregir se da bastante libertad respecto a cómo modelar el programa, salvo ciertos puntos claves que definimos deberían tener una forma óptima de hacerse, a la que ustedes deberían poder llegar. Estos puntos mencionados anteriormente son definidos al momento de crearse el enunciado, por lo que buscamos hacer que el texto dé suficientes pistas respecto a la modelación ideal, sin llegar a dar la respuesta directa.

Por todo lo anterior, la pauta entregada a los estudiantes y la utilizada en la corrección no es algo que deba ser arreglado. 

Finalmente, si consideras que en base a los contenidos vistos en el curso se te corrigió de forma incorrecta, puedes llenar el formulario de recorrección de la tarea, justificando adecuadamente por qué deberías tener mayor puntaje en algún ítem. Así podemos ver el caso y si la apelación corresponde en mayor detalle.


Esperamos que entiendas las razones detrás de esta decisión. 

Saludos,
Francisca y Daniela
