### ISSUE TITLE
Mi código no funciona bien en el archivo 'consultas.py' pero si en un archivo distinto

### ISSUE THREAD

**Issue by gato-late** [IIC2233/Syllabus#566]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, buenas tardes. Estoy teniendo problemas con mi tarea específicamente en la parte de carga de datos. Mi problema es que mi código funciona bien en un archivo distinto del 'consultas.py' (pues hago manualmente las pruebas que hace el test 00 y todo funciona perfecto), pero en el 'consultas.py' sigue arrojándome un AssertionError. ¿Qué es lo que puede estar ocurriendo?

(P.D: subí mi código a mi repositorio en caso de ser útil)

**Comment by mane6867** [comment]
Hola!, podrías subir tu archivo `funciones_auxiliares`? para revisar mejor tu código

**Comment by gato-late** [comment]
Hola, un profesor me acaba de ayudar así que ya tengo mi duda solucionada, muchas gracias en todo caso por tu respuesta @mane6867!!! :D

**Comment by el-Jay-C** [comment]
> Hola, un profesor me acaba de ayudar así que ya tengo mi duda solucionada, muchas gracias en todo caso por tu respuesta @mane6867!!! :D

Holaaa podrias decir cómo lo hiciste?? acabo de comprobar y estoy teniendo el mismo error 😢
