### ISSUE TITLE
paths tarea

### ISSUE THREAD

**Issue by asuribe** [IIC2233/syllabus#566]
En el archivo de parametros, como puedo escribir los paths para que sean generalizados??
Tengo problemas con eso :(

**Comment by DCCollao** [comment]
Hola! 

Para escribir los paths de forma relativa, es muy útil usar `\..` como si fuera un directorio. Esto te dirige a la carpeta madre de donde ejecutas el código, por ejemplo, utilizando el diagrama del enunciado:
![image](https://user-images.githubusercontent.com/37167447/69894701-d523a700-1301-11ea-8514-875a100e759a.png)

Si quisiéramos llegar desde un archivo `.py` en el cliente a algún archivo ubicado en el servidor sin utilizar sockets (**Esto es incorrecto para la tarea, es solo como ejemplo de navegación entre directorios. Toda comunicación entre servidor y cliente(s) debe ser mediante sockets**), tendríamos que escribir nuestro path de la siguiente forma:
- `\..` para pasar desde `cliente` al directorio de tu tarea, `T03`.
- Ahora que estamos en `T03`, podemos navegar a `server`. Hasta ahora, nuestro path es `\..\server`
-Por último, ya podemos acceder al archivo que deseemos dentro de server, por ejemplo, `parametros.json`

Entonces el path completo para acceder a `parametros.json` del servidor, desde el cliente sería:
`\..\server\parametros.json`.

Quedo atento a cualquier duda! Y recuerda que para efectos de la tarea acceder de esta forma al servidor es **incorrecto**, pues su información debe ser comunicada solamente mediante sockets.

**Comment by JuaniAndres** [comment]
No tendríamos que ocupar os para generalizar los paths para cualquier sistema operativo?

**Comment by asuribe** [comment]
Pense eso, pero como el archivo de parametros es json, no pude usar codigos de python, solo puedo hacer un diccionario

**Comment by JuaniAndres** [comment]
lo que se puede hacer es guardar en el json una lista de strings de las partes del path esa lista la puedes desempaquetar en el join del os

**Comment by DCCollao** [comment]
La forma que mencionas es una de las que puedes usar!

**Comment by nfragav** [comment]
Hola! Ya que no puedo usar `open('..', file)` queria saber si es que se puede usar el metodo de `os` `path.dirname(__file__))` para "desempaquetar" el directorio absoluto y obtener los archivos que el directorio padre contenga con `join`.
