### ISSUE TITLE
Duda buenas practicas sobre cohesion y acoplamiento

### ISSUE THREAD

**Issue by jervaal** [IIC2233/syllabus#567]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Holaa! espero que esten bien, tengo una duda sobre si es buena practica tener un Qtimer en e frontend, que cada cierto tiempo envie una señal que verifique el choque de 2 objetos (en el frontend solo envio los QWidgets que podrian colisionar, y en el backend verifico si se realiza esta colision o no)

De antemano muchas gracias!

**Comment by mmunoz12** [comment]
Hola @jervaal! Lo que mencionas me da la sensación que también se podría implementar en el backend sin problemas, poniendo el QTimer en el backend y enviando señales al frontend cada vez que se requiere verificar la posible colisión. Quizás es más largo de realizar pero así te aseguras de que tu frontend sólo se ocupe de manipular la interfaz gráfica y de enviar las señales recibidas por esta al backend. Avísame si te quedan dudas! :)

**Comment by jervaal** [comment]
> Hola @jervaal! Lo que mencionas me da la sensación que también se podría implementar en el backend sin problemas, poniendo el QTimer en el backend y enviando señales al frontend cada vez que se requiere verificar la posible colisión. Quizás es más largo de realizar pero así te aseguras de que tu frontend sólo se ocupe de manipular la interfaz gráfica y de enviar las señales recibidas por esta al backend. Avísame si te quedan dudas! :)

Holaa, muchas gracias por la respuesta! realicé eso y me funcioná a la perfeccion (el frontend solo se encarga de mostrarse, aparecerse y esconderse cuando es necesario). Sin embargo, al momento de realizar esto me encontre con un error que estaba cometiendo, que era que al momento de iniciar el frontend, enviaba una senal para poner en marcha el backend, pero al momento de crearlo (creo yo que) enviaba la señal cuando el backend aun no estaba creado!, por lo que tuve que poner un QTimer de singleshot que esperase un poco para emitir la senal de inicializar la ventana. ¿Esto tambien recae en la buena practica de cohesion y acoplamiento?. Por que la verdad no se me ocurre otra manera de arreglar ese error u.u,

De antemano muchisimas gracias!

**Comment by mmunoz12** [comment]
Por como lo explicas me suena a que no debiese haber problema si sólo estas haciendo que el programa “espere” un poco antes de continuar con tal acción. Sino podrías buscar una forma en que el backend se cree antes (sin correr las funciones correspondientes para no adelantarse a la inicialización de la ventana). Lo importante es que utilices las señales para unir backend y frontend, sin aplicar parte de la lógica y mecánicas del juego en este último. Espero que se haya entendido! quedo atenta :)
