### ISSUE TITLE
Problema while cliente

### ISSUE THREAD

**Issue by jjzapatai** [IIC2233/syllabus#567]
Hola, estoy teniendo un problema en mi modulo cliente. Al escuchar al servidor, no se porque no pasa el while (linea 74). LLevo mucho rato intentando de solucionarlo. Aiua porfa! Hice un push recién. Además, cuando ingreso un usuario se me cierra la sesión de inmediato.

**Comment by KnowYourselves** [comment]
Hola @jjzapatai!

En primer lugar, recuerda seguir la estructura que les dijimos en el enunciado 👀, ahora en cuanto a tu error, es la linea 48 de tu `frontend.py`, donde conectas el botón de log-in con el close de la ventana. Lo que pasa, es que apenas hagas click en el botón, se va a cerrar la ventana y por lo tanto el programa entero para, ya que no hay ninguna interfaz siendo mostrada. Si comentas esa línea, funciona correctamente.

Éxito y cuéntame que tal!

**Comment by jjzapatai** [comment]
Graciass!! Me funcionó perfecto!
Supongo que con la estructura te referías a que aun no lo tengo separado en carpetas Cliente/Servidor

**Comment by KnowYourselves** [comment]
Que bueno!, Y si, me refiero a que el cliente y el server deben estar en carpetas distintas y cada uno tiene que tener un main.py

Éxito!
