### ISSUE TITLE
Duda Test consulta anidada test numero 4

### ISSUE THREAD

**Issue by Cristobal-Hevia** [IIC2233/Syllabus#567]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [x ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
del test consultas anidada solo me falla el numero 4 y por una diferencia en el monto ahorrado, que segun yo se da porque el argumento de generador_pizzas que entra a la funcion total_ahorrado_pedidos() tiene 9 pizzas pero solo 3 tipos de pizza. Entonces nose si en la funcion total_ahorrado_pedidos() tienes que calcular el ahorro segun el generador_pizzas o el generador_contenido_pizzas. ademas cada pedido tiene un descuento distinto, entonces no se si tengo que buscar un pedido que aparezcan las 9 pizzzas o si tengo que cambiar lafuncnion

**Comment by Cristobal-Hevia** [comment]
![Captura de pantalla 2024-10-16 141207](https://github.com/user-attachments/assets/b82f5192-549b-42dc-95a0-8bbe3de8925f)

**Comment by Vicente1824** [comment]
¡Hola @Cristobal-Hevia 🫡! Creo haber entendido bien tu duda, lo primero que tendrías que hacer es la consulta de `cliente_indeciso`, y usar su resultado como generador de pizzas para la consulta `total_ahorrado_pedidos`. Podría darse el caso de que, dado que ahora hay menos pizzas, algunos pedidos del generador de pedidos tienen pizzas de las que no sabes su precio, por lo que no podrías calcular cuánto se ahorró y deberías descartar estos. Igualmente esto se aborda en la issue #490. Espero que esto resuelva tu pregunta, sino, me comentas aquí mismo.

**Comment by Cristobal-Hevia** [comment]
¡Hola @Vicente1824! si lei el issue #490 pero mi problema es distinto, ya que mi generador_contenido_pedidos lo filtro segun el generador_pizzas, por lo que no hay pedidos con pizzas de las cual no sepa el precio. y usar el resultado como generador de pizzas tambien lo estoy aplicando y de igual manera no me funciona, nose que hacer.

**Comment by Cristobal-Hevia** [comment]
Ya intenté de todo y sigue sin funcionar, volví a descargar los datos y los test, incluso lo probe manualmente desde otro archivo y nada 😢 porfavor ayudenme.

**Comment by Cristobal-Hevia** [comment]
ya lo resolvi :)

**Comment by Vicente1824** [comment]
¡Hola @Cristobal-Hevia! Lamento no responder antes, justamente estaba trabajando en responderte, disculpas por no haberte podido ayudar. ¡Que bueno que hayas podido resolver tu duda!
