### ISSUE TITLE
Mago Super

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#567]
Hola, en el enunciado dice respecto al mago Super:
*"Además, podrá tener los mismos beneficios que tienen los Magizoólogo Docencios, Tareos e Híbridos por separado"*
Pero en los beneficios que detalla luego, no se incluye el hecho de que el Docencio al alimentar, aumenta 5pts la salud total de la criatura. Qué hago al respecto?

**Comment by matiasmasjuan** [comment]
Hola @dlmed !

Esta pregunta fue respondida en la ***Issue*** #337 .

Saludos! 😄

**Comment by dlmed** [comment]
Gracias! lo siento jeje

**Comment by matiasmasjuan** [comment]
Esta bien! 😅 

Solo que para próximas **ocaciones** **visita** el ***Compilado de Issues*** #239 ya que allí podrás encontrar la gran mayoría de tus posibles dudas, respondidas. En caso de que no encuentres tu duda, puedes utilizar el **buscador** con alguna palabra **clave** sobre el asunto de tu pregunta.

Mucho éxito con la tarea! 😄
