### ISSUE TITLE
Duda comunicación cliente servidor 

### ISSUE THREAD

**Issue by benito-tondreaux** [IIC2233/syllabus#567]
Una duda que tengo para realizar la tarea es como comunicar el cliente, su backend y el servidor. Mi pregunta es si puedo comunicarme directamente desde el backend al servidor por señales o tengo necesariamente que mandar una señal al cliente y el cliente le envíe un mensaje al servidor para poder comunicarse. 

Esto surgió debido a que necesito saber si el usuario ingresado ya está conectado al servidor o no. 

De antemano muchas graciaaas!!.

**Comment by jmwielandt** [comment]
Hola,

A grandes rasgos tu tarea consta de:

- Un programa servidor que recibe conexiones por socket.

- Un programa cliente que cuenta con:
  - Una arquitectura frontend-backend con interfaz gráfica. Deben comunicarse mediante señales.
  - Un socket en su backend que se conectará al servidor.


Toda la comunicación entre el cliente y el servidor debe ser a través de los sockets, no deben importar como módulo algún archivo común, tampoco pueden acceder mediante paths a algún archivo común. Piensa que tu cliente y servidor podrían estar en dos computadores diferentes.

En el enunciado está esta foto que lo muestra de manera más esquemática.

![image](https://user-images.githubusercontent.com/37153467/69894076-778b5c80-12f9-11ea-93b6-ee7efea5a1e5.png)

Saludos!
Dime si todavía tienes dudas!
