### ISSUE TITLE
Error Desconocido

### ISSUE THREAD

**Issue by anguiloff** [IIC2233/Syllabus#567]
Hola, cuando ejecuto mi juego, este me funciona correctamente durante 5/10 segundos y luego se cae. Me sale un mensaje que Python dejó de funcionar y luego este se cierra. Sin embargo, en la cmd no me está saliendo ningún tipo de error, por lo que no se que es lo que esta mal (asumo que es algo con los QThreads).
Le pedí a un amigo que lo corriera en Mac y le apareció el siguiente error:
"Python(11305, 0x7fffbfb463c0) malloc: *** error for object 0x10d117b98: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug"
Realmente no tengo ni idea que significa este error (creo que tiene algo que ver con c) y he estado buscando pero no he encontrado mucho..
Ojalá me puedan ayudar con este error y con como hacer para que estos errores se me impriman en mi computador, ya que si no me salen no puedo saber cual es mi error (probé con un código que subieron sobre eso, pero me sigue sin funcionar (Issue 555)).
Ya subí mi tarea ya que ha gente con problemas parecidos les han pedido que la suban.
Ojalá puedan ayudarme,
Saludos!!

**Comment by sebacruzd** [comment]
Hola,

Estás usando lo que sale en el issue #555?
Con eso podríamos tener más información del error.

**Comment by anguiloff** [comment]
Si, si lo estoy usando pero me sigue sin salir ningún tipo de error.


2017-06-03 13:11 GMT-04:00 Sebastián Cruz Dides <notifications@github.com>:

**Comment by hanavarrete** [comment]
Podrías intentar revisar por partes y especificarnos más donde está el error?. Hemos revisado código pero en ocasiones muy particulares, pero por motivos de tiempo (y que sea justo para todos) no podemos estar revisando todos los repos e ir buscándoles el error. Estaré encantado de ayudarte si es que puedes acotar más el rango de posibles errores. Saludos!

**Comment by anguiloff** [comment]
La verdad es que no tengo ni idea donde está el error, ya que no me sale la línea de código donde este se genera. Lo que si puedo decir es que me comenzó a aparecer luego de que hiciera que el campeón enemigo mirara y persiguiera a mi campeón (por lo que creo que el problema está en implementar QThreads, quizás en que los dos personajes quieren ingresar a la misma info al mismo tiempo o algo así).
Lo puse en el enunciado anterior, pero o lo adjunte bien que estoy usando el código subido en la issue #555 pero este tampoco me está entregando ningún tipo de error al momento de fallar mi programa.
Espero que esto haya acotado en algo el problema.
Saludos!!

**Comment by stephichau** [comment]
@anguiloff revisé tu código y te recomiendo fuertemente modelar mejor tu programa. Dicho esto, para mover los labels de la ventana principal, debes hacerlo mediante señales (tal como se muestra en el ejemplo que subió @hanavarrete) :)
