### ISSUE TITLE
Capacidad máxima de Nebiland y llegadas

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#567]
¿Qué ocurre si un grupo llega cuando el parque ya está en su capacidad máxima o si su número de integrantes hará que se sobrepase la capacidad máxima? Dicho grupo, ¿espera fuera del parque a que se liberen los cupos suficientes o simplemente se va?

¿Puedo simplemente asumir que se van por la traumática experiencia de que Nebiland les rompió sus sueños y corazones?

**Comment by yoavnavon** [comment]
Hola! Como no está especificado, queda bajo tu criterio. Menciona tu decisión en el ReadMe. Saludos!
