### ISSUE TITLE
problema con la libreria beautifultable

### ISSUE THREAD

**Issue by stephenwpugh** [IIC2233/syllabus#567]
Hola! ayer descargue la librería beautifultable para ordenar las tablas, el cual no tuvo ningun problema, pero hoy al abrir VSCode en la carpeta de la Tarea me tiró el error `ModuleNotFoundError`, que ocurre cuando no está descargada la librería. Ya intenté desinstalandolo e instalandolo denuevo con `pip` y no pasa nada:( Creo que quizás lo instalé en la carpeta de la T01 en vez del sistema, pero no encontré en internet cómo saber si puede ser eso o como arreglarlo

**Comment by aaossa** [comment]
Hola @stephenwpugh , podrían ser muchas cosas... ¿Cómo instalaste por primera vez `beautifultable`? ¿Cómo se llama el archivo que estás ejecutando (si se llama como la librería, eso explicaría el posible error)? ¿Probaste instalando la librería desde el editor o desde la consola del sistema?
