### ISSUE TITLE
Un par de preguntas sobre el punto 3 y el 4

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#568]
Hola! Tengo un par de dudas de lo que debo hacer en los puntos 3 y 4. 

1: Puedo tener el codigo de la interfaz en un archivo separado, llamado "main.py", en la raiz de la carpeta? (el cliente abriria una distinta?)

2: Como hago que se actualizen todos los clientes?

3: Puedo guardar los datos de los textos de los usuarios en un archivo? Y similarmente, puedo guardar los estados de cuantos usuarios hay en una sala etc ahi? 

4: Una vez que hay comunicacion entre el cliente y el servidor, como puedo integrarlo a la interfaz?

**Comment by jmwielandt** [comment]
Hola,

1. Te recomiendo mirar la issue #567, creo que respondí ahí tu duda hace un rato, dime si te quedan dudas.

2. Esperamos que ustedes creen una forma de conseguirlo, pero como hint: _es trabajo del servidor._

3. ¿Por qué quieres hacer eso?

4. También lo respondo en parte en la issue que cito. Dime si te quedan dudas.

Saludos~
