### ISSUE TITLE
Si cierro y abro mi cliente no me deja iniciar sesion

### ISSUE THREAD

**Issue by videvidts** [IIC2233/syllabus#568]
Me pasa que si corro el servidor y luego el cliente puedo iniciar sesion perfectamente, sin embargo, si vuelvo a correr el cliente (sin volver a correr el servidor) no me deja iniciar sesion pero no arroja ningun error (llama cerrar_sesion de la exception que pondré abajo)

    def escuchar_cliente_thread(self, client_socket):

        while True:
            try:
                # Primero recibimos los 4 bytes del largo
                response_bytes_length = client_socket.recv(4)
                # Los decodificamos
                response_length = int.from_bytes(response_bytes_length,
                                                 byteorder="big")
                response = bytearray()
                while len(response) < response_length:
                    response += client_socket.recv(256)
                response = response.decode()

                if len(response) != 0:
                    decoded = json.loads(response)
                    self.manejar_comando(decoded, client_socket)

            except ConnectionResetError: -->ESTA EXCEPTION
                decoded_message = {"status": "cerrar_sesion"}
                self.manejar_comando(decoded_message, client_socket)
                break

**Comment by jeschuwirth** [comment]
Hola!

Estas creando un thread con la función "escuchar_cliente_thread()" para cada cliente o tienes una para todos, puede que tu servidor este escuchando al primer cliente en llegar y luego tiene problemas para el resto.

**Comment by videvidts** [comment]
Tengo uno para todos los clientes!

**Comment by videvidts** [comment]
muchas gracias!
