### ISSUE TITLE
setMouseTracking

### ISSUE THREAD

**Issue by aSPCA** [IIC2233/Syllabus#568]
Cuando abro la ventana de juego, el MainWidget puede seguir bien el movimiento de mi personaje, pero solamente si es que presiono sobre la pantalla, aplique setMouseTracking sobre la Main y la Gui con el fin de que siguiera el mouse, pero no me funciona :(

help

**Comment by hanavarrete** [comment]
Tal vez tienes un label que está por encima de esas cosas y no le activaste el setMouseTracking ahí. Podrías intentar hacer setmouseTracking en todos los labels (por el momento) para revisar si ese es el problema? Intenta eso y dime si te funcionó. Saludos!

**Comment by aSPCA** [comment]
Solucionado!, lo tenia que aplicar sobre el label que tenia la imagen de fondo

Gracias!

salu2

**Comment by hanavarrete** [comment]
De nada! (No te olvides de sacar el setmousetracking de las partes innecesarias ahora)
