### ISSUE TITLE
Tablero en ventana de juego

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#568]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Es necesario que el juego siga esta lógica de "tablero"? o puedo spawnear los objetos (incluidos los obstáculos) en posiciones aleatorias "continuas" (mientras no choquen, claro está)
![image](https://user-images.githubusercontent.com/66154723/120267006-15564380-c271-11eb-96f1-1cf052936946.png)

**Comment by valerianazal** [comment]
Hola @fernandosmither ! Efectivamente sí pueden aparecer objetos en posiciones aleatorias contiguas, siempre y cuando, como bien dices, no colisionen entre ellos. Sin embargo, recuerda considerar que **"no pueden haber obstáculos posicionados de manera contigua"**, como se especifica en el enunciado. 
Espero haber resuelto tu duda ⭐

**Comment by fernandosmither** [comment]
> Hola @fernandosmither ! Efectivamente sí pueden aparecer objetos en posiciones aleatorias contiguas, siempre y cuando, como bien dices, no colisionen entre ellos. Sin embargo, recuerda considerar que **"no pueden haber obstáculos posicionados de manera contigua"**, como se especifica en el enunciado.
> Espero haber resuelto tu duda ⭐

A propósito de lo mismo, cuánto sería la separación mínima entre obstáculo y obstáculo?

**Comment by valerianazal** [comment]
Depende de cómo armes tu tablero de juego. Debe ser espacio suficiente para que el personaje pueda transitar entre obstáculos.
Quedo atenta a cualquier duda 😄
