### ISSUE TITLE
Solicitud aumento de plazo de entrega de tarea

### ISSUE THREAD

**Issue by alejita97** [IIC2233/syllabus#568]
Estimados compañeros:
Abro esta issue con la finalidad de proponer un cambio de fecha de entrega de la tarea.
Felices fiestas patrias :) .

**Comment by cperez20** [comment]
Apoyo el motivo de la issue, producto de la cantidad de evaluaciones que muchos tenemos durante la semana, seria de mucha ayuda un plazo extra para la tarea :D

**Comment by Javi-N** [comment]
Sí!! Me sumo, esta semana está muy intensa para muchos debido a las distintas evaluaciones, sería una gran ayuda si se pudiera extender el plazo :)

**Comment by Hanfud4** [comment]
+1 a los comentarios de arriba! Creo que el tema de la semana de receso influyó mucho en que se cargaran las evaluaciones en los mismos días así que un poco más de plazo estaría excelente uwu

**Comment by aayale** [comment]
Sii porfaaa, esta semana va a estar brigido con pruebas y no alcanza el tiempo para terminar la tarea:(

**Comment by Constanzape** [comment]
Me sumo a los comentarios! Al parecer a causa de la semana de descanso muchas actividades se corrieron para esta semana, por lo que hay mucha carga académica de otros ramos también

**Comment by jpvergaralb** [comment]
Apoyo mucho. Se acumularon muchas evaluaciones entre la semana pasada y esta y no pude dedicarle lo que me hubiese gustado a la tarea (mi energia es finita ;[ ).

**Comment by JeibiCL** [comment]
Me sumo a la solicitud. Entre discretas, optimizacion y pruebas de calculo 3 y EDO. La semana está demasiado pesada.
Por favor ;(

**Comment by nico-sv** [comment]
Me sumo a los comentarios de arriba, la carga académica de estos últimos días ha sido horrible:(

P.D: contesten la ECA

**Comment by Gustav2000** [comment]
Lo mismo digo, esta semana siento que ha estado particularmente más pesada de lo normal (en mi caso particular al menos).

**Comment by difischer** [comment]
Hola, a pesar de que yo ya casi terminé la tarea y solo estoy arreglando detalles, he gastado hasta aestas alturas cerca de 20 horas en la realización. Por lo que me sumo a la petición de mis compañeros de que se de más tiempo, considerando una división igual de horas en los días, son más de 10 horas a la semana que habría que dedicar en la tarea.
Saludos!

**Comment by enriquerussi** [comment]
Hola, me sumo a los comentarios anteriores, la carga académica esta semana antes de vacaciones esta muy pesada. Todos los primeros trabajos, talleres, entregas o pruebas de todos los ramos caen en los mismo 5 días. Por favor, den más plazo.

**Comment by nikrebs99** [comment]
Apoyo, mis ramos más pesados han decidido hacer evaluaciones esta semana, por lo que no he podido dedicar el tiempo necesario a la tarea para entregar un programa funcional.

**Comment by allisonaguilar** [comment]
Hola, me sumo a los comentarios! esta semana tengo evaluaciones todos los días y no me queda tiempo para terminar la tarea :(

**Comment by Natydlb** [comment]
Hola! Yo también me sumo, esta semana se me ha hecho terrible entre pruebas y tareas :(

**Comment by vaguirrevergara** [comment]
Hola! Me sumo también a esta petición, tengo dos tareas y una interrogación esta semana

**Comment by martin-santiago** [comment]
+1 tengo 3 entregas esta semana :( con almenos 1 día más estaría bacan

**Comment by Krmn390** [comment]
> Estimados compañeros:
> Abro esta issue con la finalidad de proponer un cambio de fecha de entrega de la tarea.
> Felices fiestas patrias :) .

Me sumo, me sentiría mucho más tranquila si nos dan aunque sea un dia mas de plazo.

**Comment by fddelabarra** [comment]
Hola, me gusta la idea tambien, esta semana se me juntaron 5 tareas :'c por no decir 6  ya que 2 son de la misma materia :( seria una gran ayuda 😭😭

**Comment by DanoUC** [comment]
Hola, por favor consideren aumentar el plazo de la tarea :c a la mayoria de los ramos les dio por tirar evaluaciones para estos 3 dias u.u

**Comment by juan-palma-1** [comment]
Me sumo a la petición (la ECA explotará en sus estadísticas), al parecer la semana de receso junto muchas evaluaciones. tengo 3 interrogaciones 2 tareas para esta semana.

PD: Change da world ~ my final message. Goodbye

**Comment by catalina-arcila** [comment]
Me sumo a la petición, todos los ramos consideraron la semana de receso y nos pusieron todas las cosas esta semana:(

**Comment by pabloist** [comment]
Apoyo la moción :( estamos llenísimos de pruebas estos 3 días

**Comment by bxarnaiz** [comment]
Apoyo! Tengo que entregar otras cosas esta semana y en el finde no alcancé a terminar la tarea de progra y no quiero entregarla a medias sabiendo que puedo hacerla bien con un poco más de plazo

**Comment by mariofloresm** [comment]
Apoyo la moción

**Comment by danvillablanca** [comment]
Me sumo a la petición, a muchos profesores les gustó la idea de dejar las evaluaciones para esta semana jajaja

**Comment by sconchac** [comment]
También me sumo a los comentarios de arriba, se juntaron muchas evaluaciones esta semana 😢

**Comment by dani-sschlack** [comment]
Yo también me sumo a la moción, la verdad es que de aquí hasta el miércoles tengo una prueba, 3 tareas (contando la de progra), un control y leer los contenidos de progra (+ la autoevaluación)xd. 

![image](https://user-images.githubusercontent.com/69522104/93120948-82518b00-f69a-11ea-998d-61ef2e13ecce.png)

**Comment by vicentesalazar** [comment]
Apoyo totalmente la petición!

**Comment by thiaaare-sp** [comment]
Comparto la petición de mis compañeros, aún me faltan varias cosas de la tarea y debo estudiar para una interrogación y control que tendré el mismo miércoles. Un par de días más en la entrega ayudaría bastante con la carga de la semana:(

**Comment by daniela-carreno** [comment]
Me sumo a la petición!, todos los ramos consideraron la semana de receso para poner las evaluaciones esta semana 😢 , por lo que darnos un par de días extra para la entrega nos ayudaría bastante

**Comment by pablofaundez** [comment]
Me sumo a la petición! Esta es una de 4 entregas que tengo en estos días :(

**Comment by sbmirandap** [comment]
Me sumo! Esta semana tengo dos pruebas más dos tareas aparte de progra y una entrega y todo eso en 3 dias, le faltan horas a mi dia:(

**Comment by capitanbulla** [comment]
Me sumo a la petición ! Todos los ramos decidieron poner entregas y pruebas esta semana ):, tengo 3 entregas y 2 pruebas

**Comment by magdalenarojas** [comment]
Me sumo a la petición! no he logrado terminar la tarea porque se me juntaron muchas cosas para estos días, un par de días mas me ayudarian muchisimo

**Comment by stephenwpugh** [comment]
me sumooo, donde firmo! para hacer una buena tarea ganas sobran, solo faltan un par de días más dadas las 1001 cosas que piden entregar antes del receso:)))

**Comment by sbersani69** [comment]
Me sumo, esta súper pesada la semana ayudaría bastante un poco más de plazo 
Así se puede dormir más de 4 horas 🥴

**Comment by jorgetf-desing** [comment]
Hola, me sumo a la moción. La verdad es que esta larguísima la tarea, sumado a que se junta con muchas cosas de otros ramos. He invertido infinito tiempo y aun no estoy ni cerca de terminarla

**Comment by nitramavlis** [comment]
Me sumo a lo que piden mis compañeros  y se agradecería muchísimo un poco mas tiempo

**Comment by amorande1** [comment]
Me sumo, tengo la semana más cargada que he tenido en la u (y voy en 4to) con un día más alcanzo.

**Comment by nataliameza** [comment]
Hola! Me sumo a la petición, me da lata no poder entregar una buena tarea solo por falta de tiempo :(

**Comment by sebastianmaureira** [comment]
Me sumo a la petición

**Comment by AlexituationUC** [comment]
me sumo, he tenido que faltar a algunas clases para avanzar con todas las tareas que me han puesto :c

**Comment by ceitax** [comment]
Me sumo completamente a esto, la verdad con todos los ramos tengo ies y tareas, estoy colapsadisimo :((((UnU

**Comment by riadeane** [comment]
Hola! Me sumo a la petición uwu

**Comment by Montruki** [comment]
Me sumo a la petición, estoy colapsado en todos los ramos y a pesar de todo el tiempo que le he dedicado aun no termino la tarea. 😢

**Comment by pedrobeckerj** [comment]
Al menos que se pueda entregar el diagrama con el README por favor!!

**Comment by NIET00** [comment]
Me sumo a la petición. He dedicado muchísimas horas al trabajo, sin embargo siento que todavía me falta por terminar.

**Comment by isidorabecker** [comment]
Sii, me sumo, igual he estado muchas horas en la tarea y aún me falta mucho por hacer. Por favor considerenlo

**Comment by Bea2000** [comment]
Me sumo! La tarea ha tomado muchas horas y líneas de código y con las evaluaciones de otros ramos no da para entregar un buen trabajo.

**Comment by andresrg758** [comment]
Me sumo tambien! Al final todos los ramos para dejarnos descansar la semana despues del 18, nos llenaron la semana antes. No le he podido dedicar el tiempo que quiero a la tarea porque no es el unico ramo que tengo.

**Comment by aurzuav** [comment]
apoyooooo

**Comment by rodrigopg908** [comment]
Me sumo a la petición,  esta muy cargada la semana y hay que intentar rendir en todos los ramos, un poquito mas de plazo seria genial🥺

**Comment by mojojitos** [comment]
me sumo a la petición, esta semana la tengo super cargada :c

**Comment by mauriquan** [comment]
Me sumo a la petición

**Comment by ivannateresa** [comment]
Me sumoooo, esta semana tengo pruebas y  tareas que entregar :(

**Comment by kalarconvl** [comment]
Me sumo, de esta forma podría entregar la tarea mucho más completa

**Comment by mt-garcia** [comment]
Yo también me sumo a esta petición!

**Comment by jchamorrou** [comment]
plazo += par_de_dias

**Comment by alejita97** [comment]
@jchamorrou  y lo ingresas a un while True jejejeje

**Comment by camilabarrera26** [comment]
Me sumo a la peticion!  ha sido una semana bombardeada para todos :(

**Comment by matiasfernandez1** [comment]
Me sumo también a la petición.

**Comment by aiarias** [comment]
Me sumo también a la petición!! Porfavorrr

**Comment by Zion54** [comment]
También me sumo a la petición!!. Por favor :c

**Comment by ffelbol** [comment]
Me sumo, la semana esta llena de cosas :(

**Comment by JoseAlvarez123** [comment]
Me sumo tambien, ha estado demasiado pesada esta semada. Aiuda pofavoh :C

**Comment by agusuazo** [comment]
También me sumo, por favor :(

**Comment by sasilva4** [comment]
También me sumo

**Comment by lily416** [comment]
Como Equipo Docente hemos leído todos sus comentarios y hemos evaluado la situación. En breve les enviaremos un aviso oficial dando la información, por favor sean pacientes 🙇‍♀️🙇‍♂️.
 
Recuerde que las _issues_ del Syllabus son un medio para hacer preguntas con respecto a las tareas y los contenidos del curso 👀. Por lo mismo, si tienen algún problema o necesitan ayuda por parte del equipo docente, les pedimos que nos escriban al correo oficial del curso (iic2233@ing.puc.cl), al ayudante de bienestar (bienestar.iic2233@ing.puc.cl) o incluso a sus profesores, ya que nos permite canalizar de manera directa y personal sus situaciones y/o problemas personales 📝😉.
