### ISSUE TITLE
Aparición de carabineros

### ISSUE THREAD

**Issue by depstein26** [IIC2233/Syllabus#568]
Hola, en el enunciado dice que un carabinero de tipo Hyde o Jekyll aparece con igual probabilidad, pero en los carabineros hay un Hyde más que Jekyll, con eso, no bastaría hacer un choice de un carabinero entre todos los carabineros, sino que habría que elegir un tipo y después un carabinero de ese tipo al azar. Es así? O podemos hacerlo eligiendo un carabinero al azar si igual las probabilidades son muy similares. 0,53 vs 0,47. Gracias de antemano!

**Comment by fdominguezclaro** [comment]
Hola!
Primero saca una probabilidad entre las dos personalidades y luego eliges a uno de dicha personalidad.
Saludos!!
