### ISSUE TITLE
Duda de materia, Properties de una clase dentro de un diccionario

### ISSUE THREAD

**Issue by FJavierOss** [IIC2233/Syllabus#568]
Supongamos que tengo una clase perro que cumple con el siguiente codigo.

```python
class Perro:
    def __init__(self):
        self._ganas_dormir = 0

    @property
    def ganas_dormir(self):
        return self._ganas_dormir

    @ganas_dormir.setter
    def ganas_dormir(self, valor):
        self._ganas_dormir = valor

    @ganas_dormir.getter
        return self._ganas_dormir
```

Teniendo en cuenta este codigo quisiera guardar la funcion ganas_dormir en un diccionario con todas sus cualidades de properties.
perro = Perro()
dict1 = {"funcion":perro.ganas_dormir}

Ahora aqui viene la duda,
cuando hago 
```python
dict1.get("funcion")
```

me retorna el valor de _ganas_dormir
Pero en cambio si trato de asignarle valor no me deja, o sea en codigo
```python
dict1.get("funcion") += 1
dict1.get("funcion")
> 1

perro._ganas_dormir

> 0
```

Lo que quiero decir que me cambia el valor localmente en el dictionario pero no en el perro mismo en cuestion. ¿Como puedo hacer para modificar el atributo del perro desde el diccionario sin tener que recurrir a un metodo extra (como def modificar_ganas(self,valor): >>> self._ganas_dormir = valor y en el diccionario tener algo como dict2= {"funcion2":perro.modificar_ganas})? 
Todo esto en pos de tener un codigo mas limpio y conciso, que en caso particular podría servirme para la tarea aunq no es estrictamente necesario que lo haga asi.

**Comment by FJavierOss** [comment]
Para una instancia de una clase "x" mi idea es pasar un diccionario a una instancia de la clase "y", con metodos de "x" como elementos del diccionario donde el procesos de cambio de los atributos es desde "x" y no desde "y", "y" solo llamaria a las funciones y les pasaria valores. Basicamente es para evitar referencias circulares. Ahi se entiende mejor?

**Comment by jfbahamondes** [comment]
No encontré una forma de hacerlo mediante un diccionario ya que cuando haces  `dict1 = {"funcion":perro.ganas_dormir}` no le estás pasando un atributo sino un valor (en este caso un int) pero existen diversas formas de modelar sin referenncias circulares. En la issue #540 se habla de modelación circular y puedes preguntar y revisar ahí cualquier cosa.

Saludos.

**Comment by FJavierOss** [comment]
Lo vere, gracias

**Comment by nebil** [comment]
Vengo a reabrir este _issue_, porque puede que exista una forma de lograr lo que quieres hacer, @FJavierOss.

Bueno, retomando tu ejemplo, digamos que tenemos una (minimalista) clase `Dog`.

```python
class Dog:

    def __init__(self, name):
        self.name = name

    @property
    def name(self):
        print('Getting!')
        return self._name

    @name.setter
    def name(self, value):
        print('Setting!')
        if len(value) != 9:
            raise ValueError(f'Pero qué mal nombre –– "{value}" no es aceptable.')
        self._name = value
```

Bien. Ahora fabriquemos una instancia de esta clase.

```python
>>> doggo = Dog('Liverpool')
Setting!
```

Pidamos su nombre.

```python
>>> doggo.name
Getting!
'Liverpool'
```

Todo en orden. Ahora tratemos de asignar un nombre inválido.

```python
>>> doggo.name = 'Real Madrid'
Setting!
ValueError: Pero qué mal nombre –– "Real Madrid" no es aceptable.
```

Muy bien. Veamos, entonces, cómo podemos implementar lo del diccionario.

```python
>>> doggodict = {'name': doggo.name}
Getting!
```

Miremos qué hay dentro del diccionario.

```python
>>> doggodict
{'name': 'Liverpool'}
```

Como bien @jfbahamondes mencionó anteriormente, `doggo.name` **no entrega una referencia a la función**, sino simplemente el valor del _getter_. Y si lo piensas, esto es natural que ocurra ya que, a fin de cuentas, esto es lo que el _getter_ del _property_ (_i.e._ `doggo.name`) devuelve.
Bueno, no encontré resultados en Google acerca de cómo implementar esto. Pero una posible solución es utilizando la función _built-in_ [`setattr`](https://docs.python.org/3/library/functions.html#setattr). No estoy seguro si es lo más _pythonic_ que existe, pero es lo que puedo ofrecer por ahora. Veamos un ejemplo.

```python
>>> setattr(doggo, 'name', 'Palestino')
Setting!
>>> doggo.name
Getting!
'Palestino'
```

Funciona. Entonces, ahora podríamos crear un diccionario con una función [λ](https://en.wikipedia.org/wiki/Lambda) —claro, con esto me refiero a una _función lambda_.

```python
>>> doggolambdict = {'name': lambda value: setattr(doggo, 'name', value)}
>>> doggolambdict
{'name': <function __main__.<lambda>(value)>}
```

Como puedes notar, ahora no guarda un valor, sino nuestro λ. Bueno, probemos nuestro flamante _setter_.

```python
>>> doggolambdict['name']('Liverpool')
Setting!
```

Esto debería modificar nuestra instancia.

```python
>>> doggo.name
Getting!
'Liverpool'
```

Y efectivamente lo hace. :grinning:
Sólo para estar seguros, probemos con otro caso.

```python
>>> doggolambdict['name']('Audax Italiano')
Setting!
ValueError: Pero qué mal nombre –– "Audax Italiano" no es aceptable.
```

También funciona. Ojo: debes llamarlo como si fuera una función. Por ejemplo, mira esto.

```python
>>> doggolambdict['name'] = 'Unión Española'
>>> doggolambdict
{'name': 'Unión Española'}
```

Eso no servirá, ya que simplemente le asignará ese _string_ como valor al diccionario. Por lo tanto, no cumplirá con el objetivo de modificar el nombre de nuestro doggo. :dog:

---

Un problema con esto es que, aparentemente, ya no es posible acceder al valor del atributo desde el diccionario. Luego, habría que extender nuestro λ. A continuación, mostraré una posible forma de lograrlo.

```python
>>> doggosuperlambdict = {'name': lambda value=None: getattr(doggo, 'name') if value is None else setattr(doggo, 'name', value)}
>>> doggosuperlambdict['name']('Palestino')
Setting!
>>> doggosuperlambdict['name']()
Getting!
'Palestino'
```

Funciona, pero no me parece tan legible. Podemos también ofrecer una alternativa más general, puesto que permite entregar el nombre del atributo. Además, la escribiré en más líneas.

```python
def get_or_set(obj, attr):
    def wrapper(value=None):
        if value is None:
            return getattr(obj, attr)
        setattr(obj, attr, value)
    return wrapper
```

Luego, con esto podemos obtener una funcionalidad equivalente para nuestro diccionario.

```python
>>> doggosuperfuncdict = {'name': get_or_set(doggo, 'name')}
>>> doggosuperfuncdict['name']()
Getting!
'Palestino'
```

En fin, podría estar todo el día escribiendo alternativas; sin embargo, pienso que se entiende el punto. (Además, en algún momento, tengo que almorzar.) En cualquier caso, todo esto nos permitió revisar algunos contenidos del curso. :snake:

Avísame cómo te va con esto. Estaré atento a tus comentarios, doggo.

**Comment by jfbahamondes** [comment]
@nebil  Después de todo sería como hacer algo así?, que básicamente le queremos pasar una función y no un atributo  al diccionario: 
```  
#definimos dentro de la clase Dog
def settear_nombre(self, nombre):
    name = nombre

doggolambdict = {'name':doggo.settear_nombre}
doggolambdict['name']('Liverpool')
print(doggo.name)

>>>>Liverpool
```
De todas formas no logro encontrarle el sentido a trabajar con un diccionario así 😢.

**Comment by nebil** [comment]
Sí, @jfbahamondes. La función que definiste, según lo que entendí, es la solución que @FJavierOss terminó implementando. Efectivamente, es equivalente en el hecho que puedes modificar el atributo. Sin embargo, para conseguir el _getter_, tendrías que modificar tu función —o bien, agregar otra llave al diccionario. Además, utilizar `lambda` con `getattr/setattr` te ahorra escribir esta función, lo que deja tu clase `Dog` más limpia, sin código repetido.

Por otra parte, si esta funcionalidad se quisiera implementar para varios atributos, la función `get_or_set` —que definí arriba, en mi respuesta anterior— te permite lograr eso sin mucho trabajo adicional. Incluso, quizá se podría hacer algo con metaclases para agregar métodos de forma automática a partir de los _properties_ definidos dentro de la clase `Dog`. Porque con Python… _the sky’s the limit_. :rainbow:

Ahora bien, comparto contigo en que tampoco tengo claro si es que trabajar así es la forma óptima para evitar el modelamiento circular. Para eso, tendría que tener un mayor contexto acerca del problema que se busca resolver. De todas formas, me pareció interesante ofrecer una respuesta a la pregunta original. :nerd_face:
