### ISSUE TITLE
Rol  cliente - frontend 

### ISSUE THREAD

**Issue by jitorcas** [IIC2233/syllabus#569]
Hola! 
Avanzando en mi tarea, simplifiqué un poco las señales entre cliente - frontend, pero me surgió una duda: ¿Estaría correcto tener solo una señal entre cliente - frontend? la cual envía un dict con todo lo que se debe ejecutar en el frontend. Hasta el momento no me ha generado errores, y todo lo que ingresa el usuario pasa por el cliente y luego se envía al servidor y desde el servidor va directo al cliente, se limpia y se envía al frontend.

**Comment by gatochico** [comment]
Hola!!

Si puedes hacer eso, siempre y cuando te preocupes que toda validación ocurra solo en el cliente y una vez ocurra esto, recien se envie la señal con el cambio a ejecutar en frontend 😎 Otra cosa a fijarte si sigues ese camino es en el largo de líneas de cada módulo (es muy probable que te quede una función bastante grande!). 

Éxito 💻 🖱
