### ISSUE TITLE
Cuantas veces Quick Devil llama a los policías?

### ISSUE THREAD

**Issue by depstein26** [IIC2233/Syllabus#569]
Creo que el título es bastante auto descriptivo. No sale explícito en el enunciado, por lo que lo puede llamar una vez cada día?

**Comment by fdominguezclaro** [comment]
Hola!
Sale en el enunciado en la sección de eventos no programados. 
Saludos

**Comment by cilopez** [comment]
Como la tasa es por días sería raro que el próximo evento ocurra en el mismo día, ya que el valor obtenido sería  menor a 1, en ese caso considera que la lluvia es el día siguiente (_es decir sólo se llama una vez por día_)

**Comment by depstein26** [comment]
Gracias!

**Comment by inmadariaga** [comment]
@fdominguezclaro los días que llama distribuyen exponencial (el parámetro es días no minutos ni horas)?
