### ISSUE TITLE
Colisión personaje con Gorgory

### ISSUE THREAD

**Issue by colobos** [IIC2233/syllabus#569]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Uno va a la comisaria virtual (pierde el juego), siempre y cuando el jefe Gorgory alcance al jugador?, es decir se encuentre justo en el mismo (x, y) que el personaje principal?, o basta con que se intersecten en algún momento?. En este sentido, si fuese lo primero, solamente se perdería al quedarse quieto uno?
Saludos, y de antemano, muchas gracias por su respuesta!!

**Comment by valerianazal** [comment]
Hola @colobos ! Como se especifica en el enunciado, el jugador pierde cuando el personaje **colisiona** con el Jefe Gorgory, no necesariamente estarán en la misma posición cuando eso pase. 
Espero haber resuelto tu duda! Quedo atenta ✨

**Comment by colobos** [comment]
ok, gracias!!
