### ISSUE TITLE
Cambio de clase de una instancia

### ISSUE THREAD

**Issue by Javier16606035** [IIC2233/syllabus#569]
Hola, tenia una duda al momento de cambiar una instancia de clase. Por ejemplo:

```python
class A:
    def __init__(self, numero):
        self.atributo = numero

class B:
    def __init__(self, numero):
        self.atributo = numero 


def cambio_clase(objeto):
    objeto = B(objeto.atributo)

obj = A(2)
print(type(obj))
cambio_clase(obj)
print(type(obj))
```
El output del código anterior es:
`<class '__main__.A'>`
`<class '__main__.A'>`

Por lo tanto, la instancia obj mantiene la primera clase asignada, a pesar de haberla pasado por la función cambio_clase(). Al abrir el debugger, se puede ver que la variable local si cambia de clase dentro de la función, pero al salir de esta vuelve a su clase original. 

La solución que encontré fue esta:
```python
class A:
    def __init__(self, numero):
        self.atributo = numero


class B:
    def __init__(self, numero):
        self.atributo = numero 


def cambio_clase(objeto):
    objeto = B(objeto.atributo)
    return objeto

obj = A(2)
print(type(obj))
obj = cambio_clase(obj)
print(type(obj))
``` 
Pero quiero saber si es posible hacerlo de la primera forma (ya que, temo que la segunda forma pueda interferir con el funcionamiento de mi código). Además, necesito que el cambio de clase sea hecho por una función (o sea, hacer obj = B(obj.atributo) no me sirve).

Gracias!

**Comment by Dnpoblete** [comment]
Hola @Javier16606035, como bien mencionas esto no se puede hacer de la primera forma, ya que al tratar de modificar tu instancia dentro de la función, el cambio que realizas solo va a ser dentro de esa función, ya que en ningún momento retornas nada fuera de esta, para comunicarle al resto del código que existió ese cambio. Así que lamentablemente no se puede hacer el cambio que tu quieres dentro de la función sin retornar nada y que eso cambie en el resto del código.
Adicionalmente, me gustaría saber porqué dices que no te funciona lo que quieres hacer con el segundo método, y tampoco veo razón por la cual esto podría interferir con el funcionamiento de tu código, ya que hace exactamente lo que necesitas, solo que se agrega un pedazo más a una línea de código.

Quedo atenta a tus comentarios! :smile:

**Comment by Javier16606035** [comment]
Muchas gracias por responder! Al final me di cuenta que la segunda forma si me servia, y que tampoco afectaba a mi programa. Tenía miedo, ya que la variable que quería modificar era ocupada por todo el programa, entonces pensaba que si la modificaba, alguna parte de este iba a dejar de funcionar. Sin embargo, lo anterior no paso!. 

Nuevamente, muchas gracias! 👌

**Comment by Dnpoblete** [comment]
Que buena que hayas podido usar la segunda forma y te sirviera para lo que querias! :smile:
