### ISSUE TITLE
QPushButton

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#569]
Hola!
Como siempre estoy teniendo problemas con esto del PyQt5. No sé porqué los botones que pongo en el widget de mi juego no son apretables (cuando les hago click no funcionan D": ), los conecté a una función que   imprime "puse pausa" (por ejemplo).
 Es raro porque en otro widget tengo dos botones para seleccionar al campeón y todo bien, puse exactamente las mismas líneas y no me funciona. Tengo algo como esto para el botón que no lleva icono:
self.button = QtWidgets.QPushButton("botón", self)
self.button.setGeometry(dx, dy, a, b)
self.button.resize(self.return_button.sizeHint())
self.button.clicked.connect(funcion)
self.button.show()

Y para el que lleva icono, tengo lo mismo pero con setIcon() y todo el tema. 
 Alguien me podría ayudar?
Saludos!

**Comment by acrojas2** [comment]
@hanavarrete, @iqacevedo , @Hernan4444 los etiqueto porque parece que uds están contestando las issues de esta tarea.

**Comment by Hernan4444** [comment]
@acrojas2 puedes especificar con que son son apretables, están desabilitados acaso? o se apretan pero no ejecutan nada? Por otro lado, verificaste si las lineas donde realizas la conexión de un boton a un funcion si se ejecutan (poner un print antes del connect). Si puedes explicar mas el contexto de tu problema (que widget falla, que clase hereda, donde lo llamas) podremos encontrar donde puede estar el error.

**Comment by acrojas2** [comment]
Mi definición de botón apretable: Me refiero a que por ejemplo tengo botones conectados a nada y se clickea no pasa nada, pero en el botón se nota, sin embargo se aprieta el botón (como que se hace el gesto que se apretó pero no pasa nada y está bien porque no lo he conectado a ninguna función o la función solo imprime "apreté el botón X") .
Mi definición de botón no apretable: No pasa absolutamente nada cuando clickeo sobre el botón. Ni se inmuta a pesar de estar conectado a funciones que dicen "apreté X boton".
Acabo de poner el print que me sugeriste y no funciona. 
El Widget que falla es el que yo le llamo GameWindow y hereda de QWidget, este QWidget se llama desde la MainWindow por medio de una  funcion que settea el centralWidget.

**Comment by Hernan4444** [comment]
> Acabo de poner el print que me sugeriste y no funciona.

Imprime pero no funciona el boton o nunca se imprime eso y significa que nunca se llega a esa parte del código?

**Comment by acrojas2** [comment]
@Hernan4444 tal cual !

**Comment by hanavarrete** [comment]
@acrojas2  tampoco me quedó claro jajaja. Imprime o no? 😆

**Comment by acrojas2** [comment]
esto está pasando:
<img width="522" alt="captura de pantalla 2017-06-03 a las 4 02 21 p m" src="https://cloud.githubusercontent.com/assets/26121354/26756676/36bbba1a-4876-11e7-96e9-ea3177bde7c3.png">
y el botón lo conecto como mencioné anteriormente.
<img width="311" alt="captura de pantalla 2017-06-03 a las 4 02 41 p m" src="https://cloud.githubusercontent.com/assets/26121354/26756683/502bb52c-4876-11e7-84d2-8bf83a118343.png">
(Ojalá no haya pecado en subir este pedacito, según yo no muestra nada, lo puse solo para que entiendan mejor como estoy conectando)
self.pause es un metodo que debería imprimir "me apretaron" cuando se clickea el botón y eso es lo que no está pasando. 
saludos!

**Comment by stephichau** [comment]
@acrojas2 haz: self.pause_button :)

**Comment by acrojas2** [comment]
@stephichau antes lo tenía así y tampoco funcionaba  :(

**Comment by Hernan4444** [comment]
@acrojas2 por la definición que me das puedo suponer que tiene otro label encima de ese boton y por lo tanto cuando estás haciendo click en el botónen verdad estas clickeando otro label. A medida que uno instancia labels, estos se van sobreponiendo al otro y por lo tanto si creas un botón y luego un label con otra cosa cerca del botón, es probable que el área del label  tape al botón.

Verifica eso primero y de ahí me cuentas como te fue.

Saludos!!

**Comment by acrojas2** [comment]
Me fue mal! Intente hacer self.boton.raise_() para levantar el botón y tampoco me funcionó.

**Comment by Hernan4444** [comment]
no es necesario usar raise para levantar, sino solo cambiar el orden de como instancias
Si tienes algo de la forma:
```
self.botton = QPushButton(self)
self.label = QLabel(self)
```
Significa que el label estará sobre el botton, pero si pones
```
self.label = QLabel(self)
self.botton = QPushButton(self)
```
Ahora el botón estará encima del label

**Comment by acrojas2** [comment]
@Hernan4444 Aún no me funcionan los botoncitos! es lo último que instancio cuando se crea el widget del juego DDDD: .Hay otra solución posible ?. Sin estos botoncitos no podría hacer ni la tiendita, ni pause, ni botón de regreso al menú inicial. 
Saludos!

**Comment by iqacevedo** [comment]
@acrojas2 revise que podía estar fallando, tienes un label llamado _score_ sobre los botones de pausa (muevelo y veras que si son apretables).
Saludos !
