### ISSUE TITLE
Requisitos T01

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#569]
Hola!!

¿En la tarea es obligación ocupar properties?

Gracias :)

**Comment by vicentevegaulloa** [comment]
Hola @amahns1 !

Si es obligación usar por lo menos una vez properties. Según el enunciado:

> Para modelarlas correctamente, deberás utilizar conceptos clave de programación orientada a objetos:
herencia, clases abstractas, polimorfismo, properties y relaciones, ya sean de agregación o composición.
Cada uno de estos elementos debe ser incluido en el programa al menos una vez, y deberás descubrir
dónde implementarlos según lo propuesto por el enunciado.

Por lo que si habrá un descuento en el puntaje si no se usan properties, o no hay un uso adecuado de estas.
