### ISSUE TITLE
Duda sobre gasto_cliente_por_mes

### ISSUE THREAD

**Issue by ByDati** [IIC2233/Syllabus#569]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Respecto a los gastos del cliente, a cada pedido se le aplica el descuento respectivo? o se toma el precio normal de la pizza comprada?
Supongo que es aplicandole el descuento, pero prefiero preguntar por cualquier cosa.

Saludos y gracias de antemano.

**Comment by mane6867** [comment]
Hola!, se realizan los descuentos respectivos

**Comment by ByDati** [comment]
Yaaa, graciaaas
