### ISSUE TITLE
jupyter notbook to pdf

### ISSUE THREAD

**Issue by ciquezada** [IIC2233/Syllabus#569]
Hola, quiero pasar un jupyter notebook a pdf (uso windows) pero cuando apreto export to pdf via latex dice que hay un error  (algo de pandoc not found), instale con "pip install pandoc" pero jupyter sigue sin reconocerlo, ¿como lo puedo hacer?

**Comment by jmwielandt** [comment]
Prueba estos links a ver si te sirve
https://stackoverflow.com/questions/15998491/how-to-convert-ipython-notebooks-to-pdf-and-html
https://nbconvert.readthedocs.io/en/latest/
https://github.com/jupyter/nbviewer/issues/279

**Comment by ciquezada** [comment]
SOLUCIONADO: 
         Luego de instalar jupyter notebook en windows es necesario instalar "pandoc" y "miktex" para poder exportar el noteobok a pdf.

instrucciones: https://pandoc.org/installing.html
pandoc releases: https://github.com/jgm/pandoc/releases/tag/2.2.1
miktex downloader: https://miktex.org/download
