### ISSUE TITLE
Orden de los posts T00

### ISSUE THREAD

**Issue by DmBeta101** [IIC2233/syllabus#57]
Hola una duda,

Para el orden ascendente y descendente de los post, es necesario que estén ordenados según hora? Ya que si hay mas de un post el mismo día por el formato en el que se guardan los posts (solo fecha) no se sabe cual viene primero o después.

**Comment by KnowYourselves** [comment]
Hola @DmBeta101!

Debes ordenar los posts de acuerdo al formato de fecha entregado, como este no incluye la hora, la precisión del ordenamiento solo es hasta el día. Es decir, si hay 5 posts en el mismo dia da lo mismo como estén ordenados entre si.

Éxito!
