### ISSUE TITLE
Repositorio Mágico

### ISSUE THREAD

**Issue by JoseAvanzada2019** [IIC2233/syllabus#57]
Si el código de un alumno antiguo (años anteriores) del curso está público y quiero usar algunas de sus funciones. ¿basta con citarlo?

**Comment by lily416** [comment]
Hola 😄

Puedes hacer uso de ese código (y cualquiera que se encuentre público en internet) **mientras lo cites**, debes dejar un _link_ de acceso a dónde lo obtuviste e idealmente la fecha de acceso (por si después llegarán a bajarlo y no pudiéramos acceder al código 👀).

Saludos y éxito con la tarea 👋🏰
