### ISSUE TITLE
¿Qué pongo en el .gitignore?

### ISSUE THREAD

**Issue by martina-abello** [IIC2233/Syllabus#57]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](https://github.com/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

No sé cómo colocar archivos en el archivo .gitignore. En los ejemplos que he visto hay nombres de archivos que tienen * antes, o antes y después, o / antes y/o después, o ambos símbolos, y no sé cómo ni cuándo se utilizan.

(Además, me causa confusión que el enunciado indique que uno de los archivos a ignorar es el mismo enunciado, siendo que el enunciado no está en mi carpeta T1. Dado que en Bases Generales dice que los archivos no deben subirse al repositorio sólo debido a .gitignore, ¿significa esto que tengo que agregar el enunciado a mi carpeta, y luego añadirlo al .gitignore?)

(Otra duda, en los ejemplos por lo general hay texto aparte de los archivos usando #, que creo se supone explica qué es cada archivo? No estoy segura. ¿Eso también hay que hacerlo, y qué es lo que se pone?)

**Comment by Benjeeeh** [comment]
Hola!
Te recomiendo revisar el [siguiente link](https://github.com/IIC2233/contenidos/blob/main/.gitignore) de contenidos en donde se explica el archivo .gitignore, y posibles carpetas que se pueden autogenerar por el uso de programas como vscode u otros, por lo que te recomiendo considerarlas.
En resumen, el archivo .gitignore es para literalmente ignorar ciertos archivos a la hora de hacer push, pero de forma automática, no porque tu decidiste no subirlos (es decir, por medio de git y no porque lo hiciste de forma manual).
La simbología que se utiliza es la siguiente:
 / es para carpetas, es decir, juego/ ignora la carpeta y todo lo contenido en el.
* se usa mayormente para extensiones, por ejemplo al usar *.txt haces que se ignoren todos los archivos que tengan esa extensión.
# se usa para comentar cosas dentro de tu archivo, al igual como lo haces con tu código. Puedes hacerlo si lo consideras necesario para entender algo, pero no se utiliza tanto.
Respecto a lo del enunciado, lo ideal es que por ejemplo si descargas el enunciado y lo añades a tu carpeta (por motivos de orden, etc) este no se suba a tu repositorio. Aunque no tengas el archivo descargado, igual debes añadir la extensión pdf a tu gitignore. 
Saludos!

**Comment by martina-abello** [comment]
Agradezco la intención, pero ya había revisado ese link antes de hacer mis preguntas.

¿A qué te refieres con añadir la extensión pdf al gitignore? El enunciado solo dice que se ignore Enunciado.pdf.

**Comment by Benjeeeh** [comment]
Puedes agregarlo de los dos formas, ignorando de forma directa el Enunciado (que es lo recomendable ya que es lo que dice la tarea) o la extensión .pdf, ya que eso incluiría al enunciado también.
De cualquiera de las dos formas sirve, y no se debería tener problemas en la corrección de tu tarea.

**Comment by martina-abello** [comment]
Oka, muchas gracias.

**Comment by vichoassadi** [comment]
Copié todo directamente del Syllabus en mi repositorio personal local, y le agregué el .gitignore inmediatamente. Cuando tiré la carpeta T1 al GitHub en la nube no me aparecen las carpetas que puse en el .gitignore (supongo que está bien). No existe problema con que no esté el imprimir_tablero.py, por ejemplo, en el GitHub? Ya que se ocupa en la tarea. Gracias.

**Comment by Benjeeeh** [comment]
@vichoassadi 
Está bien, ya que ese archivo en el enunciado dice que debe ignorarse, y por lo que describes realizaste bien el proceso (es decir, está en tu computador para poder probar tu programa, pero en github no debe estar). A la hora de revisar nosotros tendremos ese archivo en nuestros computadores para poder ejecutar el programa.
Cerraré esta issue ya que está resuelta, así que si tienes otra duda debes crear otra.
Saludos! :)
