### ISSUE TITLE
Ayudantía "virtual": Herencia y Clases Abstractas

### ISSUE THREAD

**Issue by andresfdezc** [IIC2233/Syllabus#57]
¡Hola!

Los ayudantes de docencia preparamos un material de apoyo para su estudio de esta semana. Pueden encontrarlo [aquí](https://github.com/IIC2233/Syllabus/blob/master/Ayudantias/S02%20-%20Herencia%20y%20Clases%20Abstractas/S02%20-%20Herencia%2C%20Polimorfismo%20y%20Clases%20Abstractas.ipynb).

Cualquier duda que tengan al respecto pueden preguntarla en esta misma issue.

Además, si encuentran algún error, por favor avísennos.

¡Nos vemos el jueves en la actividad!

**Comment by PIPEAPABLAZA** [comment]
Hola,  no entiendo que hace el comando super().entrenar() en los metodos entrenar de las subclases de atleta. Entiendo que en la clase atleta, entrenar es abstracto y por lo tanto no se puede llamar.

**Comment by fringlesinthestreet** [comment]
El comando `super()` en la función fue un error nuestro. Ya está subida la última versión de la ayudantía. En esta se puede apreciar que `CiclistaMontagna` y `CiclistaPista` no poseen el método entrenar, esto es porque su padre ya posee este método (estas clases heredan de `Ciclista`) por lo que ellas ya pueden realizar la acción.
Lo sentimos por el error y gracias por la aclaración.

**Comment by lootarola** [comment]
def __lt__(self, other):
        if type(self) == type(other):
            # Si son del mismo tipo, simplemente compararan sus mejores marcas
            return self.mejor_marca() < other.mejor_marca()
        elif isinstance(other, Triatleta):
            # Si el otro objeto es un triatleta, daremos vuelta la comparación
            # para que se llame al método __lt__ específico del Triatleta.
            return other > self

Tengo una duda respecto a esa parte del codigo en la clase Atleta, no entiendo por qué al retornar other > self llama al método __lt__ del Triatleta en lugar del método __gt__

**Comment by jerosalazar** [comment]
@lootarola lo que entendí es que es complicado hacer una relacion de < ó > con un corredor, ciclista o nadador como self y un triatleta como other (debido a que el triatleta tiene listas distintas para sus tiempos de bici, trote y nado) así que esos casos especiales los define en los operadores del triatleta (acá hay una foto del método \_\_lt\_\_ del triatleta)
<img width="625" alt="captura de pantalla 2017-08-16 a las 4 35 41 p m" src="https://user-images.githubusercontent.com/30667977/29381799-daebb64e-82a0-11e7-9747-fc8e93616301.png">
Al retornar `other > self` manda el problema al método del triatleta y así no es necesario definir ese caso especial en cada subclase de atleta.
Espero que te sirva 😊
