### ISSUE TITLE
Variables globales

### ISSUE THREAD

**Issue by jahernandez2** [IIC2233/Syllabus#57]
Hola, en el menu de usuario defino una variable como True para hacer un ciclo: menu_usuario(ciclo = True...)
¿Esto cuenta como una variable global? Para ver el tema de la penalización. 
Saludos

**Comment by Emiliax16** [comment]
Hola! estaría bien en tu caso, ya que pertenecería a los parámetros de la función. Variable global sería que definieras la variable fuera de la función `menu_usuario()` y luego la utilizaras dentro de ella ***sin pasarla como parámetro***. Saludos!

**Comment by sconchac** [comment]
Hola, siguiendo más o menos con la misma duda, 1) No se puede definir la variable en parametros.py y después importarla?
Para cerrar toda duda, 2) Podemos aparte modificar el módulo parametros.py o debemos entregar el mismo que se entregó?
Gracias :)

**Comment by Emiliax16** [comment]
Hola @sconchac ! Sí a ambas preguntas 😺 pero no olvides subir parametros.py a tu repositorio!
Saludos.
