### ISSUE TITLE
cómo importar

### ISSUE THREAD

**Issue by nlvargas** [IIC2233/Syllabus#57]
Hola,

Me gustaría saber cómo importar una clase y sus métodos desde un módulo a otro pero sin que se ejecute todo el código en el módulo importado.

**Comment by KnowYourselves** [comment]
Tienes dos opciones:
1) `from nombre_modulo import nombre_clase`
2) En el modulo definir todas las clases y su metodo y al final hacer la siguiente linea de codigo: `if __name__ == “__main__”` Despues de esa linea puedes escribir todo el codigo que quieras el cual no sera ejecutado cuando hagas `import nombre_modulo` 
`

**Comment by nlvargas** [comment]
Gracias!
