### ISSUE TITLE
Error al agregar el caracter "■" a un archivo

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#57]
Estoy probando el tema de guardar las partidas en un archivo, y al tratar de agregar el caracter que sale en el enunciado (estoy usando Jupyter para probar) me sale el siguiente error:
![Sin título](https://user-images.githubusercontent.com/48482398/63133875-18e1e300-bf95-11e9-858e-665f368efa73.png)
Intenté reemplazando este caracter por un punto en los tableros y no tengo este error. Es necesario utilizar el caracter cuadrado en los tableros o puedo reemplazarlo por un punto?

**Comment by KnowYourselves** [comment]
Hola @FelipeA7!

Este error te sale porque el caracter que estás intentando utilizar no puede ser codificado correctamente. (Verás más esta materia después en el curso 👀). Para efectos de guardar tus partidas puedes guardar la información como sea que estimes necesario, puedes incluso representar cada punto como "potato" si quieres (please don't).

Espero haberte ayudado!

**Comment by jmwielandt** [comment]
Hola @FelipeA7 !

Complementando a lo dicho por @KnowYourselves , si cambias 
```python
archivo = open("partidas.txt", "a")
```
por
```python
archivo = open("partidas.txt", "a", encoding="utf8")
```
No debería darte problemas.

Saludos!

**Comment by FelipeA7** [comment]
> Hola @FelipeA7 !
> 
> Complementando a lo dicho por @KnowYourselves , si cambias
> 
> ```python
> archivo = open("partidas.txt", "a")
> ```
> 
> por
> 
> ```python
> archivo = open("partidas.txt", "a", encoding="utf8")
> ```
> 
> No debería darte problemas.
> 
> Saludos!

Gracias a ambos! Usé lo de encoding = "utf8" y ahora no me sale el error
