### ISSUE TITLE
Usar código anterior 

### ISSUE THREAD

**Issue by camisilvag4** [IIC2233/syllabus#57]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Hola! quería saber si hay problema en ver o ocupar código de alguna tarea que ya hice. 
El semestre pasado boté el ramo pero alcancé a hacer algo de la primera parte de la tarea, que es la misma idea del flujo de lo que llevo ahora. Si no hay problema, debo especificarlo en el readme? Muchas gracias!]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Juampisaez** [comment]
Hola @camisilvag4 
Si puedes usar el código. Pero debes referenciar en tu README qué parte estás reutilizando y de que evaluación **(muy importante para no caer plagio, todo se revisa 👀).**

Espero este bien claro, cualquier cosa quedo atento :)
