### ISSUE TITLE
Duda cycle() de itertools

### ISSUE THREAD

**Issue by pityton** [IIC2233/Syllabus#570]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, para usar una función como cycle() de itertools, ¿debo citar de donde saqué la información para saber cómo se usa o solo puedo usarlo?, ya que en los contenidos solo lo mencionan. No es el caso en donde uso código, lo explico y lo cito, sino que solo aprendo cómo funciona.

**Comment by kbetelgeuse** [comment]
Hola @pityton !

Bastaría solamente que en la parte del código en donde la utilizas cites en qué te estás basando (si es que te estás basando en un código ajeno y se está adecuando ese código al desarrollo de la consulta) y de dónde se obtuvo esa información. De acuerdo con lo que mencionas, al parecer ya estás realizando esto en la parte del código en donde usas `cycle`, por lo que ya no habrían problemas de citas. Si deseas, podrías poner en el README dónde aprendiste a utilizar ese comando, pero lo necesario que aparezca serían los dos puntos que mencioné anteriormente (el código en el que te basas y de dónde lo obtienes). Un ejemplo de cita de esos dos elementos importantes:

`"código basado en el hecho por [usuario ejemplo] para [lo que hace el código]. Obtenido de [link ejemplo]"`

Espero haber resuelto la inquietud que tenías :)! (si es que no, puedes seguir preguntando)

**Comment by kbetelgeuse** [comment]
Hola, por favor no cierres las issues, de eso nos encargamos nosotros :)
