### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by josejimenezp** [IIC2233/syllabus#570]
Hola, quería saber cuántos emojis debería implementar para que me asignen todo el puntaje del bonus. Gracias!

**Comment by lily416** [comment]
Tu duda fue respondida en la issue #564.
Siempre es bueno revisar las issues que ya fueron hechas para ver si tu duda ya fue respondida.

Salidos y éxito con la tarea 👋

**Comment by josejimenezp** [comment]
Sorry y gracias jajaja
