### ISSUE TITLE
MouseTracking

### ISSUE THREAD

**Issue by Okhan97** [IIC2233/Syllabus#570]
Tengo problema con el mouse tracking, funciona perfecto si es que el mouse esta presionado, cambia la direccion de mi personaje y avanza , pero no puedo lograr que lo haga sin presionar el mouse.

Busque en internet y decia que debia poner "self.setMouseTracking(True)" en el MainWindow , que esto haria que el metodo mouseMoveEvent funcionaria incluso aunque no estuviera presionado pero no me ha resultado asi u.u.

¿ Alguna solucion ?

**Comment by hanavarrete** [comment]
puedes revisar lo propuesto en #568 y decirme si eso te funciona? Saludos

**Comment by Okhan97** [comment]
Gracias :D
