### ISSUE TITLE
Formato parameters.py (variables v/s diccionario)

### ISSUE THREAD

**Issue by Drpinto1** [IIC2233/Syllabus#570]
Saludos, al momento de hacer el módulo parameters.py, es obligatorio usar variables y luego importarlas o el formato en que se guardan los parámetros queda a nuestro criterio?
En particular, estaba guardando los parámetros en dicionarios, según su categoría, para luego importar el diccionario y recuperar las constantes de la forma:

`from parameters import person_parameters`
`patience = person_parameters['patience']`

Es esto válido/recomendable?
Gracias de antemano!

**Comment by Hernan4444** [comment]
@Drpinto1 si es válido, mientras que las key se puedan interpretar facilmente para poder editar.

Saludos ✌️
