### ISSUE TITLE
Días de competencia

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#570]
Hola! Sigo media perdida con el tema de los días de competencia. Entiendo cómo cambian según entrenamiento/campeonato pero ahora no entiendo por qué el contador de días de competencia en la clase campeonato es un parámetro. Qué pasa si ese no empieza en 0? En el fondo: empieza el juego y empieza con un día de entrenamiento. Pero si el parámetro "día actual" se fija en 5, el primer día (de entrenamiento) es el 4? Además, DIAS_COMPETENCIA siempre será par, pero si, por ejemplo, DIAS_COMPETENCIA es igual a 6 y DIA_ACTUAL es 2, quiere decir que tenemos que simular 5 días?

**Comment by vicentevegaulloa** [comment]
Hola @kalarconvl !

Primero, `DIAS_DE_COMPETENCIA` es una parámetro y `dia_actual` es un atributo de Camponato. Esto significa que el primero es una constante y el segundo varía a medida que vayan pasando los días.  `DIAS_DE_COMPETENCIA` siempre será par (para que el último dá sea una competencia y no un día de entrenamiento) y `dia_actual` siempre partirá en 0. Por lo tanto, el caso que pones:

> Pero si el parámetro "día actual" se fija en 5, el primer día (de entrenamiento) es el 4?

jamás ocurrirá ya que se parte en 0 (entrenamiento) el `dia_actual` y aument a medida que pasan los días. Respecto al segundo caso que das:

>   Además, DIAS_COMPETENCIA siempre será par, pero si, por ejemplo, DIAS_COMPETENCIA es igual a 6 y DIA_ACTUAL es 2, quiere decir que tenemos que simular 5 días?

En este caso, como `dia_actual` es un atributo y no un parámetro, no se pude fijar, pero supongamos qu ya pasaron los días 0 y 1, por lo que te encuentra en el días 2. Eso significa que te quedan 4 días por simular (2, 3, 4 y 5) para completar los 6, ya que partes del 0. 

Espero haber resuelto tu duda. Si no queda claro sientete libre de preguntar por aqui 😄

**Comment by kalarconvl** [comment]
@vicentevegaulloa gracias!! Pero entonces los números que están en celeste en el enunciado no son los números que hay que poner en el archivo parametros.py? El 0 de dia_actual, los 0 y 1 de las fórmulas para los puntajes de los deportes, el 200 de sanar lesiones, los mínimos y máximos de excelencia y respeto, implementos deportivos e implementos médicos, y todos los demás números que están en ese formato? Los ponemos tal cual o hay que importarlos de parámetros?

**Comment by kalarconvl** [comment]
Todos esos números celestes no so lo mismo que las palabras de: "Las palabras escritas en ESTE_FORMATO son parámetros que tendrás que escribir e importar desde el archivo parametros.py"

![Enunciado pdf - Google Chrome 14-09-2020 17_48_28](https://user-images.githubusercontent.com/68581172/93136641-a4ef9e00-f6b2-11ea-81bf-c372a04cb125.png)

**Comment by vicentevegaulloa** [comment]
Los parámetros están en **mayuscula y en celeste**. Los números también están en celeste pero no significa que sean parámetros.

**Comment by kalarconvl** [comment]
@vicentevegaulloa aaah eso cambia mucho las cosas jajajajaja gracias!

**Comment by vicentevegaulloa** [comment]
Además, lo importante de los parámetros es que seas capaz de identificarlos tu mismas, como valores que son constantes durante el transcurso del juego pero que si quisieras modificar es más fail mediante u parametr en el archivo parametros.py en vez de meter mano en el código para cambiar un valor.

**Comment by vicentevegaulloa** [comment]
De nadaa @kalarconvl !!

**Comment by kalarconvl** [comment]
@vicentevegaulloa sorry lo latera, esque en la issue 465 y 496 dijeron que todos los números son parámetros, me quedo con que son números directos en el código o parámetros que hay que importar de parametros.py?

**Comment by vicentevegaulloa** [comment]
Mil disculpas!! Me confundí!! Son parámetros pero tu debes ponerle el nombre.

**Comment by kalarconvl** [comment]
@vicentevegaulloa 😭 entonces cómo es lo del día actual? Porque si día actual empieza en 5, el primer día de entrenamiento qué es? 4? y siempre será par el día actual?

**Comment by vicentevegaulloa** [comment]
@kalarconvl disculpa la confusión 🤕. La idea es que parametrices todo lo que te ayude a personalizar el programa lo máximo posible. `dia_actual` sigue siendo un atributo de campeonato, pero lo que debes parametrizar es el valor inicial de este atributo.   No te preocupes respecto al valor del parametro con el cual debe iniciarse `dia_actual`, ya que siempre nosotros no lo cambiaremos de 0. Sin embargo, es importante que lo parametrices y lo setees en 0 para que te "acostumbres" a parametrizar lo más que puedas, ya que esto siempre facilita las modificaciones en tus programas (aunque en este cao especifico no se cambiará de 0).

Una vez más lamento mucho la confusión, espero que haya quedado más claro ahora.

**Comment by kalarconvl** [comment]
@vicentevegaulloa Dale perfecto! Gracias y tranquii no hay problema!

**Comment by vicentevegaulloa** [comment]
De nada! Gracias a ti por corregirme 😊

**Comment by alejita97** [comment]
no entendí muy bn el atributo dia_actual, dice que parte en cero, el día cero lo considero como de entrenamiento??

**Comment by vicentevegaulloa** [comment]
Hola @alejita97!

Claro, el día 0 es un día de entrenamiento. De esa manera, como DIAS_COMPETENCIA es par, el campeonato termina en una competencia
