### ISSUE TITLE
calcular aprobación da enteros?

### ISSUE THREAD

**Issue by carolinamaggi** [IIC2233/syllabus#570]
si por ejemplo el magizoólogo tuviera 9 criaturas, de las cuales 8 están sanas y 7 que no han escapado, porque una criatura puede tener ambas características, me daría un nivel de aprobación de 83,3333
y en el enunciado dice que el nivel de aprobación debe ser entero.

**Comment by jeschuwirth** [comment]
Hola!

esta consulta esta resuelta en la issue #547.

**Comment by carolinamaggi** [comment]
disculpa, no es lo que pregunté, ahí dicen que si son enteros, pero con el ejemplo que di claramente no da entero y por eso mi confusión

**Comment by jeschuwirth** [comment]
![image](https://user-images.githubusercontent.com/37160256/79776807-46411680-8304-11ea-9aec-6501936edef4.png)


Los [ ] en la fórmula de aprobación representan parte entera (truncar sin decimales), por eso e resultado es entero.

Éxito!
