### ISSUE TITLE
¿Cantidad de Sockets?

### ISSUE THREAD

**Issue by JuanDlugo** [IIC2233/syllabus#570]
Hola! No me queda claro si en la tarea se debe hacer un solo server socket que capte los mensajes de todas las salas y las redistribuya o si se pueden hacer 4 sockets distintos (uno para cada sala) y que de esta manera cada uno solo esta pendiente de su sala.
Gracias!

**Comment by jmwielandt** [comment]
Hola,

Fíjate en que la conexión entre el cliente y el servidor está presente incluso si el cliente no está dentro de ninguna de las salas de chat, por lo que debes utilizar un único socket para todas las salas y mensajes que no se correspondan a las salas. Y está en la distribución de puntaje que les enviamos:

![image](https://user-images.githubusercontent.com/37153467/69905813-def7e980-1397-11ea-8e68-91807d8bd1d6.png)


Saludos.
