### ISSUE TITLE
Problema reinstalando PyQt5

### ISSUE THREAD

**Issue by Vicho77** [IIC2233/syllabus#570]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Desinstalé y volví a instalar PyQt5 por que tenía un problema con PyQt5-tools, que logré solucionar pero ahora no me funciona PyQt5. Cuando corro mi tarea, me aparece "from PyQt5.QtWidgets import (
ImportError: DLL load failed: No se encontró el proceso especificado.". Desinstalé, volvi a instalar PyQt5, reinicié el computador y sigo con problemas. Que puedo hacer?

**Comment by clementevalladares** [comment]
Hola @Vicho77, finalmente pudiste solucionar el problema?

**Comment by clementevalladares** [comment]
Estuve revisando soluciones y finalmente encontré que podías hacer lo siguiente para reinstalar python, dado que tus archivos estaban dañados.

**Comment by Vicho77** [comment]
Hola! 

Si, a lo bruto nomás, tuve que reformatear el computador entero. Gracias igual por la ayuda!!
