### ISSUE TITLE
Problemas con el menu de preparacion en nueva ronda

### ISSUE THREAD

**Issue by TomasFouyet** [IIC2233/syllabus#571]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola buenas, tengo un problema, luego de que el tiempo de la ronda de mi jugador se acaba, este vuelve al menu de preparacion con su nueva vida puntaje etc. sin embargo, cuando vuelvo al menu de preparacion necesito que se ejecute en __init__ de ese menu denuevo, pero nose como hacer esto, otro problema similar es que cuando vuelvo a jugar una nueva ronda, tambien necesito que se ejecute el __init__ de ese menu, ya que necesito que vuelva a comenzar el thread del policia y este se crea en el __init__, pero nose como hacerlo :(

**Comment by JadrinaDA** [comment]
Hola TomasFouyet! Entiendo tu problema. Tienes que rehacer todo el init? Te recomendaría que las partes que debes repetir lo pongas en otra función que corras desde el init (ej. set_up_menu()). Así cuando vuelvas a necesitar correr eso puedes simplemente llamar la función. También puedes guardar los objetos de los menús, usarlos luego borrarlos y volverlos a instanciar. Avísame si tienes más dudas!
