### ISSUE TITLE
Entrega y tiempo de carga

### ISSUE THREAD

**Issue by BoPe3p** [IIC2233/Syllabus#571]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, me surgió una duda ya que paso todos los tests cases y creo que tengo bien las funciones, sin embargo a veces me salta fail en el tiempo de carga, pero es casi como si fuera aleatorio, de hecho cuando tengo la pestaña de cmd o gitbash abierta paso los cases, pero cuando las minimizo y pongo el código a correr a veces me salta FAIL en la carga de datos de algunas funciones. Más aún, correr el código en git-bash es más rápido que en cmd por lo que pregunto si esto es normal y si es que a la hora de corregir la tarea se va a tener en cuenta esto. Adjunto imágen:

![image](https://github.com/user-attachments/assets/9405ae8a-cba5-4ac1-884a-83ab63016f7d)

**Comment by Gcamposbriceno** [comment]
Hola!
En general es mejor quedarse con cmd, ya que esa es la terminal que se usa en la corrección automatizada.
Si tus tests fallan de manera aleatoria por tiempo, es mejor buscar alguna otra manera más eficiente para evitar que eso pase justo cuando sea la corrección.
Para el segundo problema, no sé muy bien que podrás estar haciendo, pero se me ocurre que quizás estás cortriendo el código con el botón de vscode. Esto no es lo mismo que correrlo desde la terminal y no es recomendable. Si no es así, intenta explicar mejor cuándo ocurren estas fallas para ayudarte mejor.
Saludos!
