### ISSUE TITLE
Capacidad instalaciones

### ISSUE THREAD

**Issue by valerojasm** [IIC2233/Syllabus#571]
Hola! Para calcular la capacidad dan una fórmula. Tengo que asumir que se puede ocupar cualquier archivo con una cantidad x de instalaciones o contar con las que viene el archivo que nos dieron? 

Gracias!

**Comment by mfanselmo1** [comment]
Hola!
No puedes asumir que el numero de instalaciones que vienen es fijo.

**Comment by Pipelao** [comment]
Hola :)
Tengo una duda con la capacidad de instalaciones, ¿en qué momento varían?, ¿a medida que hay gente en las instalaciones la capacidad disminuye? Digo para calcular el X del que no puede sobrepasar el parque en cuanto a cantidad de gente.
Aprovecho de hacer otra pregunta, si se alcance el limite de capacidad, ¿la gente tendrá que esperar que se vacíe para poder entrar o nunca entra?
Gracias de ante mano

**Comment by mfanselmo1** [comment]
Hola
La capacidad de las instalaciones no varian, son siempre las que salen el csv. Lo segundo queda a tu criterio.

**Comment by Pipelao** [comment]
Gracias
