### ISSUE TITLE
incongruencia de nombre de variables

### ISSUE THREAD

**Issue by caespinoza5** [IIC2233/Syllabus#571]
En parámetros iniciales, según enunciado, hay varias variables que presentan disconcordancia con el archivo csv entregado. Entre ellas, dias_susto y días_susto, dinero_estudiantes y base_mesada, personalidad_hyde y personalidad_hide. Lo anterior también sucede con el archivo escenario.csv.

Lo mismo sucede en productos, con: Calorías y Calorias, Tasa de putrefacción y Tasa Putrefacción.

Solicito favor arreglar estos archivos, para poder leerlos correctamente según lo que aparece en enunciado.

¡Gracias de antemano!

**Comment by josefinabengoa** [comment]
Además de eso, hay algunos parámetros en el enunciado que salen con acento y otros no, como por ejemplo: dias_susto (sin acento) y distribución_almuerzo (con acento). ¿Los parámetros del archivo parámetros_iniciales.csv tendrán exactamente los mismos nombres que el enunciado? o tendrán todos acento o ninguno? 

Muchas gracias!!

**Comment by iqacevedo** [comment]
Hola,

Como indican están esos errores en los archivos csv. Sin embargo, como queda poco tiempo para la entrega, y muchos de sus compañeros pueden haber utilizado los archivos csv que están subidos, no los actualizaremos. De todas maneras, si los nombres al leer los archivos csv están como en el enunciado, se considerará correcto (si usaron los nombres del enunciado, cuando corrijamos lo probaremos con un archivo que esté escrito como en el enunciado).

@josefinabengoa lo anterior se refiere a los nombres que efectivamente están distintos en el enunciado y en los archivos csv, tal como dice días_susto es uno de ellos. Sin embargo,  distribución_almuerzo tiene tilde tanto en los archivos csv, como en el enunciado, por lo que siempre aparecerá así.  

Disculpas por el error,
Saludos !

**Comment by Regenschrim** [comment]
Tengo una duda con respecto a eso. Por ejemplo, yo no he hecho todavía la simulación de los escenarios, por lo tanto, solo he usado el archivo `parametros_iniciales.csv`, justamente es ahí donde esta la diferencia de nombres. ¿Se considerará malo si el programa corre solo con el archivo `parametros_iniciales.py` y no con `escenarios.csv`? Pregunto porque en la respuesta solo especificaste el caso de que los nombres esten como el enunciado.

Gracias de antemano!

**Comment by iqacevedo** [comment]
@Regenschrim no es que esté malo si no utilizas escenarios.csv, tan solo que tendrías mala esa parte de la tarea y todo lo que la relaciona (escenarios). Respecto a los nombres de las columnas, los que están en parametros_iniciales.csv si son iguales a los de escenarios.csv (aplica lo mismo en ambos casos, cuando leas escenarios.csv tienes que leer los nombres de las columnas de ese archivo).

Espero haber contestado tu duda, ya que no me quedo del todo clara 😅
Saludos !

**Comment by Regenschrim** [comment]
Creo que no me explique bien jaja En escenarios.csv sale dias_susto sin tilde y también personalidad_hide, en cambio en parametros_iniciales.csv sale días_susto con tilde y sale personalidad_hyde. El enunciado tiene dias_susto sin tilde y  personalidad_hyde. A lo que voy es que ninguno de los formatos de los archivos calza con el enunciado, entonces mi programa funciona con uno con el otro (ya que use un diccionario y significaría un cambio en las keys). El problema es que si lo cambio al formato del enunciado, no me correrá con ninguno de los dos :/ ¿Debería usar los formatos de los archivos mientras trabaje y antes de entregarlo cambiarlo al formato del enunciado? ¿O lo dejo para que funcione con alguno en particular? Espero se entienda mejor.

Saludos!

**Comment by iqacevedo** [comment]
Si tu programa corre con los nombres de las columnas de los archivos subidos está bien :)

No tienes que cambiarlo :)
