### ISSUE TITLE
Borrar linea

### ISSUE THREAD

**Issue by cmarquez1** [IIC2233/syllabus#571]
Hola, para el juego hago que para crear una linea apreto un punto y arrastro el mouse hasta otro punto lo cual me crea una linea. Sin embargo, al tratar de crear otra linea, la primera se me borra y la segunda se crea. Como puedo solucionar esto?

**Comment by gatochico** [comment]
Hola! Podrías subir la versión de tu tarea que contiene el problema a tu repositorio?

**Comment by cmarquez1** [comment]
Lo acabo de subir, en la carpeta client esta interfaz.py donde esta el codigo que hace las lineas. Para ser exacto de la linea 206 hasta la 233.

**Comment by gatochico** [comment]
Lo que está ocurriendo es debido a la forma en que funciona Qpainter!

Dentro de tu _paintEvent_, vi que haces un llamado a _qp.begin(self)_ cada vez que quieres dibujar la nueva linea. Sin embargo, cada vez que uno llama a _qp.begin(self)_, automaticamente se resetea cualquier cambio o dibujo previo hecho con el mismo evento de Qpainter para reemplazarse con el nuevo dibujo y es por eso que se te borran las otras líneas 😢 .

Algunas alternativas que puedo sugerirte:
- Haz que tu _paintEvent_ pinte todas las líneas existentes cada vez que es llamado.

- O simplemente, no utilizar QPainter! En la issue #509 se propuso una buena y válida alternativa. 

Cualquier duda comenta y éxito programando!! 💻

**Comment by cmarquez1** [comment]
No se me ocurre otra forma de hacer el tablero de juego. Donde pueda hacer aparecer puntos y lineas y donde pueda hacer que al tocar la linea esta lo detecte, ya que con qpainter si no guardo las posiciones de las lineas y puntos en alguna lista, no voy a saber donde estan ubicadas estas lineas y puntos pintadas. No se que otro widget podria ocupar para crear el tablero y sea mas facil, porque por lo que tengo entendido la tarea se enfoca mas en Nerworking. Help plis :(

**Comment by gatochico** [comment]
Leyendo tu comentario, puedo decirte que estás bastante cerca de la solución al pensar en almacenar todas las líneas existentes. :eyes: 

Por ahora, tienes implementado atributos que definen el punto de inicio y fin de una línea, ahora trata de expandirlo a un atributo que contenga todos estos pares de puntos.  Finalmente, en tu _paintEvent_, tienes actualmente implementado que dibuje la línea que une los puntos de inicio y fin, te faltaría expandirlo a que repita eso para cada línea válida que tendrás almacenada. Haciendo algo como lo anterior, logre pintar esto en tu tarea :

![image](https://user-images.githubusercontent.com/37161120/59782319-b49fed00-928b-11e9-98fb-a9c7d6f4714f.png)


Recuerda que debes preocuparte que antes de almacenar la línea, verifiques que esta sea válida! :eyes: Ahí no puedo ayudarte más, ya que entramos en territorio de Networking en sí 🤐 .

Saludos y espero haberte podido ayudar!
