### ISSUE TITLE
Números del enunciado que no se si poner de parámetros

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#571]
Hola, en el enunciado a veces se habla de que:

_Probabilidad: Esta probabilidad varía por tipo de criatura y **se mantiene entre 0 y 1.**_

Pero estos datos en la práctica no los uso en mi código, ya que no hay una forma de que estas probabilidades se cambien, ya sea por interacción del usuario o por código, ya que son valores que se asignan al principio y dependen del tipo, entonces el tipo es el que dice realmente entre qué valores está. Sin embargo, en la distribución de puntaje dice:

_Archivo parametros.py contiene **todos** los parámetros especificados en el enunciado._

Entonces no se si debo agregar igual estos valores a `parametros.py`, siendo que no los utilizo.

**Comment by matiasmasjuan** [comment]
Hola @dlmed !

Tal cual como señalas, dado que cada una de las **DCCriaturas** tiene sus **propias** **probabilidades** (dependiendo del atributo), no tiene sentido almacenar **parámetros** que no vas a utilizar ya que no le corresponen a ninguna **DCCriatura** en particular. Por lo tanto, no es necesario incluir esos valores a ```parametros.py```.

Saludos y mucho éxito con la tarea! 😄
