### ISSUE TITLE
orden filas en delegaciones

### ISSUE THREAD

**Issue by alejita97** [IIC2233/syllabus#571]
Hola 👍 una dudita el orden de las filas en delegaciones.csv será siempre el header, luego los datos de la delegación IEEEsparta y después DCCrotona o puede ser aleatorio??

**Comment by jitorcas** [comment]
Hola! @alejita97 

Siempre irá el header primero, luego los datos de DCCrotona y IEEEsparta pueden variar en orden. 

Éxito en la tarea! 🏃🏻🏋️‍♀️
