### ISSUE TITLE
Duda alcance de amistad

### ISSUE THREAD

**Issue by ShescBlank** [IIC2233/syllabus#571]
Hola :D tengo un pequeña duda en la sección de amistades con la función alcance de amistad. Haré un pequeño ejemplo:
Si "A" es amigo con "B" y "C", y, además,"B" es amigo con "C". Al preguntar por el alcance de amistad de "A" a distancia 1, la función debería retornar ["B", "C"]. Pero, ¿si le pregunto por el alcance de amistad de "A" a distancia 2, la función debería retornar [] o ["B", "C"]?

La duda me surge porque en el enunciado se menciona que: "Por ejemplo, los amigos de los amigos de A, que no son amigos de A, son parte del alcance de amistad a distancia dos de A". Por lo que no sé si repetir a los usuarios para todas las distancias posibles (sin repetir nodos) o solo ponerlos para la menor.

Muchas gracias! :D

**Comment by jmwielandt** [comment]
Hola!

Para que te sea más sencillo verlo y en términos de grafos, esa consulta debe retornar todos los nodos alcanzables desde un nodo inicial, pasando por una cierta cantidad de aristas.

Si tienes múltiples caminos para llegar de un nodo a otro, si alguno de esos caminos tiene el largo que buscas, retornas el nodo de destino como parte de tu output. En tu ejemplo, el camino [A, B, C] lleva de A a C con distancia 2, por lo que C forma parte de tu output, también el camino [A, C, B] tiene largo 2, por lo que B formará parte de tu output.

Está implícito, pero hay dos restricciones importantes:

1. El nodo de inicio no forma parte de tu output.
2. No debes repetir nodos en tu output.

Saludos!

**Comment by ShescBlank** [comment]
Muchas gracias :D

**Comment by JuaniAndres** [comment]
@jmwielandt  hola y en el siguiente caso:
![ejemplo](https://user-images.githubusercontent.com/48482216/69923862-80f5ff80-1486-11ea-8349-07ca17b55dc6.png)
Si estoy buscando alcance 4 desde A la respuesta es [B]?

**Comment by jmwielandt** [comment]
Hola @ShescBlank y @JuaniAndres,

Estuvimos revisando el caso y, para ser lo más consistentes posibles con lo que ya les dijimos, acordamos lo siguiente:

Se considerarán dos respuestas como correctas. **Deben** indicar en su readme cuál están haciendo.

La primera opción es tomar el "alcanzables" como un problema de existencia de un camino de largo K. En cuyo caso la única restricción será que no se puede devolver **inmediatamente**; si estás en B y vienes de A, en tu siguiente paso no puedes ir a A. Esta es la opción que se discutió arriba.

<details>
<summary>Simulación</summary>

![image](https://user-images.githubusercontent.com/37153467/69965868-f0560880-14f3-11ea-89e5-b422138bc86a.png)

</details>

La segunda es tomar el "alcanzables" como "todos aquellos donde la distancia más corta hasta ese nodo es de largo K", que es lo que está en los contenidos del curso. Aquí no visitas más de una vez el mismo nodo.

<details>
<summary>Simulación</summary>

![image](https://user-images.githubusercontent.com/37153467/69965612-6c9c1c00-14f3-11ea-9adb-ddcd9fff132b.png)

</details>


En la primera opción, el output del grafo que presenta Juani sí sería B, en la segunda, sería una lista (o _conjunto_) vacía. Me traspapelé en la respuesta anterior y, si no lo han implementado, preferimos que tomen la segunda opción. Por favor, disculpen 🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️

Saludos, espero que estén bien. Mucho ánimo con lo que queda!

**Comment by ShescBlank** [comment]
Hola @jmwielandt, muchas gracias nuevamente por la respuesta, pero me surge una duda con respecto a la primera opción ya que, si existe un ciclo de mínimo tres nodos en un grafo, podría quedarme dando infinitas vueltas dentro de él :/
Al final lo que hice fue recorrer el grafo guardando el recorrido que voy haciendo (usando DFS), es decir, parto desde el origen, voy avanzando nodos (los voy agregando a mi recorrido para no repetirlos) hasta que ya no se puede continuar, una vez que eso ocurre, me comienzo a devolver (quito el último nodo de mi recorrido) y pruebo las otras opciones hasta que se acaben todos los recorridos posibles con la distancia correspondiente. De esta manera, no repito nodos en mi recorrido y obtengo todos los destinos posibles.
Sin embargo, es verdad que esto es un poco distinto a lo que vimos en los contenidos del curso ya que usé backtracking para encontrar todos los caminos que me servían.

A partir de esto ¿qué será mejor, lo devuelvo a lo que tenía antes (considerando la distancia más corta) o lo dejo como está? (No me complica cambiarlo ya que todavía queda tiempo :D)

Saludos y espero tengan una buena semana 🎄 😄

**Comment by JuaniAndres** [comment]
@ShescBlank  según yo la primera opción míralo como que no puedes pasar por la misma arista 2 veces

**Comment by ShescBlank** [comment]
@JuaniAndres sip, eso hice :D, pero he hecho las dos, la versión modificada de la primera (que es la que describí arriba, sin repetir aristas en un mismo recorrido) y la segunda, así que por eso estoy preguntando.

**Comment by jmwielandt** [comment]
ISSUE 571:

@ShescBlank disculpa la demora, pasan cosas. Dado que me preguntas lo que más te conviene, para mí es tomar la segunda opción, hay un algoritmo en los contenidos que se puede aplicar directamente sin hacerle grandes cambios.

El algoritmo que propones también debería servir mientras que, cuando estés en un nodo, no vuelvas al anterior inmediatamente. Por ejemplo, un camino `A B A` es inválido, pero un `A B C A` sí lo es. DFS, BFS o algún otro algoritmo que incluya navegar el grafo estará bien.

@JuaniAndres No es exactamente eso, en realidad podrías tener un camino `A B C A B C` válido.
Saludos!

PD: de nuevo, perdón por la demora, acabo de terminar la i<sub>3</sub> de autómatas :sob:

**Comment by ShescBlank** [comment]
No te preocupes @jmwielandt, la segunda opción fue la primera que hice, antes de escribir esta issue, así que al ver que la recomendabas y que justo la tenía en un commit anterior, la volví a implementar :D

Muchas gracias de nuevo por todo y uuff espero te haya ido increíble en la I, mucho éxito en todo y que sea un buen fin de semestre!!
