### ISSUE TITLE
Duda nombres de usuario

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#572]
Hola una pregunta corta los nombres de usuario solo estarán compuestos por números, letras y espacios o pueden contener también símbolos como por ejemplo (&@$)
También vi que en el archivo que nos entregaron ocupan _ para los espacios esto va a ser siempre o también nos podemos encontrar con " "

Gracias de antemano

**Comment by jmwielandt** [comment]
Hola,

Solo vas a tener los caracteres definidos por el `\w` (estos son: `a-zA-Z0-9_`, incluye tildes) de regex. No habrá espacios ni otros caracteres como los que mencionas. En las consultas los nombres de los usuarios estarán entre comillas simples (`'`).

Saludos!

**Comment by JuaniAndres** [comment]
gracias justo preguntaba para el regex
