### ISSUE TITLE
base_mesada muuuuuy chica

### ISSUE THREAD

**Issue by Jamidd** [IIC2233/Syllabus#572]
se supone que en parámetros iniciales esta la base de la mesada, osea, el dinero que tienen para todo el mes, el problema es que es de solo 3000 pesos y por ejemplo los funcionarios tienen 7000 pesos para solo 1 día (dinero funcionarios).
que hago??, lo considero como el dinero para un solo día y lo guardo en mi base_mesada x20 o lo tomo el total y lo modifico??

**Comment by GustavPrudencio** [comment]
puedes considerarlo como la mesada para un dia o modificarlo según lo que consideres más correcto para la simulación siempre y cuando lo especifiques en el codigo o readme.

Saludos.

**Comment by iqacevedo** [comment]
Hola, 

Respecto a los funcionarios, en el enunciado dice: 

> Disponen de _dinero_funcionarios_ pesos diarios no acumulables para gastar

Por lo anterior, dinero_funcionarios corresponde a la cantidad que tienen para gastar por día.

Respecto a los estudiantes, en el calculo de mesada aparece _base_mesada_, es este el valor al que hace referencia el parámetro de parámetros_inciales.csv.

Saludos !

**Comment by Jamidd** [comment]
justamente, en parametros_iniciales.csv está base_mesada, pero está es de 3000 pesos, lo que es muy poco para que dure todo el mes, serían 150 pesos diarios (no alcanzan ni para un frugele). Por eso preguntaba si podia considerarla como la mesada de 1 dia, ya que base_mesada se supone que es para todo el mes.

**Comment by santi95** [comment]
@Jamidd esos 3000 pesos no es la plata de todo el mes, es la base de la mesada, la forma de calcular la plata mensual está en el enunciado y se hace con respecto a la base mensual

**Comment by Jamidd** [comment]
Soy un pelotudo!!!!! MUCHAS GRACIAS
