### ISSUE TITLE
manejo de bytes

### ISSUE THREAD

**Issue by JoseAvanzada2019** [IIC2233/syllabus#572]
hola, estoy tratando de pasar la matriz RGB a bytes, hasta ahora sin suerte. Lo malo es que no existe un "error modo python" y no he podido ver lo malo de mi lógica. ¿el compress de la info de IDAT es antes o después de calcular el largo? Perdonen lo poco descriptiva de la issue pero he estado pegado en este problema

**Comment by iqacevedo** [comment]
Hola !

Es antes de calcular el largo.

Saludos !

**Comment by JoseAvanzada2019** [comment]
Hola,
eso no funcionó, ¿existe algún otro error recurrente?

**Comment by JoseAvanzada2019** [comment]
no he podido solucionarlo, pero las operaciones matriciales están bien.

**Comment by jfpena1** [comment]
Hola respecto a este tema, al calcular el crc del IDAT, tengo lo siguiente:
calculable = tipo_idat_bytes + bytes_informacion
crc_ihdr = crc32(calculable).zfill(4)

Mi pregunta es, los bytes_informacion para calcular calculable tienen que estar comprimidos o sin comprimir??, porque en el enunciado sale "Calculamos el largo y el CRC al igual que el punto anterior (IHDR)"

Muchas gracias

**Comment by jfpena1** [comment]
ya lo resolvi, gracias
