### ISSUE TITLE
Delay para seguir al mouse

### ISSUE THREAD

**Issue by IriSalazar** [IIC2233/Syllabus#572]
Hola! recurro a ustedes porque no estoy logrando hacer que mi campeon siga al mouse pero de una forma lenta sin usar algo como wait(). Entiendo que hay algo de vectores de otras issues pero trato de implementarlo en el ejemplo que subieron para la tarea y el programa muere.. sera que con el wait es suficiente?

**Comment by iqacevedo** [comment]
Hola,
Lo que puedes hacer es avanzar una cantidad pequeña cada vez que apretes una tecla (tú defines que avance poquito) en la dirección en donde se encuentra el mouse. Para que entiendas más fácil cómo hacer esto prueba con avanzar un pixel hacia una dirección cada vez que se aprete la tecla, por ejemplo `label.move(posición_x_antigua +1, posicion_y_antigua)`.

Saludos !

**Comment by IriSalazar** [comment]
buena, gracias!
