### ISSUE TITLE
Crear resultados.txt en premiar a los deportistas

### ISSUE THREAD

**Issue by nicolecll** [IIC2233/syllabus#572]
Hola, en el enunciado se especifica que se debe generar el archivo resultados.txt luego de realizar las competencias del dia, ¿es posible que lo genere en el metodo que premia a los deportistas?.

**Comment by hsazos** [comment]
¡Hola @nicolecll !

Es posible, pero no obtendrás el puntaje correspondiente a la actualización diaria del archivo de resultados. Revisa la distribución de puntaje ahí esta explicitado.

¡Animo con la tarea!🦕

**Comment by nicolecll** [comment]
Ok, muchas gracias!
