### ISSUE TITLE
formato del archivo log.txt y nombres

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#572]
Hola!
Tengo dos dudas:

En el enunciado se nos indica que este es el formato para escribir los log en el archivo log.txt:

Iteración | Día de ocurrencia | Tiempo | Evento | Entidad(es) afectada(s) | Descripción de la entidad

Mi duda es si se requiere que esté escrito necesariamente en una línea y separado por "|" porque de esta forma, cuando existen muchas entidades afectadas (como un grupo con muchos niños por ejemplo) la línea se vuelve muy extensa y había pensado en escribir en líneas separadas y separar los logs con un salto de línea con el fin de que se pudiera entender con mayor facilidad 
Ejemplo de cómo escribo los logs:

Iteración: 4
Día: Domingo
Tiempo: 13:00
Descripción evento: inicio colación
Entidades afectadas: Atracción Carousel
Entidad generadora: Operador Ilse Serafín Domínguez

La segunda duda es si cuando se pide que los clientes tengan un nombre y un apellido, quiere decir que sólo tengan estos y no por ejemplo dos apellidos o un prefijo ejemplos:
Ing. Noelia Venegas
JacintoJacobo Francisco Javier Zamora Fuentes.

saludos!

**Comment by mfanselmo1** [comment]
Hola!
Para tu primera duda, si es necesario que tenga el formato pedido. Esto es porque van a haber muchos eventos que registrar, entonces con tu forma va a terminar siendo mas dificil de leer.
Para la segunda duda, con un solo nombre y apellido basta.

**Comment by santilaguna** [comment]
@mfanselmo1 Para la segunda duda me refiero a que si es un problema como están actualmente, gracias!

**Comment by mfanselmo1** [comment]
No hay problema que los uses asi, pero podría ser complicarse de mas.

**Comment by santilaguna** [comment]
Buena gracias, es que ya los tenía así!
