### ISSUE TITLE
Señales en QtDesigner

### ISSUE THREAD

**Issue by batfido** [IIC2233/syllabus#572]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo una duda respecto al uso de señales creadas y conectadas en QtDesigner. Mientras trabajaba, conecté varias señales a traves de QtDesigner, solo de interacciones de elementos dentro de la misma ventana, es esto una mala práctica?

**Comment by JadrinaDA** [comment]
Hola batfido! Es perfectamente aceptable crear las señales en QtDesigner, utilizamos este programa para hacer las cosas más fáciles. Mientras todo esté funcionando bien no hay razón por que preocuparse. Avísame si tienes más dudas, éxito!
