### ISSUE TITLE
Consulta Anidadas

### ISSUE THREAD

**Issue by JosefaATP** [IIC2233/Syllabus#572]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Cómo están?

Por mucho que he buscado sobre las funciones anidadas, como que no logro entender mucho como se debe aplicar en este caso con diccionarios y diccionarios dentro de diccionarios.

Si me pudieran explicar entregando un ejemplo, porfas.

Gracias!

**Comment by matiasherrerar** [comment]
Me pasa lo mismo. No logro  relacionar la materia con diccionarios dentro de diccionarios y la seccion de consultas anidadas en los contenidos tampoco se relaciona con lo pedido en la tarea

**Comment by wintermelyn** [comment]
Hola @JosefaATP!

No me queda muy claro si tu pregunta va mas a entender como funcionan las funciones anidadas o a como abordar la solución. Intentaré resolver ambas preguntas igualmente

> ¿Que es una función anidada?

Son funciones que pueden tener otras funciones como argumentos. El objetivo es que puedas ejecutar estas funciones usando un diccionario ejecutando las funciones desde lo mas interno hacia lo mas externo.

Tomando el mismo ejemplo del enunciado
```python
{
  'funcion': 'pizzas_pagables_de_un_tamano',
  'generador_pizzas': {
    'funcion': 'pizzas_con_ingrediente',
    'generador_pizzas': {
      'funcion': 'cargar_pizzas',
      'path': 'data/l/pizzas.csv'
    },
    'ingrediente': 'tomate'
  },
  'dinero': 10000,
  'tamano': 'S'
}
```
Notar que este diccionario nos dice (desde las funciones mas internas a las mas externas).
1. Primero cargar las pizzas desde el csv
2. Filtrar las pizzas por las uqe tienen el ingrediente tomate
3. Filtrar esas pizzas por las que tienen un precio que no excede los $10000 y que son de tamaño "S".

> ¿Como se puede abordar este problema?
Para esto lo mejor es utilizar un bucle o recursion para procesar los elementos en el diccionario. Intentaré explicar por encima como seria abordarlo con recursion

El caso base de la recursion es el punto en el que ya no necesitas hacer más llamadas anidadas. Este caso ocurre cuando llegas a una función que **no tiene otras funciones anidadas como argumentos**, es decir, cuando todos los argumentos son valores simples.

El caso recursivo es cuando encuentras un argumento que es un diccionario (lo que significa que es otra función anidada). Si el valor de uno de los parámetros es otro diccionario, quiere decir que necesitas resolver primero ese diccionario, porque contiene instrucciones para ejecutar una funcion adicional antes de seguir. Por esto llamas a la misma función pero ahora usando el sub-diccionario como entrada, lo que permitirá resolver primero las funciones mas internas. Una vez se ejecuta la función anidada puedes usarlo como argumento para la función que estaba esperando el valor y se va subiendo en el nivel de anidación, ejecutando cada función conforme se resuelven los valores.

**Comment by JosefaATP** [comment]
Entiendo mejoor,
Gracias!!
