### ISSUE TITLE
Duda sobre agregación / composición

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#572]
Hola, con respecto a esto tengo una duda en particular, en mi código, pueden existir magizoólogos aparte del DCC, pero este último es necesario para hacer casi todo, entonces en ese caso se podría decir que no pueden existir magizoólogos sin el DCC? (para efectos del diagrama)

**Comment by Dnpoblete** [comment]
Hola @dlmed, lamentablemente no podemos responder a esta duda, ya que el diagrama tiene que ser un reflejo de tú código, y adicionalmente no podemos decir si algo debiera ser agregación y composición, ya que forma parte de lo que buscamos evaluar que sepan identificar en la tarea.

Éxito con la tarea! :smile:

**Comment by dlmed** [comment]
Entiendo. Esto lo hay que comentar en algún lado del README? me refiero a si nosotres lo consideramos agregación o composición?

**Comment by Dnpoblete** [comment]
La respuesta a tu pregunta sale en el enunciado:
![image](https://user-images.githubusercontent.com/42362982/79799897-3e479d80-8329-11ea-84f4-dfb1da9c2dfc.png)

Pero si la idea es que expliquen el diagrama y utilicen la notación correcta para representar agregación y composición en el diagrama.

Éxito con la tarea! 😄
