### ISSUE TITLE
Funciones Imagen

### ISSUE THREAD

**Issue by bvallejo1** [IIC2233/syllabus#573]
Hola, quería saber si puedo agregarle funciones al archivo pixel_collector.py, desearía agregarle todas las funciones que tengan que ver con la manipulación de la imagen entregada por el usuario, como por ejemplo si entrega una imegen .jpg y transformarla a una .png y guardarla en el servidor.

**Comment by jeschuwirth** [comment]
Hola!

Para evitarte problemas en la corrección te recomiendo **no** cambiar nada en el archivo pixel_collector.py si lo encuentras más cómodo puedes crear un archivo pixel_collector_helper.py con todas las funciones extra que quieras agregar. 

Como pixel_collector.py se los entregamos nosotros en teoría podrías colocarlo en el .gitignore y que nosotros lo agreguemos a la hora de corregir, sin embargo como no es una base de datos grande no es necesario que lo ignores.

**Comment by bvallejo1** [comment]
Hola @jeschuwirth te agradecería si pudieras revisar la issue #535 donde comenté sobre un problema que me surgió.
