### ISSUE TITLE
Diagrama como poner return de una lista o str

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#573]
Hola!
Al momento de crear una clase, tengo una función que me puede retornar una lista o un string, en el diagrama que debería poner? podría ser como: *+ funcion: list/str* ?
Con respecto al tema de composición y agregación. Tengo una *claseX* que sólo existe si se ocupa en otras 3 clases. No sé como debería ser el comportamiento.
Las 3 clases deberían componerse  de *claseX* ? . El tema es que si por ejemplo desaparece una de las 3 clases, esta  *claseX* sige existiendo para las otras dos...
Pero tampoco sé si  estas 3 clases que necesitan de  *claseX* para hacer determinadas acciones, deberían agregarla?
Bueno lo que yo tomé por mientras, es que esta  *claseX* se compone de las otras 3. Considerando que sólo algo desaparecer las 3 clases, desaparece  *claseX*.

**Comment by Camila-sty** [comment]
sólo cuando desaparece*...

**Comment by Dnpoblete** [comment]
Hola @Camila-sty, como ya se ha mencionado reiteradas veces, por favor revisar las otras issues antes de abrir una nueva, y adicionalmente hacer las issues de un solo tema, ya que así es más fácil buscar las preguntas después. Debido a esto dejaré solo la primera duda de título, ya que la segunda fue respondida en la issue #572, pregunta que se hizo justo antes de esta.

En cuanto a la duda sobre retornar una lista o str, esto no es recomendable ya que es considerado una mala práctica, porque los métodos deberían retornar siempre el mismo tipo de dato, por lo que si todavía puedes, te recomiendo que lo cambies. En el caso de que lo mantengas se puede representar como `Método(input): str/list`, pero es una mala práctica.

Éxito en la tarea! :smile:
