### ISSUE TITLE
Habilidad especial DCCrotona

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#573]
Hola! Cuáles serían las bonificaciones de la habilidad especial de DCCrotona? En el fondo, cada vez que un jugador gana una competencia gana una medalla y con ello: 
- 100 monedas para la delegación
- aumenta en 20 la moral del ganador
- disminuye en 10 la moral del perdedor
- disminuye en 0.02 la excelencia y respeto del perdedor.
Pero cuando se usa la habilidad especial solo gana 100 la delegación? O se asigna aleatoriamente un ganador del equipo DCCrotona y un perdedor del equipo IEEEsparta?

**Comment by retamalcito** [comment]
¡Hola @kalarconvl!

Tu duda ya fue contestada en la issue #374, por lo que te recomiendo ir a leerla.

¡Saludos! 👋

**Comment by kalarconvl** [comment]
@retamalcito no lo había encontrado, gracias!
