### ISSUE TITLE
Duda creación de eventos

### ISSUE THREAD

**Issue by dedarritchon** [IIC2233/Syllabus#573]
Cuando un cliente toma una decision y genera un evento, esta toma de decision debe ser un metodo de la clase cliente? o puedo por ejemplo tomar la decision del cliente desde la clase que vendria siendo el "ObjetoSimulacion" en el ejemplo de los contenidos?
Gracias

**Comment by IchottMano** [comment]
@dedarritchon Hola!

Esto queda a tu criterio!

Saludos
