### ISSUE TITLE
Duda párametro parent QObject

### ISSUE THREAD

**Issue by fdominguezclaro** [IIC2233/Syllabus#573]
Hola!
Me salió una duda y por lo que leí no lo han preguntado antes. 

Si bien los **QObjects** que se crean en el MainWindow reciben un parámetro **parent** (Nuestra QMainWindow), esta bien que estos la guarden (self.parent = parent) y después la usen dentro de algún método interno? O sería **programación circular**?

Un ejemplo básico seria para leer algún estado actual del juego, como si está pausado o no.

Gracias!!

**Comment by hanavarrete** [comment]
Si te fijas en el ejemplo no la guardamos. Esto se debe a lo que tu dices, porque sería programación circular. Saludos!

**Comment by akaminetzkyp** [comment]
Hola!

Cuando uno crea una clase que hereda de un `QObject`, el `super().__init__()` tiende a recibir el `parent` del `QObject`. De esta manera, el `parent` puede ser buscado utilizando `parentWidget()`.

En muchos de los ejemplos y programas que he leído se utiliza `parentWidget()` para acceder a los métodos y atributos del `parent`. Como el `parent` del `QObject` queda guardado internamente, ¿podemos usarlo en esa clase?

Saludos!

**Comment by rrhurtado** [comment]
Hola, no hay ningún problema con usar código/ideas vistas desde otras fuentes, solo asegúrate de poner la referencia a la fuente en tu programa.

Saludos

**Comment by akaminetzkyp** [comment]
Creo que no me explique muy bien. 😨

@hanavarrete dijo que en el ejemplo no se guarda el `parent` porque sería programación circular. Sin embargo, los `QObject` guardan a su `parentWidget()` por defecto. No estoy seguro si eso clasifica como programación circular.

Entiendo por qué la programación circular no es ideal en la mayoría de los casos. Sin embargo, al hacer interfaces gráficas con PyQt es común llamar al `parentWidget()` desde el *child*.

Saludos!

**Comment by Hernan4444** [comment]
@akaminetzkyp recordemos que en PyQ  la parte que utiliza el `parent` el del frontend y por lo tanto no 
aunque tengas de atributo a tu `parent` o `children` no es de gran utilidad para nosotros puesto que la información vital está en el backend. 

De todos modos estás en lo correcto, PyQt guarda los parent y children pero para trabajarlo de forma interno y se podría considerar programación circular, sin embargo la idea es que nosotros **(los usuarios que utilizamos la librería PyQt)** no abusemos de eso para realizar programación circular, sino que solo utilizar el `parent o children` para cuando queremos conectar señales

Saludos!!

**Comment by akaminetzkyp** [comment]
Muchas gracias por la respuesta! Entiendo.

Mis unidades heredan de `QLabel`. Es por esto que tienen el método `parentWidget()`. 😃 

Saludos!
