### ISSUE TITLE
Duda Layouts en QDesigner 

### ISSUE THREAD

**Issue by Bizonte28** [IIC2233/syllabus#573]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda sobre QDesigner. He estado intentando hacer las ventantas ahí pero no he encontrado solución respecto a que las ventanas creadas si las expando o comprimo no se redimensionan los Widgets que están adentro.

**Comment by mmunoz12** [comment]
Hola @Bizonte28! Una forma es crear la ventana en Qtdesigner y aquí mismo darle el tamaño que deseas y poner los widgets ya listos con sus tamaños también. Lo otro es que crees la ventana en Qtdesigner junto con sus widgets y luego en tu código las redimensiones. Si ya redimensionaste sólo las ventanas quizás tus Widgets quedaron con las dimensiones dadas en Qtdesigner. Podrías hacer uso de `QWidget.setSizePolicy` para redimensionarlos. También podrías probar con `setFixedWidth()` y `setFixedHeith()`. Espero que eso te ayude, avisame cualquier cosa :)
