### ISSUE TITLE
duda archivo parametros.json T03

### ISSUE THREAD

**Issue by mgbriones** [IIC2233/syllabus#574]
que puede y no puede estar en el archivo parametro.json tanto en cliente como en servidor?
estos dos archivo deben ser idénticos???

**Comment by gatochico** [comment]
Hola! 
Para esta tarea, no se explicitan los parámetros a añadir ya que se busca que puedan distinguir que cosas necesitan ser parámetros y cuáles no. Dicho esto, podría serte de ayuda preguntarte **qué cosas deben mantenerse constantes dentro de una ejecución completa del programa** (echar a correr tanto el server como los _n_ clientes, hasta que se cierren todos estos scripts contaría como una ejecución), pero al mismo tiempo **pueden cambiar entre distintas ejecuciones del programa.** 

Para tu segunda pregunta, **el archivo de parámetros del server y el del cliente no deberían ser idénticos**, ya que hay parámetros que podrían serle util a uno, pero irrelevante para el otro y viceversa.

Por ejemplo, tomemos del enunciado el parámetro "cantidad de salas". ¿Por qué debe ser parámetro? Una vez ejecutado el programa, este número no puede cambiar durante la ejecución (el número de salas no puede cambiar mágicamente de 2 a 3). Sin embargo, es válido decir que la primera vez que se corra el server se limiten las salas a 2, y una vez cierre todos los scripts y quiera empezar de nuevo, pueda cambiar el valor a 3 y pedir que para esta nueva ejecución sean 3 salas. 

Este mismo parámetro solo le es útil al servidor, ya que es quien regula la cantidad de salas, y debe manejar dicha información. Por ende, debería estar sólo en los `parametros.py` del servidor y no el del usuario.

Espero haberte ayudado! :nerd_face: Cualquier duda pregunta y éxito

**Comment by fmitjans** [comment]
Hola. ¿Si ponemos la dirección del host en el archivo parametros.json, al momento de corregirla no van a tener que cambiarla los ayudantes? Como no se puede almacenar el gethostname() (a menos que usemos eval), tendríamos que guardar la dirección de nuestro propio pc.

**Comment by lily416** [comment]
@fmitjans Para evitar cambiar la hots en cada computador que se ejecute puedes hacer:
```python
host = 'localhost'
```

Saludos y éxito con la tarea 👋🐧
