### ISSUE TITLE
Problema al subir archivos con tilde

### ISSUE THREAD

**Issue by iastruque** [IIC2233/syllabus#574]
Quiero hacer un commit de un archivo que se llama menús.py, pero cuando  hago git status me aparece que se llama: "men\303\272s.py"

No sé si subir ese porque me puede generar descuentos.
(no logré subir un pantallazo en el issue)

**Comment by Dnpoblete** [comment]
Hola @iastruque, lo más probable es que esto ocurra porque el archivo que intentas subir tiene un tilde, te recomiendo intentar subiendo el archivo, pero con el nombre `menus.py`, ya que como bien dices, si lo subes con ese nombre, probablemente tendrás un descuento.

Avísame si te resulta! :smile:

**Comment by iastruque** [comment]
Si me resulto, pero hice un commit have unos diás y nome había dado cuenta de ese error.
Que implicancia tiene esto?

**Comment by Dnpoblete** [comment]
Que bueno que te resultara!
Eso sí no entiendo a que te refieres con que implicancia tiene, ¿subiste el archivo con el otro nombre?
