### ISSUE TITLE
Pasar una método de la simulación a una entidad

### ISSUE THREAD

**Issue by NicoRiquelmeCTI** [IIC2233/Syllabus#574]
Hola,

Tengo la duda de si bajo la regla de "Modelar la realidad", es legal que al momento de ir creando las entidades, tenga la habilidad de pasarle a estas un método específico del objeto de simulación, es decir, mi parque. 

Por ejemplo, hago el siguiente supuesto:

El parque tiene un celular 📲en el que recibe solicitudes de los clientes (un método de la clase Parque) y se las entrega al supervisor del parque, para que este decida si lanza un evento, como por ejemplo, evacuar a un grupo porque están muriendo de hambre 😵🚑. Entonces, ahora mis entidades "Clase Cliente" tienen la habilidad indirecta de agregar eventos a la simulación, lo que me haría mucho más sencilla esta tarea. 

Obviamente, explicando esto en mi Readme

Espero haya quedado claro. Gracias!

**Comment by IchottMano** [comment]
@NicoRiquelmeCTI Hola!

Lamentablemente no puedes hacer esto, ya que caería en modelación circular.

Saludos!

**Comment by Hernan4444** [comment]
Hola @NicoRiquelmeCTI tendré que corregir un poco más la respuesta de arriba. Primero, **si puedes**, pero recuerda revisar el material de anexo de simulación donde se indica que más que pasar un método, uno pasa la ejecución de un método, el cual retorna una función dentro. Por ejemplo:
```python
def llamar(self):
    def function(*args)
         #Hago cualquier cosa
         return algo
   return function
```

y digamos que ese método lo tiene la clase simulación. Ella puede hacer que una clase persona la instancia de la forma
```python
Persona(nombre, edad, self.llamar()) # Le paso lo que hay dentro del método
# lo cual es distinto a 
Persona(nombre, edad, self.llamar) # Le paso el método
```
Lo primero está totalmente permitido puesto que así uno puede modelar interacción entre clases. Lo segundo (que es lo que quieres hacer) se debe evitar porque estás pasando un método de la clase a la función, con eso ella puede sobreescribir el método y hacer que haga otra cosas, el principal problema es que tooodos quienes recibieron ese método también editarán dicho método.

Te invito a hacer lo siguiente:
```python
class Test:
     def __init__(self):
         pass
     def A(self):
         def function():
             pass
         return algo
     def B(self):
         return 2

test = Test()
print(test.A(), test.A(), test.B, test.B)
```
Ahí verás que en cada ejecución de A(), mandarás una función distinta y por ello, todos quienes tengan esa función, tendrán objetos distintos y por lo tanto editar uno no afectará a los demás, pero cuando haces test.B, siempre te dará el mismo objeto y eso puede ocasionar problema ante una edición del código, pero en términos de modelación circular, no lo hay puesto que te estás dando permiso para ejecutar una  acción especifica que la clase simulación le permitió.

**Comment by pcseisdedos** [comment]
@Hernan4444  yo estaba haciendo algo como esto:
`class A:
       def __init__(self):
              self.atributo = 5
       def function(self)
               return self.atributo`
y luego le pasaba esa función a varios objetos de **OTRA** clase, y al llamar a la función si el atributo cambiaba entonces la funcion retornaba el atributo cambiado, algo así:
`class OtraClase:
     def __init__(self,function):
             self.function = function
a = A() 
b = OtraClase(a.function)
c = OtraClase(a.function)
a.atributo +=4
`
esto implica que tanto b.function() como c.function() retornan 9 (que es lo que yo quiero), hice el cambio que mencionaste en mi clase A:
`def function(self):
        def auxiliar():
               return self.atributo
       return auxiliar`
y ahora tanto a b como a c les paso `OtraClase(a.function())` al instanciarlas, y funciona exactamente igual, entonces no entiendo que es lo que realmente cambió, más específicamente no entiendo esto:

> todos quienes tengan esa función, tendrán objetos distintos y por lo tanto editar uno no afectará a los demás, pero cuando haces test.B, siempre te dará el mismo objeto y eso puede ocasionar problema ante una edición del código

**Comment by pcseisdedos** [comment]
Se ve re feo, pero quise poner esto:
![image](https://user-images.githubusercontent.com/18387808/40578159-60e30962-60dd-11e8-86a6-dc8b988b7564.png)

**Comment by ciquezada** [comment]
Hola, una duda con esto, en el ejemplo donde modelas la forma correcta de la funcion llamar, si retorna la ejecucion de la funcion llamar estaria entregando la funcion que tiene dentro, ¿pero esa funcion tambien podria ser sobreescribible verdad? ¿eso no seria un problema?

**Comment by Hernan4444** [comment]
@ciquezada en ambas formas se puede editar, pero en uno de ellos se está compartiendo el mismo método y en otro no y eso puede ocasionar problemas cuando modelas por ejemplo algún decorador, pero ambos están bien términos de modelación circular.

**Comment by ciquezada** [comment]
y si existiera la clase "evento" como en el ejemplo de los contenidos de los cursos, ¿seria correcto entregarle el metodo de la clase que creo dicho evento, o tambien habria que entregar una funcion que se define dentro del metodo?

**Comment by Hernan4444** [comment]
en lo personal, para mi es siempre mejor lo segundo (una función dentro del método) porque controlas mejor que una edición no afecte a todos, sabes de inmediato que ese método se lo pasarás a otros y tienes un mayor control sobre él y los parámetros que quieres que tenga, pero todo depende  de como modelas y si necesitas algún comportamiento especial.  Ambas formas son correctas según el contexto en el que estás.
