### ISSUE TITLE
duda sobre subir dos archivos "consultas.py"

### ISSUE THREAD

**Issue by franigoat** [IIC2233/Syllabus#574]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda para subir dos archivos y no pasarse de las 400 líneas
Esta bien si creo otro archivo con el resto de las funciones pero lo llamo desde el original?? 
Es decir, tengo mi archivo de consultas.py y en ese importo consultas2.py que tiene las funciones que no me cabían, y en consultas.py, dentro de las funciones, llamo a las funciones que están en consultas2.py y corro los test de esa forma.
(los tests me funcionan correctamente, pero quiero confirmar que si me corrigen de manera automática, esto sería válido)
Muchas gracias desde ya

**Comment by wintermelyn** [comment]
Hola @franigoat!

Está permitido lo que dices, 🧙‍♂️ cito el enunciado de igual manera:
> Puedes crear nuevos archivos y/o funciones si estimas conveniente. También se permite crear funciones en otro módulo y que las funciones que pedimos completar únicamente llame a esa función externa.
