### ISSUE TITLE
Caidas del programa

### ISSUE THREAD

**Issue by andreslyon** [IIC2233/Syllabus#574]
tengo implementado el hook para ver los errores, y evitar que el programa se caiga, sin embargo, al ejecutar mi programa la mitad de las veces se cae, y no muestra el error, la otra mitad funciona, que puede ser?

**Comment by sebacruzd** [comment]
Hola,

Podrías poner todo tu código dentro de un try/except y que se imprima la excepción. Con eso te debería salir el error en la consola.
Prueba eso y avísanos si te sirve :)

**Comment by andreslyon** [comment]
Puse el codigo de los 2 Qthreads involucrados en el problema,  dentro de un try/except, y sigue cayendose, sin mostrar el error

**Comment by sebacruzd** [comment]
Pero estás seguro que son los QThreads?
Tal vez está en otra parte el error. Envuelve *todo* el código con el try/except para confirmarlo.

**Comment by rrhurtado** [comment]
Hola, por como está implementado Pyqt5 es frecuente que algunos errores no se muestren. Como bien dice Sebacruz, envolver en try/except debería funcionar. En caso de que no, te invito a consultar el siguiente link que quizás ayude

https://stackoverflow.com/a/33741755

Saludos

**Comment by Minjor** [comment]
A mi me pasa lo mismo, a veces me funciona pero cuando me arroja un error es del estilo: "python.exe - Application Error     The instruction at 0x55679c24 referenced memory at 0x55915e7c. The memory could not be written. Click on OK to terminate the program". Aun no hago que mis entidades no se superpongan (permito que choquen), puede ser eso?
![capture](https://cloud.githubusercontent.com/assets/26122797/26764074/aeac47a8-492d-11e7-9771-d084d06ecc61.PNG)

**Comment by sebacruzd** [comment]
@Minjor no debería ser problema que se superpongan las entidades, en el sentido del error. Estás haciendo lo de envolver todo con try/except?

**Comment by negutierrez** [comment]
Yo tengo todo envuelto en un try except. pero a veces el programa muere con un 
"Python dejo de funcionar" 
![image](https://cloud.githubusercontent.com/assets/11590773/26768762/188c2842-4978-11e7-9cfa-4f182f57320f.png)
Pasa generalmente cuando ya tengo varios minions (20 o mas), por lo que me tinca que es por CPU, o algo asi.
Hay algo que se pueda hacer? Para no estar obligado a limitar el numero de minions

**Comment by iqacevedo** [comment]
@negutierrez has abierto el administrador de tareas mientras corres el programa? Así puedes ver si es por CPU o algo por el estilo

Saludos !
