### ISSUE TITLE
Duda habilidad especial lisa

### ISSUE THREAD

**Issue by mjadresic** [IIC2233/syllabus#574]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Mi duda es si la habilidad especial de lisa también se activa con 10 saxofones y si se desactiva al agarrar un veneno. En el enunciado no dice nada. Saludos

**Comment by tomasrosenberg** [comment]
Hola @mjadresic!

Como no dice nada sobre lo que mencionas en el Enunciado, la habilidad especial de Lisa ocurre durante durante toda la ronda. Es decir, no es afectada por los objetos agarrados.

Estaré atento a cualquier otra duda :D
