### ISSUE TITLE
Que debe de poder hacer la Tarea: Estadísticas escenario particular

### ISSUE THREAD

**Issue by pdesolminihac** [IIC2233/Syllabus#574]
Del enunciado tengo entendido de que la tarea debe de poder simular los 4 meses para 1 escenario y entregar sus estadísticas al final. (además de que debe poder simular 'k' veces todos los escenarios para comparar)
Para este primer caso,¿Que escenario o parámetros hay que utilizar? ¿Hay que permitir al usuario elegir un escenario especifico o utilizar los parámetros iniciales? 
Edit:
¿Los parámetros iniciales que nos dieron siempre serán los mismos o puede que corrijan con otros?

**Comment by iqacevedo** [comment]
Hola,

En ese primer caso debes utilizar los parámetros del archivo parametros_iniciales.csv. Los parámetros que están en los archivos pueden variar cuando corrijamos, así como el orden de las columnas csv.

Saludos !

**Comment by pdesolminihac** [comment]
Gracias! @iqacevedo
