### ISSUE TITLE
Relación Campeonato - Menús

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#574]
Hola! No logro entender la relación del campeonato con los menús. Al principio del enunciado hablan mucho de menús y dicen que la interacción del juego se hará a través de menús, sin embargo, en la parte de Campeonato explican este como la base del juego donde tienen que incluirse también los entrenamientos y conteo de días, puntajes y medallas. Entonces no entiendo. Me baso en los Menús o en la clase Campeonato? En el caso de que todo se haga en el Campeonato, cómo recomiendan vincularlo con los menús? Porque hasta ahora tengo TODO con base en el menú de inicio, principal y de entrenador.

**Comment by amparostevens** [comment]
Hola @kalarconvl !

Efectivamente la interacción con el programa se hace en base a menús, por lo tanto, tu implementación está correcta.

La interacción a través de menús significa que gracias a ellos puedes seleccionar qué acciones realizar y efectivamente ejecutarlas, pero su definición y funcionamiento no es propia del menú, sino que está contenida en una clase. En este caso, la clase `Campeonato` es quien almacena todos los métodos que permiten el funcionamiento general del programa (como los días, realización de competencias, premiación, etc), pero para acceder a ellos y efectivamente ejecutarlos necesitas un menú. 

Espero que te haya quedado más claro.
Éxito con la tarea ✨

**Comment by kalarconvl** [comment]
O sea que desde la clase campeonato hay que llamar a los Menús para que estos funcionen?

**Comment by amparostevens** [comment]
No. Piensa que es exactamente de la misma forma que lo hicieron para la T00, sólo que en este caso deben, además, trabajar con clases, pero el flujo se sigue manejando a través de los menús.

**Comment by kalarconvl** [comment]
O sea que cuando se decide comenzar una partida desde la clase "Menús" puedo crear un objeto de la clase "Campeonato"?

**Comment by amparostevens** [comment]
Sí, podrías hacer eso.

Por ejemplo: inicias el programa y en el menú inicial se elige comenzar nueva partida. Entonces, tal como propones, podrías instanciar una clase `Campeonato` (con los atributos y métodos correspondientes), al igual que las demás clases necesarias. 

Luego se despliega el menú principal y tienes varias opciones para elegir. Si por ejemplo eliges __simular competencias__, entonces ahí se debería ejecutar esa acción, pero esa acción no está definida dentro de tu menú, sino que en la clase `Campeonato`, por lo tanto, al elegir esa acción debes hacer que se ejecute el método definido en tu clase. Esto aplica para todas las demás acciones. 

Como ves, los menús sirven para "dirigir" el programa, pero los menús no son los que en realidad almacenan cómo se deben hacer las cosas.

**Comment by kalarconvl** [comment]
@amparostevens  Dalee muchas gracias!!

**Comment by amparostevens** [comment]
No es nada! Espero que te haya quedado claro 😉
