### ISSUE TITLE
Fijar QGridLayout

### ISSUE THREAD

**Issue by MatiasBarraF** [IIC2233/syllabus#574]
hola, estaba intentando fijar un QGridLayout en la ventana a modo de agregar otros labels y widgets en la ventana, ya que el QGridLayout usa la totalidad de la pantalla
![Screen Shot 2019-06-19 at 12 46 44](https://user-images.githubusercontent.com/48270008/59784427-5de8e200-9290-11e9-99c7-180427060fb5.png)
me gustaría poder fijarla en el espacio en blanco que se ve a la izquierda, pero al agregarla me pasa lo siguiente
![Screen Shot 2019-06-19 at 12 47 02](https://user-images.githubusercontent.com/48270008/59784444-72c57580-9290-11e9-8be6-5f5a751a2b95.png)
llevo mucho pegado y no he podido fijarla, por si alguien me puede ayudar

**Comment by mjespinoza** [comment]
self.grilla.setSizeConstraint(self.grilla.SetFixedSize) eso te puede servir

**Comment by MatiasBarraF** [comment]
> self.grilla.setSizeConstraint(self.grilla.SetFixedSize) eso te puede servir

funciono perfecto, muchas gracias

**Comment by constanzacontreras** [comment]
Hola aprovechando esta issue! También tengo problemas con las grillas, ya que al tener una grilla se me expande en toda la pantalla, y no se como hacer para que solo me aparezca debajo del titulo y con los botones mas chicos.

![Captura de pantalla 2019-06-19 15 51 32](https://user-images.githubusercontent.com/48296666/59795844-30a92d80-92aa-11e9-8765-273d4b36efa9.png)

**Comment by jeschuwirth** [comment]
Hola, aunque es lo correcto colocar tu pregunta debajo de una issue que va a lo mismo, como no había ayudante asignado se podía llegar a perder, para que lo tengas en cuenta.

Un modo de solucionar tu problema es crear una grilla de altura 2, donde el elemento de arriba es el nombre de la sala y el elemento de abajo es tu grilla de botones. 

En el siguiente ejemplo sacado de: http://zetcode.com/gui/pyqt5/layout/ utilizan una 'grilla' horizontal para colocar los botones de "ok" y "cancelar", luego crean una 'grilla' vertical donde colocan la grilla horizontal como uno de los elementos. 

De ese modo podrían colocar un QLabel en la parte superior de la grilla vertical con información y abajo aparecerían los botones uno al lado del otro.


![image](https://user-images.githubusercontent.com/37160256/59811011-f0f83b00-92d5-11e9-979f-0de2a039f6e0.png)

Ojalá te sirva como ejemplo para tu tarea.

Suerte!
