### ISSUE TITLE
Estadísticas - "Cantidad de alumnos que... "

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#575]
Holaa,
Para estadísticas como "Cantidad de alumnos que no almorzaron por mes" o "Cantidad promedio de miembros (...) que abandonaron una cola de espera por día", la interpretación literal es que si a un alumno le pasa dos veces en un día/mes, cuenta una sola vez. Quisiera saber si esto está bien.

Graciaas

**Comment by iqacevedo** [comment]
Hola tómalos como un contador esos casos, en el sentido de que si le pasa dos veces en un día cuenta como dos (se debería hacer más sencillo el cálculo así).

Saludos !
