### ISSUE TITLE
Posible error en enunciado (filtro daltonismo)

### ISSUE THREAD

**Issue by furzuadr** [IIC2233/syllabus#575]
Estuve implementando el bonus de daltonismo, y pude crear mi imagen con filtro para deuteranopia. El problema es que mi resultado es distinto al del enunciado, supuse que estaba mal.

La cosa es que probé la imagen en diversos simuladores de daltonismo y en todos me dio igual a mi imagen.

Es posible que la imagen del enunciado no sea correcta?
Muchas gracias!

**Comment by KnowYourselves** [comment]
Hola @furzuadr!

Podrías hacer push de tu programa, con una función que permita probar tu filtro? 

Gracias!

**Comment by furzuadr** [comment]
Me mandarías el filtro online? Lo probé y me dio igual jajaja, acabo de hacer push. Es el archivo filtro_daltinismo.py dentro de server. Ojalá si puedes probar con la misma imagen que probaste el otro! Quizás sea por un tema de la imagen! Gracias!

**Comment by furzuadr** [comment]
Hola! Pudiste revisarlo? Muchas gracias!

**Comment by KnowYourselves** [comment]
Hola @furzuadr, tienes toda la razón, la foto utilizada para el enunciado estaba equivocada. Tu filtro funciona perfect!

**Comment by furzuadr** [comment]
Muchas gracias!
