### ISSUE TITLE
Separar parametros.py en varios módulos

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#575]
Hola,
Puedo separar parametros.py en varios archivos distintos para que sea todo más ordenado? (y fácil para mí)
Por ejemplo, en un módulo los parámetros que tienen que ver con las personas, en otro los del parque, en otro los de la simulación en sí, etc.
Gracias~

**Comment by nachocontreras** [comment]
Hola!

No, no se puede separar ```parametros.py``` por efectos de corrección. Sin embargo, puedes usar diccionarios con los parámetros para ordenarte :smile: .

Éxito con la tarea!

**Comment by nachocontreras** [comment]
Básicamente, como dice el enunciado, es para poder ser modificados con facilidad, permitiendo
evaluar la simulación bajo distintos valores iniciales. 
Estando en archivos separados su modificación sería más complicada. Más que nada es por eso. 😃
