### ISSUE TITLE
interfaz

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#575]
en la parte de interfaz dice:
![pregunta](https://cloud.githubusercontent.com/assets/26102365/26759241/bb122ae2-48c6-11e7-9060-80309c33d291.PNG)

mi pregunta es la barra de vida debe ir flotando alrededor de los personajes o podemos 
hacer que cuando el mouse pase sobre un personaje se muestre la vida en la barra de estado

**Comment by stephichau** [comment]
Debería estar visible siempre :).

**Comment by Dunkan1** [comment]
genial gracias
