### ISSUE TITLE
Características únicas de Magizoólogos respecto a alimentar una DCCriatura

### ISSUE THREAD

**Issue by NikiHV** [IIC2233/syllabus#575]
Hola! Tengo una duda con las características únicas de los Magizoólogos al alimentar una DCCriatura.
Se supone que el Magizoólogo Docencio aumenta 5 puntos de la salud total de la criatura alimentada, el Magizoólogo Tareo tiene una probabilidad de aumentar al máximo la salud de la DCCriatura que recibe el alimento y el Magizoólogo Híbrido recupera 10 puntos de salud de la DCCriatura que alimenta. Pero estas acciones ¿son solo si la criatura come efectivamente el alimento? Estoy pensando en el caso que reciba un Buñuelo de Gusarajo y la rechace. ¿O estas acciones especiales de los Magizoólogos son independientes de que la criatura coma o no finalmente el alimento?

**Comment by mpsubiabre** [comment]
Hola @NikiHV!

Esta pregunta esta respondida en la issue #357 

Éxito en la tarea:)
