### ISSUE TITLE
envío de mensajes - big endian

### ISSUE THREAD

**Issue by JosefaPaz** [IIC2233/syllabus#575]
Hola!

He estado buscando información y me gustaría saber para qué sirve poner el número de bloque al enviar datos en formato big endian, supongo que es para cuando son muchos bytes y no confundir la información, pero no he encontrado información exacta

gracias!

**Comment by jmwielandt** [comment]
Hola,

Te recomiendo mirar la issue #546, ahí lo conversamos en detalle.

Saludos!
