### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by enriquerussi** [IIC2233/syllabus#575]
Se le hacia .gitignore al archivo pycache que se genera?

**Comment by baosse** [comment]
Holaa @enriquerussi !
El archivo pycache no se debe subir.
Mucho éxito con tu entrega✨

**Comment by enriquerussi** [comment]
> Holaa @enriquerussi !
> El archivo pycache no se debe subir.
> Mucho éxito con tu entrega✨

**Comment by enriquerussi** [comment]
> Holaa @enriquerussi !
> El archivo pycache no se debe subir.
> Mucho éxito con tu entrega✨

Holaa, eso quiere decir que si lo agrego a gitignore? Tengo entendido que no se debe borrar.

**Comment by baosse** [comment]
No, no debes subirlo en el .gitignore, tampoco debes subirla a tu repo. 
Debes ignorar los archivos que te dice el enunciado, que en este caso son _delegaciones.csv_ y _deportistas.csv_ .
Espero que te sirva! ✨

**Comment by enriquerussi** [comment]
> No, no debes subirlo en el .gitignore, tampoco debes subirla a tu repo.
> Debes ignorar los archivos que te dice el enunciado, que en este caso son _delegaciones.csv_ y _deportistas.csv_ .
> Espero que te sirva! ✨

Entonces para ignorarlo, debo subir modulo a modulo de mi Tarea 01 y únicamente no subir el pycache?

**Comment by baosse** [comment]
Sii, eso mismo! Subes los archivos de tu tarea, el .gitignore y 'dejas de lado' la pycache, no la tocas jj 💙
