### ISSUE TITLE
¿parameters.txt?

### ISSUE THREAD

**Issue by rgevert** [IIC2233/Syllabus#576]
Se pueden guardar los parámetros en un archivo .txt o .csv en ves de uno .py?

**Comment by santilaguna** [comment]
@rgevert no soy ayudante, pero no te lo recomiendo es mucho más sencillo guardar los valores en un archivo.py porque sino tendrás que convertir todos los valores (cargarán todos como string), mientras que con un .py simplemente importas la variable que desees.

**Comment by leolivares** [comment]
@rgevert lo que dice @santilaguna es correcto. La idea de que sea en un archivo _.py_, es que puedas definir los parámetros ahí, importar el archivo, y utilizarlos según sea necesario.
Saludos!
