### ISSUE TITLE
Frecuencia de aparición respecto al tiempo

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#576]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### La pauta menciona lo siguiente
![image](https://user-images.githubusercontent.com/66154723/120375234-8e44b200-c2e8-11eb-912d-5e25f1eada53.png)

**Comment by valerianazal** [comment]
Hola @fernandosmither ! Puede estar un poco confuso ese item, pero se refiere a la **sección 3.3** del enunciado, adjunto foto:

<img width="1026" alt="Screen Shot 2021-06-01 at 16 29 16" src="https://user-images.githubusercontent.com/69606605/120386486-b1765e00-c2f6-11eb-8a69-33f59757a290.png">
La frecuencia de aparición en cada nivel es fija, solo depende de la dificultad, pues debe ser mayor la frecuencia en el nivel **Avanzado**.
Espero haber resuelto tu duda 🌟

**Comment by fernandosmither** [comment]
> Hola @fernandosmither ! Puede estar un poco confuso ese item, pero se refiere a la **sección 3.3** del enunciado, adjunto foto:
> 
> <img alt="Screen Shot 2021-06-01 at 16 29 16" width="1026" src="https://user-images.githubusercontent.com/69606605/120386486-b1765e00-c2f6-11eb-8a69-33f59757a290.png">
> 
> La frecuencia de aparición en cada nivel es fija, solo depende de la dificultad, pues debe ser mayor la frecuencia en el nivel **Avanzado**. Espero haber resuelto tu duda 🌟

Perfecto. Solo para el double-check. Que la frecuencia de drop dependa del tiempo transcurrido es falso, ya que esta es fija y solo depende de la dificultad?

**Comment by valerianazal** [comment]
Sí, es como dices. No cambia la frecuencia en el nivel y solo depende de la dificultad, la que se elige antes de empezar la ronda.
Mucho éxito en la tarea! ✨
