### ISSUE TITLE
tiempos de carga

### ISSUE THREAD

**Issue by DiegoRODestudiante** [IIC2233/Syllabus#576]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

hola estoy haciendo las funciones de dos generadores y voy por la 14, y me esta resultando MUY dificil que no me de error por tiempo de carga, al menos en la terminal de VS code, en la 14 por ejemplo hago 2 ciclos solamente y ni siquiera asi me baja de los 80 segundos, ayuda estoy muito frustradinho

**Comment by mane6867** [comment]
¡Hola!  viendo tu código, parece que tienes un uso excesivo de bucles (for y while), lo cual está afectando el tiempo de ejecución, esto es algo común cuando se procesan grandes cantidades de datos o se tienen bucles anidados. Puedes revisar issues que hablan de esto como la  #514
