### ISSUE TITLE
Extensión máxima lineas PEP8

### ISSUE THREAD

**Issue by burizar** [IIC2233/syllabus#576]
Hola! ¿A partir de que largo de linea empiezan a descontar puntaje? ¿100 u 80?
Tenía entendido que eran 100 pero tengo instalado el PEP8 en vs code y me da problemas con lineas más largas que 80 caracteres.
Gracias!

**Comment by baosse** [comment]
Holaa @burizar ! 
Si tu línea sobrepasa los 100 caracteres comienza a descontar.
Espero te sirva! Mucho éxito con tu tarea✨

**Comment by tsunayoshi21** [comment]
Disculpa, como instalas pep8 en vscode?

**Comment by baosse** [comment]
Holaa @tsunayoshi21 !
Aparece en la [wiki](https://iic2233.github.io/wiki/interface) del curso, en la parte de VSCode. El linter es el que te ayuda a ver los errores que vas teniendo en tu código. 
Espero que esto te sirva💙

**Comment by caroizquierdo** [comment]
duda que pasa si me paso de los 100 caracteres pero son despues de un # ?

**Comment by baosse** [comment]
Holaa @caroizquierdo ! 
Si te pasas de los 100 caracteres (con comentarios o sin comentarios) cuenta como una falta a PEP-8.
Mucho éxito!✨
