### ISSUE TITLE
Fecha de entrega T5

### ISSUE THREAD

**Issue by fantinee** [IIC2233/Syllabus#576]
disculpen duda administrativa. El enunciado dice que la fecha de entrega es mañana dia lunes a las 23:59, sin embargo, el calendario dice que es hoy domingo a las 23:59. Me podrian aclarar cual es la fecha correcta

**Comment by sebacruzd** [comment]
Hola, la fecha de entrega es el lunes a las 23:59.

Saludos!

**Comment by fantinee** [comment]
gracias :D 🎉
