### ISSUE TITLE
parametros_generales.json

### ISSUE THREAD

**Issue by F-arellano** [IIC2233/syllabus#576]
Una consulta respecto respecto a la eficiencia de procesos. habia pensado simplemente abrir el archivo .json y colocar toda su info en un diccionario, para luego trabajar con el, pero me surgió la siguiente duda, ¿no me genera problemas si fueran archivos muy grandes? porque eso significaria que tendria una variable con toda la información, y tal vez bastaria con abrir el archivo, guardar en una variable solo lo que necesito y luego cerrar el archivo (aunque claro, tendria que hacer esto cada vez que requiera una nueva variable, por eso la duda).

**Comment by jmwielandt** [comment]
Hola,

La librería json sí o sí va a cargar todo el contenido del archivo en tu memoria para buscar un solo valor. En ese sentido es mucho mejor abrir el archivo una sola vez en lugar de hacerlo por cada vez que lo requieras, ya que los accesos a disco son mucho más lentos que los accesos a memoria. Por las dimensiones de la tarea, no deberían ocupar demasiado espacio en tu memoria, ni de broma deberías estar superando el KB de RAM en los parámetros.

Te recomiendo que abras una sola vez el archivo `parametros.json` por cada lado del socket y cargues todo en un diccionario no más, es más simple que andar abriéndolo y cerrándolo constantemente.

Saludos!

**PD IMPORTANTE: el nombre pedido para los archivos es `parametros.json`, no `parametros_generales.json`. Debes respetar el nombre de los archivos ya que es parte del _formato_ de la entrega.**
