### ISSUE TITLE
filtro foto

### ISSUE THREAD

**Issue by Nitsuga69** [IIC2233/syllabus#576]
Hola!! realice el filtro de la foto según los pasos indicados, pero mi foto queda así al aplicarle el filtro:
<img width="386" alt="Captura de Pantalla 2019-06-19 a la(s) 2 15 23 p  m" src="https://user-images.githubusercontent.com/48293112/59789950-d9e92700-929c-11e9-815b-9892b722f413.png">
Y según el enunciado, debería quedar así:
<img width="193" alt="Captura de Pantalla 2019-06-19 a la(s) 2 16 50 p  m" src="https://user-images.githubusercontent.com/48293112/59790003-ef5e5100-929c-11e9-88ba-496b4a1f42f6.png">
Revise el código y no sé que odia tener malo, alguna idea???

**Comment by jeschuwirth** [comment]
Hola!

Como dice la issue #499 no importa que no quede igual al enunciado, aún no sabemos cuando se va a considerar un filtro bien aplicado y cuando no. Parece que tu algoritmo está considerando mucho el brillo(punta de la cola, parte e arriba de la cabeza y el estómago) y los cambios de gradiente (cambios entre brillo y sombra en las patas y manos).

Te recomiendo revisar las partes 2.1 y 2.2 (que tu cota esté correcta) y la parte 2.4 de este [enunciado](https://github.com/IIC2233/syllabus/blob/master/Tareas/T03/T03%20-%20PNG%20y%20Filtros.pdf)

De todos modos tu filtro se ve bastante bien :D

Exito en la tarea

**Comment by jeschuwirth** [comment]
Hola,

La issue #592 tiene ejemplos del filtro aplicado, para que sepas como debería quedar la imagen.

Suerte!
