### ISSUE TITLE
duda sobre la agregación

### ISSUE THREAD

**Issue by enriquerussi** [IIC2233/syllabus#577]
Hola, si uno de los atributos que recibe una clase es otra clase, entonces se estaría haciendo una relación de agregación? Ya que, la clase que es un atributo de la otra es independiente de la existencia de la clase en la que esta siendo atributo.

**Comment by mmunozmendez** [comment]
Hola!
Si la clase que es atributo de la otra puede existir sin la que la contiene si es agregación. 
Por ejemplo, si tienes la clase Ramo_1, que tiene una lista de estudiantes de la clase Estudiante que están en el ramo. Si Ramo_1 desaparece, les estudiantes no desaparecen, podrían estar en otros ramos. Este caso es agregación.

Éxito 🦆 !
