### ISSUE TITLE
Uso de todos los sprites

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#577]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

**Comment by Juampisaez** [comment]
Hola @fernandosmither 
Constestando a tus dudas, puedes hacer como estimes conveniente el uso de sprites mientras se cumpla con lo pedido (movimiento fluido). Respecto a tu segunda duda, si te refieres al sprite que pareciera estar parado nomas, no te recomendaria que lo consideres como neutral, de hecho, la idea de entregar asi los sprites es para mostrar la secuencia en el movimiento de un personaje, es decir, que pase del 1 al 2, del 2 al 3 y del 3 al 1.

Avisame si te queda mas claro :)

**Comment by fernandosmither** [comment]
> Hola @fernandosmither
> Constestando a tus dudas, puedes hacer como estimes conveniente el uso de sprites mientras se cumpla con lo pedido (movimiento fluido). Respecto a tu segunda duda, si te refieres al sprite que pareciera estar parado nomas, no te recomendaria que lo consideres como neutral, de hecho, la idea de entregar asi los sprites es para mostrar la secuencia en el movimiento de un personaje, es decir, que pase del 1 al 2, del 2 al 3 y del 3 al 1.
> 
> Avisame si te queda mas claro :)

Entonces no importa que al finalizar la animación quede con un pie arriba y el otro abjo?

Y lo otro, por  ejemplo justamente homero down_3 por como lo veo yo (quizás lo estoy viendo mal) es raro cuando se añade a la animación, porque es como que estuviera bailando al juntar sus manos periodicamente mientras camina, jaja, por eso me planteo no utilizarlo.

**Comment by Juampisaez** [comment]
Si, da lo mismo en realidad **si queda parado o con un pie avanzado**. Respecto a lo segundo, la verdad es que no te compliques por ese caso especifico, piensalo como que es la secuencia de movimiento, 1-2, 2-3, 3-1 y asi.

De hecho, hay herramientas que se enseñan en el curso para hacer este tipo de secuencias jijiji.
Pero insisto, como lo estas pensando puede complicarte un poco si implementas los demas personajes :) (el down_3 es diferente para algunos).

Espero quede mas claro :)

**Comment by fernandosmither** [comment]
> Si, da lo mismo en realidad **si queda parado o con un pie avanzado**. Respecto a lo segundo, la verdad es que no te compliques por ese caso especifico, piensalo como que es la secuencia de movimiento, 1-2, 2-3, 3-1 y asi.
> 
> De hecho, hay herramientas que se enseñan en el curso para hacer este tipo de secuencias jijiji.
> Pero insisto, como lo estas pensando puede complicarte un poco si implementas los demas personajes :) (el down_3 es diferente para algunos).
> 
> Espero quede mas claro :)

Sí! muchas gracias.

**Comment by ag-contreras** [comment]
> Si, da lo mismo en realidad **si queda parado o con un pie avanzado**. Respecto a lo segundo, la verdad es que no te compliques por ese caso especifico, piénsalo como que es la secuencia de movimiento, 1-2, 2-3, 3-1 y asi.

Hola! Quiero aportar, que para que la animación de movimiento se vea fluida, es mejor hacerlo en el siguiente orden:
1-2-3-2 (y loopearlo)
Así se vera muy fluido el movimiento. En caso de pasar del 3 al 1, se salta el 2 que funciona como transición.

Adjunto una prueba de concepto, con algo muy similar que ocurre al hacer un Gif con una cámara análoga especial.
https://giphy.com/search/nishika-n8000/

**Comment by fernandosmither** [comment]
> > Si, da lo mismo en realidad **si queda parado o con un pie avanzado**. Respecto a lo segundo, la verdad es que no te compliques por ese caso especifico, piénsalo como que es la secuencia de movimiento, 1-2, 2-3, 3-1 y asi.
> 
> Hola! Quiero aportar, que para que la animación de movimiento se vea fluida, es mejor hacerlo en el siguiente orden:
> 1-2-3-2 (y loopearlo)
> Así se vera muy fluido el movimiento. En caso de pasar del 3 al 1, se salta el 2 que funciona como transición.
> 
> Adjunto una prueba de concepto, con algo muy similar que ocurre al hacer un Gif con una cámara análoga especial.
> https://giphy.com/search/nishika-n8000/

Gracias por el aporte! Igual me preocupa que el tener tantos frames pueda influir negativamente en que no pase desapercibido que la animación termina después del movimiento como tal y eso conlleve descuento 😓 , quizás es más fácil ajustar el tiempo con 2 frames, pero de todas formas le daré una vuelta!
