### ISSUE TITLE
Error JSONDecodeError: Extra data 

### ISSUE THREAD

**Issue by cotosaenz** [IIC2233/syllabus#577]
Me ha salido varias veces ese error (json.decoder.JSONDecodeError: Extra data: line 1 column 79 (char 78)) en distintas oportunidades. Puede ser que pase porque envío varias cosas al mismo tiempo desde el servidor al cliente?, ocupando la misma función "send" del servidor, o no tiene nada que ver eso?. Gracias!

**Comment by jeschuwirth** [comment]
Hola!

probablemente sea porque envias dos veces información al cliente y la segunda llega antes de que se termine de procesar la primera, por lo que los bytes de juntan y levanta este error, revisa la issue #532 que tenía un error parecido

Suerte !

**Comment by cotosaenz** [comment]
muchas gracias!!
