### ISSUE TITLE
Dudas sobre evaluar test en diferentes computadores

### ISSUE THREAD

**Issue by BenJofre27** [IIC2233/Syllabus#577]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

hola buenas, que pasa si cuando evaluo un test en un compu me sale todo ok, pero si ese mismo test lo evaluo en otro compu, habiendo pasado el codigo sin ningun cambio, me sale que hay fallos o incluso errores? a cual de los dos compus le hago caso como para modificar mi codigo?

**Comment by MaxAl100** [comment]
Hola! Se me ocurren tres razones posibles por las que los tests te funcionen correctamente en un dispositivo y no en otro.
1. Tienes los tests desactualizados en uno de los dos dispositivos. Recuerda que acutalizamos los tests durante el transcurso de la tarea, por lo que si no los actualizaste en uno de los dispositivos y sí en el otro, esto puede ser la causa de la diferencia.
2. Versión de python diferente. Debido a que python cambia el funcionamiento de ciertas funciones en sus versiones, puede que el funcionamiento del código sea distinto en distintos dispositivos.
3. Distinta versión de tu código. Esta tercera opción es que tengas tu código desactualizado en uno de los dos dispositivos, lo que causaría que los tests funcionen correctamente en un dispositivo y no en el otro,
Avísame si cualquiera de estas opciones te funciona o si sigues necesitando apoyo. Saludos y buena suerte con este último trecho!

**Comment by BenJofre27** [comment]
Eran los test desactualizados. menos mal, pense que iba a tener peor puntaje con esos errores extras. Muchas gracias por la ayuda :)
