### ISSUE TITLE
Problema Posición

### ISSUE THREAD

**Issue by maxfreymo** [IIC2233/Syllabus#577]
Cuando intento realizar el cambio de posición del Campeón, el programa me arroja error porque me señala que 'position' no esta en el 'dict' del personaje. 

pd: El código base es el del ejemplo que nos dieron, solo que en vez de cambiar la posición desde el run lo hago de manera externa como Campeón.position = ([Campeón.position[0] + 10, Campeón.position[1])

**Comment by sebacruzd** [comment]
Hola,
De qué manera está definido Campeón.position?
Lo estás usando como una property? Si es así, tienes definido el property setter?

**Comment by maxfreymo** [comment]
@sebacruzd sii esta definido como property con su respectivo setter, igual al ejemplo que subieron :(

**Comment by sebacruzd** [comment]
Y estás llamando a eso desde adentro del campeón o afuera? Si es desde afuera al parecer es por eso. Si creas un método que lo use (ese método lo puedes llamar desde afuera para que use el property setter)  no debería haber problema.
