### ISSUE TITLE
Eventos Externos al Parque

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2233/Syllabus#577]
Me gustaría saber si pueden suceder dos de estos eventos al mismo tiempo o se puede hacer el supuesto que cuando llueve Ruziland se queda en su cueva y no sale a invadir el parque.
De antemano, muchas gracias

**Comment by leolivares** [comment]
Hola! @nicoparraguez 
En el enunciado no se menciona que los eventos sean excluyentes.
Por lo tanto, podrían ocurrir ambos eventos el mismo día.
Suerte!
