### ISSUE TITLE
Verificar si usuario existe (usuarios.json)

### ISSUE THREAD

**Issue by SamWeinstein** [IIC2233/syllabus#577]
Hola! Estoy intentando que el servidor verifique si el nombre de usuario existe y si este está conectado, pero me encontré con un problema muy extraño. Al verificar si el usuario existe:
`if nombre == username:` 
(siendo nombre, los nombres sacados de los diccionarios de usuarios.json y username el nombre ingresado por el usuario),  nunca ingresa al if, es decir, if nombre == username me da siempre False. Intentando solucionar el error, hice los siguientes prints antes del if: 
`print(f'{nombre} {type(nombre)}')`
`print(f'{username} {type(username)}')`
Y en el terminal me aparece:
1 <class 'str'>
1 <class 'str'>
Osea que aparentemente, son iguales, pero aun asi el '==' me da False. 
Ya intenté todo, incluyendo reiniciar el programa. 
Que puedo hacer? Mi código está en mi repositorio por si lo quieren revisar. 
Gracias!

**Comment by SamWeinstein** [comment]
Seguí avanzando en mi tarea ignorando este error hasta que nuevamente me encontré con otro error del mismo estilo, donde comparo 2 simples strings idénticos y me da False. Lo solucioné cambiando el `==` por `in`, pero esa solución claramente no sirve en el caso del nombre de usuario.

**Comment by jmwielandt** [comment]
Hola,

Justo iba a comentarte lo del largo = 113. Tu elemento invisible son los _bytes_ 0, que no tienen representación gráfica. Tu error está en el código que decodifica el mensaje que le llega del servidor. Debes remover esos _bytes_ cero con operaciones sobre los _bytes_, no sobre el string resultante (es lo que buscamos evaluar).

Saludos!

**Comment by SamWeinstein** [comment]
Solucionado, gracias!
