### ISSUE TITLE
Uso de Libreria Pyqt5.QtWidgets.QGraphicsPixmapItem para detectar colisiones y otros

### ISSUE THREAD

**Issue by kraksiplus** [IIC2233/syllabus#578]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
 Bueno mi duda es bassicamente si permiten el uso de la libreria Uso de Libreria Pyqt5.QtWidgets.QGraphicsPixmapItem para detectar colisiones entre objetos (se que es parte de la libreria Pyqt5, pero es mejor preugntar :D) 

Aparte tengo una duda con el uso de exec() en main.py ya que para ejecutar las ventanas es necesaria tener la linea: 

sys.exit(app.exec())

¿supongo que no deberia haber problema no?

Les deseo un excelente dia, ¡¡cuidense!!

**Comment by tomasrosenberg** [comment]
Hola @kraksiplus!

Existe una _issue_ general donde se pregunta si es posible usar las distintas librerías, esta es la #473. Así que te pido que por favor que preguntes por ahí para que quede guardado y te respondan. En primer instancia, te diría que sí se puede usar porque es parte de PyQt5 pero igual deberías preguntar 👀.
El uso de exec() es un método de algunos widgets de PyQt5, no una librería (es normal confundirse) por lo que no estaría prohibido su uso. De igual forma, esta duda se respondió en la _issue_ que te mencioné antes.
Quedo atento a cualquier otra duda :) Éxito en la Tarea! 💻
