### ISSUE TITLE
¿Qué hacen operadores y porteros?

### ISSUE THREAD

**Issue by Pipelao** [IIC2233/Syllabus#578]
Hola
Una consulta un poco rara, ¿de qué me sirven los operadores? Porque los tengo como objetos y los instancio pero, ¿en algún momento debo imprimir sus nombres?, porque no les tengo ninguna funcionalidad, y las que mencionan las hago en la misma simulación, ¿hay algo que esté pasando por alto?
Gracias de ante mano

**Comment by leolivares** [comment]
Hola! @Pipelao 
Recuerda que en el archivo _log.txt_, debes incluir todos los eventos que ocurran con los respectivos nombres de las entidades.
En el caso de que un operador se retire para la colación (por ejemplo), debes indicar la entidad involucrada, y su nombre respectivo.
Espero que te ayude.

**Comment by Pipelao** [comment]
Gracias
