### ISSUE TITLE
Pregunta de Qt

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#578]
Tengo un boton y un QLineEdit, como puedo enviar el resultado del QLineEdit a la funcion de el boton, para asi guardar el valor? Lo puedo guardar the forma externa?

**Comment by gatochico** [comment]
Hola! El [siguiente notebook de los contenidos](https://github.com/IIC2233/contenidos/blob/master/semana-06-07/4-dise%C3%B1o-front-back.ipynb) tiene ejemplos de lo que deseas realizar :see_no_evil:.
Éxito y cualquier duda pregunta!
