### ISSUE TITLE
testcase 4 consultas anidadas

### ISSUE THREAD

**Issue by bernarditaaliaga** [IIC2233/Syllabus#578]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

En el testcase 4 del archivo test_consultas_anidadas, no entiendo como funciona, entiendo que como el argumento es un diccionario, si la llave de la 'funcion' es otro diccionario, lleva a la recursividad y la funcion se llama a si misma, como es el caso del test 4, en la cual primero se intenta ejecutar la funcion total_ahorrado_pedidos con los argumentos: generador_contenido_pedidos, proveniente del archivo directamente, y el argumento generador_pizzas, proveniente de otra funcion que devuelve 9 instancias de pizza, en este contexto, como funciona la funcion total_ahorrado_pedidos, si habran pedidos en los que su pizza no este en los valores disponibles para calcular el ahorro?

gracias de antemano

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Gcamposbriceno** [comment]
Hola!
De la descripción del test al que te refieres: "Verifica que el test funcione para una consulta acerca de lo que se puede ahorrar un cliente que quiere 9 pizzas y no le gusta la salsa de tomate". En resumen, lo que tienes que lograr es quedarte sólo con los pedidos que coincidan con las pizzas que quiere el cliente, ya que no va a comprar las otras pizzas que tengan ingredientes que no le gustan.
Espero haberte ayudado!
