### ISSUE TITLE
Llegada al campus / Almorzar

### ISSUE THREAD

**Issue by mmsaavedra1** [IIC2233/Syllabus#578]
Si un MiembroUC llega pasado el intervalo de almuerzo ya definido:

Ej: Llega a las 14:38, pero pertenece al porcentaje de los que almuerzan entre 12:00 - 12:59

¿Lo considero como que no almorzó, o se omite para efecto de las estadísticas?

Saludos 😄

**Comment by iqacevedo** [comment]
Hola,

En otras issues se indicó que en este caso tú consideras qué pasa (si almuerza o no). Debes ser consistente con esa decisión, por lo que si consideraste qe no almorzaba si debería contar (puesto que si llego a la universidad y efectivamente no almorzó).

Saludos !
