### ISSUE TITLE
Uso de CPU

### ISSUE THREAD

**Issue by rfenzo** [IIC2233/Syllabus#578]
Hola, quería saber si alguien más tiene problemas con el uso de la CPU durante el juego, en mi caso, cuando hay unos 5 spawn de subditos vivos, el computador se queda pegado (con 5 spawns me refiero a que hay como 50 threads de subditos en pantalla), si los voy matando, entonces no se produce este problema. 

Al principio pensé que se relacionaba con el frontend y el manejo de imagenes de cada subdito que hay que ir cambiando y rotando, pero hice que vaya guardando las fotos que se van ocupando, para que si en algun momento otro thread desea la misma imagen rotada, por ejemplo, solo la tenga que buscar en una variable, pero mi problema aún sigue.

Fuí revisando el tiempo que se demora en ejecutar algunos trozos de codigo de mi clase subditos y no parece hacer un problema ahí,por lo que creo que se relaciona directamente con el numero de threads, alguien me puede dar algun consejo?. 

Gracias

**Comment by AmbrosioV** [comment]
A mi no me hace problema tener 50 threads de minions ejecutando, y por alguna razón no me deja hacer más.

**Comment by rfenzo** [comment]
Por si a alguien aún le sirve: 
Noté que el computador colapsaba cuando ocupaba el 25% de la CPU, esto debido a que los threads de python ocupan un solo nucleo del computador (a no ser que se ocupen librerias especiales). Probe cambiando todo mi codigo a QTimers y ahora el programa logra pasar los 25% de la CPU aunque igual se laguea con artos subditos en pantalla, pero al menos no se cae.

**Comment by negutierrez** [comment]
@rfenzo Muchas Gracias! con Qtimers no se me cae el juego
