### ISSUE TITLE
Entrar a  partida

### ISSUE THREAD

**Issue by emena97** [IIC2233/syllabus#578]
Hola! Un par de dudas!
Cuando se esta jugando una partida, se puede meter otro usuario en la mitad??
Y puede alguien jugar solo?

**Comment by jeschuwirth** [comment]
Saludos,

Tu primera pregunta fue respondida en la issue #548

En cuanto a la segunda, si tu programa puede jugar con varios jugadores no debería tener problemas para uno solo, por lo que si se debería poder jugar solo. Esto último no está explícito en el enunciado así que queda a criterio de alumno, por lo que si te complica o lo consideras incorrecto puedes dejarlo escrito en el readme y no va a afectar tu corrección.

Suerte en la tarea!
