### ISSUE TITLE
Imagenes en QtDesigner

### ISSUE THREAD

**Issue by fantinee** [IIC2233/Syllabus#579]
¿Cómo se pueden escalar imágenes en QtDesigner?  logro agregarlas directamente desde QtDesginer pero he estado intentando escalarlas para que calcen con el tamaño de mis labels o del mainwindow y no lo logro :(

**Comment by sebacruzd** [comment]
En la barra de la derecha sale la opción de "Scaled contents". Con esto no te sirve? 
![image](https://cloud.githubusercontent.com/assets/14894992/26764321/a95fcf7c-4932-11e7-9f76-9f86c8709ae0.png)

**Comment by fantinee** [comment]
y para los QPushButton?

**Comment by sebacruzd** [comment]
Esto era un requerimiento en la actividad 11. Si la resolviste tienes la respuesta en el código y si no, en el enunciado hay tips.

**Comment by fantinee** [comment]
pero en la actividad 11 al menos con mi compañero no utilizamos qtdesigner

**Comment by sebacruzd** [comment]
No utilizar QtDesigner, sino que las imágenes estuvieran escaladas al tamaños del PushButton. Se puede hacer con código.

**Comment by fantinee** [comment]
ok gracias!

**Comment by sebacruzd** [comment]
De nada, en todo caso, esto deberías poder encontrarlo en google.

Saludos!
