### ISSUE TITLE
p_permiso de vendedores

### ISSUE THREAD

**Issue by depstein26** [IIC2233/Syllabus#579]
No me queda bien claro que es la p_permiso, es una probabilidad que para un mismo vendedor puede ir cambiando en los días? o en un principio de la simulación se le establece a cada vendedor si tiene permiso o no con probabilidad p_permiso?

Gracias!

**Comment by iqacevedo** [comment]
Hola,

Se establece al comienzo de la simulación. Es justo como dices cada vendedor tendrá o no permiso con probabilidad p_permiso.

Saludos !
