### ISSUE TITLE
Problemas con la instalacion de tabulate/beautifultable

### ISSUE THREAD

**Issue by cnillanes** [IIC2233/syllabus#579]
Hola! Tengo mac y por default está la version 3.8 de python, sin embargo, yo programo en vscode con la version recomendada (3.7).

El problema es que cuando instalo tabulate en la terminal se guarda en la version 3.8 y por lo tanto al intentar importarla en vscode no la reconoce. 

Ya intenté una vez borrando python e instalandolo nuevamente con la versión 3.7 pero sigue guardado por default el 3.8 y no sé que más hacer :( 

Pd: Hay descuentos si la tabla de mostrar estado queda con algunos números corridos? (Pregunto en caso de no lograr dentro de estos dias instalar tabulate en la version 3.7 y por tanto no poder imprimir tablas bonitas en consola)

Gracias desde ya!

**Comment by ignacio-urrutia** [comment]
Hola @cnillanes, primero, para hacer lo que quieres sugiero intentar con el comando pip3.7 

_pip3.7 install tabulate_

o con el siguiente comando para especificar la versión de python

_py -3.7 -m pip install tabulate_

, con eso deberías poder instalar la librería para tu Mac. Si esto no funciona, puedes ordenar la tabla creando una función que te rellene cada columna con " " hasta que tenga un cierto número de caracteres y de esta manera asegurarte que sean de igual largo en cada fila. En todo caso, mientras sea legible y esté relativamente ordenado no debería haber ningún descuento. Mucho éxito con la tarea! :D
