### ISSUE TITLE
Duda sobre .geometry(), diferencias en valores en qt designer y python

### ISSUE THREAD

**Issue by nicomeiser** [IIC2233/syllabus#579]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola tengo un problema con la función .geometry() de los qlables. Cuando intento ver si mi personaje esta chocando con un objeto utilizo el método con qRect que fue explicado en otra issue, pero me falla porque el método geometry no refleja correctamente la posición que tiene mis qlabels que contienen los objetos. La posición en donde están que me indica qdesigner es distinta a la que me marca python. 
Estoy seguro que estoy comparando los mismos labels. 
Adjunto 3 imágenes, la primera es los valores que me da qdesigner para la posición de el qlabel de mas abajo a la derecha), la segunda muestra la posición actual de homero y de el label que esta justo abajo de homero(el qlabel de mas abajo a la derecha), la tercera son primero los valores de la posición de homero, y después la posición de el qlabel que esta abajo de homero 
<img width="437" alt="duda3" src="https://user-images.githubusercontent.com/80775489/120399225-96611980-c309-11eb-9dd9-ad88bb90186f.png">
<img width="370" alt="ahos ssisis" src="https://user-images.githubusercontent.com/80775489/120399298-b395e800-c309-11eb-9883-8f7248535b14.png">

<img width="113" alt="ahora si" src="https://user-images.githubusercontent.com/80775489/120399273-ab3dad00-c309-11eb-91d1-bfded9e3b731.png">

Se puede notar que la posición de homero es similar a la posición que entrega qtdesigner, pero la posición que entrega python del label es mucho menor.

**Comment by catalina-arcila** [comment]
Hola @nicomeiser, puedes subir tu código a tu repo y comentarme bien cual label te complica. Cuando es sobre labels que se mueven te recomiendo crearlos desde el código  no desde Designer. Quedo atenta

**Comment by nicomeiser** [comment]
pregunta noob, subo mi código como uno sube la tarea normalmente?
y adonde escribo los comentarios? aca o en el código?
graciasss

**Comment by catalina-arcila** [comment]
Jajajaj por aquí mejor por si otros estudiantes llegan a tener la misma pregunta y si, súbelo como una tarea normal.

**Comment by nicomeiser** [comment]
No es solo un label, son todos los labels que pueden tener objetos y obstáculos que están en una grilla, y es raro el error porque es como 'acumulativo', es decir el primer label de la grilla(el de mas arriba a la izquierda) muestra que está en la posición (1,1) igual que en qtdesigner pero mientras uno se aleja los labels empiezan a tener una posición menor a la que muestra qtdesigner.
Porque si fuera un valor fijo podría restarlo o sumarlo y quedaría bien, pero no es tan fácil jajjajajaja .
Voy a editar un poco el código porque había 'sacado' la parte del código que fallaba.

**Comment by catalina-arcila** [comment]
Hola, revisé tu código y no veo nada raro. Según la [documentación](https://doc.qt.io/qt-5/qrect.html#intersected) de *Qrect* valores devueltos se desvían de la verdaderas esquinas, te redimiendo revisarlo. A pesar de eso los demás comando de *Qrect* deberían funcionar considerando las coordenadas y tamaños correctos. 😃
