### ISSUE TITLE
Estadísticas

### ISSUE THREAD

**Issue by PhilippePotin** [IIC2233/Syllabus#579]
Que pasa con las estadísticas que tienen que ver con dia de colegio si elijo no hacer este evento externo? 

Gracias

**Comment by rihanuch** [comment]
¡Hola @PhilippePotin !

Si no realizas esta parte entonces no obtienes el puntaje asociado a ese item ni sus subpuntos (no se obtiene ni en estadisticas, ni en el evento, etc.)

¡Saludos! 🍀
