### ISSUE TITLE
Duda sobre funcionalidad del servidor

### ISSUE THREAD

**Issue by Rafoxxa** [IIC2233/syllabus#579]
Quería saber qué mensajes está estrictamente obligado a mandar el servidor y que mensajes no. Por ejemplo el cálculo para saber la cantidad de personas en una sala, no sé si lo debe hacer el cliente o el servidor. Por un lado pienso que si hago que el servidor haga muchos cálculos lo puedo colapsar pero por otro lado siento que el servidor es el encargado de las interconexiones. 
Del enunciado entendí que las operaciones que tiene que hacer el servidor son en relación a al sección 'Amistades' pero con respecto a cosas más simples como cantidad de personas en sala no sé.

**Comment by gatochico** [comment]
Hola! 

Aunque no podemos decirte de forma explícita qué mensajes manda el servidor :crying_cat_face: , en el enunciado se presentan algunas ayudas para hacer la separación. En la sección de "Roles", se indica que el servidor:
   
![image](https://user-images.githubusercontent.com/37161120/70051352-9f0b4f00-15af-11ea-82eb-5f0d31d7baf0.png)

En especial los primeros 3 puntos podrían serte de ayuda, ya que se indican acciones claves a realizar. Sin embargo, si aún tienes dudas con alguna acción, podríamos revisar las tareas del cliente (e inferir que lo que no le pertenezca debe pertenecerle al servidor ):

![image](https://user-images.githubusercontent.com/37161120/70051675-4daf8f80-15b0-11ea-9879-028d585c292a.png)
.

Finalmente, con respecto a tu duda de sobrecargar al servidor, si lo tienes implementado (junto al envio de mensajes con los clientes) de forma óptima no debería haber mayor problema.

Éxito y cualquier duda en concreto nos avisas!
