### ISSUE TITLE
Problema Actividad 2

### ISSUE THREAD

**Issue by ciquezada** [IIC2233/Syllabus#58]
Hola, en la actividad al cargar las lineas del flights.txt el codigo se cae y tira el siguiente error:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 70: invalid continuation byte

este error cambió cuando le quité el tilde a "Concepción", pero no es la idea cambiarlo, ¿Cuál puede ser el error?

(la linea de codigo que lee el archivo es la misma por enunciado: "with open(path, "r", encoding="utf-8") as file:")

**Comment by nmaturana97** [comment]
No se cual es especificamente el problema, pero en la actividad esto mismo le paso a un alumno que no habia pulleado el syllabus y habia copiado desde github a mano los archivos. Si este es tu caso, pullea syllabus y ocupa los archivos de ahi

**Comment by ciquezada** [comment]
Esa fue la solucion, Gracias!
