### ISSUE TITLE
Error verificación de uso de funciones de dcciudad

### ISSUE THREAD

**Issue by VicenteIgnacioSotoGonzalez** [IIC2233/Syllabus#58]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Buenas tardes, hoy durante el día mi código funcionaba bien en los métodos que involucraban importar funciones de dcciudad, sin embargo realice Git pull en Syllabus para actualizar los tests cases, copié los archivos nuevos de la T1 en mi carpeta personal, incluyendo un "nuevo" dcciudad. Sin embargo ahora me lanza el siguiente error (foto adjunta). Gracias de antemano.

![error test case tarea 1](https://github.com/IIC2233/Syllabus/assets/162501853/1841b319-53ee-40e8-b32d-e1d995a15599)

**Comment by Hernan4444** [comment]
Hola @VicenteIgnacioSotoGonzalez 

Podrías subir tu código a **tu repositorio privado** para poder verlo y entender por qué se gatilla el error. Justamente se actualizaron los tests porque había un error con los `imports`, pero claramente esta "solución" gatilló otro error que debemos solucionar.

Avísanos por aquí cuando el código ya esté disponible para verlo y encontrar la solución en el tests.

Saludosヾ(＾-＾)ノ

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Hola! Ya se encuentra disponible el código, gracias de antemano!

**Comment by Hernan4444** [comment]
Hola @VicenteIgnacioSotoGonzalez 

Ahí revisé la situación, el problema claramente era con la solución que habíamos confeccionado ayer en los test. Lo primero que hacía el tests era buscar si hacías `import dcciudad` o `from dcciudad import ...` y luego se encargaba de validar si llamabas a la función correspondiente. No obstante, la solución que habíamos subido no hacía un **O** sino un **Y**, es decir, que el código tuviera tanto un `import dcciudad` y `from dcciudad import ...`... y eso generaba el error en tu caso.

Acabo de subir una nueva versión que, probando con tu código y con nuestra solución, validamos que ahora si funcione con un **o**, es decir, si alguien hace  `import dcciudad` o `from dcciudad import ...`, el código no deberá tirar error por ese motivo.

¡Muchas gracias por notificar esto!
Saludosヾ(＾-＾)ノ

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Perfecto! Muchas gracias, saludos!

**Comment by Hernan4444** [comment]
De nada 😄 

Saludosヾ(＾-＾)ノ

ps: por si acaso, te recomiendo mucho revisar esta issue 🙈 
* #65
