### ISSUE TITLE
Porcentaje de extinción

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#58]
#En el enunciado se dice que hay que mostrar el porcentaje de extinción de un incendio y dice que es la razón entre los puntos de poder extintos y los puntos de poder que habían al principio del incendio, pero al principio del incendio no había nada o no se sabe, ya que en ninguna parte aparece un área o radio inicial.

**Comment by rpalmaotero** [comment]
Hola, del enunciado:

> El porcentaje de extinción se define como la razón entre los puntos de poder que han sido extintos por los recursos y los puntos de poder del incendio **desde** que se inició.

Son los puntos acumulados desde el inicio. Tal como dices, no tendría sentido que fueran los iniciales.

**Comment by jorgeriesco** [comment]
puntos acumulados desde el inicio hasta ese preciso intante? osea podria dar porcentaje mayor a 100. Ademas pensando en que puden participar otros recursos que tambien ayudaron a extinguir

**Comment by rpalmaotero** [comment]
@jorgeriesco si te da mayor a 100 implica que alguna vez estuvo en 0 puntos de poder, por lo que el incendio se encuentra apagado. Revisa la definición de incendio apagado en la sección 4.2.5 del enunciado.
