### ISSUE TITLE
Duda descuento por cambio de líneas 

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#58]
Hola, no entendí bien a qué se refiere en Descuentos.md cuando dice que se permite cambiar hasta 20 líneas de código. A qué se refiere con cambiar las líneas del código?

**Comment by ajuanchuto** [comment]
¡Hola!

Significa que al momento de mandar a recorregir tu tarea, puedes optar a modificar hasta 20 líneas de tu código (las que tú quieras, pero tienes que especificar en la recorrección cuales son) para solucionar un error y optar por obtener más puntaje. Sin embargo, por cada línea de código que modifiques, esta va a tener una penalización de puntaje según la fórmula que te dan en `Descuentos.md`.

Por ejemplo si en tu tarea tenía el siguiente código:
```
1. def imprimir_algo(texto):
2.      print(texto)
3. 
4. imprimir_algo("hola")
```
 Y luego en la recorrección quieres modificar la línea 4 porque no tenía que imprimir "hola" y ahora quieres que imprima "chao", entonces eso cuenta como una línea modificada y todavía te quedarían 19 líneas para cambiar si así lo quisieras.

Espero haber aclarado tu duda 😄

**Comment by tqmbanados** [comment]
Hola! Agrego que también puedes incluir las líneas que deseas cambiar en el README, que se envía un día después.

**Comment by JuanpaBC** [comment]
_grazie mille_

**Comment by CGR0** [comment]
Hola! algo que no me queda claro es que si quiero hacer cambios de linea tengo que rellenar el formulario para que me corrijan otro commit o simplemente lo especifico en el README??

**Comment by tqmbanados** [comment]
Hola @CGR0! Basta con especificar los cambios en tu readme :) Debes especificar el archivo y el número de la línea, e incluir la línea original y la línea por la cual la cambiarás.

**Comment by CGR0** [comment]
Ya buenisimo! Muchisimas gracias
