### ISSUE TITLE
Dudas sobre máximo de caracteres por línea [PEP8]

### ISSUE THREAD

**Issue by DonJavi-538** [IIC2233/syllabus#58]
Hola! mi duda es algo simple ¿dentro de los 100 caracteres permitidos por línea se cuentan los espacios producidos producto de la tabulación?

De antemano muchas gracias!

**Comment by jmwielandt** [comment]
Hola!

Efectivamente, se cuentan las indentaciones y todos los caracteres. Los editores permiten configurar una "regla" que marca una determinada cantidad de caracteres, todo lo que sobresalga cuenta como violación a la restricción de pep8.

![imagen](https://user-images.githubusercontent.com/37153467/63139418-471eed00-bfac-11e9-85ac-92147dad6e0a.png)

La tengo configurada en 80 caracteres de momento, pero ese es un ejemplo de cómo se ve en vscode. Ahí las líneas 4 y 6 se pasan del máximo de caracteres.

Incluso aquí, todas estas líneas serían penalizadas.
![imagen](https://user-images.githubusercontent.com/37153467/63139792-8a2d9000-bfad-11e9-94f9-cf6757df23a4.png)


Saludos!

**Comment by DonJavi-538** [comment]
Muchas gracias!

**Comment by DonJavi-538** [comment]
Perdón por las molestias, pero que configuración o extensión usaste para poder limitar el máximo de caracteres? =)

**Comment by jmwielandt** [comment]
Hola!

No es ninguna extensión, te mando capturas de cómo configurarlo.

1. File > Preferences > Settings
2. Haces click en este ícono que sale arriba a la derecha (en otras versiones de vscode es un  `{}`:
![imagen](https://user-images.githubusercontent.com/37153467/63142372-8bfc5100-bfb7-11e9-9251-82625c47f2a4.png)

3. Pones esta configuración (eso es una flecha, aunque no pudo quedar peor 😅):
![imagen](https://user-images.githubusercontent.com/37153467/63142435-c239d080-bfb7-11e9-8ca0-35c0c846132f.png)

Este es un método de configuración de editores de código bastante común, sé que al menos vscode y sublime text 3 lo usan. Si buscas en google, verás que puedes hacer maravillas como controlar que te cierre automáticamente los paréntesis, comillas, tags de html, que te quite los espacios sobrantes al final de las líneas cada vez que guardas, entre otras cosas.

Saludos!

PD: no cierres esta issue, puede servir al resto de tus compañeros. Nosotros la cerraremos cuando sea oportuno.

**Comment by Alonsortega** [comment]
Consulta, si tengo un archivo que contiene listas con información que luego importaré al programa principal, ¿aplica la regla de los 100 caracteres?

**Comment by jmwielandt** [comment]
Hola!

Si es un archivo de código, aplica.

Saludos~

**Comment by DanielaCorral** [comment]
Hola, otra consulta: ¿la regla de los 100 caracteres también aplica a los comentarios? o solamente al código "ejecutable"?

**Comment by Drpinto1** [comment]
Hola!
Citando a [PEP8](https://www.python.org/dev/peps/pep-0008/#id19):

> For flowing long blocks of text with fewer structural restrictions (docstrings or comments), the line length should be limited to 72 characters.

> Some teams strongly prefer a longer line length. For code maintained exclusively or primarily by a team that can reach agreement on this issue, it is okay to increase the line length limit up to 99 characters, provided that comments and docstrings are still wrapped at 72 characters.

tl;dr: Sin importar el número de caracteres máximos por línea para código, el máximo para los cometarios es de __72 caracteres__

**Comment by DanielaCorral** [comment]
O sea, para confirmar, la penalización no incluye comentarios, mientras estos por sí solos no excedan los 72 caracteres por línea?
