### ISSUE TITLE
Alternativa al procedimiento para dejar de seguir a un usuario

### ISSUE THREAD

**Issue by Jairuru** [IIC2233/syllabus#58]
Puedo listarle en pantalla al usuario los user de quienes sigue, y que elija quien quiere dejar de seguir? Es una forma más amena de manejar este punto que como lo señala el enunciado

**Comment by jeschuwirth** [comment]
Hola @Jairuru,

Si puedes hacerlo de esa manera :) 

Es importante comentar que como contradice al anunciado, pero es muy justificable, debes citar esta issue en tu README y así evitas tener problemas.

Suerte!
