### ISSUE TITLE
Error en Test Case T1 test_pieza_explosiva.py

### ISSUE THREAD

**Issue by munonzito** [IIC2233/Syllabus#58]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](https://github.com/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, en el archivo de test **test_pieza_explosiva.py,** ¿Puede ser que el **test_pieza_H_celda_derecha** está erróneo? 

La columna entregada es 9, la columna de la pieza explosiva es 3, y el alcance es de 4. Y si entendí bien el enunciado, la pieza no debería ser capaz de alcanzar la columna 9 (ya que su alcance no se lo permite), y la función **verificar_alcance** debería entregar **False**.

Sin embargo, el test case **test_pieza_H_celda_derecha** toma el valor **True** como correcto.

Gracias por su ayuda.

**Comment by ManuelV03** [comment]
Hola, el método "verificar alcance" que está testeando ese test case no toma en consideración el número de alcance de la bomba, sino que solo revisa si la bomba está en la misma fila (ya que la pieza es de tipo "H") por lo que el test case está correcto. Avísame si se respondió tu duda.

**Comment by munonzito** [comment]
Si, muchas gracias.
