### ISSUE TITLE
¿Es posible realizar cosas diferentes al enunciado para mejorar el flujo del juego?

### ISSUE THREAD

**Issue by bernirosas** [IIC2233/Syllabus#58]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! En el enunciado aparece que luego de descubrir un sector y ganar, se debe volver al menú de juego, sin embargo, al probar el flujo del juego con mis amigos, esta opción irrumpía notablemente en el juego ya que cada vez había que volver al a presionar 1 para volver a descubrir sectores y luego la coordenada seleccionada. Para solucionar este problema, decidí que si ganaba el jugador, entonces automáticamente le pedía otra coordenada (existiendo la opción de volver al menú de juego). ¿Es esto un problema?
Saludos

**Comment by victoriaatria** [comment]
Hola! Aunque tienes razón que a veces interrumpe el flujo del juego, debes seguir siempre lo que dice el enunciado. Es decir, cuando se descubre un sector sin bestias, deberás mostrar el tablero actualizado y el menú de juego nuevamente. Esto sirve para facilitar la corrección de las tareas, entre otras cosas.

Saludos!

**Comment by MatiasOssul** [comment]
Berni, yo hice lo mismo, lo encontré mas intuitivo. Mientras le des la opción de salir o elegir casilla en el mismo input según yo no debería haber problema.

**Comment by bernirosas** [comment]
> Hola! Aunque tienes razón que a veces interrumpe el flujo del juego, debes seguir siempre lo que dice el enunciado. Es decir, cuando se descubre un sector sin bestias, deberás mostrar el tablero actualizado y el menú de juego nuevamente. Esto sirve para facilitar la corrección de las tareas, entre otras cosas.
> 
> Saludos!

Ok gracias!
