### ISSUE TITLE
Duda lectura Fechas csv

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#58]
¿Por que al leer el archivo de users la fecha no me sale como "dd-mm-yyyy"? Si no que sale: "yyyy-mm-dd"

**Comment by nmaturana97** [comment]
Probe un poco y pareciera que excel traduce las fechas y las pone siempre como dd-mm-yyyy. Para que tengan cuidado al momento de usar las fechas y revisar en excel los archivos.

**Comment by nmaturana97** [comment]
De todos modos, queria saber como probaran ustedes las fechas.

**Comment by rihanuch** [comment]
según lo que tengo entendido tienes que hacerle strpftime o algo así y después usar (%Y-%m-%d) algo así, pero ni idea de lo que te ocurre mi desconocido compañero 😞

**Comment by nmaturana97** [comment]
jaja, prueba. guarda un archivo csv con alguna fecha  (%Y-%m-%d) y luego abrelo en excel. Aparece al reves.
