### ISSUE TITLE
Duda con PEP8 en VSC

### ISSUE THREAD

**Issue by dani-sschlack** [IIC2233/syllabus#58]
Al abrir preferences ->settings -> settings.json, me aparece esto previamente escrito:
[
<img width="940" alt="Captura de Pantalla 2020-08-19 a la(s) 16 04 04" src="https://user-images.githubusercontent.com/69522104/90684375-1401e000-e236-11ea-8e95-88578a9febf3.png">
](url)

Mi duda es si tengo que borrar todo o solo algo puntual (en ese caso qué) y en que parte agregar las 2 lineas que se mencionan en la issue de utilidad/PEP8.

**Comment by igbasly** [comment]
Hola @dani-sschlack :v:

Ese es el archivo con las preferencias del usuario e VSCode, por lo tanto, no es recomendable que borres su contenido. 
Ahora, puedes ver si lo recomendado en la issue #22 altera alguna de las líneas existentes, en cuyo caso puedes simplemente modificarla, o solo agrega la nueva configuración dentro del diccionario como nuevos atributos.

Avísame si logras configurarlo correctamente o si se genera algún problema. :smile:

**Comment by dani-sschlack** [comment]
Holaaaa🤩🤩🤩, me resulto al poner las dos líneas al final sin borrar nada, lo guarde y listooo.
<img width="1627" alt="Captura de Pantalla 2020-08-19 a la(s) 22 55 00" src="https://user-images.githubusercontent.com/69522104/90711639-3ebc5a80-e26f-11ea-8a4b-38c6d2875008.png">
Así me quedó por si acaso.
Muchas graciaaaaas!!!👌🏻💯🥳
