### ISSUE TITLE
Duda sobre uso de try-except 

### ISSUE THREAD

**Issue by Yeps3nM** [IIC2233/Syllabus#58]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Es posible para el manejo de errores en el menú utilizar try-except? Explicando en el readme cuál es su función. 

Gracias!

**Comment by vgalfaro** [comment]
Hola! no es posible ocupar try-except debido a que aún no se ven en los contenidos, te sugiero revisar #10, ahí se especifica que se pueden ocupar los contenidos hasta la semana 3. Saludos!
