### ISSUE TITLE
¿Destrucción del DCCowork?

### ISSUE THREAD

**Issue by Juaco97** [IIC2233/syllabus#58]
Cuando se ataca a una civilización y tiene construido un DCCowork, ¿en qué parte del orden del ataque se destruye? El punto 4.1 menciona solo el orden de: murallas -> soldados -> cuartel -> trabajadores -> centro urbano, pero nunca qué pasa con DCCowork y los ayudantes cuando se trata de defensa.

**Comment by BFFV** [comment]
Hola!
En la sección de ataque y defensa (4.1) se menciona que el DCCowork NO participa en la defensa, por lo que ni el edificio ni los ayudantes aportan en las fórmulas (a menos que cuentes los bonus que tiene el DCC en sus fórmulas de ataque y defensa). Es por esto que el DCCowork y los ayudantes nunca son destruidos, a menos que la civilización sea derrotada y algunos ayudantes mueran al no querer pasarse al bando ganador (explicado también en la sección 4.1).
