### ISSUE TITLE
Duda Entidades

### ISSUE THREAD

**Issue by CataLebe** [IIC2233/Syllabus#58]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Holaa, en el enunciado de la tarea nos hablan de entidades. Y en el readme aparece que valen un 15% de la tarea. En una issue se habla de esto y le respondieron a la persona que hizo la pregunta que no es necesario trabajar con clases, que solo es una recomendación. Entonces quería saber qué es lo que específicamente se evalúa en esa parte del readme.
No he usado clases, y la otra issue me dejó tranquila, pero ahora que veo el readme me volvió a entrar la duda.

Muchas gracias
![Captura de pantalla Issue entidades](https://user-images.githubusercontent.com/81182364/131606560-ac4ac2d4-99f2-40f3-a34e-0214df913ebe.png)

**Comment by nanglada** [comment]
Hola CataLebe! 
Efectivamente, no es necesario usar clases para esta tarea (aunque si es recomendado). Ese 15% que aparece en el README se refiere a que se revisa si el funcionamiento de los usuarios, las publicaciones y los comentarios es correcto. Para saber específicamente que se evalúa en cada uno (y como se compone este porcentaje), te recomiendo que vayas al excel de distribución de puntaje de la T0 (que mandaron por Canvas hace unos días). 
Igualmente, te adjunto una foto con esa parte de la distribución para que te quede bien claro. 
Mucha suerte con tu tarea! 🎉
![entidades](https://user-images.githubusercontent.com/62104901/131607103-e1197bfb-2055-4d8c-973d-90a97dddcca1.PNG)

**Comment by fernandosmither** [comment]
Para dar mis dos centavos, cuando se hable de "entidad", lo **recomendado** es tratarlo con clases, sin embargo no son necesariamente lo mismo. Lo comento porque un estudiante tenía la misma confusión en el canal de discord. 😄
