### ISSUE TITLE
Duda sobre programación funcional / contenidos T3

### ISSUE THREAD

**Issue by Jbalbin1** [IIC2233/Syllabus#580]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo una duda en cuanto a los marcos de la programación funcional, y qué se puede hacer en la tarea. Para sino cambiar los códigos que implican esto :). En mi caso, lo que me genera duda es si es que es legal por ejemplo, crear al comienzo de las funciones un diccionario que permite almacenar los nombres de pizzas con algún atributo o la pizza en sí. O en otros casos, inicializo simplemente una lista vacía en la que luego almaceno objetos o cosas. Gracias.

**Comment by MaxAl100** [comment]
Hola! En esta tarea no se pide explícitamente usar sólo programación funcional, aunque es más ideal por la velocidad que esta forma de programar facilita. 
Lo que mencionas sí es legal, pero puede fallar en términos de velocidad cuando hay grandes cantidades de archivos, para que lo tengas en consideración. 
Buena suerte con este último trecho de la tarea!
