### ISSUE TITLE
get_image_plte

### ISSUE THREAD

**Issue by josejimenezp** [IIC2233/syllabus#580]
Hola, quería saber para qué hay que ocupar la función get_image_plte. Hice los pasos que decía el documento para transformar una matriz rgb a png pero no sé si está bien hacerlos a mano o había que usar esa función en algún momento, ya que se me guardó cualquier cosa de imagen :(

**Comment by iqacevedo** [comment]
Hola ! 
De ese archivo que les entregamos sólo tienen que ocupar la función get_pixels. Así que no te preocupes por get_image_plte.
Saludos !
