### ISSUE TITLE
Elementos a desplegar en consola

### ISSUE THREAD

**Issue by caespinoza5** [IIC2233/Syllabus#580]
Quería saber si sólo debemos desplegar las estadísticas de cada simulación, o hay que simular cada evento y situación en el momento que ocurre. Lo segundo lo veo bastante tedioso, considerando que por 80 días académicos (aprox) llegan 280 personas al día, lo que se traduce en muchos prints.

**Comment by GustavPrudencio** [comment]
si te refieres a la parte de escenarios, no, no debes desplegar las estadísticas de cada simulación.

saludos.

**Comment by caespinoza5** [comment]
Gracias! Pero me refería a al momento de ejecutar una simulación, no un escenario. Mi pregunta va más orientada a si hay que desplegar cada evento (A modo de ejemplo):
x llega a la universidad.
y llega a la universidad. 
x compra snack. 
z coloca su puesto.
Lo anterior durante 80 días despliega demasiada información y se demora bastante en ejecutar. Mostramos todos los eventos o solo las estadísticas al momento de realizar una simulación?

**Comment by Jiparavich** [comment]
x2

**Comment by caespinoza5** [comment]
Ojalá puedan responder pronto la pregunta! Gracias!

**Comment by felipecr00** [comment]
me sumo a la duda!
