### ISSUE TITLE
Duda nombre imagenes de carpeta sprites

### ISSUE THREAD

**Issue by aagodoy1** [IIC2233/syllabus#580]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holaa, en la carpeta que subieron, ocurre que por ejemplo, en el caso de homero, la imagen down_3, es él QUIETO, mientras que para lisa, down_3 es ella caminando, y down_1 es donde se encuentra quieta. Puedo cambiar eso y poner el mismo formato para todos los personajes ?

**Comment by MatiasDuhalde** [comment]
Hola @aagodoy1 !

En un principio, no se podría, por la siguiente razón: en el enunciado les pedimos ignorar la carpeta completa de sprites, por lo que cualquier cambio de nombre que vayan a realizar, se perdería cuando clonemos sus repositorios para revisar la tarea.

Como alternativa, te puedo recomendar predefinir en variables las rutas de los sprites correspondientes a cada estado. Para esto, podrías definir el siguiente diccionario en tu archivo de parámetros:
```python
SPRITES_PERSONAJES = {
    "lisa" : {
        "down": {
            "standing": path.join("Sprites", "Personajes", "Lisa", "down_1"),
            "moving":  [path.join("Sprites", "Personajes", "Lisa", "down_2"), path.join("Sprites", "Personajes", "Lisa", "down_3")]
        },
        "up": {
            # ...
        },
    # ...
    },
    "homero" : {
        "down": {
            "standing": path.join("Sprites", "Personajes", "Homero", "down_3"),
            "moving":  [path.join("Sprites", "Personajes", "Homero", "down_1"), path.join("Sprites", "Personajes", "Homero", "down_2")]
        },
        "up": {
            # ...
        },
    # ...
    }
}
```

De esta manera podrías ordenar los sprites de mejor manera, y no dependerías de los números para obtener el sprite del personaje parado.


Éxito con la tarea! :sparkles:
