### ISSUE TITLE
Formato log txt

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2233/Syllabus#580]
Hola , tengo una duda en las dos ultimas aristas del formato de escritura,es decir,
Entidad(es) afectada(s) | descripcion de la entidad
Ya que por ahora estoy printeando el nombre del adulto y los niños cuando estos se ven afectados el tema es que para la cantidad de niño y nombrar sus nombres hace que el programa empiece a tardarse
Ejemplo:
Rick,morty,homero,bart,lisa | Rick(adulto)

Se puede printear en estas aristas la clase de la entidad, es decir,
Adulto - Niños | Adulto

**Comment by nachocontreras** [comment]
Hola!

En `Entidad(es) afectada(s)` se debe colocar un listado de entidades afectadas y en `Descripción de la entidad` se debe colocar el nombre de la entidad generadora del evento. 

Por lo tanto, se puede poner la clase de la entidad en esas aristas (lo que plantea el enunciado), pero en la descripción debes poner el nombre de la entidad, no de la clase.

Éxito 😄 !

**Comment by Jj1martinez** [comment]
Por ejemplo si un cliente se sube a una atracción,  las entidades afectadas serán: Cliente/Atracción pero en la descripción solo debe ir el nombre del Cliente? podría poner ambos para poder identificar a que atracción se subió? o no es necesario

**Comment by nachocontreras** [comment]
Sí, puedes poner ambos para identificar a que atracción se subió.
