### ISSUE TITLE
Largo de las lineas

### ISSUE THREAD

**Issue by AndresLaRiva** [IIC2233/syllabus#580]
Pequeña duda, la regla de no mas de 100 caracteres hace referencia solo a una linea particular o a todo el codigo? Con esto me refiero a que si por ejemplo, existen muchas indentaciones y me paso de la "columna 100" estaria fallando a la regla??

**Comment by jamigone** [comment]
Hola! Para la T0 tenía la misma duda y recuerdo haber leído en una issue que los 100 carácteres consideran las identaciones, por lo que sí se estaría fallando la regla.

**Comment by aljara97** [comment]
Hola @AndresLaRiva 

El límite de 100 caracteres por línea considera a todas las líneas de tu archivo, independiente de si son comentarios, contienen identaciones o espacios. Por tanto, **ninguna debe sobrepasar la columna 100**. Para saber si cumples con este límite te recomiendo habilitar la "regla" de tu editor de texto.

Éxito en lo que queda 🧙‍♂️
