### ISSUE TITLE
Problemas con QLabels y parents

### ISSUE THREAD

**Issue by fernddevidts** [IIC2233/Syllabus#580]
Hola!
Tengo un problema. Cuando instancio clases como las de los edificios o súbditos o los campeones y les doy como parámetro parent la MainWindow, ejecuto el programa y todos aparecen cortados a 1/3. Es como que apareciera solo 1/3 del QLabel porque hasta cuando le pongo bordes, éstos no aparecen (por eso concluí que no es un problema de escalar el tamaño de la imagen). Sin embargo, cuando instancio esas clases y les doy como parámetro parent=None, aparecen enteras en mi MainWindow.
He buscado en todas partes y no logro encontrar cómo solucionar el problema.

**Comment by hanavarrete** [comment]
podrías escribir en pseudo-código como estás instanciando estos objetos?

**Comment by fernddevidts** [comment]
En mi main window, cuando inicio el juego, dependiendo de qué campeón apreté, lo instancio, dándole como parámetro parent=self (mainwindow) y el color del equipo. Los súbditos los instancio en el inhibidor y les doy de parámetro parent el parent del inhibidor (que también es el mainwindow). Los edificios los instancio dándoles de parámetro el parent (mainwindow) y el color del equipo.

**Comment by hanavarrete** [comment]
creo que el error puede ser porque estás dandole como parametro el parent al instanciar el objeto, y luego, al ponerlos en tu lista de objetos ocupas el método de setParent. Puedes tratar sin hacer el setParent y dime si te vuelve a funcionar?

**Comment by fernddevidts** [comment]
Aaah si pero sin hacer el setParent ya no aparece nada en la pantalla D:

**Comment by iqacevedo** [comment]
Hola,

Intenta con crear un pixmap después de llamar al `super().__init__()` y setearselo al label escalando su contenido. Avísanos si te resulta (sería en vez de pasarle la imagen directamente al súper)

Saludos !

**Comment by fernddevidts** [comment]
@iqacevedo lo probé con los edificios y no funciona. ¿Será mejor no entregar el parent como parámetro y hacer setParent al agregar la entity a la ventana del juego? 
Mi único problema con esa solución es que no sabría cómo enviarle señales al parent desde otras clases ya que no está definido desde un comienzo, sino que se define al agregarse.

**Comment by hanavarrete** [comment]
creo que deberías hacer el parent como parametro (pero no almacenarlo, ya que sería programación circular) y no hacer el setParent. Puedes basarte en el ejemplo de la tarea para poder hacer esto (incluído el como manejar las señales)

**Comment by iqacevedo** [comment]
También puedes intentar darle el tamaño que le das  al label de tus widgets(como el de edificio) en vez de ingresarlo como un valor predefinido (pusiste 100,100 intenta usar el tamaño que le entregas a esa instancia).

Pero como dice @hanavarrete vuelve a leer el ejemplo, ya que es un código muy simple pero que funciona, con algo de ahí podrías solucionar tu problema.

**Comment by fernddevidts** [comment]
Ya, le puse parent de parametro a todo y no lo guardé nunca. Sin embargo, ahora tengo el problema de que no aparecen mis entities en el juego. Llamé al método show() de los labels y de los widgets pero no sé en qué me estoy equivocando :(((((

**Comment by rrhurtado** [comment]
Hola, entendiendo que lo que más demora al programar son esos 'bugs', entre que aparezcan recortados a que no aparezcan es preferible lo primero. Así puedes seguir avanzando y no quedar estancado, solo recuerda dejar una acotación a las funcionalidades parciales en el README.

Saludos
