### ISSUE TITLE
Duda con respecto al parent en un QThread

### ISSUE THREAD

**Issue by mauriquan** [IIC2233/syllabus#581]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, tengo una duda con respecto al uso de ```parent```, ya que en los contenidos, específicamente en el ejemplo de la comida (semana 7, cuadernillo 1) hacen lo siguiente (resumido):

```python
class Comida(QThread):

    def __init__(self, parent, ...):
        super().__init__()
    ...

    self.label = QLabel(parent)
    ...

class MyWindow(QMainWindow):
    ...

```
Mientras que en mi tarea tengo algo así:
```python
class Objeto(QThread):

    def __init__(self, parent, ...):
        super().__init__()
        ...
        self.label = QLabel(parent)
        ...

class Juego(QObject): #Clase donde hago los cálculos necesarios en el backend
    ...

```
A simple vista es lo mismo, sin embargo creo que el error podría estar en que ```Juego``` hereda de ```QObject```, mientras que ```MyWindow``` hereda de ```QMainWindow```.
Si corro el código tal y como lo escribí anteriormente me arroja el siguiente error:

*TypeError: arguments did not match any overloaded call:
  QLabel(parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'Juego'
  QLabel(str, parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'Juego'*

**Comment by MatiasDuhalde** [comment]
Hola @mauriquan !

El error tiene un poco que ver con lo que mencionas, pero hay un detalle extra:

Los objetos de tipo `QLabel` sólo pueden recibir otros elementos visuales como parent. Por ejemplo, pueden recibir objetos de la clase `QMainWindow` (como en el ejemplo), `QWidget`, `QPushButton`, o incluso otro `QLabel`.

En tu código, si instancias el QThread de la siguiente manera dentro de la clase Juego:
```python
mi_thread = Objeto(self)
```
Le estás pasando el mismo backend como argumento (la clase Juego, que hereda de `QObject`). Un QObject no corresponde a un objeto visual de PyQt, por lo que no puede tener otros objetos visuales como children.

Por lo tanto, debes cambiar el enfoque que le das a tu programa, y para esto, puedes seguir alguna de las siguientes alternativas:
- La más recomendada, es pasar el label que estás intentando definir en el QThread al frontend, dentro de algún objeto visual, como podría ser una ventana. Así, puedes hacer que el thread se encargue de "manipular" este label por medio de señales.
- En lugar de pasarle "self" como argumento, pasarle la **instancia** de la ventana al thread (o la instancia que quieres que quede como parent del label). De esta manera, el label tomará como parent a un objeto visual en lugar de un QObject. Ten cuidado con esta opción, dado que puede enredar la arquitectura, y hacer borrosa la diferencia entre backend y frontend.
- Integrar el thread en la ventana, tomando un enfoque similar al del ejemplo de los contenidos (instanciar y usar el thread dentro de un elemento visual). De esta manera, el label podría estar instanciado dentro del thread, tomando la ventana como parent, y funcionar correctamente. Nuevamente, ten cuidado con esta opción, debido a que si aplicas lógica en el frontend, puedes ser penalizado por no hacer separación entre frontend y backend, o no aplicar señales donde corresponda (te recomiendo revisar los ítems morados en la distribución de puntajes).

Finalmente, recuerda que si lo que buscas es generar una acción periódicamente, probablemente te sirva o acomode más la clase QTimer! Te recomiendo echarle un ojo a cómo quedaría la implementación usando QTimer en vez de QThreads!


Mucho éxito en la tarea, y si sigues con dudas, pregunta acá! :cowboy_hat_face:
