### ISSUE TITLE
valores en matriz G

### ISSUE THREAD

**Issue by josejimenezp** [IIC2233/syllabus#581]
Holaa! En la matriz G me quedan valores [0, 255, 360]. El problema es que el 360 no puedo dejarlo en un byte como lo pide el enunciado entonces tengo que dejarlo en 2 bytes para todos y me resulta esta imagen fea D:

**Comment by josejimenezp** [comment]
![editado](https://user-images.githubusercontent.com/48298035/59807661-df5b6700-92c6-11e9-9f94-0ec24cbeb7e4.png)

**Comment by jeschuwirth** [comment]
Hola!

sigo mirando código, pero por ahora encontré un error algo grande, el enunciado no explica en orden las cosas que hay que hacer, sino que al final explica en que orden hay que hacerlo:

![image](https://user-images.githubusercontent.com/37160256/59813210-b5ae3a00-92de-11e9-815b-ac41fdc8fc9e.png)

Ojalá eso te ayude, de todos modos voy a mirar un poco más la tarea para ver si eso arregla todo

**Comment by josejimenezp** [comment]
Lo hice en el orden de esa parte :(

**Comment by jeschuwirth** [comment]
Primero conviertes a escala de grises, luego aplicas la cota y por último la matriz gradiente, haces el paso 3 después del 5.

Si cambias lo anterior tu tarea me entregó esto:
![image](https://user-images.githubusercontent.com/37160256/59813446-821fdf80-92df-11e9-8dbb-f06d97f6e79d.png)

Corta la imagen antes de lo que debería, que ya es un problema de manejo de bytes probablemente, pero se nota que esta funcionando, a todo esto felicidades por como manejaste la matriz convolución, se entendió muy rápido tu código.

Como parece que debería funcionar te dejo con tu tarea, pero exito :D

**Comment by josejimenezp** [comment]
Vine para darte las gracias, ahora tengo el filtro perfect :D

**Comment by jeschuwirth** [comment]
genial :D
