### ISSUE TITLE
Delay para atacar

### ISSUE THREAD

**Issue by IriSalazar** [IIC2233/Syllabus#581]
buenisimas noches, tengo el siguiente problema.
cuando quiero que mi campeon vaya a atacar a alguien y le hago click, aparece repentinamente en la posicion que esta en el rango de ataque, y no "camina" hasta alla por asi decirlo. tengo metido en el codigo de la clase campeon una funcion perseguir_enemigo, con el tema de los vectores normalizados, y llamo a la funcion desde el main window... pero no pasa. y cuando le meti un print para ver que onda, hace todo el proceso interno de moverse (imprime estoy moviendome a x,y posicion) PERO no mueve el label de posicion en posicion... (le estoy seteando la posicion haciendo campeon.posicion = (x,y)
aparte tengo una funcion que chequea si mi enemigo esta o no en mi rango de ataque, denominemosla estoy_adentro para este ejemplo. 
se me ocurre que esto pasa porque cuando llamo a la funcion perseguir_enemigo lo hago usando un while:   _while estoy_adentro is False:_ perseguir_enemigo .

altamente probable que algo de lo que estoy haciendo este mal 👍 , pero no se exactamente que.
ayuda?

**Comment by DiegoAndai** [comment]
Hola! supongo que perseguir_enemigo está en el backend, cómo estás enviando los datos al frontend para que se actualicen? mediante señales? 

En que momento llamas al método move()?

**Comment by IriSalazar** [comment]
Si, esta en el backend, y si tambien a las señales!
hago move justo depues de poner campeon.posicion = (x_anterior + recorrido_x, y_anterior + recorrido_y). pero probe poniendole un # para ver si cambiaba algo, y tampoco hacia nada. y si no hago campeon.posicion la imagen nunca llega a destino a pesar del move. 
No me habia dado cuenta que habias contestado, perdon por tardar!

**Comment by hanavarrete** [comment]
probablemente no estás haciendo el move y manejo de señales como corresponde al cambiarse cada vez la posición. Si revisas el ejemplo que subimos a la carpeta de la tarea, cada vez  que se cambia la posición se envía una señal al frontend para que este mueva el label la cantidad correspondiente. Si tu personaje se teletransporta y no "camina" hasta allá es el motivo más rápido que se me ocurre, pero también podría ser por algún bug en tu código al momento de manejar el cambio de posición. Intenta viendo el ejemplo y revisando si estás mandando la señal cada vez que se cambia un poco la coordenada. Saludos!

**Comment by berrazuriz1** [comment]
Puede ser tambien que no le hayas puesto un time.sleep(), o algo por el estilo, y por eso aparece en la posición de destino de una.

**Comment by IriSalazar** [comment]
Lo del sleep definitivamente no es.. porque le puse un print adentro de la funcion, y la imprime la cantidad de veces que se mueve, esperando esos segundos. pero igual aparece magicamente del otro lado jaja. voy a revisar lo de las señales, gracias a todos!

**Comment by iqacevedo** [comment]
@IriSalazar lo que dice hugo debería solucionar tu problema, si no se arregla  puedes ver donde ocupas un sleep o wait de más que produzca el delay (fíjate que al actualizar la imagen o mover el campeón no se haga uno de estos de más) 

Saludos !

**Comment by rrhurtado** [comment]
Hola, en casos como estos es útil ir probando el mover desde la funcionalidad más básica (hardcodeando el número de píxeles que se mueve) y poco a poco ir añadiendo lógica para determinar en qué parte del código está el error. 

Saludos

**Comment by IriSalazar** [comment]
Gracias a todos! Si llego a encontrar el problema les cuento que era, pero aun no se que es. Voy a intentar hacer lo que dijiste @rrhurtado .
