### ISSUE TITLE
Mostrar estado durante la simulacion de competencia

### ISSUE THREAD

**Issue by camilapavesi** [IIC2233/syllabus#581]
Hola! :)
Cuando simulo las competencias diarias todo ocurre automáticamente, por lo que nunca le doy la opción al jugador de elegir mostrar estado en el transcurso de las mismas. Esto significa que nunca se podrá mostrar el estado y que éste diga "Día x: Competencia". Esto esta bien? O debo agregar la opcion durante la simulacion de competencia?
Gracias!!

**Comment by mmunozmendez** [comment]
Hola,
La opción de mostrar estado debe estar en el menú principal, es correcto que no esté durante la competencia. 
Los resultados de cada día de competencia deben guardarse en el archivo de texto correspondiente, pero puedes hacer que se impriman cosas en pantalla si crees que es mejor para entender en qué día te encuentras. Estas decisiones las puedes especificar en tu readme para que queden más claras. 

Éxito en lo que queda 🦝 !
