### ISSUE TITLE
output en consola durante escenarios

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#581]
hola ! quería saber si se puede hacer un output en consola del siguiente tipo mientras que se realizan los escenarios. Digo para que se sepa que se está avanzando en el tiempo y no está pegado 
<img width="339" alt="captura de pantalla 2017-10-22 a la s 12 26 31" src="https://user-images.githubusercontent.com/26392931/31863487-5f1c5308-b724-11e7-8f80-27774b61cbdd.png">

**Comment by GustavPrudencio** [comment]
si se puede.

saludos.

**Comment by rihanuch** [comment]
Aprovecho de preguntar también si se puede mostrar el resumen de cada escenario corrido 😅

**Comment by iqacevedo** [comment]
Hola,

A que te refieres por resumen ?, si te refieres a las estadísticas no.

Saludos !

**Comment by rihanuch** [comment]
me referia a eso! gracias!
