### ISSUE TITLE
Formato de properties en diagrama de clases

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#581]
Hola! Para el diagrama de clase tengo entendido que para señalar los propertys se usa la notación  <get/set/del> pero, los propertys deben ir en la parte de métodos ?, también estos tienen una visibilidad pública (+) o protegida(#) ?

**Comment by moquezada** [comment]
Hola @RonaldoSosa,

Efectivamente, se debe utilizar la notacion `<get/set/del>`. Por otra parte, la property se indica en la sección de atributos utilizando la notación anterior 😄 Además, la visibilidad de estos es pública debido a que en Python todos los atributos de una clase lo son! Pero siempre ten en cuenta que las properties son fundamentales en el encapsulamiento del código y nos brindan una herramienta para trabajar con algo muy parecido a los atributos privados :)

Saludos!

**Comment by mpmunoz13** [comment]
Hola! Como debemos poner los properties en el diagrama? Nos podrian dar un ejemplo?

**Comment by moquezada** [comment]
Hola @mpmunoz13!

Tomando el ejemplo del puente en los contenidos de [properties](https://github.com/IIC2233/contenidos/blob/master/semana-02/2-properties.ipynb), podrías realizarlo de la siguiente manera:

![ejemplo](https://user-images.githubusercontent.com/43896576/79801431-29203e00-832c-11ea-9744-106972965aca.PNG)

Si además en el ejemplo se aplicara un _deleter_ entonces sería `<get/set/del>` y en el caso de que solo fuese un _getter_ sería `<get>` 😄 

Saludos!

**Comment by mpmunoz13** [comment]
Entonces no definimos el setter y getter como metodos? Solo quedan definidos en los atributos? Porque se usó un + y no un -?

**Comment by moquezada** [comment]
> Entonces no definimos el setter y getter como metodos? Solo quedan definidos en los atributos? Porque se usó un + y no un -?

Exacto, generalmente las properties se declaran en la sección de atributos de la clase e indicando a través del formato que mencioné si tienen definido un _getter_, _setter_ o _deleter_. 

La razón por la que tiene un + la expliqué en el primer comentario :)

Saludos!
