### ISSUE TITLE
usuarios.json

### ISSUE THREAD

**Issue by mgbriones** [IIC2233/syllabus#581]
Al abrir el archivo me di cuenta que tiene las llaves [ ] englobando todo el mensaje, suponiendo que es archivo tipo .json, no deberia ser { }. 
Python me tira error cuando intento leerlo

**Comment by jmwielandt** [comment]
Hola,

Está bien, es un JSONArray, que se convierte en una lista de python. ¿Qué error te tira?

Saludos.

**Comment by mgbriones** [comment]
no se que hice pero en la mañana funciono, gracias de todas formas
