### ISSUE TITLE
properties 

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#582]
En el issue #329 el ayudante dice "En particular, la energía ayuda a limitar la cantidad de acciones que puede hacer el Magizoólogo en un día. Por esto, si llega a cero esta obligado a pasar de día para poder recuperarla y así poder hacer alguna acción". Ahora mi pregunta es:
si es que hice un property para energía, y dentro de este property escribí que energía no puede ser menor a 0, puedo ADEMAS escribir dentro de este mismo que cuando la energía llegue a 0 se pase al siguiente día automáticamente?

**Comment by Dnpoblete** [comment]
Hola @dsepulveda3, por favor realiza esta duda que planteas en la misma issue que mencionas, ya que es una duda sobre el mismo tema.
