### ISSUE TITLE
Cambiar Sprites Post-Entrega

### ISSUE THREAD

**Issue by vijuarez** [IIC2233/Syllabus#582]
Hola!

Estaba haciendo un poco más de trabajo con los sprites, pero no voy a poder terminar programación y sprites para la fecha de entraga. Creo que le agregan bastante al juego, por lo que me gustaría poder hacer mi entrega final con los sprites terminados. Puedo subir la tarea con place holders y, uno o dos dias despues, subir solo archivos a IMGS y que se revise esa versión?

**Comment by iqacevedo** [comment]
Hola

Si puedes (pero solo un día más para que las subas junto a tu README), eso si debes recordar subir imágenes que hagan que tu tarea funcione bien aunque no se vea perfecta (para le entrega de hoy a las 23:59). Si subes imágenes que hagan que tu tarea se vea mejor recuerda especificarlo e el README para que quien te corrija descargue las últimas imágenes que utilizaste.

Saludos !
