### ISSUE TITLE
Acceder a una sala

### ISSUE THREAD

**Issue by betojara** [IIC2233/syllabus#582]
Hola, el cómo acceder a una sala queda a criterio personal? o tiene que ser con apretando algún label o botón?

**Comment by jeschuwirth** [comment]
Saludos,

Como no se especifica en el enunciado es a criterio personal, te recomiendo un botón o label clickeable, de todos modos si tu manera no es tan 'intuitiva' como un botón déjalo explicado en el readme para que el ayudante no tenga problemas al corregir.

Suerte!
