### ISSUE TITLE
Duda sobre resultados.txt

### ISSUE THREAD

**Issue by CrisBerriosL** [IIC2233/syllabus#582]
Hola! Según el enunciado nuestro código debe ser capaz de generar un archivo "resultados.txt" y escribir los resultados de cada día de competencias en él. 
¿Tenemos que crear un archivo por partida? Es decir, si se juega una partida se crea un archivo resultados.txt, y si luego de haberla terminado se empieza una segunda partida, ¿resultados.txt se sobreescribe, tal que se borran los resultados de la partida 1 y queden solo los de la partida 2? ¿O se mantienen escritos los resultados de la partida 1 y se agregan los de la partida 2?

**Comment by retamalcito** [comment]
¡Hola @CrisBerriosL!

Esto no se dice de forma explícita en el enunciado, por lo que tienes dos opciones:

* Sobreescribir la información de `resultados.txt` cada vez que se juegue una partida.
* Agregar la información de la nueva partida a `resultados.txt`, sin borrar lo ya escrito.

Sea cual sea el método que elijas, recuerda **especificarlo en tu README** para que no tengas problemas. 😄

¡Éxito! 🏅
