### ISSUE TITLE
Duda ubicación de archivos entregados

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#582]
Hola quería confirmar algo 
El enunciado dice:

> El cliente y el servidor deberán estar separados, lo que implica que deben estar contenidos en directorios diferentes, uno llamado client, y el otro llamado server. Cada uno debe tener un archivo llamado main.py (archivo principal a ejecutar) y debe contar con todos los módulos y demás archivos necesarios para su correcta ejecución.

> 
Entonces yo puedo mover libremente los archivos que me entregaron a las carpetas correspondientes en donde van a ser usados (ej "usuarios.json , amigos.json, los sprites y archivos del bonus) o tengo que mantener su ubicación original en el directorio padre?
Supongo que es lo primero y en caso de ser así tendría solamente que especificar en el readme la estructura? 
Gracias de antemano

**Comment by jmwielandt** [comment]
Hola,

Eso lo discutimos en relación a los sprites en la issue #544, pero para todos los archivos pedidos sí, puedes moverlos (y deberías) a sus respectivas carpetas. Esto no quita que debas ignorarlos con tu `.gitignore`. También debes indicarlo en tu _readme_, como parte de las indicaciones para correr tu tarea.

Saludos!

**Comment by JuaniAndres** [comment]
Ok muchas gracias
