### ISSUE TITLE
Duda con aparición de objetos en el mapa

### ISSUE THREAD

**Issue by piacabrera** [IIC2233/syllabus#582]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda con aparición de objetos en el mapa
Hola! me queda una duda con respecto a la posición en la que aparecen los objetos, en el enunciado me parece que solo se especifica que no pueden aparecer sobre un obstáculo por lo que, podrían aparecer dos juntos? (si los tiempos en que están en pantalla son mayores al de aparicion) o podría aparecer uno justo en la posición del personaje, de forma que no se tenga que mover para agarrarlo?
Muchas gracias de antemano!

**Comment by Juampisaez** [comment]
Hola @piacabrera 
En primer el lugar en que parecen los objetos **es aleatoria**, la unica condicion es que esta posicion sea dentro del mapa y que estos no se superpongan (puedes revisar la distribucion de puntaje).
Por otro lado, recuerda que cierto tiempo (dependiendo de la dificultad) debera aparecer un objeto. El objeto que aparezca dependera que las probabilidades de aparicion (puedes considerar dividir el 100% en tres, cada parte para cada objeto y dependiendo la probabilidad que salga, mostrar el objeto correspondiente). Cada objeto debe estar una cierta cantidad de tiempo en pantalla.
Podria darse el caso de que hayan dos objetos en el mapa, por ejemplo, si el tiempo entre cada aparicion es de 3 segundos y la duracion de cada objeto en el mapa es de 10 segundos, habra un momento en que habran 3 objetos en el mapa.

Espero quede mas claro, quedo atento igual :)

**Comment by piacabrera** [comment]
Perfecto! entonces, si no pueden superponerse no podrá aparecer uno sobre lisa por ejemplo?

**Comment by Juampisaez** [comment]
@piacabrera 
Podria ocurrir, pero como te digo es aleatorio. La condicion es que **los objetos** no se superpongan.
