### ISSUE TITLE
No me funciona el .gitignore.txt

### ISSUE THREAD

**Issue by Mendez69** [IIC2233/syllabus#583]
hice un txt llamado .gitigonre y puse las cosas que no se debían subir pero igual lo están haciendo. Qué puede estar pasando?

**Comment by Dnpoblete** [comment]
Hola @Mendez69, lo que pasa es que el gitignore no es un archivo con extensión `.txt`, sino que tiene que ser un archivo `.gitgnore`. Como recomendación, revisa los `.gitgnore` entregados en las actividades e incluso puedes copiar uno para usarlo en la tarea.

Avisame como te va! :smile:

**Comment by Mendez69** [comment]
lo hice sacando el .txt y sigue sin funcionarme. También aprovecho de preguntar como puedo borrar los archivos de mi repo que se subieron sin ser ignorados :c

**Comment by Dnpoblete** [comment]
¿Y probaste con la recomendación que te comente de utilizar los .gitignore de las actividades? Avísame si te funciona. Con respecto a tu segunda duda, ya fue respondida en la issue #588, para que la revises.

Avísame como te va! 😄

**Comment by Mendez69** [comment]
Ahí sí, tenía que borrar primero los archivos que estaban subidos
Gracias!!!
