### ISSUE TITLE
Re ejecutar un código

### ISSUE THREAD

**Issue by egbusch** [IIC2233/Syllabus#583]
Hola,

Quería saber si se puede reejecutar un código (hacer un restart al programa), he buscado pero no entiendo exactamente como funciona.

**Comment by iqacevedo** [comment]
Una solución a tu problema podría hacer una función que reinicie todos los elementos de tu programa a como estaban inicialmente. Luego solo la llamas y deberías obtener lo que buscas.

Saludos!

**Comment by egbusch** [comment]
Gracias, logré solucionarlo :)
