### ISSUE TITLE
error en amigos.json ("3")

### ISSUE THREAD

**Issue by SamWeinstein** [IIC2233/syllabus#583]
Hola! Estaba probando mi programa y me dio un error en el servidor al preguntar por los amigos del usuario "3", diciendo que "3" no era ninguna entrada en el diccionario de amigos, fui a revisar al archivo de amigos.json y noté que efectivamente no está la información de amigos de "3", lo cual me pareció muy raro porque estoy casi seguro que ya había preguntado por los amigos de "3" antes sin que me ocurriera este error, por lo que pensé que por algún motivo se me borró. Luego, vine a github.com al syllabus directamente a buscar la información de los amigos de "3" para copiarla en mi archivo, y me di cuenta que en el archivo en el repositorio del syllabus tampoco está la información de los amigos de "3" y en el enunciado dice que debe estar la información de los amigos de TODOS los usuarios (y si no tiene amigos, lista vacía), pero me sorprende mucho que nadie haya dicho nada a esta altura si todos estamos usando el mismo archivo y ademas en el syllabus este no se modifica hace 9 días. Que paso acá? Estoy muy confundido pues estoy seguro que en algún momento tuve la información de los amigos de "3"

**Comment by lily416** [comment]
Lo siento había un error al momento de crear el archivo 🙇‍♀ 
Se acaba de subir un versión corregida con las usuarios que faltaban.

Gracias por avisar y éxito en la tarea 👋
