### ISSUE TITLE
tiempo de traslado a comer

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#583]
En el enunciado dice:
"Ir a comprar comida: Ya que no todos los miembros de la PUC se ubican cerca de los puestos
de comida, el tiempo T que representa el tiempo que demorará la persona en llegar distribuye
exponencial de parámetro lambda_traslado (considere que un alumno nunca se demorará más de 3lambda_traslado y que el tiempo para cambiarse de cola es nulo)"

1) creo que no tiene sentido decir que el alumno nunca se demorará más de 3lambda_traslado debido a las características de la distribución exponencial y al valor de lambda_traslado = 0.33 en el archivo parametros_iniciales.csv:
Como lambda_traslado = 0.33, entonces la esperanza del tiempo de traslado es 1/0.33=3 (aprox.) y se está diciendo que el alumno nunca demorará más de 3lambda_traslado = 3*0.33=1 (aprox.) . Es decir, se está diciendo que el alumno nunca se demorará más que un tiempo menor al tiempo esperado de demora. En ese caso no veo la razón para darle una distibución exponencial al tiempo de demora, se podría haber dado una distribución uniforme entre 0 y 3lambda_traslado o algo así.
-¿quisieron decir que el alumno no se demorará más que 3*(1/lambda_traslado)?

2) No salen las unidades de tiempo de T
-¿Las unidades de tiempo de T son minutos?

**Comment by cilopez** [comment]
1.- Efectivamente es lambda/3 , lo que queríamos referirnos era a que no fuera mayor a 3 veces el promedio.
2.-  La unidad de tiempo de T es en horas, sería casi instantáneo si fuera en minutos .

**Comment by mjgutierrez1** [comment]
Perfecto muchas gracias!
