### ISSUE TITLE
duda sobre eficiencia de tests

### ISSUE THREAD

**Issue by BenJofre27** [IIC2233/Syllabus#583]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, pregunto porque no estoy muy seguro; en la seccion 4. Test, cuando dicen "se evaluará que cada test corra en
menos de 30 segundos", eso incluye al test 'python3 -m unittest discover tests_publicos -v -b', que son 284 test juntos (y cuando yo lo corro lo hace en hasta 80 segundos, pero cada test por separado corre en 10 max)?

**Comment by Vicente1824** [comment]
¡Hola @BenJofre27 🙌! Es por cada test, lo más probable es que al correr todos los tests se demorará más de 30 segundos.

**Comment by Vicente1824** [comment]
Añadiendo a eso, una forma de verificarlo es que, si ejecutas todos los tests de una sola vez y no se levanta ningún error, quiere decir que estás bien de tiempo **en los tests públicos** (no necesariamente por tener bien los públicos, los privados también lo estarán). ¡Espero que te sea de ayuda!
