### ISSUE TITLE
Manejo bytes filtro

### ISSUE THREAD

**Issue by josejimenezp** [IIC2233/syllabus#583]
Hola, cuando llego a la matriz G me quedan los valores [0, 255, 360]. El problema es que el 360 no puedo codificarlo en un byte. ¿Debería considerarlo como 255? La imagen me queda casi entera negra y no sé porqué :'(

**Comment by jeschuwirth** [comment]
Hola!

Tienen tu misma pregunta en la issue #581, acabo de terminar de corregir las T02 así que ahora voy a intentar ayudar a encontrar el problema

**Comment by jeschuwirth** [comment]
acabo de notar que la otra issue tambien es tuya 😅 , sube a tu repo lo que llevas para observar mejor tu algoritmo

**Comment by josejimenezp** [comment]
Jajajaj ups, lo subo al tiro!

**Comment by josejimenezp** [comment]
Listo! Es el archivo filtro.py, y la imagen que puse es la misma del Squirtle. Graacias!!

**Comment by jeschuwirth** [comment]
Perfecto, voy a mirar enseguida tu código, voy a cerrar esta issue y si encuentro algo te lo comento por la #581
