### ISSUE TITLE
Duda atributo dia_actual y las duplas de días

### ISSUE THREAD

**Issue by IgorPeralta** [IIC2233/syllabus#583]
Hola! Me surgió la duda de que en el enunciado se dice que se inicializa el día actual en 0... por lo que los entrenamientos serían los días 0, 2, 4 y las competencias los días 1, 3, 5 (Si es que los días de competencia son 6), pero en los ejemplos de outputs que se dan en el enunciado sale como si se inicializara en el dia 1.
Por ejemplo, en "Mostrar Estado de la Delegación y sus Deportistas" se lee que dice: "Día 5 : Entrenamiento".
Lo mismo ocurre en "Puntajes.txt" en donde muestra los resultados de las competencias de los días 2, 4 y 6...

¿Cuál debemos seguir?

Muchas gracias!

**Comment by mmunozmendez** [comment]
Hola, 
La información oficial es la del enunciado, los outputs mostrados son solo ejemplos de como deberían verse.

Éxito con lo que queda 🦝
