### ISSUE TITLE
Operador v/s limpiador o técnico

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#583]
Hola!
Al momento de escribir los logs, cuando se repara o limpia una atracción debemos considerar al generador del evento cómo al que lo produce (en este caso el operador sería quien llama al limpiador o al técnico) o a quién lo realiza (directamente el técnico o el limpiador).
Saludos!

**Comment by IchottMano** [comment]
@santilaguna Hola!

En ese caso específico (un técnico o limpiador haciendo mantención de una atracción) el operador no tiene nada que ver, por lo que el que produce el evento no es el operador, sino que el limpiador o el técnico.

Saludos!

**Comment by santilaguna** [comment]
Gracias!
