### ISSUE TITLE
Atracción fuera de servicio

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#584]
Hola!  tengo varias dudas respecto a lo que dice el enunciado sobre cuando una atracción queda fuera de servicio.
Primero, cuando se refiere a que los clientes pueden permanecer en la cola y no pueden elegir la atracción se refiere a los clientes que luego que la atracción se encuentra fuera de servicio desean ingresar. O se refiere a los clientes que desde antes, habían decidido entrar a la atracción pero justo cuando el operador encontró una falla,  no  pudieron subirse y permanecieron en la cola . Si es el primer caso , me parece contradictorio que un cliente pueda ingresar a la cola de una atracción si esque aún no la elige ( por que no puede eligir la atracción). Si es el segundo caso , que pasa con los clientes que quieren elegirla cuando está fuera de servicio , simplemente se descarta la opción y por ende entrar a su cola?
También tengo la duda de que pasa si la próxima falla será luego de que cierre el parque , en ese caso debo sumar el tiempo que sobrepasa a las 19 a las 10 o simplemente asumo que esa falla no ocurrira

**Comment by pcseisdedos** [comment]
@leolivares respecto al punto 1, ocurre lo mismo para los clientes que ya eligieron la atracción pero aun no llegan a la cola? porque tardan 10 minutos en realizar la acción (yo eso lo interpreto como tiempo en trasladarse)

**Comment by leolivares** [comment]
@pcseisdedos Queda a tu criterio en ese caso!

**Comment by sjkinast** [comment]
Cuando la próxima falla será en un minuto entre vueltas ( cuando la atracción no esta funcionando), cuando el operador revisa la atracción esta aplica?
