### ISSUE TITLE
como probar juego en distintos computadores

### ISSUE THREAD

**Issue by snarriagada** [IIC2233/syllabus#584]
hola, para probar el juego en el mismo computador tengo en cliente y server:
HOST = "localhost"
PORT = 8081
y funciona bien, pero para que funcione corriendo el server en un computador y el cliente en otro, tengo que modificar estos parametros? porque el cliente termina conexion de inmediato
gracias!

**Comment by jeschuwirth** [comment]
Saludos,

El Host = "localhost" significa que te conectas al mismo computador, para hacerlo desde distintos PC tienes que encontrar la dirección IPv4 de tu equipo y utilizar ese como host.

Para encontrar la dirección IPv4 sólo se como se hace en windows, así que si tienes linux o mac te recomiendo buscar en google, si tienes windows has lo siguiente:

abre tu buscador (la lupa en windows 10)
![image](https://user-images.githubusercontent.com/37160256/59815981-59e8ae80-92e8-11e9-9d8b-cf5c1f1d4421.png)

Escribe cmd y aprieta enter
![image](https://user-images.githubusercontent.com/37160256/59816023-7dabf480-92e8-11e9-9dad-f00721c78087.png)

Luego escribe ipconfig en la consola 
![image](https://user-images.githubusercontent.com/37160256/59816056-9e744a00-92e8-11e9-813f-8866b16b7431.png)

En alguna de las líneas que te van a imprimir debería salir lo de arriba con tu información del equipo, ahí debería estar tu dirección.

Como 'localhost' trabaja con la misma computadora tu server puede siempre tener la dirección 'localhost', pero el cliente debe tener como host la dirección ip del computador donde está ejecutándose el server.

Además la conexión que hacemos en este curso es LAN, por lo que ambos computadores deben esta conectados  la misma red WIFI

Espero que eso solucione tus dudas y ganas de saber :)

**Comment by fediaz3** [comment]
Hola! también llego por curiosidad
quería probar mi juego con 2 computadores en el mismo wifi, pero me sale siempre este error, que no puedo arreglar y quería jugar :(

TimeoutError: [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder

Alguien le ha salido y podido solucionar?
Gracias :D

**Comment by snarriagada** [comment]
Tambien me habia salido un timeouterror y lo arregle cambiando y poniendo el mismo port en server y client, no se si tendra que ver,  suerte!

**Comment by fediaz3** [comment]
Me sirvió!
Gracias
