### ISSUE TITLE
Metaclass conflict

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#584]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Al intentar clear una clase abstracta que herede abc y qlabel a la vez, me tira
`` TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases ``
## (solución alternativa que no me gustaría, tratarla nomás como abstracta sin heredar de abc)

**Comment by MatiasDuhalde** [comment]
Hola @fernandosmither !

En una issue anterior (#525), un estudiante diseñó sus clases de una manera quizás similar a la tuya, teniendo una clase base que hereda tanto de QLabel como de ABC, con el propósito de hacer una clase base de QLabel abstracta, y así organizar de mejor manera el programa.

Sin embargo, al heredar al mismo tiempo de QLabel y ABC directamente, Python no es capaz de resolver automáticamente la metaclase que se debe asignar a la nueva clase que estás intentando crear, por lo que arroja el error que estás viendo. Cabe destacar que el concepto principal del cual se trata este error son las metaclases, y no se encuentran consideradas directamente dentro de los contenidos del curso, por lo que no es un tema que debes entender.

Para averiguar la metaclase de un objeto, puedes usar `type` sobre el nombre de la clase, de la siguiente manera:
```python
>>> type(ABC)
<class 'abc.ABCMeta'>
>>> type(QLabel)
<class 'sip.wrappertype'>
>>> type(str)
<class 'type'>
>>> type(dict)
<class 'type'>
```

Acá, puedes notar que la metaclase de ABC es `ABCMeta`, y la metaclase de QLabel es `sip.wrappertype`, las cuales son distintas, y causarán conflicto al hacer herencia de las dos clases a la vez. Sin embargo, también podrás notar que str y dict tienen como metaclase a `type`, pero no hay conflicto cuando intentas hacer una clase que herede tanto de ABC como de str, por ejemplo. Esto debido a que `type` es la metaclase base para todos los objetos. De hecho, si intentas obtener la metaclase de `ABCMeta`, verás que es `type`, la cual siempre se sobrescribe cuando realizas multiherencia con una clase que tiene otra metaclase.

Ahora, ¿cómo se arreglaría tu problema? La forma más simple es la solución que comentas que no quieres hacer, es decir, no usar ABC. Otra solución distinta es usar una clase que herede de ámbas metaclases de manera que se resuelva el conflicto que ocurre en tu implementación actual. La nueva implementación luciría de esta manera:

```python
from abc import ABC, abstractmethod
from PyQt5.QtWidgets import QLabel, QApplication
import sys


class MiMetaClase(type(ABC), type(QLabel)):
    pass


class MiClase(QLabel, ABC, metaclass=MiMetaClase):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    @abstractmethod
    def mi_metodo_abstracto(self):
        print("Hola!")


class MiSubClase(MiClase):

    def mi_metodo_abstracto(self):
        print("Sobreescribiendo método abstracto...")
        super().mi_metodo_abstracto()


if __name__ == '__main__':
    APP = QApplication(sys.argv)

    # La línea de abajo da error!!
    # instancia_a = MiClase()

    # Ahora sí podemos instanciar!
    instancia_b = MiSubClase()

```

Notar cómo la clase MiMetaClase "mezcla" las metaclases de QLabel y ABC, y luego se le pasa como metaclase a MiClase. 

Como disclaimer, personalmente no he testeado este modelo de clases en un programa grande, por lo que no puedo asegurar que no se produzcan conflictos en ciertos casos de uso, aunque no deberían ocurrir, y si ocurren, la solución sería simplemente dejar a MiClase sólamente como subclase de QLabel, e ignorar los abstractmethods. Ten en cuenta que las metaclases son un tema un poco difícil de entender, y no forma parte de los conceptos que esperamos que manejen durante este curso.


Ojalá te funcione la implementación, y mucho éxito en tu tarea! :sparkles:

**Comment by fernandosmither** [comment]
> Hola @fernandosmither !
> 
> En una issue anterior (#525), un estudiante diseñó sus clases de una manera quizás similar a la tuya, teniendo una clase base que hereda tanto de QLabel como de ABC, con el propósito de hacer una clase base de QLabel abstracta, y así organizar de mejor manera el programa.
> 
> Sin embargo, al heredar al mismo tiempo de QLabel y ABC directamente, Python no es capaz de resolver automáticamente la metaclase que se debe asignar a la nueva clase que estás intentando crear, por lo que arroja el error que estás viendo. Cabe destacar que el concepto principal del cual se trata este error son las metaclases, y no se encuentran consideradas directamente dentro de los contenidos del curso, por lo que no es un tema que debes entender.
> 
> Para averiguar la metaclase de un objeto, puedes usar `type` sobre el nombre de la clase, de la siguiente manera:
> 
> ```python
> >>> type(ABC)
> <class 'abc.ABCMeta'>
> >>> type(QLabel)
> <class 'sip.wrappertype'>
> >>> type(str)
> <class 'type'>
> >>> type(dict)
> <class 'type'>
> ```
> 
> Acá, puedes notar que la metaclase de ABC es `ABCMeta`, y la metaclase de QLabel es `sip.wrappertype`, las cuales son distintas, y causarán conflicto al hacer herencia de las dos clases a la vez. Sin embargo, también podrás notar que str y dict tienen como metaclase a `type`, pero no hay conflicto cuando intentas hacer una clase que herede tanto de ABC como de str, por ejemplo. Esto debido a que `type` es la metaclase base para todos los objetos. De hecho, si intentas obtener la metaclase de `ABCMeta`, verás que es `type`, la cual siempre se sobrescribe cuando realizas multiherencia con una clase que tiene otra metaclase.
> 
> Ahora, ¿cómo se arreglaría tu problema? La forma más simple es la solución que comentas que no quieres hacer, es decir, no usar ABC. Otra solución distinta es usar una clase que herede de ámbas metaclases de manera que se resuelva el conflicto que ocurre en tu implementación actual. La nueva implementación luciría de esta manera:
> 
> ```python
> from abc import ABC, abstractmethod
> from PyQt5.QtWidgets import QLabel, QApplication
> import sys
> 
> 
> class MiMetaClase(type(ABC), type(QLabel)):
>     pass
> 
> 
> class MiClase(QLabel, ABC, metaclass=MiMetaClase):
> 
>     def __init__(self, *args, **kwargs):
>         super().__init__(*args, **kwargs)
> 
>     @abstractmethod
>     def mi_metodo_abstracto(self):
>         print("Hola!")
> 
> 
> class MiSubClase(MiClase):
> 
>     def mi_metodo_abstracto(self):
>         print("Sobreescribiendo método abstracto...")
>         super().mi_metodo_abstracto()
> 
> 
> if __name__ == '__main__':
>     APP = QApplication(sys.argv)
> 
>     # La línea de abajo da error!!
>     # instancia_a = MiClase()
> 
>     # Ahora sí podemos instanciar!
>     instancia_b = MiSubClase()
> ```
> 
> Notar cómo la clase MiMetaClase "mezcla" las metaclases de QLabel y ABC, y luego se le pasa como metaclase a MiClase.
> 
> Como disclaimer, personalmente no he testeado este modelo de clases en un programa grande, por lo que no puedo asegurar que no se produzcan conflictos en ciertos casos de uso, aunque no deberían ocurrir, y si ocurren, la solución sería simplemente dejar a MiClase sólamente como subclase de QLabel, e ignorar los abstractmethods. Ten en cuenta que las metaclases son un tema un poco difícil de entender, y no forma parte de los conceptos que esperamos que manejen durante este curso.
> 
> Ojalá te funcione la implementación, y mucho éxito en tu tarea! ✨

Es difícil realmente agradecer adecuadamente respuestas tan completas como esta, que sumadas realmente actúan como un módulo más de contenidos de la clase. Sin embargo, te lo agradezco enormemente.

Para evitar mayores conflictos entonces, supongo que lo mejor será no crear clases abstractas con el ABC. ¿Esto no perjudicará mi evaluación, como por ejemplo en la ev. pasada cuando algunos compañeros no utilizaron properties y se les descontó?

Con esto último queda resuelta mi duda. Gracias!

**Comment by MatiasDuhalde** [comment]
Que bueno que te haya servido la respuesta! Gracias a tí por preguntar, así aprendemos todos! :relaxed: 

Para esta tarea no es requisito ni obligatorio que usen clases abstractas para modelar elementos visuales como los de tu pregunta, por lo tanto, tu puntaje no se vería perjudicado si decides no usar ABC. El foco y objetivo principal de esta tarea es que demuestren que pueden diseñar y manejar **interfaces gráficas** mediante la librería **PyQt5**, y poder crear un programa funcional que tenga una arquitectura **frontend-backend**.

Para la tarea anterior, fuímos más estrictos con los puntos que mencionas, debido a que el foco principal era la **Programación Orientada a Objetos**, y contenidos como las clases, herencia, clases abstractas, properties, entre otros, eran parte de lo que queríamos evaluar directamente.

Saludos! :cowboy_hat_face:
