### ISSUE TITLE
no me funciona el uso de properties

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#584]

**Comment by fdoflorenzano** [comment]
Hola @dsepulveda3,

Como expuesto en las [reglas del foro](https://github.com/IIC2233/syllabus/issues/1) (punto 3), no puedes compartir código directo de tus soluciones. De tener un problema, puedes replicar la situación con un ejemplo que tenga nombres genéricos que no revelen información, y abres una nueva *issue* con tu duda.

Te recomiendo el ejercicio de hacer un ejemplo pequeño intentando replicar el error, para ver donde hay diferencias con tu código. Tal vez te des cuenta antes de postear la issue del problema.

Saludos.
