### ISSUE TITLE
Duda amigos.json

### ISSUE THREAD

**Issue by sebacarrasco** [IIC2233/syllabus#584]
Hola, revisando el archivo amigos.json me di cuenta que el usuario "5" está en su proipia lista de amigos. Esa parte del diccionario se ve así:
"5": [
        "Vampiro",
        "5",
        "Mati_Oprts",
        "Nhorellana"
Esto quiere decir que uno puede auto-amistarse o es un error?

**Comment by lily416** [comment]
Lo siento había un error al momento de crear el archivo 🙇‍♀
Se acaba de subir un versión corregida con las usuarios que faltaban.

Gracias por avisar y éxito en la tarea 👋
