### ISSUE TITLE
Dia_inicio ~ Dias_competencia

### ISSUE THREAD

**Issue by Francisco-Morales-R** [IIC2233/syllabus#584]
Hola, tengo una duda con respecto a los dias en el campeonato. He leído varias issues acerca de esto pero igual no me queda claro del todo. El dia de inicio es un parámetro, por lo que puede ir variando. Entonces, ¿dependiendo del día de inicio es lo que se debe hacer primero? (Ej: si el dia de inicio es 0 [par] se va al menú de entrenador, pero si es 1 [impar] se debe empezar con las competencias al tiro) . O da lo mismo si es el día de entrenamiento es par o impar con tal de que  siempre se empiece con entrenamiento - competencia - entrenamiento - competencia, y así hasta completar la cantidad_de_dias de competencia.
Espero se haya entendido mi duda. De ante mano Gracias!

**Comment by Francisco-Morales-R** [comment]
Siguiendo con ejemplos, sería que ¿si empiezo con dia_inicial = 7, entonces el primer día [7] debería ser entrenamiento - competencia[8]... y así, hasta completar la cantidad de días que se indica con Dias_competencia [que por enunciado es par]?

**Comment by retamalcito** [comment]
¡Hola @Francisco-Morales-R!

Independiente de qué número sea el parámetro del día inicial, **siempre** se comenzará con un día de entrenamiento, sea par o impar. Por lo tanto, lo que dices en tu segundo comentario es correcto: si `dia_inicial = 7`, este día se entrenará, el día 8 será un día de competencia, el día 9 se entrenará, etc., hasta completar los días totales del campeonato.

¡Éxito! 🏅

**Comment by denisseleiva** [comment]
Holaa! @retamalcito En qué parte del enunciado se habla de un dia_inicio? Yo tenía entendido que se partía de 0 y el parámetro que daban era dias_competencia 😳

**Comment by Francisco-Morales-R** [comment]
@retamalcito Muchas gracias. Ahora sí me quedó claroo

**Comment by Francisco-Morales-R** [comment]
@denisseleiva El día inicial sale como 0 en el enunciado, pero al estar en azul pasa a ser un parámetro. que hay que tener el parámetros.py. O eso por lo menos había entendido leyendo otras issues.

**Comment by retamalcito** [comment]
¡Hola @denisseleiva!

Como dice tu compañero, todo valor que esté celeste y/o siga `ESTE_FORMATO` en el enunciado debe ser un parámetro que se almacenará en `parametros.py`.

¡Saludos! 🏅

**Comment by denisseleiva** [comment]
uffff qué bueno que me lo aclararon jajajaja muchas gracias! @retamalcito @Francisco-Morales-R
