### ISSUE TITLE
hora de llegada al campus

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#584]
Dado que la hora de llegada al campus es 11:00 + distribución triangular de 0 a 240 minutos, y que 240 minutos son 4 horas, podrían darse casos en que algún alumno llegue cercano a las 15:00 (11+4). Como para el cálculo de la hora en que el alumno decide ir a comer no se considera la hora en que el alumno llega al campus, perfectamente podría pasar que el alumno decida ir a comer cuando aún no ha llegado al campus (porque las horas de comidas van de 12:00 a 15:00).

¿Puedo agregar una restricción para que si la hora calculada en que el alumno llegue a comer es menor a la hora en que llega al campus, entonces la hora en que el alumno llega a comer se defina como la hora en que llega al campus?

**Comment by cilopez** [comment]
Si puedes y es lo ideal ya que la simulación sería más realista :+1:

**Comment by iqacevedo** [comment]
@mjgutierrez1 quiero agregar que esta duda se había respondido en otras issues, junto con mencionar su respuesta muchas veces también.
