### ISSUE TITLE
Duda tarea test_case 2 y 4 anidada

### ISSUE THREAD

**Issue by Yakao01** [IIC2233/Syllabus#585]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el test_case 4 dice que se revisa que no haya salsa de tomate pero el test solo revisa tomate, y en el test 2 dice que revisa que tenga tomate pero en el codigo del test dice que debe haber champiñones y no tomate

test_2:
![image](https://github.com/user-attachments/assets/acb8485b-a337-4483-b654-6ab35166d278)
![image](https://github.com/user-attachments/assets/2dbb6681-d89e-460a-9fca-c98dc07f9303)

test_4:
![image](https://github.com/user-attachments/assets/51c7d9e6-34f0-418d-86b0-686fb2b18dd5)

Está bien esto? o es un error del test?

**Comment by Yakao01** [comment]
Se me olvidó decir que solo estos tests me dan error al hacerlos

**Comment by Vicente1824** [comment]
¡Hola @Yakao01 😀! ¿Exactamente qué error te da? Te recomiendo revisar la issue #490, podría ser que tengas el mismo problema que el explicado ahí (como filtras algunas pizzas, hay ciertos pedidos que tienen pizzas que no están en el generador de pizzas). Por otro lado, ignora lo que dice la descripción de los testcases, pareciera que estuvieran erróneos, para el caso del test 4, serían las pizzas que no tienen tomate (podrían tener salsa de tomate), para el test 2, que tengan camarones.

**Comment by Yakao01** [comment]
Muchas graciass, eso era!! La descripción me confundió mucho :(, pense que era un error del test y lo mandé así nomas.

**Comment by vicenciomf2** [comment]
Me pasó lo mismo, terminé cambiando harto código y me fallaron más cosas en cascada dsps 😿
