### ISSUE TITLE
Cantidad de lógica en el frontend

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#585]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### ¿Cuánta es la extensión más correcta de lógica dentro del frontend? 
Puedo por ejemplo, en el mismo keypressevent (suponiendo que lo estoy agarrando en un módulo frontend) ver cuál fue la tecla (o combinación) y en base a eso enviar cierta señal al backend (diccionario de comandos, por ejemplo), o esa lógica también debe hacerse exclusivamente en el backend?

**Comment by JadrinaDA** [comment]
Hola! Sí, esas cosas pequeñas puedes hacerlo directamente en el front end. Lo importante es que no haya una función que no tenga nada que ver con la interfaz. Como las teclas son parte de la interfaz puedes verificar cual tecla fue presionada en el mismo archivo. Avísame si tienes más dudas, éxito!
