### ISSUE TITLE
no me funciona el uso de properties

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#585]
Hola! Tengo una duda sobre el uso de properties
Estoy escribiendo algo mas o menos como lo que sale el documento de properties expuesto en contendidos pero no me esta leyendo el cambio.
En mi init escribi al algo asi como self.__valor_que_cambia y luego defini el property como:

    @property
    def valor_que_cambia(self):
        return self.__valor_que_cambia

    @valor_que_cambia.setter
    def valor_que_cambia(self, valor):
            if valor > parametros_x:
                self.__valor_que_cambia = parametros_x
            elif valor < 0:
                self.__valor_que_cambia = 0
            else:
                self.__valor_que_cambia += valor

Luego en mis funciones dentro de la misma clase llamo a esta property como self.valor_que_cambia -= ALGO y no me lo lee. Estoy imprimiendo antes y despues de este y me printea lo mismo.

**Comment by fdoflorenzano** [comment]
Hola @dsepulveda3,

Si el valor de la *property* no está cambiando, es porque no se está accediendo a código que sobre escriba el valor del atributo encapsulado. Se me ocurren dos posibles razones: 
1. Haya un error de escritura con el nombre de la *property*. Revisa que donde se altere, el nombre corresponda correctamente
2. Que alguna condición en un `if`/`elif`/`else` no se esté cumpliendo, resultando en ninguna opción ejecutándose.

La última es bastante común, y suele pasar cuando se agregan muchos flujos condicionales, y resulta en que nada se ejecuta. Prueba agregando `print`s dentro del *setter*, en la primera línea, y dentro de los condicionales, a ver si está entrando a alguna opción o no.

Espero te ayude, avísanos como te va.

Saludos.

**Comment by M-Altamirano** [comment]
Hola 😄 
No soy ayudante pero se me ocurre otra razón. Tanto en los contenidos como en la documentación de Python ([https://docs.python.org/3.7/library/functions.html#property](url)) **setean** la variable al **valor que recibe** el _setter_, mientras que en tu _setter_ estás **agregándole el valor recibido **. 
Entonces, quizás el _setter_ se llama recursivamente, llega a un caso base y se queda con ese resultado. Ojalá te sirva

**Comment by dsepulveda3** [comment]
Gracias! Ya logre solucionarlo

**Comment by fdoflorenzano** [comment]
Hola,

Gracias @M-Altamirano por el aporte. 

¡Qué bueno @dsepulveda3! ¿cuál era la situación? ¿podrías explicarlo para dejar constancia en caso de que tu respuesta la ayude a alguien más?

¡Saludos!

**Comment by dsepulveda3** [comment]
Era lo que me decias. No estaba entrando el codigo a los if/elif/else. Esto porque estaba comparando tipo de magizoologo con tipo de criatura. Lo habia redactado mal yo.
