### ISSUE TITLE
Hacer clases de enunciado?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#585]
Tengo una duda, si me dicen que hay una entidad especifica, pero con dos tipos de comportamientos distintos en el parque, puedo crear dos entidades distintas(clases)? Mas concretamente

En el enunciado explicitan que existen los **operadores**,  pero estos pueden estar en la porteria o en una atraccion. Entonces, debo hacer una sola clase **_Operador_**? O puedo hacer dos clases (Operador, Portero)?

**Comment by leolivares** [comment]
Hola! @naquiroz 
Si lo deseas, puedes modelarlo como dos clases, asegurándote de que cumplan con todo lo pedido.
