### ISSUE TITLE
Duda con DES y variables en el tiempo

### ISSUE THREAD

**Issue by Regenschrim** [IIC2233/Syllabus#585]
Me surgió una duda con respecto al uso de DES. Dentro de mi simulación, el método `run()` contiene un `while (condición)` que tiene la simulación dentro. Cree una clase `Mes` que me forma los días de los 4 meses y me dice que día es de la forma `nombre_dia, número_día`. ¿Estaría mal hacer que unos métodos que me definan las variables que se mantienen de forma mensual y otro que me defina las diarias? Básicamente, el primero me diría (por ejemplo) los saldos por día en un determinado mes, y el segundo me volvería a settear los valores una vez transcurrido el día.

**Comment by iqacevedo** [comment]
Hola,

Si entendí bien, al fin y al cabo estás actualizando el estado del sistema cuando transcurre un mes.
Lo más probable es que estés realizando una simulación sincrona en esa parte, lo que no estaría bien para esta tarea, puesto que esperamos una simulación DES.

Saludos !
