### ISSUE TITLE
Duda bonus palabras bobbas

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#585]
hola se tiene que censurar casos como ( entroalsaiding->entroal%&!_ ) por contener el substring saiding o solamente se censura si esta la palabra no como substring osea ( entro al saiding -> entro al  %&!_$?)

**Comment by DCCollao** [comment]
Hola! 
Decidimos que puede ser de ambas formas y será considerado correcto.

Aún así, me soplaron que en habbo reconoce el substring a censurar, y censura al string completo! 

Éxito!
