### ISSUE TITLE
Duda click punto

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#585]
Hola, puedo asumir que al clickear en un espacio fuera del punto (dentro del cuadrado), mi programa asuma que clickeó el punto más cercano.

**Comment by ariel-m-s** [comment]
Hola!

No, no puedes.

Saludos y éxito!

**Comment by VicenteMerino** [comment]
Respecto a esto, no me queda muy claro como el enunciado pide que hagmos lineas, es valido que al hacer click en puntos adyacentes se haga una?

**Comment by lily416** [comment]
@VicenteMerino Sí es válido hacerlo de esa forma 😄 
También existen otras opciones, como la que se propone en la issue #509 donde se hace click en la línea que se quiere dibujar.

Saludos y éxito con la tarea 👋💪
