### ISSUE TITLE
método entrenar() de Deportista y entrenar_deportista() de Delegaciones

### ISSUE THREAD

**Issue by gaspcr** [IIC2233/syllabus#585]
Tengo un problema con estos métodos, ya que los dos métodos _entrenar_ modifican atributos de algún objeto del tipo Deportista. Mi pregunta es si la idea es que el método al que debemos llamar desde el main sea *entrenar_deportista()* de la clase Delegaciones, el cuál a su vez llama al método *entrenar()* de la clase Deportista?, o desde el main puedo escoger cuál método utilizar (dudo que sea lo último xd). Además, los atributos que se pueden entrenar de un Deportista los estoy tratando con @Properties, por lo cúal, en caso de que el método *entrenar()* de la clase Deportista sea el que modifica los atributos, al ser un método de la misma clase: ¿La manera de modificar esos atributos es igual a como si lo hiciera desde fuera de la clase? (es decir, de llamar a la función que settea un cambio en ese atributo).

**Comment by mmunozmendez** [comment]
Hola,
En el enunciado se describen los métodos (resumiendo):
- entrenar_deportista() de Delegaciones: la delegación podrá enviar a entrenar a sus deportistas
- entrenar() de Deportista: el entrenamiento aumento en PUNTOS_ENTRENAMIENTO el atributo físico elegido.

Hay una diferencia entre lo que hacen los métodos, si bien, se ocupan ambos al entrenar a un deportista, cumplen distintas funciones en ese proceso, te recomiendo leer en detalle las descripciones en el enunciado para separar que hace cada una. 
Con respecto a como llamar el método desde el main, no hay una única forma, dependerá de tu modelación, pero lo más importante esque tenga sentido cuando une lo ve.
En cuanto al uso de properties, si debería ser igual a modificarlas desde fuera de la clase, pero te recomiendo si tienes dudas que hagas pruebas imprimiendo resultados, para que te asegures de que está funcionando correctamente.

Éxito 🦝 !
