### ISSUE TITLE
Tipos de return en diagrama de clases

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#586]
hola, si una clase madre tiene un metodo instanciador de subclases llamado instanciador() que retorna la llamada de las clases hijas, como escribo eso en mi diagrama (cuando nombro la funcion)??
+ intanciador(): str ??
+ instanciador(): class??
+ instanciador(): instance ??

**Comment by dsepulveda3** [comment]
Replico mi duda para cuando mi funcion me retorna otra funcion? Queda a mi criterio como lo escribo?
+ funcion_1(): function ??

**Comment by dsepulveda3** [comment]
Hola. Algun comentario sobre esto????

**Comment by Drpinto1** [comment]
¡Hola!

Cuando realizas un diagrama de clases, debes escribir el tipo de objeto que retorna tu método luego de los dos puntos.

Si no sabes con certeza cuál es este tipo, puedes hacer:

```
var = clase.metodo()
print(type(var))
```

Sobre este comentario:
> Hola. Algun comentario sobre esto????

Los ayudantes tenemos un _bot_ que nos avisa de todas las _issues_, por lo que no es necesario este tipo de comentarios, no te preocupes, tu duda no se perderá :)
 
Todas las preguntas serán respondidas en cuanto algún ayudante que tenga la certeza la solución pueda hacerlo, sin embargo se acumula una gran cantidad de preguntas los días domingo, por lo que nos toma un poco de tiempo responderlas todas.

¡Saludos!

**Comment by dsepulveda3** [comment]
Vale, gracias ! Sorry lo insistente.

**Comment by Drpinto1** [comment]
No hay problema, es normal preocuparse cuando uno ve que la pregunta lleva mucho tiempo sin responder :smile:
