### ISSUE TITLE
atributos de jugadores iniciales del equipo

### ISSUE THREAD

**Issue by betolguin** [IIC2233/syllabus#586]
hola! no me queda claro si a los 5 deportistas que vienen en el archivo delegaciones.csv hay que asignarle atributos al azar para que sean deportistas? no entiendo bien esoo :(

gracias de antemano!

**Comment by jitorcas** [comment]
Hola @betolguin 

Los atributos de los cinco deportistas que vienen en el archivo `delegaciones.csv` puedes obtenerlos desde el archivo `deportistas.csv`. 

Mucho éxito en la tarea! 🥇  si quedas con dudas, pregunta no más!

**Comment by betolguin** [comment]
la verdad no me quedó muy claro :O en el fondo puedo instanciar al equipo de la delegacion  con los datos que estan en delegaciones.csv y luego eliminar esos datos del archivo para que no esten como "disponibles" para fichar??

gracias de antemano!

**Comment by jitorcas** [comment]
@betolguin 

En el archivo `delegaciones.csv` no te dan ningún dato de los deportistas más que decirte cuales perteneces a cada delegación. 

Lo que te **recomiendo** hacer es instanciar a los deportistas con los datos de `deportistas.csv` y asignarlos a las delegaciones correspondientes. 

Avísame si fui más claro esta vez!
