### ISSUE TITLE
Distribución normal -> distribución beta

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#586]
Hola,
Quería saber si puedo trabajar con una distribución beta en lugar de una normal para las variables aleatorias cuyo soporte sea un intervalo acotado, haciendo los cálculos de alfa y beta correspondientes a partir del mu y sigma que recibe la normal.

Gracias! :D

**Comment by IchottMano** [comment]
@jmwielandt Hola!

Lo que puedes hacer, si lo deseas, es tener ambas distribuciones, sin embargo tu programa debe ser capaz de poder cambiar de una a la otra (tal vez con un booleano, el cual deberás poner en tu README para poder manipularlo fácilmente), es decir no puedes reemplazar completamente la distribución normal.
Tambien, cabe decir que no se darán puntos extra por "usar una mejor distribución" o "usar una distribución mas complicada / fácil"

Saludos!

**Comment by jmwielandt** [comment]
Entiendo
Pregunto porque no sé qué tan correcto es, por ejemplo, decir que si la altura que sale es menor a 60 cm, sea 60 cm, y lo mismo con los límites superiores.

**Comment by IchottMano** [comment]
@jmwielandt Hola!

Eso estaría correcto.

Saludos!
