### ISSUE TITLE
Dudas salas de chat y parametros T03

### ISSUE THREAD

**Issue by sebacarrasco** [IIC2233/syllabus#586]
Hola tengo una serie de preguntas:
1) Un usuario puede estar en más de una sala de chat a la vez?
2) Cuando entro a una sala de chat la ventana principal debe seguir abierta o se debe cerrar?
3) En la issue #574 dicen que las cantidad de salas de chat debe ser un parametro. Podría tener este parámetro algún límite? Porque si no lo tuviera, es muy probable que en la ventana principal si hay muchas salas sus nombres se pongan unos sobre otros.
4) Si la cantidad de salas de chat es un parametro, asumo que la cantidad de personas por sala también. Hago la misma pregunta que para la cantidad de salas, podría tener un límite este parámetro?, Porque si no, es probable que los personajes y los mensajes aparezcan unos encima de otros.
5) En la distribución de puntaje, en la parte de archivo sale : "Se guardan correctamente los cambios realizados al grafo". Esto se refiere a que los cambios en el grafo deben ser guardados en el archivo amigos.json?

**Comment by Dnpoblete** [comment]
Hola @sebacarrasco en cuanto a tus dudas:

1. No puede estar en más de una sala al mismo tiempo.

2. Eso queda a tu criterio, pero es recomendable que se cierre, ya que si no lo haces tendrás que seguir actualizando en todo momento la ventana principal.

3. Ese parámetro se mantendrá con los números indicados en el enunciado, pero como hint, puedes usar áreas scrolleables para que no te falte espacio.

4.  Lo mismo que para el punto anterior.

5. La respuesta es sí, en el enunciado dice lo siguiente: "Debes actualizar el archivo que almacena el grafo en ese momento".

Espero haber respondido tus dudas, si algo no quedo claro avisame para ayudarte.

Éxito con la tarea! :smile:

**Comment by sebacarrasco** [comment]
Muchas gracias! Me quedó todo claro
