### ISSUE TITLE
Que hacer cuando jefe de sala abandona

### ISSUE THREAD

**Issue by fplois** [IIC2233/syllabus#586]
![Captura de pantalla 2019-06-20 a las 12 52 26 p m](https://user-images.githubusercontent.com/48328108/59866688-2fcfd480-935a-11e9-8ea9-cc0085b94208.png)
![Captura de pantalla 2019-06-20 a las 12 52 58 p m](https://user-images.githubusercontent.com/48328108/59866742-4ece6680-935a-11e9-9375-c5b90ce6f462.png)

Hola, tengo una duda en este punto, cuando el jefe de la sala abandona la sala, ¿debo llevar a todos los jugadores a la ventana salas? como aparece en el enunciado o ¿asignar a otro jugador como el jefe nuevo de la sala y seguir jugando?, esto sin volver a la ventana salas y sin eliminar la sala.
Gracias y saludos

**Comment by gatochico** [comment]
Hola! 

Ambos pantallazos se refieren a dos situaciones distintas, por eso el procedimiento es distinto.
El primer caso ocurre cuando los jugadores **ya jugaron una partida de timbiriche** y se acabó esta partida. Allí, el jefe decide o jugar partida nueva o terminar. Si en este punto se decide no jugar una nueva partida y terminar, se debe cerrar la sala y sacar a todos los jugadores a la lista de salas.

Por otro lado, si el jefe decidió jugar una partida nueva, queda a tu criterio (como dice #563) si la ronda comienza inmediatamente o si vuelves a una sala de espera antes de empezar la ronda. Si implementas que vuelven a una sala de espera, y ahí el jefe sale de la sala, ocurre lo que dice tu segundo pantallazo, donde se debe reasignar un nuevo jefe sin cerrar la sala o echar a la gente.

En resumen: La celda de distribución de puntaje evalua que pasa cuando el jefe sale de una sala de espera en general (puede ser que no hayan jugado nunca todavía, o que ya acabó una ronda y volvieron al chat antes de empezar otra). El pantallazo del enunciado indica como actuar **justo después de acabada la ronda** pero antes de que se eligió jugar otra ronda.

Espero haber ayudado! 💻

**Comment by fplois** [comment]
Gracias por la respuesta, ya entendí :)
