### ISSUE TITLE
Frontend/backend? módulo clases

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#586]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Estoy creando un módulo para las clases, que heredan qobjects, por lo anterior se me ocurre que este módulo pertenecería al frontend, sin embargo, qué pasa si les creo métodos que ejecuten sus animaciones y cosas un poco más de lógica, que quizás no sea completamente frontend?

La pregunta anterior. Y en definitiva, hasta qué punto es frontend, y hasta qué punto es backend? o aprovechando que ya estoy modularizando a los personajes, tengo la libertad de mezclar ambos en el mismo módulo?

_ps. En una issue anterior ya pregunté sobre el tema de tratar cuál tecla fue pulsada en el frontend, pero aquí me refiero a algo "un poco más allá", como si el gatillar la animación completa desde un método de objeto, hace que deba guardar el módulo en mi carpetita de backends en vez de la de frontends._

**Comment by Juampisaez** [comment]
Hola @fernandosmither 
Creo que la gran diferencia entre ambas partes es que en el frontend te preocupas solo de instanciar y actualizar visualmente todo el contenido de una ventana, es decir, al fin y al cabo mostrar todo lo que estas calculando por detras (backend). Por otro lado, el backend es mas que nada calculo, por ejemplo el movimiento de un personaje, las colisiones que este podria tener, los estados en el que se encuentra, es decir, cosas que se requieren antes de visualizar los labels en este caso. 
Como lo estas explicando tu, seguramente el QObject sera un label que quieres visualizar dentro de tu ventana. Sin embargo, la logica que hay por detras de este label u objeto es puramente backend (no se si se entiende la diferencia).
Cabe decir ademas que no es que debas instanciar un QObject dentro de la ventana, ya la forma correcta de hacer la comunicacion es a traves de señales.
En resumen, entiendelo como visualizacion (frontend) v/s logica (backend).

Si no se entiende algo, quedo atento :)

**Comment by fernandosmither** [comment]
@Juampisaez 
> Cabe decir ademas que no es que debas instanciar un QObject dentro de la ventana, ya la forma correcta de hacer la comunicacion es a traves de señales.

Buena!, eso sí la parte de arriba no me quedó clara. Dices que **no debo instanciar un QObject** dentro de la ventana?

**Comment by Juampisaez** [comment]
Claro, pero ahora que lo pienso bien, tambien podrias hacerlo (no pesques lo que dije anteriormente, pifie).

**Comment by fernandosmither** [comment]
> Claro, pero ahora que lo pienso bien, tambien podrias hacerlo (no pesques lo que dije anteriormente, pifie).

Vale, perfecto. Lo que concluiría mi pregunta, **puedo hacer que cada clase de objeto guarde sus parámetros?**

**Comment by Juampisaez** [comment]
Si te refieres a que cada clase tenga propios atributos, claro que si. No se si entendí bien tu pregunta

**Comment by fernandosmither** [comment]
> Si te refieres a que cada clase tenga propios atributos, claro que si. No se si entendí bien tu pregunta

Me refiero a que tengo un módulo de clases que son herederas de QLabel, cosas de frontend. Sería legal aquí meter por ejemplo en la QLabel del veneno, el parámetro del daño de veneno y otras cosas que usará el backend?

**Comment by Juampisaez** [comment]
Aaah ya te entendi. La verdad es que no tendria mucho sentido, asumo que ese valor lo tendras para calcular cuánto se le quita a la vida del personaje. Todo lo que sea calculo debe estar en el backend. La idea es que lo que sea frontend sean las cosas que se muestren.
Deberias colocarlo directamente en el backend.

**Comment by fernandosmither** [comment]
> Aaah ya te entendi. La verdad es que no tendria mucho sentido, asumo que ese valor lo tendras para calcular cuánto se le quita a la vida del personaje. Todo lo que sea calculo debe estar en el backend. La idea es que lo que sea frontend sean las cosas que se muestren.
> Deberias colocarlo directamente en el backend.

Ok, perfecto!
