### ISSUE TITLE
Importar objeto "Magizoologo" en distintos archivos .py

### ISSUE THREAD

**Issue by Mario-uc** [IIC2233/syllabus#587]
En los archivos intenté importar el objeto Magizoologo (es decir el objeto que crea o usa el usuario), para poder interactuar con él, y no me funcionó, también intenté mandarlo a través de funciones y tampoco me deja, ya que se manda el nombre como str . Me gustaría saber como puedo hacer para que el objeto se pueda mover en distintos archivos

**Comment by Mario-uc** [comment]
ya lo resolví  :b  error mío

**Comment by Dnpoblete** [comment]
Hola @Mario-uc, que bueno que lo pudieras resolver, podrías contarnos como lo solucionaste, por si alguien más tiene el mismo problema  y así lo puede solucionar viendo esta issue.

Gracias y éxito con la tarea! :smile:
