### ISSUE TITLE
Obtener el heigth de un Label

### ISSUE THREAD

**Issue by sebamoreno2811** [IIC2233/syllabus#587]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Como puedo obtener el alto y tambien el valor de y de un label? es que para el ancho muedo usar .width() y para el x x() pero para el alto no existe ni el atributo .heigth() ni y() entonces existe algun otro metodo que me lo de?

**Comment by tomasrosenberg** [comment]
Hola @sebamoreno2811!
Sí existe un método para revisar la altura y se llama .height(). Además, también se puede ver su posición en "y" con .y() al igual que como lo usas con x. Revisa si lo escribiste bien en tu código, y si no es es eso revisa que lo estés utilizando en un QLabel.
Quedo atento a cualquier otra duda :D

**Comment by sebamoreno2811** [comment]
@tomasrosenberg es que me tira un error diciendo que .height() y .y() no son metodos de un QLabel, y de hecho viendo en la documentacion tampoco salen como metodos encambio el width y el x si salen, gracias por responder!

**Comment by tomasrosenberg** [comment]
@sebamoreno2811 podrías subir lo que llevas de la tarea para echarle una mirada a tu código y decirme en qué parte lo estas intentando implementar.

**Comment by sebamoreno2811** [comment]
Ahi lo sub, en ventana_juego.py en la clase VentanaAvance quiero hacer unos parametros que representen los limites del Label baldosas para que en ese rango se mueva el personaje), entonces puedo sacar sin hardcodear los x de los veices con .x() y .width() pero por el problema anterior los y solo los puedo sacar mediante lo que me indica el qt designer.

**Comment by tomasrosenberg** [comment]
@sebamoreno2811
Acabo de revisar tu código y también corrí la tarea (vas muy bien!). Le hice los cambios que te sugerí y me funcionó perfecto. De hecho le hice prints y calzaban con los números que habías puesto.

Estos cambios fueron:
atributo = self.label.y() (para saber su ubicación en el eje y)
atributo_2 = self.label.height() (para saber la altura de dicho label)

Si es que eso no te funciona, podrías utilizar lo siguiente para el label:
.geometry().height()
.geometry().y()
.geometry().x()
.geometry().width()

Con esto también me funcionó, espero que esto resuelva tu problema. Si persiste comenta nuevamente y vemos que hacer. Y podrías aprovechar de poner una foto del error que te sale.

**Comment by sebamoreno2811** [comment]
@tomasrosenberg  ahi me funciono perfect, no se porque me tiraba error, gracias!
