### ISSUE TITLE
librería sys

### ISSUE THREAD

**Issue by jirarrazabal** [IIC2233/syllabus#587]
Puedo usar la librería sys para importar la función get_pixels de pixel_collector.py? He intentado otros métodos para importar módulos que se encuentran en carpetas padres y no me funciona. Quiero utilizar la función en un archivo en la carpeta client, cuando pixel_collector.py se encuentra en T03.
Utilicé:
import sys
sys.path.append("..")
Muchas Gracias!

**Comment by Hernan4444** [comment]
Por favor leer y utilizar la issue dedicada a estas preguntas #460
