### ISSUE TITLE
Diagrama de clase actualizado

### ISSUE THREAD

**Issue by cnillanes** [IIC2233/syllabus#587]
Holaa! los métodos extra que hayamos definido en las clases durante el desarrollo del programa, se deben incorporar en el diagrama final?

Gracias!

**Comment by vicentevegaulloa** [comment]
Hola @cnillanes !

Estás en lo correcto. Como dice el enunciado, la versión final del diagrama debe ser una fiel representación de tu programa.

**Comment by cnillanes** [comment]
Y por ejemplo las funciones usadas para la creacion del archivo "resultados.txt" que estan dentro de Campeonato pero como que no se relacionan directamente con las funcionalidades del Campeonato las debo poner de todos modos?

Lo último, debo subir un archivo.md extra para volver a explicar el diagrama final?

**Comment by vicentevegaulloa** [comment]
Deben ir todos los métodos de tus clases por lo que el método que escribe en resultados.txt si debe ir en el diagrama. Respecto a lo último, en el enunciado aparece como "conveniente" y te recomiendo fuertemente que lo hagas para facilitar la comprensión del diagrama 😄
