### ISSUE TITLE
Problemas al correr server y client a la vez

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2233/syllabus#587]
Hola! Cuando corro el codigo del server y del client mi computador se queda "pegado" y la ventana de inicio (o el front en general) no se cargan, es decir aparecen pero quedan en gris, mientras que si corro solo el client la ventana me aparece sin problemas, alguna sugerencia de que puede ser? gracias!

**Comment by gatochico** [comment]
Hola! Podrías subir tu progreso al repositorio para ver en específico tu código?

**Comment by jfuentesg26** [comment]
Si, lo acabo de subir a mi repositorio personal, gracias!

**Comment by gatochico** [comment]
Aunque no pueda asegurarte que el error este específicamente ahí, un detalle que pude encontrar es que dentro de tu cliente no hay un thread dedicado a escuchar al servidor, lo que hace que tu programa no termine de ejecutar todo el código necesario de tu `main` (por ejemplo, lo que sigue después de `cliente = DCCliente()` en main.py del cliente no alcanza a ejecutarse). 

Te recomiendo revisar esta [ayudantía](https://github.com/IIC2233/syllabus/blob/master/Ayudantias/AY08/Ejemplo%20json%20(Japonizador)/cliente/cliente.py) para que veas cómo funciona el trabajar con una interfaz + networking. 

Avísame como te va y éxito!
