### ISSUE TITLE
Formula de entrenamiento

### ISSUE THREAD

**Issue by nogalde** [IIC2233/syllabus#588]
Hola!
No me queda claro como afecta la excelencia y respeto en el entrenamiento, ya que creo que no se específica bien en ninguna parte. Por otro lado, cuando se dice que en IEEEsparta la formula de entrenamiento se pondera por 1.7, significa: puntos obtenidos de ese entrenamieto * 1.7 o puntos totales del atributo * 1.7?
Gracias

**Comment by amparostevens** [comment]
Hola @nogalde !

La fórmula de entrenamiento corresponde simplemente a sumarle PUNTOS_ENTRENAMIENTO al atributo físico, por lo tanto se debería multiplicar __PUNTOS_ENTRENAMIENTO * 1.7__ y eso sumarlo al atributo. 

Dado que __excelencia y respeto__ no están en la fórmula, no afectan.

Éxito con la tarea! 🍄

**Comment by Mamunoz42** [comment]
Hola 

Con esta ponderación que hay que realizar me surge una duda, ya que al hacer esta ponderación los atributos de mi deportista dejaran de ser int, sin embargo en el enunciado dice que es int, yo podría aproximarlos para poder mantenerlos como int?

Saludos :smile:

**Comment by amparostevens** [comment]
Hola @Mamunoz42 !
La issue #333 responde tu pregunta
