### ISSUE TITLE
Duración del turno

### ISSUE THREAD

**Issue by furzuadr** [IIC2233/syllabus#588]
Es necesario que el tiempo que le queda al usuario para jugar aparezca en todos los miembros de la sala o puedo hacerlo solo en el usuario que le toca jugar? Gracias!

**Comment by DCCollao** [comment]
Hola! 
Es necesario que sea visible para todos los miembros de la sala.
Éxito

**Comment by kmhaller** [comment]
hola, es necesario que ese tiempo se duplique si es que el jugador encierra un circulo? o puede mantenerse fijo hasta que termina o el jugador marca una linea que no encierra un cuadrado? No se entiende bien del Enunciado.

**Comment by DCCollao** [comment]
Hola! 
El tiempo no se duplica. Al momento de completar un cuadrado, es como si el jugador que lo completó tuviese otro turno, por lo que su tiempo para jugar se reinicia. 
Espero que esto aclare tu duda
