### ISSUE TITLE
Servidor

### ISSUE THREAD

**Issue by kisco99** [IIC2233/syllabus#588]
¿Puede haber un servidor para cada sala o debe haber un solo servidor?

**Comment by DCCollao** [comment]
Hola!

No sería correcto hacer un servidor para cada sala 😥 la idea es que tu único servidor sea capaz de manejar correctamente varios clientes, y mantener funcionando las salas pedidas. 
Éxito!

**Comment by kisco99** [comment]
Vale gracias!
