### ISSUE TITLE
Eliminar elementos subidos en mi repositorio

### ISSUE THREAD

**Issue by diegogarcia98** [IIC2233/syllabus#588]
Hola!

Hace tiempo subí sin querer el archivo magizoologos.csv y ahora necesito  saber cómo eliminarlo. De momento con mi .gitignore logro que no se suba el enunciado, __pycache__/ y criaturas.csv

Gracias de antemano.

**Comment by aljara97** [comment]
Hola @diegogarcia98, para eliminar un archivo de tu repositorio debes seguir los siguientes pasos:
- Respaldar los archivos de tu tarea en otra carpeta fuera de tu repositorio
- Hacer git pull de tu repositorio
- Usar el comando git rm nombre_archivo
- Luego de eso deberás hacer git commit y luego gitpush como cuando añades nuevos elementos a tu repositorio. Asegúrate que el archivo se encuentre en el `gitignore` o de lo contrario se volverá a subir. 

Espero haber aclarado tu duda, saludos y éxito con lo que queda 🧙‍♂️
