### ISSUE TITLE
Duda pyqt5

### ISSUE THREAD

**Issue by fdominguezclaro** [IIC2233/Syllabus#588]
Tengo una duda sobre como usar los Qtimers. 

En mi tarea 5, el frontend se comunicaba con QObjects que estaban en el Backend, y estos a su vez tenían instanciados sus respectivas unidades o edificios. En cada QObject yo hacia un self.timer = Qtimer() y asociaba ese timer a alguna función para que se corrar cada x milisegundos. Incluso a veces un QObject tenía mas de un QTimer, por que iban asociados a distintas funciones.
Aquí va un ejemplo:

```Python
self.lifetimer = QTimer(self)
self.lifetimer.timeout.connect(self.actualizar_vida)
self.lifetimer.start(50)
```

Es correcta esa forma de usar los QTimers? Pregunto por que si ya lo hice mal en la T05 no quiero cometer los mismos errores para esta otra. 

Gracias!!

**Comment by iqacevedo** [comment]
Hola,
Está correcta tu forma de usar QTimers, así que puedes seguir utilizándolos de esa forma.

Saludos !
