### ISSUE TITLE
datos del juego

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#588]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Sería buena práctica crear un módulo extra (como un parametros.py dinámico) que almacene los datos del juego?

con esto me refiero a literalmente cualquier tipo de dato, por ejemplo la qlabel del personaje elegido, variables comunes a todas las ventanas pero como justamente varían en el tiempo no sería adecuado dejarlas como CONSTANTES_DE_ESTE_FORMATO y que el frontend y backend accedan a ella simultaneamente?

**Comment by catalina-arcila** [comment]
Hola @fernandosmither, Siento que implementar lo que dices es muy fácil caer en uso de variables globales, así que te recomiendo usar otro método, o bien, tener ultra cuidado en no caer en la mala práctica. 😄
Espero haberte ayudado!
