### ISSUE TITLE
Dinero promedio confiscado

### ISSUE THREAD

**Issue by Polea012** [IIC2233/Syllabus#588]
En las medidas de desempeño se encuentra el dinero promedio confiscado debido a la llegada de carabineros. Por dinero confiscado, ¿se refiere al dinero ganado por los vendedores durante el día o el dinero que valía el stock confiscado por los carabineros?

**Comment by iqacevedo** [comment]
Se refiere a lo que valía el stock confiscado por carabineros
Saludos !

**Comment by Polea012** [comment]
Pero si ese el caso,¿ como le asignamos un valor al stock confiscado ?, teniendo en cuenta que el stock es general y no independiente de cada producto (por enunciado). ¿Le entregamos un valor según el producto mas caro, por ejemplo, o segun un promedio de los precios? 
Gracias de antemano!

**Comment by iqacevedo** [comment]
Tú decides cómo asignarle el valor, debes tomar un supuesto razonable (tomar el precio de uno de los productos, el más barato, el más caro, el promedio, lo más lógico). Debes especificar en tu readme lo que supongas.

Saludos !

**Comment by Polea012** [comment]
Entendido, muchas gracias !
