### ISSUE TITLE
Duda Consulta /get recommendation T03

### ISSUE THREAD

**Issue by cristozille** [IIC2233/syllabus#589]
Hola, en el enunciado una de las consultas es /get recommendation pero después en los ejemplos la mencionan como /add recommendation
Cuál de los dos debemos usar? o deberíamos preparar ambos?
Gracias!

**Comment by Dnpoblete** [comment]
Hola @cristozille , efectivamente hubo un error de tipeo, te recomiendo que utilices /get recommendation y que de todas formas lo especifiques en el ReadMe.

Éxito con la tarea! 😄
