### ISSUE TITLE
Moral delegación

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2233/syllabus#589]
Holaa :v:
Quería hacer una consulta sobre la moral que se nos entrega en el `.csv`, ya que al revisar la moral de cada jugador que compone la delegación `IEEEsparta`, me percate que la que viene no es realmente el promedio de la moral de los deportistas, entonces mi consulta es si esta debemos mantenerla hasta que ocurra algo que pueda hacer variar la moral de la delegación o si debemos calcular de inmediato cual es la moral real.

Saludos :smile:

**Comment by jitorcas** [comment]
Hola! @Mamunoz42 

La issue #375 responde a tu pregunta! 
Éxito en la tarea 🏋️‍♀️🏃🏻

**Comment by Mamunoz42** [comment]
Muchas gracias :sparkles:
