### ISSUE TITLE
Entregable de T05 y README T04?

### ISSUE THREAD

**Issue by valeria-adasme** [IIC2233/Syllabus#589]
Como dieron más plazo para la tarea 4, ¿para cuándo quedaría la entrega del README de esta misma tarea?
Lo mismo para el entregable que se pide para la tarea 5 ¿O la fecha que aparece en el enunciado queda igual?

**Comment by depedraza** [comment]
Me sumo a la consulta, el README de la tarea 4 quedaría para algo así como el miércoles a las 13:59?

**Comment by colindom** [comment]
Voy a comentar para UPear esto, porque es posible que algunas partes de mi codigo cambien de aca a mañana.

**Comment by stephichau** [comment]
Hola! El README se entrega hasta 24 hrs después de la entrega, es decir, el miércoles hasta las 13:59. Con respecto al entregable de la tarea 5, queda para el 26 de octubre. 

Saludos!
