### ISSUE TITLE
Duda sobre ventana juego y layaouts

### ISSUE THREAD

**Issue by cseverino99** [IIC2233/syllabus#589]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola estoy haciendo mi ventana de juego a partir de layouts, es decir: es una layaout vertical del menu que aparaece arriba con la vida, el punatje los botones, etc y abajo la imagen con sus personajes y objetos, pero la hacer este layaout me quedan del mismo porte el menu y la imagen, dividen la ventana mitad y mitad y eso se ve molesto además de que no me deja ver la imagen en un tamaño apropiado... que puedo hacer para arreglar esto??

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Juampisaez** [comment]
Holaa @cseverino99 
Estas trabajando en Qt o directamente en el codigo?

**Comment by cseverino99** [comment]
directamente en el codigo!!

**Comment by Juampisaez** [comment]
Uuuh, perfecto.
Ya mira si me preguntas a mi creo que se haria mucho mas facil implementarlo en Qt (en esta [issue ](https://github.com/IIC2233/syllabus/issues/521)hay un par de videos que te podrian ayudar).
Ahora bien, si lo esta implementando en codigo tal vez solamente con un vertical layout no sea suficiente, me da la impresion de que necesitarias hacer mas layouts, tal vez con un horizontal. (ahi el desafio es lograr hacer cada layout y luego mezclarlos).

Espero te sirva, quedo atento si no se entendio algo :)

**Comment by cseverino99** [comment]
Gracias por tu ayuda!! Pero sabes que no me quedo muy claro la parte de hacer más layaouts, no entiendo como hacer otro haria que el menu se viera más chico...

**Comment by Juampisaez** [comment]
Ya mira, imagina que tienes un Qlabel que funcionara de fondo para tu menu (para que se vea beio), y que tambien tienes ya tu layout con la info necesaria del menu (por ejemplo varios layouts verticales unidos en uno horizontal), este layout lo puedes setear a tu label (fondo), con el metodo .setLayout.
Esto es solo para el menu, luego tu debes crear labels aparte para el mapa, y su geometria la puedes setear con .setGeometry().

Espero se entienda mejor, trata de darle una vuelta y si no se entiende me comentas de nuevo :)
