### ISSUE TITLE
problemas identacion Sublime Text

### ISSUE THREAD

**Issue by fddelabarra** [IIC2233/syllabus#589]
Hola, no se que paso pero como que se me desconfiguro sublime o algo asi, me salen errores de identacion, borro todo y lo hago con espacios (me sale que lo hago con tab por alguna razon), y ahora me pasa que al hacer 4 espacios como que se transforma en un tab no se porque, pero eso me causa problemas y no se como arreglarlo

**Comment by Drpinto1** [comment]
¡Hola!

En estos casos es bueno intentar _googlear_ tu problema, probablemente en encuentres una solución :D

En particular para tu duda busqué "sublime 3 convert indentation to spaces" y el primer resultado enseña, con imágenes, cómo resolverla. Puedes encontrarlo en [este link](https://stackoverflow.com/questions/22529265/sublime-text-3-convert-spaces-to-tabs)

Si no logras resolver el problema con esto, pudes comentar esta misma _issue_ explicando la situación, estaré atento para intentar ayudarte. :smile: 

¡Saludos!
