### ISSUE TITLE
Error JSON

### ISSUE THREAD

**Issue by MGilB** [IIC2233/syllabus#589]
Hola, cuando corro mi programa e ingreso o creo una sala, algunas veces, me aparece un error con este código.

`json.decoder.JSONDecodeError: Extra data: line 1 column 134 (char 133)`

Busqué en Google y salía que era porque tenia diccionarios dentro de diccionarios, pero no me hace mucho sentido porque según lo visto en el curso un json es eso.

**Comment by jeschuwirth** [comment]
Hola!

Creo que tienes el mismo error que las issues #577 y #532, avisa cualquier cosa.

Suerte!

**Comment by MGilB** [comment]
Si creo que si, voy a tratar de solucionarlo con lo que dice ahí.
