### ISSUE TITLE
parque lleno

### ISSUE THREAD

**Issue by ciquezada** [IIC2233/Syllabus#589]
Hola, si el parque esta lleno, ¿los nuevos clientes son rechazados y se van, o esperan en algun tipo de cola?

**Comment by santilaguna** [comment]
No soy ayudante pero ya lo preguntaron en otra issue, si me acuerdo bien quedaba a tu criterio.

**Comment by ciquezada** [comment]
por mas que busco la issue no la encuentro, pero cerrar esta issue significa que oficialmente queda criterio supongo

**Comment by Hernan4444** [comment]
#567
