### ISSUE TITLE
Cantidad de caracteres maximos por linea

### ISSUE THREAD

**Issue by juacob** [IIC2233/Syllabus#59]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola buscando en google encontre otro metodo mas simple para partir una linea en 2 que usando el backslash, al hacer un enter despues o antes de un operador se puede dividir la linea en 2, habria problema si usara este metodo? muchas gracias.

**Comment by admiranda** [comment]
Podrías compartir el método.🤧
Gracias

**Comment by juacob** [comment]
> Podrías compartir el método.🤧 Gracias

Es apretar enter despues de un operador en una linea muy larga, la linea se desplaza hacia abajo y python lo sigue considerando como una unica linea. Espero te sirva!

**Comment by Emiliax16** [comment]
Hola! Sí se puede 😄 De hecho es una muy buena idea para no pasar los caracteres máximos permitidos por línea. Saludos!
