### ISSUE TITLE
Error con wsl

### ISSUE THREAD

**Issue by Gaspartby** [IIC2233/Syllabus#59]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema
Al poner wsl --install en la terminal me arroja un error en donde me dice que debo activar la plataforma de maquina virtual y la virtualización en la BIOS. La plataforma de maquina virtual ya la tengo activada pero al intentar activar la virtualización en la BIOS después windows no inicia y se queda cargando o aparece pantalla azul. Ya he activado y desactivado varias veces la virtualización pero no me ha dejado iniciar cuando está activada. He visto varios tutoriales en donde comentan que debo actualizar los windows o los drivers de la cpu pero nada me a funcionado. 

![WhatsApp Image 2023-08-23 at 6 02 33 PM](https://github.com/IIC2233/Syllabus/assets/141886529/b4e458bc-40ee-4abb-95c4-226b3a83f131)

**Comment by Hernan4444** [comment]
Hola @Gaspartby 

Si bien ya has intentado diferentes tutoriales, puedes confirmarnos si estas 4 opciones dichas en la issue #13 ya las probaste?

* https://github.com/IIC2233/Syllabus/issues/13

Además, la segunda opción dice que vayas atu panel de control para activar WSL. Nos confirmas si tambien tienes activado  "Virtual Machine Platform" cómo en la foto

![image](https://github.com/IIC2233/Syllabus/assets/15641721/e3cabc3d-4c15-48b4-b58c-7346c17f06a2)


Quedamos atentos a tus comentarios,
Saludos!

**Comment by Gaspartby** [comment]
hola, gracias por la ayuda.
Sí tengo activado el virtual machine como en la foto y también intenté las 4 opciones del issue #13, pero nada me sirve. 
![WhatsApp Image 2023-08-23 at 9 35 58 PM](https://github.com/IIC2233/Syllabus/assets/141886529/a9ca0cfa-b592-4702-9fb7-2f20734c0350)
![WhatsApp Image 2023-08-23 at 9 38 09 PM](https://github.com/IIC2233/Syllabus/assets/141886529/19102b21-371f-47fc-95a0-986265b6145f)

**Comment by lily416** [comment]
Hola @Gaspartby, 

Espero que te encuentres bien. Con respecto a tu error, estuve revisando las _issues_ del proyecto de WSL y encontré [lo siguiente](https://github.com/microsoft/WSL/issues/7068#issuecomment-1304559607):

> I had this same error as well. Virtualization was enabled in BIOS, Task Manager Performance tab showed it was activated. But still could not get WSL2 to work after many updates and reboots.
> 
> What fixed my problem in the end was:
> * Open Control Panel -> Programs -> Turn Windows features on or off
> * Disable Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform, and Windows Subsystem for Linux
> * Reboot
> * Re-enable the features that were disabled: Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform, and Windows Subsystem for Linux
> * Reboot
> * Open a Administrator Powershell and run:
> `wsl --set-default-version 2`
> `wsl --install -d Ubuntu`
> * And it finally worked
>
> Hope that helps others.


Igualmente, revisa por si acaso que tengas habilitada la virtualización de la CPU. Esto lo puede ver en el Administrador de tareas, en la pestaña de rendimiento:
> ![image](https://github.com/IIC2233/Syllabus/assets/26393515/47853614-62d4-40e5-8085-7448f64e990e)


Espero que lo que indicaron en la _issue_ de WSL te sea de utilidad. Si esa alternativa llega a fallar, entonces te recomiendo que contactes al profesor de tu sección, para coordinar una reunión en la que te ayude con la instalación de WSL o sino evaluar posibles alternativas.

Saludos 👋 🐢

**Comment by Gaspartby** [comment]
Muchas gracias por la ayuda.
Como comentaba en un comienzo, tengo la virtualización desactivada ya que cada vez que me meto a la bios a actuvarla luego no prende el pc, por lo que tengo que volver a desactivarla para que sea posible iniciar Windows correctamente.
