### ISSUE TITLE
Duda readme: a que se refiere con requisitos y donde considerar los modulos

### ISSUE THREAD

**Issue by bicos12** [IIC2233/Syllabus#59]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X]Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### En el archivo README.md a que se refiere el apartado de corrección "Requisitos"?
Tambien respecto al README.md  que hay que poner en la parte de ejecucion? Todos los archivos (modulos, parametros.py, archivos csv), solo nuestros módulos originales u otra cosa. Y la parte de librerias propias debemos poner nuestros modulos.py?

**Comment by ivanvlam** [comment]
Hola @bicos12 ! La parte de requisitos se refiere a que el menú de inicio contenga todas las opciones pedidas en el enunciado, puedes encontrar más información acerca de que significa cada indicador en el [documento de distribución de puntaje](https://docs.google.com/spreadsheets/d/147BEYTTFoa5OE5YtreKxyXbf2vZGRyogP03CZruHNY4/edit?usp=sharing).
Respecto a la parte de ejecución es necesario que especifiques que programa es el que se debe ejecutar y todos los archivos que son necesarios para su funcionamiento, además de sus respectivos directorios, para esta tarea lo más probable es que todos sus archivos se encuentren en la carpeta `T0/`.
Finalmente, respecto a las librerías propias, debes especificar los módulos que creaste para la tarea, además de una breve descripción de su función o contenido.
Espero te sea de ayuda. Saludos!
