### ISSUE TITLE
Usuarios nuevos en seguidores.csv

### ISSUE THREAD

**Issue by rieg-ec** [IIC2233/syllabus#59]
Hola!

tengo una duda, en seguidores.csv los usuarios que no siguen a nadie aparecen igual. Es necesario actualizar seguidores.csv  y usuarios.csv al crear un usuario? o puedo solo guardarlo en usuarios.csv y al momento de seguir a alguien agregarlo a seguidores.csv?

**Comment by KnowYourselves** [comment]
Hola @rieg-ec!

En la sección 5.2 el enunciado dice lo siguiente:

> [...] Por lo tanto el archivo deberá poseer tantas filas como usuarios han sido creados.

Por lo cual todos los usuarios que se registren deben ser ingresados al archivo _seguidores.csv_, aunque no sigan a nadie.

Éxito!
