### ISSUE TITLE
Duda ranking T0

### ISSUE THREAD

**Issue by mane6867** [IIC2233/Syllabus#59]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Ranking tarea

¡Hola!, tengo una duda, cuando el usuario solicita el ranking de juego. Entiendo que el formato queda a libre disposición según el enunciado, sin embargo, no estoy segura de las reglas que debe cumplir y a lo que debe estar preparado mi código, es decir, ¿tengo que estar preparada si solicitan el ranking y no se han terminado 10 partidas?, y si es así, ¿yo decido si no se puede visualizar el ranking o se muestran todas las partidas  terminadas?, además, ¿también tengo que tomar en cuenta el caso en el que en más de una partida se haya obtenido el mismo puntaje? y si es así, ¿yo decido cómo manejarlo?. Quería saber si existen casos correctos respecto a estos puntos.
Muchas gracias

**Comment by victoriaatria** [comment]
Hola! 
Sí, tienes que considerar el caso en que el usuario solicite ver el ranking de puntajes y todavía no existan 10 puntajes para mostrar. En este caso solo se tendría que mostrar el ranking de puntajes hasta el momento (por ejemplo, si hay solo dos puntajes almacenados, se muestran solo esos puntajes de mayor a menor puntaje).

En el caso de que existan dos o más puntajes iguales, queda a criterio tuyo cómo ordenarlo en el ranking. Recuerda especificar eso en tu readme!

Saludos
