### ISSUE TITLE
Duda respecto a puntuación de una partida guardada

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#59]
Hola si yo tengo una partida guardada y la termino que pasaría si yo la vuelvo a cargar y la termino de nuevo con respecto a los puntajes que tendría que guardar 
Guardo ambas puntuaciones con el mismo nombre de usuario, remplazo la primera por la segunda o dejo la de mayor puntaje entre ambas en el archivo puntajes?

**Comment by KnowYourselves** [comment]
Hola @JuaniAndres!

Eso queda a tu criterio. Implementa la que te acomoda más y recuerda especificar eso en tu `README`!

Éxito!

**Comment by JuaniAndres** [comment]
ya muchas gracias
