### ISSUE TITLE
Retornar None en tablero no solucionable (función solucionar_tablero)

### ISSUE THREAD

**Issue by pulpaulaa** [IIC2233/Syllabus#59]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado de la tarea se indica en la función solucionar_tablero lo siguiente: "En caso que el tablero no tenga solución, esta función debe retornar None". Y en la parte de "Solucionar tablero" en el menú de acciones, indica: "completa el tablero asegurando que se cumplan las Reglas 1, 2, 3 y 4. Luego, guarda el tablero en un archivo con el nombre original de este junto con el sufijo "sol". Por ejemplo, si el tablero era el "Archivo1.txt", el nuevo tablero se llamará "Archivo1_sol.txt". Finalmente, se debe notificar por consola si el tablero se pudo solucionar o no. En caso de tener solución, se deberá mostrar el tablero resuelto en consola".

Teniendo esto en cuenta, le pregunté hoy en la sala de ayuda de la Tarea 0 al profesor de mi sección si al tener un caso NO solucionable, se debe crear un archivo de igual manera o no. El profesor me indicó que debía crear un archivo "sol" que solo tuviera "None" dentro de él, pero me dijo que preguntara acá igual. Entonces, **¿el archivo "sol" solamente se debe crear en caso de que el tablero sea solucionable o debo crear un archivo que contenga "None"?**

**Comment by terelopezc** [comment]
Hola @pulpaulaa! En el enunciado está mencionado que en el caso de que un archivo de tablero no se pueda solucionar, basta con que la función retorne "None" y no es necesario crear ningún archivo extra. En el caso de que igual quieras hacerlo, puedes dejarlo especificado en tu Readme para que el ayudante que te corrija sepa. No olvides eso si cumplir con lo que pide el enunciado! 

<img width="702" alt="Captura de Pantalla 2023-03-23 a la(s) 15 54 52" src="https://user-images.githubusercontent.com/48325070/227322548-5eea369c-caf5-4275-89d6-7be3934e86a3.png">

**Comment by Hernan4444** [comment]
Hola @pulpaulaa 

Para complementar, aquí ocurre que el menú te pide la opción de "solucionar tablero" que lo soluciona y lo guarda, es decir, ocupa 2 de las funciones que les pedimos "`guardar_tablero`" y "`solucionar_tablero`".  Por lo tanto, no es obligatoria que selccionar una opción del menú deba llamar a una de las funciones que nosotros les pedimos. Pueden incluir funciones que comunican el menú con las nuestras.

Saludos c:

**Comment by Mcroquevielle** [comment]
Hola! Entonces en caso de que el tablero no sea solucionable podría no guardar ningun tablero? Y imprimir un mensaje de error, por ejemplo?

**Comment by Hernan4444** [comment]
Hola @Mcroquevielle 

Así es, lo que quieres hacer es válido. 

Por un lado, lo importante es que la función `solucionar_tablero` retorne None en caso no haber solución. 

Por otro lado, si durante la ejecución de tu programa (por consola), decido utilizar la opción de solucionar tablero, llamas a la función que te pedimos. Si esta retorna None, queda a tu criterio si creas a no un archivo con None. Solo nos importa, según  el enunciado, que cuando **si se encuentras una solución** esta debe ser guardada en el archivo correspondiente.

Saludos c:

**Comment by tnaspee** [comment]
Tengo una duda relacionado con esto:
En el enunciado dice que no podemos cambiar las funciones, ni lo que retornan. Pero solucionar_tablero tiene un type hint de que retorna una list. En caso de retornar None, esto arroja un error de Pylance. Osea que el código corre pero me molesta el error. Será posible hacer una excepción con esta función y borrar el -> list?

**Comment by Hernan4444** [comment]
Hola @tnaspee 

No hay problema con eliminar esa parte. Al final solo se usaba para explicitar que el tipo de dato retornado era lista. 

Saludos c:
