### ISSUE TITLE
duda avance [lista de objetos], [atributo de una clase], [diagrama de clases]

### ISSUE THREAD

**Issue by JupaOlivares** [IIC2233/syllabus#59]
Hola!

cuando tengo que señalar los atributos de una clase en el diagrama de clase, si un atributo esta conformado por una lista de objetos de una cierta clase, lo señalo como "list" o "ObjetoClaseX"?

salu2

**Comment by roberto009** [comment]
Hola!
No hay problema mientras se entienda que es una lista de esos objetos.
Puedes hacer:
`nombre_lista = Objeto []`
`nombre_lista = list(Objeto)` 
`nombre_lista = [Objeto]
Éxito con el diagrama !
