### ISSUE TITLE
extinción de incendio

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#59]
Ir extinguiendo un incendio se traduce en una disminución de su radio?

Parece obvia la respuesta, pero nunca se sabe.

**Comment by rpalmaotero** [comment]
La verdad es que no te importa mucho el radio para determinar el grado de extinción. Lo que realmente determina la extinción de un incendio son sus puntos de poder.

**Comment by negutierrez** [comment]
Pero los puntos de poder están relacionados directamente con el radio (puntos de poder = Area * potencia).
Al empezar a extinguirse el incendio, se podría asumir que la propagación baja a cero?

**Comment by rpalmaotero** [comment]
@negutierrez no puedes asumir eso.

**Comment by negutierrez** [comment]
Podemos asumir entonces que los recursos trabajan sobre los puntos de poder disminyendo la propagación en vez de la potencia? Esto me parece más intuitivo, ya que sería como que los recursos empiezan a operar sobre los bordes del incendio.

**Comment by rpalmaotero** [comment]
@negutierrez el incendio tiene una tasa de propagación `x`, que está dada por la tasa de propagación base, meteorología, etc. La tasa de propagación agranda el radio de la zona afectada. La zona afectada multiplicada por la potencia son los puntos de poder del incendio. Los recursos tienen un atributo `tasa_extincion` que son los puntos de poder que apagan en una hora. Si la tasa de puntos de poder que pierde un incendio por hora es más grande que la tasa de aumento de puntos de poder por hora, el incendio eventualmente llegará a cero puntos de poder y se extinguirá. Se entiende?

**Comment by gbordoni** [comment]
@negutierrez Pero el problema es que la tasa de propagación x no es constante en el tiempo; esta varía hora a hora dependiendo de los eventos meteorológicos que el incendio se va encontrando mientras se agranda, y de los pronosticos que ya estan afectando al incendio y que terminan, etc
Entonces para calcular una estrategia de extinción 100% correcta de acuerdo a lo que dices, habría no solo que proyectar cual va a ser la tasa del incendio una vez que lleguen los recursos que **potencialmente** voy a mandar, sino que también ir simulando y estimando cual va a ser la tasa durante **todas** las horas que los potenciales recursos esten en el incendio, revisando todos los eventos meteorológicos que hipoteticamente afectarían al incendio con los recursos trabajando en este... Y estamos hablando de simular todo eso para cada recurso disponible para poder recién definir la estrategia jajaja

De verdad creo que le falta alguna restricción, onda considerar solo el radio y puntos de poder que tiene el incendio al momento de calcular la estrategia y de ahi dejarlos estaticos o algo por el estilo

**Comment by yoavnavon** [comment]
@rpalmaotero Estoy de acuerdo con @negutierrez , ya que si se sigue un analisis "continuo" como se pide, los puntos de poder se deberian recalcular momento a momento, y no existe ninguna manera de disminuir el radio de un incendio. Es decir, independiente de si un recurso X le quita Y puntos de poder a este incendio, sus puntos de poder serian [(Pi *Radio^2*Potencia) - Y]. Si no hay manera de disminuir el radio, los puntos de poder nunca van a llegar 0, y no tiene sentido que siga participando la tasa de propagacion, ya que aún anulando dicha tasa te quedará siempre un radio (que equivale a puntos de poder). Entonces, a mi manera de ver para que el problema tenga sentido, una vez que se alcanza una tasa de propagacion = 0, y por ende se empieza a apagar el incendio, los puntos de poder se calculan como el ultimo radio que alcanzo, y de ahi se van restando. Finalmente, el restar puntos de poder significaria inevitablemente que el radio disminuye.

**Comment by rpalmaotero** [comment]
@gbordoni No necesitas calcular necesariamente **minuto a minuto**/**hora a hora** las condiciones del incendio. Sólo cuándo la tasa de propagación cambie (producto de aplicar un recurso o alcanzar un nuevo pronóstico meteorológico) y ver cuánto tiempo va a seguir con esa condición para ver la variación en los puntos de poder.

@yoavnavon Es más simple: tal como dices, los puntos de poder actuales de un incendio van a ser los que correspondan a los calculados mediante la fórmula menos los puntos de poder apagados por todos los recursos aplicados. Cuándo los puntos de poder apagados sean mayores o iguales a los de la fórmula el incendio va a estar apagado.

**Comment by rgriver** [comment]
![tumblr_inline_ogiit4sfxx1qhib83_500](https://cloud.githubusercontent.com/assets/22522629/24159931/3fb74448-0e3f-11e7-9f77-8ee1ab664d75.jpg)
